### ISSUE TITLE
option to mantain the braces and special commands in titles or all fields

### ISSUE THREAD

**Issue by biccari** [retorquere/zotero-better-bibtex#100]
I have noticed that after importing a BibTeX file, all the braces are stripped.
For example, if I have a chemical formula in the title, for instance "A New Study on {H$_2$O}", the imported entry becomes "A New Study on H&lt;sub>2&lt;/sub>O".

When this is exported in BibTeX format again, it can become
"A New Study on H\ensuremath{&#95;{2}}O"
or, if the braces option is set,
"{A New Study on H\ensuremath{&#95;{2}}O}"

However both solutions are not perfect. Since BibTeX typically change all to lowercase, in the former case I have lost the capitalization of the H and O, whereas in the latter I obtain all the capital letters as is, without the possibility of a homogeneous capitalization between the titles of the references.

A similar problem occurs with other commands in the title. The slashes and the braces are stripped, while the command name are left. 

For all these reasons, is it possible to introduce an option in the preferences in order to avoid any processing of the BibTeX fields during import/export?

Thank you.

**Comment by earcanal** [comment]
FWIW, I used the ```#LaTeX``` tag to solve my issue of (APA) capitalization of proper nouns, eg. in ```Extra``` field

```bibtex[title=Computational analysis of present-day {A}merican {E}nglish]```

Without it, the curly braces get escaped.  Is there a better way of doing this?

**Comment by retorquere** [comment]
I don't understand. What is it that you see happening, and how would you like things to be different?

**Comment by earcanal** [comment]
AIUI, the apa6 style lowercases all words in the title, but APA requires that some words (including proper nouns) are capitalised.  I can accommodate this by customizing the title field (see above) but *only* if I set a #LaTeX tag on the item.  Without that tag I get escaped curlies in my .bib, i.e.

```title = {Computational analysis of present-day \{A\}merican \{E\}nglish}```

It would be convenient for me if I didn't have to add the tag, but I guess this may break things for others.

**Comment by retorquere** [comment]
Why not just set "preserve capitals" to "all"?

**Comment by earcanal** [comment]
That's the 'better way' I was looking for.  Thanks :)
