### ISSUE TITLE
Different cite keys on two laptops better-bibtex / webdav sync original laptop

### ISSUE THREAD

**Issue by rhaynes74** [retorquere/zotero-better-bibtex#1000]
Hi folks,  I think I have submitted an error report  G2TPR5EL, will post a similar report from laptop #2 shortly.  

The basic story is that I have different cite keys on both laptops but can't figure out why.    Both laptops have same version of better-bibtex installed and same settings (as far as I can tell).

Best,
R Haynes

**Comment by retorquere** [comment]
This installation has pattern ` [auth][title][year]` (including leading space, but that would be ignored); it has keys like `EzquerroPicardIterationsIntegral2008`. This seems generated by a pattern like `[auth][shorttitle3_3][year]`. Can you try selecting all your items from the toplevel in the library, right-clicking, and selecting `BBT->Refresh`. The main way I can think of that this would happen is if you had something like `[auth][shorttitle3_3][year]` set, then synced in your library, and then changed the pattern. When the pattern is changed, references do not automatically update.
