### ISSUE TITLE
Different cite keys on two laptops better-bibtex / webdav sync, 2nd new laptop

### ISSUE THREAD

**Issue by rhaynes74** [retorquere/zotero-better-bibtex#1001]
Hi folks, here is the 2nd reference number NQARDNP5

As mentioned in the other thread, the basic story is that I have different cite keys on both laptops, but can't figure out why.  Both laptops have the same version of better-bibtex installed and the same settings (as far as I can tell).  

Laptop #2  gives author_veryshorttitle_year while laptop #1 gives authorSlightlyLongerTitleYear with no underscores. 
Best,
R Haynes

**Comment by retorquere** [comment]
There's no folks, just me. I'll have a look when I get home.

**Comment by retorquere** [comment]
Which of the two has the orange field, and which has the empty field?

**Comment by retorquere** [comment]
And which of the issues is laptop 1, and which is laptop 2?

**Comment by retorquere** [comment]
This has pattern `[auth][title][year]` (no space like in #1000). Same here, can you select-all, then right-click and `BBT->Refresh`?

**Comment by rhaynes74** [comment]
Hi - many thanks for your responses.  By setting the cite key pattern the same on both machines, selecting all and then finding the betterbibtex option in the menu (that was what I was missing) then I was able to match them up.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

**Comment by retorquere** [comment]
So solved then?

**Comment by retorquere** [comment]
Both this and #1000?

**Comment by retorquere** [comment]
What about the empty/orange fields?

**Comment by rhaynes74** [comment]
Orange indicated that I didn't have correct syntax in the field. Blank because I must have deleted the entry.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Emiliano Heyns <notifications@github.com> Date: 2018-06-25  5:14 PM  (GMT-03:30) To: retorquere/zotero-better-bibtex <zotero-better-bibtex@noreply.github.com> Cc: rhaynes74 <rhaynes74@gmail.com>, Author <author@noreply.github.com> Subject: Re: [retorquere/zotero-better-bibtex] Different cite keys on two laptops better-bibtex / webdav sync, 2nd new laptop (#1001) 
What about the empty/orange fields?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/retorquere/zotero-better-bibtex","title":"retorquere/zotero-better-bibtex","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/retorquere/zotero-better-bibtex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@retorquere in #1001: What about the empty/orange fields?"}],"action":{"name":"View Issue","url":"https://github.com/retorquere/zotero-better-bibtex/issues/1001#issuecomment-400071883"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/retorquere/zotero-better-bibtex/issues/1001#issuecomment-400071883",
"url": "https://github.com/retorquere/zotero-better-bibtex/issues/1001#issuecomment-400071883",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [retorquere/zotero-better-bibtex] Different cite keys on two laptops better-bibtex / webdav sync, 2nd new laptop (#1001)",
"sections": [
{
"text": "",
"activityTitle": "**Emiliano Heyns**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@retorquere",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"retorquere/zotero-better-bibtex\",\n\"issueId\": 1001,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"retorquere/zotero-better-bibtex\",\n\"issueId\": 1001\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/retorquere/zotero-better-bibtex/issues/1001#issuecomment-400071883"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349837874\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by retorquere** [comment]
I know that's what orange means, I built it that way :rofl: but those two patterns should not have triggered orange.

**Comment by rhaynes74** [comment]
Hi  - orange appears until correct syntax is entered :-) Once I entered a correct string then all was well.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

**Comment by rhaynes74** [comment]
Solved!
