### ISSUE TITLE
Error report submission is very slow.

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#1002]
This is a follow-up of the [author's attribute discussion](https://forums.zotero.org/discussion/72540/user-defined-authors-attribute-field#latest) on Zotero Forums. 

It has been proposed that `Creator: Last || First A. || Type` format support should be added to BBT so that users can define their own authors' attributes that map to the `authortype` field in Bibtex via the Zotero `Extra` field. 

This feature would be useful particularly for academics who write and cite works in Chinese, as elaborated over [here](https://github.com/citation-style-language/zotero-bits/issues/82#issuecomment-400202631).

**Comment by sati-bodhi** [comment]
The error report is taking a very long time to submit. Meanwhile, here are the biblatex entries. 

# Current biblatex entry: 
```
@mvbook{何晏LunYuJiJieYiShu1991,
  langid = {Chinese},
  location = {{臺北市}},
  title = {論語集解義疏},
  edition = {知不足齋民國本，民國十一年(1921)上海古書流通處據鮑氏刊本景印},
  volumes = {十卷},
  publisher = {{廣文書局}},
  date = {1991},
  author = {何晏, 集解 and 皇侃, 義疏}
}
```
# Proposed behavior: 
```
@mvbook{何晏LunYuJiJieYiShu1991,
  langid = {Chinese},
  location = {{臺北市}},
  title = {論語集解義疏},
  edition = {知不足齋民國本，民國十一年(1921)上海古書流通處據鮑氏刊本景印},
  volumes = {十卷},
  publisher = {{廣文書局}},
  date = {1991},
  author = {何晏 and 皇侃}
  authortype={集解  and 義疏}
}
```

**Comment by sati-bodhi** [comment]
Pardon me, since I am actually new to Biblatex (just switched over from Word to Markdown for my academic writing), would the proposed data structure map to this in my citation? 

>何晏集解，皇侃義疏，《論語集解義疏》。

i.e. `[author1][authortype1]，[author2][authortype2]，《title》。` 

I can see from [here](https://tex.stackexchange.com/q/62418/165606) that it works for single authors.

**Comment by retorquere** [comment]
Did you right-click the whole library (that could take a while) or just those that one reference (should be really quick)?

**Comment by sati-bodhi** [comment]
I clicked just one reference - the one I illustrated above. It took ages the last time I tried to submit one as well. I think that one didn't pull through...

**Comment by retorquere** [comment]
I don't know why it's so slow for you -- I just tried to submit a report for a single ref and it's near instantaneous.

I honestly have no idea what that stackexchange link tries to explain. I don't understand biblatex as well as some would assume.

@njbart?

**Comment by sati-bodhi** [comment]
Zotero says 'Network error' when I force it to shutdown after being unresponsive for a while.

**Comment by sati-bodhi** [comment]
It doesn't seem to work. Can I just attach a file with text from the error report over here?

**Comment by retorquere** [comment]
Sure, if it's just a .txt file. But can you try downloading https://github.com/retorquere/zotero-better-bibtex/releases/download/release/error-report.html, opening it, and submitting your file through that? That should do the same, I'm curious to see why you can't submit logs as per usual. The upload through this won't give any feedback unless there's an error though.

**Comment by sati-bodhi** [comment]
It's done. 
`Generated on 20180626T000153Z`

**Comment by retorquere** [comment]
Nothing out of the ordinary in the log. I'm actually looking for an export using `BetterBibTeX JSON`. That's what BBT does when you submit an error log by right-clicking a reference.

**Comment by sati-bodhi** [comment]
Is there anything else I need to do? 

dstillman says that: 
> BBT issues should be reported to the BBT developer on GitHub. 

on the Zotero forum where I reported the submission issue...

**Comment by sati-bodhi** [comment]
I experimented a bit with the proposed Biblatex formula. Apparently, the `authortype` field does not register in CSL. So I would still have to find a way to combine the separated strings into a single `author` variable eventually. 

![default](https://user-images.githubusercontent.com/7592695/41927375-a8f7c69a-79a4-11e8-94fa-9b600ae8e9e5.png)

It says here in the Biblatex manual that the field is 
> Not used by the standard bibliography styles.

**Comment by retorquere** [comment]
Wrt the error submission, please enable extended debugging, and try to submit a bbt error log from the help menu. If it doesn't work, save the log contents to a text file and attach it here.

**Comment by retorquere** [comment]
that screenshot is correct. Does the error submission screen not come up?

**Comment by retorquere** [comment]
If author type isn't actually commonly used, perhaps the stackexchange answer is better. But I don't know what's proposed there, really.

**Comment by sati-bodhi** [comment]
The Debug ID is D720330192.

**Comment by sati-bodhi** [comment]
Then this error popped up: 

![default](https://user-images.githubusercontent.com/7592695/41940500-7a2374f0-79cb-11e8-8712-65d3978791b9.png)

**Comment by retorquere** [comment]
That ID is for reports sent to Zotero, I can't read those. You need to use "Help->Report Better BibTeX Errors".

**Comment by sati-bodhi** [comment]
As with the Stackexchange answer, I think it simply says that `authortype` is meant to be printed, so an alternative solution is proposed.

**Comment by sati-bodhi** [comment]
Finally it went through...
The report ID is: LA62UE64

**Comment by retorquere** [comment]
No weird things in the log. Can you try again by right-clicking that reference?

**Comment by sati-bodhi** [comment]
I think I have found a working solution to my own problem without the hack: I shall keep the corrupt data in the `Extra` field like so: 

![default](https://user-images.githubusercontent.com/7592695/41942001-5e8c0b8a-79d0-11e8-9f5b-6266b5b2a006.png)

This makes it easy to segregate good data from the working solution so that I can have a functioning citation without losing data integrity.

**Comment by sati-bodhi** [comment]
The wizard.advance error popped up again. Reference error report is still taking a long time to submit...

**Comment by sati-bodhi** [comment]
G2SVB23R

**Comment by retorquere** [comment]
No I dont mean that cmd-quit causes any errors, but there's a known error in bbt when zotero is not closed using cmd-quit, and that could explain the wizard.advance problem at least.

**Comment by sati-bodhi** [comment]
The `wizard.advance` popped up in the middle of some of my sessions. Zotero has been restarted couple of times, sometimes with cmd-Q, sometimes through the error report for error logging. I cannot say for sure how it is related to cmd-Q...

The last restart was through the error log.

**Comment by retorquere** [comment]
With "in the middle of my sessions" you mean you were using zotero normally (not submitting any error) and that it just popped up? 

With cmd-Q I just mean that there's a known problem with BBT if you close zotero with the red dot (close window) rather than cmd-Q or restart through the debug window (close app). The wizard.advance problem could be related to that, but only if you've closed zotero using the red dot *and* then tried to submit an error log. If one of those two is not true for you than I have no idea where the wizard.advance problem comes from yet.

**Comment by sati-bodhi** [comment]
I was in the mist of submitting the errors when `wizard.advance` popped up. I guess you are right, then. Because Zotero's been restarting either with cmd-Q or with the red dot or with the debug log for quite a few times when that happened. The first time it was just the `no network connection` error.

**Comment by retorquere** [comment]
No, that's not what I said; it's important to get this right otherwise I can't debug the problem.

If you restart with cmd-Q the problem should *not* appear. If you close with the red dot and reopen then the problem *might* appear (there is a known problem of bbt misbehaving after a red-dot close and reopen).

I need to know which of these you are experiencing. Maybe both, I can't tell from the description.

**Comment by sati-bodhi** [comment]
ITGXXRJ9

**Comment by retorquere** [comment]
Can you submit twice in a row? Do you still see the slowness /wizard.advance error?

**Comment by sati-bodhi** [comment]
The process is real slow, but the error didn't pop up.

**Comment by sati-bodhi** [comment]
When BBT requested to restart Zotero for debug logging again, this error came up: 

![default](https://user-images.githubusercontent.com/7592695/41969407-e2912320-7a39-11e8-9e29-816bd04e32cc.png)

**Comment by retorquere** [comment]
So let me see if I understand correctly:

1. You right-click, select "BBT->Submit error report"
2. You get a message stating "Zotero debug logging is currently disabled. It will be easier to diagnose the problem if you enable it before submitting an error report."
3. After you click OK to restart, but before Zotero actually restarts, you get this error popup?

Or something else? Can you give me the detailed step-by-step you're going through to get this?

**Comment by retorquere** [comment]
Can you also still do the two-times-in-a-row submission? The 2nd submission will have debug info on the first.

**Comment by sati-bodhi** [comment]
Yes, I think you got the process right.

**Comment by sati-bodhi** [comment]
We need to give Zotero some more time to submit the second report.

**Comment by retorquere** [comment]
The thing I don't understand is how you get the `wizard.advance` error. I don't see it, and the only code that triggers it lives on the pane that is shown after you give it permission to send. If you click the "restart" button, you never get to the permission page, so I really don't know who is calling that advance.

**Comment by retorquere** [comment]
I also don't know why it's so slow. Your reports really aren't so big, and with the error-report.html (which does the same thing) you say it's pretty fast.

**Comment by sati-bodhi** [comment]
The error report didn't pull through. It ended with the same invalid response error above. 

I am submitting through the html you sent to me a day ago. 2 files from successive error reports have just been uploaded. Do take a look.

**Comment by sati-bodhi** [comment]
It seems that the original concern for the support of a new format is not a priority anymore. 
Should we change the title of this issue to more accurately reflect what we are dealing with over here? Or would it be better for me to raise a new issue?

**Comment by retorquere** [comment]
I see timeouts in the S3 logs, but I still don't know why -- I'm not seeing it, and if you use error-report.html the reports go through. Looks like I'll have to dust off the macbook to see if it's maybe a mac-specific issue.

**Comment by retorquere** [comment]
It's not MacOS perse; I've just submitted a report without issue from macOS. I do see timeouts in the S3 logs where the reports are stored, but that'd mean (I think) that it times out on your end... which doesn't make sense since a normal form submission just goes through.

Do you have any other Zotero add-ons installed?

**Comment by sati-bodhi** [comment]
![default](https://user-images.githubusercontent.com/7592695/42040797-0cc439b8-7b23-11e8-972d-1c5d757344ae.png)
Here are all the add-ons I have.

**Comment by retorquere** [comment]
Can you try disabling all but BBT to see if that makes a difference?

**Comment by sati-bodhi** [comment]
Makes no difference. I've just sent 2 more error reports. Please take a look.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.152.7253](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.152.7253.xpi) ("more logging").

**Comment by retorquere** [comment]
I've looked at the logs but I don't even see the log submissions starting. Can you try again with 7253? I really need 2 submissions in a row, at least the first with the built-in error report, even if that takes a very long time or aborts with an error. Otherwise I can't see where it's errorring out.

**Comment by sati-bodhi** [comment]
This is the first submission, similar to `error_report5.txt`
PHDUT9IH

**Comment by sati-bodhi** [comment]
The second submission hanged with this error. 
![default](https://user-images.githubusercontent.com/7592695/42074107-f5bcd106-7b9c-11e8-9fff-9703209deb79.png)

**Comment by sati-bodhi** [comment]
I am submitting the second one through `error_report6.txt`

**Comment by sati-bodhi** [comment]
This error is persistent when the error reports don't get through.

**Comment by sati-bodhi** [comment]
The report that didn't make it through has been submitted as `error_report7.txt`

**Comment by retorquere** [comment]
Do you use a proxy of any kind?

**Comment by sati-bodhi** [comment]
Not that I am aware of - How to check?

**Comment by retorquere** [comment]
Is it correct that your IP address ends with `.33`?

**Comment by retorquere** [comment]
You are not restarting Zotero between these attempts? I'm seeing an attempt to submit in PHDUT9IH, but not in report6 or report7, where I would have expected the exact opposite.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.152.7259](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.152.7259.xpi) ("is Zotero for macOS built on an older FF?").

**Comment by retorquere** [comment]
With 7259, please submit an error report and after that, look in the error log (from the help menu) and find lines with `ErrorReport::`. If you can post those here (that's what I am looking for in the 2nd report), that should tell me something.

I really don't know what's going on at your end.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.152.7300](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.152.7300.xpi) ("submit to other host").

**Comment by retorquere** [comment]
I'm still interested in the `ErrorReport::` lines from 7259 after trying to submit, but can you also try 7300? 7300 will submit to a different host, just curious to see if the problem is structurally on your PC or something between the host and your PC.

**Comment by sati-bodhi** [comment]
The IP is correct

**Comment by retorquere** [comment]
Then you're not going through a proxy.

**Comment by sati-bodhi** [comment]
6XYU9SKV
This is for 7259

**Comment by sati-bodhi** [comment]
The error report has 38387 lines and is taking a very long time to load as well.

**Comment by retorquere** [comment]
6XYU9SKV is the second submit? I need either the 2nd submit, or the ErrorReport lines after the 1st commit.

When you say it is taking a very long time as well, is that from 7259 or from 7300?

**Comment by sati-bodhi** [comment]
It is the second submit after 7259, from the error log

**Comment by sati-bodhi** [comment]
FCCHJCUH
This is the second one from 7259. Can't say if it can be considered as 'consecutive' or not. (probably not)

**Comment by sati-bodhi** [comment]
I think 7259 doesn't take quite as long to submit error reports.

**Comment by sati-bodhi** [comment]
D24EVMHN
This is also from 7259, right after FCCHJCUH. 

Don't think I am able to provide the `ErrorReport::` because it is taking very long to load.

**Comment by retorquere** [comment]
Nothing's changed in 7259 that would affect submission speed. 7300 might, because that version submits to a different log host.

There's nothing in either D24EVMHN or FCCHJCUH, but I'm seeing indications that Zotero restarted between those two -- is that correct? I need those two consecutive reports, directly after each other, without restart between them.

**Comment by sati-bodhi** [comment]
M49DTZUW
This is the consecutive without restart after D24EVMHN

**Comment by retorquere** [comment]
Wow, so if I'm interpreting that log correctly, it takes about 7 *minutes* to submit those logs?

How about 7300?

**Comment by sati-bodhi** [comment]
7300 is taking much longer...

**Comment by retorquere** [comment]
And only one of 3 came through even so. And these aren't astoundingly large files, just some 40MB.

I'm waiting for feedback on an [alternative way](https://groups.google.com/forum/#!topic/zotero-dev/JDFQjc9pP8w) to submit the logs but that requires feedback from the Zotero devs, They're usually very busy so that may take some time.

I'm looking into more alternatives, but since I can't replicate this at all at my end, I don't really have many solid ideas at this stage.

**Comment by sati-bodhi** [comment]
The last 7300 submit ended up with a `type.wizard is not a function` error.

**Comment by retorquere** [comment]
That error is literal? There is no `type.wizard` in my code.

**Comment by sati-bodhi** [comment]
It just popped up when the submission is automatically aborted.

**Comment by retorquere** [comment]
but you're sure it says `type.wizard`? Because that's not in BBT nor is it anywhere in Zotero.

**Comment by sati-bodhi** [comment]
Yes, I am pretty sure. Here is the resultant BBT error log: 
```
[JavaScript Error: "Unix error 14 during operation stat (Bad address)" {file: "(unknown module)" line: 0}]
[JavaScript Error: "Unix error 14 during operation stat (Bad address)" {file: "(unknown module)" line: 0}]
[JavaScript Error: "Unix error 14 during operation stat (Bad address)" {file: "(unknown module)" line: 0}]
[JavaScript Error: "Unix error 14 during operation stat (Bad address)" {file: "(unknown module)" line: 0}]
[JavaScript Error: "The connection to wss://stream.zotero.org/ has terminated unexpectedly. Some data may have been transferred." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "The connection to wss://stream.zotero.org/ has terminated unexpectedly. Some data may have been transferred." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "Unix error 14 during operation stat (Bad address)" {file: "(unknown module)" line: 0}]
[JavaScript Error: "Unix error 14 during operation stat (Bad address)" {file: "(unknown module)" line: 0}]
```

**Comment by retorquere** [comment]
It's just that the last error that popped up for you (wizard.advance) actually occurs in the code, and that's how I've always seen it. This one I can't find anywhere.

**Comment by retorquere** [comment]
The only pointer I could find on the unix error 14 is [this](https://forums.zotero.org/discussion/72407/word-plugin-doesnt-update-in-text-citation-numbers).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.152.7371](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.152.7371.xpi) ("use zotero request module").

**Comment by retorquere** [comment]
What does a traceroute to `s3-eu-central-1.amazonaws.com/` show?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.152.7377](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.152.7377.xpi) ("post to slack").

**Comment by retorquere** [comment]
Can you try 7377?

**Comment by retorquere** [comment]
Which [Amazon Simple Storage Service (Amazon S3)](https://docs.aws.amazon.com/general/latest/gr/rande.html) is closest to where you are?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.159.7454](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.159.7454.xpi) ("direct put to S3").

**Comment by sati-bodhi** [comment]
Asia Pacific (Singapore)

**Comment by retorquere** [comment]
Can you try with the latest release (5.0.164)?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7495](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7495.xpi) ("submit error logs to ap-southeast-1").

**Comment by retorquere** [comment]
And can you also try 7495?

**Comment by retorquere** [comment]
And can you get me the output of http://www.cloudping.info/ ?

**Comment by sati-bodhi** [comment]
T9ME49NU
This is from the new release.

**Comment by retorquere** [comment]
With new release you mean 5.0.164, or 5.0.164.7495? How long did it take?

Remember I can only see submission timing in the second consecutive attempt. The log to send is assembled just before being sent out, so the actual timing can not be part of it; the second submission reports the timing of the previous report.

5.0.164.7495 will submit to Singapore instead of Frankfurt and I'm curious to see if that makes a major difference.

**Comment by sati-bodhi** [comment]
JWB6J79Z
This is the subsequent report from the new release 5.0.164

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7501](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7501.xpi) ("log submit timing").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7504](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7504.xpi) ("auto-select s3 bucket").

**Comment by retorquere** [comment]
7504 should auto-select Singapore for you. Please try two submissions with that without restart in between, but also tell me approximately what time you experienced the submissions took, roughly.

**Comment by sati-bodhi** [comment]
I think 5.0.164 did better

**Comment by retorquere** [comment]
Is it correct that your library has 12k items? That would probably take some time to submit.

**Comment by sati-bodhi** [comment]
yes. my library has 12k items. I am still waiting for 7504 to complete the first submit.

**Comment by sati-bodhi** [comment]
![default](https://user-images.githubusercontent.com/7592695/42421161-8daf7190-8303-11e8-8a6e-b025756b05ba.png)

It is this error, once again.

**Comment by sati-bodhi** [comment]
That was from the failed 7504 submission.

**Comment by retorquere** [comment]
Would it be possible to get me a copy of your Zotero DB?

**Comment by retorquere** [comment]
You can drop it [here](https://retorquere.filepiper.com/better-bibtex). Zotero must be closed to do this safely, the DB must not be in use.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7510](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7510.xpi) ("more info in error popup").

**Comment by retorquere** [comment]
It's not there. No idea what went wrong. Can you try this:

`time curl -X PUT -T zotero.sqlite -H "x-amz-acl: bucket-owner-full-control" -H "x-amz-storage-class: STANDARD" https://better-bibtex-error-reports-62200312-apse1.s3-ap-southeast-1.amazonaws.com/zotero.sqlite`

in a shell in the directory where zotero.sqlite lives (on one line, and when Zotero is not running -- use cmd-Q is you're on Mac) and tell me what it reports?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7517](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7517.xpi) ("S3 doesn't like redirects").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7520](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7520.xpi) ("maybe it was a race condition?").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7547](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7547.xpi) ("minor cleanup").

**Comment by retorquere** [comment]
I may have found a race condition -- can you try 7547?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7559](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7559.xpi) ("smaller logs").

**Comment by sati-bodhi** [comment]
time curl -X PUT -T zotero.sqlite -H "x-amz-acl: bucket-owner-full-control" -H "x-amz-storage-class: STANDARD" https://better-bibtex-error-reports-62200312-apse1.s3-ap-southeast-1.amazonaws.com/zotero.sqlite
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>better-bibtex-error-reports-62200312-apse1</BucketName><RequestId>2CC654BE2858D0E6</RequestId><HostId>UjjC9G6rpTEIIT5X/NkNPwArUudJo6+Pel6m+0NrOXwWsKttTjiSBrNef/ewR9y0+eaoPB0oqzU=</HostId></Error>
real	0m0.691s
user	0m0.039s
sys	0m0.034s

**Comment by sati-bodhi** [comment]
![default](https://user-images.githubusercontent.com/7592695/42431315-52b205ca-8377-11e8-908d-655ddfb61e88.png)

This error came up.

**Comment by retorquere** [comment]
I had an error which I had hoped I had corrected before you saw it, but I had a `1` that shouldn't have been there, the command should have been `time curl -X PUT -T zotero.sqlite -H "x-amz-acl: bucket-owner-full-control" -H "x-amz-storage-class: STANDARD" https://better-bibtex-error-reports-62200312-apse.s3-ap-southeast-1.amazonaws.com/zotero.sqlite`.

**Comment by retorquere** [comment]
That error popup can't have been from 7547, but try 7559 to be sure.

**Comment by sati-bodhi** [comment]
time curl -X PUT -T zotero.sqlite -H "x-amz-acl: bucket-owner-full-control" -H "x-amz-storage-class: STANDARD" https://better-bibtex-error-reports-62200312-apse.s3-ap-southeast-1.amazonaws.com/zotero.sqlite.

real	6m55.530s
user	0m15.159s
sys	0m7.793s

**Comment by sati-bodhi** [comment]
F6ZDGLHF-apse
From 7559

**Comment by sati-bodhi** [comment]
FBK6L9TZ-apse
Subsequent 7559

**Comment by retorquere** [comment]
And what does `time curl -X PUT -T zotero.sqlite -H 'x-amz-acl: bucket-owner-full-control' -H 'x-amz-storage-class: STANDARD' https://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/zotero.sqlite` return?

**Comment by sati-bodhi** [comment]
time curl -X PUT -T zotero.sqlite -H 'x-amz-acl: bucket-owner-full-control' -H 'x-amz-storage-class: STANDARD' https://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/zotero.sqlite

real	43m58.593s
user	0m14.378s
sys	0m4.371s

This took a whooping 43 minutes

**Comment by retorquere** [comment]
Holy crap. Well, that at least vindicates the region picker.

With your database I've found some problems that are unrelated to the upload, I'm trying to fix those now.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7569](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7569.xpi) ("chunked uploads").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7579](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7579.xpi) ("new html parser").

**Comment by retorquere** [comment]
7579 should be better -- can you try?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7587](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7587.xpi) ("keep logging centralized for tests").

**Comment by retorquere** [comment]
Your DB allowed me to do some necessary performance work BTW -- try 7587.

**Comment by sati-bodhi** [comment]
![default](https://user-images.githubusercontent.com/7592695/42555719-d0462d9a-851b-11e8-8768-b9f23ab7a116.png)

It says 7579 is incompatible with my current version of Zotero.

**Comment by sati-bodhi** [comment]
WGE5RX4-apse
C2DNQ4MA-apse

These are from 7587. Time taken for the subsequent submission has improved significantly.

**Comment by retorquere** [comment]
I'd say. Minute and a half if my calculations are correct? The speed is most likely attributable to the better way to assemble the logs I have implemented.

Still some puzzling things though:

* this is still way too slow. You're uploading just 5.5 MB of data
* you're not making use of the speedup I had implemented using parallel uploads, because that kicks in when the upload is larger than 10MB
* WGE5RX4-apse and C2DNQ4MA-apse differ in size only by a few Kb, and if anything, WGE5RX4 should have been faster because it's smaller.

**Comment by retorquere** [comment]
I don't know why 7579 won't install; 7579 was tested automatically against Zotero 5.0.53 before release, so if it was incompatible with 5.0.53 all the tests would have failed and the release could not have gone out. If you look at the download that you have, can it be that it is a HTML file rather than a XPI? Maybe you downloaded the download page rather than the XPI?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7594](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7594.xpi) ("configurable debug log").

**Comment by retorquere** [comment]
On 7594, try setting the preference `debugLog` to `1` to see of that speeds things up.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7602](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7602.xpi) ("a little overzealous on pref hiding").

**Comment by retorquere** [comment]
7602 should be a tad faster still. I'm not sure whether `debugLog` = `1` will make much of a difference (it doesn't for me), but still curious to know.

If @blip-bloop announces a new version, you can skip all the previous ones unless I specifically ask to test an older one.

**Comment by sati-bodhi** [comment]
I cannot find `debugLog` on the preference pane. 

![default](https://user-images.githubusercontent.com/7592695/42585243-af47542e-8567-11e8-8083-3a5be884d843.png)

**Comment by retorquere** [comment]
It's not, sorry, it's a [hidden preference](https://retorque.re/zotero-better-bibtex/configuration/#hidden-preferences)

**Comment by retorquere** [comment]
Note to self: speed up submission and lower mem usage using two-layer array chunk/submit.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.169.7656](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.169.7656.xpi) ("remove dbg prefix").

**Comment by retorquere** [comment]
7656 should have a marked increase in speed for debug submission

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.170.7702](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.170.7702.xpi) ("jurism being different").

**Comment by retorquere** [comment]
assuming fixed

**Comment by sati-bodhi** [comment]
ZVBZDVZS-euc
AWZVVTHN-apse

This is from 7656. It is remarkably faster, indeed! Thank you for your keen assistance.

**Comment by sati-bodhi** [comment]
One unrelated question: I know that BBT is able to sync `.bib` files with my exported Zotero collection. Can it work the other way round so that any changes I make to the linked `.bib` file is also reflected in my Zotero collection? 

(P.S. I assume the answer is no, but just like to double-check. )
(P.P.S. I know this is off-topic, so it's okay to remove this comment entirely, or, if it merits being posted as another issue, move this to a new discussion thread.)

**Comment by retorquere** [comment]
"Can it work" is ambiguous between "do the laws of logic/physics prohibit" and "can it currently" and "can it sensibly be made to", to which the answers are no, no, and not really.
