### ISSUE TITLE
pb installation, no compatibility?

### ISSUE THREAD

**Issue by VirDela** [retorquere/zotero-better-bibtex#1003]
Hi,
I'm new to better-bibtex, and I can not install it... When I'm tring to install it on zotero I get this message:
> L'extension "Zotero Better Bib(La)Tex" ne peut pas être installée. Elle est peut-être incompatible avec cette version de Zotero Standalone. 

> 

So I can't install it because of compatibility reason?
I'm' trying to use this file:
zotero-better-bibtex-5.0.152.xpi
with:
zotero standalone 4.0.29.15
on:
OS X El Capitan, v. 10.11.6
Could you help me?

**Comment by retorquere** [comment]
BBT only works in Zotero 5.

**Comment by VirDela** [comment]
Thanks, sorry for having bothered you for nothing. I thought I've checked I have the last version of zotero, but no...
