### ISSUE TITLE
Option to disable automatic Capitalization in titles

### ISSUE THREAD

**Issue by OSHistory** [retorquere/zotero-better-bibtex#1004]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] If I am posting an export-related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

First off, great project, which fits right into my workflow :) Thx a bunch! It really solved my 
headache about zotero integration into latex.

The issue is not so much a bug, as more a caveat for international users. By default, it seems, 
the plugin tries to capitalize the titles, booktitles etc. This behaviour is switched off, if the 
`langid`-field is set to non-english (in my case the german isocode 'de'). 
I currently don't have the language field set on all items (which i now realize I probably should 
and will). 

My suggestion for an improvement would be either: 
1) Add an option to switch of capitalization altogether
2) If language id is not set, assume the users locale in zotero as langid
3) Document the behaviour in the export wiki 

Perhaps you could point me to the .ts-file that does the actual capitalization? 

Thank you very much

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/configuration/#suppresstitlecase

**Comment by OSHistory** [comment]
Wow, that was fast. Not sure how I missed that. Must have skipped over that one. 
Setting that value worked however as expected. 
Thank you very much. I'll close the issue.
