### ISSUE TITLE
Geman translation

### ISSUE THREAD

**Issue by OSHistory** [retorquere/zotero-better-bibtex#1005]
I wanted to add german translation files. I have forked the 
repo and added a branch `germanLocale`. Compilation works, 
but the generated xpi does not reflect the translations. Do I 
need to enable the new locale folder somewhere?

**Comment by retorquere** [comment]
Thanks for offering translation! Translation is handled through crowdin, if you login there you can add a German translation and crowdin will handle github.

**Comment by OSHistory** [comment]
Ok, i figured something like that from the french translation thread. I will try via crowdin

**Comment by retorquere** [comment]
I've added the reference for de-DE in the manifest so it will be picked up.

**Comment by retorquere** [comment]
crowdin can probably  import your existing work

**Comment by retorquere** [comment]
Yes, there's an "upload translations"

**Comment by OSHistory** [comment]
Oops, just saw your posting here. I created a pull-request for the translation files. 
Tested out the build xpi, which worked.

**Comment by OSHistory** [comment]
Should I upload them to crowdin anyways?

**Comment by retorquere** [comment]
I've already uploaded them. Looks like there are a few untranslated string that could have a German translation (like "Report ID"). Could you have a look? It's just 5 or so I think.
