### ISSUE TITLE
skipwords ignored in auto key generation

### ISSUE THREAD

**Issue by harrelfe** [retorquere/zotero-better-bibtex#1009]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] If I am posting an export-related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

I have defined custom site key generation using:
[auth3:lower][shortyear][title:skipwords:lower:substring=1,3]

Everything is working except that skipwords: is being ignored.  I'm still getting the article "A" at the start of an article title appearing in the key.  I have checked with the configuration editor and all the insignificant words are properly defined as set up with better BibTeX defaults.

**Comment by retorquere** [comment]
Can you submit a BBT error report for that reference?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.153.7305](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.153.7305.xpi) ("lowercase skipwords").

**Comment by retorquere** [comment]
And can you also try 7305?

**Comment by harrelfe** [comment]
I installed 7305 and did the restart but to no avail.  I'll do the debugging dump and send the error report, which make take several days to get to.  Thanks.

**Comment by retorquere** [comment]
I don't mind but it's really just 4 clicks.

**Comment by harrelfe** [comment]
I didn't realize it was that easy.  I tried adding a new journal article after restarting with debugging logging turned on.  Then I ran the Better BibTeX error report submission.  Report ID: NDF4MGA6

**Comment by retorquere** [comment]
I should have been more clear; I need a right-click on that specific reference, then select "Better BibTeX" ->  "Send Error Report". That will give me a copy of that reference so I can replay the problem better.

**Comment by retorquere** [comment]
In going through the log you submitted, I see only activity around one reference ("The long way"
 by P. Smoth), but that doesn't have an "A" in the title. So I really need a report generated by right-clicking the specific Zotero item where you experience the problem, then from the popup menu select "Better BibTeX", then "Error Report".

One thing I just now noticed is that you're using

[auth3:lower][shortyear][**title**:skipwords:lower:substring=1,3]

but `title` has `skipwords` applied automatically, so `title:skipwords` won't do anything.

If I get the specific sample by right-click/error report, I can look further.

**Comment by harrelfe** [comment]
I submitted 32RRBPYR .  The test title is "An the guess" and the constructed key is smi17ant.  So you can see that neither "A" nor "the" are being ignored.  Thanks -Frank

**Comment by harrelfe** [comment]
The first one works.  Thank you very much for the help.
