### ISSUE TITLE
Option to cut long author list by "et al."

### ISSUE THREAD

**Issue by TimotheeGreg** [retorquere/zotero-better-bibtex#1014]
I astrophysics (for example) author lists often contains hundreds of authors for one paper (all contributors to the same experiment). By consequence, once my bib file is produced from better bibtex (using bibtex), I have to cut every too long author list putting just "<first author> 'and others' " so that it is automatically replaced by "et al." in the pdf.
Would it be possible to have an option in better-bibtex that allows to do this when the author list is too long?
It would be great!

**Comment by retorquere** [comment]
This should be done by biblatex, not BBT; see e.g. [here](https://tex.stackexchange.com/questions/26575/bibtex-how-can-i-automatically-reduce-long-author-lists-to-xxx-et-al/26582). In biblatex (recommended) it is a little [easier](https://tex.stackexchange.com/questions/69028/set-limit-to-one-author-when-using-et-al-in-biblatex).

If you really want this done in BBT, you can do it in a postscript (untested) like

```
if (Translator.BetterBibTeX) {
  if (item.creators && item.creators.length > 10) {
    item.creators = [item.creators[0], { creatorType: 'author', name: 'et al' }];
    this.addCreators();
  }
}
```

but I'd *strongly* recommend doing this using biblatex.

this is not a standard feature I want to add to BBT, sorry. The aim is to reproduce the Zotero reference as faithfully as possible.

**Comment by TimotheeGreg** [comment]
I tried to use biblatex this morning and didn't manage, and I see that all my colleagues are using bibtex with the "and other" trick so I will continue with that (not difficult with regex).
I was just adding this feature request in case many people are in my case but I suppose that people manage to use biblatex :-)
Thanks for your fast answer!
