### ISSUE TITLE
References stopped exporting

### ISSUE THREAD

**Issue by ntnsndr** [retorquere/zotero-better-bibtex#1019]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

I've been using Better BibTeX for a few weeks now, and on June 18, my ~/Zotero/lib.bib export file stopped updating. I've tried a manual "Export now" and I've tried deleting the file to see if a new one would be created. No luck. It was working just fine for several weeks—I've come to rely on this plugin!

Report ID QURDIMXP

Thanks so much, all contributors, for your work on this important project.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.156.7380](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.156.7380.xpi) ("logging for translation").

**Comment by retorquere** [comment]
I'm seeing one auto-export to `/home/ntnsndr/Zotero/lib.bib` in the log starting but not finishing. Can you install 7380 and try again? It won't fix anything but a new log should give me more info.

**Comment by bwiernik** [comment]
He means install the test build linked above in the post by blip-boop and then make a new log.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.156.7386](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.156.7386.xpi) ("more logging + cleanup").

**Comment by ntnsndr** [comment]
Okay, thanks, @bwiernik. I just installed the latest build (7386) and submitted a new error report: 9BCEZTTR

Needless to say, the output file still has not updated.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.156.7399](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.156.7399.xpi) ("translation just silently exits?").

**Comment by retorquere** [comment]
Can you try 7399?

I can see the translation starting but it just silently exits. I've added more logging.

**Comment by ntnsndr** [comment]
Just tried it, and it worked! What was the problem?

Just in case, I logged the successful process, ID I476AVNR

Thanks so much for your help with this. Let me know how I should proceed from here, in terms of upgrading to future versions, etc.

**Comment by retorquere** [comment]
I made one relevant change and that is to wait until the translators are installed before allowing auto-export. I'm a little crabby that Zotero does not just give an error to handle rather than silently aborting the translation, but this does the job.

No need to upgrade, I'll fold this into a release but that release is just a relabeled 7399. You will be upgraded automatically, or you can force it (after the new release drops) from the addon menu.
