### ISSUE TITLE
Support Mendeley citation keys in Extra

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#1020]
https://forums.zotero.org/discussion/72659/citation-keys-change-from-mendeley-to-zotero

Mendeley import adds citation keys to Extra as:
Citation Key: key

Can support for this format be added? When Zotero generates CSL JSON, extraToCSL() will convert this to citation-key. 

Given that this is the format that Zotero chose, perhaps making this the default format for pinned keys in BBT might be good?

**Comment by retorquere** [comment]
Are you sure it's `Citation Key` and not `citationKey`? I can only find the latter in the Zotero source.

Once in place, BBT will use that to pick up the citekey. All the Better X translators will pick up on it; so Better CSL JSON will have it, but not the stock Zotero CSL JSON export.

**Comment by MaxKemman** [comment]
Thanks for picking this up! The "Citation Key" bit is a string, so the field `Extra` contains the string `Citation Key: Mendeleykey`. Perhaps Mendeley has a label "Citation Key" for the database field `citationKey` that Zotero imports into `Extra`?

**Comment by bwiernik** [comment]
During the import process, Zotero converts `citationKey` to `Citation Key`:
https://github.com/zotero/zotero/blob/2939b3ae95c520432b14f9674429d713db1aa70f/chrome/content/zotero/import/mendeley/mendeleyImport.js#L677

```
Zotero_Import_Mendeley.prototype._addExtraField = function (extra, field, val) {
	// Strip the field if it appears at the beginning of the value (to avoid "DOI: DOI: 10...")
	if (typeof val == 'string') {
		val = val.replace(new RegExp(`^${field}:\s*`, 'i'), "");
	}
	extra = extra ? extra + '\n' : '';
	if (field != 'arXiv') {
		field = field[0].toUpperCase() + field.substr(1);
		field = field.replace(/([a-z])([A-Z][a-z])/, "$1 $2");
	}
	return extra + `${field}: ${val}`;
};
```

**Comment by bwiernik** [comment]
(In general, Dan Stillman hates when fields are stored in extra in lowercase, with hyphens, etc., rather than in the format of: `Field Name: Value`, so any field Zotero imports is going to be use spaces rather than other characters and will generally be in Title Case.)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.156.7389](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.156.7389.xpi) ("support \"Citation Key:\" in addition to \"bibtex\"").

**Comment by retorquere** [comment]
Give 7389 a go.

**Comment by MaxKemman** [comment]
I installed the test build, and now the `Citekey` field in BBT automatically uses the key from Zotero's `Extra` field if it contains `Citation Key`, am I correct? It looks that way anyway

**Comment by retorquere** [comment]
It should use either of `Citation Key: <key>`, `bibtex: <key>` or `biblatexcitekey[<key>]`.

**Comment by retorquere** [comment]
So this works to your satisfaction then?

**Comment by MaxKemman** [comment]
Ah I see! Many thanks for adding this so quickly. It works to my satisfaction. Perhaps it could be a more explicit setting as it now seemed to overwrite all my citation keys without asking me whether I wanted that (in the situation where I _don't_ want BBT to use the Mendeley keys). That's also why I wasn't sure what had happened as I wasn't prompted about anything, but upon inspection I noticed the keys had changed

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.156.7396](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.156.7396.xpi) ("update test cases for #1020").

**Comment by retorquere** [comment]
I don't want to add more settings unless absolutely necessary; there are too many as it is, and the long-standing behavior is "if you specify a citekey, BBT will use it". At some later stage Zotero will natively support a citation key field (which I will then also use) and it seems pretty likely that the mendeley import would populate it, so I can't ignore it in that case either.

I do not (want to) distinguish where the citation key comes from (import, manually typed, pinned) because that would get very hairy very fast. On BibTeX import you will see the same behavior (the existing key will be adopted). It's easier to undo than to redo, too. The behavior is currently cleanly split in populating the "field" (import of bibtex/mendeley, manually, pinned), and using it (always when present).

You can quickly undo it by selecting "unpin key" from the BBT popup menu for a selection of references.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.156.7401](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.156.7401.xpi) ("update test cases for #1020").

**Comment by retorquere** [comment]
you can ignore that last test build

**Comment by bwiernik** [comment]
@MaxKemman I don't think it is that Zotero "changed" the citekey, but rather than Zotero's built-in BibTeX export always generates its own citekeys following the formula, rather than using any Citation Key value in Extra or elsewhere.

**Comment by retorquere** [comment]
No sense fighting label-gun, she will always win :laughing:

**Comment by retorquere** [comment]
Oh yeah the Zotero built-in BibTeX generation ignores citekeys in the `extra` field, although now that they're putting them there themselves that may changes. The `bibtex:` thing was strictly BBT.

**Comment by retorquere** [comment]
Or perhaps @MaxKemman meant that previously the imported reference would have `Citation Key` in `extra` but BBT would generate and use its own dynamic keys regardless. That has now changed; if a `Citation Key:` (or `bibtex:`) is present, this will always be used, and a dynamic key will not be generated. So if you exported from 5.0.156 or from one of the test build here (now in 5.0.157), citation keys for those imported references would have changed even though the reference itself did not.

**Comment by MaxKemman** [comment]
There's a column `Citekey` in Zotero. Before the test-build, I had set this to `[auth:lower][year]`. For example, `kemman2018`. With the testbuild, BBT takes the information from `Extra` so that now the column `Citekey` shows `Kemman2018` (capitalized because that's what Mendeley does).

I hope that clarifies what I wrote

**Comment by retorquere** [comment]
That is the expected behavior for BBT. If you want the old key back, select the imported references (should be easy to find by searching for `Citation Key:`), right-click, and select BBT->Unpin.
