### ISSUE TITLE
Exporting unicode letter ï to biblatex

### ISSUE THREAD

**Issue by drossegger** [retorquere/zotero-better-bibtex#1021]
Hi,
exporting references containing ï in a field seems to be not working properly.
Here is an example of the generated output using Export > Better BibLaTeX:

```
@article{laver1971,
  title = {On {{Fra{\"\i}sse}}'s Order Type Conjecture},
  journaltitle = {Annals of Mathematics},
  date = {1971},
  pages = {89-111},
  author = {Laver, Richard},
  publisher = {{JSTOR}}
}


```
It should be `{Fra\"isse}'s`

**Comment by drossegger** [comment]
Unfortunately I can not post the error report, as I get an error trying to "Report Better BibTeX Errors"
```
Invalid response from repository: 403, expected 204
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>60B2E13732AD1BD5</RequestId><HostId>wThjxeuQ22xEjtkuxe82WOHZFYbjYFbVultQ3/lvo1NVnueS1Sgv4l1/N9VJpas6kxMB/7BaHXE=</HostId></Error>
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.158.7434](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.158.7434.xpi) ("adjust test cases for #1021").

**Comment by retorquere** [comment]
Thanks for reporting that debug log submission was broken, that should work again now.

Try 7434. It will render `{Fra\"{\i}sse}'s` (not `{Fra\"isse}'s` (see https://en.m.wikibooks.org/wiki/LaTeX/Special_Characters).

**Comment by drossegger** [comment]
Oh thanks, so this seems to be an issue with biber/biblatex and not BBT. I temporarily fixed this by adding 
` \DeclareUnicodeCharacter{308}{\"{\i}}`
to my preamble.

**Comment by retorquere** [comment]
But does `{Fra\"{\i}sse}'s` not work?

**Comment by drossegger** [comment]
My latex cries gives me the error: "Package inputenc: Unicode char (U+308) not set up for use with latex". 

Interestingly only for \"{i} in my bib file. If I write it in my tex file it works. I guessed its probably related to my pdflatex/biber version but its worth testing on other systems.

biber version: 2.7
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)

**Comment by retorquere** [comment]
does it complain about `\"{o}` or `\"{\i}`?

**Comment by drossegger** [comment]
`\"{\i}`, `\"o \"u` and `\"a` work fine. Also `\"i` does work.

**Comment by retorquere** [comment]
And does it complain about `\={\i}`? Does `\"i` render cleanly (the dot of the `i` does not appear)?

**Comment by retorquere** [comment]
@njbart?

**Comment by drossegger** [comment]
`\"i` renders cleanly. `\={\i}` does not work with the same error except this time its a different character code (U+304).

**Comment by retorquere** [comment]
`\"i` doesn't even need a `{}` behind it?

**Comment by drossegger** [comment]
No, to test I tried the following:
 ` title = {Equivalence between {{Fra{\"i}ss{\'e}}}'s Conjec\"iture and {{Jullien}}'s Theorem},`

I attached a picture of how it renders.
![screenshot from 2018-07-06 15-09-53](https://user-images.githubusercontent.com/691852/42380611-d45cc1f0-812e-11e8-9324-a8be358299a6.png)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.158.7441](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.158.7441.xpi) ("adjust test cases for #1021").

**Comment by retorquere** [comment]
Can you try 7441?

**Comment by retorquere** [comment]
`title = {Equivalence between {{Fra\"iss\'e}}'s Conjec\"iture and {{Jullien}}'s Theorem}` should then also work, correct?

**Comment by drossegger** [comment]
correct. I am assuming 7441 is `{\"{\i}}`. This caused the behaviour described above.

**Comment by retorquere** [comment]
No, 7441 will do `\"i`

**Comment by drossegger** [comment]
Sorry but I don't understand what you want me to try. Entering the unicode 7441 gives me 瑁.

**Comment by retorquere** [comment]
I meant install the 7441 build linked to by @blip-bloop 😄

**Comment by drossegger** [comment]
Oh. Works fine, as expected. Thank you.
