### ISSUE TITLE
Error using CAYW for scannable cite

### ISSUE THREAD

**Issue by calimammoth** [retorquere/zotero-better-bibtex#1024]
Hello,

When using the zotpick service in combination with scannable cite I am now receiving this message instead of a citation. 

CAYW failed: [Exception… “aCallback must be a function”. Nsresult: “0x80070057 (NS_ERROR_ILLEGAL_VALUE)”. Location: “JS frame :: resource://gre/modules/AddonManager.jsm :: this.AddonManager.getAddonByID :: line 3461”. Data: no]
This.AddonManager.getAddonByID@resource://gre/modules/AddonManager.jsm:3461:13
Scannable-cite@chrome://zotero-better-bibtex/content/common.js:5853:31
pick@chrome://zotero-better-bibtex/content/BetterBibTeX.js:2186:44

Please can you help?

- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

# Bug classification

## Exporting references

If your bug report/feature request/question concerns problems with exporting references, please specify whether you're exporting BibTeX or BibLaTeX. Please right-click the references where you experience the export problem, select "Send Better BibTeX Error", and post the resulting report ID (shown in red after you submit) here.

## Non-export problems with BBT

If your issue is a bug report, but not for exports, restart Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled), reproduce your problem, and select "Report Better BibTeX error" from the help menu, and post the resulting report ID (shown in red after you submit) here.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7582](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7582.xpi) ("update test case for #1026").

**Comment by retorquere** [comment]
try 7582

**Comment by vtcarlino** [comment]
Hi,
I also have this problem. The error no longer appears. When I summon zotpick and choose my reference, BBT opens Zotero but nothing happens. 7582 didn't solved it.
Report ID: D349L7NU-euc

**Comment by retorquere** [comment]
I see no error in the error log. If you click http://localhost:23119/better-bibtex/cayw?format=pandoc and pick a reference, what do you see in your browser?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.168.7643](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.168.7643.xpi) ("Merge branch 'master' into 1024").

**Comment by calimammoth** [comment]
@retorquere well it work then. A pandoc style reference in the browser. But it doesn't work for my scannable cite in word. Although I should say pandoc is working for me and I am using that in scrivener right now.

I was trying to use the scannable cite style in word but use pandoc in everything else. 

Maybe it's because of this? I set up 2 different automator scripts, 1 for pandoc and 1 for scannable cite and i summon them with different keys.

**Comment by retorquere** [comment]
scannable cite is different because it requires the rtf-odf-scan plugin to be installed. It should alert nicely when it isn't installed though and that doesn't seem to be working right now.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.168.7646](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.168.7646.xpi) ("throw proper error when scannable cite is missing").

**Comment by retorquere** [comment]
give 7646 a go, with url http://localhost:23119/better-bibtex/cayw?format=scannable-cite . you might want to try the url using `curl`; Chrome and Firefox ao do not display the actual error message.

**Comment by vtcarlino** [comment]
It works! The URL returns a proper scannable-cite citation: `{ | Goodin, 2008 | | | zu:966903:B9GNJT83 }`
Your sir deserve a right place in the acknowledgments of my PhD thesis. Amazing work!

**Comment by retorquere** [comment]
Here's to at least one of us graduating :roll_eyes: 

5.0.169 will be out shortly which has this fix.

**Comment by calimammoth** [comment]
Hi, sorry but for me scannable cite still doesn't work.

However, (maybe I should open a seperate case) my bigger issue right now is that my pandoc citations... some of them are showing up as ??? in my marked 2 viewer although most come out perfecttly... any idea?

**Comment by retorquere** [comment]
Can you try the scannable cite link with `curl`?

**Comment by calimammoth** [comment]
I wish I knew what you mean but I don't.....

**Comment by retorquere** [comment]
Sorry; in a command line shell, type `curl http://localhost:23119/better-bibtex/cayw?format=scannable-cite` and post the results it spits out here.

**Comment by calimammoth** [comment]
curl: (7) Failed to connect to localhost port 23119: Connection refused

**Comment by retorquere** [comment]
That means Zotero is not running.

**Comment by calimammoth** [comment]
okay well when zotero is running it makes my zotpicker pop up

**Comment by calimammoth** [comment]
should i open a new case about the ??? pandoc?

**Comment by retorquere** [comment]
Yes please.
