### ISSUE TITLE
tag/keyword output order varies between exports for bibtex

### ISSUE THREAD

**Issue by jackwasey** [retorquere/zotero-better-bibtex#1026]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification
Minor/feature request

As with the order of references themselves, it seems that better bibtex returns keywords (based on tags) within each reference in an order which is dependent on the database keys of each synced copy of a zotero database. This again results in version control differences when the same data is exported on different platforms. Requested action: sort the tags when writing them out to the `keywords` field in betterBibTex output.

The overall principle I am trying to keep in my workflow is that the synced data (from git and zotero) produces the same output on different workstations, and for different potential collaborators.

Thanks for your consideration.

betterbibtex version 5.0.166
zotero v5.0.53

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7574](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7574.xpi) ("update test case for #1026").

**Comment by retorquere** [comment]
7574 follows the `sorted` behavior for fields too

**Comment by retorquere** [comment]
I'd appreciate feedback on whether this solves the case for you, then I can merge & release.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7582](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7582.xpi) ("update test case for #1026").

**Comment by retorquere** [comment]
hello?

**Comment by retorquere** [comment]
assuming fixed

**Comment by jackwasey** [comment]
Thanks for fixing. I see that the sorting is case sensitive: i.e. ASCII order, capitals before lower case. May I recommend case-insensitive sorting, which is more likely to be the same across platforms with different character encodings. Or maybe there is a better way, which would work with Chinese, Arabic, etc..

**Comment by retorquere** [comment]
There is a way of sorting strings that is locale-aware, but if you would sync with a Chinese user, you would probably get English-locale sort, and the Chinese user probably  Chinese-locale sort. I thought you wanted sorting for stability.

**Comment by jackwasey** [comment]
Yes - good point. My preference would be for a fixed (possibly configurable) sort collation, but I only work in English, and I wanted to raise the internationalization issue: I've no idea how your solution would work with Chinese.

**Comment by retorquere** [comment]
If I always sort by locale 'en', Chinese tags would likely sort deterministically, even if not according to Chinese custom. But Chinese isn't really the hard part here -- between French and English, there are probably different rules for sorting accented characters. Because the texts are so close, expectations might legitimately differ.

For now, I'm just sorting on 'en'. It will take a bit to adjust all the existing test cases.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.171.7743](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.171.7743.xpi) ("fixes #1026").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.171.7744](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.171.7744.xpi) ("localeCompare is case-insensitive by default").

**Comment by retorquere** [comment]
Try 7743

**Comment by retorquere** [comment]
(I'm not adding a config option for this. There's too many options already. I agree that sortability is desirable for version management purposes, but for that, any deterministic sort will do.)

**Comment by jackwasey** [comment]
That's fantastic, thanks.
