### ISSUE TITLE
Can't import BBT JSON file

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#1029]
I'm trying to import your BBT JSON test cases (here: https://gist.githubusercontent.com/anonymous/38c09bd18ed49645eb935326c0080943/raw/3685a25a82c05c48ad8662d0b10b577c3d2fb1c2/all.json) but it's failing when I use the Zotero import (File → Import…) function. The error report is LQ6AGFPG-euc. Is this a bug or am I doing something wrong?

**Comment by retorquere** [comment]
I think I accidentally put Juris-M-specific references in there, and BBT will not allow importing those into Zotero. Try https://gist.github.com/5d084c3b572d764505d3554de2b0a799 (still 3.9k references), those should be only Zotero-compatible references.

**Comment by retorquere** [comment]
Wait, I must have overlooked something else. Looking into it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.169.7667](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.169.7667.xpi) ("don't save relations in BBT JSON as we can't import them back anyhow").

**Comment by bwiernik** [comment]
Different error now: CU33925S-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.169.7670](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.169.7670.xpi) ("round-trip bbt-json").

**Comment by retorquere** [comment]
.170 has been scheduled for release though so if you can wait 10 minutes, https://gist.github.com/f5a3dcb50992a9eefeec0cc6e0da7463will work there too.

**Comment by retorquere** [comment]
note that Zotero will pop up a script about something being unresponsive; you have to click "continue" to let  the import finish. There's nothing much I can do about this right now until Zotero documents their async translators, at which stage I don't have to do it all in one long go.
