### ISSUE TITLE
Zotero Citation Key Doesn't Match Keys in .bib File 

### ISSUE THREAD

**Issue by mcmalone** [retorquere/zotero-better-bibtex#1030]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [X] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

## Exporting references

I'm exporting BibTeX, and here is my report ID: RG4A6VSG-euc

My problem:
In preferences, I've set my citation key to: [auth:lower][year] 
In Zotero, in the citation key column, the citation keys match the above format (e.g. "baicker2007").
However, in the .bib file, citation keys are in the following format: [auth:lower][shorttitle][year] 

I have already tried/checked the following:
(1) I double-checked that I am exporting my collection as "Better BibTeX" (the "export notes" and "keep updated" boxes are checked--and only those boxes--if that helps).
(2) I have refreshed my citation keys for all references in my exported collection.

The only other thread online where I found someone with this problem (https://forums.zotero.org/discussion/50328/bug-in-citation-key-mismatch-with-bib-collection-export), they had export to "BibTeX" instead of BBT, and making the change fixed their problem -- but since I'm already exporting as BBT, I'm unsure what to do.  

Any help is appreciated.

**Comment by retorquere** [comment]
I'm not sure what the original scenario was; RG4A6VSG contains no indication of an attempt at key refresh, just a few things:

* Changing the key format does not change existing keys; if you want to change keys after the pattern change, you need to select them and right-click "Refresh"
* Bib files do not update automatically unless you have selected auto-export, and here too, changing the pattern won't cause an auto-export to be triggered, but a refresh will.

In the 2nd description,, step (1) + (2) will force a change to to the citation keys, so it's explainable that keys would change and auto-exports would be triggered.

**Comment by retorquere** [comment]
So after the refresh, the auto-export kicked off (expected), but then what didn't work as expected?

**Comment by mcmalone** [comment]
Yes, to my knowledge, that is what appears to have happened. I would open the just-updated file and compare the citekey in the .bib file to the citekey in Zotero (in the citekey column), and the two would not match -- the former including the short title in the citekey and the latter not.

**Comment by retorquere** [comment]
Can you reproduce this problem? If so I can make a build that logs more.

**Comment by mcmalone** [comment]
Unfortunately, I'm not sure how to reproduce the problem since I've already fixed it. What I can tell you, in case this is helpful, is some details before the problem occurred:
(1) The collection I exported existed before I installed the BBT add-on; 
(2) In the process of learning how to use BBT, I exported the collection a few times using the wrong output (and I hadn't changed the citekey default pattern yet);
(3) However, I can confirm, that when I discovered the problem I was having:
- I had no other "automatic export" .bib files to update; I had deleted the "bad" .bib files, so I only had my correctly exported .bib file in Better BibTeX format; and
- I changed the citekey pattern BEFORE exporting my collection.

**Comment by retorquere** [comment]
1. doesn't matter
2. also doesn't matter
3. doesn't matter and
    * doesn't matter
    * wouldn't affect anything. Auto-export is just regular export but triggered by changes, and changing the pattern only affects references that are changed from that point on

If it is replicable at your end, changing the pattern (e.g. by adding a `.` at the end) and refreshing the references should kick off auto-export but the updated auto-export would not have the `.` at the end. That seems to describe the situation you had in the initial description. Otherwise I really don't know.

**Comment by retorquere** [comment]
Assuming fixed.

**Comment by lkorczowski** [comment]
While my citation key formatting is [auth:lower]_[veryshorttitle:lower]_[year] and it is working perfectly both in Zotero UI and while using BBT "Better BibLaTeX" export option.

However the BBT "Better BibTeX" export option will generate the **previous** citation key formatting (the one before the one set actually). Weird doesn't it ?

Example, I played a bit with different key formatting:

1.  [auth:lower]_[veryshorttitle:lower]_[year] + refresh all key
2.  [auth:lower]_[veryshorttitle:lower]_x[year] + refresh all key. Result: better biblatex "barachant_riemannian_x2013", better bibtex "barachant_riemannian_2013"
3. [auth:lower]_[veryshorttitle:lower]_[year] + refresh all key. Result: better biblatex "barachant_riemannian_2013", better bibtex "barachant_riemannian_x2013"

How can be even possible? Am I the only one experiencing this issue ?

**Comment by retorquere** [comment]
Please open a new issue. Since we never found what was the problem of #1030, I can't assume they're the same problem.
