### ISSUE TITLE
Unable to export My Library into *.bib file. Error: "translation failed"

### ISSUE THREAD

**Issue by llinfeng** [retorquere/zotero-better-bibtex#1031]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report
    * Not sure which entry is causing the problem

# Bug classification

## Exporting references problem:
I cannot export my entire **My Library**. Exporting through "*Better BibLatex*" or "*Better BibTex*" shall yield the same error as follows:
![image](https://user-images.githubusercontent.com/5890407/42764286-3c793316-88e3-11e8-8ee8-293696a1cf15.png)
As I have chosen the *Keep Updated* option, I found the following info from the Preference-Better BibTex tab:
![image](https://user-images.githubusercontent.com/5890407/42764493-ba4ffa68-88e3-11e8-8ae9-b2db61b638b1.png)

## What remains unclear:
1. Does it has to do with a "bad entry" in my library?
    I tried to read the Debug log, but did not find anything that points to an entry.
2. If it has to with a bad entry, where to find such "bad entry" in **My Library**?
    I succeeded with exporting a folder, but there are tons of folders in my library. Please let me know if hunting for the "bad entry" would worth the time. (I tried, but failed to tell whether the exported `*.bib` file should contain all the entries.)
3. I saw a lot of mentioning of `{better-bibtex ...}` in the log. Does it has to do with the plugin?

### Debug info
I have submitted the debug output through Zotero, with Debug ID: `D1163629660`. The Debug Log is produced in three steps:
1. Start the log
2. Go to the Preference-Better BibTex tab to "Export" the library
3. Submit the log. 
I've also made the log available as: https://github.com/llinfeng/Zotero_Debug/blob/master/Zotero%20Debug%20Output.txt

### My library:

I have made my entire **My Library** public. It is accessible through: https://www.zotero.org/llinfeng/items

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.170.7714](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.170.7714.xpi) ("more logging for <pre> failures").

**Comment by retorquere** [comment]
Can you install 7714 and try again? You can submit a BBT error log from the help menu. The debug ID you posted was sent using Zotero debug log, I can't see those.

**Comment by llinfeng** [comment]
Here goes another error log, with ID: `L54G7AUE-euc`. I've run 4 separate exporting jobs. Two that exports smaller collections worked. Two that tried to export the bigger **My Library** is still failing, for the same reason.

**Comment by retorquere** [comment]
there's no need to put your logs on github, that's what the debug report does.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.170.7720](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.170.7720.xpi) ("allow empty pre").

**Comment by retorquere** [comment]
Try 7720

**Comment by llinfeng** [comment]
I am happy to report that the export now goes through! @retorquere Thank you for making the process super straightforward: clicking on the test build link, and install the Add-on from the file should do all the jobs.

**Comment by retorquere** [comment]
It's in my benefit as much as it is yours :smiley:. Happy it works for you, you can just keep using this; I have one more fix to merge and then I'll cut a new release. You'll be upgraded to that automatically.
