### ISSUE TITLE
Exporting error

### ISSUE THREAD

**Issue by hadrienj** [retorquere/zotero-better-bibtex#1032]
Hi,

Thanks for the great work!

I get an error when I try to export a reference:

`An error occurred while trying to export the selected file.`

Here is my exporting references: 7S5W6ZJ2-euc

Thanks!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.170.7717](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.170.7717.xpi) ("trigger build").

**Comment by retorquere** [comment]
Try with 7717

**Comment by hadrienj** [comment]
Great, it seems to work (even with two other problematic references)!

Thanks!

**Comment by retorquere** [comment]
Super -- you can just keep using this, I'm going to merge a few more fixes I'm currently working on and then I'll cut a new release; you will upgrade automatically.
