### ISSUE TITLE
Don't title-case sup/subscripts

### ISSUE THREAD

**Issue by SolidTux** [retorquere/zotero-better-bibtex#1037]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

# Bug classification

## Exporting references

5YZ75HV7-euc

If the subscript is the last thing in the title, it becomes uppercase. For example:

```

@article{Name2018,
  title = {O{\textsubscript{7-X}}},
  date = {2018},
  author = {Name, Name}
}

@article{Name2018a,
  title = {O{\textsubscript{7-x}} Test},
  date = {2018},
  author = {Name, Name}
}
```

Edit: Wrapping it in `<span class="nocase">...</span>` solves this issue, but I find it still strange that the automatic capitalization changes subscripts.

**Comment by retorquere** [comment]
Just so I know I'm looking at the same thing you are, can you select both and then send a new debug report? Right now I only have `O<sub>7-x</sub>`. I assume the other was `O<sub>7-x</sub> test`?

**Comment by SolidTux** [comment]
Yes, here is the updated report: 3NSGRA4T-euc

I also added the version with the nocase span.

**Comment by retorquere** [comment]
These are other cases though.

**Comment by SolidTux** [comment]
Oh, sorry. I experimented a bit. This should be the correct one now: Z2L44TKQ-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.179.7851](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.179.7851.xpi) ("replace pre with dummy text").

**Comment by retorquere** [comment]
7851 should be better; can you try

1. installing 7851
2. importing [the combined test cases you posted](https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/1037/test/fixtures/export/Subscript%20in%20uppercase%20if%20last%20thing%20in%20title%20%231037.json)
3. export it using Better BibLaTeX, 
4. changing anything you still want changed in the output
5. put the results here

I'm not entirely sure that `O<sub>7-x</sub>` is translated wrong. I couldn't find much but both https://github.com/evansmusomi/title-case-algorithm and https://github.com/3lessthan/txttools-titlecase mention that the last word is always capitalized, and it looks like the Zotero titlecaser (which I use) considers dash-separated strings of letters as separate words.

**Comment by SolidTux** [comment]
I also don't know what the correct behaviour is here. What confused me is that subscripts are treated like normal words. But if this is expected, that's fine also.

In the output the only capital letter was 7-x at the end. [This](https://gist.github.com/SolidTux/72b7a9458871222886c473cfda1f4332) is how I'd expect it to look like, but I don't know if that's correct. I didn't find anything regarding title case and subscripts.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.179.7858](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.179.7858.xpi) ("fixes #1037").

**Comment by retorquere** [comment]
There's more on capitalization [here](http://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html); long story short: it be complicated, and requires understanding of English, so there will always be cases where Zotero (which does not understand English) will get it wrong, and that means so will BBT.

I hadn't considered sub/supscript. That sounds reasonable and doesn't break any existing test case; fortunately my existing title-caser-workarounds make this easy. Try 7858.

**Comment by retorquere** [comment]
Come Wednesday I'll be travelling and I'll probably not have internet access for a while. I'd love to close this before I go. Can you give it a go and see if it works as you expect?

**Comment by SolidTux** [comment]
Thank you very much, now it works as I expect.

**Comment by retorquere** [comment]
Thanks for the confirmation; only I can close issues on this repo. I'll fold it into a release tonight and that will close the issue.

**Comment by retorquere** [comment]
5.0.180 is out which has this fix. Thanks for reporting this, it coincidentally also prompted a fix in the Zotero citation processor, so a win all around.
