### ISSUE TITLE
Suggestion for Vim integration docs

### ISSUE THREAD

**Issue by dlukes** [retorquere/zotero-better-bibtex#1039]
First of all, thank you for a brilliant plugin! Especially the possibility to open the citation dialog via the HTTP API completely blew my mind when I found out about it, I had no idea something like this was possible :)

I have just two small suggestions for the [Vim integration docs](https://retorque.re/zotero-better-bibtex/cayw#vim):

- the API call is just one simple command, so I wouldn't use an external script, especially as it's somewhat brittle (the script might not be on the path, it might get accidentally deleted, it might not have the execute bit set, etc.)
- using `read` results in the citation being inserted on the line below the one where the cursor is, which is a bit disappointing after all the other magic :) One would expect it to be inserted at the cursor position.

After a bit of tinkering, I came up with the following setup which doesn't need an external script, just paste it in your `.vimrc` (and modify to your liking):

```vim
function! ZoteroCite()
  " pick a format based on the filetype (customize at will)
  let format = &filetype =~ '.*tex' ? 'citep' : 'pandoc'
  let api_call = 'http://localhost:23119/better-bibtex/cayw?format='.format.'&brackets=1'
  let ref = system('curl -s '.shellescape(api_call))
  return ref
endfunction

noremap <leader>z "=ZoteroCite()<CR>p
inoremap <C-z> <C-r>=ZoteroCite()<CR>
```

This inserts the citation at the cursor (instead of the line below) using the shortcut `Ctrl-z` (in insert mode) or `<leader>z` (in normal, visual etc. modes).

Maybe someone else will find these handy :)

**Comment by retorquere** [comment]
Thanks so much! You're a braver man than I am, diving into vimscript. Added to the docs.
