### ISSUE TITLE
Export \mathit

### ISSUE THREAD

**Issue by cass00** [retorquere/zotero-better-bibtex#1041]
The title of the following reference from PRE:

```
@article{PhysRevE.49.R978,
  title = {Optical determination of the saddle-splay elastic constant ${\mathit{K}}_{24}$ in nematic liquid crystals},
  author = {Polak, R. D. and Crawford, G. P. and Kostival, B. C. and Doane, J. W. and \ifmmode \check{Z}\else \v{Z}\fi{}umer, S.},
  journal = {Phys. Rev. E},
  volume = {49},
  issue = {2},
  pages = {R978--R981},
  numpages = {0},
  year = {1994},
  month = {Feb},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevE.49.R978},
  url = {https://link.aps.org/doi/10.1103/PhysRevE.49.R978}
}

```

is exported as 
```
@article{1994:PolCraKosDoa:OpticalDeterminationSaddlesplay,
  title = {Optical Determination of the Saddle-Splay Elastic Constant \$\{$\backslash$mathit\{\vphantom{{K}}\vphantom\{\}\vphantom\{\}\_\{24\}\$ in Nematic Liquid Crystals},
...

```
which creates a problem with bibtex (Illegal end of database file). The problematic part of the title is 
`${\mathit{K}}_{24}$ `

debug-ID: DSEL7UZN-euc

**Comment by retorquere** [comment]
Bibtex with math doesn't round-trip through zotero as zotero doesn't have math support. If you want to use math in titles you'll have to wrap that with pre elements as per https://retorque.re/zotero-better-bibtex/advanced/

**Comment by retorquere** [comment]
It looks like your entry in Zotero has the title

```
Optical determination of the saddle-splay elastic constant ${\\mathbb{K}}_{24}$ in nematic liquid crystals
```

It's not really possible that for this title BBT would output

```
Optical Determination of the Saddle-Splay Elastic Constant \$\{$\backslash$mathit\{\vphantom{{K}}\vphantom\{\}\vphantom\{\}\_\{24\}\$ in Nematic Liquid Crystals}
```

It is BBT output, but the `mathit` isn't in the input so BBT wouldn't output it.

Zotero does not have any form of math support, but if you want automatic sort-of-math support, you may want to look at [this](https://retorque.re/zotero-better-bibtex/scripting/#detect-and-protect-latex-math-formulas) postscript. That will wrap everything between dollar signs in a `<pre>` section and so will pass that on as raw latex. Note that if you also use Zotero for Word/LibreOffice, the raw latex will just show up as latex, not as a rendered formula.

**Comment by cass00** [comment]
I tested `mathbb`, that's why probably ended up in the bug report. The original reference is using `mathit` . The problem is that if you import the reference via zotero connector and then later export the whole library in a bib file, you'll get an error in bibtex and do probably not know where it came from. Searching for an error in a big bib file is no fun
I'll try the `<pre>` stuff later

**Comment by cass00** [comment]
> Zotero does not have any form of math support, but if you want automatic sort-of-math support, you may want to look at this postscript. That will wrap everything between dollar signs in a <pre> section and so will pass that on as raw latex. Note that if you also use Zotero for Word/LibreOffice, the raw latex will just show up as latex, not as a rendered formula.

The math part comes from the automatic import, so there is no choice in the first place. With respect to better bibtex, you naturally always want bibtex/latex and not libreoffice. Therefore using the `<pre>` script by default for exporting might make sense.  The `pre` statement worked fine for the reference discussed here.

**Comment by retorquere** [comment]
That's how I use it (that's why it's there), but I just want people to be aware of the pitfalls; there are people (like me) who eg primarily use latex but also occasionally GDocs.

**Comment by retorquere** [comment]
But this question is handled to your satisfaction then?

**Comment by retorquere** [comment]
Assuming handled.
