### ISSUE TITLE
Feature request: per-export configuration of export options

### ISSUE THREAD

**Issue by jackwasey** [retorquere/zotero-better-bibtex#1048]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Feature request

The export tab of BBT preferences has various options for URLs, DOI, unicode/latex, etc.. Because of different projects and journal submission requirements, there is no single set of values which work for everything I need. The automatic export is constantly overwriting correct `bib` files when I am forced to change the global options for a new project.

The obvious work-around is not to use automatic export, but this would be very unfortunate, as this is such a great feature.

**Comment by retorquere** [comment]
Very tricky, as the translators don't get passed the relevant information. And it involves UI work :disappointed: which I'm not really fond of. I'm keeping this open in case something crafty springs to mind.

**Comment by jackwasey** [comment]
Is this something a feature request against zotero could help with?

**Comment by retorquere** [comment]
Technically, yes, but I'm struggling to formulate a use-case that isn't BBT-specific. I may have found a way to smuggle in per-export preferences and I'm experimenting with that now.

**Comment by jackwasey** [comment]
great - happy to test if you manage to do it

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.189.2583](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.189.2583.xpi) ("allow cycling through subset of export settings").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.189.2584](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.189.2584.xpi) ("sneak in overrides").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.189.2586](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.189.2586.xpi) ("cache overrides").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.189.2587](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.189.2587.xpi) ("show togglable options").

**Comment by jackwasey** [comment]
Wow, that's amazing.

**Comment by retorquere** [comment]
Good enough? I have some ideas on how to spruce up the UI but given how crap I am at UI work (and how poorly the technology used to make them is documented), it could take a while. I could merge this into a release if it does what you want.

**Comment by jackwasey** [comment]
I'm about to check again on a different platform, but right now it looks great.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.189.2598](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.189.2598.xpi) ("docs").

**Comment by retorquere** [comment]
New UI for the overrides

**Comment by retorquere** [comment]
The UI looks substantially better (I think) but it required pretty extensive code changes - it works for me, but it'd be great comfort for me to get confirmation.

**Comment by retorquere** [comment]
In the course of this I fixed some important bugs (I know, I know, should have been done separately), but I really want to release these now. If you could confirm 2598, I can cut a release.

**Comment by jackwasey** [comment]
Ok, taking a look now. Thanks!

**Comment by retorquere** [comment]
There was a critical bug - just upgrade to the latest version, it has all the changes from #1048. You can still report here.

**Comment by retorquere** [comment]
The latest real release I mean.

**Comment by retorquere** [comment]
Assuming fixed -- seems to work for me.
