### ISSUE TITLE
Question: Is there a way to do camelCase in the bbt cite key?

### ISSUE THREAD

**Issue by seangrogan** [retorquere/zotero-better-bibtex#1051]
Sorry, I must have clicked something too quickly:

I prefer to use camelCaseConvention (like that) when typing.  I was wondering if there was an option in the automatic creation of citation keys.  If I have two or three authors, I'd like to see this

dimitrakopoulosFarrellyGodoy2002

or 

dimitrakopoulosFarrelly2002

[authEtAl] looks close to what I want, but still does the not-camelCase i'd like. 

Thanks in advance

**Comment by retorquere** [comment]
There isn't currently, no.

**Comment by seangrogan** [comment]
Cool.  No worries then.  Thanks.
