### ISSUE TITLE
BetterBibLaTeX: Software field company is mapped to publisher instead of organization

### ISSUE THREAD

**Issue by surmann** [retorquere/zotero-better-bibtex#1054]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

Within an item type "Computer Program" of Zotero, the field "Company" is mapped to "publisher" when exporting via BetterBibLaTeX. When using this file with biber in LaTeX, the publisher is not shown in the bibliography. If I switch the field name "publisher" to "organization" manually in the .bib file the company is shown.

Does it make sense to update the export mapping the company field of zotero to "organization" in BibLaTeX?

Here is the report:
KMI6SG4L-euc

**Comment by retorquere** [comment]
I will look at the manual, but please include a log as per the last checkbox.

**Comment by surmann** [comment]
I added a report. Sorry for skipping this.

**Comment by retorquere** [comment]
I need to have the ID

**Comment by surmann** [comment]
I added it to the initial post.
It is KMI6SG4L-euc.

**Comment by retorquere** [comment]
Ah, the initial post didn't update until now. The manual lists them as unsupported so has no opinion on the matter; given this, and that you say "organization" works for you, this seems like a reasonable change.

**Comment by surmann** [comment]
Thanks! :)
When will this fix be deployed?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.190.2617](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.190.2617.xpi) ("fixes #1054").

**Comment by retorquere** [comment]
Can you give 2617 a go? I prefer confirmation before cutting a new release.

**Comment by surmann** [comment]
Sure. Is it possible to install it over the current version without loosing my settings?

**Comment by retorquere** [comment]
Yep, it's just a normal release, the only difference is it needs to be installed manually.

**Comment by surmann** [comment]
Ok, it is working for BibLaTeX. Now I took a look for BibTeX. Here it is still exporting to "publisher". Sorry, that I missed this. Would please you change this, too?

**Comment by surmann** [comment]
Do you need a report for this requirement?

**Comment by retorquere** [comment]
Nope, but it would be good to know if there are styles that make use of the organization field. If I move it to organization and it still doesn't show up that's no benefit.

**Comment by surmann** [comment]
It shows up on BibLaTeX. And when you look in the citation recommendation for R, it looks like this:

    @Manual{,                                                          
      title = {R: A Language and Environment for Statistical Computing}, 
      author = {{R Core Team}},                                          
      organization = {R Foundation for Statistical Computing},           
      address = {Vienna, Austria},                                       
      year = {2018},                                                     
      url = {https://www.R-project.org/},                                
    }

Here, the organization is used to.
If you want to be certain, I can test it for BibTeX, too.

**Comment by retorquere** [comment]
Please do test. Bibtex and biblatex behave very differently. 

The "manual" type actually does list organization as a field, but BBT doesn't export "manual" as there is no corresponding zotero type.

**Comment by surmann** [comment]
Obviously.
Software is exported to @misc using BetterBibTeX. The bibtex style files I checked (alpha, alphanum, elsarticle-harv) use the field "howpublished", neither "publisher" nor "organization". Hence, if we change something, we should use "howpublished" to export the "company" field from Zotero.

**Comment by retorquere** [comment]
But isn't that more appropriate for the "how" (medium) than the "who" (publisher or organization)? Perhaps for software they're the same, but not generally. @nickbart?

**Comment by surmann** [comment]
You are right. But if "how" and "who" are the same for software would it be ok to map the company from Zotero to "howpublished"?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.190.2634](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.190.2634.xpi) ("Merge branch '1038' into 1054").

**Comment by retorquere** [comment]
Can you try 2634?

**Comment by surmann** [comment]
BibTeX and BibLaTeX both export the company now to "organization". In BibLaTeX, this works fine. BibTeX, as mentioned above, does not show this information as it expects it in "howpublished". However, I think it works as expected.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2674](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2674.xpi) ("adjust tests for #1054").

**Comment by retorquere** [comment]
Try 2674

**Comment by surmann** [comment]
Now BBT uses "howpublished" with BibTeX. Thanks!

**Comment by retorquere** [comment]
Cool -- I'm waiting on confirmation from #1058 and then I will cut a new release. You can just keep using this, you will upgrade automatically.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2677](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2677.xpi) ("adjust tests for #1054").
