### ISSUE TITLE
Bug with citekey

### ISSUE THREAD

**Issue by mikeatm** [retorquere/zotero-better-bibtex#1057]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

I'm looking at my export and two citations  have similar citekeys, one from 2011 one from 2005:

* `deak_polaronic_2011` for  `Characterization of {{Paramagnetic Species}} in {{N}}-{{Doped TiO}} {\textsubscript{2}} {{Powders}} by {{EPR Spectroscopy}} and {{DFT Calculations}}}`, and
* `deak_polaronic_2011-1`  for  ` Polaronic Effects in {{TiO}} 2 Calculated by the {{HSE06}} Hybrid Functional: {{Dopant}} Passivation by Carrier Self-Trapping}`

the first should be  `di_valentin_characterization_2005`  and the second should be `deak_polaronic_2011`.

# Bug classification
Citekey error

## Exporting references
Exporting BibTeX  : UXQHZ7KX-euc

Only happens with BibTeX not with BibLaTeX

**Comment by retorquere** [comment]
You will have to right-click those two references and send a new debug report; that will give me a copy of those two references.

**Comment by retorquere** [comment]
If the bug is not present, there's nothing to fix :smile:

**Comment by retorquere** [comment]
Please re-open if you see it happening again, but if you don't see the issue, and I don't see the issue, there's nothing I can do.

**Comment by mikeatm** [comment]
Im reopening with a new report, on the latest version: 
`8X3NP7KH-euc`

two citekeys are the same, one should have its own,

**Comment by mikeatm** [comment]
Well, im think there may be something other than better-bibtex  going on,  there is probably some sync issue, since i moved from zotero sync to self hosted filesync. something else went on.  maybe there is nothing to do.  you could add a checkbox to the issue template for guys to inform you of any sync going on and if its zotero's sync or  dropbox/self hosted. 
Im now keeping `.zotero/zotero/isxoyek0.default/zotero/better-bibtex` and `.zotero/zotero/isxoyek0.default/zotero/better-bibtex.sqlite` in sync  for better bibtex.

**Comment by retorquere** [comment]
You *really* don't want to put the sqlite databases of either Zotero or BBT in a directory synced by dropbox/gdrive/whatever. Sooner or later this will absolutely corrupt your database. You may want to delete `.zotero/zotero/isxoyek0.default/zotero/better-bibtex` and `.zotero/zotero/isxoyek0.default/zotero/better-bibtex.sqlite` and have Zotero generate fresh keys. What do you use for sync?

Zotero should really warn people to never do this. It's not BBT-specific; syncing the sqlite files will really break things down the line, if there isn't corruption in those files already.

I can see that `A DFT+U description of oxygen vacancies at the TiO2 rutile (110) surface` has the wrong citekey -- if you right-click it and choose key refresh, does it update?

**Comment by mikeatm** [comment]
Yes, if i refresh it does update and give it a proper (correct ) citekey.

**Comment by retorquere** [comment]
Was this reference recently updated/changed? There's a few ways that key could have gotten there but it should have automatically refreshed when you edited it.

Please do exclude the better-bibtex.* and zotero.* files (not just .sqlite, the databases generate other files too while in use) from sync.

**Comment by mikeatm** [comment]
No, it was not recently updated.  but as a i said there may have been changes to  zotero's DB from  self hosted sync,  i think it would be safe to assume thats the underlying cause. after  dealing with that (the sync issue), the problem (which was manifesting itself always on export even after refreshing an seeming okay in zotero)  disappeared.

**Comment by retorquere** [comment]
OK. What did you use for sync BTW?

**Comment by mikeatm** [comment]
rsync.

**Comment by retorquere** [comment]
One way or bidirectional?

**Comment by mikeatm** [comment]
bidirectional.  issue is only on one of the sides.

**Comment by retorquere** [comment]
Bidi sync will mess up the databases if they're open. If you're absolutely sure rsync doesn't run when zotero does it should be OK.
