### ISSUE TITLE
All export fails with "too much recursion"

### ISSUE THREAD

**Issue by andersjohansson** [retorquere/zotero-better-bibtex#106]
Hi,
zotero-better-bibtex seems to be causing a rather severe problem in my configuration (deactivating it seems to solve the problem).

No matter what translator (bib\* or not) or collection I choose, export always stalls with the error message: 

> too much recursion                zotero / xpcom / translation / translate_firefox.js:483

The stalling  line (I believe):
https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/translation/translate_firefox.js#L483

I guess this will be hard to debug if it doesn't happen for anyone else. I'll try to look into it more when I have time. Here's my configuration:

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
Plugins:

> Adblock Plus  2.6.4   true    {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
> AutoPager 0.8.0.10    true    autopager@mozilla.org
> Copy All Links    1.3 true    {e6a9a96e-4a08-4719-b9bd-0e91c35aaabc}
> Disable Anti-Adblock  3.1 true    {d49a148e-817e-4025-bee3-5d541376de3b}
> DOI Protocol  1.0 true    doiprotocol@chemieunser.wordpress.com
> FireGestures  1.8.7   true    firegestures@xuldev.org
> Flat Bookmarks    1.11    true    flatbm@xuldev.org
> Greasemonkey  2.1 true    {e4a8a97b-f2ed-450b-b12d-ee082ba24781}
> Item History for Zotero   1.0.65  true    zotero-item-history@mystery-lab.com
> KeeFox    1.4.2   true    keefox@chris.tomlinson
> keyconfig 20110522    true    keyconfig@dorando
> Multifox  2.2.0   true    multifox@hultmann
> Omnibar   0.7.25.20140626 true    omnibar@ajitk.com
> Paper Machines    0.4.9   true    papermachines@chrisjr.org
> Recoll Indexer    1.2.3   true    {359f0058-a6ca-443e-8dd8-09868141bebc}
> RightBar  0.5 true    rightbar@realmtech.net
> SmoothWheel (AMO) 0.45.8.20130519.3   true    {5F590AA2-1221-4113-A6F4-A4BB62414FAC}
> Stylish   1.4.3   true    {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
> Ubuntu Firefox Modifications  2.9 true    ubufox@ubuntu.com
> Zotero    4.0.21.5    true    zotero@chnm.gmu.edu
> Zotero Better Bib(La)Tex  0.6.42  true    better-bibtex@iris-advies.com
> ZotFile   3.1 true    zotfile@columbia.edu
> Zutilo Utility for Zotero 1.2.10  true    zutilo@www.wesailatdawn.com

**Comment by retorquere** [comment]
Recoll Firefox is going to be a problem. The workarounds I need to do to work around the breakage it causes is causing BBT to fail the soon-to-be-mandatory firefox extension review process, and the author does not respond to his message board.

**Comment by andersjohansson** [comment]
Too bad! And yes, I am that Anders Johansson. I'm mostly using BBT now though, and not the biblatex-translator I made (adapted from bibtex) which since (mostly) was included officially.

**Comment by retorquere** [comment]
I've posted a fix on the Recoll site but the author seems inactive. It's an incredibly simple fix, but I really don't want to pick up maintenance for an extension I don't use myself. As of the next version, BBT will complain and disable itself when it finds the current Roll Firefox version. I need to make progress towards compliance for the &^*#^@$(* mandatory signing Mozilla has introduced, and Recoll was making it impossible.

**Comment by andersjohansson** [comment]
For anyone seeing this, it seems to be fixed on the side of recoll-indexer now. The new version is available here: https://addons.mozilla.org/en-US/firefox/addon/recoll-indexer-1/

**Comment by retorquere** [comment]
Multi-process FF is going to break everything (the FF crew seem hell-bent on alienating their extension authors of late), but BBT ought to just accept the new version.

**Comment by andersjohansson** [comment]
Yes, no errors at all!
