### ISSUE TITLE
BibLaTeX Patent author handling & type

### ISSUE THREAD

**Issue by adam3smith** [retorquere/zotero-better-bibtex#1060]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

## Exporting references
As per [this](https://tex.stackexchange.com/questions/447383/biblatex-biber-patent-citation-support-based-on-zoterobbl-output/447508?noredirect=1#comment1128794_447508) BBT's (and Zotero's) handling of authors is incorrect. 
- Zotero's inventors should map to BibLaTeX author
- Zotero's assignee should map to BibLaTeX holder (a bit awkward bc assignee isn't a creator field in Zotero -- incorrectly I think)
- the patent item type should as per SO: "have a type, either the generic type = {patent}, or preferable one of the available types patenteu, patentus, ... In case a non-generic type is used, the number field may contain the patent number without the country prefix."

**Comment by retorquere** [comment]
moewe says

> In particular the Inventor (in Zotero's notation) should be exported to author and the Assignee/Holder should be exported to holder only if it does not coincide with the author list.

But assignee is not a creator-type field. Should I treat that as if it is a single-part creator-type field?

**Comment by moewew** [comment]
Note that I'm not a Zotero user, so I can only offer help on the theory not the practicalities. 

`biblatex`'s `holder` field is a name list, so it works just like `author`. As
```
@patent{laufenberg,
  author       = {Laufenberg, Xaver and Eynius, Dominique and Suelzle, Helmut
                  and Usbeck, Stephan and Spaeth, Matthias and Neuser-Hoffmann,
                  Miriam and Myrzik, Christian and Schmid, Manfred and Nietfeld,
                  Franz and Thiel, Alexander and Braun, Harald and Ebner,
                  Norbert},
  title        = {Elektrische Einrichtung und Betriebsverfahren},
  number       = 1700367,
  date         = {2006-09-13},
  holder       = {{Robert Bosch GmbH} and {Daimler Chrysler AG} and {Bayerische
                  Motoren Werke AG}},
  type         = {patenteu},
  url          = {http://v3.espacenet.com/textdoc?IDX=EP1700367},
}

@patent{sorace,
  author       = {Sorace, Ronald E. and Reinhardt, Victor S. and Vaughn, Steven
                  A.},
  title        = {High-Speed Digital-to-{RF} Converter},
  number       = 5668842,
  date         = {1997-09-16},
  holder       = {{Hughes Aircraft Company}},
  type         = {patentus},
}
```
demonstrate it makes sense to allow for a list of holders and not just one holder.

How would a list in that case work on the Zotero input side? If Zotero can't change Assignee to a name list (I suspect backwards compatibility would be an obstacle here), then assuming single part might be your best option. But even then you would probably have to detect whether the Assignee is a person or a corporation (brace protection in name fields).

**Comment by retorquere** [comment]
Zotero does not treat the `assignee` field as a creator-type field, just a text field, so the best I can do is to treat it as a single-item one-field (company) name.

**Comment by retorquere** [comment]
Is the `location` that's being discussed the counterpart to Zotero's `place` or of Zotero's `country`?

**Comment by moewew** [comment]
For `@patent` types `location` has a special meaning and should indicate the geographical scope of the patent. That would make me think `country` is more appropriate, but you should probably wait for someone who knows about Zotero to confirm that.

If possible the value of `location` should be a list (separated with `and` as usual) built from the pre-defined keys `countryde`, `countryeu`, `countryep`, `countryfr`, `countryuk`, `countryus`, for countries without a pre-defined key a verbatim export seems the best option. Note that the `location` should only be given if it differs from the geographical scope implied by the `type` (`patentde`, `patenteu`, `patentfr`, `patentuk`, `patentus`, `patreqde`, `patreqeu`, `patreqfr`, `patrequk`, `patrequs` all imply the obvious countries, the generic `patent` and `patreq` don't imply any countries) or the `number`. Compare the examples above with (the fictional)
```
@patent{almendro,
  author       = {Almendro, Jos{\'e} L. and Mart{\'i}n, Jacinto and S{\'a}nchez,
                  Alberto and Nozal, Fernando},
  title        = {Elektromagnetisches Signalhorn},
  number       = {EU-29702195U},
  date         = 1998,
  location     = {countryfr and countryuk and countryde},
}
```

If the `type` field is used with a country-specific value, then the `number` field should not contain the country prefix again. If `type` is not given or a generic `patent`, `patreq` then `number` should probably contain an appropriate country prefix.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2737](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2737.xpi) ("test case for #1060")

Install in Zotero by downloading [test build 5.0.197.2737](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2737.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by adam3smith** [comment]
Yes, agree, `assignee` is best treated as a company as things are. I hope we'll get that converted to a creator in Zotero 5.1.
Zotero doesn't have a concept of the geographic scope of a patent (nor is that, afaik, commonly cited), so I'm going to leave `location` out of the Zotero BibLaTeX export -- if I were to include it, it'd be either `country` or `issuingAuthority` though.

Just in case this helps, here's the handling of `type` that I'll be including in Zotero's BibLaTeX:

```
if (!item.patentNumber) {
			writeField("type", "patent");
		}	else if (item.patentNumber.startsWith("US")) {
				writeField("type", "patentus");
				writeField("number", item.patentNumber.replace(/^US/, ""));
		} else if (item.patentNumber.startsWith("EP")) {
				writeField("type", "patenteu");
				writeField("number", item.patentNumber.replace(/^EP/, ""));
		} else if (item.patentNumber.startsWith("GB")) {
				writeField("type", "patentuk");
				writeField("number", item.patentNumber.replace(/^GB/, ""));
		} else if (item.patentNumber.startsWith("DE")) {
				writeField("type", "patentde");
				writeField("number", item.patentNumber.replace(/^DE/, ""));
		} else if (item.patentNumber.startsWith("FR")) {
				writeField("type", "patentfr");
				writeField("number", item.patentNumber.replace(/^FR/, ""));
		} else {
			writeField("type", "patent");
			writeField("number", item.patentNumber);
		}
}
```

**Comment by adam3smith** [comment]
The latest test build doesn't quite work for me. I get
```
@patent{laufenberg,
  title = {Elektrische Einrichtung und Betriebsverfahren},
  url = {http://v3.espacenet.com/textdoc?IDX=EP1700367},
  number = {EP1700367},
  date = {2006-09-13},
  author = {Laufenberg, Xaver and Eynius, Dominique and Suelzle, Helmut and Usbeck, Stephan and Spaeth, Matthias and Neuser-Hoffmann, Miriam and Myrzik, Christian and Schmid, Manfred and Nietfeld, Franz and Thiel, Alexander and Braun, Harald and Ebner, Norbert},
  holder = {undefinedundefinedundefined},
  type = {patenteu}
}
```

The "undefined" is obviously wrong (Zotero has "Robert Bosch GmbH" as assignee) and also it should remove the EP from `number`

**Comment by retorquere** [comment]
(I cant replicate the `holder = {undefinedundefinedundefined},`, but with a BBT JSON export of your reference I should be able to find the problem)

**Comment by adam3smith** [comment]
```
{
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "release": {
      "Zotero": {
        "version": "5.0.56-beta.11+66ed33b9f",
        "platform": "Win32",
        "oscpu": "Windows NT 10.0; WOW64",
        "locale": "en-US",
        "appName": "Zotero",
        "appVersion": "5.0.56-beta.11+66ed33b9f",
        "isZotero": true,
        "isJurisM": false
      },
      "BetterBibTeX": "5.0.197.2737"
    },
    "preferences": {
      "DOIandURL": "both",
      "asciiBibLaTeX": false,
      "asciiBibTeX": true,
      "autoAbbrev": false,
      "autoAbbrevStyle": "",
      "autoExport": "immediate",
      "autoExportIdleWait": 10,
      "autoPin": false,
      "biblatexExtendedDateFormat": true,
      "biblatexExtendedNameFormat": false,
      "bibtexParticleNoOp": false,
      "bibtexURL": "off",
      "cacheFlushInterval": 5,
      "citeCommand": "cite",
      "citekeyFold": true,
      "citekeyFormat": "[auth][shorttitle][year]",
      "citeprocNoteCitekey": false,
      "csquotes": "",
      "debug": false,
      "debugLog": "",
      "itemObserverDelay": 100,
      "jabrefFormat": 0,
      "jurismPreferredLanguage": "",
      "keyConflictPolicy": "keep",
      "keyScope": "library",
      "kuroshiro": false,
      "lockedInit": false,
      "parseParticles": true,
      "postscript": "",
      "preserveBibTeXVariables": false,
      "qualityReport": false,
      "quickCopyMode": "latex",
      "quickCopyPandocBrackets": false,
      "rawLaTag": "#LaTeX",
      "scrubDatabase": false,
      "skipFields": [],
      "skipWords": [
        "a",
        "ab",
        "aboard",
        "about",
        "above",
        "across",
        "after",
        "against",
        "al",
        "along",
        "amid",
        "among",
        "an",
        "and",
        "anti",
        "around",
        "as",
        "at",
        "before",
        "behind",
        "below",
        "beneath",
        "beside",
        "besides",
        "between",
        "beyond",
        "but",
        "by",
        "d",
        "da",
        "das",
        "de",
        "del",
        "dell",
        "dello",
        "dei",
        "degli",
        "della",
        "dell",
        "delle",
        "dem",
        "den",
        "der",
        "des",
        "despite",
        "die",
        "do",
        "down",
        "du",
        "during",
        "ein",
        "eine",
        "einem",
        "einen",
        "einer",
        "eines",
        "el",
        "en",
        "et",
        "except",
        "for",
        "from",
        "gli",
        "i",
        "il",
        "in",
        "inside",
        "into",
        "is",
        "l",
        "la",
        "las",
        "le",
        "les",
        "like",
        "lo",
        "los",
        "near",
        "nor",
        "of",
        "off",
        "on",
        "onto",
        "or",
        "over",
        "past",
        "per",
        "plus",
        "round",
        "save",
        "since",
        "so",
        "some",
        "sur",
        "than",
        "the",
        "through",
        "to",
        "toward",
        "towards",
        "un",
        "una",
        "unas",
        "under",
        "underneath",
        "une",
        "unlike",
        "uno",
        "unos",
        "until",
        "up",
        "upon",
        "versus",
        "via",
        "von",
        "while",
        "with",
        "within",
        "without",
        "yet",
        "zu",
        "zum"
      ],
      "sorted": false,
      "strings": "",
      "suppressTitleCase": true,
      "testing": false,
      "warnBulkModify": 10
    },
    "options": {
      "exportNotes": false,
      "exportFileData": false,
      "exportPath": "C:\\Users\\Sebastian\\Desktop"
    }
  },
  "collections": {},
  "items": [
    {
      "itemType": "patent",
      "url": "http://v3.espacenet.com/textdoc?IDX=EP1700367",
      "extra": "Citation Key: laufenberg \nbibtex[holder=undefinedundefinedundefined;type=patenteu]",
      "assignee": "Robert Bosch GmbH",
      "country": "France",
      "title": "Elektrische Einrichtung und Betriebsverfahren",
      "creators": [
        {
          "firstName": "Xaver",
          "lastName": "Laufenberg",
          "creatorType": "inventor"
        },
        {
          "firstName": "Dominique",
          "lastName": "Eynius",
          "creatorType": "inventor"
        },
        {
          "firstName": "Helmut",
          "lastName": "Suelzle",
          "creatorType": "inventor"
        },
        {
          "firstName": "Stephan",
          "lastName": "Usbeck",
          "creatorType": "inventor"
        },
        {
          "firstName": "Matthias",
          "lastName": "Spaeth",
          "creatorType": "inventor"
        },
        {
          "firstName": "Miriam",
          "lastName": "Neuser-Hoffmann",
          "creatorType": "inventor"
        },
        {
          "firstName": "Christian",
          "lastName": "Myrzik",
          "creatorType": "inventor"
        },
        {
          "firstName": "Manfred",
          "lastName": "Schmid",
          "creatorType": "inventor"
        },
        {
          "firstName": "Franz",
          "lastName": "Nietfeld",
          "creatorType": "inventor"
        },
        {
          "firstName": "Alexander",
          "lastName": "Thiel",
          "creatorType": "inventor"
        },
        {
          "firstName": "Harald",
          "lastName": "Braun",
          "creatorType": "inventor"
        },
        {
          "firstName": "Norbert",
          "lastName": "Ebner",
          "creatorType": "inventor"
        }
      ],
      "tags": [],
      "relations": [],
      "dateAdded": "2018-09-05T14:09:46Z",
      "dateModified": "2018-09-05T14:10:53Z",
      "uri": "http://zotero.org/users/2433/items/SH3W7YJ6",
      "attachments": [],
      "notes": [],
      "itemID": 140644,
      "citekey": "laufenberg",
      "date": "2006-09-13",
      "number": "EP1700367"
    }
  ]
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2739](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2739.xpi) ("more test cases for #1060")

Install in Zotero by downloading [test build 5.0.197.2739](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2739.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
How did you grab this entry? BibLaTeX (likely BBT) import from http://v3.espacenet.com/textdoc?IDX=EP1700367 ? because the `undefined`s are already in the `extra` field, BBT is only reproducing them.

**Comment by adam3smith** [comment]
oh sorry! didn't see that. Import from clipboard of what moewe posted above, so the bug isn't export but import.

**Comment by retorquere** [comment]
No worries, that gives me a clear target

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2741](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2741.xpi) ("parse patent.holder")

Install in Zotero by downloading [test build 5.0.197.2741](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2741.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by adam3smith** [comment]
I'm now getting undefinedundefinedundefined in the assignee field on import. Also, it's not adding back the country code to the number (i.e. patenteu type should append EP to the beginning of `patentNumber`.

Export is perfect.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2742](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2742.xpi) ("restore patent number prefix on import")

Install in Zotero by downloading [test build 5.0.197.2742](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2742.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2744](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2744.xpi) ("import test for #1060")

Install in Zotero by downloading [test build 5.0.197.2744](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2744.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Both `holder` and the prefix should now import cleanly.
