### ISSUE TITLE
Auto-export locks up Zotero during large exports

### ISSUE THREAD

**Issue by danmeek** [retorquere/zotero-better-bibtex#1061]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

## Non-export problems with BBT

When the BBT add-on is enabled in Zotero for Mac, most interactions with items in collections result in the app freezing -- 15+ seconds of spinning beachball. When the add-on is disabled, this stops.

In addition, the BBT report error function fails when uploading the report (see screencaps attached). I've copied the text from the report here:
https://www.dropbox.com/s/gaa31oadvay69tn/BBT%20error%20report.rtf?dl=0 

Mac OS is High Sierra 10.13.5, Zotero is up-to-date, BBT is version 5.0.196.

A couple of possible contributing issues: my BBT library is saved in my Dropbox; and my Zotero storage was locked because I'd forgotten to renew. But I've paused syncing on Dropbox and paid my renewal for Zotero storage and the problem persists after multiple restarts.

<img width="486" alt="screenshot 2018-09-05 12 27 46" src="https://user-images.githubusercontent.com/26449951/45070419-86925780-b114-11e8-877a-ec904c624e71.png">

**Comment by retorquere** [comment]
There are some macos-specific fixes in the version posted in #863 - can you see if that at least makes the wizard.advance error go away? How many references do you have in your library?

**Comment by danmeek** [comment]
Thanks for getting back to me so quickly. I have a bit over 3,500
references in my library.

Also, it's just the BBT auto-export that I save in my Dropbox -- the Zotero
library is local, and syncs to the Zotero server.

I gave the version posted in #863 a go. I still get the beachball when I
interact with BBT, e.g. it occurs every time I ask it to refresh a citekey.
And the error reporting wizard still does not work. Sorry the Mac is giving
you so much trouble.

Many thanks,
Daniel

**Comment by danmeek** [comment]
Wait, the error report did complete, after about 3 minutes!

My report id is: C9MS5WAG-euc

Cheers,
Daniel

**Comment by retorquere** [comment]
3.5k isn't so much. I will have to enable tracing to see what's going on.

First. can you tell me which of these regions is fastest for you?

**Comment by retorquere** [comment]
https://www.cloudping.info/

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2745](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2745.xpi) ("faster s3 ping")

Install in Zotero by downloading [test build 5.0.197.2745](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2745.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2746](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2746.xpi) ("set autosave to an hour")

Install in Zotero by downloading [test build 5.0.197.2746](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2746.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
2746 should make log submission slightly faster and spaces out autosave more. Can you see if it helps?

**Comment by retorquere** [comment]
How big the the better-bibtex.sqlite file when Zotero is closed (with cmd-Q)?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.198.2752](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.198.2752.xpi) ("Merge branch 'master' into 1061")

Install in Zotero by downloading [test build 5.0.198.2752](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.198.2752.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by danmeek** [comment]
Okay, my closest region is Asia Pacific (Sydney), and my BBT sqlite file is
1.7mB.

With that 2746 build, the error reporting wizard completes a lot faster.
Report ID: M4YVEK6M-apse

Also, I hit 'reset cache' in BBT settings, and I'm not sure if it was that
or the new build but I'm not getting anymore beachball!

Cheers,
Daniel

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.198.2754](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.198.2754.xpi) ("reset autosave to 5s")

Install in Zotero by downloading [test build 5.0.198.2754](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.198.2754.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
The new build resets the save timer to what it was before, see how that works.

If you do see the problem again, please close zotero (cmd-Q) and take note of the file sizes in the better-bibtex directory in the zotero directory before resetting the cache. If the size of the cache is involved it'd be good to know how much data we're dealing with. But I'm seeing some really large save times for the main database (which is separate from the cache), I'm looking into changing the way the database is saved.

**Comment by danmeek** [comment]
Ok, I think I've found the problem.

The file sizes in the better-bibtex directory are all <2mb.

I'm using the Bibtex auto-export function to support a workflow for
inserting citekeys into markdown texts in Ulysses, and pandoc gets called
to replace the citekeys when I generate RTF output. Zotero freezes up when
auto-export is set to 'on change', and it doesn't freeze up when
auto-export is 'when idle'. I watched the settings window and the
freeze-ups occur when the auto-export status changes to 'scheduled' and end
when it changes to 'done'. And it's triggered by changing something that
affects the citekey, e.g. tweaking the publication date field.

Cheers,
Daniel

**Comment by retorquere** [comment]
Right -- fixing this requires [changes in Zotero](https://groups.google.com/forum/#!topic/zotero-dev/lHYEtdgPHCE), sorry.

Still, 15 seconds is still a lot for 3.5k references, assuming the cache is in order. Can you check that your auto-export caches are at or near 100% in the BBT preferences?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.198.2756](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.198.2756.xpi) ("save to json")

Install in Zotero by downloading [test build 5.0.198.2756](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.198.2756.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
2757 will, o.a., log how long the export actually takes. From this I could tell whether the cache is being used - -the cache makes a huge difference, I have a test that does 12k item which takes 194 seconds on a cold cache but 21 on a hot cache.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.201.2794](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.201.2794.xpi) ("add typings")

Install in Zotero by downloading [test build 5.0.201.2794](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.201.2794.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
2794 adds a trick to partially prevent lockups during export. The actual fix requires a planned change in Zotero, but there's no timeline for the fix. While any single export runs, Zotero just locks up, there's nothing I can do about that; BBT is an odd duck because it makes people do large exports, which is not customary for Zotero users. So what happens now is:

1. Start a large export on an empty cache
2. While the export runs, pre-cached items are picked from the cache (which will be none if 1. is true), the cache is populated for each item in the export
3. Subsequent exports will find a pre-filled cache for all or most of the exported items, so it should (hopefully) be fast enough to lock up Zotero for an imperceptibly small time

Problem is, if you change anything in the BBT prefs, the cache is cleared, so any time you do this you start from 1. and not from 2.

2794 adds a configurable cheat -- before BBT kicks off 1., it looks at how many uncached items will be exported, and if there are too many (with "too many" being configurable) it will pre-fill the cache for those items before the actual import starts, with individual pre-fills again locking up the UI, but because they're just single items, that should per-item be unnoticeable. This pre-fill does take time, so exporting an unfilled cache will take a lot more time, but during the pre-fill it will not lock the UI, and during the actual following export, it will be as fast as technically possible because everything comes from the cache.

This behavior is off by default but can be turned on by setting the [hidden preference](https://retorque.re/zotero-better-bibtex/configuration/#hidden-preferences) `primeExportCache` to a non-zero number; the number is how many non-cached items there have to be to trigger the behavior.

The change in Zotero will make this unnecessary, but in the meantime, it may help.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.201.2804](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.201.2804.xpi) ("configurable prime threshold/batch")

Install in Zotero by downloading [test build 5.0.201.2804](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.201.2804.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by danmeek** [comment]
Hi Emiliano,

I think this problem might have recurred — I have on-update set to 'idle' but I'm still getting Zotero lock-ups and this message appears from BetterBibtex.


<img width="260" alt="Screen Shot 2019-04-15 at 1 05 39 PM" src="https://user-images.githubusercontent.com/26449951/56151516-69ade480-5f7f-11e9-9772-9b4171ba3bec.png">

Cheers,
Daniel

**Comment by retorquere** [comment]
Did Zotero freeze while you were using it (which means the idle detection would be wrong), or did it freeze after it went idle but would then not respond until the export was done?

**Comment by retorquere** [comment]
Do you have `primeExportCache` set BTW?

**Comment by retorquere** [comment]
Really can't do anything without more information.

**Comment by danmeek** [comment]
Apologies, having a busy week. These are my settings for primeExportCache, I haven't changed them:

Cheers,
Daniel

**Comment by retorquere** [comment]
I was mistaken, it should have been `autoExportPrimeExportCacheThreshold`, but I think you mailed in response with an attachment; github discards attachments. If you send a BBT error report I als get your BBT settings. Be sure to update first, a new version has just been released.

**Comment by danmeek** [comment]
Hi again,

Sorry for the slow response — I'm in PhD write-up.
I haven't changed any of the preset values for Zotero/BBT.
I've submitted an error report: REQV743G-euc
It was running the April 19 update of BBT.
Many thanks,
Daniel

**Comment by retorquere** [comment]
You have it on, probably because BBT automatically turned it on when it saw the large auto-export. Looks like the cache priming isn't always working though because I see some 5k uncached items entering the export twice.

I know how busy a PhD can be, but if I'm going to tackle this one I'll need your help. Is this something you can do right now?

**Comment by danmeek** [comment]
Yep, happy to help — if I go quiet please don't hesitate to remind me though!

Cheers,
Daniel

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.68.3814](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3814.xpi) ("more logging for cache priming")

Install in Zotero by downloading [test build 5.1.68.3814](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3814.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try triggering an auto-export with 3814 and post a new debug log?

**Comment by kwolfert** [comment]
Maybe I can help- I'm having the same problem. I submitted an error report: HBEIQ5YI-euc

Thanks,
Katie

**Comment by retorquere** [comment]
I need a debug log specifically from 3814, you're on 5.1.68 (release).

**Comment by kwolfert** [comment]
Okay no problem, just installed 3814 and was able to reproduce the error. Report: HMF9FVKR-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.68.3823](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3823.xpi) ("log uncached query")

Install in Zotero by downloading [test build 5.1.68.3823](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3823.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
OK, that does indeed reproduce the problem. I can see the cache being filled, and I have some idea of why this may be happening -- it may be the preference overrides in the auto-export. Please generate a new debug log with 3823.

**Comment by kwolfert** [comment]
Okay here it is: I5574CD3-euc

Hopefully the main problem is fixed soon!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.68.3824](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3824.xpi) ("prefs override cache search")

Install in Zotero by downloading [test build 5.1.68.3824](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3824.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Right, prefs overrides were at least part of the problem. I'd appreciate a new debug log with 3824.

**Comment by danmeek** [comment]
Hi all,

I've installed 3824 and I haven't noticed any slowdowns while using Zotero itself — doing the kinds of things that previously caused slowdowns (e.g. adding a new item, changing an author name so that the BBTX key changed as well). In fact, Zotero felt a lot quicker to respond.
However, I did get a massive slowdown when I did the error report — trying to highlight and copy the report ID, the interface reacted about 15 seconds after I clicked it.
Debug id: R4Z4JJYR-euc
Cheers,
Daniel

**Comment by retorquere** [comment]
I can't really tell whether it helped -- I can find no auto-exports triggered in R4Z4JJYR, but that may be explained by the fact that auto-export is set to "idle" on your system, and it likely didn't fall idle. Did you manually trigger the auto-export in I5574CD3? You also had auto-export set to on-idle there, and while I don't see the system falling idle, I do see an auto-export there.

Not sure where the slowdown in the debug submission comes from, but fixing the auto-export slowdowns takes priority.

**Comment by kwolfert** [comment]
Okay I was able to trigger an auto-export error with 3824. ID is F6ARW6VN-euc. Interestingly, I didn't experience a slowdown in the error reporting interface.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3840](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3840.xpi) ("Merge branch 'master' into gh-1061")

Install in Zotero by downloading [test build 5.1.72.3840](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3840.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you get me a new debug log using 3840? I haven't been able to replicate the problem.

**Comment by danmeek** [comment]
Hi again,

I've downloaded the new update, no slowdowns visible when adding new items, moving items, renaming authors etc, but Zotero has crashed completely (spinning beachball) when I've gone to do the error report.
Cheers,
Daniel

**Comment by retorquere** [comment]
Is that reproducible? I can't make that happen on my end.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3841](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3841.xpi) ("cleanup")

Install in Zotero by downloading [test build 5.1.72.3841](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3841.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3843](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3843.xpi) ("Merge branch 'master' into gh-1061")

Install in Zotero by downloading [test build 5.1.72.3843](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3843.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Man I'll be happy when I can ditch the cache when Zotero implements async exporters. Give 3843 a go, if possible triggering an auto-export after clearing the cache in BBTs advanced prefs. If possible, tick the `send cache` box in the debug log screen. It will be slower, but between the logs and the actual cache contents, maybe I can figure out what's happening.

**Comment by kwolfert** [comment]
I downloaded 3843, cleared the cache, and triggered an auto-export. Hopefully this is helpful! FXW6SMYU-euc. My error reporting is still fine- no crashing

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3849](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3849.xpi) ("more logging")

Install in Zotero by downloading [test build 5.1.72.3849](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3849.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I still see it filling the cache and then at the end claiming that it hasn't. Can you do it again with 3849? That adds more logging still.

**Comment by kwolfert** [comment]
Sure! Here it is: JQ8UKF4K-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3853](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3853.xpi) ("does sqlite give me string IDs? That would be nasty")

Install in Zotero by downloading [test build 5.1.72.3853](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3853.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
You know the spiel by now 🙄 . More logging.

**Comment by kwolfert** [comment]
Yep, here it is: 3XW7Y33S-euc

Thank you for your work on this :)

**Comment by danmeek** [comment]
Hi again,

With 3840 I got the BBTX popup noting a 140-second export: EJ2PCEAZ-euc
With 3853 I could see Zotero doing a sync, running incredibly slowly, and after maybe 4 minutes it froze altogether.
Cheers,
Daniel

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3859](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3859.xpi) ("not all items are cachable?")

Install in Zotero by downloading [test build 5.1.72.3859](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3859.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Unfortunately I really need logs from the latest build posted here. I'll need a new one from 3859 -- it looks like the priming results are not always offered to the cache, but I don't yet know why.

**Comment by kwolfert** [comment]
Okay here it is: VPGKYFPZ-euc

**Comment by retorquere** [comment]
It's not the exports not being offered to the cache... some items are offered to the primer but they don't seem to make it to the exporter. A new build has been scheduled with more logging which will be announced here in a few minutes.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3865](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3865.xpi) ("why this can't just be static build info... never changes at runtime")

Install in Zotero by downloading [test build 5.1.72.3865](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3865.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you go into `Preferences` - `Advanced` - `Files and Folders` - `Show data directory`, quit Zotero (so that'd be cmd-Q if you're on a Mac) to make sure it is not running, and then get me a zip of the `zotero` folder of the folder that just opened? I need to get this reproducible locally.

**Comment by danmeek** [comment]
Ok, doing that now. I just noticed the Zotero folder is 10gb and the better-bibtex folder is about 21mb — is that a possible cause of the issue? I'll e-mail through a Dropbox link as soon as the zip is done.

Cheers,
Daniel

**Comment by retorquere** [comment]
That's big, but cache priming is supposed to ameliorate the problems that it would bring. To be clear -- Zotero just always locks up when doing any kind of export, that's nothing I can fix, it's just that in most uses of Zotero, exports are so small and infrequent as to not matter. The problem here is that

* BBT users are more likely to do frequent exports
* BBT users are more likely to do larger exports

The way I try to work around this is to detect potentially large exports before they happen, export them in very small chunks (which will individually lock up Zotero, but for hopefully unnoticeably short periods each), grab the output and cache it, and then kick off the actual export, using the cached output. This will still lock up Zotero, but as BBT doesn't have to do any "work" during that export, it would be as short as is possible in current Zotero.

For some reasons, even when I request the batch export (of size 10 currently), only 3 or for are actually exported, so not even half of the priming is effective... but when I request during the prime whether that batch is in the cache, I'm getting "yes". No idea what's going on there yet.

The proper solution is just for Zotero to allow me to say inside the export "it's OK to pause the export here, you can do something else" like it is possible in the imports. That will entirely solve this problem, and I could do away with the cache entirely. This change to Zotero is planned, but there's no ETA.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.74.3884](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.74.3884.xpi) ("Merge branch 'master' into gh-1061")

Install in Zotero by downloading [test build 5.1.74.3884](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.74.3884.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.75.3890](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.75.3890.xpi) ("Merge branch 'master' into gh-1061")

Install in Zotero by downloading [test build 5.1.75.3890](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.75.3890.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I have a bit of time today, so if the zip is ready, I'm really keen to get to the bottom of this.

**Comment by danmeek** [comment]
Hey Emiliano,

Thanks for the explanation in your earlier e-mail — makes sense.
Here is the zip: https://www.dropbox.com/s/if05g6chg7wn4ig/Zotero.zip?dl=0
Warm regards,
Daniel

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.75.3892](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.75.3892.xpi) ("so bottom line: we need async export. For real.")

Install in Zotero by downloading [test build 5.1.75.3892](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.75.3892.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Thanks for that - that got me a little further. I have added a small delay between priming batches and have made the priming batches smaller, and this makes the zotero ui more responsive.

The downside to all this is that the delays mean that the priming takes longer (you can see the cache filling in the preferences auto export tab), and the smaller batches also make it take longer, as each individual export action incurs overhead.

There's hidden preferences you can tweak this with, but it's really just choosing one downside over the other (slower priming vs longer freezes). The true fix is async export.

**Comment by retorquere** [comment]
Can you try 3892 to see if it (sufficiently) solves the problem for you? And if not, submit a new debug log?

**Comment by kwolfert** [comment]
Sorry I was away from my work computer over the weekend! The newest build is working well for me- less freezing. Thank you again your work on this

**Comment by retorquere** [comment]
Superb. I'm going to strip some of the logging, and then I'll put out a new release with this.

**Comment by retorquere** [comment]
I'm going to leave this issue open because to really solve it, I need (planned) changes in Zotero

**Comment by danmeek** [comment]
Hi Emiliano,

I tried 3892 and didn't spot any noticeable slowdowns with it!
Debug: Q4SXYM2Z-euc
Let me know if there's anything I can do to help make the case for raising the priority of async export in the Zotero roadmap.
Many thanks for your time and energy, Emiliano.
Best,
Daniel

**Comment by retorquere** [comment]
5.1.76 has been released that has the changes from 3892. It's still far from idea because the responsiveness comes at the cost of substantially slower auto-exports.

I'm not entirely sure what the best way is to let Zotero know that the async change is useful to others. It's being discussed [on their github](https://github.com/zotero/zotero/pull/1609), [on the Zotero forums](https://forums.zotero.org/discussion/comment/329898) and [the Zotero development discussion group](https://groups.google.com/forum/#!searchin/zotero-dev/async$20export%7Csort:date/zotero-dev/lHYEtdgPHCE/6t6WlQyLFwAJ), but they know I need this, it's planned, and I don't want it to come across like I'm sending people over to harass them...

**Comment by retorquere** [comment]
I'm going to look into splitting it off to a worker thread. This is going to be a major undertaking but should solve the problem once and for all.

**Comment by danmeek** [comment]
Hi Emiliano,

Thank you so much for your work on this. I'd be happy to continue as a beta
tester — do you want to add me on an IM platform to make communication
easier?

Cheers
Daniel

**Comment by retorquere** [comment]
Nah, github works good for me. And it will take a while to get this working, probably something for the xmas holiday.

**Comment by lyndondrake** [comment]
If you ever want testing on this, I'm happy to help too

**Comment by retorquere** [comment]
That will become relevant in the very near future. I'm putting the last touches on an overhaul that will do BBT exports in a separate thread, which should make these exports entirely painless.

Gitter works well for chat for me.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5487](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5487.xpi) ("BOOYAH!")

Install in Zotero by downloading [test build 5.1.176.5487](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5487.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
5487 does half the job currently. Regular exports will be blocking, but auto-export should be smooth. I'm still looking whether I can do the same for regular exports.

**Comment by lyndondrake** [comment]
Just tried it. Seems to work great!

**Comment by retorquere** [comment]
I very nearly have it working for all bbt exports.

**Comment by retorquere** [comment]
Note to self:

* [ ] test attachment exports
* [ ] keep registry of running threads so I can check whether they've been properly closed

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5495](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5495.xpi) ("add worker stats to error log")

Install in Zotero by downloading [test build 5.1.176.5495](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5495.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
@anjiro, @lyndondrake, @danmeek, @kwolfert: I'd really love to hear from you guys how 5495 does for you. This should fix the problems of BBT blocking Zotero once and for all -- all exports<sup>*</sup>, regular and auto-exports, are now background exports so should not affect Zotero at all. I'm really keen to get this into a formal release, but it'd be good to have confirmation that this indeed does remove the lockup problem for you guys. No more cache priming! In fact the preferences for cache priming are gone in 5945. I'm **super** stoked about this, I've been brewing on this idea for a long time, and after a few insights it turned out to be a lot less work than I had initially thought.

<hr>
<sup>*</sup> except drag-and-drop, which is mostly for citations, but which I can't fix this way because of limitations imposed by the Firefox platform

**Comment by lyndondrake** [comment]
Works for me!

**Comment by retorquere** [comment]
This is so freaking **AWESOME**. BBT exports now run on their own thread. This is not supposed to be possible under the current Zotero architecture -- I mean, BBT does a lot of things that shouldn't be possible, but this one is the most out-there of them all. I am pretty proud of myself for this one -- this should be a game-changer for large libraries. Auto-exports of thousands of entries won't be faster than it was, but it should be almost unnoticeable while it runs in terms of how usable Zotero stays. And multiple auto-exports will just run simultaneously (*actually* simultaniously, not just async-interleaved) on different cores if you have a multi-core PC (and who doesn't these days).

**WOOHOO!**

**Comment by anjiro** [comment]
Yes! This seems to work for me as well. I tried removing a couple thousand items from a collection and Zotero continues to respond. Watching the auto-export preference window, it looks like it runs multiple times ("status" changes from "running" to "done" several times) and Zotero's CPU usage hits 600+%, but things are still usable! 🎉

**Comment by anjiro** [comment]
The CPU could also be Zotero sync running, but I don't have time to check that at the moment…

**Comment by retorquere** [comment]
Yeah how often the auto-export is actually kicked off depends on the timing with which Zotero notifies BBT of deletes. When a notification comes in I delay the start of auto-exports to see if more notifications come in to limit unnecessary exports, and every time a new notification does come in within the delay window, the delay starts anew. The delay is set to 1s by default, but you can set it to a larger value by changing `extensions.zotero.translators.better-bibtex.autoExportDelay` (which is a number in seconds). With thousands of entries being changed at once, 5s wouldn't be unreasonable I think. If the delay is not sufficient to cover the time Zotero takes to actually delete a large batch of items, you'll have multiple export running targeting the same file, but since the writes to the output file are atomic, the last one should win (generally, come to think of it... I don't control the CPU time slicing, and if it's a tight race, `n-1` might finish before `n`).

It's entirely likely that the CPU would show 600% if overlapping exports are running -- you can see in the Advanced pane of BBT how many workers are currently running and how many have been running (including the currently active ones) since Zotero started, but exports are entirely CPU-bound, so they'll spike the CPU, and (at least if you're checking the load with `top` on a unixoid) 600% means "600% of 1 CPU", so on an 8-core machine, that could mean 2 cores are very bored (see [here](https://unix.stackexchange.com/questions/34435/top-output-cpu-usage-100)). So under that interpretation, 600% wouldn't be worrying.

Man I'm so **very** stoked that this works so well. Much to my amazement I by and large got it to work in one large activity -- the first test that actually ran simply worked as planned, which was a bit of a surprise, I'll tell you, for this significant a change. Don't worry, if any single test in my suite fails (and I have some 250 or upwards test), no new version will be announced on an issue, because the build tool chain automatically posts builds after the tests clear. One test fails => no build is published (test builds or prod builds).

**Comment by retorquere** [comment]
For completeness sake: with this change (which I'm going to roll out to a new release when I have a few other minor issues closed) it should be safe to have auto-export set to `on change` even for large libraries.

**Comment by kwolfert** [comment]
Seems to be working for me too!

**Comment by retorquere** [comment]
Superb!
