### ISSUE TITLE
Possible to remove leading slash on exported relative path?

### ISSUE THREAD

**Issue by abradd** [retorquere/zotero-better-bibtex#1065]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Is it possible to prevent placement of the preceding slash on exported relative file paths?

When exporting I see a file entry like:

`file = {/Bursac et al/2003_Cultivation in Rotating Bioreactors Promotes Maintenance of Cardiac Myocyte.pdf}`.

What I would like is:

`file = {Bursac et al/2003_Cultivation in Rotating Bioreactors Promotes Maintenance of Cardiac Myocyte.pdf}`.

**Comment by retorquere** [comment]
Is this an export with file export on? Or do these paths refer to linked files?

**Comment by abradd** [comment]
These are linked files that were previously exported by ZotFile.

**Comment by retorquere** [comment]
And was this particular export done with or without "export file data" checked? Without I think?

**Comment by abradd** [comment]
The export was done without selecting "Export Files". Does the 
path generation change depending on whether or not this was 
selected?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.203.2813](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.203.2813.xpi) ("fixes #1065")

Install in Zotero by downloading [test build 5.0.203.2813](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.203.2813.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Yes -- when files are exported you'll notice you're selecting a directory, not a file. Some things are handled differently based on that.

Try 2813.

**Comment by abradd** [comment]
That works! Thanks
