### ISSUE TITLE
ADS exports dates like 1993-00-00

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#1066]
Example: https://ui.adsabs.harvard.edu/#abs/1993AIPC..280..291W/abstract

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.0.2833](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.0.2833.xpi) ("fixes #1066")

Install in Zotero by downloading [test build 5.1.0.2833](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.0.2833.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
