### ISSUE TITLE
Bulk Drag and drop/hotkey citations

### ISSUE THREAD

**Issue by nicolas-navarro-guerrero** [retorquere/zotero-better-bibtex#1068]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [ ] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [ ] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

## Exporting references
I would like to be able to drag and drop a number of entries at once using "Better BibTeX Citation Key Quick Copy"

\cite{citation1, citation2, citation3,....}

**Comment by nicolas-navarro-guerrero** [comment]
Sorry, it works. I just realized it is limited to 50 entries at the time, that is good enough for me.

**Comment by retorquere** [comment]
Not limited by me though, that must be a Zotero limitation
