### ISSUE TITLE
No booktitle field when exporting references from conference proceedings

### ISSUE THREAD

**Issue by henrygouk** [retorquere/zotero-better-bibtex#1069]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

## Exporting references 
When using the Better BibTex exporter to export an `@inproceedings` reference, the `booktitle` field is not generated. I have managed to come up with a workaround by adding this to the postscript field in the Advanced settings for Better BibTeX:

```
if(item.itemType == "conferencePaper" ) {
    this.add({name: "booktitle", replace: false, value: item.conferenceName});
}
```

The Report ID generated by the bug reporter is C8B44FTB-apse

**Comment by henrygouk** [comment]
Looks good!

**Comment by retorquere** [comment]
5.1.2 has the fix.
