### ISSUE TITLE
After latest MAC OS update, Zotero freezes when trying to link a pdf to a reference 

### ISSUE THREAD

**Issue by PaulP53** [retorquere/zotero-better-bibtex#1070]
When I try to link a file to any given reference in Zotero, Zotero 5.0.55.1 freezes. It may happen immediately after having clicked the symbol for establishing the link or somewhere on my way to the folder in which the pdf is stored. Today, I could manage once, after having restarted the PC, but a next attempt failed again. The problem has occurred after I have updated my Mac OS to OS 10.14 (Mojave).

**Comment by retorquere** [comment]
Do you have any auto exports set up?

**Comment by PaulP53** [comment]
Not as far as I know. Here are two screenshots from the preferences.

**Comment by retorquere** [comment]
I can't see attachments that are mailed in. But I see [here](https://forums.zotero.org/discussion/comment/317594#Comment_317594) that the new Zotero beta seems to help, can you try that?

**Comment by PaulP53** [comment]
I’ll try and give feed back.

**Comment by PaulP53** [comment]
Yes, with the beta version it works. Thanks!
