### ISSUE TITLE
"Loading citation keys" never completes and Better BibTeX pref pane does not appear

### ISSUE THREAD

**Issue by rolandproducts** [retorquere/zotero-better-bibtex#1073]
- [✔︎] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [✔︎] I am posting a single question, bug or feature request
- [✔︎] I have included a descriptive subject of the problem
- [✔︎] I am available for follow-up questions and testing
- [✔︎] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

HVDH2A5L-apse

## Non-export problems with BBT

I recently upgraded to BBT latest, and now on start the "loading citation keys" pop up never completes (Citekey values appear as the replacement character,  �). When I open preferences, the BBT pane is not populated with any content

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.2.2906](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.2.2906.xpi) ("come *on* sourceforge!")

Install in Zotero by downloading [test build 5.1.2.2906](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.2.2906.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Is it possible you upgraded from a long time ago? Your BBT database has entries that have old (and now unexpected) data, at some point I removed the check for performance reasons thinking everyone had upgraded already.

Installing 2906 and restarting should clean out the unexpected data. After that you can just go back to the regular release (which is the same but without the check)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.2.2909](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.2.2909.xpi) ("OH COME ON SOURCEFORGE!")

Install in Zotero by downloading [test build 5.1.2.2909](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.2.2909.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by rolandproducts** [comment]
Yes, it was a long time between updates. 2906 resolved the issue - thanks!

**Comment by rolandproducts** [comment]
> Installing 2906 and restarting should clean out the unexpected data. After that you can just go back to the regular release (which is the same but without the check)

Thanks! 2906 resolved the issue.
