### ISSUE TITLE
Easier file export for collection hierarchy 

### ISSUE THREAD

**Issue by ixil** [retorquere/zotero-better-bibtex#1074]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Feature Request: Easier File Export per collection generation

## Background
I realise this may not fit the workflow for some, but I think for the goal of this project 'latex holdouts' it fits.
I like to sort papers through the collection/folder structure by topic. 
Then using the exporter and then within my text editor (vim) I can take advantage of the autocompletion.
Previously I used Mendeley and it generated a per folder/collection .bib file which I could symlink to the project/paper/section I was working on and take advantage of the cite-keys being generated and immediately available.

It would be great if for numerous / many collections it were easier to generate multiple export files - AFAIK this is not possible without manually going by collection and creating an export. For people importing a large collection / who like to do lots of sorting this is very tedious.

(If this feature exists this feature then is about improving the documentation of said feature!)

## The feature

- Automatically produced individual bibliography files
- Format possibly selectable using a menu option
- Directory where to place these files possibly determinable?

## Foreseen Problems

- **How to avoid naming clashes between sub-collections?** create a directory per library, and per collection prefix the collection name with the collection-hierarchy. This also keeps in line with the `keep keys unique` options

**Comment by retorquere** [comment]
When you say "automatically", you means that newly created collections would also automatically be added? Or do you mean some batch feature where you say "add all collections to auto-export now? The latter would be a lot less work than the former.

**Comment by retorquere** [comment]
I'm not entirely sold on the idea yet. I use the same kind of organization (one collection per paper) but that's a one-time export to keep updated for that paper. Unless you start several new papers each week, it seems like little gain is to be had here.

**Comment by ixil** [comment]
> When you say "automatically", you means that newly created collections would also automatically be added? Or do you mean some batch feature where you say "add all collections to auto-export now? The latter would be a lot less work than the former.

Yes. For new subcollections this would be ideal.

The idea came from what Mendeley does, where every 'collection' is generated as bibtex. 
![mendeley_bibtex_export](https://user-images.githubusercontent.com/2058587/47434693-5b86c480-d7a3-11e8-837b-cd88419f1ca2.png)

The result is a folder of .bib files for the whole library. This may be the easiest option, though not necessarily the most performant - but I'm not sure how many papers and folders you would need to run into this as a problem.
In my workflow this is helpful as I can just sync these files and share them with collaborators or on projects I can symlink them into the project. 
I also generally add lots of papers then sort them into categories, often create new collection hierarchies.
Working on a project I also just let latex take care of only rendering used files in the bibliography and I can easily access any bibliography and citekey autocompletion but just adding another collection as an additional bibliography.

**Comment by retorquere** [comment]
What does "one bibtex file per document" mean? Document in what sense?

**Comment by ixil** [comment]
Per document I assume to be per item in a collection - I have not used the option and I don't see this as a particularly useful feature at all, however the `file per group` would be equivalent to a `file per collection`.
Since you cannot select more than one folder at a time in zotero manually going through the export system (`click on collection -> +keep updated -> ok -> select folder location` is very tedious.

**Comment by retorquere** [comment]
Can't really be per reference, that would make no sense.

I'm still thinking about a low-impact way to get close to what you need. Exact replication has a lot of potential papercuts - a new collection appears, bbt would have to react, user edits the target folder and bbt would have to move the files, etc. If there's existing functionality I can hitch a ride on, that has my preference (which is why auto export works the way it does). It would also mean less UI work - I'm absolutely not fond of UI work.

**Comment by ixil** [comment]
> Can't really be per reference, that would make no sense.
I tried it out on Mendeley (the per document option), and apparently it does - seems completely useless to me

> I'm still thinking about a low-impact way to get close to what you need. Exact replication has a lot of potential papercuts - a new collection appears, bbt would have to react, user edits the target folder and bbt would have to move the files, etc. If there's existing functionality I can hitch a ride on, that has my preference (which is why auto export works the way it does). It would also mean less UI work - I'm absolutely not fond of UI work.

It may be that underlying this is a feature for Zotero to support (if it doesn't already), being able to hook into events seems to me like a very worthwhile feature

**Comment by retorquere** [comment]
Zotero has this, but that still means a lot of moving parts have to be put in place. I have a prototype getting there but I'm really not happy with the UI. BBTs prefs are already a cluttered mess, and I can see happening that the next question is "can we have it for multiple formats".

Rethinking the UI/workflow again.

**Comment by ixil** [comment]
Let me know if I can do anything to help (testing etc)

**Comment by retorquere** [comment]
There's still several things that I don't know how to address, UI stuff aside. It looks like mendeley only exports bibtex, BBT exports 4 auto-exportable formats; collection paths in Zotero are not enforced to be unique, so file paths derived from them also are not necessarily unique, and BBT collection exports also exports collections that are contained within them, so if you have a/b/c/d with d containing a reference e, you'd get 4 files exported, all with the reference e. That doesn't seem desirable.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5862](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5862.xpi) ("recursive export")

Install in Zotero by downloading [test build 5.2.14.5862](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5862.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Sorry for the long wait. Give 5862 a go. You set up an auto-export as usual, then go into preferences and check "Export all child collections".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5869](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5869.xpi) ("make use of parallelization")

Install in Zotero by downloading [test build 5.2.14.5869](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5869.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by the-solipsist** [comment]
I'm not sure why, but I only see the "Export all child collections" option for Better BibLaTeX exports, but not for Better CSL JSON exports. Is this by design, or is there a glitch in my Zotero?

![Screenshot from 2020-11-11 01-57-57](https://user-images.githubusercontent.com/3080824/98729958-a216de00-23c1-11eb-951f-1e36818d81b6.png)
![Screenshot from 2020-11-11 01-58-10](https://user-images.githubusercontent.com/3080824/98729962-a4793800-23c1-11eb-938a-2af094537787.png)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.85.7374](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7374.xpi) ("Merge branch 'master' into gh-1074")

Install in Zotero by downloading [test build 5.2.85.7374](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7374.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by the-solipsist** [comment]
Wow, that was quick!  Thanks, @retorquere!  I tested the test build, and it works just as expected.
