### ISSUE TITLE
Automatic export not working on Group Libraries

### ISSUE THREAD

**Issue by mrjovanovic** [retorquere/zotero-better-bibtex#1075]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

I'm trying to use BetterBiBTeX with a Zotero Group Library. Unfortunately, the extension does not export any items in my shared/group libraries. In the add-on settings under Automatic export, it only shows "My Library"  I am happy to attach the .bib file. Are group libraries not supported for automatic export or am I doing something wrong? Thank you for your time.

**Comment by retorquere** [comment]
Group libraries are supported, but as Zotero does not support "export across all libraries", neither does BBT. You can right-click the group library and export it with "keep updated" and it will show in the auto-export list.

**Comment by mrjovanovic** [comment]
Oh, great. Thank you for the quick reply!

This is slightly inconvenient, as the Zotero QuickCite doesn't tell me in which library the respective item is, and in any case I will likely use references from multiple libraries. One solution might be to use `bibtool` or something to join all these libraries into one before rendering the references in any document with pandoc. 

Any alternative suggestions on workflow would be great, though. Thanks again.
