### ISSUE TITLE
Items need to be refreshed after citekey pattern change/it takes long for BBT to get the go-ahead to start up

### ISSUE THREAD

**Issue by skanskan** [retorquere/zotero-better-bibtex#1076]
The automatic CiteKey creation doesn'e seem to work well.
No matter the pattern you define (for example [auth][year]) you get a very long CiteKey that seems to be created with something like [auth][title][year] and it takes very long to create them.

I'm using Zotero Better Bib(La)Tex 5.1.2 with Zotero 5.0.57 on Windows 10 x64.

**Comment by retorquere** [comment]
The automatic citekey generation seems to work just fine for everyone else, and if it didn't work, almost 100% of my automated tests would fail, which I'd know almost instantly. The last checkbox you saw when opening the issue says "If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu" for this reason. I believe you when you say that it doesn't seem to work for you, but without a log, I can't tell what is going wrong. Please enable extended logging from the help menu, set the pattern to whatever you want, select a few references and right-click/refresh, then send a log. 

When you say it takes long to create them, is that at startup? First-time startup? Refresh? Item change that leads to key change?

**Comment by skanskan** [comment]
Here you can see a screenshot of what I mean.
![untitled-1](https://user-images.githubusercontent.com/4120283/47616359-09ec7b80-dabc-11e8-8c3f-b76a014689ee.jpg)

![untitled-2](https://user-images.githubusercontent.com/4120283/47616394-6059ba00-dabc-11e8-8c68-a7248aab92a8.jpg)

**Comment by retorquere** [comment]
I really must have a log, generated as I described above (and as was described in the initial issue template with the checkboxes you saw when you opened the issue. Without the log I cannot tell what is going wrong.

I also need to know the answers to the questions I posed earlier ("when you say...").

**Comment by retorquere** [comment]
BTW the screen shots don't help; both can be entirely normal situations. The first one could be right after a pattern change but before the refresh (no way to tell without a log) and the 2nd one could be zotero startup (no way to tell because there's no log and the place the popup would be which would indicate zotero is still starting is cut off). I really can't help you if you don't submit a log. The procedure is clearly described when you open a new issue, but for now, enable extended logging from the help menu, select at least one reference which does not have a citekey as you expect it, right click, refresh, then right-click the same reference, send debug log. Then post the log ID here.

**Comment by skanskan** [comment]
log ID
QLBY5M7V-euc

**Comment by retorquere** [comment]
Thank you. And the questions?

**Comment by retorquere** [comment]
I don't see any trace of a refresh attempt in the log; the reference in question is also not in the log. Please, allow me to help you. Do *exactly* this:

1. Make sure extended debugging is (still) on from the Help menu, and that BBT has finished initializing (no popup window in the lower right that says `Better BibTeX`)
2. Select 1 reference for which you think the citekey should be different. While it is selected, right-click that same reference, and select `Better BibTeX` - `Refresh BibTeX Key` from the menu that pops up.
3. Select *the same reference* again if it is not selected, right-click that same reference, and from the menu that pops up, select `Better BibTeX` - `Report Better BibTeX Errors...`
4. Post the debug ID you get here.

Additionally, I need to know: when you say "it takes long to create them", is that

* at startup?
* first-time startup after installing BBT?
* after refreshing the key manually as in point 2.?
* after a change to an item leads to the key changing?

You're leaving me blind here -- I cannot see into your system, so I need more information from you.

**Comment by retorquere** [comment]
![screenshot](https://user-images.githubusercontent.com/132108/47623727-0c2ef400-db15-11e8-9788-fcd3afccd7e3.png)

Most of that minute is spent in the status "Waiting for Zotero database". I am not allowed to touch (not even read) the Zotero database until Zotero tells me it is OK to access it; you will see that it flashes through a few stages and is then done. I cannot do anything about the long delay at the start -- if Zotero gives me the all-clear faster, BBT will start faster.

**Comment by retorquere** [comment]
Can you upgrade to 5.1.5 and send a new log? I can't do anything about the long startup times of Zotero, but if I gather enough evidence (and my idea that this affects many people), maybe I can negotiate with the Zotero devs. 5.1.5 specifically adds logging that captures how long the startup phases take. For me it takes ~ 6 seconds but I've seen it take a lot longer.

**Comment by skanskan** [comment]
Hello again.

I hope I did it properly.

I've tried just restarting and also generating the keys.

Better BibTex
VDK7E278-euc
AMGNRIKP-euc

Zotero
D1821317325

I'm not complaining about anything, just trying to help to improve Zotero.

Regards.

**Comment by retorquere** [comment]
VDK7E278 shows 5.2 seconds waiting for the Zotero go-ahead and then 0.71 seconds for BBT to start after that; AMGNRIKP shows 6.4 seconds waiting for the Zotero go-ahead and then 0.72 seconds for BBT to start after that (I can't read the `D<number>` logs, those go to Zotero). It should be possible to shave a little off the 5-6 seconds startup time, but it's not currently a major priority in Zotero, and there's nothing I can do about the startup time on my end except the 0.7 seconds. The keys are ready even if you see the question mark in those first 5-6 seconds, I just am not permitted to open the database yet (opening it before ready would lead to lots of nastiness). The database is in some shape ready dusing that time or you wouldn't see any reference data either, but I'm getting my go-ahead substantially later.

I see the refresh in the logs, those take 2-8 milliseconds a piece, that shouldn't be so onerous.

**Comment by skanskan** [comment]
OK thanks,
Anyway this was a small bibliography, around 200 entries but I just selected one third of them to refresh.

**Comment by retorquere** [comment]
According to VDK7E278, there were 56 keys refreshed which took a total of 0.36 seconds. There's not much I can do to speed that up, and there's literally nothing I can do about the 6 seconds delay at the start.

Is there any place else that you experience long times to generate keys?

**Comment by skanskan** [comment]
No, it's OK.
We can close this issue if you want.
Thanks.
