### ISSUE TITLE
strange citation key

### ISSUE THREAD

**Issue by mmccourt** [retorquere/zotero-better-bibtex#1077]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

BBT Error Report:TWXFXFAR-apse
I have just upgraded to Zotero 5.0.57 and BBT 5.1.2

The citation keys for several hundred references in my repository are generated normally followng the  standard format <author>:<year>, eg Chordia:2002

However for one reference, the citation key is different, it seems to have the format <author><first three words of abstract><year>, ie brownPrivateEquityFunds2016

I also see that this reference is not exported  (the others export OK).

I have tried deleting the reference and regenerating from the web (paper URL: https://www.nber.org/papers/w22493) using the Chrome plugin, but the problem perisists 

Any thoughts?

thanks,
Maurice

**Comment by retorquere** [comment]
Looking at the reference that was sent along with the debug log, the citekey looks just about right; you have the pattern set to `[auth:lower][shorttitle3_3][year]`, which would produce `brownPrivateEquityFunds2016`. How the others got to look like `Chordia:2002` I can only guess:

* you have them pinned in the `extra` field
* the pattern was previously something like `[author]:[year]` and the Brown reference was (one of) the first references you imported after the pattern changed to `[auth:lower][shorttitle3_3][year]`

would be the most likely explanations.

I also have no problem exporting the reference. After enabling extended logging (restart with logging enabled from the Help menu), please export this one reference, and then send a new log. I will see the export activity in the log. Sorry for the new log request but the default log only registers errors (no relevant errors in the log) for performance reasons.
