### ISSUE TITLE
Spaces lost when expanding string variables during import

### ISSUE THREAD

**Issue by pgoelz** [retorquere/zotero-better-bibtex#1081]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [X] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Consider the following bibliography:
```
@string{j = {a space between this }}
@article{key,
    author  = "Author",
    title   = "Title",
    year    = 1990,
    journal = j # "and this"
}
```

When the string var j is expanded by bibtex, the journal entry is `a space between this and this`. (For a minimum working example, see [test.txt](https://github.com/retorquere/zotero-better-bibtex/files/2569058/test.txt); please change file ending to `.tex`.)

The same bibliography imported into Zotero gives me `a space between thisand this` instead, without the space. Please correct me if this is zotero behavior, not better-bibtex behavior. Else, is there a way to keep the space? For a workaround, I would also be fine with just keeping the variables unexpanded, as long as they go verbatim into exported bibtex files and can be expanded subsequently.

Thanks a lot!

**Comment by retorquere** [comment]
This was a BBT problem, or to be specific, a problem in the [bibtex parser that BBT uses](https://github.com/fiduswriter/biblatex-csl-converter). I've fixed the problem in the parser, updated it in BBT, added the test case to prevent regression, and cut a new release. 5.1.7 should drop in a few minutes.

**Comment by retorquere** [comment]
It's not feasible to retain the variables as Zotero doesn't really have a place to store them and no facility to indicate that `j # "some text"` is part literal text and part variable.

**Comment by pgoelz** [comment]
Thank you very much :)
