### ISSUE TITLE
quick copy support for visual studio code

### ISSUE THREAD

**Issue by sbaeurle** [retorquere/zotero-better-bibtex#1085]
I've recently switched from TexMaker to Visual Studio Code as my primary latex editor.
With TexMaker I was able to quick copy the bibtex key from zotero directly into my editor.

In Visual Studio Code your simply not able to drag and drop the bibtex keys into you latex sourcefiles.

Is it possible to use drag and drop with Visual Studio Code? And if, how?

Many thanks in advance.

**Comment by retorquere** [comment]
You'd have to ask the Zotero developers or the VSCode developers; I don't actually do anything for drag and drop other than to make the citekey available to the existing Zotero drag and drop functionality -- AAMOF I don't even know for what purpose it's being requested, I can't see whether it's being used for drag and drop. Drag and drop doesn't work at all for VSCode even if you set the default format to a citation style like APA.

**Comment by retorquere** [comment]
It's not so much recognizing it as an editor, Zotero doesn't have a list of supported applications, it's more likely VSCode not registering itself as a drop target.
