### ISSUE TITLE
Pin citekey when using cayw

### ISSUE THREAD

**Issue by moseslux** [retorquere/zotero-better-bibtex#1090]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [n/a] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Hello,

I am new to BBT but grateful for all of the effort that has gone into developing it to date. I'm still getting used to the plug-in, but it seems suboptimal to me that I can cite a reference in a document for later processing using the [CAYW feature](https://retorque.re/zotero-better-bibtex/cayw/) whose citekey could change in the future—say if there was a typo in one of the fields used to generate the citekey. Is it (or would it be possible) for the citekey for that reference to then be automatically pinned upon being invoked by the CAYW picker? Or is there another method for automatically pinning citekeys? I am working on a long and longterm project, and I don't want to risk having citekeys changing after I've included them in draft documents.

Thanks for any help or suggestions.

**Comment by retorquere** [comment]
Not specifically for CAYW, but you can enable [autoPin](https://retorque.re/zotero-better-bibtex/configuration/#autopin).

**Comment by retorquere** [comment]
Does this solve it for you?

**Comment by moseslux** [comment]
Yes, I think so. Thanks for the quick reply.
