### ISSUE TITLE
error on exporting note with "pre" tags / duplicate field "howpublished"

### ISSUE THREAD

**Issue by stfl** [retorquere/zotero-better-bibtex#1092]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

error report reference: 5X7R8XDH-euc

I am trying to export my library as **Better BibTeX** (which used to work fine in the past) and now I am getting an error point to javascript common.js.

**Comment by stfl** [comment]
This issue comes up with that library on a Windows as well as a Linux installation.

**Comment by stfl** [comment]
It only happens when exporting the URL in an note field. When exporting to a url field, it works.

**Comment by stfl** [comment]
The entry that caused the issue was set as **Computer Program** which if I remember correctly was generated with Zotero Connector from a Github page like one year ago. Maybe I also changed it manually afterwards but I can't remember..

I changed it to type *Web Site* and it works.

error in Terminal:

Possibly unhandled rejection:

duplicate field 'howpublished' for UsrsctpPortableSCTP2017

add@Better BibTeX:11872:23
["./Better BibTeX.ts"]/Translator.doExport@Better BibTeX:10381:17
doExport@Better BibTeX:132:5

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.12.3052](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.12.3052.xpi) ("actually fixes #1092")

Install in Zotero by downloading [test build 5.1.12.3052](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.12.3052.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 3052?

**Comment by stfl** [comment]
It looks like I can't reproduce the issue even with the previous version. I've already deleted/changed the misbehaving entries.

**Comment by stfl** [comment]
Ok. I reproduced it, updated to 3052 and the issue persists: new error report

B94J8QBZ-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.12.3055](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.12.3055.xpi) ("actually fixes #1092")

Install in Zotero by downloading [test build 5.1.12.3055](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.12.3055.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
You actually found a second problem; the first problem was reproducible with `5X7R8XDH-euc`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.12.3056](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.12.3056.xpi) ("fixes 2nd report in #1092")

Install in Zotero by downloading [test build 5.1.12.3056](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.12.3056.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Alright, try 3056.

**Comment by retorquere** [comment]
Only I can close issues; I like to keep them open until I've made sure the fix makes it into a release.

**Comment by retorquere** [comment]
Thanks for the confirmation, I'll cut a new release to include this fix. You will be upgraded automatically from the version you have now.
