### ISSUE TITLE
Question: key `extensions.zotero.translators.better-bibtex.ZotFile`

### ISSUE THREAD

**Issue by jpcirrus** [retorquere/zotero-better-bibtex#1094]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

The value of this key is `false` with the status `user set`. However, I *am* using ZotFile and never changed this setting in Config Editor. BBT (and ZotFile) appear to be working correctly. Would this be a legacy key from version 4, and if so can it be deleted?

**Comment by retorquere** [comment]
It is indeed a legacy key and can safely be deleted. I've added code that will remove the key automatically in the next release.

**Comment by jpcirrus** [comment]
Many thanks (again) for the fast response.

**Comment by retorquere** [comment]
Thanks for reporting it

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.13.3067](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.13.3067.xpi) ("fixes #1094")

Install in Zotero by downloading [test build 5.1.13.3067](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.13.3067.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.13.3068](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.13.3068.xpi) ("fixes #1094")

Install in Zotero by downloading [test build 5.1.13.3068](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.13.3068.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
