### ISSUE TITLE
Replace " : " with a script

### ISSUE THREAD

**Issue by demai** [retorquere/zotero-better-bibtex#1100]
As Zotero only knows a single title field (no subtitle) it is impossible to change the title-subtitle-separator on a csl style level. I was thinking that Zotero-BBT's scripting support could be a potential solution for this problem.

I am trying to modify the output with a small script that splits the title at " : " and creates a new title with a custom separator.

This here works with BibTeX output:

```
if (Translator.BetterBibTeX && this.has.title) {
  var split_title = item.title.split(' : ');
  var new_title = split_title.join('. ');
  this.add({ name: 'title', value: new_title, replace: true });
}
```

But I can't figure out how I can achieve the same thing with CSL JSON output. This here won't work:

```
if (Translator.BetterCSL) {
  var split_title = item.title.split(' : ');
  var new_title = split_title.join('. ');
  reference.add({ name: 'title', value: new_title, replace: true });
}
```

(Also, I don't know how I could check if a title exists in the first place.)

**Comment by retorquere** [comment]
CSL objects are simpler, and you can just manipulate them as standard JS objects; you can see what they look like by exporting to "Better CSL JSON". The following  should work:

```
if (Translator.BetterCSL && item.title) {
  reference.title = reference.title.replace(/ : /g, ', ')
}
```

For Tex you can simplify to 

```
if (Translator.BetterBibTeX && item.title) {
  this.add({ name: 'title', value: item.title.replace(/ : /g, ', ') });
}
```

(replace: true isn't necessary anymore in postscripts, it's assumed now)

**Comment by demai** [comment]
Great. That works. Thanks for your help.
