### ISSUE TITLE
Could postscript scripts be used on demand

### ISSUE THREAD

**Issue by denismaier** [retorquere/zotero-better-bibtex#1101]
As mentioned in issue #1100 I am looking for a solution the overcomes Zotero's limitation to a single title field. The code in your answer works but this poses another problem: We need to change the code before every export if we need another separator. So: Would it be possible the select the used postscript code just before the export.

**Comment by retorquere** [comment]
Nope, not possible, sorry, there's no UI hook where I could prompt for it (and it also wouldn't work for auto-exports, which have no UI at all). It would in principle be possible to add information to the `extra` field to steer the postscript.

**Comment by retorquere** [comment]
It is possible to add any [CSL variable](https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables) to the `extra` field though for fields not supported in the UI.

**Comment by demai** [comment]
Ok. UI is not necessary. But how would a workflow with the `extra` field look like?

**Comment by retorquere** [comment]
For adding new vars you mean? You can just say

```
collection-title: Some title
```

**Comment by retorquere** [comment]
(or whatever CSL variable you want. What's in the `extra` field overrides whatever is in the other fields)

**Comment by demai** [comment]
Yes, I know that and how I can add variables to the extra field. But can I use this to steer the postscript?

**Comment by retorquere** [comment]
You  can read the `extra` field and react to its content. As an example, you could do something like

```
if (Translator.BetterTeX) {
  var flag = (item.extra || '').match(/someFlag: ([a-z]+)/i);
  switch (flag ? flag[1] : '') {
    case 'X': ..... break;
    case 'somethingelse': ..... break;
  } 
}
```

**Comment by demai** [comment]
Ok, but this leads to new problems since this would not be a general setting. 

I guess the best options at the moment are:

1. Changing the code in the postscript box manually, or
2. exporting to JSON without changing the output. In this case one could use sed to preprocess the file before processing everything with pandoc. (Another option could be using a lua-filter with pandoc, but I have not been successfull with this approach.)

**Comment by retorquere** [comment]
General in what sense? You mean you want something that adapts per-export?

**Comment by demai** [comment]
That's it. 

The use case looks like that: English citation styles always use a colon between title and subtitle. German citation styles mostly use a period. So: I want to use " : " as title-subtitle-separator in the database. For some documents I might want this to become ". ", in other documents that should render as ": ". So I was hoping for a way to specify the replacement text per-export.

**Comment by retorquere** [comment]
It'd be fairly easy to make the target path available to the postscript so tot could switch on that. It'd also be possible to load the script from disk I guess, but that'd be much more involved.

**Comment by retorquere** [comment]
But what you describe is already possible. You can get the reference language, and you could override that with the flag trick above.

**Comment by demai** [comment]
Well, using the reference language would be a per item setting, right? This is not what I need. It won't matter if a specific reference is in English or in German. The relevant question is if the document, if the citation style requests colons or periods between titles and subtitles.

**Comment by retorquere** [comment]
Well, as I said, making the export target available to the postscript wouldn't be hard. Would that help?

**Comment by retorquere** [comment]
The export target turns out to already be available, I'd just forgotten about it; in the postscript you can look at `Translator.options.exportPath`, which will be the directory the file is being exported to.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.28.3162](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.28.3162.xpi) ("keep overrides")

Install in Zotero by downloading [test build 5.1.28.3162](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.28.3162.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Note that using that trick disables caching, so exports will be substantially slower.

**Comment by retorquere** [comment]
3162 has another feature; it's experimental and I'm not sure I'm going to keep it yet, but here's how you'd use it:

1. Edit the [hidden preference](https://retorque.re/zotero-better-bibtex/configuration/#hidden-preferences) `postscriptOverride`, and set it to a filename like `postscript.js`
2. In the directory where you intend to export to, create a file called `postscript.js` (or whatever you set the preference to) and add the postscript you want there
3. Export to that directory.

This postscript will replace the postscript that can be set in the BBT preferences. Using this route will likewise disable caching for exports where an `postscript.js` is found.

The test for `Translator.options.exportPath` is just part of BBT so that's available and will stay.

**Comment by demai** [comment]
Wow, that's great. I still need to test this, but this looks like this is what I need. So you can have one standard postscript, and in case you need different separators, you could just use this override feature. Great, thanks a lot!

**Comment by retorquere** [comment]
But do note those custom postscript will have the entire export run slower because it won't use the cache.

**Comment by retorquere** [comment]
so... thoughts?

**Comment by demai** [comment]
Sorry for answering so late. I just wanted to try this override feature, but I could not find `postscriptOverride` in the configuration editor. I have Zotero BBT 5.1.37 installed. What am I doing wrong?

**Comment by retorquere** [comment]
It doesn't exist on 5.1.37, just on build 3162 from above for now; I need to know it works as intended before rolling it into a release for everyone. If you can confirm it works as you want it, then I can add it to the normal release, and the preference will show up in the config editor there too.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.37.3326](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.37.3326.xpi) ("docs")

Install in Zotero by downloading [test build 5.1.37.3326](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.37.3326.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by demai** [comment]
Ok, I have now installed the latest test build (3326). I can now find `postscriptOverride` in the configuration editor, but the settings I make there does not seem to have an effect. (The usual postscript code will be applied no matter what...)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.39.3333](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.39.3333.xpi) ("fixes #1101")

Install in Zotero by downloading [test build 5.1.39.3333](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.39.3333.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I'm still thinking about whether to do this, or to add a postscript field to the autoexports. That would make it available to auto-export only, not single exports. What do you think?

**Comment by demai** [comment]
Hmm, I don't really mind. Adding a postscript field to the autoexports sounds like a reasonable approach to me. At least this will keep my project folder a bit cleaner (one file less...).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5863](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5863.xpi) ("postscript override")

Install in Zotero by downloading [test build 5.2.14.5863](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5863.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5864](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5864.xpi) ("postscript override")

Install in Zotero by downloading [test build 5.2.14.5864](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5864.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
