### ISSUE TITLE
Is Better BibTeX or BibLaTeX export Related references?

### ISSUE THREAD

**Issue by Lycurgue** [retorquere/zotero-better-bibtex#1102]
Hi,

Is Better BibTeX or BibLaTeX export Related references?
I'm using Better BibTeX and I searched the Zotero Related references within the exported .bib file but to no avail.

Thanks,

- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

**Comment by retorquere** [comment]
It doesn't currently. How would you propose the relations being exported?

**Comment by Lycurgue** [comment]
Hi retorquere,

Thanks for the reply.
Sorry, but I'm not sure what to propose to export Zotero Related refences in bibtex format. I'm essentialy an end-user, so I'm not familiar with the details of both Zotero and bibtex formats.

From the Jabref web site (https://help.jabref.org/en/EntryLinks) it seems that there is a field called 'related' for the bibtext format. We can read :

> comma separated list of BibTeX keys which are in some kind related to this entry. The type of all relations can be specified by a single relatedtype (see https://github.com/plk/biblatex/issues/475#issuecomment-246931180). Note: Biblatex prints this information if related is active at the biblatex package.

Maybe it can be a solution,
Thanks

**Comment by retorquere** [comment]
That seems reasonable, but what do you want to use it for?

**Comment by Lycurgue** [comment]
I'd like to do the same thing as in Zotero: to connect different items, e.g. book chapters.
From this Zotero page (https://www.zotero.org/support/related), we find a list of possibles usages.
Thanks

**Comment by retorquere** [comment]
Right, but for what purpose would this be used? It wouldn't show up in a bibliography I think, are there other tools that read this? This feature has ramifications for caching so I'm looking at whether it's worth the effort.

**Comment by Lycurgue** [comment]
As I said, I'm essentially an end-user, so I'm not familiar with the details of both Zotero and bibtex formats. Maybe it is not worth the effort. Thanks anyway.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.30.3173](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.30.3173.xpi) ("update typings for #1102")

Install in Zotero by downloading [test build 5.1.30.3173](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.30.3173.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I'm always happy to do these things, but development is driven mostly by user need -- if you have a BibTeX need, I can see how best to go about implementing it. But if the need isn't really there, it's hard to assess what a good result would be.

3173 will add a `related` field with the keys of the related items in Zotero; you can add the `relationtype` by adding `bibtex[relationtype=multivolume]` to the extra field, but given that the relations are not typed in Zotero, this seems pretty fragile. I'm not sure I'm going to bring this into a formal release until I know how it's going to be used.
