### ISSUE TITLE
Database schema upgrade happens too late; initialization fails.

### ISSUE THREAD

**Issue by lrnv** [retorquere/zotero-better-bibtex#1103]
Hi, 

This issue is following what i started talking about in #920 , after we understood that it's a different problem.

The issue is that BBT stands with the popup "Initializing : Instalation of converters" and wont start properly. 
I cant export collection with BBT, only standard zotero export modes are avaliable, and the popup wont leave my screen. 

After restarting with log enabled, i got the following log : [log.txt](https://github.com/retorquere/zotero-better-bibtex/files/2660012/log.txt)

Hope this wont be too hard to fix,

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.29.3168](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.29.3168.xpi) ("always probe DB for schema upgrades")

Install in Zotero by downloading [test build 5.1.29.3168](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.29.3168.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 3168

**Comment by retorquere** [comment]
Auto update still works, and I'm going to release this exact version you have as the new release.

**Comment by retorquere** [comment]
Released as 5.1.30
