### ISSUE TITLE
Better BibTex initializing: installing bundled translators

### ISSUE THREAD

**Issue by abdesss** [retorquere/zotero-better-bibtex#1104]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

ID SKVME4H8-euc

Hello,

Better BibTex freezes at installing bundled translators and citing added references in this state results in questions marks.

**Comment by retorquere** [comment]
This looks to be a duplicate from #1103 (which you could not have known) -- can you try upgrading to 5.1.30 to see if that fixes it for you?

**Comment by abdesss** [comment]
Perfect ! it did fix it.
Thank you.

**Comment by retorquere** [comment]
Apologies for the disruption, great that it works for you.

**Comment by abdesss** [comment]
Yep, i tried every solution and when i installed 5.1.29 i though i had the latest version lol.
Thank you very much for this tool, it helped me a lot and still does while writing my ph.d.
I hope the best for you.

**Comment by retorquere** [comment]
You did have the latest version, 5.1.30 is just an hour or so old.

Good luck on the PhD -- it's hard work.
