### ISSUE TITLE
[Feature Request] Floating picker for use in full-screen apps

### ISSUE THREAD

**Issue by ymshulman** [retorquere/zotero-better-bibtex#1106]
Hi!

Thank you for your tremendous work on this - it's been _incredibly_ useful to invoke this citation picker for use in Scrivener. 
Would it be a simple change to allow the picker to float over full-screen apps? As it currently stands, invoking the picker from full-screen Scrivener kicks me out of the app to another desktop (Mac), and it would be helpful if it floated even in full-screen instead.

**Comment by retorquere** [comment]
It's not something I can fix - all BBT does is trigger the Zotero picker and capture the results, the UI of this is part of Zotero, not BBT.

**Comment by ymshulman** [comment]
Got it - thank you for the clarification!
