### ISSUE TITLE
Latin small letter e with acute not escaped

### ISSUE THREAD

**Issue by ultimatecheese** [retorquere/zotero-better-bibtex#1113]
Report ID: KMQMSGHH-euc

When I make a new reference, with author name "Namé", BBT outputs as "Nam\'e", since I have "export unicode as plain-text" ticked. However, with previous references that I have made, this outputting does not change "é" to "\'e".

(I have made sure that the "export as plaintext" is ticked for the export.)

**Comment by retorquere** [comment]
In that report I only see "David Aldous" and "James Allen Fill".

**Comment by ultimatecheese** [comment]
Sorry, I must have done than without the "Namé" in there (I tried removing and readding previously). I've resubmitted as HAE72E2A-euc

**Comment by retorquere** [comment]
Was this resolves with the per-auto-export config as on the Zotero forums?

**Comment by ultimatecheese** [comment]
No, neither were resolved. Even when I did an individual output of the Aldous-Fill one with "A Namé" appended and an individual "A Namé", the two output were

- Aldous, Fill, Namé
- Nam\'e

which is quite strange!

**Comment by retorquere** [comment]
The item in HAE72E2A is marked with `#LaTeX` in which case BBT  will do no transformations at all.

**Comment by ultimatecheese** [comment]
Ah, that's a good point! I think that was maybe why I was using #LaTeX, because I wanted to manually enter the accents on names, to make sure they are right.

My apologies for wasting your time. I really appreciate BBT! I advertise it to my friends often!

**Comment by retorquere** [comment]
No problem. What about the 2nd one? `Nam'e`?

**Comment by ultimatecheese** [comment]
The new one that I typed "Namé" into Zotero (but no #LaTeX) exported "Nam\'e", as desired.

I would like to keep the #LaTeX -- it gives me confidence that exactly what I type will be outputted -- so I think I'll just stick to, on the occasion that it's needed, manually typing in the names with \' etc.

**Comment by retorquere** [comment]
That's perfectly fine.
