### ISSUE TITLE
Wrong \r import

### ISSUE THREAD

**Issue by adam3smith** [retorquere/zotero-better-bibtex#1115]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification
Import 

Via 
https://forums.zotero.org/discussion/75309/bibtex-import-bug#latest

```
@inproceedings{rehurek_lrec,
title = {{Software Framework for Topic Modelling with Large Corpora}},
author = {Radim {\v R}eh{\r u}{\v r}ek and Petr Sojka},
booktitle = {{Proceedings of the LREC 2010 Workshop on New
Challenges for NLP Frameworks}},
pages = {45--50},
year = 2010,
month = May,
day = 22,
publisher = {ELRA},
address = {Valletta, Malta},
url={http://is.muni.cz/publication/884893/en},
language={English}
}
```
The author name is incorrectly imported as "Řeh˚uřek", while the correct name is "Řehůřek". See https://radimrehurek.com/gensim/about.html

I can replicate this with BBT, but not with Zotero's stock BibTeX

**Comment by retorquere** [comment]
Thanks for the report!
