### ISSUE TITLE
Handling author- and editor-less citations

### ISSUE THREAD

**Issue by rpgoldman** [retorquere/zotero-better-bibtex#1116]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

## Exporting references

I am exporting a "Computer Program" type record that is commercial software produced by a company.  So I have no idea who the author is.  When I export my record and run BibTeX (not BibLaTeX), I get this warning:
```
Warning--to sort, need author or key in QChem
```
I sent report id: 2ZTYUYTB-euc
but probably more useful is a look at the record:
<img width="339" alt="qchem-record" src="https://user-images.githubusercontent.com/3274/50803795-d6df1900-12b0-11e9-87fe-43ea5b09d5a3.png">

In manual Bibtex usage, I'd just add a "key" field, but I don't believe that's possible with Zotero.

I fear that this might be an FAQ, but it's essentially impossible to google for an answer to this question -- anything with Zotero, export, Better Bibtex, and "key" just gives me information about the _Zotero_ citation key field, and not the _BibTeX_ key field!  So I apologize in advance.

**Comment by retorquere** [comment]
No worries. This can be done in two ways depending on how exactly you want to achieve it:

**Manually set the key per-item**

can be done by [adding the key in the `extra` field](https://retorque.re/zotero-better-bibtex/customized-exports/#add-your-own-biblatex-fields) with something like `bibtex[key=Q-Chem]`.

**Automatically set the key when there are no creators**

can be done using a [postscript](https://retorque.re/zotero-better-bibtex/scripting/) like

```
// if:
//  * this is a Better BibTeX or BetterBibLaTeX export, and
//  * the current item has no creators, and
//  * the current item is a computer program
if (Translator.BetterTeX && (!item.creators || item.creators.length === 0) && item.itemType === 'computerProgram') {
  this.add({ name: 'key', value: item.publisher }) // publisher is the company name in the Zotero interface
}
```

**Comment by retorquere** [comment]
You can see all the available fields by exporting an item using the "BetterBibTeX JSON" exporter.

**Comment by retorquere** [comment]
Does this address your question sufficiently?

**Comment by rpgoldman** [comment]
Yes, thank you so much!  I am sorry I didn't respond sooner -- this issue arose when I was in the middle of an *enormous* writing project that I am just finishing now.

**Comment by retorquere** [comment]
Cool, no worries
