### ISSUE TITLE
Error exporting with custom Extra field (8LY2P8FC-apse)

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#1118]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Description

I have a repeatable error, regardless of export format (JSON or BibLaTeX) with my definition of HALOT. This reference hasn't changed for months, but since a release or two ago Zotero hangs if Better BibLaTeX exports that reference. The custom Extra field is:

```
bibtex: HALOT
biblatex{
  editortype: "translated and edited under the supervision of",
  referencetype: mvlexicon
}
```

From experimentation, the first line (to pin the citekey) is OK, but the biblatex block causes trouble. If I omit that block, the BibLaTeX file ends up including this reference:

```
@mvbook{HALOT,
  location = {{Leiden}},
  title = {The {{Hebrew}} and {{Aramaic}} Lexicon of the {{Old Testament}}},
  shorttitle = {{{HALOT}}},
  volumes = {5},
  publisher = {{Brill}},
  date = {2000},
  keywords = {bib:custom},
  author = {Koehler, Ludwig and Baumgartner, Walter and Stamm, Johann Jakob},
  translator = {Richardson, M. E. J.}
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.39.3335](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.39.3335.xpi) ("fixes #1118")

Install in Zotero by downloading [test build 5.1.39.3335](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.39.3335.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 3335?

**Comment by lyndondrake** [comment]
That seems to fix it

**Comment by retorquere** [comment]
But it didn't import the fields, right? It left the fields in the extra field on export? Adding quotes around mvlexicon should fix that.

**Comment by lyndondrake** [comment]
Ha, I hadn't noticed that. But you're right - it hadn't changed the type, and adding the quotes fixed that up so the type changes.

**Comment by retorquere** [comment]
I'm surprised though that the reference with that particular biblatex block used to export a few months ago though. There was a legitimate bug in dealing with malformed biblatex blocks (so thanks for reporting that) but that bug has been there for a very long time.

**Comment by lyndondrake** [comment]
What changed is that Zotero hung. It was doing an export (& autoexport on idle) with no problems for ages, and that ref is a really old one that I haven't touched for many months. So maybe it was going wrong in some other way, but not by hanging?

**Comment by retorquere** [comment]
> Ha, I hadn't noticed that. But you're right - it hadn't changed the type, and adding the quotes fixed that up so the type changes.

Yeah sorry about not mentioning that earlier but I really wanted to know whether the bug behavior wasn't only fixed on my end. The bug was that it would keep trying to parse that block forever instead of ignoring it after finding it invalid.

**Comment by lyndondrake** [comment]
No worries, all part of fixing things up

**Comment by retorquere** [comment]
Odd. Maybe Zotero's behavior for hanging translators has changed. In any case, I'm happy to have been able to fix it, I'll cut a new release when I'm at my laptop. You can keep 3335, the new release will be the same but just with a formal release number. Zotero will automatically upgrade in a day or so, or you can force a check update from the addons screen.
