### ISSUE TITLE
Missing required field when field omitted

### ISSUE THREAD

**Issue by Hyphenated-Name** [retorquere/zotero-better-bibtex#1119]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Hi,
Thanks so much for the excellent tool! 

I've found what I think is a minor bug: when I have a field listed in the "fields to omit from export" setting that Better Bibtex considers to be a required field and have "include comments about potential problems" checked, Better Bibtex includes a comment saying that the field is missing. In particular, I have the "pages' field omitted, and my bibtex entries are all followed by "% Missing required field 'pages'". This happens even though my actual Zotero entries do in fact have pages listed---I just don't want them included in my bibtex.

I guess the solution should be to never count omitted fields as "required."

Report ID: 9HZ9XA4R-euc

**Comment by retorquere** [comment]
It's not a bug as such; the quality report looks at the biblatex manual and the known documentation on bibtex (such as it is) and reports which fields are missing for a type, which means styles that may legitimately depend on these fields could behave strangely. The quality report doesn't report on the quality of the source reference directly, only on the generated bib(la)tex; even if the pages *were* missing in Zotero but you'd (hypothetically) insert them e.g. with a postscript, the QR message would go away.

**Comment by retorquere** [comment]
does this address your question?

**Comment by Hyphenated-Name** [comment]
Yes, thanks. Obviously I disagree about how this should function, but I appreciate that you've considered it.
