### ISSUE TITLE
Feature request: Do not export URL with arxiv

### ISSUE THREAD

**Issue by diravan** [retorquere/zotero-better-bibtex#1121]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Feature

Right now it is possible to set BBT to export DOI/URL/both. Could it be possible to have the same feature for ArXiv? In particular I would like to be able to NOT export the URL when the extra is setted to ArXiv:#. 

If there is a easier way to do it without adding such a feature I would be happy to hear it.

Thanks a lot this amazing piece of software.

**Comment by retorquere** [comment]
A postscript should be able to do this:

```
if (Translator.BetterBibTeX && this.has.url && item.arXiv) {
  delete this.has.url
}
```

Is this a common thing to do? I added the DOI/URL/both option because it was common enough to find references on the web that stored the DOI both in the DOI and the URL field that the added clutter was an annoyance.

**Comment by retorquere** [comment]
I really need to know more about this use-case before I can do anything.

**Comment by diravan** [comment]
Sorry for my late reply. Basically my use case is the following. A good chunk of my literature is composed of ArXiv entries and I wound like those to not display the URL but sometimes I need to cite some website so I would like to have those to have the URL. 

I think that a postscript should work. Once I figured out how to make it do what I want I will add it below so if someone else has my same workflow can use it.

Thanks a lot for your help

**Comment by retorquere** [comment]
My pleasure. I think the postscript above will do what you want.

**Comment by diravan** [comment]
Yes it does. Sorry I made a small change and then it was no longer working. Thanks a lot

**Comment by retorquere** [comment]
You're welcome.
