### ISSUE TITLE
Book series field exported in Sentence case

### ISSUE THREAD

**Issue by madsmh** [retorquere/zotero-better-bibtex#1122]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

## Exporting references
When exporting with Better Biblatex the book series field is exported in
Sentence case as opposed to Title Case.

I am using the latest BBT and Zotero v. 5.0.59.

An example:
@book{leeIntroductionSmoothManifolds2013,
  location = {{New York ; London}},
  title = {Introduction to Smooth Manifolds},
  edition = {2nd ed},
  isbn = {978-1-4419-9981-8},
  pagetotal = {708},
  number = {218},
  series = {Graduate texts in mathematics},
  publisher = {{Springer}},
  date = {2013},
  keywords = {Manifolds (Mathematics)},
  author = {Lee, John M.},
  }

**Comment by retorquere** [comment]
Can you right-click that reference and select "Send BBT Error Report"?

**Comment by madsmh** [comment]
Works, thanks!

**Comment by retorquere** [comment]
Cool. I'll fold it into a release when I get home tonight (but it'll just be what you have now with a formal release number slapped on it). You'll be upgraded to that automatically in a day or so when zotero checks for plugin upgrades.
