### ISSUE TITLE
renaming to %b no longer works in ZotFile

### ISSUE THREAD

**Issue by annargrs** [retorquere/zotero-better-bibtex#1123]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

## Non-export problems with BBT

Report ID: Y7TMP83T-euc

I am not sure if this is a problem caused by some recent change in BBT or ZotFile; I've posted my issue in ZotFile repo first but got no response so far. Reporting it here as well in case it is BBT.

Expected behavior: ZotFile renaming linked pdf attachments to %b renames them to BBT citation keys.

Actual behavior: ZotFile renames them to just "pdf" if there is no such file in the attachments directory. If there is, nothing happens. Renaming to any other ZotFile pattern works. BBT log suggests that KeyManager.get is called for a non-existing entry (I also tried this with newly imported items).

**Comment by retorquere** [comment]
I've commented on https://github.com/jlegewie/zotfile/issues/386 but I think this would be best addressed in ZotFile.

**Comment by retorquere** [comment]
The `KeyManager.get is called for a non-existing entry` is probably access during startup, when Zotero starts displaying things where I'm not yet allowed to access the database.

**Comment by annargrs** [comment]
Thanks! Hopefully @jlegewie responds soon.
