### ISSUE TITLE
Exporting TEI with BBT keys

### ISSUE THREAD

**Issue by adunning** [retorquere/zotero-better-bibtex#1124]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [X] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Do you happen to know of a way to run a Zotero TEI export (i.e. using the translator at <https://github.com/zotero/translators/blob/master/TEI.js>), injecting BBT's citation keys in the xml:id field instead of using the translator's `genXMLId` function?

I realize that this is incredibly niche, so please don't waste any time on it if there isn't some obvious solution; I can always just rewrite the translator myself to imitate the BBT citation keys.

**Comment by retorquere** [comment]
It's not possible to do on the fly, but if you change 

```
var xmlid = genXMLId(item);
```

into

```
var xmlid = item.citekey;
```

in the TEI translator, it will do what you want, assuming BBT is active. The `.citekey` field is added at runtime to exported items by BBT.

Not that genXMLId assures IDs are unique (which XML demands they be). With BBT, keys generally are unique, but if you pin two items to the same key, BBT doesn't second-guess you.

**Comment by retorquere** [comment]
(if you want to be on the safe side, `var xmlid = item.citekey || genXMLId(item);` will do the job even when BBT is deactivated)

**Comment by adunning** [comment]
Hadn't realized it was available that way. Thank you very much indeed!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.43.3375](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.43.3375.xpi) ("test citationKey")

Install in Zotero by downloading [test build 5.1.43.3375](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.43.3375.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you give 3375 a go but with `var xmlid = item.citationKey || genXMLId(item);`?

**Comment by adunning** [comment]
Yes, that still works!

**Comment by retorquere** [comment]
Cool -- 5.1.44 has the change.
