### ISSUE TITLE
Error exporting duplicate eprinttype

### ISSUE THREAD

**Issue by dangom** [retorquere/zotero-better-bibtex#1128]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

Just migrated from Mendeley to Zotero. Tried exporting a collection with better biblatex but I keep getting a transaction error. I notice the file is generated, but some references seem to be missing.

## Exporting references

Exporting to BibLaTeX.
GDA52Z94-euc

**Comment by retorquere** [comment]
Thanks for reporting this. I've found the source of the error, but I'm not sure what to do yet -- your reference `Integrated strategy for improving functional connectivity mapping using multiecho fMRI.` has both an arXiv identifier and an pubmed ID, and I can't export both in biblatex. I suppose pubmed takes precedence over arXiv?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3433](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3433.xpi) ("test case for #1128")

Install in Zotero by downloading [test build 5.1.46.3433](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3433.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 3433 a go.

**Comment by retorquere** [comment]
Thanks for the confirmation. 5.1.47 will be out in a few minutes that includes this fix, but it's just a rebranded 3433. You will be upgraded by Zotero automatically to 5.1.47, or you can force it from the addons menu.
