### ISSUE TITLE
pathSearch fails on Windows with embedded variables

### ISSUE THREAD

**Issue by Felix-Soldner** [retorquere/zotero-better-bibtex#1129]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification
I updated my Zotero and followed the installation guide for BBT (https://retorque.re/zotero-better-bibtex/installation/)
After installing it from the downloaded file I can't use any of the BBT functions. 
- No CiteKeys are being generated. It is being displayed, but the cell is empty.
- The settings tap "Better BibTeX" under edit -> preferences, is being displayed, but no settings are shown. It is just a blank window.
- When I want to export a library (".bib" file) with BBT it is not listed as an option. However, it does prompt me with "are you sure you don't want the 'Better BibTeX' format?", when using other formats.
- It does list the option "report Better BibTeX Errors..." under Help

The error report ID: X6IULK3S-euc

I tried reinstalling it, but that did not help.
Anyone has any idea how to approach that? Many thanks!

best,
Felix

**Comment by Felix-Soldner** [comment]
blip-bloop, your solution works. Thank you!

**Comment by retorquere** [comment]
blip-bloop can't answer, "he" is just the build bot :smile:

**Comment by retorquere** [comment]
Oh and label-gun is a bot which will prevent issues being closed until I've merged them into a release.

**Comment by retorquere** [comment]
5.1.50 contains the fix. You will be upgraded automatically, but it's just a rebranded 3437
