### ISSUE TITLE
feature request: use bib file in aux import

### ISSUE THREAD

**Issue by Evpok** [retorquere/zotero-better-bibtex#1132]
It would be nice to be able to specify a bib file from which the aux import could fetch the missing keys.

- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

**Comment by retorquere** [comment]
The aux file has a pointer to the bib sources used, why not just use that?

**Comment by Evpok** [comment]
In my specific case, because the bib file has a lot of unused refs in it. Granted, I could probably filter them out.

**Comment by retorquere** [comment]
But the aux scanner wouldn't pick up the unused refs. It'd see which citekeys are not in Zotero and import only those from the bib file.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.53.3481](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.53.3481.xpi) ("prelim support for aux-scan pickup")

Install in Zotero by downloading [test build 5.1.53.3481](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.53.3481.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by Evpok** [comment]
Oh yeah, right, I misunderstood you answer. In that case, sure, let's use the linked bib file !

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.53.3483](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.53.3483.xpi) ("pick up missing references in aux scan")

Install in Zotero by downloading [test build 5.1.53.3483](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.53.3483.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
It's disabled by default, but 3483 should do it if you go into the preferences and enable the "AUX scan" checkbox. Give it a try.

**Comment by retorquere** [comment]
Still interested?

**Comment by Evpok** [comment]
Yes, sorry I just haven't have the time to test it yet. I have to build from master for that, right ?

**Comment by Evpok** [comment]
Oh, no, right, just saw the bot feedback, I'll keep you posted

**Comment by Evpok** [comment]
It seems to work quite well, thanks !

**Comment by retorquere** [comment]
Cool, thanks, 5.1.54 is building to include this.
