### ISSUE TITLE
Citekey won't update after deleting entries

### ISSUE THREAD

**Issue by alapo** [retorquere/zotero-better-bibtex#1134]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

## Exporting references

Report ID: MVAEFTHR-euc
I am exporting with BibTex to a `.bib` file. 

I was having issues with 2 particular references not exporting the authors correctly, so I deleted the references from Zotero and attempted to re-import them. The issue I ran into is that now the Citekeys are starting with the letter "d"  in the `bib` file yet the citekey in Zotero is not. In this example `shultz2011` is the citekey in Zotero but in the exported bib file the citekey is `shultz2011d`. I have re-exported the bibliography and made sure I did export the BibTex file. Below is the syntax for this reference in the bib file.

An example is shown below where the citekey produced is `shultz2011d` rather than `shultz2011`

```
@article{shultz2011d,
  title = {A Single Mild Fluid Percussion Injury Induces Short-Term Behavioral and Neuropathological Changes in the {{Long}}-{{Evans}} Rat: Support for an Animal Model of Concussion},
  volume = {224},
  issn = {1872-7549},
  shorttitle = {A Single Mild Fluid Percussion Injury Induces Short-Term Behavioral and Neuropathological Changes in the {{Long}}-{{Evans}} Rat},
  doi = {10.1016/j.bbr.2011.06.012},
  abstract = {Brain concussion is a serious public health concern and is associated with short-term cognitive impairments and behavioral disturbances that typically occur in the absence of significant brain damage. The current study addresses the need to better understand the effects of a mild lateral fluid percussion injury on rat behavior and neuropathology in an animal model of concussion. Male Long-Evans rats received either a single mild fluid percussion injury or a sham-injury, and either a short (24h) or long (4 weeks) post-injury recovery period. After recovery, rats underwent a detailed behavioral analysis consisting of tests for rodent anxiety, cognition, social behavior, sensorimotor function, and depression-like behavior. After testing all rats were sacrificed and brains were examined immunohistochemically with markers for microglia/macrophage activation, reactive astrocytosis, and axonal injury. Injured rats (mean injury force: 1.20 $\pm$.03 atm) displayed significant short-term cognitive impairments in the water maze and significantly more anxiolytic-like behavior in the elevated-plus maze compared to sham controls. Neuropathological analysis of the brains of injured rats showed an acute increase in reactive astrogliosis and activated microglia in cortex and evidence of axonal injury in the corpus callosum. There were no significant long-term effects on any behavioral or neuropathological measure 4 weeks after injury. These short-term behavioral and neuropathological changes are consistent with findings in human patients suffering a brain concussion, and provide further evidence for the use of a single mild lateral fluid percussion injury to study concussion in the rat.},
  language = {eng},
  number = {2},
  journal = {Behavioural Brain Research},
  author = {Shultz, Sandy R. and MacFabe, Derrick F. and Foley, Kelly A. and Taylor, Roy and Cain, Donald P.},
  month = oct,
  year = {2011},
  keywords = {Amyloid beta-Protein Precursor,Animals,Anxiety,Axons,Behavior; Animal,Brain,Brain Chemistry,Brain Concussion,Brain Injuries,Disease Models; Animal,Glial Fibrillary Acidic Protein,Gliosis,Immunohistochemistry,Male,Maze Learning,Motor Activity,Postural Balance,Rats,Rats; Long-Evans,Social Behavior,Space Perception,Swimming},
  pages = {326-335},
  pmid = {21704658},
  note = {00066}
}
```

**Comment by retorquere** [comment]
Can you split off the 2nd problem to a separate github issue? Otherwise the conversation gets very jumbled (also: no need to post screenshots, the debug report you send has the references)

**Comment by retorquere** [comment]
So strictly on the first issue: you're currently seeing `shultz2011` in the Zotero GUI, but you get `shultz2011d` if you export with BBT?

**Comment by alapo** [comment]
> So strictly on the first issue: you're currently seeing `shultz2011` in the Zotero GUI, but you get `shultz2011d` if you export with BBT?

This is correct for the first issue. For some reason when I export to .bib it is not updating the citekey.

Apologize for the screenshots I was just trying to be as descriptive as possible. I believe these 2 issues are connected. If the proper .bib is exported the issue with the in-text citation might be fixed. 

Would it make sense to wait to find a resolution to this problem before adding a new issue?

Thanks for your help, happy to troubleshoot and provide any extra files.

**Comment by retorquere** [comment]
I don't mind either way, but I don't like working on two issues in one discussion. If they turn out to be connected we'll know soon enough when the other vanishes, but in general, I prefer more issues being files even if they turn out to be duplicates over having a conversation about two things in one issue -- to be specific, I'd prefer having the text under "other issue" be moved to another issue (or removed, but why lose history?) -- it helps me keep oversight.

I'm running some local tests to try and reproduce the citekey issue.

**Comment by alapo** [comment]
Sounds good to me. If you require any files on my head to help please let me know.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.57.3518](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.57.3518.xpi) ("DB cleanup")

Install in Zotero by downloading [test build 5.1.57.3518](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.57.3518.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 3518?

**Comment by alapo** [comment]
I tried the new release and it now works. Fixed both problems with one release. Thanks for your help!

**Comment by retorquere** [comment]
Super, and thanks for the confirmation. 5.1.58 is building with this fix included, but it's just a rebranded 3518, and you will automatically be upgraded by Zotero in the next few days.

It turns out to be a [cache invalidation](https://martinfowler.com/bliki/TwoHardThings.html) problem. If Zotero is shut down after a delete before I can update the cache, the old cached item will be seen as current. Any change to the item would probably also have fixed it (because a change would update the cache), but 3518 added a scan at startup comparing the cache time with the entry time, and dropping cache entries older than their source. That will cause the cache to be rebuilt for those during export, and that fixes it.
