### ISSUE TITLE
Feature Request: Give user more control over "export as plain-text latex commands"

### ISSUE THREAD

**Issue by jandhau** [retorquere/zotero-better-bibtex#1135]
For biblatex export (possibly also useful for BibTeX), it would be useful if the user could specify independently if (a) typographic quotes will be replaced with latex quotes (b) unicode characters (such as umlauts and accents etc.) will be replaced with latex commands, or both.
As of now, the "export as plain-text latex commands" checkbox controls both, so they can only be switched on and off together.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.56.3515](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.56.3515.xpi) ("fixes #1135")

Install in Zotero by downloading [test build 5.1.56.3515](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.56.3515.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
3515 has a [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) called `ascii` -- you can enter characters there and those will always be changed to their LaTeX counterparts. In your case, you can add the typographic quotes there. The `csquotes` preference, if set, takes precedence though.

**Comment by jandhau** [comment]
Just tested with this entry
https://www.sciencedirect.com/science/article/pii/S0271530915000798
(which has single and double quotes)

Works like a charm!!   Thanks so much for quickly adding that!

**Comment by retorquere** [comment]
You're welcome. 5.1.57 is building and will have this, but it's just a rebranded 3515. You will be upgraded automatically.
