### ISSUE TITLE
Change type on export

### ISSUE THREAD

**Issue by jandhau** [retorquere/zotero-better-bibtex#1140]
Is there a way to change the type of the entry in the postscript? 

Although my target is BibLaTeX, I do not use the "collection" type, and prefer to have both books and collections as "book" in my .bib file (distinguished by the presence or absence of an author). 

Is there a way to swap collection with book? 

I assume I'd have to start with 
`if (Translator.BetterBibLaTeX && item.itemType === 'collection') { 
`
but ... I'm afraid I don't know javascript to figure it out myself :/

**Comment by retorquere** [comment]
No worries, scripting isn't as well-documented as it should be, so I generally just do these on request. You can achieve what you want in two ways:

indeed with scripting for all items at once:

```
if (Translator.BetterBibLaTeX && item.itemType === 'collection') item.referencetype = 'book'
```

or add this to the `extra`field for individual items

```
bibtex[referencetype=book]
```

**Comment by jandhau** [comment]
Excellent, this works!

**Comment by jandhau** [comment]
Oops, I closed this prematurely, I thought I had tried it but apparently that link was a book already.
With collections from amazon.com I actually still get "collection" and not "book"
using `if (Translator.BetterBibLaTeX && item.itemType === 'collection') item.referencetype = 'book'`
?

**Comment by retorquere** [comment]
My bad. The `.itemType` is the *Zotero* type. You want to either test for the Zotero itemType (export to `BetterBibTeX JSON` to see what itemType an item has, or test for `item.referencetype === 'collection'`

**Comment by jandhau** [comment]
Oh, I see, well, JSON gives me `"itemType": "book",`  (and in Zotero itself it's also listed as "Book")?  But it still becomes a "collection" in the .bib export.  Is it maybe that BBT tests for books without author and translates them into collection automatically (in which case testing for "book" doesn't help, of course).

**Comment by retorquere** [comment]
I'm not sure, I'd need a BBT error report to tell, but testing on `item.referencetype === 'collection'` should always work for your case.

**Comment by jandhau** [comment]
Did you see the error report for the item (the same that I submitted for the other thread)?  ID is WVKXIW2D-euc

Thanks so much for your attention to my issues and immediate help, BTW :) Very much appreciated!

**Comment by retorquere** [comment]
That should have been

```
if (Translator.BetterBibLaTeX && this.referencetype === 'collection') this.referencetype = 'book'

// Duplicate title to shorttitle if empty
if (Translator.BetterBibLaTeX && !this.has.shorttitle) this.add({ name: 'shorttitle', value: item.title })

// Duplicate title to booktitle for books
if (Translator.BetterBibLaTeX && item.itemType === 'book') this.add({ name: 'booktitle', value: item.title })

// Set english as langid if empty
if (Translator.BetterBibLaTeX && !this.has.langid) this.add({ name: 'langid', value: 'english' })

// Only export year to date field
if (Translator.BetterBibLaTeX && item.date) {
  const date = Zotero.BetterBibTeX.parseDate(item.date)
  if (date.type === 'date') this.add({ name: 'date', value: date.year })
}

// Correct single hyphens in page field
if (Translator.BetterBibLaTeX) {
  if (this.has.pages) this.has.pages.bibtex = this.has.pages.bibtex.replace(/(\w+)-(\w+)/g, '$1--$2');
}
```

or a little compacter

```
if (Translator.BetterBibLaTeX) {

  if (this.referencetype === 'collection') this.referencetype = 'book'

  // Duplicate title to shorttitle if empty
  if (!this.has.shorttitle) this.add({ name: 'shorttitle', value: item.title })

  // Duplicate title to booktitle for books
  if (item.itemType === 'book') this.add({ name: 'booktitle', value: item.title })

  // Set english as langid if empty
  if (!this.has.langid) this.add({ name: 'langid', value: 'english' })

  // Only export year to date field
  if (item.date) {
    const date = Zotero.BetterBibTeX.parseDate(item.date)
    if (date.type === 'date') this.add({ name: 'date', value: date.year })
  }

  // Correct single hyphens in page field
  if (this.has.pages) this.has.pages.bibtex = this.has.pages.bibtex.replace(/(\w+)-(\w+)/g, '$1--$2');
}
```

**Comment by retorquere** [comment]
Does that work for you?

**Comment by jandhau** [comment]
Sorry for getting back late ... Yes!  This one works.  Thanks also for fixing the rest of the code  :)
