### ISSUE TITLE
page numbers missing from csl style for pandoc conversion

### ISSUE THREAD

**Issue by ppoppitz** [retorquere/zotero-better-bibtex#1141]
I want to prepare a word file for latex conversion using pandoc. Following the advice in this thread [[1]](https://forums.zotero.org/discussion/comment/317413/#Comment_317413) I have used the option `citeprocNoteCitekey` and the `better-bibtex-citekeys.csl` style to obtain references in the word file such as this one:
```
[@ludemannJacquesDerridaZur2013]
```
Problem:
- Page numbers are missing from the output, even though prefix and postfix are printed. Would be nice to print them in a way that makes it easy convert them with a simple regex search and replace after the pandoc run.

I guess one would have to change the csl style, but I struggled to change it by myself.

**Comment by retorquere** [comment]
I have no experience whatsoever using or creating CSL styles, sorry. The CSL style I added was only to show how it would work, technically. But in principle you should be able to load any style you want as a base into the [CSL editor](http://editor.citationstyles.org/visualEditor/) and put the `note` field wherever you want the citekey to appear (most likely `inline` - `layout` - `group`).

**Comment by ppoppitz** [comment]
Thanks for the input. I have changed the CSL style according to my personal needs, which is probably not so useful for other users.
However, I thought it could be helpful for others to include the page variable `locator` in your example style according the pandoc markdown manual. 
I made a pull request, but its a first for me, so I hope it works.

**Comment by retorquere** [comment]
Looks good to me -- merged.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.58.3538](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3538.xpi) ("Update better-bibtex-citekeys.csl (#1142)\n\nsee #1141")

Install in Zotero by downloading [test build 5.1.58.3538](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3538.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
