### ISSUE TITLE
citekey firstpage-lastpage

### ISSUE THREAD

**Issue by linuxrider** [retorquere/zotero-better-bibtex#1147]
Till now I used the [zotero] citekey pattern.
Since some authors have same initial title words within the same year there is conflicts resolved by appending a number. Now I wanted to just append the firstpage.
So I came up with this: [zotero][firstpage:prefix=_], which works as long as there is no page prefix.
[firstpage] is empty for page numbers with prefix.
The result is author_titleword_year.
Is it possible to achieve  firstauthor_firstwordtitle_year_firstpageincludingprefix?

This is the error code for a reference for pages L1-L6  D45C7VNX-euc.

I very much like BBT. It saves a lot of time, thank you.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.58.3569](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3569.xpi) ("fixes #1147")

Install in Zotero by downloading [test build 5.1.58.3569](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3569.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try installing 3569

**Comment by linuxrider** [comment]
Thank you, seems to work.
A problem occurs now, when in the pages field instead of a hyphen the – (unicode 2013) is used.
In such a case (e.g. 183–194) the result is 
author_word_year_183-194 instead of author_word_year_183.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.58.3570](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3570.xpi) ("add m-dash as page splitter")

Install in Zotero by downloading [test build 5.1.58.3570](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3570.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.58.3571](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3571.xpi) ("backslash -> textbackslash")

Install in Zotero by downloading [test build 5.1.58.3571](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3571.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by linuxrider** [comment]
With build 3570 + 3571 [firstpage] is empty for all items I tried.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.58.3572](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3572.xpi) ("dash needs to go first")

Install in Zotero by downloading [test build 5.1.58.3572](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3572.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 3572?

**Comment by linuxrider** [comment]
I could not find a case where it is NOT working.
Thank you for your efforts!

**Comment by retorquere** [comment]
Thanks for the confirmation -- 5.1.60 is building for release with this fix.
