### ISSUE TITLE
Broken output for van/von

### ISSUE THREAD

**Issue by VorpalBlade** [retorquere/zotero-better-bibtex#1149]
**Expected behavior:**

Data that is generated should work with at least one of biber, bibtex or bibtex8, but they all fail to parse the output below in different ways

bibtex & bibtex8 gives the following error:
```
Too many commas in name 2 of "Lokhorst, Gert-Jan and family=Hoven, given=Jeroen, prefix=van den, useprefix=true" for entry lokhorstResponsibilityMilitaryRobots2014
while executing---line 2513 of file biblatex.bst
```
biber just skips the item silently (not generating any entry in the output PDF file).
Also the preview in LyX of the item is heavily broken as well, showing as "(Lokhost and famiily=Hoven 2014)"

Error report ID is EH8PMHM2-euc.

I have also exported the item in question as a Zotero RDF:
[Exported Items.rdf.txt](https://github.com/retorquere/zotero-better-bibtex/files/3014923/Exported.Items.rdf.txt)

**Actual behavior:**

The following broken entry is generated (note weird author key):
```
@incollection{lokhorstResponsibilityMilitaryRobots2014,
  title = {Responsibility for {{Military Robots}}},
  isbn = {978-0-262-52600-5},
  booktitle = {Robot {{Ethics}}: {{The Ethical}} and {{Social Implications}} of {{Robotics}}},
  publisher = {{The MIT Press}},
  date = {2014},
  pages = {145-156},
  author = {Lokhorst, Gert-Jan and family=Hoven, given=Jeroen, prefix=van den, useprefix=true},
  editor = {Lin, Patrick and Abney, Keith and Bekey, George A.}
}
```

For reference, here are the versions of the software I have (latest versions in Ubuntu 16.04 which I'm currently stuck with). It also doesn't work with the python parser [pybtex](pybtex.org) which I'm also trying to use.
```
$ biber --version
biber version: 2.4

$ bibtex --version
BibTeX 0.99d (TeX Live 2015/Debian)
kpathsea version 6.2.1
Copyright 2015 Oren Patashnik.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the BibTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the BibTeX source.
Primary author of BibTeX: Oren Patashnik.

$ bibtex8 --version
This is 8-bit Big BibTeX version 0.99d
Implementation:  C for Unix
Release version: 3.71 (18 mar 2013)
```

**Comment by retorquere** [comment]
I think you have [biblatexExtendedNameFormat](https://retorque.re/zotero-better-bibtex/configuration/#use-biblatex-extended-name-format-requires-biblatex-35) preference turned on. This requires at least biber 2.7 and biblatex 3.5 to work.

**Comment by retorquere** [comment]
Confirmed: you have `biblatexExtendedNameFormat` on. BTW, for error reporting, you don't need to export to RDF; if you right-click the problematic item and submit an error report from there, I automatically get a copy of those references, in a format that's easier to handle for me than RDF.

**Comment by retorquere** [comment]
It's not broken BTW, it's just a format that a lot of latex work flows haven't updated to yet (which is why it's off by default)

**Comment by VorpalBlade** [comment]
Yes that seems to fix it. I don't remember actively turning that option on, I must have done it by mistake. Thanks for the quick reply.
