### ISSUE TITLE
 Zotero Citation Key Doesn't Match using export "Better BibTex"

### ISSUE THREAD

**Issue by lkorczowski** [retorquere/zotero-better-bibtex#1150]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu
----------------------------------------------

Sorry to open a new thread but I found out a weird behavior with the zotero citation key similar to #1030 .

My citation key formatting is `[auth:lower]_[veryshorttitle:lower]_[year]` and it is working perfectly both in Zotero UI and while using BBT "Better BibLaTeX" export option.

However the BBT "Better BibTeX" export option will generate the previous citation key formatting (the one before the one set actually). Weird doesn't it ?

Example, I played a bit with different key formatting:

1. `[auth:lower]_[veryshorttitle:lower]_[year] `+ refresh all key
2.  `[auth:lower]_[veryshorttitle:lower]_x[year]` + refresh all key. Result: better biblatex "barachant_riemannian_x2013", better bibtex "barachant_riemannian_2013"
3. `[auth:lower]_[veryshorttitle:lower]_[year]`+ refresh all key. Result: better biblatex "barachant_riemannian_2013", better bibtex "barachant_riemannian_x2013"
4. refresh all key. Result: no change.

How can be even possible? Am I the only one experiencing this issue ?

EDIT:
the Report ID is RQHVBE7M-euc

**Comment by retorquere** [comment]
It's always OK to open a new thread.

I don't mean to be rude, but the boilerplate when you opened the issue specifically asked for a debug log and specified the steps to generate it. Without the debug log, I really can't do much to diagnose these issues.

**Comment by lkorczowski** [comment]
You are not rude, that's my fault sorry (I'll edit the thread with the checklist). I got the following error while sending the report :

"TypeError: wizard.advance is not a function (DIS8NR5T-euc, references: true)"

**Comment by retorquere** [comment]
This is on a Mac?

**Comment by lkorczowski** [comment]
I succeeded after restarting Zotero, here's the report ID:
RQHVBE7M-euc

No, it is windows 10.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.62.3625](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.62.3625.xpi) ("clean up cache on refresh")

Install in Zotero by downloading [test build 5.1.62.3625](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.62.3625.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try installing 3625 and refreshing some keys.

**Comment by lkorczowski** [comment]
solved!

Better Bibtex is working as expected now. "Keep updated" also work.

Many thanks :)

**Comment by retorquere** [comment]
Awesome, thanks for the confirmation. I'll put out a new release tonight, but it's just a rebadged 3625. You can keep using this, and you'll be upgraded automatically.

**Comment by retorquere** [comment]
(don't close the issue yet, I'll close it when I have the release out)
