### ISSUE TITLE
Japanese Input Manager Editor "ATOK" mangles text output from BBT CAYW

### ISSUE THREAD

**Issue by DarrenMMcDonald** [retorquere/zotero-better-bibtex#1154]
I am using Zotero (standalone) and BBT on a MacOS Mojave 10.4 in Japanese with a Japanese Input Manager Editor known as ATOK ( https://www.justsystems.com/en/products/atok.html ).

I use the "pop up" window in a note taking application (Agenda https://agenda.com), search for a citation and to have the citation automatically pasted into the note taking application. What results for a citation of "Brewer, 1991" is the following:

{｜Ｂれうぇｒ、1991｜｜｜ず：276004：4EAB2LZW｝

It should appear as:

{|Brewer,1991|||zu:276004:4EAB2LZW}

I posted this issue in Zotero's User's Forum ( https://forums.zotero.org/discussion/76559/accessing-citations-in-applications-other-than-word-mac-newbie/p1 ). I achieved wonderful assistance there to hone the problem down to a possible conflict with ATOK and BBT. In the Forum, I was asked to open an issue here. 

I was asked to post the attached 4 files.

If you need any further information or need me to do anything, please let me know. I am not a programmer, so detailed instructions would be appreciated.

I hope the issue can be solved.

Cheers! :)

[clipboard-contents-bbt.txt](https://github.com/retorquere/zotero-better-bibtex/files/3076144/clipboard-contents-bbt.txt)
[clipboard-contents-manual.txt](https://github.com/retorquere/zotero-better-bibtex/files/3076145/clipboard-contents-manual.txt)
[clipboard-state-bbt.txt](https://github.com/retorquere/zotero-better-bibtex/files/3076146/clipboard-state-bbt.txt)
[clipboard-state-manual.txt](https://github.com/retorquere/zotero-better-bibtex/files/3076147/clipboard-state-manual.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.66.3673](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.66.3673.xpi) ("Merge branch 'master' into 1154")

Install in Zotero by downloading [test build 5.1.66.3673](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.66.3673.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Mendeley puts the text on the clipboard in RTF. Build 3673 does that too -- see if that helps. Note that this will only work with the applescript script that pastes from the clipboard, not the applescript script that "types" into the foreground app.

**Comment by DarrenMMcDonald** [comment]
Unfortunately, I still get the same result, i.e.:

{｜Ｂれうぇｒ、1991｜｜｜ず：276004：4EAB2LZW｝

The applescript I am using is:

https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-scannable-cite.applescript

I would like to try "... the applescript script that pastes from the clipboard, not the applescript script that "types" into the foreground app." Where would I get this applescript?

**Comment by retorquere** [comment]
That applescript types the result into the foreground app as if you typed it. That's not going to work with ATOK active because ATOK will take that as it's cue to interfere. What you can do is open http://127.0.0.1:23119/better-bibtex/cayw?format=scannable-cite&clipboard=true, pick the reference you want, and then paste (cmd-v) the results and see if that works. If it does, an applescript that does the pasting on your behalf should also work.

As to how to get such an applescript, maybe @davepwsmith can get you this, but I'm not familiar with applescript. I can only help to make sure the backend in Zotero does what needs to be done, what the front-end does with it is for others (such @davepwsmith) to pick up on. But let's first test whether this helps at all.

**Comment by DarrenMMcDonald** [comment]
When I paste (cmd-v) the result I get is:

{ | Brewer, 1991 | | | zu:276004:4EAB2LZW }

for "Brewer 1991". This seems correct and ATOK did not take the cue to interfere.

How do I make contact with @davepwsmith to develop an applescript that does the pasting on my behalf?

**Comment by retorquere** [comment]
You could try opening an issue on https://github.com/davepwsmith/zotpick-applescript/issues.

I'll merge thus change into a new release; I've just been afflicted with a new MacBook so I may take a look in the next week whether it's an easy change to make, but a) I don't know why type was chosen over paste in the existing script, there may be good reasons to avoid paste that I don't know of, b) I'm not familiar with applescript, so it may take a while, and c) what I've seen from it makes it seem a pretty unappealing language to use, so no promises. Your best bet is still @davepwsmith, who has shown himself brave enough to volunteer to use it.

**Comment by retorquere** [comment]
Any progress? Have you tried the paste code from the forum thread?

**Comment by retorquere** [comment]
3673 (which I'll merge once we have the whole thing working) will put html and RTF on the clipboard. I've looked on stackoverflow and from what I see there, replacing `keystroke theReference` with `keystroke "v" using command down` (and adding `&clipboard=true` to the url in the script) should work, but I also see warnings that if you hold down a modifier key (such as ctrl) while it's pasting it would be seen as cmd-ctrl-v and it's unpredictable what that would do.

I've not tested this. I'm not really familiar with Macs. I concentrate on the backend in BBT.

**Comment by DarrenMMcDonald** [comment]
Could you provide me with more detailed instructions as to what to do?

Sorry.I tried to work out what you were asking, but my limited computer programming knowledge let me down. :(

Cheers! :)

**Comment by retorquere** [comment]
You take the applescript from https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-scannable-cite.applescript, but change [this line](https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-scannable-cite.applescript#L23) into

```
set theReference to do shell script "/usr/bin/curl 'http://127.0.0.1:23119/better-bibtex/cayw?format=scannable-cite&clipboard=true' 2>/dev/null; exit 0"
```

and [this line](https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-scannable-cite.applescript#L33)

into

```
keystroke "v" using command down
```

for completeness, this requires 3673 to be installed. Otherwise you'll just get the expected ATOK interference.

**Comment by DarrenMMcDonald** [comment]
I changed the applescript as you described and I got:

{ | Brewer, 1991 | | | zu:276004:4EAB2LZW }

It has seemed to work! :) Thanks you so much for all your help! :)

What will you do now?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.68.3801](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3801.xpi) ("datadir profile for jurism")

Install in Zotero by downloading [test build 5.1.68.3801](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3801.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
3801 includes all the changes that were made to BBT while we were working on this issue -- I'd appreciate it if you could do a final test on that to see if it still works for you, and then I will roll this into a new release.

As a courtesy, could you open an issue on https://github.com/davepwsmith/zotpick-applescript/issues and explain the problems you've had with ATOK? @davepwsmith may update the scripts, but at least people going there for similar problems could see solutions exist.

**Comment by DarrenMMcDonald** [comment]
I posted on https://github.com/davepwsmith/zotpick-applescript/issues/21 a brief explanation of the problems we encountered and the solution. I am not sure if my explanation is good enough. 

PS. Is "retorquere" and "emilianoeheyns" the same person? I just wondered who I should thank for all this hard work.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.68.3818](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3818.xpi) ("ncu")

Install in Zotero by downloading [test build 5.1.68.3818](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3818.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
It seems like a very extensive explanation; it should be absolutely fine. If you could verify that with 3818 you still have the problem solved, I can release a new version that has this behavior as standard.

Yep, retorquere and emilianoeheyns is both me.

**Comment by DarrenMMcDonald** [comment]
I can confirm that build 3818 fixes the issue. 

Thank you so much for your help. I chipped in a little bit towards your goal of purchasing a new Mac.

**Comment by retorquere** [comment]
Awesome, thanks (for both!).

The Mac is in, I'm still adjusting. Still a ton of appliances to buy just to get basic connectivity going (the new MacBook is pretty ridiculous with its 4 usb-c ports and the nothing else)

**Comment by retorquere** [comment]
I'll cut a new release in a few hours when I'm back at my PC.
