### ISSUE TITLE
Postscript error aborts CSL JSON export

### ISSUE THREAD

**Issue by annargrs** [retorquere/zotero-better-bibtex#1155]
- [ x ] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [ x ] I am posting a single question, bug or feature request
- [ x ] I have included a descriptive subject of the problem
- [ x ] I am available for follow-up questions and testing
- [ x ] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Report ID: U9HZLUYC-euc

**Exporter used:** Better CSL Json

**Expected behavior:** Exporting library with Better CSL JSON should result in exported file. 

**Actual behavior:** An error window pops up: "An error occurred while trying to export the selected file". I tried 3 different collections, all with the same result.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.66.3679](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.66.3679.xpi) ("fixes #1155")

Install in Zotero by downloading [test build 5.1.66.3679](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.66.3679.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
The postscript you have installed is only compatible with Better Bib(La)TeX but doesn't [check in which exporter it runs]. I should have caught any such errors and ignored them, that's now in place in 3679 -- if you could verify this fixes it for you, I can cut a new release.

**Comment by annargrs** [comment]
Thanks, I just tested the new build - the export works now.

**Comment by retorquere** [comment]
Awesome -- a new release has been scheduled.
