### ISSUE TITLE
URL/DOI exclusive export option

### ISSUE THREAD

**Issue by moorepants** [retorquere/zotero-better-bibtex#1156]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

**Your question/suggestion:**

I would really like a URL export option that is "export URL if there is no DOI". Right now I store both the URL and DOI for an item in zotero. If it has a DOI I'd like only it to show in the bib export but if it doesn't have a DOI and has a URL I'd like that to show, but there is no reason to show both the URL and DOI in the rendered bibliography.

If you point me to the relevant code I could potentially submit a PR.

**Comment by retorquere** [comment]
The hardest about this would be a coherent UI concept. The current UI part lives [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/Preferences.xul#L627), the part that does the actual export based on the preference settings is [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/translators/bibtex/reference.ts#L518).

**Comment by retorquere** [comment]
Wouldn't setting the `DOI/URL` preference to `DOI` already do this?

**Comment by moorepants** [comment]
I have "add urls to bibtex export" as "in a note field" (because the URLs will not show up if I have it as "no"). And I have "when a reference has both a doi and url, export" as "doi", but they both show up in the export. I'm unable to get it to export only the url or doi with preference to doi. Maybe I'm not setting things correctly?

**Comment by retorquere** [comment]
Hmm no, it's just a scenario I hadn't considered before. Can you right-click on an item that has this and submit an error report?

**Comment by moorepants** [comment]
Yes, I'll try to submit later today.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.67.3683](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.67.3683.xpi) ("fixes #1156")

Install in Zotero by downloading [test build 5.1.67.3683](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.67.3683.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I really need to know whether this addresses your concern before I can merge this into a release.

**Comment by moorepants** [comment]
I haven't had time to try it out, day job keeps me busy. Will get to it as soon as I can.

**Comment by retorquere** [comment]
My day job also keeps me busy, and I'm doing this in the little spare time I have left between job, studies, and family.

**Comment by moorepants** [comment]
Aren't we all...

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.68.3819](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3819.xpi) ("Merge branch 'master' into 1156")

Install in Zotero by downloading [test build 5.1.68.3819](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.68.3819.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
3683 expired; please try3819 instead.

**Comment by retorquere** [comment]
Assuming fixed

**Comment by moorepants** [comment]
3819 is working as I'd hope. thanks.
