### ISSUE TITLE
preserve @strings between import/export

### ISSUE THREAD

**Issue by wkjarosz** [retorquere/zotero-better-bibtex#1162]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Is there a way to have Zotero+BBT preserve @string variables between import/export? I see that I can define "import @string definitions", but this seems to simply allow BBT to expand those strings upon import. I'd prefer to keep the strings as macros so that I can ensure consistency between bib entries and modify the strings globally if needed.

**Comment by retorquere** [comment]
Not really, no. It would make the import parser pretty complicated and it's not a level of complexity I'm looking to add. It would be possible to add a preference so the `import @string definitions` would get output at export, and perhaps then you could do something sneaky with `<pre>`, but it would be decidedly unpretty.

For this kind of thing, you might be better off using JabRef, and using something like zot2bib to abuse Zotero as a capture tool.

**Comment by wkjarosz** [comment]
OK, so would you consider adding related functionality to the exporter instead?

You already have the "Assume single-word strings to be externally-defined @string vars" setting, which does nearly what I would like. However, instead of allowing the single-word setting to apply to all single-word fields (which has a high risk of false positives), would it be possible to have a tab called "export @string definitions" so that only single-word strings that are in this list would be written without surrounding braces?

This would allow importing and exporting bibtex files that rely on externally defined @strings. My hope is to use Zotero + BBT as a bibtex management system, and relying on @strings for consistent naming is essential.

Thanks again for the great work.

**Comment by retorquere** [comment]
Fair enough. I see you've opened a new issue, let's continue the discussion there.

**Comment by retorquere** [comment]
Oh wait, the other issue is slightly different.

**Comment by retorquere** [comment]
This is not too hard, I'll try to get something done today.

**Comment by retorquere** [comment]
Um, except there's the issue that if you have `@strings` defined, BBT will replace those on import by default. I'll have to think about this.

**Comment by retorquere** [comment]
Do you want me to merge this with #1171 for easier testing?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3848](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3848.xpi) ("update preference")

Install in Zotero by downloading [test build 5.1.72.3848](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3848.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by wkjarosz** [comment]
> Um, except there's the issue that if you have `@strings` defined, BBT will replace those on import by default. I'll have to think about this.

I was thinking that if there is a separate "import @strings" tab, and an "export @strings tab", I would not enter the @strings in the "import" tab, but would add them to the "export" tab. That way, Zotero would just show all my variable, but upon export I could combine the BBT-generated bib file with my bib file defining the @strings.

> Do you want me to merge this with #1171 for easier testing?

Sorry, I'm relatively new to github, so not sure how to merge issues.

**Comment by retorquere** [comment]
In 3848, there's a single `@strings` field, but you can select whether it is active for import and/or export.

You wouldn't have to merge anything, I would just merge the changes from #1171 in the xpis that are announced here and would not have new xpis announced on #1171.

**Comment by wkjarosz** [comment]
> In 3848, there's a single `@strings` field, but you can select whether it is active for import and/or export.
> 
> You wouldn't have to merge anything, I would just merge the changes from #1171 in the xpis that are announced here and would not have new xpis announced on #1171.

I added my @strings to the preference, and exported an item that uses strings for publisher, book title, and series. It properly uses the strings only for the book title.

Also, I see that the @strings are copied over to the exported bib file. Could you make this optional? I keep my @string definitions in a separate bib file so that I can for instance use a different set of definitions with abbreviated strings on demand.

Thanks!

**Comment by retorquere** [comment]
I really need to know whether you want to merge #1171. I'm making changes in the same parts of BBT in those two branches and if I don't merge these two, I need to make an intermediary partial merge to make sure they don't conflict later.

**Comment by wkjarosz** [comment]
> I really need to know whether you want to merge #1171. I'm making changes in the same parts of BBT in those two branches and if I don't merge these two, I need to make an intermediary partial merge to make sure they don't conflict later.

Sorry, yes. Allowing both @strings in the series and publisher fields and enabling the new @strings panel can be merged. Do I do that or do you? (again, sorry, this is my first time working with Issues on GitHub)

**Comment by retorquere** [comment]
You don't need to do anything, the change has already been merged. A new build that enables `@strings` for `publisher` will be announced here in 10 minutes or so.

**Comment by retorquere** [comment]
BTW, can you right-click a reference that you want exported this way send a BBT error report? That will get me a sample to add to the test suite. If you could also export that same reference to BibLaTeX, edit it to your liking, and attach that here, I'll have a complete test case. Make sure the `@strings` preferences are set as you would use them -- the debug report exports your BBT preferences and the test suite loads those.

**Comment by retorquere** [comment]
Hmm, first test failure -- with preserve set to "detect" (the equivalent to the "on" setting in the existing release, the publisher `Brill` gets detected as a potential `@string` var. This would not affect matching of course.

Well, I did always warn you didn't want this on unless you knew what you were doing, and the bew `match` mode would prevent this.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3852](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3852.xpi) ("Brill detected as var")

Install in Zotero by downloading [test build 5.1.72.3852](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3852.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 3852

**Comment by wkjarosz** [comment]
> Try 3852

Sorry for the delay. Just tried 3852. Successfully avoids braces for book title and series, but still wraps braces for publisher. Was that expected?

> BTW, can you right-click a reference that you want exported this way send a BBT error report? That will get me a sample to add to the test suite. If you could also export that same reference to BibLaTeX, edit it to your liking, and attach that here, I'll have a complete test case. Make sure the `@strings` preferences are set as you would use them -- the debug report exports your BBT preferences and the test suite loads those.

I'll work on getting you a sample later today.

**Comment by retorquere** [comment]
Not necessarily expected, no. Once I have a sample it's easier to work towards working tests.

**Comment by wkjarosz** [comment]
> BTW, can you right-click a reference that you want exported this way send a BBT error report? That will get me a sample to add to the test suite. If you could also export that same reference to BibLaTeX, edit it to your liking, and attach that here, I'll have a complete test case. Make sure the `@strings` preferences are set as you would use them -- the debug report exports your BBT preferences and the test suite loads those.

I've submitted an error report: FB297GNE-euc.

I've also attached a test case bib record along with the relevant @strings.

[test-case.txt](https://github.com/retorquere/zotero-better-bibtex/files/3117777/test-case.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3861](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3861.xpi) ("allow preserve-vars for extra fields when match")

Install in Zotero by downloading [test build 5.1.72.3861](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3861.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 3861 a go. I had to edit the input a bit -- the publication title said `PROC_SIGGRAPH93_01` but the match string was `PROC_SIGGRAPH93-01`, and the `organization` data in the `extra` field had HTML code that I stripped.

**Comment by wkjarosz** [comment]
Ah, sorry. I must have edited the string and not the entry. I’ll test this out later today. Thanks!

**Comment by wkjarosz** [comment]
> Give 3861 a go. I had to edit the input a bit -- the publication title said `PROC_SIGGRAPH93-01` but the match string was `PROC_SIGGRAPH93_01`, and the `organization` data in the `extra` field had HTML code that I stripped.

Ok, I tried 3861.

series, organization, and booktitle all get properly exported, but publisher still wraps things in braces.

I stripped the html code from the test-case bibfile I attached, I had not realized the error report includes that as well, and had not caught that issue yet.

FYI: the HTML code was generated by BBT on import into zotero, though I just tried again now and it imports properly now. Import does produce an "Import errors found" note with the following:

line 6: undefined variable 'ACS'
line 8: undefined variable 'PROC_SIGGRAPH93-01'
line 10: undefined variable 'ACM_SIGGRAPH'
line 11: undefined variable 'AW'

The exported bib file also no longer includes the @string defines.

**Comment by retorquere** [comment]
`publisher` does export as vars for me. Please right-click that reference and send a new debug report, and I can have a look. If you right-click and send a report, I get a copy of the reference as it sits in Zotero so that I can best replicate any issue you might experience.

The "import errors found" is normal. It means the bibtex you imported has these vars but they're not in the `@strings` field, nor are they in the bibtex being imported.

The exported bib file indeed no longer includes the `@string` defines.

**Comment by retorquere** [comment]
Current test case:

input: https://github.com/retorquere/zotero-better-bibtex/blob/gh-1162/test/fixtures/export/preserve%20%40strings%20between%20import-export%20%231162.json

output: https://github.com/retorquere/zotero-better-bibtex/blob/gh-1162/test/fixtures/export/preserve%20%40strings%20between%20import-export%20%231162.biblatex

**Comment by wkjarosz** [comment]
> `publisher` does export as vars for me. Please right-click that reference and send a new debug report, and I can have a look. If you right-click and send a report, I get a copy of the reference as it sits in Zotero so that I can best replicate any issue you might experience.
> 
> The "import errors found" is normal. It means the bibtex you imported has these vars but they're not in the `@strings` field, nor are they in the bibtex being imported.
> 
> The exported bib file indeed no longer includes the `@string` defines.

New error report: B7TDRM2M-euc

**Comment by retorquere** [comment]
This one has substantially different `@strings` right?

**Comment by retorquere** [comment]
For me this exports to (using the settings contained in the report):

```
@inproceedings{Mitchell96,
  author = {Mitchell, Don P.},
  booktitle = PROC_SIGGRAPH93-01,
  date = {1996-08},
  editor = {Rushmeier, Holly},
  organization = ACM_SIGGRAPH,
  pages = {277-280},
  publisher = AW,
  series = ACS,
  title = {Consequences of {{Stratified Sampling}} in {{Graphics}}}
}
```

What does it export to for you?

**Comment by wkjarosz** [comment]
> For me this exports to (using the settings contained in the report):
> 
> ```
> @inproceedings{Mitchell96,
>   author = {Mitchell, Don P.},
>   booktitle = PROC_SIGGRAPH93-01,
>   date = {1996-08},
>   editor = {Rushmeier, Holly},
>   organization = ACM_SIGGRAPH,
>   pages = {277-280},
>   publisher = AW,
>   series = ACS,
>   title = {Consequences of {{Stratified Sampling}} in {{Graphics}}}
> }
> ```
> What does it export to for you?

This is what I get: 

```
@inproceedings{Mitchell96,
  series = ACS,
  title = {Consequences of {{Stratified Sampling}} in {{Graphics}}},
  booktitle = PROC_SIGGRAPH93-01,
  publisher = {{AW}},
  author = {Mitchell, Don P.},
  editor = {Rushmeier, Holly},
  month = aug,
  year = {1996},
  pages = {277-280},
  organization = ACM_SIGGRAPH
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3868](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3868.xpi) ("adjust testcases for #1162")

Install in Zotero by downloading [test build 5.1.72.3868](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3868.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Ah, you are using bibtex, I was testing with biblatex. I've added the bibtex test case -- please try 3868.

**Comment by wkjarosz** [comment]
Works now. Thanks!

**Comment by retorquere** [comment]
Cool, I'll put out a new release tonight.
