### ISSUE TITLE
Re-create Juris-M starter profile

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#1164]

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.25.6620](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.25.6620.xpi) ("5.2.25")

Install in Zotero by downloading [test build 5.2.25.6620](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.25.6620.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
