### ISSUE TITLE
Change the Output path in Automatic Export

### ISSUE THREAD

**Issue by Fenrihr** [retorquere/zotero-better-bibtex#1165]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

**Your question/suggestion:**

First, thank you very much for this awesome piece of software.

Now .... I am using Zotero in a cross-platform enviroment (a linux laptop and a windows PC) and i would like to use BibTeX Better in that way too. For that i was wondering if exits a way to change or to use `system variables` to manage the filepath of the `output file` in the` Automatic export`.

Thanks in advance for your help!

**Comment by retorquere** [comment]
I don't fully understand. How do you share data between those two? Is your datadir on a USB drive or somesuch?

**Comment by Fenrihr** [comment]
i sync the database folder with Mega.nz and in the Zotero `advance preferences` -> `files and folder`, i changed the default database folder to the sync folder.

**Comment by retorquere** [comment]
That excludes the `zotero.sqlite` file I hope? Syncing `zotero.sqlite` [will sooner or later corrupt your database](https://www.zotero.org/support/sync) (see the "Alternative Syncing Solutions" section).

**Comment by Fenrihr** [comment]
Thanks for the info but that was not my question

**Comment by retorquere** [comment]
You are right, but I felt it was important to point out.

As to your question, I'll think about it.

**Comment by retorquere** [comment]
What kind of system variables did you have in mind? I take it you have a base dir set up for your attachments so that they can be synced outside zotero. I could consider making auto-exports relative to that if it's set.

**Comment by retorquere** [comment]
Come to think of it, failing auto exports should just be ignored, so you could just set up one for each system. That wouldn't require any changes.

**Comment by Fenrihr** [comment]
> 
> 
> What kind of system variables did you have in mind? I take it you have a base dir set up for your attachments so that they can be synced outside zotero. I could consider making auto-exports relative to that if it's set.

I was thinking something the `Environment Variables` on windows, like:
``` bash
set BIB_MyColection="C:\Projects\MyProject\papers.bib"
```
or like system-wide variables on linux:
``` shell
export BIB_MyColection="/home/usuario/Projects/MyProject/papers.bib"
```
Then use `%BIB_MyColection%` in the `Output file` option.

> 
> 
> Come to think of it, failing auto exports should just be ignored, so you could just set up one for each system. That wouldn't require any changes.

JAJAJA!! That it's much simple then using system variables!!! I didn't know htat there wasn't any problem doing that.

**Comment by tyePhDCandy** [comment]
This helps.

No need to tweak an environment variable. I'll just set up two automatic export item for two computers, respectively.

**Comment by retorquere** [comment]
Do note that sharing the better-bibtex.sqlite file using cloud sync suffers the same risks as syncing the main zotero database. If it gets corrupted, you will have to delete it, but when you delete it, all keys except those that are pinned will be regenerated, and all auto-exports would be lost.

**Comment by tyePhDCandy** [comment]
Understood. Actually, my .sqlite file got corrupted once. Since then, I've been very careful.
