### ISSUE TITLE
Exporting one or more collections, not the full library

### ISSUE THREAD

**Issue by uroojain** [retorquere/zotero-better-bibtex#1167]
My library is too large, so export takes a lot of time. i wish i could only export one folder or collection instead of the full library. i do not see any way to accomplish this. Please help.

- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Report ID:

**Exporter used:**

**Expected behavior:**

**Actual behavior:**

**Comment by retorquere** [comment]
You just right-click the collection and export it.

**Comment by uroojain** [comment]
Thank you. I am so sorry for bothering you with an insignificant issue. Your response was very helpful.

**Comment by retorquere** [comment]
No problem
