### ISSUE TITLE
IEEE citation style: access date missing for web page

### ISSUE THREAD

**Issue by uroojain** [retorquere/zotero-better-bibtex#1169]
The IEEE citation style manual shows this style for a web page:

> [1] Emarketer.com, 'Social Networking Reaches Nearly One in Four Around the World', 2014. [Online]. Available: http://www.emarketer.com/Article/Social-Networking-Reaches-Nearly-One-Four-Around-World/1009976. [Accessed: 23- Jun- 2014].

Notice the access date at the end. How can I get this access date in my web page citations?

- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [ ] I have included the error-report ID here after restarting Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled), reproducing your problem, and selecting "Report Better BibTeX error" from the help menu

Report ID:

**Expected behavior:**

**Actual behavior:**

**Comment by retorquere** [comment]
I don't know - if you can tell me what field you need, I can tell you how it can be produced by bbt.

As an aside, if you're reporting a bug, you're not supposed to pick and choose from the checkbox list but to make sure you've cheched off all points. In this case, you're really just asking a question, which is fine, but in such cases, please choose the "question" template. It will have less checkboxes, won't have the actual/exoected part, and will label the issue appropriately. But if you're reporting a bug, please do complete all steps and also fill out the actual/expected part.

**Comment by retorquere** [comment]
How to get this generated in your bibliography also depends on whether you use bibtex or biblatex.

**Comment by retorquere** [comment]
If bibtex: [this](https://www.owenstephens.co.uk/blog/2010/03/28/add_accessed_date_to_ieeetran_bibtex_style.html) says you'd have to modify the bst.

**Comment by uroojain** [comment]
I have made changes to the bst file. i am using bibtex. but een though the exapmle works fine, i cannot see an accessdate in my doc. instead of access date coming up with web page entry, the bibtex compiler is now warning me that my book entries do not have urls. the trouble is with exporting urls from zotero through better bibtex to latex. if i say do not export urls, there are no warning, and no access date. the url is there. if i say export urls in a note field, there is a series of errors. if i say export urls in url field, it raises warnings for my book entries as they do not have urls.

**Comment by uroojain** [comment]
now i can export url in the note field. in the bib file url appears in "howpublished". the access date is not there. if i try exporting url in url field, all my book entries get warnings for no url.

**Comment by retorquere** [comment]
Please right-click the item you are trying to cite, and select "Report Better BibTeX Errors" from the "Better BibTeX" item in the popup menu, then post the debug ID here.

**Comment by uroojain** [comment]
i have done wat you asked me to and the ID is SZJAVVCZ-apse

**Comment by uroojain** [comment]
I am sorry for posting the issue as a bug and not a question. i am new to github, and i am having trouble understanding the forum. please accept my apologies. Thank you for the help that you constantly provide.
Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 11:33:23 am GMT+5, Emiliano Heyns <notifications@github.com> wrote:  
 
 
I don't know - if you can tell me what field you need, I can tell you how it can be produced by bbt.

As an aside, if you're reporting a bug, you're not supposed to pick and choose from the checkbox list but to make sure you've cheched off all points. In this case, you're really just asking a question, which is fine, but in such cases, please choose the "question" template. It will have less checkboxes, won't have the actual/exoected part, and will label the issue appropriately. But if you're reporting a bug, please do complete all steps and also fill out the actual/expected part.

**Comment by retorquere** [comment]
That's OK. If you have suggestions on how to clarify the instructions that would be most helpful.

With your settings (which are submitted as part of the debug log you sent) the item is exported as

```
@misc{NegativeTranscriptionRegulation,
  title = {Negative {{Transcription Regulation}} in {{Prokaryotes}} | {{Learn Science}} at {{Scitable}}},
  url = {https://www.nature.com/scitable/topicpage/negative-transcription-regulation-in-prokaryotes-1013},
  urldate = {2019-04-18}
}
```

Does your modified style expect something else?

As another aside, do you have the option of using biblatex? biblatex has much better support for url-related concerns.

**Comment by uroojain** [comment]
this export is fine, but the other book entries do not have urls and they are creating warnings.i tried both bibtex and biblatex. the problem persists. can the url be ignored for non-webpage entries?alternately, can urldate be exported in notes?
Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 2:36:34 pm GMT+5, Emiliano Heyns <notifications@github.com> wrote:  
 
 
That's OK. If you have suggestions on how to clarify the instructions that would be most helpful.

With your settings (which are submitted as part of the debug log you sent) the item is exported as
@misc{NegativeTranscriptionRegulation,
  title = {Negative {{Transcription Regulation}} in {{Prokaryotes}} | {{Learn Science}} at {{Scitable}}},
  url = {https://www.nature.com/scitable/topicpage/negative-transcription-regulation-in-prokaryotes-1013},
  urldate = {2019-04-18}
}

Does your modified style expect something else?

As another aside, do you have the option of using biblatex? biblatex has much better support for url-related concerns.

**Comment by uroojain** [comment]
Process started: bibtex.exe "PhD_thesis"




This is BibTeX, Version 0.99d (MiKTeX 2.9)

The top-level auxiliary file: PhD_thesis.aux

A level-1 auxiliary file: introduction.aux

A level-1 auxiliary file: lambdaswitch.aux

The style file: IEEEtran.bst

Database file #1: biblio.bib

-- IEEEtran.bst version 1.13 (2008/09/30) by Michael Shell.

-- http://www.michaelshell.org/tex/ieeetran/bibtex/

-- See the "IEEEtran_bst_HOWTO.pdf" manual for usage information.

Warning--there is url but no urldate in griffiths_modern_1999

Warning--there is url but no urldate in miko_i._essentials_2009

Warning--there is url but no urldate in bruce_alberts_molecular_2002

Warning--there is url but no urldate in geoffrey_cooper_cell_2000

Warning--there is url but no urldate in a._j._f._griffiths_introduction_2000


Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 2:41:51 pm GMT+5, Urooj Ainuddin <uroojain@yahoo.com> wrote:  
 
 this export is fine, but the other book entries do not have urls and they are creating warnings.i tried both bibtex and biblatex. the problem persists. can the url be ignored for non-webpage entries?alternately, can urldate be exported in notes?
Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 2:36:34 pm GMT+5, Emiliano Heyns <notifications@github.com> wrote:  
 
 
That's OK. If you have suggestions on how to clarify the instructions that would be most helpful.

With your settings (which are submitted as part of the debug log you sent) the item is exported as
@misc{NegativeTranscriptionRegulation,
  title = {Negative {{Transcription Regulation}} in {{Prokaryotes}} | {{Learn Science}} at {{Scitable}}},
  url = {https://www.nature.com/scitable/topicpage/negative-transcription-regulation-in-prokaryotes-1013},
  urldate = {2019-04-18}
}

Does your modified style expect something else?

As another aside, do you have the option of using biblatex? biblatex has much better support for url-related concerns.

**Comment by uroojain** [comment]
my dear friend, the warnings persist, i am now exporting urls in a url field and i am getting the access date and url for webpage citations. however, i am getting urls and access dates for journal articles as well, which is not desirable.
Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 2:42:48 pm GMT+5, Urooj Ainuddin <uroojain@yahoo.com> wrote:  
 
 
Process started: bibtex.exe "PhD_thesis"




This is BibTeX, Version 0.99d (MiKTeX 2.9)

The top-level auxiliary file: PhD_thesis.aux

A level-1 auxiliary file: introduction.aux

A level-1 auxiliary file: lambdaswitch.aux

The style file: IEEEtran.bst

Database file #1: biblio.bib

-- IEEEtran.bst version 1.13 (2008/09/30) by Michael Shell.

-- http://www.michaelshell.org/tex/ieeetran/bibtex/

-- See the "IEEEtran_bst_HOWTO.pdf" manual for usage information.

Warning--there is url but no urldate in griffiths_modern_1999

Warning--there is url but no urldate in miko_i._essentials_2009

Warning--there is url but no urldate in bruce_alberts_molecular_2002

Warning--there is url but no urldate in geoffrey_cooper_cell_2000

Warning--there is url but no urldate in a._j._f._griffiths_introduction_2000


Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 2:41:51 pm GMT+5, Urooj Ainuddin <uroojain@yahoo.com> wrote:  
 
 this export is fine, but the other book entries do not have urls and they are creating warnings.i tried both bibtex and biblatex. the problem persists. can the url be ignored for non-webpage entries?alternately, can urldate be exported in notes?
Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk 

    On Tuesday, 23 April 2019, 2:36:34 pm GMT+5, Emiliano Heyns <notifications@github.com> wrote:  
 
 
That's OK. If you have suggestions on how to clarify the instructions that would be most helpful.

With your settings (which are submitted as part of the debug log you sent) the item is exported as
@misc{NegativeTranscriptionRegulation,
  title = {Negative {{Transcription Regulation}} in {{Prokaryotes}} | {{Learn Science}} at {{Scitable}}},
  url = {https://www.nature.com/scitable/topicpage/negative-transcription-regulation-in-prokaryotes-1013},
  urldate = {2019-04-18}
}

Does your modified style expect something else?

As another aside, do you have the option of using biblatex? biblatex has much better support for url-related concerns.

**Comment by retorquere** [comment]
Sorry to bother you again, but if you're replying by email, can you trim out the message you're responding to? Otherwise the entire history of the conversation gets inserted into each github message. I've been editing them out to keep the discussion clearer.

I can't really help with bibtex compilation, sorry, it's just not my area of expertise. You can have the url ignored for non-webpage entries with a postscript (Advanced tab in BBT settings):

```
if (Translator.BetterBibTeX) {
  if (item.itemType !== 'webpage') this.remove('url')
}
```

**Comment by uroojain** [comment]
This did it. Thank you. I am exporting with url in url field, and the postscript ignores the url for all webpage entries.
Urooj Ainuddin
Assistant Professor & PhD ScholarComputer and Information Systems Engineering
NED University of Engg. and Tech.
Office #: 99261261-8 Ext: 2350Email: uroojain@neduet.edu.pk

**Comment by retorquere** [comment]
Super. Glad that worked for you.

**Comment by uroojain** [comment]
Final word:
Go to https://www.owenstephens.co.uk/blog/2010/03/28/add_accessed_date_to_ieeetran_bibtex_style.html and do as directed.
Set your exports such that urls are exported in the url field.
Add the postcript(Advanced tab in BBT settings):
if (Translator.BetterBibTeX) {
  if (item.itemType !== 'webpage') this.remove('url')
}
