### ISSUE TITLE
Cite keys synchronization

### ISSUE THREAD

**Issue by Emic37** [retorquere/zotero-better-bibtex#1170]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

**Your question/suggestion:**

Hi, 
I use Zotero and BBT on two different computers. I installed BBT on my two computers and it seems BBT recreates all cite keys on the second computer. And I'm not sure they are the same on the two Zotero installation. 

So, is there a way to synchronize cite keys between computers ? Maybe, is it possible to use the Zotero sync system ? Or perhaps, is there an other way ?

Thanks in advance and thank you for your hard work.

**Comment by retorquere** [comment]
The only way that currently works is to pin your citekeys. When Zotero gains a citekey field (which has been planned for a [long time](https://forums.zotero.org/discussion/15636/changes-to-fields-and-item-types-for-zotero-5-1)), they will sync as any other data. When pinned, they'll be put in the `extra` field, and that will sync; there are also a number of existing Zotero translators (currently `BibLaTeX`,  `BibTeX`, `CSL JSON` and `TEI`) which will recognize that format, and when Zotero gains the citekey field, Zotero will migrate it there.
