### ISSUE TITLE
single-word @strings sometimes wrapped in braces

### ISSUE THREAD

**Issue by wkjarosz** [retorquere/zotero-better-bibtex#1171]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Report ID: DHEYDG2U-euc

**Exporter used:** Better BibTeX

**Expected behavior:** I have "Assume single-word strings to be externally-defined @string vars" enabled in the Advanced tab. There are two issues I encountered with this.

1) @string identifiers are allowed to have a hyphen, but BBT seems to not interpret this as a "single-word". For instance, the @string egsr92-97 is not recognized as a single-word identifier, even though it is a valid @string identifier.

2) It seems this setting only applies to certain fields. Seems to work fine for book title and journal name, but if I have a single-word string in the "Series" field, this still gets wrapped in braces on export.

**Actual behavior:**

All valid @string identifiers should not be wrapped in braces on export in any item field, so that I could externally define @strings to have consistently written publishers, series, journal names, conference names, etc.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.72.3846](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3846.xpi) ("allow dash in bibtex @strings, enable for series")

Install in Zotero by downloading [test build 5.1.72.3846](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.72.3846.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 3846.

**Comment by wkjarosz** [comment]
Thanks. I've tested it out. It works for the series field now, but not other fields. For instance, I'd like to also use @strings to make publisher names consistent, so enabling this for all fields would be useful.

**Comment by retorquere** [comment]
I can add it to publisher, but I don't want to simply enable it for all fields, as I want to review its behavior on a field-by-field basis -- `publisher` for example is a literal-list field, Zotero does not have list support for `publisher`, so I need to look into what would be appropriate behavior.

**Comment by retorquere** [comment]
But do you want to merge this with #1162 before I make more changed in this branch?

**Comment by retorquere** [comment]
Closing because the discussion and code has been merged into #1162 .
