### ISSUE TITLE
Allow Calculated Year Within Citation Key Patterns

### ISSUE THREAD

**Issue by keramsey** [retorquere/zotero-better-bibtex#1175]
Hi,

I am able to modify the default citekey generation pattern to the following:
`[year]_[auth:lower]_[shorttitle3_3]`

What I would like to do is use the citekey field to sort citations within a web page bibliography search page so that the citations are ordered by year (descending) and then first author last name (ascending). If I could calculate the value of a custom field using `[year]` (e.g., {[year]-10000}, I could sort as desired using the following citekey pattern:
`jer[null:(year-10000)]_[auth:lower]_[shorttitle3_3]_[year]`

Example: 
first author = Wenjie Ji
title = Constraints on shrub cover and shrub–shrub competition in a U.S. southwest desert
[year] = 2019
[null:(year-10000)] = -7981
[auth:lower] = ji
[shorttitle3_3] = ContstraintsShrubCover
resulting citekey value = jer-7981_ji_ContstraintsShrubCover_2019

To demonstrate this, here is a listing of potential results sorted by citekey (ascending order):
jer-7981_rossi_VegetationTerrainDrivers_2019
jer-7982_pierce_PlantplantInteractionsGrasslandtoshrubland_2018
jer-7982_pierce_PlayaWetlandsEffectsDryland_2018
jer-7983_petrie_RegionalGrasslandProductivity_2017

This would allow me to sort on citekey (ascending) to effectively achieve secondary or tertiary sorting which is the most commonly used sort order by the scientists and educators our website serves.

I hope this makes sense.  This seems like a useful feature enhancement to maintaining fixed citekey values.

Ken

**Comment by retorquere** [comment]
This seems more properly handled by reporting tools than by citekey manipulation (it's also not really a bug)

**Comment by keramsey** [comment]
Hi,

Sorry, I did not mean to tag this as a bug but as a feature request. I agree that a reporting tool would work assuming there is a tool that supports secondary sorting which I cannot find. I came across BBT and thought this would be an easy way to get the listing sorted properly,

I thought this might be a fairly easy tweak, but I understand that my assumption may not be correct. Thanks for considering my request. 

Ken

**Comment by retorquere** [comment]
No problem. What operatingsystem do you use?

**Comment by retorquere** [comment]
And what website? Maybe there's a simple way to just do the secondary sort on the site itself.

**Comment by keramsey** [comment]
Our current website is running on Ubuntu 16.04 that hosts Drupal 7 based websites. We have used the Drupal biblio module to provide searchable (including advanced search) bibliographies for research collaboration websites for the last 8 years or so. Unfortunately, the biblio module will not be further developed for Drupal 8. There is a bibcite module for Drupal 8 that would work for us if there was a way to sort by citeky as I described. This is to overcome a limitation or bug in Drupal 8 core related to the core Views module that created apparent duplicate search results when the author field is added to the sort order. Basically, adding the sort order field (author) to a view results in the author table being inner joined which causes the duplicate listings in the view's search result listing. I can sort by citekey in Drupal 8 bibcite, but the sort order is by date uploaded (descending order).

I have had no success finding an alternative solution outside of Drupal. We are now maintaining our bibliographic databases in Zotero and plan to periodically export the citations to the reporting solution. Unfortunately, I have not found a dynamic bibliographic reporting tool that would provide the capability of an advanced search interface that sorts by year (desc), first author last name (asc). All of the reporting tools I have found that are capable of advanced search functions do not support secondary sorting.

I am certainly open to suggestions.

**Comment by retorquere** [comment]
From what I understand from the description of biblio and bibcite, they pull from the Zotero API? That would not include the BBT citekeys in any case. I'm sorry, I thought you were looking for a desktop solution.

If you're OK with manual exports, I wrote an exporter a while ago that exports a CSV format that's seemed to help with seektable -- @richardkaplan should be able to tell you more as he's a heavy user of the service. Free plans seem to be available, and you can embed it in sites using iframes. From what I've been told, it's very flexible in its filtering and sorting capabilities, but I don't use it myself.

**Comment by richardkaplan** [comment]
If you can share a bit more of the goals of your project, I would be glad to give you some input on whether the tools @retorquere has suggested may work as well as some sample reports.

**Comment by keramsey** [comment]
No, only in Drupal 7 (end of life Nov. 2021) is there a biblio_zotero module that interacts with the Zotero API to keep biblio citations synchronized from Zotero using Drupal feeds module. I was able to create citekey values using BBT that almost meet my needs to sort by citekey for Drupal 8. There should be a way to setup the Drupal 8 feeds tamper module to reformat the citekey from Zotero (thanks BBT) on import using the logic I described. It would be simpler to implement directly using a Zotero Web API client if BBT supported the function I described and be more widely useful, but I realize that modifying code for a fringe use case is not necessarily feasible or worth the effort.

1. Here is the main biblio search interface (I have to fix the secondary sorting again within biblio following recent update to biblio):
https://jornada.nmsu.edu/biblio

2. Here is a basic search interface to biblio using a view:
https://jornada.nmsu.edu/lter/biblio

3. Here is the page I have been working with the Zotero API using JavaScript (thanks to Timothy Whittaker, BLE LTER):
https://jornada.nmsu.edu/lter/publications

Our scientists prefer the biblio advanced search interface (2. above) so that is what I am trying to emulate,

**Comment by retorquere** [comment]
> It would be simpler to implement directly using a Zotero Web API client if BBT supported the function I described

BBT citekeys are not available in the Zotero Web API.

If you don't care about how things look in the Zotero client, and you're OK with exporting this manually<sup>1</sup> you can actually change the citation key to anything you want (although I don't generally advice doing so) by changing `item.citekey` in a postscript by e.g. prepending the inverse year that you mention using something like what's below -- please *make sure* to end the postscript with `return false` otherwise the changes made will be cached and you don't want this in this case.

```
if (Translator.BetterTeX && item.date) {
  const date = Zotero.Utilities.strToDate(item.date)
  if (typeof date.year === 'number') item.citekey = `yer-${10000 - date.year}_${item.citekey}`
}
return false
```

These modified keys do not show up in the Zotero client, and if you forget the `return false` at the end you will get inconsistent stuff out of the export, which is fixable by clearing the cache. Note that if you ever do get inconsistent things out of the exports doing this, the first thing I will ask you is to reset the cache -- this all is only accidentally possible because I can't prevent it, it's not something I actively advocate doing, the caching system is intricate enough as it is.

-----
<sup>1</sup> although you *could* technically do this using a [pull export](https://retorque.re/zotero-better-bibtex/push-and-pull/#pull-export) and something like [localtunnel](https://localtunnel.github.io/www/), but I've not used this in production and I can't vouch for the potential security risks of opening up a PC this way.

**Comment by retorquere** [comment]
Adding calculating facilities to the BBT key generator would either be wholly specialized to this case (and it does seem like a fringe case), or would get quite involved as I'd essentially be creating a general computing facility inside the already overly complex key-pattern-parser. In the early days of BBT I would probably have jumped at this but I have become more conservative about changes to BBT behavior, and with the upcoming Zotero 5.1 port, more complexity is not what I should add without a strong use-case with fairly wide appeal.

**Comment by keramsey** [comment]
Thanks for the information. I had overlooked that modifying the citekey values outside of Zotero would effectively make citekey's useless for updates (vs. drop and re-import) from Zotero.

I had hoped to use permanent citekey values in Zotero to maintain synchronization between Zotero and Drupal by using export files from Zotero using a style (custom?) that included citekey. From what I understand you are saying is that this is not possible. Is that correct?

I really appreciate the information and want to thank you again for considering my feature request. You are welcome to close this issue.

**Comment by retorquere** [comment]
If you pin the keys, you can have whatever you want in them, and they'll work everywhere. But for your case, you'd have to set them manually.

You can use BBT exports or BBT-CSL exports if you want the citekeys. If the key is pinned, a few standard zotero exporters will also export the citekey.

**Comment by retorquere** [comment]
Oh wait, when you say style, you wanted to export formatted references, including a citekey?

I'm not entirely clear what you want to achieve, but I'm sure something can be done.
