### ISSUE TITLE
Inconsistent HTML -> LaTeX conversion

### ISSUE THREAD

**Issue by awbirdsall** [retorquere/zotero-better-bibtex#1176]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Report ID: TT3NAPUJ-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** I think that if the title in Zotero has HTML formatting like `<sub>`...`</sub>` it should be converted to LaTeX in the exported .bib file.

Example title 1: "`Spectroscopic and laser characteristics of Ti:Al<sub>2</sub>O<sub>3</sub>`"

Example title 2: "`Vibrational energy transfer in OH X <sup>2</sup>Π<sub><i>i</i></sub>, <i>v</i>=2 and 1`"

**Actual behavior:** For some references the output passes through the HTML tags, but for other references it does a fine job at converting to LaTeX.

Example 1 output: `title = {Spectroscopic and laser characteristics of Ti:Al<sub>2</sub>O<sub>3</sub>}`

Example 2 output: `title = {Vibrational Energy Transfer in {{OH X}} {\textsuperscript{2}}{{Π}}{\textsubscript{{\emph{i}}}}, {\emph{V}}=2 and 1}`

 I'm not sure what explains the different behavior. Am I missing something, or is this a bug? Thanks!

**Comment by retorquere** [comment]
Example 1 has tag `#LaTeX` which puts bbt in raw latex export mode - with that tag on an item, bbt assumes you have raw latex in names and titles and won't escape anything.

**Comment by awbirdsall** [comment]
Thanks, that fixes it. I didn't know about that behavior.

Out of curiosity, do you happen to know how the `#LaTeX` tag gets added? Does Zotero decide to add it automatically when some references are imported?

**Comment by retorquere** [comment]
`#LaTeX` is BBT specific, it's not something Zotero would do. At one point BBT could be configured (off by default) to always add that tag when importing bibtex, but that was a long time ago, and to turn it on you'd have to go into hidden preferences - it's not something you could do by accident.

In other words, I have no idea how that tag was added to that reference.

**Comment by awbirdsall** [comment]
Huh, interesting. But thanks again, really glad I learned about the tag. Feel free to close.
