### ISSUE TITLE
Question [post-script] modify referenceType if a tag is present

### ISSUE THREAD

**Issue by ujubib** [retorquere/zotero-better-bibtex#1177]
Hello, 
i wish i could change the type  of a reference on bibtex export if a tag (among others) is set to this reference. 
I try this :

```javascript

if ('Compte-rendu' in this.item.tags) {
  this.referencetype = 'note'
}
````
my problem is javascript and how to test one tag in a list of tags (your extension and the post-script feature are wonderful).

**Comment by retorquere** [comment]
You were pretty close already:

```
if (Translator.BetterTeX && item.tags && item.tags.includes('Compte-rendu')) {
  this.referencetype = 'note'
}
```

**Comment by ujubib** [comment]
Thank you very much :)
it's perfect !
