### ISSUE TITLE
CSL JSON and CSL YAML exporters: also enable deterministic ordering

### ISSUE THREAD

**Issue by jpcirrus** [retorquere/zotero-better-bibtex#1178]
- [x] I have verified in the Zotero addons screen that I have the latest release of [BBT](https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

**Report ID:**
NNWWEVRY-apse

**Exporters used:**
`Better CSL JSON` and `Better CSL YAML`

**Configuration option:**
Advanced option `Deterministically order references and fields; primarily for version control` is enabled.

**Expected behaviour:**
Exported JSON and YAML bibliographies are ordered as occurs for `Better BibLaTeX` and `Better BibTeX`.

**Actual behavior:**
Exported JSON and YAML bibliographies are *not* so ordered.

**Comment by retorquere** [comment]
Please also include a debug log (see last checkbox)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.76.3929](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.76.3929.xpi) ("seems like CSL objects are already sorted?")

Install in Zotero by downloading [test build 5.1.76.3929](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.76.3929.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jpcirrus** [comment]
Sorry about that, wasn't sure it was a bug or a feature request. Report ID addd to first post. Will now test your test build and get back.

**Comment by jpcirrus** [comment]
Thank you. I confirm that ` test build 5.1.76.3929` works correctly for both JSON and YAML export formats. However, I have some observations that would make the output closer to what the bibtex and biblatex export formats currently provide, and which I believe would be visually easier to discern.

1. The references are not sorted on the `id` key as happens with both bibtex and biblatex export formats.
2. Within each reference, the upper case keys (e.g., DOI, URL) are sorted before the lower case keys (on my machine with `LC_COLLATE="C"`. Not sure if this would change with a different `LC_COLLATE` value). Perhaps the sorting should be case insensitive to make it easier to visually locate a key within a reference without having to think about its case.
3. I think it would be helpful to have the first key in each reference key be the `id` key, followed by all the other sorted keys, as occurs with the bibtex and biblatex export formats, to allow easier reference location.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.76.3950](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.76.3950.xpi) ("adjust testcases for #1178")

Install in Zotero by downloading [test build 5.1.76.3950](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.76.3950.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
try 3950

**Comment by jpcirrus** [comment]
Thank you. I confirm `test build 5.1.76.3950` resolves this issue, as well as #1179.

**Comment by retorquere** [comment]
A new release has been scheduled to include this.
