### ISSUE TITLE
Citation keys format capitalization 

### ISSUE THREAD

**Issue by today-is-a-good-day** [retorquere/zotero-better-bibtex#1182]
*Please verify **all** of the below before submitting*:

1. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
2. you are posting a single bug or feature request
3. you have included a descriptive subject of the problem
4. you are available for follow-up questions and testing
5. you have included an error-report ID here generated by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:**
99EE8U39-euc

**Expected behavior:**
When the citation keys format is set to `[auth:lower][year][shorttitle1_0]`, shorttitle should not be capitalized. 

**Actual behavior:**
When the citation keys format is set to `[auth:lower][year][shorttitle1_0]`, shorttitle is capitalized.

**Comment by retorquere** [comment]
From what I can see from the log it's generating `olaru2015Methods` from `Methods matter: testing competing models for designing short-scale big-five assessments`; it's not so much capitalizing `shorttitle` as it is not "un-capitalizing" shorttitle. Try `[auth:lower][year][shorttitle1_0:lower]`.

**Comment by retorquere** [comment]
(`_0` is the default for shorttitle BTW so you'll get the same results with just `shorttitle1`)

**Comment by today-is-a-good-day** [comment]
`[auth:lower][year][shorttitle1_0:lower]` works! 

I found `first M (default: 0) capitalized` in the documentation about shorttittle confusing. because if I replace M with 0, it reads `first 0 capitalized` and to me that sounds like no capitalization. Even more confusing, I get the same result with M = 0 and M = 1.

**Comment by retorquere** [comment]
It should be read as "the first M have capitalization applied". With `0` and `1` the result is the same in your case as the first word is already capitalized; "do not apply capitalization" and "apply capitalization" have the same output here. `shorttitle2_0` and `shorttitle2_1` would yield different results for your sample as the 2nd word is not already capitalized.

**Comment by retorquere** [comment]
I've updated the docs to reflect that it's "apply" rather than "ensure" capitalization.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.80.3997](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.80.3997.xpi) ("update docs for #1182")

Install in Zotero by downloading [test build 5.1.80.3997](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.80.3997.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by today-is-a-good-day** [comment]
Great, thanks for the help!

**Comment by retorquere** [comment]
You're very welcome.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.80.3998](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.80.3998.xpi) ("update docs for #1182")

Install in Zotero by downloading [test build 5.1.80.3998](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.80.3998.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
