### ISSUE TITLE
Automatic export and (possibly) caching leads to changes not being synced to export.

### ISSUE THREAD

**Issue by fkroener** [retorquere/zotero-better-bibtex#1183]
When making changes to an existing citation's author's first name (M. -> Michael for consistency for example), these changes don't ever appear in the automatically exported bib file. 

I tried doing slight changes in the export settings to re-trigger the cache (unticking/ticking "Export unicode as plain-text..."), deleting the file on disk and even removing the automatic export and creating it again. The result is always "M." for one and "Michael" for the other citation.

I can't rule out user error though, and I think in the past I managed to overcome this bug somehow - it just keeps coming back.

Any help would be highly appreciated.

**Comment by retorquere** [comment]
From the "Export bug/enhancement" issue template:

> 5. you have included an error-report ID here generated by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

> The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

What should I put in the template to make it really, really clear that *I am effectively blind* without such a log? I *really* need the problem to reproduced with a log before I can do anything.

**Comment by fkroener** [comment]
Sure, there you go: 5SFLNYY9-euc

As for your template: I didn't get any template shown in the editor, but this might be user error again or overzealous umatrix blocking. Please forgive me.

**Comment by retorquere** [comment]
When you clicked `New issue`, you did not get the screen below? What path did you take to get to the issue submission?
<img width="887" alt="categories" src="https://user-images.githubusercontent.com/132108/57758827-e1933a00-76f8-11e9-9d4a-896036cb01e3.png">

Thanks for the log, I'll take a look.

**Comment by retorquere** [comment]
I don't see indications of an auto-export being triggered in the log. Can you `Restart with debugging enabled` from the `Help` menu, trigger an auto-export, then send the log?

**Comment by fkroener** [comment]
Hm, I'm actually not quite sure. Trying again now I clearly get that screen. Maybe this happened because I wasn't logged in when trying to create the issue? 

Or I blatantly ignored all these options and just clicked "Open a regular issue". Though I find that unlikely.

**Comment by retorquere** [comment]
You actually may have clicked that link; all of the options above attach a label to the issue, and this issue doesn't have one. In any case, I can't remove that text, so there's nothing more to be done there.

**Comment by fkroener** [comment]
KK9NNYJI-euc

There you go, I changed another author's first name (citation not included) in the meantime, removed the auto export and added it back. Apparently editing the author yet again didn't trigger any export.

**Comment by fkroener** [comment]
> 
> 
> You actually may have clicked that link; all of the options above attach a label to the issue, and this issue doesn't have one. In any case, I can't remove that text, so there's nothing more to be done there.

I just tested it again: this happened due to not being logged in when starting the "New issue" workflow. I really didn't get that screen.

**Comment by retorquere** [comment]
Was the title of the item you changed to trigger the auto-export `Individual autonomy in work teams: The role of team autonomy, self-efficacy, and social support`?

**Comment by fkroener** [comment]
Yes.

**Comment by retorquere** [comment]
And this was also the reference you expected to see changed in the output? I don't see this reference in the debug log, can you right-click the reference you had expected to see a change for in the output bib, and give me details on what you actually see output for that reference vs what you had expected?

**Comment by fkroener** [comment]
Those two Frese citations I had selected, weren't they part of the export?

In Zotero's interface I see:
Frese, Michael for both

In the .bib file I have 

author = {Frese, Michael},                                                                                                                                                                                                   author = {Frese, M.},

**Comment by retorquere** [comment]
They are, but I'm not seeing any changes being made to those two items in `KK9NNYJI`; I'm only seeing a change being made to the reference with title `Individual autonomy in work teams: The role of team autonomy, self-efficacy, and social support?`.

**Comment by fkroener** [comment]
Right. That change was only done in the hope of triggering an export (which didn't happen I think).

The issue should still be visible, right? Previous changes to author's first name not being exported, apparently neither when changes happen nor upon restart or removal of the automatic export.

**Comment by fkroener** [comment]
Here's another log with edits to Frese: 6CFLPPEM-euc where this bug doesn't appear to happen.
Let me try from windows again. :-)

**Comment by fkroener** [comment]
No idea can't reproduce now.

**Comment by retorquere** [comment]
In `KK9NNYJI` you did trigger an export, but I can't see whether the appropriate cache was touched after you made the change to `Frese`. BBT has several caches and they aren't all invalidated at the same time; one of the caches keeps a copy of the items as they sit in Zotero, and that cache only gets invalidated when the item changes. I can see in the log that the Frese reference is being generated anew, but the source item it uses for that was already cached; I don't know what's in that cache (you can send along your cache by ticking "Send cache" in the error submission).

In `KK9NNYJI` I can see the author for `Social Support as a Moderator of the Relationship Between Work Stressors and Psychological Dysfunctioning: A Longitudinal Study With Objective Measures` was `Michael Frese`, but that came from BBTs item cache. If that cache was not appropriately invalidated when you changed that to `M`, that would explain what you're seeing, but I can't tell from `KK9NNYJI` whether that was the case.

In `6CFLPPEM` I can see the Frese reference changing but the caches seem to get invalidated as expected. So we don't yet have your initial problem reproducible.

**Comment by retorquere** [comment]
So it's no longer reproducible?

**Comment by fkroener** [comment]
Haven't had much time to look into it yet.

Maybe information about the particular workflow are of interest:
Eiting of the citation was done on a different than the exporting system system using Zotero sync. Maybe this doesn't properly trigger cache invalidations.

**Comment by retorquere** [comment]
It should not make any difference. The items that are synced in are saved in the normal Zotero mechanisms, I can't distinguish user-edits and syncs even if I wanted to.

**Comment by retorquere** [comment]
If you see it happening again, a comment on this issue will automatically reopen it.
