### ISSUE TITLE
No brace protection when suppressTitleCase set to true

### ISSUE THREAD

**Issue by gimber** [retorquere/zotero-better-bibtex#1188]
**Report ID:** 8AQE3AZ7-euc (suppressTitleCase=true); 436LX66C-euc (suppressTitleCase=false)

**Exporter used:** BibTeX

**Expected behavior:** Words that are capitalized in Zotero entry titles are always brace protected on BibTeX export, even if suppressTitleCase is set to true:

> "BBT assumes that if a word has at least one capital letter (subject to some rather complex exceptions) you meant it to be there, and you want BibTeX to leave it alone no matter what. To do that, it wraps those (strings of) words in those double braces. [...] Also, if you don’t generally use Zotero for generating bibliographies but just for BibTeX reference management, you can turn on the hidden preference extensions.zotero.translators.better-bibtex.suppressTitleCase to keep BBT from applying title-casing, but take note that if you do this, the bibliographies you get from Zotero and the bibliograhies you get through Bib(La)TeX will differ, and you can’t complain about this. Brace protection (see below) cannot be turned off." (From the [FAQ](https://retorque.re/zotero-better-bibtex/faq/).)

**Actual behavior:** With suppressTitleCase set to true, entry titles that are capitalized in Zotero are **not** brace protected in the [BibTeX output](https://github.com/retorquere/zotero-better-bibtex/files/3182228/BBT.suppressTitleCase.true.bib.txt). When suppressTitleCase is set to false, brace protection [works as expected](https://github.com/retorquere/zotero-better-bibtex/files/3182227/BBT.suppressTitleCase.false.bib.txt). In both cases, suppressBraceProtection is set to false.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.81.4028](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.81.4028.xpi) ("fixes #1188")

Install in Zotero by downloading [test build 5.1.81.4028](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.81.4028.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 4028 a go.

**Comment by gimber** [comment]
4028 works exactly as expected. Thanks very much! Very impressed to see same-day bug fixes on a one-person volunteer project - I've hit the tip jar with a small token of gratitude.

**Comment by retorquere** [comment]
That's very much appreciated, and thanks for reporting the issue. A new release has been scheduled and should be out in a few minutes.
