### ISSUE TITLE
First author ending with macro (e.g. \ss) omits space before et al.

### ISSUE THREAD

**Issue by zsteinmetz** [retorquere/zotero-better-bibtex#1189]
I have the following reference item in my collection:

Maaß, S., Daphi, D., Lehmann, A., Rillig, M. C. (2017): Transport of microplastics by two collembolan species. Environmental Pollution 225, 456–459.

**Report ID:** P5LB388D-euc

**Exporter used:** Better BibTeX (v.5.1.81 on Zotero 5.0.66)

**Actual behavior:** The BibTeX export gives the following output:

>@article{MaassTransport2017,
  title = {Transport of Microplastics by Two Collembolan Species},
  volume = {225},
  issn = {0269-7491},
  number = {Supplement C},
  journal = {Environmental Pollution},
  doi = {10.1016/j.envpol.2017.03.009},
  author = {Maa\ss, Stefanie and Daphi, Daniel and Lehmann, Anika and Rillig, Matthias C.},
  month = jun,
  year = {2017},
  keywords = {soil,transport,Pollution,Microplastics,Soil,Transport,Collembolans,collembolans},
  pages = {456-459}
}

As a consequence, in-text citing results in **Maaßet al., 2017**

**Expected behavior:** With parentheses wrapped around \ss, we get the space back again.

**Comment by retorquere** [comment]
@nickbart: I really didn't expect this. I can look at a workaround, but I would have expected the bibtex parser to understand the name ends at the comma and would have done the necessary to prevent this.

The easiest way out of this is just to wrap nameparts, but that seems rather ugly:

```
author = {{Maa\ss}, {Stefanie} and {Daphi}, {Daniel} and {Lehmann}, {Anika} and {Rillig}, {Matthias C.}},
```

and I don't know what other side effects it would have.

Adding just the `{\ss}` is technically possible but it'd mean that ßß would come out as `{\ss}{\ss}`; currrently, BBT internally outputs `\ss{}\ss{}` and cleans up superfluous `{}`s when it sees it is followed by a punctuation mark, leading to much leaner TeX code.

**Comment by njbart** [comment]
Well, one might have guessed that bibtex would wrap names or name parts into something somehow during processing, but apparently that’s not the case.

In any case, this problem only seems to occur when using bibtex together with an author-date style such as natbib. (biblatex does not seem to be affected.)

For bibtex and, specifically, the purposes of the `alpha` bibliography style, Patashnik states, “you must place the entire accented character in braces” (e.g. `{\"o}`), and “Furthermore these braces must not themselves be enclosed in braces“ ([1], p. 4, see also p. 15). (The latter means that wrapping nameparts might not be a good idea.)

[1] Patashnik, Oren. 1988. ‘BibTeXing’. http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf.

**Comment by retorquere** [comment]
Well, damn. It's an easy enough change to make but that's going to also affect the output of Better BibLaTeX; it's fairly easy to lean up superfluous `{}` from `\ss{}`, but a ton harder to clean up superfluous braces from `{\ss}`. I will have to think about this, but in any case, thanks for the insight -- the documentation seems clear-cut on this one.

Double damn, this also means I will have to re-code all my test cases.

**Comment by retorquere** [comment]
What about something like `\\.{C}`, `\\r{U}` and `\\k{I}`?

**Comment by njbart** [comment]
None of the first three (at least not in the context at hand, i.e., if occurring at the end of a last name that ends up right before an “et al.” in an in-text citation); in my setup, the last one (`\k{I}`) throws an error. 

If you wish to try out others, here’s my `test.tex` document:

~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{natbib}
\bibliographystyle{chicago}
%\bibliographystyle{apalike}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{MaassTransport2017,
title = {Transport of Microplastics by Two Collembolan Species},
volume = {225},
issn = {0269-7491},
number = {Supplement C},
journal = {Environmental Pollution},
doi = {10.1016/j.envpol.2017.03.009},
author = {Maa\ss, Stefanie and Daphi, Daniel and Lehmann, Anika and Rillig, Matthias C.},
month = jun,
year = {2017},
pages = {456-459}
}
\end{filecontents}

\begin{document}

\cite{MaassTransport2017}

\bibliography{\jobname.bib}

\end{document}

INVOCATION:
rm test.bib; pdflatex test; bibtex test; pdflatex test; pdflatex test
~~~

**Comment by retorquere** [comment]
I can't sensibly distinguish between where the character replacement happens - end-of-name is not a context I have at the point of translation. I apply the same translation everywhere.

**Comment by njbart** [comment]
Well, my comment was less a suggestion of what you should implement and more a disclaimer about the limitations of my testing. If you want to fix both the problem reported here and the (AFAICT as of yet unreported) problem of getting correct labels when using the bibtex “alpha” style (e.g., “Göd31”, all relevant accented character code will have to be wrapped in braces anyway.

In case you wish to test the behaviour of accented chars in names when using the bibtex “alpha” style, just comment out the `natbib` line and use `\bibliographystyle{alpha}` instead of `\bibliographystyle{chicago}`.

FWIW, the issue reported in the original post above can also be fixed on the bibtex side by inserting `{}` in front of both occurrences of ` et~al.` in `FUNCTION {format.lab.names}` in `apalike.bst`.

**Comment by retorquere** [comment]
But if I'm reading BibTeXing right in the part you pointed to, things like `\^I`, `\.{C}`, `\r{U}` and `\k{I}` would need braces to be counted as a single character, right?

**Comment by retorquere** [comment]
From a little experimenting, it looks like it must become `{\^I}`, `{\.C}`, `{\r{U}}`.

I see the same error with `\k{I}`; I got that mapping from https://www.w3.org/2003/entities/2007xml/unicode.xml. Does `\k` have any meaning in TeX at all, or is it just this particular application that yields errors?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.82.4033](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.82.4033.xpi) ("fixes #1189")

Install in Zotero by downloading [test build 5.1.82.4033](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.82.4033.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 4033

**Comment by njbart** [comment]
> But if I'm reading BibTeXing right in the part you pointed to, things like `\^I`, `\.{C}`, `\r{U}` and `\k{I}` would need braces to be counted as a single character, right?

Right. My initial testing was focused on the OP’s problem but, yes, for the bibtex alpha style’s labels to come out right, these braces would all seem to be required.

As to `\k`, this is a problem with font encoding and pdflatex. Fix: just add the line `\usepackage[T1]{fontenc}` to the latex document’s preamble. (When using xelatex or lualatex, the TeX engines I’m more familiar with these days, this isn’t necessary.)

**Comment by retorquere** [comment]
Cool. Is `\kI` supposed to work, or are the braces always required?

**Comment by njbart** [comment]
The latter.

**Comment by retorquere** [comment]
Same for `\r` I take it?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.82.4037](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.82.4037.xpi) ("wrap \\\\k{} and \\\\r{} for bibtex")

Install in Zotero by downloading [test build 5.1.82.4037](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.82.4037.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
@zsteinmetz can you give 4037 a go?

**Comment by retorquere** [comment]
I'm going to assume this is fixed.

**Comment by zsteinmetz** [comment]
Sorry for the late reply, @retorquere. Works perfectly now. Thank you!

**Comment by retorquere** [comment]
You can't win from label-gun 😄. I have it set up so that comments on closed issues automatically reopen so I don't miss anything, and so that only I can close issues so I can guarantee any changes are actually merged into a new release. The new release has these changes.
