### ISSUE TITLE
Getting all caps

### ISSUE THREAD

**Issue by simonlindgren** [retorquere/zotero-better-bibtex#1190]
I am using BBT (5.1.83) in Zotero (5.0.66) with zotpick-pandoc.applescript. My citation key format in BBT is "[auth:lower][year]". But, still, zotpick outputs my references in uppercase, as in [NAME2013B]. Has something gone bad with recent Zotero updates, or am I doing something wrong?

**Comment by retorquere** [comment]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
3. you are posting a single bug or feature request
4. you have included a descriptive subject of the problem
5. you are available for follow-up questions and testing
6. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Comment by retorquere** [comment]
If you click http://localhost:23119/better-bibtex/cayw?format=pandoc and pick that reference, what do you see in your browser?

**Comment by simonlindgren** [comment]
If I do the localhost:23119 thing, I get the right (lowercase) version of the reference. But if I use the zotpick applescript from https://github.com/davepwsmith/zotpick-applescript to insert in any editor, it gets capitalised.

**Comment by retorquere** [comment]
BBTs activity ends with what ends up in your browser. Where do you see the uppercased version?

**Comment by simonlindgren** [comment]
Well, that would then be after BBTs activity ends, as the uppercased version is what comes out  if I use the zotpick applescript from https://github.com/davepwsmith/zotpick-applescript to insert in any editor.

**Comment by simonlindgren** [comment]
These are the contents of the script that ends up with BBTs input coming out as all caps:

`tell application "System Events"
	try
		set appName to (the name of every process whose frontmost is true) as string
	on error errMsg
		display alert "Problem" message "Could not get the name of the frontmost application."
		error number -128
	end try
end tell
set zotRunning to do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe=probe' 2>/dev/null; exit 0"
if zotRunning is "" then
	display alert "Zotero not running" message "This script will not work unless Zotero is running. Please launch Zotero and try again"
	tell application appName
		activate
	end tell
	error number -128
else if zotRunning is "No endpoint found" then
	display alert "Better BibTeX not installed" message "This script will not work unless Better BibTeX is installed. Please make sure that Better BibTeX is installed in the running instance of Zotero"
	tell application appName
		activate
	end tell
	error number -128
else if zotRunning is "ready" then
	set theReference to do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?format=pandoc' 2>/dev/null; exit 0"
	try
		repeat until application appName is frontmost
			tell application appName to activate
		end repeat
	on error errMsg
		display alert errMsg
	end try
	tell application "System Events"
		try
			keystroke theReference
		on error errMsg
			display alert errMsg
		end try
	end tell
end if
`

**Comment by retorquere** [comment]
https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-pandoc.applescript just [takes whatever you see there in your browser](https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-pandoc.applescript#L23) and [emulates typing it in whatever app is the foreground app](https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-pandoc.applescript#L33). I don't know exactly what happens during that typing.

**Comment by simonlindgren** [comment]
I see. It is very odd, as this used to work perfectly before, but not any more.

I have tried inserting in several different editors, so it is not about that either.

Super annoying!

**Comment by retorquere** [comment]
When I run this in Script Editor, I get it pasted into Script Editor without the capitalization. There must be something running on your system that interferes.

**Comment by simonlindgren** [comment]
I've got it! When setting up a new mac (being Swedish as I am) there is the option to set either "Swedish" or "Swedish - Pro" as your input source. I never really understood the difference, so sometimes when setting up a new system I choose one, and sometimes the other. I turns out that if it was the "Pro" setting which caused this. Using basic "Swedish" as input source solved it!

**Comment by retorquere** [comment]
Professional Swedes shout all the time?

**Comment by simonlindgren** [comment]
Seems like it :)

**Comment by retorquere** [comment]
The `B` at the end is a dead giveaway BTW. That's the disambiguation postfix and BBT never under any circumstance capitalizes that -- you can't make it if you wanted to.

**Comment by simonlindgren** [comment]
Realized now, that it wasn't the Swedish/Swedish Pro thing. The error went away after switching the input source. When switching back to Pro it still works.
