### ISSUE TITLE
question: how to show new entries inside zotero from externally updated .bib file

### ISSUE THREAD

**Issue by kirk86** [retorquere/zotero-better-bibtex#1193]
Hi, how's it going?
I was wondering if you could clarify sth for me plz.
Is there any possibility to update an exported .bib file by dumping let's say a new .bib entry and have that show up inside zotero?

I was looking at the options and there's this `BibTeX AUX scanner` and I was wondering if that would do the trick or if there's any hidden options in the settings?

Thanks!

**Comment by retorquere** [comment]
You mean import the bib file back in and update existing Zotero references that way? No, that's not possible -- I can't see whether the items in the bib file have changed or not. The closest you'll get is importing the file and using Zotero's duplicate merger.

The AUX scanner can import items which have a key BBT doesn't know about, but it skips items whose key already exists.

**Comment by kirk86** [comment]
> The AUX scanner can import items which have a key BBT doesn't know about, but it skips items whose key already exists.

That might work because I was thinking sometimes it's easier to just append a new bibtex entry in the .bib file than just importing it through zotero the standard way but have that picked up by zotero for syncing purposes.
