### ISSUE TITLE
suppressBraceProtection does not work for BibTeX export (non-English items)

### ISSUE THREAD

**Issue by alekhe** [retorquere/zotero-better-bibtex#1194]
**Report ID:** ZAH9TIWS-euc

**Exporter used:** Better BibTeX

**Expected behavior:** No double braces in `title` and `series` fields

**Actual behavior:** Double braces in `title` and `series` fields.

Both `suppressBraceProtection` and `suppressTitleCase` are set to `true`. When I use Better BibLaTeX export, I get the expected behavior, while with Better BibTeX I do not. The item’s language is not English. If I remove the language field, i.e. make it English (which is by default), then the double braces are suppressed in BibTeX export.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.84.4056](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.84.4056.xpi) ("fixes #1194")

Install in Zotero by downloading [test build 5.1.84.4056](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.84.4056.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4056?

**Comment by alekhe** [comment]
It works. Thank you!

**Comment by alekhe** [comment]
Found some differences between BibTeX and BibLaTeX exports with `suppressBraceProtection` set to `false`:
`title`, `series`: BibLaTeX — single braces, BibTeX — double braces,
`location`/`address`: BibLaTeX — double braces, BibTeX — single braces,
Tested on the same item.

**Comment by retorquere** [comment]
Huh -- that make me think that perhaps the change I lined up in 4056 may not do what I thought it did; the single extra brace isn't brace-protection, I usually use that to add a single-item literal list. @njbart, I think this flowed out of something we did a long time ago -- I'm thinking something like #379 (`suppressBraceProtection` set to `false` is just regular bibtex/biblatex export)

**Comment by njbart** [comment]
> `title`, `series`: BibLaTeX — single braces, BibTeX — double braces,

I’d need some context here: If these are exports from a Zotero item with a non-empty, non-English “Language” field, this would make sense, brace-wise.

> `location`/`address`: BibLaTeX — double braces, BibTeX — single braces,

That’s odd indeed: I’d say bibtex would need double braces, too – in order to prevent an `and` (as in `Taylor and Francis`) being interpreted as an (intra-)field separator. (One could of course also just wrap the `and` in braces, but as far as I remember, you opted for wrapping the whole field in braces instead.)

BTW, the same goes for all other fields where an `and` has special meaning (biblatex calls these “literal lists”): institution, organization, origlocation, origpublisher, publisher, as well as the aliases address and school.

**Comment by retorquere** [comment]
> > `title`, `series`: BibLaTeX — single braces, BibTeX — double braces,
> 
> I’d need some context here: If these are exports from a Zotero item with a non-empty, non-English “Language” field, this would make sense, brace-wise.

`language` is `russian` for the sample we're discussing here. What was the difference here again -- why did bibtex get the extra braces but biblatex not? I should have added this as a comment in the code. Currently, I add the extra pair of single braces if

* the translator is bibtex
* the field requires case conversion (caps-protection and title casing)
* the reference is not deemed English
 
but as said, I can't find why I did this, and the change from coffeescript to typescript a long time ago screws with `git bisect` to find the reason.

> > `location`/`address`: BibLaTeX — double braces, BibTeX — single braces,
> 
> That’s odd indeed: I’d say bibtex would need double braces, too – in order to prevent an `and` (as in `Taylor and Francis`) being interpreted as an (intra-)field separator. (One could of course also just wrap the `and` in braces, but as far as I remember, you opted for wrapping the whole field in braces instead.)

For creators I do this separately by replacing ` and ` with ` {and} `.
 
> BTW, the same goes for all other fields where an `and` has special meaning (biblatex calls these “literal lists”): institution, organization, origlocation, origpublisher, publisher, as well as the aliases address and school.

I'll have to look at this.

**Comment by njbart** [comment]
> `language` is `russian` for the sample we're discussing here. What was the difference here again -- why did bibtex get the extra braces but biblatex not? I should have added this as a comment in the code. Currently, I add the extra pair of single braces if
> 
>     * the translator is bibtex
> 
>     * the field requires case conversion (caps-protection and title casing)
> 
>     * the reference is not deemed English

biblatex has a `langid` field it can use to exclude non-English titles from any lowercasing a style might request, so no additional protection by BBT is necessary. bibtex lacks a comparable mechanism, so the only thing BBT can do to tell bibtex to back off from non-English titles is to wrap the whole thing in braces.

**Comment by retorquere** [comment]
Awesome, thanks. I can disable that when `suppressBraceProtection` is on.

`address` and `location` are currently different because I declare what is to be encoded as "single-element literal list" separately for bibtex and biblatex. Currently they are:

bibtex:
* institution
* publisher
* organization

biblatex:
* institution
* publisher
* organization
* location
* venue

as I don't know bib(la)tex nearly as well as one might assume; I just add these designations as I stumble upon them. I'll add `address` to both.

**Comment by njbart** [comment]
No need to add `address` to the biblatex list. The canonical biblatex name is `location`. (And though biblatex does accept `address` for backwards compatibility, BBT should continue to export Zotero’s “Place” to `location`.)

You could add `origlocation` and `origpublisher` to the biblatex list.

On the other hand, the biblatex manual lists “venue” as “field (literal)“, so by rights it should be excluded from the biblatex list (though I have no idea why this is being treated differently from `location`). To be honest, I won’t complain if you leave it in for the time being.

**Comment by retorquere** [comment]
With the default setting (`supress` off), I get this for biblatex

```
@mvbook{Landafshits.V7,
  author = {Ландау, Л. Д. and Лифшиц, Е. М.},
  date = {2007},
  edition = {5},
  isbn = {5-9221-0122-6},
  langid = {russian},
  location = {{М.}},
  pagetotal = {259},
  publisher = {{Физматлит}},
  series = {Теоретическая физика},
  title = {Теория упругости},
  volume = {7},
  volumes = {10}
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.84.4061](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.84.4061.xpi) ("adjust test cases")

Install in Zotero by downloading [test build 5.1.84.4061](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.84.4061.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
@alekhe can you see if 4061 does what you want across settings of `suppressBraceProtection`?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.84.4063](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.84.4063.xpi) ("Merge branch 'master' into gh-1194")

Install in Zotero by downloading [test build 5.1.84.4063](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.84.4063.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by alekhe** [comment]
(I had some strange problems with downloading the build from Amazon AWS — very slow and a number of network errors)

Checked on b4063. Everything seems to work as expected.

Just to clear some things out. I didn’t know you differentiated between BibTeX and BibLaTeX by the language field. From my experience nowadays localized BibTeX styles are language-aware and can change the letter case. I need to use a “classic”, language agnostic, style only for publications in English, which are, well, in English. That’s why I was confused when I saw different number of braces in BibTeX and BibLaTeX output.

**Comment by retorquere** [comment]
> Just to clear some things out. I didn’t know you differentiated between BibTeX and BibLaTeX by the language field. 

That's not what's happening -- bibtex and bblatex are substantially different citation processors, and I output different stuff for each, but that depends entirely on what you choose when you export -- I certainly don't mash the two together. **Within** such bib(la)tex-specific output, I differentiate between English and non-English references. BibLaTeX has better facilities than BibTeX to deal with language-dependent features, so the output for bibtex is more crude (I just brace the field).

> From my experience nowadays localized BibTeX styles are language-aware and can change the letter case.

Are you sure you're not talking about biblatex in those cases?

> I need to use a “classic”, language agnostic, style only for publications in English, which are, well, in English. That’s why I was confused when I saw different number of braces in BibTeX and BibLaTeX output.

The number of braces differ exactly because of these classic styles. I did have an error where `address` in the bibtex output didn't get that treatment.

**Comment by alekhe** [comment]
Well, I didn’t have a lot of experience so that was just my thoughts.

And this is from the gost package (BibTeX Russian styles):

> Bibtex8 fails to change case of a string if it contains Cyrillic letter in unicode. Therefore
ugost2008* styles do not change case of titles and other parts of bibliographic record while
8-bit styles do the case change where appropriate.

(ugost2008* are Unicode styles for bibtex8)

Of course this might work only for specific languages. I do not know the internals.

**Comment by retorquere** [comment]
> Well, I didn’t have a lot of experience so that was just my thoughts.

Oh I didn't mean to have it come across as a rebuttal, sorry about that. I know next to nothing about bib(la)tex myself, I'm just regurgitating what I think smarter people like @njbart have said.

> And this is from the gost package (BibTeX Russian styles):
> 
> > Bibtex8 fails to change case of a string if it contains Cyrillic letter in unicode. Therefore
> > ugost2008* styles do not change case of titles and other parts of bibliographic record while
> > 8-bit styles do the case change where appropriate.
> 
> (ugost2008* are Unicode styles for bibtex8)

Case in point: I don't really know how to interpret this or what I should (or should not) change in BBT to acommodate this. @njbart?
 
> Of course this might work only for specific languages. I do not know the internals.

That would put us on equal footing.

**Comment by alekhe** [comment]
That’s fine don’t worry, no rebuttal implied.

I don’t think any work needed. BibTeX knows nothing about languages (other than English) and one needs to overcome this flaw, which you did. Thanks a lot.
