### ISSUE TITLE
BetterBibTeX: "Booktitle" fill with "Conference Name"

### ISSUE THREAD

**Issue by amoisan** [retorquere/zotero-better-bibtex#1195]
**Report ID:**

**Exporter used:** Better BibTeX

**Expected behavior:**

**Actual behavior:**

Hello,

I am presently working on export from Zotero to BibTeX (with Better BibTeX). I use the .bib to import bibliographic data in open-access repository.

My problem : In Zotero when the field "Proceedings Title" is empty, BetterBibTeX fill it with the item of the field "Conference Name". I would like the field booktitle (Proceedings Title) not to appear in the BibTeX file if it is empty.

I tried to edit the translator BetterBibTeX.js without succes. Could someone explain to me wich line I should edit/erase ?

Sorry for my broken english,

Thank a lot,

Aurélien.

**Comment by retorquere** [comment]
As per the issue template:

> 6. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu
>
> The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Comment by retorquere** [comment]
I really need the debug ID. The debug log will give me a copy of the reference, and with that I can test the postscript before getting it to you.

**Comment by amoisan** [comment]
Excuse-me I didn't see your second answer on Zotero Forum. The script you give me works perfectly ! 

Report ID: C9PR58DY-euc (without your post-script)
Report ID: N5X99AKV-euc (with your post-script line 74)

More  explications: You already helped us to write a post-script few years ago. We added some new lines to update it to the new requirements of our open-access repository. I wanted to generate a new field "Proceedings: Yes/No" with the field "booktitle" that's why i needed to clear it. 

Thanks a lot for your precious help !

**Comment by retorquere** [comment]
Ah, awesome. Don't hesitate to ask again when needed.
