### ISSUE TITLE
Curly braces sometimes missing (publisher)

### ISSUE THREAD

**Issue by manuelhubacher** [retorquere/zotero-better-bibtex#1196]
Hi, 

I get an odd behaviour exporting my library to BibLaTeX. Publishers with just one word (e.g. Continuum) are missing the curly braces in the exported bib file. Unfortunately, I can't pin the moment when the behaviour changed… 

I expect the output to look like this:

```
@book{Dworkin:1984,
  langid = {german},
  location = {{Frankfurt am Main}},
  publisher = {Suhrkamp},
  date = {1984},
  author = {Dworkin, Ronald},
  translator = {Wolf, Ursula},
  title = {Bürgerrechte ernstgenommen}
}
```

What I actually get is this:

```
@book{Dworkin:1984,
  langid = {german},
  location = {{Frankfurt am Main}},
  publisher = Suhrkamp,
  date = {1984},
  author = {Dworkin, Ronald},
  translator = {Wolf, Ursula},
  title = {Bürgerrechte ernstgenommen}
}
```

This results in this bibliography entry with the publisher in small letters:

- Dworkin, Ronald. 1984. *Bürgerrechte ernstgenommen*. Übersetzt von Ursula Wolf. Frankfurt am Main: suhrkamp.

(I use pandoc/pandoc-citeproc to generate my bibliography.)

Thx in advance!

-----

- Report Error ID: DKCVL6XL-euc
- Zotero 5.0.66
- Better BibTeX for Zotero 5.1.85
- macOS 10.14.5

**Comment by retorquere** [comment]
You have `If a field could be a @string var, export it without braces` (in BBT advanced settings in the `@strings` tab) set to `Assume...`. If you turn it off, the behavior you see goes away.

**Comment by manuelhubacher** [comment]
Hi @retorquere,

That did the trick. 

Thanks a lot for the fast answer as well as for this fantastic Zotero extension! 😄
