### ISSUE TITLE
Unicode character error when you have chemical formulas in the item title.

### ISSUE THREAD

**Issue by Oblivion94** [retorquere/zotero-better-bibtex#1197]
**Your question/suggestion:** Good. I have found that using biblatex, with biber evidently. The items that have chemical formulas, as is the case of many scientific articles, give problems in the compilation of documents with UTF8 coding. The wrong unicode character error is output. Probably this is because the subscripts are not recognized correctly. Is it possible to fix this?

**Comment by retorquere** [comment]
Fix in what sense? If you look in the generated bib file with a text editor, does it show the right character?

* If not, can you post an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu?
* If it does show the the right character, it's a biber problem. You may just want to enable `Export unicode as plain-text latex commands` in the preferences, or experiment with the `fontenc` and/or `inputenc` packages, but I can't help with that, that's best addressed on tex.stackexchange.com.

**Comment by retorquere** [comment]
closing for lack of feedback
