### ISSUE TITLE
Why do you say LaTeX users are "holdouts"?

### ISSUE THREAD

**Issue by kendonB** [retorquere/zotero-better-bibtex#1199]
Why do you say LaTeX users are "holdouts"? To my knowledge, LaTeX is the only good free option for preparing work that will ultimately end up being printed on paper, Microsoft Word being the leading alternative. Is there some better third option out there now that people (i.e. I) don't know about?

**Comment by retorquere** [comment]
I unfortunately meet more and more conferences and even publishers where not only they provide only a word or PowerPoint template, they demand the paper be delivered in Word, nothing else. To the apparently growing crowd that makes this demand feasible for them to set, we seem to be holdouts. And there are, truth be told, some things where the latex tool chain is severely lacking and unlikely at this stage to ever catch up; see https://www.fiduswriter.org/2017/01/15/emilano-heyns/ for some of those areas.

I obviously agree that latex is not just relevant - to me it's the *only* sensible way to do serious written work. But as said, there's a growing number of venues where I have no choice but to open Word, which until recently I really even couldn't as I have only recently swapped my Linux laptop for a MacBook. I have some stirrings of a principled argument against the mandated use of an expensive proprietary tool that binds me to one of two proprietary (and each expensive in their own ways) operating systems, but not principled enough it seems to forego publishing at those venues.

The holdouts comment is meant a bit tongue-in-cheek, but holdouts yeah for holding out for the good in the face of the meh-good-enough-and-easy-to-use.
