### ISSUE TITLE
How to revert to previous citation keys

### ISSUE THREAD

**Issue by nachette93** [retorquere/zotero-better-bibtex#1200]
Hi, I'm in the middle of writing my Master thesis, and the citations keys that I used with Zotero changed to another format. 
I don't exactly know how it happened, as I don't recall modifying anything, but I would like to revert the changes. From what I've been able to learn, the format in which the key is generated is editable, and I would like to revert to the previous format, so I don't have to change 80+ citations.
The following citation key is an example of the changes:
previous format: [adhavan_torque_2013]
Current format [adhavanTorqueRippleReduction2013]
Could you please give any imput as to what to change in the format dialog box?
Currently it is set to: [zotero]

Thank you

Citation Debug ID code: 8ZQBCN3T-euc
General Debug ID code: D825133032

**Comment by nachette93** [comment]
Sorry, didn't know that. Just fixed it. The issue though, is a more general one. I would like to know how to revert to a previous citation key generation format. The aim is to match the previous format that I used in my Latex file. Th format changed around a week ago (I'm not sure why or what I did), and since then all my references are broken. I would like to remedy that

**Comment by retorquere** [comment]
I'd still need a debug ID to help you. Right-click any one of the references, and select "Report Better BibTeX Errors" from the menu that pops up.

**Comment by retorquere** [comment]
Oh wait what? You just fixed it, by which I take it you mean you managed to revert your keys, but you don't know how to revert your keys?

**Comment by nachette93** [comment]
No, I meant I added the debug codes to the issue statement, the first comment. The problem persists

**Comment by retorquere** [comment]
Thanks (I can't see the general debug logs like `D825133032` BTW, those go to Zotero).

OK, so your current pattern is set to `author_title_year` (not `[zotero]` as far as I can tell). That will just put the literal text `author_title_year` in each citekey (right?).

Do you want the `[zotero]` pattern (which does look mostly like `author_title_year`, with a few edge cases)? If so, set the pattern to `[zotero]` (including those square brackets), select all items in Zotero for which you want the citekey to follow that pattern, right-click, and select `Refresh` from the `Better BibTeX` menu entry.

**Comment by nachette93** [comment]
Thank you, that fixed that part of the issue. 
For some reason Latex is still not recognising my bibliography entry and displaying "Undefined control sequence. (\addbibresource ...)". I know this is not related to the better bibtex add-on, but is there any chance you have any idea what the issue could be, I'm currently at a loss.

**Comment by nachette93** [comment]
Never mind. Managed to fix it.
Thanks a million

**Comment by retorquere** [comment]
For that I'd have to see more of the document you're compiling, but I'm not actually a great expert on latex; if you show me the document I can take a look, but you might get faster help on tex.stackexchange.com.

**Comment by retorquere** [comment]
Ah, super, you're welcome.
