### ISSUE TITLE
Should I be able to export the files/attachments field?

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#1202]
Hi,

The "attachments" or "files" field seems to be missing in most export formats. The only one which seems to work is BetterBibTeX JSON. Most of my attachments are managed by Zotfile, but not all of them, and neither the ones in Zotero storage nor the ones in local storage (Zotfile managed) get into any of the other export formats. Any idea why?

Best,
Lyndon

**Comment by retorquere** [comment]
I'd need to know what export format specifically you're looking into that doesn't do this.

**Comment by lyndondrake** [comment]
Apologies for slow reply - away for the weekend.

An example is Better CSL JSON. I've attached an example which has no `file:` elements in it.

[zot-export.json.zip](https://github.com/retorquere/zotero-better-bibtex/files/3275211/zot-export.json.zip)

**Comment by lyndondrake** [comment]
Also here's my Better BibLaTeX JSON export in case it's something in my settings:

[bibliography-export.json.zip](https://github.com/retorquere/zotero-better-bibtex/files/3275282/bibliography-export.json.zip)

**Comment by retorquere** [comment]
CSL JSON doesn't have a field for files.

**Comment by lyndondrake** [comment]
Ah, that would explain it.

So, what I want to do is export from Zotero in a form which I can easily script in Applescript/JXA. The easiest way to do that is via a JSON format, because the import to Applescript is straightforward.

Which format would I best use? (And despite what I said at the start of the thread, the Better BibTeX JSON format doesn't include the files, which is of course sensible.)

**Comment by retorquere** [comment]
The CSV exporter maybe? I could add attachment export to the bbt json exporter, but its primary purpose is for bbt-internal debugging. I've not made  changes to it the past half year or so, so it seems pretty stable, but I reserve the right to make any changes I deem necessary at any time. That it's visible to users is not actually my intention, but it's hard to prevent. 

Otherwise it'd be simple to throw together a translator that just dumps the internal format of zotero in json. BBT json does more or less that but does some simplification on the items before I dump it out.

**Comment by lyndondrake** [comment]
CSV works in terms of getting the files out, but of course lacks the "Keep updated" possibility.

The reason I'm after this is to see if I can recreate this [Bookends–>DEVONthink script I wrote](
https://discourse.devontechnologies.com/t/a-new-bookends-dt-script-with-a-group-per-reference/47950/29) for Zotero.

I could probably do it using the Zotero web api, but that'd be a bit slow, and involves writing a bit more code. Slurping in one big JSON and iterating over it would the super-easy version.

If you have a bit of time to chuck an extra translator into BBT that would be super helpful. Or else I'm quite happy, if you updated the BBT JSON exporter to include the file, to live with the risk of the functionality disappearing at some point or breaking my script.

**Comment by retorquere** [comment]
I *think* if you just add the "keepUpdated" option to the CSV exporter (make sure to make a copy and modify the guid) it should just work (no guarantees), but with the caveat above I don't mind adding the path for the attachments to BBT JSON.

**Comment by lyndondrake** [comment]
I’d love it if you could add the path for the attachments to the BBT JSON

Sent from my phone - please excuse brevity & typos
________________________________

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.87.4109](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.87.4109.xpi) ("add attachment path")

Install in Zotero by downloading [test build 5.1.87.4109](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.87.4109.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.87.4110](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.87.4110.xpi) ("allow file export")

Install in Zotero by downloading [test build 5.1.87.4110](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.87.4110.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 4110 a go.

**Comment by lyndondrake** [comment]
Perfect, thank you!

**Comment by retorquere** [comment]
I've scheduled a new release which will include this.
