### ISSUE TITLE
"Keep updated" for BetterBibTeX JSON

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#1203]
Hi,

(There's no error report available for this)

There is no option to have "Keep updated" for BetterBibTeX JSON. I wondered if that option could be added?

Best,
Lyndon

**Comment by lyndondrake** [comment]
AFSDBCNP-euc

(I've picked a reference to which this applies and generated an error report, in case it helps)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.85.4079](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4079.xpi) ("auto-update for BBT-JSON, fixes #1203")

Install in Zotero by downloading [test build 5.1.85.4079](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4079.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
try 4079

**Comment by lyndondrake** [comment]
That works. Thank you!
