### ISSUE TITLE
Export "urldate" even when DOI and URL are empty

### ISSUE THREAD

**Issue by amoisan** [retorquere/zotero-better-bibtex#1206]
**Report ID: PY2FIFAU-euc

**Exporter used: BetterBibtex

**Expected behavior: Hello,

 I need to export "urldate" even when DOI and URL are empty. Is it possible with a post-script ?

My post-script should change "urldate" in "x-conferencenddate" but it doesn't work because of this problem.

Thanks a lot, 

Aurélien.

**Comment by retorquere** [comment]
So you want the `Accessed` field from Zotero (which is what BBT uses to fill `urldate`) in `x-conferencenddate`?

That could be done with

```
if (Translator.BetterBibTeX) {
  reference.add({ name: 'x-conferencenddate', value: item.accessDate })
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.90.4126](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.90.4126.xpi) ("postscript reused removed field")

Install in Zotero by downloading [test build 5.1.90.4126](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.90.4126.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by amoisan** [comment]
It works perfectly ! Thank you (again)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.91.4128](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.91.4128.xpi) ("5.1.91")

Install in Zotero by downloading [test build 5.1.91.4128](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.91.4128.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
