### ISSUE TITLE
Latex commands in "extra"-field treated differently

### ISSUE THREAD

**Issue by morihe** [retorquere/zotero-better-bibtex#1207]
I need to pass latex commands (starting with a backslash) to the bib file for various formatting needs - mostly to accommodate the use of Chinese characters. 

For this I have used the "extra"-field and it seemed to work well in this example: 
`biblatex[author=Liu, \chsf{刘华春}, Hua\-chun] `
produces 
`author = {Liu, \chsf{刘华春}, Hua\-chun}` in the bib file. 
 
In combination with "publisher", however, the same string is treated differently, producing
`publisher = {{Liu, \textbackslash{}chsf\{刘华春\}, Hua\textbackslash{}-chun}}`
in the bib file. 

I have tried the Json5 encoding but backslashes will disappear in the bib output in that case:
`biblatex{author: "Liu, \chsf{刘华春}, Hua\-chun"}`
produces
`author = {Liu, chsf{刘华春}, Hua-chun}`

Is there any way to work around this (or possibly any error on my side)?

Error report ID: TUXQGSWH-euc

**Comment by morihe** [comment]
I have tried escaping the backslash in the Json5 format which works well for the author alone but not for the following:
```
biblatex{
  author: "Liu, \\chsf{刘华春}, Hua\\-chun",
  title = "\\py{Hu\\-lian\\-wang jin\\-rong jian\\-guan fa\\-lü gui\\-zhi yan\\-jiu"
}
```
produces
```
  author = {刘华春},
  note = {biblatex\{
  title = "\textbackslash\textbackslash{}py\{Hu\textbackslash\textbackslash{}-lian\textbackslash\textbackslash{}-wang jin\textbackslash\textbackslash{}-rong jian\textbackslash\textbackslash{}-guan fa\textbackslash\textbackslash{}-lü gui\textbackslash\textbackslash{}-zhi yan\textbackslash\textbackslash{}-jiu"
\}\vphantom\}}
```
in the bib file.

**Comment by retorquere** [comment]
Can you please send a debug log outlined above? With it I have an exact copy of your item and settings and it's much easier for me to replicate what you're seeing. It's just a few clicks.

**Comment by retorquere** [comment]
Oh sorry I see you've edited the original report, I'll take a look.

**Comment by retorquere** [comment]
That should be 

```
biblatex{
  author: "Liu, \\chsf{刘华春}, Hua\\-chun",
  title: "\\py{Hu\\-lian\\-wang jin\\-rong jian\\-guan fa\\-lü gui\\-zhi yan\\-jiu"
}
```

(notice the `:` instead of the `=`)

**Comment by retorquere** [comment]
Are you sure that `"\\py{Hu\\-lian\\-wang jin\\-rong jian\\-guan fa\\-lü gui\\-zhi yan\\-jiu"` is correct though? The braces are unbalanced.

**Comment by morihe** [comment]
Sorry for those mistakes, you are right, of course. Interestingly, the problem persists: 
```
biblatex{
  author: "Liu, \\chsf{刘华春}, Hua\\-chun"
}
```
yields `author = {Liu, \chsf{刘华春}, Hua\-chun}`
whereas merely changing "author" to "publisher" results in 
`publisher = {{Liu, \textbackslash{}chsf\{刘华春\}, Hua\textbackslash{}-chun}}`

To me it seems that using "publisher" makes BBT convert the string to latex code that would result in the string I want once it is interpreted by latex.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.90.4138](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.90.4138.xpi) ("update testcase")

Install in Zotero by downloading [test build 5.1.90.4138](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.90.4138.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 4138 a try

**Comment by morihe** [comment]
That seems to work (in both formats)! Thank you so, so much!

**Comment by retorquere** [comment]
Thanks for the confirmation, release 5.1.92 has been scheduled.

**Comment by morihe** [comment]
Another thing I just noticed is that empty curly brackets such as 
```
biblatex{
  author: "Xu, \\chsf{}, Duo\\-qi"
}
```
get eliminated in the bib file. I personally need them to be preserved, but possibly this is intended behaviour.

**Comment by retorquere** [comment]
What doe these brackets do?

**Comment by morihe** [comment]
I have customised biblatex to treat Chinese names differently (in the order: last name, first name, Chinese characters) by checking if the field in the middle contains something other than "jr." etc. If known, I will put the Chinese characters inside the curly brackets. Here, however, I don't know them but still want the special formatting to apply. Very specific, I see ;) Perhaps I could try a workaround by inserting a tiny whitespace inside the brackets.

**Comment by retorquere** [comment]
I can make an exception for raw fields.

**Comment by morihe** [comment]
That would be awesome, if this is a concern for more users than just me!

**Comment by retorquere** [comment]
I've not yet heard about it, but it fits the philosophy of the raw fields.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.92.4162](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.92.4162.xpi) ("fix #1207 again")

Install in Zotero by downloading [test build 5.1.92.4162](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.92.4162.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try the new build

**Comment by morihe** [comment]
Works like a charm. You made my day - again!

**Comment by retorquere** [comment]
Alright, 5.1.93 is building
