### ISSUE TITLE
Installation file - zotero-better-bibtex-1.6.<>.xpi not available

### ISSUE THREAD

**Issue by ristrettoanna** [retorquere/zotero-better-bibtex#1210]
I am trying to find the installation file for the better bibtext but I am afraid, I am unable to find the file and then when I am clicking on the installation, "Woops. Looks like this page doesn't exist ¯\_(ツ)_/¯." is coming (https://github.com/retorquere/zotero-better-bibtex). Please help me acquiring the installation file for the better-bibtex.

**Comment by retorquere** [comment]
You can ignore blip-bloop here.

**Comment by ristrettoanna** [comment]
Looking forward to receiving the installation file.

**Comment by retorquere** [comment]
The link should be fixed now. Thanks for reporting this.

**Comment by ristrettoanna** [comment]
Thank you so much.
