### ISSUE TITLE
Overleaf push/pull via GitHub not working

### ISSUE THREAD

**Issue by phthalimid** [retorquere/zotero-better-bibtex#1211]
I am frequently writing multi-author articles using _Overleaf_. My co-authors and I are using _Zotero_ groups to collect/manage our references. I followed these instructions to link _Overleaf_ to _Zotero_ via _GitHub_:

https://retorque.re/zotero-better-bibtex/exporting/

It is all working, except for the automatic pull of the _Zotero_ .bib file from _GitHub_ (it works manually though). I did not try the 'arara' method, because I am not familiar with 'arara' and didn't find any instructions that I understood. I tried to use '\addbibresource[location=remote]{https://raw.githubusercontent.com/Me/MyStuff/master/zoteroBBT.bib}'. When compiling, this dies with a 'HTTP Code: 500' error.

Loads of googling let me to the conclusion that this seems to be a _biber_ problem, but (after 8 hours or so) I gave up and found no solution.

So my question is: how can I automatically pull the zotero.bib file from _GitHub_ on each compilation.

Why is this a big problem: my co-authors cannot download it manually on _Overleaf_.

**Comment by retorquere** [comment]
Arara isn't going to work on overleaf, and neither will a pull export (anything involving http: on that page), as overleaf doesn't have access to your system that the zotero client runs on, sorry.

For overleaf support, you currently have 3 options:

* pin your citekeys and use the regular zotero-overleaf integration
* use BBT auto-export and overleaf's git support
* use BBT auto-export and overleaf's dropbox support

The last two are paid features of overleaf though.

**Comment by retorquere** [comment]
I've updated the site to clarify this.

**Comment by retorquere** [comment]
Does this address your question?

**Comment by retorquere** [comment]
assuming addressed.

**Comment by phthalimid** [comment]
Hi Emiliano,

Sorry for not reacting earlier. I am travelling at the moment and have 
been busy & jet-lagged. Yes, the issue is resolved. Thanks a lot!

Thomas
