### ISSUE TITLE
Is it possible to generate keys like [author][year][letter in case of duplicates]

### ISSUE THREAD

**Issue by lsaravia** [retorquere/zotero-better-bibtex#1212]
Hi, I am trying to change how keys are generated, didn't found (I am new) how to format the citation key field, many webpage links seem to be broken, so what I would like is something like

Allesina2009
Allesina2009a
Allesina2009b

is it possible?

**Comment by lsaravia** [comment]
Is a question, I don't know how to change the label...

**Comment by retorquere** [comment]
You can't change the label, they get set according to the bug template you choose.

Which links are broken? I'd love to fix those.

Assuming the author for that reference is "Allesina", `[author][year]` should get you keys like above. If your references looks different, right-click on one of them and send a BBT error report from the popup menu.

**Comment by retorquere** [comment]
If you already get keys like `Allesina2009`, the `a`, `b` etc postfix is automatic, you can change it to `-1`, `-2`, but postfixing cannot be turned off.

**Comment by lsaravia** [comment]
I get some broken links at https://github.com/retorquere/zotero-better-bibtex/wiki, check the link on this page https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys 

And when I read the page http://retorque.re/zotero-better-bibtex/installation/configuration/citation-keys/  I see "The format of the keys is documented here" this refers to the same page http://retorque.re/zotero-better-bibtex/installation/configuration/citation-keys/ which doesn't seem to have the documentation about the format.

**Comment by retorquere** [comment]
Thanks for that -- those links have now been fixed. http://retorque.re/zotero-better-bibtex/installation/configuration/citation-keys/ now links through to https://retorque.re/zotero-better-bibtex/citing/.

**Comment by retorquere** [comment]
Does this address your question?

**Comment by lsaravia** [comment]
Yes many thanks!
