### ISSUE TITLE
Unique citations key via API

### ISSUE THREAD

**Issue by SamPassmore** [retorquere/zotero-better-bibtex#1213]
**Your question/suggestion:**
Hi, 

I am using the zotero API to auto-generate a bibtex file. 
I used this add-on tool on my desktop but is that a local change and not a change on the cloud stored DB? 

thanks, 

Sam

**Comment by retorquere** [comment]
BBT only works locally. You can get the citekeys you have locally by pinning them, that will make the available via the API, but the bibtex generated for those keys will not be BBT bibtex but zotero bibtex. But if you mostly care about the keys, pinning will work.

**Comment by SamPassmore** [comment]
Ah yes - this works thanks!
