### ISSUE TITLE
Search API multiple terms

### ISSUE THREAD

**Issue by maegul** [retorquere/zotero-better-bibtex#1215]
This concerns the API described in #852 (Feature Request: CAYW suggestions JSON API).

Thanks for such a nice feature.  Like in the request, I'm thinking of using that in a plugin.

However, I'm wondering if it's possible to pass in multiple search terms as can be done with the CAYW interface?

My experimenting with the API indicates that only the first term passed in under "params" is used.

EG, in the request below, "SEARCH_TERM2" appears not to be used.

```
http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": ["SEARCH_TERM1", "SEARCH_TERM2"] }'
```

**Comment by retorquere** [comment]
`item.search` does a quicksearch (the search field above the item list), but json-rpc allows arrays of commands, so this would work:

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '[{"jsonrpc": "2.0", "method": "item.search", "params": ["SEARCH_TERM1"] }, {"jsonrpc": "2.0", "method": "item.search", "params": ["SEARCH_TERM2"] }]'
```

**Comment by maegul** [comment]
Thanks @retorquere for quick reply!!

Your solution wasn't quite what I was after (probably because I wasn't clear enough).

I didn't realise that this API is accessing the quicksearch functionality (that definitely clarifies things).

What I was after was for the two search terms to be used together to limit or refine the search results.  Passing in an array of commands as you suggest runs two independent searches and returns an array of results, one for each element in the array passed as the command or data.

I believe this type of call is referred to as a "batch call" in the [JSON-RPC spec](https://www.jsonrpc.org/specification).

**What does appear to do what I'm after**, however, is to simply pass multiple search terms as a single space separated string (as one would do with the quick search field.

So, to use the example I originally posted, with each search term being passed as a single element in an array, the following appears perform the limiting or refining kind of search I was after:

```
http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": ["SEARCH_TERM1 SEARCH_TERM2"] }'
```

**Comment by retorquere** [comment]
That's correct, you can pass multiple terms and they'll act as an AND search. If this does what you want, we can close the issue.

**Comment by maegul** [comment]
Yes, and thanks!
