### ISSUE TITLE
Double superscript in title field on export

### ISSUE THREAD

**Issue by robbyblum** [retorquere/zotero-better-bibtex#1217]
**Report ID:** I5IZKAFW-euc

**Exporter used:** Bibtex export

**Expected behavior:** `title = {{$^{31}$}{{P NMR}} Study of...`

**Actual behavior:** `title = {{$^3^1$}{{P NMR}} Study of...`

When exporting a bibliography entry where the title includes this particular multi-character superscript, BBT (with "export unicode as plain-text latex commands") is exporting it in a form that throws a latex error when I try to compile the bibliography. The error is a "Double superscript." error, and it's not fatal, but it sure is annoying to have to dismiss it every time I compile. The expected behavior (i.e. if I manually edit the .bib file to fix this) compiles fine, but of course any manual edits I do to the .bib file get overwritten every time BBT updates the export. I don't know if there's any way to override this that I'm just not aware of.

Ironically, the original entry I imported into Zotero through "Import from Clipboard" was formatted correctly: https://gist.github.com/robbyblum/147ba69baa886f9015c3870e3e51f618. But it looks like Zotero transformed the `$^{31}\mathrm{P}$` into just "³¹P".

**Comment by retorquere** [comment]
I'll see what I can do about it -- @njbart, what do you make of this? `^{31}` is of course cleaner, but `^3^1` should be unambigous, right? The `^` acts on the first construct behind it, which is the just the `3`.

**Comment by robbyblum** [comment]
It should be unambiguous, yeah, but LaTeX seems to think it's an error, for reasons passing understanding. In the meantime I finally learned how to use the `<pre></pre>` tags so I can just hard code it in myself...

**Comment by retorquere** [comment]
Shouldn't be necessary to use `pre` here. I think I might have a fix.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.99.4275](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.99.4275.xpi) ("site-update acts funky on branches")

Install in Zotero by downloading [test build 5.1.99.4275](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.99.4275.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4275?

**Comment by robbyblum** [comment]
I pasted the unicode title back in, and this is what it converted it to:

```
@article{Rovny2018,
...
  title = {{$^{31}$}{{P NMR}} Study of Discrete Time-Crystalline Signatures in an Ordered Crystal of Ammonium Dihydrogen Phosphate},
...
}
```
Perfect! This change also cleaned up some unneeded brackets in another bibliography entry, according to the diff, so that's cool.

**Comment by retorquere** [comment]
Super. I'll fix 1218 and then cut a new release.
