### ISSUE TITLE
Search API: Results Order

### ISSUE THREAD

**Issue by maegul** [retorquere/zotero-better-bibtex#1220]
Query regarding the "search API" discussed in #852 and #1215.

There appears to be a rule governing the order in which the results are returned.
As the API uses the quicksearch functionality (as @retorquere mentions in #1215) I could quickly experiment in the GUI to see which column the API appears to be sorting by.  It appears that the results returned by the API are being sorted by the **Date Added** metadata.

I'm wondering if this is not the most appropriate way of sorting by default --- by first author, year or title would probably be more helpful.  

Also, would it be possible to change the ordering through the API (though such could of course be done straightforwardly client side)?

Thanks again for this feature!

**Comment by retorquere** [comment]
If it's done straightforwardly on the client, I prefer to have it done there. This seems like a feature that could easily devolve into a fully-fledged query parser, and I really don't want to go there. Zotero itself applies the sorting to the query results separately, so there's not something I could easily repurpose.

It's likely that results are in order of date-added, but it's also likely to be so through no specific design, as Zotero always applies sorting in the UI to the results.

**Comment by maegul** [comment]
Makes sense.  And yes, sorting clientside should almost always be feasible.  
Thanks!
