### ISSUE TITLE
CSL fields are no longer being exported

### ISSUE THREAD

**Issue by danprisk** [retorquere/zotero-better-bibtex#1222]
I've been using the CSL format in my extras field in order to include original publication dates. e.g.

> {:original-date: 1856}

However, at some point recently this has stopped working and these fields are no longer being exported to .bib files. I've found that if I switch to bibtex/square bracket format it works still, so the following works:

> bibtex[origdate=1856]

This is at least a workaround for now, but it's an issue for backwards compatibility for my existing library.

**Comment by danprisk** [comment]
Here is the requested debug id: EPY4XUMQ-euc

**Comment by retorquere** [comment]
It exports without issue for me (see below). Are you using bibtex instead of biblatex? bibtex doesn't have an `origdate` equivalent field.

```
@incollection{BourdieuSocialSpaceSymbolic1998,
  author = {Bourdieu, Pierre},
  booktitle = {Practical Reason: On the Theory of Action},
  date = {1998},
  isbn = {978-0-7456-1624-7 978-0-7456-1625-4},
  langid = {english},
  location = {{Cambridge}},
  origdate = {1989},
  pages = {1-13}, 
  publisher = {{Polity Press}},
  title = {Social {{Space}} and {{Symbolic Space}}}
}
```

**Comment by danprisk** [comment]
Thanks for the quick reply, and really sorry if this is a setup issue! Just to confirm, you mean when creating the export selecting the format as "Better BibLatex"? 

I just checked this and have run the export as "Better BibLatex", "Better Bibtex", and simply "BibLatex" and none seem to give me the same as above.

For Better BibLatex I'm getting the following:

> @incollection{bourdieu1998b,
  langid = {english},
  location = {{Cambridge}},
  title = {Social {{Space}} and {{Symbolic Space}}},
  isbn = {978-0-7456-1624-7 978-0-7456-1625-4},
  booktitle = {Practical Reason: On the Theory of Action},
  publisher = {{Polity Press}},
  date = {1998},
  pages = {1-13},
  author = {Bourdieu, Pierre},
  note = {\{:original-date: 1989]\vphantom\}}
}

Are there other settings I may be missing here?

**Comment by retorquere** [comment]
Yep, I mean exporting as `Better BibLaTeX` -- there's nothing to apologize for, but I can't currently replicate your issue at my end. 

Can you try going into the BBT advanced preferences and clicking `Reset cache` there, and then export again?

**Comment by retorquere** [comment]
Wait, I can actually replicate it, but only if I have the following in the `extra` field:

```
{:original-date: 1989]
```

but that's not in `EPY4XUMQ-euc`

(if you want to post verbatim text it display clearer with triple backticks (```) above and below the text at the start of the line -- I've amended your post for this)

**Comment by danprisk** [comment]
Ok, clearing the cache and trying again has everything working nicely - but looking at your second comment it seems like when I tested ensuring my export was set to better biblatex I may well have introduced that typo into my extra field (I was switching back and forth between bibtex/csl formats there), so it looks like this was likely just a config issue my end. Thanks for your help with that.

**Comment by retorquere** [comment]
That's quite alright, glad you're on your way again.
