### ISSUE TITLE
BBT Quick Copy link with item ID not working

### ISSUE THREAD

**Issue by qqobb** [retorquere/zotero-better-bibtex#1225]
This minor issue was first mentioned here: https://forums.zotero.org/discussion/comment/335969/#Comment_335969

With one Zotero library, BBT Quick Copy links with "Select link (item ID)" and "Org-mode (item ID)" options are lacking the "0_" or "1_" prefix to the itemkey. One currently needs to add the prefix manually to get usable links of the form <code>zotero://select/items/1_[itemkey]</code>.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.101.4314](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.101.4314.xpi) ("fixes #1125")

Install in Zotero by downloading [test build 5.1.101.4314](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.101.4314.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.103.4321](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.103.4321.xpi) ("Merge branch 'master' into gh-1225")

Install in Zotero by downloading [test build 5.1.103.4321](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.103.4321.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4321?

**Comment by qqobb** [comment]
Hi, I just tried to install 4321, but there was a failure message. I suspect that I was too late and BBT already updated to a version that included the fix. The issue is now resolved. Thanks a lot! I really appreciate your work on BBT!
