### ISSUE TITLE
Exporting a collection to Better BibLaTeX does not "Export Files"

### ISSUE THREAD

**Issue by jpeacock29** [retorquere/zotero-better-bibtex#1226]
**Report ID:** 4W3XG7XI-euc

**Exporter used:** Better BibLaTeX, with "Export Files" checked

**Expected behavior:** A folder containing the exported BibLaTeX and the files associated with the exported citations is generated.

**Actual behavior:** A folder containing only the exported BibLaTeX and no additional files is generated.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.108.4333](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.108.4333.xpi) ("log attachments saving")

Install in Zotero by downloading [test build 5.1.108.4333](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.108.4333.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you send a new log from 4333? I can't reproduce your problem locally.

**Comment by jpeacock29** [comment]
Glad to! However, the above link to build 4333 is 404ing.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.110.4342](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4342.xpi) ("Merge branch 'master' into gh-1226")

Install in Zotero by downloading [test build 5.1.110.4342](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4342.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 4342

**Comment by jpeacock29** [comment]
Still 404ing unfortunately.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.110.4346](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4346.xpi) ("Merge branch 'master' into gh-1226")

Install in Zotero by downloading [test build 5.1.110.4346](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4346.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.110.4353](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4353.xpi) ("Merge branch 'master' into gh-1226")

Install in Zotero by downloading [test build 5.1.110.4353](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4353.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
OK, I think I found the problem for that, try 4353.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.110.4365](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4365.xpi) ("support")

Install in Zotero by downloading [test build 5.1.110.4365](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.110.4365.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jpeacock29** [comment]
Tested with 4353 and the problem appears resolved. Thank you for your help and the great work you do for the community!

**Comment by retorquere** [comment]
That was unexpected. 4365 only adds logging.
