### ISSUE TITLE
Open date range crashes citekey generator

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/zotero-better-bibtex#1227]
Report ID:  IWG9U8C4-euc

On every start of Zotero I get "Assigning Citation Keys"

![image](https://user-images.githubusercontent.com/6059733/61375008-ca450a00-a86b-11e9-9daf-a33469820e94.png)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.109.4338](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.109.4338.xpi) ("open date?")

Install in Zotero by downloading [test build 5.1.109.4338](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.109.4338.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
can you send me a new debug log from 4338? I may have found something. This won't fix it but should give me enough information to fix it.

**Comment by richardkaplan** [comment]
How do I install an .xpi file?

**Comment by retorquere** [comment]
open the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by richardkaplan** [comment]
Done

Report ID: ZU5XPLXJ-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.109.4339](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.109.4339.xpi) ("fixes #1227")

Install in Zotero by downloading [test build 5.1.109.4339](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.109.4339.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 4339

**Comment by retorquere** [comment]
At least one of your items has `--` for a date, which I didn't know how to handle.

**Comment by richardkaplan** [comment]
The solution is not critical to me.. I am OK leaving it blank, assuming 01/01/01, or assuming today's date - whichever is easiest for you.

**Comment by retorquere** [comment]
It assumes blank, but the important thing is that it won't trigger key regen every start.

**Comment by richardkaplan** [comment]
Can you change it so the blank does not trigger it?

Or do we need to change the database so the blanks are not there?

I am fine either way

**Comment by retorquere** [comment]
No, 4339 fixes BBT so that when it sees an open date, it assumes no year is set. 4339 fixes it as far as I can tell, but I'd prefer to know if it also fixes it at your end -- if so, this would be ready to release.

**Comment by richardkaplan** [comment]
will give it a try

**Comment by retorquere** [comment]
Mind that the first time after install, you will still see the popup. Let that finish, then quit (cmd-quit) Zotero, and start again. It should be gone from that point on.

**Comment by richardkaplan** [comment]
Good news - the fix works.  Thank you.

Not as good news - the initial creation of citekeys now takes about twice as long as it used to.

**Comment by retorquere** [comment]
That's likely because generation failed early in the existing release which made it exit sooner than it should. It's a one-time procedure, you should not see it again.

All this is going to change anyhow when Zotero finally gets around to adding a formal citekey field, which should happen Any Moment Now™️.
