### ISSUE TITLE
export title exactly as written

### ISSUE THREAD

**Issue by erikku75** [retorquere/zotero-better-bibtex#1228]
Hello, 

I wish to have BBT export the titles I write in Zotero _exactly as they are written_. No escapes, no brackets, nothing. If the written title in Zotero contains for example

filling factors $\nu \leqslant 6$

I want that exact text to appear in the .bib file. What I get is

Filling Factors \$\textbackslash{}nu \textbackslash{}leqslant 6\$

with unwanted capitalization, \ before $, and \textbackslash{} instead of \. From looking through other reports here I see the capitalization may be unavoidable--to be honest it's not clear though. Surely there is some way to have a _literal_ character-for-character export of the title as written in Zotero?

Thank you---

**Comment by erikku75** [comment]
M6A34KZW-euc

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/exporting/advanced/

**Comment by retorquere** [comment]
Does that page address your question?

**Comment by erikku75** [comment]
yeeeessss... Sorry, I'd written a response but not posted. Ok: Tags, yes, thank you, time to learn to use those. That worked: the title (and most importantly, LaTeX) formatting went out just as written. Then I got stuck in a loop figuring out how to get LaTeX to keep the capitalization as written (again, the theme, don't mess with the title!).

But I found a feature of the tags that may or may not be intended. So: if I tag a bunch of files with #LaTeX, the title goes out as written when I export the collection. Then, for some reason, let's say I un-tag the files, and re-export the collection. It behaves as if still tagged with #LaTeX. Now I change something in one of the titles and re-export. _That_ file now behaves as if it is not tagged, the others still behave as if they are tagged (they are not). That was surprising.

And if I re-tag everything, then once again I'm back to exporting the title as written. So a "memory of having been tagged" persists. Don't know if that's supposed to happen. I would assume "if not tagged, don't behave like tagged" is what you'd want, but maybe there's a reason for this.

Thanks!

**Comment by retorquere** [comment]
There's not supposed to be any kind of memory effect. It must be a caching issue. Can you enable debug logging from the help menu, replicate the problem, and send a debug report?

**Comment by erikku75** [comment]
sure thing—will be a couple days, major proposal due tomorrow (not the best time to decide to re-up my bibliography!).

**Comment by retorquere** [comment]
I understand.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.124.4415](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.124.4415.xpi) ("Merge branch 'master' into gh-1228")

Install in Zotero by downloading [test build 5.1.124.4415](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.124.4415.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I think I've found the problem -- 4415 should fix it.

**Comment by erikku75** [comment]
gotcha, installed. Firefox said it was a corrupt download, fwiw, but Safari worked. Presumably I won't be able to reproduce the problem now. ;)  Thanks so much, I'll keep you posted of anything else.

**Comment by retorquere** [comment]
In Firefox, right - click the link and save always works for me.
