### ISSUE TITLE
Cannot search by citation key

### ISSUE THREAD

**Issue by saffar4ever** [retorquere/zotero-better-bibtex#1231]
Hi,

Even though it looks like it is supported ([http://retorque.re/zotero-better-bibtex/citing/](url)), it does not work for me. I select “All fields and tags” in the search box, but it still doesn't search by citation key.

Please assist. Thank you.

Regards,
Meshaal

**Comment by retorquere** [comment]
You can ignore @label-gun -- I've updated the site (should be live in a few minutes), citekey search did not make it to Zotero 5 in BBT. Citekey search is not currently possible within the search infrastructure of Zotero 5; it will return when citekeys get their own field in an upcoming Zotero release.

**Comment by saffar4ever** [comment]
Alright thanks
