### ISSUE TITLE
Pull export: Request not allowed

### ISSUE THREAD

**Issue by MarekSuchanek** [retorquere/zotero-better-bibtex#1233]
Hello, I have the following problem when accessing the URL for pull export as described at http://retorque.re/zotero-better-bibtex/exporting/pull/

http://127.0.0.1:23119/better-bibtex/library?/1/library.biblatex

**Expected behavior:** 200 HTTP response with file/content according to requested type

**Actual behavior:** 403 HTTP response with content `Request not allowed`

Could you please tell me what am I doing wrong?

**Comment by retorquere** [comment]
Such requests no longer work for the browser in Zotero 5.0.71. curl should work.

**Comment by retorquere** [comment]
To be specific, just about anything non-browser should work, but browser access will not work from 5.0.71 on for security reasons.

**Comment by MarekSuchanek** [comment]
Thank you very much!

**Comment by odkr** [comment]
You can get pull export to work if you set the `User-Agent` header and/or the `Zotero-Allowed-Request` header. See <https://github.com/odkr/pandoc-zotxt.lua/issues/1> for details.

Also, I've filed this as a bug with Zotero. See <https://forums.zotero.org/discussion/78502/http-user-agents-that-dont-identify-fail-for-zotero-v5-0-71>.

**Comment by retorquere** [comment]
The user-agent header should suffice (it has so far) -- `curl` sends a user-agent header by default.

**Comment by ohrensessel** [comment]
Sadly, this breaks my biblatex setup. It isn't possible anymore to include a library via `\addbibresource[location=remote]{...}`, as biblatex probably sets the user agent wrongly?!
Do you know of any possibility to set the user agent to be used by biblatex by some parameter? Or can I disable this weird security measure in zotero by any means?

**Comment by ohrensessel** [comment]
Ah nervermind. Just came accross this commit https://github.com/plk/biber/commit/cb1205356b8615b3de5492936005d9b04d0f0495

**Comment by sqrtroot** [comment]
This seems like "security by obscurity" to me, enforcing this only adds a small hurdle, that is super easy to overcome. Plus it breaks so many setups. Could it at least be possible to be able to disable this from a setting?

**Comment by retorquere** [comment]
It's out of my hands -- Zotero enforces this, not me, and I do in fact
agree that it's a valid measure. While it is easy to overcome for just
about any client, it specifically excludes one client: a web browser. A
malicious web page could previously talk with Zotero directly, and that
would mean eg that by using BBT you could request someone's library content.
