### ISSUE TITLE
How to set the option of exporting URLs into a note field in an export query URL?

### ISSUE THREAD

**Issue by roper79** [retorquere/zotero-better-bibtex#1236]

**Comment by retorquere** [comment]
![Screenshot 2019-07-24 at 13 14 18](https://user-images.githubusercontent.com/132108/61789491-187e7e00-ae15-11e9-8b33-24da3aa4b4d1.png)

**Comment by roper79** [comment]
Thanks for the reply!
This works in the desktop application, however, exporting using URL (curl) seems not to honor this setting.

**Comment by retorquere** [comment]
Oh you mean it's off and you want to turn it on only for this export?

**Comment by retorquere** [comment]
Because if it's on and the pull url doesn't do this, I'd need a debug report.

**Comment by roper79** [comment]
OK, so I made sure that the "Export in a note field" is set for URL in settings, then switched on Debug Output Logging and issued
`curl "http://127.0.0.1:23119/better-bibtex/library?/1121987/library.biblatex&exportNotes=true" > bibliography.bib`7PIRLM9S-euc
The URLs are still in the URL field, not in notes, as they were on manual export from Zotero.

Report ID: q7PIRLM9S-euc

**Comment by retorquere** [comment]
That setting is only for bibtex, not biblatex. If you change the biblatex in the url to bibtex it will likely work, but bibtex doesn't have built-in pull support.

**Comment by roper79** [comment]
Changing to bibtex solves the problem! Thanks a lot for your assistance and the wonderful software!

**Comment by retorquere** [comment]
I'll update the documentation to explain this, thanks for reporting it.
