### ISSUE TITLE
Issue with CAYW URL

### ISSUE THREAD

**Issue by AmomentOfMusic** [retorquere/zotero-better-bibtex#1237]
**Report ID:** 95LZALVU-euc

**Expected behavior:**

When calling the CAYW URL that either the picker pops up, or, if using the probe, that it says ready

**Actual behavior:**
Picker does not pop up. Instead, when I paste the URL into my browsing, it just says "Request not allowed" (see below). 
![image](https://user-images.githubusercontent.com/38445436/62078068-b6a98400-b219-11e9-8d0e-503b972fcd4c.png)

I have not used this functionality in the last couple of weeks, so I'm not 100% sure when the problem started - the last time I can be confident that I used it was about two Zotero updates ago. I suspect it might be something on my end if nobody else is experiencing this problem, but any insights you might have would be appreciated.

**Comment by retorquere** [comment]
This is due to a security update in Zotero 5.0.71 - browser requests no longer work. `curl` and any other programmatic access will work, but browsers won't.

**Comment by AmomentOfMusic** [comment]
Unfortunately this doesn't seem to be the case with powershell: 
![image](https://user-images.githubusercontent.com/38445436/62082665-3425c200-b223-11e9-8e57-452cf728566f.png)

Interestingly, when I run the curl request on bash/ubuntu (using windows new WSL feature) it seems to work fine! So it looks like it's a windows things.

**Comment by retorquere** [comment]
Try sending a user agent header

**Comment by AmomentOfMusic** [comment]
Aha! Problem solved. Thanks as always:)

**Comment by retorquere** [comment]
My pleasure.
