### ISSUE TITLE
Drag and drop not working (while copying reference does)

### ISSUE THREAD

**Issue by staaffy** [retorquere/zotero-better-bibtex#1241]
**Report ID:**
VTJC5EDN-euc

**Exporter used:**
BBT citation key quick copy

**Expected behavior:**
Drag and drop should generate a citation key with brackets, such as when I copy citation using ctrl+shift+c

**Actual behavior:**
Drag and drop citation from zotero to markdown editor Typora does not work while Zotero export settings are set to BBT citation key quick copy.  The markdown app does not react and nothing gets copied over. If I change quick copy settings to Zotero defaults (eg. Vancouver style), then drag and drop to Typora works perfectly fine, but I loose the citation keys. 

If I use ctrl+shift+c instead of drag and drop, then BBT quick copy generates references with citation keys as intended. 

Interestingly, BBT quick copy drag and drop works fine when dragging references to a word document.

So, somehow the Typora app recognizes drag and drop when using Zotero standard csl styles, but not when using drag and drop combined with BBT. 

Thanks

**Comment by retorquere** [comment]
If you select one of the standard Zotero translators (eg "Zotero RDF") as the quick copy default format, does the drag and drop work then?

**Comment by staaffy** [comment]
I can't find Zotero RDF on the list - but it seems that all the option under "export format", in the quick copy default format menu, won't work with drag and drop (so not only the BBT options), while all of the "Citation style" options work as intended. 

Sorry about that, I guess it is not an BBT issue then. Still puzzled though why copying using ctrl+shift+c works and drag and drop doesn't, when both works for the citation styles.

**Comment by retorquere** [comment]
> I can't find Zotero RDF on the list 

Huh, you're right, sorry about that.

> - but it seems that all the option under "export format", in the quick copy default format menu, won't work with drag and drop (so not only the BBT options), while all of the "Citation style" options work as intended.

That's what I wanted to know, indeed. Yeah, if those don't work, BBT Quick copy also won't, because it's using the same facility.

> Sorry about that, I guess it is not an BBT issue then. Still puzzled though why copying using ctrl+shift+c works and drag and drop doesn't, when both works for the citation styles.

No worries -- and I don't know why this is the case, it is indeed strange. You'll have to ask on the Zotero forums; if any of the export formats work, BBT Quick Copy will too.
