### ISSUE TITLE
Export of subscripted character 'x' is using unicode instead of latex commands

### ISSUE THREAD

**Issue by jlaehne** [retorquere/zotero-better-bibtex#1244]
**Report ID:**
VAJXNNZT-euc

**Exporter used:**
Better BibTeX, v5.1.127

**Expected behavior:**
"InₓGa₁₋ₓN/GaN" should be replaced by "{{In}}{\textsubscript{x}}{{Ga}}{\textsubscript{1-x}}{{N}}" or "{{In}}{$_x$}{{Ga}}{$_{1-x}$}{{N}}"

**Actual behavior:**
"InₓGa₁₋ₓN/GaN" is exported as "{{InₓGa}}{$_{1-}$}{{ₓN}}"

Besides 'x', this should work at least also for 'y' and 'z'

PS: Otherwise, I am really impressed by the unicode conversion capabilities!

**Comment by retorquere** [comment]
Do you have actual unicode samples of subscripted y and z? I need to know their character codes and I can't find them.

**Comment by retorquere** [comment]
unicode.org only has https://unicode.org/charts/PDF/U2070.pdf

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4487](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4487.xpi) ("unicode table update")

Install in Zotero by downloading [test build 5.1.127.4487](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4487.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4487 for the subscripted x?

**Comment by jlaehne** [comment]
OK, maybe subscripted y and z do not exist, because I find only the x in my database. All occurences of y are encoded as <sub>y</sub> and that is properly exported by Better BibTex.

**Comment by jlaehne** [comment]
Subscripted x works with 4487. Results in:
{{In\textsubscript{x}Ga}}{$_{1-}$}{{\textsubscript{x}N}}

The only other character in my library that is now still exported as unicode is a superscripted k: ᵏ
(Which though occurs only once in an abstract out of more than a thousand entries)

**Comment by jlaehne** [comment]
Subscripted x works with 4487. Results in:
{{In\textsubscript{x}Ga}}{$_{1-}$}{{\textsubscript{x}N}}

The only other character in my library that is now still exported as unicode is a superscripted k: ᵏ
(Which though occurs only once in an abstract out of more than a thousand entries)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4490](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4490.xpi) ("superscript k")

Install in Zotero by downloading [test build 5.1.127.4490](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4490.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jlaehne** [comment]
Works ;-)

**Comment by retorquere** [comment]
Cool, thanks -- I'm working on one more issue and then I'll cut a new release.
