### ISSUE TITLE
importing a title-cased bib

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#1246]
**Report ID:**
NNLUKD4H-apse

**Full Bib(La)TeX item you are trying to import:**

```
    @article{AdcroftETAL:1997,
      author	= "Adcroft, Alistair  and  Chris Hill
    		   and  John Marshall",
      year		= "1997",
      title		= "Representation of Topography by Shaved Cells in a
    		   Height Coordinate Ocean Model",
      journal	= "Monthly Weather Review",
      volume	= "125",
      pages		= "2293-2315"}
```

**Expected behavior:**
I need normal words in title not brace-protected.

**Actual behavior:**
Because the original title uses title case, the importer protects capitalized words and when the entry is exported, those words are protected like so

    title = {Representation of {Topography} by {Shaved} {Cells} in a {Height} {Coordinate} {Ocean} {Model}},

**Rationale/scenario**
Some publishers still use title case for their articles. See American Meteorological Society, for example (https://journals.ametsoc.org/doi/full/10.1175/JPO-D-18-0266.1 ).  If you create bib entries by copy-and-pasting or by downloading citation data from such a journal homepage, you end up with titles in title case.  I already have a giant bib file which grew like this over the years.

I was encouraged to post here by emilianoeheyns (https://forums.zotero.org/discussion/61715/prevent-extra-braces-in-bibtex-export/p2 ) .  I thank him/her for the help.

**Comment by retorquere** [comment]
You can ignore the bot message

**Comment by retorquere** [comment]
(emilianoeheyns is me BTW)

**Comment by retorquere** [comment]
I'm still working on this -- as I was going through the test cases I found a bug in the bibtex parser I used which is going to be hard to fix -- I'm almost done with a new parser, and then I can pick up the sentence casing again. I'm sorry about the delay, this is not my usual response time.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4533](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4533.xpi) ("jurism")

Install in Zotero by downloading [test build 5.1.127.4533](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4533.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4534](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4534.xpi) ("ncu")

Install in Zotero by downloading [test build 5.1.127.4534](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4534.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Man that was something. Can you try 4534?

**Comment by retorquere** [comment]
Note that the sentence-casing aims to be decent but not perfect -- I'm not doing any natural language processing, just heuristics, so you will always have to check the post-import results. Stuff from my test set comes through surprisingly well though, and if you have a counter-example I can have a look to see if I can address that.

**Comment by retorquere** [comment]
Import-export of the sample you posted now yields

```
@article{AdcroftETAL:1997,
  author = {Adcroft, Alistair and Hill, Chris and Marshall, John},
  journal = {Monthly Weather Review},
  pages = {2293-2315},
  title = {Representation of Topography by Shaved Cells in a Height Coordinate Ocean Model},
  volume = {125},
  year = {1997}
}
```

which seems reasonable to me.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4542](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4542.xpi) ("adjust test cases")

Install in Zotero by downloading [test build 5.1.127.4542](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4542.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by ryofurue** [comment]
Thank you for your hard work, @retorquere .  The example looks perfect indeed.

**Comment by ryofurue** [comment]
I downloaded the latest version of BBT, installed it onto Zotero, and imported my main collection, a large bib file.  I didn't check all the entries, but as far as I could see, the title-case problem seemed to have been all solved.  Thank you again, @retorquere  !

**Comment by retorquere** [comment]
Awesome, thanks for the follow up
