### ISSUE TITLE
Windows drive letter colon is not escaped when exporting without "Export Files" selected

### ISSUE THREAD

**Issue by karnesky** [retorquere/zotero-better-bibtex#1254]
[Reported in Zotero Forums](https://forums.zotero.org/discussion/comment/337998/#Comment_337998).

No Report ID is given; this is with default settings on a fresh install.

**Exporter Used:** Both Better BibTeX and Better BibLaTeX translators behave incorrectly.

**Expected Behavior:** The colon after a drive letter must be escaped for Zotero's importers and for JabRef to find the file. That is because both use the colon as a field separator. BBT should export `file = {C\:\\example.pdf}`. The stock Zotero translator handles this correctly, but uses JabRef-style links.

**Actual behavior:** BBT exports `file = {C:\\example.pdf}` Files are not imported because of this.

**Comment by retorquere** [comment]
Why no debug report? It will also give me a copy of the references you're trying to export.

**Comment by karnesky** [comment]
I can generate one if you need it, but I would have to do so from a personally-owned machine, rather than a corporate-owned machine & I don't have easy access to a personally-owned Windows box. This was also reported in the Zotero forums, so perhaps we can get the original user to submit one if you're really waiting on this...

**Comment by retorquere** [comment]
Alright, I'll have a look.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4536](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4536.xpi) ("fixes #1254")

Install in Zotero by downloading [test build 5.1.127.4536](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4536.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Sorry for the delay -- #1246 required a major overhaul of the bibtex importer.

The behavior in BBT was configurable -- if you have JabRef compatibility set, the `:` was escaped. I'm not sure who else uses the format but 4536 just always escapes the `:`, regardless of the JabRef compatibility setting.

I can unfortunately not test this as I don't have access to a Windows machine.

**Comment by karnesky** [comment]
Tested & confirmed working.

**Comment by retorquere** [comment]
Thanks for the confirmation. label-gun keeps issues open until I've merged them so I don't forget.
