### ISSUE TITLE
Exporting to bibtex with unicode as plain-text latex commands doesn't convert U+2040

### ISSUE THREAD

**Issue by jerryangit** [retorquere/zotero-better-bibtex#1265]
**Report ID:** CRR4MW4Z-euc

**Exporter used:** BibTeX

**Expected behavior:** Tretʹi︠a︡kov is converted to Tret'\t{ia}kov

**Actual behavior:** Tret'i︠a︡kov is converted to Tret'i︠a︡kov

**Comment by retorquere** [comment]
Can you right-click a reference that has this and send a new debug log? That will give me a test case.

**Comment by retorquere** [comment]
Your postscript isn't javascript BTW.

**Comment by retorquere** [comment]
No I mean in the BBT settings for postscript you've entered

```
<script>
@techreport{ISO3780,
type = {Standard},
key = {ISO 3780:2009},
month = oct,
year = {2009},
title = {{Road Vehicles -- Vehicle Identification Number ({VIN}) -- Content and Structure}},
volume = {2009},
address = {Geneva, CH},
institution = {International Organization for Standardization}
}
</script>
```

where BBT expects there to be javascript code.

The sample you submitted doesn't have `\u2040`, it has `\u0069\ufe20\u0061\ufe21`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.131.4590](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.131.4590.xpi) ("fixes #1265")

Install in Zotero by downloading [test build 5.1.131.4590](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.131.4590.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4590?

**Comment by retorquere** [comment]
Thanks for the confirmation -- only I can close issues, I need the reminder to include them in a new release.
