### ISSUE TITLE
automatic tags in export

### ISSUE THREAD

**Issue by clarino** [retorquere/zotero-better-bibtex#1270]
Export of items to BibLaTeX results in inclusion of the following bogus line:
  keywords = {⛔ No DOI found},

Application: Zotero 5.0.74 en-US
Platform: MacIntel Intel Mac OS X 10.14
Addons: Better BibTex for Zotero (5.1.136, extension)

**Comment by clarino** [comment]
The item to be exported is the following.

    NorGramBank: A `Deep' Treebank for Norwegian
    Type 	Conference Paper
    Author 	Helge Dyvik
    Author 	Paul Meurer
    Author 	Victoria Rosén
    Author 	Koenraad De Smedt
    Author 	Petter Haugereid
    Author 	Gyri Smørdal Losnegaard
    Author 	Gunn Inger Lyse
    Author 	Martha Thunes
    Editor 	Nicoletta Calzolari
    Editor 	Khalid Choukri
    Editor 	Thierry Declerck
    Editor 	Marko Grobelnik
    Editor 	Bente Maegaard
    Editor 	Joseph Mariani
    Editor 	Asunción Moreno
    Editor 	Jan Odijk
    Editor 	Stelios Piperidis
    URL 	http://www.lrec-conf.org/proceedings/lrec2016/summaries/943.html
    Pages 	3555-3562
    Date 	2016
    Extra 	Citation Key: Dyvik16 bibtex*[organization=ELRA;isbn/issn=978-2-9517408-9-1] event-place: Portorož, Slovenia
    Proceedings Title 	Proceedings of the Tenth International Conference on Language Resources and Evaluation (LREC'16)
    Date Added 	25/02/2019, 22:04:13
    Modified 	14/03/2019, 01:56:56
    Tags:
        ⛔ No DOI found

**Comment by clarino** [comment]
It seems that tags are exported as keywords, but that does not seem correct. In any case, the message about "No DOI found" is not a keyword.

**Comment by retorquere** [comment]
You're the first to say that exporting tags as keywords is not correct. I don't control what people put in their tags, so I can't judge what is or isn't supposed to be a keyword. If you don't want keywords at all, you can have BBT omit the field. 

If you export a debug report as requested above, I can see if I can distinguish between the kinds of tags the doi manager puts in and others.

**Comment by clarino** [comment]
To be fully clear, I did not add the tag about "No DOI found" to the item. It seems to be generated automatically. I DO want keywords in the bibliographic sense, but this is definitely not one.
I submitted a debug report with ID 36UVGIIG-euc

**Comment by retorquere** [comment]
I understand that, but the DOI manager did so on your behalf -- the tag is there. I'm going to see if I can distinguish between such tags and the ones you create manually; the DOI manager might have labelled them as automatic tags, and then I can make it so that BBT doesn't export those.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.136.4622](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.136.4622.xpi) ("keep tag types")

Install in Zotero by downloading [test build 5.1.136.4622](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.136.4622.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
>     * If your issue relates to how BBT behaves around a **specific reference(s)**, such as citekey generation or export, select at least one of the problematic reference(s), right-click it, and submit an BBT debug report from that popup menu. If the problem is with export, please do include a sample of what you see exported, and what you expected to see exported for these references.

I need a debug report generated by this procedure, not the one from the help menu.

Can you install 4622 that @blip-bloop just announced above and send a new debug report uding the above procedure?

**Comment by retorquere** [comment]
I've tried it myself but the tags from the DOI manager show up as user-entered tags, so I cannot distinguish them from the ones you entered manually. I've opened an issue on the shortdoi manager (https://github.com/bwiernik/zotero-shortdoi/issues/16) but until that is changed, I can't really do anything.

**Comment by clarino** [comment]
Thanks so far. Tags added as notifications by the system are logically very different from keywords added by the user describing the content of the item for indexing purposes, so I hope a solution will be found to keep them apart.

**Comment by retorquere** [comment]
There is a solution to keep them apart (tags can be marked as `automatic` and BBT can see whether they are), but in this case, ShortDOI doesn't yet mark them this way.

I'm waiting for the UI translations to come in but then I'll release a BBT version that allows you to select whether you want automatic tags in the export or not -- that's all I can do because I can't tell anything else about the tags other than their text and whether they're automatic or not.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.136.4634](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.136.4634.xpi) ("tests for #1270")

Install in Zotero by downloading [test build 5.1.136.4634](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.136.4634.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
