### ISSUE TITLE
Not exporting new Better BibTex entries

### ISSUE THREAD

**Issue by beatrizsantos15** [retorquere/zotero-better-bibtex#1277]
I've used Zotero for a year together with LaTeX, to automatically compile my bibliography. It always worked, but now I haven't used it for around 3 months and it has stopped exporting the papers I add to Zotero to Better BibTex. I've tried to export the library and do an automatic export manually, but it still doesn't work. In LaTeX I get the message " `citation Yalcin 2017b ' is not defined" and ``I didn't find a database entry for "Yalcin2007b". Now an exclamation point has also appeared next to the green arrow, giving this error message: "Group with libraryID 1 does not exist". 
I have this code in my TeX file in order to get the bibliography automatically exported:
\bibliographystyle{C:/texmf/bibtex/bst/Analysis} %%bib style found in bst folder, in bibtex folder, in texmf folder.
\setlength{\bibsep}{0.5pt} %%Changes spacing between bib entries
\bibliography{C:/texmf/bibtex/bib/Zotero} %%bib database found in bib folder, in bibtex folder

I realised now that the problem is that TeX Bibliography document I've called "Zotero" hasn't been updated through Zotero since a month ago. What I need to know, then, is how to make Zotero automatically update this document again?

REPORT ID: 1440684922

**Comment by retorquere** [comment]
I can't access Zotero debug reports, I need a BBT-specific report (ending in `-euc` or `-apse`), available either under the item right-click menu (if it's to do with exporting of specific items) or the help menu (for anything else).

**Comment by retorquere** [comment]
> I've tried to export the library and do an automatic export manually, but it still doesn't work.

What doesn't work? When you manually export your library, do you see the new entries?

> In LaTeX I get the message " `citation Yalcin 2017b ' is not defined" and ``

I don't know what causes this message, but the space makes me think you may have mistyped something?

> I didn't find a database entry for "Yalcin2007b". 

So do you have an entry with citekey `Yalcin2007b` in Zotero? If you export your library manually, does it show up?

> Now an exclamation point has also appeared next to the green arrow, giving this error message: "Group with libraryID 1 does not exist".

This is a problem with Zotero sync. I don't know what causes it, but this sounds like there may be something wrong with your database. If there's something wrong with your database, BBT could be affected by this.

> I have this code in my TeX file in order to get the bibliography automatically exported:

```
\bibliographystyle{C:/texmf/bibtex/bst/Analysis} %%bib style found in bst folder, in bibtex folder, in texmf folder.
\setlength{\bibsep}{0.5pt} %%Changes spacing between bib entries
\bibliography{C:/texmf/bibtex/bib/Zotero} %%bib database found in bib folder, in bibtex folder
```

this doesn't cause automatic exports though. It may rely on them, but can't cause them.

> I realised now that the problem is that TeX Bibliography document I've called "Zotero" hasn't been updated through Zotero since a month ago. What I need to know, then, is how to make Zotero automatically update this document again?

Do you have an existing auto-export in your BBT prefs?

**Comment by retorquere** [comment]
It is not related to BBT?
