### ISSUE TITLE
Once autopin is on, how to force it on existing library

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#1290]
In the title: I've just turned the hidden autopin pref on. Now how do I get my entire library autopinned? I tried to regenerate the cite keys on items, but that didn't seem to do it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.140.4779](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.140.4779.xpi) ("auto-pin even if key does not change")

Install in Zotero by downloading [test build 5.1.140.4779](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.140.4779.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
auto-pinning only actually pinned when the key changed. Can you try 4779?

**Comment by Jmuccigr** [comment]
OK, that seemed to work after I used the contextual menu to "Refresh BibTEX key". Zotero was taking a while to prepare to sync with the server, so I quit it, but the keys hhadve all turned non-Italic fairly quickly. After starting it again, the sync happened pretty quickly and all the keys seem pinned.

**Comment by retorquere** [comment]
That's the downside -- the act of pinning the keys changes the item, so they'll be synced anew to Zotero.

**Comment by retorquere** [comment]
A new release is out, Zotero will upgrade it automatically.
