### ISSUE TITLE
Cite as you write support for selected items?

### ISSUE THREAD

**Issue by anjiro** [retorquere/zotero-better-bibtex#1302]
Is there a way to get the same information, in the same way, from "Cite As You Write", but for the items selected in Zotero rather than via the citation popup?

**Comment by retorquere** [comment]
not exactly, but http://localhost:23119/better-bibtex/select?jzon (zotero item format) or http://localhost:23119/better-bibtex/select?a515a220-6fef-45ea-9842-8025dfebcc8f (BBT quick copy) might get you close enough.

**Comment by anjiro** [comment]
Perfect, the item format one will let me do my own formatting.
