### ISSUE TITLE
The `#` special character in url field of reference throws error. 

### ISSUE THREAD

**Issue by phargarten2** [retorquere/zotero-better-bibtex#1305]
Similar to issue #18, I generated the following reference from Zotero using Better BibLaTex. But, this reference has a `#` in the url field:

```
@reference{barnardMultipleImputation2015,
  langid = {english},
  title = {Multiple {{Imputation}}},
  isbn = {978-0-08-097087-5},
  url = {http://www.sciencedirect.com/science/referenceworks/9780080970875#ancpt1035},
  booktitle = {International {{Encyclopedia}} of the {{Social}} \& {{Behavioral Sciences}}},
  publisher = {{Elsevier Ltd. A}},
  urldate = {2016-05-31},
  date = {2015},
  pages = {88--93},
  keywords = {vignette},
  author = {Barnard, John and Schenker, Nathaniel and Rubin, D.B.},
  file = {/Users/Shared/Zotero/storage/KVN4EFLD/John Barnard et al. - 2015 - Multiple Imputation.pdf}
}
```
Attempting to LaTech it gives the following error

> ! Illegal parameter number in definition of \Hy@tempa.
> <to be read again> 
>                 a
> l.14 

A simple solution that upon exporting that all `#` are preceded by a backslash, i.e. `\#`.  In my example, the url field will look like:
```
url = {http://www.sciencedirect.com/science/referenceworks/9780080970875\#ancpt1035}
```

Any use of the resulting bib file precedes without an error. 

Report ID #: NRAB3DLJ-euc

**Comment by phargarten2** [comment]
Report ID #: NRAB3DLJ-euc

**Comment by retorquere** [comment]
I don't know how it happened, but there are no items in NRAB3DLJ-euc. Can you right-click that item and try sending the BBT debug log again?

**Comment by retorquere** [comment]
I don't doubt you're seeing this error, but according to the biblatex manual:

> URI fields are processed in verbatim mode and may contain special characters. They are also URL-escaped if they don’t look like they already are.The typical example of a uri field is url

I've just compiled the MWE below on overleaf and it compiles without error for me, and the URL shows as expected:

```
\documentclass{article}

\usepackage[american]{babel}
\usepackage[style=authoryear]{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{test.bib}
@reference{barnardMultipleImputation2015,
  langid = {english},
  title = {Multiple {{Imputation}}},
  isbn = {978-0-08-097087-5},
  url = {http://www.sciencedirect.com/science/referenceworks/9780080970875#ancpt1035},
  booktitle = {International {{Encyclopedia}} of the {{Social}} \& {{Behavioral Sciences}}},
  publisher = {{Elsevier Ltd. A}},
  urldate = {2016-05-31},
  date = {2015},
  pages = {88--93},
  keywords = {vignette},
  author = {Barnard, John and Schenker, Nathaniel and Rubin, D.B.},
  file = {/Users/Shared/Zotero/storage/KVN4EFLD/John Barnard et al. - 2015 - Multiple Imputation.pdf}
}
\end{filecontents*}
\addbibresource{test.bib}
\begin{document}

\nocite{*}

\printbibliography

\end{document}
```

**Comment by retorquere** [comment]
hello?

**Comment by phargarten2** [comment]
I was at a conference so sorry for the late response. As suggested, I hit "Help -> Report Error" , which gave me this Report ID: 723588222 . Please let me know if this was incorrect

I am using the **knitr** package in Rmarkdown in Rstudio to cite and reference the BibLaTex file produced by the Zotero extension. LaTeX within Rstudio had trouble running when the '#' was present in the URL field. Apparently, there may be no issue, but I wanted to post this so that you are aware.

Again thank you for the quick response

**Comment by retorquere** [comment]
Ah, that's a Zotero error report, I can't see those. I need one when you right-click the item that has this url with the hash, then from the popup menu that appears, select "send bbt debug log".

But if you're using knitr with rmarkdown, you're actually using pandoc under the hood. I'm not sure what template document rmarkdown/pandoc uses, or even whether it uses bibtex or biblatex, and those things make a major difference.

**Comment by retorquere** [comment]
> I am at a statistical conference so sorry for the late response.

This conjures up images of "statistical persons" vs individuals and I'm trying to piece together what a statistical conference would look like 😄 .

[ba-dum tss](https://ba-dum-tss.com/) I get it though. What conference?

**Comment by retorquere** [comment]
Where are we on this?

**Comment by phargarten2** [comment]
I submitted the bug report with ID USH59QJK-euc .  


I went to Biopharmaceutical Applied Statistics Symposium (BASS) -- it is just a bunch of people talking about statistics.

**Comment by phargarten2** [comment]
I know that I am using **pandoc** and the issue could be them. However, I ran into this issue and thought that you should know about it. I was able to fix it by adding the escape character `\` in front of the `#` sign ... I suppose that **pandoc** was expecting the `#` as a command instead.

**Comment by retorquere** [comment]
Adding the `\` in front of the `#` makes it so that pandoc will consume it, but pandoc is simply wrong here. It is not supposed to be consistent this way across the bibtex file, because `url` is a verbatim field, which is treated differently by bib(la)tex; other rules apply to verbatim fields, one of which being that `#` and some other characters should not be escaped. That's "should not", not "don't have to be".

If you compile this:

```
\RequirePackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@reference{barnardMultipleImputation2015,
  langid = {english},
  title = {Multiple {{Imputation}}},
  isbn = {978-0-08-097087-5},
  url = {http://www.sciencedirect.com/science/referenceworks/9780080970875\#ancpt1035},
  booktitle = {International {{Encyclopedia}} of the {{Social}} \& {{Behavioral Sciences}}},
  publisher = {{Elsevier Ltd. A}},
  urldate = {2016-05-31},
  date = {2015},
  pages = {88--93},
  keywords = {vignette},
  author = {Barnard, John and Schenker, Nathaniel and Rubin, D.B.},
  file = {/Users/Shared/Zotero/storage/KVN4EFLD/John Barnard et al. - 2015 - Multiple Imputation.pdf}
}
\end{filecontents*}

\documentclass{article} 
\usepackage[%
  backend=bibtex   % use BibTeX
% backend=biber    % Use biber
]{biblatex} 
\addbibresource{\jobname.bib}
\begin{document} 
Hello \cite{barnardMultipleImputation2015}. How are you?
\printbibliography 
\end{document} 
```

you will see that the backslash shows up in the rendered output. This is not what you want.

When using pandoc, I'd recommend using "Better CSL JSON" or "Better CSL YAML", which sidesteps this pandoc bug. Alternately, you can add the backslash automatically with a postscript, but that will mean that when you actually use LaTeX, the output will be wrong.

**Comment by phargarten2** [comment]
Perhaps this bug should be reported to pandoc; nonetheless, a workaround exists within Zotero Better Bibtex.

**Comment by retorquere** [comment]
I think it should, and I'll give input where it helps, but I'd prefer it if you could report it. I don't actually use pandoc much, and it's better if an actual user reports the issue.

Indeed, a postscript can automate inserting the backslash as a workaround.
