### ISSUE TITLE
BibTeX export does not store "References" field from WOS/Scopus

### ISSUE THREAD

**Issue by mlcanales** [retorquere/zotero-better-bibtex#1312]
Input Data: [BBT.zip](https://github.com/retorquere/zotero-better-bibtex/files/3780917/BBT.zip)
Export (after clean up with Zotero): 
[Articles.zip](https://github.com/retorquere/zotero-better-bibtex/files/3780922/Articles.zip)

I imported both a WOS and Scopus ".bib" files into a Zotero group. Than, after duplicates elimination, I try to export the library that resulted as a BibTeX file. However, the "References" column (i.e. the bibliography of each article), part of the original imported BibTeX files, disappears (i.e. I get an uncompleted BibTeX file).
I understand Zotero has no formal way to store references of items, so I would lose those in any import/export process. So, any way to work this around ??

Thanks !!

**Comment by retorquere** [comment]
I'll need samples of those "WOS" and Scopus bib files.

**Comment by retorquere** [comment]
Can you pick out one or two references that have the fields you want? I intend to add the samples to my test suite, and I'd rather not add this many if I don't have to.

**Comment by retorquere** [comment]
From the looks of it, `references` contains formatted bibliographies, I assume a list of papers cited by the article in question. I first assumed it would be citekeys. This could perhaps be imported as a note, I don't see much value in round-tripping this in bibtex im-export.

**Comment by mlcanales** [comment]
Yes of course, here is a better test sample:
[Scopus and WOS.zip](https://github.com/retorquere/zotero-better-bibtex/files/3780949/Scopus.and.WOS.zip)
The field is called "Cited references" or "references" in WOS ("savedrecs.BibTeX") and Scopus ("scopus.BibTeX") files respectively-

**Comment by mlcanales** [comment]
It would be great to have a BibTeX file at the end of this process (after mixing both databases and removing duplicates), that is why I am trying to do this with Zotero.

**Comment by retorquere** [comment]
Zotero is not the best tool for round-tripping bibtex data, even with BBT installed. you want to mix bibtex databases and you want to incur zero loss, you're better off with JabRef.

**Comment by retorquere** [comment]
BBT will already import this and retain the fields on export. I could look at retaining these fields on duplicate merge, but if it's actual duplicate removal, BBT should already do what you want.
