### ISSUE TITLE
better bibtex hanging, making zotero slow and completely taking over one CPU

### ISSUE THREAD

**Issue by averter** [retorquere/zotero-better-bibtex#1314]
**Report ID:**
AZM5SSYI-euc

**Expected behavior:**
Normal startup of Better Bibtex

**Actual behavior:**
Similar to what has been described in [this](https://github.com/retorquere/zotero-better-bibtex/issues/1313) issue, Better bibtex shows a "Better BibTeX initializing, Waiting for Zotero translators" window indefinitely, takes over a cpu core and slows Zotero down overall.

**Comment by retorquere** [comment]
You're on Zotero 5.0.60. You need to upgrade to 5.0.76 before I can look into this, I only support the latest release of Zotero. BBT is pretty intimately tied to the Zotero internals, and hooks into a few unofficial places in Zotero; Zotero is free to change those at will and I need to follow.

**Comment by averter** [comment]
Sorry again. I've update now and this is the new ID: DCV4WRVD-euc

**Comment by retorquere** [comment]
Seems like Zotero doesn't give the go-ahead for the translator load, and in the interim, BBT is doing something with the half-initialized state. I'm adding more logging to BBT, will take me a bit.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5036](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5036.xpi) ("trace all the things")

Install in Zotero by downloading [test build 5.1.151.5036](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5036.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5037](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5037.xpi) ("enable #trace logging")

Install in Zotero by downloading [test build 5.1.151.5037](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5037.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by averter** [comment]
It's getting worse. After installing the test build I cannot see better bibtex in the add-ons menu. Furthermore I cannot see a debug report. It just hangs endlessly with the menu `Please wait while the debug report is submitted` and at some point I get an error `Error: Request timed out (JWVH4IRF-euc, references: false)`

**Comment by retorquere** [comment]
This is an instrumented build that logs like crazy, so that's going to impact performance, this is not something that would show up in release builds. 

Can you start Zotero using `zotero -ZoteroDebugText > zotero.log, wait until you've seen "Waiting for zotero translators", wait 5 more seconds, then just kill Zotero and get me `zotero.log`.

**Comment by averter** [comment]
Here it is [zotero.log](https://gist.github.com/averter/e396bd3a7f8ce427b5901b78fe591728)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5040](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5040.xpi) ("partial #trace")

Install in Zotero by downloading [test build 5.1.151.5040](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5040.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
A lot is going on in BBT while it is waiting for Zotero... can you get me a new log with 5040?

**Comment by averter** [comment]
Same issue still `Error: Request timed out (ZFDLLA3G-euc, references: false)` and here is the new [zotero.log](https://ufile.io/7vu62xxy) (side note: for some reason my gists are developing unicorns, possibly because the log files are very large)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5041](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5041.xpi) ("track pending getcelltext")

Install in Zotero by downloading [test build 5.1.151.5041](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5041.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you see if 5041 is better? This removes the trace logging and has at least a fix for one potential culprit. If not, I need to get you a new trace build.

**Comment by averter** [comment]
Many thanks for your your effort. With 5041 I still get the same result. The new log is [here](https://ufile.io/4jwb4nae)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5043](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5043.xpi) ("#trace again")

Install in Zotero by downloading [test build 5.1.151.5043](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5043.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by averter** [comment]
Well done! Better bibtex is not hanging anymore and the debug report is sent. ID is RHT5NG7D-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5044](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5044.xpi) ("remove tracing")

Install in Zotero by downloading [test build 5.1.151.5044](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5044.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
In that case, 5044 should be even better, because that doesn't have the trace logging.

**Comment by averter** [comment]
Here it is: VJ2NK2ZI-euc 
For some reason the "citekey" column displays only interrogation marks in the folder where I was working. I've tried to pin new Bibtex keys but nothing changed.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.151.5049](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5049.xpi) ("wait until full load of zotero before showing cite keys")

Install in Zotero by downloading [test build 5.1.151.5049](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.151.5049.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by averter** [comment]
Yep, everything seems to be working now. In case you need it, here is the current debug report ID: QJGRQJ28-euc

**Comment by retorquere** [comment]
I've removed all tracing so the log will be pretty quiet -- if you're happy with the current performance then that's good enough for me. I found one problem that would clearly cause this and which was introduced recently, and that should now be fixed. I'm cutting a new release for this, you'll be upgraded automatically, but it'll just be what you have now.

**Comment by averter** [comment]
Great. I'll close it now then. Thank you for the excellent work.

**Comment by retorquere** [comment]
Only I can close issues here :)

**Comment by retorquere** [comment]
(it's so that I don't forget to fold fixes into a release)
