### ISSUE TITLE
ID not saved to Better CSL JSON file

### ISSUE THREAD

**Issue by ArcticSnow** [retorquere/zotero-better-bibtex#1316]
I freshly installed Zotero and the plugin Better-bibtex to export a *Better CSL JSON* file hoping to get unique id key for each citation to be used in Zettlr for example. The problem is that everytime I try to export my library using better-bibtex, the final json file has empty ID fields for each reference (where it should have unique identifier). In Zotero itself, the unique identifier created by the plugin appear though.

My system is a linux mint (Ubuntu based) OS. I tried to install and follow the same workflow in Mac OS which work just fine. Could there be a bug specific to the linux version?

Thanks

**Comment by ArcticSnow** [comment]
Ok just found a solution.

Go to **Zotero Preferences** > **Better Bibtex** tab > **Automatic export** tab. Then click the button **Export now** which updated the CSL json file. 

This was not necessary on Mac OS. Maybe a difference linux vs. Mac.

**Comment by retorquere** [comment]
No that's definitely a bug. There should be no difference between MacOS and Linux (and my automated tests all run on Linux).

**Comment by retorquere** [comment]
Is this replicable for you? If so, a debug log might tell me more.

**Comment by retorquere** [comment]
Did you perhaps set up the auto-export before the BBT init finished?

**Comment by retorquere** [comment]
I've started on Linux and I cannot reproduce the problem.

**Comment by retorquere** [comment]
Hello?

**Comment by Sisi-Wiciel** [comment]
I got the same error on manjaro. And I tried the solution, it worked. The debug report ID:7LMPUG2L-apse

> Ok just found a solution.
> 
> Go to **Zotero Preferences** > **Better Bibtex** tab > **Automatic export** tab. Then click the button **Export now** which updated the CSL json file.
> 
> This was not necessary on Mac OS. Maybe a difference linux vs. Mac.

**Comment by retorquere** [comment]
There's no indication of an export being done in 7LMPUG2L-apse.

**Comment by retorquere** [comment]
Re-doing the export via auto-export isn't a solution, it's a workaround. I can't reproduce the problem on Ubuntu, and I'd prefer to fix it rather than having people having to go through workarounds.

**Comment by retorquere** [comment]
@Sisi-Wiciel how did you do the export that misses the citekeys? Was that an auto-export, where subsequent exports succeeded? Or was the failing export a normal export, and did setting up an auto-export give you an export with citekeys, also on the export that set up the auto-export rather than retriggering? I don't know the exact scenario. 

If you can reproduce the problem, please turn on debug logging in `Help`, then reproduce, then send a debug log, that will give me some ideas on what's the state during export.

**Comment by retorquere** [comment]
Guys, you're killing me. I need a debug log generated while the problem occurred. I can't reproduce it myself so I have nothing to go on.

**Comment by Sisi-Wiciel** [comment]
So sorry. when I go back home, I will try to reproduce the bug

**Comment by retorquere** [comment]
So...

**Comment by retorquere** [comment]
Guys... really cannot help you without that log...

**Comment by Sisi-Wiciel** [comment]
So soooooorry. I had sent the log.
![2019-11-15_15-26](https://user-images.githubusercontent.com/21168981/68924696-57698280-07bc-11ea-9de1-be69ec4ed69f.png)

**Comment by retorquere** [comment]
I'm not notified for log uploads (nor would I be able to tell which log goes with which issue); the debug log ID is actually selectable, so you can copy-paste just the debug ID rather than a screenshot (also easier for me).

How many items are in this export? From the logs it would seem it didn't export any.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.160.5151](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5151.xpi) ("trace logging")

Install in Zotero by downloading [test build 5.1.160.5151](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5151.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you do the same thing to produce a log but with the 5151 build from above?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.161.5170](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.161.5170.xpi) ("Merge branch 'master' into gh-1316")

Install in Zotero by downloading [test build 5.1.161.5170](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.161.5170.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Come on people, help me help you.

**Comment by Sisi-Wiciel** [comment]
well, I am trying.

**Comment by retorquere** [comment]
I'll need a new debug log from 5170, which adds more logging.

How many items were in the export you made in the previous log? The logs made it seem like it didn't export any.

**Comment by Sisi-Wiciel** [comment]
Well, I  have sent the debug log
![2019-11-15_15-26](https://user-images.githubusercontent.com/21168981/68998479-b1b63080-08ed-11ea-8f42-885d4f02b715.png)

**Comment by Sisi-Wiciel** [comment]
This is my references.
![2019-11-17_03-49](https://user-images.githubusercontent.com/21168981/68998520-1f625c80-08ee-11ea-8544-51c8df3bbdf4.png)

**Comment by retorquere** [comment]
That screen explicitly states that I can't see the logs unless you tell me the debug ID. I am not notified of new logs being sent. I appreciate the logs being sent, but I *have* to be notified here on github.

You double-click the red ID and copy the text, you can paste just the ID.

I will have a look at the log.

**Comment by retorquere** [comment]
Wait, that's the log you sent previously with 5.1.158. I need you to install [test build 5.1.161.5170](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.161.5170.xpi) and generate a new log. I did say this [earlier](https://github.com/retorquere/zotero-better-bibtex/issues/1316#issuecomment-554302434). I cannot reproduce this, so if I'm going to fix this, I will need more logging.

**Comment by retorquere** [comment]
(I mean generate a new log and post the ID here. I cannot tell that you have uploaded a new log, and logs are automatically discarded if I don't fetch them within a week)

**Comment by retorquere** [comment]
@ArcticSnow can you reproduce the problem? If so can you do so after installing 5170 and send a debug log?

I cannot stress enough how important these logs are. Since I have not been able to reproduce the problem on my own Linux system, I need to get an idea what Zotero is doing on your systems that might produce this effect. The test build has extensive logging so it should give me a better picture if what's happening, but without such a log, I can do absolutely nothing, which, to be frank, is quite frustrating.

**Comment by retorquere** [comment]
I'd be happy to fix this, but without a **new** log from the special build **5170**, I simply cannot do anything. I cannot fix a problem for which there is no clear cause and no means to reproduce.
