### ISSUE TITLE
better biblatex translator issue: "director" field 

### ISSUE THREAD

**Issue by moritzklenk** [retorquere/zotero-better-bibtex#1317]
Hi, when exporting "movies" or "video recording" document types the "director" field is mapped to 
`director = {};`
instead, as far as I read from the biblatex-chicago guide, shouldn't it translate to:

```
editor = {};
editortype = {director}

```
or something like this?

with the existing translator, directors don't show up at all, when using biblatex-chicago style. at least I haven't found a way to make it so.

I am sorry, if this is not a bug but how it is supposed to be. in this case I would be extremely grateful for any advice...

**Comment by retorquere** [comment]
I really do need that debug report as per the first bullet point. It ensures we're looking at the same situation.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.153.5084](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.153.5084.xpi) ("fixes #1317")

Install in Zotero by downloading [test build 5.1.153.5084](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.153.5084.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
