### ISSUE TITLE
Keep keys unique freezes with read-only shared DBs/groups

### ISSUE THREAD

**Issue by maehr** [retorquere/zotero-better-bibtex#1320]
When I try to keep my keys unique across all databases BTT crashes. I guess it tries to change keys in a read-only group database that I joined https://www.zotero.org/groups/113737/doing_digital_humanities_-_a_dariah_bibliography

To make it work again I had to delete my zotero profile locally and recreate/sync it with zotero.org.

**Report ID:**

BBT "freezes" before I can do step `6. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu` and the settings menu goes blank completely.

I can reproduce this behaviour on zotero 5.0.77 on macOS 10.14.6 and Ubunut 19.10 with the latest release of BBT.

**Exporter used:**

Error-log
```
Timestamp: 07.11.2019 10:15:34
Error: {better-bibtex! +18} Better BibTeX load failed <Error: Cannot edit item in read-only library Doing Digital Humanities - A DARIAH Bibliography#
Error: Cannot edit item in read-only library Doing Digital Humanities - A DARIAH Bibliography
    Zotero.DataObject.prototype.editCheck@chrome://zotero/content/xpcom/data/dataObject.js:812:11
    Zotero.DataObject.prototype._initSave<@chrome://zotero/content/xpcom/data/dataObject.js:937:5
    tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16
    module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:18
    module.exports/Promise.coroutine/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:201:9
From previous event:
    captureStackTrace@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/debuggability.js:829:23
    CapturedTrace@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/debuggability.js:721:5
    longStackTracesCaptureStackTrace@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/debuggability.js:400:19
    module.exports/Promise.prototype._then@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:232:9
    module.exports/Promise.prototype._passThrough@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/finally.js:94:12
    module.exports/Promise.prototype.finally@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/finally.js:103:12
    PromiseSpawn@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:36:25
    module.exports/Promise.coroutine/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:197:21
    ["./db/upgrade.ts"]/upgrade/<@chrome://zotero-better-bibtex/content/common.js:56916:23> 
```

Debug-log
```
(3)(+0000004): {better-bibtex +84} dbUpgrade: old= 00036 bibtex: Wolfe2008Annotations biblatexdata[journaltitle=International Journal of Computer-Supported Collaborative Learning;langid=english;shortjournal=Computer Supported Learning]

(3)(+0000004): {better-bibtex +4} dbUpgrade: new= Citation Key: Wolfe2008Annotations tex.journaltitle= International Journal of Computer-Supported Collaborative Learning tex.langid= english tex.shortjournal= Computer Supported Learning 00036

(1)(+0000010): Rolled back DB transaction rKkUVKof

(1)(+0000004): Cannot edit item in read-only library Doing Digital Humanities - A DARIAH Bibliography

(1)(+0000006): {better-bibtex! +18} Better BibTeX load failed <Error: Cannot edit item in read-only library Doing Digital Humanities - A DARIAH Bibliography# Error: Cannot edit item in read-only library Doing Digital Humanities - A DARIAH Bibliography Zotero.DataObject.prototype.editCheck@chrome://zotero/content/xpcom/data/dataObject.js:812:11 Zotero.DataObject.prototype._initSave<@chrome://zotero/content/xpcom/data/dataObject.js:937:5 tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16 module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:18 module.exports/Promise.coroutine/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:201:9 From previous event: captureStackTrace@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/debuggability.js:829:23 CapturedTrace@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/debuggability.js:721:5 longStackTracesCaptureStackTrace@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/debuggability.js:400:19 module.exports/Promise.prototype._then@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:232:9 module.exports/Promise.prototype._passThrough@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/finally.js:94:12 module.exports/Promise.prototype.finally@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/finally.js:103:12 PromiseSpawn@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:36:25 module.exports/Promise.coroutine/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:197:21 ["./db/upgrade.ts"]/upgrade/<@chrome://zotero-better-bibtex/content/common.js:56916:23>
```

**Expected behavior:**

BBT makes sure that keys are unique across all databases (and does not try to overwrite read-only keys).

**Actual behavior:**

BBT tries to overwrite read-only keys and crashes.

**Comment by maehr** [comment]
@retorquere 

BBT "freezes" before I can do step 6. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu and the settings menu goes blank completely.

I can reproduce this behaviour on zotero 5.0.77 on macOS 10.14.6 and Ubunut 19.10 with the latest release of BBT.

**Comment by retorquere** [comment]
Damn, sorry about that. I'll have a fix later tonight. The db upgrade is not optional though. I can make it so the upgrade doesn't fail even when it doesn't execute for a group, but the group will need to upgrade too if it has custom fields or pinned keys. If it's just old style pinned keys I can work around that, but custom fields not.

**Comment by retorquere** [comment]
(note to self, try-catch around upgrade per group/library)

**Comment by maehr** [comment]
And I finally figured how to generate the report.

V2KLLIZR-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.154.5092](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.154.5092.xpi) ("skip read-only items in dbUpgrade")

Install in Zotero by downloading [test build 5.1.154.5092](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.154.5092.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by maehr** [comment]
>  this is your friendly neighborhood build bot announcing [test build 5.1.154.5092](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.154.5092.xpi) ("skip read-only items in dbUpgrade")
> 
> Install in Zotero by downloading [test build 5.1.154.5092](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.154.5092.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

works like a charm!

**Comment by retorquere** [comment]
Cool, a new release build is running.
