### ISSUE TITLE
How to export non-numeric "issue" field of journal article as "number" field in BIB reference?

### ISSUE THREAD

**Issue by ailiop** [retorquere/zotero-better-bibtex#1323]
**Report ID:** X82SY2H4-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** Non-numeric `issue` field in journal article item should get exported in the `number` reference field.

**Actual behavior:**  The `issue` item field gets exported in the `issue` reference field.

--------------------------

It seems that the way Better BibLaTeX exports the `issue` field of a Journal Article item depends on whether or not the the field value is numeric: if it is, it gets exported in the `number` reference field; otherwise, in the `issue` field.

I can see that being reasonable behaviour in general, but I would like to override it and have the item `issue` be exported into the reference `number` even when it is non-numeric.  I tried doing that by adding the following postscript:

    if (Translator.BetterTeX) {
      if (item.itemType == 'journalArticle' && item.has.issue) {
        reference.remove( 'issue' );
        reference.add( {name: 'number', value: item.issue} );
      }
    }

and some variations thereof, but could not get it to work.  Could you please help?

**Comment by retorquere** [comment]
close, but `has` lives on the `reference` being built, not the source `item`:

```
if (Translator.BetterTeX) {
  if (item.itemType == 'journalArticle' && reference.has.issue) {
    reference.remove( 'issue' );
    reference.add( {name: 'number', value: item.issue} );
  }
}
```

**Comment by ailiop** [comment]
That works.  I was sure I had tried that, but apparently I was wrong...

Thanks a lot!  For your help here and in general for this project.  :)

**Comment by retorquere** [comment]
You're very welcome.
