### ISSUE TITLE
BBT chrashes during Initialization

### ISSUE THREAD

**Issue by Isimoro** [retorquere/zotero-better-bibtex#1326]
Report ID: R6IC8BZ4-euc

As per title: BBT seemingly can't finish Initialization, it hangs up at 'Database cleanup 200/252...'.

I'm on Linux, both BBT and Zotero are up to date. The only thing i can think of that changed around the time it stopped working is that i lost my ~/.chache/zotero Directory. If i deactivate BBT Zotero starts up as usual.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.158.5127](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.158.5127.xpi) ("add logging for #gh-1326")

Install in Zotero by downloading [test build 5.1.158.5127](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.158.5127.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you get me a new log with 5127?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.158.5128](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.158.5128.xpi) ("convert number to string for dbUpgrade")

Install in Zotero by downloading [test build 5.1.158.5128](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.158.5128.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by Isimoro** [comment]
The log with 5127 is C7SQ2B2X-euc

**Comment by retorquere** [comment]
Thanks. 5128 should fix the problem, if you can verify that, I'll cut a new release.

**Comment by Isimoro** [comment]
Yes that fixed it, thanks!

**Comment by retorquere** [comment]
Awesome, thanks for the confirmation. 5.1.159 is building but it'll just be what you have now. You'll be upgraded whenever Zotero checks for new plugin versions regardless.

(only I can close issues on this repo, I keep them open as a reminder to merge stuff into a release)
