### ISSUE TITLE
"urldate" is missing in export

### ISSUE THREAD

**Issue by stefangries** [retorquere/zotero-better-bibtex#1329]
**Report ID:** GRK4YMFI-euc

**Exporter used:** Better BibTex

**Expected behavior:** The submitted website-entry should be exported with the urldate field.

**Actual behavior:** The urldate information is missing in the error.

Export with Zotero BibTex Export:
```
@misc{SQLMongoDBMapping,
	title = {{SQL} to {MongoDB} {Mapping} {Chart} — {MongoDB} {Manual}},
	url = {https://docs.mongodb.com/manual/reference/sql-comparison},
	language = {en},
	urldate = {2019-11-13},
	journal = {https://github.com/mongodb/docs/blob/master/source/reference/sql-comparison.txt},
	file = {Snapshot:C\:\\Users\\stefa\\Zotero\\storage\\NDA6QSEG\\sql-comparison.html:text/html}
}
```

Export with Better BibTex Export:
```
@misc{SQLMongoDBMapping,
  title = {{{SQL}} to {{MongoDB Mapping Chart}} \textemdash{} {{MongoDB Manual}}},
  language = {en},
  journal = {https://github.com/mongodb/docs/blob/master/source/reference/sql-comparison.txt},
  howpublished = {https://docs.mongodb.com/manual/reference/sql-comparison},
  file = {C\:\\Users\\stefa\\Zotero\\storage\\NDA6QSEG\\sql-comparison.html}
}
```

**Comment by retorquere** [comment]
It will appear when you set [Add URLs to BibTeX export](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#add-urls-to-bibtex-export) to `url`; BBT only outputs `urldate` if there's an `url` field.

**Comment by retorquere** [comment]
Does this address your problem?

**Comment by stefangries** [comment]
Yes, this helped. Thanks!
