### ISSUE TITLE
URL/DOI exclusive export broken for item types with no dedicated DOI field

### ISSUE THREAD

**Issue by DarwinAwardWinner** [retorquere/zotero-better-bibtex#1331]
Some item types, such as Book, don't have a dedicated field for the DOI, so if such items have a DOI, it gets put in the Extra field. When such an item also has a URL, both are always exported, even if the setting to only export one or the other is set. An example DOI that exhibits this issue is 10.1007/0-387-29362-0. I'll send a debug report for this shortly.

**Comment by DarwinAwardWinner** [comment]
Ok, I have submitted a debug report. The ID is YUBAAYSP-euc. When this item is exported, it contains both a DOI and URL even though I have set the setting "When a reference has both a DOI and a URL, export" to "DOI", not "both". 

Note that my reference is slightly modified from what Zotero auto-generates for using "add by identifier" on this DOI, but the auto-generated reference also exhibits the same issue. Please let me know if you need any other information.

**Comment by DarwinAwardWinner** [comment]
Oh, and here's the corresponding biblatex that's generated (abstract abbreviated):

```bibtex
@collection{Gentleman2005,
  abstract = {Bioconductor is ...},
  date = {2005},
  doi = {10.1007/0-387-29362-0},
  editor = {Gentleman, Robert and Carey, Vincent J. and Huber, Wolfgang and Irizarry, Rafael A. and Dudoit, Sandrine},
  editorb = {Wong, Wing and Gail, M. and Krickeberg, K. and Tsiatis, A. and Samet, J.},
  editorbtype = {redactor},
  isbn = {978-0-387-25146-2 978-0-387-29362-2},
  keywords = {\#nosource},
  location = {{New York, NY}},
  publisher = {{Springer New York}},
  series = {Statistics for {{Biology}} and {{Health}}},
  title = {Bioinformatics and {{Computational Biology Solutions Using R}} and {{Bioconductor}}},
  url = {http://link.springer.com/10.1007/0-387-29362-0},
  urldate = {2019-11-15}
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.160.5156](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5156.xpi) ("fixes #1331")

Install in Zotero by downloading [test build 5.1.160.5156](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5156.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
That took a lot longer than I expected, but this should fix it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.160.5157](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5157.xpi) ("bibtex makes things complicated again")

Install in Zotero by downloading [test build 5.1.160.5157](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5157.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.160.5158](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5158.xpi) ("cleanup")

Install in Zotero by downloading [test build 5.1.160.5158](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.160.5158.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by DarwinAwardWinner** [comment]
There seems to be a bit of churn in the issue status, so I'm not entirely sure what I'm meant to do next. Should I install the test build 5.1.160.5158 linked above and verify that my issue is solved?

**Comment by retorquere** [comment]
If you could, that would be most appreciated.

**Comment by DarwinAwardWinner** [comment]
Ok, I can verify that for the mentioned reference, the exported biblatex contains a `doi` field and no `url` field. So it looks like this is fixed.

**Comment by retorquere** [comment]
Awesome. I'll cut a new release, but it will just be a rebadged 5158. You will automatically be updated when Zotero checks for new plugins.
