### ISSUE TITLE
Installation prompt clarified for BetterBibtex custom BibTex keys

### ISSUE THREAD

**Issue by jpaulos** [retorquere/zotero-better-bibtex#1332]
During the installation process you must choose between three options for handling existing BibTex keys.  I am a long time BetterBibtex user and use a custom Citation key format in BetterBibtex that I like. When I choose the option for 'existing BetterBibtex users,' all my keys get re-written to the default format.

I could believe one of the three options is the right one for me, but the prompt doesn't help me understand which one. My feedback is that the prompts suggest 'who this is for' but don't clearly describe the consequences of the choice.

**Comment by retorquere** [comment]
I can add a fourth option to allow setting a custom pattern, but you won't get a live preview.
The accompanying text does give a sample of what the key would look like though. If you have suggestions for better descriptions, I'm very open to have those changed -- I'm by no means a UX expert.

In the interim, you can change the pattern, select-all, and refresh. That will apply your own pattern.

**Comment by retorquere** [comment]
I've added better explanation (I hope).
