### ISSUE TITLE
Missing Escape of Underscore in "Extra"-Field

### ISSUE THREAD

**Issue by hestehle** [retorquere/zotero-better-bibtex#1336]
I have a special DOI in the "Extra"-field of my reference of type "Book Section" which contains an underscore. In my example its "DOI: 10.1007/978-3-531-19121-8_8" (yes, that's an official DOI). The underscore in the DOI is not escaped properly such that Latex interprets the "8" as a subscript. Pain!

**Report ID:**
Sorry, not available. Using "Better BibTex Debug Report" yields an error during submission. The error says "Request timed out (ACURV6H-euc, references: true)".

I copy & paste the indivual tabs here:

*Application context:*
Application: Zotero 5.0.77 en-US
Platform: MacIntel Intel Mac OS X 10.14
Addons:
  Zotero Word for Mac Integration (5.0.24.SA.5.0.77, extension)
  Zotero LibreOffice Integration (5.0.20.SA.5.0.77, extension)
  Better BibTex for Zotero (5.1.163, extension)
Settings:
  DOIandURL = "both"
  ascii = ""
  asciiBibLaTeX = false
  asciiBibTeX = true
  autoAbbrev = false
  autoAbbrevStyle = ""
  autoExport = "immediate"
  autoExportDelay = 1
  autoExportIdleWait = 10
  autoExportPrimeExportCacheBatch = 4
  autoExportPrimeExportCacheDelay = 100
  autoExportPrimeExportCacheThreshold = 0
  autoExportTooLong = 10
  autoPin = false
  automaticTags = true
  auxImport = false
  biblatexExtendedDateFormat = true
  biblatexExtendedNameFormat = false
  bibtexParticleNoOp = false
  bibtexURL = "off"
  cacheFlushInterval = 5
  citeCommand = "cite"
  citekeyFold = true
  citekeyFormat = "[zotero:clean]"
  citeprocNoteCitekey = false
  csquotes = ""
  exportBibTeXStrings = "off"
  git = "config"
  importBibTeXStrings = true
  itemObserverDelay = 100
  jabrefFormat = 0
  keyConflictPolicy = "keep"
  keyScope = "library"
  kuroshiro = false
  lockedInit = false
  mapMath = ""
  mapText = ""
  mapUnicode = "conservative"
  newTranslatorsAskRestart = false
  parseParticles = true
  postscript = ""
  qualityReport = false
  quickCopyMode = "latex"
  quickCopyPandocBrackets = false
  rawLaTag = "#LaTeX"
  relativeFilePaths = false
  scrubDatabase = false
  skipFields = ""
  skipWords = "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
  sorted = false
  strings = ""
  suppressBraceProtection = false
  suppressNoCase = false
  suppressSentenceCase = false
  suppressTitleCase = false
  verbatimFields = "url,doi,file,eprint,verba,verbb,verbc"
  warnBulkModify = 10
  Zotero: export.quickCopy.setting = "export=a515a220-6fef-45ea-9842-8025dfebcc8f"

*Errors:*
[JavaScript Error: "Upload request 1/NZKVCX7J failed"]
[JavaScript Error: "Your WebDAV server returned an HTTP 423 error for a DELETE request.

If you receive this message repeatedly, check your WebDAV server settings or contact your WebDAV server administrator.

URL: https://rainer:********@q-institut.de/zotero/remote.php/webdav/zotero/NZKVCX7J.prop" {file: "chrome://zotero/content/xpcom/storage/webdav.js" line: 1495}]
[JavaScript Error: "{better-bibtex! +41110} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ASCQM43K-euc-2019-11-17T19.41.30/ASCQM43K-euc-debug.0001.txt 0 "]
[JavaScript Error: "{better-bibtex! +30052} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ASCQM43K-euc-2019-11-17T19.41.30/ASCQM43K-euc-debug.0001.txt 1 "]
[JavaScript Error: "Upload request 1/7575TVZK failed"]
[JavaScript Error: "Your WebDAV server returned an HTTP 423 error for a DELETE request.

If you receive this message repeatedly, check your WebDAV server settings or contact your WebDAV server administrator.

URL: https://rainer:********@q-institut.de/zotero/remote.php/webdav/zotero/7575TVZK.prop" {file: "chrome://zotero/content/xpcom/storage/webdav.js" line: 1495}]
[JavaScript Error: "HTTP DELETE https://rainer:********@q-institut.de/zotero/remote.php/webdav/zotero/2XJ6M9D5.zip failed with status code 423:

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"zotero/2XJ6M9D5.zip" is locked</s:message>
</d:error>
"]
[JavaScript Error: "HTTP DELETE https://rainer:********@q-institut.de/zotero/remote.php/webdav/zotero/4W9MDFGS.zip failed with status code 423:

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"zotero/4W9MDFGS.zip" is locked</s:message>
</d:error>
"]
[JavaScript Error: "HTTP DELETE https://rainer:********@q-institut.de/zotero/remote.php/webdav/zotero/6EIJH38B.zip failed with status code 423:

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"zotero/6EIJH38B.zip" is locked</s:message>
</d:error>
"]
[JavaScript Error: "HTTP DELETE https://rainer:********@q-institut.de/zotero/remote.php/webdav/zotero/6IENRFRP.zip failed with status code 423:

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"zotero/6IENRFRP.zip" is locked</s:message>
</d:error>
"]
[JavaScript Error: "{better-bibtex! +26190} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ASCQM43K-euc-2019-11-17T19.41.30/ASCQM43K-euc-debug.0001.txt 2 "]
[JavaScript Error: "{better-bibtex! +36384} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ASCQM43K-euc-2019-11-17T19.41.30/ASCQM43K-euc-debug.0001.txt 3 "]
[JavaScript Error: "{better-bibtex! +30022} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ASCQM43K-euc-2019-11-17T19.41.30/ASCQM43K-euc-debug.0001.txt 4 "]
Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'
Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'
Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'
[JavaScript Error: "XML Parsing Error: no root element found
Location: http://s3.eu-central-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "http://s3.eu-central-1.amazonaws.com/ping" line: 1}]
[JavaScript Error: "XML Parsing Error: no root element found
Location: http://s3.ap-southeast-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "http://s3.ap-southeast-1.amazonaws.com/ping" line: 1}]
[JavaScript Error: "{better-bibtex! +220202} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ACURV6HJ-euc-2019-11-17T19.47.34/ACURV6HJ-euc-debug.0001.txt 0 "]
[JavaScript Error: "{better-bibtex! +26} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ACURV6HJ-euc-2019-11-17T19.47.34/ACURV6HJ-euc-debug.0002.txt 0 "]
[JavaScript Error: "{better-bibtex! +30002} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ACURV6HJ-euc-2019-11-17T19.47.34/ACURV6HJ-euc-debug.0001.txt 1 "]
[JavaScript Error: "{better-bibtex! +30038} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ACURV6HJ-euc-2019-11-17T19.47.34/ACURV6HJ-euc-debug.0001.txt 2 "]
[JavaScript Error: "{better-bibtex! +30030} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ACURV6HJ-euc-2019-11-17T19.47.34/ACURV6HJ-euc-debug.0001.txt 3 "]
[JavaScript Error: "{better-bibtex! +30254} ErrorReport: failed to PUT to http://better-bibtex-error-reports-62200312-euc.s3-eu-central-1.amazonaws.com/ACURV6HJ-euc-2019-11-17T19.47.34/ACURV6HJ-euc-debug.0001.txt 4 "]
[JavaScript Error: "formatURLPref: Couldn't get pref: extensions.getAddons.link.url" {file: "resource://gre/components/nsURLFormatter.js" line: 143}]
uf_formatURLPref@resource://gre/components/nsURLFormatter.js:143:7
gListView.initialize@chrome://mozapps/content/extensions/extensions.js:2735:9
gViewController.initialize@chrome://mozapps/content/extensions/extensions.js:709:7
initialize@chrome://mozapps/content/extensions/extensions.js:211:3

*Debug log:*
(3)(+0000000): Using data directory /Users/Hele/Zotero
(3)(+0000006): IPC: Initializing pipe at /Users/Hele/Zotero/pipes/1574019595290
(3)(+0000004): Asynchronously opening database 'zotero'
(3)(+0000000): /Users/Hele/Zotero/zotero.sqlite
(3)(+0000002): Proxy not required for https://zoteroproxycheck.s3.amazonaws.com/test
(3)(+0000004): HTTP GET resource://zotero/schema/userdata.sql
(3)(+0000002): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200
(3)(+0000002): HTTP GET resource://zotero/schema/system.sql
(3)(+0000004): HTTP GET resource://zotero/schema/system.sql succeeded with 200
(3)(+0000000): Updating custom tables
(3)(+0000002): HTTP GET resource://zotero/schema/userdata.sql
(3)(+0000000): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200
(3)(+0000002): HTTP GET resource://zotero/schema/triggers.sql
(3)(+0000000): HTTP GET resource://zotero/schema/triggers.sql succeeded with 200
(3)(+0000000): Updating custom tables
(3)(+0000002): {better-bibtex +null} events: handler registered for preference-changed 
(3)(+0000000): {better-bibtex +0} events: handler registered for item-tag 
(3)(+0000000): {better-bibtex +0} events: handler registered for items-changed 
(3)(+0000002): {better-bibtex +2} events: handler registered for items-removed 
(3)(+0000000): {better-bibtex +0} events: handler registered for libraries-changed 
(3)(+0000000): {better-bibtex +0} events: handler registered for collections-changed 
(3)(+0000000): {better-bibtex +0} events: handler registered for collections-removed 
(3)(+0000000): {better-bibtex +0} events: handler registered for libraries-removed 
(3)(+0000000): {better-bibtex +0} events: handler registered for loaded 
(3)(+0000078): {better-bibtex +78} events: handler registered for preference-changed 
(3)(+0000072): {better-bibtex +72} events: handler registered for preference-changed 
(3)(+0000000): {better-bibtex +0} events: handler registered for libraries-changed 
(3)(+0000000): {better-bibtex +0} events: handler registered for libraries-removed 
(3)(+0000000): {better-bibtex +0} events: handler registered for collections-changed 
(3)(+0000000): {better-bibtex +0} events: handler registered for collections-removed 
(3)(+0000002): {better-bibtex +2} Loading Better BibTeX 
(3)(+0000004): {better-bibtex +4} Loading Better BibTeX: setup done 
(3)(+0000118): Setting mode to note
(3)(+0000006): Setting mode to note
(3)(+0000004): Setting mode to note
(3)(+0000004): Setting mode to note
(3)(+0000014): Running unlock callbacks
(3)(+0000000): IPC: Initializing pipe at /Users/Shared/.zoteroIntegrationPipe_Hele
(3)(+0000000): HTTP server listening on  127.0.0.1:23119
(3)(+0000018): LibreOfficePlugin: Communication server listening on 127.0.0.1:23116
(3)(+0000000): LibreOfficePlugin: Registering shutdown listener
(3)(+0000000): {better-bibtex +242} Loading Better BibTeX: starting... 
(3)(+0000000): {better-bibtex +0} pathSearch: looking for texstudio in {"path":["/usr/bin","/bin","/usr/sbin","/sbin"],"pathext":[""],"sep":"/"} 
(3)(+0000002): {better-bibtex +2} pathSearch:  texstudio not found in ["/usr/bin","/bin","/usr/sbin","/sbin"] 
 ...

*References:*
{
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "preferences": {
      "DOIandURL": "both",
      "ascii": "",
      "asciiBibLaTeX": false,
      "asciiBibTeX": true,
      "autoAbbrev": false,
      "autoAbbrevStyle": "",
      "autoExport": "immediate",
      "autoExportDelay": 1,
      "autoExportIdleWait": 10,
      "autoExportPrimeExportCacheBatch": 4,
      "autoExportPrimeExportCacheDelay": 100,
      "autoExportPrimeExportCacheThreshold": 0,
      "autoExportTooLong": 10,
      "autoPin": false,
      "automaticTags": true,
      "auxImport": false,
      "biblatexExtendedDateFormat": true,
      "biblatexExtendedNameFormat": false,
      "bibtexParticleNoOp": false,
      "bibtexURL": "off",
      "cacheFlushInterval": 5,
      "citeCommand": "cite",
      "citekeyFold": true,
      "citekeyFormat": "[zotero:clean]",
      "citeprocNoteCitekey": false,
      "csquotes": "",
      "exportBibTeXStrings": "off",
      "git": "config",
      "importBibTeXStrings": true,
      "itemObserverDelay": 100,
      "jabrefFormat": 0,
      "keyConflictPolicy": "keep",
      "keyScope": "library",
      "kuroshiro": false,
      "lockedInit": false,
      "mapMath": "",
      "mapText": "",
      "mapUnicode": "conservative",
      "newTranslatorsAskRestart": false,
      "parseParticles": true,
      "postscript": "",
      "qualityReport": false,
      "quickCopyMode": "latex",
      "quickCopyPandocBrackets": false,
      "rawLaTag": "#LaTeX",
      "relativeFilePaths": false,
      "scrubDatabase": false,
      "skipFields": "",
      "skipWords": "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum",
      "sorted": false,
      "strings": "",
      "suppressBraceProtection": false,
      "suppressNoCase": false,
      "suppressSentenceCase": false,
      "suppressTitleCase": false,
      "verbatimFields": "url,doi,file,eprint,verba,verbb,verbc",
      "warnBulkModify": 10
    },
    "options": {
      "exportFileData": false,
      "exportNotes": true,
      "keepUpdated": false
    }
  },
  "collections": {},
  "items": [
    {
      "version": 16120,
      "itemType": "bookSection",
      "url": "http://link.springer.com/10.1007/978-3-531-19121-8_8",
      "place": "Wiesbaden",
      "publisher": "Springer VS",
      "pages": "197-235",
      "ISBN": "978-3-531-18576-7 978-3-531-19121-8",
      "date": "2013",
      "extra": "DOI: 10.1007/978-3-531-19121-8_8",
      "accessDate": "2017-06-13T07:44:54Z",
      "libraryCatalog": ...

**Comment by retorquere** [comment]
I'd want to look at the problem with the debug log separately, but as to escaping the DOI, are you exporting as bibtex or biblatex?

**Comment by hestehle** [comment]
Hi!

I am exporting as bibtex.

Thanks for looking into the issue.

**Comment by retorquere** [comment]
Do you have an MWE that exhibits the problem? I tried the sample below and I didn't get any errors. Unfortunately, the bibtex docs don't say whether `doi` should be verbatim or not -- for biblatex it is verbatim.

```
\documentclass[a4paper, 12pt]{article}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
    @article{paper,
    author={name},
    title="{title}",
    journal={J. Phys. Conf. Ser.},
    volume={67},
    number={},
    pages={23},
    doi = {10.1007/978-3-531-19121-8_8},
    year={2007}
}
\end{filecontents*}

\begin{document}
\title{Autumn Term Report}
\author{myself}
\date{\today}
\maketitle

HI \cite{paper}

\bibliographystyle{unsrt}
\bibliography{\jobname}
\end{document}
```

**Comment by retorquere** [comment]
Are you behind a proxy by any chance?

**Comment by hestehle** [comment]
No proxy, no.

The exported bib entry looks like this:
`
@incollection{hoffjann_diskurs_2013,
  address = {{Wiesbaden}},
  title = {{Der Diskurs {\"u}ber PR-Geschichte und PR-Historiographie in Deutschland und international}},
  isbn = {978-3-531-18576-7 978-3-531-19121-8},
  shorttitle = {{Der Diskurs ?}},
  language = {de},
  booktitle = {{UnVergessene Diskurse. 20 Jahre PR- und Organisationskommunikationsforschung}},
  publisher = {{Springer VS}},
  author = {Bentele, G{\"u}nter},
  editor = {Hoffjann, Olaf and {Huck-Sandhu}, Simone},
  year = {2013},
  pages = {197-235},
  file = {/Users/Hele/Zotero/storage/6A37PNZ7/Bentele_2013.pdf},
  doi = {10.1007/978-3-531-19121-8_8}
}
`

Btw. I am using the apacite package and the bibliography style apacite.

**Comment by retorquere** [comment]
That's reproducable, working on it. For my own future reference: the MWE for this is:

```
\documentclass{article}
\usepackage[english]{babel}
\usepackage[utf8x]{inputenc}

\usepackage{apacite}

\title{Package Example: apacite}
\author{writeLaTeX}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@incollection{hoffjann_diskurs_2013,
  address = {{Wiesbaden}},
  title = {{Der Diskurs {\"u}ber PR-Geschichte und PR-Historiographie in Deutschland und international}},
  isbn = {978-3-531-18576-7 978-3-531-19121-8},
  shorttitle = {{Der Diskurs ?}},
  language = {de},
  booktitle = {{UnVergessene Diskurse. 20 Jahre PR- und Organisationskommunikationsforschung}},
  publisher = {{Springer VS}},
  author = {Bentele, G{\"u}nter},
  editor = {Hoffjann, Olaf and {Huck-Sandhu}, Simone},
  year = {2013},
  pages = {197-235},
  file = {/Users/Hele/Zotero/storage/6A37PNZ7/Bentele_2013.pdf},
  doi = {10.1007/978-3-531-19121-8\_8}
}
\end{filecontents*}

\begin{document}
\maketitle

Here is an example citation: \cite{hoffjann_diskurs_2013}.

\bibliographystyle{apacite}
\bibliography{\jobname}

\end{document}
```

**Comment by retorquere** [comment]
@njbart any opinions on this? If I compile the sample above without the escape, it fails, but I have multiple test cases in my suite that have the DOI in verbatim mode in bibtex and those users at least did not complain about this. Could of course be a different style being in use by them.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.164.5195](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.164.5195.xpi) ("adjust tests for #11336")

Install in Zotero by downloading [test build 5.1.164.5195](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.164.5195.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by njbart** [comment]
Well, my view is, it’s not BBT’s job to start fiddling with special characters in DOIs.

By rights, it’s those bibtex styles that claim to be able to deal with `doi` fields but don’t do it properly that need to be fixed. That’s certainly possible, as some of your test cases seem to show. 

Until the bibtex style maintainers in question have done their homework, adding `\usepackage{uri}` (or possibly `\usepackage[doipre={}]{uri}`) to a latex document’s preamble – after `hyperref`, but before the bib package – seems to work tolerably well, too – even with really nasty DOIs such as `10.1002/1521-4001(200209)82:9<579::AID-ZAMM579>3.0.CO;2-V`.

**Comment by retorquere** [comment]
Thanks. It's also possible to leave fixing to a postscript. But the samples I have aren't definitive proof that those authors didn't have problems - if I use the unsrt style I get no errors with this doi, and I can't find docs on whether in bibtex the doi field should be verbatim, or a more general rule that says which fields should be treated as verbatim by bibtex.

**Comment by retorquere** [comment]
Is it save to export those as a preamble in the bibtex file?

**Comment by njbart** [comment]
I don’t think you’ll ever find anything definitive on DOI fields in bibtex in general. Still, there’s the following:

The apacite manual (apacite.pdf from texlive) says “Also note that in the `url` field, special characters like ‘`%`’ and ‘`#`’ should be entered without a backslash …” In the absence of anything to the contrary being said on the DOI field, I’d argue it should be treated analogously.

The natbib manual is silent on the question of escaping characters.

apacite itself does not load `url.sty` (nor `hyperref.sty`, which would in turn load `url.sty`) – and fails when encountering a `url` field with `%` or `#`.

So `url.sty` obviously *is* a prerequisite for `apacite.sty` to function properly. There’s no reason I’m aware of not to load it, and if loaded, both urls and DOIs, even the weird ones, come out properly. (Same for natbib/plainnat; the only combo I have been testing so far.)

Hence I think there is no reason at all for BBT to fiddle with escaping characters, it’s just that users need to be made aware of the fact they should load either `url.sty` or `hyperref.sty` (or `hyperref.sty` and (!) `uri.sty` to get actual functioning hyperlinks from a DOI).

**Comment by njbart** [comment]
> Is it safe to export those as a preamble in the bibtex file?

What’s “those”?

**Comment by retorquere** [comment]
The usepackage statements.

**Comment by njbart** [comment]
You could try that for yourself – what I found is that statements in a bibtex file preamble are loaded only in the document body, so anything that needs to be loaded in the latex document’s preamble won’t work.

**Comment by retorquere** [comment]
That's no good. @hestehle, does loading that package solve the problem with the standard BBT output?

**Comment by retorquere** [comment]
(verified BTW that adding the `@preamble` doesn't work)

So @hestehle, that leaves either loading the `uri` package, or fixing it in a postscript:


```
if (Translator.BetterBibTeX && reference.has.doi) {
   reference.add({ name: 'doi', value: reference.has.doi.value, enc: 'latex' })
}
```

**Comment by njbart** [comment]
To clarify: There’s a `url` and there’s a `uri` package. The former is in widespread use (including the default pandoc latex templates), I’m using it all the time, and I’m pretty sure there’s no reason not to load it in any document. I’m less familiar with the other one, `uri`, but in combination with `hyperref` this one generates actual clickable links from DOIs. There’s probably no reason not to try the latter either (with the option to switch back to `url` in case anything problematic crops up.)

**Comment by retorquere** [comment]
Yeah sorry I meant `url`

**Comment by retorquere** [comment]
(another option, of which I don't know whether it's available to you, is to switch to biblatex of course)

**Comment by hestehle** [comment]
@retorquere, @njbart: Thanks for your investigations. We can live with the addition of `\usepackage{url}`.
