### ISSUE TITLE
[question-feature request] Is there possibility to have two groups each with its own .bib export file?

### ISSUE THREAD

**Issue by kirk86** [retorquere/zotero-better-bibtex#1339]
**Your question/suggestion:**

Hi, I was wondering if there's any possibility to have separate `.bib` files automatically exported from bbitex representing different groups of items. For instance think of papers vs books. I'm not sure whether this already exist or even if it is possible, that's why I labels as feature request as well in case it makes sense to have such an option as well.

Thanks.

**Comment by retorquere** [comment]
Yep, you can in principle have as many as you want, but note that if you have many, Zotero will slow down significantly. Just export the collections of interest and check `Keep updated`. You can find your auto-exports in the BBT preferences. If you want to remove any of them, that's where you do it.

**Comment by kirk86** [comment]
Thanks! Good to know. I think zotfile has not caught up yet to the possibility of having more than one custom place to store files, just raised that request there as well so that both bbt and zotfile can work nicely. ATM bbt is ahead of zotfile in terms of offering features :smiley:

**Comment by retorquere** [comment]
What do you use zotfile for in this context? I only know about zotfile handling attachments.

**Comment by kirk86** [comment]
Great question. Let me elaborate on my use case scenario.
The goal is twofold

1) Have separate bibtex files for articles vs books (the list can easily expand to tutorials, notes, lectures, theses, etc.)

2) Store the corresponding attachments related to each bibtex file to separate custom locations 

At the moment my articles folder looks like these:
```
articles:
------
      |
      a---|
          alexandrov---|
                      2015--|
                           title.pdf

      b
      c
       .
       .
       .
```

I'd like to have something equivalent but let's say only for my books collection.

**Comment by retorquere** [comment]
Ah... Auto-export from saved search would be nice for this, but it needs zotero changes to be feasible.

**Comment by kirk86** [comment]
I see, do they have anywhere publicly available the zotero road map?

**Comment by retorquere** [comment]
Not that I know of, and this wouldn't be on the roadmap -- for all I know, BBT is the only one who would benefit. I'm keeping it open under #904.

**Comment by retorquere** [comment]
It's being discussed on the Zotero forums under https://forums.zotero.org/discussion/70534/auto-exporting-saved-searches

**Comment by kirk86** [comment]
Thanks!
