### ISSUE TITLE
Bookauthor problem

### ISSUE THREAD

**Issue by microniko** [retorquere/zotero-better-bibtex#1345]
**Report ID:** 3P33NUZF-euc

**Exporter used:**  Better BibTeX

**Expected behavior:** Export Book author in BibTeX `bookauthor` field.

**Actual behavior:** Export Book author in BibTeX `collaborator` field.

It's OK with BibLaTex !

**Comment by denismaier** [comment]
I think there is a field `bookauthor` in standard bibtex.

**Comment by denismaier** [comment]
Ah, no field `bookauthor`

**Comment by retorquere** [comment]
So what is the desired output now?

**Comment by microniko** [comment]
Yes, @denismaier, there is no `bookauthor` field in BibTeX… So, I don't know @retorquere :\

**Comment by denismaier** [comment]
Well, if you need it for bibtex proper, adding `bookauthor` would be pointless. If you need it for pandoc-citeproc, you'd be better off using the biblatex export option.

**Comment by retorquere** [comment]
If you don't know, I don't know. If you plan to research this I can keep this issue open for a bit, otherwise I'll have to close.

**Comment by retorquere** [comment]
> If you need it for pandoc-citeproc, you'd be better off using the biblatex export option.

If you need it for pandoc, I'd go with [Better CSL JSON/YAML](https://github.com/retorquere/zotero-better-bibtex/issues/1192#issuecomment-495498650).

**Comment by denismaier** [comment]
> > If you need it for pandoc-citeproc, you'd be better off using the biblatex export option.
> 
> If you need it for pandoc, I'd go with [Better CSL JSON/YAML](https://github.com/retorquere/zotero-better-bibtex/issues/1192#issuecomment-495498650).

Oh yes, but my point was that adding a field to the export that can't be processed would be rather useless. But yes CSL Json is even better.

**Comment by retorquere** [comment]
True, and I'm not going to move authors to fields where they'll generally be lost just because it looks prettier -- for those cases there are postscripts.

**Comment by microniko** [comment]
Yes @retorquere , we can close this issue. The problem is *not* BBT ;-)
