### ISSUE TITLE
KeyManager undefined

### ISSUE THREAD

**Issue by mgswiss15** [retorquere/zotero-better-bibtex#1349]
Hello, whenever I want to get any details of the items in my library (basically when I click on an item), I get an error in Zotero, asking me to restart.  Below is the error report. Can you please help? Thanks, M.

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "key_manager_1.KeyManager is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js" line: 29}]

[JavaScript Error: "key_manager_1.KeyManager is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js" line: 29}]

[JavaScript Error: "TypeError: Zotero.BetterBibTeX is undefined" {file: "chrome://zotero/content/standalone/standalone.xul" line: 1}]
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

[JavaScript Error: "TypeError: key_manager_1.KeyManager is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js" line: 45}]
unload@chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js:45:1

[JavaScript Error: "NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICommandLine.handleFlagWithParam]" {file: "file:///opt/Zotero_linux-x86_64/components/zotero-service.js" line: 544}]

[JavaScript Error: "TypeError: key_manager_1.KeyManager is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js" line: 29}]
init@chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js:29:21
load@chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js:36:5

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 283}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:283:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:247:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3490:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1076:15

[JavaScript Error: "key_manager_1.KeyManager is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js" line: 29}]

[JavaScript Error: "key_manager_1.KeyManager is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.ItemPane.js" line: 29}]

version => 5.0.78, platform => Linux x86_64, oscpu => Linux x86_64, locale => en-US, appName => Zotero, appVersion => 5.0.78, extensions => Zutilo Utility for Zotero (3.3.0, extension), ZotFile (5.0.14, extension), Better BibTex for Zotero (5.1.166, extension), Zotero LibreOffice Integration (5.0.20.SA.5.0.78, extension)

**Comment by retorquere** [comment]
Please update to the latest BBT.

**Comment by mgswiss15** [comment]
Done, solved, thanks!
