### ISSUE TITLE
Title of German entry converted to lowercase during import

### ISSUE THREAD

**Issue by frederik-elwert** [retorquere/zotero-better-bibtex#1350]
**Report ID:** PIBKL57J-euc

**Full Bib(La)TeX item you are trying to import:**

```bibtex
@incollection{schiffer2005a,
  author = {Schiffer, S.},
  date = {2005},
  title = {Die Darstellung des Islams in der Presse: Sprache, Bilder, Suggestionen},
  publisher = {Ergon},
  booktitle = {Eine Auswahl von Techniken und Beispielen},
  address = {Würzburg},
  language = {german}
}
```

**Expected behavior:**

The title and booktitle fields should keep their casing, since the language is German.

**Actual behavior:**

The title and booktitle fields are converted to sentence case.

I know all this title casing is a delicate issue, I so hope I did not overlook anything.

From what I learned so far, the title casing is changed during export for English entries to match the conflicting expectations from Zotero and BibLaTeX. Non-English entries should remain untouched.

However, I noticed that this does not seem to apply to *importing*. When I import a BibTeX entry with language set to German, the title (and booktitle) are still converted to lowercase.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.168.5272](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.168.5272.xpi) ("fixes #1350")

Install in Zotero by downloading [test build 5.1.168.5272](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.168.5272.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
You're right. Give 5272 a spin.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.168.5277](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.168.5277.xpi) ("update of parser")

Install in Zotero by downloading [test build 5.1.168.5277](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.168.5277.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by frederik-elwert** [comment]
Thanks for the update, very much appreciated!

It does seem to work for the test cases I have. However, I noticed something that I do not fully comprehend:

* For the entries I marked with `language = {german}`, the capitalization was correctly preserved for both `title` and `booktitle` fields.
* However, for some unmarked titles, capitalization was also preserved. This was often correct, as those were also German entries, but still surprising, since I did not mark them as German.
* For some of those titles, capitalization was only preserved in the `title` field, but not in the `booktitle` field.

Examples:

```bibtex
@incollection{albrecht2007a,
  author = {Albrecht, C.},
  date = {2007},
  title = {Evangelische Publizistik},
  editor = {Malik, J./Rüpke and J./Wobbe, T.},
  publisher = {Aschendorff},
  pages = {153 – 163},
  booktitle = {Religion und Medien: Vom Kultbild zum Internetritual},
  address = {Münster}
}
```

→ Both title and booktitle converted to sentence case

```bibtex
@incollection{gaertner2008a,
  author = {Gärtner, C.},
  date = {2008},
  title = {Die Rückkehr der Religionen in der politischen und medialen Öffent­ lichkeit},
  editor = {Gabriel, K./Höhn and H.-J.},
  publisher = {Schöningh},
  pages = {93 – 108},
  booktitle = {Religion heute – öffentlich und politisch: Provokationen, Kontroversen, Perspektiven},
  address = {Paderborn}
}
```

→ Title capitalization preserved, but booktitle converted to sentence case

```bibtex
@incollection{schiffer2005a,
  author = {Schiffer, S.},
  date = {2005},
  title = {Die Darstellung des Islams in der Presse: Sprache, Bilder, Suggestionen},
  publisher = {Ergon},
  booktitle = {Eine Auswahl von Techniken und Beispielen},
  address = {Würzburg},
  language = {german}
}
```

→ Capitalization for both title and booktitle preserved.

(Btw, I know that the entries have other issues, e.g. messed up author names. This is because they are exported by an external pipeline that I do not control. My main concern is the capitalization.)

Is there some heuristic in place to guess the language of entries that do not explicitly state it? First, I thought that entries with non-ascii content were preserved, but this is not always the case.

So the new version does indeed fix my immediate problem, as it keeps the capitalization for explicitly flagged German language entries where it did not before. But there is something to the overall behaviour that I do not fully understand yet.

**Comment by retorquere** [comment]
Looking into those

**Comment by retorquere** [comment]
Ah right -- yes, there's a heuristic test: It doesn't guess the language, but if more words in a field are all-`X`case (where `X` is either `lower` or `upper`) than mixed-case, it is assumed that you want them this way.

**Comment by frederik-elwert** [comment]
Okay, I see. I guess the original issue is solved, then. I’m not 100% comfortable with the heuristic, as it appears to be slightly unpredictable. But if it works for others, and if I’m still able to control behavior through the language field, I’m good.

**Comment by retorquere** [comment]
I'm adding a setting for that, but sentence casing is always going to require after care. I'm not doing natural language processing. You can also turn sentence casing, but that's going to give ugly results on re-exports.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.171.5397](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5397.xpi) ("adjust tests")

Install in Zotero by downloading [test build 5.1.171.5397](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5397.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
5397 adds settings for this, in the "Advanced" tab.

**Comment by retorquere** [comment]
If those work to your satisfaction, I'll cut a new release.
