### ISSUE TITLE
Zotero using ~30% CPU (on my Mac) doing nothing, unless minimized

### ISSUE THREAD

**Issue by Blaisorblade** [retorquere/zotero-better-bibtex#1352]
**Report ID:**
QCKFMXTZ-euc

**Actual behavior:**
When not in use, Zotero shouldn't use significant amount of CPUs.

**Expected behavior:**
Zotero wastes lots of CPUs, iff *Better BibTeX is enabled* and *the Zotero window is not minimized into an icon*.

Disabling/enabling plugins confirms that all that matters is whether Better BibTeX is enabled.

This has been going on for a few days, but not sure how long, since it's using 30-50% of one CPU and doesn't produce significant fan noise.

First reported as https://forums.zotero.org/discussion/comment/344214.

**Comment by Blaisorblade** [comment]
BTW, the above was with v5.1.168; I just downgraded to v5.1.164 (after skimming #1346) and the issue disappears!

**Comment by retorquere** [comment]
Strange, there were hardly any changes between the two. I'm going to see if I can replicate this. The log doesn't show much activity from BBT.

**Comment by retorquere** [comment]
Got it. Fix coming up.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.168.5278](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.168.5278.xpi) ("fixes #1352")

Install in Zotero by downloading [test build 5.1.168.5278](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.168.5278.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
This fixes it for me, but I'd love confirmation on this one. I want to push this out urgently.

**Comment by VorpalBlade** [comment]
I noticed something something similar on Linux: I saw a massive amount of wakeups in powertop from Zotero, as well as a constant CPU usage of around 10%.

The test build above (5278) fixes those issues for me.

**Comment by Blaisorblade** [comment]
Test build fixes the issue for me too :-)

**Comment by Blaisorblade** [comment]
Uh — you're removing an animated GIF, but you correctly showed it only at loading time, so that shouldn't keep using CPU, right? But I can see that's not worth investigating.

**Comment by retorquere** [comment]
That is correct, but a) I have no idea why this is the case, b) this part of the Firefox is increasingly less documented and c) Zotero is moving away from the Firefox base anyhow, so this isn't worth figuring out.

**Comment by retorquere** [comment]
I will push out a new release when I'm at my desk in about an hour.

**Comment by retorquere** [comment]
Build is running and will drop in 30 minutes or so.

This has been a wild few days.

**Comment by verga** [comment]
I'm experiencing the same problem in ubuntu 18.04.3: better bibtex consumes 50-70% of CPU, even after updatint to the test release zotero-better-bibtex-5.1.168.5278.xpi; disabling the plugin "solves" the issue.

**Comment by retorquere** [comment]
Can you check whether it still happens with v5.1.169?

**Comment by retorquere** [comment]
And can you send a debug log?

**Comment by retorquere** [comment]
@verga and do you see a spinning icon in the citekey column when Zotero starts?

**Comment by verga** [comment]
Yes, the spining icon is there at zotero start

**Comment by retorquere** [comment]
Then you haven't upgraded yet. Have you restarted since updating BBT?

**Comment by verga** [comment]
The test version do not show the spin icon but a static gif waiting for the keys. I'm trying to generate the log file

**Comment by verga** [comment]
report ID: THLB27JB-euc

```
Application: Zotero 5.0.80 en-US
Platform: Linux x86_64 Linux x86_64
Addons:
  ZotFile (5.0.14, extension)
  Better BibTex for Zotero (5.1.168.5278, extension)
  Zotero LibreOffice Integration (5.0.20.SA.5.0.80, extension, disabled)
Settings:
  DOIandURL = "both"
  ascii = ""
  asciiBibLaTeX = false
  asciiBibTeX = false
  autoAbbrev = false
  autoAbbrevStyle = ""
  autoExport = "idle"
  autoExportDelay = 1
  autoExportIdleWait = 10
  autoExportPrimeExportCacheBatch = 4
  autoExportPrimeExportCacheDelay = 100
  autoExportPrimeExportCacheThreshold = 20
  autoExportTooLong = 20
  autoPin = false
  automaticTags = true
  auxImport = false
  biblatexExtendedDateFormat = true
  biblatexExtendedNameFormat = false
  bibtexParticleNoOp = false
  bibtexURL = "url"
  cacheFlushInterval = 5
  citeCommand = "cite"
  citekeyFold = true
  citekeyFormat = "[auth]-[year]"
  citeprocNoteCitekey = false
  client = "zotero"
  csquotes = ""
  debugLogDir = ""
  exportBibTeXStrings = "off"
  git = "config"
  ignorePostscriptErrors = true
  importBibTeXStrings = true
  itemObserverDelay = 100
  jabrefFormat = 0
  keyConflictPolicy = "change"
  keyScope = "library"
  kuroshiro = false
  mapMath = ""
  mapText = ""
  mapUnicode = "conservative"
  newTranslatorsAskRestart = true
  parseParticles = true
  platform = "lin"
  postscript = ""
  qualityReport = false
  quickCopyMode = "latex"
  quickCopyPandocBrackets = false
  rawLaTag = "#LaTeX"
  relativeFilePaths = false
  removeStock = false
  scrubDatabase = false
  skipFields = ""
  skipWords = "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
  sorted = false
  strings = ""
  suppressBraceProtection = false
  suppressNoCase = false
  suppressSentenceCase = false
  suppressTitleCase = false
  testing = false
  verbatimFields = "url,doi,file,eprint,verba,verbb,verbc"
  warnBulkModify = 10
  Zotero: export.quickCopy.setting = "bibliography=http://www.zotero.org/styles/chicago-note-bibliography"

```

**Comment by retorquere** [comment]
If you see the static icon you have upgraded (and the log shows this). And you're still seeing the CPU use? Even after restarting Zotero?

**Comment by retorquere** [comment]
Does downgrading to .164 fix it for you?

**Comment by verga** [comment]
I restarted zotero and now it is working _normally_ (I think I did not wait enough after start to see the cpu in its idle state... I have a large data base)  I think you may close this issue!

**Comment by retorquere** [comment]
169 contains the same fix BTW.
