### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by doncip** [retorquere/zotero-better-bibtex#1354]
I am experiencing a high CPU usage (around 50%) on my Mac 10.14.6 and the latest version of Zotero 5.0.80. This is due to Better-BibTeX because the issue goes away if I disable the addon.

**Comment by doncip** [comment]
Debug report: 37GR72TS-euc

**Comment by retorquere** [comment]
Duplicate of #1352 - I'd appreciate it if you could test whether the proposed solution works for you too.

**Comment by doncip** [comment]
Sorry for duplicate. Yes, the solution solved my problem.

**Comment by retorquere** [comment]
Cool, and no worries. A release build is running which will drop in 30 minutes or so (the full test suite takes a while)
