### ISSUE TITLE
shorttitle1_0 does not generate lower case short title in citation key

### ISSUE THREAD

**Issue by sjkiss** [retorquere/zotero-better-bibtex#1356]
HI, I'm trying to create a citation key that looks like author_title_year. But the shorttitle command in the Better Biblatex Preferences pane I am using is shorttitle1_0 and I thought that this should work, meaning that no words in the title part of the citation key would be not capitalized. But I am getting author_Title_year. I thought it would look like author_title_year. 

Any thoughts?

I have submitted a report via the debugging feature (5IP2R2WL-euc) 

the citekey that better biblatex is currently generating is healy_Data_2018. 

I would like to see healy_data_2018.

**Comment by sjkiss** [comment]
HI there, I did submit a debut id and edited the original post to note that (see 5IP2R2WL-euc)

**Comment by sjkiss** [comment]
I have solved my own problem. Adding [shorttitle1_0:lower] produced the results I needed. 
But I did not see the :lower option in the documentation. Perhaps I missed it.

**Comment by retorquere** [comment]
It's at https://retorque.re/zotero-better-bibtex/citing/#filters

**Comment by retorquere** [comment]
And that is indeed the correct solution.

**Comment by retorquere** [comment]
(I don't get notified for edits, sorry, so I didn't know you had uploaded the debug report)
