### ISSUE TITLE
Import support for the online type in BBT

### ISSUE THREAD

**Issue by pmembrey** [retorquere/zotero-better-bibtex#1358]
First thank you for BBT! I was starting to panic about how to properly cite all the work I'd collected after I had discovered there were many conflicting keys. Thanks to BBT, panic attack averted!

I've only only been using it for a couple of hours, so it is completely possible that I've missed something obvious.

The reason why this is important for me at the moment is that the paper I'm writing relies on a lot of content that isn't peer reviewed but is still the source of truth. For example, Intel ARK is the definitive place to get CPU specifications, but it doesn't feel right citing it like a peer reviewed source.

To help with that, I currently have two reference sections, one which is peer reviewed and one which isn't. Currently the way I tell them apart is with the `online` type. So I hit this issue almost immediately.

I think the solution is probably the same as #430 which is "use Better BibLaTeX" (just need to find it). I found that issue after I'd started writing up this one, but I decided to continue because I think it should still import natively even if it can't export it natively as other tools/exports could still work with it.

Thanks again for all your hard work!

**Report ID:**

K2L99KLB-euc

**Full Bib(La)TeX item you are trying to import:**

```
@online{WEB:intel-ark-atom,
        Author = {{Intel}},
        Title = {{Intel Atom E3826 specifications}},
        Url = {https://ark.intel.com/content/www/us/en/ark/products/78477/intel-atom-processor-e3826-1m-cache-1-46-ghz.html},
        Year = {2019}}
```

**Expected behavior:**

BBT imports the `online` type as is.

**Actual behavior:**

BBT doesn't recognise the `online` type and converts it to `article` instead with the following error:

```
@WEB:intel-ark-atom, importing as journalArticle
```
From looking at past issues (such as #430 and #492) the solution is for me to use Better BibLaTeX. I was thinking though that even if bibtex can't format it properly for the output (and needs to convert to say `misc`, the import should still represent this correctly so it can be used natively inside Zotero.

**Comment by pmembrey** [comment]
This should be considered an enhancement not a bug given further research.

**Comment by pmembrey** [comment]
I'm not sure if this comes under this ticket, but it might be worth making it prominent in the README that if you need to use features like `online` you'll need to use Better BibLaTeX given I'm at least the second person to hit this.

It would also be great if that included a link to it, some documentation or just some pointers - google searching and reading through some of the repo didn't enlighten me.

I'm assuming of course that if I screwed it up, someone else might too.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.169.5318](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.169.5318.xpi) ("fixes #1358")

Install in Zotero by downloading [test build 5.1.169.5318](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.169.5318.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
> I think the solution is probably the same as #430 which is "use Better BibLaTeX" (just need to find it).

It's one of the export formats installed by BBT. You'll find it in the dropdown list when you export items from Zotero.

> I found that issue after I'd started writing up this one, but I decided to continue because I think it should still import natively even if it can't export it natively as other tools/exports could still work with it.

It could be that there's curently confusion about what can be imported, and what can be exported. BBT will do it's best to import whatever bibtex *or* biblatex you offer it into things supported by Zotero. Fully separately from this, BBT will do its best to export something as it lives in Zotero to the closest possible bibtex or biblatex (depending on which you choose at export) equivalent.

You may expect this to round-trip cleanly (so import of .bib file into Zotero and re-export of the imported items to a .bib file and expect to see the exact original again), which is a soft goal of BBT, but it's really only 100% possible in a small minority of cases. By and large, bibtex, biblatex and Zotero have different ideas of what goes into a reference item, so translations going either way in most cases have to make choices on where to put the information that does the least damage to teh intent expressed in the source. 

> K2L99KLB-euc

This is a debug report from the help menu; if we are talking about export, I need one generated by right-clicking the item you want to export, and selecting "Send debug report" from the popup menu that shows. If it's about import, we don't need a debug log for this particular issue (but thanks for sending one anyway -- better one too many than one too few).

> **Expected behavior:**
> 
> BBT imports the `online` type as is.

The problem is that Zotero doesn't have an `online` type.

> **Actual behavior:**
> 
> BBT doesn't recognise the `online` type and converts it to `article` instead with the following error:
> 
> ```
> @WEB:intel-ark-atom, importing as journalArticle
> ```


It's not so much that BBT doesn't recognize it, it just doesn't know to what Zotero type it should be translated.

> From looking at past issues (such as #430 and #492) the solution is for me to use Better BibLaTeX. I was thinking though that even if bibtex can't format it properly for the output (and needs to convert to say `misc`, the import should still represent this correctly so it can be used natively inside Zotero.

That wouldn't help in your case. The difference between Better BibTeX and Better BibLaTeX only concerns how items that exist in Zotero (regardless of how they got there) are exported.

Try 1358. This will retain the reference type for export. It will still translate `online` to `journal article` though. I'm open to suggestions for an alternate Zotero item type.

**Comment by retorquere** [comment]
> I'm not sure if this comes under this ticket, but it might be worth making it prominent in the README that if you need to use features like `online` you'll need to use Better BibLaTeX given I'm at least the second person to hit this.

The README does say

> Better BibTeX works from [BibTeXing](http://ctan.cs.uu.nl/biblio/bibtex/base/btxdoc.pdf) and [Tame the BeaST](http://www.lsv.ens-cachan.fr/~markey/BibTeX/doc/ttb_en.pdf) for BibTeX, and [The Biblatex Package](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) for BibLaTeX

And those (in the case of bibtex, only roughly, but in the case of biblatex, extensively) document which fields you can expect. In the case of `online`, that is exclusively supported by biblatex -- if I were specify all this in the README, I'd just be duplicating those manuals.

> It would also be great if that included a link to it, some documentation or just some pointers - google searching and reading through some of the repo didn't enlighten me.
> 
> I'm assuming of course that if I screwed it up, someone else might too.

That's understandable, but I don't mind answering questions here, or on gitter.

**Comment by pmembrey** [comment]
Thanks for the detailed and super fast reply!

Part of my problem is that I was using Mendeley until I found out that it had really poor support for bibtex. I then saw that Zotero had great support for it, especially with BBT.

I totally get the concept of imports being different from exports (that was actually what I was talking about when I said the import should import as `online` even if it couldn't export it). What I didn't know was that Zotero itself doesn't have the concept of an `online` type - I've been using Zotero for only a few minutes longer than BBT :)

I also didn't know that Better BibLaTeX was just one of the exporters that BBT provides.

So I think we're actually on the same page now that two gaping holes in things I should have known have now been filled :)

That being said, I would suggest that `online` might be mapped to Zotero's `webpage` type. Its documentation suggests that it is for any sort of "hosted" document (although it notes you should prefer a more precise type). In the biblatex manual, it specifies `www` as an alias for `online` so it seems a reasonable approximation for each other.

Also if my last comment came off as a bit brusque, my apologies, that wasn't my intention :)

**Comment by pmembrey** [comment]
Just tested the new build - can confirm that it imports and exports that entry as `online`. I still get the errors for the type being unknown, but that makes sense given that it's falling back to `article`.

**Comment by retorquere** [comment]
I wouldn't say "should have known". Zotero has it's subtleties, BBT *definately* has it's subtleties, and both are severely under-documented. To compensate, it's always OK to ask questions about anything you want or expect BBT to do, here or on gitter.

Mendeley's "support" for bibtex is not great. I do not have the impression anyone inside Elsevier actually uses Mendeley with bibtex/biblatex.

`webpage` sounds reasonable, and Better BibLaTeX actually already exports `webpage` to `online. Test build incoming.

**Comment by retorquere** [comment]
Holy shit dude. Thanks!

**Comment by pmembrey** [comment]
No worries :)

Please consider it a small token of my appreciation - the amount of pain and anguish you've already saved me, not to mention all the pain and anguish I'd still be going through right now if BBT didn't exist and didn't have such incredible support is priceless.

I'm actually able to write content at the moment knowing that the nightmare I found just a few hours ago has already been taken care of :)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.169.5319](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.169.5319.xpi) ("test case for #1358")

Install in Zotero by downloading [test build 5.1.169.5319](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.169.5319.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
The error message about defaulting to journalArticle was a little confusing, I've changed that too (but you won't see it now for `online`).

**Comment by retorquere** [comment]
I wouldn't call it small by any measure, but I'm not complaining 😄 . 5319 imports `online` as `webpage`, and will export it again as `online` *if* using Better BibLaTeX. bibtex doesn't know about webpages or `online` so it gets the `misc` treatment. You can always still force the type to anything you want by adding `tex.referencetype=<something>` in the `extra` field.

If 5319 works as you expect, I can cut a new release.

**Comment by pmembrey** [comment]
let me give it a try now...

**Comment by pmembrey** [comment]
Confirmed it's a good fix:

* `online` types are imported as `webpage`
* No warnings on import
* Exports as `online` when exporting with Better BibLaTeX

All good from my point of view :)

**Comment by retorquere** [comment]
5.1.170 is building, but it's just a rebadged 5319. When it drops (about 30 minutes or so, the full test suite takes a while) you can force an upgrade or just wait until Zotero checks for extension updates (once every day or two days I think).

**Comment by pmembrey** [comment]
No worries, thanks again for getting such a complete fix in for my issue so quickly!

**Comment by retorquere** [comment]
My pleasure
