### ISSUE TITLE
BBT error on exporting citation graph

### ISSUE THREAD

**Issue by kirk86** [retorquere/zotero-better-bibtex#1360]
I've tried to export a citation graph but I keep receiving an error.
I've reported the error with the following report ID: `85ENWUFY-euc`

Also, I noticed that the exported citation is in `.gml` extension but yEd expects `.graphml` instead among the other formats. 

Thanks.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.171.5357](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5357.xpi) ("fixes #1360")

Install in Zotero by downloading [test build 5.1.171.5357](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5357.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by kirk86** [comment]
@retorquere The update solved the export problem but there's a problem with the import in yEd

```
Error during import.
XML Parsing Error: This page contains the following errors:error on line 1 at column 1: Document is empty. Below is a rendering of the page up to the first error.
```

Also there's another thing. If I chose to export a single item which has a related item it seems that get a graph with 2 nodes but the related node has not populated the label correctly.
```
 Creator "Zotero Better BibTeX"
Version "2.15"
graph [
  hierarchic 0
  label ""
  directed 1
  node [
    id 0
    label "goodfellow2019"
  ]
  node [
    id 1
    label "??"
    graphics [ outlineStyle "dashed" ]
  ]
  edge [
    source 0
    target 1
    graphics [
      fill  "#000000"
      sourceArrow "standard"
      targetArrow "standard"
    ]
  ]
]
```

Also could you please add another item in the nodes containing the equivalent titles or maybe something equivalent like you have in the exporter where we can choose which elements from a zotero items should be shown inside a node definition in the `.graphml` exported file?

Thanks!

**Comment by retorquere** [comment]
The first message makes me think graphml is xml-based, which GML isn't.

Wrt just exporting one: translators don't have access to anything but what was selected. I can't find out what hangs behind those missing nodes.

I'll think about checkboxes for title/author. That's doable.

**Comment by kirk86** [comment]
Thanks for the prompt reply.


> Wrt just exporting one: translators don't have access to anything but what was selected. I can't find out what hangs behind those missing nodes.

My initial understanding is that the node "goodfellow2019" is just the item selected in zotero for export. But, I don't know what the other node with id 1. Instinctively I thought that might have been the other item shown in the `Related` tab of "goodfellow2019".

It seems that's not the case if I'm understanding correctly what you're saying?

**Comment by retorquere** [comment]
Yep, that's the other item. The translator can see it's related to something, but Zotero does not give access to translators to tell what it is unless it's also exported at the same time.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.171.5360](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5360.xpi) ("options")

Install in Zotero by downloading [test build 5.1.171.5360](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5360.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
You can select "GML" from options in the file-open dialog to open GML files. 5360 adds options to add authors, title and/or year to the label, but it doesn't really look good as far as I'm concerned.

**Comment by kirk86** [comment]
> Zotero does not give access to translators to tell what it is unless it's also exported at the same time

I'll give it a try and see if exporting both related items correctly creates the `.gml` file.

**Comment by retorquere** [comment]
Any news?

**Comment by kirk86** [comment]
@retorquere Hi, sorry for the delayed reply.
So, exporting two items related to each other then it properly creates the graph nodes and edges like for instance:
```
Creator "Zotero Better BibTeX"
Version "2.15"
graph [
  hierarchic 0
  label ""
  directed 1
  node [
    id 0
    label "test1"
  ]
  node [
    id 1
    label "test2"
  ]
  edge [
    source 0
    target 1
    graphics [
      fill  "#000000"
      sourceArrow "standard"
      targetArrow "standard"
    ]
  ]
]
```
But I'm still unable to import this into yEd. I still get the xml error as before no matter if I try `.graphml` or `.gml`

**Comment by retorquere** [comment]
You need to open the options in the open dialog and select the GML format (not graphml, which is an xml format).

**Comment by kirk86** [comment]
I suppose you talking about `yworks.com/yed-live`?
I don't see such an option when I select open from local file the only available options are `All Files` or `Custom Files`.

**Comment by retorquere** [comment]
Ah, yEd live doesn't support GML.

**Comment by kirk86** [comment]
Oh, I see that's a bummer!

**Comment by retorquere** [comment]
I'm looking into graphml but in the docs I could find, you can describe a graph but not label it. That seems strangely useless. yEd can label nodes but does so in a clearly proprietary way (which I can't find docs on either). I'd rather not create output for one specific program where graphml purports to be an open standard.

**Comment by kirk86** [comment]
I don't know what to suggest here, but from the users perspective and developers perspective, it would be sensible to have something that's open source, long-lasting standard that is easily supported by online editors without forcing users to install additional software.

**Comment by retorquere** [comment]
I'm sensitive to those arguments, but a) the only standard that seems to qualify is GML, since I couldn't find a way to label nodes in graphml without using proprietary yEd extensions to graphml, and b) from an open source pov, online editors are actually worse than installable software because you're beholden to the service provider, even if it's free and/or Libre. If I must choose between only online open source and only offline open source, I'll always opt for offline.

But in this case, I'd be happy to implement any reasonable text-based standard which can be read online or offline, proprietary or open source. I just don't know any open graph storage format with node labeling  but GML.

**Comment by retorquere** [comment]
I mean you could ask yEd online and draw.io why they don't support GML. It's a drop-dead simple file format. Alternatively, if you know of an open standard which ticks the boxes, I'd be happy to do that.

**Comment by retorquere** [comment]
Come to think of it - I do know one other  format that qualifies. Graphviz dot files. But I don't know of any GUI tool/service that can read them, and the autolayout from yEd and draw.io is vastly superior to Graphviz.

**Comment by retorquere** [comment]
Interesting... yEd live claims to be able to read .dot files, even when the offline client doesn't I'll give that a go.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.171.5389](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5389.xpi) ("export dot")

Install in Zotero by downloading [test build 5.1.171.5389](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.171.5389.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Good news then maybe -- 5389 exports .dot files, which can be read with yEd online, [DotEditor](https://vincenthee.github.io/DotEditor/), and rendered by graphviz of course. Drawio can't read them, but https://github.com/hbmartin/graphviz2drawio/ can convert them to drawio.

The drawio format is pretty loopy so I don't plan to implement that.

**Comment by retorquere** [comment]
BTW Zotero relations are always bidirectional. You can add lines to the `extra` field like

```
cites: <citekey 1>, <citekey 2>, <etc>
```

and that will draw a unidirectional arrow from the item that has it in the `extra` field to items with those citekeys.

**Comment by kirk86** [comment]
Thanks for your help and great work! :smiley:

**Comment by retorquere** [comment]
My pleasure. Integrate this then?

**Comment by kirk86** [comment]
Yup, this seems to be working nice with yEd live as well. :+1:

**Comment by kirk86** [comment]
Actually the .dot representation is very nice since it gives me more freedom and now I can simply do
```
graph = pydot.graph_from_dot_file(apath)
import tempfile, Image
fout = tempfile.NamedTemporaryFile(suffix=".png")
graph.write(fout.name,format="png")
Image.open(fout.name).show()
```
Completely biapassing if I have to the need for eny dot editor.
