### ISSUE TITLE
Capitalization of titles in French

### ISSUE THREAD

**Issue by maloherry** [retorquere/zotero-better-bibtex#1362]
**Report ID:**
GM3QMS7Z-euc
**Exporter used:**

**Expected behavior:**
The title `L'évolution de l'imaginaire de l'écologie politique au début du XXIe siècle : la restructuration de l'écologie radicale française autour du mouvement pour la décroissance` should be displayed the same in the exported .bib file since we do not capitalize titles in French.

**Actual behavior:**
This is what it looks like in the .bib file :
```
  title = {L'évolution de l'imaginaire de l'écologie Politique Au Début Du {{XXIe}} Siècle : La Restructuration de l'écologie Radicale Française Autour Du Mouvement Pour La Décroissance},
  shorttitle = {L'évolution de l'imaginaire de l'écologie Politique Au Début Du {{XXIe}} Siècle},
```

It happens with a lot of references, in my .bib file : 
 ```
 title = {Le Club de l'{{Horloge}} (1974-2002). {{Evolution}} et Mutation d'un Laboratoire Idéologique},
  title = {Les Groupes de Réflexion Écologistes : Pistes Pour l'analyse d'un Espace à La Croisée Des Champs},

```
I've submitted a report only for the first reference, tell me if you need reports for the other ones.

Thanks!

**Comment by retorquere** [comment]
I think this one will do -- if no language is set on the item, BBT assumes English rules for capitalization. If you set it to e.g. `French`, or `Francais`, or anything really that is not empty and doesn't resemble `English` (like `maloherry`), it won't be capitalized. It is explained [here](https://retorque.re/zotero-better-bibtex/support/faq/#bbt-is-changing-the-capitalization-of-my-titles----why).

**Comment by maloherry** [comment]
My bad, I should have read the FAQ first, it works perfectly. Thanks!

**Comment by retorquere** [comment]
No problem at all, it's always OK to ask questions here. Not reading the FAQ isn't held against you, there's a lot to take in about BBT.
