### ISSUE TITLE
Does the publisher field work when put in Zotero's extra field?

### ISSUE THREAD

**Issue by Mister-Snuggles** [retorquere/zotero-better-bibtex#1370]
**Report ID:**
C86M7A7W-euc

**Exporter used:**
Better BibLatex

**Expected behavior:**
I want the publisher (presented as "Publisher: IEEE" in the extra field) to be exported. I want this for a journal article, if that matters.

**Actual behavior:**
I cannot see publisher exported. Even if I enable the notes field, it is not there. This suggests to me that Zotero is processing it; not sure if it is accessible to the plugin.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.174.5449](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.174.5449.xpi) ("fixes #1370")

Install in Zotero by downloading [test build 5.1.174.5449](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.174.5449.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by Mister-Snuggles** [comment]
Yay, it works now! Thank you very much!

**Comment by retorquere** [comment]
Don't worry, you can't 😆 . I have label-gun keep issues open until I close them so I have a reminder to actually merge this fix into a new release.
