### ISSUE TITLE
Shortcut for "Push references to TeXstudio"

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1371]
Many thanks for the very nice "Push references to TeXstudio" feature (though, compared to JabRef, the user has to manually go back to TeXstudio, but I guess it is only feasible via Java).

**Your suggestion:**

It would be nice for BBT to let the user perform this action by a shortcut (maybe with the help of Zutilo?).

**Comment by retorquere** [comment]
The only thing I can do as far as I know is minimize Zotero after it's pushed to TexStudio; maybe TexStudio picks focus back then.

Zutilo should be able to provide a shortcut; all it'd have to do is test for the presence of `Zotero.BetterBibTeX` (to know that BBT is installed) and then call `Zotero.BetterBibTeX.ZoteroPane.toTeXstudio()`.

**Comment by dbitouze** [comment]
>The only thing I can do as far as I know is minimize Zotero after it's pushed to TexStudio; maybe TexStudio picks focus back then.

It's worth try it! :)

> Zutilo should be able to provide a shortcut

Would be nice (though it would be better to not have to rely on a third party plugin, but I have read the discussion about ["Keyboard shortcuts for BBT"](#754) :)

**Comment by retorquere** [comment]
It's not just that I dislike UI work (which I do), I'd also have to coordinate with other shortcut-implementing extensions (such as Zutilo) to make sure we don't get in each others' way. Debugging problems regarding shortcuts would likewise be an issue. Much better to let Zutilo do it.

WRT putting texstudio back up after push, it'd be more logical to have texstudio put itself at front (configurably maybe) when it receives a citation push. That would solve it for all programs that do such pushes rather than having each have to reimplement it. Are you OK with giving that a try first?

**Comment by dbitouze** [comment]
>It's not just that I dislike UI work (which I do), I'd also have to coordinate with other shortcut-implementing extensions (such as Zutilo) to make sure we don't get in each others' way. Debugging problems regarding shortcuts would likewise be an issue. Much better to let Zutilo do it.

I can understand you dislike UI work :) About possible shortcuts clashes, I must admit I don't know how to deal with, but I guess solutions do exist since e.g. many Firefox add-ons provide shortcuts.

>WRT putting texstudio back up after push, it'd be more logical to have texstudio put itself at front (configurably maybe) when it receives a citation push. That would solve it for all programs that do such pushes rather than having each have to reimplement it. Are you OK with giving that a try first?

I'll open a TeXstudio issue for this.

**Comment by retorquere** [comment]
Since there's no central registry, and not even to my knowledge a way to know that a shortcut key has been claimed by another extension (or even Firefox/zotero itself), the solution appears to be "try not to step on anyone's toes on purpose, and fix it when it breaks" as far as I can tell. That's part of the reason why I guess shortcuts have gravitated to zutilo - it fulfills the role of a de facto registry.

**Comment by dbitouze** [comment]
>>WRT putting texstudio back up after push, it'd be more logical to have texstudio put itself at front (configurably maybe) when it receives a citation push. That would solve it for all programs that do such pushes rather than having each have to reimplement it. Are you OK with giving that a try first?

>I'll open a TeXstudio issue for this.

[Done](https://github.com/texstudio-org/texstudio/issues/857) but the TXS developers would prefer to let Zotero do the job: "So there is a good reason why JabRef takes care of bringing the TXS window to the front. Basically there is no other sane way to do that.".

**Comment by retorquere** [comment]
Windows being obnoxious again... I'll look through the zotero source to see if I can call windows apis; I'm not sure currently whether it can be done, or whether it can be done from an extension.

What about a different way - you could use something like autohotkey to trigger the BBT cayw picker, and I could implement a cayw target that does a texstudio push. That would do two things at once; texstudio would remain the foreground app (I think), and you'd have hotkey access to the functionality.

**Comment by dbitouze** [comment]
>Windows being obnoxious again...

I definitively agree.

> I'll look through the zotero source to see if I can call windows apis; I'm not sure currently whether it can be done, or whether it can be done from an extension.

One of the TXS contributors [suggests Zotero should be able to call winapi functions](https://github.com/texstudio-org/texstudio/issues/857#issuecomment-570927685) through some package like [node-ffi](https://github.com/node-ffi/node-ffi).

>What about a different way - you could use

In fact, not me :) I'm only using Linux.

> something like autohotkey to trigger the BBT cayw

I must admit I don't understand what exactly is this cayw ([Cite as you Write](http://retorque.re/zotero-better-bibtex/citing/cayw/)? I don't understand better).

> picker, and I could implement a cayw target that does a texstudio push. That would do two things at once; texstudio would remain the foreground app (I think), and you'd have hotkey access to the functionality.

Relying on another third party software would be unfortunate, IMHO.

**Comment by retorquere** [comment]
> One of the TXS contributors [suggests Zotero should be able to call winapi functions](https://github.com/texstudio-org/texstudio/issues/857#issuecomment-570927685) through some package like [node-ffi](https://github.com/node-ffi/node-ffi).

Zotero doesn't run `node`, it's a customized Firefox.

> > something like autohotkey to trigger the BBT cayw
> 
> I must admit I don't understand what exactly is this cayw ([Cite as you Write](http://retorque.re/zotero-better-bibtex/citing/cayw/)? I don't understand better).

For linux, ironhotkey or autokey could work (see https://retorque.re/zotero-better-bibtex/citing/cayw/). CAYW (indeed Cite as you Write) is a way to pick out references from your zotero lib and insert them into text-based editors -- such as texstudio.

> Relying on another third party software would be unfortunate, IMHO.

True, but I'm not keen to do per-platform work myself, and pushing texstudio to the front would definitely require per-platform work, and on the most problematic of platforms I couldn't even test because I don't have a windows system.

**Comment by dbitouze** [comment]
>Zotero doesn't run node, it's a customized Firefox.

Too bad!

>For linux, ironhotkey or autokey could work

I'll have a look at them.

>CAYW (indeed Cite as you Write) is a way to pick out references from your zotero lib and insert them into text-based editors -- such as texstudio.

Looks very nice. Are there some videos of this feature with Zotero + BBT?

>True, but I'm not keen to do per-platform work myself, and pushing texstudio to the front would definitely require per-platform work, and on the most problematic of platforms I couldn't even test because I don't have a windows system.

I can understand.

**Comment by retorquere** [comment]
I'm not aware of videos that demonstrate it, but if you type this in a shell

```
curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=cite'
```

(don't plug that URL in a browser, it won't work) you can see it in action. So far, the CAYW formats just return the picked references in the return body, but I could make a special "formatter" that executes a texstudio push instead of returning them.

**Comment by retorquere** [comment]
I also couldn't find the place in jabref that does the foregrounding. All I see is that it does the push in the same way that I do.

**Comment by dbitouze** [comment]
> I'm not aware of videos that demonstrate it, but if you type this in a shell
> 
> ```
> curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=cite'
> ```
> 
> (don't plug that URL in a browser, it won't work) you can see it in action.

Sorry, but I don't understand how it works: running this in a shell results in an empty dialog box "Quick Format Citation":

![Screenshot_20200107_152212](https://user-images.githubusercontent.com/1032633/71902098-a353fa80-3161-11ea-8523-5fb5342ca950.png)

> So far, the CAYW formats just return the picked references

In what format? `\cite{⟨key⟩}`?

> in the return body,

I don't understand what that means.

> but I could make a special "formatter" that executes a texstudio push instead of returning them.

I'm not sure to understand, but would certainly be nice! :)

**Comment by retorquere** [comment]
How it returns them is configurable, but what I'm saying is that instead of returning the picked reference I could push them to texstudio.

**Comment by dbitouze** [comment]
>How it returns them is configurable,

OK.

> but what I'm saying is that instead of returning the picked reference I could push them to texstudio.

Would be nice! 

But I still understand how it works.

**Comment by retorquere** [comment]
BBT listens on the URL `http://127.0.0.1:23119/better-bibtex/cayw` and runs code when it is accessed. By default I return the picked items in a selectable format, but I can do pretty much whatever I want in response, so instead of returning the picked items, I run the same code that runs when you select "push to TeXstudio" in Zotero.

**Comment by dbitouze** [comment]
> BBT listens on the URL `http://127.0.0.1:23119/better-bibtex/cayw` and runs code when it is accessed.

Accessed from Zotero or from the (empty) dialog box? I'm really sorry, but I still don't understand.

Suppose I'm writing a `.tex` file in TeXstudio and I want to cite a reference in a CAYW way. What am I concretely (step by step, please :) supposed to do?

> By default I return the picked items in a selectable format, but I can do pretty much whatever I want in response, so instead of returning the picked items, I run the same code that runs when you select "push to TeXstudio" in Zotero.

I'd like the picked item be pushed to TeXstudio as `\cite{⟨key⟩}` (or better, `\autocite{⟨key⟩}`).

BTW, my favorite editor isn't TeXstudio (I just use it for the LaTeX's courses I'm giving) but  Emacs. Would it be possible to choose the editor where the item is pushed?

**Comment by retorquere** [comment]
> Accessed from Zotero or from the (empty) dialog box? I'm really sorry, but I still don't understand.

Accessed by pretty much anything that can do HTTP requests, except, funnily enough, not browsers. Think of it as an API into Zotero for other apps.
 
> Suppose I'm writing a `.tex` file in TeXstudio and I want to cite a reference in a CAYW way. What am I concretely (step by step, please :) supposed to do?

You would have either TeXstudio itself, or a global hotkey, call this URL, possibly by having the hotkey call `curl` in exactly the way shown. But For TeX-aware editors, I'd probably just use auto-export and the `.bib` citation-autocomplete most will have.

> I'd like the picked item be pushed to TeXstudio as `\cite{⟨key⟩}` (or better, `\autocite{⟨key⟩}`).

That is possible. I'll probably have something in a few hours, I need to cook first.
 
> BTW, my favorite editor isn't TeXstudio (I just use it for the LaTeX's courses I'm giving) but Emacs. Would it be possible to choose the editor where the item is pushed?

With Emacs the answer is obviously yes 😄 . I generally don't choose the editor, the editor calls the HTTP API. If there's a specific way that emacs in tex-mode can be called to do something tex-studio-like (which you'd have to find out -- `vim` user here) I can look into that. But again, emacs will undoubtedly be able to autocomplete from a bib file.

**Comment by dbitouze** [comment]
> > Accessed from Zotero or from the (empty) dialog box? I'm really sorry, but I still don't understand.
> 
> Accessed by pretty much anything that can do HTTP requests,

OK.

> except, funnily enough, not browsers.

:wink:

> Think of it as an API into Zotero for other apps.

OK.

> > Suppose I'm writing a `.tex` file in TeXstudio and I want to cite a reference in a CAYW way. What am I concretely (step by step, please :) supposed to do?
> 
> You would have either TeXstudio itself, or a global hotkey, call this URL, possibly by having the hotkey call `curl` in exactly the way shown.

But how TXS would _call_ this URL?

> But For TeX-aware editors, I'd probably just use auto-export and the `.bib` citation-autocomplete most will have.

For small `.bib` files OK but, for large ones, citation-autocomplete becomes tedious. I much more prefer the following workflow (with "BBT Citation Quick Copy" selected in Zotero Export settings):

1. I write a `.tex` file in my favorite TeX editor,
1. I suddenly need to cite some references,
2. thanks to <kbd>Alt</kbd>+<kbd>Tab</kbd>, I switch to Zotero,
1. I use the handy Zotero UI to select the items of these references,
1. thanks to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>, I copy these references,
2. thanks to <kbd>Alt</kbd>+<kbd>Tab</kbd>, I switch to my favorite TeX editor,
1. thanks to <kbd>Ctrl</kbd>+<kbd>C</kbd> (or <kbd>Ctrl</kbd>+<kbd>Y</kbd> with Emacs), I paste these references,
1. I (continue to) write a `.tex` file in my favorite TeX editor (etc.)

The original purpose of the current issue ("Push references to TeXstudio") was to save the effort of steps 5, 6 and 7 above by replacing them by a single step: "I push the selected references to my favorite editor" (preferably thanks to a shortcut).

And the current derived discussion about CAYW (that I still would love to see in action because I still cannot figure out how it works in pratice) is to know if it would be a better workflow than the mine above.

> > I'd like the picked item be pushed to TeXstudio as `\cite{⟨key⟩}` (or better, `\autocite{⟨key⟩}`).
> 
> That is possible. I'll probably have something in a few hours, I need to cook first.

Thanks! But it is worth only if the resulting workflow would be more efficient than the mine above.

> > BTW, my favorite editor isn't TeXstudio (I just use it for the LaTeX's courses I'm giving) but Emacs. Would it be possible to choose the editor where the item is pushed?
> 
> With Emacs the answer is obviously yes smile .

:wink:

> I generally don't choose the editor, the editor calls the HTTP API. If there's a specific way that emacs in tex-mode can be called to do something tex-studio-like (which you'd have to find out -- `vim` user here)

Come on, come on! A so good add-on developer, using `vim` and not `Emacs`?! :stuck_out_tongue_winking_eye:

> I can look into that. But again, emacs will undoubtedly be able to autocomplete from a bib file.

Indeed, thanks to RefTeX but I still prefer the above workflow.

**Comment by retorquere** [comment]
> But how TXS would _call_ this URL?

However it preferred (but it would require changes to TXS). Most editors that call it use the text it returns to insert it at the cursor. But if I add a push-to-texstudio "formatter", TXS wouldn't have to call it. It wouldn't matter who called it, if any items were picked, they would be pushed to TXS. This is why a global "OS-wide" hotkey would work in this case. [xbindkeys](https://unix.stackexchange.com/questions/44672/assign-shortcut-key-to-run-a-script) can call `curl` ([autohotkey](https://www.autohotkey.com/) for the poor buggers stuck in Windows), and Bob's your uncle.
 
> For small `.bib` files OK but, for large ones, citation-autocomplete becomes tedious. I much more prefer the following workflow (with "BBT Citation Quick Copy" selected in Zotero Export settings): ...

This kind of case is exactly what CAYW was made for.
 
> The original purpose of the current issue ("Push references to TeXstudio") was to save the effort of steps 5, 6 and 7 above by replacing them by a single step: "I push the selected references to my favorite editor" (preferably thanks to a shortcut).

And this is possible. If you can cause a shortcut to call the cayw URL using something like `xbindkeys`, TXS wouldn't be involved in it other than that BBT will push to it.

> And the current derived discussion about CAYW (that I still would love to see in action because I still cannot figure out how it works in pratice) is to know if it would be a better workflow than the mine above.

If you want to see it in action you could install atom and [this atom plugin](https://atom.io/packages/zotero-picker), but I now see that that page also has a GIF of it in action. It would work exactly like that, and steps 3-7 would become

* press hotkey
* type title(s) and enter

(you would want to replace the part where the GIF trigger this from the atom command palette with a hotkey). You can even add qualifiers like page/section names etc in the picker, and they'll come through, formatted for LaTeX. That's not even possible in the steps-3-7 workflow.

> Thanks! But it is worth only if the resulting workflow would be more efficient than the mine above.

That only you can decide. It's trivial for me to add.

> Come on, come on! A so good add-on developer, using `vim` and not `Emacs`?! 😜

Ah yeah but I have this genetic deficiency where I have only 10 fingers.

Vim is what I started with, it's in my muscle memory. I've tried to love emacs (with `evil` installed, natch, because that is obviously both the most natural and generally superior way to use text editors; I'm sure you're familiar with the cliché *"emacs is a great operating system, lacking only a decent editor"*), but I just kept banging into the familar walls (no, I do *not* want an empty... buffer?! WTF is a "buffer"?! how do I `:wq`?! *AAARGH!!!!*.) and in the end it wasn't worth the effort. I will grant that vimscript is an abomination, and scheme beautiful.

I'm sure an Emacs-supremacist would be eager to show how easy it would be to integrate it into emacs 😉 . All you'd have to do is to make `Ctrl-Meta-Shift-Alt-/⍳¨⍴⌹⍟ph'nglui mglw'nafh-Cthulhu-R'lyeh-wgah'nagl-fhtagn` call `curl` and paste the returned text into the buffer.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5554](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5554.xpi) ("cayw tex-studio push")

Install in Zotero by downloading [test build 5.1.176.5554](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5554.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
With 5554, try binding a shortcut key to

```
curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'
```

**Comment by dbitouze** [comment]
> > But how TXS would _call_ this URL?
> 
> However it preferred (but it would require changes to TXS). Most editors that call it use the text it returns to insert it at the cursor. But if I add a push-to-texstudio "formatter", TXS wouldn't have to call it. It wouldn't matter who called it, if any items were picked, they would be pushed to TXS.

Would be nice!

> This is why a global "OS-wide" hotkey would work in this case. [xbindkeys](https://unix.stackexchange.com/questions/44672/assign-shortcut-key-to-run-a-script) can call `curl` ([autohotkey](https://www.autohotkey.com/) for the poor buggers stuck in Windows), and Bob's your uncle.

OK, I'll give a try.

> > For small `.bib` files OK but, for large ones, citation-autocomplete becomes tedious. I much more prefer the following workflow (with "BBT Citation Quick Copy" selected in Zotero Export settings): ...
> 
> This kind of case is exactly what CAYW was made for.

Nice!

> > The original purpose of the current issue ("Push references to TeXstudio") was to save the effort of steps 5, 6 and 7 above by replacing them by a single step: "I push the selected references to my favorite editor" (preferably thanks to a shortcut).
> 
> And this is possible. If you can cause a shortcut to call the cayw URL using something like `xbindkeys`, TXS wouldn't be involved in it other than that BBT will push to it.

OK.

> > And the current derived discussion about CAYW (that I still would love to see in action because I still cannot figure out how it works in pratice) is to know if it would be a better workflow than the mine above.
> 
> If you want to see it in action you could install atom and [this atom plugin](https://atom.io/packages/zotero-picker), but I now see that that page also has a GIF of it in action. It would work exactly like that, and steps 3-7 would become
> 
>     * press hotkey
> 
>     * type title(s) and enter

Very nice indeed!

> (you would want to replace the part where the GIF trigger this from the atom command palette with a hotkey).
 
OK.
 
> You can even add qualifiers like page/section names etc in the picker, and they'll come through, formatted for LaTeX. That's not even possible in the steps-3-7 workflow.

Sorry, I don't see what you mean here.

> > Thanks! But it is worth only if the resulting workflow would be more efficient than the mine above.
> 
> That only you can decide. It's trivial for me to add.

IMHO, the two workflows are equivalent, though CAYW a bit quicker, but a bit less user friendly: you have to _type_ instead of just select in a list. I guess it is a matter of taste, so providing it would be very nice!

> > Come on, come on! A so good add-on developer, using `vim` and not `Emacs`?! :stuck_out_tongue_winking_eye:
> 
> Ah yeah but I have this genetic deficiency where I have only 10 fingers.
> 
> Vim is what I started with, it's in my muscle memory. I've tried to love emacs (with `evil` installed, natch, because that is obviously both the most natural and generally superior way to use text editors; I'm sure you're familiar with the cliché _"emacs is a great operating system, lacking only a decent editor"_), but I just kept banging into the familar walls (no, I do _not_ want an empty... buffer?! WTF is a "buffer"?!
 
:wink:
 
> how do I `:wq`?! _AAARGH!!!!_.) and in the end it wasn't worth the effort.

How did you say? Ah, yes, "poor buggers stuck in..." :stuck_out_tongue_winking_eye:

> I will grant that vimscript is an abomination, and scheme beautiful.

You're honesty honors you! :wink: 

> I'm sure an Emacs-supremacist would be eager to show how easy it would be to integrate it into emacs wink . All you'd have to do is to make `Ctrl-Meta-Shift-Alt-/⍳¨⍴⌹⍟ph'nglui mglw'nafh-Cthulhu-R'lyeh-wgah'nagl-fhtagn` call `curl` and paste the returned text into the buffer.

Ah, excellent! : ROTFL :laughing:

**Comment by dbitouze** [comment]
> With 5554, try binding a shortcut key to
> 
> ```
> curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'
> ```

Works like a charm! Many thanks!

Is the underlying API (`format`, `command`, `minimize`, etc.) documented somewhere?

**Comment by retorquere** [comment]
> > You can even add qualifiers like page/section names etc in the picker, and they'll come through, formatted for LaTeX. That's not even possible in the steps-3-7 workflow.
> 
> Sorry, I don't see what you mean here.

After you've picked an item, it will turn into a blue semi-rectangle in the picker; click that blue thing and you can fill out page number, or section number, and a few other locators, citation prefix/postfix, and author suppression. If you fill those out, BBT will format them (as far as is allowed by the format chosen) into the returned text. You can select multiple items BTW for a multi-cite and BBT will format them properly for the chosen format (if the format allows it).

> IMHO, the two workflows are equivalent, though CAYW a bit quicker, but a bit less user friendly: you have to _type_ instead of just select in a list. I guess it is a matter of taste, so providing it would be very nice!

Click on the red "Z" at the left and select Classic View. This is not my work BTW, this is just the regular Zotero citation picker. I've just repurposed it for latex/markdown picking.

Additionally, 5556 will drop here shortly, and then you can add `selected=true` (or `selected=true&minimize=true`) and it won't show the picker at all and just grab whatever you had selected in Zotero. No locators/prefix etc for this of course.

> How did you say? Ah, yes, "poor buggers stuck in..." 😜

touch\\'e

> Is the underlying API (`format`, `command`, `minimize`, etc.) documented somewhere?

Probably not sufficiently so, but what there is is at https://retorque.re/zotero-better-bibtex/citing/cayw/. I have added `selected` and `texstudio` in draft at https://github.com/retorquere/zotero-better-bibtex/blob/gh-1371/site/content/citing/cayw.md and that will go live when I merge the changes for this issue into master.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5556](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5556.xpi) ("selected")

Install in Zotero by downloading [test build 5.1.176.5556](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5556.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dbitouze** [comment]
> After you've picked an item, it will turn into a blue semi-rectangle in the picker; click that blue thing and you can fill out page number, or section number, and a few other locators, citation prefix/postfix, and author suppression. If you fill those out, BBT will format them (as far as is allowed by the format chosen) into the returned text. You can select multiple items BTW for a multi-cite and BBT will format them properly for the chosen format (if the format allows it).

Ah, very nice! The only drawback is it cannot be activated just with the keyboard.

> > IMHO, the two workflows are equivalent, though CAYW a bit quicker, but a bit less user friendly: you have to _type_ instead of just select in a list. I guess it is a matter of taste, so providing it would be very nice!
> 
> Click on the red "Z" at the left and select Classic View. This is not my work BTW, this is just the regular Zotero citation picker. I've just repurposed it for latex/markdown picking.

Nice but it cannot be activated just with the keyboard either. Moreover multiple selection is not possible.

> Additionally, 5556 will drop here shortly, and then you can add `selected=true` (or `selected=true&minimize=true`) and it won't show the picker at all and just grab whatever you had selected in Zotero. 

Very nice! It is a kind of "Push references to TeXstudio", except it relies on `xbindkeys` or similar, and hence is not out of the box.

The only (other) drawback is: after you hit the relevant `xbindkeys` shortcut, Zotero window is minimized (nice!) but hence is the last (or, even worse, the penultimate if there was already another minimized window) in the <kbd>Alt</kbd>+<kbd>Tab</kbd>-stack and hence needs, when you need again to select references, the not very handy <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> shortcut to be brought at the foreground.

> > How did you say? Ah, yes, "poor buggers stuck in..." stuck_out_tongue_winking_eye
> 
> touch\'e
> 
> > Is the underlying API (`format`, `command`, `minimize`, etc.) documented somewhere?
> 
> Probably not sufficiently so, but what there is is at https://retorque.re/zotero-better-bibtex/citing/cayw/.

Sorry, I missed this (mostly because "DIY" does not evoke anything for me).

> I have added `selected` and `texstudio` in draft at https://github.com/retorquere/zotero-better-bibtex/blob/gh-1371/site/content/citing/cayw.md and that will go live when I merge the changes for this issue into master.

Nice!

**Comment by retorquere** [comment]
> Ah, very nice! The only drawback is it cannot be activated just with the keyboard.

That is true (AFAIK), but then you can hardly select items to push by just typing. But you could open a request for that at Zotero. If it changes for the word processor plugins, it changes here, because it uses the same facility.

> Nice but it cannot be activated just with the keyboard either. Moreover multiple selection is not possible.

True. Again, if it changes for the word processor plugins, that will change here too.

> Very nice! It is a kind of "Push references to TeXstudio", except it relies on `xbindkeys` or similar, and hence is not out of the box.

That is true. But an out of the box solution would be hard to do anyway -- if you're typing in TXS, Zotero (and thus BBT) can not watch the input for hotkeys being pressed.

> The only (other) drawback is: after you hit the relevant `xbindkeys` shortcut, Zotero window is minimized (nice!) but hence is the last (or, even worse, the penultimate if there was already another minimized window) in the Alt+Tab-stack and hence needs, when you need again to select references, the not very handy Alt+Shift+Tab shortcut to be brought at the foreground.

True, but options to fix that would again run into the same problem -- either Zotero has focus while you do this but then Zotero can't know what the focused program used to be, or your editor has focus and then Zotero can't listen for shortcut keys.

And also, I'm not going to do per-platform work on BBT. Sorry. Live's too short.

> > I have added `selected` and `texstudio` in draft at https://github.com/retorquere/zotero-better-bibtex/blob/gh-1371/site/content/citing/cayw.md and that will go live when I merge the changes for this issue into master.
> 
> Nice!

That is, as soon as we settle on a solution that works for you that works for me. If you're satisfied with the current state, then I can merge.

**Comment by dbitouze** [comment]
> > Ah, very nice! The only drawback is it cannot be activated just with the keyboard.
> 
> That is true (AFAIK), but then you can hardly select items to push by just typing. But you could open a request for that at Zotero. If it changes for the word processor plugins, it changes here, because it uses the same facility.

OK.

> > Nice but it cannot be activated just with the keyboard either. Moreover multiple selection is not possible.
> 
> True. Again, if it changes for the word processor plugins, that will change here too.

OK.

> > Very nice! It is a kind of "Push references to TeXstudio", except it relies on `xbindkeys` or similar, and hence is not out of the box.
> 
> That is true. But an out of the box solution would be hard to do anyway -- if you're typing in TXS, Zotero (and thus BBT) can not watch the input for hotkeys being pressed.


OK but, what I don't understand is why BBT or Zotero cannot have a button, menu or (better) shortcut that runs:

`curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&selected=true&minimize=true'
`
> > The only (other) drawback is: after you hit the relevant `xbindkeys` shortcut, Zotero window is minimized (nice!) but hence is the last (or, even worse, the penultimate if there was already another minimized window) in the Alt+Tab-stack and hence needs, when you need again to select references, the not very handy Alt+Shift+Tab shortcut to be brought at the foreground.
> 
> True, but options to fix that would again run into the same problem -- either Zotero has focus while you do this but then Zotero can't know what the focused program used to be, or your editor has focus and then Zotero can't listen for shortcut keys.

I meant: is it possible to put Zotero not as the last <kbd>Alt</kbd>+<kbd>Tab</kbd>-stack place, but at the second place, making it easy to reach with just <kbd>Alt</kbd>+<kbd>Tab</kbd>?

> And also, I'm not going to do per-platform work on BBT. Sorry. Live's too short.

I understand :)

> That is, as soon as we settle on a solution that works for you that works for me. If you're satisfied with the current state, then I can merge.

Well, just the two points above (sorry!).

**Comment by retorquere** [comment]
> OK but, what I don't understand is why BBT or Zotero cannot have a button, menu or (better) shortcut that runs:
> 
> `curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&selected=true&minimize=true' `

That is possible, but I wouldn't have it call this but just call the method that sits behind it directly. Anyhow, that runs into the earlier issue we talked about that there's no central coordinating facility that manages shortcuts, and de-facto, the central facility has become Zutilo.

> I meant: is it possible to put Zotero not as the last Alt+Tab-stack place, but at the second place, making it easy to reach with just Alt+Tab?

I have no idea. The concept of an alt-tab stack is window-manager-specific -- if you ran `i3` for example, the concept of a window stack is very different (one might say absent).

> Well, just the two points above (sorry!).

**Comment by dbitouze** [comment]
> > OK but, what I don't understand is why BBT or Zotero cannot have a button, menu or (better) shortcut that runs:
> > `curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&selected=true&minimize=true' `
> 
> That is possible, but I wouldn't have it call this but just call the method that sits behind it directly.

OK.

> Anyhow, that runs into the earlier issue we talked about that there's no central coordinating facility that manages shortcuts, and de-facto, the central facility has become Zutilo.

Ooops, indeed, sorry. I become confused because of all what we discussed. So, do you plan to implement what [you nicely proposed](https://github.com/retorquere/zotero-better-bibtex/issues/1371#issuecomment-569454366):

>Zutilo should be able to provide a shortcut; all it'd have to do is test for the presence of Zotero.BetterBibTeX (to know that BBT is installed) and then call Zotero.BetterBibTeX.ZoteroPane.toTeXstudio().

> > I meant: is it possible to put Zotero not as the last Alt+Tab-stack place, but at the second place, making it easy to reach with just Alt+Tab?
> 
> I have no idea. The concept of an alt-tab stack is window-manager-specific -- if you ran `i3` for example, the concept of a window stack is very different (one might say absent).

Good point.

**Comment by retorquere** [comment]
> Ooops, indeed, sorry. I become confused because of all what we discussed. So, do you plan to implement what [you nicely proposed](https://github.com/retorquere/zotero-better-bibtex/issues/1371#issuecomment-569454366):

That wasn't a proposal, that's what's already there 😄

**Comment by dbitouze** [comment]
> > Ooops, indeed, sorry. I become confused because of all what we discussed. So, do you plan to implement what [you nicely proposed](https://github.com/retorquere/zotero-better-bibtex/issues/1371#issuecomment-569454366):
> 
> That wasn't a proposal, that's what's already there smile

**Comment by retorquere** [comment]
No I meant the plumbing is there in BBT; that's the part I can do. It's up to zutilo to implement the actual shortcut key if he agrees.

**Comment by dbitouze** [comment]
> No I meant the plumbing is there in BBT; that's the part I can do. It's up to zutilo to implement the actual shortcut key if he agrees.

OK. Am I supposed to open an issue in Zutilo's repository for this request? If so, I guess I have to wait for the next BBT's release .

**Comment by retorquere** [comment]
I'll probably merge tonight, but that stuff has been in BBT for a while.

Yes, you will have to open an issue on Zutilo. You can tag me there and I'll help, but you're the primary user for the functionality, so you drive the conversation.
