### ISSUE TITLE
Merging error with arXiv ID

### ISSUE THREAD

**Issue by qqobb** [retorquere/zotero-better-bibtex#1373]
**Report ID:** 8FKT6VFB-euc

**Expected behavior:** Merging two items with arXiv IDs in the Extra field should result in an item with an arXiv ID. 

**Actual behavior:** The merged item has "tex.arxiv: [object Object]" in the Extra field. 

**Steps to reproduce:**
1. Import an arXiv ID twice through Zotero's "Add Item(s) by Identifier" tool, e.g. 1108.2700
2. Both will have "arXiv: 1108.2700" in the Extra field
3. Merge both versions
4. For the merged item the arXiv ID is no longer shown. The Extra field reads: 
<code>Citation Key Alias: Ginsparg2011</code>
<code>tex.arxiv: [object Object]</code>

**Comment by retorquere** [comment]
Can you right-click the two pre-merge items and select "Send Debug report" from the popup menu that appears? 8FKT6VFB-euc is from the help menu and that doesn't give me sample references to test with.

**Comment by qqobb** [comment]
Report IDs
**pre-merge:** PHT6238J-euc
**post-merge:** DU8TA4IP-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5500](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5500.xpi) ("fixes #1373")

Install in Zotero by downloading [test build 5.1.176.5500](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5500.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 5500?

**Comment by qqobb** [comment]
I tried 5500 and it works well. Thanks a lot! A minor issue is that the merged item has "arxiv:" instead of "arXiv:", you could change this for consistency.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5503](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5503.xpi) ("fix arXiv casing")

Install in Zotero by downloading [test build 5.1.176.5503](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5503.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
It's only an aesthetic difference, as it all means the same to Zotero, but 5503 outputs `arXiv`.

**Comment by qqobb** [comment]
5503 works perfectly. Thanks a lot!
