### ISSUE TITLE
Wrong height of Zotero's "Preferences" dialog box when started on BBT tab

### ISSUE THREAD

**Issue by qqobb** [retorquere/zotero-better-bibtex#1374]
BBT 5.1.176
Windows 10

**Issue:** When started on the BBT tab, Zotero's "Preferences" dialog box starts with a minimized height.

**Steps to reproduce:**
1. Open Zotero's "Preferences" dialog box.
2. Select the BBT tab & close "Preferences".
3. Reopen "Preferences". It will be started on the BBT tab, but with the wrong height, with the lower part minimized. Selecting a non-BBT tab fixes the height. Again selecting the BBT tab allows viewing the BBT preferences.

**Likely related minor issue:** With BBT enabled, Zotero's "Preferences" dialog box starts with a maximized height on the "Gereral" tab. This is not the case with BBT disabled.

**Comment by retorquere** [comment]
Are you sure it doesn't pop to the right size after the BBT has finished initializing?

**Comment by qqobb** [comment]
There seemed to be nothing related in Zotero's "Debug Output Logging".

**Comment by retorquere** [comment]
Yeah you can ignore label-gun for now.

**Comment by qqobb** [comment]
Initialization seems unrelated. Zotero was running for a longer time.

**Comment by qqobb** [comment]
I observed this issue both in my production and test setups. However, I cannot reproduce it on the test setup at the moment.

**Comment by retorquere** [comment]
Alright. I can't currently reproduce this on my mac or linux system, and I don't have access to a windows system. I'll have to see if there's anything odd in the code that could do this, but honestly, UI work was never my forte, and it shows (a minor excuse in this is that XUL is incredibly poorly documented)

**Comment by qqobb** [comment]
I'm still having it on the production setup which runs Zotero beta. But feel free to close the issue. There is a workaround in point 3 above in the steps to reproduce.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5492](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5492.xpi) ("XUL is broken in so many weird ways")

Install in Zotero by downloading [test build 5.1.176.5492](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5492.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Ah, on the beta. I hadn't tried that. But on Linux (which is my main dev env), I can't reproduce it on the beta either. Can you try whether 5429 improves matters? If not, can you get me a screenshot and a debug log?

**Comment by qqobb** [comment]
After some checks it seems that I could identify the issue:

1. The fix 5429 didn't resolve the issue.
2. The issue is not related to Zotero beta. It was the same on Zotero 5.0.80. 
3. It's not due to some preferences in Zotero's profile folder. I copied the profile from the production to the test setup, but couldn't reproduce the issue. Perhaps I never had it on the test setup.
4. It turned out that this is a display scaling issue. On a WQHD laptop screen and Windows 10's <a href="https://superuser.com/a/954582">"Change the size of text, apps, and other items"</a> set to 150%, the "Preferences" window looks like this:
<img width="496" alt="BBTissue1" src="https://user-images.githubusercontent.com/52924060/71784199-083c1300-2ff1-11ea-9af0-d44c8a5840f1.png">

Resetting the scaling to 100% removes the issue. (I will keep using the scaling setting, though.)

In Zotero's "Error Console", this possibly related warning message is shown:
<img width="470" alt="BBTissue2" src="https://user-images.githubusercontent.com/52924060/71784206-1ab64c80-2ff1-11ea-93f0-137a92fa7466.png">

I suspect that the vertical size of BBT's "Advanced" tab in the "Preferences" has increased in one of the more recent BBT updates. This might be why BBT now needs to change the vertical size.

If you want to avoid the issue for people with settings like mine, a solution might be to somehow redistribute the content of BBT's "Advanced" tab to a further tab, such that the vertical size of the "Preferences" can remain unchanged. (Note that the scaling problem only occurs with BBT enabled.) The issue might, however, only affect few people. Since starting "Preferences" on the "General" tab provides a proper workaround, I don't mind if you keep the current layout. It might be something to keep in mind for future changes.

**Comment by retorquere** [comment]
Nah, I'll have a look. That warning might have something to do with it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5502](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5502.xpi) ("remove XUL warning")

Install in Zotero by downloading [test build 5.1.176.5502](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5502.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
5502 should at least take care of the warning. No idea whether it'll help with the visual problems you're seeing. If not, I'll look into redistributing the advanced tab.

**Comment by qqobb** [comment]
5502 didn't resolve the issue. The warning message is also not gone. It's possible that the amount of warning messages is reduced. (It's always the same one.) I now get one message per opening the "Preferences". It could have been multiple repetitions before, but I'm not sure. Redistributing would be great. Most likely this would solve it.

**Comment by retorquere** [comment]
Oh I thought you meant you saw a lot of those warnings for BBT prefs. The screenshot above shows a warning wrt zotero's own pref dialogs, I can't do anything about those.

I'll do a redistribute of the pane tomorrow. It's pretty late here now.

**Comment by qqobb** [comment]
Ok, thanks! Yes, I was talking about the second screenshot above. I thought there was no other warning, there was also nothing in the debug output, if I remember correctly. Have a good night!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5507](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5507.xpi) ("split out advanced")

Install in Zotero by downloading [test build 5.1.176.5507](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5507.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
One last build before I tap out. This redistributes the advanced pane, I hope enough to fix this.

**Comment by retorquere** [comment]
I am prepping for a new release -- I'd love it if this could be in it. Can you see if 5507 does the job for you?

**Comment by qqobb** [comment]
5507 provides an improvement. It's unfortunately not a full fix. The origin of the issue seems to be the Fx60 update, not the height of BBT's preferences as I had suspected.

I could reproduce the "Preferences" issue on my test setup with an external WQHD monitor. This allowed me to do some checks with fresh Zotero installations. It turned out that the issue first appeared with Zotero 5.0.78. Changes in BBT didn't cause it:
1. Zotero 5.0.77 & BBT 5.1.164 (en): issue is absent
2. Zotero 5.0.78 & BBT 5.1.164 (en): issue has appeared
3. Zotero 5.0.80 & BBT 5.1.176.5507 (en+...): issue is present
4. Zotero 5.0.80 & BBT 5.1.176.5507 (de+fr): broken, see (b) below

With the new and clearer layout of 5507, one no longer needs to close and reopen the Preferences for viewing the bottom part of BBT's "Advanced" tab. Clicking the "General" tab once is enough to see everything. So it would be great if this could be included in your new release.

I think I spotted two errors in 5507, though:
(a) In BBT's advanced preferences, "Reset cache" should be in Export, not Import.
(b) The French and German locales seem broken, there's no BBT tab in the Preferences. Other languages seem fine.

I also observed some errors in both 1. and 4., but I'm not sure they are relevant for the issue:
<img width="470" alt="BBTissue3" src="https://user-images.githubusercontent.com/52924060/71869135-39ac0000-3111-11ea-8476-5cff2a9e23dc.png">
(Note that 1. didn't show the issue.)

Also, note that the issue does not occur with a scaling of e.g. 125%, so it should really be quite rare; only 150% seems toxic. Let's put the issue aside after the layout changes of 5507.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5526](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5526.xpi) ("move reset cache")

Install in Zotero by downloading [test build 5.1.176.5526](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5526.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
> 5507 provides an improvement. It's unfortunately not a full fix. The origin of the issue seems to be the Fx60 update, not the height of BBT's preferences as I had suspected.

I mean... it could still be I'm doing something wrong that just happened to work on older FFs. But the knowledge and docs about how XUL works or is supposed to work is growing scarcer every day. I'm certainly no expert.

> With the new and clearer layout of 5507, one no longer needs to close and reopen the Preferences for viewing the bottom part of BBT's "Advanced" tab. Clicking the "General" tab once is enough to see everything. So it would be great if this could be included in your new release.

Super.

> I think I spotted two errors in 5507, though:
> (a) In BBT's advanced preferences, "Reset cache" should be in Export, not Import.

Fixed.

> (b) The French and German locales seem broken, there's no BBT tab in the Preferences. Other languages seem fine.

Yeah, translations always roll in a bit later. 5534 will have them. 5526 has English stand-ins.

> I also observed some errors in both 1. and 4., but I'm not sure they are relevant for the issue:
> <img alt="BBTissue3" width="470" src="https://user-images.githubusercontent.com/52924060/71869135-39ac0000-3111-11ea-8476-5cff2a9e23dc.png">

The pathSearch errors are harmless, I'm looking for `git` and `texstudio` in the path, and for some reason just asking whether a file exists in a non-existent directory evokes this message. It's caught and handled but I can't prevent it showing up in the log.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5534](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5534.xpi) ("Merge branch 'master' into gh-1374")

Install in Zotero by downloading [test build 5.1.176.5534](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5534.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by qqobb** [comment]
5534 looks good, thanks a lot!

**Comment by qqobb** [comment]
See the [Zotero forum](https://forums.zotero.org/discussion/comment/351429/#Comment_351429) for a workaround.

**Comment by qqobb** [comment]
(The issue can be closed.)
