### ISSUE TITLE
Book chapter citation using p. instead of pp.

### ISSUE THREAD

**Issue by alvinyxz** [retorquere/zotero-better-bibtex#1375]
Hi Better Bibtex developer,

Thanks for your great work on improving Zotero's bib tex experience. I have a minor issue with the current citation style though.

According to APA 6th/7th, when citing a book chapter, the page number should be formatted as "pp. XX-XX." But currently when I am using Better BibTex and apacite as the LaTex citation style, the produced reference list uses "p. XX-XX".

So, instead of showing:
Faraj, S., & Azad, B. (2012). The materiality of technology: An aﬀordance perspective. In P. M. Leonardi, B. A. Nardi, & J. Kallinikos (Eds.), Materiality and organizing: Social interaction in a technological world (pp. 237-258). Oxford University Press.

It is currently showing:
Faraj, S., & Azad, B. (2012). The materiality of technology: An aﬀordance perspective. In P. M. Leonardi, B. A. Nardi, & J. Kallinikos (Eds.), Materiality and organizing: Social interaction in a technological world (p. 237-258). Oxford University Press.

Is there a simple way that I can change this?

**Comment by retorquere** [comment]
BBT doesn't really deal with styles. Rendering of bibliography is done outside Zotero for bibtex references.

**Comment by alvinyxz** [comment]
Thanks for the reply. So I compared the bib file exported by Zotero (which shows "pp." in Latex) and  the bib file exported by Better Bibtex (which shows "p." in Latex), and got this:

![Exported by Zotero](https://user-images.githubusercontent.com/7898190/71784444-99939100-2fc1-11ea-8a84-2df9ab586cc8.png)

<img width="713" alt="Picture2" src="https://user-images.githubusercontent.com/7898190/71784453-a87a4380-2fc1-11ea-9fe9-f227c0e63995.png">

I suppose it's the difference between "269--286" and "269-286" that is causing the problem.

Is it possible to export items using two hyphens with Better Bibtex?

**Comment by retorquere** [comment]
Can you right-click that reference and send a debug log (see instructions from label-gun above)?

**Comment by alvinyxz** [comment]
Sure, the report ID is 98NJVCJX-euc

It is not only this specific reference. All items exported by Better Bibtex use "pages = {XXX-XXX}" while all items exported by Zotero use "pages = {XXX--XXX}"

**Comment by retorquere** [comment]
That's not unexpected, but this gives me a specific sample to look at (and if a fix is needed, a testcase to prevent regression)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5496](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5496.xpi) ("fixes #1375")

Install in Zotero by downloading [test build 5.1.176.5496](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5496.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5499](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5499.xpi) ("update test case")

Install in Zotero by downloading [test build 5.1.176.5499](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5499.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 5499?

**Comment by alvinyxz** [comment]
I tried, and it works now! Thank you.
