### ISSUE TITLE
Pull export no longer working

### ISSUE THREAD

**Issue by clarino** [retorquere/zotero-better-bibtex#1376]
I use Zotero 5.0.80 and TeXShop 4.44.
Pull commands like
   \addbibresource[location=remote]
     {http://localhost:23119/better-bibtex/collection?/1/Teaching.biblatex}
used to work, but now result in an error:
   ERROR - Could not fetch 'http://localhost:23119/better-bibtex/collection?/1/Teaching.biblatex' 
   (HTTP code: 403)
It is noted that as of Zotero 5.0.71, access to such URLs will no longer work from the browser for security reasons; however, TeXShop is not a browser.
Is there any way the Apache settings on the local machine need to be modified to fix this problem?

**Comment by clarino** [comment]
No BBT debug report was generated after attempting to fetch the data source from Zotero as described.

**Comment by retorquere** [comment]
TeXshop is not a browser, but unfortunately, it identifies itself as one -- it sends 

```
User-Agent: Mozilla/5.0
```

as one of its headers. If TeXshop could either not send that header, send a different user-agent, or send an extra header:

```
zotero-allowed-request: true
```

then Zotero will let it in. This is not something I can (or want to) change, Zotero put this in place for good reasons.

**Comment by retorquere** [comment]
Is it texshop though that does the request? I thought it was biber itself that sent the request?

**Comment by clarino** [comment]
Installing the latest biber binary and the latest update of the biblatex package solved the issue for me. This suggests that the problem will also be solved in the next release of TeX Live (2020).
