### ISSUE TITLE
LaTeX commands in Zotero should be exported untouched

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1380]
**Report ID:**
Z5WUMPLW-euc
**Exporter used:**
Better BibLaTeX
**Expected behavior:**
LaTeX commands in Zotero should be exported untouched.
**Actual behavior:**
LaTeX commands in Zotero are changed during export.

I'm aware of the what is suggested in #124 (`<pre>... </pre>` and `#LaTeX` tag) but, in the settings, I don't see any "retain LaTeX on import" option (mentioned in https://github.com/retorquere/zotero-better-bibtex/issues/124#issuecomment-66689336) which would be easier to use.

 For instance, `\LaTeX{}` is exported as `{\textbackslash{}LaTeX\{\}`. As a consequence, the following exported reference:
```bibtex
@book{MittelbachLaTeXCompanion2006,
  langid = {french},
  location = {{Paris}},
  title = {\textbackslash{}LaTeX\{\} Companion},
  edition = {2},
  isbn = {978-2-7440-7182-9},
  pagetotal = {1008},
  publisher = {{Pearson Education France}},
  date = {2006-02},
  author = {Mittelbach, Frank and Goossens, Michel},
  translator = {André, Jacques and Bellet, Benoît and Charpentier, Jean-Côme and Hufflen, Jean-Michel and Soulet, Yves}
}
```
with the following `.tex` file:
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{csquotes}
\usepackage{biblatex}
%
\addbibresource{\jobname.bib}
\nocite{*}
%
\begin{document}
\printbibliography
\end{document}
```
results in (note the undesirable line break):

![test](https://user-images.githubusercontent.com/1032633/71878207-5ead6c80-312b-11ea-8f39-8130cbc1456f.png)

By contrast, the following `.tex` file:
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{csquotes}
\usepackage{biblatex}
%
\begin{filecontents}{\jobname.bib}
@book{MittelbachLaTeXCompanion2006-bis,
  langid = {french},
  location = {{Paris}},
  title = {\LaTeX{} Companion},
  edition = {2},
  isbn = {978-2-7440-7182-9},
  pagetotal = {1008},
  publisher = {{Pearson Education France}},
  date = {2006-02},
  author = {Mittelbach, Frank and Goossens, Michel},
  translator = {André, Jacques and Bellet, Benoît and Charpentier, Jean-Côme and Hufflen, Jean-Michel and Soulet, Yves}
}
\end{filecontents}
%
\addbibresource{\jobname.bib}
\nocite{*}
%
\begin{document}
\printbibliography
\end{document}
```
results in:

![test](https://user-images.githubusercontent.com/1032633/71878550-29554e80-312c-11ea-87fd-576165503fcd.png)

**Comment by retorquere** [comment]
You're discussing two separate issues. One is what the entry should look like in Zotero after import, the other is what an existing Zotero entry should look like when exported. We can look at both if you want, but they're not one concern; BBT export can't know how an entry got into Zotero (I can't tell whether you typed in an entry manually or it was imported by BBT or something else). BBT export takes the item as it exists in Zotero as its point of departure.

### 1

This seems like you want to have the option (again) to import

```
@book{MittelbachLaTeXCompanion2006,
  langid = {french},
  location = {{Paris}},
  title = {\LaTeX Companion},
  edition = {2},
  isbn = {978-2-7440-7182-9},
  pagetotal = {1008},
  publisher = {{Pearson Education France}},
  date = {2006-02},
  author = {Mittelbach, Frank and Goossens, Michel},
  translator = {André, Jacques and Bellet, Benoît and Charpentier, Jean-Côme and Hufflen, Jean-Michel and Soulet, Yves}
}
```

and have that `\LaTeX` show up in Zotero as `\LaTeX`, and not as `LaTeX`. This is not currently possible but it's feasible to add it.

### 2

the other is that you want an entry that has `Title: \LaTeX Companion` in Zotero to be exported as

```
title = {\LaTeX Companion}
```

this is already possible by adding the tag `#LaTeX` to the item.

**Comment by dbitouze** [comment]
>You're discussing two separate issues. One is what the entry should look like in Zotero after import,

Do you mean after import in Zotero from a website? If so, no, I didn't want to discuss that point.

>the other is what an existing Zotero entry should look like when exported.

Do you mean what an existing Zotero entry should look like when exported by BBT to a `.bib` file? If so, yes, that's what I wanted to discuss.

> We can look at both if you want, but they're not one concern; BBT export can't know how an entry got into Zotero (I can't tell whether you typed in an entry manually or it was imported by BBT or something else). BBT export takes the item as it exists in Zotero as its point of departure.

OK.

> ### 1
> 
> This seems like you want to have the option (again) to import

Import? No, the other way round (see below).

> ```
> @book{MittelbachLaTeXCompanion2006,
>   langid = {french},
>   location = {{Paris}},
>   title = {\LaTeX Companion},
>   edition = {2},
>   isbn = {978-2-7440-7182-9},
>   pagetotal = {1008},
>   publisher = {{Pearson Education France}},
>   date = {2006-02},
>   author = {Mittelbach, Frank and Goossens, Michel},
>   translator = {André, Jacques and Bellet, Benoît and Charpentier, Jean-Côme and Hufflen, Jean-Michel and Soulet, Yves}
> }
> ```
> 
> and have that `\LaTeX` show up in Zotero as `\LaTeX`, and not as `LaTeX`.
> This is not currently possible but it's feasible to add it.

Let me explain my workflow: after importing https://www.amazon.fr/Latex-Companion-1DVD-Frank-Mittelbach/dp/274407182X in Zotero, the Zotero title field contained "Latex Companion" that I manually changed (among others changes) into "\LaTeX{} Companion". Afterwards I exported this reference to a `.bib` file thanks to BBT.

> ### 2
> 
> the other is that you want an entry that has `Title: \LaTeX Companion` in Zotero to be exported as
> 
> ```
> title = {\LaTeX Companion}
> ```

Indeed, except `\LaTeX` should be `\LaTeX{}`

> this is already possible by adding the tag `#LaTeX` to the item.

Indeed, but it is a per-entry option, which is tedious if one has several items that need this tag. What would be useful is a "retain LaTeX on import" option in the BBT settings, as mentioned in https://github.com/retorquere/zotero-better-bibtex/issues/124#issuecomment-66689336.

**Comment by retorquere** [comment]
> Do you mean after import in Zotero from a website? 

I mean whenever you import bibtex, regardless of whether it comes from a file or a website. 

> Do you mean what an existing Zotero entry should look like when exported by BBT to a .bib file? If so, yes, that's what I wanted to discuss.

Yes, that's what I mean. 

> Let me explain my workflow: after importing https://www.amazon.fr/Latex-Companion-1DVD-Frank-Mittelbach/dp/274407182X in Zotero, the Zotero title field contained "Latex Companion" that I manually changed (among others changes) into "\LaTeX{} Companion". 

From the point of view of BBT, it doesn't matter how the item got into zotero, or what you edited when. BBT just looks at the item as it is at time of export. The history of the item is not available in Zotero... 

> Afterwards I exported this reference to a .bib file thanks to BBT.

...so as far as BBT is concerned, there is no "afterwards". 

> Indeed, except \LaTeX should be \LaTeX{}

Yes, to preserve the space.

> Indeed, but it is a per-entry option, which is tedious if one has several items that need this tag. What would be useful is a "retain LaTeX on import" option in the BBT settings, as mentioned in #124 (comment).

That's where I think we're talking past each other. This option wouldn't help you, because what you're asking concerns export, not import. How an items was imported, or even that it is imported, cannot be known to BBT. What you want is not "retain LaTeX on import", but "treat everything as if it has the `#LaTeX` tag even when it doesn't" 

I can add the latter option, but for the interim, you can select all entries and drag them onto the `#LaTeX` tag in the tag overview.

**Comment by dbitouze** [comment]
I guess I got confused because that both Zotero and BBT can both import and export :$

> > Do you mean after import in Zotero from a website?
> 
> I mean whenever you import bibtex, regardless of whether it comes from a file or a website.

Do you mean import a `.bib` file into Zotero? I couldn't even imagine it was possible. But that's not my concern.

>From the point of view of BBT, it doesn't matter how the item got into zotero, or what you edited when. BBT just looks at the item as it is at time of export. The history of the item is not available in Zotero...

OK.




> > Afterwards I exported this reference to a .bib file thanks to BBT.
> 
> ...so as far as BBT is concerned, there is no "afterwards". There is only "now".

Even if the automatic export isn't activated?

>This option wouldn't help you, because what you're asking concerns export, not import.

Indeed, sorry.

> How an item was imported, or even whether it is imported, cannot be known to BBT.

Understood.

> What you want is not "retain LaTeX on import", but "for export, treat everything as if it has the #LaTeX tag even when it doesn't"

Indeed.

>I can add the latter option,

Nice, thanks!

>but for the interim, you can select all entries and drag them onto the #LaTeX tag in the tag overview.

Indeed, thanks!

**Comment by retorquere** [comment]
> I guess I got confused because that both Zotero and BBT can both import and export :$

Yep, but if BBT is installed it takes precedence.

> Do you mean import a `.bib` file into Zotero? I couldn't even imagine it was possible. But that's not my concern.

Yep, very much possible.

> > ...so as far as BBT is concerned, there is no "afterwards". There is only "now".
> 
> Even if the automatic export isn't activated?

Automatic export is just a regular export that is triggered by changes to items rather than an UI action by the user -- no other difference. The history of the item (even the change that just happened) is not knowable inside Zotero. The part that does the actual export does not know (can not know) by what mechanism it was invoked.

**Comment by retorquere** [comment]
> I can add the latter option, but for the interim, you can select all entries and drag them onto the `#LaTeX` tag in the tag overview.

I had forgotten -- this is [already available](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/). If you set `rawLaTag` to `*`, all items will be treated as raw.

**Comment by dbitouze** [comment]
> I had forgotten -- this is [already available](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#rawlatag). If you set `rawLaTag` to `*`, all items will be treated as raw.

Indeed, nice! Nice, but a bit difficult to figure out such an option exist :smile:.

In fact, I cannot think of any situation where one doesn't want `rawLaTag` set to `*`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5551](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5551.xpi) ("fixes #1380 (even if it didn't ask for it")

Install in Zotero by downloading [test build 5.1.176.5551](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5551.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
> Indeed, nice! Nice, but a bit difficult to figure out such an option does exist 😄.

Hidden prefs are for things that are less commonly used (and because I don't like UI work). It's always OK to ask here.
 
> In fact, I cannot think of any situation where one doesn't want `rawLaTag` set to `*`.

if you have `rawImports` on, then yes, otherwise you'd never want it on. If your title is `Is 4 > 3? An investigation` and you have `rawLaTag = *`, you'd end up with

```
@article{citekey,
  title = {Is 4 > 3? An investigation}
}
```

which would render to `Is 4 ¿ 3? An investigation`. Believe it or not but most people don't have raw LaTeX in Zotero, and I only have it when there's stuff like math in the title.

**Comment by dbitouze** [comment]
> if you have `rawImports` on, then yes, otherwise you'd never want it on. If your title is `Is 4 > 3? An investigation` and you have `rawLaTag = *`, you'd end up with
> 
> ```
> @article{citekey,
>   title = {Is 4 > 3? An investigation}
> }
> ```
> 
> which would render to `Is 4 ¿ 3? An investigation`.

Good point!

And other, even worse, cases would be for all the TeX special characters: `# $ % & ~ _ ^ \ { }`, e.g. with `title = {Is 4$ better than nothing? An investigation}`... except maybe for the `\` special character that, I guess, is very rarely used except, precisely, for LaTeX commands. 

And, now, we go back to the subject of this issue :smile: "LaTeX commands in Zotero should be exported untouched". Hence, maybe it is worth having something different from `rawImports` and `rawLaTag`, dedicated to LaTeX commands...

**Comment by retorquere** [comment]
There's not enough information in Zotero to determine that something could be LaTeX; a backslash is perhaps not common in titles, but when typed into Zotero, it properly means a backslash, and should be exported as `\textbackslash{}`. "LaTeX commands in Zotero" *are* exported untouched if you set `rawLaTag` to `*`. I am not going to infer that something is LaTeX and other things are not -- LaTeX is hard enough to parse if you can assume it is valid. Semi-valid LaTeX? Big nope on that one.

In general, AFAIC, if you use LaTeX you are a Big Boy/Big Girl and your either have `rawLaTag` on, or content with the limitations of what can be put in the Zotero fields.

What would you have in mind besides `rawImports` (which does only structure parsing and auto-tags imported entries with `rawLaTag`) and `rawLaTag=*`? If you just want to exclude specific parts of text as raw LaTeX, that can already be done in a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5555](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5555.xpi) ("don't auto-tag if rawLaTag is set to *")

Install in Zotero by downloading [test build 5.1.176.5555](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5555.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dbitouze** [comment]
> There's not enough information in Zotero to determine that something could be LaTeX; a backslash is perhaps not common in titles, but when typed into Zotero, it properly means a backslash, and should be exported as `\textbackslash{}`. "LaTeX commands in Zotero" _are_ exported untouched if you set `rawLaTag` to `*`. I am not going to infer that something is LaTeX and other things are not -- LaTeX is hard enough to parse if you can assume it is valid. Semi-valid LaTeX? Big nope on that one.

I can understand.

> In general, AFAIC, if you use LaTeX you are a Big Boy/Big Girl and your either have `rawLaTag` on, or content with the limitations of what can be put in the Zotero fields.

Well, I'm not sure average LaTeX users and, even worse, LaTeX beginners could easily find the relevant information. But, once again, I can understand.

> What would you have in mind besides `rawImports` (which does only structure parsing and auto-tags imported entries with `rawLaTag`) and `rawLaTag=*`?

Sorry, still didn't read carefully enough and confused Im/Ex-port.

> If you just want to exclude specific parts of text as raw LaTeX, that can already be done in a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas).

OK, nice. IMHO should be (but I would understand if you would ask me to open a new issue for this):

- much more easily accessible,
- be applied to other "title" fields ("Short title", "Series title") and maybe other ones ("Abstract"?).

**Comment by retorquere** [comment]
> Well, I'm not sure average LaTeX users and, even worse, LaTeX beginners could easily find the relevant information. But, once again, I can understand.

BBT has a options available for configuring it. It can be overwhelming to find stuff on the site. All pages do include an "edit this page" button -- if you have suggestions for improvement, that button will create a pull request for the site.

> > If you just want to exclude specific parts of text as raw LaTeX, that can already be done in a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas).
> 
> OK, nice. IMHO should be (but I would understand if you would ask me to open a new issue for this):
> 
>     * much more easily accessible,

I'm open to suggestions on the how of that. I'm a little blind on the deficiencies of BBT since I of course know it fairly well.

>     * be applied to other "title" fields ("Short title", "Series title") and maybe other ones ("Abstract"?).

postscripts are just bits of javascript, you can do a lot of crazy stuff there to generated references. The code can change absolutely everything on the item being generated. There's some docs, but the docs are pretty dev-oriented, so I generally just have people tell me what they want done, and I do it, then post it on the postscript page as a sample.

**Comment by dbitouze** [comment]
> > Well, I'm not sure average LaTeX users and, even worse, LaTeX beginners could easily find the relevant information. But, once again, I can understand.
> 
> BBT has a options available for configuring it.

Do you mean through Preferences/Advanced/Config editor?

> It can be overwhelming to find stuff on the site. All pages do include an "edit this page" button -- if you have suggestions for improvement, that button will create a pull request for the site.

What I had in mind was a more exposed option in the UI.

> > > If you just want to exclude specific parts of text as raw LaTeX, that can already be done in a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas).
> > 
> > 
> > OK, nice. IMHO should be (but I would understand if you would ask me to open a new issue for this):
> > ```
> > * much more easily accessible,
> > ```
> 
> I'm open to suggestions on the how of that. I'm a little blind on the deficiencies of BBT since I of course know it fairly well.

Here too, what I had in mind was an option in the UI for "detect and protect LaTeX math formulas".

> > ```
> > * be applied to other "title" fields ("Short title", "Series title") and maybe other ones ("Abstract"?).
> > ```
> 
> postscripts are just bits of javascript, you can do a lot of crazy stuff there to generated references. The code can change absolutely everything on the item being generated. There's some docs, but the docs are pretty dev-oriented, so I generally just have people tell me what they want done, and I do it, then post it on the postscript page as a sample.

OK, I just suggested additional fields where LaTeX math formulas might be found.

**Comment by retorquere** [comment]
> > BBT has a options available for configuring it.
> 
> Do you mean through Preferences/Advanced/Config editor?

Yep. The more esoteric stuff is configurable but not exposed in the UI -- the preferences of BBT have gotten a little overwhelming (it may well be the case that BBT has as many configuration options as Zotero itself at this stage).

> What I had in mind was a more exposed option in the UI.

Most is exposed, but as said, the BBT prefs are overwhelming as is, so things that are rarely used aren't.

> Here too, what I had in mind was an option in the UI for "detect and protect LaTeX math formulas".

Ah so; no, sorry, definitely not in the way you have in mind. The postscript facility is exposed in the prefs, but individual postscript samples are not, and "detect and protect LaTeX math formulas" is not something I want to bake into BBT. A title like `Fish costs between $2 and $200 a kg` would consider `2 and ` to be math because that snippet uses a fairly naive heuristic. I want the choice of how that works and fixes for particular cases to be under direction of the individual user whose library it concerns. It is always OK to open an issue to ask "how do I do X in a postscript"; I will explain how if you want, or just make the postscript for you. But I'm not baking specific postscripts into BBT.

> OK, I just suggested additional fields where LaTeX math formulas might be found.

That's OK, but the choice regarding which fields to apply this to is up to the user. The samples on the docs site are just that -- samples. It is easy (and legitimate) to change them for your particular case into something like

```
if (Translator.BetterTeX) {
  if (reference.has.title) reference.add({ name: 'title', value: item.title.replace(/(\$.*?\$)/g, '<script>{$1}</script>') });
  if (reference.has.series) reference.add({ name: 'series', value: item.seriesTitle.replace(/(\$.*?\$)/g, '<script>{$1}</script>') });
  if (reference.has.shorttitle) reference.add({ name: 'shorttitle', value: item.shortTitle.replace(/(\$.*?\$)/g, '<script>{$1}</script>') });
}
```

or perhaps a little more generally

```
if (Translator.BetterTeX) {
  for (const [tex, zotero] of [['title', 'title'], ['series', 'seriesTitle'], ['shorttitle', 'shortTitle']]) {
    if (reference.has[tex]) reference.add({ name: tex, value: item[zotero].replace(/(\$.*?\$)/g, '<script>{$1}</script>') });
  }
}
```

I recognize most LaTeX users aren't necessarily javascript coders, which is why I'll write them on request. The postscript exists so that if I say "I don't want to affect all BBT users" I can also say "but here's how you do it anyway".

**Comment by dbitouze** [comment]
OK, thanks.
