### ISSUE TITLE
Not all Journals are abbreviated

### ISSUE THREAD

**Issue by O2-AC** [retorquere/zotero-better-bibtex#1383]
When I select the "Use Journal Abbreviations" checkbox on the automatic export, only some of my Journal titles will get abbreviated. Is there any way to provide a file containing custom abbreviations for journal titles?
I haven't found anything regarding this in the docs.

**Comment by retorquere** [comment]
I really do need that debug log, generated as label-gun describes it in point 1.

**Comment by O2-AC** [comment]
Debug ID: XWTZ64FF-euc
What I see exported:
```
@article{[citekey],
  title = {[title]},
  ...
  journaltitle = {Journal of Organometallic Chemistry}
```
What I expect:
```
@article{[citekey],
  title = {[title]},
  ...
  journaltitle = {J. Organomet. Chem. }
```

**Comment by retorquere** [comment]
That item has `Journal of Organometallic Chemistry` in the `Journal Abbr` field; if there's something there, that's always trusted to be the desired journal abbreviation.

**Comment by retorquere** [comment]
That is aside the fact that you currently can't provide a list of abbreviations; I can consider adding support for something like this, but:

1. that would be an enhancement, not a bug, and
2. If there's anything in the `Journal Abbr` field, I would always let that take precedence

**Comment by O2-AC** [comment]
So you are saying it is a problem caused directly by Zotero rather than BBT? Since Zotero is populating the `Journal Abbr` field?

**Comment by retorquere** [comment]
I don't think Zotero populates the Journal Abbr field unless an import specifically says it must be there. But if the field is filled, I'm trusting it's right.

**Comment by retorquere** [comment]
Does this answer your question?

**Comment by O2-AC** [comment]
Not really. Who does populate the fields, when I'm using the Firefox Plugin or the import via a doi then?

**Comment by retorquere** [comment]
Zotero populates them in the sense that the translator ("import instructions") for the particular site you imported that item from decided it had a journal abbreviation to offer. Zotero as a program doesn't have an opinion on this, and trusts what the import translator says. These import translators are managed by Zotero but often written by volunteers (like me). If you recall where you got that item, I could help point you to the right import translator so you can open an issue there to get that fixed.

**Comment by retorquere** [comment]
Does this answer your question?

**Comment by O2-AC** [comment]
I see. I assumed it Zotero would have a local database with abbreviations it would use globally over the literature database. I will have to find another way then. Thanks for the helpful feedback. I guess this issue can be closed, since the problem is not part of BBT.

**Comment by retorquere** [comment]
Zotero does have such a list (or rather an algorithm if I recall correctly), but if the translator specifies one, that's trusted to be correct. If you know what site it came from I can point you in the right direction to get it fixed.
