### ISSUE TITLE
Hidden preference to disable "Citation Key Alias"

### ISSUE THREAD

**Issue by qqobb** [retorquere/zotero-better-bibtex#1384]
I see the point of generating a "Citation Key Alias" upon item merge. But for me these entries are mostly not useful and lead to unwanted Citation Keys. It would be nice if there could be a hidden preference that prevents the generation of a "Citation Key Alias".

I'm often merging a preprint with a later journal publication. The preprint would e.g. have the automatic Citation Key "Author2020". When merged with a later journal version as the master item with automatic Citation Key "Author2020a", the merged item will have the key "Author2020a", while I would prefer "Author2020".

**Report ID:** JCX4IBG3-euc (pre-merge items)

**Expected behavior:** B8L35X2E-euc  (Report ID for desired post-merge item)

**Actual behavior:** Item with "Citation Key Alias" in the Extra field and post-fixed Citation Key.

**Comment by qqobb** [comment]
This would be an enhancement.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.176.5563](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5563.xpi) ("clear out alias on refresh")

Install in Zotero by downloading [test build 5.1.176.5563](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.176.5563.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 5563 first? There was a bug that when you refreshed the key, duplicates in the alias would not be removed. If you merge (getting key `Author2020a` and alias `Author2020`), then refresh (which should set the key to `Author2020`, the alias line should now disappear.

**Comment by qqobb** [comment]
5563 works well. Thanks a lot! With this, the benefit of the proposed hidden pref would be that one wouldn't need to refresh. But I could also do without it, since there is the Zutilo shortcut for refreshing.

**Comment by retorquere** [comment]
You'd still need to refresh. After the merge, the merged item has citekey `Troja2017a`, If you want that to be `Troja2017`, you refresh, and then the alias goes away. 

Do you mean you don't want the alias at all, or that you don't want it exported? Because if you don't want it exported, you can just add `ids` to `skip fields`. Otherwise I'd be be more inclined to add an option to set merge of `extra` fields on or off -- if I add one option now for the aliases, I'm going to have to add options for every one of them sooner rather than later, and that's not a path I'm willing to walk.

Although, it is of course that this is the one field that BBt adds of its own volition. Hmm.

**Comment by qqobb** [comment]
> Do you mean you don't want the alias at all

This was the proposed option. But the idea was that the key would automatically be refreshed upon merge. I think this was the behavior in the past, before the introduction of the alias. But let's keep it like in 5563. Having to refresh is not a big deal with Zutilo's shortcut. Also, using the key of the primary item makes sense, and the alias is there for a purpose. 

> Otherwise I'd be be more inclined to add an option to set merge of `extra` fields on or off

I don't understand this, since the alias is not an extra field pre-merge. It's only added post-merge.

Again, thanks a lot for 5563! I will be happy to use it in your coming release. I'm also looking forward to trying your update on #1061 in the near future :)

**Comment by qqobb** [comment]
Actually, this issue was mainly motivated by my recollection that the alias would prevent a refresh. That is, when there was a key `Trojan2017a` with alias `Trojan2017`, refreshing would not result in the key `Trojan2017`, i.e. the alias would pin the key. I just checked BBT 5.1.176 and this was not the case anymore. I guess there was some update previously that I didn't notice.

**Comment by retorquere** [comment]
> This was the proposed option. But the idea was that the key would automatically be refreshed upon merge. I think this was the behavior in the past, 

I think it might have been, but that must have been the Zotero 4 line. Keys refreshed automatically on a number of occasions there that they don't in the Z5 line of BBT.

> > Otherwise I'd be be more inclined to add an option to set merge of `extra` fields on or off
> 
> I don't understand this, since the alias is not an extra field pre-merge. It's only added post-merge.

That's what I meant by "of its own volition"

> Again, thanks a lot for 5563! I will be happy to use it in your coming release. I'm also looking forward to trying your update on #1061 in the near future :)

Testing for the current issue here actually uncovered a bug, so I'm fixing that, merging and drop the release. The background exports are super awesome (you have them now in the debug build BTW) and I'm pretty proud of getting it to work.
