### ISSUE TITLE
Better BibTeX Default parameters?

### ISSUE THREAD

**Issue by Fontanapink** [retorquere/zotero-better-bibtex#1385]
So, I installed Better BibTeX while in the middle of my thesis writing, and changed so many parameters of it so that it wouldn't mess up my already generated keys in the document.  However, now that I finished with my thesis, **I want to revert the configuration to the default one for Better BibTeX** so I can use it to its full potential, **but can't find anywhere on the internet which of those are.** 

For example, under citation key format I have: [zotero:clean] . Which one is the default one???

Thank you!

**Comment by retorquere** [comment]
I see the docs no longer list the defaults; I'll look into that, but for the interim, these are the defaults:
[defaults.json.txt](https://github.com/retorquere/zotero-better-bibtex/files/4046590/defaults.json.txt)

**Comment by retorquere** [comment]
You can go into the [hidden preferences pane](https://www.zotero.org/support/preferences/hidden_preferences) and right-click-reset all preferences that start with `extensions.zotero.translators.better-bibtex.` if you just want everything default.

The default citekey pattern is `[auth:lower][shorttitle3_3][year]`, but I'm not deeply opinionated on this, it's just my personal preference.

**Comment by Fontanapink** [comment]
Great thank you very much!

**Comment by retorquere** [comment]
Site has been updated
