### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1386]
**Your question/suggestion:**

Is there any changelog for BBT?

**Comment by retorquere** [comment]
There isn't, no.

**Comment by dbitouze** [comment]
> There isn't, no.

Too bad! IMHO, Changelogs even not detailing bug fixes ("Bug fixes" would be enough) but mentioning the new features would be welcome (otherwise we would miss some interesting ones).

**Comment by retorquere** [comment]
I've added a changelog for the last few versions. I'll try to keep it up to date, but TBH, it's not a major priority to me.

**Comment by dbitouze** [comment]
> I've added a changelog for the last few versions.

Thanks!

> I'll try to keep it up to date, but TBH, it's not a major priority to me.

I can understand.
