### ISSUE TITLE
BBT yields error with quality report

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#1387]
I just updated to BBT 5.2.4 (with Zotero 5.0.81-beta.17+7c1845b3a). Clicking on the "Export now" button in the BBT dialog box yields the message "Error: translation failed". I exported earlier today using the same version of Zotero but the previous version of BBT with no errors.

Report ID: XKD3B9BE-euc

Here's the error log:

```
Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'

[JavaScript Error: "{better-bibtex! +null} <Error: TypeError: this.has is undefined
check@resource://zotero-better-bibtex/Better%20BibLaTeX.js:10005:17
./bibtex/biblatex.qr.bcf/module.exports@resource://zotero-better-bibtex/Better%20BibLaTeX.js:10074:31
qualityReport@resource://zotero-better-bibtex/Better%20BibLaTeX.js:11545:22
complete@resource://zotero-better-bibtex/Better%20BibLaTeX.js:11163:16
doExport@resource://zotero-better-bibtex/Better%20BibLaTeX.js:9069:9
onmessage@resource://zotero-better-bibtex/worker/Zotero.js?client=zotero&version=5.0.81-beta.17+7c1845b3a&platform=mac&translator=Better%20BibLaTeX&output=/Users/jrennstich/Dropbox/mylibrary.bib:25672:13
#
undefined> "]

[JavaScript Error: "TypeError: this.has is undefined
check@resource://zotero-better-bibtex/Better%20BibLaTeX.js:10005:17
./bibtex/biblatex.qr.bcf/module.exports@resource://zotero-better-bibtex/Better%20BibLaTeX.js:10074:31
qualityReport@resource://zotero-better-bibtex/Better%20BibLaTeX.js:11545:22
complete@resource://zotero-better-bibtex/Better%20BibLaTeX.js:11163:16
doExport@resource://zotero-better-bibtex/Better%20BibLaTeX.js:9069:9
onmessage@resource://zotero-better-bibtex/worker/Zotero.js?client=zotero&version=5.0.81-beta.17+7c1845b3a&platform=mac&translator=Better%20BibLaTeX&output=/Users/jrennstich/Dropbox/mylibrary.bib:25672:13
"]

[JavaScript Error: "{better-bibtex! +2} Translators.exportItems failed in {"time":7158,"translatorID":"f895aa0d-f28e-47fe-b247-2ea77c6ed583","displayOptions":{"exportNotes":false,"useJournalAbbreviation":false,"preference_DOIandURL":"doi","preference_asciiBibLaTeX":true,"preference_asciiBibTeX":true,"preference_bibtexParticleNoOp":false,"preference_bibtexURL":"off","preference_biblatexExtendedNameFormat":false,"exportPath":"/Users/jrennstich/Dropbox"},"path":"/Users/jrennstich/Dropbox/mylibrary.bib"} "]

[JavaScript Error: "{better-bibtex! +1} AutoExport.queue.run: failed {"type":"library","id":1,"path":"/Users/jrennstich/Dropbox/mylibrary.bib","status":"running","translatorID":"f895aa0d-f28e-47fe-b247-2ea77c6ed583","exportNotes":false,"useJournalAbbreviation":false,"DOIandURL":"doi","asciiBibLaTeX":true,"asciiBibTeX":true,"biblatexExtendedNameFormat":false,"bibtexParticleNoOp":false,"bibtexURL":"off","error":"translation failed","meta":{"revision":25,"created":1573635382986,"version":0,"updated":1578685993991},"$loki":14} translation failed "]

version => 5.0.81-beta.17+7c1845b3a, platform => MacIntel, oscpu => Intel Mac OS X 10.15, locale => en-US, appName => Zotero, appVersion => 5.0.81-beta.17+7c1845b3a, extensions => Zotero DOI Manager (1.3.9, extension), ZotFile (5.0.14, extension), Zutilo Utility for Zotero (3.3.3, extension), ZoteroQuickLook (1.4.2, extension), Zotero Word for Mac Integration (5.0.24.SA.5.0.81-beta.17+7c1845b3a, extension), Zotero LibreOffice Integration (5.0.21.SA.5.0.81-beta.17+7c1845b3a, extension), Better BibTex for Zotero (5.2.4, extension), Shockwave Flash (32.0.0.303, plugin), Zotero automatic export (1.2.4, extension, disabled)
```

**Comment by jrennstich** [comment]
Added Report ID, sorry.

**Comment by retorquere** [comment]
Well shit. You can turn the [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) `extensions.zotero.translators.better-bibtex.workers` to `false` to revert to the old behavior while I sort this out.

**Comment by retorquere** [comment]
It's not related to the new worker exports (phew), you stumbled upon an much older bug in the quality report. If you turn off the quality report it will go away, but a fixed build is running through the test suite now.

**Comment by retorquere** [comment]
You have an entry in that export that translates to an `online` entry that triggered the error. If that's easy for you to identify I'd like to add it as a test case, if not, I'll just make my own.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.4.5578](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.4.5578.xpi) ("fixes #1387")

Install in Zotero by downloading [test build 5.2.4.5578](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.4.5578.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Never mind, I have a sample. Try 5578.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.4.5579](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.4.5579.xpi) ("test case for #1387")

Install in Zotero by downloading [test build 5.2.4.5579](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.4.5579.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
(and please do reset `workers` if you have set it to `false`

**Comment by jrennstich** [comment]
Did as instructed. It works now again. Differences in behavior:
- Spinning wheel (I have a very large database that takes considerable time)
- No updates on the "Cached" Percentages
- After completion, "Cached" would read "100%", now it states "0%" right after completion.
- Running it right after the first time (and with no changes made to the database), it completed super fast (given my normal timings), Cached info still at "0%"

Debug Output D335679250
Report-ID: 7N9AP56P-euc

Should I attempt to do full new one? This takes about half an hour or so.

**Comment by retorquere** [comment]
Alright, so the quality report has been fixed. Is it OK for you to address the performance issue in a different ticket? I'm very keen to look into this, but I prefer to have one ticket - one problem.

In the interim, you can go into the addons pane and in the gear menu select "Check for updates"; that will upgrade you to 5.2.7 which has the quality report fix, and adds caching for background exports (this is why you didn't see the cache fill, it wasn't there yet for background exports, but it turns out to be necessary after all).

**Comment by retorquere** [comment]
Wait -- how does an expert in the areas of long-term globalization, international social work, and research methods from a University of Applied Science know about counterfactuals?! I work at an UAS too, and the few people who would stand still long enough for me to explain counterfactuals would then still roll their eyes questioning the sanity of caring about them.

**Comment by jrennstich** [comment]
Let's just say, I had a great adviser and education. And if I knew a little less and publish more mainstream I wouldn't be at a UAS. Besides, counterfactuals are making a comeback as a method in some parts of IR.

**Comment by retorquere** [comment]
It's an uphill struggle at our UAS to convince people about the importance of living up to academic standards in our transition from fachhochschule to UAS. I'd love to have more phil of sci, research methodology and tech ethics.

Interesting that counterfactuals would make an appearance in IR. We dabble in IR, and most of the stuff I see people doing revolves around word2vec - I'm no expert, but that seems to me to be unburdened by meaning by and large.

**Comment by jrennstich** [comment]
> It's an uphill struggle at our UAS to convince people about the importance of living up to academic standards in our transition from fachhochschule to UAS. I'd love to have more phil of sci, research methodology and tech ethics.

Amen to that. Fighting the good fight here, using packaging strategies (i.e., "new teaching methodologies")

**Comment by retorquere** [comment]
By strange coincidence I am currently reading the debate about Lewis' possible worlds and it is baffling to me people don't find that as riveting as a Stephen King novel.
