### ISSUE TITLE
Customization of keys for a section of a book

### ISSUE THREAD

**Issue by Ypot** [retorquere/zotero-better-bibtex#1388]
Hi
Not a bug, but a possible enhancement. 
I would like to generate keys that contain the chapter and pages for book sections. 

Actually my settings are:
[auth.etal].[year].[shorttitle3_3]
Which works great for books, since they are quite explicit and not too long. 

But for books sections I would like to add the page and/ or the chapter (which I suppose it would be the title field, different from the book title).
Could it be possible to generate keys like this?: 
[auth.etal].[year].[shorttitle3_3].[chapter].[page]

Thanks for your work, it fits great with org-ref.

**Comment by retorquere** [comment]
Zotero's book section don't have a `chapter` field but I think you're supposed to use the `title` field for the chapter title. Under that interpretation, `[auth.etal].[year].[shorttitle3_3].[chapter].[firstpage]` should work (see https://retorque.re/zotero-better-bibtex/citing/).

**Comment by Ypot** [comment]
Thanks. But I would like to get (my enhancement suggestion):
(Title of the book).(Chapter title)

Because just the Chapter title doesn't help much to know the source.

Best regards.

**Comment by retorquere** [comment]
Try

```
[auth.etal].[year].[PublicationTitle:postfix=.][shorttitle3_3].[firstpage]
```

**Comment by Ypot** [comment]
Thanks! You solved my problem, and now I am learning, thanks to your example, how to use the (pseudo) functions. 

Best regards
