### ISSUE TITLE
Exporting @string vars

### ISSUE THREAD

**Issue by kyp44** [retorquere/zotero-better-bibtex#1394]
Hi, I'm new to using the Issues feature on GitHub so forgive me if I do anything wrong.

For reference, I'm using Zotero 5.0.80 and Better BibTeX 5.2.7. I'm trying to use the @string var exporting feature. In particular, I cannot set the option to "Assume single-word fields to be @string vars" because I have a number of single-word fields that should not be be treated as @string vars. As I only have a handful of possible @string vars, I'm trying to use the "Match against the @string vars below". The [Better BibTeX documentation on this](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/) does not make it clear what format these strings are supposed to be in or how multiple strings are delimited, but when I try to add a single such a string (e.g. just populating the box with IEEE_J_PWRE from IEEEabrv.bib) to the list and export my library it does not seem to treat this particular string as a @string var and puts braces around it in the exported .bib file.

I'm not sure if this is a bug or if I'm just using this feature incorrectly. I appreciate and help or advice on this and of course am happy to provide more details if necessary or to construct a MWE.

EDIT: Per the bot reply below, I did a debug log, the ID for which is D1012658544. It seems that the problem described above is more general and not reference specific, but if I need to include and reference and/or output please let me know.

**Comment by retorquere** [comment]
D1012658544 is a Zotero log; I have no access to those. Right-click one of the items you'd like to export while matching against @string vars, and select "send debug log" from the "Better BibTeX" option from the popup menu that you now see.

The @string vars should be entered just as you'd have them in a bibtex file. But if you follow the procedure from bullet point 1 from label-gun I'll get a copy of the reference you selected plus your BBT settings.

**Comment by kyp44** [comment]
Apologies for submitting the incorrect debug report. I followed the instructions above for a particular reference and the report ID is `E19FHFTP-euc`. In particular, this reference produces the following:
```
@article{bahmani_accurate_2015,
  title = {Accurate Evaluation of Leakage Inductance in High-Frequency Transformers Using an Improved Frequency-Dependent Expression},
  author = {Bahmani, M Amin and Thiringer, Torbj{\"o}rn},
  year = {2015},
  month = oct,
  volume = {30},
  pages = {5738--5745},
  journal = {IEEE\_J\_PWRE},
  number = {10}
}
```
whereas, with the @string var setup, I would expect
```
@article{bahmani_accurate_2015,
  title = {Accurate Evaluation of Leakage Inductance in High-Frequency Transformers Using an Improved Frequency-Dependent Expression},
  author = {Bahmani, M Amin and Thiringer, Torbj{\"o}rn},
  year = {2015},
  month = oct,
  volume = {30},
  pages = {5738--5745},
  journal = IEEE_J_PWRE,
  number = {10}
}
```

**Comment by retorquere** [comment]
Your strings block says only

```
IEEE_J_PWRE
```

BBT expects an actual `@string` declaration like

```
@string{IEEE_J_PWRE       = "{IEEE} Transactions on Power Electronics"}
```

**Comment by retorquere** [comment]
I will amend the docs
