### ISSUE TITLE
origyear not taken from csl extra-field for citation key generation

### ISSUE THREAD

**Issue by Ypot** [retorquere/zotero-better-bibtex#1395]
Hi. Not sure if it's a bug.

I add to the extra field, in Zotero:
{:original-date: 1994}

But in the generated key, in the place of [origyear], it appears the "Date" field, not the original year of the book.

I paste my citation key format exactly, just in case:
[Auth.etal].[**origyear**].[PublicationTitle:postfix=.][shorttitle3_3].[firstpage]

**Comment by retorquere** [comment]
I will need a debug log as described in point 1.

**Comment by Ypot** [comment]
Here:
YWEMXTM5-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5624](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5624.xpi) ("fixes #1395")

Install in Zotero by downloading [test build 5.2.7.5624](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5624.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 5624?

**Comment by Ypot** [comment]
5624 working in keys generation. Not sure either if it must be {:original-date: 1864} or original-date: 1994, both work.

Although, when exporting library it doesn't seem to work, I don't know if it is related, but I think it worked in the past.

@book{Vieira.1994.700ExperimentosConscienciologia.,
  title = {{700 Experimentos da Conscienciologia}},
  author = {Vieira, Waldo},
  year = {2002},
  edition = {1. ed.},
  publisher = {{Instituto Internacional de Projeciologia}},
  address = {{Rio de Janeiro}},
  isbn = {978-85-86019-05-0},
  language = {pt}
}

There it doesn't appear original year.
AZHC5FAU-euc

**Comment by retorquere** [comment]
> 5624 working in keys generation. Not sure if it must be {:original-date: 1864} or original-date: 1994, both work.

They're both supported. The `{:...:}` format was the first format supported by the citeproc in Zotero but is considered deprecated now.

> Although, when exporting library it doesn't seem to work, I don't know if it is related, but I think it worked in the past.

For me, AZHC5FAU-euc exports to

```
@incollection{Vieira.1994.700ExperimentosdaConscienciologia.Capitulo.p.22,
  title = {Capítulo 5},
  booktitle = {700 Experimentos da Conscienciologia},
  author = {Vieira, Waldo},
  date = {2002},
  origdate = {1994},
  edition = {1. ed.},
  pages = {p.22},
  publisher = {{Instituto Internacional de Projeciologia}},
  location = {{Rio de Janeiro}},
  isbn = {978-85-86019-05-0},
  langid = {portuguese}
}
```

It looks like you're exporting to BibTeX (BibTeX uses `year`/`month` fields, BibLaTeX uses `date`). BibTeX doesn't know about `origdate` fields.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5649](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5649.xpi) ("extra testcase for #1395")

Install in Zotero by downloading [test build 5.2.7.5649](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5649.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dbitouze** [comment]
> It looks like you're exporting to BibTeX (BibTeX uses `year`/`month` fields, BibLaTeX uses `date`). BibTeX doesn't know about `origdate` fields.

I would add that, with BibLaTeX, you should have:
```bibtex
@incollection{...,
  ...,
  edition = {1},
  pages = {22},
  ...
}
```

**Comment by retorquere** [comment]
`1. ed` and `p.22` is what you have entered in Zotero.

**Comment by Ypot** [comment]
> 
> 
> > 5624 working in keys generation. Not sure if it must be {:original-date: 1864} or original-date: 1994, both work.
> 
> They're both supported. The `{:...:}` format was the first format supported by the citeproc in Zotero but is considered deprecated now.
> 
> > Although, when exporting library it doesn't seem to work, I don't know if it is related, but I think it worked in the past.
> 
> For me, AZHC5FAU-euc exports to
> 
> ```
> @incollection{Vieira.1994.700ExperimentosdaConscienciologia.Capitulo.p.22,
>   title = {Capítulo 5},
>   booktitle = {700 Experimentos da Conscienciologia},
>   author = {Vieira, Waldo},
>   date = {2002},
>   origdate = {1994},
>   edition = {1. ed.},
>   pages = {p.22},
>   publisher = {{Instituto Internacional de Projeciologia}},
>   location = {{Rio de Janeiro}},
>   isbn = {978-85-86019-05-0},
>   langid = {portuguese}
> }
> ```
> 
> It looks like you're exporting to BibTeX (BibTeX uses `year`/`month` fields, BibLaTeX uses `date`). BibTeX doesn't know about `origdate` fields.

I am using BetterBibTex. I don't know why it is so different. Should I open a new issue or reinstall zotero or something else?

**Comment by retorquere** [comment]
It's a little confusing, I'm sorry about that, but "Better BibTeX" (also known as BBT) is the name of the plugin; this plugin installs a number of translators, two of which are "Better BibTeX" (which is, admittedly, confusing) and "Better BibLaTeX"). When you export, try choosing "Better BibLaTeX" from the available formats.

**Comment by retorquere** [comment]
If you select "Better BibLaTeX" from the export dropdown, do you get the desired output? If so, I can roll this into the upcoming release.

**Comment by Ypot** [comment]
> 
> 
> If you select "Better BibLaTeX" from the export dropdown, do you get the desired output? If so, I can roll this into the upcoming release.

Yes, so I should forget about BibTeX and adopt BibLateX if I want origdate/origyear?

**Comment by retorquere** [comment]
That's still output from `Better BibTeX`. if you see a `year` field, that's guaranteed `Better BibTeX`. `Better BibLaTeX` would have a `date` field.

I'm not sure `origyear` is supported by bibtex. It wouldn't show up in a `Better BibLaTeX` export, that would use `origdate`.

**Comment by Ypot** [comment]
> 
> 
> That's still output from `Better BibTeX`. if you see a `year` field, that's guaranteed `Better BibTeX`. `Better BibLaTeX` would have a `date` field.
> 
> I'm not sure `origyear` is supported by bibtex. It wouldn't show up in a `Better BibLaTeX` export, that would use `origdate`.

Report ID: H8APHJGX-euc

BetterBibLateX:
@book{Brennan.1976.MagiaExperimental,
  title = {Magia experimental},
  author = {Brennan, J. H},
  date = {1982},
  origdate = {1976},
  publisher = {{Edaf}},
  location = {{Madrid}},
  isbn = {84-7166-852-1},
  langid = {spanish}
}

BetterBibTeX:
@book{Brennan.1976.MagiaExperimental,
  title = {{Magia experimental}},
  author = {Brennan, J. H},
  year = {1982},
  publisher = {{Edaf}},
  address = {{Madrid}},
  isbn = {84-7166-852-1},
  language = {Spanish}
}

**Comment by retorquere** [comment]
Right, so `Better BibLaTeX` outputs `origdate`. Is that what you wanted?

**Comment by Ypot** [comment]
> 
> 
> Right, so `Better BibLaTeX` outputs `origdate`. Is that what you wanted?

Hi. I prefer BetterBibTeX ;D
But thanks for your work, I will adapt :-)

**Comment by retorquere** [comment]
OK, then I'll roll this into a new release so `origyear` will show up in the keys.

**Comment by retorquere** [comment]
You can still use BetterBibTeX if you want of course, but it won't output `origyear` by default (are there styles that support this? I can't find anything on `origyear` in [BibTeXing](http://ctan.cs.uu.nl/biblio/bibtex/base/btxdoc.pdf) or [Tame the BeaST](http://www.lsv.ens-cachan.fr/~markey/BibTeX/doc/ttb_en.pdf)). You can also add it using a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/) if you want. But if you want `orig` dates, why not use biblatex? That actually supports it formally.
