### ISSUE TITLE
Error when exporting to a network share

### ISSUE THREAD

**Issue by Avva23** [retorquere/zotero-better-bibtex#1396]
**Report ID: BMBQ6KIZ-euc**

**Expected behavior: Exporting the Better BibTeX library**

**Actual behavior: message: An error occurred while trying to export the selected file.**

I am very new at using Zotero and Latex, I was given months ago a template and today I tried to cite a reference. I exported the better BibTeX file and dragged and dropped a citation key in my latex file using \cite, but the whole citation key was cited instead, without any particular reference style. I decided to update the add-on and Zotero and try again. 

Since then, I cannot export my library as a Better BibTeX file, I am getting this error message: "An error occurred while trying to export the selected file." If I try to export it as a typical bib file, it works. Any suggestions? Many thanks.

**Comment by retorquere** [comment]
Can you go into Zotero's [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences), search for `extensions.zotero.translators.better-bibtex.workers`, set it to `0`, and try again?

**Comment by Avva23** [comment]
It is now working! Thank you so much!

**Comment by retorquere** [comment]
That's actually not so great, because that means background exports to SMB shares doesn't work. I'll see if I can get help from Mozilla to fix this. Is it possible for you to map a drive letter to that share?

**Comment by Avva23** [comment]
I am not sure I understand what I need to do, sorry.

**Comment by retorquere** [comment]
You're exporting to `\\lmenas4\caosguest`; I suspect that if you [map it to a drive letter](https://support.microsoft.com/en-us/help/4026635/windows-map-a-network-drive) it will work with `workers` set to the default value, and I'm curious whether that's correct.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5627](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5627.xpi) ("foreground smb exports")

Install in Zotero by downloading [test build 5.2.7.5627](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5627.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
5627 will likely also work but it will do so because it will detect that you're exporting to a network share and will work like workers is set to 0.

**Comment by Avva23** [comment]
So, now that I've manually set it to 0, will it likely change back to the default with a next update and cause the same problem at some point? I will try this 5627 download once I am free. Thank you for the suggestions so far.

**Comment by retorquere** [comment]
I don't change settings from what they've been set to explicitly. But I think 5627 will work with workers set to the default `1` because it explicitly detects network shares and behaves as if it's zero only then. That behavior will only change if I have a fix for it. I've requested support from Mozilla, but if an answer will come from them at all it will take some time.

**Comment by retorquere** [comment]
I'd still prefer to get confirmation so I can roll this into the upcoming release.

**Comment by retorquere** [comment]
I've gotten feedback from Mozilla and how I used to do it should work. Are you able to create files on `\\lmenas4\caosguest` yourself?

**Comment by Avva23** [comment]
Everything seems to work now, thanks.

On Sat, 1 Feb 2020 at 15:29, Emiliano Heyns <notifications@github.com<mailto:notifications@github.com>> wrote:

I've gotten feedback from Mozilla and how I used to do it should work. Are you able to create files on \\lmenas4\caosguest yourself?

**Comment by retorquere** [comment]
That's likely because when I detect that BBT is exporting to a network share, I disable background exports. That it works ("it" being BBT exports I take it) doesn't give me much information.

So, are you able to create files in that network location yourself? If not, that would explain why BBT can't. If you can, I need to investigate further.

**Comment by Avva23** [comment]
I don't understand what you mean by creating files. The whole discussion is way too technical for me to be able to assist you to help others having the same issue potentially in the future. I'm sorry.

At the moment I am able to export my BetterBibTex library to the network share with no problems. If it happens that I suddenly can't export it again, I plan on moving my work to a normal drive.

Thank you for taking time to investigate this, really appreciated it.

On Mon, 3 Feb 2020 at 11:02, Emiliano Heyns <notifications@github.com<mailto:notifications@github.com>> wrote:

That's likely because when I detect that BBT is exporting to a network share, I disable background exports. That it works ("it" being BBT exports I take it) doesn't give me much information.

So, are you able to create files in that network location yourself? If not, that would explain why BBT can't. If you can, I need to investigate further.

**Comment by retorquere** [comment]
> I don't understand what you mean by creating files.

Can you create a new Word file and save it to the same location that you're exporting that bib file to?

> At the moment I am able to export my BetterBibTex library to the network share with no problems.

I know, because I am disabling the new way of exporting BBT files when I detect they're about to be written to a network share. I'd very much prefer not to have to do that.

> If it happens that I suddenly can't export it again, I plan on moving my work to a normal drive. 

That's unlikely to start happening in your situation because you're falling back to the old way of saving BBT files. I'd very much prefer it if that wouldn't be necessary. Unfortunately I can't even try to replicate this problem because I don't have access to a Windows system.

**Comment by Avva23** [comment]
Thanks for the clarification. I am able to create a new word file in the same location, yes.

On Mon, 3 Feb 2020 at 19:07, Emiliano Heyns <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't understand what you mean by creating files.

Can you create a new Word file and save it to the same location that you're exporting that bib file to?

At the moment I am able to export my BetterBibTex library to the network share with no problems.

I know, because I am disabling the new way of exporting BBT files when I detect they're about to be written to a network share. I'd very much prefer not to have to do that.

If it happens that I suddenly can't export it again, I plan on moving my work to a normal drive.

That's unlikely to start happening in your situation because you're falling back to the old way of saving BBT files. I'd very much prefer it if that wouldn't be necessary. Unfortunately I can't even try to replicate this problem because I don't have access to a Windows system.

**Comment by retorquere** [comment]
And if you set the "background exports" slider to 1 again, the BBT export still fails?

**Comment by retorquere** [comment]
Oh wait -- you can't do that. Hold on.
