### ISSUE TITLE
Regression in Better CSL YAML export

### ISSUE THREAD

**Issue by jpcirrus** [retorquere/zotero-better-bibtex#1400]
**Report ID:**
SZKE4HGJ-apse

**Exporter used:**
Better CSL YAML

**Expected behavior:**
The YAML (JSON) keys in the exported bibliography items are sorted case insensitively except for the `id` key which is the first key per bibliography item, as was implemented in resolving issue #1178, and as evidenced by `collection-export-fixed-by-1178.yaml` in the attached zip file.

**Actual behavior:**
The YAML (JSON) keys in the exported bibliography items are sorted case sensitively and with the `id` key being sorted alphabetically togther with the other bibliography item keys, as evidenced by `collection-export-now-regressed.yaml` in the attached zip file.

[Better CSL YAML Export.zip](https://github.com/retorquere/zotero-better-bibtex/files/4068221/Better.CSL.YAML.Export.zip)

I am not sure when this regression happened but from reviewing previous exports know it was between 2019-05-08 and 2019-07-19 (New Zealand time).

In BBT 5.2.7 I notice that with the changes to the BBT advanced preferences, that the option `Deterministically order references and fields; primarily for version control` is no longer visible but from recent test exports it would appear to be enabled by default (or my previous enabling thereof is still in effect). Would this change have an effect on the reproducibility of current exports?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5672](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5672.xpi) ("fixes #1400")

Install in Zotero by downloading [test build 5.2.7.5672](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5672.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jpcirrus** [comment]
I have just tested this test build, but the reported issue exists as before. I have confirmed that BBT is at 5.2.7.5672, reset the chache and done two restarts of Zotero, so not sure what the problem could be.

**Comment by retorquere** [comment]
The preference was removed but BBT now always sorts. There was an error in the key sorting, which I thought I fixed in 5627.

For me, `MorganCasterSemenyawins2016` exports to 

```
[
  {"id":"MorganCasterSemenyawins2016","accessed":{"date-parts":[[2019,4,26]]},"author":[{"family":"Morgan","given":"Tom"}],"container-title":"The Telegraph","ISSN":"0307-1235","issued":{"date-parts":[[2016,8,21]]},"language":"en","source":"www.telegraph.co.uk","title":"Caster Semenya wins 800 m: Beaten GB finalist Lynsey Sharp criticises rule changes over 'obvious' hyperandrogenous women","title-short":"Caster Semenya wins 800 m","type":"article-newspaper","URL":"https://www.telegraph.co.uk/news/2016/08/21/lynsey-sharp-criticises-obvious-hypoadrogenous-women-having-bein/"}
]
```

which is, as far as I can tell, sorted correctly; `id` first, the rest alphabetically. What do you get for that item?

**Comment by retorquere** [comment]
wait -- is this with YAML? I now see that YAML used strict-alphabetic sorting and has so for a long time.

**Comment by retorquere** [comment]
I'm going through the history and YAML might actually have had the desired sort in the past if you turned *off* sorting 🙄 .

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5674](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5674.xpi) ("fixes #1400")

Install in Zotero by downloading [test build 5.2.7.5674](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5674.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jpcirrus** [comment]
The YAML (and CSL) sort was perfect immediately after the changes for #1178 as seen in `collection-export-fixed-by-1178.yaml`, in the previously attached zip file. I never checked again after that until yesterday when a repository diff evidenced that those changes had been reverted.

I can confirm that test build 5.2.7.5674 is perfect for JSON export. YAML export is correct except that what in JSON keys are `date-parts`, and in year, month, day order, are sorted day, month, year in YAML, when they should mirror the JSON order (which was also the order implemented in #1178).

I find this sorted order makes it so fast to visually lookup bib items, I wonder if it would also be worth doing for the BibTeX and BibLaTeX exports?

Thanks again for your appreciated efforts.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5677](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5677.xpi) ("OK, then does this finally fix #1400?")

Install in Zotero by downloading [test build 5.2.7.5677](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5677.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
You're right. TBH right now I don't know why it ever worked, but it should work now.

**Comment by retorquere** [comment]
If this does, in fact, do what you expect, I can roll it into a new release; I'm cutting a new release today for a fairly important fix.

**Comment by jpcirrus** [comment]
Yes, both the CSL and YAML exports are perfect. Thank you. Do you think it would be worth implementing these sort changes to the BibTeX and BibLaTeX exports as well? I know if I was using them I would appreciate that.

**Comment by retorquere** [comment]
Man that's a relief.

The biblatex and bibtex formats are sorted in what I thinks is reasonably sensible. Title, date creators, rest alphabetical IIRC. I'll cut a release when I'm back at my computer.
