### ISSUE TITLE
Minimize bibtex export package dependencies

### ISSUE THREAD

**Issue by jaromrax** [retorquere/zotero-better-bibtex#1402]
I cannot find a solution for titles that are in latex. I have *tons* of latex titles to export, I still get  e.g.  
```
{Vertex} {Constant}
 for $undefined\{7\}undefinedmathrm\{{Be}\}\{(p,undefinedensuremath\{undefinedgamma\})\}undefined\{8\}undefinedmathr
m\{{B}\}$ {Reactions}},
```
for the original title like
`Vertex Constant for $^{7}\mathrm{Be}{(p,\ensuremath{\gamma})}^{8}\mathrm{B}$ Reactions`

Is there a simple solution? Thank you
jaromir

**Comment by retorquere** [comment]
I really need that debug log, generated as explained by label-gun in point 1.

**Comment by jaromrax** [comment]
Thank you very much for the care. Is the reference ok?
FR3Q3ZGL-euc

I was checking the output. During compilatoin I am also getting errors like
```
l.56 ...eaction rate for {{Mg22}}+p\textrightarrow
                                                  {{Al23}} from the
```
and package

**Comment by retorquere** [comment]
There's a few things going on, but first: did you get `...for $undefined\{7\}undefinedmathrm\{{Be}\}...` using Better BibTeX, or Better BibLaTeX? I can't reproduce the `undefined` parts. When I export that using Better BibTeX, I get

```
{Overall {{Normalization}} of the {{Astrophysical}} \${{S}}\$ {{Factor}} and the {{Nuclear Vertex Constant}} for \$\^\{7\}\textbackslash{}mathrm\{\vphantom\}{{Be}}\vphantom\{\}\{(p,\textbackslash{}ensuremath\{\textbackslash{}gamma\})\}\^\{8\}\textbackslash{}mathrm\{\vphantom\}{{B}}\vphantom\{\}\$ {{Reactions}}},
```

no `undefined` in sight.

**Comment by jaromrax** [comment]
Thank you for the care again, your task is complicated by the fact, that I was playing with .js and conversions for hours and I have mixed up few versions... sorry for that
now - with Better Bibtex - I get the same:
```
 title = {Overall {{Normalization}} of the {{Astrophysical}} \${{S}}\$ {{Factor}} and the {{Nuclear Vertex Constant}} for \$\^\{7\}\textbackslash{}mathrm\{\vphantom\}{{Be}}\vphantom\{\}\{(p,\textbackslash{}ensuremath\{\textbackslash{}gamma\})\}\^\{8\}\textbackslash{}mathrm\{\vphantom\}{{B}}\vphantom\{\}\$ {{Reactions}}},
```
for
```
Overall Normalization of the Astrophysical $S$ Factor and the Nuclear Vertex Constant for $^{7}\mathrm{Be}{(p,\ensuremath{\gamma})}^{8}\mathrm{B}$ Reactions
```

**Comment by jaromrax** [comment]
I am still searching and I have found something! - the tag #LaTeX makes a good change, but how can I tag 100 references?: 

https://forums.zotero.org/discussion/5324/bibtex-and-greek-characters/p2

**Comment by retorquere** [comment]
Yeah that was the next thing I was going to suggest -- either:

* tagging individual entries with `#LaTeX`, or
* setting `rawLaTag` to `*` if all your items are raw LaTeX, or
* using `<script>...</script>` markers around parts of title that are LaTeX.

But I worried about those `undefined`s so I wanted to diagnose that first.

**Comment by retorquere** [comment]
> (sorry, I tried to remove $ and other characters from old bibtex.js manually)

That's in principle OK, but in practice not a good idea:

* BBT's translators are compiled from Typescript so the "sources" you see are not the actual sources
* BBT overwrites existing translators if I made changes to them, so your edits will be lost at some point.

**Comment by jaromrax** [comment]
Yes, I get the point with .js, I dont edit them anymore. My final message now:

Thank you for your help, it was vital, even you can think, you only directed me to proper use of BBT. Thank you again. I have realized:
1/ tag #LaTeX makes the BBT exporter leave latex there. This solved a lot.
2/ a lot of references have a mixed latex and utf8 characters - I repair manually
3/ `\textrightarrow` - I cannot use, the main package somehow blocks the `textcomp` package, I repair manually to $\rightarrow$
4/ I still need to change the language in .bib with `cat  ~/Downloads/Exported\ Items.bib |  sed  's/{en}/{english}/g' > my.bib`, which may be a problem of the main package.
5/ There can be also a mix :  latex in title + utf8 in authors - I dont get a proper conversion of the utf8 letter Š to {\v S}, other letters were ok - I handled manually

Great to have your package. Best regards, Jaromir

**Comment by retorquere** [comment]
In the next release, exports will default to character translation that minimizes the need for external packages, so that the manual fixup won't be necessary, as it will default to `$\rightarrow$`.

**Comment by retorquere** [comment]
Wait, `reaction rate for Mg22` doesn't occur in de debug log you sent.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5681](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5681.xpi) ("text case for #1402")

Install in Zotero by downloading [test build 5.2.7.5681](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5681.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
