### ISSUE TITLE
Extra field `References` dropped on export to Better Bib(La)Tex

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#1405]
**Item Data:**
`[
  {"id":"JolySilencetablemanners2008","accessed":{"date-parts":[[2019,10,27]]},"author":[{"family":"Joly","given":"Janneke F."},{"family":"Stapel","given":"Diederik A."},{"family":"Lindenberg","given":"Siegwart M."}],"container-title":"Personality and Social Psychology Bulletin","container-title-short":"Pers. Soc. Psychol. Bull.","DOI":"10.1177/0146167208318401","ISSN":"0146-1672, 1552-7433","issue":"8","issued":{"date-parts":[[2008,8]]},"language":"en","page":"1047-1056","references":"Retraction published 2012, <i>Personality and Social Psychology Bulletin, 38</i>[10], 1378, https://doi.org/10.1177/0146167212462821","source":"Crossref","title":"Silence and table manners: when environments activate norms","title-short":"Silence and table manners","type":"article-journal","URL":"http://journals.sagepub.com/doi/10.1177/0146167208318401","volume":"34"}
]`

**Report ID:**
FSZ9235V-euc

**Exporter used:**
Better BibTeX, Better BibLaTeX

**Expected behavior:**
`References` in Extra is mapped to some field.

**Actual behavior:**
`References` in Extra is silently dropped.

I have some data stored in `References` in Extra. When I export to Better CSL JSON, these data are mapped to the `references` field in the JSON. But when I export to Bib(La)TeX, these data are silently dropped. Is there a Bib(La)TeX field that these should instead be mapped to?

**Comment by retorquere** [comment]
This is parsed out because it's a [CSL variable](https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables); the new format for CSL variables in Zotero's extra field is just `<Name>: <Value>` rather than the older `{:<Name>: <Value>}`.

If I look in the CSL variables list, I see it means

> resources related to the procedural history of a legal case

What would that map to in either bibtex or biblatex?

(the debug log includes a copy of the reference BTW if you send it from the right-click menu)

**Comment by bwiernik** [comment]
> What would that map to in either bibtex or biblatex?

I don't really know. I only interact with bibtex as a backend for pandoc, so you would have more idea what to do with such a variable. Seems like it would undesirable to discard data like this though.

**Comment by retorquere** [comment]
I mean in principle, yeah, but bibtex is not an archival format. There must be a sensible field to put data in, and I wouldn't know what that is for this field.

**Comment by retorquere** [comment]
I know relatively little about bibtex and biblatex btw. I initially took the field mapping from the stock zotero translators, after that I consulted experts like plk and njbart. But I need a proposal for an actual field mapping. I honestly have not the slightest clue here.

**Comment by bwiernik** [comment]
I asked with John McFarlane about this issue more generally. The place where I am concerned about this is primarily users working with citeproc-pandoc, who often (annoyingly) use .bib as their data format instead of CSL JSON/YAML.

**Comment by retorquere** [comment]
There's a (single, as far as I'm concerned) good reason to use bib with pandoc which is if you're producing pdf, which uses latex under the hood.

Pandoc, for all the wonderful things it does splendidly, has a few gnarly errors in their bibtex handling, and I can't always cater to its idiosyncrasies.

That said, where would pandoc expect this datum to show up?

**Comment by bwiernik** [comment]
When building PDFs, by default, pandoc still uses CSL to do formatting.

**Comment by retorquere** [comment]
Well then there goes the sole reason to use bib with pandoc.

I'll just await his response then, but I'll check with njbart and plk before I make the change.

**Comment by bwiernik** [comment]
I’m not really concerned about archival, just the loss of data used in citation formatting.

**Comment by bwiernik** [comment]
I’m not really concerned about archival, just the loss of data used in citation formatting.

**Comment by retorquere** [comment]
Agreed, but then we'd need to know whether either there's a standard field that holds this kind of info, or that there are specific styles that use it (and then in what field they expect it). I can't find anything relevant in the biblatex manual, which makes it pretty unlikely it's in something that passes as a bibtex manual. That would leave specific styles.

**Comment by njbart** [comment]
I’m pretty sure there isn’t any suitable counterpart on the BibLaTeX (“BL”) side at all. If such variables must be shoehorned into BL databases, I’d suggest prefixing them with `csl_` for maximum clarity. BL -> CSL converters would then have to updated to convert any fields with a `csl_` prefix (or just a specific list of such fields) to the corresponding CSL variable. See also https://github.com/jgm/pandoc-citeproc/issues/435#issuecomment-576324261.

**Comment by retorquere** [comment]
I'm not inclined to add something like this. If wanted this can be added in a postscript, but I don't see bib(la)tex as archival or general data exchange formats.

**Comment by njbart** [comment]
> I'm not inclined to add something like this.

Me neither. I just happen to feel that *if* there is demand for something like this, labelling the shoehorned variables as clearly as possible is the least bad option.

**Comment by retorquere** [comment]
Better CSL JSON/YAML will export the `references` field BTW. If there are CSL styles that use this, it'd be much better to just use the CSL format for the entire pipeline.

**Comment by njbart** [comment]
Of course. All *I’m* trying to point out is that *if* anything is implemented (not my call), a clear distinction should be upheld between genuine BL fields and what is basically CSL stuff shoehorned into the BL format.

**Comment by retorquere** [comment]
Yeah no clear. We're in agreement. It's more that if @bwiernik wants to use the data, he'd likely be better off using csl

**Comment by retorquere** [comment]
@bwiernik, is this something you can live with?

**Comment by bwiernik** [comment]
Yeah, sure. It’s not my personal workflow that’s the concern.
