### ISSUE TITLE
link between Zotero & TeXstudio

### ISSUE THREAD

**Issue by PaulCAMBOURIAN** [retorquere/zotero-better-bibtex#1406]
I want to make an automatic "\autocite{}" : Zotero Picker + Better BibTeX can be used to CAYW (Cite As You Write) with TeXstudio (https://www.youtube.com/watch?v=Whn9Mk-JwL0)

**Report ID:**

**Exporter used:**
I'm on Windows 10
I edited macro with a new one : Zotero Picker

LateX code:
%SCRIPT
var url = "http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true"
system("curl -s " + url)

**Expected behavior:**
When choosen the artcile, the commande \autocite{article_key} is printed
**Actual behavior:**

When execution : I finally have "TEXstudio not found" and no \autocite{article_key}

**Comment by retorquere** [comment]
You can ignore label-gun in this case

**Comment by retorquere** [comment]
Oh wait, I misread. Is texstudio in your `$PATH`? if it is, I'll need a BBT debug log

**Comment by PaulCAMBOURIAN** [comment]
I have no possibility to "push to teXstudio" in Zotero

**Comment by retorquere** [comment]
I understand. But is texstudio in your `$PATH`?

**Comment by PaulCAMBOURIAN** [comment]
The problem was : texStudio isn't in my Path !!
it's great !

Thanks a lot

**Comment by retorquere** [comment]
you're welcome

**Comment by dbitouze** [comment]
> The problem was : texStudio isn't in my Path !!

@PaulCAMBOURIAN Please, could you explain the process to make TeXstudio being in your path?

**Comment by retorquere** [comment]
@PaulCAMBOURIAN if you can tell me the default installation path for texstudio (probably `c:\program files\something\texstudio.exe`, I can add that as a default so that it doesn't need to be in the path if it's there.

**Comment by PaulCAMBOURIAN** [comment]
To make TeXstudio being in my path: 

in 'Modify the Environment variables account '
click on 'Path'
browse to: C:\Program Files (x86)\texstudio

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.10.5716](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.10.5716.xpi) ("find texstudio in the default installation dir for windows")

Install in Zotero by downloading [test build 5.2.10.5716](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.10.5716.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
5716 should find TeXstudio even if it's not in your path.

**Comment by retorquere** [comment]
Any one of you willing to test? Otherwise I'm going to merge it blindly. I don't have access to a Windows machine to test.

**Comment by dbitouze** [comment]
> Any one of you willing to test? Otherwise I'm going to merge it blindly. I don't have access to a Windows machine to test.

I cannot test either (Linux only here). @PaulCAMBOURIAN ?

**Comment by PaulCAMBOURIAN** [comment]
I think it's ok !
I removed teXstudio of my path and add your test build.
I can make the push to teXstudio.

Thank's !

**Comment by retorquere** [comment]
Thank you

**Comment by dbitouze** [comment]
>5716 should find TeXstudio even if it's not in your path.

On Windows 10 (tested in a VM), that's not the case anymore (Zotero 5.0.95.1, BBT 5.2.117, report #YFFHTNUW-euc):

> TeXstudio not found

(TeXstudio indeed not in the Path).

**Comment by retorquere** [comment]
Where is the textstudio execeutable for you? Is it no longer in `C:\Program Files (x86)\texstudio`?

**Comment by retorquere** [comment]
(I really prefer new issues being opened rather than old issues being reopened -- github does not support re-ordering of issues, so older issues that demand attention are really hard to find in their UI)

**Comment by dbitouze** [comment]
> Where is the textstudio execeutable for you?

In`C:\Program Files\texstudio`

> Is it no longer in `C:\Program Files (x86)\texstudio`?

It seems to not be the case anymore.

>(I really prefer new issues being opened rather than old issues being reopened -- github does not support re-ordering of issues, so older issues that demand attention are really hard to find in their UI)

Sorry. Do you want me to open a new issue?

**Comment by retorquere** [comment]
No need to be sorry, but it would really help me stay organised, yes.

**Comment by dbitouze** [comment]
> No need to be sorry, but it would really help me stay organised, yes.

Done (#1743).

**Comment by qqobb** [comment]
> github does not support re-ordering of issues

@retorquere: There's ["Sort" -> "Recently updated"](https://github.com/retorquere/zotero-better-bibtex/issues?q=is%3Aissue+sort%3Aupdated-desc). That's pretty useless at the moment, though, since the bot updated most of your BBT issues in the last few hours.

Sorry if this comment is distracting. My excuse is that I just received several BBT notifications :-)

(The issue can be closed.)

**Comment by retorquere** [comment]
I didn't know about that, and sorry about the notification storm. It took me too long to realize that if I just didn't have it post that message, all would have been fine.
