### ISSUE TITLE
omitting different fields per automatic export

### ISSUE THREAD

**Issue by wkjarosz** [retorquere/zotero-better-bibtex#1408]
Report ID: ID6YC6LE-euc

Exporter used: Better BibTeX or Better BibLaTeX

Expected behavior: I'd like to be able to specify different values of "fields to omit from export" for each automatic export. Is this possible? If not, would it be possible to add this as a per-export option (much like URL/DOI option that is available both globally and on a per-export basis)?

Reason: I automatically export my large Zotero library to a master bib file which I import into each publication I write. I'd like to have multiple versions of the exported bib file: one with all information, but also one that are compressed (when page space is limited) to omit e.g. page numbers, or publisher addresses, etc.

While I can use different @string defines with the same master bib file to compress e.g. journal names, removing fields requires me to either change settings and re-export, or modify the exported bib file.

Actual behavior: fields can only be omitted globally for all exports

Thanks for the great addon!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.10.5722](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.10.5722.xpi) ("expose export dir / path")

Install in Zotero by downloading [test build 5.2.10.5722](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.10.5722.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
The UI for this would be tricky, as would the interaction with the cache. I might try to fashion a more elegant solution at a later time when I have more time (then again -- I may not, I'm not decided at this stage). I can explain why this is different from the URL/DOI option if you're curious, but if not, I won't bore you with the details.

In the interim, 5722 has a change that I'd be happy to merge and release. In this version, `Translator.exportDir` is the directory the export is being written in, and `Translator.exportPath` the full path of the output. These can be tested for in a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/), where you can remove any field you want. If you use either of these in the postscript, caching will be disabled, as the output can now vary unpredictably and I can't re-use the output for the cache (the same would go if I would at some point implement the proposed change). In the 5.2 series of BBT, the cache being disabled is less of a problem than it used to be; the UI will not be disrupted, but exports will take longer.

Such a postscript might look like

```
if (Translator.BetterBibTeX && Translator.exportPath.endsWith('/stripped.bib')) {
  delete reference.has.pages
  delete reference.has.abstract
}
```

**Comment by wkjarosz** [comment]
If you can merge and release it, the workaround you mentioned using 5722 should get me by for the time being. Thanks.

**Comment by retorquere** [comment]
Can you test whether it accomplishes what you want to do? It passes all my tests but before I cut a new version I'd prefer to know that I've addressed the issue.

**Comment by wkjarosz** [comment]
I can confirm 5722 works as you described on my end. However, the fact that caching is disabled likely means I wouldn't use this approach. I may look into using bibtool, or just a simple search/replace shell script after export.

**Comment by retorquere** [comment]
5.2.12 is building
