### ISSUE TITLE
ChromeWorker fails to load

### ISSUE THREAD

**Issue by mikulcak** [retorquere/zotero-better-bibtex#1409]
Hi,

recently the translation of an auto-updating BibLaTeX export began to fail with the error message `Translation failed` more and more often. 

I've uploaded a debug report under the id `SBGWDYNF-euc`

Thank you so much in advance for looking into it!

**Comment by retorquere** [comment]
I'm ill right now so it'll take some time before I can actually diagnose the problem, but in the interim, go into bbt settings, advanced, export, and set background exporters to 0

**Comment by retorquere** [comment]
with workers set to 1, do you have the same problem on 5.0.80 and 5.0.81? I can't replicate the problem on any one of those.

**Comment by mikulcak** [comment]
Alright, thanks for the suggestions!. I downgraded to Zotero 5.0.81 and set the number of background exports to 1, now we'll have to wait and see if the problem occurs again. 

Thanks again and get well soon!

**Comment by retorquere** [comment]
Did you do an export with 5.0.81? And that succeeded?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.11.5739](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.11.5739.xpi) ("maybe a CSP violation? But then why doesn't it happen everywhere?")

Install in Zotero by downloading [test build 5.2.11.5739](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.11.5739.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 5739 with workers=1 on 5.0.82?

**Comment by retorquere** [comment]
This is a strange error though. I also have a mac and I'm not seeing it; none of my tests (which do at least 240 exports in a row) show it. So far it seems to be unique to your system.

**Comment by mikulcak** [comment]
Hm, that is strange indeed. I have to clarify: The problem only occurs intermittently and it's a bit elusive. I have of course exported my library with your recommended settings and version yesterday and that worked, but I'll have to wait and see if it happens again. I'll try with your test version and Zotero 5.0.82 as soon as possible tonight and will let you know. 

Maybe it's a question of system load and a timeout somewhere? The MacBook I'm running this on isn't too young anymore.

**Comment by retorquere** [comment]
It shouldn't be, really. I'm loading a file that's guaranteed to exist; if that takes longer, the only thing you should notice is that the export takes longer.

Intermittent problems are the worst. 

In your case, the error message I see is super generic: 

> Failed to load worker script at resource://zotero-better-bibtex/worker/Zotero.js?client=zotero&version=5.0.82&platform=mac&translator=Better%20BibLaTeX&output=`<path>`/bibliography.bib (nsresult = 0x80004005)"

It doesn't help that Zotero builds on a technology that Mozilla itself deems deprecated, so documentation and support from the Mozilla crowd (which are the only ones that can help here) is has been flagging. If I google your error I get only a few hits, most of which are some 10 years old.

It also doesn't help that BBT some stuff (like these workers) that no-one else does in the Zotero ecosystem, so I'm on my own in figuring these out. I've currently moved the worker to the `chrome://` namespace. I saw some discussion that the namespace could be the problem. But that leaves unexplained why it works everywhere else. I can't even put out a debug build like 5739 unless all my tests pass.

**Comment by retorquere** [comment]
I've started a test run while maxing out all available io and cpu, and the tests run without issue.

**Comment by retorquere** [comment]
Can you upgrade to the latest version and try turning background exports back on to see if matters have improved for you?

**Comment by mikulcak** [comment]
Thanks so much for taking care of this! I'm starting to get a sense of the problems you're facing with bugs like this, which makes me all the more grateful for you making such quick work of it. 

I'll try during the day (I've been away the past few days so I couldn't try thoroughly) and will let you know!

**Comment by retorquere** [comment]
That's all OK. I've seen the problem now once too but it's unfortunately not reproducable at will. Right now, it tries to get a worker 5 times each time with more time between, and will turn off background exports if that still fails. The kind of failure we're experiencing is not supposed to be possible, but unfortunately the body of expertise that knows why this could fail nonetheless is dwindling fast.

**Comment by retorquere** [comment]
I've built in a retry system, which shouldn't be necessary, but I've not had the problem since. If you do, commenting here will re-open the issue automatically.
