### ISSUE TITLE
Lower-case names with numbers are not protected but capitalized

### ISSUE THREAD

**Issue by stefanct** [retorquere/zotero-better-bibtex#1410]
I have read the FAQ and a number of issues on the topic. I pity all of you for having to deal with it and thank you to not giving up. :)
However, I have another issue that is neither dealt with yet nor is there an existing issue for it AFAICT.
I am not entirely convinced that it should be solved in BBT instead of Zotero directly (please advise if I should post it to Zotero's forum instead).

Suppose you have a paper title like "V0LTpwn: Attacking x86 Processor Integrity from Software" which should be added to zotero in sentence-case as "V0LTpwn: attacking x86 processor integrity from software". With the recommended BBT settings the export protects "V0LTpwn" (but only because it contains multiple upper-case letters AFAICT) but not "x86". The latter gets capitalized to "X86".

While this is not too much of a problem in this case I would like to request that words containing numerals to be protected too since there is no other way(?) to protect lower-case words from capitalization (without turning it off completely) and not touching them is most probably an improvement (apart from possible regressions for some users that rely on this capitalization of course).

Also, is there a viable workaround to get "x86" in the eventual output?

**Comment by stefanct** [comment]
*sigh* <expletives>^C
There you go: D7XH5JM2-euc

**Comment by retorquere** [comment]
I can take a look at protecting things like `x86`, but there is a way to get that now -- just the standard  `V0LTpwn: attacking <span class="nocase">x86</span> processor integrity from software`.

**Comment by stefanct** [comment]
The/my problem with that is that it is visible everywhere including in the names of linked files if they are autorenamed. That is simply ugly... not a big issue apart from that though. Thanks for the suggestion (I forgot reading about that html markup, sorry).

**Comment by retorquere** [comment]
I'm going to see what the fallout would be of bracing that, but whatever is doing the renaming (zotero or zotfile) has a bug. This kind of html-ish markup is supported in Zotero so it means markup, not string-content, so the renamer should skip over those.

**Comment by stefanct** [comment]
Hm, but it is also visible within the Zotero GUI, e.g., in the title column of the item pane...? That would mean that you are either mistaken or there is a regression/bug in Zotero itself.

**Comment by retorquere** [comment]
Neither. Add something like `<b>word</b>` to the title, and generate a bibliography. That markup remains visible in the UI, but the generated bibliography makes that word bold. Zotero supports a limited set of html-ish markup, and BBT mirrors that support in its exports.

**Comment by stefanct** [comment]
OK, I see what you mean. Fair enough, then zotfile does not handle the markup, it still clobbers the Zotero UI (which I deem worse... I rarely see the file names after they get renamed but I noticed it). I'll open an issue with zotfile though... there does not seem to be one yet for hat. Thanks!

**Comment by retorquere** [comment]
I've generated a bibliography inside Zotero with a case-changing style (Turabian in this case) and without `<span class="nocase">...</span>`, Zotero generates

> Shelah, Saharon. 1972. ‘V0LTpwn: Attacking X86 Processor Integrity from Software’. Pacific Journal of Mathematics 41: 247–261.

So by not adding case-protection automatically for `x86`, BBT already follows the Zotero intent.

**Comment by stefanct** [comment]
Yes, and Zotero's intent is arguably wrong in the case of words containing numbers (if you ask me). They should not be touched like `V0LTpwn`. Are you trying to tell me that you consider this as a problem out of scope of BBT? - I guess so looking at the metadata changes that just came in... :)

**Comment by retorquere** [comment]
I do -- BBT has as a design goal to follow the intent of Zotero (or citeproc to be more precise) so that data that sits in Zotero can be used both in Word/LibreOffice and expect to render the same bibliography. If you can convince citeproc to change the behavior, I will follow suit.
