### ISSUE TITLE
Export Zotero field `Nb of pages` in BibLatex field `PagesTotal` 

### ISSUE THREAD

**Issue by Tixma** [retorquere/zotero-better-bibtex#1411]
I'm using Zotero (V.5.0.81) and BetterBibtex (V.5.2.7) in order to export my bibliography to a .bib file. 

I want to have the `pagetotal` field for `@books` in my .bib  exported from the Zotero field `Nb of pages`. 

My Zotero field `Nb of pages` was automaticaly converted in a .bib `Pagestotal` with BetterBibtex (V.5.1.58), it is not the case anymore.

Details on the issue is posted here : https://tex.stackexchange.com/questions/525608/betterbibtex-biber-zotero-no-export-of-book-pages

Report ID : KJW5FPYD-euc

Thank you.

**Comment by retorquere** [comment]
I'll need a debug log generated with the instructions at point 1. `KJW5FPYD-euc` is generated with the instructions from point 2.

**Comment by retorquere** [comment]
Oh wait -- you're exporting with Better BibTeX. BibTeX does not support the pagetotal field. If you export using Better BibLaTeX, the `pagetotal` field will show up.

**Comment by Tixma** [comment]
You are absolutely right. I'm sorry for losing your time, it works well now ! Thank you for your help.

**Comment by retorquere** [comment]
No problem whatsoever, I prefer one question too many over one question too few.
