### ISSUE TITLE
abbr function in Better BibTeX citation key generator

### ISSUE THREAD

**Issue by S73f4n** [retorquere/zotero-better-bibtex#1412]
Hello,

is there away to make the abbr function in the Better BibTeX citation key generator treat an actual abbreviation as independent letters, such that, e.g., "IEEE Transactions on Something" becomes "ieeets" instead of "its" when I use [journal:abbr:lower]? I'd be grateful if anybody knew a solution. 

HDXLB8E8-euc

**Comment by S73f4n** [comment]
HDXLB8E8-euc

**Comment by retorquere** [comment]
I'm afraid this will be hard to do in a stable way. If I'm going to include existing abbreviations in the result, I don't want to half-ass it, but then we have problematic terms like `IoT` (is an abbreviation even if it's not all-caps) `McDonnel` (not an abbreviation), `iPod` (not an abbreviation); `eg`, `ie`,  `vs`, `cm` and `mm` (abbreviations even though they have no capitals at all). `radar` (which technically is an abbreviation even though it is used as a word in most cases). I can't currently think of a rule that would pick the abbreviations (or rather, initialisms) out cleanly.

**Comment by retorquere** [comment]
I don't think this is viable to automate. Unless you can propose a rule, I'll have to close this issue.
