### ISSUE TITLE
Single-part patent holder names are always {brace-protected}

### ISSUE THREAD

**Issue by nils-werner** [retorquere/zotero-better-bibtex#1414]
**Report ID:** ZF9DFM5I-euc

**Exporter used:** Better BibLaTex

**Expected behavior:**

If brace-protection is disabled, a patent should be exported as

    @patent{key,
      title = {Name Of The Patent},
      holder = {Name Of The Patent Holder},
      [...]
    }

**Actual behavior:**

Iinstead it is exported as

    @patent{key,
      title = {Name Of The Patent},
      holder = {{Name Of The Patent Holder}},
      [...]
    }

**Comment by retorquere** [comment]
That was ambiguous in the BBT docs, sorry; I've [clarified](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-case-protection-to-capitalized-words-by-enclosing-them-in-braces) this now.

The brace-protection is actually case-protection (by way of braces), and only applies to title fields, not creator fields. The braces in the creator fields serve a different purpose: names in bib(la)tex can be entered in a [number of ways](https://nwalsh.com/tex/texhelp/bibtx-23.html):

1. John Paul Jones
2. Jones, John Paul
3. {John Paul Jones}

Between these, 1. and 2. mean the same, the third does not; 3 is a single-part name consisting of `John Paul Jones`, where the other two are two-part names consisting of a given name and a surname.

Normally I'd say "and you have a single-part creator name", but the logs you submitted only have two-part names. Can you paste in the *actual* faulty output you get? `Name Of The Patent` is not in the logs you sent.

**Comment by retorquere** [comment]
Can you get me a screenshot of the item with title "Time domain aliasing reduction for non-uniform filterbanks which use spectral analysis followed by partial synthesis"?

**Comment by retorquere** [comment]
Never mind that screenshot. For me, the item in ZF9DFM5I-euc exports to

```
@patent{WernerTimedomainaliasing2018,
  title = {Time Domain Aliasing Reduction for Non-Uniform Filterbanks Which Use Spectral Analysis Followed by Partial Synthesis},
  author = {Werner, Nils and Edler, Bernd},
  date = {2018-02-01},
  holder = {{Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V., Friedrich-Alexander-Universitaet Erlangen-Nuernberg}},
  keywords = {audio signal,block,mypublication,samples,set,subband},
  langid = {english},
  number = {3276620A1},
  type = {patenteu}
}
```

which does not exhibit the behavior you describe.

**Comment by retorquere** [comment]
I really can't do anything without further feedback.

**Comment by nils-werner** [comment]
I see double braces in the BibTeX code you posted:

    holder = {{Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V., Friedrich-Alexander-Universitaet Erlangen-Nuernberg}},

They are superfluous, no?

**Comment by retorquere** [comment]
Ah that. No, that's not superfluous; according to the [biblatex manual](http://ctan.cs.uu.nl/macros/latex/contrib/biblatex/doc/biblatex.pdf), page 20, `holder` is a name-list. Since Zotero doesn't have actual creator fields for the assignee but just an plain text field, I must treat it as a single-part name, and single-part names must be braced as per the explanation above.

**Comment by nils-werner** [comment]
Ah, I missed that. Thanks!
