### ISSUE TITLE
Confirmation dialog for removing auto-exports

### ISSUE THREAD

**Issue by stefanct** [retorquere/zotero-better-bibtex#1421]
I noticed that is is very easy to remove existing auto-exports (in the settings of better bibtex). Since it is impossible to undo this easily (one has to remember quite a few settings and the process how it was created in the first place) it might be nice to have a confirmation dialog (e.g., "Are you sure..."). 
A stupid alternative that reduces the risks of mistakes similarly (which is probably way less intuitive but maybe easier to implement): a checkbox beside the button that enables the button.
Since removal is seldom done an additional step to confirm it does not reduce BBT's UI effectiveness at all IMHO.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5813](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5813.xpi) ("fixes #1421")

Install in Zotero by downloading [test build 5.2.14.5813](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5813.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by stefanct** [comment]
Nice. Works for me. Thank you! Two nitpicks (I always find things to criticize, sorry :)
The reference to the auto-import looks/reads a bit strange:

> Are you sure you want to delete this-auto-export? This cannot be undone.

The first hyphen looks misplaced to me.

The other thing is the name of the dialog window. It reads `[JavaScript Application]`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5815](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5815.xpi) ("prettier title")

Install in Zotero by downloading [test build 5.2.14.5815](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5815.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by stefanct** [comment]
LGTM
