### ISSUE TITLE
paragraphs in Zotero notes need \par

### ISSUE THREAD

**Issue by clairekope** [retorquere/zotero-better-bibtex#1422]
**Report ID:** JVQPVNN2-euc

**Exporter used:** BBT BibLaTex

**Actual behavior:** Notes with multiple paragraphs have their line breaks converted to LaTeX double newlines, e.g.
```
<p>...unmodeled physics of the ISM.</p>
<p>Simulations show...</p>
```

is exported as
```
annotation = {...unmodeled physics of the ISM.

Simulations show...}
```

However, this double newline is collapsed by Biber into a single space (https://tex.stackexchange.com/questions/497673/), so that paragraph breaks in this style are not honored by Biber when generating, i.e., annotated bibliographies.

**Suggested behavior:** Insert the `\par` latex command instead of a double newline:
```
annotation = {...unmodeled physics of the ISM.
\par
Simulations show...}
```
This could also apply to abstracts with multiple paragraphs.

**Comment by retorquere** [comment]
@njbart, agreed?

**Comment by retorquere** [comment]
I'll need a debug log generated by right-clicking an item in Zotero and then send from the menu that pops up. JVQPVNN2-euc comes from the help menu and does not include a sample reference.

**Comment by clairekope** [comment]
Gotcha. New log is GE5EQHXG-euc

**Comment by retorquere** [comment]
Must it be

```
annotation = {...unmodeled physics of the ISM.
\par
Simulations show...}
```

or would

```
annotation = {...unmodeled physics of the ISM.\par

Simulations show...}
```

also do?

**Comment by retorquere** [comment]
And does something similar go for `<br />`?

**Comment by retorquere** [comment]
Currently, I export

```
Der Gleichzeitigkeitsgrad g (n) der Spitzenlastanteile Ps von Wohnungen wurde<br />aus Messungen
```

as 

```
Der Gleichzeitigkeitsgrad g (n) der Spitzenlastanteile Ps von Wohnungen wurde\\
aus Messungen
```

**Comment by retorquere** [comment]
Does the `\par` need newlines around it at all? I'm trying to figure out what to do with

```
<p>.....</p><p>....</p>
```

Ideally, you'd want only a single `\par` there, but I can't know this. So I'd either generate

```
\par ... \par \par ... \par
```

or 

```
... \par
... \par
```

and eliminate redundant `\par`s. Easier if I don't have to stuff too much context around them.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5825](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5825.xpi) ("adjust test cases")

Install in Zotero by downloading [test build 5.2.14.5825](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5825.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by clairekope** [comment]
`\par` does not need newlines; this functions as expected:
```
annotation = {...unmodeled physics of the ISM.\par Simulations show...}
```

I think just `</p><p>` should be converted to `\par`. Only replacing `</p>` might mess with spacing at the end of the text. Zotero puts a newline between `</p><p>`, but I assume you're using regex of some kind to find and replace and can therefore ignore spaces?

I think `<br />` should stay as `//`. In Zotero's HTML, it adds a newline without additional spacing between paragraphs like `<p>`. Using it in my LaTeX bib, it causes a newline but _ignores_ my paragraph indentation settings. So using `//` more closely mimics the behavior of `<br/ >`, if that makes sense.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5834](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5834.xpi) ("par cleanup")

Install in Zotero by downloading [test build 5.2.14.5834](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5834.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I can't really replace `<p></p>`; I use a HTML parser, not a regex parser. I do use a regex to clean up the results -- a new build is coming (you can ignore 5834) that does a decent job of things.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5835](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5835.xpi) ("cleanup")

Install in Zotero by downloading [test build 5.2.14.5835](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5835.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 5835 a go.

**Comment by clairekope** [comment]
Build 5835 works great!! Just as I was thinking. Thanks for your work!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5843](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5843.xpi) ("update test cases for #1422")

Install in Zotero by downloading [test build 5.2.14.5843](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5843.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
