### ISSUE TITLE
InspireHEP Lookup Fails

### ISSUE THREAD

**Issue by SolidTux** [retorquere/zotero-better-bibtex#1428]
**Report ID:** ~~GLCPF38G-euc~~ ~~D4GRSJC4-euc~~ JKTDRFHK-euc

**Expected behavior:** The citation key is imported from InspireHEP after clicking on the respective context menu entry (I don't know how it is called in English, in German it's "Hefte BibTeX-Schlüssel aus InspireHEP an").

**Actual behavior:** Nothing happens and key is unchanged.

The paper does exist on [InspireHEP](http://inspirehep.net/record/225985) and this function worked in the past for me.

**Comment by retorquere** [comment]
I need a debug log generated by right-clicking the item in question and sending a debug log from the menu that pops up. GLCPF38G-euc is from the help menu.

**Comment by SolidTux** [comment]
Sorry! Is D4GRSJC4-euc better?

**Comment by SolidTux** [comment]
That was the wrong entry ... now it should be correct:

JKTDRFHK-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.16.5886](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.5886.xpi) ("fixes #1428")

Install in Zotero by downloading [test build 5.2.16.5886](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.5886.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by SolidTux** [comment]
That fixed it! Thank you for the very fast response and fix!

**Comment by retorquere** [comment]
Thanks for reporting. Only I can close issues on this repo, I keep them open as a reminder to actually merge the fix into the release branch. I have one more open issue and will cut a new release with both probably tonight, but you can keep using this in the interim. You will be upgraded automatically.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.16.5889](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.5889.xpi) ("fixes #1428")

Install in Zotero by downloading [test build 5.2.16.5889](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.5889.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.16.5890](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.5890.xpi) ("fixes #1428")

Install in Zotero by downloading [test build 5.2.16.5890](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.5890.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
