### ISSUE TITLE
BBT and Zotero 5.0.82

### ISSUE THREAD

**Issue by kent930** [retorquere/zotero-better-bibtex#1429]
Hello,

When I try to install the BBT extension I get the following error:
`The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.`

I am running Zotero 5.0.82 on Fedora and tried to install better-bibtex v5.2.16.

Edit: Solved by re-downloading the extension using Chrome instead of Firefox.

**Comment by retorquere** [comment]
You can also download with Firefox (I do it all the time) by right-clicking the link and selecting "save link".

The error message you see is an unfortunate way that Firefox (which is what Zotero still builds on) say "I don't recognize this". While the file has the `.xpi` extension, its contents was likely the HTML page that had the redirect to the actual xpi. There is unfortunately nothing I can do about this.
