### ISSUE TITLE
Non-breakable spaces in author fields should be exported as tilde

### ISSUE THREAD

**Issue by stefanct** [retorquere/zotero-better-bibtex#1430]
While entering and exporting NBSPs (u+00a0) in other fields like the title lead to proper `~` this is not the case in the author field. There they are simply written as SP (u+0020). I did not find a workaround since for example `~` in Zotero **is** translated to `\textasciitilde{}`.

The example in **Report ID:** CRRYZ9ZY-euc shows the problem with the "author" "JTC 1/SC 22/WG 14".

**Comment by retorquere** [comment]
Was this with Better BibTeX or with Better BibLaTeX?

**Comment by stefanct** [comment]
Doesn't matter: both show the same behavior AFAICT.

**Comment by retorquere** [comment]
There was a discussion on this a while ago in #859. @njbart usually know a lot about this and advised to replace ZWS with nothing, and other-spaces with a simple space. Do you think that assessment no longer holds? What breaks for you when the NBSP is replaces with a regular space? I'm OK with leaving the NBSP as long as it doesn't break other stuff.

**Comment by stefanct** [comment]
Not sure which of these questions are to me so please ignore at will... :)

It's really an edge case obviously. However, the official documents by ISO have a space in there so removing them is obviously not ideal (OTOH probably nobody but the most pedantic persons would even notice it - and it would probably be my preferred workaround if need be). If left in as normal spaces then line breaks could easily make it even worse... that's why I was thinking about NBSPs at all and tried them.

When I noticed it not working I tried around with the other fields and since it showed a different behavior it became interesting enough to report it. Although I googled I have not found the other issue. I would have been OK with the space replacement *if* there would have been any indication (and rationale) that the replacement is on purpose, e.g., a hint in the quality report would have been totally fine with me.

**Comment by retorquere** [comment]
The question was indeed for you. And it doesn't really matter whether it's an edge case, edge cases matter too. But what you're saying is that in the rendered output the spaces are not present? Aside any issues with line breaks? That would mean I'd have to export the `NBSP`s.

**Comment by njbart** [comment]
Maybe I’m not seeing the obvious, but what exactly is the problem with ordinary (as opposed to non-breaking) spaces in author names such as “JTC 1/SC 22/WG 14”?

**Comment by retorquere** [comment]
The reason I started replacing them is because these space-like characters quite often got into zotero by copy-paste and were not intended. But I have no problem making an exemption for NBSP if that solves a problem.

**Comment by njbart** [comment]
> The reason I started replacing them is because these space-like characters quite often got into zotero by copy-paste and were not intended.

Agreed.

> But I have no problem making an exemption for NBSP if that solves a problem.

My question is, is there a genuine problem with ordinary spaces in “JTC 1/SC 22/WG 14” in the first place?

**Comment by stefanct** [comment]
> > But I have no problem making an exemption for NBSP if that solves a problem.
> 
> My question is, is there a genuine problem with ordinary spaces in “JTC 1/SC 22/WG 14” in the first place?

Well, if it's genuine or a problem is probably debatable but with normal spaces you could get a final output in the PDF with line breaks in between, e.g.:

    JTC 1/SC
    22/WG 14

**Comment by njbart** [comment]
I see. So what this seems to boil down to is whether accepting the possibility of line breaks in “JTC 1/SC 22/WG 14” or risking suboptimal overall paragraph layout is the lesser evil – in which case I’d say, the first one is.

**Comment by stefanct** [comment]
I would rather say the question is if BBT should decide this or the user. If you forcefully remove NBSPs there is no way to override this behavior. If they are exported like in other fields the user can simply replace them with normal spaces if he wants line breaks.

Compare it to a hypothetical BBT extension that replaces all occurrences of "teh" in titles with no way to override it. I hope we agree that this would be a bad idea.

**Comment by stefanct** [comment]
> The question was indeed for you. And it doesn't really matter whether it's an edge case, edge cases matter too. But what you're saying is that in the rendered output the spaces are not present? Aside any issues with line breaks? That would mean I'd have to export the `NBSP`s.

In the exported `.bib` (without your patch) I get normal spaces:

    author = {{JTC 1/SC 22/WG 14}},

I would have expected this:

    author = {{JTC~1/SC~22/WG~14}},

I would then probably try adding zero-width spaces after the `/` to make them break at the _right_ places to make sure typesetting does not have a too hard time to flow the paragraph. I would then notice that this does indeed get converted but I think not correctly: it produces a `\mbox{}` which does not allow lines break I think (it certainly does not make them in my test). I think the correct replacement would be `\hspace{0pt}`. So eventually I would arrive at something like below (which is obviously repeated for testing):

    author = {{JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14/\hspace{0pt}JTC~1/\hspace{0pt}SC~22/\hspace{0pt}WG~14}},

Which would create this final output in the bibtex style I use:

![image](https://user-images.githubusercontent.com/457881/74426405-9cea2a00-4e55-11ea-9bae-0ecab924c5d8.png)

What's the rationale for the `mbox`? Would you like me to open another issue for that?

**Comment by retorquere** [comment]
I can try making an exception for NBSP because I understand where it's coming from, but I think the comparison with `teh` is a little silly, and I've never seen anything resembling that author. There's a clear difference between these cases and whitespace replacement. It is also not the case that BBT should never transform the input; quite a bit of effort goes into parsing dates into something sensible. Let's not devolve into whataboutism and just discuss the merit of the proposal at hand.

I probably took the mbox from a list I imported to get the mapping started. It's not a deliberate choice on my part.

**Comment by stefanct** [comment]
Of course the example is silly - I was exaggerating to make the point that users should have the last say. (However, the example is less far fetched than you might think: https://scholar.google.at/scholar?hl=en&as_sdt=0%2C5&q=%22teh%22).

As you say, BBT's purpose is actually to convert the Zotero data into something reasonable so that the user does not have to think about it too much or to fix it manually after exporting. But it can never be perfect because there are sometimes no clearly best solutions (like in the C99 example). Thus my argumentation for not forcing things without an option for the user to get around it if need be. However, I understand that there are some users (probably the majority) who do not care enough for such things to even known about NBSPs or ZWSPs. UI design is hard :)

The commit you linked to earlier... is that something you want me to test (because AFAICS I would have to build BBT then or did I miss something)?

**Comment by retorquere** [comment]
Oh wait - mbox is discussed in #859.

**Comment by stefanct** [comment]
It is but AFAICS the only alternative discussed there is to leave the UTF character `\u200B` in place and not other LaTeX alternatives.

**Comment by retorquere** [comment]
No, no need to build anything, that's just github announcing a link between the commit and the issue. Once I commit a version that passes all tests (the change doesn't currently, because a test case associated with #859 doesn't pass) a new build will be uploaded here.

I'm stuck in meetings for the next few hours, when I'm free again I'm open to to any change that works. I know too little about bibtex and biblatex to have strong opinions on the matter.

**Comment by retorquere** [comment]
I do have concerns about breaking changes, so it'd be good to have some assurance that the concerns voiced in #859 remain addressed in whatever solution we settle on.

**Comment by stefanct** [comment]
For biblatex (and thin spaces) this seems relavent: https://tex.stackexchange.com/a/11083/23277

**Comment by retorquere** [comment]
You'll have to translate for me what that entails for BBT.

**Comment by stefanct** [comment]
I think we should wait for further input of @njbart.

**Comment by retorquere** [comment]
@stefanct I'm pretty curious now what's behind the scholar link, but I just get "Please enter a query in the search box above."

**Comment by stefanct** [comment]
@retorquere Hm, I have removed some GET-parameters, maybe that works better? https://scholar.google.at/scholar?q="teh"
I don't know why either of those would force you to log in... In any case you can simply search for _"teh"_ on google scholar yourself. The quintessence is that there are actually people named "Teh" :)

**Comment by retorquere** [comment]
Oh that, yeah that's not surprising, I was thinking about the part you mentioned as repeated for testing.

**Comment by stefanct** [comment]
Hm, that was in another message with no relation to google scholar though...? And in that message (with the repeated author line) there are no links whatsoever, apart from the screenshot that is hosted by github. Now I am confused. :)

**Comment by retorquere** [comment]
Crossed signals then. I thought the repeating sample unlikely because I've not seen anything like it in the real world, and the teh example unlikely because I'd see no reason to change the locution that way. So I thought the scholar link was meant to show something like the repeating sample actually did have a real-world lookalike.

**Comment by stefanct** [comment]
I see. The purpose of the repetition is simply to demonstrate the line breaking and paragraph formatting I would like to be able to attain eventually. In my current style the author comes in the beginning so line breaking is not very likely but if it comes after the title it is very much possible to require breaking with a short author of course.

**Comment by retorquere** [comment]
I'm willing to exclude NBSP if that doesn't break #859, but an actual use - case would be preferable.

**Comment by njbart** [comment]
To recap: Initially, https://github.com/retorquere/zotero-better-bibtex/issues/859 was about `\,` in name fields breaking things on the bib(la)tex side, so we concluded that thin space (U+2009) must not be mapped to `\,` but to an ordinary space instead. We then decided to map some other space-like chars to ordinary space chars (U+0020) as well, with the exception of ​zero width space (U+200B), for which there was an actual use case, so this got mapped to `\mbox{}`.

The only thing I’d actually expect to break if BBT started mapping no-break spaces in name fields to `~` is line-breaking behaviour for users who might happen to have, inadvertently or not, nbsp’s in the name fields of some of their entries. If you’re willing to risk that, fine with me.

Another option, however, might be to just postprocess any name fields in question, either, if possible, on the BBT side, or by employing biblatex’s `\DeclareSourcemap` mechanism:

In the example below, `\DeclareSourcemap` selects all author fields containing `/` (I’m assuming here that ordinary names don’t contain forward slashes) and, in that selection, replaces all ordinary spaces by `~`, and all `/`s by `/\hspace{0pt}`. If that’s a satisfactory solution for the OP, BBT wouldn’t have to be modified at all.

```
\documentclass{article}

\begin{filecontents}{\jobname.bib}
@book{jtc,
  author = {{JTC 1/SC 22/WG 14}},
  date = {2011},
  title = {A Title},
  publisher = {Publisher},
  langid = {en},
  address = {Place}
}
@book{jtc2,
  author = {{JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14/JTC 1/SC 22/WG 14}},
  date = {2011},
  title = {A Title},
  publisher = {Publisher},
  langid = {en},
  address = {Place}
}
@book{un,
  author = {{United Nations}},
  date = {2017},
  title = {A Title},
  publisher = {Publisher},
  langid = {en},
  address = {Place}
}
\end{filecontents}

\usepackage[style=authoryear]{biblatex}

\addbibresource{\jobname.bib}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[fieldsource=author,
        match=\regexp{/},final]
      \step[fieldsource=author,
        match=\regexp{\x20}, replace=\regexp{~}]
      \step[fieldsource=author,
        match=\regexp{/}, replace=\regexp{/\\hspace\{0pt\}}]
    }
  }
}

\begin{document}

Foo \autocite{jtc}.

Bar \autocite{jtc2}.

Baz \autocite{un}.

\printbibliography

\end{document}
```

**Comment by retorquere** [comment]
I also have a strong preference for a solution that does not introduce a new preference. BBT has too many as it is.

The characters under consideration are:

```
0020 SPACE
00A0 NO-BREAK SPACE
2000 EN QUAD
2001 EM QUAD
2002 EN SPACE
2003 EM SPACE
2004 THREE-PER-EM SPACE
2005 FOUR-PER-EM SPACE
2006 SIX-PER-EM SPACE
2007 FIGURE SPACE
2008 PUNCTUATION SPACE
2009 THIN SPACE
200A HAIR SPACE
200B ZERO WIDTH SPACE
202F NARROW NO-BREAK SPACE
205F MEDIUM MATHEMATICAL SPACE
3000 IDEOGRAPHIC SPACE
FEFF ZERO WIDTH NO-BREAK SPACE
```

**Comment by retorquere** [comment]
@njbart in the case you describe I would lean towards keeping the NBSP and using a sourcemap to replace them with regular spaces.

**Comment by retorquere** [comment]
Where are we on this guys? Any proposals for the mappings above?

**Comment by retorquere** [comment]
@stefanct any updates? I'm prepping for a release.

**Comment by stefanct** [comment]
Sorry, I am swamped ATM (this will be resolved within a week). njbart's proposal is certainly the right way to go for biblatex. Unfortunately, that does not help (me) with bibtex though. I will look at it in more detail in a few days. If you want to tag a release in the meantime I am totally fine with that.

**Comment by retorquere** [comment]
Any updates?

**Comment by stefanct** [comment]
Sorry, I forgot to get back at this back then. If I understood @njbart correctly then his approach of using biblatex' source mapping does only affect biblatex and not bibtex (and I am not sure how it would be integrated into BBT at all either). It's also unclear what solution you actually consider/propose (for the bibtex case). Regarding the table above I propose the following differences:

- ZWSP: `\hspace{0pt}` (explained earlier).
- en quad: this should be the same as en space.
- em quad: this should be the same as em space, and `\quad` indeed is. You could likewise declare the em space as `\quad` too AFAIK.
- 202F: should probably be thinner... like `\,`.
- FEFF: this *could* be "mapped" to an `\mbox` around the characters preceding and following the space character (but that's not an easy 1:1 mapping).

http://jkorpela.fi/chars/spaces.html has some concise explanations

**Comment by retorquere** [comment]
Sorry this lagged so long, most of these had been updated long ago.
