### ISSUE TITLE
What is right config for special bibtex characters

### ISSUE THREAD

**Issue by kirk86** [retorquere/zotero-better-bibtex#1432]
I'm trying to compile the tex file of .bib exported from BBT but it gives me an error on two instances due to special characters. Let me briefly explain.

I have the following entry which contains the following latex symbol
1. ![image](https://user-images.githubusercontent.com/2902390/74383936-15b29d00-4de8-11ea-9841-9b84914bc8fe.png)

In the exported .bib file is written as `{$\mathscr{l}$}1-Penalized`

And 

the second entry
2. ![image](https://user-images.githubusercontent.com/2902390/74384152-983b5c80-4de8-11ea-965a-0c7fcab53949.png)

which is written in the .bib file as `{\'S}wi{\k{a}}tkowski`

These two are causing the latex file to not compile and render properly.
After the following changes 
1. from `{$\mathscr{l}$}1-Penalized` to `{$\ell_{1}$}-Penalized`
2. from `{\'S}wi{\k{a}}tkowski` to `\'{S}wi{\t{a}}tkowski`

Even though `{\k{a}}` is different from `{\t{a}}` things seem to be compiling without errors.

Question: Is there possibly some setting that I'm missing or is this zotero or maybe bbt fault?

**Comment by retorquere** [comment]
I'll need a debug log generated by selecting those entries, right-clicking, and sending a debug log from the popup menu.

**Comment by kirk86** [comment]
Ok I think I might have fixed my issue by adding font encoding T1 in the .tex file. Do you still need a debug log?

**Comment by retorquere** [comment]
If it's fixed, then no. What did you add to the document specifically?

**Comment by kirk86** [comment]
I just added `\usepackage[T1]{fontenc}`

**Comment by retorquere** [comment]
Thanks. I have infrastructure in place to recommend packages, but not with specific parameters like `[T1]`. I'll have to think about that.
