### ISSUE TITLE
micro sign (unicode B5) export seems wrong

### ISSUE THREAD

**Issue by paultjevdh** [retorquere/zotero-better-bibtex#1434]
Hi,

I have some documents with a micro sign (unicode 00B5) in the title. This is an upright µ character, different from the greek µ (unicode 03BC) used as a variable which is typically in italics.
The better bibtex export code for this character is $\mathrm{\mu}$. In my latex installation this produces an _italics_ µ.
Wouldn't it be better to translate the micro sign to \textmu?
error report ID: NKAUHWLR-euc

Steps to reproduce 
Export entry "NEC µPC577H Tri state hex buffers" with better bibtex
contents of the generated output bib file:

```
@misc{noauthor_nec_nodate,
  title = {{{NEC $\mathrm{\mu}$PC577H Tri}} State Hex Buffers}
}
```

desired output:
```
@misc{noauthor_nec_nodate,
  title = {{{NEC {\textmu}PC577H Tri}} State Hex Buffers}
}
```
Best regards,
Paul

**Comment by retorquere** [comment]
I see the problem. But are you saying 00B5 and 03BC should be swapped in the mapping? because 03BC does output `\textmu`.

**Comment by paultjevdh** [comment]
Hi,

No I don't want any swapping, 03BC outputs $\mu$, _not_ \textmu and I want them to be _different_.

Consider the following title "A-D test title with lower case greek letter μPC4570, which is not the same as 1µF"
Both µ characters are different, as you can see by pasting them in https://www.fileformat.info/info/unicode/char/search.htm?q=%C2%B5&preview=entity
I get 
GREEK SMALL LETTER MU | U+03BC | GREEK SMALL LETTER MU | μ
and 
MICRO SIGN | U+00B5 | MICRO SIGN | µ
respectively.

Better bibtex export gives:
@inproceedings{author_-d_2025,
  title = {{A-D test title with lower case greek letter {$\mu$}PC4570, which is not the same as 1{$\mathrm{\mu}$}F}},
  booktitle = {{Proceedings of the test}},
  author = {Author, P. A.},
  year = {2025},
  pages = {123  ----      432},
  abstract = {This is an example
The first mu should be a greek mu which will turn out italic, the second is a textmu which should look the same as the surrounding text},
  language = {Dutch}
}
from better bibtex, (38V9A3TV-euc)

whereas bibtex.js generates
@inproceedings{author_-d_2025,
	title = {A-{D} test title with lower case greek letter $\mu${PC4570}, which is not the same as {1{\textmu}F}},
	abstract = {This is an example
The first mu should be a greek mu which will turn out italic, the second is a textmu which schould look the same as the surrounding text},
	language = {Dutch},
	booktitle = {Proceedings of the test},
	author = {Author, P. A.},
	year = {2025},
	pages = {123  --      432}
}

The greek small letter mu 03BC is translated to $\mu$ by by both.
The micro sign 00B5 is translated to {$\mathrm{\mu}$} by better bibtex
The micro sign 00B5 is translated to {\textmu} by bibtex.js

So the proposed change is to change the mapping for 00B5 to \textmu and leave 03BC as is. 
Best regards
Paul

**Comment by retorquere** [comment]
> No I don't want any swapping, 03BC outputs `$\mu$`, _not_ `\textmu` 

Yep, sorry, you're correct.

> and I want them to be _different_.

But why? When you say

> ```
> GREEK SMALL LETTER MU | U+03BC | GREEK SMALL LETTER MU | μ
> ```
> 
> and
> 
> ```
> MICRO SIGN | U+00B5 | MICRO SIGN | µ
> ```

Those both look upright to me, not slanted.

**Comment by paultjevdh** [comment]
Hi

> But why?

Because you can use µ either as a variable or as a 10^-6 in the title of an article. Even though zotero itself (or this forum) doesn't display these as different, I think in the bibliography you want variables displayed as math ($\mu$) , whereas a unit of coil of 1µH should be body text (\textmu).
Paul

**Comment by retorquere** [comment]
But isn't that choice between which char maps to which latex arbitrary here? Why 00B5 -> `\textmu` and 03BC -> `$\mu$`? If anything, `GREEK SMALL LETTER MU` seems a better match for `\textmu` than for `$\mu$`. If someone is outputting an actual greek title with 00B5 it would seem better to use `\textmu` there.

**Comment by paultjevdh** [comment]
Hi,
I agree I did not consider someone writing in greek, but I think typically the greek alphabet is used by mathematicians, physicists etc for any kind of variable, and these are in the unicode range  0370–03FF (https://unicode.org/charts/PDF/U0370.pdf)
So I would suggest using \mu there, since \alpha-\omega are in the same range.
On the other hand, the micro sign is in the unicode table with supplemental characters for latin (https://www.unicode.org/charts/PDF/U0080.pdf)
similarly ohm (resistance unit) in text is unicode 2126 from https://www.unicode.org/charts/PDF/U2100.pdf

I think the special use motivates a special character. That's why unicode specifies them twice I think.
Best regards,
Paul

**Comment by retorquere** [comment]
I'm still thinking about the best way to solve this. I recognize that it's going to be common to use the mu char this way.

**Comment by paultjevdh** [comment]
Hi,
I'm wondering why it is complicated, since the two _are_ already different in the current state ($\mu$ or {$\mathrm{\mu}$}).
The only change I propose is a different mapping for the upright µ since {$\mathrm{\mu}$} is printed slanted in my setup. The proposed \textmu gives the desired result.
Best regards,
Paul

**Comment by retorquere** [comment]
I'm trying to wrap my head around this... both `GREEK SMALL LETTER MU` and `MICRO SIGN` are usually written upright, right, not slanted? So that would favor `\textmu` for both?

**Comment by retorquere** [comment]
> I'm wondering why it is complicated, since the two _are_ already different in the current state (`$\mu$` or `{$\mathrm{\mu}$}`).

For me these both print slanted.

> The only change I propose is a different mapping for the upright µ since {$\mathrm{\mu}$} is printed slanted in my setup. The proposed \textmu gives the desired result.

I fully agree. I'm now just wondering whether I should map 03BC to `\textmu` *also*.

**Comment by retorquere** [comment]
I think I have it. `𝜇` maps to `\mu`, `µ` and `μ` map to `\textmu`

**Comment by paultjevdh** [comment]
yes!

**Comment by dbitouze** [comment]
> The only change I propose is a different mapping for the upright µ since {$\mathrm{\mu}$} is printed slanted in my setup.

@paultjevdh If I'm right, `\mathrm` (and the like) only applies to latin characters.

**Comment by retorquere** [comment]
Is `\Omega` supposed to work in text mode? It does for me, but I didn't expect it to.

**Comment by dbitouze** [comment]
> Is `\Omega` supposed to work in text mode? It does for me, but I didn't expect it to.

I don't think so:
```latex
\documentclass{article}
\begin{document}
\Omega
\end{document}
```
gives:

> ERROR: Missing $ inserted.
>
>--- TeX said ---
><inserted text> 
 >               $
>l.3 \Omega
>           
>--- HELP ---
>TeX probably found a command that can be used only in math mode when
>it wasn't in math mode. [...]

**Comment by retorquere** [comment]
right

**Comment by retorquere** [comment]
@paultjevdh don't forget to open an issue for the dashes and the citekey generation with `<span>` in the title.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5926](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5926.xpi) ("ncu")

Install in Zotero by downloading [test build 5.2.14.5926](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5926.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 5926 a spin.

**Comment by paultjevdh** [comment]
Am I correct in thinking that you changed the replacement of _all_ µ to the same \textmu?
That's not the same as
> I think I have it. 𝜇 maps to \mu, µ and μ map to \textmu

Paul

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5932](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5932.xpi) ("adjust tests for #1434")

Install in Zotero by downloading [test build 5.2.14.5932](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5932.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
`\u00b5`, `\u03bc` and `\ud835\udf7b` ('µ', 'μ', '𝝻') are converted to `\textmu`; `\ud835\udf07`, `\ud835\udf41`, `\ud835\udfb5` ('𝜇', '𝝁', '𝞵') are converted to `\mu`.

**Comment by paultjevdh** [comment]
I think I did not correctly understand what you meant when I said "yes!" 2 days ago.
Just to make sure we're on the same page: how do you map unicode 03B1 - 03C9 (lower case greek alphabet)?
I just took them from the 'character map' program in windows:
ααβγδεζηθικλμνξοπρςστυφχψω
This is a continuous range of unicode characters.
The test build 5.2.14.5932 converts this to 
{$A\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\iota\kappa\lambda$}\textmu{$\nu\xi{}o\pi\rho\varsigma\sigma\tau\upsilon\varphi\chi\psi\omega$}

(The 1st alpha is capitalized to A instead of \Alpha, I don't know why.)
All the lower case greek letters in this range, except µ, are translated to the math greek characters. Don't you think the exception for µ is strange? I think µ (03BC) should _not_ be an exception.

I think correct is
µ (03BC)  => $\mu$
µ (00B5) => \textmu

Paul

**Comment by retorquere** [comment]
You can view the entire table [here](https://unpkg.com/browse/unicode2latex/tables/unicode.json).

But why µ (03BC) => `$\mu$`? `$\mu$` is slanted, µ is not.

**Comment by retorquere** [comment]
But looking at the range you specified, almost everything in that range is currently not mapped correctly.

**Comment by retorquere** [comment]
03B1 should probably map to `\textalpha`. 1d6fc should map to `\alpha`

**Comment by paultjevdh** [comment]
That's a question of perspective. I prefer consistency. 
I don't think the complete greek alphabet exists as \textxxx

Paul

**Comment by retorquere** [comment]
That's going to affect a *bunch* of the stuff in the mapping. Basically everything text- or number-like in math mode.

**Comment by retorquere** [comment]
What misses in http://ctan.triasinformatica.nl/macros/latex/contrib/textgreek/textgreek.pdf ?

**Comment by paultjevdh** [comment]
You're correct, the list in textgreek is complete. Only 3C2 is missing, but that's a variant of sigma (currently 3C2=\varsigma, 3C3=\sigma)
It's up to you to decide whether you want to change just µ or change the other 23.
Paul

**Comment by retorquere** [comment]
> I think correct is
> µ (03BC) => $\mu$
> µ (00B5) => \textmu

I'm still trying to reconstruct the logic behind this. The issue was started with

> I have some documents with a micro sign (unicode 00B5) in the title. This is an upright µ character, different from the greek µ (unicode 03BC) used as a variable which is typically in italics.

but both 00B5 and 03BC are upright. So why map 03BC to `$\mu$`?

**Comment by paultjevdh** [comment]
Hi,
You're right. My distinction is not based on the unicode definition, but what latex/bibtex does to them. 
All the ordinary greek characters (=the greek alphabet range in the unicode table) currently end up in math mode = slanted. I thought this was intentional to properly set variables. The µ in this range (03BC) should behave alike. The situation before this discussion started was exactly that.
My question was only to change 'micro sign' behaviour which serves a different purpose and is located in a different part of the unicode table. I was then surprised when 'greek small letter mu' also changed.
Maybe we should start a new thread about this:
- this thread: change micro sign 00B5 from {$\mathrm{\mu}$} to \textmu , done, can be closed
- a new question: whether the current mapping for the greek alphabet 03B1 - 03C9 (lower case, maybe the upper case range as well), should be changed from math- to text mode ($\alpha$ => \textalpha), or not.

Paul

**Comment by njbart** [comment]
> a new question: whether the current mapping for the greek alphabet 03B1 - 03C9 (lower case, maybe the upper case range as well), should be changed from math- to text mode ($\alpha$ => \textalpha), or not.

I’d discourage that since it won’t work in LaTeX without loading additional packages (see [here](https://texblog.org/2012/03/15/greek-letters-in-text-without-changing-to-math-mode/) and [here](https://tex.stackexchange.com/questions/332295/command-textalpha-unavailable-in-encoding-t1-when-using-greek)). Surprisingly, `\textmu` is the only command that works in the absence of any extra packages.

MWE, processed with pdflatex from TeX Live 2019:

```
\documentclass{article}
\begin{document}
\textmu
\end{document}
```

**Comment by retorquere** [comment]
>     * this thread: change micro sign 00B5 from {$\mathrm{\mu}$} to \textmu , done, can be closed

I'm not currently sure this was the right thing to begin with. If the argument for this change is:

> unicode 00B5 is an upright µ character, different from the greek µ (unicode 03BC) used as a variable which is typically in italics.

They are both upright. So if this is the argument for the change, they should both be `\textmu`. If there is no other argument, then why change the behavior of the current release?

> I’d discourage that since it won’t work in LaTeX without loading additional packages

That is a good point, but that again brings the question: why change the behavior in the current formal release?

**Comment by retorquere** [comment]
Oh hello @njbart. I had missed that it was you in the last response. Is there a way to make the greek chars in math mode upright?

**Comment by njbart** [comment]
The easiest solution I’m aware of is to use the [upgreek](https://www.ctan.org/pkg/upgreek) package. For other approaches, see [here](https://tex.stackexchange.com/questions/109375/how-to-switch-to-upright-greek-in-math-mode) and [here](https://tex.stackexchange.com/questions/30550/force-upright-greek-letters-with-isomath). Note, though, that all of these depend on loading additional packages, so I wouldn’t exactly recommend this for BBT either.

**Comment by paultjevdh** [comment]
Hi,
Textmu works because it is in the textcomp package which has been adopted as part of the latex distribution, so it is no longer required to load it separately.
The other textgreek letters are in the textgreek package, which must be loaded by the user.

My upright/slanted argument is wrong insofar that I should never have made the comparison with 03BC and how it is set. The argument should just have been: the µ in µm, µF, etc should be set the same way as the surrounding text. Wrapping it in math and mathrm does not do that. With this MWE:

```
\documentclass{article}
\begin{document}
\textmu
\emph{\textmu}
\end{document}

```
 you'll see that \textmu does just that. 

Paul

**Comment by retorquere** [comment]
So both 00B5 and 03BC should map to `\textmu`? Or is micro usually written slanted? But then why isn't 03BC slanted?

**Comment by njbart** [comment]
My view:

U+03BC belongs to the „Greek and Coptic“ Unicode block, and I would avoid introducing any new inconsistencies by treating it any different than all the other Greek characters in its neighbourhood – so continuing to map U+03BC to `$\mu$` seems best.

U+00B5, on the other hand, belongs to the „Latin-1 Supplement“ Unicode block, but bears no specific connection to its neighbours, so giving it a special treatment by mapping it to `\textmu` seems ok.

**Comment by paultjevdh** [comment]
Exactly what I've been trying to say a few times.
Paul

**Comment by retorquere** [comment]
Ok so nothing to do with being upright then?

**Comment by retorquere** [comment]
The test cases you submitted would then become

```
@misc{_NECuPC577HTristatehexbuffers_,
  title = {{{NEC \textmu{}PC577H Tri}} State Hex Buffers},
  annotation = {In Yamaha tuner IC101 en IC102}
}

@inproceedings{Author_ADtesttitlewithlowercasegreeklettermPC4570whichisnotthesameas1uF_2025,
  title = {A-D test title with lower case greek letter {$\mu$}PC4570, which is not the same as 1\textmu{}F},
  booktitle = {Proceedings of the test},
  author = {Author, P. A.},
  date = {2025},
  pages = {123---432},
  abstract = {This is an example
The first mu should be a greek mu which will turn out italic, the second is a textmu which schould look the same as the surrounding text},
  langid = {dutch}
}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5952](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5952.xpi) ("jurism beta still broken")

Install in Zotero by downloading [test build 5.2.14.5952](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5952.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by paultjevdh** [comment]
Hi,
I was off-line for a few days. 
I just tested the test build and I think it is just what I wanted.

Thanks

Paul

**Comment by retorquere** [comment]
Alright, merged to master, will be in the upcoming release.
