### ISSUE TITLE
Git pull/push is not triggered on automatic export

### ISSUE THREAD

**Issue by eppfel** [retorquere/zotero-better-bibtex#1439]
First, excellent work you are doing! 

**Report ID:** 7MDMY2W3-euc

**Exporter used:** Automatic export BibTex with Zotero on Mac

**Expected behavior:** I have configured multiple automatic exports and setup git repositories for the respective overleaf projects. I set git config in order to push on change to overleaf.

**Actual behavior:** Although the export works (I find a changed file in the repository), it is not added/commited/pushed. 

It was working a few weeks ago but I have set up new projects since then.

Any other info I could give you? How could I get more debug output because in the debug logs I don't see anything pointing towards git.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5944](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5944.xpi) ("fixes #1439")

Install in Zotero by downloading [test build 5.2.14.5944](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5944.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 5944. Thanks for reporting this.

**Comment by retorquere** [comment]
closing for lack of feedback

**Comment by eppfel** [comment]
Thanks for this super quick fix. Sorry, for missing it. It seems to work.

**Comment by retorquere** [comment]
Cool, thanks, I'll schedule a release.
