### ISSUE TITLE
Edition Numbers in BibTeX Exports

### ISSUE THREAD

**Issue by qak** [retorquere/zotero-better-bibtex#1446]
The Zotero [documentation](https://www.zotero.org/support/kb/item_types_and_fields) claims that numerical edition numbers should be entered as Arabic numbers:

>  [...] Where numeric, enter as simple Arabic numeral (i.e., “2” rather than “second”).

But BibTeX expects edition numbers to be entered as strings. From the BibTeX package's documentation:

> **edition** The edition of a book—for example, “Second”. This should be an ordinal, and should have the first letter capitalized, as shown here; the standard styles convert to lower case when necessary.

I've verified this claim by creating a minimal-working LaTeX file, copying over a BBT exported BibTeX bibliography file and comparing the output PDF with string and integer edition numbers. I've tried this with the Natbib styles _plain_ and _plainnat_. String edition numbers are output as expected (e.g. second edition) but integer numbers are output in an awkward-looking manner (e.g. 2 edition).

BibLaTeX on the other hand prefers integer edition numbers. From the BibLaTeX package's documentation:

> [...] The edition of a printed publication. This must be an integer, not an ordinal. Don’t say `edition={First}` or `edition={1st}` but `edition={1}`. The bibliography style converts this to a language dependent ordinal. It is also possible to give the edition as a literal string, for example “Third, revised and expanded edition”.

This means that when one correctly enters edition numbers as integers into Zotero, they are correctly exported by BBT only when exporting BibLaTeX bibliography files. In order for BBT to correctly export BibTeX bibliography files, BBT needs to convert integers to capitalised strings as described in the package's documentation. Would this be possible? I guess there might be a library available for converting integers to strings. Even just hardcoding the first 10 or 20 edition numbers would probably cover the vast majority of existing edition numbers.

An obvious temporary workaround would be to change the edition numbers in Zotero to strings. I guess that another option for me would be to add a [postscript](http://retorque.re/zotero-better-bibtex/exporting/scripting/) that converts the integer edition numbers occurring in my reference list to strings. Of course fixing the issue in BBT would be ideal.

**Comment by retorquere** [comment]
I think it's doable, but I would appreciate a debug report as per point 1 above. It will give me a test case to work with.

**Comment by qak** [comment]
This is the debug report's ID: `KUFC4KDR-euc`. Does the report have a reference attached? I'm a bit unsure whether I've done it correctly.

**Comment by retorquere** [comment]
It does have a reference attached, thank you. I'm in the middle of fixing another bug, but I'll get to this one just after -- the problem you describe shouldn't be hard to fix.

**Comment by retorquere** [comment]
Would this always be in English? If you have an article with language German, would series still need to be `Second`, or should it then be `Zweite`?

**Comment by retorquere** [comment]
@qak one of my testcases has `edition` set to `9 Dover printing, 10 GPO printing` in their Zotero library. Should that become `Ninth Dover printing, tenth GPO printing`, or be left as-is?

@njbart? Opinions? Or are you more about biblatex?

**Comment by retorquere** [comment]
@qak must the ordinal be capitalized?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.6035](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6035.xpi) ("adjust tests for #1446")

Install in Zotero by downloading [test build 5.2.14.6035](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6035.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Try 6035

**Comment by qak** [comment]
> Would this always be in English? If you have an article with language German, would series still need to be `Second`, or should it then be `Zweite`?

I didn't think of this when creating this issue. Reading the BibTeX package's documentation doesn't suggest that BibTeX has been developed with internationalisation in mind. The quote from the documentation

> __edition__ The edition of a book—for example, “Second”. This should be an ordinal, and should have the first letter capitalized, as shown here; the standard styles convert to lower case when necessary.

would indeed suggest that ordinals should be written in the language the user wants printed in his or her bibliography. I've just tested a few non-English bibliography styles distributed with TeX Live and most of them just printed the English ordinal into the bibliography (the ordinals seemed always appropriately capitalised though).

This would mean that BBT should not only convert integers to strings but also translate them into _the language of the user's bibliography_. But _the language of the user's bibliography_ isn't something that Zotero keeps track of. Or am I wrong? Whilst bibliography items in Zotero do have a language field, this field only holds the language of the bibliography item itself (or the language of its metadata in Zotero), which can be different from the language of the user's TeX or LaTeX document.

> Try 6035

I'll try it ASAP.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.6041](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6041.xpi) ("Merge branch 'master' into gh-1446")

Install in Zotero by downloading [test build 5.2.14.6041](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6041.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
It might not be the style language but the reference language. Try adding a language field.

**Comment by retorquere** [comment]
I don't think I can sensibly add translated numbers.

**Comment by retorquere** [comment]
I could use https://github.com/yamadapc/js-written-number which would give me a few languages, but the problem of detecting what language to use remains.

**Comment by retorquere** [comment]
@njbart, I know you're more involved with biblatex than bibtex, but ideas on this?

**Comment by qak** [comment]
I've tried [test build 5.2.14.6041](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6041.xpi) and it works as expected. If I continue using the test build, will BBT automatically upgrade to the next nontest build with a higher version number? Or am I supposed to switch back to the stable version and wait for the code to get merged? Could I bump into any database version incompatibilities when manually switching from the newer test build back to the older stable version?

> I could use https://github.com/yamadapc/js-written-number which would give me a few languages, but the problem of detecting what language to use remains.

I think that a viable way to implement this would be to let the user specify the bibliography's language when creating an export. Then BBT could translate edition numbers to the desired language. But I'm not sure whether implementing this is actually worth it because people who have non-English bibliographies might already be using BibLaTeX due to its superior internationalisation support. Furthermore when I was testing non-English Natbib styles, one of them actually internally translated the English ordinal into the style's language. I think that the biggest issue is that the BibTeX documentation simply doesn't deal with non-English bibliographies at all and therefore every non-English Natbib style might do things in its own way.

IMO we could change the issue's title to 'English Edition Numbers in BibTeX Exports' and consider the issue resolved until somebody opens a ''Non-English Edition Numbers in BibTeX Exports' issue.

Sorry for the late reply and thanks for taking the time to deal with this.

**Comment by retorquere** [comment]
BBT will indeed automatically be upgraded to 5.2.18 somewhere in the next 24 hours, depending on how Zotero is configured. Your Zotero database is always safe (I don't write to it at all), in some test builds (but not this one) your BBT database could be modified incompatibly, but when that happens, and I'm not certain I will be releasing the same day, I just walk people through getting a backup of the BBT database before that happens. But in this case, neither database is affected, this is just a code change.

WRT having the user specify the language, I can only add checkboxes to the Zotero export window, so having the user pick a language would be a very awkward UI, and there are export where the user doesn't get an UI at all (drag and drop exports).

I'm fine with just going with what is in 6041 now. It's better than it used to be.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6108](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6108.xpi) ("Merge branch 'master' into gh-1446")

Install in Zotero by downloading [test build 5.2.18.6108](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6108.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I've moved this behavior to a preference in the next release.
