### ISSUE TITLE
Can't export volumeTitle from Juris-M

### ISSUE THREAD

**Issue by maras** [retorquere/zotero-better-bibtex#1447]
Hello.

First of all, thank you for such useful tool.

Problem is, that I can't  export  volumeTitle field from Juris-M with BBT BibLaTeX. Better JSON see that field:
```[
  {"id":"AleksaiteLietuviuteatroistorija2009","accessed":{"date-parts":[[2011,2,17]]},"archive":"NN","archive_location":"Kn. mugė","call-number":"4109 xy","editor":[{"family":"Aleksaitė","given":"Irena"}],"ISBN":"978-9955-868-18-7","issued":{"date-parts":[[2009]]},"language":"lt","note":"p; sud.; Kn.","number-of-pages":"583","publisher":"Gervelė","publisher-place":"Vilnius","source":"10","type":"book","title":"Lietuvių teatro istorija","title-short":"Lietuvių teatro istorija. Kn. 4","volume":"4","volume-title":"1980-1990"}
] 
```
My postscript line is ```if (this.item.volumeTitle) { this.add({ name: 'part', value: this.item.volumeTitle }); }``` It is similar to other lines, that is working perfectly. 
I changed volumeTitle formatting to volumetitle, volume-title, VolumeTitle, Volumetitle, Volume-Title and nothing works. Maybe I am doing something wrong?
**Report ID:**
MGBU7ZAC-euc
**Exporter used:**
Better BibLaTeX

Thank you once more.

**Comment by maras** [comment]
I understood my silly mistake: item type was manuscript, not book, so rule not worked.
Sorry for the noise and thank you for hard work.

**Comment by retorquere** [comment]
Glad you got it sorted.
