### ISSUE TITLE
Duplicate number field causes export error

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#1448]
Report-ID: DSEN33NB-euc

For some reason I cannot understand, Zotero + BBT is unable to export. I have not made any changes to the settings. The dialog states Error: Translation failed". 
<img width="799" alt="screenshot_242" src="https://user-images.githubusercontent.com/22581234/75711579-f0b69900-5cc6-11ea-8841-426769f4d967.png">

I noticed this has happened before, so I submitted a report. Hope this reveals further information.

Thanks for looking into this!

**Comment by retorquere** [comment]
Does `wilkinson-fair-2016` mean anything to you?

**Comment by jrennstich** [comment]
Yes. It’s a new entry I made.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.6036](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6036.xpi) ("fixes #1448")

Install in Zotero by downloading [test build 5.2.14.6036](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.6036.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jrennstich** [comment]
running it...

**Comment by retorquere** [comment]
Can you right-click that entry and send a debug report for it?

**Comment by jrennstich** [comment]
Working again. You're amazing! It's as zippy as before.

Presumably one of the 53 (!) authors who screwed things up with their name? Just a wild guess. 

Report ID: L8DQS5PW-euc

Thanks so much!

**Comment by jrennstich** [comment]
> Can you right-click that entry and send a debug report for it?

Report ID: DXBI5X9G-euc

**Comment by retorquere** [comment]
> Presumably one of the 53 (!) authors who screwed things up with their name? Just a wild guess.

No, this is squarely on me. I needed that reference so I can add it as a test case and prevent regression.

**Comment by jrennstich** [comment]
Ok - thanks for sorting this out so quickly!

**Comment by jrennstich** [comment]
Sorry, me again. I am afraid, the newly pushed version still produces that error. 5.2.14.6036 worked well, does not on my end.

Report ID: KWI5QXBN-euc

**Comment by retorquere** [comment]
The fix has not yet been deployed yet to a new release, I need to fix a few more and will then roll out.

**Comment by jrennstich** [comment]
Ah, sorry, I will just install `5.2.14.6036` then. Sorry again.

**Comment by retorquere** [comment]
No worries, I intend to release today, one of them is more thorny than I thought.

**Comment by retorquere** [comment]
Oh and you don't need to manually reinstall after you've installed a debug build. The release will be picked up automatically.

**Comment by retorquere** [comment]
Wait - I don't know why this was still based on .14? Looking into that.
