### ISSUE TITLE
tex.IDs= foo_bar are escaped despite the equals sign

### ISSUE THREAD

**Issue by muelli** [retorquere/zotero-better-bibtex#1449]
I have an item with an extra field "tex.IDs: foo_bar" and the exported BibLaTeX file shows the escaped underscore.

**Exporter used:**
BibLaTeX

**Expected behavior:**
The [documentation](http://retorque.re/zotero-better-bibtex/exporting/) states:

> The difference between lines with an = or an : is that the fields marked with = are considered to be valid (“raw”) latex and will be passed on into the generated files as-is. The lines marked with : are assumed to be plain-text and LaTeX special characters (such as the & above) will be escaped.

**Actual behavior:**

But using either `=` or `:` doesn't make a difference in the export, i.e. the underscore is always escaped.

**Comment by muelli** [comment]
8T5WJATY-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.16.6072](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.6072.xpi) ("Merge branch 'master' into gh-1449")

Install in Zotero by downloading [test build 5.2.16.6072](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.16.6072.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 6072?

As far as I can tell this bug was specific to `tex.ids` (which I treated specially since it is used in item merge). Any other field name should be unaffected.

**Comment by muelli** [comment]
yep, works much better. thanks :)

**Comment by retorquere** [comment]
Cool, thanks, rolling out a new release.

**Comment by mortang2410** [comment]
I don't know if this problem was fixed, but it seems to be broken again.

A minimal working example: mwe.bib
```
@Article{Titi_Gwiazda_conservation_entropy,
  author = {Claude Bardos and Piotr Gwiazda and Agnieszka Świerczewska-Gwiazda and Edriss S. Titi and Emil Wiedemann},
  title  = {Onsager's conjecture in bounded domains for the conservation of entropy and other companion laws},
  year   = {2019},
  eprint = {arXiv:1902.07120},
}

@Article{bardosOnsagerConjectureBounded2019,
  author        = {Bardos, Claude and Gwiazda, Piotr and Świerczewska-Gwiazda, Agnieszka and Titi, Edriss S. and Wiedemann, Emil},
  title         = {Onsager's Conjecture in Bounded Domains for the Conservation of Entropy and Other Companion Laws},
  year          = {2019},
  month         = feb,
  abstract      = {We show that weak solutions of general conservation laws in bounded domains conserve their generalized entropy, and other respective companion laws, if they possess a certain fractional differentiability of order 1/3 in the interior of the domain, and if the normal component of the corresponding fluxes tend to zero as one approaches the boundary. This extends various recent results of the authors.},
  archiveprefix = {arXiv},
  eprint        = {1902.07120},
  eprinttype    = {arxiv},
  keywords      = {Mathematics - Analysis of PDEs},
  primaryclass  = {math},
  url           = {http://arxiv.org/abs/1902.07120},
  urldate       = {2020-09-13},
}

```
If you try to import and merge these two entries (seen as duplicates), you will see a correct tex.ids in Zotero
![Captzgzxbdsure](https://user-images.githubusercontent.com/3200308/106111803-5abb0680-6101-11eb-90df-824ecebef4b0.JPG)
But the exported biblatex file will have escaped underscore.
![Captuzdhrazre](https://user-images.githubusercontent.com/3200308/106111951-86d68780-6101-11eb-89ad-cbc1f6b56ef8.JPG)

Everything I use is up-to-date.

**Comment by retorquere** [comment]
This is a different issue, please open a new ticket.
