### ISSUE TITLE
Correct way to export "language" to bibtex

### ISSUE THREAD

**Issue by stefanct** [retorquere/zotero-better-bibtex#1453]
This report is based on my problem described at [stackexchange](https://tex.stackexchange.com/q/527949/23277). If I understood [retorquere's comment](https://tex.stackexchange.com/questions/527949/babel-define-language-synonym-for-ieeetran?noredirect=1#comment1339682_527949) correctly, BBT handles Zotero's language field differently in the bibtex and bib**la**tex exports respectively:

 - in biblatex it is exported as `langid` and the value is transformed
 - in bibtex it is exported as `language` and the value is not touched but copied verbatim

I don't know what the *right* thing for bibtex would be (that's why I have not reported this problem in the first place - I am not sure if it is a good idea to change this behavior), **but** in my limited use case, that uses the non-standard IEEEtrans bibtex style, transforming the values of the language field would have improved my situation AFAICT (e.g., transforming `en` to `english`). I have not looked at the (biblatex) transformation rules to check if all the different language values I encountered in Zotero imports are handled by them though (so it is possible that it would not have helped me completely if the rules are "incomplete").

A quick search indicates that any package or style operating on `language` in the context of bibtex expects them to be valid `babel` languages... I assume this is what the transformation tries to produce for the biblatex export and thus I think that would make sense...

**Comment by retorquere** [comment]
Is there documentation on what are valid babel languages? I'm looking at section 1.24 from the babel manual, and that says

> [list of languages]
> There are more languages not listed above, including

which isn't a whole lot to go on

**Comment by stefanct** [comment]
There are two ways in babel to define languages:

> The first sections describe the traditional way of loading a language (with ldf files). The
> alternative way [is] based on ini files, which complements the previous one (it does not
> replace it).

Those from `.ini` files could easily be extracted by grepping for `name.babel` within https://github.com/latex3/babel/tree/master/locale (cf. 1.13 of babel.pdf)

The `.ldf` files seem to be distributed into the various language packages like https://ctan.org/tex-archive/macros/latex/contrib/babel-contrib/german

I guess since you only need the main names that the `.ini` files/locales are enough. They would also provide the language codes immediately in the directory name...

**Comment by retorquere** [comment]
This will sound silly, but I'm not deeply familiar with bibtex. What does Babel do in the citation toolchain? Is it the only package dealing with translations? I also see mention of polyglossia here and there.

**Comment by retorquere** [comment]
I'm looking at the babel mappings, and there seem to be conflicting mappings:

* both `grc` and `el` claim to be `ELL`
* both `grc` and `el` claim to be `greek`
* both `yue` and `zh` claim to be `ZHS`

**Comment by stefanct** [comment]
AFAICT switching hyphenation patterns is the (only?) relevant thing it provides that some styles take advantage of. I *think* use of polyglossia together with bibtex will probably be pretty low to non-existent (since polyglossia is not used with pdf(la)tex but lualatex etc).

Regarding the conflicts: I have not looked into the babel source but ell == el == gre is (modern) greek and gr**c** is ancient greek (which babel probably just maps to modern greek), see https://en.wikipedia.org/wiki/Greek_language.
No idea about the Chinese mapping really... but yue seems to be a variation spoken in the south of China while zh (or zho) is the overall code for Chinese.
Thus I don't think these are actual conflicts... is ELL and greek really different or just aliases?

**Comment by retorquere** [comment]
It's more that if I see `greek` in the language field, I don't know whether I should output `langid = {grc}` or `langid = {el}`. Same for `yue`/`zh`.

**Comment by retorquere** [comment]
I still need more input. I don't know how to decide the matter.

**Comment by stefanct** [comment]
No idea, why you closed this. If it's just because *I* did not reply: there was no reason to since I cannot help with the decision because I have no idea either. Depending on how the implementation works I would probably just use the first match and ignore "conflicts".

**Comment by retorquere** [comment]
I figured you lost interest - that happens pretty often. If you can't decide, I certainly can't, so then we're stuck.

Between those two language mappings there's no clear "first", so the outcome might be random. That seems undesirable.

**Comment by stefanct** [comment]
It's not random if it does not matter anyway for the end result ;)
But you are right insofar that I am not heavily invested into this issue since I have a workaround in place (that maps the few language IDs I expect to encounter with a few fixed rules).

**Comment by retorquere** [comment]
Doesn't it matter? `grc`/`el` yields the same output, and so do `yue`/`zh`?

**Comment by stefanct** [comment]
I don't know (or how to test that) but I had the impression that this might very well be the case if the mapping "in the other way" maps them to the same language.

**Comment by retorquere** [comment]
Ah, like that.

Could you find out how to test this? I'd rather not make undirected changes.
