### ISSUE TITLE
Missing unicode symbols for East European Names

### ISSUE THREAD

**Issue by jlaehne** [retorquere/zotero-better-bibtex#1455]
**Exporter used:**
Better BibTeX

**Expected behavior:**
The unicode symbols `ȩ` and `ḝ` should be translated into LaTeX code `\c{e}` and `\c{\u{e}}`.
Example: Stȩpniewski, Kḝstutis

**Actual behavior:**
Characters are currently not converted

**_Edit:_ Debug ID:**
R7MJF3ZA-euc

* Ȩ is Unicode 0228 should be `\c{E}`
* ȩ is Unicode 0229 should be `\c{e}`
* Ḝ is Unicode 1E1C should be `\c{\u{E}}`
* ḝ is Unicode 1E1D should be `\c{\u{e}}`

**Comment by jlaehne** [comment]
Debug ID added (see above)

**Comment by jlaehne** [comment]
ȩ is Unicode 0229 (capitalized 0228)
See: http://www.unicode.org/charts/PDF/U0180.pdf

ḝ is Unicode 1E1D (capitalized 1E1C)
See: http://www.unicode.org/charts/PDF/U1E00.pdf

**Comment by retorquere** [comment]
Does `{\c e}` do the same as `\c{e}`?

**Comment by jlaehne** [comment]
Yes, just checked.

Same for \c{\u{e}} and {\c{\u e}}, just the order of \c and \e matters in this case!

**Comment by retorquere** [comment]
Does it? What is the difference?

Sorry it took so long but I had to make some fairly extensive changes to the parser to support this.

**Comment by jlaehne** [comment]
Oh, I thought it will just be another character in some lookup list.

If you exchange `\c` and `\u`, the breve is not put on top, but before the character.

**Comment by retorquere** [comment]
It is just a lookup list but I do my best so that the output parses back into Zotero well too, and combined diacritics I hadn't dealt with yet.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6157](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6157.xpi) ("auto-balance tests")

Install in Zotero by downloading [test build 5.2.18.6157](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6157.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jlaehne** [comment]
I tried to install the test build, but Zotero claims it could not be installed, possibly due to an incompatibility to my Zotero version (5.2.18)!?

**Comment by retorquere** [comment]
What does `file zotero-better-bibtex-5.2.18.6157.xpi` say when you execute it in the commandline?

**Comment by jlaehne** [comment]
The commandline says `bash: ./zotero-better-bibtex-5.2.18.6157.xpi: cannot execute binary file: Exec format error`

I did a fresh download of the file and updated zotero to the very latest (5.0.84) to no avail.

**Comment by retorquere** [comment]
You can't run the plugin like this. I need to know whether the download succeeded; you can just type `file zotero-better-bibtex-5.2.18.6157.xpi`, verbatim, and it will tell you.

**Comment by jlaehne** [comment]
It says: zotero-better-bibtex-5.2.18.6157.xpi: Zip archive data, at least v2.0 to extract
(on the linux console)

**Comment by retorquere** [comment]
But 6157 does not? That's strange because it's only dropped here after all tests pass, and as part of the tests it is installed in Zotero.

**Comment by retorquere** [comment]
The size difference is correct BTW. It's shipping with a large (un)abbreviation list.

**Comment by jlaehne** [comment]
I thought the unabbreviation list was already part of 5.2.18, as it was released at the beginning of this week.

I have asked a colleague to test it as well, and otherwise I will try in the office on Monday - no chance on my laptop so far.

----- Original Message -----
> From: "Emiliano Heyns" <notifications@github.com>
> To: "retorquere/zotero-better-bibtex" <zotero-better-bibtex@noreply.github.com>
> Cc: "Jonas Lähnemann" <jonas@pdi-berlin.de>, "Author" <author@noreply.github.com>
> Sent: Freitag, 13. März 2020 22:50:37
> Subject: Re: [retorquere/zotero-better-bibtex] Missing unicode symbols for East European Names (#1455)

> The size difference is correct BTW. It's shipping with a large (un)abbreviation
> list.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/retorquere/zotero-better-bibtex/issues/1455#issuecomment-598926657

-- 
__________________________________________________________________________
        _  _
       | ||_|  |  Jonas Lähnemann
  _  _ | | _   |  Paul-Drude-Institut für Festkörperelektronik
 | || || || |  |  Semiconductor Spectroscopy Department
 | || || || |  |  Hausvogteiplatz 5-7, 10117 Berlin, Germany
 | ||_||_||_|  |  E-mail: laehnemann@pdi-berlin.de
 | |           |  Tel: +49 (0) 30 20377-450 (office)
 |_|           |                       -463 (lab)
__________________________________________________________________________

**Comment by retorquere** [comment]
> I thought the unabbreviation list was already part of 5.2.18, as it was released at the beginning of this week. 

That is a good point. I'll look into it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6169](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6169.xpi) ("Merge branch 'master' into gh-1455")

Install in Zotero by downloading [test build 5.2.18.6169](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6169.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
The problem wasn't in the packaging but in the upload. I had missed it because the releases get uploaded by another script in the tests.

**Comment by jlaehne** [comment]
Over the whole movement to home-office, I lost track that I already checked this on Monday and forgot to post that it works like a charm. Thanks!

**Comment by retorquere** [comment]
NP, everyone's life is going to be hectic for a while. My own calendar has absolutely exploded. Thanks for the feedback, it's been merged, I have two more fixes lined up and then I'll cut a release. You can keep this and you'll be upgraded to the real release automatically.
