### ISSUE TITLE
Cannot import notes that were exported with BetterBibTeX JSON

### ISSUE THREAD

**Issue by hartmut1s** [retorquere/zotero-better-bibtex#1456]
[JavaScript Error: "Error: undefined: unexpected note.attachments for zotero in {"itemType":"note","note":"<p>Wenn nicht anders angegeben, habe ich mich bei der Gliederung an <em>Introduction to Global Missions</em>, Zane Pratt, M. David Sills, Jeff K. Walters angelehnt bzw. weitgehend übernommen</p>\n<p> </p>","tags":[{"tag":"remove note"}],"dateAdded":"2020-01-21T09:53:25Z","dateModified":"2020-01-21T14:32:59Z","itemID":651,"attachments":[],"notes":[]} / {"dateAdded":true,"dateModified":true,"id":true,"itemID":true,"itemType":true,"note":true,"tags":true}" {file: "chrome://zotero/content/xpcom/translation/translate_firefox.js line 425 > eval" line: 1676}]

**Comment by hartmut1s** [comment]
debug ID: XRWA6VIT-euc

![importing hangs](https://user-images.githubusercontent.com/8261898/76326578-1fe19180-62e9-11ea-94f2-2cc22f137af3.jpg)

**Comment by retorquere** [comment]
Can you attach the file you're trying to import here? You may have to rename it to `.txt` to get github to allow it to be attached.

**Comment by hartmut1s** [comment]
Here is the link to the JSON file:
https://www.dropbox.com/s/d54at4zu532bgly/Weltmission%20erster%20Punkt%20-%2006-03-2020.json?dl=0

[Weltmission erster Punkt - 06-03-2020.zip](https://github.com/retorquere/zotero-better-bibtex/files/4314691/Weltmission.erster.Punkt.-.06-03-2020.zip)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6153](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6153.xpi) ("don't initialize notes & attachments for notes & attachments")

Install in Zotero by downloading [test build 5.2.18.6153](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6153.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
The files generated by the current release have unexpected fields on notes. If you have existing files, you can remove the `notes` and `attachment` arrays from items with itemType `note` or `attachment`. Build 6153 will generate files that can be imported back in without manual editing. If you can verify this fixes the problem for you, I can merge it into a release.

**Comment by hartmut1s** [comment]
When I try to download [test build 5.2.18.6153](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6153.xpi), I get the error "page not found." Can you please verify the link?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6182](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6182.xpi) ("Merge branch 'master' into gh-1456")

Install in Zotero by downloading [test build 5.2.18.6182](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6182.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by hartmut1s** [comment]
Report ID: U5Q6GQB6-euc
Debug ID D886575919
[Debug ID D886575919.zip](https://github.com/retorquere/zotero-better-bibtex/files/4338066/Debug.ID.D886575919.zip)

Steps to reproduce:
- export references and at least one standalone note (use the BetterBibTeX JSON format and check export notes and export files in Translator Options)
- try to import this JSON file into a different category

LINK to JSON file:
https://www.dropbox.com/s/v5a27bp3pyaqt66/Weltmission%20-%2016-03-2020.zip?dl=0

Expected behavior:
I will see all the references and the standalone note


Actually, I was only able to import the references. The standalone note didn't make it. The import process didn't finish. I had to manually stop the process.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6187](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6187.xpi) ("pop version for tests")

Install in Zotero by downloading [test build 5.2.18.6187](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6187.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you export again with 6187?

**Comment by hartmut1s** [comment]
Report ID: 5I5YZHT7-euc
The import of the standalone note still hangs. I have to manually stop the process. Importing the references is okay like before.

Here is the JSON file.
[Die Missiologische Grundlage der Bibel - 16-03-2020 evening.zip](https://github.com/retorquere/zotero-better-bibtex/files/4339646/Die.Missiologische.Grundlage.der.Bibel.-.16-03-2020.evening.zip)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6191](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6191.xpi) ("explicitly strip them")

Install in Zotero by downloading [test build 5.2.18.6191](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6191.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by hartmut1s** [comment]
Can you please explain what I am supposed to do when you wrote to "explicitly strip them"?

**Comment by retorquere** [comment]
Nothing - that message is just my commit message. The commit that led to this build explicitly strips the extra fields - I don't know why you're seeing this when I'm not, but I hope me explicitly stripping those fields fixes it for you.

That zotero hangs when an import fails is not something I can fix - that's just how zotero reacts when any import, bbt or not, fails. You might want to report that to zotero come to think of it, but zotero severely restricts (for good reason) what translators can do.

**Comment by hartmut1s** [comment]
Success! The import of references and a standalone file worked. This is great.
[import complete.zip](https://github.com/retorquere/zotero-better-bibtex/files/4342269/import.complete.zip)

**Comment by retorquere** [comment]
Superb. Integration tests are running.
