### ISSUE TITLE
Import hangs without completing

### ISSUE THREAD

**Issue by jsta** [retorquere/zotero-better-bibtex#1458]
I am having what seems like a new issue importing references (either with vanilla bib import or import-from-clipboard) where Zotero hangs and does not complete the import. I am on Zotero 5.0.60 and BBT is updated through March 6, 2020. It does not appear to be related to the size of the import because I get hanging with importing only a single reference.

**Comment by jsta** [comment]
The debug ID is: EVMXFZNE-euc

**Comment by retorquere** [comment]
Can you go into the [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences) and turn off `importJabRefAbbreviations` and `importJabRefStrings`?

**Comment by retorquere** [comment]
I can see the error in the log but I can't replicate it, at least not on the current Zotero. In principle I only support the latest Zotero version, which is 5.0.84. If it works in 5.0.84 but not in 5.0.60, I'm afraid you'll have to upgrade. Turning off the preferences above disables the part that errors out for you.

**Comment by jsta** [comment]
It works with those hidden preferences turned off :tada:

**Comment by retorquere** [comment]
Then I'm going to consider this addressed. If it recurs on the latest Zotero, feel free to reopen. I'd strongly suggest upgrading zotero btw.
