### ISSUE TITLE
After import, all standalone notes are lumped together in the first collection

### ISSUE THREAD

**Issue by hartmut1s** [retorquere/zotero-better-bibtex#1463]
**Report ID:** LJFMZF79-euc

**Full Bib(La)TeX item you are trying to import:**
[Mission und internationale Zusammenarbeit.zip](https://github.com/retorquere/zotero-better-bibtex/files/4355743/Mission.und.internationale.Zusammenarbeit.zip)

I exported a collection with all subcollections, references and standalone notes. 

**Expected behavior:**
After the import, I expected to see all standalone notes linked to their respective collection.

**Actual behavior:**
After the import, all independent notes are no longer linked to their respective collection but they are lumped together in the first collection.

Collection with standalone note (original setup)
![Collection with standalone note (original)](https://user-images.githubusercontent.com/8261898/77091384-c3792300-6a08-11ea-8d94-b3e2d8ebfa9c.jpg)

Collection without standalone note (after import)
![Collection without standalone note (after import)](https://user-images.githubusercontent.com/8261898/77091436-d986e380-6a08-11ea-85b7-c02dc32b9ccc.jpg)

All standalone notes lumped together in first collection (after import)
![All standalone notes lumped together in first collection (after import)](https://user-images.githubusercontent.com/8261898/77091470-e60b3c00-6a08-11ea-95f7-a48cc2bc0c29.jpg)

**Comment by retorquere** [comment]
This seems to be a more general Zotero problem. If I recreate the original, export to Zotero RDF, and import it back, the notes don't appear in the subcollections either. So it looks like just generally adding notes to collections from translators is currently broken in Zotero.

**Comment by hartmut1s** [comment]
Thank you for your explanation and feedback. I will post this problem in the respective forum of Zotero.
