### ISSUE TITLE
LaTeX field tex.author+an not being exported

### ISSUE THREAD

**Issue by gncs** [retorquere/zotero-better-bibtex#1464]
**Report ID:** WVMY4289-euc

**Exporter used:** Better BibLatex

**Expected behavior:** Additional information, given as "tex.author+an= 2=highlight" in the extra field should show up as "author+an= 2=highlight" in the exported bibliography file.

**Actual behavior:** "author+an= 2=highlight" does not show up in the bib file. This works for "author_an= 2=highlight", though. I am suspecting it has something to do with the plus sign?

**Comment by retorquere** [comment]
Your `skip fields` is set to 

```
author+an,abstract,file,keywords,timestamp,urldate,copyright,issn,month,language,shorttitle,langid,acmid,issue_date
```

**Comment by gncs** [comment]
Sorry, I completely missed that. Thank you for the feedback.
