### ISSUE TITLE
Overline export error

### ISSUE THREAD

**Issue by jlaehne** [retorquere/zotero-better-bibtex#1465]
I played with a lot of entries that have an overline on numbers, they are quite differently imported into Zotero, but I guess that is a problem of how the journals give away the metadata. Still, I found several cases where wrong or even not translatable LaTeX was written by BBT.

**Report ID:**
W94VSSEY-euc

**Exporter used:**
BetterBibTeX

**Summary of behaviors during Export:**

The TeX command is put behind the number, even if the overline applies to the number before. There is two different types of overlines occuring, but both are misplaced:

Short overline:
- `(112̄2)`  is exported as `(112\=2)`, but should be `(11\=22)`
- `(0001̄)` is exported as `(0001\=)`, but should be `(000\=1)`

Long overline:
- `(0001̅)` is exported as `(0001{$\overline$})`, which does not even translate! Correct would be `(000{$\overline{1}$})`

**Edit:** Originally included import errors split off as: #1467 and #1468 and the export error in #1469

**Comment by retorquere** [comment]
I've found the problem on point 1; it will take a bit of time as I need to clean up something else for the fix, but I expect it to be done over the weekend.

Point 2 is an entirely different matter though; I'd prefer to handle that in a separate issue. But if it's just math sections, you might be helped with https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas.

**Comment by retorquere** [comment]
Wait, that's not right. Point 1 also deals with two separate issues (both correctly identified as problems); one is export, one is import. I'd prefer to deal with those separately too. But I have a solution in mind for 1.import, and for 1.export, I think I have one too.

**Comment by jlaehne** [comment]
Sorry for posting too many different issues together, I was evaluating them together and some just turned up on the way. So I'll open a separate issue for the import.

Point 2 is solved by adding `<script>` commands, but that makes the title in Zotero even more lengthy and I was hoping that an automatic detection might be possible (e.g. a pair of `$` signs and at least one `\` in between them should be unlikely to appear in another context). Let me know if you think it feasible to have such an automatic detection, then I could open an extra issue.

No hurry on these issues, I just stumbled across them a while ago and finally had the time to evaluate them a bit more systematically.

**Comment by retorquere** [comment]
That's the thing -- if it is always math sections you're interested in, a postscript can be used to add the script tags on the fly during export, no need to add them manually or even see them in Zotero.

**Comment by jlaehne** [comment]
OK, works great. Thanks.

**Comment by retorquere** [comment]
Do the other two issues cover the remaining questions raised here?

**Comment by jlaehne** [comment]
Yes, I split them off for clarity as you said it is separate issues.

**Comment by retorquere** [comment]
Cool, appreciated, but I didn't want to close the issue until that was certain.

**Comment by jlaehne** [comment]
Oh sorry, misunderstanding. I left the export part in here. Sorry. Should I also make another separate issue for clarity?

**Comment by retorquere** [comment]
No, not necessary, but if you could edit the top message to restrict it to the remaining question that'd be helpful.

**Comment by jlaehne** [comment]
Done, I broke it down and added another separate export issue. I guess I was too tired yesterday to do it properly.

**Comment by retorquere** [comment]
OK so what's in the edited first message is now the actual issue for #1456?

**Comment by jlaehne** [comment]
Yes

**Comment by retorquere** [comment]
A few of the items in `W94VSSEY-euc` have latex code in the titles BTW.

**Comment by retorquere** [comment]
If I clear out the ones with LaTeX in the titles I have 8 entries:

```
Leung, B., Sun, Q., Yerino, C., Zhang, Y., Han, J., Hyun Kong, B., Koun Cho, H., Liao, K.-Y., & Li, Y.-L. (2012). Growth evolution and microstructural characterization of semipolar (112̄2) GaN selectively grown on etched r-plane sapphire. Journal of Crystal Growth, 341(1), 27–33. https://doi.org/10.1016/j.jcrysgro.2011.12.035
Monavarian, M., Rashidi, A., Aragon, A., Oh, S. H., Nami, M., DenBaars, S. P., & Feezell, D. (2017). Explanation of low efficiency droop in semipolar (202¯1¯) InGaN/GaN LEDs through evaluation of carrier recombination coefficients. Optics Express, 25(16), 19343. https://doi.org/10.1364/OE.25.019343
Niehle, M., Trampert, A., Albert, S., Bengoechea-Encabo, A., & Calleja, E. (2015). Electron tomography of (In,Ga)N insertions in GaN nanocolumns grown on semi-polar (112̄2) GaN templates. APL Materials, 3(3), 036102. https://doi.org/10.1063/1.4914102
Romanyuk, O., Jiříček, P., Paskova, T., & Bartoš, I. (2014). Polarity of semipolar wurtzite crystals: X-ray photoelectron diffraction from GaN{101¯1} and GaN{202¯1} surfaces. Journal of Applied Physics, 116(10), 104909. https://doi.org/10.1063/1.4894708
Song, J., Chang, S.-P., Zhang, C., Hsu, T.-C., & Han, J. (2015). Significantly improved luminescence properties of nitrogen-polar (0001̅) InGaN multiple quantum wells grown by pulsed metalorganic chemical vapor deposition. ACS Applied Materials & Interfaces, 7(1), 273–278. https://doi.org/10.1021/am506162z
Song, J., Yuan, G., Xiong, K., Leung, B., & Han, J. (2014). Epitaxial lateral overgrowth of nitrogen-polar (0001̅) GaN by metalorganic chemical vapor deposition. Crystal Growth & Design, 14(5), 2510–2515. https://doi.org/10.1021/cg500229r
Zhang, Z., Zheng, K., Lu, Z.-Y., Chen, P.-P., Lu, W., & Zou, J. (2015). Catalyst Orientation-Induced Growth of Defect-Free Zinc-Blende Structured ⟨001̅⟩ InAs Nanowires. Nano Letters, 15(2), 876–882. https://doi.org/10.1021/nl503556a
Zywietz, T., Neugebauer, J., & Scheffler, M. (1998). Adatom diffusion at GaN (0001) and (0001̄) surfaces. Applied Physics Letters, 73(4), 487–489. https://doi.org/10.1063/1.121909
```

**Comment by retorquere** [comment]
I'd prefer it if you could get me a new debug report with the items that exhibit the problem, but cleaned up so that they look good in Zotero -- right now the exported bibtex looks wonky, but that's because the input in Zotero is wonky. Perhaps an import made with #1467, but please do check the results.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6223](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6223.xpi) ("fixes #1468")

Install in Zotero by downloading [test build 5.2.18.6223](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6223.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jlaehne** [comment]
Sorry, it was the full file I played with to identify the problems and get an overview how it is imported from the journals.

You still need a new debug report? All the issues seem to have been solved with your new builds. Using `5.2.18.6224`, everything exports correctly, works in a test LaTeX file without errors, and reimports correctly!

Thanks.

**Comment by retorquere** [comment]
Oh if those cover this request, then we can close it

**Comment by jlaehne** [comment]
Yep, `\overline` and `\=` are at the right position now.

**Comment by retorquere** [comment]
Cool, thanks for reporting this, and for the verification.

Took a fairly large change to the parser but in the end it cleaned up a lot of old stuff.
