### ISSUE TITLE
Overline during Import

### ISSUE THREAD

**Issue by jlaehne** [retorquere/zotero-better-bibtex#1467]
**Report ID:**
W94VSSEY-euc

**Exporter used:**
BetterBibTeX

**Summary of behavior:**
- `(000\=1)` is correctly imported as `(0001̄)`
- `(000\overline{1})`, however is imported as `(000̅1)`, so the line is placed over the number before
- `(000{$\bar{1}$})`, is imported as `(000̄1)`, so the same error

**Comment by retorquere** [comment]
Can you get me a full sample bib file that includes these?

**Comment by jlaehne** [comment]
Here is a bib file with several examples for each of the three cases (just renamed the ending so that it would upload):
[bar-import.txt](https://github.com/retorquere/zotero-better-bibtex/files/4364418/bar-import.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6219](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6219.xpi) ("fixes #1467")

Install in Zotero by downloading [test build 5.2.18.6219](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6219.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jlaehne** [comment]
The import looks good! Works fine now.

You closed the export issue #1465, but that still puts the `\overline` and `\=` in the wrong place.
