### ISSUE TITLE
Import of \langle and \rangle TeX commands

### ISSUE THREAD

**Issue by jlaehne** [retorquere/zotero-better-bibtex#1468]
**Report ID:**
W94VSSEY-euc

**Exporter used:**
BetterBibTeX

**Summary of behavior:**
- `$\langle{}001\rangle$`, is imported as `〈001〉`, while before export it was `⟨001⟩`. So it uses a different Unicode symbol for `\langle` and `\rangle` on import than on the export, which is not displayed correctly (at least on my system).

**Comment by jlaehne** [comment]
Sample bib file (though 
[bar-angle.txt](https://github.com/retorquere/zotero-better-bibtex/files/4364423/bar-angle.txt)
with txt ending):

**Comment by retorquere** [comment]
I'm having a little trouble interpreting the question... you're saying that on import, `\langle` is imported as `U+3008` (which it does), but then I don't follow anymore. You say

> before export it was `⟨001⟩`

and there the left angle bracket is `U+27E8` but I don't understand how it got there if you say that the import made it `U+3008`. Why was it `U+27E8` before export? And `U+27E8` will indeed export to `\langle` (as will `U+3008`).

**Comment by retorquere** [comment]
`bar-angle.bib` seems to be malformed -- the second `$` is in a different brace-grouping than the first.

**Comment by retorquere** [comment]
`bar-angle.bib` was generated by BBT?!?!

**Comment by retorquere** [comment]
Oh wait -- do you mean that rather than outputting `\langle`, it outputs `U+27E8`?

**Comment by jlaehne** [comment]
I had corrected the bib file manually and overlooked the extra brace-group. This is the corrected file:
[bar-angle.txt](https://github.com/retorquere/zotero-better-bibtex/files/4366102/bar-angle.txt)

The issue is that `U+27E8` exports as `\langle`, 
but `\angle` imports as `U+3008`, which is less common.

See e.g. https://mirrors.ibiblio.org/CTAN/macros/latex/contrib/unicode-math/unimath-symbols.pdf

`U+27E8` is the `mathematical left angle bracket` (https://unicode.org/cldr/utility/character.jsp?a=27E8), which I think would be the correct one here.

**Comment by retorquere** [comment]
Gotcha

**Comment by retorquere** [comment]
(the ibiblio link doesn't work for me BTW)

**Comment by jlaehne** [comment]
I sneaked an https in the link, but it is only available via http

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6222](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6222.xpi) ("fixes #1468")

Install in Zotero by downloading [test build 5.2.18.6222](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6222.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6223](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6223.xpi) ("fixes #1468")

Install in Zotero by downloading [test build 5.2.18.6223](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6223.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jlaehne** [comment]
tested, LGTM
