### ISSUE TITLE
Missing $ in TeX export of ⟨ to \langle

### ISSUE THREAD

**Issue by jlaehne** [retorquere/zotero-better-bibtex#1469]
**Report ID:**
W94VSSEY-euc

**Exporter used:**
BetterBibTeX

**Summary of behaviors during Export:**
`⟨001̅⟩` is exported as `\langle{}001{$\overline\rangle$}`, which is not translating. `\langle` is missing the `$` signs for a math environment on top of the problem with the overline mentioned in #1465. Correct would be `$\langle{}00\overline{1}\rangle$` or `$\langle{}$00$\overline{1}\rangle$`

There is also an issue with the reimport, discussed in #1468.

**Comment by retorquere** [comment]
Or is it just that the `$` signs are missing? I've found the problem that caused that.

**Comment by jlaehne** [comment]
Yes, this one is just about the missing `$`

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6224](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6224.xpi) ("fixes #1469")

Install in Zotero by downloading [test build 5.2.18.6224](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6224.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jlaehne** [comment]
tested, LGTM
