### ISSUE TITLE
Option for BBT-generated citation key to use the Zotero-generated abbreviation even when Zotero's Journal Abbr field is not empty

### ISSUE THREAD

**Issue by pou2** [retorquere/zotero-better-bibtex#1470]
Hi there. I believe I may have seen something to this effect when looking through the repo issues (e.g., #604), at least in the context of import/export. My main interest is being able to use a reliably consistent journal abbreviation value for the citation key generator. The problem is that publishers are inconsistent about metadata for this field (e.g., the journal full title is often resupplied as the abbreviation). Would it be possible to optionally make BBT act as though the Zotero journal abbreviation field is empty (e.g., with a function or filter)?

[I posted about this on the Zotero forums](https://forums.zotero.org/discussion/82029/automatically-clear-out-the-journal-abbreviation-field) where it was suggested that I might check here as well; in that post I noted that a workaround is probably possible for me by using the Zotero javascript API to clear the journal abberviation field—so if this sort of a BBT option isn't feasible, I should still be able to get what I'm looking for. But maybe this customization would be valued by others as well?

Either way, thanks for your time and work.

**Comment by pou2** [comment]
Obviously this is not a bug. I did not realize that it would be auto-labeled as such (or overlooked any specified default label when posting the issue), and I'm not sure how to apply the correct "enhancement" label.

**Comment by retorquere** [comment]
No worries - you get prompted for the issue type when you're logged into github, if not it defaults to `bug`.

I'd still need a debug report as per point 1.

**Comment by pou2** [comment]
Thanks for the swift reply, and thanks for looking into this.

The report ID is GDB6H7QJ-euc

The [example reference](https://www-sciencedirect-com.echo.louisville.edu/science/article/pii/S0006291X07018402) was imported to Zotero via a browser connector. This particular journal supplies its full title for the journal abbreviation metadata field. Consequently, the cite key generated from my format rules is 2007_Wada_BiochemicalandBiophysicalResearchCommunications_1, whereas the desired cite key obtained once the journal abbreviation field is cleared in Zotero is 2007_Wada_BiochemBiophysResCommun_1.

Although I'm sure you'll have no problem looking through my format rules, just in case it helps at all: only the first or second rules are relevant. The second rule is slightly more straightforward, so I've provided it here:

    [=journalArticle][year:postfix=_][authorLast:nopunctordash:postfix=_][journal:nopunctordash:postfix=_][Pages:clean:replace=-,\ :select=1,1]

Of course, the specific part in question is:

    [journal:nopunctordash:postfix=_]

Let me know if there's anything else I can do.

**Comment by retorquere** [comment]
Not currently -- a couple of issues were reported over the past few days, and I'm working through them, I'll likely get to this one tomorrow, and then I'll likely need more info.

**Comment by retorquere** [comment]
Hmm, I don't know. Wouldn't an option in Zotero so you can easily clear out the abbrev (right-click, clear abbrev) for multiple items be a better solution? That way all translators and bibliography production would benefit.

**Comment by pou2** [comment]
Yes, I think that this approach could work for me if you think it's the appropriate way to go. It would be better than what I do now.

Like I said, I may look into trying to use the Zotero javascript API to do this automatically, since a fully automatic solution would be the nicest.

My situation is that I use the cite key as an abbreviated citation when I take notes and as the file name for the associated PDF. I import a lot of articles into Zotero that never end up being cited in a formal publication but often end up being referenced in notes I make at the time. Also, I use [rafaqz's citation.vim](https://github.com/rafaqz/citation.vim); I'm not saying I expect this to be supported, but I bring it up as an example of why it is ideal for me to have the cite key to be automatically in its final state, since, e.g., citation.vim allows one to pull up the pdf directly from a cite key in a notes document in vim, and this would not work consistently if a bad citation key was autogenerated and then fixed after having already been inserted into a notes document. Regarding citations that end up in a formal publication, this always ends up being a manageably small set of references that I will end up carefully checking over anyway, so I won't be relying on anything to be automatically perfect at that stage anyway.

Ultimately, I recognize that I can get by with the way things are, and I am grateful for how much BBT helps with the way I do things already, so it's no problem if this idea can't be implemented. Beggars can't be choosers. I also recognize that my choice of citation key style may be totally idiosyncratic and that it is within my power to do something different (I am just very attached to way I'm trying to do it now). 

That being said, if I were to make a case as to why you might decide this feature could be valuable in BBT, here's what I'd say:

1. It is presumably a goal for cite key autogeneration to be as reliable as possible.
2. The very nice "fancy" options are already made available, so it would be ideal if they aligned with the primary goal of reliability to the greatest extent that is reasonably possible. (I'm glad to have these options even as they are of course; it's much better than not having them at all.)
3. The 'journal' function is (a) maybe the most prone to suffering from unreliable metadata and (b) already has functionality developed for it that could completely fix this problem. I love the ability to use the Zotero abbreviation autogeneration, and enabling the possibility to force its use provides a way for the function to be much more reliable if a user cares about that.
4. The journal is very useful to incorporate into the citation key, especially in some disciplines where publications are more frequent and you might be citing 5 papers from the same author in the same year.

I'm totally cool with whatever you decide. Thanks again.

**Comment by retorquere** [comment]
> Yes, I think that this approach could work for me if you think it's the appropriate way to go. It would be better than what I do now.
>
> Like I said, I may look into trying to use the Zotero javascript API to do this automatically, since a fully automatic solution would be the nicest.

I could probably whip up a plugin that just adds this to the Zotero context menu tomorrow.
 
> My situation is that I use the cite key as an abbreviated citation when I take notes and as the file name for the associated PDF. I import a lot of articles into Zotero that never end up being cited in a formal publication but often end up being referenced in notes I make at the time. Also, I use [rafaqz's citation.vim](https://github.com/rafaqz/citation.vim); I'm not saying I expect this to be supported, 

I'm not sure in what way it would be supported?

> Ultimately, I recognize that I can get by with the way things are, and I am grateful for how much BBT helps with the way I do things already, so it's no problem if this idea can't be implemented. Beggars can't be choosers. I also recognize that my choice of citation key style may be totally idiosyncratic and that it is within my power to do something different (I am just very attached to way I'm trying to do it now).

Your choice of citation key style is not odd to me in the sense that it is just one of the ways I expected people to use citekey formatting.

> That being said, if I were to make a case as to why you might decide this feature could be valuable in BBT, here's what I'd say:
> 
>     1. It is presumably a goal for cite key autogeneration to be as reliable as possible.

Yes, but this is a matter of interpretation. To me, reliable means that it reliably does what you tell it to. If you use `[journal]` in your pattern, I would expect that to reliably perform the documented behavior: use abbrev if available, publication title if not. I agree that it's odd that `[journal]` does this but I copied this behavior from JabRef, and reliable also means that I can't just change behavior years down the line. I'd be OK with adding `[journal:full]` that would just not use at the abbrev if set.

>     2. The very nice "fancy" options are already made available, so it would be ideal if they aligned with the primary goal of reliability to the greatest extent that is reasonably possible. (I'm glad to have these options even as they are of course; it's much better than not having them at all.)

I don't see them as currently out of alignment. Consistency across time is an important form of reliability from my POV. I would find it pretty shocking if I found keys suddenly changed after a BBT upgrade when I changed nothing in Zotero.

>     3. The 'journal' function is (a) maybe the most prone to suffering from unreliable metadata and (b) already has functionality developed for it that could completely fix this problem. I love the ability to use the Zotero abbreviation autogeneration, and enabling the possibility to force its use provides a way for the function to be much more reliable if a user cares about that.

That the abbrev field is often filled with inappropriate data is a wider Zotero problem. There is absolutely no way to tell how data got into that field; I can't see whether it came from an import, or that the user typed it in. Given that, I don't see it as BBTs work to second-guess user input.

>     4. The journal is very useful to incorporate into the citation key, especially in some disciplines where publications are more frequent and you might be citing 5 papers from the same author in the same year.

But that would be solved with `[journal:full]` (or something else we deem better expresses what we want) without interrupting existing behavior.

**Comment by pou2** [comment]
> I could probably whip up a plugin that just adds this to the Zotero context menu tomorrow.

If you did, then that'd be awesome and I'd put it to use.

> I'm not sure in what way it would be supported?

I guess what I meant was something like "I don't expect my particular workflow/use-case to be supported, particularly when it involves some additional customization"; there was probably some vague thinking at the back of my head about "I shouldn't be asking this dev to stress out about some other project that isn't their focus", too, but there isn't anything that I'm aware of in citation.vim that BBT doesn't work well with. Sorry for being confusing.

> Yes, but this is a matter of interpretation. To me, reliable means that it reliably does what you tell it to, and that this behavior is stable over time. If you use `[journal]` in your pattern, I would expect that to reliably perform the documented behavior: use abbrev if available, publication title if not. I agree that it's odd that `[journal]` does this but I copied this behavior from JabRef, and reliable also means that I can't just change behavior years down the line. I'd be OK with adding `[journal:full]` that would just not use at the abbrev if set.

Although I was trying to imagine things from your perspective to 'make the case', I'm not surprised that I was imperceptive about this; your interpretation sounds reasonable.

[journal:full] sounds like it would be a great solution for my situation.

> I don't see them as currently out of alignment. Consistency across time is an important form of reliability from my POV. I would find it pretty shocking if I found keys suddenly changed after a BBT upgrade when I changed nothing in Zotero.

I think your POV makes sense, so I was mistaken in my line of reasoning.

> That the abbrev field is often filled with inappropriate data is a wider Zotero problem. There is absolutely no way to tell how data got into that field; I can't see whether it came from an import, or that the user typed it in. Given that, I don't see it as BBTs work to second-guess user input.

That makes sense; I can see it that way.

> But that would be solved with `[journal:full]` (or something else we deem better expresses what we want) without interrupting existing behavior.

Yes, that sounds like a good solution.

If you're looking for my thoughts on the choice for the filter name, I don't know if "full" brings to mind what I am looking for, personally. If the journal is, e.g., Biochemical Pharmacology, then "full" makes me think I might get something like 2008_Turner_BiochemicalPharmacology_781 when what I really want from using [whatever this filter ends up being named] is 2008_Turner_BiochemPharmacol_781 instead (but I might be thinking about it the wrong way and don't know your implementation plans).

If it is implemented as a filter, I guess you would want it to be something that could be applied to any field or function. I sense you may have a reason for not wanting to implement it as a function (e.g., to maintain consistency with JabRef or something like that); if I'm mistaken about that, though, maybe something like `[journabbr]` or `[jabbr]` or `[journalabbr]` or `[abbrjourn]` or `[zoterojournabbr]`, etc., would work well.

Actually, rereading the description of `[journal]` in the docs ("...If ‘automatic journal abbreviation’ is enabled in the BBT settings, it will use the same abbreviation filter Zotero uses in the wordprocessor integration...") makes me think that something like `[autojournabbr]` or `[zoteroautojourn]` might be a good fit.

If it really ought to be implemented as a filter, then maybe something like `[journal:zoterojournabbr]` or `[journal:zoterojournabbr]` would be good. I don't know how Zotero's abbreviation filter works, but maybe it could be something that someone would want to apply to text other than the journal title.

Obviously I have no problem with however things are implemented or named; I'm fine with whatever and am just trying to be useful.

**Comment by retorquere** [comment]
Ah right good point. No, a filter wouldn't be appropriate because filters can only act on what they're passed, they can't "undo" stuff that happened before they were called. So something like `journal.full` could do the job, because that would just be different pattern. In retrospect I regret just copying jabref's behavior without removing warts like this, but I can't fix that now.

Given that `journal` already has existing behavior that it will use the auto-abbreviated journal name, `autojournabbr` as proposed would just be an alias for `journal`. As I'm not willing to change the behavior of `journal` (because that would affect existing users), `autojournabbr` wouldn't help with your use-case.

I'll get you the other plugin tonight. I have a scaffolding tool that makes it easy to generate Zotero plugins.

**Comment by retorquere** [comment]
> Although I was trying to imagine things from your perspective to 'make the case', I'm not surprised that I was imperceptive about this; your interpretation sounds reasonable.

I can't take full credit for this interpretation; I essentially cribbed it from Dworkin.

**Comment by retorquere** [comment]
I'm an idiot. Try `[Journal]` or `[PublicationTitle]`.

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-clear-journal-abbrev/

**Comment by pou2** [comment]
Awesome, THANK YOU SO MUCH; I really appreciate it!

**Comment by retorquere** [comment]
You're welcome. 

`[PublicationTitle]` will give you the journal name (if it has one), and not look at the abbreviation at all.

**Comment by pou2** [comment]
My problem is pretty much completely addressed by the plugin that you just made, so I'm perfectly happy.

In case you'd still like to have my feedback on the other parts, however, here you go.

---

I checked the behavior with `PublicationTitle`...

Behavior with original setup (`[=journalArticle][year:postfix=_][authorLast:nopunctordash:postfix=_][journal:nopunctordash:postfix=_][Pages:clean:replace=-,\ :select=1,1]`):
2015_Gao_TrendsinMicrobiology_468

Actually desired behavior (achieved by clearing out the bad metadata):
2015_Gao_TrendsMicrobiol_468

Behavior with `...[PublicationTitle:nopunctordash:postfix=_]...`:
2015_Gao_TrendsinMicrobiology_468

I have a feeling that I may have miscommunicated what I was looking for on the filter/function thing. For example, the provisional name for the filter you suggested was "full", and you have pointed out that PublicationTitle would also give the full value. What I meant to ask for originally was not the full journal title, but rather the Zotero abbreviation of the full journal title. `[journal]` does this for me, and that's why your new plugin solved my problem. The issue with `[journal]` was that the contents of Zotero's Journal Abbr field would take precedence over the Zotero abbreviation of the full journal title (and I agree that is the way `[journal]` should be implemented).

Maybe something like `[PublicationTitle:zoterojournabbr]` better conveys what I was looking for.

But again, I am perfectly happy with my situation now, and you don't have to worry about this unless you want to.

**Comment by retorquere** [comment]
Ah I see. Yeah, I don't think I'm going to do that. If the plugin solves the problem, that seems like a good resolution. It'd be strange if you got one abbrev in the key and another in the export.
