### ISSUE TITLE
Ability to use citation key in CSL-based bibliography and citation formats

### ISSUE THREAD

**Issue by dmkaplan2000** [retorquere/zotero-better-bibtex#1472]
**Report ID:** 9FQS3TN9-euc

**Expected behavior:**

I would like to be able to include the citation key in a zotero CSL blibliography format, but as far as I can tell the citation key is not a real CSL field and so it is not accessible in CSL files. I saw an old discussion of this issue on the zotero forum [here](https://forums.zotero.org/discussion/56462/in-line-citation-with-as-citekey-for-easier-latex-conversion/p2), but I couldn't find anything since then and was wondering what the status is. Is it possible to include the citation key in the output from a CSL formatting file?

To explain why I want this, I have a considerable amount of text that was written using the Zotero plugin to word that I now want to convert for use in a Rmarkdown document. As far as I know, the easiest way to do this would be to change the bibliography format to a format that uses `@CITATIONKEY` as the citation so that I can just save as a text and import into my Rmarkdown document.

**Actual behavior:**

I can't find any CSL variable or zotero option in about:config that would allow me to access the citation key in a CSL file. If it is there and I just missed it, please let me know where it is.

Thanks,
David

**Comment by dmkaplan2000** [comment]
Report ID: 9FQS3TN9-euc

**Comment by retorquere** [comment]
It should be possible using https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#citeprocnotecitekey

If you enable that, BBT smuggles in the citekey by overwriting the CSL `note` field with it, in the (unvalidated) assumption that no style actually uses `note`. `note` is available in the processor, so styles that display the notefield (which you may have to create based on an existing style) will show the citekey there.

**Comment by dmkaplan2000** [comment]
Awesome! I saw that config option and almost clicked it, but didn't think it did what it does. 

Thanks for all your work on better bibtex for zotero. It is immensely useful!

**Comment by retorquere** [comment]
That's what I strive for 😄 .
