### ISSUE TITLE
Where can I learn more about available methods at localhost:23119/better-bibtex/json-rpc?

### ISSUE THREAD

**Issue by Bubblbu** [retorquere/zotero-better-bibtex#1473]
I have come across the `item.search` method while browsing issues and saw that `references` is also available. I am mostly interested in programmatically accessing individual items via their citekeys which is working for me with `item.search` at the moment. However, I wanted to learn more about the exposed methods on localhost.

**Comment by retorquere** [comment]
The jsonrpc endpoint exposes the methods of the User and Item class at https://github.com/retorquere/zotero-better-bibtex/blob/master/content/json-rpc.ts

**Comment by Bubblbu** [comment]
Thanks for the pointer! So the available endpoints through json-rpc are:

- user.groups
- item.search
- item.attachments

Is there any way to retrieve the formatted-citation for a particular item? I was hoping that the `reference` endpoint would provide that option.

**Comment by retorquere** [comment]
There isn't currently a `reference` endpoint (I think?), but formatted citations wouldn't be hard to add.

**Comment by Bubblbu** [comment]
Yes! I had thought that I came across `reference` in another issue but realized that it doesn't exist in the `json-rpc.ts` file.

Happy to work on a PR if you could point me to some relevant resources. I've been finding better-bibtex really useful to interact with my programmatically interact with Zotero based on citekeys (managing notes etc). Retrieving formatted citations would be a great addition for my use case

**Comment by retorquere** [comment]
When you say "formatted citation", do you mean the in-text citation, or the bibliography entry?

* sample to generate [in-text citation(https://github.com/retorquere/zotero-better-bibtex/blob/master/content/cayw/formatter.ts#L236)
* sample to generate [bibliography entry](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/cayw/formatter.ts#L246)

**Comment by Bubblbu** [comment]
I am in this case specifically talking about the entry in the bibliography. However, I would like to keep the quick copy settings set to Bibtex citekeys. If I understand correctly, those methods only work with changed quick copy settings, no?

**Comment by Bubblbu** [comment]
Would you prefer me to create proper issues as feature requests?

Concretely, I would love to be able to access formatted citations (as in a bibliography) and another interesting feature would be access to the saved notes. I wonder if the latter can be solved similar to the PDF endpoint that uses `has-attachment`

**Comment by retorquere** [comment]
You can use this issue to describe them as feature requests, no need to open a new issue

**Comment by Bubblbu** [comment]
**Feature suggestion:** API endpoint to retrieve formatted citations for items

Retrieve a formatted citation for a single item. This differs from the retrieval of a [bibliography entry](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/cayw/formatter.ts#L246) in its independence of the quick copy/export configuration in Zotero/BBT.

Ideally, the user would specify the selected item and a format and a formatted citation would be returned (which are also often provided on journal pages, e.g. PLOS provides a [citation page](https://journals.plos.org/plosone/article/citation?id=10.1371/journal.pone.0228914) for articles).

**Comment by Bubblbu** [comment]
**Feature suggestion:** Retrieve notes taken in Zotero 5 for individual items

I am not sure if this is possible, but retrieving notes through a similar endpoint would be really cool. Simply returning the full HTML markup would be enough as the conversion to another format would be then trivial on the user side.

**Comment by retorquere** [comment]
@Bubblbu what does "selected" mean here, and how would the user specify the desired style?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6357](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6357.xpi) ("retrieve notes")

Install in Zotero by downloading [test build 5.2.21.6357](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6357.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
For notes: try 
```
curl http://localhost:23119/better-bibtex/json-rpc \
-X POST \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
--data-binary '{"jsonrpc": "2.0", "method": "item.notes", "params": [["bentley_academic_2011", "@ShelahnoteHanfnumbers1970" ]] }'
```

(substituting the citekeys obviously) with 6357

**Comment by Bubblbu** [comment]
> @Bubblbu what does "selected" mean here

Oh sorry. I've been thinking ahead for myself a bit here. I'm building a CLI that will provide an interactive interface (ideally using formatted citations) in order to give the user the option to select an item on the CLI instead of purely relying on the citation picker.

For the endpoint, that shouldn't have any implication imo. The response would entail an array of formatted citations for all items that fit the searchquery right?

>  and how would the user specify the desired style?

I was thinking of re-using the internal labels for various styles that Zotero uses for the export formats. For now, I will probably simply go with a single default format, but having this feature could be really nice for the creation of automated annotated bibliographies based on notes and summaries.

**Comment by Bubblbu** [comment]
> For notes: try
> 
> ```
> curl http://localhost:23119/better-bibtex/json-rpc \
> -X POST \
> -H "Content-Type: application/json" \
> -H "Accept: application/json" \
> --data-binary '{"jsonrpc": "2.0", "method": "item.notes", "params": [["bentley_academic_2011", "@ShelahnoteHanfnumbers1970" ]] }'
> ```
> 
> (substituting the citekeys obviously) with 6357

This was quick :O thank you!

I'll test it later today

**Comment by retorquere** [comment]
> For the endpoint, that shouldn't have any implication imo. The response would entail an array of formatted citations for all items that fit the searchquery right?

That depends on what you want to achieve. For formatted citations, there's really two things you could be requesting:

* given a list of items, give the formatted bibliography, or
* given a list of lists of items, give the in-text citation for each of the groups

> > and how would the user specify the desired style?
> 
> I was thinking of re-using the internal labels for various styles that Zotero uses for the export formats. For now, I will probably simply go with a single default format, but having this feature could be really nice for the creation of automated annotated bibliographies based on notes and summaries.

The label for the style should be doable. You could also just choose the default format that Zotero already has a preference-setting for.

**Comment by Bubblbu** [comment]
> curl http://localhost:23119/better-bibtex/json-rpc \
> -X POST \
> -H "Content-Type: application/json" \
> -H "Accept: application/json" \
> --data-binary '{"jsonrpc": "2.0", "method": "item.notes", "params": [["bentley_academic_2011", "@ShelahnoteHanfnumbers1970" ]] }'

This is working perfectly for me! Amazing. Thank you!

**Comment by Bubblbu** [comment]
> That depends on what you want to achieve. For formatted citations, there's really two things you could be requesting:
> 
> * given a list of items, give the formatted bibliography, or
> * given a list of lists of items, give the in-text citation for each of the groups

I am more interested in the former. I would personally use the endpoint to retrieve the formatted entry for a single item, however, having the option to provide a list of items is obviously only benefitial.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6367](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6367.xpi) ("fixes #1473")

Install in Zotero by downloading [test build 5.2.21.6367](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6367.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6369](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6369.xpi) ("cleanup")

Install in Zotero by downloading [test build 5.2.21.6369](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6369.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
try the latest drop

**Comment by Bubblbu** [comment]
```
curl http://localhost:23119/better-bibtex/json-rpc \
   -X POST \
   -H "Content-Type: application/json" \
   -H "Accept: application/json" \
   --data-binary '{"jsonrpc": "2.0", "method": "items.bibliography", "params": [["@verkuytenNegativeImplicationsBeing2020"], {"id": "apa"}] }'
```

Using this request I am getting this error response:

`{"jsonrpc":"2.0","error":{"code":-32603,"message":"TypeError: style.getCiteProc is not a function"},"id":null}`

I assume `apa` should be fine as a style id, no?

**Comment by retorquere** [comment]
Zotero expects the full style url, so `http://www.zotero.org/styles/apa`.

The error is thrown a few layers down, so it'd be hard to work around that.

**Comment by retorquere** [comment]
I new build is running that will add the `http://www.zotero.org/styles/` if it's not there.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6370](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6370.xpi) ("fill out style url")

Install in Zotero by downloading [test build 5.2.21.6370](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6370.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by Bubblbu** [comment]
Works perfectly again. This is wonderful, thank you!
