### ISSUE TITLE
Exporting Book Sections as Inbook

### ISSUE THREAD

**Issue by qak** [retorquere/zotero-better-bibtex#1474]
Zotero items of type `Book Section` are exported by BBT's BibTeX exporter as `incollection` entries. It looks like BBT's BibTeX exporter doesn't use the `inbook` entry type. According to previous discussions (#282 and #877), BBT's BibLaTeX exporter uses `inbook` for book sections with book authors and `incollection` for book sections without book authors; it seems to me that the BibTeX exporter should export entries in the same way. Here's a debug-report ID with a relevant `Book Section` entry: `FBHYQ2SX-euc`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.20.6281](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6281.xpi) ("dammit fs-extra!")

Install in Zotero by downloading [test build 5.2.20.6281](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6281.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by qak** [comment]
Thanks, I can confirm that the issue's resolved in the test build.

**Comment by retorquere** [comment]
Thanks for the confirmation, merged.
