### ISSUE TITLE
BibTeX Entries with Volume and Number Fields

### ISSUE THREAD

**Issue by qak** [retorquere/zotero-better-bibtex#1475]
According to BibTeX's documentation the entry types `book`, `inbook`, `incollection`, `proceedings` and `inproceedings` can have either the `volume` field or the `number` field specified, but not both. I have a Zotero item of type `Conference Paper` with fields `Volume` and `Issue` filled out. This entry is exported by BBT's BibTeX exporter as an `inproceedings` entry with both fields `volume` and `number`. BibTeX outputs the following warning when parsing the exported bibliography:
```
Warning--can't use both volume and number fields in [citation key]
```
The resulting BBL file contains only the contents of the `volume` field (the `number` field is omitted). This would suggest that BBT's BibTeX exporter should only include the `volume` field in `book`, `inbook`, `incollection`, `proceedings` and `inproceedings` entries when the values of both `volume` and `number` are known from Zotero's `Volume` and `Issue` fields respectively. Here's a debug-report ID with a relevant `Conference Paper` entry: `A45Y75PT-euc`. Please note that BibLaTeX's documentation doesn't seem to indicate that BibLaTeX has this limitation too.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.20.6289](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6289.xpi) ("Merge branch 'gh-1476' into gh-1475")

Install in Zotero by downloading [test build 5.2.20.6289](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6289.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 6289?

**Comment by qak** [comment]
Thanks, the issue is resolved in the test build.

**Comment by retorquere** [comment]
Thanks for the confirmation, merged
