### ISSUE TITLE
30-Mar-2020 parsed as literal

### ISSUE THREAD

**Issue by ning-y** [retorquere/zotero-better-bibtex#1476]
Firstly, thanks for all the time and effort you've put into this extension.

**Report ID:** KBHXQGU2-apse

**Exporter used:** Better BibTex, Better BibLaTeX

**Expected behavior:** A Zotero entry with date written as `30-Mar-2020` should export (as *Better BibTeX* or *Better BibLaTeX*) with the year field `2020`.

**Actual behavior:** A Zotero entry with date written as `30-Mar-2020` exports (for both Better BibTex or Better BibLaTeX) with the bugged year field `30-Mar-2020`.

**To replicate:**
1. Create a new Journal Article Zotero entry.
2. Give this entry, in the *Date* field, the date `30-Mar-2020`.
3. Export this entry via *Export Item* or *Export Collection*, setting the format as either Better BibTeX or Better BibLaTeX.
4. The resulting bib files are:
  ```
  ==> better-biblatex.bib <==
  
  @article{TestEntry2020,
    title = {Test {{Entry}}},
    year = {30-Mar-2020}
  }
  
  
  
  ==> better-bibtex.bib <==
  
  @article{TestEntry2020,
    title = {Test {{Entry}}},
    year = {30-Mar-2020}
  }
  ```
The result of this bug is that in-text author-year citations become something like "(Heyns 30-Mar-2020)" rather than "(Heyns 2020)".

I am using Zotero 5.0.85, with Better BibTeX for Zotero 5.2.20, on Debian GNU/Linux 9.12 (stretch; x86_64 Linux 4.9.0-12-amd64).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.20.6282](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6282.xpi) ("Merge branch 'master' into gh-1476")

Install in Zotero by downloading [test build 5.2.20.6282](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6282.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 6282?

**Comment by ning-y** [comment]
@retorquere Seems to work well, thank you!

**Comment by retorquere** [comment]
thanks
