### ISSUE TITLE
Can I automate .aux scanning (via JSON-RPC)?

### ISSUE THREAD

**Issue by mrkwjc** [retorquere/zotero-better-bibtex#1477]
Hi!

As in the topic: can i somehow externally (via cayw?) send .aux file to zotero-better-bibtex and then (maybe immediately) retrieve a related .bib file?

Regards,
Marek

**Comment by retorquere** [comment]
It wouldn't be via CAYW; CAYW always has user interaction via item picking. There's also a JSON-RPC API that could be the gateway for this, but what's the use-case? If you're using the aux-file to get the bib-file, you'd need the bib file to get the aux file, so you'd have the bib file already.

**Comment by mrkwjc** [comment]
My goal is to keep the .bib file constantly synced with the keys currently used in the document. I thought that using .aux file wii be ok because it contains all these keys and it is generated even if .bib file is empty. An of course better bibtex contains parser for it. But of course maybe there is a better way i do not see now...

**Comment by retorquere** [comment]
It could be made to work I think. If the endpoint would update an existing group, that group could be set up for auto-export, and it'd work.

**Comment by mrkwjc** [comment]
I also thought that this should work :). But afaiu parsing for keys to be updated should be done locally? Also, could you please point me out how the endpoint updates an existing group?
Thanks!

**Comment by retorquere** [comment]
It'd be an endpoint to be added to the local jsonrpc support

**Comment by mrkwjc** [comment]
Well, unfortunately this sounds to me like magic spells :) Hovewer, can i do something at all with this on my own, with the current state of Zotero+Better Bibtex software? Or some software update would be necessary?

**Comment by retorquere** [comment]
An update would be required. I can take a look over the weekend, maybe next weekend, depending on how much the mayhem subsides. On your own end, you'd have to POST the aux file to BBT -- that can probably be done using `curl`. If you're in an incredible hurry, something could be bodged together using the [debug bridge](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge).

**Comment by mrkwjc** [comment]
I'm affraid i'm not skillful enough to develop Javascript, so i must wait... Anyway i think, this will be a very useful feature. Thanks!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6400](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6400.xpi) ("fixes #1477")

Install in Zotero by downloading [test build 5.2.21.6400](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6400.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
A new build will drop here in 15 minutes or so. Can you install that and test it out? You'd use it with:

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "collection.scanAUX", "params": [{ "libraryID": 1, "key": "P5RPA64T"} , "/Users/emile/Downloads/output.aux"] }'
```

where `libraryID` and `key` of the collection can be learned from right-clicking the collection and selecting `Download Better BibTeX export`. You'll see two URLs, only the first is of interest. The number after `collection/?/` is the `libraryID`, the string after that before the period is the `key`. Path must be absolute paths.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6402](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6402.xpi) ("fixes #1477")

Install in Zotero by downloading [test build 5.2.21.6402](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6402.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by mrkwjc** [comment]
Unfortunately this didn't work for me with the error:
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"[Exception... \"Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.append]\"  nsresult: \"0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)\"  location: \"JS frame :: chrome://zotero-better-bibtex/content/common.js :: parse :: line 55061\"  data: no]"},"id":null}
```
I checked twice, that file name is a valid abslolute AUX file path and the libraryID is also valid. I installed test version 5.2.21.6402.

**Comment by retorquere** [comment]
What did you send, exactly?

**Comment by mrkwjc** [comment]
UPDATE: I tried couple of times and somehow once i get the output: `{"jsonrpc":"2.0","id":null}` and my AUX based collection appeared in zotero! But for most trials i get the error above...

My exact command is:
```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "collection.scanAUX", "params": [{ "libraryID": 1, "key": "AQIV4BNT"} , "/home/mwojc/Lectures/SoilMechanics/lectures.aux"] }'
```

**Comment by retorquere** [comment]
But all these attempts were with the same aux file?

**Comment by mrkwjc** [comment]
Yes. I just repeate in console exactly the same command with the frequency about 1/10s

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6411](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6411.xpi) ("add logging")

Install in Zotero by downloading [test build 5.2.21.6411](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6411.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Van you reproduce the problem on 6411 and send a debug log from the help menu after the first failure?

**Comment by mrkwjc** [comment]
That's the debug output:
```
[JavaScript Error: "{better-bibtex! +1} JSON-RPC: <Error: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.append]#
parse@chrome://zotero-better-bibtex/content/common.js:61556:13
scan@chrome://zotero-better-bibtex/content/common.js:61497:15
scanAUX@chrome://zotero-better-bibtex/content/common.js:64689:15
handle@chrome://zotero-better-bibtex/content/common.js:64804:56
init@chrome://zotero-better-bibtex/content/common.js:64837:107
> "]

version => 5.0.85, platform => Linux x86_64, oscpu => Linux x86_64, locale => pl-PL, appName => Zotero, appVersion => 5.0.85, extensions => Zotero LibreOffice Integration (5.0.22.SA.5.0.85, extension), Better BibTex for Zotero (5.2.21.6411, extension)

(3)(+0000000): Starting full-text content processor

(5)(+0112257): POST /better-bibtex/json-rpc HTTP/1.1 Host: localhost:23119 User-Agent: curl/7.69.1 Content-Type: application/json Accept: application/json Content-Length: 153

(3)(+0000004): {better-bibtex +null} json-rpc: execute {"jsonrpc":"2.0","method":"collection.scanAUX","params":[{"key":"AQIV4BNT","libraryID":1},"/home/mwojc/Lectures/SoilMechanics/lectures.aux"]}

(3)(+0000001): {better-bibtex +1} AUX scanner: parsing /home/mwojc/Lectures/SoilMechanics/lectures.aux

(1)(+0000001): {better-bibtex! +1} JSON-RPC: <Error: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.append]# parse@chrome://zotero-better-bibtex/content/common.js:61556:13 scan@chrome://zotero-better-bibtex/content/common.js:61497:15 scanAUX@chrome://zotero-better-bibtex/content/common.js:64689:15 handle@chrome://zotero-better-bibtex/content/common.js:64804:56 init@chrome://zotero-better-bibtex/content/common.js:64837:107 >

(5)(+0000001): HTTP/1.0 200 OK X-Zotero-Version: 5.0.85 X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"jsonrpc":"2.0","error":{"code":-32603,"message":"[Exception... \"Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.append]\" nsresult: \"0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)\" location: \"JS frame :: chrome://zotero-better-bibtex/content/common.js :: parse :: line 61556\" data: no]"},"id":null}

(2)(+0018493): WARNING: Zotero.Collection.prototype.parent has been deprecated -- use .parentID or .parentKey

(3)(+0055768): HTTP POST "[JavaScript Error: "{better-bi…" (2384 chars) to https://repo.zotero.org/repo/report?debug=1

(3)(+0000010): POST body gzipped from 2384 to 901; 62% savings

(3)(+0001027): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200
```

**Comment by retorquere** [comment]
Please just send a BBT debug log from the help menu

**Comment by mrkwjc** [comment]
I sent log named: 35GBXA7K-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6413](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6413.xpi) ("why can this path not be found?")

Install in Zotero by downloading [test build 5.2.21.6413](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6413.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can I get a new debug log from 6413?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6414](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6414.xpi) ("path, not file")

Install in Zotero by downloading [test build 5.2.21.6414](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6414.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can I get a new debug log from 6414?

**Comment by mrkwjc** [comment]
Submitted with ID: GASETGG5-euc

Now it works! However, each run creates new subcollection instead of updating the same one. Is this intended?

**Comment by retorquere** [comment]
This build uses the FF-own way for reading the files rather than the Zotero shells around them... should not have made any difference, but good to know.

Ah, right, yes, it does currently use the collection as the root to create a new one. That's fixable.

**Comment by retorquere** [comment]
Now that I think of it -- would you expect items not in the aux file to be cleared out? That would make things considerably more complex.

**Comment by retorquere** [comment]
No wait -- that's not true. Forget that. So yeah -- would you expect items not in the aux to be removed from the target collection?

**Comment by mrkwjc** [comment]
Yes. I'd like to keep the target collection continuoulsy synced with the aux, i.e. the references used currently in the document (but of course i do not want to remove them from the zotero library).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6420](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6420.xpi) ("allow replace")

Install in Zotero by downloading [test build 5.2.21.6420](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6420.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "collection.scanAUX", "params": [{ "libraryID": 1, "key": "P5RPA64T", "replace": true} , "/Users/emile/Downloads/output.aux"] }'
```

should update the collection in-place

**Comment by retorquere** [comment]
Nothing of this deletes or modifies existing items. It only populates the target collection.

**Comment by mrkwjc** [comment]
It works! However one more idea: is this still possible to go half-step back, namely: create new subcollection *if it does not exist* and replace otherwise? Maybe by new keyword option?

**Comment by retorquere** [comment]
A lot is possible, I'm just not sure how it would work. What parameters would you expect to submit, how would you point to "a collection that does not exist"? Getting some Frege flashbacks here :)

**Comment by mrkwjc** [comment]
I was convinced that the subcollection inside a collection can be accessed just by its name? So that with curl i can send always the same collection ID, but different aux files. This should create new subcollection named as aux file or update if it was created before.

**Comment by retorquere** [comment]
Ah like that. I'll see.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6429](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6429.xpi) ("harden build against github outage")

Install in Zotero by downloading [test build 5.2.21.6429](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6429.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
In 6429, `replace` can either be a boolean (where obviously only `true` will actually replace the collection contents) or a string, in which case a subcollection in the collection you point to will either be created or replaced.

**Comment by mrkwjc** [comment]
It works! That's exactly what i needed :-) Thank you very much.

I think this can be closed now...

**Comment by mrkwjc** [comment]
Ahh. One more thing. After sending aux (let's say a new aux), i'd like to synchronize immediately the bib file. I know such synchronization can be set up manually in zotero and this is done once, but: is there a `curl` way for this?

**Comment by retorquere** [comment]
A build of that will drop in 15 minutes or so, but the signature for `collection.scanAUX` has changed. I'm setting up docs for that now, but that will take a bit.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6449](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6449.xpi) ("json-rpc: add autoexport")

Install in Zotero by downloading [test build 5.2.21.6449](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6449.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Docs at temporarily at https://github.com/retorquere/zotero-better-bibtex/blob/gh-1477/site/layouts/shortcodes/json-rpc.md

**Comment by retorquere** [comment]
you can ignore the build that will be announced shortly, it's a side effect of the docs update

**Comment by retorquere** [comment]
If these two work to your satisfaction, I can merge and release.

**Comment by retorquere** [comment]
This issue is currently the one thing that keeps me from cutting a new release. I'd *really* prefer if I could get some feedback on the latest adaptations.

**Comment by mrkwjc** [comment]
Sorry for delay. Could you instruct me now how to use the scanAUX and autoexport with curl? I'm calling this:

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "collection.scanAUX", "params": [{"aux": "/home/mwojc/Lectures/SoilMechanics/lectures.aux", "collection": "SoilMEchanics/lectures"}]}'
```
but i get this:
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"TypeError: (intermediate value).split is not a function"},"id":null}(base)
```
I'm pretty sure this call is wrong...

**Comment by mrkwjc** [comment]
I called now:
```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "collection.scanAUX", "params": ["/My Library/SoilMechanics/lectures", "/home/mwojc/Lectures/SoilMechanics/lectures.aux"]}'
```
but it says there's no "My Library":
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Error: Library 'My Library' not found"},"id":null}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6463](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6463.xpi) ("log library names")

Install in Zotero by downloading [test build 5.2.21.6463](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6463.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you get me a debug log of that with 6463?

**Comment by mrkwjc** [comment]
It is working, i had to use localized name for 'My Library', i.e. 'Moja biblioteka' in my case. I'll test autoexoprt in a while...

**Comment by mrkwjc** [comment]
"autoexport.add" didin't work with this call:
```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "autoexport.add", "params": ["/Moja biblioteka/SoilMechanics/lectures", "bibtex", "/home/mwojc/Lectures/SoilMechanics/lectures.bib", "{}", "True"]}'
```
I get error:
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Error: Library 'home' not found"},"id":null}
```

Send debug report n this: RWM5TAYG-euc

**Comment by retorquere** [comment]
A new build is incoming that fixes this error, and also makes it that a collection path that starts with an empty library name (so `//SoilMechanics/lectures` in your case) selects "My Library" whatever its local name is.

When that build drops, you will still need to change the call to

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "autoexport.add", "params": ["//SoilMechanics/lectures", "bibtex", "/home/mwojc/Lectures/SoilMechanics/lectures.bib", {}, true]}'
```

`"{}"` is a string with curly brackets vs `{}` which is an empty object, and `"True"` is the string `True` vs `true` which is a boolean truth value. But you can in principle omit the latter two; `replace` defaults to `false` but on repeated calls you wouldn't typically want to overwrite the auto-export; replacing will a.o. undo any custom settings you had on it, and it is seen as "existing" only if it has the same target path for the bib file and the same collection source.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6468](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6468.xpi) ("Merge branch 'master' into gh-1477")

Install in Zotero by downloading [test build 5.2.21.6468](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6468.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6468 contains these changes

**Comment by mrkwjc** [comment]
scanAUX works nicely with "//" but with "/My Library" it still complains there's no such library. Regarding the autoexport.add i was also successful, but i observed that the 'bib' file is not populated with collection entries until you make a first change in the collection (via scanAUX for example). I think 'bib' should be immediately populated at export creation.

In general things are now functional to me, the above caveats are the minor ones...

**Comment by retorquere** [comment]
> scanAUX works nicely with "//" but with "/My Library" it still complains there's no such library. 

That is correct -- if you have a name there, it must match an existing library. The robust way to select the personal library is to omit the name.

> Regarding the autoexport.add i was also successful, but i observed that the 'bib' file is not populated with collection entries until you make a first change in the collection (via scanAUX for example). I think 'bib' should be immediately populated at export creation.

Ah you mean for an existing collection? New build coming up.

> In general things are now functional to me, the above caveats are the minor ones...

Prefer to get full closure. New build should land in about 10 minutes.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6472](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6472.xpi) ("schedule on add")

Install in Zotero by downloading [test build 5.2.21.6472](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6472.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by mrkwjc** [comment]
> > scanAUX works nicely with "//" but with "/My Library" it still complains there's no such library.
> 
> That is correct -- if you have a name there, it must match an existing library. The robust way to select the personal library is to omit the name.

Ok, that's just fine.

> > Regarding the autoexport.add i was also successful, but i observed that the 'bib' file is not populated with collection entries until you make a first change in the collection (via scanAUX for example). I think 'bib' should be immediately populated at export creation.
> 
> Ah you mean for an existing collection? New build coming up.

I mean that when you create a new export interactively then the indicated bib file is immediately populated with the exported collection entries (and then updated on change if desired). When i call autoexport.add then the new autoexport is added to zotero, but there's no initial export. This is still so with the new build.

**Comment by retorquere** [comment]
Just so I understand correctly, what you're doing is you use JSON-RPC to set up auto-export for an existing, non-empty collection, which does not yet have an auto-export, and that setup over JSON-RPC succeeds, but the target file is not created?

**Comment by mrkwjc** [comment]
Yes. But even if the collection will be newly created and empty, then the target file should be created or updated. This target file is designated for continuous update anyway.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6475](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6475.xpi) ("schedule even when empty")

Install in Zotero by downloading [test build 5.2.21.6475](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6475.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6475 should do it.

**Comment by mrkwjc** [comment]
It does indeed :) So i'm fully satisfied now. My workin workflow is the following:

with ['collection', 'name']:
    create 'name.tex'
    call autoexport.add('//collection/name', 'bibtex', 'name.bib')
    write text with citations inserted via cayw interface (custom shortcut in TexStudio)
    use 'name.bib' as the bibliography file
    when needed (new tool in TexStudio can be added):
        first pdflatex run
        call collection.scanAUX('//collection/name', 'name.aux')
        second pdflatex run

I think, this issue can be closed now.
