### ISSUE TITLE
/ Should be exported as \slash

### ISSUE THREAD

**Issue by jendrikw** [retorquere/zotero-better-bibtex#1478]
According to [wikibooks](https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Slash_marks):

_Words that use slash marks, such as "input/output" should be typeset as `input\slash output`, which allow the line to "break" after the slash mark (if needed). The use of the / character in LaTeX should be restricted to units, such as `mm/year`, which should not be broken over multiple lines._

**Report ID:** 5BTMRMQW-euc

**Exporter used:** Better Biblatex

**Expected behavior:**
```bib
@online{VoronovPortingRedisWebAssembly,
  title = {Porting {{Redis}} to {{WebAssembly}} with {{Clang}}\slash {{WASI}}},
  author = {Voronov, Mikhail},
  date = {2019-07-02},
  journaltitle = {Medium},
  url = {https://medium.com/fluence-network/porting-redis-to-webassembly-with-clang-wasi-af99b264ca8},
  urldate = {2020-03-11},
  abstract = {At Fluence, we use WebAssembly (Wasm) to run applications in a trustless network of independent nodes. This trustless environment mandates…},
  file = {/home/MYUSER/Zotero/storage/6TA9UQGE/porting-redis-to-webassembly-with-clang-wasi-af99b264ca8.html},
  keywords = {wasm},
  langid = {english}
}
```

**Actual behavior:**
```bib
@online{VoronovPortingRedisWebAssembly,
  title = {Porting {{Redis}} to {{WebAssembly}} with {{Clang}}/{{WASI}}},
  author = {Voronov, Mikhail},
  date = {2019-07-02},
  journaltitle = {Medium},
  url = {https://medium.com/fluence-network/porting-redis-to-webassembly-with-clang-wasi-af99b264ca8},
  urldate = {2020-03-11},
  abstract = {At Fluence, we use WebAssembly (Wasm) to run applications in a trustless network of independent nodes. This trustless environment mandates…},
  file = {/home/MYUSER/Zotero/storage/6TA9UQGE/porting-redis-to-webassembly-with-clang-wasi-af99b264ca8.html},
  keywords = {wasm},
  langid = {english}
}
```

**Comment by jendrikw** [comment]
> Alternately, I could translate solidus (2F) to / and full width solidus (FF0F) to \slash.

That sounds reasonable.

**Comment by retorquere** [comment]
I currently have 2215 DIVISION SLASH mapped to `\slash` but it seems better to map 2215 to a math-slash and FF0F to text-`\slash`. Agreed?

**Comment by jendrikw** [comment]
Makes sense.

**Comment by retorquere** [comment]
I'm not super happy with how `U+FF0F` looks in the text. I'm considering `U+200B/` instead to generate `\slash`; the unicode standard says

> The U+200B zero  width  space  indicates  a  word  break  or  line  break opportunity, even though there is no intrinsic width associated with this character.

which seems to fit with what `\slash` does.

**Comment by retorquere** [comment]
Does `\slash` break before or after the slash?

**Comment by jendrikw** [comment]
Is it possible to enter the zero-width space as HTML escapes codes or something? It would be hard to know if the title already includes some or not.

`\slash` is defined in the LaTeX kernel latex.ltx on line 577 as `\def\slash{/\penalty\exhyphenpenalty}`. So it breaks after the slash.

So it would be more consistent to map `/U+200B` to `\slash`.

**Comment by jendrikw** [comment]
The way pandoc translates plain text to LaTeX is by encouraging authors to insert a zero-width space at points where line breaks are allowed, so the user can put them before or after the slash, or at a different place in the surrounding words. A zero-width space is always translated as `\hspace{0pt}`, so that LaTeX can make a line break. See https://github.com/jgm/pandoc/issues/3132#issuecomment-251117723.

**Comment by retorquere** [comment]
> Is it possible to enter the zero-width space as HTML escapes codes or something?

Zotero doesn't support it. Technically you could use `input<script>\slash </script>output`, but that's a BBT-only thing, it'd mess up Word-rendered bibliographies of the same item.

> It would be hard to know if the title already includes some or not.

Absolutely. I'm not super happy about this workaround, and I'm open to any better option that doesn't involve natural language processing.

> So it would be more consistent to map `/U+200B` to `\slash`.

Thanks. Tests are running.

**Comment by retorquere** [comment]
> The way pandoc translates plain text to LaTeX is by encouraging authors to insert a zero-width space at points where line breaks are allowed, so the user can put them before or after the slash, or at a different place in the surrounding words. A zero-width space is always translated as `\hspace{0pt}`, so that LaTeX can make a line break. See [jgm/pandoc#3132 (comment)](https://github.com/jgm/pandoc/issues/3132#issuecomment-251117723).

I export a standalone ZWS (`U+200B`) to `\mbox{}`, which should achieve the same. It's currently just specifically `/U+200B` that would get converted into `\slash`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.20.6346](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6346.xpi) ("ncu")

Install in Zotero by downloading [test build 5.2.20.6346](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6346.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jendrikw** [comment]
I can confirm that the new build correctly exports `/U+200B` as `\slash`.

**Comment by jendrikw** [comment]
For future reference: If the part before the slash is a word that LaTeX doesn't know how to hyphenate (like _Clang_ in my case), you need to give it the hyphenation pattern including the `/` symbol:

```latex
\hyphenation{Clang}
\hyphenation{Clang/}
```
