### ISSUE TITLE
The "Pin BibTeX key from InspireHEP" option has stopped working

### ISSUE THREAD

**Issue by jmcarm** [retorquere/zotero-better-bibtex#1479]
The "Pin BibTeX key from InspireHEP" option worked perfectly in my system, but has now stopped working. This may be due to the fact that InspireHEP page (https://inspirehep.net/) has recently (26th March 2020) changed to an upgraded version. It might be possible that the zotero-better-bibtex has to adapt to this change...

Thanks very much for your work on this add-on.

**Comment by jmcarm** [comment]
Debug ID: N6RIKPEW-euc

**Comment by retorquere** [comment]
I see on https://blog.inspirehep.net/ that

> The old interface will remain accessible for a limited time at https://old.inspirehep.net/ and will be switched off by June 2020. 

So I can fix this temporarily but they're talking about shutting off the existing API in 2 to 3 months, but they don't have anything written on how the replacement API will work or even when it goes live.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.20.6343](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6343.xpi) ("Merge branch 'master' into gh-1479")

Install in Zotero by downloading [test build 5.2.20.6343](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6343.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jmcarm** [comment]
It works now, thank you very much!

**Comment by retorquere** [comment]
Mind that it will stop working again in a few months. I couldn't find information on the API that's supposed to replace this one come June (or earlier). If you find something, let me know.

**Comment by jmcarm** [comment]
Thank you. I have written an email (copied below) to feedback@inspirehep.net. I will let you know if I receive an answer from them.

-----E-mail
Dear Sirs,

Thank you very much for the new INSPIRE. It works very nicely. I am a professor of physics working at the University of Zaragoza and actively use Zotero as my bibliographic database. Zotero has an extension called "Better BibTeX" (https://retorque.re/zotero-better-bibtex/) that allows you to pick up the BibTeX key from INSPIRE. It uses the old API from INSPIRE, and stopped working when you changed to the new INSPIRE. After my request at Github, the developer has fixed this temporarily by pointing to the old API, but this will only work until you switch it off completely. Will you provide information on the new API so that this very useful Zotero add-on can continue working properly?

Many thanks. With best regards,

Jose Manuel Carmona
University of Zaragoza

**Comment by retorquere** [comment]
Thanks

**Comment by jmcarm** [comment]
For your information, I received this message today from INSPIRE:

Dear Jose,

Thanks for your feedback. We don't offer a public API on the new system yet,
but it's planned and we will certainly provide detailed information on how to
use it.

Best regards,
The INSPIRE Team

**Comment by retorquere** [comment]
That's not incredibly helpful. Well, let me know when they offer a more substantial response.

**Comment by jmcarm** [comment]
Hello, INSPIRE has answered me today about this issue:

Dear Jose Manuel,

We released the new INSPIRE API. Please find more information on our blog post:
https://blog.inspirehep.net/2020/06/we-released-the-new-inspire-api/

Best regards,
the INSPIRE team

-----

I hope this can be useful. Many thanks.

**Comment by retorquere** [comment]
Would it be possible for you to find out what query to send to the API to search for the key based on the DOI or arXiv ID? It's not immediately clear to me from the API docs.

**Comment by jmcarm** [comment]
Hi, I see that
https://inspirehep.net/api/doi/10.1103/PhysRevD.101.044057
or
https://inspirehep.net/api/arxiv/0909.1706
redirects to the record of doi "10.1103/PhysRevD.101.044057" or the record with arxiv "0909.1706".

In that record, the key appears after "texkeys".

Is this what you need? I am not sure how you extracted the key from the queries with the old API.

If this is not what you need, we can e-mail the inspire team. They indicate:

"If you have any suggestions, remarks or questions, we’d be more than happy to hear from you! Just email us at feedback@inspirehep.net!

**Comment by retorquere** [comment]
Nope, those work, they don't redirect, they directly give the JSON I need.

**Comment by jmcarm** [comment]
Sorry, I do not understand well. Does this mean that the problem is solved?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.30.6672](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.30.6672.xpi) ("fixes #1479")

Install in Zotero by downloading [test build 5.2.30.6672](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.30.6672.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6672 should fix it. I'd appreciate it if you could test it.

**Comment by jmcarm** [comment]
Dear Emiliano,

Yes, it works nicely! Many thanks for fixing it.

Best regards,
Jose Manuel

**Comment by retorquere** [comment]
A new release build is running that will include this.

**Comment by chensun-hep** [comment]
It works like a charm as of today. Thanks!
