### ISSUE TITLE
Prevent automatic regeneration of all BibTeX after installation

### ISSUE THREAD

**Issue by erhart1** [retorquere/zotero-better-bibtex#1480]
# Description

First of all thank you for this add-on. It is very useful for me since it in principle allows customization of BibTeX keys. Unfortunately, after the initial installation it seems unavoidable that the add-on regenerates all keys. Since I am using the add-on on multiple machines, all my BibTeX keys are being regenerated every time I installed the add-on on another machine. Since the default key is not the one I am using, this destroys all my existing keys. When I then reconfigure the key format, I have to generate keys one more time. Since there is afaik no function for doing this for the entire database, I have to do this by hand. Selecting all entries doesn't seem to work (there are several thousand entries) and hence I have to select them in blocks for regeneration. This is very annoying, especially after the third or fourth time. 

Maybe I am missing something but I have not been able to find a way around this dilemma.

**Comment by erhart1** [comment]
Debug ID: P42SCP2E-euc

**Comment by retorquere** [comment]
The only way to prevent this is by "pinning" the citekeys (right-click, BBT, pin). This will write the cite keys to the `extra` field, and those always take precedence -- when that is present, no new key will be generated, and the `extra` field syncs, so they'll get to your other systems. The non-pinned keys live in a separate database that I cannot sync -- I may not add private data to the zotero database.

A change to zotero is planned to add a formally supported (and syncable) citekey field, but that's been talked about for years -- no idea when it wil finally drop.

**Comment by retorquere** [comment]
Does this answer your question?

**Comment by erhart1** [comment]
Yes. Thank you very much. Sorry for the slow reply.
