### ISSUE TITLE
Some Unicode characters converted to LaTeX

### ISSUE THREAD

**Issue by sieversMartin** [retorquere/zotero-better-bibtex#1481]
**Report ID:** T59CEP9J-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** All Unicode characters are kept untouched on export

**Actual behavior:** _Some_ characters are concerted into a LaTeX macro, e.g.
before (with 5.2.16): `title = {Vedic anuṣṭhú and anuṣṭh(u)yā́},`
now (with 5.2.20): `title = {Vedic anuṣṭhú and anuṣṭh(u)y\'{ā}},`
or
before: `title = {Avestisch \emph{auuax́iiāi. rafənō.x́iiāi}},`
and now: `title = {Avestisch \emph{auua\'{x}iiāi. rafənō.\'{x}iiāi}}`

```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.20.6311](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6311.xpi) ("fixes #1481")

Install in Zotero by downloading [test build 5.2.20.6311](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.20.6311.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by sieversMartin** [comment]
Works fine. Thank you very much.

**Comment by retorquere** [comment]
@njbart how would I reproduce `ā́`? `\'{{\=a}` doesn't work.

**Comment by retorquere** [comment]
NM, got it, `tipa`
