### ISSUE TITLE
Initializing error, Starting auto-export

### ISSUE THREAD

**Issue by Merovex** [retorquere/zotero-better-bibtex#1485]
**Report ID:** GHIRK9QM-euc

**Exporter used:** I don't know what this means, but using OSX standalone Zotero. I'm new to it, and only have 10 references. So, this is about as vanilla as they come. I did the basic setup wizard, and as soon as everything restarted I got this error.

**Expected behavior:** I expect it to initialize. I only started using Zotero this week, and installed the latest Better BibTeX this morning from the release page, release date 8 April 2020. Should be current.

**Actual behavior:** The "Better BibTeX: Initializing Starting auto-export" dialog pops up, and only goes away when I close Zotero.

```
[JavaScript Error: "Error: zotero-better-bibtex: load of content/auto-export.ts failed:[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIIdleService.addIdleObserver]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://zotero-better-bibtex/content/common.js :: ./auto-export.ts/queue< :: line 53991"  data: no]::./auto-export.ts/queue<@chrome://zotero-better-bibtex/content/common.js:53991:9
./auto-export.ts@chrome://zotero-better-bibtex/content/common.js:53981:15
__webpack_require__@chrome://zotero-better-bibtex/content/webpack.js:82:12
./key-manager.ts@chrome://zotero-better-bibtex/content/common.js:57340:23
__webpack_require__@chrome://zotero-better-bibtex/content/webpack.js:82:12
./json-rpc.ts@chrome://zotero-better-bibtex/content/common.js:57195:23
__webpack_require__@chrome://zotero-better-bibtex/content/webpack.js:82:12
./better-bibtex.ts@chrome://zotero-better-bibtex/content/common.js:54414:1
__webpack_require__@chrome://zotero-better-bibtex/content/webpack.js:82:12
./BetterBibTeX.ts@chrome://zotero-better-bibtex/content/BetterBibTeX.js:15:25
__webpack_require__@chrome://zotero-better-bibtex/content/webpack.js:82:12
checkDeferredModules@chrome://zotero-better-bibtex/content/webpack.js:48:23
webpackJsonpCallback@chrome://zotero-better-bibtex/content/webpack.js:35:19
@chrome://zotero-better-bibtex/content/BetterBibTeX.js:2:2
"]
```

**Comment by retorquere** [comment]
Wait -- before you do that, move them, don't delete them, and get me a copy

**Comment by Merovex** [comment]
How to get you the copy?

**Comment by Merovex** [comment]
I think perhaps when I activated the plugin, a setting was not made correctly? It almost looks like it is try to auto-export nowhere. I removed better-bibtex, deleted the entries, then re-installed. I was not re-presented with the install wizard dialog. So, there is a configuration setting that is unchanged.

**Comment by retorquere** [comment]
> How to get you the copy?

Zip and send via https://transfer.sh/ , post the link here maybe?

> I think perhaps when I activated the plugin, a setting was not made correctly?

It's more likely that there was a corrupt database that it failed to load

> It almost looks like it is try to auto-export nowhere. I removed better-bibtex, deleted the entries, then re-installed. I was not re-presented with the install wizard dialog. So, there is a configuration setting that is unchanged.

The configuration is saved in the central place for preferences, not in the DB.

**Comment by retorquere** [comment]
Can't do anything without those files.

**Comment by Merovex** [comment]
Sorry, I did not notice your reply. Transfer.sh did not work, here's a GDrive shared.

https://drive.google.com/file/d/1r4ebBLrBke3xGZRqFubJ8TlINJPos6v_/view?usp=sharing

**Comment by retorquere** [comment]
There are no errors in those databases. If you remove them, or move them out of the zotero directory, does BBT start up?

**Comment by Merovex** [comment]
When I shut down Zotero, delete everything with better-bibtex (`rm -rf better-bibtex*`) and restart, then the files are returned, and I am afflicted with the "Starting auto-export" that just sits there. Perhaps there is a configuration setting when I installed BB that I cannot change that is causing this?

**Comment by retorquere** [comment]
Wait -- you're on 5.1.139. Can you first upgrade and then see whether the problem persists?

**Comment by Merovex** [comment]
All seems right with the world. I thought I'd pulled down the latest version originally. TTFN

**Comment by Merovex** [comment]
Well, I guess I can't close it?

**Comment by retorquere** [comment]
If an issue is labeled anything but `question`, I'm the only one that can close it. I keep bug-issues open as a reminder to myself that I must merge the changes into a release.

**Comment by Merovex** [comment]
Cool. Well, thanks a lot for the help & patience. Cool mod.
