### ISSUE TITLE
Cite keys in Russian

### ISSUE THREAD

**Issue by Nick222** [retorquere/zotero-better-bibtex#1487]
Can user change option to create citekeys in Russian - all symbols are non-Latin ?

**Comment by retorquere** [comment]
I really do need that debug log as per point 1 above.

**Comment by Nick222** [comment]
ID HDRARBVA-euc

**Comment by retorquere** [comment]
Try `[Auth:lower][Title:select=1,3][year]`, and unchecking `Force citation key to plain text`.

**Comment by Nick222** [comment]
No - only Latin "polivanovKrugOcherednyhProblem2020"

**Comment by retorquere** [comment]
Did you refresh the key after changing the pattern?

**Comment by retorquere** [comment]
For me the key is `поливановКругочередныхпроблем2020` with those settings, but you need to refresh the key. Keys are not automatically refreshed after the pattern changes.

**Comment by Nick222** [comment]
YES !!! Wonderful ! :) Thank You very march ! :)

**Comment by retorquere** [comment]
My pleasure.
