### ISSUE TITLE
Regression in export to better biblatex

### ISSUE THREAD

**Issue by hoehnp** [retorquere/zotero-better-bibtex#1491]
**Report ID:**
5CH5E2X6-euc
**Exporter used:**
Better BibLaTeX
**Expected behavior:**
export of reference with correct encoding, successfully compiling with latexmk -pdf
behaviour changes on update from 5.2.20 to 5.2.21
[old.txt](https://github.com/retorquere/zotero-better-bibtex/files/4480491/old.txt)
**Actual behavior:**
Encoding of special characters with incorrect encoding, compilation with latexmk -pdf fails
[new.txt](https://github.com/retorquere/zotero-better-bibtex/files/4480437/new.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6376](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6376.xpi) ("fix tests for #1491")

Install in Zotero by downloading [test build 5.2.21.6376](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6376.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Thanks for reporting this -- both were actually wrong. With your settings, the export should have yielded `ı̈` for biblatex, and `{\"{\i}}` for bibtex. Try 6376.

**Comment by hoehnp** [comment]
@retorquere: really thanks a lot for the quick response. I installed the test build and it seems to fix my issue. Auto-exports produce working bibtex code again. I believe we can close the issue now.

**Comment by retorquere** [comment]
Thanks for the confirmation -- I have a bit more cleanup work I want to do, and then I'll merge & close
