### ISSUE TITLE
Stop auto-exporting when making changes to omitted fields

### ISSUE THREAD

**Issue by MSBack** [retorquere/zotero-better-bibtex#1494]
**Report ID:**

**Exporter used:**
Better BibLaTex
**Expected behavior:**
No auto-export when changing fields that are omitted from the export.
**Actual behavior:**
Auto-exports are triggered by changes to omitted fields, even though nothing will be different in the exported file. This is thus unnecessary.

**Comment by retorquere** [comment]
This is unfeasible, sorry. In order to detect what fields would be exported, I have to run the export; the export removes the omitted-fields at the end. Certainly given postscripts it is not possible to predict beforehand what the output will be.

**Comment by MSBack** [comment]
Okay, that's unfortunate, but thanks for the response and a great plugin.

**Comment by retorquere** [comment]
There's also the additional issue that Zotero tells me *that* an item has changed, but not *how* it has changed, so this really cannot be done, sorry.
