### ISSUE TITLE
use author dash separation rather than camel casing in citekey

### ISSUE THREAD

**Issue by bdarcus** [retorquere/zotero-better-bibtex#1495]
I would like to generate citekeys as follows:

```
doe-smith_2018-title-some
```

... where the first fragment (authors) and the last fragment (shortitle with skipwords applied) uses a dash to separate words, rather than camel casing.

I think I could use title and replace the spaces with dashes, but that's not exactly what I want.

Is this possible?

Here's my current config:

```
[authors2:lower][>0]_[year]-[shorttitle:skipwords:lower]| [shorttitle:skipwords:lower]-[year]
```

**Comment by bdarcus** [comment]
I couldn't figure out how to label this a question, rather than a bug.

**Comment by retorquere** [comment]
You probably weren't logged in to github when you started making the issue -- if you're logged in, you get a prompt to choose.

I'd still prefer to receive a debug log as per point 1, because that will give us a shared example to work with. In my experience that works better than abstract discussions about hypothetical items.

**Comment by bdarcus** [comment]
I was logged in, but maybe I just missed something.

In any case, the report ID is WYCN6ZSK-euc.

**Comment by retorquere** [comment]
And what key would you want to generate for that item?

**Comment by bdarcus** [comment]
If this is current output:

```
salnikovadarcus_2019-spacesmuslimidentity
```
This is what I want:

```
salnikova-darcus_2019-spaces-muslim-identity
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6393](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6393.xpi) ("citekey filters")

Install in Zotero by downloading [test build 5.2.21.6393](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6393.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bdarcus** [comment]
I see the test build and have installed it. But what do I do to modify my config to get my desired output?

To remind, here it is:

```
[authors2:lower][>0]_[year]-[shorttitle:skipwords:lower]| [shorttitle:skipwords:lower]-[year]
```

**Comment by retorquere** [comment]
On 6393, these two should each get you what you want (that they didn't work on the main release was a bug):

```
[authors2+-:lower]_[year]-[shorttitle:condense=-:lower]
```

```
[authors2:condense=-:lower]_[year]-[shorttitle:condense=-:lower]
```

**Comment by bdarcus** [comment]
That does indeed work; thank you!
