### ISSUE TITLE
Add keyboard shortcut to pin/unpin keys

### ISSUE THREAD

**Issue by jcvtieck** [retorquere/zotero-better-bibtex#1496]
Hi, I encounter myself importing new references constantly during my research and writting process.
I add them one by one as I need them, and I make sure the information is correct and so on.
It would be awesome if there was a keyboard shortcut to just pin/unpin the keys so that they are generated with my settings.
By default they are pinned when imported.

Thanks,
camilo

**Comment by jcvtieck** [comment]
Sorry for spamming...
I just found Zutilo.
cool!

**Comment by retorquere** [comment]
If you're logged in when you create the issue you get the option to submit a question, and for those you don't get the request for a debug log.
