### ISSUE TITLE
Missing options for pull export?

### ISSUE THREAD

**Issue by fabbra** [retorquere/zotero-better-bibtex#1498]
The [documentation](http://retorque.re/zotero-better-bibtex/exporting/pull)  of the amazing pull export feature mentions two options: `exportNotes`, `useJournalAbbreviation`.
I am missing the other options available for Better BibTeX export (see image):

![image](https://user-images.githubusercontent.com/12109179/79751738-64fad980-8313-11ea-9649-18deb2b2fb68.png)

Are these options undocumented or simply not available?

**Comment by retorquere** [comment]
Technically, `exportNotes` and `useJournalAbbreviation` are export options, and these are already only applicable to specific imports. The screenshot you included shows preferences, and these are usually installation-wide. I have infrastructure in place for limited overrides per-export for these preferences, if you have an auto-export, you can see which those are. These overrides are somewhat complicated to implement, and every single option I add potentially doubles (or more if it's not a yes/no option) the memory use, so I don't add these lightly. But the ones I already have in the auto-export overview are feasible to add to the pull-export.

**Comment by fabbra** [comment]
Okay, thanks for clarification!

**Comment by retorquere** [comment]
I can actually add these, but I'll need to know of any of the settings in the AEs are useful to you.

**Comment by fabbra** [comment]
I had to put this on hold and find an alternative way to my solution (due to issues with getting the Zotero client running on my server generating the automated bibliography). 
I will get back to you once this gets more active again...

**Comment by retorquere** [comment]
Ok, we'll reopen when that happens.
