### ISSUE TITLE
protecting the journal field for latex macros in betterbibtex

### ISSUE THREAD

**Issue by NegriAndrea** [retorquere/zotero-better-bibtex#1499]
I am trying to export an item that has a latex macro (\mnras) inside the Publication field in Zotero. By using a postscript I am trying to protect the backslash, by performing a substitution of the entire journal field, in the same fashion as the one reported on the website for the math expressions in the title. It seems that the substitution does not work in 

item.publication.replace(/(\w.*)/g, '<script>{$1}</script>') 

**Report ID:**
HVFGAI93-euc
**Exporter used:**
BetterBibTex
**Expected behavior:**
@article{Andreon+2005,
  title = {Rigorous Luminosity Function Determination in the Presence of a Background: Theory and Application to Two Intermediate Redshift Clusters},
  author = {Andreon, S. and Punzi, G. and Grado, A.},
  year = {2005},
  month = jun,
  volume = {360},
  pages = {727--736},
  issn = {0035-8711, 1365-2966},
  doi = {10.1111/j.1365-2966.2005.09063.x},
  journal = {\mnras},
  language = {en},
  number = {2}
}
**Actual behavior:**
@article{Andreon+2005,
  title = {Rigorous Luminosity Function Determination in the Presence of a Background: Theory and Application to Two Intermediate Redshift Clusters},
  author = {Andreon, S. and Punzi, G. and Grado, A.},
  year = {2005},
  month = jun,
  volume = {360},
  pages = {727--736},
  issn = {0035-8711, 1365-2966},
  doi = {10.1111/j.1365-2966.2005.09063.x},
  journal = {\textbackslash{}mnras},
  language = {en},
  number = {2}
}

**Comment by retorquere** [comment]
That regex replacement is going to end up with `\<script>{mnras}</script>` being given to `add`, and that will indeed yield `\textbackslash{}mnras`. Try 

```
item.publication.replace(/(\\\w+)/g, '<script>{$1}</script>')
```

Not entirely sure why you'd want `\w.*`? That means "word character followed by all the rest of the input, whatever it is".

**Comment by NegriAndrea** [comment]
I'm far from being an expert of regex, I was trying to get the whole \mnras since there is only that in the publication field. But yes, in practice I would like to protect every latex command which is not inside $$.
I replaced the postscript with 

if (Translator.BetterTeX && reference.has.journal) {
reference.add({ name: 'journal', value: item.publication.replace(/(\\\w+)/g, '<script>{$1}</script>') });
}

but it still gives me the very same output.

**Comment by retorquere** [comment]
I'll need a new debug log with that postscript in place.

**Comment by retorquere** [comment]
Oh wait -- it's not the regex, it's `item.publication`. You'll want either one of these instead:

```
if (Translator.BetterTeX && reference.has.journal) {
  reference.add({ name: 'journal', value: reference.has.journal.value.replace(/(\\\w+)/g, '<script>{$1}</script>') });
}
```

or 

```
if (Translator.BetterTeX && reference.has.journal) {
  reference.add({ name: 'journal', value: item.publicationTitle.replace(/(\\\w+)/g, '<script>{$1}</script>') });
}
```

**Comment by retorquere** [comment]
The reason the earlier postscript still outputted something is that it errored out, and postscripts fail silently by default. If you don't want that, you can set the [hidden pref](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/) `ignorePostscriptErrors` to `false`. I have it set to `false` usually in my tests, that's how I found it now :)

**Comment by retorquere** [comment]
Does this answer your question?

**Comment by NegriAndrea** [comment]
It works beautifully! Perhaps some others are looking for this, it would be great to have it in the webpage.

**Comment by retorquere** [comment]
Done, but it'll take some 15 minutes to show up.
