### ISSUE TITLE
Long shot: add to the URL syntax to allow storing additional data

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#1502]
My use case is that I have a script which syncs my Zotero data across to DevonThink. I'd really love to be able to store the DevonThink UUID back with the Zotero item, and I suppose in general to have the option to store other random bits of data in the Zotero item too.

Is there a way to add this capacity to the http://127.0.0.1:23119/better-bibtex/… server?

I realise this has risks, but maybe if it were to be confined to key:value pairs to store in the extra field? Maybe with a custom- prefix to avoid splatting existing data?

**Comment by retorquere** [comment]
There is a way, but I don't think it fits well within BBTs functional scope. I could spin up a separate plugin to do this if you want.

**Comment by lyndondrake** [comment]
If you could that would be awesome. The dream for my use case would be to expose an AppleScript dictionary but I'm guessing a REST interface is a bit more cross-platform :-)

**Comment by retorquere** [comment]
I am not touching applescript with a 1000 feet pole.

**Comment by lyndondrake** [comment]
Fair enough :-)

It is a truly horrible scripting language to be fair. But if I can get some URLs working, I can use that to do the rest myself (sadly in AppleScript but that's the Mac world).

**Comment by retorquere** [comment]
How would you find the corresponding item in Zotero?

**Comment by lyndondrake** [comment]
In the BBT JSON, I can see `itemid` fields - I note that they are different to the Zotero Selector ids? I would assume the `itemid` is unique to the current library?

**Comment by retorquere** [comment]
BBT JSON normalizes the itemIDs so it's easier to compare two exports -- the BBT JSON format was created primarily for my test suite.

The itemIDs are indeed unique to the Zotero installation, across all libraries.

I'll have to think a bit how I can service both needs. I could perhaps do the normalization on the fly in my test suite instead of during export.

**Comment by retorquere** [comment]
A build will drop on #1505 in 10 minutes or so that will also reinstate the actual itemIDs.

Would it be OK of the method to add stuff to the extra field would look a little like the following?

You POST a javascript object looking like

```
{
   "1023": {"key1": "data1", "key2": "data2"}
}
```

then it would look up item 1023, remove lines starting with `key1:` and `key2:`, and add lines `key1:data1` and `key2:data2".

**Comment by retorquere** [comment]
It doesn't actually need a separate plugin.

If you install the [debug bridge](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge), the script at https://gist.github.com/6ab3cef48aeddee680a2be4a2a42c88a will modify the `extra` fields specified as above. The data can be piped in or given as a file parameter.

The README for debug bridge talks about visual studio code, you can just ignore that. The python script I linked to talks to the debug bridge directly.

**Comment by lyndondrake** [comment]
OK cool, I'm giving that a go. Works great from what I can see.

Am I right that I can also modify this to write more or less any field (I guess, any field that's writeable for a Zotero plugin)?

If so it opens up some cool possibilities. E.g. the data I pull in from my library has some predictable formatting oddities; I could use it to script the necessary changes to clean the format up.

(And looking through other issues, I've seen a few references to the XML-RPC bridge. I'm probably being a bit dim, but I can't seem to find the docs for the bridge, and I'm curious about it.)

**Comment by retorquere** [comment]
It can do absolutely anything that Zotero can do, up to and including hosing your database.

The JSON-RPC (I'm never touching XML-RPC again unless doing so pays for my kids college and my immediate retirement) interface has only just been documented, it will go up on the site when #1477 closes, but in the interim the general explanation is [here](https://github.com/retorquere/zotero-better-bibtex/blob/gh-1477/site/content/exporting/json-rpc.md) and the methods are listed [here](https://github.com/retorquere/zotero-better-bibtex/blob/gh-1477/site/layouts/shortcodes/json-rpc.md).

**Comment by lyndondrake** [comment]
That JSON-RPC bridge looks super useful. Given that I feel a little cautious about the risk of hosing my Zotero database, are you open to suggestions for functionality to add to the JSON-RPC bridge? Once that release is out of the way

**Comment by retorquere** [comment]
I add stuff to the json-rpc interface of they relate to BBT functionality, I don't want to have it devolve in a generalized zotero remote-access playground.

Hosing your database takes a bit of effort, it's not what's most likely to happen, but you do need to know a bit about how Zotero works, and if you do a "delete from item" sql query, zotero will dutifully oblige, and in my case I tried sticking urls which I knew weren't supported in the "related" table, and that broke syncing for me.

**Comment by lyndondrake** [comment]
OK, I'll stick to the debug bridge and will exercise great caution…

**Comment by retorquere** [comment]
I don't mind writing the occasional script for this. The one above should be safe, as it does very limited work.
