### ISSUE TITLE
Retrieve formatted-bibliography for a given citekey *without* the picker

### ISSUE THREAD

**Issue by scbarton** [retorquere/zotero-better-bibtex#1504]
I wonder if there is a way use the better-bibtex API to retrieve a `formatted-bibliography` by specifying a citekey, without using the picker. This would enable the building of complete bibliographies from a list of citekeys.

Sorry if I have overlooked something here.  Right now I'm doing that through BibDesk, but it would be great to only interface with Zotero.

**Comment by retorquere** [comment]
Yep, #1473, which I'll release somewhere in the next few days.

**Comment by scbarton** [comment]
Great, looking forward to it, and I'll be happy to test.  🎉
