### ISSUE TITLE
Add zotero selector URL to BBT JSON export

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#1505]
The Zotero selector URL (zotero://…) doesn't seem to be in the BBT JSON export - would it be ok to add it?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6435](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6435.xpi) ("validate lib against schema")

Install in Zotero by downloading [test build 5.2.21.6435](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6435.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you test 6435? I'm looking to cut a new release.

**Comment by lyndondrake** [comment]
Perfect. Thank you!

I note that the select URL isn't included for the attachments, but that's not particularly useful as I'd only really want to open the actual file rather than jump to the attachment item in Zotero.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6451](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6451.xpi) ("add select links to BBT JSON attachments")

Install in Zotero by downloading [test build 5.2.21.6451](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6451.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by lyndondrake** [comment]
Just tried it - looks like it works great. Thank you!

**Comment by richardkaplan** [comment]
Hi - could you please re-post the most recent test build, which has expired?  Thank you.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6505](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6505.xpi) ("locator for scannable cite")

Install in Zotero by downloading [test build 5.2.21.6505](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6505.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
