### ISSUE TITLE
Edition: converted from cardinal to text ordinal

### ISSUE THREAD

**Issue by longwayahead** [retorquere/zotero-better-bibtex#1508]
Hi, sorry if this isn't the right place to post this.

I have the following reference:
![image](https://user-images.githubusercontent.com/830052/80382143-d6013a80-8899-11ea-88d2-0faef7df438a.png)

Which gets exported by BBT as the following
![image](https://user-images.githubusercontent.com/830052/80382216-ee715500-8899-11ea-85be-06531973e287.png)

The edition field renders as "Second" with this reference preventing the biblatex-chicago from rendering the reference as "2nd ed.". Instead it renders it as "Second".

I don't see an option to set whether the ordinals are rendered as numbers or as text, and this seems to have cropped up only recently because it was exporting without problems a few months ago.

If you can help I'd really appreciate it. Thanks in advance

EDIT here's the debug report ZG7RJ479-euc

**Comment by longwayahead** [comment]
Pasing the debug id here
ZG7RJ479-euc

**Comment by longwayahead** [comment]
Sorry, I should add that when I manually change the .bib file to "2" instead of "Second" biblatex-chicago renders the reference correctly.

**Comment by retorquere** [comment]
But what you show above is a better bibtex export, not better biblatex.

**Comment by longwayahead** [comment]
Yep, better bibtex has been working for my setup. I haven't touched any of the configuration files but I've let zotero and BBT update. I was wondering whether something might have changed in the way editions were being exported?

I found issue 1446 which seems to have modified the way ordinals are set and also seems to be around the time when I started experiencing the different export behaviour.

Have I been doing something wrong?

**Comment by retorquere** [comment]
If you're using biblatex, you really should be exporting using "Better BibLaTeX" instead of "Better BibTeX". Both are bundled with BBT. You'll find that "Better BibLaTeX" exports the number, not the ordinal word. In many regards, bibtex should be seen as obsolete and replaced with biblatex, and you already appear to be using biblatex.

**Comment by longwayahead** [comment]
You're right: I had selected the wrong export option in the plugin and my export setup was living on borrowed time. Changed to export to BibLaTeX and it works perfectly again.

Thanks for your help and especially for BBT, great plugin!
