### ISSUE TITLE
Extract "Original date" from Extra

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#1510]
**Report ID:**
S6E2G4X7-euc

**Exporter used:**
Better BibLaTeX

**Expected behavior:**
Extract `Original date: 2019` from Extra filed to BibLaTeX `origdate`. 

**Actual behavior:**
Not extracted.

If I change the CSL key to `original-date: 2019`, it extracts to `origdate` as expected.

**Comment by bwiernik** [comment]
Here is Zotero's code for extracting variables entered with more readable capitalization and spaces, rather than all-lowercase and hyphens/underscores: https://github.com/zotero/zotero/blob/91ca6d2ba6cbe6256a0adc97f3d3de05a9bcb833/chrome/content/zotero/xpcom/cite.js#L320

**Comment by retorquere** [comment]
I'm working on this but it's taking a lot more time than I thought.

**Comment by retorquere** [comment]
The fix for this will also solve the underlying problem of #1471

**Comment by retorquere** [comment]
> Here is Zotero's code for extracting variables entered with more readable capitalization and spaces, rather than all-lowercase and hyphens/underscores: https://github.com/zotero/zotero/blob/91ca6d2ba6cbe6256a0adc97f3d3de05a9bcb833/chrome/content/zotero/xpcom/cite.js#L320

that says it's taken the transformation (at least partially) from https://aurimasv.github.io/z2csl/typeMap.xml which in turn was generated from the internal schema of Zotero 4.0.29.16 -- we have an ouroboros schema 😆

**Comment by retorquere** [comment]
This should now work.
