### ISSUE TITLE
Dateparser doesn't recognize 'de' in Spanish dates

### ISSUE THREAD

**Issue by Ypot** [retorquere/zotero-better-bibtex#1513]
**Report ID:**
SMCFGVUG-euc

Item Info:
Date: 26 de enero de 2009
No extra field

Keys generation:
[date=%oY] generates nothing in citation key
[date=%Y] generates correctly the Year (2009)

I think it neither exports correctly the "year" to the bibtex file.

**Comment by retorquere** [comment]
So there's two problems then? One is the citekey generation, one is specific to bibtex export? Or does it also affect biblatex export? I'm not sure which one you're using.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6489](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6489.xpi) ("fixes #1513")

Install in Zotero by downloading [test build 5.2.21.6489](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6489.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
This date is not going to be recognized properly by Zotero BTW. BBT has it's own dateparser which recognizes more dates (but the Zotero dateparser is faster). This date will now be correctly recognized by BBT, but zotero will not pick up the month.

**Comment by retorquere** [comment]
6489 should fix it.

**Comment by Ypot** [comment]
> 
> 
> 6489 should fix it.

It does!!!
Thanks.
