### ISSUE TITLE
Can I over override the original item type using extra field?

### ISSUE THREAD

**Issue by adalibas** [retorquere/zotero-better-bibtex#1516]
By default, Zotero contains very few item types compared to (for example) BibLatex. Similarly it contains very few field types but BBT solves some of that problem by allowing entering extra information in the extra fields.

However, I do not see any way of overriding value of the item type field in Zotero using that method. For example, Zotero does not have a item type for a full issue of a journal; but BibLatex has one. I do not mind that I have to see it as a book or magazine in the Zotero, but I would like to override that during export to bibtex.

Is there any way that I can do that?

(By the way, I sincerely and heartily thank you for all your great help to all researchers)

**Comment by adalibas** [comment]
Report id: 89EKFC9X-euc
This is a full issue of journal, as Zotero does not have a [Journal] item type,  it is stored as a [Journal Article] in Zotero in order to access fields [volume] and [issue]
I want to export this as a [periodical] for my biblatex entry.

**Comment by retorquere** [comment]
This is possible using `tex.referencetype: periodical` or `biblatex.referencetype: periodical` depending on whether you want to change the reference type for both bibtex and biblatex, or biblatex only.

**Comment by retorquere** [comment]
(and you're very welcome; it's always nice to hear it helps people)

**Comment by adalibas** [comment]
Thank you for the swift reply, and yes [tex.referencetype: periodical] works like a charm.
However, biblatex specifies that the tag "special issue" must go in the {note} field.
I tried [tex.note: special issue],then [tex.note= special issue], then [tex.note: {special issue}], and then [tex.note= {special issue}] and all the variations usign [biblatex.note ....] 
In none of the cases does BBT export a enrty containing a note field.

**Comment by retorquere** [comment]
You have `note` in your skipfields

**Comment by adalibas** [comment]
Oh, you are right!!!
I was using that option to block the unnecessary information entered to extra field by auto-import to Zotero, since extra field in zotero is translated to notes field in bibtex. And when I had code tex code in the extra field for some entries it had not interfered before. Which means that I have to exclude notes from my skipfields but more onerously I have to go through my library and delete any unnecessary  information in the extra field for any item.

**Comment by adalibas** [comment]
And thank you so much for your lightening fast replies and patience, and wonderful work!!

**Comment by retorquere** [comment]
I'm going to exclude extra to note export in an upcoming release.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.22.6527](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.22.6527.xpi) ("don't export extra if notes is off")

Install in Zotero by downloading [test build 5.2.22.6527](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.22.6527.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
