### ISSUE TITLE
Exporting error in obsolete version of BBt

### ISSUE THREAD

**Issue by Ann-Holmes** [retorquere/zotero-better-bibtex#1518]
**Report ID: C6V2R5A5-apse**

**Exporter used: Better BibLaTex**

**Expected behavior: Exporting successfully**

**Actual behavior: Warning info: An error occurred while trying to export the selected file.**

**Comment by retorquere** [comment]
I can't reproduce this from the reference in the debug log, and the error you are experiencing isn't in the log either. Can you upgrade to 5.2.22 (you're on 5.2.16), turn on debug output logging in the help menu, reproduce the problem, and then send a new debug log?

**Comment by Ann-Holmes** [comment]
> I can't reproduce this from the reference in the debug log, and the error you are experiencing isn't in the log either. Can you upgrade to 5.2.22 (you're on 5.2.16), turn on debug output logging in the help menu, reproduce the problem, and then send a new debug log?

Thanks!
It works when I upgrade to 5.2.22.
