### ISSUE TITLE
Hi! Why does it tell me the file is corrupt? 

### ISSUE THREAD

**Issue by catkinsonforsci** [retorquere/zotero-better-bibtex#1519]
**Report ID:**

**Expected behavior:**

**Actual behavior:**

**Comment by retorquere** [comment]
What platform are you on, and what browser did you use?

**Comment by catkinsonforsci** [comment]
Thank you for such a fast reply!! 🙂
I am using Firefox..I just found something that said I can't use it on Firefox? I am looking to make my bibliography in R Studio.
Thank you



________________________________

**Comment by retorquere** [comment]
Firefox is fine. Try right-click and save if you previously just clicked the download link - Firefox will think the extension is for Firefox and will try to install it and fail.

**Comment by retorquere** [comment]
assuming addressed.

**Comment by kindlychung** [comment]
This addon is for zotero, not for firefox. The .xpi extension might fool a lot of people.
