### ISSUE TITLE
Variables (page numbers etc) not appearing in Word

### ISSUE THREAD

**Issue by mcvmcvmcvmcv** [retorquere/zotero-better-bibtex#1528]
I'm following up on a question that I raised <a href="https://forums.zotero.org/discussion/comment/356620/#Comment_356620">on the Zotero forums</a>, because I found that variables like page numbers were not making it through to my Word document when I used the lua filter to keep the citations 'live' in Word. Please find my word doc attached. It's in a state before hitting document preferences so you can see the strings that got passed through.

[Text.docx](https://github.com/retorquere/zotero-better-bibtex/files/4666012/Text.docx)

**Comment by mcvmcvmcvmcv** [comment]
Report ID: LZ6R9CUU-apse

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.23.6583](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.23.6583.xpi) ("ncu")

Install in Zotero by downloading [test build 5.2.23.6583](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.23.6583.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Thanks for reporting this. Can you try 6583 with https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-1528/site/content/exporting/zotero.lua ?

**Comment by retorquere** [comment]
BTW, do you recall how you opened this issue? Were you logged in when you opened it? You should have been prompted to choose from 5 categories of issue types, and each should have added a label to the issue, but this issue wasn't labeled, and I've seen other that weren't labeled.

**Comment by retorquere** [comment]
Oh also: the config for this filter has changed; docs are temporarily up at https://github.com/retorquere/zotero-better-bibtex/blob/gh-1528/site/content/exporting/pandoc.md until I merge this.

**Comment by mcvmcvmcvmcv** [comment]
Hmm. Now the citations are just getting passed through as plain text. I wasn't sure what variable to put in the <code>library:</code> field, but I tried various things including leaving it blank, and nothing seemed to work. Passing along the md file I used (converted to txt). Was running this:

<code>pandoc -s --lua-filter=zotero.lua --reference-doc /Users/MYNAME/.pandoc/reference.docx -f markdown+smart -t docx -o /Users/MYNAME/Desktop/"$title".docx "$@"</code>
 
[Text.txt](https://github.com/retorquere/zotero-better-bibtex/files/4671684/Text.txt)

I got here from the <a href="https://retorque.re/zotero-better-bibtex/support/">'submit an issue' link on this page</a>.

**Comment by retorquere** [comment]
And you weren't prompted to choose an issue template? Strange.

Can you send a new debug log from 6583, selecting the references in that markdown file?

If these are items from your personal library, omit the library entirely; if it's from a group library, use the name of the library.

**Comment by retorquere** [comment]
I've replaced the citekeys that were in the document with some that happen to be in my test lib, bit after compilation, the text initially looks like

```
.... many hundreds of thousands of men were never more than instrumental?<open Zotero document preferences: [See also @Villagrasa; For another account of xyz, consult @biggs1996]>
Some text to make a footnote, hopefully...
```

Which is what I expect; after opening the Zotero document preferences and selecting a style (I usually go for APA) and clicking `OK`, the document now looks like:

```
... many hundreds of thousands of men were never more than instrumental?(For another account of xyz, consult Biggs, 1996; See also Villagrasa & Duran, 2013)
Some text to make a footnote, hopefully....
```

**Comment by mcvmcvmcvmcv** [comment]
Oops, I completely missed the part where I needed to install the new build :| Sorry about that. Everything is working perfectly well now, all the variables are passed correctly! Many thanks.

Yes, when I follow that link (https://github.com/retorquere/zotero-better-bibtex/issues/new) it lets me add a new issue without categorizing it.

**Comment by retorquere** [comment]
Cool thanks -- I'll merge and cut a new release.

Where did you get this link? The link on github itself is now https://github.com/retorquere/zotero-better-bibtex/issues/new/choose

**Comment by retorquere** [comment]
Ah, I see I had that on my site. That's fixed now, should be up in 20 minutes or so.
