### ISSUE TITLE
debug-bridge: passing parameters

### ISSUE THREAD

**Issue by stefanct** [retorquere/zotero-better-bibtex#1530]
I am misusing the debug-bridge a bit for some prototyping since it is the most workable way for me to edit JS code to be executed in Zotero (that I have found so far anyway). One thing I noticed that could be improved for the regular use case too is that it does not seem to be possible to pass parameters from the outside. I have tried the one obvious way that curl allows (i.e., adding another `--data-binary` argument), e.g., `curl -s -H "Content-Type: application/javascript" -X POST --data-binary @$js_file --data-binary "testvar=123" http://127.0.0.1:23119/debug-bridge/execute`.

That almost makes it to the final script but with the `&` from the encoding prepended, e.g., for an empty `$js_file` the call above logs the following:

    (3)(+0000002): debug-bridge: executing &testvar=123

    (3)(+0000001): debug-bridge failed (0ms): SyntaxError: expected expression, got '&'

    (5)(+0000001): HTTP/1.0 500 Internal Server Error X-Zotero-Version: 5.0.87 X-Zotero-Connector-API-Version: 2 Content-Type: application/text debug-bridge failed: SyntaxError: expected expression, got '&' init@chrome://zotero-debug-bridge/content/debug-bridge.js:33:24 Zotero.Server.DataListener.prototype._processEndpoint<@chrome://zotero/content/xpcom/server.js:524:26 tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16 module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18 module.exports/Promise.coroutine/<@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:201:9 Zotero.Server.DataListener.prototype._bodyData@chrome://zotero/content/xpcom/server.js:344:5 Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:316:5 Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:210:7

One might be able to hack around that by ending the JS file with something like `testvar="` and using `--data-binary "123\";"`or so but... BUT. ;)

This could facilitate testing by supplying external information to the script that it cannot receive otherwise.

**Comment by retorquere** [comment]
In the code that executing, there's an object called `query` that holds all url query parameters, so if you call `http://127.0.0.1:23119/debug-bridge/execute?par1=v1&par2=v2` you'd have the equivalent of having

```
let query = { par1: 'v1', par2: 'v2' }
```

at the top of the source.

**Comment by retorquere** [comment]
or to be precise: if you submit `return 'hello'`, the debug bridge wraps that as

```
async function(query) {
  return 'hello'
}
```

and then calls that function with the object holding the query parameters as the argument.

**Comment by stefanct** [comment]
Ah indeed. My JS skills are to poor to recognize the construction of the parameter of the callback (https://github.com/retorquere/zotero-better-bibtex/blob/4167e61948684930e58ab4c99cfb207ce7e6a846/test/fixtures/debug-bridge/content/debug-bridge.js#L33). Thanks a lot for the quick enlightenment (and the debug bridge)!

**Comment by retorquere** [comment]
No worries. Questions are free.
