### ISSUE TITLE
Field missing when exporting Item Type: Software as Better BibTex from Zotero

### ISSUE THREAD

**Issue by heinonmatti** [retorquere/zotero-better-bibtex#1532]
Hi,

I need to cite several R packages in my Rmd-document (to do this I'm using crsh/citr, which exports as Better BibTex). Lots of fields are missing, and the type says "misc". 

In other words, when I export Better BibTex, I get this:

> @misc{aust2020PapajaPreparingAPA,
>   title = {Papaja ({{Preparing APA Journal Articles}})},
>   author = {Aust, Frederik},
>   year = {2020},
>   collaborator = {Barth, Marius},
>   copyright = {View license}
> }

When I export as Better BibLaTex, I get:

> @software{aust2020PapajaPreparingAPA,
>   title = {Papaja ({{Preparing APA Journal Articles}})},
>   author = {Aust, Frederik},
>   date = {2020},
>   origdate = {2014-07-20T11:43:41Z},
>   url = {https://github.com/crsh/papaja},
>   urldate = {2019-04-04},
>   editora = {Barth, Marius},
>   editoratype = {collaborator},
>   version = {0.1.0.9942}
> }

... Which is what I need.

Is this a bug?

Matti

**Your question/suggestion:**

**Comment by retorquere** [comment]
It's not a bug; biblatex supports different/more fields and entrytypes than bibtex does (which is why BBT offers them both). You'll have to ask the citr author to request biblatex instead of bibtex from BBT.

**Comment by retorquere** [comment]
OTOH if there are sensible bibtex mappings for the data you need I'll be happy to add those to the bibtex export.

**Comment by heinonmatti** [comment]
I'm a bit unsure what "sensible bibtex mappings" means. It would be great if the export included at least the version number and url, prefereably also programming language.

**Comment by retorquere** [comment]
Sensible meaning that it is a field usually picked up by existing bibtex styles.

It still looks to me like you'd be better helped with the biblatex export. May I ask why you prefer bibtex over biblatex, when biblatex has the fields you want?

**Comment by retorquere** [comment]
`url` isn't a supported field in bibtex for example - urls are generally encoded as verbatim, and that will more likely than not either error out in bibtex, or give strange results. I really do think that you want biblatex, which does support `url`. You can have BBT output the url in an `url` field in the preferences, but the caveat applies - the results may be unpredictable.

**Comment by retorquere** [comment]
Wouldn't it just work if you set `betterbiblatex_format` to biblatex in citr?

**Comment by retorquere** [comment]
Hello?

**Comment by retorquere** [comment]
closing for lack of feedback
