### ISSUE TITLE
Date Added field not available for citekey although it was in the past

### ISSUE THREAD

**Issue by rasmuse** [retorquere/zotero-better-bibtex#1534]
Thanks for the great software.

I am running latest Zotero and latest BBT (5.2.25).

**Report ID:**

YPBI8MST-euc

**Expected behavior:**

`[auth][year]-[dateAdded]` or `[auth][year]-[DateAdded]` should be a valid citekey format as it has been in the past.

**Actual behavior:**

`[auth][year]-[dateAdded]` and `[auth][year]-[DateAdded]` are not accepted as citekey formats.

**Further explanation**

I have been using the Date Added field in my citation keys for several years. This has worked well for me to keep my citation keys stable. I have been using the citekey pattern `[auth][year]-[DateAdded]` to obtain citekeys like `Einarsson2019-2019-04-0109:16:14`. I figured this would be a nice citekey pattern that would be stable through various types of changes and regeneration of citekeys.

However I just noted that my BBT settings no longer have that citekey but simply `[auth][year]` and that adding `[DateAdded]` or `[dateAdded]` is not possible. The input field for the citation key turns orange to indicate it's not a valid citekey format.

The latest added reference in my library that has successfully generated a key using DateAdded is from 2020-05-05. The next reference was added 2020-05-12 without DateAdded and so I guess I made a version upgrade of Zotero and/or BBT between those dates that disabled this feature, but unfortunately I cannot remember which one(s) I updated. I do usually upgrade Zotero and BBT as soon as prompted to do so (e.g., when new translators are released).

**Edit**

Added debug report after restarting Zotero.

**Comment by rasmuse** [comment]
Thanks for the helpful bot reply. I have now edited my report above with the debug report id YPBI8MST-euc .

**Comment by retorquere** [comment]
Thank -- but I need a debug log as per point 1. YPBI8MST-euc was sent from the help menu, as per point 2.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.25.6625](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.25.6625.xpi) ("fixes #1534")

Install in Zotero by downloading [test build 5.2.25.6625](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.25.6625.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 6625?

**Comment by rasmuse** [comment]
Yes, it works!

Thank you for the extremely fast feedback and resolution, and apologies for sending the wrong type of debug report.

Closing the issue as my problem is resolved and I suppose this will released in a future version.

**Comment by retorquere** [comment]
I'll cut a new release somewhere today.

**Comment by rasmuse** [comment]
This problem is back in the latest version (5.2.46), and I think earlier too, although I have not pinned down exactly which version(s) work and which don't. I installed the test build (6625) that you created on June 1st, and today when I opened Zotero it was auto-updated and said that it removed a citekey format containing the invalid `DateAdded`.

Maybe the solution to my issue was never merged into the main branch? Or maybe it reappeared for some other reason?

Here is a reference-specific debug report: EWDYFBRX-euc

Grateful for any input. Thanks again for the great software!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.46.6847](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.46.6847.xpi) ("fixes #1534")

Install in Zotero by downloading [test build 5.2.46.6847](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.46.6847.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by rasmuse** [comment]
Build 6847 works! Thank you.

**Comment by retorquere** [comment]
Thanks for the confirmation, I've cut a new release
