### ISSUE TITLE
stars and brackets in fields are kept even with :clean filter

### ISSUE THREAD

**Issue by 8hur** [retorquere/zotero-better-bibtex#1535]
Hi, thanks for the extension.

I probably have quite a unique setup and I'm not absolutely certain I've missed something.
I use the "journal" (when available) field in my citation keys and use the clean: filter to edit the field.
The CSL json is then parsed by https://github.com/Zettlr/Zettlr which might use some pandoc related function.
The journal field however sometime contains characters such as stars (*) or brackets ([ ]) and theses characters are kept in the citation keys ... which throws an error in the software down the line.

I was wondering if keeping these characters while the clean function is intended and if so, is there a way around it?

**Comment by retorquere** [comment]
But if I had to take a guess, using `alphanum` instead of `clean` might do the job for you.

**Comment by 8hur** [comment]
> But if I had to take a guess, using `alphanum` instead of `clean` might do the job for you.

Indeed, it solved it! I guess I missed the filter when I read the documentation. Thanks a lot.
