### ISSUE TITLE
Auto Exporting not staging and pushing bib with git

### ISSUE THREAD

**Issue by clairekope** [retorquere/zotero-better-bibtex#1536]
**Report ID:** 692E5RD3-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:**
Auto export should be pushing the newly exported bib to Overleaf automatically.

**Actual behavior:**
Modified bib files show as unstaged in the output directory and was not pushed to Overleaf. Credentials have been stored so that pulls and pushes should be able to proceed automatically.

Log indicates that Better BibTeX thinks the extension is not enabled?
`(3)(+0000001): {better-bibtex +1} git.pull {"enabled":false,"git":null} `
Even though it is:
```$ git config -l
push.default=simple
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://git.overleaf.com/5de56c54c5f3a3000196ff4f
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
credential.helper=store
zotero.betterbibtex.push=true
````

**Comment by retorquere** [comment]
It looks like the git executable is not in the `$PATH` that's available to Zotero. Can you go to `Help` -> `Debug Output Logging` -> `Restart with logging enabled`, let Zotero restart, and then send a new BBT log from the `Help` menu?

**Comment by clairekope** [comment]
Interesting, because it's in /usr/bin (at least that's the one that is
being used when I use the command line). The new log is D801701768

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by retorquere** [comment]
That's a zotero log, I can't access those. I need a bbt debug log. Those always end in -euc or -apse.

**Comment by clairekope** [comment]
Whoops, the report # is 3W8BQH92-euc

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by retorquere** [comment]
As far as Zotero knows, the `$PATH` is `/app/bin:/usr/bin`

**Comment by retorquere** [comment]
How did you install Zotero?

**Comment by clairekope** [comment]
I believe I installed it from the package installer built into Linux Mint

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by retorquere** [comment]
That likely means it's a snap package. Those are very restricted in what binaries they can see.

**Comment by clairekope** [comment]
Ah, ok. Should I reinstall from the Zotero website then?

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by retorquere** [comment]
It should be possible to configure a snap to get access to more paths.

The zotero binaries from the official downloads will work but there is some (very little) extra work you need to do to get launcher integration done. It's well documented on the zotero site.

Alternately, there's these: https://github.com/retorquere/zotero-deb. There's a one-time setup for that but the desktop integration stuff is done by the packager.

**Comment by retorquere** [comment]
No wait, you're more likely to have a flatpacked install. Mint had some philosophical objections to snap, and I see you're on Zotero 5.0.86, and flatpack is currently one release behind, so that'd fit.

I'm not familiar with either unfortunately. I obviously know zotero-deb -- I created the package -- but stuff that comes with your distro probably has your preference. You'd have to ask the flatpack project or mint how to add path access to flatpacks -- I have no idea how they work.

**Comment by clairekope** [comment]
Thank you for the information! I will look into it. I think this issue can
now be closed, as the problem is on my end.

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.26.6634](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6634.xpi) ("really should be found? flatpacks are weird")

Install in Zotero by downloading [test build 5.2.26.6634](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6634.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Could you give 6634 a try nonetheless?

**Comment by clairekope** [comment]
Exported bib shows as unstaged; report ZRSXCMC8-euc

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.26.6637](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6637.xpi) ("more logging")

Install in Zotero by downloading [test build 5.2.26.6637](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6637.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you give it one more go with 6637?

**Comment by clairekope** [comment]
Sure thing! New log is IK35KK9Y-euc

Claire Kopenhafer
she/her
Graduate Student
Physics & Astronomy; Computational Math, Science, & Engineering
Michigan State University

**Comment by retorquere** [comment]
I got the logging wrong. I need to turn in now as I have an early start tomorrow, but a new build will drop here in 20 minutes or so -- I will be back around noon tomorrow and then I can take a further look.

**Comment by clairekope** [comment]
Ok; I'm happy to debug if you are committed to making this work but I was
able to get it working with the install from the website

-Claire

**Comment by retorquere** [comment]
Naah, I wouldn't have you install the flatpack just for this. Glad you got it work.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.26.6640](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6640.xpi) ("the comma is not optional my man")

Install in Zotero by downloading [test build 5.2.26.6640](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6640.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
