### ISSUE TITLE
Better-bibtex won't install

### ISSUE THREAD

**Issue by alisonketz** [retorquere/zotero-better-bibtex#1537]
When I try to install better bibtex, I get the following error: The add-on "Better BibTex for Zotero" could not be installed. It may be incompatible with this version of Zotero.

What versions of zotero is better bibtex compatible with? I couldnt find this on the website. I have updated my zotero application to 5.0.60, which is the latest version available for linux. I am running Ubuntu 16.04. Maybe I need to run an older version of zotero? If that's the case, what version?

**Comment by alisonketz** [comment]
Here is the bug Debug report generated ID # 1889323388

**Comment by alisonketz** [comment]
oops, here is the Debug ID: D790911852

**Comment by retorquere** [comment]
The latest version for Linux is 5.0.78. You may have installed Zotero from the smathot PPA, which has stopped releasing updates a long time ago.

If this is indeed the case, you would need to uninstall zotero, remove the smathot repo from /etc/apt, and either install the zotero binaries from https://www.zotero.org/download/ manually, install the apt repo from https://github.com/retorquere/zotero-deb (which I keep updated), or the snap/flatpack packages (at least I think those are available, but I have no experience with these).

Uninstalling and reinstalling will not affect your zotero library.

**Comment by alisonketz** [comment]
Thanks Emiliano! 

Although I thought that I had installed zotero from the zotero website directly using their tarball... I had previously installed it using the cogscinl ppa from a few years ago - and because I had not uninstalled that ppa, the fresh installation that I thought I had done, well, it didn't work. Deleting the ppa, subsequent uninstalling zotero, and reinstalling using your link worked like a charm. Again, thanks for your help!
