### ISSUE TITLE
Unicode "ø" in author name is exported with trailing space which does not work in bibtex

### ISSUE THREAD

**Issue by henrikh** [retorquere/zotero-better-bibtex#1538]
**Report ID:** G6NWLYL4-euc

**Exporter used:** betterbibtex

**Expected behavior:** "ø" is exported as `{\o}` making spacing right.

**Actual behavior:** "ø" is exported `\o `. Which doesn't work in MiKTeX as per #69

**Comment by retorquere** [comment]
Sorry about that. I'll get you a fix in the weekend. Maybe tonight, but that I can't promise.

**Comment by retorquere** [comment]
Not that this will stand in the way of that fix on the BBT end, but is this not something that MiKTeX intends to fix? It's a little strange I think. Is this discussed for MiKTeX somewhere?

**Comment by henrikh** [comment]
No need to rush for my sake :) I'll perhaps just switch to TeXLive to handle it.

I'll see how to make a bug report to MiKTeX.

**Comment by retorquere** [comment]
This weekend is doable. I know what I have to do, I just need an hour to modify the tests mostly.

**Comment by retorquere** [comment]
Is this bibtex specific? Or is biblatex affected too in MikTeX?

**Comment by retorquere** [comment]
And this is specific to author names? Other fields like titles are not affected?

**Comment by henrikh** [comment]
I’m not sure.

I can test it more thoroughly tomorrow.

**Comment by henrikh** [comment]
I've made a minimal example which exhibits the desired behavior on my computer _and_ on Overleaf: link is here: https://www.overleaf.com/read/csphznvkznyx

I think it is a bibtex/bibliography issue and not BetterBiblatex, but as seen simply having `\o ` will not work in one scenario. It is only on the author name when the format `last, first` is used in the author list.

**Comment by henrikh** [comment]
A temporary workaround is to set BBT to export unicode -- that seems to work fine.

I also checked the file generated by bibtex. It is bibtex which inserts a non-breaking space.

**Comment by retorquere** [comment]
OK, so if I'm reading this sample correctly, this problem is particular to bibtex author names (when the author names are written as Family, Given). This is great news, because I already treat bibtex author names differently for other reasons, so this can be a very localized fix.

What I had absolutely not expected is that this:

```
 author = {S\o{}ren, Space}
```

*also* inserts a space there, and that is, as far as I'm concerned, unequivocally wrong.

But if I interpret this sample correctly (that this problem is restricted to bibtex, not biblatex, author names), then that's an easy fix. I'm working on the implementation, but it'd be great to get your confirmation on that.

As an aside, you can construct such MWEs as a single file:

```
\documentclass{article}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@inproceedings{ABC,
  title = {A\o c {A\o c} A{\o}c},
  author = {S\o{}ren, Space and {S\o ren}, Enclosed and S{\o}ren, Unit and Søren, Unicode and Normal S\o ren},
  year = {2020},
  pages = {2},
  lccn = {abc}
}
\end{filecontents*}

\begin{document}

s\o s\cite{ABC}

\bibliographystyle{plain}
\bibliography{\jobname}

\end{document}
```

**Comment by retorquere** [comment]
The test suite is running and a build will drop here in 15 minutes or so.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.26.6647](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6647.xpi) ("two-stage tests")

Install in Zotero by downloading [test build 5.2.26.6647](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.26.6647.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 6647?

**Comment by henrikh** [comment]
Amazing! @retorquere I just tested it and it seems to work perfectly!

**Comment by retorquere** [comment]
So fixed? This change *only* affects creator fields (author, editor, etc), for bibtex, not biblatex. All other circumstances use to regular latex generation with spaces to end commands when followed by text.

**Comment by henrikh** [comment]
I've only found it to affect author field. I suspect that it is a bug when bibtex reorders to first and last name. At least when I dig into the bibtex output, that seems to be the case.

Also, one small request, in these two files could you remove the "note" field from these example bibliography entries:

https://github.com/retorquere/zotero-better-bibtex/compare/gh-1538#diff-f359c9dc6c670e83bc2fca2f7e1995b9

https://github.com/retorquere/zotero-better-bibtex/compare/gh-1538#diff-d9d84ebbe604d3e4c380d4409dd76d4a

I didn't notice that it was included in the delivered output from Zotero.

**Comment by retorquere** [comment]
That's only because I have the ["export notes" option on](https://github.com/retorquere/zotero-better-bibtex/compare/gh-1538#diff-d9d84ebbe604d3e4c380d4409dd76d4aR7) during that export. If it's off, those don't appear.

**Comment by retorquere** [comment]
I'd still say this is a bug in bibtex, but since I already treat bibtex creator names differently, I'm happy to release this.

**Comment by henrikh** [comment]
Thanks! And thanks for being super helpful :) Just tell me if there is something else I can help with :)

**Comment by retorquere** [comment]
Nope, that should be it, I'm prepping a new release

**Comment by Edmundod** [comment]
I'm experiencing the same problem with polish letter ł. Let's consider a name Michał Truchło, exported to bib file it becomes `Truch\l o, Micha\l{}`, which gives `M. Truchł o`. It looks like a surname is not processed correctly. On the other hand for name Paweł I have both `Pawe\l` and `Pawe\l{}` in different references, so tbh I'm a little bit lost.

**Comment by retorquere** [comment]
@Edmundod if you have this issue with 5.2.28, I'll need a debug log.

**Comment by Edmundod** [comment]
Indeed, I had 5.2.26, but with 5.2.28 it is working perfectly. Sorry for the trouble and thank you for your work :)

**Comment by retorquere** [comment]
That's alright, thanks for letting me know.
