### ISSUE TITLE
Do not export subcollection items

### ISSUE THREAD

**Issue by alekhe** [retorquere/zotero-better-bibtex#1539]
**Your question/suggestion:**

When I export a collection which has a subcollection, the .bib file contains all items from the subcollection. Is it possible not to export subcollection items?

I use “Export” with “Better BibTeX.”

**Comment by retorquere** [comment]
You'd have to ask Zotero. Exporters can't see whether you exported a collection or you just selected a bunch of items and exported those, they just get a list of items to export.

**Comment by alekhe** [comment]
Understood. Thank you.
