### ISSUE TITLE
import software related biblatex entries

### ISSUE THREAD

**Issue by rdicosmo** [retorquere/zotero-better-bibtex#1544]
**Report ID: RUG7Z4YB-euc**

**Full Bib(La)TeX item you are trying to import:**
```
@SOFTWAREVERSION{delebecque:hal-02090402-condensed,
  ABSTRACT = {Software for Numerical Computation freely distributed.},
  AUTHOR = {Delebecque, Fran{ç}ois and Gomez, Claude and Goursat, Maurice and Nikoukhah, Ramine and Steer, Serge and Chancelier, Jean-Philippe},
  INSTITUTION = {Inria},
  LICENSE = {Scilab license},
  URL = {https://www.scilab.org/},
  DATE = {1994-01},
  FILE = {https://hal.inria.fr/hal-02090402/file/scilab-1.1.tar.gz},
  HAL_ID = {hal-02090402},
  HAL_VERSION = {v1},
  NOTE = {First Scilab version. It was distributed by anonymous ftp.},
  REPOSITORY = {https://github.com/scilab/scilab},
SWHID={swh:1:dir:1ba0b67b5d0c8f10961d878d91ae9d6e499d746a;origin=https://hal.archives-ouvertes.fr/hal-02090402},
  TITLE = {Scilab},
  VERSION = {1.1},
}

@SOFTWARE{delebecque:hal-02090402,
  ABSTRACT = {Software for Numerical Computation freely distributed.},
  AUTHOR = {Delebecque, Fran{ç}ois and Gomez, Claude and Goursat, Maurice and Nikoukhah, Ramine and Steer, Serge and Chancelier, Jean-Philippe},
  INSTITUTION = {Inria},
  LICENSE = {Scilab license},
  URL = {https://www.scilab.org/},
  DATE = {1994},
  HAL_ID = {hal-02090402},
  HAL_VERSION = {v1},
  REPOSITORY = {https://github.com/scilab/scilab},
  TITLE = {Scilab},
}

@SOFTWAREVERSION{delebecque:hal-02090402v1,
  CROSSREF = {delebecque:hal-02090402},
  DATE = {1994-01},
  FILE = {https://hal.inria.fr/hal-02090402/file/scilab-1.1.tar.gz},
  NOTE = {First Scilab version. It was distributed by anonymous ftp.},
SWHID={swh:1:dir:1ba0b67b5d0c8f10961d878d91ae9d6e499d746a;origin=https://hal.archives-ouvertes.fr/hal-02090402},
  VERSION = {1.1},
}

@SOFTWARE{cgal,
  AUTHOR = {{The CGAL Project}},
  EDITOR = {{CGAL Editorial Board}},
  URL = {https://cgal.org/},
  DATE = {1996},
  TITLE = {The Computational Geometry Algorithms Library},
}

@SOFTWAREVERSION{cgal:5-0-2,
  URL = {https://docs.cgal.org/5.02},
  CROSSREF = {cgal},
  DATE = {2020},
SWHID={swh:1:rel:636541bbf6c77863908eae744610a3d91fa58855;origin=https://github.com/CGAL/cgal/},
  VERSION = {{5.0.2}},
}

@SOFTWAREMODULE{cgal:lp-gi-20a,
  AUTHOR = {Karavelas, Menelaos},
  LICENSE = {GPL},
  URL = {https://doc.cgal.org/5.0.2/Manual/packages.html#PkgVoronoiDiagram2},
  CROSSREF = {cgal:5-0-2},
  INTRODUCEDIN = {cgal:3-1},
  SUBTITLE = {{2D} Voronoi Diagram Adaptor},
}

@SOFTWAREMODULE{cgal:lp-gi-20a-condensed,
  AUTHOR = {Karavelas, Menelaos},
  EDITOR = {{CGAL Editorial Board}},
  LICENSE = {GPL},
  URL = {https://doc.cgal.org/5.0.2/Manual/packages.html#PkgVoronoiDiagram2},
  DATE = {2020},
  INTRODUCEDIN = {cgal:3-1},
  SUBTITLE = {{2D} Voronoi Diagram Adaptor},
SWHID={swh:1:rel:636541bbf6c77863908eae744610a3d91fa58855;origin=https://github.com/CGAL/cgal/},
  TITLE = {The Computational Geometry Algorithms Library},
  VERSION = {{5.0.2}},
}

@SOFTWARE{parmap,
  AUTHOR = {Di Cosmo, Roberto and Danelutto, Marco},
  INSTITUTION = {Inria and University of Paris and University of Pisa},
  LICENSE = {LGPL-2.0},
  URL = {https://rdicosmo.github.io/parmap/},
  DATE = {2020},
  REPOSITORY = {https://github.com/rdicosmo/parmap},
  TITLE = {The Parmap library},
  VERSION = {1.1.1},
}

@CODEFRAGMENT{simplemapper,
  CROSSREF = {parmap},
  SUBTITLE = {Core mapping routine},
SWHID={swh:1:cnt:43a6b232768017b03da934ba22d9cc3f2726a6c5;lines=192-228;origin=https://github.com/rdicosmo/parmap},
}
```
**Expected behavior:**

Since Zotero has a Software category, these entries should be at least imported as Software, while waiting for a more refined Software taxonomy to find its way in Zotero

**Actual behavior:**

All entries are imported as "Journal Article", here are the import errors shown in Zotero

Import errors found:

    Don't know what Zotero type to make of 'softwareversion' for @delebecque:hal-02090402-condensed, importing as journalArticle
    Don't know what Zotero type to make of 'software' for @delebecque:hal-02090402, importing as journalArticle
    Don't know what Zotero type to make of 'softwareversion' for @delebecque:hal-02090402v1, importing as journalArticle
    Don't know what Zotero type to make of 'software' for @cgal, importing as journalArticle
    Don't know what Zotero type to make of 'softwareversion' for @cgal:5-0-2, importing as journalArticle
    Don't know what Zotero type to make of 'softwaremodule' for @cgal:lp-gi-20a, importing as journalArticle
    Don't know what Zotero type to make of 'softwaremodule' for @cgal:lp-gi-20a-condensed, importing as journalArticle
    Don't know what Zotero type to make of 'software' for @parmap, importing as journalArticle
    Don't know what Zotero type to make of 'codefragment' for @simplemapper, importing as journalArticle

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.30.6671](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.30.6671.xpi) ("basic software import")

Install in Zotero by downloading [test build 5.2.30.6671](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.30.6671.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6671 will import these types as Software, but may not yet give the exact desired results. It'd be helpful if you could install 6671, import the items above, correct the imported items to what you think they should be, select these items and send a new debug log from the right-click menu.

**Comment by rdicosmo** [comment]
Excellent, this version does the import. I submitted a suggestion for improvement via
UR99RWLV-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.30.6681](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.30.6681.xpi) ("fixes #1544")

Install in Zotero by downloading [test build 5.2.30.6681](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.30.6681.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Does 6681 doe what you want?

**Comment by rdicosmo** [comment]
> Does 6681 do what you want?

Yes, that works quite fine!

I do not see how one could do better using the existing fields in CSL : it is really not clear where to put the extra software bib(la)tex fields like repository, swhid, etc.  so for the moment it's quite fine to keep them in the extra field as BBT does.

Thanks a lot for making this change.

**Comment by retorquere** [comment]
Superb, I'll merge this into a release tonight. Anything else you need I'll be happy to discuss.
