### ISSUE TITLE
Error saying this add-on is incompatible with Zotero 5.0.75

### ISSUE THREAD

**Issue by atreyagagan** [retorquere/zotero-better-bibtex#1548]
I have been using this add-on for a few years without any problems, but it has stopped working after the latest Zotero update. So I removed it and re-downloaded the xpi file and tried to install it, but I get an error. 

OS: Arch Linux 5.7.2 with i3 windows manager. 
Zotero version: 5.0.75

I get this error when I try to install the xpi:

![a](https://user-images.githubusercontent.com/13967245/85218333-fbbd3400-b35e-11ea-96f8-3413b6faadb2.png)

**Comment by retorquere** [comment]
You need to be on at least zotero 5.0.77 for BBT to work, and I can only provide support for the latest Zotero version (5.0.88 at time of writing).

**Comment by retorquere** [comment]
For completeness sake 5.0.75 is not the latest Zotero update, it's 11 versions behind latest, and 5.0.75 was released in Oct 2019. How do install zotero? It should have automatically updated to latest long ago.

**Comment by retorquere** [comment]
And from the looks of it, arch has 5.0.88 available.

**Comment by atreyagagan** [comment]
Thank you, updating my zotero did it! Sorry about the confusion.
