### ISSUE TITLE
Copy CiteKey option in BBT context menu 

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#1551]
Hi Emiliano, 

first, thank you for the hard work and the continuous improvement of BBT. It is such an indispensable tool!

I have a suggestion, which if you have time, you can see will it be useful for the others and decide will you make it. 

Sometimes, when I find a reference in Zotero I want to copy the BBT Citekey so I can add it in some text editor. Is it possible in  BBT context menu to have an option for copying the citekey with some prefix and suffix? For example citekey mijalche.07 to be copied as [@mijalche.07]. Zotero has someting like Copy Citation. Thus this can be called Copy CiteKey.

One more time thank you and have a nice day
Mijalche

**Comment by retorquere** [comment]
Does [this](https://retorque.re/zotero-better-bibtex/citing/#drag-and-drophotkey-citations) suffice for what you need?

**Comment by mijalche** [comment]
Yes, that is the perfect solution. I was not aware about it, sorry and thank you!
Have a nice day

**Comment by retorquere** [comment]
No worries, asking is always OK.
