### ISSUE TITLE
[Enhancement/Question] Auto pin citation keys

### ISSUE THREAD

**Issue by f-brinkmann** [retorquere/zotero-better-bibtex#1552]
Again, thanks for the great work! I would love to see an option in the BBT preferences to automatically pin the generated citation keys on import (or export).

I saw that this was dropped in Zotero-5, probably for a good reason (https://github.com/retorquere/zotero-better-bibtex/issues/875). So please just close the request, if this is not possible...

**Comment by retorquere** [comment]
On import is already possible: https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopin

**Comment by f-brinkmann** [comment]
thx - activated :)
