### ISSUE TITLE
Format disambiguations

### ISSUE THREAD

**Issue by tillheilmann** [retorquere/zotero-better-bibtex#1554]
The pseudo-function 0 does not accept filters like :replace to change the delimiter for added disambiguation numbers (-1, -2, ...).

I have managed to replicate my usual pattern for manually generated citation keys in my 2000+ entries Bib(La)TeX database using this expression:

[authors1:lower:select=1,1][authForeIni:lower:prefix=.][authors1:lower:select=2,1:replace=etal,ea:prefix=.][year:prefix=:][0]

Now, if there was a way to change the delimiting dash to a period, I would be 99% there. :-)

BTW: Fantastic piece of software, thank you! Keep up the great work.

**Comment by tillheilmann** [comment]
debug id: S3JBY3NH-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.34.6698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.34.6698.xpi) ("excel column")

Install in Zotero by downloading [test build 5.2.34.6698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.34.6698.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
If you install 6698, you can now add a block `[postfix=.%(n)s]`, which will set the disambiguation postfix using a [sprintf-js](https://www.npmjs.com/package/sprintf-js) spec. 3 named placeholders are supported:

* `%(n)s`: numeric
* `%(a)s`: alphabetic (lowercase)
* `%(A)s`: alphabetic (uppercase)

Go wild.

This is still a pseudo-function -- it doesn't actually add anythin to the citekey, it just tells BBT what to add should it be needed. It doesn't matter where you have it, the results (if anything) will always appear at the end. `[0]` is now just an alias for `[postfix=-%(n)s]`.

**Comment by retorquere** [comment]
@franvillamil, you can try this build with `[postfix=%(a)'a2s]`

**Comment by retorquere** [comment]
I really need feedback. I'm about to merge a big change, and it'd be a lot less work for me if I could merge this first.

**Comment by tillheilmann** [comment]
Maybe I don't understand how to use it correctly, but this (with build 6698)

[auth:condense:lower:clean:nopunctordash][authForeIni:prefix=\.:lower][authors1:prefix=\.:condense:lower:select=2,1:replace=etal,ea][year:prefix=\:][postfix=.%(n)s]

gives me the year twice, as in

baudrillard.j:1978:1978.1

for example.

**Comment by retorquere** [comment]
I'll need a debug log for that.

**Comment by tillheilmann** [comment]
MZ38MBEV-euc

**Comment by retorquere** [comment]
New build coming up. 

`[auth:condense]` and `[authors1:prefix=\.:condense]` won't do what you want BTW. `auth` and `authors1` will have `condense` applied already, so `auth:condense` is equivalent to just `auth`, and since `authors1` is already condensed when it reaches `select`, it will always look like a single word to `select`. You'll want to play with the captitalized `Auth` and `Authors`, which preserve spaces to break up words.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.34.6710](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.34.6710.xpi) ("fix test case")

Install in Zotero by downloading [test build 5.2.34.6710](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.34.6710.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by franvillamil** [comment]
> @franvillamil, you can try this build with `[postfix=%(a)'a2s]`

Just installed 6710, and the double postfix works (have the same duplication issue as @tillheilmann with 6698). It is still not what I was trying to do (include `aa` postfix in all references, and change to `ab` in case there two double references), but it was just a matter of replicating the key format I had in BibDesk in case it was straightforward. So I guess it probably makes more sense to just update all my references in .tex files, which shouldn't be a huge issue anyway. Thanks for looking into this!

**Comment by retorquere** [comment]
@franvillamil if you still experience the double postfix, I'll want to fix that, but to fix these things, I need a debug log. `postfix=%(a)'a2s]` should get you `aa`, `ab`, etc, because that means `alpha disambiguation, right-justify and fill out with `a` up to two places.

**Comment by retorquere** [comment]
> include `aa` postfix in all references, and change to `ab`

Ah wait I understand. I can fix that if you want.

**Comment by retorquere** [comment]
Ugh wait reading comprehension is a thing. It works as you want but you want to start at `aa`. That's doable. Let me know if you'll be willing to test it, then I'll build it.

**Comment by retorquere** [comment]
A new build will drop here soon, and then `[postfix+1=%(a)'a2s]` will work. It just means that it will start counting at 1 rather than 0; currently, only `+1` or nothing (meaning start at 0) are supported.

**Comment by franvillamil** [comment]
> A new build will drop here soon, and then `[postfix+1=%(a)'a2s]` will work. It just means that it will start counting at 1 rather than 0; currently, only `+1` or nothing (meaning start at 0) are supported.

That's great, I'll test the new build as soon as it's ready. Just in case you need it, debug ID: `NVUNR67V-euc`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.34.6714](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.34.6714.xpi) ("+1")

Install in Zotero by downloading [test build 5.2.34.6714](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.34.6714.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by franvillamil** [comment]
@retorquere Just tried 6714, it works great!

**Comment by retorquere** [comment]
Alright, a new release build is running through the tests.

**Comment by tillheilmann** [comment]
> New build coming up.
> 
> `[auth:condense]` and `[authors1:prefix=\.:condense]` won't do what you want BTW. `auth` and `authors1` will have `condense` applied already, so `auth:condense` is equivalent to just `auth`, and since `authors1` is already condensed when it reaches `select`, it will always look like a single word to `select`. You'll want to play with the captitalized `Auth` and `Authors`, which preserve spaces to break up words.

This seems not right for `authors1`. I use the expression `[authors1:prefix=\.:condense:lower:select=2,1:replace=etal,ea]` to produce the string "ea" only (!) for titles with two or more authors. If I drop the `:condense` filter from this expression, then it generates the second part of the author's last name *if* this last name is of the kind "de Saussure".

**Comment by retorquere** [comment]
Can you send me a debug log for that item?

**Comment by retorquere** [comment]
No, please open a new issue for that. Damn. The problem is that things like `select` expect spaces to be concept-dividers. I hadn't taken into account that names can have spaces.

**Comment by tillheilmann** [comment]
Okay. I am not sure, however, to describe this issue because it does not really seem like a bug to me. When the last name is "de Saussure", I expect the filter `:select=2,1` to give me "Saussure", no?

**Comment by retorquere** [comment]
That should be the case for `Auth`, but not `auth`. The current behavior is problematic if you have both `de Saussure` and `Brown`. `select=2,1` will return nothing for `Brown`.

**Comment by tillheilmann** [comment]
True. The thing is that I tried to use the :select filter as a hack to get at the "EtAl" part of `authors1`.

**Comment by retorquere** [comment]
Can I consider the issue that we started this topic with addressed?
