### ISSUE TITLE
Import external bibtex file changes for zotero update

### ISSUE THREAD

**Issue by fab6** [retorquere/zotero-better-bibtex#1555]
Hi
Is it possible or planed to update the zotero database based on any changes in the main better-bibtex-file, which one has done e.g. with an editor.
E.g. I have in mind, that I figure out during writing, that I am missing the date for an entry and could easily update it with my text editor.
If this is not possible with better-bibtex, it would be great, if you have some other hints or ideas how to do this.
Thank you in advance!

**Comment by retorquere** [comment]
This is not currently possible, and I don't think I'll be building it.

BibTeX files don't really have the concept of "changes", but it is sort of possible. You'd have to occasionally see whether the file modification timestamp has changed, and then either programmatically import the file and merge the duplicates, or parse the file (the BBT parser is [available separately
](https://github.com/retorquere/bibtex-parser)) and figure out which entries have changed by inspecting comparing them all to what you've parsed, and then update those items. This seems like a lot of work just to avoid having to call up Zotero.

If you just want to update Zotero entries from a text editor, it'd be lots easier to just have something like a CSV file with something like

| citekey | field | value |
|--------|------|------|
| `@somekey` | title | the nice and accurate predictions of Agnes Nutter, witch |
| `@somekey` | publicationTitle | independent |

and have a Zotero plugin read this occasionally, apply the changes, and delete the file.

**Comment by fab6** [comment]
ok, thank you very much for your quick reply! I will look if I get it managed somehow, thanks!

**Comment by retorquere** [comment]
Feel free to ask questions when needed.
