### ISSUE TITLE
Generating an "EtAl" string separately from authors' names with :select filter

### ISSUE THREAD

**Issue by tillheilmann** [retorquere/zotero-better-bibtex#1558]
I would like to produce an "EtAl" string for titles with multiple authors *separately* from the authors' names. The expression

`[authors1:select=2,1]`

works as expected for multiple authors and gives me "EtAl" *if* the first of the authors’ last names does not contain spaces. However, when there are spaces in the last name, I need to use something like

`[authors1:condense:select=2,1]`

but this, in turn, omits or 'swallows' the "EtAl" for last names with no spaces.

**Report ID:**

H99QI4YM-euc

**Comment by retorquere** [comment]
In this case I'd sooner add an `[etal=2,EtAl]` function to directly do what you want, or a `[split=.]` after which `select` would work.

**Comment by tillheilmann** [comment]
Yes, my earlier attempts are crude hacks. A clean solution with a proper function is certainly to be preferred.

**Comment by retorquere** [comment]
Ugh wait, there's also `[editors1]`, and `[etal=` would have to know whether you want etal for all authors, or just the editors. `[..:split=.]` would work though.

**Comment by tillheilmann** [comment]
Ideally for every title there is a list either of authors or of editors. If there are both, the list of authors takes precedence. If the list contains more than one name (with or without spaces, periods or any other character), I would like to access an "EtAl" string which I can customize. Doable?

**Comment by tillheilmann** [comment]
Sorry, I only realize now that you are, of course, right. A `[etal]` function would have to account for both lists (authors and editors). But to avoid further complication, it could be made so that the argument given to the function applies equally to both lists.

**Comment by retorquere** [comment]
I'm thinking it'd be better to just extend `auth`/`ed` functions. I could make them `auth.etalN` etc where `auth.ethal` is just equivalent to `auth.etal2`, and `auth.etalN+noauthor` to do the same but just produce `etal` when the conditions are met. `auth.etal2+noauthor` with two authors would produce nothing per the current behavior. I do not want to change the existing behavior. I took the original patterns from JabRef without thinking about them and there are a few that in retrospect I shouldn't have adopted, but I don't want to break existing unless it's a bug.

If you have an idea that generalizes over all these etal functions, that'd be good too.

This is going to be a bitch to document.

**Comment by tillheilmann** [comment]
I thnk it is not so easy to reproduce my custom pattern with the auth / ed functions:

[Last name of first author or editor (normalized, lower case)]
[Initials for first and middle name of first author or editor (lower case, prefixed by ".")]
["ea" in case of multiple authors or editors (prefixed by "."]
[Year or date of publication (no periods, dashes or anything, prefixed by ":"]
[Disambiguation by numbers 1, 2, 3... (prefixed by ":"]

Honestly, I am not sure it is really worth all the work. I am not a heavy Zotero user anyway. I just thought it would be neat to sync my 2000+ BibTeX *.bib file with Zotero and have my usual citation keys. You don't need to go the extra mile just for me.

**Comment by retorquere** [comment]
```
authors(max=2).discard + authors(1) + authors([2,2],name='%(i)s').prefix('.') + date('%Ym%d').prefix(':')
|
authors(1) + authors([2,2],name='%(i)s').prefix('.') + '.ea' + date('%Ym%d').prefix(':') 
```
