### ISSUE TITLE
Reverting live citations to cite keys in pandoc

### ISSUE THREAD

**Issue by ebardelli** [retorquere/zotero-better-bibtex#1559]
Hi!

I am using the CSL pandoc filter to go from bibtex keys in markdown to live citations in Word. I was wondering if there is a way to revert live citations to bibtex keys with Pandoc.

Thank you!

**Comment by retorquere** [comment]
label-gun asked for a debug log because you chose "bug" rather than "question". In any case, this should be possible I think, but it'll require a new pandoc lua filter. I'll think about how to go about that.

**Comment by ebardelli** [comment]
Thank you for considering it.

I was trying to change the label to question, but you beat me to it. Sorry for choosing the wrong label. I must have missed it in the submission screen.

**Comment by retorquere** [comment]
Not possible with pandoc AFAICT.
