### ISSUE TITLE
Send Note to TexStudio ?

### ISSUE THREAD

**Issue by dimmenhau** [retorquere/zotero-better-bibtex#1560]
Hello, 
would it be possible to extend the plugin to send notes to TexStudio with the citation ?
Then you could use the notes as a collection for quotations.

**Comment by retorquere** [comment]
Just out of curiosity: were you offered 4 kinds of issues to pick from? I see many unlabeled issues being created where the labeling should be automatic. I just don't understand how this happens.

In any case, you'd have to ask the texstudio people. If they offer a way to have notes pushed to them, I can have a look.

**Comment by dimmenhau** [comment]
Hello,
i have not found a way to label my request. Otherwise I would have already labelled it as "Question".

If I go to "Export -> Format -> Chicago Manual of... ", then I can insert the notes into TexStudio by drag & drop. Only if I use the Better BibText Citation ... - format then it does not work.

**Comment by retorquere** [comment]
> Hello,
> i have not found a way to label my request. Otherwise I would have already labelled it as "Question".

It should have been automatic. The standard "new issue" button above goes to https://github.com/retorquere/zotero-better-bibtex/issues/new/choose and that should have offered you a choice. Strange.

> If I go to "Export -> Format -> Chicago Manual of... ", then I can insert the notes into TexStudio by drag & drop. Only if I use the Better BibText Citation ... - format then it does not work.

Drag and drop works for me. Can you describe what you do, step by step (starting with "I open TeXstudio"), and what "does not work" looks like?

**Comment by dimmenhau** [comment]
Here's what I have in the works:
TeXstudio 2.12.22 (git 2.12.22)
Zotero 5.0.88

Zotero - Setting:
Export -> Better BibTeX Citation Key Quick Copy

Library:
see report
[Zotero-Bericht.pdf](https://github.com/retorquere/zotero-better-bibtex/files/4868689/Zotero-Bericht.pdf)


Steps:
- TeXstudio & Zotero have started
- Drag & Drop on a book arrives in TeXStudio as follows -> \cite{Hunnebeck.2014}
- Drag & Drop on a note arrives in TeXStudio as follows -> \cite{}
- Menu "Better BibTex -> Send entry to TexStudio" -> \cite{Hunnebeck.2014}

Change the setting to "Chicago Manual of Style 17th edition (full note)".
- Drag & Drop on a book arrives in TeXStudio as follows -> Hunnebeck, Lou, and Monika Dauer ITIL® Service design. 2nd edition, 3rd impr., 2011 edition. London: TSO, 2014.
- Drag & Drop on a note arrives in TeXStudio as follows -> "This is a direct quote.^[p.~12]{Hunnebeck.2014} "
- Menu "Better BibTex -> Send entry to TexStudio" -> \cite{Hunnebeck.2014}

I hope this helps.

**Comment by retorquere** [comment]
So you mean you'd want to be able to drag and drop notes this way?

**Comment by dimmenhau** [comment]
yes and it would be nice if this could be linked to the \cite.

If that comes out in the end, then that would be a great solution:
`\glqq<notetext>\grqq~\cite{<citekey>}`

Example:
`\glqqThis is a direct quote.\grqq~\cite{Hunnebeck.2014}`
`\glqqThis is a direct quote.\grqq~\cite[p. ~12]{Hunnebeck.2014}`

**Comment by retorquere** [comment]
I could see drag-n-dropping the notetext, but to have the citekey and `glqq` placed seems a bit arbitrary; people could have different preferences for that. What I could consider is that dropping a note *and* an item would drop both next to each other.

`\glqqThis is a direct quote.\grqq~` won't work BTW, it would need to be `\glqq{}This is a direct quote.\grqq~`

**Comment by dimmenhau** [comment]
I can live with the two drag drops or I can write myself TexStudio macro.

After I created my own command for one, I'm not sure if the brackets are included in \glqq.
Direct quote in my text:
`\begin{quoteDI}TEST\citeDI{Hunnebeck.2014}\end{quoteDI}`

the definition thereof:
`\newenvironment{quoteDI}{\glqq}{}`
`\newcommand{\citeDI}[2][]{\grqq~\citep[#1]{#2}`
