### ISSUE TITLE
How to complete the abbreviations of periodicals

### ISSUE THREAD

**Issue by zoushucai** [retorquere/zotero-better-bibtex#1561]
When I export bib, the abbreviations of periodicals are incomplete. What should I do？

**Comment by retorquere** [comment]
Why doesn't *anybody* read the submission template?!

**Comment by retorquere** [comment]
Please reopen when you have posted a debug log.

I don't know why people find this so hard. It is explained in detailed steps in the issue template and immediately by label-gun.
