### ISSUE TITLE
Referencing from entire zotero library, rather then exported library-user problem (beginner) 

### ISSUE THREAD

**Issue by GabriellaS-K** [retorquere/zotero-better-bibtex#1563]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4 you are posting a single question.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

**Your question/suggestion:**

Hi, 

I am a beginner with R/Rmarkdown, and have just downloaded the better-bibtex to use to reference from zotero, in Rmarkdown. I followed the really helpful setup [instructions](https://retorque.re/zotero-better-bibtex/citing/). However, each time I open R Markdown, and click 'addin', insert citation,  a pop up appears (see attached picture) 
<img width="606" alt="Screenshot 2020-07-05 at 19 24 50" src="https://user-images.githubusercontent.com/32248649/86539541-3ee9dc00-bef5-11ea-999d-179a89c9cc5d.png">

Then if I connect and load zotero libraries, the references are from my entire zotero, rather than the exported bibliography I saved to the same directory as my markdown file. 

YAML header looks like: 
```
output:
  pdf_document: default
  html_document: default
  bibliography: paper_2020.bib
```
I must be doing something wrong! Sorry for such a basic question, would be grateful for any help!
Thanks

**Comment by retorquere** [comment]
Hi, I build the backend to this, but window you have included here is from the [front end](https://github.com/crsh/citr), which I didn't build. I'm afraid I'm going to have to refer you to that repo, but if my help is needed to get the issue resolved, I'll be happy to assist.

**Comment by GabriellaS-K** [comment]
OK thanks very much! I'll ask over there :)
