### ISSUE TITLE
unexpected tag aborts export

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#1565]
Me again...the latest BBT results in an interrupted export process for me, unfortunately. Here's the 

Report ID: JW8VYZ9S-euc

I have added one entry, then tried to run clicking "Export Now" (from previous set-up). I had a couple of failed runs, the cache seems stuck in 12 percent. Exporter is Better BibLaTeX.

As always, thanks for your amazing programming wizardry and help!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.37.6761](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.37.6761.xpi) ("log items")

Install in Zotero by downloading [test build 5.2.37.6761](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.37.6761.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you get me a new log with 6761?

**Comment by jrennstich** [comment]
Sure thing:
Report ID: 7VZBAN7D-euc
Same thing happened. Stopped at 12 percent.
Thanks for super fast reply!

**Comment by retorquere** [comment]
Can you right-click `boyd-why-2007` and send a log from the popup menu?

**Comment by jrennstich** [comment]
Ah, that's the culprit. Thanks. 
Report ID: NNIIYKP8-euc
Not quite sure what you mean by log from pop-up. I only get the option to send a BBT debut report. 
But the problem was the name:
<!>boyd <!>danah

**Comment by jrennstich** [comment]
Thanks for clearing that up!

**Comment by retorquere** [comment]
I meant from the menu that pops up. BBT should have been able to deal with that name as it was.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.37.6763](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.37.6763.xpi) ("fixes #1565")

Install in Zotero by downloading [test build 5.2.37.6763](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.37.6763.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
@jrennstich @O2-AC get it while it's hot.

**Comment by retorquere** [comment]
I honestly don't know why it would crop up now and not sooner. That bit of code hasn't changed in a long while. I do make use of the built-in HTML parser, maybe that has changed behavior in the latest Zotero upgrade. The pseudo-HTML that Zotero supports is pretty nasty to parse, but this fix should deal with it.

**Comment by O2-AC** [comment]
Awesome. Everything works as expected for me with the fix. Thanks for the quick response

**Comment by jrennstich** [comment]
Gosh darn it, burnt my grabby fingers :-) Put in the offending characters again trying to reproduce the error - it's fixed from my side. Here's the 

Report ID: TZU8QSAY-euc

Thanks for your super quick fix!

**Comment by retorquere** [comment]
Thanks for reporting it. The 2nd report is now in the test suite so it can't happen again.
