### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by SusM13** [retorquere/zotero-better-bibtex#1566]
hello, I have a problem with my document reconising my references that are generated via zotero (linked) I added a new reference and since then it can't compile the references in the document anymore. Can anyone help me? Thanks

**Comment by retorquere** [comment]
I have no idea what this is about. I don't see anything linked. Do you have a problem compiling a latex document?

**Comment by SusM13** [comment]
I’m sorry, I’m using overleaf and was still trying to find how to get the BBT debug report. 
I linked Zotero to my Overleaf account and in my document my references.bib file is generated directly from Zotero. Now, I added a new references and it stopped working, it says that he cannot find the references or to check if I used the correct key, which I have and all the references are in the file. So I don’t understand.

**Comment by retorquere** [comment]
If you use the direct zotero-overleaf integration that overleaf offers, you must pin your citekey (select item(s), right-click, BBT, pin citekey) and sync, or they won't show up in overleaf. There's nothing I can do that makes it easier than that. The options to use BBT output in overleaf is documented [here](https://retorque.re/zotero-better-bibtex/exporting/auto/#getting-your-bbt-generated-biblatexcitekeys-to-other-places).

**Comment by retorquere** [comment]
Does this address your question?

**Comment by SusM13** [comment]
I fixed the issues, which apparently was due to 2 references that had no date and no author, I cancelled them in my zotero library and then it worked again without having to pin the cite key.

**Comment by retorquere** [comment]
If you don't pin the key, BBT is not involved with the way you are using Zotero - Overleaf.

**Comment by SusM13** [comment]
Ok I see, I ll pin them then thanks
