### ISSUE TITLE
Field "Institution" not available anymore in key pattern for Zotero

### ISSUE THREAD

**Issue by schumad** [retorquere/zotero-better-bibtex#1568]
Thanks a lot for the great work, I'm a happy user of BBT!
In Zotero, I have reports that often have no entry in the author field but only a company or institution name in the field "Institution". For generating citation keys, I use a different format with the institution if there is no author (pattern recovered from an earlier backup):
`[Auth:nopunctordash][>0][shorttitle3_3:skipwords:prefix=_][year:prefix=_] | [Institution:nopunctordash][shorttitle3_3:skipwords:prefix=_][year:prefix=_]`
This worked well until March 18th 2020 (I can't tell when it stopped working as I haven't added reports after that). Today, I've restarted Zotero and again added reports without author but only an institution, and there was no citation key generated by BBT. By checking for the reason, I've realized that the wiki mentions that the institution is only available in Juris-M. Furthermore, the pattern changed without editing anything from my side (see debug report).
I'd appreciate if the institution field would again become available for Zotero. Then I can fix the pattern myself.
Report ID: HXSK8UZ6-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.39.6767](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.39.6767.xpi) ("institution is a specialization for publisher in Zotero; fixes #1568")

Install in Zotero by downloading [test build 5.2.39.6767](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.39.6767.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you give 6767 a spin?

**Comment by schumad** [comment]
I've quickly tested 6767 with a couple of different items and it works again as before! Thanks a lot for the fast fix, much appreciated!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.40.6780](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.40.6780.xpi) ("adjust tests")

Install in Zotero by downloading [test build 5.2.40.6780](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.40.6780.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you right-click an item that uses the institution in the key and send a debug log? Then I can add a test case to prevent regressions.

**Comment by schumad** [comment]
Report ID: MS4UAD7M-euc

**Comment by retorquere** [comment]
Much appreciated.
