### ISSUE TITLE
Incompatible with Zotero 5.0.87

### ISSUE THREAD

**Issue by stakaz** [retorquere/zotero-better-bibtex#1570]
Hello, the latest release does not seems to be compatible with the latest Zotero version 5.0.87.

I cannot provide a debug report because I have removed the installed version after the error occurs and downloaded the latest release (v5.2.39). But I cannot install is due to incompatibility issues.

I see that the latest commit changes some version numbers so probably it will be fixed in the next hours anyway?

Thanks.

**Comment by stakaz** [comment]
As I have written in the previous message, I cannot install the extension due to incompatibility issues and therefore I cannot provide a debug report.

**Comment by retorquere** [comment]
5.0.87 is not the latest version of Zotero, 5.0.88 is. I have changed the behavior to disable rather than uninstall BBT when it finds an incompatible version, but you'll need to upgrade.

**Comment by stakaz** [comment]
Oh, ok, thanks, I use AUR on Arch so probably there will be an update soon. I have uninstalled the extension accidentally before trying to reinstall again.

**Comment by stakaz** [comment]
Ok, there is already the 5.0.88 online. Thanks.
