### ISSUE TITLE
Update 2020-07-12: crashes JurisM on start, automatically disabled

### ISSUE THREAD

**Issue by zaw-shinoto** [retorquere/zotero-better-bibtex#1572]
[Update 2020-07-12- crashes JurisM on start, automatically disabled.start.log.txt](https://github.com/retorquere/zotero-better-bibtex/files/4907915/Update.2020-07-12-.crashes.JurisM.on.start.automatically.disabled.start.log.txt)
**Report ID: ?**

**Expected behavior:** 

Start JurisM and get all settings (columns in particular) and all Addons working as normal.

**Actual behavior:** 

JurisM freezes, I have to force quit. Then I restart JurisM, BBT is disabled, all columns are set "on" and I had set them manually back to normal. Then I enable BBT again and restart JurisM. Same problem. I leave everything as is, set logging on restart and restart, everything works find. Log is attached, I hope it is OK this way. 

JurisM seems to work now; but the problem on start looked serious, and I expect more users experiencing this. 

Best,
Maria

**Comment by zaw-shinoto** [comment]
I added the the log, there is no way to add a debug report, as far as I understand the situation. 

Thanks for developing BBT.

**Comment by retorquere** [comment]
What version of Juris-M are you on?

**Comment by retorquere** [comment]
Oh wait, I see in the log you're on 5.0.89m8.

**Comment by retorquere** [comment]
Can you try upgrading BBT from the addons menu?

**Comment by zaw-shinoto** [comment]
Sorry for the confusion, I will try to get on the track and be cooperative. Please excuse my lack of experience.

**Comment by retorquere** [comment]
No no, I didn't mean that! I have found the error and put out a new release and I'm hoping that will fix it for you!

**Comment by zaw-shinoto** [comment]
I am working on it, the problem stays. I am now repeating all steps and wanted to write immediately -- in 5 minutes or so. 

OK?

**Comment by zaw-shinoto** [comment]
Hi, 

now I have repeated the process several times with the updated BBT disabled and enabled. 

First it looked that the problem still was the same, but it may be that the update was not ready then. 

Now everything worked fine, like before. 

Thanks for the great support!

Maria

**Comment by retorquere** [comment]
Awesome, thanks for reporting this and getting confirmation so quickly!
