### ISSUE TITLE
Custom pinned citation key

### ISSUE THREAD

**Issue by beojan** [retorquere/zotero-better-bibtex#1574]
When adding items to my bibliography, I like to use a citation key describing the topic of the item rather than the authors' names. The ability to pin a custom citation key (taken as input) would be really helpful. I currently have to pin whatever key is generated, then modify the `Extra` field.

**Comment by beojan** [comment]
This is a feature request not a bug.

**Comment by retorquere** [comment]
You can just type `Citation Key: <your key>` in the extra field, you don't need to pin it first. A key is pinned when that line is present in the extra field, however it got there. The `pin key` is just a convenience for when you want the generated key as the pinned key.

**Comment by retorquere** [comment]
Does this address your question?

**Comment by beojan** [comment]
A menu option (or even better, a keyboard shortcut) would be nice, but yes, this answers my question.

**Comment by retorquere** [comment]
For shortcuts you'd have to look at Zutilo, but what would the menu option do?

**Comment by beojan** [comment]
I'd have thought a menu option would be needed to setup a keyboard shortcut. I'll try Zutilo.

**Comment by retorquere** [comment]
Correct, but what would the menu option do? Just write `Citation Key:` in the extra field? Then I see no real benefit over using `pin citation key` and typing over the key.

**Comment by beojan** [comment]
I was thinking it could show a `prompt` box to ask the user for the key to use.

**Comment by retorquere** [comment]
So it'd prompt for a key and then write that to the `extra` field with `Citation Key:` prepended?

**Comment by beojan** [comment]
Yes.

**Comment by rddunphy** [comment]
> Correct, but what would the menu option do? Just write `Citation Key:` in the extra field? Then I see no real benefit over using `pin citation key` and typing over the key.

I think the main benefit would be clarity - the current process is not difficult once you know how it's done, but it's a bit counterintuitive (as the word "pin" implies that the citation key *won't* change). Also, it relies on the user knowing that the citation key is stored in the `Extra` field, which is not obvious from clicking on `Pin BibTeX key`. I don't usually need to manually specify citation keys, so I'd forgotten how it's done; I first tried clicking on the "Citation Key" line in the side panel, then tried double-clicking it, then searched the context menu, and finally ended up googling it (which is how I ended up here). Not a huge hardship, to be sure, but a `Change BibTeX key...` option that opens up a prompt dialog would be a nice usability feature.

Thanks for maintaining this great add-on, by the way - it makes my life so much easier!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.75.7218](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.75.7218.xpi) ("fixes #gh-1574")

Install in Zotero by downloading [test build 5.2.75.7218](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.75.7218.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Good point. Try 7218.

**Comment by beojan** [comment]
Thanks. That works great.

**Comment by rddunphy** [comment]
That looks great, thanks!
