### ISSUE TITLE
Unexpected HTML tags abort export

### ISSUE THREAD

**Issue by tea4or2wo** [retorquere/zotero-better-bibtex#1575]
**Report ID:**

WJ2YBV9E-apse

**Steps to reproduce:**

1. open Zotero
2. Right click on the whole library in the left pane
3. choose "export library" in context menu
4. choose `better biblatex` format in pop-up
5. select "export notes"
[6. willing to select "keep updated" as soon as it gets to work]

I have checked similar issues on Zotero forum and here.

**Exporter used:**

betterbiblatex

**Expected behavior:**

exporting a `.bib` file for my whole library

**Actual behavior:**

 pop-up saying: "An error occured while trying to export the selected file"

**Comment by tea4or2wo** [comment]
I am sorry but I do not know how to isolate which items in the library cause the export to fail.

**Comment by retorquere** [comment]
No worries, the logs have the info -- at least one of the causes is `heimburgerGererDocumentationQuelques2012`. I'm away from my computer right now alas, and it will be at least 6 hours before I'm back. This will be a simple fix but not from my phone 😉 .

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.43.6798](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.43.6798.xpi) ("fixes #1575")

Install in Zotero by downloading [test build 5.2.43.6798](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.43.6798.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6798 should fix it.

**Comment by tea4or2wo** [comment]
Thank you, that works!

Is there anything related to user behavior to avoid repetition in the future?

**Comment by retorquere** [comment]
No -- this was a bug in BBT and you shouldn't have experienced it.
