### ISSUE TITLE
Book section gets book citation key upon creation

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#1579]
Upon creating a new book section from an existing book reference, where keys are autopinned, the section's key is the same as the book's.

Any automated way to prevent this from happening? In some cases, the key simply needs an increment ("-1") on the end; in others there's a separate section author, so an entirely new key is needed.

Right now I use the contextual menu to un-pin the key, and then BBT generates the correct new key. Of course I forget to do this...a lot.

PS some way to check for duplicate pinned keys would be awesome. Right now I process my export back-ups to look for them.

**Comment by retorquere** [comment]
You mean by duplicating the item, then changing the item type? Tricky. Zotero duplicates the item including the extra field, I don't get notified how a new item came into existence, so I can't tell its a duplicate, and if there's a pinned key in the extra field I can't tell how it got there. I can try to see if I can patch the duplicate method in Zotero to clear the pinned key, but that'd be specific to item duplication.

**Comment by retorquere** [comment]
If you just want to detect them, I could add that to the quality report.

**Comment by Jmuccigr** [comment]
Sorry about that. I’m using Zutilo to make book sections from existing books. 

https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md

I always confuse what’s built in and what’s in an extension.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.45.6821](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6821.xpi) ("Merge branch 'master' into gh-1579")

Install in Zotero by downloading [test build 5.2.45.6821](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6821.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 6821 a go

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.45.6822](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6822.xpi) ("list key duplicates")

Install in Zotero by downloading [test build 5.2.45.6822](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6822.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Or 6822 if you want the quality report to list duplicates

**Comment by qqobb** [comment]
One could consider removing pinned citation keys within Zutilo's "Create book section" function ([here](https://github.com/willsALMANJ/Zutilo/blob/d2d5f7055b8aec9d509a7a32896285f29dcfa2f4/addon/chrome/content/zutilo/zoteroOverlay.js#L833)). But I'm not sure that this is what users generally want. You might, e.g., have a book with pinned key `AuthorBook` and want to create a book section with `AuthorBookCh1`. Keeping the pinned key could help in this case.

@Jmuccigr: You could also set a Zutilo shortcut for BBT's "Unpin key", see [here](https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md#better-bibtex-functions).

**Comment by retorquere** [comment]
6822 will remove the pinned key from the copy when you call `item.clone`. While it is likely that you would want `AuthorBookCh1`, it is unlikely that you'd want a duplicate key `AuthorBook`, and if you have autopin on, `AuthorBook` would likely be generated + pinned, so with an appropriate key pattern you should be able to have BBT generate `AuthorBookCh1` and have that autopinned. Zutilo's "Create book section" calls `duplicate` which in turn calls `item.clone`.

Removing it inside Zutilo's "Create book section" would be an alternate solution, but I can't patch it in, nor would I want to. Patching extensions is susceptible to race conditions which are hard to safeguard against and to debug. So it would have to be done on the Zutilo side; it could just do what I did: https://github.com/retorquere/zotero-better-bibtex/blob/gh-1579/content/better-bibtex.ts#L211

**Comment by qqobb** [comment]
@retorquere: Thanks for the explanation. This seems a good solution. Not cloning a pinned citation key seems to be the preferred option in most cases. Especially if the autopin option is used, which I missed is the case here. So I guess 6822 is exactly what @Jmuccigr wants.

**Comment by retorquere** [comment]
6822 is indiscriminate btw, it's not specifically when auto pin on, it's active whenever an item is cloned. If zutilo wants to implement it that'd be fine too, I don't have a real preference here

**Comment by qqobb** [comment]
> 6822 is indiscriminate btw, it's not specifically when auto pin on, it's active whenever an item is cloned.

I noticed that and also don't have a strong preference here.

One could argue that BBT should deviate from Zotero's behavior as little as necessary. So if Zotero keeps a citation key in Extra when duplicating an item, then BBT should do so as well. But on the other hand, since BBT is introducing many new features related to the citation keys, changes in Zotero's behavior should be OK if they serve a purpose. This issue shows that there's a reason for the changes discussed here. I'm not using the autopin option, so I can't judge whether only changing Zutilo's "Create book section" function would work equally well. With autopin, 6822 might provide the preferred behavior when duplicating items. So maybe keep the changes of 6822 until somebody provides convincing arguments against it?

**Comment by retorquere** [comment]
I agree BBT should change the behavior as little as possible, but I'd argue this case is different:

1. The citation key is added by BBT, it's not something that's in Zotero without it, and
2. The primary purpose of the citation key is to uniquely define an item

**Comment by retorquere** [comment]
@Jmuccigr can you test whether 6822 does what you want?

**Comment by Jmuccigr** [comment]
> @Jmuccigr can you test whether 6822 does what you want?

Away from the laptop now, but will check soon.

**Comment by Jmuccigr** [comment]
No, it doesn't seem to work for me. If I use the contextual menu to create a book section, it gets an incremented citation key based on the book's. It doesn't seem to matter if I have autopin on or off (usually on).

I also don't see any conflict reports in the exports when I have a duplicate citation key (though TBH I'm not sure I'm doing that right).

Zotero for Mac 5.0.89. High Sierra 10.13.6.

**Comment by retorquere** [comment]
To turn on conflict reports you need to turn on the quality report.

WRT the copy getting the incremented citation key -- Zutilo calls zotero's `duplicate`, but `duplicate` saves the item (generating a key) *before* Zutilo modifies the item. If Zutilo instead called `clone` (which doesn't save), modified the clone, and then saved it, it would get a key based on the modified copy instead.

**Comment by Jmuccigr** [comment]
It seems to work as you say: I can see the new item without a key, then watch the key get created and incremented. Of course it's using the book info to create the new key, since I haven't entered any section info yet, and therefore grabs the book editor as author, who is usually not the section author.

> To turn on conflict reports you need to turn on the quality report.

This means check the box for "Include comments about potential problems"?

**Comment by retorquere** [comment]
> It seems to work as you say: I can see the new item without a key, then watch the key get created and incremented. Of course it's using the book info to create the new key, since I haven't entered any section info yet, and therefore grabs the book editor as author, who is usually not the section author.

If it requires manual edits by you, having Zutilo use `clone` rather than `duplicate` won't change anything. I suppose I could introduce a delay for auto-pinning. That would give you a little time to make your edits before the key "solidifies".

> > To turn on conflict reports you need to turn on the quality report.
> 
> This means check the box for "Include comments about potential problems"?

Correct, sorry about that, I changed the user-facing wording.

**Comment by Jmuccigr** [comment]
Yeah, most of the time the section author differs from the book author (editor), at least in my use cases, and so my key, which has author in it, needs more than a simple increment. A pause of decent length would help.

Frankly if there were an easier way to unpin the key than going through the menus, like a button, that would probably be bearable. Can you insert a menu item that a keystroke could be assigned to?

**Comment by retorquere** [comment]
That already exists.

**Comment by retorquere** [comment]
I understand more than a simple increment, but autopin just means "pin citekey immediately after item creation". It can't know you intend to change it soon after.

**Comment by Jmuccigr** [comment]
I get the issue, but since I use Zotfile to make the file, I was wondering whether there was a way to insert something into that process. I guess not.

> That already exists.

How so?

**Comment by retorquere** [comment]
> I get the issue, but since I use Zotfile to make the file, I was wondering whether there was a way to insert something into that process. I guess not.

Zutilo could do it. But the way the zutilo code does it I can't do something midway.

> > That already exists.
>
> How so?

Right-click item, Better BibTeX, Unpin.

**Comment by Jmuccigr** [comment]
Yeah, that’s a nested contextual menu. If it were a regular menu item, I could set a shortcut in MacOS. Or there could be a button. :-)

**Comment by retorquere** [comment]
I don't really want to start adding top-level menu's. BBT does a lot and that will get cluttered very quickly. Zutilo can add shortcuts.

**Comment by Jmuccigr** [comment]
> Zutilo can add shortcuts.

Thanks for this. I didn't know about that and my Zutilo install was way out of date. That solves my problem.
