### ISSUE TITLE
HTTP endpoint for citekey -> scannable cite mapping

### ISSUE THREAD

**Issue by kjambunathan** [retorquere/zotero-better-bibtex#1582]
## Context

I am the owner of OpenDocument export for Emacs Org files.  I am hoping to integrate `better-bibtex` and `Zotero ODF scan` in the COMMAND LINE pipeline i.e., I want the document production with NO user intervention whatsoever.

I have two questions:

<details><summary>Question 1: Any way I can hit http://localhost:23119 with a BetterBibtex key and get a native Zotero key</summary>

If yes, I can use this service to translate an existing BetterBibtex to any of the other export formats including native zotero urls and scannable text.  

I want to avoid the Zotero pop-up.

```
~$ curl -s http://127.0.0.1:23119/better-bibtex/cayw?format='scannable-cite'
{ | Wrigstad, & Castegren, 2017 | | | zu:0:TH5CXWRG }
```

Consider my request as a continuation of #1581 (Issue ID: KMFGJF27-apse).  In that issue I have imported an existing `bib` file with fixed keys to Zotero and I only want the Zotero DB key for the item.
</details>

<details><summary>Question 2: A command line tool for importing a `bib` file to the Zotero DB.</summary>

Looking at the `pandoc/Makefile`, I see that this is possible,

```
start:
	ZOTERO_IMPORT=$(PWD)/biblio.bib npm start
```

I would appreciate if you provide a user-facing command line to do this.
</details>

**Comment by retorquere** [comment]
re Q1: I can add a [json-rpc](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/) method to do that.

re Q2: That only works because of a special accommodation of my test harness. It requires py3.8, node 14, and a second plugin being installed (which my test framework automates). You're free to use it as it is, but I'm not splitting it off to something more lightweight. But if you right-click a bib file and open it with Zotero, Zotero will offer to import it.

**Comment by retorquere** [comment]
More re: Q1: `zu:0:TH5CXWRG` is not the native Zotero key of the item; `TH5CXWRG` is, the rest of that is specific to Scannable Cite. The pandoc filter allows you to influence what comes before by specifying `zotero.library` either in the yaml metadata or the command line.

Also re Q1: you can call `http://127.0.0.1:23119/better-bibtex/export/item?pandocFilterData=true&translator=jzon&citationKeys=<key1>,<key2>,...` and you'll get a JSON document with all item details for those keys. That already exists (the pandoc lua filter uses it for example) so that needs no changes in BBT.

**Comment by kjambunathan** [comment]
> https://retorque.re/zotero-better-bibtex/exporting/json-rpc/

`item.search(searchterms)` is what I want.  

The only difference is I want ALL items in the database (or library).  

In the transcript below, I have tried passing an empty string, a `*` (hoping for a regexp wildcard) and a `.` but I get nothing. ( It is understandable because the API is targetting a UI-based picker)

`search` is a poor term.  I want to just list the collection.

Here is a transcript for you to look at


## Retrieve items: search term is `wrig`

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": ["wrig"] }'
```

```json
{"jsonrpc":"2.0","result":[{"id":"http://zotero.org/users/local/debm4usg/items/TH5CXWRG","type":"paper-conference","container-title":"SPLASH-E","note":"Citation Key: wrigstad2017mastery","title":"Mastery learning-like teaching with achievements","author":[{"family":"Wrigstad","given":"Tobias"},{"family":"Castegren","given":"Elias"}],"issued":{"date-parts":[["2017"]]},"library":"My Library","citekey":"wrigstad2017mastery"}],"id":null}~$ 
```


## Retrieve items: search term is `artistotle`

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": ["aristotle"] }'
```

```json
{"jsonrpc":"2.0","result":[{"id":"http://zotero.org/users/local/debm4usg/items/75X2T9MT","type":"book","event-place":"Cambridge","publisher":"Cambridge University Press","publisher-place":"Cambridge","title":"De Anima","author":[{"literal":"Aristotle"}],"editor":[{"family":"Hicks","given":"Robert Drew"}],"issued":{"date-parts":[["1907"]]},"library":"My Library","citekey":"aristotleAnima1907"},{"id":"http://zotero.org/users/local/debm4usg/items/RS9B3YHD","type":"book","event-place":"New York","publisher":"G. P. Putnam","publisher-place":"New York","title":"Physics","author":[{"literal":"Aristotle"}],"translator":[{"family":"Wicksteed","given":"P. H."},{"family":"Cornford","given":"F. M."}],"issued":{"date-parts":[["1929"]]},"library":"My Library","citekey":"aristotlePhysics1929"},{"id":"http://zotero.org/users/local/debm4usg/items/WPBD2LIG","type":"book","collection-title":"Clarendon Aristotle","event-place":"Oxford","publisher":"Clarendon Press","publisher-place":"Oxford","title":"Poetics","author":[{"literal":"Aristotle"}],"editor":[{"family":"Lucas","given":"D. W."}],"issued":{"date-parts":[["1968"]]},"library":"My Library","citekey":"aristotlePoetics1968"},{"id":"http://zotero.org/users/local/debm4usg/items/UV87JXXQ","type":"book","publisher":"Cambridge University Press","title":"The Rhetoric of Aristotle with a commentary by the late Edward Meredith Cope","title-short":"Rhetoric","author":[{"literal":"Aristotle"}],"editor":[{"family":"Cope","given":"Edward Meredith"}],"issued":{"date-parts":[["1877"]]},"library":"My Library","citekey":"aristotleRhetoricAristotleCommentary1877"},{"id":"http://zotero.org/users/local/debm4usg/items/NCU6ZG9Y","type":"book","event-place":"Princeton","publisher":"Princeton University Press","publisher-place":"Princeton","title":"Aristotle's \\mkbibquoteDe Motu Animalium","author":[{"family":"Nussbaum","given":"Martha"}],"issued":{"date-parts":[["1978"]]},"library":"My Library","citekey":"nussbaumAristotleMkbibquoteDeMotu1978"},{"id":"http://zotero.org/users/local/debm4usg/items/UPL84QBW","type":"chapter","collection-number":"9","collection-title":"Studies in Philosophy and the History of Philosophy","container-title":"Studies in Aristotle","event-place":"Washington, D.C.","page":"161-191","publisher":"The Catholic University of America Press","publisher-place":"Washington, D.C.","title":"Aristotle's Theory of the Intellect and its Interpretation by Averroes","title-short":"Aristotle's Theory of the Intellect","author":[{"family":"Hyman","given":"Arthur"}],"editor":[{"family":"O'Meara","given":"Dominic J."}],"issued":{"date-parts":[["1981"]]},"library":"My Library","citekey":"hymanAristotleTheoryIntellect1981"},{"id":"http://zotero.org/users/local/debm4usg/items/KYCXS2G9","type":"paper-conference","container-title":"Aristotle on Mind and the Senses","note":"event-place: Cambridge","page":"281-324","publisher":"Cambridge University Press","title":"Le \\emphDe Anima dans la tradition grècque: Quelques aspects de l'interpretation du traité, de Theophraste à Themistius","title-short":"\\emphDe Anima dans la tradition grècque","author":[{"family":"Moraux","given":"Paul"}],"editor":[{"family":"Lloyd","given":"G. E. R."},{"family":"Owen","given":"G. E. L."}],"issued":{"date-parts":[["1979"]]},"library":"My Library","citekey":"morauxEmphDeAnimaDans1979"}],"id":null}
```

## Retrieve all items - ???

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": [""] }'
```

```json
{"jsonrpc":"2.0","result":[],"id":null}
```

**Comment by kjambunathan** [comment]
I need to examples on how to use `item.export(citekeys, translator, libraryID)` and `

## In `item.export(citekeys, translator, libraryID)`, can you list out some valid values for `translator` param




```
item.export(citekeys, translator, libraryID)

Generate an export for a list of citekeys

    citekeys: Array of citekeys
    translator: BBT translator name or GUID
    libraryID: ID of library to select the items from. When omitted, assume ‘My Library’
```

```
item.bibliography(citekeys, format)

Generate a bibliography for the given citekeys

    citekeys: An array of citekeys
    format: A specification of how the bibliography should be formatted

returns: A formatted bibliography

```

### When `translator` is set to `pandoc` or `scannable-cite` the `curl` command hangs. 

Here is a transcript ...

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.export", "params": [["wrigstad2017mastery"], "pandoc"] }'
  C-c C-c

~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.export", "params": [["wrigstad2017mastery"], "scannable-cite"] }'
  C-c C-c
```

## In `item.bibliography(citekeys, format)`, can you give me some sample values for `format` param

Here is a transcript .... I have mostly passed an invalid value for `format` param.  But then why is it complaining about invalid `style` instead?

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.bibliography", "params": [["wrigstad2017mastery"], "scannable-cite"] }'

{"jsonrpc":"2.0","error":{"code":-32603,"message":"Error: no style specified"},"id":null}
```



```
item.bibliography(citekeys, format)

Generate a bibliography for the given citekeys

    citekeys: An array of citekeys
    format: A specification of how the bibliography should be formatted

returns: A formatted bibliography
```

**Comment by retorquere** [comment]
This "question 1, question 2" format doesn't work for me if you're re-using question numbers. It's hard for me to tell what I'm addressing. It's also easier to read for me if you put separate questions in separate comment boxes, this thread is getting very hard to read.

If you want everything, you can use [pull export](https://retorque.re/zotero-better-bibtex/exporting/pull/): http://127.0.0.1:23119/better-bibtex/export/library?/1/library.jzon

The jzon format wasn't in the pull export docs, it's added now but it takes some time for GH to update the site.

**Comment by kjambunathan** [comment]
> This "question 1, question 2" format doesn't work for me if you're re-using question numbers. It's hard for me to tell what I'm addressing. It's also easier to read for me if you put separate questions in separate comment boxes, this thread is getting very hard to read.

Ok.  I will replay the questions one by one ....

**Comment by kjambunathan** [comment]
**Question on usage of [JSON-RPC](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/): In `item.export(citekeys, translator, libraryID)`, can you list out some valid values for `translator` param**

```
item.export(citekeys, translator, libraryID)

Generate an export for a list of citekeys

    citekeys: Array of citekeys
    translator: BBT translator name or GUID
    libraryID: ID of library to select the items from. When omitted, assume ‘My Library’
```

```
item.bibliography(citekeys, format)

Generate a bibliography for the given citekeys

    citekeys: An array of citekeys
    format: A specification of how the bibliography should be formatted

returns: A formatted bibliography

```

**When `translator` is set to `pandoc` or `scannable-cite` the `curl` command hangs.**

Here is a transcript ...

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.export", "params": [["wrigstad2017mastery"], "pandoc"] }'
  C-c C-c

~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.export", "params": [["wrigstad2017mastery"], "scannable-cite"] }'
  C-c C-c
```

**Comment by retorquere** [comment]
If you want everything, just use pull export: http://127.0.0.1:23119/better-bibtex/export/library?/1/library.jzon

**Comment by kjambunathan** [comment]
**Question on usage of [JSON-RPC](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/): In `item.bibliography(citekeys, format)`, can you give me some sample valid values for `format` param

When I set `format` to  `scannable-cite`, I see a complaint about `style` instead .... Here is a transcript.

```
~$ curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.bibliography", "params": [["wrigstad2017mastery"], "scannable-cite"] }'

{"jsonrpc":"2.0","error":{"code":-32603,"message":"Error: no style specified"},"id":null}
```

**Comment by retorquere** [comment]
When an unsupported format is passed, Zotero throws an error I can't catch unfortunately. I should document the format better; it is a JSON object with the following possible keys:

* quickCopy (boolean): when true, use the QuickCopy setting from Zotero
* contentType (string): when present, must be `html` or `text`
* id (string): a CSL style name

**Comment by kjambunathan** [comment]
>What do you want to accomplish?

What you see below is what I want.  But I want it not for a solitary key, but for /all/ keys

```
~$ curl -s http://127.0.0.1:23119/better-bibtex/cayw?format='scannable-cite'
{ | Wrigstad, & Castegren, 2017 | | | zu:0:TH5CXWRG }
```

I won't be using pandoc's filter. 

 Filter will be on Emacs / Emacs Lisp sid. 

I will use your JSON RPC call to accomplish the translation from citekey->scannable-cite

     `@wrigstad2017mastery`->`{ | Wrigstad, & Castegren, 2017 | | | zu:0:TH5CXWRG }`

and will pass the resulting document to ODF scan.






>item.bibliography uses the Zotero CSL processor to create a bibliography.

**Comment by kjambunathan** [comment]
The signature of JSON-RPC will be something like 

collection.citation(citekeys, format).

If citekeys is unspecficied, retrieve for all keys.  

`format` can be any of the `Export Formats` that I can select in  Zotero's Quick Copy preferences.  I am only interested in `scannable-cite` for now.

The result will be two-columned table, with colnames 'citekey' and 'citation string` (in whatever format)

**Comment by kjambunathan** [comment]
> The jzon format wasn't in the pull export docs, it's added now but it takes some time for GH to update the site.

>> the ID you get by right-clicking your collection and selecting “Show collection key”

I couldn't find such a option.   The URL is available when one right clicks the collection and does `Download Better BibTex Export`.  

![Screenshot from 2020-07-26 10-25-55](https://user-images.githubusercontent.com/19869864/88471779-78c56580-cf2a-11ea-9efc-0d7093a4a889.png)

**Comment by kjambunathan** [comment]
The doc at https://retorque.re/zotero-better-bibtex/exporting/pull/ says `.jzon` is one of the available formats.  I dont' find `jzon` format in the drop down list.  Is this deliberate?  Btw, that page requires an additional note where one can do a 'Show Collection Key'.

![Screenshot from 2020-07-26 10-34-02](https://user-images.githubusercontent.com/19869864/88471890-a363ee00-cf2b-11ea-842f-2c70fe8f8ca9.png)

**Comment by retorquere** [comment]
> The doc at https://retorque.re/zotero-better-bibtex/exporting/pull/ says `.jzon` is one of the available formats. I dont' find `jzon` format in the drop down list. Is this deliberate?

Yes. This format is not expected to be used by end-users.

Given that format BTW, you can create scannable cites like so (in python; I don't speak scheme unfortunately):

```
#!/usr/bin/env python3

import requests
import json
import re

lib = json.loads(requests.get('http://127.0.0.1:23119/better-bibtex/export/library?/1/library.jzon').text)

def scannable_cite(item):
  uri = item['uri'].split('/')
  key = uri[-1]
  lib_or_uid = uri[4]
  if lib_or_uid == 'local': # unsynced
    user_or_group = 'zu'
    lib_or_uid = '0'
  else:
    user_or_group = 'zu' if uri[3] == 'users' else 'zg'
  return '{ | @' + item["citationKey"] + ' | | | ' + user_or_group + ':' + lib_or_uid + ':' + key + ' }'

lib = {
  item['citationKey']: scannable_cite(item)
  for item in lib['items']
  if item['itemType'] not in ['note', 'attachment']
}
```



> I couldn't find such a option. The URL is available when one right clicks the collection and does `Download Better BibTex Export`.

That's correct -- the docs were out of date. The site is rebuilding to fix this.

**Comment by kjambunathan** [comment]
Thanks for the python script.  I will test drive it tomorrow.
