### ISSUE TITLE
DOMParser Error after BBT installed

### ISSUE THREAD

**Issue by l0o0** [retorquere/zotero-better-bibtex#1584]
Maybe this is a bug. 

I am trying to build an addon for Zotero. And I found an error when I run code in the Zotero RunJavascript window. I can't use `new DOMParser`, above is the screenshot.
![图片](https://user-images.githubusercontent.com/2743744/88248969-9352d100-ccd5-11ea-85c8-cf55c90e5f9d.png)

Demo code
```javascript
var parser = new DOMParser();
var resptext = '<p>内容</p><div>divNext</div>'
var html = parser.parseFromString(resptext, "text/html");
html;
```

Is there a conflict between BBT and JS environment?

Report-ID: DZNA9A5E-apse

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.45.6839](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6839.xpi) ("use default domparser")

Install in Zotero by downloading [test build 5.2.45.6839](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6839.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
There was indeed; try 6839

**Comment by l0o0** [comment]
@blip-bloop Thank you for your quick reply. The error is fixed. Your add-on is veeeeeery good.👍

**Comment by retorquere** [comment]
@blip-bloop is a bot 😄 . I'll merge this into a release.
