### ISSUE TITLE
BibTeX exports month abbreviations instead of numeric months

### ISSUE THREAD

**Issue by zoushucai** [retorquere/zotero-better-bibtex#1587]
- [x] 1. you have picked the right category for the issue in the previous screen.
 - [x] 2. You are on the latest release of Zotero
 - [x] 3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
 - [x] 4. you are posting a single bug or feature request.

`Export`: 

When I export my bibliography, "month" is exported without curly brackets. Field Date is displayed as  ‘06/2014’ in `Zotero` .
The **actual behavior ** derived from Better BibTex is as follows:
```
@article{xu2014weak,
  title = {Weak transitivity of interval-valued fuzzy relations},
  author = {Xu, Yejun and Wang, Huimin and Yu, Dejian},
  year = {2014},
  month = jun,
  volume = {63},
  pages = {24--32},
  journal = {Knowledge-Based Systems}
}
```
But this is not what I want. What I want is whether the month field can be translated into a number,  **Expected behavior** as follows

```
@article{xu2014weak,
  title = {Weak transitivity of interval-valued fuzzy relations},
  author = {Xu, Yejun and Wang, Huimin and Yu, Dejian},
  year = {2014},
  month = {6},
  volume = {63},
  pages = {24--32},
  journal = {Knowledge-Based Systems}
}
```

**Comment by retorquere** [comment]
Come on, you ticked boxes 1-4 but then omitted the debug report?

**Comment by retorquere** [comment]
@njbart what is the right way here? BibTeXing says month abbreviation, TTB says "abbreviation or number, number preferred".

@zoushucai why do you want it numeric? What goes wrong for you with the month abbreviation? According to "LaTeX: A document preparation system"

> Some abbreviations are predefined by the bibliography style. These always include the usual three-letter abbreviations for the month.

**Comment by zoushucai** [comment]
> @njbart这里的正确方法是什么？BibTeXing表示月份缩写，TTB表示“缩写或数字，首选数字”。
> 
> @zoushucai为什么要数字化？月份缩写对您来说有什么问题？根据“ LaTeX：文件准备系统”
> 
> > 一些缩写是由书目风格预先定义的。这些总是包括本月通常的三个字母的缩写。

Thank you. In fact, I don't understand the rules, but I personally think it's better to use numbers than words,

**Comment by retorquere** [comment]
Then it's just an aesthetic preference, and one that goes against the recommendation of the leading documentation on the matter. Why would it be better here? If you do not experience any problem with the generated bibtex as it is, I would prefer to stick to what little documentation that exists for bibtex.
