### ISSUE TITLE
Remove permanently file .bib

### ISSUE THREAD

**Issue by MissBaccara** [retorquere/zotero-better-bibtex#1588]
Hello,

I'm writing you because I have a problem with the library export. I've exported my library from Zotero with Better BibTeX several times in the same folder under a different name and I checked the "Keep up-to-date" option. I have deleted the .bib files I no longer need, but they automatically reappear. Could you please tell me how to permanently delete them? I can't find a solution.

Thank you in advance!

**Comment by retorquere** [comment]
No problem. https://retorque.re/zotero-better-bibtex/exporting/auto/#managing-auto-exports:

> After you’ve set up an auto-export using an Keep updated export, you can manage your auto-exports in the BBT preferences under the Automatic exports tab. There, you can remove auto-export, change settings on them, or remove them.

**Comment by MissBaccara** [comment]
Thank you ! I didn't use the correct terms to search fro my problem.

**Comment by retorquere** [comment]
No worries, it's always OK to ask. What terms did you use? I might add them to the page.

**Comment by MissBaccara** [comment]
I searched in French ... I guess this is the reason !

**Comment by retorquere** [comment]
Ah, I don't speak French, sorry.
