### ISSUE TITLE
no Configuration Dialog on AutoExport

### ISSUE THREAD

**Issue by dimmenhau** [retorquere/zotero-better-bibtex#1594]
Hello,
I just installed Linux Ubuntu Mate 18.10 and 20.04 with Zotero 5.0.89 and with the plugin 5.2.47. Under both Linux versions the configuration dialog for the automatic export is not available. 
![Screenshot at 2020-07-30 02-40-14](https://user-images.githubusercontent.com/59511540/88867564-2035e700-d20e-11ea-9a3d-6f74710c7008.png)
Is this an error or does it not work under Linux ?

I have uploaded my log data to GitLAB under the ID: 2HAY9WSF-euc

Greeting
      Dietmar

**Comment by retorquere** [comment]
It should absolutely work on Linux. Do the auto-exports you set up run? Can you send another debug log with the "send cache" option enabled in the debug-log prompt?

**Comment by dimmenhau** [comment]
i have download the debug log with cache: ID 2JBQ97LI-euc

**Comment by retorquere** [comment]
You don't have any auto-exports set up. Right-click a collection or library, export with Better BibTeX or Better BibLaTeX, and make sure to check the "keep updated" checkbox.

**Comment by dimmenhau** [comment]
Sorry for the trouble, but somehow I must have overlooked that in my tests with GIT, ZOTERO & ShareLaTEX (on Docker).

**Comment by retorquere** [comment]
No worries.
