### ISSUE TITLE
Disable file field in automatic exports

### ISSUE THREAD

**Issue by janosh** [retorquere/zotero-better-bibtex#1600]
**Exporter used:** BibLaTeX

What are common use cases for the `file` field in automatic exports and is there a way to remove it besides [scripting](https://retorque.re/zotero-better-bibtex/exporting/scripting)?

```bib
@article{barber1998ensemble,
  title = {Ensemble Learning in Bayesian Neural Networks},
  author = {Barber, David and Bishop, Christopher M.},
  date = {1998},
  journaltitle = {Nato ASI Series F Computer and Systems Sciences},
  volume = {168},
  pages = {215--238},
  % do i need this?
  file = {/Users/janosh/Library/Zotero/storage/3EYCB5VW/Barber and Bishop - 1998 - Ensemble learning in Bayesian neural networks.pdf}
}
```

**Comment by retorquere** [comment]
I couldn't tell you what common use cases are - I don't use it myself. You can just add it to "skip fields" in the preferences, but that'll remove it for regular exports too.

The other way is indeed by scripting, but I couldn't tell you what the benefit would be over skip-fields.

**Comment by retorquere** [comment]
No worries, it's always OK to ask.
