### ISSUE TITLE
Importing changes "Journal" to "The Journal"

### ISSUE THREAD

**Issue by florisvdh** [retorquere/zotero-better-bibtex#1601]
I'm using Zotero 5.0.89 and Better BibTeX 5.2.47.

**Report ID:** REJZ4MUU-euc

**Full Bib(La)TeX item that I imported:**

This is the bib file (to be unzipped first): [articles.bib.zip](https://github.com/retorquere/zotero-better-bibtex/files/5041361/articles.bib.zip)

These are its contents:

```bibtex
@Article{id1,
  author  = {Family Name, First Name},
  title   = {Title},
  journal = {Journal},
  year    = {2020},
  volume  = {1},
  number  = {2},
  pages   = {3},
}

@Article{id2,
  author  = {Family Name, First Name},
  title   = {Title},
  journal = {Journal of Abcde Research},
  year    = {2020},
  volume  = {1},
  number  = {2},
  pages   = {3},
}

@Article{id3,
  author  = {Family Name, First Name},
  title   = {Title},
  journal = {Abcde},
  year    = {2020},
  volume  = {1},
  number  = {2},
  pages   = {3},
}
```

**Expected behavior:**

All of the above **journal names** should be imported as-is.

**Actual behavior:**

If the journal name is "Journal" (`id1` above), it is converted in Zotero to "The Journal" (as can be seen from below screenshot). This is not the case in the two other examples.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19164640/89646349-e9219e80-d8bb-11ea-96fd-6d1ee0bc2fc3.png)

</details>

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.48.6915](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.48.6915.xpi) ("update testcase for #1601")

Install in Zotero by downloading [test build 5.2.48.6915](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.48.6915.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6915 should fix it. I had an error (mapping "Journal" to "The Journal") in the unabbreviation lists I import from JabRef.

**Comment by florisvdh** [comment]
Thank you!! I confirm this is now fixed. :clap: :tada:

**Comment by retorquere** [comment]
Thanks, a new release has been scheduled.
