### ISSUE TITLE
Change fixated -> fixed

### ISSUE THREAD

**Issue by Benjamin-Lee** [retorquere/zotero-better-bibtex#1604]
In the README, the word "fixated" is used when I believe "fixed" should be.

fixed
> predetermined and not subject to or able to be changed

fixated
> cause (someone) to acquire an obsessive attachment to someone or something.

**Comment by qqobb** [comment]
How about changing the [current paragraph in the README file](https://github.com/retorquere/zotero-better-bibtex/blob/1e17272f0fed263e7e09765948885d67a37f6e99/README.md#facilities-for-generating-citation-keys) to something like this:

### Facilities for generating citation keys
* Automatically generate [citation keys](https://retorque.re/zotero-better-bibtex/citing/) without key clashes! Generate citation keys that take into account other existing keys in your library that are not part of the items you export. Prevent random breakage!
* Generate citation keys based on [JabRef patterns](https://docs.jabref.org/setup/bibtexkeypatterns).
* Set your own, stable citation keys, drag and drop LaTeX citations, add other custom BibLaTeX fields.

(I updated the link to the JabRef website.)

**Comment by retorquere** [comment]
Thnks -- updated

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.48.6917](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.48.6917.xpi) ("fixes #1604")

Install in Zotero by downloading [test build 5.2.48.6917](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.48.6917.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
