### ISSUE TITLE
BBT refuses to export using "tex.referencetype: book"

### ISSUE THREAD

**Issue by nivaca** [retorquere/zotero-better-bibtex#1606]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:** 
IKK2BMGB-euc

**Exporter used:**
Better Biblatex 

**Expected behavior:**
The bib entry should get exported as a @book

**Actual behavior:**
The bib entry gets exported as a @collection. I have added "tex.referencetype: book" in the "extra" field.

![2020-08-09-11-57-08](https://user-images.githubusercontent.com/2309005/89737578-881ed580-da37-11ea-8286-2a22de06ab11.png)

[Exported Items.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5048089/Exported.Items.bib.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.48.6924](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.48.6924.xpi) ("fixes #1606")

Install in Zotero by downloading [test build 5.2.48.6924](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.48.6924.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
With 6924, the `tex.referencetype` should no longer be required.

**Comment by nivaca** [comment]
@blip-bloop Thanks. This build works.

**Comment by nivaca** [comment]
@retorquere Yes, you're right. Even without the "tex.referencetype", the export type is correct.

**Comment by nivaca** [comment]
Should I marked this fixed?

**Comment by retorquere** [comment]
@blip-bloop can't hear you, he's a bot 😄 . The issue will auto-close when I do a new release, which I'm scheduling now.
