### ISSUE TITLE
Case protection to words containing more than two capitalized letters

### ISSUE THREAD

**Issue by DanteSung** [retorquere/zotero-better-bibtex#1607]
IEEE requires to 

> Capitalize all major words in the journal title. Capitalize only the first word of the article and subtitle

For example, the title `Fifty Years of MIMO Detection: The Road to Large-Scale MIMOs` is preferred as: 
`Fifty years of MIMO detection: The road to large-scale MIMOs`.

If I choose the case-protection in bbt, the output will be:
```
title = {Fifty {{Years}} of {{MIMO Detection}}: {{The Road}} to {{Large}}-{{Scale MIMOs}}},
```
Is it possible to change the tile into the following by detecting the number of capitalized letters in every word?
```
title = Fifty years of {{MIMO}} detection: The road to large-scale {{MIMOs}}
```
Thank you for your consideration!

**Comment by DanteSung** [comment]
The debug ID is FGD6S982-euc

**Comment by retorquere** [comment]
You have your titles stored in Zotero in Title Case; [Zotero expects them in sentence case](https://retorque.re/zotero-better-bibtex/support/faq/#bbt-is-changing-the-capitalization-of-my-titles----why).

**Comment by DanteSung** [comment]
Thanks for your reply.

I've selected the `Apply title casing to titles` in Advanced settings but it doesn't work.

Please check `63KRTDWM-euc`

**Comment by DanteSung** [comment]
Seems that I misunderstood your reply.

Did you mean that the title I stored in Zotero should be `Fifty years of MIMO detection: The road to large-scale MIMOs`

**Comment by DanteSung** [comment]
Double-checked the same title in sentence case and selected `Apply title casing to titles` and `case protection` in `Advanced-Export`. This time it works well. Please check `XWKTNY8Q-euc`.

But transforming titles from Title case into sentence case seems to be a lot of work... Any way I can do it automatically?

**Comment by DanteSung** [comment]
Me again 😃 . I googled Zotero's doc and find I can do it by right-clicking the `title` bar one title at a time.

But that option will not preserve any abbrs at all. For example, `MIMO` will be changed into `mimo` and `Apply title casing to titles` and `case protection` can't save it. Please refer to `5W2VTAA6-euc`

Is it possible to perform case protection by counting capitalized letters in the Title case?

**Comment by retorquere** [comment]
> Thanks for your reply.
> 
> I've selected the `Apply title casing to titles` in Advanced settings but it doesn't work.

Titles that are already title-cased won't be affected by this setting. You could try [this](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-case-protection-to-capitalized-words-by-enclosing-them-in-braces).

> Did you mean that the title I stored in Zotero should be `Fifty years of MIMO detection: The road to large-scale MIMOs`

That is correct.

> Me again 😃 . I googled Zotero's doc and find I can do it by right-clicking the `title` bar one title at a time.

That is also correct...

> But that option will not preserve any abbrs at all. For example, `MIMO` will be changed into `mimo` and `Apply title casing to titles` and `case protection` can't save it. Please refer to `5W2VTAA6-euc`

... but as you've found, the algorithm used there is very simplistic.

> Is it possible to perform case protection by counting capitalized letters in the Title case?

I'd really rather not. It is very unfortunate that the vast majority of bibliographic data that is offered to Zotero for import is in such poor shape, but I don't feel it is BBTs job to counteract that, especially when there are no good rules that will cover the situation -- "iPod" for example should get case protection even though it has just one capital, as should family names.

I am going to think about how it can best be corrected in bulk in Zotero.

**Comment by DanteSung** [comment]
I agree that there would be some outliers like "iPod", but I still think by counting the number of capitalized letters could solve probably 90% of the problems since it would make sense for most technical terms.

**Comment by retorquere** [comment]
While it might solve 90% of the problems, it would introduce new problems like no longer protecting iPod and family names, and this would be a breaking change for people who have come to rely on the existing behavior. Sentence-casing the input solves the problem without this breakage.

If the "two-character" rule would do the job, I'd be happy to create a script for you that will lowercase title words with only one capital in Zotero itself.

I am looking into ways to bulk-edit TitleCased input (which should really be a feature Zotero would want to offer), but I'm not willing to introduce breaking behavior on account of malformed input. If you also use LibreOffice or Word, the bibliographies will also not be correct there, as Zotero expects the input to be sentence-cased, not title-cased.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.52.6932](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.52.6932.xpi) ("better sentence case")

Install in Zotero by downloading [test build 5.2.52.6932](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.52.6932.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6932 adds a "BBT sentence case" to the right-click menu. it lowercases everything that:

1. Isn't at a sentence start
2. Is of the shape `<Uppercase><Lowercase>*`

If that works well enough for you, I can add a bulk-change facility. I'm also adding a notifier for when new non-sentencecased titles are added to the library so the "bulk" doesn't have to add up too much over time.

**Comment by DanteSung** [comment]
Thank you so much! That works farily well for me and genuinly saves me from modifying the titles by adding curley braces to MMSE, MIMO, LS, ZF and on and on and on. 😃 

Please add a bulk-change facility if possible. Thanks!

**Comment by retorquere** [comment]
When you say fairly well, are there cases I'm missing? Obviously this will lowercase family names, so post-change inspection will always be necessary, but am I missing other cases?

**Comment by retorquere** [comment]
> Thank you so much! That works farily well for me and genuinly saves me from modifying the titles by adding curley braces to MMSE, MIMO, LS, ZF and on and on and on. 😃

It should never be required to post-edit BBT output; for these cases, Zotero has a way to mark things as no-case-meddling using `<span class="nocase">...</span>` and BBT will always translate that to `{{...}}`. This is a standard Zotero facility that the internal bibliography processor also uses.

**Comment by DanteSung** [comment]
Oops, that's a linguistic misunderstanding. I meant it worked perfectly for my cases 🤣 
I'm not sure what `<span class="nocase">...</span>` means actually. I've tried the Quick Copy option with BibLaTex in the Export panel, it seems to output the form I want but that option per se is not flexible, for example, it will export abstract and I can't customize it at all.

**Comment by retorquere** [comment]
> I'm not sure what `<span class="nocase">...</span>` means actually.

https://www.zotero.org/support/kb/rich_text_bibliography

> I've tried the Quick Copy option with BibLaTex in the Export panel, it seems to output the form I want but that option per se is not flexible, for example, it will export abstract and I can't customize it at all.

https://retorque.re/zotero-better-bibtex/installation/preferences/export/#fields-to-omit-from-export-comma-separated

**Comment by DanteSung** [comment]
Thanks for the reply!

I might not explain myself clearly. I've been using the "fields-to-omit" feature since the beginning. I was saying that if I choose to export references directly through Zotero's BibLaTex, I cannot customize which fields to omit.

Can you please add the bulk facility?

**Comment by retorquere** [comment]
> I might not explain myself clearly. I've been using the "fields-to-omit" feature since the beginning. I was saying that if I choose to export references directly through Zotero's BibLaTex, I cannot customize which fields to omit.

Oh but you can use Better BibLaTex in the Quick Copy option.

> Can you please add the bulk facility?

A build for it is [running through the test suite](https://travis-ci.org/github/retorquere/zotero-better-bibtex/builds/716726605) and will be announced here automatically when it passes.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.52.6933](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.52.6933.xpi) ("bulk sentence caser")

Install in Zotero by downloading [test build 5.2.52.6933](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.52.6933.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by DanteSung** [comment]
Thanks! Now I can go back to issue https://github.com/retorquere/zotero-better-bibtex/issues/1597.
 Probably the only way is to match against the whole title field. That means I need to manually remove all the redundant information.

**Comment by retorquere** [comment]
That means it works as you want? Because then I can merge & close the current issue.

**Comment by DanteSung** [comment]
Yes. It works perfectly!
