### ISSUE TITLE
preprint link to published article

### ISSUE THREAD

**Issue by ADB991** [retorquere/zotero-better-bibtex#1611]
Not everyone has access to journal articles, but everyone has access to arXiv.
I like to include, when available, a link to the arXiv when citing a published journal article.
The way I do it is by adding these fields in the bibtex entry:

    eprint={quant-ph/9609002},
    archivePrefix={arXiv},
    primaryClass={quant-ph}

What should I do, within zotero and BBT, so that when I export the bibtex entry I get these fields too?

The process need not be fully automatic, I don't mind entering some data by hand in Zotero.

**Comment by ADB991** [comment]
GH8S9LZL-euc

**Comment by ADB991** [comment]
it's not a bug, it's a usage question / feature request, but I don't know how to remove `bug` label

**Comment by retorquere** [comment]
You can either add a line to your `extra` field:

```
arXiv: quant-ph/9609002
```

or have a `Journal article` with a `journal` field like:

```
arXiv:quant-ph/9609002
```

**Comment by retorquere** [comment]
> 1. If your issue relates to how BBT behaves around a **specific reference(s)**, such as citekey generation or export, select at least one of the problematic reference(s), right-click it, and submit an BBT debug report from that popup menu. If the problem is with export, please do include a sample of what you see exported, and what you expected to see exported for these references.
> 2. If the issue **does not relate to references** and is of a more general nature, generate an debug report by restarting Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled), reproducing your problem, and selecting "Send Better BibTeX debug report..." from the help menu.

`GH8S9LZL-euc`  was sent using method 2 ("does not relate to references"), I need a log generated by method 1.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.54.6967](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.54.6967.xpi) ("category for pre-2007 arXiv")

Install in Zotero by downloading [test build 5.2.54.6967](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.54.6967.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6967 adds the primaryClass for pre-2007 arXiv keys.

**Comment by ADB991** [comment]
Neither solution works...
The first one, just adds a `note` field in the bibtex entry, like this
```
    @article{rovelli1996,
	title = {Relational {Quantum} {Mechanics}},
	volume = {35},
	doi = {10.1007/BF02302261},
	number = {8},
	urldate = {2020-08-07},
	journal = {International Journal of Theoretical Physics},
	author = {Rovelli, Carlo},
	month = aug,
	year = {1996},
	note = {arXiv: quant-ph/9609002},
}
```
The second one clearly does not work as I am talking specifically for when the article is already published.

**Comment by ADB991** [comment]
For reference, what I want is:
```
    @article{rovelli1996,
	title = {Relational {Quantum} {Mechanics}},
	volume = {35},
	doi = {10.1007/BF02302261},
	number = {8},
	urldate = {2020-08-07},
	journal = {International Journal of Theoretical Physics},
	author = {Rovelli, Carlo},
	month = aug,
	year = {1996},
        eprint={quant-ph/9609002},
        archivePrefix={arXiv},
        primaryClass={quant-ph}
}

```

**Comment by ADB991** [comment]
this is the debug report 5PJNJHDM-euc

**Comment by retorquere** [comment]
Do bibtex styles support these fields? I thought that was a biblatex thing.

If the article is already published, and you want to include the journal name, why include the arXiv information? That would make the reference ambiguous - if the reader wants to pick up the article, should they get it from arXiv or from the publisher?

**Comment by ADB991** [comment]
Yes it works for me. Maybe it is biblatex (texmaker says bib(la)tex so I don't know, sorry).

The reason to include both the DOI and the arXiv identifier is to help out the reader.
Not everyone has access to journals online, or maybe they do, but they need to connect to a VPN.
Also, I like reading the arXiv versions, I'm more used to that typesetting style.

**Comment by ADB991** [comment]
Actually, no, I found it, it is bibtex

**Comment by retorquere** [comment]
I can add them for bibtex, and you can get the ambiguous reference using the `extra` field, but I'd recommend against actually citing anything this way that will actually be submitted to a publisher (or graded if you're still in uni). Ambiguous references will be counted against you.

**Comment by retorquere** [comment]
Wait -- bibtex export already has it. Given `5PJNJHDM-euc` I'm getting the fields as you want. But you have not installed 6967

**Comment by ADB991** [comment]
It's not working for me. I have also tried after installing 6967.  Debug: 2DDBNGTL-euc
I also have trouble as it keeps adding a lot of fields I told it not to add in the Preferences panel (like abstract, file, annote etc)

**Comment by qqobb** [comment]
@ADB991: Are you actually using BBT's export translator? Maybe you're using Zotero's own translator. See [1].

[1] [Zotero and LaTeX/BibTeX](https://libguides.mit.edu/ld.php?content_id=34248570), PDF by Christine Malinowski for MIT Libraries (2018).

**Comment by retorquere** [comment]
Good point - can you post the actual output you get?

**Comment by ADB991** [comment]
damn! that worked!
I'm sorry i wasted your time.... It works exactly as expected!

So, I've been using Zotero export all this time.. Thank god you made BBT!
