### ISSUE TITLE
Citekey � on Windows for references without citation key, on Mac normal citekeys like zotero-1234

### ISSUE THREAD

**Issue by danieltomasz** [retorquere/zotero-better-bibtex#1612]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:**
 6UQDDQXE-euc
**Expected behavior:*
**Actual behavior:**

Hi, I use Zotero between computers.
I use BetterBibtex plugin. I have my library on two computers
While on Mac for different non-paper entries I have citekeys like zotero-1234, the same entries on windows have non-defined citekeys (citekeys appear as �)
How I could solve that?

**Comment by retorquere** [comment]
You've missed point 7.

**Comment by danieltomasz** [comment]
> You've missed point 7.

Thanks, I just updated my initial post.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.53.6961](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.53.6961.xpi) ("fallback needs a postfix")

Install in Zotero by downloading [test build 5.2.53.6961](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.53.6961.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
6961 should fix the problem.

**Comment by danieltomasz** [comment]
I installed test build and it works!

**Comment by retorquere** [comment]
Thanks for the confirmation, I've scheduled a new release.
