### ISSUE TITLE
BBT sentence case?

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#1616]
Today, I've started to see "BBT sentence case" appear as an option in the title casing context menu. What's the difference between this and Zotero's typical sentence case?

**Comment by retorquere** [comment]
This sentence caser won't lowercase words after `;?:.!`, and will only lowercase words that are of the form `/^[A-Z][a-z]*$/`. It also respects `<span class="nocase">`.

There's more sentence-case stuff coming, but the UI isn't really settled yet. For now it lives in BBT advanced prefs under import.

**Comment by retorquere** [comment]
It's still fairly naive. I've actually looked at NLP libraries but the models are very large. I will in an upcoming release remove the option from the menu if the current item is non-English.

**Comment by bwiernik** [comment]
Cool! What's the thinking regarding the punctuation rule? 

Styles like Vancouver don't want subtitles to be capitalized, so users should probably generally store their data with only letters after `!?` uppercased do that those styles are formatted correctly. 

CSL 1.1 will include a "capitalize-subtitle" text case, and Zotero already uppercases the subtitle for styles starting with "apa" and few other styles calling for this behavior.

**Comment by retorquere** [comment]
Oh really? Then I'm just behind the times. Selecting what punctuation triggers this is easy for me to change.

**Comment by retorquere** [comment]
(the reason for adding this to BBT is that I still get comments on superfluous bracing bib(la)tex output for stuff that sits in Zotero in Title Case and I'd rather just say "use this and inspect the results" rather than the umpteenth discussion about how BBT should work accomodate Title-Cased titles)

**Comment by retorquere** [comment]
I've changed it to just `?` and `!`
