### ISSUE TITLE
Citations not downloaded

### ISSUE THREAD

**Issue by ajbrads** [retorquere/zotero-better-bibtex#1617]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:** RYIGFHY7-euc

**Exporter used:**

**Expected behavior:**

**Actual behavior:**

**Comment by retorquere** [comment]
I don't see an export attempt in your log. What were you doing, and what did you expect. As in the template:

**Exporter used:**

**Expected behavior:**
 
**Actual behavior:**

**Comment by ajbrads** [comment]
Sent another debug report with this ref: YZAZK8RI-euc

My problem: after clicking download Bibtex and selecting 'BibTex' in the drop down menu, there is no further menu for where to save the citations and nothing further happens.

This morning I unistalled and re-installedd version 5.2.54 with still the same result

Trust you can make sense of this, as I have nothing to do with programing, coding etc; it is all a bit meaningless to me :) 
Thanks in anticipation of your he

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/exporting/pull/

That dialog only gets you the url to download from. You still have to download it. If you just want to export the items using BBT, you should just use the regular zotero export dialog.

**Comment by ajbrads** [comment]
Hi Emiliano
Please forgive me for being such a dummy! All now working as it should do,
not that I use the correct export 😀
Many thanks for your speedy returns and especially your patience. Have a
great day
Best regards
Adrian

**Comment by retorquere** [comment]
No worries, it's always OK to ask.
