### ISSUE TITLE
Better BibTex never ends the initialization phase

### ISSUE THREAD

**Issue by Polarfuechsli** [retorquere/zotero-better-bibtex#1624]
Hi, 

I am currently encountering a problem with Better BibTex. When I start Zotero, it never finishes the initialization phase, a pop up remains open and the keys are not generated. 

Could you please help me to resolve this issue? 
Thank you in advance for your help! 

**Report ID:UL5K8YF5-euc**

Expected behavior:Better BibTex should finish the Initialization phase.

Actual behavior:A pop-up does not disappear while starting Zotero: Better BibTex: Initializing, "Démarrage du gestionnaire de clés" (Starting of the key manager).

**Comment by retorquere** [comment]
This is a duplicate of #1622, please join that issue.
