### ISSUE TITLE
Unexpected: Different CityKeys on Different Machines - Is this intended?

### ISSUE THREAD

**Issue by finn-matti** [retorquere/zotero-better-bibtex#1629]
(I read the guidelines for submitting an issue but since this is more of a general question, I have not included an error report. I will include one if requested.)

**Report ID:** WDXDHNG9-euc

**Exporter used:** Don't know what this means. Since there has been a report id I assume the answer is yes.

**Expected behavior:**

The key of the item should have been `luhmann1991` from the start on the new machine (as it had been set on the old machine) and then synched using Zotero's sync engine/infrastructure…

**Actual behavior:**

… , but it was not. It was in the BBT standard format `luhmannSozialeSystemeGrundriss1991` instead until I refreshed it. Interestingly enough the Citation key format was already set to `[auth:lower][year]`.

**My question:** Is this a known limitation? Do I have to set up and refresh citation keys on every instance of Zotero from scratch? I understand that BBT has to be installed on both machines for it to work. So synching citations keys between two Zotero instances on two machines probably needs the extension. But are citation keys not synched at all? It seems to me that at least pinned keys seem to be preserved. But why are unpinned keys overwritten in the first place?

Thanks for your help!

**Comment by finn-matti** [comment]
… even though I double checked: This is not an "Export bug/enhancement/question" but a "Key generation bug/enhancement/question". I checked if the guidelines were different for the other issue type: But I couldn't find anything with a quick glance. So hopefully it's just the label. Sorry!

**Comment by finn-matti** [comment]
And I might have found an answer to my question after trawling the closed issues:

 >The only way that currently works is to pin your citekeys. When Zotero gains a citekey field (which has been planned for a long time), they will sync as any other data. When pinned, they'll be put in the extra field, and that will sync; there are also a number of existing Zotero translators (currently BibLaTeX, BibTeX, CSL JSON and TEI) which will recognize that format, and when Zotero gains the citekey field, Zotero will migrate it there.

Source: #1170 

If this the only way to sync keys right now, I would love to be able to pin all keys automatically.

…which now makes this issue a feature request, I guess?

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay

**Comment by finn-matti** [comment]
Thanks! And sorry for this somewhat scattered issue.

**Comment by retorquere** [comment]
No worries.
