### ISSUE TITLE
Version for older Zotero

### ISSUE THREAD

**Issue by gestauffer** [retorquere/zotero-better-bibtex#1631]
I do not have the latest version of Zotero, and will check with our IT department if the latest update is authorized. But it is generally a slow process in our department. As an alternative, what version of BetterBibTex would be supported in Zotero 5.0.84 in the meantime?

**Comment by retorquere** [comment]
It's honestly easier for me to build a one-off of the current version that will work with 5.0.84 than it would be to find out what version worked with 5.0.84.

**Comment by gestauffer** [comment]
OK. Well, I'll see if my request to update Zotero gets approved, and in the meantime I can update my already-exported library manually with new entries.

**Comment by retorquere** [comment]
I mean I can get you a current version that will accept 5.0.84, either tonight, or Sunday afternoon.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.66.7096](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7096.xpi) ("skip more latest-version safeguards")

Install in Zotero by downloading [test build 5.2.66.7096](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7096.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
7096 should work on 5.0.84
