### ISSUE TITLE
Option to "Append" exports to existing bib file

### ISSUE THREAD

**Issue by Nidish96** [retorquere/zotero-better-bibtex#1632]
Thank you very much for this add-on - it seems to be really nice.

I was wondering if it would be easy to add an export feature that would just append to an existing .bib file. This, in my opinion, would greatly speed up my writing as I often forget to export one or two references and I end up exporting those files to a completely new bib file and inserting that onto my project's bib file.

If such a feature is already there, please do let me know how.

Edit: This suggests me to have a Debug ID, so here it is (although I don't have any errors/warnings): X9JT8HNW-euc 
This is an enhancement question.

Best,
Nidish

**Comment by retorquere** [comment]
When you pick the `question` category, you don't get a prompt for a debug log.

Zotero translators don't write the file themselves, Zotero does it on their behalf, so append isn't possible. But why not just use auto-export? That will keep the bib file updated with changes.

**Comment by retorquere** [comment]
And if you don't want to use that, you could use Zotero's quick copy to drag and drop the new items into an existing file.

**Comment by Nidish96** [comment]
Thank you. I was aware of auto-export but that was not what I had in mind and was wondering if there was something better. 
quick copy, although not perfect, is probably the next best thing (I wasn't aware this exists, so thank you).

I'm closing the issue since it's probably better put to Zotero developers than here, going by your response. Thanks again!

**Comment by retorquere** [comment]
It's not really what export in Zotero was designed for I'm afraid. But does the target file have multiple (possibly non-Zotero) sources then?

Another option could be to use the CAYW functionality:

```
curl 'http://127.0.0.1:23119/better-bibtex/cayw?format=translate&translator=biblatex&minimize=true' >> test.bib
```

will bring up the zotero picker and add whatever you pick to the end of the bib file.

**Comment by retorquere** [comment]
Or

```
curl 'http://127.0.0.1:23119/better-bibtex/export/selected?biblatex' >> test.bib
```

if you want whatever you have selected in Zotero.
