### ISSUE TITLE
How to ignore square brackets in veryshorttitle?

### ISSUE THREAD

**Issue by fmge** [retorquere/zotero-better-bibtex#1633]
Report ID: FKKMEVIC-euc

I use the following pattern for generating my citekeys: `[auth:lower][year][veryshorttitle:lower]`. However, for a title that starts with the word _Manif[est]_ it creates gschwind2015manif as a citekey. How square brackets in the title can be ignored to get gschwind2015manifest as a result?

Thanks for your help!

**Comment by qqobb** [comment]
@fmge: If you pin the citation key, you can manually set it to whatever you prefer. Could this provide a solution for you? There is also value in keeping things simple, so unless you have a large number of items with this issue, I would just do it that way.

**Comment by fmge** [comment]
Yes this is an acceptable solution! Thanks for your help!

**Comment by retorquere** [comment]
Only I can close issues that are not marked `question`. Thanks for stepping in!

**Comment by fmge** [comment]
Ok, thanks. I have one more question. It's more of a hint (regarding skipwords). Should I post it here or open a new issue?

**Comment by retorquere** [comment]
I prefer a new issue.
