### ISSUE TITLE
Links broken on website

### ISSUE THREAD

**Issue by statzhero** [retorquere/zotero-better-bibtex#1634]
The first two links seem to go nowhere: https://retorque.re/zotero-better-bibtex/exporting/pandoc/

Probably just needs to be updated.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.66.7100](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7100.xpi) ("fixes #1634")

Install in Zotero by downloading [test build 5.2.66.7100](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7100.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
