### ISSUE TITLE
[Feature] Add Markdown Link support in QuickCopy

### ISSUE THREAD

**Issue by whitenoisedev** [retorquere/zotero-better-bibtex#1635]
I don't think I need to convince you how popular markdown is.
Would it be possible to add a couple of markdown option in QuickCopy format.

For example:
Markdown Link with Citekey select link
`[@citekey](zotero://select/items/@citekey)`

Markdown Link with Zotero select link
``[@citekey](zotero://select/library/items/zotid)``

Ultimately, it would be nice to use the same expressive power as in `Citation Keys` to construct a custom markdown link 
`[[auth] [Title] [year]](zotero://select/items/@citekey)` 

Thank you for this great software.

**Comment by aboharbf** [comment]
I second this request. I realize the functionality is present in a hacky way if you use the post script box under the 'Advanced' tab, but a more straightforward, user friendly way would be fantastic.

**Comment by fastexitlane** [comment]
Perhaps a little late to the party, but I roughly built a seperate translator as "workaround" for that purpose myself yesterday: https://gitlab.com/-/snippets/2089075
This copies the Zotero select link with author-year-style description as markdown link. Building the same thing for citekey select links should be easy. However, I don't know how to integrate this with BBT, so that you can choose this as quick copy format in the settings there.

**Comment by retorquere** [comment]
Apologies guys -- with the craziness of last year issues have slipped my attention. Build 507 adds [eta](https://eta.js.org/) template support. Use of it will be (rather summarily I'm afraid) be described on the site as

```
Used for drag-and-drop/quick copy citations in `Build your own` format. This is going to get pretty technical, sorry.

          You can paste a [Eta](https://eta.js.org/) template here. Inside the template, you will find an array `it.items`, each of which is a serialized Zotero item.
          To find out what an item looks like inside the template, export some items as BetterBibTeX JSON.
```

for `[@citekey](zotero://select/items/@citekey)` you'd add this in the preferences:

```
<% for (const item of it.items) { %>[@<%= item.citationKey %>](zotero://select/items/@<%= item.citationKey %>)<% } %>
```

Adding the citekey format functions would be a major undertaking as Zotero enforces that the translators and the rest of the code live in distinct environments, so I can't access the citekey formatter functions in the translator.

**Comment by fastexitlane** [comment]
Now this sounds nice!

The latest betas (507 + 508) completely remove the BBT settings pane, though. Debug ID is `C2G5HGQJ-euc`. This debug output looks suspicious to me:

```
[JavaScript Error: "XML Parsing Error: undefined entity Location: chrome://zotero-better-bibtex/content/Preferences.xul Line Number 527, Column 25:" {file: "chrome://zotero-better-bibtex/content/Preferences.xul" line: 527 column: 25 source: " <menuitem label="&better-bibtex.Preferences.citekey.quickCopy.etaTemplate;" value="eta"/>"}]
```

**Comment by retorquere** [comment]
The pre-release builds only support English, sorry.

**Comment by retorquere** [comment]
(I'm not sure how Zotero decides what language to load with. Maybe it's just a setting in Zotero)

**Comment by retorquere** [comment]
eta support has been released, so will work in non-English Zotero.
