### ISSUE TITLE
Postscript export: Moving website title from journal to howpublished field

### ISSUE THREAD

**Issue by niloysh** [retorquere/zotero-better-bibtex#1638]
This is not an error report or an enhancement request, I just have a **question**.

I am using the **Better BibTex exporter** and I have a reference of type ```webpage``` that I want to export to .bib and include it in my LaTex file using the IEEEtran style.

![zotero-ref](https://user-images.githubusercontent.com/31400952/92933964-8b591700-f464-11ea-9e7f-c2eafd7968c8.png)

I have found the corresponding **postscript snippet** on the documentation page that adds ```access date``` and ```URL```. It works as expected. It uses the ```@misc``` field and outputs the website title to the journal field. I have also turned on the export URL feature.

![bib-output](https://user-images.githubusercontent.com/31400952/92934196-d7a45700-f464-11ea-918e-d5f49f10a84a.png)

Now, the IEEEtran style does not actually output the contents of the ```journal``` field (which represents the content of website title} in ```@misc``` type entry.
![ieeetran-bst](https://user-images.githubusercontent.com/31400952/92934430-19cd9880-f465-11ea-9165-3aaf26eb1384.png)

But IEEE reference guide states that the Website title should be given as follows:
![ieee-reference-guide-snippet](https://user-images.githubusercontent.com/31400952/92934537-3a95ee00-f465-11ea-8b26-ac4bbdc621e3.png)

Since I am already using the URL, I want to remove ```URL``` from ```howpublished``` and move the website title to ```howpublished```, so that it is displayed properly. So, my question is **How can I modify the postscript snippet to have ```website title``` show up in the ```howpublished``` field?**

So far I have tried to access it using ```item.websitetitle``` or ```item.websiteTitle``` but could not get it to work. Thanks for your help.

**Comment by retorquere** [comment]
If you pick `question` from [New Issue](https://github.com/retorquere/zotero-better-bibtex/issues/new/choose), @label-gun doesn't come into action. Anyhow, in this case I really do want a debug log as per instruction 1. from @label-gun. It will give me a copy of the item I can import into Zotero so I don't have to retype the screenshot.

**Comment by retorquere** [comment]
This should do it:

```
if (Translator.BetterBibTeX && item.itemType === 'webpage') {
  if (item.accessDate) reference.add({ name: 'note', value: `(accessed ${item.accessDate.replace(/\s*T?\d+:\d+:\d+.*/, '')})` })
  if (item.url) reference.add({ name: 'howpublished', bibtex: `{\\url{${reference.enc_verbatim({value: item.url})}}}` })
  if (item.publicationTitle) reference.add({ name: 'howpublished', value: item.publicationTitle })
}
```

If you want to know what items look like inside the postscript, you can export them as `BetterBibTeX JSON`.

**Comment by niloysh** [comment]
It works perfectly! The part about exporting them as ```BetterBibtTex JSON``` was also very helpful. I would suggest adding this one line in the documentation in the scripting section. It would help users perform simple modifications to the example scripts given there.

Since my question has been answered, I am closing this issue. Thanks again for the wonderful  software.
