### ISSUE TITLE
Entries with URL exported with (partial) URL in eprint field

### ISSUE THREAD

**Issue by shotcollin** [retorquere/zotero-better-bibtex#1639]
*Please verify **all** of the below before submitting*:

**Report ID:** X2AJBF78-euc and VHQYQF5C-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** Zotero field ```URL``` is exported to field ```url``` in .bib file. This is what happens with other entries that have URLs. 

@article{Mehrling2000,
  title = {Modern Money: Fiat or Credit?},
  author = {Mehrling, Perry},
  date = {2000},
  journaltitle = {Journal of Post Keynesian Economics},
  volume = {22},
  pages = {397--406},
  url = {https://www.jstor.org/stable/4538686}
}

**Actual behavior:** Zotero field ```URL``` is exported to field ```eprint```. This appears to only affect items with URLs from JSTOR. These items also have ```eprinttype``` set to {jstor}.

@article{Mehrling2000,
  title = {Modern Money: Fiat or Credit?},
  author = {Mehrling, Perry},
  date = {2000},
  journaltitle = {Journal of Post Keynesian Economics},
  volume = {22},
  pages = {397--406},
  eprint = {4538686},
  eprinttype = {jstor}
}

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.66.7135](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7135.xpi) ("optionally extract eprint info from url")

Install in Zotero by downloading [test build 5.2.66.7135](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7135.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
7135 has a new option in the export tab to disable eprint extraction.

**Comment by retorquere** [comment]
7135 adds a preference in the export pane to regulate the behavior.

**Comment by retorquere** [comment]
Can you test if this is what you need?

**Comment by shotcollin** [comment]
Sorry for the delay. Yes, that works. Thanks!
