### ISSUE TITLE
Exporting collections names

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#1642]
I'm trying to construct postscript expression to include Zotero collection name the item belongs to. But simple:

```js
 if (item.collections) reference.add({ name: 'coll', value: item.collections });
```

as a result gives some - I suppose - ID's of collections concatenated in one string:

```
  coll = {29RZVFBNEBJEX6H9VC4E2SB43CXKTH742YEX6VUS}
  coll = {3CXKTH74KCTN247F}
  coll = {AF44D2WE2YEX6VUSKCTN247F}
  coll = {3CXKTH74KCTN247F}
  coll = {8S2TIGZ4VC4E2SB42YEX6VUSKCTN247F}
  coll = {3CXKTH74M4DDFV4X2YEX6VUS}
```

How to get the "friendly" names of the collections? Similarly, like for keywords (tags) export?

The bug report ID is: 62SKTAMA-euc

Darek

**Comment by retorquere** [comment]
This should do it:

```
if (Translator.BetterBibLaTeX) {
  var ityear = Zotero.BetterBibTeX.parseDate(item.date).year;
  reference.add({ name: 'zoterolocal', value: 'zotero://select/items/@' + item.citationKey });
  if (item.uri) reference.add({ name: 'zoterouri', value: item.uri });
  if (item.date) reference.add({ name: 'year', value: `${ityear}`});
  if (item.DOI) reference.add({ name: 'doiuri', value: 'https://doi.org/' + item.DOI });

  if (item.collections) reference.add({ name: 'coll', value: item.collections.map(coll => Translator.collections[coll].name), sep: ', ' });
}
```

When `add` is passed an array value, it concatenates the elements using the `sep` parameter (which is blank by default). You can see what `Translator.collections` looks like by exporting in BBT JSON format.

**Comment by dbobak** [comment]
@retorquere, it does not work. The "coll" field does not appear in exported file.

Report ID: 5ELY2X3X-euc

**Comment by retorquere** [comment]
`5ELY2X3X-euc` does not contain any collections.

**Comment by dbobak** [comment]
@retorquere, i tried again. In postscript I put two lines, one exporting collections IDs, second - translated collection names:

```js
if (Translator.BetterBibLaTeX) {
	var ityear = Zotero.BetterBibTeX.parseDate(item.date).year;
	reference.add({ name: 'zoterolocal', value: 'zotero://select/items/@' + item.citationKey });
	if (item.uri) reference.add({ name: 'zoterouri', value: item.uri });
	if (item.date) reference.add({ name: 'year', value: `${ityear}`});
	if (item.DOI) reference.add({ name: 'doiuri', value: 'https://doi.org/' + item.DOI });
	if (item.collections) reference.add({ name: 'coll', value: item.collections });
	if (item.collections) reference.add({ name: 'coll2', value: item.collections.map(coll2 => Translator.collections[coll2].name), sep: ', ' });
}
```

The IDs are exported, the names - not.

Report ID: KBVT4UGR-euc

And here is generated BibLaTex file:
[__test4.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5230868/__test4.bib.txt)

**Comment by retorquere** [comment]
Shit, it's a caching issue. I'll have to disable the cache if you're accessing the collections, because what actually turns up in the output is dependent on the collection tree you're exporting.

For now, you will have to clear the cache before export, and change the line to:

```
if (item.collections) reference.add({ name: 'coll2', value: item.collections.map(coll => Translator.collections[coll]?.name).filter(coll => coll), sep: ', ' });
```

But as far as I can tell, you are exporting the collection these items sit in themselves, and Zotero does not make that "root collection" available to translators. Only collections somewhere under the collection you are exporting are passed to the translator.

I'll get a fix for the caching problem.

**Comment by dbobak** [comment]
@retorquere, I have:
1. added the line to the postscript field. It got orange; removing the question mark from `[coll]?.name)` corrected the problem, but I'm not sure if it's ok.
1. cleared the cache (preferences -> BBT -> Advanced -> Export -> Reset cache)
1. exported some collection with subcollections, then - exported some manually selected items.
1. in both cases still no effect: collections ID's are exported, collections names - not.

And I usually export entire library (manually selecting items without some scratch and temporary items), not collections. I do not know, if it matters.

Report ID: FZPD7GHM-euc

**Comment by retorquere** [comment]
Huh, strange, I thought I had tested that, but my postscript didn't have it, and it indeed does not compile (which is what the orange means).

Try

```
if (item.collections) reference.add({ name: 'coll', value: item.collections.filter(coll => Translator.collections[coll]).map(coll => Translator.collections[coll].name), sep: ', ' });
```

when the postscript is orange, the last compilable version remains active.

Is `FZPD7GHM-euc` from your entire library?

**Comment by dbobak** [comment]
@retorquere, now it works. Thank you! 

Here are the results of some tests. Exports 1-3 are is done after reseting the cache:

1. Exporting entire library (clicking on the library in the left pane):
	collections are exported.
2. Exporting one of the collections (with subcollections):
	subcollections are exported, top-level collection - not.
3. Exporting manually selected items (clicking on the references pane):
	no collections are exported.
4. Exporting manually selected items WITHOUT resteting the cache:
	collections are exported.

In all the cases above, parent collection of the subcollection item belongs to is not exported, unless item is explicitly assigned also to parent collection.

>Is FZPD7GHM-euc from your entire library?

No, it's from one of the subcollections. Entire library counts more than 3000 items. I have a quite elaborated collections tree, treating them as hierarchical, categorized tags.

**Comment by retorquere** [comment]
> @retorquere, now it works. Thank you!
> 
> Here are the results of some tests. Exports 1-3 are is done after reseting the cache:
> 
>     1. Exporting entire library (clicking on the library in the left pane):
>        collections are exported.

Correct, and as intended by Zotero. Nothing I can do about this.

>     2. Exporting one of the collections (with subcollections):
>        subcollections are exported, top-level collection - not.

Correct, and as intended by Zotero. Nothing I can do about this.

>     3. Exporting manually selected items (clicking on the references pane):
>        no collections are exported.

Correct, and as intended by Zotero. Nothing I can do about this.

>     4. Exporting manually selected items WITHOUT resteting the cache:
>        collections are exported.

This is a bug that I am working on to fix. It should behave as point 3.

> In all the cases above, parent collection of the subcollection item belongs to is not exported, unless item is explicitly assigned also to parent collection.

I don't understand what you're expressing here, sorry.

FZPD7GHM-euc does not contain collections, so if all is right, this should either be a collection with no further subcollections, or manually selected items.

**Comment by dbobak** [comment]
> I don't understand what you're expressing here, sorry.

Does not matter, just tried to show behaviour of the Zotero when exporting collections. For now the postrscript works almost perfectly, just have to remember to clear the cache manually. 

Thank you!

**Comment by retorquere** [comment]
I'm still looking to get a fix out, but try this for the interim:

```
if (Translator.BetterBibLaTeX) {
  var ityear = Zotero.BetterBibTeX.parseDate(item.date).year;
  reference.add({ name: 'zoterolocal', value: 'zotero://select/items/@' + item.citationKey });
  if (item.uri) reference.add({ name: 'zoterouri', value: item.uri });
  if (item.date) reference.add({ name: 'year', value: `${ityear}`});
  if (item.DOI) reference.add({ name: 'doiuri', value: 'https://doi.org/' + item.DOI });

  if (item.collections) reference.add({ name: 'coll', value: item.collections.filter(coll => Translator.collections[coll]).map(coll => Translator.collections[coll].name), sep: ', ' });
  return false // this instructs BBT to not cache the item
}
```

The fix I'm working on will automate that if you access `item.collections` in the postscript

**Comment by dbobak** [comment]
> `return false // this instructs BBT to not cache the item`

Seems this fix works. Exported, changed the item collections, exported again. Collections are updated.

**Comment by retorquere** [comment]
It's not a fix, really, rather a workaround. A fix is [building](https://travis-ci.org/github/retorquere/zotero-better-bibtex/builds/727691620).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.66.7130](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7130.xpi) ("fine-grained cache disabler")

Install in Zotero by downloading [test build 5.2.66.7130](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.66.7130.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
7130 should not require the `return false`

**Comment by retorquere** [comment]
Also has a much more precise and fine-grained cache disabler.

**Comment by dbobak** [comment]
The test build works ok. The collections are updated without manually resetting the cache.
