### ISSUE TITLE
[Question] urldate not exported

### ISSUE THREAD

**Issue by elya5** [retorquere/zotero-better-bibtex#1645]
Hi

for website references, the urldate does not get exported. Is there anything I need to activate for that? Should it happen automatically?

**Comment by retorquere** [comment]
The issue type picker starts off with:

>  Export bug/enhancement/question
> You appear to have found a bug in BBTs export, are proposing an enhancement to the exports, or ***have a question about exporting items***

That would have brought you to 

> 7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
> 8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

I really need these. Otherwise I'm just guessing at what your situation looks like.

**Comment by elya5** [comment]
Whoops. Sorry for picking the wrong category

I just figured it out myself. Thanks for the quick reply though

**Comment by fcastilloec** [comment]
@elya5 Can you help everybody landing on this issue by letting us know how did you manage to add a `urldate` field?
I'm trying to set the `urldate` to the `item.accessDate` but no matter what I do, `urldate` never gets added

**Comment by retorquere** [comment]
Most likely cause is that there's no `url` field in the entry. BBT doesn't
export the `urldate` field of there's no `url`. To get the `urldate` she
must have either added an URL to the zotero item, or added the `urldate`
with a postscript.

**Comment by elya5** [comment]
For me, I had to set the option to add the URLs to the export in the "automatic export" section.

**Comment by retorquere** [comment]
And that meant the export has an `url`, so `urldate` gets output.
