### ISSUE TITLE
Exporting parent collections

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#1646]
Referring to a #1642. Is it possible to export not only a collection the item belongs to, but also a parent collections of that collection? For example:

```
Collection1
   |
   Collection2
      |
      Collection3
         |
         item
```
When exporting Collection1, I would like to have in exported bib file not only Collection3 name, but also Collection2 and Collection1.

best 
Darek

**Comment by dbobak** [comment]
ad. 1. Root collection is not critical, it's the same for all exported items, so it could easily be assigned manually.
ad. 2.
Chosing jabref4 option, collections are not exported at all (see attachments).
When jabref3 if choosen, the collection are exported, but:
1. the file is focused on the collection, not item (at the end there is a collection list with item assigned)
2. only explicitly assigned collections are exported; parent collections are not if the item is not explicitly assigned to them also.

I'm attaching two bib files (with jabref3 and jabref4 option) and screenshot of the exported collection tree.

Report ID: GAHTYAPH-euc

![obraz](https://user-images.githubusercontent.com/6285546/93612571-f314e200-f9cf-11ea-96ac-1df9e944a532.png)
[jr3@Environment.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5246244/jr3%40Environment.bib.txt)
[jr4@Environment.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5246245/jr4%40Environment.bib.txt)

**Comment by retorquere** [comment]
Both of those exports do show the collections; in the jabref 3 format, everything is at the bottom, in the (IMO inferior) jabref 4 format, the structure is at the bottom, and the collection membership sits in the `groups` for each entry.

What had you wanted to see? bibtex doesn't really have anything for "collections" as far as I know. Jabref adds this format itself, but it's non-standard.

**Comment by retorquere** [comment]
> Chosing jabref4 option, collections are not exported at all (see attachments).

For JabRef 4 format, you need to piece together the structure at the bottom, and the membership in the `groups` field of each entry. I'm not fond of this either, but that's how JabRef does it.

> When jabref3 if choosen, the collection are exported, but:
> 
>     1. the file is focused on the collection, not item (at the end there is a collection list with item assigned)

Again, not my choice. I think the JabRef format is inelegant (group assignment is limited in the `4` format, and JabRef will happily write broken `groups` fields if you have characters like `%` or `#` in the group name, but that's just how they do it, and there isn't really any other collection-structure that I know of in bib(la)tex.

>     2. only explicitly assigned collections are exported; parent collections are not if the item is not explicitly assigned to them also.

But that's what Zotero reports to translators, and by default, that's how Zotero displays collections. Items in child collections do not show up in parent collections by default.

**Comment by dbobak** [comment]
> What had you wanted to see? bibtex doesn't really have anything for "collections" as far as I know. Jabref adds this format itself, but it's non-standard.

Yes, I know it's not standard. I'm just looking for the way to classify my collection and the collections were the best choice (because of the possibility of building hierarchy). And now I try to join Zotero with TiddlyWiki knowledge base. TW imports bibtex, that's why I choose the format. To the point. I'd like to have result which lists item collection and paret collections of the collection item belongs to.

For example.
1. If the item belongs to the MIS2 collection, I'd like to have in bib file:
`collection = {MIS2, Weichselien, Pleistocene}`
2. If the item belongs to the Weichselien, I'd like ot have:
`collection = {Weichselien, Pleistocene}`
3. If the item belongs to the MIS2 and Loess collections, I'd like:
`collection = {Loess, MIS2, Weichselien, Pleistocene}`

**Comment by retorquere** [comment]
If you want the hierarchical collection path, you'd have something like this:

```
if (Translator.BetterBibLaTeX) {
  function collection(id) {
    if (!Translator.collections[id]) return []
    return collection(Translator.collections[id].parent).concat([ Translator.collections[id].name ])
  }

  var ityear = Zotero.BetterBibTeX.parseDate(item.date).year;
  var icon = this.referencetype;
  reference.add({ name: 'zoterolocal', value: 'zotero://select/items/@' + item.citationKey });
  if (item.uri) reference.add({ name: 'zoterouri', value: item.uri });
  if (item.date) reference.add({ name: 'year', value: `${ityear}`});
  if (item.DOI) reference.add({ name: 'doiuri', value: 'https://doi.org/' + item.DOI });
  if (reference.has.subject) reference.has.subject.bibtex = reference.has.subject.bibtex.replace(/\\/g, '').replace(/^{/g, '{[[').replace(/}$/g, ']]}');
  if (reference.has.keywords) reference.has.keywords.bibtex = reference.has.keywords.bibtex.replace(/\\/g, '').replace(/^{/g, '{[[').replace(/}$/g, ']]}').replace(/\,/g, ']] [[');
  reference.add({ name: 'icon', value: `${icon}` + ".svg"});

  if (item.collections) {
    reference.add({
      name: 'subject',
      value: item.collections.filter(subject => Translator.collections[subject]).map(subject => Translator.collections[subject].name),
      value: item.collections.map(id => collection(id).join(', ')),
      sep: ']] [['
    })
  }
}

```

**Comment by retorquere** [comment]
(`GAHTYAPH-euc` only exported a single item, and Zotero then does not offer collection info to the translators BTW. I imported from `jr3@Environment.bib.txt` for the test)

**Comment by dbobak** [comment]
Thanks, it works well. It sometimes exports duplicate parent collection names, but it's not a problem at all. Also, some strange things happend, when I've changed the separator. But it's not a problem, regexps deals with it. Here's my version of the code:

```
if (Translator.BetterBibLaTeX) {
	function collection(id) {
		if (!Translator.collections[id]) return []
		return collection(Translator.collections[id].parent).concat([ Translator.collections[id].name ])
	}

	var ityear = Zotero.BetterBibTeX.parseDate(item.date).year;
	var icon = this.referencetype;
	reference.add({ name: 'zoterolocal', value: 'zotero://select/items/@' + item.citationKey });
	if (item.uri) reference.add({ name: 'zoterouri', value: item.uri });
	if (item.date) reference.add({ name: 'year', value: `${ityear}`});
	if (item.DOI) reference.add({ name: 'doiuri', value: 'https://doi.org/' + item.DOI });
	if (reference.has.keywords) reference.has.keywords.bibtex = reference.has.keywords.bibtex.replace(/\\/g, '').replace(/^{/g, '{[[').replace(/}$/g, ']]}').replace(/\,/g, ']] [[');
	reference.add({ name: 'icon', value: `${icon}` + ".svg"});

	if (item.collections) {
		reference.add({
			name: 'subject',
			value: item.collections.filter(subject => Translator.collections[subject]).map(subject => Translator.collections[subject].name),
			value: '[[' + item.collections.map(id => collection(id).join(']] [[')) + ']]',
			sep: ']] [['
		})
	};

	if (reference.has.subject) reference.has.subject.bibtex = reference.has.subject.bibtex.replace(/\\/g, '').replace(/(,+)]/g, ']').replace(/\[(,+)/g, '[').replace(/,+/g, ']] [[').replace(/\[\[]]/g, '');
}
```

**Comment by retorquere** [comment]
```
value: item.collections.filter(subject => Translator.collections[subject]).map(subject => Translator.collections[subject].name),
value: '[[' + item.collections.map(id => collection(id).join(']] [[')) + ']]',
```

Javascript dicts can't have duplicate keys. The FF engine will most likely pick the last, but I think the language spec doesn't guarantee a deterministic result.

> It sometimes exports duplicate parent collection names

If an item is in multiple collections, that's what will happen; in the current setup, it will output the full hierarchical path for each of the collections it's in.

> Also, some strange things happend, when I've changed the separator

Strange in what sense?

The separator won't get latex-conversion BTW.

**Comment by dbobak** [comment]
> Strange in what sense?

Inserts random commas and omits my separator `]] [[`
Some samples from attached bib file:
```
AubryEtAl2014MiddletoUpper
subject = {[[Site formation,,,]]}

BackenbachEtAl2014Potential
subject = {[[,Pleistocene]] [[Weichselian]]}

BarbieriEtAl2017Bridging
subject = {[[,,,,]]}
  
BartonRielSalvatore2014Formation
subject = {[[Site formation,]]}

BlackEtAl2015Campanian
subject = {[[,,Climate,]]}

Bradley2015Paleoclimatology
subject = {[[Climate,Pleistocene]] [[Weichselian,Loess,,]]}  
```
I'm also attaching exported Zotero RDF of the same collection.

> The separator won't get latex-conversion BTW.

That's OK for me. The importer in TiddlyWiki [bibtexParse.js](https://github.com/ORCID/bibtexParseJs/blob/master/bibtexParse.js) cannot interpret latex escapes, so anyway I'm replacing them with regexp.

[@Environment.bib.zip](https://github.com/retorquere/zotero-better-bibtex/files/5251904/%40Environment.bib.zip)
[@Environment.rdf.zip](https://github.com/retorquere/zotero-better-bibtex/files/5251905/%40Environment.rdf.zip)



Report ID: H5LAZ8W9-euc

**Comment by retorquere** [comment]
They're not random as such -- `item.collection` contains all collection IDs that an item is part of, but only hands the corresponding collection info for the collections actually beingexported at the time to translators, so some paths will be empty because there is no corresponding `Translator.collections[id]`. This should do it:

```
if (item.collections) {
  reference.add({
    name: 'subject',
    value: item.collections
      // map collection to hierarchical path
      .map(id => collection(id).join(', '))
      // remove paths for which no collection info was passed
      .filter(coll => coll !== '') // `coll => coll` would have done the same, as an empty string is false-ish to javascript 
      // surround each apth found with square brackets
      .map(coll => `[[ ${coll} ]]`) 
      // and join them with a space (`sep: ' '` would have done the same)
      .join(' ')
  })
}
```

> That's OK for me. The importer in TiddlyWiki bibtexParse.js cannot interpret latex escapes, so anyway I'm replacing them with regexp.

But then why bother with bibtex exports? Why not just JSON exports?

**Comment by dbobak** [comment]
Ok, I get it. Thanks a lot, the script now works perfectly.

> But then why bother with bibtex exports? Why not just JSON exports?

TiddlyWiki cannot import JSON as bibliographical data. With BibTeX it works (not very well, but - it works) out of the box.
