### ISSUE TITLE
CAYW format: {cite}`reference` format for MyST markdown

### ISSUE THREAD

**Issue by darikg** [retorquere/zotero-better-bibtex#1652]
I'm using Citation Picker for Zotero in VS Code, writing Jupyter Book MyST markdown files. It uses the 

```
{cite}`reference`
```

format. I think I just need to pick/make the right format [here](https://retorque.re/zotero-better-bibtex/citing/cayw/#diy)

Is it currently already supported or would I have to make a new translator?

Thanks!

**Comment by retorquere** [comment]
I'm working on a more flexible way to do this, but a translator of your own would work.

**Comment by darikg** [comment]
Thanks @retorquere! Do you happen to have a link to an example translator implementation?

**Comment by retorquere** [comment]
https://www.zotero.org/support/dev/translators/scaffold . But I'm working on something to make it more flexible inside BBT.

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/citation-keys/#eta-template
