### ISSUE TITLE
Any danger in leaving citeprocnotecitekey enabled?

### ISSUE THREAD

**Issue by gasedwards** [retorquere/zotero-better-bibtex#1653]
Hi there, in your instructions for the [citeprocnotecitekey](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#citeprocnotecitekey) hidden preference, you say "Please disable it when done". 

Is there any danger in leaving it enabled? If its a stability issue or something I'll toggle as and when needed, but after some searching this preference and your custom CSL file solved a non-trivial issue for me in getting documents back to markdown from docx without losing or having to hand-code all references!

Thanks 😄

**Comment by retorquere** [comment]
No, no stability issues (it doesn't screw more than BBT usually does with zotero if you have it on), it's just that it will obviously give non-standard results for styles that use the note field, and I want to prevent spurious error reports to the zotero devs.

**Comment by gasedwards** [comment]
Thanks - very helpful!
