### ISSUE TITLE
Better BibTeX options pane not visible anymore

### ISSUE THREAD

**Issue by mikulcak** [retorquere/zotero-better-bibtex#1654]
Hi, 

I have encountered a weird error/bug: The Better BibTeX preference pane is not visible in the Zotero Preferences anymore. It is still active and continues to export data (although there something going wrong there as well, but I'll file a separate issue for that), but I cannot access the preferences anymore. Of course I've tried restarting Zotero and rebooting my machine, but to no avail. 

The debug log id is: 7RXR5DVB-euc
The version is 5.2.72

I hope the log helps you.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.72.7178](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.72.7178.xpi) ("late init")

Install in Zotero by downloading [test build 5.2.72.7178](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.72.7178.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by vitorn** [comment]
Hi,

I have the same problem - I have no idea when it started (it's been a while I don't look at the Zotero preferences pane), but the Better BibTeX tab isn't there.  I thought I might have messed up the configuration (I sincronize the Zotero files with between a laptop and a desktop, both under macOS Catalina), so I tried uninstalling Better BibTeX (and even removing the files from the Zotero folder), but the problem remains.  The exporter still works. 

I tried installing the test build, but no difference.

The debug log id is LF7TICK7-euc

Thanks!

**Comment by retorquere** [comment]
Can you both please try build 7178.

**Comment by retorquere** [comment]
Apologies @vitorn -- yours is indeed from 7178, but it's a different issue. I'll get you a build when I'm back at my PC.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.72.7185](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.72.7185.xpi) ("translations for de-DE and pt-BR")

Install in Zotero by downloading [test build 5.2.72.7185](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.72.7185.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
@vitorn 7185 should fix your problem

**Comment by mikulcak** [comment]
Nice, that fixed it! That it could be something as "simple" as a missing translation didn't occur to me at all. Thank you so much!

**Comment by retorquere** [comment]
There's no way you could have known. @mikulcak, I still need confirmation that 7178 fixes your problem, because it's unrelated to @vitorn's problem.

**Comment by mikulcak** [comment]
So far it looks good (although only with background exports disabled) - exports that failed yesterday are working perfectly today.

**Comment by retorquere** [comment]
But not with background exports enabled?

**Comment by mikulcak** [comment]
No, unfortunately not. I'll try to generate a debug log with background exports enabled.

**Comment by retorquere** [comment]
On a new issue please.

**Comment by vitorn** [comment]
Good morning!

I just did a quick test with 7185, and all seems to be working fine, many thanks!
