### ISSUE TITLE
Export to BibLaTeX fails

### ISSUE THREAD

**Issue by mikulcak** [retorquere/zotero-better-bibtex#1655]
debug id is: 7RXR5DVB-euc
version is: 5.2.72

As mentioned in the other issue, the automatic library export to BibLaTeX unfortunately began to repeatedly fail recently. New Zotero entries do not get exported and translated into BibLaTeX. Unfortunately, due to the other issue (the missing preference pane), I cannot access the precise error message any longer, but I am hoping it is contained in the debug log.

**Comment by retorquere** [comment]
Looks like this has the same underlying cause as #1654.
