### ISSUE TITLE
When exporting notes, also handle the <blockquote> tag

### ISSUE THREAD

**Issue by svictor9** [retorquere/zotero-better-bibtex#1656]
This is an suggestion for enhancement.
 
**Exporter used:**
Better BibLaTex. Check "Export Notes".

**Expected behavior:**
When exporting a Zotero note which contains text between `<blockquote>…</blockquote>`, wrap it in `\begin{quotation}…\end{quotation}`. 

**Actual behavior:**
When a Zotero note contains text between `<blockquote>…</blockquote>`, it is exported unwrapped, as a normal paragraph.

**Workaround**
In `resources/Better BibLaTeX.js` add this after line 13615 in the `switch (tag.nodeName)` conditional:
```
	    case 'blockquote':
	        latex = '\n\n\\begin{quotation}\n...\n\n\\end{quotation}\n';
	        break;
```

Unfortunately I don't have the environment/skills to fork, build, test and make a proper pull request. However, this change enabled me to properly wrap the `<blockquote>` paragraphs in my exported my notes.

**Background**
I insert `<blockquote>` blocks in Zotero using the `"` icon. I use that to say that some paragraph in my note is a direct quote from the text to which the note is attached.  Exporting notes from Zotero is probably not useful on a daily basis, but it came in handy when I needed to convert all my notes to a different format.

**Comment by retorquere** [comment]
I'd still prefer a debug report as per point 1. It will give me the item as a test case so I can prevent regression.

**Comment by svictor9** [comment]
Ok. Here: 7UI49M96-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.72.7179](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.72.7179.xpi) ("fixes #1656")

Install in Zotero by downloading [test build 5.2.72.7179](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.72.7179.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by svictor9** [comment]
That doesn't seem to work. 
I inserted the `case 'blockquote'` after line 13615,  between `case 'tr':` and `case 'h1':`. You inserted it last in the row. Could this make a difference?
Anyway, here's a new report id: 2VMKUXXU-euc

**Comment by retorquere** [comment]
I don't see how it could make a difference. That switch statement doesn't use fall-through, switch statements always trigger on a single key value (if a key appears twice, the first instance is chosen, but `blockquote` does not appear twice), and when I run my tests on your items, I get this:

```

@book{Kant-Book,
  title = {A Book},
  author = {Kant, Emmanuel},
  publisher = {{Him}},
  location = {{Here}},
  note = {\section{This is a heading}

\par
This is some text
\par
\begin{quotation}

\par
Then this is a quote from the book. It is inserted using the " icon in Zotero. It appears indented and with a blue vertical line to~ its left.
\par
It can span several paragraphs.
\par
\end{quotation}

\par
And this is some regular text again.},
  timestamp = {2015-02-24 12:14:36 +0100}
}
% == BibLateX quality report for Kant-Book:
% Unexpected field 'timestamp' (added because JabRef format is set to 4)
% Exactly one of 'date' / 'year' must be present
```

Can you try clearing the cache from the BBT advanced prefs and exporting again?

**Comment by svictor9** [comment]
You're right, it was a cache problem. 
Clearing the cache from BBT's advanced preferences was not enough though. Some cache files were still present in `/home/vic/.zotero/vic_library/better-bibtex/`. 
I uninstalled BBT, `rm -rf /home/vic/.zotero/vic_library/better-bibtex*`, reinstalled. Then it worked.

**Comment by retorquere** [comment]
> You're right, it was a cache problem.
> Clearing the cache from BBT's advanced preferences was not enough though. Some cache files were still present in `/home/vic/.zotero/vic_library/better-bibtex/`.

The clear-cache clears the in-memory cache; the files in that directory aren't read while Zotero is running. The cache is  saved at shutdown, so you start with a warm cache, and since the in-memory cache was cleared, it would have written either an empty cache at shutdown, or written one in which only fresh entries were present.

> I uninstalled BBT, `rm -rf /home/vic/.zotero/vic_library/better-bibtex*`, reinstalled. Then it worked.

That will also have deleted `better-bibtex.sqlite`, which contained your citekeys, so they'll be regenerated. The citekeys played no role in this, you could have kept them. Uninstalling doesn't hurt, but doesn't do anything related to the problem you experienced either. Uninstalling BBT removes the BBT code from Zotero and removes the bundled translators, but they aren't related to caching issues.

Anyhow, good that it's solved. I don't know why your cache wasn't cleared after you installed 7179, but that's impossible to find out after the fact. I'll merge the functional change into a new release.

**Comment by retorquere** [comment]
(Only I can close issues here BTW, I like to keep them open until I've merged the fix unto master to prep for a new release)
