### ISSUE TITLE
From Markdown to Zotero live citations: author-in-text not working

### ISSUE THREAD

**Issue by linxule** [retorquere/zotero-better-bibtex#1658]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:**
WQ8HLSPM-euc

**Exporter used:**
zotero.lua
 - YAML header method: author-in-text: true
 - Command-line method: --metadata=author-in-text:true

**Expected behavior:**

last names of the authors replace the citekey
![image](https://user-images.githubusercontent.com/43122877/93954935-95252900-fd46-11ea-8e7e-1693aa474600.png)

**Actual behavior:**
YAML header method: 
![image](https://user-images.githubusercontent.com/43122877/93954410-91dd6d80-fd45-11ea-92b8-a57071e8d35c.png)

Command-line method: dead links (only last names of authors and not the year)
![image](https://user-images.githubusercontent.com/43122877/93954372-75d9cc00-fd45-11ea-81a9-e83425168006.png)

**Comment by retorquere** [comment]
I'll also need a copy of the markdown source. It's OK if it's just a snippet, as long as it has the full YAML header you have, and at least one of the misbehaving citekeys.

**Comment by linxule** [comment]
Sorry for the delay. Here I did a test with another citekey. You will find the markdown sources, docx outputs, and the pandoc commands used. 
[MDtoScan test.zip](https://github.com/retorquere/zotero-better-bibtex/files/5299697/MDtoScan.test.zip)

**Comment by andersjohansson** [comment]
The point as I understand it is that a `@citekey` (AuthorInText) citation in pandoc markdown should produce: `Authors (2021)` (or perhaps `Authors [3]`). That is authors in text _and_ a reference.
I believe you interpreted it as printing only authors for the lua-filter. As noted this is of course still somewhat of a hack, as it is not supported by zotero.

I did some messy edits here which gives a more correct output, but it's not based on a very thorough understanding of the code:
https://github.com/andersjohansson/zotero-better-bibtex/tree/pandocAuthorInText

Edited file:
https://github.com/andersjohansson/zotero-better-bibtex/blob/pandocAuthorInText/pandoc/pandoc-zotero-live-citemarkers.lua

Bundled lua-filter:
https://github.com/andersjohansson/zotero-better-bibtex/blob/pandocAuthorInText/site/content/exporting/zotero.lua

**Comment by retorquere** [comment]
Sorry I had let this lie so long -- life got hectic and then I just lost track of what I still had ongoing. @andersjohansson I've incorporated your changes and have published a new bundle, that should be up in about 10 minutes.

**Comment by retorquere** [comment]
The entire thing is a bodge so your code may actually be an improvement ;). The changes were [minor](https://github.com/retorquere/zotero-better-bibtex/commit/8e22efc2360a38135767800c6bd80accd9e93eef) so easy to assess.

**Comment by andersjohansson** [comment]
Thanks!
I'm getting closer to being able to write in org-mode in emacs (with its soon finalized citation format) and export from there correctly to both latex and zotero-enabled odt/docx-documents via pandoc markdown.

(some emacs libraries for managing this bridging:
https://gitlab.com/andersjohansson/org-cite-pandoc
https://gitlab.com/andersjohansson/ox-md-pandoc-zotero)
