### ISSUE TITLE
Tab for settings dissapeared in Zotero preferences

### ISSUE THREAD

**Issue by dagdrommer** [retorquere/zotero-better-bibtex#1659]
As described in the headline, I am not able anymore to access the Settings of better-bibtex in Zotero since a recent (I don't know which) update of this great tool. Here my Report-ID: 9SD96RWH-euc

Things I have tried so far without success:
- restart Zotero
- reinstall Zotero
- remove and reinstall better-bibtex (with restarting Zotero several times in between)
- disable and enable better-bibtex (with restarting Zotero several times in between)

Support is appreciated and thank you in advance!

**Comment by retorquere** [comment]
Debug log.

**Comment by dagdrommer** [comment]
Thank you very much for the quick response.
My apologies! I have searched for a duplicate, but couldn't find any - probably used the wrong keywords.

**Comment by retorquere** [comment]
You have nothing to apologize for.
