### ISSUE TITLE
Adding copyright field in BibLaTeX

### ISSUE THREAD

**Issue by 8hur** [retorquere/zotero-better-bibtex#1664]
When exporting a set of document containing some information in the "Rights" field of Zotero

- using Better BibTeX export, the output contain a "copyright" field with the correct information.
- using Better BibLaTeX export, this field is not present

As they are multiple reason I prefer BibLaTeX field but i would also like to use the contents of this filed, I was wondering why this limitation is present and if there was a way to circumvent it.

**Comment by 8hur** [comment]
[CISA-BibLaTeX.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5317107/CISA-BibLaTeX.bib.txt)
[CISA-BibLaTeX-Expected-result.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5317108/CISA-BibLaTeX-Expected-result.bib.txt)
[CISA-BibTeX.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/5317109/CISA-BibTeX.bib.txt)

**Comment by retorquere** [comment]
Thank you. Can you also include a debug report ID as explained by label-gun, point 1?

**Comment by 8hur** [comment]
report id: UAFLXEAB-euc

**Comment by 8hur** [comment]
Found a way to manually add it:

```js
if (Translator.BetterBibLaTeX && item.rights) {
  this.add({ name: 'copyright', value: item.rights });
}
```
I've added this code to the export script. Does this looks like the proper way to do it?

Also I am still curious to hear if there is a motivation for not including it in the default export settings.

**Comment by retorquere** [comment]
This is almost exactly what I'd have recommended, but it can be shortened to

```js
if (Translator.BetterBibLaTeX ) this.add({ name: 'copyright', value: item.rights });
```

as `add` simply skips the field when it's given an empty value.

**Comment by retorquere** [comment]
The biblatex manual doesn't list `copyright` as a supported field, so I really shouldn't add it as a default export -- for these things, postscripts fill the void.
