### ISSUE TITLE
Entry types for arXiv preprints in Bib(La)TeX exports

### ISSUE THREAD

**Issue by qqobb** [retorquere/zotero-better-bibtex#1667]
This is a follow-up to this [discussion on the Zotero forum](https://forums.zotero.org/discussion/comment/365116/#Comment_365116). (See also #460 for a related discussion.)

For Better BibLaTeX, arXiv preprints are now already exported as `@online` by default. (See [here](https://github.com/retorquere/zotero-better-bibtex/commit/ff928c144b5d85fc585ea6004f926e069ab309cf#diff-5ea62acb43e3cf80636fd1072cb0c369) for the code.)

For Better BibTeX, this BBT postscript can be used for exporting arXiv preprints as `@misc`:
```
if (Translator.BetterBibTeX && reference.referencetype === 'article' && item.arXiv) {
  if (reference.has.journal && item.arXiv.source === 'publicationTitle') {
    reference.remove('journal');
  }
  if (!reference.has.journal) reference.referencetype = 'misc'
}
```

Currently, the postscript will depend on the presence of a `libraryCatalog` entry, see [here](https://github.com/retorquere/zotero-better-bibtex/blob/275d09b059617fa35febc06289a44c2b388c9dd8/translators/bibtex/reference.ts#L433).

I created a pull-request (#1666) that removes the dependency on the Library Catalog field. Here is some reasoning for this change:
 1. The arXiv ID can be expected in two Zotero fields, Publication and Extra.
 2. If at least one arXiv ID is found, `item.arXiv` should be set.
 3. For an arXiv ID in Publication: `item.arXiv.source = 'publicationTitle'`.
 4. If the arXiv ID is only found in Extra: `item.arXiv.source = 'extra'`.
 5. For recognizing arXiv preprints, the best criterion seems to be a Publication field that either contains an arXiv ID or is empty. Zotero's Library Catalog field, on the other hand, seems irrelevant. (For example, it might not be populated for references imported from a `.bib` file.) The entry types in Bib(La)TeX exports should not depend on it.

(The condition `item.libraryCatalog.match(/^arxiv(\.org)?$/i)` could still be used in a BBT postscript, if needed.)

**Comment by retorquere** [comment]
The sample has been added to the site, and a new release build has been started that includes the PR. Both should show up in 15 minutes or so.
