### ISSUE TITLE
what do I do with zotero.lua

### ISSUE THREAD

**Issue by lauren-aka-proudunicornmods** [retorquere/zotero-better-bibtex#1670]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4 you are posting a single question.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

**Your question/suggestion:**
Hi,

I'm following the instructions here: https://retorque.re/zotero-better-bibtex/exporting/pandoc/
regarding trying to get my YAML frontmatter supporting markdown editor to export docs with live citations, and I'm so sorry to bother you, but I do not know what to do with the pandoc filter (zotero.lua) once I have downloaded it.
I am very new to computing and only just started learning to code, so I am sure that there is a well known step that I am missing!
I hope I have posted this in the right space, and I'm sorry to bother you if I have not!
Best,
Lauren

**Comment by lauren-aka-proudunicornmods** [comment]
here is everything in my cmd that I have tried (it crashed after the last command):

Microsoft Windows [Version 10.0.18363.1082]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Laura>--pandoc
'--pandoc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Laura>pandoc --version
pandoc 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: C:\Users\Laura\AppData\Roaming\pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

C:\Users\Laura>cd documents

C:\Users\Laura\Documents>echo %cd%
C:\Users\Laura\Documents

C:\Users\Laura\Documents>cd pandoc-test

C:\Users\Laura\Documents\pandoc-test>pandoc
hello pandoc
^Z
<p>hello pandoc</p>

C:\Users\Laura\Documents\pandoc-test>dir
 Volume in drive C is Windows
 Volume Serial Number is 66E3-A34C

 Directory of C:\Users\Laura\Documents\pandoc-test

07/10/2020  21:33    <DIR>          .
07/10/2020  21:33    <DIR>          ..
07/10/2020  21:25                89 hi.md
               1 File(s)             89 bytes
               2 Dir(s)  16,564,412,416 bytes free

C:\Users\Laura\Documents\pandoc-test>pandoc hi.md -f markdown -t html -s -o hi.html

C:\Users\Laura\Documents\pandoc-test>dir
 Volume in drive C is Windows
 Volume Serial Number is 66E3-A34C

 Directory of C:\Users\Laura\Documents\pandoc-test

07/10/2020  21:37    <DIR>          .
07/10/2020  21:37    <DIR>          ..
07/10/2020  21:37             1,059 hi.html
07/10/2020  21:25                89 hi.md
               2 File(s)          1,148 bytes
               2 Dir(s)  16,564,359,168 bytes free

C:\Users\Laura\Documents\pandoc-test>.\hi.html

C:\Users\Laura\Documents\pandoc-test>pandoc hi.md -f markdown -t word -s -o hi.docx
Unknown output format word

C:\Users\Laura\Documents\pandoc-test>pandoc hi.md -f markdown -s -o hi.docx

C:\Users\Laura\Documents\pandoc-test>dir
 Volume in drive C is Windows
 Volume Serial Number is 66E3-A34C

 Directory of C:\Users\Laura\Documents\pandoc-test

07/10/2020  21:41    <DIR>          .
07/10/2020  21:41    <DIR>          ..
07/10/2020  21:41            10,019 hi.docx
07/10/2020  21:37             1,059 hi.html
07/10/2020  21:25                89 hi.md
               3 File(s)         11,167 bytes
               2 Dir(s)  16,573,014,016 bytes free

C:\Users\Laura\Documents\pandoc-test>dir
 Volume in drive C is Windows
 Volume Serial Number is 66E3-A34C

 Directory of C:\Users\Laura\Documents\pandoc-test

07/10/2020  21:47    <DIR>          .
07/10/2020  21:47    <DIR>          ..
07/10/2020  21:41            10,019 hi.docx
07/10/2020  21:37             1,059 hi.html
07/10/2020  21:25                89 hi.md
07/10/2020  21:47             4,509 unt.md
               4 File(s)         15,676 bytes
               2 Dir(s)  16,486,301,696 bytes free

C:\Users\Laura\Documents\pandoc-test>pandoc unt.md -f markdown -s -o unt.docx

C:\Users\Laura\Documents\pandoc-test>dir
 Volume in drive C is Windows
 Volume Serial Number is 66E3-A34C

 Directory of C:\Users\Laura\Documents\pandoc-test

07/10/2020  21:48    <DIR>          .
07/10/2020  21:48    <DIR>          ..
07/10/2020  21:41            10,019 hi.docx
07/10/2020  21:37             1,059 hi.html
07/10/2020  21:25                89 hi.md
07/10/2020  21:48            12,250 unt.docx
07/10/2020  21:47             4,509 unt.md
               5 File(s)         27,926 bytes
               2 Dir(s)  16,486,014,976 bytes free

C:\Users\Laura\Documents\pandoc-test>pandoc -s --lua-filter=zotero.lua
pandoc hi.md -f markdown -s -o hello.docx

dir

**Comment by lauren-aka-proudunicornmods** [comment]
Sorry, another update:
I figured out that I need zotero.lua in the same folder as the files I'm converting?
and then I ran
pandoc -s --lua-filter=zotero.lua untitled.md -f markdown -s -o untitled.docx
and this is what happened:

C:\Users\Laura\.pandoc>dir
 Volume in drive C is Windows
 Volume Serial Number is 66E3-A34C

 Directory of C:\Users\Laura\.pandoc

07/10/2020  22:42    <DIR>          .
07/10/2020  22:42    <DIR>          ..
07/10/2020  22:34             4,513 untitled.md
07/10/2020  19:52            52,425 zotero.lua
               2 File(s)         56,938 bytes
               2 Dir(s)  16,396,767,232 bytes free

C:\Users\Laura\.pandoc>pandoc -s --lua-filter=zotero.lua untitled.md -f markdown -s -o untitled.docx
Error running filter zotero.lua:
PandocHttpError "http://127.0.0.1:23119/better-bibtex/export/item?pandocFilterData=true&translator=json&citationKeys=adolphs2006IntroducingElectronicText" (HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 23119
  secure               = False
  requestHeaders       = []
  path                 = "/better-bibtex/export/item"
  queryString          = "?pandocFilterData=true&translator=json&citationKeys=adolphs2006IntroducingElectronicText"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.connect: <socket: 568>: failed (Connection refused (WSAECONNREFUSED))))
stack traceback:
        [C]: in function 'pandoc.mediabag.fetch'
        zotero.lua:1735: in upvalue 'load_items'
        zotero.lua:1745: in function 'zotero.get'
        zotero.lua:1898: in function <zotero.lua:1884>
        (...tail calls...)

C:\Users\Laura\.pandoc>

**Comment by retorquere** [comment]
> I figured out that I need zotero.lua in the same folder as the files I'm converting?

That will work but it's not strictly necessary: https://github.com/pandoc/lua-filters/issues/21

> Error running filter zotero.lua:
PandocHttpError "http://127.0.0.1:23119/better-bibtex/export/item?pandocFilterData=true&translator=json&citationKeys=adolphs2006IntroducingElectronicText" (HttpExceptionRequest Request {

Is Zotero running with the BBT plugin installed?

**Comment by lauren-aka-proudunicornmods** [comment]
Thank you for getting back to me! I tried putting the zotero.lua in a .pandoc\filters folder as that post suggested, but unfortunately it did not work for me!
I had not remembered to keep zotero running though! Sorry!

When I ran the command with zotero running and the lua in the same folder as the files to be converted, it converted the files, but the citations were just plain text. I played around with the settings a bit, and found that I need to have 'surround pandoc citations with brackets' switched on for it to work for some reason!

It is working now YAY!!! Thank you so much for making this and for bearing with me!!!

This is the cheatsheet I made for myself (in case it is helpful to anyone):

### in file explorer

- put zotero.lua in the same folder as the files converting

### in zotero

- in the edit menu, make sure it is set as copy as "better bibtext quickcopy citation"
- in the better bibtext preferences pane, make sure "surround pandoc citations with brackets" IS checked
- KEEP zotero running!

### in command line
- navigate to the folder
-type:

pandoc -s --lua-filter=zotero.lua untitled.md -f markdown -s -o untitled.docx

where 'untitled.md' is the file to convert, and 'untitled.docx' is the output

### in word

-refresh zotero a few times until it works

**Comment by retorquere** [comment]
> Thank you for getting back to me! I tried putting the zotero.lua in a .pandoc\filters folder as that post suggested

`.pandoc/filters` needs to be in your home directory. I don't have much experience with windows, but `echo %USERPROFILE%` looks like it could point to the right place.

> When I ran the command with zotero running and the lua in the same folder as the files to be converted, it converted the files, but the citations were just plain text. I played around with the settings a bit, and found that I need to have 'surround pandoc citations with brackets' switched on for it to work for some reason!

That shouldn't be needed. I don't know why that would have made a difference. Unless you mean you dragged new citations into the document and thereby changed the citation formatting -- the filter reads just reads off what pandoc itself has deemed to be citations, so they need to be valid pandoc citations. The settings you name play no role in the pandoc filter, they are only involved in getting references into your markdown source.

**Comment by lauren-aka-proudunicornmods** [comment]
> .pandoc/filters needs to be in your home directory. I don't have much experience with windows, but echo %USERPROFILE% looks like it could point to the right place.

Thank you! I will try that out!

> The settings you name play no role in the pandoc filter, they are only involved in getting references into your markdown source

I have no idea why it worked when it worked, and didn't before! Maybe there was something else I had done incorrectly? I will try changing back the settings and see if it still works :) 

Thank you for explaining everything!

**Comment by retorquere** [comment]
My pleasure. If `%USERPROFILE%` doesn't work (or doesn't exist), you could see what the value of `%USER%` is and try `C:\User\%HOME%` (replacing `%HOME%` with its actual value).

Don't worry about asking questions, this pandoc filter is very new, so it's not well documented yet, and may even have bugs (although what it actually does is pretty simple -- the heavy lifting is done bt pandoc itself).

**Comment by 553269487** [comment]
hI retor, i add the lua into the user folds, but still get
`pandoc -s --lua-filter=zotero.lua --metadata=zotero_scannable_cite:true --metadata=client:jurism ...
[WARNING] Could not deduce format from file extension .
  Defaulting to markdown
pandoc: ...: openBinaryFile: does not exist (No such file or directory)
`
while dir would see lua actually exit

**Comment by retorquere** [comment]
You need to specify the markdown source and the target file.
