### ISSUE TITLE
Options for non-selected translaotro not hidden in autoexport preferences

### ISSUE THREAD

**Issue by mk6ve** [retorquere/zotero-better-bibtex#1671]
**Report ID:** 4LBYVIXW-euc

**Exporter used:** BibLaTeX

**Expected behavior:**

The dot symbol (⋅) in title would be converted to a LaTeX command using both BibTeX and BibLaTeX when 'Export unicode as plain-text latex commands' is checked.

**Actual behavior:**

In a .bib file generated by BibTex automatic export, the refence title is: {Transient {{Fcho1}}/2{$\cdot$}{{Eps15}}/{{R}}{$\cdot$}{{AP}}-2 Nanoclusters Prime the {{AP}}-2 Clathrin Adaptor for Cargo Binding}

In a .bib file generated by BibLaTex automatic export, the reference title is: {Transient {{Fcho1}}/2⋅{{Eps15}}/{{R}}⋅{{AP}}-2 Nanoclusters Prime the {{AP}}-2 Clathrin Adaptor for Cargo Binding}

Additionally, I am slightly confused by the fact that 'Export unicode as plain-text latex commands' appears both in the Export preference menu and the automatic export for a given library. In this case it does not make a difference whether it checked in both places or just for the library, but does one take precedence over the other? I would assume per-library settings supersede the setting in Export tab?

**Comment by mk6ve** [comment]
I actually fixed my immediate problem by changing the mathematical dot operator in the reference, which my font did not have, to a unicode middle dot, which works fine. I am still curious if there is something I was doing wrong in regards to BBT though.

**Comment by retorquere** [comment]
> Additionally, I am slightly confused by the fact that 'Export unicode as plain-text latex commands' appears both in the Export preference menu and the automatic export for a given library. In this case it does not make a difference whether it checked in both places or just for the library, but does one take precedence over the other?

The auto-export settings override the global preferences. If you have `Export unicode as plain-text latex commands` off in the global preferences, and on in the autoexport, it will be on for that autoexport.

**Comment by retorquere** [comment]
BBT knows about the mathematical dot operator (`0x22C5`), so it must be that the auto-export config had it turned off.

**Comment by mk6ve** [comment]
Right, I see the problem now. There is two boxes for the unicode conversion in the library export settings. I only had the upper one checked before. It works when I check both of them.

<img width="488" alt="Screen Shot 2020-10-14 at 13 25 21" src="https://user-images.githubusercontent.com/19314272/95982817-e776d880-0e20-11eb-96fc-75619adca8d7.png">

But now I am curious, what is the point of having two boxes?

**Comment by retorquere** [comment]
Can you get me a screenshot of the whole pane?

**Comment by retorquere** [comment]
For me it looks like this:

![Screenshot 2020-10-14 at 13 41 53](https://user-images.githubusercontent.com/132108/95984305-48071500-0e23-11eb-907b-a874861da8b3.png)

**Comment by mk6ve** [comment]
Same here, for the global preferences. The double setting is in per-library settings:

<img width="1173" alt="Screen Shot 2020-10-14 at 13 39 05" src="https://user-images.githubusercontent.com/19314272/95984448-7edd2b00-0e23-11eb-867a-3bcd3b3de240.png">

**Comment by retorquere** [comment]
Ha, that's a bug in the auto-export display. I'm looking into it.

**Comment by retorquere** [comment]
I'm not sure what happened here. There's no error in the log you sent, and for me, the AE screen looks like this:

![Screenshot 2020-10-14 at 16 27 53](https://user-images.githubusercontent.com/132108/96003464-8956ef00-0e3a-11eb-8a53-0e566cf79036.png)

Did you open the screen above before or after sending off the log? I would expect an error occurred right after you opened the preferences screen that shows that auto-export, and that causes some elements not to be hidden.

Why do you have background exports disabled BTW?

**Comment by mk6ve** [comment]
I sent off the error report before taking that screenshot, I only noticed there was two option boxes after your comments here. I just restarted Zotero and it's still there.

As for background exports, I have no idea. I am pretty sure I did not do it myself. Is it possible that it would be a setting carried over from some older version?

**Comment by mk6ve** [comment]
Done, SE9HJCC7-apse

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.82.7287](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.82.7287.xpi) ("hide non-selected AE options; fixes #1671")

Install in Zotero by downloading [test build 5.2.82.7287](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.82.7287.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by mk6ve** [comment]
That fixes it as far as I can tell. There is only one option in the automatic export and it does what it's supposed to.

Thanks a lot!
