### ISSUE TITLE
Selectively excluding keys [file]

### ISSUE THREAD

**Issue by HaoZeke** [retorquere/zotero-better-bibtex#1672]
Hi!
In my workflow, I tend to export a bunch of project specific `.bib` files, but also keep a "main" bibliography. In particular, for the "main" bibliography, I would like to keep the `file` citekey, since it is consumed by `org-ref`. For the project specific ones, it is best to not keep `files` as the file-paths are effectively useless for any collaborators.

Currently, the only option for exclusion is global, as in it is enforced across all subsequent exports. Would it be possible to setup the exclusion on a per-export basis? Or alternatively, have a whitelist, such that the key is excluded in all exports except one?

Superb work by the way. Not sure how the tags work, this is a feature request, not a bug.

**Comment by retorquere** [comment]
Sorry it took so long to come around to this -- it is not my custom to leave people waiting so long for an answer.

There isn't an easy way for me to implement this; not only am I not sure how I'd expose this UI-wise, but BBT's caching mechanism relies on items exporting to the same text, so I can't easily vary per location.

It is possible to do this in a postscript by inspecting `Translator.exportDir`, but doing so will disable caching automatically. If your exports aren't large you likely won't notice, but if you regularly export thousands of items, it will be substantially slower. Use of Zotero should be largely unimpeded.

The postscript might look like

```
if (Translator.BetterTeX && Translator.exportDir !== "<your own directory") delete item.file
```

**Comment by retorquere** [comment]
Does this address your question?

**Comment by HaoZeke** [comment]
Yup, thanks, that makes sense. Sorry for the late reply.

**Comment by retorquere** [comment]
I can hardly complain after letting this issue sit for so long.
