### ISSUE TITLE
Cleared (undefined) `rawLaTag` disables raw #LaTeX processing

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1674]
# Description of the problem
Despite a `#LaTeX` tag, some fields are not exported as if they’re wrapped in `<script>...</script>`. For instance, for an entry with such a `#LaTeX` tag with the following characteristics:

- Item Type: Journal Article
- Title: Completeness of $\mathbb{R}$
- Author: Bar, Foo
- Short Title: $\mathbb{R}$: complete!
- Extra: <script>$\mathbb{R}$ !</script>
- Tag: #LaTeX

I get the following actual behavior where:
- the title is OK thanks to https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas
- the annotation is OK thanks to `<script>...</script>`
- the short title is *not* OK since:
    - the entry its belongs to, having the `#LaTeX` tag, should then have all fields exported as if they’re wrapped in `<script>...</script>` (literal LaTeX),
    - its content should hence be similar to the one of the annotation (see expected behavior).

# Required informations
**Report ID:** U2Z8CJBC-euc
**Exporter used:** Better BibLaTeX
**Expected behavior:**
```bibtex
@article{BarCompletenessmathbbR,
  shorttitle = {$\mathbb{R}$: Complete!},
  author = {Bar, Foo},
  annotation = {$\mathbb{R}$ !},
  keywords = {\#LaTeX},
  title = {Completeness of {$\mathbb{R}$}}
}
% == BibLateX quality report for BarCompletenessmathbbR:
% Exactly one of 'date' / 'year' must be present
% Missing required field 'journaltitle'
```
**Actual behavior:**
```bibtex
@article{BarCompletenessmathbbR,
  shorttitle = {\$\textbackslash mathbb\{\vphantom\}{{R}}\vphantom\{\}\$: Complete!},
  author = {Bar, Foo},
  annotation = {$\mathbb{R}$ !},
  keywords = {\#LaTeX},
  title = {Completeness of {$\mathbb{R}$}}
}
% == BibLateX quality report for BarCompletenessmathbbR:
% Exactly one of 'date' / 'year' must be present
% Missing required field 'journaltitle'
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.84.7300](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.84.7300.xpi) ("debug logging for #1674")

Install in Zotero by downloading [test build 5.2.84.7300](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.84.7300.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I can't currently replicate this. With that reference, and your BBT settings, I get

```
@article{BarCompletenessmathbbR,
  shorttitle = {$\mathbb{R}$: complete!},
  author = {Bar, Foo},
  annotation = {<script>$\mathbb{R}$ !</script>},
  title = {Completeness of <script>{$\mathbb{R}$}</script>}
}
% == BibLateX quality report for BarCompletenessmathbbR:
% Exactly one of 'date' / 'year' must be present
% Missing required field 'journaltitle'
```

can you install 7300, select "restart with debug logging" from the help menu, re-export this item, and then send a new BBT debug log?

**Comment by dbitouze** [comment]
@retorquere Done with BBT debug log P63XM56S-euc. Now, the entry is exported as:

```bibtex
@article{BarCompletenessmathbbR,
  shorttitle = {$\mathbb{R}$: complete!},
  author = {Bar, Foo},
  annotation = {<script>$\mathbb{R}$ !</script>},
  title = {Completeness of <script>{$\mathbb{R}$}</script>}
}
% == BibLateX quality report for BarCompletenessmathbbR:
% Exactly one of 'date' / 'year' must be present
% Missing required field 'journaltitle'
```

BTW, the `rawLaTag` hidden preference is now:

`extensions.zotero.translators.better-bibtex.rawLaTag;#LaTeX`

and now I'm not sure: maybe the error I had was due to the fact I did reset its value (I guess I misunderstood the documentation).

Sorry for the noise. 

With 7300, spurious `<script>...</script>` in the exported `.bib` file, isn't it?

**Comment by dbitouze** [comment]
>With 7300, spurious <script>...</script> in the exported .bib file, isn't it?

Well, coming back to 5.2.84, the Zotero entry as in the OP, in particular with:

- Title: Completeness of $\mathbb{R}$

but now with:

`extensions.zotero.translators.better-bibtex.rawLaTag;#LaTeX`

is exported as:
```bibtex
@article{BarCompletenessmathbbR,
  shorttitle = {$\mathbb{R}$: complete!},
  author = {Bar, Foo},
  annotation = {<script>$\mathbb{R}$ !</script>},
  title = {Completeness of <script>{$\mathbb{R}$}</script>}
}
% == BibLateX quality report for BarCompletenessmathbbR:
% Exactly one of 'date' / 'year' must be present
% Missing required field 'journaltitle'
```
so still spurious `<script>...</script>` in the title field of the exported `.bib` file, isn't it?

**Comment by retorquere** [comment]
Not spurious - if you set `#LaTeX`, everything is passed through as-is, because you've told BBT to assume everything is valid LaTeX already, and in your case, "everything" includes those `<script>` tags.

Remains strange that I didn't get your initial input with your settings. I'll have to look into that.

**Comment by dbitouze** [comment]
>Not spurious - if you set #LaTeX, everything is passed through as-is, because you've told BBT to assume everything is valid LaTeX already, and in your case, "everything" includes those <script> tags.

Except:

- the Zotero's title field contains no `<script>` tag ("Completeness of $\mathbb{R}$"),
- the `title` field in the exported `.bib` field contains such a tag (`title = {Completeness of <script>{$\mathbb{R}$}</script>}`).

**Comment by retorquere** [comment]
> maybe the error I had was due to the fact I did reset its value

That must have been the problem, and that explains the difference in behavior. When you reset the value, it will be `undefined`, and BBT tries to find the tag with value `undefined` (not the string `"undefined"`), and that will never be found. But if you restart while it is `undefined`, BBT will reset it to the default `#LaTeX`, and I did restart after applying your settings.


> * the Zotero's title field contains no `<script>` tag ("Completeness of $\mathbb{R}$"),
> * the `title` field in the exported `.bib` field contains such a tag (`title = {Completeness of <script>{$\mathbb{R}$}</script>}`).

Because you added it in the postscript. What's added in the postscript is also assumed to be raw LaTeX for an item tagged as such. If you want to exempt such items you'd have to use something like

```
if (Translator.BetterTeX && reference.has.title && !item.raw) {
  reference.add({ name: 'title', value: item.title.replace(/(\$.*?\$)/g, '<script>{$1}</script>') });
}
```

**Comment by dbitouze** [comment]
>Because you added it in the postscript. What's added in the postscript is also assumed to be raw LaTeX for an item tagged as such. If you want to exempt such items you'd have to use something like [...]

Sorry, but I'm a bit lost. Does it mean you recommend to systematically add `&& !item.raw` to the post script which [detects and protects LaTeX math formulas](https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas), having in mind entries with `#LaTeX` tag?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.84.7301](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.84.7301.xpi) ("fall back to default for cleared pref")

Install in Zotero by downloading [test build 5.2.84.7301](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.84.7301.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I recommend not mixing the postscript protection and the #LaTeX tag on the same item. Checking for `item.raw` is one way to accomplish that. Another is to not use the auto-protect postscript.

**Comment by dbitouze** [comment]
>I recommend not mixing the postscript protection and the #LaTeX tag on the same item. Checking for item.raw is one way to accomplish that. Another is to not use the auto-protect postscript.

Suppose a PhD student in mathematics. Several entries of his bibliography are likely to contain mathematic formulas, so he would probably be interested in the (global) postscript protection. Now, suppose some entries, because of some special fields (`shorttitle`, `abstract`, etc.), needs literal LaTeX in the export: there is a great temptation to use the (locally global) `#LaTeX` protection instead of adding many (locally local) `<script>` tags.

**Comment by retorquere** [comment]
In that case there's currently no way around checking for `item.raw`.

**Comment by dbitouze** [comment]
> In that case there's currently no way around checking for `item.raw`.

So we're going back to #1380 :wink: 

In fact, I'm in the process to go into some details about BBT in a LaTeX course I'm giving to PhD students (among others) because, during the previous course (2 weeks ago), some students (in maths, in physical sciences, in computer science) were disappointed because of these LaTeX commands not exported untouched. And the configuration process of BBT is somewhat long/complicated (I'm not fully understand all the items), especially for students who are discovering (La)TeX + Bib(La)TeX + Zotero + BBT :smile: so I'd like to be as simple as possible. If I understand correctly, the advices for such students could be:

1. for all of them, the post script:
```
if (Translator.BetterTeX && reference.has.title && !item.raw) {
  reference.add({ name: 'title', value: item.title.replace(/(\$.*?\$)/g, '<script>{$1}</script>') });
}
```
2. for those who would need **from time to time** literal LaTeX export in other fields than the title: add the `#LaTeX` tag to the relevant entries,
3. for those who would need **almost always** literal LaTeX export in other fields than the title: Preferences/Advanced/Config editor/Search for `rawLa`/Right Click/Modify/Replace `#LaTeX` by `*` (in such a case, post script is useless but harmless).

Do you agree with these advices?

**Comment by retorquere** [comment]
> And the configuration process of BBT is somewhat long/complicated (I'm not fully understand all the items)

Even I occasionally forget about functionality in BBT. It's become a complex beast.

You can do it for multiple fields with

```js
if (Translator.BetterTeX && !item.raw) {
  const fields = ['title', 'titleaddon']
  for (const [name, field] of Object.entries(reference.has)) {
    if (fields.includes(name)) {
      reference.add({ name, value: field.value.replace(/(\$.*?\$)/g, '<script>{$1}</script>') })
    }
  }
}
```

>  * for those who would need **from time to time** literal LaTeX export in other fields than the title: add the `#LaTeX` tag to the relevant entries,
> 
>  * for those who would need **almost always** literal LaTeX export in other fields than the title: Preferences/Advanced/Config editor/Search for `rawLa`/Right Click/Modify/Replace `#LaTeX` by `*` (in such a case, post script is useless but harmless).

That seems correct. Note that Zotero does not understand postscripts, it's strictly a BBT thing, and those `$` signs will show up if you create a bibliography in Word/LO.

**Comment by dbitouze** [comment]
> > And the configuration process of BBT is somewhat long/complicated (I'm not fully understand all the items)
> 
> Even I occasionally forget about functionality in BBT.

Happy to know that I'm not the only one! :smile: 

> It's become a complex beast.

Indeed. I'll open a new issue about ("Export" tab) "When converting to plain-text latex commands", which is somewhat obscure from my point of view...
 
> You can do it for multiple fields with
> 
> ```js
> if (Translator.BetterTeX && !item.raw) {
>   const fields = ['title', 'titleaddon']
>   for (const [name, field] of Object.entries(reference.has)) {
>     if (fields.includes(name)) {
>       reference.add({ name, value: field.value.replace(/(\$.*?\$)/g, '<script>{$1}</script>') })
>     }
>   }
> }
> ```

OK but one has to complete by himself the `const fields` list. Giving to `rawLaTag` the value `*` looks simpler.

> That seems correct. Note that Zotero does not understand postscripts, it's strictly a BBT thing,

OK.

> and those `$` signs will show up if you create a bibliography in Word/LO.

But BBT is designed to export to Bib(La)TeX, designed for (La)TeX, isn't it? Hence,  why one would rely on it for a bibliography in Word/LO?



Anyway, I still argue for a simple check box is the "Export" tab in the BBT config that let the user easily ask for literal LaTeX export in all fields (with, maybe, a list fields to omit, similar to the one in the "Fields" part).

**Comment by retorquere** [comment]
> But BBT is designed to export to Bib(La)TeX, designed for (La)TeX, isn't it? Hence, why one would rely on it for a bibliography in Word/LO?

BBT is, but Zotero is not. Many people (myself included) use Zotero both with Word (if the publisher demands Word) or LaTeX (all other times).
 
> Anyway, I still argue for a simple check box in the "Export" tab in the BBT config that let the user easily ask for literal LaTeX export in all fields (with, maybe, a list fields to omit, similar to the one in the "Fields" part).

As a shortcut to setting `rawLaTag` to `*` you mean?

**Comment by dbitouze** [comment]
> > But BBT is designed to export to Bib(La)TeX, designed for (La)TeX, isn't it? Hence, why one would rely on it for a bibliography in Word/LO?
> 
> BBT is, but Zotero is not.

Indeed, I noticed :wink: 

> Many people (myself included) use Zotero both with Word (if the publisher demands Word) or LaTeX (all other times).

But the BBT "Export" settings doesn't change (interfere with) the content of Zotero's fields, which is what is used by Word/LO, isn't it?

> > Anyway, I still argue for a simple check box in the "Export" tab in the BBT config that let the user easily ask for literal LaTeX export in all fields (with, maybe, a list fields to omit, similar to the one in the "Fields" part).
> 
> As a shortcut to setting `rawLaTag` to `*` you mean?

Yes (with, maybe, possibility to exclude some fields from literal LaTeX export).

**Comment by retorquere** [comment]
> But the BBT "Export" settings doesn't change (interfere with) the content of Zotero's fields, which is what is used by Word/LO, isn't it?

That is true, but the dollar signs (and the latex formula) will show up in Word/LO bibliographies.

I'll think about the field config. I've become more hesitant adding new preferences - BBT might already have more preferences than Zotero itself.

**Comment by dbitouze** [comment]
> > But the BBT "Export" settings doesn't change (interfere with) the content of Zotero's fields, which is what is used by Word/LO, isn't it?
> 
> That is true, but the dollar signs (and the latex formula) will show up in Word/LO bibliographies.

Indeed, but I don't see the connection with BBT _export (to a `.bib` file)_ settings.

> I'll think about the field config. I've become more hesitant adding new preferences - BBT might already have more preferences than Zotero itself.

I understand but LaTeX users are the main target users of BBT and, among them, mathematicians certainly make up the majority. Hence, an easy way for them to export Zotero fields content as they expect would be very helpful (maybe much more than other settings, such as "Include JabRef-specific metadata" I guess).

**Comment by retorquere** [comment]
No connection with bib export, just a general point about using a BBT-only facility.

I regret adding the jabref settings, but it's there, and I don't like to remove existing features. I'll think about the field exemptions.

**Comment by dbitouze** [comment]
> No connection with bib export, just a general point about using a BBT-only facility.

OK. About those `$` signs that will show up in bibliographies with Word/LO, it is a job for the "to Word/LO export" to deal with them, not for BBT :wink: 

> I regret adding the jabref settings, but it's there, and I don't like to remove existing features. I'll think about the field exemptions.

Maybe more rarely used options could be gathered in "advanced" part(s) of the BBT config tab(s), only revealed if "Show advanced" check box(es) would checked.

**Comment by retorquere** [comment]
There's no such thing as Word/LO export. Zotero talks to Word/LO directly and must assume that whatever is in eg the title field is what you want to see as text. But Zotero has no math support, so the formulas will look janky anyhow.

**Comment by retorquere** [comment]
BTW, there's already stuff like

```
tex.title= stuff with $x>y$.
```

which will override whatever is in the title. No need for `#LaTeX` tagging or postscripts.

**Comment by dbitouze** [comment]
> BTW, there's already stuff like [...] which will override whatever is in the title.

Sorry, I'm puzzled:

- where `tex.title` has to be specified?
- does its value ("stuff with $x>y$" in your example) be the actual content of the title?

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/exporting/#add-your-own-biblatex-fields

It's added in the `extra` field. What I showed would be the actual content - when using `=` instead of `:`, that line is treated as raw LaTeX. This would override the zotero title for BBT exports, so this would even allow use in both word and latex.

**Comment by dbitouze** [comment]
> BTW, there's already stuff like [...] which will override whatever is in the title. No need for `#LaTeX` tagging or postscripts. [...] so this would even allow use in both word and latex.

OK but, for a LaTeX export, `#LaTeX` looks simpler.
