### ISSUE TITLE
Chinese pinyin transliteration cite key gets too long

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#1678]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:**
WGDCV2JW-apse
**Expected behavior:**
Citation keys should be kept short and clean, like in the English case. 
**Actual behavior:**
The full self-generated citation-key for this title, `論象山與朱子文本所呈顯之儒學宗教性` is `黃信二LunXiangShanYuZhuZiWenBenSuoChengXianZhiRuXueZongJiaoXing2015` which is very cumbersome to type and distracting on the screen in working papers. 

One simple solution would be to make available the option of cutting off at the 6th character, which produces `黃信二LunXiangShanYuZhuZi2015` or with reference to the `Short Title` field, if it is available (even though that can also get pretty long). 

I have to manually change my cite-key for Chinese sources almost every time with the present setting.

**Comment by sati-bodhi** [comment]
Judging by the way Chinese works described overe [here](https://github.com/retorquere/zotero-better-bibtex/issues/1662#issuecomment-711484429), having the option of generating citation keys in the original form could be even better.

**Comment by duncdrum** [comment]
See https://github.com/retorquere/zotero-better-bibtex/issues/1353 does this not work for you?

**Comment by sati-bodhi** [comment]
> See #1353 does this not work for you?

I have this in my citation format `[Auth][veryshorttitle:nopunct:split-ideographs:select=1,3:clean][year]` but adding `split-ideographs:select=1,3` doesn't seem to do anything for me. Does that work only with `title`?

**Comment by sati-bodhi** [comment]
I believe this issue can be closed for now - the [manual](https://retorque.re/zotero-better-bibtex/citing/) is clear enough. One last thing I need to ask is regarding the use of `clean`. It says in the manual that the purpose is to: 

> transliterate the citation key and removes unsafe characters

Had there been any issues with having Chinese characters within the citation key?

**Comment by retorquere** [comment]
I couldn't tell you -- I have no knowledge about Chinese.

**Comment by sati-bodhi** [comment]
> I couldn't tell you -- I have no knowledge about Chinese.

What I mean is, whether there is any rationale behind regarding Chinese characters as "unsafe"  to use in the citation key as of now? 

I know in the past, before the proliferation of UTF8, there used to be many encoding issues with with non-ascii characters, which includes Chinese characters. I just need to know whether you have encountered such examples, reported by users, in the course of your work.

**Comment by retorquere** [comment]
> I know in the past, before the proliferation of UTF8, there used to be many encoding issues with with non-ascii characters, which includes Chinese characters. I just need to know whether you have encountered such examples in regard to Chinese characters, reported by users, in the course of your work.

That is correct -- to deal with such legacy toolchains, "unsafe" is any non-7bit-ASCII. I don't have specific reports that Chinese keys cause trouble. You can turn off the default clean by unchecking `Force citation key to plain text`, but most if not all of the default non-capitalized pattern functions will have transliteration applied, so for that to have any effect, you must be using the capitalized self-assembly pattern functions.

**Comment by duncdrum** [comment]
@sati-bodhi there are two types of unsafe characters, double-byte characters because of the non-unicode legacy of bibtex, and substitution characters (historical variants, etc) which you usually don't want to substitute in .e.g author names.

**Comment by sati-bodhi** [comment]
I think I am satisfied with the settings and result as it stands right now. Kudos for the brilliant software and support!

**Comment by sati-bodhi** [comment]
I presume working primarily in `BibLaTeX` make it relatively "safe" to include Unicode characters in the citation key and `.bib` database in general. 

> You can turn off the default clean by unchecking Force citation key to plain text, but most if not all of the default non-capitalized pattern functions will have transliteration applied, so for that to have any effect, you must be using the capitalized self-assembly pattern functions.

I just realize that I cannot use `capitalize` without transliterating the Chinese characters: 
`[Auth][Title:skipwords:capitalize:select=1,1:split-ideographs:select=1,3:nopunct][year]`
Other than making sure all my titles are in Title Case, is there any other way to "uppercase the first letter of each word" without invoking `clean`?
