### ISSUE TITLE
What's the purpose of "When converting to plain-text latex commands"?

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1679]
In the BBT config tab, "Export" tab, the "When converting to plain-text latex commands" part is somewhat obscure from my point of view. Could please explain and maybe illustrate with examples what are (the differences between):

- Minimize additional latex packages required
- Minimize the number of switches between math-mode and text-mode
- Prefer text-mode replacements
- Prefer math-mode replacements

**Comment by retorquere** [comment]
It's nothing much, and I shouldn't have included it as a preference. But what it drives is the following:

For many unicode characters, there are  both a math-mode command and a text-mode command to produce them. Some of these commands require extra packages to be loaded in LaTeX (if you have the quality report on it will list them). When there is both a math-mode and a text-mode command available for a unicode character, you can choose here to prefer:

* the one which doesn't require a specific package to be loaded
* to stay in the mode the last char was produced in
* the text-mode command
* the math-mode command

**Comment by retorquere** [comment]
It's nothing much, and I shouldn't have included it as a preference. But what it drives is the following:

For many unicode characters, there are  both a math-mode command and a text-mode command to produce them. Some of these commands require extra packages to be loaded in LaTeX (if you have the quality report on it will list them). When there is both a math-mode and a text-mode command available for a unicode character, you can choose here to prefer:

* the one which doesn't require a specific package to be loaded
* to stay in the mode the last char was produced in
* the text-mode command
* the math-mode command
