### ISSUE TITLE
Registered Trade Mark Sign in Title

### ISSUE THREAD

**Issue by TimonSchulz** [retorquere/zotero-better-bibtex#1680]
Hello @retorquere ,

I am trying to add a title into my bibliography, which contains a registered trade mark sign (®). I would like for it to be above the name such as GX®. If I type the trademark sign into the title it will be on the same level as the rest of the text and will also appear like this in my bibliography.

I'm using Zotero and BBT with the latest versions. I'm exporting in BibTeX / Better BibTeX to LaTeX.

**Report ID: XB4RJBZX-euc**

This is my input into Zotero's title section:

Gx® Nadelspritzen

... with the difference of ® being on the same level as the regular text. I would like to rise it up.

This is the output in my .bib-file:

```
@misc{gerresheimerag,
  title = {{{Gx}}\textregistered{} {{Nadelspritzen}}},
  author = {{Gerresheimer AG}},
  annotation = {S. 4},
  file = {/Users/timonschulz/Zotero/storage/D9JKVK2Y/gxr-nadelspritzen.html},
  note = {Zuletzt gepr\"uft 05.08.2020},
  howpublished = {\url{https://www.gerresheimer.com/produkte/pharmazeutische-primaerverpackungen/spritzen-aus-glas/gxr-nadelspritzen.html}}
}**
```

Thank you for your support
Timon

**Comment by retorquere** [comment]
Try `<sup>®</sup>`
