### ISSUE TITLE
Capitalisation of Letters in Titles

### ISSUE THREAD

**Issue by TimonSchulz** [retorquere/zotero-better-bibtex#1681]
Hello everyone,

I get a rather random capitalisation of first letters in a title in my bibliography.

My input into Zotero's title section is e.g.:

'DIN EN ISO 10993-1:2017-04 Biologische Beurteilung von Medizinprodukten - Teil 1: Beurteilung und Prüfung im Rahmen eines Risikomanagementsystems'

I would like for it to turn out exactly like this with 'von', 'und', 'im', and 'eines' not capitalised.

However I get

'von', 'Und', 'Im', and 'Eines' so 'von' not capitalised and the rest capitalised. This behaviour appears in a couple of items regardless of the item type (book, website, etc.)

```
@misc{technischenkomiteeiso/tc194undcen/tc2062017,
  title = {{{DIN EN ISO}} 10993-1:2017-04 {{Biologische Beurteilung}} von {{Medizinprodukten}} - {{Teil}} 1: {{Beurteilung}} Und {{Pr\"ufung}} Im {{Rahmen}} Eines {{Risikomanagementsystems}}},
  author = {{Technischen Komitee ISO/TC 194 und CEN/TC 206}},
  year = {2017}
}
```

**Report ID: 2956PM2R-euc**

**Exporter used: Better BibTeX**

**Comment by njbart** [comment]
Not a bug. Try using a non-English tag in Zotero’s `Language` field. In your case, `de` or `de-DE` should do the trick.

See https://retorque.re/zotero-better-bibtex/support/faq/#bbt-is-changing-the-capitalization-of-my-titles----why
