### ISSUE TITLE
Word segmentation for Chinese references

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#1682]
Can word segmentation modules such as [jieba](https://github.com/fxsjy/jieba#jieba-1) be integrated as part of the key generation code? 

We could do something like: `[Title:jieba:skipwords:capitalize:select=1,1:nopunct]` to produce meaningful citation keys in Chinese. 

![圖片](https://user-images.githubusercontent.com/7592695/96532888-60fa4500-12bf-11eb-8426-19cdd4152846.png)

Presently, with `split-ideographs`, we arbitrarily select a position to cut off Chinese characters, which may result in meaningless segments. For example, with this reference (**ID: KY2E37FJ-apse**) and the following code: 

`[Auth][Title:skipwords:capitalize:select=1,1:split-ideographs:select=1,3:nopunct][year]`

「古訓」in the title, meaning "old connotations" would be cut off at "old". By integrating the `jieba` module, meaningful word segments can be split accordingly, rendering better generation of Chinese citation keys. (It should work for Japanese Kanji as well.)

**Comment by retorquere** [comment]
I must apologize, I've fallen behind on handling issues. The debug log has expired, can you send me a new one?

**Comment by sati-bodhi** [comment]
U5GSLEA-apse

**Comment by retorquere** [comment]
Just to make sure: [split-ideographs](https://retorque.re/zotero-better-bibtex/citing/) does something importantly different from jieba?

**Comment by retorquere** [comment]
You have background exports disabled BTW, that's going to affect performance for exports.

**Comment by retorquere** [comment]
If I replace `split-ideagraphs` with `jieba` in my test build I get the citekey `傅斯年性命古1985`, but I don't know if that's what you want.

**Comment by sati-bodhi** [comment]
> If I replace `split-ideagraphs` with `jieba` in my test build I get the citekey `傅斯年性命古1985`, but I don't know if that's what you want.

Not exactly. As demonstrated above, a proper application of `jieba.cut` should render the title as `性命 古訓 辨證` so it should either be `傅斯年性命1985` or `傅斯年性命古訓1985`, depending on how many 'words' you allow.

**Comment by sati-bodhi** [comment]
> Just to make sure: split-ideographs does something importantly different from jieba?

What `split-ideographs` does is to arbitrarily treat each character as a 'word'. 
`jieba` makes use of an internal dictionary to identify groups of characters that actually form a 'word' that acts as a meaningful grammatical unit.

**Comment by retorquere** [comment]
> Not exactly. As demonstrated above, a proper application of `jieba.cut` should render the title as `性命 古訓 辨證` 

I'm using https://github.com/pulipulichen/jieba-js which was the best maintained javascript jieba implementation I could find; it segments `性命古訓辨證` into `性命 古訓 辨證` (demo [here](https://pulipulichen.github.io/jieba-js/)). So it looks like it does the right thing, yeah? They look the same to me, but I can't be sure as I can't read Chinese.

> so it should either be `傅斯年性命1985` or `傅斯年性命古訓1985` depending on how many 'words' you allow.

I'm sorry but I don't understand how `性命 古訓 辨證` relates to either `傅斯年性命` or `傅斯年性命古訓`. From the options you provide it looks to me like word/character ordering is different from what I'm used to, but I don't know in what way. In the case of the pattern above, it should pick out 3 'words'; which of these two options would be the correct result, and by what rule does it construct to that pick?

**Comment by sati-bodhi** [comment]
> I'm using https://github.com/pulipulichen/jieba-js which was the best maintained javascript jieba implementation I could find; it segments `性命古訓辨證` into `性命 古訓 辨證` (demo [here](https://pulipulichen.github.io/jieba-js/)). So it looks like it does the right thing, yeah? They look the same to me, but I can't be sure as I can't read Chinese.

Yes, the segmentation is correct. 

> I'm sorry but I don't understand how 性命 古訓 辨證 relates to either 傅斯年性命 or 傅斯年性命古訓. From the options you provide it looks to me like word/character ordering is different from what I'm used to, but I don't know in what way. In the case of the pattern above, it should pick out 3 'words'; which of these two options would be the correct result, and by what rule does it construct to that pick?

The first 3 characters, `傅斯年`, is the author. This is followed by 3 segmented `words`. 

So it can be either `傅斯年性命` (Au+T1) or `傅斯年性命古訓` (Au+T1+T2) or `性命古訓辨證` (Au+T_in_full). 

This can be altered by changing the second variable of `select` without `split-ideographs`. 

So `[Auth][Title:jieba:skipwords:capitalize:select=1,2:nopunct][year]` should produce: 
 `傅斯年性命古訓1985`.

**Comment by retorquere** [comment]
I'm running into [this](https://github.com/pulipulichen/jieba-js/issues/18) problem.

**Comment by retorquere** [comment]
I'm looking into `cncut` instead.

**Comment by retorquere** [comment]
which [crashes](https://github.com/shataniya/cncut/issues/2) outright. On to the next library.

**Comment by retorquere** [comment]
[this](https://github.com/bluelovers/ws-segment/tree/master/packages/novel-segment) seems well maintained but the docs are all in Chinese it appears.

**Comment by retorquere** [comment]
Does [this](https://github.com/ooooevan/jieba) text explain the meaning of the options `cutAll`, `dag`, `hmm` and `cutForSearch`?

**Comment by retorquere** [comment]
You can ignore this version, I don't have the preferences in place yet.

**Comment by retorquere** [comment]
447 has an extra option under Advanced -> Citekeys where you can enable `jieba` support. When it is off, `:jieba` won't do anything. I'd appreciate it if you could test whether this version does what you expect.

**Comment by sati-bodhi** [comment]
I get the error: 

> The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

**Comment by retorquere** [comment]
test builds are only up for a week. A new build will drop here in 10 minutes or so.

**Comment by retorquere** [comment]
That error message you get is the rather unhelpful message Firefox/Zotero gives when you try to install something that's named `.xpi` but is actually an html file. if you rename it to `.html` and open it in your browser you'll see "file not found" or something to that effect.

**Comment by sati-bodhi** [comment]
The test build works as expected, thank you!

**Comment by retorquere** [comment]
A release build has been scheduled
