### ISSUE TITLE
Biblatex export to year vs date

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#1684]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:**
TTLR2VBA-apse
**Exporter used:**
Better-Biblatex
**Expected behavior:**
`date` field should be exported as `year` and `month`, possibly including `date` itself
**Actual behavior:**
`date` field exported as `date` only

```
@article{WongEarly2015,
  title = {Early {{Confucian Philosophy}} and the {{Development}} of {{Compassion}}},
  author = {Wong, David B.},
  date = {2015-06},
  journaltitle = {Dao},
  shortjournal = {Dao},
  volume = {14},
  pages = {157--194},
  issn = {1540-3009, 1569-7274},
  doi = {10.1007/s11712-015-9438-x},
  url = {http://link.springer.com/10.1007/s11712-015-9438-x},
  urldate = {2020-10-07},
  file = {/Users/satibodhi/Zotero/storage/3ZDRRUDG/Wong - 2015 - Early Confucian Philosophy and the Development of .pdf},
  langid = {english},
  number = {2}
}
```

**Comment by njbart** [comment]
> Expected behavior:
date field should be exported as year and month, possibly including date itself

Wrong. [RTFM](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf).

**Comment by sati-bodhi** [comment]
It says here in the manual: 

![圖片](https://user-images.githubusercontent.com/7592695/96937259-511a7500-14fa-11eb-89e6-977a7b161778.png)

year/date are the required fields. 

![圖片](https://user-images.githubusercontent.com/7592695/96937369-86bf5e00-14fa-11eb-8682-f2d882a3c801.png)

But I only get the `date` field on export. 

With `org-ref`, 

![圖片](https://user-images.githubusercontent.com/7592695/96938106-20d3d600-14fc-11eb-9eaf-498c47f17ab8.png)

the `year` field gets obliterated as a result (which doesn't happen with BibTeX because there is a `year` field).

**Comment by sati-bodhi** [comment]
![圖片](https://user-images.githubusercontent.com/7592695/96941646-8d070780-1505-11eb-8cce-73fda9350c16.png)

I think "automatically created" pertains to what happens when Biblatex bibliography and citation style files are drafted. Having `datepart` fields exported together with the date could save some work when citing via other channels. 

It _does_ make sense, though, to export to either `date` or date parts as separate fields - but not both - to avoid contradictions.

**Comment by retorquere** [comment]
Where it says `year/date` in the docs, that means exactly one of those, not both. If you look in the bcf file you can see the rules made explicit.

The "automatically created" means that the date in `date` will be parsed and those parts will be made available to the style.

**Comment by retorquere** [comment]
If org-ref requires a `year` field, that would mean it expects bibtex, not biblatex.

**Comment by njbart** [comment]
The essential bit in the biblatex manual is, “For every field of datatype `date` in the datamodel, datepart fields are *automatically* created […]” (my emph.). None of these datepart fields are included in the lists of user-facing fields in “2.2.2 Data Fields”, “2.2.3 Special Fields”, “2.2.4 Custom Fields” or “2.2.5 Field Aliases” (with the exception of `year` and `month`, which are permitted for backwards compatibility with traditional BibTeX).

What’s more, the biblatex manual explicitly discourages using `year` and `month`, which wouldn’t make sense if any of the other datepart fields were ok to use, let alone an alleged improvement over the date `field`.

The final straw, however, for the idea that datepart fields could sensibly be used in a biblatex database file (well, at least one that is supposed to be understood by biblatex itself) is the fact that when processing with `latex` and `biber` (examples below), `year` and `month` are supported for legacy reasons, and `urlyear`, `urlmonth`, `urlday` do make it into the output, too, crucially, `day` is not.

Compare the following two examples (the first one prints a day, he second one doesn’t):

```
\documentclass{article}
\begin{filecontents}{\jobname.bib}
@online{item1,
  title = {A Web Page},
  author = {John Doe},
  date = {2019-09-21},
  urlyear = {2020},
  urlmonth = {10},
  urlday = {22},
}
\end{filecontents}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\section{Text}
Blah blah \autocite{item1}.
\printbibliography
\end{document}
```

```
\documentclass{article}
\begin{filecontents}{\jobname.bib}
@online{item1,
  title = {A Web Page},
  author = {John Doe},
  year = {2019},
  month = {9},
  day = {21},
  urlyear = {2020},
  urlmonth = {10},
  urlday = {22},
}
\end{filecontents}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\section{Text}
Blah blah \autocite{item1}.
\printbibliography
\end{document}
```

I maintain that outputting a `date` field, and only that, *is* the desirable behaviour for BBT, and doing so isn’t a bug at all.

**Comment by sati-bodhi** [comment]
> If org-ref requires a `year` field, that would mean it expects bibtex, not biblatex.

`org-ref` and also [`helm-bibtex`](https://github.com/tmalsburg/helm-bibtex/issues/217#issuecomment-351364633), which part of the `org-ref` code uses, do have a `biblatex` compatibility issue. 

If not having (even just) the year field exported, (not even) for backward compatibility reasons, is the consensus over here, I will have to look for a solution downstream with either `helm-bibtex` or `org-ref`.

**Comment by retorquere** [comment]
For compatibility reasons bibtex allows using year/month *instead of* date, but it's discouraged.

The preferable solution would be to have helm-bibtex fix the incompatibility, but for the short term, a postscript would let you add the `year` if you want.

**Comment by sati-bodhi** [comment]
> For backward compatibility reasons biber allows using year/month _instead of_ date, but it's discouraged.
> 
> The preferable solution would be to have helm-bibtex fix the incompatibility, but for the short term, a postscript would let you add the `year` if you want.

That sounds good to me. Kindly advise how the postscript can be invoked. Thank you!

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/exporting/scripting/ and then something like

```js
if (Translator.BetterBibLaTeX) {
  const date = Zotero.BetterBibTeX.parseDate(item.date)
  if (date && typeof date.year === 'number') ref.add({ name: 'year', value: `${date.year}` })
}
```
