### ISSUE TITLE
"Book Title" exports to "Journaltitle" for Biblatex `@incollection` reference type

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#1691]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:**
KF7MT934-apse
**Exporter used:**
better-biblatex
**Expected behavior:**
"Book Title" should export to `booktitle`, not  `journaltitle`

Note that I am trying to make use of Zotero's "Book Section" to export to Biblatex `@inbook` and `@incollection` separately, with `@inbook` as default.

**Comment by sati-bodhi** [comment]
Seems like Zotero's "Book Section" is defaulted to `@incollection` with the correct field of `booktitle`. Setting `tex.referencetype` otherwise would export "Book Title" as `journaltitle`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.85.7356](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7356.xpi) ("adjust tests")

Install in Zotero by downloading [test build 5.2.85.7356](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7356.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
7356 fixes the problem shown in `KF7MT934-apse`. Can you test? Then I can merge and release.

**Comment by sati-bodhi** [comment]
The new build fixed the above problem. 

But there is one more issue: websites and blogposts, translated as `@online`, exports "Website Title" to `journaltitle`. It seems that there is presently no field corresponding to "Website Title" 
in Biblatex, but `journaltitle` is definitely way off. 

![圖片](https://user-images.githubusercontent.com/7592695/98635889-b7a7eb80-2360-11eb-93b8-12c806279161.png)

Perhaps we could just use websitetitle as is, in a customized field.

**Comment by retorquere** [comment]
I agree that journaltitle goes against the manual, but then so does websitetitle. Moving to websitetitle doesn't look like an improvement in that sense.

**Comment by njbart** [comment]
I’d suggest using `organization`.

- Used by biblatex-chicago for website titles (e.g., `CNN.com`, `Twitter`, `Evanston Public Library` and others; see example files).
- Not explicitly associated with website titles, but at least recognized and rendered, typically right after the `title` field, by (vanilla) biblatex.
- Better than biblatex-apa’s hack of using the `eprint` field (again, see the package’s example files) – which users might want to use for genuine `eprint` information instead.

**Comment by retorquere** [comment]
@sati-bodhi can you send a debug log for the item that gets exported as `@online`?

**Comment by sati-bodhi** [comment]
> @sati-bodhi can you send a debug log for the item that gets exported as `@online`?

WP99WRJL-apse

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.85.7373](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7373.xpi) ("Merge branch 'master' into gh-1691")

Install in Zotero by downloading [test build 5.2.85.7373](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7373.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.85.7378](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7378.xpi) ("adjust test cases for #1691")

Install in Zotero by downloading [test build 5.2.85.7378](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7378.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by sati-bodhi** [comment]
The test build works as expected. Thank you.
