### ISSUE TITLE
Changing item type for only BibLaTeX does not work

### ISSUE THREAD

**Issue by marcschulder** [retorquere/zotero-better-bibtex#1694]
**Report ID:** BQSLU8LU-euc

**Exporter used:** Better BibTeX / BetterBibLaTeX

**Expected behavior:**
In #1516 it is mentioned that the reference type can be changed for BibLaTeX without affecting BibTeX by using `biblatex.referencetype: periodical` instead of `tex.referencetype: periodical` in the extra field.

**Actual behavior:**
Both commands work the same. Better BibTeX and Better BibLaTeX exports are affected by either one. When specifying multiple commands (I initially used `bibtex.referencetype` and `biblatex.referencetype` in the hope of changing types for both independently), whichever is last is applied for both exports.

I would love to be able to specify types **and** fields independently for both, as I do require both formats for various purposes. My main application would be to add more fields to BibLaTeX without bloating up BibTeX with unusable fields, but I've also had situations in the past where I hacked a field for BibTeX while BibLaTeX was fine with the default export.

**Comment by marcschulder** [comment]
Can confirm that that fixed it. Thanks a bunch for the quick response!

**Comment by retorquere** [comment]
Took longer than I had expected actually. Thanks for reporting it.
