### ISSUE TITLE
biber 2.14 rejects the date field generated from Better BibLaTex

### ISSUE THREAD

**Issue by minecraft2048** [retorquere/zotero-better-bibtex#1695]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID:** CGEI6CRU-apse

**Exporter used:** Better BibLaTex with Keep updated checkbox ticked

**Expected behavior:** biber can import exported bib file without any warnings

**Actual behavior:**
Generated bib file (dp.bib):
```

@online{ruderOverviewGradientDescent2016,
  title = {An Overview of Gradient Descent Optimization Algorithms},
  author = {Ruder, Sebastian},
  date = {2016-01-19T14:20:00.000Z},
  url = {https://ruder.io/optimizing-gradient-descent/},
  urldate = {2020-11-24},
  abstract = {Gradient descent is the preferred way to optimize neural networks and many other machine learning algorithms but is often used as a black box. This post explores how many of the most popular gradient-based optimization algorithms such as Momentum, Adagrad, and Adam actually work.},
  file = {/home/byakuya/Zotero/storage/3HRV92HZ/optimizing-gradient-descent.html},
  langid = {english},
  organization = {{Sebastian Ruder}}
}

@article{tibshiraniLecture15Log,
  title = {Lecture 15: {{Log Barrier Method}}},
  author = {Tibshirani, Ryan and Dasigi, Pradeep and Gowayyed, Mohammad},
  pages = {7},
  file = {/home/byakuya/Zotero/storage/GFL5QTM7/Tibshirani et al. - Lecture 15 Log Barrier Method.pdf},
  langid = {english}
}
```
ext3.bcf for use with biber: https://gist.github.com/minecraft2048/5ec0204799520c4db1887338cfc0b4a1

Run `biber ext3.bcf` 

Actual biber output:
```
INFO - This is Biber 2.14 (beta)
INFO - Logfile is 'ext3.blg'
INFO - Reading 'ext3.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'dp.bib'
INFO - Globbed data source 'dp.bib' to dp.bib
INFO - Looking for bibtex format file 'dp.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'dp.bib'
WARN - Entry 'ruderOverviewGradientDescent2016' (dp.bib): Invalid format '2016-01-19T14:20:00.000Z' of date field 'date' - ignoring
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'nty/global//global/global' of type 'entry' with template 'nty' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'ext3.bbl' with encoding 'UTF-8'
INFO - Output to ext3.bbl
INFO - WARNINGS: 1
```
biber rejects the date field generated from Better BibLaTex because the date format `2016-01-19T14:20:00.000Z` that is exported from Zotero have milliseconds in it, which is that trailing zeros after that decimal point. If I manually delete the millisecond portion of the date field it then biber accepts the file without any warning

**Comment by retorquere** [comment]
I'm not sure why biber is rejecting this; I've reported it at https://github.com/plk/biber/issues/352 . For the time being, you can go into the [hidden options](https://www.zotero.org/support/preferences/hidden_preferences) and set `biblatexExtendedDateFormat` to `false`.

**Comment by retorquere** [comment]
The next version of biber will accept the date as it was, but build 137 work with biber 2.14 -- I'd appreciate it if you could test it.
