### ISSUE TITLE
tex.origdate ignored in citekey generation

### ISSUE THREAD

**Issue by kevinmorio** [retorquere/zotero-better-bibtex#1696]
**Report ID:** 6YBCMKDU-euc

**Expected behavior:** The citekey should be `orwell1945` thereby using the year given in `tex.origdate`.

**Actual behavior:** The citekey is `orwell2008` and thus falls back to the `date` field.

**Comment by retorquere** [comment]
I'm sorry -- this has escaped my attention, absolutely didn't mean for it to take so long to respond. Can you get me a new debug log? I didn't pick up `6YBCMKDU-euc` and it has since expired.

Almost two months -- apologies!

**Comment by kevinmorio** [comment]
Of course! No problem, the report ID is `85EV34KP-euc`.

**Comment by retorquere** [comment]
I need a debug log created by right-clicking the item you describe above, and selecting "send debug log" under "better bibtex" in the menu that pops up.

**Comment by retorquere** [comment]
Can you try replacing `tex.origdate:` with `Original Date:` in the `extra` field? The `tex` fields don't have any special meaning to BBT other than that they're exported as-is; `Original Date:` is Zotero's way to add a "field" for things that it does support but does not have a field for in the GUI. BBT will pick it up for citekey generation, it will still be exported as `origdate` for biblatex exports, and as a side benefit you will also get the original date in Zotero-generated bibliographies.

**Comment by kevinmorio** [comment]
**Report ID:** TEQ4634L-euc

Using `Original Date:` or `original-date:` works fine. Thank you for the explanation about how this is handled by BBT and Zotero. I only noticed the issue of `tex.origdate` when importing bibtex entries from clipboard which add `tex.origdate` in the `extra` field when present. So it seems to be more an issue of how Zotero imports bibtex entries than with BBT.

**Comment by retorquere** [comment]
Good point -- build 339 will move `origdate` to `Original Date` rather than `tex.origdate`.

**Comment by kevinmorio** [comment]
Thanks, that works perfectly!. I didn't know that the import functionality is provided by BBT.

**Comment by retorquere** [comment]
It is when BBT is installed. If BBT is not installed, or if you disable BBT imports, imports are done by Zotero itself, but BBT's import fidelity is much better.
