### ISSUE TITLE
Fetch using JSON-RPC with JavaScript

### ISSUE THREAD

**Issue by eurunuela** [retorquere/zotero-better-bibtex#1697]
**Your question/suggestion:**

Is it possible to use JavaScript to export using JSON-RPC?

I'd like to do the [curl command in the docs](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/) but on JavaScript. I have tried the following but I get a `net::ERR_BLOCKED_BY_CLIENT` error.

```
var citeKey = 'urunuela2020StabilityBasedSparseParadigm';
const response = await fetch("http://localhost:23119/better-bibtex/json-rpc", {
  body: "{'jsonrpc': '2.0', 'method': 'item.search', 'params': ['" + citeKey + "']}",
  headers: {
    Accept: "application/json",
    "Content-Type": "application/json"
  },
  method: "POST"
});
var data = await response.json();
console.log(data);
```

Thank you!

**Comment by retorquere** [comment]
Where is this running? Node or browser?

**Comment by eurunuela** [comment]
It's running in the browser (RoamResearch to be more specific).

**Comment by retorquere** [comment]
Zotero has started blocking requests from browsers a while ago (for a good reason I might add) so this is out of reach for browsers (and out of my control). It might be possible to send post requests from a browser - I'd have to go find out.

**Comment by eurunuela** [comment]
I tried using the [Zotero Web API](https://www.zotero.org/support/dev/web_api/v3/basics#export_formats) to do the same but I couldn't make it work. That's why I thought that the JSON-RPC from BBT was going to be easier. If you happen to know how I can get the same results with the Zotero API, that would be awesome.

**Comment by retorquere** [comment]
This cannot be done with the Zotero web API. You could use the Zotero Web API to sync an offline copy and search that, but that's going to be a bit of work.

**Comment by eurunuela** [comment]
So what would you suggest is the best way to retrieve a JSON object from Zotero given a citeKey from RoamResearch (i.e. browser)?

**Comment by retorquere** [comment]
I'm afraid it won't be possible without a browser plugin. Browser plugins are not subject to the same restrictions as general web pages, so a plugin could serve as a bridge between the Roam webpage and the Zotero local web API.

**Comment by eurunuela** [comment]
Thank you! It looks like I may have to learn plugin programming on the Christmas holidays 🙈
