### ISSUE TITLE
Keep updated option not available

### ISSUE THREAD

**Issue by larsniebusch** [retorquere/zotero-better-bibtex#1698]
Report ID: ZAVUSVUQ-euc

After a first install of Zotero and BBT, the option 'Keep updated' is not being shown when opening the export dialogue. I couldn't find any way to make it happen. Since your [tutorial](https://retorque.re/zotero-better-bibtex/exporting/auto/) implies it should be there immediately, I assumed it was excluded by choice, since Zotero changed some things about the export for security reasons, although I couldn't find anything online. Any help much appreciated.

**Comment by retorquere** [comment]
With what exporter are you trying to use "keep updated"? "keep updated" only shows for BBTs own exporters.

**Comment by larsniebusch** [comment]
BBT export, of course. BBT added an item for export on the right-click context menu for folders, which I used. Though I understand that could have been a reason for a post such as mine. 
Since you're asking, I assume the feature still works and has not been removed?

**Comment by qqobb** [comment]
@larsniebusch: Could it be that you're referring to ["Download Better BibTeX export..."](https://retorque.re/zotero-better-bibtex/exporting/pull/)? You should get the "Keep updated" option with "Export Collection…", then selecting "Better BibTeX".

I tried to clarify this with PR #1699.

**Comment by retorquere** [comment]
In the export method @qqobb describes (and which I had assumed @larsniebusch meant), "Keep updated" still works and has not been removed.

**Comment by retorquere** [comment]
Is this issue resolved?

**Comment by larsniebusch** [comment]
Yes.
