### ISSUE TITLE
Pin BibTex key from InspireHEP stopped working 

### ISSUE THREAD

**Issue by jantoniadis** [retorquere/zotero-better-bibtex#1702]
**Report ID:** LQEU3FTQ-euc

**Expected behavior:** Citekey should be replaced by the InspireHEP key when this option is selected

**Actual behavior:** Citekey is not updated. It did work for some time after the new InsireHEP API was released, but not anymore 

Thanks in advance for the feedback

**Comment by retorquere** [comment]
`LQEU3FTQ-euc` has the arXiv identifier in the `pages` field, I don't think that has ever worked? The current behavior expects the arXiv identifier to be in the `publication title` field.

**Comment by jantoniadis** [comment]
Thanks @retorquere!  

However, the same seems to happen with all entries, including those for which the arXiv id is in the publication title field. 
Another example:  
**Report-ID**: XLFKGFUR-euc

**Comment by retorquere** [comment]
in `XLFKGFUR-euc` the publication title field has `The Astrophysical Journal`. I don't see an arXiv ID in this entry.

**Comment by jantoniadis** [comment]
Indeed, but still, `Pin BibTex key from InspireHEP` doesn't fetch the  InspireHEP key

**Comment by retorquere** [comment]
Man I don't know why my mind went there. I think I know the cause.

**Comment by retorquere** [comment]
Can you try build 179 above?

**Comment by jantoniadis** [comment]
Sorry, now there is an `error fetching the InspireHEP key` error; see `Y9286FGY-euc`

**Comment by jantoniadis** [comment]
Slightly different error:
`Could not fetch InspireHEP key from DOI []...PID does not exist`

see `X8EV5EIG-euc`

**Comment by retorquere** [comment]
The `PID does not exist` message comes from inspireHEP, not BBT. A new build will be rolling in soon that will make that more explicit, but you have `10.1093/mnras/stw2759` in the `DOI` field, and when I call https://inspirehep.net/api/doi/10.1093/mnras/stw2759 based on that, I get `{"status": 404, "message": "PID does not exist."}` as a response. You can click that link and see that result.

**Comment by jantoniadis** [comment]
build 191 works as intended, thanks @retorquere!

Indeed, `PID does not exist` means that this particular entry is not in InspireHEP, my bad!

**Comment by retorquere** [comment]
Cool, thanks for the confirmation, 5.2.79 is building
