### ISSUE TITLE
Suppress authors in better-bibtex-citekeys.csl style?

### ISSUE THREAD

**Issue by jogrue** [retorquere/zotero-better-bibtex#1703]
Hi all,

I was using the better-bibtex-citekeys.csl to go from Word to Pandoc---this is a great hidden feature, thanks a lot for that. Previously, I was trying to use regex to get Pandoc citation from the Zotero field codes ...

The only thing that does not work is suppressing authors. If the regular citation looks like that `[@jogru-bugreport-2020]`, it should become `[-@jogru-bugreport-2020]` if "suppress authors" is checked. In the Zotero field code for Word "suppress-author":true is added.

I tried it with a macro like this in the CSL:

``` xml
  <macro name="noauthor">
    <choose>
      <if variable="suppress-authors">
        <text value="@" prefix="-"/>
      </if>
      <else>
        <text value="@"/>
      </else>
    </choose>
  </macro>
```

I also tried `suppress-author` as variable name (because that is how it is documented for citeproc-js: https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cite-items). Unfortunately, this also did not work. Finally, I tried "author" as the variable name because I thought the suppress author tickbox would maybe just unset the author name. This also did not work. Also, I could not really figure out why the author disappears in other styles.

I might further look into this but since my CSL knowledge is almost zero, maybe someone already has an idea how to check if "suppress-authors" is set.

Best,
Johann

**Comment by jogrue** [comment]
I really think the debug log is unnecessary here, at least if you are not telling me it should work already. However, in case, here it is: D928181290

**Comment by retorquere** [comment]
Yeah 

> I might further look into this but since my CSL knowledge is almost zero, maybe someone already has an idea how to check if "suppress-authors" is set.

"Someone" is just me on this repo. And unfortunately I know absolutely nothing about CSL, being, after all, a LaTeX-head.

> I really think the debug log is unnecessary here, at least if you are not telling me it should work already. However, in case, here it is: D928181290

It isn't necessary here, it's just the standard reply by `label-gun` if you select anything else than `question` for the issue type. I can only read BBT-specific logs BTW (the ones whose IDs end in `-euc` or `-apse`); the `D<number>` reports are only accessible to the official Zotero crew.

**Comment by retorquere** [comment]
I don't know anything about CSL; you'll fare better asking this question on the Zotero forums.
