### ISSUE TITLE
arXiv Items Being Exported as `online`

### ISSUE THREAD

**Issue by ultimatecheese** [retorquere/zotero-better-bibtex#1704]
I frequently download citation data of preprints from arXiv. Here is an example of a downloaded citation.

![image](https://user-images.githubusercontent.com/14955065/102799353-52590880-43aa-11eb-88ff-1b53c12e964c.png)

This gets exported as the following.

![image](https://user-images.githubusercontent.com/14955065/102799419-6c92e680-43aa-11eb-8ea3-363263957ec2.png)

I am not sure why it's coming as `online`, not `article`. I use `biblatex` with a custom style and want it to fall in the `@article` class

**Comment by ultimatecheese** [comment]
BBT debug report: TQS8HMXR-euc

**Comment by qqobb** [comment]
> I am not sure why it's coming as `online`, not `article`. I use `biblatex` with a custom style and want it to fall in the `@article` class

See here for an explanation:
https://forums.zotero.org/discussion/86748/change-the-online-entry-type

**Comment by ultimatecheese** [comment]
Hmm, that is a shame. Naturally the majority of what I download are journal articles, just not yet accepted for publication. Thus I desire the same style for arxiv articles as for journal articles, but with the journal details replaced with the arxiv details.

I've had a read of the link and the link inside that. They're relatively recent questions. I see mentioned the claim that biblatex requires a journal entry. Is this a recent change from biblatex? Only I have old exports which do not have the journal entry. Also, it doesn't _appear_ to be true. By this I mean that I just made a file with `@article` but no `journaltitle` entry and it was fine.

I'm not very good at writing these postscripts. Is there a way to use that to convert these `@article`s into the more natural `@online`? It looks like some variant on the following should work, maybe?

```
if (Translator.BetterBibTeX && reference.referencetype === 'article' && item.arXiv) {
  if (reference.has.journal && item.arXiv.source === 'publicationTitle') {
    reference.remove('journal');
  }
  if (!reference.has.journal) reference.referencetype = 'misc'
}
```

I tried just replacing `BibTeX` with `BibLaTeX` and `'misc'` with `'article'`. I also tried removing the first `if` statement. But this didn't work.

**Comment by retorquere** [comment]
I understand that most authors who put their work on arXiv wishes their work to be published at some point, but biblatex expects there to be a `journaltitle` field, and with arXiv papers, there isn't anything to put there. biblatex won't error out (it hardly ever does regardless of what you give it), but if you inspect your logs, you will see the warning.

Given that biblatex will not be able to properly style it as a journal article (and that is not new, that's ancient), I don't really see the benefit over having it be `@article` instead of `@online`, where the `@article` will generate warnings in the compile.

Anyhow, I'd be happy to write a postscript for you, but going by

> Is there a way to use that to convert these `@article`s into the more natural `@online`?

I'm not sure what you want the postscript to do? BBT already exports `TQS8HMXR-euc` as `@online`.

**Comment by ultimatecheese** [comment]
Thanks, retorquere, for getting back to me so quickly.

Apologies for the typo. I wanted to convert `@online` into `@article`---contrary to what I wrote!

If that is possible, that would be great. Otherwise I'm sure I can come up with a work around. I think only on one occasion have I ever referenced something which is actually `online` (a blog), so worst come to worst I can just just define `@online` to be the same as `@article` in my `biblatex` custom commands.

Thanks so much for BBT---it's amazing, I love it! :-)

**Comment by retorquere** [comment]
Also you wanted this for biblatex, right? And just change archive `@online`s to `@article`? Then it'd become

```
if (Translator.BetterBibLaTeX && reference.referencetype === 'online' && item.arXiv) {
  reference.referencetype = 'article'
}
```

What differences does biblatex render between `journaltitle`-less `@article`s and `@online`?

**Comment by ultimatecheese** [comment]
That works perfectly, thank you :)

Regarding the differences, I'm not sure what the default behaviour does. I use the following drivers.

```
\DeclareBibliographyDriver{article}{%
	\usebibmacro{bibindex}%
	\usebibmacro{begentry}%
	\usebibmacro{author}%
\setunit{\addspace}%
	\usebibmacro{date}%
\newunit\newblock
	\usebibmacro{title}%
\newunit\newblock
	\printfield{journaltitle}\addperiod%
\setunit*{\addspace}%
	\usebibmacro{volume+number+eid}%
\setunit*{\addspace}\newblock
	\printfield{pages}
\setunit*{\addspace}%\newblock
	\printfield{comments}%
	\usebibmacro{eprint}%
\setunit*{\addspace}%
	\printfield{doi}%
	\usebibmacro{finentry}%
}

\DeclareBibliographyDriver{online}{%
	\usebibmacro{bibindex}%
	\usebibmacro{begentry}%
	\usebibmacro{author}%
\setunit{\addspace}%
	\usebibmacro{date}%
\newunit\newblock
	\usebibmacro{title}%
\newunit\newblock
	\usebibmacro{eprint}%
%\setunit{\addspace}%
%	\usebibmacro{urldate}
	\usebibmacro{finentry}%
}
```

A few of those  are custom fields that I've created. I don't really see why, but after the fairly recent* change to making the output `@online` instead of `@article`, the arXiv stuff was coming up with the title in italics. [*I'm not sure exactly when this happened. I have old `.bib` files which have `@article`. I only noticed the change yesterday.]

**Comment by ultimatecheese** [comment]
Yikes, closing and reopening accidentally, sorry. Feel free to close when you're ready and delete this comment.

**Comment by retorquere** [comment]
The change is recent in BBT.
