### ISSUE TITLE
google-scholar like references

### ISSUE THREAD

**Issue by jvdheyden** [retorquere/zotero-better-bibtex#1705]
as discussed in https://github.com/retorquere/zotero-better-bibtex/issues/595#issuecomment-749103313

**Report ID:** DPPQBHSL-euc, S6YAXWZ5-euc:

**Exporter used:** BetterBibTex

**Expected behavior:**elkaafarani2020lossy, yoo2017postquantum

**Actual behavior:**el2020lossy, yoo2017post

**Comment by retorquere** [comment]
Do you think you can provide a description of the algorithm that generates these keys? I have tests running on a more general solution, but that is going to get you a much more elaborate pattern. If there is a clear algorithm, I could just implement it as `[google]`.

**Comment by retorquere** [comment]
207 adds regex replace which will make this pattern work:

```
[Auth:lower:replace=\[-\ \].*,,regex:alphanum][year][Title:skipwords:replace=\[-\ \].*,,regex:alphanum:lower]
```

It ain't pretty, but until someone can give me the algorithm that google scholar uses to create keys, this reproduces the keys you mentioned above.

**Comment by jvdheyden** [comment]
Thank you, works like a charme!
