### ISSUE TITLE
can you improve the length of the Citation Key in Chinese

### ISSUE THREAD

**Issue by zoushucai** [retorquere/zotero-better-bibtex#1706]
- [x] Key generation enhancement
- [x] enhancement

Let Citation Key format: [auth:lower][year][veryshorttitle:lower]

However, the Citation  Key of Chinese literature is too long.  I hope to use only the first one or two character in title,

eg: [Article links](https://kns.cnki.net/kcms/detail/detail.aspx?filename=1018101333.nh&dbcode=CMFD&dbname=CMFD2019&v=%25mmd2BYOeIDrMsVKKx6wbIa3IaWFtWs0UFL%25mmd2FMUouSY3inEJjiMk9VGP2pPvJ5RhuAWivY)

**Expected behavior:  zhangqisheng2018jiyu **

**Actual behavior: zhangqisheng2018jiyufenjiesixiangdeduomubiaojinhuasuanfayanjiu **

**Comment by retorquere** [comment]
Without the requested debug log, I can only guess at what you want. You could try `[auth:lower][year][Title:split-ideographs:select=1,3:lower]`. If you want something else, I'll need a debug log as outlined above.

**Comment by zoushucai** [comment]
> Without the requested debug log, I can only guess at what you want. You could try `[auth:lower][year][Title:split-ideographs:select=1,3:lower]`. If you want something else, I'll need a debug log as outlined above.

Wow, that's just what I want, thank you,
