### ISSUE TITLE
Incorrect export of entries, where authors only have last names

### ISSUE THREAD

**Issue by xianwenchen** [retorquere/zotero-better-bibtex#1707]
**Report ID:** 376MAQ39-euc

**Expected behavior:**

Let the last name of an author be "Test and Examine Center".
There is no first name.

The exported author name should be:
author = {{Test and Examine Center},},

**Actual behavior:**

The exported author name in biblatex becomes
author = {Test {and} Examine Center},

As a consequence, in the bibliography, the author becomes
Center, Test and Examine ...

**Comment by xianwenchen** [comment]
**Report ID:** 376MAQ39-euc

**Comment by retorquere** [comment]
If you click on the "switch to single field" icon next to the name, you'll get the export you want.

**Comment by xianwenchen** [comment]
Thank you! Sorry that I didn't know this feature.
