### ISSUE TITLE
file field export problem

### ISSUE THREAD

**Issue by rhaynes74** [retorquere/zotero-better-bibtex#1708]
Hi folks, when I export my library from the latest version of zotero and in better bibtex format my file fields look like:

/Users/rhaynes/Zotero/storage/CDJEJLSE/Abushammala et al. - 2015 - A novel fixed point iteration method for the solut.pdf;/Users/rhaynes/Zotero/storage/D57ASCSY/S0096300315012102.html

What combination of settings would change this to just be the pdf attachment? 

Best,
R Haynes

**Comment by rhaynes74** [comment]
Hi folks, here is the debug id:

L8498G83-euc

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by retorquere** [comment]
There's no folks, just me.

L8498G83-euc was generated from the help menu (point 2), not by right-clicking the references (point 1), but there isn't a setting that allows filtering of attachments. You could do it with a postscript such as

```
if (Translator.BetterTex && item.attachments) {
  reference.add({ name: 'file', value: item.attachments.filter(a => (a.defaultPath || a.localPath || '').toLowerCase().endsWith('.pdf')), enc: 'attachments' })
}
```

**Comment by rhaynes74** [comment]
Thanks - I will give it a try!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment]
I placed the script in the postscript dialog in the better bibtex settings but I don't see any difference in the output.

**Comment by retorquere** [comment]
Sorry, it had a typo, now corrected.

**Comment by rhaynes74** [comment]
Thanks - will give the new one a try as well.   Might be adaptable to situations that the editor search and replace won’t handle.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by retorquere** [comment]
Editor search and replace?

**Comment by rhaynes74** [comment]
An editor search and replace can be used to remove the additional file names from the file field. Not elegant, but generally works.

**Comment by retorquere** [comment]
I still do not understand, sorry.  The postscript will leave only the `PDF` attachments in the export. If you want only a single PDF, that would be

```
if (Translator.BetterTeX && item.attachments) {
  const pdfs = item.attachments.filter(a => (a.defaultPath || a.localPath || '').toLowerCase().endsWith('.pdf'))
  if (pdfs.length) {
    reference.add({ name: 'file', value: [pdfs[0]] , enc: 'attachments' })
  } else {
    delete reference.has.file
  }
}
```

**Comment by rhaynes74** [comment]
Hi - thanks, the first script now works.
