### ISSUE TITLE
Zotero export BibTex file titles are all in uppercase?

### ISSUE THREAD

**Issue by zoushucai** [retorquere/zotero-better-bibtex#1712]
- [x] Export

I recently found that a new function ”BBT sentence case“ has been added, which I like very much.

When I export the BibTex file, the title of my Zotero software interface has been changed to the "BBT sentence case" style. However, when I export the BibTex file, all the titles in the bib file are in the form of initials?

**Report ID: D1481547640 **

```

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://1228075512%40qq%2Ecom:****@dav.jianguoyun.com/dav/zotero/
Line Number 1, Column 1:" {file: "https://1228075512%40qq%2Ecom:****@dav.jianguoyun.com/dav/zotero/" line: 1}]

Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'

version => 5.0.94, platform => MacIntel, oscpu => Intel Mac OS X 10.14, locale => en-GB, appName => Zotero, appVersion => 5.0.94, extensions => ZotFile (5.0.16, extension), Zotero Scihub (0.0.7, extension), ZoteroQuickLook (1.4.2, extension), Zotero DOI Manager (1.3.9, extension), Jasminum (0.0.8, extension), Zutilo Utility for Zotero (3.6.1, extension), Zotero LibreOffice Integration (5.0.25.SA.5.0.94, extension), Zotero Word for Mac Integration (5.0.30.SA.5.0.94, extension), Zotero Storage Scanner (5.0.8, extension), Better BibTex for Zotero (5.2.102, extension)

```
![2020123009QQ20201230-092244](https://gitee.com/zscqsmy/blogimg/raw/master/uPic/2020123009QQ20201230-092244.png)

**Expected behavior: The title in the bib file should be "A consistency improving method in the analytic hierarchy process based on directed circuit analysis"**

**Actual behavior:  But  the title in the bib file should  be  "A Consistency Improving Method in the Analytic Hierarchy Process Based on Directed Circuit Analysis" **

**Comment by retorquere** [comment]
Report IDs with `D<number>` go to the Zotero devs, I cannot access those. I need a debug report generated as described in point 1 above.

But what you describe is likely covered [here](https://retorque.re/zotero-better-bibtex/support/faq/#bbt-is-changing-the-capitalization-of-my-titles----why). If you really do want titles in sentence case (even though that means that you are feeding bib(la)tex sentence case, where it *absolutely* expects Title Case), you can turn it off as described [here](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-title-casing-to-titles), but then you cannot complain about faulty rendering.

**Comment by zoushucai** [comment]
Thank you. My problem has been solved. 
Is Report IDs similar to this style? eg ：‘HXU49LWA-apse’

**Comment by zoushucai** [comment]
> Report IDs with `D<number>` go to the Zotero devs, I cannot access those. I need a debug report generated as described in point 1 above.
> 
> But what you describe is likely covered [here](https://retorque.re/zotero-better-bibtex/support/faq/#bbt-is-changing-the-capitalization-of-my-titles----why). If you really do want titles in sentence case (even though that means that you are feeding bib(la)tex sentence case, where it _absolutely_ expects Title Case), you can turn it off as described [here](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-title-casing-to-titles) -- but then you cannot complain about faulty rendering.

Thank you. My problem has been solved.
Is Report IDs similar to this style? eg ：‘HXU49LWA-apse’

**Comment by retorquere** [comment]
That is correct, that is a BBT debug report. I've modified the issue template to describe the difference, you certainly weren't the first one for whom this was confusing.
