### ISSUE TITLE
How to generate citations with citation key by CSL style?

### ISSUE THREAD

**Issue by zoushucai** [retorquere/zotero-better-bibtex#1714]
- [x] Export
- [x] Key generation 

I try to right-click and select 'create bibliography from item',  and do the following:

![2020123116as](https://gitee.com/zscqsmy/blogimg/raw/master/uPic/2020123116as.png)

Generate reference file style: 
```
[1]X. Zhou, Y. Hu, Y. Deng, F.T.S. Chan, A. Ishizaka, A DEMATEL-based completion method for incomplete pairwise comparison matrix in AHP, Annals of Operations Research. 271 (2018) 1045–1066. https://doi.org/10.1007/s10479-018-2769-3.
```
However, I want to generate the following format
```
\bibitem{zhou2018dematel}  X. Zhou, Y. Hu, Y. Deng, F.T.S. Chan, A. Ishizaka, A DEMATEL-based completion method for incomplete pairwise comparison matrix in AHP, Annals of Operations Research. 271 (2018) 1045–1066. https://doi.org/10.1007/s10479-018-2769-3.

```

**Report ID: QAZ72QCR-apse**

**Expected behavior:**
```
\bibitem{zhou2018dematel}  X. Zhou, Y. Hu, Y. Deng, F.T.S. Chan, A. Ishizaka, A DEMATEL-based completion method for incomplete pairwise comparison matrix in AHP, Annals of Operations Research. 271 (2018) 1045–1066. https://doi.org/10.1007/s10479-018-2769-3.

```

**Actual behavior:**
```
[1]X. Zhou, Y. Hu, Y. Deng, F.T.S. Chan, A. Ishizaka, A DEMATEL-based completion method for incomplete pairwise comparison matrix in AHP, Annals of Operations Research. 271 (2018) 1045–1066. https://doi.org/10.1007/s10479-018-2769-3.
```

**Comment by retorquere** [comment]
This is possible by setting [citeprocNoteCitekey](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#citeprocnotecitekey) (restart Zotero to have the change take effect), and then [edit the style you want](https://editor.citationstyles.org/visualEditor/), and add a variable `note` with a pre- and postfix (see screenshot). Import that style, and render as usual.
![Screenshot 2020-12-31 at 16 02 15](https://user-images.githubusercontent.com/132108/103415257-a66da500-4b81-11eb-9f12-c6843daffe12.png)

**Comment by zoushucai** [comment]
@retorquere  It's so easy to edit CSL file. Thank you very much.
