### ISSUE TITLE
tbd deleted

### ISSUE THREAD

**Issue by phargarten2** [retorquere/zotero-better-bibtex#1715]

**Comment by phargarten2** [comment]
Report ID: M74AL9WE-euc

**Comment by retorquere** [comment]
`M74AL9WE-euc` was sent using method 2 described by @label-gun. I need a debug log sent by using method 1.

**Comment by phargarten2** [comment]
The suggestion was general in nature. I provided the reference as an example. Take any reference with a DOI and/or a URL field. I am asking that Better BibTex would add a URL (if the reference doesn't have one) or replace the URL (if the reference has one) with the DOI in form `url: https://doi.org/<doi>`. Thanks.

**Comment by retorquere** [comment]
It's incredibly frustrating that people keep second-guessing (third-guessing if you count blip-bloop's re-request) whether I do or do not need such a debug log.

It is entirely possible that what you suggest is already possible. I can tell you whether that is the case when we have common facts to reason about, in this case a sample reference which you want to export different than it does now for you. A debug log will give me that sample and will cost you less time than typing in the earlier response.

**Comment by phargarten2** [comment]
I am sorry. I shouldn't have made the suggestion. I will close and delete the issue.

**Comment by retorquere** [comment]
It's fine to make suggestions. Once I'm clear what it is precisely based on a sample I'd be more than happy to look into it.

**Comment by retorquere** [comment]
It's possible that [this](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#when-a-reference-has-both-a-doi-and-a-url-export) does what you were trying to suggest.
