### ISSUE TITLE
Identical Pinned keys lost when merging duplicated records 

### ISSUE THREAD

**Issue by comcamot** [retorquere/zotero-better-bibtex#1721]
I use the nice feature "Pin BibTeX key from InspireHEP". However, quite often I find duplicated records when bulk copying from private libraries to group libraries, which have the same pinned key. When merging those records the pinned key is lost and the new record reverts to the automatically generated key. One can re-pin the key from InspireHEP in the new merged record, but it would be nicer to keep the pinned key.

**Comment by retorquere** [comment]
If you send the problematic items with a (single!) BBT debug log as described in point 1, I can have a look.

**Comment by comcamot** [comment]
Report ID: EYCQC4BR-euc
Thank you!

**Comment by retorquere** [comment]
`EYCQC4BR-euc` was generated with only a single item selected. I need you to select both, right-click, and then send a debug log. That way I get both items.

**Comment by retorquere** [comment]
Also the item in `EYCQC4BR-euc` does not have a pinned key. I need two items in the exact state you mentioned above, just before you tried to merge them.

**Comment by comcamot** [comment]
https://user-images.githubusercontent.com/35140609/104244404-9ea3df80-5462-11eb-8e76-e3ae7498f351.mp4

This is an example of what happens.

**Comment by retorquere** [comment]
I need you to select those two items just before the merge, right-click them, and send a debug log from the menu that pops up. That will give me those items and your settings, so I can see if I can replicate it locally.

**Comment by comcamot** [comment]
JVBDY5T7-euc
I marked the two duplicated records and sent the report, then I did the merging.
In the previous report I marked the only record after merging and sent the report.

**Comment by retorquere** [comment]
Alright, I can reproduce it. I'll take a look.

**Comment by retorquere** [comment]
Can you try build 316?

**Comment by retorquere** [comment]
I'd really appreciate a confirmation of fix or more info on what doesn't work.

**Comment by comcamot** [comment]
It seems that now it works well. Thank you!
