### ISSUE TITLE
Set output file path for automatic export without GUI

### ISSUE THREAD

**Issue by mcnoat** [retorquere/zotero-better-bibtex#1724]
Operating System: PureOS (based on Debian 10.7)
Zotero version: 5.0.94 (5.0.95 is not yet available through flatpak)
BBT version: 5.2.110
File manager: Nautilus 3.30.5-stable

I want to automatically export a bib file to a directory in my `/home` directory (e.g. `/home/me/mypaper/`). For some reason the GUI file manager that is shown to me when I am supposed to select the output directory for automatic exporting, only displays the default directories (Documents, Downloads, etc.) and `Zotero/`, i.e. I cannot select `mypaper/`.
Unsuccessful solutions I tried:
* double clicking the GUI display of the path to switch to a `\dir1\dir2\` style text field
* Ctrl + L
* searching for `mypaper\` (search yielded no results)

I assume that Zotero uses Nautilus, the only file manager listed in my installed software. The interface design certainly looks like it. However, some of the solutions listed above should work in regular Nautilus...
Is there a way to change the "Output file" variable for a given automatic export without using the GUI interface? Of course, I would also welcome any other solution to this problem.

**Comment by retorquere** [comment]
This is something Zotero does. BBT just gets the resulting path. But Flatpacks are always finicky with custom directories. By default they're pretty restricted. The debs don't suffer this problem.

**Comment by mcnoat** [comment]
I found the zotero-deb Github repo on my own (wasn't aware of it previously) and install Zotero from it. Now the directory selection works properly.
Thanks.
