### ISSUE TITLE
Notes are exported as [object Object]

### ISSUE THREAD

**Issue by rubendibattista** [retorquere/zotero-better-bibtex#1725]
Exporting an item that has notes, produces a `.bib` file where the `notes`  field contains the string `[object Object]`. 

```
@book{alighieri_divine_nodate,
  title = {The {{Divine}} Comedy of {{Dante Alighieri}} /},
  author = {Alighieri, Dante},
  publisher = {{Houghton Mifflin}},
  file = {C\:\\Users\\ruben\\Zotero\\storage\\PQXYBS99\\cmc.marmot.org.html},
  note = {[object Object]}
}
```
![image](https://user-images.githubusercontent.com/8077364/104676634-0cad0880-56e8-11eb-9071-dbaa3b1f9553.png)

**Report ID:**
AMFG4JEY-euc

**Exporter used:**
BetterBiblatex

**Expected behavior:**
It should export the string in the note

**Actual behavior:**
It exports the string [object Object]

**Comment by rubendibattista** [comment]
I just submitted the report with BBT: AMFG4JEY-euc

**Comment by retorquere** [comment]
Sorry it took so long. Can you try build 317 above?

**Comment by rubendibattista** [comment]
Thanks! It works!

**Comment by rubendibattista** [comment]
Ok, I don't know how to close the issue 😂

**Comment by retorquere** [comment]
You can't close issues, sorry - I keep them open until I have merged the solution to master so I don't forget to include it in a release.
