### ISSUE TITLE
How to rename existing attached .pdfs with citekey?

### ISSUE THREAD

**Issue by cobblepot1** [retorquere/zotero-better-bibtex#1726]
I have a number of items with attached .pdfs and I would like to rename the .pdf files with the item citekey name. When I use the Zotero "rename" keyboard shortcut, it renames the files but I don't know any way to get Zotero to rename using a citekey. I have Zutilo installed but I don't know how to get Zutilo to rename an existing attachment without locating the pdfs individually and reattaching the times. This will not work for me because I want to rename over 5000 .pdfs.

Is there a way to rename all .pdfs with the citekey? Ideally I would be able to select multiple items and use a keyboard shortcut to rename. Any solutions welcome. Thanks.

**Comment by retorquere** [comment]
This functionality is more suited for Zotfile. The BBT citekeys are available to other plugins such as zutilo.

**Comment by qqobb** [comment]
@cobblepot1: The ZotFile add-on can already use BBT's citekey for renaming files, see here: https://github.com/jlegewie/zotfile/issues/468.

**Comment by retorquere** [comment]
Oh cool I'll need to remember that.
