### ISSUE TITLE
format of zotero:// links

### ISSUE THREAD

**Issue by damiencourousse** [retorquere/zotero-better-bibtex#1727]
Exports from better bibtex can generate links with two different formats, as follows:

-    with the citation key: `zotero://select/items/ + citekey`
-    with the zotero reference key: `zotero://select/library/items + key`

Example of exports  (each by adjusting the configuration of zotero and BBT settings):
- with the citation key:  `zotero://select/library/items/TBRBVPID`
- with the zotero reference key: `zotero://select/items/@clearZettelkastenHowOne2020`

Is it the correct format?  Is there somewhere a specification or a document that describes the link formats?

I am using zotxt-emacs, and the author reports [in zotxt-emacs issue #53](https://github.com/egh/zotxt-emacs/issues/53) that the proper format for zotero links is: `zotero://select/items/[LIBRARY]_[KEY]`

- release of Zotero: using zotero 5.0.95 on Linux
- release of BBT: using version v5.2.110

**Report ID:**  K5KZXE8R-euc

**Exporter used:**  Better BibTeX Citation Key Quick Copy

**Expected behavior:**  seems OK but another plugin describes another export format, discussed above and in [in zotxt-emacs issue #53](https://github.com/egh/zotxt-emacs/issues/53)

**Actual behavior:** seems OK but another plugin describes another export format

**Comment by qqobb** [comment]
With BBT, you can use:
```
zotero://select/items/@[citekey]
zotero://select/items/bbt:[citekey]
```
This is not something pure Zotero offers, it's a (cool) feature of the BBT add-on. As far as I know, this is not documented, but you can read more about it in #769.

Currently, Zotero's official format for these links is:
```
zotero://select/library/items/[itemKey]
```
The old format `zotero://select/items/[LIBRARY]_[KEY]` is also still supported. You need to look at Zotero's source code for documentation, e.g., [here](https://github.com/zotero/zotero/blob/2adf0e6d3cab50959f0307fa2d663a9c82ea60bc/components/zotero-protocol-handler.js#L715-L725). You can also find related discussions on the Zotero forum, e.g., [here](https://forums.zotero.org/discussion/73893/zotero-select-for-collections).

BTW, the [Zutilo add-on](https://github.com/wshanks/Zutilo) can help you with creating `zotero://select` links.

**Comment by damiencourousse** [comment]
Thanks for the detailed feedback!

**Comment by retorquere** [comment]
Thanks for picking up the slack - I'm a bit swamped at the moment.
