### ISSUE TITLE
ids field should be created in raw mode

### ISSUE THREAD

**Issue by mortang2410** [retorquere/zotero-better-bibtex#1729]
When merging two duplicate biblatex entries with different citation keys in zotero, if one citation key has an underscore `_`, then the underscore will be escaped  `\_` in the exported biblatex file.

Expected behavior: the underscores should not be escaped. 

A minimal working example: mwe.bib
```
@Article{Titi_Gwiazda_conservation_entropy,
  author = {Claude Bardos and Piotr Gwiazda and Agnieszka Świerczewska-Gwiazda and Edriss S. Titi and Emil Wiedemann},
  title  = {Onsager's conjecture in bounded domains for the conservation of entropy and other companion laws},
  year   = {2019},
  eprint = {arXiv:1902.07120},
}

@Article{bardosOnsagerConjectureBounded2019,
  author        = {Bardos, Claude and Gwiazda, Piotr and Świerczewska-Gwiazda, Agnieszka and Titi, Edriss S. and Wiedemann, Emil},
  title         = {Onsager's Conjecture in Bounded Domains for the Conservation of Entropy and Other Companion Laws},
  year          = {2019},
  month         = feb,
  abstract      = {We show that weak solutions of general conservation laws in bounded domains conserve their generalized entropy, and other respective companion laws, if they possess a certain fractional differentiability of order 1/3 in the interior of the domain, and if the normal component of the corresponding fluxes tend to zero as one approaches the boundary. This extends various recent results of the authors.},
  archiveprefix = {arXiv},
  eprint        = {1902.07120},
  eprinttype    = {arxiv},
  keywords      = {Mathematics - Analysis of PDEs},
  primaryclass  = {math},
  url           = {http://arxiv.org/abs/1902.07120},
  urldate       = {2020-09-13},
}

```
If you try to import and merge these two entries (seen as duplicates), you will see a correct tex.ids in Zotero
![Captzgzxbdsure](https://user-images.githubusercontent.com/3200308/106111803-5abb0680-6101-11eb-90df-824ecebef4b0.JPG)
But the exported biblatex file will have escaped underscores.
![Captuzdhrazre](https://user-images.githubusercontent.com/3200308/106111951-86d68780-6101-11eb-89ad-cbc1f6b56ef8.JPG)

Everything I use is up-to-date.

**Comment by mortang2410** [comment]
HYDZZZTH-euc

**Comment by retorquere** [comment]
I need a log with both items, pre-merge. `HYDZZZTH-euc` has only the resulting item.

**Comment by mortang2410** [comment]
Pre-merge: G75BCQBZ-euc

I updated to the test build 5.2.110.321 
The problem still persists for me. Have you been able to reproduce it?

**Comment by retorquere** [comment]
> The problem still persists for me. Have you been able to reproduce it?

I have. Does the problem persist for you on export of the existing item? Or for items that are newly merged? For newly merged items it should be fixed.

**Comment by mortang2410** [comment]
I am using 5.2.110.323 and the problem still persists, even when I delete the entries, make new ones, change citation keys etc. 
![Captugxre](https://user-images.githubusercontent.com/3200308/106381002-cbb12700-636a-11eb-9579-ae1bc0d8f99a.JPG)

I assume I will have to wait for your fix for existing items.

**Comment by retorquere** [comment]
A test was failing and then the build pipeline doesn't produce a test build. Making new entries, deleting entries or changing the citekeys won't trigger the new behavior, only merges do. The build that will drop soon will always export `ids` unescaped, the earlier build only fixed the merges so that they become `tex.ids=` rather than `tex.ids:`.

**Comment by retorquere** [comment]
Can you try whether build 330 fixes it for you?

**Comment by mortang2410** [comment]
Awesome! Everything is fixed now.

**Comment by retorquere** [comment]
Cool. I'm collecting a few more fixes and will cur a new release tonight or tomorrow. In the interim you can just use what you have, you'll be upgraded automatically.
