### ISSUE TITLE
Getting @string definitions from external file

### ISSUE THREAD

**Issue by argenos** [retorquere/zotero-better-bibtex#1731]
**Your question/suggestion:**

I love the ability to define `@strings` to format references consistently, however, I tend to maintain those strings as an external `bib` file under git. The ability to use an external file instead of pasting them in the settings every time I make an update would make for a great QOL improvement.

**Comment by retorquere** [comment]
Do you think people generally have only one of these? Or multiple, one per-project eg?

**Comment by argenos** [comment]
Good question! I do only keep a single file with all the journal/conference definitions and re-use it everywhere by including both bibs `\bibliography{definitions,zotero}`. 

I guess my workflow is geared towards using the `@string` as part of my export workflow than importing bib files into Zotero, roughly: 

1. Add a new item (usually dragging PDFs or by adding the DOI) 
2. Edit the conference/journal to match that string 
3. If it's a new journal/conference, add the string to the `@string` definitions bib file
4. Copy it to de Advanced tab in the preferences

Since I have exported my library & collections with the "keep updated" option on, I add both the `@string` definitions bib file and the exported one to use with LaTeX, e.g. `\bibliography{definitions,zotero}`. 

And thank you very much for this plugin! I appreciate all the hard work you've done to make Zotero useful!

**Comment by retorquere** [comment]
I think I have a solution that will handle both.

**Comment by argenos** [comment]
Oh, I just realized the bot added a new label. Do you need more information from my side?

**Comment by retorquere** [comment]
No, sorry. I have a solution, sorry for the long radio silence, but I've been swamped. I can likely get to it next week.

**Comment by argenos** [comment]
Absolutely no rush! Thanks for taking the time to look at this!

**Comment by argenos** [comment]
I installed the test build suggested by the bot, but found no UI differences on the preferences. Do you have a few pointers on what the workflow would look like or what menu/setting to snoop around? 
Cheers, and once again thanks!

**Comment by retorquere** [comment]
Sorry about that; there's only a [hidden preference](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#stringsoverride) for this.

**Comment by argenos** [comment]
I don’t know why I didn’t think to search there. That looks perfect, I’ll give it a try and report back!

**Comment by retorquere** [comment]
Don't blame yourself for this - I should absolutely have given instructions. *Certainly* for hidden preferences.
