### ISSUE TITLE
Support Rebiber to auto fix bib entries from arxiv.

### ISSUE THREAD

**Issue by lkhphuc** [retorquere/zotero-better-bibtex#1732]
Hi,
I just recently found out about [Rebiber](https://github.com/yuchenlin/rebiber), a neat tool to automatically fix the bib entries obtained from arxiv pages.

In order to use Rebiber with my current workflow, first I have to enable BBT autoexport, then manually run Rebiber python command on the exported bib file, before git commit to my Overleaf repo.

One way to automate that is setup a pre-commit hook on the git repo, but I was wondering if this is something that can be done inside BBT as an option or advanced script, since I think this feature is quite useful in general.

Best regards.

**Comment by retorquere** [comment]
Can you get me a debug log (right-click, bbt menu, send debug log) for an item you think would benefit from being passed through rebiber? And does rebiber target bibtex or biblatex?

**Comment by lkhphuc** [comment]
The report id is: `ZKYCG8ST-euc`

> And does rebiber target bibtex or biblatex?` 

I'm not sure to be honest, but in their python program they used a package called `bibtexparser`.

**Comment by retorquere** [comment]
That's the parser they use, but the fixes the make after having parsed the bibtex will be targeted towards either bibtex or biblatex.

Which fixes do they apply that you are interested in?

**Comment by lkhphuc** [comment]
Thank for quick response. I would prefer biblatex if possible.

**Comment by retorquere** [comment]
Ok, but what does rebiber actually *do* for you? Like a concrete example of something that it fixes for you on a specific bib entry.

**Comment by retorquere** [comment]
I really need more info to be able to help you.

**Comment by retorquere** [comment]
If you do not respond I will have to close the issue.

**Comment by lkhphuc** [comment]
Sorry for the hassle.

**Comment by retorquere** [comment]
It was no hassle -- I just don't know what I have to do, as you've only talked about the solution (rebiber) but not about the problem.
