### ISSUE TITLE
Enhancement for NASA ADS exports

### ISSUE THREAD

**Issue by HNLala** [retorquere/zotero-better-bibtex#1733]
**Debug ID** 
G3D4N9ZA-euc

I am trying to export citations created off NASA ADS commonly used by astronomers. For e.g., see
https://ui.adsabs.harvard.edu/abs/2004A%26A...424..927C/exportcitation.  I have included this citation format in the expected behavior. 

The BBT-generated citation key is quite handy and is one of the main reasons I am using BBT. However, I'd like to retain a few of the original fields as they are. In particular, instead of exporting url as 'url', exporting it as 'adsurl'. Additionally, I would like to keep the fields archivePrefix,  eprint, primaryClass.
Is there an option already present which will allow me to do that? Or will it be possible for you to implement such a feature? 

Many astronomical journals link both the DOI (to the official published version of the article) and the url (linked to ADS). However, the latter is recognized only if it is named 'adsurl' and not 'url'. 

Thanks a lot for this immensely helpful tool.

**Desired behavior:**
```
@ARTICLE{2004A&A...424..927C,
       author = {{Caputo}, F. and {Castellani}, V. and {Degl'Innocenti}, S. and {Fiorentino}, G. and {Marconi}, M.},
        title = "{Bright metal-poor variables: Why ``Anomalous'' Cepheids?}",
      journal = {\aap},
     keywords = {stars: variables: Cepheids, stars: evolution, Astrophysics},
         year = 2004,
        month = sep,
       volume = {424},
        pages = {927-934},
          doi = {10.1051/0004-6361:20040307},
archivePrefix = {arXiv},
       eprint = {astro-ph/0405395},
 primaryClass = {astro-ph},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2004A&A...424..927C},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

**Actual behavior:**
```
@article{caputo2004_BrightMetalpoorVariables,
  title = {Bright Metal-Poor Variables: {{Why}} ``{{Anomalous}}'' {{Cepheids}}?},
  shorttitle = {Bright Metal-Poor Variables},
  author = {Caputo, F. and Castellani, V. and Degl'Innocenti, S. and Fiorentino, G. and Marconi, M.},
  year = {2004},
  month = sep,
  volume = {424},
  pages = {927--934},
  issn = {0004-6361},
  doi = {10.1051/0004-6361:20040307},
  url = {http://adsabs.harvard.edu/abs/2004A%26A...424..927C},
  urldate = {2021-02-01},
  journal = {Astronomy and Astrophysics}
}
```

**Comment by retorquere** [comment]
debug log. please.

**Comment by retorquere** [comment]
The `adsurl` can be handled with a postscript:

```
if (Translator.BetterTeX && reference.has.url && reference.has.url.value.includes('adsabs.harvard.edu')) {
  reference.has.url.name = 'adsurl'
}
```

WRT the `arXiv` stuff, `G3D4N9ZA-euc` doesn't have that info, so I can't "keep" what's not in your database. But if you import that sample above, BBT will put the following in the extra field:

```
arXiv: astro-ph/0405395 [astro-ph]
tex.adsnote: Provided by the SAO/NASA Astrophysics Data System
tex.adsurl: https://ui.adsabs.harvard.edu/abs/2004A&A...424..927C
```

and those will be exported back out to their respective biblatex fields on re-export. You don't have to re-import of course, you can just add these lines to the `extra` field yourself.

If you want to import the `\aap` command in a way that it will be re-exported, you can test with build 338 above; you'll have to set the [hidden preference](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/) `importUnknownTexCommand` to `tex` before import. I may make this an exposed setting, but I've added it just now.

**Comment by HNLala** [comment]
**Debug Log**
WYLFJJ9R-euc

Thank you for the detailed reply, I have followed what you recommended. However, I noticed a difference in how the exports work based on how I was importing the reference. Maybe I should report it to Zotero devs. Anyway, details are:

**Case A**:
If I use the Zotero connector and save the reference using the Firefox addon on this page (https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/abstract), BBT exports the following citation:
```

@article{ji2020_SouthernStellarStream,
  title = {The {{Southern Stellar Stream Spectroscopic Survey}} ({{S5}}): {{Chemical Abundances}} of {{Seven Stellar Streams}}},
  shorttitle = {The {{Southern Stellar Stream Spectroscopic Survey}} ({{S5}})},
  author = {Ji, Alexander P. and Li, Ting S. and Hansen, Terese T. and Casey, Andrew R. and Koposov, Sergey E. and Pace, Andrew B. and Mackey, Dougal and Lewis, Geraint F. and Simpson, Jeffrey D. and {Bland-Hawthorn}, Joss and Cullinane, Lara R. and Da Costa, Gary. S. and Hattori, Kohei and Martell, Sarah L. and Kuehn, Kyler and Erkal, Denis and Shipp, Nora and Wan, Zhen and Zucker, Daniel B.},
  year = {2020},
  month = oct,
  volume = {160},
  pages = {181},
  issn = {0004-6256},
  doi = {10.3847/1538-3881/abacb6},
  url = {http://adsabs.harvard.edu/abs/2020AJ....160..181J},
  urldate = {2021-02-03},
  journal = {The Astronomical Journal}
}
```
On the other hand, if I copy the citation from the clipboard in the format described here:
**Case B:**
```
@ARTICLE{2020AJ....160..181J,
       author = {{Ji}, Alexander P. and {Li}, Ting S. and {Hansen}, Terese T. and {Casey}, Andrew R. and {Koposov}, Sergey E. and {Pace}, Andrew B. and {Mackey}, Dougal and {Lewis}, Geraint F. and {Simpson}, Jeffrey D. and {Bland-Hawthorn}, Joss and {Cullinane}, Lara R. and {Da Costa}, Gary. S. and {Hattori}, Kohei and {Martell}, Sarah L. and {Kuehn}, Kyler and {Erkal}, Denis and {Shipp}, Nora and {Wan}, Zhen and {Zucker}, Daniel B.},
        title = "{The Southern Stellar Stream Spectroscopic Survey (S$^{5}$): Chemical Abundances of Seven Stellar Streams}",
      journal = {\aj},
     keywords = {Globular star clusters, Stellar abundances, Dwarf galaxies, Milky Way stellar halo, 656, 1577, 416, 1060, Astrophysics - Solar and Stellar Astrophysics, Astrophysics - Astrophysics of Galaxies},
         year = 2020,
        month = oct,
       volume = {160},
       number = {4},
          eid = {181},
        pages = {181},
          doi = {10.3847/1538-3881/abacb6},
archivePrefix = {arXiv},
       eprint = {2008.07568},
 primaryClass = {astro-ph.SR},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

This format is copied to the clipboard from:
https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/exportcitation

In this case, BBT pins the incoming citekey automatically (which might be something you can help me with) but the rest of the keywords are transferred as expected. Even the unknown tex command of the journal abbrev. works well now. The BBT export is:

```
@article{2020AJ....160..181J,
  title = {The Southern Stellar Stream Spectroscopic Survey (S{$^5$}): {{Chemical}} Abundances of Seven Stellar Streams},
  author = {Ji, Alexander P. and Li, Ting S. and Hansen, Terese T. and Casey, Andrew R. and Koposov, Sergey E. and Pace, Andrew B. and Mackey, Dougal and Lewis, Geraint F. and Simpson, Jeffrey D. and {Bland-Hawthorn}, Joss and Cullinane, Lara R. and Da Costa, Gary. S. and Hattori, Kohei and Martell, Sarah L. and Kuehn, Kyler and Erkal, Denis and Shipp, Nora and Wan, Zhen and Zucker, Daniel B.},
  year = {2020},
  month = oct,
  volume = {160},
  pages = {181},
  doi = {10.3847/1538-3881/abacb6},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System},
  adsurl = {https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J},
  archivePrefix = {arXiv},
  eid = {181},
  eprint = {2008.07568},
  eprinttype = {arxiv},
  journal = {\aj},
  number = {4},
  primaryClass = {astro-ph.SR}
}
```

I understand if this might be too idealistic, but what I hope can be possible is:
1. I use the Zotero Connector on the page: https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/abstract and it creates a new entry for this reference and attaches the related PDF.
2. It recovers all the fields listed here (in the 'Export Citation' section, that is): https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/exportcitation
3. BBT generates its own citekey
4. The exported citation looks like this:

```
@article{ji2020_SouthernStellarStream,
  title = {The Southern Stellar Stream Spectroscopic Survey (S{$^5$}): {{Chemical}} Abundances of Seven Stellar Streams},
  author = {Ji, Alexander P. and Li, Ting S. and Hansen, Terese T. and Casey, Andrew R. and Koposov, Sergey E. and Pace, Andrew B. and Mackey, Dougal and Lewis, Geraint F. and Simpson, Jeffrey D. and {Bland-Hawthorn}, Joss and Cullinane, Lara R. and Da Costa, Gary. S. and Hattori, Kohei and Martell, Sarah L. and Kuehn, Kyler and Erkal, Denis and Shipp, Nora and Wan, Zhen and Zucker, Daniel B.},
  year = {2020},
  month = oct,
  volume = {160},
  pages = {181},
  doi = {10.3847/1538-3881/abacb6},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System},
  adsurl = {https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J},
  archivePrefix = {arXiv},
  eid = {181},
  eprint = {2008.07568},
  eprinttype = {arxiv},
  journal = {\aj},
  number = {4},
  primaryClass = {astro-ph.SR}
}
```

In the desired format, every field except the citekey is identical to the incoming citation. Instead of importing the fields in its usual way, it will be great if Zotero lifts these fields verbatim from the 'Export Citation' section.

**Comment by retorquere** [comment]
> Even the unknown tex command of the journal abbrev. works well now.

It's also possible to have these expanded into their full names BTW; in the advanced BBT prefs, there's an `@strings` field where you can add something like

```
@preamble{
\newcommand{\aj}{Full Journal Name}
}
```

this mechanism is pretty primitive; only simple commands without parameters can be defined this way.

> * I use the Zotero Connector on the page: https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/abstract and it creates a new entry for this reference and attaches the related PDF.
> 
> * It recovers all the fields listed here (in the 'Export Citation' section, that is): https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/exportcitation

Zotero doesn't notify other parts of the code that a scrape is ongoing; the new item just appears in the database. For this to work, I'd have to patch the scraping process, detect that this specific site is being scraped, download the bibtex, etc... essentially duplicating Zotero's scrape facility, with site-specific scraping code on top of this to make it work. That is not something I want to take on.

> * BBT generates its own citekey

You can disable citekey import: https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#importcitationkey
 
> In the desired format, every field except the citekey is identical to the incoming citation. Instead of importing the fields in its usual way, it will be great if Zotero lifts these fields verbatim from the 'Export Citation' section.

I know that Zotero has a priority order for their scrapers when multiple formats are available -- if this is also the case for the ADS site, you may be able to give bibtex import precedence either automatically or manually. I haven't used this in many years, but I can't imagine this would have been removed. You'd have to ask about this on the Zotero forums, they'll know better.

**Comment by retorquere** [comment]
Does this address the problem you have?

**Comment by retorquere** [comment]
I'm going to assume your problem has been addressed.

**Comment by HNLala** [comment]
Sorry for the delay. Your solutions worked to a T. Thanks.

**Comment by retorquere** [comment]
Super, thanks for the confirmation. I'll close the issue when I've merged it into a release, I keep these open a a reminder to do so.
