### ISSUE TITLE
Separate key commands for copying citations and bibtex entries using the clipboard or drag/drop

### ISSUE THREAD

**Issue by mo-seph** [retorquere/zotero-better-bibtex#1735]
This may be a feature request, or a failure to understand Zotero correctly.

There are two things I routinely do with entries in Zotero - drag a citation into a latex document, and copy the bibtex into a .bib file.

As far as I can tell, the only mechanism for doing this is Shift+Drag, or Shift+Cmd+C (on a Mac). This means that I have to go to Zotero preferences and change the Quick Copy Default Format between "Better BibTeX Citation Key Quick Copy" and "Better BibTex" for the two operations.

Is there any way to set up a different key command or mouse gesture for the two actions?

**Comment by retorquere** [comment]
I don't think that option exists, but you'd have to ask the Zotero crew on the forums. The quick-copy facility is something that Zotero provides, BBT is just one of the producers in it.
