### ISSUE TITLE
Export fails for duplicate "extra" field

### ISSUE THREAD

**Issue by rddunphy** [retorquere/zotero-better-bibtex#1739]
I have (at least) one item in my library that causes the BBT exporter to fail - most items export without issue. (There's nothing obvious about the item jumping out at me, although it does contain a few special characters.) Exporting e.g. using Zotero RDF works fine.

**Report ID:** ZMABXAF7-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** Should generate the .bib file.

**Actual behavior:** Fails with the following alert: "An error occurred while trying to export the selected file."

I'm on Zotero version 5.0.95 and BBT version 5.2.113 (but I noticed the behaviour before updating BBT just now). Thanks for your help!

**Comment by retorquere** [comment]
Can you try build 377?

**Comment by rddunphy** [comment]
That works great, thanks!

**Comment by retorquere** [comment]
Super, thanks for the confirmation (and the report).
