### ISSUE TITLE
Dave Smith's zotpick for Scrivener delivers cite keys in all caps

### ISSUE THREAD

**Issue by blankens10** [retorquere/zotero-better-bibtex#1740]
Help!
All the components are up to date. The cite keys in Zotero are in the correct format, and when I quick copy from zotero the key is in the correct format. But when i use cmd-y from within Scrivener it's in all caps.  I have no idea what to do about this.

**Report ID: 9DK5SEW8-euc

**Expected behavior: Deliver a cite key in my designated format: [auth:lower][shorttitle3_3][year] e.g.  @adamsAspectsMusicText2008

**Actual behavior: Instead, it delivers @ADAMSASPECTSMUSICTEXT2008.

**Comment by retorquere** [comment]
If you paste it in anything else, what do you get?

**Comment by blankens10** [comment]
Ok, so specifically:
If I use shift-cmd-C in Zotero, and paste it anywhere, it works fine (e.g. @adamsAspectsMusicText2008)
It's only when I use the Zotpicker app for Scrivener, from within Scrivener or if I activate it directly in the applications folder, it inserts an all caps version, (e.g. @ADAMSASPECTSMUSICTEXT2008)
Thats it. It was working fine yesterday, and as far as I know, I didn't change anything except keeping everything up to date.

**Comment by retorquere** [comment]
Can you modify the applescript to paste in something else than scrivener so we can test whether it's scrivener, or something else that interferes with the paste? Zotpick cannot request anything uppercased (bbt doesn't have a picker format that uppercases) and to my knowledge, zotpick doesn't do anything except request-and-paste. So I don't know what's happening on your system but I don't see any way this can be caused by BBT or zotpick. A test-paste in another app like textedit may tell us more.

**Comment by retorquere** [comment]
I can see in `9DK5SEW8-euc` that zotpick requests `pandoc` format and gets `@adamsAspectsMusicText2008`. Whatever happens beyond that point is beyond BBTs control. Something must be interfering with the paste -- I know that a recent macos update brought with it an absolutely infuriating "replace consecutive spaces with `.<space>` while typing" which drove me bonkers for a week before I found out.

**Comment by blankens10** [comment]
Well, I did the textedit thing, and submitted the log as QHK4AUT3-euc
It did the same thing, pasted in all caps. not sure if this will help or not. 
I did install the most recent mojave security update recently, so maybe that's it. 
Anyway, it's not the end of the world if I can't make it work, quick copy isn't that inconvenient

**Comment by retorquere** [comment]
That log shows again that the key is delivered to zotpick as expected, not capitalized. There's nothing I can do here, unfortunately. The problem exists beyond the point where BBT has influence.

**Comment by blankens10** [comment]
¯\_(ツ)_/¯  Well, thanks anyway for such a prompt and thorough response. And thanks for BBT, super helpful.
