### ISSUE TITLE
TeXstudio not found by Zotero Citation Picker

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1743]
**Report ID:**
YFFHTNUW-euc

**Context:**
- Windows 10 (tested in a VM from Linux Mageia 7)
- Zotero 5.0.95.1
- BBT 5.2.117

**Expected behavior:**
TeXstudio should be found by Zotero Citation Picker
**Actual behavior:**
TeXstudio is not be found by Zotero Citation Picker:

>TeXstudio not found

**Guess:**
It is related to the fact TeXstudio is not in the Windows' system path and its own one seems:

- to have formerly been `C:\Program Files (x86)\texstudio`,
- to now be `C:\Program Files\texstudio`.

**Comment by dbitouze** [comment]
According to https://github.com/texstudio-org/texstudio/issues/1475, the path to TeXstudio on Windows now is `C:\Program Files\texstudio`.

**Comment by retorquere** [comment]
450 should find texstudio for you.

**Comment by dbitouze** [comment]
> 450 should find texstudio for you.

Indeed: thanks!
