### ISSUE TITLE
How to use the last word of the title?

### ISSUE THREAD

**Issue by Ypot** [retorquere/zotero-better-bibtex#1746]
Hi!

I use the Title in the Key, but it should finish always with the last word of the title. Is it possible?
Example:

Book: 
- Author: Sanz Aparicio
- Title: Fundamentos teóricos y prácticos de la motivación
- Year: 2019
 
Generated Key:
 _SanzAparicio.2019.FundamentosTeoricosPracticos_

Desired Key: 
_SanzAparicio.2019.FundamentosTeoricosMotivacion_

**Comment by retorquere** [comment]
It's just a few clicks. A debug report. Please.

**Comment by Ypot** [comment]
Report-ID: 6N9YYWRV-euc

**Comment by retorquere** [comment]
Currently not possible, but I'm working on a change to allow it.
