### ISSUE TITLE
Enabling BBT leads to lagging when entering item info (with auto-export and workers off)

### ISSUE THREAD

**Issue by johannesdue** [retorquere/zotero-better-bibtex#1748]
**Report ID:**
QX8Y9P59-euc

**Expected behavior:**
Entering item info in Zotero works smoothly when BBT is enabled

**Actual behavior:**
Entering item info in Zotero leads to repeated lags of 3-4 seconds when typing and moving between fields when BBT is enabled. This behavior ceases when BBT is disabled.

**Comment by retorquere** [comment]
Is 425 better? I had a lot of logging that was always on from a previous debugging session.

**Comment by johannesdue** [comment]
Tried running 425, doesn't seem to make any difference.

**Comment by retorquere** [comment]
Can you get me a new debug log (with Zotero debug logging on) from build 427?

**Comment by johannesdue** [comment]
Sure, here it is: J89I8F3K-euc

**Comment by retorquere** [comment]
Are you performing item merges often?

**Comment by johannesdue** [comment]
No, not often at all.

fre. 26. feb. 2021, 14:04 skrev Emiliano Heyns <notifications@github.com>:

**Comment by retorquere** [comment]
Can you go into the [hidden preferences](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/), search for `extraMerge` (you will find `extraMergeTeX`, `extraMergeCSL` and `extraMergeCitekeys`), set them all to `false`, and see if that makes the difference?

**Comment by johannesdue** [comment]
It still lags after setting those to false. A second after changing fields
with Tab, the lag occurs.

fre. 26. feb. 2021 kl. 15:59 skrev Emiliano Heyns <notifications@github.com

**Comment by retorquere** [comment]
Can you get me a new log with all those 3 off? I see merges in `J89I8F3K-euc` and they seem to be taking a lot of time, and I want to make sure these are not sitill the cause.

**Comment by retorquere** [comment]
BTW you have an auto-export set up that consistently fails because a folder in the target path is missing. How many items do you have in your library BTW?

**Comment by johannesdue** [comment]
I fixed the auto-export target issue, but the problem persisted. But then I set auto-export to "idle" instead of "on change". That did the trick. I logged these operations here (first "on change" with lags, then with "idle" without lags): DTHCJMPW-euc.

**Comment by retorquere** [comment]
When you look at the auto-export in the preferences, what percentage does it say is cached?

You have background exports off, caching is going to help, but foreground exports are always going to be more laggy than background exports.

**Comment by retorquere** [comment]
You can also keep it on immediate, but set a longer `autoExportDelay` in the hidden preferences. It is currently set at 1 (meaning 1 second). If you set it at eg 10, auto-exports won't kick in until 10 seconds after the last item change. But unless background exports are giving you errors, you really want it on (which it should be by default).

**Comment by johannesdue** [comment]
Cache is 100%. I tried enabling background export by sliding parallel background export all the way right, this did not help. Made it worse, I think.

**Comment by retorquere** [comment]
Can you set it at 1 and generate a new debug log from 429? Setting it higher shouldn't really make a difference in your case, as you only have one auto-export set up as far as I can tell.

**Comment by johannesdue** [comment]
Ok, here's autoexportdelay at 1, autoexport on change, and background export disabled: 59VGTPSL-euc

**Comment by johannesdue** [comment]
(setting autoexportdelay to 10 did fix the issue though)

**Comment by retorquere** [comment]
According to your logs, workers are still at 0.

**Comment by retorquere** [comment]
With workers at 0 the current behavior is expected -- exporting the 2.5k items takes 4 seconds and Zotero will freeze during that time, as Zotero itself does not support async or background exports. Async exports are rumored to come at some point and that should help a little, but this behavior is just what Zotero does during exports of any kind, not specifically BBT. But BBTs exports are relatively slow, so it's more noticeable. Hence the background exports, which happen on a fully isolated thread (for the most part).

**Comment by retorquere** [comment]
I'd be really interested in getting a log with workers set at 1. With workers at 0, the lag really cannot be helped. Zotero really does not allow exporters to run without freezing Zotero (try doing any large export with any non-BBT format -- Zotero will freeze while it's running), and auto-exports do just that. With some hackery I managed to split off the brunt of the work to a separate thread (worker), so that should give the best experience. If that still lags, that means the prep for the worker must be taking long, and I'd be interested in finding out why that is so.

**Comment by johannesdue** [comment]
Ok, I logged some operations to `9SGRPJHK-euc` with workers set at 1 and autoexport on change. There's less of a lag now, maybe 0.5s instead of 3-4s.

**Comment by retorquere** [comment]
Can you get me a new log with 458?

**Comment by johannesdue** [comment]
Here you go: `4INIU9QB-euc`

**Comment by retorquere** [comment]
Can you install 463, set the hidden pref `workersCache` to `false`, and get me a new log?

**Comment by retorquere** [comment]
In about 10 minutes a build will drop that has a preference in the UI to turn of the worker cache. This should make the lag less, at the cost of the exports (in the background, where they can't bother Zotero) taking longer.
