### ISSUE TITLE
Feature request: quick way to copy either the cite command or the full BibTex entry.

### ISSUE THREAD

**Issue by tobiasBora** [retorquere/zotero-better-bibtex#1750]
Hello,

First, thanks a lot for this great extension. I've very new to Zotero, so sorry if I'm asking for something trivial to do. I just have one issue with Better Bibtex: I can't find a quick way to switch between copying the short entry `\cite{XXX}` or the full BibTex citation.

Indeed, I can't really use the "auto export" feature to create my citation file because the .bib file I want to populate is an old file created by someone else that we share and I don't want to change it significantly. I just would like to be able to copy/paste a few BibTex entries to add to our current project. Usually, I use the short key mechanism, so every time I want to copy the full Bibtex entry, I need to change the settings via "Edition > Preferences > Exportation > Better BibTex ", and when the copy is done, I need to do it again to revert back to the short Citation Key mechanism.

Would it be possible to add an entry in the right-click menu to be able to choose which style I want to copy? And maybe assign different keyboards shortcuts?

Thanks!

**Comment by qqobb** [comment]
You can get additional keyboard shortcuts and item context menu options for Zotero's Quick Copy with the [Zutilo add-on](https://github.com/wshanks/Zutilo#zutilo).

Zutilo's "QuickCopy items" function is explained in its [command reference](https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md#item-menu-functions).

**Comment by retorquere** [comment]
@qqobb already answered the quick-cite question better than I probably would have; remains this:

> Indeed, I can't really use the "auto export" feature to create my citation file because the .bib file I want to populate is an old file created by someone else that we share and I don't want to change it significantly.

I'm not sure how auto-export figures into this.

**Comment by tobiasBora** [comment]
Great, thanks a lot for the tip. I wanted to avoid to use Zutilo because I got some troubles with it (drag&drop of tags were not usable anymore), but I'll try again and fill an issue in Zutilo if the problem continues to occur.

Concerning the auto-export, it is just that I was thinking of automatically appending the citations in a file if the citation were not already present: this would make sure that I don't need to manually copy the items I need. Do you know if it exists? If not do you think it make sense to include it in zotero or better bibtex?

**Comment by retorquere** [comment]
> Concerning the auto-export, it is just that I was thinking of automatically appending the citations in a file if the citation were not already present: this would make sure that I don't need to manually copy the items I need. Do you know if it exists? 

This sounds to me like a very different issue from the quick-copy question. Are there two separate questions here? But even if this is a separate question I still don't understand what you are describing. When the source of an autoexport changes (the collection/library), the source is exported in full, overwriting the existing file. Why would you want to factor in whether the entry does or does not exist in the bib file? On export, they will all be replaced anyhow. What is the use-case you have in mind?

**Comment by tobiasBora** [comment]
It is indeed a different issue, just vaguely related as this feature would avoid the need to copy Bib entries into my `.bib` file since it would be automatically merged. Anyway, for clarification I just created a more detailed issue here https://github.com/retorquere/zotero-better-bibtex/issues/1755, we can close this one thanks!

**Comment by retorquere** [comment]
Why not just use multiple bibliography statements in the source document?

**Comment by tobiasBora** [comment]
The main issue of multiple bibliography statements is that if my co-authors update an entry in the file generated by Zotero (say I included the arxiv version and my co-author puts instead the journal version), it will remove its content. Also, I'm not sure how duplicated entries are managed by BibTex in that case.
