### ISSUE TITLE
"Fields to omit from export" is not working

### ISSUE THREAD

**Issue by SunHaozhe** [retorquere/zotero-better-bibtex#1751]
**Report ID:** R2KWF8K2-euc 

**Exporter used:** Copy as BibTex (using keyboard shortcut `Shift+cmd+C`, Quick Copy)

**Expected behavior:** The exported bibtex (in clipboard) should not contain `annote` fields, because I have put `annote` in `Zotero -> Preferences -> Better BibTex -> Export -> Fields to omit from export (comma-separated)`

**Actual behavior:** The exported bibtex still contains `annote` fields as if I did not ask Zotero (with Better BibTex) to omit them.

I saw that this issue have been reported before, for example #729 . However, reading that does not solve my problem. I have tried to click on the `Reset cache` button under  `Zotero -> Preferences -> Better BibTex -> Advanced -> Export -> Reset cache`, however this did not solve my problem either. I also tried to restart Zotero. 

Could you please help me?

**Comment by retorquere** [comment]
Your quick-copy translator is set to `BibTeX`, not `Better BibTeX`, so BBT is not being called. You are getting the Zotero BibTeX export, which doesn't know about "omit fields".

**Comment by SunHaozhe** [comment]
Could you please tell me how I could switch from BibTeX to Better BibTeX? I did not see such thing in the documentation.

**Comment by SunHaozhe** [comment]
Hi, thanks a lot for your help. For those who encountered the same issue, see `Zotero -> Preferences -> Export -> Default Format`, select `Better BibTeX` instead of `BibTeX`

**Comment by retorquere** [comment]
Same place where you must have set the quick copy translator before - Preferences - export - default format
