### ISSUE TITLE
No citation key for pdf file

### ISSUE THREAD

**Issue by Benoit-prof** [retorquere/zotero-better-bibtex#1753]
Hello,

I use zotero (5.0.96) with zotero connector for chrome (5.0.82) and better bibtex (5.2.124). All is perfectly fine except for pdf file that i want to add to my bibliography.
I explain
For example at this url there is a pdf file : [http://www.cnesco.fr/wp-content/uploads/2021/03/Cnesco_CCI_formation_continue_Preconisations_210226.pdf](http://www.cnesco.fr/wp-content/uploads/2021/03/Cnesco_CCI_formation_continue_Preconisations_210226.pdf)
i can add it to zotero, it is recognized like a pdf. The problem is that i do not have any citation key generated for it by better bibtex.
Is it normal ? How can i fix it ? Is there a way to add manually a citation key ?
Any help would be appreciated.

**Comment by retorquere** [comment]
If you right-click the pdf and select "create parent item", you can create a parent item that will have a citekey. Attachments on their own cannot have citation keys, as the bibliography style would not have enough information to render a bibliography from just a filename.

**Comment by Benoit-prof** [comment]
Hello,
@retorquere : thanks for your answer. I thought it was something like this. I did what you have suggested and i got m precious citation key.
Regards, Benoît.
