### ISSUE TITLE
Initializing stuck on 'Starting key manager'

### ISSUE THREAD

**Issue by LouiseMcRae** [retorquere/zotero-better-bibtex#1754]
Hello, I was wondering if I could get some help with this issue, please:

**Report ID:** 8Z83PFEA-euc

**Expected behavior:** Citekeys are generated once Better BibTex has initiated

**Actual behavior:** Citekeys are not generated and initialization is not completed. The initialization notifcation window remains open stating 'Starting key manager' and hourglass icons are visible in the Citekey field. 

I tried looking at closed issues related to this and turned the automaticScraperUpdates off, but this didn't help. I have removed the add on and then added it again.

**Comment by retorquere** [comment]
Can you get me a debug log from build 500, but checking the "send cache" checkbox?

**Comment by retorquere** [comment]
oh wait, I might have enough from 8Z83PFEA-euc

**Comment by retorquere** [comment]
Right, can you get me a debug log from build 501, making sure to check the "send cache" checkbox.

**Comment by LouiseMcRae** [comment]
Thank you. I've just submitted the debug log from build 501 **Report ID**: GZLNDIVB-euc

**Comment by retorquere** [comment]
Can you go into the Zotero preferences and:

* Select the "Advanced" pane
* Click the button "config editor"
* Click "Yes, I accept the risk"
* Search for `scrubDatabase`
* Double-click it to toggle it to `true`
* Close the preferences windows that came up
* Close Zotero (File->Quit I think on Windows)
* Restart Zotero

That should fix it. This version has a few other performance fixes that weren't yet in 5.2.124, you can just keep this as I've also just scheduled a release of 5.2.126, and you will be upgraded automatically.

**Comment by LouiseMcRae** [comment]
Yes, that has fixed it. Thank you for a speedy fix, very helpful!
