### ISSUE TITLE
Use relative paths for `file = {...}` field of `.bib` export.

### ISSUE THREAD

**Issue by goretkin** [retorquere/zotero-better-bibtex#1756]
Sorry if this is the wrong place, since I report ID is not applicable.

The difference is in the `file = ` field.

This is related, but not exactly equivalent, to Zotero's
`user_pref("extensions.zotero.baseAttachmentPath", "$base_path")`
setting.

**Exporter used:**
Better BibLaTeX auto exporter ("keep updated")

**Desired behavior:**
```
@inproceedings{bohlin2000path,
  title = {Path Planning Using Lazy {{PRM}}},
  booktitle = {Proceedings 2000 {{ICRA}}. {{Millennium}} Conference. {{IEEE}} International Conference on Robotics and Automation. {{Symposia}} Proceedings (Cat. {{No}}.{{00CH37065}})},
  author = {Bohlin, R. and Kavraki, L. E.},
  date = {2000-04},
  volume = {1},
  pages = {521-528 vol.1},
  issn = {1050-4729},
  doi = {10.1109/ROBOT.2000.844107},
  file = {thesis/literature/zotero/data/storage/WW8FF8QM/Bohlin and Kavraki - 2000 - Path planning using lazy PRM.pdf},
  organization = {{IEEE}}
}
```

**Actual behavior:**
```
@inproceedings{bohlin2000path,
  title = {Path Planning Using Lazy {{PRM}}},
  booktitle = {Proceedings 2000 {{ICRA}}. {{Millennium}} Conference. {{IEEE}} International Conference on Robotics and Automation. {{Symposia}} Proceedings (Cat. {{No}}.{{00CH37065}})},
  author = {Bohlin, R. and Kavraki, L. E.},
  date = {2000-04},
  volume = {1},
  pages = {521-528 vol.1},
  issn = {1050-4729},
  doi = {10.1109/ROBOT.2000.844107},
  file = {/Users/goretkin/projects/thesis/literature/zotero/data/storage/WW8FF8QM/Bohlin and Kavraki - 2000 - Path planning using lazy PRM.pdf},
  organization = {{IEEE}}
}
```

**Comment by goretkin** [comment]
BTMK7BEX-euc

**Comment by retorquere** [comment]
You can turn on [this](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#relativefilepaths) at the cost of losing caching.

**Comment by retorquere** [comment]
(the debug ID also gives me a copy of your BBT settings, versions of zotero and plugins, etc, so even if I don't need the log, this gives me a better sense of what context BBT works in)

**Comment by goretkin** [comment]
Oh, I didn't notice that option. Thanks so much!

On the topic of caches, I am experimenting with keeping my zotero data directory versioned under git (using [this](https://ongardie.net/blog/sqlite-in-git/) to get some meaningful-ish diffs for the sqlite databases, though it's still pretty inscrutable). I ignored the files in `$datadir/better-bibtex/cache.*` because they were changing often, appearing and reappearing, etc. Do you have any opinion on this, or generally, how to maintain version history?

**Comment by retorquere** [comment]
You're not really expected to know about the hidden preferences, it's OK to ask here.

There's one sqlite file that may be worth backing up, that holds the citation keys. There's a bunch of json files, those will disappear on start and reappear on shutdown. Those are just caches, I don't see much value in versioning those. They will be automatically rebuilt when missing or corrupted.

**Comment by retorquere** [comment]
Does this address your questions?

**Comment by goretkin** [comment]
Yes, it does. Thank you!
