### ISSUE TITLE
Add option to split titles and subtitles

### ISSUE THREAD

**Issue by bdarcus** [retorquere/zotero-better-bibtex#1759]
Would be nice to have an export option to make use of the biblatex subtitle field.

**Comment by retorquere** [comment]
I really need a debug log as per point 1 in the description by label-gun. I have no idea what is in your library that you want treated this way and I'd rather not guess. This is why I ask for a debug log in the issue template, and why label-gun sends a reminder if you forget.

**Comment by bdarcus** [comment]
I'm sorry; I missed that you use those for this purpose.

Here is it: XLRBLF5E-euc.

So I submitted one example where the delimiter is the very common colon, and another with a question mark.

I think in some languages, a period can also be used.

**Comment by retorquere** [comment]
Eh, that would be a heuristic, and those tend to grow a lot of preferences to steer them around edge cases. You could do this with a fairly simple postscript:

```
if (Translator.BetterBibLaTeX && reference.has.title) {
  const titles = reference.has.title.value.match(/(.+?[?:;])(.*)/)
  if (titles) {
    reference.add({ name: 'title', value: titles[1].trim() })
    reference.add({ name: 'subtitle', value: titles[2].trim() })
  }
}
```

**Comment by bdarcus** [comment]
> Eh, that would be a heuristic, and those tend to grow a lot of preferences to steer them around edge cases. 

Yeah, that's a reasonable point. Why in CSL 1.1 we're making titles full objects (the original proposal was to try to define these heuristics).

> You could do this with a fairly simple postscript:

Thank you; that's all I need then!

I'll close this then.

**Comment by bdarcus** [comment]
While I have you, how can I change the name of an exported field name (from "keywords" to "tags")?

I'm looking at the "scripting" docs, but not seeing an example of that.

**Comment by retorquere** [comment]
The easiest way is to cheat and change the name of the field:

```
if (Translators.BetterBibLaTeX && reference.has.keywords) {
  reference.has.keywords.name = 'tags'
}
```

Removing the `keywords` field and adding the `tags` field would be the "clean" way but this achieves functionally the same.

**Comment by bdarcus** [comment]
Allow me to just add here how much I appreciate the work you do on this project. It's a great resource, and it's just gotten better!

**Comment by retorquere** [comment]
You're very welcome.
