### ISSUE TITLE
Feature request: Add command line interface

### ISSUE THREAD

**Issue by szsdk** [retorquere/zotero-better-bibtex#1760]
A very common scenario I meet is writing a paper on different computers. Then the auto-updating does not work. Each time a new reference added, I need to manually update the bib file. Sure this updating is a very straightforward procedure. But clicking a menu and selecting a path could be very annoying especially when you may add hundreds of references.

Do you guys think it is possible to add some simple CLI to simplify those tedious work?

**Comment by retorquere** [comment]
There's no guys, just me.

I don't fully understand what the workflow you propose would look like. Does the different computer have Zotero installed? How are you adding references, and what are you adding them to on the different computer? What would the command line interface do precisely?

**Comment by szsdk** [comment]
Hi. What I am thinking is something like
```
bbt collection/subcollection --output output.bib
```

Whenever a new reference is added to `collection/subcollection`, I could run that command to update the bib file.

**Comment by retorquere** [comment]
Ah OK, this should work for your case: https://retorque.re/zotero-better-bibtex/exporting/pull/

**Comment by szsdk** [comment]
Yes, you made my day. I hope I could know it earlier. Please feel free to close this issue.

**Comment by retorquere** [comment]
No problem
