### ISSUE TITLE
Zotero/Juris-M not working with Lyz using BetterBibTeX

### ISSUE THREAD

**Issue by maras** [retorquere/zotero-better-bibtex#1761]
Hello

**Report ID:**
BGQIFJJC-euc
**Expected behavior:**
Lyz (Zotero/Juris-M connector to Lyx) can pick up BBT created keys and export bibliography entries from Zotero/Juris-M to bib file using BBT rules and automatically create citation in Lyx. It was working week (or two weeks) ago.
**Actual behavior:**
Now it isn't working. I tried several versions of Zotero (last 5.0.96, beta, v. 5.0.95 and v. 5.0.94), Juris-M (last and beta) – not working. Lyz didn't change very long time.
But Lyz is working after selecting BibLaTeX instead of Better BibLaTeX in its settings of export format and translator. I've created a lot of rules of export and they were working. I changed nothing in BBT during several last months. 

Thank you.

**Comment by retorquere** [comment]
Can you get me a new log from build 529?

**Comment by maras** [comment]
8STIRJIG-euc
Thank you for such fast response!

**Comment by retorquere** [comment]
I see BBT completing an export, but no indication of problems in that log. I've not used lyz before -- how do I set it up to replicate your problem?

**Comment by retorquere** [comment]
And what steps do you take to replicate the problem? Does Lyz have any preferences to set (I can't find anything in the UI).

**Comment by retorquere** [comment]
Ah I've found the settings, but I'd still need to know which steps you took when you found the problem. I've tried a few "cite in lyx" clicks and those worked.

**Comment by retorquere** [comment]
Ah wait, I think I have something.

**Comment by maras** [comment]
I see my comment wouldn't be useful for you :).

I see that error after attempt of inserting citation: `TypeError: A value undefined was yielded that could not be treated as a promise`. I saw that error in debug log.

You can install Lyz to Zotero from there: https://github.com/wshanks/lyz/releases Then select item in Zotero, select "Cite in Lyx" from right menu or from Lyz toolbar. Using it for the first time with Lyx document there will be popup to create new bib file or use old. After creating new bib file user should do the same (select item, "cite in Lyx") once more, but from popup he should select use old, select previously created bib file and after that reference should appear in the Lyx text. 
There should be Better BibLaTeX, not BibLaTeX selected in Lyz settings.

Maybe there were some changes in Zotero, but I installed old versions and all the same. Strangely, that even old version of BBT isn't working (I installed 5.2.121).

**Comment by retorquere** [comment]
For the short term, go into the [hidden preferences](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/) and set `workersMax` to 0, which will disable background exports. It's not something you want to have routinely disabled, but the problem with lyz is related to this. I'll report back here when it is fixed, then we can reset it.

**Comment by retorquere** [comment]
I think I have found the problem -- tests are running.

**Comment by retorquere** [comment]
Can you give build 531 a try? With `workersMax` set to 1 if you had it set to 0.

**Comment by maras** [comment]
Yes, it is working both with Zotero and Juris-M.

Thank you very much for such fantastically quick fix!

**Comment by retorquere** [comment]
Cool, thanks for testing. I've scheduled a new release, but you can just keep this; the new release is just what you have with a new version slapped on. You'll be upgraded to the official releases automatically.
