### ISSUE TITLE
BetterBibTeX is exported to a wrong location if file path contains ampersand

### ISSUE THREAD

**Issue by kachkaev** [retorquere/zotero-better-bibtex#1762]
Looks like one of the recent updates either in Zotero or this extension broke Better BibTeX exports into folders that contain `&` (at least on macOS). Repro steps are provided below.

**Report ID:**

~D692026383~
CQ6EWN7A-euc

**Exporter used:**

_Better BibTeX_

<img width="348" alt="Screenshot 2021-03-14 at 13 13 24" src="https://user-images.githubusercontent.com/608862/111069922-42435780-84c7-11eb-8189-70228bc5fa79.png">

**Expected behavior:**

1.  Check versions: _Zotero 5.0.96.1_,  _Better BibTeX for Zotero 5.2.126_

1.  Create two folders:
     - `~/Desktop/zotero-export-mwe/hello world`
     - `~/Desktop/zotero-export-mwe/hello&world`
     
1. Export _My Library.bib_ twice via _Zotero_ → _Export library..._ → _Better BibTeX_:
     - `~/Desktop/zotero-export-mwe/hello world/My Library.bib`
     - `~/Desktop/zotero-export-mwe/hello&world/My Library.bib`

1. Observe two new files on the disk in the expected locations.

**Actual behavior:**

Paths of two new files are:
- `~/Desktop/zotero-export-mwe/hello world/My Library.bib`
- `~/Desktop/zotero-export-mwe/hello.bib` ⚠️

Looks like `&` (and possibly other special chars) break the output path.

<img width="528" alt="Screenshot 2021-03-14 at 13 23 27" src="https://user-images.githubusercontent.com/608862/111070220-81be7380-84c8-11eb-8a08-8ef09e30680d.png">

I was able to reproduce this behavior on two machines, one with macOS Big Sur and another with macOS Catalina. The bug looks like something pretty new – it was spotted about 7-10 days ago when Zotero stopped auto-updating a bib file in the thesis folder. Interestingly, when the extension is disabled and I export a normal bib, the problem with ampersand does not repeat.

**Comment by kachkaev** [comment]
Sorry, I initially did not get the difference between Zotero reports and extension reports. Got the new report now, hope it is correct:

CQ6EWN7A-euc

<img width="662" alt="Screenshot 2021-03-14 at 13 41 45" src="https://user-images.githubusercontent.com/608862/111070796-36f22b00-84cb-11eb-90b5-dcebe33534c4.png">

**Comment by retorquere** [comment]
I can't find any "hello world" or "hello&world" mentions in the log file. What is the actual path you tried to save to?

**Comment by retorquere** [comment]
Wait, never mind, I see it happening now.

**Comment by retorquere** [comment]
build 527 fixes it

**Comment by retorquere** [comment]
Does 527 work for you?

**Comment by kachkaev** [comment]
Hi @retorquere! Sorry for a slight delay with the response. I just tried test build 5.2.126.527 and it worked 🎉

Many thanks for your quick fix and for maintaining the extension in general! 🙌

I’m going to keep the issue open as I don’t know when exactly you usually close them. However, I consider it resolved for myself 🙂

**Comment by retorquere** [comment]
Thanks for the confirmation, and yes, I like to keep issues open until I've merged them into the main release. Normally I'd do that tonight but GH has an outage, so my release pipeline is down right now.
