### ISSUE TITLE
Integration of new Zotero annotations capabilities

### ISSUE THREAD

**Issue by bepolymathe** [retorquere/zotero-better-bibtex#1763]
Hi @retorquere 
Thanks for this great great tool !
Zotero has launched a [new integrated PDF reader](https://www.zotero.org/support/pdf_reader_preview) that allows very interesting work on tags. It offers the possibility to put tags to highlighted text excerpts. Currently, the export of the bibliography in .bib integrates all the text extracts but not the tags. It would be very useful to be able to retrieve them somehow to integrate them in other uses ([here org-mode](https://github.com/org-roam/org-roam-bibtex/issues/178)). 
Would you be interested in this idea?

**Comment by retorquere** [comment]
Sure, but Zotero would have to provide a way to read those tags; when the page says "they're not yet searchable" that likely means they're not handled as regular tags inside Zotero.

**Comment by bepolymathe** [comment]
Hi @retorquere 

Yes you're right, it's a little early, but it was also to document it and not forget it. It will be possible normally.

![image](https://user-images.githubusercontent.com/29939805/111117833-53907080-8568-11eb-88f3-aa125248d75a.png)

Also, I'm wondering in what type of field of a .bib entry these tags could fit. :thinking:

**Comment by retorquere** [comment]
Please remind me when activity happens on this front. I don't follow all discussions on the Zotero forums, and new features need an advocate to provide input.

**Comment by bepolymathe** [comment]
ok, I will try to follow the news ;-)

**Comment by corstian** [comment]
Slightly related; when running automatic exports these fail with an error "translation failed". Two lines which stand out in the debug log;

```
(3)(+0000012): {better-bibtex true} +214 worker translation failed, error: <Error: Unexpected Zotero Item type "annotation" in chrome://zotero/content/xpcom/utilities.js itemToCSLJSON@chrome://zotero/content/xpcom/utilities.js:1529:13 exportItemsByWorker@chrome://zotero-better-bibtex/content/common.js:63527:48 >
```
and later;
```
(3)(+0000002): {better-bibtex true} +1 auto-export library 1 failed: {"$loki":1,"DOIandURL":"both","asciiBibLaTeX":false,"asciiBibTeX":true,"biblatexExtendedNameFormat":false,"bibtexParticleNoOp":false,"bibtexURL":"off","error":"translation failed","exportNotes":false,"id":1,"meta":{"created":1601883827108,"revision":240,"updated":1616430093103,"version":0},"path":"C:\\Users\\...\\Library.json","recursive":false,"status":"running","translatorID":"f4b52ab0-f878-4556-85a0-c7aeedd09dfc","type":"library","useJournalAbbreviation":false} translation failed 
```

**Comment by retorquere** [comment]
@corstian would you be OK with opening a separate issue for this?

**Comment by corstian** [comment]
@retorquere Done: https://github.com/retorquere/zotero-better-bibtex/issues/1770

**Comment by retorquere** [comment]
I'll be tracking work on this in issue #2126 -- I've requested the change from zotero, no idea when it will happen.
