### ISSUE TITLE
Export in jekyll scholar liquid {% cite key %} syntax?

### ISSUE THREAD

**Issue by sneakers-the-rat** [retorquere/zotero-better-bibtex#1766]
*Please verify **all** of the below before submitting*:

- [x] 1. you have picked the right category for the issue in the previous screen.
- [x (beta)] 2. You are on the latest release of Zotero
- [x] 3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
- [x] 4 you are posting a single question.
- [x] 5. the issue has a subject that succinctly describes the problem or question.
- [x] 6. you are available for follow-up questions and testing.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

**Your question/suggestion:**

Hello!!! Hopefully simple question regarding a v minor feature-- I'd like to extend the plugin to have an export mode where i can click and drag a citation into my text editor, but rather than formatted as a LaTeX `\cite{key1,key2}`, i'd like to export it like `{% cite key1 key2 %}` for use with jekyll scholar. Seems like it would be pretty easy for me to implement, but I can't manage to find where this definition is written in the source & don't really understand the structure of zotero extensions. If you can point me in the right direction I should be able to manage. if it's something you'd like to have in the extension i'd be happy to PR :)

Thanks in advance, love this plugin and use it literally all the time

**Comment by retorquere** [comment]
The formats themselves are implemented [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/translators/Better%20BibTeX%20Citation%20Key%20Quick%20Copy.ts), and you add them to the selection menu [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/Preferences.xul#L529), and you'd need to add a label [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/locale/en-US/zotero-better-bibtex.dtd#L95) (only to the English strings, translations are handled through Crowdin).

Alternately, you can select "Eta template" as the quick-copy format and enter an [eta template](https://retorque.re/zotero-better-bibtex/installation/preferences/citation-keys/#eta-template).

**Comment by sneakers-the-rat** [comment]
Fabulous!!!! I'll take a crack at it. Feel free to close this issue :)
