### ISSUE TITLE
Disabling the Better BibTex Initializing popup - possible? 

### ISSUE THREAD

**Issue by digital-carver** [retorquere/zotero-better-bibtex#1767]
**Your question/suggestion:**

When Zotero starts up, there's every time a small pop-up window about BibTex initializing and its progress. I find it unnecessarily distracting and would like to disable it. If not entirely (which would also be fine), at least to make it local within the Zotero window rather than a global pop-up that obstructs other windows. 

I've searched the Zotero forums and the old issues here, looked at the Better BibTex preferences section too, but couldn't see anything related to this. Is this possible to do, and if not, could it be added as a configurable preference in the future?

**Comment by retorquere** [comment]
I can see whether there's a more subtle way to show load progress, but I'm not removing it entirely. Zotero has a very long startup sequence during which plugins really shouldn't do anything, and I kept getting complaints about the long startup time when I was really only waiting for the all-clear from Zotero.

**Comment by digital-carver** [comment]
I understand, I guessed the reason for the pop-up must be something like that. It makes sense to have it on as a default, but providing an option to turn it off - even an "Advanced" preference i.e. an `about:config` value to set - would be very helpful.

Often, I open Zotero when I come across a useful article, I click the Zotero Connector, and it informs me that Zotero isn't open. At this point, when Zotero is opening, I'm into research mode already, and would really prefer not to be distracted by what looks like an OS notification at a glance. My use case is such that the loading time of plugins is of little concern to me, and an unobtrusive experience is of much more importance. Perhaps this isn't the average use case, but a little option in some corner, available to be tweaked for this use case, would be much appreciated.

**Comment by retorquere** [comment]
I'm looking at a progress bar at the top near the sync button instead, but it's misbehaving.

**Comment by qqobb** [comment]
I actually like BBT's startup prompt. The Zotero desktop client isn't fast at startup, so when I launch Zotero I just Alt+Tab away to other programs. The BBT prompt remains in the foreground and when it disappears I know Zotero is ready.

@digital-carver: I would recommend starting Zotero before you're in research mode and then keeping it open.

@retorquere: I'm not sure new UI options are a good idea. The current feature is working well and other options might introduce new issues, especially given that Zotero's UI keeps evolving. A hidden option in `about:config` for users who don't like the prompt seems like a good solution to me. Those users would see whether Zotero is ready by watching the citekeys appearing. That should be enough.

**Comment by retorquere** [comment]
To be clear, it is not the loading time of plugins that is the issue. It's zotero that is taking long to load, and I'm just informing of that to set the expectations right. BBT loads much faster than zotero does, once it's allowed to.

**Comment by retorquere** [comment]
A build will drop here shortly, with that installed, you can go into the hidden settings and change `startupProgress` into `progressbar`. If that looks OK to you, I can merge to main.

**Comment by digital-carver** [comment]
Nice. This is quite unobtrusive and visually has a polished look as well. Thanks for the quick work on this.
