### ISSUE TITLE
Export as Collected Notes does not list subcollections

### ISSUE THREAD

**Issue by davidoskky** [retorquere/zotero-better-bibtex#1768]
**Exporter used: Collected Notes

**Expected behavior:
When I export the collected notes every collection appears as a title in the html document and all the articles contained in that collection are listed after such title.
I would expect to have subtitles for subcollections and have the articles contained in those subcollections listed after such subtitle.

**Actual behavior:
All the articles from the subcollections appear at the beginning of the document and there is no way to differentiate from which one they are from.
I don't know if this could cause problems: all my collections that contain subcollections have a space in their name and contain no articles as I use them simply to organize.

**Comment by davidoskky** [comment]
**Report ID:AGI9JQ42-euc

**Comment by retorquere** [comment]
You couldn't have known, but `AGI9JQ42-euc` does not contain any collections. You'll have to right-click your library to send the debug report.

**Comment by davidoskky** [comment]
I'm sorry, here it is: 8CNNP8IN-euc
I hope everything is alright this time.

**Comment by retorquere** [comment]
No need to be sorry, you couldn't possibly have known. `8CNNP8IN-euc` does contain collections.

**Comment by retorquere** [comment]
Can you try build 551?

**Comment by davidoskky** [comment]
Thank you, I didn't believe you would start working on it so quickly!!
I installed the build provided above, but the issue is not solved.
Now at the top of the file an extra title is displayed, which wasn't there before: "1. Unfiled".
After that title are listed all the articles from the subcollections, it is still impossible to distinguish from which subcollection they're from.
The rest of the document is identical as it was before.

**Comment by retorquere** [comment]
Are you exporting your full library, or a collection?

**Comment by davidoskky** [comment]
I am exporting the full library.
I tried exporting just one collection containing subcollections and it does work as expected: each subcollection has a title and the articles from those subcollections are listed after the title.

**Comment by retorquere** [comment]
When I export your library (assuming what you sent is your whole library), I get this: https://gist.github.com/bfd9fca4f213ec910686a9f6dc4d54b3

**Comment by davidoskky** [comment]
Strange... this is exactly what I want!
In truth right now I have been testing on a different library than the one I sent you as I have that in the computer in my workplace.
I will try tomorrow with that same library to see what happens.

**Comment by retorquere** [comment]
That makes it hard for me to know what's going wrong. If you get me a debug log of that different library I might be able to replicate your problem.

**Comment by davidoskky** [comment]
I am at my workplace now and I tried exporting the whole library, it doesn't work with this library either.
Here is the debug log with the same library I sent you previously: KBQEFBTE-euc

**Comment by retorquere** [comment]
When you say "it doesn't work", what doesn't work, precisely? Can you get me the exported file?

**Comment by davidoskky** [comment]
Here is the exported file: https://filebin.net/xr4fa5jho1x98auh/My_Library.html?t=tqw7p7s2
All the articles from subcollections appear after the first title "1. Unfiled" and you cannot distinguish between different subcollections.

**Comment by retorquere** [comment]
`KBQEFBTE-euc` was sent from the Help menu.

**Comment by retorquere** [comment]
I'm losing track of what debug ID goes with the failing export. If https://filebin.net/xr4fa5jho1x98auh/My_Library.html?t=tqw7p7s2 is the output that isn't as you wanted, I need to have a library-debug-log for that Zotero library.

**Comment by davidoskky** [comment]
I'm sorry about the mess!
I made this log right clicking the library that produced that output: 3DIK9WZA-euc

**Comment by retorquere** [comment]
That gets me https://gist.github.com/3b62a2e0379eafd46413b897a444df48

**Comment by davidoskky** [comment]
At this point I do not understand, every time I export my library I obtain the output I sent you.
I tried exporting the library in two ways: right click on the library -> Export library or File -> Export library.

Am I doing something wrong?

**Comment by retorquere** [comment]
I don't see how you could do anything wrong here. ISTR there was something you could have recursive exports or not, but I can't find anything about that here.

**Comment by retorquere** [comment]
A new version will be announced here shortly; can you export to Collected Notes and *after* that send a debug log (from the Help menu will suffice here).

**Comment by davidoskky** [comment]
Here it is: 9GIAMN4Y-euc
The output is the same of the previous version.

**Comment by retorquere** [comment]
Can you do the same with 555?

**Comment by davidoskky** [comment]
Here it is: CKY75CWE-euc
I made this with a different library, but the output has the same problem.
If you need the debug done with the same library as before, I'll send it to you on monday.

**Comment by retorquere** [comment]
And the same with 556?

**Comment by davidoskky** [comment]
Here it is: B4WIPXHP-euc
I just realized, I didn't mention I have the ZotFile addon installed as well.

**Comment by retorquere** [comment]
you know the drill

**Comment by retorquere** [comment]
(the debug log also lists which extensions you have installed, but zotfile shouldn't matter)

**Comment by davidoskky** [comment]
Here is the new one: 6597FAF2-euc

**Comment by retorquere** [comment]
There's only 2 collections in that log, PGP and Modelli, and no subcollections. There were 6 I think in the previous, with one having multiple subcollections.

**Comment by davidoskky** [comment]
That's strange, it's the same library of B4WIPXHP-euc and I do have 6 collections...
I tried sending the debug once again: JTQKMMS7-euc

**Comment by davidoskky** [comment]
I mean, 3 collections, one of which has 4 subcollections.

**Comment by retorquere** [comment]
No, previously I saw this:

* Fingerprints
* Modelli
* Modelling methods
  * Applicability Domain
  * Classification
  * Consensus
  * Distance
  * Random Forest
* PGP
* Virtual Screening

**Comment by retorquere** [comment]
A new build will drop here in a few minutes; do a Collected Notes export with that, and then right-click on the library to send the debug log. That will give me the logs + the library the collected notes were exported from so I have a coherent picture.

**Comment by davidoskky** [comment]
Here is the new log: TH5CR4T9-euc

**Comment by retorquere** [comment]
Another log please from 563. Still no idea what's happening on your system, but it looks like specifically the Collected notes is not being offered subcollections. No idea why yet. And I can't replicate it on my systems.

**Comment by davidoskky** [comment]
Here: EUMFIMPD-euc

**Comment by davidoskky** [comment]
Have fun with this: SVPMTUJ4-euc

**Comment by retorquere** [comment]
Alright, I know why this happens now.

**Comment by retorquere** [comment]
568 should fix it, but I'd still appreciate it if I could get a new log after a Collected notes export. They export in the foreground for you, and I'd like to see if I can fix that.

**Comment by davidoskky** [comment]
Thank you very much, it does work now!
You really did work a lot to help me with this, thank you!

Here is, hopefully, the last debug: BBHMS25Y-euc

**Comment by retorquere** [comment]
I could use your help a bit more. You are not getting background exports and I have not been able to replicate that on my systems.

**Comment by davidoskky** [comment]
No problem, it takes me just one moment to send a debug log!

**Comment by davidoskky** [comment]
Here: 8DZ6X8K3-euc

**Comment by retorquere** [comment]
Awesome, that's what I needed to see. Thanks for all your help, I've scheduled a release of 5.2.132, but that's just a rebadged 569. You will be updated automatically somewhere in the next few days regardless when Zotero checks for new versions.

**Comment by davidoskky** [comment]
Thank you for your hard work!
