### ISSUE TITLE
[shortyear] adds 00 when date is missing

### ISSUE THREAD

**Issue by whitenoise-dev** [retorquere/zotero-better-bibtex#1769]
- Use  [shorttitle3_3][shortyear][0]
- Clip a webpage on the browser

**Expected behavior:**
ThePageTitle

**Actual behavior:**
ThePageTitle00

I am not sure if this bugs happens with regular zotero entries (papers)

**Comment by retorquere** [comment]
Oblig "please send a debug log first". The clipped webpage will have led to an item in your library. Please send a debug log as per point 1 by label-gun for that item. Without that I'd be guessing at what is actually in your library. Please just help me help you.

**Comment by whitenoise-dev** [comment]
Report ID: 9PEHYSNB-euc

I tested. This is reprduceble if you simply create an empty item with just a title

![image](https://user-images.githubusercontent.com/3163647/111983973-27816c00-8ae1-11eb-91e5-bf590530b553.png)

**Comment by retorquere** [comment]
Thank you. The debug log also gives me the sample to add to my test suite so the problem can't creep back in.

**Comment by retorquere** [comment]
Can you try 573?

**Comment by whitenoise-dev** [comment]
tested. it works!
