### ISSUE TITLE
Export not omitting specified fields

### ISSUE THREAD

**Issue by halawiye** [retorquere/zotero-better-bibtex#1775]
I wanted to remove abstracts, file paths and urls from my biblatex export so I added `abstract,file,url` to the "fields to omit from export" field in preferences.

**Report ID:**
EDEP86B5-euc

**Exporter used:**
Export Library > Format: BibLaTeX

**Expected behavior:**
Library exported as .bib file with specified BibLaTeX fields omitted

**Actual behavior:**
Library exported as .bib file with all fields still present

**Comment by retorquere** [comment]
I need a debug log from right-clicking the reference in question, not from the help menu.

**Comment by halawiye** [comment]
> I need a debug log from right-clicking the reference in question, not from the help menu.

Apologies, I've just sent one. Report ID: FFMWEIJM-euc
The problem seems to affect all of my references.

**Comment by retorquere** [comment]
FFMWEIJM-euc has 36 items, I'm going to focus on just the first ("Revisiting the wrinkling of elastic bilayers II: Post-bifurcation analysis"), if I fix it for one it will be fixed for all of them, and a single item (if possible) gives a more focused dialogue.

**Comment by retorquere** [comment]
It is removed for me. Can you try resetting the cache in the BBT advanced prefs and exporting again?

**Comment by halawiye** [comment]
Thanks for your swift responses. I tried resetting the cache but unfortunately, the error is still persisting and the abstract is still appearing in the exported .bib file.

**Comment by retorquere** [comment]
Can you install build 605, enable logging in the help menu, export "Revisiting the wrinkling of elastic bilayers II: Post-bifurcation analysis", and send a new debug log?

**Comment by halawiye** [comment]
Done, the new report ID is VYM82EPV-euc.

**Comment by retorquere** [comment]
I think you are exporting with the `BibLaTeX` exporter, not `Better BibLaTeX`.

**Comment by halawiye** [comment]
Ahh, I thought the plugin overrode the `BibLaTeX` exporter. It's all working fine, thanks so much for your help!

**Comment by retorquere** [comment]
If everything is working as it's supposed to, the export dialog displays a text in red alerting you to choose the BBT format when you select the zotero-standard biblatex export.

**Comment by halawiye** [comment]
> If everything is working as it's supposed to, the export dialog displays a text in red alerting you to choose the BBT format when you select the zotero-standard biblatex export.

I didn't have that warning text before, but after selecting `Better BibLaTeX` and going back to `BibLaTeX` it now appears. I only installed BBT yesterday so I think the chosen format was just defaulting to the previous choice of `BibLaTex` (perhaps the alert is only triggered once the format has been changed).

**Comment by retorquere** [comment]
Strange, it should always show that with BBT installed. I'll take a look.
