### ISSUE TITLE
BBT preference window is too wide

### ISSUE THREAD

**Issue by windingwind** [retorquere/zotero-better-bibtex#1778]
**Report ID:**
ASLDWPX4-apse

**Expected behavior:**
The preference window should have a normal size

**Actual behavior:**

After the BBT plugin loaded, the preference window will become wider, and if I disable BBT, this won't happen.

The widened window has a big blank area, which is strange.
![image](https://user-images.githubusercontent.com/33902321/112433490-4d2aa180-8d7d-11eb-9b76-a3aa432de899.png)

**Comment by windingwind** [comment]
In the latest Zotero beta, resizing the preference window is disabled, so I cannot reach its top bar or move the window if I use a small screen device, because of BBT preference page's abnormal width.

I also reported this problem to the Zotero forum, but they probably cannot do any.

**Comment by retorquere** [comment]
I'll see what I can do, but the preferences window is really wonky. It doesn't look like that across platforms, and I don't explicitly set the size; AAMOF I frequently tell Zotero to just size to the content, and this is how it ends up. And the technology that is used for this has been deprecated bij Mozilla years ago, so docs are scant, and support non-existent.

**Comment by windingwind** [comment]
Thanks! As a plugin developer, I understand it's difficult.

Could this happen because some hidden elements are added to the window during the loading process?

For example, some hidden elements bound with event handlers.

**Comment by windingwind** [comment]
Thanks,
The width is no longer strange, while the height may still have some problems.

![image](https://user-images.githubusercontent.com/33902321/112499617-9cdf8c00-8dc2-11eb-87e3-2f59c1b1fe8d.png)

**Comment by retorquere** [comment]
That prefs screen has *way too much* room at the bottom on MacOS. So infuriating. Like a large, weird chunk of nothing under that checkbox you marked.

A new build will drop in a bit that will attempt to make that bit scrollable. I don't know what else to make of it.

**Comment by retorquere** [comment]
> Could this happen because some hidden elements are added to the window during the loading process?
> 
> For example, some hidden elements bound with event handlers.

I don't think this is the case. But even if it were, that doesn't explain why the window is to short on Windows and too tall on MacOS/Linux.

**Comment by retorquere** [comment]
Can you give 611 a go?

**Comment by retorquere** [comment]
![Capture](https://user-images.githubusercontent.com/132108/112519904-20858280-8d9b-11eb-9d4c-e83af7797b53.PNG)

this is how it looks on windows for me

**Comment by windingwind** [comment]
Well, 611 is still the same for me.

![image](https://user-images.githubusercontent.com/33902321/112563883-2750db80-8e15-11eb-85a8-6b0f898b4f96.png)
![image](https://user-images.githubusercontent.com/33902321/112563896-2fa91680-8e15-11eb-8760-f81f64df6ef3.png)

Sorry for my late reply. I'm in China +8.

Anyway, at least the width is OK. Wasting more time on this issue is not necessary. Maybe you can just let it go and I'll try to find out the solution.

Thank you for your patience!

**Comment by windingwind** [comment]
Amazing fix speed! I guess this issue is already solved in 611. 

If I open the preference window and select the BBT tab while BBT is loading, its height will not be justified;
Otherwise, everything is fine.
And if I reopen the pref window, it will have a normal size.

Maybe because of the async load function--so the view cannot be updated right away.

Thank you!

**Comment by retorquere** [comment]
There's two stages to the prefs screen loading - when zotero starts, it still does a lot of "boot-up" work, and extensions must wait for this to finish. In this phase, BBT hides the controls on its prefs pane. After that, it will tell zotero to resize the prefs window to fit the controls to whatever is shown, every half second. The size-to-content function doesn't work as well as I thought it would, or I'm not using it right, but that's the only function that I know of that does anything halfway reasonable.

You might have seen the prefs window between updates. I honestly don't know. This part of Firefox that zotero builds on is a mistery to me, I have the only two books written on the matter here, and they make no mention of it; the online docs have fallen into disrepair, and Firefox doesn't really want people to use XUL/XPCOM anymore, so there's no active support community.
