### ISSUE TITLE
Exporting Zotero collections to Qiqqa

### ISSUE THREAD

**Issue by element4l** [retorquere/zotero-better-bibtex#1779]
edit: this is not a bug, I could not figure out how to apply/change the label assigned to this question. 

I'm trying to migrate from Zotero to Qiqqa, or maybe even use them side by side. But I want to maintain my collection organization. Is there a way to attach that information in bibtex, or apply the collections as tags to be transported over?

**Comment by retorquere** [comment]
If you enable [jabref metadata](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#include-jabref-specific-metadata), BBT will export the collections in jabref format. Maybe qiqqa understands that.

**Comment by element4l** [comment]
Thank you, retorquere. Unfortunately although Qiqqa can import jabref, it looks like that information about collections is not used by Qiqqa in any way from what I can tell. It does import tags, I've confirmed. So that postscript way might be worth a shot. I'm not exactly a programmer, but able and willing to learn. This is something I would put some time into myself if you could point me in the right direction on how one might start doing that.

**Comment by retorquere** [comment]
Don't worry about it. It's always OK to ask for a postscript. This facility is mainly an escape I grant myself so I don't have to change BBT for one-off requests.

```
const collections = item.collections.map(key => (Translator.collections[key] || {}).name).filter(coll => coll)
reference.add({ 
  name: 'keywords',
  value: item.tags.concat(collections),
  enc: 'tags',
})
```

**Comment by element4l** [comment]
That's really fantastic. I will give this a try. I saw that including jabref data turns off caching which says is a problem for auto-exporting. If I implemented this postscript instead of doing that, will that work for auto-export?

By the way, I have to say after digging around with Zotero plugins and seeing you on all these projects, I cannot thank you enough for everything you have created. You are an absolute gem to the community, and I don't think Zotero would be what it is without your contributions, so thank you.

**Comment by retorquere** [comment]
Yep, postscripts run in auto-exports, and this particular postscript will not affect caching. 

WRT the jabref data, auto exports will work fine, they'll just be a fair bit slower. Overall, zotero will actually be snappier though.

And you're very welcome.

**Comment by element4l** [comment]
This is very spectacular. I have just spent the better part of a week full time figuring out how to manage this library in a sensible way. You have made this infinitely easier. I have basically solved every problem I had now because of you. I am flat broke at the moment but when I do begin making an income again I will be sure to support your patreon. I really greatly appreciate your responsiveness. Outstanding.

**Comment by retorquere** [comment]
Don't worry about support - I'm financially stable, I used the support that came in to get a very necessary laptop upgrade, but since then it's been fueling upgrades to my drumkit, and I'm saving up for a trip to visit a friend in the USA - given the state of the world, I still have lots of time to save up.

I'm happy I could help you.
