### ISSUE TITLE
How to have duplicate citekey postfix to start from "b" instead of "a"?

### ISSUE THREAD

**Issue by ajshajib** [retorquere/zotero-better-bibtex#1781]
I would like to have the duplicate citekey postfix to start counting from "b" instead of "a". For example, instead of Shajib21, Shajib21a, Shajib21b, I want the series to look like Shajib21, Shajib21b, Shajib21c.

**Comment by retorquere** [comment]
This is not currently possible, and it would not be easy to add. I'm working on an overhaul of the pattern generator that might make it feasible, but that's not a short-term thing.

The closest you can currently get is using `[postfix+1=%(a)s]`, which would get you Shajib21a, Shajib21b, Shajib21c.

**Comment by ajshajib** [comment]
Ok, thanks for the clarification. I will close the issue now.

**Comment by ajshajib** [comment]
I figured out a way do it using postscript. The trick is to use `[postfix+1=%(a)s]` to have the series look like "Shajib21a, Shajib21b, Shajib21c", and then the following postscript will remove the a from "Shajib21a" to make the series look like "Shajib21, Shajib21b, Shajib21c".

```
if (Translator.BetterTeX || Translator.BetterBibLaTeX) {
     var new_cite_key = reference.item.citekey.replace(/\a$/, '');
     delete reference.item.citekey;
     delete reference.item.citationKey;
     reference.item['citekey'] = new_cite_key;
     reference.item['citationKey'] = new_cite_key;
}
```

**Comment by retorquere** [comment]
You can simplify that to

```
if (Translator.BetterTeX) reference.item.citationKey = reference.item.citationKey.replace(/a$/, '')
```

but note that the citationkeys used elsewhere in zotero (CAYW, drag-drop, displayed in the UI, etc) differ from the keys you export this way.
