### ISSUE TITLE
BibTeX citation key for Japanese documents

### ISSUE THREAD

**Issue by ShiroTakeda** [retorquere/zotero-better-bibtex#1785]
**My Report ID: WF6BUBJS-apse**

First of all, I would like to thank you for creating a useful tool like BBT. I am generally satisfied with the features of BBT. But I am writing this message because I face a problem that seems to be a bug.

**Actual behavior:**

I am a Japanese Zotero and BBT user and have many Japanese bibliography entries in Zotero library.

The problem is that when I make BBT to automatically generate BibTeX citation key for Japanese bibliography entries, **BBT converts Japanese characters (Kanji and Hiragana) in author name and title to "pinyin" (romanization for Chinese)**.

For example, I have the following document in Zotero (which is exported to BibTeX format).

    @article{youcunTanSuJiaGenoErChongnoPeiDang2018,
      title = {{炭素価格の二重の配当}},
      author = {有村, 俊秀 and 武田, 史郎 and 尾沼, 広基},
      year = {2018},
      volume = {11},
      pages = {73--78},
      doi = {10.14927/reeps.11.2_73},
      file = {G\:\\Zotero\\storage\\NHWXDXFM\\有村 et al_2018_炭素価格の二重の配当.pdf},
      journal = {環境経済・政策研究},
      language = {Japanese},
      number = {2}
    }

This is a Japanese article and uses Japanese characters (Kanji and Hiragana) in title, author and journal fields.

Please take a look at the the citation key of this entry (youcunTanSuJiaGenoErChongnoPeiDang2018), which is generated by BBT
automatically. It is the combination of pinyin expressions of Japanese characters in author and title fields.

The citation key expressed in pinyin will be useful for Chinese users but it is not desirable for Japanese users because romanization of Japanese characters is completely different from pinyin.

For example, BBT converts Japanese character "有村" in author name to pinyin "You Cun" but the standard Japanese romanization (Hepburn romanization) of "有村" is "Ari Mura".

For details of the difference in romanization in Japanese and Chinese, please see

+ https://en.wikipedia.org/wiki/Romanization_of_Japanese
+ https://en.wikipedia.org/wiki/Hepburn_romanization
+ https://en.wikipedia.org/wiki/Pinyin

In Better BibTeX option -> Advanced -> Citation keys, I found the following option

"Apply kuroshiro romanization in Japanese names/titles. Use a lot of memory".

However, even when I turn on this option, Japanese characters in citation key are always converted to pinyin. I think that this is not an intended behavior.

**Expected behavior:**

I do not want BBT to convert Japanese characters to roman characters when this kuroshiro option is not turned on. Taking the previous entry as an example, when the kuroshiro option is not turned on, I want the citation key like

有村炭素価格2018 or 有村-炭素価格-2018

This citation key does not romanize Japanese characters and uses Japanese characters as they are.

Japanese LaTeX users usually use pBibTeX or upBibTeX (unicode-enabled version of pBibTeX) as BibTeX engine. These BibTeX engines can handle citations key written in Japanese characters. So I think that it is not necessary for many Japanese users to romanize Japanese characters in citation keys.

**Comment by retorquere** [comment]
Thank you for including a debug log, that makes troubleshooting so much easier. Can you go into the advanced prefs and turn on `kuroshiro romajization in Japanese names/titles`, and see if that does better?

**Comment by ShiroTakeda** [comment]
> This documents the possibilities, but it's pretty dense; what it comes down to is that if you make the leading character uppercase, you get unprocessed data that you can then modify using filters. Something like this may get close to what you want:

    [Auth][Title:split-ideographs:select=1,3:capitalize][year]

Thank you very much. I did not know this feature. With this feature, I am likely to be able to create the desired citation key.

**Comment by retorquere** [comment]
It's not as easy to fine in the documentation as it should be, so it's always OK to ask.
