### ISSUE TITLE
Can't find the "keep updated" checkbox

### ISSUE THREAD

**Issue by walkinverse** [retorquere/zotero-better-bibtex#1790]
This is a install error with no debug in zotero.  I cannot install it via firefox.  The XPI file states it's corrupted.  Not sure what to do.

<img width="474" alt="Screen Shot 2021-04-12 at 1 16 37 PM" src="https://user-images.githubusercontent.com/42853036/114456122-5b582a80-9b91-11eb-981f-0430d294ed05.png">

Support log ID:

**Comment by walkinverse** [comment]
There is no log. Its a Firefox issue. Wont install states corrupted.

**Comment by retorquere** [comment]
I've added an explanation of what happened and the remedy to the the [BBT docs](https://retorque.re/zotero-better-bibtex/support/faq/#add-on-could-not-be-installed-because-it-appears-to-be-corrupt).

**Comment by walkinverse** [comment]
Thank you.  I just had another issue and I will post the logs.  I switched computers and now I cannot  export as I accidentally closed my library and cannot get the section to export.  

Support Id: MLI7R7F6-euc

All I get is a blank screen and it says wont show until  you export, but I have no way to export.  I used export library. but my library is no longer showing and I have no way of getting it to show. 

<img width="723" alt="Screen Shot 2021-04-15 at 7 43 53 PM" src="https://user-images.githubusercontent.com/42853036/114964673-0aac3000-9e24-11eb-9df0-47be2f8647a0.png">

Thank you again. Sorry for the delay in responding.  Having to move everything to a backup computer.

**Comment by RobbiNespu** [comment]
>  this is your friendly neighborhood build bot announcing [test build 5.2.147.729](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.147.729.xpi) ("don't use decoder for utf-8")
> 
> Install in Zotero by downloading [test build 5.2.147.729](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.147.729.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

Still not working, same issue

**Comment by retorquere** [comment]
I'll need a new log from build 729

**Comment by walkinverse** [comment]
Here is the log id: DT4NDUGF-euc

**Comment by retorquere** [comment]
I don't see errors in that log. Can you try to export as you did previously, and then send a support log again?

**Comment by walkinverse** [comment]
Sure.  Here is the new ID and also I had to update Zotero to the beta version as it updated the database.  

Log ID: FC78YQBV-euc. 

I do not see the screen any longer.  Please see screen shots.

<img width="727" alt="Screen Shot 2021-04-16 at 3 04 44 AM" src="https://user-images.githubusercontent.com/42853036/115009423-2255d980-9e61-11eb-96c0-32a4aa2efde1.png">
<img width="694" alt="Screen Shot 2021-04-16 at 3 05 17 AM" src="https://user-images.githubusercontent.com/42853036/115009437-241f9d00-9e61-11eb-8463-6168d417656d.png">

**Comment by retorquere** [comment]
I'm sorry, but I do not know what screen you're not seeing, or what that would indicate. The auto-export screen will not show anything until you've done an export from the main window (the usual Zotero exports) and checked the "keep updated" checkbox. `MLI7R7F6-euc` did have an error which could have prevented the cache from loading, but the autoexports, if any, should have loaded fine; but `FC78YQBV-euc` does not show an error, and also does not show any export activity that could create an auto-export.

**Comment by walkinverse** [comment]
I can no longer do an automated export.  On the first screen the library has been removed and I have no way to generate it.  I exported the library, and even after the screen still shows blank.

<img width="447" alt="Screen Shot 2021-04-16 at 3 19 55 AM" src="https://user-images.githubusercontent.com/42853036/115011228-3f8ba780-9e63-11eb-9c02-287a9ec478cd.png">
<img width="464" alt="Screen Shot 2021-04-16 at 3 22 09 AM" src="https://user-images.githubusercontent.com/42853036/115011229-40243e00-9e63-11eb-8ba1-7331e034a6b6.png">
<img width="737" alt="Screen Shot 2021-04-16 at 3 22 39 AM" src="https://user-images.githubusercontent.com/42853036/115011232-40bcd480-9e63-11eb-90d3-c087237cdf08.png">
<img width="562" alt="Screen Shot 2021-04-16 at 3 23 09 AM" src="https://user-images.githubusercontent.com/42853036/115011233-40bcd480-9e63-11eb-93f8-db7584609391.png">

**Comment by retorquere** [comment]
But you haven't checked "keep updated" here.

**Comment by retorquere** [comment]
I think I have something.

**Comment by retorquere** [comment]
No, I do see them appearing. Can you make sure that debug logging is enabled, then export with "keep updated" checked, then send a new support log? Without restarting Zotero in between.

**Comment by walkinverse** [comment]
Again, there is not checked. Please see screecast video.  Here is the most current ID: SAKG4XUL-euc

https://ln.sync.com/dl/ade826520/cph33h8b-9rurxkzq-gmcu9g5p-wymukcj4

**Comment by retorquere** [comment]
Go to 1:21 in that screencast. There is a "keep updated" checkbox that you need to check, that will create the auto-export. Also, if your sending a support you must not restart between recreating the problem and sending the log, because when you restart, Zotero clears its logs.

**Comment by singlinger** [comment]
![image](https://user-images.githubusercontent.com/29154976/115178514-0756c400-a104-11eb-95ed-e714d35195b0.png)

No "Keep Updated" item

**Comment by retorquere** [comment]
Pause the video at 1:20 and look at the checkboxes just above the ok button you click.

**Comment by walkinverse** [comment]
I must have missed it. Thank you again for your help and this plugin. Also, I am not sure, but it asked me to update the version of Zotero as the database was a different version after I installed the plugin.  I assume that is normal?  Thank you again.

**Comment by retorquere** [comment]
> I must have missed it. Thank you again for your help and this plugin.

So does the autoexport appear now?

> Also, I am not sure, but it asked me to update the version of Zotero as the database was a different version after I installed the plugin. I assume that is normal? Thank you again.

That's not related to the plugin. Zotero asks that sometimes.

**Comment by walkinverse** [comment]
I think we are good to go.  Thank you again!

<img width="718" alt="Screen Shot 2021-04-18 at 10 36 40 PM" src="https://user-images.githubusercontent.com/42853036/115186489-af35a880-a096-11eb-8c39-914d38952a7c.png">
