### ISSUE TITLE
BBT sentence case has stopped working for a few days now

### ISSUE THREAD

**Issue by MavropaliasG** [retorquere/zotero-better-bibtex#1795]
**Support log ID:** WCKKVMWL-apse

**Expected behavior:** Change the title of article to sentence case.

**Actual behavior:** Nothing happens. This has stopped working since the last week, I have been trying with multiple articles from multiple sources, and I have received 2 - 3 updates in zotero-better-bibtex during this time. I have been using the regular zotero sentence case till now.

**Comment by retorquere** [comment]
I can replicate this, on it.

As an aside, another plugin is generating (unrelated) errors, you might want to report this to the author:

```
[JavaScript Error: "TypeError: dois[0] is undefined" {file: "chrome://zotero-scite/content/Scite.js" line: 74}]
getDOI@chrome://zotero-scite/content/Scite.js:74:5
getCellX@chrome://zotero-scite/content/Scite.js:140:17
Zotero_ItemTreeView_prototype_getCellText@chrome://zotero-scite/content/Scite.js:161:12
Zotero_ItemTreeView_prototype_getCellText@chrome://zotero-better-bibtex/content/better-bibtex.js:59950:14
```

**Comment by MavropaliasG** [comment]
I can confirm that test build 5.3.2.774 fixes the issue. Thank you @retorquere

**Comment by retorquere** [comment]
Thanks for the report; I've scheduled a new release, you'll be upgraded automatically, but it's simply a rebadged 774.
