### ISSUE TITLE
Trigger export of bibliography "from the outside"

### ISSUE THREAD

**Issue by publicimageltd** [retorquere/zotero-better-bibtex#1796]
I love using betterbibtex; and I use in particular the feature to export my library to a .bib file automatically. That way, I can use my zotero library from within emacs, which accesses the .bib file.

The only annoying issue I have is keeping that exported file up to date. I can't export upon every change, that doesn't work (too slow, too many entries); and export-when-idle does also not work so well. So I usually open emacs, find out that the bib entry is not there, open zotero, export manually (right click), and go back to emacs. 

Now my question: would it be possible to trigger the export from within emacs, e.g. by calling zotero in headless mode with some argument? That's probably not a betterbibtex question, so if you know any resources that could help, I'm willing to learn. Yet minimally, if there is a way to trigger a command from the outside, I would need to know how I could trigger the betterbibtex export of my library.

**Comment by retorquere** [comment]
How many entries are at play here?

You can simply call the [pull export](https://retorque.re/zotero-better-bibtex/exporting/pull/) URL using `curl` with something like `curl -o mybib.bib 'http://127.0.0.1:23119/better-bibtex/export/library?/1/library.biblatex'` (or something inside emacs can undoubtedly do it for you). If you're using biblatex you can also use a remote `addbibresource`, but that means the document can only compile on the system where you have Zotero running. That's undesirable for most people in my experience.

**Comment by retorquere** [comment]
(how did you submit the issue BTW? You git the request from the bot because the issue wasn't labeled, but the green "new issue" button should have led you to an issue creation menu with would all give a label to the issue)

**Comment by publicimageltd** [comment]
Ah, perfect! "Pull export" - didn't know that exists, thanks so much! Tried it; and it just works (tm).

This issue was posted the normal way, I figure; I did nothing special, and it's not my first issue. Don't know why there was no creation menu.

Keep up the good work, and thanks for the fast reply where in fact a RTFM would have been enough! :grin:

**Comment by retorquere** [comment]
That last response is a bug in the bot, sorry, I'll look into that immediately.

**Comment by retorquere** [comment]
I don't like to point to RTFM; there's too much information to digest, and just finding it requires some knowledge. Glad I could help.
