### ISSUE TITLE
Cite archive documents with BetterBibLaTeX

### ISSUE THREAD

**Issue by rezemika** [retorquere/zotero-better-bibtex#1799]
Hello!

This issue is related to my post in the Zotero forum: https://forums.zotero.org/discussion/89445/cite-archive-documents-with-betterbiblatex-or-other

I write a document with LaTeX and Zotero, and I would like to cite archive documents, like old paper documents, stored in a repository wirh an identifier. But when I export such documents from Zotero to a bibliography file, the archive-related fields are missing, and I only get their title, date, and URL.

**Support log ID:** `DBIEZHQW-euc`

**Exporter used:** Better BibLaTeX

**Behavior:** I would be very convenient to export archive-related fields, in order to cite archive documents with their archive repository or their identifier. For instance, I have a scan of an old paper document, which is cited like this with the "Modern Language Association 8th edition": 

`Un million et demi d’infirmes, handicapés physiques et mentaux. 31 mai 1968, https://archives.strasbourg.eu/archive/fonds/FRAM67482_0592_114Z/view:115037. Archives de la Ville et l’Eurométropole de Strasbourg, 114 Z 1 248.`

But here is the bib file created with the Better BibLaTeX exporter:

```
@letter{MillionDemiInfirmes1968,
  title = {Un Million et Demi d'infirmes, Handicapés Physiques et Mentaux},
  date = {1968-05-31},
  url = {https://archives.strasbourg.eu/archive/fonds/FRAM67482_0592_114Z/view:115037},
  urldate = {2021-04-08},
  type = {Letter}
}
```

As you can see, the archive-related files are not exported, so the repository ("Archives de la Ville et l’Eurométropole de Strasbourg") and the identifier ("114 Z 1 248") won't be printed in the bibliography.

Do you think it would be possible to add support for these files in BetterBibTeX?
Thank you very much in advance!

PS: I apologize if I made mistakes for the archival terminology in english, it's not my native language.

**Comment by retorquere** [comment]
I'll need a debug created by right-clicking the item you want exported differently, and then selecting "send support log" from the BBT entry in the popup menu that appears.

**Comment by rezemika** [comment]
Oh sorry, here is report id for the same item: `TWQ9AUAW-euc`. ;)

**Comment by retorquere** [comment]
I'm going through https://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/biblatex-contrib/biblatex-mla/doc/biblatex-mla.pdf but I don't seeclear recommendations for what to put in the `eprint` field, which I think would be the best candidate. @njbart?

**Comment by njbart** [comment]
This is one area where some of the supposedly most popular packages – biblatex, biblatex-apa, biblatex-chicago, biblatex-mla – are all over the place, if they explicitly support archival material at all. So it’ll be difficult to find a solution that caters for all of these and possibly other packages, too.

First, basics. The relevant CSL variables are, as described in the CSL manual:

`archive` – archive storing the item  
`archive_location` – storage location within an archive (e.g. a box and folder number)  
`archive-place` – geographic location of the archive
    
While the GUI equivalents of the first two seem to appear in virtually all Zotero entry types, the third is only accessible via the "Extra" field (and, like other non-GUI variables, probably not used much, though it does appear in a number of csl styles, including apa and chicago variants).

Now, biblatex has no special fields for dealing with info about physical archives but does have provisions for electronic archives via the fields `eprint` ("identifier"), `eprintclass` ("section of an archive"), and `eprinttype` ("name of the archive").

One could get away, I guess, with mapping `archive` -> `eprinttype`, `archive_location` -> `eprint`, and `archive-place` -> location (or, possibly, `eprintclass`, or combining `archive_location` and `archive-place` into `eprinttype`).

What I don’t like about this is that biblatex output would look rather weird, if not misleading (just think of `eprinttype={Bodleian Library}`).

Two other packages, biblatex-chicago and biblatex-mla, do mention items in physical archives, but only one (biblatex-mla) has a clear schema of how to record archival information (type `@unpublished`; fields `number`, `library`, `location`; see manual). Note that the `library` field is unique to biblatex-mla. (biblatex does define the field, but never uses it in its standard styles, and I find no indication that either biblatex-apa or biblatex-chicago would use it for a physical archive.)

biblatex-chicago seems to recommend using the type `@misc` with an non-empty `entrysubtype` filed, and the fields `organization` for the archive’s name, `location` for its address, and `type`, `howpublished`, `number` (according to the packages’s manual, see the various sections on the `misc` field) or `note` (some items in the package’s example file `dates-test.bib`) for location within an archive.

Finally, biblatex-apa does not discuss physical archives at all. I suspect it will generate some output from both `eprint`/`eprintclass`/`eprinttype` and `organization`/`location`/`number`, though I haven’t checked whether any of this would conform to how one would expect information about a physical archive to be printed.

So, what to do?

I’m all in favour of a default behaviour by BBT that does not discard any information that has been entered into Zotero, and in this case this includes the fact that stuff has been put into the *"Archive …" GUI fields. Mapping these to fields like `eprint` or `library`/`organization` would remove a clear indication that originally this was meant to provide information about a physical archive. Plus, to open another can of worms, information about libraries and library call numbers would have to be shoehorned into the very same kinds of biblatex fields, adding to the confusion.

So my suggestion is to have BBT output, by default, biblatex fields named exactly like their CSL counterparts, i.e., `archive`, `archive_location`, `archive-place` (or possibly, for maximum clarity, `csl_archive`, `csl_archive_location`, `csl_archive-place`.

Users would then have to actively do one of two things (and, given that it seems none of the various biblatex packages is vastly more popular than any of the others, I think it’s only fair to leave this to the users):

Either have BBT map these field names to those appropriate for the particular biblatex package they are using.

Or employ the `sourcemap` mechanism provided by biblatex/biber to remap fields at latex/biber runtime.

**Comment by retorquere** [comment]
Given this entry:

![Screenshot 2021-05-07 at 22 34 41](https://user-images.githubusercontent.com/132108/117505582-8cefc600-af84-11eb-80dc-79b246ee70a1.png)

Should the `Library Catalog: IEEE Xplore` be used for anything? The entry currently exports to

```
@article{mosenia2017ComprehensiveStudySecurity,
  author = {Mosenia, Arsalan and Jha, Niraj K.},
  title = {A {{Comprehensive Study}} of {{Security}} of {{Internet}}-of-{{Things}}},
  journaltitle = {IEEE Transactions on Emerging Topics in Computing},
  shortjournal = {IEEE Trans. Emerg. Top. Comput.},
  volume = {5},
  pages = {586--602},
  publisher = {{IEEE}},
  date = {2017-10},
  issn = {2376-4562},
  doi = {10.1109/TETC.2016.2606384},
  annotation = {ZSCC: NoCitationData[s0]},
  number = {4}
}
```

also looks like `publisher` doesn't belong here.

**Comment by njbart** [comment]
> Should the `Library Catalog: IEEE Xplore` be used for anything?

If there’s any demand for this at all, one could try something along the lines of what I’ve suggested above. Finding intuitively understandable biblatex field names seems even more tricky, though. Zotero has "Library Catalog" and "Call Number", which it maps to CSL `source` [!] and `call-number`. But neither `source` nor `csl_source` as biblatex field names would immediately indicate that this was mapped from a "Library Catalog" GUI field, and I hesitate to suggest something like `zotero_library_catalog` as a biblatex field name …

> also looks like `publisher` doesn't belong here.

This comes from the "Extra" field (cheater syntax).

**Comment by retorquere** [comment]
Can entries have comments between the fields?

**Comment by retorquere** [comment]
I'm going to add a pref for this, I do not want to export these fields by default

**Comment by retorquere** [comment]
This build doesn't change anything yet, you can safely ignore it.

**Comment by retorquere** [comment]
There solution is described at https://retorque.re/zotero-better-bibtex/exporting/scripting/#citing-documents-with-a-physical-archive-location
