### ISSUE TITLE
Citation keys not updating when information changed

### ISSUE THREAD

**Issue by JohnCWood** [retorquere/zotero-better-bibtex#1800]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT support log from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Support log ID: 9E35E3P4-euc

**Expected behavior: When changing information in a Zotero record (such as name or year), normally the citekey is automatically changed to reflect this. (I've been using Zotero consistently for a couple of years and this has always worked this way as far as I can recall. The problem seems to have only come up in recent days.) 

**Actual behavior: The citekey is NOT being updated. Even when doing a manual refresh of the record, the citekey does not change. I have had to go into the citekey and change it manually. I generated the Log ID (as a test) when changing the name of the author from Abelshauser to Schmidt. In the main Zotero window the item moved alphabetically to Schmidt and the author was correctly displayed. However, the BBT-generated citekey did not change, neither in the main central window nor in the field entry window on the right. 

Thanks for any help you might provide!

**Comment by JohnCWood** [comment]
Additional description of problem: Even when creating a *new* item from scratch, the citation key is not updating. 

Here is a support log for this example of the same problem. 

Support log ID: 8RCJ4QSC-euc

![Screenshot from 2021-05-05 20-50-03](https://user-images.githubusercontent.com/41887839/117193743-8544eb80-ade3-11eb-9aae-1ba6910fa6bc.png)

**Comment by retorquere** [comment]
I think I have that replicable. On it.

**Comment by JohnCWood** [comment]
Great, many thanks!

**Comment by JohnCWood** [comment]
I removed the old BBT and installed the new one. Seems to work as normal again! Thank you!

**Comment by retorquere** [comment]
Thanks for the confirmation, glad it was solved. And thanks for reporting!

**Comment by JohnCWood** [comment]
I'm a big fan of BBT, so happy to help!

**Comment by JohnCWood** [comment]
Sorry for the premature close. I'm new at this.

**Comment by retorquere** [comment]
No worries, this behavior of issues is peculiar to this specific repo, there's absolutely no way to know this without trying. It's a shame that GH issues have such poor workflow facilities, this is the best I could come up with; previously I would reopen without comment and that too was confusing.
