### ISSUE TITLE
Citekey dependent on input method

### ISSUE THREAD

**Issue by xracoonx** [retorquere/zotero-better-bibtex#1801]
**Support log ID:**
CKP8H2AQ-refs-euc

**Expected behavior:**
The Citekey should be independent of which input method for author names is used (single field/two fields).

**Actual behavior:**
The Citekey is dependent of which input method for author names is used.

**Comment by xracoonx** [comment]
Just got an email saying that I did not upload a support log ID even though I did...

**Comment by xracoonx** [comment]
CKP8H2AQ-refs-euc

**Comment by retorquere** [comment]
That's a bug in the bot, I'll look into that, but wrt the issue itself, it's complicated - zotero itself makes this distinction for a reason, single-part name fields usually denote proper nouns with spaces, so it's not clear to me how I should detect it's actually a two-part name.

I don't have access to my computer right now and it'll be a bit before I do - what is the single-part name in question?

**Comment by xracoonx** [comment]
Okay, I see that Zotero makes a difference in the bib-file. But the output in biblatex is the same... Maybe the biblatex algorithm could be used to determine the CiteKey in order to avoid this problem?

Two-field export:
```
@incollection{bonjour_there_2013,
  title = {Is {{There A Priori Knowledge}}?},
  booktitle = {Contemporary {{Debates}} in {{Epistemology}}},
  author = {Bonjour, Laurence and Devit, Michael},
  editor = {Steup, Matthias and Turri, John and Sosa, Ernest and Steup, Professor of Philosophy Matthias and Turri, John and Sosa, Romeo Elton Professor in the Department of Philosophy Ernest},
  date = {2013},
  publisher = {{John Wiley \& Sons, Incorporated}},
  location = {{Somerset, UNITED STATES}},
  url = {http://ebookcentral.proquest.com/lib/sub/detail.action?docID=1245461},
  urldate = {2021-05-05},
  isbn = {978-1-118-32814-9},
  keywords = {Knowledge,Theory of.}
}
```

One-field export:
```
@incollection{laurencebonjour_there_2013,
  title = {Is {{There A Priori Knowledge}}?},
  booktitle = {Contemporary {{Debates}} in {{Epistemology}}},
  author = {{Laurence Bonjour} and Devit, Michael},
  editor = {Steup, Matthias and Turri, John and Sosa, Ernest and Steup, Professor of Philosophy Matthias and Turri, John and Sosa, Romeo Elton Professor in the Department of Philosophy Ernest},
  date = {2013},
  publisher = {{John Wiley \& Sons, Incorporated}},
  location = {{Somerset, UNITED STATES}},
  url = {http://ebookcentral.proquest.com/lib/sub/detail.action?docID=1245461},
  urldate = {2021-05-05},
  isbn = {978-1-118-32814-9},
  keywords = {Knowledge,Theory of.}
}
```

**Comment by xracoonx** [comment]
Also Zotero seems to figure out rather well how to switch from one-field to two-field input and vice versa. Maybe their algorithm could be used to determine a stable cite-key?

**Comment by retorquere** [comment]
I'll take a peek, but why not just switch to the two-part name? My worry is dat some proper nouns are only meaningful as a whole, and then I'd be stacking kludge on kludge to tell them apart. The zotero field splitter has the benefit that you see the results and can edit them when they're not what you want, that interactivity does not exist for key generation.

**Comment by xracoonx** [comment]
Yes, there may be good reasons for sticking to how it works currently. I am not able to see the whole picture. All I experienced was that I entered a name in the one-field format which worked fine for biblatex but that I could not find the CiteKey as usual in the `<lastname>_<title>_<year>` format. Now I see that BetterBibTeX is set to `[auth:lower]_[shorttitle1_1:lower]_[year]`. And `[auth:lower]` apparently does not imply the guessing of the last name as zotero's one to two field switch does. Maybe a new field could be added such as `[auth:lower_last]` or so which does create the stable CiteKey as I expected? And maybe this could even become the new default (leaving people who are used to the `[auth:lower]` non-interfered with...)?

**Comment by njbart** [comment]
> … but why not just switch to the two-part name? 

Precisely. *Not* using two-part fields for conventional personal names will cause no end of trouble further down the line. Except for sheer luck, one will *not* get "correct" output from something like `author = {{Laurence Bonjour} and Devit, Michael}`. (If in doubt, try a few different biblatex styles, in particular author-year variants …) And I don’t see why BBT should go out of its way to facilitate such bad practices.

**Comment by xracoonx** [comment]
Thanks. That is helpful to know but does not solve the problem of wrong expectation. I don't think it's to be expected that a typical user of Zotero/Better BibTeX has this kind of knowledge. After all, these tools enable people to use BibTeX even without any knowledge of BibTeX files. But maybe Zotero and not Better BibTeX is to blame for my expectations then? There is a placeholder in the one-field input that reads "(full name)". Taking the typical meaning of "full name" in English, this creates the expectation that entering "Laurence Bonjour" is equivalent to entering "Bonjour" and "Laurence" in the two-field input which has the placeholders "first" and "last". And in fact it is in Zotero when switching between one- and two-field input. Maybe these are not equivalent. Then it would be good if Zotero would inform the user what they are for. Maybe by choosing a more accurate placeholder for the one-field input?

**Comment by njbart** [comment]
Fair enough. I realize "full name" could indeed be considered a bit of a misnomer. (The [citeproc-js docs](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html) use "Institutional name" – would that be any clearer?)

And, surprisingly, there doesn’t seem to be any discussion of this in the Zotero docs at all.

You might want to take this up with the Zotero developers.

**Comment by xracoonx** [comment]
Actually, the Zotero documentation mentions "Instututional name" as well:

> Each name field can be toggled between single and two field mode by clicking the “Switch to single field” / “Switch to two fields” buttons at the end of the creator field. Single field mode should be used to institutions (e.g., when the author is “Company A”), while two field mode (last name, first name) should be used for personal names. If a person has only one name (e.g., “Socrates”), enter this as a Last Name in two field mode. You can switch the order of two field author names by right-clicking on the name and choosing “Swap First/Last Names” (https://www.zotero.org/support/adding_items_to_zotero#editing_items)

So, I guess it's really an issue with a too ambiguous field description. I'll try to bring it up on the Zotero forum.

**Comment by xracoonx** [comment]
Here is my attempt: https://forums.zotero.org/discussion/89541/ambiguous-description-of-one-field-author-input#latest

**Comment by retorquere** [comment]
> Maybe a new field could be added such as [auth:lower_last] or so which does create the stable CiteKey as I expected? And maybe this could even become the new default (leaving people who are used to the [auth:lower] non-interfered with...)?

I could extend the `select` filter to allow for offset-from-end; that should allow something like `[author:select=-1.1]`, but that will give you funny results when you have an actual last name with a space. Honestly, I think the best option here is just to use the two-part input. The selecting or guessing is really a kludge-on-a-kludge workaround, and that's going to bite me on support. You want two-part names for actual two-part names anyhow, because your bibliographies will include given names in one-field mode.

**Comment by retorquere** [comment]
>  And in fact it is in Zotero when switching between one- and two-field input. 

It just splits on the last space. If you enter "David Lloyd George" in the one-part name field, it will split incorrectly. The split has no smarts about names (nor should it, [given the complexity involved](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)), it is a convenience, the user is supposed to add the smarts.

Thank you for reporting the naming issue on the Zotero forums. I think the current behavior in BBT the the right behavior, even though I know the web importers will occasionally import a name as one-part when it is intended to be a two-part name.

**Comment by retorquere** [comment]
I feel like this has been addressed.

**Comment by xracoonx** [comment]
Let's hope Zotero takes it on. By the way, I just noticed that my CiteKey for the respective entry changed a day ago or so. Now it is not the last name of the author of the book section but the editor of the book. Was there anything changed? This does not strike me as an improvement.

**Comment by retorquere** [comment]
Keys also do not update unless the entry changes, or you manually refresh the key. (re)installation of BBT won't change/refresh any keys.

**Comment by xracoonx** [comment]
Now it is the last name of the author again. I know that it changed because it broke my document. I'll keep an eye on it. Maybe it has to do with me using Zotero on different computers. Maybe on one of them another format is used which creates some sort of conflict?

**Comment by retorquere** [comment]
If you are generating keys one more than one system, and these systems have different patterns, and the generated bib files with these keys end up in the same place, then yes, they will differ, but that should not be surprising.
