### ISSUE TITLE
Automatic commit/push cycle in Git does not seem to work

### ISSUE THREAD

**Issue by mfhepp** [retorquere/zotero-better-bibtex#1802]
*Please verify **all** of the below before submitting*:

**Support log ID:** DNV98TYP-euc

**Exporter used:** Better BibTex

**Expected behavior:** After a change of an entry, the .bib file should be exported AND the change should trigger an automated pull / add/ commit / push cycle in Git.

**Actual behavior:**
The local .bin files is updated upon a change. But the change is not committed / pushed to the repository.

<pre>
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   xyz-master.bib

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.DS_Store
	archive/

no changes added to commit (use "git add" and/or "git commit -a")
</pre>

`$ git config zotero.betterbibtex.push`was successful:

`$ git config zotero.betterbibtex.push
true
`

The `config` file in the `.git` folder of the repository is attached.

A manual add/commit/push cycle works.

<pre>
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/xyz/references.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[zotero "betterbibtex"]
	push = true
</pre>

**Comment by mfhepp** [comment]
I found and solved the issue, but others may also face the same problem:

First: In order to debug such stuff, close BetterBibTex and start it in a terminal window with full debug output, like so on OSX:
`$ /Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText`

With that, I could see that the `pull` command was returning a warning

<pre>
$ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
</pre>

So the solution is to go to the directory that holds your Git repository to which you are exporting the .bib file and then squelch the warning:

`$ git config pull.rebase false``

So the default reconciliation approach will be `merge`.

I would not set this globally because of side-effects.

With that set and restarting Zotero, the problem disappears.

**Comment by retorquere** [comment]
This is more than a warning then? Because git does not actually pull?

Capturing the output of shell commands is unfortunately not easy in Zotero; the code that's supposed to do it in its Firefox base works but frequently crashes Zotero unceremoniously.

**Comment by mfhepp** [comment]
Yes, `git pull` issues a warning and actually executes the pull properly.

But either the returned exit code is not zero or Zotero stops if a warning message is returned. So as soon as `git pull` (or likely any other CLI command) returns with a warning, the following commands are not executed (and this silently).

**Comment by retorquere** [comment]
Actually.... I can't see the output of the command, but I *can* ignore the exit status.

**Comment by retorquere** [comment]
Wait - the warning was in the logfile?

**Comment by mfhepp** [comment]
No, in the live console output when starting Zotero in debug mode with 
`$ /Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText`

**Comment by mfhepp** [comment]
Actually, I think it would be ideal to show the console output of the git commit to the user, or at least the success of the operation.

**Comment by retorquere** [comment]
I agree, or at least show it when it seems to fail, but I cannot capture the output of programs I run; it is supposed to be possible, but if I call the api that does it, zotero crashes fairly reliably. I'm surprised it shows up in the console text, I'll see what I can grab from that, but even that I will not be able to grab reliably - it will be intermixed with other console text.

**Comment by mfhepp** [comment]
As an addendum: The cycle can also fail if you have untracked files in the repository, e.g. a `.DS_Store` file in OSX, because the warning of untracked files will also return a non-zero exit code

The fix is to add a .gitignore file to the repository to which Zotero exports.
