### ISSUE TITLE
Can't download .xpi file

### ISSUE THREAD

**Issue by aakritimalik** [retorquere/zotero-better-bibtex#1804]
See error message below -

![image](https://user-images.githubusercontent.com/83862926/117976843-7fde2880-b330-11eb-8335-666d39b7ac88.png)

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/support/faq/#add-on-could-not-be-installed-because-it-appears-to-be-corrupt

**Comment by aakritimalik** [comment]
Thanks, works now!

**Comment by retorquere** [comment]
Good to hear you got it working; the message from the bot is wrong, it is misbehaving. It should not have posted here.
