### ISSUE TITLE
Infinite install loop

### ISSUE THREAD

**Issue by ronburk** [retorquere/zotero-better-bibtex#1805]
For some weeks now, I get the commonly seen "New Better BibTeX translators have been installed. If you want to use these for drag-and-drop (e.g. to drag and drop citekeys or citations), you will need to restart once to activate them." dialog box when starting up Zotero. But when I click the "Restart now" button, I get the same dialog again after restart. Eventually I give up and just hit the "Restart later" which seems to let me get on with my life without any detectable ill effects.

Is this some known issue with better-bibtex, or with Zotero, or... something else I can easily fix? Thanks!

Windows 10. Latest Zotero: 5.0.96.2. Better BibTex for Zotero 5.4.10.

**Comment by ronburk** [comment]
DKCPBGVF-euc

**Comment by retorquere** [comment]
I don't see any BBT error but I see a whole host of errors looking like

```
"Win error 5 during operation open on file C:\rlb\data\zotero\styles\american-sociological-association.csl (Access is denied.
```

looks like there's a permission problem in your Zotero profile; that could in turn cause a lot of problems.

**Comment by ronburk** [comment]
Ugh. Must've gotten wedged by the old portable-ntfs-drives-user-ID-no-match hassle. (c:\rlb is a junction point on multiple machines I carry Zotero around to on thumb drive). Sure enough, running Zotero as Administrator averts the problem. Thanks for your help!

**Comment by retorquere** [comment]
No worries.

**Comment by retorquere** [comment]
Wouldn't that be a reason to use exFAT rather than NTFS on the thumb drive?

**Comment by ronburk** [comment]
> 
> 
> Wouldn't that be a reason to use exFAT rather than NTFS on the thumb drive?

For sure. Unfortunately, my experience over the years has been more annoying file-level data loss with removable drives on exFAT than with a journaling filesystem, so I put up with different annoyances. :-)
