### ISSUE TITLE
Initializing "Loading citation keys" won't disappear

### ISSUE THREAD

**Issue by ReaderGuy42** [retorquere/zotero-better-bibtex#1809]
I'm on the newest version of the add-on (5.4.13) and I can't find anything about this or how to solve it.

The little pop-up saying "Better BibTex: Initializing - Loading citation keys"
won't disappear.

Any advice? Thanks!

**Comment by ReaderGuy42** [comment]
support log ID T3ZMGEM9-euc

**Comment by retorquere** [comment]
Can you shut down Zotero, go into the Zotero profile directory, and get me a copy of the json files in the `better-bibtex` folder?

**Comment by ReaderGuy42** [comment]
All of the .json files in that folder?

**Comment by retorquere** [comment]
Yes please. You ought to be able to zip them up and attach them here.

**Comment by ReaderGuy42** [comment]
[.json.zip](https://github.com/retorquere/zotero-better-bibtex/files/6501927/default.json.zip)
Thanks! If there's anything else you need, let me know :)

**Comment by retorquere** [comment]
Will do. I know from T3ZMGEM9-euc that there's something wrong with the database, but I don't know which. The jsons will tell.

**Comment by ReaderGuy42** [comment]
Thank you! That did it :)
