### ISSUE TITLE
Exporting "month = {season}" for BibTeX

### ISSUE THREAD

**Issue by TheVoroscope** [retorquere/zotero-better-bibtex#1810]
Per a request from @retorquere made in a [Zotero Forum post](https://forums.zotero.org/discussion/comment/383275/#Comment_383275) I'm bringing this issue here to Git.

A week ago BBT was not exporting "Year Season" date fields from Zotero correctly via the automatic export to .bib files in ordinary BibTeX via the Better BibTeX .bib output -- the Year was being dropped entirely (and no Season was coming out). That was noted there, and a fix produced double-quick, with this code (in 5.4.13):
```
case 'season':
      ref.add({ name: 'year', value: date.year })
      ref.add({ name: 'month', value: ['', 'spring', 'summer', 'fall', 'winter'][date.season] })
break
```

As noted at the Zotero Forum, the use of "fall" would not be sufficient for (e.g.) GB or AU users, since the term used is "Autumn" t/here, so some extension to this case selector is needed (I do have a few refs with this season in my database, so they are not unknown). Hence the request to bring this here.

A quick check of the ISO 8601 Date-Time spec (as of 2019), interpreted at [Extended Date Time Format, Level 1, Seasons](https://loc.gov/standards/datetime/) shows (for use with BibLaTeX at least) that:

> Seasons
> The values 21, 22, 23, 24 may be used used to signify ' Spring', 'Summer', 'Autumn', 'Winter', respectively, in place of a month value (01 through 12) for a year-and-month format string.
>    Example                   2001-21     Spring, 2001

which shows the use of "Autumn" instead of the North American usage of "Fall".

For my part, using the .bst BibTeX, "month = {Season}" kludge with {Autumn} added to the case selector would suffice (as per the advice at [Stackexchange](https://tex.stackexchange.com/questions/396421/best-way-to-encode-season-spring-summer-fall-winter-in-bibtex/396619#396619)). Mileage may vary for others, especially for BibLaTeX, where some selector may end up being needed for Autumn/Fall selection (ISO says Autumn...).

**_Love_** BBT, BTW. ❤️👍

Support log ID:

**Comment by TheVoroscope** [comment]
Output from Chicago 17 full-note is:

>Hinton, Leanne. Review of _Hopi Time_, by Ekkehart Malotki. _American Indian Quarterly_ 12, no. 4 (Autumn 1988): 361–64. https://doi.org/10.2307/1184426.

Output to the .bib file is
```
@article{hinton88rht,
  title = {Hopi {{Time}}},
  author = {Hinton, Leanne},
  year = 1988,
  month = {fall},
  volume = {12},
  pages = {361--364},
  issn = {0095-182X (print); 1534-1828 (elec.)},
  doi = {10.2307/1184426},
  collaborator = {Malotki, Ekkehart},
  journal = {American Indian Quarterly},
  number = {4}
}
```

I'm less concerned about the mis-match between `Reviewed Author` in Zotero and the use of `collaborator` in the .bib, because that's not something BibTeX really understands (and would take too long to deal with). But the mis-match between Autumn and fall is visible above.

**Comment by retorquere** [comment]
I still really need a support log as per bullet point 1.

**Comment by retorquere** [comment]
Good point. 892 exports the year, not the season, and makes the season available in postscripts, so that one could do:

```
if (Translator.BetterBibTeX && reference.date.type === 'season') {
  reference.add({ name: 'month', value: ['', 'spring', 'summer', 'fall', 'winter'][reference.date.season] })
}
```

**Comment by TheVoroscope** [comment]
Yep, works with the scripting option under the Advanced tab pref. 👍
