### ISSUE TITLE
Request for a way to make citekeys out of the `Date Added` field using a specific date and time format

### ISSUE THREAD

**Issue by Sienna-Milady** [retorquere/zotero-better-bibtex#1812]
I'd like to generate citekeys using the `Date Added` field from Zotero items using a specific date and time format.

The desired behavior for this feature should be that the text from the `Date Added` field can be converted into a different date and time format which would be used for citekeys.

I think that this could be a filter similar to the date-formatting filter but for the time too, or a time-formatting filter that could be combined in some way with the existing date-formatting filter.

An example of the behavior is as follows: if the `Date Added` field of an item is `5/19/2021, 1:08:47 PM`, then a possible resulting citekey could be `20210519130847`, which translates to 2021(year)05(month)19(day)13(hour)08(minutes)47(seconds).

**Comment by retorquere** [comment]
You don't want this anymore? Otherwise I'll need a support log as described in point 1 by the label gun bot.

**Comment by Sienna-Milady** [comment]
I wanted to make a feature request, not report a bug. I wanted to close this because I didn't know how to proceed after the bot came up and added the label. I also made a duplicate of the issue which got the same label. Sorry! Let me know what I should do.

**Comment by Sienna-Milady** [comment]
Here it is: `697JQBAD-refs-euc`. Hope it's not too late. (Dismiss the backticks).

**Comment by retorquere** [comment]
No problem

**Comment by Sienna-Milady** [comment]
Is there anything else that I should do?

**Comment by retorquere** [comment]
Nope, that's all, thanks

**Comment by Sienna-Milady** [comment]
Alrighty.

**Comment by retorquere** [comment]
You can get the key you want using the pattern `[DateAdded:format-date=%Y%m%d%H%M%S]`

**Comment by Sienna-Milady** [comment]
Thanks a ton! I'll use this right away :D

**Comment by retorquere** [comment]
Please let me know if it works, and I'll merge it into the next release.

**Comment by Sienna-Milady** [comment]
Something's not right with the citekeys generated. The citekey of my latest item is `20210522195852`, while the date of addition from the `Date Added` field is `5/22/2021, 4:58:52 PM`. The hour in the citekey differs from that of the `Date Added` field by 3 hours.

The pattern for the citation key format is the one that you sent.

Do you have any idea what's going on?

**Comment by retorquere** [comment]
The date added is in UTC. If you open your library in a different country, the "date added" shown in Zotero will change according to the local timezone dynamically, but the time stored is UTC.

**Comment by Sienna-Milady** [comment]
How can I open my library in a country that uses UTC? I couldn't find any information about this in the Zotero documentation, though if there is this, I missed it.

Otherwise, the filter works fine.

**Comment by retorquere** [comment]
You'd do that by eg setting your OS to region Iceland. I don't think you'd want to do that. If you want keys to have the local time, I'd have to add a filter to add or subtract the requisite number of hours. Timezone handling however is [not trivial](https://www.zainrizvi.io/blog/falsehoods-programmers-believe-about-time-zones/) so unless there's a library that does it for me, that filter would just add a configurable but fixed number of hours.

**Comment by retorquere** [comment]
> Otherwise, the filter works fine.

The filter hasn't changed. The function for DateAdded was added.

**Comment by retorquere** [comment]
Note to self: https://www.w3schools.com/jsref/jsref_gettimezoneoffset.asp might help.

**Comment by retorquere** [comment]
does this do what you want?

**Comment by Sienna-Milady** [comment]
The link returns "Page not found".

**Comment by Sienna-Milady** [comment]
Yes, that's perfect!

**Comment by Sienna-Milady** [comment]
Yes, that's perfect!
