### ISSUE TITLE
Export of BetterBibTex not possible

### ISSUE THREAD

**Issue by jonnythemonster** [retorquere/zotero-better-bibtex#1820]
I am attempting to export a collection in Zotero as Better BibTeX, as I did before the last update. Unfortunately, this does not work. Neither for BetterBibTex, BetterBibLaTex, for collections nor the library. I have also activated and deactivated the keep-updated option within the export dialogue.

I hope I have reported the error correctly - I am new here.

**Support log ID:**
D431399525

**Exporter used:**
Better BibTeX

**Expected behavior:**
A new bib file that replaces the old one

**Actual behavior:**
Error after selecting "Replace". It says: "Ein Fehler ist aufgetreten bei dem Versuch, die ausgewählte Datei zu exportieren."

**Comment by jonnythemonster** [comment]
Okay, actually I made a mistake and reported the Zotero ID. I tried multiple times to create an BetterBib-ID. It is not possible. If I select `Send Better BibTeX debug report...` nothing happens.

**Comment by retorquere** [comment]
What OS are you on?

**Comment by jonnythemonster** [comment]
11.3.1 (20E241)

**Comment by retorquere** [comment]
MacOS?

**Comment by jonnythemonster** [comment]
Yes

**Comment by retorquere** [comment]
Can you cmd-Q Zotero, open the terminal, and run this:

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/Downloads/BBT.log &
```

then attach (not paste!) the file `BBT.log` in your Downloads folder here.

**Comment by jonnythemonster** [comment]
Sure 👍 
[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/6538559/BBT.log)

**Comment by retorquere** [comment]
And you saw the error popup when you generated the last log?

**Comment by jonnythemonster** [comment]
I am not sure if the error was displayed when entering the terminal. Unfortunately, the build did not help, rather the opposite. At the beginning, the error simply persisted. I tried reinstalling the add-on. That didn't help either. Restarting the computer resulted in Zotero starting, but all my literature was not recognised.

**Comment by retorquere** [comment]
If you just want to get on with your life, grab 5.4.14, but I'd hugely appreciate it if you would be around to test.

**Comment by jonnythemonster** [comment]
I find your application incredibly useful and I am more than willing to support you. Just let me know how.

**Comment by retorquere** [comment]
Hugely appreciated! Can you join on #1821?

**Comment by jonnythemonster** [comment]
I have just tried the build. At first glance, nothing changes. I can't set any citation keys and unfortunately the export doesn't work either.

**Comment by retorquere** [comment]
You also still can't send a debug log?

**Comment by jonnythemonster** [comment]
No

**Comment by retorquere** [comment]
Can you start with 

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/Downloads/BBT-1820.log &
```

and get me the log again?

**Comment by jonnythemonster** [comment]
[BBT-1820.log](https://github.com/retorquere/zotero-better-bibtex/files/6539718/BBT-1820.log)

**Comment by retorquere** [comment]
I have no idea what's so different about your system. When I start up Zotero like that, I get the following at the start of the log:

```
1621950437906 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider", "XPIInternal"]
1621950437909 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1621950437932 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1621950437934 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
```

your log skips the first 70 lines of startup that are in mine, and end at about 12% of my log.

Just so we know 100% we're looking at the same thing:

* cmd-Q Zotero
* start from command line as before
* wait until the BBT popups at the bottom left are gone
* cmd-Q Zotero

and then send the log?

**Comment by jonnythemonster** [comment]
Actually I forgot cmd-Q Zotero at the end. The thing is that BBT popups at the bottom are not appearing.
[BBT-1820.log](https://github.com/retorquere/zotero-better-bibtex/files/6539859/BBT-1820.log)

**Comment by retorquere** [comment]
Can you make a log again with 

```
/Applications/Zotero-beta.app/Contents/MacOS/zotero -ZoteroDebugText 2>&1 > ~/Downloads/BBT-1820.log &
```

**Comment by jonnythemonster** [comment]
there is not such directory
`[1] 2727
zsh: no such file or directory: /Applications/Zotero-beta.app/Contents/MacOS/zotero
[1]  + exit 127   /Applications/Zotero-beta.app/Contents/MacOS/zotero -ZoteroDebugText 2>&1 > 
`

**Comment by jonnythemonster** [comment]
Without the beta Version - don't know if that helps

`/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText 2>&1 > ~/Downloads/BBT-1820.log & `

[BBT-1820.log](https://github.com/retorquere/zotero-better-bibtex/files/6540005/BBT-1820.log)

**Comment by retorquere** [comment]
Yeah sorry about that, without the `-beta`

**Comment by retorquere** [comment]
Man I do *not* know what is so different about our systems. That log should absolutely have quite a few lines like

```
1621953983220 addons.xpi .....
```

and that's just missing in your log. Do you see a lot of text going across the terminal as Zotero starts? You should see at most 

```
2021-05-25 16:48:54.926 zotero[17754:265368] *** WARNING: Textured window <ToolbarWindow: 0x109735850> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
JavaScript warning: resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js, line 205: unreachable code after return statement
JavaScript error: chrome://zotero/content/xpcom/dataDirectory.js, line 35: Error: Data directory not initialized
objc[17754]: Class ZoteroSBApplicationDelegate is implemented in both /Applications/Zotero.app/Contents/Resources/extensions/zoteroMacWordIntegration@zotero.org/resource/libZoteroWordIntegration.dylib (0x10d378a28) and /Applications/Zotero.app/Contents/Resources/extensions/zoteroMacWordIntegration@zotero.org/resource/libZoteroWordIntegrationClient.dylib (0x10d393a18). One of the two will be used. Which one is undefined.
```

**Comment by retorquere** [comment]
Other take. Type `script` on the command line. You will see 

```
Script started, output file is typescript
```

and will be back at the prompt. There, type

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText
```

reproduce the error, and quit zotero. You should once again see the command prompt. Type `exit`, you will see

```
Script done, output file is typescript
```

and attach the file `typescript` it generated here.

**Comment by retorquere** [comment]
Same cause as #1821, please join there

**Comment by retorquere** [comment]
Can you go into the [hidden prefs](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/), look up extensions.zotero.translators.better-bibtex.citekeySearch, disable it, and restart Zotero?
