### ISSUE TITLE
Miss labeled version number

### ISSUE THREAD

**Issue by lewisharvey** [retorquere/zotero-better-bibtex#1828]
Now when I manually or automatically update to v5.4.18, Zotero says I have v5.4.13 installed and wants to update again. Is the version number on the latest v5.4.18 version set correctly?

**Comment by lewisharvey** [comment]
support log ID: U88FM9U5-euc

**Comment by retorquere** [comment]
5.4.18 is a re-upload of 5.4.14 (not sure why it would say 13) as an emergency fix for #1821. I'm hammering out the last details on discord, and will then release 5.4.19.

**Comment by lewisharvey** [comment]
Dear Emiliano,
Thanks for the note and all your fantastic work!
Cheers, Lew
---
Lewis O. Harvey, Jr. (he, him, his)
Director - Psychology and Neuroscience Honors Committee
Department of Psychology and Neuroscience
345 UCB (Office MUEN 251b)
University of Colorado Boulder
Boulder, Colorado 80309-0345 USA
+1 303.492.8882 (office)
+1 303.492.2967 (fax)
http://psych.colorado.edu/~lharvey (web)

CU UndocuAlly: I stand with undocumented students and staff, and their families.
---

On May 26, 2021, at 09:00, Emiliano Heyns ***@***.******@***.***>> wrote:



Closed #1828<https://github.com/retorquere/zotero-better-bibtex/issues/1828>.

**Comment by retorquere** [comment]
You're welcome - the new version is out so everything should be back on track.
