### ISSUE TITLE
quick copy notification causes Zotero titlebar problem

### ISSUE THREAD

**Issue by cobblepot1** [retorquere/zotero-better-bibtex#1831]
**Support log ID:**
LWULWQ8X-apse

**Expected behavior:**
When I use a keyboard shortcut to 'quick copy' a citekey to the clipboard, I get a notification in the titlebar about preparing the quick copy. After it's done, I would expect the notification to disappear and the Zotero titlebar to return to its previous layout.

**Actual behavior:**
![Clipboard Image](https://user-images.githubusercontent.com/65119937/120130061-dcc65380-c1f7-11eb-8d38-02c72f93bdb9.jpg)
The notification "Better BibTeX Citation Key Quick Copy" text remains in the titlebar and I cannot see how to remove it. The problem is that my Zotero window is 1/2 my monitor width and the text pushes my search and sync indicators past the window edge. Can I disable the notification, have it disappear quickly, or fix this in some other way?

Thanks!

**Comment by retorquere** [comment]
the progress bar ought to have disappeared automatically. It now actually does in build 993 -- can you verify it also works for you?

**Comment by cobblepot1** [comment]
Thanks, but it doesn't work—same behavior as before. Submitted new log BTSEXVQP-apse.

**Comment by cobblepot1** [comment]
Sorry, still no change. Submitted new log IRSYHISG-apse.

**Comment by cobblepot1** [comment]
Sorry, still not working. Tried with both 5.4.20.1000 and .1001 from the other thread. Support ID HLSR7CPY-apse.

**Comment by retorquere** [comment]
Ah -- I need you to restart zotero with debugging enabled from the help menu, then replicate the problem, then send a log.

In this case I got the information I needed from the log, but `HLSR7CPY-apse` was generated from .1001, not .1000. Builds on other threads will likely have very different logging enabled so I expect logs to be generated from the last version on the current issue.

**Comment by cobblepot1** [comment]
OK, Support ID S2CLDCAI-apse.

**Comment by retorquere** [comment]
Strange. Are you sure you restarted with debug logging? The log indicates that it's off at start; if it's off at the start, the logging I need is disabled and won't turn on if you set debug logging on while Zotero is running.

**Comment by cobblepot1** [comment]
Trying again. 26PQ7Q4R-apse
Help menu says that logging is enabled.

**Comment by retorquere** [comment]
That is correct, it is on from the moment you turn it on, but to debug this issue I need it to be already on when Zotero starts, long before you could even get to the help menu, and the only way to do that is to go in the Help menu => Debug Output Logging => Restart with logging enabled. I don't see the logging yet that I need. Can you install 1010 and try that procedure again? So:

* Install 1010, but do *not* click "Restart now"
* Go into the Help menu => Debug Output Logging => Restart with logging enabled.
* Reproduce the problem
* Send a log

**Comment by cobblepot1** [comment]
This one seems to have solved the problem! Thanks.
