### ISSUE TITLE
Improve import of films

### ISSUE THREAD

**Issue by simifilm** [retorquere/zotero-better-bibtex#1837]
**Support log ID:**
NG993Q6V-euc

**Full Bib(La)TeX item you are trying to import:**

```
@movie{Marka.S:2011a,
	date-added = {2020-09-16 13:56:16 +0200},
	date-modified = {2020-09-16 13:56:52 +0200},
	director = {Sebastian Marka},
	location = {DE},
	read = {1},
	title = {Interview},
	year = {2011}}
```

**Expected behavior:**
At the moment, import of films is severely limited. BBT does not recognise the type `@movie`. It only handles `@film` correctly, although `biblatex` does not know about this type.

In `@film` entries, the field `location` (and `address`) is not handled properly. It is imported as `Extra: tex.location` instrad of `Extra: Publisher place`. Interestingly, export does work correctly: When exporting a film from Zotero, `Extra: Publisher place` ends up as `location`.

**Actual behavior:**
Map `@movie` to `film`, map `location` to `Extra: Publisher place`.

**Comment by simifilm** [comment]
More in general: There are several of `biblatex`'s `orig` fields for which equivalents exist in the Zotero's `extra` field, but which are currently not mapped properly on import. Shall I open new bugs for these?

**Comment by retorquere** [comment]
> More in general: There are several of biblatex's orig fields for which equivalents exist in the Zotero's extra field, but which are currently not mapped properly on import. Shall I open new bugs for these?

That can be handled under this issue, no problem.

> Map @movie to film

A new build will drop here shortly that fixes that

> map location to Extra: Publisher place

I'll look into this. Mapping these fields is a little trickier.

**Comment by retorquere** [comment]
Why `Publisher place` rather than `Place`?

**Comment by simifilm** [comment]
> Why Publisher place rather than Place?
Ah sorry, I didn't realise `Place` works as well. In the Zotero forums, I only found references to the former.

It would also probably be good to map `biblatex`'s `@video` to `film`.

As for the additional mapping. I am not sure, what is already handled by BBT, but the following mappings would make sense

`original-date` ⇿ `origdate`
`original-publisher` ⇿ `origpublisher` 
`original-publisher-place` ⇿ `origlocation`
`original-title` ⇿ `origtitle

**Comment by simifilm** [comment]
Something else I've noticed: At the moment, `BBT` collapses `title` and `subtitle` into `Zotero`'s `title` field on import and joins them with a hyphen. 

Is this documented somewhere? And would it be possible to add the possibility to configure how these fields are joined?

**Comment by retorquere** [comment]
> > Why Publisher place rather than Place?
> 
> Ah sorry, I didn't realise `Place` works as well. In the Zotero forums, I only found references to the former.
> 
> It would also probably be good to map `biblatex`'s `@video` to `film`.
> 
> As for the additional mapping. I am not sure, what is already handled by BBT, but the following mappings would make sense
> 
> `original-date` ⇿ `origdate`
> `original-publisher` ⇿ `origpublisher`
> `original-publisher-place` ⇿ `origlocation`
> `original-title` ⇿ `origtitle`
 
Can you construct a testcase for these? Field mappings are not uniform  across types, so I always prefer to have concrete test cases.

**Comment by simifilm** [comment]
I just realised that the mapping does work one way: `original` entries `Zotero`s `Extra` field are correctly mapped when exported to `BibLaTeX`, but not the other way round. `orig` fields in `.bib` files end up as `tex…` in `Zotero`s `Extra` field.

Here's an example:

> @book{Roy.O:2017a,
	location = {New York},
	author = {Roy, Olivier},
	origdate = {2016},
	origlanguage = {french},
	origlocation = {Paris},
	origtitle = {Le djihad et la mort Le djihad et la mort},
	publisher = {Oxford University Press},
	subtitle = {The Global Appeal of Islamic State},
	title = {Jihad and Death},
	translator = {Schoch, Cynthia},
	year = {2017}}

I normally don't use `origpublisher`.

**Comment by retorquere** [comment]
I only have the following Zotero-supported `orig` fields:

* Original date
* Original publisher
* Original publisher place
* Original title

So I don't have a place for `origlanguage`

**Comment by simifilm** [comment]
> So I don't have a place for origlanguage

That is correct, AFAIK.

Thanks for taking care of this so quickly, this is simply amazing.

Something I noticed which I did not realise before: With `@movie`, the `author` field is now mapped to `Contributor`.

I understand that, by default, `@movie` is basically undefined in `biblatex`. My own style `biblatex-fiwi` is, to my knowledge, the only one with extensive support for films. While I have added the field `director` which does not exist in standard `biblatex` , the default for `director` is `author`. I have also added `scriptwriter` which is mapped to `editor`. So maybe it would make sense to add the following:

author/director ⇿  director
editor/scriptwriter ⇿  scriptwriter

Here's an example:

```
@movie{Ball.W:2014a,
	address = {US},
	author = {Ball, Wes},
	editor = {Noah Oppenheim and Grant Pierce Myers and T.S. Nowlin},
	title = {The Maze Runner},
	year = {2014}}
```

**Comment by retorquere** [comment]
Hi,

It's not clear to me whether we're addressing import or export currently. The bidi arrows aren't always helpful, as the transformation between bib(la)tex can't be entirely without loss of information about the context in which a field was used. I try to get roundtrippable import/export, but it's not a hard target.

Easiest for me actually is:

*import*:

* paste the bib(la)tex to import here
* import and edit it in zotero to have it look like you want
* right-click the item and send a debug log from the popup menu, and paste the log id next to the input sample

this will give me exactly what you have so we can forego guessing and descriptions.

*export*

* export the entry from Zotero to bib(la)tex and edit the things you'd like to see differently
* paste the result here
* right-click the entry you exported and send a log from the popup menu
* paste the log ID next to the sample entry

**Comment by simifilm** [comment]
_import:_
```
@movie{Ball.W:2014a,
	address = {US},
	author = {Ball, Wes},
	editor = {Noah Oppenheim and Grant Pierce Myers and T.S. Nowlin},
	title = {The Maze Runner},
	year = {2014}}
```
Support log ID: LBJE5FK6-refs-euc

_export:_

```
@movie{spielbergJaws1975, 
 title = {Jaws},
  author = {Spielberg, Steven},
  date = {1975},
  location = {US},
  editor = {Benchley, Peter and Gottlieb, Carl}}

```

Support log ID: VHX8F3TY-refs-euc

**Comment by retorquere** [comment]
> the default for director is author

I don't know what is meant by this.

I have no expertise in film -- it's not entirely clear to me what "author" means for a film. It seems more fuzzy than for a book or article. Not that I have reason to doubt that the closest analogue for a movie editor is author though. @njbart, what do you make of this? Is there any precedent that you know of?

**Comment by simifilm** [comment]
> I don't know what is meant by this.

I have introduced the field `director` for `@movie` in `biblatex-fiwi`, but it is an alias of `author`.

In general, the director is considered the central creative instance of a film, so it makes sense the use the `author` field for this. In addition, in most citation styles, the director of a film is mentioned, but rarely the scriptwriter. So I would definitely opt for treating mapping `Zotero`s  `director` to `author`. I think it is preferable to mapping it to `director` which only a few `biblatex` styles support.

**Comment by retorquere** [comment]
> In general, the director is considered the central creative instance of a film,

Wow, really? Alright, cool.

**Comment by simifilm** [comment]
Is that surprising? How often do you read about a film's scriptwriter oder editor?

Anyway, while there are huge differences in how films are cited in different styles – some even demand that actors are given which makes no sense at all –, the director is essential in all of them. And if you look at what is common in film and media studies, in most cases, only the director is given (tv shows are a bit different; here you often cite the show runner and sometimes the channel on which the show premiered).

I introduced the `production` in `biblatex-fiwi` for films which don't have an identifiable director (quite common if you deal with early films; in my case, I needed this for ISIS online videos which don't have proper credits). Having read the discussion in #365, I have now decided to map this field to `publisher`. So in a future release, they will be equivalent.

Oh, and did you see my question regarding the handling of `subtitle`?

**Comment by retorquere** [comment]
> Is that surprising? How often do you read about a film's scriptwriter oder editor?

Me, literally? Never on both.

> Oh, and did you see my question regarding the handling of subtitle?

I did but then forgot -- it's currently neither configurable nor documented. Do you have a different rule for importing them in mind?

**Comment by njbart** [comment]
> In general, the director is considered the central creative instance of a film, so it makes sense the use the `author` field for this.

True, broadly speaking. But details vary wildy when it comes to how this is handled by the various biblatex packages, and, accordingly, what might be encountered when importing from biblatex data in the wild.

**biblatex** itself makes no provisions for films/movies/videos at all, except for `@movie` and `@video` being aliases for `@misc`.

As of lately, it does support “data annotations“ via additional field such as, e.g., `AUTHOR+an:role` (see section “3.7 Data Annotations” in the v3.16 manual, and the biblatex-apa example below).

**biblatex-apa** used to support `director` and `producer` fields, but currently seems to make extensive use of “data annotations“ only. The manual does not discuss any of this, but see this example from the package’s `biblatex-apa-test-references.bib`:


```
% ENTRYSUBTYPE is a localisation string
% Three data annotations, one for each name in the AUTHOR list
@VIDEO{10.12:87b,
  ENTRYSUBTYPE    = {tvepisode},
  AUTHOR          = {B. Oakley and J. Weinstein and J. Lynch},
  AUTHOR+an:role  = {1=writer;2=writer;3=director},
  TITLE           = {Who Shot {Mr.} {Burns}? ({Part} {One}) ({Season}~6,
                     {Episode}~25)},
  MAINTITLE       = {The Simpsons},
  EXECPRODUCER    = {D. Mirkin and J. L. Brooks and M. Groening and S. Simon},
  PUBLISHER       = {Gracie Films and Twentieth Century Fox Film Corporation},
  DATE            = {1995-05-21}
}
```

**biblatex-chicago** on the other hand, does not use `author` but `editor` in combination with an `editortype` of `director`. Other `editortypes` include `producer` and `none` (“particularly useful if you want to identify performers”; for details, see the manual, currently v2.1).

**Comment by simifilm** [comment]
Interesting to see the example from `biblatex-apa`. Basically, they do everything different than `biblatex-fiwi`. Here's an example of tv episode in `biblatex-fiwi`:

```
@movie{Reardon.J:1994a,
	location = {USA},
	author = {Reardon, Jim},
	maintitle = {The Simpsons},
	number = {6},
	title = {Treehouse of Horror V},
	volume = {6},
	year = {1994}}
```

As I said, I am well aware that various citation styles handle films vastly differently. But AFAICS, APA actually does *not* mention the screenwriter in its citation style. So I am not sure why this is implemented in `biblatex-apa` (in `biblatex-fiwi`, the field `scriptwriter` only exists because a user specifically asked for it. I never use it and it is disabled by default).

That said, I am open to changes in `biblatex-fiwi`, for example adopting the annotation approach. It probably would be best to try to coordinate the various the styles in this regard, but this is definitely beyond the scope of this bug.

> I did but then forgot -- it's currently neither configurable nor documented. Do you have a different rule for importing them in mind?

My preference would be a period followed by an empty space. But that's just me. The hyphen approach seems unusual though. I would say that in general, either periods or colons are most common.

**Comment by retorquere** [comment]
> but this is definitely beyond the scope of this bug

For import this is true, for export not.

**Comment by njbart** [comment]
FWIW, the APA Manual, 7e, has:

> **87. TV series episode or webisode**
>
> Barris, K. (Writer & Director). (2017, January 11). Lemons (Season 3, Episode 12) [TV series episode]. In K. Barris, J. Groff, A. Anderson, E. B. Dobbins, L. Fishburne, & H. Sugland (Executive Producers), Black-ish. Wilmore Films; Artists First; Cinema Gypsy Productions; ABC Studios.
>
> Oakley, B. (Writer), Weinstein, J. (Writer), & Lynch, J. (Director). (1995, May 21). Who shot Mr. Burns? (Part one) (Season 6, Episode 25) [TV series episode]. In D. Mirkin, J. L. Brooks, M. Groening, & S. Simon (Executive Producers), The Simpsons. Gracie Films; Twentieth Century Fox Film Corporation.
>
> **Parenthetical citations:** (Barris, 2017; Oakley et al., 1995)   
> **Narrative citations:** Barris (2017) and Oakley et al. (1995)
>
> - Include writer(s) and the director for the episode. Include the contributor roles in parentheses after each contributor’s name. “Writer” and “Director” are shown here, but “Executive Director” or other role descriptions might also be used.
>
> - Provide the season number and episode number after the title in parentheses.

This looks a bit excessive to me as well, but, be that as it may, the most interesting question for BBT here is about useful heuristics for importing stuff into Zotero. 

At a minimum, an `author` field in a `@movie` or `@video` item in the absence of any fields like `director`, or `author+an:role` or `editortype` (including `editor[abc]type`) containing `director` would most likely indicate a director.
In addition, an `author` field in any item type if accompanied by `authortype={director}` or by `author+an:role={director}`, or an `editor` field in any item type accompanied by `editortype={director}` or by `editor+an:role={director}` is definitely intended to represent a director as well (note again that instead of `editor`, `editor[abc]` could be used in any of these field names). There are probably other variations out there, but these are the ones that come to mind ATM …

> It probably would be best to try to coordinate the various the styles in this regard, but this is definitely beyond the scope of this bug.

Agreed on both counts.

FWIW, again, I’m not sure why biblatex-apa uses `EXECPRODUCER` rather than something like `editor` plus `editor+an:role={execproducer}`, and I’ve been puzzled for a long time why biblatex-apa never went for using something like `volume=6, number=25` for TV seasons and episodes. If you, @simifilm, would like to try coordinating with biblatex-apa, this, I think, would be worth bringing up.

**Comment by simifilm** [comment]
@njbart This section from the APA manual is completely braindead IMO and obviously written by people who never actually work with films. The point of any citation is to clearly identify a certain work; why you would need stuff like executive producer is completely beyond me. But this is not really surprising, since I rarely ever encounter APA in film or media studies. In my experience, in English speaking humanities, in other words, the fields which do work with film, MLA is much more common.

That said, I doubt that many people ever use `biblatex-apa` in the way the example posted by @njbart implies since neither the annotation part nor fields like `execproducer` are mentioned in the manual.

I think I also looked at this once, but since I originally did only have the role of director did not see the point in using anything but `author`. I think I even looked at the annotation mechanism once for `biblatex-fiwi`. If I remember correctly, main reason I did not follow this route, was that it really does not work well with BibTeX GUIs (`BibDesk` in my case).

I don't want to promise too much, but I think I might try to get in touch with Phil and David Fussner, the author of `biblatex-chicago`. Maybe we can clean this up a bit.

**Comment by njbart** [comment]
> This section from the APA manual is completely braindead IMO […]

I won’t argue with that – but don’t forget there are people out there compelled by supervisors or publishers to follow this format to the letter. 

> […] I doubt that many people ever use biblatex-apa in the way the example […] implies since neither the annotation part nor fields like execproducer are mentioned in the manual.

This does not necessarily follow. The biblatex-apa manual itself is extremely terse compared to its biblatex and biblatex-chicago counterparts, and actually says “biblatex-apa-test-references.bib […] is the main documentation […]”.

And, more importantly, I don’t see any other way to use biblatex-apa. `director` not longer works (I just checked), so `author` plus `author+an:role={director}` seems to be the only option there is.

**Comment by simifilm** [comment]
@retorquere Thank you very much for the new build. Your response time is simply amazing.

**Comment by retorquere** [comment]
I must admit I've lost track of the discussion above -- would it be possible to construct import/export samples that you agree on?

**Comment by simifilm** [comment]
I am good for the moment. Import from `biblatex-fiwi` seems to work fine now. And for everything else I think we first have to agree on among style authors.

**Comment by retorquere** [comment]
And wrt the import of the annotated styles? I don't think I'm handling that correctly right now. A sample with match would help a lot.

**Comment by retorquere** [comment]
closing this as (partially) resolved as I want to cut a new release. If the dialogue progresses on the annotated fields etc, please open a new issue.
