### ISSUE TITLE
Error in customizing the export from Zotero 

### ISSUE THREAD

**Issue by stefanopagliari** [retorquere/zotero-better-bibtex#1838]
I have a question about the JS script to customize the export from Zotero 
 I have run the example that I found on the webpage (https://retorque.re/zotero-better-bibtex/exporting/scripting/) :

```
if (Translator.BetterTeX) {
  reference.add({ name: 'keywords', value: item.tags, sep: ', ' });
}
```

In the bib file that is exported by zotero however I get this: 

```
keywords = {[object Object], [object Object], [object Object], [object Object]}
```

Expected behavior:   
As an example when I export a reference with the following tags: 
- Social Sciences: Comprehensive Works
- Sociology
- Trade Policy

On the exported file, I have this:  

```
keywords = {[object Object], [object Object], [object Object]}
```

I'm not familiar with JS, so apologies if this is a simple mistake.

Support log ID:

**Comment by retorquere** [comment]
The sample on the site was wrong, it should be

```
if (Translator.BetterTeX) {
  reference.add({ name: 'keywords', value: item.tags, sep: ', ', enc: 'tags' });
}
```

tags need to be encoded differently. The default encoder is treating them like strings and then you get the `[object Object]`

**Comment by stefanopagliari** [comment]
This worked. Thank you for answering this. 

I have a couple of probably dumb quick questions about "is it possible to do XYZ". Should I open another issue or is there another channel you prefer?

**Comment by retorquere** [comment]
Probably not dumb. There's a lot of moving parts to BBT.

Here is OK, although I usually encourage questions to be handled on https://github.com/retorquere/zotero-better-bibtex/discussions

**Comment by stefanopagliari** [comment]
Thank you. I have posted the question in the discussions page
