### ISSUE TITLE
Hidden Preferences documentation

### ISSUE THREAD

**Issue by roaldarbol** [retorquere/zotero-better-bibtex#1843]
First of all, I've just switched to Zotero after much hesitation - and finding this plug-in made me make the switch! Really nice work! 

I'm trying to enable autoPin, and found this closed thread (#890) which had a link on how to configure the Hidden Preferences (https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopin). Am I right to believe that what is being referred to as `Config editor` is now called `postscript`, or is it something else? Otherwise just a small hint of updating the documentation. :-) Thanks again for the good  work!

**Comment by roaldarbol** [comment]
...aaaand I figured out that I'm wrong. Wasn't super clear that it was Zotero's own `Preferences/Advanced`, I assumed it was in the BetterBibTex `Preferences`.

**Comment by retorquere** [comment]
I've added a comment to that effect on the site. Should be up in 10 minutes.
