### ISSUE TITLE
Linking to Zotero items: pb with the id field

### ISSUE THREAD

**Issue by myildi** [retorquere/zotero-better-bibtex#1849]
Hello,
Thank you very much for developing this nice extension!
I use the last version of Zotero with the last version of OSX.
I meet a problem with BetterbibteX. 

I use Hook for connecting different information together and it has now a module for linking with Zotero items, that is very useful for me (I am a researcher).

It reads the information about the selected item in Zotero through the following curl command:
"curl -s -d selected=t\\&format=json  -G http://127.0.0.1:23119/zotxt/items"
and then builds a zotero:// link using the id it reads from this record

When Better BibTeX is activated, I get as the id the citekey of the article, like
                         zotero://select/library/items/harmsen2015
 and the the zotero link cannot point to the specific article when I click it.

If I deactivate BBTX, the correct id (the same as the name of the subfolder in the Zotero storage folder) is obtained and the link points to the specific file:
                       zotero://select/library/items/DCEXAPF4

I have looked at the BBTX options but I have not been able to locate any item about the ids. For now, I have had to deactivate BBTX, but I would be happy to continue to use it if I can set an option that lets me retrieve the internal id of Zotero.

Thank you for your attention.

Best regards.
Murat

**Comment by retorquere** [comment]
I don't generate or modify this url, that's zotxt's work. Zotxt likely detects the presence of BBT and reacts to that, but I don't know how it reacts to BBT and whether it's configurable; you'll have to ask the Zotxt developer.

**Comment by myildi** [comment]
Thank you very much! I will contact the developer of Zotxt too.
