### ISSUE TITLE
Support for bib glossary items via `bib2gls`

### ISSUE THREAD

**Issue by LecrisUT** [retorquere/zotero-better-bibtex#1854]
Similar to the current Zotero item to bib entry export, but between `Dictionary Entries` on Zotero side in an exported collection to a compatible `.bib` file following the convention in section 4 of the `bib2gls` [documentation](http://mirrors.ctan.org/support/bib2gls/bib2gls.pdf). A possible mapping can be:

| Zotero     | Bib              |
|------------|------------------|
| Title      | name/short       |
| Abstract   | description/long |
| Extra:Type | type             |

Support log ID: AUNRMUX2-refs-apse

**Comment by retorquere** [comment]
I need a more concrete idea of what you want, so you'd have to create such a collection as you envision it would sit in Zotero, and send a support log as per point 1.

**Comment by LecrisUT** [comment]
Done. `[FR]` is short for `[Feature Request]`

**Comment by retorquere** [comment]
This can be done with a postscript:

```
if (Translator.BetterTeX) {
  if (reference.referencetype === 'abbreviation') {
    reference.has.title.name = 'short'
    reference.has.abstract.name = 'long'
  }
}
```

and adding a line in the dictionary entries with:

```
tex.referencetype: abbreviation
```

**Comment by LecrisUT** [comment]
Yes, that's getting closer.

Ideally there would be a separate translator `Better bib2gls` that only scrapes for `Dictionary Entry`, so that it would not interfere with other bib exports. Based on the snippet  and hints, I can try my luck hacking a translator up.

The other thing is that it would need a separate logic or ignore the automated citation key creation. Unfortunately there is no clear way of distinguishing normal `Dictionary Entry` from the ones used to export to `bib2gls`. Here a custom item type would solve much of these problems.

**Comment by retorquere** [comment]
But that's contingent on there being custom entry types. I don't know if that's ever going to happen. It's certainly not happening soon.

**Comment by retorquere** [comment]
> ignore the automated citation key creation

If by that you mean "don't generate but use X", you can do that by adding

```
Citation key: X
```

to the `extra` field.

**Comment by retorquere** [comment]
With 1100 you can do

```
if (Translator.BetterTeX) {
  if (reference.referencetype === 'abbreviation') {
    reference.has.title.name = 'short'
    reference.has.abstract.name = 'long'
  }
  else {
    return {write: false}
  }
}
```

**Comment by retorquere** [comment]
Still interested?

**Comment by retorquere** [comment]
Custom classes are perpetually being considered.

Yes, the facility to discard entries is the new functionality. 

WRT a separate translator, wouldn't it be better to directly target what bib2gls targets, rather than targeting bib2gls?

**Comment by LecrisUT** [comment]
> WRT a separate translator, wouldn't it be better to directly target what bib2gls targets, rather than targeting bib2gls?

If I understand correctly you are referring to just translating the glossary entries rather than having a new translator. Yes that could also work, but there would appear edge cases where you might want to have dictionary entry to act both as glossary entry and reference.

While bib2gls and biblatex might work with a combined bib database, I don't think many people would choose that route, especially since the glossary items would be in a separate zotero collection for management and sharing purposes. That's why it would be more intuitive to have a separate translator. But also you might want to accommodate for the other camp as well, in which case it might be helpful to have both implementations.

**Comment by retorquere** [comment]
> If I understand correctly you are referring to just translating the glossary entries rather than having a new translator. Yes that could also work, but there would appear edge cases where you might want to have dictionary entry to act both as glossary entry and reference.

No, I mean: what we discussed above generates output that `bib2gls` can convert into some other output. Why not have a separate translator that generates the other output (whatever it is, I don't know) directly?

**Comment by LecrisUT** [comment]
Oh that's a good idea. The generate files I find are `.glg` and `.glstex` with maybe the latter being able to be used for the translation. You might want to shoot a quick message to the [`bib2gls`](https://github.com/nlct/bib2gls) dev on that part.

The only problem I can think of is that the latex compilation procedure is just like normal bib one `latex` -> `bib2gls` -> `latex` so that the first one can generate the list of items and format it needs. It would depend on exactly what processes are done in the `bib2gls` and what are done in the `latex` one, but `.glstex` looks to have relatively general information, but I don't think you might want to do that translator. Here are some snippets of that file:
```latex
%% Plenty of Fluff
\glsnoexpandfields
\providecommand{\bibglshashchar}{\expandafter\@gobble\string\#}
\providecommand{\bibglscircumchar}{\expandafter\@gobble\string\^}

%% Also a lot of organization stuff
\bibglssetlettergrouptitle{{E}{E}{5701632}{}}
\bibglssetlettergrouptitle{{H}{H}{5898240}{abbreviations}}

%% Example of an entry
\bibglsnewabbreviation{Gls:AE}%
{location={\glsnoidxdisplayloc{}{page}{glsnumberformat}{4}},
sort={AE|},
group={\bibglslettergroup{A}{A}{5373952}{}}}%
{AE}%
{average-energy}
\glsxtrfieldlistadd{Gls:AE}{loclist}{\glsnoidxdisplayloc{}{page}{glsnumberformat}{4}}
```

**Comment by retorquere** [comment]
If it generates two files, that already rules out a Zotero translator, which can only generate output for 1 file.

**Comment by retorquere** [comment]
1138 has an extension for [postscriptOverride](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#postscriptoverride) -- in addition to checking for the filename in this preference, it will also check for the presence of the target file name for the export, with the `.bib` replaced by `.js`. If either of those two is present, that file will be taken as the postscript instead of the postscript in the preferences. This way you can set up two auto-exports, where one runes the postscript above, and the other just does the regular export. The postscript above can test for other things, you can eg just test for type `dictionaryEntry` and then set `referencetype` in the postscript. That way the regular exports remain untouched.

@njbart do you reckon feeding bib2gls is common enough that a separate translator that automates this would be useful?

**Comment by retorquere** [comment]
This change is now merged to master and will be in the next release.
