### ISSUE TITLE
Latest Better BibTex addon not working with the latest version of Zotero

### ISSUE THREAD

**Issue by njss** [retorquere/zotero-better-bibtex#1855]
Zotero starts but is not visible, even no tray icon on the taskbar (the Zotero process is running on Windows 10 Task manager).
If I remove Better BibTex from Zotero extensions...then Zotero works again (Zotero ui is visible and Zotero icon on windows task bar)
This happened after the latest Better BibTex auto-update on Zotero 5.0.96.2 on Windows 10

**Comment by retorquere** [comment]
Is zotero installed on your c: drive, and is your library in the default place (home dir under c:\users? I'll have access to a windows system tonight so I can see whether I can replicate this, but this would be good to know ahead of time.

**Comment by retorquere** [comment]
I cannot replicate this with Zotero 5.0.96.2 and BBT 5.4.25 on Windows 10 (Enterprise 64 bit). I'll need more info on the state of your system.

**Comment by retorquere** [comment]
5.4.23 works for you?

**Comment by retorquere** [comment]
As I can't replicate the problem, I'll need you to 

1. Install BBT, but *do not* restart Zotero when offered. Just quit Zotero.
2. Generate a log using [these instructions](https://www.zotero.org/support/debug_output#windows), redirecting the output to a file:

```
"C:\Program Files (x86)\Zotero\zotero.exe" -ZoteroDebugText -console > log.txt
```

Zotero will still hang, but you can quit Zotero from the task manager after say 30 seconds.

**Comment by njss** [comment]
Hi @retorquere,

I've generated the log as you suggested.
The only error on the log file was related to lack of space in the cloud storage of zotero.
After executing this command, Zotero started to work just fine, every time.
No idea what happened. I am not authorized to share the log file, there is just too much private information on it.
However I am happy again, everything works just fine.

Thank you.

**Comment by retorquere** [comment]
I understand. I don't like these transient errors, but if there is nothing in the logs, there's nothing that can be done. Feel free to open a new issue should it recur.
