### ISSUE TITLE
Initializing forever

### ISSUE THREAD

**Issue by MNCLorena** [retorquere/zotero-better-bibtex#1865]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT support log from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Support log ID:**
How do I get this?
**Expected behavior:**
I have uninstalled and installed better bibtex many times and the issue doesn't resolve. It used to work before but now it stopped working. I have around 2000 references in Zotero. The Bibtex preferences don't even appear to me. (See image below)
**Actual behavior:**
![image](https://user-images.githubusercontent.com/71108559/124131824-8ba7ba80-da56-11eb-8d4b-76bd2a667bd0.png)

**Comment by MNCLorena** [comment]
D1244476882

**Comment by retorquere** [comment]
Can you do the following:

* install https://github.com/retorquere/zotero-debug-log
* restart Zotero with debug logging enabled from the `Help menu`
* Select `Send debug log to file.io` from the `Help` menu
* Paste the log ID from the popup here

**Comment by MNCLorena** [comment]
7tbnFitVyYFB-4XKVNHJV

**Comment by MNCLorena** [comment]
Hi, I installed it. Nothing changed.

**Comment by retorquere** [comment]
Can you then get me a new file.io log?

**Comment by MNCLorena** [comment]
mNKgOxygRtAN-P9XL2BR2

**Comment by retorquere** [comment]
Sorry about the disruption. It's to do with code that's not used often, on Windows. New build incoming.

You're getting a lot of "out of storage" errors BTW from a running sync.

**Comment by MNCLorena** [comment]
Thanks about the storage info (I dont want to buy extra storage, so I just sync myself - not sure how to disable this). 
I am using in Windows. Should I wait for a new update? Did you find the problem? Thank you for such fast verifications!! I have been trying to solve it on my own for a while.

**Comment by retorquere** [comment]
> I am using in Windows. Should I wait for a new update?

I won't be able to fix it without your help -- I don't have access to a Windows system currently.

> Did you find the problem?

I found *a* problem, fixed that, but then found another. 1153 should fix the second and hopefully the last problem for you.

> Thank you for such fast verifications!! I have been trying to solve it on my own for a while.

No need, it's always OK to ask for help here.

**Comment by MNCLorena** [comment]
It worked!! Thank you very much!! =)

**Comment by retorquere** [comment]
Super -- thanks for the quick turnaround. You can keep 1153, it will be upgraded to the next release automatially; a new release that has the current fix will go out somewhere before next Monday. You can uninstall the separate debug-log extension.
