### ISSUE TITLE
Exclude/Include items in export based on condition (via script?)

### ISSUE THREAD

**Issue by janosfoeth** [retorquere/zotero-better-bibtex#1866]
Hi, I've got some feature/enhancement request or request for help with scripting:

I would like to define which items get exported by specific conditions on fields of the item. For example I want to exclude some items from the export based on a condition e.g. a specific tag set on the item. Respecively the other way arround I just want to include items with a specific tag in the export.

I didn't find any feature for this. Maybe it is possible via scripting but the [examples in the Docs](https://retorque.re/zotero-better-bibtex/exporting/scripting/) didn't contain anything to remove the whole item from export - just how to modify it / the reference.

Background: I assign a specific tag to items that I reviewed and that are ready to be cited, as well as I assign another tag to items that I definitely don't wont to cite (but keep in my library for completeness, e.g. some sketchy web ressources). This feature would help me to keep my bib file clean: just containing ready-to-cite items.

Is there any way to accomplish this?

Thanks in advance! - Let me know if you need more information.

**Exporter used:** Biblatex

**Expected behavior:** Set a specific tag on items. These item get included / excluded in export based on rules I defined.

**Actual behavior:** I didn't find a way to do this.

**Comment by janosfoeth** [comment]
Here is the support log key: 576BVWIJ-refs-euc
I included items with some tags, however I think it's not necessary for my issue.

**Comment by retorquere** [comment]
You can issue `return { write: false }` in the postscript and then that item will not be written to the output. If you get me a debug log per point 1. I can create a full postscript for you.

**Comment by janosfoeth** [comment]
Wow thanks for replying that quick!
I submitted a support log. The tags I use are 'nocite' and 'bibchecked'.

**Comment by janosfoeth** [comment]
ok.. you provided the script snippet faster than I could answer! Big thanks!

**Comment by janosfoeth** [comment]
Seems like I rushed by saying it solved my issue.
Actually I can't get it to work. Even if I just use the following code snippet
```
if (Translator.BetterTeX) {
  return { write: false };
}
```
it still exports everything (instead of nothing, which I suspect should be the case).
I submitted another log if this helps: `T4JDC9F2-refs-euc`

**Comment by retorquere** [comment]
Apologies -- this functionality is in a release I'm prepping for this weekend.

**Comment by janosfoeth** [comment]
Thanks. I installed it and restarted Zotero, but it's stuck at
![image](https://user-images.githubusercontent.com/22803606/124177282-4b752600-dab0-11eb-8932-658bc8c39890.png)
I'm also not able to send another log via Help -> Send Better BibTex support log (nothing happens).
I think I'll downgrade (somehow?) and wait for the official release.

**Comment by retorquere** [comment]
Can you do the following:

* install https://github.com/retorquere/zotero-debug-log
* restart Zotero with debug logging enabled from the `Help menu`
* Select `Send debug log to file.io` from the `Help` menu
* Paste the log ID from the popup here

**Comment by retorquere** [comment]
If you downgrade and wait then that bug is going to be in the next release -- I don't have it, or my tests would not have passed.

**Comment by janosfoeth** [comment]
Definitely makes sense.
Log ID: 3HbM2YY7zgM0-XQRXUN84

**Comment by retorquere** [comment]
Found it. Build should drop in 10 minutes when the tests pass.

**Comment by retorquere** [comment]
If this works you can keep it, and uninstall the separate debug log extension. I'll probably cut a new release with this fix Sunday at the latest. There's one more fix I would prefer to have in.

**Comment by janosfoeth** [comment]
Works like a charm! Thanks for the great support and ultra quick bugfixing 😊

**Comment by retorquere** [comment]
Super thanks for helping suss this last one out!

**Comment by janosfoeth** [comment]
Just to add my final solution to the initial problem - if anyone finds this and is curious:

Targets:
1. I tag items with `nocite` that I dont won't to export (they won't get exported to bib file -> I won't accidentally cite them).
2. Before the final release of my work, I only want to have items with tag `bibchecked` in my exported bib file as these are the references I checked carefully.

This is now (/with the upcoming release resp.) possible with the following code:
```
if (Translator.BetterTeX) {
  state = true
  // return only items with tags != nocite:
  state = state && !item.tags.find(tag => ['nocite'].includes(tag.tag));
  // return only bibchecked items (comment/uncomment if needed):
  state = state && item.tags.find(tag => ['bibchecked'].includes(tag.tag));
  // return state:
  return { write: state }
}
```
I can adjust the behaviour by commenting/uncommenting the respective line for the `bibchecked` tag.

**Comment by retorquere** [comment]
Understandable; this will be slightly faster:

```
if (Translator.BetterTeX) {
  state = true
  // return only items with tags != nocite:
  state = state && !item.tags.find(tag => tag.tag === 'nocite');
  // return only bibchecked items (comment/uncomment if needed):
  state = state && item.tags.find(tag => tag.tag === 'bibchecked');
  // return state:
  return { write: state }
}
```
