### ISSUE TITLE
`# of Pages` gets exported as `annotation` instead of as `pagetotal`

### ISSUE THREAD

**Issue by qak** [retorquere/zotero-better-bibtex#1867]
I have an item of type _Report_ in Zotero with field `# of Pages: 16`. This item gets exported as
```
@report{morton1966a,
  title = {A Computer Oriented Geodetic Data Base; and a New Technique in File Sequencing},
  author = {Morton, G. M.},
  date = {1966-03-01},
  institution = {{International Business Machines Co. Ltd.}},
  location = {{Ottawa, Ontario, Canada}},
  url = {https://domino.research.ibm.com/library/cyberdig.nsf/0/0dabf9473b9c86d48525779800566a39},
  urldate = {2021-06-30},
  annotation = {\# of Pages: 16},
  langid = {canadian},
  type = {Research report}
}
```
using the Better BibLaTeX exporter. The number of pages is getting incorrectly exported as `annotation = {\# of Pages: 16}` but it should be exported as `pagetotal = {16}`. The support log ID: `QPXXF7TP-refs-euc`.

It seems that this issue doesn't happen for all item types though. I can see that the `pagetotal` field gets correctly exported by the Better BibLaTeX exporter for fields of type _Book_ and _Thesis_.

**Comment by retorquere** [comment]
I can add `# of pages` as an alias, but the [currently supported form](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) is `number of pages`.

**Comment by retorquere** [comment]
TBH I'm not sure how it does actually work for some types. That must be Zotero moving it into the item at time of export for some types.

**Comment by qak** [comment]
> I can add `# of pages` as an alias, but the [currently supported form](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) is `number of pages`.

Oh I see, I didn't realise BBT expects `number of pages`. I'm using `# of Pages` because this is what Zotero [uses](https://www.zotero.org/support/kb/item_types_and_fields) for some item types (e.g. types _book_ and _thesis_). Changing `# of Pages: 16` to `Number of Pages: 16` exports `pagetotal = {16}` as expected.

> TBH I'm not sure how it does actually work for some types. That must be Zotero moving it into the item at time of export for some types.

For the types I've mentioned (book and thesis), Zotero offers a field titled `# of Pages`. For the reported item I manually entered `# of Pages: 16` (or `Number of Pages: 16`) into Zotero's `Extra` field. I just didn't expect BBT to expect a slightly different field name.

I guess the issue now boils down to 'Is it correct for BBT to expect `Number of Pages` if Zotero uses `# of Pages`?'. It's not going to be an issue for me any more as I'll just refer to the 'extra fields supported by BBT' page you've linked in the future, but I guess there's a nonzero probability of somebody else getting caught out by the naming inconsistency in the future. I'll leave it up to you if you'd prefer to keep things as is or if you'll add an alias for `# of Pages`.

**Comment by retorquere** [comment]
I'll look into the aliases; the label in the list on the BBT page is the internal (English) name mapping to a variable name or the csl name; Zotero doesn't actually always use `# of pages` for that field, it will be one of

* `# a bajennoù`
* `# av sider`
* `# de páginas`
* `# di Pagine`
* `# halaman`
* `# lk`
* `# of Pages`
* `# sidor`
* `# stran`
* `# síður`
* `#ページ`
* `Aantal pagina's`
* `Antal sider`
* `Anzahl der Seiten`
* `Liczba stron`
* `N.º de Páginas`
* `Nb de pages`
* `Nr. de pagini`
* `Nre. de pàgines`
* `Nº de Páxinas`
* `Número de páginas`
* `Počet strán`
* `Puslapių kiekis`
* `Sayfa Sayısı`
* `Sivumäärä`
* `Tal sider`
* `Terjedelem`
* `orr.kopurua`
* `Št. strani`
* `Брoj страница`
* `Кільк. сторінок`
* `Число страниц`
* `брой страници`
* `تعداد صفحه`
* `عدد الصفحات`
* `จำนวนหน้า`
* `លេខទំព័រ`
* `总页数`
* `頁數`
* `총 페이지수`

and I don't know whether zotero will treat `# lk: 16` the same, or always, or depending on current Zotero locale.

**Comment by retorquere** [comment]
Anyhow, I'll get a test build going later today and that will also show whether there are label conflicts.

**Comment by retorquere** [comment]
Doesn't look like Zotero supports any form of `# of Pages: 16` when rendering a bibliography in word/libreoffice BTW, not even `number-of-pages: 16`, which is the CSL notation, and Zotero uses the CSL as one of the ways of entering `extra` fields.

**Comment by njbart** [comment]
`number-of-pages: 16` in the Extra field does work (try `vancouver.csl` and a “Book” item), it’s just that very few styles actually support it.

**Comment by retorquere** [comment]
But that won't work with `# of Pages` I reckon. If there's no label clashes I don't mind adding all translations as aliases, but if there are I'm not going to deal with the ambiguities.

**Comment by qak** [comment]
> But that won't work with `# of Pages` I reckon. If there's no label clashes I don't mind adding all translations as aliases, but if there are I'm not going to deal with the ambiguities.

Now that I'm thinking of it, adding all translations as aliases might create more inconsistencies that it'll resolve. Let's say that you add `# of Pages` and its translations as aliases for `Number of Pages`. What about BBT's `Number of Volumes` extra field, should this one be aliased to `# of Volumes` and its translations too? I guess that `Number of Pages` and `Number of Volumes` aren't the only fields [here](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) that can differ between BBT and Zotero. The result might be that BBT will seemingly unpredictably support non-English item fields in some cases an English-only fields in other cases. I think it might be simpler and more consistent to let Zotero support translations of the officially supported fields and let BBT support only English field names. It's not like BibTeX or BibLaTeX support non-English field names either. Keep in mind that when I reported this issue then I had no idea about the [list](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) you've linked (I probably saw it long ago and forgot about it).

**Comment by njbart** [comment]
Actually I’m not aware of *any* translations of field names being supposed to work here. Zotero’s documentation (https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra) only lists the official CSL variable names plus their “prettified” versions, i.e., without hyphens, and possibly capitalized.

**Comment by retorquere** [comment]
All of those will work in BBT, plus all prettified versions of Zotero internal fields, as there are plenty fields that don't have a CSL equivalent.

**Comment by retorquere** [comment]
> Now that I'm thinking of it, adding all translations as aliases might create more inconsistencies that it'll resolve. Let's say that you add # of Pages and its translations as aliases for Number of Pages. What about BBT's Number of Volumes extra field, should this one be aliased to # of Volumes and its translations too?

Effectively I'd have to add all of [these](https://gist.github.com/cdafc3a6f525df1977ecb41bc664feeb). The list is so long I can't paste it here, and none of these are supported by Zotero itself.

**Comment by retorquere** [comment]
All fields that are supported by Zotero are supported by BBT in all the formats that Zotero supports (some Zotero labels, and the standard and prettified versions of CSL fields) and mean the same in BBT. BBT supports more fields -- all fields that Zotero's internal model allows, even if the cite engine from Zotero won't pick them up.

**Comment by retorquere** [comment]
> only lists the official CSL variable names plus their “prettified” versions, i.e., without hyphens, and possibly capitalized.

BBT supports all of these, and the key is tested case-insensitively -- `number of pages: 16` == `NUMBER of PaGeS: 16` as far as BBT is concerned.

**Comment by retorquere** [comment]
> Now that I'm thinking of it, adding all translations as aliases might create more inconsistencies that it'll resolve. 

I haven't checked, but if among the translations there is a label in two languages that translate to different variables, that would be a showstopper, and I'd not add any of the translations.

**Comment by retorquere** [comment]
I can't add these translation-aliases. `pt-BR` adds `Editor` as a label for `publisher` (a text field) where elsewhere `editor` is a creator-type field. That would mean that if you enter `Editor: X` on an English Zotero and sync it to a `pt-BR` Zotero, the meaning of that line would change. That's not acceptable.

I'm open to suggestions on how to best document what can be used for these fields.

**Comment by qak** [comment]
> I'm open to suggestions on how to best document what can be used for these fields.

I've read through BBT's documentation and I think that everything is explained properly, it's just that I didn't RTFM enough. The documentation clearly [states](https://retorque.re/zotero-better-bibtex/exporting/#csl-fields) that fields in `Extra` should be CSL variables and there's even a link to the CSL specification there. Everything is further explained in [here](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) too. As it turns out, even Zotero's documentation [mentions](https://www.zotero.org/support/kb/item_types_and_fields#citeable_fields_not_included_in_zotero) that `Extra` should contain CSL variable names (and therefore not necessarily the field names displayed by Zotero itself), which I hadn't fully realised until now. I think this issue can be closed now. Thanks for taking the time to thoroughly investigate this issue though.

**Comment by retorquere** [comment]
Mind that I'd never say RTFM -- BBT's behavior can be surprisingly complex, so it's always OK to ask.
