### ISSUE TITLE
Cannot add custom BibTeX Field

### ISSUE THREAD

**Issue by moffat** [retorquere/zotero-better-bibtex#1872]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT support log from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Support log ID:**

**Exporter used:**

**Expected behavior:**

I"m trying to add a "Status: in preparation" field to a "Journal Article" item so that it shows up in the exported BibTeX file. I believe, according to [this support page](https://retorque.re/zotero-better-bibtex/exporting/) that the way to do this is to add:

```
Status: in preparation
``` 

in the "Extra" field of the Zotero item. However, this doesn't work.

**Actual behavior:**

The bibtex entry for the item in question does not change.

**Comment by retorquere** [comment]
If it's only for bibtex exports, try adding `tex.status: in preparation` to the `extra` field. `Status` isn't a know Zotero or CSL field, so there's no mapping for it. With the `tex.` prefix you tell BBT to just add that field as-is.

**Comment by moffat** [comment]
Thanks, that worked.
