### ISSUE TITLE
Use creator in extra field when there's no creator in the usual places?

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#1873]
### Discussed in https://github.com/retorquere/zotero-better-bibtex/discussions/1871

<div type='discussions-op-text'>

<sup>Originally posted by **Jmuccigr** July 13, 2021</sup>
I've [just discovered](https://forums.zotero.org/discussion/comment/386724#Comment_386724) that Zotero has no "editor" option for the creator of a web page, but the usual "cheat" of putting one into the extra field works fine. However BBT seems to want nothing to do with using that field to create a cite key. I put `[extra=editor:lower][year][0] | [auth:(unknown)][year][0]` in the format, and it ignores the editor field. If I use another name for it, like "blah" or tex.editor, it works fine. Of course that also means that Zotero no longer recognizes it as a creator and so it won't end up in the exported citations.

There's also the issue of the format Zotero needs for names there, that is "Last || First", which I suppose I could handle with regex so BBT doesn't process the whole thing.

Am I missing the proper way to do this?</div>

**Comment by retorquere** [comment]
@Jmuccigr I hadn't thought to use these names for key generation. If you could right-click such an item and send a support log from the popup menu, I can make it work.

**Comment by Jmuccigr** [comment]
> 🤖 this is your friendly neighborhood build bot announcing [test build 5.4.25.1203](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.4.25.1203.xpi) ("fixes #1873")
> 
> Install in Zotero by downloading [test build 5.4.25.1203](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.4.25.1203.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

Yep, this seems to work for me with my format string...as long as I don't have a date. Once I insert one, it does the "unknown" thing.

But if I change the format to remove the date with the editor: `[extra=editor:lower][0] | [auth:(unknown)][year][0]`, then it will work with the date and also insert it after the editor name, which doesn't seem consistent with the format (though maybe I'm not understanding how the format works). Also, if I change the format string back to include the date part, the key now includes the date (but still not the editor).

I submitted two logs, changing the format string in between:

Log without the date in the format: CACCRLN6-refs-euc
Log with the date in the format: 2UFBHLIC-refs-euc

PS The log message refers to a "Next" button, but it's "Continue" on my Mac.

**Comment by Jmuccigr** [comment]
OK, figured something out. The | seems only to affect the first element in the format string, so if I use `[extra=editor:lower] | [auth:(unknown)][year][0]` all is well. That doesn't seem to jibe with the documentation.

**Comment by retorquere** [comment]
With build 1203 you can use `[edtr:lower][year][0] | [auth:(unknown)][year][0]` rather than `[extra=editor:lower][year][0] | [auth:(unknown)][year][0]`. `editor` isn't one of the recognized fields by the `extra` function -- it only knows about the ones listed [here](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/), but that wasn't on the site yet I see. I've scheduled an update of the site to add that link. That list has "simple fields" -- basically, those fields that are a single line of text in Zotero. `editor` is a creator-type field and those can appear multiple times, they're treated differently, but they weren't previously picked up by `auth` and `edtr` and so on. 1203 fixes that.

> OK, figured something out. The | seems only to affect the first element in the format string, so if I use [extra=editor:lower] | [auth:(unknown)][year][0] all is well. That doesn't seem to jibe with the documentation.

The `|` means "if the preceding pattern did not generate any output, proceed to the next pattern". Since the date generates output, the pattern is accepted. You could use something like `[edtr:lower][>0][year][0] | [auth:(unknown)][year][0]` where the `[>0]` means "if there is no output at this point, skip to the next pattern".

**Comment by Jmuccigr** [comment]
> > OK, figured something out. The | seems only to affect the first element in the format string, so if I use [extra=editor:lower] | [auth:(unknown)][year][0] all is well. That doesn't seem to jibe with the documentation.
> 
> The `|` means "if the preceding pattern did not generate any output, proceed to the next pattern". Since the date generates output, the pattern is accepted. You could use something like `[edtr:lower][>0][year][0] | [auth:(unknown)][year][0]` where the `[>0]` means "if there is no output at this point, skip to the next pattern".

No, what I mean is that if I have the format as `[extra=editor:lower] | [auth:(unknown)][year][0]`, I get the year in the citekey when there's an editor in the extras (and no author) even though there's no year in the first part of the format. But in fact [extra=editor] doesn't work at all, but now [auth:(unknown)][year][0] by itself now works just fine and will grab the author if there is one, then the extra editor, if there is one.

One more thing, there was a brief a difference between Editor and editor (initial cap), where the former resulted in a pinned cite key, the latter did not, but that seems to have stopped.

**Comment by retorquere** [comment]
It's a little confusing because both `CACCRLN6-refs-euc` and `2UFBHLIC-refs-euc` have pinned citekeys, which will always take precedence. The pinned key in `2UFBHLIC-refs-euc` has only a year, and as long as that line is present, it doesn't matter what your pattern is set to. If there is a `Citation Key:` line in the `extra` field, BBT will always take that verbatim, and will not use the generator.

Can you remove the `Citation Key:` line from `extra`, send a new log, and describe what you see happening that you don't want to there?

**Comment by retorquere** [comment]
There should not be a difference between `editor:` and `Editor:`, and that hasn't changed in a very long time. If you see a difference, please open a new issue for that.

**Comment by retorquere** [comment]
Oh wait, you have autopin on.

**Comment by retorquere** [comment]
OK, so with no authors, a date of `1999`, and only `editor: Darwin || Charles` in the `extra` field:

**`[extra=editor:lower][year][0] | [auth:(unknown)][year][0]`** yields `1999`.

`[extra=editor]` does not yield any output, because `extra=` only does single-line fields, and `editor: ...` is a (potentially) multi-line field, as there can be more than one `editor: ` line. But `[year]` does yield output, so BBT never gets to the 2nd pattern.

**`[extra=editor:lower][0] | [auth:(unknown)][year][0]`** yields `Darwin1999`.

Because there is no output from the first pattern as the year is no longer present, BBT moves on to the next. There it finds `[auth]`, that will take authors if it can find any, and if not, will take  the first of editors, translators, collaborators that are present. With 1203, `editors:` is recognized and used as "native" creators are, so it will find `Darwin` through the fallback, uses that, and adds the year.

Documentation was at least incomplete for this behavior, and when I merge 1203 that will also update the docs, but the behavior of ` | ` is consistent.

**Comment by Jmuccigr** [comment]
> Oh wait, you have autopin on.

I do, and when I test I use the “unpin citation” menu item to get it to redo the cite key. Seems to work. Let me know what I can test.

**Comment by retorquere** [comment]
> > Oh wait, you have autopin on.
> 
> I do, and when I test I use the “unpin citation” menu item to get it to redo the cite key. Seems to work. Let me know what I can test. 

That's fine. Does your experience match either of the scenarios above (because those are in-spec and aren't likely to going to change)? If not, I'd need you to set up the scenario you have in mind, try to regenerate the key, and then send a new log for that item.

**Comment by Jmuccigr** [comment]
OK, a few things:

Most importantly, my current format string is `[auth:(unknown)][year][0]` which seems to behave the way I want, i.e., it grabs an editor in the extra field.

>> No, what I mean is that if I have the format as [extra=editor:lower] | [auth:(unknown)][year][0], I get the year in the citekey when there's an editor in the extras (and no author) even though there's no year in the first part of the format.

> I cannot reproduce this behavior with 1203. Can you set this up and send a new log for it?

To be clear on this, the first part, `[extra=editor:lower]`, just doesn't seem to work at all. The log for that all by itself as the format is VDFKK8GZ-refs-euc.

Now, I'll add the second part to get this format, `[extra=editor:lower] | [auth:(unknown)][year][0]`, which works fine: 99PKAZYH-refs-euc

Finally with just the second part, `[auth:(unknown)][year][0]`: UWIXSAFW-refs-euc. So it seems pretty clear that the extra field isn't working for me in the format.

In each case I'm unpinning the cite key, which seems to delete it and then BBT re-creates it. I'm not quite sure I understand what you've written above about extra only doing single-line fields. Perhaps it's that pinning the citekey results in multi-line extra fields?

**Comment by retorquere** [comment]
> Most importantly, my current format string is `[auth:(unknown)][year][0]` which seems to behave the way I want, i.e., it grabs an editor in the extra field.

That's what 1203 and later have added. `[edtr]` and `[auth]` will now find creator-type lines in the `extra` field.

Long story short: `[edtr:lower][0] | [auth:(unknown)][year][0]` should get you what you want.

The rest is just my attempt to explain BBTs behavior, which wrt the extra field is fairly complicated. I'm in the process of creating a visual guide through this labyrinth, which I'll put up on the site when done, but it's slow going.

> To be clear on this, the first part, `[extra=editor:lower]`, just doesn't seem to work at all. The log for that all by itself as the format is VDFKK8GZ-refs-euc.

I think my attempts to explain how extra-field handling works have muddied things. `[extra=editor]` will never generate output, and that's by design. During key generation, BBT makes a copy of the `extra` field and does the following (all on a copy of the item, not the actual item, so these don't actually change the item you see in Zotero):

1. lines that can be recognized as Zotero creator-type fields are added to the creators list, and are removed from `extra`
2. lines that can be recognized as a Zotero non-creator-type field that is not multi-line (so `extra` and `abstract` are excluded) are taken as fallbacks for missing fields, and removed from `extra`

"fallback" here just means that if you have a `DOI` field filled out in the item, and a `DOI: bla bla` in the extra field, that is stripped and ignored, because Zotero GUI fields take precedence, but for items where you haven't filled the `DOI` field or the item type doesn't have a `DOI` field, this value is used as the item's DOI.

So an `extra` field that looks like

```
editor: Darwin || Charles
publisher: me
doge: much wow
```

will leave the key generator with this setup wrt the data in `extra`

```
creators: [
  { firstName: 'Charles', lastName: 'Darwin', type: 'editor' }
]
fallback:
  publisher: me
remainder:
  doge: much wow
```

the `extra=` function *only* gets values from `fallback` and `remainder`, so `[extra=editor]` will never generate output, as it is claimed as a creator-type. This was already the case before 1203 as it is just the work that the extra-parser does before key generation. 1203 and later likewise strip the extra field, but makes the stripped data available to key generation.

What you can do instead (post-1203) is `[edtr:lower][0] | [auth:(unknown)][year][0]`

> In each case I'm unpinning the cite key, which seems to delete it and then BBT re-creates it. I'm not quite sure I understand what you've written above about extra only doing single-line fields. Perhaps it's that pinning the citekey results in multi-line extra fields?

No, I was trying to explain rule 1/2 above -- I shouldn't have mentioned the key pinning, I mentioned that because I said before that "your keys are pinned, that takes precedence" and then realized you had not manually pinned them to stay that way. Anyhow, `editor` is treated as creator-type; even if it weren't, it couldn't play the same role as `publisher` and `doge` above, as this is a valid scenario:

```
editor: Darwin || Charles
publisher: me
editor: Wallace || Alfred Russel 
doge: much wow
```

so it's not clear what the return value should be for `[extra=editor]` as there are multiple lines that would match. The `auth` and `edtr` functions can deal with multiple creator-type values, and they will now also find the creator-type fields in the `extra`, in addition to the regular creator-type fields Zotero offers in the GUI.

I'm truly sorry that `extra` field handling is so complicated, but it's just simply complicated. Zotero has planned to add more "real" fields in the GUI (e.g a DOI on all item types) and as these are added, the `extra` handling should become less and less necessary. [This](https://github.com/retorquere/zotero-better-bibtex/issues/1862#issuecomment-870368091) shows a small part of the mapping process, that's going to be cleaned up and part of the visual guide, but the actual graph is much larger.

**Comment by retorquere** [comment]
Is your issue resolved with `[edtr:lower][0] | [auth:(unknown)][year][0]` on 1203?

**Comment by Jmuccigr** [comment]
> Is your issue resolved with `[edtr:lower][0] | [auth:(unknown)][year][0]` on 1203?

I'm good with just the auth part. Thanks for the help.

(Sorry for the delay - traveling)
