### ISSUE TITLE
Bare year export

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#1874]
@njbart any opinion on `year = 2021` vs `year = {2012}` for bibtex? Or `date = 2021` for biblatex?

Support log ID:

**Comment by njbart** [comment]
Seems to be permitted. On bibtex: “For numerical values, curly braces and double quotes can be omitted” (http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf). WRT biblatex, all of the year-only `date` fields in https://github.com/plk/biblatex/blob/dev/bibtex/bib/biblatex/biblatex-examples.bib seem to be bare (unlike the `date` fields containing additional elements, though). 

But what’s wrong with including the braces?

**Comment by retorquere** [comment]
Nothing, mainly curious.
