### ISSUE TITLE
citation key format nopunctordash filter list

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#1880]
Where does `nopunctordash` get its filter strings from? I just realized that the character `─` commonly used as a CJK dash is not filtered. 

A quick hack would be to add `─` to the skipwords list, but it makes the list messy. 

**Support log ID:**
BS2NMUCX-refs-apse

**Expected behavior:**
Filter out `─` from citekey with `nopunctordash` in `Title`.

Citation key format settings:
`[Auth]_[Title:nopunctordash:jieba:skipwords:capitalize:select=1,3]_[year]`

**Actual behavior:**

`─`  not filtered out in citekey.

**Comment by retorquere** [comment]
punctuation is anything that matches character classes `Pe`, `Pf`, `Pi`, `Po` or `Ps`, dash is anything that matches character class `Pd` (and I'm adding `Pc`, which I had overlooked).

This character is [Box Drawings Light Horizontal](https://www.compart.com/en/unicode/U+2500), which is from character class Other Symbol; I can't include this character based on it's character class. So the only option I have would be to include it specificallly. Which I don't mind doing, but yes, it would be a sort of hack.

**Comment by sati-bodhi** [comment]
Wow, I never realized that. 

I think many Chinese IMEs use this character in place of the EM DASH and TWO EM DASH either out of ignorance or as a hack for certain fonts to display that symbol properly. 

Since I can customize my own IME, I'll replace the character with the more formal EM DASH, which is recognized as such and filtered out by your code.

**Comment by retorquere** [comment]
I mean... these drawing chars have no sensible interpretation other than use as pseudo characters. I might as well treat it as a dash, certainly if this is the default behavior for some IMEs.

**Comment by sati-bodhi** [comment]
That should be good, too!
If that's the case, you should take note of the and Hyphen-minus (U+FF0D),  Horizontal bar (U+2015). They are also commonly used in place of the EM DASH, according to [Wikipedia](https://zh.wikipedia.org/wiki/破折号).

**Comment by retorquere** [comment]
Can you try build 1286?

**Comment by sati-bodhi** [comment]
1313 worked as expected. Thank you!

**Comment by retorquere** [comment]
Super, thanks, that will go into the upcoming update.
