### ISSUE TITLE
Start with minimized commandline-windows on automated `git push` on export 

### ISSUE THREAD

**Issue by JoschD** [retorquere/zotero-better-bibtex#1881]
Hey,
I have a small problem with the automated git export (which is absolutely amazing, like everything about this extension) on Windows:
The git command opens commandline-windows (even though only for a few seconds) that grab the cursor focus. In combination with the fact that the "export on idle" function is sometimes triggered even when I am still typing into Zotero, this is very annoying.

Would it be possible to start these windows minimized/out-of-focus? Or maybe I can modify the command somewhere myself?

Thank you very much!

**Comment by retorquere** [comment]
You can ignore label gun in this issue

**Comment by retorquere** [comment]
Can you try build 1319?

**Comment by JoschD** [comment]
Hey, looking good! 
During the export there is no terminals popping up and the file is still pushed to overleaf!

Thank you very much! I've seen it was a highly complicated fix ;) 
I'm not sure if I would be using Zotero without your extension. It makes things so much easier! :)

**Comment by retorquere** [comment]
You're welcome :) I had this fix lined up but forgot to activate it when zotero upgraded to a compatible Firefox.

**Comment by JoschD** [comment]
Is it on me to close the issue? I think it can be closed. :)

**Comment by retorquere** [comment]
Nope, that's on me, but thanks for asking!
