### ISSUE TITLE
Auto-export overview in prefs cuts off delete button on Linux

### ISSUE THREAD

**Issue by hongyi-zhao** [retorquere/zotero-better-bibtex#1884]
On Ubuntu 20.04, I'm using the latest stable version of `Zotero` and `zotero-better-bibtex`, and I want to update the exported bibliography entries immediately after an entry has been added into `Zotero` each time. For this purpose, I use the 
`inotifywait` tool to monitor `$HOME/Zotero/zotero.sqlite` for some events, say, `modify`. But the problem is some bibliographies also have notes and associating files which will result in multiple triggering of observation events for each bibliography, as a result, the exporting operation will run multiple times after such a  bibliography entry has been added into `Zotero`. In order to solve this problem, I additionally calculate the md5sum of all citation keys as following, and only execute the export operation when this md5sum is changed.
 
```shell
#!/usr/bin/env bash
zotero_sqlite=$HOME/Zotero/zotero.sqlite
better_bibtex_export=$HOME/Documents/bibliograph/better-bibtex
bibtex_filename=$better_bibtex_export/references-bibtex.bib
biblatex_filename=$better_bibtex_export/references-biblatex.bib
while read _
do
  if [[ $citation_key_md5sum != $(curl -s "http://127.0.0.1:23119/better-bibtex/export/library?/1/library.bibtex"  | grep '^\@' | sort | md5sum | cut -d ' ' -f1)  ]]; then
    #echo "Changes are observed."
    citation_key_md5sum=$(curl -s "http://127.0.0.1:23119/better-bibtex/export/library?/1/library.bibtex"  | grep '^\@' | sort | md5sum | cut -d ' ' -f1)
    curl -s "http://127.0.0.1:23119/better-bibtex/export/library?/1/library.bibtex" -o $bibtex_filename
    #curl -s "http://127.0.0.1:23119/better-bibtex/export/library?/1/library.biblatex" -o $biblatex_filename
  fi
done < <(inotifywait --quiet --monitor --event MODIFY $zotero_sqlite)
```
Though the above method works, but it seems cumbersome. Is there any more concise and elegant way to accomplish this task?

Regards,
HY

Support log ID:

**Comment by retorquere** [comment]
Why not just set up a BBT auto-export?

**Comment by hongyi-zhao** [comment]
I'm not familiar with `JavaScript`. Although I've read the documentation [here](https://retorque.re/zotero-better-bibtex/exporting/scripting/), but I still failed to figure out the `JavaScript` code corresponding to my above shell script.

**Comment by retorquere** [comment]
> I'm not familiar with `JavaScript` and `TypeScript`. Although I've read the documentation [here](https://retorque.re/zotero-better-bibtex/exporting/scripting/), but I still failed to figure out the code corresponding to my above shell script.

No need for either of those. Export the collection/library you are interested in using the Better BibTeX or Better BibLaTeX exporter, and check the "keep updated" option. That export will then show up in the place you screenshotted above. From that point on, Zotero will just update the bib file whenever any of the items in that collection/library change/get added/deleted.

**Comment by hongyi-zhao** [comment]
> and check the "keep updated" option.

I can't find the above option:

![image](https://user-images.githubusercontent.com/11155854/128584992-2a4ab819-bad1-4281-b68a-07eb603b4451.png)

**Comment by retorquere** [comment]
You need to select "Better BibTeX", not "BibTeX", but in this screenshot the red message that would usually alert you to that fact is missing

<img width="366" alt="Screenshot 2021-08-07 at 04 59 59" src="https://user-images.githubusercontent.com/132108/128585855-ae496769-18c9-4d1b-b2a9-38c030f1796e.png">

which would indicate there is some kind of error preventing a proper load of BBT.

**Comment by hongyi-zhao** [comment]
Thank you very much. Got it. As shown in the screenshot below:

![image](https://user-images.githubusercontent.com/11155854/128586786-4a18d59e-5e77-47ef-9823-57a610e7afc0.png)

**Comment by hongyi-zhao** [comment]
This is a great feature, but I still want to know if there is a script-based way to enable/use it?

**Comment by retorquere** [comment]
That the glee button doesn't show must be Linux-specific, I'll see gaat I can do about that.

Script-based in what sense? Shell script? What would you want to be able to do through shell scripting?

**Comment by retorquere** [comment]
Can you test whether build 1284 shows the delete button for the auto-export?

**Comment by hongyi-zhao** [comment]
Still failed to show the delete button for the auto-export:

![image](https://user-images.githubusercontent.com/11155854/128617519-ddd62078-3604-4b07-96e9-478a71462934.png)
![image](https://user-images.githubusercontent.com/11155854/128617549-397882d6-f925-4b77-905e-b2f9c37b8d80.png)

**Comment by hongyi-zhao** [comment]
> Script-based in what sense? Shell script? What would you want to be able to do through shell scripting?

I mean more flexible control and communicate with BBT from within *nix CLI or Emacs.

**Comment by retorquere** [comment]
What *specifically* do you want to be able to do? "More flexible" doesn't tell me what you are missing right now. If you want fully flexible, you  can install the [debug bridge](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge) and you can do whatever you want with all of Zotero. There's also a few [JSON-RPC commands](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/) you can send BBT. If those two don't cover your needs, you are going to have to be more specific.

I'll get you a fix for that button missing later this afternoon when I get home.

**Comment by hongyi-zhao** [comment]
> What _specifically_ do you want to be able to do?

I describe this requirement in detail as follows:

I use `zotero-better-bibtex` and also use [eBib-Biblio based method](http://juanjose.garciaripoll.com/blog/ebib-biblio-interface/index.html) as the bibliography database manipulation/building/management workflow with Emacs. For `zotero-better-bibtex` the `bib(la)tex` files are exported from zotero, while for [ebib](https://github.com/joostkremers/ebib) and [biblio.el](https://github.com/cpitclaudel/biblio.el), the `bib(la)tex` files are created directly. Now, I want to let `zotero-better-bibtex` and `ebib`/`biblio.el` use the same `bib(la)tex` files with the following collaboration and interoperability:

1. When I modified the `bib(la)tex` files through `ebib`/`biblio.el`, they should be imported into the corresponding `zotero` collection library. 
2. When I modified the `zotero` collection library, the corresponding `bib(la)tex` files should be updated immediately, which can be done by the feature discussed in this issue.
3. For the entries generated by `ebib`/`biblio.el`, use the citation key generation rule of `BBT` to maintain the consistency.

> I'll get you a fix for that button missing later this afternoon when I get home.

Thank you very much for your wonderful work.

**Comment by hongyi-zhao** [comment]
Another thing that really surprised me is it seems that zotero and BBT don't store their prefs in `~/.zotero/` or `~/Zotero/`.

**Comment by retorquere** [comment]
> * When I modified the `bib(la)tex` files through `ebib`/`biblio.el`, they should be imported into the corresponding `zotero` collection library.

This isn't really related to BBT, as import is a general Zotero functionality, which in turn calls BBT sometimes for doing the work of the import. You can invoke this by using the debug bridge to execute

```
await Zotero_File_Interface.importFile({ file: Zotero.File.pathToFile(path), createNewCollection: false })
```

You can't really "import into a collection"; what you can do is assign imported items to an existing collection after import. But I honestly doubt you want to do this. You will end up with more and more duplicates of items, as each import will import all items in the bib file as new, independent items.

If you're talking about bi-directional sync instead of import, [that is not happening](https://github.com/retorquere/zotero-better-bibtex/issues/1755), as the bib file is not a good sync source.

> * When I modified the `zotero` collection library, the corresponding `bib(la)tex` files should be updated immediately, which can be done by the feature discussed in this issue.

OK, so nothing extra there.

> * For the entries generated by `ebib`/`biblio.el`, use the citation key generation rule of `BBT` to maintain the consistency.

I don't know what BBT could do for you here.

**Comment by retorquere** [comment]
> Another thing that surprised me is that `Zotero` and `BBT` don't seem to store their preferences in `~/.zotero/` or `~/Zotero/`.

That is not related to the current issue(s), that is a general Zotero question. I know the answer (they are stored in the profile, not in the data dir), but the discussion of the why/how of that should be had with the Zotero developers.

**Comment by hongyi-zhao** [comment]
> That is not related to the current issue(s), that is a general Zotero question. I know the answer (they are stored in the profile, not in the data dir), but the discussion of the why/how of that should be had with the Zotero developers.

Thank you for letting me know the thinking direction of the problem.

**Comment by hongyi-zhao** [comment]
> If you're talking about bi-directional sync instead of import, [that is not happening](https://github.com/retorquere/zotero-better-bibtex/issues/1755), as the bib file is not a good sync source.

Yes, that's what I think.

**Comment by retorquere** [comment]
What Linux are you on? I can't replicate this on Ubuntu 20.04
<img width="331" alt="Screenshot 2021-08-08 at 20 21 06" src="https://user-images.githubusercontent.com/132108/128641873-70f557ec-5e7e-4e79-ae77-f1f54378ba24.png">

**Comment by retorquere** [comment]
Can you give build 1289 a go?

**Comment by hongyi-zhao** [comment]
> What Linux are you on? I can't replicate this on Ubuntu 20.04

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

> Can you give build 1289 a go?

Still meet the same problem.

![image](https://user-images.githubusercontent.com/11155854/128649314-62511484-273f-44fd-810f-51ed86025df0.png)

![image](https://user-images.githubusercontent.com/11155854/128649296-a7bdb07b-f74b-42d3-a0b3-22ab58941bce.png)

**Comment by retorquere** [comment]
That's the same problem. Can you go into the `Help` menu, select `Debug Output Logging`, then `Restart with logging enabled`, let Zotero restart, then go into Preferences, BBT, Auto-export (which will show the button cut off), then back into the `Help menu` and select `Send Better BibTeX Support log`, and post the red ID you get here.

**Comment by hongyi-zhao** [comment]
`8DLRPQR8-apse`

![image](https://user-images.githubusercontent.com/11155854/128792719-5f3d67c9-5c10-4930-a8b1-5b0b04e14b71.png)

**Comment by hongyi-zhao** [comment]
It seems the problem is caused by something wrong of my system. Now, I installed the Ubuntu 20.04.2 LTS, and the problem disappeared:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

![image](https://user-images.githubusercontent.com/11155854/129438498-b0e80339-1ff8-4448-b70e-62ed71d4b957.png)


![image](https://user-images.githubusercontent.com/11155854/129438466-b153a803-504e-4459-948d-085f52a5ba3f.png)

**Comment by retorquere** [comment]
I needed to overhaul the prefs screens anyway, so no worries.

**Comment by hongyi-zhao** [comment]
Got it. The problem is caused by the larger interface text font size.

This will OK:

![image](https://user-images.githubusercontent.com/11155854/129469967-0f2451a7-7e35-4ab2-8e5d-2ab704bc78b9.png)

This will trigger the problem reported here:

![image](https://user-images.githubusercontent.com/11155854/129470023-b9511842-5bcd-452e-8b60-6ea61305a63f.png)

**Comment by retorquere** [comment]
Can you see if build 1315 works with the larger font size?

**Comment by hongyi-zhao** [comment]
Yes. This version has a scroll bar which will do the trick:

![image](https://user-images.githubusercontent.com/11155854/129479139-46a9324f-d88f-43dc-af0a-0916ad735c56.png)

**Comment by retorquere** [comment]
I'

**Comment by hongyi-zhao** [comment]
> I'

What's your meaning?

**Comment by retorquere** [comment]
I'll try to replicate this when I get back to my linux system. The vertical scrollbars shouldn't be necessary, and the horizontal ones may only be required for the filename.

**Comment by retorquere** [comment]
I clicked on "comment" by accident before I finished my message.

**Comment by hongyi-zhao** [comment]
This version fixes this problem and has no scrollbars

**Comment by retorquere** [comment]
Superb. Is the fields for the target filename sensible qua length?

**Comment by hongyi-zhao** [comment]
I'm not sure whether I understand you correctly. Anyway, see below:

![image](https://user-images.githubusercontent.com/11155854/129480456-317fa4fd-8353-4641-b3bd-5a172a440383.png)

**Comment by retorquere** [comment]
That's sort of OK, but the window is still too wide. I'll see what I can do about that.

**Comment by retorquere** [comment]
1318 may or may not solve the width problem, but the larger font may just always have this. The prefs pane module from Firefox (which Zotero is built on) has long-known resizing problems, and since Mozilla itself no longer use the prefs pane module, it is not going to be fixed by them. We're stuck with trying kludges and workarounds.

**Comment by hongyi-zhao** [comment]
![image](https://user-images.githubusercontent.com/11155854/129499196-5c44c33c-5691-4557-a878-84513a291b07.png)

**Comment by retorquere** [comment]
That's as good as it's going to get looks like.
