### ISSUE TITLE
FeatureRequest: Overwrite an existing item with bibtex from clipboard

### ISSUE THREAD

**Issue by noppelmax** [retorquere/zotero-better-bibtex#1885]
Hey,

i often face the problem that I have a couple of papers imported from ArXiv which will later be published at a conference. So I would like to keep all my notes, relations and tags for the paper/the item but replace all the items information with the original published version. Therefore I look up the bibtex stuff in the internet and copy to clipboard. In the next step I would like to overwrite all the fields of the item with the bibtex from the clipboard. Is this complicated to implement? I already took a loot at the sqlite db but doing this in sqlite would be a hard challenge. The Zotero Plugin API should be able to handle this more easily. Sadly I did not found any documenation of this API. Nor of nice and clear examples on how to add menu items and stuff.

My current workaround:
+ "File -> Import from Clipboard"
+ And then mark every field and copy it to the original item
+ Remove the imported item

So my questions:
+ Is this already implement somewhere and i just did found it?
+ How hard is this to implement?
+ Do you have any good Zotero Plugin API documentation?
+ Does anyone else have this problem?

**Comment by retorquere** [comment]
> I already took a loot at the sqlite db but doing this in sqlite would be a hard challenge.

You really don't want to modify the DB directly. It's easy to screw things up and make the DB unreadable for Zotero.

>     * Is this already implement somewhere and i just did found it?

https://github.com/wshanks/Zutilo has functionality to copy-paste fields between items. Whether you import from bibtex or something else isn't really important.

>     * How hard is this to implement?

I don't know what metric to use to describe this. Not incredibly hard if you know Javascript

>     * Do you have any good Zotero Plugin API documentation?

There isn't any. I learn how Zotero works by reading its source.

>     * Does anyone else have this problem?

I think you'll get better answers to this on the Zotero forums

**Comment by noppelmax** [comment]
Hey, i managed to get a menuitem in the right-click dropdown of a bib item. I also managed to get the text of the clipboard. But i failed to get the translater working. That is my current code for the menuitem click action:

```
pasteBibTex: function() {
        /* Function to parse the BibTex in the clipboard and overwrite all the contained 
        fields in the selected item. */
        var zitems = this.getSelectedItems(['regular']);

        if (!this.checkItemNumber(zitems, 'regularNoteAttachment1')) {
            return false;
        }

        var clipboardText = ZutiloChrome.getFromClipboard().trim()
        if (!clipboardText) {
            return false;
        }

        var translation = new Zotero.Translate.Import();
		translation.setString(str);

        Zotero.log(translation.translate());

        /*for (let zitem of zitems) {
            zitem.setString(clipboardText);
            zitem.saveTx()
        }
        */

        return true;
    }
```
I am not sure if `Zotero.Translate.Import()` is the correct Translator because I don't really want to import something. But I didn't found any snippet on how to parse BibTex and how to set fields of a `zitem`. What ever a `zitem` is. I guess I need to move this to the Zutilo Repository. Thank you for your response!

**Comment by retorquere** [comment]
Import is async, so you'd need to `await` it, but I'm pretty sure zotero doesn't offer a way to parse bibtex without importing it into items.
