### ISSUE TITLE
field for "formal notes"

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#1893]
Support log:  C6KFDXE6-refs-apse

A reference in the reference list sometimes needs to print extra information such as "in press".  In the traditional Bibtex way, you write
````
@article{somelabel,
  author = {. . . },
  . . .,
  notes = {in press}
}
````
If I'm not mistaken (but I may well be), there doesn't seem to be a Zotero field for this purpose.  Is that so?

Zotero's "Notes" feature seems to be designed for personal notes, which shouldn't be printed in the reference list:

https://forums.zotero.org/discussion/91365/non-exporting-personal-notes

So, my question is, what field should one use for the formal notes?  (If the answer is Zotero's "Notes" feature, then obviously the question is, where should one write one's personal notes?)

Support log ID:

**Comment by ryofurue** [comment]
Sorry for the omission.  This is the support log
C6KFDXE6-refs-apse

**Comment by retorquere** [comment]
> If I'm not mistaken (but I may well be), there doesn't seem to be a Zotero field for this purpose. Is that so?

I think that analysis is correct. I hadn't thought of it this way before.
 
> Zotero's "Notes" feature seems to be designed for personal notes, which shouldn't be printed in the reference list:

I don't know, really. CSL does have access to a note field, but I don't know what that gets filled with.

> So, my question is, what field should one use for the formal notes? (If the answer is Zotero's "Notes" feature, then obviously the question is, where should one write one's personal notes?)

Currently I don't have an answer for this. A workaround is possible by tagging the notes, but it's not a great solution. I could switch to using `extra` for notes. But dumping the research notes outside the entry means it cannot be read back. I could go `extra` -> `note` and do the Zotero notes as `note_1`, `note_2` etc.

**Comment by retorquere** [comment]
I checked and that's indeed what Zotero does; the `extra` field goes to the `note` field for CSL, which makes the biblatex `note` field a sensible equivalent.

**Comment by ryofurue** [comment]
Thank you for your research.  (Before this conversation, I didn't even know what CSL is, but now I 've started to see what you mean).

`extra` must be the right choice.  But, in that case,  would we need to coordinate with the developers of the Zotero browser plugin?  The plugin just dumps extra information which isn't suitable for the reference list into the `extra` field.

Ideally we want to have an option for the browser plugin not to use the `extra` field.  (Perhaps it should dump the extra info into another *unused* field.)

**Comment by retorquere** [comment]
Can you try 1405?

> `extra` must be the right choice. But, in that case, would we need to coordinate with the developers of the Zotero browser plugin? The plugin just dumps extra information which isn't suitable for the reference list into the `extra` field.

That's going to be difficult. The plugin is merely a conduit, the actual data being brought into Zotero is collected and offered to Zotero is immplement by some 650 [translators](https://github.com/zotero/translators) written by probably just as many volunteers.

> Ideally we want to have an option for the browser plugin not to use the `extra` field. (Perhaps it should dump the extra info into another _unused_ field.)

I don't think that would be necessary -- structured data like `Original Date: 800bc` can go to the `extra` field, and unstructured data should go to child notes. Structured data does not show up in the `note` field.

**Comment by ryofurue** [comment]
@retorquere Thank you again for the detailed explanation.  Sorry for my misunderstanding. When I wrote my previous comment, I didn't know that the `Extra` field has a standardized structure. So, I guess you are introducing a new *subfield* under the `extra` field to be exported as `note` in bibtex.  Is that right?

Should we write "note: In press", for example, within the `extra` field, to print "In press" in the final reference list of the LaTeX document that uses the exported bibtex file?

I'm new to Zotero: I'm in the process of writing my first paper using a bibtex file auto-generated by Better BibTeX, and I'm stumbling upon one problem after another, learning things like this in the process.

So, at first I didn't know what you mean by "Can you try 1405?" . . . But now I understand you mean the message I got from the "build bot".  I'll try that as soon as possible.

**Comment by retorquere** [comment]
> @retorquere Thank you again for the detailed explanation. Sorry for my misunderstanding.

Absolutely no worries

> When I wrote my previous comment, I didn't know that the `Extra` field has a standardized structure.

Well, that's not exactly correct. Zotero and BBT have functionality to interpret the unstructured `extra` field to recignize structured data; specifically, if a line in the `extra` field looks like `key: value`, and Zotero/BBT recognize the `key`, they will remove that line from the `extra` field during processing and use the `value` in some way.

> So, I guess you are introducing a new _subfield_ under the `extra` field to be exported as `note` in bibtex. Is that right?

No, I consume the structured data, and whatever remains is going into the `note` field. You can force the content of the `note` field BTW by using the structured-data line

```
tex.note: something
```

and whatever else is in the `extra` field will be ignored.

> Should we write "note: In press", for example, within the `extra` field, to print "In press" in the final reference list of the LaTeX document that uses the exported bibtex file?

Either will work. 

```
Original Date: 1998
tex.note: In press
```

works, but also

```
Original Date: 1998
In press
```

because the first forces the `note` field, and the 2nd because the structured `Original Date` is stripped, and `In press` remains and goes to the `note` field.

> I'm new to Zotero: I'm in the process of writing my first paper using a bibtex file auto-generated by Better BibTeX, and I'm stumbling upon one problem after another, learning things like this in the process.

It's always OK to ask for help.
 
> So, at first I didn't know what you mean by "Can you try 1405?" . . . But now I understand you mean the message I got from the "build bot". I'll try that as soon as possible.

Yes, sorry, that is what I meant.

**Comment by retorquere** [comment]
> I'm new to Zotero: I'm in the process of writing my first paper using a bibtex file auto-generated by Better BibTeX, and I'm stumbling upon one problem after another, learning things like this in the process.

That's OK. You just happened to start with the more complex end; not many users actually use the `note` field in tex/csl. The handling of the `extra` field is a stopgap measure in Zotero for things that don't have good support in the UI, and the documentation for it is not great. I implement the same `extra`-field functionality with some tex-specific extensions, but things like `Original Date: xyz` also work if you use Zotero's Word/LibreOffice support.

**Comment by retorquere** [comment]
https://forums.zotero.org/discussion/91398/please-add-doi-field-to-presentation-or-add-a-poster-type#latest is an example of how zotero uses the extra field.

**Comment by ryofurue** [comment]
I've just tried 1405 and I confirm it works as intended.  Thanks!

But, there is a minor problem, which I don't know how to solve.  This is a very special case, but this particular document I refer to has an update in the form of a webpage.  So, in the "note" (the `Extra` field), I write something like "Updates are documented in http://some.institution.edu/program/updates ".  In the PDF version of my paper, this note is nicely printed, but I'm not able to make it a hyperlink.  I then tried `\url{ . . . }` but it doesn't work as intended.

**Comment by ryofurue** [comment]
@retorquere said
> Can you send a support log for that item?

Sure.

I'm not sure if I did it correctly but here is (what I think is) the support log ID

I8MJVTQ3-refs-apse

which I generated on the particular item.

**Comment by retorquere** [comment]
> I then tried `\url{ . . . }` but it doesn't work as intended.

bibtex or biblatex?

**Comment by retorquere** [comment]
Oh, I see. There's two ways I see you could do this:

## use the following `extra` field

```
The programs are available from, and updates to them are documented in, <script>\url{https://www.whoi.edu/cms/files/Fortran_30425.htm}</script> (2007).
```

pro: easy
con: will output the `<script>` tags and `\url` command if you render the bibliography in Word

## use a postscript

```
if (Translator.BetterTeX) {
  if (item.extra) reference.add({ name: 'extra',  value: item.extra.replace(/https?:\/\/[^ ]+/, '<script>\\url{$1}</script>') })
}
```

pro: will work in TeX and Word
con: more complex

**Comment by retorquere** [comment]
Ah, PostScript. Memories. Not uniformly good ones, but memories.

No, it's a javascript snippet that runs after ("post") BBT is ready generating the tex reference and just before it is written out: https://retorque.re/zotero-better-bibtex/exporting/scripting/

**Comment by ryofurue** [comment]
Thanks.  After some trial and error, I found the following postscript works
````javascript
if (Translator.BetterTeX) {
  if (item.extra) reference.add({ name: 'note',  value: item.extra.replace(/(https?:\/\/[^ ]+)/, "<script>\\url{$1}</script>") })}
````
Note the `name: 'note'`  bit.  When that was `name: 'extra'`, a bibtex field named `extra` was created beside the `note` field in the exported result.

Also, I've managed to get `$1` work only when the regex includes a group (delineated by the pair of parens).

So, I'm so far happy with this postscript.  For more robustness, however, we would need to specify the end of a URL more precisely.  Currently the end of URL is defined as a following whitespace, but something like
````javascript
(https?:\/\/[-_?&:./\w]+)
````
will be a bit more robust.  But, this is still far from complete

https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url

and I guess we should leave this issue as an "exercise for the reader" :-)

**Comment by retorquere** [comment]
> Note the `name: 'note'` bit. When that was `name: 'extra'`, a bibtex field named `extra` was created beside the `note` field in the exported result. Also, I've managed to get $1 work only when the regex includes a group (delineated by the pair of parens).

Uh, yeah, my bad on both of those.

> and I guess we should leave this issue as an "exercise for the reader" :-)

Yep. That's what postscripts are for; things that don't have a good general solution and that the user can control to tweak to the situation as necessary.

**Comment by bwiernik** [comment]
@retorquere The CSL field for “in press” and similar is `status`.

**Comment by retorquere** [comment]
CSL has fields with spaces?

**Comment by bwiernik** [comment]
See the variables section at the bottom. 

https://github.com/citation-style-language/documentation/blob/master/specification.rst
