### ISSUE TITLE
How to build the latest git master version of `zotero-better-bibtex` manually?

### ISSUE THREAD

**Issue by hongyi-zhao** [retorquere/zotero-better-bibtex#1894]
It seems that the [ci workflow of this project](https://github.com/retorquere/zotero-better-bibtex/blob/master/.github/workflows/ci.yaml) is rather complicated. If I want to build the latest git master version of zotero-better-bibtex manually, are there some simple steps/hints/suggestions?

Regards,
HY

Support log ID:

**Comment by retorquere** [comment]
You need to have node >= 16 and python 3.9 (although 3.7 might work). The build procedure has only been tested on:

- Linux (any distro should do)
- MacOS (any version should do)
- Windows Subsystem for Linux (the latest version)

It may or may not work under the standard Windows shell, I haven't tested, and I doubt it will, but if you only have a  Windows system there's no harm in trying. And you could always use virtualbox to run a linux for the build. 

Anyhow -- inside the clones project, run
```
pip3 install -r requirements.txt`
npm install
```

to install the pytjon and node packages, and then 

- `npm run build`

will build the xpi and place it in the subdirectory `xpi`. These xpis are cross platform, so you can use the xpi on Windows just fine.

**Comment by hongyi-zhao** [comment]
>     * npm run build

The last step failed with the following messages:

```
> zotero-better-bibtex@5.4.28 build
> npm run rebuild


> zotero-better-bibtex@5.4.28 rebuild
> parallel --ungroup ::: 'npm run lint' 'npm run esbuild' 'npm run tsc'

parallel: invalid option -- '-'
parallel [OPTIONS] command -- arguments
	for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
	run specified commands in parallel

```

**Comment by retorquere** [comment]
Which version of `parallel` are you running? For me, `parallel --version` shows

```
GNU parallel 20161222
Copyright (C) 2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel
```

**Comment by hongyi-zhao** [comment]
> Which version of `parallel` are you running? For me, `parallel --version` shows

Thank you for your comment. I reinstalled `parallel` as follows:

```
$ sudo apt install --reinstall parallel
$ parallel --version
GNU parallel 20161222
Copyright (C) 2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel
```
Now, I've successfully compiled `zotero-better-bibtex`:

```
$ ls -1lh xpi/
total 32M
-rw-rw-r-- 1 werner werner 4.3K Aug 25 15:54 debug-bridge-5.4.28.werner.X10DAi-00.xpi
-rw-rw-r-- 1 werner werner  32M Aug 25 15:54 zotero-better-bibtex-5.4.28.werner.X10DAi-00.xpi
```
