### ISSUE TITLE
Dollar sign is not escaped in file field when exported to Better BibTeX or Better BibLaTeX

### ISSUE THREAD

**Issue by yuuyins** [retorquere/zotero-better-bibtex#1895]
**Support log ID:**
59LVUYVM-refs-euc

**Exporter used:**
Better BibTeX and Better BibLaTeX

**Expected behavior:**
Given an item which has attached a stored copy of a file which has in its filename a dollar sign `file $ name.ext`, exporting this item to either Better BibTeX or Better BibLaTeX escapes the dollar sign for the file field.

    @book{test-2021-test,
      title = {Test},
      author = {{Test}},
      year = {2021},
      file = {/home/yuu/Zotero/storage/4R5EZIUE/test \$ test.epub}
    }

**Actual behavior:**
Given an item which has attached a stored copy of a file which has in its filename a dollar sign `file $ name.ext`, exporting this item to either Better BibTeX or Better BibLaTeX doesn’t escape the dollar sign for the file field.

    @book{test-2021-test,
      title = {Test},
      author = {{Test}},
      year = {2021},
      file = {/home/yuu/Zotero/storage/4R5EZIUE/test $ test.epub}
    }

**Reproduce**

1.  On your system, create a new file named `test $ test.epub`
2.  On Zotero, create a new book item with the following
    -   Title: `Test`
    -   Author: `Test`
    -   Date: `2021`
    -   Add attachment > Attach stored copy of file > `test $ test.epub`
3.  Export the book item to either `Better BibTeX` or `Better BibLaTeX`

(Notice this is also reproducible when exporting collections).

**Comment by retorquere** [comment]
`file` is a verbatim field; the dollar sign should not be escaped in it. Which program is having difficulty reading the unescaped dollar sign?

**Comment by yuuyins** [comment]
It's the highlighting on bibtex-mode from Emacs (https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/textmodes/bibtex.el).

![emacs-bibtex-mode-dollar-sign](https://user-images.githubusercontent.com/86538850/130816460-aefc19f2-72e6-4f9c-8bb8-4de2bdd46d28.png)

I assumed this was an issue with Better BibTeX. Just tested on Emacs, opening the file with `org-ref-cite-open-pdf` with the cursor on the citation works, so I guess it's just a bug with the highlighting.
