### ISSUE TITLE
preference

### ISSUE THREAD

**Issue by tughv** [retorquere/zotero-better-bibtex#1898]
when i enter into the preference, it  doesn't show all as i expected,i have to click other buttom and back
**Expected behavior:**
[
![image](https://user-images.githubusercontent.com/40344969/131127806-3e96e185-0527-4339-8668-fa7845a439cb.png)
](url)
**Actual behavior:**
[
![image](https://user-images.githubusercontent.com/40344969/131127744-0bff374d-4295-4d7d-a7e0-b72533d984a4.png)
](url)

**Comment by tughv** [comment]
1790047934

**Comment by tughv** [comment]
REUEXUGT-apse

**Comment by qqobb** [comment]
(@retorquere: This issue with the Preferences pane seems to be fixed in the latest beta.)

**Comment by retorquere** [comment]
Unfortunately, the switch of the latest beta to react has somewhat taken me by surprise, and I will need some time to figure out how to fix this.

**Comment by qqobb** [comment]
I can confirm that the resizing issue of the Preferences is fixed now in the latest versions of the Zotero beta and BBT.
