### ISSUE TITLE
PSA: BBT does not work in Zotero beta 5.0.97 39+

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#1899]
Just updated to the latest Z beta 5.0.97-beta.39+dea4a47b6 (on MacOS 11.5.2 (20G95), BBT 5.4.28). When booting Z, BBT seems to get loaded, but none of the keys are generated. The little info box (bottom right) does not appear either, but I am able to see the BBT tab in Preferences, although it seems different than before. 

**Support log ID:**
D1305265593 (Debug ID)

Report ID 1413329344

Send BBT Support Log does NOT work (tried to multiple times)

[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa already loaded from apa.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 178}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:178:15
tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:609:17
module.exports/Promise.prototype._settlePromise0@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:649:5
module.exports/Promise.prototype._settlePromises@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:729:13
_drainQueueStep@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:93:9
_drainQueue@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:86:9
Async.prototype._drainQueues@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:102:5
Async/this.drainQueues@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:15:9

Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'

[JavaScript Error: "Download failed with response code undefined"]

[JavaScript Error: "Error: Download failed with response code undefined" {file: "chrome://zotero/content/xpcom/file.js" line: 478}]

[JavaScript Error: "TypeError: bbt_zoteropane is null" {file: "chrome://zotero/content/standalone/standalone.xul" line: 1}]
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

version => 5.0.97-beta.39+dea4a47b6, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => en-US, appName => Zotero, appVersion => 5.0.97-beta.39+dea4a47b6, extensions => ZoteroQuickLook (1.4.2, extension), ZotFile (5.0.16, extension), Zotero Memento (1.0.0, extension), Zotero Storage Scanner (5.0.8, extension), Mdnotes for Zotero (0.1.3, extension), DOI Manager (1.4.1, extension), Zutilo Utility for Zotero (3.9.0, extension), scite Plugin for Zotero (1.0.9, extension), Better BibTex for Zotero (5.4.28, extension), Zotero Word for Mac Integration (5.0.38.SA.5.0.97-beta.39+dea4a47b6, extension), Zotero LibreOffice Integration (5.0.25.SA.5.0.97-beta.39+dea4a47b6, extension)

**Expected behavior:**

**Actual behavior:**

**Comment by qqobb** [comment]
@jrennstich: See here: https://forums.zotero.org/discussion/91449/add-ons-broken-in-the-latest-beta-version-bbt-zutilo-etc

**Comment by jrennstich** [comment]
Thanks for the quick note

**Comment by retorquere** [comment]
@qqobb thanks for having my back here and on the forum.

**Comment by retorquere** [comment]
I'm close to having this fixed, only need to fix https://github.com/retorquere/zotero-better-bibtex/discussions/1904#discussioncomment-1250344

**Comment by retorquere** [comment]
That should do it.

**Comment by retorquere** [comment]
Would very much appreciate feedback -- then a new release can go out.

**Comment by lewisharvey** [comment]
Wow. thanks so much for the speedy fix. BBT 5.4.28.1448 now works properly with Zotero 5.0.97-beta.40+952663de7. I am so grateful because I rely on BBT and am in the middle of writing several manuscripts that depend on it. Thank you for giving up your Sunday to finding a solution. With best wishes, Lew Harvey

**Comment by jrennstich** [comment]
> Wow. thanks so much for the speedy fix. BBT 5.4.28.1448 now works properly with Zotero 5.0.97-beta.40+952663de7. I am so grateful because I rely on BBT and am in the middle of writing several manuscripts that depend on it. Thank you for giving up your Sunday to finding a solution. With best wishes, Lew Harvey

Couldn't agree more.

**Comment by jrennstich** [comment]
> Would very much appreciate feedback on the build that will drop here momentarily -- then a new release can go out.

Also can confirm that everything works with the posted build. Thanks so much!

**Comment by qqobb** [comment]
Thank you, @retorquere, you did it! I just tried 5.4.28.1456 and it's working well.

(A minor detail: You could capitalize the column header to "Citation Key" to follow the style of the other columns.)

**Comment by qqobb** [comment]
For some reason, when sorting by the Citation Key column, the secondary sort was initially set to "Attachments". Items without attachments were separated from items with attachments, so it wasn't properly in (a single) alphabetical order. I changed the secondary sort to Date, which fixed this issue. Now I don't see "Attachments" as an option for secondary sort. Not sure what was happening, but all is well now.

**Comment by retorquere** [comment]
> For some reason, when sorting by the Citation Key column, the secondary sort was initially set to "Attachments".

I don't think there's something I can do about that -- Zotero handles sorting, I just supply the data.

**Comment by retorquere** [comment]
> Thank you, @retorquere, you did it! I just tried 5.4.28.1456 and it's working well.
> 
> (A minor detail: You could capitalize the column header to "Citation Key" to follow the style of the other columns.)

I'll add that, but I'll also add translation infra for it (wasn't there before), and it usually takes an hour, sometimes two, for the French translations to drop in. When that is in, I'll cut a new release.
