### ISSUE TITLE
better bibtex problem installation 

### ISSUE THREAD

**Issue by phy1994** [retorquere/zotero-better-bibtex#1901]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT support log from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Support log ID:**

**Exporter used:**

**Expected behavior:**

**Actual behavior:**

**Comment by retorquere** [comment]
You did not say what the problem was.

**Comment by phy1994** [comment]
i'm trying to install better bibtex and when i download any version i have the following message "le module complémentaire téléchargé depuis ce site n'a pas pu etre installé car il semble corrompu "

**Comment by phy1994** [comment]
i'm trying to install better bibtex and when i download any version i have the following message "  the add-on downloaded from this site could not be installed because it seems corrupted "

**Comment by retorquere** [comment]
What URL are you downloading BBT from, and with what browser?

**Comment by phy1994** [comment]
this one 
https://github.com/retorquere/zotero-better-bibtex/releases/tag/v5.4.28

**Comment by retorquere** [comment]
> this one
> https://github.com/retorquere/zotero-better-bibtex/releases/tag/v5.4.28

That's the page that has the download link for the xpi, it's not the link to the xpi itself. If you're downloading that url, you have the html page saved, and that of course isn't a valid install file.

**Comment by qqobb** [comment]
@phy1994: You need to install the XPI file in the Zotero desktop app. See here: https://github.com/jlegewie/zotfile/issues/499.

**Comment by phy1994** [comment]
please can you send me the URL to download the xpi file 
i need to use zotero in latex and it's been many weeks that i'm trying to fix the problem .

**Comment by retorquere** [comment]
On that page you mentioned, if you expand the assets, you find the link https://github.com/retorquere/zotero-better-bibtex/releases/download/v5.4.28/zotero-better-bibtex-5.4.28.xpi, that's the one you need.

As @qqobb pointed out, if you're using Firefox, you must right-click that asset link and save, *not* click the link, because Firefox will think it's a Firefox plugin and will try to install it in Firefox rather than downloading it.

**Comment by phy1994** [comment]
ooh  i did what you recommended and it works but i encountered another problem i send you  a screenshot  this is in french it means that there is a problem of compatibility . 
what can i do ,????
![Capture d’écran de 2021-08-28 20-51-18](https://user-images.githubusercontent.com/87550631/131229461-c0c71ac4-0ff4-47e9-bb34-fbf76e6ec323.png)

**Comment by phy1994** [comment]
ooh  i did what you recommended and it works but i encountered another problem i send you  a screenshot  this is in french it means that there is a problem of compatibility . 
what can i do ,????
![Capture d’écran de 2021-08-28 20-51-18](https://user-images.githubusercontent.com/87550631/131229461-c0c71ac4-0ff4-47e9-bb34-fbf76e6ec323.png)

**Comment by retorquere** [comment]
What version of zotero do you have?

**Comment by qqobb** [comment]
@phy1994: You should be using Zotero version 5.0.96.3. See here: https://askubuntu.com/a/1160369

**Comment by phy1994** [comment]
i used  zotero version  5.0.96.2

**Comment by phy1994** [comment]
i used zotero version 5.0.96.2 and i installed it from  the ubuntu software 
![Capture d’écran de 2021-08-28 22-09-58](https://user-images.githubusercontent.com/87550631/131231102-cd99c8ac-f971-453a-a4ae-bf99e20f7984.png)

**Comment by phy1994** [comment]
yes ! i tried to install it using the terminal      https://askubuntu.com/a/1160369
but i had the folowing message 
![Capture d’écran de 2021-08-28 22-13-20](https://user-images.githubusercontent.com/87550631/131231187-d0cbfd07-e4d3-4b3d-b08e-585cbbc3e473.png)

**Comment by retorquere** [comment]
> i used zotero version 5.0.96.2 and i installed it from the ubuntu software

This is the snap-packaged version

> yes ! i tried to install it using the terminal https://askubuntu.com/a/1160369
> but i had the folowing message
> ![Capture d’écran de 2021-08-28 22-13-20](https://user-images.githubusercontent.com/87550631/131231187-d0cbfd07-e4d3-4b3d-b08e-585cbbc3e473.png)

That's the deprecated `smathot` version.

In principle it should work in the snap version, although we've had frequent reports that it runs into permissions problems at some point. The `smathot` version hasn't updated in a long while, and the last version they packaged is indeed not compatible with BBT. If you want a deb-packaged version you should remove the repo you added for the `smathot` version, uninstall the `smathot` version, and instead use [this](https://askubuntu.com/questions/332109/how-to-install-zotero-in-ubuntu/1160369#1160369), **not** [this](https://askubuntu.com/a/332117/687208).

**Comment by phy1994** [comment]
hi again i installed the version 5.0.96.3 of zotero and i tried to add better bibtex as you told me there is always a problem of incompatibility . 
THANK YOU

**Comment by phy1994** [comment]
and when i open  this version of zotero i have the following message 
![Uploading Capture d’écran de 2021-08-29 22-12-05.png…]()

**Comment by qqobb** [comment]
@phy1994: Remove all your Zotero packages once. Especially the outdated `smathot ` package. See https://askubuntu.com/a/187891 for apt. Also remove the snap package.

Then run these commands:
```
wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
sudo apt update
sudo apt install zotero
```

**Comment by retorquere** [comment]
Anything down to 5.0.85 should work with the current BBT release, but what @qqobb says is good practice; make sure you only have one zotero installed.

The snap version is slowly getting better, but the snap permission system gets in the way sometimes; if it doesn't install in it, I'll have to ask you to ask the snap maintainers of the package.

The smathot packages are stuck on Zotero 5.0.60, which is nearly 2.5 years behind the current Zotero release at time of writing, and should not be used for anything. The smathot repo calls my debs an "an alternative installer", but it should just take down all their Zotero packages and redirect to my debs; they're doing everyone a disservice by keeping them up, as old stackoverflow posts still point to it. My debs repo is the only maintained deb-packaged Zotero, and I feel pretty confident that for Linux you want either the official Zotero tarball, or my debs, and nothing else. My debs update within 2 hours of a formal Zotero release, fully automated, so they're always up to date.

**Comment by phy1994** [comment]
@qqobb  i followed the steps that you suggested me and i have the same message. also when i try to install better bibtex i have the same problem of incompatibility.  so i'm not very good in coding .... i dont understand where is the problem so if you suggest me another way to work with zotero instead of better bibtex i would be very thankful. 
![Capture d’écran de 2021-08-29 23-15-39](https://user-images.githubusercontent.com/87550631/131266997-8cf3087d-8673-46da-b42e-a9b54157c56b.png)
![Uploading Capture d’écran de 2021-08-29 23-16-12.png…]()

**Comment by retorquere** [comment]
There's no need to launch Zotero from the terminal, I think you'll find it more comfortable to click on the grid on the lower left and type "zotero" in the search box there.

In any case, I think Zotero is just hiding behind your browser at the moment. If you click the Zotero icon in the left bar it should appear. It looks like it has opened some dialogs, those are probably first-run windows that ask whether you want to install the Libreoffice plugin.

**Comment by phy1994** [comment]
ooohh i tried another version of better bibtex i think it works  finally !!!
thank you so much for help 
![Capture d’écran de 2021-08-29 23-35-19](https://user-images.githubusercontent.com/87550631/131267464-fb018581-93b9-4c94-95ae-79887ddf028e.png)
