### ISSUE TITLE
Citekey format request: org-cite

### ISSUE THREAD

**Issue by tecosaur** [retorquere/zotero-better-bibtex#1910]
:wave: hello. I was rather happy to see you support org-ref citation keys. Seeing that you do: In the past few months there's been a major development with Org — the introduction of a native citation syntax, termed org-cite. It would be great if Zotero could support this.
The documentation on the citation syntax has yet to be written, but a simple citation is just `[@cite:KEY]`. If you'd like more information, I have written a [blog post](https://blog.tecosaur.com/tmio/2021-07-31-citations.html) about this (in which I give Zotero a special mention too :wink:).

**Comment by tecosaur** [comment]
Heh, sounds like you've had a lot of trouble getting people to follow basic instructions. This template is listed with the description
> Key generation bug/enhancement
> You appear to have found a bug in BBTs citation key generation, or are proposing an enhancement to the key generation.

though, and I don't think enhancement suggestions would need a debug log...

**Comment by retorquere** [comment]
I also use the enclosed references as a test case to prevent regressions.

**Comment by tecosaur** [comment]
> In what way would you want support? CAYW, drag and drop, something else?

I think the primary use here would be drag and drop and quick copy

**Comment by retorquere** [comment]
Drag & Drop == Quick Copy. I still need a sample submitted as a support log, and you'd have to tell me what you want the result to look like.

**Comment by tecosaur** [comment]
Ah cool. I just made the support log `PM6BIN7N-apse`, and I'm happy to elaborate on the expected output beyond what I said in the my 1st comment of this issue, I'm just not sure what you're looking for.

**Comment by retorquere** [comment]
I meant to say I needed a support log generated by right-clicking an item of interest (in this case, an item you would want to drag and drop) and selecting the support log option from that menu. Such IDs will have `-refs-` in the name.

**Comment by tecosaur** [comment]
Ah, ok. That makes a lot more sense to me :sweat_smile:. Here we go: `MF3JMZHF-refs-apse`. So in that example, `[cite:@daiOptimalBayesClassifiers2017]` would be the expected org-cite citation.

**Comment by retorquere** [comment]
And how would multiple keys combine?

**Comment by tecosaur** [comment]
Keys are separated with semicolons here, i.e. `[cite:@daiOptimalBayesClassifiers2017;@otherkey;@anotherkey]` I doubt anything else is relevant to Better BibTeX but just in case, here's the full syntax:

![img](https://blog.tecosaur.com/tmio/figures/citation-structure-full.svg)

**Comment by retorquere** [comment]
That looks like a citation of a single source, not multiple, and it has semicolons in it. How does org-cite distinquish between multiple parts of one source, and multiple sources?

**Comment by tecosaur** [comment]
Say I wanted to cite page 7 of `foo` and chapter 2 of `bar`. The relevant citation in org-cite syntax would be `[cite:@foo pp.7;@bar chap.2]`. The handling of `pp.7` / `chap.2` is left up to backends though, so I wouldn't focus too much on it. If it isn't handled specially, it will just be used as a suffix for that key.

**Comment by retorquere** [comment]
build 1485 should do what you want

**Comment by tecosaur** [comment]
Cool :smiley: I'll take a look when I can see the preferences pane again.

**Comment by retorquere** [comment]
Can't proceed on that without new support logs. I cannot reproduce the problem with the prefs pane.

**Comment by tecosaur** [comment]
Unfortunately, I've become tremendously busy as of late. However, I'll try to find the time to test by the end of the week.

**Comment by retorquere** [comment]
Any news?
