### ISSUE TITLE
Doesn't work in latest Zotero update

### ISSUE THREAD

**Issue by antonkarasu** [retorquere/zotero-better-bibtex#1911]
After the latest auto update of Zotero (5.0.97-beta.39+dea4a47b6) my citation keys don't list, and I can't export a citation (using Pandoc markdown format). The error log is below:

[JavaScript Error: "TypeError: Zotero.ItemTreeView is undefined" {file: "chrome://zotero-better-bibtex/content/better-bibtex.js" line: 82546}]
@chrome://zotero-better-bibtex/content/better-bibtex.js:82546:3
@chrome://zotero-better-bibtex/content/better-bibtex.js:173:1

**Comment by retorquere** [comment]
Without a support log I don't know what version of BBT you have installed. The request for the support log is there for a reason, and also the request to verify you are on the latest version of BBT. There is a high chance you're still on 5.4.28. 5.4.29 was released last night for compatibility with the beta. But without a support log, that is just a guess.

**Comment by antonkarasu** [comment]
Apologies - I couldn't get Zotero to give me a support log ID - that didn't seem to be working. I have installed the new version and it all looks OK.
