### ISSUE TITLE
Enhancement: Add spaces when copying multiple keys

### ISSUE THREAD

**Issue by champagnealexandre** [retorquere/zotero-better-bibtex#1917]
I find myself frequently copying citation keys with the CMD-SHIFT-C shortcut with BBT, and one thing I could suggest is to introduce spaces between the keys. Pasting those directly into LaTeX without said spaces introduces long lines without spaces, which prevents editors (e.g. emacs) from breaking the line.

This might sound like a silly comment but when frequently citing multiple references at the same time, it creates multiple non-breaking lines in a document which is a bit annoying depending on the editor layout you use.

Thanks!

**Comment by champagnealexandre** [comment]
@retorquere awesome! wasn’t expecting this to be implemented so fast!!

Just tried the update myself, works wonderfully🤘

Thank you !

**Comment by retorquere** [comment]
> @retorquere awesome! wasn’t expecting this to be implemented so fast!!

Ha, I considered this to be a slow response :) 

> Just tried the update myself, works wonderfully🤘

You're welcome. I'll merge this into a new release tonight, but you can just keep what you have. The new release will just be what you have now with a new version number slapped on, and you'll be upgraded somewhere in the next 48 hours automatically.
