### ISSUE TITLE
Language field in the metadata exported incorrectly

### ISSUE THREAD

**Issue by ah-dagdelen** [retorquere/zotero-better-bibtex#1921]
Support log ID: NQSVQTXA-refs-euc
Betterbibtex for Zotero 5.4.29
Zotero 5.0.96.2
Linux Mint 20.2 Cinnamon

In Zotero, I keep language fields for works in German as follows:
de for German
de-AT for Austrian
de-CH for Swissgerman

de-At is for German spoken and written in Austria, and de-CH is for German spoken and written in Switzerland.

In the exported biblatex file, I get in the language fields German and Austrian accordingly. They are correct. For de-CH, I get in langid field German instead of Swissgerman. Shouldn't I get Swissgerman here?

Here is the output with Betterbiblatex.

> @book{kollerSchweizerischesObligationenrechtBesonderer2012,
>   title = {Schweizerisches Obligationenrecht Besonderer Teil Band I},
>   shorttitle = {OR BT I},
>   author = {Koller, Alfred},
>   date = {2012},
>   publisher = {{Stämpfli Verlag}},
>   location = {{Bern}},
>   langid = {german}
> }
> 

Here is the CSL json format from Zotero:
```
[
	{
		"id": "kollerSchweizerischesObligationenrechtBesonderer2012",
		"type": "book",
		"event-place": "Bern",
		"language": "de-CH",
		"publisher": "Stämpfli Verlag",
		"publisher-place": "Bern",
		"title": "Schweizerisches Obligationenrecht Besonderer Teil Band I",
		"title-short": "OR BT I",
		"author": [
			{
				"family": "Koller",
				"given": "Alfred"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2012"
				]
			]
		}
	}
]
```

**Comment by retorquere** [comment]
I currently have a fixed (and rather limited) mapping; I'm looking at [this](https://www.npmjs.com/package/rfc5646-tags) or [this](https://www.npmjs.com/package/@sozialhelden/ietf-language-tags) to re-use existing effort to get a complete mapping, but both of those have `German (Switzerland)` rather than `Swissgerman` for `de-CH`. Do you know of a maintained mapping that gets `swissgerman`?

**Comment by retorquere** [comment]
[this](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) has swissgerman but does not understand `de-CH`.

**Comment by ah-dagdelen** [comment]
I couldn't find one.

I also checked some other converters, e.g. pandoc. I thought, their mapping might be of help if there is one. But it did not work out.

**Comment by njbart** [comment]
Check out the [biblatex manual](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) as well as [IETF BCP47](https://tools.ietf.org/rfc/bcp/bcp47.txt).

The [babel](https://www.ctan.org/pkg/babel) and [polyglossia](https://www.ctan.org/pkg/polyglossia) manuals might be useful, too. Note that both babel and polyglossia have begun to support BCP47 tags in addition to the traditional ones, but biblatex has not yet (it’s being [discussed](https://github.com/plk/biblatex/issues/961), though).

Hence my suggestion for a sensible mapping from BCP47 to currently used biblatex tags:

BCP47 | biblatex
--|--
de | ngerman
de-DE | ngerman
de-AT | naustrian
de-CH | nswissgerman
de-1901 | german
de-DE-1901 | german
de-AT-1901 | austrian
de-CH-1901 | swissgerman

**Comment by retorquere** [comment]
babel equates de-CD to German though, and polyglossia to german variant=swiss, spelling=new.

**Comment by njbart** [comment]
(1) If you're referring to the babel manual, p.21 (extract below), I've seen that, too, but though I’m not sure what this table really is about, I’m sure it can't be the mapping we're talking about. In particular, it also indiscriminately maps (?) all variants of English to "English" – which definitely is *not* what should be happening when mapping from BCP47 to babel or polyglossia.

![Screenshot 2021-09-17 at 14 31 04](https://user-images.githubusercontent.com/2765811/133783404-19297c4a-a131-4cc4-8890-8f054c256789.png)

I still maintain that both `nswissgerman` and `swissgerman` are mentioned in the babel manual as well as the biblatex manual, and both work when using `\usepackage[nswissgerman]{babel}` or `\usepackage[nswissgerman]{babel}` in a latex document, so it is these identifiers that should be used when mapping from `de-CH` or `de-CH-1901`.

(2) From the polyglossia manual: "For convenience reasons, polyglossia also supports the use of babel names"

**Comment by retorquere** [comment]
Interesting -- yep, I missed that, but I'm now looking at the babel source, and there I find for `babel-de-CH.ini`:

```
name.babel.A = german-ch
name.babel.B = nswissgerman
; The following conflicts with gsw:
name.babel.C = swissgerman
```

so on the upside, this looks to be a machine-readable mapping for language codes I could use, but also that there are multiple names, and assuming that `.A` means preferred, or default, `de-CH`  would map to `german-ch` rather than `nswissgerman`.

**Comment by retorquere** [comment]
Booh, no `nl-BE` or `nl-rBE`.

**Comment by njbart** [comment]
Ok, but first and foremost, this is about biblatex. Its manual, p. 29, lists, under "Supported Languages":

![Screenshot 2021-09-17 at 15 21 06](https://user-images.githubusercontent.com/2765811/133789494-05e1f452-99fe-43b8-afa0-24ab42dbc1a9.png)

So these, I take it, are the values that should be used in the `langid` field.

The biblatex manual also says (p. 28), also on the `langid` field: "The identifier must be a language name known to the babel/polyglossia packages."

Now all of these (german, austrian, swissgerman, ngerman, naustrian, nswissgerman) *are* known to babel and polyglossia.

`german-ch` OTOH, whatever it is supposed to be used for, does *not* seem to be a user-facing language identifier: Using `\usepackage[german-ch]{babel}` in a latex document bombs with `! Package babel Error: Unknown option 'german-ch'.`

**Comment by retorquere** [comment]
Cool; I'll use the `biblatex` list to establish preferred alternatives, and will otherwise just pick the `name.babel` from the babel ini files.

**Comment by retorquere** [comment]
@ah-dagdelen can you verify build 1556 does what you expect?

**Comment by ah-dagdelen** [comment]
@retorquere thanks a alot. 

I can verify that I get nswissgerman for de-CH tag now. For de and de-At, I get German and Austrian respectively.

I agree with @njbart. Using n versions of the languages seems like a better idea here. n versions refer to the new orthography (Neue Rechtschreibung) while the others refer to the old orthography (Alte Rechtschreibung). The difference may cause some issues regarding word hyphenation.

**Comment by retorquere** [comment]
So in other words, satisfactory? If you have samples of all of those, a right-click-support-log would give me samples to add to my test suite.

**Comment by ah-dagdelen** [comment]
Yes satisfactory, the problem is solved for de-CH. Thanks for solving this issue.

Support log: CFWE9TLS-refs-euc

**Comment by retorquere** [comment]
@njbart what does `bibtex` expect/support in the `language` field?

**Comment by njbart** [comment]
Unlike biblatex, bibtex does not seem to officially support either `language` or `langid` fields. I don’t expect these fields to cause any problems if included in a bibtex file (and I’ve actually seen bibtex files with a language field in the wild), but I’m not sure whether they’d serve any useful purpose in that format either.

**Comment by retorquere** [comment]
So I might as well leave it out for bibtex then? What are the casing rules for bibtex? Everything title-cased?

**Comment by njbart** [comment]
> So I might as well leave it out for bibtex then? 

I guess so. (Unless users complain, of course.)

> What are the casing rules for bibtex? Everything title-cased?

The rules for bibtex and biblatex are essentially the same, so, yes, title-cased.

(Still, there are some “small differences between bibtex the program and the btparse library used by biber” we’ve [encountered before](https://github.com/jgm/pandoc-citeproc/issues/189).)

**Comment by retorquere** [comment]
> > What are the casing rules for bibtex? Everything title-cased?
> 
> The rules for bibtex and biblatex are essentially the same, so, yes, title-cased.

The reason I ask is that in biblatex, I look at the language information to determine whether or not to apply title-casing (to be specific, title-casing for Engl-ish, and no title casing for all others). So for bibtex I should also look at the language info I have? Or just treat everything as Engl-ish and title-case titles?

**Comment by njbart** [comment]
As I said [some time ago](https://github.com/retorquere/zotero-better-bibtex/issues/383#issue-111953976): “For bibtex, which does not have a langid field and thus cannot distinguish languages, I would guess that the complete title fields of non-English titles should be wrapped in braces to prevent bibtex from messing with capitalisation.“ I have no reason to assume anything has changed WRT bibtex since then.

**Comment by retorquere** [comment]
Ah right -- *non*-English is treated special here, rather than biblatex, where English is treated special.

**Comment by njbart** [comment]
> Ah right -- non-English is treated special here, rather than biblatex, where English is treated special.

I don’t think that’s the case. The default, IIRC, is in both cases to sentence-case titles if requested to do so by a style; it’s just that bibtex does not have anything similar to biblatex’s `langid` field to prevent this from happening, so the only solution is to wrap the whole title in braces.

In addition:

Maybe including `langid` fields in bibtex files might still clarify *why* titles were enclosed in braces upon export from BBT, as might some kind of comment in a quality report.

A `langid` field in a bibtex file would also be picked up by pandoc’s citeproc (that’s about the only case where I’m positive a tool designed for bibtex would know about `langid`).

**Comment by retorquere** [comment]
... which is probably why I have code that does just all of this ...

Sorry man, it's been a long month.
