### ISSUE TITLE
Problem with greek (and other unicode) characters in titles of references

### ISSUE THREAD

**Issue by tsknapton** [retorquere/zotero-better-bibtex#1922]
Zotero version: zotero-beta-5.0.97beta.43-1

BBT version: 5.4.29

Support log ID: NWKYAC5P-refs-euc

I'm exporting using better biblatex and one of my references has a greek letter (ρ, U+03C1) as well as another with angle brackets.  I have the 'export unicode as plain-text latex commands' flag on for bibtex and biblatex but still no luck.  The bibliography exports just fine but when I try compiling I get this error:

! Package inputenc Error: Unicode character ρ (U+03C1) not set up for use with LaTeX

I checked the .bib file and the letter appears as ρ instead of $\rho$ or whatever it's supposed to be with the aforementioned flags on.  I can get around the issue by enclosing the problem characters in <scipts> ... </script> tags in the title field in zotero.

**Comment by tsknapton** [comment]
NWKYAC5P-refs-euc

**Comment by retorquere** [comment]
The rho and angle brackets are in the attachment filename; since `file` fields are verbatim, I cannot replace those with `\rho` etc -- in verbatim fields the contents must appear as-is (with a few exceptions). Your options are to either rename the attachment to not have these characters, or to add `file` to the skip-fields in the preferences.

**Comment by retorquere** [comment]
Wait -- where did you add the `<script>` tags?

**Comment by tsknapton** [comment]
It's a problem with the Title field.  

Initially I tried to use this: 
![image](https://user-images.githubusercontent.com/76971222/133269138-44fcaae3-8873-4317-99ed-143fa1691e51.png)

but that threw the error. 

This is the fix with the <script> tags:
![image](https://user-images.githubusercontent.com/76971222/133269418-e0f3ba9a-3805-415b-8bea-37bc6484315e.png)

**Comment by retorquere** [comment]
Right, in the title you can use `ρ` and that error should be solved by turning the plain-text-commands on. The remaining error was because of what was in the `file` field.

**Comment by tsknapton** [comment]
Oh okay.  If the problem was with the file field then why is it fixed by adding the <script> tags to the Title field?  Or am I not understanding you correctly?

**Comment by tsknapton** [comment]
Both plain-text options are on (for BibTeX and for BibLaTeX). 

The title field is back to:
`ρ measurements in laser‐produced implosions using elastically scattered ions`

The result of the export is a .bib file containing the line: 
`title = {ρ Measurements in Laser‐produced Implosions Using Elastically Scattered Ions},`

With same error upon compilation as I mentioned in the original post

**Comment by retorquere** [comment]
Are you sure you are exporting with *Better* BibTeX/BibLaTeX and not the standard Zotero BibTeX/BibLaTeX exporters?

Wait no, if you weren't using the BBT exporters, the `<script>` tags would not have worked. But I cannot reproduce this on my end.

Can you try the following for me:

* Turn on debug logging from the help menu
* change `implosions` into `Implosions`
* do an export with `Better BibTeX` (plain-text option still at the default on)
* Right-click and send a new BBT log

**Comment by tsknapton** [comment]
Did what you asked (exported as Better BibTeX rather than Better BibLaTeX), the relevant line in the .bib seems correct now:
`title = {{$\rho$} Measurements in Laser-produced {{Implosions}} Using Elastically Scattered Ions},`

new log ID is: MKFBR62C-refs-euc

**Comment by retorquere** [comment]
And if you export with Better BibLaTeX (you can change implosions back, I just needed to make sure it was a BBT translator)?

**Comment by tsknapton** [comment]
If I export as Better BibLaTeX now the relevant line in the .bib file is 
`title = {{$\rho$} Measurements in Laser-produced Implosions Using Elastically Scattered Ions},`
which is also correct?  

I'm fairly certain I had exported using better biblatex before because my .bib updated itself automatically when I changed it, and like you said the `<script>` wouldn't have worked otherwise? Weird

**Comment by retorquere** [comment]
Gaah, I hate transient errors. It's probably a cache eviction problem, but even just changing the plaintext option should have dropped the cache.

**Comment by tsknapton** [comment]
I did also restart zotero every time I made a change which I thought might help with cache issues?  Anyway, I appreciate your help.

**Comment by retorquere** [comment]
A restart should not make a difference, as the cache is saved between restarts.

**Comment by retorquere** [comment]
Cache problems are hard to diagnose, sorry. If it reappears, please feel free to reopen or open a new issue, but I'm afraid there's not much I can do.

**Comment by tsknapton** [comment]
No problem, thanks
