### ISSUE TITLE
Kuroshiro hardcoded to apply to all CJK language items when option checked

### ISSUE THREAD

**Issue by jtcarlyle** [retorquere/zotero-better-bibtex#1928]
**Jurism version:** 5.0.93 (latest) 

**BBT version:** 5.4.29

**Support log ID:** Z3F7ALHY-refs-euc

**Expected behavior:** Kuroshiro word segmentation and transliteration only apply to citekeys for items that have the language field as "ja" or otherwise only transliterates fields that are marked as containing Japanese language data.

**Actual behavior:** If the user has checked the Kuroshi preference, Kuroshi word segmentation and transliteration is applied to all fields that the method "removeDiactrictics" is called on, regardless if they contain Japanese language data or not. Results in Chinese words get parsed incorrectly and transcribed in romaji as if they were Japanese.

# Detailed explanation:

The removeDiacritics method in /content/key-manager/formatter.ts has the following line:

```typescript
 if (Preference.kuroshiro && kuroshiro.enabled) str = kuroshiro.convert(str, {to: 'romaji'})
```
This only checks the users kuroshiro preference and if kuroshiro is enabled before converting the string to romaji. Ideally, it should at least check something like 

```typescript
this.item.language === 'japanese'
```
before doing the conversion. Kuroshiro will try to convert any *kanji* that are shared between modern standard Japanese writing and the Simplified and Traditional Chinese character sets (which is the majority of them, especially with Traditional Chinese). Ideally, though, for Juris-m there ought to be some dedicated method for transliteration that checks the language of the field before applying any transliteration. If this isn't set, then it could default to the language set for the item. I have quite a few citations where the name of the author is Chinese but the title and other info is Japanese. Without checking the language of each field, there would be no way of choosing how to transliterate each field (there are surnames that are used in both languages like 林 ja: Hayashi vs. zh: Lin).

**Comment by retorquere** [comment]
Work on this continues on #1930
