### ISSUE TITLE
Export of hypen for range in the volume field

### ISSUE THREAD

**Issue by ebouna** [retorquere/zotero-better-bibtex#1929]
**Zotero version:** 5.0.96.3

**BBT version:** 5.4.29

**Support log ID:** AIBBNRK6-refs-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** I would like a hyphen in the volume field designating a range to be exported as `--` (two hyphens): `volume = {1--3}`. The same happens with hyphens in the pages field, i.e., 1 hyphen is replaced by two hyphens when the file is exported. 
Cf. a complete entry with a volume field showing the expected output:
```
@book{begovic2002,
  title = {Giga Barićeva. Roman iz zagrebačkog poslijeratnog života},
  author = {Begović, Milan},
  editor = {Vinski, Nina and Ferenčić, Snježana},
  date = {2002},
  volume = {1--3},
  location = {{Zagreb}},
  langid = {croatian},
  shorthand = {GB 2002}
}
```

**Actual behavior:** 
When I insert "1-3" in the volume field, this is exported as `volume = {1-3}` and **not** as  `volume = {1--3}`. The latter behaviour would be consistent with the current export of the pages field. Here,  "29-42" is exported as  `pages = {29--42}`. Can the export behaviour in the case of the volume field be corrected, viz. made consistent with the pages field? If not, I'd like to know what may speak against this? Thanks a lot for your help.
```
@book{begovic2002,
  title = {Giga Barićeva. Roman iz zagrebačkog poslijeratnog života},
  author = {Begović, Milan},
  editor = {Vinski, Nina and Ferenčić, Snježana},
  date = {2002},
  volume = {1-3},
  location = {{Zagreb}},
  langid = {croatian},
  shorthand = {GB 2002}
}
```

**Comment by retorquere** [comment]
Can you see whether build 1592 does what you want?

**Comment by ebouna** [comment]
Yes, the problem has been solved! Works perfectly. Thanks a lot!!!
