### ISSUE TITLE
Capitalise chosen words when exported

### ISSUE THREAD

**Issue by alexreg** [retorquere/zotero-better-bibtex#1931]
It would be great to have an "Extra" field when I can specify the words to quote in braces when exporting (and thus maintain capitalisation). This would mainly be useful when the option to auto-quote capitalised words is not selected, though I can also see it being useful in that case for the purpose of the first word, which may be a proper noun (which can't be auto-detected easily, of course).

I propose a field format something like:
```
Quote Words: WordA, WordB, WordC
```

Alternatively, a more powerful format might be:
```
Quote Matches: \b(WordA|WordB|WordC)\b
```

This would do the same as above, but would allow for matching arbitrary regexps.

**Zotero version:**
5.0.96.3

**BBT version:**
5.4.29

**Support log ID:**
YK3HJUYG-refs-euc

**Exporter used:**
BibLaTeX

**Comment by retorquere** [comment]
Why not just use `<span class="nocase">WordA</span>`?

**Comment by retorquere** [comment]
The `<span class="nocase">` is the formally supported syntax in Zotero (this syntax is not BBT-specific), but `<nc>...</nc>` still works. I don't see Zotero removing it, but technically, it's deprecated.

**Comment by alexreg** [comment]
Thanks for clarifying. I presume that's part of CSL?

**Comment by alexreg** [comment]
Good to know, cheers. I'm asking the guys on the Zotero forums for confirmation, but this sounds fair enough.
