### ISSUE TITLE
Extensions to citation format syntax

### ISSUE THREAD

**Issue by alexreg** [retorquere/zotero-better-bibtex#1933]
What came out of [this discussion](https://github.com/retorquere/zotero-better-bibtex/discussions/1932) is the following, as I see it.

1. Currently there's no support for displaying, e.g., at most two authors *including* the `ea` / `EtAl` bit. So, we would either get `AuthorA` (one author), `AuthorA;AuthorB` (two authors, `;` as separator) or `AuthorA;EtAl` (three or more authors). For the record, this concurs with how authors are listed in many places (though it's obviously not the only style).
2. It would be nice to be able to configure the `authors` function to use strings other than `EtAl`, e.g., `ea`, without resorting to hacks like [suggested here](https://github.com/retorquere/zotero-better-bibtex/discussions/1932#discussioncomment-13643520) (although admittedly that should work in 99.9% of cases). An extension to the syntax would again just be more convenient.

**Zotero version:**
5.0.96.3

**BBT version:**
5.4.29

**Support log ID:**
YK3HJUYG-refs-euc

**Exporter used:**
BibLaTeX

**Comment by alexreg** [comment]
Hi @retorquere. Any chance you might be able to get around to this soon? Unfortunately my existing solution has now broken.

**Comment by retorquere** [comment]
It's currently hard to add arguments to this function, and I'm still hashing out the new pattern format, but in the interim, this should do what you want on the current release:

```
[authors+;:replace=\[^;\]+,,regex:longer=1:discard] [authors1+;:replace=;.*,,regex:postfix=;ea] | [authors2+;]
```

what it says is:

first pattern:
* `[authors+;:replace=\[^;\]+,,regex:longer=1:discard]`: 
  * get me all authors, separated by semicolon,
  * replace anything that's not a semicolon by nothing (which leaves just the separating semicolons),
  * if there is *not* more than 1 semicolon (which means there are not more than 2 authors), skip to the next pattern, but otherwise,
  * discard the semicolons
* (we know at this point we have more than two authors) `[authors1+;:replace=;.*,,regex:postfix=;ea]`:
  * get the first author, separated from `EtAl` by a semicolon,
  * replace the semicolon and anything that follows by nothing,
  * add `;ea`

second pattern, we know here that there are not more than two authors
* `[authors2+;]`: get maximum two authors, separated by semicolon. This would append `;EtAl` if there are more than 2, but we know this is not the case, so `;EtAl` never gets added.

**Comment by alexreg** [comment]
Thanks very much for that interim solution. It works nicely except for one thing: in some cases, "ea" is append without a preceding `;`. I think you should see this if you try a journal entry with four authors.

**Comment by retorquere** [comment]
Can you right-click such an entry and send a support log?

**Comment by alexreg** [comment]
@retorquere Here it is: 8BPC7TTA-refs-euc

**Comment by retorquere** [comment]
The entry in `8BPC7TTA-refs-euc` generates `Ladyman;ea` for me, which is what I had expected. Have you refreshed the keys after changing the pattern? Changing the patterns alone does not change existing keys.

**Comment by alexreg** [comment]
Thanks. I didn't inspect the string closely, evidently. And I didn't know about the refresh feature. It seems to be working now. I use the following format, including the year:

```
[authors+;:replace=\[^;\]+,,regex:longer=1:discard] [authors1+;:replace=;.*,,regex:postfix=;ea] :[year] | [authors2+;] :[year]
```

**Comment by alexreg** [comment]
Ah, don't you want to leave this open as a tracking issue for the new format feature? Or is there somewhere else I can follow that?

**Comment by retorquere** [comment]
The new format won't introduce new features, it will just make new features easier to add. When it drops, existing patterns will be turned into the new format automatically.

**Comment by alexreg** [comment]
Okay, sounds fair. So the above format should be automatically updated to its optimal form? If not, I suppose I can ask again...

**Comment by retorquere** [comment]
It is not a matter of optimal form. When (if, even) I settle on a new format, it will initially just be a new syntax to specify exactly the same functionality. It will just be a format that's easier to add new functionality to. If I transform patterns in the existing format to the new format, they'll look very much like what you have, and will work exactly the same.

**Comment by alexreg** [comment]
I see. No change of introducing my above format as a built-in? I believe it's very common in literature.

**Comment by retorquere** [comment]
The chance is there as soon as I've finished the new format. It's harder than I thought, so it's a longer term project, and I don't have an ETA.

**Comment by alexreg** [comment]
Okay, no worries. Thanks for the update and honesty in any case!

**Comment by retorquere** [comment]
> I see. No change of introducing my above format as a built-in? I believe it's very common in literature.

Which citation style does this?

**Comment by alexreg** [comment]
@retorquere It's so widespread it's probably a rule of many style guides, though some style guides seem to leave open multiple acceptable options. I'll cover Harvard and APA, since they are two major ones (perhaps *the* two major ones).

The Harvard style (according to [this guide](https://www.imperial.ac.uk/media/imperial-college/administration-and-support-services/library/public/harvard.pdf) by a major international university, which was the easiest to find for me) specifies the following.

> If the work has two or three authors, include all names in your citation. For more than three authors, see section 5.3.
> ...
> If the work has four or more authors/editors the abbreviation ‘et al.’ should be used after the first author’s name. **It is also acceptable to use ‘et al.’ after the first author if the work has three authors.**

(emphasis added)

For APA, I found an [even more authoritative source](https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/author-date), namely the organisation itself.

> The format of the author element of the in-text citation changes depending on the number of authors and is abbreviated in some cases.
> * For a work with one or two authors, include the author name(s) in every citation.
> * For a work with three or more authors, include the name of only the first author plus “et al.” in every citation (even the first citation).

Hope this convinces you! :-)

**Comment by retorquere** [comment]
Now's the time to test your earlier assertion 😏 . Build 1832 adds support for `[style=<stylename>]` for styles that have been installed in Zotero and will return the in-text citation; that means for example that if the in-text citation includes a year, so will this. A later version will give feedback about whether a style exists while you're entering the pattern, it will currently allow any string. The stylename is the identifier of the style, not it's full name; to get the style `American Psychological Association 7th edition (curriculum vitae, sorted by descending date)`, you would enter `[style=apa-cv]`.

I might change the keyword `style` before release. I was considering `csl=` or `cite=`. I haven't yet found one I really like.

**Comment by alexreg** [comment]
@retorquere Thanks for implementing that. I'm afraid that `[style=apa-cv]` doesn't work for me. It shows as an invalid format and is not accepted.

**Comment by retorquere** [comment]
Do you have apa-cv installed? It's not installed by default

**Comment by alexreg** [comment]
@retorquere Ah, I see. How can I get style identifiers of installed styles?

**Comment by retorquere** [comment]
You can see which styles you have installed in Preferemces -> Cite -> Style manager, and you can find the corresponding ID by searching on https://www.zotero.org/styles. If you've found your style, and you copy the link to it, the end of the URL is the ID.

**Comment by alexreg** [comment]
No luck, I'm afraid. I tried `[style=apa]` and `[style=harvard-bath]`, which are both installed.

**Comment by retorquere** [comment]
This version will give feedback about whether the style is available.

**Comment by alexreg** [comment]
That seems to work now. The APA style corresponds to what I wrote above, while the Harvard style corresponds to one of the variants above (the one that lists all three authors).

Will it be possible to have a simplified form of my above format, in this new system?

**Comment by retorquere** [comment]
If you edit the CSL style, BBT will follow. I thought existing citation styles already did what you want?

**Comment by alexreg** [comment]
They indeed do what I want *in terms of the number of authors and 'et al.'*, but not in terms of the exact format. I'm happy to have https://github.com/retorquere/zotero-better-bibtex/issues/1933#issuecomment-974498887, which works, though a less 'hacky' version would of course be nice.

**Comment by retorquere** [comment]
Alright. I'll keep the style function, but for now, I don't want to add a new bespoke function for this user case. There may be a way to generalize the authors function with parameters that would get you what you want, but that will have to wait for the new pattern format.

**Comment by alexreg** [comment]
Okay, I'll stay tuned for that! Cheers.

**Comment by retorquere** [comment]
>  Currently there's no support for displaying, e.g., at most two authors _including_ the `ea` / `EtAl` bit. So, we would either get `AuthorA` (one author), `AuthorA;AuthorB` (two authors, `;` as separator) or `AuthorA;EtAl` (three or more authors). For the record, this concurs with how authors are listed in many places (though it's obviously not the only style).
> 
>  It would be nice to be able to configure the `authors` function to use strings other than `EtAl`, e.g., `ea`, without resorting to hacks like [suggested here](https://github.com/retorquere/zotero-better-bibtex/discussions/1932#discussioncomment-13643520) (although admittedly that should work in 99.9% of cases). An extension to the syntax would again just be more convenient.

Both are now possible using the [new key formula syntax](https://retorque.re/zotero-better-bibtex/citing/#functions) in the build that will drop here in 10 minutes:

```
authors(min=2,n=1,sep=';',etal=EtAl) + year | authors + year
```

or

```
authors(max=1) + year | authors(n=1,sep=';',etal=EtAl) + year
```

**Comment by alexreg** [comment]
@retorquere Looks great! Thanks.

**Comment by retorquere** [comment]
this is out now in a new release.

**Comment by alexreg** [comment]
@retorquere I think your above example is almost what I want, but not quite. (It doesn't handle the two-author case correctly, displaying both their names.) I think this is what I want?

```
authors(min=3,n=1,sep=';',etal=ea) + ':' + year | authors(sep=';') + ':' + year
```

(I'm not quite sure what the `n` parameter does, mind you!)

**Comment by retorquere** [comment]
If you get me a new debug log for an item where it doesn't do what you want I can have a look. That will give me a copy of the item so we can talk concretely about what is happening and what concrete output we should expect.

`n` is just the number of authors you want to have show up in the citekey, in this case, `1`. `max` means "if there are more than 3 authors, abort the current formula and jump to the next after the `|`"

**Comment by retorquere** [comment]
> (It doesn't handle the two-author case correctly, displaying both their names.) 

For me it does with a two-author item. This is why the log is so important. We don't currently know of each other what we're looking at.

**Comment by alexreg** [comment]
Log ID is Q6MYIW3U-refs-euc

**Comment by alexreg** [comment]
BTW if this requires v6.7, then note that Zotero does not update to that. (It thinks there is no new version.)

**Comment by retorquere** [comment]
Overlapping release builds, thanks for the tip; the issue we were discussing here didn't rely on anything in 6.7.0 but I've issued a build for 6.7.1 which will fix the update problem.

WRT the current issue, with this formula

```
authors(max=1) + ':' + year | authors(n=1,sep=';',etal=EtAl)+ ':' + year
```

and the item from `Q6MYIW3U-refs-euc`, I get `Gebharter;EtAl:2016` as the citekey. If you change the formula and not the item after that, you can right-click on the item(s), and select BBT -> refresh to apply the formula.

**Comment by alexreg** [comment]
@retorquere Yeah, that's the problem. Since there are only two authors, it should be `Gebharter;Schurz:2016`, according to my style. Thanks for the new release in any case.

**Comment by retorquere** [comment]
OK, so then

```
authors(max=2) + ':' + year | authors(n=1,sep=';',etal=EtAl)+ ':' + year
```

would do the trick?

**Comment by alexreg** [comment]
@retorquere Yes, that works, thank you. (I think it does exactly the same as [my above example](https://github.com/retorquere/zotero-better-bibtex/issues/1933#issuecomment-1118059870), but is perhaps a bit more intuitive.) Cheers.

**Comment by retorquere** [comment]
> @retorquere Yes, that works, thank you. (I think it does exactly the same as [my above example](https://github.com/retorquere/zotero-better-bibtex/issues/1933#issuecomment-1118059870), but is perhaps a bit more intuitive.) Cheers.

Oh I thought you meant that didn't work either.

**Comment by alexreg** [comment]
I think both work and are equivalent, unless I'm mistaken. I'll use yours because it's arguably marginally clearer.

**Comment by retorquere** [comment]
Whatever works, literally. I just thought you had uncovered a bug where your formula didn't work.
