### ISSUE TITLE
Case protection missing from some references in the series field

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#1934]
**Zotero version:**
5.0.97-beta.45+571801e1f

**BBT version:**
5.4.29

**Support log ID:**
M9Q8P88W-refs-apse

**Exporter used:**
Better BibLaTeX

**Expected behavior:**
The `series` field should be case-protected, and generally is.

**Actual behavior:**
Case protection is missing from the series field for some, but not all, references. I can't tell why but this one is an example where the case protection is missing.  (This in turn means that `biblatex-sbl` produces a duplicate abbreviations list entry even though the two series names display identically.)

**Comment by retorquere** [comment]
For the reference in `M9Q8P88W-refs-apse`, the `language` field is set to `eng;fre;ger;gre;heb`; only items that have an Engl-ish<sup>*</sup> language set get case handling applied. Zotero nor biblatex understand multiple languages so `eng;fre;ger;gre;heb` is treated as a single language name (which is not Engl-ish).

---
<sup>*</sup> I'm rolling out a change tonight that will make this the following set: american, australian, british, canadian, en, en-au, en-ca, en-en, en-gb, en-nz, en-us, eng, english, english-au, english-australia, english-ca, english-canada, english-gb, english-newzealand, english-nz, english-unitedkingdom, english-unitedstates, english-us, newzealand, ukenglish, usenglish

**Comment by lyndondrake** [comment]
Ah, that makes sense. Where it bites for me is that I have entries which are marked as English (correctly) but with German series names, and in those the series name gets exported with case protection. Other entries with the same German series name have another language tag (also correctly), and get exported without case protection. When the abbreviations list is generated by BibLaTeX, the list has two separate series names: one with case protection and one without — although confusingly, they both render the same.

Also, there is scope for the rendering to not work as the case I've entered is the correct case for those items and applying English case rules to the German series name would be incorrect.

I can see that the behaviour is sensible in general terms, because normal case differs considerably by language. But in this case it generates an unhelpful result for me.

 One option is that I can remove the language from the items. I do use the language field to filter my bibliography but I could convert it to a tag instead, I suppose.

What do you suggest I do?

**Comment by retorquere** [comment]
> Also, there is scope for the rendering to not work as the case I've entered is the correct case for those items and applying English case rules to the German series name would be incorrect.

I'm not sure biblatex supports mixed-language entries -- @njbart, any ideas on this? If there isn't multi-language support (I don't think CSL does either BTW), the only other option I see is to add a forced title using a override like

```
tex.title= Das judäische und das babylonische Jeremiabuch
```

overrides using `=` rather than `:` are output as-is.

**Comment by retorquere** [comment]
Interesting. In biblatex, the `language` field is a list. I don't yet know what hangs on that.

**Comment by njbart** [comment]
Remember that in biblatex, `langid` is defined as "The language id of the bibliography entry" (note the singular!), so this is supposed to contain exactly one language tag. This controls, amongst others, how hyphenation, capitalization, and (if configured to do so) translation of role designations such as "editor", month names and other date elements, etc. are to be rendered in the bibliography entry.

`language` (and `origlanguage`), by contrast, contain possibly free-form descriptions of the language(s) (one or more!) of the full text of the work. Biblatex language identifiers may but do not have to be used (see, e.g., the following entry from http://tug.ctan.org/tex-archive/macros/latex/contrib/biblatex/doc/examples/biblatex-examples.bib).

```
@book{cicero,
  author       = {Cicero, Marcus Tullius},
  title        = {De natura deorum. {\"U}ber das Wesen der G{\"o}tter},
  date         = 1995,
  editor       = {Blank-Sangmeister, Ursula},
  translator   = {Blank-Sangmeister, Ursula},
  afterword    = {Thraede, Klaus},
  language     = {langlatin and langgerman},
  publisher    = {Reclam},
  location     = {Stuttgart},
  langid       = {german},
  indextitle   = {De natura deorum},
  shorttitle   = {De natura deorum},
  annotation   = {A bilingual edition of Cicero's \emph{De natura deorum}, with
                  a German translation. Note the format of the \texttt{language}
                  field in the database file, the concatenation of the
                  \texttt{editor} and \texttt{translator} fields, and the
                  \texttt{afterword} field},
}
```

Inside biblatex fields, users may switch languages using the standard babel or polyglossia commands, a alternative to wrapping strings in `{}` to prevent case transformation. Note that babel or polyglossia commands also affect hyphenation, which is usually desirable.

So both

`series = {{Eine Deutsche Serie}}`

and

`series = {\textgerman{Eine Deutsche Serie}}`

can be expected to prevent case transformation when using sentence-case styles such as biblatex-apa.

The options when exporting from Zotero/CSL are of course limited to wrapping non-English strings in `<span class=”nocase”>...</span>`, which will be exported as the first variant. Indicating which non-English language to use for a particular field or string seems impossible.

Compared to Zotero/CSL, Juris-M/CSL-M seem to provide additional multilingual capabilities, but I have never had a closer look so far.

**Comment by lyndondrake** [comment]
Well, the export is correctly mapping the Zotero language field to biblatex `language`. So the language of the entry (which in both Zotero and BibLaTeX is the language field) is what Better BibTeX is using to determine whether it applies case protection during export.

But that is arguably wrong, as that field in Zotero is not the language of the bibliography entry. In fact, I can't see anything in Zotero which allows a user to define the language of the bibliography entry.

**Comment by retorquere** [comment]
Better BibLaTeX maps `language` to `langid`, not `language`.

**Comment by lyndondrake** [comment]
> the only other option I see is to add a forced title using a override like
> 
> ```
> tex.title= Das judäische und das babylonische Jeremiabuch
> ```
> 
> overrides using `=` rather than `:` are output as-is.

This is probably the simplest way to do it, I guess.

It's a shame there's no way to script Zotero, otherwise I could automate some of this.

BTW everything I'm using Zotero for in terms of `.bib` generation is completely impossible without Better BibTeX. There are so many edge cases not covered by Zotero (or CSL) and so I'm extremely grateful that you've made Better BibTeX. Thank you!

**Comment by retorquere** [comment]
> It's a shame there's no way to script Zotero, otherwise I could automate some of this.

There are actually two ways to script Zotero:

1. if you want to script general Zotero stuff (not necessarily exports), you can use their javascript runner from the tools menu, or you  can use my [debug bridge](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge) if you have scripts you want to run more often.
2. If you want to script something inside BBT, you can use a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/); you could e.g do

```
if (Translator.BetterBibLaTeX && item.title && item.language && item.language.includes(';ger;')) {
  reference.add({ name: 'title', bibtex: '{' + reference.enc_latex(item.title) + '}' })
}
```

you'd probably want a better check than testing for `;ger;` though.

**Comment by retorquere** [comment]
> BTW everything I'm using Zotero for in terms of `.bib` generation is completely impossible without Better BibTeX. There are so many edge cases not covered by Zotero (or CSL) and so I'm extremely grateful that you've made Better BibTeX. Thank you!

You're very welcome. I must admit BBT got a bit out of hand in terms of complexity, but I am fairly confident that Zotero + BBT is the absolute best in bibtex handling for ref managers that aren't bibtex-native like JabRef; certainly a lot better than the well-known commercial offerings. I haven't actually actively used Zotero myself for a few years now; I might at some point get back into the academic game, but I'm currently just working on BBT because I enjoy being part of this community.

**Comment by lyndondrake** [comment]
> 2\. If you want to script something inside BBT, you can use a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/);

I'd forgotten about this. That might well be the way forward.

**Comment by lyndondrake** [comment]
I could also use that to have a dictionary of `shortseries` fields which correspond to the `series` field, for example.

**Comment by retorquere** [comment]
I don't think there's anything else I can do on this issue. If you have more questions, keep 'em coming.
