### ISSUE TITLE
Key Not Generating ShortTitle

### ISSUE THREAD

**Issue by j3902d** [retorquere/zotero-better-bibtex#1936]
**Zotero version:5.0.96.3**

**BBT version:5.4.29**

**Support log ID:4TQIILBR-refs-euc**

**Expected behavior:solzhenitsyn1963ivan-denisovich**

**Actual behavior:solzhenitsyn1963**

Here is the citation key format I'm using:

```
[auth:lower:condense=-:(unnamed)][year:(0000)][ShortTitle:>0:lower:condense=-] | [auth:lower:condense=-:(unnamed)][year:(0000)][shorttitle2_0:lower:condense=-]
```

Key generation was working as expected before it stopped today.

**Comment by retorquere** [comment]
You'd have to use `[ShortTitle:>0][ShortTitle:lower:condense=-]`; `:>0` just aborts the pattern and moves to the next pattern if the input is too short, but if it doesn't abort, it just returns nothing. `[ShortTitle:lower:condense=-]` already outputs nothing if `ShortTitle` isn't available. This hasn't changed in years AFAICR, so it can't just have started happening today.

**Comment by j3902d** [comment]
Thanks for explaining. That fixed it.

**Comment by j3902d** [comment]
> You'd have to use `[ShortTitle:>0][ShortTitle:lower:condense=-]`; `:>0` just aborts the pattern and moves to the next pattern if the input is too short, but if it doesn't abort, it just returns nothing. `[ShortTitle:lower:condense=-]` already outputs nothing if `ShortTitle` isn't available. This hasn't changed in years AFAICR, so it can't just have started happening today.

Thanks for explaining. That solved my problem.
