### ISSUE TITLE
Not clear how to remove .bib from autoexport list

### ISSUE THREAD

**Issue by kbarros** [retorquere/zotero-better-bibtex#1937]
**Zotero version:** 5.0.96.3

**BBT version:** 5.4.29.1591

**Support log ID:** V9HRJNXY-refs-euc

**Exporter used:** Not sure I understand

**Expected behavior:** Expect to be able to remove item from autoexport list

**Actual behavior:** Clicking "Remove" does not remove item from autoexport.

Text description:

Under `Preferences -> Better Bibtex panel -> Automatic export panel`,  I see a list of automatic exports. I would like to remove one of them. When I click the "Remove" button at the bottom, it does not seem to have any action.

**Comment by kbarros** [comment]
I can confirm this new build now allows to "Remove" autoexport items.

Unfortunately, I'm now observing that autoexport stopped working. New files not being written unless I explicitly click "Export now" button... Do you want me to file another issue?

**Comment by retorquere** [comment]
No, just submit a new log here.

**Comment by kbarros** [comment]
Really strange, I can't reproduce it after restarting Zotero.

**Comment by retorquere** [comment]
Then I'm afraid there's nothing more that I can do. The change in 1609 is included in the release build that's running through the tests right now.
