### ISSUE TITLE
Can I emulate the "Export Now" button for a given exported collection?

### ISSUE THREAD

**Issue by llinfeng** [retorquere/zotero-better-bibtex#1938]
Can there be a keyboard shortcut to emulate the act of manually clicking on the "Export Now" button in the following interface? It takes quite a number of clicks to get to this interface.

![image](https://user-images.githubusercontent.com/5890407/135125198-fc900a05-63a2-402d-a72d-a43441a6a374.png)

A CLI call is more favorable if possible. Something like: `executable_for_better_bibtex.exe -export_collection=CollectionName -output_path=path_to_output_bib_file.bib`

----

The reason for asking for a manual shortcut is that I found Zotero constantly running at 50%+ CPU when I turned on Automatic export.

**Comment by retorquere** [comment]
> Can there be a keyboard shortcut to emulate the act of manually clicking on the "Export Now" button in the following interface? It takes quite a number of clicks to get to this interface.

Shortcuts are managed by Zutilo, but I don't see how this would work if you have more than one auto-export.


> A CLI call is more favorable if possible. Something like: `executable_for_better_bibtex.exe -export_collection=CollectionName -output_path=path_to_output_bib_file.bib`

https://retorque.re/zotero-better-bibtex/exporting/pull/
 
> The reason for asking for a manual shortcut is that I found Zotero constantly running at 50%+ CPU when I turned on Automatic export.

If you're not making changes, this should not be happening. If you have a large library, and you're making many changes, this might happen. 50% still sounds like a lot. But without a support log, there's nothing I can do.

**Comment by retorquere** [comment]
Any further questions?

**Comment by llinfeng** [comment]
The Pull Export feature works better than what I would expect. Thanks a lot for the pointer. Though, I jumped through the following hoops:

----

1. One needs to first open Zotero with better-bibtex installed properly. This is no other background service hosting for the `23119` port.
2. As mentioned on the [documentation page](https://retorque.re/zotero-better-bibtex/exporting/pull/), the best way to get the URL for `curl`-ing is to use the `Download Better BibTeX export...` menu entry. It does not worth the effort to compose the link by oneself.
3. On Windows, use `cmd.exe` (Command Prompt) for the first attempt. For those who uses WSL2, connections initiated using `curl http://localhost:xxxx` will be refused. The same command works fine on WSL1 instances.
![image](https://user-images.githubusercontent.com/5890407/135770354-767ac19f-c216-4db0-9093-2a0e830a7487.png)

----

@retorquere Thanks a lot for pointing me in the right direction.
