### ISSUE TITLE
Transforming exported file names (windows path conversion)

### ISSUE THREAD

**Issue by jx1e** [retorquere/zotero-better-bibtex#1939]
**Zotero version: 5.0.96.3**

**BBT version: 5.5.0**

**Your question/suggestion:** Hi, I am using Zotero on windows but I would like the exported file paths to be linux-like (i.e. forward slashes instead of back slashes). 
Example:

```
(current)
file = {storage\\SJGFJW9F\\Wainwright and Jordan - 2007 - Graphical Models, Exponential Families, and Variat.pdf}

(to)
file = {storage/SJGFJW9F/Wainwright and Jordan - 2007 - Graphical Models, Exponential Families, and Variat.pdf}
```
I've tried the following postscript (which I adapted from https://github.com/retorquere/zotero-better-bibtex/issues/910#issuecomment-868969797)
```
if (Translator.BetterTeX && !Translator.options.exportFileData && item.attachments && Translator.exportPath.match('\\\\')) {
  for (const att in item.attachments) {
       att.localPath = att.localPath.replace('\\\\', '/')
  }
  reference.add({ name: 'file', value: item.attachments, enc: 'attachments' })
}
```
but to no avail. I've checked that the if-condition works, but the rest of the body isn't changing anything. Also, for some reason I cannot generate a proper debug log because it just gives me a blank window. Any help will be greatly appreciated.

**Comment by retorquere** [comment]
Let's first look at the problem of the log submission -- can you install https://github.com/retorquere/zotero-debug-log, recreate the problem, then from the help menu select "send log to file.io" and post the resulting ID here.

**Comment by retorquere** [comment]
Never mind -- I can reproduce it.

**Comment by retorquere** [comment]
Can you upgrade to 5.5.1 and try to submit a log again?

**Comment by retorquere** [comment]
There's a few problems with the postscript though:

```
if (Translator.BetterTeX && !Translator.options.exportFileData && item.attachments && Translator.exportPath.match('\\\\')) {
  for (const att in item.attachments) {
```
javascript array values are iterated over with `of`, not `in`; `in` iterates over keys, so in this case you would have gotten `0`, `1`, etc, which are the keys to an array.

```
       att.localPath = att.localPath.replace('\\\\', '/')
```

This will only replace the first `\\` and will leave other `\` characters in place.

**Comment by jx1e** [comment]
> 
> 
> Can you upgrade to 5.5.1 and try to submit a log again?

Updated and it works now.
Example citation: BL3NU539-refs-apse
From help menu: EFRKHWT3-apse


> 
> 
> There's a few problems with the postscript though:
> 
> ```
> if (Translator.BetterTeX && !Translator.options.exportFileData && item.attachments && Translator.exportPath.match('\\\\')) {
>   for (const att in item.attachments) {
> ```
> 
> javascript array values are iterated over with `of`, not `in`; `in` iterates over keys, so in this case you would have gotten `0`, `1`, etc, which are the keys to an array.
> 
> ```
>        att.localPath = att.localPath.replace('\\\\', '/')
> ```
> 
> This will only replace the first `\\` and will leave other `\` characters in place.

Thanks. I'm new to both this and Javascript. I've now tried 
```
if (Translator.BetterTeX && !Translator.options.exportFileData && item.attachments && Translator.exportPath.match('\\\\')) {
  for (const att of item.attachments) {
       att.localPath = att.localPath.replace(/\\/g, '/')
  }
  reference.add({ name: 'file', value: item.attachments, enc: 'attachments'}) // doesn't do anything
  reference.add({ name: 'file1', value: item.attachments, enc: 'attachments'})  // imperfect result
}
```
giving me the following output
````
(extensions.zotero.translators.better-bibtex.relativeFilePaths True)
  file = {storage\\SJGFJW9F\\Wainwright and Jordan - 2007 - Graphical Models, Exponential Families, and Variat.pdf},
  file1 = {..\\..\\..\\..\\C\:/Users/Jacky/Zotero/storage/SJGFJW9F/Wainwright and Jordan - 2007 - Graphical Models, Exponential Families, and Variat.pdf}

(extensions.zotero.translators.better-bibtex.relativeFilePaths False)
  file = {C\:\\Users\\Jacky\\Zotero\\storage\\SJGFJW9F\\Wainwright and Jordan - 2007 - Graphical Models, Exponential Families, and Variat.pdf},
  file1 = {C\:/Users/Jacky/Zotero/storage/SJGFJW9F/Wainwright and Jordan - 2007 - Graphical Models, Exponential Families, and Variat.pdf}
````
Okay, so the "file" field isn't getting modified and the relative paths are strange. I don't want the paths tied to windows so it would be great to have correct relative paths like that of before.

**Comment by retorquere** [comment]
The attachment handling does a lot under the hood that's not easily hooked into. A build will drop here in 10 minutes or so that will allow

```
if (Translator.BetterTeX && !Translator.options.exportFileData && item.attachments && Translator.exportPath.includes('\\\\')) {
  if (item.attachments) {
    reference.add({ name: 'file', bibtex: reference.enc_attachments({ value: item.attachments }, path => path.replace(/\\\\/g, '/')) })
  }
}```

`enc_attachments` has a new parameter that is a function that allows modifying the path just before it is written out.

I'm unlikely to drop this once released, but it seems like a niche case to me, and if attachment-handling must change for some reason, I'm not promising this will never change. I've added a note in the code to refer to this issue, and if I need to change this, I'll comment here.

**Comment by jx1e** [comment]
Some small things that I found that I had to modify:
Replacing all the `\\\\` with `\\`, and
replacing 
```reference.add({ name: 'file', bibtex: reference.enc_attachments({ value: item.attachments }, path => path.replace(/\\\\/g, '/')) })```
with  
```reference.add({ name: 'file', value: reference.enc_attachments({ value: item.attachments }, path => path.replace(/\\/g, '/')), enc: 'verbatim'})```
because the file field wasn't being enclosed in curly brackets. I'm not sure if this is the best thing to do, but everything seems to work out fine now. 

Thank you for all your help and time!

**Comment by retorquere** [comment]
Right -- I think that should work. The `bibtex:` version should just have had `{` and `}` added to the beginning/end, but I think your version is better actually.
