### ISSUE TITLE
Rename old v6.0.0 tag/release?

### ISSUE THREAD

**Issue by qqobb** [retorquere/zotero-better-bibtex#1940]
I noticed that there's a v6.0.0 tag/release from Sep 19, 2018. At some point you might want to rename it, perhaps before Zotero 6 is released.

https://github.com/retorquere/zotero-better-bibtex/releases?after=v5.1.2
https://github.com/retorquere/zotero-better-bibtex/tags?after=v5.1.2

**Comment by retorquere** [comment]
Thanks - I've just removed it.
