### ISSUE TITLE
Add listing of available collections and their IDs to pull export?

### ISSUE THREAD

**Issue by a-fent** [retorquere/zotero-better-bibtex#1941]
The URL for a pull request over HTTP for a collection requires either the internal collection Id or the path. For brevity and stability and for avoiding the pitfalls of URL encoding, the Id is probably preferable.

Would it be reasonable to add an HTTP endpoint that lists available collections in the library and returns them (probably as JSON)? i.e. the return value of the API call `Zotero.Collections.getByLibrary(Zotero.Libraries.userLibraryID, true)`

This would provide local client applications a way to browse and select collection Ids, possibly interactively.

Background: I write in Emacs using .bibs exported from Zotero with BB, and update the .bib from within Emacs based on a specific collection (using a modified version of an old package: https://github.com/vspinu/zotelo). I'd like to update this package to allow picking Ids pulled from BB.

Happy to prepare a PR if this is reasonable, in scope and no security concerns. 

Zotero version: 5.0.96.3 (Linux) 
Support log id: MQVHKW27-euc

**Comment by retorquere** [comment]
It wouldn't be any greater security concern than the existing comms Zotero allows. For this I'd propose a JSON-RPC method (see `content/json-rpc.ts`) that takes an optional library ID or name, defaulting to the personal library), and which responds with the full collection hierarchy. If you want to prep a PR for that, then sure.

What you want (I think) is already possible by getting a pull export in BBT JSON format BTW. That will have much more information than you need, but the collection info is there. But for a PR I'd just walk the hierarchy and return that.

**Comment by a-fent** [comment]
Just to say (belatedly) thanks for the feedback and guidance. I'll try to put a PR together soon, just got delayed working out how to put together the development environment.

**Comment by wolfoo2931** [comment]
I guess this can be closed now.

@a-fent you can find an example on how to use it here: https://github.com/retorquere/zotero-better-bibtex/pull/2133#issuecomment-1114178504

Best Regards,
Oliver, working on [MonsterWriter](https://www.monsterwriter.app/)

**Comment by a-fent** [comment]
Great to see this pull request merged and feature added, looking forward to trying it.
