### ISSUE TITLE
Is the BBT configuration stored (or possible to export) into a file?

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#1942]
**Zotero version:**
5.0.96.3

**BBT version:**
5.5.1

**Your question/suggestion:**
I'd like to easily share my BBT configuration with colleagues. Instead of telling them to change this and this on this and this UI ((sub)sub)windows, it would be more convenient to share a BBT config file. Is there such a file available and, if so, where? Thanks.

Support log ID:

**Comment by retorquere** [comment]
Yep; if you export to "BetterBibTeX JSON", you get all your BBT preferences. If you take that file, and add 

```
const data =
```

to the start, and

```
for (const [k, v] of Object.entries(data.config.preferences)) {
  Zotero.Prefs.set('translators.better-bibtex.' + k, v)
}
```

to the end, you can paste that into the Zotero Javascript runner (Tools -> Developer -> Run Javascript) and that will apply them.

**Comment by dbitouze** [comment]
AFAICS, this file contains also the bibliography entries. The only way to share only the configuration is to remove the `"items"` array, isn't it?

**Comment by retorquere** [comment]
> AFAICS, this file contains also the bibliography entries. The only way to share only the configuration is to remove the `"items"` array, isn't it?

You can in principle just retain the `preferences` section, you don't need anything else.

> BTW, I see the array:
> 
> ```json
>   "version": {
>     "bbt": "5.5.1",
>     "zotero": "5.0.96.3"
>   }
> ```

Nothing, but it might be an indication that you have preferences in the JSON that are no longer used. BBT usually repairs those at next start.

**Comment by dbitouze** [comment]
>You can in principle just retain the preferences section, you don't need anything else.

OK but that's in the `"config"` section which has to be kept, isn't it?

**Comment by retorquere** [comment]
You can strip it down to only the preferences but then you have to replace the `data.config.preferences` accordingly.

**Comment by dbitouze** [comment]
>You can set that in a similar way:
>
> `Zotero.Prefs.set('export.quickCopy.setting', 'a515a220-6fef-45ea-9842-8025dfebcc8f')`
>
> the a51... string is the ID you find at the top of the BBT quick copy translator

The following JavaScript code doesn't work: no error when run but, in Edit → Preferences → Export → Quick Copy, it is written "Loading..." instead of "Better BibTeX Quick Copy: \autocite{citation keys}".

```javascript
const data ={
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "localeDateOrder": "dmy",
    "options": {
      "exportFileData": false,
      "exportNotes": true,
      "keepUpdated": false
    },
    "preferences": {
      "DOIandURL": "doi",
      "ascii": "",
      "asciiBibLaTeX": true,
      "asciiBibTeX": true,
      "autoAbbrev": false,
      "autoAbbrevStyle": "",
      "autoExport": "immediate",
      "autoExportDelay": 5,
      "autoExportIdleWait": 10,
      "autoExportPathReplaceDiacritics": false,
      "autoExportPathReplaceDirSep": "-",
      "autoExportPathReplaceSpace": " ",
      "autoPinDelay": 0,
      "automaticTags": true,
      "auxImport": false,
      "baseAttachmentPath": "",
      "biblatexExtendedDateFormat": true,
      "biblatexExtendedNameFormat": true,
      "biblatexExtractEprint": true,
      "bibtexParticleNoOp": false,
      "bibtexURL": "off",
      "cacheFlushInterval": 5,
      "caching": true,
      "citeCommand": "autocite",
      "citekeyFold": true,
      "citekeyFormat": "[auth][shorttitle][year]",
      "citekeySearch": false,
      "citeprocNoteCitekey": false,
      "csquotes": "",
      "exportBibTeXStrings": "off",
      "exportBraceProtection": true,
      "exportTitleCase": true,
      "extraMergeCSL": true,
      "extraMergeCitekeys": true,
      "extraMergeTeX": true,
      "git": "config",
      "import": true,
      "importBibTeXStrings": true,
      "importCaseProtection": "as-needed",
      "importCitationKey": true,
      "importExtra": true,
      "importJabRefAbbreviations": true,
      "importJabRefStrings": true,
      "importSentenceCase": "on+guess",
      "importUnknownTexCommand": "ignore",
      "itemObserverDelay": 5,
      "jabrefFormat": 0,
      "jieba": false,
      "keyConflictPolicy": "keep",
      "keyScope": "library",
      "kuroshiro": false,
      "mapMath": "",
      "mapText": "",
      "mapUnicode": "conservative",
      "newTranslatorsAskRestart": false,
      "parseParticles": true,
      "patchDates": "",
      "platform": "lin",
      "postscript": "if (Translator.BetterTeX && !item.raw) {\n  const fields = ['title', 'titleaddon','shorttitle','annotation']\n  for (const [name, field] of Object.entries(reference.has)) {\n    if (fields.includes(name)) {\n      reference.add({ name, value: field.value.replace(/(\\$.*?\\$)/g, '<script>{$1}</script>') })\n    }\n  }\n}",
      "postscriptOverride": "",
      "preferencesOverride": "",
      "qualityReport": false,
      "quickCopyEta": "",
      "quickCopyMode": "latex",
      "quickCopyOrgMode": "zotero",
      "quickCopyPandocBrackets": false,
      "quickCopySelectLink": "zotero",
      "rawImports": false,
      "rawLaTag": "#LaTeX",
      "relativeFilePaths": false,
      "retainCache": false,
      "scrubDatabase": false,
      "separatorList": "and",
      "separatorNames": "and",
      "skipFields": "abstract,file,urldate",
      "skipWords": "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum",
      "startupProgress": "popup",
      "strings": "",
      "testing": false,
      "verbatimFields": "url,doi,file,eprint,verba,verbb,verbc",
      "warnBulkModify": 10,
      "warnTitleCased": false,
      "workers": 1
    }
  },
}
for (const [k, v] of Object.entries(data.config.preferences)) {
    Zotero.Prefs.set('translators.better-bibtex.' + k, v)
}
Zotero.Prefs.set('export.quickCopy.setting', '36a3b0b5-bad0-4a04-b79b-441c7cef77db')
```

**Comment by retorquere** [comment]
Does restarting Zotero fix it?

**Comment by retorquere** [comment]
Ah no -- I think that's the ID from the *output* of the BBT JSON translator, which is its own ID. If you look in the Zotero `translators` directory, you'll find a bunch of `.js` files, each starting with a header with an `translatorID`; it's that ID that you want to use. You can add any ID there of a translator that has an `doExport` function; the ID of `Better BibTeX Citation Key Quick Copy` is `a515a220-6fef-45ea-9842-8025dfebcc8f`.

The name of the `Better BibTeX Quick Copy` translator changes in that dropdown depending on the value of BBTs `quickCopyMode`, so to get this autocite option as described, you need a combination of 3 settings:

* `export.quickCopy.setting`: `export=a515a220-6fef-45ea-9842-8025dfebcc8f`, which selects the BBT Quick Copy Translator
* `translators.better-bibtex.quickCopyMode`: `latex`
* `translators.better-bibtex.citeCommand`: `autocite`

BBT preferences can get complicated sometimes.

**Comment by dbitouze** [comment]
Works perfectly well now: many thanks!

Just one other field I forgot, I don't know if it is actually necessary for the export, and I couldn't figure out where to find its ID, sorry: Edit → Preferences → Export →Character Encoding → Import Character Encoding → Unicode (UTF-8)

Otherwise, a button in the BBT config tab to export its config would be _very_ nice! :smile:

**Comment by retorquere** [comment]
BBT doesn't do anything with that setting.

I'll add settings import/export, but just for BBT settings, not other (related) zotero settings.

**Comment by retorquere** [comment]
I haven't yet added prefs import/export.

**Comment by retorquere** [comment]
The import tab now has an "import preferences" button. Export is just BBT-JSON export, which includes the current preferences. You can strip everything but the `config.preferences` from the file if you want, but they do no harm, they're just not read.
