### ISSUE TITLE
Initializing stuck on 'Starting key manager'

### ISSUE THREAD

**Issue by rqhu1995** [retorquere/zotero-better-bibtex#1944]
**Zotero version:** 5.0.97-beta.46+4cfa23050

**BBT version:** 5.5.1

**Support log ID:** LPRCTUWF-apse

**Expected behavior:** BBT correctly initializes.

**Actual behavior:** The pop up window stuck at "Better BibTeX: Initializing, starting key manager." Also, in Zotero Preference panel, after clicking "Better BibTeX" tab, nothing but only "Better BibTeX is loading" is shown.

This bug has been reported by others before. I have referred to those and tried change the configurations in Zotero Advanced Settings as follows, but the problem still remained:

- change the value of **'extensions.zotero.translators.better-bibtex.scrubDatabase'** to true
- change the value of **'extensions.zotero.automaticScraperUpdates'** to false

The log reported was generated after the configurations above.

**Comment by rqhu1995** [comment]
> Can you run this command in a terminal:
> 
> ```
> file '/Users/hurunqiu/NutstoreCloudBridge/我的坚果云/Zotero/better-bibtex-search.sqlite'
> ```
> 
> and get me the output of that command?

OK. The output is:

```
 /Users/hurunqiu/NutstoreCloudBridge/我的坚果云/Zotero/better-bibtex-search.sqlite: data
```

**Comment by retorquere** [comment]
Can you try build 1643?

**Comment by retorquere** [comment]
Can you also stop Zotero (cmd-Q), zip up `/Users/hurunqiu/NutstoreCloudBridge/我的坚果云/Zotero/better-bibtex-search.sqlite`, and attach it here? After that, build 1643 should start up without problems.

**Comment by retorquere** [comment]
Is NutstoreCloudBridge a cloud sync utility like Dropbox? If that is the case, [this](https://www.zotero.org/support/kb/data_directory_in_cloud_storage_folder) applies -- cloud sync should not be used for database files. If it is a file sync service it is fairly likely that file sync has corrupted this search database. This is easily remedied by removing the file and restarting Zotero; BBT will rebuild the database. But if your Zotero database is also synced this way, you are likely to corrupt that too, and that's not restored so easily.

**Comment by rqhu1995** [comment]
> this

Yes, NutstoreCloudBridge is a cloud sync service.

**Comment by rqhu1995** [comment]
> Is NutstoreCloudBridge a cloud sync utility like Dropbox? If that is the case, [this](https://www.zotero.org/support/kb/data_directory_in_cloud_storage_folder) applies -- cloud sync should not be used for database files. If it is a file sync service it is fairly likely that file sync has corrupted this search database. This is easily remedied by removing the file and restarting Zotero; BBT will rebuild the database. But if your Zotero database is also synced this way, you are likely to corrupt that too, and that's not restored so easily.

Yes, NutstoreCloudBridge is a cloud sync service, and both BBT and Zotero SQL files have been synced in this way. I haven't noticed this issue before. I get your point now and I think it's my own problem.

**Comment by retorquere** [comment]
1646 should fix the prefs pane.
