### ISSUE TITLE
create citekey filter function to truncate number of words in [title]

### ISSUE THREAD

**Issue by daggers-camille** [retorquere/zotero-better-bibtex#1947]
**Zotero version:** 5.0.96.3

**BBT version:** 5.5.3

**Support log ID:**  PR4RFDGV-apse

**Expected behavior:**
With a very long title I get a citekey output like 
AUTHOR-year-DecolonisingTheSpecialRelationshipDiegoGarciaTheChagossiansAndAngloAmericanRelations

:abbr would make the title too compressed and equally confusing.

Ideally with something like, idk, :truncateX or :limitX  where X is the max number of words,  I could set the citekey rules as [title:capitalise:truncateX] to chop off part of that title. 

(X could also be defined as max number of characters, but that seems nonintuitive. Goodness knows certain authors love large words.)

**Comment by daggers-camille** [comment]
Support log is **NRJKB5K5-refs-apse**

**Comment by retorquere** [comment]
That's the right kind of log, but something has gone wrong during upload -- can you send a new one?

**Comment by retorquere** [comment]
`FWXC2XNR-refs-apse` has the seam problem as earlier, I'll look into that separately, but `KSIRNHJF-refs-apse` has a title that starts with `Chap10 The assemblage`; `Decolonising` does not appear in `KSIRNHJF-refs-apse`. What would you like the key to be for this entry?

**Comment by retorquere** [comment]
Ha, found the issue with the error report.

**Comment by retorquere** [comment]
I'd rather have an actual example based in the entry in `KSIRNHJF-refs-apse`. `authoryear` could eg be `palan2015` and `bookshorttitle` would be some form of `LegaciesofEmpire`, and `Chap10The assemblage of American imperium` would have to be concatenated in someway, because keys can't have spaces.

If you just tell me the *actual* key you'd like to have, I can see how close I can get, but "something like" is not a sufficiently clear target for me, sorry.

**Comment by retorquere** [comment]
try

```
[=book/bookSection][edtr.etal:lower][auth.etal:upper]-[year]-[title:select=1,6:capitalize]_[ShortTitle:capitalize] | [=journalArticle/report][auth.etal:upper]-[year]-[title:select=1,6capitalize] | [edtr.etal:lower][auth.etal:upper]-[year]-[title:select=1,6capitalize]
```

(I've added the [`select`](https://retorque.re/zotero-better-bibtex/citing/#filters) filter calls)

**Comment by daggers-camille** [comment]
some of the <title:select=1,6:capitalize> were <title:select=1,6capitalize> (missing <:>) but once i fixed that the citekey turned out exactly how i wanted it! i ran a refresh on some of my long citekeys to doublecheck and they are all turning out as supposed to. tysm!! everything is way easier to read now

**Comment by retorquere** [comment]
Sorry about that one. Good like this then yeah?
