### ISSUE TITLE
Magazine article type

### ISSUE THREAD

**Issue by step21** [retorquere/zotero-better-bibtex#1952]
**Zotero version:**
5.0.96.3
**BBT version:**
5.5.4
**Support log ID:**
- (as far as I know the behaviour is as expected, so the support log will not help)
**Exporter used:**
Better Biblatex
**Expected behavior:**
Ideally, item keys for magazine articles and journal articles would be different, so that they can be treated differently.

**Actual behavior:**
Both journal articles and magazine articles are prefixed by `@article`.

**Comment by step21** [comment]
94NSZRR8-refs-euc

**Comment by retorquere** [comment]
So what entry types do you propose instead? The biblatex manual literally says

> **article**: An article in a journal, magazine, newspaper, or other periodical

**Comment by step21** [comment]
I tried to just use the `entrysubtype` in `printbibliography` but unfortunately this did not work. Do you have any suggestions? Additionally, my journal articles do not seem to have this field, so to get only the journal articles I guess I would have to filter on all that do not have entrysubtype?
Any hints welocme :)
