### ISSUE TITLE
Request: add argument to`item.search` JSON-RPC endpoint to allow library ID to be specified

### ISSUE THREAD

**Issue by mhucka** [retorquere/zotero-better-bibtex#1956]
This is a follow up to @retorquere's suggestion to open an issue related to the discussion linked below. Specifically, the request is to extend the `item.search` JSON-RPC endpoint with a way to indicate the ID of the library to be searched. 

(I can't speak to suggested implementation, but just looking at the other endpoint definitions, one idea that comes to mind is to add an optional argument to `item.search` for `libraryID`, following the example of `item.export`.)

### Discussed in https://github.com/retorquere/zotero-better-bibtex/discussions/1955
<div type='discussions-op-text'>

<sup>Originally posted by **mhucka** October 11, 2021</sup>
The documentation indicates that one of the endpoints is [`item.search`](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/#itemsearchsearchterms). Is it possible to search a specific library using this? I can't figure out the syntax to do so and can't find any examples of how to do it.

</div>

Support log ID:

**Comment by mhucka** [comment]
I finally tried it. I must have done something wrong in the installation, but I followed the [instructions above](https://github.com/retorquere/zotero-better-bibtex/issues/1956#issuecomment-943068828) to the letter. To confirm, according to the Zotero Add-ons manager, the new one is the version installed:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1450019/137660384-b0eb92bd-499d-4ccf-a477-c9dad76c4a00.png">

My version of Zotero is 5.0.97-beta.49+9432cb7e7 and I'm running on a macOS 10.14 system. Here are is what happens when I try to use  the `items.search` endpoint. I wrote the folllowing test script:

```python
#!/usr/bin/env python3

from commonpy.network_utils import net

print('-'*70)
print('Without library id:')
url = 'http://localhost:23119/better-bibtex/json-rpc'
headers = {'Content-Type': 'application/json', 'Accept' : 'application/json'}
data = ('{"jsonrpc": "2.0", "method": "item.search", ' + '"params": ["SD9DXAFK"] }')
(response, error) = net('post', url, headers = headers, data = data)
print(response.content)

print('-'*70)
print('With library id:')
url = 'http://localhost:23119/better-bibtex/json-rpc'
headers = {'Content-Type': 'application/json', 'Accept' : 'application/json'}
data = ('{"jsonrpc": "2.0", "method": "item.search", ' + '"params": ["SD9DXAFK", "1"] }')
(response, error) = net('post', url, headers = headers, data = data)
print(response.content)
print('-'*70)

```

Here's the output:

```
----------------------------------------------------------------------
Without library id
b'{"jsonrpc":"2.0","error":{"code":-32603,"message":"[Exception... \\"Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [mozIStorageAsyncStatement.bindByIndex]\\"  nsresult: \\"0x8000ffff (NS_ERROR_UNEXPECTED)\\"  location: \\"JS frame :: resource://gre/modules/Sqlite.jsm :: bindParam :: line 693\\"  data: no]"},"id":null}'
----------------------------------------------------------------------
With library id
b'{"jsonrpc":"2.0","error":{"code":-32603,"message":"[Exception... \\"Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [mozIStorageAsyncStatement.bindByIndex]\\"  nsresult: \\"0x8000ffff (NS_ERROR_UNEXPECTED)\\"  location: \\"JS frame :: resource://gre/modules/Sqlite.jsm :: bindParam :: line 693\\"  data: no]"},"id":null}'
----------------------------------------------------------------------
--Return--
```

I attempted to send a BBT debug log using the previous instructions about debug logs (restarting Zotero with debug enabled, running my test script, right-clicking menu in Zotero, pulling down the BBT menu item to send a log), but at the last step in the dialog for sending an error log, I get this:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1450019/137661302-27f6bb86-c2dd-4039-9b2e-ad26fd10a534.png">

However, I used the "save" option early in the dialog sequence to save a copy of the debug log, and would be happy to send it to you via email (or attach it here, if that's safe to do?). Please let me know what to do.

**Comment by mhucka** [comment]
An update on this: I removed the BBT add-on from Zotero, restarted Zotero, re-installed the regular BBT v5.5.4, restarted again, then tried the test function above. It didn't generate the error I expected above (but also, as expected, didn't do anything with an extra argument for the library id).

I then again installed BBT v5.5.4.1685 from the link above, restarted, tried the test function – and again got the same error:

```
b'{"jsonrpc":"2.0","error":{"code":-32603,"message":"[Exception... \\"Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [mozIStorageAsyncStatement.bindByIndex]\\"  nsresult: \\"0x8000ffff (NS_ERROR_UNEXPECTED)\\"  location: \\"JS frame :: resource://gre/modules/Sqlite.jsm :: bindParam :: line 693\\"  data: no]"},"id":null}'
```

So, if I'm doing something wrong, it's pretty consistent.

**Comment by mhucka** [comment]
Sorry if I missed something – should I try something else?

**Comment by retorquere** [comment]
No, sorry, this was an accidental close because I pushed stuff to master. The test infrastructure of github is currently broken so I cannot release test builds, and these fail silently. I'm working on a workaround for that now.

**Comment by retorquere** [comment]
A new build will drop here that will either work or give a more helpful error message. These two (type of) calls are now equivalent:

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": ["combinatorial", "group name"] }'
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.search", "params": {"terms": "combinatorial", "library": "group name"} }'
```

**Comment by mhucka** [comment]
Sorry to be so late coming back to this. The links above no longer work. Should I try the latest release (5.6.8) instead?

**Comment by retorquere** [comment]
No, these builds expire after about 5 days. I've scheduled a new build for this issue.

**Comment by mhucka** [comment]
Debug logging now seems to work with this update! Thank you. After installing it, restarting, turning on debugging, and trying the [1st curl command above](https://github.com/retorquere/zotero-better-bibtex/issues/1956#issuecomment-962652477), I got the same error as always. I submitted the log; id is D542397479.

```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"[Exception... \"Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [mozIStorageAsyncStatement.bindByIndex]\"  nsresult: \"0x8000ffff (NS_ERROR_UNEXPECTED)\"  location: \"JS frame :: resource://gre/modules/Sqlite.jsm :: bindParam :: line 693\"  data: no]"},"id":null}
```

**Comment by retorquere** [comment]
`D<number>` reports go ti the Zotero devs, I have no access to those. I specifically need a BBT support log; the ID will have `-euc` or `-apse` in it.

**Comment by mhucka** [comment]
Ah, sorry, I forgot that part again. I'll do it over shortly.

**Comment by mhucka** [comment]
OK, tried it, and ....

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1450019/142458345-b1961e14-6237-4a79-92ab-e0f34c28da16.png">

**Comment by mhucka** [comment]
I did it again but used file.io this time.  The id is UYQ1OtH0sz3D-BCI9KRKE.

**Comment by retorquere** [comment]
If the ID doesn't have `-euc` or `-apse`, it's not a BBT support log, and I cannot access it.

**Comment by retorquere** [comment]
> However, I saved a copy of the log before going on to the 2nd panel and getting the error above, and could send you that log.

I'll take that. Can you also test build 1823?

**Comment by rusterx** [comment]
> 🤖 this is your friendly neighborhood build bot announcing [test build 5.6.10.1836](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.6.10.1836.xpi) ("libraryID for export is optional")
> 
> Install in Zotero by downloading [test build 5.6.10.1836](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.6.10.1836.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

Thanks, this version can use item.export as expected.

**Comment by retorquere** [comment]
When @mhucka confirms it works for him too I'll issue a new release.

**Comment by mhucka** [comment]
Good news: it works for me too! I tried both curl commands above and both gave results rather than errors. Well done!

Thank you for all your work on this.
