### ISSUE TITLE
Using Better Bibtex Citekeys in Word to convert Zotero cites back into a Markdown format

### ISSUE THREAD

**Issue by guizar** [retorquere/zotero-better-bibtex#1960]
**Zotero version:**
5.0.97-beta.50+5f61ac23

**BBT version:**
5.5.4

**Support log ID:**
LWZYVPS7-refs-euc

**Expected behavior:**
When enabling _Better Bibtex Citekeys_ I expect to get the reference key:   `[@ceddia2014GovernanceAgriculturalIntensification]`

This used to work but it stopped doing so recently (last time I used this successfully was a couple of months ago, my Zotero might have been updated during that time)

**Actual behavior:**
When enabling _Better Bibtex Citekeys_ and refreshing the Word document I'm getting all the text included in the Extra field 
```
[@tex.pmc= PMC4034233
tex.pmid= 24799696
Citation Key Alias: ceddia2014GovernanceAgriculturala
Citation Key: ceddia2014GovernanceAgriculturalIntensification]
```

**Comment by guizar** [comment]
I'm wondering if it's simpler to just replace the content of the `Extra` field with the bibtext key in a format that is understandable to the parser and remove everything else (e.g. leaving only the `Citation Key:  xxx` part). 

I'd be happy to give this a try. Do you know of a tool that would enable me to automate this?

Thanks again

**Comment by retorquere** [comment]
That's how it's already supposed to work. I haven't yet found why it doesn't.

**Comment by retorquere** [comment]
Can you enable `citeprocNoteCitekey`, restart, try again, and submit a log?

**Comment by guizar** [comment]
**Support log ID:**
DZXKQTZ5-euc

Thanks for the follow up! (and sorry for the delay from my end!)

I followed the steps above but the issue is still present. When switching from any CSL style to the Bibtex style (after refreshing) the fields are replaces with strings of text like:


- CSL STYLE ERROR: reference with no printed form.
- @Citation Key: ewers2008EstimatesReserveEffectiveness
- and so on

**Comment by retorquere** [comment]
Can you choose "Restart with logging enabled" from the help menu, try again, and send a new log?

**Comment by guizar** [comment]
Done! the report code is `SQVW37AH-euc` 
thanks!

**Comment by retorquere** [comment]
Can you do the same with 1856?

**Comment by guizar** [comment]
I tried again and is still showing the same issues.

Log: `MWCMTLZ5-euc`

Thanks!

**Comment by retorquere** [comment]
It's not a fix, I'm trying to establish what happens by adding logging. A new logging build will drop here shortly, can you do the same again with that?

**Comment by guizar** [comment]
Done!
KNI9HCF6-euc

**Comment by retorquere** [comment]
Its a difference in behavior between Zotero release and beta. You can ignore builds that drop here until further notice; I need more information fro the Zotero devs.

**Comment by retorquere** [comment]
If all is well 1858 should *not* work for you.

**Comment by guizar** [comment]
Great, please keep me posted when you need me to make further tests. Cheers

**Comment by retorquere** [comment]
Can you try build 1859?

**Comment by guizar** [comment]
It works!! 😁 when turning refs into bibtex it gives back the citation keys as expected; eg:

_[@griscom2017NaturalClimateSolutions; @seddon2020UnderstandingValueLimits; @tsvcm2021TaskforceScalingVoluntary]_

Log ID: `M54GWJF4-euc`

**Comment by retorquere** [comment]
Thanks for the confirmation.
