### ISSUE TITLE
Exporting Folder/Category. Previous postscript does not work anymore

### ISSUE THREAD

**Issue by stefanopagliari** [retorquere/zotero-better-bibtex#1962]
In order to export the category/folder of an entry, I have this postscript:

`reference.add({ name: 'collections', value: item.collections.map(key => Translator.collections[key] && Translator.collections[key].name).filter(name => name), sep: ', ' })
`
This worked until quite recently, but I can't find this field anymore in my exported bib file. Do you think that any changes in the recent update of Zotero may have changed this?

 
**Zotero version:** 5.0.97-beta.50+5f61ac23a

**BBT version:** 5.5.4

**Comment by retorquere** [comment]
Can't help you without a support log.
