### ISSUE TITLE
Specific BBT citation key format is no longer working for my use case after update

### ISSUE THREAD

**Issue by j-vollen** [retorquere/zotero-better-bibtex#1970]
**Zotero version:** 5.0.97-beta.52

**BBT version:** 5.6.3

**Support log ID:**  
YQ4IHZ2I-refs-euc

**Expected behavior:** 
For the particular reference I've chosen as an example, I am expecting a citation key of 'AzLe19a'. More generally, I want a citation key format with the following structure:

a) If the reference has a single author, [first three letters of first author surname] [last two digits of year] ['a' if no conflicts, otherwise next alphabetical char available]
b) If the reference has two authors, [first two letters of first author surname][first two letters of second author's surname][same as above]
c) If the reference has three authors, [first letter of first author surname][first letter of second author surname][first letter of third author surname][same as above]
d) If the reference has four or more authors, first letter of first author surname][first letter of second author surname][first letter of third author surname][plus sign][same as above]

This was working with the following format until today (Zotero updated today and I also think I allowed for the update of some BBT translators or something, I'm really not sure):

```
[auth1_1][auth1_2][auth1_3][auth1_4:>0]+[shortyear][postfix+1=%(a)s]|
[auth1_1][auth1_2][auth1_3:>0][auth1_3][shortyear]|
[auth2_1][auth1_2:>0][auth2_2][shortyear]|
[auth4_1][shortyear]
```

**Actual behavior:**
Starting today, the citation keys are being generated with the following format:
[first letter of every author up to four][plus-sign][last two digits of year]['a' if no conflicts, otherwise next alphabetical char available]

**Comment by retorquere** [comment]
I have a change coming up that would break your use-case, but there's an equivalent pattern that will work now and after the change:

```
[postfix+1=%(a)s]|
[auth1_1][auth1_2][auth1_3][auth1_4:>0]+[shortyear]|
[auth1_1][auth1_2][auth1_3:>0][auth1_3][shortyear]|
[auth2_1][auth1_2:>0][auth2_2][shortyear]|
[auth4_1][shortyear]
```

the reason is that before, the postfix would be set when the pattern was read; after the change, the postfix will be set as the pattern is executed, and `[auth1_4:>0]+` can jump to the next pattern before the postfix is executed. This change I show here will always execute the postfix.
