### ISSUE TITLE
Why there is a @ in front of the key although there is no @ in the .bib file?

### ISSUE THREAD

**Issue by Pentaonia** [retorquere/zotero-better-bibtex#1972]
**Zotero version: 5.0.96.3**

**BBT version: 5.6.4**

**Your question/suggestion:**
Unfortunately, when I insert a key, the name is always prefixed with an @, which means that the citation can not be identified by LaTeX. Is it possible to prevent the @?

**Comment by retorquere** [comment]
Is that [this](https://marketplace.visualstudio.com/items?itemName=mblode.zotero) extension?

If so, then you'll need to contact the author of that extension. BBT provides the backend for this feature but it expects to be told what to return, and it looks like that extension either hardcodes markdown or defaults to it as the return format.

**Comment by Pentaonia** [comment]
Hi, I found the problem in the extension settings.
In the settings, the access URL to Better bibtex is given, which can be adjusted. In fact, "pandoc" was specified there. Changing it to "biblatex" brought the desired success. 
Perhaps you could indicate in your extension description that you have also included a paragraph on your website. I had to search for a long time until I came to the section where I found this configuration option. So that everyone can see directly which export variants you have included (https://retorque.re/zotero-better-bibtex/citing/cayw/#diy).

But anyway thanks for your fast help and reply!

**Comment by retorquere** [comment]
The README would get terribly unwieldy if I were to describe all integration points of BBT in a way that would make sense to users of other extensions. I think this would be better handled in the README of the VSCode extension.
