### ISSUE TITLE
Export addendums into bibtex file

### ISSUE THREAD

**Issue by fgvieira** [retorquere/zotero-better-bibtex#1975]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT support log from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

If you've verified all of the above, please remove the instructions up to and including this line.

**Zotero version:**
5.0.96.3

**BBT version:**
5.6.4

**Support log ID:**
B56N63WF-refs-euc

**Exporter used:**
BibLatex

**Expected behavior:**
I'd like to include some notes after each bibliography entry, like:
```
Zhou JJ, Vieira FG, He XL, Smadja C, Liu R, et al. Genome Annotation and Comparative Analyses of the Odorant-Binding Proteins and Chemosensory Proteins in the Pea Aphid Acyrthosiphon Pisum. Insect Mol. Biol. 2010;19 Suppl 2:113–22. First two authors contributed equally to this work.
```
I've managed to do it if I add the text as `addendum`, but not sure how I can add it in Zotero (or have BBT export notes as addendum).

**Actual behavior:**
Right now, since I've added `First two authors contributed equally to this work` as a note in Zotero, that is placed in the middle:
```
Zhou JJ, Vieira FG, He XL, Smadja C, Liu R, et al. Genome Annotation and Comparative Analyses of the Odorant-Binding Proteins and Chemosensory Proteins in the Pea Aphid Acyrthosiphon Pisum. Insect Mol. Biol. 2010;19 Suppl 2. First two authors contributed equally to this work.:113–22.
```

**Comment by florianhofhammer** [comment]
Have you tried putting `tex.addendum: First two authors contributed equally to this work` into the `Extra` field in Zotero?
Contents in this format are just copied into the resulting .bib file by BBT, see [the docs](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) for better instructions :)

**Comment by retorquere** [comment]
That is indeed the way to do this.

**Comment by fgvieira** [comment]
That was exactly what I was looking for!
Thanks both.

**Comment by fgvieira** [comment]
Just a follow-up question, is it possible to pass reserved characters through this way?
For example:
```
tex.addendum: \textit{(*First two authors contributed equally to this work)}
```

So that they are interpreted in `latex`?
I've tried and I get:
```
addendum = {\textbackslash textit\{(*First two authors contributed equally to this work)\}},
```

**Comment by retorquere** [comment]
That's the difference in behavior between `tex.<something>:` and `tex.<something>=` and; `=` means "verbatim latex", so in your case, that would be

```
tex.addendum= \textit{(*First two authors contributed equally to this work)}
```
