### ISSUE TITLE
Bibtex export fails, if question mark in journal name

### ISSUE THREAD

**Issue by dl6tud** [retorquere/zotero-better-bibtex#1976]
If the name of the publication in Zotero contains only question marks ("???"), the export fails.

**Zotero version:**
5.0.96.3

**BBT version:**
5.6.4

**Support log ID:**
M5Y2HLPI-euc

**Exporter used:**
Better Bibtex

**Expected behavior:**
Works

**Actual behavior:**
Does not work.

**Comment by retorquere** [comment]
I need a log generated by right-clicing the item that exhibits the problem, and selecting "send BBT support log" from the popup menu. The ID will have `-refs` in it.

**Comment by dl6tud** [comment]
It is not possible to submit the log, because it seems to be empty (see screenshot). Therefore, I attached it.
[2021-11-05T11.11.10.zip](https://github.com/retorquere/zotero-better-bibtex/files/7483808/2021-11-05T11.11.10.zip)
![Bildschirmfoto_2021-11-05_12-12-04](https://user-images.githubusercontent.com/33529919/140502124-b7b0d0f9-50b9-4e50-ac43-304703f03d49.png)

**Comment by retorquere** [comment]
I've just released 5.6.6, can you upgrade and try again?

**Comment by dl6tud** [comment]
The problem is solved in v5.6.7 now. Thank you very much!

**Comment by retorquere** [comment]
Also the original problem with the question marks?

**Comment by dl6tud** [comment]
Yes! I can send the log now, and the problem with the question mark disappeared, too. Thank you!!

**Comment by retorquere** [comment]
That means the questionmark thing was collateral damage, I've not changed anything in that area.
