### ISSUE TITLE
Can't submit support log

### ISSUE THREAD

**Issue by rzach** [retorquere/zotero-better-bibtex#1979]
**Zotero version:** 5.0.96.3

**BBT version:** 5.6.7

**Support log ID:** can't generate a support log

**Expected behavior:** Right click on item, selecting "BBT > Send BBT support log" prompts to restart with debugging enabled. Upon restart, sending a BBT support log generates an ID.

**Actual behavior:** Zotero restarts with loging enabled.  "BBT > Send BBT support log" just shows the "restart with logging enabled prompt". Clicking "Next" produces an empty summary page. Clicking "Next" again results in the "Wait while support log is generated" dialog, and hangs there. No support log ID is produced.

Zotero debug log attached.
[log.txt](https://github.com/retorquere/zotero-better-bibtex/files/7491070/log.txt)

**Comment by retorquere** [comment]
Can you install https://github.com/retorquere/zotero-debug-log/releases/tag/v2.0.8, try to submit a BBT support log, send a file.io debug log from the help menu, and then post the ID from that last action here?

**Comment by rzach** [comment]
S61XQtn95XEC-QMPLCWD2

**Comment by retorquere** [comment]
The previous error was knock-on damage, 1777 should fix both.

**Comment by rzach** [comment]
The behavior remains the same (both inability to submit log, and unprotected caps after :colon)

**Comment by rzach** [comment]
Here is the file.io debug id: 1YTJyyu9eUA3-R4QE7PUN

**Comment by retorquere** [comment]
I'm first trying to solve the problem that underlies the debug log.

**Comment by rzach** [comment]
Will you need more from me for that other than the new file.io log? That was done after trying to send the debug log using the test build

**Comment by retorquere** [comment]
No, a build will drop on #1978 in a few minutes.
