### ISSUE TITLE
When integration with vim, how to specify command in biblatex format? Thanks!

### ISSUE THREAD

**Issue by zuxfoucault** [retorquere/zotero-better-bibtex#1980]
When integration with vim, how to specify command in biblatex format? Thanks!
https://retorque.re/zotero-better-bibtex/citing/cayw/#diy

**Comment by zuxfoucault** [comment]
I get it, something like `let format = &filetype =~ '.*tex' ? 'biblatex&command=parencite' : 'pandoc'`
Thanks!

**Comment by retorquere** [comment]
I need to sit down and fix that bot, sorry about the noise. I don't actually know how the vim integration works (I'm an avid vim user, but the macro language is deep, scary voodoo), I just provide the backend.
