### ISSUE TITLE
resizing window duplicates help and close buttons

### ISSUE THREAD

**Issue by swestlake** [retorquere/zotero-better-bibtex#1982]
**Zotero version:**
5.0.96.3

**BBT version:**
5.6.8 

**Support log ID:**
GZ6ULHJK-euc

**Expected behavior:**

**Actual behavior:**

this error only occurs after installing the bbt addon (doesn't occur on other general occassions)
steps:

1) go to preferences
2) resize window about 1.5 times it's default size

this bug occurs with build test 5.6.8.1797 and stable 5.6.8

this bug may have been around for awhile earlier.. though I am recentlty checking out this plugin on Linux's build of Zotero, the program should be expected to still have its traditional layout unaffected regarding the Help/Close buttons --- which only become noticeably repeated after installing the bbt plugin.

please take a look
thanks

**Comment by retorquere** [comment]
The preferences window is [known wonky](https://groups.google.com/g/zotero-dev/c/glmezJ5JIX4/m/tHxS0eXIAAAJ) -- it is supposed to flow with the size of the elements in it, but it just doesn't. It's apparently a problem in the firefox base, and Mozilla is not using this prefs infrastructure anymore so they're not going to fix it. There's not really anything I can do about this.
