### ISSUE TITLE
Empty menu item in automatic export

### ISSUE THREAD

**Issue by jamespeapen** [retorquere/zotero-better-bibtex#1984]
**Zotero version:** 5.0.97-beta.55+3b993b2af

**BBT version:** 5.6.8

**Support log ID:** SH99WY32-refs-euc

**Exporter used:** Better BibTex

**Expected behavior:** I think there should be a tick option in the menu for automatic export

**Actual behavior:** The menu is an empty entry for automatic export. At first I had not used the Better BibTex exporter and didn't see the keep updated tick in the export options. Now I have auto export working but this menu item is still empty

![Screen Shot 2021-11-11 at 09 46 20](https://user-images.githubusercontent.com/39574560/141317649-be8ebef2-add5-43ef-ace8-3bd08428fe58.png)

**Comment by retorquere** [comment]
This menu was only expected to appear and populate when you have auto-exports set to manual or on idle. build 1816 should fix it.

**Comment by jamespeapen** [comment]
Can confirm it's fixed. Thanks!
