### ISSUE TITLE
Hyphenated words is capitalized incorrectly

### ISSUE THREAD

**Issue by Kipsora** [retorquere/zotero-better-bibtex#1985]
**Zotero version:** 5.0.96.3

**BBT version:** 5.6.8

**Support log ID:** 5SZ44ZR6-refs-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** The word "pre-training" in title case should be "Pre-training"

**Actual behavior:** The word is rendered as "Pre-Training"

**Comment by retorquere** [comment]
BBT uses the Zotero titlecaser -- this is a problem that exists in Zotero itself. If you create a bibliography for this item in `Chicago Manual of Style 17th edition (author-date)` you'll get the same problem.

**Comment by Kipsora** [comment]
Thanks for your prompt response. So I guess currently the only existing workaround is to use `<span class="nocase">`?

**Comment by retorquere** [comment]
I think so, yes, but I'd appreciate it if you'd report this on the zotero forums.

**Comment by Kipsora** [comment]
OK. Thanks!

**Comment by retorquere** [comment]
@njbart do you known what capitalization bib(la)ex expects here?

**Comment by njbart** [comment]
bibtex and biblatex merely expect users to enter titles in title case in whatever variant they see fit.

CMOS does recommend the variant preferred by the OP. (See CMOS as well as adamsmith’s comment [here](https://forums.zotero.org/discussion/comment/393632/#Comment_393632).)

Zotero/citeproc-js’s titlecaser seems to implement CMOS’s rule 2 but not 3.

So short of changing the titlecaser, the only workaround I’m aware of is indeed is to use `<span class="nocase">`.

FWIW, CMOS mentions, but does not recommend a different variant at the end of 8.161:

> Under another, simplified practice that is not recommended by Chicago, only the first element and any subsequent element that is a proper noun or adjective are capitalized.

So, arguably, "Pre-Training" is not wrong per se, it just follows rules different from what CMOS recommends.

**Comment by Kipsora** [comment]
So I asked people on Zotero forum, the guy suggested me to use [non-breaking hyphens](https://graphemica.com/%E2%80%91) ("‑", note this is different from "-" though they look the same), which I guess can be served as an alternative workaround to people who are looking for a solution.

**Comment by retorquere** [comment]
So, can we close this?

**Comment by Kipsora** [comment]
Yeah you can close it. I just leave here a message for people who also attempt to find a solution.
