### ISSUE TITLE
Is it possible to directly generate Latex commands that reference multiple files?

### ISSUE THREAD

**Issue by Yujie-Cui** [retorquere/zotero-better-bibtex#1986]
I have multiple papers explaining the same phenomenon. When I write the background of my thesis, I need to cite them. Is there a way that I can directly get the command of \cite{paperA_cite_key,paperA_cite_key,paperA_cite_key,paperA_cite_key}. Just like in Medeley.

Thanks

**Comment by retorquere** [comment]
Yes, you can: https://retorque.re/zotero-better-bibtex/installation/preferences/export/#quick-copy, set format to `LaTeX citation` and LaTeX command to `cite` (which is the default).

**Comment by Yujie-Cui** [comment]
Thank you very much for your reply. But there are still some problems. When I select the papers, click ctrl+shift+c, and then paste it into my latex file. It will appear the corresponding bib entry. This is what I want.

But when I select the papers, click ctrl+shift+A, and then paste it into my latex file. It will appear [1]-[3]. This is not what I want, what I want is \cite{paper_a_citekey,paper_b_citekey}

![image](https://user-images.githubusercontent.com/89470132/142335444-4a22880b-2716-4636-8a50-c5ca93323eef.png)

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/export/#quick-copy:

> In the Zotero “Export” pane, choose `Better BibTeX Quick Copy` as the default export format for quick copy

Zotero allows only one quick-copy format, so if you want quick copy of citations in the way you describe, you can't also have quick-copy of bibtex entries. There's nothing I can do about that.

**Comment by Yujie-Cui** [comment]
> In the Zotero “Export” pane, choose Better BibTeX Quick Copy as the default export format for quick copy
![image](https://user-images.githubusercontent.com/89470132/142422108-a863e43d-dc86-4242-8a96-0371593dbbf4.png)
In the Zotero “Export” pane, it seems that Better BibTeX Quick Copy is not set as the default option here. I only want commands that can generate \cite{}.
![image](https://user-images.githubusercontent.com/89470132/142422209-6317ff1c-6931-488e-adb3-a4535944634f.png)
When I set the cite keys, but nothing seems to change.

The version I use is:

![image](https://user-images.githubusercontent.com/89470132/142422395-26e40fa3-aa10-453f-a1bc-461ea25bb713.png)

**Comment by retorquere** [comment]
To get quick-copy of the kind you describe, you need to set the `Default Format` in the first screen that now says `IEEE` to `Better BibTeX Quick Copy`.

**Comment by Yujie-Cui** [comment]
Thank you very much! It worked.
