### ISSUE TITLE
.bib not recognised by autocomplete-bibtex due to no curly brackets for month entry

### ISSUE THREAD

**Issue by tomislavmedak** [retorquere/zotero-better-bibtex#1987]
**Zotero version:** 5.0.96.3

**BBT version:** 5.6.8

**Support log ID:**

**Exporter used:** BetterBibtex

**Expected behavior:** A .bib file that works with autocomplete-bibtex in Atom

**Actual behavior:** Autocomplete-bibtex fails to recognise .bib file.

This might be an autocomplete-bibtex issue and I've reported on the project's GitHub page, but reporting here as well as it is connected with export formatting. A BetterBibTex export file for my entire library would not be recognised by autocomplete-bibtex, whereas an export file for subcollection works as expected. Today I was able to establish what caused the problem.

The entry in my .bib file that broke the bib file had the following format:

```
@misc{unfccc_glasgow_2021,
  title = {Glasgow {{Climate Pact}}: Advance {{Version}}},
  author = {{UNFCCC}},
  year = {2021},
  month = nov
}
```

The bit of code causing problems was the name of the month with no curly brackets ending up as the last line of code before the closing curly bracket. If I manually added curly brackets, or pasted after the month another entry with curly brackets, autocomplete-bibtex would work fine.

References where there's nothing after the month entry are quite rare -- in my entire Zotero library with some 2000 references I found only three.

But also, the month entry is the only entry in export not wrapped in curly brackets.

**Comment by retorquere** [comment]
I'd suggest taking this up with autocomplete-bibtex first -- this is a valid bibtex entry, `nov` is a pre-declared string in bibtex to allow localization of the date.

**Comment by retorquere** [comment]
BBT can also export citeproc YAML, which is also supported by autocomplete-bibtex it seems. Should be faster too as it's substantially simpler to parse.

**Comment by retorquere** [comment]
If you want to fix this, you can do it with a postscript:

```
if (Translator.BetterBibTeX && reference.has.month && reference.has.month.bibtex[0] != '{') {
  reference.has.month.bibtex = '{' + reference.has.month.bibtex + '}'
}
```

but otherwise I think this should be addressed in the atom plugin.

**Comment by tomislavmedak** [comment]
Awesome, thank you, Emiliano!
