### ISSUE TITLE
How to prevent BetterBibLaTeX from escaping braces in author names (institution name)

### ISSUE THREAD

**Issue by newuserofthis** [retorquere/zotero-better-bibtex#1988]
**Zotero version:**
5.0.96.3

**BBT version:**
5.6.8

**Support log ID:**
2EWDGA7X-refs-euc

**Exporter used:**
BetterBibLaTeX

**Expected behavior:**
Author with braces without escaping

**Actual behavior:**
Braces are escaped.

My author is an institution and and I put it in braces. When I export with BetterBibLaTeX the braces around the author are escaped. What settings need to be made to prevent BetterBibLaTeX from escaping. Thank you very much for your help!

`@online{DeutscherLandkreistag_2021_AufgabenDerLandkreise,
title = {Aufgaben der {{Landkreise}}},
author = {\{Deutscher Landkreistag\}}
}`

**Comment by retorquere** [comment]
If you change the name to single-field mode by clicking the white bar to the left of the name (if you hover you will see "Switch to single field") and remove the braces, I think you will get the output you want.

**Comment by newuserofthis** [comment]
Sorry, I overlooked this bar. Works perfectly. Thanks for answering so swiftly!
