### ISSUE TITLE
item.export entry point need librayID

### ISSUE THREAD

**Issue by rusterx** [retorquere/zotero-better-bibtex#1989]
I saw from <https://retorque.re/zotero-better-bibtex/exporting/json-rpc/> that better bibtex can export bibtex entry. I used the api of item.export and the following code before, and it can be exported normally. The item.export interface shows that if libraryID is not provided, My Library will be used by default. But now the libraryID must provide, otherwise it will report an error. But I don't know where to get this libraryID.

```js
let pyload = JSON.stringify({
     "jsonrpc": "2.0",
     "method": "item.export",
     "params": [
         keys, "biblatex"
     ]
});
```

The reported error is:

```text
must have required property'libraryID'
```

If you've verified all of the above, please remove the instructions up to and including this line.

**Zotero version:** 5.0.97-beta.56+32a5826a1

**BBT version:** 5.6.10

**Support log ID:**

**Exporter used:**

**Expected behavior:** No need provide libraryID with default library.

**Actual behavior:**

**Comment by rusterx** [comment]
I only want to use item.export for local library rather web library. So, I don't know how to get libraryID.

**Comment by retorquere** [comment]
I'm doing related work on #1956, can you join that issue? I have the problem fixed on a build that will drop there in 10 minutes or so.
