### ISSUE TITLE
Zotero does not respond, CPU usage is high （15-20%）, disabled better-bibtex is workon and everything is OK。  5.6.10

### ISSUE THREAD

**Issue by bujianbusan** [retorquere/zotero-better-bibtex#1991]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by restarting Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled), reproducing your problem, and selecting "Send Better BibTeX suupport log" from the help menu.

If you tried to submit BBT a support log and ended up with an ID looking like `D<number>`, that is a Zotero debug report, which I cannot access. Please follow the instructions exactly -- your support log ID should end in `-euc` or `-apse`.

**I AM NOT KIDDING ABOUT THIS. *PLEASE* INCLUDE A DEBUG LOG. I WILL END UP ASKING FOR IT ANYWAY**

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a log of what Zotero was doing at the time of error. Without it, I'm effectively blind.

If you've verified all of the above, please remove the instructions up to and including this line.

**Zotero version:**

**BBT version:**

**Support log ID:**

**Expected behavior:**

**Actual behavior:**

**Comment by retorquere** [comment]
Have you even *glanced* through the instructions in the message template? I am *obviously* not experiencing this problem, or I would be fixing it. There is no way for me to sensibly even *guess* what causes BBT to do this on your system.

**Comment by bujianbusan** [comment]
OS is win11.  This problem had been solved. This should be an accident. In addition, it may be related to my synchronization device process.

**Comment by bujianbusan** [comment]
Thanks！
