### ISSUE TITLE
Question about pin

### ISSUE THREAD

**Issue by jing-bi** [retorquere/zotero-better-bibtex#1996]
**Zotero version:**
5.0.96.3
**BBT version:**
5.6.11

Thanks for the awesome tool, it indeed makes my left easier, good work!

## Question
When doing the pin citation key action, is there a way I can clean the extra field and only add the citation key without the prefix "Citation Key"?
The behavior now is the append the citation key to the existing text.

**Comment by retorquere** [comment]
Not possible, no. This is just zotero's way for adding extra "fields", so this is the only way to save the citekey in the item.

What problem are you experiencing with this line in the extra field?

**Comment by jing-bi** [comment]
Not a big problem, I'm trying to locate some attachment with citation key but you know zotero only allow you to find things with zotero namespace, so I thought if I can have the extra only used for citation key, I can do many things but sadly this is not possible.

Thanks for the prompt response!

**Comment by retorquere** [comment]
I don't quite follow what you're trying to do that you cannot currently do. If you search for the citekey with the `Citation Key:` in the extra field, don't you find it?

**Comment by jing-bi** [comment]
Oh the my use case is that I use citation key to create note like [citation key].md now I want to locate this note and open it with a specific app (not the default for markdown). I want to achieve this by using zotero [look up engine ](https://www.zotero.org/support/locate) but unlikely it doesn't provide a citation key name space nor the way to extract the key from extra, so I have to store the citation key somewhere before using it.

Does it make sense to you.

**Comment by retorquere** [comment]
I don't follow, sorry.

**Comment by jing-bi** [comment]
that's cool, I've find another way out. Thanks for your help!
