### ISSUE TITLE
"Copy as BibLaTeX" does not respect separators

### ISSUE THREAD

**Issue by alexreg** [retorquere/zotero-better-bibtex#1997]
**Zotero version:**

5.0.96.3

**BBT version:**

5.6.11

**Support log ID:**

ILS86C5E-refs-euc

**Exporter used:**

BibLaTeX (`Copy as BibLaTeX` in Edit menu)

**Expected behavior:**

The configured separator should be used in name fields, as per https://github.com/retorquere/zotero-better-bibtex/issues/1927, e.g.,

`SurnameA, FirstnameA | SurnameB, FirstnameA`

**Actual behavior:**

The default `and` separator is used, e.g.,

`SurnameA, FirstnameA and SurnameB, FirstnameA`

**Comment by retorquere** [comment]
You'll have to set "Better BibLaTeX" as the default export format in the "Export" pane of the preferences. You currently have "BibLaTeX", which is the Zotero biblatex export.

**Comment by alexreg** [comment]
Oh I see. I didn't know this was built into Zotero. Thanks.

**Comment by retorquere** [comment]
Just to be sure - if you set the default export format to "Better BibLaTeX" rather than "BibLaTeX", you'll get what you want.
