### ISSUE TITLE
google scholar like citekey

### ISSUE THREAD

**Issue by luoxiaojie9527** [retorquere/zotero-better-bibtex#1999]
**Zotero version:5.0.96.3**

**BBT version:5.6.11**

**Support log ID:NHSQBSMH-refs-apse**

**Expected behavior:afanasyev2019towards**

**Actual behavior:afanasyev2019blockchainbased**

It seems the BBT ignore words like "towards, a, for..." when generating citekey

**Comment by retorquere** [comment]
By default, it does, yes. If you don't want that, you can use either `Auth` instead of `auth`, or edit the [skipWords](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#skipwords) to remove `towards` etc.

**Comment by luoxiaojie9527** [comment]
I want to keep `towards`, but remove `the,` `an`,etc as google scholar BibTex. 
For example, the google scholar BibTex citekey of  the paper "Towards Blockchain-based Multi-Agent Robotic Systems: Analysis, Classification and Applications" is `afanasyev2019towards`. 
While, for the paper "The swirlds hashgraph consensus algorithm: Fair, fast, byzantine fault tolerance", it is `baird2016swirlds`.
If I use `[auth:lower][year][veryshorttitle:lower]` in BBT, I can get `baird2016swirlds`, but I can't get `afanasyev2019towards`. While if I use  `[auth:lower][year][Title:lower:select=1,1]`, I can get `afanasyev2019towards`, but I can't get `baird2016swirlds`.

**Comment by retorquere** [comment]
So why not just remove "towards" from the skipwords and use `auth`?

**Comment by luoxiaojie9527** [comment]
How to remove "towards" from the skipwords

**Comment by retorquere** [comment]
At the top of the page I linked to you will find instructions on how to get to the hidden preferences, once there, the skipwords is just a string of comma separated words, and you can just remove towards from it.

**Comment by qqobb** [comment]
@luoxiaojie9527: Did you try this: https://github.com/retorquere/zotero-better-bibtex/issues/1705#issuecomment-749546297?

**Comment by luoxiaojie9527** [comment]
Hahhah, it works after I remove "towards" from the skipwords list under the instruction of you mentioned. Thank you！ @retorquere
