### ISSUE TITLE
Feature request: Enable user to customize whether BibTeX fields get curly brackets or double quotes

### ISSUE THREAD

**Issue by waeiski** [retorquere/zotero-better-bibtex#2000]
**Zotero version:** 5.0.96.3

**BBT version:** 5.6.11

**Support log ID:** [YK5NBJ2F-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/7719873/YK5NBJ2F-euc.zip) 

**Exporter used:** BetterBibtex

Is it possible to export a BibTeX file where the fields are not encased in curly brackets, but in double quotes? If not, this could be a good feature to add. Curly brackets protect how bibliographical entries are written in the LaTeX document and in some cases these need to be modified according to style guides. This results in a lot of tedious work of replacing the curly brackets to double quotes.

For example, a current entry in my .bib file after exporting with BBT looks like this:

```
@article{Bereitschaft2015,
  title = {Neighborhood Diversity and the Creative Class in {C}hicago},
  author = {Bereitschaft, Bradley and Cammack, Rex},
  year = {2015},
  journal = {Applied Geography},
  volume = {63},
  pages = {166--183},
  doi = {10.1016/j.apgeog.2015.06.020},
  url = {www.sciencedirect.com/science/article/pii/S0143622815001642},
  urldate = {2021-11-09}
}
```
However, I would love to have the option to change the values to double-quoted ones instead:

```
@article{Bereitschaft2015,
  title = "Neighborhood Diversity and the Creative Class in {C}hicago",
  author = "Bereitschaft, Bradley and Cammack, Rex",
  year = "2015",
  journal = "Applied Geography",
  volume = "63",
  pages = "166--183",
  doi = "10.1016/j.apgeog.2015.06.020",
  url = "www.sciencedirect.com/science/article/pii/S0143622815001642",
  urldate = "2021-11-09"
}
```
Thank you, regardless whether you think this is a valuable feature to add.

**Comment by retorquere** [comment]
@njbart I thought these were equivalent? Is there a difference in behavior between quoted and braced fields?

**Comment by njbart** [comment]
They are not completely equivalent (see below), but I also see no advantage in introducing an option to permit outer double quotes. In particular, BBT would have to start protecting straight double quotes that are part of the content of a field.

I would also be interested to know if the OP can name a specific use case. In my opinion, the two versions shown above are indeed completely equivalent.

Relevant bits from http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf:

![Screenshot 2021-12-15 at 15 55 11](https://user-images.githubusercontent.com/2765811/146211326-52081cb7-bd7f-42ec-a1f7-b3adcf5c41c8.png)

**Comment by waeiski** [comment]
Thank you for following up on this.

I have to apologize right away to @retorquere and @njbart, it turns out this is a non-issue. Instead of submitting a feature request, I should have tested it on my own before typing anything here. After doing some testing with this on a test document, I can confirm that this issue was merely a perceived one by myself and my colleagues, that resulted from half of us having used double quotes for many years and a misunderstanding of what curly braces are for. The issue can be closed, I'm sorry for taking your time with this.

**Comment by retorquere** [comment]
> Thank you for following up on this.
> 
> I have to apologize right away to @retorquere and @njbart, 

Not as far as I'm concerned. I legitimately didn't know either, that's why I asked @njbart. I am a fairly naive user of bibtex. I just happen to be good enough at programming here to make a difference, but all the knowledge that makes bbt works comes from examples from the field like this could have been, and experts like Nick.

**Comment by njbart** [comment]
No problem. Sometimes things are just not that obvious.
