### ISSUE TITLE
citeprocNoteKey method for using citation keys in CSL formats fails if citation key contains colon ":"

### ISSUE THREAD

**Issue by kbauer** [retorquere/zotero-better-bibtex#2002]
See also https://forums.zotero.org/discussion/93523

## Steps to reproduce

1. Create a library entry with `Citation Key: prefix:keyname` in the "Extra" field, i.e. an entry with a pinned citation key `prefix:keyname` and select it.
2. Add the ["Better BibTeX Citekeys" style](https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/master/better-bibtex-citekeys.csl).
3. In Zotero Preferences > Cite select the "Style Editor" or "Style Preview" and select the Better BibTeX Citekeys style.

## Expected behavior

In the preview, the citation should be shown as `[@prefix:keyname]`.

## Actual behavior 

Instead it is shown as `[[CSL STYLE ERROR: reference with no printed form.]]`.

![image](https://user-images.githubusercontent.com/7498468/146548785-53233b55-d603-4cb6-8d17-b2b05eddc64b.png)

**Zotero version:** 5.0.96.3

**BBT version:** 5.6.11

**Support log ID:** MJQ5PQN8-euc

**Comment by retorquere** [comment]
This build should make `citation-key` available to styles.

**Comment by kbauer** [comment]
I am getting

    The add-on "Better BibTex for Zotero" could not be installed. It may be incompatible with this version of Zotero.

Is there some way to test without installing the Beta version of Zotero? It is hard to go back to the release version after using the Beta version, so I'd rather avoid it.

**Comment by retorquere** [comment]
It should absolutely work on both the beta and the current release of zotero - if a release drops here, it has passed the test suite, and that actually installs the client to run the tests. What OS are you on? And what browser did you use to download the build?

**Comment by kbauer** [comment]
@retorquere 
I am on Open Suse 15.2 64bit, using Google Chrome.

**Comment by retorquere** [comment]
That should work, and the fact you extracted the RDF should already have told me that the download wasn't corrupted. How did you install zotero?

**Comment by kbauer** [comment]
Zotero is installed manually into `/home/kdbauer/.local/opt/Zotero_linux-x86_64/zotero`. Probably by downloading from https://www.zotero.org/download/ and extracting it there. I have `Zotero-5.0.96.3_linux-x86_64.tar.bz2` in my `~/Downloads` anyway.

**Comment by retorquere** [comment]
That should just work. But I've made it so that it would be a ton of work to create a release that doesn't install and passes all the tests. It's not structurally the plugin. Build 1890 could not have dropped if that were the case. I'll have to hit the zotero forums for help on this one.

**Comment by retorquere** [comment]
Installs without a problem for me on Linux and MacOS.

**Comment by kbauer** [comment]
Upon looking into the "Error Console" I found that a "Unix Error 5" was reported, i.e. some issue on the level of opening the file. Entirely unclear why; I can interact normally with any other program. After moving the file to /tmp/ it worked. So this means that the error message in the Addons dialog was misleading.

However, after successful installation, the results are not desirable. With the existing "Better BibTeX Citekeys" I now get (Support Log ID SPTDS6C8-euc):

```
[@Citation Key: prefix:keyname]
[@Citation Key: Chauvicourt2019]
[@Page Version ID: 973296033 Citation Key: wiki:TrigonometricPolynomial]
[@Citation Key: Kantorowitsch1956]
[@Citation Key: Urabe1966]
[@Citation Key: Urabe1965]
[@Citation Key: uni-stuttgart.de/NLvibInstitut]
[@Page Version ID: 1037873708 Citation Key: wiki:RungeKutta]
```

and upon replacing "note" with "citation-key"

```
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
[[CSL STYLE ERROR: reference with no printed form.]]
```

![image](https://user-images.githubusercontent.com/7498468/146636139-be3cb1c7-5467-4269-965c-d58bf226864c.png)

**Comment by retorquere** [comment]
> Upon looking into the "Error Console" I found that a "Unix Error 5" was reported, i.e. some issue on the level of opening the file. Entirely unclear why; I can interact normally with any other program. After moving the file to /tmp/ it worked. It might also have been related to the disk being full (some leakage problem in /var). So this means that the error message in the Addons dialog was misleading.

OK. Strange that you could still extract `install.rdf`.

> However, after successful installation, the results are not desirable. With the existing "Better BibTeX Citekeys" I now get (Support Log ID SPTDS6C8-euc):
> 
> ```
> [@Citation Key: prefix:keyname]
> [@Citation Key: Chauvicourt2019]

I don't know what you mean by `With the existing "Better BibTeX Citekeys"`. What actions are you performing? Oh wait, the CSL style? Yes, then these results are as I expected. The CSL style adds the `[@` and `]`, the patch provides the Citation Key line, and the style just outputs `note` there. So the patch in and of itself worked. 

> and upon replacing "note" with "citation-key"
> 
> ```
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> [[CSL STYLE ERROR: reference with no printed form.]]
> ```

Just learned from the forums that the `citation key:` format doesn't yet work in Zotero. Try build 1896, which sets `citation-key` directly. If that doesn't work, I'll add the `citation-key:` form to the `extra` field.

Can you try build 1896?

**Comment by kbauer** [comment]
With 1896, the `citation-key` variable now works, including keys with colon `:` character, see screenshot:

![image](https://user-images.githubusercontent.com/7498468/146671597-0425dfff-439e-4f5a-9e5b-24b5fbbc73bc.png)

**Comment by retorquere** [comment]
Fantastic, that means the cleanest option works, and it will automatically transition when zotero adds a citation key field.

**Comment by retorquere** [comment]
> Just for future reference, is there somewhere I can see what the CSL processing layer actually *sees* as input?

I have no absolutely no idea. I've combed through the citeproc sources before, but found myself in a maze of twisty passages. I can't see the overall structure.
