### ISSUE TITLE
Support "citation-key" variable in addition to "citeprocNoteKey" workaround

### ISSUE THREAD

**Issue by kbauer** [retorquere/zotero-better-bibtex#2003]
**Zotero version:** 5.0.96.3

**BBT version:** 5.6.11

**Support log ID:** MJQ5PQN8-euc

**Exporter used:** ??

**Cross references:** 
  - https://forums.zotero.org/discussion/93523
  - https://github.com/retorquere/zotero-better-bibtex/issues/2002

As discussed in the Forum, CSL has, or will have as of 1.0.2, a `citation-key` variable for the purpose of using explicit keys in the bibliography or citation formats.

Currently, this field is exported by neither Zotero's native exporter nor by BBT.

![image](https://user-images.githubusercontent.com/7498468/146550882-5acba779-0e25-429b-b008-b3c4060eb876.png)

Once supported, the option `citeprocNoteKey` will be obsolete, though likely required for compatibility with existing workflows / documents.

**Comment by retorquere** [comment]
This is going to be solved by #2002 -- if the information on the forum is correct, you should just be able to use the `citation-key` variable without relying on abuse of the `note` field, and I'm just going to replace the note-field hack with `citation-key` support.
