### ISSUE TITLE
Issue with CAYW scannable-cite format export

### ISSUE THREAD

**Issue by rlasse** [retorquere/zotero-better-bibtex#2007]
Hi, 

I am experiencing an issue with pulling scannable-cite citations through CAYW. I have been using zotpick's scripts to open BBT to Scrivener both by using davepwsmith's app and by making my own automation service. (https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-scannable-cite.applescript) The CAYW UI opens without any issues and I'm able to pick Zotero items. But in every case, BBT exports the following message instead of exporting the scannable-cite citation:
"CAYW failed: TypeError: item.uri is undefined
Scannable-cite@chrome://zotero-better-bibtex/content/better-bibtex.js:81160:15"

Every other format query seems to work just fine (pandoc, mmd, ...), so I'm guessing this is an issue with the scannable-cite format?

Below I attached a debug log. I would very much appreciate your help!

_What I tried:_
-accessing the CAYW through terminal (same outcome)
-reinstalling BBT and zotpick scripts (same outcome)
-clearing Zotero cache (no effect)

----
Application: Zotero 5.0.97-beta.59+abe8c39c5 en-US
Platform: MacIntel Intel Mac OS X 10.16

[87XAHELY-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/7747915/87XAHELY-euc.zip)

**Comment by retorquere** [comment]
Can you install 1904, do that again, and send a new log?

**Comment by rlasse** [comment]
Just updated to 1904, the issue is still present unfortunately. Here is the log.
[SUH5RA6U-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/7758787/SUH5RA6U-euc.zip)

**Comment by retorquere** [comment]
I know it's still present, this just adds logging.

Is the reporting facility not working properly for you? If you click submit you ought to see the ID presented in red, that will give me the logs. The zip files work, but I have tools that pick up the log based on the id, and those make it easier to create test cases when needed. Not wholly relevant to your case, as I don't expect I will need to add a testcase for this, but if the reporting is broken I'd need to fix it.

**Comment by rlasse** [comment]
Oh very sorry about that. I was able to submit it now, it was greyed out before. ID: DZHAPAVG-euc

**Comment by retorquere** [comment]
strange

**Comment by retorquere** [comment]
Can you try 1906?

**Comment by rlasse** [comment]
Just did that. There is still an error but the error message changed:
_CAYW failed: Error: No formatted citation found for zu:0:QPJVRHFM
scannable-cite@chrome://zotero-better-bibtex/content/better-bibtex.js:81168:17_

I reshared a log: 6TXF2E5L-euc.

**Comment by retorquere** [comment]
can you get me a new log with 1908?

**Comment by rlasse** [comment]
Here you go. Error message:
CAYW failed: Error: No formatted citation found for “zu:0:QPJVRHFM” in [“zu:6371466:QPJVRHFM”]
scannable-cite@chrome://zotero-better-bibtex/content/better-bibtex.js:81168:17

Log ID: XNZQ3SJV-euc

**Comment by retorquere** [comment]
build 1909 removes the dependency on the ODF-scan plugin being installed.

**Comment by rlasse** [comment]
Great! The export seems to work now, this is the message: { | Berry, 1975 | | | zu:0:ITEMKEY }
But it seems that the item key is not being exported properly?

Log ID: GZ6FNBVE-euc

**Comment by retorquere** [comment]
you are running BBT in test mode. Set `translators.better-bibtex.testing` to `false` (which is the default, not sure how it got turned on for you) and you will get the key.

**Comment by rlasse** [comment]
Oh I see. not sure how this happened. I am getting the key now, but there is still an undefined part: { | Berry, 1975 | | | zu:6371466:undefined }

Not sure if this will affect the citation?

Log ID:N7CFKKL9-euc

**Comment by rlasse** [comment]
Just checked and ODT scanner does recognize the citations, so I guess it should be fine?

**Comment by rlasse** [comment]
Actually, the item key that is exported is the same for every item... 
And I just checked, although ODF scan recognizes the citations, Zotero is not able to change the format of the citation because "it is no longer in the Zotero Database."

**Comment by retorquere** [comment]
I need to find out why you're getting an undefined.

**Comment by rlasse** [comment]
1913 seems to have solved it. Thank you!!!
Interestingly though, options such as adding page numbers are not getting exported, while this is not the case for pandoc?

**Comment by retorquere** [comment]
1915 should solve that

**Comment by rlasse** [comment]
yes, everything works well now! Again, thank you so much!!
