### ISSUE TITLE
Export is failing

### ISSUE THREAD

**Issue by Melloguy** [retorquere/zotero-better-bibtex#2008]
**Zotero version:**  5.0.96.3

**BBT version:**   6.1.0

**Support log ID:**  H9PFQGAR-refs-euc

**Exporter used:**   Zotero/Better Bibtex

**Expected behavior:**  Attempting to export a collection

**Actual behavior:**  Export failed; no file created or populated

**Comment by retorquere** [comment]
I'm see these errors in `H9PFQGAR-refs-euc`:

```
C:\Users\Herrin\Desktop\Thesis Tex Files\Previous Papers\Use in Thesis.bib\files\4762 (The system cannot find the path specified.
```

**Comment by Melloguy** [comment]
Is there something that I failed to do somewhere during setup?  I was never asked for a file destination.

I also ran a Zotero item report and its export to csv file.  Neither contained the citation key I created with your software.


Dick Herrin
843-290-7099

________________________________

**Comment by retorquere** [comment]
> Is there something that I failed to do somewhere during setup? I was never asked for a file destination.

There isn't a path to configure.

Do you recognize the path I named earlier at all? The error seems to relate to an attachment named `big-data-statistics`.

> I also ran a Zotero item report and its export to csv file. Neither contained the citation key I created with your software. 

That is correct, they do not, they're not mine.

**Comment by Melloguy** [comment]
The path you mentioned was an empty folder that was created on a previous export attempt.  I deleted it later in cleanup so I could try again with a blank slate.  I am puzzled how this came back into play.

While we can spend time working through this, I am not at all sure this is what I need to be doing.  I haven't been able to get much to work and/or give me the output I am looking for.

This is what I am trying to produce only with your cite key.  What I am showing here is the Zotero version with the key it created.

@article{chen_data_2015,
title = {Data Mining for the Internet of Things: Literature Review and Challenges},
volume = {11},
issn = {1550-1477},
url = {https://doi.org/10.1155/2015/431047},
doi = {10.1155/2015/431047},
shorttitle = {Data Mining for the Internet of Things},
abstract = {The massive data generated by the Internet of Things ({IoT}) are considered of high business value, and data mining algorithms can be applied to {IoT} to extract hidden information from data. In this paper, we give a systematic way to review data mining in knowledge view, technique view, and application view, including classification, clustering, association analysis, time series analysis and outlier analysis. And the latest application cases are also surveyed. As more and more devices connected to {IoT}, large volume of data should be analyzed, the latest algorithms should be modified to apply to big data. We reviewed these algorithms and discussed challenges and open research issues. At last a suggested big data mining system is proposed.},
pages = {431047},
number = {8},
journaltitle = {International Journal of Distributed Sensor Networks},
shortjournal = {International Journal of Distributed Sensor Networks},
author = {Chen, Feng and Deng, Pan and Wan, Jiafu and Zhang, Daqiang and Vasilakos, Athanasios V. and Rong, Xiaohui},
urldate = {2021-03-05},
date = {2015-08-01},
langid = {english},
note = {Publisher: {SAGE} Publications},
file = {Chen et al_2015_Data Mining for the Internet of Things.pdf:C\:\\Users\\Herrin\\Zotero\\storage\\RJR88CVA\\Chen et al_2015_Data Mining for the Internet of Things.pdf:application/pdf},
}

@article{wang_satellite_2019,
title = {Satellite Edge Computing for the Internet of Things in Aerospace},
volume = {19},
issn = {1424-8220},
url = {https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6832566/},
doi = {10.3390/s19204375},
abstract = {As one of the information industry’s future development directions, the Internet of Things ({IoT}) has been widely used. In order to reduce the pressure on the network caused by the long distance between the processing platform and the terminal, edge computing provides a new paradigm for {IoT} applications. In many scenarios, the {IoT} devices are distributed in remote areas or extreme terrain and cannot be accessed directly through the terrestrial network, and data transmission can only be achieved via satellite. However, traditional satellites are highly customized, and on-board resources are designed for specific applications rather than universal computing. Therefore, we propose to transform the traditional satellite into a space edge computing node. It can dynamically load software in orbit, flexibly share on-board resources, and provide services coordinated with the cloud. The corresponding hardware structure and software architecture of the satellite is presented. Through the modeling analysis and simulation experiments of the application scenarios, the results show that the space edge computing system takes less time and consumes less energy than the traditional satellite constellation. The quality of service is mainly related to the number of satellites, satellite performance, and task offloading strategy.},
number = {20},
journaltitle = {Sensors (Basel, Switzerland)},
shortjournal = {Sensors (Basel)},
author = {Wang, Yuxuan and Yang, Jun and Guo, Xiye and Qu, Zhi},
urldate = {2021-03-05},
date = {2019-10-10},
pmid = {31658684},
pmcid = {PMC6832566},
file = {Wang et al_2019_Satellite Edge Computing for the Internet of Things in Aerospace.pdf:C\:\\Users\\Herrin\\Zotero\\storage\\IN2YGQGW\\Wang et al_2019_Satellite Edge Computing for the Internet of Things in Aerospace.pdf:application/pdf},
}

How do I get this with better-bibtex?

Thanks.

Dick Herrin
843-290-7099
________________________________

**Comment by retorquere** [comment]
> The path you mentioned was an empty folder that was created on a previous export attempt. I deleted it later in cleanup so I could try again with a blank slate. I am puzzled how this came back into play. 

No idea, but it is the only error in your log, so it's all I have to go on.

> While we can spend time working through this, I am not at all sure this is what I need to be doing. I haven't been able to get much to work and/or give me the output I am looking for. 

Can you go into the hidden preferences (see instructions on [how to open them](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/)), search for `workers`, set its value to `0`, try the export again, and send a new log? Maybe a foreground export will give a more detailed error message.

> This is what I am trying to produce only with your cite key. 

For which I need to solve the problem you are experiencing. I just don't know what causes it yet. These are manual exports, correct? Not auto-exports?

**Comment by Melloguy** [comment]
I will try again as soon as I get back to my computer.  I am running manual exports not auto.

Thanks.


Dick Herrin
843-290-7099

________________________________

**Comment by Melloguy** [comment]
These are the hidden "worker" values I find.  I assume the one in bold is the one you are referring to?

[cid:81273b11-b16a-43b9-8014-2a92f3333512]

I need the full biblaTex file with the custom keys I created using your software.  I need to insert it into my LaTex thesis file so I can assign my citations using those custom keys.  I am against the wall on time and need to resolve this as soon as I can.  Thanksl

Dick Herrin
________________________________

**Comment by retorquere** [comment]
If you answer by mail, all formatting and images are stripped, so I don't know which part was bold, and I can't see the image.

If you pin the keys, you will get the BBT keys with the Zotero (non-Better) Bib(La)TeX exporters. That should solve your immediate need.

**Comment by Melloguy** [comment]
Does this work for you?

Dick Herrin

________________________________

**Comment by retorquere** [comment]
What do you mean by "this"? If you are responding by mail rather than by typing it in at https://github.com/retorquere/zotero-better-bibtex/issues/2008, anything that's not plain-text gets stripped away before I see it.

**Comment by Melloguy** [comment]
Sorry.  I attached an image file, hoping you could see that.  There are ten hidden entries that have “worker” in the name.  The one In bold I referred to is “extensions.zotero.translators.better.bibtex.workers”.  Is this the one you want me to change from “1” to “0”?

Dick Herrin
843-290-7099

________________________________

**Comment by retorquere** [comment]
Yes, that is the one.

If you want to include pictures, you will have to come the the github site to attach them.

**Comment by Melloguy** [comment]
Okay.  I made the change and it ran without incident.  Thanks!  I see a bunch of comments after each entry.  It appears you have included some validation rules I haven't seen applied before.  I’m not quite sure what to do about them.  Two very common ones are the title-case in zotero, and unused version.  Do you have something somewhere that explains these?

Thanks again!




Dick Herrin
843-290-7099

________________________________

**Comment by retorquere** [comment]
That's a bummer for me, because that was only meant to be used for diagnosis, it wasn't supposed to be a fix. I would propose dropping the cache from the BBT advanced prefs and setting it back to `1`, but if that doesn't work, you can keep it at `0` and go about your way. Exports will be slower when workers are set to `0`, and if you currently don't have the time (which is understandable) to diagnose the problem, I will have to close this issue. If you see the problem again, and you have time, feel free to reopen it by commenting here.

The comments you see are the [quality report](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#include-comments-about-potential-problems-with-the-exported-references), which you can disable.

**Comment by Melloguy** [comment]
I know that this leaves you a bit unsettled as a developer, but you have successfully helped get around this obstacle and on my way with what I need.  And for all that, I thank you so much!

Best regards and Merry Christmas!

Dick Herrin
843-290-7099

________________________________
