### ISSUE TITLE
Zotero stuck for several seconds when edit item 

### ISSUE THREAD

**Issue by XikunHuang** [retorquere/zotero-better-bibtex#2010]
**Zotero version:** 5.0.96.3

**BBT version:** 6.1.1

**OS**: Win10

**Your question/suggestion:** Zotero will be stuck for 2 or 3 seconds each time I edit items, such as add new tags for a paper. If I **disable**  zotero-better-bibtex, the problem disappears. So I am wondering whether this add-on causes the above problem,  and what zotero-better-bibtex will do when I add new tags or a new note for a paper.  BTW, there are ~2500 items in my Zotero library.
Any suggestions? Thanks a lot! 

Support log ID:

**Comment by retorquere** [comment]
I cannot do anything for you without a support log.

**Comment by XikunHuang** [comment]
I am sorry for ommiting the support log. I followed the template of **Question on use not covered by the other categories above.** and it does not mention support log. Maybe I choose the wrong category. Despite this, it is my mistake. Now I know how to find the support log of BBT and Zotero (Help->), and I will try to figure this out and update the progress. 
Thanks for your time!

**Comment by retorquere** [comment]
You are right, the question template doesn't explain when not to use it. I'll update the issue templates to clarify this. But if you want me to look into this slowdown, I need a support log.

**Comment by retorquere** [comment]
To be clear, Zotero should not be stuck 2 seconds after each edit, and certainly not for a library of this size. If you have tens of thousands of entries and are auto-exporting them, then maybe, but then I'd recommend different settings. A support log will give me your BBT settings too.

**Comment by XikunHuang** [comment]
The Support log ID is: 943C74ZS-apse.
"If you have tens of thousands of entries and are auto-exporting them, then maybe"
Yes, I set automatic export to be **On Change**.

**Comment by retorquere** [comment]
For a small library as this, that's the  recommended setting. I'll look at the log when I'm done cooking.

**Comment by XikunHuang** [comment]
It solves the problem with auto-exporting Disabled. Maybe there are too many items (about 2500) in my library, and it takes time to update each time I edit the items. Enjoy cooking. Thanks for your time.

**Comment by retorquere** [comment]
2500 is a small library. You could see slowdown if you have tens of thousands of items.
