### ISSUE TITLE
item.export gives error "keyscope is global, do not provide a library ID"

### ISSUE THREAD

**Issue by mhucka** [retorquere/zotero-better-bibtex#2014]
**Zotero version:**

5.0.97-beta.62+ad02b7019

**BBT version:**

6.1.2

**Support log ID:**

I tried to use the facility to submit a BBT support log, and while it did create one (which I can save), in the last step it gives me the following error:

<img width="546" alt="Screen Shot 2021-12-31 at 14 01 36" src="https://user-images.githubusercontent.com/1450019/147839892-b64025b3-7e1a-4c7f-9e5f-4101e1f37787.png">

I assume this means it never sent it electronically. The saved support log (QV9KX9J3-euc) is attached to this ticket instead.

**Exporter used:**

`item.export` API being called with `biblatex` or `jzon`.

**Expected behavior:**

I'm trying to use the [JSON-RPC interface to get data for a given citation key](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/#itemexportcitekeys-translator-libraryid). It is very difficult (for me) to figure out the exact proper syntax of calls to the JSON-RPC endpoint, but I found the following responses to Github issues that show examples of how to call the `item.export` endpoint:

* https://github.com/retorquere/zotero-better-bibtex/issues/1637#issuecomment-691011782
* https://github.com/retorquere/zotero-better-bibtex/issues/1511#issuecomment-622452718

Based on the above, it appears to me the following `curl` call should work. Apart from the actual citation key used, this command is identical to what is shown in the response to someone else's issue, and which (at the time) someone confirmed, at https://github.com/retorquere/zotero-better-bibtex/issues/1637#issuecomment-691011782.

```sh
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "item.export", "params": [["Warzel2021opinion"], "biblatex"] }'
```

<br>

**Actual behavior:**

The `curl` command above results in the following error:

```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"keyscope is global, do not provide a library ID"},"id":null}
[QV9KX9J3-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/7797128/QV9KX9J3-euc.zip)

```

I have also tried "bibtex" and "jzon" instead of "biblatex" as the value of the "translator" parameter, but always get the same error.

Note that the libraryID parameter is not present in the call parameters, yet the error complains about having provided a library ID. I'm stumped.

I verified that the given citation key exists in my library.

**Comment by mhucka** [comment]
I don't see any attached files in the issue above, yet I was careful to attach it and I know I saw GitHub's issue system indicate that a file was uploaded and attached. I don't know if the lack of any obvious file attachments is purely a UI issue in the GitHub ticket system or if it never actually included the file. I'm going to try to include it here to this comment just in case.

[QV9KX9J3-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/7797132/QV9KX9J3-euc.zip)

**Comment by mhucka** [comment]
I also used the file.io approach that [you previously explained to me](https://github.com/retorquere/zotero-better-bibtex/issues/1956#issuecomment-953217710) to send the debug log. The id is mECREI3yuhaJ-BXRDQ5Y5 but it is for a different run of Zotero. (Restarted, restarted again with BBT debug logging enabled, ran curl, then pulled down the menu item for "send debug log to file.io".)

**Comment by retorquere** [comment]
Can you try 1931? It should fix the libraryID problem.

I take it you have already tried to download the log from file.io? It's no longer there.

**Comment by mhucka** [comment]
Thank for the super fast response :-)

> Can you try 1931? It should fix the libraryID problem.

Yes, it does! Thank you.

> I take it you have already tried to download the log from file.io? It's no longer there.

No, actually, I don't believe I did anything at all with it after submitting it. I'm not sure what happened. I seem to have the worst luck with the log submissions …. Anyway, I hope the attached log (upthread) was helpful as a substitute.

**Comment by retorquere** [comment]
The error was clear from the description, but thanks for trying to submit a log. It is usually required for me to fix things.
