### ISSUE TITLE
Syntax Error when generating citation keys for Author names with Apostrophe (O'Shea)

### ISSUE THREAD

**Issue by gboes** [retorquere/zotero-better-bibtex#2016]
**Zotero version:**
Zotero 5.0.96.3 en-GB
**BBT version:**
  Better BibTex for Zotero (6.1.3, extension)
**Support log ID:**
PU92VYXI-refs-euc

**Expected behavior:**
citation key format: [Auth][year]
Export Author "James O'Shea" As "OShea2012"

**Actual behavior:**
Export Author "James O'Shea" As "O'Shea2012" leading to a syntax error in the .bib file.

**Comment by gboes** [comment]
Workaround:
Adding a manual citation key without Apostrophe in the Zotero "Extra" Field:
```
Citation key: Oshea2012
```

**Comment by retorquere** [comment]
Your citekey format uses `Auth` rather than `auth`; from https://retorque.re/zotero-better-bibtex/citing/#functions:

> *Note*: the functions above all have the clean filter (see below) automatically applied to them. If you want more control, auth, authIni, edtr, … and all the author-related fields that mimic the JabRef equivalents also have capitalized versions (so Auth, AuthIni, Edtr, …) which follow the same algorithm but do not have any cleaning (diacritic folding, space removal, stripping of invalid citekey characters) applied. 

So you need to either remove the invalid characters with a `:replace` filter, or apply the `:clean` filter (but in the latter case, just using `auth` rather than `Auth` achieves the same).

**Comment by gboes** [comment]
wow, that was fast!
I was under the wrong impression that the difference between "auth" and "Auth" was a matter of capitalization; now I understand that a lot more is going on.
This seems to have fixed it, thank you so much.

**Comment by retorquere** [comment]
My pleasure. Neither `auth` nor `Auth` do anything wrt capitalization, which is why people often use `auth:lower`. `auth` is (at this point) just a shorthand for `Auth:clean`.
