### ISSUE TITLE
Question about a making specific citation key generator

### ISSUE THREAD

**Issue by Annie-of-the-Stars** [retorquere/zotero-better-bibtex#2017]
**Zotero version:** 5.0.96.3

**BBT version:** 6.1.3

Hello! I would like to produce a citation key generator that gives the following things in the order shown:

1. The first name of the author in lower case.
2. A plus sign if there are two or more authors.
3. The year of publication. If there's no publication date, use the year of the access date field. Either wrapped by periods.
4. The title abbreviated and in lower case.

So far, I have this:

```
[Author:replace=("\ ([A-z]|[0-9])*",""):lower][authors1:replace=("EtAl","+"):replace=("([A-z]|[0-9])","")].[year:([AccessDate:select=1,4])].[Title:lower:abbr]
```

However, only `[Title:lower:abbr]` and the periods seem to work. Could you point me in the right direction?

**Comment by Annie-of-the-Stars** [comment]
I thought the support log was unnecessary. On second thought, maybe it is. So, here it goes: `I636JYCK-euc`.

**Comment by retorquere** [comment]
Please re-read point 1. I really do need a support log, as described in point 1; the ID will have `-refs` in it. It's honestly fairly disheartening to have to explain this so often. Without it I'd be making assumptions about your situation which makes things unnecessarily error-prone.

**Comment by Annie-of-the-Stars** [comment]
I'm sorry. I'm not in the best state of mind, so words are like gibble-gabble to me sometimes. I should've read point one much more carefully. 

Maybe I'll make a Firefox extension to put up a big wall of text saying "ADD SUPPORT LOG ID" whenever I open an issue for this plugin. Hopefully that'll do the trick. 

Anyways, here's the support log ID: `X4D5XEZB-refs-euc`.

**Comment by retorquere** [comment]
I don't think I could entice users to install an extra plugin just for support.

I will have to think about a way to enable what you want, preferable without complicating the existing syntax too much. It probably won't be finished today unfortunately. I haven't found a way to do it applying the existing functions.

**Comment by Annie-of-the-Stars** [comment]
> Maybe I'll make a Firefox extension to put up a big wall of text saying "ADD SUPPORT LOG ID" whenever I open an issue for this plugin. Hopefully that'll do the trick.

This was meant to be a joke, haha. I don't even know how to make Firefox add-ons. Even if it wasn't a joke, not even I would entice users to use it merely for support.

Take your time with the citation key generator. Just let me know if you need anything from my side.

**Comment by retorquere** [comment]
I've finally finished the citekey gen overhaul. For the time being you'll need a leading `''` to trigger the new parser, but this should do what you want:

```
'' + 
authors(1, etal='+').lower.postfix('.') + year.len('>', 0).postfix('.') + title 
|
authors(1, etal='+').lower.postfix('.') + AccessDate.postfix('.') + title 
```

**Comment by Annie-of-the-Stars** [comment]
Ooh. Cool. There's an issue: It uses the author's last name instead of the first name. Support log ID of a reference: `IDTID8JZST-refs-euc`.

**Comment by retorquere** [comment]
```
'' + 
authors(1, name='%(g)s', etal='+').lower.postfix('.') + year.len.postfix('.') + title 
|
authors(1, name='%(g)s', etal='+').lower.postfix('.') + AccessDate.postfix('.') + title 
```

**Comment by Annie-of-the-Stars** [comment]
Purr-fection. Thank you so much.:)

**Comment by retorquere** [comment]
This will be in the next release, which will go out somewhere this week.
