### ISSUE TITLE
Error exporting items without citation keys to Better BibTeX format

### ISSUE THREAD

**Issue by Dominic-DallOsto** [retorquere/zotero-better-bibtex#2018]
Continued discussion from https://github.com/diegodlh/zotero-cita/issues/145

I am using Cita to store the citations for items in Zotero. Citations are Zotero items that aren't saved to the library and therefore that never get citation keys. When trying to export them to a .bib file with the Better BibTeX exporter, an error occurs and the export fails.

Since the above-mentioned issue, I made sure the item has a citation key in its `extra` field but still I received the same error:

```
Error: No citation key in {"key":null,"version":null,"itemType":"journalArticle","title":"An Unsolvable Problem of Elementary Number Theory","date":"1936-04","extra":"Citation Key: churchUnsolvableProblemElementary1936","volume":"58","pages":"345","publicationTitle":"American Journal of Mathematics","DOI":"10.2307/2371045","issue":"2","ISSN":"00029327","creators":[{"firstName":"Alonzo","lastName":"Church","creatorType":"author"}],"tags":[],"collections":[],"relations":{},"uri":"http://zotero.org/users/local/KPwFNg0W/items/null","itemID":null,"attachments":[],"notes":[],"citationKey":"","citekey":"","itemKey":null,"libraryID":1,"$cacheable":false}
itemsGenerator@resource://zotero-better-bibtex/Better%20BibTeX.js:59390:17
doExport@resource://zotero-better-bibtex/Better%20BibTeX.js:63721:5
Zotero__workerContext</ctx.onmessage@resource://zotero-better-bibtex/worker/zotero.js?version=5.0.96.2.SOURCE.abbb9fa07&platform=lin&translator=Better%20BibTeX&output=/home/dominic/Desktop/Exported%20citations.bib&localeDateOrder=mdy&debugEnabled=true&worker=1:46592:11
```

Support log ID: BQ8HFK34-refs-euc

**Comment by retorquere** [comment]
You need changes in BBT that are now building. A new build will drop here in 10 minutes or so that has the change to the exporter and to `propose`.

How do you get `5.0.96.2.SOURCE.abbb9fa07` BTW? Not many people build Zotero from source.

**Comment by retorquere** [comment]
That's the one. It will require the corresponding changes in cita, but if that combo is confirmed to work, I'll put out a new release of BBT that has these changes.

**Comment by Dominic-DallOsto** [comment]
Thanks! Works a treat!

> How do you get `5.0.96.2.SOURCE.abbb9fa07` BTW? Not many people build Zotero from source.

Ahh, I have a source build on Ubuntu for extension development so I can connect the firefox dev tools and debug more easily.
