### ISSUE TITLE
How to export Archive, Loc. in Archive in bibtex

### ISSUE THREAD

**Issue by pbinkley** [retorquere/zotero-better-bibtex#2020]
Support Log ID: RD2D7YL4-refs-euc

To reproduce:

- create a ```Manuscript``` item, with the ```Archive``` and ```Loc. in Archive``` fields populated, in collection "testcollection"
- export the item using the http API:

```
wget -O archivestest.bib "http://127.0.0.1:23119/better-bibtex/export/collection?/1/test/testcollection.biblatex"
```
- the output does not include the two fields:

```
@unpublished{binkleyLetterLlewellynRaney1936,
  title = {Letter to {{M}}. {{Llewellyn Raney}}},
  author = {Binkley, Robert C.},
  date = {1936-04-23},
  annotation = {RCBFWB: Doc. 12393}
}
```

- when exporting json, however, the two fields are present:

```
    {
        "archive": "Joint Committee on Materials for Research Collection, Library of Congress, Washington, D.C.",
        "archive_location": "Box 23, \"Micro-Copying of Newspaper Titles\"",
        "author": [
            {
                "family": "Binkley",
                "given": "Robert C."
            }
        ],
        "citation-key": "binkleyLetterLlewellynRaney1936",
        "id": "binkleyLetterLlewellynRaney1936",
        "issued": {
            "date-parts": [
                [
                    1936,
                    4,
                    23
                ]
            ]
        },
        "note": "RCBFWB: Doc. 12393",
        "title": "Letter to M. Llewellyn Raney",
        "type": "manuscript"
    },
```

This is important because the Archive and Loc. in Archives fields are necessary for citing archival documents. (See https://libguides.nus.edu.sg/c.php?g=145733&p=956617 )

Support log ID:

**Comment by retorquere** [comment]
@pbinkley I'm not yet sure where I should put this information. I'm more likely to put it in biblatex though, I hope that is all the same to you. bibtex is almost guaranteed to not have anything standardized for this.

> This is important because the Archive and Loc. in Archives fields are necessary for citing archival documents. (See https://libguides.nus.edu.sg/c.php?g=145733&p=956617)

That doesn't give guidance on what biblatex fields to put this information in however.

@njbart, I see this in the biblatex manual:

> **number**: it may contain the number of a journaltitle in an article or review entry, the number of a title in a periodical entry, the volume/number of a book (or musical recording) in a series, the (generally numerical) specifier of the type in a report entry, *the archive location* (or database accession number) of a dataset entry, and the number of a national or international standard in a standard entry.

(emphasis mine)

does that make `number` the right place for this? Where should the archive itself be put?

**Comment by pbinkley** [comment]
My interest is just in getting this working with Pandoc and csl stylesheets, and I hadn't thought about how to map it to biblatex (which I don't know much about). It looks like this has [come up before](https://forums.zotero.org/discussion/62081/how-to-export-archive-and-archive-location-to-bibtex) with no solution other than using json, so there may not be a way around the gap in biblatex. If there were a way to warn a user like me that these fields hadn't been exported, that would save trouble, but I don't see where that could happen within Better Bibtex's workflow. Thanks for looking at this, and please don't spend time on it on my account.

**Comment by retorquere** [comment]
I was just thinking about a structural addition to BBT, but it's easy enough to add them in a postscript:

```
if (Translator.BetterTeX) {
  reference.add({ name: 'archive', value: item.archive })
  reference.add({ name: 'archivelocation', value: item.archiveLocation })

}
```

I have thought about detecting fields that are not exported, but the few experiments I did did not pan out. But a new approach just struck me, so I'll try to add them to the quality report.

**Comment by retorquere** [comment]
> My interest is just in getting this working with Pandoc and csl stylesheets

But if that's the case, why not export to Better CSL JSON? That has both those fields.

**Comment by retorquere** [comment]
> If there were a way to warn a user like me that these fields hadn't been exported, that would save trouble, but I don't see where that could happen within Better Bibtex's workflow.

If you turn on the [quality report](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#include-comments-about-potential-problems-with-the-exported-references) BBT will add information on data in the zotero item that is not used in the export.

**Comment by pbinkley** [comment]
I think I'm good. I'm using the BBT json (I just changed the ```/better-bibtex/``` url I fetch from .biblatex to .json). I'll turn on the quality report and keep an eye on it, to learn more about how BBT works. Thanks for your attention to this.
