### ISSUE TITLE
Map/translate the "call-number" field from Bib(La)TeX to Zotero's "call number" (CallNumber) field

### ISSUE THREAD

**Issue by nathan-artist** [retorquere/zotero-better-bibtex#2021]
Hello, I just started using Better BibTeX and I have a feature suggestion: Would it be possible to map/translate the "call-number" field from Bib(La)TeX to Zotero's "call number" (CallNumber) field?

I am importing a BibTeX file created with a BibTeX editor for macOS called [BibDesk](https://en.wikipedia.org/wiki/BibDesk). One of the default fields in BibDesk is named "call-number". It is not standard BibTeX, but it is a default field for anyone who uses BibDesk, and it corresponds exactly to Zotero's "call number" (CallNumber) field. It would make sense to map/translate that field on import, instead of putting it in the Extras field.

Thanks!

**Comment by retorquere** [comment]
Can you paste the actual item you're trying to import?

**Comment by nathan-artist** [comment]
Here is an example. There are many other fields, but "call-number" is the relevant field:

```
@Book{            Kirk:2002er,
  address       = {New York},
  author        = {Kirk, Stuart A. and Reid, William James},
  call-number   = {HV40},
  dewey-call-number={361.3},
  doi           = {10.7312/kirk11824},
  genre         = {Social service},
  isbn          = {0231118244},
  jstor         = {10.7312/kirk11824},
  library-id    = {2001028014},
  oclc          = {45888941},
  year          = {2002},
  publisher     = {Columbia University Press},
  title         = {Science and social work: a critical appraisal}
}
```

**Comment by retorquere** [comment]
Can you edit the imported item in Zotero to what you would want it to be, right-click it, and send a BBT support log?

**Comment by nathan-artist** [comment]
Support log ID: HFQ5VUTR-refs-euc

**Comment by nathan-artist** [comment]
The example is a book, but this would apply to all item types.

**Comment by retorquere** [comment]
Can you try build 1960? It should work for all itemtypes. But a sample gives me a testcase, which I've added to the test suite, so that there can't be accidental regressions.

**Comment by nathan-artist** [comment]
I tried build 1960 with 11 different Bib(La)TeX item types (Article, Book, Booklet, InCollection, InProceedings, MastersThesis, Misc, PhDThesis, Online, TechReport, Unpublished), and it worked for all item types except Online. This makes sense because Online items usually do not have a call number (none of my Online items really have call numbers; I just added one to test it), although it is not inconceivable that some might: for example, [WorldCat](https://en.wikipedia.org/wiki/WorldCat) catalogs some online resources, although I don't know how many of them have call numbers. Anyway, I think it is perfectly reasonable that it does not work for the Online item type, and I am very happy that this feature is implemented. You are awesome, Emiliano!

**Comment by retorquere** [comment]
You're very welcome, and thanks for the conformation. BBT tests whether the target item type can take a call number, and if it does not, places it in the `extra` field; if you re-export the item to biblatex, it will be detected and will re-appear in the output.
