### ISSUE TITLE
How to export bib without month and date in "year" item (Using better bibtex)

### ISSUE THREAD

**Issue by qswt111** [retorquere/zotero-better-bibtex#2022]
Support log ID: TMFP7A3K-refs-euc

The "Date" of some items is like "2019/03/09", as shown below:

![image](https://user-images.githubusercontent.com/94038091/148879615-abe9e594-c8c5-41b6-b0f6-fdf199c00604.png)

- When exporting it with bibtex, the format is right, such as:

![image](https://user-images.githubusercontent.com/94038091/148879653-01c571e7-76cb-4691-b3c8-13e66e2683da.png)

![image](https://user-images.githubusercontent.com/94038091/148879697-9d488bc3-a749-48d2-8636-cc453c25977c.png)

- When Better BibTex is used, the "year" of exported bib is "year={2019/03/09}", as shown below:

![image](https://user-images.githubusercontent.com/94038091/148879723-b22880c1-af4c-47f4-9210-0f252f672439.png)
![image](https://user-images.githubusercontent.com/94038091/148879758-c7b6a95b-0f94-43b2-a03a-46a7a4583738.png)

How to set bbt to modify this issue? I really don't want to modify them one by one.
Thank you!

**Comment by retorquere** [comment]
I'm of two minds about this. If I detect dates the way Zotero does it, it will falsely detect things like `xx 1985` as dates, and I don't really want that. In your case it is the trailing slash that trips up date recognition. If you remove that, both Zotero and BBT will recognize the date.
