### ISSUE TITLE
(Automatically) Pin citation key

### ISSUE THREAD

**Issue by tdegeus** [retorquere/zotero-better-bibtex#2023]
I have imported my Mendeley library in Zotero.
Mendeley generated BibTeX citation keys as "[auth][year]" which I also let Better BibTeX do. 

Now a seemingly simple question:
For all imported items the citation key by Mendeley is pinned. How can I remove the pinning for all items where the citation key generated by Better BibTeX would be the same?

Support log ID:

**Comment by retorquere** [comment]
There is no option to do that. You can unpin all keys after import, or specify beforehand that keys should be regenerated during import, but that will regenerate all of them.

**Comment by tdegeus** [comment]
Thanks for the reply. That's a pity! Is there a way how I could do this semi-manually?

**Comment by retorquere** [comment]
I'll get you something later today.

**Comment by retorquere** [comment]
Why do you want to do this if I may ask?

**Comment by retorquere** [comment]
With 1980 installed, this should do it if you paste it into Tools -> Developer -> Run Javascript. Make sure the `Run as async function` is checked before you click `Run`. I've tested this on my test library, it worked, and I don't see how it could go wrong, but you assume the risk that it might.

```
for (const lib of Zotero.Libraries.getAll()) {
  for (const item of await Zotero.Items.getAll(lib.id)) {
    if (!item.isRegularItem()) continue

    await item.loadAllData()
    const citekey = Zotero.BetterBibTeX.KeyManager.generate(item)
    if (citekey === item.getField('citationKey')) await Zotero.BetterBibTeX.KeyManager.unpin(item.id)
  }
}
```

still not clear why you want to do this, but here ya go.

**Comment by tdegeus** [comment]
Thanks! I just want to cleanup. But maybe you are right and I should not worry.

**Comment by retorquere** [comment]
You don't have to justify this to me, but I do not understand in what sense unpinning keys on this division is a cleanup. What is unclean about the present state of things?

**Comment by tdegeus** [comment]
I had one conflict of a pinned key coexisting with a generated key. I was starting to wonder if I should look in to it as a bug, or wether it is my huge number of pinned keys that I should start to rethink.

**Comment by retorquere** [comment]
You can tell BBT to regenerate an unpinned key when the existing key is created as a pinned key.

**Comment by tdegeus** [comment]
@retorquere Interestingly I have a strong use-case for the exact opposite of what I was asking. In particular, to use a basic bibtex file during writing on Overleaf I need the default Zotero BibTeX exporter to use the same keys as I do locally when exporting using Better BibTeX. I.e. I should *pin* all items. 

What would the code look like to do that:
```java
for (const lib of Zotero.Libraries.getAll()) {
  for (const item of await Zotero.Items.getAll(lib.id)) {
    if (!item.isRegularItem()) continue

    await item.loadAllData()
    const citekey = Zotero.BetterBibTeX.KeyManager.generate(item)
    await Zotero.BetterBibTeX.KeyManager.pin(item.id)
  }
}
```
?

**Comment by retorquere** [comment]
> Then, can I select to autopin new items? (I did find to do it item per item, in the "Better BibTeX" drop down on right click)

It will also work if you select all instead of select one.

**Comment by tdegeus** [comment]
Thanks, I found that too. It does require one manual step on my side. I was wondering if I could get rid of that.

**Comment by retorquere** [comment]
The manual step of selecting them? What did you have in mind as the interaction?

**Comment by retorquere** [comment]
Or do you mean auto-pin from this point on? That's what auto-pin does.

**Comment by tdegeus** [comment]
Great, found it! Thanks

**Comment by tdegeus** [comment]
P.S. I would vote for a non-hidden options
