### ISSUE TITLE
Feature Request: Allowing file export with "Keep updated" option

### ISSUE THREAD

**Issue by simonla82** [retorquere/zotero-better-bibtex#2024]
When exporting a library to the `Better BibLaTeX` format, it is not possible to use both the `Export Files` and the `Keep updated` option. 

I would like to use the `Keep updated` option and have **relative filepaths** in my exported `.bib`-file. If I understand #126 correctly, this is not possible, as long as the files are not exported alongside the library, since there is no relative path from my exported `.bib`-file to the Zotero storage location (to be precise, of course such a relative path exists, e.g., `../../../../../Users/user/Zotero/storage`, but that's no real improvement against absolute paths).

Thanks a lot for considering this feature request!

**Comment by retorquere** [comment]
These options are mutually exclusive is for performance reasons; I'd have to scan through and potentially copy over your attachments, and both are time-consuming actions.

But relative paths is always on now. If you export without attachments to a place that has the attachments somewhere under it (that is, the relative path from the bib file to the attachments has no `..` in it), you will get relative paths.

**Comment by simonla82** [comment]
Ah, exporting to a different place, solves my problem. Thank you very much for your quick reply!
