### ISSUE TITLE
Remove autopin

### ISSUE THREAD

**Issue by Kullenej** [retorquere/zotero-better-bibtex#2027]
In my Zotero library, all new added items automatically gets pinned before I get to change fields in the metadata. I looked into the hidden preferences but can only see the option for delay - is it possible to manually pin the citekeys?

**Comment by Kullenej** [comment]
Support log ID: CZW8RYY7-euc

**Comment by retorquere** [comment]
It should turn off if you set `autoPin` to `0` (which is the default value, so clearing `autoPin` should set it to `0`).

**Comment by Kullenej** [comment]
Thank you - I accidently pressed the "set to default" instead of just typing 0 and now it has disappeared from the hidden preferences

**Comment by retorquere** [comment]
That's a bug -- a version with a fix is building now.

**Comment by Kullenej** [comment]
It came back when I restarted. Thank you!
