### ISSUE TITLE
Another add-on conflict: PubPeer

### ISSUE THREAD

**Issue by dmhowcroft** [retorquere/zotero-better-bibtex#2028]
The [PubPeer Plugin for Zotero](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin) produces the same error outcome as [Issue 1909](https://github.com/retorquere/zotero-better-bibtex/issues/1909): Better Bibtex fails to load, and the preferences pane just shows "Better Bibtex is loading" continuously with no action.

Not Better Bibtex's responsibility to deal with other add-on developers, but I wanted to open an issue to document the problem in case someone else encounters it. For me, removing the Pubpeer Plugin fixed the problem.

Support log ID:

**Comment by retorquere** [comment]
I can fix that as I have push access to that repo. I'll do that when I get back home.

**Comment by retorquere** [comment]
Done

**Comment by dmhowcroft** [comment]
Awesome! Thanks so much for the fix elsewhere and for your incredible work on BBT! It makes Zotero much nicer :)
