### ISSUE TITLE
add fully formatted reference in export to bibtex json

### ISSUE THREAD

**Issue by kabo1234** [retorquere/zotero-better-bibtex#2031]
Hi,

I'm not sure if this in an obvious thing I have just missed...I am generating an automatic export to bibtex json for use with the BibNotes Formatter for Obsidian ([bibnotes](https://github.com/stefanopagliari/bibnotes)). 

I'd like to be able to export a full reference in Chicago 17th (full note) with each reference, which can then be called upon by BibNotes (e.g. in the Extra field?), but I can't work out how to do that.

Is this possible with BetterBibTex, or is this a Zotero issue?

Many thanks for your help!

**Comment by retorquere** [comment]
Can you produce a sample of the exported item was you'd like to see it?

**Comment by kabo1234** [comment]
I’m not sure how I would do that…

this would be the reference that I would like to see somewhere in the exported bibtex json file:

Sheehan, Rebecca A. “Facebooking the Present: The Biopic and Cultural Instantaneity.” In The Biopic in Contemporary Film Culture, edited by Tom Brown and Belén Vidal, 35-51. London, UK: Taylor & Francis Group, 2013.

perhaps it could be in the extra field?

**Comment by retorquere** [comment]
I looked into this in #2042 but it doesn't seem possible, sorry. The bibnotes author could do this by calling BBTs JSON-RPC API.
