### ISSUE TITLE
After I disabled the extension `PubPeer Plugin for Zotero`, BBT is working again

### ISSUE THREAD

**Issue by zzzgithubzzz** [retorquere/zotero-better-bibtex#2032]
Reference: @retorquere @qqobb After I disabled the extension `Sci-Hub Plugin for Zotero`, everything is ok.

_Originally posted by @dualer in https://github.com/retorquere/zotero-better-bibtex/issues/1909#issuecomment-945347031_

Wanted to point out that for me, the problem was caused by the 'PubPeer addon'. Disabling this got back the much needed BBT working again.

Cheers!

**Comment by zzzgithubzzz** [comment]
Just wanted to leave a comment for people like me who haven't yet got BBT working and were struggling to find a fix. Hope this helps.
Disabling all addons and figuring out the problematic one and then disabling them will get the BBT working again.

Cheers!

**Comment by retorquere** [comment]
Doesn't an upgrade to the latest version of pubpeer solve the problem?

**Comment by zzzgithubzzz** [comment]
> Doesn't an upgrade to the latest version of pubpeer solve the problem?

Nope. Tested with the "zotero-pubpeer-0.0.12.xpi" plugin, returns the dreaded "BBT is loading.." error. Removed the plugin, now BBT works fine.

**Comment by retorquere** [comment]
Can you install https://github.com/retorquere/zotero-debug-log, restart with debugging enabled, then "send a log to file.io", and paste the ID here?
