### ISSUE TITLE
BBT continuously asks to restart Zotero 

### ISSUE THREAD

**Issue by AntonOellerer** [retorquere/zotero-better-bibtex#2033]
Hey,
First of all, thank you for your great extension!
I use BBT, and encountered the problem that after each start BBT asks me to restart Zotero with the message 
```
New Better BibTeX translators have been installed. If you want to use these for drag-and-drop (e.g. to drag and drop citekeys or citations), you will need to restart once to activate them.
```
After a few time I decided to look into the logs and noticed a lot of messages in the style of 
```
[JavaScript Error: "Overwriting translator with same filename 'Better BibLaTeX.js'" {file: "chrome://zotero/content/xpcom/translation/translators.js" line: 568}]
Zotero.Translators</this.save<@chrome://zotero/content/xpcom/translation/translators.js:568:7
tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:609:17
module.exports/Promise.prototype._settlePromise0@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:649:5
module.exports/Promise.prototype._settlePromises@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:729:13
_drainQueueStep@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:93:9
_drainQueue@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:86:9
Async.prototype._drainQueues@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:102:5
Async/this.drainQueues@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:15:9
```
the only thing varying is the filename of the translator.

I am using the Zotero flatpak version, version `5.0.96.3`, BBT version `6.1.10` on fedora 35.
Best regards
Anton

**Comment by retorquere** [comment]
Do you experience the same problem with the tarball version of Zotero? Flatpacks sometimes have permission errors from how the container is set up.

**Comment by retorquere** [comment]
(otherwise I will need a support log ID, not just a log snippet)

**Comment by AntonOellerer** [comment]
I have not tried with the tarball yet, the support id is `PALAQNVW-euc`.

**Comment by retorquere** [comment]
That log shows that Zotero says it's overwriting them, and then actually overwrites them. Zotero should not report this as an error, as nothing is actually going wrong.

Can you go into your zotero datadirectory and get me the `hash` field value at the top of `Better BibLaTeX.js`.

But I'd really also prefer it if you could test the tarball version. You don't need to do anything special, you can just unpack it and start it, it should find everything it needs automatically.

**Comment by AntonOellerer** [comment]
The hash is `2786323948fca5fc715fe49fdbc3a8e38382ba3a55fdafbfcf8091aabbc9c347`, I will try it with the tarball version now, thank you for your help!

**Comment by retorquere** [comment]
Can you generate a new log from build 2014?

**Comment by AntonOellerer** [comment]
`6RQ26VXU-euc` :+1:

**Comment by retorquere** [comment]
Can you open `Tools` -> `Developer` -> `Run javascript`, paste in 

```
Zotero.Translators.get('f895aa0d-f28e-47fe-b247-2ea77c6ed583')
```

click `Run` and post the result here?

**Comment by AntonOellerer** [comment]
```json
{
    "translatorID": "f895aa0d-f28e-47fe-b247-2ea77c6ed583"
    "translatorType": 2
    "label": "Better BibLaTeX"
    "creator": "Simon Kornblith, Richard Karnesky, Anders Johansson and Emiliano Heyns"
    "target": "bib"
    "priority": 50
    "lastUpdated": "2022-01-26"
    "browserSupport": "g"
    "minVersion": "4.0.27"
    "maxVersion": ""
    "inRepository": false
    "configOptions": {
        "getCollections": true
        "hash": "7cedfa514ac864ec42ea7aeec5cc583a7ad51a7a92bed3d17b7864d2c80a702b"
    }
    "displayOptions": {
        "exportNotes": false
        "exportFileData": false
        "useJournalAbbreviation": false
        "keepUpdated": false
    }
    "runMode": 1
    "cacheCode": undefined
    "path": "/home/antono/Zotero/translators/Better BibLaTeX.js"
    "fileName": "Better BibLaTeX.js"
    "metadata": {
        "translatorID": "f895aa0d-f28e-47fe-b247-2ea77c6ed583"
        "translatorType": 2
        "label": "Better BibLaTeX"
        "creator": "Simon Kornblith, Richard Karnesky, Anders Johansson and Emiliano Heyns"
        "target": "bib"
        "priority": 50
        "lastUpdated": "2022-01-26"
        "browserSupport": "g"
        "minVersion": "4.0.27"
        "maxVersion": ""
        "inRepository": false
        "configOptions": {
            "getCollections": true
            "hash": "7cedfa514ac864ec42ea7aeec5cc583a7ad51a7a92bed3d17b7864d2c80a702b"
        }
        "displayOptions": {
            "exportNotes": false
            "exportFileData": false
            "useJournalAbbreviation": false
            "keepUpdated": false
        }
    }
    "init": function (info) {...}
    "getCode": function () {...}
    "serialize": function (properties) {...}
    "logError": function (message, type, line, lineNumber, colNumber) {...}
}
```

**Comment by retorquere** [comment]
And the same from the tarball version? BBT on your system is getting back that the translator is not installed, rather than this error.

**Comment by AntonOellerer** [comment]
```json
{
    "translatorID": "f895aa0d-f28e-47fe-b247-2ea77c6ed583"
    "translatorType": 2
    "label": "Better BibLaTeX"
    "creator": "Simon Kornblith, Richard Karnesky, Anders Johansson and Emiliano Heyns"
    "target": "bib"
    "priority": 50
    "lastUpdated": "2022-01-26"
    "browserSupport": "g"
    "minVersion": "4.0.27"
    "maxVersion": ""
    "inRepository": false
    "configOptions": {
        "getCollections": true
        "hash": "7cedfa514ac864ec42ea7aeec5cc583a7ad51a7a92bed3d17b7864d2c80a702b"
    }
    "displayOptions": {
        "exportNotes": false
        "exportFileData": false
        "useJournalAbbreviation": false
        "keepUpdated": false
    }
    "runMode": 1
    "cacheCode": undefined
    "path": "/home/antono/Zotero/translators/Better BibLaTeX.js"
    "fileName": "Better BibLaTeX.js"
    "metadata": {
        "translatorID": "f895aa0d-f28e-47fe-b247-2ea77c6ed583"
        "translatorType": 2
        "label": "Better BibLaTeX"
        "creator": "Simon Kornblith, Richard Karnesky, Anders Johansson and Emiliano Heyns"
        "target": "bib"
        "priority": 50
        "lastUpdated": "2022-01-26"
        "browserSupport": "g"
        "minVersion": "4.0.27"
        "maxVersion": ""
        "inRepository": false
        "configOptions": {
            "getCollections": true
            "hash": "7cedfa514ac864ec42ea7aeec5cc583a7ad51a7a92bed3d17b7864d2c80a702b"
        }
        "displayOptions": {
            "exportNotes": false
            "exportFileData": false
            "useJournalAbbreviation": false
            "keepUpdated": false
        }
    }
    "init": function (info) {...}
    "getCode": function () {...}
    "serialize": function (properties) {...}
    "logError": function (message, type, line, lineNumber, colNumber) {...}
}
```

**Comment by retorquere** [comment]
This is related to a problem I've been asking about [since 2017](https://groups.google.com/g/zotero-dev/c/j_FdSB3psmI). I'm still experimenting, but this part of Zotero is really complicated.

**Comment by retorquere** [comment]
I've re-opened a new thread on zotero-dev but I'm getting zero response from the Zotero crew. Really disappointing. I have not forgotten about your issue, but I cannot move forwards without their input. If I could reproduce the issue I might have been able to create a solution, but without it, I need their input.

**Comment by AntonOellerer** [comment]
Ah I can understand that this is frustrating!
Thank you very much for the efforts, and let me know if there is any way I can help!

**Comment by retorquere** [comment]
I don't really know how. I don't want to push too hard on the Zotero devs, who have no formal obligation to help.

**Comment by retorquere** [comment]
Can you install 2096, *not* restart when Zotero asks after installation of the plugin, instead restart with logging enabled from the Help menu, then send a new log ID?

**Comment by AntonOellerer** [comment]
It seems as if the error disappeared, or at least I do not get the `restart` prompt anymore.

ID: KVUULVBH-euc

**Comment by retorquere** [comment]
It seems to work  only because I removed the code that prompted the reinstall. The information I (finally) got from Zotero doesn't seem to be right. To be continued.

**Comment by retorquere** [comment]
Can you try the same with 2098?

**Comment by AntonOellerer** [comment]
Oc, HXAVW6JV-euc :+1:

**Comment by retorquere** [comment]
Great -- we're one step ahead, and you've actually helped me a long-standing annoyance in BBT; when translators update, a restart is no longer needed! Yay! But for your situation, we've solved a symptom, not the cause, because the cause of the problem in your case is that at every start, Zotero says it can't find the BBT translators.

When you quit Zotero, are the BBT translators actually present?

**Comment by retorquere** [comment]
And can you get me a new log, same procedure?

**Comment by AntonOellerer** [comment]
Nice :sweat_smile: 
The log id is 23HWAFHH-euc, how do I check for the presence of the translators?

**Comment by retorquere** [comment]
They're in your zotero storage directory, under `zotero/translators`

**Comment by AntonOellerer** [comment]
I attached the output of `Zotero/translators`, I hope I don't leak any sensitive information :sweat_smile: [translators.txt](https://github.com/retorquere/zotero-better-bibtex/files/8127929/translators.txt)

**Comment by retorquere** [comment]
Nothing secret in there, but that confirms what I expected. It's just that when I ask Zotero whether the BBT translators are installed, it always says "no" in your case. 2100 will work for you, but has the unfortunate effect that the caches will be dropped every start; BBT drops the cache when translators are updated, and Zotero is telling BBT that the translators must be reinstalled every time, so...

I've asked on the zotero dev group again, but at the very least, you won't always get these restart requests with the current changes. I'm going to put out a new release with this (you will be upgraded automatically, no need to do anything), but I do hope we can still find your problem.

**Comment by AntonOellerer** [comment]
Ok, thank you very much! :pray: 
I am afraid my thesis will go one for some time, so I hope I can assist you with debug information whenever needed.

**Comment by retorquere** [comment]
I'll just have to wait (again) for more information from the Zotero team. I don't know what's so different about your installation that you get this effect.

Did you ever try the tarball version BTW?

**Comment by AntonOellerer** [comment]
Yeah, all of the debug logs should be from the official tarball version

**Comment by retorquere** [comment]
Can you get me a new log, same procedure?

**Comment by AntonOellerer** [comment]
UVR73RTI-euc :)

**Comment by retorquere** [comment]
again please

**Comment by AntonOellerer** [comment]
55BQNRI9-euc :+1:

**Comment by retorquere** [comment]
Awesome, that was it, thanks! A new release is going through the test suite. You can force-update once it drops in ~ 30 minutes, but it's just a version number slapped onto build 2112, and you will be upgraded automatically in the next 48 hours if you don't do anything.

So happy that this restart issue is now gone for everyone.

**Comment by AntonOellerer** [comment]
Very nice, thank you a ton! :pray: :pray:
