### ISSUE TITLE
Citation key format of the exported library cannot be changed

### ISSUE THREAD

**Issue by fangbq** [retorquere/zotero-better-bibtex#2035]
Why is the citation key format of the exported library not changed after I changed this item?

![iShot2022-02-03 02 34 43](https://user-images.githubusercontent.com/6072905/152216526-84d5c1a1-cc0d-4b8f-91c3-c14c821ddcc7.jpg)

My Export setting:
<img width="810" alt="Screenshot 2022-02-03 at 2 38 19 AM" src="https://user-images.githubusercontent.com/6072905/152216885-c59cae9b-35f1-4da0-90b6-156810f92c54.png">
<img width="419" alt="Screenshot 2022-02-03 at 2 39 04 AM" src="https://user-images.githubusercontent.com/6072905/152216985-9d1b9850-1451-4d66-83af-57df57b00997.png">

Zotero version: 5.0.97-beta.64+ae7bfe7f4
BBT version: 6.1.10
Support log ID: FLDPD8VC-apse

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/citing/:

> **note that changing the pattern used to cause all your non-pinned keys to be regenerated in Zotero 4**. In Zotero 5, this is no longer the case; changing a pattern will only affect references being created/changed after you changed the pattern. If you want your keys to update after a pattern change you will have to select your references, right-click, and select Refresh. This will not affect keys you have pinned.

**Comment by fangbq** [comment]
@retorquere Solved. Thank you!
