### ISSUE TITLE
Is there any way to jump/link to an Obsidian note from the corresponding item in Zotero?

### ISSUE THREAD

**Issue by fangbq** [retorquere/zotero-better-bibtex#2041]
I can create and open an obsidian note in Obsidian for any imported references from Zotero now.

What if I want to open the corresponding obsidian note when I am reading a pdf in Zotero (using the internal Zotero pdf viewer)?
Is there any way to jump/link to Obsidian from Zotero?

Support log ID:

**Comment by retorquere** [comment]
This seems like something you should ask the zotero team, it's not clear to me how BBT would be involved in this.

**Comment by fangbq** [comment]
@retorquere Thanks for your suggestion. I should ask this question in the Obsidian forum. I'm just curious about your workflow on this.

**Comment by retorquere** [comment]
I don't use obsidian in concert with Zotero.
