### ISSUE TITLE
Support for migrating from word to LaTeX

### ISSUE THREAD

**Issue by kokalz** [retorquere/zotero-better-bibtex#2043]
I'm trying to follow the instructions from https://retorque.re/zotero-better-bibtex/citing/migrating/ to move a paper from word to latex. The guide references better bibtex csl file in order to perform that. However the quoted link is empty and no csl file is available.

I tried to find the file form the previous releases of the software (pre 6.0.0) but trying to install that one in Zotero gives an "unexpected error".

Is this action something that is still supported? If so, where could the latest version of the .csl file be downloaded?

Support log ID:

**Comment by eppfel** [comment]
The link to the CSL file is still broken on this page: https://retorque.re/zotero-better-bibtex/citing/migrating/

**Comment by retorquere** [comment]
It's back up now.
