### ISSUE TITLE
Better BibTex for Zotero is incompatible with Zotero 6.0 beta.1+c6d03753f.

### ISSUE THREAD

**Issue by danieltomasz** [retorquere/zotero-better-bibtex#2046]
After the update cause by problems with latest beta MacOS  12.3 add-on stopped working
https://forums.zotero.org/discussion/94408/zotero-does-not-run-under-macos-12-3beta#latest

**Comment by johnkingeu** [comment]
Better Bibtex fails to install on the latest Zotero beta (Zotero 6.0 beta.1+c6d03753f under MacOS 12.1)
