### ISSUE TITLE
cache disabled

### ISSUE THREAD

**Issue by walkinverse** [retorquere/zotero-better-bibtex#2048]
Everything used to work, and all of a sudden it no longer exports.  I tried changing the setting to idle, on-change and it does not work.  Every time I add a new reference I have to manually go to the screen and click export now. 

My OS is Mac Catalina 10.15.7

Support log ID: FX7MH8QV-refs-euc

**Comment by walkinverse** [comment]
new ID: 38CJJKDU-refs-euc

I also sud grep to find the entry and it's not there.  For whatever reason is no longer exports.  I have to manually do it every-time I add a new record to zotero.

**Comment by retorquere** [comment]
Can you generate a new log from 2059?

**Comment by walkinverse** [comment]
Just tested by adding a new record with 2059 and still not in the file.  Even modified after adding to zotero.

id: 32GCK73Y-refs-euc

**Comment by retorquere** [comment]
these aren't fixes, they just add diagnostic logging. Can you generate a new log from 2061?

**Comment by walkinverse** [comment]
ID: 2Y4CCILJ-refs-euc

**Comment by retorquere** [comment]
Can you choose "Restart with debugging enabled" from the help menu, reproduce the problem, and send a new log?

**Comment by retorquere** [comment]
Same again please, restart with debugging enabled after installation, reproduce, new log

**Comment by walkinverse** [comment]
New ID for 2062: WGF2GQS4-refs-euc

**Comment by walkinverse** [comment]
New ID for 2062: WGF2GQS4-refs-euc

**Comment by walkinverse** [comment]
ID: JLEE74I9-refs-euc

**Comment by walkinverse** [comment]
Any update?  Did you receive my last ID?

**Comment by retorquere** [comment]
No, and yes, respectively. I've been swamped the last few days.

**Comment by retorquere** [comment]
Still only for diagnosis, so a new log please.

**Comment by walkinverse** [comment]
ID: 42QFT77I-refs-euc

**Comment by retorquere** [comment]
Still only for diagnosis, so new log again please.

**Comment by walkinverse** [comment]
ID: P84GJMH3-refs-euc

**Comment by walkinverse** [comment]
ID: P84GJMH3-refs-euc

**Comment by retorquere** [comment]
And again

**Comment by walkinverse** [comment]
Support Log ID: NMHNSVP4-refs-euc

**Comment by retorquere** [comment]
Errrr... just to check, you are aware you have your `autoExportDelay` set to 6493 seconds (approx 108 minutes)?

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autoexportdelay

**Comment by walkinverse** [comment]
What should I set it to try and resolve the issue?

**Comment by retorquere** [comment]
You can right-click and reset it and it will be reset to the default of 5 seconds.

**Comment by walkinverse** [comment]
Ok, done.  Will that fix it?  And thank you for all the help.

**Comment by retorquere** [comment]
> Ok, done.  Will that fix it?  

You tell me.

**Comment by walkinverse** [comment]
I am testing now and it seems to work.  I had to move it to 60 seconds . Reason is at 5, I have a large library over 4K and the CPU heats and the fans kick on hard.  I am on a mac.  But, seems to have fixed it.  Should I continue to use the version 2078?  Thank you again.

**Comment by retorquere** [comment]
You can keep using 2078 or manually revert to 6.2.5. 2078 is just 6.2.5 plus extra logging. Either one will automatically be updated when a new version comes out.

4k is not so large that it should be a problem though. With your settings, everything should be cached. If you manually export your library twice, how long does the 2nd export take?

**Comment by walkinverse** [comment]
About 15 seconds and it's say 0% cached.  The first time took about 45 seconds.

**Comment by retorquere** [comment]
That could be explained by the serialization cache getting filled but not the output cache. We can look into that if you want. The output cache should get filled with your settings.

**Comment by walkinverse** [comment]
Support Log Id: 5BAZTPTD-refs-apse

**Comment by walkinverse** [comment]
Log Id:  WZB66BCR-refs-euc

**Comment by retorquere** [comment]
You have caching turned off. Please go into BBT prefs -> export -> misc and turn it back on. It is on by default.

**Comment by walkinverse** [comment]
Do you want me to run another test?

**Comment by retorquere** [comment]
Sure, but the most important thing is whether it is now faster after the cache has filled. A log will they me that, but it should be noticeably faster.

**Comment by walkinverse** [comment]
It started again.  After a new update to Zotero, it broke. Support Log ID: DPD35TDH-refs-euc

**Comment by retorquere** [comment]
What broke? There is no error in `DPD35TDH-refs-euc`.

**Comment by retorquere** [comment]
you still have caching off BTW.

**Comment by walkinverse** [comment]
It's the same issue as before. It won't auto export after the update to Zotero. I did not change any settings once we had it working. Where can I turn the cache back on? I noticed it changed the auto export again from the 60 ms we set.

**Comment by retorquere** [comment]
> It's the same issue as before. It won't auto export after the update to Zotero.

If you say something is broken, it is not the same. Auto-export worked when you first reported the issue, you just had a very, very long delay set (which I didn't think to check when you reported it, which is my bad). Auto-export worked as intended. Aside that, there was one thing that actually was broken, which was caching. So when you said "it broke", I didn't know what you mean.

> Where can I turn the cache back on?

Export - Misc - Enable caching for background exports.

I don't know what keeps resetting your preferences. To be clear, the way I see it, nothing was broken but the caching, and there's something that meddles with your settings.

> I noticed it changed the auto export again from the 60 ms we set.

60 seconds more likely, but you currently have it set to 120, which is two minutes. Do auto-exports start if you wait two minutes?

**Comment by walkinverse** [comment]
Sorry for the confusion. My bad. A while back ago, I accidentally installed the beta version of Zotero. And I do not know how to get back to the stable release without losing everything. I wonder if every time an update installs via beta it changes things?

I just turned on the cache.  I will be doing research later today and I will let you know if runs. I thought the time was milliseconds also.  Sorry.  I'll set it to one minute and see how it goes.  Will keep you informed. Thank. you again for all your help, I appreciate it a ton.

**Comment by retorquere** [comment]
> And I do not know how to get back to the stable release without losing everything. 

I don't think this is possible. But I'm seeing steady recommendations to just stay on the beta, as it's stable, and the release will be out soon.

> I just turned on the cache. I will be doing research later today and I will let you know if runs. I thought the time was milliseconds also. Sorry. I'll set it to one minute and see how it goes. Will keep you informed. Thank. you again for all your help, I appreciate it a ton.

You are very much welcome. Don't read too much into my earlier lecturing, I have autism and tend to explain things in great detail even when not really needed, which sometimes comes across as berating. This is not my intent.
