### ISSUE TITLE
No manual export with latest Zotero 6.0-beta.1+c6d03753f

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#2051]
I am unable to export manually under

Zotero 6.0-beta.1+c6d03753f

My set-up:
- MacOS 12.2.1 (21D62)
- MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
- 2.7 GHz Quad-Core Intel Core i7
- 16 GB 2133 MHz LPDDR3

Support log: MGQQLTTF-euc

Thanks for looking into this!

**Comment by retorquere** [comment]
I don't see a manual export in `MGQQLTTF-euc`. Can you do a manual export using Better BibTeX (not Better BibLaTeX) and send a new log?

I do see one error in `MGQQLTTF-euc` which says

```
/Users/jrennstich/Dropbox/mylibrary.bib does not have a parent folder
```

which would mean `/Users/jrennstich/Dropbox` does not exist as far as Zotero can tell?

**Comment by jrennstich** [comment]
My sincere apologies. Works like a charm now. Simple Dropbox thing.

**Comment by retorquere** [comment]
No worries.
