### ISSUE TITLE
Conditional on Language

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#2053]
<div type='discussions-op-text'>

<sup>Originally posted by **@jaymaleoca** February 20, 2022</sup>
I've been trying to format the citekey pattern based on language and not been successful yet. 

What I'm trying to do is: to follow a pattern if it's in specified languages (in my case, non-Latin script languages) and use the default otherwise.

For example,
- default: **[auth][year][title]** ---> if language field is specified as English or unspecified.
- if it's specified as non-English, e.g., use **[extra][year][title]**. The intention is that I want to keep the native script title in the title field but maybe use an English translation in Extra field.

I just can't find a way how to specify this... I've tried using:
> [language=xx], [language:xx], [title:language=xx], [xx] in language short code or
> [language=Chinese], [language:Japanese], [title:language=LongName], [Language]

Can someone help me, please? 😑</div>

**Comment by retorquere** [comment]
@julianaym I think `[language=zh/ja]` will do what you want in 2093. But in the current release, while typing all of the above, the field will have cone orange and if you hover you cursor on it, you will see the error explained and the valid options listed.

**Comment by retorquere** [comment]
No longer interested?

**Comment by jaymaleoca** [comment]
Sorry. Just fell off the cracks as I get busy with my work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jaymaleoca** [comment]
Sounds good. I"ll close it for now.
