### ISSUE TITLE
Omit e. g. 'language' works only for full bib export, not selected items?

### ISSUE THREAD

**Issue by 192933488S** [retorquere/zotero-better-bibtex#2056]
### Discussed in https://github.com/retorquere/zotero-better-bibtex/discussions/2055

<div type='discussions-op-text'>

<sup>Originally posted by **192933488S** February 25, 2022</sup>
Can anyone verify please:

Reproduction steps:

1. Have latest Zotero (+ lib content), latest BBT
2. Set Exports -> Fields -> Omit: 'language'
3. Export a selected item using right click -> Export item
4. Compare with full export of bib File -> Export library
5. Result: Selected item export does not omit 'language'

Would be nice if it works for selected items too.

Regards</div>

**Comment by 192933488S** [comment]
5564UA5F-refs-euc

**Comment by retorquere** [comment]
You have `language` in the skip-fields preference.

You also have caching off. Are you sure you want that?

**Comment by 192933488S** [comment]
Reverse answer:

- Caching not sure? Shall I enable
- Language: Yes, want to remove it since it's troubling the LaTeX class I'm using in combination with bable and other packages, so if it's "out" of the *.bib, it "works" and produces output without warnings etc. The language as such is not showing in the reference or do I misunderstand something?

**Comment by retorquere** [comment]
But it's being exported if you export the whole library? How are you exporting the library?

**Comment by retorquere** [comment]
Are you sure there's a `language` field in the output at all? Can you paste an exported entry here that has the field you want to get rid of?

**Comment by retorquere** [comment]
I'd generally advise to leave caching on, yes.

**Comment by 192933488S** [comment]
> Are you sure there's a `language` field in the output at all? Can you paste an exported entry here that has the field you want to get rid of?

Sure,

Variant 1 – without (Full export, omitting 'language'

@article{zeilinger_experiment_1999,
	title = {Experiment and the foundations of quantum physics},
	volume = {71},
	issn = {0034-6861, 1539-0756},
	url = {https://link.aps.org/doi/10.1103/RevModPhys.71.S288},
	doi = {10.1103/RevModPhys.71.S288},
	number = {2},
	urldate = {2022-01-23},
	journal = {Reviews of Modern Physics},
	author = {Zeilinger, Anton},
	month = mar,
	year = {1999},
	pages = {S288--S297},
}

Variant 2 – with (using right click -> Export item)

@article{zeilingerExperimentFoundationsQuantum1999,
	title = {Experiment and the foundations of quantum physics},
	volume = {71},
	issn = {0034-6861, 1539-0756},
	url = {https://link.aps.org/doi/10.1103/RevModPhys.71.S288},
	doi = {10.1103/RevModPhys.71.S288},
	language = {en},
	number = {2},
	urldate = {2022-01-23},
	journal = {Reviews of Modern Physics},
	author = {Zeilinger, Anton},
	month = mar,
	year = {1999},
	pages = {S288--S297},
}

In principle I was unable to actually also find the specification for the field 'language' and this matters too me. Does it use the standard-format EN, DE, IT, do you know? I have found *.bibs with 'English' or 'ger' randomly. I'd say it's rather unusual nowadays having a field unspecified - or maybe it is and ignored etc.

**Comment by retorquere** [comment]
Those are exported by the Zotero BibTeX export, not the Better BibTeX export.

**Comment by 192933488S** [comment]
Could a "BBT Export item" menu-item be added to the right-click drop-down menu, which would do just that? Exporting a selection of items via Better BibTeX export.

**Comment by retorquere** [comment]
But you can use BBT to export a selection of items or your whole library. When exporting, choose "Better BibTeX" or "Better BibLaTeX" from the dropdown in the export popup (where you can also check "export notes" and such). Zotero will remember the last export format you chose, so it will be the default after that.

**Comment by 192933488S** [comment]
Duh! Right of course that works. Sorry for the long discussion, sometimes the answers is right in front of you, but must be explicitly enforced or set. I wasn't clear to me that this acts as a filter in this case or simple replacement.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/6486666/155792377-b5817d94-d0da-4577-b5be-7a4d8e1021ba.png">

**Comment by retorquere** [comment]
No problem. I now see the reminder isn't shown, I'll set of I can fix that.

**Comment by retorquere** [comment]
2118 will show a warning when you select the standard BibTeX/BibLaTeX format.
