### ISSUE TITLE
BetterBibLaTeX exports articles as @online

### ISSUE THREAD

**Issue by Prometheos2** [retorquere/zotero-better-bibtex#2058]
Hello,

I recently noticed that some items typed as journal articles in Zotero are exported as `@online` objects in Better BibLaTeX files.

Support logs: 9TZKSDLY-euc / Y753UI2J-euc
Possibly related to #1444

For example, this item on Zotero:
```bib
@article{vandenoordWaveNetGenerativeModel2016,
	title = {{WaveNet}: A Generative Model for Raw Audio},
	url = {http://arxiv.org/abs/1609.03499},
	shorttitle = {{WaveNet}},
	journaltitle = {{arXiv}:1609.03499 [cs]},
	author = {van den Oord, Aaron and Dieleman, Sander}
	date = {2016-09-19},
	langid = {english},
	eprinttype = {arxiv},
	eprint = {1609.03499},
}
```

is exported as an @online by BetterBibLaTex: 
```bib
@online{vandenoordWaveNetGenerativeModel2016,
  title = {{{WaveNet}}: {{A Generative Model}} for {{Raw Audio}}},
  shorttitle = {{{WaveNet}}},
  author = {family=Oord, given=Aaron, prefix=van den, useprefix=true and Dieleman, Sander},
  date = {2016-09-19},
  eprint = {1609.03499},
  eprinttype = {arxiv},
  primaryclass = {cs},
  url = {http://arxiv.org/abs/1609.03499},
  archiveprefix = {arXiv},
  langid = {english}
}
```

I remain at your disposal to help resolve this issue, if it proves to be one.

**Comment by retorquere** [comment]
Please select the items in question, right-click, and send a debug log from the pop-up menu that appears.

**Comment by retorquere** [comment]
Does #1704 describe the behavior you experience?

**Comment by Prometheos2** [comment]
> Does #1704 describe the behavior you experience?
It does; I just checked, both 'mislabelled' articles are arXiv ones, and adding a custom journal name labels the resulting article with `@article`

I read that arXiv didn't fare well with BibLaTex, but I didn't expect it to be *that* bad; especially after reading your "Add arXiv data" post-script ^^'

Thank you for the help.

> Please select the items in question, right-click, and send a debug log from the pop-up menu that appears.
Here's the new one, with the test dummy: S4Z625ZV-refs-euc

**Comment by retorquere** [comment]
Your explanation gave me sufficient information, thank you.

@njbart, do you know if the situation has changed for preprints in biblatex?

@Prometheos2 I'm afraid that unless something did change in biblatex in the interim, the postscript is going to have to be the option to change these items to `@article`; I don't think changing the current behavior is better if biblatex will just see them as incomplete `@article`s. What problem do you experience with these items being `@online`?

**Comment by Prometheos2** [comment]
> Your explanation gave me sufficient information, thank you.

You're welcome

> @Prometheos2 I'm afraid that unless something did change in biblatex in the interim, the postscript is going to have to be the option to change these items to `@article`; I don't think changing the current behavior is better if biblatex will just see them as incomplete `@article`s. 

Yeah, I just read about the warning BibLaTex gives with arXiv preprints; it does not sound like a good idea to enforce it.

> What problem do you experience with these items being `@online`?

It's simply that I use the type to filter my bibliographies in LaTex, and I usually split papers from websites.
I started using tags for those preprints, to fix it; and I'm now trying to create a post script to automatically add those.

**Comment by retorquere** [comment]
You can recognize arXiv items by testing for `item.arXiv`. It is always OK to ask with help for postscripts; it is very common that I just write them for people.

**Comment by Prometheos2** [comment]
Thank you for the offer
I wrote this from your post-script samples:
```js
if (Translator.BetterBibLaTeX) {
  // your 'Changing the reference type from collection to book' code
  if (reference.referencetype === 'collection') reference.referencetype = 'book' 

  if ( reference.referencetype === 'online' && item.arXiv) reference.add({ name: 'keywords', value: item.tags.concat('preprint'), enc: 'tags' })
}
```

Do you think it is good?

**Comment by retorquere** [comment]
That looks exactly right to me.

**Comment by njbart** [comment]
Since you asked: No, I’m not aware of any recent changes wrt preprints, except for `unpublished` being updated to output eprint information in 2020 / v3.15. [The discussion around this](https://github.com/plk/biblatex/issues/981) makes it clear that biblatex maintainers continue to recommend `online` for arXiv and other preprints. However, `unpublished` (and `misc`) work just as well, and personally, I’d use `unpublished` for preprints.

**Comment by Prometheos2** [comment]
> That looks exactly right to me.

Thank you for the feedback 😊






> Since you asked: No, I’m not aware of any recent changes wrt preprints, except for `unpublished` being updated to output eprint information in 2020 / v3.15. [The discussion around this](https://github.com/plk/biblatex/issues/981) makes it clear that biblatex maintainers continue to recommend `online` for arXiv and other preprints. However, `unpublished` (and `misc`) work just as well, and personally, I’d use `unpublished` for preprints.

If you don't mind me asking, why do you think so?
What is the difference between `unpublished` and `online`?

**Comment by retorquere** [comment]
If I'd have to guess, unpunished suggests that it might be published at some point, vs a webPage, which is sort of published, but usually no intention of making it more formal.

**Comment by njbart** [comment]
Right. Plus (in vanilla biblatex at least), the output from `unpublished` is visually closer to `article` (titles wrapped in quotes in both cases) that `online` (titles italicized).

**Comment by Prometheos2** [comment]
Thank you for the information
Have a nice day (or evening)

**Comment by Prometheos2** [comment]
(re-closing this, since the bot opened it back because of my comment)
