### ISSUE TITLE
keeping em-dash as it is results in nothing after rendering the tex file

### ISSUE THREAD

**Issue by crliu95** [retorquere/zotero-better-bibtex#2063]
Some papers use em-dash "—" (\u2014 in unicode) in the title. And when these papers are exported into a .bib file by biblatex, the em-dash is not converted in to forms like "---" (three hyphens) or "\textemdash", but only as it is—the "—" form. As a result, the tex engine can not directly render this character and generates nothing in the final pdf file.

Here is an example:

The original title (in Zotero) is:
> Suing the Leviathan—An Empirical Analysis of the Changing Rate of Administrative Litigation in China

The .bib file shows that:
`@article{Li2013SuingLeviathanEmpirical,
  title = {Suing the {{Leviathan}}—{{An Empirical Analysis}} of the {{Changing Rate}} of {{Administrative Litigation}} in {{China}}},
  ...
`
in which I think the em-dash here (between the "Leviathan" and "An") should be changed into something like "---" (three hyphens) or "\textemdash".

And the pdf looks like:

![image](https://user-images.githubusercontent.com/20499205/156883243-0ab47d8f-bcb2-4617-8e92-6b3d0bac06a3.png)

The debug log ID is: PG5P58CX-refs-apse . And I am using the TexLive 2020 with XeLaTeX engine on Overleaf to render the tex file.

**Comment by retorquere** [comment]
I don't know whether you were exporting using using Better BibTeX or Better BibLaTeX. I see a Better BibLaTeX export running in your log, so for the moment I'm going to assume that is where you experienced the problem

biblatex supports unicode, so I leave unicode in place by default. If you are getting compilation errors, you may not have set up biblatex processing correctly. You can make BBT change unicode to LaTeX commands for Better BibLaTeX exports however if you want, see [Export unicode as plain-text latex commands](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#export-unicode-as-plain-text-latex-commands).

**Comment by crliu95** [comment]
> I don't know whether you were exporting using using Better BibTeX or Better BibLaTeX. I see a Better BibLaTeX export running in your log, so for the moment I'm going to assume that is where you experienced the problem

Exactly! I was using Better BibLaTeX exporting the entrys to the .bib file.

> biblatex supports unicode, so I leave unicode in place by default. If you are getting compilation errors, you may not have set up biblatex processing correctly. You can make BBT change unicode to LaTeX commands for Better BibLaTeX exports however if you want, see [Export unicode as plain-text latex commands](https://retorque.re/zotero-better-bibtex/installation/preferences/export/#export-unicode-as-plain-text-latex-commands).

Oh, I just found out there is an option (in Zotero -> edit -> preference -> Better BibTeX)  indicating for the unicode translation issue. After setting this up, the annoying "—" is changed into \textemdash , which is perfect.

Thanks for your kind and timely help!

**Comment by retorquere** [comment]
You're welcome.
