### ISSUE TITLE
Not auto-pinning citekey

### ISSUE THREAD

**Issue by m-pauper** [retorquere/zotero-better-bibtex#2067]
Zotero version 5.0.96.3
BBT version 6.2.10

I am not sure what I am doing wrong but BBT is not automatically pinning the citekey. I have looked for the autoPin in hidden settings, 
but it is not there. Only autoPinDelay, which is set to 0.

Let me know if there is something I should double-check on my side or whether you need a support log.

Thanks!

**Comment by m-pauper** [comment]
Support log ID: WTMXA2GS-refs-euc

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay

Unrelated, but you have caching off. That will affect BBT performance, I'm not sure that is intentional on your part.

**Comment by retorquere** [comment]
Meaning if you set autopin delat to anything non-zero, it becomes active. 0 means off.
