### ISSUE TITLE
Automatically pin keys from InspireHEP

### ISSUE THREAD

**Issue by ChenSun-Phys** [retorquere/zotero-better-bibtex#2068]
I am not sure if it's a switch that I've missed -- is it possible to automatically pin keys from InspireHEP upon importing the bib entry or right before (auto) exporting to bibtex? Thanks.

**Comment by retorquere** [comment]
It's possible to set the pattern to `[inspire-hep]` and then enable [autoPin](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay), but that will not solely apply to keys that can be fetched from inspire-hep.

There is no facility to pin just before export.

**Comment by ChenSun-Phys** [comment]
Thank you for the prompt response! I'm able to set autoPinDelay to a value larger than zero. Would you mind clarifying how to set the pattern to `[inspire-hep]` ? Is this also a switch among the hidden parameters?

**Comment by ChenSun-Phys** [comment]
Oh I realized that you meant setting "Citation key format" to `[inspire-hep]`. That works. Thanks a lot!
