### ISSUE TITLE
Copy & paste is not working.

### ISSUE THREAD

**Issue by Qiwei-Zhao** [retorquere/zotero-better-bibtex#2069]
I want copy one highlight on the PDF in zotero reader, and paste it to other apps, but the Copy & paste function is not working.
If I turn off the BBT plugin, I can do the copy and paste. Normally, the copy text is the text + link format like: 
_“one on their own”: they do not represent the shared goal and hence disregard the partner’s sub-goal, and this impairs the performance when mutual adj” ([Sacheli et al., 2015, p. 4](zotero://select/library/items/7ZRQ7KPB)) ([pdf](zotero://open-pdf/library/items/3IY8IYTD?page=4&annotation=AA42DE8M))_
so I can quickly jump and locates the highlight in other app.

zotero version: 6.0-beta.10+b1d11bf7d
BBT version: v6.2.14

**Comment by retorquere** [comment]
I need you to reproduce the problem and send a support log as per point 2.
