### ISSUE TITLE
From Markdown to DOCX + Zotero live citations with pandoc not fully working

### ISSUE THREAD

**Issue by rgaiacs** [retorquere/zotero-better-bibtex#2070]
Consider the following minimal markdown example:

```
$ cat mwe.md 
---
title: Minimal Working Example
author: Raniere Silva
---

Blah blah [@costadasilvaCollaborationsWorkshop20182019].
```

I run

```
$ pandoc --from markdown --to docx --citeproc --bibliography zotero.bib --lua-filter=zotero.lua --metadata=zotero_scannable_cite:true --metadata=zotero_client:zotero mwe.md --out\
put mwe.docx
zotero-live-citations a266bf0e6
```

and pandoc will convert my Markdown file to DOCX. The produced DOCX is has `Do Zotero Refresh`:

![Screenshot from 2022-03-17 14-56-56](https://user-images.githubusercontent.com/1506457/158753846-ac1888df-ea67-4c89-8684-4479343dac18.png)

When I try to refresh, Zotero tells me

> You must insert a citation before performing this operation.

Can you help me have the Pandoc filter working?

# Environment information

- Pandoc 2.17
- Zotero 6.0-beta.5+8b7afcf24
- Better BibTex for Zotero 6.2.10
- Zotero LibreOffice Integration 5.0.23

**Comment by retorquere** [comment]
Don't use --bibliography. Using that, pandoc will have converted the citemarkers to plain text before my script gets to them.

**Comment by rgaiacs** [comment]
Support log ID: TD2E2FG8-refs-apse

@retorquere Thanks for the reply. Very naive from my side to use `--bibliography` and `--citeproc`. I run

```
$ pandoc --from markdown --to docx --lua-filter=zotero.lua --metadata=zotero_scannable_cite:false --metadata=zotero_client:zotero mwe.md --output mwe.docx
```

and I still face the same issue. After some exploration, I got the following message from LibreOffice Writer's Zotero Integration

> This document contains Zotero ReferenceMarks. Upon reopening the document, Zotero will be unable to edit existing citations or add new references to the bibliography.
>
> To save Zotero citation information, please select the "ODF Text Document" format when saving, or switch to Bookmarks in the Zotero Document Preferences.

I run

```
pandoc --from markdown --to odt --lua-filter=zotero.lua --metadata=zotero_scannable_cite:false --metadata=zotero_client:zotero mwe.md --metadata=zotero_csl_style:apa --output mwe.odt
```

and `Zotero Refresh` worked. My conclusion is that the bug is with LibreOffice Writer or LibreOffice Writer's Zotero extension support to DOCX. I submit https://github.com/retorquere/zotero-better-bibtex/pull/2071 to clarify this to future users. 

Thanks for the great software. I will leave this issue open so it get a closing comment from you.

**Comment by retorquere** [comment]
I'm actually not sure how compatibility across these formats is between word processors. I don't use Word or LO unless a specific task demands it, so I have very little experience with them.

Great that your problem got resolved.

**Comment by retorquere** [comment]
Can you try

```
pandoc --from markdown --to odt --lua-filter=zotero.lua --metadata=zotero_transferable:true mwe.md --metadata=zotero_csl_style:apa --output mwe.odt
```

**Comment by rgaiacs** [comment]
# DOCX

When I run

```
$ pandoc --from markdown --to docx --lua-filter=zotero.lua --metadata=zotero_transferable:true --metadata=zotero_csl_style:apa mwe.md --output mwe.docx
```

I get the following **error**

```
zotero-live-citations a266bf0e6
Error running filter zotero.lua:
zotero.lua:2070: Scannable-cite documents are not transferable
stack traceback:
        zotero.lua:2070: in function 'Meta'
```

# ODT

When I run

```
$ pandoc --from markdown --to odt --lua-filter=zotero.lua --metadata=zotero_transferable:true --metadata=zotero_csl_style:apa mwe.md --output mwe.odt
```

I get the same error

```
zotero-live-citations a266bf0e6
Error running filter zotero.lua:
zotero.lua:2070: Scannable-cite documents are not transferable
stack traceback:
        zotero.lua:2070: in function 'Meta'
```

**Comment by baptisteImbert** [comment]
Hi,
Following rgaiacs method did the trick for me as well as long as I use papers stored in "My Library" in Zotero.
However, my papers are actually stored in a Group library called "x".
So in my yaml header, I mentioned "library: x". Yet I get the following error:
```
could not fetch Zotero items: no items found
@oziolorAnnotationDepthConfounds2021 not in Zotero
```
Would you have any clue on what I am doing wrong?

Using pandoc 2.11 and Zotero 6.0.4.

**Comment by rgaiacs** [comment]
@baptisteImbert I was unable to reproduce the bug.

```
$ cat mwe.md 
---
title: Minimal Working Example
author: Raniere Silva
zotero:
  library: bonej
---

Blah blah [@doubeBoneJFreeExtensible2010].
$ pandoc --from markdown --to odt --lua-filter=zotero.lua --metadata=zotero_scannable_cite:false --metadata=zotero_client:zotero mwe.md --metadata=zotero_csl_style:apa --output mwe.odt
zotero-live-citations a266bf0e6
```

I'm using pandoc 2.17.1.1 and Zotero 6.0.2-beta.4+cc5e1106e but from the log that you provide, I don't think the issue is with pandoc or Zotero.

Can you check that the name of the library is not misspelled? Different case or trailing white space.

**Comment by baptisteImbert** [comment]
Thank you @rgaiacs  for the fast answer. All good now, it was actually a simple mistake on my side.
I copied the header from the doc without realizing the block ended with `...` instead of `---`.
Anyway, thanks for the BBT extension, it's great!
