### ISSUE TITLE
Option to replace " with "{}

### ISSUE THREAD

**Issue by JohannesNeuwirth** [retorquere/zotero-better-bibtex#2072]
Hi, thanks for the great tool!

When I export the Library to Better BibLaTeX, in some fields Umlauts are changed (eg ä → `\"a`). This is true for most fields and does not effect keywords. But `"` is not changed to `"{}`, which leads to the amusing output:
`"Matrix" als...` → `"Matrixäls...`

Support log ID: GW82ZJQG-refs-euc

I tried reinstalling and restarting Zotero and checking and unchecking the boxes 'Export unicode as plain-text latex commands'.

**Comment by retorquere** [comment]
Can you paste the output you get? I get pretty much what I expected:

```
@book{wolf2020Zwischen,
  title = {Zwischen Illusion und Wirklichkeit Wachowskis "Matrix" als filmische Auseinandersetzung mit der digitalen Welt},
  author = {Wolf, Christof},
  date = {2020},
  publisher = {{Loyola Productions Munich GmbH}},
  isbn = {978-3-939926-10-8},
  langid = {german},
  annotation = {OCLC: 1226310859}
}
```

which renders to

> Wolf, C. (2020). Zwischen Illusion und Wirklichkeit Wachowskis "Matrix" als
filmische Auseinandersetzung mit der digitalen Welt. Loyola Productions
Munich GmbH.

for me. I don't see anything out of the ordinary.

**Comment by retorquere** [comment]
Are you saying that just generally, `"` should be changed to `"{}`? That seems strange to me.

**Comment by JohannesNeuwirth** [comment]
Weird. It reacts differently with different packages.
My output is:
> Wolf, Christof (2020). Zwischen Illusion und Wirklichkeit Wachowskis ”Matrix ̈als filmische Auseinandersetzung mit der digitalen Welt.
Loyola Productions Munich GmbH (siehe S. 3, 6 f.).

Replacing `'` with `'{}` in all instances would solve my particular problem, or to use `\enquote{}` with  csquotes, but I don't know what problems would come up with this (except from compatibility issues).

Here some examples:

```
\documentclass[a4paper, fontsize=12pt]{scrreprt}

\usepackage[english, ngerman]{babel}
\usepackage[T1]{fontenc}
	
\begin{document}
"Matrix" als
\end{document}
```
> "Matrixäls

```
\documentclass[a4paper, fontsize=12pt]{scrreprt}

%	\usepackage[english, ngerman]{babel}
	\usepackage[T1]{fontenc}

	
\begin{document}
"Matrix" als
\end{document}
```
>"Matrix" als
```
\documentclass[a4paper, fontsize=12pt]{scrreprt}

	\usepackage[english, ngerman]{babel}
%	\usepackage[T1]{fontenc}

	
\begin{document}
"Matrix" als
\end{document}
```
>”Matrixa ̈ls

**Comment by JohannesNeuwirth** [comment]
I thought that it was `csquote`s fault but `babel` is the culprit. But I cannot relinquish `babel` .

**Comment by retorquere** [comment]
@njbart? The latter two behaviors seem bizarre to me. The only way I see I could accommodate this (due to the char-by-char translation BBT does) is by exporting `"` as `{}"{}`, but I can see a lot of objections coming my way if I do that. And I'd rather not add yet another preference to BBT.

This seems like a great candidate for BBTs [enquote support](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#csquotes). You would have to edit the title to have discernable left and right quotes.

**Comment by JohannesNeuwirth** [comment]
Just for context:
The Matrixa ̈ls-behaviour is quite a problem with German LaTeX. Each PDF-viewer handles it differently when copying and pasting. This is especially problematic when writing something with a character-limit.

**Comment by JohannesNeuwirth** [comment]
I found a solution: Modifying babel with the option `shorthands=off` solved my particular problem at least.
```
\documentclass[a4paper, fontsize=12pt]{scrreprt}

\usepackage[shorthands=off, english, ngerman]{babel}
\usepackage[T1]{fontenc}
	
\begin{document}
"Matrix" als
\end{document}
```
> "Matrix" als

However, I still think that a general solution would be helpful (if possible).

**Comment by retorquere** [comment]
Tests are running on a new build

**Comment by retorquere** [comment]
But is there a more general problem that isn't solved by turning shorthand off?

**Comment by JohannesNeuwirth** [comment]
Awesome! I think it would be a compatibility issue.
Using something like `\"a \"{a} {\"a}` still works. I just use all the Unicode characters I desire in my code, so the shorthands never were useful to me in particular.

**Comment by retorquere** [comment]
Do you know the full range of characters that needs special treatment under babel-ngerman-shorthand?

**Comment by JohannesNeuwirth** [comment]
I found it [here](https://texdoc.org/serve/ngermanb/0)(page 2)

**Comment by retorquere** [comment]
I'll think about making a more easily configurable method, but with build 2199, you can go into the hidden prefs, find a key named `charmap`, and enter an augmentation table for the charachter mapping of BBT. In my testcase I used `{"\"":"{\"}"}`, which means "if you find `"`, write that out as `{"}`. `"` is a special char to JSON, other characters will be more easily readable, eg, `{"'":"{'}"}`.

**Comment by retorquere** [comment]
This is a more general facility for something like csquotes, I may well migrate that to this format. Not sure yet.

**Comment by JohannesNeuwirth** [comment]
Now it appears in the `.bib` file as `{"}` but I‘m getting some obscure errors when running LaTeX. 
I’ll get to it asap (maybe not tomorrow).

**Comment by retorquere** [comment]
You can add whatever you want for the replacement. You can map it to `"{}` if you want, but I don't understand why `{"}` could give you errors.

**Comment by JohannesNeuwirth** [comment]
Putting in `{"\":"\"{}"}` worked. I'll play around with the error messages when I have time. 
Thank you so much!

**Comment by retorquere** [comment]
This build replaces the rather awkward json mapping with a CSV file on disk: https://github.com/retorquere/zotero-better-bibtex/blob/gh-2072/site/content/installation/preferences/hidden-preferences.md#charmap
