### ISSUE TITLE
Tried to add Better Bibtex citekey column to Zotero 6 but now I can't see any of my papers

### ISSUE THREAD

**Issue by cccaldwell** [retorquere/zotero-better-bibtex#2073]
When I first launched Zotero 6, my columns were missing some elements, so I started by right clicking on the columns and adding citation keys as a column. My center pane disappeared, and I lost collection-level access to my papers (although they are still on the hard drive).

Now when I start Zotero, it shows my papers briefly in the center pane, then they disappear and I can't see or access them. The collections pane folders seem empty, and the center pane is blank.

I removed Better Bibtex, restarted, used sync to try to restore. Nothing has worked so far

I reported this to the Zotero forums, and it was suggested I post here as well.

**Comment by cccaldwell** [comment]
I deleted bbt as part of my troubleshooting, so there is no bbt support log. Below is the error report generated by Zotero:

Report ID: 1891320183
[JavaScript Error: "TypeError: Argument 1 of Node.appendChild is not an object." {file: "chrome://zotero/content/itemTree.js" line: 3948}]

[JavaScript Error: "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the "Pause on exceptions" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue." {file: "resource://zotero/loader.jsm -> resource://zotero/react-dom.js" line: 4000}]

[JavaScript Error: "An error has occurred. Please restart Zotero.

You can report this error by selecting "Report Errors…" from the Help menu."]

[JavaScript Error: "this.crash@chrome://zotero/content/xpcom/zotero.js:1235:21
componentDidCatch@chrome://zotero/content/libraryTree.js:228:190
callback@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:20189:9
callCallback@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:12348:5
commitUpdateQueue@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:12369:11
commitLifeCycles@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:20739:13
commitLayoutEffects@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:23456:9
callCallback@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:3942:11
invokeGuardedCallbackDev@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:3991:9
invokeGuardedCallback@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:4053:5
commitRootImpl@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:23181:11
unstable_runWithPriority@resource://zotero/loader.jsm -> resource://zotero/react.js:2764:14
runWithPriority$1@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:11306:12
commitRoot@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:23020:5
performSyncWorkOnRoot@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:22359:5
flushSyncCallbackQueueImpl/<@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:11357:28
unstable_runWithPriority@resource://zotero/loader.jsm -> resource://zotero/react.js:2764:14
runWithPriority$1@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:11306:12
flushSyncCallbackQueueImpl@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:11352:11
flushSyncCallbackQueue@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:11339:5
scheduleUpdateOnFiber@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:21923:11
enqueueForceUpdate@resource://zotero/loader.jsm -> resource://zotero/react-dom.js:12534:7
Component.prototype.forceUpdate@resource://zotero/loader.jsm -> resource://zotero/react.js:409:5
clearItemsPaneMessage/<@chrome://zotero/content/itemTree.js:3749:582
clearItemsPaneMessage@chrome://zotero/content/itemTree.js:3749:557
changeCollectionTreeRow@chrome://zotero/content/itemTree.js:3835:225
"]

[JavaScript Error: "TypeError: Argument 1 of Node.appendChild is not an object." {file: "chrome://zotero/content/itemTree.js" line: 3948}]

[JavaScript Error: "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the "Pause on exceptions" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue." {file: "resource://zotero/loader.jsm -> resource://zotero/react-dom.js" line: 4000}]

[JavaScript Error: "Upload request 1/2K7B9FII failed"]

[JavaScript Error: "You have reached your Zotero File Storage quota. Some files were not uploaded. Other Zotero data will continue to sync to the server.

See your zotero.org account settings for additional storage options.

Wieman_2014_Large-scale comparison of science teaching methods sends clear message.pdf (626 KB)"]

[JavaScript Error: "this.tree is null" {file: "chrome://zotero/content/itemTree.js" line: 3757}]

[JavaScript Error: "this.tree is null" {file: "chrome://zotero/content/itemTree.js" line: 3757}]

[JavaScript Error: "Upload request 1/24YRDYZN failed"]

[JavaScript Error: "You have reached your Zotero File Storage quota. Some files were not uploaded. Other Zotero data will continue to sync to the server.

See your zotero.org account settings for additional storage options.

Castilla et al. - 1985 - Human Exclusion from the Rocky Intertidal Zone of .pdf (1318 KB)"]

[JavaScript Error: "this.tree is null" {file: "chrome://zotero/content/itemTree.js" line: 3757}]

[JavaScript Error: "this.tree is null" {file: "chrome://zotero/content/itemTree.js" line: 3757}]

version => 6.0, platform => MacIntel, oscpu => Intel Mac OS X 10.15, locale => en-US, appName => Zotero, appVersion => 6.0, extensions => ZotFile (5.1.0, extension), Pubpeer Plugin for Zotero (0.0.13, extension), Zotero Word for Mac Integration (5.0.39.SA.6.0, extension), Zotero LibreOffice Integration (5.0.25.SA.6.0, extension), ZoteroAbstractCleaner (0.0.1, extension, disabled), Zotodo (0.7.0, extension, disabled)

**Comment by retorquere** [comment]
If you deleted BBT, it can have no effect, so if the problem persists without BBT installed, it is a Zotero problem. I'm sorry you're being sent back and forth. Where did you post this on the Zotero forums?

**Comment by cccaldwell** [comment]
The Zotero Forum is now saying it's a Zotero issue too. Which is what I figured. Thanks for your help.

**Comment by retorquere** [comment]
No worries.
