### ISSUE TITLE
Empty citation-key causes scrub-database loop

### ISSUE THREAD

**Issue by gongxun45** [retorquere/zotero-better-bibtex#2074]
[debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/8310821/debug.txt)
When I open Zetero, I get a prompt like this: 
[javascript application]
Better BibTeX: error saving citekey, restart to repair

and I lose all my citation keys.

**Comment by gongxun45** [comment]
[WVGDYLZF-apse.zip](https://github.com/retorquere/zotero-better-bibtex/files/8310831/WVGDYLZF-apse.zip)

**Comment by retorquere** [comment]
Can you reproduce this and then generate a log before restarting?

**Comment by gongxun45** [comment]
[K6JBZII3-apse.zip](https://github.com/retorquere/zotero-better-bibtex/files/8310846/K6JBZII3-apse.zip)
this only shows when I open Zetero every time. and I generate the log right now. I don't if it works,thank you .

**Comment by retorquere** [comment]
I see the error. On it.

**Comment by retorquere** [comment]
You are on 6.2.10. Can you first upgrade to 6.2.14 and see if the error still exists? If so, I'll need a log like K6JBZII3-apse.

**Comment by gongxun45** [comment]
[X6DMJQQS-apse.zip](https://github.com/retorquere/zotero-better-bibtex/files/8310983/X6DMJQQS-apse.zip)
ok

**Comment by retorquere** [comment]
Can you try build 2205?

**Comment by retorquere** [comment]
I would really prefer to have confirmation.
