### ISSUE TITLE
citation key for Japanese documents

### ISSUE THREAD

**Issue by ShiroTakeda** [retorquere/zotero-better-bibtex#2077]
My Support log ID is "T4Y9NLCW-apse".

I am a Japanese Zotero & BBT user and manage many Japanese documents with Zotero.

BBT automatically generates citation keys. In doing so, BBT has the feature to convert Kanji (Chinese) characters to pin-yin and romaji. However, I don't want to use this feature. That is, I want to use the Kanji characters as they are for the citation key.

Therefore, I have turned off the following two options.

+ Apply kuroshiro romajization in Japanese names/titles. Uses a lot of memory.
+ Enable `jieba' filter in citekey patterns. Uses a lot of memory.

However, if I let BBT automatically generate citation keys, all Kanji characters are converted to pin-yin. In other words, the behavior is the same as when the jieba filter is turned on.

I would prefer the behavior that the conversion of Kanji to pin-yin only when the above option (jieba filter option) is on.

**Comment by retorquere** [comment]
[Force citation key to plain text](https://retorque.re/zotero-better-bibtex/installation/preferences/#force-citation-key-to-plain-text) is on by default, if you turn it off you will get the behavior you want.

**Comment by ShiroTakeda** [comment]
Thank you very much! I followed your suggestion and it solved the problem.
