### ISSUE TITLE
Lowercase "A" in BBT Sentence Case

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#2078]
Support log: I9TH4EA5-refs-euc

BBT Sentence Case doesn't change the case of single uppercase letters like "C" or "R". However, "A" usually is the English article, rather than a proper noun. So, could "A" also be lowercased when the function is run:

Example:
`insight: A Unified Interface to Access Information from Model Objects in R`

Expected result:
`insight: a unified interface to access information from model objects in R`

**Comment by retorquere** [comment]
Is this for import, or for the right-click option? I see now that I have different implementations for those, I'm going to unify them, but it'd help to know what your baseline is.

**Comment by retorquere** [comment]
BTW thank you for including a debug log.

**Comment by bwiernik** [comment]
I was thinking in the right click option

**Comment by qqobb** [comment]
It seems that BBT sentence case is keeping single-character words capitalized following #1780. You might want to keep "vitamin A" unchanged. (Issue #1742 might also be related.)

> Example:
> `insight: A Unified Interface to Access Information from Model Objects in R`

I guess "A" is capitalized here following the [APA Style](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) title case:

>In title case, capitalize the following words in a title or heading:
> -   the first word of the title or heading, even if it is a minor word such as “The” or “A”

So perhaps BBT sentence case could check for such cases. However, keeping "A" capitalized might also be ok. See the example at the end of [this APA Style guide](https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case) from September 2019.

**Comment by bwiernik** [comment]
APA style guide is irrelevant—Zotero applies APA sentence case as needed. An initial A at the beginning of the subtitle is the most common case, much more common than vitamin A, so making A an exception to the single letter upper case rule is best

**Comment by bwiernik** [comment]
All all-caps words are now being lowercased, rather than just `A`. For example `Type B Personality: A Meta-Analysis` becomes `Type b personality: a meta-analysis` rather than `Type B personality: a meta-analysis`. And `Structured Interviewing for OCB: Construct Validity, Faking, and the Effects of Question Type` becomes `Structured interviewing for ocb: construct validity, faking, and the effects of question type` rather than `Structured interviewing for OCB: construct validity, faking, and the effects of question type`


Two sample items:
SJ6CUYRJ-refs-euc

**Comment by qqobb** [comment]
I guess the change suggested here is to replace `: A ` with `: a `. All single-character `A`'s in the middle of a sentence could be kept unchanged. So add something like

```js
title.replace(/: A /g, `: a `);
```

**Comment by bwiernik** [comment]
No, it really should be any single A. In nearly all cases, an uppercase A is an error

**Comment by qqobb** [comment]
> No, it really should be any single A. In nearly all cases, an uppercase A is an error

There's no title case rule listed [here](https://titlecaseconverter.com/rules/) that capitalizes an article "a" in the middle of a sentence. If you're dealing with erroneous title casing to start with, you could apply Zotero's sentence case function that is more aggressive.

I'm OK with this sentence casing:
```
Type B Personality: A Meta-Analysis
Type B personality: a meta-analysis
```

But I would then also expect:
```
Type A Personality: A Meta-Analysis
Type A personality: a meta-analysis
```

These A's should be preserved in my opinion:
```
Period after a sentence. A new sentence.

Vitamins A, B, and C.

Hepatitis A and hepatitis B vaccines.

Treatment of hepatitis A. Treatment of hepatitis B.

U S A / U. S. A. / U.S.A. / N.A.S.A. / A.M.
```

**Comment by qqobb** [comment]
Well, "A.M." could be turned into "a.m.", but then you'd also end up with "u.s.a.".

**Comment by retorquere** [comment]
Acronyms that are a repetition of Capital-Period get special treatment in my sentence caser.

**Comment by DanteSung** [comment]
Acronyms now seem to not function well.

As mentioned in https://github.com/retorquere/zotero-better-bibtex/issues/2123#issuecomment-1104871248, the original title is: `Is FFT Fast Enough for Beyond 5g Communications?`

Expected: `Is FFT Fast Enough for Beyond 5g Communications?`

What BBT provides: `Is fft fast enough for beyond 5g communications?`

The acronym `FFT` is not considered in the sentence caser.

72XTXMTJ-apse

**Comment by retorquere** [comment]
> What BBT provides: `Is fft fast enough for beyond 5g communications?`

Not on build 2435

**Comment by retorquere** [comment]
Build 2447 was not built on this issue. Separate issues have separate builds, so 2447 does not contain the code present in 2435.

**Comment by DanteSung** [comment]
> Build 2447 was not built on this issue. Separate issues have separate builds, so 2447 does not contain the code present in 2435.

Got it. Would use build 2435 for now. Thanks!

**Comment by DanteSung** [comment]
cool. build 2450 would also do the job.

**Comment by retorquere** [comment]
As soon as we have a consensus here I will release a new version, these builds will auto-update to the formal release.

**Comment by bwiernik** [comment]
looks good to me

**Comment by qqobb** [comment]
I tested 2450. This is a title before and after using BBT's title case function:
```
Q&A: Vitamins A, B, and C. Hepatitis A and hepatitis B vaccines. Treatment of hepatitis A. Treatment of hepatitis B.
Q&a: vitamins a, B, and c. hepatitis a and hepatitis B vaccines. Treatment of hepatitis a. treatment of hepatitis b.
```

I'd expect the title to remain unchanged.

**Comment by retorquere** [comment]
I don't really have a strong opinion one way or the other, so I'd prefer it if you guys could come to a consensus. I do not want to introduce a new configuration preference for this though, and given the naiveté of the sentence cases, it is always on the user to inspect & correct the results. I'm not doing any kind of NLP in the sentence-casing.

**Comment by bwiernik** [comment]
The test qqobb gave is fine. Matching `: A` and `—A` and returning `: a` and `—a` to lowercase initial A in subtitles but leaving others is fine

**Comment by retorquere** [comment]
Do you have a sample title for the latter case?

**Comment by bwiernik** [comment]
`insight—A Unified Interface to Access Information from Model Objects in R`

**Comment by retorquere** [comment]
So 

```
Q&A: A Vitamins A, B, and C Study. Hepatitis A and hepatitis B vaccines. Treatment of hepatitis A. Treatment of hepatitis B.
```

becomes

```
Q&A: a vitamins A, B, and C study. Hepatitis A and hepatitis B vaccines. Treatment of hepatitis A. treatment of hepatitis B.
```

**Comment by retorquere** [comment]
Shouldn't M-dashes have spacing around them? `insight—A` looks like a two-part word.

**Comment by retorquere** [comment]
Oh wait, em-dashes are not hyphens. Got it.

**Comment by retorquere** [comment]
So

```
insight—A Unified Interface to Access Information from Model Objects in R
```

becomes

```
insight—a unified interface to access information from model objects in R
```

**Comment by bwiernik** [comment]
Yes

**Comment by retorquere** [comment]
alright, the updated sentencecaser will be in the next release.

**Comment by retorquere** [comment]
```
Crossroads, Directions and A New Critical Race Theory
```

now sentence-cases to

```
Crossroads, directions and A new critical race theory
```

acceptable damage?

**Comment by retorquere** [comment]
Are the other `A`'s than vitamins and hepatitides?

**Comment by qqobb** [comment]
> acceptable damage?

I'd say yes. It's the consequence of an erroneous title case. The title page (inside) of that book shows "Crossroads, Directions and a New Critical Race Theory". You can check this in Google books or Amazon.

> Are the other `A`'s than vitamins and hepatitides?

https://pubmed.ncbi.nlm.nih.gov/22628224/
Cholinergic-associated loss of hnRNP-A/B in Alzheimer's disease impairs cortical splicing and cognitive function in mice

https://pubmed.ncbi.nlm.nih.gov/3348967/
Clinical features and course of type A and type B vitiligo

https://pubmed.ncbi.nlm.nih.gov/3779524/
Evaluation of the reversed passive latex agglutination (RPLA) test kits for detection of staphylococcal enterotoxins A, B, C, and D in foods

https://psycnet.apa.org/record/1981-30747-001
Type A behavior, hostility, and coronary atherosclerosis.

https://www.nature.com/articles/ncomms15963
The A-B transition in superfluid helium-3 under confinement in a thin slab geometry

https://dl.acm.org/doi/abs/10.1145/3097983.3097992
Peeking at A/B Tests: Why it matters, and what to do about it

**Comment by retorquere** [comment]
Alright, then the current state of things is going into the release.

**Comment by qqobb** [comment]
> Matching `: A` and `—A` and returning `: a` and `—a` to lowercase initial A in subtitles but leaving others is fine

Add a final whitespace, so ": A " becomes ": a " and "—A " becomes and "—a ".

**Comment by retorquere** [comment]
That's already in.
