### ISSUE TITLE
Custom field ordering -- dependent on order entry in "Extra" rather than static

### ISSUE THREAD

**Issue by lukisikul** [retorquere/zotero-better-bibtex#2082]
Hi, I have already seen [this prior closed thread](https://github.com/retorquere/zotero-better-bibtex/issues/512) (and its [documentation on the site](https://retorque.re/zotero-better-bibtex/exporting/scripting/#custom-field-order)) in which a postscript was created to allow for fields to be ordered in a certain way. I am not familiar with this scripting at all, but as far as I can tell this is a static solution, that postscript will cause entries to always export with the specified fields in such an order.

Is there a way to -- whether through another postscript or perhaps a feature I'm missing -- instead specify an ordering based on how the fields are entered in the "Extra" field in Zotero? I am thinking specifically of extra fields (i.e., "tex.____:"), which I have begun to use quite often in my work, and it would be helpful if the fields could stay in the order in which I write them in the "Extra" Zotero field once exported through BBT.

For example, I have an article in which I use custom fields to link to the working paper version of that article, its appendix, and its data file. In "Extra" in Zotero, I'd write:

_tex.url_working_paper: [link]
tex.url_appendix: [link]
tex.url_data_file: [link]_

These fields go toward the end of the BibTeX output automatically, only followed by the "keywords" and "file" BibTeX fields, which I like and would like to keep (i.e., I'd rather not have to specify these fields always appear in the order they're written but at the start of the BibTeX output), but they show up in alphabetical order, such that "tex.url_working_paper" shows up last of the three.

I have begun using these fields a lot, and the field names can vary considerably, so if there is a way to make specifically these extra fields that begin with "tex." stay in the same order I wrote them (and still appear toward the end or at the end of all the other BibTeX fields) this would be ideal.

**Comment by retorquere** [comment]
debug log id for the item in question please. one with `-refs` in it.

**Comment by retorquere** [comment]
Dude, help me help you. I need that debug log.

**Comment by retorquere** [comment]
The easiest is to replicate the BBT sorting algorithm and add the extra-fields into them. It's fairly large, and this will be hard to read if you don't know javascript.

<details><summary>click arrow to show postscript</summary>

```
if (Translator.BetterTeX) {
  // output entry fields are sorted on the order they appear here; items with a `-` in front of them will
  // appear in that order at the end, after all fields that are not named in this list. Fields not named
  // here will sort in the middle alphabetically.
  const fieldOrder = [ // the original leader list
    'type',
    'ids',
    'title',
    'shorttitle',
    'booktitle',
    'author',
    'editor',
    'translator',
    'holder',
    'options',
    'date',
    'origdate',
    'year',
    'month',
    'journal',
    'journaltitle',
    'shortjournal',
    'series',
    'edition',
    'volume',
    'number',
    'eprint',
    'eprinttype',
    'primaryclass',
    'pages',
    'publisher',
    'address',
    'institution',
    'location',
    'issn',
    'doi',
    'url',
    'urldate',
  ].concat(
    Object.keys(item.extraFields.tex), // add the tex. fields in order of appearance
    [ // add the trailer list
      '-keywords',
      '-annotation',
      '-note',
      '-groups',
      '-timestamp',
      '-files',
      '-file',
    ]
  ).reduce((acc, field, idx) => { // assign rankings based on the list order above
    if (field[0] === '-') {
      acc[field.substring(1)] = -(idx + 1)
    }
    else {
      acc[field] = idx + 1
    }
    return acc
  }, {})

  const keys = Object.keys(entry.has).sort((a, b) => {
    const fa = fieldOrder[a]
    const fb = fieldOrder[b]

    if (fa && fb) return Math.abs(fa) - Math.abs(fb) // if they both appear in the list, output them in relative order
    if (fa) return -fa // if only one appears, return that position
    if (fb) return fb
    return a.localeCompare(b) // otherwise, alphabetically
  })
  for (const field of keys) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

</details>

> I saw the automatic message, but I didn't think a support log would be helpful in this instance as I believe this is a feature request more than anything else.

This is really discouraging. For feature requests to I need sample entries, and the log gives them to me. I've tried explaining this in the bot text but that turned out to be too long and people just did not read the wall of text at all, so I reverted to the "just do this please" phrasing. I try to be clear without being too confrontational; I've stuck label-gun in this process to make it less personal, but I don't know how I can make this part of the bot message more clear without being obnoxious:

> **This request is much more likely than not to apply to you, too, _even if you think it unlikely_**, and even if it does not, there's no harm in sending a debug log that turns out to be unnecessary. @retorquere will usually just end up saying "please send a debug log first".

I'm open to suggestions to make this more clear without being off-putting, but having to plead for debug logs is a really depressing part of my support work; I've created label-gun to take that burden off of me, but that still ends up being ignored about half the time.

**Comment by retorquere** [comment]
If the postscript doesn't work for you, you can comment here and the issue will re-open automatically.

**Comment by lukisikul** [comment]
Thank you for sending the postscript. I'm not sure it would solve my issue, however. It could be because I'm not understanding your instructions in the comments of the code, I'm not sure.

I used the postscript to test export of the same reference I showed in my last reply, adding the three extra fields that reference has in their order of appearance:

```
if (Translator.BetterTeX) {
  // output entry fields are sorted on the order they appear here; items with a `-` in front of them will
  // appear in that order at the end, after all fields that are not named in this list. Fields not named
  // here will sort in the middle alphabetically.
  const fieldOrder = [ // the original leader list
    'type',
    'ids',
    'title',
    'shorttitle',
    'booktitle',
    'author',
    'editor',
    'translator',
    'holder',
    'options',
    'date',
    'origdate',
    'year',
    'month',
    'journal',
    'journaltitle',
    'shortjournal',
    'series',
    'edition',
    'volume',
    'number',
    'eprint',
    'eprinttype',
    'primaryclass',
    'pages',
    'publisher',
    'address',
    'institution',
    'location',
    'issn',
    'doi',
    'url',
    'urldate',
  ].concat(
    Object.keys(item.extraFields.tex), // add the tex. fields in order of appearance
    [ // add the trailer list
      '-keywords',
      '-annotation',
      '-note',
      '-groups',
      '-timestamp',
      '-files',
      '-file',
      '-url_published_version',
      '-url_online_appendix',
      '-url_main_figures_and_tables',
    ]
  ).reduce((acc, field, idx) => { // assign rankings based on the list order above
    if (field[0] === '-') {
      acc[field.substring(1)] = -(idx + 1)
    }
    else {
      acc[field] = idx + 1
    }
    return acc
  }, {})

  const keys = Object.keys(entry.has).sort((a, b) => {
    const fa = fieldOrder[a]
    const fb = fieldOrder[b]

    if (fa && fb) return Math.abs(fa) - Math.abs(fb) // if they both appear in the list, output them in relative order
    if (fa) return -fa // if only one appears, return that position
    if (fb) return fb
    return a.localeCompare(b) // otherwise, alphabetically
  })
  for (const field of keys) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

This indeed outputs the correct code that I would expect to see, with those fields in their order of appearance at the end of the bib output. However, I'm not sure how to make it list _any_ extra fields in their order of appearance when exporting an entire library rather than a single reference, the former being my use case. I don't see how this works unless I'm missing something (unless the comment "if they both appear in the list, output them in relative order" is supposed to address this?).

And to be clear, I can't necessarily make a master list of all the extra fields I plan on using and the order I want them to be in, and put that in this postscript, as

A) the extra fields are incredibly varied, e.g., online appendix vs supplementary appendix vs online materials vs data appendix, or even all the various authors when listing a particular paper in the form of tex.url_author_yyyy, and this is a level of detail I don't want to do away with, but even if I did;
B) the preferred order of these various types of extra fields can change depending on the context of the particular reference.

Is there a way to have the library export all "tex" fields in all references in the order of appearance, and at the end of the Bib output?

**Comment by lukisikul** [comment]
I see, then perhaps I've misunderstood, sorry.

I came to my conclusion because if I changed the order of the fields when listing them in that section of the postscript, it changed how the fields were exported in the BibTeX. So it seems like the order in the export doesn't correlate to the order of appearance, as I believe you're saying, but the order when listed in the postscript, which wouldn't work for me when exporting an entire library at once as discussed. I'll provide some examples below, let me know if you need me to submit another support log or anything.

With no postscript, I get the following export on the test reference:
```
@unpublished{Piketty.etal_2017_CapitalAccumulationPrivatePropertyRising,
  title = {Capital Accumulation, Private Property and Rising Inequality in {{China}}, 1978-2015},
  author = {Piketty, Thomas and Yang, Li and Zucman, Gabriel},
  year = {2017},
  address = {{Cambridge, MA}},
  doi = {10.3386/w23368},
  url = {https://www.nber.org/papers/w23368},
  abstract = {This paper . . .},
  url_main_figures_and_tables = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015mainfiguresandtables-2018},
  url_online_appendix = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015onlineappendix-2018},
  url_published_version = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015-2019},
  keywords = {Data Sources: Wealth Inequality Trends},
  file = {C\:\\Users\\lukis\\Zotero\\storage\\JIKL8ST4\\Piketty.etal_2017_CapitalAccumulationPrivatePropertyRising.pdf}
}
```
This is the default alphabetical order rather than the order of appearance in the extra field (which is published version, online appendix, main figures and tables).

<details><summary>With the following postscript I list these fields in the order of appearance, as I'd like them to appear:</summary>

```
if (Translator.BetterTeX) {
  // output entry fields are sorted on the order they appear here; items with a `-` in front of them will
  // appear in that order at the end, after all fields that are not named in this list. Fields not named
  // here will sort in the middle alphabetically.
  const fieldOrder = [ // the original leader list
    'type',
    'ids',
    'title',
    'shorttitle',
    'booktitle',
    'author',
    'editor',
    'translator',
    'holder',
    'options',
    'date',
    'origdate',
    'year',
    'month',
    'journal',
    'journaltitle',
    'shortjournal',
    'series',
    'edition',
    'volume',
    'number',
    'eprint',
    'eprinttype',
    'primaryclass',
    'pages',
    'publisher',
    'address',
    'institution',
    'location',
    'issn',
    'doi',
    'url',
    'urldate',
  ].concat(
    Object.keys(item.extraFields.tex), // add the tex. fields in order of appearance
    [ // add the trailer list
      '-keywords',
      '-annotation',
      '-note',
      '-groups',
      '-timestamp',
      '-files',
      '-file',
      '-url_published_version',
      '-url_online_appendix',
      '-url_main_figures_and_tables',
    ]
  ).reduce((acc, field, idx) => { // assign rankings based on the list order above
    if (field[0] === '-') {
      acc[field.substring(1)] = -(idx + 1)
    }
    else {
      acc[field] = idx + 1
    }
    return acc
  }, {})

  const keys = Object.keys(entry.has).sort((a, b) => {
    const fa = fieldOrder[a]
    const fb = fieldOrder[b]

    if (fa && fb) return Math.abs(fa) - Math.abs(fb) // if they both appear in the list, output them in relative order
    if (fa) return -fa // if only one appears, return that position
    if (fb) return fb
    return a.localeCompare(b) // otherwise, alphabetically
  })
  for (const field of keys) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

</details>

And I get the following export on the test reference:
```
@unpublished{Piketty.etal_2017_CapitalAccumulationPrivatePropertyRising,
  title = {Capital Accumulation, Private Property and Rising Inequality in {{China}}, 1978-2015},
  author = {Piketty, Thomas and Yang, Li and Zucman, Gabriel},
  year = {2017},
  address = {{Cambridge, MA}},
  doi = {10.3386/w23368},
  url = {https://www.nber.org/papers/w23368},
  abstract = {This paper . . .},
  keywords = {Data Sources: Wealth Inequality Trends},
  file = {C\:\\Users\\lukis\\Zotero\\storage\\JIKL8ST4\\Piketty.etal_2017_CapitalAccumulationPrivatePropertyRising.pdf},
  url_published_version = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015-2019},
  url_online_appendix = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015onlineappendix-2018},
  url_main_figures_and_tables = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015mainfiguresandtables-2018}
}
```
This is what I'd like to see.

<details><summary>But if I use the following postscript with a different ordering of the custom fields:</summary>

```
if (Translator.BetterTeX) {
  // output entry fields are sorted on the order they appear here; items with a `-` in front of them will
  // appear in that order at the end, after all fields that are not named in this list. Fields not named
  // here will sort in the middle alphabetically.
  const fieldOrder = [ // the original leader list
    'type',
    'ids',
    'title',
    'shorttitle',
    'booktitle',
    'author',
    'editor',
    'translator',
    'holder',
    'options',
    'date',
    'origdate',
    'year',
    'month',
    'journal',
    'journaltitle',
    'shortjournal',
    'series',
    'edition',
    'volume',
    'number',
    'eprint',
    'eprinttype',
    'primaryclass',
    'pages',
    'publisher',
    'address',
    'institution',
    'location',
    'issn',
    'doi',
    'url',
    'urldate',
  ].concat(
    Object.keys(item.extraFields.tex), // add the tex. fields in order of appearance
    [ // add the trailer list
      '-keywords',
      '-annotation',
      '-note',
      '-groups',
      '-timestamp',
      '-files',
      '-file',
      '-url_online_appendix',
      '-url_published_version',
      '-url_main_figures_and_tables',
    ]
  ).reduce((acc, field, idx) => { // assign rankings based on the list order above
    if (field[0] === '-') {
      acc[field.substring(1)] = -(idx + 1)
    }
    else {
      acc[field] = idx + 1
    }
    return acc
  }, {})

  const keys = Object.keys(entry.has).sort((a, b) => {
    const fa = fieldOrder[a]
    const fb = fieldOrder[b]

    if (fa && fb) return Math.abs(fa) - Math.abs(fb) // if they both appear in the list, output them in relative order
    if (fa) return -fa // if only one appears, return that position
    if (fb) return fb
    return a.localeCompare(b) // otherwise, alphabetically
  })
  for (const field of keys) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

</details>

I get the following export, which just conforms to that ordering, rather than retaining the order of appearance seen in the extra field:

```
@unpublished{Piketty.etal_2017_CapitalAccumulationPrivatePropertyRising,
  title = {Capital Accumulation, Private Property and Rising Inequality in {{China}}, 1978-2015},
  author = {Piketty, Thomas and Yang, Li and Zucman, Gabriel},
  year = {2017},
  address = {{Cambridge, MA}},
  doi = {10.3386/w23368},
  url = {https://www.nber.org/papers/w23368},
  abstract = {This paper . . . },
  keywords = {Data Sources: Wealth Inequality Trends},
  file = {C\:\\Users\\lukis\\Zotero\\storage\\JIKL8ST4\\Piketty.etal_2017_CapitalAccumulationPrivatePropertyRising.pdf},
  url_online_appendix = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015onlineappendix-2018},
  url_published_version = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015-2019},
  url_main_figures_and_tables = {https://bibbase.org/network/publication/piketty-yang-zucman-capitalaccumulationprivatepropertyandrisinginequalityinchina19782015mainfiguresandtables-2018}
}
```
This leads me to believe that I could not list all extra fields in use in this postscript (in whatever order, since the wanted order can change, as discussed), export the entire library at once, and have each entry show its tex.url fields in the order of appearance as seen in that entry.

>>and at the end of the Bib output?
>
>I'm inclined to say "no" here. It's not impossible, but it would be convoluted, and you'd be applying a monkey-patch to a part of BBT that I do not promise to keep stable that way. Such a patch could break without warning.

Ok, that makes sense.

In response to your edit to my last reply:

>not sure why you pasted the script again here verbatim?

I didn't. The script includes the three "url_" fields, as described, same as in the postscripts I've pasted here. I would have highlighted them or bolded or something to make it easier to pick out, but I couldn't figure out how to do that. I'm not used to Github's markdown/styling.

Also, sorry, I forgot to respond to your other comments regarding the support log in my last reply when I meant to. I'll respond here.

I did read the wall of text, as I saw that it said it probably applies to you, so I tried to make sure if that was the case. After reading it, I still thought it didn't. I probably didn't read it closely enough, as reading it now I can see that it does cover my case, when it singles out "enhancement requests".

It could be that the language regarding "issues" in points 1 and 2 confused me, as I'm not submitting a bug but a feature request, and I associate the term with the former. I remember reading those two points and double-checking your [support page](https://retorque.re/zotero-better-bibtex/support/) to see that indeed you had said "If you have any questions on the use of the plugin, please do not hesitate to file a GitHub issue to ask for help.", and that this wasn't just a forum for bug fixes.

I think I:
A) was pressed for time, as this was the last thing I did for my workday before logging off, and didn't expect to do something else at that point once I saw the email a few minutes later, and;
B) did not intuit that logs would be something you need for a feature request, I thought my (hopefully detailed) description of what I wanted to see or know if it was possible would be enough. Hopefully this information is useful to you going forward, I don't know if I have any specific suggestions right now (since you said you were open to them).

**Comment by retorquere** [comment]
> I get the following export, which just conforms to that ordering, rather than retaining the order of appearance seen in the extra field:

That's because the `-<fieldname>` means "put it here at the end". The position hints are processed in order, so if you have

```
url_online_appendix
...
-url_online_appendix
```

the latter takes precedence.

> I didn't. The script includes the three "url_" fields, as described, same as in the postscripts I've pasted here. I would have highlighted them or bolded or something to make it easier to pick out, but I couldn't figure out how to do that. I'm not used to Github's markdown/styling.

Ah I don't think you can do that inside code blocks, but then just pick out the relevant lines, or do something like

```
// CHANGE HAPPENS HERE
'-url_online_appendix',
// ENLIGHTENMENT COMES IN THE NEXT POINT-RELEASE
```

otherwise it's nigh impossible to pick out differences. But sorry that I missed this.

> I don't know if I have any specific suggestions right now (since you said you were open to them).

I am open to them, but that is a separate issue.

I do prefer vague reports over missed reports, but the question for me is if I ask in a follow-up specifically for these, and it is just a few clicks, why do people feel the need to argue that I don't know what I'm talking about? I'm getting so frequent pushback on the support log that it was worth it to create label-gun just so I wouldn't find myself in heated arguments so much of the time. I don't have stats at hand, but label-gun kicks in what feels like the majority of the time. On the forums the Zotero devs will just lock issues for people that refuse to send a log. I have considered having label-gun just close & lock issues if they sit around for a week without getting the requested log. I find it actually no-hyperbole-depressing to have to plead to people to get me the stuff that I know allows me to help them just a tad more efficiently.

I hope you understand that it is massively frustrating to have to explain patiently again and again and again, that yes, I need these logs. Is it impossible to help without them, of course not, but why would I want to when it is so easy to generate them? Without them I'm having to ask for/guess at settings, retype stuff, which is always fun with unicode, etc; I have very limited time, and with the tools I have around the support logs I can do quick 10-minute stints to fetch the data, set up a failing test (which is useful for both enhancements and bugs), and then spend a few minutes tinkering whenever I find them. I probably have 10 changes going on at any given time, and the setup of git, github issues, and my support logs allows me to switch efficiently between them. All between the existing time claims of a family, a fulltime job, and trying to be a drummer. 

I just never thought the support logs would be such a problem. I honestly do not understand why people feel like it is a point that should be argued. If i say it helps me, why isn't that enough in and of itself? Why begrudge me that efficiency?

**Comment by lukisikul** [comment]
>That's because the -<fieldname> means "put it here at the end". The position hints are processed in order

Sorry, but I'm finding myself quite confused as to how this answers my question, and how the postscript can be used to do what I describe. your comment in the postscript says to put the tex fields there, where the fields all start with a hyphen, so that's where I put them. But if the position hints are processed in order, how is it that you can export the library and have "all `tex.` fields of the item currently being exported in the order they appear on the item currently being exported. For each individual item."? I don't see how this is the case, which is why I gave the examples in my last reply. 

Re: highlighting code changes with comments, sure that makes sense.

Re: the logs, I'm not trying to argue with you. You said you were open to suggestions, I was just trying to provide what my thought process may have been in an effort to help, not excuse my actions or argue with you that I was right to not provide a log.

**Comment by retorquere** [comment]
Ah, OK. The way they're added in the postscript I offered adds them to the leader-list, not the trailer-list, because the `tex.` keys do not have the `-`. It might look that way because of the indentation, but if you wanted them to be part of the trailer-list, they would go in the same spot but would instead look like

```
Object.keys(item.extraFields.tex).map(field => '-' + field)
```

If that's still not what you want, I think we should just forget what's above and restart with your request.

The diatribe about the logs wasn't intended to single you out. It was more a lament that I have to do this so often. It's a lingchi problem, and every now and then that spills over.

**Comment by retorquere** [comment]
Forget the earlier postscript -- see if this does what you want:

```
if (Translator.BetterTeX) {
  const tex_fields = Object.keys(item.extraFields.tex).filter(field => entry.has[field])
  let tex_field = 0
  const field_order = Object.keys(entry.has).map(field => tex_fields.includes(field) ? tex_fields[tex_field++] : field)
  for (const field of field_order) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

**Comment by lukisikul** [comment]
Yes! This seems to work. I've tested it on a few different references and haven't had an issue yet. Thank you so much!

The only thing that would make it perfect would be ensuring these fields were always the last ones in the bib export, but assuming the following still stands with this new code:

>>and at the end of the Bib output?
>
>I'm inclined to say "no" here. It's not impossible, but it would be convoluted, and you'd be applying a monkey-patch to a part of BBT that I do not promise to keep stable that way. Such a patch could break without warning.

Then that's fine.

Thank you for your work on this, it is greatly appreciated.

**Comment by retorquere** [comment]
Oh, *that* is what you wanted.

```
if (Translator.BetterTeX) {
  const tex_fields = Object.keys(item.extraFields.tex).filter(field => entry.has[field])
  const field_order = Object.keys(entry.has).filter(field => !tex_fields.includes(field)).concat(tex_fields)
  for (const field of field_order) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

**Comment by lukisikul** [comment]
Apologies for the late response, but yes, thank you this seems to work perfectly. Sorry if I hadn't been clear on that before.

Thank you so much for your help. I'll close the issue now.

**Comment by lukisikul** [comment]
Hi,

I've found some references that don't create the expected output, and I'm not sure why. I have double-checked I am using the same postscript as before, the last one pasted in this thread by you, and the same example reference I've used before in this thread is still working fine. I've created a support log for an offending reference, log ID _XSBZ3D5N-refs-euc_.

The reference has 3 tex fields, one labelled for the working paper, for the online appendix, and then the replication data. I would expect it to export those fields in that order as they are written, but it lists the replication data before the online appendix. See below:

```
@article{Jakobsen.etal_2020_WealthTaxationWealthAccumulationTheory,
  title = {Wealth Taxation and Wealth Accumulation: Theory and Evidence from {{Denmark}}},
  author = {Jakobsen, Katrine and Jakobsen, Kristian and Kleven, Henrik and Zucman, Gabriel},
  year = {2020},
  month = feb,
  journal = {The Quarterly Journal of Economics},
  volume = {135},
  number = {1},
  pages = {329--388},
  doi = {10.1093/qje/qjz032},
  url = {https://doi.org/10.1093/qje/qjz032},
  abstract = {Using administrative wealth records from Denmark [. . .]},
  keywords = {Data Sources: Wealth Inequality Trends,Wealth Taxation},
  file = {C\:\\Users\\lukis\\Zotero\\storage\\SCQAW5YY\\Jakobsen.etal_2020_WealthTaxationWealthAccumulationTheory.pdf},
  url_working_paper = {https://bibbase.org/network/publication/jakobsen-jakobsen-kleven-zucman-wealthtaxationandwealthaccumulationtheoryandevidencefromdenmark-2019},
  url_replication_data = {https://bibbase.org/network/publication/jakobsen-jakobsen-kleven-zucman-replicationdataforwealthtaxationandwealthaccumulationtheoryandevidencefromdenmark-2019},
  url_online_appendix = {https://bibbase.org/network/publication/jakobsen-jakobsen-kleven-zucman-onlineappendixforwealthtaxationandwealthaccumulationtheoryandevidencefromdenmark-2020}
}
```

This is the first reference I've observed this happen in. I'm not sure what the issue may be.

**Comment by retorquere** [comment]
I have this reproducible but I don't yet know what causes it.

**Comment by retorquere** [comment]
A new build will drop here that will allow this postscript to work:

```
if (Translator.BetterTeX) {
  const tex_fields = Object.entries(item.extraFields.tex).sort((a, b) => a[1].line - b[1].line).map(field => field[0]).filter(field => entry.has[field])
  const field_order = Object.keys(entry.has).filter(field => !tex_fields.includes(field)).concat(tex_fields)
  for (const field of field_order) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

the reordering of fields used to rely on a technicality that requesting the keys of an object returns them in the order they were added -- AFAIK that is supposed to always work in javascript, and if it wouldn't the delete-add trick wouldn't work, but for some reason it is disturbed somewhere before the fields are written out. This build just remembers the line numbers and then the postscript sorts on that.

**Comment by lukisikul** [comment]
Apologies for the late response, but I have made sure to update my BBT install to the latest version and the new script you posted does seem to fix the issue on the test reference. Thank you very much, again. I'll close the issue again.
