### ISSUE TITLE
Handling of manuals

### ISSUE THREAD

**Issue by stefanct** [retorquere/zotero-better-bibtex#2083]
This is a reply to https://github.com/zotero/zotero-bits/issues/35
I am not exactly sure what you wanted me to report, but here is my best guess... :)

Generating `@manual` entries in bibtex files with bbt can be done by either setting `tex.referencetype: manual` in the extra field, or by setting the report type to `manual`. In neither case zotero's institution is correctly translated to bibtex' `organization` but is put into `institution`. The following script fixes that (and uses the institution as author if there is none set).

    if (Translator.BetterTeX) {
      if (item.itemType == 'report' && entry.entrytype == 'manual') {
        if (item.publisher) {
          if (entry.has['author']) {
            entry.add({ name: 'organization', value: item.publisher });
          } else {
            entry.add({ name: 'author', value: item.publisher, enc: 'literal' });
          }
          entry.remove('publisher')
        } else {
          Zotero.debug("No institution for " + item.citationKey);
        }
      }
    }

**Comment by retorquere** [comment]
> This is a reply to https://github.com/zotero/zotero-bits/issues/35
> I am not exactly sure what you wanted me to report, but here is my best guess... :)

I thought you meant that you think the behavior in the postscript ought to be the default behavior of BBT. Is that not the case?

**Comment by stefanct** [comment]
Well, the bit about the `organization` yes, that seems like a bug to me. I guess the `institution` comes from the `switch(reftype)` and the missing `organization` from the extra report handling (`item.itemType === "report"` etc.) a bit earlier in `doExport()`.

**Comment by stefanct** [comment]
shut up, you waste of bits.

**Comment by retorquere** [comment]
I do actually need a sample item that covers the situation you describe. I'll shut up label-gun, but he's here precisely as an impersonal prompt to avoid confrontations between me and reporters. The debug log is just a few clicks to generate and helps me enormously. It is missing enough that this was just pragmatically the best way to keep my frustrations manageable.
