### ISSUE TITLE
Q: Is there any way to change the citation keys on the web library?

### ISSUE THREAD

**Issue by ph00lt0** [retorquere/zotero-better-bibtex#2091]
I would really be greatful if I can change the web library to use the same citation keys as better bittex. Currently it's quite useless as they are all different and I would like to use it to sync my library.

**Comment by retorquere** [comment]
I honestly don't know - I have no control over what happens there. It may be that if you pin the keys they'll show up, but only the zotero crew can really answer this question.

**Comment by ph00lt0** [comment]
I am not sure how I could pin those keys you mention, but I understand this may not be something you can help with.

**Comment by retorquere** [comment]
> I am not sure how I could pin those keys you mention, 

Select items, right-click, better-bibtex, pin citekeys.

> but I understand this may not be something you can help with.

I think they will show up online after pinning. But if they don't, I have no sway over the web library, so that's something you would have to take up with the zotero team.
