### ISSUE TITLE
Feature Request: Export attachment annotations

### ISSUE THREAD

**Issue by mgmeyers** [retorquere/zotero-better-bibtex#2092]
Log ID: WUJY6J7F-refs-euc

The new PDF reader in Zotero 6 stores annotations in the Zotero database, and it would be useful to be able to export these annotations some how.

I could see two things being particularly useful here, though there may be other scenarios I'm not thinking of:

1. Similar to the json-rpc `item.notes(citekeys)` command, implementing a `item.annotations(citekeys)` command
2. Include annotations when using the `BetterBibTeX JSON` translator

On Zotero's end, attachments items now have a `getAnnotations` method that may be useful:

https://github.com/zotero/zotero/blob/174f1aaddebbc3adc237595e3bea7f7c45196129/chrome/content/zotero/xpcom/data/item.js#L3922-L3953

**Comment by retorquere** [comment]
It doesn't look like annotations are offered to translators.

WRT json-rpc, you mean `item.annotations` would get all annotations divorced from the attachment that they belong to?

**Comment by mgmeyers** [comment]
> It doesn't look like annotations are offered to translators.

Ah, dang, that's unfortunate.

> WRT json-rpc, you mean `item.annotations` would get all annotations divorced from the attachment that they belong to?

Hmm 🤔 , good question. I guess it would offer more flexibility to return something like an array of:

```
{
  "open": "zotero://open-pdf/library/items/N5XIYNYX",
  "path": "mypdf.pdf",
  "annotations": [...annotations...]
}
```

In this case, I guess another option then would be to include annotations in the output of `item.attachments` since the output is similar?

**Comment by retorquere** [comment]
That seems like a better approach.

**Comment by retorquere** [comment]
This needs the same change in zotero as #2126, so I'll be tracking the work for this on that issue -- I've requested the change from zotero, no idea when it will happen.
