### ISSUE TITLE
Configurable journal abbreviation for citekey

### ISSUE THREAD

**Issue by pou2** [retorquere/zotero-better-bibtex#2097]
Essentially, this request has previously been discussed (https://github.com/retorquere/zotero-better-bibtex/issues/1470). The resolution to the issue was the creation of a plugin (https://github.com/retorquere/zotero-clear-journal-abbrev/). My Zotero installation automatically upgraded from version 5 to 6 (6.0.4), and Zotero says this plugin is incompatible with Zotero 6.0.4. I recognize I can downgrade if need be, but since two years have passed and the plugin has stopped working, I thought I would broach the subject again and see what you thought (perhaps implementation of the proposed enhancement below will be more interesting to you than addressing plugin incompatibility).

Briefly, Journal_Abbr metadata is frequently bad (e.g., sometimes publishers set this metadata to be identical to the unabbreviated journal title in the Publication field) and the BBT `[journal]` function will preferentially use the value from the Journal_Abbr field if it is provided. If the Journal_Abbr field is blank, `[journal]` will return the an abbreviated form of the Publication field (generated by passing it through the Zotero wordprocessor abbreviation filter, provided that 'automatic journal abbreviation’ is enabled in the BBT settings). A new function, such as `[journal.full]`, which simply ignored the Journal_Abbr field if set, would be wonderful. That way, users could opt to exclusively use the value obtained by the Zotero abbreviation filter (currently this is not possible).

You had previously seemed on the cusp of implementing such a function, but I think I got carried away obsessing over tiny irrelevant details (in an attempt to be helpful/engaged) and maybe ended up dissuading you in the end!

In any case, as always, thank you very much for all your work, and I respect whatever decision you make and understand that your time is very precious.

---

Support log ID (based on an arbitrarily selected library item, since the issue is unrelated to my library): B9DAEHWA-refs-euc

**Comment by retorquere** [comment]
Oh I'm OK with journal.full.

**Comment by pou2** [comment]
That would be fantastic; thank you!!

**Comment by retorquere** [comment]
Wait, this will get you exactly the same as `[PublicationTitle]`.

**Comment by pou2** [comment]
Let me try to do a better job of explaining.

Basically, I want the value of `[PublicationTitle]`, except passed through the Zotero wordprocessor filter for automatic journal abbreviation. `[journal]` provides the desired functionality provided that the Journal_Abbr field is empty, but if Journal_Abbr is populated then its value is given as output. What I want is something like `[journal]`, except that outputs the Zotero wordprocessor filter auto-abbreviation value at all times, even if something is already present in Journal_Abbr.

Here are some examples to show you what I mean. Imagine a reference with Publication_Title set to "Biomedical Research" and Journal_Abbr set to be empty.

`[PublicationTitle]` => BiomedicalResearch
`[JournalAbbreviation]` => (nothing)
`[journal]` => Biomed.Res.
`[journal.full]` => Biomed.Res.

Now imagine a reference with Publication_Title set to "Biomedical Research" and Journal_Abbr set to "Biomedical Research The Journal".
`[PublicationTitle]` => BiomedicalResearch
`[JournalAbbreviation]` => BiomedicalResearchTheJournal
`[journal]` => BiomedicalResearchTheJournal
`[journal.full]` => Biomed.Res.

I don't care what you choose to call the function; I'm fine with `[journal.full]` as a name.

Hope this is helpful. Thanks again!

**Comment by retorquere** [comment]
I think I finally get what you want. I don't think `journal.full` is a good name for this, but I've made the abbreviator configurable. With build 2299, `B9DAEHWA-refs-euc` with `[auth:lower][shorttitle3_3].[journal=auto][year]` gets you `duarteRoleOrganicSolvent.J.Supercrit.Fluids2012`.

**Comment by pou2** [comment]
Yes yes yes! Thank you! I tested it and it works.

**Comment by retorquere** [comment]
Super. The parameter is a bit weird but that will read better once I have the pattern formatter overhaul done.
