### ISSUE TITLE
Failed to update .bib file in background

### ISSUE THREAD

**Issue by kgfeuerherm** [retorquere/zotero-better-bibtex#2098]
ID: BQPSMP5A-euc (there was a previous ID which I lost while trying to get here due to not being able to cut and paste from the Zotero info... sorry)

I cannot unfortunately tell you exactly all the details. A box popped up begging me to file a report, unfortunately it vanished as well before I was able to get everything sorted out. My apologies.

Essentially, I was making changes to a Zotero entry (adding an author to an artwork) and when I reran my TeX compilation (in TeXShop) nothing changed, no matter what I did. Somewhere along the line (I *believe* after closing and reopening Zotero to force the plugin etc. to read the new information) I got a message to the effect that background update of the .bib file had failed after 5 attempts.

That's all I can tell you, I'm afraid, and as a former programmer I appreciate that's not terribly helpful; however I figure it at leasts brings awareness of the issue if nothing else, i.e., it happened....

FWIW

**Comment by retorquere** [comment]
Can you try build 2297?

**Comment by kgfeuerherm** [comment]
Happy to, but this is the first issue I've encountered in years, so unlikely the problem will reoccur....

**Comment by retorquere** [comment]
You're using Firefox. Zotero and Firefox share their plugin architecture, so Firefox thinks the xpi is intended for itself, concludes it can't actually install it, and unhelpfully reports it as corrupt. If you right click and save you can install it in Zotero.

**Comment by kgfeuerherm** [comment]
Downloaded it using Chrome no problem, installed.

Unfortunately, yesterday was my last real TeX/Zotero development day (end of academic term) but I'll try to poke around with it and see whether anything comes up. I'll report back if I find anything I expect to be of value to you.
