### ISSUE TITLE
Can't install BBT on the Zotero-beta version 6.0-beta.1+8c846468f on Linux

### ISSUE THREAD

**Issue by baogiadoan** [retorquere/zotero-better-bibtex#2099]
Hi, I can't install BBT, the pop-up message: 

`The add-on "Better BibTex for Zotero" could not be installed. It may be incompatible with this version of Zotero.`

Linux Manjaro
Zotero-beta version 6.0-beta.1+8c846468f
BBT version: 6.4.2

**Comment by retorquere** [comment]
Can you try build 2307?

**Comment by andersjohansson** [comment]
That doesn’t seem to help for my case #2093 either:
```javascript
const versionCompare = Components.classes['@mozilla.org/xpcom/version-comparator;1'].getService(Components.interfaces.nsIVersionComparator);

versionCompare.compare("6.0.SOURCE.c12fba6da","6") /* Returns -1 */

versionCompare.compare("6.0-beta.1+8c846468f","6") /* Returns -1 */
```
Time for bringing it up with the Zotero devs?

**Comment by retorquere** [comment]
I guess. This is not the kind of thing that would be easy to resolve for them. I'm still looking for a pragmatic solution to this issue that doesn't lie about what versions it supports.

**Comment by baogiadoan** [comment]
@retorquere I'm happy to downgrade to a lower version of Zotero Beta, may I know which is the last known version that still supports and works well with BBT, I tried to a few recent version of Zotero Beta but without success

**Comment by retorquere** [comment]
Downgrading won't help. BBT reports it supports 6+, but that makes zotero think the 6 beta isn't in range. I'll get you a build that works around that.

**Comment by baogiadoan** [comment]
thanks @retorquere I tried the build 2314 and I can install it now
