### ISSUE TITLE
Is it possible to customize the order of fields in each entry of exported BibTeX files?

### ISSUE THREAD

**Issue by gaochenyi** [retorquere/zotero-better-bibtex#2111]
Currently, BBT outputs files like this:

```bibtex
@article{key
  title = {Title},
  author = {Author},
  year = {2003},
}
```

I would like to have files like this:

```bibtex
@COMMENT{lexical order}
@article{key
  author = {Author},
  title = {Title},
  year = {2003},
}
```

Does BBT allow customization of the field order during serialization?

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/exporting/scripting/#custom-field-order
