### ISSUE TITLE
Req: dark mode citekey field

### ISSUE THREAD

**Issue by glocalglocal** [retorquere/zotero-better-bibtex#2117]
Log ID: 7NJTUZ4T-euc

It would be good if we could edit the BibTeX key directly in the right pane of Zotero by simply clicking on the field, in the same way we can edit every other field.

At the moment, to change the key we have to do this: 
- right click
- scan the menu to decide on the right submenu
- scan the submenu to decide on the right option 
- click on 'Change BibTeX key...'

This doesn't sound like a lot until you have to do it several times. The alternative would involve intuitively clicking on the field you are looking at already. Frictionless and more consistent.

**Comment by retorquere** [comment]
The item pane is very resistant to adding editable fields. That I can display the key there already took significant effort.

**Comment by glocalglocal** [comment]
That's a shame. Speaking of that field, I added [Zotero-Dark-Theme](https://github.com/Rosmaninho/Zotero-Dark-Theme) and the Citation Key is the only field that doesn't change to white-on-grey: 

![image](https://user-images.githubusercontent.com/16408198/163825730-cdfc6177-92bd-48ef-ae2e-2f41a01b64d7.png)

Not a huge problem of course but I was wondering if there anything that BBT or Zotero-Dark-Theme could do.

**Comment by qqobb** [comment]
@glocalglocal: A future update of Zotero should provide a proper Citation Key field. The new Preprint item type has it already. At the moment, pinning BBT's citation key will write it to the item's Extra field, where it can be edited. In general, you'd want to set up your citation key format such that only a small fraction needs to be changed manually.

Here are some related options that might help:

- With the [autoPinDelay option](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay), you can have the citation keys pinned automatically.

- You could use the ["Apps/Menu" key](https://en.wikipedia.org/wiki/Menu_key) or Shift+F10 as an alternative to right-clicking items. When the item's context menu is being shown, press "B" on your keyboard and then "Enter" to select BBT's "Change BibTeX key..." function.

- The [Zutilo add-on](https://github.com/wshanks/Zutilo#readme) provides some keyboard shortcuts for BBT. You could set a shortcut for "Pin BibTeX key".  We could also add a new Zutilo shortcut for "Change BibTeX key...".

**Comment by glocalglocal** [comment]
Hopefully, Zotero's key field will resolve this although IME it can take ages between releases. I try not to overcustomise because it almost always leads to higher maintenance later (eg when something breaks). I only change keys manually to replace long organisation names with something less cumbersome. Thanks for the tips.

**Comment by retorquere** [comment]
Wrt key editing I also want to wait to see what behavior Zotero itself wants to implement. The most plausible behavior seems to me to be what auto-pin does now, combined with with an option for manual refresh. I don't expect the citekey to come soon for all items, but one item already has it, so it's clearly being worked on.

**Comment by glocalglocal** [comment]
One problem with Extra I see is that it's increasingly becoming a dumping ground for all sorts of things (three add-ons and a referencing style already here).

**Comment by retorquere** [comment]
That is something you'll have to take up with the Zotero team. The `extra` field is consistently named the appropriate place for plugin data that is meant to sync.

WRT dark mode, I probably need to add a class to the citekey field to have it update, but I don't know what exactly. If you know what it is I'll gladly add it, but I know next to nothing about CSS.

**Comment by qqobb** [comment]
I'm planning to add a Zutilo shortcut for BBT's "Change BibTeX key...". See https://github.com/wshanks/Zutilo/issues/224.

**Comment by glocalglocal** [comment]
> WRT dark mode, I probably need to add a class to the citekey field to have it update, but I don't know what exactly. If you know what it is I'll gladly add it, but I know next to nothing about CSS.

There may be some help coming [here](https://github.com/Rosmaninho/Zotero-Dark-Theme/issues/42#issuecomment-1108197607).

**Comment by retorquere** [comment]
We'll have to wait for that as I have no burning desire to dive into their CSS.

**Comment by retorquere** [comment]
Looks like @Rosmaninho solved it on their end.
