### ISSUE TITLE
Zotero export item format issue

### ISSUE THREAD

**Issue by DanteSung** [retorquere/zotero-better-bibtex#2119]
I'm not sure if this question is within the scope of better Bibtex but please give it a look.

I've been using Zotero and bbt to manage a `.bib` file for years. My Zotero setting is `Preferences-Export-Item Format-Better BibTex`.

Recently I just found that `Quick Copy` can be helpful when writing latex and I switched the `Export-Item Format` setting to `Better BibTex Quick-Copy: \cite{citation keys}`.

Here comes the problem: although using `quick copy` to insert citation keys is super convenient, I cannot manage to `.bib` file anymore --- I have to switch back to `Export-Item Format-Better BibTex` to add new bib items into my `.bib` file and switching back to `quick copy` to add citation keys, which is really annoying.

Is there any workaround to use quick copy and add bib items at the same time?

Thank you in advance.

**Comment by DanteSung** [comment]
The debug id is `Y3RY5WFS-apse`.

**Comment by retorquere** [comment]
You might want to use [auto-export](https://retorque.re/zotero-better-bibtex/exporting/auto/)

You have BBT caching off BTW, that will affect performance.

**Comment by DanteSung** [comment]
For some reason, my bib file is forked from another place which only overlaps with my Zotero library  for about 20%. And all of my papers would share the same bib file.

Auto-export seems to work better to manage different auto-generated bib files as you mentioned in [auto-export](https://retorque.re/zotero-better-bibtex/exporting/auto/).
>You can set up separate exports for separate papers for example if you have set up a collection for each.

One way I can think of is to import the bib file I'm currently using into Zotero as a separate collection, but that would result in a lot overlapped items which I'm not sure how to deal with.

Is there any other workaround to separate `Better BibTex ` and `Better BibTex Quick-Copy: \cite{citation keys}`?

Thank you!

Ps.: could you pls lemme know where to turn BBT caching on?

**Comment by retorquere** [comment]
> For some reason, my bib file is forked from another place which only overlaps with my Zotero library for about 20%. And all of my papers would share the same bib file.

That's not a scenario I can support. There's not enough information in the bib file to know what to update. It'd also be a performance and qualitynightmare, as BBT would have to parse and reconstruct the bib file frequently and perfectly.

> Auto-export seems to work better to manage different auto-generated bib files as you mentioned in [auto-export](https://retorque.re/zotero-better-bibtex/exporting/auto/).

Yep. Why not split off that 20% to a separate file and have multiple files in your `\bibliography` call?

> One way I can think of is to import the bib file I'm currently using into Zotero as a separate collection, but that would result in a lot overlapped items which I'm not sure how to deal with.

You'd get a lot of duplicates very fast. I'd not recommend doing this.

> Is there any other workaround to separate `Better BibTex ` and `Better BibTex Quick-Copy: \cite{citation keys}`?

That is a Zotero question. BBT just provides the translators, Zotero calls them. Maybe that Zutilo has a shortcut key to do different exports?

> Ps.: could you pls lemme know where to turn BBT caching on?

prefs - BBT - export - misc - enable caching

**Comment by DanteSung** [comment]
Thank you for your reply!

I've solved my problem by using [Zutilo](https://github.com/wshanks/Zutilo).

There's a function in Zutilo called `Quick Copy Items` which does exactly what I wanted.

For those who find this page on Google, please follow the guide of `Quick Copy Items` from the [COMMANDS page of Zutilo](https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md).
