### ISSUE TITLE
Error with replace filters in citation keys

### ISSUE THREAD

**Issue by ByronAhn** [retorquere/zotero-better-bibtex#2122]
When specifying a citation key format, the ":replace" filter seems to not be recognized. When I add a replace filter, the box turns orange (as if the string was invalid) and my addition isn't saved.

- Here's the string that works:
    - [authEtAl][shortyear]
- And here's one that doesn't work (I lifted the replace filter directly from [the documentation on this page](https://retorque.re/zotero-better-bibtex/citing/)):
    - [authEtAl:replace('.etal','&etal')][shortyear]

support log ID: 2AA7BAWB-euc

**Comment by retorquere** [comment]
I'm reworking the pattern documentation, which is partly generated, so parts updated too early. The generated function/filter descriptions are for the new citation key format, if you type `[authEtAl][shortyear]` the box under it shows the new format as `authEtAl + shortyear`, and replace would be `authEtAl.replace('.etal','&etal') + shortyear`. During the transition period you can force the new format by prefixing the pattern with `'' + `. At some point the old format will just be converted to the new format and that's all you'll see/be able to enter.

**Comment by ByronAhn** [comment]
got it, thank you for the super quick response!
