### ISSUE TITLE
Feature Request: adding another shortcut for BBT Sentence-case

### ISSUE THREAD

**Issue by DanteSung** [retorquere/zotero-better-bibtex#2123]
I read issue https://github.com/retorquere/zotero-better-bibtex/issues/754 and also https://github.com/wshanks/Zutilo/issues/72 and found out that Zutilo could call `Zotero.BetterBibTeX.KeyManager.pin('selected')` (pin key for selected references) to call BBT pin function.

Can you please also lemme know what to call for BBT Sentence-case? Currently I have to Right Click-BBT context menu-BBT Sentence case.

Thanks.

Debug ID: 8468RGR3-apse

**Comment by DanteSung** [comment]
Downloaded and installed the test build, but found a bug (not sure if it is a bug) for BBT-sentence case.

I remember we discussed in https://github.com/retorquere/zotero-better-bibtex/issues/1607#issuecomment-671533889, where you mentioned that 
>it lowercases everything that:  1. Isn't at a sentence start; 2. Is of the shape `<Uppercase><Lowercase>*`

I'm not sure whether the title has to meet BOTH conditions or any of them.

What BBT did before, as far as I remember, was changing from 
- Originally saved from web:  `Is FFT Fast Enough for Beyond 5g Communications?`

to
-  BBT-sentence case:`Is FFT Fast Enough for Beyond 5g Communications?` (`FFT` meets condition 1 but doesn't meet condition 2, so it should not be lowercased)

However, the BBT-sentence case now provides:
- `Is fft fast enough for beyond 5g communications?` which is exactly the same as the default sentence case, lowercasing everything except the sentence start.

FYI:

- Zotero default title case: `Is Fft Fast Enough for Beyond 5g Communications?`
- Zotero default sentence case: `Is fft fast enough for beyond 5g communications?`

Can you please look into it?

Debug ID: 72XTXMTJ-apse

**Comment by retorquere** [comment]
Please join #2078 for a discussion of sentence-casing. #2123 is only for discussing the Zutilo integration point. With build 2447, Zutilo can call `Zotero.BetterBibTeX.Text.sentenceCase(title, htmlSupport)` (I would suggest setting htmlSupport to `true`) to sentencecase a string.

**Comment by DanteSung** [comment]
Could you explain more about this?
> setting htmlSupport to true

Do you mean call sentence-casing as 
```
keys.categories.BBTSentenceCase = 'bbt'
    keys.shortcuts.BBTSentenceCase = function(win) {
        win.Zotero.BetterBibTeX.ready.then(function() {
            win.Zotero.BetterBibTeX.Text.sentenceCase(title, true)})
    }
```

Or finding `htmlSupport ` somewhere and set it to `true`?

**Comment by DanteSung** [comment]
Also opened an issue in https://github.com/wshanks/Zutilo/issues/224#issue-1210731590

**Comment by retorquere** [comment]
> Do you mean call sentence-casing as
> 
> ```
> keys.categories.BBTSentenceCase = 'bbt'
>     keys.shortcuts.BBTSentenceCase = function(win) {
>         win.Zotero.BetterBibTeX.ready.then(function() {
>             win.Zotero.BetterBibTeX.Text.sentenceCase(title, true)})
>     }
> ```
> 
> Or finding `htmlSupport ` somewhere and set it to `true`?

No, the former, just always have it `true` for titles. But simply calling `win.Zotero.BetterBibTeX.Text.sentenceCase(title, true)` won't do anything, Zutilo must retrieve an item based on some criteria, set the modified title, and save the item. That lives [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/ItemPane.ts#L4) for BBT, with the criteria being "is currently displayed", but I don't know what the context is for the hotkey you are setting up.

**Comment by DanteSung** [comment]
Already posted the request in Zutlio. I have no idea how Zutlio would call BBT tbh, just found the bbt-related snippet in the source code of Zutlio and thought adding it would work.

>I don't know what the context is for the hotkey you are setting up.

I was just thinking adding this hotkey function without assigning it. You know, just let users to decide.

**Comment by retorquere** [comment]
Alright. So, does that mean you have what you need? Is there something else we ought to discuss under this issue, or can it be closed?

**Comment by DanteSung** [comment]
I'll wait to see if there're any feedbacks from Zutilo side since the function call is exposed.

Is `Zotero.BetterBibTeX.Text.sentenceCase(title, htmlSupport)` only exposed on this build? If this issue is closed, can someone still download [test build 6.5.1.2447](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.5.1.2447.xpi) ("expose sentencecase")?

**Comment by retorquere** [comment]
> Is `Zotero.BetterBibTeX.Text.sentenceCase(title, htmlSupport)` only exposed on this build? 

Yes, for now.

> If this issue is closed, can someone still download [test build 6.5.1.2447](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.5.1.2447.xpi) ("expose sentencecase")?

Yes, for about a week.

**Comment by qqobb** [comment]
Ok, BBT already had this function: `Zotero.BetterBibTeX.ZoteroPane.sentenceCase();`. It's working in the "Run JavaScript" tool.
