### ISSUE TITLE
Using the new citekey syntax

### ISSUE THREAD

**Issue by moaschulz** [retorquere/zotero-better-bibtex#2128]
**Support log ID: S3FG3NDU-refs-euc**

I was taken a bit by surprise by the change to a new syntax for citekey generation patterns. Unfortunately, the automatic translation does not deliver the same results as the previous version.

In the old syntax, I used:

```
[authEtAl]-[year]-[shortTitle:capitalize:nopunctordash:select=1,9:>0] | 
[authEtAl][>0]-[year]-[Title:capitalize:nopunctordash:select=1,9] | 
[year]-[Title:capitalize:nopunctordash:select=1,9]
```

Upon the latest update, BBT automatically translated this to:

```
'' + authEtAl+'-'+year+'-'+shorttitle.capitalize.nopunctordash.select(1,9).len('>', 0) | 
authEtAl+len('>',0)+'-'+year+'-'+Title.capitalize.nopunctordash.select(1,9) | 
year+'-'+Title.capitalize.nopunctordash.select(1,9)
```

Unfortunately, this swapped `shortTitle`, which uses the "Short Title" item field for `shorttitle`, which is a function drawing on the "Title" field. So I corrected this and tried to use:

```
authEtAl + '-' + year + '-' + shortTitle.capitalize.nopunctordash.len('>', 0) | 
authEtAl.len('>', 0) + '-' + year + '-' + Title.capitalize.nopunctordash.select(1,9) | 
year + '-' + Title.capitalize.nopunctordash.select(1,9)
```

This returned an error (orange shading in preferences), which disappeared after I reintroduced the initial `'' + ` - although I don't quite get what that would be doing and couldn't find any [documentation](https://retorque.re/zotero-better-bibtex/citing/) on it.

```
'' + authEtAl+'-'+year+'-'+shortTitle.capitalize.nopunctordash.len('>', 0) | 
authEtAl+len('>',0)+'-'+year+'-'+Title.capitalize.nopunctordash.select(1,9) | 
year+'-'+Title.capitalize.nopunctordash.select(1,9)
```

This no longer gives an error, but it does *not* generate the same citekeys as the old pattern. For example:

Title: The Problem of Presentations: How It is That One Object is Perceptually Given in Multiple Ways
Author: Werner, Konrad
Year: 2022
Short Title: The Problem of Presentations

Old citekey: `Werner-2022-TheProblemOfPresentations`
New citekey: `Werner-2022-ProblemPresentationsHow`

So apparently, it is no longer possible to use the Short Title field and `shortTitle` is now taken as `shorttitle`? That would be a pity, working with custom short titles was really handy for me.

**Comment by retorquere** [comment]
I had forgotten to set the default to the old parser 😞 . A new build will drop here soon that is opt-in for the new parser, and if that works for you, that will go out as a new release. That build will use the old parser if the pattern starts with `[`.

Yeah, sorry about the change in the formatter, but it is a necessary change, the old parser was getting pretty crufty, and the new parser will make things more flexible. I have no way to communicate such changes to BBT users unfortunately.

> Unfortunately, this swapped `shortTitle`, which uses the "Short Title" item field for `shorttitle`, which is a function drawing on the "Title" field. So I corrected this and tried to use:

That must have been a bug in the old parser though. All "direct field access" was triggered by a leading capital, so to get the `Short Title` field I would have expected to see `ShortTitle` instead of `shortTitle` (see [this table](https://retorque.re/zotero-better-bibtex/citing/#direct-access-to-unprocessed-fields), which hasn't changed for the new parser).

**Comment by moaschulz** [comment]
Thanks for your prompt reply! It goes without saying that I much appreciate your continuous work on BBT 🙏 

> That must have been a bug in the old parser though. All "direct field access" was triggered by a leading capital, so to get the Short Title field I would have expected to see ShortTitle instead of shortTitle (see [this table](https://retorque.re/zotero-better-bibtex/citing/#direct-access-to-unprocessed-fields), which hasn't changed for the new parser).

Ah! Turns out I never actually understood that that is what this table is supposed to be... I found `shortTitle` just by trial and error after desperately looking for it in the functions list. For slow noobs like me, maybe an extra sentence could do? Perhaps like: "The above functions all retrieve information stored in the item's fields and process it in some way. Besides this, you can just as well call fiel contents without any processing. To access Zotero fields, refer to them as given in the table below:"

**Comment by retorquere** [comment]
> The above functions all retrieve information stored in the item's fields and process it in some way. Besides this, you can just as well call field contents without any processing. To access Zotero fields, refer to them as given in the table below:

Great point -- tests are running on a fix for a problem I found through looking into this case, site update & fix will be released when they pass.

**Comment by mlkvikp** [comment]
> I had forgotten to set the default to the old parser disappointed . A new build will drop here soon that is opt-in for the new parser, and if that works for you, that will go out as a new release. That build will use the old parser if the pattern starts with `[`.
> 
> Yeah, sorry about the change in the formatter, but it is a necessary change, the old parser was getting pretty crufty, and the new parser will make things more flexible. I have no way to communicate such changes to BBT users unfortunately.
> 
> > Unfortunately, this swapped `shortTitle`, which uses the "Short Title" item field for `shorttitle`, which is a function drawing on the "Title" field. So I corrected this and tried to use:
> 
> That must have been a bug in the old parser though. All "direct field access" was triggered by a leading capital, so to get the `Short Title` field I would have expected to see `ShortTitle` instead of `shortTitle` (see [this table](https://retorque.re/zotero-better-bibtex/citing/#direct-access-to-unprocessed-fields), which hasn't changed for the new parser).

Hi, do I understand it correclty that a new release will be able to read a command from the old parser just fine? I have a rather complex citekey generation pattern (see below) that I would ideally just want to keep..

[authors+/:replace=\[^/\]+,,regex:longer=2:discard] [authors1+/:replace=/.*,,regex:postfix=_et_al] : [year] | [authors3+/]:[year]

**Comment by retorquere** [comment]
The strategy is that all existing patterns should work and transfer without loss to the new format. I'm not at home right now, but any valid old pattern you have should work exactly the same.

**Comment by retorquere** [comment]
But that failed for this pattern. A new build will drop here in 10 minutes which will support

```
[authors+/:replace=\[^/\]+,,regex:longer=2:discard] [authors1+/:replace=/.*,,regex:postfix=_et_al] : [year] | [authors3+/]:[year]
```

note that I had to escape the brackets in the regex -- I am going to assume this worked at some point without the escapes but I have no idea how, since brackets are always special in the old syntax. 

The new syntax has a new feature where you can say

```
authors(n=1,max=2,etal=_et_al) + year.prefix(':') | authors(joiner='/')  + year.prefix(':')
```
where the first term means "when there are more than 2 authors, skip to the next pattern, but if not, give me one author, add `_et_al` if there is more then one". I think that is what your original pattern sought to do, the new syntax can just do it more cleanly.

**Comment by retorquere** [comment]
> The aforementioned citekey worked until the latest version without problems.

Really strange. But going forward the unescaped brackets won't work. 

> Thank you for the citekey in the new syntax, I in fact wanted the opposite logic:
> 
> '' + authors(n=3,max=3, joiner='/') + year.prefix(':') | authors(n=1, etal='_et_al')  + year.prefix(':')

You can leave off the leading `'' +` btw.

**Comment by retorquere** [comment]
this build replaces `joiner` with the more readable `join`. `joiner` still works but will show a warning.
