### ISSUE TITLE
Using zotero.lua filter for generating docx files based on org files and org-ref

### ISSUE THREAD

**Issue by aminevsaziz** [retorquere/zotero-better-bibtex#2130]
Recently I discovered the filter provided by betterbibtex for having live zotero citation using pandoc and markdown. I tried first with org file where I use org-ref citation + this filter but things failed a bit (org-ref in the format of  cite:&key ).

My question is there any clarification about the filter so maybe we can use it or modify it a bit to include popular org?

**Comment by retorquere** [comment]
I'm not sure it needs to be modified. If pandoc supports citations in org mode I think it should just work as is; if pandoc doesn't it would be pretty complex to get it to work, as it relies on pandoc clearly marking citation nodes in the AST.

**Comment by aminevsaziz** [comment]
> I'm not sure it needs to be modified. If pandoc supports citations in org mode I think it should just work as is; if pandoc doesn't it would be pretty complex to get it to work, as it relies on pandoc clearly marking citation nodes in the AST.
> 
> Specifically, I scan for [these](https://github.com/retorquere/zotero-better-bibtex/blob/master/pandoc/pandoc-zotero-live-citemarkers.lua#L391) in the AST. If pandoc doesn't parse org-mode cites into a `Cite` node, you'd have to replicate that by hand.

Thank you for your fast reply. Pandoc does support org-ref.
Furthermore the filter keep crashing each time I tried.
for example:
Line 1626 bad argument #1 to 'randomseed' (number has no integer representation)
Stack trackback:
Zetero.lua:1626 : in function <zotero.lua.1617>
[C] in function ' require '
Zotero.lua:1794: in main chunk

**Comment by retorquere** [comment]
No input should be able to crash pandoc, so that is something you'll have to take up with the pandoc crew.

**Comment by retorquere** [comment]
If that's a copy-paste, the `Zetero.lua` is strange.

**Comment by aminevsaziz** [comment]
> If that's a copy-paste, the `Zetero.lua` is strange.

Not copy paste 😅 but I type the output

**Comment by retorquere** [comment]
Still, if it's crashing, that's something the pandoc people can look into, not me.

**Comment by aminevsaziz** [comment]
> Still, if it's crashing, that's something the pandoc people can look into, not me.

well after some mingling i fixed the issue by switching to lua5.3. however the issue is still persistent as you can you see from the files attached that using odt you can produce citation but pandoc docx you cant despite pandoc being able to process the org-ref citation syntax
odt output
[org-odt.odt](https://github.com/retorquere/zotero-better-bibtex/files/8553129/org-odt.odt)
docx output
[test1.docx](https://github.com/retorquere/zotero-better-bibtex/files/8553130/test1.docx)

org source file
`#+csl-style: elsevier-harvard.csl
#+csl-locale: en-US
#+PANDOC_OPTIONS: lua-filter:zotero.lua citeproc:t
#+PANDOC_METADATA: zotero_client:zotero transferable:true zotero_scannable_cite:true zotero_csl_style:apa
#+cite_export: csl ./elsevier-harvard.csl


For example, you can refer to a table name, e.g. Table ref:table-1 in pageref:table-1. You have to provide the context before the ref link, e.g. Table, Figure, Equation, Section, and so on.

#+name: table-1
#+caption: A simple table.
| x |
| 1 |
| 2 |


org-ref citation using _cite:&_ [[cite:&nam_2011]]


* Bibliography
#+print_bibliography: :numbered t

bibliographystyle:unsrtnat

bibliography:/home/xz/dotfiles/org/bibtex/zotlib.json`

**Comment by retorquere** [comment]
> #+PANDOC_OPTIONS: lua-filter:zotero.lua citeproc:t

you don't want to run both this filter and citeproc, because the first being ran will make citation information unavailable to the other.

> #+PANDOC_METADATA: zotero_client:zotero transferable:true zotero_scannable_cite:true zotero_csl_style:apa\

transferable should be zotero_transferable, transferable only works for ODT, and you can't combine scannable-cite with anything else.

**Comment by aminevsaziz** [comment]
> 

let me try and let you know

**Comment by rgaiacs** [comment]
I was having the same problem:

```
filters/zotero.lua:1626: bad argument #1 to 'randomseed' (number has no integer representation)
```

I removed line 1626,

```
math.randomseed(os.clock()^5) 
```

and the script worked for me.

**Comment by aminevsaziz** [comment]
> I was having the same problem:
> 
> ```
> filters/zotero.lua:1626: bad argument #1 to 'randomseed' (number has no integer representation)
> ```
> 
> I removed line 1626,
> 
> ```
> math.randomseed(os.clock()^5) 
> ```
> 
> and the script worked for me.

That's right I faced this issue with Lua >=5.4, but You can change that into for example 12345 or any integer number.

@rgaiacs Can you share an example of your workflow (org --> docx)?

**Comment by rgaiacs** [comment]
Information about Pandoc in my machine:

```
$ pandoc --version
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /home/raniere/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

My workflow was Markdown to ODT and DOCX.

**Comment by aminevsaziz** [comment]
> Information about Pandoc in my machine:
> 
> ```
> $ pandoc --version
> pandoc 2.18
> Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
> citeproc 0.7, ipynb 0.2, hslua 2.2.0
> Scripting engine: Lua 5.4
> User data directory: /home/raniere/.local/share/pandoc
> Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
> This is free software; see the source for copying conditions. There is no
> warranty, not even for merchantability or fitness for a particular purpose.
> ```
> 
> My workflow was Markdown to ODT and DOCX.

Can you provide an org an example + some details. E.g running prepossessing hook inside emac to process org-ref references and then use odt and then convert to docx ?

**Comment by retorquere** [comment]
Can you try this version: https://gist.github.com/e5954e1fc19755ea50b706ae8a527147

**Comment by aminevsaziz** [comment]
> Can you try this version: https://gist.github.com/e5954e1fc19755ea50b706ae8a527147
> 
> This version replaces the math.random call with sequential IDs.

thank you @rgaiacs; the gist is more clean.

**Comment by rgaiacs** [comment]
@aminevsaziz going back to your first post

> Recently I discovered the filter provided by betterbibtex for having live zotero citation using pandoc and markdown. I tried first with org file where I use org-ref citation + this filter but things failed a bit (org-ref in the format of cite:&key ).

My understanding is that you was having issues due `Line 1626 bad argument #1 to 'randomseed'`. I had a similar problem when converting Markdown to ODT and remove that line worked for me.

Regarding org to ODT, I'm not very familiar with the process. [Pandoc's manual](https://pandoc.org/MANUAL.html) says

> When the citations extension is enabled in org, org-cite and org-ref style citations will be parsed as native pandoc citations.

So, the following minimal working example should work

```
$ cat /tmp/mwe.org 
For example, you can refer to a table name, e.g. Table ref:table-1 in pageref:table-1. You have to provide the context before the ref link, e.g. Table, Figure, Equation, Section, and so on.

#+name: table-1
#+caption: A simple table.
| x |
| 1 |
| 2 |


org-ref citation using _cite:&_ [[cite:&wilsonApplyingComputerVision]]
$ pandoc --from org+citations --to odt --output /tmp/mwe.odt --lua-filter=zotero.lua --metadata=zotero_client:zotero /tmp/mwe.org 
zotero-live-citations a266bf0e6
```

**Comment by aminevsaziz** [comment]
> working example should work

unfortunately, it wont work from command line you need to run a preprocessing hook inside emacs in order for:
1. the crossreferences to be processed using refproc.
2. citation to be processed with csl preprocess hook

**the preprocessing hooks that can be added to the end of the file and CTRL+c CRTL +c**
#+BEGIN_SRC emacs-lisp
(require 'ox-pandoc)
(require 'org-ref-refproc)
(let ((org-export-before-parsing-hook '(org-ref-cite-natmove org-ref-refproc))
      (org-export-after-parsing-hook '(org-ref-csl-preprocess-buffer))
      )
  (org-open-file (org-pandoc-export-to-docx)))
#+END_SRC

from my digging it turn out pandoc recognize org-ref citations in the form of [[citation][text]] and not [[citation]]. please keep an eye on [Pandoc issue #8044](https://github.com/jgm/pandoc/issues/8044#issuecomment-1111256377).

**Comment by aminevsaziz** [comment]
> > @ngirard unfortunately, it wont work from command line you need to run a preprocessing hook inside emacs in order for:
> > 
> > 1. the crossreferences to be processed using refproc.
> > 2. citation to be processed with csl preprocess hook
> 
> I don't understand this though. Won't this preprocessing convert cites into their rendered counterparts? Which would mean the zotero.lua script will not find Cite nodes in the AST, as they'd have been pre-replaced with content and markup (the rendered form of the cite).

that`s exactly the point that confused me the most.

**Comment by retorquere** [comment]
> > 1. the crossreferences to be processed using refproc.
> > 2. citation to be processed with csl preprocess hook
> 
> I don't understand this though. Won't this preprocessing convert cites into their rendered counterparts? Which would mean the zotero.lua script will not find Cite nodes in the AST, as they'd have been pre-replaced with content and markup (the rendered form of the cite).

I'll need to get feedback about this.

> please keep an eye on [Pandoc issue #8044](https://github.com/jgm/pandoc/issues/8044#issuecomment-1111256377).

Sorry, but no. If you keep an eye on it and ping me when something happens, that is fine, but I wouldn't even know how to reproduce your issue since I don't use org.

**Comment by retorquere** [comment]
If you get new information you can comment here and the issue will automatically re-open.
