### ISSUE TITLE
Uninstalling Better Bibtex from Zotero

### ISSUE THREAD

**Issue by afredston** [retorquere/zotero-better-bibtex#2131]
Hi, I apologize if the answer to this exists somewhere in the Better Bibtex documentation that I didn't look, but:

How do I perform a clean uninstall of Better Bibtex from my desktop Zotero? I installed it for citation management with R + rmarkdown which has been made obsolete by recent RStudio updates to allow citation management.

**Comment by retorquere** [comment]
You can uninstall bbt from the addon menu in Zotero.
