### ISSUE TITLE
Copy date-added/date-modified from extra field regenerates citation key

### ISSUE THREAD

**Issue by ahmontgo** [retorquere/zotero-better-bibtex#2142]
Support log ID: 9SNTM2H6-refs-euc

When using the "copy date-added from extra field" function after importing a bibliography, the original imported citation key is overwritten and replaced with a generated citation key.

Expected behavior: Copying date-added/date-modified from extra field should only modify date-added and date-modified
Actual behavior: In addition to modifying date-added/date-modified, the extra field "Citation Key" is deleted from "extra" and the pinned citation key is regenerated.

I think the log has everything needed, but if you want to re-import the file, the sample is here:
https://people.reed.edu/~ahm/TestImport.bib

(note: I generated an earlier support log but with the incorrect fields. Sorry! This log can be deleted: 9SNTM2H6-refs-euc )

Screenshots of before and after attached.
<img width="454" alt="Screen Shot 2022-05-05 at 2 23 26 PM" src="https://user-images.githubusercontent.com/4921971/167029999-93247916-71ad-43ce-b343-21953e4252c2.png">
<img width="451" alt="Screen Shot 2022-05-05 at 2 23 08 PM" src="https://user-images.githubusercontent.com/4921971/167030004-9e2cf5d6-2d0e-4ac9-a5dd-609d076718eb.png">

**Comment by retorquere** [comment]
Reproducible, and I want to say, thank you for all the detail, you have given me absolutely everything I need in one go for diagnosis and that means likely also for the fix. It doesn't happen often that I get them like this.

**Comment by ahmontgo** [comment]
Confirm that this now works on my end. Thank you for the rapid turnaround on this! I am in the process of moving my master .bib library (with 9K entries) into Zotero and BBT has enabled me to preserve all of my fields.
