### ISSUE TITLE
GFL8KFQC-euc Can't export library

### ISSUE THREAD

**Issue by Kullenej** [retorquere/zotero-better-bibtex#2143]
Support log ID: GFL8KFQC-euc

I can't seem to export my library - it loads and then nothing happens.

**Comment by retorquere** [comment]
I don't see an export happening in `GFL8KFQC-euc`. What exporter did you use?

**Comment by Kullenej** [comment]
A simple restart of the computer was all I needed. Sorry for the convienience and thank you again for an amazing plugin!
