### ISSUE TITLE
How to export markdown citations to LibreOffice via Pandoc

### ISSUE THREAD

**Issue by u30af** [retorquere/zotero-better-bibtex#2145]
I feel foolish filing this because I'm 97% sure the issue is just that I'm overlooking or have misconfigured some aspect of the workflow, but I've been tearing my hair out trying to figure out what I'm doing wrong.

I'm working on a dissertation chapter, writing in Markdown. I'm using Atom with the zotero-citations package to pull references from Zotero/Better BibTeX, then converting to ODT via Pandoc for cleanup, saving as Word and sending to committee members, etc. Eventually I'll be converting the Markdown to LaTeX but still need some time to get the required formatting set up.

I don't think I have anything terribly exotic in my setup. I haven't changed any of the Better BibTeX defaults or anything like that. Using Atom 1.60.0, Pandoc 2.18, zotero-citations 5.7.0, BBT 6.7.1, Zotero 6.0.6, LibreOffice 7.2.6.2 on a mostly-updated Fedora 35. I've downloaded the zotero.lua file from the BBT documentation site and put it in ~/.pandoc/filters.

Here's an example with the same behavior as the larger chapter file:
```
---
zotero:
  library: "My Library"
  scannable-cite: true
  client: zotero
  author-in-text: false
  csl-style: turabian-fullnote-bibliography
---
# Chapter 1
*draft 2022-05-05*

## Introduction

Jurgen Habermas is known as one of the most-cited authors in the social sciences. @habermasPublicSphereEncyclopedia2012
```
To convert this to ODT, I run (with Zotero open):
` pandoc -s --lua-filter=zotero.lua -f markdown -t odt mwe.md -o out.odt`
which produces the output:
`zotero-live-citations 993af1f79`
which I'm assuming isn't an explicit error?

Adding the `--verbose` flag above results in
```
[INFO] Running filter /home/username/.pandoc/filters/zotero.lua
zotero-live-citations 993af1f79
[INFO] Fetching http://127.0.0.1:23119/better-bibtex/export/item?pandocFilterData=true&translator=jzon&library=My%20Library&citationKeys=habermasPublicSphereEncyclopedia2012...
[INFO] Completed filter /home/username/.pandoc/filters/zotero.lua in 61 ms
```
Running the same command on the full document takes a bit longer to process and the list of citation keys is much longer, but it seems to finish successfully in the same way.

When I open the out.odt file in LibreOffice Writer, it looks like this. Right away I see that the usual gray Zotero fields don't seem to be present:
![Screenshot from 2022-05-08 13-46-30](https://user-images.githubusercontent.com/31356727/167315244-85bcfde1-947f-4e6c-afb6-0b7fb77cbff4.png)

I open the Zotero document preferences, confirm that my preferred citation style is selected, and then click OK. 
Clicking the Zotero refresh button pops up the following message: `You must insert a citation before performing this operation.` The citation keys are obviously just plain text.

So from the looks of the Pandoc output, is it correct to assume that the conversion process is connecting to Zotero/BBT just fine? Is there something completely obvious I'm missing here?

Thank you in advance!

**Comment by u30af** [comment]
Just restarted Zotero with debug logging enabled, re-ran the pandoc conversion above, and submitted a debug report. The debug ID is `RYCISLXU-euc`.

**Comment by retorquere** [comment]
> So from the looks of the Pandoc output, is it correct to assume that the conversion process is connecting to Zotero/BBT just fine? Is there something completely obvious I'm missing here?

Yes, and no, respectively. I have it reproducible.

**Comment by u30af** [comment]
I don't know if this adds anything meaningful, but I was searching around the web and found someone's blog where they described a similar Markdown-Zotero-Pandoc workflow (and which I can't now find my way back to) and I saw that their citations were enclosed in brackets. I made this change to my MWE:

`Jurgen Habermas is known as one of the most-cited authors in the social sciences. [@habermasPublicSphereEncyclopedia2012]`

and ran Pandoc again.

On opening the ODT, there is now some additional code, or something, around the citation mark, though Zotero still claims I have not added any citations to the document:
![Screenshot from 2022-05-10 17-11-32](https://user-images.githubusercontent.com/31356727/167744329-bf957787-6913-4ef1-ba0f-bee5796f38a7.png)
I tried running Pandoc to output a DOCX instead of ODT file, and now get this:
![Screenshot from 2022-05-10 17-14-37](https://user-images.githubusercontent.com/31356727/167744427-56c850af-6b3b-4d5a-9e65-e533fc51d955.png)
(Apparently my Pandoc templates for ODT and DOCX are different). The gray background looks more like an embedded Zotero citation, but on opening document properties and then refreshing the document, Zotero still gives the same complaint about no citations.

**Comment by u30af** [comment]
Do you mean the newest version of BBT? I think I had the most recent release (6.7.1) from here but I downloaded and reinstalled it, then restarted Zotero. Running pandoc gives the same results as my previous comment, both with ODT and DOCX.

**Comment by retorquere** [comment]
No, sorry, I meant the newest Lua file.

**Comment by u30af** [comment]
Okay, I downloaded the updated Lua file from https://retorque.re/zotero-better-bibtex/exporting/pandoc/ (is that the right place? I didn't see anything obvious in the GitHub repo), replaced the previous one, and ran the conversions to ODT and DOCX again. Aside from the pandoc output changing to `zotero-live-citations f34bfc770`, the documents look and act the same.

**Comment by retorquere** [comment]
> I don't know if this adds anything meaningful, but I was searching around the web and found someone's blog where they described a similar Markdown-Zotero-Pandoc workflow (and which I can't now find my way back to) and I saw that their citations were enclosed in brackets. I made this change to my MWE:

There's a few things happening here; your original MWE used @habermasPublicSphereEncyclopedia2012, which means the citation is rendered to something like `Habermas (2012)`, which is not something Zotero supports, so if you enable author-in-text (which you have off), it will output the author name as plain text, and then a cite with suppress-author (which Zotero does support). When it is off, the filter passes through the `@habermasPublicSphereEncyclopedia2012` unchanged.

 
> `Jurgen Habermas is known as one of the most-cited authors in the social sciences. [@habermasPublicSphereEncyclopedia2012]`

This is a form of quote that Zotero supports.
 
> and ran Pandoc again.
> 
> On opening the ODT, there is now some additional code, or something, around the citation mark, though Zotero still claims I have not added any citations to the document:

That's because you requested `scannable-cite` to be output. scannable-cite only works for ODT.

> I tried running Pandoc to output a DOCX instead of ODT file, and now get this: ![Screenshot from 2022-05-10 17-14-37](https://user-images.githubusercontent.com/31356727/167744427-56c850af-6b3b-4d5a-9e65-e533fc51d955.png) (Apparently my Pandoc templates for ODT and DOCX are different). The gray background looks more like an embedded Zotero citation, but on opening document properties and then refreshing the document, Zotero still gives the same complaint about no citations.

I think we first need to establish what you want to output, because you have a strange combination of options.

**Comment by u30af** [comment]
> I think we first need to establish what you want to output, because you have a strange combination of options.

I thought this might be the case. I don't think I quite understand what some of the options like `scannable-cite` or `author-in-text` did, or if they were relevant.

As far as what I want to output: I'd like to be able to output my Markdown with citations to ODT as live Zotero citations, or whatever the terminology is: as though I'd entered the citations from Zotero, so that I can change citation styles etc. as necessary within LibreOffice and have them updated, generate a bibliography with the Zotero plug-in, reflect changes I make to entries in Zotero, etc.

(I realize I may have made this unnecessarily confusing with my reports of trying to convert from Markdown to DOCX with the citations--I do **not** need Markdown→DOCX conversion, just ODT. I share Word documents with my committee but I produce them from the ODT after unlinking the Zotero citations anyway.)

But this is now somewhat irrelevant; I think I made a change that got the desired behavior! I thought that the `scannable-cite` option was what I wanted (the Zotero citations embedded in an ODT document) which is why I had it turned on in my YAML block. But your reply made me wonder if it was something more specific or advanced, so I disabled it. Now the following MWE produces the correct behavior: when I open the ODT file and choose a citation style in the Zotero document preferences, the citation code changes to the actual expected citation.

```
---
zotero:
  library: "My Library"
  scannable-cite: false
  client: zotero
  author-in-text: false
  csl-style: turabian-fullnote-bibliography
---

# Chapter 1
*draft 2022-05-05*

## Introduction

Jurgen Habermas is known as one of the most-cited authors in the social sciences. [@habermasPublicSphereEncyclopedia2012]
```

I think I initially had `scannable-cite` disabled but that was before I realized the citation needs to be enclosed in brackets, which may have explained why it wasn't working from the start.

Given what I had wanted to output and how this appears to work as expected, are there any other options I should be aware of or that may cause potential issues?

**Comment by retorquere** [comment]
No, I don't think so.

**Comment by u30af** [comment]
Thank you so much for all the assistance, especially since the issue was just my mis-configured settings. I really appreciate your time & patience, and I'm glad that I can use BBT to streamline the citing/references portion of my dissertation.
