### ISSUE TITLE
'Copy as Better BibTex' does ignore Journal Abreviations

### ISSUE THREAD

**Issue by f-brinkmann** [retorquere/zotero-better-bibtex#2147]
Hello,

I noted that Journal abbreviations are ignored when quickly exporting references using the 'Edit -> Copy as Better BibTeX' from Zotero's graphical interface. For example, I get the field

journal = {Journal of the Audio Engineering Society}

using the Copy option, whereas in the automatically generated bib file containing my entire library, I get the correct entry

journal = {J. Audio Eng. Soc.}

Best, Fabian

Support Log: 5H7DAMJ6-refs-euc

**Comment by retorquere** [comment]
That's because with quick-copy you cannot pass options. You must have the "use journal abbreviation" option checked when you do manual exports.

**Comment by f-brinkmann** [comment]
I already had `Use journal abbreviations` enabled in *Zotero Preferences -> Better BibTex -> Automatic Export* and did not find anything else that seemed to be related. I found another option for automatic abbreviation, but that does not seem to be the problem here, because there is no automatic abbreviation for the Journal used in the example.

**Comment by retorquere** [comment]
> I already had `Use journal abbreviations` enabled in _Zotero Preferences -> Better BibTex -> Automatic Export_ 

That is unrelated to quick-copy

> and did not find anything else that seemed to be related.

I think there isn't anything of the sort you want. When you export manually, you are offered some checkboxes to drive the behavior of that specific, one-time export. When you choose "keep updated", BBT notes the choices you made here and copies that to the auto-export. But there isn't any place where you can set the one-time export options for quick-copy. They are just always assumed off by Zotero, and that is the information Zotero feeds to the translator.

> I found another option for automatic abbreviation, but that does not seem to be the problem here, because there is no automatic abbreviation for the Journal used in the example.

I don't understand what you are saying here.

**Comment by f-brinkmann** [comment]
OK, I see. In this case, an easy workaround would be to copy paste single references from the bib-file containing the entire library. Thanks for the quick responses!

**Comment by wuchichou** [comment]
@f-brinkmann Or alternatively, there is a workaround given by @OVlasiuk in https://github.com/zotero/zotero/issues/292#issuecomment-875084043, which does not need to generate bibtex file and copy-paste entries manually.
