### ISSUE TITLE
Auto export with git sometimes fails

### ISSUE THREAD

**Issue by lennartb-** [retorquere/zotero-better-bibtex#2148]
Support log ID: ZEF6CPZI-euc

I've set up BBT with auto export and git (hosted on Overleaf) as described on https://retorque.re/zotero-better-bibtex/exporting/auto/ However, most of the time the export from Zotero fails. I can see a small error window at the bottom right for a very short time, which apparently says that the git process exited with exit code 1. Pushing manually via a terminal works perfectly.
I've checked the log and it says
```
(3)(+0000095): {better-bibtex} +95 flash: {'title':'autoexport git push failed','body':'failed with exit status 1: "c:\\\\program files\\\\git\\\\cmd\\\\git.EXE" -C E:\\OneDrive\\Path\\to_my\\Folder commit -m "BibLaTeX updated by Better BibTeX for Zotero"'}
```

which doesn't give any more info. Anything I can do to help debugging this?

**Comment by lennartb-** [comment]
There doesn't appear a shell. I think it fails at git commit, you added the cmd command only on the git push line :)

**Comment by lennartb-** [comment]
```
remote: Counting objects: 7, done
remote: Finding sources: 100% (4/4)
remote: Getting sizes: 100% (6/6)
remote: Compressing objects: 100% (875/875)
remote: Total 4 (delta 3), reused 0 (delta 0)
Unpacking objects: 100% (4/4), 389 bytes | 4.00 KiB/s, done.
From https://git.overleaf.com/[redacted]
   b1e69ec..826ca63  master     -> origin/master
Your local changes to the following files would be overwritten by merge:
  zotero-biblatex.bib
```

Interesting, as there are no remote changes to the file, as it is only ever written by Zotero and BBT.

**Comment by retorquere** [comment]
Can you try 2586?

**Comment by lennartb-** [comment]
I uploaded a new log at M9HW3CNH-euc

The initial `git checkout` now reports `Updated 0 paths from the index`, the following shells are empty and nothing seems to get commited or pushed

**Comment by retorquere** [comment]
Empty shells in what sense? Are the other commands still being executed? Remember I cannot see what you see.

**Comment by lennartb-** [comment]
Sorry, each git command opens a cmd-window/shell in the debugging versions, and each contains the output of the git command executed. The first for `git checkout` print the “Updated 0 paths...”, the following ones that open for commit and push contain nothing, as the git commands don't seem to do or print anything.

**Comment by retorquere** [comment]
It should show, in order, checkout, pull, add, commit, push. Can you post screenshots of the git commands?

**Comment by lennartb-** [comment]
Not a whole lot to see:
![image](https://user-images.githubusercontent.com/5563601/168467055-d0def9ea-f11b-4177-a4f8-2e60d93602ae.png)

After I close the window (it does nothing further, I waited a couple of minutes), the next two windows are the same: 
![image](https://user-images.githubusercontent.com/5563601/168467093-0377d224-6aee-4fa6-bdb4-d2b711ed05ef.png)

**Comment by retorquere** [comment]
> Not a whole lot to see:

That's weird in itself, because a `git push` will say `Everything up-to-date` if there is no work to do.

what is core.autocrlf set to for that clone/user/globally?

**Comment by lennartb-** [comment]
`git config core.autocrlf` returns `false`. Same behaviour with new build.

The repo lies in a OneDrive-synced folder btw, but that shouldn't have an impact on how git behaves.

**Comment by retorquere** [comment]
Well that's just strange, because the new build show always commit & push, even when there are no changes. Can you send a new debug log after replicating?

**Comment by lennartb-** [comment]
Sure, 9CHT45H9-euc

**Comment by retorquere** [comment]
It's the `add` that fails. What does 

```
CMD.EXE /C "c:\\program files\\git\\cmd\\git.EXE" -C E:\OneDrive\Uni\MA\Thesis add zotero-biblatex.bib
```

show if you run it anywhere but in `E:\OneDrive\Uni\MA\Thesis`?

**Comment by lennartb-** [comment]
Nothing. If I use the same command in a different repo in a "regular" (non-OneDrive) folder to add an existing file to that repo nothing is printed as well. I assume `git add` just doesn't print anything if it succeeds. Can it be that the git command itself succeeds, but for some reason a nonzero exit code is returned? Currently trying to run the TS code directly in the JavaScript console in Zotero.

**Comment by retorquere** [comment]
Can you run it in cmd, and after that in the same shell type `echo %errorlevel%`?

**Comment by retorquere** [comment]
And if you do `git add non-existent-file`, what is the errorlevel then?

**Comment by retorquere** [comment]
> I don't know JS at all and cobbled this only together, but it seems to return -1 regardless of whether the command was

args should be an array of individual arguments, split the string at the spaces. If you paste it as text I can correct it for you.

**Comment by lennartb-** [comment]
For an existing file, errorlevel is "0", for a non-existing file it's "128".

```
const proc = Components.classes['@mozilla.org/process/util;1']
    .createInstance(Components.interfaces.nsIProcess)

const cmd = new FileUtils.File('C:\\Windows\\System32\\cmd.exe')
proc.init(cmd)
const args = ["/k", "git -C E:\\OneDrive\\Uni\\MA\\Thesis add zotero-biblatex.bib"]
// const args = ["/k", "git","-C","E:\\OneDrive\\Uni\\MA\\Thesis","add","zotero-biblatex.bib"]
proc.runAsync(args, args.length, null)
return proc.exitValue
```
Like this? Also returns -1.

**Comment by retorquere** [comment]
> Like this? Also returns -1.

almost -- you have the right `const args` commented out above

And if you issue this:

```
const proc = Components.classes['@mozilla.org/process/util;1']
    .createInstance(Components.interfaces.nsIProcess)

const cmd = new FileUtils.File('git.exe') // I don't know what the full path to git.exe is on your system
proc.init(cmd)
const args = ["-C","E:\\OneDrive\\Uni\\MA\\Thesis","add","zotero-biblatex.bib"]
proc.runAsync(args, args.length, null)
return proc.exitValue
```
what do you get if you manually change (like add an empty line somewhere) and then run this?

**Comment by lennartb-** [comment]
Yeah, tried both versions of mine with the same result.

Your code also returns -1. Did some more testing, I don't think `proc.exitValue` receives the correct value from it's processes: 
![image](https://user-images.githubusercontent.com/5563601/168789306-c167c40f-3be4-4048-b7c0-f857187af76e.png)

(no open changes in this example)

**Comment by retorquere** [comment]
This build will just ignore results <= 0. It's really strange. I haven't gotten any response from the zotero devs, so this seems the most reasonable approach right now.

**Comment by lennartb-** [comment]
Sorry for the delay. I used the latest version from the branch over the last couple of days, and while the error message in Zotero still comes up, all git operations seem to be successful.

**Comment by retorquere** [comment]
Which error message? Exit values lower than 0 are treated as succeeding in 2623, so I would not have expected an error message.

**Comment by lennartb-** [comment]
I uploaded a new support log: S5TBRKWW-euc

Git add seems to work fine now, the commit "fails" with exit value 1, however I assume that's because there's nothing commit, as in the screenshot I posted [earlier](https://github.com/retorquere/zotero-better-bibtex/issues/2148#issuecomment-1128688492). This seems to be an outlier though, as I can see in the git history that BBT succeeds regularly in pushing changes.

**Comment by retorquere** [comment]
It shouldn't really happen that there's nothing to commit, but the errors are only reported now, they do not block anything.

Do you still get the cmd popups? I didn't expect that.

**Comment by retorquere** [comment]
No, I'm fine for interaction with windows 😄
