### ISSUE TITLE
how to install, when "damaged" 

### ISSUE THREAD

**Issue by justusnoe** [retorquere/zotero-better-bibtex#2149]
Tried many ways now, but installation wasn't possible. There is always the warning: "this add-on could not be installed because it appears to be corrupted in mozilla". 
How can I solve this? 
Thanks

**Comment by retorquere** [comment]
Is it firefox that says it's damaged, or Zotero?

**Comment by justusnoe** [comment]
firefox

**Comment by retorquere** [comment]
Right-click, save, drag onto zotero. Firefox tries to install it as a Firefox plugin without asking, and gives this rather unhelpfully message when it finds out its not for Firefox.

**Comment by justusnoe** [comment]
got it! have to add it by the add one menu
