### ISSUE TITLE
Not exporting certain fields correctly

### ISSUE THREAD

**Issue by brandazzle** [retorquere/zotero-better-bibtex#2150]
When creating a `.bib` file, BetterBibTeX places the journal name in a "Journaltitle" field instead of the "Journal" field, and places the date in a "Date" field rather than the expected "Month" and "Year" fields, making LaTeX unable to read the journal or date.

Support log ID: PNLIHY5U-refs-euc

**Comment by retorquere** [comment]
Are you perhaps exporting as biblatex rather than bibtex?

**Comment by retorquere** [comment]
cloding for inactivity
