### ISSUE TITLE
LyX integration of `zotero-better-bibtex`. 

### ISSUE THREAD

**Issue by hongyi-zhao** [retorquere/zotero-better-bibtex#2152]
I noticed the [`lyz`](https://github.com/wshanks/lyz) project, which is a plugin for Zotero intended to make working with LyX/Zotero more pleasant. OTOH, I want to know if [`zotero-better-bibtex`](https://github.com/retorquere/zotero-better-bibtex) also have the similar features/capabilities.

Regards,
HZ

**Comment by retorquere** [comment]
No, the lyz project does something distinct.
