### ISSUE TITLE
Provides the function of right-clicking to quickly export bibtex text to the clipboard

### ISSUE THREAD

**Issue by ARC-MX** [retorquere/zotero-better-bibtex#2154]
~enhancement 
Alongside a description of your problem/question/feature suggestion, please also include a support log ID.

In order to facilitate users to manage documents at any time, it is sometimes necessary to manually add new files, so it is not very convenient to re-export the bibtex file. It is recommended to provide the function of right-clicking the selected file and automatically exporting the bibtex content to the clipboard.

Thank you very much

**Comment by retorquere** [comment]
Select file where? Outside zotero? An attachment in Zotero?

**Comment by ARC-MX** [comment]
![image](https://user-images.githubusercontent.com/34829404/168476094-6ef7af2b-6917-4486-9b80-1276e78ad127.png)
  then we can paste @article to .bib file

**Comment by retorquere** [comment]
I was confused because that's not a file. But zotero already has quick-copy functionality for this.

**Comment by ARC-MX** [comment]
If I click on this option I can copy the following to my clipboard.
`@inproceedings{choiAccurateEfficient2bit2019,
  title     = {Accurate and Efficient 2-Bit Quantized Neural Networks},
  booktitle = {Proceedings of Machine Learning and Systems},
  author    = {Choi, Jungwook and Venkataramani, Swagath and Srinivasan, Vijayalakshmi (Viji) and Gopalakrishnan, Kailash and Wang, Zhuo and Chuang, Pierce},
  editor    = {Talwalkar, A. and Smith, V. and Zaharia, M.},
  year      = {2019},
  volume    = {1},
  pages     = {348--359}
}`
After that I can paste it into my bib file.

**Comment by retorquere** [comment]
But that is what zotero's quick-cooy does, only it uses a key combination instead of a menu option. It seems to me what you want is standard zotero functionality.

**Comment by ARC-MX** [comment]
Ok, I found a similar function in zotero
thank you again
