### ISSUE TITLE
Failed to start background export

### ISSUE THREAD

**Issue by nebelj** [retorquere/zotero-better-bibtex#2156]
I have automatic export enabled but get a "failed to start background export" error. It says to "PLEASE report this as a bug" here. 

Here's a support log ID for an arbitrary reference, since I'm really not sure what reference (if any) is responsible for it: IU3WI3U2-refs-euc

Thanks!

**Comment by retorquere** [comment]
Is this a transient problem, or structural?

**Comment by nebelj** [comment]
Thanks! It’s definitely not transient—I’ve had and noticed the issue for a long time, on multiple devices, across multiple versions of Zotero (though same library).

**Comment by retorquere** [comment]
Is this for an export to a network drive or cloud drive?

**Comment by nebelj** [comment]
No, the library is stored locally (though synced via Zotero).

**Comment by retorquere** [comment]
I'd need to see a log that captures the error happening, `IU3WI3U2-refs-euc` has no errors.

**Comment by nebelj** [comment]
How about 6DIGIY6U-refs-euc? This seems to list errors on my end.

**Comment by Connerdric** [comment]
I have a very similar issue ! 
Here is my log, i think it contains the error : 
8IE6LL7T-euc

**Comment by retorquere** [comment]
I need a log from 2602

**Comment by Connerdric** [comment]
I am not sure to understand what you mean by : a log from 2602

**Comment by retorquere** [comment]
Sorry -- a new build was just posted with version 6.7.1.2602, that build shows more details about the error. The release only says "could not get worker" but no hint why.

**Comment by Connerdric** [comment]
Got it !

**Comment by retorquere** [comment]
The frustrating thing is that there's a decent chance it will say "could not fetch this URL that lives right in this package"

**Comment by Connerdric** [comment]
I see, well i haw going to try to redo the error to give you a usefull log. I'll keep you updated

**Comment by Connerdric** [comment]
Well, right now every thing seems to be working smoothly... maybe the update did it, or i stop doing an error i didn't know i was making. Anyway, i am going to see if it pass the test of time haha, but for know it's ok. Thanks for the quick answer!

**Comment by retorquere** [comment]
You can safely keep using this build, it is production code, and the next release will have this logging.

**Comment by retorquere** [comment]
Can you upgrade to build 2620?

**Comment by nebelj** [comment]
Just upgraded. I'm not getting the error now, for the first time I can remember, so that's great. I did just submit a support log anyways, EH3X5KBR-refs-euc.
