### ISSUE TITLE
Failed to start background export 

### ISSUE THREAD

**Issue by Connerdric** [retorquere/zotero-better-bibtex#2158]
Hi,

I am having issues with Better Biblatex not updating the exported library automatically. It's like it doesn't detect the "change" in it when i add or remove reference.  It, sometimes, makes an error pop-up saying : Failed to start background export, please report as a bug. The library is local on my computer, i use it to connect with Opsidian witch i use for note taking. 

I think that this log as the error in it : 8IE6LL7T-euc

If you need anything to help me ask it, i don't know exactly what you need ! 

Thanks a lot

**Comment by retorquere** [comment]
Thanks for the log -- can you join #2156? Then I don't have to cross-post.
