### ISSUE TITLE
Remove Doi in Elsevier Latex Templates

### ISSUE THREAD

**Issue by sx351967213** [retorquere/zotero-better-bibtex#2177]
**Alongside a description of your problem/question/feature suggestion, please also include a support log ID.**
Hi，everyone.
Recently, I have been using better bibtex to insert References for elsevier latex template but it always adds doi. What can I do to remove the doi.
Reproducing the problem：
1. Zotero export a Better Bibtex.bib.
2. The bibliographystyle of latex templates is Elsevier - Harvard.
3. The latex command is:
4. \bibliographystyle{cas-model2-names.bst}
\bibliography{References}
Thank you for your help.

**Comment by retorquere** [comment]
I you do not supply a log ID I will have to close the issue.
