### ISSUE TITLE
Bugs with Automatic Export & UI

### ISSUE THREAD

**Issue by Prometheos2** [retorquere/zotero-better-bibtex#2179]
Hello,

I have a few bugs with Automatic Export: 
* the export is not done on modification, like it should, 
* and the UI is blank, despite having quite a few exports.

Adding new exports does not fix the UI.

![image](https://user-images.githubusercontent.com/45640841/173338146-e35c63ea-7c8e-4a99-800f-fda3dfaefc42.png)

The citation key format also appears blank and filled with orange when opening the settings, but it fills up after switching tabs.

![image](https://user-images.githubusercontent.com/45640841/173339015-b663ebd9-2bb3-4e25-a8f7-ddf79e31036e.png)

I recently exported the same directory to two different files, and started modifying the Tex Live installation, so it might be that.

## Report references:
* XHK45WLI-euc (w/o reference)
* WCBGMANR-refs-apse (with a reference)

**Comment by Prometheos2** [comment]
It also resets the parallel exports slider to 0 whether I modify it (or ignore the change)

UKWIV8DC-refs-euc

**Comment by retorquere** [comment]
> It also resets the parallel exports slider to 0 whether I modify it (or ignore the change)

I didn't know 6.7.1 still had the slider, I've put out 6.7.5 which removes it.

Your auto-export database has been changed outside BBT in some way, would it be possible for you to quit Zotero, zip `better-bibtex.sqlite` and attach it here?

**Comment by Prometheos2** [comment]
Here it is
[better-bibtex.zip](https://github.com/retorquere/zotero-better-bibtex/files/8893536/better-bibtex.zip)

Do you want me to stay on 6.7.1, or update to .5 and see if the bug still happens?

**Comment by retorquere** [comment]
There is a single auto-export record to `Tools.bib` that is missing metadata -- no idea how that database could have gotten in that state, but unlikely through BBT. If you go into the Zotero [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences), enable `scrubDatabase`, and restart, that will remove it and leave the rest. The pattern being empty was knock-on damage, that fixes after the DB is scrubbed.

**Comment by Prometheos2** [comment]
That fixed the problem, both the UI and the exporting
Thank you for the help 😊
