### ISSUE TITLE
debug-bridge for zotero 6

### ISSUE THREAD

**Issue by randomgeek78** [retorquere/zotero-better-bibtex#2183]
I have used [debug-bridge](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge) in the past and found it very helpful. But the [released version](https://github.com/retorquere/zotero-better-bibtex/releases/download/debug-bridge/debug-bridge-5.1.105.emile.limonia.xpi) is not compatible with zotero 6. Any plans of releasing a version of debug-bridge for Zotero 6? Thanks!

**Comment by randomgeek78** [comment]
@retorquere I don't know if you need me to provide more information. If so, please let me know. Thanks!

**Comment by retorquere** [comment]
no further information, I've updated the reease.

**Comment by randomgeek78** [comment]
@retorquere Thanks. I was able to install it in Zotero 6. But I was not able to find `extensions.zotero.debug-bridge.password` in the Config Editor. Am I to create a new key? I don't remember what I did for Zotero 5 but I was able to follow your instructions without any issues.

**Comment by retorquere** [comment]
If you had a very old version of the debug bridge it didn't have the password requirement. If so, you will have to create a new key, yes.

**Comment by randomgeek78** [comment]
Got it. I was able to create a new key and was also able to test run it. For others who may be interested, these are some simple instructions to test run it-

1. Follow [link](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge) to setup Zotero and the password. Let's assume the password is `1234`.
2. Create a directory proof-concept and cd into it
3. Create a file hello.js with contents:
```javascript
async function test(query) {
  await Zotero.Schema.schemaUpdatePromise; 
  return 'hello ' + query.world
}
```
4. Create a run.sh file-
```bash
password=1234
curl -s -H "Content-Type: application/javascript" -X POST \
  --data-binary @hello.js \
  'http://127.0.0.1:23119/debug-bridge/execute?world=world&password='$password
```
If you run `run.sh`, you should see `"hello world"` as the output. This is generated within Zotero.
