### ISSUE TITLE
High CPU allocation when exporting library. ID: RNIM2HLU-refs-euc

### ISSUE THREAD

**Issue by Harry-2100** [retorquere/zotero-better-bibtex#2184]
Support log ID: RNIM2HLU-refs-euc

I have described the issue in https://forums.zotero.org/discussion/97843/entering-data-makes-zotero-unresponsive-id-164452951

**Comment by retorquere** [comment]
Can you install build 2768, try again (after turning on worker), and send a new log?

**Comment by Harry-2100** [comment]
I may have misunderstood the "worker" thing. I will have to verify. Will get back...

**Comment by retorquere** [comment]
`worker` is still set to `false` in `NX3PJSG4-euc`.

**Comment by retorquere** [comment]
Background export works, and most items come from the cache; this is how I expect things to be. You can keep this or reinstall the release you had, no difference, and the build you installed will upgrade to the next release automatically.
