### ISSUE TITLE
"Better BibTeX: error saving autoexport, restart to repair"

### ISSUE THREAD

**Issue by BapMel** [retorquere/zotero-better-bibtex#2186]
Hi,

(My Zotero Debug ID is D1619403057. I could not get a BBT support log because the initialization of Better BibTeX does not terminate. In other words, my issue even seems to prevent me from getting a technical report...)

Zotero 6.0.8
Better BibTeX 6.7.10
Ubuntu 20.04

**Expected behaviour:**

- install BBT;
- answer to the initializing questions;
- the initialization terminates;
- use Zotero with BBT.

**Actual behaviour:**

- install BBT;
- answer to the initializing questions;
- get a message saying that BBT is now configured;
- click on the "Finish" button;
- the "Better BibTeX: Initializing" box appears and, after some steps, freezes at the step "Installation des convertisseurs" in French, thus probably "Installing converters" in English;
- a window opens, titled "[JavaScript Application]", with the message: "Better BibTeX: error saving autoexport, restart to repair";
- the same happens each time I restart and answer to BBT's initialization questions.

Here is my Zotero log:
[debug_output.zip](https://github.com/retorquere/zotero-better-bibtex/files/8925975/debug_output.zip)

I tried to:
- reinstall BBT;
- remove the Zotero/better-bibtex directory and restart.

What should I do?

Thanks!

Baptiste.

**Comment by retorquere** [comment]
How did you install Zotero/how do you start Zotero? I'm seeing filesystem permission errors for `/home/meles1/Zotero/styles/...` in that log, and I'd prefer to make sure those aren't the root cause.

**Comment by retorquere** [comment]
please try build 2771

**Comment by retorquere** [comment]
could really use that feedback

**Comment by BapMel** [comment]
Thanks for your answers! 

Concerning the filesystem permission errors about ~/Zotero/styles/..., I saw that some files had root as owner and group. I changed it, now it is me as a normal user.

I have installed test build 6.7.10.2772, but I still have the same issue. 

Now I have a BBT log ID: V3U5D7CK-euc.

**Comment by retorquere** [comment]
This doesn't seem like it's the same issue? If you start Zotero again, do you see the first-run wizard again?

**Comment by BapMel** [comment]
When I start again Zotero now, the BBT first-run wizard opens and still freezes while "installing converters". It has not changed.

What has changed now is that I do not have any Zotero error anymore: the Zotero error log is empty. Maybe this is because I changed the owner of my ~/Zotero/styles/... files.

**Comment by BapMel** [comment]
It seems that the problem is solved! Some of my ~/.zotero files were owned by root, too: prefs.js, extensions.ini, mimeTypes.rdf. 

I changed their owner and now BBT seems to work. Thanks a lot!

**Comment by retorquere** [comment]
Super. That's why I asked how you installed/start zotero btw.

**Comment by BapMel** [comment]
If I remember well, I first installed it from a .deb file (and BBT worked). More recently, I switched to the Zotero repository. Maybe my trouble with BBT began at that time. I probably did something wrong during the installation, but I cannot remember what.

Thanks again for your help!
