### ISSUE TITLE
citation-key variable disappeared in v6.7.5

### ISSUE THREAD

**Issue by jjadup** [retorquere/zotero-better-bibtex#2188]
**Issue**
I have a custom Zotero bibliography style (a .csl file) which uses the variable "citation-key" to extract an entry's citation key. This worked up to and including v6.7.1, but it no longer works in v6.7.5 and later.

**Potential cause**
Comparing versions, I noticed line 107 in content/better-bibtex.ts was removed between v.6.7.1 and v6.7.5: `cslItem['citation-key'] = citekey.citekey`

**Request**
Is there any way for me to use the citation key in a .csl file without rolling back my installation to v.6.7.1 when this was still possible?

**Comment by jjadup** [comment]
Support log ID: K5XT2MYD-refs-euc

My expectation of the Quick Copy output would be a string prepended with "[^QuinnnEtAl2021]: ". Instead, this is missing from the string since the bibliography style is not able to get the citation key.

**Comment by retorquere** [comment]
You do not want this behavior back?

**Comment by jjadup** [comment]
If possible, I **would like** the "citation-key" variable back since I use it in my bibliography style. Alternatively, if there's a new way to get the BBT citation key in the latest version then please let me know.

**Comment by jjadup** [comment]
The test build works, thank you!

Apologies for the premature close, I hit the wrong button, but the bot re-opened it automatically.
