### ISSUE TITLE
unable to put "postfix" in middle of citekey

### ISSUE THREAD

**Issue by daaaaaaaaaniel** [retorquere/zotero-better-bibtex#2190]
ID: `PHG3RDB4-euc`  

BBT prevents cite key collisions by adding a postscript (by default a, b, etc.). The output can be customized beyond the default - I'm using`+postfix('-%(a)s',1)` to put '-' before it. I would like this "postfix" to appear in the middle of my citekey, rather than the end. 

For example, the cite key `manning.etal2019_Imme-a` is generated for the item below. I want it to look like `manning.etal2019-a_Imme`, with the "postfix" after the year rather than at the very end of the key.  

Manning, Erin, Anna Munster, and Bodil Marie Stavning Thomsen, eds. *Immediation I*. Open Humanites Press, 2019. 

My full formula is this:

```
auth(clean=true).lower.replace(find="-",replace="")+auth(1,2).replace(/.+/g,'.etal')+year+postfix('-%(a)s',1)+len('>',5)+ShortTitle.skipwords.capitalize.len('>', 1).select(1,2).clean.replace(find="-",replace="").condense('').substring(1,4).prefix(_) | auth(clean=true).lower.replace(find="-",replace="")+auth(1,2).replace(/.+/g,'.etal')+year+postfix('-%(a)s',1)+shorttitle(2,2).clean.replace(find="-",replace="").condense('').substring(1,4).prefix('_').default(untitled)
```
\* It's basically the same formula twice — once with the verbatim Short Title, and if it's empty then using the Title field as the fallback.

**Comment by retorquere** [comment]
Sorry for the long silence -- this is indeed not currently possible. It would be a fairly significant change to implement this.

**Comment by retorquere** [comment]
Build 3438 add `infix`, which works just like `postfix` but adds the disambiguator where it appears in the formula rather than at the end. I'd appreciate it if you could test it.

**Comment by daaaaaaaaaniel** [comment]
@retorquere I would be happy to test it, but I can't figure out how (I'm relatively new to participating in open source projects and I'm not coming from a computer science/programming background). I don't know where to find Build 3438. I searched the branches and tags in the repo but couldn't find one labeled "3438".

Today in Zotero I updated to the latest version of BBT today (6.7.38). I tried changing my editing my citation key format replaceing `+postfix('-%(a)s')` with `+infix('-%(a)s')`, but this causes the background to turn orange and prevents me from saving the new formula.

**Comment by daaaaaaaaaniel** [comment]
@retorquere I've installed Build 3438 in my Zotero client and I updated my citekey formula to make use of `infix` rather than `postfix`. It seems like using `infix` prevents prevents the generation of new citekeys when importing new items, and prevents existing citekeys from updating when using the "Refresh BibTeX key" popup menu item. 

Submitted log `VZTIC3AX-refs-euc`.

**Comment by retorquere** [comment]
This build should fix that.

**Comment by daaaaaaaaaniel** [comment]
@retorquere so far its working flawlessly in my tests this time around. nice job with this one!
