### ISSUE TITLE
Citations keys get reassigned each time, and Initializing stuck on 'Starting key manager' 

### ISSUE THREAD

**Issue by guqinglei123** [retorquere/zotero-better-bibtex#2193]
OS: Windows

Zotero version: 6.0.9

BBT version: 6.2.14

Support log ID: ZSMT74IZ-apse

Expected behavior: BBT correctly initializes.

Actual behavior: 
 I open Zotero (6.0.9) with BBT (6.2.14), and it says “Better BibTeX:Assigning citation keys，Found 15 items without a citation key” each time.
The pop up window stuck at "Better BibTeX: Initializing, starting key manager." Also, in Zotero Preference panel, after clicking "Better BibTeX" tab, nothing but only "Better BibTeX is loading" is shown.

**Comment by retorquere** [comment]
I don't quite follow -- your debug log confirms Zotero 6.0.9 and BBT 6.2.14, but you mention zotero 5.0.66 and BBT 5.1.85?

**Comment by guqinglei123** [comment]
Sorry,  there are some typos in the description of actual behavior. I use Zotero 6.0.9 and BBT 6.2.14.  I have revised it.

**Comment by guqinglei123** [comment]
The  TXT file is NULL.

**Comment by retorquere** [comment]
And if you try `C:\Program Files (x86)\Zotero\zotero.exe” -ZoteroDebugText -console > zotero.txt 2>&1` instead?

**Comment by retorquere** [comment]
I need more info, or I cannot help. I cannot reproduce this.
