### ISSUE TITLE
Space being produced after \textendash

### ISSUE THREAD

**Issue by lukisikul** [retorquere/zotero-better-bibtex#2194]
Support log ID: QGWWWW58-refs-euc

Hi, I have noticed that references with en dashes are producing a space following "\textendash" in their titles. I have reproduced this for one offending reference, and then generated the support log noted above. Below is an example of the titles being spit out. I would expect no space after "\textendash", as the title in Zotero is "Top incomes, income and wealth inequality in the Netherlands: the first 100 years 1914–2014 – what's next?"

`  title = {Top Incomes, Income and Wealth Inequality in the {{Netherlands}}: The First 100 Years 1914\textendash 2014 \textendash{} What's Next?},`

In case it is not included in the support log, and is relevant at all, I am also exporting with the following postscript you had created for me following an earlier issue:

```
if (Translator.BetterTeX) {
  const tex_fields = Object.keys(item.extraFields.tex).filter(field => entry.has[field])
  const field_order = Object.keys(entry.has).filter(field => !tex_fields.includes(field)).concat(tex_fields)
  for (const field of field_order) {
    // delete and add has the effect of fields being added to the end
    const value = entry.has[field]
    delete entry.has[field]
    entry.has[field] = value
  }
}
```

**Comment by retorquere** [comment]
The postscript is included in the debug log (all BBT settings are), but why did you nor expect the space after the first `\textendash`? Does it render incorrectly?

**Comment by retorquere** [comment]
No problem.
