### ISSUE TITLE
Auto-export not triggered by 'Add item(s) by identifier'

### ISSUE THREAD

**Issue by KaiAragaki** [retorquere/zotero-better-bibtex#2196]
Steps to reproduce:

1. Click the magic wand 'Add item(s) by identifier' button
2. Paste in a DOI link (Example: 10.1016/j.cell.2017.09.007)
3. Check library. No bibtex entry will be exported.

This was done on the 'On Change' mode of automatic export.

Support log: 
26CJBVC7-refs-euc

**Comment by retorquere** [comment]
I cannot reproduce this problem (that is, it works for me). A build will drop here in 10 minutes or so that adds more logging; please reproduce the error on that build and post a new log.

**Comment by KaiAragaki** [comment]
I can no longer reproduce the issue...so I guess issue solved? Thank you for your time!
