### ISSUE TITLE
Unpin Key sometimes fails to work

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#2197]
For some entries, the "unpin key" feature fails to work.

> Alongside a description of your problem/question/feature suggestion, please also include a support log ID.

YLUHWRSB-refs-apse

Right click on the item > "Better BibTeX" > "Unpin BibTeX key" doesn't unpin the key.

**Comment by ryofurue** [comment]
> Can you enable debug logging from the help menu and resubmit a log?

Oops.  Sorry I should've done that first time.

Debug logging enabled, right-click > Unpin, Send Better BibTeX support log.

YA7QVHQ4-refs-apse

> Is this consistently for particular entries?

Yes. I have at least two consistent entries like that.

**Comment by retorquere** [comment]
HuangRX-QiuB:1998 isn't pinned? Does it show in your library as pinned?

**Comment by retorquere** [comment]
Can you send a debug log and check "include cache"?

**Comment by retorquere** [comment]
There is a discrepancy between the key database and your Zotero database, some items are in the key database as pinned that don't have the citekey in the `extra` field. I don't know how that came about (short of direct edits to the zotero database outside zotero, but hardly anyone does that), but it's easy to fix fortunately. Can you do the following:

* go into the [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences)
* find `scrubDatabase` and toggle it to `true`
* restart Zotero

**Comment by ryofurue** [comment]
> Can you do the following:

Thanks. I've done that, but how long do you expect for Zotero to to take to rebuild the deleted database(s)?  So far, it's more than 60 minutes since Zotero was re-launched.  It's stuck at "Better BibTeX: Initializing".  I have 1480 items in the "My Library" view as Zotero reports.

**Comment by retorquere** [comment]
It's supposed to be instant. Can you cmd-quit Zotero, open a shell, and type

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/zotero.txt
```

after it's been stuck at initializing for a minute, cmd-quit again, and attach the generated zotero.txt here.

**Comment by ryofurue** [comment]
So, this is the debug log file:

https://drive.google.com/file/d/1YXxCp5zxGCuJ3rtuZNMq60uTp_LMLfKh/

**Comment by retorquere** [comment]
2885 should take care of that error and allow the scrub to proceed.

**Comment by retorquere** [comment]
cache is included, but not `HuangRX-QiuB:1998`.

Can you cmd-q Zotero, zip the zotero.sqlite and better-bibtex.sqlite databases, and attach the zip here? I need to be able to replicate this.

**Comment by ryofurue** [comment]
Here is the support log right after I tried to unpin `HuangRX-QiuB:1998`

D36ZR784-apse

And here is the zip archive that contains `zotero.sqlite` and `better-bibtex.sqlite` after I quit Zotero:

https://drive.google.com/file/d/1phTftqi0Ga7B8gdMfWbTeLhIxYVXx6l6/

(Actually I didn't know where they are stored.  I searched the disk and found them in ~/Zotero/ . I hope they are the correct ones.)

**Comment by retorquere** [comment]
Those are the right databases

**Comment by retorquere** [comment]
Can you try copying over this database into ~/Zotero:
[bbt.zip](https://github.com/retorquere/zotero-better-bibtex/files/9041869/bbt.zip)

**Comment by retorquere** [comment]
I can't replicate the problem with your database. I can see cleaning is needed, but the clean just succeeds for me.

**Comment by retorquere** [comment]
Can you try build 2908? No need to set `scrubDatabase`.

**Comment by ryofurue** [comment]
> Can you try build 2911?

Thank you for your help! I confirm that this build has fixed the problem. Specifically, I downloaded and installed it and then restarted Zotero.  Then, the problematic entry already acquired the correct (unpinned) key.
