### ISSUE TITLE
inspireHep fetching broken

### ISSUE THREAD

**Issue by zachjweiner** [retorquere/zotero-better-bibtex#2201]
Seems key fetching from inspireHEP hasn't worked for around 6 weeks, at least for arXiv preprints. Tried parsing through the log - I see `InspireHEP says: PID does not exist.` regarding the arXiv DOI, which I don't think INSPIRE supports. (Just searching arxiv:XXXX.XXXXX works.)

I tried deleting the DOI entry and regenerating a log, but I can't seem to get it to behave as I'd expect (not that I understand the logs, I'm just searching for "inspire" in them). I keep seeing references to the most recently imported item in my library and not the item I'm trying to generate the log for. Happy to try suggestions to help debug.

2KJSIB5M-refs-euc

**Comment by zachjweiner** [comment]
That's working - thanks for the fast fix!

**Comment by retorquere** [comment]
Shouldn't have broken in the first place -- I've added `2KJSIB5M-refs-euc` as a testcase to prevent future regressions.
