### ISSUE TITLE
"jieba" filter is not working even it is enabled when dealing with  Chinese words

### ISSUE THREAD

**Issue by JakysonChen** [retorquere/zotero-better-bibtex#2202]
I have enabled “jieba” filter in the preference setting. eg My item has six  Chinese characters, the Pinyin is"ni hao wo ai zhong guo"
My Citation key format is:
auth.lower+date('%Y')+shorttitle.lower.jieba.select(1,2)
But the Citation Key did not select the first two "Chinese words", which supposes to be "auth2022nihao".Now the output is"auth2022nihaowoaizhongguo".

**Comment by JakysonChen** [comment]
[](url
[8N3Y7TVI-refs-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/9021323/8N3Y7TVI-refs-euc.zip)
)

**Comment by JakysonChen** [comment]
[8N3Y7TVI-refs-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/9021327/8N3Y7TVI-refs-euc.zip)

**Comment by JakysonChen** [comment]
Hello, I just figured it out. Looks like when using "jieba", the"auth" or "title" must be the original input. If I assign the number of words of the title, like using "shorttitle(3), the "jieba" filter will not work. The format I use now is:
auth.jieba.select(1,2).lower+year+title.jieba.select(1,2).lower
And it works fine. But the "lower" or "upper" filter is not working with the Chinese words in titles, the citation key looks like this:
haying2020ZhuLuoJiShiJie
Is this normal?
[5Z355HBM-refs-apse.zip](https://github.com/retorquere/zotero-better-bibtex/files/9024659/5Z355HBM-refs-apse.zip)

**Comment by retorquere** [comment]
Jieba only splits, it doesn't transliterate (fold), you still need to apply fold before lower, so something like `clean(false) + auth.jieba(1,2).fold.lower`. Or if you have "Force citation key to plain text"  off, just `auth.jieba(1,2).fold.lower`.
