### ISSUE TITLE
Settings missing

### ISSUE THREAD

**Issue by tim-hilde** [retorquere/zotero-better-bibtex#2203]
Since the last update (6.7.15) the better bibtex menu is missing from the settings pane.

The log id is VB4PWJ4R-euc

**Comment by tim-hilde** [comment]
Unfortunately, this didn't work. I've removed the plugin, restarted zotero, reinstalled and restarted again. I sent another log under ZPLKRGWV-euc

**Comment by retorquere** [comment]
Can you try build 2904?

**Comment by denishem** [comment]
Hi, I had the same problem. Build 2904 fixed it for me.

**Comment by tim-hilde** [comment]
Still not working, also new log: YCWE8J5B-euc

**Comment by tim-hilde** [comment]
Still nothing... TLDJ9DYK-euc

**Comment by retorquere** [comment]
> Still nothing... TLDJ9DYK-euc

On it.

**Comment by retorquere** [comment]
@tim-hilde can you send a log with "send cache" on?

**Comment by hsteinbrecher** [comment]
My window looks similar to @tim-hilde and misses the entries corresponding to the auto exports after I installed test build 6.7.15.2920. With the original built I missed the better bibtex menu in general. Here is the log: F83W2QV5-euc

**Comment by tim-hilde** [comment]
> 🤖 this is your friendly neighborhood build bot announcing [test build 6.7.15.2935](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.15.2935.xpi) ("keep ae- attribs")

The latest build worked! Thanks!

**Comment by hsteinbrecher** [comment]
@retorquere test build 6.7.15.2936 perfectly solved to problem and brought everything missing back 👍
