### ISSUE TITLE
Citation key format: backward compatibility issue.

### ISSUE THREAD

**Issue by aemartinez** [retorquere/zotero-better-bibtex#2204]
This is my citation key format in the previous format:

`[=journalArticle][auth:lower]:[PublicationTitle:skipwords:abbr:lower:alphanum][volume:prefix=-][issue:prefix=_] | [=conferencePaper][auth:lower]:[extra=tex.shortconf:lower:>0][shortyear] | [=conferencePaper][auth:lower]:[conferenceName:skipwords:abbr:lower:alphanum][shortyear] | [auth:lower][shortyear]
`

It worked flawlessly before I updated Zotero and Better Bibtex. 

After updating it does not work and yields the following error:
`Line 1: Unexpected token =`

Support log ID: E5FSGFWZ-refs-euc

**Comment by retorquere** [comment]
Thanks, I have it reproducible. I consider this an urgent issue, but I'm stuck in 8 hours of meetings tomorrow -- very little chance I'll be able to resolve it before Friday.

**Comment by retorquere** [comment]
Please send a new log from build 2926

**Comment by aemartinez** [comment]
Build 2926
Support log ID: HPS452AD-refs-euc

Build 2928
Support log ID: T92EGWX5-refs-euc

In both cases it correctly transformed my old citation key format into the new language.
