### ISSUE TITLE
'add-on appears to be corrupt'

### ISSUE THREAD

**Issue by kvragu** [retorquere/zotero-better-bibtex#2206]
After downloading the xpi, it fails to install, and firefox pops up '...add-on... appears to be corrupt'. The problem persists across firefox and chromium, on two different laptops. I'm running linux mint 20.2. Sorry, I don't know how to include a support log ID.
Alongside a description of your problem/question/feature suggestion, please also include a support log ID for this.

**Comment by kvragu** [comment]
> https://retorque.re/zotero-better-bibtex/support/faq/#add-on-could-not-be-installed-because-it-appears-to-be-corrupt

Thank you, my bad for not checking the faq. Sorted now.

**Comment by retorquere** [comment]
no problem
