### ISSUE TITLE
`better-bibtex` may result in Zotero's `quit unexpectedly`

### ISSUE THREAD

**Issue by iseesaw** [retorquere/zotero-better-bibtex#2208]
My Zotero always quit unexpectedly after I entered some papers or links.

When I run `/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText ` in the terminal, the debug logging showed that `better-bibtex` may be the source of trouble. 

After I disable `better-bibtex`, My Zotero worked well. 

How can I use `better-bibtex` again? Could you please give me some help? Thanks.

**Debug logging in the console:**

```
zotero(3)(+0000000): adding better-sentencecase

zotero(4)(+0000003): Unregistering notifier observer in notifier with id 'itembox_hF'

zotero(3)(+0000004): adding better-sentencecase

zotero(3)(+0000001): BBT started, loading ZoteroPane

zotero(3)(+0000000): ZoteroPane started

zotero(3)(+0000000): BBT: ItemPane loaded

zotero(3)(+0000003): ObsVault Error: Error: vaultpath is not set or does not exist.

zotero(3)(+0000006): ObsVault Error: Error: vaultpath is not set or does not exist.

zotero(3)(+0000008): {better-bibtex} +32 on-idle: idle.observe: { topic: 'idle', data: '18' }

zotero(3)(+0000000): {better-bibtex} +0 on-idle: idle.observe: => resume idle

zotero(3)(+0000000): {better-bibtex} +0 on-idle: queue.resume: start-of-idle

zotero(3)(+0000001): {better-bibtex} +1 on-idle: queue resumed: start-of-idle

zotero(3)(+0000000): {better-bibtex} +0 scheduler: already active

zotero(4)(+0000000): CREATE INDEX tmpSearchResults_LWKuiWCD_itemID ON tmpSearchResults_LWKuiWCD(itemID)

zotero(4)(+0000012): SELECT GROUP_CONCAT(itemID) FROM items WHERE itemID IN (SELECT itemID FROM items WHERE (itemID NOT  IN (SELECT itemID FROM deletedItems) AND itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems))) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?))) AND (itemID IN (SELECT itemID FROM tmpSearchResults_LWKuiWCD) OR itemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_LWKuiWCD)) OR itemID IN (SELECT itemID FROM itemNotes WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_LWKuiWCD))) [1
```

**Part of Logs given by Zotero after quit unexpectedly**

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               zotero [2847]
Path:                  /Applications/Zotero.app/Contents/MacOS/zotero
Identifier:            org.zotero.zotero
Version:               6.0.9 (6.0.9)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-07-12 12:43:49.3689 +0800
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Bridge OS Version:     6.5 (19P5071)
Anonymous UUID:        976BEB77-DD1B-B493-5799-F6E99C6456C9


Time Awake Since Boot: 4200 seconds
```

**Comment by retorquere** [comment]
I don't see any indication in that log snippet that points to BBT as the cause of the crash, just normal startup logging. This happens reliably with BBT installed, and doesn't happen without BBT?

**Comment by iseesaw** [comment]
Yes, this happens reliably with BBT installed, and doesn't happen without BBT.
[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/9090965/BBT.log)

**Comment by retorquere** [comment]
And this is where the log ends abruptly, because Zotero crashes? The problem is I cannot reproduce this, and the only errors I see in the log seem to indicate something relating to Obsidian (the ObsVault log lines). Does a MacOS error dialog pop up? That generally has error info that will not be in the log.

But just generally, Javascript plugins should just not have the capability to bring down Zotero, so there is at least also a Zotero bug involved. What does the memory/cpu load show when this happens?

**Comment by iseesaw** [comment]
Yes, there is a macOS error dialog popping up. I use Obsidian as my Markdown editor and [zotero-markdb-connect](https://github.com/daeh/zotero-markdb-connect) links my Markdown database to Zotero.

If any of the BBT and [zotero-markdb-connect](https://github.com/daeh/zotero-markdb-connect) is disabled, it works well.
