### ISSUE TITLE
Export library to Better CSL JSON/YAML failed when "standard" items included.

### ISSUE THREAD

**Issue by chenyhsu** [retorquere/zotero-better-bibtex#2212]
Trying to export library to Better CSL JSON/Better CSL YAML failed, message: "Error: translation failed".  Export to bibtex is just fine.

And I found that in debug archive:
```
(3)(+0000001): {better-bibtex :error:} +1 worker translation failed, error: Error: Unexpected Zotero Item type "standard"
```

Tried to export without such items, then it works.
Related bug report id:  2KWNZHPG-apse

**Comment by retorquere** [comment]
Can you get me a log with the item in question included (select that item, right-click, send BBT log from that menu).

**Comment by chenyhsu** [comment]
BBT log id: CNFD7KYD-refs-apse. (From right click menu).

**Comment by retorquere** [comment]
2964 should fix it.

**Comment by chenyhsu** [comment]
Confirmed `test build 6.7.16.2964` works for both Better CSL JSON and YAML.
Also tested re-import exported items, seems no info got lost.
