### ISSUE TITLE
Apply Title Casing to tex.subtitle entry on export?

### ISSUE THREAD

**Issue by PlayfulPan** [retorquere/zotero-better-bibtex#2213]
Hi,

One of my entries on Zotero has both a title and a subtitle. I have included the subtitle under tex.subtitle label in the extra field. Is there an easy way to get BBT to apply the standard title case conversion and bracing to tex.subtitle entries as it does for other title-like entries? 

Specifically, if the subtitle entry is:
`
tex.subtitle: The rigged Hilbert space formulation of quantum mechanics
`
then the output in the .bib file when exporting with Better BibLaTex is
`
subtitle = {The rigged Hilbert space of quantum mechanics}
`

However, if I list it under a different title type, such as tex.maintitle, then
`
tex.maintitle: The rigged Hilbert space of quantum mechanics
`
becomes
`
maintitle = {The Rigged {{Hilbert}} Space of Quantum Mechanics}
`
with proper title casing and bracing applied. This is the desired behavior I would to have happen for tex.subtitle entries. Is there some easy postscript I can use to accomplish this? I've looked through other issues here, but I can't find much regarding how to apply title casing to specific entries.

Any help would be appreciated!

**Comment by PlayfulPan** [comment]
Here's the support log for the specific entry in question.
[IC62ZBS9-refs-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/9128673/IC62ZBS9-refs-euc.zip)

**Comment by retorquere** [comment]
It was an unintentional beneficial side-effect. A new build will drop here in 10 minutes (assuming all tests pass) that adds:

* `subtitle` is now included in the now-intended side effect
* you can force this behavior where it isn't automatic by including any capital in the prefix, eg `TeX.subtitle: ...`
* the existing release would have allowed (and the new build still allows) this in a postscript:

```
if (Translator.BetterTeX) {
  if (entry.has.subtitle) entry.add({ ...entry.has.subtitle, caseConversion: true })
}
```

**Comment by retorquere** [comment]
BTW it is easier for me if you just let the error reporter submit the logs rather than attaching them here. Attaching works of course but I have built tools that pull submitted logs into a testcase automatically.

**Comment by retorquere** [comment]
Can you test build 2969

**Comment by PlayfulPan** [comment]
Sorry for the late reply!

I did test it and it works great.

You're doing God's work!

Thanks!
