### ISSUE TITLE
intermittent setTimeout failure (object not initialized)

### ISSUE THREAD

**Issue by SoftlySpoken** [retorquere/zotero-better-bibtex#2215]
I've run into an error when trying to Export Item in the Better BibTeX format. The error message is simply "An error occurred while trying to export the selected file." (Zotero Forum discussion thread [here](https://forums.zotero.org/discussion/comment/412845#Comment_412845))

After a restart the export works normally again, but after another restart the error reappeared. (The error occurs the first time I export an item after that restart; after that I tried exporting multiple times, and the same error message popped up.)

I successfully generated a log this time (only including one item export). Support log ID: DXPKED2U-apse

However, when I restart again, a notification says Zotero is automatically installing an update, and afterwards exporting works fine again. I'm not sure if this is because the update fixed it?

**Comment by retorquere** [comment]
Can you try build 2975?

**Comment by SoftlySpoken** [comment]
> Can you try build 2975?

Just installed, working without issue as of now! Will come back if there's any problem, thanks a lot.
