### ISSUE TITLE
Export JSON file with "incorrect" format of note item

### ISSUE THREAD

**Issue by R4D0M123** [retorquere/zotero-better-bibtex#2216]
I'm using BBT to `Export collection` for markdown note in format of `BetterBibTex JSON`.
In the json file produced, notes with images has a uri in the form of `http://zotero.org/user...` rather then the expect form of 
 `zotero://...`. This causes difficulty in managing notes with images.

I'm not sure this is a bug/feature or I just miss click on some option, and I can not found a drop down or button in the preferences to address that.

I'm pretty sure this is not related to a specific item except the note containing a image.

Log Num:IH7S9AJV-refs-apse
Relese Edition :6.7.16

**Comment by retorquere** [comment]
BBT-JSON is mostly just a dump of the objects that translators get handed by Zotero. I am open to adding the select link if you want. I am surprised to see http:// rather than https://.

What kind of problem does this cause? Isn't the image available on the given URL?

**Comment by R4D0M123** [comment]
I'm using a Obsidian plugin to automate the note-taking process, the URL there point to my online library and (through a Chrome browser) go to the `www.zotero.org/<username>/item-list` page. This causes the plugin I use in Obsidian can not find the image.

I personally prefer keep everything localy on my PC, and I ran out of space in zotero's online storge, the image is not likly to appear on that end of the URL.

The function you mention should fix my problem.

**Comment by retorquere** [comment]
Oh I thought it would be an additional field like the select link, but it'd require decoding and changing the note itself. What Obsidian plugin is this? Maybe it could be added there? Otherwise I might look at making postscripts available for BBTJSON.

**Comment by R4D0M123** [comment]
I'm using `BibNote Formatter`, Link : `https://github.com/stefanopagliari/bibnotes`.It specific use the json file from `BBT`.

The workflow is using the json file produced by `BBT` form given Zotero collection, and the `BibNote` plugin for Obsidian read that json file and auto-genarate `.md` file, include notes.

**Comment by retorquere** [comment]
The BBT JSON format does little more than dump what Zotero hands translators; it's a close representation of Zotero's internal state, without much processing applied. If BibNote uses BBT-JSON to get this so that it can apply processing, it doesn't sound strange to me that it would do this processing too.

**Comment by R4D0M123** [comment]
So it a json processing issue then.😂

I will try to file a issue to `BibNote` see if any processing is possible on that end, but a out-of-box local uri is still nice to have, please consider adding that feature.

Thanks for your time and attention.

**Comment by retorquere** [comment]
Not really a JSON processing issue. JSON is just the format in which the translator writes the results; you can get the same content with the RDF translator. The issue is HTML-in-HTML-attribute processing.

**Comment by R4D0M123** [comment]
Update:The author of `BibNote` has fix this as a bug in newer version.
