### ISSUE TITLE
Including extra fields in .bib export

### ISSUE THREAD

**Issue by daaaaaaaaaniel** [retorquere/zotero-better-bibtex#2217]
Support Log: `L667EZXS-euc`

I've begun adding relevant fields to the Extras section of my Zotero items. I want these extra fields to be included in the .bib export, but I'm having trouble making it happen. 

By and large I'm sticking to the CSL fields covered on the documentation site, under the section on [Label/variable list](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/#labelvariable-list "Extra fields :: Better BibTeX for Zotero") on the "Extra fields" page. According to that page, "*extra-fields are available to postscripts as `extra.kv.<variable-name>`.*"

Here is the postscript I'm currently using in a helpless attempt to debug. I'm trying to figure out how to include the chapter-number value in the .bib export. I must be doing it totally wrong because my .bib file doesn't include any items with a chapter field (nor chapter1, chapter2, chapter3, etc).

```javascript
if (Translator.BetterTeX) {
  if (item.extra.kv.chapter-number) {
    entry.add({ name: 'chapter', value: item.extra.kv.chapter-number});
  }
  if (item.chapter-number) {
    entry.add({ name: 'chapter1', value: item.chapter-number});
  }
  if (item.chapter) {
    entry.add({ name: 'chapter2', value: item.chapter});
  }
  if (item.extra.kv.chapter) {
    entry.add({ name: 'chapter3', value: item.extra.kv.chapter});
  }
  if (item.extra.kv.session) {
    entry.add({ name: 'chapter4', value: item.extra.kv.session});
  }
  if (item.session) {
    entry.add({ name: 'chapter5', value: item.session});
  }
}
```

Ideally, I want every CSL value that I include in the Extra field to be present in the .bib export. But for starters I'll be happy if it includes the chapter-number and the container-title-short.

**Comment by retorquere** [comment]
I need a debug log that includes the entry you're trying to export. Right-click the entry and send a debug log from the popup menu. Such reports will have `-refs` in the ID.

**Comment by retorquere** [comment]
But for starters, `item.extra.kv.chapter-number` should be `item.extra.kv['chapter-number']`; javascript identifiers cannot have minus signs in them.

**Comment by daaaaaaaaaniel** [comment]
debug log: `CBMHRZ89-refs-euc`

This is the postscript I'm using:
```javascript
if (Translator.BetterTeX) {
// This adds bdsk-file-x fields for BibDesk
  if (!Translator.options.exportFileData && item.attachments && item.attachments.length) {
    item.attachments.forEach((att, i) => {
      entry.add({ name: `bdsk-file-${i + 1}`, value: (att.saveFile ? att.defaultPath : '') || att.localPath, enc: 'verbatim' })
    })
// This uses relative paths instead of absolute
    for (const att of item.attachments) {
      if (att.localPath) {
        att.localPath = att.localPath.replace(RegExp("^\/.*?\/.*?\/"), "~/")
      }
    }
    entry.add({ name: 'file', value: item.attachments, enc: 'attachments' })
    return { cache: false }
  }
// This does absolutely nothing, apparently… 
  if (item.extra.kv['chapter-number']) {
    entry.add({ name: 'chapter', value: item.extra.kv['chapter-number']});
  }
}
```

**Comment by retorquere** [comment]
That's a quirk you could hardly be expected to know -- the extra fields are available in two types of exporters, the CSL exporters and the TeX exporters. In the CSL exporters the `extra` fields are available by their CSL name (in this case, `chapter-number`. In the TeX exporters though, the extra fields are available by their Zotero name (in this case, `session`). You can specify them in either mode or by its english label in the `extra` field, and BBT will try to map them to the target mode as needed; The mapping is available [here](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/). If there is no mapping (eg `code number` has no CSL equivalent), the field stays in its stated format (zotero or CSL, not the label).

Two other points aside from that: the extra variables are available as `item.extraFields.kv` or `extra.kv`, not `item.extra.kv`; `item.extra` is what remains of the `extra` field after the `extra`-variables have been extracted, it is a string, and strings cannot have other properties like this.

If an item has attachments, the `return { cache: false }` will prevent any later code in the postscript from running, you might want to do

```
if (Translator.BetterTeX) {
  let cache = true
  // This adds bdsk-file-x fields for BibDesk
  if (!Translator.options.exportFileData && item.attachments && item.attachments.length) {
    item.attachments.forEach((att, i) => {
      entry.add({ name: `bdsk-file-${i + 1}`, value: (att.saveFile ? att.defaultPath : '') || att.localPath, enc: 'verbatim' })
    })
    // This uses relative paths instead of absolute
    for (const att of item.attachments) {
      if (att.localPath) {
        att.localPath = att.localPath.replace(RegExp("^\/.*?\/.*?\/"), "~/")
      }
    }
    entry.add({ name: 'file', value: item.attachments, enc: 'attachments' })
    cache = false
  }
  // This does absolutely nothing, apparently…
  if (item.extra.kv['chapter-number']) {
    entry.add({ name: 'chapter', value: item.extra.kv['chapter-number']});
  }

  return { cache }
}
```

**Comment by daaaaaaaaaniel** [comment]
@retorquere Thanks for trying to shed some light on this! But I still feel like I'm grokking around in the dark. I must be misunderstanding because it seems like you gave two contradictory pieces of advice. First you [said](https://github.com/retorquere/zotero-better-bibtex/issues/2217#issuecomment-1191075334) that 
>`item.extra.kv.chapter-number` should be `item.extra.kv['chapter-number']`  

then you [said](https://github.com/retorquere/zotero-better-bibtex/issues/2217#issuecomment-1191528054) 
> the extra variables are available as `item.extraFields.kv` or `extra.kv`, not `item.extra.kv`; `item.extra` is what remains of the extra field after the `extra`-variables have been extracted, it is a string, and strings cannot have other properties s like this.

So should I use `item.extra.kv['chapter-number']` or not? You posted a code snippet that uses _item.extra.kv_['chapter-number']) - which is the same name I was using in the sample that I posted. When I ran it (using both your version and my version), there were no chapter fields in my exported .bib. Then, based on how I understand the rest of your response, I tried replacing _item.extra.kv_['chapter-number']) with  `item.extraFields.kv['chapter-number'])`, yet still no chapter fields were generated in my .bib export.

For reference, the item associated with debug log `CBMHRZ89-refs-euc` had these three fields in the Extras field (or possibly chapter 2… can't remember exactly but shouldn't matter). It's represenative of the way I use the Extra field across my whole library.
```
chapter-number: 3
DOI: 10.2307/j.ctv1fcf88w.7
container-title-short: The World Computer
```

**Comment by retorquere** [comment]
Yeah sorry that was sloppy, it's been one of those days.... You should be using `item.extraFields.kv` (which may have fields removed from it as the regular export uses them) or `extra.kv` (which has all fields present in the `extra` field). I've updated the code above.

I realize the mapping between `chapter-number` and `session` (`session` is not my choice, I take this from Zotero) is confusing, but the remapping is used in the normal control flow of BBT output production, and I need them in their context-native formats.
