### ISSUE TITLE
Export multi-word extra field with specific formatting

### ISSUE THREAD

**Issue by jdossgollin** [retorquere/zotero-better-bibtex#2222]
I have a reference with a long institutional author, and I want to use the `shortauthor` field (in Biblatex / Biber) so that a short author is used for the in-text citation.

This works well! For example, with an author field that is United States Army Corps of Engineers, Galveston District, I can set `tex.shortauthor=USACE` in the `Extra` field and my `.bib` file has a line `shortauthor={USACE}`. Great!

However, if my `author` is `United States Army Corps of Engineers Fort Worth District` and I want the short version to be "USACE Fort Worth", this is harder. I set `tex.shortauthor=USACE Fort Worth` but the `.bib` file (using better biblatex) is `shortauthor={USACE Fort Worth}`. Since there is just the one set of brackets, biblatex formats it wrong (with my current biblatex settings it drops all words after the first.)

How do I change the line in the extra field so that my `.bib` field is `shortauthor={{USACE Fort Worth}}` (i.e, double bracket)? From the documentation [here](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) I wasn't able to figure out how to do this.

Thanks!

**Comment by retorquere** [comment]
Just include the extra braces:

```
tex.shortauthor={USACE Fort Worth}
```

**Comment by jdossgollin** [comment]
If I do that I get `shortauthor = {\{PBL Netherlands\}}`

Not sure if relevant but I have the "export unicode as plain-text latex commands" box checked

**Comment by retorquere** [comment]
Can you right-click said entry and send a debug log? This is why the bot asks for a debug log BTW. It makes sure that we are looking at exactly the same thing so I don't have to guess.

**Comment by jdossgollin** [comment]
Support log ID: UHGIIX29-refs-euc

This is actually for a slightly different reference -- desired behavior is `{{PBL Netherlands}}` rather than `{{USACE Fort Worth}}` but otherwise the same problem

Thanks

**Comment by retorquere** [comment]
This is what threw me off; in the original message you say

> I set `tex.shortauthor=USACE Fort Worth`

but in `UHGIIX29-refs-euc` you have

> `tex.shortauthor: {PBL Netherlands}`

The difference is the `:` vs the `=`. If you use `=`, you will get what you need. It isn't very explicitly highlighted on the [extra vars page](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) I'll admit:

> Finally, you can use `=` instead of `:` as a delimiter, and that will indicate to BBT that what follows the = is “raw LaTeX”; BBT will not do any escaping and just copy it out unchanged.

**Comment by jdossgollin** [comment]
That works, thanks! I just copied the syntax from the automatically generated citation key field, apologies for the incorrect original message (hence the logs 😄).

**Comment by retorquere** [comment]
Hence indeed the logs
