### ISSUE TITLE
Performance impact of quick copy with BBT

### ISSUE THREAD

**Issue by Michael-N-N** [retorquere/zotero-better-bibtex#2229]
I have set Quick Copy of Zotero to ‘BBT Quick copy Eta template’. This setting has a noticeable negative impact on the performance when using drag and drop within Zotero, e.g. to add an item to a collection or to add a tag to an item. 
Compared to a situation when quick copy is set to a citation style the lag is somewhere between half and a few seconds. It gets worse if more items are selected to drag and drop.

I am wondering if there is anything I can do to get a better performance?

Log-File: E2MLQWLZ-euc

Thanks in advance,
Michael

**Comment by retorquere** [comment]
I'll exempt quick copy from background export -- background export has a fairly long ramp-up time, and quick-copy doesn't really benefit.

**Comment by retorquere** [comment]
Can you try build 3016?

**Comment by Michael-N-N** [comment]
I have tested it but sadly it is no real improvement. I'd say it is more or les the same time lag. Do you want to have a new log file?

**Comment by retorquere** [comment]
No, I'll create a build that does more logging first

**Comment by retorquere** [comment]
Can you get me a log from 3021 (with debug logging on, after reproducing the problem)

**Comment by Michael-N-N** [comment]
Here it is : NB8RVKRD-euc

**Comment by retorquere** [comment]
I have it reproducible. Wow, that's pretty bad. It will be a bit of work to fix this though. It's pulling in code it shouldn't, and the resulting translator is too big.

**Comment by retorquere** [comment]
I think you'll find build 3029 much improved

**Comment by Michael-N-N** [comment]
Perfect! The lagging is gone. Thank you for the fix!

**Comment by retorquere** [comment]
Thanks for the confirmation, and for reporting the issue of course -- you can just keep using this build, I'm prepping a new release to include it. You can leave this issue open, I'll close it when I get out the new release. You don't have to do anything to upgrade later, that is automatic.
