### ISSUE TITLE
better bibtex for zotero is incompatible with zotero 6.0-beta.1+8c846468f on Linux

### ISSUE THREAD

**Issue by zain-raza** [retorquere/zotero-better-bibtex#2235]
Hi all

No debug ID for this, tried to install build 2314 from this link: https://github.com/retorquere/zotero-better-bibtex/issues/2099 but that didn't work for me. I got the following error:

"The add-on "%S" could not be installed. It may be incompatible with this version of Zotero."

Linux Manjaro
Zotero-beta version 6.0-beta.1+8c846468f
BBT version: 6.7.19

**Comment by retorquere** [comment]
That is both a very old zotero beta, and an old BBT build. Neither are supported, I only support the latest zotero/zotero-beta version, and build 2314 (which as based on BBT 6.4.2) is no longer available for download.

There is no supported version for zotero-beta 6.0-beta.1+8c846468f. Does BBT 6.7.19 not install on zotero-beta 6.0.12.3+d03b0a716? Or do you not have access to the latest beta?

**Comment by zain-raza** [comment]
Unfortunately it does not seem that I have access to the latest through my package manager. Let me see if I can get the latest build directly. Thanks for the quick response!
