### ISSUE TITLE
Limits to no. of auto-updated bibliographies? 

### ISSUE THREAD

**Issue by statzhero** [retorquere/zotero-better-bibtex#2239]
This is not an issue as such, rather a preemptive question for integrating VS Code/Latex with Zotero: is it recommended 

1. to create one auto-updated bibliography in a centralized location or 
2. to create a separate auto-updated bibliography for each project? 

I'm wondering if option 2 will eventually run into performance issues.

Many thanks!

**Comment by statzhero** [comment]
Sorry, I'm not sure if this is the right place to ask the question -- please redirect if not appropriate.

**Comment by retorquere** [comment]
Both should work, and one isn't necessarily more performant than the other. Personally I've always used the second scenario.
