### ISSUE TITLE
Better BibTeX for Zotero is incompatibile with Zotero 6.0.3

### ISSUE THREAD

**Issue by macdems** [retorquere/zotero-better-bibtex#2243]
Better BibTeX for Zotero seems incompatibile with the newest Zotero 6.

I kindly ask to fix it immitiately, as this is a major issue rendering Zotero unusable for me!

**Comment by macdems** [comment]
It works with Zotero 6.0.10, so closing the issue.

**Comment by talestomaz** [comment]
Indeed, thanks! I don't know why Manjaro didn't update Zotero automatically... I have to install it through another package `zotero-bin`.
