### ISSUE TITLE
Installation in Zotero 6 not working

### ISSUE THREAD

**Issue by talestomaz** [retorquere/zotero-better-bibtex#2244]
I have tried to install the add-on, but I get the message: "The add-on "Better BibTex for Zotero" could not be installed. It may be incompatible with this version of Zotero."

Could you help me spot what is going wrong?

Add-on file: zotero-better-bibtex-6.7.19.xpi

See Zotero Debug file attached. [D1298517107.txt](https://github.com/retorquere/zotero-better-bibtex/files/9308089/D1298517107.txt)

**Comment by connorjward** [comment]
I think this issue was raised in https://github.com/retorquere/zotero-better-bibtex/issues/2243. Basically 6.0.3 doesn't work but if you can upgrade to 6.0.10 you should be fine.

(I just hit the same issue and this resolved it for me)

**Comment by talestomaz** [comment]
Indeed, thanks! I don't know why Manjaro didn't update Zotero automatically... I had to install 6.0.10 through another package `zotero-bin`.
