### ISSUE TITLE
Auto Abbreviation of Proceedings Title

### ISSUE THREAD

**Issue by paul-ang** [retorquere/zotero-better-bibtex#2245]
For journal paper, the Publication field can be automatically abbreviated when using Better BibTeX export. Can I do the same with the conference paper's Proceedings Title field? 

Thanks.

**Comment by paul-ang** [comment]
Sorry, the support log ID is NMRZ9LV2-refs-apse. The Proceedings title is _Proceedings of the Medical Imaging with Deep Learning_. After exporting using the Better BibTex style, I am hoping the title can be automatically abbreviated (similar to journal publication title), e.g., _Proc. Med. Imag. Deep Learn._

**Comment by paul-ang** [comment]
The test build works great. Thanks so much!

**Comment by retorquere** [comment]
Thanks for reporting this, I've scheduled a release build.

**Comment by paul-ang** [comment]
Hi @retorquere , it looks like the auto abbrev feature only works for that specific entry (log: NMRZ9LV2-refs-apse). I have submitted a new support log for a conference paper entry that you can test on. Log: BVLEGQCW-refs-apse

Please find attached a screenshot that shows the exported contents for both entries. Note that both entries are conference paper (i.e., Item Type = Conference Paper). Hence, it should be `@inproceedings` in the .bib file. However, the entry that is automatically abbreviated is exported with `@article`. 

Please let me know if you need more information.

Thank you.

![Screen Shot 2022-08-18 at 11 54 54 am](https://user-images.githubusercontent.com/17742813/185275087-340f35bb-c7d3-4342-a568-96a48b235efe.png)

**Comment by retorquere** [comment]
> it looks like the auto abbrev feature only works for that specific entry

That is simply untrue. It works for many items, just not `inproceedings` items (right now at least). We can talk about that, but the automatic journal abbreviator as it stands works for journals, and conference proceedings aren't really journals. The item in `NMRZ9LV2-refs-apse` is treated as an article because it has an arXiv ID. A side effect of that is that it's treated as an article in a journal.

That said, proceedings titles do look journal-ish, 3108 will treat them that way.

**Comment by paul-ang** [comment]
Thanks for the explaination. The new build automatically abbreviates the title for `inproceedings` items now, which is what I want. Thanks for that.

Is it possible to treat an entry as `inproceedings` if the Item Type = Conference Paper? Rather than treated as an article if the arXiv ID is present.

**Comment by retorquere** [comment]
I was mistaken -- it's being exported as an `@article` because you have `type: article` in the `extra` field.

**Comment by paul-ang** [comment]
Thanks for the clarification.
