### ISSUE TITLE
Using zotero.lua .md to .docx to add canonic number after comma without 'p.'

### ISSUE THREAD

**Issue by mtorressahli** [retorquere/zotero-better-bibtex#2248]
Hi,

First of all, many thanks for all you do; it's amazingly valuable work.

My issue: I'm exporting **.md to .docx** with pandoc and **zotero.lua**, and I need a reference to use a canonic number (Bekker) instead of, for example, page number but have not been able to figure out how to do so.

```
Input:            Aristotle [-@Aristotle2006Rhetoric, 1365b]
Desired output:   Aristotle (ca. 322 B.C.E./2006, 1365b)
Obtained output:  Aristotle (ca. 322 B.C.E./2006, p. 1365b)
```

**I suppose setting ", 1365b" as suffix would suffice**, but I do not know how to do that without it being interpreted as page reference.

Not sure if a debug ID would be useful, but here it is:

debug ID: I448AYC2-refs-euc

Many thanks in advance

Best
Manuel.

**Comment by retorquere** [comment]
At what point do you get `Aristotle (ca. 322 B.C.E./2006, p. 1365b)`? If it's directly after the conversion from `.md` to `.docx`, that text is just a placeholder.

At any point after conversion, if you choose the bibliography style using the zotero button in Word and refresh the bibliography, it will be replaced with the correct style.

**Comment by mtorressahli** [comment]
Hi, many thanks for the quick reply!

From `Aristotle [-@Aristotle2006Rhetoric, 1365b]` in the .md, I get `<Do Zotero Refresh: [@Aristotle2006RhetoricTheory, 1365b]>` in the .docx, which Zotero transforms into `Aristotle (ca. 322 B.C.E./2006, p. 1365b)` with APA7.

Full .docx field code after export, before Zotero refresh:

```
ADDIN ZOTERO_ITEM CSL_CITATION {"cita-ti-onItems":[{"prefix":"","locator":"1367b","uris":["http://zotero.org/users/5204543/items/SY9NYTH4"],"suppress-au-thor":true,"uri":["http://zotero.org/users/5204543/items/SY9NYTH4"],"itemData":{"original-date":{"literal":"circa 323 B.C.E."},"edition":"2","call-number":"PN173.A7 K46 2007","source":"Library of Congress ISBN","language":"en","number-of-pages":"337","id":"Aristotle2006RhetoricTheory","ISBN":"978-0-19-530508-1 978-0-19-530509-8","event-place":"New York, NY, USA","citation-key":"Aristotle2006RhetoricTheory","type":"book","translator":[{"family":"Kennedy","given":"George Alexander"}],"editor":[{"family":"Kennedy","given":"George Al-exander"}],"author":[{"literal":"Aristotle"}],"title-short":"On rheto-ric","publisher":"Oxford University Press","note":"OCLC: ocm62282427","issued":{"date-parts":[[2006,6]]},"title":"On rhetoric: a theory of civic discourse","publisher-place":"New York, NY, USA"},"id":11631}],"citationID":"00000001","schema":"https://github.com/citation-style-language/schema/raw/master/csl-cita-tion.json","properties":{"noteIndex":0,"formattedCitation":"[@Aristotle2006RhetoricTheory, 1367b]"}}   
```

**Comment by retorquere** [comment]
You'd have to ask Zotero. After the conversion, BBT is no longer involved in any way.

**Comment by mtorressahli** [comment]
Many thanks again. I'll do that then. In any case, is there a way of 'forcing' a string (", 1365b") to be a suffix?

**Comment by retorquere** [comment]
I think if you omit the comma, it will treat the remainder will be treated as the suffix.

**Comment by mtorressahli** [comment]
Hi

Sorry for the late reply. The issue seems to be related to how the filter interprets the first thing after a comma. 

The filter seems to interpret any first thing after a comma as a page reference. I'd like to input a suffix with a comma that is not a page reference, sometimes starting with number. Therefore including the comma and the first elements as parts of the suffix. The filter exports them to 'locator' by default. Would it be possible to specify that the first thing after the comma is not a locator/page reference?

I've tried four different formats; these are the results:

## Input

[@Billig1991IdeologyOpinions, one suffix after comma]
[@Billig1991IdeologyOpinions  2 suffix without comma]
[@Billig1991IdeologyOpinions, 3 suffix after comma with number]
[@Billig1991IdeologyOpinions, 4 oneWordSuffixWNo]

## How I'd like/expect them to look

(Billig, 1991, one suffix after comma) 
(Billig, 1991 2 suffix without comma) 
(Billig, 1991, 3 suffix after comma with number)
(Billig, 1991, 4 oneWordSuffixWNo)

## How they look

(Billig, 1991, p. one suffix after comma) 
(Billig, 1991 2 suffix without comma) 
(Billig, 1991, p. 3 suffix after comma with number)
(Billig, 1991, p. 4 oneWordSuffixWNo)


## Fields

1. <Do Zotero Refresh: [@Billig1991IdeologyOpinions, one suffix after comma]>
2. <Do Zotero Refresh: [@Billig1991IdeologyOpinions 2 suffix without comma]>
3. <Do Zotero Refresh: [@Billig1991IdeologyOpinions, 3 suffix after comma with number]>
4. <Do Zotero Refresh: [@Billig1991IdeologyOpinions, 4 oneWordSuffixWNo]>

## Fields' code

1. { ADDIN ZOTERO_ITEM CSL_CITATION {"citationID":"00000001","schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json","properties":{"formattedCitation":"[@Billig1991IdeologyOpinions, one suffix after comma]","noteIndex":0},"citationItems":[{"uris":["http://zotero.org/users/5204543/items/LSENZGP8"],"suffix":" suffix after comma","uri":["http://zotero.org/users/5204543/items/LSENZGP8"],"id":154,"prefix":"","itemData":{"author":[{"given":"Michael","family":"Billig"}],"language":"en","citation-key":"Billig1991IdeologyOpinions","title-short":"Ideology and opinions","call-number":"HM251 .B47459 1991","note":"MAG ID: 386349523","event-place":"London, England","source":"Library of Congress ISBN","type":"book","publisher-place":"London, England","collection-title":"Loughborough studies in communication and discourse","issued":{"date-parts":[[1991]]},"ISBN":"978-0-8039-8332-8 978-0-8039-8331-1","id":"Billig1991IdeologyOpinions","publisher":"Sage Publications","number-of-pages":"216","title":"Ideology and opinions: studies in rhetorical psychology"},"locator":"one"}]}   }

2. { ADDIN ZOTERO_ITEM CSL_CITATION {"citationID":"00000002","schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json","properties":{"formattedCitation":"[@Billig1991IdeologyOpinions 2 suffix without comma]","noteIndex":0},"citationItems":[{"uris":["http://zotero.org/users/5204543/items/LSENZGP8"],"suffix":" 2 suffix without comma","uri":["http://zotero.org/users/5204543/items/LSENZGP8"],"prefix":"","itemData":{"author":[{"given":"Michael","family":"Billig"}],"language":"en","citation-key":"Billig1991IdeologyOpinions","title-short":"Ideology and opinions","call-number":"HM251 .B47459 1991","note":"MAG ID: 386349523","event-place":"London, England","source":"Library of Congress ISBN","type":"book","publisher-place":"London, England","collection-title":"Loughborough studies in communication and discourse","issued":{"date-parts":[[1991]]},"ISBN":"978-0-8039-8332-8 978-0-8039-8331-1","id":"Billig1991IdeologyOpinions","publisher":"Sage Publications","number-of-pages":"216","title":"Ideology and opinions: studies in rhetorical psychology"},"id":154}]}   }

3. { ADDIN ZOTERO_ITEM CSL_CITATION {"citationID":"00000003","schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json","properties":{"formattedCitation":"[@Billig1991IdeologyOpinions, 3 suffix after comma with number]","noteIndex":0},"citationItems":[{"uris":["http://zotero.org/users/5204543/items/LSENZGP8"],"suffix":" suffix after comma with number","uri":["http://zotero.org/users/5204543/items/LSENZGP8"],"id":154,"prefix":"","itemData":{"author":[{"given":"Michael","family":"Billig"}],"language":"en","citation-key":"Billig1991IdeologyOpinions","title-short":"Ideology and opinions","call-number":"HM251 .B47459 1991","note":"MAG ID: 386349523","event-place":"London, England","source":"Library of Congress ISBN","type":"book","publisher-place":"London, England","collection-title":"Loughborough studies in communication and discourse","issued":{"date-parts":[[1991]]},"ISBN":"978-0-8039-8332-8 978-0-8039-8331-1","id":"Billig1991IdeologyOpinions","publisher":"Sage Publications","number-of-pages":"216","title":"Ideology and opinions: studies in rhetorical psychology"},"locator":"3"}]}   }

4. { ADDIN ZOTERO_ITEM CSL_CITATION {"citationID":"00000004","schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json","properties":{"formattedCitation":"[@Billig1991IdeologyOpinions, 4 oneWordSuffixWNo]","noteIndex":0},"citationItems":[{"uris":["http://zotero.org/users/5204543/items/LSENZGP8"],"suffix":" oneWordSuffixWNo","uri":["http://zotero.org/users/5204543/items/LSENZGP8"],"id":154,"prefix":"","itemData":{"author":[{"given":"Michael","family":"Billig"}],"language":"en","citation-key":"Billig1991IdeologyOpinions","title-short":"Ideology and opinions","call-number":"HM251 .B47459 1991","note":"MAG ID: 386349523","event-place":"London, England","source":"Library of Congress ISBN","type":"book","publisher-place":"London, England","collection-title":"Loughborough studies in communication and discourse","issued":{"date-parts":[[1991]]},"ISBN":"978-0-8039-8332-8 978-0-8039-8331-1","id":"Billig1991IdeologyOpinions","publisher":"Sage Publications","number-of-pages":"216","title":"Ideology and opinions: studies in rhetorical psychology"},"locator":"4"}]}   }

**Comment by retorquere** [comment]
How would you specify this? `[@Billig1991IdeologyOpinions, IV]` could legitimately be `(Billig, 1991, p. IV)`, so it's not just detecting a number. How does pandoc render `[@Billig1991IdeologyOpinions, one suffix after comma]`?

**Comment by njbart** [comment]
See https://pandoc.org/MANUAL.html#extension-citations, in particular:
> In complex cases, you can force something to be treated as a locator by enclosing it in curly braces or prevent parsing the suffix as locator by prepending curly braces:
>```
>[@smith{ii, A, D-Z}, with a suffix]
>[@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]  
>[@smith{}, 99 years later]  
>```

**Comment by mtorressahli** [comment]
Many thanks to both. I'll use the curly braces as pointed by @njbart; sorry for not noting that was in the manual. As suggested by @retorquere, I've rendered seven alternatives into pdf with pandoc --cite-proc (using xelatex and apa7.csl). I see that the ones starting with arabic numerals (with or without a comma) are converted into page references.

1. [@Billig1991IdeologyOpinions, one suffix after comma]
2. [@Billig1991IdeologyOpinions 2 suffix without comma]
3. [@Billig1991IdeologyOpinions, 3 suffix after comma with number]
4. [@Billig1991IdeologyOpinions, iv Oneword]
5. [@Billig1991IdeologyOpinions, five]
6. [@Billig1991IdeologyOpinions, vi]
7. [@Billig1991IdeologyOpinions a seventh case without comma]

1. (Billig, 1991, one suffix after comma)
2. (Billig, 1991, p. 2 suffix without comma)
3. (Billig, 1991, p. 3 suffix after comma with number)
4. (Billig, 1991, iv Oneword)
5. (Billig, 1991, five)
6. (Billig, 1991, vi)
7. (Billig, 1991 a seventh case without comma)

**Comment by njbart** [comment]
Hmm, I’m seeing the same thing wrt citeproc. Possibly a regression. Might merit a bug report at https://github.com/jgm/pandoc/.

**Comment by retorquere** [comment]
Yeah that's what I'd want, assuming I can get it done. Lua has really anemic text-matching plumbing, and I want this dependency-free.

**Comment by mtorressahli** [comment]
Many thanks again.

The issue in citeproc has just been addressed at https://github.com/jgm/pandoc/commit/35a3fb7e833c01f0352914a23727dff0145e7304 in case that's of any help.

**Comment by retorquere** [comment]
@mtorressahli can you attach the doc you're compiling to this issue, and submit a debug ID by selecting your whole library, right-clicking it, and choose BBT -> Send debug log (assuming you're OK with me adding these to my test suite).

**Comment by retorquere** [comment]
Dummy doesn't matter as long as

1. it contains all relevant samples, and 
2. it actually does match the items selected in the debug log

Fully ideal would be if you could compile it to an `.odt` file with live references, edit the `.odt` file with Libreoffice to have the suffixes and locators as you would want them to be, and attach that odt here. Otherwise you will have to walk me through it.

**Comment by mtorressahli** [comment]
I've attached the files. Couldn't find the saved log file in my computer after generating the bug report; but I got the Debug ID ENFMY8YA-refs-euc

[05_Analysis_test.odt](https://github.com/retorquere/zotero-better-bibtex/files/9548610/05_Analysis_test.odt)
[05_Analysis_test.md](https://github.com/retorquere/zotero-better-bibtex/files/9548611/05_Analysis_test.md)

LEt me know if it would be useful to make changes in any of the files or generate new ones

**Comment by retorquere** [comment]
Log is preferred actually. Superb, thanks for the test case, this will make it much easier to fix.

**Comment by retorquere** [comment]
Strange, you have double ISBNs in those entries, and when I compile using pandoc those end up in the citation, but they're not in the odt you submitted. But I can work with this.

**Comment by mtorressahli** [comment]
> I'm confused about what the comma means. Does the comma always mean "comma plus whatever follows is a suffix"? Does Zotero have an equivalent for `[@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]`?

I think the issue is that different reference styles might require different use cases of the comma. Pandoc's `citeproc` interprets anything after the comma except an Arabic number as suffix. In Zotero's plugin `[@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]` would be equivalent to this image:

![image](https://user-images.githubusercontent.com/14179167/189870678-baf34fe3-68cc-4976-9f10-5b5c73bb0c4e.png)


> Strange, you have double ISBNs in those entries, and when I compile using pandoc those end up in the citation, but they're not in the odt you submitted. But I can work with this.

Sorry about that; APA doesn't use ISBNs so I often don't pay attention. I've fixed them now, would you like me to generate the log again?

**Comment by retorquere** [comment]
> I think the issue is that different reference styles might require different use cases of the comma.

I really hope that it's not the case that parsing of the citation is style-dependent. I don't know what style will be chosen eventually in the generated word/LO doc.

> Pandoc's citeproc interprets anything after the comma except an Arabic number as suffix. In Zotero's plugin `[@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]` would be equivalent to this image:

But then how does that differ from `[@smith{pp. iv, vi-xi, (xv)-(xvii)} with suffix here]`?

> Sorry about that; APA doesn't use ISBNs so I often don't pay attention. I've fixed them now, would you like me to generate the log again?

No, the current stuff is workable for me. Did you edit the fields in the ODT using the above citation picker BTW, or did you just edit the "this is what the rendered citations should look like". Best for me would be the former, because then I have an exact match for the parse results. Currently I'm trying to replicate them, but I wouldn't half mind skipping that.

**Comment by retorquere** [comment]
Why would `[@Billig1991IdeologyOpinions{ii, A, D-Z}, with a suffix]` yield `(Billig, 1991, ii, A, D-Z}, with a suffix] )` rather than `(Billig, 1991, pp. ii, A, D-Z}, with a suffix] )`? A missing locator label is always assumed to be `page`, no?

**Comment by retorquere** [comment]
> I suppose setting ", 1365b" as suffix would suffice

I don't see any other way to get what you want in CSL/Zotero. Locators always have labels, although Zotero does support the `canon` locator. `{} suffix` does work in the local version I have now.

**Comment by mtorressahli** [comment]
> Why would
> 
> `[@Billig1991IdeologyOpinions{ii, A, D-Z}, with a suffix]`
> 
> yield
> 
> `(Billig, 1991, ii, A, D-Z}, with a suffix)`
> 
> rather than
> 
> `(Billig, 1991, pp. ii, A, D-Z, with a suffix)`
> 
> ? A missing locator label is always assumed to be `page`, no? And the closing brace should be consumed I take it.

It is assumed to be a page if there's a digit (see https://github.com/jgm/pandoc/commit/35a3fb7e833c01f0352914a23727dff0145e7304); I assume digits are Arabic numerals. Otherwise (or in addition), maybe the default behaviour changes when the locator is put within curly braces?

**Comment by retorquere** [comment]
The thing is as far as I can tell, Zotero has no concept of label-less locators, and by extension, I would guess citeproc wouldn't have them (since Zotero just passes all citation suff to citeproc pretty much verbatim). Even if pandoc treats `{....}` as a verbatim locator, Zotero doesn't seem to have an equivalent, so it'd have to move to the suffix. If pandoc has label-less locators though, I don't see what difference there would be between

`[@Billig1991IdeologyOpinions{ii, A, D-Z}, with a suffix]`

and

`[@Billig1991IdeologyOpinions{}ii, A, D-Z, with a suffix]`

**Comment by retorquere** [comment]
> It is assumed to be a page if there's a digit (see https://github.com/jgm/pandoc/commit/35a3fb7e833c01f0352914a23727dff0145e7304);

The comments there specifically seem to aim at fixing handling of `{}...` though.

**Comment by mtorressahli** [comment]
> > I think the issue is that different reference styles might require different use cases of the comma.
> 
> I really hope that it's not the case that parsing of the citation is style-dependent. I don't know what style will be chosen eventually in the generated word/LO doc.

I might've said something absolutely irrelevant and confusing to the issue at hand to be honest - I misunderstood the question. If I'm not wrong, `citeproc` treats what comes after a comma as locator when (i) it's an Arabic numeral or (ii) is one of the known locator labels. Otherwise, it treats the comma and what follows as suffix.

> > Pandoc's citeproc interprets anything after the comma except an Arabic number as suffix. In Zotero's plugin `[@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]` would be equivalent to this image:
> 
> But then how does that differ from `[@smith{pp. iv, vi-xi, (xv)-(xvii)} with suffix here]`?

I'd say `citeproc` treats them the same.

> > Sorry about that; APA doesn't use ISBNs so I often don't pay attention. I've fixed them now, would you like me to generate the log again?
> 
> No, the current stuff is workable for me. Did you edit the fields in the ODT using the above citation picker BTW, or did you just edit the "this is what the rendered citations should look like". Best for me would be the former, because then I have an exact match for the parse results. Currently I'm trying to replicate them, but I wouldn't half mind skipping that.

I've attached an odt with a new subsection included the output manually modified (there was also an error in the 'expected output' of example 9).

> > I suppose setting ", 1365b" as suffix would suffice
> 
> I don't see any other way to get what you want in CSL/Zotero. Locators always have labels, although Zotero does support the `canon` locator. `{} suffix` does work in the local version I have now.

that works perfectly for me, and I'd assume for most people in similar situations where `citeproc`'s curly braces are a reasonable solution. It's how I wrote it for the test document: `[-@Aristotle2006RhetoricTheory{}, 1365b] `.





> The thing is as far as I can tell, Zotero has no concept of label-less locators, and by extension, I would guess citeproc wouldn't have them (since Zotero just passes all citation suff to citeproc pretty much verbatim). Even if pandoc treats `{....}` as a verbatim locator, Zotero doesn't seem to have an equivalent, so it'd have to move to the suffix. If pandoc has label-less locators though, I don't see what difference there would be between
> 
> `[@Billig1991IdeologyOpinions{ii, A, D-Z}, with a suffix]`
> 
> and
> 
> `[@Billig1991IdeologyOpinions{}ii, A, D-Z, with a suffix]`

I think the first would add a comma and space, being equivalent to `[@Billig1991IdeologyOpinions{}, ii, A, D-Z, with a suffix]`



> > It is assumed to be a page if there's a digit (see [jgm/pandoc@35a3fb7](https://github.com/jgm/pandoc/commit/35a3fb7e833c01f0352914a23727dff0145e7304));
> 
> The comments there specifically seem to aim at fixing handling of `{}...` though.

True. Although the behaviour with the examples I used fit the same assumption: without braces, either with only a space or a comma and a space (examples 2 and 3), `citeproc` treats them as locator references and, by default, page references.

[05_Analysis_test.odt](https://github.com/retorquere/zotero-better-bibtex/files/9558534/05_Analysis_test.odt)

**Comment by retorquere** [comment]
> I might've said something absolutely irrelevant and confusing to the issue at hand to be honest - I misunderstood the question. If I'm not wrong, `citeproc`

When you say "citeproc", you mean pandoc-citeproc, right? Because Zotero also uses citeproc (citeproc-js), and it seems there are differences between the two (like label-less locators for example)

> treats what comes after a comma as locator when (i) it's an Arabic numeral or (ii) is one of the known locator labels. Otherwise, it treats the comma and what follows as suffix.

But this then also goes for stuff in braces, which is pretty weird in the case of the braced syntax, which seems to be specifically for locators.

> I've attached an odt with a new subsection including the output manually modified with the citation picker (there was also an error in the 'expected output' of example 9).
> 
> [05_Analysis_test.odt](https://github.com/retorquere/zotero-better-bibtex/files/9558534/05_Analysis_test.odt)

This doesn't seem to have any live references? I specifically need a odt file generated by pandoc with the lua filter, with subsequently corrected live citations.

> True. Although the behaviour with the examples I used fit the same assumption: without braces, either with only a space or a comma and a space (examples 2 and 3), `citeproc` treats them as locator references and, by default, page references. This file was produced using `citeproc`.
> 
> [05_Analysis_test_citeproc.odt](https://github.com/retorquere/zotero-better-bibtex/files/9558606/05_Analysis_test_citeproc.odt)

But with corrected live citations?

**Comment by retorquere** [comment]
> > `{} suffix` does work in the local version I have now.
> 
> I'd love to try that one bytheway!

https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2248/site/content/exporting/zotero.lua

**Comment by mtorressahli** [comment]
> When you say "citeproc", you mean pandoc-citeproc, right? Because Zotero also uses citeproc (citeproc-js), and it seems there are differences between the two (like label-less locators for example)

yep, I meant `pandoc-citeproc`. The label-less locator is confusing, to be honest; I'd say it means nothing different than a suffix. Having the braces enabled, it might be more consistent to always label locators. If someone needs a locator without label (or other 'complex cases') they can use the suffix prepended with empty braces.

> > treats what comes after a comma as locator when (i) it's an Arabic numeral or (ii) is one of the known locator labels. Otherwise, it treats the comma and what follows as suffix.
> 
> But this then also goes for stuff in braces, which is pretty weird in the case of the braced syntax, which seems to be specifically for locators.

agree; the only difference it seems to make is putting an immediately adjacent braced sequence in the place a locator would use in any given style (maybe this is when label-less locators could be useful?)

> This doesn't seem to have any live references? I specifically need a odt file generated by pandoc with the lua filter, with subsequently corrected live citations.

In my laptop it looks like live citations, under the heading *Manually Adjusted Output with Citation Picker*. I haven't used Zotero with LibreOffice before (I was forced to migrate from LaTeX to MS Word) so I might be doing something wrong? Let me know if this one works

[05_Analysis_test.odt](https://github.com/retorquere/zotero-better-bibtex/files/9560951/05_Analysis_test.odt)


> > [05_Analysis_test_citeproc.odt](https://github.com/retorquere/zotero-better-bibtex/files/9558606/05_Analysis_test_citeproc.odt)
> 
> But with corrected live citations?

These were 'dead' because I produced them with `pandoc --citeproc` just to check its actual output

> https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2248/site/content/exporting/zotero.lua

Thanks! I used my usual workflow (`pandoc --lua-filter=zotero.lua -f .md -t .docx`) and all worked as expected! (except the ambiguous case of the potentially label-less locator, of which I'm not sure what we should expect anymore)

**Comment by retorquere** [comment]
I need the .md file the odt was rendered from too.

**Comment by retorquere** [comment]
Also please a new debug log for those two items.

**Comment by mtorressahli** [comment]
> Also please a new debug log for those two items.

here it goes

[05_Analysis_test_BBT_log.zip](https://github.com/retorquere/zotero-better-bibtex/files/9564435/05_Analysis_test_BBT_log.zip)

**Comment by retorquere** [comment]
I can work with this, so no new action is needed right now, but I generally prefer debug IDs over attached zips as I have tooling around fetching them and creating testcases from them, and for a next submission (if there should be a need for one), please select only those two items rather than everything in your library.

**Comment by mtorressahli** [comment]
> I can work with this, so no new action is needed right now, but I generally prefer debug IDs over attached zips as I have tooling around fetching them and creating testcases from them, and for a next submission (if there should be a need for one), please select only those two items rather than everything in your library.

Ok, sorry about that. I've generated a new log with only those items. This is the ID GNH9DDKS-refs-euc and the file:

[05_Analysis_test_BBT_log_twoItems.zip](https://github.com/retorquere/zotero-better-bibtex/files/9564876/05_Analysis_test_BBT_log_twoItems.zip)

**Comment by retorquere** [comment]
Thanks, but I think I have it, and after a successful debug log submission there is no need to attach the zip here. If the submission is successful, the zipfile will have already been uploaded to a S3 bucket which my tools read out and download automatically.

**Comment by retorquere** [comment]
A full test suite is running now, in 15-30 minutes the new version of the lua filter will be on the site.

**Comment by mtorressahli** [comment]
> A full test suite is running now, in 15-30 minutes the new version of the lua filter will be on the site. Thanks for reporting this and for the samples. The new locator/suffix parser is a lot more elegant than what I had before.

works perfectly :)
