### ISSUE TITLE
Twitter citekey causing issue when imported to Obsidian

### ISSUE THREAD

**Issue by atakanokan** [retorquere/zotero-better-bibtex#2251]
Support log ID: 99N5ZRN3-refs-euc

The citekey generated by better bibtex is causing issues when references are imported to Obsidian due to Twitter references having square brackets in their keys.

**Comment by retorquere** [comment]
Brackets are valid in citekeys. You can remove them by changing the pattern eg like so:

```
auth.lower.replace(/[^a-z]/ig, '') + shorttitle(3,3) + year
```

**Comment by retorquere** [comment]
Or you can be more specific in the replace with

```
auth.lower.replace(/[\[\]]/ig, '') + shorttitle(3,3) + year
```

but that's less readable

**Comment by atakanokan** [comment]
@retorquere thank you for the prompt response. I assume I can add any characters in between the two `'`s for brackets' replacement?

**Comment by retorquere** [comment]
Yep, any valid javascript string literal

**Comment by atakanokan** [comment]
After adding your `.replace` bit, how do I change the citekeys retrospectively in Zotero?
