### ISSUE TITLE
authEtal2(sep='&') + year =>  & disappears

### ISSUE THREAD

**Issue by haraldFo** [retorquere/zotero-better-bibtex#2252]
Hello,

when I enter '&' as the separator between the authors, the logical AND is not shown in the generated citation key.

Is this a bug or is this behavior on purpose?

Zotero: 6.0.13
BBZ: 6.7.22

Best,
Harald

**Comment by haraldFo** [comment]
Debug ID: UGLTK9GT-refs-euc

**Comment by retorquere** [comment]
Can you give build 3129 a go?

**Comment by haraldFo** [comment]
it works - thank you!
