### ISSUE TITLE
BetterBibLaTex file is not updated

### ISSUE THREAD

**Issue by czenci** [retorquere/zotero-better-bibtex#2253]
Alongside a description of your problem/question/feature suggestion, please also include a support log ID.

You can generate a support log ID by: KJSLXY9H-refs-euc

Dear support team, I need your help. My .bib file is not updated. I added a new file into Zotero and refreshed the bibtex file, but the .bib file is still not updated. 

Thank you for your help in advance.

**Comment by retorquere** [comment]
There's no team, just me. Did you check the "Keep updated" checkbox when you exported the bib file?

**Comment by czenci** [comment]
Dear Emiliano,

thank you for your quick reply.

This is how I exported my Zotero collection:
[cid:9d93cae7-8b2a-49b4-b91a-75bc5f1ae91a]

I also tried to export with Better CSL JSON but I was not able to find my annotations in Obsidian.

Looking forward to your reply.

Regards,
Eniko


________________________________

**Comment by retorquere** [comment]
You have to respond through the web client to post images, not by mail.

**Comment by czenci** [comment]
Thanks, so I should stay at BibLaTex. So this is how I exported my collections:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/99724605/187372879-fd20091e-052b-468d-92ad-f2e5f0f513de.png">

**Comment by retorquere** [comment]
You haven't enabled "keep updated", so the bib file will not update as you make changes in Zotero. "Keep updated" is disabled in this screenshot as it is not compatible with "Export files". If you disable "Export files" you can enable "Keep updated".

**Comment by czenci** [comment]
Thank you! It has been resolved, thanks again for the quick help. And for the plugin as well, it makes research easier.
