### ISSUE TITLE
Automatic export not working on Mac

### ISSUE THREAD

**Issue by zhangtiangu09** [retorquere/zotero-better-bibtex#2256]
When I try to Export collection (formatted as 'Better BibTex'), the 'keep updated option' is grey and not available.

**Comment by retorquere** [comment]
Is "export files" checked? These two are mutually exclusive.

**Comment by zhangtiangu09** [comment]
> Thanks for the reply. Do you mean 'export item...' by right clicking a single paper? The 'keep updated' option is also grey in that case.

**Comment by retorquere** [comment]
No, when you export a collection, you get a popup where you can specify what the format, and checkboxes to specify whether you want to include notes, attachments, and the "keep updated" checkbox. In that popup, make sure that "export files" is *not* checked.

**Comment by zhangtiangu09** [comment]
That works! Thanks a lot for your solution!
