### ISSUE TITLE
Problem with installing add-on in Zotero Version 6.0.8

### ISSUE THREAD

**Issue by Paudeli** [retorquere/zotero-better-bibtex#2261]
**Report-ID: 1906525718**

Hello everyone!

I just updated Zotero to version 6.0.8 and tried to implement the latest .xpi version (6.7.23.) of better bibtex. Already in the add-on manager I got the following error message: "Add-on installation failed. The add-on "Better BibTex for Zotero" could not be installed. It may be incompatible with this version of Zotero."

What should I do to fix this?

This is my first blogpost and I am not that familiar with LaTeX at all. So I am sorry if I missed something to make my problem clear...
Thanks for helping anyway!

**Comment by Paudeli** [comment]
Report-ID added in original post

**Comment by retorquere** [comment]
There's no everybody, just me. You need to upgrade to at least zotero 6.0.9, but preferably just to the latest version.

**Comment by retorquere** [comment]
Does that address your concern?

**Comment by Paudeli** [comment]
Yes, absolutely! Now everything is working. Thanks a lot!
