### ISSUE TITLE
Zotero crash on opening

### ISSUE THREAD

**Issue by Kullenej** [retorquere/zotero-better-bibtex#2262]
According to what we said in Zotero Forums, here is the log-file I got through the terminal.
[zotero-debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/9547645/zotero-debug.txt)

**Comment by Kullenej** [comment]
[System Error.txt](https://github.com/retorquere/zotero-better-bibtex/files/9547867/System.Error.txt)

**Comment by retorquere** [comment]
Seems related to other plugin
