### ISSUE TITLE
Zotero not exporting "extra" field

### ISSUE THREAD

**Issue by pmc2222** [retorquere/zotero-better-bibtex#2263]
Hi there,
I'm a beginner so I hope the issue I'm trying to open is pertinent and it follows an acceptable format...

I'm working with Zotero version 6.0.13, and exporting a "Better BibTeX" bib file.

I would like to add, in the bibliography, the original publication date for some of the references.
For that reason I add "original-date: XXXX" to the "Extra" field, for each of the concerned references.
(In the exportation window, I check the "Export notes" option (actually as I have a french version, I check "Exporter les notes")

The problem is that when I take a look (in an ascii editor) to the exported Better BibTex bib file, the information written in the extra field is not shown.

I have read this thread https://github.com/retorquere/zotero-better-bibtex/issues/1628 and it looks that there was a problem like this in the past, that was solved with a new version. My versions (both of Zotero and BBT) are quite recents, but I still have this problem (extra field information not appearing in the Better BibTex bib file exported).

May I have some help please?

Thank you very much, I look forward to hearing from you!

**Comment by pmc2222** [comment]
Sorry, here it is the debug id : HSFXTN2Y-refs-euc

**Comment by retorquere** [comment]
Thank you. Bibtex does not have a field for the origdate, so it is omitted in the export; if you export as Better BibLaTeX, it will be exported, otherwise I could help you export it for Better BibTeX using a postscript.

**Comment by pmc2222** [comment]
Thank you for your fast answer!

I have exported the Better BibLaTex bib file and I do have the extra field. However, this solution is not useful for me, as the next step in my workflow is generating and html from a Markdown file with pandoc, by using the following command:

pandoc Thèse_v1.md -f markdown --bibliography biblio_Better_BibLaTex.bib --csl=iso690-author-date-fr-no-abstract.csl --citeproc -s -o TEST.html

So, can you please help me out exporting the extra data to the Better BibTeX bib file by using a postcript? (I hope this way I will finally see the original publication date in my bibliography).

Thank you very much!

**Comment by retorquere** [comment]
When you export as Better BibLaTeX you get

```
@book{freud2019,
  title = {Le malaise dans la culture},
  author = {Freud, Sigmund},
  editor = {Pellegrin, Pierre},
  translator = {Astor, Dorian},
  date = {2019},
  origdate = {1876},
  publisher = {{Flammarion}},
  location = {{Paris}},
  langid = {fre}
}
```

if pandoc is not picking up `origdate` you would have to take that up with pandoc. origdate is a valid biblatex field, and the proper field for this date. I could help you put the origdate in another field using a postscript, but I wouldn't know what field that would have to be for pandoc to pick it up.

But for this case I would recommend exporting to Better CSL JSON and using

```
pandoc Thèse_v1.md -f markdown --bibliography biblio.json --csl=iso690-author-date-fr-no-abstract.csl --citeproc -s -o TEST.html
```

for reasons explained [here](https://retorque.re/zotero-better-bibtex/exporting/pandoc/#use-csl-not-bibtex-with-pandoc). CSL also has orig-date so it's likely to just be picked up correctly there.

**Comment by pmc2222** [comment]
Thank you again!

I have exported my library in a Better CSL JSON format (file biblio_Better_CLS_JSON.json) and I do see the orignal date:

  {"id":"freudMalaiseDansCulture2019","author":[{"family":"Freud","given":"Sigmund"}],"citation-key":"freudMalaiseDansCulture2019","editor":[{"family":"Pellegrin","given":"Pierre"}],"event-place":"Paris","ISBN":"978-2-08-149365-0","issued":{"date-parts":[[2019]]},"language":"fre","original-date":{"date-parts":[[1930]]},"publisher":"Flammarion","publisher-place":"Paris","source":"Open WorldCat","title":"Le malaise dans la culture","translator":[{"family":"Astor","given":"Dorian"}],"type":"book"},

However, when I create the html file, by using the command:

pandoc Thèse_v1.md -f markdown --bibliography biblio_Better_CLS_JSON.json --csl=iso690-author-date-fr-no-abstract.csl --citeproc -s -o TEST.html

The reference still appears without the original date:

FREUD, Sigmund, 2019. Le malaise dans la culture. Paris : Flammarion. ISBN 978-2-08-149365-0. 

But I guess that must be a problem with pandoc and not with BBT(?)

Any further advice would be much appreciated.

Thank you again!

**Comment by retorquere** [comment]
Are you sure this style renders orig date? Have it tried with apa7 (which I think renders origdate)?

**Comment by retorquere** [comment]
The extra field information is actually offered for rendering, but if a style just doesn't look at the offered data, nothing will appear.
