### ISSUE TITLE
Include integers in shorttitle

### ISSUE THREAD

**Issue by Zetison** [retorquere/zotero-better-bibtex#2264]
Is it possible to get shorttitle to not exclude numbers and function words, and characters inside math environment (i.e. "$L^2$")? I want the key to include the first authors last name, the year and the first unicode alphanumeric character of the three first words of the title. (similar to [auth][year][shorttitleINI:lower] in Jabref but only with unicode alphanumeric characters)
auth + year + shorttitle(3,3).abbr.lower

Example: A paper written by Venås in 2019 named "Exact 3D scattering solutions for spherical symmetric scatterers" should have key Venas2019e3s (instead of Venas2019ess)
Example: Paper by Day from 1979 titled "$L_p$-estimates for static stress fields" should have key Day1979lef
[GGM3YMAC-refs-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/9606422/GGM3YMAC-refs-euc.zip)

**Comment by Zetison** [comment]
The setup "auth + year + Title.select(1,3).abbr.lower.alphanum" gets me closer but still does not resolve the math environment properly (as it is simply ignored).

**Comment by retorquere** [comment]
> Is it possible to get shorttitle to not exclude numbers and function words

It doesn't exclude numbers (`auth + year + shorttitle.abbr.lower` gives `Venas2019e3s`), and you can change what words are ignored by changing [skipWords](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#skipwords). If you make that empty, it will not skip words of 2 letters or more; 1-letter words are always skipped.

> does not resolve the math environment properly (as it is simply ignored).

It isn't ignored, you have instructed to have it removed; Given "$L_p$-estimates for static stress fields"

* Title.select(1,3) => "$L_p$-estimates for static" (`select` deems `$L_p$-estimates` to be one "word")
* Title.select(1,3).abbr => "$fs" (`abbr` takes the first character from each "word")
* Title.select(1,3).abbr.lower => "$fs"
* Title.select(1,3).abbr.lower.alphanum => "fs" (`$` isn't alphanum)

Zotero doesn't have a concept of math environments, a `$` is just a dollar character. You might get closer to what you want using

```
auth + year + Title.replace(/[{}$]/g, '').replace(/-/g, ' ').select(1,3).abbr.lower
```
