### ISSUE TITLE
Remove empty lines in Better BibTeX export

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2266]
When I export to Better BibTeX, I get 1 empty line at the beginning and 3 empty lines at the end.
Is it the expected behaviour? Is there a reason for the 3 empty lines at the end?

I am importing the references in my .bib file one by one. The end result I would like to get is to have a single empty line between entries.
So ideally, to minimize additional formatting needed, I would prefer to have only one empty line in the exported BibTeX entry, either at the top or the bottom.
Is it possible to keep only one empty line in the export?

Other users may have different preferences in the number of empty lines. Would it be possible to add the number of empty lines as an option?

Debug log ID: XJT9TZ29-euc

Thank you very much.

**Comment by retorquere** [comment]
Can you try build 3375?

**Comment by mjthoraval** [comment]
I have just tested on Zotero 6.0.16-beta.11+5cea183ae, Windows 10.
It is working perfectly now. There is no empty line before anymore, and just one empty line after in the output.
So I can add entries in my .bib file with a single Ctrl+V, without any additional reformatting needed.
Thank you very much!

**Comment by retorquere** [comment]
There shouldn't be an empty line after.

**Comment by retorquere** [comment]
But why not use auto-export for bib file upkeep?

**Comment by retorquere** [comment]
I don't get empty lines. You do?

**Comment by mjthoraval** [comment]
I was testing in Evernote, as I thought any text editor would be the same. I don't know why Evernote is adding an empty line, but it is not really relevant actually. It would have been more logical to test in the LaTeX editor. Sorry about this.
In the LaTeX editors I am using, I indeed do not get any empty line. I just get a carriage return at the end of the BibTeX entry copied. So if I paste the content at the start of a line already containing some text, it will move that text to a new line and put the BibTeX content above, without any empty line. If I copy the content to an empty line, the empty line will remain below the BibTeX entry.

I am writing papers either locally with TeXnicCenter, or online on Overleaf. I mostly create the references manually into .bib file with BibTeX. So I just use the Quick Copy shortcut to get the BibTeX of items in my library. I just do it once every time I write a paper. I am not sure if there is a better way to do?

**Comment by retorquere** [comment]
Better is subjective, the way I use it I have one collection per paper, auto-export each collection to the git clone of my overleaf paper; instead of git you could use dropbox. That way the bib file is always up to date on overleaf, and no manual copying.

**Comment by retorquere** [comment]
That sounds like a sound approach to me.
