### ISSUE TITLE
Feature request: support multiple keys in zotero:// links

### ISSUE THREAD

**Issue by ilupin** [retorquere/zotero-better-bibtex#2267]
debug log ID: MNYCCEG7-refs-apse

Hi, Zotero allows to open multiple items using `zotero://select/library/items?itemKey=[itemKey1],[itemKey2]`, and it would be nice if BBT also support multiple keys in zotero:// links, e.g. `zotero://select/items/bbt:[key1],[key2]`. Thanks!

**Comment by retorquere** [comment]
zotero://select/library/items?itemKey=@[citeKey1],bbt:[citeKey2] will work on build 3193

**Comment by ilupin** [comment]
I have installed the build 3193, but it doesn't work. Actually, `zotero://select/library/items?itemKey=[itemKey1],[itemKey2]` also fails to select items with the build, which works again if I use [v6.7.23](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.23). 

debug log ID: JIYAPX5C-apse

**Comment by retorquere** [comment]
A new build will drop here in about 10 minutes, can you get me a new log from that?

Unfortunately I cannot test this myself because calling up the `zotero://` protocol has never worked for me (which is likely due to the crazy setup I have for use + testing).

**Comment by ilupin** [comment]
Here is the debug log ID with build 3197: 2PYCBSL5-apse. Thanks.

**Comment by ilupin** [comment]
The build 3198 fixes the `zotero://select/library/items?itemKey=[itemKey1],[itemKey2]`, but doesn't work if citekeys are used.

debug log ID: 4IL2Z98Z-apse

**Comment by ilupin** [comment]
I confirm zotero link with multiple citekeys works on build 3199. Thanks!
