### ISSUE TITLE
Automatic export of Better BibTeX file is scheduled, but not executed

### ISSUE THREAD

**Issue by hsteinbrecher** [retorquere/zotero-better-bibtex#2268]
Dear @retorquere, 

the debug/Support log ID is USNVAXYP-euc. 

The following problem appears. I got several libraries that are exported to different bib files. In the "Automatic export" section I activated that the export should be triggered "On Change". Anyhow when I am editing my library in the top-right corner appears "Scheduled Better BibTeX" with a grey circle that indicates also after a longer period of waiting to progress and also several hours later the respective library is not updated.

Can you help out on that issue?

Thanks in advance and bests

**Comment by retorquere** [comment]
`USNVAXYP-euc` does show auto-export activity, but your wait period for auto-export is set to 229 seconds, and I see changes coming in within those 229 seconds, and that will reset the timer. Can you do nothing in Zotero for 5 minutes after changing an item, and then send a new log?

You shouldn't keep your zotero.sqlite in a dropbox-synced folder BTW: https://www.zotero.org/support/kb/data_directory_in_cloud_storage_folder.

**Comment by hsteinbrecher** [comment]
Thanks @retorquere for the quick reply!

The new debug log ID is WGED5AXB-euc. How can I change the auto-export delay to trigger a more immediate update of my .bib-file?

Thanks for the hint on the zotero.sqlite in a cloud storage! The path was the result of a move from one laptop to another. I will fix that. :)

**Comment by retorquere** [comment]
I do see the auto-export starting now.

To reset the delay, go into the hidden prefs as explained at the top of [this page](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autoexportdelay) and reset `autoExportDelay` to the default 5.

**Comment by hsteinbrecher** [comment]
Now it works perfectly fine! Thank you for your quick help! Why does it happen, that the `autoExportDelay` changes?

**Comment by retorquere** [comment]
I don't know, the only cause I know is it's because people experiment in the hidden prefs. BBT doesn't change this setting itself, only reads it.
