### ISSUE TITLE
BetterbibTex "Keep up to date" option

### ISSUE THREAD

**Issue by shYroale** [retorquere/zotero-better-bibtex#2269]
Hello,

I downloaded Betterbibtex but when I want to export my Zotero library I can't click on the option that allows me to keep my library updated with new changes. The option appears but it is in gray and I cannot click on it.

Thanks a lot for your help!

**Comment by retorquere** [comment]
Uncheck "export files"

**Comment by shYroale** [comment]
Thank you very much for your quick reply, it works ! You helped me very much :)

**Comment by retorquere** [comment]
You're welcome.
