### ISSUE TITLE
The add-on "Better BibTex for Zotero" could not be installed

### ISSUE THREAD

**Issue by Lobz** [retorquere/zotero-better-bibtex#2272]
Good day. I'm trying to install Better BibTex add-on for Zotero on Debian 10.
My Zotero version is 6.0.1. I downloaded the xpi file from /latest, which is currently pointing here: https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.23

When I try opening the file I get the message "The add-on "Better BibTex for Zotero" could not be installed. It may be incompatible with this version of Zotero."

I have failed to find any info on which version of Zotero is supported by the latest release. Any help is welcome.

**Comment by retorquere** [comment]
You need at least zotero 6.0.9.

**Comment by Lobz** [comment]
Thank-you. Somehow I thought the debian zotero package was the latest. I see there is a zotero-deb repository in your github, I suppose I can use it to get the latest version?
