### ISSUE TITLE
date vs year/month field

### ISSUE THREAD

**Issue by chenboshuo** [retorquere/zotero-better-bibtex#2274]
Some compile environments needs year instead of date
for example:
```latex
@article{lipsky2021men,
  title={Men and oral health: a review of sex and gender differences},
  author={Lipsky, Martin S and Su, Sharon and Crespo, Carlos J and Hung, Man},
  journal={American Journal of Men's Health},
  volume={15},
  number={3},
  pages={15579883211016361},
  year={2021},
  publisher={SAGE Publications Sage CA: Los Angeles, CA}
}
```
is correct,
but
```
@article{lipsky2021men,
  title = {Men and Oral Health: A Review of Sex and Gender Differences},
  author = {Lipsky, Martin S and Su, Sharon and Crespo, Carlos J and Hung, Man},
  date = {2021},
  journaltitle = {American Journal of Men's Health},
  volume = {15},
  number = {3},
  pages = {15579883211016361},
  publisher = {{SAGE Publications Sage CA: Los Angeles, CA}},
  file = {/home/cbs/Zotero/storage/8CSTTKRQ/lipsky_et_al2021men_and_oral_health.pdf}
}
```
the year is missing, and they can't recognize the `date` key.
How to set the output format for this?
Thank you for your attention.

**Comment by retorquere** [comment]
Hard to say without a debug log, but the first entry doesn't look like it was generated by BBT, and the second looks like it was exported using Better BibLaTeX (which uses `date`) rather than Better BibTeX (which uses `year`/`month`).

**Comment by chenboshuo** [comment]
> Hard to say without a debug log, but the first entry doesn't look like it was generated by BBT, and the second looks like it was exported using Better BibLaTeX (which uses date) rather than Better BibTeX (which uses year/month).

I change export settingss to `BibTex` and get my expected outcome,Thank you.
