### ISSUE TITLE
Zotero patchDates hidden preference

### ISSUE THREAD

**Issue by cl-bu** [retorquere/zotero-better-bibtex#2275]
Hello,

I am a new and very inexperienced user of Zotero and Better Bibtex and would like to ask for your help in the following matter.

Currently, I am trying to import a Papers 3 library to Zotero for Mac, and I would like to retain the original "date-added" dates from my old Papers 3 library.

As recommended at the Zotero forums, I have downloaded BBT, then imported my old Papers 3 library and attempted to use the "patchDates" hidden preference to change the "Date Added" info in Zotero to the original date of my old Papers 3 library.

However, the "Copy date-added/modified from extra field" command in the BBT menu did not yield any results. 
In the "extra field", the following information was not recognized: "tex.date-added: 2020-07-20T15:15:36GMT, tex.date-modified: 2020-07-20T15:34:24GMT".

BBT was only able to recognize these dates after I edited them in the extra field in the following fashion: "tex.dateadded: 2020-07-20T15:15:36, tex.datemodified: 2020-07-20T15:34:24". After these edits, the "Copy date-added/modified from extra field" command recognized the dates, but the exact times in the "date added" and "modified" fields are always set to "02:00:00".

Is there a way that I do not have to change "tex.date-added" to "tex.dateadded" or "tex.date-modified" to "tex.datemodified" before running the "Copy date-added/..." command, and is it possible that the exact times (not only the dates) are also copied to the "date added" and "modified" fields in Zotero?

I hope I was able to communicate my problem in an understandable fashion.

Many thanks!

(debug log ID: CFVHPQC4-refs-euc)

**Comment by retorquere** [comment]
Thanks for the report, will go out in the next release.

**Comment by cl-bu** [comment]
Thank you for the fast help! The test build works fine!
