### ISSUE TITLE
[sic] in book title in Zotero 6.0.15 becomes [Sic] in BB export file.

### ISSUE THREAD

**Issue by BoiseStateCS410** [retorquere/zotero-better-bibtex#2276]
This title in Zotero 6.0.15

The Elements of Geometrie of the Most Auncient Philosopher Euclide of Megara [sic]

becomes this output 

  title = {The Elements of Geometrie of the Most Auncient Philosopher Euclide of Megara [Sic]},

in the export file. This happens no matter how the title is categorized: BBT, Sentence, or Title case.

This entry is for the first English edition of Euclid in 1570. The printer was confused about his Euclids--this book was actually by Euclid of Alexandria, not Megara, so I want to add a [sic] after the title. How can I accomplish that?

**Comment by BoiseStateCS410** [comment]
Debug log: 3P8GMLDQ-refs-apse

**Comment by njbart** [comment]
Try `<span class="nocase">[sic]</span>`.

**Comment by retorquere** [comment]
That is indeed the right solution -- try generating a CMoS bibliography from `3P8GMLDQ-refs-apse` and you'll see that without the nocase Zotero also turns it into

> Euclid [of Alexandria]. The Elements of Geometrie of the Most Auncient Philosopher Euclide of Megara [Sic]. Translated by al-Ḥajjāj ibn Yūsuf Ibn Maṭar, Thābit ibn Qurrah al-Ḥarrānī, Adelard of Bath, Bartolomeo Zamberti, and Sir  Henry Billingsley. First English. London: John Day, 1570.

**Comment by retorquere** [comment]
also: you should have your titles in sentence case in Zotero, not Title Case, so

> The elements of geometrie of the most auncient philosopher Euclide of Megara [sic]

instead of

> The Elements of Geometrie of the Most Auncient Philosopher Euclide of Megara [sic]

**Comment by BoiseStateCS410** [comment]
Thanks for your help. I hope this helps others as well.
