### ISSUE TITLE
How to format citation keys on Mac?

### ISSUE THREAD

**Issue by didiowen** [retorquere/zotero-better-bibtex#2277]
Hi all,

I'm a new user to BBT and markdown writings. I tried to format my own citation key using the instructions given in [Citation Keys](https://retorque.re/zotero-better-bibtex/citing/#configurable-citekey-generator), but when I want to set the journal abbreviation filter to **auto**, I tried `journal.abbr:auto`, `journal.abbr=auto`, and `journal.abbr(auto)`, and none of which worked (when it didn't work the background went orange). I looked up some posts and see people use citation key format like `[auth:lower][year][veryshorttitle:lower]`, and wonder how I can format my citation keys correctly?

Many thanks to answering my stupid question.

<img width="694" alt="截圖 2022-10-12 22 48 33" src="https://user-images.githubusercontent.com/115644557/195379092-1a569a2d-45ee-4d4f-8be3-1aa06f0a9cb2.png">
<img width="696" alt="截圖 2022-10-12 22 48 54" src="https://user-images.githubusercontent.com/115644557/195379118-fa277eec-21d7-4c3a-93c1-10d7a8fc3181.png">

**Comment by didiowen** [comment]
My debug log id is: J65V7GJQ-refs-apse

**Comment by retorquere** [comment]
`authEtal2 + journal(abbrev=auto) + year`, but this does mean that if an item has an explicit journal abbrev set, it will not be used.

**Comment by didiowen** [comment]
Thanks! It works!

I also want to know how to use `Title:fold=chinese:lower:nopunctordash:select=1,3` in the the format because I'm also a Chinese user having problems with the title...I wish `veryshorttitle` also gets the `fold=Chinese` function.

**Comment by retorquere** [comment]
`clean(false) + veryshorttitle.fold(chinese)`

In the next release you will also be able to use the better named

`fold(false) + veryshorttitle.fold(chinese)`

**Comment by retorquere** [comment]
Oh and you can also just turn off "Force citation key to plain text" in the preferences, then you don't need `clean(false)`
