### ISSUE TITLE
Better BibTeX : Initializing don't stop

### ISSUE THREAD

**Issue by neybaf** [retorquere/zotero-better-bibtex#2280]
Debug ID TK2TFUFI-apse

Hi there, 

Since a while now, better Bib TEx stay "initializing charging cite keys". I think it appears after I disabled all plugins to check a problem I had with zotero.  It looks like the plugin is loading but nothing happens and citekey never appears. The options panels say that the plugin is "loading".

Not sure if I give the right debug ID, tell me if I have to do anything else. 

To repeat the problem : 
1. Open Zotero
2. Wait
3. Cry because you don't have citekeys 

Thanks

**Comment by retorquere** [comment]
Please send a new log from 3309

**Comment by neybaf** [comment]
Hi, new Debug ID is UGCDCBLZ-apse

**Comment by retorquere** [comment]
Sorry -- you need to start up Zotero, choose "Restart with debugging enabled" from the Help menu, then send a BBT debug log. There's no startup information in `UGCDCBLZ-apse`, and the error happens at startup.

> Could

yes?

**Comment by neybaf** [comment]
That was what I did actually. Weird... Anyway here are 2  debug ID.

First debug ID 

I wait a bit  and then submit the debug ID  -  8FWTCQHU-apse

Second Debug ID 

1. I closed all opened documents 
2. I tried to refresh the sync with zotero various time
3. I checked the "rapport d'erreur Zotero" (Zotero Error report, I guess) 
4. Pop up appeared
5. Then I submit a second debug ID -  DDPDX6HG-apse

> Yes? 

I was thinking the plugin already fixed itself, as after the pop up appeared all the citekeys are there. 

About the bug itself, could it come from a large RSS feed not checked ? It looks lie the Zotero error report show Zotero has problems with some feed. 

I opened a thread on [Zotero's forum](https://forums.zotero.org/discussion/100573/better-bib-tex-stay-initializing?new=1) with the Zotero error report and Debug ID

**Comment by retorquere** [comment]
Try 3314. There was a bug in the key generator that your pattern hit. The charachters `"#%'(),=\{}~` and space are illegal in ib(la)tex citekeys and will thus always be removed from the generated citekey BTW, so the spaces, commas and parentheses in your pattern are effectively no-ops.

**Comment by neybaf** [comment]
Hey, still not working 

Debug ID soon after launch  -  XGJB55L9-apse

As the plugin is not starting I can't change my pattern...

**Comment by neybaf** [comment]
It's fixed Nice
How do you explain parenthesis did work before ?

**Comment by retorquere** [comment]
That's strange because between the last two versions, I only added logging.

I'm not sure what "works" means in this context. The edge case you hit was that if no output was generated besides the fixed strings in the formula, and only invalid characters remained, BBT would error out on assigning the resulting empty key. What could have "worked" is that a key was generated, the invalid characters were removed, and a non-empty key remained, and that would be assigned. But a key with parentheses or commas should not have been possible, not before, not now.

**Comment by neybaf** [comment]
Strange Indeed 
The plugin is still initializing at every launch of zotero. It needs less than a minute

As you can see on the picture I did had parenthesis on my citekeys, but since the last updates if I refresh the citekey parenthesis are deleted

<img width="253" alt="Capture d’écran 2022-10-23 à 23 06 50" src="https://user-images.githubusercontent.com/103755582/197399745-e13a3be6-0bb1-4df4-b997-4b906f346741.png">

**Comment by retorquere** [comment]
> As you can see on the picture I did had parenthesis on my citekeys,

That was definitely a bug.

> but since the last updates if I refresh the citekey parenthesis are deleted

That's good then.

**Comment by neybaf** [comment]
Thanks for the quick fix
