### ISSUE TITLE
auth.lower unexpectedly includes first name if author name has been switched to single field

### ISSUE THREAD

**Issue by RoBaaaT** [retorquere/zotero-better-bibtex#2281]
Hello,

I am using a custom citation key format that includes ``auth.lower`` and am running into the following (for me) unexpected behaviour:
The citation key produced by BetterBibtex depends on whether I have set the author name in the item info to be displayed using two fields or a single field. In the second case the citekey will unexpectedly include the author's first name. Is this expected/intended behaviour?

I've always thought of this field display option in Zotero as just a purely cosmetic feature, but maybe I am wrong and it changes the internal representation which is then used by BetterBibtex to generate the citekey?

In any case, the [documentation](https://retorque.re/zotero-better-bibtex/citing/#generating-citekeys) states that the ``auth`` functions returns "The [...] author's last name". If the behaviour difference with the display option is intended (or at least expected) it would be good to update the documentation to reflect this. As a user it is confusing if author first names suddenly show up in citekeys although the documentation states that it should just be using the last name.

Just in case it helps, here are some debug log IDs of refreshing citation keys in the two cases:
1. Refreshing citation key with two-field first author: TLFH85GW-refs-euc
2. Refreshing citation key with single-field first author: Y4VSBCLE-refs-euc

**Comment by retorquere** [comment]
This is expected behavior. The difference is not merely cosmetic; single-field names are for compound names like company names (eg `International Business Machines`), or single-named individuals (eg `Aristoteles`), where the "first"/"last" name don't make sense. Where those terms do apply, you must use the two-field option. References will also include the first name when rendered by Zotero itself if you use single-field.

**Comment by RoBaaaT** [comment]
Thanks for the explanation. In this case IMO it would make sense to update the documentation to mention that ``auth`` will return the author's last name or full compound name depending on the type of author name. What do you think?
