### ISSUE TITLE
Auto-export stops working, "Error: out of memory"

### ISSUE THREAD

**Issue by Aisha1022** [retorquere/zotero-better-bibtex#2283]
Hello

I have auto-export set up through BBT to export citations and associated notes to Obsidian. It's been working great up until now but for the last couple of days, the auto-export is no longer working and I am getting an error that says "out of memory". 

Are you able to please assist?

Thanks very much in advance!

**Comment by Aisha1022** [comment]
Hello!

Sorry, I've never submitted a help request before so I didn't know how to generate/send a debug log. The debug log ID us AM7YSVW8-refs-apse

Please let me know if you need anything else, thanks very much in advance!

**Comment by retorquere** [comment]
Can you go into the BBT prefs under `Export` -> `Misc`, disable `Enable cache`, and see if that makes a difference?

**Comment by Aisha1022** [comment]
Hi, thanks so much I think this worked!
