### ISSUE TITLE
Citeproc: citation __ not found`

### ISSUE THREAD

**Issue by edent** [retorquere/zotero-better-bibtex#2284]
Debug log ID: `GKMDY6SP-euc`

I have my citations in Markdown, using the VS Code plugin. When I try to use Pandoc to format the output, I get:

`[WARNING] Citeproc: citation verletComputerExperimentsClassical1967 not found`

My minimum viable Markdown is:

```
---
zotero:
  scannable-cite: false
  client: zotero
  author-in-text: false
  csl-style: apa # pre-fill the style
---

# Intro

Computers are complicated @verletComputerExperimentsClassical1967
```

The command I'm running is:

`pandoc -s --lua-filter=zotero.lua -C test.md -o test.html`

Zotero is running in the background. I can reach http://127.0.0.1:23119/connector/ping . The Better BibTex plugin is installed and configured. I'm using the latest LUA file. Pandoc 2.19.2

I'm sure I must be missing something obvious - but I couldn't work it out from reading the documentation.  What do I need to do so Pandoc can find the citations from Zotero?

**Comment by retorquere** [comment]
html is not a valid target for this filter, so it falls back to letting pandoc doing it's own citation work. The only valid targets are docx and odt, which are the only document formats Zotero supports.

**Comment by edent** [comment]
Thank you. However, it still gives me the same error.

```
pandoc -s --lua-filter=zotero.lua -C test.md -o test.odt
zotero-live-citations 9016790
[WARNING] Citeproc: citation verletComputerExperimentsClassical1967 not found
```

What's the JSON that it should be sending the endpoint? I'll see if that produces an error.

**Comment by retorquere** [comment]
If that's the full output of the pandoc run, the filter isn't active, as the first thing it does is print its version.

I don't have access to my computer right now,  when I'm back I can say what json must be sent, but that doesn't seem to be the problem for me. The script will mention missing citekeys, but not with this message. For some reason it looks like the filter doesn't run at all.

**Comment by retorquere** [comment]
Remove `-C` from the command line. You are instructing pandoc to run it's own citation processor, and that steals the citations from the input before the lua filter runs.

You don't send anything to the endpoint, it's a GET of
http://127.0.0.1:23119/better-bibtex/export/item?pandocFilterData=true&translator=json&citationKeys=`<your citation keys here`

**Comment by edent** [comment]
Aha, that's great. Thanks for your help - and the brilliant tool.
