### ISSUE TITLE
Feature Request: Make Zotero Internal Item ID available in Citation Key Variables and/or export JSON id field

### ISSUE THREAD

**Issue by ryanwwest** [retorquere/zotero-better-bibtex#2286]
Hi, I'm wondering if you can get the Zotero internal item ID field as a variable in the citation key format (https://retorque.re/zotero-better-bibtex/citing/). There is an itemID field available that translates to a value like zotero-678 (I think you can get this with the variable ArchiveID), but this is not the item ID I'm referring to. I'd like to get the value used at the end of a select URI, e.g., JFWCVTFR from zotero://select/library/items/JFWCVTFR.

I understand that I could also just not use citekeys for my Select URLs; however, I'm nevertheless hoping to find a way to get this ID as part of my citekey. I'm open to using Postscript or other things if necessary.

Alternatively, I'm wondering if, when exporting citations to JSON CSL (or another file format that can stay updated with changes), I can make the id field of a citation equal to the Zotero internal item ID (instead of equal to citation-key). For example, one (simplified) line of JSON output for a citation is:

```
{
    "id":"20ThingsVe2021",
    "citation-key":"20ThingsVe2021",
    "title":"20 Things I've Learned in my 20 Years as a Software Engineer",
    "type":"webpage"
}
```

id is currently the same as citation-key.

Both of these involve making the same Zotero Internal Item ID available, so I've put them in one FR, but I can separate if preferred. Thanks!

**Comment by retorquere** [comment]
Formula's in build 3323 now allow `item`, `item(key)` (which is the same as `item`) or `item(id)`.

To get the itemKey into CSL, you can either use `item` as the formula and get the item key into your CSL that way, or use a postscript for CSL:

```
if (Translator.BetterCSL) csl.id = zotero.itemKey
```

**Comment by ryanwwest** [comment]
@retorquere Thank you so much, what incredible response time and support. Both options seem to work correctly and independently of one another.

**Comment by retorquere** [comment]
Cool -- a new release build is running.
