### ISSUE TITLE
Wrong Citation Key displayed for Single Field Author Names

### ISSUE THREAD

**Issue by Murgeye** [retorquere/zotero-better-bibtex#2287]
Hi,
thanks for your work. I found the following issue while reorganizing my bibliography and would appreciate a fix. If you need any more info, I will be happy to provide it.

Debug Log ID: MI24VEEP-refs-euc

Entry:
![image](https://user-images.githubusercontent.com/16648242/197721900-97ba46e8-cb4a-4ab4-94fb-d7a631fe4268.png)

Citation Key Format:
`auth.lower + '_' + shorttitle(1,0).lower + '_' + year`

# Expected Behaviour
Citation Key displayed in Zotero (`microsoftcorporation_office_2018`) matches the one in the generated bib file.

# Actual Behavior
Citation Key in bib file differs (`microsoft_corporation_office_2018`).

Generated bib entry:
```
@misc{microsoft_corporation_office_2018,
	title = {Office {Document} {Cryptography} {Structure}},
	url = {https://interoperability.blob.core.windows.net/files/MS-OFFCRYPTO/%5bMS-OFFCRYPTO%5d-181211.pdf},
	language = {en},
	author = {{Microsoft Corporation}},
	year = {2018},
}
```

I think the citation key in the bib file is actually correct, but the display in Zotero is wrong.

# Environment
macOS 13.0 (MacBook Pro 2017)
Zotero Version 6.0.15

**Comment by retorquere** [comment]
The bibtex output you pasted above is from the Zotero BibTeX export, not the Better BibTeX export.

**Comment by Murgeye** [comment]
Oh wow, this is embarassing. I am using the Overleaf sync for Zotero and kinda assumed (since I haven't touched it in a while) that it used the Better BibTeX Export. But since it takes the bibliography directly from my Zotero account, it of course does not. I guess there is no way to export the Better BibTeX to the Zotero account and sync it to Overleaf?

I can confirm that the Better BibTeX export indeed puts out the same citation key as shown in the GUI. Apologies for the confusion.

**Comment by retorquere** [comment]
> Oh wow, this is embarrassing. I am using the Overleaf sync for Zotero and kinda assumed (since I haven't touched it in a while) that it used the Better BibTeX Export. But since it takes the bibliography directly from my Zotero account, it of course does not. I guess there is no way to export the Better BibTeX to the Zotero account and sync it to Overleaf?

You can either pin them manually, or use [autopin](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay) to pin them automatically. Pinned keys show up in overleaf.

If you want the actual BBT output, [there are a few ways](https://retorque.re/zotero-better-bibtex/exporting/auto/#getting-your-bbt-generated-biblatexcitekeys-to-other-places).
