### ISSUE TITLE
Error message  "An error occurred while trying to export the selected file." (out of memory)

### ISSUE THREAD

**Issue by giuseppeciccolini** [retorquere/zotero-better-bibtex#2288]
Debug log ID: XG7LUDHA-refs-euc

Since a few days ago, when I try to export My Library in Better BibLatex format I get the following pop-up error message: "An error occurred while trying to export the selected file.".

The problem does not occur systematically, only occasionally.
The problem seems not to be related to any specific file. I tried selecting a list of items, and sometimes it occurs, other no.

**Comment by retorquere** [comment]
There's a host of permission errors regarding `Zotero\storage` in your home dir, can you look into that first? It's making it hard to find the actual BBT error in the log file.

**Comment by retorquere** [comment]
I do not see any indication of a Better BibLaTeX export in `XG7LUDHA-refs-euc`.



> The problem does not occur systematically, only occasionally.
> The problem seems not to be related to any specific file. I tried selecting a list of items, and sometimes it occurs, other no.

If you send a new log immediately after the problem occurs, that would give me more info on the error. Without that, there's nothing for me to go on. I've imported `XG7LUDHA-refs-euc` and I could export that without problems.

**Comment by giuseppeciccolini** [comment]
Thank you. About your first reply, I've opened a thread on the Zotero forum and I'll check that.
For the second one, I'm sorry for that, this is the new debug log ID: FDMXI2WD-refs-euc
Perhaps you'll see that from the log (IDK), the export went fine at the first export and than I got the error message for a second export, in both cases trying to export My Library.

**Comment by giuseppeciccolini** [comment]
I have 2438 items in My Library.
The issue occurs even with 1000 items, but I had no problem till a few days ago (when the number of items was not that different from today).

I have 15 GB free in my PC.
My RAM is 16 GB. The export procedure doesn't involve a substantial increase in used RAM apparently. 
I've run Windows memory diagnostics tool and it looks fine.

Thanks!

**Comment by retorquere** [comment]
On Windows Zotero can apparently [only use 3GB of memory](https://forums.zotero.org/discussion/comment/414969/#Comment_414969). Try going into the BBT prefs, export -> misc -> disable "use cache".

**Comment by giuseppeciccolini** [comment]
Thanks that makes a lot of sense. Your solution to change the BBT prefs doesn't fix the problem unfortunately, I'll turn to the Zotero forum to see if there is anything else I can do.

**Comment by retorquere** [comment]
I'll see if I can find a Windows machine to reproduce this on. It's still primarily a BBT problem.

**Comment by giuseppeciccolini** [comment]
Have you managed to reproduce it? Thanks!

**Comment by retorquere** [comment]
I have, but I don't have a solution yet. Have you tried background export? That does work for me.

**Comment by samzukoff** [comment]
I'm not a developer, just a regular user, and I'm getting the same error ("An error occurred while trying to export the selected file.") when I try to export my library into a folder where I'm working on a beamer presentation. It creates a file that has nothing in it -- it overwrote my .bib file when I was trying to update it after I added some new entries into Zotero. I've tried exporting it to a folder with a shorter path, it didn't help. I've tried reinstalling Better Bibtex in Zotero, didn't help. Tried turning off some of the options that other people have mentioned in similar posts, hasn't helped. Not sure if this is enough information for anyone to try to help me figure out the problem, hope it is. Thanks in advance!

**Comment by retorquere** [comment]
@samzukoff I can't help you without a BBT debug log. Enable debug logging from the help menu, reproduce the problem, then send a BBT debug log from the help menu.

Please open a new issue for your problem -- chances are pretty good that you experience an entirely unrelated problem. "An error occurred" is the unhelpful generic message Zotero displays whatever the error happened to be, and translators cannot influence this in any way.

**Comment by retorquere** [comment]
Turning off the cache in the export settings in the cache may help, as may using background export. Windows 32 bit apps are constrained to 3G of memory, there is nothing I can do about that.

**Comment by samzukoff** [comment]
That worked!! Thanks so much!!!
