### ISSUE TITLE
Compatibility issues with the latest Zotero beta 6.0.16-beta.7+238c7ce41

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2291]
I have recently updated to the latest Zotero beta 6.0.16-beta.7+238c7ce41: https://forums.zotero.org/discussion/100656/available-for-beta-testing-zotero-link-options-for-quick-copy
After the update, the feature described in that post did not work. So following the instructions from dstillman (now removed by him), I have reset the translators in Zotero Preferences > Advanced > Files and Folders > Reset Translators... Is this process affecting BBT?

After this reset of the translators, the functionality worked again. But then some problems came back, only with BBT active:
``````
[JavaScript Error: "Translator has no doExport function" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 1337}]
[JavaScript Error: "Code promise is not resolved in noWait mode" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 1798}]
[JavaScript Error: "this._translatorInfo is null" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2506}]
[JavaScript Error: "Translator has no doExport function" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 1337}]
``````

The issue is not very stable, so the best way to reproduce in the latest beta:
1) Remove (not Disable) BBT from the Add-ons Manager
2) Reset Translators
3) Restart Zotero
4) In the Zotero Preferences > Export > Quick Copy > Note Format, select `Markdown + Rich Text` and also tick the two options below
5) Create a note
6) Open a PDF file in the Zotero PDF Reader
7) Highlight some text
8) With the new functionality in the beta, drag and drop of the highlighted text into a Word document produces hyperlinks back to Zotero on the annotation copied to Word
![image](https://user-images.githubusercontent.com/36054098/197951768-2386d099-ca3a-4063-aadb-c2d0526aa562.png)
9) Install Add-on from File... for zotero-better-bibtex-6.7.29
10) Restart Zotero
11) Try again to drag and drop the annotation from the Zotero PDF Reader. This time, when you try to drop in Word, it shows a forbidden sign (circle crossed).
![image](https://user-images.githubusercontent.com/36054098/197952454-dffed39d-e980-48de-ba66-34dfc4c64d9f.png)
It produces the error above. Debug log ID: 9U5RPQUH-euc
12) Restart Zotero
13) The drag and drop of an annotation to Word is now working properly again.

A simple Disable - Enable of BBT seems to be sufficient to reproduce, but I just give the full process to get a better chance that you can reproduce it.
Things seem to work fine after restart, so hopefully everything is fine. But it is probably good to check what is happening before they release Zotero 6.0.16.
I do not really understand what is happening, or how it is related to BBT, but the steps above suggest that there is something wrong when using BBT in the latest beta. I will update here if I notice any other problem.

Thank you very much again for the plugin and its maintenance.

**Comment by retorquere** [comment]
This is a long-standing problem. I need information from the Zotero crew, which I've tried repeatedly to get [on the forums](https://forums.zotero.org/discussion/comment/410463/#Comment_410463) and their [dev channel](https://groups.google.com/g/zotero-dev/c/7UE3441sug8/m/-Ur5L2FxAQAJ), but I've yet to receive a response.

**Comment by mjthoraval** [comment]
Thank you for your reply.
Since the process was updated in the latest beta, it may trigger more reports in the forum that could help raise the issue.
Just to confirm on one point: does the Reset Translators. process affect BBT?

**Comment by retorquere** [comment]
Oh yes, sorry I forgot: the reset will have deleted the translators on disk, so yes, it will affect BBT, but BBT checks at each start whether the translators need to be reinstalled,so that fixes it.

I'm not optimistic about feedback from the devs on this particular issue. I've gotten exactly zero responses on this, and it's been a while since I started raising it.

**Comment by retorquere** [comment]
[good news](https://groups.google.com/g/zotero-dev/c/7UE3441sug8)!

**Comment by mjthoraval** [comment]
Nice :)

**Comment by retorquere** [comment]
This should be out now -- can you retest on the latest Zotero?

**Comment by mjthoraval** [comment]
I have reproduced the steps in my original post, and I do not see the problem anymore. So it should be solved I think.
Thank you very much!
Tested with Zotero 6.0.19-beta.3+89bc09469 on Windows 10, BBT 6.7.36.

[Is it better to close the issue myself or let you decide?]

**Comment by retorquere** [comment]
I usually prefer to close issues myself. Thanks for the confirmation!
