### ISSUE TITLE
Citation key format is ignoring vertical bar '|' for preprints

### ISSUE THREAD

**Issue by bhvieira** [retorquere/zotero-better-bibtex#2292]
I'm using the following citation key format for testing purposes
````
auth.postfix(_) + journal.nopunct.postfix(_) + year | auth + '_default_' + year
````
I expected that Preprints, which lack the journal field, would use the second case, but it is not occurring.

Application context:
<details>

> Application: Zotero (Zotero) 6.0.15 en-GB
> Platform: Win32 Windows NT 10.0; WOW64
> Addons:
>   Zotero LibreOffice Integration (6.0.2.SA.6.0.15, extension)
>   Zotero Word for Windows Integration (6.0.1.SA.6.0.15, extension)
>   Better BibTex for Zotero (6.7.29, extension)
> Settings:
>   citekeyFormat = "auth.postfix(_) + journal.nopunct.postfix(_) + year | auth + '_default_' + year"
>   keyConflictPolicy = "change"
>   keyScope = "global"
>   platform = "win"
> Settings at default:
>   ascii = ""
>   asciiBibLaTeX = false
>   asciiBibTeX = true
>   autoAbbrev = false
>   autoAbbrevStyle = ""
>   autoExport = "immediate"
>   autoExportDelay = 5
>   autoExportIdleWait = 10
>   autoExportPathReplaceDiacritics = false
>   autoExportPathReplaceDirSep = "-"
>   autoExportPathReplaceSpace = " "
>   automaticTags = true
>   autoPinDelay = 0
>   auxImport = false
>   baseAttachmentPath = ""
>   biblatexExtendedDateFormat = true
>   biblatexExtendedNameFormat = false
>   biblatexExtractEprint = true
>   bibtexParticleNoOp = false
>   bibtexURL = "off"
>   cache = true
>   cacheFlushInterval = 5
>   charmap = ""
>   citeCommand = "cite"
>   citekeyFold = true
>   citekeyFormatBackup = ""
>   citekeySearch = true
>   csquotes = ""
>   DOIandURL = "both"
>   exportBibTeXStrings = "off"
>   exportBraceProtection = true
>   exportTitleCase = true
>   extraMergeCitekeys = false
>   extraMergeCSL = false
>   extraMergeTeX = false
>   git = "config"
>   import = true
>   importBibTeXStrings = true
>   importCaseProtection = "as-needed"
>   importCitationKey = true
>   importExtra = true
>   importJabRefAbbreviations = true
>   importJabRefStrings = true
>   importNoteToExtra = ""
>   importSentenceCase = "on+guess"
>   importUnknownTexCommand = "ignore"
>   itemObserverDelay = 5
>   jabrefFormat = 0
>   jieba = false
>   kuroshiro = false
>   language = "langid"
>   mapMath = ""
>   mapText = ""
>   mapUnicode = "conservative"
>   parseParticles = true
>   patchDates = "dateadded=dateAdded, date-added=dateAdded, datemodified=dateModified, date-modified=dateModified"
>   postscript = ""
>   postscriptOverride = ""
>   preferencesOverride = ""
>   qualityReport = false
>   quickCopyEta = ""
>   quickCopyMode = "latex"
>   quickCopyOrgMode = "zotero"
>   quickCopyPandocBrackets = false
>   quickCopySelectLink = "zotero"
>   rawImports = false
>   rawLaTag = "#LaTeX"
>   relativeFilePaths = false
>   retainCache = false
>   scrubDatabase = false
>   separatorList = "and"
>   separatorNames = "and"
>   skipFields = ""
>   skipWords = "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
>   startupProgress = "popup"
>   strings = ""
>   stringsOverride = ""
>   testing = false
>   verbatimFields = "url,doi,file,ids,eprint,/^verb[a-z]$/,groups,/^citeulike-linkout-[0-9]+$/, /^bdsk-url-[0-9]+$/"
>   warnBulkModify = 10
>   warnTitleCased = false
>   Zotero: export.quickCopy.setting = "export=f895aa0d-f28e-47fe-b247-2ea77c6ed583"
> Zotero.Debug.enabled: true
> Zotero.Debug.enabled at start: true
> Total export workers started: 0, currently running: 0
</details>
Debug log:
GM9GHMFU-refs-euc

**Comment by retorquere** [comment]
Missing fields just return an empty string, they don't jump to the next formula. You might want

```
type(preprint) + auth + '_default_' + year | auth.postfix(_) + journal.nopunct.postfix(_) + year
```

or

```
auth.postfix(_) + journal.default('default').nopunct.postfix(_) + year
```

**Comment by bhvieira** [comment]
That you so much @retorquere ! That fixes it, closing this issue :)
Apparently I didn't get what 'I' then
