### ISSUE TITLE
Citation key format operator request

### ISSUE THREAD

**Issue by rtalexander** [retorquere/zotero-better-bibtex#2296]
It would be useful to have a citation key operator that returns the first character of the first n words of a title. For example, if the title were "Gone With The Wind", the operator would return "GWTW", or possibly "GWW" if common stop words are removed. The advantage of this is that shorter citation keys can be generated based on longer titles.

**Comment by retorquere** [comment]
I prefer to add test cases when I build new functionality, that makes sure it doesn't accidentally break in the future. A debug log gives me a test case.

With the current release, you can already do `title.abbr.upper` which would get you `GWW`. If you want just the first 2 words, you'd do `title.select(2).abbr.upper`. I can get you a new build where `abbr` picks a configurable number of characters per word (it always picks 1 now), but as said, I prefer to add test cases for new stuff.

**Comment by retorquere** [comment]
Build 3358 adds `abbr(<number>)` support so you can choose how many characters `abbr` will pick per word.

**Comment by retorquere** [comment]
I assume this fixes your problem.
