### ISSUE TITLE
Problems with RSS feeds

### ISSUE THREAD

**Issue by davidoskky** [retorquere/zotero-better-bibtex#2297]
I'm sorry as I cannot reproduce this anymore, but I'll point out that something strange goes on with RSS feeds.
For some time I was not able to update the RSS feeds in Zotero anymore, once I disabled better bibtex they started updating again and no problem showed up after I enabled the plugin again.

Probably having a citation key for each rss item is creating some problems somewhere I would guess...
Anyways, temporarily disabling the plugin seems to solve the issue.

**Comment by retorquere** [comment]
I'll see whether I can exclude RSS items.

**Comment by retorquere** [comment]
Build 3359 should fix the problem.

**Comment by davidoskky** [comment]
Alright, feeds appear to update correctly and the citation key is not present on new items.
Unfortunately I'm not able to tell you whether the problem is solved, but I'll let you know if I observe something like that again.

**Comment by retorquere** [comment]
If something does reappear, commenting here will reopen the issue automatically.
