### ISSUE TITLE
Automatic export page is ~bugged~ not the place to create auto-exports

### ISSUE THREAD

**Issue by MavropaliasG** [retorquere/zotero-better-bibtex#2298]
I am trying to set the directory where I will export my bibliography, and I think the preferences page is not displaying correctly

This is what I currently see

![image](https://user-images.githubusercontent.com/13523909/198439689-b18342c1-0534-465a-b98a-25f21720b7bd.png)

There's not even 'Keep updated' as an option in the dropdown menu.

I removed and reinstalled Better Bibtex (6.7.35) but the problem still remains.

Zotero 6.0.15 running on Manjaro Linux. If it helps I sent a debug log 2F6MMME4-refs-apse  and  A8ZHHV8S-apse

**Comment by retorquere** [comment]
Just export as you normally would. The "Keep updated" option is in the export popup, not in the preferences.

**Comment by MavropaliasG** [comment]
Hi @retorquere thank you for your quick reply and the amazing work with this addon. You were right, going through File > Export and exporting as Better BibTex re-populated the 'Automatic export' page correctly. Thank you once again
