### ISSUE TITLE
CAYW TypeError: Formatter is not a function

### ISSUE THREAD

**Issue by LioSergent** [retorquere/zotero-better-bibtex#2299]
I've been using the amazing CAYW feature with vim for some time. Last time I used it without problem was 19th October. Today it returns this error:

```
CAYW failed: TypeError: Formatter[(intermediate value)] is not a function
pick@chrome://zotero-better-bibtex/content/better-bibtex.js:248535:44
```

I did not dig into Zotero updates or changes I made to my operating system in the past 10 days, but I can try if you need.

Here's a log ID: 4QI49PAG-refs-euc

I did not try anything to solve the issue

Thanks a lot for the very useful add-on !

**Comment by retorquere** [comment]
Can you send me a new debug log from 3362?

**Comment by LioSergent** [comment]
ARPWDQGR-refs-euc

The issue seems clear now, and it's my bad. The popup with 3362 becomes "No formatter parencite". 
Switching it back to "citep" just like the example given in https://retorque.re/zotero-better-bibtex/citing/cayw/#vim works. I must have changed to "parencite" thinking it was just a string passed to BBT without even trying it worked.

Sorry !

**Comment by retorquere** [comment]
You want `http://127.0.0.1:23119/better-bibtex/cayw?format=latex&command=parencite`
