### ISSUE TITLE
BBT + Zotfile creating duplicate attachments during import

### ISSUE THREAD

**Issue by ZBiener** [retorquere/zotero-better-bibtex#2300]
Debug log id: 9BARMPSF-euc

Apologies, I'm not sure what I'm doing wrong here. I thought I had this working a few days ago, but I've been trying to solve so many little migration issues, I have lost track.

I have Zotfile set up to file automatically to a custom location, with custom naming patterns. When I import a bibtex library *without* BBT, the filing works properly (except that Zotero chokes on paths with ";" in them).

When I enable BBT, filing stops working properly. 

+ Instead of the custom location, the files are put into Zotero's default storage directory, using the normal subdirectory structure.
+ Some files are duplicated. So, instead of one PDF listed under an item, I now see two: one file with a .pdf extension, and one without. Both files actually have a .pdf extension in the file system, but that's not how they show in Zotero. This does not happen to all files! But I can't figure out the conditions of duplication. It is always the same enties, however. In the sample .bib file below, they are the ones associated with: sakellariou202228, westfall1973a, gocl1613, and ducheyne_2015. Duplication does *not* happen with garberayers1998b and zcosm02.

Any tips would be appreciated. 

The .bib file is (with some paths shortened):
```
@book{gocl1613,
	address = {Hildesheim},
	author = {Goclenius, Rudolph},
	category = {Primary},
	date = {1964},
	keywords = {Dictionaries, Scholasticism},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Primary/Goclenius.R/Goclenius - Lexicon philosophicum, quo tanquam clave philosophicae (1964).pdf},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Primary/Goclenius.R/Goclenius - Lexicon philosophicum, quo tanquam clave philosophicae (1964)a.pdf},
	note = {Rodolphus Goclenius. Reprint (1st work). Originally published: Francofurti : M. Becker, 1613. Added title page, engr. of original edition.},
	origdate = {1613},
	publisher = {G. Olms},
	title = {Lexicon philosophicum, quo tanquam clave philosophicae fores aperiuntur},
	annote = {B51 .G576 1964}}

@book{garberayers1998b,
	title = {The {Cambridge} History of Seventeenth-Century Philosophy},
	category = {Secondary},
	date = {1998},
	date-added = {2022-10-26 18:58:57 -0400},
	date-modified = {2022-10-26 18:58:57 -0400},
	edition = {2Rev Ed},
	editor = {Garber, Daniel and Ayers, Michael},
	isbn = {0521531802},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Garber.D;Ayers.M/GarberAyers - The Cambridge History of Seventeenth-Century Philosophy (2003).pdf},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Garber.D;Ayers.M/GarberAyers - The Cambridge History of Seventeenth-Century Philosophy (2003)a.pdf},
	month = {May},
	price = {\$80.00},
	publisher = {Cambridge University Press},
	title = {The Cambridge History of Seventeenth-Century Philosophy}}


@book{ZGaukroger1998a,
	address = {London},
	category = {Secondary},
	date = {1998},
	date-added = {2015-09-09 17:10:49 +0000},
	date-modified = {2019-04-20 15:19:21 -0400},
	editor = {Gaukroger, Stephen},
	isbn = {0415170540 (hardcover)},
	keywords = {Emotions},
	library-id = {97024517},
	publisher = {Routledge},
	title = {The Soft Underbelly of Reason : The Passions in the Seventeenth Century},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Gaukroger.S/Gaukroger - The Soft Underbelly of Reason  The Passions in the Seventeenth (1998).pdf}}



@book{zcosm02,
	address = {Cambridge},
	booktitle = {The {Cambridge} Companion to {Newton}},
	category = {Secondary},
	date = {2002},
	date-added = {2022-10-26 18:58:57 -0400},
	date-modified = {2022-10-26 18:58:57 -0400},
	edition = {2nd},
	editor = {Cohen, I. Bernard and Smith, George E.},
	isbn = {0521651778},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Iliffe.R;Smith.G/IliffeSmith - The Cambridge Companion to Newton (2016).pdf},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Cohen.I;Smith.G/CohenSmith - The Cambridge Companion to Newton (2002).pdf},
	price = {\$85.00},
	publisher = {Cambridge University Press},
	title = {The Cambridge Companion to {Newton}}}

@article{ducheyne_2015,
	author = {Ducheyne, Steffen},
	category = {Secondary},
	date = {2015},
	date-added = {2022-10-26 18:58:57 -0400},
	date-modified = {2022-10-26 18:58:57 -0400},
	journal = {Estudios de Filosofía},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Ducheyne.S/Ducheyne - An editorial history of Newton’s regulae philosophandi (2015).pdf},
	month = {Jun.},
	number = {51},
	pages = {143–164},
	title = {An editorial history of Newton’s regulae philosophandi},
	year = {2015},
	annote = {In the paper at hand, I provide an editorial history of
		  Isaac Newton’s famous regulae philosophandi on the basis
		  of extant manuscript material.&amp;lt;/p&amp;gt;}}

@article{westfall1973a,
	author = {Westfall, Richard S.},
	category = {Secondary},
	date = {1973},
	date-added = {2022-10-26 18:58:57 -0400},
	date-modified = {2022-10-26 18:58:57 -0400},
	issn = {00368075, 10959203},
	journal = {Science},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Westfall.R/Westfall - Newton and the Fudge Factor (1973).pdf},
	number = {4075},
	pages = {751--758},
	publisher = {American Association for the Advancement of Science},
	title = {Newton and the Fudge Factor},
	urldate = {2022-09-27},
	volume = {179},
	year = {1973}}

@article{sakellariou202228,
	author = {Sakellariou, Vassilis and Test, User},
	category = {Secondary},
	date = {2022},
	date-added = {2022-10-26 18:58:57 -0400},
	date-modified = {2022-10-26 18:58:57 -0400},
	issn = {0039-3681},
	journal = {Studies in History and Philosophy of Science},
	keywords = {Constitutive, Synthesis, Historicised, Dynamical laws},
	file = {/Users/.../OneDrive-University/Reference/Bibdesk/Secondary/Sakellariou.V/Sakellariou - Constituting the ‘object’ of science in Newton's Principia (2022).pdf},
	pages = {28-36},
	title = {Constituting the ‘object’ of science in Newton's Principia: the many faces of Janus},
	url = {https://doi.org/10.1016/j.shpsa.2022.07.002},
	volume = {95},
	year = {2022}}
```

**Comment by retorquere** [comment]
Can you try again with 3365?

**Comment by ZBiener** [comment]
Thanks for the quick turnaround!! Yes, that fixed it.

**Comment by ZBiener** [comment]
I'm afraid I spoke too soon. There is still something strange going on at the interface of Zotero/Zotfile/BBT. 
Debug file: VKZ7LM6A-euc

+ When I import the .bib file above, items that have Editor fields, but no Author fields (i.e., like an edited book as a whole), are not filed properly. Items with Author fields, on the other hand, are filed just fine (with an exception, see below). 
+ However, once the bibliography is imported, if I select any *file* and ask Zotero to "Rename and Move", the item is renamed and moved properly. If I select the item itself (not its subordinate files), no rename and move is initiated. 

The above two things only seem to happen when BBT is enabled.

+ The exception, however, is file import also seems to choke on pathnames with two consecutive spaces in them. You can see this in the entry for ZGaukroger1998a above. When I remove the extra space in "Reason  The", the file is processed properly. Once again, this happens when BBT is enabled, but not when Zotfile alone is enabled.

This might be better handled as a separate issue. Should I open one?

**Comment by retorquere** [comment]
There's too much going on here at once. Let's first address

> * When I import the .bib file above, items that have Editor fields, but no Author fields (i.e., like an edited book as a whole), are not filed properly.

What do you mean by "are not filed properly"? They I've imported `garberayers1998b`
 and I don't immediately see what's wrong with it.

**Comment by retorquere** [comment]
> * The exception, however, is file import also seems to choke on pathnames with two consecutive spaces in them.

Build 3379 fixes this.

It'd be helpful to me if you could be more specific in your reports; "not files properly" and "chokes" can mean a host of things. It'd help me if you could describe what you're seeing that you did not expect to see, or what you're not seeing that you did expect to see.

**Comment by ZBiener** [comment]
Apologies. That was sloppy (and annoying) of me. And thank you again for getting to these comments so quickly! 

First thing, Build 3379 indeed fixes the double-space issue. Thank you.

Let me try to state the other issue more clearly. Sorry for the length.

The issue occurs when both BBT and Zotfile are enabled. It does not occur when Zotfile in enabled but BBT is disabled. With both enabled, when I import an entry like garberayers1998b, all the bibliographic data is imported properly. However, the associated .pdf files are not placed into the correct directory.

For example, I have the following pattern specified in Zotfile for the intended directory structure: "%c/%F|%L/". This should place an item's associated files into a directory named after the item's collection (%c), with a subdirectory named after the item's Authors (if they are found) or after the item's Editors (if no Authors are found) (%F|%L). 

Instead of following this pattern, upon import the item's associated files are placed into the standard Zotero storage directory, under subdirectories of the usual sort (e.g., "3J25IA37"). Additionally, if any filename renaming pattern was specified in Zotfile, it is also ignored, the file's original filename is kept as-is. **This only happens when the item has Editors, but not Authors, associated with it**.

Interestingly, after the import is complete, I can fix the issue by selecting the .pdf files in Zotero and hitting "Rename and Move". The files are then moved to the proper directory and renamed. But the files aren't properly placed during the import process.

There is one kink here that will matter for testing. The current official release of Zotfile does not extract Editor names properly from the Zotero database. So, regardless of BBT, it will not put the file for an entry like garberayers1998b in the correct directory. But this problem has been corrected in the latest merge (see "Fix Editor Wildcards", https://github.com/jlegewie/zotfile/pull/634). The issue I'm reporting here occurs with this 'fixed' version, when BBT is enabled. (It does not occur when BBT is disabled). 

Sorry for the hassle.

**Comment by retorquere** [comment]
This must be some kind of timing issue, because Zotfile's rename activity should happen in a phase where BBT can no longer have any influence on matters.

Import translators have zero influence over where attachments are saved to; translators can say "please attach the file you can find at [path] to the this item which I request you save", and Zotero does the actual copying/renaming/whatnot of the attachment (and item saving BTW, also something which import translators have no say over). The imported attachments should *always* appear in the storage directory first, because that is what Zotero does for all attachment imports, no exceptions.

Zotfile listens to a [notifier event](https://github.com/jlegewie/zotfile/blob/894e2627ded626404b14db596a1ca9b0851bebb4/chrome/content/zotfile/notifier.js#L29) which Zotero should fire *after* attachments have been saved there, and Zotfile then actively [renames](https://github.com/jlegewie/zotfile/blob/688c423f61884c77d76922d06ce85a981f8c35f4/chrome/content/zotfile/zotfile.js#L866)/moves these attachments into the desired place. I see Zotfile does a test for file existence there, it'd be interesting to have it log the results from that.

There's an incoming build 3384 which will drop here in about 15 minutes where you can [disable BBT imports](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#import) without uninstalling BBT, I accidentally removed that option a few weeks ago, build 3383 brings it back.

As an aside, `garberayers1998b` has two title fields. BBT used to concatenate them, but 3384 picks the last found instead (following biblatex behaviour).

**Comment by ZBiener** [comment]
Thank you. I figured it was something with the 'hand-off' between components, but I am way out of my depth. It seems like this issue might be better posted in the Zotfile forums. But I'll try to dig around the code for a bit to see if I can find a fix. Thank for your help.

**Comment by retorquere** [comment]
Please do keep me in the loop. The procedure I described here is what usually happens, but BBT employs a few [monkey patches](https://en.wikipedia.org/wiki/Monkey_patch) that can mess with the regular order of things. I don't see how they could be involved here, but still. The fact that BBT being present reliably reproduces the problem must mean *something*.

I'm happy to help diagnose this issue, but since the attachments do in fact turn up in the expected `storage` directory, the next step is to see why Zotfile misses either the notification, or decides the files don't exist, and we can only know which is the case with more logging from Zotfile.

What happens if you turn off BBT imports through the hidden pref in 3384 but leave BBT otherwise enabled? Do you still see the problem?

**Comment by retorquere** [comment]
> * However, once the bibliography is imported, if I select any _file_ and ask Zotero to "Rename and Move", the item is renamed and moved properly. If I select the item itself (not its subordinate files), no rename and move is initiated.

And this is different when BBT is not installed?

**Comment by ZBiener** [comment]
Sorry for the delay. I tried to do more extensive testing, which build 3884 really helped with. 

It turns out that I was quite wrong. The Editor fields had nothing to do with the behavior. It was just a conincidence that my entries with Editor tags also had multiple attachements. It was a further coincidence that because my items with multiple attachements had a ";" in them, it appeared as if the issue was related to BBT (since BBT parses ";" correctly, whereas the standard input filters do not).

The actuall issue is with multiple attachments. It turns out that when more than one attachment is imported per item, those attachement are not moved by Zotfile to the proper location during the import process. They can subsequently be moved by hitting the "Rename and Move" command. But they are not properly moved during the import process. 

This seems clearly like a Zotfile issue, which I will post to that repository. 

Many apologies for the runaround.

**Comment by retorquere** [comment]
Never a problem. BBT is a complex beast and I'm not at all surprised it causes problems sometimes.

**Comment by retorquere** [comment]
I wouldn't be at all surprised if the standard bibtex exporter does not support multiple attachments.
