### ISSUE TITLE
Export: "Error: Unexpected date type"

### ISSUE THREAD

**Issue by chrishammermann** [retorquere/zotero-better-bibtex#2303]
Debug log ID: R923F2B5-euc

I have today noticed that my automatic export did not update since 22nd September. I have been mostly working with old references, so I didn't notice it until now. In the automatic export tab there's an "Error: Unexpected date type" message. When I try to do a manual export, I get the same error message (the full message should be in the log submitted).

**Comment by retorquere** [comment]
Can you right-click the library or collection that this auto-export covers, and send a new BBT error log from the popup menu? The ID will have `-refs` in it.

**Comment by retorquere** [comment]
Build 3403 should fix the problem

**Comment by chrishammermann** [comment]
Thank you, works well!
