### ISSUE TITLE
Regenerating citation key every time zotero startup

### ISSUE THREAD

**Issue by LamFTS** [retorquere/zotero-better-bibtex#2304]
Hi there, I am using zotero 6.016 on Archlinux+GNOME, better-bibTex plugin is the latest version (6.7.36),  I notice that citation key is generated every time zotero startup, I check the folder that zotero storage is located, better bibtex files seems exists just fine, I just don't know why it regenerating citation key over and over again.

![image](https://user-images.githubusercontent.com/53118840/200829463-528f1487-6a2d-4e78-ab4c-2e7f84a8595e.png)
![image](https://user-images.githubusercontent.com/53118840/200829541-99fa137f-c3ed-495a-9614-1863d264e559.png)

**Comment by LamFTS** [comment]
Here is my Bug ID: USJ2GANE-refs-apse, I hope this can be useful

**Comment by retorquere** [comment]
Can you disable zotero-updateifs and delitem (they are throwing errors, I want to make sure they are not interfering), go into help -> debug-> start with debugging enabled, and after restart, send a new log.

**Comment by irmoodie** [comment]
Hello,

As of last week I am having exactly the same issue, upon restart better-bibTex (6.7.36) regenerates all citation keys.

Windows 11 22H2
Zotero 6.0.18 (other addons: Night for Zotero 0.4.19, but bbtx behaviour is the same with it disabled)

Debug log ID: XBSTMVJJ-euc

Let me know if there's anything I can do to help troubleshoot it.

**Comment by retorquere** [comment]
Can you send a new debug log and check "include cache" before you send it?

**Comment by retorquere** [comment]
Can you shut down zotero, zip `better-bibtex.sqlite`, and attach that zip here?

**Comment by nocona71** [comment]
> Hello,
> 
> As of last week I am having exactly the same issue, upon restart better-bibTex (6.7.36) regenerates all citation keys.
> 
> Windows 11 22H2 Zotero 6.0.18 (other addons: Night for Zotero 0.4.19, but bbtx behaviour is the same with it disabled)
> 
> Debug log ID: XBSTMVJJ-euc
> 
> Let me know if there's anything I can do to help troubleshoot it.

Actually I am observe a similar problem for a couple of days: 

![grafik](https://user-images.githubusercontent.com/63201084/201988253-7f018beb-4242-4805-b663-e70f0edd7cee.png)
In addition the number of citation keys appears to be increasing every restart of the computer.

![grafik](https://user-images.githubusercontent.com/63201084/201988550-1cc86823-f263-4476-a0f6-b46244c77deb.png)
Zotero: 6.0.18
Better BibTex for Zotero: 6.7.36

**Comment by retorquere** [comment]
I need a copy of your database. The log won't have enough information.

**Comment by nocona71** [comment]
I made a copy of the db. However, I am reluctant to send the full db. Is there maybe another way to support? Is there something special in the data you are looking for?

**Comment by nocona71** [comment]
... maybe this excerpt of the db as "sort of" JSON already helps.
[better-bibtex.zip](https://github.com/retorquere/zotero-better-bibtex/files/10015627/better-bibtex.zip)

**Comment by nocona71** [comment]
Debug log ID: EXXPNB8Z-euc

**Comment by retorquere** [comment]
The bbt db only has your citekeys, nothing else.

**Comment by nocona71** [comment]
could you offer your public key?

**Comment by retorquere** [comment]
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGN0DdABEADqlCO29yET6e1BPJ1SOS2lYw3cObmZmzRTGTE8WEwWRDQ4M9RT
oMP0BEYyvVDTL91A6kUi6zfEiU+L/PizIo6Xr1jUQa3XLDYTaAy0HZDuAJncUYHL
j3PtzWbJuJtkSYgjux2wVUGQDzX+uxK8CAnIWsJUXw+oZLlhPvFxQ66Z7aQNpR+c
Yq7S0n4EhDB+GRb11OWM/hZSX/3QE1TTsc0R83uYp/DAdhpbMyy0UbLfe0L5EsMH
hW8FERxZVlpMM48Ja689TcmiiFMepU3BxHwGnnPtf0FJzx9jNsmuYiyIkbm8FUaJ
H3NiQgoLp5sP7KSjos1rLYUiMBQCRezgy/GzAiWxPMTx27beButpllZx22sxmQx0
LMqOwBZCjZ6PDXjKjJwEy5EuXOsSnv9L1jsMvhEYMgcIfkejvmq08v5HgztWPDvj
y8+Nbnx4fojcb+iZL4/8O7HvS1d5LmhNGoXYC6CQmz5emFR0CEuBil5uBwwnD6I3
8VFGVwERa+2VT05i6TL8nmxeN9CYL9mwwHBPFbj2vJVfitrnMaG9wQYLTyBPB0om
/7rq+QMuJ+co0v0XxS2iZZsKubtNf3q34hOprS969NtFuaTEOmD3pGFr9aXBME9c
cIRuxFlbD30K6E5ffNWYHgTZFYfjekem4fd8c64Rfb3BXZTr12e8CiLCVwARAQAB
tC9FbWlsaWFubyBIZXlucyA8ZW1pbGlhbm8uaGV5bnNAaXJpcy1hZHZpZXMuY29t
PokCVAQTAQgAPhYhBNShpr6PizKx4Le5iOwrkTfiKOuGBQJjdA3QAhsDBQkHhh8A
BQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEOwrkTfiKOuGicoP/RhTuvCX5969
P/xJWWLXQiuy9mw1bWi6LzK4WOxAJte40TITfnhYCTVpCkt5S2XioK/BflfyBY1l
QPTXAav9rqVgffch2h2MDxCnoc629fBmpxhL4RTrnQidBEr0JnLa9Q/nuNXCjNEt
//eCx/bwWCyqThonfBnAuFb5SALpQlKdiYjt61RW4IWyGcWS8v5kqi+cO7y7dkuw
Gq032bLRODw0Xe6eAQW7Wn2cLu1B8occFo6oKEIe1x4XDOPtox5fc3oOZkh3eftz
V63E6RU93msp6cwT+SV5HPGN8xK+dbwY0djZAYtnyh5vFZJf67Em3MpT99eXSM9J
wFBL2nfJCkGQ27E5DypDchLOltkfJR+Q0jkMBUxBeWCoE4xvpJtsamXGYdWIDZZv
vCZ0BhWW8qnfzSwDMVNue5CWP1035ctgpFkzbM2U6Cy5o8/tXB7em/WqYrFQGyye
rw8GO+6YQGybOlEloBuExuMo8B8jB0AzZqF8rCMYJUFMxwoqGJ+g6i9nXcAZUw1f
jdCZ+2FkCiK7rr1rFZD8sV3OFOQlbzkr05sI9IB0LWZQPFtu9Qsll34mhyArSUML
f1P+sy0zWMp12Gg5wA2T9DoTFYKXlQasqRCuBSNJRaTk2gVvhntkkfIwTTU4Ait+
EfkX9DXM4nG6sfKbHy62we4iDJcxtUQPuQINBGN0DdABEADPnxv80iGfE4/+t0eB
QygMdQKmKzeV4laNSs3hyFzysKZzhIFD92lI3VF8WMExfxjX+bFtfl6yoWRHAD8C
Fmq7S0II83EGWxI5Ia5ZZakswLwm8K2SUBSyEP3rQkrM7vOVILvoiOJrphjXwzsH
kNkN2rUrVCFoj6EfHJ0jNLHPPczA1RDylGcLAl0phe7PhXxtmuNbvs4LErjLWB5X
x8ZdcK3Em6I6FBeGLSBDHsbvuCfS0omXCZ46eybc8rWsmwaxH8OHMS30ztB+i15h
OtDBafdiFyvIlJ6jWxczQUJjJ0mn8TMJL2fzo/jzFi8k9hpmZMP0NfrbET6y7YQx
N+HaIDBR1bxsMShAe3FjdUdcz7xqVZ4xyxUO+Kox1ZlUTYmjHLf6Mr6e5y4VXnUC
66EHc4xTwEx9tlIgpj9IQ3rXDhKLMou25o6oMeSuQu5kuRfM9k4Do9b61Vro7pE3
ztv43aA54o99QDLlVm0M09KBEjbsSNtcH5kjp5OkS9+uGEB6wDw1tCr1V5VBZO6t
QmJnKm76S4xBRp+45U7sz9GSwv7At5ANa9+OoQxlrVcW4FONX3BGWgiPfxVo2+P2
aMhaQNI0wJStgqSqkTbYTrINIFqfoa1xsNgsVkGY3hyMXFZI54Cnonmb5NUkY4am
KXXuxWrpm8HgpbeNkSXkiThY8wARAQABiQI8BBgBCAAmFiEE1KGmvo+LMrHgt7mI
7CuRN+Io64YFAmN0DdACGwwFCQeGHwAACgkQ7CuRN+Io64Y0cA//UdNTwYW4TGiB
1sZqLS7aNbCYirxcyO6Z4t0fvv8CsXRcKI9OV1iXegRCABYMKcvB542GLujAinOB
+IIc/dojoWVwe1ZxbG/WHyBd0hyE3pgKKm3mNwqBeR5Z4tA0irGdYVnmKpjf+iHP
eupRrdJnr2/Jy3kZkm3Xc0luLopq4XYMSrHUgxpH7oh2cy8RfaLP2TKHcvZybGMO
8v6qXQn2SYYhmaI9E5tvILZQrNH5O5KbHUoktnTpfF1W5lCdpM/yCfKPrnxB8te6
/wg8n++QTwI/txRcy9apzhWg4GyygAO6tVgRYPNzqOXtQgy3AU096FCkVI9OowM1
c8yc9B541qRhL1MScWZtLJF/b+v8QPz0HsqGm1Sixd9wgDeuJA4a0iw2EazeGndp
fX40H99Zko9po5Ql3UdrxhE4RpjJrZ0n47fvB1ZWTHCA85f4lVsMhXZXzIWcmsQQ
I4OWsWb+FBMiSkEZwZPjlOR8UC1UX7I0w4khbfcTDsIAMvc93rAnDq5PZL2FuGSE
P2tUiDryTNepJQSwpQ58UfYF/GFNCuHChdYxAwmSp8fWkT3mACbcRFbJ2fn6ESt+
e8SW1oH6qH4jjdsgYb7hTFhXpao9aAtBjZ7Qxk6Bn7PRa2OPHOGZ5Svjas1zepzC
aKC7FaHUlebqi2htKoqV/TBPpHv41lY=
=wDk1
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by retorquere** [comment]
Can you also get me a new log from build 3423?

**Comment by irmoodie** [comment]
I can also confirm the behaviour of "Found X items without a citation key" increasing with each restart of zotero. My library size is ~1K but X is now shown as 2K+.

I have installed build 3423 and have submitted another log: 69Z3K6E5-euc

**Comment by nocona71** [comment]
here we go: 
[better-bibtex.gpg.zip](https://github.com/retorquere/zotero-better-bibtex/files/10020542/better-bibtex.gpg.zip)

**Comment by retorquere** [comment]
Do you have RSS feeds active?

**Comment by irmoodie** [comment]
> Do you have RSS feeds active?

Yes RSS feeds for about 20 journals.

**Comment by retorquere** [comment]
Can you try build 3428?

**Comment by LamFTS** [comment]
problem solved after removing all RSS feed, but the problem didn't occur even with RSS activation in before.

**Comment by retorquere** [comment]
Build 3428 should have fixed it even with the rss feeds in place.

**Comment by mjthoraval** [comment]
Build 3428 solves the problem for me on Zotero 6.0.19-beta.3+89bc09469, Windows 10.
Thanks!

**Comment by irmoodie** [comment]
> Build 3428 should have fixed it even with the rss feeds in place.

Fixed! Thanks for the quick help!
