### ISSUE TITLE
bracket of Citation Key can't work

### ISSUE THREAD

**Issue by ChristinaHyh** [retorquere/zotero-better-bibtex#2305]
I set the citation key format as `auth.postfix('(') + year.postfix(')')+ journal.abbr.prefix('-[') + shorttitle(3,3).condense(_).prefix(']-')`, it should be like `XXX(2019)-[C]-XXX_XXX_XXX` and it worked before. However, these days it became `XXX2019-[C]-XXX_XXX_XXX`, the bracket can't work now.

**Comment by retorquere** [comment]
BTW an alternative form of your formula could be

```
auth + year.prefix('(').postfix(')')+ journal.abbr.prefix('-[').postfix(']') + shorttitle(3,3).condense(_).prefix('-')
```

which is slightly longer but will get cleaner keys when parts are missing (although the parentheses will still be stripped).

**Comment by ChristinaHyh** [comment]
> BTW an alternative form of your formula could be
> 
> ```
> auth + year.prefix('(').postfix(')')+ journal.abbr.prefix('-[').postfix(']') + shorttitle(3,3).condense(_).prefix('-')
> ```
> 
> which is slightly longer but will get cleaner keys when parts are missing (although the parentheses will still be stripped).

Got it. Thank you! I will try.
