### ISSUE TITLE
How to convert test cases to CSL-JSON

### ISSUE THREAD

**Issue by zepinglee** [retorquere/zotero-better-bibtex#2310]
Hi! I'm working on https://github.com/zepinglee/citeproc-lua, a CSL processor for LaTeX, in which a BibTeX-to-CSLJSON converter is required for better compatibility with traditional TeX users. I find the `.bib` test cases in BBT ([test/fixtures/import](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/import)) very useful for testing the processor. The JSON targets are in Zotero's internal formats and how can I convert them to CSL-JSON? 

I can write simple pieces of JavaScript code like Zotero translators but I'm not familiar with npm package structure. Can you give me some hints on where I can start with? Thanks!

Debug log ID: XYYYAZYD-refs-apse

**Comment by retorquere** [comment]
[csl-json.zip](https://github.com/retorquere/zotero-better-bibtex/files/10024741/csl-json.zip)

Some filename cleanup will be needed, but I think it should be automatable, and I can't guarantee they're in the same order as the bib source.

**Comment by duncdrum** [comment]
👍

**Comment by zepinglee** [comment]
> [csl-json.zip](https://github.com/retorquere/zotero-better-bibtex/files/10024741/csl-json.zip)
> 
> Some filename cleanup will be needed, but I think it should be automatable, and I can't guarantee they're in the same order as the bib source.

Thanks and it helps a lot!
