### ISSUE TITLE
"An error occurred while trying to export the selected file."

### ISSUE THREAD

**Issue by samzukoff** [retorquere/zotero-better-bibtex#2313]
Still having the problem. I think this is the info you needed. Please let me know if I did this wrong or you need something else. Sorry I don't know what I'm doing. Thanks! 

Submitted with Debug ID D318618690 📋
[JavaScript Error: "out of memory"]

[JavaScript Error: "out of memory"]

[JavaScript Error: "out of memory"]

[JavaScript Error: "out of memory"]

version => 6.0.18, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.18, extensions => Better BibTex for Zotero (6.7.38, extension), Zotero LibreOffice Integration (6.0.3.SA.6.0.18, extension, disabled), Zotero Word for Windows Integration (6.0.2.SA.6.0.18, extension, disabled)

(3)(+0061920): Getting contents of C:\Users\samzu\AppData\Roaming\Zotero\Zotero\Profiles\kuo44v21.default\treePrefs.json

(3)(+0000008): Writing column prefs of length 2200 to file C:\Users\samzu\AppData\Roaming\Zotero\Zotero\Profiles\kuo44v21.default\treePrefs.json

(3)(+0026818): HTTP POST "[JavaScript Error: "out of mem…" (809 chars) to https://repo.zotero.org/repo/report?debug=1

(3)(+0000012): POST body gzipped from 809 to 366; 55% savings

(3)(+0000732): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200

(3)(+0010282): {better-bibtex} +null on-idle: idle.observe: {"topic":"idle","data":"10"}

(3)(+0014223): {better-bibtex} +14224 on-idle: idle.observe: {"topic":"active","data":"0"}

_Originally posted by @retorquere in https://github.com/retorquere/zotero-better-bibtex/issues/2288#issuecomment-1320915365_

**Comment by samzukoff** [comment]
Yep, did do it wrong. Hopefully this is what you're looking for?

(3)(+0000000): Using data directory C:\Users\samzu\Zotero
(3)(+0000005): Looking for Firefox profile in C:\Users\samzu\AppData\Roaming\Mozilla\Firefox
(3)(+0000001): Getting contents of C:\Users\samzu\AppData\Roaming\Mozilla\Firefox\profiles.ini
(3)(+0000006): Asynchronously opening database 'zotero'
(3)(+0000000): C:\Users\samzu\Zotero\zotero.sqlite
(4)(+0000026): PRAGMA main.locking_mode=EXCLUSIVE
(4)(+0000001): PRAGMA page_size
(4)(+0000001): PRAGMA cache_size=2000
(4)(+0000001): PRAGMA foreign_keys=true
(4)(+0000015): SELECT version FROM version WHERE schema='system'
(4)(+0000003): SELECT version FROM version WHERE schema='userdata'
(4)(+0000000): SELECT version FROM version WHERE schema='compatibility'
(4)(+0000002): SELECT value FROM settings WHERE setting='db' AND key='integrityCheck'
(3)(+0000001): HTTP GET resource://zotero/schema/global/schema.json
(3)(+0000002): Proxy not required for https://zoteroproxycheck.s3.amazonaws.com/test
(3)(+0000001): HTTP GET resource://zotero/schema/global/schema.json succeeded with 200
(4)(+0000003): SELECT version FROM version WHERE schema='globalSchema'
(3)(+0000000): Database is up to date with global schema version 21 -- skipping update
(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql
(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200
(4)(+0000000): PRAGMA foreign_keys = false
(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql
(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200
(4)(+0000000): SELECT 1 FROM itemDataValues WHERE value=0 LIMIT 1
(4)(+0000001): Beginning DB transaction WPunfzHL
(3)(+0000003): HTTP GET resource://zotero/schema/system.sql
(3)(+0000001): HTTP GET resource://zotero/schema/system.sql succeeded with 200
(3)(+0000001): Updating custom tables
(4)(+0000000): PRAGMA foreign_keys
(4)(+0000000): SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND tbl_name=? ['customItemTypes']
(4)(+0000001): DELETE FROM itemTypesCombined
(4)(+0000002): DELETE FROM fieldsCombined
(4)(+0000001): DELETE FROM itemTypeFieldsCombined
(4)(+0000001): DELETE FROM baseFieldMappingsCombined
(4)(+0000001): INSERT INTO itemTypesCombined SELECT itemTypeID, typeName, display, 0 AS custom FROM itemTypes UNION SELECT customItemTypeID + 10000 AS itemTypeID, typeName, display, 1 AS custom FROM customItemTypes
(4)(+0000001): INSERT INTO fieldsCombined SELECT fieldID, fieldName, NULL AS label, fieldFormatID, 0 AS custom FROM fields UNION SELECT customFieldID + 10000 AS fieldID, fieldName, label, NULL, 1 AS custom FROM customFields
(4)(+0000001): INSERT INTO itemTypeFieldsCombined SELECT itemTypeID, fieldID, hide, orderIndex FROM itemTypeFields UNION SELECT customItemTypeID + 10000 AS itemTypeID, COALESCE(fieldID, customFieldID + 10000) AS fieldID, hide, orderIndex FROM customItemTypeFields
(4)(+0000002): INSERT INTO baseFieldMappingsCombined SELECT itemTypeID, baseFieldID, fieldID FROM baseFieldMappings UNION SELECT customItemTypeID + 10000 AS itemTypeID, baseFieldID, customFieldID + 10000 AS fieldID FRO ...

**Comment by retorquere** [comment]
Please submit a *Better BibTeX* log from the help menu.

**Comment by samzukoff** [comment]
Sorry, I don't think this came up the first time (or more likely I just missed it): GVEAN8DT-euc

**Comment by retorquere** [comment]
Sorry, you were correct, it is the same problem as #2288. Please re-join that discussion.
