### ISSUE TITLE
Got an export issue while exporting the Better BibTeX file.

### ISSUE THREAD

**Issue by wellerwen** [retorquere/zotero-better-bibtex#2314]
Report ID:  D1299464020

Steps to reproduce:

1. open Zotero
2. Right-click on the whole library in the left pane
3. choose "export library" in the context menu
4. choose the `better biblatex` format in pop-up
5. select "export notes"
6. willing to select "keep updated" as soon as it gets to work

Expected behavior:
exporting a `.bib` file for my whole library

Actual behavior:
pop-up saying: "An error occured while trying to export the selected file"

I have checked similar issues on the Zotero forum and here, but I haven't found the solution.
![屏幕截图 2022-11-20 165109](https://user-images.githubusercontent.com/90732059/202893523-8b2a56b8-ec96-47e8-b66e-70f365d7d17d.png)

Enclosed is the debug log.
[debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/10049228/debug.txt)

**Comment by retorquere** [comment]
The attached debug.txt is a jumbled mess, sorry. Please send a log as described in point 2. of the bot message.

**Comment by wellerwen** [comment]
Report ID: D416402413

I find that the citation keys do not show at the top of "Info". I am not sure whether this issue causes the exporting issue.

![屏幕截图 2022-11-20 174146](https://user-images.githubusercontent.com/90732059/202895301-2bf23c6e-2978-4380-b2e0-9bc8a4eac446.png)

**Comment by retorquere** [comment]
Please re-read the bot instruction at point 2. I cannot read `D<number>` reports, those go to Zotero, not me.

**Comment by wellerwen** [comment]
Debug log ID: 6IG5N63P-euc
[debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/10049326/debug.txt)

There is no citation key at the top of the 'Info' pane so it may be an issue related to the citekey generation. I reproduced the debug log following the bot instruction at point 1.

I am newer using Zotero. Thanks a lot.

**Comment by wellerwen** [comment]
> Please re-read the bot instruction at point 2. I cannot read `D<number>` reports, those go to Zotero, not me.

Okay, I will do it right now.

**Comment by retorquere** [comment]
No need to attach `debug.txt`, the debug ID suffices. Can you go into the Help menu, restart with debugging enabled, reproduce the problem, then send a log like you did the last time?

**Comment by wellerwen** [comment]
> No need to attach `debug.txt`, the debug ID suffices. Can you go into the Help menu, restart with debugging enabled, reproduce the problem, then send a log like you did the last time?

That's fine. Thanks.

**Comment by wellerwen** [comment]
Debug log ID：EQ478WC5-apse

![1](https://user-images.githubusercontent.com/90732059/202897006-b5e2fe35-e42f-42a6-92d2-b3eface220c6.png)

the log file is too big to upload here.

**Comment by wellerwen** [comment]
[EQ478WC5-apse.zip](https://github.com/retorquere/zotero-better-bibtex/files/10049385/EQ478WC5-apse.zip)

**Comment by retorquere** [comment]
Please don't upload log files here. It only adds clutter. Just the ID `EQ478WC5-apse` is enough.

**Comment by retorquere** [comment]
Can you go into preferences -> `Advanced` -> `Config Editor` -> `I accept the risk` -> search for `scrubDatabase`, double-click it to set it to `true`, then restart Zotero.

**Comment by wellerwen** [comment]
OKay, let me try.

**Comment by retorquere** [comment]
Can you please install build 3448 and go into the Help menu, restart with debugging enabled, reproduce the problem, then send a log like you did the last time?

This build adds only logging, it will not fix the problem, no screenshot needed, just the debug log ID.

**Comment by wellerwen** [comment]
Sure. I got the new debug ID following your instruction.

The debug log ID: UJ2ANITY-apse

Thanks for your patience.

**Comment by retorquere** [comment]
Same procedure please

**Comment by wellerwen** [comment]
> Same procedure with 3450 please

It does not work. The same problem exists as in previous versions. The Debug ID: JX74F8MQ-apse

Thanks.

**Comment by retorquere** [comment]
> It does not work. The same problem exists as in previous versions. The Debug ID: JX74F8MQ-apse

That was still only for diagnosis. 3453 should fix it.

**Comment by wellerwen** [comment]
This version works very well now.  How professional you are! 

Thanks for your patience and help. You really helped me a lot. I have learned how to put out the debug log and install the BBT. 

Thank you!

**Comment by wellerwen** [comment]
## Report ID: 6J4V2YDJ-apse

## Steps to reproduce:

1. Right-click on the whole library in the left pane in Zotero

2. choose the `export library` in the context menu

3. choose the `Better BibTeX` format in the pop-up while selecting `keep updated` in Translator Options

4. Export a .bib file into my local folder

5. Copy a citation key of literature from Zotero, for example, “JianChu_2021_Hometown”

6. Cite the key with the format [@JianChu_2021_Hometown] in my Typora

7. Save the Markdown file

8. Interpret the .md file using Pandoc as follows:

   `C:\Users\Administrator>pandoc --cite --bibliography="F:/A0_MarkDown/literatureBibtex/2_Institution_Econ.bib" "F:/A0_MarkDown/typoratry.md" -o "F:/A0_MarkDown/demo-citation.docx`

## Expected behavior:

  exporting a `.docx` file with well-formatted literature

## Actual behavior:

CMD shows: 

`Error reading bibliography file F:/A0_MarkDown/literatureBibtex/2_Institution_Econ.bib:
(line 6234, column 27):
unexpected '<'`

Then I opened the .bib file and found that there exists the sign `'<'` among **Chines literature**. So I just exported English literature into the .bib file and interpreted the MD file again. I got the expected results this time. Also, I tried to export my literature including Chinese and English ones but with the `Better CSL JSON `format. The interpretation was pretty good.

Therefore, I do not understand why Pandoc cannot interpret Chinese literature with the `Better BibTeX` format.

Thanks.

**Comment by retorquere** [comment]
please open a new issue for this.
