### ISSUE TITLE
export errors on Windows/sluggish performance

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#2315]
.

**Comment by devonwp** [comment]
I don't see where I can edit this. In particular, I don't see as "Better BibTeX" tab of the Edit > Preferences menu.

**Comment by retorquere** [comment]
I don't see your message on github. If you don't see the prefs at all, that
must be a bug. Please open a new issue for this.

**Comment by retorquere** [comment]
That means the translators were not cleaned up when you un-installed bbt (which would be a bug), or you are non-zoyero-cloud-syncing te zotero profile and they came over from another PC.

**Comment by devonwp** [comment]
I don’t believe I ever uninstalled BBT intentionally. I also use Zotero
cloud sync.

**Comment by retorquere** [comment]
That's good news for me because if plugins disappear without user involvement that would be a zotero bug rather than a BBT bug 😏

**Comment by retorquere** [comment]
No, a reset of your translators from the zotero prefs and a restart will reinstall the bbt translators and you should be good to go.

**Comment by devonwp** [comment]
Thanks!

Do you just mean Edit > Preferences > Advanced > General > Miscellaneous >
[Automatically check for updated translators and styles > Update?

**Comment by retorquere** [comment]
Select “Reset Translators” from the Advanced pane of the Zotero preferences.

**Comment by devonwp** [comment]
Ah okay, thank you!

**Comment by jingjieyeo** [comment]
> Select “Reset Translators” from the Advanced pane of the Zotero preferences.

I had the same issue (Zotero 7.0.0-beta.16+1766f8bb5 and BBT Jul 3rd release) so I tried your suggestion to reset translators. But now `export collections` does not even show BBT even though I removed and re-installed the BBT add-on. Any ideas what the issue is? Should I re-install Zotero entirely?

**Comment by retorquere** [comment]
There isn't yet a compatible BBT release for Z7, but there's a decent chance tonight there will be. Follow #2522 for news on that.

**Comment by retorquere** [comment]
In fact Zotero shouldn't have allowed BBT to install into Zotero 7 (yet).

**Comment by retorquere** [comment]
#2829 has a fix. I'm keeping #2315 for the citation key display

**Comment by retorquere** [comment]
> > Select “Reset Translators” from the Advanced pane of the Zotero preferences.
> 
> I had the same issue (Zotero 7.0.0-beta.16+1766f8bb5 and BBT Jul 3rd release) so I tried your suggestion to reset translators. But now `export collections` does not even show BBT even though I removed and re-installed the BBT add-on. Any ideas what the issue is? Should I re-install Zotero entirely?

Versions before the drop on #2829 do not work at all on b70+. Reinstalling Zotero won't fix that unless you're downgrading. But the fix on #2829 should make that irrelevant, I'm going to make a new release out of that right now.

**Comment by retorquere** [comment]
I have scheduled the work to address this for next week.

**Comment by retorquere** [comment]
With Zotero 7 beta, you can open a new issue, and send a debug log.

**Comment by retorquere** [comment]
This implements the first of the two caches. This should use less memory *and* be faster (after the cache fills). Working on the 2nd cache.

**Comment by retorquere** [comment]
Make sure to have background export on.

**Comment by retorquere** [comment]
All cache upgrades have been finished in this build. I'd appreciate it if someone that previously had problems on Windows could test, but this is going into the next release.
