### ISSUE TITLE
Choosed zotero citekey but BBT changed a few of them

### ISSUE THREAD

**Issue by markdimi** [retorquere/zotero-better-bibtex#2316]
Hello!

Because I have a current article that I am writing, I choosed zotero citekey but in the export BBT added "-1" in the end of a few citekeys (12).

Probably it is something that has to do with duplicates, because after I eliminate all duplications (with merges) the best part of citekeys didn't have  "-1" in the end, but they still remain two entries with it.

I selected one entry and selected the BBT debug log.

Debug log ID: WVGTUHV8-refs-euc

**Comment by retorquere** [comment]
When you merge items, your retain the key if the master item you chose in the merge. You can have the key regenerated by selecting the items, right-clicking, and selecting "bbt -> refresh".

**Comment by markdimi** [comment]
Yep, it was pretty straightforward. Thank you very much and kudos for your work and support!
