### ISSUE TITLE
Pandoc cannot interpret Chinese literature with the Better BibTeX format？

### ISSUE THREAD

**Issue by wellerwen** [retorquere/zotero-better-bibtex#2317]
## Steps to reproduce:

1. Right-click on the whole library in the left pane in Zotero

2. choose the `export library` in the context menu

3. choose the `Better BibTeX format in the pop-up while selecting `keep updated` in the Translator Options

4. Export a .bib file into my local folder

5. Copy a citation key of literature from Zotero, for example, “JianChu_2021_Hometown”

6. Cite the key with the format [@JianChu_2021_Hometown] in my Typora

7. Save the Markdown file

8. Interpret the .md file using Pandoc as follows:

   `C:\Users\Administrator>pandoc --cite --bibliography="F:/A0_MarkDown/literatureBibtex/2_Institution_Econ.bib" "F:/A0_MarkDown/typoratry.md" -o "F:/A0_MarkDown/demo-citation.docx`

## Expected behavior:

  exporting a `.docx` file with well-formatted literature

## Actual behavior:

CMD shows: 

`Error reading bibliography file F:/A0_MarkDown/literatureBibtex/2_Institution_Econ.bib:
(line 6234, column 27):
unexpected '<'`

Then I opened the .bib file and found that there exists the sign `'<'` in **Chines literature**. So I just exported English literature into the .bib file and interpreted the MD file again. I got the expected results. Also, I tried to export my literature including Chinese and English ones but with the `Better CSL JSON `format. The interpretation was pretty good.

Therefore, I do not understand why Pandoc cannot interpret Chinese literature with the `Better BibTeX` format.

Thanks.

**Comment by retorquere** [comment]
I need you to right-click the item in question in Zotero and send a BBT debug log from the popup menu that appears. The debug log ID will have `-refs-` in it.

Can you also paste the bibtex entrty that has the problem here?

**Comment by wellerwen** [comment]
## Debug log ID: 2AXVCQBL-refs-apse

## Some entries
Can I just paste a few entries? All entries are very long.

For example:
```
@article{Chen_2018_LiuDongDeSheHuiZiBen----ChuanTongZongZuWenHuaShiFouYingXiangYiMinJiuYe?,
  title = {流动的社会资本\textemdash\textemdash 传统宗族文化是否影响移民就业?},
  author = {陈, 斌开 and 陈, 思宇},
  year = {2018},
  journal = {经济研究},
  volume = {53},
  number = {3},
  pages = {35--49},
  issn = {0577-9154},
  langid = {zh\_CN},
  annotation = {89 citations(CNKI)[8-15-2022]{$<$}北大核心, CSSCI{$>$}}
}
```
```
@article{Guo_2014_ZongZuWangLuoYuCunZhuangShouRuFenPei,
  title = {宗族网络与村庄收入分配},
  author = {郭, 云南 and 姚, 洋 and Foltz, Jeremy},
  year = {2014},
  journal = {管理世界},
  number = {1},
  pages = {73-89+188},
  issn = {1002-5502},
  doi = {10.19744/j.cnki.11-1235/f.2014.01.010},
  langid = {zh\_CN},
  annotation = {112 citations(CNKI)[8-15-2022]{$<$}北大核心, CSSCI{$>$}}
}

```

Thanks.

**Comment by wellerwen** [comment]
The citation keys are generally long for Chinese literature, so it is not convenient to cite when writing.  Can I shorten the Chinese citation key to the format of the English ones (Such as Bambio_2018_Land)?

**Comment by retorquere** [comment]
```
@article{Chen_2018_LiuDongDeSheHuiZiBen----ChuanTongZongZuWenHuaShiFouYingXiangYiMinJiuYe?,
  title = {流动的社会资本\textemdash\textemdash 传统宗族文化是否影响移民就业?},
  author = {陈, 斌开 and 陈, 思宇},
  year = {2018},
  journal = {经济研究},
  volume = {53},
  number = {3},
  pages = {35--49},
  issn = {0577-9154},
  langid = {zh\_CN},
  annotation = {89 citations(CNKI)[8-15-2022]{$<$}北大核心, CSSCI{$>$}}
}
```

renders without issue if I use it on overleaf, so this appears to be a pandoc problem. But unless you are rendering to PDF, CSL-JSON should be preferred anyhow: https://retorque.re/zotero-better-bibtex/exporting/pandoc/#use-csl-not-bibtex-with-pandoc

**Comment by wellerwen** [comment]
OKay, thanks.
