### ISSUE TITLE
Force locator (instead of suffix) on live export

### ISSUE THREAD

**Issue by mac-obs** [retorquere/zotero-better-bibtex#2318]
Hi,

First of all: Thank you for developing this extension. BBT has helped me tremendously while working on my dissertation. I am using your Pandoc filter to export from .md to docx. via pandoc with Zotero live citations. 

My question: Is there a way to force pandoc to treat something as a locator (instead of it being automatically recognized as a suffix)? 
According to the [pandoc user's guide ](https://pandoc.org/MANUAL.html#extension-citations) "you can force something to be treated as a locator by enclosing it in curly braces or prevent parsing the suffix as locator by prepending curly braces. Z.B. `[@smith{ii, A, D-Z}, with a suffix]`". This works for me perfectly using the normal (non live citations = citeproc ) export. However, I cannot get this to work using the live citations. 

In my specific case I frequently need to use "Rn. X" as a locator ("Rn." = margin number; "X" = random number). For example, if my citeky looks like this [@GAMaduro2009-09-30Rottmann, {Rn. 15}], on export I will get "Rn. 15" as a suffix using the live citation, not as a locator. Using the citeproc pandoc export, Zotero recognizes "Rn. 15" as the locator. 
(It's relevant because according to the citation guideline I need to follow, the case name should appear after the locator (margin number) but before the suffix.)

I don't know if this even concerns BBT, but any help would be truly appreciated. 

Deubg log ID: PFKGEKEJ-refs-euc

Best,

Michael

**Comment by retorquere** [comment]
Yep, this concerns BBT; Zotero supports only a fixed set of locator types, margin number is not among them.

**Comment by retorquere** [comment]
> Using the citeproc pandoc export, Zotero recognizes "Rn. 15" as the locator.

I don't understand what you mean to convey here, sorry.

**Comment by mac-obs** [comment]
Okay, great. Sorry, for the misunderstanding, that's on me. I try to be more clear: 

1. Desired Citation: The citation guideline I need to follow requires me to have the margin number in the middle of some information from the Zotero entry (in the example "Rottmann" which is the name of a case by a European Court). 

So the citation I would like to have at the end looks like this (Rn. 15) being the page / margin number I added to the specific citation: 
EuGH, Urt. v. 03.02.2010 – C-135/08, ECLI:EU:C:2010:104, **Rn. 15** – Rottmann.

2. If the citekey in .md looks like this "[@EuGH2010-02-03Rottmann, Rn. 15]", pandoc will add the margin number at the end of the citation (which is not where I want it to go): 
EuGH, Urt. v. 03.02.2010 – C-135/08, ECLI:EU:C:2010:104, – Rottmann, **Rn. 15**.

I think this is because "Rn. 15" is not recognized as a locator, but as a suffix.

3. I found out that I can force pandoc to recognize "Rn. 15" as the locator by using { }. If my citekey is "[@EuGH2010-02-03Rottmann, {Rn. 15}]" and I export without live citation (using pandoc --citeproc) I manage to get the citation I want: 
EuGH, Urt. v. 03.02.2010 – C-135/08, ECLI:EU:C:2010:104, **Rn. 15** – Rottmann.

4. If I try to do the same with live citations it doesn't work. If I export with live citations, refresh with the Zotero Word Plugin, and then check the citation, I can see that Zotero is using "Rn. 15" to fill the suffix, not to fill the locator (the locator type remains page, which is fine for my purposes because I added the Rn. manually). See here:  
 ![grafik](https://user-images.githubusercontent.com/111188217/203094946-d58310df-d598-4c55-a92d-aec81cdf4901.png)

I could now manually change the entries and move "Rn. 15" to page from suffix, but that would be a lot of work for each and every footnote.

**Comment by mac-obs** [comment]
You closing this means you cannot help? Or was that due to something I did? Sorry, I am not familiar with the customs on GitHub.

**Comment by retorquere** [comment]
You closed the issue.

![image](https://user-images.githubusercontent.com/132108/203495385-bf9d17e8-ff5b-4999-80b1-71e4a333a25c.png)

**Comment by retorquere** [comment]
> So the citation I would like to have at the end looks like this ("Rn. 15" being the page / margin number I added to the specific citation):
> EuGH, Urt. v. 03.02.2010 – C-135/08, ECLI:EU:C:2010:104, **Rn. 15** – Rottmann.

Can you create a Word document (using Word and Zotero, no pandoc) that has a Zotero reference like this? If so, please attach it here, and I'll see what I can do. If it's not possible to create such a document using Word+Zotero, then it would look like Zotero just doesn't support it, in which case I can't create a Zotero-compatible live document with it.

**Comment by mac-obs** [comment]
Sorry for closing it then, didn't see the default opion when commenting was closing the issue.

Here is the Word document: [Citation_Test.docx](https://github.com/retorquere/zotero-better-bibtex/files/10078052/Citation_Test.docx)

**Comment by mac-obs** [comment]
Could you access the document?

**Comment by mac-obs** [comment]
Could you access the document?

**Comment by retorquere** [comment]
Yes, I could, but haven't yet found time to dive into it. If this is what you want, that's achievable. But Zotero will assume this is a page number (see "add/edit citation").

**Comment by retorquere** [comment]
Can you try https://gist.github.com/98426c9afa569bf213a051f70b9805d9 ?

**Comment by mac-obs** [comment]
It works perfectly! 
Both forcing the locator with curly braces and prevent parsing the suffix as locator by prepending curly braces!
Thank you so much! You have saved me a lot of work! Amazing! :)
