### ISSUE TITLE
Citation key is too long for Chines literature

### ISSUE THREAD

**Issue by wellerwen** [retorquere/zotero-better-bibtex#2320]
The citation keys are generally long for Chinese literature, so it is not convenient to cite when writing. Can I shorten the Chinese citation key to the format of the English ones (Such as Bambio_2018_Land)? 

I have set the Citation key format as `auth+"_"+year+"_"+Title.skipwords.select(1,1)` .

**Comment by retorquere** [comment]
If you send a debug log per instruction 1. I will get your current key format and the sample that generates this particular citekey. It makes it much easier to replicate the problem exactly.

**Comment by wellerwen** [comment]
## Debug log ID: 9JN24N2D-refs-apse

## Steps to reproduce:

1. Right-click on the specific collection in the left pane of Zotero library

2. choose the `export library` in the context menu

3. choose the `Better CSL JSON`  in the pop-up while selecting `keep updated` in the Translator Options

4. Export a .json file into my local folder

5. Copy a citation key of literature from Zotero, for example, 

   - `“Yang_2022_ShuZiHuaZhuanXingYuQiYeChuangXinXiaoLu----LaiZiZhongGuoZhiZaoYeShangShiGongSiDeJingYanZhengJu” `
   - `Fang_2022_ShuZiHuaZhuanXingShiFouCuJinLiaoQiYeNeiGongTongFuYu?----LaiZiZhongGuoAGuShangShiGongSiDeZhengJu`  
   
6. Cite the key with the format [@Fang_2022_ShuZiHuaZhuanXingShiFouCuJinLiaoQiYeNeiGongTongFuYu?----LaiZiZhongGuoAGuShangShiGongSiDeZhengJu] in my Typora

7. Save the Markdown file

8. Interpret the .md file using Pandoc as follows:

```html
C:\Users\Administrator>pandoc --cite --bibliography="F:/A0_MarkDown/literatureBibtex/digital.json" "F:/A0_MarkDown/typoratry.md" -o "F:/A0_MarkDown/demo-citation3.docx"
```

## Expected behavior:

Exporting `.docx` file with well-formatted literature

## Actual behavior:

I could not receive the .docx file as CMD pop-up shows:

```html
[WARNING] Citeproc: citation Fang_2022_ShuZiHuaZhuanXingShiFouCuJinLiaoQiYeNeiGongTongFuYu not found
[WARNING] Citeproc: citation Pan_2022_ShuZiHuaZhuanXingYuQiYeChuangXin not found
[WARNING] Citeproc: citation Yang_2022_ShuZiHuaZhuanXingYuQiYeChuangXinXiaoLu not found
```
I think this issue may be caused by the citekey generation. I have tried two ways to cite the literature. First, I used the Pandoc to interpret English literature, such as `@Acemoglu_2022_Automation`. It worked very well. Then, I just interpreted Chinese literature, which has relatively short citation keys, such as  `@Guo_2014_ZongZuWangLuoYuCunZhuangShouRuFenPei` and `@Li_1994_DangDaiZhongGuoNongCunZongZuWenTiYanJiu`. It also worked well.

Therefore, based on my understanding, the issue of interpretation is that some long citation keys are not accurate for Pandoc to read. Generally, the citation key for Chinese literature is not concise and clear as that for English literature.

Looking forward to your help. Thanks.

**Comment by wellerwen** [comment]
Chinse citation key is composed of the surname of the first author, the year of publication, and the Chinese translation (Pronounce: pin yin) of the full title rather than the first word.

**Comment by retorquere** [comment]
I'll explain below how to get shorter citekeys, but first: this is another error in pandoc, because this renders just fine:

```
\documentclass{ctexart}
%\usepackage[utf8]{inputenc}
\bibliographystyle{plainnat}
\usepackage{url}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{Fang_2022_ShuZiHuaZhuanXingShiFouCuJinLiaoQiYeNeiGongTongFuYu?----LaiZiZhongGuoAGuShangShiGongSiDeZhengJu,
  title = {流动的社会资本\textemdash\textemdash 传统宗族文化是否影响移民就业?},
  author = {陈, 斌开 and 陈, 思宇},
  year = {2018},
  journal = {经济研究},
  volume = {53},
  number = {3},
  pages = {35--49},
  issn = {0577-9154},
  langid = {zh\_CN},
  annotation = {89 citations(CNKI)[8-15-2022]{$<$}北大核心, CSSCI{$>$}}
}
\end{filecontents}

\begin{document}
\cite{Fang_2022_ShuZiHuaZhuanXingShiFouCuJinLiaoQiYeNeiGongTongFuYu?----LaiZiZhongGuoAGuShangShiGongSiDeZhengJu}
\bibliography{\jobname.bib}
\end{document}
```

**Comment by wellerwen** [comment]
Okay,  thanks. I guess the pandoc can not render Chinese literature with irregular citation keys as aforementioned.

**Comment by retorquere** [comment]
I'll get to the citekey cleanup in the afternoon, things have gotten very busy suddenly.

**Comment by wellerwen** [comment]
Thanks! Take your time.

**Comment by retorquere** [comment]
Please install build 2320, enable "Enable Jieba" in the BBT preferences, restart, and set the formula to something like `auth+'_'+year+'_'+shorttitle`.

**Comment by retorquere** [comment]
> Debug log ID: GTB6E54J-refs-apse

I don't see this report, can you submit again?

> I am not sure whether this version can work well on the desktop computer at my office, but this version is really not able to fix the citekey issue on my laptops. Both two laptops cannot present citation keys concisely as I want. One shows the format as `fangShuZiHuaZhuanXingShiFouCuJinLiaoQiYeNeiGongTongFuYuLaiZiZhongGuoAGuShangShiGongSiDeZhengJu2022`, while the other is `__2022-3` for the same Chinese literature, although I have installed the latest version and set the `Enabel jieba` mode. 

Without the log, I can't really say what is happening.

> Besides, both computers failed to change the citekey format as `[auth][year][shorttitle]` or `[auth]_[year]_[shorttitle]`. It seems that this version does not allow me to change the citekey format as I want.

Failed in what way? When I enter `[auth]_[year]_[shorttitle]`, BBT changes that to `auth.fold+"_"+year+"_"+shorttitle` (which is the new format for citekey formulas), and that seems to work without problems for me.

**Comment by wellerwen** [comment]
Okay, here is the new debug log ID: Z6D7XJHC-refs-apse.

`Failed in what way? When I enter [auth]_[year]_[shorttitle], BBT changes that to auth.fold+"_"+year+"_"+shorttitle (which is the new format for citekey formulas), and that seems to work without problems for me.`

When I changed the format to `[auth][year][shorttitle]` or `[auth]_[year]_[shorttitle]` in BBT preferences, there was no any change in the Info pane of Zotero, although I restarted Zotero. What the citation key really shows in the pane is in the way like author_shorttitle_year, such as `acemoglu_automation_2022`.

Thanks.

**Comment by retorquere** [comment]
They don't change automatically. You have to select the items, right click, and choose `Better BibTeX` -> `Refresh`.

**Comment by wellerwen** [comment]
Oh, my God. I made such a low mistake.

I have refreshed all citation keys. Most of them are concise and clear now, except for a few citekeys of Chinese literature, which are still long but not a big problem. Anyway, Pandoc can now render all literature normally.

I really appreciate your help. Thanks so much!
