### ISSUE TITLE
Single last name (e.g. corporate) authors not exported correctly when Zotero has no first name

### ISSUE THREAD

**Issue by tweedyf** [retorquere/zotero-better-bibtex#2323]
When exporting a Zotero entry with a multiple-word last name in the author field and no first name, the resulting BibTeX file is incorrectly generated. For example:

In Zotero:
```
Last Name: Ice Cube
First name: 
```

In the BetterBibTeX export:
`author = {Ice Cube}`

But should instead be:
`author = {{Ice Cube}}`

This doesn't arise for multiple-word last names when a first name is present in Zotero.

**Comment by tweedyf** [comment]
Debug ID: K7KLTRLK-refs-euc

**Comment by retorquere** [comment]
So why not switch to a single-part name here? That's what it's for.

**Comment by tweedyf** [comment]
Yes, that works.

This still seems like incorrect behavior by BetterBibTeX, so I thought you would like to know.

**Comment by retorquere** [comment]
If there's a first name, it goes after the comma, and the last name does not need bracing.
