### ISSUE TITLE
Replace jounral names with custom abbreviations in bib file

### ISSUE THREAD

**Issue by HNLala** [retorquere/zotero-better-bibtex#2325]
Debug Log ID: F6TBZEVE-refs-euc

Is there a way to provide a custom acronyms.csv/a dictionary to replace the entries in the "journal" records of the bib file?
For example, in the entry included in the log file, I would like to replace `journal = {Astronomy and Astrophysics}` with `journal = {\aap}`.

Thanks a lot.

**Comment by retorquere** [comment]
How many of these journal records would there be? If they don't need to be loaded from disk a postscript could do it, but it'd be unwieldy for large lists.

**Comment by HNLala** [comment]
Less than twenty.

**Comment by retorquere** [comment]
```
if (Translator.BetterBibTeX && tex.has.journal) {
  const journals = {
    "astronomy and astrophysics": "{\\aap}",
    // add more journals here
  }
  const journal = journals[tex.has.journal.value.toLowerCase()]
  if (cmd) tex.has.journal.bibtex = journal
}
```

**Comment by retorquere** [comment]
assuming addressed
