### ISSUE TITLE
debug-bridge failed: SyntaxError: missing variable name 

### ISSUE THREAD

**Issue by redleafnew** [retorquere/zotero-better-bibtex#2328]
The procedure was followed: https://github.com/retorquere/zotero-better-bibtex/tree/50a4464df659360f3196bcc1d30c0012763977ed/test/fixtures/debug-bridge in VSCode.

The code in a js file as:

```
var items = ZoteroPane.getSelectedItems();
var item = items[0]; 
return item;
```

However it prompted me:

```
debug-bridge failed: SyntaxError: missing variable name
init@chrome://zotero-debug-bridge/content/debug-bridge.js:33:24
Zotero.Server.DataListener.prototype._processEndpoint<@chrome://zotero/content/xpcom/server.js:526:26
tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.coroutine/<@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:201:9
Zotero.Server.DataListener.prototype._bodyData@chrome://zotero/content/xpcom/server.js:339:5
```

When a simple code` return 'a'; `was tested, it prompt me as `'null'`.

Can anysome give me advice.

Thanks.

2. selecting the problematic reference(s)
3. right-clicking them
4. choose `BBT debug log` from the popup menu.

If you are sure your question does not relate to items in your library at all, just select any one item in your library.

Please remove this boilerplate before submitting your issue. Thank you.

**Comment by retorquere** [comment]
```
var items = Zotero.getActiveZoteroPane().getSelectedItems();
var item = items[0]; 
return item;
```

**Comment by redleafnew** [comment]
Thanks for your kind reply.

the error message still exist. 
![image](https://user-images.githubusercontent.com/22135631/205257790-72507121-183b-45e0-9929-b80cc19421ec.png)
 
And I created a new profile through zotero.exe -p, installed debug-bridge-6.7.9.emile.limonia.xpi, and created extensions.zotero.debug-bridge.password, it still doesn't work.

**Comment by redleafnew** [comment]
Debug output in Zotero

```

version => 6.0.19-beta.6+3d8bbb3e5, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.19-beta.6+3d8bbb3e5, extensions => Zotero LibreOffice Integration (6.0.3.SA.6.0.19-beta.6+3d8bbb3e5, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.19-beta.6+3d8bbb3e5, extension), Zotero Debug Bridge (0.1.5, extension)

(3)(+0060441): Getting contents of E:\xxx\treePrefs.json

(3)(+0000004): Writing column prefs of length 2110 to file E:\xxx\treePrefs.json

(5)(+0011793): POST /debug-bridge/execute?password=CTT HTTP/1.1 Host: 127.0.0.1:23119 User-Agent: curl/7.64.1 Accept: */* Content-Type: application/javascript Content-Length: 3

(3)(+0000011): debug-bridge: executing var

(3)(+0000001): debug-bridge failed (0ms): SyntaxError: missing variable name

(5)(+0000003): HTTP/1.0 500 Internal Server Error X-Zotero-Version: 6.0.19-beta.6+3d8bbb3e5 X-Zotero-Connector-API-Version: 2 Content-Type: application/text debug-bridge failed: SyntaxError: missing variable name init@chrome://zotero-debug-bridge/content/debug-bridge.js:33:24 Zotero.Server.DataListener.prototype._processEndpoint<@chrome://zotero/content/xpcom/server.js:526:26 tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16 module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18 module.exports/Promise.coroutine/<@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:201:9 Zotero.Server.DataListener.prototype._bodyData@chrome://zotero/content/xpcom/server.js:339:5 Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:314:5 Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:208:7

```

**Comment by retorquere** [comment]
You have `var` selected. Either select-all, or select nothing, before running the script. VSCode sends the selected text.

**Comment by redleafnew** [comment]
One item was selected in Zotero, and no code was selected in VSCode.

And I selected the code in VSCode and press ctr+Alt+k，doesn't work.

Select nothing in zotero, doesn't work. either.

**Comment by redleafnew** [comment]
In my home computer, the same operation and same code work.
It's weird.

**Comment by retorquere** [comment]
The only way I could replicate it is if I selected just `var`. Is there a difference if you save the file first?

**Comment by redleafnew** [comment]
no. I have saved the file before run the code.
And it taks several seconds to run in my work computer, normally, it takes less than one second in my home computer.
Is it possible some applications blocked the visit to zotero by VSCode?

**Comment by retorquere** [comment]
I can't say. But it seems something is coming through, or you wouldn't be getting this error.
