### ISSUE TITLE
Automatic export not working properly (2min delay) => Solved, the delay is a setting that can be changed

### ISSUE THREAD

**Issue by Oskiator** [retorquere/zotero-better-bibtex#2329]
Hi,
I get a similar problem than described here : https://github.com/retorquere/zotero-better-bibtex/issues/1958
But as I work on a different environment I thougt it was better to open a new ticket
Log : 78QMAVE7-euc ; [78QMAVE7-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/10146994/78QMAVE7-euc.zip)

## Bug
Adding a new reference seems to trigger auto-export but it takes a lot of time
  - When I add a new reference, "Scheduled Better BibTex" stay frozen 2min before updating. ![image](https://user-images.githubusercontent.com/96892939/205453921-bff8fa6a-aa0f-4900-97b1-267aa8767b3c.png) 

![image](https://user-images.githubusercontent.com/96892939/205453552-0d8166a2-6fd0-4b17-b75d-2da0f7c28337.png)
Keep updated is checked

![image](https://user-images.githubusercontent.com/96892939/205453572-ff3ce1d2-8278-4b2c-9ec2-dce7f03c8b7b.png)

## What I've tried
- reinstalling plugin
- update zotero and plugin to the last version => no changes
- disabling Zotero sync => no changes
- restarting zotero and see if it trigger or not BBT. It doesn't.
- Changing exported file location to the root of my hard drive. 
- Tried with format "BibTex" and "BibLaTex"
- Save to Zotero from Firefox and from Chrome

## Additional info
- I don't remember since when it stopped working fluently, but I remember that it does work when I started using it. (not sure, but I think end of 2021 it was working)
- Working on windows 10
- I don't get any error.
- The autoexport is really useful for me as I can then import references from the updated file directly to obsidian. I tried also to close obsidian to avoid eventual interferences. 

I would be happy to have some help there 🙂
Thanks a lot for your work.
Enjoy your day !

## EDIT : Solution
In fact, that was not a bug, but a setting. The delay was set to 127 seconds.
![image](https://user-images.githubusercontent.com/96892939/205487539-9f8a3ce1-f7e9-47b8-a507-4d56f6c85322.png)

Answer by retorquere : 
> If you open zotero's hidden prefs under advanced - config editor, search for autoExportDelay, right-click and reset, the problem should go away.

**Comment by retorquere** [comment]
Your autoExportDelay is set to 127, so two minutes is about right. If you open zotero's hidden prefs under advanced - config editor, search for autoExportDelay, right-click and reset, the problem should go away.

**Comment by Oskiator** [comment]
oooh ! Magic ! Thanks very much. That's really helpful. 
Is there any inconvenients to set it below 5 ? 
Many thanks

**Comment by retorquere** [comment]
The lower it's set, the higher the chance that you're still editing the same item or another item in the same export, and if that happens you'll get overlapping exports.

**Comment by Oskiator** [comment]
👌🙏 Many thanks.
