### ISSUE TITLE
"Keep Updated" Option Greyed Out

### ISSUE THREAD

**Issue by adham-elarabawy** [retorquere/zotero-better-bibtex#2330]
Just did a fresh install of zotero (version 6.0.18) and zotero-better-bibtex (latest release 6.7.42 xpi), and for some reason, I cannot enable the "keep updated" option when exporting. Image attached for reference. I tried this for both exporting a collection and a library and it still didn't work.

![image](https://user-images.githubusercontent.com/9634713/205469123-c634dbfe-ffde-4c63-8ba3-375b01d4f5f9.png)

**Comment by retorquere** [comment]
You cannot check "keep updated" when "export files" is on.

**Comment by adham-elarabawy** [comment]
Oh thank you! It works now.
