### ISSUE TITLE
What's the default citation key format of BBT?

### ISSUE THREAD

**Issue by Kantomat** [retorquere/zotero-better-bibtex#2331]
Hi,

I have just installed Zotero-better-bibtex. It is great because it allows a smooth cooperation with apps like zettlr.
I have the following question: In the installation process I was asked to choose a citation key format. Unfortunately I didn't choose "BBT" but Zotero. Obviously it is possible to change this in Preferences -> Better BibTeX -> Citation-Key. I couldn't find the default citation key of BBT in the Documentation. Could you tell me the default citation key, that I might replace it? 
Thank You and kind regards,
Sebastian 
Debug-ID: NGE9REP4-euc

**Comment by Kantomat** [comment]
Debug-ID: NGE9REP4-euc

**Comment by retorquere** [comment]
You got there before me. The non-zotero default is `auth.lower + shorttitle(3,3) + year`, but that just happens to be my preference, nothing more sophisticated than that.
