### ISSUE TITLE
Citation Key generated is too long for Chinese articles

### ISSUE THREAD

**Issue by FDUZS** [retorquere/zotero-better-bibtex#2333]
debug log ID: VQ84RGZ4-refs-apse

The citation key format I have been using is `[auth:lower][year][Title:fold=chinese:lower:nopunctordash:select=1,3]` since my [last issue](https://github.com/retorquere/zotero-better-bibtex/issues/2089#issuecomment-1082534715), which best suits my needs.

I come to notice that the format has changed, and it seems to be automatically transformed to `auth.fold.lower + year + Title.fold(chinese).lower.nopunctordash.select(1,3)`. But the key generated is not as expected, like changing from `cui2021kaifanghuo` to `cui2021kaifanghuoqusjihuayanjinlichengdongyinjiduiwoguodeqishi`.

Couple of hours spent, I still could not figure out the desirable combination. And my sincere suggestion is to remove the duplicate, rarely-used functions/filters/fields, and stabilize the citation key formula to better focus on the stability, documentation, and new functionality.

**Comment by retorquere** [comment]
The legacy formula would always apply `splitIdeographs` when the global setting to force to ascii was on, in a way that wasn't easy to consistently transform to the new formula format. Try 

```javascript
auth.fold.lower + year + Title.splitIdeographs.fold(chinese).lower.nopunctordash.select(1,3)
```

**Comment by FDUZS** [comment]
> The legacy formula would always apply `splitIdeographs` when the global setting to force to ascii was on, in a way that wasn't easy to consistently transform to the new formula format. Try
> 
> ```js
> auth.fold.lower + year + Title.splitIdeographs.fold(chinese).lower.nopunctordash.select(1,3)
> ```

thanks! it works.
