### ISSUE TITLE
Error while exporting collection to Zotero-RDF

### ISSUE THREAD

**Issue by Prometheos2** [retorquere/zotero-better-bibtex#2336]
Hello,

I've got errors trying to export some of my collections to Zotero RDF files while BBT is enabled.

Debug log ID:
* `YJMUWV36-euc`
* `6VTRNZ3N-euc` (second collection)
* `G52R6DHP-euc` (with cache disabled)

It seems that it only concerns elements with the connector's timestamps (`2013-07-11T07:00:00.000Z`), as one of my collections without one is exported without error.

There are some errors given in the debug logs, which seem to imply it's from Zotero or one of the files (?): 
```
[JavaScript Error: "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]" {file: "chrome://zotero/content/xpcom/file.js" line: 47}]
[JavaScript Error: "Error: Unexpected path value 'undefined'" {file: "chrome://zotero/content/xpcom/file.js" line: 56}]
[JavaScript Error: "value must be defined in Zotero.RDF.addStatement" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2995}]
[JavaScript Error: "value must be defined in Zotero.RDF.addStatement" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2995}]
[JavaScript Error: "XML Parsing Error: no root element found
Location: http://s3.eu-central-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "http://s3.eu-central-1.amazonaws.com/ping" line: 1}]
[JavaScript Error: "XML Parsing Error: no root element found
Location: http://s3.ap-southeast-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "http://s3.ap-southeast-1.amazonaws.com/ping" line: 1}]
[JavaScript Error: "value must be defined in Zotero.RDF.addStatement" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2995}]
[JavaScript Error: "value must be defined in Zotero.RDF.addStatement" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2995}]
```

Thank you for your attention

**Comment by Prometheos2** [comment]
and I just noticed #2315, let me try that.

**Comment by retorquere** [comment]
And this is reliably tied to whether BBT is active? I don't interfere in any way with RDF exports, so I have no idea how to begin to address this.

> it only concerns elements with the connector's timestamps

I don't know what this means.

**Comment by Prometheos2** [comment]
Yes, it errors out when BBT is active, and works properly when it's not.
I was able to find the faulty elements for the first collection: `TJNGAX34-euc` (`5JTKWIF4-euc` includes three of them).

It seems that it's because of titles with colons, author names with dashes, and the "timestamps"

> I don't know what this means.

Oops, sorry about that.

It's the time of the last update/publication, appending to the date. Like this: `2013-07-11T07:00:00.000Z`

**Comment by retorquere** [comment]
Can you select one or more of the items that exhibit this behavior, right-click, and send a debug log from the BBT submenu? The ID will have `-refs-` in it.

**Comment by Prometheos2** [comment]
Here `F8D5896L-refs-euc`

**Comment by retorquere** [comment]
I cannot reproduce the problem using `F8D5896L-refs-euc`, can you try disabling all 3rd party plugins except BBT, restart Zotero, and try again?

**Comment by retorquere** [comment]
I have tried on Windows and on MacOS, both export these 3 items without issue to Zotero RDF.

**Comment by retorquere** [comment]
Can you drop [this Zotero RDF.js](https://gist.github.com/7dde9ef05f1d684f162b812166d60d8e) into your translators dir, restart Zotero, reproduce the problem, and send a new log?

**Comment by Prometheos2** [comment]
Sadly, I will be stuck on Ubuntu until tomorrow; I will try on Windows tomorrow, hopefully in the morning.

I was able to reproduce the problem, and I tried this translator, but it didn't work: `WD5FKTAR-refs-euc`

**Comment by retorquere** [comment]
It wasn't expected to work, just give me more debug info. Can you try the new version I just published at the previous URL? I don't see any extra logging.

**Comment by Prometheos2** [comment]
Weird; I probably didn't install it properly

This one should be good to go: `A56UAGGQ-refs-euc`

**Comment by retorquere** [comment]
please try build 3534

**Comment by Prometheos2** [comment]
Still erroring out: `ICPASXML-refs-euc`

```
[JavaScript Error: "value must be defined in Zotero.RDF.addStatement" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2995}]
[JavaScript Error: "value must be defined in Zotero.RDF.addStatement" {file: "chrome://zotero/content/xpcom/translate/src/translation/translate.js" line: 2995}]
```

**Comment by retorquere** [comment]
All of these items have at least one single-part name. Can you test what happens for one item if you switch that name to two-part?

**Comment by retorquere** [comment]
Can you test 3539?

**Comment by Prometheos2** [comment]
Both of those solutions work
Thank you very much!

Still, what a weird bug ^^' 

I wish you happy holidays

**Comment by retorquere** [comment]
The change to two-part names wasn't intended to be a solution, just a diagnosis. The new build is the solution. Thanks for reporting this, I'll roll it out in a new release.
