### ISSUE TITLE
accented character in 'journal' field is not brace protected by bibtex export

### ISSUE THREAD

**Issue by EricMarcon** [retorquere/zotero-better-bibtex#2337]
The journal name `Química Nova` is exported as `journal = {Qu\'imica Nova}` but should be `journal = {Qu{\'i}mica Nova}`.

Author names containing the same character are exported correctly: it seems the issue is not the character but the field that contains it.

**Zotero version**: 6.0.18

**BBT version**: 5.6.7

**Support log ID**: KEILBHX5-refs-euc

**Exporter used**: Better BibTeX

**Expected behavior**: `journal = {Qu{\'i}mica Nova}`

**Actual behavior**:  `journal = {Qu\'imica Nova}`

**debug log** ID: KEILBHX5-refs-euc

**Comment by retorquere** [comment]
Do you have an MWE where this journal title is rendered incorrectly? As far as I know those two forms you show are equivalent.

**Comment by EricMarcon** [comment]
It is not exactly an MWE: I use Better BibTex to export my bibliography to document an R package. In R, the [Rdpack](https://geobosh.github.io/Rdpack/) package allows developers to include references in the help pages of their own packages (example here of the [code](https://github.com/EricMarcon/divent/blob/master/R/ln_q.R) and the [output](https://ericmarcon.github.io/divent/reference/ln_q.html))

When I have `journal = {Qu{\'i}mica Nova}` in my bibtex file, the help pages are produced. When I have `journal = {Qu\'imica Nova}`, they are not because the text is incorrectly interpreted as a LaTeX macro that does not exist: an error occurs and the process stops.

So the short answer is that `{\'i}` is OK in the R ecosystem while `\'i` is not. Author names often have accented characters and Better BibTex exports them between braces. Journal names usually don't because most of them are in English but when they do, it would be better to export them the same way, both for consistency and for R developers.

The long answer is a but more complicated. In R, the [rbibutils](https://geobosh.github.io/rbibutils/) package is the standard to manipulate bibtex files. It is used internally by Rdpack. I found an old, [closed issue](https://github.com/GeoBosh/rbibutils/issues/7) that mentions the problem. To make it short, `{\'i}` should be read correctly but is not. The issue was closed but should be reopened. I'll do that, but this may be long to solve.

The valid argument for you to make the extra effort of exporting accented characters in the journal field between braces, as they are in author names, is consistency between fields.

Thanks!

**Comment by retorquere** [comment]
The difference between the two is because of #1189. Both are valid constructs, and they *ought* to be equivalent, but "character" counting fails for bibtex. This is specific to bibtex BTW, if you export as biblatex, you will not see the braced variant.

I suppose I could add an option to select the bibtex-creator map instead of the other maps. I'll see what I can whip up.

**Comment by retorquere** [comment]
Wouldn't you be better off with a toolchain that uses CSL-JSON? That bypasses all these problems definitively.

**Comment by retorquere** [comment]
Build 3517 adds a new option to https://retorque.re/zotero-better-bibtex/installation/preferences/export/#when-converting-to-plain-text-latex-commands which should do what you need. I still say this is a bug in rbibutils though.

**Comment by EricMarcon** [comment]
Sorry but I get this window (Zotero "Tools" menu, select "Better BibTeX") after installing build 3157:

![Capture](https://user-images.githubusercontent.com/29632125/207786872-1b3af27d-4627-446e-835b-8f30d77dd41d.PNG)

Support log ID:: VRVZDN2M-euc

**Comment by retorquere** [comment]
3157 didn't work because I didn't have the French translations yet, build 3527 has English strings for those in the meantime.

**Comment by EricMarcon** [comment]
It works perfectly, thank you.

My small contribution: French for "Add braces to accented characters to assist simple latex parsers" is "Placer les caractères accentués entre accolades pour aider certains analyseurs latex".

**Comment by retorquere** [comment]
If you can add that [here](https://crowdin.com/project/zotero-better-bibtex) it automatically shows up in BBT, and I keep the management centralized.

**Comment by retorquere** [comment]
looks like someone did, so I'll issue a new release
