### ISSUE TITLE
Lyx doesn't have "add ons" in TOOLS drop-down menu; how to add Zotero LYZ?

### ISSUE THREAD

**Issue by Zipgit** [retorquere/zotero-better-bibtex#2338]
A similar issue seems to have cropped up about a year ago, but here I am with the latest LYX version and the first thing I discover when trying to use LYZ is that there ISN'T a drop-down for 'add ons' in the TOOLS menu.
Also,
I've tried downloading the latest  LYZ version but I get error messages from my browser saying that "it appears that this file is corrupted".
![image](https://user-images.githubusercontent.com/36453740/207740706-30240c2c-f240-4a16-8511-a480160857d2.png). This happens even if I have LYX open (running) while attempting the download.
Also, this same problem appears in both my Linux version (Mint / Cinnamon) and in Win10-64bit
If someone can shed some light on this, it would be appreciated !

**Comment by retorquere** [comment]
Are you looking for [this](https://github.com/wshanks/lyz) plugin?

**Comment by Zipgit** [comment]
Good question! In fact, I tried to download and use Lyz, but that did not download, either (same error message). 
I have since discovered that this (is; or seems to be...) a Firefox issue; I was able to download BBT using MS-Edge without any hiccups.
I hacked away at this late into the night. I was able to get the BBT into Zotero (which does have an "add ons" menu item), and after more hacking, found that I could export the Zotero library to a file / folder that Lyx can "see".  That part of the Lyx "work flow" wasn't intuitively obvious, because I am new to both Lyx and to Tex / LaTeX. I was, in fact, expecting a direct-to-Zotero link from within Lyx ( as is the case with MS-Word), so that I could actively update Zotero entries without repeatedly  exporting the Library for Lyx to draw from.
At least, that is the work-flow that I understand right now. 
If I am wrong about the work-flow, please feel free to let me know!
Zipgit

**Comment by Zipgit** [comment]
To clarify, perhaps: I thought that both Lyz and BBT were **_add-ons for Lyx_**, from which it could access Zotero directly. This is the way that MS-Word operates with Zotero----it accesses Zotero's database directly.

**Comment by retorquere** [comment]
That is not the case. I don't know much about Lyz.

**Comment by qqobb** [comment]
> I thought that both Lyz and BBT were add-ons for Lyx

No, both Lyz and BBT are add-ons for *Zotero*.

@Zipgit: See here:
https://retorque.re/zotero-better-bibtex/support/faq/#add-on-could-not-be-installed-because-it-appears-to-be-corrupt

I'm not familiar with LyZ, but BBT and LyZ seem to be compatible: https://github.com/wshanks/lyz/issues/19#issuecomment-348864115

**Comment by retorquere** [comment]
@Zipgit does this answer your questions?
