### ISSUE TITLE
[Bug] Overleaf Git integration requires two pull before commit

### ISSUE THREAD

**Issue by sraedler** [retorquere/zotero-better-bibtex#2356]
### Debug log ID

NO-Log

### What happened?

Scenario: I am writing in Overleaf and need a new reference that is known not to be in the library. I add the reference and the auto-export plugin writes a new bibtex file. Git integration is configured.

Git integration works if the branch is already up to date.
It appears like Overleaf creates a commit right after a pull if something has changed online.
Therefore, another pull and push /merge is required.

Solution proposal: push once and after 2 seconds a second time. Then commit and then push.

BTW: I work alone, so there is no other person writing while bbt is being exported. 

Edit: I'm using Windows. As of now, I could not catch the error in a debug log. I will attach one if I could catch the error

**Comment by retorquere** [comment]
> Solution proposal: push once and after 2 seconds a second time. Then commit and then push.

Do you mean pull once and then after 2 seconds a second time?

**Comment by sraedler** [comment]
yep, I think that could solve the issue.

**Comment by sraedler** [comment]
Thanks, this solved my problem!
