### ISSUE TITLE
[Bug]: Mdnotes > Create full export note not working

### ISSUE THREAD

**Issue by chloeskafte** [retorquere/zotero-better-bibtex#2358]
### Debug log ID

C9TAWKMI-apse

### What happened?

Exporting annotations with metadata to Obsidian was working and then suddenly wasn't. Right click on the citation entry after creating an Annotation Note and select Mdnotes > Create full export note. Save into a folder in the Obsidian vault but once I have selected the folder it never appears in the Obsidian Vault.

**Comment by retorquere** [comment]
Are you sure you're reporting this on the right repo? This is not the MDNotes repo, and most of the errors in `C9TAWKMI-apse` are mdnotes errors. There are a few messages that are from BBT about attachments not having any output, but the items that this would relate to are not in `C9TAWKMI-apse`.

**Comment by chloeskafte** [comment]
Thank you I will post on there
