### ISSUE TITLE
[Bug/Feature]: Citation Key Capitalization Issue Revisited with a Debug Log.  

### ISSUE THREAD

**Issue by ihsankahveci** [retorquere/zotero-better-bibtex#2359]
### Debug log ID

QDQT9M2C-refs-euc

### What happened?

Thank you for this amazing package! I experience some problems when generating citation keys. It was reported before (#2233) but couldn't resolved due to missing debug log.

I want my citation keys to **strictly**  follow this format:  
`auth.lower + year + veryshorttitle(1, 0)`

Here, I demonstrate the issue with the following paper:
- Bradley, V. C., Kuriwaki, S., Isakov, M., Sejdinovic, D., Meng, X.-L., & Flaxman, S. (2021). Unrepresentative big surveys significantly overestimated US vaccine uptake. Nature, 600(7890), 695–700.
- BBT generates this citation key: `bradley2021Unrepresentative`
- However, I expect the first letter not to be capitalized: `bradley2021unrepresentative`

If this is the expected behavior by design, could you add a feature so that BBT de-capitalizes words if a user specified that way.

**Comment by retorquere** [comment]
Does `auth.lower + year + veryshorttitle(1, 0).lower` do what you want? I've updated the docs to clarify that `veryshorttitle` does not remove existing capitalization.

**Comment by ihsankahveci** [comment]
Thank you! This is exactly what I needed. Happy new year!
