### ISSUE TITLE
[Bug/Feature]: Issue of generating citekeys with parentheses 

### ISSUE THREAD

**Issue by xinyin8** [retorquere/zotero-better-bibtex#2366]
### Debug log ID

TLGF4B5A-refs-euc

### What happened?

I recently upgraded my Zotero v5 to v6.0.19, and better-bibtex to the latest version (v6.7.44). 

My personal preference is to generate a citekey in a format of `Author(2020)TitleShortName`, so I use the formula `auth + "(" + year + ")" + shorttitle(3,3)` in BBT settings. This worked nicely (Zotero v5 + old better-bibtex), but broke down after the upgrading: e.g. now BBT drops the parentheses and generates `Author2020TitleShortName` instead. 

Is this a bug or just BBT does not support parentheses in citekey anymore? If you have a better way to generate such formats, please let me know. Thanks!

**Comment by retorquere** [comment]
Parenthesis should never have been allowed in citationkeys. The charachters `"`, `#`, `%`, `'`, `(`, `)`, `,`, `=`, `\`, `{`, `}`, `~` and whitespace characters are all disallowed in bib(la)tex citation keys. You could perhaps use 

```
auth + "[" + year + "]" + shorttitle(3,3)
```

as an alternative.

**Comment by xinyin8** [comment]
I use `(` and `)` with latex and it seems fine. According to [Link 1](https://tex.stackexchange.com/questions/581901/what-is-the-safe-character-set-for-a-bibtex-label) and [Link 2](https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys), only the following characters `{ } , ~ # % \` should be avoided. 

Would it be possible to allow the parenthesis in citekeys? It would be nice to leave this option open and let the user decide if they want to use it not.

**Comment by retorquere** [comment]
The first comment on Link 1 says

> One thing I recently ran into us that biber does not support () in citation keys, whereas bibtex does. This is listed for example in the explanation of entrykey in the biblatex manual. 

And indeed the biblatex manual (p. 167-168) says

> biber additionally forbids round brackets (`()`), quotationmarks (`", '`), and the equals sign (`=`).

**Comment by xinyin8** [comment]
Indeed, like a lot of other peoples, I am using `BibTex` ;)  

My humble suggestion would be to re-open this option, i.e. the possibility of adding the parenthesis in citekeys. This should not hurt as the user has to intentionally add them in the formula to get it work. Alternatively, it could be a hidden option accessible via 'Config Editor' to allow special characters. a penny for your thoughts.

**Comment by xinyin8** [comment]
I put another thought on this. One potential issue might be that the bibtex information has parenthesis in e.g. author names, while the user is using `Biber`. Therefore, enabling this option is perhaps more complicated. 

If this is hard to implement I will live with it. Thanks anyhow for the prompt replies!

**Comment by retorquere** [comment]
If you go into the hidden prefs (advanced pane in Zotero prefs) you can edit the pref `citekeyUnsafeChars` to remove the parentheses.
