### ISSUE TITLE
Bug: Cannot "keep updated" when exporting library

### ISSUE THREAD

**Issue by linkmonitor** [retorquere/zotero-better-bibtex#2369]
### Debug log ID

7V7YK3CD-euc

### What happened?

When I try to export a library with the "Better BibTeX" format I do not have the option to "Keep updated".
<img width="1248" alt="Screen Shot 2023-01-06 at 1 36 58 PM" src="https://user-images.githubusercontent.com/75212/211104574-007516f9-090b-48cf-9435-c611ca2fb0cf.png">

**Comment by retorquere** [comment]
Uncheck "export files". You cannot export files for a "keep updated" export.

**Comment by linkmonitor** [comment]
That solves it. Thank you for educating me.
