### ISSUE TITLE
Ability to handle original publication date

### ISSUE THREAD

**Issue by igravious** [retorquere/zotero-better-bibtex#237]
Hello,

I would like to be able to handle original publication dates, like so: https://en.wikipedia.org/wiki/Parenthetical_referencing#How_to_cite

This uses a [1948] 2007 format. The citation key becomes @work_1948 no problem but the year of the publication of the edition is not passed through.

It's only a small thing!

**Comment by retorquere** [comment]
How would you note this in Zotero, and what would you like the BibTeX to look like? It's sounds to me like this should be handled by including an `origdate ` field in the resulting BibTeX, which could be achieved by including `biblatexdata{origdate: 1800 }`

**Comment by igravious** [comment]
What I've been doing so far, and I don't know if it right is to plonk, for example, [1948] 2007 directly into the date: field in Zotero as per that link in my previous comment. What happens at the moment as I said is that the citation key changes from @work_2007 to @work_1948 and the 2007 info does not get pulled across. According to this Stackexchange link: http://tex.stackexchange.com/questions/142999/the-proper-way-to-cite-the-earliest-publication-date-in-brackets-followed-by it does seem that ```origdate``` (and/or ```origyear```) is the way to go as a BibTeX field. Great.

Btw, would this field be passed over to the Atom.io citation package? Do I need to file a separate issue for that? Is there any way extra I can help in all this besides testing?

**Comment by retorquere** [comment]
Hmm, that's an interesting question. The atom package uses the embedded Zotero CSL processor; I've just pushed a change that picks out `originate` from the workaround mentioned in https://forums.zotero.org/discussion/3673/original-date-of-publication/, so using`{:original-date: 1948}` instead of `biblatexdata{origdate: 1948}` ought to work for both Bib(La)TeX and for anything that uses the CSL processor.

**Comment by retorquere** [comment]
I won't have time to test until I get home tonight, but you could try zotero-better-bibtex-0.14.14-2015-07-13@13:05:51.xpi from https://zotplus.github.io/better-bibtex/#debug using the `{:original-date: 1948}` notation to see if it works with atom (it should).

**Comment by retorquere** [comment]
I have already verified it works for Bib(La)TeX BTW, so it just remains to be tested for atom.

**Comment by igravious** [comment]
Where in the Zotero interface in Firefox should I see this new notation/field? I've installed the new xpi? I'm not seeing it :/

**Comment by igravious** [comment]
Wait! Ignore question. I stuck ```{:original-date: 1948}``` into the ```Extra``` field and it went right through when I hit ```ctrl+alt+a``` in atom. Happy days. I've included a screenshot. It uses the ```(author, old/new)``` syntax whereas I'd use ```(author, [old] new)``` but I can tweak that myself in the plugin's code :) 

![citation_zotero_atom](https://cloud.githubusercontent.com/assets/109220/8653429/42dee396-297c-11e5-9ef6-bc684b16ad68.png)

**Comment by retorquere** [comment]
Super, happy to hear it works well. The release will go out tonight. 

There should be no need to tweak the code; the citation style should take care of this. Perhaps simply selecting a different style (https://atom.io/packages/zotero-citations)? If you have however selected the correct style but the origdate is not in the right place, I'd submit an issue at https://github.com/citation-style-language/styles

**Comment by retorquere** [comment]
What's your subject BTW? Those names are familiar :)

**Comment by igravious** [comment]
The intersection of philosophy and computing. (aka humanities computing, aka digital humanities) :8ball:

**Comment by retorquere** [comment]
I'm currently in the final throes of a master of Philosophy of Science, Technology & Society, of which honestly only the Phil of Sci part holds my interest, and then even very old-school Popper-style Phil of Sci, with a dash of good ole analytic epistemology. That combo quite often brings Floridi on my path. I am graduating in the Technology & Values track however, which means that at some point I'm going to have to jam technology in there, as I usually do as an afterthought :)

Currently working on justification of false beliefs for well-being as part of my supervisor's project... my own project on the philosophy of expertise grew a bit out of hand, in the sense of well-maybe-if-you-hire-four-maximax-phds out of hand. And I'd still have to jam technology in there.
