### ISSUE TITLE
[Bug/Feature]: Child items that use the crossref field do not have their parent fields imported

### ISSUE THREAD

**Issue by andrewheiss** [retorquere/zotero-better-bibtex#2373]
### Debug log ID

MEN4TZDD-refs-euc

### What happened?

[BibDesk natively supports the `crossref` field](https://bibdesk.sourceforge.io/manual/BibDeskHelp_2.html#SEC18), which biber and biblatex use when working with LaTeX. This field lets you set up child/parent relationships with items, where children inherit fields from their parents. 

For instance, consider these two items—an edited book with lots of chapters from different authors and a chapter from that book:

```bibtex
@inbook{El-HusseiniToeplerSalamon:2004,
    author = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
    chapter = {12},
    crossref = {SalamonSokolowski:2004},
    pages = {227--32},
    title = {Lebanon}}

@book{SalamonSokolowski:2004,
    address = {Bloomfield, CT},
    editor = {Lester M. Salamon and S. Wojciech Sokolowski},
    publisher = {Kumarian Press},
    title = {Global Civil Society: Dimensions of the Nonprofit Sector},
    booktitle = {Global Civil Society: Dimensions of the Nonprofit Sector},
    volume = {2},
    year = {2004}}
```

When importing the `.bib` file, though, the chapter doesn't get any of the parent information—book title, date, publisher, etc. are all blank:

![image](https://user-images.githubusercontent.com/73663/211345094-3580db0d-4447-4aea-bfae-ce0e582e7585.png)

**Comment by retorquere** [comment]
This should also be solved by the build on #2374.

**Comment by andrewheiss** [comment]
Build 3620 almost fixes this. The parent item's book title is added to the child item, but the volume, publisher, date, and place are still blank:

```bibtex
@inbook{El-HusseiniToeplerSalamon:2004,
	author = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
	chapter = {12},
	crossref = {SalamonSokolowski:1112004},
	date-added = {2023-01-08 09:21:39 -0500},
	date-modified = {2023-01-08 18:45:02 -0500},
	pages = {227--32},
	title = {Lebanon111}}

@book{SalamonSokolowski:1112004,
	address = {Bloomfield, CT},
	date-added = {2023-01-08 09:22:08 -0500},
	date-modified = {2023-01-08 12:03:40 -0500},
	editor = {Lester M. Salamon and S. Wojciech Sokolowski},
	publisher = {Kumarian Press},
	title = {Global Civil Society: Dimensions of the Nonprofit Sector111},
	volume = {2},
	year = {2004}}
```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/73663/212103549-c504f579-346a-4082-ba38-1caefb7487a6.png">

**Comment by andrewheiss** [comment]
Additionally, if the child item is of type `incollection` (which BibDesk tends to use by default for book chapters) instead of `inbook`, the book title field doesn't get transferred.

```bibtex
@incollection{El-HusseiniToeplerSalamon:2004,
	author = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
	chapter = {12},
	crossref = {SalamonSokolowski:1112004},
	date-added = {2023-01-08 09:21:39 -0500},
	date-modified = {2023-01-08 18:45:02 -0500},
	pages = {227--32},
	title = {Lebanon111}}

@book{SalamonSokolowski:1112004,
	address = {Bloomfield, CT},
	date-added = {2023-01-08 09:22:08 -0500},
	date-modified = {2023-01-08 12:03:40 -0500},
	editor = {Lester M. Salamon and S. Wojciech Sokolowski},
	publisher = {Kumarian Press},
	title = {Global Civil Society: Dimensions of the Nonprofit Sector111},
	volume = {2},
	year = {2004}}
```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/73663/212104027-0d090bd2-2044-4755-b808-870ecf549f0f.png">

**Comment by retorquere** [comment]
Does bibdesk have documentation on their crossref rules? I'm looking at the [biber inheretance rules](https://github.com/plk/biber/blob/dev/data/biber-tool.conf) and I don't see `incollection` inheriting from `book`.

**Comment by andrewheiss** [comment]
This isn't from their official documentation, but [this is the general approach they've taken and recommend](https://sourceforge.net/p/bibdesk/mailman/message/7781170/):

> incollection is for your typical edited collection of papers with 
different names by different authors.  Booktitle is the title of the 
whole book, Title is the title of the chapter (or paper).
> 
> inbook is for chapters or page ranges of a more traditional book, that 
has either an author or an editor, not both (and so each section of the 
book has the same authorship as the book in total).

So in general `incollection` is for things like edited volumes while `inbook` is for chapters within a single-authored book.

However, [other places like here](https://www.bibtex.com/t/template-inbook/) recommend `inbook` for things like edited volumes. 

Both types seem to work in both biblatex/biber and through citeproc/pandoc

(Using this markdown file through pandoc)

```markdown
Using `incollection`: @El-HusseiniToeplerSalamon:2004-incollection

Using `inbook`: @El-HusseiniToeplerSalamon:2004-inbook
```

```bibtex
@inbook{El-HusseiniToeplerSalamon:2004-inbook,
	author = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
	booktitle = {Global Civil Society: Dimensions of the Nonprofit Sector},
	chapter = {12},
	crossref = {SalamonSokolowski:2004},
	pages = {227--32},
	title = {Lebanon}}

@incollection{El-HusseiniToeplerSalamon:2004-incollection,
	author = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
	booktitle = {Global Civil Society: Dimensions of the Nonprofit Sector},
	chapter = {12},
	crossref = {SalamonSokolowski:2004},
	pages = {227--32},
	title = {Lebanon}}

@book{SalamonSokolowski:2004,
	address = {Bloomfield, CT},
	editor = {Lester M. Salamon and S. Wojciech Sokolowski},
	publisher = {Kumarian Press},
	title = {Global Civil Society: Dimensions of the Nonprofit Sector111},
	volume = {2},
	year = {2004}}
```

Rendered as PDF using a biblatex backend:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/73663/212146058-05af8bc8-373a-4e51-a6ae-94555d9bb45b.png">

Rendered as HTML using the Chicago author-date CSL:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/73663/212146908-024e960a-def1-432d-8ca4-bc64e43cf246.png">

**Comment by retorquere** [comment]
> incollection is for your typical edited collection of papers with
> different names by different authors. Booktitle is the title of the
> whole book, Title is the title of the chapter (or paper).

That doesn't really specify what they're doing though. Either there are specific rules covering `incollection` -> `book` that I can't readily find, or they use something like "for the purposes of inheritance, `incollection` -> `book` behaves like `incollection` -> `collection`", and I don't know which is in play. And since this works in biber, biber is doing something similar.

I have an MWE that reproduces this, so I'll go talk to plk. @njbart, any insights on this?

**Comment by retorquere** [comment]
Got an answer from plk, and as frustratingly usual, "it's complicated". It looks like the mapping for crossref can vary at compile tim, depending on the document being compiled. I've posted to the bibdesk mailing list to ask where they have their mapping -- such a pain they're still on sourceforge.

**Comment by retorquere** [comment]
Can you try build 3636?

**Comment by andrewheiss** [comment]
Using this .bib file (with a bunch of `111`s and `222`s added to prevent duplication)…

```bibtex
@inbook{El-HusseiniToeplerSalamon:2004-inbook,
  author    = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
  chapter   = {12},
  crossref  = {SalamonSokolowski111:2004},
  pages     = {227--32},
  title     = {Lebanon111}
}

@incollection{El-HusseiniToeplerSalamon:2004-incollection,
  author    = {Hashem El-Husseini and Stefan Toepler and Lester M. Salamon},
  booktitle = {Global Civil Society111: Dimensions of the Nonprofit Sector},
  chapter   = {12},
  crossref  = {SalamonSokolowski111:2004},
  pages     = {227--32},
  title     = {Lebanon111}
}

@book{SalamonSokolowski111:2004,
  address   = {Bloomfield, CT},
  editor    = {Lester M. Salamon and S. Wojciech Sokolowski},
  publisher = {Kumarian Press},
  title     = {Global Civil Society111: Dimensions of the Nonprofit Sector111},
  volume    = {2},
  year      = {2004}
}
```

…it works! Fields like publisher, volume, date, etc. are all correctly imported into the child item, both with `inbook` and with `incollection`. It even works when the child item doesn't have an explicit `booktitle` field (like `El-HusseiniToeplerSalamon:2004-inbook` in the example):

<img width="347" alt="image" src="https://user-images.githubusercontent.com/73663/212344516-403746a1-0019-45b9-b1a7-af66b71c9d8b.png">

**Comment by retorquere** [comment]
Thanks! I have one more issue open, I expect to put out a new release including #2373 and #2374 somewhere today.

**Comment by retorquere** [comment]
(don't forget to update the blog)

**Comment by andrewheiss** [comment]
Perfect, will update as soon as new release is released! Thanks for your help with this and for such a wonderful add-on!

**Comment by retorquere** [comment]
New version is out now.
