### ISSUE TITLE
unwanted inclusion of Zotero's internal journal abbreviations in CSL JSON

### ISSUE THREAD

**Issue by tillgrallert** [retorquere/zotero-better-bibtex#2375]
### Debug log ID

NQHMA8ST-refs-euc

### What happened?

I have found that the latest update of BBT includes journal abbreviations from Zotero's internal abbreviations list (see [this issue](https://forums.zotero.org/discussion/102230/journal-abbreviations-in-csl-json-export-of-unclear-origin#latest) on Zotero Forums) as "container-title-short". These are not abbreviations provided explicitly for individual references by the user and they break my workflow and pipelines: Publishers / journals in my field often require custom abbreviations that tend to differ from one journal to another. In order to cater to such needs, Pandoc and citeproc allow for the use of custom lists of abbreviations with any CSL style you might have. BUT this only works if the "container-title-short" is not explicitly provided by the bibliographic data for individual references. Therefore, I would deeply appreciate the option to turn this new behaviour off.

**Comment by retorquere** [comment]
Something must have gone wrong in the log submission -- can you send a new one?

**Comment by tillgrallert** [comment]
I just submitted a new one: `5VTJMZDY-refs-euc`. However, the issue does not pertain to a specific reference.

**Comment by retorquere** [comment]
But this item does exhibit the problem, right?

**Comment by tillgrallert** [comment]
This is odd. I have created a new log submission (3YPZKIAT-refs-euc) because I did not take note of the reference the last one belonged to and exported this reference to Better CSL JSON, which returned 

```json
[
  {"id":"Zhao2022SystematicReviewWikidata","abstract":"Wikidata has been widely used in Digital Humanities (DH) projects. However, a focused discussion regarding the current status, potential, and challenges of its application in the ﬁeld is still lacking. A systematic review was conducted to identify and evaluate how DH projects perceive and utilize Wikidata, as well as its potential and challenges as demonstrated through use. This research concludes that: (1) Wikidata is understood in the DH projects as a content provider, a platform, and a technology stack; (2) it is commonly implemented for annotation and enrichment, metadata curation, knowledge modelling, and Named Entity Recognition (NER); (3) Most projects tend to consume data from Wikidata, whereas there is more potential to utilize it as a platform and a technology stack to publish data on Wikidata or to create an ecosystem of data exchange; and (4) Projects face two types of challenges: technical issues in the implementations and concerns with Wikidata’s data quality. In the discussion, this article contributes to addressing three issues related to coping with the challenges in the speciﬁc context of the DH ﬁeld based on the research ﬁndings: the relevance and authority of other available domain sources; domain communities and their practices; and workﬂow design that coordinates technical and labour resources from projects and Wikidata.","accessed":{"date-parts":[[2022,12,31]]},"author":[{"family":"Zhao","given":"Fudie"}],"citation-key":"Zhao2022SystematicReviewWikidata","container-title":"Digital Scholarship in the Humanities","container-title-short":"Digit. Scholarsh. Humanit.","DOI":"10.1093/llc/fqac083","ISSN":"2055-7671, 2055-768X","issued":{"date-parts":[[2022,12,28]]},"language":"en","page":"fqac083","source":"DOI.org (Crossref)","title":"A systematic review of Wikidata in Digital Humanities projects","type":"article-journal","URL":"https://academic.oup.com/dsh/advance-article/doi/10.1093/llc/fqac083/6964525"}
]
```

This contains the key-value pair `"container-title-short":"Digit. Scholarsh. Humanit."`

**Comment by retorquere** [comment]
That should ga away if you turn off this:

![image](https://user-images.githubusercontent.com/132108/211504930-6f232a7c-2673-4e38-b6da-6a5b8f55769b.png)

**Comment by tillgrallert** [comment]
Thank you very much for pointing me to this setting. I had never seen it before and did not actively toggle it.
