### ISSUE TITLE
[Feature]: Combine the last name and first name in Chinese.

### ISSUE THREAD

**Issue by earthmoon** [retorquere/zotero-better-bibtex#2381]
### Debug log ID

ERHRLB2T-refs-apse

### What happened?

May you add a new feature? Thanks.
When the first name and the last name in Chinese are separated, even users have set `author.lower + year` in Better Bibtex, the citation keys will only contain the last name and year, not contain the first name. However, the Chinese only have nearly 100 last names, so it is difficult to tell the authors by their last names. How about adding a feature that when there is Chinese, Better Bibtex will always contain last name and first name.

**Comment by retorquere** [comment]
See #2380

**Comment by earthmoon** [comment]
> See #2380

Thanks a lot.
