### ISSUE TITLE
[Bug]: `capitalize` filter is ignored for kuroshiro-processed author names

### ISSUE THREAD

**Issue by okomestudio** [retorquere/zotero-better-bibtex#2383]
### Debug log ID

42D5BKI9-refs-euc

### What happened?

I've been using the following citekey formula `authEtal2.capitalize + year + shorttitle(3, 3)`. 

This has been working as intended for me. For example, given the input:

```
Title: 表現のための実践ロイヤル英文法
Author: 綿貫, 陽
Author: Petersen, Mark
Date: 2006
```

I get "Watanuki.Petersen2006HyogenNoTame".

However, with the current version, I've noticed that the romaji-translated author names no longer gets capitalized. With the same input, this means that I get "watanuki.Petersen2006HyogenNoTame". (Note that the first "w" is lowercase. Also note that the English name does get capitalized, as expected.)

The behavior appears to be a bug introduced relatively recently.

**Comment by retorquere** [comment]
Yes, sorry about that -- when I started with transliteration I was very naive about how people would want to treat CJK names, so I had hard-coded in transliteration for names. `authEtal2.transliterate.capitalize + year + shorttitle(3, 3)` now does what you want.

Apologies for the change.

**Comment by okomestudio** [comment]
Thanks for the quick response. I appreciate it.

So this means that `authEtal2.transliterate.capitalize + year + shorttitle(3, 3)` is actually the proper and intended way to write the formula? 

If so, it would be nice to see some clarification in the documentation on this point.

In any case, thanks again for very quickly addressing the issue.

**Comment by retorquere** [comment]
Good point, the docs are building, should be out in 5 minutes or so.
