### ISSUE TITLE
Bug: bbt_update_bib wipes the bib file

### ISSUE THREAD

**Issue by sebdunnett** [retorquere/zotero-better-bibtex#2385]
### Debug log ID

225ZJ2H2-euc

### What happened?

Using a journal sample bib and then attempting to update with one of my own references from Zotero. Updating the bib from the rmd file wipes the bib so it's an empty file.

The journal bib has 4/5 references in it, none of which are in my Zotero library, but are referenced in the rmd file. I expected update_bib to just add my own reference to the bib, but appreciate refs not in my library could be a cause...

**Comment by retorquere** [comment]
I don't know what bbt_update_bib is. Maybe an external tool that builds on BBT?

**Comment by retorquere** [comment]
Looks like this project: https://github.com/paleolimbot/rbbt . You'll have to file the issue there.

**Comment by sebdunnett** [comment]
Yes, sorry - misposted it here.
