### ISSUE TITLE
[Bug]: CAYW failed

### ISSUE THREAD

**Issue by cyrande** [retorquere/zotero-better-bibtex#2388]
### Debug log ID

D803461013

### What happened?

I am sure I'm having a very simple problem since I'm actually quite new to everything. But the problem is first I've started have issues with CAYW quick copy directory. I believe i somehow fixed it. But now I only see that "CAYW failed" from BBT. I uninstalled and reinstalled everything and tried to clean all cache. But really now I do not have any idea what's going on. Any help will be appreciated! 

ps. eventually. I use Zotero + BBT for Obsidian through [Zotero Integration](https://github.com/mgmeyers/obsidian-zotero-integration)

**Comment by cyrande** [comment]
BBT debug ID:  2NE2ZDSS-euc

**Comment by retorquere** [comment]
I don't see any CAYW activity in `2NE2ZDSS-euc`. Can you enable debugging in the `Help` menu, reproduce the problem, and send a new debug log?

**Comment by KimYeongHyeon** [comment]
i also got this problem when importing from obsidian using Zotero Integration addon. my debug log is like the following

(5)(+0016483): GET /better-bibtex/cayw?probe=true HTTP/1.1
Host: 127.0.0.1:23119
Connection: keep-alive
Accept: application/json
Content-Type: application/json
User-Agent: obsidian/zotero
Sec-Fetch-Site: none
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US


(5)(+0000015): HTTP/1.0 200 OK
X-Zotero-Version: 6.0.20
X-Zotero-Connector-API-Version: 2
Content-Type: text/plain

ready
(5)(+0000010): GET /better-bibtex/cayw?format=formatted-citation&style=apa HTTP/1.1
Host: 127.0.0.1:23119
Connection: keep-alive
Accept: application/json
Content-Type: application/json
User-Agent: obsidian/zotero
Sec-Fetch-Site: none
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US


(3)(+0000009): Integration: BetterBibTeX-addEditCitation:'3' invoked
(3)(+0000004): Synchronous integration plugin functions are deprecated -- update to asynchronous methods
(3)(+0000347): Editing citation:
(3)(+0000000): {"properties":{},"citationItems":[],"schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json"}
(3)(+0000000): Integration: Displaying dialog chrome://zotero/content/integration/quickFormat.xul
(3)(+0000001): Integration: Retrieved 1 fields in 0.003; 333.3333333333333 fields/second
(3)(+0000010): Integration: Updated session data for 1 fields in 0.008; 125 fields/second
(3)(+0000281): Quick Format received citation:
(3)(+0000001): {"properties":{},"citationItems":[],"schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json"}
(3)(+0000042): {better-bibtex} +42371 window-loaded chrome://zotero/content/integration/quickFormat.xul
(3)(+0001292): QuickFormat: QuickSearch: ml
(4)(+0000020): SELECT COALESCE(IAn.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IAn USING (itemID) WHERE itemID IN (SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT  IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND (itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL)) AND itemID NOT IN (SELECT itemID FROM items WHERE itemTypeID=1 UNION SELECT itemID FROM items WHERE (itemTypeID IN (SELECT itemTypeID FROM itemTypesCombined WHERE typeName=?)))) AND ((itemID IN (SELECT itemID FROM itemData WHERE (fieldID IN (?,?,?,?) AND valueID IN (SELECT valueID FROM itemDataValues WHERE value LIKE ?))) OR itemID I ...

**Comment by KimYeongHyeon** [comment]
here is full log
[2G6RY85Q-apse.zip](https://github.com/retorquere/zotero-better-bibtex/files/10500223/2G6RY85Q-apse.zip)

**Comment by retorquere** [comment]
Can you try build 3695?

**Comment by KimYeongHyeon** [comment]
In my case, 3695 works! thank you.
