### ISSUE TITLE
[Bug/Feature]: 

### ISSUE THREAD

**Issue by Victor-Le-Coz** [retorquere/zotero-better-bibtex#2389]
### Debug log ID

T9WXVHRP-euc

### What happened?

A bug happened!

Hi, 

The auto-export git push function does not work with my setup, and I could not figure out why.

The debug log mentions: "autoexport git push failed"

I have the following lines in my git config file:
[zotero "betterbibtex"]
	push = true

One remark: my zotero runs on windows but I can also access to the repositoy where my git.overleaf project is cloned via linux, so I used directly the cmd lines in linux to initialize the git, clone the rep, and enable BBT push = True.

Best,

Victor

**Comment by Victor-Le-Coz** [comment]
Issue solved, it was a security layer in windows, that I could not see when pushing from linux, now it is solved, and BBT successfully performs the push

**Comment by retorquere** [comment]
Super, thanks for the explanation.
