### ISSUE TITLE
[Feature]: Specify a library with `json-rpc`

### ISSUE THREAD

**Issue by scbarton** [retorquere/zotero-better-bibtex#2392]
### Debug log ID

X3S4D96H-refs-euc

### What happened?

I have two libraries in my Zotero vault, My Library and one Group Library.  There is quite a bit of duplication between the two libraries, and auto-generated citekeys lead to duplicate citekeys for records that appear in both libraries.  

Because of this duplication, when I generate a bibliography with `json-rpc` using the `item.bibliography` method and a list of `citekeys`, two bibliography entries are generated for `citekeys` that match both libraries. 

I suggest that an argument be added to `json-rpc` to specify a library from which to return references.  This idea was first suggested in [this discussion](https://github.com/retorquere/zotero-better-bibtex/discussions/2384).

Thanks!

**Comment by scbarton** [comment]
With [test build 6.7.54.3741](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.54.3741.xpi), I could successfully select "My Library" and return non-duplicated references.

However, I was not successful in selecting a Group Library (in my case, "scb-group"). When this library was specified, the returned bibliography is empty, even though the specified citekeys exist in that library.

Even so, the ability to select "My Library" is enough for my needs. Thanks!

**Comment by scbarton** [comment]
I reproduced the problem with debug log 55SA5ALQ-refs-euc. Thanks for taking a look!

**Comment by retorquere** [comment]
Can you test 3769?

**Comment by scbarton** [comment]
Hi, the problem persists, Bug Log ID: 4D35TZ4J-refs-euc

Thanks for your help on this!

**Comment by retorquere** [comment]
Can you send a new log, checking "include cache" on the log submission dialog?

**Comment by scbarton** [comment]
Done, Bug Log ID: 3Y7VHXBJ-refs-euc

Thanks!

**Comment by retorquere** [comment]
Can you do the same from 3813?

**Comment by scbarton** [comment]
Yes, here's a debug log: N3IZ4GB4-refs-euc

I'll also note that, with this test build, when I do not specify a library, only one reference is retrieved per citekey. the reference is retrieved from "My Library". Previously, references from both libraries were returned if the same citekey appears in both.

Thanks again for your work on this...

**Comment by retorquere** [comment]
I think I've got it now.

**Comment by scbarton** [comment]
That worked! I made a debug log anyway in case you are interested: 5L6TD8BY-refs-euc

It looks like default library is "My Library" of no library is specified. I kind of like having the references drawn from both libraries in that case, but I'm not picky and what you have written will work great for me. Thank you!

**Comment by retorquere** [comment]
Build incoming that allows specifying library as `*` for all.
