### ISSUE TITLE
[Feature]: preprint: print more information 

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#2395]
### Debug log ID

3X8WKDMA-refs-apse

### What happened?

Currently, Zotero's *Preprint* field becomes `@misc` but then I miss the following two pieces of information in the reference list:
- The fact that it's a preprint.
- The name of the preprint archive (preprint server).

I don't know what's the best entry type, but if we use `@article` with `journal = {repository name}` and `note={preprint}` then most bibliography processors will produce good references with perhaps warnings like "missing volume number" and "missing pages".  This handling would be almost the same as a journal article "in press".

**Comment by retorquere** [comment]
In the case of `3X8WKDMA-refs-apse`, what would be the preprint archive? `Earth and Space Science Open Archive`?

**Comment by ryofurue** [comment]
Thank you for your response.

> what would be the preprint archive? `Earth and Space Science Open Archive`?

Yes.  The Zotero browser plugin put it in the "Repository" field of the "Preprint" entry.

I can see that preprint can be problematic because there is no standard practice for biblatex.  If you look at discussion on the Net, you see that some recommend `@article`, some `@online`, some `@misc`.  At least, it seems the names of the relevant fields are sort of standardized by biblatex for arXiv, though:

[](https://tex.stackexchange.com/questions/3833/how-to-cite-an-article-from-arxiv-using-bibtex)

But, for other preprint services . . . I don't know.

**Comment by retorquere** [comment]
@njbart would you reckon a preprint would be better mapped to `unpublished`, or to `online`?

**Comment by njbart** [comment]
If this is about biblatex, the examples from https://github.com/plk/biblatex/blob/dev/bibtex/bib/biblatex/biblatex-examples.bib seem to indicate that `@online` is appropriate, unless the article in question has also been officially published, in which case `@article` would make more sense.

```
@article{baez/article,
  author       = {Baez, John C. and Lauda, Aaron D.},
  title        = {Higher-Dimensional Algebra {V}: 2-Groups},
  journaltitle = {Theory and Applications of Categories},
  date         = 2004,
  volume       = 12,
  pages        = {423-491},
  version      = 3,
  eprint       = {math/0307200v3},
  eprinttype   = {arxiv},
  langid       = {english},
  langidopts   = {variant=american},
  annotation   = {An \texttt{article} with \texttt{eprint} and
                  \texttt{eprinttype} fields. Note that the arXiv reference is
                  transformed into a clickable link if \texttt{hyperref} support
                  has been enabled.  Compare \texttt{baez\slash online}, which
                  is the same item given as an \texttt{online} entry},
}

@online{baez/online,
  author       = {Baez, John C. and Lauda, Aaron D.},
  title        = {Higher-Dimensional Algebra {V}: 2-Groups},
  date         = {2004-10-27},
  version      = 3,
  langid       = {english},
  langidopts   = {variant=american},
  eprinttype   = {arxiv},
  eprint       = {math/0307200v3},
  annotation   = {An \texttt{online} reference from arXiv. Note the
                  \texttt{eprint} and \texttt{eprinttype} fields. Compare
                  \texttt{baez\slash article} which is the same item given as an
                  \texttt{article} entry with eprint information},
}

@online{itzhaki,
  author       = {Itzhaki, Nissan},
  title        = {Some remarks on {'t Hooft's} {S}-matrix for black holes},
  date         = {1996-03-11},
  version      = 1,
  langid       = {english},
  langidopts   = {variant=american},
  eprinttype   = {arxiv},
  eprint       = {hep-th/9603067},
  annotation   = {An \texttt{online} reference from arXiv. Note the
                  \texttt{eprint} and \texttt{eprinttype} fields. Also note that
                  the arXiv reference is transformed into a clickable link if
                  \texttt{hyperref} support has been enabled},
  abstract     = {We discuss the limitations of 't Hooft's proposal for the
                  black hole S-matrix. We find that the validity of the S-matrix
                  implies violation of the semi-classical approximation at
                  scales large compared to the Planck scale. We also show that
                  the effect of the centrifugal barrier on the S-matrix is
                  crucial even for large transverse distances.},
}

@online{wassenberg,
  author       = {Wassenberg, Jan and Sanders, Peter},
  title        = {Faster Radix Sort via Virtual Memory and Write-Combining},
  date         = {2010-08-17},
  version      = 1,
  langid       = {english},
  langidopts   = {variant=american},
  eprinttype   = {arxiv},
  eprintclass  = {cs.DS},
  eprint       = {1008.2849v1},
  annotation   = {A recent \texttt{online} reference from arXiv using the new
                  (April 2007 onward) identifier format. Note the
                  \texttt{eprint}, \texttt{eprinttype}, and \texttt{eprintclass}
                  fields. Also note that the arXiv reference is transformed into
                  a clickable link if \texttt{hyperref} support has been
                  enabled},
  abstract     = {Sorting algorithms are the deciding factor for the performance
                  of common operations such as removal of duplicates or database
                  sort-merge joins. This work focuses on 32-bit integer keys,
                  optionally paired with a 32-bit value. We present a fast radix
                  sorting algorithm that builds upon a microarchitecture-aware
                  variant of counting sort},
}
```

**Comment by retorquere** [comment]
@ryofurue right now BBT will output the following for `3X8WKDMA-refs-apse`:

```
@online{CalilPHR:2022,
  title = {High-resolution, basin-scale simulations reveal the impact of intermediate zonal jets on the {{Atlantic}} oxygen minimum zones},
  author = {Calil, Paulo H. R.},
  date = {2022-10-18},
  eprinttype = {Earth and Space Science Open Archive},
  eprintclass = {Oceanography},
  doi = {10.1002/essoar.10511180.2},
  url = {https://essopenarchive.org/doi/full/10.1002/essoar.10511180.2},
  urldate = {2022-10-26},
  langid = {english}
}
% == BibLateX quality report for CalilPHR:2022:
% ? unused Archive location ("world")
% ? unused ISSN ("1051-1180")
% ? unused Library catalog ("www.essoar.org")
```

note that `eprint` is missing as the Zotero entry did not have an identifier filled out. It's not reported as missing in the quality report since `@online` only requires at least one of `doi`/`eprint`/`url` to be present. It does seem weird to me to have the `eprinttype` field but not the `eprint` field.

**Comment by retorquere** [comment]
Maybe if it has an ISSN I should use `@article` rather than `@online`?

**Comment by retorquere** [comment]
Maybe if it has an ISSN I should use `@article` rather than `@online`?

**Comment by ryofurue** [comment]
> Maybe if it has an ISSN and a journaltitle I should use `@article` rather than `@online`?

I don't think so . . . For the particular example I've sent you, the preprint will remain as preprint for ever.  It will not be treated as a journal article.  The server is not linked to a particular journal.  When a preprint is published in a journal, the preprint webpage just shows a link to the published version.

I guess this preprint server has an ISSN only because its editorial board controls the quality of the preprints and administers proper curation.

**Comment by ryofurue** [comment]
> right now BBT will output the following

I guess you mean you will produce another BBT test version?  I'm currently using
[the latest test version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.54.3749.xpi)  and it puts the entry in `@misc` with `type = {Preprint}`, etc.

I'll test what happens with `@online` with biblatex-chicago, which I use.

**Comment by retorquere** [comment]
> I guess you mean you will produce another BBT test version? I'm currently using
> [the latest test version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.54.3749.xpi) and it puts the entry in `@misc` with `type = {Preprint}`, etc.

3749 outputs what I posted earlier for biblatex, and the following for bibtex:

```
@misc{CalilPHR:2022,
  title = {High-resolution, basin-scale simulations reveal the impact of intermediate zonal jets on the {{Atlantic}} oxygen minimum zones},
  author = {Calil, Paulo H. R.},
  year = {2022},
  month = oct,
  publisher = {{Earth and Space Science Open Archive}},
  doi = {10.1002/essoar.10511180.2},
  chapter = {Oceanography},
  copyright = {Creative Commons Attribution 4.0 International License},
  langid = {english}
}
```

I don't know how you got `type = {Preprint},`, neither the BBT nor the stock bib(la)tex exports seem to produce that. Maybe the `type = {Preprint},` is reasonable for bibtex? I don't know.

**Comment by ryofurue** [comment]
> 3749 outputs what I posted earlier for biblatex

I see!  I totally forgot that I'm using "bibtex" output, not "biblatex" output.  Sorry for the confusion.

> I don't know how you got `type = {Preprint}`,

Again, sorry that was my mistake. I have two entries on Zotero for the same preprint: One is "Web Page" type and the other, "Preprint" type.  You get `type = {Preprint}` for the Web Page version.

Okay, I'll test the "biblatex" output and see how biblatex-chicago handles it.

**Comment by ryofurue** [comment]
I got
> Paulo H. R. Calil. High-Resolution, Basin-Scale Simulations Reveal the Impact of Intermediate Zonal Jets on the Atlantic Oxygen Minimum Zones. Oct. 18, 2022. doi: 10.1002/essoar.10511180.2. url: https:// essopenarchive.org/doi/full/10.1002/essoar.10511180.2 (visited on 10/26/2022).

from biblatex (without any package options) on the basis of the "bib**latex**" output from BBT.  `biblatex-chicago` is essentially the same.

Still there is no indication that this is a preprint or name of the repository.  Perhaps I should ask the developers of biblatex and biblatex-chicago?

**Comment by retorquere** [comment]
That's what I'd recommend. The biblatex manual doesn't say anything about preprints.

**Comment by njbart** [comment]
Well, short of getting biblatex or biblatex-chicago modified I'd imagine adding something like `pubstate = {preprint}` would do the trick. One could also think of having this added by BBT, or by biblatex on the fly in case `eprinttype` contains the name of a known preprint archive.

**Comment by ryofurue** [comment]
Thank you both for your help.

With test build 6.7.54.3757, I get
>  Paulo H. R. Calil. High-resolution, basin-scale simulations reveal the impact of intermediate zonal jets on the Atlantic oxygen minimum zones. Oct. 18, 2022. doi: 10.1002/essoar.10511180.2. url: https:// essopenarchive.org/doi/full/10.1002/essoar.10511180.2 (visited on 10/26/2022). preprint.

We do get "preprint" now.

I've submitted a request to the official biblatex git.  I just asked them to make an official recommendation in the official manual about preprints.  What type a preprint should be.  Where the name of the preprint server should go. And so on and so forth.

**Comment by Dellu** [comment]
I was here to ask about the mapping of the preprints. Turns out, you guys have already fixed it. I am getting @Misc for the preprints, and all the fields are correctly mapped. 

`@misc{Workneh2022za,
  title = {Negation is discontinuous not in Amharic},
  author = {Workneh, Desalegn},
  year = {2022},
  publisher = {LingBuzz},
  url = {https://ling.auf.net/lingbuzz/006628},
  urldate = {2022-07-02},
  keywords = {amharic,morphology,negation,negative polarity items,nonconcatenative,semitic,syntax},
  annotation = {LingBuzz Published In: Work in progress}
}
`

This is absolutely what I hopped for. Thank you so much.

**Comment by retorquere** [comment]
@ryofurue if you comment here the issue will automatically reopen.
