### ISSUE TITLE
The `_eprint` comment in the `note` bib field.

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#2399]
### Debug log ID

H7JTWI8X-refs-apse

### What happened?

[It is entirely possible that I'm missing something. If so, I apologize.]

Summary: Currently, the `eprint` field is printed as "_eprint: https:// . . . " in the generated reference list.

Details:
The `eprint` field from journals is imported by Zotero browser plugin as `_eprint:` in the `Extra` field.  Here is an example article

https://doi.org/10.1029/2008GL035209

but anything from this publisher seems to include the `eprint` field.

Currently this `Extra` field is copied into the `note` field in the generated .bib file and, as a result, printed in the generated reference list as "_eprint: https:// . . . . ".

The current workaround is just to delete the `_eprint` information in the `Extra` field. . . .

I don't know what to do with this `eprint` information. Basically it's a useful piece of information. Especially the above publisher uses these three different URLs:
1.  URL to the full paper (DOI landing page) -> `doi` field;
2. URL to the abstract page -> `url` field;
3. URL to the PDF file -> `eprint` field.

This arrangement makes a lot of sense and I think the publisher is very conscientious about digital publishing, but the bibtex community or Zotero community isn't fully prepared. [**I've fixed my formatting error above.**]

**Comment by retorquere** [comment]
Can you try build 3754?

**Comment by ryofurue** [comment]
> Can you try build 3754?

Yes.  The unwanted "_eprint: https . . . " string is now gone from the reference list now.  Thank you for your prompt response!
