### ISSUE TITLE
[Bug/Feature]: Arabic script letters in citation keys

### ISSUE THREAD

**Issue by Serena-UB** [retorquere/zotero-better-bibtex#2403]
### Debug log ID

LFZ25M2F-refs-euc

### What happened?

Hi! I originally posted this on Zotero forums, and was asked to open an issue for it here.

I hope someone can help me with this:

Something strange happens to the citation keys of my Zotero entries in Arabic script. Some of the Arabic letters are automatically converted to Latin characters, but some are converted to question marks.

My citation key formula is auth+year.

An example:

The article author is هناء زايد عباس

The citation key becomes this:

hn��z�ydaab�s2020

Why are some of the Arabic characters converted and others not? If I could access the convertion table for this and modify it, it would be great.

The characters not being read, are ا and ء .

**Comment by Serena-UB** [comment]
LFZ25M2F-refs-euc

**Comment by retorquere** [comment]
Would `hnAzAydEbAs2020` be a reasonable romanization for `هناء زايد عباس`?

**Comment by Serena-UB** [comment]
In this case, the alif, "ا" is rendered "A" and the ayn "ع" is rendered E, which works well (I didn't know the citation keys were case sensitive!), but the hamza, "ء" is left out. 

The letter "ء" is often rendered either with unicode character 02BE ( ʾ ), or some kind of accent or backtick. Popularly, it is also romanized with the number 2. If it should be a letter, I suggest "x", because on the Arabic keyboard, the "ء" is in the same spot as the "x" on a qwerty keyboard.

**Comment by retorquere** [comment]
I use [jsingua](https://github.com/kariminf/jslingua) for the romanization, do you think you can discuss with the author of that library what the best choices are? I don't speak/read any arabic.

**Comment by Serena-UB** [comment]
Do you mean with the author of jslingua?

**Comment by retorquere** [comment]
Yes. I am not in a position to judge whether the changes you want make broader sense. @kariminf will get you a much better dialogue.

**Comment by Serena-UB** [comment]
Ok, I will ask him!

**Comment by retorquere** [comment]
> The letter "ء" is often rendered either with unicode character 02BE ( ʾ ), or some kind of accent or backtick. Popularly, it is also romanized with the number 2. If it should be a letter, I suggest "x", because on the Arabic keyboard, the "ء" is in the same spot as the "x" on a qwerty keyboard.

The issue is that `'` is not a legal character in citation keys, so it gets discarded. If `2` or `x` is an equally valid romanization, wouldn't it be better to make that a feature of `jslingua`? I would prefer to keep discussions about romanization between native speakers/experts, I cannot judge what is and isn't suitable.

**Comment by retorquere** [comment]
I'm now getting ``hnAzAyd`bAs2020`` as the citekey, I could make that ``hnA2zAyd`bAs2020`` if you think it's better, but I will have to take your word for it that this is a global preference qua romanization rather thanm your personal preference. I have no way to distinguish the two.

**Comment by kariminf** [comment]
Hi,

Using "Buckwalter" transliteration هناء زايد عباس will be transliterated as hnA' zAyd EbAs 

But names are a bit different to transliterate; in this case it is transliterated as: 
**hanaa zayed abbas** (both alef and hamza are transliterated to "a")

The problem with Arabic names transliteration is there are 2 different systems: east (English-pronunciation) and west (French-pronunciation). 
For example, ابو بكر can be transliterated into abu bakr (east) or abou bakr (west)

I will introduce names transliteration in jslingua in the coming version

**Comment by retorquere** [comment]
And replacing `'` with `2`?

**Comment by kariminf** [comment]
' is replaced by another a

instead of hana' we write hanaa

**Comment by Serena-UB** [comment]
For most purposes transliteration is phonetically oriented, i.e. we try to represent how the words are to be read. But in this case, we need an orthographically oriented transliteration, where each character is represented by one or two Latin keyboard characters

**Comment by Serena-UB** [comment]
There are many different transliteration systems for Arabic, there is not one or two. زايد can be rendered Zayed or Zayyed or Zayid etc. but in this case it doesn't matter, what matters is that it is possible to anticipate what the citation key for a reference will say. You cannot program ي to convert to "ye" because it will not apply to other words. "zAyd" is therefore a more appropriate orthographical romanization in this case.

**Comment by Serena-UB** [comment]
> I could make it `hnA2zAydEbAs2020` if you think it's better, but I will have to take your word for it that this is a global preference qua romanization rather than your personal preference. I have no way to distinguish the two.

Most academic transliteration systems will use symbols for this letter that are not legal characters for citation keys. And using "a" for two different Arabic characters seems to be confusing and imprecise. So I'm just trying to suggest other options that make sense. I don't think there is a right or wrong answer here. I suggested "2" and "x" for the reasons I mentioned, and I think either of them would work fine.

**Comment by retorquere** [comment]
This is exactly why I prefer that this kind of discussion is held between native speakers/experts.

**Comment by Serena-UB** [comment]
Ok, so what happens now?

**Comment by retorquere** [comment]
You tell me -- I see these comments about different romanizations for names, and I don't know whether or how to act on these. If the current romanization I showed above suffices for you, I'm willing to add that to the next release. But they may change depending on the follow-up from @kariminf.

**Comment by kariminf** [comment]
I think, since the objective is just to avoid special characters such as ' by replacing them by another such as 2, in this case a simple mapping from Buckwalter's transliteration is enough. So, no need to change jslingua (even if I add names transliteration, Buckwalter will still as it is). 

There are other characters which can be considered as special :
https://en.wikipedia.org/wiki/Buckwalter_transliteration

**Comment by retorquere** [comment]
I don't see the `'` character in the buckwalter row of the table? The only non-alphanum characters I see are `*` and `$`. I see `'` in the Qalam row.

**Comment by kariminf** [comment]
Under the table, there are hamza variants in addition to alef and harakat : 
- lone hamza: '

**Comment by retorquere** [comment]
`}` is also disallowed in citation keys.

**Comment by Serena-UB** [comment]
[BBTCitKeysArabic.pdf](https://github.com/retorquere/zotero-better-bibtex/files/10664072/BBTCitKeysArabic.pdf)

**Comment by Serena-UB** [comment]
I mapped the convertion table in the current version. What is it based on?

**Comment by retorquere** [comment]
https://www.npmjs.com/package/transliteration

**Comment by retorquere** [comment]
`�` is the [unicode replacement character](https://www.fileformat.info/info/unicode/char/fffd/index.htm) and can be loosely understood as "unknown character".

**Comment by Serena-UB** [comment]
It doesn't seem easy to find a package with only allowed transliteration characters.

I don't know whether this is useful, but it shows a use of number two for versions of the letter hamza: https://github.com/amasad/arabish

u'ء': '2',
  u'أ': '2',
  u'ؤ': '2',
  u'إ': '2',
  u'ئ': '2',
  u'آ': '2',

**Comment by retorquere** [comment]
From https://github.com/amasad/arabish:

> And it's not that hard!
...
> With a better training corpus and some simple tweaking to the rules we can get at least up to 80% accuracy of Yamli or similar services. 

These two sentences seem to contradict one another. Surely if it's "not that hard", accuracy would be 100%.

**Comment by Serena-UB** [comment]
Ok, then what about simply using "a" for "ا" and ignoring all versions of "ء" so that they are converted to nothing? The only problem for researchers working with Arabic texts are the replacement characters.

**Comment by retorquere** [comment]
I don't know what about it -- as I said, I have no idea what is reasonable/desirable here.

**Comment by retorquere** [comment]
> All these suggestions are reasonable and desirable, but there will always be different opinions.

If there will always be different opinions, I'm stuck negotiating between these opinions about a matter of which I understand nothing. But if the two of you can reach a consensus, I'll take that for now, with the proviso that if a different opinion swings by, I may change the implementation.

**Comment by retorquere** [comment]
> ignoring all versions of "ء"

What does "all versions" mean here? Is it just "all occurrences" or are there indeed different versions of this character?

> Under the table, there are hamza variants in addition to alef and harakat :
> 
>     * lone hamza: '

I have no idea what `hamza`, `alef` and `harakat` mean.

If you guys can get me a simple mapping table to pre-apply before passing the content through jslingua and/or one that I can apply after the string is passed through jslingua, that is fine, but it can't depend on me understanding anything of what is going on in the romanization.

**Comment by kariminf** [comment]
I still don't understand what is the problem here. Do you want a transliteration which is based on : Phonetics or Orthography ?  

As I understood,  you want just an orthography-oriented transliteration. In this case, I suggest a simple solution : 
- Use jslingua (Buckwalter) to transliterate Arabic letters into Latin; then
- Use the following python dictionary to map into a semi-phonetically oriented transliteration 

```
{
    "'": "a",
    ">": "a",
    "<": "i",
    "&": "u",
    "}": "i",
    "|": "a",
    "{": "a",
    "`": "a",
}
```

**Comment by retorquere** [comment]
> I still don't understand what is the problem here. Do you want a transliteration which is based on : Phonetics or Orthography ?

I don't even know what this means. I'm trying to negotiate a solution that makes sense to people who speak the language (which is not me).



> As I understood, you want just an orthography-oriented transliteration. In this case, I suggest a simple solution :
> 
>     * Use jslingua (Buckwalter) to transliterate Arabic letters into Latin; then
> 
>     * Use the following python dictionary to map into a semi-phonetically oriented transliteration
> 
> 
> ```
> 
> ```

This I can do. @Serena-UB, A new build will drop here in 10 minute or so.

**Comment by retorquere** [comment]
@Serena-UB the citekey would come out as `hnAazAydEbAs2020`.

**Comment by Serena-UB** [comment]
Perfect, thank you both!

**Comment by Serena-UB** [comment]
But what about * and $ in Buckwalter - will they work in citation keys?

**Comment by retorquere** [comment]
> But what about * and $ in Buckwalter - will they work in citation keys?

Yes, those will work.

**Comment by Serena-UB** [comment]
I downloaded it, but strangely it works only for the one reference, not for other references. Am I doing something wrong?

**Comment by Serena-UB** [comment]
I've been trying in various ways. The new transliteration now works only for references I download to Zotero through chrome, but not if I create a new reference and type in the author name myself.

**Comment by retorquere** [comment]
Have you tried refreshing the keys?

**Comment by retorquere** [comment]
> I've been trying in various ways. The new transliteration now works only for references I download to Zotero through chrome, but not if I create a new reference and type in the author name myself.

That is strange. Please turn on debug logging in the Help menu, create such a new reference again, and then right-click that item and send a debug log.

**Comment by Serena-UB** [comment]
Yes, I tried refreshing the keys.

If I download a reference, it works, even if I change the author name and retype it. But if I create a new reference, I get the old transliteration system

I already submitted a new debug log for it: STR2X8IX-refs-euc

**Comment by retorquere** [comment]
The item doesn't have a language set. For implicit romanization, you need to set the language. You can also explicitly do `auth.transliterate(ar) + year`.

**Comment by Serena-UB** [comment]
Ah, I see, it works now. Thanks!
