### ISSUE TITLE
[Bug]: relativePaths overwritten by absolute after automatic export.

### ISSUE THREAD

**Issue by Jarartur** [retorquere/zotero-better-bibtex#2405]
### Debug log ID

PXIFAKBK-refs-euc

### What happened?

Hello, and thanks for the plugin as it's really helpful.

I think I got  #1181 bug again. When I export to biblatex with `Keep updated` option checked and `relativePaths` enabled the first export is fine. Then if I make a change and it exports automatically it changes all paths to absolute again.

I also disabled caching for background exports but still it doesn't work.

**Comment by retorquere** [comment]
Can you install 3779, reproduce the problem, and send a new log?

**Comment by Jarartur** [comment]
Sure thing: `UTESESSR-refs-euc`

**Comment by Jarartur** [comment]
FYI, this test build throws an error when trying to export. I made a debug log: `7PIJPTAI-refs-euc`.

**Comment by retorquere** [comment]
I see what's happening.

**Comment by Jarartur** [comment]
Unfortunately the issue still persists. Attaching new log as a feedback: 5XJE96DK-refs-euc

**Comment by retorquere** [comment]
Can you get me a new log?

**Comment by Jarartur** [comment]
Sure: `N3SDEW3G-refs-euc`. Thank you for the continued support :)

**Comment by retorquere** [comment]
Can you go into Prefs -> Export -> Misc, disable caching, and see if that makes a difference?

**Comment by Jarartur** [comment]
I do not have it enabled:
![image](https://user-images.githubusercontent.com/45856425/218517943-a3119055-d508-491b-b0f2-e083d7d2cd0e.png)

**Comment by retorquere** [comment]
I'll need a new log

**Comment by Jarartur** [comment]
WGRLRBT6-refs-euc

**Comment by retorquere** [comment]
again please.

**Comment by Jarartur** [comment]
Happy to report it is working now 🥳.

Thanks for the support.
