### ISSUE TITLE
[Bug/Feature]: Zotero to Obsidian: automatic update not working 

### ISSUE THREAD

**Issue by pumpkinfiasco** [retorquere/zotero-better-bibtex#2407]
### Debug log ID

R9A339SK-euc

### What happened?

I have the Zotero/Obsidian workflow set up. The documents that were in my Zotero library at the time I created this are all there, but whenever I try to add new stuff it's not updating. As far as I can tell this is all set up to automatically update through BibLaTex, but even when I use the 'export now' button the new sources aren't showing up when I try to cite them in Obsidian.

**Comment by retorquere** [comment]
No BBT error in `R9A339SK-euc`. Does the bib file on disk update when you click 'export now'?

There is a separate error in the log from another plugin, I don't think it's related to this, but you might want to inform the author:

```
[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 883}]
Security Error: Content at moz-nullprincipal:{18a5810b-d102-4694-a3b8-05f63b28792c} may not load or link to chrome://knowledge4zotero/content/treeView.html.
```

**Comment by pumpkinfiasco** [comment]
Hey, yeah it looks like it has - I recently changed some of the folder names in Zotero and that is showing.

**Comment by retorquere** [comment]
Any updates?
