### ISSUE TITLE
[Bug]: BBT Stuck on "Better BibTeX is Loading"

### ISSUE THREAD

**Issue by jacobtfisher** [retorquere/zotero-better-bibtex#2408]
### Debug log ID

? (Can't get one)

### What happened?

Hi there, 

I'm on MacOS 13.2, with the latest versions of both Zotero and BBT

I'm not sure exactly what the issue is (and I can't get a debug log since BBT isn't loading at all), but since the latest BBT update I'm no longer able to use BBT at all. When I go to the preferences, it just says "Better BibTeX is loading," and when I check the Zotero error logs, it just says: 

```
[JavaScript Error: "TypeError: Zotero.BetterBibTeX is undefined" {file: "chrome://zotero/content/standalone/standalone.xul" line: 1}]
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1
```

I've tried uninstalling and reinstalling both BBT and Zotero with no luck. Any suggestions as to how I could continue to troubleshoot this issue?  

EDIT: After enabling debug logging, I still can't get a BBT debug log (it just doesn't do anything when I click the menu option). I did get a new error message in the Zotero Error Report though:

```
[JavaScript Error: "NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setIntPref]" {file: "chrome://zotero-better-bibtex/content/better-bibtex.js" line: 5885}]
setDefaultPrefs@chrome://zotero-better-bibtex/content/better-bibtex.js:5885:17
PreferenceManager2@chrome://zotero-better-bibtex/content/better-bibtex.js:5843:11
content/prefs.ts@chrome://zotero-better-bibtex/content/better-bibtex.js:5833:20
__init@chrome://zotero-better-bibtex/content/better-bibtex.js:20:26
@chrome://zotero-better-bibtex/content/better-bibtex.js:272429:3
@chrome://zotero-better-bibtex/content/better-bibtex.js:3:1
```

**Comment by retorquere** [comment]
Can you try install build 3802, go into Help -> Debug -> restart with debugging enabled, let Zotero restart, and send a debug log?

**Comment by jacobtfisher** [comment]
Build 3802 seems to have fixed the issue, but just in case, I submitted a debug log (`BAK3S8T2-euc`). Thank you!

**Comment by retorquere** [comment]
It didn't fix the issue, I put in a workaround that allowed it to start so I could diagnose the error, the problem is still there. Can you please go into Help -> Debug -> restart with debugging enabled, let Zotero restart, and send a debug log? It looks like with `BAK3S8T2-euc` the logging was turned on after the restart, I really need it to be on during start.

**Comment by jacobtfisher** [comment]
> It didn't fix the issue, I put in a workaround that allowed it to start so I could diagnose the error, the problem is still there. Can you please go into Help -> Debug -> restart with debugging enabled, let Zotero restart, and send a debug log? It looks like with `BAK3S8T2-euc` the logging was turned on after the restart, I really need it to be on during start.

Done! The new log ID is `SEMFTN42-euc`.

**Comment by retorquere** [comment]
Still nothing in the log. Build 3815 should put up a popup with an error message, I need to know what it says.

**Comment by jacobtfisher** [comment]
Sounds good. I'm working from my other computer today so I won't be able to get around to this until the evening but I should have something for you then.

**Comment by jacobtfisher** [comment]
Ok I just installed that version and an error message popped up with something to the effect of `autoPinDelay cannot be set to 0` — I recall changing that setting a long time ago when I was working with an extension that used BBT citekeys. When I changed the setting and restarted Zotero with logging enabled, the message didn’t pop up again.  I did just submit 
another error report (`K4Y4WU89-euc`), but apologies if changing that setting before restarting makes the report less helpful. Let me know if there’s any other way I can help figure this out.

**Comment by retorquere** [comment]
The erroneous value will have been replaced now, so I don't think I can do further diagnosis. Do you remember what you set it to previously?

**Comment by jacobtfisher** [comment]
I think that it was set to 0, but IIRC, it had somehow encoded it as a string instead of an integer. I could be wrong on that, though, so take it with a large grain of salt.

**Comment by retorquere** [comment]
That would have done it.
