### ISSUE TITLE
Cannot select "keep updated"

### ISSUE THREAD

**Issue by Januzsch** [retorquere/zotero-better-bibtex#2411]
**Keep updated Button un clickable**

By mistake I deleted my automatic export Library in BBT, if I try to export my library again, it is impossible to click the "keep updated" box. I see it but its unclickable.
Can anyone plz help?

<img width="349" alt="Bildschirm­foto 2023-02-12 um 18 36 07" src="https://user-images.githubusercontent.com/125210433/218327212-4cf4b537-df47-4c4b-a584-4d77067bff5b.png">

**Comment by retorquere** [comment]
Disable "Dateien exportieren". Auto-export does not support exporting attachments.

**Comment by Januzsch** [comment]
THANK YOU! I searched for hours to find the problem and it was so easy^^

**Comment by retorquere** [comment]
It's always OK to ask. UI work is not my strong point.
