### ISSUE TITLE
[Bug/Feature]: auto push failed with exit status 128

### ISSUE THREAD

**Issue by Victor-Le-Coz** [retorquere/zotero-better-bibtex#2412]
### Debug log ID

F7B2A9T6-euc

### What happened?

Hi,

Suddenly, my auto-push to overleaf doesn't work anymore.

I checked that I can push manually, every thing works fine, except some warnings:

warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
warning: failed to probe 'https://git.overleaf.com/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
warning: failed to probe 'https://git.overleaf.com/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 548 bytes | 78.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2)
remote: Updating references: 100% (1/1)
To https://git.overleaf.com/xxxx
   xxxxxx master -> master

Here is my .gitconfig file:
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://git.overleaf.com/xxxx
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[zotero "betterbibtex"]
	push = true

I have the following bug:

auto push failed with exit status 128

Many thanks in advance for your help, 

Victor

**Comment by retorquere** [comment]
I can't retrieve `F7B2A9T6-euc`, something must have gone wrong in the submission. This is on Windows yeah? What git client produced the output you pasted? The command line client? What is `%errorlevel%` after this runs?

**Comment by Victor-Le-Coz** [comment]
Dear Emiliano, 

Thank you for your quick response.

I have created and send a new debug report 7XH9MIJC-euc.

Indeed, it is git on windows unfortunately, and I used git bash “MINGW64” to run manually my push to overleaf to test if git works without better bib tex (also I don’t know what means command line client )

I did not understand your last question, where should I look for errorlevel ? I could not find it in my debug file !

Kind regards,

Victor

**Comment by retorquere** [comment]
> I have created and send a new debug report 7XH9MIJC-euc.

Thanks, that has the info I need
 
> Indeed, it is git on windows unfortunately, and I used git bash “MINGW64” to run manually my push to overleaf to test if git works without better bib tex (also I don’t know what means command line client )

It's a program you run from `CMD` by typing it's name.

If you open `CMD` and type in

```
C:\Users\vlecoz\AppData\Local\Programs\Git\cmd\git.EXE -C L:\overleaf\xxxx pull
```

and press `Enter`, does that work? That's what BBT is doing under the hood

> I did not understand your last question, where should I look for errorlevel ? I could not find it in my debug file !

After the command is finished, you can type

```
echo %errorlevel%
```

and it will tell you whether the previous program you started in `CMD` has actually finished successfully

**Comment by Victor-Le-Coz** [comment]
Thank you, indeed, it seems to be a git issue, I run my first tests with "git bash" not with the direct git cmd used by BBT.

Here is the error I get when running the cmd:
_C:\Users\vlecoz>C:\Users\vlecoz\AppData\Local\Programs\Git\cmd\git.EXE -C C:\Users\vlecoz\Documents\overleaf\xxxx pull
      0 [main] sh 2470 C:\Users\vlecoz\AppData\Local\Programs\Git\usr\bin\sh.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    335 [main] sh 2470 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
      0 [main] bash 2471 C:\Users\vlecoz\AppData\Local\Programs\Git\usr\bin\bash.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    323 [main] bash 2471 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
      0 [main] bash 2472 C:\Users\vlecoz\AppData\Local\Programs\Git\usr\bin\bash.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    359 [main] bash 2472 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
      0 [main] sh 2473 C:\Users\vlecoz\AppData\Local\Programs\Git\usr\bin\sh.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    413 [main] sh 2473 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
remote: Please sign in using your email address and Overleaf password.
remote:
remote: *Note*: if you sign in to Overleaf using another provider, such
remote: as Google or Twitter, you need to set a password on your Overleaf
remote: account first. Please see https://www.overleaf.com/learn/how-to/Troubleshooting_git_bridge_problems
remote: for more information._

Please note that (i) I moved my directory to make sure it is not a location issue, (ii) i only have one cmd prompt open.

Finnaly, here is the "echo %errorlevel%" cmd result:
1

Best,

**Comment by retorquere** [comment]
> `0 [main] sh 2470 C:\Users\vlecoz\AppData\Local\Programs\Git\usr\bin\sh.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32`

I have no idea what this error means, but it looks like that's at least one of the reasons why the pull fails.

I don't know how you ran `git bash`, but `C:\Users\vlecoz\AppData\Local\Programs\Git\cmd\git.EXE` is being used by BBT because it is first in your [PATH](https://windowsreport.com/edit-windows-path-environment-variable/). If you edit the `PATH` variable so that the directory in which your `git bash` is found comes first, BBT will use that.

**Comment by retorquere** [comment]
Did that work? Or does the error remain?

**Comment by Victor-Le-Coz** [comment]
I do not have sufficient administrative rights to test this, but I have asked people to help, I keep you informed !

**Comment by Victor-Le-Coz** [comment]
Hi,

For information, the issue is solved. It was due to hidden background processes git.exe observable only in the task manager. It seems that each of the pull / push updates created a process that was never closed then, until 32 processes were opened. Beyond this limit, all the pull / push failed due to the above windows error (more than 32 git.exe running).

I don't know why this processes did not close in the first place, maybe an exit cmd at the end of the BBT push would avoid this issue in the future (if it ever happens again, because I do not observe any unclose git.exe currently).

Best,

**Comment by retorquere** [comment]
I don't start these processes using `cmd`, so there's nothing to send an `exit` to.
