### ISSUE TITLE
[Bug/Feature]:  Unable to process Russian  "ь" symbol while transliteration

### ISSUE THREAD

**Issue by Alex-Romanko** [retorquere/zotero-better-bibtex#2413]
### Debug log ID

4UJYKHKF-refs-euc

### What happened?

I've faced an error when truing to work with library that contains citations written in russian. When Better BibTex generates the citation index it tries to transliterate russian alphabet and fails with "ь" symbol which leads to creation indexes like this: roman�koPolimeraznayaCepnayaReakciya2022. Then pandoc fails  to reed the database.bib and fails with error: 

```
unexpected '\65533'
Error: pandoc document conversion failed with error 25
```

Is it possible to filter this symbol during index generation?

**Comment by Alex-Romanko** [comment]
Thank you for your prompt response! I have installed the test build and it has resolved the issue!

**Comment by retorquere** [comment]
Would `romankoPolimeraznaiaTsepnaiaReaktsiia2022` also be an acceptable transliteration?
