### ISSUE TITLE
Author multi-character initial gets shortened

### ISSUE THREAD

**Issue by juhaszp95** [retorquere/zotero-better-bibtex#2419]
### Debug log ID

3BSUIU2B-refs-euc

### What happened?

Hello,

First of all, many thanks for developing this plugin.

Occasionally, there are authors whose first name initials are in fact multiple characters, see e.g. the last author Yu. E. Lozovik in https://journals.aps.org/pra/abstract/10.1103/PhysRevA.75.063630. This is not necessarily a typo but something that authors from non-English speaking countries ask for (e.g. when they have non-latin alphabets).

When the author name is kept in Zotero as "Lozovik, Yu. E." (i.e. as two fields) it gets incorrectly printed in the bibliography in LaTeX as "Y. E. Lozovik", whereas if it's kept in Zotero as "Yu. E. Lozovik" (i.e. as one field) it gets correctly printed as "Yu. E. Lozovik". This is probably to do with the fact that in the latter case the name is protected by an extra set of braces in the exported .bib file, so BibLaTeX/Biber doesn't try to shorten it. (The .bib was exported with BBT.)

Could this be fixed such that the behaviour would be the same regardless of how it was entered in Zotero? (It took me some time to ensure correct behaviour, it seems that even protecting the name in the two-field format as <pre>{{Yu.}}</pre> doesn't help, although the braces seem to propagate to the .bib file, so this might be a BibLaTeX/Biber issue in fact.

Many thanks,
Péter

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/exporting/advanced/#recognizing-initials-in-names works, but I see now it is a bit ugly, so a new build will drop here that adds a soft-hyphen (`﻿`) as a delimiter.

**Comment by retorquere** [comment]
Can you see whether build 3878 works for you with last name `Lozovik` and first name `Yu.⁣ E.`?

**Comment by juhaszp95** [comment]
I'm afraid it still gets shortened to Y. E. Lozovik. (The entry in the .bib file is now "Lozovik, {\relax Yu.} E.".)

**Comment by retorquere** [comment]
What should it look like in the bib file to get the desired effect? And do you have an MWE latex document for me?

**Comment by juhaszp95** [comment]
I've actually tried a couple times and couldn't get the two-field version to work with any combination of braces, \relax etc. The one-field version works out of the box - so this might be a BibLaTeX problem in the end.

Here's an MWE LaTeX file:

\documentclass{article}
\usepackage[style=phys]{biblatex}
\addbibresource{refs.bib}

\begin{document}
	One field: \cite{Astrakharchik2007_onefield}
	
	Two fields: \cite{Astrakharchik2007_twofield}
	
	BBT suggestion: \cite{Astrakharchik2007_BBT}
	
	\printbibliography
\end{document}

And here's the associated bib file:

\documentclass{article}
\usepackage[style=phys]{biblatex}
\addbibresource{refs.bib}

\begin{document}
	One field: \cite{Astrakharchik2007_onefield}
	
	Two fields: \cite{Astrakharchik2007_twofield}
	
	BBT suggestion: \cite{Astrakharchik2007_BBT}
	
	\printbibliography
\end{document}


Out of all these, only the one-field version gives the desired output.

**Comment by retorquere** [comment]
@njbart? Surely there's a solution to this?

**Comment by njbart** [comment]
Try the biber/biblatex extended name format, something along these lines:

`author = {family=Duchamp, given=Philippe, given-i={Ph}},`

For details, see the biber manual (and https://github.com/retorquere/zotero-better-bibtex/issues/566).

**Comment by juhaszp95** [comment]
The following entry produces the right result for me:
```
author = {family=Lozovik, given=bla, given-i={Yu. E}}
```
But if I delete the "given" part, it just gives "Lozovik" (and ignores the given-i part). Also note the period needed after Yu but not after E.

**Comment by retorquere** [comment]
*smacks forehead* of course. In build 3883 you can check "extended name format" under the biblatex prefs and it'll do the right thing. @njbart maybe I should just default that to `true`? This isn't new-ish anymore at this stage right?

**Comment by retorquere** [comment]
@juhaszp95 you want the initials to be `Yu. E.`? That will require a different solution I think.

**Comment by juhaszp95** [comment]
Yes, the name should come out as Yu. E. Lozovik, and we don't know (straightforwardly) where these initials come from, i.e. we don't know what the full given names are.

**Comment by retorquere** [comment]
Then for your specific case, setting the first name to `Yu. E.⁣` will probably do it (I just moved the marker to the end). I'm still pondering a more general solution to generate `given-i` in the case of multiple firstnames, but it will probably end up with me making some [naive assumptions about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). Nice rabbit hole to chase down.

**Comment by retorquere** [comment]
I'm trawling through citeproc to see how it generates initials.

**Comment by retorquere** [comment]
It doesn't apparently for cases like this. I agree the hidden char is clunky -- I'm considering adding a mapping list where one can add exceptions like these.

**Comment by retorquere** [comment]
@njbart should `given-i` have periods? Should eg `Jacques Philippe Marie` come out as `given-i=JPhM`, `given-i=J. Ph. M.`, `given-i=J Ph M`, something else? The biber manual shows an example but doesn't really say whether it has any expectations for what goes in the field.

**Comment by retorquere** [comment]
@juhaszp95 I think I have a solution, no invisible characters required. Can you try build 2419?

**Comment by juhaszp95** [comment]
I presume you meant build 3917? Using that, Zotero still gives "Lozovik, Yu. E." in the bib file which then gets turned into Y. E. Lozovik, as before I'm afraid. (Although there might be an invisible character here I don't see? Either way, it didn't help I'm afraid.)

**Comment by retorquere** [comment]
I did mean build 3917, yes. The entire business with special marker characters is out, and for me `3BSUIU2B-refs-euc` exports to (after switching the name to two-field mode)

biblatex:
```
@article{astrakharchik2007,
  title = {Weakly Interacting Two-Dimensional System of Dipoles: {{Limitations}} of the Mean-Field Theory},
  shorttitle = {Weakly Interacting Two-Dimensional System of Dipoles},
  author = {Astrakharchik, G. E. and Boronat, J. and Casulleras, J. and Kurbakov, I. L. and family=Lozovik, given=Yu. E., given-i=Yu. E.},
  date = {2007-06-29},
  journaltitle = {Physical Review A},
  shortjournal = {Phys. Rev. A},
  volume = {75},
  number = {6},
  pages = {063630},
  issn = {1050-2947, 1094-1622},
  doi = {10.1103/PhysRevA.75.063630},
  url = {https://link.aps.org/doi/10.1103/PhysRevA.75.063630},
  urldate = {2023-02-22},
  langid = {english}
}
```

bibtex:
```
@article{astrakharchik2007,
  title = {Weakly Interacting Two-Dimensional System of Dipoles: {{Limitations}} of the Mean-Field Theory},
  shorttitle = {Weakly Interacting Two-Dimensional System of Dipoles},
  author = {Astrakharchik, G. E. and Boronat, J. and Casulleras, J. and Kurbakov, I. L. and Lozovik, {\relax Yu. E.}},
  year = {2007},
  month = jun,
  journal = {Physical Review A},
  volume = {75},
  number = {6},
  pages = {063630},
  issn = {1050-2947, 1094-1622},
  doi = {10.1103/PhysRevA.75.063630},
  langid = {english}
}
```

**Comment by retorquere** [comment]
Can you switch the name to two-field mode and send a new log for the item from build 3917?

**Comment by juhaszp95** [comment]
I've just sent debug log VWL7MWRH-refs-euc. It's strange. I've restarted Zotero (again) and now it exports it as "Lozovik, {\relax Yu. E.}", no matter if I choose Better BibTeX or Better BibLaTeX. (I've tried restarting Zotero again a couple times / exporting it in different formats, but this is what it now gives.)

**Comment by retorquere** [comment]
> no matter if I choose Better BibTeX or Better BibLaTeX

That's because you have biblatex extended name format support off; when it's off, both exporters do export this way. In any case, does this render as you want?

**Comment by juhaszp95** [comment]
Oh that's right. The \relax version doesn't work. I've enabled that setting now, restarted Zotero, and it now exports it as "family=Lozovik, given=Yu. E., given-i=Yu. E.".  That comes out as "Y. u. . E. . Lozovik". However, if I change it to "family=Lozovik, given=Yu. E., given-i={Yu. E.}" (note extra braces) it comes off correctly. So I think we're close to a solution! We just need those extra braces. (Maybe around the given field too, but my template only uses the abbreviation.)

**Comment by retorquere** [comment]
Do you have an MWE for me that you use to compile these? I'm trying to figure out what biber expects in the `given-i`. Does `given-i={Yu}E` work?

**Comment by juhaszp95** [comment]
Sure -- the same as before.

LaTeX MWE:
```\documentclass{article}
\usepackage[style=phys]{biblatex}
\addbibresource{refs.bib}

\begin{document}
	One field: \cite{Astrakharchik2007_onefield}
	
	Two fields: \cite{Astrakharchik2007_twofield}
	
	\printbibliography
\end{document}
```

Bib file:
```
@article{Astrakharchik2007_twofield,
	title = {Weakly interacting two-dimensional system of dipoles: {{Limitations}} of the mean-field theory},
	shorttitle = {Weakly interacting two-dimensional system of dipoles},
	author = {Astrakharchik, G. E. and Boronat, J. and Casulleras, J. and Kurbakov, I. L. and family=Lozovik, given=Yu. E., given-i=Yu. E.},
	date = {2007-06-29},
	journaltitle = {Phys. Rev. A},
	volume = {75},
	number = {6},
	pages = {063630},
	issn = {1050-2947, 1094-1622},
	doi = {10.1103/PhysRevA.75.063630},
	url = {https://link.aps.org/doi/10.1103/PhysRevA.75.063630},
	urldate = {2023-02-22},
	langid = {english}
}

@article{Astrakharchik2007_onefield,
	title = {Weakly interacting two-dimensional system of dipoles: {{Limitations}} of the mean-field theory},
	shorttitle = {Weakly interacting two-dimensional system of dipoles},
	author = {Astrakharchik, G. E. and Boronat, J. and Casulleras, J. and Kurbakov, I. L. and {Yu. E. Lozovik}},
	date = {2007-06-29},
	journaltitle = {Phys. Rev. A},
	volume = {75},
	number = {6},
	pages = {063630},
	issn = {1050-2947, 1094-1622},
	doi = {10.1103/PhysRevA.75.063630},
	url = {https://link.aps.org/doi/10.1103/PhysRevA.75.063630},
	urldate = {2023-02-22},
	langid = {english}
}
```

If I change given-i to {Yu}E that also works! (As well as {Yu. E.}.)

**Comment by retorquere** [comment]
New build is incoming that does that. Relax only works for bibtex, not biblatex, it turns out, so that means the only way to get "special" initials done right is with the extended name format.

As an aside, here's a neat trick for self-contained MWEs BTW:

```latex
\documentclass[american]{article}
\usepackage[style=phys, backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@article{Astrakharchik2007_twofield,
	title = {Weakly interacting two-dimensional system of dipoles: {{Limitations}} of the mean-field theory},
	shorttitle = {Weakly interacting two-dimensional system of dipoles},
	author = {Astrakharchik, G. E. and Boronat, J. and Casulleras, J. and Kurbakov, I. L. and family=Lozovik, given=Yu. E., given-i={{Yu}}E},
	date = {2007-06-29},
	journaltitle = {Phys. Rev. A},
	volume = {75},
	number = {6},
	pages = {063630},
	issn = {1050-2947, 1094-1622},
	doi = {10.1103/PhysRevA.75.063630},
	url = {https://link.aps.org/doi/10.1103/PhysRevA.75.063630},
	urldate = {2023-02-22},
	langid = {english}
}
\end{filecontents*}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by juhaszp95** [comment]
Should I give this build 3928 a try then?

**Comment by retorquere** [comment]
I'd appreciate it, just as a final check.

**Comment by juhaszp95** [comment]
Works amazingly, thanks very much! I think we can close this issue now. I guess this will be built into one of the future ordinary releases? (So I can upgrade safely.)

**Comment by retorquere** [comment]
I'm hoping to close #2398 if I get some feedback, and then I'm cutting a new release, but it will likely just be 3928 with a new version number slapped on. No need to do anything, it will automatically upgrade when I release it.

**Comment by juhaszp95** [comment]
Hello,

Sorry to have to reopen this, but I'm having the same issue again: debug log ID ZJEAST6M-refs-euc.

This time it's not the first, but the second initial of some authors that are shortened to just character. Perhaps the fix implemented so far only checks the first initial?

**Comment by retorquere** [comment]
You need to add periods to have them be recognized as initials. I have to steer clear of [making too many assumptions about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) -- I can't safely assume it is initialized just because the "name" is short.

**Comment by juhaszp95** [comment]
Ah, I see, makes sense. Thanks - adding the periods resolved the issue.
