### ISSUE TITLE
[Feature]: Apply case-protection to whole title rather than individual words

### ISSUE THREAD

**Issue by juhaszp95** [retorquere/zotero-better-bibtex#2424]
### Debug log ID

8W8TJL8D-refs-euc

### What happened?

Hello Again,

Many thanks for closing #2419 again.

This time I'm opening an issue as currently when the "Apply case-protection to capitalized words by enclosing them in braces" option is enabled in Export, it does exactly that -- applies case-protection to capitalised words in the title by enclosing the individual words (or sometimes multiple words) in braces. However, if a title contains dashes and the like, with capital words on both sides of the dash, this individual protection of the words separately makes it difficult for LaTeX to apply fine typographical adjustments (e.g. via package microtype), as it cannot treat the text as a whole and is interrupted by these braces. This results in some (minor) differences between the cases where the whole title is protected altogether in braces versus individual words are protected individually with braces.

It would be great to have the option to enclose the whole title in braces, protecting its capitalisation, rather than words individually. This would seem to be more correct and closer to the intention of printing the title "as-is".

E.g. the title "Atomic Energy Levels—The Rare-Earth Elements" should be exported in BibLaTeX as ```title = {{{Atomic Energy Levels—The Rare-Earth Elements}}}``` (or maybe one less set of braces), and not ```title = {Atomic {{Energy Levels}}—{{The Rare-Earth Elements}}}``` which is the current behaviour.

I can reproduce the desired behaviour by setting the title ```<pre>{{Atomic Energy Levels—The Rare-Earth Elements}}</pre>``` in Zotero, but it would be great to not have to do that.

**Comment by retorquere** [comment]
If you add a tag `#LaTeX` to an item, all fields will be treated as raw latex.

I understand what you want to do, and we can certainly talk about better ways to do caps protection, but the base assumption is always going to be that titles are stored in Zotero as sentence case, because that's what zotero expects.

**Comment by juhaszp95** [comment]
I see what you mean. I guess there are some more examples I can give that better highlight the issue.
- If I have the (I think) default settings, which is: "apply title-casing to titles" ON (export), "apply case protection to capitalized words" ON (export), and "sentence-case titles on import" on "yes, but try to exclude already sentence-cased titles". When I now import DOI 10.1103/PhysRevLett.115.243002, in Zotero (using the magic wand tool), the title appears as "Cooling of a Bose-Einstein Condensate by Spin Distillation" in the Zotero entry (i.e. it is actually not sentence-cased, it is the original casing). When I export this entry as BibLaTeX it gives ```title = {Cooling of a {{Bose-Einstein Condensate}} by {{Spin Distillation}}}``` which is fine.
- With the same settings I import DOI 10.1103/PhysRevA.77.013404 (by Yu. E. Lozovik :)); and the title in Zotero appears as "Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases" (which is the original casing). When I export this it gives ```title = {Super-{{Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}```, which is where my problem lies, as it should rather give ```title = {{{Super-Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}```. By the way, when this bib entry is compiled in LaTeX, it comes off as "Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases", i.e. the sentence-casing was ignored altogether by BibLaTeX when generating the entry.
- For this same entry I actually want to achieve ```{{Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases}}``` or at least ```{{{Super-Tonks-Girardeau}} regime in trapped one-dimensional dipolar gases}```. This is currently only possible if I have title-casing on export OFF, and set the title in Zotero as ```<pre>{{Super-Tonks-Girardeau}}</pre> regime in trapped one-dimensional dipolar gases```. I filed this as debug log ID MQ8YGDF2-refs-euc.

I hope these give a bit more insight. I think there are two (independent) things that could be done:
- Include the word(s) around hyphens etc. within the same set of braces. (This is regardless of the casing of the title.)
- Have the option to not apply any transformation to titles at all, but to export (and potentially import) them "as-is".

**Comment by retorquere** [comment]
> * and "sentence-case titles on import" on "yes, but try to exclude already sentence-cased titles". When I now import DOI 10.1103/PhysRevLett.115.243002, in Zotero (using the magic wand tool), the title appears as "Cooling of a Bose-Einstein Condensate by Spin Distillation" in the Zotero entry (i.e. it is actually not sentence-cased, it is the original casing).

Which is a problem, as it *should* be "Cooling of a Bose-Einstein condensate by spin distillation" in Zotero. But the BBT importer is not in play here, a different importer does this.

> When I export this entry as BibLaTeX it gives `title = {Cooling of a {{Bose-Einstein Condensate}} by {{Spin Distillation}}}` which is fine.

It is actually not fine:

```latex
\documentclass[american]{article}
\usepackage[style=apa, backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@article{one,
    author = {Me},
	title = {{{Super-Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}
}
@article{two,
    author = {Me},
	title = {Cooling of a {{Bose-Einstein Condensate}} by {{Spin Distillation}}}
}
\end{filecontents*}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

APA says titles should be sentence-case, and the Cooling entry has brace protection which prevents the title from being actively sentence-cased by biblatex.

> * When I export this it gives `title = {Super-{{Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}`, which is where my problem lies, as it should rather give `title = {{{Super-Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}`.

Why? Capitals at the start of a title are never case-changed by bib(la)tex so need no protection.

> By the way, when this bib entry is compiled in LaTeX, it comes off as "Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases", i.e. the sentence-casing was ignored altogether by BibLaTeX when generating the entry.

bib(la)tex expects title-case and actively sentence-cases for styles that demand it, but in this case there is nothing to title-case, so it happens to come out as it went in. It ought to come out as sentence-cased too if you have `{{{Super-Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}`

> * For this same entry I actually want to achieve `{{Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases}}`.

Which will render incorrectly for styles that demand title-cased output.

> or at least `{{{Super-Tonks-Girardeau}} regime in trapped one-dimensional dipolar gases}`

Which will likewise render incorrectly for styles that demand title-cased output.

**Comment by juhaszp95** [comment]
Thanks for the comments. A couple points:
- I use biblatex-phys to generate a nice output, but I want to deviate from its style by keeping the titles as-is. This is a matter of taste. This can be done by protecting capitalised words.
- ```{Super-{{Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}``` is different to ```{{{Super-Tonks-Girardeau}} regime in trapped one-dimensional dipolar gases}``` which is equivalent (for my purpose) to ```{{Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases}}```. This is not due to capitalisation but due to the issue I described in the original question -- if a title contains dashes and the like, with capital words on both sides of the dash, this individual protection of the words separately makes it difficult for LaTeX to apply fine typographical adjustments (e.g. via package microtype), as it cannot treat the text as a whole and is interrupted by these braces. This results in some (minor) differences between the cases where the whole construct is protected altogether in braces versus individual words are protected individually with braces. It just so happens that the first word in the hyphenated construct is the first word of the title, but all words in the construct should be within the same set of braces, wherever they appear in the title.

So:
- I think ```{{{Super-Tonks-Girardeau}} regime in trapped one-dimensional dipolar gases}``` should always be preferred over ```{Super-{{Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases}``` in export.
- It would be nice to have the option ```{{Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases}}``` if someone wants to print the title as-is, without any modifications whatsoever (i.e. don't bother with case protection etc., just protect the whole thing).

**Comment by retorquere** [comment]
> I think {{{Super-Tonks-Girardeau}} regime in trapped one-dimensional dipolar gases} should always be preferred over {Super-{{Tonks-Girardeau}} Regime in Trapped One-Dimensional Dipolar Gases} in export.

I will consider grabbing the first word in the caps protection (@njbart, opinions on this?); exporting as sentence-case can be done by disabling "Apply title-casing to titles".

> It would be nice to have the option {{Super-Tonks-Girardeau regime in trapped one-dimensional dipolar gases}} if someone wants to print the title as-is, without any modifications whatsoever (i.e. don't bother with case protection etc., just protect the whole thing).

You mean for all titles then, not something per-entry? This can be easily achieved with a postscript. It looks to me like a way to subvert the expectations of the citation processor, and I'd rather not add an extra setting for that. I already have too many of these (such as "apply title-casing"); I keep these for backwards compat, but I just shouldn't have added them in the first place.

**Comment by juhaszp95** [comment]
Many thanks.

Re caps protection around dashes: The important part is that all words around dashes/hyphens should be protected in the same set of braces, wherever they appear (including in the front). This was the point of the original example: ```title = {Atomic {{Energy Levels—The Rare-Earth Elements}}}``` should be preferred over ```title = {Atomic {{Energy Levels}}—{{The Rare-Earth Elements}}}```. I.e. the important part is to include the whole hyphen/dash structure in the protection when a word on either side should be protected.

Re protecting the whole title: Yes, all titles in an export would be most ideal, and yes, this can be done post-processing (but it is more convenient if that's not needed), but I understand why you think that should not be done. (I either have to subvert the expectations of biblatex-phys, or rewrite biblatex-phys myself. The former is more convenient, the latter is more correct (and more work).)

**Comment by retorquere** [comment]
Just to be clear, with a postscript I mean a BBT postscript with BBT would apply automatically, not something you'd have to do manually after the export.

Is it always the case that each part of a multi-part word or each word in a dash-separated sequence of words should be all be case-protected, just because any one part of it needs case protection? It never happens that a part/word exists which should not be case-protected even though it is attached to one that does need it?

BTW Zotero supports arbitrary case protections by enclosing any part of the title with `<span class="nocase">...</span>`, and BBT will honor those. I think `<nc>...</nc>` also works. This is the generic Zotero facility for case protection, and will also work in Word.

**Comment by juhaszp95** [comment]
That is a very good and subtle point you raise. Let's consider a made-up title "Properties of anti-Bose commutators" (sentence-case). Here only Bose should be protected from a casing point of view, but from a typography point of view anti-Bose should go in the same braces. 

If BBT exports it as ```{{anti-Bose}}``` but one uses a style that wants to convert this to title-case, that would be a problem. However, you can control in the current settings how to export the title case-wise, so you have control over that and could specify it to match the style you then want to use (I think). Just saying -- maybe this is another use-case for encapsulating the whole title in braces, so you can be sure of your output... Or you could just care about the single entry.

**Comment by juhaszp95** [comment]
You're right Re encapsulating all - but at least it would give predictable behaviour. (And it still solves the problem to be able to export a title as-is.) 

I guess this is a subtle problem where different behaviour would be desirable in different cases.

**Comment by retorquere** [comment]
Wouldn't turning off title-casing and brace-protection and adding `\DeclareFieldFormat{titlecase}{#1}` to the preamble do what you want? That will just turn of sentence-casing in biblatex and that should make it so exactly what is in Zotero would show up in your output.

**Comment by juhaszp95** [comment]
No, as I want to print all titles as-is (as was originally printed), some of which are sentence-case, some of which are not.

**Comment by retorquere** [comment]
I understand that, but given that biblatex assumes "title-case means do nothing", that's exactly what you want.

**Comment by juhaszp95** [comment]
Biblatex might, but biblatex-phys doesn't. If words aren't protected, they get converted to lowercase. I.e. both ```title = {Properties of anti-Bose commutators}``` and ```title = {Properties of Anti-Bose Commutators}``` are rendered as "Properties of anti-bose commutators". Only ```title = {Properties of {{anti-Bose}} commutators}``` or ```title = {{Properties of anti-Bose commutators}}``` give what I need ("Properties of anti-Bose commutators").

**Comment by retorquere** [comment]
This seems to work for me:

```latex
\documentclass[american]{article}
\usepackage[style=phys, backend=biber]{biblatex}
\usepackage{filecontents}
\DeclareFieldFormat{titlecase}{#1}
\begin{filecontents*}{\jobname.bib}
@article{one,
    author = {Me},
	title = {{{Super-Tonks-Girardeau}} regime in trapped one-dimensional dipolar gases}
}
@article{two,
    author = {Me},
	title = {Cooling of a Bose-Einstein Condensate by Spin Distillation}
}
\end{filecontents*}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by juhaszp95** [comment]
Oh, you're right! I thought this converts all titles to titlecase, but I see what you did now. So I guess I could just switch off protecting capitalisation in BBT export and use this biblatex setting. Nice. I think this solves my problem. I guess the question of how/whether to include hyphens in capitalisation-protection still holds, but it's up to you to figure out how it is best to take care of that.

**Comment by retorquere** [comment]
Yep, if you turn off caps protection and title-casing under export, you should have what you want.

The `anti-Bose` example is a breaking case, so I won't do that. Whether `Super-` should be included in the caps protection is something I can consider, but I will wait until @njbart weighs in -- he's my go-to for all things biblatex, he knows way more than I do, and I need to consider that the choices I make affect all BBT users, so I need to make sure I don't rush through decisions.

**Comment by juhaszp95** [comment]
Of course! Great -- and thanks again. I guess encapsulating the whole title in the same set of braces solves the issue (as it protects capitalisation and includes hyphens in the same structure, whatever the title is), but I see why you could be awerse to that.
