### ISSUE TITLE
[Bug/Feature]: BibLaTeX omits `urldate` when only `url` is specified in omit list

### ISSUE THREAD

**Issue by paulenit** [retorquere/zotero-better-bibtex#2427]
### Debug log ID

VKI3YM9W-euc

### What happened?

When entering the BibLaTeX field `url` to ignore upon export (entered via Preferences > BetterBibTeX > Export > Fields > Fields to omit from export) the field `urldate` (used e.g. for online citations which have a date when the source was last accessed) is also omitted from the export. The problem is that it is currently not possible to ignore only the `url` field but retain the `urldate` field in an export.

**Steps to reproduce:**

1. Add [mwe.txt](https://github.com/retorquere/zotero-better-bibtex/files/10858495/mwe.txt) to the library. This contains a collection with a single item with both a url and an accessed date.
2. Add `url` to the fields omitted on export (via Preferences > BetterBibTeX > Export > Fields > Fields to omit from export)
3. Export the collection as BetterBibLaTeX
4. Both the `url` and `urldate` field are omitted. My expected behavior is that only the exact field specified is omitted.

**Suggested Improvement:**

IMO only the explicit fields given in the omit list should be omitted and not act as regex-like objects that extend to other fields with starting e.g. with the same prefix.

**Comment by retorquere** [comment]
It doesn't work as a regex.

**Comment by retorquere** [comment]
new build incoming.

**Comment by paulenit** [comment]
> It doesn't work as a regex/prefix. I removed the `urldate` specifically when no URL is present in the output.

I guess that makes sense. I also have to admit, that the use case for omitting the URL on export and keeping the `urldate` might be very niche, and I did end up _not_ omitting the `url` altogether for my project. I was just confused when the access date was missing and the cause was not obvious. So this might just be a me problem or lacking documentation...

**Comment by paulenit** [comment]
[test build 6.7.58.3975](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.58.3975.xpi) removed the undocumented behavior. Thanks for the implementation!
