### ISSUE TITLE
[Bug/Feature]: After the update, the preferences interface displays an error.

### ISSUE THREAD

**Issue by kettly1260** [retorquere/zotero-better-bibtex#2429]
### Debug log ID

W3FXYWSS-apse

### What happened?

After the update, an error occurred in the display of the preferences interface, and the display interface was too long to be fully displayed. After disabling the plugin, the display no longer appears to be a problem

**Comment by juhaszp95** [comment]
I can concur: debug log ID K88ISPWV-euc.

For me it is also sometimes too high, i.e. the top is over the top edge of the screen, and I cannot drag it down. When it's too long and I can't see the bottom, I can't save changed preferences.

**Comment by kettly1260** [comment]
After installing the beta version, the problem still exists

**Comment by retorquere** [comment]
Can you get me a new log from build 3943? I didn't fix anything, I just added logging. I cannot reproduce your problem here, so I need to know what's going on in your installation.

**Comment by kettly1260** [comment]
new log： WSPM3SQN-apse

**Comment by retorquere** [comment]
Did you open the prefs window before sending `WSPM3SQN-apse`? I don't see the error that was present in `W3FXYWSS-apse`.

**Comment by retorquere** [comment]
I have part of the problem reproducible, I'll first see if I can fix that.

**Comment by kettly1260** [comment]
new ID: ILCRBVTW-apse

https://user-images.githubusercontent.com/20242614/222315481-56406bcb-a0e3-4fdc-af8b-323bccd6cfd6.mp4

**Comment by retorquere** [comment]
I'm working on it.

**Comment by retorquere** [comment]
Can you try build 3953?

**Comment by juhaszp95** [comment]
This seems to work for me now!
