### ISSUE TITLE
_eprint in extra causes CSL-JSON export error

### ISSUE THREAD

**Issue by creativixum** [retorquere/zotero-better-bibtex#2430]
### Debug log ID

4NEVT6LT-refs-euc

### What happened?

Hey. I want to export my Zotero library in Better CSL JSON format and keep it updated to access it from note taking tools. After having chosen the folder I want to export to, it sends the message: "An error occurred while trying to export the selected file." What could this be due to? I tried reinstalling Better Bibtex already. 

![grafik](https://user-images.githubusercontent.com/126689444/222170490-a79e8eb0-a08d-4077-9148-b52f0580b7e8.png)

**Comment by retorquere** [comment]
Can't do anything without a debug log.

**Comment by creativixum** [comment]
I am really sorry, then I don't seem to know what a debug log is if it not what I gave. Would you mind to tell me what I need to provide exactly? My programming skills are limited to data analytics in Python :(

**Comment by retorquere** [comment]
If you know any entry that triggers the error when exported, select it, and follow the steps under point 1. above. No programming required, it's just a few clicks in Zotero.

**Comment by davvalent** [comment]
Hi, sorry to interrupt. I ran into this problem today. That was caused by an underscore character `_` at position 0 of a key in the extra field. Example: `_eprint: https://doi.org/10.1080/00182370.2020.1725992`. Underscore removed and problem solved. This field has been populated by the Taylor and Francis+NEJM Zotero translator. Hope this can be useful.

**Comment by retorquere** [comment]
`G4UGH356-refs-euc`

**Comment by retorquere** [comment]
Please try build 3950

**Comment by creativixum** [comment]
> If you know any entry that triggers the error when exported, select it, and follow the steps under point 1. above. No programming required, it's just a few clicks in Zotero.

Hey, thank you! The debug log is: 4NEVT6LT-refs-euc

**Comment by retorquere** [comment]
Thanks; I think build 3950 will fix the problem, can you install that and try the export again?

**Comment by saifelayan** [comment]
I encountered a similar issue where the export process failed for all entries that had an 'Extra' field containing the text "_eprint: ...". I submitted the debug log.

**Comment by retorquere** [comment]
You have to tell me de debug ID, I don't know who submits what. But did you try this with build 3950? Because I think that will fix it.

**Comment by saifelayan** [comment]
Debug log: TMAAZWEX-refs-euc. 
Build 3950 fixes the problem. Thanks

**Comment by retorquere** [comment]
@creativixum ?

**Comment by creativixum** [comment]
> @creativixum ?

Yes, I just installed it, it works now! What did this do?
Thank you so much!

**Comment by retorquere** [comment]
BBT parses fields in the `extra` menu, but these fields used to always have a counterpart as either a CSL variable, or something that was present as a field on another entry type. `_eprint` does not, and I hadn't considered that scenario before.
