### ISSUE TITLE
postscript doesn't work

### ISSUE THREAD

**Issue by MikeChanV8** [retorquere/zotero-better-bibtex#2431]
### Debug log ID

KYVHAGZF-apse

### What happened?

Use post-processing code to move the exported DOI to note filed and then delete the DOI, but it retains its original form in the newset release V6.7.55
Posrscript:
```
if (Translator.BetterTeX) {
  if (tex.has.doi) {
    tex.add({ name: 'note', value: `doi:<a href="https://doi.org/${tex.has.doi.value}">${tex.has.doi.value}</a>`, html: true })
    delete tex.has.doi
  }
}
```
Exported item:
```
@article{abbaszadehSimplifiedModelPredictive2017,
  title = {Simplified Model Predictive Control with Variable Weighting Factor for Current Ripple Reduction},
  author = {Abbaszadeh, Alireza and Khaburi, Davood Arab and Mahmoudi, Hamid and Rodr{\'i}guez, Jos{\'e}},
  year = {2017},
  month = aug,
  journal = {IET Power Electronics},
  volume = {10},
  number = {10},
  pages = {1165--1174},
  issn = {1755-4543, 1755-4543},
  doi = {10.1049/iet-pel.2016.0483},
  langid = {english}
}
```
Expected form:
```
@article{abbaszadehSimplifiedModelPredictive2017,
  title = {Simplified Model Predictive Control with Variable Weighting Factor for Current Ripple Reduction},
  author = {Abbaszadeh, Alireza and Khaburi, Davood Arab and Mahmoudi, Hamid and Rodr{\'i}guez, Jos{\'e}},
  year = {2017},
  month = aug,
  journal = {IET Power Electronics},
  volume = {10},
  number = {10},
  pages = {1165--1174},
  issn = {1755-4543, 1755-4543},
   note = {doi:\href{https://doi.org/10.1049/iet-pel.2016.0483}{10.1049/iet-pel.2016.0483}},
  langid = {english}
}
```

**Comment by retorquere** [comment]
There's no error in `KYVHAGZF-apse`, and for me this postscript seems to work. Can you right-click the Abbaszadeh entry in Zotero, and choose Better-BibTeX -> Debug log? You will get a debug ID with `-refs-` in it.

**Comment by MikeChanV8** [comment]
The debug ID is UZETIIAX-refs-euc.

Fiedls set in Export is 
![image](https://user-images.githubusercontent.com/71354849/222365674-7d848d56-01fd-40dc-a7b1-030c526a40a0.png)
postscript is
![image](https://user-images.githubusercontent.com/71354849/222365907-30ed216f-b630-490c-bc7b-2eb270f62e87.png)

Exported bib item keep doi in it original form instead of note...

**Comment by retorquere** [comment]
For me this just works as-is. Can you change the postscript to

```
Zotero.debug('2431: entering postscript')
if (Translator.BetterTeX) {
  Zotero.debug('2431: TeX postscript')
  if (tex.has.doi) {
    Zotero.debug('2431: has a DOI')
    tex.add({
      name: 'note',
      value: `doi:<a href="https://doi.org/${tex.has.doi.value}">${tex.has.doi.value}</a>`,
      html: true
    })
    delete tex.has.doi
  }
}
```

do an export of the item from `UZETIIAX-refs-euc`, and send a new log?

**Comment by retorquere** [comment]
And if you remove the "Zotero.debug" lines?

**Comment by MikeChanV8** [comment]
After  removing all the three Zotero.debug lines, that is reverting to yesterday's code you prodived in the discussions.
The postscript code works very well.

The debug ID is U5CARGBZ-refs-euc for now

**Comment by retorquere** [comment]
> The postscript code works very well.

Then I don't know what happened, because we didn't really change the postscript. I just reformatted the long line, and in any version of formatting we had, it always worked for me.

**Comment by MikeChanV8** [comment]
I tested using the reformatted and original code. Both are effectively for now.
And the problem cann't be reproduced, even when I rolled back bbt to V6.7.54 and then updated to V6.7.55 again.
Anyway, it works as I expected.
Thanks for your time and efforts. I really appreciate it.
