### ISSUE TITLE
[Bug/Feature]: Synchronisation settings UI does not reflect current settings?

### ISSUE THREAD

**Issue by Prometheos2** [retorquere/zotero-better-bibtex#2434]
### Debug log ID

PP7TLX7A-refs-euc

### What happened?

Hello,

I changed the synchronization settings (both auto export activation and the delay), but the UI shows the default parameters each time I reopen the settings.

The automatic export seems to work, regardless of the option, so it may actually be on the parameter I set.
The delay, however, seems to remain on 2 seconds, despite putting it at 40+ seconds.

I scrubbed the database and deleted all auto-exports, but that did not fix the problem.
I think it started with the previous update (the big window UI one).

**Comment by Prometheos2** [comment]
It seems my post-script does not work either, so it might be because of it

**Comment by retorquere** [comment]
Can you try build 3959

**Comment by Prometheos2** [comment]
It didn't fix the problem

YJV57QKT-refs-euc

**Comment by retorquere** [comment]
The error you had is gone though, so there's that. I can't reproduce the problem however, so can you try the following:

* Open Zotero prefs, tab Advanced -> General -> Config editor -> "I accept the risk"
* Search for `autoExport` in the window that just opened
* Open Zotero prefs, tab Better BibTeX -> Automatic export, and change "Automatic export"

The value of `extensions.zotero.translators.better-bibtex.autoExport` should change along with the setting you choose in the BBT prefs.

**Comment by Prometheos2** [comment]
autoExport is changed and stays changed, however `extensions.zotero.translators.better-bibtex.autoExportDelay` is reset to 2 every time I open the Settings

**Comment by retorquere** [comment]
I have that reproducible.

**Comment by Prometheos2** [comment]
Seems fixed!
Thanks!
