### ISSUE TITLE
[Bug/Feature]: CSL export error

### ISSUE THREAD

**Issue by didiowen** [retorquere/zotero-better-bibtex#2437]
### Debug log ID

XH3YTE9T-apse

### What happened?

![Snipaste_2023-03-08_13-40](https://user-images.githubusercontent.com/115644557/223629030-e80e82d4-9c71-4924-ab94-b85e791fd3e7.jpg)
Cannot export library since March 2nd. The full error message goes as: "TypeError: ef is undefineddoExport@chrome://zotero-better-bibtex/content/worker/zotero.js?version=6.0.22&platform=mac&locale=en-US&clientName=Zotero:137592:15generateCSLJSON@chrome://zotero-better-bibtex/content/worker/zotero.js?version=6.0.22&platform=mac&locale=en-US&clientName=Zotero:137727:5generateCSLJSON@chrome://zotero-better-bibtex/content/worker/zotero.js?version=6.0.22&platform=mac&locale=en-US&clientName=Zotero:165238:7doExport@resource://zotero-better-bibtex/Better%20CSL%20JSON.js:3382:5ctx2.onmessage@chrome://zotero-better-bibtex/content/worker/zotero.js?version=6.0.22&platform=mac&locale=en-US&clientName=Zotero:165471:11"

**Comment by didiowen** [comment]
Hi, 
the correct debug ID is XH3YTE9T-apse, but the issue was mysteriously solved itself...

**Comment by retorquere** [comment]
I think you hit the problem in #2430, and the mysterious solution was that Zotero upgraded to the new release that fixed it.

**Comment by Mela** [comment]
I'm having the same issue. I'll look if that magic Zotero update solution works.

**Comment by retorquere** [comment]
If you go into the addons screen, click the gear and check for updates.

**Comment by retorquere** [comment]
Then I'll need a debug log.

**Comment by Mela** [comment]
On it.

**Comment by Mela** [comment]
*sigh* Okay. Here is what I did.

- Ran into the problem.
- googled the error
- found this github issue
- restarted Zotero
- searched for updates
-- no updates
- tried a BetterBibTex export
- still threw an error
- copied the Zotero version number
- checked this issue
- saw your request for a debug log
- activated the BetterBibTex debug log
- restarted Zotero
- tried better BetterBibTeX export.
- ERROR MAGICALLY GONE
- version number still 6.0.23-beta.3+a1d06066b
*groans*

**Comment by retorquere** [comment]
Transient errors are just fantastic.

Do you know whether there was a particular entry that would throw the error? If so, I'd still like to have a debug log for that, just to make sure. I've tested #2430 on the beta just to be sure but I cannot reproduce the issue.

**Comment by Mela** [comment]
I've sent the debug log via the function via Help -> Send Better BibTex debug log. Is this okay? If it isn't, here the ZIP I've downloaded from that dialogue. 

But since didiowen's problem also went away after activating the debugging option (I guess) maybe this option is doing something different?

**Comment by retorquere** [comment]
If you know what entry triggered it, I'd need a log generated by right clicking the entry, and then better bibtex - send debug log. That will give me a copy of the entry to test with.

**Comment by Mela** [comment]
Sadly, I have no idea what entry the culprit could be.

**Comment by retorquere** [comment]
Ah well.
