### ISSUE TITLE
[Bug]:CAYW failed 

### ISSUE THREAD

**Issue by dreamMilk** [retorquere/zotero-better-bibtex#2439]
### Debug log ID

FA4AFDUC-refs-apse

### What happened?

A CAYW failed error occurred while exporting information

**Comment by retorquere** [comment]
Can you reproduce the error on build 3983 and send a new log?

**Comment by retorquere** [comment]
Can't do anything without a new log.

**Comment by dreamMilk** [comment]
> Can't do anything without a new log. 没有新日志什么也做不了。

Sorry, I almost forgot about it. This is the log ID running on 3983: EVGWV3VX-refs-apse

**Comment by dreamMilk** [comment]
> > Can't do anything without a new log. 没有新日志什么也做不了。
> 
> Sorry, I almost forgot about it. This is the log ID running on 3983: EVGWV3VX-refs-apse

As before, CAYW failed is displayed when citing documents

**Comment by retorquere** [comment]
These builds for now only add logging to find the cause of the problem, I don't know what the problem is yet (I cannot reproduce it locally). Can you get me a new log from build 4002?

**Comment by dreamMilk** [comment]
> These builds for now only add logging to find the cause of the problem, I don't know what the problem is yet (I cannot reproduce it locally). Can you get me a new log from build 4002? 

This is the log ID of version 4002: NSFKDIC8-refs-apse

**Comment by retorquere** [comment]
This just adds more logging -- I can see what call is being issued, but that call succeeds for me.

**Comment by retorquere** [comment]
(assuming you picked `Combined multi-objective optimization...`)

**Comment by dreamMilk** [comment]
> (assuming you picked `Combined multi-objective optimization...`) （假设您选择了组合多目标优化...）

The main process is like this, using Obsidian's Zotero Integration plug-in to import document information, when importing, zotero's own document selection page will pop up, and after selecting confirmation, Bibtex reports an error, and the Obsidian plugin does not receive any information about the document.
I don't know if this will help you pinpoint the cause

**Comment by dreamMilk** [comment]
> (assuming you picked `Combined multi-objective optimization...`)

This problem exists on any literature entry

**Comment by retorquere** [comment]
I will need a new debug log from build 4003.

**Comment by dreamMilk** [comment]
> I will need a new debug log from build 4003.

Debug log ID:UEXDP4YL-refs-euc

**Comment by retorquere** [comment]
Can you try again on the new build, and send a log? It won't work, but I hope to get a more useful error message in the log with it.

Can you try disabling all extensions except bbt and trying again? I haven't been able to reproduce the error, I'd like to rule out or hone in on extension conflicts.

**Comment by dreamMilk** [comment]
> 



> Can you try again on the new build, and send a log? It won't work, but I hope to get a more useful error message in the log with it. 
> 
> Can you try disabling all extensions except bbt and trying again? I haven't been able to reproduce the error, I'd like to rule out or hone in on extension conflicts. 

Following your thinking, I checked all the extensions. The Zotero Citation extension was found to be a source of conflict.

**Comment by dreamMilk** [comment]
> > 
> 
> > Can you try again on the new build, and send a log? It won't work, but I hope to get a more useful error message in the log with it.
> > Can you try disabling all extensions except bbt and trying again? I haven't been able to reproduce the error, I'd like to rule out or hone in on extension conflicts.
> 
> Following your thinking, I checked all the extensions. The Zotero Citation extension was found to be a source of conflict.

Keep only the bbt and Zotero Citation extensions,Debug log ID:B6FQ63NW-refs-apse

**Comment by retorquere** [comment]
Where do I find this Zotero Citation extension?

**Comment by dreamMilk** [comment]
> Where do I find this Zotero Citation extension? 

This is the url of the extension:https://github.com/MuiseDestiny/zotero-citation.
Conflict issues are currently being raised in the extension

**Comment by retorquere** [comment]
I can't help there. Everything is in chinese.

**Comment by retorquere** [comment]
Build 4028 should fix it.

**Comment by dreamMilk** [comment]
I run without problems with build 4029, thanks for your help.👍
