### ISSUE TITLE
Bug: "Download Better BibTeX export ..." broken

### ISSUE THREAD

**Issue by tdltdc** [retorquere/zotero-better-bibtex#2440]
### Debug log ID

QQMH786P-refs-euc

### What happened?

On an entirely fresh install of Zotero and zotero-better-bibtex, right clicking My Library and then clicking "Download Better BibTeX export..." returns the following error in a pop-up:

```
XML Parsing Error: prefix not bound to a namespace
Location: chrome://zotero-better-bibtex/content/ServerURL.xul
Line Number 17, Column 9:        <html:select id="formats" onchange="update();">
--------^
```

**Comment by bjornpijnacker** [comment]
I can confirm this as well

```
XML Parsing Error: prefix not bound to a namespace
Location: chrome://zotero-better-bibtex/content/ServerURL.xul
Line Number 17, Column 9:        <html:select id="formats" onchange="update();">
--------^
```

It's not present in v6.7.57 for me so it seems to be a regression since v6.7.58

**Comment by tdltdc** [comment]
That didn't fix it, but the error message is different this time:

```
XML Parsing Error: mismatched tag. Expected: </html:select>.
Location: chrome://zotero-better-bibtex/content/ServerURL.xul
Line Number 18, Column 53:          <html:option value=".biblatex"/>BibLaTeX</html:option>
----------------------------------------------------^
```

**Comment by retorquere** [comment]
A new release build is running through the test suite.

**Comment by retorquere** [comment]
What are you using to download the feed? Zotero's webserver can no longer be accessed from browsers.

**Comment by tdltdc** [comment]
I see! That works (using `wget`). Thanks for the quick fix!
