### ISSUE TITLE
[Bug]: Journal abbreviation not exported on its own

### ISSUE THREAD

**Issue by juhaszp95** [retorquere/zotero-better-bibtex#2443]
### Debug log ID

HHBCAIRN-refs-euc

### What happened?

Hello,

I've just tried to export an entry in Zotero, which only has the journal abbreviation given, but not the full journal title itself. I've set BBT to use journal abbreviations in its export. Without the full journal tile, it exports the journal abbreviation into the `shortjournal` field in the .bib file (which is not recognised by my style, biblatex-phys), but when I put a random string into the `Publication` field in Zotero, it exports it into the `journaltitle` field, which is what I need (this is debug log ID DPYXXXCR-refs-euc).

I think this might be a bug - if the `Journal Abbr` field of Zotero is not empty, it should probably export into the `journaltitle` field of the .bib file, regardless whether there's a `Publication` given in Zotero or not.

**Comment by retorquere** [comment]
For the first part I agree, but for the 2nd part -- if the `Journal Abb` field of Zotero is filled you want it to *always* be used for the `journal` field, regardless of whether the publication title is present or `use journal abbreviation` is checked? That doesn't seem right?

**Comment by juhaszp95** [comment]
I meant use it always if use journal abbreviation is checked, regardless of what the full journal title is / if it exists in the record.

**Comment by retorquere** [comment]
Isn't that already the current behavior?

**Comment by retorquere** [comment]
> I think this might be a bug - if the Journal Abbr field of Zotero is not empty, it should probably export into the journaltitle field of the .bib file, regardless whether there's a Publication given in Zotero or not.

.... when `use journal abbreviation` is checked, I take it. That is in build 4004.

**Comment by juhaszp95** [comment]
It works now, thanks!
