### ISSUE TITLE
[Bug]: Automatic export of Better BibTeX keeps "Disabled" and can't be changed

### ISSUE THREAD

**Issue by Amendaw** [retorquere/zotero-better-bibtex#2444]
### Debug log ID

JGNMENI2-apse

### What happened?

[Bug]: Automatic export of Better BibTeX keeps "Disabled" and can't be changed. After changing the status to "on Change" and then clicked OK, the setting keeps the same ("Disable") when opening the Preferences Windows again. 

I restarted Zotero, but the problem is still here.

**Comment by retorquere** [comment]
Can you

* go into the [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences)
* look for `translators.better-bibtex.logEvents`
* double-click it to set it to `true`
* try to change the setting to `on Change`
* send a new debug log

**Comment by retorquere** [comment]
I cannot read `D<number>` logs, only BBT logs, which end in `-apse` or `-euc`.

**Comment by Tomaubier** [comment]
Sorry, here it is: `MTJSPH9P-euc`

**Comment by retorquere** [comment]
Can you try whether [this build](https://github.com/retorquere/zotero-better-bibtex/issues/2447#issuecomment-1469735174) fixes the problem for you?

**Comment by Tomaubier** [comment]
Yes it works (for now at least)! Thanks!!
