### ISSUE TITLE
[Bug]: postscript silently ignored

### ISSUE THREAD

**Issue by TomBener** [retorquere/zotero-better-bibtex#2445]
### Debug log ID

89W2SRQA-refs-apse

### Description:

I am experiencing a bug with the code used to delete fields for certain reference types in the BibLaTeX output using postscript in version 6.7.59 of Zotero. Specifically, the following code fails to delete the "url" field for certain reference types, although it worked in the previous version:

```js
if (
  Translator.BetterBibLaTeX &&
  (item.itemType == "book" ||
    item.itemType == "bookSection" ||
    item.itemType == "journalArticle" ||
    item.itemType == "thesis")
) {
  delete this.has.url;
}
```

The expected behavior is that the "url" field should be deleted for the reference types "book", "bookSection", "journalArticle", and "thesis" in the BibLaTeX output using postscript, as it was in the previous version.

### Steps to reproduce:

1.  Create a reference of one of the reference types mentioned above.
2.  Export the reference in BibLaTeX format using postscript.
3.  Check the output for the presence of the "url" field.

Actual result: The "url" field is present in the output, despite the code above.

Expected result: The "url" field should be deleted from the output, as it was in the previous version.

Thanks for your help in fixing this issue.

**Comment by retorquere** [comment]
I don't see export activity in `89W2SRQA-refs-apse`, I see no errors, and this postscript works for me. Can you export one item that exhibits the problem, then right-click that item, and send a new debug log?

**Comment by TomBener** [comment]
The new debug log ID is `BJRQM26B-refs-apse`. Could you see useful information in it?

**Comment by retorquere** [comment]
Can you get me a new log from 4014?

**Comment by retorquere** [comment]
a build will drop here shortly that has some extra logging enabled, but it will unfortunately require a somewhat awkward way of starting Zotero (these instructions are Mac-specific):

*   after installing the build, cmd-quit Zotero
*   open a command line shell (alt-space, "terminal")
*   type `/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/Downloads/2445.txt 2>&1` and press enter
*    export an entry where you expect the error to manifest

after this, there will be a log file in your Downloads folder named 2445.txt. You can mail that to [emiliano.heyns@iris-advies.com](mailto:emiliano.heyns@iris-advies.com).

**Comment by TomBener** [comment]
@retorquere Have sent the log file, please check it.

Thanks for your work!

**Comment by retorquere** [comment]
No error there. Can you disable the cache in the prefs under Export - Misc and send another log this way?

**Comment by TomBener** [comment]
It’s really weird. The error disappeared if I followed your instructions to debug it. However, it has the error from time to time when I generally use Zotero. I’ll try to debug it later.

**Comment by retorquere** [comment]
It would be good to know if the cache is part of the problem, so if you could leave the cache off, we're most likely to reproduce the issue.

**Comment by TomBener** [comment]
It appears that the cache is not the underlying issue, as it is consistently disabled. However, it can be confirmed that exporting functions adequately during Zotero debugging, whereas the complication persists during ordinary usage.

**Comment by retorquere** [comment]
I don't expect disabling the cache to fix it, I expect it to more reliably trigger the error. I suspect that it sometimes the error isn't triggered because the output is fetched from the cache rather than running the code that has the error.

**Comment by retorquere** [comment]
`2445.txt` doesn't show that the postscript is ran at all, that's why I suspected the cache. I'll add more logging. Build 4018 disables the cache everywhere for the time being.

**Comment by retorquere** [comment]
A new build will drop here shortly that adds a ridiculous amount of logging.

**Comment by dlukes** [comment]
I can consistently reproduce the behavior I described in #2448 with the current release of BetterBibTeX, but unfortunately not with build 4019 above. Not once did the postscript fail to run with that build. I'll send the log anyway, but it'll probably be of limited usefulness?

**Comment by retorquere** [comment]
Yeah I need the error to occur. So you can consistently reproduce the problem on 6.7.60? Or 6.7.59?

**Comment by dlukes** [comment]
Sorry, I didn't notice there was a 6.7.60, I followed the link from the documentation website, which still points to 6.7.59. But tried 6.7.60 now and I can consistently reproduce the problem on both 59 and 60 (background export, no cache, no debug output).

**Comment by dlukes** [comment]
Can it be some kind of race condition? And debugging slows things down just enough so that it disappears?

**Comment by retorquere** [comment]
I have no idea yet. I'm not even sure the postscript is reached. It'd be easy to explain if the problem only did occur when debugging is on, because I made changes to how the debug log messages are constructed. But with debug off, that code is just not hit at all.

Can you try versions before 6.7.59?

A new build will drop here that writes the postscript error (if that's what it is) to the output. That is not what you want to stay on, because the output is only usable for diagnosis. But if that captures the error, that would be a huge help. I cannot reliably reproduce the problem.

**Comment by dlukes** [comment]
Here's the output with 4021: [Exported Items.txt](https://github.com/retorquere/zotero-better-bibtex/files/10991837/Exported.Items.txt)

Nothing much there either, I'm afraid... But the problem occurred, the `file` field that the postscript was supposed to add is missing.

**Comment by retorquere** [comment]
That is suuuper strange. The postscript is executing *and finishing*, it's just not having an effect? New build incoming, same procedure please (for CSL export).

**Comment by retorquere** [comment]
I have it reprodicible.

**Comment by retorquere** [comment]
and the fix!

**Comment by retorquere** [comment]
Would appreciate confirmation, would like to get a release out asap.

**Comment by dlukes** [comment]
Confirmed! Thank you very much :tada:

(And sorry for being non-responsive, I was teaching and then rushed home to relieve my wife on duty with the kids.)

**Comment by retorquere** [comment]
No worries man, kids first! I just want to get this out before the next pile-on of issues.

**Comment by TomBener** [comment]
@retorquere Thanks for your work! The latest version works perfectly!

**Comment by the-mann** [comment]
Thanks again @retorquere !!!
