### ISSUE TITLE
[Bug]: url export setting keeps changing to no and does not reflect true value

### ISSUE THREAD

**Issue by zlhaa23** [retorquere/zotero-better-bibtex#2447]
### Debug log ID

69KUN6A4-euc

### What happened?

# Produce bug
(I'll use "url export setting" to refer to the setting found in Settings>BBT>Export>BibTeX)
1. Open settings and set url export setting to "in the note field"
2. Export in format "Better BibTex". The export contains urls in note fields as intended
3. Open settings and check url export setting. _**It shows "no" now**_
4. Export again. It still contains urls in the note fields, as in Step 2
5. I can reproduce the above after restarting Zotero.
6. I have to select another item in the dropdown menu and then change back to "no" (trigger some UI event presumably), to have an export with no urls.

If I understand correctly my debug log contains steps 2-4.

# Comments
Seems like the "underlying setting" is processed as intended. It's just that the Zotero settings window somehow does not reflect the underlying setting, and keeps reverting to some "default value" on the GUI.

This is very similar to https://github.com/retorquere/zotero-better-bibtex/issues/2444. Indeed, I have the same issue with "Automatic export", where the "default value" would be "Disabled". (Although for that I only looked at the settings window and didn't examine if it actually does automatic export)

Overall, it may not affect use, but the fact that the UI doesn't reflect the actual setting is driving me crazy.

**Comment by retorquere** [comment]
Reproducible.

**Comment by retorquere** [comment]
Can you try build 4012?
