### ISSUE TITLE
[Bug]: Japanese date format is not parsed correctly

### ISSUE THREAD

**Issue by ge9** [retorquere/zotero-better-bibtex#2449]
### Debug log ID

WQJ98YTK-apse

### What happened?

Since I use Japanese language in Google Chrome, Zotero Connector sets the "date" value of some items like "7月 1, 2009". 
https://dl.acm.org/doi/10.1145/1538788.1538814 is an example and I submitted the debug output for it.
When I export this item using better bibtex, it sets BibTeX's "year" value as "7月 1, 2009", which should have been "2009".
A similar issue for Chinese was reported in https://github.com/retorquere/zotero-better-bibtex/issues/621 and it seems to have been fixed (so "七月 1, 2009" will be correctly parsed into "2009"), but still Japanese "7月 1, 2009" does not work.

Also refer to twitter reply from Emiliano Heyns(@retorquere): https://twitter.com/retorquere/status/1635403804010237952 and https://twitter.com/retorquere/status/1635404438386130945
### Workaround
Use following postscript:
```
if (tex.has.year) {
tex.add({name: 'year', replace: true, value: tex.has.year.value.replace(/.* /, '')})
}
```
This is essentialy same as one provided in the previous issue but updated to conform to the current version.
Also note that you may have to enable debug output logging and modify postscript to make your script work: https://github.com/retorquere/zotero-better-bibtex/issues/2447

**Comment by retorquere** [comment]
Build 4011 should fix that. If you could confirm, I can roll that into a new release.

**Comment by ge9** [comment]
I confirmed the build 4011 fixed this. thank you.
