### ISSUE TITLE
Citation key formula not generating lowercase for Chinese authors

### ISSUE THREAD

**Issue by TomBener** [retorquere/zotero-better-bibtex#2450]
### Debug log ID

ISJLK9NE-refs-apse

### What happened?

I encountered a bug in the citation key formula of Better BibTeX for Zotero. Specifically, when using the formula `auth.lower+year`, the generated citation key is not in lowercase for Chinese authors.

For example, I have an item with the author `作者` and the year `2023`. According to the citation key formula, the expected key should be `zuozhe2023`. However, the actual key generated is `ZuoZhe2023`, which is not in lowercase as expected.

### Steps to reproduce:

1.  Set the citation key formula as `auth.lower+year`.
2.  Add an item with a Chinese author and a year.
3.  Check the generated citation key.

Expected result: The generated citation key should be in lowercase for all authors, regardless of their language.

Actual result: The generated citation key is not in lowercase for Chinese authors.

Please let me know if you need any additional information or clarification on this issue. Thank you for your help in resolving this bug.

**Comment by retorquere** [comment]
try `auth.transliterate.lower+year`. Without `.transliterate`, the key manager will try to lowercase `作者`, and javascript toLowerCase() doesn't know how to do that.

**Comment by TomBener** [comment]
@retorquere Thanks, It works!
