### ISSUE TITLE
[Feature]: export journal and abbr at the same time

### ISSUE THREAD

**Issue by fangzhou-xie** [retorquere/zotero-better-bibtex#2451]
### Debug log ID

3UWSFBTF-refs-euc

### What happened?

Hi, thank you very much for this wonderful plugin!

I was trying to write a simple postscript to export both "Journal" and "Journal Abbr" into bibtex, but couldn't make it work. I know there is an option in the setting to export "shortjournal" as "journal", but I wanted to export both at the same time.

As an example (using the entry I generated by the debug log) I would like to have the following fields in the resulting bibentry:

```
journal = {Statistical Papers},
abbr = {Stat Papers}
```

This is the following postscript I am currently trying (but not working):

```
if (Translator.BetterBibTeX) {
  tex.add({name: "abbr", value: zotero.abbr});
}
```

I would appreciate any help. Thanks!

**Comment by fangzhou-xie** [comment]
I am not sure if this is related to issue #2445 and #2448 , but it seems working to me after using the following postscript:

```
if (Translator.BetterBibTeX) {
  Zotero.log('2431')
  Zotero.log(zotero.journalAbbreviation)
  tex.add({name: "abbr", value: zotero.journalAbbreviation});
}
```

Without the two logging lines, it didn't work for me whether I enable/disable debug logging or checking/unchecking background export. With these two "Zotero.log" lines, it works with debug logging disabled and background export enabled.

I am not sure why this is the case though.

**Comment by retorquere** [comment]
Please join issue #2445. These are likely all related.

**Comment by fangzhou-xie** [comment]
Sure. I'll close this issue then.

**Comment by retorquere** [comment]
My bad, you did in fact find the right solution. `zotero.journalAbbreviation` is indeed the journal abbrev, `zotero.journalAbbreviation || zotero.autoJournalAbbreviation` if you use automatic journal abbrev as a fallback.

**Comment by fangzhou-xie** [comment]
Thanks for your feedback! However, I tried a couple more times with this postscript, it seems that it only works by disabling "background output". Is this the part that linked to issue #2445 ?

**Comment by retorquere** [comment]
Yes, that is #2445
