### ISSUE TITLE
[Bug/Feature]: RTF Output

### ISSUE THREAD

**Issue by themillerfamily** [retorquere/zotero-better-bibtex#2453]
### Debug log ID

RZYNE2FM-refs-euc

### What happened?

For those of us using Scrivener, another option is to use the RTF Scan, and it would be great to output tags to scan using Zotero's RTF Scan feature. The output format is generally `{Author, "Title", Date [, reference]}`. I can't figure out a way to create this output. While I can tell CAYW to output in `format=formatted-citation`, this generally outputs in the format `(Author, Date [, reference])`. Is there a way to create my own output format in this way or does this require something further? I also found that I cannot use the JSON output, as the Title is not included in this output.

Thanks for creating such a great tool!

**Comment by retorquere** [comment]
The [rtf-scan docs](https://www.zotero.org/support/rtf_scan) are unclear about:

* whether you can have a title *and* a locator
* how to specify a locator other than (I assume) "page"
* when and how it is determined one should use "et al"

If you can find out those things, I could add it to BBTs CAYW.

**Comment by retorquere** [comment]
A new build will drop here shortly that enriches the `json` format, although in my tests, the existing `json` format does have the title.

> The output format is generally {Author, "Title", Date [, reference]}

In what sense "generally"? Not always? Do you know what should happen if any of these parts are missing in the entry? Are there quotation rules for the title, and is the date just the year or the full date?

Curious minds want to know :)

**Comment by retorquere** [comment]
I have not received new information here or from the [developer forums](https://groups.google.com/g/zotero-dev/c/2y05hexLhIc/m/PTS6bgbZAAAJ). I will have to close this issue for inactivity. If you find new information and comment here, the issue will automatically reopen.
