### ISSUE TITLE
Bug: {\relax} in author also removes trailing dot '.'

### ISSUE THREAD

**Issue by paultjevdh** [retorquere/zotero-better-bibtex#2454]
### Debug log ID

H8XPZRD8-refs-euc

### What happened?

I noticed that the auto-export of better bibtex now uses {\relax} around authors with two-letter initials. This also introduces the following bug:
Author A. Th. A. M. de Waele was previously compiled to 
  author = {{de Waele}, A. Th. A. M. and {de Bruyn Ouboter}, R.},
With the current version it has become
  author = {{de Waele}, {\relax A. Th. A. M} and {de Bruyn Ouboter}, R.},
Not only has {\relax} been added, also 'M.'  has changed to 'M'  

This may have been introduced by the fix for #2419.

**Comment by retorquere** [comment]
This renders correctly for me though:

```latex
\documentclass[a4paper, 12pt]{article}

\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@article{de_waele_quantum-interference_1969,
  title = {Quantum-Interference Phenomena in Point Contacts between Two Superconductors},
  author = {{de Waele}, {\relax A. Th. A. M} and {de Bruyn Ouboter}, R.},
  year = {1969},
  month = feb,
  journal = {Physica},
  volume = {41},
  number = {2},
  pages = {225--254},
  doi = {10.1016/0031-8914(69)90116-5}
}
\end{filecontents*}

\begin{document}
\title{Autumn Term Report}
\author{myself}
\date{\today}
\maketitle

HI \nocite{*}

\textquotedbl{}x\textquotedbl

\bibliographystyle{apalike}
\bibliography{\jobname}
\end{document}
```

**Comment by retorquere** [comment]
Do you have an MWE where it doesn't?

**Comment by retorquere** [comment]
I think I have a workaround. Coming up.

**Comment by retorquere** [comment]
Can you try build 4052?

**Comment by paultjevdh** [comment]
Hi,
Your MWE renders correctly for me too, that's quite magical!

I also tested build 4052, which solves the issue.
Thanks

**Comment by retorquere** [comment]
> Hi, Your MWE renders correctly for me too, that's quite magical!

BibTeX is pretty convoluted, and a large portion of its behaviors is not documented.

> I also tested build 4052, which solves the issue. Thanks

I think 4052 is the preferable solution, so I'm going to roll that out.
