### ISSUE TITLE
[Feature]: Export date including day for newspaper or blog articles

### ISSUE THREAD

**Issue by Seitzal** [retorquere/zotero-better-bibtex#2461]
### Debug log ID

TS2CYM8J-refs-euc

### What happened?

When exporting to BibTeX (.bib), I expected newspaper and blog articles to be exported with a `date` field like `date = {2014-07-28}`. Instead, Zotero only exported the year and month:
```
  ...
  year = {2014},
  month = jul,
  ...
```
Since most citation guidelines I've encountered advise specifying the precise date of publication when referencing news articles, I think it would be good if the export allowed this (especially since the citation style can still decide to only include year and/or month for some types of publication). After manually inserting the field into the .bib file, BibTeX processed it correctly and generated the reference I wanted, but I don't want to go back and insert date fields manually for all of those references, only to have them overwritten by automatic export later.

**Comment by retorquere** [comment]
Export as biblatex rather than bibtex. Biblatex supports full dates, bibtex does not.
