### ISSUE TITLE
missing \ before _ in url in .bib file

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#2466]
### Discussed in https://github.com/retorquere/zotero-better-bibtex/discussions/2464

<div type='discussions-op-text'>

<sup>Originally posted by **DS-Rodrigues** March 27, 2023</sup>
Hi 

I am using Better BibTeX to get my references from Zotero to LaTeX (I use TeXShop). I have just downloaded the latest version of Better BibTeX (v6.7.62)

However, I get a list of errors in LaTeX because in the url field in .bib file the _ are missing the \ before.

In Zotero (Preferences) I selected Add URLs to BibTeX export in the 'url' field and in my main.tex I included `\usepackage{url}`.

Am I doing something wrong? Could you please advise?

Thanks,
Daniela</div>

Debug log ID: 3TNML7DH-refs-euc

**Comment by retorquere** [comment]
@DS-Rodrigues let's continue here.

**Comment by DS-Rodrigues** [comment]
Hi thanks for your help with this. I thought I had shared with you the log (Debug log ID: 3TNML7DH-refs-euc), didn't you receive it?

**Comment by retorquere** [comment]
I did, but you posted a second entry that was not included in the debug log:

```bibtex
@incollection{worldhealthorganizationResolutionWHA72Primary2019,
  title = {Resolution {{WHA72}}.2: {{Primary}} Health Care},
  booktitle = {Seventy-Second {{World Health Assembly}}},
  author = {{World Health Organization}},
  year = {2019},
  publisher = {{World Health Organization}},
  address = {{Geneva}},
  url = {https://apps.who.int/gb/ebwha/pdf\_files/WHA72/A72\_R2-en.pdf},
  langid = {english}
}
```

**Comment by retorquere** [comment]
Ah OK. So build 4075 repairs the quoting bug, but you have urls set to export to an url field, and that is verbatim mode. You can have it export as non-verbatim by choosing the option `in the 'url' field, but assuming the 'url' package is not loaded` (in build 4075, which I intend to release tonight).

**Comment by DS-Rodrigues** [comment]
Just to add that I do shit+command+L in TeXShop, then shit+command+B to run .bib file and then I get the error when I do shit+command+L after running bibliography.

**Comment by retorquere** [comment]
> Just to add that I do shit+command+L in TeXShop, then shit+command+B to run .bib file

LaTeX can be a cantankerous beast, but I take it that is a typo 🤣 

> Goto error I get directed to the thesis.bbl and this is highlighed:

The problem is bibtex doesn't support URLs. There are various workarounds to make them work, loading the `url` package used to do it for me, and the "in the 'url' field, but assuming the 'url' package is not loaded" is another workaround.

If at all possible, I'd advice to go with biblatex instead of bibtex, but if you are bound to bibtex, "in the 'url' field, but assuming the 'url' package is not loaded" is your best bet.

**Comment by DS-Rodrigues** [comment]
Haha but I did mean TeXShop (https://pages.uoregon.edu/koch/texshop/)

I don't actually know if I can use biblatex..

I tried the "in the 'url' field, but assuming the 'url' package is not loaded" but I got the same error. I guess I will have to install the new release, right?

**Comment by DS-Rodrigues** [comment]
Oh 🤣 I am sorry , of course I meant shift

**Comment by DS-Rodrigues** [comment]
Sorry but just to confirm - do I need to download and install Better BibTeX? I have just tried now with the "in the 'url' field, but assuming the 'url' package is not loaded" option but I am getting the same exact error. I removed url package from LaTeX, not sure if that is needed. I also tried it without sending URLs in .bib file and worked, but I do need the URLs.. I also tried biblatex and it does not work for me unfortunately.

**Comment by retorquere** [comment]
You can upgrade from the addin menu under tools.

**Comment by retorquere** [comment]
The new release is out

**Comment by DS-Rodrigues** [comment]
I've just updated it and all is working now- thanks very much!
