### ISSUE TITLE
[Feature]: Button to "reset" the pinned key, so you don't need to "unpin", then re-"pin" it

### ISSUE THREAD

**Issue by ReaderGuy42** [retorquere/zotero-better-bibtex#2468]
### Debug log ID

PG44T9ZB-refs-euc

### What happened?

Feature Request: When changing something in the metadata, e.g. the author's name, sometimes the citekey is then no longer correct, e.g. if Zotero/BBT interprets a file as the whole book but you're just referring to a chapter or something of that sort. 

I love that I can pin citekeys, but in this case it would no longer be correct, so I have to unpin and repin the key for it to make sense. 

This is not that important or top priority, but maybe at some point you could look into adding a "reset" button to go under the "unpin" one that does this? 

No big deal if not.

Thanks :)

**Comment by retorquere** [comment]
In this release you can edit the citekey; if you clear it, it will be unpinned and generated fresh. If you couple that with [automatic pinning](https://retorque.re/zotero-better-bibtex/installation/preferences/#automatically-pin-citation-key-after) you have what you want.

**Comment by ReaderGuy42** [comment]
Ah, great, thank you, I'll look into that :)
