### ISSUE TITLE
[Bug/Feature]: series = {无}

### ISSUE THREAD

**Issue by holderhe** [retorquere/zotero-better-bibtex#2469]
### Debug log ID

Z2YN9NC6-refs-apse

### What happened?

Apologies. I am not sure this is a bug or i am not setting it right. 
The bib file exported is with `series = {无}` (which is in chinese while others in english) in all references. i am supposing this should be `series = {Null}` or` series = {}`. could you show me the right way to set it as this please.

**Comment by holderhe** [comment]
Thank you for clarifying this. but i see series of these references are all empty, so i expect that output should be like this `series = {}`. if i want export series of these references like `series = {}`, what should i do?

**Comment by zepinglee** [comment]
This should be a bug from the Zotero translators. I don't see any reason to fill this field with "Null/无" rather than leaving it empty. @holderhe What is the URL of this entry? I suggest cleaning them up manually or with JavaScript code.

**Comment by holderhe** [comment]
see my another question #2470 , there is an example of this translator problem. i am expecting this should be leaving empty rather than fill with any stuff. 
BTW, i am curious about why this is translated for me since i don't ask for and why only this `series` field?

**Comment by holderhe** [comment]
> see my another question #2470 , there is an example of this translator problem. i am expecting this should be leaving empty rather than fill with any stuff. BTW, i am curious about why this is translated for me since i don't ask for and why only this `series` field?

@retorquere sorry, above is reply to @zepinglee .
i am thinking this issue maybe be caused by the Zotero translators as @zepinglee said, so sorry for that this isn't BBT related perhaps. i am asking for a workaound to resolve this. 
but this is still a bit confusing why when these refference previewed in Zotero series are empty but export with `series = {无}` in bib. should BBT just ignore it and not export seires to bib when series is empty?

**Comment by retorquere** [comment]
It isn't empty:

![image](https://user-images.githubusercontent.com/132108/228497515-18b23c80-5ccc-45cc-929a-01532736be02.png)

**Comment by holderhe** [comment]
yes, you are right. this field maybe empty when import in but changed to current situation by some add-ons. sadly i don't how to rule out the one caused this.

**Comment by retorquere** [comment]
You rule it out as in you are sure that Zotero Update IFs **does not** cause it, and that there must be some other cause?

Can we agree that if you empty those fields, the problem goes away, and that this is not a BBT issue?

**Comment by holderhe** [comment]
sorry for my poor language, i mean i rule out all my add-ons one by one, finally find Zotero Update IFs does cause it. this is not a BBT realted issue. Though this problem holds on but i think i should turn to Zotero Update IFs and ask help.
Thank you for this much effort help me out.

**Comment by holderhe** [comment]
one more thought, this Zotero Update IFs add-on custom adding these `series title` and `series text` fields, should them not affect BBT while BBT could ignore them and only take `series` into export?

**Comment by retorquere** [comment]
> one more thought, this Zotero Update IFs add-on custom adding these `series title` and `series text` fields, should them not affect BBT while BBT could ignore them and only take `series` into export?

`series` is a valid Zotero field (not on all item types, but on a few), and `series` is a valid field for `@article`. If it weren't, I already wouldn't be using it, so I don't want to remove this. `Zotero IFs` is apparently also adding that field to the items presented to the export translators, which is something they must be actively doing, so you could also ask them to stop doing that. I can't see whether it was Zotero or a plugin that put the field there.

But why not just clear the field? That would solve the issue, yes?

**Comment by retorquere** [comment]
BTW the screenshot I posted is without IFs installed. That data is just simply in the zotero entry. So you must either clear it manually, or have IFs modified to no longer put `none` there. As said, I can't distinguish how data got into the entry, you could have typed it there and there would be literally no way for me to tell. So there's no other option than to clear the data out of that field.

**Comment by retorquere** [comment]
Can you confirm clearing out the field solves the issue? I really don't see how this is a BBT problem.

**Comment by holderhe** [comment]
> Can you confirm clearing out the field solves the issue? I really don't see how this is a BBT problem.
yes, i clear out the field and the problem solved. This is not  a BBT problem.


> > one more thought, this Zotero Update IFs add-on custom adding these `series title` and `series text` fields, should them not affect BBT while BBT could ignore them and only take `series` into export?
> 
> `series` (which is how it's offered to the translator) is a valid Zotero field (not on all item types, but on a few), and `series` is a valid field for `@article`. If it weren't, I already wouldn't be using it, so I don't want to remove this. `Zotero IFs` is apparently also adding that field to the items presented to the export translators, which is something they must be actively doing, so you could also ask them to stop doing that. I can't see whether it was Zotero or a plugin that put the field there.
> 
> But why not just clear the field? That would solve the issue, yes?

as for this conversation, i mean `series` in my situation are actually empty (at least seen in info) but series title and text are not (see the screenshot you posted), so i am expecting BBT would only export with series but not series title and text so my problem can be solved.
BTW, there are indeed some confusion between `series` and `series title` which discussed in some place like ["series" vs "series title"](https://forums.zotero.org/discussion/18322/?Focus=126054#Comment_126054).

**Comment by retorquere** [comment]
Please try build 4086.

**Comment by holderhe** [comment]
Problem solved. Thank you!
