### ISSUE TITLE
authors' name are divided into parts

### ISSUE THREAD

**Issue by holderhe** [retorquere/zotero-better-bibtex#2470]
### Debug log ID

MW4YMJ9L-refs-apse

### What happened?

```
@article{rehman2019multivariate,
  title = {Multivariate Variational Mode Decomposition},
  author = {family=Rehman, given=Naveed, prefix=ur, useprefix=false and Aftab, Hania},
  series = {无},
  volume = {67},
  number = {23},
  pages = {6039--6052},
  issn = {1941-0476},
  doi = {10.1109/TSP.2019.2951223},
  booktitle = {IEEE Transactions on Signal Processing},
  year = {2019-12},
  journal = {IEEE Transactions on Signal Processing}
}
```
see this example, the authors' name are are divided into family and given names, etc. is this the supposing behavior? what should i do to turn this into normal style? Thank you in advance.

**Comment by retorquere** [comment]
Yes, this is the correct behavior. Is this not rendering as you expect?

You can turn extended name format off here:
![image](https://user-images.githubusercontent.com/132108/228444961-7bea7a64-b048-497b-aa5f-54f0e320392d.png)
but I really don't see what the benefit would be of turning that off unless you are on a very old biblatex (older than 3.5).

**Comment by holderhe** [comment]
sorry, i feel not right baccause i am not export biblatex but bibtex instead, and this is the one reference showed in this way while i am keeping get warnings. is there any other setting i am do it wrong that cause this inconsistency?

**Comment by retorquere** [comment]
If you export as Better BibTeX, you get 

```
author = {ur Rehman, Naveed and Aftab, Hania},
```

You are exporting as Better BibLaTeX, and trying to make BibTeX of it through your postscript.
