### ISSUE TITLE
Feature: 'type: dataset' export bib without url

### ISSUE THREAD

**Issue by holderhe** [retorquere/zotero-better-bibtex#2471]
### Debug log ID

UECSSUYL-refs-apse

### What happened?

when set reference type as dataset (adding `type: dataset` in `extra`), the export bib is missing `url `or saying `howpublished`.

**Comment by retorquere** [comment]
Are you exporting as bibtex or biblatex? bibtex doesn't have a `dataset` entry type, but biblatex does, and that exports as

```bibtex
@dataset{worldbank2017pakistan,
  title = {Pakistan - Solar Radiation Measurement Data},
  author = {{World Bank}},
  date = {2017},
  url = {https://energydata.info/dataset/pakistan-solar-radiation-measurement-data},
  urldate = {2023-03-30},
  organization = {World Bank via ENERGYDATA.info, under a project funded by the Energy Sector Management Assistance Program (ESMAP)}
}
```

**Comment by holderhe** [comment]
Thank you for clarifying this. i wasn't aware that bibtex doesn't have a `dataset` entry type. 
Problem solved. thank you for instant reply.
