### ISSUE TITLE
Bug: cannot add insert/update auto exports

### ISSUE THREAD

**Issue by ledzeg** [retorquere/zotero-better-bibtex#2477]
### Debug log ID

G6HMB3NA-euc

### What happened?

Hi, the error message `Better BibTeX: error inserting autoexport, restart to repair` (see figure) appears when I try to export a library, checking the boxes `Export Notes` and `Keep updated`. I downloaded the latest version 6.7.69 and installed it, but the error persists. My bug log ID is **`G6HMB3NA-euc`**. Despite I follow the instructions given [here](https://github.com/retorquere/zotero-better-bibtex/issues/1958#issuecomment-943270558) to send the bug log, I included it here in the `debug.txt` file. I also sent the Debug Output identified with **`D767054594`**.

After I sent the Debug Output, I decided to read the last part of it and found some errors, I think indicating that I must have included the property `Normalize` (lines 174592, 174599), but after checking this box and trying to export the library again, the error persists. 

[debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/11183476/debug.txt)
![image](https://user-images.githubusercontent.com/107968926/230726087-9f84702a-212f-4294-a551-3690182fb508.png)

**Comment by air910305** [comment]
i just Install  test build 6.7.69.4117 and it works perfectly， thanks a lot！

**Comment by ledzeg** [comment]
I also installed [test build 6.7.69.4117](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.69.4117.xpi) and the error disappeared. Thank you @retorquere!

**Comment by retorquere** [comment]
New release build is running, it's just a rebadged 4117, you will be upgraded automatically regardless.
