### ISSUE TITLE
edition as numeric cardinal instead of English ordinal

### ISSUE THREAD

**Issue by jsdodge** [retorquere/zotero-better-bibtex#2480]
### Debug log ID

DBZGVIHH-refs-euc

### What happened?

In Zotero the "Edition" field is set to "7", which is automatically converted to "Seventh" in the bib-file. The publisher house style uses "7th", however, and as noted in this [discussion](https://github.com/retorquere/zotero-better-bibtex/discussions/2416#discussioncomment-5114619), it would be helpful to have the ability to export the edition number for publications in languages other than English.

```
@book{born1999,
  title = {{Principles of Optics: Electromagnetic Theory of Propagation, Interference and Diffraction of Light}},
  author = {Born, M. and Wolf, E. and Bhatia, A. B. and Clemmow, P. C. and Gabor, D. and Stokes, A. R. and Taylor, A. M. and Wayman, P. A. and Wilcock, W. L.},
  year = {1999},
  edition = {Seventh},
  publisher = {Cambridge University Press},
  address = {Cambridge; New York},
  doi = {10.1017/CBO9781139644181}
}
```

**Comment by retorquere** [comment]
I think I'll just revert to the old behavior. Biblatex exports don't do this translation to English text btw, and if you have multilanguage bibliographies you'll be much better of with biblatex of you can use it for other reasons too.

**Comment by jsdodge** [comment]
Thanks. Unfortunately biblatex is not an option for me: it's incompatible with RevTeX, which is one of the standard packages used in physics.

**Comment by retorquere** [comment]
Still, what do you make of [this](https://mirror.lyrahosting.com/CTAN/biblio/bibtex/base/btxdoc.pdf):

> **edition** The edition of a book—for example, “Second”. This should be an ordinal, and should have the first letter capitalized, as shown here; the standard styles convert to lower case when necessary.

`7` is not an ordinal, it is a cardinal.

**Comment by jsdodge** [comment]
The Chicago Manual of Style recommends (14.113),

“When an edition other than the first is used or cited, the number or description of the edition follows the title in the listing. An edition number usually appears on the title page and is repeated, along with the date of the edition, on the copyright page. Such wording as Second Edition, Revised and Enlarged is abbreviated in notes and bibliographies simply as 2nd ed.; Revised Edition (with no number) is abbreviated as rev. ed. Other terms are similarly abbreviated.”

House styles will vary (as will the publication language), so it would be best to have some flexibility.

**Comment by retorquere** [comment]
I understand style demands can vary this way, it's precisely because of this that I want to know how bibtex and revtex go about meeting these various demands of different styles. The idea behind bibtex/biblatex is that they have a sort-of-universal generic format that they can translate in concert with the style files to the style-correct output. bibtex for its part seems to have settled on "always an ordinal" for edition, biblatex on a cardinal. 

I have reached out to revtex and put you in BCC to see what their expectation is in relation to the bibtex expectations. If need be I'll add a new preference, but before I do that I need to hear from them. Or is revtex its own processor, separate from bibtex, that just uses a format that looks like  bibtex?

If you need an immediate solution, a postscript could tide you over:

**Comment by retorquere** [comment]
It doesn't seem like they're going to get back to us.

**Comment by retorquere** [comment]
If they get back to you, you can comment here and the issue will automatically reopen.

**Comment by jsdodge** [comment]
I haven't heard back from the folks at the American Physical Society, but their [example file](http://mirrors.ctan.org/macros/latex/contrib/revtex/sample/aps/apssamp.pdf) includes multiple references that list the edition number in the abbreviated form that *The Chicago Manual of Style* recommends: Refs. [3], [8], [9], [32], and [42]. I'm including a couple of screenshots below. The [Physical Review Style and Notation Guide](https://journals.aps.org/files/styleguide-pr.pdf) does not give an example of a book reference that includes an edition number, but the available evidence indicates that Physical Review prefers the abbreviated form in references.

Regarding the reference that you [cited above](https://github.com/retorquere/zotero-better-bibtex/issues/2480#issuecomment-1501731626), *both* "Second" and "2nd" are [ordinal numerals](https://en.wikipedia.org/wiki/Ordinal_numeral). I can't remember if I wrote the title for this issue, but the issue is not whether to represent the edition as a cardinal number or as an ordinal number, but whether the ordinal edition number should be abbreviated.

<img width="886" alt="Screen Shot 2023-04-27 at 7 07 51 PM" src="https://user-images.githubusercontent.com/4602669/235037207-461d548b-df50-4678-b63f-9cb658a373c4.png">

<img width="900" alt="Screen Shot 2023-04-27 at 7 09 54 PM" src="https://user-images.githubusercontent.com/4602669/235037498-d3614bc3-201e-4ab0-a389-552edf027b8d.png">

**Comment by retorquere** [comment]
I've moved the ordinal-iazation to a preference so it can be turned on (off by default)
