### ISSUE TITLE
Better BibTeX Initializing stuck at Loading citation keys

### ISSUE THREAD

**Issue by Aisha1022** [retorquere/zotero-better-bibtex#2482]
### Debug log ID

IKQNXBET-euc

### What happened?

I tried to open Zotero today and there is a pop-up stuck on 'Better BibText: Initializing' and none of the citation keys will load. I'm running the latest version of BBT. Thank you very much in advance for your help!

**Comment by retorquere** [comment]
Can you get me a new log from build 4125?

**Comment by Aisha1022** [comment]
I just submitted a new debug log - log ID W8UHAMAN-euc

Thank you!

**Comment by retorquere** [comment]
Our messages crossed -- I need a log from 4126, sorry.

**Comment by Aisha1022** [comment]
No worries, just downloaded 4126 and sent a new debug log - log id 9R4JWZNQ-euc

Please let me know if you need anything else from me, thanks!

**Comment by retorquere** [comment]
Can you send a log and check the `include cache` checkbox before sending?

**Comment by Aisha1022** [comment]
Hi, sorry for the delay. Just sent a log and checked include cache. Debug log ID: 86PPU3SP-euc

**Comment by retorquere** [comment]
please install 4158, choose "restart with debug logging" from the help menu, and send a new log.

**Comment by Aisha1022** [comment]
Hi, I just installed 4158 and sent a new debug log - log ID: TWM32XS5-apse
Thank you!

**Comment by retorquere** [comment]
I need a new log from 4166.

**Comment by Aisha1022** [comment]
Hello. new log submitted from 4166. debug log ID: DQLMEC7B-euc
Thanks!

**Comment by Aisha1022** [comment]
Hi, great news, the issue has been fixed and BetterBibTex and the citation keys are now loading fine. Thanks so much for all your help, I really appreciate it!
