### ISSUE TITLE
[Bug]: arXiv categories missing in the BibTeX output when stored only in the Extra field

### ISSUE THREAD

**Issue by aywi** [retorquere/zotero-better-bibtex#2483]
### Debug log ID

DKRCS6I6-refs-apse

### What happened?

The old behavior of Zotero was to save arXiv papers as journal articles and store categories in the Journal field. Now Zotero has changed to save arXiv papers as preprints and only save categories in the Extra field.

I have tried three combinations and found that categories are missing in the BibTeX output when stored only in the Extra field. I guess the underlying implementations for reading arXiv information from Journal vs. Extra are different?

**Comment by aywi** [comment]
The current BBT output is:
```bib
@misc{Ramaswamy2022ELUDEGeneratingInterpretable,
  title = {{{ELUDE}}: {{Generating}} Interpretable Explanations via a Decomposition into Labelled and Unlabelled Features},
  shorttitle = {{{ELUDE}}},
  author = {Ramaswamy, Vikram V. and Kim, Sunnie S. Y. and Meister, Nicole and Fong, Ruth and Russakovsky, Olga},
  year = {2022},
  month = jun,
  number = {arXiv:2206.07690},
  eprint = {arXiv:2206.07690},
  publisher = {{arXiv}},
  doi = {10.48550/arXiv.2206.07690},
  urldate = {2023-04-11},
  archiveprefix = {arxiv}
}
```
What I expected is (has `arXiv:2206.07690 [cs]` in the Extra field):
```bib
@misc{Ramaswamy2022ELUDEGeneratingInterpretable,
  title = {{{ELUDE}}: {{Generating}} Interpretable Explanations via a Decomposition into Labelled and Unlabelled Features},
  shorttitle = {{{ELUDE}}},
  author = {Ramaswamy, Vikram V. and Kim, Sunnie S. Y. and Meister, Nicole and Fong, Ruth and Russakovsky, Olga},
  year = {2022},
  month = jun,
  number = {arXiv:2206.07690},
  eprint = {arXiv:2206.07690},
  primaryclass = {cs},
  publisher = {{arXiv}},
  doi = {10.48550/arXiv.2206.07690},
  urldate = {2023-04-11},
  archiveprefix = {arxiv}
}
```
I have tried to access the category via `zotero.arXiv.category` but what I get is `undefined`.

This is a sample output of previously saved arXiv papers (when Zotero still saved them as journal articles):
```bib
@article{Jin2021EUCAPracticalPrototyping,
  title = {{{EUCA}}: A Practical Prototyping Framework towards End-User-Centered Explainable Artificial Intelligence},
  shorttitle = {{{EUCA}}},
  author = {Jin, Weina and Fan, Jianyu and Gromala, Diane and Pasquier, Philippe and Hamarneh, Ghassan},
  year = {2021},
  month = feb,
  journal = {arXiv:2102.02437 [cs]},
  eprint = {2102.02437},
  primaryclass = {cs},
  url = {https://arxiv.org/abs/2102.02437},
  archiveprefix = {arxiv},
  langid = {english}
}
```
PS: The categories can be multiple, e.g. `arXiv:2004.10282 [cs, eess, q-bio]`.

**Comment by retorquere** [comment]
> Thanks, it looks good! Somehow you also changed the eprint in the BibTeX output of the preprint (stripping out the arXiv: head) to make it the same as the previously saved journal article form.

This brings it in line with the other ways BBT shows arXiv IDs in the output. That I didn't do it here was an oversight. The `eprinttype`/`archiveprefix` tells you what type the identifier in `eprint` is.
