### ISSUE TITLE
Bug: dataset unsupported in itemToCSLJSON in Zotero beta

### ISSUE THREAD

**Issue by Mela** [retorquere/zotero-better-bibtex#2485]
### Debug log ID

49P3YIFF-euc

### What happened?

My BetterBibTeX export fails again. This time the error message is: 

`Unexpected Zotero Item type "dataset"itemToCSLJSON`

I googled and found this:
https://forums.zotero.org/discussion/104104/saved-online-with-no-account-database-corrupt

There were two new item types introduced about ten days ago and that's about the time when the export ran successfully for the last time. 

Thus maybe my problem is caused by the new item types? 

Regards,
Mela

**Comment by retorquere** [comment]
Does it work if you export without checking "background export"?

**Comment by Mela** [comment]
I'm using the automatic export. Need to look where I even find that option.

**Comment by Mela** [comment]
Found it. 
Yes, export worked when "Background export" was unchecked.

**Comment by retorquere** [comment]
Can you verify that it works?

**Comment by Mela** [comment]
Export finished without errors. 

![Bildschirmfoto 2023-04-13 um 17 03 25](https://user-images.githubusercontent.com/361364/231803081-b9178a23-33a2-4f6d-a7d2-88e3a6abbc8b.png)
