### ISSUE TITLE
[Feature]: Keep original citation keys

### ISSUE THREAD

**Issue by bernb** [retorquere/zotero-better-bibtex#2486]
### Debug log ID

F87GDDSN-refs-euc

### What happened?

I have just switched to Better BibTeX for the automatic export feature, which works great. I already have 5 pages of citations used on 70 pages and I really do not want to change all citation keys in the text. I do not care about the citation key format as my IDE (IntelliJ with TeXiFy) will find the correct citation key as I type parts of the title. It also warns if duplicate citation keys are used.
I would prefer to use Better BibTeX but keep the original citation keys when exporting.

**Comment by bernb** [comment]
I want to keep the citation keys used by Zotero when not using Better Bibtex. For the entry used for the debug log this was `cignoni_meshlab_nodate` without Better Bibtex, but is now `cignoniMeshLabOpenSourceMesh` with Better Bibtex activated.

**Comment by retorquere** [comment]
Set the citation key formula to `zotero`.

But it's impossible to guarantee that they will always match the ones generated without BBT, as zotero-generated keys can change depending on what combination of items is exported together, without any changes to the items themselves.

**Comment by bernb** [comment]
That did work, thanks a lot.

[Just in case others find this Thread later on: You need to refresh the citation key after changing the citation key to `zotero`: Right Click on the entries -> Better BibTeX -> Refresh BibTeX Key]

> But it's impossible to guarantee that they will always match the ones generated without BBT, as zotero-generated keys can change depending on what combination of items is exported together, without any changes to the items themselves.
That's good to know and I don't mind if some items have a different key, I am just happy I do not need to change all of them.

> If you want stable keys with BBT on or off, you can also enable auto pinning https://retorque.re/zotero-better-bibtex/installation/preferences/#automatically-pin-citation-key-after . The pinned keys will be used by Zotero when BBT is not running.
I have activated that just in case.
