### ISSUE TITLE
[Bug]: Export QuickCopy setting does not control behavior 

### ISSUE THREAD

**Issue by aquaresima** [retorquere/zotero-better-bibtex#2487]
### Debug log ID

WWGVRSMY-refs-euc

### What happened?

Hello,

I just want to copy the citation key from a shortcut, which used to work.
I intend to use the QuickCopy, together with Zutilo. 

In Settings->BetterBibtex->Export->QuickCopy, I set the value to CiteKeys (command _citep_)
Then in Zutilo shortcut, I set QuickCopyItems to cmd-maiusc-c - I also tried by the context menu, and with the alternatives 1 and 2.

Then I do the cmd-maiusc-c and I get this:

_Wu, J., Chua, Y., Zhang, M., Li, H., & Tan, K. C. (2018). A Spiking Neural Network Framework for Robust Sound Classification. Frontiers in Neuroscience, 12, 836. https://doi.org/10.3389/fnins.2018.00836_

Which is not what I want, I want this:
_\citep{wuSpikingNeuralNetwork2018}_

The debug says this!
```

(3)(+0000032): Refreshing item box

(3)(+0003157): Keyboard shortcut: copySelectedItemsToClipboard

(3)(+0000446): Abbreviated Nature Communications as Nat. Commun.

(3)(+0000418): Copied bibliography to clipboard in 824 ms}
```

Thanks for your help!

**Comment by retorquere** [comment]
> In Settings->BetterBibtex->Export->QuickCopy, I set the value to CiteKeys (command citep)

Can you get me a screenshot of this? When `Cite keys` is selected, you should not see the `LaTeX command` field. If you want `\citep{...}` you should choose `LaTeX citation`.

If you export the item as "Better BibTeX Citation Key Quick Copy", do you get the output you expect? If so, you should ask the Zutilo author.

**Comment by aquaresima** [comment]
> Can you get me a screenshot of this? When Cite keys is selected, you should not see the LaTeX command field. If you want \citep{...} you should choose LaTeX citation.

Correct, I have Latex command selected now. But the citekeys gives this:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/53222249/231996763-256934da-db46-4d31-ad70-005f9a3055af.png">

It s maybe a bit bugged, when you open the settings the 'CiteKey' has the '\citep{...}' option, but if you select 'Latex command' and then reselect 'Cite key' the '\citep{...}' goes away!

<img width="598" alt="image" src="https://user-images.githubusercontent.com/53222249/231997428-1878a5eb-2fc6-46f5-b81a-c72ecb02d5e2.png">

> If you export the item as "Better BibTeX Citation Key Quick Copy", do you get the output you expect? If so, you should ask the Zutilo author.

Yes, if I export the QuickCopy key I can access the '\citep{myBibKey}'. It is written in a .txt file.

Ok, I can forward this question to Zutilo, but anyway, how am I supposed to access the QuickCopy _if_ I disable Zutilo?
I would be ok even with a context menu entry that allows exporting the BibKey to the clipboard. At the moment, I can only get it through the .txt file!


I find it difficult to trace back the Quick Copy from BetterBibTex command because it has the very same name as the default Quick Copy from Zotero! Maybe you could use another name?

**Comment by aquaresima** [comment]
> Can you upgrade to the latest version and try again? I cannot replicate this.

I am already on the 6.7.71 and on the last Zotero update.

> You can set the quick-copy translator in Zotero Prefs -> Export -> Item Format -> Better BibTeX Quick Copy.

Yes! This worked out! But now I can only Quick copy the \citep{bibkey}, with both these shortcuts:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/53222249/232014923-b8ff7165-e875-4df7-805b-1e92e8eeec1e.png">

> I can add that. But you can double-click the citation key in the item and press Cmd-C to put it on the clipboard.
Yes, but in this way I do not get the '\citep{}' wrapped around, and I can only do it for one item at time.

### _My_ understanding of Quick Copy

Zotero exposes a default 'Quick Copy', that can be set here:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/53222249/232015439-51086281-7954-4149-82e2-68b245029340.png">
And it is _permanently_ assigned to Cmd+shift+C; Good. 
This can be changed (as you just tipped me) to the better bibtex key! 

_THEN_ we have some further shortcuts, that can be set by 'Advanced-> Shortcut' 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/53222249/232016571-dc018feb-cd0c-4d72-a46a-c139123c0ec4.png">
Some of these shortcuts work (new note and new item), but for the two 'Copy Selected Items to the CP' or 'Copy Selected Items Citations to the CP' I have no behavior. That is, the clipboard (CP) remains unchanged. 

_EVENTUALLY_  There is a Quick Copy that can be set in the Better BibTex settings.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/53222249/232017118-1612df37-3588-484b-b803-9eacc8ec6280.png">
This Quick Copy command can be accessed through the 'default quickcopy' (this is what I m doing now), and it basically overrides (or better, bypass) the default export letting you set it through 'bibtex'. 

In this relatively intricate puzzle, we also have Zutilo. Zutilo shortcuts (nor the context menu setting) expose a generic QuickCopy item (which I believe to be the Zotero default) and two additional alternatives. The QuickCopy maps to the default Zotero Quick Copy (which maps to the Better Bibtex Quick Copy in my case). The two alternatives are left hanging.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/53222249/232018231-f628993e-6944-4926-b4ba-9321e04822a5.png">
 
In conclusion.
- I have two menus to choose what to export (the default Quick Copy and the Better Quick Copy), but I can only access one through a shortcut (1. in the list below), and I cannot access any of them through the Context Menu.

- I also have six keybindings/shortcuts, namely:
   1. Shift+Cmd+C, default Zotero in Settings-> Export 'Quick Copy' [ works! ] I have it remapped to Bibtex QuickCopy (see image)
   2. Shift+Cmd+U,  user-defined 'Copy Selected Items to the clipboard' [ not working]
   3. Shift+Cmd+Y,   user-defined in Settings: 'Copy Selected Items Citations to the clipboard' [ not working] 
   4. Shift+Cmd+B, user-define in Zutilo: 'Quick Copy-Item' [works!] it is the same as in (1)
   5. Shift+Cmd+X, user-define in Zutilo: 'Quick Copy-Item (alt 1)' [not working] 
   6. Shift+Cmd+X, user-define in Zutilo: 'Quick Copy-Item (alt 2)' [not working] 

The setting that remaps the 'Quick Copy' to 'Better BibTex Quick Copy'
<img width="681" alt="image" src="https://user-images.githubusercontent.com/53222249/232033948-8e23bf81-30ce-4aca-9321-c5088a7f90fa.png">

It seems to me that there is an overkill of shortcuts, and not enough settings to choose what they do!

**Comment by retorquere** [comment]
> I am already on the 6.7.71 and on the last Zotero update.

My bad -- the last release was stuck in testing on the beta. .74 is out now.

> Yes! This worked out! But now I can _only_ Quick copy the \citep{bibkey}.

That is unfortunately the choice Zotero makes.

> Yes, but in this way, I do not get the '\citep{}' wrapped around, and I can only do it for one item at a time. I want the shortcut :)

OK, I can do that. But if you don't need the full entry under a shortcut alongside the `\citep{...}` shortcut, assigning quick-copy to BBT quick-copy will give you a working solution as-is.

> Zotero exposes a default 'Quick Copy', that can be set here: 

correct.

> And it is _permanently_ assigned to Cmd+shift+C; Good. This can be changed (as you just tipped me) to the better bibtex key!

correct.
 
> _THEN_ we have some further shortcuts, that can be set by 'Advanced-> Shortcut' ... Some of these shortcuts work (new note and new item), but for the two 'Copy Selected Items to the CP' or 'Copy Selected Items Citations to the CP' I have no behavior. That is, the clipboard (CP) remains unchanged. I would like to assign the quickcopy of a full citation to those, but could not find a way

There isn't one. Cmd-Shift-C can be assigned to an exporter, but Cmd-Shift-A only works for citation styles, not exporters.
 
> _EVENTUALLY_ There is a Quick Copy that can be set in the Better BibTex settings. ... This Quick Copy command can be accessed by overriding the 'default quickcopy' (this is what I m doing now, see first screenshot). But it cannot be accessed in any other way.

Close. I had the option of making a myriad of quick-copy translators, or making one that can vary its behavior based on further configuration. I chose the latter. Once upon a time this detail setting would show under the Item Format when you selected BBT Quick Copy, but Zotero didn't like me changing their own preferences screen, so I moved it out.
 
> In this relatively intricate puzzle, we also have Zutilo. Zutilo shortcuts expose a generic QuickCopy item (which I believe to be the Zotero default) and two additional alternatives. The QuickCopy maps to the default Zotero Quick Copy (which maps to the Better Bibtex Quick Copy in my case). The two alternatives are left hanging.

I don't really know much about Zutilo. I know it manages shortcuts, but I don't use it myself.

>  I have two menus to choose what to export (the default Quick Copy and the Better Quick Copy), but I can only access one through a shortcut (1. in the list below), and I cannot access any of them through the Context Menu.

These two settings work in tandem, but correct.

>   I also have six keybindings/shortcuts, namely:

I don't know about these. You'll have to ask the Zutilo author.

**Comment by aquaresima** [comment]
Ok thanks a lot for clarifying! Hope this thread is helpful to someone else in the future!

I would say that a nice workaround to have both Maiusc-Shift-A and Maiusc-Shift-C would be to have the 'Better Bibtex Quick Copy' accessible by a Context Menu Entry - in addition to the tandem with the 'Quick Copy' as it is now.

If there'd be a Context Menu entry, along with the other BibTex entries: 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/53222249/232050548-2f95291d-29b1-4480-b6bb-8e283f20602d.png">

it could be mapped to a third command via Zutilo, which already has access to some 'Better BibTex' functions.
<img width="606" alt="image" src="https://user-images.githubusercontent.com/53222249/232050788-b10179d9-34ab-4c3e-acd6-b092255112f1.png">

If you create the entry I will take care of poking Zutilo developers about it! Maybe use the same API structure of 'Pin key...' and the other that you see in the screenshot above, because those are already accessible to Zutilo!

Thanks a lot. 

PS. 
Can we have a 'push to VS Code' along 'push to TexStudio' ? :):)

**Comment by retorquere** [comment]
If VSCode has an API that will respond to something, sure.

**Comment by aquaresima** [comment]
Sure, I ll check it and open another Feature Request if I find something!

Meanwhile, will you let me know for the 'Copy citekey' entry in the context menu?

Thanks again for your answers

**Comment by retorquere** [comment]
> Sure, I ll check it and open another Feature Request if I find something!
> 
> Meanwhile, will you let me know for the 'Copy citekey' entry in the context menu?

Zutilo can should be able to do this this without me adding it. It's a little awkward to set up, but this is how it is supposed to work:

In the hidden prefs:

* set `extensions.zutilo.quickCopy_alt1` to `export=a515a220-6fef-45ea-9842-8025dfebcc8f` (which is BBT quick copy)
* set `extensions.zutilo.quickCopy_alt2` to `export=ca65189f-8815-4afe-8c8b-8c7c15f0edca` (which is BBT BibTeX)
* In the Zutilo preferences, assign shortcut keys to `QuickCopy items (alt 1)` and `QuickCopy items (alt 1)`

I'm pretty sure I got that right. Zutilo can also add these to the item menu (which is what you describe above), but I can't get them to work. You'll have to ask Zutilo about that though. I'd rather not implement behavior already covered by other plugins. BBT is complex enough as it is.

**Comment by aquaresima** [comment]
Great! With the last comment, I could achieve exactly what I wanted to!

**Comment by aquaresima** [comment]
> > Sure, I ll check it and open another Feature Request if I find something!
> > Meanwhile, will you let me know for the 'Copy citekey' entry in the context menu?
> 
> Zutilo can should be able to do this this without me adding it. It's a little awkward to set up, but this is how it is supposed to work:
> 
> In the hidden prefs:
> 
> * set `extensions.zutilo.quickCopy_alt1` to `export=a515a220-6fef-45ea-9842-8025dfebcc8f` (which is BBT quick copy)
> * set `extensions.zutilo.quickCopy_alt2` to `export=ca65189f-8815-4afe-8c8b-8c7c15f0edca` (which is BBT BibTeX)
> * In the Zutilo preferences, assign shortcut keys to `QuickCopy items (alt 1)` and `QuickCopy items (alt 1)`
> 
> I'm pretty sure I got that right. Zutilo can also add these to the item menu (which is what you describe above), but I can't get them to work. You'll have to ask Zutilo about that though. I'd rather not implement behavior already covered by other plugins. BBT is complex enough as it is.


Great! By assigning these shortcuts I could achieve exactly what I wanted to!
