### ISSUE TITLE
[Feature]: Auto export with bibtex format

### ISSUE THREAD

**Issue by wztdream** [retorquere/zotero-better-bibtex#2489]
### Debug log ID

auto export with bibtex format

### What happened?

Hi,
Thank you for this great project. 
BBT is great for my non-formal writing. But recently I am preparing a scientific paper, the styles that the journal used only supports bibtex format. The entry keys are mismatch with BBT. So is it possible to setting the format for auto export to bibtex format? I seems now it only support better bibtex and better biblatex format.

**Comment by retorquere** [comment]
The issue template asks for a debug log ID. People ignore that, and then ignore the bot reminding them that yes, I *do* need a debug log ID. Can you offer me some insight on why people are so reluctant to perform 4 mouse clicks so I can help them? I really don't understand. It's really frustrating. I don't want to make the bot explanation longer, because that will make less people read the information.

The debug logs gives me your BBT settings, so that I don't have to guess at them, and I don't have to deal with screenshots of settings. Your settings influence, among other things, how your keys are generateed.

> the styles that the journal used only supports bibtex format. The entry keys are mismatch with BBT. 

I don't know what this means. BBT-generated keys work just fine for any bibtex style, including whatever style a particular journal mandates.

**Comment by wztdream** [comment]
> The issue template asks for a debug log ID. People ignore that, and then ignore the bot reminding them that yes, I _do_ need a debug log ID. Can you offer me some insight on why people are so reluctant to perform 4 mouse clicks so I can help them? I really don't understand. It's really frustrating. I don't want to make the bot explanation longer, because that will make less people read the information.
> The debug logs gives me your BBT settings, so that I don't have to guess at them, and I don't have to deal with screenshots of settings. Your settings influence, among other things, how your keys are generateed.
> 

Thank you for your reply, and sorry for not able to provide the "debug log ID". For me, I did not know what the so called **debug log id** means, I think may be that's why people ignore that.  In my case, what I what is just a feature request, so there is no "bug" there, so it seems for my case it is unreasonable to provide the "bug log id".

> > the styles that the journal used only supports bibtex format. The entry keys are mismatch with BBT.
> 
> I don't know what this means. BBT-generated keys work just fine for any bibtex style, including whatever style a particular journal mandates.

Sorry for the confusion. I think I used the wrong word "key", may be I should use the word "item".  What I mean is that the journal usually expect a "year" item, but the auto export with "better bibtex format" setting usually give a "date" item, and the styles provided by the journal did not recognize "date", so the reference generated by latex will have no "year".

Anyway, lets see a simple example below, you can see that there is no "year" if auto export the bib file with better bibtex format.

Here is what I get when using auto export with better bibtex format:
```bibtex
@online{burgessMONetUnsupervisedScene2019,
  title = {{{MONet}}: {{Unsupervised Scene Decomposition}} and {{Representation}}},
  shorttitle = {{{MONet}}},
  author = {Burgess, Christopher P. and Matthey, Loic and Watters, Nicholas and Kabra, Rishabh and Higgins, Irina and Botvinick, Matt and Lerchner, Alexander},
  date = {2019-01-22},
  number = {arXiv:1901.11390},
  eprint = {arXiv:1901.11390},
  eprinttype = {arxiv},
  doi = {10.48550/arXiv.1901.11390},
  url = {http://arxiv.org/abs/1901.11390},
  urldate = {2022-07-22},
  abstract = {The ability to decompose scenes in terms of abstract building blocks is crucial for general intelligence. Where those basic building blocks share meaningful properties, interactions and other regularities across scenes, such decompositions can simplify reasoning and facilitate imagination of novel scenarios. In particular, representing perceptual observations in terms of entities should improve data efficiency and transfer performance on a wide range of tasks. Thus we need models capable of discovering useful decompositions of scenes by identifying units with such regularities and representing them in a common format. To address this problem, we have developed the Multi-Object Network (MONet). In this model, a VAE is trained end-to-end together with a recurrent attention network -- in a purely unsupervised manner -- to provide attention masks around, and reconstructions of, regions of images. We show that this model is capable of learning to decompose and represent challenging 3D scenes into semantically meaningful components, such as objects and background elements.},
  pubstate = {preprint},
}
```
And this is what I get when manually export it with bibtex format:

```bibtex
@misc{burgessMONetUnsupervisedScene2019,
	title = {{MONet}: {Unsupervised} {Scene} {Decomposition} and {Representation}},
	shorttitle = {{MONet}},
	url = {http://arxiv.org/abs/1901.11390},
	doi = {10.48550/arXiv.1901.11390},
	abstract = {The ability to decompose scenes in terms of abstract building blocks is crucial for general intelligence. Where those basic building blocks share meaningful properties, interactions and other regularities across scenes, such decompositions can simplify reasoning and facilitate imagination of novel scenarios. In particular, representing perceptual observations in terms of entities should improve data efficiency and transfer performance on a wide range of tasks. Thus we need models capable of discovering useful decompositions of scenes by identifying units with such regularities and representing them in a common format. To address this problem, we have developed the Multi-Object Network (MONet). In this model, a VAE is trained end-to-end together with a recurrent attention network -- in a purely unsupervised manner -- to provide attention masks around, and reconstructions of, regions of images. We show that this model is capable of learning to decompose and represent challenging 3D scenes into semantically meaningful components, such as objects and background elements.},
	urldate = {2022-07-22},
	publisher = {arXiv},
	author = {Burgess, Christopher P. and Matthey, Loic and Watters, Nicholas and Kabra, Rishabh and Higgins, Irina and Botvinick, Matt and Lerchner, Alexander},
	month = jan,
	year = {2019},
	note = {arXiv:1901.11390 [cs, stat]},
}
``` 
 But strangely, if I **manully** export the bibfile with better bibtex format there is a year item!

This is what I get if I manually export the bib file. Manually here I mean by "select the paper in zotero" --> right click and choose "export item" --> then choose better bibtex format -- then export
```bibtex
@misc{burgessMONetUnsupervisedScene2019,
  title = {{{MONet}}: {{Unsupervised Scene Decomposition}} and {{Representation}}},
  shorttitle = {{{MONet}}},
  author = {Burgess, Christopher P. and Matthey, Loic and Watters, Nicholas and Kabra, Rishabh and Higgins, Irina and Botvinick, Matt and Lerchner, Alexander},
  year = {2019},
  month = jan,
  number = {arXiv:1901.11390},
  eprint = {arXiv:1901.11390},
  publisher = {{arXiv}},
  doi = {10.48550/arXiv.1901.11390},
  urldate = {2022-07-22},
  abstract = {The ability to decompose scenes in terms of abstract building blocks is crucial for general intelligence. Where those basic building blocks share meaningful properties, interactions and other regularities across scenes, such decompositions can simplify reasoning and facilitate imagination of novel scenarios. In particular, representing perceptual observations in terms of entities should improve data efficiency and transfer performance on a wide range of tasks. Thus we need models capable of discovering useful decompositions of scenes by identifying units with such regularities and representing them in a common format. To address this problem, we have developed the Multi-Object Network (MONet). In this model, a VAE is trained end-to-end together with a recurrent attention network -- in a purely unsupervised manner -- to provide attention masks around, and reconstructions of, regions of images. We show that this model is capable of learning to decompose and represent challenging 3D scenes into semantically meaningful components, such as objects and background elements.},
  archiveprefix = {arxiv},
}
```

**Comment by wztdream** [comment]
And here is the debug log id: UWR9LUND-apse
I did not know it before, sorry about that.

**Comment by retorquere** [comment]
> Thank you for your reply, and sorry for not able to provide the "debug log ID". For me, I did not know what the so called **debug log id** means, 

Please re-read the **bold** message parts in the bot message

> I think may be that's why people ignore that. In my case, what I what is just a feature request

WHICH THE BOT MESSAGE ADDRESSES SPECIFICALLY

> so there is no "bug" there, so it seems for my case it is unreasonable to provide the "bug log id".

**Unreasonable**?!?!? Are you **kidding** me?! It is unreasonable for me to ask that you make **four mouseclicks**? I have done support for BBT at least since 2017. I think I'm better positioned to determine what is and isn't needed in the work I do.

I am just flabbergasted. You think it is reasonable to ask for support when you can't be bothered to perform four mouse clicks, which a full instruction on how to perform them, and even a justification for why I need them?

> Sorry for the confusion. I think I used the wrong word "key", may be I should use the word "item". What I mean is that the journal usually expect a "year" item, but the auto export with "better bibtex format" setting usually give a "date" item, 

It does not. Better BibLaTeX exports `date`. Better BibTeX exports `year` and `month`.

> Anyway, lets see a simple example below, you can see that there is no "year" if auto export the bib file with better bibtex format.

If you send a debug log as per instruction point 1., I get a copy of that item so that I can try to replicate what you are experiencing. **This is why I ask for these logs, and this is why I am better positioned to judge what is and isn't necessary for me to help you**.

**Comment by retorquere** [comment]
> And here is the debug log id: UWR9LUND-apse I did not know it before, sorry about that.

`UWR9LUND-apse` doesn't contain activity indicating an export using either Better BibTeX or Better BibLaTeX. Please trigger the auto-export (you can trigger the auto-export in the BBT preferences), then right-click the item and send a debug report from the popup menu. Point 1 in the bot message explains how.

When you send a new log, please check the checkbox that says "include cache".

> Here is what I get when using auto export with better bibtex format:

This is 100% generated by Better BibLaTeX, not Better BibTeX. Are you sure you have set up an auto-export for Better BibTeX, not Better BibLaTeX? Please go into the BBT preferences and post a screenshot of the auto-export you have set up.

**Comment by wztdream** [comment]
@retorquere 
>Unreasonable?!?!? Are you kidding me?! It is unreasonable for me to ask that you make four mouseclicks? I have done support for BBT at least since 2017. I think I'm better positioned to determine what is and isn't needed in the work I do.

Hi, I am really sorry if my previous comment make you feels not good, I really did not mean that.  You are an active maintainer, and really helps a lot.  And you are right, I should read the bot comment carefully, and the bug log id is really important and necessary for trouble shooting. 

Here is the new log bug id: 2LBSJS5C-refs-apse

>This is 100% generated by Better BibLaTeX, not Better BibTeX. Are you sure you have set up an auto-export for Better BibTeX, not Better BibLaTeX? Please go into the BBT preferences and post a screenshot of the auto-export you have set up.
![image](https://user-images.githubusercontent.com/39213018/232208751-15337d56-0702-4616-a3ea-a648d94960e5.png)

I think you are right, my setting is BibLaTex.  It seems there is no setting option about the format, "BibLaTex" seems is the default setting. So how can I change the setting to BetterBibTex, and what is better is that also allow to setting to bibtex?

**Comment by retorquere** [comment]
You cannot change the format, but you can remove it here and set up a new auto-export using Bette BibTeX. The one in the screenshot was set up with Better BibLaTeX selected as the export format.

**Comment by wztdream** [comment]
I seems not work, I cliked the "remove" button, this is what I get:
![image](https://user-images.githubusercontent.com/39213018/232210793-59031d34-08e7-4386-8696-8dd850d3c969.png)
It is empty, and there is no "add" option here. Can you elaborate how to add the auto export? I think there should be an option here.
