### ISSUE TITLE
[Bug]: No "keep updated" option available when creating a new collection export

### ISSUE THREAD

**Issue by shuoyuan** [retorquere/zotero-better-bibtex#2491]
### Debug log ID

CQLAUSPV-refs-apse

### What happened?

BBT 6.7.75
Zotero 6.0.23

There is no "keep updated" option appearing in the Collection Export pane when I want to create a new automatic export task for a collection, even though five previously created automatic export tasks are working perfectly.

<img width="292" alt="Snipaste_2023-04-19_16-57-09" src="https://user-images.githubusercontent.com/25116465/233027113-87c19d30-44f6-414c-bdd5-abe9cf6d00e7.png">

**Comment by shuoyuan** [comment]
Thank you for your prompt response, and you are right the "Keep Updated" option is back.
I vaguely remember not having these options when I wanted to export, but now there are here, I don't understand ...

**Comment by retorquere** [comment]
They're always absent for "BibTeX" and "BibLaTeX". The screenshot you posted above is the way it should be. "Keep Updated| *only* exists when you choose one the the "Better ..." formats in the dropdown.
