### ISSUE TITLE
[Bug]: Auto-export cannot be removed

### ISSUE THREAD

**Issue by martenlienen** [retorquere/zotero-better-bibtex#2493]
### Debug log ID

MUL2TQCR-refs-euc

### What happened?

I want to remove an old auto export because I have created a new one that exports to a different file. However, there is no button or other way to remove the auto-export in the `Automatic export` settings pane as you can see in the following screenshot.

![image](https://user-images.githubusercontent.com/339165/233788932-05c793e2-8c54-40a7-8ae3-1bd2fbe6c3ff.png)

**Comment by retorquere** [comment]
Please try build 4202

**Comment by martenlienen** [comment]
Unfortunately, it still looks exactly the same. Should there be a button to remove the export?

**Comment by retorquere** [comment]
Yeah but it's scrolled out of the bottom. I'm trying to make it scrollable for you.

**Comment by martenlienen** [comment]
Thanks that worked a little bit! There is now a scrollbar but it only scrolls one row of text, so I can see a new checkbox but not the buttons at the bottom:
![image](https://user-images.githubusercontent.com/339165/234586086-51968b55-dd3d-44e9-8ca3-27fb905e1a44.png)
However, I can click in the field and then press tab until I get to the Remove button which brings it in view but this scrolls the tab bar at the top (Automatic Exports etc.) out of view and there is no way to bring it back besides closing and re-opening the preferences window:
![image](https://user-images.githubusercontent.com/339165/234586490-79e0fecf-488d-4548-afff-d5f77176d6ee.png)
Also, I cannot resize the preferences window to make it large enough to fit everything. If I resize it, it always snap back to its original size.

**Comment by retorquere** [comment]
The BBT prefs open from the Tools menu in build 4256. Can you test whether that improves matters?

**Comment by martenlienen** [comment]
I can now resize the window but the inner thing that has the settings and buttons stays the same size and I still cannot scroll in the inner thing. In the following screenshot I have resized the window but you can see that the buttons at the bottom are still hidden.

![image](https://user-images.githubusercontent.com/339165/236679737-3392efc6-e1b5-4a02-bb51-e137fdb688ce.png)

**Comment by martenlienen** [comment]
Now I can resize the window and the buttons appear! However, I can still cannot scroll in the window and resizing it puts the UI in some *weird* states:

![image](https://user-images.githubusercontent.com/339165/236692582-b997d30b-59bb-4197-aedc-91ee040c0ede.png)

![image](https://user-images.githubusercontent.com/339165/236692605-82e3145a-698a-4aa9-a679-297c6209cf7f.png)

**Comment by retorquere** [comment]
I think I have fixes for those. I'll get to that when I'm home in a few hours. UI work is such finicky work.

**Comment by martenlienen** [comment]
Okay, but in the default view without resizing the window the buttons are still out of view

![image](https://user-images.githubusercontent.com/339165/236700068-30f95ae1-a90b-437f-ba87-484bf53dfa78.png)

**Comment by martenlienen** [comment]
But the buttons no longer puke out their labels and the tabs at the top also keep their height :)

**Comment by retorquere** [comment]
This should resize the window to its proper size when you select a tab. At this point I'm just experimenting to see what gets you the desired result. I cannot reproduce the problem on MacOS or Ubuntu 22.10, and the documentation for the Zotero UI framework has fallen into disrepair literally a decide ago, so good information and support is hard to come by.

Not the fault of Zotero BTW, they inherited it (and the docs for it) from their use of Firefox as a platform, and they're working actively to replace it, but it does complicate for now getting a stable UI done.

**Comment by martenlienen** [comment]
Yes, now everything works! Thanks a lot for your enthusiasm for working out this UI issue. I use i3 as my window manager and that might have been the source of the problem. Sometimes GUIs can be overwhelmed when thrown in a tiling window manager, even if I configure them as floating windows.
