### ISSUE TITLE
[Feature]: BBT auto exports when I modify a note, even though it has the setting of not exporting notes

### ISSUE THREAD

**Issue by matthieuheitz** [retorquere/zotero-better-bibtex#2500]
### Debug log ID

RWTFWW43-euc

### What happened?

It's not really a bug, more something that could be more efficient, but I did a debug log as github asked.
BBT auto exports when I modify a note attachment whose entry belongs to the folder that has auto-export enabled, even though that folder has the setting of not exporting notes.
There should be a condition so that BBT doesn't auto export if only a note has been changed, when the setting of exporting notes is off.

**Comment by MSBack** [comment]
I made an issue about this here earlier: https://github.com/retorquere/zotero-better-bibtex/issues/1494

**Comment by retorquere** [comment]
And I answered that issue - to find out what changed, I have to do the export.
