### ISSUE TITLE
[Bug]: Initializing stuck at Installing bundled translators

### ISSUE THREAD

**Issue by gabrieldansereau** [retorquere/zotero-better-bibtex#2501]
### Debug log ID

F6THSK9F-euc

### What happened?

Seems similar to #2482. I opened Zotero today and the pop-up is stuck on 'Better BibText: Initializing - Installing bundled translators'. None of the citation keys load. Everything worked fine yesterday.

Thanks in advance for your help!

**Comment by retorquere** [comment]
Can you try this build?

**Comment by gabrieldansereau** [comment]
Still the same. New debug ID is 3NDDEQDK-euc

**Comment by retorquere** [comment]
Can you :hiddenprefs:, search for `scrubDatabase`, double-click it to toggle it to `true`, and restart Zotero?

**Comment by gabrieldansereau** [comment]
New debug ID is XVVWR5IS-euc. I set `scrubDatabase` to true, then restarted directly with logging.

It spends more time on "Loading databases", then still hangs on "Installing bundled translators" and switches back `scrubDatabase` to false.

**Comment by retorquere** [comment]
A new build will drop here in a few minutes, can you do the above procedure again, but this time when you send the log, check the "include cache" checkbox before sending.

**Comment by gabrieldansereau** [comment]
New debug ID is 6LXZ26XU-euc

Thanks a lot for your quick responses!

**Comment by retorquere** [comment]
Is it possible you edited your auto-exports manually at some point? You have 2 auto-exports setup, but they're missing their metadata, so you're getting errors when BBT checks whether they should be scheduled at start. I've never seen a database in this state.

**Comment by gabrieldansereau** [comment]
It's possible I moved the exported files around at some point, but I don't think I changed the content or played with metadata in my Zotero folder. The bug did happen the day after I set up one of the 2 auto-exports though.

I can definitely live without them or start them over. Is it possible to disable the auto-exports somewhere other than in the Preferences? Right now the Better BibTex tab only displays "Better BibTex is loading" and I cannot change the settings.

**Comment by retorquere** [comment]
A build will drop here in 5 minutes or so that will remove the problematic entries when scrubDatabase is on. That should resolve the problem for you.

Moving around files should have no impact. I have no idea how these entries ended up this way in your database.

**Comment by gabrieldansereau** [comment]
Problem resolved! Thank you so much, really grateful for your help over the weekend!

**Comment by retorquere** [comment]
My pleasure. It's easier for me to do this in weekends, so you planned your problem just right 😉 . The fix is in the new release, you will be upgraded automatically. Thanks for your patience in hashing this out.
