### ISSUE TITLE
[Bug] CAYW doesn't work anymore with TeXstudio

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#2511]
### Debug log ID

WSTGFCS5-refs-euc

### What happened?

The following [TeXstudio](https://texstudio.sourceforge.net/) script used to work in order to CAYW:
```
%SCRIPT
var url = 'http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true';
system('curl -s ' + url);
```
That's not the case anymore and [the TXS developer suspects an issue with Zotero](https://github.com/texstudio-org/texstudio/issues/3109).

I noticed several changes in recent versions of Zotero that might cause the current issue. Should the `curl` call be updated?

**Comment by retorquere** [comment]
I don't see a call to CAYW at all in `WSTGFCS5-refs-euc`. Can you turn on debug logging in the hep menu, try CAYW again by calling it with `curl` from the command line, and send a new debug log?

**Comment by retorquere** [comment]
See my comment over at TSX.

**Comment by dbitouze** [comment]
> I don't see a call to CAYW at all in `WSTGFCS5-refs-euc`. Can you turn on debug logging in the hep menu, try CAYW again by calling it with `curl` from the command line, and send a new debug log?

Here it is with KVW6WX2B-euc. I added `zotero-allowed-request` to the TeXstudio script:
```
%SCRIPT
var url = 'http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true&zotero-allowed-request=true';
system('curl -s ' + url);
```
but I get the same error in the `Messages` panel of TeXstudio:

```
Process started: curl -s http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true&zotero-allowed-request=true

Request not allowed
```

**Comment by dbitouze** [comment]
> I added `zotero-allowed-request` to the TeXstudio script

But tweaking the user-agent:
```
%SCRIPT
var url = 'http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true';
system('curl -s -A "TeXstudio" ' + url);
```
did the trick: see https://github.com/texstudio-org/texstudio/issues/3109#issuecomment-1546891005.
