### ISSUE TITLE
[Bug/Feature]: "Error occurred" exporting library 

### ISSUE THREAD

**Issue by mmzotero** [retorquere/zotero-better-bibtex#2516]
### Debug log ID

68LTWEDJ-refs-euc

### What happened?

**What happened in Zotero:** I tried to export my library -- with both Better BibTex and Better BibLaTex, it creates a file with that name, but it is empty, and then Zotero says "Error Occurred"

**I expected:** I though it would make a file with all my annotations, pdf, etc. and the .bib file.

**Re: debug log:** I was not siure which reference to right-click so I right-clicked a random citation in Zotero.

**Thank you!**

**Comment by retorquere** [comment]
Zotero reports:

> Win error 3 during operation removeEmptyDir on file C:\Users\moizm\OneDrive\Desktop\PhD Research\My Library\files\4016 (The system cannot find the path specified.)

Is there anything special about that path? I think background export was on, can you try exporting with it off and see if you get a different error?

**Comment by mmzotero** [comment]
Thank you for being so speedy!

> 

I can export "Zotero RDF" without issues.



> Zotero reports:
> 
> > Win error 3 during operation removeEmptyDir on file C:\Users\moizm\OneDrive\Desktop\PhD Research\My Library\files\4016 (The system cannot find the path specified.)
> 
> Is there anything special about that path? I think background export was on, can you try exporting with it off and see if you get a different error?

**Turn off Background export:** made no difference
**New location export that was not in OneDrive:** no difference
**That 4016 path:** I realised a bunch of my PDFs had not transferred into Zotero for some reason, so I uploaded all of them.. unfortunately it hasn't made a difference. 
**Export without "export files/annotations" ticked on**: made no difference

So sorry, I don't know if maybe there is some other missing file? I don't know how to check.

**Comment by retorquere** [comment]
I'm still seeing errors related to `C:\Users\moizm\OneDrive\Desktop\My Library` in `4S29H6JD-refs-euc`. Can you restart Zotero, do only the second export, and send a new log?

**Comment by mmzotero** [comment]
> 

Here you are! Again an empty .bib file.

Debug log: **6IFQE5LE-refs-euc**

**Comment by retorquere** [comment]
It's an out of memory error. Go into better bibtex prefs -> export -> misc and disable the cache, see if that helps.

**Comment by retorquere** [comment]
Zotero on Windows is (for now) memory-constrained. That will change with Zotero 7.

**Comment by mmzotero** [comment]
Oh!! Ok! I did disable the cache, I guess I just have too many PDFs saved on it :( Thank you for your help!!

**Comment by retorquere** [comment]
The number of attachments won't make a difference unfortunately.

**Comment by mmzotero** [comment]
Oh.. sorry I can ask this on a Zotero forum, but then why would it be out of memory :S Does Zotero use a lot of memory just to...exist?

**Comment by retorquere** [comment]
It's primarily BBT I'm afraid. I don't know how it is on Windows, but on MacOS, Zotero uses about 400Mb of memory, and if you load BBT, that's another 400 MB (I really need to look into that. that's a lot more than I had expected). On Windows, Zotero cannot use more than 2GB sum total.

**Comment by mmzotero** [comment]
Thank you so much anyway! I will just not sync to Obsidian until the new Zotero thing comes out. C'est la vie. 

Thanks again and also for explaining!
