### ISSUE TITLE
No "Export notes" option on Automatic Export page

### ISSUE THREAD

**Issue by haroldship** [retorquere/zotero-better-bibtex#2517]
### Debug log ID

VIZJFCEN-refs-euc

### What happened?

I would like to export notes along with references. However, the option to Export Notes is missing from the Automatic Export dialog in the configuration.

![image](https://github.com/retorquere/zotero-better-bibtex/assets/3765503/7893f0d0-bf20-4f0b-b79f-5b353382b129)

**Comment by retorquere** [comment]
The Zotero `extra` field gets copied to CSL `note`, but Zotero items can have multiple rich-text notes, and the CSL-JSON spec doesn't accommodate these.

**Comment by retorquere** [comment]
does that address your question?

**Comment by haroldship** [comment]
So if I want to also export Notes, I need to use different format?

**Comment by haroldship** [comment]
I have switched to BibLaTeX format and I see it now.
