### ISSUE TITLE
Feature: import of non-standard entry type

### ISSUE THREAD

**Issue by Dario-Izaguirre** [retorquere/zotero-better-bibtex#2521]
### Debug log ID

ID D1470548010 

### What happened?

Good morning,
I work as a researcher in history and for a long time I have been using the JabRef program for my bibliographic database. I recently started using Zotero, given the dynamism of that program.
I imported my database from JabRef and everything seemed to work fine, until I realized that certain entries weren't working in Zotero.
The fact is that, for the construction of bibliographies with primary sources, JabRef allows you to create custom bibliography types that allow you to cite unpublished or daily documents. I created a type in JabRef (Periodical) that has worked perfectly for me. However, Zotero is unable to import it and consequently I am unable to use those entries.
Zotero gives me an import error, which I'll pass on immediately.

here the Zotero's error
Don't know what Zotero type to make of 'periodical' for @BolLegi186672, importing as document

Here the JabRef Citation

@periodical{BolLegi186672,
   journal = {Legislative and Official Bulletin 1866-1872},
   title = {{{\normalfont A.N.H. -- Legislative and Official Bulletin}}},
   year = {1866},
   number = {Series 1a, No. 1},
   month = {02},
   address = {Tegucigalpa},
   keywords = {Newspapers},
   }

Best regards,
[Debug Output.txt](https://github.com/retorquere/zotero-better-bibtex/files/11518642/Debug.Output.txt)

**Comment by retorquere** [comment]
Sorry for the bit message. The input sample suffices.

**Comment by retorquere** [comment]
But other than the note left by the import, the resulting entry re-exports to

```
@periodical{BolLegi186672,
  title = {A.{{N}}.{{H}}. \textendash{} Legislative and Official Bulletin},
  year = {1866},
  month = feb,
  number = {Series 1a, No. 1},
  address = {{Tegucigalpa}},
  keywords = {Newspapers}
}
```

so I'm not sure what you want done differently.

**Comment by retorquere** [comment]
The note is informative, it isn't an error. This is the only way importers can provide feedback on what happened during the import.

**Comment by retorquere** [comment]
So...?

**Comment by retorquere** [comment]
In assuming this is addressed.
