### ISSUE TITLE
[Bug/Feature]: BibTex tab missing in Zotero Settings

### ISSUE THREAD

**Issue by tleschev** [retorquere/zotero-better-bibtex#2523]
### Debug log ID

TAB_MISSING is not a debug log ID. Come on. 

### What happened?

As already mentionned by another user, the citation key column sometime goes missing from Zotero. Restarting it usually solve the issues. 
However, the Bibtex tab in the settings is now missing as well, which means that I cannot handle my exported libraries. I have tried quitting and restarting Zotero, disabling and enabling the extensions, but this does not solve the issue. 
Any idea what may cause this ? 
Thank you for your help !

**Comment by retorquere** [comment]
As both the template and the bot message said. There's no debug log, so I can't help you. I don't know why this is ignored so often.

**Comment by retorquere** [comment]
If you comment here the issue will automatically reopen. Without a debug log there's nothing I can do.
