### ISSUE TITLE
[Bug]: Length filter double-counting characters

### ISSUE THREAD

**Issue by Servinjesus1** [retorquere/zotero-better-bibtex#2525]
### Debug log ID

KA2EETKC-refs-euc

### What happened?

Using the `journal` Function with the `abbr` and `len` Filters is not working because each character is being double-counted in the `len` filter. That is to say, in the debug logged example, the journal abbreviation abbreviation (Journal Abbreviation field, abbreviated again) is JLTP, but the `len` filter must be set to `len('<', 8)` to work. I validated this with the `substring` Filter, when taking characters 1-1 or 1-2, I get a J, and 1-8, I get all four characters.

That it's both the `len` and `substring` Filters double-counting is interesting. Could this be a generic issue with counting characters, or a problem somehow specifically with journals and their abbreviations?

**Comment by retorquere** [comment]
It was counting all characters, including spaces.

**Comment by retorquere** [comment]
Can you verify 4319 does what you expect?

**Comment by Servinjesus1** [comment]
The same fix would also be helpful on `substring` for debugging.

This doesn't solve the problem, though. For my abbreviation (JLTP), I still need a len value of 8 to get the filter to pass.
![(12-14)_000569 My Library - Zotero](https://github.com/retorquere/zotero-better-bibtex/assets/8541095/0e290e48-02fd-4b84-99d4-4013a5532dc3)

which seems to be a separate problem from the spaces kept around in `len`/`substring` before they're ultimately removed right at the end of key generation. More details:

![(12-22)_000570 My Library - Zotero](https://github.com/retorquere/zotero-better-bibtex/assets/8541095/37785df1-f84c-4c60-b92f-0b21e739c766)

With substring, I've confirmed that it is including spaces:
![(12-22)_000571 My Library - Zotero](https://github.com/retorquere/zotero-better-bibtex/assets/8541095/5c5b8436-51b4-4652-b02c-034616a97472)
(Taking 12 characters from unfiltered journal value returns a key with 10 characters, 2 spaces were in the unfiltered journal value)

Still a problem with `len`:
![(12-30)_000572 My Library - Zotero](https://github.com/retorquere/zotero-better-bibtex/assets/8541095/bb556c12-5622-4c4e-a39c-3333c19b23de)
(length must be <13 to pass despite apparent change which should prune the spaces from substring before calculating the length)

`abbr` seems to be a completely separate problem:

**Comment by retorquere** [comment]
> The same fix would also be helpful on substring for debugging.

I'm not yet sure I want to do that for substring. For debugging you can use `.condense.len` or `condense.substring`.

**Comment by retorquere** [comment]
> The same fix would also be helpful on `substring` for debugging.
> 
> This doesn't solve the problem, though. For my abbreviation (JLTP), I still need a len value of 8 to get the filter to pass. ![(12-14)_000569 My Library - Zotero](https://user-images.githubusercontent.com/8541095/241000212-0e290e48-02fd-4b84-99d4-4013a5532dc3.jpg)

I cannot reproduce this, for me this gets me `JLTP` as the key. Have you refreshed the key after setting this formula?

> Still a problem with `len`: ![(12-30)_000572 My Library - Zotero](https://user-images.githubusercontent.com/8541095/241003588-bb556c12-5622-4c4e-a39c-3333c19b23de.jpg) (length must be <13 to pass despite apparent change which should prune the spaces from substring before calculating the length)

I also cannot reproduce this. `journal(off).substring(1,12).len('<', 11) | 'wrong'` gets me `JournalofL`.

> 
> `abbr` seems to be a completely separate problem:

There seems to be something missing here.

**Comment by retorquere** [comment]
I don't think I want to add space-removal to `substring`. The problem is this:

There are filters (`skipwords` and `select`) that require spaces to be present, and at least one (`replace`) that may want them, so a blanket removal of spaces in all functions/filters would be a problem. Maybe a combination of `.substring.select` is unlikely, but I am reticent of making it impossible by making `.substring` always behave like `.condense.replace`. I am more comfortable having `len` apply space-removal unconditionally because `len` only tests the value, it doesn't alter it.

`.condense.substring` will do what you want while I ponder the question. Can you run your cases with `condense` added?

**Comment by Servinjesus1** [comment]
My mistake, wasn't using the updated version on that last test.

That's reasonable, instead I think stripping whitespace from `len` and `abbr` make the most sense. My current theory is that `abbr` must be turning 'Journal of Low Temperature Physics' into 'J o L T P' because when I do `journal('off').abbr` plus:
- `.substring(1,2)` I get 'J'
- `.substring(1,3)` I get 'Jo'
- `.substring(1,4)` I get 'Jo'
- `.substring(1,5)` I get 'JoL'
- `.substring(1,6)` I get 'JoL'

but adding condense makes `.condense.substring(1, X)` give me X characters like I expect.

It helped to learn that whitespace doesn't get stripped until the very last step.

**Comment by retorquere** [comment]
Does this do what you want?

**Comment by Servinjesus1** [comment]
Yep, thanks!
