### ISSUE TITLE
[Feature]: Set title case protection export-by-export

### ISSUE THREAD

**Issue by juhaszp95** [retorquere/zotero-better-bibtex#2534]
### Debug log ID

AYT5WWT9-refs-euc

### What happened?

Hello,

Thanks for maintaining BBT. Currently, applying case-protection for capitalised words is a global switch, i.e. you can do this for all exports or none. I currently have this setting off as it's not generally needed (and I can take car of special cases in biblatex), but some journals come with their own BibTeX .bst styles which I cannot edit and which do need case-protection.

Therefore, it would be nice if I could enable case-protection on a case-by-case basis, i.e. it if I could enable it for a certain automatic export, but keep the default (off) for other exports.

**Comment by retorquere** [comment]
We disagree on whether it is generally (un)needed. I only added the option because people stubbornly keep entering title-cased titles to Zotero.

In what cases is it not needed? And in what cases is it needed for bibtex but harmful for biblatex? If you can send a few samples as per instruction 1. above I can take a look. This is why I need these, it's frustratingly common for people to second-guess me on this even though I make it pretty clear they're generally not optional.

**Comment by juhaszp95** [comment]
The use case is this: I want to preserve capitalisation in my titles as they are printed originally. As suggested in https://github.com/retorquere/zotero-better-bibtex/issues/2424#issuecomment-1446548778, I do `\DeclareFieldFormat{titlecase}{#1}` for biblatex-based styles. However, there is no bibtex alternative to this (as far as I can tell), only to protect the capitalised words, so I would like to do that for certain exports where I'm bound to use a journal's bibtex-based .bst style. However, I don't want case-protection to be enabled generally for the reasons mentioned in https://github.com/retorquere/zotero-better-bibtex/issues/2424.

**Comment by retorquere** [comment]
I can see why you'd want that, but that doesn't sound like the general case to me. 

If you don't want any casing to be applied, the zotero-supported way to do that is to wrap the whole title in `<span class="nocase">...</span>` (I think Zotero also supports `<nc>...</nc>`; I know BBT does). Would that get you what you want?

**Comment by retorquere** [comment]
I will still need a debug log as per point 1 if we're going to talk specifics. I prefer to have actual case data alongside more abstract talk about BBT behavior.

**Comment by juhaszp95** [comment]
I've generated a log as an example, ID AYT5WWT9-refs-euc. (Bose is a name, so would have to remain capitalised either way.)

I'm submitting a paper to the American Physical Society (Physical Review, which has it's mandatory LaTeX class called RevTeX), which makes the title lowercase (including Bose) except the first letter (via a bibtex style file).

The problem with the <span> construct is that I would have to do it for all my entries and it would not be easy to change/reverse if references are reused between different projects. I would rather just enable case protection for this specific export.

**Comment by retorquere** [comment]
You can do per-directory preferences using https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#preferencesoverride. Maybe that gets you what you need?

I do still disagree with you on whether case protection is or is not generally needed. It might not be needed with the `\DeclareFieldFormat{titlecase}{#1}` hack, but the things you want from bib(la)tex are very certainly not the general case.

Adding modifiable prefs to the auto-exports is not happening short-term. It would require a change to the rather delicate caching mechanism, and I'm neck-deep in the Zotero 7 port right now.

**Comment by retorquere** [comment]
Just for curiosity -- Why fight the style about how `Droplet Crystal Ground States of a Dipolar Bose Gas` is printed? The way I see it, for the general case, entering `Droplet crystal ground states of a dipolar Bose gas` in Zotero to get `Droplet Crystal Ground States of a Dipolar {{Bose}} Gas` seems exactly right.

**Comment by juhaszp95** [comment]
The journal accepts all capitalisation (and it changes from article to article), so I'm trying going with the 'as published' version. Bose would need protection either way, but protection is difficult for some edge cases as discussed in https://github.com/retorquere/zotero-better-bibtex/issues/2424.

I think the per-directory preferences will work. Just so that I understand correctly, if I set this to e.g. preferences.json, this means that BBT will look for this file in every directory that it exports to, and if found, use the overrides for the export in that directory, if not found, go with the normal settings? (I.e. multiple preferences.json could exist in multiple directories in theory with different content.)

**Comment by retorquere** [comment]
> The journal accepts all capitalisation (and it changes from article to article), so I'm trying going with the 'as published' version.

Against recommended practice, but you could get that by entering `Droplet Crystal Ground States of a Dipolar Bose Gas` in Zotero and keeping caps protection on.

> I think the per-directory preferences will work. Just so that I understand correctly, if I set this to e.g. preferences.json, this means that BBT will look for this file in every directory that it exports to, and if found, use the overrides for the export in that directory, if not found, go with the normal settings? (I.e. multiple preferences.json could exist in multiple directories in theory with different content.)

Correct. BBT does disable caching for exports where an override file is found.

**Comment by juhaszp95** [comment]
> Against recommended practice, but you could get that by entering `Droplet Crystal Ground States of a Dipolar Bose Gas` in Zotero and keeping caps protection on.

I want to keep that setting off as the way it is implemented at the moment fails in some edge cases as discussed in https://github.com/retorquere/zotero-better-bibtex/issues/2424.

I've also just tried using the preferencesOverride, but it doesn't seem to do anything to the export - see log ID 386ACL4H-refs-euc. I also attach [preferences.json](https://github.com/retorquere/zotero-better-bibtex/files/11721244/preferences.json.txt) which only has a single line, which should enable brace protection, but the exported .bib doesn't have any extra braces.

**Comment by juhaszp95** [comment]
Hello - will this new build appear here, or shall I look somewhere else?

**Comment by retorquere** [comment]
It should have dropped here, not sure what went wrong, but I've scheduled a new drop.

**Comment by retorquere** [comment]
> It should have dropped here, not sure what went wrong, but I've scheduled a new drop.

I had scheduled a drop for #2543 instead of #2534.

**Comment by juhaszp95** [comment]
I've just submitted debug log ID AAQ7MVFA-refs-euc. (This is a random entry in the export which would need to be case-protected, but the prefs.json doesn't do that for some reason.)

**Comment by retorquere** [comment]
You'll need to trigger an export before sending the log, I'm not seeing an export in `AAQ7MVFA-refs-euc`.

**Comment by retorquere** [comment]
It says there is a syntax error in `\\<server name>\<path>\preferences.json` (is it OK to name the actual server/path here?)? Can you post the contents of that `preferences.json` file here?

**Comment by juhaszp95** [comment]
I haven't specified any path (I don't think that is necessary / possible in the settings you suggested - I understood it would look for this file in the directory of export). I've already uploaded my .json here:

> I've also just tried using the preferencesOverride, but it doesn't seem to do anything to the export - see log ID 386ACL4H-refs-euc. I also attach [preferences.json](https://github.com/retorquere/zotero-better-bibtex/files/11721244/preferences.json.txt) which only has a single line, which should enable brace protection, but the exported .bib doesn't have any extra braces.

**Comment by retorquere** [comment]
Ah, I see. This isn't valid JSON:

```
{"override": "preferences": {"exportBraceProtection": true}}
```

try instead

```
{ "override": { "preferences": { "exportBraceProtection": true } } }
```

**Comment by retorquere** [comment]
> I haven't specified any path (I don't think that is necessary / possible in the settings you suggested

That is correct, but BBT uses that information to construct the full path, and I usually prefer to remove all ambiguity -- you have multiple auto-exports set up, and I want to know for sure we're talking about the same one. The path makes precise which we are talking about. But I think the previous message should do the job.

**Comment by juhaszp95** [comment]
Indeed, the updated .json solved the problem! Many thanks. I got the wrong syntax from here: 

> You can do per-directory preferences using https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#preferencesoverride. Maybe that gets you what you need?

Perhaps BBT could report the syntax error rather than ignoring it silently.

**Comment by retorquere** [comment]
> I got the wrong syntax from here:

Oops. New docs are building.

> Perhaps BBT could report the syntax error rather than ignoring it silently.

I'll think about it, but this is not easy. Zotero exports can only report back one of two things:

1. Success
2. Failure

I cannot (easily) give details about what went wrong, and a partial status (like "export completed, but the preferences.json override has an error") isn't really a thing in Zotero. So I largely have the choice between 1. ignore any problems, or 2. whatever problem occurs, treat it as a fatal problem.
