### ISSUE TITLE
[Bug/Feature]: Latex math does not show up properly with bibtex

### ISSUE THREAD

**Issue by HumpyBlumpy** [retorquere/zotero-better-bibtex#2536]
### Debug log ID

ERRT3373-refs-euc

### What happened?

Latex math enclosed in $$ (for example in titles) does not show up properly. 
For example, the exported .bib for the reference in the debug log is
```
@article{zacheDynamicalTopologicalTransitions2019,
  title = {Dynamical {{Topological Transitions}} in the {{Massive Schwinger Model}} with a \$\textbackslash ensuremath\{\textbackslash theta\}\$ {{Term}}},
  author = {Zache, T. V. and Mueller, N. and Schneider, J. T. and Jendrzejewski, F. and Berges, J. and Hauke, P.},
  year = {2019},
  month = feb,
  journal = {Phys. Rev. Lett.},
  volume = {122},
  number = {5},
  pages = {050403},
  publisher = {{American Physical Society}},
  doi = {10.1103/PhysRevLett.122.050403},
  urldate = {2022-06-24},
}
```
which does not show up properly in the latex generated document (using bibtex + revtex4.2). The title shows up with `$\ensuremath{\theta}$`. Instead of the actual symbol for \theta.

Replacing the title field with   `title = {Dynamical {{Topological Transitions}} in the {{Massive Schwinger Model}} with a $\ensuremath{\theta}$ {{Term}}},`
makes it show up properly.

**Comment by retorquere** [comment]
Zotero has no latex math support, so a dollar sign is just a dollar sign in Zotero, but you can make BBT recognize math section:

https://retorque.re/zotero-better-bibtex/exporting/scripting/#detect-and-protect-latex-math-formulas

**Comment by HumpyBlumpy** [comment]
That works. Thanks!
