### ISSUE TITLE
[Bug]: BBT does not tolerate the main window being closed and reopened.

### ISSUE THREAD

**Issue by alanzchen** [retorquere/zotero-better-bibtex#2541]
### Debug log ID

CRFCYIUX-refs-euc

### What happened?

Automatic Export was correctly set up, but after Zotero is running for a while (unknown threshold time), the automatic export would stop running. When I tried to trigger an export manually in the BBT preference window, the `Status:` would stuck at `0%` or `100%` indefinitely.

Rebooting Zotero would resolve the issue, but the same problem would appear after it runs for a while.

One of the export destinations is a git repository and have auto git push enabled if that matters.

**Comment by retorquere** [comment]
BBT does not currently tolerate the main window being closed and reopened (something that can only happen on a Mac), and I'm seeing errors in the log relating to that. The new version I'm working on for Zotero 7 should allow it, but for now, can you cmd-Q Zotero and try to recreate the problem?

**Comment by retorquere** [comment]
It's not the fault of zotero 6, this is a BBT bug that I found a fix for while I was doing the 7 port. There will be a Z6 version that has the fix, I just don't know when.

**Comment by retorquere** [comment]
I'm taking this along in #2522
