### ISSUE TITLE
[Feature]: export "standard" item type

### ISSUE THREAD

**Issue by zzxcodelife** [retorquere/zotero-better-bibtex#2543]
### Debug log ID

YBFQAFYY-refs-euc

### What happened?

A bug happened! I am using BBT in zotero. Today i found that BBT cannot export references of type "standard". I use the software 7-Zip to check zotero-better-bibtex-6.6.79.xpi. I opened the file ./content/workder/zotero.js, and after searching and comparing, I found that the "standard" item was missing in some places. Specifically: 128764 lines, 131569 lines. Refs of type "standard" will be marked as "msic". After supplementing these two omissions, the Refs marked with "standard" can be exported correctly.

The corrected codes in zotero.js are shown as follow：
**line 128764 ：**     
 types: /* @__PURE__ */ new Set(["article", "book", "bookinbook", "booklet", "collection", "inbook", "incollection", "inproceedings", "inreference", "manual", "misc", "mvbook", "mvcollection", "online", "patent", "periodical", "proceedings", "reference", "report", "set", "suppbook", "suppcollection", "suppperiodical", "thesis", "unpublished", "standard"]),
**lines 131568-131570**：
        report: "techreport",
        standard: "standard",
        statute: "misc",

**Comment by retorquere** [comment]
I'd rather know what you want the output to look like.

**Comment by retorquere** [comment]
Are you exporting to bibtex or biblatex?

**Comment by zzxcodelife** [comment]
Before I modified it, the entry of this document in the exported .bib file was: _@misc{ZhongHuaRenMinGongHeGuoGongYeHeXinXiHuaBu2016,
    title = {6kV～1000kV power transformer sound level: JB/T 10088-2016},
    author = {{Ministry of Industry and Information Technology of the People's Republic of China}},
    year = {2016},
    month = oct,
    langid = {chinese}
}_
When I complete the above modification, the entry of the document in the exported .bib file is:
_@standard{ZhongHuaRenMinGongHeGuoGongYeHeXinXiHuaBu2016,
    title = {6kV～1000kV power transformer sound level: JB/T 10088-2016},
    author = {{Ministry of Industry and Information Technology of the People's Republic of China}},
    year = {2016},
    month = oct,
    langid = {chinese}
}_
Their difference lies in the change of document type mark.

**Comment by retorquere** [comment]
That's bibtex though. Bibtex doesn't know a `@standard` entry type. If you export as biblatex, it will already export as `@standard`.

**Comment by zzxcodelife** [comment]
oh, I see. Thank you!
