### ISSUE TITLE
[Feature]: Don't export file field

### ISSUE THREAD

**Issue by juhaszp95** [retorquere/zotero-better-bibtex#2547]
### Debug log ID

LECQGYLX-refs-euc

### What happened?

Hello,

I'm exporting a collection as a .bib file to use it with a paper (co-authored with other people). The .bib file itself has a 'file' field with a .pdf file mentioned in it, including its full path. This is not useful information for generating citations in LaTeX, but more importantly I would not like to reveal my folder structure to the outside world (as this eventually gets submitted). Is there a way to prevent BBT from including that 'file' field in the export?

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/export/#fields-to-omit-from-export-comma-separated

**Comment by juhaszp95** [comment]
Ah, I haven't realised this - thanks!
