### ISSUE TITLE
Zotero online citation keys are not synched to the local db

### ISSUE THREAD

**Issue by srjmas** [retorquere/zotero-better-bibtex#2549]
### Debug log ID

YYRP45FM-refs-euc

### What happened?

My workflow is to write in overleaf with link to online zotero.org and to manage citations on my laptop with the zotero software.
When I copy the citation key from the software with ctrl+shift+C it follows a different pattern than what I see from inside overleaf or .bib files I export from the website.

My workaround:

1) Tools->Better Bibtex preferences -> citation key formula :
auth.lower +'_'+ shorttitle(1,1).lower + '_'+year
2) Select the citation to export, right click -> Better BibTex -> refresh BibTex key
3) ctrl+shift+C to copy a key that matches what I see in overleaf

It feels messy and error inviting, is there a better way to resolve it?

**Comment by retorquere** [comment]
Select all your items in Zotero, right-click, better bibtex, pin citation keys, and then set https://retorque.re/zotero-better-bibtex/installation/preferences/#automatically-pin-citation-key-after to a non-zero value. After that, all your citation keys are automatically written to the `extra` field, and citation keys written in the `extra` field will be used as the keys on Overleaf.

**Comment by srjmas** [comment]
Thank you all works!
