### ISSUE TITLE
[Bug]:  Preferences panel doesn't open anymore

### ISSUE THREAD

**Issue by charveey** [retorquere/zotero-better-bibtex#2552]
### Debug log ID

H37T7ZG6-euc

### What happened?

I can't access BBT Preferences panel anymore
```
XML Parsing Error: undefined entity
Location: chrome://zotero-better-bibtex/content/Preferences.xul
Line Number 208, Column 19:                  <checkbox preference="extensions.zotero.translators.better-bibtex.bibtexEditionOrdinal" label="&better-bibtex.Preferences.export.fields.bibtexEditionOrdinal;"></checkbox>
------------------^
```

**Comment by retorquere** [comment]
The French translations hadn't synced. A new release build should be out in 30 minutes or so.

**Comment by Saidelocha** [comment]
Same problem here

**Comment by retorquere** [comment]
That makes sense because I didn't specifically target @charveey with this build. The file is missing for all French users. A release build is scheduled, but there are unrelated errors in the release build which block the release that I am addressing now.

**Comment by charveey** [comment]
Thank you @retorquere I'll patiently wait for the fix. I can still downgrade if I need to access preferences in the meantime.
