### ISSUE TITLE
[Bug]: New BetterBibTex update stopped exporting doi field

### ISSUE THREAD

**Issue by HumpyBlumpy** [retorquere/zotero-better-bibtex#2554]
### Debug log ID

L5IDKQT3-refs-euc

### What happened?

Hi,

After the newest update of BetterBibTex, my automatic exports into .bib files stopped exporting the doi field. 
Previous versions worked fine.

**Comment by retorquere** [comment]
That dropped out by mistake, a new build is running through the test suite that adds it back, but `doi` isn't a field bibtex supports; `doi` is a biblatex field.

**Comment by HumpyBlumpy** [comment]
Well I noticed my references dont have a link whereas they used to. I am using Revtex4.2 with bibtex. The only change I then noticed was the lack of doi.

**Comment by retorquere** [comment]
Build is running to restore that

**Comment by HumpyBlumpy** [comment]
Thanks, I think that works. I'm guessing revtex does something with the doi field despite bibtex then
