### ISSUE TITLE
[Bug]: DOIs excluded from export in 6.7.86 

### ISSUE THREAD

**Issue by philipmgrant** [retorquere/zotero-better-bibtex#2555]
### Debug log ID

WPZZZZKZ-refs-euc

### What happened?

After upgrading to version 6.7.86, exported .bib files no longer include the `doi` field.

On version 6.7.79 with identical settings and library items, the `doi` field was included as expected. See the attached pair of files for a minimal example.  (They're .bib files: I added a .txt extension because Github requires it.)
[6_7_86.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/11947109/6_7_86.bib.txt)
[6_7_79.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/11947110/6_7_79.bib.txt)

My export preferences are set to "both" for items with both DOI and URL. (But in any case, on 6.7.86 the DOI is missing even for items with no URL.)
![preferences](https://github.com/retorquere/zotero-better-bibtex/assets/46570855/a6ebfb30-c648-47f9-8bfa-3ff4eab2e124)

**Comment by retorquere** [comment]
Oh .88 didn't release. On it.

**Comment by philipmgrant** [comment]
That's working correctly for me with the test build now. Thanks very much for the quick fix!

**Comment by retorquere** [comment]
Thanks for reporting it. .91 is out, but it's just a rebadged .4525. You can request an upgrade manually or wait for a day or two until Zotero checks for updates.
