### ISSUE TITLE
[Bug/Feature]: journal abbreviation when generating citationkey

### ISSUE THREAD

**Issue by bigwork-easydone** [retorquere/zotero-better-bibtex#2572]
### Debug log ID

GWN2AZ9W-refs-apse

### What happened?

Hi! I am reaching out to you regarding an issue I am facing with citation key generation. The debug log ID is `GWN2AZ9W-refs-apse`.

Taking the journal Information System Research as an example to illustrate the problem I'm facing, 
- when I use the formula `auth.lower + year + journal(abbrev="abbrev+auto")`, the citation key is `koh2022Inf.Syst.Res.`; 
- when I use the formula `auth.lower + year + journal(abbrev="auto")`, the citationkey is `koh2022Inf.Syst.Res.a`; 
- when I use the formula `auth.lower + year + journal(abbrev="abbrev")`, the citationkey is `koh2022InformationSystemsResearch`. 
These results show that the journal ISR does not have an explicit abbreviation, and the auto filter abbreviated it as `Inf.Syst.Res.`. 

BUT, I hope the citation key can be `koh2022ISR`, namely using the combination of author name, year, and first letter of each word in the journal title. but I do not know how to achieve this, Could you help me? Thank you very much.

**Comment by retorquere** [comment]
Does `PublicationTitle.abbr` work for you?

**Comment by bigwork-easydone** [comment]
Very magical. It's exactly what I want. Thank you a lot!
