### ISSUE TITLE
[Bug]: Auto-Export ignores DOI/URL settings

### ISSUE THREAD

**Issue by sraedler** [retorquere/zotero-better-bibtex#2573]
### Debug log ID

2VVNI3MR-euc

### What happened?

Prior to the current update (and possibly 1 or 2 other versions), the DOI/URL export option of the automatic export worked.
Now, regardless of the setting, it always outputs URL and DOI.

![image](https://github.com/retorquere/zotero-better-bibtex/assets/11181512/25d8d1f4-b334-4bea-a062-54ebf03fde41)

**Comment by sraedler** [comment]
In Version [6.7.79](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.79) it is works.

**Comment by puppe** [comment]
The setting “Export unicode as plain-text latex commands” seems also to be ignored. Could both issues be related?

**Comment by retorquere** [comment]
@puppe that is a different problem, please open a new issue.

**Comment by retorquere** [comment]
@sraedler can you right-click one of the entries where the problem occurs and send a BBT debug log for that (it will have `-refs-` in the ID.

**Comment by sraedler** [comment]
Sorry, that was my mistake in the description! It's in the Auto-Export.

With the manual export, it works.
Shall I do anything else and upload a BBT debug log?

**Comment by retorquere** [comment]
No that's fine, you did everything right, I just want to use the actual item you experience the issue with in my test case for preventing regression. If you right-click one of the items that exhibits the problem and select BBT - send debug log from the menu I get sent a copy of the item.

**Comment by sraedler** [comment]
I experienced, if export -> Fields -> "... DOI and URL..." is set to DOI, auto-export is working correctly.

The Debug-Token: CSFNZ7BD-euc

**Comment by retorquere** [comment]
Thanks, but that's a debug log sent from the help menu. Please right-click the zotero item, and from the popup menu, select better bibtex - send debug log. The ID will have `-refs` in it. I think I have the issue reproducible, but I'd like to make sure I'm covering your case.

**Comment by retorquere** [comment]
Yes, thanks! Sorry for being such a stickler about this but I have had a fair number of instances where I thought I had solved the problem only to find out the problem was subtly different from what I thought it was.

**Comment by retorquere** [comment]
I have it reproducible.

**Comment by retorquere** [comment]
4678 should fix the problem (I have a covering test), would appreciate confirmation.

**Comment by sraedler** [comment]
I can confirm that the test build is working!
Thanks for fixing it!
