### ISSUE TITLE
[Bug]: Underscores are escaped in DOI, but it's a verbatim field

### ISSUE THREAD

**Issue by philipmgrant** [retorquere/zotero-better-bibtex#2575]
### Debug log ID

2ILWVKPS-refs-euc

### What happened?

If the DOI field in Zotero contains an underscore, it is escaped to `\_` in the export. But DOI is a verbatim field, so this results in a literal backslash appearing in bibliography output in LaTeX.

The example file and bug log were generated by 6.7.94, but this looks like it has been an issue since 6.7.91. The behaviour was correct (no escape character) in 6.7.79 and earlier.
[6_7_94.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/12062001/6_7_94.bib.txt)
[6_7_79.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/12062002/6_7_79.bib.txt)

**Comment by retorquere** [comment]
Are you exporting as bibtex or as biblatex? They're verbatim fields for biblatex. Bibtex doesn't know about doi fields and will treat them as non-verbatim by default. But it's possible to force bbt to export dois as verbatim for bibtex by editing the `verbatimFields` hidden property and changing `biblatex.doi` into just `doi`.

**Comment by retorquere** [comment]
That's bibtex in those samples, not biblatex.

**Comment by philipmgrant** [comment]
Right, it does look like what bibtex does with underscores is undocumented and quirky (e.g. https://github.com/retorquere/zotero-better-bibtex/issues/532).

The fix to the hidden property gets me back to the previous behaviour with no escaping though, so that works for me!

**Comment by MatthiasLohr** [comment]
Running into the same issue.

> The fix to the hidden property gets me back to the previous behaviour with no escaping though, so that works for me!

@philipmgrant, which hidden property are you referring to?

**Comment by retorquere** [comment]
I got a mail-in about non-verbatim dois breaking bibtex compilation. Maybe a made the wrong call I changing the default. I don't know.

**Comment by MatthiasLohr** [comment]
Me neither ;) Just saw in my git diff, that many lines of my bibtex file have changed without actually having me changed something in Zotero... that got my attention, then I found this issue.

**Comment by philipmgrant** [comment]
> I'm using BibTeX with the natbib package and am now also getting undesired escaped backslashes in the bibliography section of the compiled pdfs. It was working fine until a few days or weeks ago.

Here's how the previous behaviour can be restored:

In "about:config" (accessed in Zotero from Edit >> Preferences >> Advanced >> Config Editor), find the preference called `extensions.zotero.translators.better-bibtex.verbatimFields`. This is a comma-separated string: edit it to just change `biblatex.doi` to `doi`.

**Comment by retorquere** [comment]
I am going to restore the default to what it was before.
