### ISSUE TITLE
[Bug]: "Export unicode as plain-text latex-commands" is ignored in auto-exports

### ISSUE THREAD

**Issue by puppe** [retorquere/zotero-better-bibtex#2578]
### Debug log ID

D850971117

### What happened?

Starting with version 6.7.86, the setting “Export unicode as plain-text latex-commands” for BibLaTeX export is ignored. The exact same file is produced with or without enabling the setting. I confirmed this with diff. This bug affects version 6.7.93 and 6.7.94 as well. I have worked around this issue by downgrading to 6.7.79 and disabling automatic updates for the time being.

The debug log has been produced with version 6.7.86 byfollowing these steps[^1]:

1. Click on Hilfe -> Logging des Debug-Outputs -> Aktivieren.
2. Click on Werkzeuge -> Better BibTeX -> Open Better BibTeX preferences.
3. Switch to tab “Automatic Export”.
4. Select the automatic export that is affected (a Better BibLaTex export with “Export unicode as plain-text latex-commands” enabled).
5. Click on “Export now”.
6. Close the preferences window.
7. Submit the debug log.

Maybe notable: After I click on “Export now”, the percentage next to “Cached:” remains at “50%”. It goes up to “100%” immediately when I turn off the setting in question. In version 6.7.79, it first shows “50%” and then eventually shows “100%”.

[^1]: Instead of guessing at the original English terms, I use the German labels that I actually see for some of the UI elements.

**Comment by puppe** [comment]
Sorry, here‘s the correct log ID: YAZSNWAK-euc.

The debug log has been produced with version 6.7.86 byfollowing these steps[1](https://github.com/retorquere/zotero-better-bibtex/issues/2578#user-content-fn-1-baf384cd5a9d1678375b0771984ce31c):

1. Restart with logging enbaled.
2. Click on Werkzeuge -> Better BibTeX -> Open Better BibTeX preferences.
3. Switch to tab “Automatic Export”.
4. Select the automatic export that is affected (a Better BibLaTex export with “Export unicode as plain-text latex-commands” enabled).
5. Click on “Export now”.
6. Close the preferences window.
7. Submit the debug log.

**Comment by retorquere** [comment]
I will need a `-refs-` log, generated by the steps from option `1.` above.

**Comment by puppe** [comment]
SVJN2DBI-refs-euc

**Comment by retorquere** [comment]
4681 should fix the problem (I have a covering test), would appreciate confirmation.

**Comment by puppe** [comment]
Can confirm, that this fixes the original issue.

But it introduced new issues. I can‘t change the settings on automatic exports anymore. They are there for a split second and then they disappear. It‘s also difficult to select automatic exports from the dropdown menu. It sometimes becomes unresponsive and I have to click outside of the menu to close it. I made a screen recording:

https://github.com/retorquere/zotero-better-bibtex/assets/1393865/19e5dc9a-06fd-448f-b556-a64e648beeeb

I also activated logging and tried selecting automatic exports again. ID: XE7NX9W5-euc

**Comment by puppe** [comment]
Maybe also of note: Do you see that the entries in the menu say “undefined (Better BibLaTeX) […]”? In other versions of BibLaTeX they are labeled “Meine Bibliothek (Better BibLaTeX) […]”.

**Comment by retorquere** [comment]
Can you try build 4696?

**Comment by puppe** [comment]
Works perfectly now!

The only thing I notice is that “Cached” now permanently says “? %”. Don‘t know if that‘s an issue, or what it even means.

**Comment by retorquere** [comment]
I have that reproducible. On it.

**Comment by puppe** [comment]
Looks good. The cache rate is now displayed correctly.
