### ISSUE TITLE
[Feature]: Ignore File-path on export

### ISSUE THREAD

**Issue by sraedler** [retorquere/zotero-better-bibtex#2579]
### Feature-Description

The export function exports the "file-path" in Bibtex files.
This option has no advantage for collaborative projects and also not for me as a user.
An option to suppress this export would be helpful to make the Bibtex file clearer. Especially for long paths.

@retorquere BTW, it is not possible to submit a feature request without passing a Debug-Log key. Therefore, the github-action below occurs even if not applicable.

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/export/#fields-to-omit-from-export-comma-separated

**Comment by retorquere** [comment]
> BTW, it is not possible to submit a feature request without passing a Debug-Log key. Therefore, the github-action below occurs even if not applicable.

The text above explains why people who think it is not applicable to them are usually wrong. So the answer is "no".
