### ISSUE TITLE
[Feature]: Add support for Zotero automatic rename to citekey

### ISSUE THREAD

**Issue by tomhaley** [retorquere/zotero-better-bibtex#2583]
### Debug log ID

5SUNJRIB-refs-euc

### What happened?

Zotero 7 added built-in capability to automatically rename files when attaching them. It would be great to be able to use the citekey as the filename; Zotfile included this capability but still seems unlikely to come to Zotero 7.

**Comment by retorquere** [comment]
The formatting of the filename from `attachmentRenameFormatString` happens in a way that is not feasible to augment unfortunately.
