### ISSUE TITLE
[Bug]: Quick copy export ignores fields to omit

### ISSUE THREAD

**Issue by jryans** [retorquere/zotero-better-bibtex#2585]
### Debug log ID

ZZCAQUWM-refs-euc

### What happened?

In recent versions of BBT / Zotero, the Export -> Fields -> Fields to omit setting appears to be ignored.

BBT version: 6.7.94
Zotero version: 6.0.26
macOS 13.4.1

## Steps to reproduce

1. Set some fields to ignore
2. Export to BibTeX via quick copy (Cmd-Shift-C)

## Expected

The fields to omit should be omitted.

## Actual

All fields appear to be included in the export.

**Comment by retorquere** [comment]
You have the quick-copy translator set to `BibTeX`, not `Better BibTeX`.

**Comment by jryans** [comment]
Oh my, how embarrassing! Indeed, changing it back fixes things. 😅 

Thanks for all of your work on BBT! 😄
