### ISSUE TITLE
Feature:  keyboard shortcut for Change BibTex Key

### ISSUE THREAD

**Issue by notuntoward** [retorquere/zotero-better-bibtex#2594]
### Debug log ID

7HKA8UB8-refs-euc

### What happened?

The autogenerated citekeys that BetterBibTex makes are a good start, but since they're often too long, or are missing key words, I almost always edit them.  

Would it be possible to add a keyboard shortcut for editing the key?  

Since editing is such a frequent operation, the right click and mouse method of getting to the citekey editor is a little too involved.

**Comment by retorquere** [comment]
Zutilo does shortcuts for Zotero; if they call `Zotero.BetterBibTeX.KeyManager.set()`, you get the same popup.

The beta version I'm prepping for the Zotero 7 beta (progress is tracked on #2522) will allow direct editing in the item pane.

**Comment by notuntoward** [comment]
Thanks for the answer.  Which of the zotilo options call `Zotero.BetterBibTex.KeyManager.set()`?  In the zotilo preferences shortcut pane, I see the following:

<img width="254" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/3851891/13fc6325-1d98-4246-b5e1-32da97057df9">

**Comment by retorquere** [comment]
You'll have to ask the Zutilo developer whether he wants to add this as a new action. But as I said, the next version will have direct editing of the citation key. The set popup might go away entirely at that point.
