### ISSUE TITLE
[Bug/Feature]: %b in ZotFile Renaming Rules no longer returns BBT citation key

### ISSUE THREAD

**Issue by pou2** [retorquere/zotero-better-bibtex#2597]
### Debug log ID

DILCEQ73-refs-euc

### What happened?

I use ZotFile to rename files when they are imported. The Renaming Rule I have always used without issue is {%b}, which, until today, would return the reference's BBT citation key. Now, instead of being renamed to, e.g., "2005_Li_Macromolecules_6767.pdf", the file will be named "pdf". Please let me know if there is any additional information I can provide.

**Comment by retorquere** [comment]
You'd have to ask the Zotfile developer. If he can diagnose the problem I can see what I can do on my end.

**Comment by pou2** [comment]
Yeah, as soon as I made the comment I realized I needed to probably go that route, sorry for the premature trouble. I had reached out here first because I saw that BBT had just been updated whereas ZotFile had not been updated since last year, but I think what you suggest still makes the most sense. Thanks!

**Comment by retorquere** [comment]
Ah I see what the problem is -- I've submitted a PR to ZotFile.

**Comment by notuntoward** [comment]
I'm seeing the same filename of 'pdf'.  In addition, when I export a collection with "export files" clicked (screenshot 1),   I get an error popup saying it can't export the "selected file," but I have no files selected (screenshot 2).  I believe that was working yesterday or the day before.

![image](https://github.com/retorquere/zotero-better-bibtex/assets/3851891/0508ff2a-7c0a-44fa-9037-912308f24aab)
![image](https://github.com/retorquere/zotero-better-bibtex/assets/3851891/10d7dfe2-9a37-4e9a-8144-f6679bf2407d)

**Comment by retorquere** [comment]
@notuntoward the "in addition" is something entirely different than #2597, please open a new issue.
