### ISSUE TITLE
Bug: Z7 background export box reverts to unchecked

### ISSUE THREAD

**Issue by warwickmm** [retorquere/zotero-better-bibtex#2598]
### Debug log ID

V9V65QGB-euc

### What happened?

Upon checking "Keep updated" when exporting a library, the "Background export" checkbox is automatically checked.  However, upon revisiting the menu, the "Background export" checkbox is unchecked.

Steps to reproduce:
1. Right-click on My Library -> Export Library... -> select Better BibTeX
2. Check "Keep updated".  If it's already checked, uncheck and check again.
3. Notice that "Background export" is automatically checked.
4. Proceed with the export.
5. Right-click on My Library -> Export Library... -> select Better BibTeX.
6. Notice that "Background export" is now unchecked.

This was originally reported [here](https://github.com/retorquere/zotero-better-bibtex/issues/2522#issuecomment-1661290939).

**Comment by retorquere** [comment]
reproducible

**Comment by retorquere** [comment]
I found and fixed it; if you are still experiencing it, please open a new issue.
