### ISSUE TITLE
[Bug/Feature]: Latest update (6.7.96) is broken

### ISSUE THREAD

**Issue by madhusudansingh** [retorquere/zotero-better-bibtex#2599]
### Debug log ID

D2088420714

### What happened?

Platform: Linux
Zotero version (standalone): 6.0.26

Better biblatex does not start up (saw the usual flash message at the bottom right but did not pay attention to it). Preferences are not loaded. Perpetual message "Better BibTeX is loading" upon clicking "Open Better BibTeX preferences ...".

There is no right click Better Biblatex menu. I generated and submitted a Zotero debug log. There is no "Send Better BibTeX debug report ..." menu since Better BibTeX did not load in the first place!

Needless to say, latex keys are also not showing, which makes this a showstopper.

Under Add ons, the version showing is Better BibTex for Zotero 6.7.96 dated today. So, I am running both Zotero and Better BibLaTeX with the latest versions.

Restarting did not help the two times I tried it.

I am hoping that this is some kind of a weird cache issue that cropped up from closing a window too early.

**Comment by madhusudansingh** [comment]
The issue auto resolved after a few restarts.

**Comment by retorquere** [comment]
But that's not supposed to be necessary.

Without a log I can't do anything though. I am not experiencing this problem, so I have no leads on what the cause could be. 6.7.96 passes all the tests I have.

When BBT fails to start up, there will be a "Send debug log to file.io" in the Help menu, you can use that should it happen again.

**Comment by retorquere** [comment]
If you experience this again, you can comment here, and the issue will automatically reopen.

**Comment by Mela** [comment]
I was experiencing most likely the same problem just a moment ago.
Looks like Better BibTeX hung on loading "object serializer". 

Restarted Zotero: error returned. 
- Disabled Better BibText, 
- Zotero restart
- re-enabled Better BibText
- Zotero restart: now Better BibTeX fully loaded again. 

![Bildschirmfoto 2023-08-02 um 23 30 15](https://github.com/retorquere/zotero-better-bibtex/assets/361364/274e5b8d-d018-4767-aa50-223e3ab31f43)

**Comment by retorquere** [comment]
Without a debug log I cannot do anything with this information. **Better BibTeX passes the entire production-level test suite** before a build is released, so you are pretty much guaranteed I am not experiencing the same problem, and without a debug log I can only guess at what is different about your system.

**Comment by retorquere** [comment]
If you experience the problem again, please send a debug log. The issue will automatically reopen.
