### ISSUE TITLE
[Bug/Feature]: UI bug in citation key formula input

### ISSUE THREAD

**Issue by postylem** [retorquere/zotero-better-bibtex#2600]
### Debug log ID

YPCIJ9X5-refs-euc

### What happened?

UI issue on macOS:
When inputting citation key formula, the inputted text is wrapped into a narrow part of the left side of the input box rather than using all available space. 

![Citation Keys window](https://github.com/retorquere/zotero-better-bibtex/assets/5202957/def3f8c6-a295-444a-939c-d62ab7a3c875)
(Settings > BetterBibTeX > Open Better BibTeX preferences... > Citation Keys)

The text box is about 600px wide, but it behaves as if it were only about 180px wide (see scrollbar in image, and text wrapping). 
This is a UI issue, not a bug with the functionality (afaict no issue with the citation key formula, it just is hard to see what you're doing :). 

--
macOS v13.4.1 (c) 
Zotero v6.0.26
BBT v6.7.96

**Comment by retorquere** [comment]
Yeah, UI is not my specialty, and the technology that is available in Zotero to build the UI is pretty janky. Zotero 7 will make some of these things better. A build will drop here in a bit that will fix it, but strangely enough you need to resize the text box to see the controls at the bottom. As I said, pretty janky. Fortunately it looks like 7 will drop soon.

**Comment by postylem** [comment]
This build fixes the issue indeed. But I see what you mean about needing to resize the text box to see controls.  

<img width="659" alt="Screenshot 2023-08-05 at 07 52 31" src="https://github.com/retorquere/zotero-better-bibtex/assets/5202957/44f28588-793c-4dc1-8d5c-507f70c8af51">
