### ISSUE TITLE
[Bug]: "better bibtex: translators" does not complete on large library

### ISSUE THREAD

**Issue by vancleve** [retorquere/zotero-better-bibtex#2602]
### Debug log ID

none available; clicked "send debug log to file.io"

### What happened?

On BBT, [test build 6.7.96.2522.4784](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.96.2522.4784.xpi) with a library of +19k items with PDFs, BBT fails to complete loading and is stuck at
<img width="183" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/1442334/1e2da099-35b3-4fcc-b5ec-e3898bb82787">

I have clicked "send debug log to file.io". I do not receive any output after selected that menu item.

Is there more debug info I can provide?

Zotero: 7.0.0-beta.26+6dcc70f53

**Comment by vancleve** [comment]
Here is the log file

[zotero_bbt_debug_vancleve.txt](https://github.com/retorquere/zotero-better-bibtex/files/12244081/zotero_bbt_debug_vancleve.txt)

**Comment by vancleve** [comment]
I receive the following error trying to install [test build 6.7.97.2602.4793](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.97.2602.4793.xpi)

<img width="480" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/1442334/08d4790e-31f3-4d02-a54c-9763ed9f9f00">

**Comment by retorquere** [comment]
That could be [this](https://groups.google.com/g/zotero-dev/c/Xg1XIT3HDP0/m/UirR3nwbEwAJ) which would make it a Zotero bug; if that is the case, please report it on their [forum](https://forums.zotero.org). If it is, a re-install of the same XPI shoudl re-enable BBT.

**Comment by retorquere** [comment]
sorry, that is my fault. I'll get you a fixed build.

**Comment by nathancashion** [comment]
I'm having the exact same problem. I've installed the test build above and tried to submit a debug file but "Send Better BibTeX debug report..." does not appear in the help menu.

I sent it to file.io, debug ID: D872777689

I cannot open BBT preferences. I just see a window that says "Better BibTeX is loading"

![Screenshot 2023-08-02 at 10 04 41 PM](https://github.com/retorquere/zotero-better-bibtex/assets/67849068/b79687ff-f3e2-4c77-b337-8693828927f2)

**Comment by retorquere** [comment]
That is a zotero debug id. I have no access to those. If you send to file.io the ID will have a dash.

**Comment by iGormilhit** [comment]
Had the same issue. Tried the test build ([this comment](https://github.com/retorquere/zotero-better-bibtex/issues/2602#issuecomment-1663058019)) and then the startup process succeeded. Thanks.

**Comment by retorquere** [comment]
@iGormilhit if you can reproduce this for a recent build I'd be much helped with a debug log.

**Comment by vancleve** [comment]
BBT seems to be loading very fast now with [test build 6.7.98.2602.4812](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.98.2602.4812.xpi)! No more getting stuck no translators. Thanks!

Just in case its helps, here is a log file ID: AQLUMFL9-euc
