### ISSUE TITLE
Citation key does not appear after install

### ISSUE THREAD

**Issue by ms609** [retorquere/zotero-better-bibtex#2604]
Hi,

I love the new integration of the Citation Key field – much more convenient than the previous implementation!

One issue however is that when I am editing other fields in a citation, pressing <kbd>Tab</kbd> sends the cursor to the Citation Key field.  Thus it is no longer possible to navigate between fields using the keyboard.

Debug log ID: `L99SBW8H-euc`

Thanks for your work on this invaluable plugin!

**Comment by ms609** [comment]
Addendum: I just installed Zotero 7 and the devel build of Better Bibtex and the issue persists.

**Comment by retorquere** [comment]
Reproducible. I have a question about this outstanding with the Zotero team.

**Comment by retorquere** [comment]
6.7.100 is out which should fix the problem.

**Comment by ms609** [comment]
Thanks: I installed v6.7.101 and restarted Zotero.

Tabbing now works as expected among regular citation fields.

But...

- When I launch Zotero the Citation Key field is not visible
- When I disable and re-enable the BB addon, the Citation Key field appears, but is disabled. The text is greyed out, and I can highlight the text but cannot place the cursor in the box or edit the contents.

**Comment by retorquere** [comment]
> Thanks: I installed v6.7.101 and restarted Zotero.
> 
> Tabbing now works as expected among regular citation fields.
> 
> But...
> 
>     * When I launch Zotero the Citation Key field is not visible

And this is reproducible for you? A build will drop here in 10 minutes that adds more logging, if you can reproduce, please send a log right after it has happened.

>     * When I disable and re-enable the BB addon, the Citation Key field appears, but is disabled. The text is greyed out, and I can highlight the text but cannot place the cursor in the box or edit the contents.

I've reverted to the previous behavior, I've talked to the Zotero crew, and plugin-added editable fields are not feasible right now. Zotero 7 will get a supported way to do that, but for Zotero 6, an editable citekey field is not possible.

**Comment by ms609** [comment]
Yes, reproducible.  On 6.7.103:

- Log immediately after launching Zotero and selecting a citation: `WLNCUKVE-euc`
  - Citation Key field not displayed
- Log after toggling Better Bibtex off then on again: `3T9XUVM8-euc`
  - Citation Key field now visible (not editable)

**Comment by retorquere** [comment]
>     * Log immediately after launching Zotero and selecting a citation: `WLNCUKVE-euc`
>       
>       * Citation Key field not displayed

I haven't been able to reproduce it. A new build will drop here soon with a potential fix, and more logging. If it's not fixed, please submit a new log.

>     * Log after toggling Better Bibtex off then on again: `3T9XUVM8-euc`
>       
>       * Citation Key field now visible (not editable)

No need to report this. The citation key is going to have to be read-only for Zotero 6. Having it editable messed with the other item fields in the item pane. Zotero 7 will soon add a way that I can have it editable there.

**Comment by ms609** [comment]
The issue persists: `3AS5C2UX-euc`

**Comment by ms609** [comment]
The issue persists:  `V4FASI99-euc`

**Comment by retorquere** [comment]
You have switched to Zotero 7, `L99SBW8H-euc` is from Zotero 6, so that's what I thought we were diagnosing. Zotero 7 support is tracked in #2522. Currently it is not possible to display the citation key in Zotero 7, the Zotero team is working to make it possible (see top of #2522).

**Comment by ms609** [comment]
Sorry for the confusion – since I installed Zotero 7 I've been using that version exclusively.  

In that case v6.7.103.2604.4836 is behaving as we expect: Citation Key field is never visible, but the key can be edited (I now see) via the context menu.  That configuration works fine for now, and I'll look forwards to enjoying the new behaviour once you are able to take advantage of the forthcoming Zotero 7 API.

Thanks for your help diagnosing this issue, and thanks again for the excellent plugin!

**Comment by jrennstich** [comment]
Debug Log from 4845: DCZTD3XH-euc/6.7.103.2522.4845-7

**Comment by retorquere** [comment]
Citation key cannot be displayed in Zotero 7 until the Zotero team makes the new API available.

**Comment by jrennstich** [comment]
Ok. Just wanted to send a debug log for information purposes, since the message read "debug log version" and I figured, you were interested in debugs :-)

**Comment by retorquere** [comment]
No worries. I expect the item field API somewhere this or next week.
