### ISSUE TITLE
[Bug/Feature]: Better Bibtex breaks Zotero in Ubuntu 22.04

### ISSUE THREAD

**Issue by alosferrer** [retorquere/zotero-better-bibtex#2610]
### Debug log ID

NA

### What happened?

After installing Better Bibtex 6.7.104 on a freshly-installed Zotero 6.0.26 in a freshly-installed Ubuntu 22.04.02 LTS and restarting, the library does not show up. Collections are not clickable. The middle panel is empty. The right panel is replaced by a "better bibtex: user interface", which is also empty. I cannot generate a BBT debug log because there is no reference to be seen at all if BBT is enabled, and references are only back if BBT is disabled. Disabling Better bibtex and restarting, the library is back.

Here is a screenshot. I just had added one collection ("Stochastic Choice") with 12 references in it before installing Better Bibtex.

![ScreenshotBBT](https://github.com/retorquere/zotero-better-bibtex/assets/107697433/f75bbb8c-5a2f-479f-a0c7-4033b5ade4f9)

Help would be highly appreciated.

**Comment by alosferrer** [comment]
Debug ID: D371692463

The issue does not relate to specific references. I restarted with logging enabled and sent the debug output. However, the option "Send better BibTex debug report" did not appear under "Help."

Note: The first time I restarted with logging enabled, the problem did not reproduce, i.e. the references were visible again and BBT options appeared in the context menus. The second time it did reproduce, i.e. all references were gone. I sent the debug output then.

**Comment by retorquere** [comment]
I can't read those, those go to the zotero team. If there isn't a "send better bibtex debug log", there will be a "send to file.io" entry in the help menu. I can read either of those, with a preference for the former.

**Comment by alosferrer** [comment]
Thank you very much for looking into this. I reproduced the problem again. There is still no "send better bibtex debug log", so I am unable to do that. I did send "to file.io" now, the ID is tPm9vTR55HKU-67GVT88Q . I am also attaching the saved Debug output as txt.

[DebugOutput.txt](https://github.com/retorquere/zotero-better-bibtex/files/12269164/DebugOutput.txt)

**Comment by retorquere** [comment]
It will be a few hours before I can actually look at it, I'm traveling currently.

**Comment by alosferrer** [comment]
No problem, thanks again and safe travels.

**Comment by retorquere** [comment]
A build will drop in a few minutes that should offer temporary relief while I work on a more permanent solution. I don't know why this hit you (I can't yet reproduce it) but it's something that needed changing anyhow.

**Comment by alosferrer** [comment]
Many thanks for this. I have installed the build and restarted several times. I confirm that the previous issue is gone and BBT seems to be working as expected. This is great. I will start using it now. Thank you!

**Comment by retorquere** [comment]
Can you still add the citation key to the middle column? The better fix I mentioned earlier is already in this build, but I've also added a safeguard which will skip adding the column if an error occurs (which is the proxy problem you experienced).

**Comment by alosferrer** [comment]
I just tried it and it seems to work. Is this what you mean (see screenshot)?
![ScreenshotBBT2](https://github.com/retorquere/zotero-better-bibtex/assets/107697433/224e1261-8a95-4eac-a21d-da0c7b9cc110)
I also restarted Zotero (sicne the previous problem appeared after restart) and the CitationKey column is still there.

**Comment by retorquere** [comment]
That's what I mean indeed - great, then the fix I applied actually solves the problem. It's work I had planned anyhow.

**Comment by alosferrer** [comment]
Many thanks again! Very much appreciated.
