### ISSUE TITLE
[Bug]: Language Code is not Recognized

### ISSUE THREAD

**Issue by 2017MK2017** [retorquere/zotero-better-bibtex#2611]
### Debug log ID

No

### What happened?

When using language codes as recommended by Zotero (de-DE), Better Bibtex does not recognize* them and thus applies title casing to "de-DE" items.

> We recommend storing these as two letter ISO language codes followed by two letter ISO country codes (e.g., en-US for American English, or de-DE for German). ([Zotero Documantation](https://www.zotero.org/support/kb/item_types_and_fields#general_fields))

---

Side note: Using "ger" works fine.

---

\* Even worse: Better Bibtex does not only not understand "de-DE" (i.e., interpret it as an unknown language), it completely ignores the input (i.e., deletes it).
This can be verified because the langid-bibtex-field is empty and if it wouldn't be deleted, title casing should not have been applied, because (taken strictly) the following does not hold for an unknown language.

> English items, as far as BBT is concerned, are those items that have their language explicitly set to an English language (american counts as English for example), and those items that have no explicit language set. ([Better Bibtex FAQ](https://retorque.re/zotero-better-bibtex/support/faq/#bbt-is-changing-the-capitalization-of-my-titles----why))

**Comment by retorquere** [comment]
What the... why would you post "no" instead of making a few mouse clicks?!?

The above bot post explains is all. If you post a debug log the issue will automatically reopen.

**Comment by 2017MK2017** [comment]
Must have been my bad. It is working now. I might have opened the file faster than Better Bibtex saved it.

**Comment by retorquere** [comment]
Or maybe you saved it using the standard Zotero BibTeX exporter?

**Comment by 2017MK2017** [comment]
I am using auto export and waited for Better Bibtex to be done (top right status [after the delay]).

**Comment by retorquere** [comment]
But then I don't know how you got some output and not the entire output. BBT auto exports are atomic, they don't build bit by bit.

**Comment by 2017MK2017** [comment]
I just opened the file faster than BBT saved it.

**Comment by retorquere** [comment]
I don't really think that's the explanation, but if what you have works, that works for me.

**Comment by 2017MK2017** [comment]
I think I did not really waited till Better Bibtex was done. So I opened the file before the auto update was done.

**Comment by retorquere** [comment]
But then the behavior would not have differed around the handling of the language field.
