### ISSUE TITLE
[Bug]:  BBT sentence case does not work

### ISSUE THREAD

**Issue by MavropaliasG** [retorquere/zotero-better-bibtex#2616]
### Debug log ID

KK6KQC48-apse/6.7.106-6

### What happened?

BBT sentence case does nothing (no changes when selected). I have to be using the Zotero sentence case now.

It hapens in all items, I provide the below article as an example. BBT sentence case did not work but normal Zotero case works.

https://pubmed.ncbi.nlm.nih.gov/37498655/

Zotero 6.0.26

BBT 6.7.106

Manjaro Linux KDE

**Comment by retorquere** [comment]
Reproducible.

**Comment by retorquere** [comment]
Can you confirm that solves it?

**Comment by MavropaliasG** [comment]
> Can you confirm that solves it?

It works! Thank you very much, Emiliano!
