### ISSUE TITLE
BBT does not escape # in first argument of \href in note

### ISSUE THREAD

**Issue by 2017MK2017** [retorquere/zotero-better-bibtex#2617]
### Debug log ID

I am not willing to provide any personal data

### What happened?

When a note has a URL in it, BBT does not escape the # character in `\href`'s first argument:

Note in Zotero:

> [https://www.example.com/#foo](https://www.example.com/#foo)

Created item:

```
@misc{TheKey,
  title = {TheTitle},
  author = {{TheAuthor}},
  date = {2023},
  note = {\href{https://www.example.com/#foo}{https://www.example.com/\#foo}}
}
```

**Comment by 2017MK2017** [comment]
Nevertheless: Biber runs and after that lualatex crashes

**Comment by retorquere** [comment]
Can you give an MWE latex document?

**Comment by 2017MK2017** [comment]
```
\documentclass{article}

\begin{filecontents}{\jobname.bib}
@misc{TheKey,
  title = {TheTitle},
  author = {{TheAuthor}},
  date = {2023},
  note = {\href{https://www.example.com/#foo}{https://www.example.com/\#foo}}
}
\end{filecontents}

\usepackage[backend=biber,style=apa]{biblatex}
\addbibresource{\jobname.bib}
  
\begin{document}

Test see \parencite{TheKey}.

\end{document}

```

**Comment by retorquere** [comment]
You need to load `hyperref` to use `href`

**Comment by retorquere** [comment]
Does this address your question?

**Comment by 2017MK2017** [comment]
Adding

```
\addbibresource{\jobname.bib}

\usepackage{hyperref}

\begin{document}
```

does not help.

---

With and without, the pdf is correctly created, but LuaLaTex throws:

```
Illegal parameter number in definition of \abx@field@note.

l.19 Test see \parencite{TheKey}.
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.
```

**Comment by retorquere** [comment]
This compiles without error with me on overleaf with lualatex

```
\documentclass{article}
\begin{filecontents}{\jobname.bib}
@misc{TheKey,
  title = {TheTitle},
  author = {{TheAuthor}},
  date = {2023},
  note = {\href{https://www.example.com/\foo}{https://www.example.com/\#foo}}
}
\end{filecontents}
\usepackage{hyperref}
\usepackage[backend=biber,style=apa]{biblatex}
\addbibresource{\jobname.bib}
  
\begin{document}

Test see \parencite{TheKey}.

\end{document}
```

make sure to recompile from scratch from the dropdown menu at least once. Otherwise your compilation uses cached files with the error in it.

**Comment by 2017MK2017** [comment]
Your note replaced `#` by `\`:
`note = {\href{https://www.example.com/\foo}{https://www.example.com/\#foo}}`
instead of
`note = {\href{https://www.example.com/#foo}{https://www.example.com/\#foo}}`

**Comment by retorquere** [comment]
That was a mistake, but this also compiles without error:

```
\documentclass{article}
\begin{filecontents}{\jobname.bib}
@misc{TheKey,
  title = {TheTitle},
  author = {{TheAuthor}},
  date = {2023},
  note = {\href{https://www.example.com/foo}{https://www.example.com/\#foo}}
}
\end{filecontents}
\usepackage{hyperref}
\usepackage[backend=biber,style=apa]{biblatex}
\addbibresource{\jobname.bib}
  
\begin{document}

Test see \parencite{TheKey}.

\end{document}
```

**Comment by retorquere** [comment]
@njbart ?

**Comment by njbart** [comment]
It seems that hash characters in the first argument of `\href` should indeed be escaped in case `\href` is used in the argument of some other command (I assume that this is what’s happening in a biblatex context). See https://tex.stackexchange.com/a/366941.

**Comment by retorquere** [comment]
@2017MK2017 can you make a sample entry that exports the wrong way, export it as BBT json, rename it to .txt, and attach it here?

**Comment by retorquere** [comment]
I need a "BetterBibTeX JSON" export instead of a "Better CSL JSON" export.

I'm looking into giving more privacy options in the debug log wizard, but this sort of thing is why I press for debug logs. It automates what I need for my work.

**Comment by retorquere** [comment]
How do I actually output this URL in the note field? I suspect I should be doing the same for `%` characters.

**Comment by retorquere** [comment]
@2017MK2017 the build above fixes it for me, would appreciate it if you could check if it works for you.

@njbart can I get a percent sign in the URL? The MWE below renders the URL with `\%` in the output, but if I remove the backslash, rendering breaks.

```
\documentclass{article}
\usepackage{url}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@misc{something-else_one,
  author  = {Some One},
  title   = {Something else},
  year    = {nodate},
  url     = {https://somesite.org/someotherpage},
  urldate = {2017-12-19},
  note    = {\url{https://somesite.org/\%20someotherpage}}
}
\end{filecontents}
\usepackage[style=apa]{biblatex}
\DeclareLanguageMapping{english}{english-apa}
\usepackage{xpatch}
\xpatchbibdriver{misc}
  {\printfield{entrysubtype}}
  {\printfield{entrysubtype}%
   \newunit\newblock
   \printfield{note}}
  {}
  {}
\addbibresource{\jobname.bib}
\pagestyle{empty}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by retorquere** [comment]
So it looks like in url-as-argument verbatim-ish mode, `\`, `%` and `#` need escaping (and subsequent unescaping when parsing bibtex).
