### ISSUE TITLE
how to specify path to pandoc binary 

### ISSUE THREAD

**Issue by scbarton** [retorquere/zotero-better-bibtex#2620]
### Debug log ID

29PSJRB8-refs-euc/6.7.109-6

### What happened?

Just a note regarding better bibtex features that require pandoc.  The [AUX Scanner page](https://retorque.re/zotero-better-bibtex/citing/aux-scanner/) and [Issue 2079](https://github.com/retorquere/zotero-better-bibtex/issues/2079)  discuss using `sudo launchctl config user path $PATH` to set the application path to point to `pandoc`. This solution did not work for me, using macos 13.5 Ventura. 

What did work was adding the path to `pandoc` (in my case `/opt/homebrew/bin`) to `/etc/paths`. There is some indication that this is the correct approach for recent versions of macos. Perhaps this approach should be recommended going forward?

**Comment by retorquere** [comment]
Do you know whether this also works on older MacOS version (so it could just be the general method rather than using launchctl)?

**Comment by scbarton** [comment]
> Do you know whether this also works on older MacOS version (so it could just be the general method rather than using launchctl)?

No I do not. I could test that but it will take me some time to set up a test system.

**Comment by retorquere** [comment]
Any news?

**Comment by retorquere** [comment]
See bottom of https://retorque.re/zotero-better-bibtex/citing/aux-scanner/
