### ISSUE TITLE
[Bug]: cayw api error with `minimize` in Zotero 7

### ISSUE THREAD

**Issue by RayKr** [retorquere/zotero-better-bibtex#2621]
### Debug log ID

not in zotero 7 client

### What happened?

When I was develop a vscode plugin using `CAYW` api, and I want to use `minimize` variable to minimize zotero 7 window after a pick, there is an zotero error like this 
```
CAYW failed: windows.getNext().QueryInterface is not a function
init@jar:file:///Users/jzl/Library/Application%20Support/Zotero/Profiles/gdjuekh7.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js:133535:43
```
It maybe a zotero 7's compatibility problem I think. Please to check it, thank you!

**Comment by retorquere** [comment]
I don't know what "not in zotero 7 client" means? That error is not enough to go on.

**Comment by RayKr** [comment]
> I don't know what "not in zotero 7 client" means?

Sorry, I didn't make it clear. What I meant was that I wasn't performing the operation in the Zotero client, so I couldn't get the log of the BBT plugin. I'm using the Cayw API in my VSCode plugin development, and there is a "minimize" field inside which can minimize the Zotero window after picking. However, when debugging with Postman, an error occurred.

**Comment by RayKr** [comment]
Okay, I follow the tips to produce a log, debug log id is `M3JY8Y9L-apse/6.7.111-7`.

**Comment by retorquere** [comment]
I think build 4926 (linked above) will fix it. Can you try that build?

**Comment by RayKr** [comment]
> I think build 4926 (linked above) will fix it. Can you try that build?

Oh, yes! I tried it, 4926 it works!

<img width="721" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/10293675/b1b395df-b325-4274-b46c-237226162434">

<img width="1008" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/10293675/2a4b8c06-d946-454a-952b-bcf6166f5847">
