### ISSUE TITLE
[Bug/Feature]: Communication problem seemingly introduced by BetterBibtex

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [retorquere/zotero-better-bibtex#2623]
### Debug log ID

None yer

### What happened?

I reported the following behaviour against zotero-deb : 

> I have a communication problem and a display update problem with a freshly-installed repo version (replacing a hand-installed one).

> My motivation was the communication problem (constated with the hand-installed version). The display problem seems new.

> Setup : 
> - Debian testing
> - LibreOffice as from Debian testing
> - Zotero (6.0.26) installed today (2023-08-17) from the repo added via your script.
> - LibreOffice plugin (6.0.3) reinstalled systemwide (using `sudo lowriter` to reinstall for all users, using `/usr/lib/zotero/extensions/zoteroOpenOfficeIntegration@zotero.org/install/Zotero_OpenOffice_Integration.oxt`)

> Symptoms : 
> - Communication problem : 
>    - Zotero opens fine and retirieve my daatabase (local library + 3 shared libraries)
>     - I can't open the plugin's `Set Zotero preferences` : trying tis opens a dialog box stating `LibreOffice could not communicate with Zotero. Please ensure Zotero is open and set to an online state and try again.`
> - Display/update problem :
>     - Creating a new collection in one of the shared libraries is inefficient : command is accepted but the collection "never" appears.
>     - Ditto for a new collection in the local library.
>     - However, closing Zotero then reopening it shows the newly created libraries.
>     - Adding a reference in the local library new collection (via the Chromium plugin) is apprently inefficient.
>     - However, selecting another collection then reselecting the new library shows that the reference has indeed been added.
>     - Ditto for the shared library.

You suggested to submit in the `zotero.org` forum, which I did.  An answer suggested to remove Zotero plugins. I started bu disabling BetterBibtex, which *restored* the normal behaviour.

At your suggestion, I re-submit this issue. Let me now what supplementary information you need to track the problem.

HTH,

**Comment by EmmanuelCharpentier** [comment]
Steps taken : 
- Reenabled BetterBibTeX
- Enabled debug logging at restart
- Restarted Zotero

BetterBibtex never ended its database update (I let it run for about 45 minutes).

- Sent the log. The message box told that theId to sed was `D2072674402`

I plan to re-disable BetterBibtex, disable logging and restart.

Let me know if you need other trials or attempts.

**Comment by EmmanuelCharpentier** [comment]
> - Sent the log. The message box told that theId to sed was D2072674402

Errr... that was the Zotero log. The BetterBibTeX log ID was `gJOiBLxjB2Y6-GJWH33AV`

Apologies...

**Comment by retorquere** [comment]
Debug logging doesn't appear to be on in `gJOiBLxjB2Y6-GJWH33AV`, and Better BibTeX is disabled, so I don't expect it would exhibit the error. I really do need a log after reproduction -- All builds of Zotero are put through the test suite on Linux, so it's not the case that this problem appears on all Linux systems.

**Comment by EmmanuelCharpentier** [comment]
OK. I'll retry the same steps ! How much time do you want me to wait before sending the log ?

**Comment by retorquere** [comment]
Assuming a not too ancient system, if BBT startup takes more than 10 seconds, you can be reasonably sure the error is in the log.

**Comment by EmmanuelCharpentier** [comment]
Apparently, I sent a log *twice* : `nNwplUbkYrQu-KYZP35BP` and `mlFMW34q0p5v-P2HI99F9`

Err.. make this *thrice* : `kWIZDnSyMIAz-N9YSA3GT`

Err... Zotero seems to send logs at regular intervals. I have now three message boxes recording sendings to `file.io`.

I'll stop that and wait further instrucyions if necessary.

**Comment by retorquere** [comment]
None of these show any errors at all. I'll spin up a debian VM to see if I can replicate this. My own system and Github's systems run ubuntu, maybe there's a difference.

**Comment by EmmanuelCharpentier** [comment]
> None of these show any errors at all. I'll spin up a debian VM to see if I can replicate this. My own system and Github's systems run ubuntu, maybe there's a difference.

FWIW, a VM runing Windows 11 + Zotero (current) + BetterBibtex (current) aon a DB containing the same libraries runs fine.

**Comment by EmmanuelCharpentier** [comment]
> Can you try again with build 5932?

I'm still wth 6.7.112, and trying to find updates brings me `No updates found`. the betterbibtex:database still doesn' terminate...

Instructions ?

**Comment by retorquere** [comment]
These debug builds don't install via the update mechanism, you must download them and install them manually.

**Comment by EmmanuelCharpentier** [comment]
> How do I do that ?

Never mind : I just re-read the bot message. Shame on me !

**Comment by EmmanuelCharpentier** [comment]
Log after about 90 seconds of the never ending `bette bibtex : database` loop : `nJnC7k6KFC4E-RYPT8XJI`.

**Comment by retorquere** [comment]
Debug logging at start does not appear to be on, and since this is a startup, the problem has probably occurred before logging started. Can you choose "Help" > "Debug Output Logging" > "Restart with Logging Enabled", let Zotero restart, and then send a new log?

**Comment by EmmanuelCharpentier** [comment]
>  Can you choose "Help" > "Debug Output Logging" > "Restart with Logging Enabled", let Zotero restart, and then send a new log

That's what (I believe) I've done. I'll make a second attempt. Stay tuned.

**Comment by retorquere** [comment]
You can just use file.io for now. The option you tried is more convenient for me, but the file.io sender has less dependencies so it's more reliably available.

**Comment by retorquere** [comment]
I'm having difficulty installing Debian testing in Virtualbox.

**Comment by retorquere** [comment]
Same problem on VMWare fusion, and I don't have a spare system I could use for this.

**Comment by EmmanuelCharpentier** [comment]
> I'm having difficulty installing Debian testing in Virtualbox.

What is the problem ?

**Comment by retorquere** [comment]
Same on both, cannot install the bootloader so the system is unbootable.

**Comment by EmmanuelCharpentier** [comment]
Did you try to boot a Debian Live image ?

**Comment by EmmanuelCharpentier** [comment]
Other possibility : dump an image on a (physical) USB key and boot from that.

**Comment by retorquere** [comment]
I'm going to see if I can bring up Debian in a docker image on my Ubuntu system.

**Comment by retorquere** [comment]
> Other possibility : dump an image on a (physical) USB key and boot from that.

My Linux system is headless, it's not really set up to boot this way.

**Comment by retorquere** [comment]
I'm hitting [this](https://groups.google.com/g/linux.debian.bugs.dist/c/R0gLqy-kqFM) problem installing debian testing.

**Comment by retorquere** [comment]
Is there a live cd version of testing? All I'm seeing are 12.1 images

**Comment by retorquere** [comment]
I've installed 12.1 in virtualbox, but I am getting errors when I try to install the dependencies needed for the libreoffice plugin.

Would it be possible for you to prep an virtualbox image for me? The only other option I see is that you keep sending new logs. I'd love to get to the bottom of this.

**Comment by EmmanuelCharpentier** [comment]
> Would it be possible for you to prep an virtualbox image for me? The only other option I see is that you keep sending new logs. I'd love to get to the bottom of this.

Where can I send you the resulting tarball ,(3,8 GB (including the .iso), from an 8 GB directory) ?

**Comment by retorquere** [comment]
If you have a google acount you can upload it to my google drive: https://docs.google.com/forms/d/e/1FAIpQLSc1FseErFiGca8fzJq2lzJzbiDM5bXPdizpGD9kiFHQ5G1Ugg/viewform?usp=sf_link

**Comment by EmmanuelCharpentier** [comment]
I can't uload : I get an error page telling (in French) : 

```
Autorisation nécessaire
Seuls les utilisateurs faisant partie de l'organisation du propriétaire du formulaire peuvent afficher celui-ci.

Si vous pensez qu'il s'agit d'une erreur, contactez le propriétaire du formulaire. [En savoir plus](https://support.google.com/docs/?p=forms_settings)
```

I.e. "Authorization necessary. Oly users belonging to the form's owner's organization can display it. If you thnk this is an error, contact the form's owner [yadda yadda...]".

**Comment by retorquere** [comment]
Sorry, I had the permissions set wrong: https://docs.google.com/forms/d/e/1FAIpQLSc1FseErFiGca8fzJq2lzJzbiDM5bXPdizpGD9kiFHQ5G1Ugg/viewform?usp=sf_link

**Comment by EmmanuelCharpentier** [comment]
Underway.

It willl be long : that's 3.7 GB at (at best) 150 kB/sec, i. e. about 7 hours. Joys of DSL... Sorry for that.

Look at `Readme_Emiliano.txt` for details (such as passwords...).

**Comment by EmmanuelCharpentier** [comment]
Done.

**Comment by retorquere** [comment]
The upload appears to have failed -- I see no file in the upload folder 😞 . Can you try https://transfer.pcloud.com/ ?

**Comment by EmmanuelCharpentier** [comment]
> Can you try https://transfer.pcloud.com/ ?

Have you an email address to receive the file ?

**Comment by retorquere** [comment]
Oh yes, sorry: emiliano.heyns@iris-advies.com

**Comment by EmmanuelCharpentier** [comment]
Underway. Still needs about 7 hours...

**Comment by EmmanuelCharpentier** [comment]
>Still needs about 7 hours...

More probably 9-10 haurs...

Did you try to reproduce my creation process ? Uneventful, except for the initial boot, which required rte-specifying the ISO boot image (might be a Virtualbox wizard bug...).

**Comment by retorquere** [comment]
What creation process?

**Comment by EmmanuelCharpentier** [comment]
Use Virtualbox wizard : this fails initially because it does not find the boot ISO. Point it manually to your netinst ISO : this,*doesù install your VM...

According to [prcloud](https://transfer.pcloud.com/), the upload should be complete in a bit more than 2 hours...

**Comment by retorquere** [comment]
I didn't use the wizard.

**Comment by EmmanuelCharpentier** [comment]
> I downloaded the iso and booted off that by pointing the wizard to it, then skipped non-attendant.

And this didn't boot ? I *did* use non-attendant...

[ From a earlier post ]
> I've installed 12.1 in virtualbox, but I am getting errors when I try to install the dependencies needed for the libreoffice plugin.

What dependencies gave you problems ?

**Comment by retorquere** [comment]
> And this didn't boot ? I did use non-attendant...

The dvd image did boot in virtualbox, but the resultant install in virtualbox does not boot since the installation fails to write the bootloader.

> What dependencies gave you problems ?

I forgot, I can test this when I get home tonight.

**Comment by EmmanuelCharpentier** [comment]
Done : transfer verified.

**Comment by EmmanuelCharpentier** [comment]
In Gnome's system menu : 
- item "Pays et langue" : choose English and your preffered location
- item "Clavier" : choose your preferred setup

There are also default settings in `/etc`.

**Comment by EmmanuelCharpentier** [comment]
> There are also default settings in /etc

And in your profile (hiden dot files at the root of your home directory).

**Comment by retorquere** [comment]
It won't let me select anything but French:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/132108/980e10ac-97fb-4bbe-bd67-c6cbf76b7779)

I tried 

```
update-locale LANG=en_US.UTF-8 LANGUAGE
```

as root but I get "invalid locale settings".

**Comment by EmmanuelCharpentier** [comment]
> It won't let me select anything but French:

Try [this](https://bbs.archlinux.org/viewtopic.php?id=141124).

**Comment by EmmanuelCharpentier** [comment]
> Try [this](https://bbs.archlinux.org/viewtopic.php?id=141124).

which leads to [this](https://wiki.archlinux.org/title/Locale), whoch explains to edit `etc\locale.gen` to enable the desired locale, then rin `locale.gen`.

HTH,

**Comment by retorquere** [comment]
I've booted the image, installed LO and Zotero, and tried what you did:

> I can't open the plugin's Set Zotero preferences : trying tis opens a dialog box stating LibreOffice could not communicate with Zotero. Please ensure Zotero is open and set to an online state and try again.

I take it you mean "Set Document Preferences" here? That just works for me.

> Ditto for a new collection in the local library.

Likewise, creating collections, no problems. I cannot reproduce any of the problems you have on the virtualbox image.

Can you execute the following for me?

```
find ~/Zotero -exec ls -lh {} \; | awk '{print $1 " " $2 " " $3}' | sort -u
```

**Comment by retorquere** [comment]
That looks fine. I'm trying to think of something that could be different about your system, but it's not just the combination of Debian testing + zotero + bbt. Can you replicate the problem in the virtualbox image?

**Comment by EmmanuelCharpentier** [comment]
> Can you replicate the problem in the virtualbox image?

This will be long (> 15 00 reference in 4 libraries). Don't expect result before tomorrow, I guess...

**Comment by retorquere** [comment]
I don't see any other way. I can't replicate anything.

**Comment by EmmanuelCharpentier** [comment]
I have to put that on the back burner (urgent works to do which don'( require Better BibTeX). I'll keep you posted.

Sorry for the delay.

**Comment by EmmanuelCharpentier** [comment]
> install that, go to Help -> Debug -> Restart with logging enabled, let BBT stew for a bit at start

Done. I included the cache in the send attempt.

> and then send a file.io log.

The sending fails (Dialog box stating "Request timed out (IQ43IF4-euc, itels: false). The original dialog box is still open.

Instructions ?

**Comment by EmmanuelCharpentier** [comment]
Noteworthy : the BibTeX update at start seems to have been completed.

**Comment by retorquere** [comment]
Well that is a bit of good news then. I've been looking into smoothing out BBTs startup process. One thing that will help a little is disabling citekey search. But I have a 24k library in my test suite, and while that takes *forever* to start, it does reliably start.

**Comment by retorquere** [comment]
For the log, does a log to file.io succeed?

**Comment by EmmanuelCharpentier** [comment]
> For the log, does a log to file.io succeed?

How do I do that ?In the "Help" menu, I just have one iram "Envoyer le journel de débogage Better BibTeX" (Send the Better BibTeX debug journal) and a submenu "Journal de débogage" (Debug log), with an entry "Envoyer le journal" (Send log). Is that what you mean ?

Fair warning : this entry tells me that the log has 9625 lines recorded...

**Comment by EmmanuelCharpentier** [comment]
Long sent. Id : D608866396.

**Comment by retorquere** [comment]
I can't read those logs, those go to the Zotero team.

> How do I do that ?In the "Help" menu, I just have one iram "Envoyer le journel de débogage Better BibTeX" (Send the Better BibTeX debug journal) and a submenu "Journal de débogage" (Debug log), with an entry "Envoyer le journal" (Send log). Is that what you mean ?

I forgot the startup finishes now -- from start until 15 seconds after the BBT startup completes, there is also a "Send debug log to file.io" in the Help menu.

**Comment by EmmanuelCharpentier** [comment]
> I forgot the startup finishes now -- from start until 15 seconds after the BBT startup completes, there is also a "Send debug log to file.io" in the Help menu.

Done. Let me know if you received it.

**Comment by retorquere** [comment]
You have to tell me the ID, without it I cannot access it.

**Comment by EmmanuelCharpentier** [comment]
> You have to tell me the ID, without it I cannot access it.

Sorry : I forgot that. Id = kb9F9QkjdvBp-M9VIZ6Y3.

**Comment by retorquere** [comment]
As far as I can tell, debug logging was off during start and at the time you submitted the log. I can see that BBT is installed, but not much more.

BTW if you don't care about citekey search, you can turn that off to save some time during startup. I'm also going to shift that to post-start.

**Comment by EmmanuelCharpentier** [comment]
Important : `zotero-better-bibtex-6.7.113.2623.4970.xpi` *no longer exhibit*s the problems I reported. I can now : 
- Access document preferences
- Insert one or many references
- Insert bibliography.

Do you need further debug logs attempts ?

**Comment by retorquere** [comment]
> 6.7.113.2623.4970.xpi` _no longer exhibit_s the problems I reported. I can now :

That is good in a way, although I'd rather have found and fixed the problem... there's nothing you can do to further this right now. I have some startup performance work planned that might play into the problem you encountered.

If you do encounter the problem again, commenting on this issue will automatically reopen it.

I'm scheduling a new release that shifts citekey search init to post-startup, which should mean you can leave it enabled.

**Comment by EmmanuelCharpentier** [comment]
Okay. I'll re-enable automatic updates and keep you posted here in case of seemingly related problems.

Since I seem to have an "interesting" setup, please do not hesitate to ring me if you need a test in this specific setup.

Thank you for your care of my problem !

**Comment by EmmanuelCharpentier** [comment]
FWIW : `zotero-better-bibtex-6.7.113.2623.4983.xpi` works like the former revision.

**Comment by EmmanuelCharpentier** [comment]
> FWIW : `zotero-better-bibtex-6.7.113.2623.4983.xpi` works like the former revision.

Ditto for `6.7.114`

**Comment by retorquere** [comment]
The former I'm relieved to know, the latter is the same as the former, but with a new version number and published in the upgrade path so people pick it up automatically.

**Comment by retorquere** [comment]
I'll still be looking into the startup performance.
