### ISSUE TITLE
[Feature]: add a small note on Zotero 7 compatibility in readme?

### ISSUE THREAD

**Issue by champagnealexandre** [retorquere/zotero-better-bibtex#2625]
### Debug log ID

none

### What happened?

Hi,

I’ve been using Zotero 7 beta for some time now and BBT has been *mostly* functional. However on some occasions it wasn’t, and restarting/turning on and off the plugin/updating solved it.

I recently noticed citation keys weren’t being displayed reliably, and came here to verify. There are a couple issues open about Zotero 7 compatibility like #2522 and #2604, but some of these contain a lot of discussions and it’s a bit hard to keep track on what’s the current status on Z7 compatibility.

Can I suggest that a small note be added in the Readme on what’s the current status for Z7 compatibility? Given the fact that many people are actively testing Z7 (it’s significantly faster on my M1) I think this would be useful. As I understand, I think you’re waiting on Zotero devs to update the API for the citation key to be displayed correctly, so the section I’m suggesting could simply contain a note about this.

I know you’ve already been working hard on this so I hope my suggestion isn’t asking too much. I think it would clear some confusion for people testing Z7/BBT in the meantime and make it easier to see what’s the current status.

Thanks again for all the hard work on BBT!

**Comment by retorquere** [comment]
done!

**Comment by champagnealexandre** [comment]
Thank you so much!

And thanks again for the hard work, BBT is an essential tool :)
