### ISSUE TITLE
[Bug]: Journal acronym from acronyms list not used in generated citation key

### ISSUE THREAD

**Issue by briochemc** [retorquere/zotero-better-bibtex#2634]
### Debug log ID

7V5NMTWK-refs-apse/6.7.114-6

### What happened?

_as recommended by @retorquere, mostly copied from earlier post by @briochemc in https://github.com/retorquere/zotero-better-bibtex/discussions/2633 (FWIW: I have generated a new debug log here so that it matches the `acronyms.csv` file attached below)_

I want to use journal acronyms when generating citation keys. To do that I created this file in my `~/Zotero/better-bibtex`:
[acronyms.csv](https://github.com/retorquere/zotero-better-bibtex/files/12459814/acronyms.csv)

And then in the citation key formula, I used
```
journal(abbrev="off").acronym
```

However, the generated citation key contains "EarthandPlanetaryScienceLetters" instead of the desired acronym, "EPSL". 

It seems none of the acronym lines work.

**Comment by briochemc** [comment]
LGTM (for my case)!

**Comment by retorquere** [comment]
It was a documentation problem; I required a specific header that I didn't document, but then how you had it seemed much more reasonable so I added support for either form.

I'll put out a new release later today, that'll just be a rebadged version of what you already have. You don't need to do anything, and you will automatically be upgraded between now and two days (I believe zotero checks every 48 hours).

**Comment by briochemc** [comment]
OK so I was missing something!

BTW I'm not sure what I did wrong but now that I started adding other acronyms it does not seem to work anymore...

**Comment by briochemc** [comment]
Oh it seems that I need to restart Zotero if I edit the list of acronyms. I thought I'd point it out if someone else is trying this feature...

**Comment by retorquere** [comment]
I've documented that, site should update in about 10 minutes.

**Comment by briochemc** [comment]
> You don't need to do anything, and you will automatically be upgraded between now and two days (I believe zotero checks every 48 hours).

Do you mean that I don't even have to reinstall better-bibtex even though I installed the test build? I.e., will Zotero know to replace the test build with the latest version?

**Comment by retorquere** [comment]
Yes.
