### ISSUE TITLE
[Bug/Feature]: Background export setting isn't saved

### ISSUE THREAD

**Issue by Itrekr** [retorquere/zotero-better-bibtex#2635]
### Debug log ID

EV5FB9CK-refs-euc/6.7.116-6

### What happened?

Upon checking "Keep updated" when exporting a library, the "Background export" checkbox is automatically checked. However, upon revisiting the menu, the "Background export" checkbox is unchecked.

Steps to reproduce:

    Right-click on My Library -> Export Library... -> select Better BibTeX
    Check "Keep updated". If it's already checked, uncheck and check again.
    Export the library
    Reboot Zotero / Export again
    Notice that "Background export" is automatically unchecked.
  

This was previously also reported here: https://github.com/retorquere/zotero-better-bibtex/issues/2598

**Comment by retorquere** [comment]
New release build is running. Apologies it took so long -- it's been incredibly busy.

**Comment by Itrekr** [comment]
Confirmed to be working. The exporting at least. Background export checkbox remains checked after exporting. The 'Keep updated' checkbox idoesn't, but the export works so I assume it's intentional? As long as the auto-export is doing it's job I'm satisfied.

**Comment by Itrekr** [comment]
Also: no apologies required.

**Comment by retorquere** [comment]
> The 'Keep updated' checkbox idoesn't, but the export works so I assume it's intentional?

That is indeed intentional. I don't want people to be setting up auto-exports accidentally.
