### ISSUE TITLE
[Bug]: Citation key not show in item pane

### ISSUE THREAD

**Issue by HoollyFox** [retorquere/zotero-better-bibtex#2639]
### Debug log ID

36a3b0b5-bad0-4a04-b79b-441c7cef77db

### What happened?

In zotero 6, it's normal, but in zotero 7, citation key not show in item pane, like: 
<img width="332" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/23378900/d42ec8a4-730f-4675-845e-0a4aae11e041">

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-better-bibtex#readme

https://github.com/retorquere/zotero-better-bibtex/issues/2522
