### ISSUE TITLE
[Bug]: Export library display error.

### ISSUE THREAD

**Issue by earthmoon** [retorquere/zotero-better-bibtex#2641]
### Debug log ID

ZZ6IQSYD-euc/6.7.116-6

### What happened?

A bug happened!

Hello,

When I exported all my library, there will display an error. The bug has been submitted. Thanks. Another question: what is the **idle**?  I have chose **idle** to automatically export library, but I don't know when BetterBibTeX will export and I haven't see it exporting.

Best regards.

**Comment by retorquere** [comment]
#2315

**Comment by retorquere** [comment]
Idle means when you haven't used Zotero for a while. I As long as you're actively using Zotero, it will not export.

**Comment by earthmoon** [comment]
> Idle means when you haven't used Zotero for a while. I As long as you're actively using Zotero, it will not export.

Once I left my laptop there and go to lunch for an hour. When I returned,it haven't export `.bib` file. So, when will BetterBibTeX export it when set it to `idle`.

**Comment by retorquere** [comment]
Did you restart after changing that setting? You're still getting out of memory errors.

> Once I left my laptop there and go to lunch for an hour. When I returned,it haven't export .bib file. So, when will BetterBibTeX export it when set it to idle.

It will not while you're having out of memory errors.

**Comment by earthmoon** [comment]
> Did you restart after changing that setting? You're still getting out of memory errors.
> 
> > Once I left my laptop there and go to lunch for an hour. When I returned,it haven't export .bib file. So, when will BetterBibTeX export it when set it to idle.
> 
> It can't while you're having out of memory errors.

It is impossible to out of memory here.

**Comment by retorquere** [comment]
> It is impossible to out of memory here.

It is clearly not impossible because Zotero is out of memory on your system. Zotero 6 on Windows is a 32 bit app and that has a hard cap on memory use regardless of how much memory your system has. Zotero 7 will change that.

You haven't answered my question. Have you restarted Zotero since changing that setting? If not, changing the setting makes no difference.

**Comment by earthmoon** [comment]
> > It is impossible to out of memory here.
> 
> It is clearly not impossible because Zotero is in fact out of memory on your system. Zotero 6 on Windows is a 32 bit app and that has a hard cap on memory use regardless of how much memory your system has. Zotero 7 will change that.
> 
> You haven't answered my question. Have you restarted Zotero since changing that setting? If not, changing the setting makes no difference.

I will test it in about 3 hours. I forgot it now. Thanks a lot.

**Comment by retorquere** [comment]
BTW I'm not just guessing that Zotero is out of memory, the top of the error log says

```
[JavaScript Error: "out of memory"]
[JavaScript Error: "out of memory"]
```

**Comment by earthmoon** [comment]
> JavaScript Error: "out of memory"]

Okay. I have left my laptop for nearly 3 hours but no new file exported.

**Comment by retorquere** [comment]
OK, but have you restarted Zotero. If you did not restart Zotero, it is unavoidable that you will still have out of memory errors.

**Comment by earthmoon** [comment]
> OK, but have you restarted Zotero. If you did not restart Zotero, it is unavoidable that you will still have out of memory errors.

In the morning today, it exported when I started the Zotero, so it can work if memory is not out of. However, now, I needn't to start it if I hope it export, as it is easier to export it by hand compared to restart it.

**Comment by retorquere** [comment]
OK, so you did restart. How many items are in your library?

**Comment by earthmoon** [comment]
> OK, so you did restart. How many items are in your library?

 3466. Hope Zotero 7 will be released soon.

**Comment by retorquere** [comment]
That's not an awful lot. BBT must have a memory leak, I'll look into that, but that's a notoriously hard problem to diagnose, as cause and effect are typically not near each other. 

Zotero 7 should be out [somewhere this year](https://groups.google.com/g/zotero-dev/c/t0oP9NECX54/m/CyD9xz2oDgAJ) but I haven't yet seen an indication of a more precise date.

**Comment by earthmoon** [comment]
> en an indication of a more precise date

Thanks a lot. If I choose exported when changed, it will often stuck, so the exported when idle is only choice.

**Comment by earthmoon** [comment]
I have restarted the Zotero, but found BetterBibTeX didn't export the library. So, **AutoExport** wouldn't work at any time.

**Comment by retorquere** [comment]
I can't say what would be the cause of this without a debug log.

**Comment by earthmoon** [comment]
> I can't say what would be the cause of this without a debug log.

Thanks for reminder. The debug id is `YM56XQE5-euc/6.7.116-6`

**Comment by retorquere** [comment]
I don't see an error in that log, but I also cannot find an attempted export in that log. Can you reproduce the problem using manual export and send a debug log right after?

**Comment by earthmoon** [comment]
> I don't see an error in that log, but I also cannot find an attempted export in that log. Can you reproduce the problem using manual export and send a debug log right after?

There is no error, but it just didn't automatically export no matter whether restart the Zotero.

**Comment by earthmoon** [comment]
> this is your friendly neighborhood build bot announcing [test build 6.7.116.2641.5048](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.116.2641.5048.xpi) ("balance fallback")

May anyone tell me what is this?

**Comment by retorquere** [comment]
That build has extra logging to see if zotero's idle mechanism actually fires, and how BBT responds to that.

**Comment by retorquere** [comment]
Can you install that, let it go idle again, and send a new log?

**Comment by earthmoon** [comment]
> Can you install that, let it go idle again, and send a new log?

Yes. Please check that: `4L6MC7K3-apse/6.7.116.2641.5048-6`

**Comment by retorquere** [comment]
Did you change an item before letting Zotero fall idle? I can't find the change in the log.

**Comment by earthmoon** [comment]
> Did you change an item before letting Zotero fall idle? I can't find the change in the log.

`TFDRL6LI-euc/6.7.116.2641.5048-6`. This time I made a change.

**Comment by retorquere** [comment]
Can you do that again with 5049?

**Comment by earthmoon** [comment]
> Can you do that again with 5049?

This one `TIZVHLQU-euc/6.7.116.2641.5049-6`. Thanks.

**Comment by retorquere** [comment]
Same please

**Comment by earthmoon** [comment]
> ~Same please~ I have it reproducible

Thanks a lot. Please see this one: `8W2KIUJM-apse/6.7.116.2641.5050-6`.

**Comment by retorquere** [comment]
5052 should re-enable on-idle search

**Comment by earthmoon** [comment]
> 5052 should re-enable on-idle search

This version will export when idle. It is good. Thanks!

**Comment by retorquere** [comment]
Thanks! I've scheduled the release of 6.7.117

**Comment by earthmoon** [comment]
> Thanks! I've scheduled the release of 6.7.117

Looking forward to the day when it can be updated.

**Comment by retorquere** [comment]
.117 is just 5052 with a new version number; you are up to date as you are, and Zotero will automatically update to .117 in the next few days. If you want it now, wait until https://github.com/retorquere/zotero-better-bibtex/actions/runs/6121132049 goes green, then go in the addons screen and ask Zotero to search for updates.

**Comment by earthmoon** [comment]
Okay. Good job! Thanks.
