### ISSUE TITLE
[Feature]: Could support search by `Short Title` field in CAYW Picker? 

### ISSUE THREAD

**Issue by RayKr** [retorquere/zotero-better-bibtex#2642]
### Debug log ID

G67GT8CP-euc/6.7.116-7

### What happened?

I really like the CAYW feature and even developed a VSCode plugin [Zotex](https://github.com/RayKr/zotex). However, I found that during usage, it seems that the picker cannot search for content by Short Title. It's a pity because I frequently use this field to annotate my index for an article with a very memorable name. But this field doesn't seem to work in the picker's search. Will this feature be supported?

**Comment by retorquere** [comment]
You'd have to ask zotero - I just pop up their picker and they tell me what items were selected. The search mechanism is entirely theirs.

**Comment by RayKr** [comment]
Oh, yes. I just checked zotero/zotero repo, and I find the [code](https://github.com/zotero/zotero/blob/b918ad2892d2853f0511a26aa0cace2bd6e5ea4f/chrome/content/zotero/xpcom/data/search.js#L320) about this feature, It has supported. Therefore, I verified in my library again and confirmed it works. Sorry to bother you. :)

**Comment by RayKr** [comment]
Then allow me to close this issue pls.
