### ISSUE TITLE
[Bug]: When export on change is set, BetterBibTeX will interrupt modification of reference information

### ISSUE THREAD

**Issue by earthmoon** [retorquere/zotero-better-bibtex#2647]
### Debug log ID

NUJ43GJ7-apse/6.7.116.2641.5052-6

### What happened?

A bug happened!

Hello,

Set export on change, and then import a new reference into the Zotero. As BetterBibTeX is preparing to export the library, we modify some information of the refence, then our operation for the reference will be broken. 

Thanks.

**Comment by retorquere** [comment]
What operation for the reference will be broken? I don't see any errors in the log, so I don't know what's going wrong or what you are doing.

**Comment by earthmoon** [comment]
> What operation for the reference will be broken? I don't see any errors in the log, so I don't know what's going wrong or what you are doing.

Weird. I can't duplicate the bug. May be  the night I will meet it again.

**Comment by retorquere** [comment]
Can you also first upgrade to 118?

**Comment by earthmoon** [comment]
> Can you also first upgrade to 118?

Yes!

**Comment by retorquere** [comment]
If you find the bug again and comment here, the issue will automatically reopen.
