### ISSUE TITLE
[Bug]: Colon in attachments' file paths after drive letter escaped

### ISSUE THREAD

**Issue by dazu89** [retorquere/zotero-better-bibtex#2648]
### Debug log ID

JLK8XHA9-refs-euc/6.7.118-6

### What happened?

Using Zotero 6.0.27 and BBT 6.7.116 on a Windows Machine when exporting a collection via BBT in format 'Better Biblatex' the colon in attachments' file paths after the drive letter is escaped with a backslash `D\:\\Users\\User\\Zotero` effectively corrupting the file paths.
I tried postscript processing with `att.localPath = att.localPath.replace(/(\D)\\\:/g, '$1\:')` but could not get it to work.

**Comment by dazu89** [comment]
[debug-without-cache.txt](https://github.com/retorquere/zotero-better-bibtex/files/12565331/debug-without-cache.txt)

**Comment by retorquere** [comment]
There is nothing in that log. Is there a specific reason you are not using the built-in debug log facility? My entire support workflow is built around it.

**Comment by retorquere** [comment]
I need the input sample, the output you are getting, and the output you want. The debug log offers the first with very little effort.

I must admit I find it pretty frustrating when people post something like `-` instead of a debug log ID, certainly when it comes with no explanation.

**Comment by dazu89** [comment]
Please apologize, I did not intend to hamper your effort or to waste your time. I just reproduced the issue and submitted a bug report. JLK8XHA9-refs-euc/6.7.118-6

**Comment by retorquere** [comment]
And the output you get/you want?

**Comment by dazu89** [comment]
What I get when exporting a collection into the Better BibLaTeX Format
```
@book{bardossyEvaluationUncertaintiesRisks2004,
  title = {Evaluation of Uncertainties and Risks in Geology: New Mathematical Approaches for Their Handling},
  author = {Bárdossy, György},
  date = {2004},
  file = {C\:\\Users\\Visitor\\Zotero\\storage\\YFXEPE57\\Bárdossy - 2004 - Evaluation of uncertainties and risks in geology .pdf}
}
```
what I want 
```
@book{bardossyEvaluationUncertaintiesRisks2004,
  title = {Evaluation of Uncertainties and Risks in Geology: New Mathematical Approaches for Their Handling},
  author = {Bárdossy, György},
  date = {2004},
  file = {C:/Users/Visitor/Zotero/storage/YFXEPE57/Bárdossy - 2004 - Evaluation of uncertainties and risks in geology .pdf}
}
```
The insertion/escaping of the colon, i.e. `C\:\\`, in the file path corrupts the file path, it should be either `C:\\` or in following UNIX convention `C:/`.

**Comment by dazu89** [comment]
Superbe! This build fixes the outlined path corruption. Thank you very much, @retorquere!
