### ISSUE TITLE
Not choose "Keep Updated", there is an error when export.

### ISSUE THREAD

**Issue by earthmoon** [retorquere/zotero-better-bibtex#2649]
### Debug log ID

J4455CLV-apse/6.7.118-6

### What happened?

Hello,

When export the library without choosing the **Keep Updated**, there would be an error. However, if tick the **Keep Updated**, there wouldn't.

Thanks.

**Comment by retorquere** [comment]
maybe because it's using the worker to export, but you are still showing out of memory errors. I'm doing some work to limit memory use, but as it stands, I can't help you when you have caching on.

I'll see if I can detect the out of memory condition and show it in the UI somewhere.
