### ISSUE TITLE
Incorrect double slash in `Download better BibTeX export...`

### ISSUE THREAD

**Issue by dmkaplan2000** [retorquere/zotero-better-bibtex#2657]
### Debug log ID

44ZWC3RG-refs-euc/6.7.120-6

### What happened?

When I right clink on collection in Zotero and select `Better BibTeX` => `Download better BibTeX export...`, I am presented with two possible URLs. There is an error in the second proposed URL in that it has a double slash instead of a single slash (I like the second form of the URL as it is easier for me to identify where it comes from in my Zotero collection). For example, the dialog shows the following URL:

```
http://127.0.0.1:23119/better-bibtex/export/collection?/1/projects//2023-reducer.bibtex
```

but the correct URL is (note the single slash before 2023):

```
http://127.0.0.1:23119/better-bibtex/export/collection?/1/projects/2023-reducer.bibtex
```

I am using Zotero 6.0.27 and Better Bibtex for Zotero 6.7.120.

**Comment by retorquere** [comment]
New release build is running.

**Comment by dmkaplan2000** [comment]
Looks good to me. Thanks again for creating BBZ, it is a great tool.
