### ISSUE TITLE
Citation Key blocks following date field in extra

### ISSUE THREAD

**Issue by denismaier** [retorquere/zotero-better-bibtex#2658]
### Debug log ID

HQ8N6ANL-refs-euc/6.7.120-6

### What happened?

Depending on where `Citation Key` is in `Extra`, a directly following date field (maybe only `event-date`) is not available to citeproc-js. With the three items from the debug log and the minimal style below, I'm getting the following results:

1. `Citation Key` directly above `Event date` -> "match" -> `Event Date` not used
2. `Citation Key` last in `Extra` -> "10. Mai 2001match" -> as expected
3. `Citation Key` first in `Extra` ->  "10. Mai 2001match" -> as expected

I'm not sure whether this has something to do with Zotero BBT. (I actually doubt it, but I thought I'd better ask since this it involves the `Citation Key` field.)

```xml
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" demote-non-dropping-particle="never">
  <info>
    <title>event-date-test</title>
    <id>http://www.zotero.org/styles/event-date-test</id>
    <link rel="self" href="http://www.zotero.org/styles/event-date-test"/>
    <updated>2023-09-20T12:11:03+00:00</updated>
  </info>
  <citation>
    <layout>
      <date form="text" variable="event-date"/>
    </layout>
  </citation>
  <bibliography>
    <layout>
      <date form="text" variable="event-date"/>
      <choose>
        <if type="performance" match="any">
          <text value="match"/>
        </if>
      </choose>
    </layout>
  </bibliography>
</style>
```

**Comment by retorquere** [comment]
Sorry for the delay. Looking into it now.

**Comment by retorquere** [comment]
The citation key isn't strictly mine BTW, the Zotero bib(la)tex exporters use it too.

How are you testing this? I have tried exporting to CSL-JSON (which uses the same transformation) and there the extra field is just dumped into the `note` field.

**Comment by denismaier** [comment]
I suspect it may be a citeproc-js issue. As you say, the note field is exported properly. Pandoc also processes the exported items without issues, the visual editor as well.

**Comment by retorquere** [comment]
Easy to test whether it's BBT -- disable BBT, restart Zotero, and test again. If that still fails, it's unequivocally Zotero, not BBT. If it is BBT, I can look into it further. I'm less familiar with the citeproc part of Zotero.

**Comment by denismaier** [comment]
Ok – it's not BBT. Same thing happens without BBT.

**Comment by denismaier** [comment]
Closing here.
