### ISSUE TITLE
Quick start is not working

### ISSUE THREAD

**Issue by lbugnon** [retorquere/zotero-better-bibtex#2659]
### Debug log ID

documentation

### What happened?

if you do the following, parse_string function is not found 

!pip install --no-cache-dir --force-reinstall git+https://github.com/sciunto-org/python-bibtexparser@main
import bibtexparser
library = bibtexparser.parse_string("asd")

**Comment by retorquere** [comment]
wrong repo. You're looking for https://github.com/sciunto-org/python-bibtexparser
