### ISSUE TITLE
Import error with character '+' in BibTeX field name

### ISSUE THREAD

**Issue by zepinglee** [retorquere/zotero-better-bibtex#2660]
### Debug log ID

QAV4K73D-refs-euc/6.7.122-6

### What happened?

An import error occurs when I import the following BibTeX entry (from [plk/biblatex-apa/bibtex/bib/biblatex-apa-test-references.bib](https://github.com/plk/biblatex-apa/blob/0cffc8636dd2ffd8955c1e90e76fb70c237be584/bibtex/bib/biblatex-apa-test-references.bib#L65-L69)) into Zotero.

```bibtex
@BOOK{9.8:11,
  AUTHOR             = {U. Author},
  AUTHOR+an:username = {1="@ausername"},
  DATE               = {2014}
}
```

The error message says:
```
Import errors found:

- line 3, column 9: Expected "=", Optional Whitespace, or [_:a-zA-Z0-9\-] but "+" found.
```

It seems that BBT uses `[_:a-zA-Z0-9\-]+` as the pattern of the field names but actually BibTeX and biber accepts more characters including `+`. According to <https://github.com/aclements/biblib>, the field pattern of the original BibTeX is ``[A-Za-z!$&*+\-./:;<>?@[\\\]^_`|~][0-9A-Za-z!$&*+\-./:;<>?@[\\\]^_`|~]*``. This is `[\x20-\x7f]` excluding `[ \t"#%'(),={}]`, initial digits, and '\x7f' which is rarely used.

Biber uses `btparse` as its parsing library with a different pattern for field name: ``[a-z0-9!$&*+\-./:;<>?[\]^_`|]+`` (see its [documentation](https://metacpan.org/dist/Text-BibTeX/view/btparse/doc/bt_language.pod)). Unlike the original BibTeX, biber accepts initial digit but disallows `@`, `\`, and `~`.

**Comment by retorquere** [comment]
@njbart do you know what the nearest equivalent to `@periodical` `@jurisdiction`, `@legislation`, `@legmaterial`, `@legadminmaterial`, `@constitution` or `@legal` is?

**Comment by retorquere** [comment]
Build 5131 will import the file you linked to, and has better item type matches for `@audio`, `@dataset`, `@image` and `@presentation`, some awkward choices for `@hardware` (becomes Zotero `computer program`) and `@reference` (becomes `book`). @periodical` `@jurisdiction`, `@legislation`, `@legmaterial`, `@legadminmaterial`, `@constitution` or `@legal` still map to `document` until I find a better match.

**Comment by zepinglee** [comment]
> Build 5131 will import the file you linked to, and has better item type matches for `@audio`, `@dataset`, `@image` and `@presentation`, some awkward choices for `@hardware` (becomes Zotero `computer program`) and `@reference` (becomes `book`). `@periodical` `@jurisdiction`, `@legislation`, `@legmaterial`, `@legadminmaterial`, `@constitution` or `@legal` still map to `document` until I find a better match.

- `@periodical`: CSL v1.0.2 has `periodical` as entry type and I suggest adding `Type: periodical` in the `extra` field.
- `@jurisdiction` should be mapped to Zotero `case`. The biblatex documentation defines `jurisdiction` as "Court decisions, court recordings, and similar things" and all seven entries in `biblatex-apa-test-references.bib` are legal cases.
- `@legislation` can be mapped to Zotero `statute`.
- `@legmaterial` is an entry type defined in `biblatex-apa` and it's not in standard biblatex data model. The APA §11.6 says: "Legislative materials include federal testimony, hearings, bills, resolutions, reports, and related documents." Zotero has corresponding `bill` and `hearing` types but it's not trivial to further divide into these types.
- `@legadminmaterial` is also defined in `biblatex-apa` and it matches `regulation` in CSL. Yet Zotero doesn't have this type. I suggest using `statute` type with `Type: regulation` in `extra` field since they have similar fields.
- `@constitution`: Neither Zotero nor CSL has this type. Perhaps the closest type is `statute`.
- `@legal` is defined in biblatex as: legal documents such as treaties. The only `@legal` entry in `biblatex-apa-test-references.bib` is also a treaty. Thus it should match CSL's `treaty` type. Similar to `regulation`, I suggest `statute` type with `Type: treaty` in `extra`.

**Comment by retorquere** [comment]
For `11.4:3`, would Court be a good place for `9th Cir.`. I'm currently putting it in `extra` as `Authority`.

**Comment by retorquere** [comment]
For the itemtypes mentioned above, this is what ends up in the `extra` field. Maybe there are more entries that have native Zotero fields that these should end up in.


* document
Citation Key: 10.1:12a
Issue: 1
Pages: 51–104
Type: periodical
Volume: 6
tex.issuetitle: Special section

* document
Citation Key: 10.1:12b
Issue: 4
Type: periodical
Volume: 73
tex.issuetitle: Special issue

* statute
Citation Key: 11.10:29
Type: treaty

* case
Citation Key: 11.4:1
tex.citation: 347 U.S. 483

* case
Citation Key: 11.4:2
tex.citation: 576 U.S. ___

* case
Citation Key: 11.4:3
Authority: 9th Cir.
tex.citation: 951 F.2d 1128

* case
Citation Key: 11.4:4
Authority: N.D. Ohio
tex.citation: 133 F.Supp.2d 1034

* case
Citation Key: 11.4:5
Original Date: 1981
tex.citation: 563 F.Supp. 332 and aff'd and 727 F.2d 888
tex.citation+an:citedate: 1="1981";3="1984"
tex.citation+an:citeinfo: 2=appeal
tex.citation+an:citeorg: 1="D. Kan.";3="10th Cir."

* case
Citation Key: 11.4:6
tex.citation: 17 Cal.3d 425 and 131 Cal. Rptr. 14 and 551 P.2d 334

* case
Citation Key: 11.4:7
tex.citation: 826 S.W.2d 201
tex.citation+an:citedate: 1="1992"
tex.citation+an:citeorg: 1="Tex. Ct. App."

* statute
Citation Key: 11.5:10
Place: 20 U.S.C § 6301

* statute
Citation Key: 11.5:11
Place: Pub. L. No. 111-2, 123 Stat. 5

* statute
Citation Key: 11.5:12
Place: 20 U.S.C § 1681 <i>et seq.</i>

* statute
Citation Key: 11.5:13
Original Date: 1971
Place: Fla. Stat. § 394

* statute
Citation Key: 11.5:8
Place: 42 U.S.C § 12101 <i>et seq.</i>

* statute
Citation Key: 11.5:9
Place: Pub. L. No. 88–352, 78 Stat. 241

* bill
Citation Key: 11.6:14
Place: 114th Cong.
Type: regulation

* bill
Citation Key: 11.6:15
Place: 113th Cong.
Type: regulation

* statute
Citation Key: 11.6:16
Place: H.R 1100, 113th Cong.

* bill
Citation Key: 11.6:17
Issue: 438
Place: 114th Cong. and 162 Cong. Rec. 2394
Type: resolution
tex.source: senate

* report
Citation Key: 11.6:18
Issue: 114-358
tex.source: houseofrepresentatives

* statute
Citation Key: 11.9:23
Type: constitution
tex.article: I
tex.source: us

* statute
Citation Key: 11.9:24
Type: constitution
tex.article: IX
tex.source: southcarolina

* statute
Citation Key: 11.9:25
Type: constitution
tex.amendment: XIX
tex.source: us

* statute
Citation Key: 11.9:26
Type: constitution
tex.amendment: XIX
tex.eventdate: 1933
tex.source: us

* statute
Citation Key: 11.9:27
Type: constitution
tex.amendment: I–X
tex.source: us

* statute
Citation Key: 11.9:28
Type: charter
tex.article: 1
tex.part: 3
tex.source: unitednations

**Comment by zepinglee** [comment]
Thanks! It looks good to me.
