### ISSUE TITLE
Zotero 7 Beta: Refresh BBT Citation Keys makes Zotero unresponsive

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2664]
### Debug log ID

4Z5T67T5-euc/6.7.122-7

### What happened?

I would like to change the format of the Citation Keys in my library.
After modifying the Citation Key formula, I understand that I need to do a Refresh on all items in my library.

Just after triggering the Refresh, I get an empty popup window:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/fa2af2bc-ba72-4df4-a76a-93469324b4aa)
What is supposed to be in there?

For 10 items, that seems to work fine.
But already from 20 items, Zotero becomes unresponsive. It eventually manages to finish after some time.
Same for 100, successful after a longer time, increasing with the number of items to refresh.

The problem is that I would like to refresh my whole library, with 15k+ items. I could probably just wait long enough that everything is finished. But if I give up and close Zotero, none of the Citation Keys are changed when I restart Zotero.
It would be nice if:
- It could show some progress bar
- It could be split into smaller chunks automatically, so that I do not need to restart from scratch after restarting Zotero
- Give a final confirmation at the end that it was successful

Thank you very much for this plugin!

**Comment by retorquere** [comment]
I can replicate the popup, but not the slowdown. If I do 50 it's near instantaneous. I'll see what I can add for logging for diagnosis.

In the short term you can get rid of the popup by setting the [warning threshold](https://retorque.re/zotero-better-bibtex/installation/preferences/#warn-me-when-changing-citation-keys-in-bulk) to `0`.

**Comment by retorquere** [comment]
I think I know why and I think I have a solution for that, but that will have to wait until the weekend.

**Comment by mjthoraval** [comment]
I have received an email to install a test build:
> Install in Zotero by downloading [test build 6.7.122.2664.5137](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.122.2664.5137.xpi)

After installing the test build and restarting Zotero, the righ-click menu of BBT has disappeared:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/06743a32-381a-4321-99e8-7bdb6280cdb9)

Same for other BBT menus, so I cannot even send you a Debug log ID.
It seems that the menus apear for a short time just after starting, but then disappear.
I was able to get this one before it disappeared: IR68ZEDM-dVSV5ElK07C0

The report errors from Zotero gives:
```
1695925446509	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36


1695925447701	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\mjthoraval\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist"]
openWindowPrompt@resource://gre/modules/Prompter.jsm:1226:17
openPrompt@resource://gre/modules/Prompter.jsm:1067:12
openPromptSync@resource://gre/modules/Prompter.jsm:1046:10
alert@resource://gre/modules/Prompter.jsm:1329:17
alert@resource://gre/modules/Prompter.jsm:80:7
alert@jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/v494ek1z.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js:7312:15
sendAsync@jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/v494ek1z.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js:7341:16


appName => Zotero, version => 7.0.0-beta.42+2db19ad4c, os => Windows 10.0 19045, locale => en-GB, extensions => Better BibTex for Zotero (6.7.122.2664.5137, extension), Open PDF for Zotero (0.0.8, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Translate for Zotero (1.1.0-18, extension, disabled), Zotero Better Authors (3.4.0, extension, disabled), Better Notes for Zotero (1.1.4-25, extension, disabled)
```

**Comment by retorquere** [comment]
That wasn't supposed to go out, please install the release version.

**Comment by mjthoraval** [comment]
Thanks, it is back to the previous state.

**Comment by mjthoraval** [comment]
Or it is probably just an impression that nothing is happening.
If I look at the number in the Debug Output Logging, il continues to go up very quickly.
And after some time, Zotero still becomes unresponsive.

**Comment by mjthoraval** [comment]
Great! After a few minutes, the Refresh of my whole library is finally successful.
The total time is good I think.
But adding some kind of progress indication would make it less confusing probably.

Anyway, the problem is solved for me. Thank you very much!
Let me know if I can help do more testing, or just close this issue?

**Comment by retorquere** [comment]
I'm going to add the progress meter tomorrow, would appreciate you testing it - I don't have a library this size to test with.

**Comment by mjthoraval** [comment]
I have tested a bit the [test build 6.7.122.2664.5161](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.122.2664.5161.xpi).

If I change between the two citation key formulas below, I get a refresh of my full library (15k+) in around 6 minutes.
- auth.lower + shorttitle(3,3) + year
- auth.capitalize + year
If I simply refresh the library with the same formula as already implemented on all items, I get down to 2 minutes.

The notification that something is still running is nice.
Zotero still becomes unresponsive for the large part of the refresh.
But at least I know that it will finish in a reasonable time.
Refreshing citation keys is not something I will do every day, so the current processing time is fine.

Thanks!
