### ISSUE TITLE
Missing CITATION KEY in the 1st line of panel

### ISSUE THREAD

**Issue by wudidingdong** [retorquere/zotero-better-bibtex#2669]
### Debug log ID

E3B3WM7M-apse/6.7.123-7

### What happened?

Today I have update my Zotero 6 to Zotero 7 and I have installed the latest version of better bibtex. However, the CITATION KEY in the first line of the panel disappear (see the figure). One should emphasize that I could still see the citation key in the exported bib file. 

I have reinstall Zotero 7 and better bibtex plugin, the problem still existed. 

Debug log ID: E3B3WM7M-apse/6.7.123-7. Thanks for your help.

![image](https://github.com/retorquere/zotero-better-bibtex/assets/40603060/0391f14b-f14b-4db5-8d5b-54ff0f1a6b7a)

**Comment by retorquere** [comment]
See first bullet point of top post on #2522.
