### ISSUE TITLE
pandoc -s --lua-filter=zotero.lua problem

### ISSUE THREAD

**Issue by jasonandjack1997** [retorquere/zotero-better-bibtex#2673]
### Debug log ID

NA it is about the pandoc filter

### What happened?

Sorry, but It drives me crazy. When I spent hours trying to do this:
**https://retorque.re/zotero-better-bibtex/exporting/pandoc/**

this command won't work as it shows I need lua 2.16.2 at least. However, I have that and the latest version, but they both won't work. 
**pandoc -s --lua-filter=zotero.lua**

When I look at the pandoc filter lua file linked here 
https://retorque.re/zotero-better-bibtex/exporting/zotero.lua
I found it could be the problem here as written in the code:
if lpeg == nil then
  print('upgrade pandoc to version 2.16.2 or later')
  os.exit()
end

So the message might be the issue of lpeg. 
Then I tried to luarocks install lpeg. Then error showed I don't have cl. So I installed the big visual studio and got cl. Then another error that lua.h cannot find stdarg.h. Then I copied then another .h is missing. Finally:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/87abf38e-eac8-4c0e-bdb3-b20b92a87fd7)

I am really crazy. But I really need this feature to have live zotero citations in text file converted to word. I love this feature and I wish I could make it!

All the best

**Comment by jasonandjack1997** [comment]
it is not about the plugin. It is about using your pandoc filter to do document conversion.

**Comment by retorquere** [comment]
You don't need Lua 2.16.2, you need pandoc 2.16.2. Pandoc has a builtin Lua, it doesn't use the command line Lua, and it doesn't support Luarocks.

**Comment by jasonandjack1997** [comment]
> You don't need Lua 2.16.2, you need pandoc 2.16.2. Pandoc has a builtin Lua, it doesn't use the command line Lua, and it doesn't support Luarocks.

Thanks for the reply. Yes I installed the latest pandoc  3.1. 8 got the error and then changed  to 2.16.2 still the same error. 

One question is that do I need to run this if I want to convert a md file with citation into a docx file:
pandoc -s --lua-filter=zotero.lua --metadata=zotero_scannable_cite:true --metadata=zotero_client:jurism ...

what I ran is pandoc -s --lua-filter=zotero.lua -- -f docx -o test.docx test.md

Or should I do something else?

**Comment by retorquere** [comment]
3.1.8 should do fine. I have 3.1.6.1 and that works. What does `pandoc --version` say?

> what I ran is pandoc -s --lua-filter=zotero.lua -f docx -o test.docx test.md

That's fine, you can use the `--metadata` parameters if you want but it's more convenient to have the setup in the markdown yaml header such as

```
---
title: 'The rhetoric of tests'
bibliography: library.json
csl: apa7.csl
zotero:
    csl-style: apa7 # pre-fill the style
papersize: a4
---
```

**Comment by jasonandjack1997** [comment]
> 3.1.8 should do fine. I have 3.1.6.1 and that works. What does `pandoc --version` say?
> 
> > what I ran is pandoc -s --lua-filter=zotero.lua -f docx -o test.docx test.md
> 
> That's fine, you can use the `--metadata` parameters if you want but it's more convenient to have the setup in the markdown yaml header such as
> 
> ```
> ---
> title: 'The rhetoric of tests'
> bibliography: library.json
> csl: apa7.csl
> zotero:
>     csl-style: apa7 # pre-fill the style
> papersize: a4
> ---
> ```

Very thanks. I am new to pandoc. Just found that anaconda installed time ago also has a pandoc in and the version is lower. I changed the priorities in the sys and user PATH and the version issue is gone! Thanks!

Now the problem becomes:

>  pandoc -s --lua-filter=zotero.lua -f docx -o test.docx test2.md
couldn't unpack docx container: Did not find end of central directory signature
> pandoc --version
pandoc.exe 3.1.8
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\Administrator\AppData\Roaming\pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.


<img width="689" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/5700223/2fec2b2f-753c-4594-9c2b-a01db822381b">

**Comment by retorquere** [comment]
That looks to me like the docx template pandoc uses is broken. I think that if you just run pandoc without the lua filter you would get the same error message.

**Comment by jasonandjack1997** [comment]
Many thanks I think the curren issue is solved. Great thanks.
