### ISSUE TITLE
Have trouble converting md to docx with live citations

### ISSUE THREAD

**Issue by jasonandjack1997** [retorquere/zotero-better-bibtex#2674]
### Debug log ID

NA

### What happened?

Many thanks for your great work and thanks for solving my previous issue.

I tried to convert a md with citations to docx.
The docx file seems not showing keys as live citations. 

In the md file:
```
---
title: 'The rhetoric of tests'
bibliography: library.json
csl: apa7.csl
zotero:
    csl-style: apa7 # pre-fill the style
papersize: a4
---
@zuImpactMortalitySalience2021

@miron-spektorMotivatingCreativityEffects2015

@zuImpactMortalitySalience2021a
```

In the converted docx file they are yet plain text. Zotero doc preferences didn't help:
<img width="372" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/5700223/26b94ac3-0282-466d-a862-5e5af6ea6185">

I used the Citation Picker for Zotero plugin in vscode to insert citations. Haven't figure out how to drag and drop items  in vscode. 

I think I misconducted some key steps but I am new to this and didn't yet find helps in the issues sections.

**Comment by jasonandjack1997** [comment]
Found #2425 and I think a bracket worked!
or 
author-in-text: true!

BTW: If I want to convert md to docx, I don't need to export a bib or CSL JSON file I suppose? Just keep zotero open is fine?

All the best,

**Comment by retorquere** [comment]
If you feel no debug log is required, please use the [discussion board](https://github.com/retorquere/zotero-better-bibtex/discussions).

**Comment by retorquere** [comment]
> Found #2425 and I think a bracket worked! or author-in-text: true!

Correct.
 
> BTW: If I want to convert md to docx, I don't need to export a bib or CSL JSON file I suppose? Just keep zotero open is fine?

That is also correct.
