### ISSUE TITLE
Failing when exporting

### ISSUE THREAD

**Issue by Cadhor** [retorquere/zotero-better-bibtex#2677]
### Debug log ID

Q7Z9YIWT-euc/6.7.124-6

### What happened?

I installed better BibTex today, at first I could export without any problems, then I realized that the export had the key "journaltitle" and I needed the key "journal" to correctly read it on overleaf, so I tried to change it in the advanced settings "post-script", after that I can no longer export anything, I have tried to remove the "post-script" I made and left it blank again, but I can still not export anything using BibTex,

**Comment by retorquere** [comment]
There's an error in your BBT database. Can you send a new debug log, but also check the "include cache" checkbox in the error log screen?

`journaltitle` is a biblatex field, if you want `journal` the bibtex export will do that.

**Comment by Cadhor** [comment]
Thank you for the quick response, just did that and sent a new debug log with the cache, J2CSBU89-refs-euc/6.7.124-6

**Comment by retorquere** [comment]
Nothing strange in that database. Can you go into the help menu, choose "Restart with debugging enabled", let Zotero restart, reproduce the problem, and then send a new debug log?

**Comment by Cadhor** [comment]
Well, it seems to be working now... Maybe I only needed to reboot my computer, I tried several things yesterday, even uninstalling and reinstalling and it didn't fix it, but it seems like turning off and on my computer fixed it. Thanks anyway for all the trouble and the quick responses and very useful addon!
