### ISSUE TITLE
exporting changes some letters by {$<$}pan cla="enqoe"{$>$} in fields with words 

### ISSUE THREAD

**Issue by Dtress** [retorquere/zotero-better-bibtex#2679]
### Debug log ID

S9APD7WZ-euc

### What happened?

Dear retorquere,
When I export any collection with BBT either in Better BibTex or Better BibLaTeX, fields which contains letters, not only diacritics, are wrote with strange chains alternatively with normal letters. By example : journal = Politix is transformed in journal = {P{$<$}pan cla="enqoe"{$>$}liix}.
Fields with numeric chains are correctly exported as the paths in the field file.
I tested with the default Zotero BibLaTex export and the result is OK.

```
@article{darmonNotionCarriereInstrument2008,
  title = {{La n{$<$}pan cla="enqoe"{$>$}i{$<$}pan cla="enqoe"{$>$}n d{$<$}pan cla="enqoe"{$><$}pan cla="enqoe"{$>$}arri\`er{$<$}pan cla="enqoe"{$>$}:n inrm{$<$}pan cla="enqoe"{$>$}n in{$<$}pan cla="enqoe"{$>$}ra{$<$}pan cla="enqoe"{$>$}i{$<$}pan cla="enqoe"{$>$}nni{$<$}pan cla="enqoe"{$>$}d'{$<$}pan cla="enqoe"{$>$}bj{$<$}pan cla="enqoe"{$><$}pan cla="enqoe"{$>$}ivai{$<$}pan cla="enqoe"{$>$}n}},
  shorttitle = {{La n{$<$}pan cla="enqoe"{$>$}i{$<$}pan cla="enqoe"{$>$}n d{$<$}pan cla="enqoe"{$><$}pan cla="enqoe"{$>$}arri\`er{$<$}pan cla="enqoe"{$>$}}},
  author = {Darm{$<$}pan cla="enqoe"{$>$}n, Mri{$<$}pan cla="enqoe"{$>$}l},
  year = {2008},
  journal = {P{$<$}pan cla="enqoe"{$>$}liix},
  volume = {82},
  number = {2},
  pages = {149},
  issn = {0295-2319, 1953-8286},
  doi = {10.3917/p{$<$}pan cla="enqoe"{$>$}x.082.0149},
  urldate = {2014-10-09},
  langid = {fr{$<$}pan cla="enqoe"{$>$}n{$<$}pan cla="enqoe"{$>$}h},
  file = {/home/pierre/Zotero/storage/FZ49D7Q8/notion_de_carrière_Darmon_Muriel.pdf;/home/pierre/Zotero/storage/HK4QZT47/-CSCO-3h--revue-politix-2008-2-page-149.html}
}
% == BibTeX quality report for darmonNotionCarriereInstrument2008:
% ? unused Library catalog ("CrossRef")
% ? unused Url ("https://nomade.etu.univ-nantes.fr/+CSCO+3b756767633A2F2F6A6A6A2E706E7665612E76617362++/-CSCO-3h--revue-politix-2008-2-page-149.htm")
```

Best regards.

Pierre

**Comment by retorquere** [comment]
You're on BBT 6.7.93, please upgrade to the latest version and see if the problem still exists.

**Comment by Dtress** [comment]
I have updated to BBT 6.7.124 but the problem remains
Debug log ID
M4AACL7Y-euc/6.7.124-6

**Comment by retorquere** [comment]
I'll need you to right-click that entry and send a better bibtex debug log from the menu that pops up. De log ID will have `-refs-` in it.

**Comment by retorquere** [comment]
I have imported the item from https://www.cairn.info/revue-politix-2008-2-page-149.htm?ref=doi&contenu=citepar and I can't reproduce the problem. A `-refs-` logs will tell me more.

**Comment by Dtress** [comment]
I can't reproduce it on another computer too.
And now I can't create a debug log. I have this message : 
translate in English by me : memory is overfull ! Zotero on Windows has restrictions
I use a Debian bookworms
![Screenshot_20231016_180147](https://github.com/retorquere/zotero-better-bibtex/assets/85844600/973cf8c3-3532-4445-857a-7d6cf7a573c4)

**Comment by Dtress** [comment]
The Zotero errors journal gives this message
[JavaScript Error: "TypeError: this.errorlog is undefined" {file: "chrome://zotero-better-bibtex/content/better-bibtex.js" line: 125022}]

[JavaScript Error: "TypeError: this.errorlog is undefined" {file: "chrome://zotero-better-bibtex/content/better-bibtex.js" line: 125022}]

[JavaScript Error: "IndexedDB Maintenance finished with error: NS_ERROR_NOT_AVAILABLE: ActorsParent.cpp:16691"]

version => 6.0.27, platform => Linux x86_64, oscpu => Linux x86_64, locale => fr-FR, appName => Zotero, appVersion => 6.0.27, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.27, extension), Better BibTex for Zotero (6.7.128, extension)

**Comment by retorquere** [comment]
A debug log will drop in 10 minutes or so that might tell me more, but there's something really strange at play. The memory log message is put there when it is detected in the log file, but I only monitor the log file when Zotero tells me it's running under Windows.

**Comment by Dtress** [comment]
NYGBX2Q7-euc/6.7.129.2679.5242-6
After "Install in Zotero by downloading [test build 6.7.129.2679.5242]"
cache is included
ERROR message when I launch the debug journal : 
La mémoire de Zotero est saturée ! Zotero sur Windows a des restrictions d'utilisation de la mémoire qui seront améliorées par Zotero 7. En attendant, veuillez désactiver la mise en cache de Better BibTeX et redémarrer Zotero.

Thank you very much for your attention.

**Comment by Dtress** [comment]
I am very sorry to cause you this busy problem. Here is the ID log
RZFICWGD-euc/6.7.130-6
The message complaining about Windows disappeared. But the main problem remain.
Best regards

**Comment by Dtress** [comment]
Oh sorry I have make a mistake, don't pay attention to the message above

**Comment by Dtress** [comment]
with the [test build 6.7.129.2679.5245]
47Z3W2HX-euc/6.7.129.2679.5245-6

**Comment by Dtress** [comment]
PKXUBIYG-euc/6.7.130-6

**Comment by retorquere** [comment]
> I'll need you to right-click that entry and send a better bibtex debug log from the menu that pops up. De log ID will have `-refs-` in it.

**Comment by Dtress** [comment]
2MGNCC33-refs-euc/6.7.133-6
Is it right ?

**Comment by retorquere** [comment]
Mostly -- can you export that item as RDF and attach it here?

**Comment by retorquere** [comment]
You have set the preference `csquotes` to the text `csquotes`. That's not how it's supposed to be used. If you clear it, the problem will go away.

**Comment by Dtress** [comment]
Please, where is set this preference ?

**Comment by retorquere** [comment]
Go into the Zotero [hidden preferences](https://www.zotero.org/support/preferences/hidden preferences), search for `csqoutes`, edit it and clear its contents. But you must have been here before, this is the only UI available to edit them. The hidden prefs are advanced usage so they're not exposed in the regular UI.

**Comment by Dtress** [comment]
Dear Retorquere, thank you very much for pains due to my mistake.
Have more interesting problems to solve.

**Comment by retorquere** [comment]
> Dear Retorquere, thank you very much for pains due to my mistake.
> Have more interesting problems to solve. 

I don't know what you mean by this. Is the problem solved?

**Comment by Dtress** [comment]
My English is awful !
Yes problem solved
