### ISSUE TITLE
Feature request: Quick Copy / Citation picker support for nbconvert/Jupyter

### ISSUE THREAD

**Issue by saf-dmitry** [retorquere/zotero-better-bibtex#2681]
### Debug log ID

NA

### What happened?

Please add Quick Copy/drag-and-drop and citation picker support for syntax compatible with the [nbconvert](https://nbviewer.org/github/jupyter/nbconvert-examples/blob/master/citations/Tutorial.ipynb) tool for converting and exporting Jupyter Notebooks. Here is an example of what you would type into a Markdown cell:

```
<cite data-cite="granger2013">(Granger, 2013)</cite>
```

Here, `grander2013` should be the citation key generated by BBT. As far as I understand, one citation can contain only one item.

**Comment by saf-dmitry** [comment]
I cannot send a debug log, because it appears to  be empty.

**Comment by retorquere** [comment]
Is this Zotero 6 or 7 beta?

**Comment by saf-dmitry** [comment]
> Is this Zotero 6 or 7 beta?

Zotero 6.0.28

**Comment by saf-dmitry** [comment]
I've just installed the build 6.7.130. The "out of memory" error message is gone. I submitted a debug log.

Debug log ID: GZCFLH7T-euc/6.7.130-6

**Comment by retorquere** [comment]
Al right. Can you test the jupyter quick copy?

**Comment by saf-dmitry** [comment]
I briefly tested the new Jupyter notebook Quick-Copy format. It appears to work just fine. Thank you for your prompt help!

Looking forward to see the format support in citation picker a.k.a. Cite as you write (CAYW)!

By the way, I'm wondering why the formats supported by Quick-Copy and CAYW are different. For example, CAYW supports MultiMarkdown (MMD) citations, while Quick-Copy don't.

**Comment by retorquere** [comment]
This format isn't really a standard for jupyter it seems - quarto and jupyterbook have a different syntax. Where is this format documented?

**Comment by saf-dmitry** [comment]
> This format isn't really a standard for jupyter it seems - quarto and jupyterbook have a different syntax. Where is this format documented?

Unfortunately, there is no "official" format for citations in Jupyter notebooks (as far as I know).

[Nbconvert](https://nbconvert.readthedocs.io/en/latest/) is one of the most adopted tools for converting Jupyter notebooks into another static format including HTML, LaTeX, PDF, Markdown, reStructuredText, and more. The citation format is documented in the official [nbconvert documentation](https://nbconvert.readthedocs.io/en/latest/latex_citations.html).

Quarto and pandoc use pandoc citation format. Jupyter Book uses MyST Markdown flavour and requires installing an extension for JupyterLab to render MyST in Markdown cells.

There are also extensions for managing citations from Zotero in Jupyter notebooks: [cite2c](https://github.com/takluyver/cite2c) for Jupyter Notebook and [jupyterlab-citation-manager](https://github.com/krassowski/jupyterlab-citation-manager) for JupyterLab. Both extensions use formats that are similar to nbconvert citation format, but the user's reference database is accessed online using the API key (no support for local Zotero installation 😞).

The is also the Calico Document Tools, but the project is apparently dead by now.  A description can be found [here](https://jupyter.brynmawr.edu/services/public/dblank/jupyter.cs/Examples/Calico%20Document%20Tools%20and%20Bibtex.ipynb).

> What other features does jupyter citation support (stuff like page number etc)?

As far as I know, you can put  basically anything between the opening and closing `cite` tags. This part is only rendered in Jupyter notebook, but is completely replaced by nbconvert according to the citation style used. I.e., only citation key matters, everything else, like page numbers, will be ignored by the conversion process.

**Comment by retorquere** [comment]
> As far as I know, you can put basically anything between the opening and closing cite tags. This part is only rendered in Jupyter notebook, but is completely replaced by nbconvert according to the citation style used.

Is there any documentation on this format? It's pretty anemic if it doesn't support locator rendering.

**Comment by saf-dmitry** [comment]
> Is there any documentation on this format? It's pretty anemic if it doesn't support locator rendering.

The citation format is documented in the official [nbconvert documentation](https://nbconvert.readthedocs.io/en/latest/latex_citations.html).

Citations are handled by the [citation2latex](https://nbconvert.readthedocs.io/en/latest/api/filters.html#nbconvert.filters.citation2latex) filter as part of the nbconvert tool. Looking in the [source code](https://github.com/jupyter/nbconvert/blob/main/nbconvert/filters/citation.py) of the filter will tell you the "ultimate truth" how citations are handled. Like stated in the documentation, you can use basically any HTML tag with a `data-cite` attribute. The output LaTeX `\cite{...}` command is hardcoded, i.e., there is no place to accommodate locators. To implement locator handling like e.g., `\cite[<locator>](<citation_key>)` you could modify the citation filter accordingly.

**Comment by retorquere** [comment]
I'll need you to test this before I integrate this into a release.

**Comment by saf-dmitry** [comment]
The provided link to [test build 6.7.136.2676.5340](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.136.2676.5340.xpi) is broken.

What exactly should I test? Quick Copy functionality? CAYW citation picker (what URI format)?

**Comment by retorquere** [comment]
Builds expire. I'll get you a new build later. It has both CAYW and quick copy, format is `jupyter`.

**Comment by saf-dmitry** [comment]
Quick Copy works as expected, but CAYW can't find the required format:

![Screen Shot 2023-11-24 at 16 41 29](https://github.com/retorquere/zotero-better-bibtex/assets/30050534/f6b32a4b-96d5-4087-b63f-9e174b36bdda)

**Comment by saf-dmitry** [comment]
Now both, Quick Copy and CAYW citation picker, work as expected 👍.

**Comment by saf-dmitry** [comment]
Please, don't forget to add the new CAYW format to the [documentation page](https://retorque.re/zotero-better-bibtex/citing/cayw/index.html).

**Comment by retorquere** [comment]
I'll add them, there's currently a problem with updating the site, so I don't know how long it'll take.

**Comment by retorquere** [comment]
they have been added
