### ISSUE TITLE
Database changed during migration

### ISSUE THREAD

**Issue by vijaymarupudi** [retorquere/zotero-better-bibtex#2684]
### Debug log ID

JZGY99E2-cRXxRwuSbZKf

### What happened?

I've written some scripts to use the `better-bibtex.sqlite` file to extract some data. Looks like my better-bibtex updated yesterday, and there seems to be some evidence of database corruption? I get this error on the command line.

```
$> sqlite3 better-bibtex.sqlite '.schema'
Error: malformed database schema (autoexport_setting_insert) - trigger autoexport_setting_insert cannot reference objects in database betterbibtex
```

I haven't noticed anything wrong when I open Zotero, but didn't try to change anything in fear of data loss.

When I recover the database, like this

```
$> sqlite3 better-bibtex.sqlite '.recover' | sqlite3 recovered.sqlite
```

I can use the recovered.sqlite file just fine using my script.

**Comment by retorquere** [comment]
The database isn't corrupt, but needs a different way to access from outside Zotero. You need to issue

```
ATTACH DATABASE '<path to better-bibtex.sqlite>'  AS betterbibtex
```

after which you can read the database as `betterbibtex."better-bibtex"`.

**Comment by vijaymarupudi** [comment]
I see, I had no idea, thank you for the information, and all your work on Better BibTeX!

**Comment by retorquere** [comment]
Thanks! There's no way you could have known.

**Comment by kasuar** [comment]
Where exactly do I issue the following command: 

ATTACH DATABASE '<path to better-bibtex.sqlite>'  AS betterbibtex

I'm a "simple" Zotero user, with a stand-alone installation within Windows 11. Because of the issue described by the original poster, zotsite doesn't work anymore.

**Comment by retorquere** [comment]
Somewhere in https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/betterbib.py, but I'd prefer it if @plandes reaches out for the fix. I'll help with the fix but I have no idea what it does or how it does it, so I won't be testing anything.

**Comment by plandes** [comment]
This is now fixed.  Thanks everyone for seeing this before I did, and particularly @retorquere for the archaic SQLite `attach database` code 🙂.

I have [released version 0.8.2](https://github.com/plandes/zotsite/releases/tag/v0.8.2) and deployed. This should fix it @kasuar:

```bash
pip install -U zensols.zotsite
```

**Comment by retorquere** [comment]
Archaic? Database schemas are a fairly fundamental feature in databases.

**Comment by plandes** [comment]
@retorquere I added that previous comment to the wrong issue (sorry for the confusion).  Right, schemas are a fundamental feature, but I'm not very familiar with SQLite, never used the feature, or created `:memory:` connections.
