### ISSUE TITLE
Zotero 7 no longer display citation key in info pane

### ISSUE THREAD

**Issue by SongshGeo** [retorquere/zotero-better-bibtex#2691]
### Debug log ID

ZDEBMLDE-euc/6.7.132-7

### What happened?

After updating to Zotero 7 and the newest `better-bibtex`, the citation key field disappeared in the info pane. I searched for issues but was surprised that I found no related report. I neither found any related setting item in preference settings. Am I missing something?

**Comment by retorquere** [comment]
#2522 

> Open issues:
> 
> * [ ] citekey display/edit field awaits API from Zotero ([#](https://groups.google.com/g/zotero-dev/c/dzBI00ptxGw/m/EA7LS6JyAAAJ))
