### ISSUE TITLE
Cannot change and update citation key

### ISSUE THREAD

**Issue by Gao-XianLin** [retorquere/zotero-better-bibtex#2692]
### Debug log ID

AP6A4VB5-apse/6.7.131.2522.5272-7

### What happened?

Hi, 

I was trying to update my citation key formula. However, it seems that no matter what I enter, when I close the panel and reopen it, there is always an orange field as well as an "Active citation key formula". I also tried entering "zortero:clean", but it comes back with the same problem (an orange field as well as an "Active citation key formula"). 

Would you be so kind as to let me know how to fix it? Thanks in advance for any advice or help on this!

**Comment by retorquere** [comment]
Please upgrade to 6.7.132 first, then reproduce.

**Comment by Gao-XianLin** [comment]
Hello, thank you for quick response! Yes, I have upgraded and reproduced the issue. The new debug log id is: WPEN5MF5-apse/6.7.132-7

Thank you!

**Comment by Gao-XianLin** [comment]
Hello, thank you for creating the build. I've downloaded and installed it. But it seems the problem persists. I created another new debug log: BFYDIJJD-apse/6.7.133.2692.5291-7

Thank you so much for your help!!

**Comment by Gao-XianLin** [comment]
Hello thank you so much! Now it seems I can change the citation key formula but I still cannot update my items' citation key. I tried to create a debug log: DI7DLFQI-refs-apse/6.7.133.2692.5294-7
Thank you so much for your help!

**Comment by retorquere** [comment]
Is the item whose key you tried to update the item in `DI7DLFQI-refs-apse/6.7.133.2692.5294-7` (an article by Andisheh Vahedi)? Because that has a pinned key, it won't update unless you force-refresh it.

**Comment by Gao-XianLin** [comment]
Wow, exactly! After unpinning the keys, I saw that I can now update the citation key smoothly without any problem! Thank you so so much!
