### ISSUE TITLE
Closing + reopening the Z7 window makes the BBT menu disappear on macOS

### ISSUE THREAD

**Issue by champagnealexandre** [retorquere/zotero-better-bibtex#2694]
### Debug log ID

can’t send

### What happened?

Hi,

I don’t remember if this was discussed already, but the BBT menu disappears when closing+reopening the Zotero 7 window on macOS. This is actually pretty similar to [issue 8](https://github.com/retorquere/zotero-open-pdf/issues/8) from the zotero-open-pdf plugin. I’ve searched the issues in the BBT repo and can’t find any reference to this behavior.

If this problem is caused by Zotero still being in beta feel free to close the issue. I haven’t sent a bug report as the menu disappears, so I’m not sure how should I do it when reproducing the bug.

Thanks again for the hard work on BBT.

**Comment by champagnealexandre** [comment]
> **PS: If the Debug Log menu does not appear, or it does not send the debug log**
> 
> A fallback option is available under "Help" > "Send debug log to file.io".

I’ve just tried this but the "Send debug log to file.io" menu disappears too!

**Comment by retorquere** [comment]
That disappears 15 seconds after load has succeeded. A new build will drop here in 10 minutes or so.

**Comment by champagnealexandre** [comment]
Seems to be working fine now! Thank you!
