### ISSUE TITLE
Database corrupted through cloud sync

### ISSUE THREAD

**Issue by 284479754** [retorquere/zotero-better-bibtex#2695]
### Debug log ID

WBTQQ3HC-5PBLHParEtaK

### What happened?

need help to solve the probelm
![image](https://github.com/retorquere/zotero-better-bibtex/assets/13973637/d1327bfc-d43c-4043-8086-50cf154d7c7a)

**Comment by 284479754** [comment]
Following the step 2, i get an id : SL8EBD2A-mzvINnzh6cPe
![image](https://github.com/retorquere/zotero-better-bibtex/assets/13973637/67647fb1-ac6a-4cec-9d47-be2cd642a699)

**Comment by retorquere** [comment]
I think your `zotero.sqlite` and `better-bibtex.sqlite` are in a cloud-synced drive. You [don't want to do that](https://www.zotero.org/support/kb/data_directory_in_cloud_storage_folder). It is likely the reason you got the current problem. Build 5297 should fix it, but you want to have these two files outside cloud-synced folders.

**Comment by retorquere** [comment]
Did you not get a warning about this? I think Zotero should have detected this.

**Comment by 284479754** [comment]
Thanks for  your help. Exactly, i have got this warning on sqlite corruption, but i ignored them.  Now ,i have move all my zotero file to the default location, but the sqilte can not be restored, maybe i have delete the bak file careless. Please help check the figures below, what should i do in the next? Thanks a lot!
![image](https://github.com/retorquere/zotero-better-bibtex/assets/13973637/6ae842ab-b6a4-4a4b-97f4-8e8cb4d832cf)

![image](https://github.com/retorquere/zotero-better-bibtex/assets/13973637/f1ae8a98-bcaa-436d-a68a-e30cc98fca00)

**Comment by retorquere** [comment]
> what should i do in the next? 

You have to ask about this in the [https://forums.zotero.org/](Zotero forums). Database corruption through cloud sync is a Zotero issue, not a BBT issue.

**Comment by 284479754** [comment]
Thanks a lot!
