### ISSUE TITLE
urldate when only DOI is exported

### ISSUE THREAD

**Issue by D4NNYH** [retorquere/zotero-better-bibtex#2697]
### Debug log ID

CTHI4PWF-refs-euc/6.7.133-6

### What happened?

I have selected only to export the DOI when both DOI and url are available and it still contains the urldate when exported. I believe its the same issue as issue #869 that another use had a few years ago.

**Comment by D4NNYH** [comment]
@retorquere 
HFX3F3M8-euc/6.7.133-6

**Comment by retorquere** [comment]
Sorry, the bot was on the fritz.
