### ISSUE TITLE
Citation key is not shown completely (is cut)

### ISSUE THREAD

**Issue by mikkovedru** [retorquere/zotero-better-bibtex#2699]
### Debug log ID

L4GHSZ9T-euc/6.7.135-6

### What happened?

Using the latest Zotero 6.0.27 and Better BibTeX version 6.7.135 on Linux.

Citation key in the Info panel cuts the name, despite there being a lot of space on the right.

![image](https://github.com/retorquere/zotero-better-bibtex/assets/2521942/b36e1b4a-5950-4ccd-8d2e-b457af501f3f)
Instead of `1996_CultureHonorPsychologyViolenceSouth_byNisbetta`, it only shows half.

I [have been told](https://forums.zotero.org/discussion/109058/bug-citation-key-is-not-shown-completely) that this is an issue which I should report here.

**Comment by mikkovedru** [comment]
Works great now, thank you!
![image](https://github.com/retorquere/zotero-better-bibtex/assets/2521942/2528d4a2-372d-4718-8091-4bf4371f923a)

**Comment by retorquere** [comment]
It'll be in the next release.

Just out of curiosity, do you really use keys this long?

**Comment by mikkovedru** [comment]
> Just out of curiosity, do you really use keys this long?

Yes. The thing is that I don't use Zotero for academic sources, but for all the .pdfs. This includes publications, books, etc.

Also, a big decision that influenced the chosen format was to use Zotero to keep all the copies of my reference web pages. So let's say max 100 pages a day, 365 days, 40 years of the rest of my life: 1.5M files. Iso dates in names help a lot, but having sensible search terms directly as part of the name is much better.

You can see the usefulness easily in the names of the books, when the main name can just be gibberish, but the secondary name after the colon is the one that has proper information:
- Harmful to Minors: The Perils of Protecting Children from Sex
- Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential
- Algorithms to Live By: The Computer Science of Human Decisions
- Connect: Building Exceptional Relationships with Family, Friends, and Colleagues 
, you get the point.

The same thing with the article/news pages.
- **‘He probably didn’t believe they were live munitions’**. Questions abound after top Ukrainian military aide killed by grenade he received for his birthday
- **What’s the catch?** In Russia’s Saratov region, the authorities’ response to a film about housing shows art can still shame the government into action

All those would be referenced in my Obsidian Zettelkasten. And sure, the keys could just look random and I could open them every time I would have needed, but for sure getting the idea about the content right there in the name is so much better!

It's the same idea as properly naming not only my Obsidian notes, but also the images that are part of those notes. Sure, some sort of random UID would work as well, but having sensible names is better, especially if I want to search or reference files from other notes.

In the end this idea of using .pdf and Zotero to keep news/articles archive didn't pan out, but the chosen naming scheme stayed because it is still much better than the Academic defaults.
