### ISSUE TITLE
CAYW failed on Zotero7

### ISSUE THREAD

**Issue by JohannaXiao** [retorquere/zotero-better-bibtex#2702]
### Debug log ID

699GKS9U-euc/6.7.136-7

### What happened?

Hello,

System: macOS Sonoma 14.1
Better-bibtex Version: 6.7.136
Zotero 7
I got the error:
`Better-bibtex: CAYW failed`
when I want to use the [obsidian-zotero-integration](https://github.com/mgmeyers/obsidian-zotero-integration)
And when I click on this button
![image](https://github.com/retorquere/zotero-better-bibtex/assets/62994240/df7bc3ea-42e2-4ae2-b1bf-1095a9488a1c)
It also generated this error. So I guess it's maybe related Better-bibtex directly.
I attached the error report just below.

Thanks in advance for anyone that can give me some help with it.
[RER9WQYE-euc.tgz](https://github.com/retorquere/zotero-better-bibtex/files/13243900/RER9WQYE-euc.tgz)

**Comment by retorquere** [comment]
Can you uninstall the "Zotero Citation" plugin and try again?

**Comment by retorquere** [comment]
No need to attach the debug log. The ID is sufficient.

**Comment by JohannaXiao** [comment]
> Can you uninstall the "Zotero Citation" plugin and try again?

Yes, It works now!! after uninstalling the "Zotero Citation". Thank you!

**Comment by retorquere** [comment]
That plugin is calling `console.log` which isn't always available, which caused the error. You might want to report that to the developer of that plugin.
