### ISSUE TITLE
[Feature Request] Add Zotero open links to BibTeX exported file

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2709]
### Debug log ID

T645FJ79-refs-euc/6.7.136-7

### What happened?

I would like to create a special bibliography style file (`.bst`) with an option to add the Zotero Open links in the bibliography, to either the item or the PDF file.
To do that, I would need to add custom fields in the BibTeX file (`.bib`), like:
- zoteroOpenItemLink = {...}
- zoteroOpenPDFLink = {...}

Is it possible to add an option to add these into the exported BibTeX file?

**Comment by retorquere** [comment]
You can do this using a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/index.html):

```
if (Translator.BetterTeX) {
  target.add({
    name: 'zoteroOpenItemLink',
    value: `zotero://select/items/${source.libraryID}_${source.itemKey}`,
    enc: 'verbatim'
  })
 
  const pdf = (source.attachments || []).find(att => att.filename.match(/[.]pdf$/i))
  if (pdf) {
    target.add({
      name: 'zoteroOpenPDFLink',
      value: `zotero://select/items/${source.libraryID}_${pdf.itemKey}`,
      enc: 'verbatim'
    })
  }
}
```

**Comment by mjthoraval** [comment]
Thank you very much!
The first link works nicely. But the second one is "undefined":
```
  zoteroOpenItemLink = {zotero://select/items/1_QI2X8MFR},
  zoteroOpenPDFLink = {zotero://select/items/1_undefined}
```

I would prefer actually to open the PDF file directly. So with a link like:
```
zotero://open-pdf/library/items/RSYFMBGW
```
See for example: https://forums.zotero.org/discussion/86980/quickly-create-a-open-pdf-link

But I don't know where I can find information on how to generate these keys and how to format the select and open-pdf links?

Debug log ID: PF9ZWX7B-euc/6.7.136-7

**Comment by retorquere** [comment]
I'm not sure whether I have enough information to detect whether it's the user library or a shared group, but please right-click an entry from each for which you want this export and send a BBT debug log from the popup menu. The ID will have `-refs-` in it.

**Comment by retorquere** [comment]
(and please include the entry for which you get an `undefined`)

**Comment by mjthoraval** [comment]
I have restarted Zotero with logging enabled.
Then exported one item.
Then sent the debug log through a right-click on the item that I have just exported.
Debug log ID: GRB7GEHZ-refs-euc/6.7.136-7

Here is the corresponding output I get for that item:
```
  zoteroOpenItemLink = {zotero://select/items/1_DK2ZUDQY},
  zoteroOpenPDFLink = {zotero://select/items/1_undefined}
```

And another one:
```
  zoteroOpenItemLink = {zotero://select/items/1_3APZ3FJN},
  zoteroOpenPDFLink = {zotero://select/items/1_undefined}
```
Debug log ID: Q6H64ZEY-refs-euc/6.7.136-7

> (and please include the entry for which you get an `undefined`)

I am getting an `undefined` for any item that I export.
I am not sure how to include the entry?

**Comment by retorquere** [comment]
I've modified the script above, please retry.

**Comment by mjthoraval** [comment]
If there is only one PDF file as attachment, it is working:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/0fad53f1-0995-44f7-87a3-bcc1cf98fc65)
```
  zoteroOpenItemLink = {zotero://select/items/1_NAQWBWJ8},
  zoteroOpenPDFLink = {zotero://select/items/1_L8VPLV25}
```
Debug log ID: VUIIZPKM-refs-euc/6.7.136-7

If there are multiple attachment, I only get the first one:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/e21b55b9-7cce-44c7-82d0-d2ff3cfb8ea8)
```
  zoteroOpenItemLink = {zotero://select/items/1_QI2X8MFR}
```
Debug log ID: NLUW9XB5-refs-euc/6.7.136-7

**Comment by retorquere** [comment]
You proposed one field, I don't see how I can add multiple links in it.

**Comment by retorquere** [comment]
Or by first one you mean the openitem field, and not the openpdf link?

**Comment by mjthoraval** [comment]
Yes

**Comment by mjthoraval** [comment]
> You proposed one pdf field, I don't see how I can add multiple links in it.

I just need to open the default PDF file that is opened by a double click on the item.

**Comment by retorquere** [comment]
Script above updated again.

**Comment by mjthoraval** [comment]
Thank you very much! It is working now.

From this post below, it seems that the format with the `libraryID` is the old formatn while the new format should use `groupID`?
https://forums.zotero.org/discussion/86980/quickly-create-a-open-pdf-link

And from here, they mention the new format:
https://github.com/zotero/zotero/blob/7c5600913b5baa659a1eb5277cb1529b0454089a/components/zotero-protocol-handler.js#L811
https://github.com/zotero/zotero/blob/7c5600913b5baa659a1eb5277cb1529b0454089a/components/zotero-protocol-handler.js#L1130

Will these link remain valid or will they break after some time?

**Comment by retorquere** [comment]
That runs in an entirely separate environment, there's very little that applies to both of those.

**Comment by retorquere** [comment]
Postscripts tap into how zotero represents the items to all translators. That provides some incentive to Zotero to keep these objects stable as many translators may depend on them, but ultimately I don't control when or how zotero makes changes to them.

**Comment by mjthoraval** [comment]
Thank you for the explanations.
