### ISSUE TITLE
Additional whitespaces in front of locators and in suffixes in zotero.lua

### ISSUE THREAD

**Issue by jmiba** [retorquere/zotero-better-bibtex#2716]
### Debug log ID

S423WZGG-refs-euc/6.7.136-6

### What happened?

The lua filter zotero.lua used for transforming citekeys to live Zotero citations in Pandoc markdown-to-docx exports adds additional whitespaces in front of locators and produces suffixes that contain only a whitespace:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/8625511/0472b140-cc9c-4d2e-ac25-770285d48e38)
and (double whitespace):
![image](https://github.com/retorquere/zotero-better-bibtex/assets/8625511/f2335827-5eb6-4184-8993-3d81f50e4272) 

I worked around this by adding `:gsub("(%S+)%s+", "%1 "):gsub("^%s*(.-)%s*$", "%1")` to **line 1865** of the zotero.lua script:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/8625511/e367d6bd-f5f3-401b-9622-f96b58fb8a51)

But I'm sure this is very inelegant.

**Comment by retorquere** [comment]
I'll need the source document to debug this.

**Comment by jmiba** [comment]
> I'll need the source document to debug this.
I work with Obsidian and the Pandoc Plugin for Obsidian. My source document is markdown and looks anything like this:
```
---
lang:
  - de
zotero:
  library: 
  scannable-cite: false
  author-in-text: false
  csl-style: chicago-author-date
---
# Test
Does it work? [@campbell2021 15; or @moore2021 p. 31] .
Well, it does. [@wilke chap. 7, S. 1-13]

```
The Pandoc plugin is configures with a defaults file that looks like this:
```
resource-path: 
  - .
  - ${.}/Second Brain/02 Dateien/Medien/
from: markdown+wikilinks_title_after_pipe+mark+lists_without_preceding_blankline
bibliography: 
  - ${.}/Second Brain/02 Dateien/Bibliographie/Meine Bibliothek.json
filters:
  - ${.}/Second Brain/.obsidian/zotero.lua
```
The bibliography file is stated for a fall back. It works like a charm (great filter, really), apart from the added whitespaces in suffixes.

**Comment by retorquere** [comment]
I've tried adding the proposed fix, and locally my tests run OK, but in my CI environment I'm getting

```diff
-        "suffix": ", esp.\ufffd chapters 1 and 6"
+        "suffix": ", esp.\u00a0chapters 1 and 6"
```

meaning there previously was a unicode replacement character (of which I don't yet understand how it got there) followed by a space, and those being replaced with a non-breaking space (of which I don't understand how it got there).

I'm trying to figure out what's happening here, but I don't want to disable the test.

**Comment by retorquere** [comment]
If I add that gsub line, for some reason I'm getting [errors](https://github.com/retorquere/zotero-better-bibtex/actions/runs/7003153455/job/19048416011#step:9:2088) when I run my tests on the test githubs infra that I cannot reproduce locally. Any idea? I have no idea where that non-breaking space comes from, but it's only there when I add the gsubs you proposed.

**Comment by retorquere** [comment]
Wait that's not right, I'm getting the NBSPs too locally -- looking into it.

**Comment by jmiba** [comment]
> it's only there when I add the gsubs you proposed

Actually, I did not really propose these as they seem to correct an error that happens earlier. I just used them for myself as a workaround.

**Comment by retorquere** [comment]
Can you try the new version from the site (revision 1fb47fe)?

**Comment by jmiba** [comment]
I tested the revised zotero.lua filter and this is what happens:
- the Word document converted to live citations looks OK
- after conversion, editing the citations of this type [@bmbf2023] or [@bmbf2023 12] (source markdown document) works as expected
- editing citations with explicitely stated locators [@bmbf2023 chap. 3] or [@bmbf2023 p. 24] shows that there is an additional whitespace in front of the digit:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/8625511/c7c714e6-5b66-42fc-a28e-c1bd13424a97)

**Comment by retorquere** [comment]
There's a new version up that will remedy that. Turns out Pandoc was inserting the NBSPs.
