### ISSUE TITLE
word zotero field code currpted

### ISSUE THREAD

**Issue by jasonandjack1997** [retorquere/zotero-better-bibtex#2718]
### Debug log ID

V4C94885-refs-euc/6.7.137-7

### What happened?

I am converting a md file with bbt citations to a word file. In the converted word document when click zotero referesh the error bellow occurs and the citations are deleted automatically!
I opened the converted word files weeks ago which could be refershed and updated to live ciations  and did the same actions, but even these files show the same errors as below: zotero code corrupted, and citations got deleted.

The command:
pandoc -s --lua-filter=zotero.lua -o paperback.docx paper.md

The md file:

```markdown
---
zotero:
    csl-style: apa7 # pre-fill the style
    author-in-text: true
---

Creativity, a fundamental feature of human intelligence, has long been a challenge for AI 
[@ArtifIntellRev2022AnantrasirichaiArtificialIntelligenceCreative]
[@NatHumBehav2023WebbEmergentAnalogicalReasoning; @2023ZhangExploringMITMathematics; @InternetofThingsandCyber-PhysicalSystems2023RayChatGPTComprehensiveReview]
```

The word file
![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/7b41679c-6f6c-4e24-bff8-58d0395826de)

The error when referesh:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/0021ca14-129a-4664-9bf7-93b12d8d8aca)

I have nearly a hundred ciations in that paper and now don't know what to do .

Another question is some citations have the "not in zotero" in the pandoc converting process but the keys are actual keys of items. 

Best,

**Comment by jasonandjack1997** [comment]
> Hello there @jasonandjack1997,
> 
> Hope you're doing well! `@retorquere` is here to help you get the most out of your experience with Better BibTeX. To make sure he can assist you effectively, he kindly asks for your cooperation in providing a debug log – it's like giving him the key to understanding and solving the puzzle!
> 
> Getting your debug log is a breeze and will save us both time in getting your problem resolved or the new feature you'd like implemented. Trust me, it's way quicker than discussing why it's important. 😃
> 
> **How to Share Your Debug Log:**
> 
> 1. If the issue involves specific references, citekey generation, or exports, just right-click on the relevant item(s) and choose "Better BibTeX -> Submit Better BibTeX debug log" from the menu.
> 2. For other issues, follow these simple steps:
>    
>    * Restart Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled).
>    * Reproduce the problem.
>    * Select "Send Better BibTeX debug report..." from the help menu.
> 
> Once you hit that submit button, you'll get a special red debug ID. Just share that with `@retorquere` in this issue thread. If the question is regarding an export, don't forget to include what you see exported and what you expected.
> 
> By sharing your debug log, you're giving `@retorquere` a clearer picture of your setup and the items causing the issue. It's like a superhero cape for him – he can swoop in and tackle the problem much faster.
> 
> We totally get that your time is valuable, and we appreciate your effort in helping `@retorquere` help you. You might be surprised at how much this simple step speeds up the whole process.
> 
> Thanks a bunch!
> 
> **PS: If the Debug Log menu does not appear, or it does not send the debug log**
> 
> A fallback option is available under "Help" > "Send debug log to file.io".

> ![image](https://user-images.githubusercontent.com/132108/284931772-dd081606-b1c7-46a2-8940-4e6bc6a91268.png)

Sorry that I reallized that the log provides settings and contextual info. The log id is provided.
The pandoc version is 3.1.8. 

> ![image](https://user-images.githubusercontent.com/132108/284931772-dd081606-b1c7-46a2-8940-4e6bc6a91268.png)



> ![image](https://user-images.githubusercontent.com/132108/284931772-dd081606-b1c7-46a2-8940-4e6bc6a91268.png)

> ![image](https://user-images.githubusercontent.com/132108/284931772-dd081606-b1c7-46a2-8940-4e6bc6a91268.png)

Sorry that I reallized that the log provides settings and contextual info. The log id is provided.
The pandoc version is 3.1.8.

**Comment by retorquere** [comment]
Don't open duplicate issues because you chose to ignore he debug log request for two days and then expect an immediate response from me.

I'll look into the problem today.

**Comment by retorquere** [comment]
Please also upload a screenshot where the Zotero popup does not obscure the document, the error message says "this citation" but I cannot see which citation it is referring to.

**Comment by retorquere** [comment]
> Another question is some citations have the "not in zotero" in the pandoc converting process but the keys are actual keys of items.

The debug log only had `Anantrasirichai and Bull`, so I cannot test this. With the items in `V4C94885-refs-euc/6.7.137-7` there is just one item and the rest correctly fails to resolve.

**Comment by jasonandjack1997** [comment]
> Please also upload a screenshot where the Zotero popup does not obscure the document, the error message says "this citation" but I cannot see which citation it is referring to.

The screenshot is the previous image.

**Comment by jasonandjack1997** [comment]
> > Another question is some citations have the "not in zotero" in the pandoc converting process but the keys are actual keys of items.
> 
> The debug log only had `Anantrasirichai and Bull`, so I cannot test this. With the items in `V4C94885-refs-euc/6.7.137-7` there is just one item and the rest correctly fails to resolve.

I think the problem could be a version issue. When I used zotero 6.0.27 on a third computer the citations in docx refreshed correctly (most of them) and not automatially deleted (every citation is kept). 

I suppose it could be caused be the Word plugin version with zotero 7. Altought weeks ago the plugin worked fine.

**Comment by retorquere** [comment]
> > Please also upload a screenshot where the Zotero popup does not obscure the document, the error message says "this citation" but I cannot see which citation it is referring to.
> 
> The screenshot is the previous image.

I understand, but I need a new screenshot where you move the popup out of the way so that I can see what "this citation" refers to. I am assuming zotero highlights it in some way, but I cannot see it, because the popup is over the document.

**Comment by retorquere** [comment]
> I suppose it could be caused be the Word plugin version with zotero 7. Altought weeks ago the plugin worked fine.

I'll see whether I can reproduce the problem on Z7b.

**Comment by jasonandjack1997** [comment]
> > > Please also upload a screenshot where the Zotero popup does not obscure the document, the error message says "this citation" but I cannot see which citation it is referring to.
> > 
> > 
> > The screenshot is the previous image.
> 
> I understand, but I need a new screenshot where you move the popup out of the way so that I can see what "this citation" refers to. I am assuming zotero highlights it in some way, but I cannot see it, because the popup is over the document.

Here I reproduced it.
No matter yes or no clicked all will be deleted.
![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/6e8a0b5d-f307-4486-9941-1eeadcbebc86)

**Comment by jasonandjack1997** [comment]
Q7PCJS7D-refs-apse/6.7.137-7
The citekey is ArtifIntellRev2022AnantrasirichaiArtificialIntelligenceCreative. The key is identical but it could not be found and converted. 
One citation in pandoc cmd showed not found but still converted
![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/1d366a2c-ed35-49be-8336-18ce68641051)
![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/c07bc865-f727-4d50-8d4a-e035bec20aa9)
![image](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/e2a34dcd-4516-4526-8ab3-1a34a432e482)

**Comment by retorquere** [comment]
Citation keys are case-sensitive; your document has `ArtifIntellRev2022AnantrasirichaiArtificialintelligencecreative` but your library has`ArtifIntellRev2022AnantrasirichaiArtificialIntelligenceCreative`, and it is the latter that is not found.  I cannot speak for the other items as they are not in `Q7PCJS7D-refs-apse/6.7.137-7`.

**Comment by retorquere** [comment]
(BTW Zotero popups aside , it is substantially easier for me to deal with text documents and console output being attached or pasted rather than screenshotted, it's easier for me to search for exact terms).

**Comment by retorquere** [comment]
I can reproduce the corruption message on Zotero beta, but have not yet found the cause. I've asked the devs for support on the [developers forum](https://groups.google.com/g/zotero-dev/c/pcaQTdFx3t4).

**Comment by retorquere** [comment]
There's a new version of the filter on the website, combined with this test build it should solve the corruption problem.
