### ISSUE TITLE
ciations all got corrupted and automatically deleted when converting md with ciatation keys to docx using pandoc

### ISSUE THREAD

**Issue by jasonandjack1997** [retorquere/zotero-better-bibtex#2719]
### Debug log ID

V4C94885-refs-euc/6.7.137-7

### What happened?

I am converting a md file with bbt citations to a word file. In the converted word document when click zotero referesh the error bellow occurs and the citations are deleted automatically!

I opened the converted word files weeks ago which could be refershed and updated to live ciations and did the same actions, but even these files show the same errors as below: zotero code corrupted, and citations got deleted.

This example and action I did achived correct live citations results few weeks ago but tody I opened the previeusly converted docx files and did zotero refresh, even these previously correct citations were shown corrputed and gone!  I don't know what  is going on.

I tried on two PCs still the same

My coauthor is waiting for my version of the paper for days but now it is totally corrupted and I am really crazy on it.

The command:
pandoc -s --lua-filter=zotero.lua -o paperback.docx paper.md

The md file:
zotero:
csl-style: apa7 # pre-fill the style
author-in-text: true
Creativity, a fundamental feature of human intelligence, has long been a challenge for AI
[@ArtifIntellRev2022AnantrasirichaiArtificialIntelligenceCreative]
[@NatHumBehav2023WebbEmergentAnalogicalReasoning; @2023ZhangExploringMITMathematics; @InternetofThingsandCyber-PhysicalSystems2023RayChatGPTComprehensiveReview]

The docx file and error
![284927272-7b41679c-6f6c-4e24-bff8-58d0395826de](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/0737ad72-3533-4596-8a52-2dc43e8dcb60)
![284927466-0021ca14-129a-4664-9bf7-93b12d8d8aca](https://github.com/retorquere/zotero-better-bibtex/assets/5700223/dc4633d4-5309-40ec-ad65-485c35abef25)

I have nearly a hundred ciations in that paper and now don't know what to do .

This is a duplicate of #2718 but that got no response for 3 days due to lack of log id and I am really really time constrained so I have to open another one. I really hope my problem can be solved.

Best,

**Comment by retorquere** [comment]
Yeah it got no response for 3 days because you were asked for a debug log ID immediately and you chose to ignore that for two days -- and now suddenly no response from me withing one day is a problem?
