### ISSUE TITLE
Bug: German Umlaut "ä" sometimes becomes "ae", sometimes "a" in the citekey.

### ISSUE THREAD

**Issue by FiniTea** [retorquere/zotero-better-bibtex#2721]
### Debug log ID

K63JSJVX-refs-euc/6.7.140-6

### What happened?

My Citekey gets created as authetal + year.

I have "Universität  Wien" as author and "2023" in two instances (both in the debug log). In one instance the citekey is "UniversitatWien2023", in the other its "UniversitaetWien2023". This is obviously troublesome as it makes them hard to distinguish and thus use in my Latex-documents. The right one would be "UniversitaetWien2023" and "UniversitaetWien2023a", or even better "UniversitätWien2023" and "UniversitätWien2023a", but i dont know if the latter might be not compatible with latex or zotero in general.

Thanks!

**Comment by retorquere** [comment]
In the `100 Jahre Psychologie` item, the language is set to `de`, in the `Paul Felix` article the language is unset. Different folding rules apply for items that are known-German.

WRT support for unicode in citation keys:

* Zotero doesn't care whether there's an `ä` (it currently doesn't do much of anything with citation keys, and that's unlikely to change once Zotero does add them more broadly)
* biblatex can be made to work with non-ASCII characters but I don't know how (but I know there are BBT users who have Chinese characters in their citekeys)
* bibtex is unlikely to tolerate them

**Comment by FiniTea** [comment]
Thanks for the reply! Thats interesting and very good to know! Is there any benefit to check whether the language is set properly? Because i ignored that setting till now and wonder if i might be able to disable it, as it sounds like something that might lead to problems when i dont remember to change it one day.

**Comment by retorquere** [comment]
You can use either `auth.transliterate(minimal)` to consistently get `a`, or `auth.transliterate(de)` to consistently get `ae`.

**Comment by retorquere** [comment]
> Is there any benefit to check whether the language is set properly?

Absolutely -- see the 2nd paragraph of [this text](https://retorque.re/zotero-better-bibtex/support/faq/index.html#bbt-is-changing-the-capitalization-of-my-titles----why).
