### ISSUE TITLE
Change In CiteKey Format is not Reflected In Export

### ISSUE THREAD

**Issue by czhang03** [retorquere/zotero-better-bibtex#2728]
### Debug log ID

CKYXHMEP-euc/6.7.140-7

### What happened?

I have changed the citekey format to `auth.lower` in setting as an example, but when I export (both to file and quick copy) the citekey format remains the default `auth.lower + shorttitle(3,3) + year`. 

I am running flathub Zotero 7.0.0-beta.53+969031a37 (64-bit) with a fresh installation of better-bibtex.

### Example Behavior and Expected Behavior

For example, if I want to export 
```
May, J. P. (1999). A concise course in algebraic topology. University of Chicago Press.
```
I still get
```
@book{mayConciseCourseAlgebraic1999,
  title = {A Concise Course in Algebraic Topology},
  author = {May, J. Peter},
  year = {1999},
  series = {Chicago Lectures in Mathematics},
  publisher = {{University of Chicago Press}},
  address = {{Chicago}},
  isbn = {978-0-226-51182-5 978-0-226-51183-2},
  lccn = {QA612 .M387 1999},
  keywords = {Algebraic topology}
}
```
I am expecting the export to be
```
@book{may,
  title = {A Concise Course in Algebraic Topology},
  author = {May, J. Peter},
  year = {1999},
  series = {Chicago Lectures in Mathematics},
  publisher = {{University of Chicago Press}},
  address = {{Chicago}},
  isbn = {978-0-226-51182-5 978-0-226-51183-2},
  lccn = {QA612 .M387 1999},
  keywords = {Algebraic topology}
}
```

---

**An aside:** This is just an example (it would be pretty unreadable to have just the author as citation key). I actually want the citation key to be `auth.lower + '_' + shorttitle(3,3) + '_' + year`.

**Comment by retorquere** [comment]
Did you edit the item after changing the formula, or right-clicked it and refreshed the citation key? Just updating the formula does not change existing citekeys. Only a change to the item, or a forced refresh, applies the new formula.

**Comment by czhang03** [comment]
Oh! That is a bit unintuitive, but it works now. Thanks!

**Comment by retorquere** [comment]
> Oh! That is a bit unintuitive, but it works now. Thanks!

If it did change whenever the formula changes the citation keys would continuously change while you are typing the formula; if you want to enter 

```
auth.lower + '_' + shorttitle(3,3) + '_' + year
```

`auth` would first be valid, and all keys would change, then `auth.lower` would become valid, and all keys would change, then `auth.lower + '_'` would become valid, etc.

**Comment by czhang03** [comment]
Maybe a better UX is to add a highlighted "refresh all citation key" button underneath the citation key formula when the system detects that the citation key formula is changed?

**Comment by retorquere** [comment]
What would turn the button back off again? If you manually refresh items, or edit them, the formula would already have been applied. I'd have to keep track of what items (or keys) hadn't changed since last edit to the formula. ISTM it would get convoluted fast, and then the button status would be one more unintuitive aspect of the BBT UI.
