### ISSUE TITLE
Zotero 7 epub annotations

### ISSUE THREAD

**Issue by Liimurr** [retorquere/zotero-better-bibtex#2734]
### Debug log ID

H4YGJRS4-refs-euc/6.7.140-7

### What happened?

I use Readwise right now for all epub files since it has annotation integration with obsidian and epub support.
Zotero+Better Bibtex results in superior citations and better data ownership; I obviously would rather use Zotero for as much as possible.
With Zotero 7 introducing epub annotation support, it seems that may be possible once Better Bibtex supports it.
However, when checking the data coming in to obsidian, it seems epub files don't have any annotations like the pdfs do.
I also checked google `"Better BibTex" "epub"` as well the issues here on github but found nothing.
Is there a plan to support this soon? Would love to see this!

**Comment by retorquere** [comment]
Hi, I'm not clear on what you want BBT to do that it currently doesn't. BBT does nothing with epub files currently, so it also doesn't affect how epubs appear anywhere else. Can you elaborate?

**Comment by Liimurr** [comment]
Hey, Thanks for the fast reply!  
I'll do my best to elaborate.  

I may have made unintentional mistakes here so apologies if I misunderstand where BetterBibTex begins and the Obsidian plugin ends or other gaps in my knowledge here.  

To my knowledge the Obsidian plugin simply extracts information from Zotero, relying on the Better BibTex plugin to do the heavy lifting.  

I'm assuming the fields here are pulled directly from BetterBibtex:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/14037388/e67a3dd6-6af2-4a8c-8bc9-2555d1bbf0d7)

If the annotation field gets populated with data for the epub format obsidian can handle the rest and pull in the data!  

If I left anything out that may help elaborate let me know and I'll try to respond ASAP!

**Comment by Liimurr** [comment]
Looking into it more this may be an issue with the Obsidian-Zotero-Integration plugin?
I thought BetterBibTex was used to extract the information in the screenshot, though I'm not sure on exactly how they use it. 
:/

**Comment by retorquere** [comment]
Yep, you've got it right. BBT has some features that allow other plugins to reach into Zotero, but I don't know what the obsidian plugin needs.

**Comment by Liimurr** [comment]
Thanks for the confirmation!

I have since gone to the obsidian-zotero-integration github page and asked for clarification on what they need.
https://github.com/mgmeyers/obsidian-zotero-integration/issues/285 

It doesn't seem they are likely to respond any time soon, as the ticket I posted on is months old. But if/when they do, I can update this ticket or open a new one if they are missing something.

**Comment by retorquere** [comment]
You can comment here and the issue will automatically reopen.

**Comment by retorquere** [comment]
(the "not planned" sounds harsh but my choices are "not planned" and "completed")
