### ISSUE TITLE
Difficulty converting a BBT-managed RMarkdown document to docx and maintaining live Zotero citations 

### ISSUE THREAD

**Issue by TaymAlsalti** [retorquere/zotero-better-bibtex#2736]
### Debug log ID

Q5TCJ3AI-refs-euc/6.7.140-6

### What happened?

Hi,

I'm encountering problems trying to convert my .rmd file to a docx. with live Zotero citations:
When I run this in the Terminal within Rstudio and RProject (working dir)
`pandoc -s --lua-filter=zotero.lua --metadata=zotero_scannable_cite:true --metadata=zotero_client:jurism -o Thesis.docx -f markdown -t docx Thesis.rmd`
I get the error below, which seems to contain all my citation keys. I had my Zotero (v. 6.0.30) open. Other potentially relevant information: 

- pandoc v. 3.1.11
- zotero.lua (latest version) is in the working dir
- references.bib is in the working dir, although I get the same error with or without that line in the YAML header
- RStudio 2023.09.1 Build 494
- I originally knit the document to a PDF using the papaja package and managed all references using Zotero and Better Bibtex
- Abridged YAML header in Thesis.rmd:

```
---

bibliography        : ["references.bib"]
zotero:
  library: "tDCS-Motor Learning" # zotero group name
  client: zotero 
  author-in-text: false 
  csl-style: apa 
---
```

Would appreciate any hints!

Many thanks,
Taym

P.S. I submitted a debug log using all references in my group library because I don't know which specific references, if any, are causing the problem.

> zotero-live-citations caf41cc
Error running filter zotero.lua:
Could not fetch http://127.0.0.1:24119/better-bibtex/export/item?pandocFilterData=true&translator=json&citationKeys=dubljevicRisingTideTDCS2014%2CbanksPublicationBiasCall2012%2CevansHierarchyEvidenceFramework2003%2CstanleyMetaRegressionMethods2008%2CkepesMetaanalyticReviewsOrganizational2013%2CpagePRISMA2020Statement2021%2CmaassenReproducibilityIndividualEffect2020%2CR%2Dforcats%2CkangTranscranialDirectCurrent2016a%2CwurzmanOpenLetterConcerning2016%2CjonesHighPrevalenceLow2005%2CR%2Dmeta%2CzettlerTDCSResearchWorld2017%2CschalkenReportingQualitySystematic2017%2CbeggOperatingCharacteristicsRank1994%2CstanleyMetaregressionApproximationsReduce2014%2CshamseerPreferredReportingItems2015%2CrosenthalFileDrawerProblem1979%2CwexlerWhoUsesDirecttoConsumer2018%2CveveaPublicationBias2019%2CsimonsohnBetterPcurvesMaking2015%2CsimmonsFalsePositivePsychologyUndisclosed2011%2CaytugRevealedConcealedTransparency2012%2CcooperHandbookResearchSynthesis2009%2CxieDynamicDocumentsKnitr2015%2CgelmanGardenForkingPaths2013%2CgeyskensReviewEvaluationMetaAnalysis2009%2CkangTranscranialDirectCurrent2018%2CwanEstimatingSampleMean2014%2CpussegodaSystematicReviewAdherence2017%2CmoreauConductingMetaanalysisAge2020%2CviechtbauerOutlierInfluenceDiagnostics2010%2CReportingGuidelinesEQUATOR%2CluedtkeTranscranialDirectCurrent2012%2CborensteinCriticismsMetaanalysis2009%2Csimonsohn59PETPEESENot2017%2CR%2Dbase%2CR%2Dmetafor%2CadaImpactMetaanalyticDecisions2012a%2CnitscheTranscranialDirectCurrent2008%2CrstudioteamRStudioIntegratedDevelopment2021%2CsimonsohnPCurveEffectSize2014%2CmorenoAssessmentRegressionbasedMethods2009a%2CwoodsTechnicalGuideTDCS2016%2CtaylorTriangulatingMetaanalysesExample2016%2CR%2DMatrix%2CbuttonPowerFailureWhy2013%2CnosekPreregistrationRevolution2018%2CmoherImprovingQualityReports2000%2CliuEffectsTranscranialElectrical2021%2CcarterCorrectingBiasPsychology2019%2CR%2DMAd%2CtobiasAssessingInfluenceSingle1999a%2CfregniRegulatoryConsiderationsClinical2015%2CaustinPrefrontalElectricalStimulation2016%2CdavisRegulationConsumerTDCS2016%2CliberatiPRISMAStatementReporting2009%2CkonstantopoulosStatisticallyAnalyzingEffect2019%2CmcshaneAdjustingPublicationBias2016%2CR%2Dreadxl%2CR%2Dtidyr%2CgazzanigaMethodsCognitiveNeuroscience2018%2CveveaGeneralLinearModel1995%2CminarikImportanceSampleSize2016%2CmoherPreferredReportingItems2009%2CR%2Dreadr%2CdieckmannEmpiricalAssessmentMetaAnalytic2009%2CplesserReproducibilityVsReplicability2018%2CmadeyskiEffectSizesTheir2018%2CusheyRenvProjectEnvironments2021a%2CxieKnitrGeneralpurposePackage2021%2CR%2Dggplot2%2ChardwickeShouldPsychologyJournals2019%2ClakensExaminingReproducibilityMetaAnalyses2017%2CmorgantiImpactMetaanalysesClinical2007%2CriggsAtHomeTranscranialDirect2018%2CrohatgiWebPlotDigitizer2021%2CvanassenMetaanalysisUsingEffect2015%2CbuchEffectsTDCSMotor2017%2CgopalakrishnanSystematicReviewsMetaanalysis2013%2CeggerBiasMetaanalysisDetected1997%2CbakkerRulesGameCalled2012%2CrosenAnodalTDCSRight2016%2CR%2DkableExtra%2ClipkaResolvingHeterogeneityTranscranial2021%2CR%2Dstringr%2CnieminenMetaanalyticDecisionsReliability2011%2CwayantEvaluationReproducibleResearch2019%2ChigginsonCurrentIncentivesScientists2016%2CbrunoniTranscranialDirectCurrent2016%2CquintanaPreregistrationPublicationNontechnical2015%2CvoracekWhichDataMetaanalyze2019%2CbuscemiSingleDataExtraction2006%2ChyattQuandaryCovaryingBrief2020a%2ChungEfficacyTranscranialDirect2021%2ChozoEstimatingMeanVariance2005%2ChilgardOverstatedEvidenceShortterm2017%2CveveaPublicationBiasResearch2005%2CxieKnitrComprehensiveTool2014%2CpageEvaluationsUptakeImpact2017%2CR%2Dtibble%2CvanaertConductingMetaAnalysesBased2016%2ChorvathQuantitativeReviewFinds2015%2CpolaninTransparencyReproducibilityMetaAnalyses2020%2CpagePRISMA2020Explanation2021%2CgleserStochasticallyDependentEffect2009%2CmorrisCombiningEffectSize2002%2CsterlingPublicationDecisionsTheir1959%2CopensciencecollaborationEstimatingReproducibilityPsychological2015a%2CreisNoninvasiveCorticalStimulation2009%2CmoherPreferredReportingItems2015%2CR%2Dpapaja%2CguzzoMetaanalysisAnalysis1987%2CveronikiMethodsEstimateBetweenstudy2016%2CgebodhTranscranialDirectCurrent2019%2CduvalNonparametricTrimFill2000%2CfordErrorsConductSystematic2010%2CioannidisMassProductionRedundant2016%2CR%2Ddmetar%2ChungEfficacyTranscranialDirect2021a%2CR%2Ddplyr%2CgotzscheDataExtractionErrors2007%2CsteenbergenUnfocusFocUs2016%2CahnReviewMetaAnalysesEducation2012%2CgianniTDCSRandomizedControlled2021%2CstaggPhysiologicalBasisTranscranial2011%2CvalentineHowManyStudies2010%2CaguinisMetaAnalyticChoicesJudgment2011%2Cbotvinik%2DnezerVariabilityAnalysisSingle2020%2ChigginsCochraneHandbookSystematic2019%2CnosekPromotingOpenResearch2015%2CpageReproducibleResearchPractices2018%2ChohnEmpiricalReviewResearch2020%2CrothsteinPublicationBiasMetaanalysis2005%2CharrerDoingMetaAnalysisHandsOn2021%2CbromanRecommendationsFundingAgencies2017%2CsimonsohnPcurveKeyFiledrawer2014%2CborensteinEffectSizesMetaanalyses2019%2CborensteinPublicationBias2009%2CR%2Dpurrr%2CsteinerCausalReplicationFramework2019%2CgoodmanWhatDoesResearch2016%2CinzlichtBiasCorrectionTechniquesAlone2015%2CbennabiTranscranialDirectCurrent2014%2CaguinisDebunkingMythsUrban2011%2CheireneCallReplicationsAddiction2021
HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 24119
  secure               = False
  requestHeaders       = []
  path                 = "/better-bibtex/export/item"
  queryString          = "?pandocFilterData=true&translator=json&citationKeys=dubljevicRisingTideTDCS2014%2CbanksPublicationBiasCall2012%2CevansHierarchyEvidenceFramework2003%2CstanleyMetaRegressionMethods2008%2CkepesMetaanalyticReviewsOrganizational2013%2CpagePRISMA2020Statement2021%2CmaassenReproducibilityIndividualEffect2020%2CR%2Dforcats%2CkangTranscranialDirectCurrent2016a%2CwurzmanOpenLetterConcerning2016%2CjonesHighPrevalenceLow2005%2CR%2Dmeta%2CzettlerTDCSResearchWorld2017%2CschalkenReportingQualitySystematic2017%2CbeggOperatingCharacteristicsRank1994%2CstanleyMetaregressionApproximationsReduce2014%2CshamseerPreferredReportingItems2015%2CrosenthalFileDrawerProblem1979%2CwexlerWhoUsesDirecttoConsumer2018%2CveveaPublicationBias2019%2CsimonsohnBetterPcurvesMaking2015%2CsimmonsFalsePositivePsychologyUndisclosed2011%2CaytugRevealedConcealedTransparency2012%2CcooperHandbookResearchSynthesis2009%2CxieDynamicDocumentsKnitr2015%2CgelmanGardenForkingPaths2013%2CgeyskensReviewEvaluationMetaAnalysis2009%2CkangTranscranialDirectCurrent2018%2CwanEstimatingSampleMean2014%2CpussegodaSystematicReviewAdherence2017%2CmoreauConductingMetaanalysisAge2020%2CviechtbauerOutlierInfluenceDiagnostics2010%2CReportingGuidelinesEQUATOR%2CluedtkeTranscranialDirectCurrent2012%2CborensteinCriticismsMetaanalysis2009%2Csimonsohn59PETPEESENot2017%2CR%2Dbase%2CR%2Dmetafor%2CadaImpactMetaanalyticDecisions2012a%2CnitscheTranscranialDirectCurrent2008%2CrstudioteamRStudioIntegratedDevelopment2021%2CsimonsohnPCurveEffectSize2014%2CmorenoAssessmentRegressionbasedMethods2009a%2CwoodsTechnicalGuideTDCS2016%2CtaylorTriangulatingMetaanalysesExample2016%2CR%2DMatrix%2CbuttonPowerFailureWhy2013%2CnosekPreregistrationRevolution2018%2CmoherImprovingQualityReports2000%2CliuEffectsTranscranialElectrical2021%2CcarterCorrectingBiasPsychology2019%2CR%2DMAd%2CtobiasAssessingInfluenceSingle1999a%2CfregniRegulatoryConsiderationsClinical2015%2CaustinPrefrontalElectricalStimulation2016%2CdavisRegulationConsumerTDCS2016%2CliberatiPRISMAStatementReporting2009%2CkonstantopoulosStatisticallyAnalyzingEffect2019%2CmcshaneAdjustingPublicationBias2016%2CR%2Dreadxl%2CR%2Dtidyr%2CgazzanigaMethodsCognitiveNeuroscience2018%2CveveaGeneralLinearModel1995%2CminarikImportanceSampleSize2016%2CmoherPreferredReportingItems2009%2CR%2Dreadr%2CdieckmannEmpiricalAssessmentMetaAnalytic2009%2CplesserReproducibilityVsReplicability2018%2CmadeyskiEffectSizesTheir2018%2CusheyRenvProjectEnvironments2021a%2CxieKnitrGeneralpurposePackage2021%2CR%2Dggplot2%2ChardwickeShouldPsychologyJournals2019%2ClakensExaminingReproducibilityMetaAnalyses2017%2CmorgantiImpactMetaanalysesClinical2007%2CriggsAtHomeTranscranialDirect2018%2CrohatgiWebPlotDigitizer2021%2CvanassenMetaanalysisUsingEffect2015%2CbuchEffectsTDCSMotor2017%2CgopalakrishnanSystematicReviewsMetaanalysis2013%2CeggerBiasMetaanalysisDetected1997%2CbakkerRulesGameCalled2012%2CrosenAnodalTDCSRight2016%2CR%2DkableExtra%2ClipkaResolvingHeterogeneityTranscranial2021%2CR%2Dstringr%2CnieminenMetaanalyticDecisionsReliability2011%2CwayantEvaluationReproducibleResearch2019%2ChigginsonCurrentIncentivesScientists2016%2CbrunoniTranscranialDirectCurrent2016%2CquintanaPreregistrationPublicationNontechnical2015%2CvoracekWhichDataMetaanalyze2019%2CbuscemiSingleDataExtraction2006%2ChyattQuandaryCovaryingBrief2020a%2ChungEfficacyTranscranialDirect2021%2ChozoEstimatingMeanVariance2005%2ChilgardOverstatedEvidenceShortterm2017%2CveveaPublicationBiasResearch2005%2CxieKnitrComprehensiveTool2014%2CpageEvaluationsUptakeImpact2017%2CR%2Dtibble%2CvanaertConductingMetaAnalysesBased2016%2ChorvathQuantitativeReviewFinds2015%2CpolaninTransparencyReproducibilityMetaAnalyses2020%2CpagePRISMA2020Explanation2021%2CgleserStochasticallyDependentEffect2009%2CmorrisCombiningEffectSize2002%2CsterlingPublicationDecisionsTheir1959%2CopensciencecollaborationEstimatingReproducibilityPsychological2015a%2CreisNoninvasiveCorticalStimulation2009%2CmoherPreferredReportingItems2015%2CR%2Dpapaja%2CguzzoMetaanalysisAnalysis1987%2CveronikiMethodsEstimateBetweenstudy2016%2CgebodhTranscranialDirectCurrent2019%2CduvalNonparametricTrimFill2000%2CfordErrorsConductSystematic2010%2CioannidisMassProductionRedundant2016%2CR%2Ddmetar%2ChungEfficacyTranscranialDirect2021a%2CR%2Ddplyr%2CgotzscheDataExtractionErrors2007%2CsteenbergenUnfocusFocUs2016%2CahnReviewMetaAnalysesEducation2012%2CgianniTDCSRandomizedControlled2021%2CstaggPhysiologicalBasisTranscranial2011%2CvalentineHowManyStudies2010%2CaguinisMetaAnalyticChoicesJudgment2011%2Cbotvinik%2DnezerVariabilityAnalysisSingle2020%2ChigginsCochraneHandbookSystematic2019%2CnosekPromotingOpenResearch2015%2CpageReproducibleResearchPractices2018%2ChohnEmpiricalReviewResearch2020%2CrothsteinPublicationBiasMetaanalysis2005%2CharrerDoingMetaAnalysisHandsOn2021%2CbromanRecommendationsFundingAgencies2017%2CsimonsohnPcurveKeyFiledrawer2014%2CborensteinEffectSizesMetaanalyses2019%2CborensteinPublicationBias2009%2CR%2Dpurrr%2CsteinerCausalReplicationFramework2019%2CgoodmanWhatDoesResearch2016%2CinzlichtBiasCorrectionTechniquesAlone2015%2CbennabiTranscranialDirectCurrent2014%2CaguinisDebunkingMythsUrban2011%2CheireneCallReplicationsAddiction2021"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 (ConnectionFailure Network.Socket.connect: <socket: 768>: failed (Connection refused (WSAECONNREFUSED)))
stack traceback:
        zotero.lua:1680: in upvalue 'load_items'
        zotero.lua:1690: in function 'zotero.get'
        zotero.lua:1847: in function <zotero.lua:1830>
        (...tail calls...)

**Comment by retorquere** [comment]
You're running Zotero, I thought you were running Juris-M. Can you try with [this version](https://gist.github.com/retorquere/9523c889683fbbeaa36c41f2a3737929) and report back what it prints before the error?

**Comment by TaymAlsalti** [comment]
Yes, I'm running zotero. Here is the new output before the error:

> zotero-live-citations a522fcd
new version "caf41cc" available at https://retorque.re/zotero-better-bibtex/exporting
better bibtex: command line override "scannable_cite"
better bibtex: command line override "client"

**Comment by retorquere** [comment]
RStudio is calling pandoc with `--metadata=zotero_scannable_cite:true --metadata=zotero_client:jurism`. If you remove those it should work.

**Comment by TaymAlsalti** [comment]
Yes, that worked! However using both the old and new lua filters only three references are being recognised and properly encoded when I referesh Zotero in the newly output document (although only a subset of the in text citations are being converted to live citations for these three references, too). The rest are "not found" even though they are in the group library and saved under the correct citation keys. E.g., the first one

> zotero-live-citations a522fcd
new version "caf41cc" available at https://retorque.re/zotero-better-bibtex/exporting
@ahnReviewMetaAnalysesEducation2012: not found

![image](https://github.com/retorquere/zotero-better-bibtex/assets/57235416/110d9e0e-ce2b-49db-80cf-f51608e55a1a)

I can't tell what's special about the three references which _were_ found but here are their citation keys, if that helps:
buchEffectsTDCSMotor2017
kangTranscranialDirectCurrent2018
luedtkeTranscranialDirectCurrent2012

**Comment by retorquere** [comment]
You can use the standard filter again, the one I posted here just reported the command line parameters.

Can you run that conversion again, and after the conversion, send a debug log?

**Comment by TaymAlsalti** [comment]
Okay I don't know whether I changed something and what exactly it was, but upon rerunning the conversion with the standard filter all references could be found and all citations but a few were correctly converted. The remaining ones are non standard in-text citations where the author's name should be rendered outside the parentheses, e.g., 

> as done by @reisNoninvasiveCorticalStimulation2009

or where other stuff is written in the brackets so that this extra stuff can appear in the rendered parentheses, e.g., 

> [at least among the ~50% of meta-analyses which conduct such analyses pageEvaluationsUptakeImpact2017; @veveaPublicationBias2019; @borensteinPublicationBias2009; @harrerDoingMetaAnalysisHandsOn2021].

Should I send a debug log for this?

**Comment by retorquere** [comment]
> The remaining ones are non standard in-text citations where the author's name should be rendered outside the parentheses, e.g.,

You can still convert those by using [`author-in-text: true`](https://retorque.re/zotero-better-bibtex/exporting/pandoc/index.html#from-markdown-to-zotero-live-citations), but Zotero doesn't support this, so the result will just be plain content for Zotero. If you update the reference in Zotero, the author part thus converted won't change.

> or where other stuff is written in the brackets so that this extra stuff can appear in the rendered parentheses, e.g.,

These should just work, so yes, if you have a minimal markdown document + items (in the debug log) that reproduce this, I can take a look.

> Edit: these are few enough that I'd be fine with modifying them manually in the output document and closing this issue if you prefer. :)

Nope, I'd prefer it if these would just work; if you've found a bug, I'd like to fix it.

**Comment by TaymAlsalti** [comment]
> You can still convert those by using [author-in-text: true](https://retorque.re/zotero-better-bibtex/exporting/pandoc/index.html#from-markdown-to-zotero-live-citations), but Zotero doesn't really support this, so the result will just be plain content for Zotero. If you update the reference in Zotero, the author part thus converted won't change.

With `author-in-text: true` I actually now get the correct live citation but without the author's name but perhaps that's what you meant? So "by @reisNoninvasiveCorticalStimulation2009" was rendered as "by (2009) + the live citation. 

> These should just work, so yes, if you have a minimal markdown document + items (in the debug log) that reproduce this, I can take a look.

Ok I noticed the "@" was missing from the first citation key in the brackets so now this 

`[at least among the ~50% of meta-analyses which conduct such analyses @pageEvaluationsUptakeImpact2017; @veveaPublicationBias2019; @borensteinPublicationBias2009; @harrerDoingMetaAnalysisHandsOn2021].`

is rendered as

> (Borenstein et al., 2009b; Harrer et al., 2021; at least among the ~50% of meta-analyses which conduct such analyses Page & Moher, 2017; Vevea et al., 2019)

So I guess the "at least..." part is being grouped with the Page & Moher citation when sorting alphabetically? I tried adding a comma before the first citation but that didn't change this.

Here's the entire content of a reproducible RMD and here's the debug ID: BFXJMKI4-refs-euc/6.7.140-6

> ```
>---
> bibliography        : ["references.bib"]
> zotero:
>   library: "tDCS-Motor Learning" # zotero group name
>   client: zotero 
>   author-in-text: false 
>   csl-style: apa 
>   author-in-text: true
> ---
> ```
> 
> Small-study effect methods have been available for more than two decades and are very widely used [at least among the ~50% of meta-analyses which conduct such analyses @pageEvaluationsUptakeImpact2017; @veveaPublicationBias2019; @borensteinPublicationBias2009; @harrerDoingMetaAnalysisHandsOn2021].

**Comment by retorquere** [comment]
You can't have `author-in-text` be both true and false. The behavior is undefined when you do that.

**Comment by retorquere** [comment]
Interesting -- we may have stumbled upon a Zotero bug? If you edit the generated citation in Word, the 

> at least among the ~50% of meta-analyses which conduct such analyses

**is** part of the prefix of the first item. I'll check with the Zotero devs.

Do you have a sample where author in text fails?

**Comment by retorquere** [comment]
Ha, I have found it -- Zotero sorts citations by default but can be told to not do so. Fix incoming.

**Comment by retorquere** [comment]
Can you send a new debug log from 5515? This version together with https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2736/site/content/exporting/zotero.lua will solve the prefix problem. I'd still like to fix the author-in-text problem if you have an MWE for that.

**Comment by TaymAlsalti** [comment]
> Can you send a new debug log from 5515? This version together with https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2736/site/content/exporting/zotero.lua will solve the prefix problem.

Done but I idiotically copied something over the debug ID and lost it. The problem was not fixed, I had the same output as before using the MRE above. 

MRE for the author-in-text issue (same pandoc code as above and with two of the references included in the last two debug requests I sent):

> ```
> ---
> zotero:
>   library: "tDCS-Motor Learning" # zotero group name
>   client: zotero 
>   author-in-text: false 
>   csl-style: apa 
>   author-in-text: true
> ---
> ```
> This was done by @pageEvaluationsUptakeImpact2017 and @veveaPublicationBias2019.

Was rendered as "This was done by (2017) and (2019).".

**Comment by retorquere** [comment]
> Done but I idiotically copied something over the debug ID and lost it. The problem was not fixed, I had the same output as before using the MRE above.

Can you send a new one, and attach the docx file that didn't come out right?

**Comment by retorquere** [comment]
There's a new version on https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2736/site/content/exporting/zotero.lua (should say "zotero-live-citations 48ec0f9" at the top) that will fix the author-in-text version.

**Comment by TaymAlsalti** [comment]
> There's a new version on https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2736/site/content/exporting/zotero.lua (should say "zotero-live-citations https://github.com/retorquere/zotero-better-bibtex/commit/48ec0f984a2ec290eed5ef88a6260d0affe7442e" at the top) that will fix the author-in-text version.

Sorry I have to do this to you on new year's eve but using this new filter, the same pandoc code, and this MRE:

```
---
zotero:
  library: "tDCS-Motor Learning" # zotero group name
  client: zotero 
  author-in-text: false 
  csl-style: apa 
  author-in-text: true
---


This was done by @pageEvaluationsUptakeImpact2017 and @veveaPublicationBias2019 and @fregniRegulatoryConsiderationsClinical2015a.
```

I get 

> This was done by Page and Moher (2017) and Vevea, Coburn and Sutton (2019) and Fregni, Nitsche, Loo, Brunoni, Marangolo, Leite, Carvalho, Bolognini, Caumo, Paik, Simis, Ueda, Ekhitari, Luu, Tucker, Tyler, Brunelin, Datta, Juan, Venkatasubramanian, Boggio and Bikson (2015).

Both the second and third citations should be "et al."ed according to the APA of course. Here's a debug ID: BGYEB56A-refs-euc/6.7.140.2736.5515-6



Re: the prefix issue here's the debug ID ARIDAE96-refs-euc/6.7.140.2736.5515-6 and here's the output [MRE.docx](https://github.com/retorquere/zotero-better-bibtex/files/13801589/MRE.docx) file.

**Comment by retorquere** [comment]
That still has conflicting author-in-text directives. Can you remove the false directive? And can you double check the version of the zotero.lua filter you're using?

**Comment by retorquere** [comment]
Oh wait it does work it's just not APA compliant... oof that will be harder, I'll see what I can do about that.

**Comment by TaymAlsalti** [comment]
> That still has conflicting author-in-text directives. Can you remove the false directive? And can you double check the version of the zotero.lua filter you're using?

Aaah sorry I misunderstood you the first time you told me about the conflicting directives and hadn't noticed it the whole time. Removing the first (`: false`) one didn't do anything because I presume the second one overrode it anyway. So yes, the new filter (`zotero-live-citations 48ec0f9`) works, it just doesn't do output APA compliant in-text citations. :)

**Comment by retorquere** [comment]
Build 5519 + zotero-live-citations e9fb621 from https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/gh-2736/site/content/exporting/zotero.lua will get style-compliant author-in-text. It's a bit of a kludge so I don't know if it will always work -- the citation processor that Zotero uses doesn't really support author-only cites, so I have it generate a citation and attempt to extract the author from it.

**Comment by retorquere** [comment]
Can you verify that this does what you need?

**Comment by TaymAlsalti** [comment]
I just checked and it does! Sorry for the delay!

It now renders:

> This was done by Page & Moher (2017) and Vevea et al. (2019) and Fregni et al. (2015).

**Comment by retorquere** [comment]
Awesome. I'm pretty proud of this kludge 😁. One more thing that BBT does that's not supposed to be possible in Zotero 😄.

I'll put out a new release for this today.
