### ISSUE TITLE
Flathub Zotero 7 Beta crash when a PDF is open on startup

### ISSUE THREAD

**Issue by czhang03** [retorquere/zotero-better-bibtex#2739]
### Debug log ID

A9JE7PIY-euc/6.7.140-7

#### Step To Reproduce

- Install Zotero 7 beta from flathub (although I am not sure installing from flathub is necessary)
- open a PDF and close zotero
  - reopen zotero without any further input, the app would crash without showing the content of the pdf
  - reopen zotero while rapidly moving mouse, the app would load the content of the pdf, and then freeze and crash
  - reopen zotero, and rapidly switching to "My Library" tab before the "Better BibTex: Assigning Citation Key" dialog box show up will prevent the crash.

This issue is not reproducible in Zotero safe mode and not reproducible in Zotero stable (6.0.30).

#### Terminal Log
Both rapidly moving the mouse and not moving the mouse produces the same crash log in the terminal:
```
> flatpak run org.zotero.Zotero 
mozilla::detail::MutexImpl::mutexLock: pthread_mutex_lock failed: Invalid argument
/app/bin/zotero: line 18:     5 Segmentation fault      (core dumped) "$CALLDIR/zotero-bin" -app "$CALLDIR/app/application.ini" "$@"
```
As I cannot send the debug log when zotero crashes, I attached a debug log for the rare occasion that Zotero did not crash, even when started with pdf open. I cannot reproduce this behavior (not crash) even since.

**Comment by retorquere** [comment]
I cannot reproduce this on the official tarball (or my packaged debs, which are the same). I can open Zotero, open a pdf, close Zotero, and I am not getting a segfault on close.

Plugins aren't even supposed to be able to cause segfaults, so we will probably have to involve the Zotero devs, but they'll want a reproduction with the tarball. To my knowledge they don't support flatpacks/snaps.

**Comment by czhang03** [comment]
I will try to reproduce this issue on tarball, hopefully with a minimal library. 

I am on fedora 39 BTW, dont know if that helps...

**Comment by retorquere** [comment]
Doesn't really, I don't have access to a Fedora system.

The tarball can safely be used with your existing library, you just can't have the flatpak and the tarball running at the same time (Zotero will not allow it).

**Comment by retorquere** [comment]
Any progress?

**Comment by czhang03** [comment]
I have reinstalled Zotero (flathub beta) and resynced my files. I was no longer able to reproduce this issue. Probably is just my old PDF is glitched on the computer or something. I will close this issue as we have no more thread to proceed.
