### ISSUE TITLE
BUG:  There is a conflict between Better BitTex and mdnotes

### ISSUE THREAD

**Issue by UnableToUseGit** [retorquere/zotero-better-bibtex#2742]
### Debug log ID

V4EBZD5J-refs-euc/6.7.143-6

### What happened?

![Snipaste_2024-01-08_10-34-49](https://github.com/retorquere/zotero-better-bibtex/assets/104746935/d85fb57c-5a2f-4416-88cf-4fe47039fbf1)

Mdnotes will create failed if use the citekey made by "Better BitTex" as title.
When I reduce the version of "Better BitTex", the bug fixed.

os: window10
Mdnotes: 0.2.3
Better BitTex: 6.7.143

**Comment by retorquere** [comment]
There are no relevant errors in `V4EBZD5J-refs-euc/6.7.143-6`, just quota errors. The mdnotes author will have to say where it's failing, when that is known I can see what I can do to accommodate mdnotes. A cursory inspection shows nothing strange about how mdnotes calls BBT.

**Comment by retorquere** [comment]
Seems to be https://github.com/argenos/zotero-mdnotes/pull/225 .

**Comment by retorquere** [comment]
This problem has apparently been known to the MdNotes project since late October. I have suggested a fix bet there's nothing I can do on my end.

**Comment by UnableToUseGit** [comment]
Thanks for your answer!

> This problem has apparently been known to the MdNotes project since late October. I have suggested a fix bet there's nothing I can do on my end.
