### ISSUE TITLE
Imported name suffix in `family` part

### ISSUE THREAD

**Issue by zepinglee** [retorquere/zotero-better-bibtex#2744]
### Debug log ID

6MKZLSYL-refs-apse/6.7.143-6

### What happened?

When imported from `.bib`, the name suffix "Jr." is placed in the `family` name part and it's not correctly recognized as `suffix` in the exported CSL-JSON. According to <https://forums.zotero.org/discussion/23745>, the "Jr." is expected in the `given` part. The exported CSL-JSON works correctly in the latter format. See also <https://forums.zotero.org/discussion/37289> and <https://forums.zotero.org/discussion/3271>.

BibTeX data:
```bib
@BOOK{apa-test.9.46:8,
  AUTHOR = {Costa, Jr., P. T. and McCrae, R. R.},
  DATE   = {2013}
}
```

Exported CSL-JSON:
```json
			{
				"family": "Costa, Jr.",
				"given": "P. T."
			}
```

Exported CSL-JSON with "Jr." in `given` name part:
```json
			{
				"family": "Costa",
				"given": "P. T.",
				"suffix": "Jr."
			}
```

**Comment by retorquere** [comment]
Is `Jr.` a special case then? Because `Costa, J.` would mean `{ given: 'J.', family: 'Costa' }`.

**Comment by retorquere** [comment]
@njbart? Do you know if there are more of these special cases?

**Comment by retorquere** [comment]
Does that mean `{MacCallum, III, T.}` should parse into `{ given: 'T.', family: 'MacCallum, III' }`?

**Comment by zepinglee** [comment]
> Does that mean `{MacCallum, III, T.}` should parse into `{ given: 'T.', family: 'MacCallum, III' }`?

No. My understanding is that “III” is also a name suffix as "Jr". In the `apa.csl` output, `{ given: 'T.', family: 'MacCallum, III' }` becomes `MacCallum, III, T.` and `{ given: 'T., III', family: 'MacCallum' }` with "III" in the `given` part gives `MacCallum, T., III.` as expected in the APA manual.

<img width="332" alt="Screenshot 2024-01-13 at 13 27 47" src="https://github.com/retorquere/zotero-better-bibtex/assets/12290822/14e2069f-8dce-4474-9df8-ec8af23fc651">

CSL-JSON:
```json
[
	{
		"id": "apa.9.44:6b",
		"type": "document",
		"language": "en-US",
		"note": "tex.entrytype: nameonly",
		"author": [
			{
				"family": "MacCallum",
				"given": "T.",
				"suffix": "III"
			}
		]
	}
]
```

<img width="145" alt="Screenshot 2024-01-13 at 13 26 40" src="https://github.com/retorquere/zotero-better-bibtex/assets/12290822/490d35b9-803c-4c8b-bab7-9ae678965cb4">

**Comment by zepinglee** [comment]
> Is `Jr.` a special case then? Because `Costa, J.` would mean `{ given: 'J.', family: 'Costa' }`.

The `btxdoc.pdf` says:

> To summarize, BibTeX allows three possible forms for the name:
>         "First von Last"
>         "von Last, First"
>         "von Last, Jr, First"

The `Jr` part is not likely to be confused with `First` part because it's delimited by the second comma.

If there are more commas, BibTeX will raise an error.
```
Too many commas in name 1 of "Costa, Jr., P. T., Doe" for entry apa-test.9.46:8
```

**Comment by retorquere** [comment]
All right, that's what my parser does, I just stuck the result in the wrong place.

**Comment by retorquere** [comment]
5614 fixes it. Would appreciate it if you could check it does what you want.

**Comment by zepinglee** [comment]
It works correctly now.
