### ISSUE TITLE
Bug: Out of memory error on Windows

### ISSUE THREAD

**Issue by chiavez** [retorquere/zotero-better-bibtex#2748]
### Debug log ID

RCYJ3YSL-refs-euc/6.7.143-6

### What happened?

This problem is really similar to that shown in: https://github.com/retorquere/zotero-better-bibtex/issues/1575

**Steps to reproduce:**
1. open Zotero
2. right click on "My Library" on the left panel
3. click on "export library" in the context menu
4. choose the "Better BibLaTeX" format in the pop-up menu
5. uncheck all boxes in the 'Translator Options' of the pop-up menu
6. click on the 'OK' button
7. choose a file name and click on "Save" on the Windows Explorer pop-up menu

**Expected behaviour:**
exporting a .bib file for my whole library

**Actual behaviour:**
pop-up saying: "An error occurred while trying to export the selected file."

**Notes**
I tried to export each collection separately and **no** errors occur...

**Comment by retorquere** [comment]
You're actually running into #2315. I'm working on something that will relieve memory pressure, but that's a fair bit of work, and I don't know how long it will take. I see you've already turned off the cache, so short-term there's nothing that can be done about this (except moving to Zotero 7).

**Comment by retorquere** [comment]
The fix will be communicated on #2315, if you want to be kept updated, please join that issue.

**Comment by chiavez** [comment]
Hi, Thank you very much for the answer. I'll look at https://github.com/retorquere/zotero-better-bibtex/issues/2315 then. Good luck with the fix!

(By the way, if the issue is about the memory i can just select a smaller portion of my library to be exported, i guess)

**Comment by chiavez** [comment]
I wanted to add a quick tip to solve this problem easily (up to a certain extent at least). The issue is related to memory, therefore reducing the data to export fixes it. So, instead of exporting your library by splitting it into different .bib files, you can export your library altogether but with less information for each database entry. Anyway, many fields will not even show up in your bibliography (e.g. the 'abstract' field).

So i did the following:

1. Tools --> better bibtex --> open better bibtex preferences --> Export --> Fields --> 'Fields to omit from export (comma-separated)' 
2. then I put in the following list (I prefer simple bibliographies, everyone uses Google Scholar anyway): 'url, doi, language, urldate, note, annotation, file, abstract, keywords'
