### ISSUE TITLE
Recent update breaks zotxt

### ISSUE THREAD

**Issue by newhallroad** [retorquere/zotero-better-bibtex#2749]
### Debug log ID

ICIP9EVP-euc/6.7.143-6

### What happened?

Thank you for your wonderful work.

I believe a new release of better bibtext has broken something in zotxt. The key issue seems it might be `TypeError: zotero.BetterBibTeX.KeyManager.keys.findOne is not a function`.

My setup:
Zotero 6.0.30
Better BibTex for Zotero 6.7.143
zotxt 6.0.2
I am accessing zotxt through the pandoc-zotxt.lua filter in emacs 29.1 on Windows 10.
The filter should find entries in Zotero from their citekeys in my markdown file, and generate a bibliography. Now the debug log says that it is unable to find any entries. 

Here is the debug log:

```
(5)(+0062999): GET /zotxt/items?betterbibtexkey=yerushalmi_Introduction_2013 HTTP/1.1 Host: localhost:23119 Accept-Encoding: gzip

(3)(+0000004): TypeError: zotero.BetterBibTeX.KeyManager.keys.findOne is not a function findByBBTKey@chrome://zotxt/content/modules/Core.jsm:217:18 itemsEndpoint/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/alexanderkaye/AppData/Roaming/Zotero/Zotero/Profiles/79uiu4p8.default/extensions/zotxt@e6h.org.xpi!/bootstrap.js:420:24 itemsEndpoint@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/alexanderkaye/AppData/Roaming/Zotero/Zotero/Profiles/79uiu4p8.default/extensions/zotxt@e6h.org.xpi!/bootstrap.js:419:13 handleErrors/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/alexanderkaye/AppData/Roaming/Zotero/Zotero/Profiles/79uiu4p8.default/extensions/zotxt@e6h.org.xpi!/bootstrap.js:300:18 Zotero.Server.DataListener.prototype._processEndpoint<@chrome://zotero/content/xpcom/server.js:526:26 Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:302:5 Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:208:7

(5)(+0000002): HTTP/1.0 500 Internal Server Error X-Zotero-Version: 6.0.30 X-Zotero-Connector-API-Version: 2 Content-Length: 0 
```

I apologize because I think this might be something that the zotxt developer needs to fix. I posted an issue [there](https://github.com/egh/zotxt/issues/40#issue-1964722558) too and have not had a reply from the developer yet. Someone did post a suggestion in that thread, but I have been unable to fix the problem myself by modifying the zotxt xpi package. I am posting here in case you are able to fix the problem on your end.

Very many thanks.

**Comment by retorquere** [comment]
If the code is just trying to get the citation key, use this:

```
try {
  return item.getField('citationKey')
} catch (err) {
  return undefined
}
```

Sorry for the disruption. This code is future-proof and will also automatically work with the formal citation key field when it comes to Zotero.

**Comment by retorquere** [comment]
I will look tomorrow whether I can put a shim in place. But it'd be better to use the future-proof code.

**Comment by newhallroad** [comment]
Thank you so much for the very quick response. 
Could you advise on how to implement the code your recommendation?
As far as I can tell, the problematic line in zotxt is in `extension/content/modules/Core.jsm` ([here](https://github.com/egh/zotxt/blob/master/extension/content/modules/Core.jsm)).
The relevant line at 215 is:
```
function findByBBTKey(citekey, zotero) {
    let libraryID = zotero.Libraries.userLibraryID;
    let itemId = zotero.BetterBibTeX.KeyManager.keys.findOne({ libraryID, citekey }).itemID;
    return zotero.Items.getAsync(itemId);
}
```
Which part do you recommend I replace with your code?
Thank you for the more detailed advice.

**Comment by retorquere** [comment]
Ah that's different. I will have something tomorrow.

**Comment by retorquere** [comment]
See https://github.com/egh/zotxt/pull/42

**Comment by newhallroad** [comment]
Thanks again for working on this. I am still having trouble. 
See debug log M6IRRXC2-euc/6.7.143-6
The key lines are:
```
(5)(+0091297): GET /zotxt/items?betterbibxkey=yerushalmi_Introduction_2013 HTTP/1.1 Host: localhost:23119 Accept-Encoding: gzip

(5)(+0000002): HTTP/1.0 400 Bad Request X-Zotero-Version: 6.0.30 X-Zotero-Connector-API-Version: 2 Content-Type: application/json; charset=UTF-8 "No param supplied!"
```

It could be I am doing something wrong. I took your pull request and compressed the `extension` directory into a zip file, then changed the extension to `xpi` and loaded it as an add-on to Zotero. If I am doing something wrong, please let me know and I will retry.

**Comment by retorquere** [comment]
zotxt doesn't work for me at all, it's not installing the HTTP endpoint. I built it using `make notest`, but all that does is zip things up. But we should continue the conversation on the zotxt project, there's nothing to change about BBT to fix the problem, and the zotxt author will have to get involved, if only to merge the PR.

**Comment by retorquere** [comment]
> betterbibxkey=yerushalmi_Introduction_2013

this isn't right in any case, zotxt supports `betterbibtexkey` and `citekey` for citation key search

**Comment by newhallroad** [comment]
I know that's not conventional better bibtext or citekey syntax but if I am reading the [manual](https://github.com/odkr/pandoc-zotxt.lua/blob/main/man/man1/pandoc-zotxt.lua.rst#web-api) correctly, (perhaps I'm not,) zotxt should recognize it if I have pinned the key. In any case, I agree that I don't think this is the fundamental issue. I'll continue on the zotxt issues site as you suggest.

**Comment by retorquere** [comment]
No I mean your URL has `betterbibxkey` where it should be betterbib**te**xkey.

**Comment by retorquere** [comment]
But other than that yeah I really can't do much, zotxt will need to be updated. I don't know why it doesn't initialize properly for me, I see no errors.
