### ISSUE TITLE
"Report number" field is incorrectly translated into the "issue" field when importing a techreport from a .bib file

### ISSUE THREAD

**Issue by dorian-groll** [retorquere/zotero-better-bibtex#2752]
### Debug log ID

6JFT6T6Q-refs-euc/6.7.143-6

### Expected behaviour

I want to import a .bib file in Zotero, which contains only reports ("@techreport" entries). Each one of them has a "number" field, that I expect to become a "Report Number" field once imported in Zotero. 

The import does behave as expected when Zotero Better Bibtex is disabled:  the "number" field is indeed used to populate the "Report Number" field in Zotero. 

### Actual behaviour

However, when Zotero Better Bibtex is enabled, the "number" field is saved as an "Issue" in the "Extra" attributes of Zotero. For instance, importing the following entry from a .bib file produces the result pictured in the screenshot here below:
```bib
@techreport{customCitationKey,
  title = {What a Great Report},
  author = {{A very well-known and serious institution}},
  year = {1995},
  month = jan,
  number = {my\_precious\_report\_number},
  pages = {6},
  langid = {english}
}
```
![better_bibtex_report_number_bug](https://github.com/retorquere/zotero-better-bibtex/assets/42706184/74cfeead-b3fe-4b56-b514-551e6496e717)

### Source of the issue

While trying to find where the problem comes from, I have found that the [BibTeX translator used by Zotero](https://github.com/zotero/translators/blob/master/BibTeX.js) specifically addresses the case of techreports through a "fix" (as commented). Lines 398 through 400 are reproduced below:
```js
else if (field == "number") { // fix for techreport
		if (item.itemType == "report") {
			item.reportNumber = value;
```

I wanted to check whether the Better Bibtex translators were also taking this specific case into account, but it does not seem to be the case. In [bibtex.ts, line 943](https://github.com/retorquere/zotero-better-bibtex/blob/5eb4e571b771b2983d8708c00214184f9508a389/translators/bibtex/bibtex.ts#L943), the "number" attribute is defined as such: 
```ts
protected $number(_value: string): boolean {
    let field = 'issue'
    let numbers = (this.bibtex.fields.number || []).map(n => `${n}`)
    const issues = (this.bibtex.fields.issue || []).map(n => `${n}`)

    if (this.item.itemType === 'patent') {
      field = 'number'
      if (this.patentNumberPrefix) {
        const patentNumberPrefix = this.patentNumberPrefix.toLowerCase()
        numbers = numbers.map(n => n.toLowerCase().startsWith(patentNumberPrefix) ? n : `${this.patentNumberPrefix}${n}`)
      }
    }

    return this.set(field, numbers.concat(issues).join(', '), [field])
  }
```
Here, `let field = 'issue'` does seem to define "issue" as the default field for the number attribute. An exception is made for patents below. I may very well be mistaken and maybe other files are involved, but I guess that this part of the code should be changed to take into accounts the "report" itemType and add another exception. If you can confirm that it would indeed fix the problem, I can try and submit a pull request.

**Comment by retorquere** [comment]
Thank you for reporting this. Build 5634 fixes it. If you can confirm that this does what you need, I can cut a new release.

**Comment by zepinglee** [comment]
I would like to suggest more item types besides `report`. The following is a list of Zotero item types that have `number` fields (taken from <https://github.com/zotero/zotero-schema/blob/master/schema.json> by searching `: "number"`).

Zotero item type | `number` field name | `biblatex` entry type
--- | --- | ---
`bill` | `billNumber` | `legislation` (Non-standard type)
`case` | `docketNumber` | `jurisdiction` (Non-standard type)
`dataset` | `number` | `dataset`
`hearing` | `documentNumber` | -
`patent` | `patentNumber` | `patent`
`podcast` | `episodeNumber` | `audio` (Not specified but used in `biblatex-apa`)
`preprint` | `archiveID` | -
`radioBroadcast` | `episodeNumber` | `audio` (The most suitable type I guess.)
`report` | `reportNumber` | `report`
`standard` | `number` | `standard` (Non-standard type)
`statute` | `publicLawNumber` | `legislation` (Non-standard type)
`tvBroadcast` | `episodeNumber` | `video` (Not specified but used in `biblatex-apa`)

**Comment by retorquere** [comment]
Don't know how I missed that. A new build is incoming. I haven't changed `video` and `audio` entry types though. I don't think mapping `@video` to `tvBroadcast` and `@audio` to `radioBroadcast` is warranted.

**Comment by dorian-groll** [comment]
Thank you very much for this very quick fix, it works exactly as expected with [test build 6.7.143.2752.5634](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.143.2752.5634.xpi). And thank you for this add-on in general, it is incredibly useful!

**Comment by retorquere** [comment]
That implements all the changes outlined above
