### ISSUE TITLE
Onboarding is not shown after first install

### ISSUE THREAD

**Issue by niklasbogensperger** [retorquere/zotero-better-bibtex#2755]
### Debug log ID

NZHUB9JW-refs-euc/6.7.143-6

### What happened?

As mentioned in the title, the onboarding mentioned in the manual (Installation -> "On first install you will be asked a few questions. Please read these instead of just clicking through." at the bottom) is never shown.
I have restarted Zotero and uninstalled/reinstalled the plugin several times but such a window was never shown.

**Comment by retorquere** [comment]
I thank you for your diligence, but the onboarding wizard has been removed as it seemed to raise more questions than answer them. I have updated the installation page, that will take about 10 minutes to show up publicly.

**Comment by niklasbogensperger** [comment]
That makes sense, thanks for the quick response!
