### ISSUE TITLE
Suggestion for emacs integration of CAYW

### ISSUE THREAD

**Issue by newhallroad** [retorquere/zotero-better-bibtex#2758]
### Debug log ID

No debug log; suggestion for addition to documentation

### What happened?

This is a suggested **emacs** addition to the "Editor Integration" section of the [CAYW documentation](https://retorque.re/zotero-better-bibtex/citing/cayw/index.html).
I wrote a function in elisp, which brings up the CAYW input, adds the chosen items as pandoc citations to the buffer, and moves the point to after the citations. I use this in markdown-mode. Emacs users who use org-mode may (or may not) need something different.
I am not any kind of expert, but this works well for me and I thought some of your users may find it useful. 
Here is the function:
```
(defun alk/bbt-zotero-insert-key ()
  "Run shell command to bring up better bibtex cayw input and insert pandoc citation at point"
  (interactive)
  (shell-command "curl -s http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc^&brackets=true" t nil) ; caret escapes ampersand 
  (search-forward "]") ; place cursor after inserted citation
  )
```

Separately, I think there is a typo in the documentation. On the very last line, `select=true` should be `selected=true`.

**Comment by newhallroad** [comment]
Thank you bot, but there is no debug log as this is a suggestion for an addition/correction to the documentation. Please let me know if you would prefer me to submit it somewhere other than here. Thanks.

**Comment by retorquere** [comment]
Thanks for the addition!

> Please let me know if you would prefer me to submit it somewhere other than here.

I've copy-pasted your text above into the page, but for the docs, there's a pencil in the top-right of each page where people can suggest edits.

> Separately, I think there is a typo in the documentation. On the very last line, `select=true` should be `selected=true`.

Not a typo, but I've moved that line into the main table of options for clarity.

**Comment by newhallroad** [comment]
Thanks for this. I hope my code is of help to others. 
Thanks for telling me about that pencil. I'll use that in future.
Sorry I misunderstood your documentation about `select`. You were right, of course.
As it happens, though, I have been unable to get the `select` option to work. If I have a moment, I'll open a separate issue about it.
