### ISSUE TITLE
Export unicode character ő as latex command broken in 6.7.144

### ISSUE THREAD

**Issue by trappitsch** [retorquere/zotero-better-bibtex#2761]
### Debug log ID

74E5JK89-refs-euc/6.7.144-6

### What happened?

Exporting a bibliography with an author's name containing an ő results in a incorrect `bib` file when `Export unicode as plain-text latex commands` is activated.
The author's last name is Pető.

Expected export: Pet{\H o}
Actual export (in 6.7.144): Pet{\Ho}

Downgrading to 6.7.143 fixes this and the author is correctly exported as described above.

Hope this description is not too concise, happy to clarify/test!

Thanks!

**Comment by retorquere** [comment]
Thanks for reporting, a new version is running through release tests now.

**Comment by trappitsch** [comment]
Thanks for the quick fix, it's all working as of the latest release!
