### ISSUE TITLE
Reverting original Zotero Citation Keys

### ISSUE THREAD

**Issue by umutkaya-ugent** [retorquere/zotero-better-bibtex#2762]
### Debug log ID

donhaveonesincedeletedtheapp

### What happened?

Better Bibtex cannot replicate the default Zotero citation keys perfectly. It is difficult to revert back to the defaults even after deleting the add-on as they are stored in the extra field. There should be an option to do this easily or documentation on how to do it:

For those using Zotero Cloud:
- Unpinning they keys (select all items in library, right click -> Better Bibtex -> Unpin) would remove the "fixed" citation keys created by the extension (which are stored in the extra field).
- Afterwards, sync the database.
- In order to get rid off the effects of the extension: If you had secured your files on the cloud, try deleting ~/Zotero and ~/.zotero, and reinstalling the application. 
-Finally sync and export as usual.

**Comment by retorquere** [comment]
Please use discussions for this kind of thing. The documentation is user-editable (pencil icon at the top-right of the webpage) so have at it.
