### ISSUE TITLE
Zotero was unable to load translators and styles

### ISSUE THREAD

**Issue by zcliminghui** [retorquere/zotero-better-bibtex#2766]
### Debug log ID

JAL9QEQT-apse/6.7.147-7

### What happened?

Zotero7 Updated to the latest version: "Zotero was unable to load translators and styles", Unable to return to original interface

**Comment by retorquere** [comment]
No longer a problem? Just to be sure, the only errors I see in `JAL9QEQT-apse/6.7.147-7` are from jasminum or zoterostyle.
