### ISSUE TITLE
Better BibTeX startup failed (TypeError: item Toolbar is null)

### ISSUE THREAD

**Issue by panmengguan** [retorquere/zotero-better-bibtex#2767]
### Debug log ID

WKQ9HR98-fio-qHjOR2O2OTl3

### What happened?

After Zotero updated to 7.00-beta.55+9151fb355 (64-bit), It displayed "Better BibTeX startup failed (TypeError: item Toolbar is null)" when Zotero started, and the bibtex key

![image](https://github.com/retorquere/zotero-better-bibtex/assets/4384206/698116c5-4656-4962-998a-992d2d6a21d3)

**Comment by retorquere** [comment]
Can you verify you're in the latest version?

**Comment by retorquere** [comment]
You are not on the latest version. If you upgrade the problem will go away.

**Comment by panmengguan** [comment]
Thanks. It was fixed after updating betterbibtex manually.

**Comment by retorquere** [comment]
Yeah plugins update within 48 hours so usually I would have been able to have an update ahead of time, but this change came unannounced so I had to put out an emergency fix. It's fortunate I could even find the time.
