### ISSUE TITLE
One issue with using the Zotero Integration in Obsidian with support from Better BibTex

### ISSUE THREAD

**Issue by xuanera33** [retorquere/zotero-better-bibtex#2769]
### Debug log ID

JBBRMCXA-euc/6.7.147-7

### What happened?

I use Zotero and Obsidian for my work. Specifically, I use the Zotero Integration add-in in Obsidian to import my Zotero notes to my Obsidian files, which requires necessary support from Better BibTex for Zotero. I have used this workflow for almost one year and did not meet any problems until Jan. 4, 2024, when you published the edition of 6.7.143. I tried to import notes as usual, but I got an error message in Obsidian, "Error retrieving item data: Unexpected end of JSON input". On that day, I tried all the ways I could find to fix it, but they didn't work. Finally, I deleted the edition of 6.7.143 and added the old one, 6.7.136, back. The problem was solved!!! Then, I just closed the auto-updated option for the add-on and thought this problem would not bother me again!

It was my bad that I forgot to close the auto-updated option for my Zotero. The software was updated today, and when I opened it, my Better-BibTex 6.7.136 reported an error, " Better BibTex startup failed. TypeError: itemToolbar is null". I thought you guys probably had found my issues in the edition of 6.7.143, so updating Better BibTex to the latest edition (6.7.147) may solve these two errors together. However, I got the same error message in my Obsidian again ("Error retrieving item data: Unexpected end of JSON input") after updating my add-on to the edition of 6.7.147. Now, I'm frustrated and have no idea how to deal with it. I'm not a professional computer person. What I can do is limited. But I really love my workflow and don't want to give it up.  Please help me to check what the problem is here. I will be happy to provide any information you may need!

**Comment by retorquere** [comment]
I don't know what other plugin (for Zotero or Obsidian) is involved here, so I have no idea what could be going wrong here, but whatever problem needs solving, if something needs to be done on the BBT side, it will be on 6.7.147 or later. I cannot support older BBT versions.

**Comment by retorquere** [comment]
Looks to be a plugin to obsidian. I'd need to know which.

**Comment by retorquere** [comment]
The only error in `JBBRMCXA-euc/6.7.147-7` is from the inspire plugin you have installed

**Comment by retorquere** [comment]
In any case you'll have to get the author of that obsidian plugin involved. I don't know what that plugin is calling from BBT that gives the response it did not expect.

**Comment by retorquere** [comment]
Could it be this issue: https://github.com/mgmeyers/obsidian-zotero-integration/issues/330

if so, the author of the obsidian plugin has a fix.

**Comment by xuanera33** [comment]
> Could it be this issue: [mgmeyers/obsidian-zotero-integration#330](https://github.com/mgmeyers/obsidian-zotero-integration/issues/330)
> 
> if so, the author of the obsidian plugin has a fix.

Yes!!!!! It is!!!! The plug-in I use in Obsidian is Zotero Integration. I'm sorry that I thought it was the issue with the Better BibTex plug-in. Thank you so much for your help and effort!!! Great work!!!
