### ISSUE TITLE
shorttitle in citekeys always pinyinized

### ISSUE THREAD

**Issue by astanabe** [retorquere/zotero-better-bibtex#2770]
### Debug log ID

6N43WGW4-refs-apse/6.7.147-6

### What happened?

Hi,

Thank you for developing useful plugin!

I'm using Better-Bibtex to export .bib  files and Citation key formula I'm using is "auth+year+shorttitle".
However, shorttitle has been always pinyinized even if "Force citation key to plain text" and "Ideographs in citekeys" are disabled.

Best regards,

**Comment by astanabe** [comment]
Thank you for your quick reply.

I downloaded and tested [test build 6.7.147.2770.5730](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.147.2770.5730.xpi).
I confirmed that the test build worked fine.

Thanks again.

Best regards,

**Comment by retorquere** [comment]
I'll cut a new release tonight
