### ISSUE TITLE
“Import errors found” on importing bib file

### ISSUE THREAD

**Issue by r13s** [retorquere/zotero-better-bibtex#2771]
### Debug log ID

A2P9DDJR-refs-euc/6.7.147-6

### What happened?

How to reproduce:

- Follow the link: https://primo.nlr.ru/permalink/f/oo3rn7/07NLR_LMS012806668
- Scroll down the page
- Click “EXPORT BIBTEX”
- Select an encoding
- Click “DOWNLOAD”
- Import the downloaded bib file into Zotero (File — Import)

**Comment by retorquere** [comment]
When I download from that URL, I get

```
@book{АренсЗ2022Кдпз,
series = {Серия "Между строк"},
abstract = {Метод Zettelkasten - это эффективная система организации полезной информации, идей для работы и учебы, развития мышления, придуманная немецким социологом Никласом Луманом. С помощью этой книги вы освоите принцип полезных заметок и поймете не только то, как он работает, но и почему. Неважно, кто вы
 и чем занимаетесь - учитесь в университете, пишете статьи или просто читаете книги и изучаете интересную информацию, - с помощью метода Zettelkasten вы на
учитесь делать это более продуктивно и без лишних усилий},
publisher = {Манн, Иванов и Фербер},
booktitle = {Как делать полезные заметки эффективная система организации идей по методу Zettelkasten},
isbn = {978-5-00169-985-9},
year = {2022},
title = {Как делать полезные заметки = How to take smart notes : эффективная система организации идей по методу Zettelkasten},
language = {rus},
address = {Москва},
author = {Аренс З},
keywords = {Знание -- Усвоение -- Психологические исследования -- Популярные издания NLR12::RU\NLR\AUTH\66645826},
lccn = {978-5-00169-985-9},
}
```

but that entry has `\6` in the keywords field, which isn't syntactically valid bibtex. It also has macros `\NLR` and `\AUTH` of which I don't know what they mean, but at least they're valid latex.

You can import this by either:

* fixing the keywords field to be valid latex
* removing the `keywords` field from the input, or
* adding the `keywords` field to [verbatimFields](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html#verbatimfields)

but I'd say you wouldn't want to do the last option structurally.

**Comment by retorquere** [comment]
> It looks like the `keywords` field starting from `NLR12` to the end of the line contains a MARC record in RUSMARC ISO 2709 format.

So that's an error on their end it seems. I'm working on making this parsable, but they really should fix their bibtex output.
 
> I'm not proficient in LaTeX, so I'd rather import the ris file (you can download it there) instead of the bib file. Or fill in all the data manually.

I do not understand what you are asking here.

**Comment by retorquere** [comment]
> Just saying, I would rather import a different file format instead of editing the bib file or using hidden preferences. I

But then why don't you just import a different file format? That page does offer RIS export and BBT is not involved at all with RIS import.

**Comment by retorquere** [comment]
No problem. Next version of BBT will tolerate the input with the error.
