### ISSUE TITLE
URL import isn't precisely verbatim

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#2772]
### Debug log ID

PEN7XJ77-euc/6.7.148-6

### What happened?

Find out how to handle `\url`/`\href` imports. They're not verbatim (`\foo` expands), but they're not regular LaTeX (`~` and `#` are passed through as regular text)

```
\newcommand{\foo}{FOO}
\begin{document}
\url{hi~there\foo} 
```

**Comment by retorquere** [comment]
@njbart any clues on this?

**Comment by njbart** [comment]
What's the use case? Do such URLs containing TeX/LaTeX commands/macros ever appear in databases in the wild?

I found one example where using such a URL might conceivably make sense inside a LaTeX document (https://tex.stackexchange.com/questions/331210/how-to-i-use-a-command-in-a-href) - but in a database?

**Comment by retorquere** [comment]
No specific use-case, just trying to understand what's going on.
