### ISSUE TITLE
export using python script

### ISSUE THREAD

**Issue by sangkookchoi** [retorquere/zotero-better-bibtex#2774]
### Debug log ID

6NCVXBUM-refs-apse/6.7.148-6

### What happened?

When I export a collection with ~40 articles with the following python script

urllib.request.urlretrieve('http://127.0.0.1:23119/better-bibtex/export/collection?/1/QuantumZenoMonteCarlo.biblatex', "library.bib")

, it works fine.

However, when I try to export my whole library ("My Library") with ~4000 articles by using the following python script, 

urllib.request.urlretrieve('http://127.0.0.1:23119/better-bibtex/export/library?/1/library.biblatex', "library.bib")

it fails with the following error:
HTTPError: HTTP Error 500: Internal Server Error.

**Comment by retorquere** [comment]
A new version is out (v6.7.149) that fixes this problem.

**Comment by sangkookchoi** [comment]
Thanks:)
