### ISSUE TITLE
After the recent update to Better Bibtex for Zotero I cannot knit any Rmd rticles that contain citations

### ISSUE THREAD

**Issue by tmyack** [retorquere/zotero-better-bibtex#2778]
### Debug log ID

send to file.io

### What happened?

, I receive this error:  Error in result$result[[3]] : subscript out of bounds Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> force -> bbt_bib -> .action Execution halted,

**Comment by retorquere** [comment]
This seems to be a problem with something on the rstudio side. Without a debug log, I can't tell you what is being called in BBT, so there's no further information I can give you.
