### ISSUE TITLE
Better BibTex "disable"

### ISSUE THREAD

**Issue by RemyDadier** [retorquere/zotero-better-bibtex#2785]
### Debug log ID

951367618-euc

### What happened?

Hello, I recently changed my computer. I reinstalled my Zotero (version 6.0.30) and since then my Better BibTex (last version available to my knowledge 6.7.159) no longer works (impossible to download the extension on my Zotero). Indeed, I'm stuck on: "Better BibTex for Zotero will be installed after you restart Zotero". With no change on restart and no reaction when I click "Undo". Can you help me ? My goal is to be able to install BibTex again because I use it daily and have been for many years now and this problem is holding me back in my research. Thank you so much for your help and for your contribution to the community through this extension!

(Not having BibTex so I am not able to provide you with a debug log ID, so do not take into account the one provided which is invented in order to be able to submit my request)

Here's a picture of what I've been stuck on for a week now :
![image](https://github.com/retorquere/zotero-better-bibtex/assets/104691625/db437039-14a5-47d8-94ac-0ced032ebf72)

**Comment by retorquere** [comment]
What operating system do you use?

**Comment by RemyDadier** [comment]
Window 64 bit

**Comment by RemyDadier** [comment]
Window 11 * sorry

**Comment by retorquere** [comment]
Press the Windows key, type `PowerShell` into the search bar, and press Enter. This will open a new PowerShell window.

In the PowerShell window, type the following command and press Enter to start output capture:

```
Start-Transcript -Path "$HOME\Desktop\transcript.txt"
Start-Process -FilePath "C:\Program Files (x86)\Zotero\zotero.exe" -ArgumentList "-ZoteroDebugText"### 
```

wait for Zotero to start, open the plugins window to verify it's still in the "restart" state, then go back to powershell and type

```
Stop-Transcript
```

and then attach the `transcript.txt` file that was created on your desktop here.

**Comment by RemyDadier** [comment]
Le voici : 

[transcript.txt](https://github.com/retorquere/zotero-better-bibtex/files/14210557/transcript.txt)

**Comment by retorquere** [comment]
There's nothing in it. I'll have to ask Zotero how to capture the log then. Windows is such a pain with this.

**Comment by retorquere** [comment]
I have just tried a clean install on a windows system and I can't yet replicate this.

**Comment by RemyDadier** [comment]
It's really weird... In any case, thank you for taking your time to help me, it's very kind of you. Isn't there a way to completely manually remove all traces of Better BibTex (without having to go through zotero) in order to start from scratch?

You see, there is this annotation "disabled" that appears in the BibTex version but it doesn't delete the extension which prevents me from reinstalling it on top of it in order to get around the problem.

![image](https://github.com/retorquere/zotero-better-bibtex/assets/104691625/3498389c-ee52-4f42-a840-818bcc06bf7f)

**Comment by retorquere** [comment]
Oh if that's all you want: 

* shut down zotero
* open the explorer, go to `C:\Users\<your user name>\AppData\Roaming\Zotero\Zotero\Profiles`
* there will be a single folder with a bunch of random characters in front, go into that
* go into the `extensions` folder
* delete the folder `better-bibtex@iris-advies.com` or file `better-bibtex@iris-advies.com.xpi` you find there.

and then start zotero

**Comment by RemyDadier** [comment]
I don't know if this action will solve the problem, but it's worth a try just in case (if it does, I'll let you know so you can warn future users if necessary). And this action won't damage my zotero database, will it?

**Comment by retorquere** [comment]
Nope. Deleting `better-bibtex@iris-advies.com` or file `better-bibtex@iris-advies.com.xpi` doesn't even touch the BBT-private data, those are just the code of BBT itself.

**Comment by RemyDadier** [comment]
it works! Thank you very much once again for the time you spent helping me with my problem. I've converted my entire research lab to your extension (coupled with Obsidian software) and I can't thank you enough for the time you save me every day! 

![image](https://github.com/retorquere/zotero-better-bibtex/assets/104691625/b93f003a-9ff2-424a-b519-12368c87b206)
