### ISSUE TITLE
Double newlines means parbreak

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#2789]
### Debug log ID

E742428P-refs-euc/6.7.159.emile.kiku.fritz.box-6

### What happened?

Double newlines should be interpreted as a parbreak

**Comment by acsr** [comment]
After upgrading today to BetterBibTex 6.7.160 my eta-template was not working like expected anymore.

it.items serialized from JSON were not seperated by parbreaks at the end of the nested output of the template.

The JSON l directly exported via BetterBibTeX json looked OK.

@retorquere Can you remember I had to work around differences between newlines and paragraph breaks to make it working for me in Logseq.

I am not sure if I need to change my template or something is missing in your update. 
In any case it should not pass silently.

### Example Export

In line 12 the next item starting at `- ### The Most Dangerous Writing App` is concatenated to the preceeding item without any delimiter.

```markdown
- ### The Least Dangerous To-Do List
creators:: author: Manuel Ebert
url:: https://theleastdangeroustodolist.com
tags:: #[[Schreiben]], #[[Writing]], #[[Online Tools]], #[[Tools]], #[[Writing Software]], #[[Writing Blog Posts]], #[[Text Creation]], #[[Schreibblockade]], #[[Manu Ebert]], #[[The Most Dangerous Writing App]]
zotero:: [@ebertLeastDangerousToDo2023](zotero://select/groups/5387086/items/E6Q3V4RB)
  - #### abstractNote
    The satisfaction of checking things off your to-do list, without any of the hard work.
  - #### Relations
    - http://zotero.org/groups/3305/items/HPSPXE2V
    - http://zotero.org/groups/5387086/items/IJ6LI577
    - http://zotero.org/groups/5387086/items/IQ438J55
    - http://zotero.org/groups/5387086/items/Y428Z85I- ### The Most Dangerous Writing App
creators:: author: Manuel Ebert
url:: https://maebert.github.io/themostdangerouswritingapp
tags:: #[[Schreiben]], #[[Writing]], #[[Online Tools]], #[[Tools]], #[[Writing Software]], #[[Writing Blog Posts]], #[[Text Creation]], #[[Schreibblockade]], #[[Manu Ebert]], #[[The Most Dangerous Writing App]]
zotero:: [@ebertMostDangerousWriting2022](zotero://select/groups/5387086/items/IQ438J55)
  - #### abstractNote
    Don’t stop typing, or all progress will be lost.
  - #### Relations
    - http://zotero.org/groups/3305/items/K69CGHDJ
    - http://zotero.org/groups/5387086/items/E6Q3V4RB
    - http://zotero.org/groups/5387086/items/IJ6LI577
    - http://zotero.org/groups/5387086/items/Y428Z85I
```

Thanks for all your efforts.

**Comment by acsr** [comment]
OK Race Condition with your answer and my final edit above. Need to come back on this tomorrow...

**Comment by retorquere** [comment]
That's fine. Please remember that if I am to debug anything that generates output I will always require a debug log (with `-refs-` in it). There's no use in me trying to guess what the input was that breaks something when you can just hand me a ready-to-use testcase.

**Comment by acsr** [comment]
I will mandatory include debug log ID every time in the future I

**Comment by acsr** [comment]
Opened a new issue and created a related Debug log with ID
