### ISSUE TITLE
My citation key formula suddenly includes editors for book sections even when there is a declared author

### ISSUE THREAD

**Issue by Ibai-Asensio** [retorquere/zotero-better-bibtex#2794]
### Debug log ID

NSVP5WV7-euc/6.7.162-6

### What happened?

Dear Emiliano,

First of all a thousand thanks for developing such a great tool and keep it updated, it is truly great.

My issue is simple and stated in the title. Suddenly (maybe after updating Zotero to version 6.0.31, but I'm not sure) ==the citation key I have been using for a long time changed its behavior. Now, it includes the book editors in book sections, along the authors, even though the author field is *not* empty==. This is breaking many citations in my current project.

I have checked the guidelines for generating citekeys and think that there hasn't been any change, or at least it still says "All auth... functions will fall back to editors if no authors are present on the item".

I hope you can find time to look into this and hopefully fix it. Or, if I'm making a mistake, for which I apologize in advance, perhaps taking a moment to point me towards it. I also apologize if more people is sending the same issue (plausible if this comes from an update…).

That is all, thank you very much in advance for your time.

Ibai

**Comment by retorquere** [comment]
Hi,

I need a debug log created by right-clicking the entry that exhibits this problem and sending a debug log from the popup menu. The debug log ID will have `-refs-` in it.

**Comment by Ibai-Asensio** [comment]
Hi,

Done! I think. I submitted the debug log for two example entries through the right-click menu.
(I wasn't fully sure that was it so I sent another full debug log, ID ZE74VZRA-euc/6.7.162-6).

**Comment by retorquere** [comment]
This is also a debug log from the Help menu. Please select an item where key generation doesn't work like you expect, right-click it, and send a debug log from the menu that pops up, under the "Better BibTeX" option. If the ID does not contain `-refs-`, it's not the right debug log for this case.

**Comment by Ibai-Asensio** [comment]
Ah, I see. It didn't pop up when selecting two items, my bad. Thanks for the guidance!
These are the IDs for the two examples:

TWDRBXEI-refs-euc/6.7.162-6
Y67N6ZDE-refs-euc/6.7.162-6

**Comment by retorquere** [comment]
It should pop up regardless, also if you have two selected, but this works too.

**Comment by Ibai-Asensio** [comment]
This works beautifully again. Thank you so much!!!
