### ISSUE TITLE
Exporting "#" in hashtags. 

### ISSUE THREAD

**Issue by mms-neuro** [retorquere/zotero-better-bibtex#2795]
### Debug log ID

YTH373FG-euc/6.7.162-6

### What happened?

Using the combination of 
"zotero-storage-scanner"
"zotero-better-bibtex" and 
lualatex+biber, I have the following problem:

Zotero-storage-scanner creates "#nosource"-tags, which are then exported by zotero-better-bibtex as keywords (with the "#") into the .bib-files. These crash then in the longtem the combination of lualatex+biber, since it does not expect the hashtag in the keyword-field. 

I'm not sure, where excatly the "error" is, but the combination is fatal.

**Comment by retorquere** [comment]
You need to right-click the entry and send a BBT debug log from the menu that pops up. The ID will have `-refs-` in it.

**Comment by retorquere** [comment]
@njbart, between this and #2781 I don't know what to make of `keywords` fields. Escaping `_` breaks tag filtering, but `#` can't be in the keywords field without escape.

**Comment by mms-neuro** [comment]
Like that? 
NZZVUN8A-refs-euc/6.7.162-6
That's one entry, which has #nosource as tag (the nosource without hashtag came because I renamed all tags at another computer to fix the problem temporarily).

**Comment by retorquere** [comment]
I may have to just filter out the `#`, but I'd like to understand what the rules are for this field. It's apparently not simply verbatim-or-not.

**Comment by retorquere** [comment]
Looks like tags tolerate everything except `#` and `%`.

**Comment by retorquere** [comment]
I think it's more likely that people will want to filter on tags than want to print them, and since  escaping breaks filtering, I'm going to keep that as the primary use case. Printing will still be possible with the workarounds you mention.

I have to admit - I don't know what "literal mode" entails. Is that what I might know as regular document body mode?

**Comment by njbart** [comment]
> I think it's more likely that people will want to filter on tags than want to print them, and since escaping breaks filtering, I'm going to keep that as the primary use case. Printing will still be possible with the workarounds you mention.

Agree.

> I have to admit - I don't know what "literal mode" entails. Is that what I might know as regular document body mode?

Yes. "[LaTeX] regular document body mode" captures it quite nicely.

**Comment by retorquere** [comment]
As an aside -- is there a difference between `--` and `\textendash`? [This](https://tex.stackexchange.com/a/132675) seems to indicate that `\textendash` should be preferred and that `--` requires extra packages/config, but I've always used `--` without having to do anything.

**Comment by njbart** [comment]
Extra packages: None required.

Whether you're using the one or the other might have effects on hyphenation though, and it seems if you do want to allow a linebreak you should use `--` (see [here](https://tex.stackexchange.com/questions/601632/whats-the-difference-between-and-textendash)).
