### ISSUE TITLE
Auto-export git pull and git push error

### ISSUE THREAD

**Issue by thiagocorreiap** [retorquere/zotero-better-bibtex#2803]
### Debug log ID

LRQQ4L4X-refs-euc/6.7.163-6

### What happened?

There is an error appearing when BBT tries to auto-export and use git. The message says it is an error on git pull and git push. Indeed I can see the process happening on my GitHub Desktop application. I am able to see that BBT created a commit and committed it. However they just accumulate and never get pushed. If I push manually it works.

I'm using auto-export + git to update my `.bib` file on Overleaf. I have followed the steps described in the [documentation](https://retorque.re/zotero-better-bibtex/exporting/auto/index.html) to set it up. The git I'm using is the one provided by the Overleaf.

**Comment by retorquere** [comment]
Can you try configuring the global git name & email?

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

**Comment by thiagocorreiap** [comment]
It is working now! Thank you for the support and quick reply. The solution was simpler than that. I just had to do a `git pull` on my terminal. It asked for my overleaf credentials and then everything started working as normal.
Thank you again
