### ISSUE TITLE
authorsn should not have ea

### ISSUE THREAD

**Issue by phamdn** [retorquere/zotero-better-bibtex#2807]
### Debug log ID

TLBEJAFM-refs-euc/6.7.164-6

### What happened?

authorsn(2) returns the last name of the first two authors and "ea". The "ea" part is not necessary as many other author functions already have it. 
I would love to have  "ea" removed from authorsn or have a new author function similar to authorsn but without "ea".

**Comment by retorquere** [comment]
you're using `authAuthEa`, I'm not going to remove the `ea` appending from that. Maybe try `creators(n=2)`

**Comment by phamdn** [comment]
I probably copied the debug log when using `authAuthEa`. Here is the new Debug log ID VUYA432F-refs-euc/6.7.164-6 for `authorsn` in case you need.
Anyway, `creators(n=2)` works well for me. Thank you very much for the suggestion.
