### ISSUE TITLE
Slowing down Zotero when the Add-on is turned on

### ISSUE THREAD

**Issue by sammo3182** [retorquere/zotero-better-bibtex#2809]
### Debug log ID

8A9FQ6NR-refs-apse/6.7.165-7

### What happened?

It looks like `Better bibtex` slows down Zotero 7 dramatically. I am using the latest released version of Zotero Beta 7 in Win 11. Every move including clicking the menu or importing new items takes a much longer responding time. It sounds similar to #2783, but on my side, you still get responses but very slow.

My entire team are heavy users of better bibtex, but right now we have to turn it on and off manually to maintain the basic function of Zotero. We'll appreciate it if a newer update could address this issue!

**Comment by retorquere** [comment]
There's nothing that stands out in the log. My main suspicion would be auto-export, I'm working on a performance fix there but it's slow going. Try setting auto-export to "in idle", if it's the auto-export, that should make a big difference.

**Comment by sammo3182** [comment]
> There's nothing that stands out in the log. My main suspicion would be auto-export, I'm working on a performance fix there but it's slow going. Try setting auto-export to "in idle", if it's the auto-export, that should make a big difference.

You are a life savor, Emiliano! Indeed, big difference, like everything becomes smooth immediately!

**Comment by retorquere** [comment]
That's great because the performance fix I'm working on addresses this specific issue. Once that is done you should be able to use "On Change" without the slowdowns.

**Comment by daeh** [comment]
Just linking the original issue #2667

**Comment by retorquere** [comment]
a build will drop on #2667 in a few minutes that has the performance fix; please follow that issue and comment there for further questions.
