### ISSUE TITLE
Feature Request: Support for Chinese Quotation Marks When Exporting with “Export unicode as plain-text latex commands”

### ISSUE THREAD

**Issue by TomBener** [retorquere/zotero-better-bibtex#2810]
### Debug log ID

CXQBCHI2-refs-apse/6.7.165-7

### What happened?

Thanks for your work to create great BBT.

I am writing to suggest an enhancement related to the handling of Chinese quotation marks in bibliographic entries when exporting with the “Export unicode as plain-text latex commands” option enabled. The context of this request is to improve the usability of BBT for users who work with Chinese-language sources and need to maintain the correct formatting of Chinese quotation marks in LaTeX documents.

### Current Behavior

When exporting items from Zotero using Better BibTeX with the “Export unicode as plain-text latex commands” option toggled, the export process converts standard quotation marks into LaTeX-style double quotes. For example, a title in the Zotero library like `被“废除不平等条约”遮蔽的北洋修约史（1912--1928）` is exported as:

```bibtex
@book{tangqihua2010,
  title = {被``废除不平等条约''遮蔽的北洋修约史（1912--1928）},
  author = {唐启华},
  date = {2010-09-01},
  publisher = {社会科学文献出版社},
  location = {北京}
}
```

### Expected Behavior

For Chinese-language bibliographic entries, it would be preferable to maintain the original Chinese quotation marks in the exported `.bib` file, like so:

```bibtex
@book{tangqihua2010,
  title = {被“废除不平等条约”遮蔽的北洋修约史（1912--1928）},
  author = {唐启华},
  date = {2010-09-01},
  publisher = {社会科学文献出版社},
  location = {北京}
}
```

This issue is also discussed in the context of LaTeX usage with Chinese texts in [CTeX group](https://github.com/CTeX-org/ctex-kit/issues/389).

### Suggested Feature

I propose that BBT could include an option or automatically detect Chinese-language entries to preserve the original Chinese quotation marks when the “Export unicode as plain-text latex commands” option is active. This feature would significantly enhance the accuracy and readability of bibliographic references for academic writing and publication in Chinese studies.

Thank you for considering this feature request. I believe it would make BBT even more valuable for a broad user base, especially those engaged in multilingual academic work.

Best regards,

**Comment by retorquere** [comment]
How would I detect that special handling was needed for this entry?

As an aside, what is the purpose of having plain-text on in this case? You're exporting unicode anyhow.

**Comment by TomBener** [comment]
Thank you for your prompt response. The special handling for Chinese quotation marks could potentially be triggered by detecting the presence of Chinese characters within the bibliographic entry. A heuristic approach could be checking if the title or other relevant fields contain a significant number of Unicode characters within ranges typically used for Chinese script (e.g., 4E00–9FFF for CJK Unified Ideographs).

It is useful to enable “Export unicode as plain-text latex commands” in most cases for LaTeX. The issue is that English and Chinese both use the same quotation marks (with same Unicode value). So for Chinese, the Chinese quotation mark should be written like `“你好”` instead of the general LaTeX-style. This issue may be a reference for you: https://github.com/CTeX-org/ctex-kit/issues/389

**Comment by retorquere** [comment]
But in `CXQBCHI2-refs-apse/6.7.165-7`, the title already has the quotes you want. And if you use a toolchain that requires support for unicode input anyhow, why use plain-text mode?

This sounds more like a task for postscripts.

**Comment by TomBener** [comment]
Because the plain-text mode not only includes the conversion of quotation marks, but also many other special symbols.

It would be nice if postscript could perform the action. Could you please provide some information? Thanks so much!

**Comment by retorquere** [comment]
> Because the plain-text mode not only includes the conversion of quotation marks, but also many other special symbols.

I understand that, but does that do anything useful? If your toolchain understands unicode, what unicode->tex conversion improves matters for you over just using unicode?

> It would be nice if postscript could perform the action. Could you please provide some information? Thanks so much!

I was thinking of this

```
if (Translator.BetterTeX) { // only for bibtex and biblatex
  // if more than 50% of the title is CJK
  if (zotero.title && (zotero.title.replace(/[^\u4E00-\u9FFF]/g, '').length / zotero.title.length) > 0.5) {
    // re-add the title field doing only minimal ascaping
    tex.add({ name: 'title', bibtex: '{' + zotero.title.replace(/([{}])/g, '\\$1') + '}' })
  }
}
```

but I see a few things that could go wrong with this now. I'll see what I can do.

**Comment by TomBener** [comment]
Thank you very much for considering this enhancement and proposing a solution with a postscript. The approach to detect CJK content in the title and apply minimal escaping seems promising for preserving Chinese quotation marks in the titles. I'm keen to assist in any way I can to ensure this feature supports accurate and typographically correct bibliographic entries for Chinese texts.

**Comment by retorquere** [comment]
This postscript will sometimes fail. I'm making a change to BBT to make it robust.

**Comment by retorquere** [comment]
You don't have `Export unicode as plain-text latex commands` on though, and then `CXQBCHI2-refs-apse/6.7.165-7` exports to

```
@book{tangqihua2010,
  title = {被“废除不平等条约”遮蔽的北洋修约史（1912–1928）},
  author = {唐启华},
  date = {2010-09-01},
  publisher = {社会科学文献出版社},
  location = {北京}
}
```

**Comment by retorquere** [comment]
With build 5922 you can do

```
if (Translator.BetterBibLaTeX) {
  // if more than 50% of the title is CJK
  if (zotero.title && (zotero.title.replace(/[^\u4E00-\u9FFF]/g, '').length / zotero.title.length) > 0.5) {
    // re-add the title field doing only minimal ascaping
    tex.add({ name: 'title', value: zotero.title, enc: 'minimal' })
  }
}
```

but I'm honestly puzzled by why you would want to. In `CXQBCHI2-refs-apse/6.7.165-7` you have `Export unicode as plain-text latex commands` off, and I still don't see what benefit turning it on has for your situation.

**Comment by TomBener** [comment]
@retorquere Thanks for your work.

Indeed, it is unnecessary to enable the option for the example Chinese entry above, but for English, this is necessary. For example, without toggling `Export unicode as plain-text latex commands`, the exported biblatex is:

```bibtex
@book{parasol2021,
  title = {{{AI Development}} and the ‘{{Fuzzy Logic}}’ of {{Chinese Cyber Security}} and {{Data Laws}}},
  author = {Parasol, Max},
  date = {2022},
  publisher = {Cambridge University Press},
  location = {Cambridge},
  doi = {10.1017/9781009064804}
}
```

After compiling in LaTeX with both English and Chinese, the entry would be converted the bibliography below. As the screenshot shows, the single quotes here was treated by LaTeX as the Chinese quotation mark and was unexpectedly wide.

![CleanShot 2024-03-13 at 20 00 21@2x](https://github.com/retorquere/zotero-better-bibtex/assets/49151155/ffe3831c-d03b-41db-bd31-86c35ace16af)

While if `Export unicode as plain-text latex commands` was enabled, the entry above would be exported as:

```bibtex
@book{parasol2021,
  title = {{{AI Development}} and the `{{Fuzzy Logic}}' of {{Chinese Cyber Security}} and {{Data Laws}}},
  author = {Parasol, Max},
  date = {2022},
  publisher = {Cambridge University Press},
  location = {Cambridge},
  doi = {10.1017/9781009064804}
}
```

And it would be compiled to the desired output, as the screenshot shows below.

![CleanShot 2024-03-13 at 20 08 06@2x](https://github.com/retorquere/zotero-better-bibtex/assets/49151155/15e98fe3-85dd-4219-b94a-896472f642ea)

Hope this explanation helps clarify the usage. Thanks again for your great work.

**Comment by retorquere** [comment]
It's all up to you of course, but why not change the quotes in the English entry?

**Comment by TomBener** [comment]
> It's all up to you of course, but why not change the quotes in the English entry?

I haven't thought like this before, but I write articles with Pandoc/Quarto, whose default language locale is always `en-US`, so the first idea came up was changing non-English quotes.

**Comment by retorquere** [comment]
regardless, if 5922 and the modified postscript do what you want, I'll roll that into a new release.

**Comment by TomBener** [comment]
Great. Thank you!

**Comment by TomBener** [comment]
> ```js
> if (Translator.BetterBibLaTeX) {
>   // if more than 50% of the title is CJK
>   if (zotero.title && (zotero.title.replace(/[^\u4E00-\u9FFF]/g, '').length / zotero.title.length) > 0.5) {
>     // re-add the title field doing only minimal ascaping
>     tex.add({ name: 'title', value: zotero.title, enc: 'biblatex' })
>   }
> }
> ```

I have tried this code with build 5922, but it didn't work. The debug ID is `KWNYX57V-refs-apse/6.7.165.2810.5922-7`. However, this code works:

```js
if (Translator.BetterTeX) { // only for bibtex and biblatex
  // if more than 50% of the title is CJK
  if (zotero.title && (zotero.title.replace(/[^\u4E00-\u9FFF]/g, '').length / zotero.title.length) > 0.5) {
    // re-add the title field doing only minimal ascaping
    tex.add({ name: 'title', bibtex: '{' + zotero.title.replace(/([{}])/g, '\\$1') + '}' })
  }
}
```

**Comment by retorquere** [comment]
My bad -- that should have been

```
if (Translator.BetterBibLaTeX) {
  // if more than 50% of the title is CJK
  if (zotero.title && (zotero.title.replace(/[^\u4E00-\u9FFF]/g, '').length / zotero.title.length) > 0.5) {
    // re-add the title field doing only minimal ascaping
    tex.add({ name: 'title', value: zotero.title, enc: 'minimal' })
  }
}
```

**Comment by TomBener** [comment]
@retorquere Great, it works. Thank you~

**Comment by TomBener** [comment]
I found an issue with the escaped punctuations for Chinese titles.

With the current escaping mechanism for Chinese titles, the en-dash is not escaped. For example,

```bib
@book{duzanqi2003,
  author = {{杜赞奇}},
  translator = {{王福明}},
  date = {2003-08},
  publisher = {江苏人民出版社},
  location = {南京},
  title = {文化、权力与国家——1900–1942年的华北农村}
}
```

However, this Unicode `–` in LaTeX is interpreted not perfectly, as the screenshot below shows, `1900–1942` looks not very proper.

![CleanShot 2024-03-26 at 15 57 15@2x](https://github.com/retorquere/zotero-better-bibtex/assets/49151155/324c801b-63e3-43ba-babd-ad85663fe52e)

In comparison, if the en-dash is represented with two hyphens in the `.bib` file, it would look much better, as the screenshot below shows.

```bib
@book{duzanqi2003,
  author = {{杜赞奇}},
  translator = {{王福明}},
  date = {2003-08},
  publisher = {江苏人民出版社},
  location = {南京},
  title = {文化、权力与国家——1900--1942年的华北农村}
}
```

![CleanShot 2024-03-26 at 15 59 27@2x](https://github.com/retorquere/zotero-better-bibtex/assets/49151155/50c17614-4d73-4390-9703-f32699597bd7)

As a result, I propose that the `minimal` option can only process quotation marks, while other punctuations, such as en-dash, em-dash should follow the general LaTeX syntax. Thanks for your consideration.

**Comment by retorquere** [comment]
I'm not going to change `minimal`. `minimal` is just that -- it escapes only those characters that would otherwise give document compilation errors or that have a different meaning in LaTeX (like `<`), and nothing else. You can add the en-dash to the [ascii](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html#ascii) preference to have it output double-hyphen.

**Comment by retorquere** [comment]
If the unicode en-dash is not interpreted properly by biblatex, you should open an issue on https://github.com/plk/biblatex

**Comment by TomBener** [comment]
I have tried changing the font selection for the text. With `Palatino` for ASCII and `Noto Serif CJK SC` for CJK fonts, the display of the en-dash looks perfect, regardless of whether the Unicode en dash `–` or two consecutive hyphens `--` are used.

![CleanShot 2024-03-26 at 20 19 46@2x](https://github.com/retorquere/zotero-better-bibtex/assets/49151155/faf9c931-9141-4972-9822-307a01256e37)

I think there is no issue with the `biblatex` package, as the symbol in PDF is indeed the en-dash. And the [ascii](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html#ascii) preference doesn’t work in my case as I have turned on `Export unicode as plain-text latex commands`.

If you plan to change `minimal` option, I think Pandoc’s smart [extension](https://pandoc.org/MANUAL.html#extension-smart) could be a reference:

> Interpret straight quotes as curly quotes, `---` as em-dashes, `--` as en-dashes, and `...` as ellipses.
> In LaTeX, `smart` means to use the standard TeX ligatures for quotation marks (` `` ` and `''` for double quotes, `` ` ``and `'` for single quotes) and dashes (`--` for en-dash and `---` for em-dash).

**Comment by TomBener** [comment]
I’d like to know are there any updates on how to export the en-dash to the double-hyphen with the ascii preference?

**Comment by retorquere** [comment]
> I’d like to know are there any updates on how to export the en-dash to the double-hyphen with the ascii preference?

A build will drop here when I have that ready. 

> By the way, how to disable the escaping for other fields, such as `author`, `editor` and `journaltitle` in `Better BibLaTeX`?

Disabling escaping is an all-or-nothing affair. Of you turn it on, all fields get it.

**Comment by TomBener** [comment]
Thanks. I mean by scripting to do this. For example, this postscript disables escaping for the `title` field:

```js
if (Translator.BetterBibLaTeX) {
  // if more than 50% of the title is CJK
  if (zotero.title && (zotero.title.replace(/[^\u4E00-\u9FFF]/g, '').length / zotero.title.length) > 0.5) {
    // re-add the title field doing only minimal ascaping
    tex.add({ name: 'title', value: zotero.title, enc: 'minimal' })
  }
}
```

I'd like to also apply the same rule to `author`, `editor` and `journaltitle`.

**Comment by retorquere** [comment]
I think it'd be easier to just set exports to plain-text, and the [install](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html#charmap) the attached [charmap.csv](https://github.com/retorquere/zotero-better-bibtex/files/14787006/charmap.csv)

**Comment by retorquere** [comment]
> I added the following charmap to replace `$\cdot$` with `·`.

That will work but then why is `…` in the input if you don't want it?

> to the double-hyphen -- for Chinese titles:

If you want that everywhere, not just titles, you can just add

`–,--,`

to `charmap.csv` without the need for a postscript.

**Comment by retorquere** [comment]
Oh cdots, sorry

**Comment by TomBener** [comment]
> If you want that everywhere, not just titles, you can just add
> 
> `–,--,`
> 
> to `charmap.csv` without the need for a postscript.

It seems this didn't work as I have enabled the `minimal` escaping option for Chinese titles in postscript. Is it correct that the postscript is the last one to be executed when exporting?

**Comment by retorquere** [comment]
Yes. If you get me a new debug log I can have a look

**Comment by retorquere** [comment]
Oh in the postscript. That's not fixed yet.

**Comment by retorquere** [comment]
As I said before, if a build drops here there's something to test. Until that time, postscripts won't work in this way.

**Comment by retorquere** [comment]
The build that dropped will work

**Comment by TomBener** [comment]
@retorquere Huge thanks, it works!
