### ISSUE TITLE
Add possibility to export only entries with specific Tags

### ISSUE THREAD

**Issue by q-wertz** [retorquere/zotero-better-bibtex#2811]
### Debug log ID

W33PEQL5-euc/6.7.165-6

### What happened?

As far as I see, currently it is only possible to export (using `Better BibLaTeX` or `Better BibTex`) the whole library.

As my library is quite large it would be nice for writing e.g. papers to only export entries with specific Tags and/or from specific Collections. So far I was not able to find this functionality.

Kind of related to https://github.com/retorquere/zotero-better-bibtex/issues/1826 and the solution suggested in https://github.com/retorquere/zotero-better-bibtex/issues/1826#issuecomment-915029083

EDIT: I found out that I can select the Tag, then mark entries and export them with right click. But as far as I understand I cannot keep the file updated with new entries that are added to the Tag.

**Comment by retorquere** [comment]
You can just select your tag, then select all shown items, and export.

**Comment by retorquere** [comment]
For collections, just right click the collection and export. Maybe I'm not understanding your question, but these things are standard Zotero functionality.

**Comment by retorquere** [comment]
Unfortunately the way zotero works it's not possible to know that the items were exported because they were selected through a tag. Zotero exposes the fact that a collection or a library was exported, which is why I can set up auto-exports for them.

**Comment by q-wertz** [comment]
Ok. Thanks for the information about the collections.

I thought it might be possible to have a extra setting in the export functionality of BetterBibtex to only export and keep updated certain Tags.

**Comment by retorquere** [comment]
That's technically possible, but I'd have to re-implement the export GUI bits. I'd rather have that Zotero provides hints on what they're exporting so that I can hook auto-export into that.

**Comment by retorquere** [comment]
I've tested a bit, and I can't reliably detect whether an item was exported because the user selected a tag or not. When Zotero adds hints in the export, I can act on this, but without this, I can't really take this on.
