### ISSUE TITLE
zotero select link + bbt citation key

### ISSUE THREAD

**Issue by jasonandjack1997** [retorquere/zotero-better-bibtex#2813]
### Debug log ID

HP784ZHC-refs-apse/6.7.165-7

### What happened?

I would like to have zotero select link  followed by better bibtex citation key to make it clickale as well as readable. 

Thanks for this great plugin. 
I would like to know what is the best way to generate a zotero select link so I can get to this item by clicking in other applications. The zotero select link is not readable, yet it allows me to have additional parameters or suffix so it would be great to have it readable by adding a bbt citation key to show the journal name, year, author etc. Also it can be easily converted to real citations in word with minimal efforts. A zotero select uri will double secure locating the item if the bbt citation key changed. 

I tried the citation key configurations but as documented   the 'zotero' field is not the zotero item key.

Or if I use quick copy to get the zotero select link, what is the most convient way to get the bbt ciation key   as only one option for quick copy.

**Comment by retorquere** [comment]
It's one of the quick-copy options:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/132108/c13baaa3-5db5-465c-b68b-f3b5e998afaf)

**Comment by retorquere** [comment]
Do you have an example of how that would look?

**Comment by jasonandjack1997** [comment]
Thanks for the reply. For citations it could be like:zotero://select/zoterokey/journalnameyearauthorname, or something similiar.Using this link I can go to the zotero item, besides that I can read the last part to know or recall the key information of this citation. Finally I can use a regex to delete the zotero select part and only leave the bbt citation keys thus to be converted to live citations in word or other documents. I personally think it would be very useful.I think the only thing I need is a "zotero select key" in the quick copy function, as the 'zotero://select'part is a fixed string. If a zotero select key is provided along side author and other fields, any composition can be flexible.All the best,Steve
        
            
        
    
         
        
            
                        
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Emiliano ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/14/2024 23:00
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [retorquere/zotero-better-bibtex] zotero select link + bbt citation key (Issue #2813)
        
      
    
  

Do you have an example of how that would look?

**Comment by retorquere** [comment]
There was a bug in the preferences screen. If you update, you'll see that you can choose to have the citation key in the select-link quick-copy export.

**Comment by retorquere** [comment]
Does that address your request?

**Comment by jasonandjack1997** [comment]
Sorry but I didn't figure out how to do it. I have the 15 March 2024 version. To be simple I would like to have a sort of "a combination of zotero select link and bbt citation key(authoryearjurnal)". All the best,
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Emiliano ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/18/2024 21:19
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [retorquere/zotero-better-bibtex] zotero select link + bbt citation key (Issue #2813)
        
      
    
  

Does that address your request?

**Comment by retorquere** [comment]
You're on 6.7.165. Please upgrade. After that, you can go to BBT preferences - Export - Quick Copy - Select link - citation key.

**Comment by jasonandjack1997** [comment]
Wow many thanks thanks so much for this upgrade! I didn't find this upgrade nor did I expected that it could be so fast. Thanks so much. This brings me to the zotero item even without the zotero selection key part!I really appreciate your work and effort!All the best,
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Emiliano ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/20/2024 15:31
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [retorquere/zotero-better-bibtex] zotero select link + bbt citation key (Issue #2813)
        
      
    
  

You're on 6.7.165. Please upgrade. After that, you can go to BBT preferences - Export - Quick Copy - Select link - citation key.

**Comment by retorquere** [comment]
Zotero should update to newer versions automatically.
