### ISSUE TITLE
Angle brackets importing incorrectly from UTF-8 .bib file when BBT is enabled

### ISSUE THREAD

**Issue by jcblum** [retorquere/zotero-better-bibtex#2814]
### Debug log ID

Y9WEUTMI-refs-euc/6.7.165-6

### What happened?

When BBT is enabled, importing from a UTF-8 encoded `.bib` file results in left and right angle brackets `<` (U+003C) and `>` (U+003E) turning into ¡ (U+00A1) and ¿ (U+00BF) characters. If I import from the same file with BBT disabled, the brackets import correctly.

As far as I can tell, the problem seems to be limited to `<` and `>`. I don't have a lot of other "special" characters in the references I am importing, but I added some accented characters and curly quotes to my test file, and they were unharmed by importing with BBT enabled.

Here's the test file that I used to import the reference selected in the debug log:
(I had to change the file extension to `.txt` for GitHub to accept it, but made no other edits).
[import_encoding_test.txt](https://github.com/retorquere/zotero-better-bibtex/files/14595164/import_encoding_test.txt)

Thanks for all the hard work you put into developing Better BibTeX (one of my most relied-upon plugins!), and apologies in advance if this turns out to be some mistake on my part that I've overlooked 😅.

**Comment by retorquere** [comment]
I'm afraid the stock bibtex importer has it wrong. Try compiling this:

```
\documentclass{article}

\usepackage[backend=biber, style=alphabetic]{biblatex}

\begin{filecontents}{\jobname.bib}
@Article{WOS:000290839600002,
  AUTHOR = {Willis, Jessica E. and Stewart-Clark, Sarah and Greenwood, Spencer J. and Davidson, Jeff and Quijon, Pedro},
  JOURNAL = {Aquatic Invasions},
  MONTH = {MAR},
  NUMBER = {1},
  PAGES = {7--16},
  TITLE = {A PCR-based assay to facilitate early detection of <i>Diplosoma listerianum</i> in Atlantic Canada},
  VOLUME = {6},
  YEAR = {2011},
  ABSTRACT = {The reçent detectíon of the invasive colonial tünicate <i>Diplosoma listerianum</i> in Havre-Aubert, Magdalen Islands (Québec, Canada) in 2008, “prompted” the ‘development’ of a molecular assay as a method to detect and monitor for the potential invasion of this species in Prince Edward Island.},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{WOS:000290839600002}
\printbibliography
\end{document}
```

**Comment by retorquere** [comment]
If you want italicized text, latex offers `\emph{Diplosoma listerianum}`

**Comment by retorquere** [comment]
> I realize that BibTeX is not an ideal data interchange format

It can be a pretty good data exchange format, it's just that so many institutions put out crap software to put out stuff that vaguely resembles bibtex 😉
