### ISSUE TITLE
Better BibTeX export from Zotero missing Extra fields, e.g. "issued"

### ISSUE THREAD

**Issue by KAKDH** [retorquere/zotero-better-bibtex#2816]
### Debug log ID

MGD6YVIY-refs-euc/6.7.166-6

### What happened?

Hi!

Can anyone advise how to fix an issue with BetterBibTeX export of my Zotero bibliography?

I store publication dates which are ranges in the Extra field as "issued: 2000/2001". In the past I didn't have issues with the export, but now the "Issued" field is missing from my exported bib file.

I use Better BibTeX version 6.7.166 and Zotero 6.0.35 on MAC Sonoma 14.3.1. 

Thanks in advance!
K.

**Comment by retorquere** [comment]
I'm not sure this was ever different; I've looked through the history of the code and I don't see indications I've previously exported `issued`. It's also not in the biblatex manual, which is what I usually go by, although I'm about to go through `biblatex-apa` and `biblatex-chicago` to see if they say different.

In `MGD6YVIY-refs-euc/6.7.166-6` you have an item with a date field of `1829–1830` and indeed an `Issued: 1829/1830` in the extra field, which means the same, and has the same value, so I'm not sure what to make of it. If you want to have `issued` show up in BBT output, you could put `tex.issued: 1829/1830` in Extra.

**Comment by KAKDH** [comment]
Thanks for your answer. 

While I cannot find any old export with "issued" included, in one of my exports from 2021 the entry appears the following way:

        @book{rafn1829,
          address = {Kaupmannah{\"o}fn},
          title = {Fornaldars{\"o}gur {{Nor{\dh}rlanda}}},
          timestamp = {2018-01-02T11:48:36Z},
          author = {Rafn, Carl Christian},
          year = {1829-1830}
        }

While now it appears like this:
      @book{rafn1829,
        title = {{Fornaldar s{\"o}gur Nordrlanda eptir g{\"o}mlum handritum}},
        editor = {Rafn, Carl Christian},
        year = {1829},
        publisher = {Popp},
        address = {Copenhagen},
        langid = {danish},
      }

So it looks like back in the day the conversion didn't have problems with ranges, while now it does. 

I checked and adding tex.issued to Extra solves the problem, but is this really the only solution? I have hundreds of entries in my bibliography so I'd rather not check all of them manually.

**Comment by retorquere** [comment]
Sorry, I had missed you were exporting for bibtex, I did my tests with biblatex. Bibtex doesn't really do date ranges, but build 5937 should work better for you.

**Comment by KAKDH** [comment]
Thank you so much, it works perfectly indeed. Now I get both, ranges in "isssued" and "year". Appreciate the quick fix!
K.

**Comment by KAKDH** [comment]
OK I was to quick celebration. Actually, it turns out that now it converts all ranges (both in year & issued) into the format with a shlash / instad of a dahs –, so 1900–1901 becomes 1900/1901.

I believe that I encoded dates with "/" in "issued" because this was recommend for some MSWord plug-in, while I kept "—" in the date field. Is there any way of exporting just the date field as encoded and ignore the issued (or covert it also into the format with dash)?   

Thanks!

**Comment by retorquere** [comment]
BBT ignores the `issued` because in Zotero, `Issued` is just a type-dependent display label for `Date`, and since you have the `Date` field filled, that takes precedence. I'm not sure what the `Issued` line in the extra field can do in practice in the sample you offered in Zotero.

WRT your question, what I can do is add a preference that allows you to disable date parsing/date normalization for bibtex exports, but that means whatever is in the `Date` gets dumped into the `year` field if I can't parse it to a simple date (like in this case). 

For anything else we're in [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/index.html) territory. There you can do pretty much whatever you want.

**Comment by retorquere** [comment]
BTW are you sure you must be tied to bibtex? biblatex solves a lot of these problems.

**Comment by KAKDH** [comment]
Thanks, but when I export with Better BibLaTex I get the same issue, output looks like this, despite my Zotero Date field being "1829–1830": 

        @mvbook{rafn1829,
          title = {Fornaldar sögur Nordrlanda eptir gömlum handritum},
          editor = {Rafn, Carl Christian},
          date = {1829/1830},
          publisher = {Popp},
          location = {Copenhagen},
          issued = {1829/1830},
          langid = {danish},
          volumes = {3}
        }

**Comment by retorquere** [comment]
Biblatex supports EDTF dates, and that's what EDTF date ranges look like. But before the fix, BBT would only export the "from" date from the date range.

**Comment by KAKDH** [comment]
Well, this is certainly not how the date ranges are represented in humanities research. 
Could you please advise whether there is any way for me to reproduce the export as it was done in 2021 example, quoted above, where the range is a range with dahs, not slash? Cheers!

**Comment by KAKDH** [comment]
Re you response: 

> BBT ignores the `Issued` in extra because in Zotero, `Issued` is just a type-dependent display label for `Date`, and since you have the `Date` field filled, that takes precedence. I'm not sure what the `Issued` line in the extra field can do in practice in the sample you offered in Zotero.


My export from Zotero using Better BibTeX contains the "issued" field and looks like this: 


      @book{rafn1829,
        title = {{Fornaldar s{\"o}gur Nordrlanda eptir g{\"o}mlum handritum}},
        editor = {Rafn, Carl Christian},
        year = {1829/1830},
        publisher = {Popp},
        address = {Copenhagen},
        issued = {1829/1830},
        langid = {danish}
      }

**Comment by retorquere** [comment]
> Well, this is certainly not how the date ranges are represented in humanities research. 

I'm not contesting that, but with biblatex the citation processor will take that EDTF date range and present it as the style demands. It's not just rendered as it sits in the biblatex file. That's what I mean by "biblatex has EDTF support'. 

> Could you please advise whether there is any way for me to reproduce the export as it was done in 2021 example, quoted above, where the range is a range with dahs, not slash? Cheers!  

I'll put together a postscript, but I'd recommend testing what the results look like after rendering with biblatex. Bibtex used to make these input tweaks necessary, and biblatex was created to address a lot of those.

**Comment by KAKDH** [comment]
That would be fantastic. Thank you so much for your help and sorry for the inconvenience!

**Comment by retorquere** [comment]
> My export from Zotero using Better BibTeX contains the "issued" field and looks like this: 

That's not right. That's from the unchanged entry from the debug log? Or does that have `tex.issued` in the extra field?

**Comment by retorquere** [comment]
What style in particular is the journal you're prepping for use?

**Comment by retorquere** [comment]
> I'll put together a postscript, but I'd recommend testing what the results look like after rendering with biblatex. Bibtex used to make these input tweaks necessary, and biblatex was created to address a lot of those.

This for example:

```
\documentclass[a4paper]{article}
\usepackage[T1]{fontenc}% see: http://tex.stackexchange.com/q/71517/8528
\usepackage[utf8]{inputenc}
\usepackage[british]{babel}
\usepackage{csquotes}
\usepackage[style=apa, backend=biber]{biblatex}
\DeclareLanguageMapping{british}{british-apa}

\begin{filecontents}{\jobname.bib}
@mvbook{rafn1829,
      title = {Fornaldar sögur Nordrlanda eptir gömlum handritum},
      editor = {Rafn, Carl Christian},
      date = {1829/1830},
      publisher = {Popp},
      location = {Copenhagen},
      langid = {danish},
      volumes = {3}
    }
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{rafn1829}

\printbibliography
\end{document}
```

renders as

> Rafn, C. C. (Ed.). (1829–1830). Fornaldar sögur Nordrlanda eptir gömlum handritum. Popp.

**Comment by retorquere** [comment]
> My export from Zotero using Better BibTeX contains the "issued" field and looks like this:
> 
> ```
>   @book{rafn1829,
>     title = {{Fornaldar s{\"o}gur Nordrlanda eptir g{\"o}mlum handritum}},
>     editor = {Rafn, Carl Christian},
>     year = {1829/1830},
>     publisher = {Popp},
>     address = {Copenhagen},
>     issued = {1829/1830},
>     langid = {danish}
>   }
> ```

I cannot reproduce this without adding `tex.issued:` in the extra field. If you add `tex.` (or `bibtex.`, or `biblatex.`) in front of a field you're telling BBT that you just want that field added. BBT won't second-guess you on that.

**Comment by KAKDH** [comment]
> That's not right. That's from the unchanged entry from the debug log? Or does that have `tex.issued` in the extra field?

Right, it does have tex.issued. Sorry.

**Comment by retorquere** [comment]
This postscript will give you the options you described:

```
if (Translator.BetterBibTeX) {
  if (zotero.date) tex.add({ name: 'year', value: zotero.date }) // if you just want what is in the date field without any processing

  if (zotero.date) {
    if (tex.date.type == 'interval') tex.add({ name: 'year', value: `${tex.date.from.year}–${tex.date.to.year}` }) 
  }
}
```

you only need one of the inner `if` parts, depending on whether you want pass-through or specific handling of date ranges, which EDTF calls intervals. It's not a requirement to get familiar with javascript -- I generally write these on request.

But as you can see in the biblatex sample above, the `/` is just a technical aspect of how biblatex stores dates, how it is rendered is determined by the style, and different styles will make different choices on how to render date ranges. That's what styles are for.

**Comment by KAKDH** [comment]
Thanks a lot for your patience.  It looks like I got it to work by using BibLaTeX export and author-tile style, but now I have another issue that Better BibLaTex export contains URLs and I don't want URLs in my bibliography. In Better BibTex there was an option of ignoring them, while here I can only choose whether to prioritise DOIs or URLs. 

Gosh, one thing gets fixed and another gets broken. 

Here the defs of my bibliography:         
        \usepackage[backend=biber, style=authortitle, sorting=nyt, natbib=true]{biblatex}
        \addbibresource{MyLibrary.bib}
        \AtEveryBibitem{\clearlist{language}}
        \AtEveryBibitem{%
	        \ifentrytype{online}
	        {}
	        {\clearfield{urlyear}\clearfield{urlmonth}\clearfield{urlday}}}
        \AtEveryBibitem{%
	        \clearlist{publisher}%
	        \clearfield{pagetotal}%
}

**Comment by KAKDH** [comment]
> This postscript will give you the options you described:
> 
> ```
> if (Translator.BetterBibTeX) {
>   if (zotero.date) tex.add({ name: 'year', value: zotero.date }) // if you just want what is in the date field without any processing
> 
>   if (zotero.date) {
>     if (tex.date.type == 'interval') tex.add({ name: 'year', value: `${tex.date.from.year}–${tex.date.to.year}` }) 
>   }
> }
> ```
> 
> you only need one of the inner `if` parts, depending on whether you want pass-through or specific handling of date ranges, which EDTF calls intervals. It's not a requirement to get familiar with javascript -- I generally write these on request.
> 
> But as you can see in the biblatex sample above, the `/` is just a technical aspect of how biblatex stores dates, how it is rendered is determined by the style, and different styles will make different choices on how to render date ranges. That's what styles are for.

Cool, thank you so much, let me test it!

**Comment by retorquere** [comment]
> Thanks a lot for your patience. It looks like I got it to work by using BibLaTeX export and author-tile style, but now I have another issue that Better BibLaTex export contains URLs and I don't want URLs in my bibliography. In Better BibTex there was an option of ignoring them, while here I can only choose whether to prioritise DOIs or URLs.

They're separate choices, you can remove the URL from exports [here](https://retorque.re/zotero-better-bibtex/installation/preferences/export/index.html#fields-to-omit-from-export-comma-separated).

but since you're already using `AtEveryBibitem`, you can just add

```
\clearfield{url}
```

**Comment by retorquere** [comment]
Oh and

```
\usepackage[backend=biber, style=authortitle, sorting=nyt, natbib=true,url=false]{biblatex}
```

should work too.

**Comment by KAKDH** [comment]
The postscript fixed all my issues, thank you very much! I really appreciate it.

**Comment by retorquere** [comment]
Not a problem. Still recommend biblatex, but I understand just wanting to get things done.
