### ISSUE TITLE
[Feature] Add typst CAYW citations

### ISSUE THREAD

**Issue by Kasi07** [retorquere/zotero-better-bibtex#2817]
### Debug log ID

TWJFUAK7-euc/6.7.169-7

### What happened?

I would like to insert the citations into my typst document and thus would love to see typst support for the CAYW feature.

I noticed the pandoc uses the `@citation-key` syntax which also works with typst most of the time. But I would like to see the `#cite(<citation-key>)` syntax as this is much more versatile.

Also [here](https://typst.app/docs/reference/model/cite/) is the link to the typst citation documentation.

**Comment by retorquere** [comment]
`typst` doesn't do multi-cite then?

**Comment by Kasi07** [comment]
This is almost working. But the citation key has to be surrounded by '<' and '>'.

As the `<label>` syntax only supports certain characters ([see here](https://typst.app/docs/reference/foundations/label#syntax)) maybe we could insert a check using a regex (In this case `/^[a-zA-Z0-9_\-:.]+$/` if I stand correctly) to determine when to use the arguably uglier `label("example")` syntax.

**Comment by retorquere** [comment]
Why the `\n`? That would make them non-adjacent.

**Comment by Kasi07** [comment]
I took that from your earlier [implementation](https://github.com/retorquere/zotero-better-bibtex/blob/a5104f171f9ab6a1480fefcfdf8fc71e20dead0d/content/cayw/formatter.ts#L86).
Also in typst new lines are generally ignored and this would make it look cleaner.
I just checked and putting them in separate lines works just fine.

**Comment by retorquere** [comment]
> I took that from your earlier implementation.

Yeah my bad. New build incoming.

**Comment by retorquere** [comment]
No locators or anything?

**Comment by retorquere** [comment]
`supplement` and `form` could be filled, we have that info

**Comment by Kasi07** [comment]
> No locators or anything?

What do you mean by locators?

> supplement and form could be filled, we have that info

The supplement could be useful.
As the form depends on the placement in the text I am unsure how we would know about it?

**Comment by retorquere** [comment]
Does typst accept `#cite(<arrgh>,,"year")` (or how else would I pass `none` for supplement)?

> As the form depends on the placement in the text I am unsure how we would know about it?

You can suppress author in the cite, which would mean `"year"` for `form`

**Comment by Kasi07** [comment]
You can just use the key in typst like: `#cite(<arrgh, form: "year")`

**Comment by Kasi07** [comment]
This is working great, thank a lot!
