### ISSUE TITLE
Support for extra field with manually edited .bib

### ISSUE THREAD

**Issue by paolieri** [retorquere/zotero-better-bibtex#2825]
### Debug log ID

5E9RPDTE-refs-euc/6.7.173-7

### What happened?

Sometimes, I need to make manual changes to the .bib files. I'd like to save these manually edited .bib in a special field; if the field is non-empty, I'd like Better BibTeX to return that field instead of generating an entry from the metadata. Is it already possible to do this with scripting?

**Comment by retorquere** [comment]
What had you wanted to export for `5E9RPDTE-refs-euc/6.7.173-7`?

**Comment by paolieri** [comment]
Scripts allow .bib fields during the reference generation, right?
I'd like to modify the entire final .bib string to replace it with an `extra` variable (if it has been set). 
The extra variable is my manually edited bibtex entry.

I'm not sure what this variable should be called, so `5E9RPDTE-refs-euc/6.7.173-7` didn't include it.

**Comment by retorquere** [comment]
It'd be a lot easier if you could post what you want the final output to look like.

**Comment by paolieri** [comment]
Apologies! I prepared another debug entry: `DI42QWGJ-refs-euc/6.7.173-7`

I have an extra field called `bib`:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/1083642/489c8845-53db-4eaf-ad0b-9ebcfb5a06f3)

I would like the output of `Export Item...` > `Format: Better BibTeX` to be the value of this field, i.e., 

```
@inproceedings{DBLP:conf/nips/VaswaniSPUJGKP17,
  author       = {Ashish Vaswani and
                  Noam Shazeer and
                  Niki Parmar and
                  Jakob Uszkoreit and
                  Llion Jones and
                  Aidan N. Gomez and
                  Lukasz Kaiser and
                  Illia Polosukhin},
  editor       = {Isabelle Guyon and
                  Ulrike von Luxburg and
                  Samy Bengio and
                  Hanna M. Wallach and
                  Rob Fergus and
                  S. V. N. Vishwanathan and
                  Roman Garnett},
  title        = {Attention is All you Need},
  booktitle    = {NIPS 2017},
  pages        = {5998--6008},
  year         = {2017}
}
```

As an alternative to using a field, a solution could be to have a .bib attachment:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/1083642/3f7900a2-ecf3-4dc0-9c19-8cf0e44556d3)

The generated output would be the content of the attachment (if present).

**Comment by retorquere** [comment]
There are ways to achieve this output, but not by having BBT export the `extra` field or an attachment in this way. If you just want the output, you could either:

**using standard BBT export:**

* set type to `Conference paper`
* change the title to sentence-case, optionally protect `is` and `you` (`Attention <span class="nocase">is</span> all <span class="nocase">you</span> need`)
* add the editors
* set "Date" to `2017`
* set "Pages" to `5998--6008` 
* set "Proceedings title" to `NIPS 2017`
* add `Citation Key: DBLP:conf/nips/VaswaniSPUJGKP17` to the `extra` field

and export using Better BibTeX. This entry will work in Word etc too.

**manual control:**

you can control everything manually, I really don't understand how that would be beneficial in your case (also note that `Łukasz` is replaved by `Lukasz` in your sample), but here goes: add the following to the `extra` field :

```
Citation Key: DBLP:conf/nips/VaswaniSPUJGKP17
tex.author: Ashish Vaswani and Noam Shazeer and Niki Parmar and Jakob Uszkoreit and Llion Jones and Aidan N. Gomez and Lukasz Kaiser and Illia Polosukhin
tex.editor: Isabelle Guyon and Ulrike von Luxburg and Samy Bengio and Hanna M. Wallach and Rob Fergus and S. V. N. Vishwanathan and Roman Garnett
tex.title: Attention is All you Need,
tex.booktitle: NIPS 2017,
tex.pages: 5998--6008
tex.year: 2017
```

or any combination of these methods.

**Comment by paolieri** [comment]
Thank you! 

I was suggesting a single input (either in the metadata or as an attachment) because I already have the final .bib that I would like to use. With either standard BBT export or "manual control", I would have to edit multiple fields to match the .bib that I have.

As a workaround, I've found that I can:
- Add the .bib as an attachment
- Export the items for my bibliography with `Export Files` selected
- Collect the attached .bib from the export directory with 
```
find 'Exported Items/files' -name '*.bib' -exec cat {} \; | pbcopy
```
