### ISSUE TITLE
Pandoc: error reading bibliography file, unexpected J

### ISSUE THREAD

**Issue by samprovost** [retorquere/zotero-better-bibtex#2826]
### Debug log ID

I3J5I8HT-refs-euc/6.7.173-6

### What happened?

When using pandoc to create a docx file from a note in Obsidian I get the following error:

Error reading bibliography file /Users/samprovost/Documents/Obsidian Vaults/Obsidian Vault/My Library.bib:
(line 2849, column 13):
unexpected 'J'

The bibliography entry that pandoc is having trouble with is:

```
@article{de Jong2012,
  title = {Perceived Green Qualities Were Associated with Neighborhood Satisfaction, Physical Activity, and General Health: Results from a Cross-Sectional Study in Suburban and Rural {{Scania}}, Southern {{Sweden}}},
  author = {family=Jong, given=K., prefix=de, useprefix=true and Albin, M. and Skärbäck, E. and Grahn, P. and Björk, J.},
  date = {2012},
  journaltitle = {Health Place},
  volume = {18},
  doi = {10.1016/j.healthplace.2012.07.001}
```
It appears the issue is with the author name "de Jong". The J in Jong is (line 2849, column 13).

I am using pandoc version -3.1.12.3-arm64-macOS on an Apple Silicon M1 Max.

Thanks
Sam

**Comment by retorquere** [comment]
The entry as pasted above is incomplete, so that could explain the problem, there's also a space in your citation key, which isn't valid. Other than that I would guess that Pandoc doesn't understand extended name mode, because this renders without issue:

```
\documentclass[a4paper]{article}
\usepackage[T1]{fontenc}% see: http://tex.stackexchange.com/q/71517/8528
\usepackage[utf8]{inputenc}
\usepackage[british]{babel}
\usepackage{csquotes}
\usepackage[style=apa, backend=biber]{biblatex}
\usepackage{hyperref}

\DeclareLanguageMapping{british}{british-apa}

\begin{filecontents}{\jobname.bib}
@article{deJong2012,
  title = {Perceived Green Qualities Were Associated with Neighborhood Satisfaction, Physical Activity, and General Health: Results from a Cross-Sectional Study in Suburban and Rural {{Scania}}, Southern {{Sweden}}},
  author = {family=Jong, given=K., prefix=de, useprefix=true and Albin, M. and Skärbäck, E. and Grahn, P. and Björk, J.},
  date = {2012},
  journaltitle = {Health Place},
  volume = {18},
  doi = {10.1016/j.healthplace.2012.07.001}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography
\end{document}
```

but you can turn off extended name format for biblatex in the preferences.

**Comment by retorquere** [comment]
If I put this into `bib.bib`:

```
@article{deJong2012,
  title = {Perceived Green Qualities Were Associated with Neighborhood Satisfaction, Physical Activity, and General Health: Results from a Cross-Sectional Study in Suburban and Rural {{Scania}}, Southern {{Sweden}}},
  author = {family=Jong, given=K., prefix=de, useprefix=true and Albin, M. and Skärbäck, E. and Grahn, P. and Björk, J.},
  date = {2012},
  journaltitle = {Health Place},
  volume = {18},
  doi = {10.1016/j.healthplace.2012.07.001}
}
```

and run

```
pandoc bib.bib -t csljson -o bib.json
```

pandoc converts the entry to CSL-JSON successfully.

Ah, I get it; if I enter the input you originally posted (with the missing end brace and the space in the citation key), pandoc reports:

```
Error at "bib.bib" (line 1, column 13):
unexpected 'J'
@article{de Jong2012,
```

so it's the space in the key. pandoc is quite precise in this case where the error is. BBT doesn't generate keys with spaces, but it will blindly accept whatever key you put into the `extra` field. BBT can put keys in the extra field on your behalf, but when doing that, it cannot generate keys with spaces, so this key was put there manually, or it was put there by BBT and then edited.

**Comment by samprovost** [comment]
Thanks for your response. I will make the change and try to run pandoc again today.

Sam
________________________________

**Comment by retorquere** [comment]
Is the issue resolved?

**Comment by samprovost** [comment]
Hello,

The issue is resolved. It looks like BBT added spaces to the citekey of some of the documents in my Zotero library with extended names.

I didn't edit any of them or add spaces in the extra field so I'm not sure how they ended up there if, as you say, BBT can't add keys.

Anyway I just had to run the pandoc script a few times to find the entries with spaces and remove them in Zotero.

Thanks for your help

Sam

**Comment by retorquere** [comment]
> Hello,
> 
> The issue is resolved. It looks like BBT added spaces to the citekey of some of the documents in my Zotero library with extended names.

BBT *always* removes spaces in the last step of key generation. The name (title?) cannot affect that. If you can replicate bbt generating spaces I'd like to know.

**Comment by samprovost** [comment]
Thanks Emiliano,

I don’t think I can replicate it because I don't know at which point the citation keys were created or altered.

Maybe it was an interaction with another app that added the spaces into the three citations. The issue was across three citations with lead authors with extended names such as de Jong or van Dillen. Not sure if that helps at all.

Thanks for your assistance and guidance,

Sam


On 10 Apr 2024, at 2:36 PM, Emiliano Heyns ***@***.***> wrote:

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


Hello,

The issue is resolved. It looks like BBT added spaces to the citekey of some of the documents in my Zotero library with extended names.

BBT always removes spaces in the last step of key generation. The name (title?) cannot affect that. If you can replicate bbt generating spaces I'd like to know.

**Comment by retorquere** [comment]
The key generation has no relation to the extended name formats - both take the zotero author name (first/last or single part) and generate content (keys or extended names respectively). I don't first generate the extended name and then generate a key from it. But even if I would have, spaces are unconditionally removed from the key at the end of the key generation process.
