### ISSUE TITLE
Cannot use the plugin zotero-better-bibtex v6.7.173 in JurisM Standalone 6.0.22m4

### ISSUE THREAD

**Issue by vserge** [retorquere/zotero-better-bibtex#2827]
### Debug log ID

qudmeY6m1SBz-VNW79D93

### What happened?

Hello,

Thanks for your great work!
Some times ago was a problem #475 
Today I think hove the same problem: 
I can't install the pluggin zotero-better-bibtex v6.7.173 in JurisM Standalone 6.0.22m4.
I get the following error message: "Better BibTex for Zotero is incompatible with Zotero 6.0.22m4. Better BibTex for Zotero (disabled)."

I hope you can help!

**Comment by retorquere** [comment]
BBT isn't compatible with Juris-M anymore, Juris-M stalled for a while and has fallen behind too far behind zotero for BBT to support both. I think I've heard Juris-M has picked up development on a 7-compatible version, which bbt would support, but I have no idea where that stands.

**Comment by vserge** [comment]
OK, Thank you.
Will be waiting new version of Juris-M.

**Comment by vserge** [comment]
How to get the log for BBT in Juris-M?

**Comment by retorquere** [comment]
> How to get the log for BBT in Juris-M?

No need
