### ISSUE TITLE
Better BibTeX does not work with Zotero beta 70 and later

### ISSUE THREAD

**Issue by bohong65** [retorquere/zotero-better-bibtex#2829]
### Debug log ID

D1066909120

### What happened?

After an update to Zotero7.0.0-beta.69+56c363521, an error poped up when starting Zotero suggesting an error related to better-bibtex. Since it was shown at the startup, I can only provide the error information with no debug log.
I am pretty much sure the problem is caused by better-bibtex, cause if I disable it, everything goes on well.
![Uploading PixPin_2024-04-09_10-59-49.png…]()
> 1712631217335	addons.xpi	WARN	Checking D:\scholar\zotero\distribution\extensions for addons
1712631218304	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled
[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]
[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]
[JavaScript Error: "Attempt to override an existing message: "delitemwithatt-delete-collection-and-attachment"." {file: "delitemwithatt-addon.ftl" line: 0}]
[JavaScript Error: "Components.classes['@mozilla.org/embedcomp/prompt-service;1'] is undefined" {file: "jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/better-bibtex@iris-advies.com.xpi!/bootstrap.js" line: 40}]
@jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/better-bibtex@iris-advies.com.xpi!/bootstrap.js:40:12
@jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/better-bibtex@iris-advies.com.xpi!/bootstrap.js:157:3
_loadScope@chrome://zotero/content/xpcom/plugins.js:161:27
Zotero.Plugins</this.init@chrome://zotero/content/xpcom/plugins.js:56:17
[JavaScript Error: "TypeError: OS is undefined" {file: "jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 15953}]
[JavaScript Error: "TypeError: OS is undefined" {file: "jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 141042}]
[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]
[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/zoterocitation@polygon.org.xpi!/chrome/content/scripts/index.js" line: 4906}]
[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/zoterocitation@polygon.org.xpi!/chrome/content/scripts/index.js" line: 4906}]
[JavaScript Error: "uncaught exception: undefined" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]
[JavaScript Error: "uncaught exception: undefined" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]
[JavaScript Error: "uncaught exception: undefined" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]
[JavaScript Error: "uncaught exception: undefined" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]
[JavaScript Error: "uncaught exception: undefined" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]
[JavaScript Error: "uncaught exception: undefined" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]
[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "TypeError: newNode is undefined" {file: "jar:file:///C:/Users/rabbi/AppData/Roaming/Zotero/Zotero/Profiles/023hgj4c.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 141265}]
appName => Zotero, version => 7.0.0-beta.69+56c363521, os => Windows 10.0 22631, locale => zh-CN, extensions => Easier Citation (0.4.2, extension), Wandering File (0.2.8, extension), Zotero Reference (0.5.8, extension), Jasminum (1.0.0-6, extension), Translate for Zotero (1.1.0-18, extension), Ethereal Style (3.1.3, extension), Del Item With Attachment (0.3.1, extension), Better BibTex for Zotero (6.7.173, extension)

**Comment by bohong65** [comment]
Debug ID: D1066909120

**Comment by serein88** [comment]
I'm having the same issue. my debug log ID : D1310167716

![Clip_2024-04-09_10-58-35](https://github.com/retorquere/zotero-better-bibtex/assets/71763787/42655158-750f-4dc0-8dd6-75431acf0834)

**Comment by venkate123** [comment]
Could you tell me how to temporarily disable zotero-better-bibtex? Thanks! @bohong65

**Comment by DrownFish19** [comment]
> Could you tell me how to temporarily disable zotero-better-bibtex? Thanks! @bohong65
> 
> Or can anyone share the zotero version beta 68 of MacOS version?

from zotero forums:
> [dstillman](https://forums.zotero.org/profile/6/dstillman) : This would be some problem with the plugin, but this shouldn't break Zotero, so we've fixed this in the latest beta, 7.0.0-beta.70. If you're seeing this, you can reinstall Zotero from the [Beta Builds](https://www.zotero.org/support/beta_builds) page.

the new version can be downloaded from [link](https://www.zotero.org/support/beta_builds)

**Comment by venkate123** [comment]
> > [dstillman](https://forums.zotero.org/profile/6/dstillman) : This would be some problem with the plugin, but this shouldn't break Zotero, so we've fixed this in the latest beta, 7.0.0-beta.70. If you're seeing this, you can reinstall Zotero from the [Beta Builds](https://www.zotero.org/support/beta_builds) page.
> 
> the new version can be downloaded from [link](https://www.zotero.org/support/beta_builds).

Thank you. This did help!

**Comment by bohong65** [comment]
> Could you tell me how to temporarily disable zotero-better-bibtex? Thanks! @bohong65
> 
> Or can anyone share the zotero version beta 68 of MacOS version?

From Tools>>Add-ons(or Plugins)>>Click the switch on the right side of plugin box to disable/enable

**Comment by bohong65** [comment]
> I'm having the same issue. my debug log ID : D1310167716
> 
> ![Clip_2024-04-09_10-58-35](https://private-user-images.githubusercontent.com/71763787/320711059-42655158-750f-4dc0-8dd6-75431acf0834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDg1NzUsIm5iZiI6MTcxMjY0ODI3NSwicGF0aCI6Ii83MTc2Mzc4Ny8zMjA3MTEwNTktNDI2NTUxNTgtNzUwZi00ZGMwLThkZDYtNzU0MzFhY2YwODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZGI4MmZkZjQyYTlkMzRjOThlNzgwNjJkNDMyYTIzYmE0NTA1MDNlOTk0NGZiNWVmYTNlMzcxODY4MWM5MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C6L2YkK_CTWcbEUPcxwqxc90DkhlwEq57CC9HXhdVHw)

BTW, Add citation in Word also encountered unknown error, better to wait for yet another update of Zotero7

**Comment by venkate123** [comment]
> From Tools>>Add-ons(or Plugins)>>Click the switch on the right side of plugin box to disable/enable

Thanks. But in my laptop (Macbook), it can not be turn off by this way. But this method from zotero forums works:

> Restart in Troubleshooting Mode (Help → "Restart in Troubleshooting Mode…”, or hold down Shift at startup) to temporarily disable all plugins, uninstall Better BibTeX, and then contact the plugin developer for help.

**Comment by retorquere** [comment]
I'm looking into the problem but they've made changes that are not easy to work around given that I want a single plugin to work on both 6 and 7.

**Comment by marjomol** [comment]
I'm not getting the error window, but the plug-in is not working for me either as it doesn't appear in the settings of Zotero 7 and it cannot be recognised by the obsidian plug-in where I use it. It also happens since the last update of the beta.

**Comment by marjomol** [comment]
> @marjomol Were you able to solve the problem by reinstalling back the previous version of Zotero? I am not able to find Z7 beta versions before version 69 to install and see if everything works well.

I've been traying but I cannot find any repository with older Zotero 7 versions. In the [forum](https://forums.zotero.org/discussion/comment/460340#Comment_460340) they are throwing the ball to the plug-in's developers as usual.

**Comment by retorquere** [comment]
And I don't see how I could have anticipated this. I guess I have to set up a notification somehow when the zotero for devs page changes.

**Comment by FeralFlora** [comment]
> And I don't see how I could have anticipated this. I guess I have to set up a notification somehow when the zotero for devs page changes.

Well, there was a post about it in the Zotero dev mailing list 10 days ago: https://groups.google.com/g/zotero-dev/c/wirqnj_EQUQ

>We've added a section to the Zotero 7 developer docs that covers the biggest changes to the Mozilla platform from Firefox 102 to 115

> To give plugin developers a chance to update their code first, we've pushed builds on the 'dev' channel

Btw, haven't you been waiting for this? 👇 
> This version also includes **the promised API for adding custom sections to the item pane**

**Comment by retorquere** [comment]
> Well, there was a post about it in the Zotero dev mailing list 10 days ago: https://groups.google.com/g/zotero-dev/c/wirqnj_EQUQ

titled "dev build for fx115 and custom item-pane sections". Not exactly a call to action, and I'm absolutely swamped in email. I'm not reading any email I don't have to. But fair point, I could have known this.

> Btw, haven't you been waiting for this? 👇
> 
> > This version also includes **the promised API for adding custom sections to the item pane**

Yeah, I'll look into that when I have BBT running again in 7.

**Comment by FeralFlora** [comment]
> titled \"dev build for fx115 and custom item-pane sections\". Not exactly a call to action, and I'm absolutely swamped in email.

Fair point, they should definitely have worded that better. And of course, that wasn't meant as criticism, just wanted to point it out for fairness.

**Comment by retorquere** [comment]
Stuff is broken in ChromeWorkers :(. This is not going to be a quick fix.

**Comment by mialuyao** [comment]
> I'm having the same issue. my debug log ID : D1310167716
> 
> ![Clip_2024-04-09_10-58-35](https://private-user-images.githubusercontent.com/71763787/320711059-42655158-750f-4dc0-8dd6-75431acf0834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDg3ODcsIm5iZiI6MTcxMjcwODQ4NywicGF0aCI6Ii83MTc2Mzc4Ny8zMjA3MTEwNTktNDI2NTUxNTgtNzUwZi00ZGMwLThkZDYtNzU0MzFhY2YwODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAwMjEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjk2ZWNmYTQ2YTJkOTEwMzE3NDU5MWQ0YjYwMWUyZGI2N2U4NzU4ZjEzMWY0YWZmNDZlZTk3NjgxMjgyNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lyfyGaioonF5oDoI3k5jZvFRSXi-9b8r3yv90IGbj98)

I've encountered the same issue as well. Have you found a solution? Is it currently usable?

> > From Tools>>Add-ons(or Plugins)>>Click the switch on the right side of plugin box to disable/enable
> 
> Thanks. But in my laptop (Macbook), it can not be turn off by this way. But this method from zotero forums works:
> 
> > Restart in Troubleshooting Mode (Help → "Restart in Troubleshooting Mode…”, or hold down Shift at startup) to temporarily disable all plugins, uninstall Better BibTeX, and then contact the plugin developer for help.

The method doesn't work on my MacBook. There's a small window like this.
![1712709183732](https://github.com/retorquere/zotero-better-bibtex/assets/93652296/a87f88ce-fcb3-4865-a54a-20a742ac34c3)

**Comment by bohong65** [comment]
> @marjomol Were you able to solve the problem by reinstalling back the previous version of Zotero? I am not able to find Z7 beta versions before version 69 to install and see if everything works well.

@zararash I did keep the old version package for Zotero7.0.0-beta.40+24ae34104, which works well. The package is for Windows 64bit though, I paste it here, might help?
https://drive.google.com/file/d/1pea3RnZY3GEGREo6LNhAL1AwxaLhM-iI

**Comment by Sciroccogti** [comment]
> @zararash I did keep the old version package for Zotero7.0.0-beta.40+24ae34104, which works well. The package is for Windows 64bit though, I paste it here, might help? https://drive.google.com/file/d/1pea3RnZY3GEGREo6LNhAL1AwxaLhM-iI

Really helpful! Thanks!

BTW, is there anyway to turn off auto update?

**Comment by bohong65** [comment]
> > I'm having the same issue. my debug log ID : D1310167716
> > ![Clip_2024-04-09_10-58-35](https://private-user-images.githubusercontent.com/71763787/320711059-42655158-750f-4dc0-8dd6-75431acf0834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDg3ODcsIm5iZiI6MTcxMjcwODQ4NywicGF0aCI6Ii83MTc2Mzc4Ny8zMjA3MTEwNTktNDI2NTUxNTgtNzUwZi00ZGMwLThkZDYtNzU0MzFhY2YwODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAwMjEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjk2ZWNmYTQ2YTJkOTEwMzE3NDU5MWQ0YjYwMWUyZGI2N2U4NzU4ZjEzMWY0YWZmNDZlZTk3NjgxMjgyNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lyfyGaioonF5oDoI3k5jZvFRSXi-9b8r3yv90IGbj98)
> 
> I've encountered the same issue as well. Have you found a solution? Is it currently usable?
> 
> > > From Tools>>Add-ons(or Plugins)>>Click the switch on the right side of plugin box to disable/enable
> > 
> > 
> > Thanks. But in my laptop (Macbook), it can not be turn off by this way. But this method from zotero forums works:
> > > Restart in Troubleshooting Mode (Help → "Restart in Troubleshooting Mode…”, or hold down Shift at startup) to temporarily disable all plugins, uninstall Better BibTeX, and then contact the plugin developer for help.
> 
> The method doesn't work on my MacBook. There's a small window like this. ![1712709183732](https://private-user-images.githubusercontent.com/93652296/321035762-a87f88ce-fcb3-4865-a54a-20a742ac34c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTc3MTIsIm5iZiI6MTcxMjcxNzQxMiwicGF0aCI6Ii85MzY1MjI5Ni8zMjEwMzU3NjItYTg3Zjg4Y2UtZmNiMy00ODY1LWE1NGEtMjBhNzQyYWMzNGMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDlkMmU4ZmI1MmZmYTA2ZGU1NGVhMThiODgzYmExN2MzYTBiOWY2MmY0MWJkMDE1MGZmZWJkYmQ4MDA3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JG94QifxAukKt94Z8WitlMXv-84oPH6wnbcI28vkmD4)

@mialuyao Humm, it is the same case on Windows, small window exists, but doesn't prohibit you from using, actually you need to click "Check for Updates" when the error window pops up, so as to continue any operation.

**Comment by bohong65** [comment]
> > @zararash I did keep the old version package for Zotero7.0.0-beta.40+24ae34104, which works well. The package is for Windows 64bit though, I paste it here, might help? https://drive.google.com/file/d/1pea3RnZY3GEGREo6LNhAL1AwxaLhM-iI
> 
> Really helpful! Thanks!
> 
> BTW, is there anyway to turn off auto update?

Sure, open the config editor
![image](https://github.com/retorquere/zotero-better-bibtex/assets/14939297/f38e43b3-0dee-4353-b3c2-e25d9f3d110e)
Search for update, change the app.update.auto to false
<img width="735" alt="PixPin_2024-04-10_11-03-51" src="https://github.com/retorquere/zotero-better-bibtex/assets/14939297/3fdebb0a-9bdf-4bea-99e5-e72039320201">

**Comment by Sciroccogti** [comment]
> Sure, open the config editor 
Thanks!

One of my friend @GSW4869 happens to have kept newer installer:
https://drive.google.com/file/d/1FSo8Oqg9-0j846HMqo7-dFr_Lpa9ojB5/view?usp=drive_link

**Comment by mialuyao** [comment]
> > > I'm having the same issue. my debug log ID : D1310167716
> > > ![Clip_2024-04-09_10-58-35](https://private-user-images.githubusercontent.com/71763787/320711059-42655158-750f-4dc0-8dd6-75431acf0834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDg3ODcsIm5iZiI6MTcxMjcwODQ4NywicGF0aCI6Ii83MTc2Mzc4Ny8zMjA3MTEwNTktNDI2NTUxNTgtNzUwZi00ZGMwLThkZDYtNzU0MzFhY2YwODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAwMjEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjk2ZWNmYTQ2YTJkOTEwMzE3NDU5MWQ0YjYwMWUyZGI2N2U4NzU4ZjEzMWY0YWZmNDZlZTk3NjgxMjgyNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lyfyGaioonF5oDoI3k5jZvFRSXi-9b8r3yv90IGbj98)
> > 
> > 
> > I've encountered the same issue as well. Have you found a solution? Is it currently usable?
> > > > From Tools>>Add-ons(or Plugins)>>Click the switch on the right side of plugin box to disable/enable
> > > 
> > > 
> > > Thanks. But in my laptop (Macbook), it can not be turn off by this way. But this method from zotero forums works:
> > > > Restart in Troubleshooting Mode (Help → "Restart in Troubleshooting Mode…”, or hold down Shift at startup) to temporarily disable all plugins, uninstall Better BibTeX, and then contact the plugin developer for help.
> > 
> > 
> > The method doesn't work on my MacBook. There's a small window like this. ![1712709183732](https://private-user-images.githubusercontent.com/93652296/321035762-a87f88ce-fcb3-4865-a54a-20a742ac34c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTc3MTIsIm5iZiI6MTcxMjcxNzQxMiwicGF0aCI6Ii85MzY1MjI5Ni8zMjEwMzU3NjItYTg3Zjg4Y2UtZmNiMy00ODY1LWE1NGEtMjBhNzQyYWMzNGMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDlkMmU4ZmI1MmZmYTA2ZGU1NGVhMThiODgzYmExN2MzYTBiOWY2MmY0MWJkMDE1MGZmZWJkYmQ4MDA3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JG94QifxAukKt94Z8WitlMXv-84oPH6wnbcI28vkmD4)
> 
> @mialuyao Humm, it is the same case on Windows, small window exists, but doesn't prohibit you from using, actually you need to click "Check for Updates" when the error window pops up, so as to continue any operation.

When I close this small window, the app crashes. I can't use it right now. 
![1712718878596](https://github.com/retorquere/zotero-better-bibtex/assets/93652296/266c4a60-2c90-4f6b-8f53-6a5ca46d2543)
![1712719042016](https://github.com/retorquere/zotero-better-bibtex/assets/93652296/21737b55-04c2-44bb-80fc-9c20e12e34ad)

**Comment by venkate123** [comment]
> The method doesn't work on my MacBook. There's a small window like this. ![1712709183732](https://private-user-images.githubusercontent.com/93652296/321035762-a87f88ce-fcb3-4865-a54a-20a742ac34c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDAzNTgsIm5iZiI6MTcxMjc0MDA1OCwicGF0aCI6Ii85MzY1MjI5Ni8zMjEwMzU3NjItYTg3Zjg4Y2UtZmNiMy00ODY1LWE1NGEtMjBhNzQyYWMzNGMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZWMyMDVkZTdmZTUxNmM5YTg2YTVlZGE3NmMwMTA4NmEwMjQ3MGVhZjQ5NjZjZTVlZTNkOWJlNzA4MWIwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fF4XJk4POTt_1bbV_7PN8hFqjNVw6l6gdv-qFvP_IDY)

After you minimize this small window, you can left click on the Zotero main window. Then you can select Help → "Restart in Troubleshooting Mode…” from the menu bar.

**Comment by bohong65** [comment]
@mialuyao Can you see the main interface if you minimize the small window instead of close it? If you can't, then you have to downgrade to elder version, 7.0 beta.40 for instance.

**Comment by afk-procrastinator** [comment]
I'm running into the same issue on MacOS, except Zotero works as normal. It's just as if better-bibtex simply wasn't enabled or installed. Any news on when this might be fixed?

**Comment by retorquere** [comment]
No. This has my attention, and BBT is partially running again, but some pretty fundamental stuff is gone from Zotero that doesn't have an obvious replacement in 70+. I'm looking for workarounds but I'm not sure they exist, and I may be dependent on Zotero to make changes to make it work again.

**Comment by btromm** [comment]
Are you using the flatpak or tarball build? It is fully broken for me on the tarball.

Luckily, my macOS build has yet to update to 72.

**Comment by retorquere** [comment]
I'm using the .deb-packaged tarball, but that has started failing last night. My tests run at least once a day to pick up these kind of things.

**Comment by kzssc** [comment]
not a complaint/solution, just a temporary fix: i'm currently reverting back to b68 to make use of the plugin. Thanks to the people over in the Zotero forum. https://forums.zotero.org/discussion/113539/importing-bibtex-from-clipboard-fails-on-zotero-7#latest

**Comment by retorquere** [comment]
I'm optimistic about getting a fix out tomorrow. Most tests run green again, two to go.

**Comment by Sciroccogti** [comment]
> 🤖 this is your friendly neighborhood build bot announcing [test build 6.7.173.2829.6002](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.173.2829.6002.xpi) ("docs would have been soooooooo useful")

It works!

**Comment by Homerjf0ng** [comment]
@retorquere you're a legend - my Zotero to Obsidian pipeline is alive again!

**Comment by bohong65** [comment]
Everything works well, thank you all!

**Comment by retorquere** [comment]
> Btw, haven't you been waiting for this?

Turns out no -- this allows adding whole sections, I want to add the citation key to the existing section. Making a separate section for the the citation key isn't good UX, and if they at some point add their own field for citation key, it is for sure ending up in the default item pane.

**Comment by retorquere** [comment]
Yeah that should have been when, not if. I suppose. One item type actually does have a citation key field now, but getting it for all item types was supposed to come real soon now for a long time.

**Comment by erazlogo** [comment]
Is it possible to copy citekey in the Zotero 7 interface? I haven't been able to figure out how. I can only add it as a list column, but then I can't copy it.
