### ISSUE TITLE
Stuck in "Exporting items" with 7.0.0-beta.71+03d0ea436

### ISSUE THREAD

**Issue by Sciroccogti** [retorquere/zotero-better-bibtex#2831]
### Debug log ID

D1678910747

### What happened?

Debug log cannot be generated because the `BBT debug log` just wont popup. I think the new version is not supported yet.

**Comment by GYukai** [comment]
Same here

**Comment by retorquere** [comment]
See #2829

**Comment by retorquere** [comment]
Please subscribe to #2829 if you want to track progress

**Comment by Sciroccogti** [comment]
Right, it seems to be the same problem.
Luckily Linux version works fine so far.

**Comment by retorquere** [comment]
If it had broken on Linux I would have known sooner, because my test suite runs on linux.
