### ISSUE TITLE
BBT can't work on 7.0.0-beta.72+128a540af

### ISSUE THREAD

**Issue by aaronkhq** [retorquere/zotero-better-bibtex#2833]
### Debug log ID

N/A

### What happened?

sorry for that I can not provide the Debug log ID because BBT can't work at all.
mac: macOs Sonoma 14.1.1 (23B81)
zotero version: 7.0.0-beta.72+128a540af
BBT version: 6.7.173

When I update Zotero to 7.0.0-beta.72+128a540af, I find BBT can't work at all. I tried to close all the other plugins and just keep BBT. However, Zotero Setting can't show BBT. 

<img width="1032" alt="image" src="https://github.com/retorquere/zotero-better-bibtex/assets/65768952/d96e8332-e6d4-46d0-a0a3-0afd2f8f94b1"> 

I also made Zotero back to 7.0.0-beta.68 (I can only find the last version on the Internet. Do anyone know where I can download 7.0.0-beta.70 or 7.0.0-beta.71?) and BBT can work on  7.0.0-beta.68. 

Hoping for your reply!
Thank you for your amazing work!

**Comment by ThaddeusWu** [comment]
Hi team,

First of all, thanks all your contribution to the Zotero community. I recently suffered the same issue, which made a broken connection with Obsidian (cannot detect the BBT plugin has been installed).

This is my debug ID - D17567357

mac: macOs Sonoma 14.1.1 (23B81)
zotero version: 7.0.0-beta.72+128a540af
BBT version: 6.7.173

Thank you very much!

Best,
Thaddeus

**Comment by retorquere** [comment]
#2829
