### ISSUE TITLE
URL not recognised in a simple @online .bib file entry on import

### ISSUE THREAD

**Issue by WitaliBartsch** [retorquere/zotero-better-bibtex#2842]
### Debug log ID

CFWDK68Z-refs-euc/6.7.174-6

### What happened?

In a simple case (please see bib entry below), the URL is not recognised when importing that file through BBT. In contrast to that, regular Zotero import does it.
[example.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/15038818/example.bib.txt)

The corresponding BBT settings are as follows. However, I have already tried out a number of different combinations setting some of the flags below to false, to no avail though.

Thank you very much for your help and your great software! 👍 

extensions.zotero.translators.better-bibtex.import;true
extensions.zotero.translators.better-bibtex.importDetectURLs;true
extensions.zotero.translators.better-bibtex.importSentenceCase;off
extensions.zotero.translators.better-bibtex.importSentenceCaseQuoted;true
extensions.zotero.translators.better-bibtex.importUnknownTexCommand;ignore
extensions.zotero.translators.better-bibtex.rawImports;true

**Comment by WitaliBartsch** [comment]
Good morning and thank you very much for releasing an update so quickly for me to test. I just did resulting in the following error message:

1713765770894	addons.update-checker	WARN	Request failed: https://github.com/retorquere/zotero-storage-scanner/releases/download/release/update.rdf - 404: Not Found

[JavaScript Error: "XML Parsing Error: not well-formed
Location: moz-nullprincipal:{4961a39c-f3b3-497a-8fa6-8fca72d0d590}
Line Number 1, Column 1:" {file: "moz-nullprincipal:{4961a39c-f3b3-497a-8fa6-8fca72d0d590}" line: 1 column: 1 source: "@Online{Gartner_CloudComputing,"}]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: moz-nullprincipal:{0aaa723a-b804-4fbb-8ecd-d99b2682946e}
Line Number 1, Column 1:" {file: "moz-nullprincipal:{0aaa723a-b804-4fbb-8ecd-d99b2682946e}" line: 1 column: 1 source: "@Online{Gartner_CloudComputing,"}]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: moz-nullprincipal:{7b0a494a-e460-48ec-9721-ea54447f482c}
Line Number 1, Column 1:" {file: "moz-nullprincipal:{7b0a494a-e460-48ec-9721-ea54447f482c}" line: 1 column: 1 source: "@Online{Gartner_CloudComputing,"}]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: moz-nullprincipal:{77c8b3ec-7122-437c-b82b-d60d951615d7}
Line Number 1, Column 1:" {file: "moz-nullprincipal:{77c8b3ec-7122-437c-b82b-d60d951615d7}" line: 1 column: 1 source: "@Online{Gartner_CloudComputing,"}]

[JavaScript Error: "A network error occurred." {file: "chrome://zotero/content/xpcom/file.js" line: 339}]

version => 6.0.36, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-GB, appName => Zotero, appVersion => 6.0.36, extensions => Zutilo Utility for Zotero (3.10.0, extension), ZotFile (5.1.2, extension), Open PDF for Zotero (0.0.11, extension), Storage Scanner for Zotero (5.0.12, extension), Mdnotes for Zotero (0.2.3, extension), ZoteroAbstractCleaner (0.0.7, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.36, extension), Zotero Word for Windows Integration (6.0.4.SA.6.0.36, extension), Zotero OCR (0.7.1, extension), Better BibTex for Zotero (6.7.174.2842.6049, extension), Zotero Better Notes (1.0.4, extension)

**Comment by WitaliBartsch** [comment]
I am sorry to to say this, but it actually got worse: previously, an entry would be generated inside a new collection – just without the URL field inside. Now, no entry is created at all anymore.

**Comment by retorquere** [comment]
Can you try to import again, and then send a debug log? There's no need to post parts of the log in the issue, the debug log gives me what I need.

**Comment by WitaliBartsch** [comment]
The issue has been resolved.
