### ISSUE TITLE
Work not going to Obsidian via citekey

### ISSUE THREAD

**Issue by Dgr4h4m** [retorquere/zotero-better-bibtex#2843]
### Debug log ID

Y6K4WWJJ-refs-euc/6.7.174-6

### What happened?

I use pandoc to insert citation into Obsidian via a bibtex file. This file is not pulling up when I try and cite it in Obsidian. I re-exported my library and deleted and re-added this resource and the same issue is still being experienced.

**Comment by retorquere** [comment]
I don't understand the situation you are describing, sorry.

> I use pandoc to insert citation into Obsidian via a bibtex file.

I don't know how you're using pandoc here, but it doesn't sound like BBT is involved in this step.

> This file is not pulling up when I try and cite it in Obsidian

I don't know what "pulling up" means in this context

> I re-exported my library

OK so you've exported it using BBT I take it? Is the file exported successfully?

> and deleted and re-added this resource

I am assuming "this resource" refers to the successfully exported bibtex file, but I don't know what you deleted it from and where you added it to.

**Comment by Dgr4h4m** [comment]
No problem, thank you for getting back to me. I realized that the bibliography file I was pointing Obsidain to was the wrong file that was not updating automatically. I changed the file path to the correct bibliography file and it is working now.
