### ISSUE TITLE
Three dashes in extra field for generating markdown files from bibtex

### ISSUE THREAD

**Issue by juancarloscastillo** [retorquere/zotero-better-bibtex#2849]
### Debug log ID

---

### What happened?

I have a problem with the newest version of BBT regarding including  three dahes (---).  in the extra field. Before (at least with version 6.7.132) when generating the bibtex file it reflected there the line breaks before and after them, but in the new version it eliminates the line breaks. The need for the line breaks it relates with a script I use that generates markdown files from the bibtex entries (https://jc-castillo.com/post/zotero-academic/) , therefore I need the --- in a different line in the bibtex, as it is specified in the extra field.
I installed the previous BBT version and it works fine, but I hope this could also work in the current and future versions.

This is how it is rendered with the previous version, reflecting the extra field (annotation in bibtex) correctly: 

```
@inproceedings{castillo_authoritarianism_2011a,
  title = {Authoritarianism, social dominance, and trust in public institutions.},
  booktitle = {Annual Scientific Meeting of the International Society of Political Psychology – ISPP},
  author = {Castillo, J. and Miranda, D. and Torres, P.},
  year = {2011},
  month = jul,
  address = {Bilgi University, Istambul},
  keywords = {legitimacy ideology Chile},
  annotation = {url\_slides: "lisa-coes.github.io/"
---
This is a presentation funded by ANID 
}
}
```

 And here with the newest one, eliminating the line breaks before and after:

```
@inproceedings{castillo_authoritarianism_2011a,
  title = {Authoritarianism, social dominance, and trust in public institutions.},
  booktitle = {Annual Scientific Meeting of the International Society of Political Psychology – ISPP},
  author = {Castillo, J. and Miranda, D. and Torres, P.},
  year = {2011},
  month = jul,
  address = {Bilgi University, Istambul},
  keywords = {legitimacy ideology Chile},
  annotation = {url\_slides: "lisa-coes.github.io"---This is a presentation funded by ANID 
}
}
```

Thanks in advance, wonderful work with this Zotero add-on!

**Comment by retorquere** [comment]
You're asking my time but can't be bothered to make a few mouse clicks to make that time spent efficiently, or even write out why you think (wrongly) that I don't need or deserve a log.

The issue will automatically reopen when you post a debug log.

**Comment by juancarloscastillo** [comment]
Actually, I took the time for the few mouse clicks but the program  freezed and I could not move forward in generating the log, therefore I tried to detail the issue as clear as possible. After your message, I thought that maybe this was because I had to install a previous version in order to solve my issue; so, I installed again the new version and the debug log worked well. 

The debug log ID is 2KZZJD5R-refs-euc/6.7.177-6

I uploaded the produced files:

[items.json](https://github.com/retorquere/zotero-better-bibtex/files/15138580/items.json)
[debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/15138581/debug.txt)

Thanks in advance for your time.

**Comment by retorquere** [comment]
> Actually, I took the time for the few mouse clicks but the program freezed and I could not move forward in generating the log

Which is a more useful explanation than `---`. If the debug log doesn't work, I want to fix that.

> I uploaded the produced files:

no need, that's what the debug log is for. I have a toolchain that (among other things) makes ready-to-run testcases from debug log IDs so that I don't have to copy-paste, download, put in the right place etc. All sources of errors.

I agree that what is put in `annotation` isn't really right for what's in your `extra` field. I'm sort of torn on what the right output would be, or even whether `annotation` is the right field for it; I started out with the idea that `extra` was for lightweight notes, but really notes are for notes, and `extra` is more for custom fields. In any case, the following gives output that renders what is in your `extra` field:

```
@inproceedings{castillo_authoritarianism_2011,
  title = {Authoritarianism, social dominance, and trust in public institutions.},
  author = {Castillo, J. and Miranda, D. and Torres, P.},
  date = {2011-07},
  location = {Bilgi University, Istambul},
  eventtitle = {Annual Scientific Meeting of the International Society of Political Psychology  ISPP},
  keywords = {legitimacy ideology Chile},
  annotation = {url\_slides: "lisa-coes.github.io/"\\
---\\
This is a presentation funded by ANID}
}
```

but from your description, you want single linebreaks to show up as-is, which as far as LaTeX is concerned is the same as a space, which is equivalent to the current output.

**Comment by retorquere** [comment]
I'd appreciate feedback on the change.

**Comment by retorquere** [comment]
Did it previously have back-ticks around the triple-dash? I'm not sure how that ever came about.

**Comment by juancarloscastillo** [comment]
Previously there were no back-ticks around the triple dash, but now I am adding the backslashes in the extra field  and I can see them in the bibtex, then you very much.

**Comment by juancarloscastillo** [comment]
I added the backticks to the --- because otherwise they were transformed into a line in the preview of the message, but I get the three dashed without backticks.
I checked again and actually if I add the backslashes I get  \textbackslash. If I understand well: the line breaks in the extra field should appear as \\ in the annotation field in the bibtex, right? I tried again (with the last version of BBT) and they do not appear, what I get is:

```
  annotation = {url\_slides: "lisa-coes.github.io/" --- This is a presentation funded by ANID}
}
```

**Comment by retorquere** [comment]
> I added the backticks to the --- because otherwise they were transformed into a line in the preview of the message, but I get the three dashed without backticks.

Ah OK I see.

> If I understand well: the line breaks in the extra field should appear as \ in the annotation field in the bibtex, right? 

as `\\`. 

> I tried again (with the last version of BBT) and they do not appear, what I get is:

Latest as in latest release? Or the latest version dropped here? If latest release -- please try latest version dropped here. If latest version dropped here -- please send a debug log.

**Comment by juancarloscastillo** [comment]
Now I tried with the latest-latest and it works perfectly. Thank you very much.
