### ISSUE TITLE
Can not find "Push Reference to Texstudio"

### ISSUE THREAD

**Issue by kmrkmrkmr** [retorquere/zotero-better-bibtex#2855]
### Debug log ID

PIA8P77X-refs-euc/6.7.178-6

### What happened?

I can not find the "Push Reference to Texstudio" option. And the texstudio is in my PATH.
What's more, I tried CAYW. Following https://www.youtube.com/watch?v=Whn9Mk-JwL0 , I write Macro in Texstudio and terminal, both work well and get right result, but the result only shows in the "messages" box of Texstudio and do not be inserted to the text.
I want to fix the "Push Reference to Texstudio" option and fix the CAYW macro.

**Comment by retorquere** [comment]
Please go to Help -> Debug Output Logging -> Restart with Logging enabled, allow Zotero to restart, and send a new debug log.

No relation, but the Zotero Style plugin is reporting errors in the log. The plugin author may want to know.

**Comment by kmrkmrkmr** [comment]
QUXRXSHH-refs-euc/6.7.179-6
This is the new Debug Log ID with the two plugins enabled.

5GJZMYNU-refs-euc/6.7.179-6
And this is the Debug Log ID with three plugins disabled: Zotero Style, journalabbr and pdf preview. The last one (pdf preview) also appears in the error. The existing error is about sync now but my sync works well. Although these plugins are disabled, I can not find the option.

I used to use zotero in Windows 10 with all these plugins and the "Push reference to texstudio" function works well. Of cause the plugin versions are not the same. I am sorry that the Windows system has been deleted.

**Comment by retorquere** [comment]
> QUXRXSHH-refs-euc/6.7.179-6 This is the new Debug Log ID with the two plugins enabled.

It doesn't matter whether the other plugins are enabled or not they don't interfere with BBT. The authors may just want to know.

Please go into Tools -> Developer -> Run javascript, paste in the code below, and click "run". Then tell me what the right window says:

```
const ENV = Components.classes['@mozilla.org/process/environment;1'].getService(Components.interfaces.nsIEnvironment)
ENV.get('PATH')
```

**Comment by kmrkmrkmr** [comment]
Here is answer in the right window:
```
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/username/.local/share/JetBrains/Toolbox/scripts
```

The command in terminal:
```shell
zotero
```
can launch the zotero but shows
```
Gtk-Message: 12:10:10.855: Failed to load module "appmenu-gtk-module"
WebGL(0x7c8ee567b800)::ForceLoseContext
```

And the command in terminal:
```shell
texstudio
```
can launch Texstudio and shows nothing in terminal.

I can find zotero and texstudio only in `/usr/bin` and here are the details:
```shell
lrwxrwxrwx 1 root root 22 Apr 22 20:50 /usr/bin/zotero -> /usr/lib/zotero/zotero
-rwxr-xr-x 1 root root 24235432 Mar  2 10:28 /usr/bin/texstudio
-rwxr-xr-x 1 root root 552 Apr 22 20:50 /usr/lib/zotero/zotero
```

What's more, I used to think it is something about Linux but I found that the BBT on my Windows 10 laptop can not use the function too. So I tried an old version (6.7.142) on my Linux right now and I found the function "Push entries to Texstudio" and works well. I send a Debug Log ID:
4NXACGBT-refs-apse/6.7.142-6

I do not know if you remove this function in the new version BBT and I do not find much information about "Push entries to Texstudio" function in issues and official website.

**Comment by retorquere** [comment]
> can launch the zotero but shows
> 
> ```
> Gtk-Message: 12:10:10.855: Failed to load module "appmenu-gtk-module"
> WebGL(0x7c8ee567b800)::ForceLoseContext
> ```

not relevant, that error comes from zotero itself.

> I do not know if you remove this function in the new version BBT

If I did I wouldn't be asking these questions?

A new build will drop here soon that will do more logging, it might also solve the problem. If it doesn't, please send a new log.

**Comment by kmrkmrkmr** [comment]
I tried the test build. It solves the problem and works well. And here is the new log:
SQ7Y9WK9-euc/6.7.181.2855.6163-6

Should I wait for a new version to fix the issue or is there something wrong with my software and plugin settings?

**Comment by retorquere** [comment]
Nope, it was a bug in BBT.

**Comment by kmrkmrkmr** [comment]
I am so sorry for the open and close, please close it. I will not reply.
