### ISSUE TITLE
[Zotero 7 Beta] Stealing focus after item creation

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2857]
### Debug log ID

Q8MVY9KZ-euc

### What happened?

Just after creating an item from the "New Item" icon at the top left of the Items Tree, the cursor usually goes to the Title field of the newly created item.
But after activating the BBT plugin, I can see the cursor in the Title field for a short time and then it goes away.

I also got an error while submitting the BBT debug log:
`OperationError: PathUtils.filename: Could not initialize path: NS_ERROR_FILE_UNRECOGNIZED_PATH (Q8MVY9KZ-euc, items: false)`

BBT 6.7.178
Zotero 7.0.0-beta.76+91054acfe (64-bit)
Windows 10

**Comment by retorquere** [comment]
I've found the problem with the debug log, thank you. I'll look into the focus-stealing.

**Comment by retorquere** [comment]
Can you test build 6179?

**Comment by jryans** [comment]
I have tested build 6179 in Zotero 6, and it looks like it fixes the focus issue for me, thanks! 😄 

I haven't used Zotero 7 yet, so perhaps best to wait for @mjthoraval to provide feedback after testing in that version.

**Comment by mjthoraval** [comment]
Sorry for the late reply.
I confirm that the problem is fixed.
Thank you very much!
