### ISSUE TITLE
XML parsing error while opening  

### ISSUE THREAD

**Issue by fritzCard** [retorquere/zotero-better-bibtex#2858]
### Debug log ID

QQ48C3PJ-euc/6.7.179-6

### What happened?

I would like to open the BetterBibTex Preferences. But I get an error message
XML Parsing Error: undefined entity
Location: chrome://zotero-better-bibtex/content/preferences.xul
Line Number 425, Column 15: <checkbox class="bbt-autoexport-options bbt-autoexport-BetterBibLaTeX bbt-prefs-2col-span" data-ae-field="biblatexChicago" label="&better-bibtex_preferences_auto-export_fields_biblatexChicago.label;" oncommand="Zotero.BetterBibTeX.PrefPane.autoexport.edit(this)"/>
--------------^
I have tried uninstalling and reinstalling the add-on. However, that did not solve the problem. The error message is the same.

Thank you for your support!

**Comment by stefan-kuepper** [comment]
AA4PW592-euc/6.7.179-6

I got the same issue

**Comment by retorquere** [comment]
Please try build 6148

**Comment by fritzCard** [comment]
That worked. 

Many, many thanks for the prompt response to my problem!

**Comment by fritzCard** [comment]
That worked. 

Many, many thanks for the prompt response to my problem!
