### ISSUE TITLE
Focus moves away from author after setting last name

### ISSUE THREAD

**Issue by jryans** [retorquere/zotero-better-bibtex#2864]
### Debug log ID

ZJ8LCKF4-refs-euc/6.7.182-6

## Context

macOS 14.4.1
Zotero 6.0.37
BBT 6.7.182

## Summary

(This issue is similar / the same as https://github.com/retorquere/zotero-better-bibtex/issues/2790, but unlike the reporter there, I am using regular Zotero 6.)

I have also noticed that keyboard focus is lost when entering an author's last name, presumably because the BBT citation key changes. This forces me to switch to the mouse, which slows down Zotero operations for me. If I disable BBT, the issue goes away, so it seems related to BBT's citation key UI.

## Expected results

1. Enter author last name (without pressing Enter)
2. Press Tab to move to first name
3. First name field is focused

## Actual results

1. Enter author last name (without pressing Enter)
2. Press Tab to move to first name
3. First name field is briefly focused, but then focus moves away

**Comment by retorquere** [comment]
I'm going to fix this together with #2857, I'd appreciate it if you would join that issue
