### ISSUE TITLE
Item pane citation key label string missing

### ISSUE THREAD

**Issue by jryans** [retorquere/zotero-better-bibtex#2865]
### Debug log ID

ZJ8LCKF4-refs-euc/6.7.182-6

## Context

macOS 14.4.1
Zotero 6.0.37
BBT 6.7.182

## Summary

The item pane citation key label seems to be missing from the strings in recent BBT versions:

![2024-05-04 at 16 51](https://github.com/retorquere/zotero-better-bibtex/assets/279572/dbaafb2e-3a3c-407a-915d-03e2d6587093)

**Comment by retorquere** [comment]
I'm waiting for the translations to come in and then I'll cut a new release.

**Comment by jryans** [comment]
Thanks for the quick fix! 😄
