### ISSUE TITLE
Cannot export library to a .bib file on MacOS

### ISSUE THREAD

**Issue by polientary** [retorquere/zotero-better-bibtex#2867]
### Debug log ID

G3QYRPAE-euc/6.7.182-7

### What happened?

Exported .bib file of the entire library stopped updating. According to last modified date it stopped updating on April 10. Tried to re-export, but I get an error "An error occurred while trying to export the selected file.". 
When I delete the file and remove it from export in settings of BBT, it reappears in exported files again after restart.
Tried to disable caching but it does not work.

**Comment by retorquere** [comment]
Please install build 6181 and send a new log

**Comment by polientary** [comment]
Done
W7MAYF3D-euc/6.7.182.2867.6181-7

**Comment by retorquere** [comment]
Again with vuild 6186 please

**Comment by retorquere** [comment]
Again with 6195 please

**Comment by polientary** [comment]
ZGDZ2JGQ-euc/6.7.182.2867.6195-7

**Comment by polientary** [comment]
Thanks for the quick resolution by the way! It really helped me!
