### ISSUE TITLE
Zotero 7: BBT startup error on older beta

### ISSUE THREAD

**Issue by Michael-N-N** [retorquere/zotero-better-bibtex#2875]
### Debug log ID

A8X5LYFK-fio-BepPxImdsD0X

### What happened?

Everytime I start Zotero there is an error message from BBT: "Better bibTeX startup failed. TypeError: Zotero.ItemPaneManager is undefinded."

Zotero: 7.0.0-beta.68+c31a40c74 (64-bit
BBT: 6.7.185
OS: Windows 10

**Comment by retorquere** [comment]
You'll need to upgrade Zotero beta to the latest version.

**Comment by Michael-N-N** [comment]
Sorry, I thought that I had the latest Zotero version.

The update fixed the problem. Thanks.
