### ISSUE TITLE
BBT exporting @string references when asked to export @string references

### ISSUE THREAD

**Issue by kzssc** [retorquere/zotero-better-bibtex#2876]
### Debug log ID

B4BIM45S-euc/6.7.186-7

### What happened?

Some items in the exported .bib are without (double) brackets, this renders capitalisation problem post-pandoc (attached). This issue is not found on the zotero-exported .bib (example not included). 

![Attachment-1](https://github.com/retorquere/zotero-better-bibtex/assets/37780271/b8562b44-2b31-477d-aea7-7832a60f60df)
<img width="188" alt="Attachment" src="https://github.com/retorquere/zotero-better-bibtex/assets/37780271/1effd430-2705-4174-9d7a-a56f55fd4712">

<img width="179" alt="Attachment-4" src="https://github.com/retorquere/zotero-better-bibtex/assets/37780271/8b2c147e-2562-4da9-8d37-b2aa1b4d1256">
<img width="284" alt="Attachment-3" src="https://github.com/retorquere/zotero-better-bibtex/assets/37780271/bdedaaeb-d5ff-4de1-a96f-785e51c81efe">

**Comment by retorquere** [comment]
You're telling BBT to do this:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/132108/b15de4ad-9d22-432b-8d3b-5588fbed9115)

The default is "No".

**Comment by kzssc** [comment]
You're right - no idea why that was changed. (I couldn't even understand what the menu means, haha!) All good!
