### ISSUE TITLE
Scripting: Remove reading notes from tex field "notes" based on tag

### ISSUE THREAD

**Issue by Neigelily** [retorquere/zotero-better-bibtex#2878]
### Debug log ID

remove-reading-notes

### What happened?

Hello,

Would it be possible to get help writing a postscript that removes Zotero reading notes from tex field "note" based on tag specifying that a Zotero note is a reading note?

Thanks a lot in advance!

**Comment by retorquere** [comment]
remove-reading-notes is not a debug log ID of course.

**Comment by Neigelily** [comment]
I'm very sorry for not including a debug log ID. I wasn't sure as to whether I should since I'm not encountering any bug. Here it is: P8LZ55QA-euc/6.7.192-6

**Comment by retorquere** [comment]
I'll need a debug log obtained by right-clicking the item of interest abs sending it from the menu that pops up. It will have `-refs-` in it.

**Comment by Neigelily** [comment]
Thank you, here it is: 6QZ8IQX2-refs-euc/6.7.192-6

**Comment by retorquere** [comment]
I will take a look when I'm back home.

**Comment by Neigelily** [comment]
Thanks a lot!

**Comment by retorquere** [comment]
```
if (Translator.BetterTeX) { // only for tex, not for CSL
  if (zotero.notes) { // only if the item has notes
    // remove the field unconditionally -- if you filter all notes away, the input may be empty, and add doesn't do anything if the input
    // is empty -- maybe I should change that
    tex.remove('notes')
    // keepeverything except the unwanted note, that is: notes without tags, or, if a note has tags, not the tag 'Reading note'
    zotero.notes = zotero.notes.filter(note => !note.tags || !note.tags.find(tag => tag.tag === 'Reading note'))
    // add the field back
    this.add({ name: 'note', value: zotero.notes.map(note => note.note).join('</p><p>'), html: true })
  }
}
```

**Comment by Neigelily** [comment]
It works, thank you so much! And thanks a lot for your work on this awesome plugin.
