### ISSUE TITLE
cayw window does not appear

### ISSUE THREAD

**Issue by scbarton** [retorquere/zotero-better-bibtex#2879]
### Debug log ID

F23I56JV-refs-euc/6.7.192-6

### What happened?

I can't seem to get the CAYW window to appear using BBT.  I have been using this command in the terminal:

```
/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?format=pandoc&brackets=True'
```

but no window appears. The zotero integration with MS Word is working, because I can get a CAYW window in Word.

Thanks for any and all assistance!

**Comment by retorquere** [comment]
Can you check if the style you have configured for quickcopy (`https://csl.mendeley.com/styles/6316143/thesis`) is actually installed, and if not, select another style and try again?

**Comment by scbarton** [comment]
Yes, I'm able to copy and paste with that style.

I did see the Javascript error `"this.style is undefined"` and tried selecting other styles (which I also know are installed.)  In both cases, I could generate a bibliography in Word, I could copy a bibliography with Edit > Copy Bibliography, and I could generate a bibliography in Preferences > Cite > Styles > Style Preview.   

Thanks for your help on this!

**Comment by scbarton** [comment]
I did some troubleshooting. After re-saving and downloading a custom style (with an old mendeley URL) that was used in my "Item Format" in Settings > Export > Quick Copy, everything is working.
