### ISSUE TITLE
BBT hangs on startup at "translators" stage

### ISSUE THREAD

**Issue by dcconsta** [retorquere/zotero-better-bibtex#2880]
### Debug log ID

D1359076965

### What happened?

On startup, BBT fails to initialize completely (hangs at "translators"). The interface is partially responsive (existing items remain accessible) but it is impossible to add new items.
![BBT_hang](https://github.com/retorquere/zotero-better-bibtex/assets/169903154/98064e4c-a4ae-4dd7-9496-2a786fa635a2)
Aside from the D... version, I cannot generate a debug report (either from the right-click menu or with file.io), so I'm attaching the locally saved output (obtained by restarting Zotero with debugging enabled):
[Debug Output.txt](https://github.com/retorquere/zotero-better-bibtex/files/15321119/Debug.Output.txt)

**Comment by retorquere** [comment]
Can you try again with build 6254 and attach a new log?

Does the file.io option not work for you, or does it not appear?

**Comment by retorquere** [comment]
It wasn't a solution, sorry, it was just for diagnosis. A new build will drop soon, still just for diagnosis, I expect that will put up a notification saying "Failed to load translators", with a reason, I need that reason. The notification will stay up 8 seconds

I expect it will proceed to load BBT, but BBT will not be functional (not reliably anyway). I think I know where it stalls, this build should confirm that, and then I'll have to talk about the Zotero crew; if my diagnosis is correct, I am supposed to wait for something in Zotero to finish, but that wait is not returning.

**Comment by dcconsta** [comment]
There is no notification. At startup, BBT goes quickly through all the steps and then Zotero seems functional (items can be added), and even BBT works partially (I can export items, but not refresh keys, for instance).
Here is the new log, in case it should help.
[Debug Output_3.txt](https://github.com/retorquere/zotero-better-bibtex/files/15323323/Debug.Output_3.txt)

**Comment by retorquere** [comment]
A new build will drop shortly that will put up about 8 notices. The last 3 you see are relevant (I don't know what they'll say yet).

**Comment by retorquere** [comment]
Are you on Zotero 6 or 7?

**Comment by dcconsta** [comment]
I'm on Zotero 6.0.36. Here is the record of the startup process and the corresponding log.
[Debug Output_4.txt](https://github.com/retorquere/zotero-better-bibtex/files/15331239/Debug.Output_4.txt)
https://github.com/retorquere/zotero-better-bibtex/assets/169903154/c1fef36a-a122-4ed0-9fdc-610a98a9aec0

**Comment by retorquere** [comment]
This adds new logging. A single message should pop up (content doesn't matter, but I need to know whether you see it), again not everything will work, but you should be able to send a normal debug log.

**Comment by dcconsta** [comment]
There is indeed a brief popup message "Better BibTex: Assigning citation keys <new line> Ready". The main Zotero windows appears 30s later. Here is the log.
[Debug Output_5.txt](https://github.com/retorquere/zotero-better-bibtex/files/15332863/Debug.Output_5.txt)

**Comment by dcconsta** [comment]
Here is the startup log using build 6263.
[Debug Output_6.txt](https://github.com/retorquere/zotero-better-bibtex/files/15349646/Debug.Output_6.txt)

**Comment by retorquere** [comment]
Confirms the problem. It seems Zotero doesn't return from translator initialization. I've asked about it [here](https://groups.google.com/g/zotero-dev/c/Vcg_RH8IjLE) -- in the interim, I'll leave this in place so that BBT can mostly start.

**Comment by dcconsta** [comment]
Thanks for all the work! BBT is mostly functional on my system. Contrary to a previous statement, key refreshing does work. It is just that the field is not updated in the middle panel until one navigates away from the collection.

**Comment by retorquere** [comment]
The middle pane would be an entirely different problem.

**Comment by dcconsta** [comment]
I have upgraded and everything seems to work OK, aside from the delayed key refresh (see above). To be fair, however, I see no obvious changes with respect to build 6263. I'll let you know in case of any anomaly.
A big thank you for your reactivity!

**Comment by phockett** [comment]
Just came to say that I had the same issue after updating Zotero to v6.0.36, but it's now working properly again after today's update (I'm showing BBT build 6.7.201 in the add-ons info), and I haven't noticed any other issues. Thanks for the efforts!

Also: profuse thanks for BBT in general - an indispensable tool, and Zotero would not be usable for me without it.

**Comment by retorquere** [comment]
Thanks guys! It's been a stressful few days, so the kind words are much appreciated. I try not to be a disruption, but Zotero is in flux, and BBT has pretty complex interactions with its internals... What I have in place now is a workaround, Zotero is looking into the underlying issue, and I hope to have a proper fix soon. The workaround is be fine, but it's not elegant.
