### ISSUE TITLE
Preprint with status in extra fails to export

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#2881]
### Debug log ID

8PKJSPS3-apse/6.7.192-6

### What happened?

"File" > "Export Library . . . " > Select Better BibLaTeX and "keep updated" > Press "OK" >  Choose file > "An error occurred while trying to export the selected file".

There is a bibtex file generated and kept updated by BBT in the same folder, which is kept updated.  But, I no longer be able to generate a biblatex file.

Before this happened, I had noticed that the biblatex file hadn't been updated. I went to the BBT preferences, selected the biblatex file and pressed the "Update Now" button but the file wasn't updated. I repeated this a few times but the file wasn't updated.  So, I deleted the file and pressed the "Update Now" but the file wasn't generated. I then restarted Zotero and did the same but the file wasn't generated.

**Comment by retorquere** [comment]
Can you select the auto-export library/collection (whichever it ends up being), right-click it, and send a debug log from that? It will have an ID with `-refs-` in it.

**Comment by ryofurue** [comment]
Thank you as always for your prompt help, but

> Can you select the auto-export library/collection (whichever it is in your case), right-click it, and send a debug log from that?

I'm sorry that I can't figure out exactly what I'm supposed to do.  Can you break it down to a step-by-step set of instructions?  I repeated the procedure I described in my initial report, but I didn't know where, when, or what to right-click.

**Comment by retorquere** [comment]
Oh I see you only have library auto-exports set up. Just right-click your library in the top left, select Better BibTeX -> Send debug log.

**Comment by ryofurue** [comment]
HZ8H8PJX-refs-apse/6.7.192.2881.6262-6

> Just right-click your library in the top left, select Better BibTeX -> Send debug log.

The above log ID is the result of that.  I hope it helps.

In the meanwhile, the [test build 6.7.192.2881.6262](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.192.2881.6262.xpi) seems to have solved my original problem. I can now generate biblatex files.

**Comment by Baumtomographie** [comment]
I, too, cannot export to Better BibTeX anymore: debug log ID: AAS9D6Q2-euc/6.7.192-6.

"File" > "Export Library . . . " > Select Better BibLaTeX > Press "OK" > Choose file > "An error occurred while trying to export the selected file".

File is created with size 0.

**Comment by retorquere** [comment]
@Baumtomographie please right-click the problematic items and send a debug log from the popup menu. The ID will have `-refs` in it.

**Comment by Baumtomographie** [comment]
The errors I get are:
"[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 883}]
[JavaScript Error: "out of memory"]
[JavaScript Error: "out of memory"]
[JavaScript Error: "XML Parsing Error: no root element found
Location: https://s3.eu-central-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "https://s3.eu-central-1.amazonaws.com/ping" line: 1}]
[JavaScript Error: "XML Parsing Error: no root element found
Location: https://s3.ap-southeast-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "https://s3.ap-southeast-1.amazonaws.com/ping" line: 1}]
[JavaScript Error: "out of memory"]
[JavaScript Error: "out of memory"]"

I'm sorry, but I don't know where to find these "problematic items". The bib-file is empty.

**Comment by retorquere** [comment]
Just select your library, right-click it, and send a debug log from the popup menu. But you may be suffering #2315.

**Comment by retorquere** [comment]
@ryofurue there's still a bug (`pubstate` has the wrong value), a new version will drop soon that addresses it. Can you do me a favor? Can you export the item titled

> Comparing the linear and nonlinear buoyancy-driven circulation

to "BetterBibTeX JSON" and "Zotero RDF", zip them up, and attach the zip here?

**Comment by Baumtomographie** [comment]
The debug log is empty, so there is no send option available.

**Comment by retorquere** [comment]
Can you show a screenshot from that? The debug log is never empty, because I always add my own information to the top.

**Comment by retorquere** [comment]
But have you disabled the cache as described in #2315?

**Comment by ryofurue** [comment]
> @ryofurue there's still a bug (pubstate has the wrong value), a new version will drop soon that addresses it. Can you do me a favor? Can you export the item titled
>
> >Comparing the linear and nonlinear buoyancy-driven circulation
>
> to "BetterBibTeX JSON" and "Zotero RDF", zip them up, and attach the zip here?

Here it is.

[comparing-linear-and-nonlinear.zip](https://github.com/retorquere/zotero-better-bibtex/files/15344965/comparing-linear-and-nonlinear.zip)

But these files were generated on a different machine from the one I made my initial report on.  My Zotero databases are sync'ed across all my machines, though.

**Comment by retorquere** [comment]
Ah no I need it from the system you sent the debug logs from. The bug is fixed, but the debig log had the attached files in a text encoding I didn't expect. I want to see whether that's something my debug log does, or whether it's something zotero does. But that is system bound.

Or maybe it occurs on both systems. Can you also send a debug log for that item on the system you exported these zipped files from?

**Comment by retorquere** [comment]
It shouldn't be happening at all, and I've had an Intel Mac, now have an m2 Mac, and I've never been able to replicate it. What locale are your machines configured for?

**Comment by retorquere** [comment]
Thanks. The exports are OK, so that means I'm mutilating the debug log myself. `DQWXFMSK-refs-apse/6.7.192-6` has the same issue, and the files in the zipfile are OK. I'll look into this separately -- for now, the problem we started with is solved. I'll cut a new release, you'll be upgraded automatically.

**Comment by retorquere** [comment]
@Baumtomographie I can't move forward on your case without more input.

**Comment by ryofurue** [comment]
> What locale are your machines configured for?

I'm curious myself!  I migrated from Linux to Mac more than 10 years ago. When I was using Linux, I roughly knew how system locale was set (/etc/ . . . ) and how the user overrides it.

Internally, Macs should be the same, but I've never looked into it.  You just open the shiny white box of your new Mac machine, switch it on, and answer several questions.  Then, you are good to go.  During this setup, I just choose "English (US)".

For my command shell, I set 
    LC_ALL="en_US.UTF-8"
    LC_COLLATE="C"

but I don't think these would affect Zotero because I launch Zotero by double-clicking on it from "Applications" on Finder.

If you (we) are suffering from some weird character coding, does it come from the Zotero browser plugin or from the webbrowser or from the publisher who provides the metadata?

**Comment by retorquere** [comment]
I don't think it's a encoding problem anymore, your files showed that. I have a fix lined up but I'm going to be tied up for a few more hours - I'd hugely appreciate it if you could test it when I have it done.

**Comment by retorquere** [comment]
Yeah, got it, I was mutilating the logs. That's fixed now -- thanks for the help

**Comment by retorquere** [comment]
@Baumtomographie please open a new issue for the problem you are experiencing.

**Comment by ryofurue** [comment]
When I launched Zotero ten minutes ago, BBT was updated, and I restarted Zotero.  I then went to the BBT preferences and pressed the "Export now" button. The biblatex file was renewed.  So everything seems to be working normally.
