### ISSUE TITLE
Automatic git export not working on Automatic export of Collection on Mac to Overleaf

### ISSUE THREAD

**Issue by SebusFu** [retorquere/zotero-better-bibtex#2882]
### Debug log ID

XU4TTGU2-euc/6.7.193-6

### What happened?

I followed the instructions to use the automatic export with auto push to git (overleaf git in my case). my .git/config says true for push. 
The automatic export to .bib file works, but is not committed. If I do pull, commit, push in terminal on folder I get the expected result. 
I did not find any additional information that the auto process is done or not. I restarted Zotero and terminal a few times, without any change in result.

**Comment by retorquere** [comment]
Can you test build 6273?

**Comment by SebusFu** [comment]
Thanks a lot, this works. It now asks for the password of git.overleaf.com and automatic syncing is working. Thanks for your quick help! Do you need any further information?

**Comment by retorquere** [comment]
No, just conformation that it works is good.

**Comment by retorquere** [comment]
A new release will go out today.

**Comment by retorquere** [comment]
Can you try this build to see if it solves the problem for you?

**Comment by jooyoungseo** [comment]
It's still not working on my end, either: Z7FMWNCU-euc/6.7.207-7

**Comment by jooyoungseo** [comment]
The new update is not staged and commited automatically:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/19754711/9239dafd-3714-4d44-8d4c-528b8f539cb0)

**Comment by retorquere** [comment]
> It's trying to run
> 
> ```
> /usr/bin/git -C /Users/sebastianschaper/Diss/Paper/Theory-nkd-decoupling/OverleafProject/65d72359067c2d4e421e8a52 commit -m "BibTeX updated by Better BibTeX for Zotero"
> ```
> 
> can you run that from a directory that is *not* `/Users/sebastianschaper/Diss/Paper/Theory-nkd-decoupling/OverleafProject/65d72359067c2d4e421e8a52` and see what it reports.

Please try this.

**Comment by jooyoungseo** [comment]
@retorquere I am sorry, but I am a different user who's experiencing this issue on Windows. I have left my log above. Your comment does not apply to me.

**Comment by retorquere** [comment]
@jooyoungseo I see no auto-export activity in your log. You have to trigger an export so the log will show what goes wrong.

**Comment by jooyoungseo** [comment]
@retorquere I have triggered again in this log: NE57HNEI-euc/6.7.207-7

**Comment by retorquere** [comment]
@jooyoungseo please try this in `cmd.exe` in a directory that is **not** `C:\overleaf\assets24\maidr`:

```
"C:\Program Files\Git\cmd\git.EXE" -C C:\overleaf\assets24\maidr checkout references\hci.bib
```

**Comment by jooyoungseo** [comment]
@retorquere Thanks. Still does not work: IUKLYCBX-euc/6.7.207-7                                                                                                                                                       

```bash
AdAdministrator: C:\WINDOWS\system32\cmd.exe
                                                                                                                                                       
                    
C:\>"C:\Program Files\Git\cmd\git.EXE" -C C:\overleaf\assets24\maidr checkout references\hci.bib                                                       
                    
Updated 1 path from the index                                                                                                                          
                    
                                                                                                                                                       
                    
C:\>                                                                                                                                                   
```

**Comment by retorquere** [comment]
> AdAdministrator: C:\WINDOWS\system32\cmd.exe

Is this an administrator shell? If so, please run in a regular shell

**Comment by jooyoungseo** [comment]
No. Executing the command in the user shell does not make any change. I have removed all the  connected auto-exported bibs and started from scratch, but still see the same issue: TK8SMITH-euc/6.7.207-7

**Comment by retorquere** [comment]
Please send a new debug log from 6464. This is not expected to fix anything, it just adds more information to the log.

**Comment by jooyoungseo** [comment]
Yes, here you go: 69FTRVHD-euc/6.7.207.2882.6464-7

**Comment by jooyoungseo** [comment]
Yes, here you go: 69FTRVHD-euc/6.7.207.2882.6464-7

**Comment by retorquere** [comment]
Build 6467 will show the git output in a window, I need to see what it is. You might want to use a screen recorder, I don't know how long the window stays up.

**Comment by jooyoungseo** [comment]
Here is a new log: VE46GRJM-euc/6.7.207.2882.6467-7

Below is the screen capture:

![Recording 2024-06-23 at 14 33 08](https://github.com/retorquere/zotero-better-bibtex/assets/19754711/f835a7cf-ff67-4f1a-b483-b40e17d72880)

**Comment by retorquere** [comment]
![image](https://github.com/retorquere/zotero-better-bibtex/assets/132108/b1a4691d-30e7-4c31-99eb-69ed9cf678d4)

**Comment by retorquere** [comment]
It looks like you're running some things as admin, others as a regular user. That's a really hard environment to support.

**Comment by retorquere** [comment]
@SebusFu if you don't respond in going to have to close this issue.

@jooyoungseo you have a rights issue. If you've resolved that, and it still doesn't work, please open a new issue.

**Comment by retorquere** [comment]
@SebusFu if you don't respond in going to have to close this issue.

@jooyoungseo you have a rights issue. If you've resolved that, and it still doesn't work, please open a new issue.

**Comment by retorquere** [comment]
@jooyoungseo and please don't follow the suggestion by git above. That would just have git proceed with the problem present, and I don't want to debug windows ownership issues. You have mixed ownership of that repo, that's not supported. The git repo should be unambiguously owned by the user Zotero runs as.

**Comment by jooyoungseo** [comment]
@retorquere Thanks for your help with debugging this issue. I have resolved this on my end. However, I think other Windows users who save their repo under C drive will face the same issue because C drive is owned by admin by default. Zotero, on the other hand, is run with the current user power. To address this issue, users will have to either adjust their `zotero.exe` property to elevate the run permission to admin or add the repo under C drive to their git safe.directory list.

Another possible issue that I have found that the bbt push option needs to be removed from the git global level. I have noticed that auto push does not work when the option exists in the git global config.

I have jot down the following simple batch script for my own use that can be executed inside the target repo and this addresses the issue above.

`zotero_bbt_auto_push.cmd`:

```bash
@echo off

rem Allow Zotero to push updated references
rem Remove bbt setting from `--global` git config because it must be set on a local level
git config --global --unset zotero.betterbibtex.push
git config zotero.betterbibtex.push true

setlocal enabledelayedexpansion

rem Get the current directory
set "dir=%cd%"

rem Add the current directory as a safe directory in Git
git config --global --add safe.directory "!dir!"

endlocal
```

**Comment by retorquere** [comment]
> @retorquere Thanks for your help with debugging this issue. I have resolved this on my end. However, I think other Windows users who save their repo under C drive will face the same issue because C drive is owned by admin by default. 

You can, however, create a directory there that as admin and then change ownership to the regular user.

> Zotero, on the other hand, is run with the current user power. To address this issue, users will have to either adjust their `zotero.exe` property to elevate the run permission to admin

**PLEASE DON'T DO THIS**. This will get you in all sorts of problems since now the Zotero directory will also be admin-owned, and this will make diagnosis nasty work.

If you are going to do this nonetheless (and I'm saying: don't), and you want to report problems for plugins or Zotero itself, **mention that you are running Zotero as admin**, because a) that complicates everything, and b) it is guaranteed to be unexpected to the developer. That is aside the fact that just generally, running things as admin that are not directly related to system administration is not advisable.

> or add the repo under C drive to their git safe.directory list.

Also no. Just create a directory on C:\, give ownership to the regular user, and do all your work as non-admin in that directory.
  
> Another possible issue that I have found that the bbt push option needs to be removed from the git global level.

It doesn't need to be removed, but BBT won't read it there.

> I have noticed that auto push does not work when the option exists in the git global config.

That is correct.

**Comment by SebusFu** [comment]
Hi, sorry for the late response, I've been away. It currently works for me. Thank you very much for your great support and the great tool!
