### ISSUE TITLE
Zotero 7: Incorrect cite key temporarily displayed after adding item

### ISSUE THREAD

**Issue by jryans** [retorquere/zotero-better-bibtex#2884]
### Debug log ID

ULF39FN5-refs-euc/6.7.197-7

### What happened?

Zotero 7.0.0-beta.78+5be5ca941
BBT 6.7.197 (and also debug build 6.7.192.2522.6245)

STR:

1. Open several PDF tabs in Zotero (I have 4 open at the moment)
2. Go to https://pola.rs/, save this site via the connector
3. The parent item is created, and initially the correct cite key is shown
4. A few seconds later, the web site attachment is added, and around then the wrong cite key appears

It's hard to relay the content of all of the BBT debug build notifications, as they are a lot of the flashing on screen. It looks like when the website attachment is added, BBT seems to think Zotero somehow cycled through all of the open PDF tabs as well. The newly added item ends up displaying the cite key for the 3rd open PDF tab in my case.

**Comment by jryans** [comment]
The issue still occurs with the test build above. I sent an additional debug log for that build: E4DPEDAU-refs-euc/6.7.197.2884.6281-7.

**Comment by jryans** [comment]
The issue still occurs with the latest test build, here's a fresh debug log: ZF7UKZNE-refs-euc/6.7.197.2884.6284-7.

With this round of testing, I noticed the item happened to display at least 2 different incorrect cite keys. (The final cite key displayed is still incorrect.)

**Comment by retorquere** [comment]
I can reproduce it now, but as far as I can tell, this is a [Zotero bug](https://groups.google.com/g/zotero-dev/c/wirqnj_EQUQ/m/VgfFSTUdAQAJ).

**Comment by windingwind** [comment]
Not sure if I understand this issue correctly. #2922 should fix https://forums.zotero.org/discussion/116309/citation-key-not-displayed , which presumably is another form of this issue.

**Comment by retorquere** [comment]
That was indeed the case; this fix will be in the next release, which goes out before next Wednesday.

**Comment by jryans** [comment]
Yes, I agree this appears to be fixed when using Zotero 7.0.0-beta.98+0b3eda5d8 and BBT 6.7.214. Thanks all! 😄
