### ISSUE TITLE
[Zotero 7 Beta] Feeds Item Pane not updating when switching items

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2885]
### Debug log ID

5FC5YJXD-euc/6.7.197-7

### What happened?

Here are some of the problems in the latest build:

1. The metadata of feeds items does not update in the Item Pane when switching item in the Feeds
2. If I switch to My Library and then to the Feeds, I get:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/b18fb679-5c73-4a0e-8672-e244c476ad9c)

3. The BBT extension does not appear in the Settings.
4. The Export and Cite cannot be displayed:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/f7747967-d94b-46f7-b691-86b0177a8892)

5. Send debug log to file.io does not do anything (when I see it)

3-5 are probably stuck on loading BBT.

Some of the errors:
```
1716230245786	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1716230246625	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1716230249616	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "Error: no citation key for 56309" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 83376}]

[JavaScript Error: "no citation key for 56309" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 83376}]

[JavaScript Error: "TypeError: Components.classes['@mozilla.org/embedcomp/prompt-service;1'] is undefined" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 8687}]

[JavaScript Error: "no citation key for 56309" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 83376}]

[JavaScript Error: "Error: no citation key for 56340" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 83376}]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 687}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:687:7


[JavaScript Error: "Error: no citation key for 56345" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 83376}]

[JavaScript Error: "Error: no citation key for 56345" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 83376}]
```

BBT version 6.7.197
Zotero 7.0.0-beta.79+95d5a5417 (64-bit)
Windows 10

**Comment by mjthoraval** [comment]
I have narrowed down the problem. It appears only if I use the new feature to view the header of the Item Pane as "Bibliography Entry":
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/1d85eca2-5db6-400f-a348-e5e69406b35f)

I am using the citation style provided by adamsmith here:
https://forums.zotero.org/discussion/comment/463228/#Comment_463228

The other 2 view options do not trigger the problem.

**Comment by retorquere** [comment]
How do I configure this? I don't see this popup menu.

**Comment by retorquere** [comment]
A new build will drop here that fixes file.io, and also adds new logging.

**Comment by mjthoraval** [comment]
> How do I configure this? I don't see this popup menu.

It is the new feature announced here: https://forums.zotero.org/discussion/114422/available-for-beta-testing-customizable-item-pane-header
You can get it from a right click on the new header of the Item Pane.

**Comment by mjthoraval** [comment]
Here is a new Debug Log ID with the test build: VYKD5I69-euc/6.7.198.2885.6287-7
If I use the "Bibliography Entry" view:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/79d0a15d-1ea0-4c03-b058-9a6422907996)
If I use the "Title" view:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/0981ec20-3278-4d1c-a72d-b437a8715791)

**Comment by retorquere** [comment]
Yeah but I don't know how to switch between those two modes. I see you have a "View as" menu somewhere but I don't see that.

**Comment by retorquere** [comment]
Oh nm, I wasn't on the latest beta

**Comment by mjthoraval** [comment]
Thank you. This build fixes the problems.

**Comment by retorquere** [comment]
Super -- thanks!

**Comment by retorquere** [comment]
apparently it's not solved for everyone. Can you join 2887 if you're having these problems again?
