### ISSUE TITLE
[Zotero 7 Beta] BBT cannot load after update

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2886]
### Debug log ID

CGCLUU35-fio-QvFxDXHpZxk2

### What happened?

Just  after updating the [last bug](https://github.com/retorquere/zotero-better-bibtex/issues/2885), I got a an error that BBT could not load.
I saved the debug log ID (CGCLUU35-fio-QvFxDXHpZxk2), disabled BBT are re-enabled it.
Now it works. But the debug log ID may still be useful?

BBT version 6.7.198.2885.6293
Zotero 7.0.0-beta.79+95d5a5417 (64-bit)
Windows 10

**Comment by mjthoraval** [comment]
I cannot reproduce, so I don't know what happened.
You can close the issue if the debug log is not useful.

**Comment by retorquere** [comment]
Would have loved to see the log -- could it be you visited file.io after upload? For security considerations, the logs from file.io are deleted after anyone downloads them.

**Comment by mjthoraval** [comment]
I am in the broken state again.
The "Send debug log to file.io" does not work.
I keep it this way in case I can report anything useful to you.

**Comment by retorquere** [comment]
Do you see any errors in the Zotero log viewer that might indicate why file.io isn't working?

**Comment by mjthoraval** [comment]
Nothing moves when I try to use the "Send debug log to file.io".

```
1716243260691	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1716243261580	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1716243261599	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1716243263156	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 687}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:687:7


appName => Zotero, version => 7.0.0-beta.79+95d5a5417, os => Windows 10.0 19045, locale => en-GB, extensions => Better BibTex for Zotero (6.7.198.2885.6293, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Open PDF for Zotero (0.0.11, extension, disabled), Zotero Better Authors (4.1.3, extension, disabled), ZoteroPreview (0.7.8, extension, disabled), Translate for Zotero (1.1.0-beta.41, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.39, extension, disabled), Zotero OCR (0.7.2, extension, disabled), Notero (0.5.16, extension, disabled), Zotero Attanger (1.2.2, extension, disabled), Better Notes for Zotero (1.1.4-beta.73, extension, disabled)
```

**Comment by retorquere** [comment]
Did you see a message saying `Zotero translator init timed out`?

**Comment by retorquere** [comment]
You don't need to keep it this way, I need to go to sleep, will be back in the morning.

**Comment by mjthoraval** [comment]
I had 2 popup windows, one saying some "[...] Ready" and then another one with an error.
I could not catch them.
I will keep it this way and be back in the morning.
Thanks!

**Comment by mjthoraval** [comment]
Ok, got it this time:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/c5a5b01d-9425-4134-8990-f20d99c2377f)

And the debug log ID after the screenshot: BIWBP79S-fio-bu5VcpcujZIA

**Comment by mjthoraval** [comment]
After update:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/c216bdb2-2773-4c7e-98bf-06ad2ee8c2f4)

8A7XNEUE-fio-WuMbi1QF1kSB

**Comment by mjthoraval** [comment]
This one seems to solve the problem of BBT not loading.
I have restarted a few times without seeing the issue anymore.
Thank you very much!

It can take a while to load, but it is similar time as without BBT:
UUPP4VGJ-fio-34hgWdHws0Oq
N9CDTMGC-euc/6.7.199.2886.6298-7

**Comment by retorquere** [comment]
^&*#! will these problems never stop... anything relevant you see in the log viewer? If you install https://github.com/retorquere/zotero-debug-log alongside, does file.io work?

**Comment by mjthoraval** [comment]
Waiting a bit, I got these:
```
(3)(+0013810): {better-bibtex startup: [translators]} +288006 idle: Tue May 21 2024 11:09:08 GMT+0200 (Central European Summer Time), save-database idle

(3)(+0000000): {better-bibtex startup: [translators]} +1 emit: better-bibtex event emit idle {"state":"idle","topic":"save-database"}

(3)(+0012980): {better-bibtex startup: [translators]} +12979 idle: Tue May 21 2024 11:09:21 GMT+0200 (Central European Summer Time), save-database active

(3)(+0000000): {better-bibtex startup: [translators]} +1 emit: better-bibtex event emit idle {"state":"active","topic":"save-database"}

(3)(+0034627): {better-bibtex startup: [translators]} +34626 idle: Tue May 21 2024 11:09:56 GMT+0200 (Central European Summer Time), save-database idle

(3)(+0000000): {better-bibtex startup: [translators]} +1 emit: better-bibtex event emit idle {"state":"idle","topic":"save-database"}

(3)(+0001911): {better-bibtex startup: [translators]} +1911 idle: Tue May 21 2024 11:09:58 GMT+0200 (Central European Summer Time), save-database active

(3)(+0000000): {better-bibtex startup: [translators]} +0 emit: better-bibtex event emit idle {"state":"active","topic":"save-database"}
```

**Comment by mjthoraval** [comment]
If the BBT plugin can load, the debug log can finally be sent: FJLZF5QX-fio-ZytQtgpWajMT
The debug log from zotero-debug-log still does not work:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/b94fa059-ef33-4f3b-af3f-f61832b8d8bb)

**Comment by retorquere** [comment]
What platform are you on?

**Comment by mjthoraval** [comment]
I am on Windows 10.
Here is what I get from "Restart with Logging Enabled..." in the BBT debug output log window: 7YYQK4XW-euc/6.7.200.2886.6306-7
But this time it was successful.

I have restarted the computer. It is now successfully loading the last few times I have tried.
I will update here if it comes back again.

**Comment by mjthoraval** [comment]
Note that that "Send debug log to file.io" popup window only appears when the plugin is fully loaded (the Citation key column appears in the Items Tree), even if I click on it very early in the startup process. This is probably why I cannot get the debug ID when BBT does not load.

**Comment by retorquere** [comment]
` 7YYQK4XW-euc/6.7.200.2886.6306-7` gave me something useful, new build incoming.

> Note that that "Send debug log to file.io" popup window only appears when the plugin is fully loaded 

You mean without zotero-debug-log installed. This is so weird. It's the first thing I do. Load order of plugins is not deterministic, so with zotero-debug-log installed it could be that just zotero-debug-log loads after BBT. But BBT also has file.io registration, and that should be the first thing it does. It also should disappear after 15s.

**Comment by mjthoraval** [comment]
Same again...
I have updated BBT, then activated it (only BBT). The Citation key column appeared before restart.
Then I restart, and BBT does not load anymore.

Same symptoms as mentioned before, except that the Feeds are working properly now: https://github.com/retorquere/zotero-better-bibtex/issues/2885

1) The BBT extension does not appear in the Settings.

2) The Export and Cite sections do not display in the Settings:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/9acf2a44-c033-4527-a724-cfab3ac2c487)

3) "Send debug log to file.io" -> "Better BibTeX" does not do anything. Also nothing appears in the Debug Output log.

4) Here are the errors I get in the debug output of Zotero:
```
1716290242965	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1716290243575	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1716290243587	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1716290244290	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "Translators not yet loaded"]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 687}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:687:7


appName => Zotero, version => 7.0.0-beta.80+9de70613a, os => Windows 10.0 19045, locale => en-GB, extensions => Better BibTex for Zotero (6.7.200.2886.6307, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Open PDF for Zotero (0.0.11, extension, disabled), Zotero Better Authors (4.1.3, extension, disabled), ZoteroPreview (0.7.8, extension, disabled), Translate for Zotero (1.1.0-beta.41, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.39, extension, disabled), Zotero OCR (0.7.2, extension, disabled), Notero (0.5.16, extension, disabled), Zotero Attanger (1.2.2, extension, disabled), Better Notes for Zotero (1.1.4-beta.73, extension, disabled), Debug Log for Zotero (2.0.17, extension, disabled)
```

**Comment by mjthoraval** [comment]
I have activated the plugin "Debug Log for Zotero" version 2.0.17.
Restarted Zotero.
Same problem again.
Both options "Send debug log to file.io" -> "Debug Log" & "Better BibTeX" do not do anything and do not trigger any message in the Debug Output log.

The new Debug Ouptut content:
```
1716290937236	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1716290937955	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1716290937967	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1716290937968	addons.webextension.debug-log@iris-advies.com	WARN	Loading extension 'debug-log@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1716290939221	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "SyntaxError: redeclaration of const Zotero" {file: "chrome://zotero/content/customElements.js" line: 1}]
@chrome://zotero/content/customElements.js:1:1
@chrome://zotero/content/update/update-header.js:8:25


[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 687}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:687:7


appName => Zotero, version => 7.0.0-beta.80+9de70613a, os => Windows 10.0 19045, locale => en-GB, extensions => Debug Log for Zotero (2.0.17, extension), Better BibTex for Zotero (6.7.200.2886.6307, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Open PDF for Zotero (0.0.11, extension, disabled), Zotero Better Authors (4.1.3, extension, disabled), ZoteroPreview (0.7.8, extension, disabled), Translate for Zotero (1.1.0-beta.41, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.39, extension, disabled), Zotero OCR (0.7.2, extension, disabled), Notero (0.5.16, extension, disabled), Zotero Attanger (1.2.2, extension, disabled), Better Notes for Zotero (1.1.4-beta.73, extension, disabled)
```

**Comment by mjthoraval** [comment]
Restart with Logging Enabled...
-> BBT can finally load: P7E6N3FE-euc/6.7.200.2886.6307-7

**Comment by retorquere** [comment]
There's no BBT activity in this log. Can you try [this](https://github.com/retorquere/zotero-better-bibtex/issues/2785#issuecomment-1934245288) way of starting zotero and generating a log?

**Comment by mjthoraval** [comment]
This does not seem to work:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/186b8967-c0c3-4637-9342-e672e1dce98f)

The content of "Transcript.txt":
```
**********************
Début de la transcription Windows PowerShell
Heure de début : 20240521133947
Nom d'utilisateur : MJ-DELL\mjthoraval
Utilisateur runAs :  MJ-DELL\mjthoraval
Nom de la configuration : 
Ordinateur : MJ-DELL (Microsoft Windows NT 10.0.19045.0)
Application hôte : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ID de processus : 19132
PSVersion: 5.1.19041.4412
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.4412
BuildVersion: 10.0.19041.4412
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcription démarrée, le fichier de sortie est C:\Users\mjthoraval\Desktop\transcript.txt
PS>Erreur de terminaison (Start-Process) : « Impossible d’exécuter cette commande en raison de l’erreur : Le fichier spécifié est introuvable. »
Start-Process : Impossible d’exécuter cette commande en raison de l’erreur : Le fichier spécifié est introuvable.
Au caractère Ligne:2 : 1
+ Start-Process -FilePath "C:\Program Files (x86)\Zotero\zotero.exe" -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
Start-Process : Impossible d’exécuter cette commande en raison de l’erreur : Le fichier spécifié est introuvable.
Au caractère Ligne:2 : 1
+ Start-Process -FilePath "C:\Program Files (x86)\Zotero\zotero.exe" -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

C:\Users\mjthoraval>
PS>Start-Transcript -Path "$HOME\Desktop\transcript.txt"
Start-Process -FilePath "C:\Program Files\Zotero\zotero.exe" -ArgumentList "-ZoteroDebugText" 
**********************
Fin de la transcription Windows PowerShell
Heure de fin : 20240521134040
**********************
```

**Comment by mjthoraval** [comment]
I have waited more than 5 minutes this time before sending the `Stop-Transcript` command.
It is still empty:
```
**********************
Début de la transcription Windows PowerShell
Heure de début : 20240521135729
Nom d'utilisateur : MJ-DELL\mjthoraval
Utilisateur runAs :  MJ-DELL\mjthoraval
Nom de la configuration : 
Ordinateur : MJ-DELL (Microsoft Windows NT 10.0.19045.0)
Application hôte : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ID de processus : 19132
PSVersion: 5.1.19041.4412
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.4412
BuildVersion: 10.0.19041.4412
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcription démarrée, le fichier de sortie est C:\Users\mjthoraval\Desktop\transcript.txt
C:\Users\mjthoraval>
PS>Stop-Transcript
**********************
Fin de la transcription Windows PowerShell
Heure de fin : 20240521140241
**********************
```

**Comment by mjthoraval** [comment]
And as reported before, disabling the plugin and re-enabling it is enough to make it work again.

**Comment by mjthoraval** [comment]
> ` 7YYQK4XW-euc/6.7.200.2886.6306-7` gave me something useful, new build incoming.
> 
> > Note that that "Send debug log to file.io" popup window only appears when the plugin is fully loaded
> 
> You mean without zotero-debug-log installed. This is so weird. It's the first thing I do. Load order of plugins is not deterministic, so with zotero-debug-log installed it could be that just zotero-debug-log loads after BBT. But BBT also has file.io registration, and that should be the first thing it does. It also should disappear after 15s.

I have tested with only the BBT plugin.

**Comment by mjthoraval** [comment]
Maybe something wrong during the installation of the plugin?

When I enable the plugin, I get in the Debug Output:
```
1716294705044	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1716294705045	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "uncaught exception: undefined"]
```

And when I disable it:
```
[JavaScript Error: "uncaught exception: undefined"]
```

**Comment by retorquere** [comment]
> When I enable the plugin, I get in the Debug Output:

That's because I have 5-part versions for the debug build. It's just a warning.

**Comment by retorquere** [comment]
Windows is such a pain for debugging. Nothing works. And since I've moved to apple silicon, I can't even run vmware for testing.

If you start `cmd` (windows-r, `cmd`), then in that console window, type

```
"C:\Program Files (x86)\Zotero\zotero.exe" -ZoteroDebugText
```

I think a 2nd console window will pop up. In that console window, the logging should appear. I think in the top-left you can select edit-select all, edit-copy -- I don't have access to Windows so I am working from memory here.

**Comment by mjthoraval** [comment]
The command starts Zotero, but I cannot see any other window opening, and nothing in the console window.

**Comment by mjthoraval** [comment]
Got it: https://www.zotero.org/support/debug_output#windows
I have added `-console` to get it to work:
```
"C:\Program Files\Zotero\zotero.exe" -console -ZoteroDebugText
```

[output.txt](https://github.com/retorquere/zotero-better-bibtex/files/15394459/output.txt)

**Comment by retorquere** [comment]
🤬 `Zotero.Translators.init()` is still stuck, even with peeking. And the Zotero crew is not picking up on my support request for this.

**Comment by mjthoraval** [comment]
Let me know if I can do anything to move forward on this.
Hopefully the can identify the problem soon.

**Comment by mjthoraval** [comment]
I have tried all the steps I did before to trigger the bug.
It is still working reliably now.
The problem is fixed I think.

**Comment by retorquere** [comment]
It's a work-around more than a fix, but this gets things going. Can you do one more test for me? open Tools -> Developer -> Run Javascript, check `Run as async function`, and run this:

```
await Zotero.Translators.init()
return 'done'
```

then uninstall BBT, restart Zotero, and repeat these steps. It should in both cases print `done`, but I think at least with BBT installed it will not print anything.

**Comment by retorquere** [comment]
That was not what I expected. I don't know what to make of this. It's most likely a time-sensitive issue then, but `await Zotero.Translators.init()` reliably hangs for you and others when I call it (as I must) in BBT startup.

In any case, I've reported this to the Zotero devs, and in the mean time, I have a workaround.

**Comment by retorquere** [comment]
Can I bother you once more about this? The Zotero crew wants to look into this, but they're asking

> We'd want to see a Debug ID from startup (or debug log sent to [support@zotero.org](mailto:support@zotero.org)) from someone who can reproduce this.

I can produce a build that will reintroduce this problem. I can't reproduce it myself unfortunately.

**Comment by mjthoraval** [comment]
I can reproduce with the test build 6.7.200.2886.6307 above.
Debug ID: D503095659
Or with the new test build 6.7.201.2886.6313:
Debug ID: D813083066

**Comment by mjthoraval** [comment]
On the new test build 6.7.200.2886.6307, the test commands do not work anymore:
```
await Zotero.Translators.init()
return 'done'
```

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/b3a25af4-9083-414c-b3ca-6e5e7feca430)

**Comment by mjthoraval** [comment]
Trying to test again in the test build 6.7.200.2886.6307, to see if I had made a mistake or if there is some randomness also on that, and now the bug is gone...
I actually don't know how to reproduce the bug reliably.

**Comment by retorquere** [comment]
> On the new test build 6.7.201.2886.6313, the test commands do not work anymore:

Both with and without BBT installed?

**Comment by mjthoraval** [comment]
This was with the BBT installed.
When I disable BBT, it works.

**Comment by mjthoraval** [comment]
Here is another Debug ID with a successful loading of BBT: D522314190
It is exactly the same configurations as above:
BBT version 6.7.201.2886.6313
Zotero 7.0.0-beta.80+9de70613a (64-bit)
Windows 10

One of the things that I did since the previous Debug ID is to disable BBT and re-enable it, as was previously reported in the other threads in the forums.
Hopefully the comparison can give some clues on what went different between them.

**Comment by mjthoraval** [comment]
Finally... It took me a long time, but I have managed to get back into the broken mode with the test build 6.7.201.2886.6313.
I was starting to doubt that the bug had ever existed.

Now that I am back into it, note that the connector in Firefox is also broken:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/79f3b91e-64e3-4f41-9d15-a6b4b0914251)

So the problem is likely the same as the other one: https://github.com/retorquere/zotero-better-bibtex/issues/2887

I am still testing, but I think that the way to get back into the broken mode was achieved by enabling and disabling multiple times BBT during the loading of Zotero. On the way, this has send me several nasty errors, including one saying that I had broken the translators, opening this page: https://www.zotero.org/support/kb/unable_to_load_translators_and_styles
Still need to do more testing to confirm this.

**Comment by retorquere** [comment]
> Hopefully the comparison can give some clues on what went different between them.

Thanks man. I hope the Zotero devs can shed some light here. But I think I've also just seen a report pass by where the workaround didn't fix the startup issue :(

> So the problem is likely the same as the other one: #2887

I was hoping they were the same problem, because I have absolutely no idea how that can even happen.

**Comment by retorquere** [comment]
> I am still testing, but I think that the way to get back into the broken mode was achieved by enabling and disabling multiple times BBT during the loading of Zotero.

This is timing sensitive. BBT takes some time to start up and I don't know what Zotero does if you disable a plugin while it's starting.

**Comment by mjthoraval** [comment]
Ok, it indeed seems to be time sensitive.
Here is some of the zoology I got when playing with enabling and disabling the plugin. But after all these, BBT is still able to recover and load properly. I am again not able to reproduce the bug anymore.

Some of the errors obtained when disabling and enabling BBT during the statup of Zotero:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/65fd70b6-b208-48ae-8cec-0989d2859c18)

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/a5f13cb9-7645-46bd-9b9c-50587b4d0a22)

`[JavaScript Error: "Could not stat file(C:\Users\mjthoraval\Zotero\translators\Better BibLaTeX.js) because it does not exist" {file: "resource://gre/modules/Prompter.sys.mjs" line: 1231}]`

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/d721ec5b-2bd1-4c45-af8c-5026692cb782)

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/36ad3d12-3dad-4295-9200-fb0e73d39f8a)

**Comment by retorquere** [comment]
Gotta love transient errors

**Comment by mjthoraval** [comment]
Another remark, probably not important, but this is all I got for now.
Here is the header menu when BBT is running and working:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/006f0c4f-d308-4f00-bfe2-a100b71d8428)

After I disable BBT, it becomes:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/bcea3614-7197-4176-b5cc-be052ec410b2)

**Comment by retorquere** [comment]
Finally one that I can say "that's a zotero bug". The item pane in Zotero 7 is one of the few places where I interact with Zotero strictly through it's formal APIs.

**Comment by mjthoraval** [comment]
A few more just for the record:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/a7e65294-e7d6-4eff-8a39-6ece0374b244)

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/49760cf7-1f7e-4c9b-b575-b7ca2cc38b14)

**Comment by retorquere** [comment]
> A few more just for the record:

Is this after a fast enable/disable? This shouldn't happen if BBT is allowed full startup/shutdown.

**Comment by mjthoraval** [comment]
This is just for a random combination of changing version of BTT, enable/disable of BBT, start/shutdown of Zotero...
If you think that any of these is useful, I can try to reproduce.
But if this is likely happening when doing something very wrong in Zotero, then it is probably what I did.
I still cannot get back to the broken mode now.

**Comment by mjthoraval** [comment]
When I was giving up reproducing the bug, I reactivated all my plugins and restarted Zotero...
And it is back in the broken mode...
I have disabled all the other plugins and kept only BBT -> It stays in the broken mode.
I have disabled the automatic sync to produce a clean Debug Output -> Still in broken mode.
I have no idea what triggered the problem. But at the moment it is reproducible at every restart of Zotero.

At least, I can now produce a new clean Debug ID in the latest beta from "Restart with Logging Enabled...":
Debug ID D472271866
[2024_05_23 - Debug Output BBT Bug.txt](https://github.com/retorquere/zotero-better-bibtex/files/15413371/2024_05_23.-.Debug.Output.BBT.Bug.txt)
BBT version 6.7.201.2886.6313
Zotero 7.0.0-beta.81+721f54fe4 (64-bit)
Windows 10

I have waited 20 minutes this time before submitting it, in case there was any doubt that anything was still happening that could eventually start BBT.

It is easy to solve the problem: disable BBT, restart Zotero, enable BBT, restart Zotero -> The bug is gone.
But I will stay in this broken mode a few more days in case anyone gets some more idea of testing that can be done.

**Comment by mjthoraval** [comment]
Trying to be exhaustive on what I can report.
I confirm that the connector in Firefox is broken again, so most likely the same bug:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/518e5c99-b0a3-4b78-ab46-67de70ebce40)

Here is the Debug Output for refreshing the page and trying to import from Firefox:
Debug ID: D382407023
[2024_05_23 - Debug Output BBT Bug - Connector.txt](https://github.com/retorquere/zotero-better-bibtex/files/15413579/2024_05_23.-.Debug.Output.BBT.Bug.-.Connector.txt)

```
(5)(+0016493): POST /connector/ping HTTP/1.1 Host: 127.0.0.1:23119 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0 Accept: */* Accept-Language: en-GB,en;q=0.5 Accept-Encoding: gzip, deflate, br, zstd Content-Type: application/json X-Zotero-Version: 5.0.124beta4 X-Zotero-Connector-API-Version: 2 Content-Length: 2 Origin: moz-extension://746bca92-3333-4b62-ba48-91b1f8aea7ec Connection: keep-alive Sec-Fetch-Dest: empty Sec-Fetch-Mode: cors Sec-Fetch-Site: same-origin

(3)(+0007186): {better-bibtex startup: [translators]} +23678 idle: Thu May 23 2024 09:56:22 GMT+0200 (Central European Summer Time), save-database idle

(3)(+0000001): {better-bibtex startup: [translators]} +1 emit: better-bibtex event emit idle {"state":"idle","topic":"save-database"}

(3)(+0001309): {better-bibtex startup: [translators]} +1309 idle: Thu May 23 2024 09:56:23 GMT+0200 (Central European Summer Time), save-database active

(3)(+0000000): {better-bibtex startup: [translators]} +1 emit: better-bibtex event emit idle {"state":"active","topic":"save-database"}
```

**Comment by retorquere** [comment]
Thanks! I've added this to the report, you can go back to the regular release for the time being. Zotero said they'd look into the issue, and until that sheds some light on the matter, I don't think there's anything we can do.

**Comment by mjthoraval** [comment]
I have tried restarting the computer and opening Zotero before anything else -> the bug is still here.

BBT is working after a simple disable/enable.
And the bug can be repeated reliably when in the broken mode.
Assuming that something got broken during installation or update of BBT, is there a way to send you the current state of BBT with all parameters? There should be some parameter written somewhere that would be different from a normal installation?

Another observation: When in the broken state, if I click on an item in the Items Tree during loading, with the "Bibliography Entry" mode of the header in the Item Pane, the header will be stuck on "Loading..." for ever:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/1bfc77cc-f67e-4aad-9534-dda032343641)

After waiting for the loading of Zotero to finish, switching item gets the header working again:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/006b09ee-7ad2-4de5-a9c5-ad532b737c59)

**Comment by jdnicholas** [comment]
I'm fairly certain I am experiencing the same issue, where BBT is not starting, I get the error:

> Better BibTeX startup failed
> ReferenceError: name is not defined

With BBT Version 6.7.201, Zotero 7.0.0-beta.81+721f54fe4 (64-bit), on Windows 10.

When I restarted with logging enabled I got this Zotero Debug ID: D205623513, and this for BBT: 667PZV5F-fio-VF7UrGprTIFr.
When I: Disable BBT -> Restart Zotero -> Re-enable BBT -> Restart Zotero, I have this: RHMMIUQ4-fio-IYEiZgHbaZIW

And if I enable Zotero Debug Output Logging I see this when I try to enable:
```
(3)(+0037158): Enabling plugin better-bibtex@iris-advies.com

(3)(+0000006): Calling bootstrap method 'startup' for plugin better-bibtex@iris-advies.com version 6.7.201 with reason ADDON_ENABLE

(2)(+0000000): Plugin better-bibtex@iris-advies.com is missing bootstrap method 'startup' this.warn@chrome://zotero/content/xpcom/zotero.js:1258:71 _callMethod@chrome://zotero/content/xpcom/plugins.js:196:16 onEnabling@chrome://zotero/content/xpcom/plugins.js:463:13 callAddonListeners@resource://gre/modules/AddonManager.sys.mjs:1535:48 callAddonListeners@resource://gre/modules/AddonManager.sys.mjs:3768:52 updateAddonDisabledState@resource://gre/modules/addons/XPIDatabase.jsm:2891:34 setUserDisabled@resource://gre/modules/addons/XPIDatabase.jsm:783:25 enable@resource://gre/modules/addons/XPIDatabase.jsm:1342:27 handleEvent@chrome://mozapps/content/extensions/aboutaddons.js:2509:27 
```

Not sure if this is indeed the same issue, if not I can open a new one, but if so, maybe the logs from another system may help narrow down the cause...

**Comment by jdnicholas** [comment]
> different problem, see #2882
Ah, sorry. Either way, BBT 6.7.202 seems to work for me now
