### ISSUE TITLE
Error message on installation

### ISSUE THREAD

**Issue by juengling** [retorquere/zotero-better-bibtex#2888]
### Debug log ID

Sorry, but as BBT could not be installed, this is not possible.

### What happened?

When installing the XPI file as described in the online docs, this error message (German) occurs:

> Die Erweiterung "%S" konnte nicht installiert werden. Sie ist eventuell inkompatibel mit dieser Version von Zotero.

My Translation: The add-in "%S" could not be installed. It's perhaps incompatible with this version of Zotero.

**Comment by retorquere** [comment]
Does this message come from Zotero, or from Firefox?

**Comment by juengling** [comment]
> Does this message come from Zotero, or from Firefox?

It came from Zotero. **But please hold on, perhaps it was my fault.** I'm currently working on a very slow Wifi connection, so I didn't realise the download process was still in progress. I'll have to look, if the message reappears after finishing the download.

**Comment by retorquere** [comment]
It's very easy to verify. Rename the file to have extension `.zip` and see if you can open it.

**Comment by juengling** [comment]
I tried quite too early to install it. It was indeed the sloppy internet connection. Now at home (50 MBit) it took only a second to download! Sorry for the trouble, I'll close the ticket.
