### ISSUE TITLE
TypeError: Zotero.getMainWindow() is null

### ISSUE THREAD

**Issue by MrSerth** [retorquere/zotero-better-bibtex#2892]
### Debug log ID

EMFJAWCL-fio-etWpVAdU8ghS

### What happened?

I just closed my Zotero, after starting it about two minutes earlier. A few seconds after I closed it, the attached pop up was shown (without any visible Zotero window).

<img width="489" alt="Bildschirmfoto 2024-05-29 um 16 03 43" src="https://github.com/retorquere/zotero-better-bibtex/assets/7300329/ff945a18-c7d9-4e23-8214-e6e2406a8d35">

My BetterBibTex version: `6.7.202`
My Zotero version: `7.0.0-beta.81+721f54fe4`

Unfortunately, since Zotero was already in the process of shutting down, I could not get a debug log immediately. Instead, I had to quit and reopen it before sending the debug log.

**Comment by retorquere** [comment]
I'll see what I can find, but logs are cleared after restart, so there's not much you could have done.

**Comment by MrSerth** [comment]
Thanks for working on this issue and providing a custom build. I've installed the build from this issue and am currently observing the situation. So far, the issue hasn't reappeared.

**Comment by retorquere** [comment]
Will be in the next release, you'll be upgraded automatically
