### ISSUE TITLE
Citation dialog not in focus

### ISSUE THREAD

**Issue by tommyhosman** [retorquere/zotero-better-bibtex#2895]
### Debug log ID

JFWECRJE-euc/6.7.202-7

### What happened?

I'm using BBT with obsidian Zotero Integration. When I call the citation command the Zotero citation dialog appears, but the keyboard cursor is not focused to the dialog input. And to clarify, the citation dialog is in the foreground, but not the active window (I cannot tab into the input).

The Zotero citation dialog works as expected with the Word plugin. 

Please let me know if you need more information!

Versions
```
Zotero Integration: 3.1.8
Zotero: 7.0.0-beta.82+79fa160e4 (64-bit)
Better BibTex: 6.7.202
```

**Comment by retorquere** [comment]
I've asked the Zotero crew, but I cannot replicate the problem locally (on MacOS, I don't have access to a Windows machine)

**Comment by retorquere** [comment]
I've bought a Windows machine, I'm setting it up to try to replicate this.

**Comment by retorquere** [comment]
Turns out it's not something I can fix. The word processor plugins force the focus back, not zotero itself. Even if there was a way to yield focus to another app, I wouldn't know what app was calling.
