### ISSUE TITLE
Add "Copy as Better BibTeX" in the right-click menu of items

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#2898]
### Debug log ID

BBUNRVFU-refs-euc/6.7.203.2887.6397-7

### What happened?

It would be nice if BBT could add a "Copy as Better BibTeX" option in the right-click menu on an item.
There are already other plugins doing that, as discussed [here](https://forums.zotero.org/discussion/comment/465147/#Comment_465147), with the relevant code [here](https://github.com/windingwind/zotero-actions-tags/discussions/165). But they are quite technical. And this is a common request in the forums for BBT users. So a default integration in BBT would probably be useful for new Zotero users.

As the other plugins are not focused on this aspect, they do not propose a nice interface to select an export format.
I would find it easier to have a simple dropdown menu in the BBT settings.

**Comment by deardeer7** [comment]
Zotero本身已经有快速复制：`Ctrl + Shift + C`

**Comment by retorquere** [comment]
You can also double-click the key in the item pane section and Cmd-C. But a build that adds the menu entry will drop here shortly.

**Comment by retorquere** [comment]
That build has the change. If you can confirm it does what you need, I can merge it into a new release.

**Comment by mjthoraval** [comment]
Sorry for the late reply.
I am getting this error when trying to add the test build:
![image](https://github.com/user-attachments/assets/b112e110-d828-4e09-bc5d-4d18183834aa)

**Comment by mjthoraval** [comment]
Thank you. I understand that this build adds the menu option "Copy key to clipboard".
This is nice, but I was more referring to the Quick Copy format "Better BibTeX":
![image](https://github.com/user-attachments/assets/e96436fd-e1fb-4f93-a635-1165a86d3c60)

It is possible to change the Quick Copy settings to switch to that format and then use the normal Quick Copy shortcut. But I usually prefer using the Quick Copy functionality for other purposes, to simply get the formatted citation of an item. And switching between the formats in the settings every time is quite painful.

Would it be possible to get this format directly from a right-click and add the ability to assign a shortcut to it?
Thank you very much!

**Comment by retorquere** [comment]
Build incoming for the change to quick-copy, but I don't deal with shortcut keys, Zutilo does that for Zotero 6, and Zotero Tags and Actions does it for Zotero 7 IIRC.

**Comment by mjthoraval** [comment]
The "Quick copy to clipboard" is not working for me.
It triggers the following error:
`[JavaScript Error: "TypeError: this.ZoteroPane is undefined" {file: "jar:file:///C:/Users/mjthoraval/AppData/Roaming/Zotero/Zotero/Profiles/4o6yeo4t.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 117639}]`

**Comment by mjthoraval** [comment]
This version still copies the citation key instead of the bibtex of the item.
Should I change something somewhere?

**Comment by retorquere** [comment]
I can't tell for sure without a debug log, but if I'd have to guess I would say your BBT quickcopy format is set to `Cite Keys`.

**Comment by retorquere** [comment]
Ah. That doesn't seem like a good idea to me, really; I don't see a good reason to prefer Better BibTeX over Better BibLaTeX here. Maybe the Tags & Actions plugin can provide a shortcut? I'd be happy to provide an action to call.

**Comment by mjthoraval** [comment]
It is already possible to do this with the Actions & Tags plugin, as detailed in the (very long) post I have linked at the top of this discussion.
My point here was just to say that setting this up requires 2 plugins, some script and extracting information from the advanced settings of Zotero, as well as understanding the concepts of Quick Copy, Translators, ... I have tried a few times explaining this to new Zotero users using LaTeX. But the final reply is always that they are not going to spend so much time for such a basic functionality.

A basic LaTeX user simply needs to have access to the BibTeX of the entries to write articles, but also the formatted citations to put in emails or quick reports. Both functionalities are provided by the Quick Copy functionality of Zotero, but it can only do one at a time. And it is very painful to switch between formats.
Most new users trying to use Zotero for the first time are just trying to get the formatted information from a right-click on the item. This is why I thought that integrating this in the right-click menu directly from the BBT plugin would make it easier for new users to discover this simple operation.

I am open to suggestions if you think that there are easier ways to achieve this for new users...

**Comment by retorquere** [comment]
> A basic LaTeX user simply needs to have access to the BibTeX of the entries to write articles

But wouldn't a basic TeX user use biblatex these days?

A new build will drop in a bit that adds both. I don't think adding more preferences to BBT for this is the right approach. It's hard to find the right preference in the BBT prefs already.

**Comment by mjthoraval** [comment]
Thank you. It is working nicely.
Just a small issue to solve on the text in the menu:

![image](https://github.com/user-attachments/assets/9df78430-eeb4-466f-8efc-53134b443780)

I would put an emoji in front of the text in the menus to identify them easily, but that is probably just personal taste.

> But wouldn't a basic TeX user use biblatex these days?

In my field (Fluid Mechanics), the main journals all provide a LaTeX template using BibTeX (REVTeX for APS and AIP, Journal of Fluid Mechanics, ...). I haven't seen BibLaTeX alternatives. So a PhD student in my field would write in LaTeX with BibTeX.

**Comment by retorquere** [comment]
> I would put an emoji in front of the text in the menus to identify them easily

The full list of emojis is [here](https://www.unicode.org/emoji/charts/full-emoji-list.html), feel free to make suggestions.

**Comment by mjthoraval** [comment]
I would put the B button (blood type) (n° 1568, 🅱) or other [B letters](https://emojicombos.com/emoji-letters) (🅑, Ⓑ, 🄱, 🇧, ⓑ, ...).
But a few others could also work:
- card index: 1316, 📇
- clipboard: 1320, 📋
- page facing up: 1272, 📄

**Comment by mjthoraval** [comment]
Then the B button (blood type) (n° 1568, 🅱) is good. Thank you.

**Comment by mjthoraval** [comment]
I am still seeing the same as in the previous version. The functionality is working, but the text displayed in the menu is not correct:
![image](https://github.com/user-attachments/assets/e5488cd0-14ad-4a31-a9d0-a9acfa777590)

**Comment by mjthoraval** [comment]
Thank you. It is working fine now:
![image](https://github.com/user-attachments/assets/2363ad5a-83eb-41ac-921b-594b37bad028)
