### ISSUE TITLE
Cache always at 0%

### ISSUE THREAD

**Issue by dlawisch** [retorquere/zotero-better-bibtex#2907]
### Debug log ID

MI76ZBZ6-euc/6.7.206-6

### What happened?

No matter how I configure Better Bibtex, the cache always appears as "0%".

Steps I've taken to eliminate variables:

Disabled all extensions except for Better Bibtex.

On Better Bibtex Preferences -> Automatic Export:
- Removed current automatic export

On Better Bibtex Preferences -> Export -> Miscellaneous:
- Selected "Reset cache"

Removed Better Bibtex extension.
Restarted Zotero, closed again.

On data and profile folders, deleted anything resembling Better Bibtex related.
- /data/better-bibtex/
- /data/better-bibtex.sqlite
- /profile/translators/Better Bibtex JSON.js

Opened Zotero. On Preferences -> Advanced -> Files and Folders -> Database Maintenance:
- Selected "Reset Translators"
- Selected "Reset Styles"
- Selected "Check Database Integrity"

Restarted Zotero. Installed Better Bibtex extension. Restarted Zotero.
Waited for Better Bibtex to reassign citation keys. Took a couple of minutes, ~5k items.

On Better Bibtex Preferences -> Export -> Miscellaneous:
- "Retain export cache across upgrades" is checked
- "Enable caching for background exports" is checked
- Selected "Reset cache"

Made sure no automatic export existed.

On Tools -> Better Bibtex -> Send debug log:
- Selected "Restart with Logging Enabled"

Made sure better bibtex cache settings were still applied.
Waited for "bibtex waiting for zotero" and regular zotero sync.

Selected My Library -> Export Library -> Better Bibtex
- "Export Notes" unchecked
- "Export Files" unchecked
- "Use Journal Abbreviation" unchecked
- "Keep updated" checked
- "Background export" checked

Exported to a new file test.bib. Around 6k items, took around 30 seconds.

On Better Bibtex Preferences -> Automatic export:
- Cached shows 0%
- Selected "Export Now", took around 10 seconds.
- Cached still at 0%.

Auto export is "On Change", set delay for 5s.
Made tiny change in library, waited 5s. Export started and took around 20 seconds.

On Better Bibtex Preferences -> Automatic export:
- Cached shows 0%
- Selected "Export Now" again, took around 20 seconds.
- Cached still at 0%.

Then on Tools -> Better Bibtex -> Send debug log:
- "Include item: cache" checked
- Debug log ID: MI76ZBZ6-euc/6.7.206-6

Does it seem like the cache is working and perhaps it's just displayed as 0%?

As I understand if a cache error occured it would show up as "Cached ?%", is that right?

I want to make sure it's working because Zotero uses a lot of CPU during export and the GUI hangs a bit.

Increasing export delay or setting it to idle might alleviate that but I would like to streamline the path from "creating/editing zotero item" to "generate updated .bib" as much as possible.

Thanks!

**Comment by retorquere** [comment]
The question mark is when it has no info yet. Info is calculated after export. Reset empties the cache btw.

I'm in the middle of a total overhaul of the caching system, being tracked under #2315. I wouldn't worry about the cache until that comes out, ETA is about two weeks.

The cache is currently a tradeoff between speed and memory use, functionally there's no difference, so wrt streamlining, nothing will change functionally. 

After the overhaul, start of export will be faster, and memory use will drop significantly for large libraries.

**Comment by retorquere** [comment]
No, both 6 and 7.

**Comment by retorquere** [comment]
A new build just dropped on #2315, please subscribe to that issue for further work on this.
