### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by warpedwood** [retorquere/zotero-better-bibtex#2910]
### Debug log ID

J6652M6A-euc/6.7.207-7

### What happened?

I have recently noticed high CPU usage (around 15%). It occurs without any specific action being taken. I have opened an issue on Zotero forums, but the problem seems to come from BBT: https://forums.zotero.org/discussion/115438/zotero-7-beta-high-cpu-usage#latest. I'm running Ubuntu 24.04, Zotero 7.0.0-beta.91+3c6625f3c (64-bit), and BBT 6.7.207.
Thanks for your help and your work

**Comment by retorquere** [comment]
Does the CPU usage drop when you set auto-export to "off"? Although I don't see any BBT activity after start.

**Comment by warpedwood** [comment]
Yes, it drops when I put auto-export on "pause". Maybe I should delete some of the folders that are on auto-export, at least when I'm not using them.

**Comment by retorquere** [comment]
I'm going to add an option to allow disabling individual auto-exports. It's expected that system load will rise while an auto-export runs, but I don't see any auto-export activity in `J6652M6A-euc/6.7.207-7`.

**Comment by warpedwood** [comment]
Thanks for adding the option. 
The high CPU usage doesn't happen every time I start Zotero. I can't figure out why.  I enabled the "on change" option for auto-export again, added new references, and restarted Zotero, but there was no high CPU usage again. Just before that, I deleted some collections with auto-export. That may have helped. So I think you're right that the problem is auto-export.

**Comment by retorquere** [comment]
I would say the cause rather than the problem, but yes.

**Comment by warpedwood** [comment]
Actually, it just started again. I sent you a new debug log. Here is the ID if it helps: 5TLAXLIQ-euc/6.7.207-7

**Comment by retorquere** [comment]
detailed debug logging is off on your system, so there isn't anything in the log.

**Comment by warpedwood** [comment]
Sorry. Here is a new one, hoping it works: ANK9H4DJ-euc/6.7.207-7

**Comment by retorquere** [comment]
That does indeed show activity. Some of that is inherent (auto-exports will take non-zero time), but the work I'm doing on #2315 will drop some of the work being done.

**Comment by retorquere** [comment]
Can you subscribe to #2315 for further progress on this? A new build just dropped there that should improve matters.
