### ISSUE TITLE
Use `prepublished` as default pubstate for arXiV articles

### ISSUE THREAD

**Issue by fynsta** [retorquere/zotero-better-bibtex#2911]
### Debug log ID

PIYEJX44-refs-euc/6.7.208-6

### What happened?

The `pubstate` of an arXiV entry is written as `preprint` for BibLaTeX. However, as we can see in the [BibLaTeX documentation](https://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf#page=295&zoom=100,0,0), this is not actually a supported value. It should be `prepublished`. Then it will also actually be correctly capitalized by the citation engine.

**Comment by retorquere** [comment]
Awesome. I'll roll it out to release.

**Comment by fynsta** [comment]
Wow, thank you so much for the quick improvement!

**Comment by rafisics** [comment]
So, this is why suddenly all the `pubstate` entries in my Zotero bib items switched from `preprint` to `prepublished`.  I don't know, I kinda prefer the term `preprint`.

**Comment by retorquere** [comment]
It's changeable by postscript if you want it, but being in line with the documented behavior of biblatex is a better default.
