### ISSUE TITLE
Journal abbreviation detection active while importJabrefAbbreviations is off

### ISSUE THREAD

**Issue by unknownnumbers** [retorquere/zotero-better-bibtex#2916]
### Debug log ID

HAFA33CG-fio-gBbN7cpwFFTJ

### What happened?

When I imported bibtex data into the zotero with "rawimport mode", it cannot maintain the journal field and it may be changed by translators. 

Precisely, when I import the following from the clipboard:

```
@article {citekey,
    AUTHOR = {Author},
     TITLE = {title},
   JOURNAL = {J. Funct. Anal.},
}
```

The journal field become "Journal of Functional Analysis" while 'journal abbr' is "J. Funct. Anal."
I think there are some translators which changes the "journal" field from "J. Funct. Anal." to "Journal of Functional Analysis".
But I have set the value of "extensions.zotero.translators.better-bibtex.rawImports" as "true".

![image](https://github.com/retorquere/zotero-better-bibtex/assets/28758103/503845e9-f9d9-46e0-a1a4-3e3a67e18e57)

It is quite strange performance.

**Comment by retorquere** [comment]
I forgot to document the relevant setting, you can [turn this behavior off](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html#importjabrefabbreviations).

**Comment by retorquere** [comment]
I'm assuming this addresses your question. If it doesn't, you can comment here and the issue will reopen.

**Comment by unknownnumbers** [comment]
BC2L9U5S-fio-9hluAQ8hoSjU
I use the following again with the new settings.
(**extensions.zotero.translators.better-bibtex.rawImports;true**)
(**extensions.zotero.translators.better-bibtex.importJabRefAbbreviations;false**)
```
@article {citekey,
    AUTHOR = {Author},
     TITLE = {title},
   JOURNAL = {J. Funct. Anal.},
}
```
Unfortunately, the rendering is that nothing occurs in the term, "publication", which shall be exported by item format 'better BibTeX'.
Shown in the following pictures:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/28758103/138b7c92-dc17-4ac4-aa9b-4c8a58298a6a)

And the export content by item format 'better BibTeX' is:

```
@article{Author_,
  title = {title},
  author = {Author}
}
```

**Comment by retorquere** [comment]
I'm looking into it, but I see you're structurally sending fio logs, so the regular BBT logs not work for you? fio logs are a fallback, the regular BBT logs are less work for me to use for diagnosis.

**Comment by retorquere** [comment]
There's no need to post your BBT settings btw, they're in the log.

**Comment by unknownnumbers** [comment]
> I'm looking into it, but I see you're structurally sending fio logs, so the regular BBT logs not work for you? fio logs are a fallback, the regular BBT logs are less work for me to use for diagnosis.

Thanks again for your prompt and patient reply! I greatly apologize that I do not know the difference between the two types of logs and just follow the hit to upload the log. If it is necessary, I will try to seek another method to find the simplified logs.

**Comment by unknownnumbers** [comment]
> There's no need to post your BBT settings btw, they're in the log.

OK. I guess that it is. I attached it to highlight the changes and avoid the lack of the issue's description. I will not put the duplicated content anymore. Thank you so much!

**Comment by retorquere** [comment]
> Thanks again for your prompt and patient reply! I greatly apologize that I do not know the difference between the two types of logs and just follow the hint to upload the log. If it is necessary, I will try to seek another method to find the simplified logs.

Don't worry too much about it, the fio logs are a great fallback, but if you right-click an item, and select Better BibTeX - send debug log from the popup menu instead, you get an ID that ends in -euc or -apse, those logs specifically are the least work for me to work with.

The fio option sticks around if BBT had problems starting up, but if BBT starts normally, the fio option should disappear after 15s.

I'm a little slower than usual, as I'm traveling, and network reception is very spotty.

**Comment by retorquere** [comment]
> OK. I guess that it is. I attached it to highlight the changes and avoid the lack of the issue's description. I will not put the duplicated content anymore. Thank you so much!

Also don't worry too much about this. I appreciate the effort. I have a fix lined up, but I'll need a better net connection to roll out a build. May take another 12h to get overlapping time and network availability.

**Comment by unknownnumbers** [comment]
> > Thanks again for your prompt and patient reply! I greatly apologize that I do not know the difference between the two types of logs and just follow the hint to upload the log. If it is necessary, I will try to seek another method to find the simplified logs.
> 
> Don't worry too much about it, the fio logs are a great fallback, but if you right-click an item, and select Better BibTeX - send debug log from the popup menu instead, you get an ID that ends in -euc or -apse, those logs specifically are the least work for me to work with.
> 
> The fio option sticks around if BBT had problems starting up, but if BBT starts normally, the fio option should disappear after 15s.
> 
> I'm a little slower than usual, as I'm traveling, and network reception is very spotty.

OK. Wish you a nice journey!

**Comment by retorquere** [comment]
Does this behave the way you expected?

**Comment by unknownnumbers** [comment]
> Does this behave the way you expected?

It works! Thanks a lot!
