### ISSUE TITLE
[Feature request] Add a copy button following the value.

### ISSUE THREAD

**Issue by llity** [retorquere/zotero-better-bibtex#2925]
### Debug log ID

NA

### What happened?

You can add a copy button next to the value. Also found a bug in the reader where values are not displayed.

<img width="416" alt="image" src="https://github.com/user-attachments/assets/c3d7f08c-ec13-43f8-bd7b-31f177c47195">

**Comment by retorquere** [comment]
How do you propose I find out what the bug is without a debug log?
