### ISSUE TITLE
Patched Zotero.Utilities.Internal.itemToExportFormat prevents export of unsaved Zotero items

### ISSUE THREAD

**Issue by Dominic-DallOsto** [retorquere/zotero-better-bibtex#2926]
### Debug log ID

RKDGUGVC-refs-euc/6.7.214.2920.6605-7

### What happened?

I'm working on updating the [Cita](https://github.com/diegodlh/zotero-cita/) extension for Zotero 7 and noticed this error.

Cita stores data about the citations made by each Zotero item in a custom format (not as proper Zotero items). When we want to export all the citations belonging to a particular item we convert this to a list of Zotero Items that aren't actually saved in the database and pass these to the Zotero translator.

A while ago now we encountered a different error when exporting to better bibtex format, because these "unsaved" items didn't have citation keys, but we developed the workaround of first manually giving them citation keys https://github.com/diegodlh/zotero-cita/issues/145

But this new issue occurs when exporting to any format (`fixExportFormat` is always called [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/better-bibtex.ts#L442) when exporting items) because these unsaved items don't have ids, and so trigger the error [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/item-export-format.ts#L66).

Would it be possible to first check whether the item to be serialised has a citation key and if so use it, before trying to get the item's citation key from the key manager by item ID?

I checked to make sure - exporting cited items from Cita works fine when BBT isn't installed.

(sorry that this is using an unrelated debug build of BBT - the current release 6.7.214 isn't up to date with the latest changes in item-export-format.ts)

**Comment by retorquere** [comment]
Can I test whether the item is unsaved? That would be the best thing to check for, right?

**Comment by retorquere** [comment]
Oh I can just test for the presence of `id`

**Comment by Dominic-DallOsto** [comment]
Ahh yeah - that makes sense. Is `item.id` null by definition if the item is unsaved?

**Comment by retorquere** [comment]
I think it's `undefined` rather than `null`. Build incoming.

**Comment by retorquere** [comment]
That should work. Ik you can verify, I'll put out a new release.

**Comment by Dominic-DallOsto** [comment]
Actually these builds didn't work for me because `item.id` is `null`

**Comment by Dominic-DallOsto** [comment]
Perfect thanks, that works now!

**Comment by retorquere** [comment]
A release build is running, should be out in 10.

**Comment by retorquere** [comment]
This solves the primary problem (which is good, and I'm happy you caught it), but you'd have to test https://github.com/diegodlh/zotero-cita/issues/145 again. Background exports will not work because it needs serialized items to be present in BBTs serialization cache, which is keyed on item id, but you can easily avoid those, and I take it you're not exporting large batches of items.

**Comment by retorquere** [comment]
Sorry about that. New build incoming with [this](https://github.com/retorquere/zotero-better-bibtex/blob/gh-2926/content/key-manager.ts#L590) change.

**Comment by retorquere** [comment]
Note it's a Set now, not an array.

**Comment by retorquere** [comment]
Is that confirmation that it works? If so, I'll put out another release.

**Comment by Dominic-DallOsto** [comment]
> Is that confirmation that it works? If so, I'll put out another release.

No I was just speculating. I can't see the new build yet?

**Comment by Dominic-DallOsto** [comment]
Perfect thanks! Now I get different keys.

```bibtex
@article{smithPaper2022a,
  title = {Paper},
  author = {Smith, J},
  year = {2022},
  journal = {J1}
}

@article{smithPaper2022,
  title = {Paper},
  author = {Smith, J},
  year = {2022},
  journal = {J2}
}
```

**Comment by retorquere** [comment]
Release build is running.

**Comment by Dominic-DallOsto** [comment]
Yep! Works all good with 6.7.217. Thanks a lot!
