### ISSUE TITLE
BBT not working for my zotero 7 which ran as admin

### ISSUE THREAD

**Issue by zoe667** [retorquere/zotero-better-bibtex#2928]
### Debug log ID

D98635366

### What happened?

My BBT never worked well....when I use zotero 6, I will have to disable BBT often to make my zotero successfully loading. And when I tried to create/import notes to Obsidian, it always told me it cannot connected to zotero/BBT. Today I really want to establish that connection between zotero and obsidian and download zotero 7, but the BBT is not compatible, what should I do?
Thank you for any advice!

**Comment by retorquere** [comment]
I can't read those logs, and BBT is compatible with Zotero 7. Are you [downloading BBT with Firefox](https://retorque.re/zotero-better-bibtex/installation/index.html)?

**Comment by retorquere** [comment]
> My BBT never worked well....when I use zotero 6, I will have to disable BBT often to make my zotero successfully loading. And when I tried to create/import notes to Obsidian, it always told me it cannot connected to zotero/BBT. 

And the point this is supposed to convey is...? You reported precisely one issue before, months ago, said it worked perfectly after the fix I put out then. I am not a mind reader -- if you have problems, report them.

**Comment by zoe667** [comment]
Nope. I downloaded via Chrome. That Is very weird. I cannot load log file correctly because I open zotero with safe mode (or it will frozen with BBT enabled) And I enable debug then close and open zotero normally, it frozen. And I cannot get the log file or something. Any other way I can do it?
Or perhaps i downloaded the wrong version of  BBT？mine was 6.7.217. zotero is 7.0.0 beta

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 3:36:46 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


I can't read those logs, and BBT is compatible with Zotero 7. Are you downloading BBT with Firefox<https://retorque.re/zotero-better-bibtex/installation/index.html>?

―

**Comment by retorquere** [comment]
6.7.217 is the latest version, so that's not it. BBT is tested at least every night on Linux, I use it daily with 6 and 7 on MacOS, so it's not outright incompatibility, but something is obviously not working for you. What platform are you on?

**Comment by zoe667** [comment]
Thank you of course for your previous help! It only worked for that one time...or maybe not. I just give up using BBT for a while because it keep happening. Very weird. I really don't know how to deal with it. Especially the log thing.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 3:41:04 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


My BBT never worked well....when I use zotero 6, I will have to disable BBT often to make my zotero successfully loading. And when I tried to create/import notes to Obsidian, it always told me it cannot connected to zotero/BBT.

And the point this is supposed to convey is...? You reported precisely one issue before, months ago, said it worked perfectly after the fix I put out then. I am not a mind reader -- if you have problems, report them.

―

**Comment by retorquere** [comment]
I'm on beta 7.0.0-beta.113 BTW

**Comment by zoe667** [comment]
Right. I'm not sure about 'platform'？what should it be？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 3:45:36 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


6.7.217 is the latest version, so that's not it. BBT is tested at least every night on Linux, I use it daily with 6 and 7 on MacOS, so it's not outright incompatibility, but something is obviously not working for you. What platform are you on?

―

**Comment by retorquere** [comment]
> I just give up using BBT for a while because it keep happening.

Which I can't fix if no one reports it. This might come as a surprise, but I can't fix problems I don't experience and I don't know others are experiencing.

**Comment by retorquere** [comment]
> Right. I'm not sure about 'platform'？what should it be？

MacOS, Linux or Windows.

**Comment by retorquere** [comment]
How many items are in your library?

**Comment by zoe667** [comment]
Windows. Is the process I follow, like open safe mode with zotero, enable debug blabla, right？To provide the report you need？I saw debug ID there. Not sure why it cannot be accessed.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 3:48:41 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


Right. I'm not sure about 'platform'？what should it be？

MacOS, Linux or Windows.

―

**Comment by zoe667** [comment]
I would say 80 to 100 literatures, and also several group libraries.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 3:50:36 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


How many items are in your library?

―

**Comment by zoe667** [comment]
I got a new debug id, D1979524475. Is it accessible? By the way, I re-installed back to zotero 6

**Comment by retorquere** [comment]
> Windows. Is the process I follow, like open safe mode with zotero, enable debug blabla, right

In safe mode plugins don't load, so there's nothing for me to diagnose. I'll try on a windows system.

> I saw debug ID there. Not sure why it cannot be accessed. 

Because `D<number>` logs go to the Zotero team, I'm not part of the Zotero team.

**Comment by zoe667** [comment]
Oh right. But when I restart with debug logging enabled, there is no "send debug log to BBT" option in Help menu as instructed on BBT webpage. Is it because I disabled BBT? But if I do not disable BBT, zotero frozen as soon as it initiated. And I cannot click help menu to enable debug. Should I talked to zotero team for this? Thank you!

**Comment by retorquere** [comment]
It starts without issue for me on Windows on a pretty large library (24000 items), so it's not just that it doesn't work on Windows.

> there is no "send debug log to BBT" option in Help menu as instructed on BBT webpage

there should be a "send to file.io" (see above). If you restart with debugging enabled, let it sit 10 seconds or so, then send to file.io I should get a usable log.

**Comment by retorquere** [comment]
> Is it because I disabled BBT?

Oh. Yes.

> But if I do not disable BBT, zotero frozen as soon as it initiated. And I cannot click help menu to enable debug. Should I talked to zotero team for this? Thank you!

It might be necessary at some point but it's primarily my responsiblity to fix this.

Would you be OK with sharing a copy of your profile?

**Comment by zoe667** [comment]
Not at all. Please, be my guest. How should I assist you do that？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 4:23:36 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


Is it because I disabled BBT?

Oh. Yes.

But if I do not disable BBT, zotero frozen as soon as it initiated. And I cannot click help menu to enable debug. Should I talked to zotero team for this? Thank you!

It might be necessary at some point but it's primarily my responsiblity to fix this.

Would you be OK with sharing a copy of your profile?

―

**Comment by retorquere** [comment]
Shut down Zotero (don't do any of this while Zotero is running), find the `Zotero` folder in your user directory, upload it to https://www.file.io/, and give me the resulting code.

**Comment by retorquere** [comment]
What windows version BTW? And what version of Zotero beta? Can you send a log from Zotero 6?

**Comment by zoe667** [comment]
Yes. I re-installed zotero6, so the beta version is automatically removed. My Windows is 64 bit, x64 based processor. 12th Gen Intel Core i7-12700H 2.30Ghz. I will now try the fileio thing.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 4:30:25 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


What windows version BTW? And what version of Zotero beta? Can you send a log from Zotero 6?

―

**Comment by retorquere** [comment]
Yes but what version of Windows. 10? 11?

**Comment by zoe667** [comment]
Windows 11 veraion23H2
BTW, after 10 min, the progress showed on fileio is still 0%, is that normal？total is 126 mb. Shouldn't be this slow.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 4:53:17 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


Yes but what version of Windows. 10? 11?

―

**Comment by retorquere** [comment]
> I re-installed zotero6, so the beta version is automatically removed

That's not true. The installers don't interfere, and you can safely have them installed side by side, you just can't use them both at the same time.

**Comment by retorquere** [comment]
> BTW, after 10 min, the progress showed on fileio is still 0%, is that normal？total is 126 mb. Shouldn't be this slow.

No that's not normal. Does https://securesha.re/ work for you?

**Comment by zoe667** [comment]
It can only upload files, not folder. So...

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Emiliano Heyns ***@***.***>
发送时间: Tuesday, August 6, 2024 5:01:53 PM
收件人: retorquere/zotero-better-bibtex ***@***.***>
抄送: Ziying Song ***@***.***>; Mention ***@***.***>
主题: Re: [retorquere/zotero-better-bibtex] BBT not working for my zotero 7 (Issue #2928)


BTW, after 10 min, the progress showed on fileio is still 0%, is that normal？total is 126 mb. Shouldn't be this slow.

No that's not normal. Does https://securesha.re/ work for you?

―

**Comment by retorquere** [comment]
That may have been the problem with file.io. I meant to zip the folder and send the zip.

**Comment by zoe667** [comment]
This is the link: https://file.io/SosYDiG8tGJd

**Comment by retorquere** [comment]
`SosYDiG8tGJd` contains the Zotero directory under Program Files. I need the Zotero directory in your user directory (`C:\Users\<your username>/Zotero`)

**Comment by zoe667** [comment]
Right, here is the link: https://file.io/6FVVlJ0i6IUY

**Comment by retorquere** [comment]
There's just 118 items in the library, and it starts without any problems for me. BBT does show up as incompatible, but I removed what you had installed and reinstalled a fresh and it launches without any issue.

**Comment by retorquere** [comment]
There weren't other plugins in the profile you sent me

**Comment by zoe667** [comment]
I got ZotCard, Zotfile, Notero, Zotero Better Notes, Zotero Reference, Zotero style, and two I am not recognized with: Zotero LibreOffice Integration, Zotero Word for Windows Integration
Any one suspicious?

**Comment by retorquere** [comment]
Oh wait what you sent was the storage, not the profile. The profile is harder to find.

Try disabling all non zotero, non bbt plugins, and see whether that starts cleanly. If so, there's likely a problematic interference.

**Comment by zoe667** [comment]
Nah...I disabled all the others (with BBT enabled) and restart, it frozen right away.

**Comment by retorquere** [comment]
Then I'll need a copy of the profile as well. I'll try to find out where that's located on Windows.

You don't keep zotero stuff on network drives, usb drives, or cloud directories by any chance?

**Comment by zoe667** [comment]
I use ZotFile, this is an addon that transfer the pdf files from zotero storage (which is 300 MB for free version) to my local disc - if this is of any relevance.

**Comment by retorquere** [comment]
No, that's normal use.

**Comment by retorquere** [comment]
The profile directory can be found here: https://www.zotero.org/support/kb/profile_directory

can you zip that and put it on file.io?

**Comment by zoe667** [comment]
Thank you - I tried to locate it, after C:\Users\username\AppData\Roaming\Zotero\Zotero\Profiles, I only got a folder called cva03hy8.default. When I tried to compress it, it said "file not found or no read permission", what should I do then?

**Comment by retorquere** [comment]
> Thank you - I tried to locate it, after C:\Users\username\AppData\Roaming\Zotero\Zotero\Profiles, I only got a folder called cva03hy8.default.

So far so good.

> When I tried to compress it, it said "file not found or no read permission", what should I do then?

I don't know. I can compress that directory without issue, so at first glance it looks like there's a rights problem with that folder. Have you at some point started Zotero as administrator?

**Comment by zoe667** [comment]
Yes - I think there was one time I saw instructions online to let me open Zotero with administrator's mode to fix something.

**Comment by retorquere** [comment]
That instruction did not come from Zotero, and there's no telling what it broke. It is never necessary to run Zotero as administrator. I've seen people do this because they wanted their data dir somewhere on c:\whatever. There are ways to do that but running as admin is not the way and will break things in unpredictable ways that are near impossible to diagnose.

My advice would be to contact the Zotero forums to fix the current situation. The permission problems is likely that cause of the breakage.

Do you remember where you saw this recommendation to run as admin? That needs to be corrected.

**Comment by zoe667** [comment]
I see. thanks - but I cannot remember where I saw it...cause I was using a lot of online info to assist me establishing Zotero working environment, like addons. I will try to contact Zotero team. I do appreciate that you tried very hard to help me with this!

**Comment by zoe667** [comment]
Oh， just one more question, could you suggest a clear way to state my problem with "administrator" thing? Should I just say "I once used administrator mode to start my Zotero and that caused a breakage for the connection of my BBT and Zotero (once enable BBT, my zotero frozen), how can I reverse it? It is not fixed by reinstalling zotero or BBT"

**Comment by retorquere** [comment]
I'd just say you've ran zotero as admin and are now experiencing permission problems with your profile folder. They'll likely tell you to delete the profile. The profile is regenerated on start when missing.

**Comment by retorquere** [comment]
You can tag me on the discussion on the forum and I'll jump in.

**Comment by zoe667** [comment]
Okay, you mean tag you in "retorquere" or "Emxxx xxxx"? Just to make sure not to expose something that I shouldn't

**Comment by retorquere** [comment]
I'm emilianoeheyns on the forums.

**Comment by retorquere** [comment]
If the profile fix still leaves a BBT issue, you can comment here and the issue will reopen.
