### ISSUE TITLE
Wrong ordering of items in exported library

### ISSUE THREAD

**Issue by josineto** [retorquere/zotero-better-bibtex#2929]
### Debug log ID

3PHZ6LA2-refs-euc/6.7.217-7

### What happened?

Today I switched from Zotero 6 to 7. The only problem I've faced is: in the exported library (both in CSL JSON or CSL YAML), the ordering of items is not the same as of BBT in Zotero 6: instead of ordering items by citation key, it seems BBT orders items by the date I've added them to Zotero (it's not even the item's date itself), rendering a very confusing ordering.

To make the debug log, I restarted Zotero with debugging active, then proceeded to BBT settings, exported again the two automatic exports (CSL JSON and CSL YAML), then selected the whole library (left panel), right-click, and "Send BBT log" (or something like that). I don't know if it suffices to you, let me know if not. (And thank you, I use BBT for 4 years now, your work really shines!)

**Comment by SmallHollow** [comment]
I can confirm that the version 6.7.217 (and 6.7.216) exports the bibliography in a different order than before. I went back to 6.7.214 to get the ordering by citation key. I'm using Zotero 6.

**Comment by retorquere** [comment]
In this build, if you go into the prefs -> export -> misc, you can change the export sort order. The new order is slightly more efficient, and I was getting remarks from the Zotero team about BBT slowing things down, so 6.2.216+ addresses those problems, of which this was one aspect. Sorry for the disruption, but I don't really have a way to announce changes.

**Comment by josineto** [comment]
I tested with [test build 6.7.217.2929.6677](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.217.2929.6677.xpi) in Zotero 7.0.0 beta 112 and it works now: as the [bot message says](https://github.com/retorquere/zotero-better-bibtex/issues/2929#issuecomment-2273211609), I can select to order items by creation date, citation key or not ordering at all, and it works as expected.

Thank you!

**Comment by retorquere** [comment]
> as the [bot message says](https://github.com/retorquere/zotero-better-bibtex/issues/2929#issuecomment-2273211609), I can select to order items by creation date, citation key or not ordering at all, and it works as expected.

Contrary to popular belief, I am not a bot 😉

**Comment by retorquere** [comment]
I'll put out a new release tonight

**Comment by josineto** [comment]
> Contrary to popular belief, I am not a bot 😉

haha sorry for that! And thank you for the release!

**Comment by eltos** [comment]
> Sorry for the disruption, but I don't really have a way to announce changes.

@retorquere It would be much appreciated if you could hint such **breaking changes** in the release notes on GitHub or the CHANGELOG.md (which btw hasn't been updated for a long time).
I know it's a little bit of additional effort, but I'm sure you can make up the time by not having to deal with issues like this one ;)

PS: Thanks for maintaining this great extension, it's so valuable and helpful!

**Comment by retorquere** [comment]
I'll try to add it to the github releases. I've removed the changelog file.
