### ISSUE TITLE
stuck on export 

### ISSUE THREAD

**Issue by gkb21** [retorquere/zotero-better-bibtex#2940]
### Debug log ID

S2AS7NC2-apse/6.7.219-6

### What happened?

I'm trying to export my library but its stuck on exporting items and also shows: better BibTeX: preparing better biblatex

**Comment by retorquere** [comment]
Can you start with logging enabled from the help menu and send a new log?

**Comment by gkb21** [comment]
like this 4XY6ZWK3-apse/6.7.219-6

**Comment by retorquere** [comment]
Please install 6739, restart with logging enabled, and send a new log.

**Comment by gkb21** [comment]
That seems to have fixed it thank you ! C6ZY26P3-apse/6.7.219.2940.6739-6

**Comment by retorquere** [comment]
It's not really a fix, it's just a bodge to allow BBT to start, despite the presence of the problem.

You have a "webpage" item titled "Commands And Arguments" that has not been assigned a citation key (I don't know why yet), but which is also not listed as missing at start. Can you tell me what you see in the "citation key" section of that item? And if you right-click the item and select BBT-Refresh, does it get assigned one?

**Comment by gkb21** [comment]
<img width="337" alt="Screenshot 2024-08-13 at 8 56 33 AM" src="https://github.com/user-attachments/assets/bb645789-64f2-4388-9b44-a6629f286e39">

There isn't a section for citation key and refreshing doesn't do anything.

**Comment by retorquere** [comment]
Ah sorry you're on Zotero 6. Do any of the other items show the citation key at the top? Is it just this item that doesn't show it?

Can you send a log and check the "include item cache" checkbox?

**Comment by gkb21** [comment]
<img width="337" alt="Screenshot 2024-08-13 at 10 16 34 AM" src="https://github.com/user-attachments/assets/50f13662-0048-4f18-b5b7-5350d27e64d8">

Yeah it is. 

QWCAAYPY-apse/6.7.219.2940.6739-6

**Comment by retorquere** [comment]
If you go into Tools, Developer, Run Javascript, and past this into the left pane, verbatim

```
return await Zotero.DB.columnQueryAsync("WITH _items AS ( SELECT items.itemID, items.key as itemKey, items.libraryID, extra.value AS extra FROM items LEFT JOIN itemData extraField ON extraField.itemID = items.itemID AND extraField.fieldID IN (SELECT fieldID FROM fields WHERE fieldName = 'extra') LEFT JOIN itemDataValues extra ON extra.valueID = extraField.valueID WHERE items.itemID NOT IN (SELECT itemID FROM deletedItems) AND items.itemTypeID NOT IN (SELECT itemTypeID FROM itemTypes WHERE typeName IN ('attachment', 'note', 'annotation')) AND items.itemID NOT IN (SELECT itemID from feedItems) ) SELECT itemID FROM _items WHERE itemID NOT IN (SELECT itemID from betterbibtex.citationkey)")
```

and click "Run", what do you get in the right pane?

**Comment by gkb21** [comment]
[
    "0": 1306
]

**Comment by retorquere** [comment]
That checks out, I just don't know why it's not getting a key assigned. I need to get some shuteye, but a new build will drop in 10 mins or so, please install it, do not let it restart, go to Help -> Debug output logging -> Start with logging enabled, let Zotero restart, and then send a new log. I'll look at it when I get up.

**Comment by gkb21** [comment]
thank u ! 7ZC8EPP2-apse/6.7.219.2940.6741-6

**Comment by retorquere** [comment]
I think I have it. New build will drop in 10, same procedure please.

**Comment by gkb21** [comment]
Here is the debug log: KUV7DTWB-apse/6.7.219.2940.6742-6

**Comment by retorquere** [comment]
I'm looking into it but my response times are slower than usual, the zotero 7 release is bringing in a spike of requests, and I'm currently away to a competition with limited to to get behind a computer. I'm doing my best to address the issues and will be back to normal response times on Tuesday.

**Comment by gkb21** [comment]
Hi,
Thanks for all this, I think it might be all fixed now, I updated to Zotero 7 and that seemed to fix all the errors I was having !
