### ISSUE TITLE
Options disregarded for CSL YAML export

### ISSUE THREAD

**Issue by allefeld** [retorquere/zotero-better-bibtex#2945]
### Debug log ID

MN5MU9A3-refs-euc/6.7.221-7

### What happened?

The options

- "Export language as" and
- "When an item has both a DOI and a URL, export"

do not seem to have an effect on CSL YAML exports.

The exported file always contains `language` rather than `langid`, and both `DOI` and `URL` if defined in an item.

If that is the intended behavior, it should be documented.

Though I would actually appreciate the option to omit `URL` only if `DOI` is defined.

**Comment by retorquere** [comment]
> - "Export language as" and
> - "When an item has both a DOI and a URL, export"
> 
> do not seem to have an effect on CSL YAML exports.

"export language as" doesn't make sense for CSL. It's unambiguous where the language field should go. 

> The exported file always contains `language` rather than `langid`, 

because langid is not a CSL variable, and language is. 

> and both `DOI` and `URL` if defined in an item.

I can look into that when I'm back at my system but that's likely how zotero treats it. Where better bibtex/biblatex are wholly separate exporters, the better csl exporters only apply minor improvements on the zotero exports. This could be one of them. 

> If that is the intended behavior, it should be documented.

I patiently await a pull request for this documentation. I also usually entertain requests or suggestions for improvement of the documentation - the curse of knowledge is real. I think "should" is too strong a term here. 

> Though I would actually appreciate the option to omit `URL` only if `DOI` is defined.

Which I can look into.

**Comment by retorquere** [comment]
I've sectioned off the settings that only apply to TeX exports. I will look into the doi/url behavior later.

**Comment by allefeld** [comment]
> "export language as" doesn't make sense for CSL. It's unambiguous where the language field should go.

I figured that out later, but I found the CSL specification quite hard to understand. A hint in the description might therefore be helpful.

> I patiently await a pull request for this documentation. I also usually entertain requests or suggestions for improvement of the documentation - the curse of knowledge is real. I think "should" is too strong a term here.

I'm perfectly happy to help with improving the documentation, just say the word. I've done that with several other projects, but I'm not going to create a PR uninvited. Plus, in order to fix the documentation I need to know the facts, and you're the one who knows how BBT operates.

> Which I can look into.

Great, thanks!

**Comment by retorquere** [comment]
> I figured that out later, but I found the CSL specification quite hard to understand. A hint in the description might therefore be helpful.

I'm just going to group these settings under the bibtex/biblatex section.

I don't know all of the CSL spec either, but most people who are not involved in CSL or citeproc development (and I'm not) are more interested in the output of citeproc than the input of it. At the end of the day, CSL is just a way to get your items into citeproc. 

> I'm perfectly happy to help with improving the documentation, just say the word.

There's an open invitation - every page has an "edit this page" button which opens it in an editor which creates a PR.
