### ISSUE TITLE
 "No endpoint found" debug-bridge not working properly in Zotero 7.0.1

### ISSUE THREAD

**Issue by carllx** [retorquere/zotero-better-bibtex#2947]
### Debug log ID

436PJ9GD-apse/6.7.221-7

### What happened?

Recently, due to issue #2944, I reinstalled the latest Zotero 7.1 from the beta version, along with the latest [v6.7.221](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.221). However, the debug-bridge is not functioning properly. When executing the following command in Terminal:

```zsh
curl \
 -s \
 -X POST \
 -H "Content-Type: application/javascript" \
 -H "Authorization: Bearer ddd" \
 --data-binary @/Users/usr/Documents/script.js \
"http://127.0.0.1:23119/debug-bridge/execute?quection=$quection&itemID=$itemID"

// No endpoint found
```

The response indicates that no endpoint was found.

**Comment by retorquere** [comment]
I'm looking into it but my response times are slower than usual, the zotero 7 release is bringing in a spike of requests, and I'm currently away to a competition with limited to to get behind a computer. I'm doing my best to address the issues and will be back to normal response times on Tuesday. I don't know why zotero 7 release responds differently than the beta it was tested on.

**Comment by carllx** [comment]
@retorquere Thank you for your reply and explanation. I fully understand your current situation with increased workload and limited time. I greatly appreciate that you are still paying attention to this issue despite your busy schedule.
I am trying other versions of Zotero, and although the problem has not been resolved, I will patiently wait until you have more time to investigate this issue in depth.
If I discover any new clues or relevant information, I will promptly update this issue.

Thank you again for your efforts and support. Good luck with your competition! We look forward to further resolving this issue when you return next Tuesday.

**Comment by retorquere** [comment]
I can't reproduce this. I am running this:

```
curl -v -H "Content-Type: application/javascript" --data 'return 4' "http://127.0.0.1:23119/debug-bridge/execute"
```

and that gets me 'Bearer token expected', not a message about no such endpoint. What exact message are you getting?

**Comment by retorquere** [comment]
My tests are also running without issue and that would not be possible without debug bridge. Any relevant errors in the logs?

**Comment by carllx** [comment]
Thank you for providing the detailed information about your attempts. Based on your description, I would respond to retorquere in English as follows:

"I ran the following curl command:

curl -v -H "Content-Type: application/javascript" --data 'return 4' "http://127.0.0.1:23119/debug-bridge/execute"

The response I received was:

HTTP/1.0 404 Not Found
X-Zotero-Version: 7.0.1-beta.3+ec7ffa8c0
X-Zotero-Connector-API-Version: 2
Content-Type: text/plain

No endpoint found

When I checked Zotero.Server.Endpoints in the Error Console, I saw a list of objects, but "/debug-bridge/execute" was not among them. The endpoints I saw included various API endpoints, Better BibTeX endpoints, and connector endpoints, but nothing related to the debug bridge.

This seems to confirm that the debug-bridge endpoint is not available in my Zotero installation. Could this be related to the specific version I'm using (7.0.1-beta.3+ec7ffa8c0)?"

```javascript

"/api/": function ()
"/api/creatorFields": function ()
"/api/groups/:groupID": function ()
"/api/groups/:groupID/collections": function ()
"/api/groups/:groupID/collections/:collectionKey": function ()
"/api/groups/:groupID/collections/:collectionKey/collections": function ()
"/api/groups/:groupID/collections/:collectionKey/items": function ()
"/api/groups/:groupID/collections/:collectionKey/items/tags": function ()
"/api/groups/:groupID/collections/:collectionKey/items/top": function ()
"/api/groups/:groupID/collections/:collectionKey/items/top/tags": function ()
"/api/groups/:groupID/collections/top": function ()
"/api/groups/:groupID/items": function ()
"/api/groups/:groupID/items/:itemKey": function ()
"/api/groups/:groupID/items/:itemKey/children": function ()
"/api/groups/:groupID/items/:itemKey/file": function ()
"/api/groups/:groupID/items/:itemKey/file/view": function ()
"/api/groups/:groupID/items/:itemKey/file/view/url": function ()
"/api/groups/:groupID/items/tags": function ()
"/api/groups/:groupID/items/top": function ()
"/api/groups/:groupID/items/top/tags": function ()
"/api/groups/:groupID/items/trash": function ()
"/api/groups/:groupID/items/trash/tags": function ()
"/api/groups/:groupID/items/trash/top": function ()
"/api/groups/:groupID/items/trash/top/tags": function ()
"/api/groups/:groupID/searches": function ()
"/api/groups/:groupID/searches/:searchKey": function ()
"/api/groups/:groupID/searches/:searchKey/items": function ()
"/api/groups/:groupID/tags": function ()
"/api/groups/:groupID/tags/:tag": function ()
"/api/itemFields": function ()
"/api/itemTypeCreatorTypes": function ()
"/api/itemTypeFields": function ()
"/api/itemTypes": function ()
"/api/schema": function ()
"/api/users/:userID/collections": function ()
"/api/users/:userID/collections/:collectionKey": function ()
"/api/users/:userID/collections/:collectionKey/collections": function ()
"/api/users/:userID/collections/:collectionKey/items": function ()
"/api/users/:userID/collections/:collectionKey/items/tags": function ()
"/api/users/:userID/collections/:collectionKey/items/top": function ()
"/api/users/:userID/collections/:collectionKey/items/top/tags": function ()
"/api/users/:userID/collections/top": function ()
"/api/users/:userID/groups": function ()
"/api/users/:userID/groups/:groupID": function ()
"/api/users/:userID/items": function ()
"/api/users/:userID/items/:itemKey": function ()
"/api/users/:userID/items/:itemKey/children": function ()
"/api/users/:userID/items/:itemKey/file": function ()
"/api/users/:userID/items/:itemKey/file/view": function ()
"/api/users/:userID/items/:itemKey/file/view/url": function ()
"/api/users/:userID/items/tags": function ()
"/api/users/:userID/items/top": function ()
"/api/users/:userID/items/top/tags": function ()
"/api/users/:userID/items/trash": function ()
"/api/users/:userID/items/trash/tags": function ()
"/api/users/:userID/items/trash/top": function ()
"/api/users/:userID/items/trash/top/tags": function ()
"/api/users/:userID/publications/items": function ()
"/api/users/:userID/publications/items/tags": function ()
"/api/users/:userID/publications/items/top": function ()
"/api/users/:userID/searches": function ()
"/api/users/:userID/searches/:searchKey": function ()
"/api/users/:userID/searches/:searchKey/items": function ()
"/api/users/:userID/settings": function ()
"/api/users/:userID/tags": function ()
"/api/users/:userID/tags/:tag": function ()
"/better-bibtex/cayw": function Handler()
"/better-bibtex/collection": function CollectionHandler()
"/better-bibtex/export/collection": function CollectionHandler()
"/better-bibtex/export/item": function ItemHandler()
"/better-bibtex/export/library": function LibraryHandler()
"/better-bibtex/export/selected": function SelectedHandler()
"/better-bibtex/json-rpc": function Handler2()
"/better-bibtex/library": function LibraryHandler()
"/better-bibtex/select": function SelectedHandler()
"/connector/attachmentProgress": function Progress()
"/connector/delaySync": function DelaySync()
"/connector/detect": function Detect()
"/connector/document/execCommand": function "/connector/document/execCommand"()
"/connector/document/respond": function "/connector/document/respond"()
"/connector/getClientHostnames": function GetClientHostnames()
"/connector/getSelectedCollection": function GetSelectedCollection()
"/connector/getTranslatorCode": function GetTranslatorCode()
"/connector/getTranslators": function GetTranslators()
"/connector/ieHack": function IEHack()
"/connector/import": function Import()
"/connector/installStyle": function InstallStyle()
"/connector/ping": function Ping()
"/connector/proxies": function Proxies()
"/connector/request": function Request()
"/connector/saveItems": function SaveItems()
"/connector/savePage": function SavePage()
"/connector/saveSingleFile": function SaveSingleFile()
"/connector/saveSnapshot": function SaveSnapshot()
"/connector/selectItems": function SelectItems()
"/connector/sendToBack": function "/connector/sendToBack"()
"/connector/sessionProgress": function SessionProgress()
"/connector/updateSession": function UpdateSession()
"/integration/macWordCommand": function "/integration/macWordCommand"()
```

**Comment by retorquere** [comment]
Can you try version 54 I just uploaded?

**Comment by carllx** [comment]
@retorquere, Thank you very much for your continued attention to this issue and for providing a new version for testing. I have attempted to update to version 54 that you just uploaded, but unfortunately, the problem still persists.

The specific situation is as follows:

1. I updated to the latest version.
2. Executed the following curl command:

   ```
   curl -v -H "Content-Type: application/javascript" --data 'return 4' "http://127.0.0.1:23119/debug-bridge/execute"
   ```

3. The response is still:

   ```
   No endpoint found
   ```

4. When checking Zotero.Server.Endpoints in the Error Console, I still don't see the "/debug-bridge/execute" endpoint.

It appears that after updating to the new version, the debug-bridge issue remains unresolved.

**Comment by retorquere** [comment]
Does debug bridge show as installed and active in the plugins pane?

**Comment by retorquere** [comment]
Wait you don't have debug bridge installed according to `436PJ9GD-apse`?

**Comment by retorquere** [comment]
That would of course explain why you don't have the endpoint.

**Comment by carllx** [comment]
Thank you very much for your patient help @retorquere I have tried installing version 701 and its beta versions and have reinstalled versions 67210 67212 67218 67221 and 67222 of the BBT plugin However I am still unable to successfully use the Endpoints feature and I dont see the debug bridge option in the plugin panel To solve my personal problem I wrote an Endpoint myself I guess this might be a special case and it seems that only I have encountered this issue at the moment Therefore I have decided to close this issue.

**Comment by retorquere** [comment]
Uh that's fine, but those are all BBT builds, and does not include debug bridge. Debug bridge is a separate plugin, found at https://github.com/retorquere/zotero-better-bibtex/blob/master/test%2Ffixtures%2Fdebug-bridge%2FREADME.md
