### ISSUE TITLE
Cannot search an item using its citation key after being related to another item

### ISSUE THREAD

**Issue by paluanium** [retorquere/zotero-better-bibtex#2949]
### Debug log ID

WXB4C2HE-refs-euc/6.7.221-6

### What happened?

If I try to relate an item A with another item B by in the Related tab of item A clicking the Add button and add item B, then after that I cannot search the item B using its citation key. If I then restart Zotero then I can search for B again with its citation key again, but the problem comes back whenever I perform the above action.

**Comment by retorquere** [comment]
This build doesn't fix it but adds logging, please reproduce and send a new log.

Zotero will likely report the build incompatible, you can ignore that, it's running.

**Comment by paluanium** [comment]
Hello @retorquere I followed your instruction and sent a new log. Thanks.

**Debug log ID**
AT8NB3BP-refs-euc/6.7.221.2949.6759-6

**Comment by retorquere** [comment]
A new log please?

**Comment by paluanium** [comment]
Here is the new log.
[6V7S8QED-refs-euc.zip](https://github.com/user-attachments/files/16644142/6V7S8QED-refs-euc.zip)

**Comment by retorquere** [comment]
Thanks, I'll have a look when I get home.

You've chosen to attach rather than send via the BBT dialog, is log submission failing? If so I need to look at that too.

**Comment by paluanium** [comment]
Actually I misunderstood that you preferred a direct attachment than a log ID.
If it is more convenient for you then I can re-send via a log submission? Thank you anyway.

**Comment by retorquere** [comment]
A log id is preferred; I have tooling that downloads and unpacks it from which I can create anti-regression testcases automatically, and it's also more private (only I can see the contents. But attach works, and I have the information I need, so no need for a new log; I can get a fix out if this [redacted] internet connection allows me to log in.

**Comment by paluanium** [comment]
This latest build fixed the issue. Many thanks.
