### ISSUE TITLE
Getting different sort orders on different computers

### ISSUE THREAD

**Issue by yakatz** [retorquere/zotero-better-bibtex#2952]
### Debug log ID

5IVN5XPQ-refs-euc/6.7.222-7

### What happened?

I check my `.bib` files into git. I have the sorting option set to the new sort by creation date option (#2929), I get different sort orders on different computers. The only difference between them is one is Windows 10 and one is Windows 11. The versions of Zotero and this plugin are the same. When I change the order to citation key, I get the same results (with one difference and I will open a separate bug report for that). I can't find any reason that the order would be different. The collections are synced through my Zotero account.

**Comment by retorquere** [comment]
I need you to test this version to see if it solves the problem for you.

**Comment by yakatz** [comment]
It looks like this is no longer an issue with `6.7.226`
