### ISSUE TITLE
No `Citation key` column after update to the latest version

### ISSUE THREAD

**Issue by paluanium** [retorquere/zotero-better-bibtex#2959]
### Debug log ID

S48XPNMU-euc/6.7.225-6

### What happened?

I've just updated the the Better Bibtex to the latest version within the addon manager of Zotero 6. After restarting, the `Citation key` column disappeared.

**Comment by paluanium** [comment]
This build fixed the issue. Thank you.

**Comment by phamdn** [comment]
same problem. But the test build works

**Comment by retorquere** [comment]
release build is running
