### ISSUE TITLE
[Bug] Better bibtex cause zotero crash (plugin conflicts may exist)

### ISSUE THREAD

**Issue by opacscdbph44** [retorquere/zotero-better-bibtex#2961]
### Debug log ID

JZDJ5FHD-apse/6.7.225-7

### What happened?

The software crashed due to better bibtex. I'm not sure what happened.
As soon as I disable better bibtex, everything is back to normal.

Seems to be conflicting with the Ethereal Reference plugin (maybe other plugins, I cannot confirm the specific conflicts that still exist.).
When I only enable "Ethereal Reference" and "better bibtex": IQ9YRKAP-apse/6.7.225-7

**Comment by opacscdbph44** [comment]
> 🤖 this is your friendly neighborhood build bot announcing [test build 6.7.225.6834](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.225.6834.xpi) ("simple logger")
> 
> This update may name other issues, but the build just dropped here is for you; it just means problems already fixed in other issues have been folded into the work we are doing here. Install in Zotero by downloading [test build 6.7.225.6834](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.225.6834.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

I tried 6.7.225, It randomly works, randomly crash :SDJ3ZNAI-apse/6.7.225.6834-7; RFP8UPB9-apse/6.7.225.6834-7

I also tried 6.7.226, it also will cause zotero crash: VVDLKAGX-apse/6.7.226-7; BI2ANUZS-apse/6.7.226-7

**Comment by retorquere** [comment]
A new log please.

**Comment by retorquere** [comment]
without further followup I am going to have to close this issue.

**Comment by retorquere** [comment]
closed for inactivity
