### ISSUE TITLE
Better CSL does not extract extra variables

### ISSUE THREAD

**Issue by nateinla** [retorquere/zotero-better-bibtex#2963]
### Debug log ID

8HMFT7MM-refs-euc/6.7.226-7

### What happened?

Hi there. Thanks so much for this terrific plugin!
I'm trying to get add a postscript to BBT to export a CSL variable from the Extra field. However, any script I add is exported as as the field "postscript": [code]. I've included a short debug script in the debug example I uploaded.

I expect this has to do with the "ae:sql:get: undefined is not a string but a undefined" error, but I'm a total noob.

Thanks in advance for your guidance!

**Comment by retorquere** [comment]
> I'm trying to get add a postscript to BBT to export a CSL variable from the Extra field. However, any script I add is exported as as the field "postscript": [code]. I've included a short debug script in the debug example I uploaded.

I can't yet reproduce this. I get the simple log message as expected. I don't yet know by what path this could end up as a field "postscript" in the output CSL. Can you send a new log and tick the "include cache" option?

> I expect this has to do with the "ae:sql:get: undefined is not a string but a undefined" error

No relation.

**Comment by retorquere** [comment]
A debug build will drop here in a few minutes, please install it, export again, and send a new log.

**Comment by nateinla** [comment]
### Debug log ID

R52FBFKP-euc/6.7.226.6867-7

**Comment by retorquere** [comment]
Can you reset the cache, export again, and send a new log?

**Comment by retorquere** [comment]
I don't see the translator running. A new build will drop soon, please generate a new log from that.

**Comment by nateinla** [comment]
### Debug log ID

NW6FZ38F-euc/6.7.226.6870-7

**Comment by retorquere** [comment]
`NW6FZ38F-euc` shows the CSL to be 

```
{"id":"11spreadmoderndemocracy_","type":"article-journal","language":"en","source":"Zotero","title":"11. The spread of modern democracy","citation-key":"11spreadmoderndemocracy_"}
```

before and after the postscript has ran. A new build will drop soon, please generate a new log, but can you also post the actual output you are getting?

**Comment by nateinla** [comment]
### Debug log ID

JCYNWNHC-euc/6.7.226.6875-7

json attached. Thanks!
[Exported Items.json](https://github.com/user-attachments/files/16808230/Exported.Items.json)

**Comment by retorquere** [comment]
I don't see a CSL JSON export in `JCYNWNHC-euc/6.7.226.6875-7`, and that `Exported Items.json` does not contain the text `postscript`.

**Comment by retorquere** [comment]
You are exporting as `BetterBibTeX JSON`, which is BBTs debug format (and it's also used for automation). You want `Better CSL JSON`.

**Comment by nateinla** [comment]
Thanks. I've set the export format to Better CSL JSON, and I don't see the postscript anymore. 

But, I've tried adding my actual JS to the scripting section and I'm still not seeing my CSL variable ("GSCC") still listed under the "notes" field. JSON attached.
[Exported Items.json](https://github.com/user-attachments/files/16808452/Exported.Items.json)


Here's the script I've added:

`if (Translator.BetterBibTeX) {
  if (this.extraFields && this.extraFields.extra) {
    let citeCount = this.extraFields.extra.find(field => field.name === 'GSCC');
    if (citeCount) {
      this.add({ name: 'GSCC', value: citeCount.value });
    }
  }
}`

FYI, my ultimate goal is to get this field to show up in Obsidian using the Zotero Integration plugin.

**Comment by retorquere** [comment]
The script you posted will only do stuff in the `Better BibTeX` translator, and `.add` is specific to the TeX translators; CSL uses simple object manipulation. You want something like

```
if (Translator.BetterCSL) {
  if (extra.kv.GSCC) csl[GSCC] = extra.kv.GSCC
}
```

**Comment by retorquere** [comment]
> listed under the "notes" field. 

I am not sure what you mean by this.

**Comment by nateinla** [comment]
> > listed under the "notes" field.
> 
> I am not sure what you mean by this.

In the JSON I see the CSL variable under "note":"GSCC: 0021819 \nmy-note: testing" which includes everything in the Extra field.

I tried the script 

`if (Translator.BetterCSL) {
  if (extra.kv.GSCC) csl.GSCC = extra.kv.GSCC
}'

But that's not pulling it out. I looked at your Extra fields doc and the Scripting doc, but I'm lost. Should the code above be enough to pass a new CSL variable that's used in the Extra field?

**Comment by retorquere** [comment]
`8HMFT7MM-refs-euc/6.7.226-7` does not contain a line

```
GSCC: something
```

so there's nothing to pull out.

**Comment by retorquere** [comment]
But there is an error somewhere. I'll look into it tomorrow.

**Comment by retorquere** [comment]
This will do it now:

```
if (Translator.BetterCSL) {
  if (extra.raw.gscc) csl.GSCC = extra.raw.gscc
}
```

the `.kv` variables only support equivalents of Zotero fields, the `.raw` fields have any colon-separated value in `extra`.

**Comment by nateinla** [comment]
Thanks! GSCC is showing up in the json export.

Now I need to figure out how to get the Zotero Integration plugin to recognize it. For another day!
