### ISSUE TITLE
PhD thesis not exported correctly

### ISSUE THREAD

**Issue by firubat** [retorquere/zotero-better-bibtex#2966]
### Debug log ID

PSMULG4S-euc/6.7.226-7

### What happened?

I have a Zotero entry with "Item type: Thesis" and "Type: PhD thesis".
it is exported as 
```
@thesis{key,
  type = {phdthesis},
etc...}
```
As I understand [from here](https://github.com/retorquere/zotero-better-bibtex/issues/2428) (and other places) it should have been exported as `@phdthesis{key, ...}`.

**Comment by retorquere** [comment]
I need a `-refs` log (right-click entry, better bibtex, send debug log). Are you exporting as bibtex or as biblatex?

**Comment by firubat** [comment]
Seems that it was biblatex, and bibtex does actually\export as I expected. Is that the expected behavior in biblatex?

This is the log for the biblatex export 
64V7VIWD-refs-euc/6.7.226-7

**Comment by firubat** [comment]
Oh I see, my apologies then, I was not aware of this distinction. So I think it can be closed.
