### ISSUE TITLE
zotero.lua throwing an error when internet disabled

### ISSUE THREAD

**Issue by mcvmcvmcvmcv** [retorquere/zotero-better-bibtex#2968]
### Debug log ID

R6SDZ2VY-apse/6.7.226-6

### What happened?

When was converting a file from .md to .docx using pandoc, I received the following error while I had wifi disabled on my computer:

> Error running filter /Users/MYNAME/.local/share/pandoc/filters/zotero.lua:
> Could not fetch https://retorque.re/zotero-better-bibtex/exporting/zotero.lua.revision
> HttpExceptionRequest Request {
>   host                 = "retorque.re"
>   port                 = 443
>   secure               = True
>   requestHeaders       = []
>   path                 = "/zotero-better-bibtex/exporting/zotero.lua.revision"
>   queryString          = ""
>   method               = "GET"
>   proxy                = Nothing
>   rawBody              = False
>   redirectCount        = 10
>   responseTimeout      = ResponseTimeoutDefault
>   requestVersion       = HTTP/1.1
>   proxySecureMode      = ProxySecureWithConnect
> }
>  (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: "retorque.re", service name: "443"): does not exist (nodename nor servname provided, or not known))
> stack traceback:
> 	/Users/MYNAME/.local/share/pandoc/filters/zotero.lua:3: in main chunk

When I turned wifi back on, the file processed without any issue. The part of the zotero.lua file that is at issue is: 

>   local mt, latest = pandoc.mediabag.fetch('https://retorque.re/zotero-better-bibtex/exporting/zotero.lua.revision')

I would like to be able to process files with wifi off, so is there some way to get around this? Many thanks in advance for your time.

**Comment by retorquere** [comment]
New version online that makes the call soft-fail

**Comment by mcvmcvmcvmcv** [comment]
Hmm, now I get the following error, which throws whether I am online or not:

> Error running filter /Users/MYNAME/.local/share/pandoc/filters/zotero.lua:
> /Users/MYNAME/.local/share/pandoc/filters/zotero.lua:3: attempt to index a nil value (global 'json')
> stack traceback:
> 
> 
> -----------------
> 
> zotero-live-citations 199d652

**Comment by retorquere** [comment]
new version is up

**Comment by mcvmcvmcvmcv** [comment]
Yes, that works perfectly, thank you.

**Comment by mcvmcvmcvmcv** [comment]
Yes, that works perfectly, thank you.
