### ISSUE TITLE
Better BibTeX Startup Failed - NotFoundError: IDBDatabase.transaction: 'metadata' is not a known object store name

### ISSUE THREAD

**Issue by luisgsalazar** [retorquere/zotero-better-bibtex#2971]
### Debug log ID

7GUJZ2AS-fio-moYPaeImq1sd

### What happened?

I updated Zotero to Zotero 7 and when I opened Zotero a window with the message "Better BibText Startup Failed - NotFoundError: IDBDatabase.transaction: 'metadata' is not a known object store name"  appeared. 

I have an Obsidian-Zotero pipeline, even though Zotero is running and Better BibTex plugin has been downloaded it does not work either.

Help, please!

**Comment by retorquere** [comment]
A test build will drop here shortly, please install and test

**Comment by luisgsalazar** [comment]
Thank you so much!

The problem is solved with the test build.

Cheers!
