### ISSUE TITLE
Install Zotero 7: Where do I find the XPI file?

### ISSUE THREAD

**Issue by satikusala** [retorquere/zotero-better-bibtex#2976]
### Debug log ID

N/A

### What happened?

I'm sorry, I suspect that this is a REALLY silly question, but I'm not familiar with GitHub. Where do I find the XPI file to install Zotero 7? The readme direct you to the old Zotero 6 BBT instructions. Thanks.

**Comment by retorquere** [comment]
Where are these instruction? I don't have any specific instructions for 6 or 7, the xpi is compatible with both.

**Comment by satikusala** [comment]
In the readme (https://github.com/retorquere/zotero-better-bibtex/blob/master/README.md the Installation Instructions under Getting Started (https://retorque.re/zotero-better-bibtex/installation/) to to the main website for 6.

My question is where can I find and download the XPI file for 7. I must be missing something simple.

**Comment by retorquere** [comment]
> Getting Started (https://retorque.re/zotero-better-bibtex/installation/) to to the main website for 6.

The only mention of 6 is

> Restart Zotero if you’re using Zotero 6

So in other words, if you're not using zotero 6, don't restart.

> My question is where can I find and download the XPI file for 7. I must be missing something simple.

There is no "xpi file for 7". There is one xpi file, which, again, is compatible with both 6 and 7. I don't know how else to explain this.

**Comment by satikusala** [comment]
Oh, I get it. the XPI file that you download is dynamic, and it will grab the appropriate code from GitHub for 6 or 7 (at least that is what I think you’re saying).

Thanks. :) Looks like I got it working.

Michael

**Comment by retorquere** [comment]
> Oh, I get it. the XPI file that you download is dynamic, and it will grab the appropriate code from GitHub for 6 or 7 (at least that is what I think you’re saying).

No, it's one xpi and no code is fetched dynamically. It just works on both 6 and 7.

**Comment by satikusala** [comment]
Cool, thanks so much. I understand now. I appreciate your patience with my questions.
