### ISSUE TITLE
Implement or improve documentation of sortkey in the extra fields

### ISSUE THREAD

**Issue by zackbatist** [retorquere/zotero-better-bibtex#2977]
### Debug log ID

7T4QGVJV-euc/6.7.227-7

### What happened?

I'm trying to modify the sorting of bibliographic entries in latex by appending SORTKEY as an extra field for the entries that I would like to manually sort (as per https://tex.stackexchange.com/questions/128387/sort-bibliography-with-same-author-and-same-year-biblatex). However it's not clear to me whether this is actually implemented at all in betterbibtex, since it is not included in the table of extra fields (https://retorque.re/zotero-better-bibtex/exporting/extra-fields/index.html). If it is a current feature, some clarification on how to implement this in practice would be really helpful.

Thank you.

**Comment by retorquere** [comment]
> However it's not clear to me whether this is actually implemented at all in betterbibtex

It is not; there is no Zotero field that carries this meaning, and items in Zotero have no intrinsic order, so I have no information I could base this on.

> since it is not included in the table of extra fields

which means it is not available this way, this list is exhaustive

> If it is a current feature, some clarification on how to implement this in practice would be really helpful.

using the [BBT-specific](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/index.html#bbt-specific) format, from the same page:

```
tex.sortkey: something
```

**Comment by zackbatist** [comment]
Thank you for pointing out the BBT-specific format. It is still not accomplishing what I need it to do, I suspect it may have to do with how this is outputting as an annotation, as per:

`\field{annotation}{SORTKEY = \{b\}}`

I'm still trying to figure out how it _should_ be output and to modify my input string accordingly. I will post if/when I figure it out, for future reference.

**Comment by zackbatist** [comment]
The solution is to use `=` instead of `:`, as per the instructions under the BBT-specific heading on support page to generate "raw latex". Moreover, I used `tex.SORTTITLE` rather than `tex.SORTKEY`; the latter put the one labelled `{a}` at the top of the entire bibliography, whereas the former sorts only the items with the same authors and years.
