### ISSUE TITLE
Zotero does not close without of focus with Better BibTex enabled

### ISSUE THREAD

**Issue by doncip** [retorquere/zotero-better-bibtex#2980]
### Debug log ID

Unable to generate it

### What happened?

I am using a Mac with macOS version 14.6.1, M1 processor, with Zotero 7.
When Better BibTex is enabled, Zotero does not exit if the main window is out of focus.
This happens if I try to exit by clicking on the dock icon or if I try to restart the computer without closing Zotero beforehand.
I was not able to generate the report, because Zotero can only be closed by forcing it and the report is lost.

**Comment by retorquere** [comment]
reproducible

**Comment by doncip** [comment]
Yes, problem solved! Thank you very much!
