### ISSUE TITLE
Citekey with Short Title No Longer Working

### ISSUE THREAD

**Issue by darrylmy** [retorquere/zotero-better-bibtex#2985]
### Debug log ID

4SI55C4J-refs-euc/6.7.229-7

### What happened?

I just updated from the beta to Zotero 7.0.5 and Better BibTex 6.7.227, and the citekey is no longer using the Short Title for the citekey, but rather, the Title. I have confirmed this by changing both fields and the Citekey changes when the Title field is changed.

Here is what I have for the citekey generator which was, but is no longer working:

authEtAl.nopunct + year + shorttitle(2,2)

Can this be looked into for a fix?

**Comment by retorquere** [comment]
This has always been the behavior of `shortTitle`. `shortTitle` picks from the Zotero `Title` field of the item, and by instructing it to take two words, you end up with `SemanticsBiblical`. If you want the Zotero `Short title` in the citekey, you must use `ShortTitle`. The leading capital instructs BBT to take a Zotero field, verbatim.

**Comment by darrylmy** [comment]
Okay, I must have misunderstood. I thought that shortTitle meant use the Short Title field, and (2,2) would take two words (if there are more than two). So any Short Title field with only one word would have one word in the citekey.

Is it possible to specific the Short Title field and still instruct it to take only a maximum of two words?

**Comment by retorquere** [comment]
Yes: `ShortTitle.select(n=2)`

**Comment by darrylmy** [comment]
Great, thank you for your help! Sorry for my misunderstanding.

**Comment by dstark** [comment]
> This has always been the behavior of `shortTitle`. `shortTitle` picks from the Zotero `Title` field of the item, and by instructing it to take two words, you end up with `SemanticsBiblical`. If you want the Zotero `Short title` in the citekey, you must use `ShortTitle`. The leading capital instructs BBT to take a Zotero field, verbatim.

Thanks so much! I've been searching for this off and on. One thing I'm seeing though in Zotero 7.0.6 beta (Windows 10) is that if I

- already have an item with a citekey,
- change the citekey from a different pattern to use `ShortTitle`, and
- refresh a citeky with this new pattern,

then the citekey

- still displays as the old citekey in the library pane and
- the citation key box in the item info pane goes blank

This is just a matter of the display to the user, though. The change to the citekey actually does get applied. If I duplicate the item, it will that duplicate will reflect the old citekey. If I then refresh the duplicate's citekey to apply the new pattern to it, I'll get `a` to differentiate it from the old item. And after restarting Zotero after the change in the citekey pattern, the display to the user shows the current citekeys for both items and other citekey refreshes display instantly as expected.

**Comment by retorquere** [comment]
Is this specific to the beta?

**Comment by retorquere** [comment]
(this is a different issue though; I'd appreciate it if you could open a new issue so `darrylmy` doesn't get notifications of updates unrelated to the issue originally posted)
