### ISSUE TITLE
cannot update citekeys

### ISSUE THREAD

**Issue by SophieHerbst** [retorquere/zotero-better-bibtex#2986]
### Debug log ID

JJH3CGQG-refs-euc/6.7.229-7

### What happened?

I would like citations in my word document to appear as author_shorttitle(1)_year, to use text snippets from previously written .docx files in latex. I installed BBT and updated zotero. The BBT style works without errors, but I cannot get the cite-keys to change. I edited in the settings field as shown by the screenshots, but even after refreshing the citations or restarting word and zotero, the citations in my docx keep the format @Authorshorttitle(3)year, which was the default. 
What am I missing?
<img width="614" alt="Screenshot 2024-09-16 at 17 46 22" src="https://github.com/user-attachments/assets/05c15e8a-f9a6-4606-b6ce-d09fc5c547ae">

**Comment by retorquere** [comment]
You are missing a debug log 🤷

**Comment by SophieHerbst** [comment]
I edited the above post with the reference: VZWLYMVH-refs-euc/6.7.229-7
[ApplicationContext.txt](https://github.com/user-attachments/files/17016473/ApplicationContext.txt)
[Errors.txt](https://github.com/user-attachments/files/17016474/Errors.txt)
[DebugLog.txt](https://github.com/user-attachments/files/17016475/DebugLog.txt)

**Comment by retorquere** [comment]
No need to attach logs, that's what the debug logs are for. I think you are experiencing the same problem as # #2948, can you see if the latest build there solves the problem for you?

**Comment by SophieHerbst** [comment]
Thank you so much for your rapid help. At first, I thought it works, but it is not the case for all citations. 
Here is a report for one where it doesn't work (I still get the default string): IMU874X4-refs-euc/6.7.230-7
I tried refreshing, but it doesn't change.
And this one, where it works as expected: 7ARYV2FQ-refs-euc/6.7.230-7

**Comment by retorquere** [comment]
7ARYV2FQ-refs-euc is not from build 6993.

**Comment by SophieHerbst** [comment]
Sorry, I had overlooked the latest built 'there' and just reinstalled the latest built from the general repository.
It works as expected now. Thank you so much for your help and patience with my rookie mistakes.

**Comment by retorquere** [comment]
No worries, and thanks for the confirmation. 6993 is rolling out to release now.
