### ISSUE TITLE
Use "nonacademic" entrysubtype in place of "newspaper/magazine" for biblatex-apa

### ISSUE THREAD

**Issue by chayaninw** [retorquere/zotero-better-bibtex#2987]
### Debug log ID

WMK9XZ9K-refs-euc/6.7.231-7

### What happened?

The `biblatex-apa` package uses the `entrysubtype` "nonacademic" for newspaper articles and other non-academic articles. (Section 4.2.3 of the [`biblatex-apa` documentation](https://ftp.rrze.uni-erlangen.de/ctan/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa.pdf)).

Currently, BBT by default would insert `entrysubtype = {newspaper}` or `entrysubtype = {magazine}` when exporting respective item types. Since BBT now has a dedicated export option for `biblatex-apa`, I would propose that the "nonacademic" subtype is used instead if the `biblatex-apa` option is selected.

**Comment by retorquere** [comment]
Can you post how you think the resulting entry from `WMK9XZ9K-refs-euc/6.7.231-7` should look like?

**Comment by chayaninw** [comment]
Thank you! As far as I can tell, the exported entry from build 7017 should fit what `biblatex-apa` expects, and the compiled bibliography matches APA7 prescriptions.
