### ISSUE TITLE
The send to file.io option sometimes disappears on the help menu

### ISSUE THREAD

**Issue by dstark** [retorquere/zotero-better-bibtex#2991]
### Debug log ID

AIS78KF7-fio-oThpGgibQu8e

### What happened?

In Zotero 7.0.5 on Windows 10, the `send to file.io` option disappears from the help menu shortly after starting Zotero. I've tried to submit a log for this issue at the noted ID, but I'm not sure if it's captured anything useful. Here are a couple screenshots taken less than 30 seconds apart.

![image](https://github.com/user-attachments/assets/b3a4d070-304b-4011-9d61-1a11e17172ef)
![image](https://github.com/user-attachments/assets/ba90706d-4ff3-45a1-93b8-85019c903817)

**Comment by retorquere** [comment]
File.io disappears 15 seconds after BBT started successfully.

**Comment by retorquere** [comment]
If you need it to stay you can install https://github.com/retorquere/zotero-debug-log

**Comment by dstark** [comment]
Ah, got it. Makes sense if that's intended behavior. Just wasn't something I was aware of. Thanks so much for the clarification!
