### ISSUE TITLE
using zotero://select to select multiple citationkeys.

### ISSUE THREAD

**Issue by jshahin** [retorquere/zotero-better-bibtex#2993]
### Debug log ID

GX62HJIN-euc/6.7.231-7

### What happened?

I would like to be able to select more than one citationkey using the zotero://select function. this currently does not work in BBT.

**Comment by retorquere** [comment]
Please try with this build (which will fail) and then send a new log.

**Comment by retorquere** [comment]
still interested?

**Comment by jshahin** [comment]
Yes, sorry, it’s a crazy fortnight; teaching both in NL and Belgium, and conferences. Will try tomorrow if OK with you, sorry for the delay!!On 26 Sep 2024, at 08:46, Emiliano Heyns ***@***.***> wrote:﻿
still interested?

**Comment by retorquere** [comment]
No problem, trust me, I know how that is.

**Comment by jshahin** [comment]
Hi Emiliano

As promised, I have run, and yes, it failed :). On entering: 

***@***.***

Into my browser, Zotero ‘beachballed' for a very long time, and then selected everything. One other weird thing: it opened all the triangles (so makes all attachments visible in the list view in my library (see screenshot).

J2TJ8TCZ-euc/6.7.234.7043-7

All the best,
-Jamal

￼

**Comment by retorquere** [comment]
I need a log from just after it fails.

**Comment by retorquere** [comment]
sorry, didn't read beneath the cut.

**Comment by jshahin** [comment]
Do I need to do anything extra then?

**Comment by retorquere** [comment]
new log please

**Comment by jshahin** [comment]
It worked?!

RV852YNM-euc/6.7.236.7089-7

Wow!!

Best wishes,  
-Jamal

**Comment by retorquere** [comment]
Also for multiple then?

**Comment by jshahin** [comment]
How do I write out multiple? Separate with an &?Sorry, amateur hour here :-)On 27 Sep 2024, at 13:48, Emiliano Heyns ***@***.***> wrote:﻿
Also for multiple then?

**Comment by retorquere** [comment]
Just as you would with multiple item keys.

**Comment by jshahin** [comment]
so, after referring to: https://forums.zotero.org/discussion/75794/feature-request-allow-multiple-item-selection-with-zotero-select, I tried zotero://select/library/items?citationKey=gerring2008,gerring2009 and that did nothing. 

Neither did: zotero://select/library/items?citationKey=@gerring2008,@gerring2009.

zotero://select/library/items/@gerring2008,@gerring2009 selected the entire library.

9DES2FYW-euc/6.7.238-7

**Comment by retorquere** [comment]
Please retry on build 7096

**Comment by jshahin** [comment]
Afraid the same experience as last time:

WASVVBWS-euc/6.7.238.7096-7

Best wishes,  
-J

**Comment by retorquere** [comment]
But does that actually work to select these items if you select them by their item keys?

**Comment by retorquere** [comment]
You can get the item keys by selecting some items and then going into Tools - Developer - Run Javascript and entering

```
ZoteroPane.getSelectedItems().map(item => item.key)
```

and press Run

**Comment by jshahin** [comment]
Thanks, I was just trying to find out how to do that. Indeed, that (see example below) works perfectly!

zotero://select/library/items?itemKey=ZPAGHTHD,SF46N4F2,IL6VAQU5,SK6QTBYT

Best wishes,  
-Jamal

**Comment by retorquere** [comment]
Can you send me a new log after you did that?

**Comment by jshahin** [comment]
Sure, here it is:

QUXZUENW-euc/6.7.238.7096-7

Carried out on: zotero://select/library/items?itemKey=P4FBPSLU,PNAR8RAH,9KK62BU8,IL6VAQU5,V5AK2CU3

**Comment by jshahin** [comment]
Hi! No change.

I carried out zotero://select on multiple itemkeys and that worked.

I carried out ***@***.******@***.******@***.******@***.******@***.*** and that didn’t seem to react, as well as some other variants (citationkey all in lower case, omitting the “/library” part).

Debug log:
3CJYSLZZ-euc/6.7.238.7100-7

**Comment by jshahin** [comment]
No change, sorry..

Tried zotero://select/library/items?itemKey=P4FBPSLU,PNAR8RAH,9KK62BU8,IL6VAQU5,V5AK2CU3 and that worked.

Tried: ***@***.******@***.******@***.******@***.******@***.*** and that doesn’t work

Tried: ***@***.*** and that doesn’t work either

But good old ***@***.*** does!

2EEJ62KS-euc/6.7.238.7103-7

**Comment by retorquere** [comment]
Most of the text posted is unreadable, sorry. Please use the web interface. The mail-response interface of github has a lot of issues.

I can see the first form in your logs, the other doesn't trigger my code. I'll have to dive into zotero to see what sanity checks it does to weed them out.

**Comment by jshahin** [comment]
Reposting: 

No change, sorry..

Tried zotero://select/library/items?itemKey=P4FBPSLU,PNAR8RAH,9KK62BU8,IL6VAQU5,V5AK2CU3 and that worked.

Tried: zotero://select/library/items?citationkey=@gerring2008,@gerring2008a,@gerring2009,@gersbach2005e,@gervais2013 and that doesn’t work

Tried: zotero://select/library/items?citationkey=@gerring2008 and that doesn’t work either

But good old zotero://select/library/items/@gerring2008 does!

**Comment by retorquere** [comment]
> Just as you would with multiple item keys.

it's

```
zotero://select/library/items?itemKey=@gerring2008,@gerring2008a,@gerring2009,@gersbach2005e,@gervais2013
```

not

```
zotero://select/library/items?citationkey=@gerring2008,@gerring2008a,@gerring2009,@gersbach2005e,@gervais2013
```

Zotero does not support `citationkey=` so my code never gets called.

**Comment by jshahin** [comment]
that works! (sorry, brief)
