### ISSUE TITLE
fail to export better bibtex

### ISSUE THREAD

**Issue by Hugo-Leung** [retorquere/zotero-better-bibtex#3000]
### Debug log ID

WP3UBB65-euc/6.7.238-7

### What happened?

I am trying to export a collection to a bibtex file, a white bar appear at the center but no file is written. The white bar remains until I restart zotero
<img width="664" alt="image" src="https://github.com/user-attachments/assets/cf1ec7e7-b21b-46bb-92c9-05dec8699fee">

**Comment by retorquere** [comment]
What path are you trying to export to? I'm seeing an "invalid path" error.

Also, what version of Zotero are you on? Your log says 7.0, mine say 7.0.6. Please make sure you're on the latest version of Zotero.

**Comment by Hugo-Leung** [comment]
> What path are you trying to export to? I'm seeing an "invalid path" error.

I am try to export to my home directory (/Users/cleung). I have no issue exporting with exporting a zotero built-in bibtex to the same directory.

> Also, what version of Zotero are you on? Your log says 7.0, mine say 7.0.6. Please make sure you're on the latest version of Zotero.
Yes I am using 7.0.6

**Comment by Hugo-Leung** [comment]
If it helps, I tried to downgrade Better Bibtex to 6.7.236 and it can successfully export to bibtex file.

**Comment by retorquere** [comment]
Nothing that changed between those versions would explain this.

I'm not seeing any export activity in `WP3UBB65-euc/6.7.238-7`. Can you recreate the problem and send a new log?

**Comment by Hugo-Leung** [comment]
Z5ZSN67Q-euc/6.7.238-7 is the log before exporting.
H3JYF94W-euc/6.7.238-7 is after I tried to export.

**Comment by retorquere** [comment]
Your logs now do say you're on 7.0.6. Strange. `WP3UBB65-euc` has multiple places where it reports being on 7.0.

What BBT translator are you using? I'm still seeing no export activity in `H3JYF94W-euc/6.7.238-7`, nor do I see any errors, so something must be (silently, which is weird) going wrong before the BBT translator kicks in. A new build will drop here, please install that, recreate the problem, then send a new log. It will give me more insight on what BBT is doing at the time you started the export.

**Comment by Hugo-Leung** [comment]
> Your logs now do say you're on 7.0.6. Strange. `WP3UBB65-euc` has multiple places where it reports being on 7.0.

It is possible zotero updated itself between the two logs

> What BBT translator are you using? 

better bibtex

>I'm still seeing no export activity in `H3JYF94W-euc/6.7.238-7`, nor do I see any errors, so something must be (silently, which is weird) going wrong before the BBT translator kicks in. A new build will drop here, please install that, recreate the problem, then send a new log. It will give me more insight on what BBT is doing at the time you started the export.

Let's hope this one will give us more information 4W4IMZX3-euc/6.7.238.7098-7

**Comment by Hugo-Leung** [comment]
Here is the new log QCV4JXBA-euc/6.7.238.7101-7

**Comment by seth4618** [comment]
Could this be related to issue #3001 ?

**Comment by Hugo-Leung** [comment]
Thank you for your work. Here is the new log: H5694XFG-euc/6.7.238.7107-7

**Comment by seth4618** [comment]
I tried the test build ...7107 and when loading a pop-up came up saying "blocked", but it appears to be loaded.  I tried exporting and got an error dialog that said an error occurred during export.  See log: 4IQCNLEH-fio-2bODeBcCiL0G.  More info also from the Error console:
```
14:33:57.677 NS_ERROR_NOT_AVAILABLE [better-bibtex.js:109219](jar:file:///home/seth/.zotero/zotero/jzd3acam.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js)
14:34:05.250 No citation key in {"version":3,"itemType":"journalArticle","title":"Breaking the filter bubble: democracy and design","abstractNote":"It has been argued that the Internet and social media increase the number of available viewpoints, perspectives, ideas and opinions available, leading to a very diverse pool of information. However, critics have argued that algorithms used by search engines, social networking platforms and other large online intermediaries actually decrease information diversity by forming so-called “filter bubbles”. This may form a serious threat to our democracies. In response to this threat others have developed algorithms and digital tools to combat filter bubbles. This paper first provides examples of different software designs that try to break filter bubbles. Secondly, we show how norms required by two democracy models dominate the tools that are developed to fight the filter bubbles, while norms of other models are completely missing in the tools. The paper in conclusion argues that democracy itself is a contested concept and points to a variety of norms. Designers of diversity enhancing tools must thus be exposed to diverse conceptions of democracy.","date":"2015-12-18","language":"En","shortTitle":"Breaking the filter bubble","libraryCatalog":"link.springer.com","url":"https://link.springer.com/article/10.1007/s10676-015-9380-y","accessDate":"2024-09-22T23:39:27Z","rights":"2015 The Author(s)","extra":"","volume":"17","pages":"249-265","publicationTitle":"Ethics and Information Technology","DOI":"10.1007/s10676-015-9380-y","issue":"4","ISSN":"1572-8439","creators":[{"firstName":"Engin","lastName":"Bozdag","creatorType":"author"},{"firstName":"Jeroen","lastName":"van den Hoven","creatorType":"author"}],"tags":[],"collections":["WRKEDJBS"],"relations":{},"dateAdded":"2024-09-22T23:47:03Z","dateModified":"2024-09-22T23:47:03Z","uri":"http://zotero.org/groups/5674905/items/SPVDCHUT","attachments":[{"version":5,"itemType":"attachment","title":"Full Text PDF","url":"https://link.springer.com/content/pdf/10.1007/s10676-015-9380-y.pdf","accessDate":"2024-09-22T23:39:28Z","parentItem":"SPVDCHUT","linkMode":"imported_url","contentType":"application/pdf","charset":"","filename":"Bozdag and van den Hoven - 2015 - Breaking the filter bubble democracy and design.pdf","tags":[],"relations":{},"dateAdded":"2024-09-22T23:47:03Z","dateModified":"2024-09-22T23:47:03Z","uri":"http://zotero.org/groups/5674905/items/JNE3IDZ3","localPath":"/home/seth/Zotero/storage/JNE3IDZ3/Bozdag and van den Hoven - 2015 - Breaking the filter bubble democracy and design.pdf"}],"notes":[],"$cacheable":false,"extraFields":{"raw":{"number":"4","publisher":"Springer"},"kv":{"number":"4","publisher":"Springer"},"creator":{},"creators":[],"tex":{},"citationKey":"","aliases":[]},"citationKey":""} [better-bibtex.js:139967](jar:file:///home/seth/.zotero/zotero/jzd3acam.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js)
14:34:05.270 No citation key in {"version":3,"itemType":"journalArticle","title":"Breaking the filter bubble: democracy and design","abstractNote":"It has been argued that the Internet and social media increase the number of available viewpoints, perspectives, ideas and opinions available, leading to a very diverse pool of information. However, critics have argued that algorithms used by search engines, social networking platforms and other large online intermediaries actually decrease information diversity by forming so-called “filter bubbles”. This may form a serious threat to our democracies. In response to this threat others have developed algorithms and digital tools to combat filter bubbles. This paper first provides examples of different software designs that try to break filter bubbles. Secondly, we show how norms required by two democracy models dominate the tools that are developed to fight the filter bubbles, while norms of other models are completely missing in the tools. The paper in conclusion argues that democracy itself is a contested concept and points to a variety of norms. Designers of diversity enhancing tools must thus be exposed to diverse conceptions of democracy.","date":"2015-12-18","language":"En","shortTitle":"Breaking the filter bubble","libraryCatalog":"link.springer.com","url":"https://link.springer.com/article/10.1007/s10676-015-9380-y","accessDate":"2024-09-22T23:39:27Z","rights":"2015 The Author(s)","extra":"","volume":"17","pages":"249-265","publicationTitle":"Ethics and Information Technology","DOI":"10.1007/s10676-015-9380-y","issue":"4","ISSN":"1572-8439","creators":[{"firstName":"Engin","lastName":"Bozdag","creatorType":"author"},{"firstName":"Jeroen","lastName":"van den Hoven","creatorType":"author"}],"tags":[],"collections":["WRKEDJBS"],"relations":{},"dateAdded":"2024-09-22T23:47:03Z","dateModified":"2024-09-22T23:47:03Z","uri":"http://zotero.org/groups/5674905/items/SPVDCHUT","attachments":[{"version":5,"itemType":"attachment","title":"Full Text PDF","url":"https://link.springer.com/content/pdf/10.1007/s10676-015-9380-y.pdf","accessDate":"2024-09-22T23:39:28Z","parentItem":"SPVDCHUT","linkMode":"imported_url","contentType":"application/pdf","charset":"","filename":"Bozdag and van den Hoven - 2015 - Breaking the filter bubble democracy and design.pdf","tags":[],"relations":{},"dateAdded":"2024-09-22T23:47:03Z","dateModified":"2024-09-22T23:47:03Z","uri":"http://zotero.org/groups/5674905/items/JNE3IDZ3","localPath":"/home/seth/Zotero/storage/JNE3IDZ3/Bozdag and van den Hoven - 2015 - Breaking the filter bubble democracy and design.pdf"}],"notes":[],"$cacheable":false,"extraFields":{"raw":{"number":"4","publisher":"Springer"},"kv":{"number":"4","publisher":"Springer"},"creator":{},"creators":[],"tex":{},"citationKey":"","aliases":[]},"citationKey":""} [better-bibtex.js:139967](jar:file:///home/seth/.zotero/zotero/jzd3acam.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js)

​
```

**Comment by retorquere** [comment]
That's all in `H5694XFG-euc/6.7.238.7107-7`. I'm looking into it.

**Comment by nwarford** [comment]
I wanted to comment to say that I'm having what seems to be a very similar issue.

Debug log: IP4I3DRY-euc/6.7.238-7

My campus IT department forced me to upgrade Zotero today (now I'm on 7.0.6) and I also get stuck on an "Exporting Items" screen.

<img width="1554" alt="Screenshot 2024-09-30 at 10 12 35 AM" src="https://github.com/user-attachments/assets/7023c3c6-bf33-465b-a65f-937e88bc60fb">

**Comment by Hugo-Leung** [comment]
This new test build works for me. And the new log is K2GNSYGE-euc/6.7.238.7110-7

**Comment by seth4618** [comment]
The test build ...7110 worked for me.

**Comment by seth4618** [comment]
Build ...7113 worked as well.

**Comment by Hugo-Leung** [comment]
Build 7113 works for me as well. Log: 6JS2D24W-euc/6.7.238.7113-7

**Comment by retorquere** [comment]
Please also try 7115 and 7116 (latter will drop in a bit)

**Comment by Hugo-Leung** [comment]
Build 7115 does not work for me. I got a stuck progress bar. Log: HDRRXS4G-euc/6.7.238.7115-7

**Comment by retorquere** [comment]
That confirms one problem then. I think 7116 will work, but that leaves the one change that's not in 7116 which I need to figure out.

**Comment by Hugo-Leung** [comment]
Build 7116 does not work for me log AN899SWP-euc/6.7.238.7116-7.

**Comment by Hugo-Leung** [comment]
Build 7117 works for me. Log: 8GMHIZZ6-euc/6.7.238.7117-7

**Comment by Hugo-Leung** [comment]
Build 7118 works for me. New Log:`H5G7NCJJ-euc/6.7.238.7118-7`

**Comment by seth4618** [comment]
It also works for me.

**Comment by Hugo-Leung** [comment]
Build 7121 works for me. Log: `5R5KCMNJ-euc/6.7.238.7121-7`

**Comment by retorquere** [comment]
Wow so I have found the problem and that was the very last place I suspected. Glaringly obvious now that I know. Release is going out now.

**Comment by retorquere** [comment]
thanks for helping figure this out.

**Comment by Hugo-Leung** [comment]
Thank you for your work. This just shows how important BBT is important to a lot of people.
