### ISSUE TITLE
Fail to Export - keepUpdated

### ISSUE THREAD

**Issue by juanpedroross** [retorquere/zotero-better-bibtex#3001]
### Debug log ID

CCQ4LGZE-fio-whIigELfVa4T

### What happened?

Hi, I am trying to export my library automatically. 

My debug log is 9CCQ4LGZE-fio-whIigELfVa4T. My problem is that I press Export Collection, select Better BibLatex, and then keep updated. The progress bar appears but never ends, and no error is thrown.

**Comment by seth4618** [comment]
I have a similar issue, but in my case I didn't check "keep updated".  See debug log id: LDU6KSNK-euc/6.7.238-7

**Comment by seth4618** [comment]
Just as an FYI, I downgraded to 6.7.236 and things work again.

**Comment by retorquere** [comment]
I'll see if I can just roll back those changes. No idea why this change made any difference.

**Comment by juanpedroross** [comment]
For me using the 6.7.236 version did not solved my problem. However in this case did appeared an error saying "there was an error" latter I can submit another log id trying that.

**Comment by juanpedroross** [comment]
I re-downloaded the version 6.7.236 and re-installed it, and now it is working :)!

**Comment by retorquere** [comment]
Can you try the last build from #3000?

**Comment by retorquere** [comment]
Please try upgrading to v6.7.240 and see if that solves the problem.

**Comment by seth4618** [comment]
It does!
