### ISSUE TITLE
Exporting Items hangs

### ISSUE THREAD

**Issue by seth4618** [retorquere/zotero-better-bibtex#3002]
### Debug log ID

LDU6KSNK-euc/6.7.238-7

### What happened?

I right click on a collection and "export collection..."  using format "better bibtex" with only "worker" checked.  It then goes ask for filename, I select one, and then shows "exporting items..." for ever.  All data should be in debug log.  This appears to happen on all collections, even those that had been previously exported correctly.

**Comment by juanpedroross** [comment]
I just uploaded other issue with exactly the same issue!

**Comment by seth4618** [comment]
Sorry I should have searched.  Will +1 your issue

-seth

**Comment by retorquere** [comment]
Do not +1 issues. Just subscribe.
