### ISSUE TITLE
Export bibTex to clipboard with one button click

### ISSUE THREAD

**Issue by lemingshen** [retorquere/zotero-better-bibtex#3006]
### Debug log ID

NA

### What happened?

I really appreciate the elegant design of Better BibTex. I'm wondering if we can add a new function, i.e., could you please add one more button on the right-side panel that directly exports the bibTex to the clipboard? 

For example,
![image](https://github.com/user-attachments/assets/5d4c3810-6f55-4168-877c-892a70650572)

**Comment by retorquere** [comment]
I can't place buttons there that do such a thing, that can only open and close sections.
