### ISSUE TITLE
Automatic export: Library not updating prior to export

### ISSUE THREAD

**Issue by tduncs** [retorquere/zotero-better-bibtex#3007]
### Debug log ID

PXB2BFA3-euc/6.7.236-7

### What happened?

My Library is no longer updating prior to export. Recently upgraded to Zotero 7, but it was working in Zotero 7 prior to this occurrence. I have it set to auto-export on change, but when I go to settings, it's showing the last update was Sep 23rd 2024, despite having made changes and added references since. I have status=green tick. The new additions are not present in the .bib file (the export itself runs fine). 
I have got to the limit on my online Zotero storage but this shouldn't affect the .bib ? 
Thank you

**Comment by retorquere** [comment]
You're not on the most recent version of BBT. If the latest doesn't work, see if the discussion in #3000 applies to you.

**Comment by tduncs** [comment]
Thanks. I've updated to the version in the other thread. 
My library still isn't updating prior to export. 
Log: GKI6YB9M-euc/6.7.238.7121-7

![image](https://github.com/user-attachments/assets/556db705-4533-4bea-98b6-d5ca121910b2)

**Comment by retorquere** [comment]
prior to export?

**Comment by tduncs** [comment]
As in, I can export the library fine, but it's an old version that isn't updating on change, as expected.

**Comment by tduncs** [comment]
Hmmm, so I've had another look - in settings the last update is showing as 23rd Sept (as in the screenshot). I've added several references since then, all of which are coming through into the .bib up to the 26th Sept. Then all four most recent from 30th Sept to today, don't exist in the .bib.

**Comment by tduncs** [comment]
Am I missing something - could it be to do with online storage - do I need to restart again?

**Comment by retorquere** [comment]
No relation to online storage. I was just confused with your wording. A new build is incoming that will tell me more about what is going on on your system.

**Comment by tduncs** [comment]
OK, thank you.

**Comment by retorquere** [comment]
please install, reproduce the problem, and send a new log.

**Comment by tduncs** [comment]
That seems to have worked! Back up and running.

**Comment by retorquere** [comment]
Can you check whether the regular release (.240) also works for you?

**Comment by tduncs** [comment]
That came up with a 'Blocked' popup when I installed from file, and now the citation key field has gone?

**Comment by tduncs** [comment]
Ok, that's good to know! I couldn't recreate the Blocked popup - but I removed and re-added the plugin, and started a new Auto-Export. And all seems to be working! 
Could you tell me one thing, while I've been changing the references to test all this, sometimes the citation key is added to the Extra field, and the citation key will only change based on a change to the author field if the text in Extra is removed. Is this expected behaviour? 
Thanks very much.

**Comment by retorquere** [comment]
> sometimes the citation key is added to the Extra field

this is either something you have selected to do, so on your instruction only, or you have enabled auto-pin, which will do it on your behalf a configurable number of seconds after a change.

> and the citation key will only change based on a change to the author field if the text in Extra is removed. Is this expected behaviour?

Yes. If this appears without you doing anything, you have enabled [auto-pin](https://retorque.re/zotero-better-bibtex/installation/preferences/index.html#automatically-pin-citation-key-after).

The reason some people want this is that they have used the key in articles and they don't want it to change even if corrections are made to the item. Another benefit is that these keys will show up on the Zotero-Overleaf integration -- if they are not in the `Extra` field, that integration will generate keys that are pretty much guaranteed to differ from BBts, and even have a chance to change over time even if you don't touch the item in Zotero.

**Comment by retorquere** [comment]
So .240 works for you now?

**Comment by tduncs** [comment]
> So .240 works for you now?

Yes - thanks very much.


> The reason some people want this is that they have used the key in articles and they don't want it to change even if corrections are made to the item. Another benefit is that these keys will show up on the Zotero-Overleaf integration -- if they are not in the `Extra` field, that integration will generate keys that are pretty much guaranteed to differ from BBts, and even have a chance to change over time even if you don't touch the item in Zotero.

And.... I didn't realise there was an Overleaf integration! So thank you again.
