### ISSUE TITLE
Export items never stops

### ISSUE THREAD

**Issue by mndldm** [retorquere/zotero-better-bibtex#3011]
### Debug log ID

NZPD6QDL-refs-apse/6.7.238-7

### What happened?

after selecting export collection as better bibtex, the exporting never stops. 
![Screenshot 2024-10-02 092425](https://github.com/user-attachments/assets/1f2cbd6c-4bc6-4ada-a329-6b4656b8b0f9)

**Comment by retorquere** [comment]
please upgrade to 6.7.240 first
