### ISSUE TITLE
Quotation marks: add on option to replace them by \enquote{} on export

### ISSUE THREAD

**Issue by gracile-fr** [retorquere/zotero-better-bibtex#302]
Some of my references it Zotero have in their titles (or in other fields), some quotations marks. They are correctly exported by BBT but, in the final output produced by LaTeX, that can cause certain issues. Straight quotes are not parsed correctly as being the opening or the closing quote by LaTeX… (the reason, I read, is that <code>"</code> is right quotation mark in some encoding). Nested quotes can't be managed correctly, punctuation (with French guillemets) is deficient (nbsp needed).

Personally I use the <code>csquotes </code>package and its <code>\enquote{}</code> command (which switches automatically from one type of quotes to another if they're nested and handles French punctuation, with babel, perfectly.)
Would it be possible to add, perhaps as an option, the replacement of quotes by <code>\enquote{}</code> (or any other command defined by the user)? I.e. check if a word is wrapped by some quotation marks and replace them.

Quotations marks I use are: <code>« »</code> (guillemets) and <code>" "</code> (straight), and, rarely, <code>“ ”</code>. Other languages use:  <code>‘ ’</code> and <code>„ “</code>. So the list of quotation marks might have to be defined by the user too.

(In French, guillemets «» comes with a non-breaking space after the opening and before the closing mark. As I wrote above, this is handled by csquotes and babel, so the space must be removed on export if you decide to implement my suggestion).

A .<a href="https://gist.github.com/gracile-fr/b869edcea2abfb5030d3">json</a> and a <a href="https://gist.github.com/gracile-fr/02e68bf219a6ae50650d">.bib</a> to test (but with the actual behaviour of the exporter).

**Comment by retorquere** [comment]
The guillemets and the fancy quotes would be the easy case as I can recognize them independent of context, but the straight quotes are tricky. Straight quotes are also sometimes used to denote inches for example.

**Comment by gracile-fr** [comment]
Indeed, but I think it's rare in titles. Is it possible to rely on the context (figures), and the fact that they're not paired? Geography: « 49° 30′ 00″ » 
https://en.wikipedia.org/wiki/Prime_%28symbol%29

**Comment by retorquere** [comment]
You wouldn't believe the amount of variety present in bibliographies :/. In
a 3-quote situation there'd be no way of deciding short of some fairly
spectacular AI. How about if I just do the guillemets and fancy quotes?
Then you could force csquotes by replacing straight quotes.

**Comment by retorquere** [comment]
Could you give http://tempsend.com/6D23630EAA a try? It will replace single and double guillemets (including a single breaking or non-breaking space if present) and left and right double quotes if you set the preference to on (defaults to off). It does not replace straight quotes or single left quotes, as the single right quote is simply the apostrophe -- too common a character to mess with.

**Comment by gracile-fr** [comment]
Great, I'll change the remaining straight quotes in my library. Thank you!

**Comment by retorquere** [comment]
This hasn't been merged into the main branch yet, I'm putting together a
test case in the morning, then I'll release it when all pass. Does it do
what you need?

**Comment by gracile-fr** [comment]
Yes,that does the trick. As for the test, you can use the data in the file above.

**Comment by retorquere** [comment]
Which file is that?

**Comment by gracile-fr** [comment]
A .<a href="https://gist.github.com/gracile-fr/b869edcea2abfb5030d3">json</a> and a <a href="https://gist.github.com/gracile-fr/02e68bf219a6ae50650d">.bib</a> to test (but with the actual behaviour of the exporter).

**Comment by gracile-fr** [comment]
(updated with the <code>\enquote{}</code> markup and to fit the test guidelines -- timestamp, etc…)

**Comment by retorquere** [comment]
Thanks, I'd overlooked those, that helps tremendously. It just struck me though -- I can replace the guillemots safely, but in the case of the fancy quotes, `“` can be either open or close quotes (see your sample above). That makes it once again tricky to just assume they can be replaced safely without regards to context.

**Comment by gracile-fr** [comment]
In my sample above, Searle's article is enclosed by straight quotes. Is that your remark ?

**Comment by retorquere** [comment]
Ah no sorry, I meant <code>“ ”</code>. vs <code>„ “</code>.

**Comment by gracile-fr** [comment]
I see.
I think that you can rely on the fact that an opening quote has a space before, and the closing quote has its space after. Except the guillemet, but it's more straightforward with them (though there might be some languages which use them in the opposite way).
Or, that could be user-defined (hidden pref is ok): code <code>«»,“”</code> would mean that there are two pairs to take into account, and the first defined is the opening quote.

**Comment by retorquere** [comment]
It won't always have spaces around them; a comma can for example follow a closing quote. Human language is frustratingly flexible. The hidden pref is what I've gone with; a simple string of character pairs, no separating comma. Also no enabling in the GUI anymore; if the csquotes pref is non-empty, it is applied. Tests are running, if they go green I'll release.

**Comment by retorquere** [comment]
Travis is unresponsive at the moment, so it will probably take a few tries to get a release out. I'll try again tonight.

**Comment by gracile-fr** [comment]
So, I can have as <code>extensions.zotero.translators.better-bibtex.csquotes</code> the value <code>«»“”</code> ?

**Comment by retorquere** [comment]
Yep.

**Comment by retorquere** [comment]
I don't know if it's been released yet, Travis has been acting up.

**Comment by retorquere** [comment]
Shouldn't such quotes translate to `\mkbibquote{...}` rather than `\enquote{...}`?

**Comment by adamaltmejd** [comment]
Just tried this, setting `extensions.zotero.translators.better-bibtex.csquotes` to the value `""`. The .bib file now replaces each quotation with `Enquote$>$` and `Enquote$<$` instead of the proper `\enquote{...}`. Using BBT 5.0.180 and Zotero 5.0.54.

**Comment by retorquere** [comment]
csquotes only works with two distinct quote characters.

**Comment by retorquere** [comment]
Try with left/right double quotation marks (https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html).

**Comment by adamaltmejd** [comment]
Makes sense, thanks!
