### ISSUE TITLE
`charmap.csv` mapping not working anymore

### ISSUE THREAD

**Issue by TomBener** [retorquere/zotero-better-bibtex#3020]
### Debug log ID

WK7KAEXZ-refs-apse/6.7.240-7

### What happened?

I encountered the same issue as described in #2893 again recently. Could you help to diagnose and fix the issue? Thanks very much!

**Comment by retorquere** [comment]
I cannot access `D<number>` logs, those go to the Zotero team. Please see message above.

**Comment by TomBener** [comment]
The Debug log ID has been updated.

**Comment by retorquere** [comment]
I have it reproducible, I don't have a fix yet.

**Comment by TomBener** [comment]
Thanks for your prompt fix. The test build 6.7.240.7170 works perfectly!
