### ISSUE TITLE
[Bug?] Original-date in extra field does not appear in the bibtex file

### ISSUE THREAD

**Issue by gitsroid** [retorquere/zotero-better-bibtex#3022]
### Debug log ID

See the issue

### What happened?

I want to add the original date of some works to my references. For that I put `original-date: YYYY` in the extra field. The problem: the original date is not added to my bibtex file. It generates the reference well when using zotero but not when using pandoc. If I put `tex.original-date: YYYY` then it works with pandoc (because the original date is added to my bibtex file) but not via zotero.

What is expected:

When adding `original-date: YYYY` to the extra field to be able to add to the references the original date via zotero and pandoc.

Zotero version: 7.0.5
Betterbibtex version: 6.7.240

About the debug log: I have some private items and I have not seen the way of sending an edited debug log within betterbibtex menu. If you really need it for this issue, please, tell me a way of sending it edited (I also do not want to post it here).

**Comment by retorquere** [comment]
Are you exporting as Better BibLaTeX? BibTeX doesn't know about origdate.
