### ISSUE TITLE
Preferences broken in Zotero 7

### ISSUE THREAD

**Issue by gledguri** [retorquere/zotero-better-bibtex#3031]
### Debug log ID

NA

### What happened?

![Screenshot 2024-10-21 at 12 45 03](https://github.com/user-attachments/assets/e3c1f2e2-2f3c-49b5-bd5a-b6ff816e8bd1)

I am unable to change the active citation key using Zotero 7 and Mac OS

**Comment by retorquere** [comment]
Seriously, how do you come to the idea that the log is not applicable?

Please reproduce the problem and send a log. I much prefer a log over guessing what the problem is.

**Comment by gledguri** [comment]
Thought this was a quick fix. However, here's the log number XHJG63WS-refs-euc/6.7.245-7

**Comment by thekswenson** [comment]
I have the same problem running 7.0.7 on linux.
Here is the log number: GC8CAEIZ-euc/6.7.245-7

**Comment by clbrady** [comment]
Same problem.
Debug Log ID: BEYYQJVM-euc/6.7.245-7

**Comment by LHYi** [comment]
I am also having the same issue on Windows 11.
Debug Log ID: UCZ8Q4EF-euc/6.7.245-7

**Comment by mikeliao97** [comment]
same

**Comment by retorquere** [comment]
I see the problem now. I might not be able to fix it today, bit tomorrow should be doable.

**Comment by mausgrau** [comment]
> I have the same problem running 7.0.7 on linux. Here is the log number: GC8CAEIZ-euc/6.7.245-7
Same her with 7.0.8 (64-bit) Zotero  and 6.7.245 BBT
I just installed this seemingly useful extension today and thought  I was the problem ;-)
Thanks for your work in advance

**Comment by mausgrau** [comment]
Sadly, the issue is not resolved for me: I can edit the Citation Formula now in the Gui in the BBT Preferences, but when I click update Citation Key on any item of the library it just removes the Citation Key, or sets it to nothing ''.
![2024-10-24_10-30](https://github.com/user-attachments/assets/87627032-7c05-41f7-896f-f280b8293595)

**Comment by lubingau** [comment]
It works for me on Ubuntu 22.04 and Zotero 7.0.3.
Thanks!

**Comment by retorquere** [comment]
This build is just a stopgap, I need to redo the preferences entirely it seems.

**Comment by Reeednose** [comment]
> Yes, on Mac OS 14.6 and Zotero 7, I see the same preferences window as the one at the top of this conversation (with the strange orange bar), even after installing the temporary fix above.

At first, I encountered this problem too, so I tried manually deleting each letter one by one and retyping it (when using backspace, a warning message about the referenced formula appears in the orange bar). After that, it worked.

**Comment by sunhamkim** [comment]
> Sadly, the issue is not resolved for me: I can edit the Citation Formula now in the Gui in the BBT Preferences, but when I click update Citation Key on any item of the library it just removes the Citation Key, or sets it to nothing ''. ![2024-10-24_10-30](https://private-user-images.githubusercontent.com/167517975/379684361-87627032-7c05-41f7-896f-f280b8293595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTk4MjcsIm5iZiI6MTcyOTgxOTUyNywicGF0aCI6Ii8xNjc1MTc5NzUvMzc5Njg0MzYxLTg3NjI3MDMyLTdjMDUtNDFmNy04OTZmLWYyODBiODI5MzU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMTI1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmI5NTRiZjk3YzcwMjI5YmI2MmU3NGQyY2I3M2Q1N2YwNjgyZjY3NDg2YzEyYjU3NWFhMWRjOTg4MThjZjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vN5__8J8FSzFMXTiUmiP-w9fFY4byUuxO9-4AE1_GME)

Same here, on Windows 11 and Zotero 7.

**Comment by agileinfocus** [comment]
Build 6.7.246.7229 fixed the problem for me.

**Comment by retorquere** [comment]
New release is out

**Comment by fportales** [comment]
I can edit the automatic exports now. Thank you
