### ISSUE TITLE
Unable to cancel auto BibTeX export

### ISSUE THREAD

**Issue by moritz-da** [retorquere/zotero-better-bibtex#3035]
### Debug log ID

IQL8MJJK-euc/6.7.246-7

### What happened?

I set up an automatic export to a Bibtex file. The export works, but I can no longer delete it or view the settings I configured. Please see the screenshot.

![Bildschirmfoto 2024-10-23 um 13 45 09](https://github.com/user-attachments/assets/8b85d8a0-ce57-4fdd-8141-588876b94169)

**Comment by retorquere** [comment]
You couldn't have known, but this is the same problem as #3031. Please subscribe to that issue.
