### ISSUE TITLE
Citation key formula field has no effect

### ISSUE THREAD

**Issue by ghbrown** [retorquere/zotero-better-bibtex#3038]
### Debug log ID

ZVR3IKCV-refs-euc/6.7.248-7

### What happened?

The citation key formula does not seem to affect the resulting output.
Specifically, it seems that the output is stuck on the BB default.

**Comment by retorquere** [comment]
Can you install build 7236, right-click an item, choose "refresh" from the BBT submenu, and send a new log?

**Comment by ghbrown** [comment]
This should do it: 66BER5ZM-refs-euc/6.7.248.7236-7

**Comment by retorquere** [comment]
your citekey formula is set to just `title`, and the refresh has set the citekey accordingly; unchanged from what it was, but refreshed nonetheless. Is it not displaying `measurecriticalvaluesdifferentiablemaps`?

**Comment by ghbrown** [comment]
Yes, I was just using `title` to mess around, so I expected a key like that. And when I export the single item the .bib file contains the appropriate key.
However, I had only been checking the output of the whole collection, which was not (and is still not) using `title` as the formula.

**Comment by retorquere** [comment]
OK, but did you refresh those items? Changing the formula has no effect on existing keys.

**Comment by ghbrown** [comment]
I did not realize this, sorry for the hassle. Refreshing the entries of the collection produces the desired result.
I read the docs but this fact was in a section I skimmed over too fast. Thanks for the help!
