### ISSUE TITLE
Feature Request: Export Templates/Profiles

### ISSUE THREAD

**Issue by m-walters** [retorquere/zotero-better-bibtex#3039]
### Debug log ID

none

### What happened?

I'm pretty new to this utility, but already I've encountered something that I think many others might appreciate.
I have a bib export for my Obsidian use. And I have a new one for my manuscript.
For my manuscript, I don't need that as many bib fields (don't need the `urldate` date accessed, etc.), but for Obsidian I like more details.

It would be handy to be able to create different exporting templates/profiles to fit different contexts.

**Comment by m-walters** [comment]
Why is the Feature Request combined with bug reports??

**Comment by retorquere** [comment]
Because years of doing this has shown it to be effective for my workflow.

**Comment by retorquere** [comment]
Do you have any idea how bizarre it is being asked to justify how I provide my free support for my free software?

https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html#preferencesoverride
