### ISSUE TITLE
Cannot enter an 'editor' field (better BibLaTeX)

### ISSUE THREAD

**Issue by svann576** [retorquere/zotero-better-bibtex#3048]
### Debug log ID

GTSMCP3J-refs-euc/6.7.250-6

### What happened?

I cannot enter an 'editor' field, only an 'editors' field. When entering

```tex.editors = Joe```

it exports correctly, while entering

```tex.editor = Joe```

exports no editor. I came across this issue when I had book entry that only listed editors, no authors, and better biblatex had not exported any of them. This manual attempt at fixing things however did not help: it seems that my biblatex setup expects the 'editor' field, not 'editors'; if an entry only has the latter, it ignores them completely.

Another test is entering a post-script:
```
ex.add({ name: 'editors', value: 'test' });
```
this results in a 'test' field for every item, but
```
ex.add({ name: 'editor', value: 'test' });
```
outputs nothing.

**Comment by retorquere** [comment]
`D<number>` debug logs go to the Zotero team, I cannot access those, and it lacks information I need. Please see point 1. above how to send a BBT debug log.

**Comment by svann576** [comment]
Edited, see above.

**Comment by retorquere** [comment]
you have `editor` in your skip fields.

**Comment by svann576** [comment]
I am so sorry, this is embarrassing. Sorry for wasting your time!

**Comment by retorquere** [comment]
No problem.

You can also add them in the extra field as

```
editor: Lastname || Firstname
```

and that will work for both BBT and Zotero itself
