### ISSUE TITLE
Cache can not be opened on start

### ISSUE THREAD

**Issue by Midway65** [retorquere/zotero-better-bibtex#3053]
### Debug log ID

QUQLECRM-euc/6.7.250-7

### What happened?

Every time upon opening Zotero 7 latest build the message pops up saying Better Bibtex: Cache cannot be opened. Restart Zotero upon which the same thing happens.

**Comment by retorquere** [comment]
How large is your library?

Also: https://www.zotero.org/support/kb/data_directory_in_cloud_storage_folder

**Comment by Midway65** [comment]
3700 items, 6.7 GB. Storage is static, onedrive was turned off before the database was placed there.

**Comment by retorquere** [comment]
The disk usage of your attachments doesn't factor into this. I take it the 6.7GB is mostly attachments. 3700 items with an 6.7gn zotero.sqlite file would be really weird)

**Comment by Midway65** [comment]
Not aware of starting Z in admin mode, doubtful. Yes lots of attachments books give it the bulk.

**Comment by Midway65** [comment]
By the way I've turned off all other plugins and tested and still had the same result.

**Comment by Midway65** [comment]
If I remember correctly there was a statement in the error file that mentioned that this was not a database issue.

**Comment by Midway65** [comment]
Also ran a check and repair utility on zotero.sqlite DB restarted and same error message. Is there another DB within zotero that might be having and effect?

**Comment by retorquere** [comment]
It's not those files, it's the indexeddb that can't be opened. Those files are in `C:\Users\<username>\AppData\Roaming\Zotero\Zotero\Profiles\<profilename>\storage\permanent\chrome\idb`. You can use https://sqlitebrowser.org/dl/ to inspect them (with zotero *not* running) -- if the table `databases` contains just BetterBibTeX, you can delete all files and folders in the `idb` and restart Zotero.

**Comment by retorquere** [comment]
(to the best of my knowledge BBT is the only extension using IDB, so theoretically you could just remove those files/folders without inspecting, but I can't be 100% sure I'm the only one)

**Comment by Midway65** [comment]
Inspected those files and deleted. Restarted and exact same error occurred. Is that cache suppose to be built upon starting?Looked at the ibd folder after restart and  it was empty. Restarted again after disabling the cache purge in settings and same result. If I take those files and folders from a b/u and place them in the ibd folder would they be recognized and then would the cache be rebuilt and updated. I'm way out of my depth here. I no nothing about coding.

**Comment by Midway65** [comment]
As an experiment I opened Z with the newest version of BB plugin. Went to settings and turned off the cache switches and then closed Z. I added my backup files to the previously indicated directory and then reopened Z. The error message reappeared and when I went to the cache folder IBD both the folder and the db file had been wiped.

**Comment by retorquere** [comment]
> Is that cache suppose to be built upon starting?

Initialized, but yes, the file/folder should re-appear after start of Zotero, as BBT will create an empty cache.

> If I take those files and folders from a b/u and place them in the ibd folder would they be recognized and then would the cache be rebuilt and updated.

It might, but it might also introduce more difficulties. These are supposed to be created automatically by Zotero when I request a new cache, I don't even make them myself directly.

> Went to settings and turned off the cache switches and then closed Z. 

That won't affect cache creation.

Please open command prompt (search for it in the start menu), and paste 

```
"C:\Program Files\Zotero\zotero.exe" -P
```

in it. You will see a window pop up called "Zotero - Choose User Profile", then

* click "Create Profile"
* click "Next"
* pick a name ("Test" will do)
* click "Finish"
* select the new profile
*  **uncheck** "Use the selected profile"
* click "Start Zotero"

Zotero will start, with all settings at default and no plugins installed, but with all your items and attachment present. Install BBT and test.

If this works it means your original profile is corrupt.

You can go back to your original profile by existing zotero and starting it as usual. It will pop up the earlier profile chooser, you can select the default profile and it will be back to what it was, but if the new profile works, the only thing I can advise is to delete the original profile. You can at that point re-check "Use the selected profile", and the popup won't come up again.

**Comment by Midway65** [comment]
Creating a new profile did work! I very much appreciate your kind help. Thank you!

**Comment by retorquere** [comment]
Then you can delete the old profile and uncheck the checkbox, it will start with the new profile by default.

**Comment by Midway65** [comment]
Great, and once again thank you.
