### ISSUE TITLE
Failure to export library

### ISSUE THREAD

**Issue by CappuccinoCreature** [retorquere/zotero-better-bibtex#3055]
### Debug log ID

8TC5JJ3A-euc/6.7.251-7

### What happened?

When I try to export my Zotero library as a Better CSL JSON file, there is no opportunity to set a file path for the exported file. I have also not been able to find the file on my computer.
I left click on 'My Library' and select 'Export Library'. I select the format 'Better CSL JSON' and check 'Keep updated'. Then, I click 'OK'. At that point, I expected a window to open that would allow me to designate a directory for the export, but nothing happens. I have tried going to Settings-->Advanced-->Data Directory Location, but the library does not appear in the directory specified there.

**Comment by retorquere** [comment]
You're using a Snap install of Zotero, and it's blocking startup of BBT. Snaps have all kinds of weird file system limitations -- the Zotero crew also does not support Snap-installed Zotero.

If you're on a Debian-based distro like Ubuntu, you can install the [packaged official client](https://github.com/retorquere/zotero-deb), but I can't help you with snaps.
