### ISSUE TITLE
Citation keys are missing certain words if hyphens are used

### ISSUE THREAD

**Issue by trevorablett** [retorquere/zotero-better-bibtex#3059]
### Debug log ID

WUASBCL7-refs-euc/6.7.251-7

### What happened?

I've been using Better Bibtex for years (which is excellent by the way, and thank you) with the following Citation key formula:

```
auth.lower + shorttitle(3,3) + year
```

With Zotero 7 + BBT 6.7.251 on Ubuntu 24.04, I'm seeing an issue where a number of references that have hyphens in the title now don't include the full word. Some examples:

- "End-to-end training of deep visuomotor policies" by Levine et al. becomes `levineEndendTrainingDeep2016` (notice the missing "to")
- "On-Line Q-Learning Using Connectionist Systems" by Rummery et al. becomes `rummeryLineQLearningUsing1994` (notice the missing "On")
- "Soft Actor-Critic: Off-Policy Maximum Entropy Deep Reinforcement Learning with a Stochastic Actor" by Haarnoja et al. becomes `haarnojaSoftActorCriticPolicy2018` (notice the missing "Off")

Obviously not a major issue, and probably reasonably easy to fix, but a bit of a nuisance. Thanks. Let me know if there's anything else I can provide.

**Comment by trevorablett** [comment]
Wow, thanks for the quick fix! The test build totally resolves it.

**Comment by retorquere** [comment]
New release build is running.
