### ISSUE TITLE
test build 6.7.251.7293: Missing column header

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-better-bibtex#3062]
### Debug log ID

STCKJ62Y-euc/6.7.251.7293-7

### What happened?

Thank you very much for the update to get the Citation Key [in the Item Pane](https://github.com/retorquere/zotero-better-bibtex/issues/2522#issuecomment-2484423832).

It works great. Just a small problem: the header for the Citation Key column is now missing:
![image](https://github.com/user-attachments/assets/a485e72a-0548-4c1d-a887-1e39357b22ad)

BBT: test build 6.7.251.7293
Zotero 7.0.10-beta.2+dc47650eb (64-bit)
Windows 10

**Comment by mjthoraval** [comment]
Fixed, thank you.

**Comment by nhan000** [comment]
Hi @mjthoraval, how do you have the citation key show up here?
![image](https://github.com/user-attachments/assets/fd90cac6-b1cd-4569-a1ab-e318c79b73af)

Mine only shows up in the lower right section.
![image](https://github.com/user-attachments/assets/d3606300-9e0a-4a0d-8fe7-cc9f2dea2743)
I'm on Zotero 7.0.10 (64-bit), Windows 11.

**Comment by retorquere** [comment]
That's temporarily gone until Zotero fixes the API I need for it.
