### ISSUE TITLE
Better BibLatex copied year column as string if "./" character is found

### ISSUE THREAD

**Issue by ckenadiao** [retorquere/zotero-better-bibtex#3067]
### Debug log ID

Q4BJ38RD-euc

### What happened?

1. In Zotero, import the following DOI identifier: 10.1109/82.204108 
2. Look at the entry. Notice that in the year column, it is Jan./1992, with the './'. (I noticed that this behaviour also applies to some of the DOI, but not all.)
3. Use the Better BibLaTex functionality to copy the latex's format to clipboard, and then just paste it in notepad.
4. Copy the latex format, this time through BibLateX only -- paste it in notepad.
5. Compare both entry (I paste it below for reference) -- you notice that BibLateX manage to parse this entry to date = {1992-01}, but not for Better BibLatex where it shows year = {Jan./1992}. This causes compilation error in typst (see https://github.com/typst/hayagriva/issues/247 where I originally discuss about this issue)

**(Better BibLateX)**
@article{Leung1992,
  title = {Multibit {{Sigma}} - {{Delta A}}/{{D}} Converter Incorporating a Novel Class of Dynamic Element Matching Techniques},
  author = {Leung, B.H. and Sutarja, S.},
  year = {Jan./1992},
  journaltitle = {IEEE Transactions on Circuits and Systems II: Analog and Digital Signal Processing},
  shortjournal = {IEEE Trans. Circuits Syst. II},
  volume = {39},
  number = {1},
  pages = {35--51},
  issn = {10577130},
  doi = {10.1109/82.204108},
  url = {http://ieeexplore.ieee.org/document/204108/},
  urldate = {2024-10-29},
  langid = {english},
  file = {D:\OneDrive\Documents\Research\Zotero\Leung1992_journalArticle_multibit-sigma-delta-ad-converter-inc_vol39.pdf}
}

**(BibLateX through quick copy)**
@article{Leung1992,
	title = {Multibit Sigma - Delta A/D converter incorporating a novel class of dynamic element matching techniques},
	volume = {39},
	rights = {https://ieeexplore.ieee.org/Xplorehelp/downloads/license-information/{IEEE}.html},
	issn = {10577130},
	url = {http://ieeexplore.ieee.org/document/204108/},
	doi = {10.1109/82.204108},
	pages = {35--51},
	number = {1},
	journaltitle = {{IEEE} Transactions on Circuits and Systems {II}: Analog and Digital Signal Processing},
	shortjournal = {{IEEE} Trans. Circuits Syst. {II}},
	author = {Leung, B.H. and Sutarja, S.},
	urldate = {2024-10-29},
	date = {1992-01},
	langid = {english},
	file = {PDF:D\:\\OneDrive\\Documents\\Research\\Zotero\\Leung1992_journalArticle_multibit-sigma-delta-ad-converter-inc_vol39.pdf:application/pdf},
}
[debug.txt](https://github.com/user-attachments/files/17837033/debug.txt)

**Comment by retorquere** [comment]
Please right-click the item in your library, and send a BBT debug log from the pop-up menu. The resulting ID will have `-refs-` in it.

**Comment by retorquere** [comment]
Wait - is this a common occurrence? Why not just fix the date in the Zotero item?

**Comment by ckenadiao** [comment]
The updated debug log is CKV7LRRK-refs-euc

**Comment by retorquere** [comment]
Can you try again? I don't know what happened but I haven't received that log.

**Comment by retorquere** [comment]
i think actually the Zotero scraper should be fixed here. Jan 1992 is not the right date at all for that article, aside the fact that it should not be formatted that way.

**Comment by ckenadiao** [comment]
I double checked the article, it seems like the date is correct - January 1992? I think the date of publication (Aug 2002) referred form the website is the date of the article becomes digital. 
![image](https://github.com/user-attachments/assets/dc46122c-77a6-4cee-8d69-29b13e90d18a)

**Comment by ckenadiao** [comment]
Yeah, I tested build 7328 and it seems everything is fixed now.
