### ISSUE TITLE
Data Error on Mac 

### ISSUE THREAD

**Issue by aprajit** [retorquere/zotero-better-bibtex#3070]
### Debug log ID

L5NAFQ5H-fio-AUT7rebksdtL

### What happened?

Using latest version of BBT (was present in earlier versions as well). BBT not working with error "Error: Data provided to an operation does not meet requirements."  Using Zotero 7 (also occurs in Zotero 7 Beta).  Reinstalling (both Zotero and BBT) does not fix things.

**Comment by retorquere** [comment]
Please turn on debug logging in the help menu, disable and enable BBT, then send a new log. There are no errors logged in `L5NAFQ5H-fio-AUT7rebksdtL`.

**Comment by aprajit** [comment]
Thanks---did as you recommended and new Debug log ID is CENZHTNJ-fio-OzrUssxodQI6

**Comment by aprajit** [comment]
I installed it and get the same error. The new debug log ID is XTZYE7WZ-fio-ZrgTJLNBpMpW

**Comment by retorquere** [comment]
Debug logging was off at time of submission of the report, so there's nothing in the log.

**Comment by aprajit** [comment]
Apologies---here is he new debug log ID 9RBDI6RM-fio-TyVPUaFo18Hd

**Comment by aprajit** [comment]
This one works with no issues so far. Thank you!
