### ISSUE TITLE
Notes not included in .bib file during bulk or collection exports

### ISSUE THREAD

**Issue by sienilorenzo** [retorquere/zotero-better-bibtex#3073]
### Debug log ID

KV2UEWCI-refs-euc/6.7.256-7

### What happened?

I am experiencing an issue with Better BibTeX in Zotero. When I export a single item using Better BibLaTeX, the note field is correctly included in the .bib file, and the notes display as expected. However, when I export my entire library or even smaller collections, the note field is missing for all entries in the resulting .bib file.

I have verified that:

Notes are attached directly to the Zotero items.
The Export notes option is checked during the export.
I am using the latest versions of Zotero and Better BibTeX.
This issue occurs regardless of the library size (even with very small collections).

Environment: 
I recently installed Zotero and Better BibTeX, so they are the latest available versions as of 11/25/2024.

(sorry if the issue is trivial, I don't have the highest proficiency with this stuff yet, and this is my first ever bug report)
(ChatGPT could not help me)

**Comment by sienilorenzo** [comment]
I don't know if this could help, but most references in my library don't have notes for now. The item I have been using for single item export, and for checking if notes were being exported after the bulk export is the article titled "A shift in the mechanisms controlling hippocampal engram formation during brain maturation"

**Comment by retorquere** [comment]
This is not a fix, it will just get me more logging. Can you make a new log from that please, recreating the problem?

**Comment by sienilorenzo** [comment]
I feel a bit embarrassed, and I'm sorry for wasting your time, but I thought I had checked that everything was up to date. I've updated Zotero and now everything works fine. In any case, thanks for your availability, and have a great rest of your day :)
