### ISSUE TITLE
Better BibTex startup Failed

### ISSUE THREAD

**Issue by a1wilson** [retorquere/zotero-better-bibtex#3079]
### Debug log ID

M4BFTHB4-apse/6.7.258-7

### What happened?

Upon startup, BetterBibTex fails, with error: 

> TypeError: Zotero.ItemTreeManager.registerColumn is not a function

At first instance, it was not on startup, but while Zotero was open, and I was editing an entry (specifically changing its category from book to journal article).

Subsequent startups all produce the same error message, and BetterBibTex Citation Key columns is absent.

**Comment by retorquere** [comment]
You need to upgrade to 7.0.10

**Comment by jherkenhoff** [comment]
Had the same problem (7.0.9), which was fixed by upgrading to 7.0.10. Thanks :+1:

**Comment by a1wilson** [comment]
My apologies for the bother! Went away with an upgrade.
