### ISSUE TITLE
Bibtex Keys not updating.

### ISSUE THREAD

**Issue by KonstantinHirsch** [retorquere/zotero-better-bibtex#3081]
### Debug log ID

D669744804

### What happened?

BBT seems to start up as indicated by short pop up. However, no Bibtex key appears at the side-panel, see screenshot.

<details><summary>screenshot</summary>

![Screenshot from 2024-11-28 10-40-06](https://github.com/user-attachments/assets/a815f9c3-2e5d-42ec-a053-43d85a8352c8)

</details>

**Comment by KonstantinHirsch** [comment]
Followed the steps described above and generated a new log with the ID: EDGS4FQB-euc/6.7.258-7

**Comment by retorquere** [comment]
The citation key now sits at the top of the pane in the screenshot, can you send a new screenshot?

I'm also seeing a lot of errors in the log about scite-zotero-plugin. Probably not related, but still.

**Comment by isaac-tes** [comment]
The citation keys are indeed visible at the top, but there is a bug that they do not change when selecting a new item in the library, e.g. it stays fixed to the citation key of the first selected item when opening Zotero (see attached pictures).
Although it appears that the (auto-) exported citation keys in the .bib files are still correct.
![image](https://github.com/user-attachments/assets/f1c6b3c1-9d3b-4411-9c33-65b3f0f76329)
![image](https://github.com/user-attachments/assets/dffb6133-e715-4c27-bcd9-a492775fcc70)
![image](https://github.com/user-attachments/assets/4edc6726-8b78-4b39-90fe-c4e8f3802ea6)

Thanks for the amazing plugin btw.

**Comment by retorquere** [comment]
This looks to be a zotero bug. I'll go talk to them.

**Comment by retorquere** [comment]
In the interim you can view the key by displaying it in the middle table.

**Comment by KonstantinHirsch** [comment]
Thanks for taking care of the issue!

**Comment by maxoppelt** [comment]
Probably related to https://github.com/retorquere/zotero-better-bibtex/issues/3074

**Comment by retorquere** [comment]
Is indeed the same issue, thanks. @KonstantinHirsch please follow that issue.
