### ISSUE TITLE
Send debug log window is too small to actually use

### ISSUE THREAD

**Issue by chiavez** [retorquere/zotero-better-bibtex#3083]
### Debug log ID

I cannot generate one, that's the issue

### What happened?

I wanted to help you debug issue #3074 but I can't send you a debug log because of the issue below.

The debug log window is not usable on my laptop (14in screen) because it is too small to access the buttons on the bottom.
![image](https://github.com/user-attachments/assets/a50e5e4c-a617-4fe4-9138-2b9abd7fa902)

Resizing the window does not help:
![image](https://github.com/user-attachments/assets/13a14f44-3698-4ac5-b5a1-615354d9bb5a)

I did not manage to use the keyboard to access the buttons on the bottom neither. Moving the window outside the top of the screen (alt + spacebar) is not possible, because Windows moves it back within the screen.

Also, i noticed my app version is not the latest, but i could not find a way to force the update. 

I try to manually copy some information below:

**Comment by retorquere** [comment]
I'll see what I can do, but I suck at and despise doing UI work.

**Comment by chiavez** [comment]
No worries, and thank you very much for your work on this great app!

**Comment by retorquere** [comment]
I'll move the text to a tooltip when I find out how, but in the interim, the text is just gone. I doubt anyone reads it in any case.
