### ISSUE TITLE
BBT won't properly load and restricts PDF download by connector

### ISSUE THREAD

**Issue by haakmal** [retorquere/zotero-better-bibtex#3089]
### Debug log ID

JXD6V4CL-apse/6.7.258-7

### What happened?

This started happening today, I noticed something was wrong when the browser connector wouldn't download a PDF I knew I had access to. Had no errors or problems yesterday. Restarted Zotero after the issue with connector not downloading PDF and I've been consistently getting this error message each time I restart `TypeError: Zotero.ItemTreeManager.registerColumn is not a function`.

**What happens?**
- Error message pops up
- BBT loads but not fully. _How can I tell?_ I can see it active in plugin's but not visible in settings.
- Additionally, library would not show new items added until I move to different collection and back.

I'm not sure if connector is linked to this in some way or not, but as soon as I switched off BBT then no error, PDF's were downloading fine, and no issue with library delay. Switch BBT back on and everything happens again including error.

Log sent by interface, hopefully that much is working.

**Comment by retorquere** [comment]
Please upgrade Zotero to 7.0.10

**Comment by retorquere** [comment]
I've scheduled a new release that is compatible with Zotero < 7.0.10 but it will be missing functionality.
