### ISSUE TITLE
TypeError: Zotero.ItemPaneManager.registerInfoRow is not a function

### ISSUE THREAD

**Issue by hcharp** [retorquere/zotero-better-bibtex#3091]
### Debug log ID

DIKURQSY-fio-StSwGVoIrkT7

### What happened?

Since the last update, the add-on sends this message error:
`TypeError: Zotero.ItemPaneManager.registerInfoRow is not a function
`
It comes when I start Zotero, and I cannot use Zotero in TexStudio anymore.
After some tests, I figured out that this message appears each time I deactivate and activate Better BibTex for Zotero add-on in Zotero.
I then saw that there had been an update and connected the dots.

Thanks for your help and for this very useful add-on!

**Comment by retorquere** [comment]
Zee #3092
