### ISSUE TITLE
Better BibTeX startup failed: TypeError: Zotero.ItemPaneManager.registerInfoRow is not a function

### ISSUE THREAD

**Issue by erydit** [retorquere/zotero-better-bibtex#3092]
### Debug log ID

G928WY5Q-refs-euc/6.7.259-7

### What happened?

Hello! 

An error `TypeError: Zotero.ItemPaneManager.registerInfoRow is not a function` is raising up at every Zotero startup.

Zotero: 7.0.7 (64-bit)
BBT: 6.7.259

**Comment by hcharp** [comment]
Hi, I opened the same ticket ;)
I checked the code, could it be that the function `registerInfoRow` was not declared?
Anyway, same ticket #3091

**Comment by retorquere** [comment]
Not a typo.

I'm rolling out a new release that is downward compatible with missing functionality to prevent this problem, but the problem is solved by upgrading to Zotero 7.0.10.

**Comment by hcharp** [comment]
Thank you. Where can we find the 7.0.10 version?

**Comment by retorquere** [comment]
Help -> Check for upgrades
