### ISSUE TITLE
Better BibTeX startup failed TypeError: Zotero.ItemPaneManager.registerInfoRow is not a function

### ISSUE THREAD

**Issue by Russ-dh** [retorquere/zotero-better-bibtex#3093]
### Debug log ID

65IELLLB-euc/6.7.259-7

### What happened?

Since this morning, when I start Zotero, the Better BibText plugin generates this error: Better BibTeX startup failed TypeError: Zotero.ItemPaneManager.registerInfoRow is not a function
![Better-bib_startup_error](https://github.com/user-attachments/assets/4d614cc9-1de8-4821-abfd-211bc59b858b).

The good news is that Better BibText is still working. After adding a new item in Zotero, I am able to generate a file in Obsidian via the Citations plugin in Obsidian. But I do not understand the error message when starting Zotero.

**Comment by retorquere** [comment]
Please upgrade BBT.

**Comment by retorquere** [comment]
(and Zotero BTW)

**Comment by Russ-dh** [comment]
Updating Zotero solved this. Apologies, I had thought that Zotero was updating automatically!

**Comment by Russ-dh** [comment]
Updated Better BibTex manually as well. Thanks for the quick response!

**Comment by retorquere** [comment]
Absolutely no need to apologize. Zotero does auto-update, but only tests every few days (IIRC) whether an update is available.
