### ISSUE TITLE
Error: Blocked

### ISSUE THREAD

**Issue by glocalglocal** [retorquere/zotero-better-bibtex#3095]
### Debug log ID

IQIQH64P-refs-euc/6.7.263-7

### What happened?

At least once a day I get a popup with this error message: 

Better BibTeX startup failed
Error Blocked

This happens while Zotero is apparently idling in the background -- ie it's not something in my interaction with Zotero that causes it. 

Then, BBT will exit (no BBT in menus, no Citekey entry in sources detail), but Zotero continues as normal. To get BBT back I have to restart Zotero. 

The debug log may not show much because I can't generate the error on demand.

**Comment by retorquere** [comment]
`IQIQH64P-refs-euc` indeed doesn't contain the error. I would need a log generated after it happens -- The help menu should have an option "Send to file.io" when it does, you can use that and post the log here.

**Comment by ienzo** [comment]
Can confirm I'm getting this error too on Zotero 7.0.10 (64-bit). Perhaps it's an issue with the new 7.0.10 update?

**Comment by retorquere** [comment]
I need logs, not confirmation. I don't see the error so I don't know what the cause is.

**Comment by retorquere** [comment]
build 7410 will have more info in the popup, but it's not a replacement for getting a log id.

**Comment by glocalglocal** [comment]
For the last 48 hours or so I am waiting for the error message to show up but it's not happening. It should have occurred several times by now. It may be that the latest Zotero update fixed things. I notice that the citation key appears at the bottom of the pane again, so something must have changed. I'll keep you posted.

**Comment by retorquere** [comment]
If you comment here the issue will automatically reopen
