### ISSUE TITLE
BBT 6.7.263 does not start with flatpak'ed Zotero 7.0.10

### ISSUE THREAD

**Issue by froli-code** [retorquere/zotero-better-bibtex#3097]
### Debug log ID

D576275333

### What happened?

Hi all,

I am trying to use BBT Version 6.7.263 with Zotero 7.0.10 on Manjaro Linux 24.2.0 (Flatpak Version of Zotero).
Whenever I try to install the plugin, I get the following error message:

`[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: jar:file:///home/oliver/.zotero/zotero/klsleeza.default/extensions/better-bibtex@iris-advies.com.xpi!/bootstrap.js :: pref :: line 100"  data: no]`

This message appears when I try to install the plugin, activating it, or simply restarting Zotero. I tried re-installing Zotero (switched from AUR version to Flatpak version), but the error persists.

Thanks a lot!

**Comment by retorquere** [comment]
You'll have to ask the flatpack maintainer for Zotero. The flatpack apparently makes a folder that plugins ought to be able to write to unavailable. Zotero doesn't support flatpacks for this reason, and same holds for BBT, sorry.

**Comment by retorquere** [comment]
See also [here](https://forums.zotero.org/discussion/comment/479067/#Comment_479067).

**Comment by froli-code** [comment]
I downloaded the tarball, but the problem persisted. The solution was to delete the ~/.zotero directory and restarting Zotero. Maybe something with the permissions in the folder was wrong. The Flatpak version is also working fine now.

Thanks a lot for your support!
