### ISSUE TITLE
Trouble loading better-bibtex

### ISSUE THREAD

**Issue by gkb21** [retorquere/zotero-better-bibtex#3114]
### Debug log ID

Better BibTeX Debug n/a

### What happened?

When I try and install/load  better-bibtex I get this error:

[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: jar:file:///Users/griffinkatrivesisbrown/Library/Application%20Support/Zotero/Profiles/2qnv73rd.default/extensions/better-bibtex@iris-advies.com.xpi!/bootstrap.js :: pref :: line 100"  data: no]

currently hasn't loaded correctly:
<img width="290" alt="Screenshot 2024-12-22 at 9 01 18 am" src="https://github.com/user-attachments/assets/3964bfa6-3f3a-4050-a13c-3db3a513a9c7" />
<img width="733" alt="Screenshot 2024-12-22 at 9 01 29 am" src="https://github.com/user-attachments/assets/1b13bd73-b95a-459c-b9f9-bafc909bc8e9" />

**Comment by gkb21** [comment]
It wouldn't allow me send a Better BibTeX log since it isn't even loading properly. And there doesn't seem to be an option for  “Help” > “Send debug log to file.io” only this D610046798. Sorry

**Comment by gkb21** [comment]
Also I'm downloading with safari

**Comment by gkb21** [comment]
[Debug Output.pdf](https://github.com/user-attachments/files/18220220/Debug.Output.pdf)

Hopefully this debug log helps

**Comment by gkb21** [comment]
Its still not quite working but at least I can send a debug log :) 

<img width="733" alt="Screenshot 2024-12-23 at 12 47 47 am" src="https://github.com/user-attachments/assets/ebdd25ef-54ec-45a5-9124-060f025a5e1e" />

Debug log:
I84S6A77-apse/6.7.263.7456-7

**Comment by retorquere** [comment]
can you go into your preferences, and

* search for "config", 
* click "Config editor"
* click "Accept"
* search for "retain"
* send a screenshot

**Comment by retorquere** [comment]
7457 will show a more detailed error -- I think I know what it is, but I'd like to make sure

**Comment by retorquere** [comment]
can you go into your Zotero profile directory and remove the line that sets `cacheRetain`?

**Comment by gkb21** [comment]
Before: 

<img width="1262" alt="Screenshot 2024-12-23 at 5 39 06 am" src="https://github.com/user-attachments/assets/c0cad379-4c72-4db6-8b62-4507cdb6221c" />


After:

<img width="295" alt="Screenshot 2024-12-23 at 5 44 24 am" src="https://github.com/user-attachments/assets/588def3c-7b96-426b-b26a-abf2ddf7e008" />


Deletion of remove the line that sets cacheRetain



Debug log: 
85HU6LJW-apse/6.7.263.7457-7

**Comment by retorquere** [comment]
So I think it works now?

**Comment by gkb21** [comment]
I think so, although this did appear the first time I tried importing from Zotero to obsidian:

<img width="1311" alt="Screenshot 2024-12-23 at 5 48 11 am" src="https://github.com/user-attachments/assets/6a7ddbc2-b14e-44b8-824a-27b0a45206dc" />

But seemed to work on the subsequent goes

**Comment by retorquere** [comment]
I'd need a new log for the cayw error, it's a different problem.

**Comment by gkb21** [comment]
Yep can do, although it only happened once after I first installed the version above. But the error hasn't showed up again. So I'm not sure how to replicate it. 

Debug log: 
6D88JRFZ-apse/6.7.263.7457-7

**Comment by retorquere** [comment]
If the error hasn't shown up again I can't diagnose it. If it does, you can open a new issue and we'll look at it then.
