### ISSUE TITLE
@jurisdiction: map court/authority to institution

### ISSUE THREAD

**Issue by gracile-fr** [retorquere/zotero-better-bibtex#326]
Would it be possible to map Zoteros's <code>court</code> field (CSL: <code>authority</code>) to BibLaTeX <code>institution</code>?

**Comment by retorquere** [comment]
I don'y see why not; do you have a testcase I could use?

**Comment by gracile-fr** [comment]
```
@jurisdiction{_dalain_2010,
  date = {2010-12-23},
  institution = {CE, Ass.},
  journaltitle = {Rec.},
  number = {337033},
  pages = {649},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {Dalain},
  volume = {I}
}

{
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "release": "1.2.29",
    "preferences": {
      "csquotes": "«»“”",
      "citekeyFormat": "[auth:lower][Title:fold:nopunct:skipwords:select,1,1:lower:alphanum:prefix,_][year:prefix,_][0]",
      "skipWords": "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum",
      "skipFields": "abstract,file,editora,editoratype,editorb,editorbtype",
      "usePrefix": false,
      "preserveCaps": "all",
      "fancyURLs": false,
      "langID": "babel",
      "autoAbbrev": false,
      "autoAbbrevStyle": "http://www.zotero.org/styles/nature",
      "pinCitekeys": "manual",
      "rawImports": false,
      "DOIandURL": "both",
      "attachmentsNoMetadata": false,
      "preserveBibTeXVariables": false
    },
    "options": {
      "exportFileData": false,
      "exportNotes": false
    }
  },
  "collections": [],
  "items": [
    {
      "itemType": "case",
      "tags": [],
      "relations": {},
      "extra": "",
      "reporter": "Rec.",
      "court": "CE, Ass.",
      "language": "fr-FR",
      "dateDecided": "23/12/2010",
	  "reporterVolume": "I",
      "firstPage": "649",
      "caseName": "Dalain",
      "docketNumber": "337033",
      "creators": [],
      "attachments": [],
      "notes": [],
      "itemID": 2077,
      "date": "23/12/2010",
      "pages": "649",
      "title": "Dalain",
      "number": "337033",
      "seeAlso": [],
      "__citekey__": "_dalain_2010"
    }
  ]
}
```

**Comment by retorquere** [comment]
What biblatex style are you using to process this? I've looked at bath, chicago and oscola, and none of them you support `institution`. oscola does support `court`.

**Comment by chayaninw** [comment]
> What biblatex style are you using to process this? I've looked at bath, chicago and oscola, and none of them you support `institution`. oscola does support `court`.

I was looking into how a few `biblatex` styles handle a `@jurisdiction` entry. I tried citing an American federal court case, which expects (in Zotero field names) case name, court, date, reporter, reporter volume, and first page in the citation. Below is what I find.

- `biblatex-chicago` expects the court name to be in the  `location` field. It doesn't work with `institution`.
- `biblatex-oxref` expects the court name to be in the `court` or `institution` field, but also says "Use the `location` field for the location of the court in American, Australian or Canadian cases."
- `biblatex-apa` expects the court name to be in the `organization` field. In addition, it does not use `journaltitle`, `volume`, or `pages` at all. It expects the reporter, volume, and page to be manually formatted in `citation` field. It also does not use `institution` or `location`.
- `oscola`, according to the manual expects `court`, but also says that it is a synonym for `institution` (page 23 of the [manual](http://ctan.cs.uu.nl/macros/latex/contrib/biblatex-contrib/oscola/oscola.pdf)). It also uses `location` for American, Canadian, and Australian cases. I couldn't get oscola to run, so I didn't test the results.

**Comment by retorquere** [comment]
Can you open a new issue for this? I'd prefer to have a debug log for a few sample items that show the data you describe here, and full biblatex exports as you would like to see them?

**Comment by chayaninw** [comment]
Sorry I didn't intend to report an issue about BBT exports per se. I saw there was an outstanding question on what fields are expected for courts in the `@jurisdiction` entry type and I thought I could provide some inputs based on what I tried with different `biblatex` packages (which show that they expect different things).
