### ISSUE TITLE
Provide button for citations

### ISSUE THREAD

**Issue by dbitouze** [retorquere/zotero-better-bibtex#4]
Drag-and-drop citations are not that handy when working with maximized windows of both TeX editor and (browser) Zotero UI: the user has to first "unmaximize" these two windows to be able to drag-and-drop.

I know the Ctrl+Shift+C shortcut  but a feature à la JabRef could be nice: a button (and a shortcut!) for adding the citation in a (preselected) TeX editor (JabRef currently has plug-ins for Emacs, Vim,TeXstudio, Kile, LaTeXEditor, WinEdt, LyX, OpenOffice). Hence, instead of (being writing in the TeX editor window):
1. Alt+Tab to switch to the Zotero UI,
2. click to select the relevant item,
3. Ctrl+Shift+C to copy it,
4. Alt+Tab to switch to the TeX editor window,
5. Ctrl+V to paste the citation,
6. continue to write,

it would require only:
1. Alt+Tab to switch to the Zotero UI,
2. click to select the relevant item,
3. click on the relevant button or (better) hit the corresponding shortcut,
4. Alt+Tab to switch to the TeX editor window,
5. continue to write.

Okay, only one step less but probably a more natural workflow.

**Comment by retorquere** [comment]
https://zotplus.github.io/better-bibtex/cayw.html
