### ISSUE TITLE
bibtex export of phdthesis does not case-protect "type"

### ISSUE THREAD

**Issue by murmlgrmpf** [retorquere/zotero-better-bibtex#435]
Hi,

We have recognized that the export of phdthesis wit better-bibtex does not put the type into curli brackets.

```
@phdthesis{Zellh13,
  type = {PhD Thesis},
```

Whereas it should be 

```
@phdthesis{Zellh13,
  type = {{PhD} {Thesis}},
```

This has the negative impact that in the bibliography PhD will show up as Phd. The standard bibtex export does feature the brackets.

Best,
Thomas

**Comment by retorquere** [comment]
Can you right-click that reference for me and select "send better bibtex error"? That will give me a test case.

**Comment by murmlgrmpf** [comment]
Sorry, I was skiing this weekend. I will send you the error as soon as I am back in office on Monday.

**Comment by murmlgrmpf** [comment]
329RQKFE Is the error key.

**Comment by retorquere** [comment]
Tests are running, [this](https://github.com/ZotPlus/zotero-better-bibtex/blob/435/test/fixtures/export/biblatex%20export%20of%20phdthesis%20does%20not%20case-protect%20-type-%20%23435.bib) is what is currently output. The reason for the double braces can be found in [this discussion](https://github.com/ZotPlus/zotero-better-bibtex/issues/383#issuecomment-153904326) should you wonder; the TL;DR is that BibTeX has more exceptions than it has rules, and double-brace seems to do the job consistently where single-brace does not. I also group adjacent words that would normally be brace-protected into a single braced-protected group to minimise clutter.

**Comment by retorquere** [comment]
Tests green, good to go if you can confirm this is the output you want.

**Comment by murmlgrmpf** [comment]
Yes, I can confirm, this is the output that fixes my Issue. Thank you very much!

**Comment by retorquere** [comment]
Super. I'm traveling now, but when I get access to a computer I'll cut a
release

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5450](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.79.5450.issue-644.xpi) ("test for #435").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5451](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.79.5451.master.xpi) ("test for #435").
