### ISSUE TITLE
Call BBT generated "Citation Key" field in CSL editor

### ISSUE THREAD

**Issue by andrew-greve** [retorquere/zotero-better-bibtex#455]
Hello all,

I would like to discuss a possibility for BBT which I hope will be of interest to a few people out there.  My sincere apologies if posting here is not the correct way to go about this, but I saw a note saying to leave any ideas in the issue tracker.

I would like very much to be able to call the citation key defined by BBT in an in-line citation using the Word (or other) plugin.  I write my documents using Word and then use pandoc to convert the docx to a tex file, which pandoc does beautifully.  I then drop this converted tex output into one of my latex templates.  The only thing left for me to do is manually change all of the (Author, 2016) in-line citations to \autocite{author_2016} or \autocite*{author_2016} so biblatex and hyperref can do their thing.  I think it is possible to use the Zotero CSL Editor to make a citation style that will give me the desired output, so I won't have to manually type the autocite commands anymore.  

Using the CSL editor, I see that it is relatively straightforward to change the prefix and suffix of an in-line citation.  This can be \autocite{ for the prefix and } for the suffix.  Now all that's left is to call the citation key set by BBT in the middle!  Obviously, the full solution here would require the prefix to be \autocite* when the author name is suppressed in the Zotero Word add-in, and page/section/chapter numbers should also show ( eg. \autocite*[1]{author_2016} ).  The astrix should be set by using the suppress author command, and the page number should format as shown by just typing the page number in the Word plugin popup.  Citation keys for citations with more than one source should be separated by commas, as biblatex requires.  It seems like a bit of a task when I think about it, but I'm really hoping that this project could see some progress, as it would I think make some real strides toward the fastest Word-->LaTex conversion possible.  Once complete, a few versions of what I've outlined above could be added to the Zotero citation repository (for people who use cite commands beside autocite).

The most basic question that I need to know the answer to to get started is how to call the "Citation Key" field generated by BBT in the CSL editor, so the key will show in an in-line citation in Word.  I believe this is a "macro," correct?  What is the macro name so I can call it in the CSL editor?

The rest of the workflow is pretty straightforward.  Just export the biblatex to a .bib file as usual, copy the pandoc generated latex into a template, and compile.  The result is a fully typeset document with about zero conversion work!

Anyway, I'm not a programming whiz, but I'm willing to learn, so if anyone finds this an interesting possibility and is willing to help me, I'm sure it would be of great use to quite a few people, who work/collaborate in Word, and then typeset with LaTeX and BBT.  Thanks everyone!

**Comment by adam3smith** [comment]
(answered from the Zotero side [here](https://forums.zotero.org/discussion/56462/in-line-citation-with-as-citekey-for-easier-latex-conversion/#Comment_247548), but @retorquere would have to say about the possibility to implement the CSL mapping of the citekey in BBT.

**Comment by retorquere** [comment]
I'm going to hold off merge until there's more clarity on how this will work on the Word/LibreOffice side. Debug builds are cheap, so if you need any particular twist, lets me know.

**Comment by andrew-greve** [comment]
Thanks.  I've got someone who knows a whole lot more about this than I do asking a couple of questions on the Zotero dev forum.  I'll update this post if anything new comes in.

**Comment by retorquere** [comment]
No problem.

Another option would be to look into http://writer2latex.sourceforge.net/. W2L is not Zotero-aware (doesn't recognize the special tags Zotero inserts), but it could in principle be changed to recognize those and export them to \cite{...} stuff, using a little help from BBT to resolve the tags to citation keys. W2L is written in Java, and I'd rather not spend my time in that language if I can help it, but that should give you a clean save-as compilable LaTeX document.

Word/Libreoffice will be a little anemic compared to what LaTeX can do (no acronyms, no theorems, no thank you), but if all you want is citation, that should be super-clean.

**Comment by retorquere** [comment]
Correction: W2L does recognize Zotero tags according to http://writer2latex.sourceforge.net/index6.html#features, but it would still need to be changed to fetch the citation keys. That should be a relatively mild change though. Citation keys could be picked up using a web api I could provide, or using a refkey -> citekey mapping I could export. But you'd have to talk to the W2L devs about that.

**Comment by retorquere** [comment]
So, what are we to do with this issue?

**Comment by andrew-greve** [comment]
Sorry, I guess it should just be closed. Talked to my programmer friend, and was told that this just isn't possible. Thanks all for trying anyway! Hope Zotero can make the changes required to implement this in the future!
