### ISSUE TITLE
[Idea] collection autoexport/syncing

### ISSUE THREAD

**Issue by nylki** [retorquere/zotero-better-bibtex#46]
This is a feature proposal.
It would be useful in some cases to automatically synchronize changes in the zotero database with a biblatex/bibtex database. So once a new element was added, removed, edited in zotero, a new export would be triggered.
I like to only work eg. with markdown/latex and just add my references in zotero. However I don't always want to export my library manually, I'd rather like to (more or less) instantly use my added bibliography items in markdown/latex.

To reduce overhead when editing alot at the same time several approaches could be thought of in some different ways:
- if change (edit, add, remove, ...) is less than $time ago: do nothing. Otherwise export collection or merge only the changes.
- export/merge every $minutes/seconds if changes happened
- export when focus (cursor) is out of zotero/firefox (zotero/firefox not the active window) and changes happened.
- ask for export/merge after a change happenend

**Comment by nylki** [comment]
Just noticed an auto-export feature is implemented in ZotPlus now. Thanks! :+1:

**Comment by retorquere** [comment]
Technically, it's in Zotero Better BibTeX; Zotplus is the container for my plugins, but you're very much welcome.

**Comment by nylki** [comment]
@retorquere ah damn… accidently mixed up the names.
keep up the great work!
