### ISSUE TITLE
URL export simple name

### ISSUE THREAD

**Issue by janakelarsson** [retorquere/zotero-better-bibtex#464]
Not a bug report, but a wishlist item.

I just discovered the "BibLaTeX url" choice in the collection drop-down menu (Firefox). Brilliant, no more tedious manual exporting!

It would be more intuitive to have the name of the collection, so that I'd use
http://localhost:23119/better-bibtex/collection?/0/Contextuality.biblatex
rather than
http://localhost:23119/better-bibtex/collection?/0/5F5885KD.biblatex

I just tried the above (\addbibresource{http://localhost:23119/better-bibtex/collection?/0/Contextuality.biblatex}) AND IT WORKS! 

Please amend the generated url in the result dialog from the "BibLaTeX url" menu item

Otherwise, thanks for the great extension!

**Comment by retorquere** [comment]
It does work, most of the time, but not always. Zotero allows the creation of collections with exactly the same "path", and named access will pick one at random. Access by ID always works.

**Comment by janakelarsson** [comment]
I see. Yes, it is possible to create two with the same name in the same spot in the tree. Same "path". My question would be: why? Is there a use case for this? I would NOT want the same "path" for two different collections. I suppose it will work as long as I have unique "paths".

I suppose another benefit would be that the ID works even if the path changes. I'd still prefer human-readable.

Could you not make the dialog read "If your collection has a unique name, use ... otherwise ..."? Or have Zotero only allow unique paths?

**Comment by janakelarsson** [comment]
Didn't mean to close this, yet.

**Comment by retorquere** [comment]
I don't control what collection names Zotero allows, so that is out.

I'll think about the other options, but this UI was implemented as a quicky feature; I don't want the popup to get too big.

Personally, I use BBTs auto-export instead of the URL-export these days.

**Comment by janakelarsson** [comment]
I realize you have no control over Zotero, I basically meant "file a bug report at Zotero".

I have so many projects that autoexport would become unwieldy. I think.
------------------------------------------
http://localhost:23119/better-bibtex/collection?/0/5F5885KD.biblatex
or if the collection name is unique:
http://localhost:23119/better-bibtex/collection?/0/Contextuality.biblatex

**Comment by janakelarsson** [comment]
Jesus, what happened to *that*?

**Comment by retorquere** [comment]
*grin* the line of dashes you entered means "new chapter starts here". Yay markdown.

I'd sooner display both, with a warning for the path-based URL. URLs are supposed to be stable pointers to entities (the U stands for "Unique"), and if you have a unique collection name now, but add a duplicate later, the behavior would become unpredictable.

I honestly have no idea why anyone would want duplicate names, but if there's one thing I learned,  "nobody is ever going to do that" has consistently proven itself wrong when I built the assumption into BBT.

Unwieldy in what sense, BTW? Not saying you ought to use autoexport over pull export, I've just seen my own use of pull export dwindle to zero after I had auto-export.

**Comment by janakelarsson** [comment]
Performance. I'm worried that I'll export the same collection to many places. For several collections. Granted, there is a limit to the number of papers I write per year, but I use this in applications and CVs too, and the numbers grow faster than I expected. 

Besides, with pull I can just branch using a copy of the TeX source and carry on, not worrying about having to export again, to a different location in my file tree.

**Comment by retorquere** [comment]
That last point is entirely correct.

Performance wise, BBT caches quite aggressively, so unless you have a hundred going, I wouldn't worry about it... but you sound like you might have.

**Comment by janakelarsson** [comment]
In any joint project, I'd need to export anyway.

Pull export will be useful in one, two dozen files per year. Well, it works for me as is.

**Comment by retorquere** [comment]
I'll look at the popup. It'll be somewhere next week though. Thesis work right now.

**Comment by janakelarsson** [comment]
Whoa, then leave this. Good luck!

**Comment by retorquere** [comment]
I wish I could think of a cleaner place to show these URLs, but my GUI-fu is weak.
