### ISSUE TITLE
Url export preference lost

### ISSUE THREAD

**Issue by melsophos** [retorquere/zotero-better-bibtex#466]
BBT loses the preference concerning the export of the URL (that I set to "export in URL field") each time that I restart Firefox: this is set back to the default value "none".

**Comment by retorquere** [comment]
I can't reproduce it here. Can you get me a [debug report](https://github.com/retorquere/zotero-better-bibtex/blob/master/CONTRIBUTING.md#submitting-an-issue)?

**Comment by melsophos** [comment]
Here are two debug reports:
- before enabling the url option (but after a restart, with the option enabled before): DW4E9WR7
- just after enabling the option (during the same Firefox instance as the previous report): BENI6XTE
I hope this will help. Thanks a lot for your time, and if you need any additional information please let me know.

**Comment by retorquere** [comment]
Could you temporarily uninstall Zotfile and try again? The only error I see in the log seems triggered by BBT, but caused by something Zotfile adds. If you could confirm, I can talk to the Zotfile author.

**Comment by melsophos** [comment]
I disabled Zotfile and the bug did not happen. But what is even stranger is that since I have enabled it again I cannot reproduce again the bug despite many tests. Here is a report if you want to check if the error you were mentioning has disappeared: 7W3TPGEC.

**Comment by retorquere** [comment]
The error is still in the logs. Zotfile has some code that is started after a delay, and that's where the error crops up.

I'm starting to think BBT doesn't actually cause the error, it's just a race condition -- if BBT finishes its startup before the error in Zotfile happens, the error does no harm, but if the Zotfile code runs first, BBT's initialization is interrupted.

I've filed an issue with the Zotfile author -- lets keep this issue open until we get some kind of resolution, but if my assessment is correct, there's nothing BBT can do about it.

**Comment by melsophos** [comment]
Thank you! If I see anything new I will let you know.

**Comment by retorquere** [comment]
We're tracking the issue [here](https://github.com/jlegewie/zotfile/issues/220#issuecomment-204979088);   can you install [4.2.6 prerelease](https://addons.mozilla.org/en-US/firefox/addon/zotfile/versions/) and generate a new error report?

**Comment by melsophos** [comment]
From now on do you prefer that I answer here or in the other place?
Here is the report with 4.2.6 installed: CBJBIX6K
Also note that when I looked at the option after installing the new version it was turned off again.

**Comment by retorquere** [comment]
The error from the logs is gone, so that's good news.

You mean to say the option is still turned off after you turned it on? That means it's in BBT, not the interaction between BBT and Zotfile.

Can you do the following:

1. Enable the "in an URL field" option
2. Go into "about:config", and verify the "extensions.zotero.translators.better-bibtex.bibtexURLs" option is set to "url"
3. Stop Firefox (fully, no windows open)
4. Start Firefox again
5. Go into "about:config", and verify the "extensions.zotero.translators.better-bibtex.bibtexURLs" option is still set to "url"
6. Submit a new error report.

There are no errors in your last log, and I really don't know of anything that could actually toggle the preference, rather than preventing it being saved, but let's see what we learn from this procedure.

**Comment by melsophos** [comment]
I tried several times the steps you are indicating, but the preference was always removed so point 5) is failing. Do you want nonetheless a report?
On the other hand I performed another check: when I quit Firefox after changing the option, the new value "extensions.zotero.translators.better-bibtex.bibtexURLs" is correctly saved to the prefs.js file. But when I launch Firefox again this line is deleted from the file.

**Comment by retorquere** [comment]
Yes, please do get me a report, after step 3 and after step 5.

No idea what could be causing this.

**Comment by melsophos** [comment]
Ok I have made three reports:
- opening without having changed the option in the previous session (setting: off): FQ5EEUZW
- after changing the setting (setting: url): TBKAH7I3
- closing the previous session and opening again (setting: off): MVBBV4MI

**Comment by retorquere** [comment]
Absolutely nothing in the logs, except in TBKAH7I3, where I can see you have set the preference. Crazy. So it seems the preference reverts after startup, but there's nothing in the log that indicates any prefs activity -- and when debugging is on, I log *all* changes to the BBT prefs.

Could you try disabling all extensions except Zotero and BBT, restart, and try the 5-step test again? It's hard to imagine that another extension could be doing this, but I have no other conceptual path that leads to this pref reverting, and I cannot reproduce it here.

**Comment by melsophos** [comment]
I have disabled all the extensions but Zotero and BBT. The problem is still here. Here are three new reports, same process:
- first session: 8WGDJSKS
- after turning on: GM2UHDJV
- after restarting: PTHX4Z4E

**Comment by retorquere** [comment]
Still nothing in the logs.

Could you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2233.xpi, then go into about:config add a preference called extensions.zotero.translators.better-bibtex.bibtexURLs2, set it to `url`, and go through the tests again? I've temporarily added this pref and if present it will take precedence; I want to know whether all prefs are reset, or just that one particular preference.

Crazy. I have no idea what's going on.

**Comment by melsophos** [comment]
So the new preference stays after restarting. In particular one time I had the file opened when Firefox started, and I could see that precisely the line for the url disappeared and I would say this was the only one since the line number of the line displayed just shifted by one.

Here are the various logs:
- starting session (1 off, 2 off): HX2QHBAJ
- set option 2 (1 off, 2 url): 8GXNAMXR
- restart firefox (1 off, 2 url): 59CDZQCN
- set option 1 (1 url, 2 url): P367RUI5
- restart firefox (1 off, 2 url): IXJDD47P

**Comment by retorquere** [comment]
I think I have it. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2241.xpi ?

**Comment by melsophos** [comment]
Unfortunately the problem is still here.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2251.xpi and submit a debug report?

**Comment by melsophos** [comment]
Here are the three reports, same order:
- start: 263EQCS8
- set preference: DN2VJNCH
- restart: 6IICUHEK

**Comment by retorquere** [comment]
OK, I've neutered some legacy code that must be the cause of this, try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2260.xpi

**Comment by retorquere** [comment]
I'm ready to cut a new release if this does indeed fix it.

**Comment by melsophos** [comment]
Ok so I confirm that it is fixed. I was making some checks because first it looked fixed, but then later it reappeared: in fact Firefox rolled the BBT version back to a previous one.
Thanks a lot for looking to this and giving so much efforts to get it fixed!

**Comment by retorquere** [comment]
So to make sure: issue fixed, can be closed?

**Comment by melsophos** [comment]
Yes everything is good.

**Comment by retorquere** [comment]
Urgh -- I just made an error in merging. I am positive I corrected it properly, but could you do me a favor and check https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2283.xpi for me? It works for me, but I'd like to make sure. Super thanks for your patience BTW.

Odd that it should have reverted -- the builds are technically versioned "later" than the last release.

**Comment by melsophos** [comment]
I have tested several times and this is fixed.
You should not apologize, you are the one making all the work in writing this wonderful tool and fixing bugs!
