### ISSUE TITLE
Drag and drop not working from Zotero standalone to RStudio rmarkdown

### ISSUE THREAD

**Issue by richardtc** [retorquere/zotero-better-bibtex#467]
Drag and drop not working from Zotero standalone to RStudio Rmarkdown file. I select reference in Zotero, drag to Rmarkdown file, but no code inserted, just blank. I don't see any errors logged. It does however work if dragged to a simple text file.

eg. @peng_reproducible_2011

I've tried reinstalling the xpi file, and followed the guidelines at: https://github.com/retorquere/zotero-better-bibtex and https://github.com/bbest/rmarkdown-example

Maybe it's related to the Zotero prefs as noted in latter reference?

In Zotero Preferences, set:
Export: "Default Output Format" to Pandoc citation
Better Bib(La)tex: "Citation key format" to [auth:lower]_[veryshorttitle:lower]_[year]

Zotero: 4.0.29.5
RStudio: 0.98.1103
knitr: 1.12.3
OS: Mint Linux 17.1

**Comment by retorquere** [comment]
Is this specific to R Studio? Does it work if you drag it to another editor?

**Comment by richardtc** [comment]
It works if dragged to a text file

**Comment by retorquere** [comment]
Those settings don't affect drag and drop workings, only the output. Zotero does the actual work of drag and drop, BBT only generates the content to be dropped, so I'm afraid this is a more general issue of RStudio not accepting Zotero drops.

Can you try doing a QuickCopy + paste (the hotkey associated with quick copy can be found in the [preferences](https://www.zotero.org/support/creating_bibliographies) -- I am not at my Linux station right now so I can't check what the defaults are for Linux) to see if that works? If it does, that drag-and-drop aspect of it is outside of BBTs reach to fix, and it would require the Zotero devs to look into it.

**Comment by richardtc** [comment]
To confirm, I can copy using hotkeys (ctrl+shift+c) and paste a reference from Zotero into Rmarkdown.

**Comment by retorquere** [comment]
Then I'm afraid there's nothing I can do. The part that handles drag-and-drop is part of Zotero.

Alternately, perhaps [cite as you write](https://github.com/retorquere/zotero-better-bibtex/wiki/Cite-as-you-Write) could be used in RStudio somehow?

**Comment by retorquere** [comment]
Could it be you are experiencing [this](https://forums.zotero.org/discussion/57403/shift-drag-to-place-cite-in-google-doc-fails/#Item_0) zotero issue?

**Comment by richardtc** [comment]
Yes it could be. I'm using standalone Zotero ... will wait for the new release.   I'm currently able to insert citations with ctrl+shift+c to copy and ctrl-v to paste into Rmarkdown in RStudio.

**Comment by retorquere** [comment]
Please let me know how it goes after you upgrade
