### ISSUE TITLE
Zotero Better Bib(La)Tex is not compatible with Iceweasel 38.7.1

### ISSUE THREAD

**Issue by Padoup-Padoup** [retorquere/zotero-better-bibtex#468]
Hello,

I am using Iceweasel on Debian and had a system upgrade towards Iceweasel 38.7.1. Iceweasel is basically the Debian branding of Firefox. During this upgrade, the Zotero Better Bibtex module got deactivated, and in the Iceweasel modules Better Bibtex appears deactivated with the following message: `Zotero Better Bib(La)Tex is not compatible with Iceweasel 38.7.1`. I am using Better BibTex version 1.6.39.

Since everything was working fine before the Iceweasel upgrade (according to this [Debian page](https://packages.qa.debian.org/i/iceweasel.html), the upgrade was from Iceweasel version 38.6.1 to 38.7.1), I installed the `checkCompatibility` addon for Firefox (that does not enforce the version check) and everything seems to be back to normal.

Do you have any idea why these versions are not compatible?
Thanks in advance,

**Comment by retorquere** [comment]
That was a mistake on my part. I try to keep the supported versions a little limited because I have so little time to test all variants, but I hadn't considered Debian would still be on 38. Tests are running for release.

**Comment by Padoup-Padoup** [comment]
Awesome! I installed the update and it is working. Thanks a lot! 
Regarding Debian... hum... I know...
