### ISSUE TITLE
Timestamp for import?

### ISSUE THREAD

**Issue by jeff-kerr** [retorquere/zotero-better-bibtex#470]
I see at https://github.com/retorquere/zotero-better-bibtex/issues/142 functionality was added to export the Zotero "date modified" field as a Bibtex key "timestamp."  

I think it would be neat if the import filter could also recognize this field during import and populate the Zotero "date modified field"?  For example, if I roundtrip the data from BBT export to BBT import, the timestamp doesn't seem to follow?

My main application is not roundtrip but migration from JabRef (and other managers) that export the timestamp field.  It would be great if BBT could recognize it, possible with a few different date formats (for example, JabRef's default is yyyy.MM.dd, with no time).

For me, I think it should also populate the date added with the same data as date modified, unless we could come up with a way to specify both dates in Bibtex somehow.

**Comment by retorquere** [comment]
Translators don't have access to the datetime fields. Zotero fills them in with the current date whatever any translator tells them. It's not the problem that it isn't recognized; Zotero is incredibly flexible with parsing dates.

**Comment by jeff-kerr** [comment]
Ok thanks!  I asked the Zotero forum but it seems like there is little interest in adding this functionality.

**Comment by retorquere** [comment]
Then there's nothing I can do, unfortunately. Are you OK with closing this issue?

**Comment by jeff-kerr** [comment]
Sure.
