### ISSUE TITLE
Math markup to unicode not always imported correctly

### ISSUE THREAD

**Issue by jeff-kerr** [retorquere/zotero-better-bibtex#472]
I am migrating my rather large JabRef-managed database into Zotero using BBT.  One issue involves whether to use the option "Retain LaTeX markup on BibTex import."  

If I use it, then I get all the of my existing bracing {} for capitalization showing up (for example, in Zotero's title field).  I would say this is undesirable because, even though it exports back to BibTeX just fine, the braces show up in any of the nice non-bibtex features like "Copy Citation", Word integration, etc.

But if I don't use it, then all my greek character and other math commands are stripped completely (eg '10 $\mu$W" in the BibTeX before import becomes just '10 muW' in the title field).  

Rather than have an option to ditch just the {}'s but retain the math markup, I have been reading that the preferred way to store special characters in Zotero is to directly store them in Unicode.  I verified that BBT already exports unicode 'mu' in a BibTeX friendly way as '\ensuremath{\mu}'

The question is, on import, can I get BBT to convert the LaTeX math markup into Unicode? (and discard the {}'s).  Or maybe, if BBT can't already do this, can I pre-process my .bib file through something that will convert all the math markup into unicode (or another format) that BBT can import correctly?

Thanks in advance

**Comment by jeff-kerr** [comment]
Just verified that if I search/replace $\mu$ with the actual unicode character (in a text editor that supports it), then BBT imports it correctly.  So I guess this changes to whether there is an external tool that can do this for me automatically for most commonly used characters (like greek) before I import with BBT, or whether it's something that could be added to BBT (latex markup to unicode conversion during import), or whether there is something else I am missing that would make this easier.

Thanks!

**Comment by retorquere** [comment]
Can you submit a sample of that reference by right-clicking it and selecting "Report Better BibTeX error"? If you post the ID you get after clicking through here, I'll have the reference to test with. It ought to already do this translation during import; I think I know why it doesn't, but I'd like to verify.

**Comment by jeff-kerr** [comment]
Thanks for looking at this!  Great to know it's part of the plan.

I just constructed a somewhat degenerate test reference that I compiled from many of the special characters I'm seeing in my BibTeX title fields (attached).  I'm not a BibTeX expert, so I'm sure how many of these are standard -- I just threw it all in, in case some are useful and easy to support.  I'm also attaching a PNG of what this looks like after compiling a document (TeXShop 3.18, Mac OSX 10.9, IEEEtran as the reference style).  This output is what I would expect to happen from the given BibTeX, but again, not really sure if it is standard to support all these.

It seems the most important would be the greek characters and the math symbols.  Secondary would be the non-breaking spaces ("~" or U+00A0), and thin spaces ("\;" and maybe U+202F?), and maybe the long minus sign ("$-$").

Finally attaching the output that BBT currently gives during import followed by export.

Thanks again, hope it helps!

[testimport.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/205160/testimport.bib.txt)
![texshop ieeetran](https://cloud.githubusercontent.com/assets/16180976/14295396/5cd164ba-fb43-11e5-8d08-ab4c8474941d.png)
[testexport.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/205180/testexport.bib.txt)

**Comment by jeff-kerr** [comment]
Side note, it looks like thin space "\;" should actually map to U+2009 (U+202F as in my earlier post is incorrect).  If I insert U+2009 in the Zotero GUI, BBT exports as \hspace{0.167em}, which renders nicely in my TeXShop flow!

**Comment by retorquere** [comment]
I have the mapping of stuff like `\mu` working (that it didn't was a bug), but it needs some serious performance work to be done (my testing service currently breaks halfway the build as it uses too much memory).

I've added `\;`; when this is done, `\;` will map to U+2009 and back.

**Comment by jeff-kerr** [comment]
Great, thanks, appreciate it!  And thanks for adding the spacing support. 

I made another slight error in my posts, the thin space should be "\," (comma), this should map to U+2009 (I did have \, in my test sample, just typed it wrong in the posts above, sorry!).  Incidentally, "\;" (semicolon) is a thick space, not sure if anyone uses this?

For completeness, here is the full list of math spacing options for latex, and closest unicode I could find by comparing the 'em' size):

\quad (1em, U+2001)
\; (5/18 em, U+2004)
\: (4/18 em, U+205F)
\, (3/18 em U+2009)
\! (-3/18 em, did not find the code for this)
\qqad (2 em, did not find the code)
~ (non-breaking U+00A0)

I guessed at the unicode by comparing these two sites:
https://www.sharelatex.com/learn/Spacing_in_math_mode
https://www.cs.tut.fi/~jkorpela/chars/spaces.html

**Comment by jeff-kerr** [comment]
Attaching test sample with the 5 space options above (that I found unicode), and the rendering I get from TeXShop.

[testimport2.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/205577/testimport2.bib.txt)
![texshop ieeetran testimport2](https://cloud.githubusercontent.com/assets/16180976/14302003/5033b628-fb6a-11e5-92a1-657074ed5aca.png)

**Comment by retorquere** [comment]
I'm reading the mappings from http://www.w3.org/2003/entities/2007xml/unicode.xml and http://www.w3.org/Math/characters/unicode.xml -- I just haven't implemented the matching properly for BibTeX `->` Zotero. The other way around works (but that's also lots easier).

**Comment by retorquere** [comment]
BTW it would be very helpful if you could import one of those BibTeX files, correct the reference in Zotero to your liking, and then attach the BibTeX here together with an export in the "BetterBibTeX JSON" format. That will give me a clean test to work towards.

**Comment by retorquere** [comment]
BTW the full post-processed map is [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/resource/translators/latex_unicode_mapping.coffee)

**Comment by retorquere** [comment]
My code requires a unicode code point to translate to, it has bidi translation baked into its assumptions. I've added the others (they were formerly variants of `\hspace{...}`), but it doesn't seem that spacing in references is a common enough occurence to warrant rebuilding the whole BibTeX transliteration.

**Comment by retorquere** [comment]
yay, the build went green! You can grab the [test build](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.43-circle-2123.xpi), or if you can get me those testcases as decribed above, I can get to testing.

**Comment by retorquere** [comment]
I think I've got it. Test build is at https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.43-circle-2139.xpi, but if you're happy with what's below, I'll count that as confirmation:

```
Test Title With 100 μJ, 200​μJ Energy, and ±0.1% Accuracy, 0.2mm² Size, and -50dB Attenuation
Test Title with space  quad, spacesemi-colon, spacecolon, spacecomma, space nbsp
```

**Comment by retorquere** [comment]
For shits and giggles I tried importing this with the stock BibTeX importer:

```
Test Title With 100 μJ, 200\,\mboxμJ Energy, and $\pm$0.1% Accuracy, 0.2\,mm$^2$ Size, and $-$50\,dB Attenuation
Test Title with space\quad quad, space\;semi-colon, space\:colon, space\,comma, space nbsp
```

Stock did get `\mu` right before I did, I'll grant that 😄

**Comment by jeff-kerr** [comment]
Great thanks!  I can review this and provide the samples you asked for and double-check that it imports correctly,  Are there instructions somewhere on how I can test the above build without risking my current profile (can I point it somewhere else?)

**Comment by retorquere** [comment]
What platform are you on?

**Comment by retorquere** [comment]
Ah never mind that, you can install [this](https://addons.mozilla.org/en-US/firefox/addon/profilist/) to create new profiles and switch between them. Profiles are fully separated, so you'll also have to install Zotero anew in the new profile, and all your settings will be default in the new profile (so no sync, no references, no bookmarks, it's like starting anew)

**Comment by jeff-kerr** [comment]
Ok, attaching the samples!  I imported the two references in the "testimport.bib" file, adjusted it to the way  I think it should look (by inserting the correct Unicode's via the "special characters" dialog) and then exported a BBT JSON file "testexport.json."  I'd say the rendering in the exported JSON looks pretty decent, so I guess it's just a matter of fixing the import.  I'll try your test-build in a sandboxed profile to check it out!

[testimport.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/209338/testimport.bib.txt)
[testexport.json.txt](https://github.com/retorquere/zotero-better-bibtex/files/209339/testexport.json.txt)

BTW, in your post above (immediately below the efd1b7f commit) it looks like some of the spacing is missing in the second reference?

**Comment by jeff-kerr** [comment]
The greek and math symbols are working, this is fantastic thanks! 

On the spacing characters and options.  I reviewed your [https://github.com/retorquere/zotero-better-bibtex/blob/master/resource/translators/latex_unicode_mapping.coffee](map).  I see what you mean about the spaces.  I actually find that the mapping in this file is completely fine for export (TeX package makes a correct looking PDF, even with the hspaces and all).  But it also looks like the mappings from my earlier post are working for export, so this is great too!  

For import, it looks like the spacing characters do not work (not sure if that was intended).  Like you mentioned I don't think all of these will be used much.    I might suggest just adding just adding the exception for "\," (slash comma) -> U+2009, since this is the most commonly used for creating thin spaces between numbers and units.  Also '~' -> U+00A0, which the nonbreaking space, although I do see this one referenced in one of the sections of latex_unicode_mapping.coffee, so maybe its a bug that one doesn't work?

Other than this, looks fantastic.  And of course, BBT is really great for us holdouts :)

**Comment by retorquere** [comment]
**question back**

The `\,` should get mapped. I'll look into that, but your BBT JSON file has `<sup>2</sup>` instead of `²`. Both will work, but are you sure that's what you want?

**responses to your comments**

* The BBT JSON exports should always look exactly like what you have in Zotero -- it is just a straight dump of what the translators are offered. Import/export from/to BibTeX is all that's going to be interesting wrt to the mapping.

* The spacing missing could be an paste error. Github doesn't support everything -- the final say is the BBT JSON export.

* The mapping is used both ways -- mostly, there are a few exceptions hardwired into the BibTeX parser -- so they should indeed work for both im- and export. It's not possible to do a 100% roundtrip, because LaTeX technically isn't a document format but a programming language -- to get the *real* meaning of what a LaTeX source says, you have to execute it. And there is no canonical mapping from any unicode codepoint to a single LaTeX construct. But I try to get close.

* The `~`... if you have a NBSP in your Zotero reference, BBT will export that to `~`, but (at least currently) on import of BibTeX, it gets changed into a normal space. I realize that's a little arbitrary, but I used to find bibtex files that had `~`s in them in really odd places, and BNSPs are hard to find/correct in Zotero. But on retrospect, the `~` is easy to find in BibTeX... I'll remove that hardwired morphing.

**Comment by retorquere** [comment]
Wow, that was a lot more work than I thought it would be. I currently have this:

```
m: Test Title With 100<c2><a0><ce><bc>J, 200<e2><80><89><ce><bc>J Energy, and <c2><b1>0.1% Accuracy, 0.2<e2><80><89>mm<c2><b2> Size, and -50<e2><80><89>dB Attenuation
t: Test Title With 100<c2><a0><ce><bc>J, 200<e2><80><89><ce><bc>J Energy, and <c2><b1>0.1% Accuracy, 0.2<e2><80><89>mm<c2><b2> Size, and <ef><bc><8d>50dB Attenuation
l:   Title                    = {{T}est {T}itle {W}ith 100~$\mu${J}, 200\,{\mbox{$\mu$}}{J} {E}nergy, and $\pm$0.1\% {A}ccuracy, 0.2\,mm$^2$ {S}ize, and $-$50\,d{B} {A}ttenuation},

m: Test Title with space<e2><80><83>quad, space<e2><80><84>semi-colon, space<e2><81><9f>colon, space<e2><80><89>comma, space<c2><a0>nbsp
t: Test Title with space<e2><80><83>quad, space<e2><80><84>semi-colon, space<e2><81><9f>colon, space<e2><80><89>comma, space<c2><a0>nbsp
l:   Title                    = {{T}est {T}itle with space\quad quad, space\;semi-colon, space\:colon, space\,comma, space~nbsp},
```

(M means mine, T is yours, L is LaTeX).

The second title matches perfectly. The first still has two differences:

1. I have a slim space between `50` and `dB`, your sample doesn't. I think my sample is what you want, correct?
2. The second is that you translate `$-$` to an M-dash, I translate it to `-`. It's not incredibly hard to add this one sample, but I try to minimalize special cases for parser speed and maintainability, and this is a special case of the more general case the BBT doesn't *really* understand math mode. The BBT parser simply ignores the '$' sign and interprets what's between them as it would any other LaTeX construct. I'm inclined to keep the behavior this way.

You can grab this build at http://tempsend.com/68730F8F60 -- not my usual spot, but my build infrastructure doesn't publish debug builds when one or more of the tests fails, and currently the test associated with this issue does.

**Comment by jeff-kerr** [comment]
Great, tried the new build, most of the spacing is working now!  A couple responses and then one more issue I noticed.

**Superscript '2'**
The `²` character, as you have it now, seems fine!  I didn't complain too much about the <sup> tags because it was still exporting to BibTeX correctly (as \ensuremath{^2}) and was still working nicely in word citation.  So I guess whatever makes the most sense for you!  Eg. I'm not sure how you handle it if there are more complicated expressions in the superscript during import.

**Mismatches from the sample I provided**
1. Yes, should have the slim space between 50 and dB, this was missed.  Both your sample(s) seem correct
2. I think keeping the regular dash - is fine then, in the spirit of minimizing exceptions as you suggest. Understood on stripping the $.

**Issue with quad**
In my pre-import BibTeX, I had `space\quad quad`, ie. there is a space after the `\quad` command.  Your JSON sample seems fine (e.g. `<e2><80><83>` is inserted).  But on export, it produces `space\quadquad`. My TeX package complains because \quadquad is not a command. I guess there might be a similar issue for any [A-Za-z] type command that is mapped? (they need a space to separate from the subsequent text, whereas things like \, do not).  Not sure on the exact rule for this, or how it should be handled.  Would need to dig.  If there is a deterministic rule then maybe something can be added to the map generation to detect when a space is required and insert it directly into the map?

Otherwise looks good!  When I have a bit more time (maybe later today or tomorrow) I can try running on my whole library and see if I notice anything else....

**Comment by retorquere** [comment]
**Superscript '2'**

There's a special case (I know, I know) for `^1`, `^2` and `^3`; all the rest still gets wrapped in `<sup>...</sup>`, but the behavior on export is exactly the same.

**Issue with quad**

Ugh, right. Could I bother you for a testcase? Inport [this](https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/472/test/fixtures/import/Math%20markup%20to%20unicode%20not%20always%20imported%20correctly%20%23472.json), export to Better BibLaTeX or Better BibTeX (please specify which), correct it, and post the corrected bib file here? I know where the problem is, but I'd prefer to have a testcase to prevent regressions.

**Comment by jeff-kerr** [comment]
Sure, attached: [testexport_v3.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/210906/testexport_v3.bib.txt)
  
Only change I had to make was adding a space after \quad.

Imported my full library and noticed one or two more things during a quick peruse.  I'll try to compile into a separate test case for those and you can see if there's something that can/should be done!

**Comment by jeff-kerr** [comment]
Ok so it turns out the only thing significant enough to report involves the degree symbol 
U+00B0 -> °. If I use this code in Zotero and export with BBT, I get `\textdegree`, which I found out doesn't work in mine (and from what I've read, other) TeX package unless you include an extra package `\usepackage{textcomp}` in the doc.  With the package it works.  

The way I learned to specify degree symbol was like this: `$^\circ$` (eg. in math mode), and this doesn't require the extra package, so this is how I have it in my current .bib library.  Not sure if you want to add one more exception :).  Otherwise I have nothing else to report -- great work!

**Comment by retorquere** [comment]
I think I have that covered now, too. Tests are running, but I'm getting some sleep now -- busy day ahead.

**Comment by jeff-kerr** [comment]
Awesome, this is great.  Makes sense on the sleep, judging by the timestamps :)  Happy to test on my lib when it's ready!

**Comment by retorquere** [comment]
Finally, all tests green! If you could give [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.43-circle-2173.xpi) a spin, I'd appreciate it.

**Comment by jeff-kerr** [comment]
Imported my library and it looks great!  Thanks so much!  I can close this.

**Comment by retorquere** [comment]
Super, I've scheduled a release build, 1.6.44 should be out soon.

**Comment by retorquere** [comment]
An earlier comment I posted got lost somehow -- I'm exporting `U+2003` to `\quad{}` rather than `\quad<space>` because of [this](https://github.com/retorquere/zotero-better-bibtex/issues/69). Import will recognize both.

**Comment by jeff-kerr** [comment]
Great, yes I saw that in my test and it works!
