### ISSUE TITLE
Possible key generation scheme issue with [journal:nopunct]

### ISSUE THREAD

**Issue by dmbortz** [retorquere/zotero-better-bibtex#474]
Hello,

I had been using [authors3][year][journal:nopunct] as my key scheme for awhile now.  With pubgin version 1.6.43, I just noticed that the keys are only generated as if the scheme was [authors3][year].  I don't know how long this has been like this, but I've just upgraded to zotero 4.0.29.2 and the problem still seems to be there.

Any suggestions?

thanks!
D

**Comment by retorquere** [comment]
Can you right-click such a reference and post the resulting debug ID (after clicking through) here?

**Comment by dmbortz** [comment]
I've never used the "error report" system before - I just did as you said and the ID came up as:

2DH5SZ37

**Comment by dmbortz** [comment]
I think I did this for an entry where the journal is correct.  Here's one where the journal is not included in the key:

KMDAICUW

**Comment by retorquere** [comment]
Bugger. It seems I have misread the Jabref specs back when I started.

**Comment by retorquere** [comment]
I have a few other issues open that I'm going to bundle in the next release, if you're in a hurry you can grab https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.43-circle-2129.xpi

**Comment by dmbortz** [comment]
Awesome! Thanks so much...

On Wed, Apr 6, 2016 at 11:19 AM, retorquere <notifications@github.com>
wrote:

> Closed #474
> <https://github.com/retorquere/zotero-better-bibtex/issues/474>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/retorquere/zotero-better-bibtex/issues/474#event-617156256>
>



-- 
DM Bortz
Department of Applied Mathematics
University of Colorado
Boulder, CO 80309-0526
http://mathbio.colorado.edu
