### ISSUE TITLE
Cannot install the plugin zotero-better-bibtex--1.6.43 in JurisM Standalone 4.0.29.6m63

### ISSUE THREAD

**Issue by agathek** [retorquere/zotero-better-bibtex#475]
Hello,

Thanks for your great work! I can't install the pluggin zotero-better-bibtex--1.6.43 in JurisM Standalone 4.0.29.6m63, i get the following error message:
The add-on "Zotero Better Bib(La)Tex" could not be installed. It may be incompatible with this version of Zotero Standalone.

 I am not running  jurism or zotero online simultaneously.

I hope you can help!

all the best

Agathe

**Comment by retorquere** [comment]
It's currently not compatible with Juris-M. I've scheduled a full test run to see how much is broken, but Juris-M and Zotero differ internally, and BBT pretty pervasively depends on/alters internal behavior of Zotero.

**Comment by retorquere** [comment]
Errors, errors everywhere. I've contacted [Juris-M](https://github.com/Juris-M/zotero/issues/16) to see if they can shed some light, but it's more involved than declaring compatibility in the install manifest.

**Comment by agathek** [comment]
***thank you***

> On 09 Apr 2016, at 18:04, retorquere <notifications@github.com> wrote:
> 
> Errors, errors everywhere. I've contacted Juris-M <https://github.com/Juris-M/zotero/issues/16> to see if they can shed some light, but it's more involved than declaring compatibility in the install manifest.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/retorquere/zotero-better-bibtex/issues/475#issuecomment-207813106>

Agathe Keller
06 63 28 77 49

58 bis rue de Paris
93100 Montreuil sous Bois

**Comment by retorquere** [comment]
BBT is updated, and will be released as soon as Juris-M updates to .7 -- some bugs were fixed in Juris-M that BBT needs.

**Comment by agathek** [comment]
great news!
> On 16 Apr 2016, at 18:09, retorquere <notifications@github.com> wrote:
> 
> BBT is updated, and will be released as soon as Juris-M updates to .7 -- some bugs were fixed in Juris-M that BBT needs.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/retorquere/zotero-better-bibtex/issues/475#issuecomment-210847698>

Agathe Keller

tel : +33 1 57 27 68 87

Université Paris 7 Laboratoire SPHERE UMR 7219 
Bâtiment Condorcet
Parcels: 3è étage bureau 387A
Office: 6th floor 688 A
 10 rue A.Domont et L.Duquet
75013 PARIS

Postal Address :
Université Paris 7 - CNRS
Laboratoire SPHERE UMR 7219
Equipe Sphere
Case 7093
5 rue Thomas Mann
75205 PARIS CEDEX 13
France

**Comment by retorquere** [comment]
The new release is out, it should work with Juris-M.

**Comment by agathek** [comment]
ok as soon as I can , i’ll test it.
thanks

> On 20 Apr 2016, at 22:55, retorquere <notifications@github.com> wrote:
> 
> The new release is out, it should work with Juris-M.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/retorquere/zotero-better-bibtex/issues/475#issuecomment-212602837>

Agathe Keller

tel : +33 1 57 27 68 87

Université Paris 7 Laboratoire SPHERE UMR 7219 
Bâtiment Condorcet
Parcels: 3è étage bureau 387A
Office: 6th floor 688 A
 10 rue A.Domont et L.Duquet
75013 PARIS

Postal Address :
Université Paris 7 - CNRS
Laboratoire SPHERE UMR 7219
Equipe Sphere
Case 7093
5 rue Thomas Mann
75205 PARIS CEDEX 13
France

**Comment by retorquere** [comment]
If it works, it work in the sense that it installs and runs. There are already open issues on how BBT output can be better tuned for Juris-M.

**Comment by agathek** [comment]
It seems that what I thought were private mails, are online with my work’s address and phone number! Is there anything we can do to erase them?

further, according to one of my students who did the installation, better-bibtex doesn’t seem to work with the new version of JurisM Standalone…

with all best

Agathe

**Comment by retorquere** [comment]
I've deleted your messages. I'd need to have new issue reports from your students - I need to know what specifically doesn't work.

**Comment by retorquere** [comment]
Your student hasn't chimed in yet (no new reports on Juris-M standalone). It's really important the user him/herself reports the issue, as I can't get the required details for troubleshooting by pass-through. I need more detail than "doesn't seem to work", as that can mean anything ranging from "refuses to install" to "installed but has disabled itself" to "works, but I don't like the output".

**Comment by retorquere** [comment]
BTW I have tested BBT 1.6.52 in Juris-M 4.0.29.9m75 and that just worked for me.

**Comment by retorquere** [comment]
(that is, I've done extensive testing on 4.0.29.9m75 in Firefox, and cursory tests on 4.0.29.9m75 standalone).
