### ISSUE TITLE
Preferences GUI issue

### ISSUE THREAD

**Issue by jeff-kerr** [retorquere/zotero-better-bibtex#476]
I see a GUI problem and thought maybe I should report here.  Not sure if this is a BBT or Zotero issue.

In both the standalone and Firefox versions of Zotero on Mac OS X (10.9) The BBT preferences pane is not fully visible for me (see below) ![PNG](https://cloud.githubusercontent.com/assets/16180976/14405580/2399d810-fe60-11e5-8bc2-23bcf5537823.png)

If I expand the window size downwards, the internal pane doesn't scale with it (eg. see below)
![PNG](https://cloud.githubusercontent.com/assets/16180976/14405592/50df33d8-fe60-11e5-8b13-9638a8f825a6.png) 

So I can't seem to reveal the rest of the preferences.

**Comment by retorquere** [comment]
Definitely a BBT problem, not Zotero.

**Comment by retorquere** [comment]
Could you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2198.xpi to see if the problem is solved for you? It looks better here now.

**Comment by jeff-kerr** [comment]
Looks better, but now it overflows on the right side.  Also, seems to force the window to be full screen width.

![Screenshot](https://cloud.githubusercontent.com/assets/16180976/14446836/2a5af5b6-0028-11e6-89a2-1e6d327eeb81.png)

**Comment by jeff-kerr** [comment]
What about scroll bars for the internal pane?  The outer window could be whatever size it wants, but the internal panel can be fully viewed with scrolling?

**Comment by retorquere** [comment]
The text should just wrap according to the docs. The UI part of Mozilla is not really my expertise, so I usually just mess with the UI until it sort of works.

**Comment by jeff-kerr** [comment]
Ok cool.  Yeah definitely not my expertise either!

**Comment by retorquere** [comment]
I still need to sort out a few things, but I should have a new version to try soon.

**Comment by retorquere** [comment]
Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2220.xpi

**Comment by melsophos** [comment]
I had the same problem and the new version solves it.

**Comment by retorquere** [comment]
A new release will be out soon. I'm trying to bundle this with #466, #475 and #477.

**Comment by jeff-kerr** [comment]
Looks good now, thanks!
