### ISSUE TITLE
Expose "select" in server URL? 

### ISSUE THREAD

**Issue by scottmartincampbell** [retorquere/zotero-better-bibtex#477]
I've been tinkering with zotero-better-bibtex and the zotxt / zotxt-emacs combination and have run up against a problem with easy citekeys that are not unique. I'd like to use the BBT key in my text instead, since they are unique and easily converted for use with LaTeX as well. 

From what I can tell, zotxt can be made to output the BBT key (with some additional work) but there is no obvious way to go back to the item back in Zotero, ie: use zotxt to select the item for editing/review/opening the PDF/etc. Would it make sense for BBT to offer "select" via the server? Or maybe I've missed something.

**Comment by retorquere** [comment]
I think I could add this, but I'm not sure how useful you'll actually find
it; zotero does allow highlighting an entry by calling an url (the zotero
reports use this to highlight attachments for example) , so I'd just have
to add the citekey as an recognized identifier, but the highlight us so
faint I can never find it.

**Comment by scottmartincampbell** [comment]
I agree it's a pain to see, but using the 'select' URL is the only way I know of to jump from a citation in emacs to the item in Zotero.

**Comment by scottmartincampbell** [comment]
Here's an idea that might be simpler: could you create a translator similar to the Pandoc citation and LaTeX citation translators, but writes an org-mode link?  More or less the same as what `zotxt-org-insert-reference-link` creates. As in: 

`[[zotero://select/items/libraryid_itemid][@betterbibtexkey]]`

It looks like it would only be an extra two or three simple lines to modify either translator (see https://gist.github.com/nschneid/3134386 for an example). I tried, but Zotero threw an error I couldn't decipher quickly.

**Comment by retorquere** [comment]
Can you give https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2204.xpi a go? `zotero://select/items/@citationkey` should work.

For group libraries, it's a little awkward, but I see no other way: `zotero://select/items/@libraryID@citationkey`, but finding out the library ID is rather odd -- right-click any collection in the group library, select 'BibLaTeX URL', and in the resulting URL, which will look like `http://localhost:23119/better-bibtex/collection?/<number>/CVHZ2S6F.biblatex`, `<number>` is your library ID.

I'd rather not add to the proliferation of BBT translators. I could perhaps add an option to pandoc citation to generate those links, if org-mode is largely pandoc compatible, but in either case I don't know what URL to generate when you select more than one reference.

**Comment by retorquere** [comment]
Forget about that previous version, I didn't check in everything. I'm trying to get a new version built, but Mozilla extension signing is currently broken, so I have to wait until that gets fixed.

**Comment by scottmartincampbell** [comment]
That's why it didn't work. Thanks for the update.

I can understand the reluctance to add more translators, but an option for org-mode would be very handy for quick copying. For multiple references, I think the best option is multiple org links. As in: 

`[[zotero://select/item/id1][@betterbibtexkey1]] [[zotero://select/item/id2][@betterbibtexkey2]]`

I'm not sure why my efforts to modify yours failed--I just added two lines to create and write the zotero id in the org-mode link, renamed the translator and gave it a new guid.

**Comment by retorquere** [comment]
The translators in that gist don't look like mine.

Getting a copy of my translator and modifying the guid should work as long as BBT is installed. What error were you getting?

What does zotxt-org-insert-reference-link do? And what doesn't it do that you want it to?

**Comment by scottmartincampbell** [comment]
The translator error was generic--"An error occured tried to export selected file". I'm tried to figure out the debug log. 

In the mean time, zotxt-insert-reference-link creates a link like this:

`[[zotero://select/items/libraryID_itemID][key]]`

By default, the key is the Easy Citekey, but it's possible to change the key to a better bibtex key. This works great from within emacs, but I'd like to be able to quick copy or drag from zotero, which needs an export translator.

**Comment by retorquere** [comment]
Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2220.xpi ; in the preferences, set Quick Cite to `org mode`, and choose `BBT Quick Copy` as the Quick Copy translator.

**Comment by scottmartincampbell** [comment]
I tried it, and while the  both `pandoc` and `LaTeX` work, `org mode` doesn't copy anything to the clipboard (or export anything to a file).  There is an error in the debug log that seems relevant:

`(5)(+0000000): Translate: [better-bibtex:Better BibTeX Quick Copy] Zotero doesn't support getting the group ID inside a translator, sorry http://zotero.org/users/[numbers]/items/APGUKV4E {"libraryID":"[numbers]","key":"APGUKV4E"}`

`(3)(+0000001): Translate: Translation successful`

`(5)(+0000000): Translate: Running handler 0 for done`

It's not a group item I'm trying to export. Thanks for your help with this, by the way.

**Comment by retorquere** [comment]
Sorry: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2221.xpi

**Comment by scottmartincampbell** [comment]
Well, that worked (perfectly) but now `zotxt` isn't with an error `REQUEST [error] Error (error) while connecting to http://127.0.0.1:23119/zotxt/items.`

I went back to the last release 1.6.45 and zotxt started working again.

**Comment by retorquere** [comment]
That must mean zotxt is requesting one of the translators I bundled into
quick copy. I think I can emulate that fairly easily.

**Comment by retorquere** [comment]
That is, if I knew what it was calling. There will be an error in the logs which will tell me more.

**Comment by retorquere** [comment]
Ah wait you already included an error message earlier. Really don't know what breaks if there is nothing else in the logs. I've asked the Zotxt author to help out: https://gitlab.com/egh/zotxt/issues/38

**Comment by retorquere** [comment]
No, wait again, that must be an emacs error rather than a Zotero error. Can you get me a zotero error for when that happens?

**Comment by retorquere** [comment]
Try this version: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2225.xpi with export mode set to org-mode (can be any, but zotxt expects pandoc mode, and I'm curious if my workaround is effective)

**Comment by scottmartincampbell** [comment]
Here's the debug. Zotxt-emacs is able to search for records (I cut that part of the log) but I think that when it tries to grab the bbt key, zotxt (the actual firefox extension) can't find the translator. Does that make sense?



----
(5)(+0002862): GET /zotxt/items?key=0_7888P8HK&format=betterbibtexkey HTTP/1.1
Host: 127.0.0.1:23119
User-Agent: curl/7.43.0
Accept: */*
Accept-Encoding: deflate, gzip



(5)(+0000001): SELECT ROWID FROM items WHERE libraryID IS NULL AND key=?

(5)(+0000000): Binding parameter 1 of type string: "7888P8HK"

(4)(+0000000): Translate: Binding sandbox to http://www.example.com/

(4)(+0000006): Translate: Parsing code for undefined (9b85ff96-ceb3-4ca2-87a9-154c18ab38b1, undefined)

(1)(+0000001): Error: Translator undefined is unsupported within this environment
    ===== Stack Trace =====
    Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1206:1
    Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1189:58
    Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1574:16
    Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1189:4
    Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:2265:3
    Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.translate@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:1241:1
    myExport@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:275:5
    handleResponseFormat@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:386:13
    itemsEndpoint@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:502:5
    Zotero.Server.DataListener.prototype._processEndpoint@chrome://zotero/content/xpcom/server.js:412:4
    Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:274:3
    Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:197:4
    =======================

(2)(+0000000): Translate: Translation using no translator failed: 
string => Error: Translator undefined is unsupported within this environment
stack => Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1206:1
Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1189:58
Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1574:16
Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1189:4
Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:2265:3
Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.translate@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:1241:1
myExport@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:275:5
handleResponseFormat@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:386:13
itemsEndpoint@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:502:5
Zotero.Server.DataListener.prototype._processEndpoint@chrome://zotero/content/xpcom/server.js:412:4
Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:274:3
Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:197:4

url => undefined
downloadAssociatedFiles => true
automaticSnapshots => false

(5)(+0000000): Translate: Running handler 0 for done

(5)(+0000000): HTTP/1.0 400 Bad Request
X-Zotero-Version: 4.0.29.7
X-Zotero-Connector-API-Version: 2
Content-Length: 0

**Comment by retorquere** [comment]
This is with the last version I put up above?

**Comment by scottmartincampbell** [comment]
Yes. I guess the new translator GUID is the problem, based on your comment over here (https://gitlab.com/egh/zotxt/issues/38) and the log.

**Comment by retorquere** [comment]
That last version modified Zotero behavior to pick the new translator when the old one is requested. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2242.xp ? It'll fail, but there's additional logging, so if you send me a debug report after the failure, I'll know what's happening.

**Comment by retorquere** [comment]
Forget that last version, I found at least one cause of it failing, new build is preparing.

**Comment by retorquere** [comment]
Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2245.xpi

**Comment by scottmartincampbell** [comment]
This has more debug info. JSON syntax error?


(5)(+0003491): GET /zotxt/items?key=38275_ZGQTP2CT&format=betterbibtexkey HTTP/1.1
Host: 127.0.0.1:23119
User-Agent: curl/7.43.0
Accept: */*
Accept-Encoding: deflate, gzip



(5)(+0000001): SELECT ROWID FROM items WHERE libraryID=? AND key=?

(5)(+0000000): Binding parameter 1 of type int: 38275

(5)(+0000000): Binding parameter 2 of type string: "ZGQTP2CT"

(3)(+0000000): SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    ===== Stack Trace =====
    Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.setTranslator@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:1071:1
    myExport@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:267:5
    handleResponseFormat@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:386:13
    itemsEndpoint@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:502:5
    Zotero.Server.DataListener.prototype._processEndpoint@chrome://zotero/content/xpcom/server.js:412:4
    Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:274:3
    Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:197:4
    =======================

(5)(+0000001): HTTP/1.0 500 Internal Server Error
X-Zotero-Version: 4.0.29.7
X-Zotero-Connector-API-Version: 2
Content-Length: 0

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2255.xpi

**Comment by retorquere** [comment]
Please let me know if this version does better.

**Comment by scottmartincampbell** [comment]
Still not working.

(5)(+0000450): GET /zotxt/items?key=38275_RKEXCTEZ&format=betterbibtexkey HTTP/1.1
Host: 127.0.0.1:23119
User-Agent: curl/7.43.0
Accept: */*
Accept-Encoding: deflate, gzip



(5)(+0000000): SELECT ROWID FROM items WHERE libraryID=? AND key=?

(5)(+0000000): Binding parameter 1 of type int: 38275

(5)(+0000000): Binding parameter 2 of type string: "RKEXCTEZ"

(3)(+0000001): TypeError: Zotero.BetterBibTeX.translators.BetterBibTeXQuickCopy is undefined
    ===== Stack Trace =====
    Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.setTranslator@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:1071:9
    myExport@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:267:5
    handleResponseFormat@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:386:13
    itemsEndpoint@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/scott/.mozilla/firefox/otwupv7d.default/extensions/zotxt@e6h.org/bootstrap.js:502:5
    Zotero.Server.DataListener.prototype._processEndpoint@chrome://zotero/content/xpcom/server.js:412:4
    Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:274:3
    Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:197:4
    =======================

(5)(+0000000): HTTP/1.0 500 Internal Server Error
X-Zotero-Version: 4.0.29.7
X-Zotero-Connector-API-Version: 2
Content-Length: 0

**Comment by retorquere** [comment]
OK, I think I've got it. I've submitted a change request to zotxt, but in the meantime, this should do it: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2262.xpi

**Comment by scottmartincampbell** [comment]
Hooray. That did it.  Thanks so much. This will help my workflow enormously.

**Comment by retorquere** [comment]
OK, once I close #466 and #475 I'm going to cut a new release

**Comment by retorquere** [comment]
I see you've reopened the issue, is something still amiss?

**Comment by scottmartincampbell** [comment]
s

**Comment by scottmartincampbell** [comment]
Hi again. Sorry to be a bother. I was just testing this with group libraries, and quick copy failed, popping up: "An error occurred while trying to export the selected file.". This is the debug log:

(3)(+0053031): copySelectedItemsToClipboard
(4)(+0000001): Translate: Binding sandbox to http://www.example.com/
(4)(+0000005): Translate: Parsing code for Better BibTeX Quick Copy (9b85ff96-ceb3-4ca2-87a9-154c18ab38b1, 2016-04-17 10:48:18)
(3)(+0000004): Translate: Beginning translation with Better BibTeX Quick Copy
(1)(+0000007): ReferenceError: local is not defined
    ===== Stack Trace =====
    Mode.orgmode@/home/???/zotero/translators/Better BibTeX Quick Copy.js:1597:11
    doExport@/home/???/zotero/translators/Better BibTeX Quick Copy.js:1612:12
    =======================
(2)(+0000000): Translate: Translation using Better BibTeX Quick Copy failed: 
string => ReferenceError: local is not defined
stack => Mode.orgmode@/home/???/zotero/translators/Better BibTeX Quick Copy.js:1597:11
doExport@/home/???/zotero/translators/Better BibTeX Quick Copy.js:1612:12

url => undefined
downloadAssociatedFiles => true
automaticSnapshots => false

(5)(+0000000): Translate: Running handler 0 for done

(5)(+0001230): SELECT collectionID FROM collections WHERE collectionID IN (SELECT collectionID FROM collectionItems WHERE itemID=?)

(5)(+0000000): Binding parameter 1 of type int: 44

**Comment by retorquere** [comment]
Oops.

**Comment by retorquere** [comment]
A new build is up at https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2289.xpi. Group libraries ought to work now.

**Comment by scottmartincampbell** [comment]
Something isn't quite right. 

1) I think the select URL has a typo. I think it should be zotero://select/items (with an 's'). 

2) The library ID isn't right. I can get the right ID by right-clicking the group collection and using "Biblatex URL". That ID works.

**Comment by retorquere** [comment]
1) Damn, you're right. Sorry about that.

2) OK, then I misunderstood the Zotero devs... the translators get the group ID, and the select URL expects the library ID, which annoyingly enough are not the same. I've tried to work around it with https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2290.xpi

**Comment by scottmartincampbell** [comment]
1) Well, it was mostly working; I only noticed when debugging the actual link. I don't know what difference it makes. 

2) That works. Thanks. However, there is something odd going on zotxt-emacs and org-zotxt-mode. For a short period of time, it won't return the zotoro://select link, just the BBT key. It went away, so I can't quite reproduce it yet. I'll keep trying.

**Comment by retorquere** [comment]
OK, you want me to hold off a release?

**Comment by scottmartincampbell** [comment]
I can't figure out the pattern. And if it does happen, BBT org-mode quick copy still works, and then the zotxt-emacs problem seems to go away. So I'll close for now and you can release if you're okay with that. If I can uncover a pattern I let you know.

**Comment by retorquere** [comment]
No idea what could be the cause of that. In some sense it would have to mean the value of the preference fluctuates. 

I just heard back from the zotero devs, and my solution for group libraries works, but only locally. The library id for the same group will differ per synced client.

**Comment by retorquere** [comment]
Wait, are there any messages in the light when you get only the key?

**Comment by retorquere** [comment]
(in the log I meant).

Reopening this issue because the links are a point of concern. The translator doesn't have easy access to the relevant data.

**Comment by scottmartincampbell** [comment]
I have figured out problem with zotxt-emacs inserting links. It was an emacs configuration problem and some inconsistency on my part in testing it. All is working reliably now. 

As for the problem with local group IDs and synced computers, I hadn't tested that yet with your translator or zotxt-emacs, so I don't know what to expect. I should have a chance later today to try that.

**Comment by retorquere** [comment]
It's more a question of what is desirable. The links generated will only work for the PC they were created on. The links are now of two kinds:

1. For references in your personal library, the links will have an ID like `0_<key>`. These are globally unique
2. For references in group libraries, the links will have an ID like `<number>`, which are the *local* identifiers of the reference

The `zotero://select` protocol doesn't support links with ID `<group ID>_<key>`, which would be valid wherever you called them, only `<library ID>_<key>` or `<item ID>`. Library ID and item ID are only valid on a single PC -- it just happens to be the case that `0` is an alias for `this PCs local library`. If you sync your PC to another through the Zotero servers, the group libraries you have get a single identifying group ID (which you cannot use in the select URL) and on each PC you sync to a local library ID (but there's no way to map one to the other in a translator).

I'm going to try something else. I think I know a way.

**Comment by retorquere** [comment]
Could you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2294.xpi ?

**Comment by scottmartincampbell** [comment]
That didn't work.

When I quick copied from a group library, the URL generated was: 
`[[zotero://select/items/@{groupID}~VEZCXQKD][@bell1996_University]]`



Then, when I tried to quick copy from my library, there was an error and the following in the debug log:

(3)(+0020188): copySelectedItemsToClipboard
(4)(+0000001): Translate: Binding sandbox to http://www.example.com/
(4)(+0000005): Translate: Parsing code for Better BibTeX Quick Copy (9b85ff96-ceb3-4ca2-87a9-154c18ab38b1, 2016-04-19 15:29:16)
(3)(+0000004): Translate: Beginning translation with Better BibTeX Quick Copy
(5)(+0000006): SELECT linkedItemID FROM itemSeeAlso WHERE itemID=?
(5)(+0000000): Binding parameter 1 of type int: 658
(5)(+0000000): SELECT tagID, name FROM tags WHERE tagID IN (SELECT tagID FROM itemTags WHERE itemID=?)
(5)(+0000000): Binding parameter 1 of type int: 658
(5)(+0000001): SELECT collectionID FROM collectionItems WHERE itemID=?
(5)(+0000000): Binding parameter 1 of type int: 658
(5)(+0000000): SELECT ROWID FROM relations WHERE 1 AND subject=?
(5)(+0000000): Binding parameter 1 of type string: "http://zotero.org/users/35159/items/7Z9TGCKK"
(5)(+0000000): SELECT itemID FROM itemSeeAlso WHERE linkedItemID=?
(5)(+0000000): Binding parameter 1 of type int: 658
(5)(+0000000): SELECT COUNT(*) FROM deletedItems WHERE itemID=?
(5)(+0000001): Binding parameter 1 of type int: 658
(5)(+0000000): SELECT A.itemID, value AS title FROM itemAttachments A NATURAL JOIN items I LEFT JOIN itemData ID ON (fieldID=110 AND A.itemID=ID.itemID) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE sourceItemID=? AND A.itemID NOT IN (SELECT itemID FROM deletedItems)
(5)(+0000000): Binding parameter 1 of type int: 658
(5)(+0000000): SELECT N.itemID, title FROM itemNotes N NATURAL JOIN items WHERE sourceItemID=? AND N.itemID NOT IN (SELECT itemID FROM deletedItems)
(5)(+0000000): Binding parameter 1 of type int: 658
(1)(+0000003): TypeError: groupID.startswith is not a function
    ===== Stack Trace =====
    Mode.orgmode@/home/???/zotero/translators/Better BibTeX Quick Copy.js:1599:16
    doExport@/home/???/zotero/translators/Better BibTeX Quick Copy.js:1620:12
    =======================

**Comment by retorquere** [comment]
So sorry about that. [This](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2303.xpi) should fix both.

**Comment by scottmartincampbell** [comment]
Yes, that's working again. Thanks!

**Comment by retorquere** [comment]
Super -- thanks!
