### ISSUE TITLE
Some additional processing

### ISSUE THREAD

**Issue by melsophos** [retorquere/zotero-better-bibtex#479]
I am opening this issue following the discussion in #460 in order to not mix different topics, which I guess is easier to handle for you.

> @melsophos what kind of math strangeness?

Typically this: `\textdollar{}{{S}}\^{}1 \ensuremath{\backslash}times {{S}}\^{}3\textdollar{}`, instead of the simple `$S^1 \times S^3$`.

> And you can avoid the brackets by either sentence-casing your titles (which is what zotero recommends) or setting the language to non-English.

I prefer to keep the same casing as the one in the title of the paper, and in particular to keep accents for english titles. Moreover this is necessary when there are abbreviation. What I wanted to say is that the complicated-looking title

    {{{BV Master Action}} for {{Heterotic}} and {{Type II String Field Theories}}}

can be replaced by the simpler one

    {{BV Master Action for Heterotic and Type II String Field Theories}}

But after reading several sites on the topic, I am not sure that this is the good solution: it seems that one should protect only things like first name and abbreviation, and let the bibtex style capitalize or not. Note that I don't like so much this solution either because if I have both french and english titles in my bibliography I don't know if bibtex will use different rules.

**Comment by retorquere** [comment]
Yes! Thank you, separate issue *much* appreciated. In order

## math mode

I assume you have `$S^1 \times S^3$` somewhere in your title, and you want that output in math mode. BBT can't know whether you wanted math mode or whether you wanted literally `$S^1 \times S^3$`, in which case `\textdollar{}{{S}}\^{}1 \ensuremath{\backslash}times {{S}}\^{}3\textdollar{}` is actually correct. If you want untranslated LaTeX output, you can have `titles that have <pre>$S^1 \times S^3$</pre> in them` and BBT will pass on the part between `<pre>...</pre>` unmodified.


## sentence casing

Indeed, style capitalization is why BBT doesn't surround the whole text in double-braces. The double-double braces are another workaround to prevent things like https://github.com/retorquere/zotero-better-bibtex/issues/383#issuecomment-153904326 . If you sentence-case your Zotero references, BBT will Title Case them by default or for references marked as English, and will keep them unchanged (whatever sentence or titlecasing you might have otherwise) if not. Which is odd, but apparently specced behavior (see same thread)

**Comment by retorquere** [comment]
Wow that last sentence makes no sense. Here's what I meant:

## sentence casing

Indeed, style capitalization is why BBT doesn't surround the whole text in double-braces. The double-double braces are another workaround to prevent things like https://github.com/retorquere/zotero-better-bibtex/issues/383#issuecomment-153904326 . The idea is that you sentence-case your Zotero references (as Zotero recommends), and then it gets a little complicated.

There are two things that affect capital letters: Title Casing and Capital Preservation.

Capital Preservation is always on for certain fields like titles. If you have capitals in a word except the first, BBT assumes you meant it to be there, and you want BibTeX to leave it alone no matter what. To do that, it wraps those (strings of) words in double braces. This is to let BibTeX know that `ISDN` may not be changed to `isdn` or `Isdn`.

For English titles (and if no language is set, it is assumed to be -- I know, how very un-post-colonial of me), it will Title Case the title on output, but those Title Cased words BBT changed itself will *not* be wrapped in double-braces, as it *is* OK for the styles to change casing for those, depending on the style at play. So `I like ISDN heaps better than dialup` would output to `I Like {{ISDN}} Heaps Better than Dialup`. Apparently non-English titles are supposed to be in sentence case, so BBT doesn't touch those. See again this thread: https://github.com/retorquere/zotero-better-bibtex/issues/383#issuecomment-153904326 . Bib(La)TeX be crazy.

**Comment by retorquere** [comment]
For the math issue, see also the Hardcore page on the wiki.

**Comment by retorquere** [comment]
That would be the "From unicode" page, sorry

**Comment by melsophos** [comment]
Correctly, I have $S^1 \times S^3$ in the title and would like to keep it like this, such that Latex displays it nicely as a formula. But I understand that it might get tricky to recognize precisely what is a formula and what is not. On the other hand I don't like to add `<pre>` because this adds more text inside Zotero fields and display, but I prefer to keep it clean.

For the title I understand better the point, I never thought thoroughly to the problem. I think I should remove from my script this double bracing and keep the default behaviour, the problem is that I don't want to lowercase all the titles of my entries, there are too many of them! (since the capitalization is preserved when saving the document). I will think to this but I am not sure that you should change anything in BBT.

**Comment by retorquere** [comment]
It's not just that it's tricky -- the intent is to have LaTeX render what the user typed, and if the user typed `math formulas in LaTeX look like $S^1 \times S^3$` to `math formulas in LaTeX look like $S^1 \times S^3$` it would render to "math formulas in LaTeX look like S<sup>1</sup> x S<sup>3</sup>", which is not what the user entered. If you want to export LaTeX as LaTeX without `<pre>`, add the tag `#LaTeX` to the reference, and it will assume you want LaTeX to be exported unchanged for most of its fields (things like URLs etc are always escaped). But there must be a way to signal "I want dollar signs" or "I want math mode". It's not safely detectable.

You don't have to lowercase the titles; if you want them Title Cased, the bracing will preserve that. Zotero has built-in functions to changes titles to sentence/title case BTW.

**Comment by retorquere** [comment]
Anything else I can explain on this topic? Anything you disagree with? If I missed something I'd love to improve BBT.

**Comment by melsophos** [comment]
Thanks a lot for all these explanations; and sorry for the late answer, these last days were busy. The #LaTeX tag is a good idea!
