### ISSUE TITLE
Auto-incrementing citation key?

### ISSUE THREAD

**Issue by jeff-kerr** [retorquere/zotero-better-bibtex#480]
I wonder if I could make a feature request.

I have a database that originally began in RefWorks.  There, the citation keys were just an ID number that would increment by 1 each time a reference was added.   It's a simple system, but I've stuck with it ever since (migration to JabRef and now to Zotero), and actually kind of like it.  

The question is, would it be possible to add such an auto-incrementing ID number for the citation key generator in BBT?  Ideally the option would force a scan of the existing ID numbers and would start with the next ID beyond the highest ID found.  I also wouldn't mind interacting with it as an option in the hidden menu (maybe specify a starting place for the ID number and it would just increment by 1 each time it is used).

Let me know what you think.

**Comment by retorquere** [comment]
You should be able to get mostly there by just using [id] as a pattern. It
won't scan for existing entries, but existing entries should have gotten
pinned keys on import if you imported as bibtex, and the newer ones will
get the zotero-assigned internal id, which is unique to an installation of
zotero, usually consecutive, and the import should have taken the lower
numbers.

How on earth do you keep apart what you're citing though? I have some 3000
refs in Zotero, no frigging way I'd know what reference 1578 would mean in
a paper.

**Comment by jeff-kerr** [comment]
Thanks, indeed it is close!

Yes it is a good question :)  When citing, I likely wouldn't remember the exact citation key for a paper, so I don't think I'm loosing much just grabbing from Zotero.  Once inside, if needed, I can see what was cited just using the output references.  Readability of the TeX is not as great I'll admit though.  Might abandon this soon... kinda something I just held over from Refworks!  At least the key generation and lack of clashing is simple...

**Comment by retorquere** [comment]
It makes me think Refworks wasn't really concerned with BibTeX users. I've never heard of meaningless citation keys as a desideratum.

**Comment by jeff-kerr** [comment]
Indeed.  Followup question, is there a nice way (existing database?) for handling journal acronyms in the BBT citekey generation?  For example, for "Proceedings of the National Academy of Sciences" the abbreviation would be something like "Proc. Natl. Acad. Sci. U.S.A.", but for the citekey you would want PNAS.

**Comment by retorquere** [comment]
I think `[journal:abbr]` does that if you have a journal abbrev filled out (although it will probably turn into PNASU -- haven't tried). You can enable BBT auto-abbrev and it will use the abbrevs Zotero generates if you don't have one filled out, but they are of varying quality.

**Comment by jeff-kerr** [comment]
Nice thank you.  I will give it a look!
