### ISSUE TITLE
The link in the add-on pane of FF points to the wrong URL

### ISSUE THREAD

**Issue by duncdrum** [retorquere/zotero-better-bibtex#481]
The link in the addon-pane points to 
``https://retorquere.github.io/better-bibtex/``
resulting in ``404 error``
![screenshot 2016-04-21 15 16 38](https://cloud.githubusercontent.com/assets/6205362/14710105/5c342978-07d4-11e6-8c49-b4962dda4aa9.png)

it should point to 
``https://github.com/retorquere/zotero-better-bibtex/wiki``

**Comment by retorquere** [comment]
Thanks for reporting it, will be fixed in the next release (day or so)
