### ISSUE TITLE
Dollar sign in title not properly escaped

### ISSUE THREAD

**Issue by jlongrc** [retorquere/zotero-better-bibtex#485]
I add the question mark because the way it was done didn't catch my eye as incorrect, but for some reason is causing problems. The title of the citation is `The largest U.S. companies would owe $620 billion in U.S. taxes on the cash they store in tax havens, the equivalent of our defense budget. [Tweet]` and I am exporting via Better Biblatex to a *.bib file.

Using 1.6.48 and Zotero Standalone 4.0.29.5. Compiling with latexmk. Here's a **mwe**

```
\documentclass{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage[style=apa,sortcites=true,sorting=nyt,backend=biber]{biblatex}
\usepackage{filecontents}
\DeclareLanguageMapping{american}{american-apa}

\begin{filecontents*}{bib.bib}
	@online{sanders_largest_2016,
	  title = {The largest {{U}}.{{S}}. companies would owe \textdollar{}620 billion in {{U}}.{{S}}. taxes on the cash they store in tax havens, the equivalent of our defense budget. [{{Tweet}}]},
	  url = {https://twitter.com/SenSanders/status/717771426284060673},
	  titleaddon = {SenSanders},
	  author = {Sanders, Bernie},
	  date = {2016-04-06}
	}
\end{filecontents*}

\addbibresource{bib.bib}

\begin{document}
 
\cite{sanders_largest_2016}

\printbibliography

\end{document}
```

Running this will get you these error messages, which are apparently due to the way the dollar sign is escaped: 

```
E: mwe.tex:25 Extra }, or forgotten $
E: mwe.tex:25 Missing $ inserted
E: mwe.tex:25 Missing } inserted
```

The issue seems to be `\textdollar{}`. Dropping the brackets doesn't help. On the other hand, you will see that it works fine if you change `\textdollar{}` to `\$`. Not sure if the export to `\textdollar{}` is a non-default behavior that I've unintentionally prompted.

**Comment by retorquere** [comment]
That's a bug indeed. Could you do me a favor, right-click that reference, and select "Send BetterBibTeX Error"? That will give me a testcase so it won't reappear by accident later. If you post the resulting debug ID (red), I'll know which testcase is yours.

**Comment by retorquere** [comment]
NM, I just imported your MWE, that will do as a testcase.

**Comment by retorquere** [comment]
All my tests pass, could you give https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.48-circle-2329.xpi a go?
