### ISSUE TITLE
"[zotero]" citekey format doesn't match zotero's default format

### ISSUE THREAD

**Issue by e-matteson** [retorquere/zotero-better-bibtex#487]
The better-bibtex "[zotero]" format handles colons differently than zotero does by default. For example, for the paper ["Biomaterials: Where We Have Been and Where We Are Going"](https://www.ncbi.nlm.nih.gov/pubmed/15255762) the default zotero citekey is   `ratner_biomaterials:_2004` and the "[zotero]" format citekey is `ratner_biomaterials_2004`.

This is inconvenient if you start using better-bibtex and want the new bib file to match your existing citations.

**Comment by retorquere** [comment]
Can you right-click on such a reference and send me a debug report?

**Comment by e-matteson** [comment]
Sure, here's the report ID for the example paper mentioned above: DZEZ4XQD
Thanks for looking at it.

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.49-circle-2354.xpi works for me, can you verify? Note that the sample you submitted has a fixed citekey, that won't change unless you clear the citekey.

**Comment by e-matteson** [comment]
Yup, that corrected all the citekeys with colons in my library, and didn't change any of the other citekeys. Thanks for the quick fix!
