### ISSUE TITLE
Better BibTeX Database Corruption

### ISSUE THREAD

**Issue by doctornerdis** [retorquere/zotero-better-bibtex#488]
Before I get to my issue, I just want to thank you for BBT. It has allowed me to use Zotero in plain text situations, and that has made my research world a much happier place. I really appreciate all the work you've done and your sharing it with the rest of us.

I'm running BBT on the Zotero standalone. With the last BBT update, I have started getting the following error messages every time I start the application:

```
The Zotero database 'zotero' appears to have become corrupted.

Please restart Zotero to attempt an automatic restore from the last backup.
```

Then, after restart, I get the following:

```
The Zotero database 'zotero.sqlite' appears to have become corrupted.

Your data was restored from the last automatic backup made on 5/4/2016 at 8:54:58 AM. The damaged file was saved in your Zotero directory.
```

If I continue without restarting, Zotero still works, but I can't export or sync bib files.

I uninstalled and reinstalled Zotero without any plugins, and there were no corruption issues. But the problem started again when I added BBT.

I sent an error report. The number is **SSBNRW97**.

**Comment by retorquere** [comment]
It's actually your BBT database which has gone corrupt, not your zotero DB. Please do the following:

1. Shut down firefox completely (apple-quit, not just all windows closed)
2. go into your Firefox profile directory (` ~/Library/Application\ Support/Firefox/Profiles/*/zotero`). If you still see `sqlite-journal` files, go back to step 1
3. `betterbibtex-lokijs.sqlite` into https://dbinbox.com/retorquere

if you want to get back to work immediately, remove `betterbibtex-lokijs.sqlite`, and Zotero will start again. BBT will start regenerating your citation keys. I'll take a look at the database to see what's recoverable.

That doesn't solve how your database could have gotten corrupted in the first place. Were you making backups of your database using some kind of versioning system, or do you have your databases on dropbox or somesuch?

**Comment by retorquere** [comment]
Oh sorry, youre using standalone. Same goes -- make sure you really quit Zotero standalone, not just closing the last window.

**Comment by retorquere** [comment]
Rather than going into your profile directory manually, try installing this version: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.50-circle-2375.xpi . It will do a corruption check, and if corrupt, restore a backup if present.

That still leaves the question on how your DB git corrupted. There shouldn't be any way BBT can cause this itself, which was my main reason for using the Zotero DB facilities in the first place. Did you perhaps force-close Zotero, or use backup software or something like Dropbox? Those are known hazards when it comes to database corruption.

**Comment by doctornerdis** [comment]
I downloaded the second version. There was a corruption. I sent you the **betterbibtex-lokijs.sqlite.damaged** file. There was no backup to restore, but it just regenerated everything, and now everything is back to normal.

I'm not sure how the DB got corrupted in the first place. I think my computer crashed when I was syncing/exporting an existing bib file. So perhaps it was a force-close scenario like you said. At any rate, thank you so much for your help!

**Comment by retorquere** [comment]
That could be an explanation. The cache in your DB was corrupted, but the cache can be cleanly rebuilt. I could retrieve your citation key database, I can send it to you if you want. If you didn't have duplicate keys, there should be no change. In any case, super thanks for reporting this, the stuff in the build you have should be useful for everyone. I've made a few more changes, on which my tests are running again, and if they pass too, I'm cutting a new release.

**Comment by retorquere** [comment]
A new release is out. I'll hold on to the repaired DB for a bit should you still want it.

**Comment by doctornerdis** [comment]
Many thanks, but there's no need. Like you said, there's no issues since I don't have duplicate keys.
