### ISSUE TITLE
Synchronization with attachments between different computers.

### ISSUE THREAD

**Issue by hitswint** [retorquere/zotero-better-bibtex#489]
If i add some item with attachment(PDF) in zotero on one computer, everything works fine, bib file with file field is generated. 
But when i synchronize on another computer, the bib file is generated without file field, even the zotero has updated the item with attachment. It seems like the attachment addition does not invoke the update of bib file.

**Comment by retorquere** [comment]
Assuming you are attaching your PDF on computer A, and syncing (through the Zotero server) to computer B, can you do the following:

* Enable debug logging in the advanced pane of the BBT preferences on computer B
* Attach a new pdf to a reference on computer A
* Sync A, then B
* Export the corresponding reference on computer B
* Right-click the reference on computer B and select "Send BetterBibTeX Error"
* Post the resulting debug ID (the red code) here

**Comment by retorquere** [comment]
Could it be that you just submitted KXJD3D6Z? One of the associated references is titled "The evolution of cultural evolution". 

If this is yours, you've run out of quota on the Zotero server. If this is your debug ID, are you sure the attachment actually makes it over to computer B?

**Comment by hitswint** [comment]
I just submitted N9KUB9EQ, Thanks.

**Comment by retorquere** [comment]
Which log is from computer A, and which from computer B?

**Comment by hitswint** [comment]
They are all logs from computer B. First i added some chinese paper and get N9KUB9EQ. I'm afraid the log information was not clear, so i added another paper in English and get VQH5JGT8. Sorry for the trouble, you can just see the latter log.

**Comment by retorquere** [comment]
In N9KUB9EQ, I don't see any activity that indicates an attachment being added, so there's nothing to trigger BBT to update the output.

**Comment by retorquere** [comment]
There is activity in VQH5JGT8, so I'd expect to have an export happen there.

**Comment by retorquere** [comment]
I also see auto-export activity in VQH5JGT8, BTW.

**Comment by retorquere** [comment]
Could you try disabling zotfile temporarily to see if that makes a difference?

**Comment by hitswint** [comment]
S28MPUUW is the report with zotfile disabled.

**Comment by hitswint** [comment]
S28MPUUW is the report with zotfile disabled, still no file field exported.

**Comment by hitswint** [comment]
I use webdav to update pdf files, BTW.

**Comment by retorquere** [comment]
If you go into Prefs -> Advanced -> Files and Folders, what do you have "Linked Attachment Base Directory" set to?

**Comment by hitswint** [comment]
I did not set the base directory as well as the data directory location, they are all kept at default value.

**Comment by retorquere** [comment]
I don't understand -- S28MPUUW does show attachments showing up, the cache being invalidated, and  two collections are being exported. So you're saying the collections do export, but on computer B, the file paths are missing -- that's the only difference?

If so, could you try going into BBT advanced prefs, click "reset cache", and try again?

**Comment by retorquere** [comment]
Can you please upgrade to the latest release (1.6.53) and try again? Some things were fixed that might affect this problem (positively, that is).

**Comment by hitswint** [comment]
Upgrading to latest release does not help. But reset cache helps, i have tried several times and confirmed that click "reset cache" and then "export" in automatic export panel will trigger the attachment update in bib file, which is what i wanted.
AZEZ42WG is another report with no attachment update, i hope it will help a little.

**Comment by retorquere** [comment]
I think you have debug logging off in AZEZ42WG, it doesn't show any activity.

**Comment by retorquere** [comment]
It's something specific to webdav syncing. I think I have it reproduced, working on a fix.

**Comment by retorquere** [comment]
Damn, that was a lot of work. Zotero syncs WebDAV hosted attachments in two stages:

1. Get the metadata from the Zotero Server
2. Get the attachment data from WebDAV

but it tells extensions that the item has been updated after 1, but nothing after 2. So I kicked off auto-export while the attachment wasn't yet *really* in, and during export, Zotero would tell me "this is not really an attached file", and boom.

I think I have a workaround. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.55-circle-2442.xpi ?

**Comment by hitswint** [comment]
Everything works fine here, great job!
