### ISSUE TITLE
Issue Citing Websites

### ISSUE THREAD

**Issue by doctornerdis** [retorquere/zotero-better-bibtex#492]
This may be a problem for only for me because I use the Chicago author-date CSL, but I've found an issue when dealing with websites, too. I think BBL should transfer the **Website Title** in Zotero to the **Journal** or **Journaltitle** fields, not the **Titleaddon** field. 

Right now, if I have the following entry in Zotero:

<img width="335" alt="screen shot 2016-05-10 at 1 09 47 pm" src="https://cloud.githubusercontent.com/assets/16094430/15143067/8d9aaf92-16b0-11e6-94c7-a53198dad4a4.png">

It comes out as:

```
@online{snoj_population_2013,
	Author = {Snoj, Jure},
	Date = {2013-12-18},
	Langid = {english},
	Timestamp = {2016-02-01T06:48:54Z},
	Title = {Population of {{Qatar}} by {{Nationality}}},
	Titleaddon = {BQ Magazine},
	Url = {http://www.bq-magazine.com/economy/2013/12/population-qatar},
	Urldate = {2016-02-01}}
```

Which renders incorrectly as:

<img width="460" alt="screen shot 2016-05-10 at 1 17 14 pm" src="https://cloud.githubusercontent.com/assets/16094430/15143282/8d5e735a-16b1-11e6-9d95-57cd170df6ac.png">

But when you have 

```tex
@online{snoj_population_2013,
	Author = {Snoj, Jure},
	Date = {2013-12-18},
	Journal = {BQ Magazine},
	Langid = {english},
	Timestamp = {2016-02-01T06:48:54Z},
	Title = {Population of {{Qatar}} by {{Nationality}}},
	Url = {http://www.bq-magazine.com/economy/2013/12/population-qatar},
	Urldate = {2016-02-01}}
```

It renders correctly as:

<img width="463" alt="screen shot 2016-05-10 at 1 18 38 pm" src="https://cloud.githubusercontent.com/assets/16094430/15143336/cc05beec-16b1-11e6-833a-6dcd60784e2b.png">

**Comment by retorquere** [comment]
Can you right-click that reference, select "Send BetterBibTeX error", and post the resulting debug ID here?

**Comment by retorquere** [comment]
Could you first upgrade to .52 (out just now)? That has some changes to titleaddon handling.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.52-circle-2395.xpi ?

**Comment by doctornerdis** [comment]
The new version worked. Phenomenal! BBT is magic.

In case you want it, here is the debug ID: **6ST3575I**. 

Many thanks again for all your work.

**Comment by doctornerdis** [comment]
No wait, I'm still having the problem. 

For example, I changed the following entry from **Newspaper Article** in Zotero to **Webpage**.

<img width="332" alt="screen shot 2016-05-12 at 10 37 44 am" src="https://cloud.githubusercontent.com/assets/16094430/15207284/ca23814a-182d-11e6-8faa-675d7600a7f1.png">

But when it rendered like this:

<img width="536" alt="screen shot 2016-05-12 at 10 38 08 am" src="https://cloud.githubusercontent.com/assets/16094430/15207292/da5f9454-182d-11e6-84c1-f19b34e6279a.png">

I checked the bib file and got this:

```
@online{haroon_elation_2012,
	Author = {Haroon, Azmat},
	Date = {2012-01-27},
	Timestamp = {2016-05-12T07:31:14Z},
	Title = {Elation, worries on the campus},
	Url = {http://www.thepeninsulaqatar.com/news/qatar/181277/elation-worries-on-the-campus},
	Urldate = {2016-04-17},
	Bdsk-Url-1 = {http://www.thepeninsulaqatar.com/news/qatar/181277/elation-worries-on-the-campus}}
```

The is no field for the website title, either as **Journal**, **Journal Title**, or **Titleaddon**.

I just sent you an error report: **WJZ7JQSE**.

**Comment by retorquere** [comment]
.53 was released before I could merge this. If you could verify that https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.53-circle-2405.xpi does the right thing (which is .53 with the changes for this issue), I'll merge and release.

**Comment by doctornerdis** [comment]
Yup, all set. Thanks for taking care of this.

**Comment by retorquere** [comment]
A new release is underway.
