### ISSUE TITLE
QPN4XM9Z

### ISSUE THREAD

**Issue by siljamardla** [retorquere/zotero-better-bibtex#493]
I have set up automatic export of a bib file by File - Export Library - Format: Better BibTex/Better BibLaTex and checking the Keep Updated box. Updating works for a while (shows in the list in preferences and makes real updates) but after a while (usually by the next day) it is gone and I have to set up a new automatic export.
Please tell me if I'm simply doing something wrong.

**Comment by retorquere** [comment]
Can you upgrade to the latest version and try again?

**Comment by retorquere** [comment]
(it sounds like #490, which was just fixed)

**Comment by siljamardla** [comment]
Made the update, seems to work. My bad for not doing it before. To be fair, I tried but I couldn't remember how I installed the add-on in the first place :)

**Comment by retorquere** [comment]
That's OK. It will update automatically at some point (I don't know when FF decides to check), but you can force an update of your extensions by going into the hamburger menu at the top right, selecting Add-ons, then the gear dropdown, and select "check for updates".
