### ISSUE TITLE
export of report item : no institution field

### ISSUE THREAD

**Issue by dapouns** [retorquere/zotero-better-bibtex#494]
Hi,
when I export a report item with Better Bibtex, I don't get the institution field. It is here when using bibtex export. Is it a bug ? Is there a way to add this field ?
Regards
Pouns

**Comment by retorquere** [comment]
Can you right-click on that reference, select "send better bibtex report", and post the debug ID here?

**Comment by dapouns** [comment]
Here it is : KDNS9677

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.55-circle-2433.xpi ?

**Comment by dapouns** [comment]
Yes, it works !
Thank you :)
