### ISSUE TITLE
Zotero picker add page, suffix/ prefix does not work

### ISSUE THREAD

**Issue by mijalce** [retorquere/zotero-better-bibtex#495]
I use zotero-pandoc picker to insert citations from Zotero to Scrivener. 
For some time I face the following issue:
I call the zotero-pandoc picker, search for reference, add the reference, add page, suffix or prefix and press enter. In the Scrivener document it is pasted only the Citation key, not added page, suffix or prefix. I think that this started happening after I upgraded to Pandoc 1.17.0.1. Thus I do not know is it related to BBT picker or Pandoc has changed something. However, I raise the issue here because maybe there are some changes in Pandoc that need to be reflected in the picker. 
Thanks!

**Comment by retorquere** [comment]
This is the OSX zotero-pandoc picker?

**Comment by mijalce** [comment]
yes, that is the one

**Comment by retorquere** [comment]
To be specific: you're using these instructions http://davepwsmith.github.io/academic-scrivener-howto/ ? If so, which of the applets do you use?

**Comment by mijalce** [comment]
Ok. 
I do not use the instructions from Dave and not his picker. The reason is that when I add citation through Dave's picker it shows it like this @Davis.etal.07.c or test @Davis.etal.07.c, p.6 test. However I want to show it as [@Davis.etal.07.c] or [test @Davis.etal.07.c, p.6 test]. The output of Dave's picker after the compilation is "test Davies et al (2007) p.6 test" while it should be (test Davies et al, 2007, p6 test).

For compilation I use zotxt and the following command 
-F pandoc-zotxt -F pandoc-citeproc --csl=/Users/mijalce/.csl/citation.csl

The content of my script is 

set zotRunning to do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe=probe' 2>/dev/null; exit 0"
if zotRunning is "" then
	display alert "This script will not work unless Zotero is running. Please launch Zotero and try again"
	tell application "Scrivener"
		activate
	end tell
	error number -128
else if zotRunning is "No endpoint found" then
	display alert "This script will not work unless Better BibTeX is installed. Please make sure that Better BibTeX is installed in the running instance of Zotero"
	tell application "Scrivener"
		activate
	end tell
	error number -128
else if zotRunning is "ready" then
	set theReference to do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?keyprefix=%40&citeprefix=%5B&citepostfix=%5D&clipboard=yes format=pandoc' 2>/dev/null; exit 0"
	tell application "Scrivener"
		activate
		repeat until application "Scrivener" is frontmost
		end repeat
		tell application "System Events"
			keystroke theReference
		end tell
	end tell
end if

This script is based on the discussions we had when the picker was developed. 

My apologies, if I messed up with my picker, but it was working fine for long period. 

Thank you and keep the good work!

**Comment by retorquere** [comment]
Not entirely sure where the change could have occurred, but the current pandoc formatter doesn't use any of those parameters, and hasn't in a while. You mean you want to optionally have the brackets added?

**Comment by mijalce** [comment]
Actually, I want the brackets to be always added, by default.

**Comment by retorquere** [comment]
You can give https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.55-circle-2440.xpi a try with the url `http://localhost:23119/better-bibtex/cayw?format=pandoc&brackets=true`; if that's what you want, I can merge & release. But I can't reproduce the other problems. I get all the pre & post & locator stuff here.

**Comment by mijalce** [comment]
this functions perfectly! This is what I want.
Thanks!
