### ISSUE TITLE
No autosynchronization

### ISSUE THREAD

**Issue by Luigistudent** [retorquere/zotero-better-bibtex#496]
Every time I export a collection and click "keep updated", as long as Zotero is open I can see the collection under "Preferences → Better BibTeX → Automatic export"; however, when I restart Zotero, the collection is no longer there so it doesn't synchronize automatically if I add new items.

**Comment by retorquere** [comment]
This is likely the same as #490 -- upgrading should take care of the problem.

**Comment by retorquere** [comment]
Can you confirm this is the case?

**Comment by Luigistudent** [comment]
Yes, it resolved, thank you.
