### ISSUE TITLE
Automatic export configuration dissapears after computer restart 

### ISSUE THREAD

**Issue by Delosari** [retorquere/zotero-better-bibtex#498]
First of all I want to thank the developers for this great plugin which I discovered last week.

I would like to check with you the following issue I have (which my be caused by my installation/set up)

I am using the standalone zotero v4.0.29 version (along with the chrome plugin)  in ubuntu 16.04.

I installed zotero by downloading the tar file and moving the contents to /opt/.

I installed zotero-better-bibtex 1.6.56 dowloading the .xpi file and installing it from the add-ons manager.

I have successfully generated a .bib file which works for my documents but it is not updating properly. I have set the option "on change" but I have noticed that when I restart the computer on the tab "Automatic export" the table is empty.

Do you think there is an issue with the addon being on this root folder not working properly? Which is the standard procedure to force an update on all the .bib files?

**Comment by retorquere** [comment]
There's no developers, there's only me, sorry 😄 .

When you exported the bib file, did you tick the checkbox that says "Keep updated"? It's the ticking of that checkbox that registers a bib file for auto-update. It's only for those that the option "on change" does anything.

Then again, if you say the the automatic exports are not in the table *after restart*, that kind of makes me think they were there previously? In any case, it'd be good to know that for sure first.

**Comment by Delosari** [comment]
Hello Retorquere! In that case thank you very much to you.

It seems it is working perfectly now. (I got the clear cache message twice upon restart). So I am very happy.

Thanks again for your work
