### ISSUE TITLE
No pandoc citation export option

### ISSUE THREAD

**Issue by michaellevy** [retorquere/zotero-better-bibtex#501]
Hey, I'm probably missing something silly here, but I just installed BBT (1.6.56), and I don't have any pandoc export options. I do have a bunch of "better bib..." options. Thanks.

**Comment by retorquere** [comment]
You're looking for either "Better CSL JSON", which replaced "Pandoc JSON", or "Better BibTeX Quick Copy", which replaced "Pandoc Citations". I've updated the docs, they didn't reflect these changes yet.

**Comment by michaellevy** [comment]
Awesome, thanks!
