### ISSUE TITLE
Citekey search on Zotero search box

### ISSUE THREAD

**Issue by eds89** [retorquere/zotero-better-bibtex#502]
Hi,
Would it be possible to include citekey search within the Zotero search box? That is, in a transparent way? For instance: while searching for 'title, abstract and author', also search for citekey.

I think this feature would be useful.

**Comment by retorquere** [comment]
I'm not saying it cannot be done, but it's not easy. I have a few crazy weeks ahead, but then I'll have a look.

**Comment by eds89** [comment]
Hi Retorquere,

Just checking if you've been able to add this feature to Better BibTex?

Best wishes.

**Comment by retorquere** [comment]
There's a version you could test at https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.70-circle-2646.xpi ... it's not a perfect solution (saved searches that use subsearches might include items which ought to be excluded) but for quicksearches it ought to work... Zotero has no integration points for this so I had to come up with something slightly hackish.

**Comment by retorquere** [comment]
Is this still of interest?

**Comment by mijalce** [comment]
for me, yes!

**Comment by retorquere** [comment]
Could you test whether it works to your satisfaction?

**Comment by mijalce** [comment]
I am using version 1.6.72. In this version it does not work. How should I update?

**Comment by retorquere** [comment]
Install https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.72-circle-2809.xpi. This is a version that will go out in the next few days, but has the citekey search added. Once the new version drops, it's version will be higher, and you'll upgrade automatically.

**Comment by eds89** [comment]
I'll do it soon.

**Comment by mijalce** [comment]
it works! You need to select "All fields and tags" and it finds it. It works even if you search with only part of the Citation Key. Excellent!
Thanks!

**Comment by retorquere** [comment]
Super, thanks for the confirmation (and yes, you need to select "all fields and tags"). I'll merge to master and will cut a new release.
