### ISSUE TITLE
Authors with a single name are exported with a comma inside the value.

### ISSUE THREAD

**Issue by JohnLukeBentley** [retorquere/zotero-better-bibtex#504]
Steps to reproduce:

In Zotero Standalone, with zotero-better-bibtex installed:

*  Create an entry:

    Item Type: Book
    Title: Republic
    Author: Plato
    Date: 0380 

* Tools Preferences > Export > Default Output Format: Better BibLaTex.
* Select your Plato entry.
* Press Ctrl + Shift+ C.
* Paste your clipboard into a bib file (or any plain text file).
* Observe the result (my custom key may not match yours, so ignore the key).

		@book{plato_380_republic,
			title = {Republic},
			timestamp = {2016-05-28T01:13:38Z},
			author = {Plato,},
			date = {0380}
		}

	In particular observe the extra comma in 
	
		`author = {Plato,},`
	
	It should be
	
		`author = {Plato},`

With the extra common errors compiling the *.bib produces these warnings ....

> WARN - BibTeX subsystem: warning: comma(s) at end of name (removing)
> WARN - BibTeX subsystem: author, warning: comma(s) at end of name (removing)

Changing the `Default Output Format` to `BibLaTex`, thereby invoking the native exporter, avoids this problem.

Zotero Better Bib(La)Tex Version: 1.6.59
Zotero Standalone Version: 4.0.29.10

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.59-circle-2509.xpi ?

**Comment by JohnLukeBentley** [comment]
That solves it and passes my tests. Outstanding! Thanks.

Can I assume "Protocol in case of clash between shared collection citation keys and other keys? #505" is more of a note to yourself that this single name extra comma bug may have had an impact on the request (in #505) to avoid key clashes with respect to shared collections. I mean, would you like me to examine #505 in detail?

**Comment by retorquere** [comment]
Thanks for the confirmation. No, no need to look at #505, the link is just
there because I mentioned I'm going to cut a new release once I get
confirmation on both this and #505. No connection between these two issues
beyond that.
