### ISSUE TITLE
Protocol in case of clash between shared collection citation keys and other keys?

### ISSUE THREAD

**Issue by madhusudansingh** [retorquere/zotero-better-bibtex#505]
This is not so much as an issue, but a realization of a pitfall, that may need some fixes.

Consider the following scenario:

I have a student, A, with whom I have shared a Zotero shared collection. He and I add journal articles etc. to it so that we can read them, and when it comes to writing papers, we can have the same collection to work off.

Imagine the following:

My collection (these are dummy citations - showing citation keys):

Messina, K., et al., J. Non Cryst. Solids, 99(4):3128-3134, 2010 (Messina:2010a)
Messina, A. N.., et al., J. Biomed. , 19(7):20-26, 2015 (Messina:2015a)

(All my citations in my Zotero collections are cumulatively exported to the same large file. I have like 40 collections, and can't be bothered to do separate \addbibresource calls in the markup.)

A's Zotero collection does not have any authors named Messina, but he finds the following publication he needs to cite in a manuscript we are preparing, and he adds it to the shared collection:

Messina, J., Appl. Phys. Lett., 98(4):1209-1212, 2010

This item in his collection naturally gets the citation key (Messina:2010a) and in the shared collection gets the same entry.

Now, as long as all manuscripts are with A as a co-author, I am ok. But when I want to work on a single author review artlcle, and add two \addbibresource calls - one for my giant file, and another for the shared collection with A, I have a problem. If I wanted to cite the article that my student sent, I would have two citation keys floating around with the same key index.

Now, one can say - copy the citation over from the shared collection and put it in this paper. Or better, each manuscript should have its independent shared collection. However, unless you are rolling your own Zotero server, shared collections eat up the fixed amount of disk space quickly.

Would it be a good idea for better biblatex to prepend the name of the collection to the citation key?

So,

Messina, J., Appl. Phys. Lett., 98(4):1209-1212, 2010 would have Acollection:Messina:2010a. Unwieldy, but rules out potential disasters.

**Comment by retorquere** [comment]
When you say collection, you mean group library, correct?

**Comment by retorquere** [comment]
If you do mean group library, you can give https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.59-circle-2507.xpi a go; it adds `[library]` as a pattern option. If this is what you want, I can merge it into a release.

**Comment by retorquere** [comment]
I'm re-reading your initial question, and I'm a little confused now.

On the one hand, it sounds like you're using shared groups when you say "I have shared a Zotero shared collection". The only way I know of that you can do this is either account sharing, or using Zotero groups. the `[library]` pattern should do what you want in the latter case. Using something like `[library:postfix,\:][auth:postfix,\:][year]` would get you `Messina:2010a` for your personal library, and `Acollection:Messina:2010a` for the same reference in a group library named `Acollection`. Or something like `[library:(madhusudansingh)]:[auth:postfix,\:][year]` if you want `madhusudansingh:Messina:2010a` for your own library.

On the other, you say "All my citations in my Zotero collections are cumulatively exported to the same large file", and this only works for things in a single library, not across libraries/groups. So that suggests that you share an account with someone, and agree to work in a specific collection within that library, and that you want the name of that collection in the citation key.

The latter is not possible. Citation keys are bound to the reference, and a reference can be in any number of collections, including none. That would mean a reference would have to vary its citation key depending from which point the export was started. Not only would this be a major change in the internal workings of BBT, but Zotero doesn't hand information on this point of export to the export translators.

**Comment by madhusudansingh** [comment]
Abuse of terminology on my part. I apologize.

Shared collections are group libraries. The [library] tag will do nicely.
Isn't it in the latest release (I had an auto-update only yesterday)?

**Comment by retorquere** [comment]
It isn't yet, no. If you could verify it works to your satisfaction (after
installing the version from that link), I release that as an official
version.

**Comment by madhusudansingh** [comment]
Would love to. Can you add a configuration choice that makes it the default behaviour for all Group Libraries for a person? Namely, I could still enter [author]:[year] as my format, but it would treat that as [library]:[author]:[year] by default. The reason for this request is that this would save a ton of work for me to explicitly set it, and then, in turn to request all my students to do it one by one for theirs. 

One question: how would [library]:[author]:[year] affect exports from My Library (non shared)? I hope that the library string would default to blank in that case.

**Comment by retorquere** [comment]
> Can you add a configuration choice that makes it the default behaviour for all Group Libraries for a person? Namely, I could still enter [author]:[year] as my format, but it would treat that as [library]:[author]:[year] by default. The reason for this request is that this would save a ton of work for me to explicitly set it, and then, in turn to request all my students to do it one by one for theirs. 

I could, but I don't think I will want to. The preference would really amount to something like "always prepend `[library:postfix,\:]` if on". All students would still have to make sure that their cite key pattern is the `[author]:[year]` that, and would also have to make sure the preference is on. I don't think this is relevantly different from instructing the students to make sure the pattern is `library:postfix,\:][auth:postfix,\:][year]` -- in fact, it seems like a simpler instruction. There's really not any effort spared or risk mitigated.

On top of that, prepending this particular pattern is a little arbitrary, and I just know others will want to have a different leader, or postfix, or separator.

If you mean you already have a substantial number of pinned citekeys, all this won't work, but the whole idea of pinned citekeys is that they override the key generation of BBT. This is unfortunately also not doable with a [Postscript](https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting-examples), as Zotero does not make the library name or ID available during export.

> One question: how would [library]:[author]:[year] affect exports from My Library (non shared)? I hope that the library string would default to blank in that case.

The `[library]` part will be blank for My Library, but with this pattern you'd always get a leading `:` in My Library, as parts not between `[...]` are fixed text that is always included. `[library:postfix,\:]` means "library name, and add a `:` if the name is not empty".

If this sounds like what you want, and you could verify using the pre-release at https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.59-circle-2507.xpi, I can get it into the next release. You're right that you just saw a release -- I don't really pool fixes and enhancements into releases, I usually work on the issues that are on the issue list and release when I have them done and confirmed. In this case, I'll probably release together with #504 somewhere today or tomorrow.

**Comment by retorquere** [comment]
I'm going to cut a new release, and I'd like to include this change if you are satisfied. Can you confirm that this does what you want?

**Comment by retorquere** [comment]
So....

**Comment by retorquere** [comment]
Still interested?

**Comment by madhusudansingh** [comment]
Sorry. It has been a crazy day at work. This works. Thanks!!

**Comment by retorquere** [comment]
OK, it'll be in the next release.
