### ISSUE TITLE
"Citation key rescan after upgrade" message

### ISSUE THREAD

**Issue by pprw** [retorquere/zotero-better-bibtex#506]
For a few days, I have the two following messages related to BBT showing at every launch of Firefox. They appears on my Firefox homepage.

![capture d ecran_2016-05-29_22-01-12](https://cloud.githubusercontent.com/assets/5262986/15635795/372ea26a-25e9-11e6-9418-498c9c68082a.png)

Is it normal? If yes, how can I disable these warnings?

Firefox 46.0.1
BBT 1.6.59

**Comment by retorquere** [comment]
That's absolutely not normal. There have been a few releases in rapid succession in the past week, but that should not cause these to be shown at every launch.

Can you go into the zotero gear menu and select "Send Better BibTeX Error"? After clicking through, you'll get an ID in red, if you post that here I can investigate.

**Comment by retorquere** [comment]
NM, I have it reproducible, on it.

**Comment by retorquere** [comment]
Can you try this one: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.59-circle-2512.xpi ?

**Comment by pprw** [comment]
Seems to fix it! No more message !

Thank you for the quick fix.
