### ISSUE TITLE
Repeatedly asks to clear cache on launch

### ISSUE THREAD

**Issue by jarmitage** [retorquere/zotero-better-bibtex#507]
As of recently I get this message every time I launch Zotero. I take the recommended option and a notification says that the new cache has been built, but the same window appears next time I launch.

![2016-05-30 at 10 27 29](https://cloud.githubusercontent.com/assets/2885827/15645626/799e46b0-2651-11e6-952f-a2edbe08b5d0.png)

**Comment by retorquere** [comment]
I've just released a new version; your problem is caused by the same problem that was reported in #506. An upgrade to .60 should take care of the problem. Please do let me know if that is the case; if not, I need to look into your problem further.

**Comment by jarmitage** [comment]
I just updated and the window is now not appearing. It seems to be ok so I will close the issue. Thanks
