### ISSUE TITLE
Mantain JabRef group structure when importing BibTeX db (again)

### ISSUE THREAD

**Issue by framecurrent** [retorquere/zotero-better-bibtex#508]
This is the same issue as dealt with in issue #97. It seems however as the group import feature is broken since then. Also tested with the same example as in issue #97. Any workaround?

JabRef version 2.9
Zotero version 4.0.29.5 (OSX)
zotero-better-bibtex version 1.6.59

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.60-circle-2516.xpi ?

**Comment by framecurrent** [comment]
Works fine. Thanks!
