### ISSUE TITLE
Add-on instalation failed

### ISSUE THREAD

**Issue by quctex** [retorquere/zotero-better-bibtex#509]
Add-on instalation failed with message:

> The add-on "%S" could not be installed. It may be incompitable with this version of Zotero Standalone

Installation according instruction https://github.com/retorquere/zotero-better-bibtex/wiki/Installation.

zotero-better-bibtex-1.6.60.xpi
Zotero Standalone 4.0.29.10
Windows 7 x64

**Comment by retorquere** [comment]
I've just done a fresh install of ZSA 4.0.29.10 with BBT 1.6.60, on Win10 x64, I can't reproduce yet.At what stage exactly do you get this message?

**Comment by quctex** [comment]
After stage 4 in this [instruction](https://github.com/retorquere/zotero-better-bibtex/wiki/Installation), the 'open file dialog' be closed, and errorr message popups.

**Comment by retorquere** [comment]
I pass that stage without errors. I'll talk to the Zotero guys.

**Comment by quctex** [comment]
I solve the problem, my bad, sorry please. Suddenly, when I download xpi file by firefox, it consist of 

> <html><body>You are being <a href="https://github-clou...... et 

but not real file. I try download with download manager program, and now all right. My first issue ever, what a shame...

**Comment by retorquere** [comment]
Oh, right, the downloads do redirects. Does this resolve your question?

**Comment by quctex** [comment]
Yes.
