### ISSUE TITLE
Database updates every minute

### ISSUE THREAD

**Issue by villeneuved** [retorquere/zotero-better-bibtex#510]
The files betterbibtex-lokijs.sqlite and betterbibtex-lokijs.sqlite-journal are updated every minute, even when Zotero Standalone is idle.  I use Sugarsync to backup my files.  This means that Sugarsync is almost continually writing the sqlite files to the cloud.  Zotero.sqlite also updates even when idle, but only every hour or so.  Is the frequent updating necessary?  BBT version 1.6.60.

**Comment by retorquere** [comment]
Can you see if https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.60-circle-2522.xpi behaves better?

**Comment by villeneuved** [comment]
That seems to have fixed it.  betterbitex-lokijs.sqlite is now written once when Zotero Standalone starts, and subsequently only when I do something in Zotero, such as exporting a collection to Bibtex.

Thank you for your quick response.
