### ISSUE TITLE
Export to Biblatex/Bibtex. Custom field order.

### ISSUE THREAD

**Issue by JohnLukeBentley** [retorquere/zotero-better-bibtex#512]
I recently suggested https://forums.zotero.org/discussion/59674/export-to-biblatexbiber-and-others-custom-field-order/

It would be nice to have this functionality at the Better Bib(La)Tex level.

**Comment by retorquere** [comment]
You can already do this with a [postscript](https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting-examples):

```
// the bib(la)tex fields ordered according to this array.
// If a field is not in this list, it will show up at the end in random order.
var order = ['title', 'author'];
this.fields.sort(function(a, b) { return order.indexOf(a.name) - order.indexOf(b.name); });
```

**Comment by retorquere** [comment]
I think this is the best I can do for this request.

**Comment by JohnLukeBentley** [comment]
Looks awesome. I'll look into it and close the thread if there's no further comment to make. Thanks very much.

**Comment by JohnLukeBentley** [comment]
With

```
// the bib(la)tex fields are ordered according to this array.
// If a field is not in this list, it will show up at the end in random order.
var order = ['author', 'date', 'title', 'publisher'];
this.fields.sort(function(a, b) { return  order.indexOf(a.name) - order.indexOf(b.name) });
```

I get

```
@book{nietzsche_1974_gay,
  edition = {1},
  isbn = {0-394-71985-9},
  shorttitle = {The {{Gay Science}}},
  abstract = {Nietzsche called The Gay Science "the most personal of all my books." It was here that he first proclaimed the death of God -- to which a large part of the book is devoted -- and his doctrine of the eternal recurrence.  Walter Kaufmann's commentary, with its many quotations from previously untranslated letters, brings to life Nietzsche as a human being and illuminates his philosophy. The book contains some of Nietzsche's most sustained discussions of art and morality, knowledge and truth, the intellectual conscience and the origin of logic.  Most of the book was written just before Thus Spoke Zarathustra, the last part five years later, after Beyond Good and Evil. We encounter Zarathustra in these pages as well as many of Nietzsche's most interesting philosophical ideas and the largest collection of his own poetry that he himself ever published.  Walter Kaufmann's English versions of Nietzsche represent one of the major translation enterprises of our time. He is the first philosopher to have translated Nietzsche's major works, and never before has a single translator given us so much of Nietzsche.},
  pagetotal = {407},
  timestamp = {2016-05-24T03:08:22Z},
  langid = {english},
  translator = {Kaufmann, Walter},
  keywords = {Philosophy / General,Philosophy / History & Surveys / Modern},
  origdate = {1882},
  shorthand = {GS},
  author = {Nietzsche, Friedrich Wilhelm},
  date = {1974-03},
  title = {The {{Gay Science}}: {{With}} a {{Prelude}} in {{Rhymes}} and an {{Appendix}} of {{Songs}}},
  publisher = {{Random House}}
}
```

The ordering is right, but the ordered fields are placed at the end of the non specified fields. Any trivial postscript to make the specified fields start at the top?

**Comment by retorquere** [comment]
Ah, yes, sorry:

```
var order = ['title', 'author'];
this.fields.sort(function(a, b) { return ((order.indexOf(a.name) + 1) || order.length) - ((order.indexOf(b.name) + 1) || order.length); });
```

**Comment by JohnLukeBentley** [comment]
Thanks. Better. But with

```
var order = ['author', 'date', 'title', 'publisher'];
```
I get

```
@book{russell_1914_oura,
  author = {Russell, Bertrand},
  date = {1914},
  title = {Our {{Knowledge}} of the {{External World}}},
  location = {{Chicago}},
  timestamp = {2016-06-05T18:51:06Z},
  publisher = {{The Open Court Publishing Company}},
  shorthand = {KEW}
}
```

That is, `author`, `date`, and `title` OK. `publisher` out of sequence.

**Comment by retorquere** [comment]
off by one error on my part:

```
var order = ['author', 'date', 'title', 'publisher'];
this.fields.sort(function(a, b) {
  return ((order.indexOf(a.name) + 1) || (order.length + 1)) - ((order.indexOf(b.name) + 1) || (order.length + 1));
});
```

or if you like clear code over compact code:

```
this.fields.sort(function(a, b) {
  var oa = order.indexOf(a.name);
  var ob = order.indexOf(b.name);
  if (oa < 0) { return 1; } // a is not in order, so put it at the end
  if (ob < 0) { return -1; } // b is not in order, so put it at the end
  return oa - ob;
});
```

the compact sample relies on a few (stable) javascript quirks that may not be immediately obvious:

1. indexOf returns `-1` if it can't find the object you're looking for
2. in Javascript, `undefined`, `false`, `null`, an empty string and `0` all behave falsish (that is, if you use it in a condition that expects a boolean value, all of these are treated as if they're false)
3. The `||` operator doesn't return a boolean value, but returns the first non-falsish value (so `null || undefined || false || "" || 0 || 'x' || 3.14` will return 'x')
4. in the sort function, a return value of `0` means the comparitives are equal, any value lower than zero means a < b, and any value greater than zero means a > b (most examples will use -1, 0, 1, but they don't need to be)

so in the compact example, I add one to the indexOf result so `not found` (-1) becomes falsish, and if it's falsish, I use order.length + 1, which equates to "just past the last element of order". The reason publisher was out of order is because it got assigned 4 just like any non-found field when I used just order.length, and those are all treated as equal; that it ended up where it did was essentially random.

**Comment by JohnLukeBentley** [comment]
Thanks. I tested the "clear code" form and it passes a handful of testing.

Thanks also for the detailed javascript explanation. I should have the relevant Javascript knowledge to have worked this out myself. However,

* I'm rusty
* My brain is foggy today,
* What you are doing is clever coding anyway,
* I felt better with you looking into it should there be some kind of interaction issue between postscript code and your code base.

... I just mean to express my deep gratitude for your putting in the work. This is another great piece of functionality from your Add-in.

**Comment by retorquere** [comment]
Oh, no worries. I don't expect any BBT user to have or want javascript knowledge. I just needed a break and my way of taking breaks is usually writing code. The postscript facility is there more for my benefit than anyone elses; it means that I have a way to resist jumping into each and every one request with a new preference pane.

There's really nothing you can screw up in a postscript. It runs in the Zotero translator sandbox, and if you change the postscript, the cache is dropped, to it'll generate everything afresh.

**Comment by alekhe** [comment]
Hi, there. Can I reopen this one?
I tried to use this code
> ```
> var order = ['author', 'date', 'title', 'publisher'];
> this.fields.sort(function(a, b) {
>   return ((order.indexOf(a.name) + 1) || (order.length + 1)) - ((order.indexOf(b.name) + 1) || (order.length + 1));
> });
> ```
But it seems like it does nothing. Has something changed in the API?

**Comment by retorquere** [comment]
Can you right-click a reference where this fails and submit a bbt error report?

**Comment by alekhe** [comment]
> Can you right-click a reference where this fails and submit a bbt error report?

E.g.: USJZ6STY-euc

**Comment by retorquere** [comment]
I had forgotten I had changed this -- `this.fields` no longer exists. Instead there's `this.has`, but it's an object, not an array -- this should work:

```
var order = ['author', 'date', 'title', 'publisher'];

// as javascript enumerates properties in the order they were added since ES6, deleting and re-adding a property effectively moves it to the end.
function moveToEnd(obj, field) {
  const value = obj[field]
  delete obj[field]
  obj[field] = value
}

// first, push all the ordered fields to the end in the desired order
// reversing the order because we're going to reorder fields by pushing them to the end in the right order
for (const field of order.reverse()) {
  if (typeof this.has[field] !== 'undefined') moveToEnd(this.has, field)
}
// then, move all non-ordered fields to the end
for (const field in this.has) {
  if (!order.includes(field)) moveToEnd(this.has, field)
}
```

**Comment by retorquere** [comment]
Come to think of it, this would achieve the same and is easier to read:

```
// strip out author, date, title, publisher and remember the rest
const { author, date, title, publisher, ...rest } = this.has

// re-create this.has with the properties in the desired order, and add the rest
this.has = { author, date, title, publisher, ...rest }

// strip out empty fields we might have added when one of the non-rest properties does not exist
Object.keys(this.has).forEach(key => this.has[key] === undefined && delete this.has[key])
```

Mind that this will only work for the TeX translators, not the CSL translators that are also bundled, so whichever way you choose, you might want to make sure it's only ran there:

```
if (Translator.BetterTeX) { // covers both Translator.BetterBibTeX and Translator.BetterBibLaTeX
  const { author, date, title, publisher, ...rest } = this.has
  this.has = { author, date, title, publisher, ...rest }
  Object.keys(this.has).forEach(key => this.has[key] === undefined && delete this.has[key])
}
```

**Comment by alekhe** [comment]
The first variant works fine. Except that you don’t need to reverse the order — they will be added in the correct one.

For the second one I get a syntax error—I don’t understand what `...rest` is. Should I enumerate all the fields? Or, is that a syntax structure for all other fields?

**Comment by retorquere** [comment]
Right of course, no reverse needed.

The second version turns out only works in the newest javascript -- I mostly use typescript and that supports it but I had forgotten it would compile that down to something that works, but is really not pretty to look at. Forget the 2nd version.

**Comment by alekhe** [comment]
OK, understood. Thanks for the help.

**Comment by retorquere** [comment]
A little more compact:

```
const order = ['author', 'date', 'title', 'publisher'];
const keys = Object.keys(this.has)
for (const field of keys.sort((a, b) => ((order.indexOf(a) + 1) || (keys.length + 1)) - ((order.indexOf(b) + 1) || (keys.length + 1)))) {
  const value = this.has[field]
  delete this.has[field]
  this.has[field] = value
}
```

**Comment by alekhe** [comment]
Thanks for the improvement. Just needed to change `(keys.length + 1)` to `(keys.length + order.length + 1)` since I created a quite lengthy order list and it sorted incorrectly for items with few fields.

**Comment by retorquere** [comment]
That's correct -- my sample assumed the order list would always be shorter than the key list, yours fixes that.
