### ISSUE TITLE
Citation key generation bug. Phantom "a" appended to key.

### ISSUE THREAD

**Issue by JohnLukeBentley** [retorquere/zotero-better-bibtex#513]
I've just done a complete reinstall of Zotero (4.0.29.10) and zotero-better-bibtex (1.6.61) for reasons I don't need to mention.

I'm using zotero-better-bibtex to generate citation keys. Zotero > Preferences > Better Bib > Citation Keys:

`Citation Key Format: [Auth:condense,_:lower]_[year]_[veryshorttitle:lower]`

The resulting citation is constructed as expected, except with a phantom "a" appended to the end. This has occurred for most of my items (which exceeds 20).

Example item (with malformed citation key):

```
@book{plato_2004_republica,
  author = {{Plato}},
  date = {2004-09-15},
  origdate = {-0379},
  title = {Republic},
  publisher = {{Hackett Publishing Company, Inc.}},
  location = {{Indianapolis}},
  edition = {3rd edition},
  isbn = {0-87220-737-4},
  abstract = {This edition includes a select bibliography, a synopsis of each book, a glossary of terms, a glossary and index of names, and a general index.},
  pagetotal = {392},
  timestamp = {2016-06-05T18:52:21Z},
  translator = {Reeve, C. D. C.}
}
```

The phantom "a" doesn't appear to derive from any field.

**Comment by retorquere** [comment]
Have you started with a clean profile, or reused an existing profile?

**Comment by retorquere** [comment]
If you re-used a profile, the old BBT database may still be there, and that will have reserved any previously existing citation keys. If that's the case, try this version:
https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.61-circle-2529.xpi

it will, after an upgrade of BBT (and this version will be considered an upgrade), remove key reservations for non-existent items.

**Comment by JohnLukeBentley** [comment]
Fixed. Looks like it was a corrupted profile.

Before posting the issue I actually thought I had deleted the profile. At something like (on Windows)

    C:\Users\John\AppData\Roaming\Zotero\Zotero\Profiles\for5ipfv.default\zotero

 However, on visiting it again there was two Zotero profiles (a new and old one). So I uninstalled everything, manually deleted `C:\Users\John\AppData\Roaming\Zotero\` (thereby removing all profiles), and reinstalled Zotero and Zotero-Better-Bibtex (BBT).

Everything looks ok now. Sounds like it was down to a corrupted profile, as you suspected. 

I'll therefore hold off upgrading BBT until your next version number increment (or there's another reason to do so).

**Comment by retorquere** [comment]
Ah, shame, I was curious whether the pre-release was going to fix your problem in-place. There was existing code in place to take care of such issues, but apparently it didn't do the job in your case.

With a fully fresh start, the pre-release won't do anything, so there's no need to install it.

Glad you can get back to work in any case.

**Comment by retorquere** [comment]
(the phantom `a` is a key disambiguator in the case of key duplicates BTW, you should only see it if you have genuine key overlap)

**Comment by JohnLukeBentley** [comment]
> There was existing code in place to take care of such issues, but apparently it didn't do the job in your case.

I finished deleting my profiles and reinstalling before seeing your offer of the pre-release :(

Thanks for the info on `a`.

**Comment by JohnLukeBentley** [comment]
Just a tip for those following given @retorquere's ...
> the phantom a is a key disambiguator in the case of key duplicates BTW, you should only see it if you have genuine key overlap

... if you find your citation key getting incremental alphas (e.g. `key`, `keya`, `keyb`, etc.) then go to your root folder in Zotero and delete the duplicates.

**Comment by retorquere** [comment]
Note that this won't necessarily get rid of the disambiguation letter. If
in the merge you pick the reference with `keyb` as the master record to
merge into, whether that results in `key` after the merge depends on
whether Zotero puts the duplicates in the trash after it saves the merged
reference (in which case `key` is free when the reference is saved, so it
will take it) or after it saves the merged reference (in which case the key
won't be free at time of save, so only at the next change does it get the
now-free key)

**Comment by JohnLukeBentley** [comment]
... I should add, then, that you may want to delete the original entry as well as the duplicates, to ensure there is no lock on the key, before re-importing (or retyping) the original entry. 

(Would that be right?).

**Comment by retorquere** [comment]
that would be right, or you could clear the key on the reference, which should cause it to be regenerated.

**Comment by JohnLukeBentley** [comment]
Thank you kindly. I hope the defense of your thesis went well.

**Comment by retorquere** [comment]
Well enough. I think the thesis could have been better had I planned the feedback sessions with my supervisors more strictly (they're not always easy to get a hold of), but I did graduate with honors.

**Comment by JohnLukeBentley** [comment]
Congratulations! 

Of course the subject of your thesis will have supplied you with the virtue of being impervious to all the glories and laurels, such that "honors" are. However, better to be exercising virtue against "honors" than to be exercising virtue against a "fail". :)

**Comment by retorquere** [comment]
And that is the truth. Thanks.
