### ISSUE TITLE
Change format of pull export

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#516]
Wondering if there's any way to get spaces instead of line breaks in the entries of the pull report. I'm trying to process them and it would be easier to handle entries that were one line each.

**Comment by retorquere** [comment]
That's not currently possible, no, but a regex will pick them out:

```ruby
#!/usr/bin/env ruby
open('CAIAH.bib').read.scan(/((^|\n)@.*?\n})/m).each{|ref|
  next if ref[0] =~ /^@comment/
  puts ref[0].strip.gsub("\n", ' ')
}
```

**Comment by Jmuccigr** [comment]
Yeah, I'm currently handling it with some `grep` and `sed`.

Another thing that has come up for me is that inside `file` multiple files don't get their own lines. If that's not doable either, feel free to close.

**Comment by retorquere** [comment]
Is having multiple file fields compatible with Jabref? I took the file field encoding from there.

**Comment by Jmuccigr** [comment]
About the only thing I can find on the internal format of the .bib file is [this](http://nwalsh.com/tex/texhelp/bibtx-6.html), and it doesn't really address the file field, probably because that's not a standard field.

But I wasn't thinking of multiple fields, just having a line break in between the different files (also not addressed on that page):

`
file = {Yoffe - 2015 - A Campus Rape Ruling, Reversed.html:/Users/user/Documents/Zotero data/storage/3JXSQ8Q8/Yoffe - 2015 - A Campus Rape Ruling, Reversed.html:;

Yoffe - 2015 - A Campus Rape Ruling, Reversed.pdf:/Users/user/Documents/Zotero data/storage/5T8A2NZ4/Yoffe - 2015 - A Campus Rape Ruling, Reversed.pdf:application/pdf}
`

instead of

`
file = {Yoffe - 2015 - A Campus Rape Ruling, Reversed.html:/Users/user/Documents/Zotero data/storage/3JXSQ8Q8/Yoffe - 2015 - A Campus Rape Ruling, Reversed.html:;Yoffe - 2015 - A Campus Rape Ruling, Reversed.pdf:/Users/user/Documents/Zotero data/storage/5T8A2NZ4/Yoffe - 2015 - A Campus Rape Ruling, Reversed.pdf:application/pdf}
`

with an extra line in that first example for effect.

**Comment by Jmuccigr** [comment]
Upon a regular Zotero export to bibtex, there isn't anything after that semicolon. However, I think I just confirmed a bug:

In the entry above, the html file has no filetype, where it should be `text/html` after the colon and before the semicolon. Zotero's usual method includes it.

**Comment by retorquere** [comment]
can you right-click that reference and select "send better bibtex report"? If you post the resulting ID here, I can investigate.

I don't understand "there isn't anything after that semicolon"?

**Comment by Jmuccigr** [comment]
ID: E753Z86E

Though none of the html attachments get reported with a filetype, it appears from running this:

`curl -s -stdout 'http://localhost:23119/better-bibtex/library?library.biblatex' | grep text/html`

What I meant was that the two file refs are separated by a semicolon and not by anything else, like a line break. Both your export and Zotero's do that same thing.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.64-circle-2543.xpi ? That should fix the latter problem.

**Comment by retorquere** [comment]
I'm not diametrically opposed to adding a line break, but breaking jabref
compatibility would be undesirable. I just don't know what jabref would do
with the linebreak. It doesn't export it itself, and jabref doesn't have a
formal spec, so I'm loathe to go beyond it. Perhaps you could check with
the jabref devs to see what their take on this is?

**Comment by Jmuccigr** [comment]
Yep, that seems to do it. Now all the files in my library have filetypes in the export. Thanks!

I'll have a look into the other item.
