### ISSUE TITLE
Book section url not exported

### ISSUE THREAD

**Issue by xracoonx** [retorquere/zotero-better-bibtex#517]
I have a book section that contains an url field. The url field shows up fine in zotero but is missing in the better bibtex exported bib file. What can I do?

better bibtex exports the "urldate" just fine but misses to export the url field.

**Comment by retorquere** [comment]
Is this for BibTeX or BibLaTeX? BibTeX doesn't have url support, so if you want them regardless, you can enable it in the "Export" tab of the BBT preferences.

**Comment by xracoonx** [comment]
Great, Thanks! I am actually using BibLaTeX. So I changed the export from BibTeX to BibLaTeX and everything works just fine.
