### ISSUE TITLE
Add more fields to Better CSL JSON export

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#518]
A request:

It would be convenient if the json output in this mode could contain, perhaps as an option, more fields than csl recognizes. For example, the files attached to an entry. (OK, this is really the only one I care about right now.)

These should be ignored by anything reading the json and so shouldn't cause any problems. OTOH, if they were there (as they are in other formats, like bibtex), they could be used (and I have a use-case in mind, of course).

I tested the effect of this by adding a file field and processing the json with pandoc. No harm done. See the final comments on [this Zotero forum thread](https://forums.zotero.org/discussion/35451/exporting-to-csl-json-results-in-loss-of-fields/#Comment_255706).

**Comment by retorquere** [comment]
@fbennet, any thoughts on this? If I add a field "attachments", can I count on citeproc ignoring this?

**Comment by retorquere** [comment]
BTW, if you're just looking at an easy-to-process format that has everything of the reference, BetterBibTeX JSON (the bbt debug format) does that. I see zotero rdf mentioned in that thread, but ZRDF doesn't roundtrip well.

**Comment by Jmuccigr** [comment]
I use the CSL because my main workflow involves pandoc and that works best (I'm told). I don't need the file refs for pandoc though.

pandoc-citeproc seems to ignore it, btw, based on my testing.

PS I'd call it "file" to match what bibtex outputs.

**Comment by retorquere** [comment]
I'm going to wait to see what @fbennett thinks of this, he's the expert on what CSL will tolerate. This also goes for terminology; CSL is not BibTeX, so I'd rather fall in line what the CSL experts say is appropriate.

**Comment by Jmuccigr** [comment]
Understood.

**Comment by Jmuccigr** [comment]
Further thoughts, @fbennett?

**Comment by retorquere** [comment]
Without feedback from the citeproc crew, I'd really rather not add this and potentially go out of spec. If you find more information on how CSL-JSON can accommodate this, please do re-open. In the meantime, BBT JSON has all the info you need.

**Comment by fbennett** [comment]
Ah, sorry for being bad about responding! It's probably worth running this past the xbiblio-devel list, where CSL developers and the maintenance team hang out. Like pandoc, citeproc-js will just ignore fields that it doesn't know about: the processor does not attempt to validate its input. So it should work okay currently. A slight worry might be that, at some point down the road, CSL might add a field of the same name, and then there would be issues with legacy data.

So as far as citeproc-js is concerned, it's no problem, but best-practice-wise, it would probably be good to run it past the CSL team.

Apologies again for the very late response.

**Comment by retorquere** [comment]
@Jmuccigr, would you do the honors? You should be more capable of expressing the desired result. I'll be happy to implement whatever rolls out.

**Comment by retorquere** [comment]
Closed for inactivity

**Comment by fbennett** [comment]
Sorry! The processor will ignore fields outside of the CSL schema, with the
sole exception of "multi," which is a reserved word in CSL-M.

**Comment by retorquere** [comment]
Oh hi @fbennett - your previous response was sufficient for me, but I was waiting for @jmuccigr to come back with results from the csl group. Without feedback from the csl group I'd be hesitant to make the change, but on a broader principle, if the requesting user isn't around for feedback and testing, I'm blind when it comes to acceptence testing, since it's not a change I'd use personally. That's mostly the reason I close issues for inactivity.

**Comment by Jmuccigr** [comment]
Sorry about the delay. I just havenʻt gotten around to this. I'll try to get it done this week.

**Comment by retorquere** [comment]
Any updates?

**Comment by retorquere** [comment]
So...

**Comment by gleachkr** [comment]
I'd like to see something like this too... Would this be achievable (particularly adding a field with the attached files) using a postscript snippet?

**Comment by retorquere** [comment]
It's not possible now, but it is in principle possible to add it. The problem I need to find a way around is that people have postscripts in the wild, and these were so far only ran on latex-like references, so the code was free to assume only those were being passed. If I now also run the postscript on CSL references, people who export both CSL and LaTeX and have a postscript would start experiencing errors... mostly silently recoverable errors, but I don't like that "mostly" part. Existing postscripts would have to be changed to detect whether the postscript is being ran against a LaTeX or a CSL reference. Or I'd have to add a separate postscript for CSL references. Still pondering this one.

**Comment by retorquere** [comment]
Can you give [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.98-br518-3762.xpi) a try? In the postscript you will have to test for `Translator.BetterCSLJSON`, `Translator.BetterCSLYAML` (or for `Translator.header.label.startsWith('Better CSL')` if you want to catch them both in one go); if true, you can use `reference` (the CSL reference being built) and `item` (the Zotero reference) in your script; any change to `reference` will be in the CSL reference written out.

**Comment by gleachkr** [comment]
Works beautifully. Here's the postscript I used (which may be ill-formed in other ways, but does the job for JSON nicely):

```
switch (Translator.header.label) {
  case 'Better BibLaTeX':
    break;
  case 'Better BibTeX':
    break;
  case 'Better CSL JSON':
       reference.file = item.attachments[0].localPath;
    break;
  case 'Better CSL YAML':
    break;
}
```

**Comment by retorquere** [comment]
I'll merge and cut a new release with this. Note that this postscript will generate an error when you have references without an attachment. BBT ignores postscript errors, so it's unlikely that any damage will result, but still. The error-ignoring is why I'm comfortable doing the csl postscript this way; latex postscripts, even if they don't test which translator they're running under, will reference `this`, which will not exist under the csl processors, so it'll bail before it can do any harm.

**Comment by retorquere** [comment]
OK, merged to master and .99 will be released automatically.
