### ISSUE TITLE
Change definition of "on idle" for export

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#519]
I think I read in #385 that the idle time that will kick off an update of the cache is 10 seconds. When I'm woking on updating my database, such as adding scans of my files, which I tend to do in batches, I easily hit this target and have to wait for Zotero to become responsive again.

My system seems to be a bit slow on stuff like this, but I wonder whether lengthening this time would help. It seems to me that a longer wait won't really matter to anyone who isn't working on multiple entries, but will help those who are.

**Comment by retorquere** [comment]
If you're adding scans, you should not be hitting the idle timeout; according to [the Mozilla docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIIdleService), "The idle service is for computer-wide idle detection, not just application idle detection. In other words, even if the user is working in other applications, the idle service will still consider the user to be active." so whatever you would be doing should prevent the idle timer from triggering.

You can change the wait time however by going into `about:config`, and changing the `autoExportIdleWait` value to something other than the default 10. It will take a restart of Firefox for the value to take hold.

**Comment by Jmuccigr** [comment]
I'm not sure it isn't my system which seems to have some slow disk access at times. I'm on the standalone, but I'll try the change you suggest.

**Comment by retorquere** [comment]
The same change should work on standalone.

**Comment by Jmuccigr** [comment]
Just coming back to this to report that standalone definitely does not adhere to the idle time on my system. Just now I was working on attaching files and it suddenly decided to do an export, which is big enough that Zotero locks up for a noticeable amount of time. There definitely was not a long enough idle time in Zotero, let alone the system.

**Comment by Jmuccigr** [comment]
Another data point on the idle: for some reason my export was 0K, so I made a tiny change in one entry and waited. Nothing. Then I went and clicked on another Zotero entry and the export started.

**Comment by retorquere** [comment]
Can you right-click on any reference and select "send BBT error report"? That will get me your current settings. This one is hard to debug, as I can only wait for Firefox to notify me of idleness. If there's nothing in your settings, I'll have to make a special instrumented build with more logging.

**Comment by Jmuccigr** [comment]
Done. 8H6ITJ6Z

**Comment by retorquere** [comment]
Nothing out of the ordinary there. On idle, after 10 seconds. I'll get you an instrumented build.

**Comment by Jmuccigr** [comment]
Except app.update.idletime is set to 60 in FireFox, as is extensions.zotero.translators.better-bibtex.autoExportIdleWait.

**Comment by retorquere** [comment]
The first is just how long you need to be idle before Firefox will prompt you for an update to Firefox, and the second I can see in your preferences is set to 10 (seconds, that is).

60 seconds would be long (although I know people who have it set to longer on really constrained systems), but it still wouldn't explain the behavior you describe in https://github.com/retorquere/zotero-better-bibtex/issues/519#issuecomment-233096889; that stuff only happens when you click away is sort of explainable -- Zotero doesn't notify extensions of changes until the changed field loses focus, so you need to either click a different field in the same reference or click another reference, but it doesn't explain why the export starts immediately after that when you have on-idle set -- by definition, Firefox isn't idle when you click something.

**Comment by Jmuccigr** [comment]
FireFox says both idles are set to 60, but the Zotero one isn't, according to your report? Or is it another idle that FireFox doesn't show?

On the clicking away thing, I made a change to a field and hit return, so the change was accepted. Then I waited. Then I clicked on another entry to get the export to kick in. I don't think that's quite what you describe, since the changed field should have lost focus with the return, no?

**Comment by retorquere** [comment]
Can you do the following:

1. Turn on extended debugging in the BBT advanced prefs
1. install [this instrumented build](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.70-circle-2645.xpi) and let firefox restart
2. let firefox go idle (so at least 10 seconds do absolutely nothing on the PC -- not just FF needs to sit idle)
3. Submit a BBT error report and post the ID here.

**Comment by Jmuccigr** [comment]
I'll do this, but for the record, I use the standalone, not FireFox. I took reports via both, waiting before each:

From the standalone: D9R6MCJ2
From FireFox: S2GCPNXV

My FireFox Zotero library was way out of date, so I also got that all sync'ed up before running the report.

**Comment by retorquere** [comment]
It doesn't really matter which you use, as standalone is just a stripped-down firefox, but the log made with standalone D9R6MCJ2 was not from the instrumented build. That means I don't know what the actual idle timeout is (the settings I get say 10 seconds, but the instrumented build logs the actual value should that somehow be different), but I do see auto-exports being scheduled (mostly no-ops as there's nothing to do, which seems right as I don't see any other relevant activity in the logs leading up to the attempted scheduling).

Can you install the instrumented build in Firefox, make a change, let it sit idle for two minutes, and then submit a new debug log? Since you are on OSX, don't forget to really quit Firefox after the install; OSX has this annoying habit of keeping programs running even if you close the last window. Saying "Yes" to the "do you want to restart" popup you get after installation will do the job.

**Comment by Jmuccigr** [comment]
Leaving aside the comment about OS X and closed windows, I had installed the plug in in FireFox and then re-started it. I didn't do anything in Zotero, so it's still using the standard plug in (1.6.71). Here's another shot at both (you said the standalone had the old plug in, but asked for FireFox):

Firefox: GBE4WRHP
Standalone: A92NXCAB

Again, FireFox about:config shows the idle times at 60, not 10.

**Comment by retorquere** [comment]
I don't know where the 60 seconds come from -- I can see in the standalone log that the idle scheduler is on a 10 second delay. I'm not disputing that you see 60, but Firefox is handing BBT 10. Can you add a screenshot where you see that 60?

From the firefox log I can't tell yet -- one of your other extensions (jsonview) is interrupting the BBT startup and throws an error midway which prevents BBT from finishing its initialization. I've reported the error to the jsonview dev, but could you temporarily disable it while we figure that problem out?

In your standalone log, I see an idle-triggered export being kicked off for /Users/john_muccigrosso/Documents/github/local/temples/temple_bib.json and /Users/john_muccigrosso/Documents/github/local/miscellaneous/My Library.json. I see no item changes in that log, so from the logs it looks like they're just triggered from idle.

**Comment by retorquere** [comment]
(the reason why I was specific about restarting Firefox BTW was that the fact that OSX doesn't quit apps when you close the last window still frequently bites me, and I asked for logs from an instrumented build, and there was one log from a release build. I figured the log was just captured after install but before restart)

**Comment by Jmuccigr** [comment]
![screenshot 2016-08-07 19 41 42](https://cloud.githubusercontent.com/assets/615115/17466155/1230f344-5cd7-11e6-8ed7-4447fe48ba75.png)

And I've got jsonview turned off now. Want a new error report?

**Comment by retorquere** [comment]
Sure, lets see what BBT gets handed. You see the same 60 for standalone?

**Comment by Jmuccigr** [comment]
Had to look up how to get the value for standalone. It's 10, not 60. I misunderstood your comment back on June 16 to mean that the change in FireFox would also affect the standalone, not that the standalone needed to have its value changed separately. I didn't even realize that the standalone had an about:config window.

So, with a new value of 60 in the standalone, here's the error report: 77AIDQJI

**Comment by retorquere** [comment]
I can see it going idle (and that it's now on a 60 second delay), but it thinks it has nothing to do ("no pending jobs"). I also see no reference changes, so perhaps there really isn't anything to do? I do see a translation happening for the BetterBibTeX JSON format, but it doesn't appear to have been kicked off by the idle scheduler. Was that a manual export? Or a pull export?

Which is your main Zotero client BTW, standalone or Firefox? For debugging purposes I'd prefer to stick to one for the time being -- if I diagnose the problem we can always still see if it affects the other differently. Which shouldn't be the case, but it has happened before.

To get back to your original report, which was based on standalone I think, you found that Zotero was kicking off exports even when you has set it on idle, but while you were adding scans. Can you reproduce that still? The log file for that should show activity on the references for your work on the attachments, and it will have logging on the auto-exports. It would give me an idea in what order things were happening.

**Comment by Jmuccigr** [comment]
I'll see what I can do. It correctly knew that it had nothing to do. I'll make some changes and see when it kicks it. It locks up Zotero and takes long enough that I notice. And yes, standalone is my go-to. I don't use Firefox normally.

**Comment by Jmuccigr** [comment]
I had to delete an entry, so the library was re-exported. Here's the report: W3P8HG95

**Comment by Jmuccigr** [comment]
For completeness, here's one from right after I opened the standalone and cleared the cache after getting the warning to do. It took 5 minutes: AGCHANEQ

**Comment by retorquere** [comment]
So here's what I think the log says (all times relative to the time the log started):

* 00:03:22: non-scheduled export
* 12:54:53: idle scheduler wakes up, but nothing to do. If I'm reading the logs right, your system didn't fall idle for nearly 13 hours. This is followed by a few more wakeups with nothing to do
* 15:22:19: item 15801 changed, no export as it sees the setting is on-idle, not on-change
* 15:22:48: item 3738 changed, no export as it sees the setting is on-idle, not on-change
* 15:22:48: item 3738 trashed, no export as it sees the setting is on-idle, not on-change
* 15:22:55: items 16240 and 15801 changed, no export as it sees the setting is on-idle, not on-change
* 15:22:56: items 15801 and 16240 changed, no export as it sees the setting is on-idle, not on-change (the order of the rest of the parameters makes me think this and the one above is the putting in place of an attachment maybe? All the changes above seem to affect an item with citekey "New2016")
* 15:24:01: the idle scheduler wakes up and finds it has work: a search (which is relatively expensive to export BTW), and the full library)
* 15:28:49: a new export is started, but not by the scheduler.

So the activity of the idle scheduler seems to be OK, there's really 3 things I can't explain:

1. The first export at 00:03:22
2. The last export at 15:28:49
3. How you managed to get a log for 15+ hours in 6 hours

I'm building a new instrumented build that puts absolute timestamps in the log

EDIT: just noticed your additional comment. For these tests, you don't have to reset the cache. A cache reset will always cause all auto-exports to be rescheduled, as the assumption is that something must have changed in the output generated by BBT you want to have reflected in the exports.

**Comment by retorquere** [comment]
New build at https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.71-circle-2651.xpi to make more sense of the log timestamps.

**Comment by Jmuccigr** [comment]
I'll try the new one.

The system wasn't idea for that long, but Zotero may not have been running.

Yes, I added some attachments.

Interestingly the file modification time is 15:23, not 15:28. I was watching and saw the new file get created at 15:18 and the export finish at 15:23. In fact the computer went to sleep at 15:28. Could be that you're just off by 5 minutes on the whole thing.

FYI the search export is pretty short, about 6 items or so.

**Comment by Jmuccigr** [comment]
Did you see this, @retorquere ?

**Comment by retorquere** [comment]
Ah, the debug log? No, I didn't, I don't get notifications for edits, I'll go check.

**Comment by retorquere** [comment]
In this log I idle exports being scheduled on a 60 second delay, and I see an auto-export being kicked off at Mon Aug 08 2016 16:41:39 after what does appear to be sufficient idle time. There wasn't a change to a reference that caused the auto-export to be scheduled, but a change of the installed BBT version (and all these debug versions have their own version ID) schedules all auto-exports anew. So in this log, I see nothing out of the ordinary.

**Comment by Jmuccigr** [comment]
I'll post something when I have an unusual experience.

**Comment by retorquere** [comment]
Please re-open the issue (or file a new one) if the problem re-appears.
