### ISSUE TITLE
Possible bug when exporting

### ISSUE THREAD

**Issue by dinisov** [retorquere/zotero-better-bibtex#520]
Hello,

When exporting with either better bibtex or better biblatex the journal name in the resulting .bib is sometimes is not inside curly brackets. This then generates errors when compiling or the sort `string "blah blah blah" undefined' and it won't add the name of the journal to the reference.

It didn't work for the journal names `Neurology' and `Neuropsychologia', but it works for everything else apparently. Something with the use of `Neuro' in the name? Weird...

Dinis

**Comment by gracile-fr** [comment]
More details are probably needed: https://github.com/retorquere/zotero-better-bibtex/wiki/Support

**Comment by retorquere** [comment]
Do you perhaps have "Assume single-word strings" on? Try unchecking that.

**Comment by dinisov** [comment]
Zotero standalone running in Ubuntu linux 14.40.

Better bibtex v1.6.65

I can't think of anything else.

**Comment by dinisov** [comment]
Yep retorquere was right. Problem fixed. Thanks!
