### ISSUE TITLE
Aux scanner does not recognize multiple citations when using the cite package

### ISSUE THREAD

**Issue by bonderado** [retorquere/zotero-better-bibtex#521]
Using multiple keys in a citation  is not recognized.
the command:
\cite{Akey,Bkey,Ckey}
produces  the following in the aux file :
\citation{Akey,Bkey,Ckey}
Apparently, the regular expression in use :
re = /\\citation{([^}]+)}/g
interprets this case as the single citation key "Akey,Bkey,Ckey" that, of course, is not in Zotero and a notice for missing key  is generated, while the actually existing keys Akey, Bkey, Ckey, are not imported .

Steps to reproduce:
1 Create a file main.tex wit hthe following content
(change A_key and B_key to values that exist in your zotero database):

\documentclass{article}
  \usepackage{cite}
\begin{document}
  \cite{A_key,B_key}
\end{document}

2 compile the file
 pdflatex main

3 open zotero and import the main.aux file

Expected result:
A_key and B_key are imported as two separate items.

Actual result: 
the two keys are not imported,
the concatenation of "A_key,B_key" is signaled as missing key.

Notes:
This was observed after upgrading to the latest version today.
This does not happen when the cite package is not in use.

**Comment by retorquere** [comment]
This must have been a long-standing error, I haven't changed anything about the AUX scanner in 5 months. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2546.xpi ?

**Comment by bonderado** [comment]
Thank you for the quick response.
I just tried  the version you linked and it imported all the references in my document correctly.
I think the bug can be closed.
