### ISSUE TITLE
Aux scanner does not scan secondary aux files when \include is used in the tex document

### ISSUE THREAD

**Issue by bonderado** [retorquere/zotero-better-bibtex#522]
When the main.tex file includes contents from secondary files, each file has its own .aux and main.aux contains lines like:
\@input{secondary.aux}

The aux scanner ignores those lines, so references from secondary.tex are lost, moreover, if all uses of \cite are in secondary files, zotero-better-bibtex reports:
"The selected file is not in a supported format."
for main.aux.

Steps to reproduce:

1. Create a main.tex file with the following contents:
\documentclass{article}
\begin{document}
  \include{secondary}
\end{document}
2. Create a secondary.tex file with the following content (change A_key to fit your zotero database):
\cite{A_key}

3. compile main.tex
pdflatex main

4. run zotero and import main.aux

Actual result:
A dialog pop up, with the message:
"The selected file is not in a supported format."
"A_key" is not imported.

Expected result:
"A_key" is importeed in zotero.

Note:
If  the line:
\cite{B_key}
is added in main.tex inside the document environment, then the dialog does not pop up, but only "B_key" is imported correctly, while "A_key" is ignored.

**Comment by retorquere** [comment]
This cannot be fixed using the current import mechanism. Import translators are handed the contents of the file but not its location, so I can't know what path they are relative to, and even if I could find out, import translators are not allowed to open files themselves. I might be able to fudge around this by treating them as attachments, but even if that would work, nested inputs beyond the main file would be out of reach.

For the short term, you might be able to use latexpand to flatten the aux files into a single file, but I haven't tried that myself. For the longer term, I'll look into a non-import way to do aux scanning.

**Comment by bonderado** [comment]
Well that is unfortunate, but since I use a Makefile for my documents I can do the flattening on my own using a simple minded script that acts on the .aux directly.

For example I am trying with this, flataux.py:

    #! /usr/bin/env python

    # usage flataux.py file.aux
    # will output to flattened_file.aux


    def flataux(fname):
        import re
        pattern = re.compile('\\\@input{([^}]*)}')
        with open(fname, 'r') as source:
            for line in source:
                match = pattern.search(line)
                if match is not None:
                    print 'found ', line
                    for secondary in flataux(match.groups()[0]):
                        yield secondary
                else:
                    yield line

    if __name__ == '__main__':
        import sys
        name = sys.argv[1]
        with open('flattened_'+name, 'w') as destination:
            destination.writelines(flataux(name))

Ideally I should be able to query zotero from the script and get it to export  the relevant keys, but I am not that good.

A possible workaround for you, is to allow importing from "main.fls". 
This file is only generated when latex is run with the "--recorder" option and, at least in my setup, it dumps the full path of all input and output files: it can be filtered to extract output files with the .aux extension. The users have to remember using the "--recorder" option, but it seems acceptable.
 
I am leaving this open just in case, but you can close it if you feel it is beyond the scope of the plugin.

Thank you again for looking into it.

**Comment by retorquere** [comment]
Can you attach such an fls file?

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2559.xpi ? The bibtex aux importer is gone, replaced by a menu item in the gear menu.

I don't get such `\input` behavior myself, I have multi-file latex documents but they all collect into one aux file. Perhaps because I'm using biblatex?

**Comment by bonderado** [comment]
Hi, sorry for the inordinate amount of trouble.

Regarding the creation of an aux file for each include, I do not know if it is a default enabled in the (pdf)ltex build I use or caused by some package, butthey pop out on my disk whenecver I compile the document.

I checked 1.6.65-circle-2559.xpi  and it appears that issue #521 crept back into it: when I have sub.aux files the citation is not imported. when all is in one aux file it works as expected. 

I also attach the main.fls I get using the '--recorder' option and the two aux fies that displayed the issue [auxfls.zip](https://github.com/retorquere/zotero-better-bibtex/files/328416/auxfls.zip) although I feel that scanning the aux should be the better way to go (everyone will have aux).

Have a good day.

**Comment by retorquere** [comment]
Can you zip up your aux files for me too?

**Comment by retorquere** [comment]
Oh, hold on, they're in the zip too. But in what way is #521 back? That sub.aux is not imported is this bug, not #521.

I got the regex for the inclusion wrong, a new build is on its way.

**Comment by bonderado** [comment]
Yes sorry about the bug number I was posting from the office when people came in to ask me something and I got the numbers mixed.

**Comment by retorquere** [comment]
Can  you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2574.xpi ?

**Comment by bonderado** [comment]
Looks like now the scanner is expecting to have sub files and bails out if not.
If I have a secondary aux, nothing is imported at all. I tried to delete the \@input{test.tex} line and the citations from main were imported.

**Comment by retorquere** [comment]
Nope, no expectations, but it's probably encountering an error and stopping. Enable extended debugging in the BBT prefs, try to scan again, and then from the gear menu select "report better bibtex error". It will show an ID in red, if you  post that here, I can investigate

**Comment by bonderado** [comment]
Ok, done,
ReportID: Z8UKSKFF

**Comment by retorquere** [comment]
Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2582.xpi

**Comment by bonderado** [comment]
Hi,
I tried the circle-2582 with the document I currently write and it worked just fine.

Sorry that this issue took you so much work, but we can close it now.

Thank you so much for being so supportive.

**Comment by retorquere** [comment]
No apologies please, you're helping improve BBT. I'll merge this and release a new version somewhere today or tomorrow.
