### ISSUE TITLE
Cannot install Better Bibtex on Zotero Standalone

### ISSUE THREAD

**Issue by xniso4ka** [retorquere/zotero-better-bibtex#523]
Hi!
I am using Zotero Standalone version 4.0.29.5, and it shows me an error when I am trying to install Zotero Better Bibtex. It got installed on my firefox plugin though. It is very strange because for a while i could see Better Bibtex options for exporting my references, but I do not anymore.
Could you please help?

Thank you!

**Comment by retorquere** [comment]
What error do you see?

**Comment by xniso4ka** [comment]
After I installed a firefox plugin, I can see better bibtex options, but when I try to export using them it gives this error:

(1)(+0000007): TypeError: this.titleCaseLowerCase is undefined
    ===== Stack Trace =====
    Translator.initialize/this.titleCaseLowerCase<@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:1272:5
    Translator.initialize@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:1270:49
    Translator.initialize@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:18134:5
    Translator.nextItem@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:1425:3
    doExport@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:17683:17
    =======================

(2)(+0000000): Translate: Translation using Better BibLaTeX failed: 
string => TypeError: this.titleCaseLowerCase is undefined
stack => Translator.initialize/this.titleCaseLowerCase<@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:1272:5
Translator.initialize@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:1270:49
Translator.initialize@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:18134:5
Translator.nextItem@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:1425:3
doExport@/Users/evgeniiaiakhnis/Library/Application Support/Zotero/Profiles/nyo756n4.default/zotero/translators/Better BibLaTeX.js:17683:17

url => /Users/evgeniiaiakhnis/Desktop/USC_Files/Exported Items.bib
downloadAssociatedFiles => true
automaticSnapshots => true

(5)(+0000000): Translate: Running handler 0 for done

**Comment by retorquere** [comment]
So you can install it correctly, but you cannot export?

**Comment by xniso4ka** [comment]
Well, as far as i understand, I need to install it separately on my firefox plugin and standalone? It shows as one of the extensions on my firefox, but not on the standalone. And when I try to do "Install add-on from file", it tells me that the version is not compatible. So I am very confused.

**Comment by retorquere** [comment]
OK, but can we keep the two issues apart? It's a little confusing to be dealing with them intertwined. There is apparently a separate issue when you try to export from firefox, please file a new issue for that, and let's try to figure out why it's not installing on standalone.

So you say you get a "not compatible" message, and you're installing the same XPI on both firefox and standalone? I've just installed the latest BBT on standalone 4.0.29.5, and I can just install it. How have you downloaded the XPI? No through a download manager?

**Comment by xniso4ka** [comment]
I just clicked on the installation file here https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.65

**Comment by retorquere** [comment]
And you used this same file for both standalone and firefox?

**Comment by xniso4ka** [comment]
yes

**Comment by retorquere** [comment]
can you attach the xpi you downloaded to this issue?

**Comment by xniso4ka** [comment]
it says that that file type is not supported

**Comment by retorquere** [comment]
Just rename it to .zip, I think it will allow that

**Comment by xniso4ka** [comment]
No, wait, I was wrong. I actually don't have it on my computer. I think it installed automatically when I pressed the installer here https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.65

**Comment by xniso4ka** [comment]
sorry, for the confusion, I guess I was trying to open a different file

**Comment by xniso4ka** [comment]
does it mean that it actually got installed on my standalone?

**Comment by retorquere** [comment]
I don't know, but it seems unlikely. In standalone, you can go into tools - addons to see which plugins are installed. This is also where you would install the plugin -- if you haven't been in that part of the UI, I don't think you have installed BBT.

**Comment by xniso4ka** [comment]
could you attach the installation file here for me to try?

**Comment by rmzelle** [comment]
Just download https://github.com/retorquere/zotero-better-bibtex/releases/download/1.6.65/zotero-better-bibtex-1.6.65.xpi and select that from Tools > Add-ons menu (gear menu, "Install add-on from file...")

**Comment by retorquere** [comment]
It wouldn't be different from getting it from https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.65. Just right-click on the xpi link and choose "save", and then install it in standalone.

**Comment by xniso4ka** [comment]
cool, it installed correctly now and it all works! Thank you very much for your help!

**Comment by retorquere** [comment]
OK, if there's still a separate issue with exports, please file a new issue
