### ISSUE TITLE
Cache must be dropped if Zotero profile location changes

### ISSUE THREAD

**Issue by Quantizen** [retorquere/zotero-better-bibtex#524]
I have changed my zotero's data directory location to a custom one, for example, `/Users/Username/Zotero`. But the directory of files is still 

```
PDF:/Users/Username/Library/Application Support/Zotero/Profiles/vbzmo3uh.default/Zotero/storage/...
```
but not
```
PDF:/Users/Username/Zotero/storage/...
```
What should I do if I want the later one?

**Comment by retorquere** [comment]
Go into the bbt preferences, advanced tab, and clear the cache.

**Comment by Quantizen** [comment]
It works! Thanks!

**Comment by retorquere** [comment]
I've made a change that should make this automatic in the future.
