### ISSUE TITLE
Sort export by citation key

### ISSUE THREAD

**Issue by gncs** [retorquere/zotero-better-bibtex#525]
What determines the order of bib(la)tex items in the output file? Is it possible to sort the items by the citation key?

Thank you very much!

**Comment by retorquere** [comment]
It's the order Zotero offers the items to the translator; that ordering is outside my control. It is technically possible for a translator to read in all items, sort them, and then go about its work, but it's not a trivial change, and it would impact both speed and memory use.

**Comment by gncs** [comment]
I started a discussion in the [Zotero forum](https://forums.zotero.org/discussion/60375/sort-items-zotero-offers-to-translator/). I will get back to you as soon as I know more :)

**Comment by retorquere** [comment]
Zotero doesn't (formally) know about the citation key, so it's not something they could do. The first part of my comment was just an answer to "what determines the order"; I didn't mean to imply Zotero could/should change this, sorry.

The citation key is specific to BBT. If any sorting on the citekey is to be done, it must be done by BBT. 

There's two ways BBT actually can; one is to hijack the method that fetches the items to feed to the translator. That's not formally supported, and it's fragile; I do it in a few places as a method of last resort, but I avoid it whenever I can (those spots will be the main hurdle to migrate to 5.0).

The other option would be to generate the whole export in memory, and sort that before doing the actual export. That, as mentioned, has performance and speed implications, and BBT is already slower, and more of a memory hog, than I want it to be.

I'm trying to come up with a way to make this happen with minimal impact on code, and preferably no UI (the BBT preferences are too baroque as it is), but I haven't been able to come up with anything yet.

**Comment by retorquere** [comment]
The change has been accepted in the Zotero 5.0 release, and is pending acceptance in the 4.0 line. It will take a while before it will find your way though -- Zotero has a more sensible release schedule than BBT.

**Comment by gncs** [comment]
Thanks!
