### ISSUE TITLE
Firefox crashed and now Better Bibtex doesn't work: no citation keys

### ISSUE THREAD

**Issue by StephenSelf** [retorquere/zotero-better-bibtex#526]
While working this morning, Firefox unexpectedly crashed (crash report: https://crash-stats.mozilla.com/report/index/22a3185f-c46d-4e65-9108-9f7b02160627). Once I brought it back up, all my citation keys were gone. I completely uninstalled all Zotero add-ons as well as Zotero itself, rebooted computer, and still, when I bring it all back up and reinstalled with latest versions, there are no citation keys. When I run an export using Better Bibtex, I get an error saying that the file could not be exported. When I run export without Better Bibtex, it works fine. When I run autoexport using Robert Kühn's plug-in, it also works fine. But I still have no citation keys with Better bibtex and cannot export with it. I sent a Better Bibtex bug report. Please assist. Thanks!

**Comment by retorquere** [comment]
What was the ID of the bug report?

**Comment by retorquere** [comment]
I've found at least one problem that could affect you -- could you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.66-circle-2596.xpi ?

**Comment by StephenSelf** [comment]
I’m afraid I didn’t not the ID number. Is there a way I can find it? Thanks

SNS

**Comment by retorquere** [comment]
Nope, once submitted, the ID is discarded. But specially for you, retries are free :)

Just install the debug version from https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.66-circle-2596.xpi, and if the problem still exists, submit a new error report.

**Comment by StephenSelf** [comment]
It looks like that fixed it. I had found a discussion thread that talked about BBT database becoming corrupt. Is that what happened here? I want to try to understand what happened so I can be wary in the future and avoid it. Thanks for your help. Sorry for missing the ID.

SNS

**Comment by retorquere** [comment]
No, this was a different issue. I don't know what caused Firefox to crash, but what stopped BBT from working is an error in the upgrade-detection. I would expect that (unless you deleted your profile) the citekeys should just reappear now.

I've scheduled a new release, .67 should be out soon, but it's just the release of the version you have now.

**Comment by StephenSelf** [comment]
Ok. Good to know. Yeah, all citekeys are back and everything is functioning normally. Thanks for all your work and help on this!

SNS

**Comment by retorquere** [comment]
No worries, and sorry for the disruption.

**Comment by retorquere** [comment]
(Since that error report on DB corruption, BBT has gone back to using the Zotero database facilities. That should take care of DB corruption, even if data loss as a result of such hard crashes is still possible)
