### ISSUE TITLE
Report ID: PDQPCADE / An error occurred while trying to export the selected file.

### ISSUE THREAD

**Issue by awesomeindustries** [retorquere/zotero-better-bibtex#530]
```
**[JavaScript Application]**
An error occurred while trying to export the selected file.
```

This error occurs in .67, both for trying to export a collection to Better BibTeX and for Better BibLaTeX.

I use Zotero Standalone on a OS X 10.11.5. I also have the Zotero plugin in Firefox, which uses the Zotero Standalone library so it acts as a Zotero Connector (as suggested on the Zotero site).

The above error also occurs if Firefox is quit.

**Comment by retorquere** [comment]
Just to be sure: you haven't merely closed Firefox, but really stopped it using command-Q? And do both Standalone (ZSA) and Firefox (ZF) have BBT installed? If you only use Firefox for the connector, it's best not to have BBT installed in Firefox, only in ZSA.

From the logs it looks like the BBT database has gotten corrupted, and the usual Zotero DB recovery didn't kick in. Have you recently experienced a Firefox or ZSA crash?

Can you do the following for me, in order:

1. Stop both ZF and ZSA (full quit, so command-Q or Quit from the menu)
2. Find your zotero Profile directory. If you're sharing your profile dir between ZSA and ZF, it will be in `~/Library/Application Support/Firefox/Profiles`, for ZSA it will be in `~/Library/Application Support/Zotero/Profiles`
3. Under that directory, find `betterbibtex-lokijs.sqlite`. In the same directory you find this, there should not be any other files named `betterbibtex-lokijs<whatever>` -- if there are, either ZF or ZSA is likely still running.
4. Drop  `betterbibtex-lokijs.sqlite` into https://dbinbox.com/retorquere

This will allow me to see where the corruption lies and try to recover your database.

If you're in a hurry, you can **after doing the above steps** try the following:

5. Download the [BBT prerelease](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.67-circle-2612.xpi) and install it

This version will allow you to proceed but will regenerate all citation keys except those that are pinned. For most people this is sufficient, but if you have a significant number of auto-generated keys that are disambiguated through postfixes, it will be a nuisance. The next release will move away from the Zotero DB mechanism and use a file-based backup and recovery system -- the pre-release is just what is going to be released really soon. When it cannot read the DB during migration, it will generate a fresh file-based DB instead.

**Comment by awesomeindustries** [comment]
I really quit (CMD Q) Firefox. Firefox does not have BBT installed.

I am using a custom data location, it is configured like this in ZSA and ZF (to be able to configure ZF, ZSA should be Quit)

`Zotero settings > Advanced  > Files and Folders > Data Directory Location`
The location I use is `~/Documents/Literature/Zotero Base/`
In this directory I did find the sqlite file. There were also some sqlite.bak and sqlite 1.bak files, they are more recent than the betterbibtex-lokijs.sqlite file.

I have uploaded all 3 files to your dbox.

Maybe another symptom is that I am not able to generate or clear any citation keys, could that be related?

**Comment by retorquere** [comment]
Unfortunately, all three (the DB file and the backups) appear to be corrupt. I have no idea how to even cause that, or why Zotero hasn't created database backups, or skipped the corrupt database and moved on.

BBT handles this error rather ungracefully and fails to initialize; this does explain that a lot of things won't work. [this prerelease](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.67-circle-2613.xpi) should handle the problem better... but I'm afraid I can't recover your database, which means that any non-pinned keys will be regenerated. In that profile directory, a new directory will be created called `better-bibtex`, in which two files will appear, called `db.json` and `cache.json`. Numbered backups will appear soon after.

**Comment by awesomeindustries** [comment]
Awesome, it works as a charm! Thank you very much for your quick replies and adequate solution!

**Comment by retorquere** [comment]
I'm sorry I couldn't do better, but I'm happy you can proceed. I'll just cut a release right now, you'll be asked whether you want to upgrade somewhere the next 24 hours unless you force a Zotero/Firefox to look for new extensions.

**Comment by awesomeindustries** [comment]
I have a reasonably large library (1500 items), but I am in no way attached to the citation keys: no work is lost, so for my situation you couldn't do better!
Cheers!
