### ISSUE TITLE
XPW67IUN underscore in doi field

### ISSUE THREAD

**Issue by cdriveraus** [retorquere/zotero-better-bibtex#532]
It seems that the underscore is causing latex problems, and should probably be handled differently?

**Comment by retorquere** [comment]
Is this for bibtex or biblatex?

**Comment by cdriveraus** [comment]
Using natbib / bibtex. And when I say problems, I mean 'missing $ inserted', though still compiles.

**Comment by retorquere** [comment]
@nickbart I don't think bibtex knows about DOIs, correct? I output them in verbatim mode, and bibtex doesn't seem to like it.

**Comment by nickbart1980** [comment]
It’s certainly not in the original bibtex specs, but if some bibtex style does render the content of a `doi` field, but chokes on special characters, I’d consider that style to be broken. It’d say this is not a BBT bug, and would recommend to contact the style author instead.

**Comment by cdriveraus** [comment]
Aha ok... it's the apa6 style, for interest.

**Comment by retorquere** [comment]
I've sent the apa6 maintainer (brian@beitzel.com) an email asking his advice.

**Comment by retorquere** [comment]
I got back a somewhat cryptic response:

"The apa6 class does not handle bibliographies, so this question is best addressed to the maintainers of whichever bibliography packages are involved.  However, I see no reason to treat DOIs for BibLaTeX any differently from BibTeX."

Does that mean it'd be a natbib issue?

**Comment by nickbart1980** [comment]
I would guess so. An alternative might be to try an addon like the `uri` package (see https://tex.stackexchange.com/questions/53993/natbib-of-doi-with-bad-characters). Anyway, an MWE demonstrating the OP’s problem would be very helpful …

**Comment by retorquere** [comment]
Well, that was rather embarrassing. As @nickbart1980 said, and MWE would be very helpful -- I need to know your bibliography style in use rather than the document style.

**Comment by cdriveraus** [comment]
Ok - here you are...

[doiproblem.zip](https://github.com/retorquere/zotero-better-bibtex/files/359624/doiproblem.zip)

**Comment by retorquere** [comment]
@nickbart1980 i've put it up at https://www.sharelatex.com/project/54feca38f58d781e0c982eeb so we can experiment, but it has no bib style specified -- do you know what the default style is if none is specified? Would that be `plain`?

**Comment by retorquere** [comment]
Wow, I'm on a roll today. @nickbart1980 already pointed to the solution -- adding `\usepackage{uri}` or `\usepackage{doi}` to your document should fix it.

**Comment by cdriveraus** [comment]
Sure, thanks I appreciate it being looked into - I thought you must have been wanting to implement something on your end! :)

**Comment by retorquere** [comment]
I fix what I can, but BibTeX in particular doesn't make life easy. I've settled on BibLaTeX myself. Which, make no mistake, has tons of issues too, but they tend to be slightly more sane problems in today's world. Alas, not everyone can use BibLaTeX, but if you can, you're doing yourself a favor.
