### ISSUE TITLE
Auto exporting issue

### ISSUE THREAD

**Issue by ETaSky** [retorquere/zotero-better-bibtex#533]
Hello retorquere,

It appears that this issue (same as #490,#493,#496) happens again in the latest version of BetterBibTex (.68). The auto export disappeared after zotero restarted. I am using Zotero standalone v 4.0.29.10 on a windows machine. I tried to install previous versions of Better BibTex (.53, .57, .66, .67) to see if the issue disappeared. But to make it even weirder, in all the previous versions I have tested, when clicking "export collections", the BetterBibTex format was not there (so as the checkbox of "Keep Updated").
Thank you!

**Comment by retorquere** [comment]
Can you submit an better bibtex error report and post the ID here? It's
probably not the same issue, even if the symptoms appear the same.

**Comment by ETaSky** [comment]
Thanks! The report ID is MBV7J7ZN.
I did what you instructed in #490, but I am not sure if this is what you are expecting. Thank you very much!

**Comment by retorquere** [comment]
The previous versions expected a different database format in a different location; since that won't be present after you've ran .68, the older versions will initialize a new pre-.68 database... and running .68 on that again will migrate the mostly-empty older-format database over the newer .68 database format. There will be numbered backups in the `better-bibtex` folder under the `zotero` data directory, first order of business is to secure those, then we'll look further.

**Comment by ETaSky** [comment]
Sorry, I don't get what you meant. Should I do something?

**Comment by retorquere** [comment]
I wanted to have a look at your backup files, but if you've used BBT in the interim and changed references, they will probably have been overwritten. What version are you on now? If you're not back on .68, go into the Zotero data directory (Preferences/Advanced/Files and Folders and click "Show Data Directory") and secure the cache.json* and db.json* files you find in the better-bibtex directory... but the MBV7J7ZN log is from .68, so you're likely on that version. In which case, skip the above.

To get back to the issue at hand, when you say "the auto export disappeared", what exactly are you (not) seeing? Is the "keep updated" option gone, have existing auto-exports disappeared from the overview in the BBT prefs, something else? I do see auto-export activity in the logs to a file called MicrobiomeScratches.bib, and a claim that the export was successful.

There are some errors in the log but they don't seem related to BBT. To make sure about this, could you disable all extensions except BBT, restart, and submit a new log?

**Comment by ETaSky** [comment]
Thanks. I disabled all other extensions and restarted zotero and submitted an error report, the ID is: MS9DUKM9.
I am now on .68 version.
What I mean by "disappear" is the same as the issues the other reported. 1. on .68 version, I am able to export the  collection, and able to click the "keep updated" option (means the Better bibtex format is there). 2. The first step successfully created an auto export, which appeared in the Automatic export tab in the Better BibTex preferences. 3. But as long as I restarted Zotero, the auto export records disappeared in the Automatic export tab and I could see it is not auto exporting. Hope this clarifies what the issue is.
Thank you!

**Comment by retorquere** [comment]
OK, can you go into the Zotero data directory (Preferences/Advanced/Files and Folders and click "Show Data Directory") and drop the `cache.json` and `db.json` files you find in the `better-bibtex` directory into https://dbinbox.com/retorquere

**Comment by ETaSky** [comment]
Thanks! I have already uploaded the two files.

**Comment by retorquere** [comment]
There was an error in the DB, likely related to #537. I have a fixed version you could put in place, how can I get it to you? There was an invalid citekey `sperandiobacteria_host2003` in the database, where the underscore was an odd character I've replaced. Cache.json also had an error, but that regenerates cleanly, so you can delete it.

**Comment by ETaSky** [comment]
Thank you very much! Perhaps you can email me at etasky@gmail.com, or share with me over dropbox using the same email address.

**Comment by ETaSky** [comment]
Hello. Thank you very much! This indeed solved the problem. Really appreciate it!

**Comment by retorquere** [comment]
My pleasure. Unfortunately until #537 is fixed there is a change the problem will re-emerge, so I propose keeping this issue open until it is resolved.

**Comment by retorquere** [comment]
.69 fixes #537
