### ISSUE TITLE
zotero uses wrong citation key when exporting tot bibtex file

### ISSUE THREAD

**Issue by voeler** [retorquere/zotero-better-bibtex#534]
Even though in the Zotero interface the correct key is displayed (fokkema1993), after exporting my library to .bib file, it uses the default Zotero scheme (fokkema_seismic_1993).

Other settings are also ignored. E.g. the 'fields to omit for export' option is also not working with input 'note' (the note field still appearts in the bibtex file).

**Comment by retorquere** [comment]
Can you try clearing your cache in the Better BibTeX Advanced preferences and try again?

**Comment by retorquere** [comment]
(there's no error in the log that was submitted so if the clear-cache doesn't help I'll need a new debug log with extended debugging on)

**Comment by voeler** [comment]
I didn't realize I was able to select Better Bibtex when exporting ><. Sorry for bothering you! Everything is working fine now.

**Comment by retorquere** [comment]
Oh, right, you exported using "BibTeX"? That's the stock Zotero BibTeX exporter.

**Comment by voeler** [comment]
Yes, I somehow assumed BBT would 'overwrite' the default bibtex features of zotero, but being able to choose between default zotero and BBT in this way is actually pretty good!

Also, thanks for developing this plugin, makes zotero a much more usable.

**Comment by retorquere** [comment]
It did at one time overwrite the standard BibTeX exporter, but that yielded some funky error reports for the Zotero devs who could have no idea who generated the error.
