### ISSUE TITLE
library does not show up in auto-export table

### ISSUE THREAD

**Issue by voeler** [retorquere/zotero-better-bibtex#535]
I'm not sure if I'm doing something wrong, but after exporting my library it does not show up in the automatic export pane in BBT preferences.

**Comment by retorquere** [comment]
There's no error in the log you submitted. You did tick 'keep updated' when you exported the library? If so, can you enable extended debugging in the BBT advanced prefs and submit a new log ID?

**Comment by voeler** [comment]
Solved (see issue #534).
