### ISSUE TITLE
UTF-8 Encoding Issue (BibLaTeX)

### ISSUE THREAD

**Issue by InazeaAnazasi** [retorquere/zotero-better-bibtex#536]
When exporting to BetterBibLaTeX, the umlauts are not being encoded properly: ö , ä, ü and  ß all become �. Strange enough, when I export using BibLaTeX, all these characters are encoded properly; but, of course, then I can not take advantage of the great cite keys generated by better-bibtex... The problem is relevant because my LaTeX recognices ä,ö,ü and ß, but not �, so basically, I can not compile my tex-file.

**Comment by retorquere** [comment]
Can you right-click on that reference and select "send better bibtex error"? If you post the resulting ID here I'll have a copy to inspect.

**Comment by InazeaAnazasi** [comment]
While doing so, I saw that now, all characters are exported properly... I must have done something wrong, then. However, now it works. Thanks!
