### ISSUE TITLE
Citation keys have changed

### ISSUE THREAD

**Issue by gracile-fr** [retorquere/zotero-better-bibtex#538]
The French definite article "les" was removed previously, but it's not the case anymore.
e.g.: key was : <code>author_bases_year</code> and is now : <code>author_les_year</code>.

The French definite article "l'" was changed to "l" (apostrophe stripped) but now it is entirely stripped. 
e.g.: key was : <code>author_lacte_year</code> and is now : <code>author_acte_year</code>.

This change *[edit: the second one, concerning "l'"]* can be seen as an improvement, so that's ok for me, but why do the keys have been changed? I've a document which still uses the old keys and need to update it now :-( Is it the "normal" behaviour to update keys automatically when BBT is updated but the user data are not? Thanks !

**Comment by retorquere** [comment]
No, that should not have happened. The keys, once generated, should remain until a reference is changed. What is your key pattern? What part did "les" come from?

**Comment by gracile-fr** [comment]
I don't have change the default key patern : author_title_year
"les" is coming from the title, e.g. : "Les actes"

**Comment by retorquere** [comment]
Looking at one of the logs you submitted for #537 (R2V794XC) it looks like the pattern is `[zotero]`, and that pattern doesn't remove `les`, so the puzzling thing for me is how the generated key was ever `author_bases_year`.

The default skipwords setting for `[title]` would remove `les` though -- could it be you have recently changed the pattern from something like `[auth:lower]_[title:lower]_[year]` to `[zotero]`? That would explain why all keys changed -- a pattern change will re-do all existing non-pinned keys.

**Comment by gracile-fr** [comment]
<code>[zotero]</code> means that it's zotero default pattern right ? How could I have changed the pattern ?

**Comment by retorquere** [comment]
That does mean it's the default pattern. The pattern can be changed in the BBT preferences, but I don't keep a history of pref changes, so I can't tell whether it was ever anything different. What I do know is that the `[zotero]` pattern wouldn't have removed `les`, and the only way I can explain `les` being absent earlier is if the pattern was at some time different.

**Comment by gracile-fr** [comment]
I'm pretty sure I've never changed it in the BBT prefs or elsewhere… Did you update the skipwords in the last few months (actually in the last 11 months).

**Comment by retorquere** [comment]
Skipwords was changed on 2015-12-09, but this would not have affected the `[zotero]` pattern, which uses a fixed skipwords list copied from the Zotero BibTeX translator. The `[zotero]` pattern was last changed on 2016-06-10, but `les` has never been in the fixed list for that.

**Comment by gracile-fr** [comment]
<blockquote>The [zotero] pattern was last changed on 2016-06-10</blockquote>What has been changed? Where can I see the changelog for this pattern?

It is stranger than I thought: <code>l'</code> is not always stripped ! For some items, the old behaviour remains and only the apostrophe is removed… maybe old items, I have to investigate further.

**Comment by retorquere** [comment]
The history of that pattern runs from [here](https://github.com/retorquere/zotero-better-bibtex/blame/master/chrome/content/zotero-better-bibtex/BetterBibTeXPatternFormatter.coffee#L176) to [here](https://github.com/retorquere/zotero-better-bibtex/blame/master/chrome/content/zotero-better-bibtex/BetterBibTeXPatternFormatter.coffee#L211). The change to its skipwords list is [here](https://github.com/retorquere/zotero-better-bibtex/blame/master/chrome/content/zotero-better-bibtex/BetterBibTeXPatternFormatter.coffee#L178); it didn't change the skipwords list but was an adjustment of the `span` detection. `l'` *is* in the skipword list though, and as far as I can tell it always has been.

But there's one thing I hadn't considered, come to think of it... I [changed the pattern *default*](https://github.com/retorquere/zotero-better-bibtex/commit/cc98ef38c618c2202d28c8e2c533ab58e6f82ed4#diff-c14d544f6a1c862abbe23b3342060687R14) on [Jan 29](https://github.com/retorquere/zotero-better-bibtex/blame/master/defaults/preferences/defaults.yml#L14) from `[auth:lower][Title:fold:nopunct:skipwords:select,1,1:lower:alphanum:prefix,_][year:prefix,_][0]` (which aimed to emulate the zotero pattern, but didn't perfectly) to `[zotero]` (which just copied the zotero code)]... and a change to the default doesn't get alerted to the running code as a pref change. So any references that changed after that would be subject to the new pattern, and old ones would just keep the key generated under the emulator pattern.

I have tests running on a version that will find these keys and cause them to be regenerated. Fortunately, for each dynamic key I retained the pattern against which they were generated, so I can just touch the keys where the stored pattern is different from the effective pattern.

**Comment by gracile-fr** [comment]
Ok. I'm still not sure why some keys have changed because their references have not changed after Jan 29.

In additon, I've found that:
1) If a title begins by <code>L'</code> and is immediately followed by a word beginning with an accented char such as é, è, ê, etc, the accent is stripped, the apostrophe is stripped but the article remains.
E.g.: title=<code>L'évolution</code> ; <code>key=levolution</code> ; title=<code>L'exemple</code> ; <code>key=exemple</code>
It's a bug in my opinion, but probably a Zotero bug if I follow you correctly ?

2) The typographic or curly apostrophe (U+2019 right single quotation mark) fools the stripping mechanism.
E.g.: title=<code>L’exemple</code> ; <code>key=lexemple</code> ; <code>title=L'exemple</code> ; <code>key=exemple</code>

**Comment by gracile-fr** [comment]
Re: the <code>Les</code> issue:
The change you made on Jan 29 explain why <code>les</code> was stripped before and is not removed anymore, right ?

**Comment by retorquere** [comment]
There's one reason I can think of that a key could have changed even though its reference has not: if you generated a pinned key that conflicts with an existing key, and your key conflict policy is "change". Other than that, it really shouldn't change.

WRT:

1. Easily tested: export the reference with the standard BibTeX exporter -- the `[zotero]` pattern should replicate what that yields. The `[zotero]` pattern intends to replicate the standard zotero key generation pattern *exactly*, warts and all.
2. Does this happen for the `[zotero]` pattern (in which case there's nothing I can do about that) or one of BBT's own patterns?

**Comment by gracile-fr** [comment]
I assume I should open an issue on the Zotero side to add <code>les </code>as a skip word and to fix the <code>l'+diacritic</code> and <code>l’</code> issues.

**Comment by retorquere** [comment]
If the `[zotero]` pattern is important to you, then yes. Personally, I don't use it, and it's only present in BBT (and set to the default) to help people migrate who already used the Zotero BibTeX exporter.

**Comment by retorquere** [comment]
(but if the Zotero BibTeX exporter changes, I simply follow suit)

**Comment by gracile-fr** [comment]
The [zotero] pattern is not important to me. I've just chosen the simplest way. I'm a bit afraid to make some changes to the pattern because I don't want to see all my non-fixed keys change again.
But, let say that I just want the [zotero] pattern without <code>les</code>, <code>l'</code> and <code>l’</code>: what should I do ?

**Comment by retorquere** [comment]
To do it structurally, you have to change the citekey pattern. If you already know what pattern you want, we could modify the database to make sure your keys don't change when you change to that pattern.

**Comment by retorquere** [comment]
[this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.69-circle-2638.xpi) is going to go out soon, it should detect the keys generated on the old pattern and cause them to be regenerated. If you want to make sure that they dynamic keys you have are retained exactly as-is, don't install it yet, I can fudge your DB if you get me a copy that will keep all your keys.

**Comment by gracile-fr** [comment]
I'm not sure what I should have done and what you have changed ? Thanks anyway

**Comment by retorquere** [comment]
I could in principle have saved any dynamic keys with postfixes and restore them in exactly the same way. They probably will regenerate the same way anyhow.

**Comment by gracile-fr** [comment]
Ok, I understand it's too late but that's my fault (I've been quite busy). Are there any changes to the way the keys are generated?

**Comment by retorquere** [comment]
Nope, none, but the order in which they're generated determines the
postfixes, and that order is not wholly deterministic.

**Comment by gracile-fr** [comment]
side question: which version of Firefox are you using now that <code>xpinstall.signatures.required</code> pref has been disabled in FF 48?

**Comment by retorquere** [comment]
I'm using 48. I'm not super happy about how Mozilla has gone about the whole thing, but I need to use the same browser my users have. As a consequence (and to the initial surprise of Mozilla), I have started to sign each and every build. First only the builds that passed my CI tests (as those are often used for debugging with users), and now also all my local builds. 1,068 builds uploaded to Mozilla so far, and since they don't allow for easy cleanup of throwaway builds, that's only going to climb.

**Comment by retorquere** [comment]
Except that Mozilla is unwilling, apparently, to sign Selenium, which breaks my tests. Grrrreat. So I'm now down to ESR, and rooting for Zotero to hasten their move away from Firefox entirely.

**Comment by gracile-fr** [comment]
What about Firefox Developer Edition ? Or <a href="https://blog.mozilla.org/addons/2016/07/29/extension-signing-availability-of-unbranded-builds/">unbranded builds</a> ?

**Comment by retorquere** [comment]
Not an option, because they [won't update](https://bugzilla.mozilla.org/show_bug.cgi?id=1290548#c9). I can't tell you how eagerly I await the Zotero team ditching Firefox. It's become one major annoyance after the other, and I don't even use Firefox except for Zotero.
