### ISSUE TITLE
Add postscript to correct the "language" field

### ISSUE THREAD

**Issue by saccohuo** [retorquere/zotero-better-bibtex#540]
I use Zotero to grab metadata from Chinese papers website, and then get the `language` field of every item as `中文` or `中文;`.

But when the bib file is used to generate bibliography, there is something wrong with the omitted item of the additional authors except when I modify the value of `language` field to `zh`.

So I wanna replace the value of language field from `中文` or `中文;` to `zh`, how can I write the postscript? Thanks!

I tried to realize it with the following code, but found it not work. I do not know the reason.
```
﻿if (Translator.BetterBibTeX) {
  if (this.item.language == '中文' || this.item.language == '中文;') {
    this.remove(language);
    this.add({name:language, value:"zh"});
  }
}
```

**Comment by retorquere** [comment]
Close though. At the time of the postscript, the authors have already been set and won't change unless you change them. I reckon something like this should work:

```
if (Translator.BetterBibTeX && (this.item.language) === '中文' || this.item.language === '中文;')) {
  this.item.language = 'zh'; // addCreators looks at this field
  this.add({ name: language, value: 'zh', replace: true });
  this.addCreators(); // re-does the creator fields
}
```

**Comment by saccohuo** [comment]
There is an additional right round bracket in the code you give.
It still cannot work though I remove the additional bracket.
```
﻿if (Translator.BetterBibTeX && (this.item.language === '中文' || this.item.language === '中文;')) {
  this.item.language = 'zh'; // addCreators looks at this field
  this.add({ name: language, value: 'zh', replace: true });
  this.addCreators(); // re-does the creator fields
}
```

**Comment by retorquere** [comment]
Can you right-click that reference and select "send better bibtex error
report", and post the debug id and a sample of how you'd like it to look
here?

**Comment by saccohuo** [comment]
The report ID is `CW7T8W56`.
What does the sample mean? I cannot understand it clearly.
I just want the `language` field of the item modified to be `zh` when I use BetterBibTeX export.

**Comment by retorquere** [comment]
There was a typo in my earlier script, it should have been

```
if (Translator.BetterBibTeX && (this.item.language === '中文' || this.item.language === '中文;')) {
  this.add({ name: 'language', value: 'zh', replace: true });
}
```

**Comment by saccohuo** [comment]
It does work.
Thanks!
