### ISSUE TITLE
Citation Key missing in standalone

### ISSUE THREAD

**Issue by rgjeff** [retorquere/zotero-better-bibtex#542]
I'm running standalone on OS X and for some reason the Citation Key field is blank for all my entries (in the Info tab for each item). I have standalone running on a different PC and the Citation Key displays there with no issues. I've looked through the preferences and made sure all the options are consistent between each machine but no dice. Pic below of what I'm seeing, if the above didn't make sense...

![he3oeyt](https://cloud.githubusercontent.com/assets/20844029/17411287/c346ed80-5a45-11e6-88e7-486577cf22e2.png)

**Comment by retorquere** [comment]
Must be an error preventing bbt from fully initializing. I won't be able to look at it before Sunday, but could you submit a bbt error report?

**Comment by rgjeff** [comment]
> Must be an error preventing bbt from fully initializing. I won't be able to look at it before Sunday, but could you submit a bbt error report?

Thanks! Do you mean submit an error report through "Preferences --> BBT --> Advanced tab --> Report BBT Errors..."? I'm also having an issue here... I'm selecting it but nothing happens (on my PC an error report window pops, so I assume this is an issue as well). Another thing I'm noticing now is that there's a 6th tab in "Prefs --> BBT" called "BBT has been disabled". Is that indicating that it's currently disabled?

**Comment by retorquere** [comment]
No, that tab is hidden after successful startup of bbt, so that adds to the idea bbt failed to initialize. If no window pops up for the debug log, you can choose "submit error report" (not bbt error report), and in the window that pops up there you can preview the errors from the log and copy them here. No need to submit that report, I can't access it.

**Comment by rgjeff** [comment]
Thanks!

> [JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]" {file: "chrome://zotero-better-bibtex/content/zotero-better-bibtex.js" line: 14}]
> 
> [JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]" {file: "chrome://zotero-better-bibtex/content/zoteroPane.js" line: 2}]
> 
> [JavaScript Error: "TypeError: Zotero.BetterBibTeX is undefined" {file: "chrome://zotero-better-bibtex/content/itemPane.js" line: 51}]

**Comment by retorquere** [comment]
On which version of Zotero are you?

**Comment by rgjeff** [comment]
4.0.11 on OS X

**Comment by retorquere** [comment]
BBT only works on Zotero 4.0.28 or later. A lot changed in 4.0.28, and keeping it backwards compatible was no longer feasible. BBT tries to warn about this but it looks like that warning doesn't work on 4.0.11

**Comment by rgjeff** [comment]
Perfect! I didn't know I was using an older version... it was telling me it was up to date when I checked for updates. Just downloaded 4.0.29.5 and all seems to be working now. Thanks for your help!

**Comment by retorquere** [comment]
My pleasure.
