### ISSUE TITLE
Incompability

### ISSUE THREAD

**Issue by JenniferRoelens** [retorquere/zotero-better-bibtex#543]
I get this error message when I try to install the xpi file as plugin:
"The add-on "%S" could not be installed. It can be incompatible with this version of Zotero Stand-alone." I checked for an update of the Zotero software, but I already have the latest version. Is there a way to fix this?

Greetings,

Jennifer

**Comment by retorquere** [comment]
Is that error message verbatim? I can't find the "it can be incompatible" part in the zotero error messages list.

**Comment by retorquere** [comment]
Can you drop the XPI you downloaded into https://dbinbox.com/retorquere ?

**Comment by JenniferRoelens** [comment]
Hi, 

 

I dropped the XPI!

 

Sorry for the late answer!

 

Greetings,

 

Jennifer

**Comment by retorquere** [comment]
That's OK, but where did you get this file? It's an development asset which isn't shipped with the released plugin. You should have a file ending in `.xpi`, such as found [here](https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.71)

**Comment by JenniferRoelens** [comment]
Hi, I downloaded the latest version here:

https://github.com/retorquere/zotero-better-bibtex

 

It’s my fault, I didn’t go to the release tab!

 

I’m so sorry!

 

Greetings,

 

Jennifer

**Comment by retorquere** [comment]
No problem, and you're not the first to try to install one of the source files, which is why I knew to ask for a copy. The error message from Firefox could be clearer here, as it should be easy to detect that it isn't an XPI at all.
