### ISSUE TITLE
Request: Shortcut for quickly copying the citekey

### ISSUE THREAD

**Issue by openmedi** [retorquere/zotero-better-bibtex#544]
It would be nice if there would be a shortcut to quickly copy the city key.

**Comment by retorquere** [comment]
Adding a new hotkey would require subverting some stuff in Zotero which would be jard ro get right. The best I can do is a new quick copy format -- if you try [this build](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.69-circle-2640.xpi) you can try to see if it does what you want. You configure it as per [these instructions](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#drag-and-drophotkey-citations), but you choose "cite keys" as the format. You can see the relevant hotkey for quick copy in the Zotero prefs under Advanced/Shortcuts.

**Comment by openmedi** [comment]
That helped. Even though in a little bit of a weird way. I installed the build and restarted Zotero (standalone) after which I had the option "cite keys" in my quick copy dropdown of BetterBibTeX. I picked that one and tried the quick copy command, but it didn't work. I restarted Zotero again. Now the option was not in my dropdown menu anymore, so I picked "pandoc", which basically gives me the citekey with an added '@' in front. And that worked. This is close enough what I wanted. I just thought there might be a bug in this build.

**Comment by retorquere** [comment]
If the option wasn't there anymore, you must somehow have reverted to an the release build -- the options for that drop down are hard-coded. The citekeys quick-copy does work for me. I have found a Zotero error that might sometimes interfere, I'm trying to track down the cause of that.

**Comment by retorquere** [comment]
I was wrong, the error message I thought I saw was unrelated. I really can't get it to fail here. Could you try that debug build again, and make sure you've use cmd-shift-c (or the windows/linux equivalent) and not cmd-shift-a?

**Comment by openmedi** [comment]
Now the option sticks around. I don't know what I could've done to revert to the old build but I'm glad it's working now.

**Comment by retorquere** [comment]
.71 has this change included.
