### ISSUE TITLE
kivelson1995, kivelson1995a swapped after update

### ISSUE THREAD

**Issue by skjaeve** [retorquere/zotero-better-bibtex#545]
There was an update to Zotero and Better-Bibtex in the last day or two. I have set up Zotero/BB to automatically keep a .bib file up to date. After the update, these two items had their labels swapped around:
````
@book{kivelson1995,
  address = {Cambridge, UK},
  title = {Introduction {{To Space Physics}}},
  isbn = {0-521-45714-9},
  timestamp = {2016-05-29T20:58:57Z},
  publisher = {{Cambridge University Press}},
  editor = {Kivelson, Margaret G. and Russell, Christopher T.},
  year = {1995}
}

@incollection{kivelson1995a,
  address = {Cambridge, UK},
  title = {Physics of {{Space Plasmas}}},
  isbn = {0-521-45714-9},
  timestamp = {2016-05-29T21:01:08Z},
  booktitle = {Introduction {{To Space Physics}}},
  publisher = {{Cambridge University Press}},
  author = {Kivelson, Margaret G.},
  year = {1995},
  pages = {27--57}
}
````

`kivelson1995` became `kivelson1995a`, and `kivelson1995a` became `kivelson1995`. I had not defined manual labels for these entries.

No other labels were changed, though the order of entries in the file was shuffled.

**Comment by retorquere** [comment]
That the order swapped is in principle explainable (and should be harmless), but the key changes should not have happened. I'm going through my code to see if I can find the reason it did that. Apologies for the disruption.

**Comment by retorquere** [comment]
The only thing I've found so far is the fix I put in place for #538... which could have side-effects like you describe (for which I'll have to find a solution), but given that you clearly don't use the `[zotero]` pattern, that particular problem shouldn't have affected you... still looking.

**Comment by retorquere** [comment]
Ah bugger... the fix for #538 would have affected you. Too late to turn that back now (unless you found it immediately, in which case you have backups), but I'll have to think about how to find a middle road between these two.

**Comment by retorquere** [comment]
I'm extremely sorry about this. Thanks for reporting this issue.

**Comment by retorquere** [comment]
I've disabled this behavior until I figure out a safe way to do it. It won't help you, but a new release will go out soon.
