### ISSUE TITLE
Abbreviations in key generated for Conference Proceedings

### ISSUE THREAD

**Issue by dmbortz** [retorquere/zotero-better-bibtex#548]
Hello,

For a conference paper, the generated key does not seem to generate abbreviations.  For illustration, I have attached a bib file with a conference proceedings paper.

[Exported Items.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/427093/Exported.Items.bib.txt)

The key scheme I use is [authors3][year][journal:nopunct] and I would guess that they key should be something like CorlessJeffreyKnuth1997Proc1997IntSympSymbAlgebrComput and not CorlessJeffreyKnuth1997Proceedingsofthe1997InternationalSymposiumonSymbolicandAlgebraicComputation

Any thoughts?

Thanks again for an awesome plugin!

**Comment by retorquere** [comment]
Do you have auto-abbrev configured or have a manually entered journal abbrev on that item?

**Comment by dmbortz** [comment]
A journal abbrev has not been manually entered. So, I presume it should be using auto-abbrev.  Attached is a screenshot of zotero for that entry.

![screenshot](https://cloud.githubusercontent.com/assets/4753909/17820753/8f8ac792-660b-11e6-8bfe-0773543efcf6.png)

Is there something else I should have done to get auto-abbrev working on this entry?  Abbreviations in the key scheme are working fine on standard journal articles.

**Comment by retorquere** [comment]
Can you right-click that reference and select "report better bibtex error"? If you post the resulting ID (in red) here, I'll have a copy I can test with.

**Comment by dmbortz** [comment]
The ID is 7T9PVX2Z.  It will be the second error I've submitted - when I did the first one, I accidentally closed the window before copying the ID to post it here.

**Comment by retorquere** [comment]
No problem, I don't get actively notified of error reports, so there's no noise, and they're auto-removed after a few days.

Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.72-circle-2775.xpi ?

**Comment by dmbortz** [comment]
That worked - thanks!  Note that after the install, the key was still incorrect (in terms of abbreviations).  I had to "generate key" and then "remove key" to make it work.  The key resulting from "generate" had the correct abbreviations. And, then after I removed the generated key, the auto-abbrev generated key was correct.

**Comment by retorquere** [comment]
That is correct -- I don't want to release a new version and have people being caught unawares by changing keys.

I'm prepping for a release that includes this and #541, which will most likely go out this weekend. You can use this in the interim, it will update once I put out a formal release.

**Comment by dmbortz** [comment]
Sounds good. thanks again!
