### ISSUE TITLE
Better BibLaTeX import improvements

### ISSUE THREAD

**Issue by mrgah** [retorquere/zotero-better-bibtex#549]
A few issues cropped up when I was trying to import a Biblatex file into Zotero with better-bibtex: 

- BBT ignores \mkbibemph{} and \mkbibquote{} commands
- 'thesis'-type items do not import as theses, but 'phdthesis'-type items do
- 'journaltitle' (the biblatex alias for 'journal') is not imported correctly
- 'inreference'-type items (i.e. entries in reference works) import as journal articles, not as book section items
- relatedly, 'collection'-type items import as journal articles, when they should probably be imported as books

Thanks!

**Comment by retorquere** [comment]
Can you attach a bibfile containing examples? I'll add those as test cases.

**Comment by retorquere** [comment]
@nickbart1980 I'm trying to put together an MWE compiling both csquotes and mkbibquote, but for the life of me, I'm not getting it to work. Can I bother you for a sample?

**Comment by nickbart1980** [comment]
Sure: https://www.sharelatex.com/project/57bbf30dd796406a5f7982c3

**Comment by retorquere** [comment]
Thanks @nickbart1980, this was driving me nuts.

@mrgah, I really still need your samples as test cases. Specifically the `thesis` that doesn't import right, as that's the one I can't explain yet, but I really want to add them all as test cases.

**Comment by retorquere** [comment]
The synthetic tests run green.

**Comment by mrgah** [comment]
Sure, here's an example of a thesis-type item that did not import correctly. I checked and, oddly, a number of _other_ thesis-type items did import correctly (I can provide examples of those if that would help). 

@Thesis{Bennett2003,
  Title                    = {Xenonika: medical texts associated with xenones in the late Byzantine period},
  Author                   = {Bennett, David Christopher},
  Date                     = {2003},
  Institution              = {University of London},
  Type                     = {Ph.D.},
}

**Comment by retorquere** [comment]
I'll add that to the tests and see what turns up. Can you also include samples of the other issues you described above?

**Comment by mrgah** [comment]
Sure.

An example of the \mkbibemph command: 

@Incollection{Cooper2013,
  Title                    = {Byzantium between East and West: Competing Hellenisms in the \mkbibemph{Alexiad} of Anna Komnene and her Contemporaries},
  Author                   = {Glen Cooper},
  Crossref                 = {Classen2013},
  Date                     = {2013},
  Pages                    = {263-87}
}

A journal article with the journaltitle field: 

@Article{Correns1891,
  Title                    = {Die dem Boethius fälschlich zugeschriebenen Abhandlung des Dominicus Gundisalvi {'De} unitate'},
  Date                     = {1891},
  Journaltitle             = {Beiträge zur Geschichte der Philosophie des Mittelalters},
  Pages                    = {1-11},
  Volume                   = {1},
  Editor                   = {Correns, Paul},
}

An example of the (somewhat weird) biblatex-chicago Inreference entry type:

@Inreference{Algar1985,
  Title                    = {Encyclopedia Iranica},
  Lista                    = {Besmallah: in exegesis, jurisprudence, and cultural life},
  Author                   = {Algar, Hamid},
  Date                     = {1985},
  Pages                    = {172-4},
  Volume                   = {4}
}

And finally, an example of the Collection entry type: 

@Collection{Arsdall2012,
  Title                    = {Herbs and Healers from the Ancient Mediterranean through the Medieval West: Essays in Honor of John M. Riddle},
  Date                     = {2012},
  Editor                   = {Anne van Arsdall and Timothy Graham},
  Location                 = {Burlington, VT},
  Publisher                = {Ashgate},
}

Thanks!

**Comment by retorquere** [comment]
@nickbart1980 is there a known domain that `Type` falls into?

**Comment by retorquere** [comment]
that is to say, is there a (reasonably) fixed list of values it is likely to take?

**Comment by retorquere** [comment]
Oops nm got it.

**Comment by retorquere** [comment]
Can you  try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.72-circle-2793.xpi ?

**Comment by retorquere** [comment]
It is really important for me to get feedback on how a change performs before I merge it to the main version.

**Comment by mrgah** [comment]
Alright, just did a fresh import, and almost all of these issues are resolved!

The only real outstanding issue is that, according to the biblatex-chicago spec, `Lista` in an `@Inreference` is actually the title of the article, while the `Title` field should map to Zotero's Book Title field. (See issue 4UPHPWUG, which I believe I've submitted correctly, for the Algar1985 cite specified above.) And of course, there's the underlying problem that Zotero's Encyclopedia Article and Dictionary Entry types do not map neatly on to the `Inreference` type, but that's not your problem.

**Comment by retorquere** [comment]
Ugh, that lista thing is a bear. I'll get it though. Many changes again.

So 4UPHPWUG is Algar1985 after you fixed it to your liking? That's perfect.

**Comment by retorquere** [comment]
OK, give https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.72-circle-2814.xpi a shot.

**Comment by mrgah** [comment]
Great! Algar1985 appears to be importing correctly now (or at least as correctly as the mismatch between Biblatex and Zotero item types will allow). Thanks!
