### ISSUE TITLE
Umlaut in author name - problematic?

### ISSUE THREAD

**Issue by cdriveraus** [retorquere/zotero-better-bibtex#550]
When I import this reference into zotero - http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4705270/ - and output to bibtex with better bibtex (output below), the umlaut in Sütterlin is not converted to {\"u} as I thought it should be. Consequently when I compile my document I get strange characters appearing.

@article{koval2016Emotional,
  title = {Emotional {{Inertia}} is {{Associated}} with {{Lower Well-Being}} when {{Controlling}} for {{Differences}} in {{Emotional Context}}},
  volume = {6},
  issn = {1664-1078},
  doi = {10.3389/fpsyg.2015.01997},
  timestamp = {2016-08-24T15:15:44Z},
  urldate = {2016-08-24},
  journal = {Frontiers in Psychology},
  author = {Koval, Peter and Sütterlin, Stefan and Kuppens, Peter},
  month = jan,
  year = {2016},
  pmid = {26779099},
  pmcid = {PMC4705270}
}

**Comment by retorquere** [comment]
The default for biblatex is not to translate these characters. You can change this default in the preferences. Bibtex will by default translate them.

**Comment by cdriveraus** [comment]
Ok, but I'm ouputting to bibtex - can you tell me where to find this option, I looked before posting the issue and just looked again...

**Comment by retorquere** [comment]
I've just tried and it translates as I would expect. Make sure you choose "Better BibTeX" and "Better BibLaTeX", and have Prefs->BBT->Export->Export BibTeX as ASCII checked.

**Comment by cdriveraus** [comment]
Perfect thank you. I don't recall turning the export as ASCII option off, but I guess it is possible.

**Comment by retorquere** [comment]
If you came to the current version from a very old version (like a year ago
I think), it might actually have botched this preference upgrade. For more
recent versions, the defaults are set this way, so I don't know how it
could flip other than by user action.
