### ISSUE TITLE
<pre> not working in Extra field

### ISSUE THREAD

**Issue by mortenbrons** [retorquere/zotero-better-bibtex#559]
Report ID: 8H9A39XE

In version 1.6.73, auto-updated on my computer August 31, 2016, what is between `<pre>` and `</pre>` is simply substituted with the string "undefined". This happens in the Extra field only, as far as I can see. In the Title field it works fine. I have used this construction extensively without problems previously.

**Comment by retorquere** [comment]
Can you right-click that reference and select "send BBT error"?

**Comment by mortenbrons** [comment]
Done; I get the following entry in the bibtex file:

@article{Brons:pretest,
  title = {$pretest$},
  author = {{Br\o{}ns}, Morten},
  note = {Hello undefined}
}


Fra: retorquere [mailto:notifications@github.com]
Sendt: 1. september 2016 16:46
Til: retorquere/zotero-better-bibtex
Cc: Morten Brøns; Author
Emne: Re: [retorquere/zotero-better-bibtex] <pre> not working in Extra field (#559)


Can you right-click that reference and select "send BBT error"?

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.73-circle-2838.xpi ?

**Comment by mortenbrons** [comment]
It works!
Thanks a lot for your lightning fast reaction. And thanks for a wonderful plugin that makes my life easier on a daily basis. Will this be a basis for an update?

Best wishes,
Morten


Fra: retorquere [mailto:notifications@github.com]
Sendt: 1. september 2016 18:19
Til: retorquere/zotero-better-bibtex <zotero-better-bibtex@noreply.github.com>
Cc: Morten Brøns <mobr@dtu.dk>; Author <author@noreply.github.com>
Emne: Re: [retorquere/zotero-better-bibtex] <pre> not working in Extra field (#559)


Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.73-circle-2838.xpi ?

**Comment by retorquere** [comment]
Yes, before tomorrow afternoon.

**Comment by retorquere** [comment]
A new release is out, upgrade will be automatic (but it's just a tagged version of what you have now)
