### ISSUE TITLE
arXiv duplicate fields when exporting to BibTeX

### ISSUE THREAD

**Issue by roberthannah89** [retorquere/zotero-better-bibtex#560]
A problem occurs when I import arXiv papers. So I import with Zotero connector. I use Better Bibtex to export a .bib file. This .bib file has duplicate information in the fields. E.g.

```
@article{DuchiChaturapruekRe2015_asynchronousa,
  title = {Asynchronous Stochastic Convex Optimization},
  eprinttype = {arxiv},
  eprint = {1508.00882},
  primaryClass = {math, stat},
  journal = {arXiv:1508.00882 [math, stat]},
  author = {Duchi, John C. and Chaturapruek, Sorathan and R{\'e}, Christopher},
  month = aug,
  year = {2015}
}
```

The result is that arXiv:1604.05649 [math] is repeated twice.

J. C. Duchi, S. Chaturapruek, and C. Ré, “Asynchronous stochastic convex optimization,” ArXiv:1508.00882
[math, stat], Aug. 2015. arXiv: 1508.00882 [math, stat].

Report ID: 6SX6GZQ6

**Comment by retorquere** [comment]
Can you right-click that reference and select "submit BBT error"? That will give me the reference as you have it in Zotero.

**Comment by roberthannah89** [comment]
NDMRF6F8

**Comment by retorquere** [comment]
If you export to BibLaTeX, you should get what you need. I'm going to guess that you process with BibLaTeX in any case, since BibTeX doesn't know about eprint fields so typically wouldn't render them.

@nickbart1980, is there anything sensible that can be done for BibTeX when it comes to arXiv?

**Comment by roberthannah89** [comment]
Yes. I'm using biblatex. My quick fix is just to suppress all eprint fields, and just have the "journal" field reflect that it's from arXiv.

**Comment by retorquere** [comment]
But were you exporting with better bibtex it with better biblatex?

**Comment by roberthannah89** [comment]
There's a better biblatex? Sorry, I had no idea this existed!

**Comment by roberthannah89** [comment]
Wait. Excuse me. What's the difference? It says Better Bibtex on Zotero.

**Comment by retorquere** [comment]
The full name of the extension is "Zotero Better Bib(La)Tex"; it packs a [bundle of translators](https://github.com/retorquere/zotero-better-bibtex/wiki/Bundled-translators), one of which is `Better BibTeX` which targets BibTeX and it's rather outdated feature set, and another is `Better BibLaTeX`, which is what you want to use if you can.

Some journals are stuck in the past though and demand BibTeX, which is why it's still an option, but since you are using biblatex, you will want to use the `Better BibLaTeX` exporter rather than the `Better BibTeX` from the dropdown when you export.

**Comment by retorquere** [comment]
(on the zotero site this extension may still be called "Better BibTeX", which is how it started out. I also still often use the BBT abbreviation, but its scope has gotten wider than just producing BibTeX)

**Comment by roberthannah89** [comment]
I see. Sorry about the confusion.

**Comment by retorquere** [comment]
No need to apologise. The issue tracker is specifically also for asking usage questions.
