### ISSUE TITLE
Information on JSON request to retrieve bibtex 

### ISSUE THREAD

**Issue by benoitdepaire** [retorquere/zotero-better-bibtex#561]
This bug report/feature request/question concerns:

* [x] BibTeX export
* [ ] BibLaTeX export
* [ ] Other

I am having trouble figuring out what the appropriate JSON scheme looks like to retrieve a bibtex export based on a set of keys, using HTTP POST to the better-bibtex server. I am trying to mimic to functionality of the zotero-citations plugin (also by retorquere) for an RStudio plugin. Using HTTP GET to pick my references from Zotero through better-bibtex works fine, but then exporting the appropriate bibtex file fails.

Based on my inspection of the zotero-citations plugin, I tried to send a POST request (in R, but this is irrelevant) to http://localhost:23119/better-bibtex/schomd, encoded the body as "json" and the body contained the following where "van_der_aalst_business_2013" is a  citation key in my zotero library.

```
{
  method:"citations",
  params: [
    ["van_der_aalst_business_2013"], 
   {style: "apa"}
  ]
}
```
I also tried to quote the key's in the JSON objects ("method", "params", "style" instead of _method_, _params_ and _style_), but this doesn't work either. 

When sending the POST request, I do get a response with status 200, but the body of the response consists of the following

```
$jsonrpc
[1] "2.0"

$error
$error$code
[1] 5000

$error$message
[1] "TypeError: req is null\nZotero.BetterBibTeX.endpoints.schomd.init@chrome://zotero-better-bibtex/content/web-endpoints.js:179:1\nZotero.Server.DataListener.prototype._processEndpoint@chrome://zotero/content/xpcom/server.js:412:4\nZotero.Server.DataListener.prototype._bodyData@chrome://zotero/content/xpcom/server.js:314:3\nZotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:286:3\nZotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:197:4\n"

$id
NULL
```

Anybody got an idea what is going wrong and can provide me with a valid JSON example? Thanks!

**Comment by retorquere** [comment]
I'm not familiar with `R`, but this works for me:

```
curl -X POST --data-binary '{"method" :"bibtex", "params": [ ["duchi_asynchronous_2015"] ] }' http://localhost:23119/better-bibtex/schomd
```

The data you post must be valid JSON; the schomd endpoint speaks [json-rpc](http://json-rpc.org/wiki/specification). In my implementation, the ID is optional; you'll get it back if you specify it, but it's safe to omit it.

**Comment by retorquere** [comment]
Sorry, that should have been 

```
curl -X POST --data-binary '{"method" :"bibtex", "params": [ ["duchi_asynchronous_2015"], {"translator": "betterbibtex"} ] }' http://localhost:23119/better-bibtex/schomd
```

When the translator is omitted, it defaults to biblatex.

**Comment by benoitdepaire** [comment]
Thanks,

I managed to get it to work with your curl command. I added the -v flag to see what was being sent to the server and did the same thing in my R-code. Apparently, the R code was not setting the content-type (correctly), which made it fail.

Thanks for the support and the great code!

B.

**Comment by retorquere** [comment]
I'm surprised the content-type had any effect (I don't check for it), but if it works, it works.
