### ISSUE TITLE
Biblatex extended name format

### ISSUE THREAD

**Issue by nickbart1980** [retorquere/zotero-better-bibtex#566]
Biblatex (or rather biber) supports an extended name format now (see the biber 2.6 manual), with improved support for particles/prefixes – among others:

- per-name (rather than per-entry) options for `useprefix` (and `juniorcomma`)
- explicit specification of name parts, so particles that could not be parsed in the old format (“’s-”, “’t-”) can be used now

BBT should start using this format, at least for names containing particles, and where comma-suffix=true

Example mappings CSL → biblatex:

- `[van Gogh][Vincent]` → `AUTHOR = {family=Gogh, given=Vincent, prefix=van, useprefix=true}`
- `[Humboldt][Alexander von]` → `AUTHOR = {family=Humboldt, given=Alexander, prefix=von, useprefix=false}`
- `[Bennett][Frank G.,! Jr.]` → `AUTHOR = {family=Bennett, given=Frank G., suffix=Jr., juniorcomma=true}`

Per-*entry* options, e.g., `OPTIONS = {useprefix=true}` should no longer be used for names.

I see two options for BBT:

1. Use the extended name format across the board.

2. Use it only if names contain any particles, or comma-suffix=true.

    This is possible, and might reduce clutter, since traditional BibTeX name formats and the extended form may be used together:

    `AUTHOR = {Harman, Jr., Hans and given=Simon, prefix=de, family=Beumont}`

One caveat: Though there appear to be *no* real names with both a non-dropping and a dropping particle, citeproc-js *will* parse, e.g., [la Doe][John de] into a name containing both. Neither the old nor the new biblatex format can handle this, so BBT will at least have to emit a warning. (Currently BBT puts both into the biblatex equivalent of a non-dropping particle.)

**Comment by retorquere** [comment]
When you say "now", how recent is this? Is this in wide enough circulation to make this safe to use always, or should this be another setting?

**Comment by retorquere** [comment]
This is just a month or so old, right? That means it'd become an option, I can't assume everyone has upgraded or can upgrade even.

**Comment by nickbart1980** [comment]
It’s in the official texlive distro, so those who run regular updates should have it. The biber manual says “Version biber 2.6 (biblatex 3.5) 10th September 2016”.

**Comment by retorquere** [comment]
This has no extra braces around parts of names, ever?

**Comment by nickbart1980** [comment]
The biber manual says “Compound parts *may* be protected with braces: `AUTHOR = {given={Jean Pierre}}`” (my emph.) – but apparently that’s not a requirement.

**Comment by retorquere** [comment]
Can you take a look at  https://github.com/retorquere/zotero-better-bibtex/blob/565%2B566/test/fixtures/export/Do%20not%20caps-protect%20name%20fields%20%23384%20%23565%20%23566.biber26.biblatex ?

**Comment by nickbart1980** [comment]
Looks good, but add `suffix=III` to `stevenson`, and in `medici`, use `prefix=de’\mbox{}`.

There’s also a problem with `given={\relax Ph}ilippe`, reported at https://github.com/plk/biblatex/issues/492; let’s see what the biblatex people say.

**Comment by retorquere** [comment]
That would also make the regular (non-extended) BibLaTeX export for medici `author = {de’\mbox{} Medici, Lorenzo},`, correct?

```
diff --git a/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biber26.biblatex b/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biber26.biblatex
index 361d71a..c77f1d7 100644
--- a/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biber26.biblatex	
+++ b/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biber26.biblatex	
@@ -24,7 +24,7 @@
 }
 
 @book{stevenson,
-  author = {family=Stevenson, given=Adlai E., juniorcomma=true},
+  author = {family=Stevenson, given=Adlai E., suffix=III, juniorcomma=true},
   note = {[Stevenson][Adlai E.,! III]}
 }
 
@@ -184,7 +184,7 @@
 }
 
 @book{medici,
-  author = {family=Medici, given=Lorenzo, prefix=de’ , useprefix=false},
+  author = {family=Medici, given=Lorenzo, prefix=de’\mbox{}, useprefix=false},
   note = {[Medici][Lorenzo de’U+200B]}
 }
 
diff --git a/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biblatex b/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biblatex
index b853604..97155c3 100644
--- a/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biblatex	
+++ b/test/fixtures/export/Do not caps-protect name fields #384 #565 #566.biblatex	
@@ -189,7 +189,7 @@
 }
 
 @book{medici,
-  author = {de’​ Medici, Lorenzo},
+  author = {de’\mbox{} Medici, Lorenzo},
   note = {[Medici][Lorenzo de’U+200B]}
 }
 ```

**Comment by nickbart1980** [comment]
Correct.

**Comment by retorquere** [comment]
OK, tests run green again. Wait until plk reacts before merge?

**Comment by nickbart1980** [comment]
Yeah, I think so.

**Comment by nickbart1980** [comment]
https://github.com/plk/biblatex/issues/492#issuecomment-252376754:

> This was a bug. You can do this now with biber 2.7 DEV and biblatex 3.7 DEV by using the usual brace protection:

> `author = {family=Duchamp, given=Philippe, given-i={Ph}},`

**Comment by retorquere** [comment]
OK, tests run green. Suggestions on how to name the corresponding preference?

**Comment by nickbart1980** [comment]
The biblatex and biber manuals call it the “extended name format”, so maybe:

“Use BibLaTeX extended name format”

or:

“Use BibLaTeX extended name format (requires biber 2.6 and biblatex 3.5)”

or (since biblatex 3.5 won’t work without biber 2.6 anyway):

“Use BibLaTeX extended name format (requires biblatex 3.5)”

Not sure if further explanations are required. Currently, it only makes a real difference for creator lists that contain both DP- and NDP (or juniorcomma-true and -false) creators; the old biblatex name format couldn’t handle such cases.

**Comment by retorquere** [comment]
Done. Tests are green, I'm merging this into master.
