### ISSUE TITLE
Support asciidoctor-bibtex format

### ISSUE THREAD

**Issue by ProgramFan** [retorquere/zotero-better-bibtex#567]
Hi, I am the author of [asciidoctor-bibtex](https://github.com/asciidoctor/asciidoctor-bibtex). asciidoctor-bibtex add modern citation support to asciidoc documents. It would be nice for better-bibtex to support "cite-as-you-write" for asciidoctor-bibtex enabled asciidoc documents.

The citation syntax of asciidoctor-bibtex is `cite:[KEY1(pretext), KEY2(pretext), KEY3, ...]`. And I can easily construct it using `curl -s -G http://localhost:23119/better-bibtex/cayw --data-urlencode "citeprefix=cite:[" --data-urlencode "citepostfix=]"`. But it is much verbose for end-users and does not support pretext (usually something like `p88`). So I would like to see a `format=asciidoctor-bibtex` in BBT.

I would like to help making this feature in good shape. Unfortunatelly, I have no experience developing firefox extensions and so not able to provide a PR.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-2925.xpi ? the cayw url will be `http://localhost:23119/better-bibtex/cayw?format=asciidoctor` and you can add `&cite=citenp` if you want no the `citenp` form.

Asciidoctor-bibtex has no suppress-author support?

**Comment by ProgramFan** [comment]
Hi, @retorquere , thanks for your quick response and work.

I installed the above version and `curl -s http://localhost:23119/better-bibtex/cayw?format=asciidoctor` returns nothing on stdout. How can I investigate it?

Asciidoctor-bibtex only supports pretext currently, no suppress-author is implemented. BTW, I suggest we use `asciidoctor-bibtex` instead of `asciidoctor` as the format name, since asciidoctor-bibtex is an asciidoctor extension and the grammar is not included in asciidoc core grammars. However, I can personally accept `format=asciidoctor`.

**Comment by ProgramFan** [comment]
BTW, I tried other formats and still encountered the above no-output problem.

**Comment by retorquere** [comment]
Right, sorry about that, try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-2936.xpi

I've changed the format to `asciidoctor-bibtex`, but it seems a bit superfluous, no? What other asciidoctor extensions are going to call BBT? In any case, no difference to me.

Let me know if this does what you want, and I'll merge and release.

BTW, for future reference, what asciidoctor-bibtex calls a pretext Zotero calls a `locator` (as in, location within the document referenced), it'd be easier for me to keep to that terminology. Currently the cayw picker will return `<citekey>(<pagenum>)` if you picked a page, but will prefix with a designator such as `ch.` if you picked a chapter for example, so it'd look like `<citekey>(ch. <chapnum>)` in that case.

**Comment by ProgramFan** [comment]
The above version works perfectly.

A little explanation to the name: there is another asciidoctor extension `asciidoc-bib` adding bibtex citation to asciidoc documents. But its citation grammar is inspired by that of pandoc and does not follow the asciidoc grammar convention. Users may want to use it so calling my extension `asciidoctor-bibtex` is necessary, although a bit superfluous.

**Comment by retorquere** [comment]
I've merged this and will cut a new release in the next few days to bundle some other fixes.
