### ISSUE TITLE
CSL status → biblatex pubstate

### ISSUE THREAD

**Issue by nickbart1980** [retorquere/zotero-better-bibtex#573]
It would be great if BBT could export the the CSL `status` variable, in Zotero currently only available via the “cheater syntax” in the Extra field, e.g., `{:status:forthcoming}` or `status: forthcoming`, to the biblatex `pubstate` field.

**Comment by retorquere** [comment]
Can you right-click a reference that has this and select "Send BBT error"? That will get me a test case

**Comment by nickbart1980** [comment]
RRGS493D – thank you.

**Comment by retorquere** [comment]
[this](https://github.com/retorquere/zotero-better-bibtex/blob/573/test/fixtures/export/CSL%20status%20%3D%20biblatex%20pubstate%20%23573.biblatex) then yeah?

**Comment by nickbart1980** [comment]
Exactly.
