### ISSUE TITLE
Add a Quick Copy Gitbook mode

### ISSUE THREAD

**Issue by davy39** [retorquere/zotero-better-bibtex#574]
Hi,
 I would like to use zotero+bbt with [Gitbook](https://www.gitbook.com/editor/), since there are some [bibtex plugins](https://plugins.gitbook.com/browse?q=bibtex) like [this one](https://plugins.gitbook.com/plugin/bibtex).

Could you please add a Quick Copy Gitbook mode in order to export in the following format ?

**{{ "**citation-key**" | cite }}**

By the way, many thanks for your work which is very appreciated !

**Comment by retorquere** [comment]
Can you give a concrete example? I'm not sure whether the quotes should be there verbatim or whether they indicate is is only a placeholder, and I do really know what the bold means to say. You can add literal stuff to github issues by enclosing it in single backticks (inline text) or triple backticks (larger chunks of text)

**Comment by davy39** [comment]
Thanks for you very fast answer, and sorry not to be clear...
For example if `Meirieu2006` is the citation key, I would like BBT to Quick copy `{{ "Meirieu2006" | cite }}`.

**Comment by retorquere** [comment]
What is the expected format if more than one reference is selected?

**Comment by davy39** [comment]
I just add a try with multiple entries, it looks like the bibtex plugin doesn't support them...
So it would be better to format them this way : `{{ "Meirieu2006" | cite }}{{ "Meirieu2009a" | cite }}{{ "Meirieu2009b" | cite }}`

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3089.xpi

**Comment by davy39** [comment]
Thanks for this, I tried it and here are the results : 
- I had to disable ZotFile because of this error : 

> Better BibTeX has been disabled because it has detected conflicting extension "ZotFile" 4.2.5 or earlier. After upgrading to 4.2.6, Better BibTeX will start up as usual. A pre-release of ZotFile 4.2.6 can be found at https://addons.mozilla.org/en-US/firefox/addon/zotfile/versions/

Even after upgrading to 4.2.6 (and restart firefox), I still get the message.

- I realised that drag and drop doesn't work with Gitbook (running Linux Mint), but anyway ctr+shift+C -> paste is already a great improvement.

I'm going to look for way to get this drag and drop functionality.
Many thanks for your great work !

**Comment by retorquere** [comment]
I don't get any errors when I have ZotFile 4.2.6 installed. Can you enable advanced debugging in the BBT prefs, restart firefox, and select "Send Better BibTeX Error report" from the Zotero gear menu?

Not all applications support D&D of Zotero references I've found, but in these cases it's not specific to BBT. I'm not entirely sure how Zotero does D&D, it calls a translator (in this case BBT quick copy) and does some magic with the results -- after result generation, BBT is out of the loop, and Zotero does the work. If ctrl-shift-C (or was that ctrl-shift-A?) works, there's nothing more I can do.

**Comment by retorquere** [comment]
I've tried installing 4.2.5 (BBT disables itself) and letting it upgrade to 4.2.6 and reinstall (no more error). If you fully restart Zotero, do you again get the disable warning?

**Comment by davy39** [comment]
Nothing to do I cannot enable both ZotFile & BBT. I did an error report CMRPBMX2.

The D&D problem is indeed from GitBook IE since they're struggling with some copy/paste issues : https://github.com/GitbookIO/feedback/issues/155

**Comment by retorquere** [comment]
Looking at that log, Astrill throws an error, and BBT apparently doesn't even get to the point where it lists the existent plugins. Can you disable Astrill and try again?

**Comment by retorquere** [comment]
Where did you get Astrill Proxy Switcher from? I can't find it.

**Comment by retorquere** [comment]
Can you enable extended debugging in BBT, install [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3094.xpi) (and restart) and submit a new debug log? There's another user that's experiencing this (#551) with Zotfile, but I haven't yet been able to reproduce the problem at my end. This build will explicitly report what version of Zotfile it thinks is installed.

**Comment by retorquere** [comment]
There's a new version out [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3095.xpi) that will give better reporting.

**Comment by retorquere** [comment]
Since #551 also has this problem I'm starting to doubt whether the error caused by Astrill is interfering with BBT, but Astrill support says "That add-on is obsolete in the new version of Astrill application and is no more available in Add-ons for Firefox.", so perhaps it'd be a good idea in any case to remove Astrill altogether.

**Comment by retorquere** [comment]
I think I found the problem -- if you could try [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3095.xpi) to verify it works, I can merge & release.

**Comment by davy39** [comment]
Concerning Astrill, I think I've never used the addon but I suppose that it comes from [the bundle](https://www.astrill.com/download.php) I downloaded a while ago. I noticed it as well in the log and disabled it without success.
Indeed, your last post solved my issue. So many thanks for your support !

**Comment by retorquere** [comment]
Super, final tests are running, if they go green I'm cutting a release.
