### ISSUE TITLE
better bibtex disabled on ZSA

### ISSUE THREAD

**Issue by mclearc** [retorquere/zotero-better-bibtex#575]
I'm using Zotero standalone 4.0.29.15 and the most recent version of BBT. After installing Zotero standalone and BBT on a fresh machine I get "Better BibTeX has been disabled because neither Zotero nor Juris-M are installed" in the preferences. I'm not sure what the problem is. I have the data directory for Zotero standalone in a custom location, while the BBT extension is located in (I'm on OS X) ~/Library/Application Support/Zotero/Profiles/<random number>/extensions. Perhaps it needs to be in the custom directory? I've tried that though and it doesn't seem to work. Zotero only recognizes extensions in Zotero/Profiles/.../extensions. Any ideas?

**Comment by retorquere** [comment]
On it, cause found.

**Comment by retorquere** [comment]
Can you  try this: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.76-circle-3104.xpi

**Comment by mclearc** [comment]
It worked initially. Then I added some other plugins (e.g. Zotfile) and it seems to have broken again. I'd send you the debug, but I'm again getting only "Better BibTeX has been disabled because neither Zotero nor Juris-M are installed" in the preferences. I should say also that I reverted to a backup of my `Profile` directory and everything works fine there (including Zotfile).

**Comment by retorquere** [comment]
Which zotfile version did you install? And what OS are you on?

**Comment by mclearc** [comment]
I'm on OS X Sierra (which may itself be part of the problem). The Zotfile is recent. I downloaded it a few days ago from the Zotfile homepage. I've reverted back to the prior `Profile` and everything appears to be working again.

**Comment by retorquere** [comment]
I'm on Sierra myself. I'm running tests on a version that won't disable if no Zotero/Juris-M is installed (it's a harmless situation even if it would occur), which will allow normal debug reports to be sent. While that runs (circleCI is sloooow right now) you should be able to view the debug log from the Zotero preferences in the advanced pane, maybe there's something that sticks out. If not, a full startup log can be generated by fully closing Zotero (cmd-Q), starting a terminal, and typing

```
script
/Applications/Zotero.app/Contents/MacOS/zotero-bin -app /Applications/Zotero.app/Contents/Resources/application.ini -ZoteroDebug
exit
```

the log will be in a file called `typescript`. But a non-disabling version should be only 10 minutes or so out.

**Comment by mclearc** [comment]
Ok. I'm really not sure what is going on. I deleted then reinstalled the version you linked to me. Things seem to be working now, including with at least Zotfile enabled. I just submitted the debug log: VVQCX3FM. Sorry that I can't be of more help.

**Comment by retorquere** [comment]
this won't disable on account of no Zotero/Juris-M: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.76-circle-3107.xpi

Curious what else it complains about, because it's fairly obvious Zotero is installed in ZSA 😕

**Comment by retorquere** [comment]
Ah, we just crossed our messages. I'll look at that log.

**Comment by mclearc** [comment]
Just to clarify -- I got BBT working again with the version *prior* to that linked just above.

**Comment by retorquere** [comment]
Exactly nothing in that log... ah well, it works now, .77 should be released in about 10 minutes after the tests have ran.

**Comment by mclearc** [comment]
Thanks for trying in any case. I'll close the thread. Hopefully when I update this time Zotero won't decide to go loopy again.

**Comment by retorquere** [comment]
Well you found a genuine bug -- BBT would indeed deem ZSA non-Zotero, so I'm glad you reported that quickly. It's BBT that's being loopy, but .77 will take care of the problem you initially found. The transient problem after that... I don't know, but when it reappears, don't hesitate to call back in.

You'll be updated to .77 somewhere tomorrow (Firefox checks for extension updates once a day by default), but you can force it by checking for updates in the addons pane under the gear menu (when it releases -- hurry up circle!). .77 is just a tagged version of what you have already though.
