### ISSUE TITLE
Use without Zotero?

### ISSUE THREAD

**Issue by mlinchitstest** [retorquere/zotero-better-bibtex#577]
Would you consider making this runnable without the Zotero desktop program? This would be very useful on a web server, to get data from Zotero through the web api and translate that to bibtex, while at the same time using the keys defined in the "extra field". Something like that could be for wikis and a bunch of other web applications.

**Comment by retorquere** [comment]
It's not impossible, but since BBT (re)uses a lot of the Zotero internals, it'd be a long-term project to stub those out.

**Comment by mlinchitstest** [comment]
thanks for the update. there already exist utilities of the type I described. The only problem is that they generally don't care what key BBT puts in the `extra field`, which is pretty annoying.

**Comment by retorquere** [comment]
That's not all that BBT does though. The work to produce acceptable Bib(La)TeX from Zotero references has turned out to be pretty involved.

**Comment by retorquere** [comment]
I've given it a go but it's not really feasible.
