### ISSUE TITLE
Problem exporting Library

### ISSUE THREAD

**Issue by stfl** [retorquere/zotero-better-bibtex#578]
I cannot export my whole zotero library to better bibtex

report id: MKAIKVHN

I am running zotero-standalone on Debian.
The Error "An error occurred while trying to export the selected file." appears when trying to export through Files -> Export Library

**Comment by retorquere** [comment]
This appears to be the same problem as #576; could you please join that issue?

**Comment by stfl** [comment]
how do I join this issues?

**Comment by retorquere** [comment]
As soon as you post any response in an issue you become subscribed there.

**Comment by stfl** [comment]
thank you. I clicked subscribe, which I guess should do the same ;)

**Comment by retorquere** [comment]
Indeed it does.
