### ISSUE TITLE
[JavaScript Error: "TypeError: collection.getChildItems is not a function" {file: "chrome://zotero/content/xpcom/translation/translate_item.js" line: 763}]

### ISSUE THREAD

**Issue by stfl** [retorquere/zotero-better-bibtex#579]
When exporting a group the progress bar never disappears. 

Report ID: UH65RMBF

```
[JavaScript Error: "TypeError: collection.getChildItems is not a function" {file: "chrome://zotero/content/xpcom/translation/translate_item.js" line: 763}]
Zotero.Translate.ItemGetter.prototype.setCollection@chrome://zotero/content/xpcom/translation/translate_item.js:763:21
Zotero.Translate.Export.prototype._prepareTranslation@chrome://zotero/content/xpcom/translation/translate.js:2219:4
Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1214:3
Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1189:58
Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1574:16
Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1189:4
Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:2265:3
Zotero_File_Exporter.prototype.save@chrome://zotero/content/fileInterface.js:96:3
Zotero.BetterBibTeX.exportGroup@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:1130:10
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

```

**Comment by retorquere** [comment]
This is when right-clicking a collection and exporting? In Zotero standalone? Or is this when exporting a shared collection?

**Comment by stfl** [comment]
a shared collection "export group"

**Comment by retorquere** [comment]
Can you get me a screenshot of what you're trying to export? I'm afraid I still misunderstand, and I can't reproduce the error.

**Comment by stfl** [comment]
![export group](https://cloud.githubusercontent.com/assets/1321542/19485457/89874d50-955b-11e6-8065-fa3fd86438bd.png)

**Comment by retorquere** [comment]
I tried that and it just worked for me on two different systems, on two different OSes. Bugger!

There is a chance that you've been bitten by the same problem that seems to underlie #576 -- I expect to get confirmation on that soon, but you could try whether [that version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.77-circle-3117.xpi) works for you.

**Comment by retorquere** [comment]
(oh hey, it's you 😳 )

**Comment by stfl** [comment]
3117 doesn't work here.. 
[3117-group.txt](https://github.com/retorquere/zotero-better-bibtex/files/538310/3117-group.txt)

**Comment by retorquere** [comment]
Bummer. There's no error in that log though -- what error are you seeing?

**Comment by stfl** [comment]
the prograss bar is running in circles.. infinatly
errors as shown in 1st post, taken from report error to zotero..

**Comment by duncdrum** [comment]
there has been a long standing zotero issue with permissions of individual items / attachments in group libraries. The spinning circle of doom, sounds familiar from that one. Just in case, can you test with a new group in which you are certain to have full permission of all items.

**Comment by retorquere** [comment]
@stfl the reason I was asking is that that error ("collection.getChildItems is not a function") is not in  3117-group.txt.

I have tried to reproduce this with various permissions on the group member, with ZSA and ZF, but I'm not seeing this error.

Hold on, can you try "Export library" on that group, rather than "Export group"?

**Comment by retorquere** [comment]
I think I have it reproducible. More tests ongoing.

**Comment by retorquere** [comment]
OK, I think I have it: I implemented "Export Group" because for a while, Zotero didn't have an export option for group libraries, just for collections within those. Zotero does now have this option, so it appears to be superfluous. Can you verify that "export library" does what you want? Then I can just remove "export group" (which for me also just gets stuck).

**Comment by retorquere** [comment]
(waiting for this to merge & release #576)

**Comment by stfl** [comment]
Export library works for this purpose like in #576 
Thank you

**Comment by retorquere** [comment]
OK, new release is out.
