### ISSUE TITLE
transliteration for citekey

### ISSUE THREAD

**Issue by mlinchitstest** [retorquere/zotero-better-bibtex#580]
if you use non-english sources, the citation key becomes ??? or blank. the only way to fix it is to manually change the key (even the MKZ fork won't help here, as far as I can tell). are there any plans to implement transliteration? thanks

**Comment by retorquere** [comment]
What is your citation key pattern?

**Comment by mlinchitstest** [comment]
i've tried `[zotero]` and `[auth][year]`.  Tried `Force ASCII` on/off. observed with citations in Cyrillic, Chinese etc. I'm assuming this is expected behavior.

**Comment by retorquere** [comment]
`[auth][year]` should already do transliteration, and `force ascii` ought to force that once over. Can you try the following:

1. In BBT prefs/advanced, enable extended debugging
2. Install https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.77-circle-3112.xpi
3. after Firefox restarts, change the reference in any way so that BBT will try to regenerate the key
4. Right-click that reference and select "Send Better BibTeX error report"
5. Post the red debug ID you get here

**Comment by retorquere** [comment]
BTW, translit for Cyrillic and Chinese could be tricky -- maybe it's just those languages that don't transliterate properly. If you can get me a reference that doesn't get what you want I can investigate -- for that, you can just do steps 4 + 5 with the version of BBT you already have, that will send me the reference.

**Comment by mlinchitstest** [comment]
Indeed diacritics are handled just fine (tried Vietnamese). But anything with an entirely different character set is not:
Reported on standalone: XQBUVKWR
Reported on experimental install of "jurist-M" in firefox: X7TQ7WBB

**Comment by retorquere** [comment]
You can try [this version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.77-circle-3126.xpi). Do note that the reference you sent in the debug report has a fixed citation key in the `extra` field, so it won't generate a new key unless you remove that.

**Comment by mlinchitstest** [comment]
Thanks! That works GREAT. (minor issue is that, even after accepting to clear the cache, the old keys apparently remain —you apparently have to change the citekey pattern then change it back again to have everything refresh)

**Comment by retorquere** [comment]
The cache is only for speeding up exports; only a reference change or a pattern change will affect already-generated keys. I think I once had it so after an upgrade it would regenerate, but for that would mean you could accidentally and without warning change many keys, which could introduce breakage in articles you already finished which relied on those keys.

**Comment by retorquere** [comment]
new release it out. Note that `[zotero]` will only use the transliteration if you have 'force to ascii' on.
