### ISSUE TITLE
Automatic add-on update disables BBT for Juris-M users: upgrading BBT restores support

### ISSUE THREAD

**Issue by duncdrum** [retorquere/zotero-better-bibtex#581]
Automatic add-on update pulls BBT 1.6.77

which results in: 
```Better BibTeX has been disabled because it found Juris-M 4.0.29.12.97, but requires 4.0.29.12m98 or later.```

Juris-M 4.0.29.12.97 is the latest stable release, as of posting. Using os X 10.11.6 and FF 49.0

**Comment by retorquere** [comment]
m97 introduced a [bug](https://github.com/Juris-M/zotero/issues/24) that breaks BBT. Juris-M [m98beta2](https://github.com/Juris-M/zotero/releases/tag/v4.0.29.12m98beta) fixes the bug and is currently the only version that is compatible with BBT -- I'm waiting for the fix to be released into a new Juris-M version. I've put up a BBT version that will accept m97 [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.77-circle-3123.xpi), but be advised that this combination does not pass the BBT test suite. Most things will work in this combo, but I don't generally like to put out versions that don't pass my test suite.

I could make a version that also accepts m95, but if you install m95 you'd just be upgraded back to m97 again in a day.

**Comment by duncdrum** [comment]
I see, i ll hold before installing the beta, as long as i can. Just to make sure that during the regular upgrade path the extra field info (yes I use it too) remains intact. Shall we leave this open so its easier to find for other users taken by surprise.

**Comment by retorquere** [comment]
None of your references will be touched regardless of what you do; none of the combos will mess with your references. The deletion that is mentioned in the Juris-M thread relates only to how a copy of the reference is handed to BBT, never your references as you've stored them in Juris-M.

**Comment by retorquere** [comment]
I'm going to cut a new release which will complain but accept m97. I can't really fix any problems that may occur on m97 though -- there's a change particular to m97 which makes that I can't run my tests, and I need to be able to run my tests. Just waiting for #579 to clear.
