### ISSUE TITLE
Missing items in right-click menu

### ISSUE THREAD

**Issue by specter119** [retorquere/zotero-better-bibtex#584]
Report ID: 5HXD957M

I found some items in right-click menu is ‘nearly’ missing (e.g. export collection). The missing items can be select in a very narrow width with no fonts.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3136.xpi ?

**Comment by simonkeys** [comment]
I'm having the same issue -- I tried the update, but it doesn't seem to solve it. 

I'm on Mac OS X 10.10.5.

**Comment by retorquere** [comment]
Can you submit a debug log using 1.6.78-circle-3136 after calling up the menu, and attach a screenshot of what you're seeing?

**Comment by specter119** [comment]
@retorquere 1.6.78-circle-3136 works well

**Comment by retorquere** [comment]
@simonkeys, how about you? Which update did you mean?

**Comment by simonkeys** [comment]
My mistake, I had updated the extension in Firefox, but I was using the standalone version. 1.6.78-circle-3136 fixes the problem for me, too.

**Comment by retorquere** [comment]
OK, super, I've merged this and will release as soon as #585 clears.

**Comment by retorquere** [comment]
.79 is out
