### ISSUE TITLE
"null translator" in webserver export

### ISSUE THREAD

**Issue by tobi2185** [retorquere/zotero-better-bibtex#586]
Until yesterdays update the web server export via my library was working flawless. When I want to assess the collection now, I just get the message "null translator".

Report ID: D7HKIX8X
BibLaTeX

Thanks anyway for the great tool!

**Comment by retorquere** [comment]
I have it reproducible, working on it.

**Comment by retorquere** [comment]
As a matter of fact I have a fix, but my test/release service (circleCI) suffers the fallout of a DDOS attack. If you're in a hurry you can try https://transfer.sh/119kjw/zotero-better-bibtex.xpi -- the change was very isolated, but I have not been able to run the usual test suite on it.

**Comment by tobi2185** [comment]
Thank you so much for the quick fix! It´s working again!

**Comment by retorquere** [comment]
.79 is out

**Comment by dbobak** [comment]
In some cases, the web server still has errors:

1. When trying to access entire library:
URL: http://localhost:23119/better-bibtex/library?library.biblatex
gives error: Could not export bibliography 'library.biblatex': TypeError: Zotero.BetterBibTeX.Translator is undefined

2. When collection has a "&" in its name, the second version of URL does not work:
collection name: &Subjects
URL: http://localhost:23119/better-bibtex/collection?/0/34FCFCKT.biblatex works
URL: http://localhost:23119/better-bibtex/collection?/0/&Subjects.biblatex
gives error: Error: Could not export bibliography 'Subjects.biblatex': ReferenceError: collectionkey is not defined.

**Comment by retorquere** [comment]
Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.79-circle-3180.xpi

**Comment by dbobak** [comment]
3180 works like a charm :) Thank you!
