### ISSUE TITLE
sudden incompatibility with zotxt

### ISSUE THREAD

**Issue by emelin** [retorquere/zotero-better-bibtex#589]
Since very recently, I noticed that zotero-better-bibtex causes certain problems while using 

    https://github.com/egh/zotxt

A request like this:

    http://127.0.0.1:23119/zotxt/items?key=0_7KAENGFZ&format=key

does still work, but when choosing another format like: 

    http://127.0.0.1:23119/zotxt/items?key=0_7KAENGFZ&format=betterbibtexkey

or 

    http://127.0.0.1:23119/zotxt/items?key=0_7KAENGFZ&format=easykey

then Firefox will not return any result!

If I disable zotero-better-bibtex, zotxt works as expected again. 
So I guess and hope to report the issue to the right address here.

Thank you for taking care of all this amazing features of this extension!

**Comment by emelin** [comment]
Thank you for this quick answer. 
I reported the issue to @egh at gitlab: 
    https://gitlab.com/egh/zotxt/issues/43

Hopefully tings can be resolved soon.
In the meantime however, it would be great, if I could simply switch back to a previous version of zotero-better-bibtex. I tried to do this, but I didn't succeed.

Would you know, what I would need to do, to get the old functionality back, at least temporarily?

Thank you for another quick answer.

**Comment by retorquere** [comment]
You'd have to download an older bbt version from https://github.com/retorquere/zotero-better-bibtex/releases, and disable automatic updates on the extension settings. Disabling auto updates is not something I'd recommend, but if not you'd just be upgraded in a day. 

You'll understand I can't accept bug reports on older bbt versions. If you want support, you'll need to be back on the latest version.

**Comment by emelin** [comment]
Of course, I understand perfecly that there can be no support and I am happy to receive an answer at all on these matters!

Thank you for describing the steps of downgrading to an earlier version.
Yet, this is exaclty what I did and now tried again going even back to version 1.6.69. I also tried to combine the downgrading with an older version of firefox, noteably 48.0.

However, whatever combination I used, the old behaviour is not restored! 
I also tried to do a cache reset -- but no difference. 
Only if I disable zotero-better-bibtex, then zotxt works again as expected.
Could it be that the database hase been changed permanently, or there are some other files affected that I would need to replace?

Sorry, for bothering once more with this issue. I surely wouldn't, if I would not depend on the workflow so nicely made possible by the cooperation of thses two extensions.

**Comment by retorquere** [comment]
No bother. 

The Firefox version shouldn't matter, and the database structure hasn't changed in a while. If you didn't get any notice, the cache would have been reset automatically (and the cache wouldn't have affected zotxt, it's not reading the cache). 

If you enable extended debugging and submit a debug report, I can have a look. I can look up later tonight what version most likely still worked with zotxt, but I'm currently commuting.

**Comment by emelin** [comment]
That's extraordinary kind of you!

All right, I am back at Firefox 49.0.2 but with an older version of zotero-better-bibtex installed, namely 1.6.69.

The extended debug report was given the reference:  MUFAB8VI 

In 3 different browser tabs, I repeated the same 3 requests as in my first post with exactly the same result as reported above.

Hope that might tell you something.
Thanks for spending your time on that issue!

**Comment by retorquere** [comment]
I think 1.6.74 was the last version before `Zotero.BetterBibTeX.translators` was replaced. `MUFAB8VI` has no errors that relate to zotxt or bbt.

**Comment by retorquere** [comment]
(extended debugging wasn't on when `MUFAB8VI` was sent though, so there's not too much I can tell from that log)

**Comment by emelin** [comment]
Ok. I'll immediately repeat that.
But I guess something really crazy is going here:
While testing a minimal setup with Firefox zotero and zotero-better-bibtex ONLY, I now get

    null translator
when requesting 

    http://localhost:23119/better-bibtex/collection?/0/RD9P2G2U.biblatex
which used to work perfectly.

The debug report is: 7FJQBZQM

Next post, will be with version 1.6.74 and right debug settings enabled.

**Comment by retorquere** [comment]
The `null translator` problem is #586 -- I'm trying to figure out #585 and will release those two together.

**Comment by emelin** [comment]
After what felt like a thousand restarts of Firefox, I am back on a working setup!

I can know certainly confirm, that 1.6.75 is the last working version. 
Interesting might be that issue #585 is also introduced by version 1.6.76 and they might indeed be considered connected.

Thank you again for answering all that amazingly quickly!
Good luck while debugging.

**Comment by emelin** [comment]
Zotxt has been updated to 0.1.35 and works well with zotero-better-bibtex 1.6.80.

All fine again!

**Comment by egh** [comment]
Thanks @retorquere and @emelin !
