### ISSUE TITLE
[Feature request] Using origyear in a custom citation key.

### ISSUE THREAD

**Issue by JohnLukeBentley** [retorquere/zotero-better-bibtex#591]
I've sent my Hume and Wenar entries, which I expand on below, as Report ID: B9GKHH82 
## BBT's custom citation key feature generally works well

At the moment I have a custom citation key ...

Zotero > Tools > Preferences > Better Bibtex > Citation Keys > Citation Key Format: `[Auth:condense,_:lower]_[year]_[veryshorttitle:lower]`

... and that works well enough.

So from a Zotero Entry of ...

```
Author: Wenar, Leif
Date: 2015-09-09
Title: Rights
Publication: The Stanford Encyclopedia of Philosophy
```

... BBT will use my custom citation key format to produce a Citation Key "wenar_2015_rights". Generally that's perfect.
## My desire for origyear handling

However, I also have some Zotero entries that include BBT custom fields, and the specific custom field `origdate`, a field which biblatex supports (and some third party biblatex style's support).  For example in Zotero I might have ...

```
Title: An Enquiry Concerning the Principles of Morals
Author: Hume, David
Book Title: Enquiries Concerning Human Understanding and Concerning the Principles of Morals
Date: 1975
Extra: bibtex[origdate=1751]
```

... which BBT will reliably export, complete with my custom citation key, as ...

```
@incollection{hume_1975_enquiry,
  author = {Hume, David},
  date = {1975},
  origdate = {1751},
  title = {An {{Enquiry Concerning}} the {{Principles}} of {{Morals}}},
```

However, for entries with an `origdate` (in addition to a `date`) I'd rather have a citation key that uses the `origyear`. In this example to produce "hume_1751_enquiry" rather than "hume_1975_enquiry".
## The call is for origyear rather than origdate as such

Note it's the `origyear` rather than `origdate` I'd be after. In Biblatex `origdate` is parsed out into relevant date parts `origyear`, `origmonth`, `origday`, etc. and made available for styles. In the Hume example there's no difference between `origyear` and `origdate`. However in something like, from Zotero ...

```
Author: Wenar, Leif
Date: 2015-09-09
Extra: bibtex[origdate=2005-12-19]
Title: Rights
Publication: The Stanford Encyclopedia of Philosophy
```

I'd want BBT to generate a citation key of "wenar_2005_rights" rather than "wenar_2005-12-19_rights" (nor would I want, as would occur with my current customization, "wenar_2015_rights"). That is, I'd like to end up with an export like ...

```
@article{wenar_2005_rights,
  author = {Wenar, Leif},
  date = {2015-09-09},
  origdate = {2005-12-19},
  title = {Rights},
  journaltitle = {The Stanford Encyclopedia of Philosophy},
```

[Edit: If I was citing this entry in a real article I'd probably only by interested in the latest date and not use `origdate` at all. But I include the example as you, as BBT dev, would probably need to programatically handle `origdate`s that include a full date, rather than merely a year.]
## What the solution might entail

I note from https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys

> ... in addition to the 'special' fields listed JabRef also allows all 'native' fields as key values; the [BBT] plugin does the same but allows for Zotero native fields (case sensitive!) not Bib(La)TeX native fields

And I don't think my feature request amounts to adding custom citation key support for Biblatex native fields, as such. Rather it perhaps amounts to a request for:
1. Adding custom citation key support for BBT custom fields (as inserted into Zotero's extra field with 'Bibtex[fieldname1=fieldvalue1;fieldname2=fieldvalue2; ...]'; and
2. A special handling of 'Bibtex[origdate=...]' such that BBT parses this and makes it available to custom citation key formatting as `origdate` (holding the full value) and `origyear` (holding just the year. I could see some future potential requests for parsing into other components `origmonth`, `origday`, etc - but for the moment that's nowhere part of my interest - I'm only interested in the year part (and perhaps the whole part of `origdate`).
## My motivations

Just to expose my motivations. Obviously I'm interested in writing articles where the original publication date is more important. So I'm wanting to end up with in-text citations and bibliographic entries that look like ...

> Lorem (Hume **1751**).
> 
> Hume, David. **1751**. "An Enquiry Concerning the Principles of Morals." In Enquiries Concerning Human Understanding and Concerning the Principles
> of Morals, 3rd ed., edited by L. A. Selby-Bigge and P. H. Nidditch. Note.
> New York: Oxford University Press, **1975-06-12**. [Bold added]

When writing in latex, and using a biblatex file, that this entry might have a modern date in the citation key, e.g. "hume_1975_enquiry", is not too great of a problem. In one's tex document this might be referenced as `\autocite{hume_1975_enquiry}` and the modern date is appropriately regulated, using one's chosen style vodooo, to a less important position on the rendered PDF output.

However, I'm attempting to identify, and if need be create, a toolchain that allows lightweight markup source documents (like markdown) to be transformed into various end user formats (pdf via latex, epub, html, Amazon Kindle). Pandoc looks promising here. In this context the readability of the source markup is more important than, say, the readability of a tex document. The whole motivation for using a lightweight source document is so that it can be handed around directly between non expert users. 

So, in the context of writing articles where the original date is more important, and that the writing will be an a lightweight markup language, I'd much rather have a citation key that uses the original year. 

Edit: Added edit as marked.
Edit: "the" to "that".

**Comment by JohnLukeBentley** [comment]
In the meantime a workaround can be used by leveraging the feature documented at https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#set-your-own-fixed-citation-keys

For example, in Zotero my Hume entry currently has a citation key `hume_1975_enquiry` and I want to end up with `hume_1751_enquiry`. To do this:

1. In Zotero right click on the entry > "Generate BibTex Key".  "bibtex: hume_1975_enquiry" will be appended to the Extra field (and so, excellently, does not interfere with existing values in the Extra field).
2. Manually edit "bibtex: hume_1975_enquiry" to be the desired key,  "bibtex: hume_1751_enquiry".
3. Tab out of the Extra field to save.
4. Click on some other entry. Click again on the Hume entry. This will refresh the Citation Key which now should be taking its value from the Extra Field "bibtex: hume_1751_enquiry". That is, the Citation Key should now be "hume_1751_enquiry".

**Comment by retorquere** [comment]
In BBT5 you will be able to use `[origyear]` in your pattern; `origyear` will be origyear if present, year otherwise; `year` the other way around.
