### ISSUE TITLE
Empty entries in the collection context menu after installing BBT

### ISSUE THREAD

**Issue by michaelpalmeruw** [retorquere/zotero-better-bibtex#592]
First, thanks for this excellent add-on, which makes Bibtex import so much better. 

I noticed one issue after installing BBT. Right-clicking on collections or sub-collections in the leftmost pane brings up a context menu. BBT apparently adds some new entries to this menu, but some of the menu titles go missing in action (please see attached images). My BBT version is 1.6.78 (current as of today). 

Thanks, Michael 

Screenshot without BBT installed 

![no-bbt-cropped](https://cloud.githubusercontent.com/assets/23055717/19688627/83091084-9a98-11e6-96b0-1e28b5ec2acb.png)

Screenshot with BBT installed

![with-bbt-cropped](https://cloud.githubusercontent.com/assets/23055717/19688625/83070da2-9a98-11e6-8c7c-175b518efa04.png)

**Comment by retorquere** [comment]
I think you're bitten by #584; I'm readying a release that will address this (a.o.)

**Comment by dbobak** [comment]
Confirming the bug. Zotero Standalone on Windows.

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3168.xpi ought to fix the issue (this is what is slated for release). Wouldn't mind knowing if it does address the issue for you both.

**Comment by dbobak** [comment]
Yes, with this version the issue is fixed. Thanks!

**Comment by retorquere** [comment]
A release is going out within a few hours, preferably with #590 but it's not a blocker. You'll be upgraded automatically.

**Comment by michaelpalmeruw** [comment]
great, thank you.

On 25/10/16 09:57 AM, retorquere wrote:
> I think you're bitten by #584; I'm readying a release that will address this (a.o.)
>

-- 
Michael Palmer
364 Anatolin Place
Waterloo, ON N2L5G8

**Comment by retorquere** [comment]
.79 is out

**Comment by michaelpalmeruw** [comment]
yes, it does - thanks! M.

On 25/10/16 10:42 AM, retorquere wrote:
> https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3168.xpi ought to fix the issue (this is what is slated for release). Wouldn't mind knowing if it does address the issue for you both.
>

-- 
Michael Palmer
364 Anatolin Place
Waterloo, ON N2L5G8
