### ISSUE TITLE
Book reviews

### ISSUE THREAD

**Issue by njbart** [retorquere/zotero-better-bibtex#593]
Book reviews are quite problematic, and not only for BBT:
- Zotero is limited to one set of reviewed-authors and one reviewed-title (so there’s no way to format reviews of two or more books properly), and there’s no way to input reviewed-editors rather than reviewed-authors. 
- vanilla biblatex and biblatex-chicago (and bibtex, too) have no special functionality for book reviews, so all details have to be included in the title field.
- biblatex-apa has the most flexible approach, using biblatex’s “related” functionality.

In any case, BBT’s current biblatex output (and the output formatted by latex) is unsatisfactory since it lists reviewed authors as “collaborators” and fails to indicate that an item is a book review at all.

Actual BBT output (from one of the Z58T9QFH examples):

```
@review{kamp_deconstructing_2006,
  abstract = {Example from CMoS, 16e, 14.125},
  author = {Kamp, David},
  date = {2006-04-23},
  editora = {Pollan, Michael},
  editoratype = {collaborator},
  langid = {american},
  title = {Deconstructing Dinner},
  url = {http://www.nytimes.com/2006/04/23/books/review/23kamp.html}
}
```

Expected output:

```
@review{kamp_deconstructing_2006,
  abstract = {Example from CMoS, 16e, 14.125},
  author = {Kamp, David},
  date = {2006-04-23},
  editora = {Pollan, Michael},
  editoratype = {collaborator},
  langid = {american},
  title = {Deconstructing Dinner},
  titleaddon = {\bibstring{reviewof} \mkbibemph{The Omnivore’s Dilemma: A Natural History of Four Meals}, \bibstring{by} Michael Pollan},
  url = {http://www.nytimes.com/2006/04/23/books/review/23kamp.html}
}
```

So, it seems the following would be needed for vanilla biblatex and biblatex-chicago:
- If there is a “Reviewed Author” in a Zotero entry, treat it as a review.
- If the “Extra” field contains “type: review” or “type: review-book”, treat it as a review, too.
- If there is no “reviewed-title: Blah” or “{:reviewed-title:Blah}” in the “Extra” field:
  - Assume that the “Title” field contains the BOOK TITLE.
  - Construct a biblatex `title` field as follows: `\bibstring{reviewof} \mkbibemph{` BOOK TITLE `}, \bibstring{by} {` LIST OF AUTHORS `}`
- If there is a “reviewed-title: Blah” or “{:reviewed-title:Blah}” in the “Extra” field:
  - Assume that the “Title” field contains a separate, non-generic title.
    - This should become the biblatex title.
  - Assume that the “reviewed-title” variable contains the BOOK TITLE.
    - Construct a biblatex `titleaddon` field as follows: `\bibstring{reviewof} \mkbibemph{` BOOK TITLE `}, \bibstring{by} {` LIST OF AUTHORS }`

In both cases:
- Titlecase the BOOK TITLE
- Wrap the LIST OF AUTHORS in `{}`
- If there is more than one author, use `\bibstring{and}`, e.g., `John Doe, Ron Roe, \bibstring{and} Mike Moe`

(For reviews of _edited_ books, I have started using `[Doe][John,!ed.]` in Zotero’s `reviewed-author` field. It’s a hack, sure, but maybe BBT could try to parse `,!ed.` or `,!eds.` and use `\bibstring{byeditor}` instead of `\bibstring{by}` in such cases. Anyway, that's strictly optional, and does not solve all of Zotero’s problems either – there seems to be no hack that would allow you to input two or more reviewed books …)

The same should work for bibtex (if you want to implement that at all), but all `bibstring` elements would have to be replaced by their plain English counterparts.

The approach outlined so far would also work (sort of, at least) for biblatex-apa.

Specifically for biblatex-apa something else could be tried, but it would involve tapping into the “Related” functionality of Zotero by checking whether a “review-book” entry has one or more “related” book entries, constructing a suitable biblatex @review entry that contains the citekeys of the book(s), and exporting all items involved. – You’ll have to decide whether you want to try _that_.

**Comment by retorquere** [comment]
Something like the latter is already being worked on in #529, so it's not too much of a stretch. The rest I'll have to look at later -- I need to get the release out.

**Comment by retorquere** [comment]
@njbart are you interested in picking this back up?

**Comment by njbart** [comment]
Yep, still interested – and happy to answer any questions (as always), but apologies for not being able to test-drive anything Z5-related for the time being. Much of my daily work has been depending on an uninterrupted Zotero- and pandoc-centered workflow for some time now, so with neither BBT nor zotxt completely ready, I can’t really afford to upgrade to Z5 just yet.

**Comment by retorquere** [comment]
Understandable. Most of BBT is done though, with just [these](https://github.com/retorquere/zotero-better-bibtex/milestone/1) open issues.

It is perhaps better to hold off this issue until the 5.0 port is complete; It'd work best if I can get source samples + corrected output, and the source sample format (the stuff that the debug report submits) has changed.

**Comment by retorquere** [comment]
BBT is ready. I think I've seen moves in zotxt indicating it was either ready or close to it.

**Comment by retorquere** [comment]
zotxt is now Z5 compatible.

**Comment by retorquere** [comment]
We could pick this back up now.

**Comment by retorquere** [comment]
Zotero doesn't really have a place for this info. The desired result can be achieved currently by adding

```
tex.titleaddon= \bibstring{reviewof} \mkbibemph{The Omnivore’s Dilemma: A Natural History of Four Meals}, \bibstring{by} Michael Pollan
```
to the `extra` field.
