### ISSUE TITLE
Google Scholar like Citation Key Generation 

### ISSUE THREAD

**Issue by ludaesch** [retorquere/zotero-better-bibtex#595]
I've started to use zotero with better-bibtex as I hope I can import (and merge) the many .bib files I have. I would like to keep the Google Scholar generated citation keys if possible!

In addition, for newly generated keys, I'd like the generated keys to conform the Google Scholar format as well! How can I customize the key generation with better-bibtex so that the generated keys follow the Google Scholar format (as if exporting Google Scholar references as bib files)?

Thanks!

PS I'm saving / exporting files in "better-bibtex" (rather than "better-biblatex") currently..
(aside: not married to this -- just not sure which one to pick).

**Comment by retorquere** [comment]
I don't know what `Google Scholar generated citation keys` means as an algorithm, but if you mean "*I intend to import Google Scholar-generated BibTeX references, and I want to keep the keys they have*", that's just what happens already. On import, you'll find your key as `bibtex: <your key>` in the `extra` field, and BBT will always use those when present.

BibLaTeX (Better or not) should always be your preferred format if you can get away with it. BibTeX has many, *many* limitations and I need to "dumb down" the references considerably to generate valid BibTeX from them. BibLaTeX is much more accommodating of modern references. But not every journal accepts BibLaTeX, so the BibTeX option is there if you need it.

**Comment by retorquere** [comment]
(note: the `bibtex:` thing only happens if you import with BBT installed. The standard Zotero BibTeX importer doesn't do this, but BBTs takes precedence when installed)

**Comment by retorquere** [comment]
still interested?

**Comment by retorquere** [comment]
Closed for lack of user response.

**Comment by ludaesch** [comment]
Thanks! This helps (and sorry for the late response)

**Comment by retorquere** [comment]
No worries. But I still don't know what you mean when you say "as Google scholar generates them". What do such keys look like?

**Comment by ludaesch** [comment]
Take for example this paper: [Tractable database design and datalog abduction through bounded treewidth](https://scholar.google.com/scholar?cluster=12180149755054481714) . When you follow that link and click on "cite" and then on "BibTeX", you'll get an entry that has the key:
"gottlob2010tractable".  I have many BibTeX records of this form and correspondingly named many PDF files (here: gottlob2010tractable.pdf) scattered in many folders (semi-organized).  

Since I reuse Google Scholar BibTeX keys as filenames, I can quickly search for them (e.g. in Spotlight). This gives me a fast, low-tech way of going from BibTeX records to PDF files on my disk. I have hundreds if not thousands of such Google-Scholar-named PDF files all over the place. Hence I would love to configure Zotero to generate Google-Scholar compatible keys if possible.

Alternatively, I can start naming new PDF files I download using the default Zotero key (here: gottlob_tractable_2010.pdf). 

But if I knew how to make Zotero generate gottlob2010tractable instead, I'd be even more happy :-)

**Comment by retorquere** [comment]
Try `[auth:lower][year][veryshorttitle:lower]`

**Comment by ludaesch** [comment]
Works like a charm (so far :-)! Thanks!
If I want to have Zotero reformat all keys in an existing collection to use the new format, how could I do that?

**Comment by retorquere** [comment]
Select all, right-click and select "clear bibtex key" ought to do the trick. This will also reset all keys that were pinned though.

**Comment by jvdheyden** [comment]
I'm having the problem that unlike BetterBibTex, Google Scholar removes all words that come after a whitespace or a dash (in an author or title field). How can I replicate this behaviour in better bib tex?

**Comment by retorquere** [comment]
Can you get me a BBT debug report from the item you have in mind, the key BBT produces, and the key you want it to produce?

**Comment by jvdheyden** [comment]
the bug report id is DPPQBHSL-euc
tthe key BBT produces is elkaafarani2020lossy and I would like to be el2020lossy
similarly bug report id S6YAXWZ5-euc:
the key BBT produces is yoo2017postquantum and I would like it to be yoo2017post

**Comment by retorquere** [comment]
Can you open a new issue with these debug IDs? This is not easily replicable with the existing key generator, so I'll have to make changes.
