### ISSUE TITLE
Citationkey in italic

### ISSUE THREAD

**Issue by mijalce** [retorquere/zotero-better-bibtex#597]
This is simple question and I am asking it out from a curiosity. If you do not have time just ignore it. 
In Zotero I notice that some of the generated CitationKeys are _italic_ while other citation keys are not. 
If I find a CitiationKey that is italic and when I press Generate Bibtex key it is transformed to normal (non-italic). The CitationKey is the same. 
Is there a difference between italic and normal CitationKey?

**Comment by retorquere** [comment]
A citation key displayed in italic is dynamic, and may change when the reference changes. When it is not italicised it means the citation key is pinned and written down in the `extra field` and it won't change even if you change the reference.
