### ISSUE TITLE
better-bibtex/schomd fails with method bibtex

### ISSUE THREAD

**Issue by berndjr** [retorquere/zotero-better-bibtex#598]
I use better-bibtex with Emacs/RefTeX. For the creation of BibTeX file for a given document I call the schomd endpoint, which did work up to release 1.6.75. Release 1.6.76 tells me "No endpoint" and from release 1.6.77 instead of the requested BibTeX file I get the result `[object Promise]`.

E. g. I call the URL http://127.0.0.1:23119/better-bibtex/schomd with the POST method and the following data: `{"method":"bibtex","params":[["bouillon_recht_2004","kinsella_against_2008"],{"translator":"biblatex"}]}`. The result is this:

```
HTTP/1.0 200 OK
X-Zotero-Version: 4.0.29.15
X-Zotero-Connector-API-Version: 2
Content-Type: application/json

[object Promise]
```

**Comment by retorquere** [comment]
Sorry, that was sloppy. Things are a bit topsy-turvy as I try to prep for 5.0, and not everything was covered by existing tests. This case has been added as a test now -- can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.80-circle-3259.xpi ?

**Comment by berndjr** [comment]
That version works again.
