### ISSUE TITLE
Citation keys sometimes have an ampersand &

### ISSUE THREAD

**Issue by psmith1303** [retorquere/zotero-better-bibtex#602]
I'm using the BibTex export, and some of my items, such as as the sample sent in error report ID VFPXJMK2 may contain an ampersand.

For example, the key might be: brannback_r&d_2003

Alas, the & creates problems further down the line, when I use pandoc to process the file; it doesn't like ampersands in citation keys -- it chokes and complains about the entry. Pandoc support says that  having an ampersand in the key is incorrect. 

There seem to be a few posts to Tex.stackexchange indicating that ampersand in keys is often problematic more generally (i.e., beyond pandoc),  and no real solution I can find other than removing the ampersand from the key.

**Comment by retorquere** [comment]
You have `[zotero]` (the default) as a citekey pattern. That pattern replicates the default Zotero citekey generation exactly, and that includes all its flaws -- such as including ampersands in the key. The reason it's the default is that I did not want to introduce sudden changes for people that were already using Zotero to generate their BibTeX and were already using those keys. `[auth:lower:postfix,_][shorttitle:lower:postfix,_][year]` should get you close to the `[zotero]` pattern without its attendant problems.

**Comment by retorquere** [comment]
does this address your question?

**Comment by psmith1303** [comment]
Perfectly. Thank you.
