### ISSUE TITLE
Quick copy Bibtex on windows 10 leads to save as window

### ISSUE THREAD

**Issue by TheoChristiaanse** [retorquere/zotero-better-bibtex#603]
I've tried to use the Quick Copy Better BibTex option, to copy the bibtex item to the clip board but it pops out an save as menu.

I can save "Exported Items.txt" (suggested name) and copy from notepad but takes a lot of time.

I'm using windows 10 and Zotero 4.0.29.10

**Comment by retorquere** [comment]
You can already sort of do this using [quick copy](https://www.zotero.org/support/creating_bibliographies#quick_copy) if you have the quick-copy translator set to Better Bib(La)TeX.

**Comment by TheoChristiaanse** [comment]
Thanks for your reply! but this pops out a "save-as" window to save a txt file for me. Maybe it is because of Windows 10?

**Comment by retorquere** [comment]
Does this only happen with BBT translators (this would be surprising) or with all translators? If it happens with all, you'd have to talk to the zotero people - the quick copy stuff calls a translator of your choosing and puts the results on the clipboard Translators (such as BBT) cannot do anything except spit out text strings, so translators (generally) cannot trigger things like save-as.

**Comment by retorquere** [comment]
Hold on, how do you use the quick copy translator?

**Comment by retorquere** [comment]
Still interested?

**Comment by TheoChristiaanse** [comment]
![image](https://cloud.githubusercontent.com/assets/7392/20243997/6e728278-a924-11e6-9050-8425ad22fa3e.png)

I tried to find other quick copy options in the export but only the Better Bibtex has the quick copy. All other export options will pop out a save-as menu.

**Comment by retorquere** [comment]
I can't hide it from that menu, alas, but that's not where it's intended to be used, it's intended to be used with the Zotero [quick copy](https://www.zotero.org/support/creating_bibliographies#quick_copy) feature. Quick copy and regular export use the same Zotero infrastructure, so anything that you can use for quick copy you will by necessity also find in th export dropdown.

In the setup outlined in the [quick copy](https://www.zotero.org/support/creating_bibliographies#quick_copy) page, choose "Better BibTeX Quick Copy" as the export format, and in your case, set the Quick Copy format in the BBT "Citation keys" prefs to "Cite Keys". Then use the shortcut keys as explained on the Zotero [quick copy](https://www.zotero.org/support/creating_bibliographies#quick_copy) page.

**Comment by retorquere** [comment]
Still interested?

**Comment by TheoChristiaanse** [comment]
Thanks! I got it working like that. It took me a while to understand what you ment. I'm current writing my thesis under a hard deadline.

**Comment by retorquere** [comment]
I appreciate that, but I try to keep the number of open issue as low as possible as I'm working through the 5.0 port so I know what things still need to be done. I know how hard deadlines can be, and thesis work, but I really need bug-reporters to be available for resolution to get closure.
