### ISSUE TITLE
[Feature] Suggesting adding LyX Support

### ISSUE THREAD

**Issue by Oberreiter** [retorquere/zotero-better-bibtex#609]
Hi,
I want to suggest adding citation support for LyX similar to the existing Firefox Plugin 
[LyX Addon for Firefox](https://addons.mozilla.org/en-US/firefox/addon/lyz/)

Regards
Andreas

**Comment by retorquere** [comment]
Seems like a shame to duplicate the effort. Why not [drop a request](https://github.com/willsALMANJ/lyz/issues) with the Lyz author to pick the keys from the BBT database? I'll be glad to assist reading from it -- the DB is a [LokiJS](http://lokijs.org/#/) database so it's easy and well-documented how to fetch data from it. Or do you mean to pop up the picker? This is easy too, but best done from the Lyx/Lyz side.

**Comment by Oberreiter** [comment]
I haven't got Lyz working at the moment. And I'm working with the standalone Version of Zotero. So I hoped for a direct support. But you are right. I will try to get Lyz working.

**Comment by retorquere** [comment]
It's possible that direct support is desirable, but then I'd have to know what you mean by support. What would you want to have that you don't have currently?
