### ISSUE TITLE
Citation keys do not follow on import

### ISSUE THREAD

**Issue by ptb0890** [retorquere/zotero-better-bibtex#610]
We are currently attempting to transition from Mendeley to Zotero.

Using Zotero 4.0.29.5 with better-BibTeX 1.6.86, I have attempted to import our library, a subset can be found in the .bib file at https://gist.github.com/ptb0890/0154a50b744fae8aae3db78ab9319b0a however the citation keys generated do not seem to match, specifically when there are multiple entries for the same author in the same year, e.g.

Mendeley->Zotero/better-BibTeX

Denner2014->Denner2014f
Denner2014a->Denner2014a
Denner2014b->Denner2014b
Denner2014c->Denner2014g
Denner2014d->Denner2014e
Denner2014e->Denner2014c
Denner2014f->Denner2014d
Denner2014h->Denner2014

Perhaps I have missed something in the configuration?

**Comment by retorquere** [comment]
Nope, you've hit upon a bug in BBT. I'll look into it (so please don't close the issue yet), but in the interim you can check "Re-scan pinned citation keys after start" in the BBT advanced prefs, restart firefox, and the keys will be picked up.

**Comment by ptb0890** [comment]
Thanks, that has fixed the keys for us.

**Comment by retorquere** [comment]
I'll get to the real bug as soon as I can.

**Comment by retorquere** [comment]
Will be folded into the Z5 port
