### ISSUE TITLE
Biblatex Annotation Import Bug

### ISSUE THREAD

**Issue by mrgah** [retorquere/zotero-better-bibtex#613]
Sorry to bug you with another Biblatex bug, but according to the Biblatex Chicago documentation, `annotation` is an alias for Bibtex's `annote` Entry field. However, `annotation` fields are imported differently by BBT than `annote` fields (`annotation` fields end up in the extra field). 

Additionally, `note` entry fields end up in the Extra field as well. Given that note is for "bibliographic data that doesn’t easily fit into any other field," this may well be intentional. 

Thanks as always for the hard work!

**Comment by retorquere** [comment]
Do you you have a sample for me?

**Comment by mrgah** [comment]
Yep: 

@Book{Demus1984,
  Title                    = {The Mosaics of San Marco in Venice},
  Author                   = {Demus, Otto},
  Date                     = {1984},
  Location                 = {Chicago},
  Publisher                = {University of Chicago Press},
  Annotation                 = {a "monumental" work on the mosaics of San Marco},
}

**Comment by retorquere** [comment]
The problem is fixed but github is experiencing an [outage](https://status.github.com/messages) which prevents a release. I think that as soon as the outage is resolved the release process will be started automatically, but I'll try to keep an eye on it.

**Comment by retorquere** [comment]
The release is out.
