### ISSUE TITLE
lib/fold-to-ascii.js load failed

### ISSUE THREAD

**Issue by doctornerdis** [retorquere/zotero-better-bibtex#615]
I've been running Zotero on a Mac, standalone v. 4.0.29.5. All of a sudden, I'm getting the following error message:

```
lib/fold-to-ascii.js load failed: SyntaxError: class is a reserved identifier
```

I'm unable to send an error report, so apologies for no report ID. Looking through previous issues, maybe this has something to do with #590 ?

Many thanks!

**Comment by retorquere** [comment]
Ugh, Zotero standalone and its ancient Firefox version... can you try this version: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.87-br615-3386.xpi

**Comment by doctornerdis** [comment]
Yup, that worked. Thank you!

Are you recommending that people use the Firefox version of Zotero w/ BBT instead of the standalone?

**Comment by retorquere** [comment]
No not specifically, just a little frustrated that Zotero uses such outdated platforms for standalone. I run my tests against the plugin version, and that usually works out to the same, just not always.

This is going to be resolved soon anyhow as Zotero 5.0 includes an upgrade of the platform they use, plus soon standalone will be all there is.

**Comment by retorquere** [comment]
A new release is scheduled and should be out in 10 minutes or so, but it's just what you have now.

**Comment by doctornerdis** [comment]
OK. Thanks. As always, I appreciate your help.

**Comment by sbanerjee23** [comment]
Hi @retorquere, unfortunately this error is back on 1.6.92. I reinstalled 1.6.91, and it seems fine. I am on Ubuntu 16.04 with Zotero v 4.0.29.10.

**Comment by retorquere** [comment]
Can you submit an error log?

**Comment by sbanerjee23** [comment]
I'm not sure how to debug this. If you can guide me a bit, I'd be happy to try and help.

**Comment by retorquere** [comment]
If you go into the zotero settings, advanced, then "view log" you'll be able to see the error log. If you could out the contents of that on gist.github.com I will have more info.

**Comment by sbanerjee23** [comment]
I enabled the debug output log after reinstalling 1.6.92, and this is what is shows:

https://gist.github.com/sbanerjee23/57a66cf28a702f328e9386dd269d29a0

**Comment by retorquere** [comment]
Hmm, not enough info yet. Could you go into Preferences->Advanced, enable "Enable after restart", restart Zotero, and then submit such a debug log again?

**Comment by sbanerjee23** [comment]
Any better?

https://gist.github.com/sbanerjee23/446a0fddc44538e978921e371f66f576

**Comment by retorquere** [comment]
Argh standalone again. Sorry. I've added a safeguard that this won't happen again. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.92-br615-3544.xpi ?

**Comment by sbanerjee23** [comment]
Works, no error. Thanks for the awesome extension.

**Comment by retorquere** [comment]
Great, I'll cut a new release.
