### ISSUE TITLE
How to export call numbers to BibLaTeX field

### ISSUE THREAD

**Issue by kfeuerherm** [retorquere/zotero-better-bibtex#616]
I gather that I should be able to customize BBT behaviour to export the call number, when present, to a field of my choice, but for the life of me I can't figure out how to do this. I assume the thing to do is to add some code to the Postscript box, along the lines of

`if (this.item.callNumber)
  {
    this.add({ name: 'annote', value: this.item.callNo });
  }`

but evidently this isn't right. The desired output is `annote = { <call number> },`.

Can you assist? With thanks.

**Comment by retorquere** [comment]
Try changing `callNo` to `callNumber`, but if that doesn't do it, could you please right-click the reference you want to export and select "send better bibtex error"? That will give me the reference to test with.

**Comment by kfeuerherm** [comment]
Wow, thanks for the speedy response!

I thought I’d tried callNumber, but I guess not, because it works! Much appreciated!!

**Comment by retorquere** [comment]
Do you have a debug ID?

**Comment by kfeuerherm** [comment]
Apologies, I’m new at this… where do I find a debug ID?

**Comment by retorquere** [comment]
That's OK -- if you right-click that reference in Zotero, then select "Send Better BibTeX error", you will be presented a dialog to submit an error report. When you submit that dialog you'll be shown an alphanumeric ID in red -- if you give me that, I know which report is yours.

**Comment by kfeuerherm** [comment]
Um, ok…. I got this : T4VV6QHW (in red)

I have to compliment you on your efficiency and generosity here. I wish all products were this well supported!

Best

Karljürgen

**Comment by retorquere** [comment]
Thanks, that gets me both the reference and your current BBT settings. But with this ref and the postscript I saw in the report, I get

```
annote = {P211 .F63 2001}
```

in the output. Can you enable extended debugging in BBT, retry your export, and then send another debug report?

**Comment by kfeuerherm** [comment]
But that’s what I wanted to get in the ouput…?

Anyhow, here’s the new ID: JC8EEIAX

Hope I did this correctly…

**Comment by retorquere** [comment]
I know, so it works on my end. Nothing of interest in the new log however. Can you try [this version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.88-br616-3399.xpi) (with extended debugging on) and submit a new debug log? I've added extra logging.

**Comment by kfeuerherm** [comment]
Here you go: HZA7PKWF

BTW I thought Firefox was going to go into a loop, it installed, said restart, then did that again, and then it was (I assume?) fine….

Is there a list of the field names I would use, say I wanted to add other things into the annote field (for example)? It seems a shame to bother you everytime if I want to add to this down the road….

Best

K

**Comment by retorquere** [comment]
> Here you go: HZA7PKWF

Ah sorry I forgot to mention you need to make an export before submitting the report. The error happens during export. If you want you can try it with [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.88-br616-3402.xpi), which will color the postscript field orange if you have syntax errors. Not that I think you have them now, but it may help (and it's going into the next release in any case).

> BTW I thought Firefox was going to go into a loop, it installed, said restart, then did that again, and then it was (I assume?) fine….

Possibly when firefox restarted it opened with the download URL for the xpi, downloaded it again, etc? That might cause this behavior... but Firefox is not supposed to auto-install XPIs, you should always get the confirmation dialog. Otherwise I have no idea. The behavior of the installer is off-limits for extensions, they have no control over how it behaves.

> Is there a list of the field names I would use, say I wanted to add other things into the annote field (for example)? It seems a shame to bother you everytime if I want to add to this down the road….

Not a documented list (and the list would vary per reference type), but if you export a reference in the `BetterBibTeX JSON` format you will see a list of fields you can use. But I don't mind doing the occasional postscript, it's not exactly a deluge of requests.

**Comment by kfeuerherm** [comment]
Ok. I clicked on your “this”, and got the installation dialogue twice as before (with restarts in between).

Then I exported the one item. Then I right-clicked on it to generate the report. Code: ZCKZ45WU

Hope I did it right this time :)

Right, I’ll keep the JSON export in the back of my mind. When I have a moment, I’ll experiment…. (I did my undergraduate degree in computer science, but it’s long ago—1984—so pre-internet and I programmed in Pascal and B mostly (predecessor to C) and I’m upgrading *very* slowly as time permits…. :)

**Comment by retorquere** [comment]
Can you try this postscript, and generate a new debug log:

```
Zotero.debug('callNumber:' + this.item.callNumber);
this.add({ annote: this.item.callNumber });
Zotero.debug('fields:' + Object.keys(this.has));
```

This adds some debugging. It also uses two shortcuts: If you have only a name and a value, you can add it as `<name>: <value>`, and `this.add` doesn't output anything if the value is empty.

I remember Pascal (although not fondly), but B... no, not acquainted. But instead, I offer APL (but fortunately they stopped making the keyboards and the world moved on), TCL (which is underrated), Basic (but let's not dwell on that shall we?). And of course C. And Java. Ugh, Java.I think I liked Pascal better.

These days though I'm Ruby when I can, python/javascript when I must.

**Comment by kfeuerherm** [comment]
Here you got: GW8XA7PZ

I remember doing some APL, briefly… don’t remember special keyboards, so don’t recall whether we memorized shortcuts for that or what…. oh well. I always wondered what happened to APL….

Basic is hardly basic any more!! It should be allowed to die gracefully :)

**Comment by retorquere** [comment]
From that log I can see the callNumber is found in the postscript and seems to be applied successfully to the reference. This is the output I get when I export that reference with the postscript:

```

@book{Fischer2001,
  location = {{London}},
  title = {A History of Writing},
  isbn = {978-1-86189-101-3},
  abstract = {From notches to tablets -- Talking art -- Speaking systems -- From alpha to omega -- The East Asian 'regenesis' -- The Americas -- The parchment keyboard -- Scripting the future., "From the earliest scratches on stone and bone to the languages of computers and the internet, A History of Writing offers a fascinating investigation into the origin and development of writing throughout the world. Commencing with the first stages of information storage, Fischer focuses on the emergence of complete writing systems in Mesopotamia in the fourth millennium BC. He documents the rise of Phoenician and its effect on the Greek alphabet, generating the many alphabetic scripts of the West. Chinese, Vietnamese, Korean and Japanese writing systems are dealt with in depth, as is writing in pre-Columbian America. Also explored are Western Europe's medieval manuscripts and the history of printing, leading to the innovations in technology and spelling rules of the 19th and 20th centuries"--Provided by publisher.},
  pagetotal = {352},
  timestamp = {2016-12-21T15:31:39Z},
  langid = {english},
  series = {Globalities},
  publisher = {{Reaktion Books}},
  author = {Fischer, Steven Roger},
  date = {2001},
  keywords = {Alphabet History.,Writing History.},
  annote = {P211 .F63 2001}
}
```

What is it that you get?

**Comment by retorquere** [comment]
Oh sorry, you already said it works... ugh I need to be paying more attention.

**Comment by kfeuerherm** [comment]
Not sure you’ll get this, as it’s closed, but just for comparison if you do get it:

@book{fischer_history_2001,
  location = {{London}},
  title = {A History of Writing},
  isbn = {978-1-86189-101-3},
  abstract = {From notches to tablets -- Talking art -- Speaking systems -- From alpha to omega -- The East Asian 'regenesis' -- The Americas -- The parchment keyboard -- Scripting the future., "From the earliest scratches on stone and bone to the languages of computers and the internet, A History of Writing offers a fascinating investigation into the origin and development of writing throughout the world. Commencing with the first stages of information storage, Fischer focuses on the emergence of complete writing systems in Mesopotamia in the fourth millennium BC. He documents the rise of Phoenician and its effect on the Greek alphabet, generating the many alphabetic scripts of the West. Chinese, Vietnamese, Korean and Japanese writing systems are dealt with in depth, as is writing in pre-Columbian America. Also explored are Western Europe's medieval manuscripts and the history of printing, leading to the innovations in technology and spelling rules of the 19th and 20th centuries"--Provided by publisher.},
  pagetotal = {352},
  timestamp = {2016-12-20T14:57:38Z},
  langid = {english},
  series = {Globalities},
  publisher = {{Reaktion Books}},
  author = {Fischer, Steven Roger},
  date = {2001},
  keywords = {Alphabet History.,Writing History.},
  annote = {P211 .F63 2001}
}

And for your edification: https://www.thinkage.ca/english/gcos/expl/b/manu/manu.html <https://www.thinkage.ca/english/gcos/expl/b/manu/manu.html>

(I have a copy of another cute thing, the Zed manual, which I did try to send you but it’s just over the message limit at your end; 5.9 Mb. I printed it myself in 1980!)

Thanks very much for your help!

**Comment by retorquere** [comment]
You are not going to trick me into learning B just so I can take over maintenance of your old projects :)

Zed, zed... no, doesn't ring a bell.

(I do get mail for closed messages as I'm auto-subscribed on all issues new and old)

**Comment by kfeuerherm** [comment]
Ha ha, well, unless you have a Honeywell 6660 you aren’t going anywhere anyhow; and I don’t have any old projects :)

Here’s a small clip from the Zed manual that will fit.

Enjoy the holidays!

**Comment by retorquere** [comment]
I am fairly certain that I don't have a 6k series in my hardware stash. Not enough space in the house I think.

I think you must have mailed your response; github doesn't post attachments to mail messages to the [tracker](https://github.com/retorquere/zotero-better-bibtex/issues/616) which is where your messages end up -- so no Zed clip for me.

**Comment by kfeuerherm** [comment]
:)

Yes, I did. It’s no big deal, just a curiosty, but how would I send it to you otherwise? at the Github site somehow?

**Comment by retorquere** [comment]
You can either attach it [through the web interface](https://github.com/retorquere/zotero-better-bibtex/issues/616) or mail it to me at emiliano.heyns@iris-advies.com
