### ISSUE TITLE
Wrong title field on BibLaTeX export

### ISSUE THREAD

**Issue by nonkreon** [retorquere/zotero-better-bibtex#622]
Hi,
I find your project ultimately the one that will satisfy my needs, but there are a few problems unfortunately. Allow me to thank you first then share these problems with you so we can resolve them. My report ID is MM8M5TKQ.

I'm exporting to BibLaTeX currently. The problem is, for entries of type "article", the journal title goes to the field "journaltitle", and actual "title" field is left empty, resulting in no title in the compiled bbl file (I'm using the IEEEtran style).

Thanks again for your efforts for making our lives easier,

**Comment by retorquere** [comment]
That seems like an error in the style (right @njbart), as `journaltitle` is the proper title field for articles under biblatex. Are you sure you're using biblatex to compile the reference?

If you're sure you want this you could do this in a postscript:

```
if (this.has.journaltitle) { this.has.journaltitle.name = 'journal'; }
```

**Comment by nonkreon** [comment]
You were right, I was not using biblatex! 
Thanks a lot!
