### ISSUE TITLE
Manual alteration of exported BibLaTeX entries

### ISSUE THREAD

**Issue by nonkreon** [retorquere/zotero-better-bibtex#623]
My report ID is MM8M5TKQ.

Whenever I alter an exported BibLaTeX entry to suit my needs, when I restart Zotero it just overwrites on the entry. Is there a way to prevent this?

**Comment by retorquere** [comment]
Do you have an auto export set up?

**Comment by nonkreon** [comment]
Yes I do, I auto export when idle to the bib file from the cloud on two different computers, one at the office and the other at home, my Zotero is also syncing between the two from the Cloud using a WebDAV server. The first time I set-up the auto export on the second computer, it overwrote the whole file as expected, I understand that. But now it seems like whenever I close the Zotero at one and start it up on the other, it overwrites the whole file again with the information from Zotero.

**Comment by retorquere** [comment]
There are a number of reasons why bbt would redo an auto export, one of which is almost any change to the bbt prefs. BBT will err on the side of caution and rewrite if there is a chance the export is outdated. Post-processing an auto export is always going to carry this risk. Can the post-processing be done in a postscript?

**Comment by retorquere** [comment]
closing for lack of feedback
