### ISSUE TITLE
Feature Request: Altering BibLaTeX entries inside Zotero

### ISSUE THREAD

**Issue by nonkreon** [retorquere/zotero-better-bibtex#625]
My report ID is MM8M5TKQ. Can I alter the BibLaTeX entry itself inside Zotero?
Thanks!

**Comment by retorquere** [comment]
I don't understand. What do you want to modify in Zotero?

**Comment by nonkreon** [comment]
Like the "title" field instead of "journaltitle", to quickly fix the problem in #622

**Comment by retorquere** [comment]
That can only be done in a postscript.

**Comment by nonkreon** [comment]
OK, thanks for the wonderful project :)
