### ISSUE TITLE
[question] Zotero bib API with zotero-better-bibtex

### ISSUE THREAD

**Issue by howecome** [retorquere/zotero-better-bibtex#626]
I'm using the zotero-better-bibtex plugin to export my references to a bibtex .bib file for use with LaTex. This seems to work really nicely - Thanks!

I would like to use bibbase.org to access a collection using the zotero API interface so that I can also have a 'live' publications list on my website. The bib file this produces (which is then parsed and rendered by bibbase.org) includes the bibtex parameters created/used by BBT in the note field, which then get rendered as seen at ( [http://alastairhmoore.com/test-publications/](http://alastairhmoore.com/test-publications/) ) or without the embedding ([http://bibbase.org/show?bib=https%3A%2F%2Fapi.zotero.org%2Fusers%2F3646722%2Fcollections%2FT2R9K7BX%2Fitems%3Fkey%3DBOpOAr8MeAOlvK9qDoPzmAHq%26format%3Dbibtex%26limit%3D100](http://bibbase.org/show?bib=https%3A%2F%2Fapi.zotero.org%2Fusers%2F3646722%2Fcollections%2FT2R9K7BX%2Fitems%3Fkey%3DBOpOAr8MeAOlvK9qDoPzmAHq%26format%3Dbibtex%26limit%3D100))

Is there anyway to avoid this? I checked on the zotero forum ([https://forums.zotero.org/discussion/63773/extra-field-exported-as-note-in-bib-format-api-call](https://forums.zotero.org/discussion/63773/extra-field-exported-as-note-in-bib-format-api-call)) and apparently there is no way to use BBT to serve the API request which I think would be the best solution. Can you suggest an alternative?

**Comment by retorquere** [comment]
It is not (currently) possible to run BBT outside Zotero; if it ever gets done, it would still require some kind of web server hosting as the BBT translator is unlikely ever to be included in Zotero itself.

It will at some point be possible to have the BBT data outside the `extra` field as the Zotero devs have planned for a way for extensions to store their reference-related data in a clean way in de DB, but that's still a while off, and there's no ETA.

If you're not afraid of a little hackery though, it can still be done. You could set your library up to auto-export using BBT, use a tool to auto-upload that file to a webserver when it changes, and then have bibbase.org use that online file to fetch the bib file. Dropbox used to be able to do direct downloads, but I'm not sure they allow that anymore. As a last ditch, [sparkleshare](https://www.sparkleshare.org/) + [github pages](https://pages.github.com/) should work, but will take a bit of setting up.

**Comment by howecome** [comment]
Thanks for the quick reply. It's a shame about these current limitations. It seems like zotero+BBT is very nearly perfect for my needs so I look forward to the zotero devs allowing you to move the bibtex stuff out of `extra`.

In the meantime, I did think of doing something along the lines of what you suggested. For my personal references this could work ok - thanks for the heads about sparkleshare. However, for me to convince the rest of my research group that we would shift our group bib file to zotero I would need to be able to run the auto-export from an always-on machine so that it picks up changes made by other people when I'm not connected. Can zotero+BBT be run from a headless red hat installation? I did a quick search but couldn't see anything.

**Comment by retorquere** [comment]
That is fully possible - see eg http://stackoverflow.com/questions/12050021/how-to-make-xvfb-display-visible. In this scenario you would have the choice between auto-export and have the resulting file served by a simple web server (I'd recommend nginx) or BBTs pull export and put a reverse proxy in front of it (again nginx would be my choice here). 

I'll give some thought to something that would work in a less hacky way, but this ought to get you started.

**Comment by howecome** [comment]
Thanks for the pointer. I'll see whether our server admin can support this.

For my personal collection, I have now managed to get the dropbox solution to work in a way that I am really happy with [http://alastairhmoore.com/publications/](http://alastairhmoore.com/publications/). As a note to anyone else attempting this, to get this to work I had to
- get the share link
- convert it to a download link using [http://www.syncwithtech.org/p/direct-download-link-generator.html](http://www.syncwithtech.org/p/direct-download-link-generator.html)
- encode it to URL/percent encoding using [http://www.url-encode-decode.com/](http://www.url-encode-decode.com/)
- paste it into the appropriate bibbase script command, in my case `<script src="http://bibbase.org/show?bib=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fbwdznrwia21wdyo%2Falastairhmoore.bib%3Fdl%3D1&jsonp=1&group0=type&group1=year"></script>`

**Comment by retorquere** [comment]
If that xvfb setup isn't feasible, you could make use of my testing harness. It's set up to run fully automated in a headless environment (circleci in my case, but any should do) and it can trigger pretty much any behavior you'd want, including export of the library. A call by IFTTT could schedule a run of the circle test, but you'd still need a place to put the resulting file.

**Comment by howecome** [comment]
I found a windows machine that I thought could be always on and tried setting it up to do the auto-export. However, it doesn't seem to pick up changes to the database made on another machine. Of course if I manually press the sync button then it gets the changes (and BBT instantly does its stuff), but that kind of defeats the point. Is there a setting in zotero somewhere that I'm missing or is this something that the test harness would help with?

**Comment by retorquere** [comment]
It's a setting in the Zotero preferences at the same place you configure the sync account. I assume it's the same across all platforms, but I don't have access to a windows PC to check. Whether auto-sync works shouldn't be affected by the presence of BBT, but you can send a BBT error report if you want and I'll have a look if there's any error preventing sync.

**Comment by howecome** [comment]
I have auto sync enabled, it just doesn't seem to actually do it. I agree it's not a BBT error so I'll check on the zotero forum to see if they can help. Thanks.

**Comment by retorquere** [comment]
While I don't expect BBT to interfere here, it wouldn't be the first time it broke something in zotero (although the last time that happened was long enough ago that I can't remember). I could take a look, but I won't be able to inspect the logs until noon tomorrow.

**Comment by howecome** [comment]
It seems there is an error, but I can't tell whether it is anything to do with BBT.

Steps to reproduce:
- Start zotero standalone on a mac and windows machine (both show the same synced group library with one collection, windows machine is already setup to auto-export the collection on change)
- Change title of an entry on mac.
Press sync to force sync to zotero server
- Check in browser that record is updated - works fine
- Check zotero standalone on windows machine - entry is not updated
- Generate first error report (E9TI47AZ)
- After a few minutes without any sync activity, manually force sync - entry is updated, and BBT exports updated bib file as expected
- Generate second error report (NSMS96X6)

**Comment by retorquere** [comment]
Alright so it's good that I looked into this first because

1. BBT did trigger a fault in Zotero (although that was a Zotero function not dealing well with unexpectedly large input), and 
2. the function I called to trigger that did not return the selection of reference-collections that I needed anyway, so needed to call something else anyhow.

Tests are running on a fix.

**Comment by retorquere** [comment]
Can you give  https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.90-br626-3435.xpi a try?

**Comment by howecome** [comment]
- Added the new xpi to both the mac and windows machines. Restart with clear cache.
- Added new entry on mac + forced sync
- Browser shows update
- Windows machine does not - report ID: 75SCHQRT
- Force sync on windows - entry now appears and BBT does export
- Generate another error report for good measure: EZ3IJKJC

**Comment by retorquere** [comment]
OK so the good news is that the error that probably prevented sync is gone. I've merged that fix and scheduled 1.6.91 for release to include it.

The not so good news is that I now see absolutely no errors so I have no idea why auto-sync is not happening. I'm afraid the Zotero team will have to look into it. They're almost certainly going to ask you whether it works when BBT is not installed, so you may as well try that ahead of submitting a report to them. In any case, whether you keep BBT installed or not, remember to turn off extended BBT debugging -- the log is very, very chatty (about 40MB a pop in your last reports) when it is on (OK so BBT is very, very chatty -- most of that 40MB is mine), and they may not want to plod through all of it.

Do keep me posted -- don't close this issue just yet.
