### ISSUE TITLE
Generated "bibtex" keys in "Extra" field not consistent with values in "Citation Key" field

### ISSUE THREAD

**Issue by dotran** [retorquere/zotero-better-bibtex#629]
Hello, I've just filed an error report # **JW7F3246**.

My _Citation key format_ is `[authorsAlpha:lower][year]`

More than a year ago, I reported the issue https://github.com/retorquere/zotero-better-bibtex/issues/415 regarding "_Duplicate citekeys generated in chronological order w.r.t. Date Added_". You released a fix and things have worked since then.

The current issue is I've recently noticed the (occasional) inconsistency between the generated bibtex keys (by right click --> Generate BibTeX key) in the Extra field and the ones displayed in the Citation Key field of Zotero's right pane.

For example, I have a reference with bibtex key generated correctly as "lh2015" as displayed in the Extra field, while its Citation Key field displays "_lh2015i_" in ITALIC! Similarly for the reference with bibtex key of "lh2015a" being displayed in the Citation Key field as "_lh2015e_".

(Of course in the library I am having many references rendered "lh2015..." --- they're simply multiple chapters of a book of the same authors which were added to Zotero at the same Hour and Minute but at different Second, so according to the fix for issue #415, there should not be a problem here.)

Since the Citation Key field locates near the top of the right panel which is very convenient to read and copy, I hope you can make an effort to fix this issue.

Thank you for your excellent work!
Tod

**Comment by retorquere** [comment]
Does this problem remain if you select any other reference and then select back the misbehaving one? That would tell me whether it's a display issue or a refresh issue.

**Comment by todn** [comment]
The problem does remain, even if I restart Zotero. Let me know if you need further information.

**Comment by retorquere** [comment]
This should be fixed now in the Z5 port. If it reappears, please open a new issue.
