### ISSUE TITLE
can zotero-better-bibtex also be used as  chrome extension?

### ISSUE THREAD

**Issue by GitOffice** [retorquere/zotero-better-bibtex#631]
zotero-better-bibtex  is great for us. for Zotero Connector is chrome extension, can zotero-better-bibtex also be used as  chrome extension for chrome's users? Thanks.

**Comment by retorquere** [comment]
The simple answer is "no"; I wish it could be done, but zotero doesn't actually run in chrome, the chrome extension just connects to zotero and has it do its work. 

What would you want to do that you can't now?

**Comment by retorquere** [comment]
closing for lack of feedback
