### ISSUE TITLE
Stop requests to clear cache

### ISSUE THREAD

**Issue by chase-dwelle** [retorquere/zotero-better-bibtex#632]
Since updating to Zotero 0.29.15 I have consistently received the following alert every time I open Zotero or start a new session with Firefox:

> You have upgraded Zotero to 4.0.29.16. This usually means output generation for Bib(La)TeX has changed, and it is recommended to clear the cache in order for these changes to take effect.
> 
> Since you have a large library, with 1381 entries cached, this may lead to a slow first (auto)export as the cache is refilled.
> 
> If you don't care about the changes introduced in 1.6.91, and you want to keep your old cache, you may consider skipping this step.
> 
> If you opt NOT to clear the cache, and you experience unexpected output at some point in the future, please first clear the cache from the preferences before reporting an issue
> 
> Do you want to clear the BibTeX cache now?

Clearing the cache or keeping it does not stop this alert from appearing. Is there a location where I can clear the cache manual, or some other way to suppress this alert?

**Comment by retorquere** [comment]
You can go into Zotero's [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences) and set `confirmCacheResetSize` to `0` (to disable entirely) or to any number above `1381` in your case should you still want some kind of warning at some stage. Recommended to just disable from what you describe.

**Comment by chase-dwelle** [comment]
Your comment got rid of the message. For reference of others, the default value of `confirmCacheResetSize` is 1000. I set my new value to 2000 just to remind myself that I may want to clean out my reference library once I hit 2000 items.
