### ISSUE TITLE
exporting groups?

### ISSUE THREAD

**Issue by ookimi** [retorquere/zotero-better-bibtex#633]
I'm trying to set my bib files to work with Eratosthenes bibliography manager on Android (can't believe that there still isn't a proper zotero client!!!!). What I can't get to work is the groups - the items and keywords are all there.

I made sure that the "export subcollections" box is ticked, but the resulting bib files do not actually have anything resembling my collection paths. Judging by two closed issues, this should exist and even be default?

**Comment by retorquere** [comment]
I'm not sure how Eratosthenes expects the collections to be encoded, but BBT will by default export it in a JabRef-compatible format that will start with `@comment{jabref-meta: groupstree:` and then a jumble of characters that encodes your collection tree. You don't see something like this at the end of your export?

**Comment by ookimi** [comment]
Oh, my bad - I didn't see the end of the file.
And no, it doesn't work anyway. I tried to open my file with JabRef to make sure that whatever happens is not the fault of Eratosthenes, and JabRef won't process my file. It says "group tree could not be parsed. If you save the BibTex database, all groups will be lost". Same behavior with databases exported with better biblatex and better bibtex.

Perhaps this is just a glitch in my database. But I looked into the format Eratosthenes is expecting, and it seems that this is not going to work anyway. The developer says that only top-level groups are supposed to be supported, which would do next to nothing for my library.

Too bad! Back to square one...

**Comment by retorquere** [comment]
I'd have to look into jabref, but that'd require a user willing to co-test; I don't use jabref myself, and from what you describe, you don't either. 

I'd be happy to add the Eratosthenes groups format if you're interested (and willing to test), but if you need nested groups, and Eratosthenes doesn't do that, there would be little point. 

There are android clients for Zotero btw, but I can't speak to their quality, as I don't use them.

**Comment by ookimi** [comment]
I asked the developer of Eratosthenes if he plans to do anything about it - will report if he replies. But if not, it is a dead end indeed. And yes, I've given up JabRef ever since I found your plugin :)

I have tried three Android clients: Zojo, Zed, and Zotable (a new iteration of long-deceased Zandy). None of them are workable (sync issues, lack of attachments, or both), and none seem to be actively developed.

There is a new something called Aziz or ZedEx that looks promising, but that won't even install on my M96 onyx reader, so that's a no-go for me.

**Comment by ookimi** [comment]
For what it's worth, I can confirm that when I enabled the export of sub-collections, the export became very slow and never completed (3100 items in the library, according to zotero). It got back to norm with disabling the subcollections.

**Comment by retorquere** [comment]
What do you want to do on android? When I still tried years ago I thought I'd want to do tracking of what I read but nothing was even close to usable. One of those experiments was my zotero opds extension, but that was aimed at attachments more than the references they were on.

**Comment by retorquere** [comment]
That slowdown may just be a one time thing. BBT caches very aggressively but the cache needs to be built the first time.

**Comment by ookimi** [comment]
well, I have a huge library, and I want to be able to open a file without having to go to the computer to send it to the tablet. So basically I want to use the zotero collections to navigate to an item, and then open it from there (stored in dropbox). And unfortunately there is still nothing usable.

Side question: out of despair I am now playing with the built-in search by author and title in my reader. One useful thing that JabRef can do is write XMP metadata to pdfs themselves, which zotero can't do. However, better bibtex is providing me with all those braces and latex codes that are undesirable in this scenario:

Suffix {\emph{-Ness}} in {{Jane Austen}}'s {{\emph{Pride and Prejudice}}}

Is there a way to make BetterBibTex to output everything plain-text, as-is?

**Comment by retorquere** [comment]
I don't follow what you're trying to achieve. Do you want your full library navigatable and openable offline, on Android? I have no solution for you there. Full export even of large libraries ought to be feasible with BBT but the first time [will take a long time](https://github.com/retorquere/zotero-better-bibtex/wiki/Performance) and there's no way around that. Zotero 5.0 may or may not be better, if I ever find the time to make the move.

To answer your second question, there is no way that you would want to use. *Technically*, setting the language field of your references to non-English (it can be anything, as long as BBT can't sensibly decide that it could be English) will make BBT not export most of those braces, but that will very, very likely have side effects should the time come you need actual references rendered. There is no way to prevent `\emph{...}` to be output, but the language "trick" would prevent the braces around `Jane Austen`. I do not recommend that you do this however.
