### ISSUE TITLE
BibTeX export: omit "file=" paths

### ISSUE THREAD

**Issue by azrdev** [retorquere/zotero-better-bibtex#635]
I'm exporting BibTeX files from a bibliography with file (PDF) attachments. The exported entries contain a `file` attribute like `file = {description:/full/path/to/firefox/profile:mime/type; another attachment ...}`, which leaks the path to my firefox profile. I'd like to omit the `file` attribute from the bibtex file altogether, is that possible?

**Comment by retorquere** [comment]
Sure, just add `file` to the skip fields in the settings.

**Comment by azrdev** [comment]
Got it, thanks! I already had the impression I missed something obvious…

**Comment by retorquere** [comment]
The settings screen could use some UX attention, but it's not really my specialty.
