### ISSUE TITLE
Books exported with archive-place

### ISSUE THREAD

**Issue by adunning** [retorquere/zotero-better-bibtex#637]
Exporting a book to Better CSL JSON format that has something filled into the Zotero 'Place' field will export this information to `publisher-place`, `event-place`, and `archive-place`. Only the first two of these are used with the standard CSL JSON export in Zotero, and I think this would be preferable.

Including `archive-place` causes problems for styles that use this field; with MHRA style, for example, it means that the publisher place occurs twice in the citation.

Many thanks, as always, for your fabulous work on this.

**Comment by njbart** [comment]
I'd even argue that any sensible exporter should export the Zotero 'Place' field of a book to the CSL variable `publisher-place` *only*. Other variables, if needed, can easily be added via the 'cheater' syntax.

**Comment by retorquere** [comment]
So what would become the general rule for `Place` field? Which types have it, and what should it be mapped to?

**Comment by njbart** [comment]
Off the top of my head, practically all item types would be well served by exporting the 'Place' field to 'publisher-place' only. The only exception I'm aware of is 'Presentation', where 'Place' should be exported to 'event-place'.

**Comment by adunning** [comment]
I think that a conference paper would also take `event-place` (though properly it could have a place of both publisher and event, which Zotero doesn't yet allow).

**Comment by retorquere** [comment]
I've just looked and these item types have a `place` field:

* audioRecording
* book
* bookSection
* computerProgram
* conferencePaper
* dictionaryEntry
* encyclopediaArticle
* hearing
* manuscript
* map
* newspaperArticle
* patent
* presentation
* radioBroadcast
* report
* thesis
* tvBroadcast
* videoRecording

**Comment by retorquere** [comment]
As indeed there's always only one `place` field on a reference, if you guys can tell me what CSL fields should be filled with that `place` value, it's easy enough for me to make that happen.

**Comment by njbart** [comment]
As I said, practically all item types would be well served by exporting the 'Place' field to 'publisher-place' only. Bar one exception, it seems all of Zotero's 'Place' fields should be understood as describing a publisher's (or writer's, broadcaster's etc.) place (or location, address, etc.).

The only exception I'm aware of is 'Presentation', where 'Place' should be exported to 'event-place'.

('Interview' could be one other item where an 'event-place' might make sense, but this one currently does not even have a 'Place' field in Zotero.)

A conference paper, by contrast, is formally published (at least that's what Zotero/CSL assume), so its 'Place' field should be mapped to 'publisher-place'. Of course it might also make sense to indicate, in addition, an `event-place`, but this would have to be done via the 'cheater' syntax using the 'Extra' field.

**Comment by retorquere** [comment]
For some reason I added `archive-place` myself, that's not Zotero's doing. I can't trace it back to any issue ticket, so I'm just going to remove it.

**Comment by retorquere** [comment]
In Juris-M, but not Zotero, these input references (first block) give me the CSL in the second block. So either Juris-M generates wrong CSL (entirely possible, but the Juris-M author is also the citeproc author), or the rules for `archive-place` are more complicated than just for presentations.

```
{
      "itemType": "report",
      "place": "Place",
      "date": "2015",
      "extra": "editor: Editrix||Emma\neditor: Editor||Ed\n{:X-genre: xxx}",
      "institution": "Institution",
      "reportType": "working paper",
      "reportNumber": "77",
      "title": "A report",
      "creators": [{ "creatorType": "author", "lastName": "Author", "firstName": "Ann" }],
      "publisher": "Institution",
      "type": "working paper",
      "number": "77"
    },
    {
      "itemType": "tvBroadcast",
      "place": "US",
      "date": "1996-09-16",
      "extra": "bibtex: friends:leia:tv\nvolume: 3",
      "runningTime": "22 min",
      "network": "NBC",
      "language": "en-US",
      "episodeNumber": "1",
      "title": "The one with the Princess Leia fantasy",
      "programTitle": "Friends",
      "creators": [
        { "creatorType": "director", "lastName": "Mancuso", "firstName": "Gail"},
        { "creatorType": "scriptwriter", "lastName": "Curtis", "firstName": "Michael" },
        { "creatorType": "scriptwriter", "lastName": "Malins","firstName": "Gregory S." }
      ],
      "publisher": "NBC",
      "number": "1"
    },
    {
      "itemType": "videoRecording",
      "volume": "3",
      "place": "US",
      "date": "2003",
      "extra": "bibtex: friends:leia:dvd\ncontainer-title: Friends\nnumber: 1\noriginal-publisher: NBC\noriginal-date: 1996-09-16",
      "videoRecordingFormat": "DVD",
      "studio": "Warner Home Video",
      "runningTime": "22 min",
      "language": "en-US",
      "title": "The one with the Princess Leia fantasy",
      "creators": [
        { "creatorType": "director", "lastName": "Mancuso", "firstName": "Gail" },
        { "creatorType": "scriptwriter", "lastName": "Curtis", "firstName": "Michael" },
        { "creatorType": "scriptwriter", "lastName": "Malins", "firstName": "Gregory S."}
      ],
      "medium": "DVD",
      "publisher": "Warner Home Video"
    }
```

gives me

```
  {
    "author": [ { "family": "Author", "given": "Ann" } ],
    "editor": [ { "family": "Editrix", "given": "Emma" }, { "family": "Editor", "given": "Ed" } ],
    "event-place": "Place",
    "archive-place": "Place",
    "genre": "working paper",
    "id": "Author2015",
    "issued": { "date-parts": [ [ 2015 ] ] },
    "note": "{:X-genre: xxx}",
    "number": "77",
    "publisher": "Institution",
    "publisher-place": "Place",
    "title": "A report",
    "type": "report"
  },
  {
    "container-title": "Friends",
    "dimensions": "22 min",
    "director": [ { "family": "Mancuso", "given": "Gail" } ],
    "event-place": "US",
    "archive-place": "US",
    "id": "friends:leia:tv",
    "issued": { "date-parts": [ [ 1996, 9, 16 ] ] },
    "language": "en-US",
    "number": "1",
    "publisher": "NBC",
    "publisher-place": "US",
    "title": "The one with the Princess Leia fantasy",
    "type": "broadcast",
    "volume": "3"
  },
  {
    "container-title": "Friends",
    "dimensions": "22 min",
    "author": [ { "family": "Mancuso", "given": "Gail" } ],
    "event-place": "US",
    "archive-place": "US",
    "id": "friends:leia:dvd",
    "issued": { "date-parts": [ [ 2003 ] ] },
    "language": "en-US",
    "medium": "DVD",
    "number": "1",
    "original-date": { "date-parts": [ [ 1996, 9, 16 ] ] },
    "original-publisher": "NBC",
    "publisher": "Warner Home Video",
    "publisher-place": "US",
    "title": "The one with the Princess Leia fantasy",
    "type": "video",
    "volume": "3"
  },
```

**Comment by njbart** [comment]
To be clear, my impression is that Zotero's mapping of 'Place' to all three of 'publisher-place', 'event-place', and 'archive-place' was never anything but a crude hack to compensate for the lack of 'Event-place' or 'Archive-place' fields in Zotero. Now that we can use the 'cheater' syntax in the 'Extra' field (and are promised many more fields once 5.x is rolled out …), I see no reason at all not to get rid of that hack, in particular if it interferes with the proper functioning of some styles (the problem that motivated the original post).

**Comment by retorquere** [comment]
So you mean that it'd be best to actively scrub `archive-place` from CSL-JSON output unless the itemtype is `presentation`?

**Comment by njbart** [comment]
Not quite. I'd say:

1. If item type is 'Presentation', map 'Place' to 'event-place'.
2. For all other item types, map 'Place' to 'publisher-place'.
    - If 'event-place' is needed, too, users have to use the 'cheater' syntax.
3. Do not map 'Place' to 'archive-place', ever.
    - If 'archive-place' is needed, too, users have to use the 'cheater' syntax.

**Comment by retorquere** [comment]
Which would mean I'd have to actively scrub it from the CSL-JSON output, because Juris-M puts it there, not me.

**Comment by retorquere** [comment]
I may have forgotten to say that I augment the CSL-JSON that Zotero/Juris-M generates rather than constructing it from scratch.

**Comment by retorquere** [comment]
test version [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br637-3493.xpi)

**Comment by retorquere** [comment]
@adunning, still interested?

**Comment by adunning** [comment]
Oh, sorry; the test version worked for me.

**Comment by retorquere** [comment]
OK, then I'm scheduling a new round of tests with the latest changes from master -- if they pass, I'll merge into master and set up a new release.

**Comment by adunning** [comment]
Thanks very much!

**Comment by retorquere** [comment]
OK, the new release has this.

**Comment by adunning** [comment]
Thank you very much!
