### ISSUE TITLE
Initialize failed: TypeError: can't convert null to object

### ISSUE THREAD

**Issue by olafklingt** [retorquere/zotero-better-bibtex#638]
Platform: os x 10.10
BBT: 1.6.91
Zotfile: 4.29.15

I just noticed that the plugin is not working anymore after the automatic update. The following error message is displayed when I try to access the settings dialog: "Initialize failed: TypeError: can't convert null to object". Nothing else is shown and I can't see any other settings or options. Deactivating the add-on and activating it again was not able to solve this issue. Any thoughts on this?

here is the zotero log:
https://gist.github.com/olafklingt/87c661ba716f83562a78e30933197182

i read the other closed bug reports.
yes i have numbers in extra fields.

**Comment by retorquere** [comment]
Can you try [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-master-3509.xpi) version and put up a new zotero log? The TypeError doesn't have enough information, this version should also fail but explain better where.

**Comment by olafklingt** [comment]
The Debug ID is D947177789.

**Comment by retorquere** [comment]
That looks like a Zotero debug log submission; I don't have access to those. Can you put it in a gist again?

**Comment by olafklingt** [comment]
ah i thought i have seen people sending that id...

https://gist.github.com/olafklingt/3ab2ffda7da2a872debf590ba71b3da2

here is the log

**Comment by retorquere** [comment]
BBT has it's own debug log submission system but that only works if BBT has succesfully initialized. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br638-3521.xpi ? From the previous log I could see where it happens but not why.

**Comment by olafklingt** [comment]
thanks for your help. 
here is the log:
https://gist.github.com/olafklingt/81cd684747be41c66df0031a5d892dcf

**Comment by retorquere** [comment]
Apologies; I used BBTs logging -- which don't work if BBT didn't initialize. [This](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br638-3530.xpi) uses Zotero's own logging; could you please get me a new log using it?

**Comment by olafklingt** [comment]
this is the new zotero log:
https://gist.github.com/olafklingt/4ce5fc0edafeb6963c2c8c39d74a06dd

and this is what is printed on the bbt pane in Zotero:

Better BibTeX initialization failed: TypeError: can't convert null to object

[4]</</</Collection.prototype.remove@chrome://zotero-better-bibtex/content/lib/lokijs.js:4721:12
[4]</</</Collection.prototype.remove@chrome://zotero-better-bibtex/content/lib/lokijs.js:4716:11
[4]</</</Collection.prototype.removeWhere@chrome://zotero-better-bibtex/content/lib/lokijs.js:4692:7
_Class.prototype.purge@chrome://zotero-better-bibtex/content/db.js:381:12
Zotero.BetterBibTeX.init@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:339:5
load@chrome://zotero-better-bibtex/content/include.js:31:11

**Comment by retorquere** [comment]
I don't *get* it. I see where the error occurs but it shouldn't be able to get there. Can you try [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br638-3532.xpi) version and generate a new log?

**Comment by olafklingt** [comment]
ok no problem.

https://gist.github.com/olafklingt/a4d653e2bdb22cae7e99ca167573e1ce

Better BibTeX initialization failed: TypeError: can't convert null to object

[4]</</</Collection.prototype.remove@chrome://zotero-better-bibtex/content/lib/lokijs.js:4721:12
Zotero.BetterBibTeX.LokiJS.Collection.prototype.remove@chrome://zotero-better-bibtex/content/include.js:16:22
[4]</</</Collection.prototype.remove@chrome://zotero-better-bibtex/content/lib/lokijs.js:4716:11
Zotero.BetterBibTeX.LokiJS.Collection.prototype.remove@chrome://zotero-better-bibtex/content/include.js:16:22
[4]</</</Collection.prototype.removeWhere@chrome://zotero-better-bibtex/content/lib/lokijs.js:4692:7
_Class.prototype.purge@chrome://zotero-better-bibtex/content/db.js:381:12
Zotero.BetterBibTeX.init@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:339:5
load@chrome://zotero-better-bibtex/content/include.js:39:11

**Comment by olafklingt** [comment]
ah does it make a difference if i rebuild the cache? (mean for the log?)

**Comment by retorquere** [comment]
Yes, it would make a change. Can you try again with [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br638-3534.xpi)?

**Comment by olafklingt** [comment]
ok this time with cache rebuild.

https://gist.github.com/olafklingt/f8419a73a830a69d8b4f29487397f823

db.js load failed: TypeError: can't convert null to object

**Comment by retorquere** [comment]
Ah, I didn't mean for you to actually rebuild the cache. Are you sure you restarted Firefox after installing? I'm missing some logging. Can you try with [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br638-3535.xpi)

**Comment by olafklingt** [comment]
I use standalone zotero. 
and yes i restarted after installing.
https://gist.github.com/olafklingt/165a322b2ebc084656e6ab13afb6bb10

**Comment by retorquere** [comment]
Could you Quit Zotero, and get me a copy of `/Users/olaf/Library/Application Support/Zotero/Profiles/k3xi5rnf.default/zotero/better-bibtex/cache.json`? I know the origin of the TypeError now (https://github.com/techfort/LokiJS/issues/532) but not why it gets in that state. There must be something in that collection that does this but I have no idea how I'd even get it in there.

**Comment by olafklingt** [comment]
https://www.dropbox.com/s/q0g5davx7m8uv5u/cache.json?dl=0

i hope this helps


Am 31/1/17 um 4:16 pm schrieb retorquere:

**Comment by retorquere** [comment]
There are zeroes in your database, no idea how those could have gotten in there. This, however, should fix it:

1. Quit Zotero
2. Replace `/Users/olaf/Library/Application Support/Zotero/Profiles/k3xi5rnf.default/zotero/better-bibtex/cache.json` with [this version](https://mega.nz/#!F452wADZ!-5bft0ySJ69j_1Eug16co6seZ3nKGutM7CFg0494Pc4), where I've removed the mysterious zeroes.
3. Install [this BBT version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.91-br638-3539.xpi) and let it restart
4. ...
5. Profit

**Comment by olafklingt** [comment]
so now it works again, bbt got started.
here is the log:
https://gist.github.com/olafklingt/550e0dbb2d80a4f69ca10853b7bd62ea
thanks for fixing in my file a problem which is very likely not bbts fault :-/

**Comment by retorquere** [comment]
I'm still assuming it's my fault. The DB library I use is very robust, and it was my choice to use it even if it wouldn't have been.

**Comment by retorquere** [comment]
I've added some extra safeguards and will merge this into the new release. I'm sorry for the disruption.

**Comment by olafklingt** [comment]
no problem it didn't hit me in a pressures moment. but i maybe should switch off auto update a few month before having to hand in my thesis :-P ... should i test the new version with the old cache.json?

**Comment by retorquere** [comment]
The new version is just the version you have now but tagged with a new version number.

**Comment by olafklingt** [comment]
this is the log of the last version with the broken cache.json:
https://gist.github.com/olafklingt/ce40839c4062c0145966b4170124b781
which still fails. For the case it matters to you. 

As the file you send me works i am fine. 

thank you very much for your help and this software!

**Comment by retorquere** [comment]
That's still the same error unfortunately. The question is how this data could have gotten into your database -- once it's there, the failure is predictable, but there should have been no way to get this data in.
