### ISSUE TITLE
Better BibTeX single word strings in institution and publisher fields not recognized as @string vars

### ISSUE THREAD

**Issue by pubpsyclotech** [retorquere/zotero-better-bibtex#639]
In Better BibTeX, when the Fields preference "Assume single-word strings to be externally-defined @string vars, etc" is selected, the following fields are not translated correctly:

1. Item type:@report, field:institution, {} are added around the string in the exported file e.g.

 institution = {INSTITUT},

whereas it should be

 institution = INSTITUT,

2. Item type:@book, field:publisher, {{}} are added around the string in the exported file e.g

  publisher = {{PUBPH}},

whereas it should be

  publisher = PUBPH,

**Comment by pubpsyclotech** [comment]
Reading your very instructive site, I was able to fix it myself temporarily with a little code in the Postscript field.  Obviously this just removes the punctuation regardless of whether single word or words separated with spaces.  It would still be useful to have that functionality.

if (this.item.itemType === 'report' && Translator.BetterBibTeX) {
    if (this.item.institution) {
      this.add({ name: 'institution', replace: true, bibtex: this.enc_verbatim({value: this.item.institution}) });
    }
  }
if (this.item.itemType === 'book' && Translator.BetterBibTeX) {
    if (this.item.publisher) {
      this.add({ name: 'publisher', replace: true, bibtex: this.enc_verbatim({value: this.item.publisher}) });
    }
  }

**Comment by retorquere** [comment]
I do var preserve on a field-by-field basis. [This version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.93-br639-3550.xpi) adds `institution`, if this does what you want I will put it in the next release.

**Comment by retorquere** [comment]
You must be the first user to work through my atrocious documentation to this level :)

**Comment by pubpsyclotech** [comment]
The new version doesn't seem to work.  It is doing this for example for INST_ITU_T
  institution = {INST\_ITU\_T},

**Comment by retorquere** [comment]
I forgot one spot in the BibTeX translator. Try this one: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.93-br639-3553.xpi

**Comment by pubpsyclotech** [comment]
Thanks! The new version is now working for @report field institution.

However, for @book field publisher it is unchanged, i.e.
  publisher = {{PUB-PH}},
but should be for single word entry
  publisher = PUB-PH,

**Comment by pubpsyclotech** [comment]
Could you also add this functionality in @book field place? (address).

It is currently rendered as
  address = {PUB-DOVER:ADR},

Many thanks.

**Comment by pubpsyclotech** [comment]
Please would you add **@booksection** publisher

**Comment by retorquere** [comment]
New version available for testing [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.93-br639-3567.xpi)

**Comment by retorquere** [comment]
According to all tools I tested with (among which [jsonlint](http://jsonlint.com/)), that is valid JSON. What parser is choking on it?

**Comment by pubpsyclotech** [comment]
I tried the new version, and it is missing out many references, so I got 101 warnings.  I'll roll back to the previous version.

**Comment by retorquere** [comment]
I don't know what you mean with "missing out references".

**Comment by pubpsyclotech** [comment]
Many of the items in the bib file were not generated so I received many warnings such as "Warning missing reference for Grimm2007".  In other words not all the items in the library were generated.

**Comment by retorquere** [comment]
Could you (at least temporarily) install that last version again, enable extended debugging, and submit a bbt error report? That will probably tell me what's wrong. All my own tests pass on that version or I couldn't have given it to you.

**Comment by pubpsyclotech** [comment]
Not sure how to enable extended debugging but are the errors from the dialogue box and I sent you an error report.

[JavaScript Error: "config.doppel.origStrings[(quotePos + 1)] is undefined" {file: "chrome://zotero-better-bibtex/content/lib/citeproc.js" line: 15350}]
[JavaScript Error: "no element found" {file: "https://better-bibtex-error-reports-62200312.s3.eu-central-1.amazonaws.com/" line: 1}]

**Comment by retorquere** [comment]
The extended debugging setting is in the bbt preferences in the advanced pane.

**Comment by retorquere** [comment]
Can you right-click one of the references that don't export and send an error report from that menu? That will give me a copy.

**Comment by pubpsyclotech** [comment]
It says "Please wait while the error report is submitted".  It is just staying on this page, and not reaching the "continue" stage.

**Comment by pubpsyclotech** [comment]
OK I tried again and the ID is H362BZ6E

**Comment by retorquere** [comment]
Ugh and of course that reference exports without error for me. Can you see whether exporting only that one reference works for you? Maybe it only happens if you export many references and some kind of interplay happens.

**Comment by pubpsyclotech** [comment]
The single export works.  102 out of ~320 don't export into the .bib file.   It only becomes apparent when the file is completely regenerated, when the postscript  is changed for example.  I'm reverting back to 3553.

**Comment by retorquere** [comment]
Can you select those 320 references, right-click and send a debug report?

**Comment by retorquere** [comment]
(doesn't matter which BBT version you do that with)

**Comment by retorquere** [comment]
I know where the error is (it's in my use of the CSL titlecaser), but I don't know yet what triggers it, and I can't reproduce it here yet.

**Comment by pubpsyclotech** [comment]
Here's the error report ID: KWR3I74X

**Comment by retorquere** [comment]
All 320 exported using 3567 without issue. Can you try disabling all other extensions to see if one of them perhaps conflicts in some way with BBT?

**Comment by pubpsyclotech** [comment]
By extensions do you mean Add-ons?

**Comment by pubpsyclotech** [comment]
Is it possible for you to roll back the changes you made for me after 3553 as I can work around my additional requests using postscript

**Comment by pubpsyclotech** [comment]
I disabled both add ons, refreshed the .bib file and I still get the 102 warnings for items that don't export.

**Comment by retorquere** [comment]
You can just use 3553 if you want, but there really weren't any changes beyond flagging two more fields for variable preservation. That's what's so weird about this all. The code that errors out already gets called for a lot of fields, and it's not called for the two fields that I flagged extra in 3567.

With extensions I do mean add-ons, yes. You don't need to disable the LO/Word integrations. I'll just add those

**Comment by pubpsyclotech** [comment]
I am using the Postscript below with 3553 and my files.  I've adapted all my references to work with this.

if (this.item.itemType === 'report' && Translator.BetterBibTeX) {
if (this.item.institution) {
this.add({ name: 'institution', replace: true, bibtex: this.enc_verbatim({value: this.item.institution}) });
}
}
if (this.item.itemType === 'book' && Translator.BetterBibTeX) {
if (this.item.publisher) {
this.add({ name: 'publisher', replace: true, bibtex: this.enc_verbatim({value: this.item.publisher}) });
}
}
if (this.item.itemType === 'book' && Translator.BetterBibTeX) {
if (this.item.address) {
this.add({ name: 'address', replace: true, bibtex: this.enc_verbatim({value: this.item.address}) });
}
}
if (this.item.itemType === 'thesis' && Translator.BetterBibTeX) {
if (this.item.university) {
this.add({ name: 'school', replace: true, bibtex: this.enc_verbatim({value: this.item.university}) });
}
}

**Comment by retorquere** [comment]
This should do the same but should be less effort to add new cases to:

```
if (Translator.BetterBibTeX) {
  switch (this.item.itemType) {
    case 'report':
      if (this.item.institution) { this.add({ name: 'institution', replace: true, bibtex: this.enc_verbatim({ value: this.item.institution }) }); }
      break;

    case 'book':
      if (this.item.publisher) { this.add({ name: 'publisher', replace: true, bibtex: this.enc_verbatim({ value: this.item.publisher }) }); }
      if (this.item.address) { this.add({ name: 'address', replace: true, bibtex: this.enc_verbatim({ value: this.item.address }) }); }
      break;

    case 'thesis':
      if (this.item.university) { this.add({ name: 'school', replace: true, bibtex: this.enc_verbatim({ value: this.item.university }) }); }
      break;
  }
}
```

I've added the LO plugin to my tests but all tests pass. I'd have been surprised if that would have been the cause though. I still don't know what triggers this error in your installation.

**Comment by retorquere** [comment]
I'll go talk to the citeproc author; the error happens in citeproc, but it may be because of what I'm feeding it. That will typically take a while though, it's basically one guy doing all of citeproc and he's crazy busy.

**Comment by retorquere** [comment]
I've found where the error happens but it'll need help from the citeproc author to fix (see [here](https://github.com/Juris-M/citeproc-js/issues/35). In the meantime I have a reproducable test case that triggers it and a [potential workaround](https://github.com/retorquere/zotero-better-bibtex/issues/647) -- could you see if that workaround also removes the error for you?

**Comment by pubpsyclotech** [comment]
I installed zotero-better-bibtex-1.6.94-br647-3601.xpi regenerated the output and it all works as expected using your revised postscript from 8th Feb.    Many thanks!
