### ISSUE TITLE
[feature request] Add a possibility to select only the 2 last digits for year in citekeys

### ISSUE THREAD

**Issue by MatthieuPERIN** [retorquere/zotero-better-bibtex#640]
Hi, (first thanks for the awesome code)

I used to put 2 digit date format to shorten my citation key:

Kennedy1963Assassination -> Kennedy63Assassination

I would appreciate to have a simple [year-short] statement that give back the last 2 digit from year.

Formal behavior would be (Pyhton style)
````python
if len(year) >= 2 :
    return year[:2]
else :
    return "" 
    #(empty string to work with [>0] statement).
````

Tell me if you need more info, If you point me the right place I might be able to code it myself (even if I do not understand a thing about coffescript, but willing to learn :-) )

Have a nice day !

**Comment by retorquere** [comment]
Don't worry about coffeescript, it'll be replaced by ES6 after the 5.0 port.

Doesn't `shortyear` do what you want?

**Comment by retorquere** [comment]
closing for lack of feedback

**Comment by MatthieuPERIN** [comment]
Ouuuppps sorry for the lacks of answer :/ (vacation time :D)

Yeah `shortyear` does just what I want ! Havent found it on the Better Bibtex help page but found it hide in the JabRef help page.

Thanks for the info !

**Comment by retorquere** [comment]
Thanks for getting back. Glad it worked.
