### ISSUE TITLE
All fields exported in JSON export

### ISSUE THREAD

**Issue by tpoisot** [retorquere/zotero-better-bibtex#641]
The fields to omit from export are not omitted when exporting to Better CSL Json

**Comment by retorquere** [comment]
That is correct, the skipfields option only works for Better Bib(La)TeX. Which fields are causing trouble?

**Comment by tpoisot** [comment]
abstract and source, mostly. I've also tried removing them through a script, but to no avail.

**Comment by retorquere** [comment]
There's no technical barrier to adding postscript support to the CSL exporters; it would be harder for the skipfields, because you can't tell the translator where they're supposed to be active, and they may affect BibTeX processing. Also, the CSL isn't really a flat structure like bib(la)tex.

Why do you want these fields gone? The CSL styles I'm familiar with all ignore those two.

**Comment by tpoisot** [comment]
Some json parsers choke up on the weird sh|t that some publishers put on the abstract, and it's a problem before the CSL style.

**Comment by retorquere** [comment]
I have tests running on postscript support for CSL, but the case you describe means one of two things:

1. BBT outputs out-of-spec JSON
2. The JSON parser you use is broken

The JSON format is well defined and fairly rigid, including escaping rules and character set (utf-8 only); if you have a sample that breaks a JSON parser you use, I'd love to get my hands on it. There's really nothing I should even be able to put in the reference that would cause auto-of-spec JSON. I use JSON.stringify as supplied by Firefox -- I'd suspect the consuming parser before I'd suspect Mozilla would get JSON wrong.

**Comment by tpoisot** [comment]
Here is one such file (exported from BBT): https://gist.github.com/tpoisot/ebf13e9cc07e387d34e94a43e3c0918a

Interestingly, it doesn't render using JSONovich or any other JSON extension in firefox (which makes me suspect that some of the abstract content is breaking json).

**Comment by retorquere** [comment]
According to all tools I tested with (among which [jsonlint](http://jsonlint.com/)), that is valid JSON. What parser is choking on it?

**Comment by retorquere** [comment]
How is JSONovich supposed to work? I opened that gist in raw mode but I'm not seeing anything happening.

**Comment by retorquere** [comment]
JSON-dataview and JSON-formatter happily format that JSON file for me.

**Comment by retorquere** [comment]
And for JSONovich I don't see any errors in the web/developer console.

**Comment by retorquere** [comment]
closing for lack of feedback
