### ISSUE TITLE
Exporting more fields using BibTeX and renaming them

### ISSUE THREAD

**Issue by ajustine** [retorquere/zotero-better-bibtex#642]
Hi,

BetterBibTeX authorizes us to omit some fields from export, but could it be possible to include some more in those BibTeX exports ? For example, "conference name", "callNumber" or "archive" ?
And if possible, where in any JS file (or directly in BBT) could I rename those fields ?

My point is, I would like to use some "rare" Zotero fields to export some special BibTeX information that can't be written in any existing Zotero field, such as an internal identifying number for authors from our institution.
So I would like to be able to write this id in the "callNumber", export this callNumber with BBT and rename its label "x-onbehalfof" instead of callNumber...

Thank you very much !!

**Comment by retorquere** [comment]
You can add them in a [postscript](https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting) using something like

```
if (Translator.BetterBibTeX) {
  this.add({ name: 'callNumber', value: item.callNumber });
}
```

**Comment by ajustine** [comment]
Thank you very much for your answer !
Shall I just paste that in my postscript ? Nothing is happening...

**Comment by retorquere** [comment]
If nothing is happening, that would indicate either you have no callnumbers or you're not using BetterBibTeX. If you want it to work for both BetterBibTeX and BetterBibLaTeX, you can change it to

```
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ name: 'callNumber', value: item.callNumber });
}
```

**Comment by ajustine** [comment]
Hum... Sorry, it seems that my example with callNumber was not a good one since the field is in fact already imported by "classic" BetterBibTeX, but its BibTeX name is "lccn" and not callNumber. My bad.

So I tried
```
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ name: 'Archive', value: item.Archive });
}
```
but it doesn't work either, even if I do really have a Archive field in my Zotero reference...

**Comment by retorquere** [comment]
It may not be named exactly that. If you export a reference with "BetterBibTeX JSON" you get the exact field names to use.

**Comment by ajustine** [comment]
I'm afraid BetterBibTeX JSON tells me to use "archive"... Sorry :-s

**Comment by retorquere** [comment]
So that seems OK then. Fields are case-sensitive, so 

```
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ name: 'Archive', value: item.archive });
}
```

ought to work. Since you're not using any other configuration for the field, you could shorten it to

```
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ Archive: item.archive });
}
```

**Comment by ajustine** [comment]
I hate to say this but it still doesn't work... I must be doing something wrong but I cannot see what.

I have this journal article reference which includes some text in fields like Archive (JSON tells its name is archive), Loc. In Archive (archiveLocation), Library Catalog (libraryCatalog), Call Number (JSON tells its name is callNumber but BetterBibTeX exports it as "lccn") etc.

I cleared all the code I already had in my postscript and pasted the one you wrote.
Then I exported my reference using BetterBibTeX.
But those fields still don't appear in my .bib file...

**Comment by retorquere** [comment]
Sorry, that should have been

```
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ Archive: this.item.archive });
}
```

**Comment by ajustine** [comment]
Still nothing... sorry...

**Comment by retorquere** [comment]
Can you enable extended debugging in BBTs advanced prefs, trye the export again, and then submit a BBT error report?

**Comment by ajustine** [comment]
Done ! The ID is T22BVBJF.
Thank you very much !!

**Comment by retorquere** [comment]
No errors in that log. Can you right-click the reference which you're trying to export and send another debug report from that menu?

**Comment by ajustine** [comment]
Report ID: TGSM3VUP

**Comment by ajustine** [comment]
And here's what I get in my .bib file:
`@article{dupont_titre_2016-28,
  series = {Collection},
  title = {Titre de l'article de revue},
  volume = {50},
  copyright = {Autorisations de l'article de revue},
  issn = {ISSN},
  lccn = {Cote},
  shorttitle = {Titre abr{\'e}g{\'e}},
  doi = {10.1340/309registries},
  language = {FR},
  timestamp = {2016-11-22T10:11:58Z},
  number = {20},
  urldate = {2016-01-01},
  journal = {Titre de la revue},
  author = {Dupont, Jean},
  editor = {Bernard, Marie},
  translator = {{de Rotterdam}, Erasme},
  collaborator = {Durand, Pierre and Martin, Anne},
  month = mar,
  year = {2016},
  keywords = {Mot-clé 1,Mot-clé 2,Mot-clé 3},
  pages = {123 et suiv.}
}`

**Comment by retorquere** [comment]
If I export that I get the `Archive` added as expected. Could you try clearing your cache in the BBT advanced prefs?

**Comment by ajustine** [comment]
I tried with another computer and it still doesn't work... I am very puzzled.

**Comment by retorquere** [comment]
Can you change the postscript to what's below, make sure extended debugging is on, export again, and then submit an error report?

```
Zotero.debug("running postscript for " + JSON.stringify(Translator.header, null, 2));
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ Archive: this.item.archive });
}
```

**Comment by ajustine** [comment]
Done ! Report ID: 2KXTVICD

**Comment by retorquere** [comment]
OK, so the postscript is running. Change it to this and submit a new log, we'll get to the bottom of this.

```
Zotero.debug("running postscript: " + JSON.stringify({
  BetterBibTeX: Translator.BetterBibTeX,
  BetterBibLaTeX: Translator.BetterBibLaTeX,
  active: Translator.BetterBibTeX || Translator.BetterBibLaTeX,
  item: this.item,
  archive: this.item.archive
}, null, 2));
if (Translator.BetterBibTeX || Translator.BetterBibLaTeX) {
  this.add({ Archive: this.item.archive });
}
```

**Comment by ajustine** [comment]
Yes, the postscript is running perfectly well when I add some other code like this.add etc...

Anyway, here is the Report ID: X9FJVUUM

**Comment by retorquere** [comment]
I've just now noticed that you're on an older debug version -- could you install 1.6.93 first to see if that changes things? Don't know why you weren't upgraded automatically.

**Comment by ajustine** [comment]
IT WORKS !!!!! \o/
Hell, all that fuss only because of my older version... I feel deeply sorry that I wasted your time like this.
Anyway, it totally works. I can add all the fields I want, and rename them.
THANK YOU SO MUCH for your help and your patience !!

**Comment by retorquere** [comment]
Always a pleasure. You couldn't know the update mechanism had failed. You can of course remove the call to `Zotero.debug` now.

**Comment by retorquere** [comment]
(smacks forehead -- and now I know why you saw no output -- the shortcut `<field>: <value>` as an alias for `name: <field>, value: <value>` was added after the version you had, and BBT was thinking "you aren't giving me a value so I don't need to do anything")

**Comment by ajustine** [comment]
Thank you again for your help. I got another question, dealing with the same kind of problem: I am using some Zotero types that are unknown to BibTeX. E.g., when I have an `"itemType" : "presentation"` (according to BibTeX Json), my BibTeX export gives me a `@misc` reference.
Is there any way I could tell BBT to export my Zotero `presentation `as a `@poster` ?
Thank you very much !

**Comment by retorquere** [comment]
Sure, you can use something like

```
if (Translator.BetterBibTeX && this.item.itemType == 'presentation') {
  this.referencetype = 'poster';
}
```
