### ISSUE TITLE
Random lower-/upper cases in citation keys inserted in Scrivener

### ISSUE THREAD

**Issue by sfhd** [retorquere/zotero-better-bibtex#645]
Hi,

thanks a lot for this great add-on to Zotero! 

I use the BBT (1.6.94) to insert citation keys into Scrivener (2.8.1.2) with the help of Dave Smith's zotpick-applescript (more precisely: zotpick-pandoc for Scrivener.app). My citation key format looks as follows: [auth:lower]:[veryshorttitle:lower]. 

Everything's works fine except the following: each time, I get a different random distribution of lower and upper case letters. Here's what I got after I selected the same reference eight times in a row:

```
@Hume:treAtise
@HUMe:Treatise
@HUme:treatise
@HUME:TREatise
@HUme:treATIse
@HUme:TREATISE
@hume:trEATISe
@HUME:trEatise
```

My main question is whether this might happen because of the applescript or because of BBT - and how I could determine the culprit (unfortunately, I don't have any experience with scripts). 

The citation keys show up correctly in Zotero (i.e. 'hume:treatise' in this case), so my suspicion is that this might be a problem with the applescript.

The number of my submitted error report is PK7ZFJR4.

Any suggestions are much appreciated!

Thanks a lot for your help, and sorry if this has nothing to do with BBT (I also posted this message to Dave Smith's Github page),

Fabian

**Comment by retorquere** [comment]
Can you execute `/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?format=mmd` in the shell, pick a few references, and then tell me what is being spit out to the terminal?

**Comment by sfhd** [comment]
Thanks for the quick reply!

It spits out the citation keys alright (e.g. '#hume:treatise'). So I guess this means that it is a problem with the applescript?

**Comment by retorquere** [comment]
I checked in his repo and while I don't know exactly what the `.app` version calls, the generic scripts calls this URL. I don't control what happens to the keys beyond spitting them out when the URL is called. At the very least, @davepwsmith will have to help diagnose the problem.

**Comment by sfhd** [comment]
Okay, I'll see what he'll have to say and report back. I'll also try to create my own app from his script, to see whether that might work. Thanks again for your help!

**Comment by davepwsmith** [comment]
The app is just a packaged applescript. I'm afraid I haven't had a Mac for a couple of years now, and so the scripts haven't been updated for any changes. In theory they just copy and paste from BBT, so it's hard to imagine why you're seeing this.

**Comment by retorquere** [comment]
@davepwsmith can you confirm that your script is calling `http://localhost:23119/better-bibtex/cayw?format=mmd`?

**Comment by davepwsmith** [comment]
Yes, it is. Seems this is a known issue in Sierra? See:

http://stackoverflow.com/questions/41227700/applescript-keystroke-sometimes-capitalizing-letters

https://github.com/lionheart/openradar-mirror/issues/16313#event-853509911

I'm not maintaining the scripts any more, but @Jmuccigr should be able to update them if he has time.

**Comment by sfhd** [comment]
The script I'm using does indeed call `http://localhost:23119/better-bibtex/cayw?format=mmd`.

Executing the script on its own works fine. But once I turn the script into an application with the help of Apple's Script Editor, the output starts to randomly involve upper case letters.

**Comment by sfhd** [comment]
@davepwsmith, thanks for the info! 

I added the workaround suggested at the first link, modified the delay a bit, turned the script into an application, and now everything works as intended. 

It's really just a matter of changing keystroke command.

**Comment by retorquere** [comment]
The proper solution would of course involve the scrivener guys to implement integration points... Not that that's going to happen.

**Comment by mijalce** [comment]
@sfhd can I kindly ask you to share the complete script so I can use it. 
Thanks!

**Comment by Jmuccigr** [comment]
The app is indeed just the script compiled. I just tweaked the script to use that fix and pushed it to master. I'm on ElCap and it works fine for me. Please let me know though.

**Comment by sfhd** [comment]
@mijalce, you simply need to load the script in Apple's Script Editor and replace 

`keystroke theReference` 

with the following

```
repeat with letter in (theReference)
keystroke letter
delay 0.005
end repeat
```

After that, just save the script as an application and let Scrivener use it as the reference manager.

**Comment by retorquere** [comment]
nothing I can do on my end

**Comment by wodecki** [comment]
hi, 

I have the same problem, but my citekeys changed from lower case to upper case:

- in my BibTex lib (exported from Zotero) I have cite-key eg. wodecki2006
- curl http://localhost:23119/better-bibtex/cayw?format=mmd returns: 
[#wodecki2006][]%   
- in my markdown editor it results with WODECKI2006

I have changed the zot-pick script as above: replacing

`keystroke theReference`

with

```
repeat with letter in (theReference)
keystroke letter
delay 0.005
end repeat

```

but it didn't help.

My OS: Mac OS Mojave

Any idea? Many thanks in advance :)

Andy

**Comment by retorquere** [comment]
This issue can't be fixed on the BBT side. BBT outputs the correct text. If it can be fexied anywhere, it is over at https://github.com/davepwsmith/zotpick-applescript

**Comment by Jmuccigr** [comment]
For posterity: this error was local to the user. Fixed by a restart.
