### ISSUE TITLE
Issue exporting in ASCII code the spanish accented letter i

### ISSUE THREAD

**Issue by fpichardom** [retorquere/zotero-better-bibtex#646]
Report ID: ZC3DGJAB

When trying to export using the option better biblatex or better bibtex as ASCII it exports the spanish accented letter **i** as \\'\i instead of \\'i. Latex displays an error message wherever it finds that. So far I have only seen this happening with the i. Accents for other letters are exported good. 

As an example the author field in one of the entries displays like this:

author = {Mac{\\'\i}a, Manuel J and Armesilla, Pedro J and C{\\'a}mara-Leret, Rodrigo and Paniagua-Zambrana, Narel and Villalba, Soraya and Balslev, Henrik and Pardo-de-Santayana, Manuel}

**Comment by retorquere** [comment]
What error do you get? `\'\i` is the correct sequence to export - a regular `i` would have a dot which could misaligned with the accent character printed over it; the `\i` avoids that by printing an `i` without the dot.

**Comment by retorquere** [comment]
See e.g. https://en.m.wikibooks.org/wiki/LaTeX/Special_Characters

**Comment by fpichardom** [comment]
Ok, I see. It seems is a problem with biber, maybe?. When I write it in text like \\'\i it works. But if its part of the bib file using biblatex with biber I get these errors:

Package inputenc Error: Unicode char ́ (U+301)(inputenc) not set up for use with LaTeX. This is a test citation \parencite{macia2011}

[0] Config.pm:343> INFO - This is Biber 2.5 [0] Config.pm:346> INFO - Logfile is 'main.blg' [88] biber:290> INFO - === Wed Feb 15, 2017, 13:05:40 [285] Utils.pm:165> ERROR - main.bcf is malformed, last biblatex run probably failed. Deleted main.bbl [285] Biber.pm:113> INFO - ERRORS: 1 

I added the sample document I used here: [test_citation](https://github.com/fpichardom/test_citation.git)
With biblatex it only works if I remove the backslash before the i, but it seems to be working using natbib.

I tried it in Overleaf and then in TeXstudio with TeX Live installed.

**Comment by retorquere** [comment]
Hmm, [this](http://tex.stackexchange.com/questions/23817/biber-writes-incorrect-unicode-encoding-of-i) would indicate the `\i` is no longer required. @njbart?

**Comment by njbart** [comment]
> Hmm, this would indicate the \i is no longer required. @njbart?

Yes, that what it seems to say; but AFAICT this is only true for `\'i` ``\`i`` and `\^i`, but not for `\=i` and others.

Maybe it's easier not to modify BBT, but to have users either switch to xelatex (https://github.com/fpichardom/test_citation.git works fine for me this way with texlive 2016, biber 2.7), or, when using pdflatex, to add `--output-safechars` to the biber command line (works fine for me as well).

**Comment by retorquere** [comment]
@fpichardom would any of those options work for you? Changing the character translation to be specific to whether it's being for for BBT or BBLT would be quite involved.

**Comment by fpichardom** [comment]
Using xelatex with texlive version 2015.20160320-1 and biber 2.4 in Ubuntu 16.04 doesn't work properly. It gives no errors, but the result shows Maca instead of Macía for example. Using pdflatex and biber with the argument --output-safechars did work as intended though. This seems like a good option.
