### ISSUE TITLE
Export failing with javascript issue

### ISSUE THREAD

**Issue by dillonma** [retorquere/zotero-better-bibtex#650]
I get a javascript error when exporting. Report ID 23NRTF7R. Started happening sometime in the last couple weeks. Happens on both Better BibTeX and Better BibLaTeX exports.

[JavaScript Error: "config.doppel.origStrings[(quotePos + 1)] is undefined" {file: "chrome://zotero-better-bibtex/content/lib/citeproc.js" line: 15350}]

Would be happy to try to debug, not sure where to start. Windows.

Much appreciated.

**Comment by retorquere** [comment]
This is most likely a duplicate of #647 -- try the version I posted there. I'm talking with the author of the lib here the problem seems to occur.

**Comment by dillonma** [comment]
Yes, it is, cheers. For others, the link is [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.94-br647-3601.xpi) for version 1.6.94-br647-3601 which resolves this issue in 1.6.94 of BBT.

@retorquere you're a lifesaver. Cheers.
