### ISSUE TITLE
Cite as you Write not respecting pandoc format Quick Copy brackets preference

### ISSUE THREAD

**Issue by jpcirrus** [retorquere/zotero-better-bibtex#653]
With the following configuration:
Quick Copy Default Output Format: Better BibTeX Quick Copy.
QuickCopy format: Pandoc.
Surround Pandoc citations with brackets: checked.

Citations dragged from Zotero are formattted correctly with surrounding brackets.
Using Cite as you Write surrounding brackets are not applied but should be.

**Comment by retorquere** [comment]
CAYW has its own config; you can add the brackets by adding `brackets=yes` to the CAYW url.

CAYW is going to be out in the next few days BTW.

**Comment by jpcirrus** [comment]
Thanks, I had got the brackets working with the CAYW config you suggested. I had thought that the config would be mirrored but not a problem.
