### ISSUE TITLE
Export write relative file path in "file" entry

### ISSUE THREAD

**Issue by muahah** [retorquere/zotero-better-bibtex#654]
Linked to export for both BibTeX and BibLaTeX exports.

When exporting a reference with basic zotero exports, the `file` entry is populated with the path of the associated files (if any).
Depending on zotero options (preferences/advanced/files and folders/base directory), the path may be absolute or relative to a given folder.
When using Better Bibtex, paths are always relative to the main zotero folder, regardless of this option.
Is there any way of having absolute paths ?

**Comment by retorquere** [comment]
This is an export which does not export the attachments, and the BibTeX file is exported to a place outside the zotero directory?

**Comment by muahah** [comment]
> This is an export which does not export the attachments ?

I'm just exporting the .bib file

> the BibTeX file is exported to a place outside the zotero directory ?

I export the .bib in the zotero directory.
Should I understand that the path is intended to be relative when exporting to the zotero folder ?

**Comment by retorquere** [comment]
Yes, if the bibtex file is exported to a place where the attachments live under that directory, the path is relative, which works out to "if you export attachments, or you export to the Zotero data directory". If you export to a place that is not a parent of the attachments directory, the file paths should be exported as absolute paths.

**Comment by muahah** [comment]
Exporting to an another folder (not parent of the attachment directory) worked.
thanks.
I suppose this relative path functionnality is here to make easier moving around the zotero folder ?
