### ISSUE TITLE
pandoc-citeproc error when citation key includes "&" character

### ISSUE THREAD

**Issue by samkimhis** [retorquere/zotero-better-bibtex#655]
Report ID: 8W66A3N2

I tried to export to BibTeX or BibLaTeX from Zotero library and use pandoc-citeproc. The problem was that one of my citation keys generated by Better BibTeX contained "&". When I removed "&" manually, the pandoc-citeproc error was gone. I think "&" should be rejected from the citation key to prevent this kind of error.

**Comment by retorquere** [comment]
The submitted report only says "Zotero: 4.0.28.8, Better BibTeX: 1.6.95"; can you leave the checkbox in the first tab of the error submission dialog enabled? It submits information which I need.

Is there a particular reason you're still on Zotero 4.0.28.8?

**Comment by retorquere** [comment]
Ah wait, the info I needed was in the references. You have your citekey format at the default `[zotero]`, which has a lot of [known problems](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#configurable-citekey-generator). If you change it to pretty much anything else, or you post-filter it at least through `[zotero:nopunct]` or `[zotero:alphanum]`, I think the problem will go away. But the `[zotero]` pattern is broken-by-design as it aims to replicate the standard Zotero citekey generation precisely.

**Comment by samkimhis** [comment]
Thanks! That solved the problem
