### ISSUE TITLE
special characters and multiple-name authors citation keys

### ISSUE THREAD

**Issue by danilomm** [retorquere/zotero-better-bibtex#656]
Hi,

I've been using Better BibTeX for a couple of years, with pandoc-citeproc.
I have many articles written with citation keys generated with Better Bibtext in 2015.
However, many of them have changed. Namely:

1. The ones with special accented characters:
Before: the special characters were replaced by the equivalent non accented vowel. Now they are being omitted in the citation key.
i.e.:
Title: Geórgicas
Former key: silva_georgicas_1941
Current key: silva_gergicas_1941

2. The ones with multiple names in the author field.
i.e.
Author: Schlosser Magnino, Julius von
Former key: schlossermagnino_letteratura_1964
Current key: schlosser_magnino_letteratura_1964

3. Also, some prefixes previously ignored now are being considered.
i.e.
Title: L Antichita di Roma
Former key: palladio_antichita_1554
Current key: palladio_l_1554

Can I automatically retrieve the former keys, or should I manually edit each one?

All the best,
Danilo

**Comment by retorquere** [comment]
Can you submit an error report by right-clicking these entries? It could be that the library I use for transliteration has changed its behavior.

**Comment by retorquere** [comment]
closed for inactivity
