### ISSUE TITLE
Exported .bib causes error when using pandoc.

### ISSUE THREAD

**Issue by norbertschmidtnet** [retorquere/zotero-better-bibtex#659]
Report ID: I7NUHVDM (Extended Report ID: 7W3TDVTU)

I am having trouble using the exported .bib file with pandoc. The error occurs both when trying to use a file exported either as Better BibLaTeX or Better BibTeX.

Using a reference bib file from http://pandoc.org/demos.html (pandoc-demo.bib) does not result in said error, therefore I assume something is wrong with my exported bib file from the Better BibLaTeX plugin.

When exporting my library as **Better BibLaTeX** (myzoterolib-bbl.bib) the following error is thrown:

```
pandoc-citeproc: "stdin" (line 4750, column 2):
unexpected "r"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

When exporting my library as **Better BibTeX** (myzoterolib.bb) the following error is thrown:

```
pandoc-citeproc: "stdin" (line 4184, column 2):
unexpected "t"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

The error is the same no matter whether the option "Export BibLaTeX as ASCII" is checked or not.

Better Bib(La)TeX version 1.6.96.

Any hints for solving this issue would be greatly appreciated.

The attached zip file contains both library files mentioned as well as my markdown document and the pandoc reference bib file which works.
[bibexport-error.zip](https://github.com/retorquere/zotero-better-bibtex/files/966717/bibexport-error.zip)

**Comment by retorquere** [comment]
My guess from that error would be that pandoc doesn't support `techreport` or `report`. But that'd be an error in pandoc, because according to both [BIBTEXing](http://ctan.cs.uu.nl/biblio/bibtex/base/btxdoc.pdf) and [Tame the BeaST](http://www.lsv.fr/~markey/BibTeX/doc/ttb_en.pdf), `techreport` is a valid BibTeX entry type, and according to the [the biblatex manual](http://mirror.unl.edu/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf), `report` is a valid BibLaTeX entry type.

**Comment by norbertschmidtnet** [comment]
Following your guess I exported a subset of my library excluding reports and that indeed resolved the issue. (At least as long as I'm not citing one of those reports.)

I'll seek further help on the pandoc mailing list then.

Thanks a lot for the incredibly fast reply and the clarification!

**Comment by retorquere** [comment]
My pleasure. It is possible to alter the reference type in a [postscript](https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting) (although the how of it isn't yet documented there), but having pandoc fixed is obviously a better long-term solution.

**Comment by norbertschmidtnet** [comment]
Just a quick follow up to document the cause of the issue, found thanks to Joost Kremers on the pandoc mailing list:

pandoc-citeproc seems to be ok with ampersands anywhere but in a reference's key.

I had one reference in my library that ended up with an & in the citation key and that caused pandoc to throw the error reading the .bib file.

Since I couldn't just change the citation key manually in Zotero, my workaround now was to change the & in the editors field to an "And". Technically that's now not 100% correct anymore, but will work for me for now as it was only that one reference.

I'm not sure whether pandoc will or can be fixed to accept ampersands in keys.

Maybe a possible workaround could be to avoid generating citation keys with ampersands (no idea whether there are other characters that would cause a similar issue).

This is the reference that caused the issue for me:
```
@report{orrick_herrington_&_sutcliffe_llp_balancing_2014,
  location = {{London}},
  title = {Balancing Purpose and Profit - {{Legal}} Mechanisms to Lock in Social Mission for “Profit with Purpose” Businesses across the {{G8}}},
  url = {http://www.trust.org/contentAsset/raw-data/1d3b4f99-2a65-49f9-9bc0-39585bc52cac/file},
  timestamp = {2017-04-30T15:13:35Z},
  langid = {english},
  editorb = {{Orrick, Herrington \& Sutcliffe LLP} and {UnLtd} and {Thomson Reuters Foundation}},
  editorbtype = {redactor},
  date = {2014-12},
  file = {2014-balancing_purpose_and_profit_-_legal_mechanisms_to_lock_in_social_mission_for.pdf:/Users/norbert/Documents/eBooks/zotero/2014-balancing_purpose_and_profit_-_legal_mechanisms_to_lock_in_social_mission_for.pdf:application/pdf},
  groups = {21E16000 Sustainable Business and Consumption,25E18000 Sustainable Entrepreneurship,21E16000 Sustainable Business and Consumption,25E18000 Sustainable Entrepreneurship,21E16000 Sustainable Business and Consumption,25E18000 Sustainable Entrepreneurship}
}
```

**Comment by retorquere** [comment]
The earlier error points unambigously to the `techreport` and the `report` text:

```
pandoc-citeproc: "stdin" (line 4184, column 2):
unexpected "t"
```

The ampersands in the key is a different problem (and would be spotted at a different column in the bibfile in the pandoc error log); you have your citekey pattern set to the default `[zotero]`, which [inherits all of the problems of the standard zotero key generator](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#configurable-citekey-generator).

**Comment by retorquere** [comment]
(that means if you change your citekey pattern, the ampersand problem will go away)

**Comment by norbertschmidtnet** [comment]
I just found issue #602 and and changed my citekey pattern right away.
This seems to have solved the issue entirely.

I don't know about the `report` or `techreport` texts, as they are still in my now working .bib file.

But thanks a lot for your support! Everything seems to be working now.
