### ISSUE TITLE
Errors on export - not sure what's causing them

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#661]
This affects both BibLaTeX export and BibTeX export. The ID is QK4AKWPW.

Every export gets the errors, and I can't figure out which items are causing the problem.

**Comment by retorquere** [comment]
Is there a reference with a date field that says simply `unknown`?

**Comment by retorquere** [comment]
Or perhaps with an `?` or `uu`? I have a fix, but I'd love to get my hands on a reference that triggered the error to add to my test suite.

**Comment by retorquere** [comment]
Can you try [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.96-br661-3730.xpi) version?

**Comment by lyndondrake** [comment]
Many apologies — I missed the reply at the time. It was indeed corrupt data in the date field, but I don't have the examples any more, which I realise is a nuisance.

**Comment by retorquere** [comment]
The dates cannot be corrupt -- whatever is in that field, BBT must respond appropriately. In this case I suspect there was a valid EDTF date in the field which BBT didn't handle properly.
