### ISSUE TITLE
question: is it possible to integrate ZBB into a workflow based on visual studio code?

### ISSUE THREAD

**Issue by DrGo** [retorquere/zotero-better-bibtex#662]
hello,
I am not familiar with ZBB, but I need a way to integrate Zotero citations into my writing workflow which is currently based on editing markdown in visual studio code.

Any tutorials/suggestions/ideas will be greatly appreciated,

Thanks,

**Comment by retorquere** [comment]
Depends on what you mean by integrate. There is an HTTP api that can be called to reach into BBT, and there are [atom](https://github.com/retorquere/zotero-citations) and [brackets](http://wasifbaig.com/brackets-zotero/) extensions that call into it for various needs. Architecturally these two should work very similar to VSC extensions, but neither of them will just drop in and work.

What do you want an integration to do?

**Comment by DrGo** [comment]
Thanks for the prompt reply,
I found the atom extension you mentioned, a similar extension for VSC will be great, allowing for searching and inserting citations and then formatting the in-text citations and bibliography. 
Do you know of anyone working on such extension?
Another question, do you know of a Golang implementation of the Zotero API?
Thanks

**Comment by retorquere** [comment]
I'm not aware of anyone working on a vscode version, no. 

To my knowledge there's no golang implementation of the zotero api, nor of the bbt api (should you mean to access that, they're not the same).

**Comment by mblode** [comment]
Hey @retorquere and @DrGo, 
I have just released a VS Code extension that integrates with Zotero and Better Bibtex. Please let me know your thoughts and whether this solves your problem. Thank you :)

https://marketplace.visualstudio.com/items?itemName=mblode.zotero

**Comment by DrGo** [comment]
wonderful! Thank you very much Mathew.
