### ISSUE TITLE
retain "date-added" and "date-modified" fields

### ISSUE THREAD

**Issue by maxheld83** [retorquere/zotero-better-bibtex#663]
Thanks for the fantastic work.

I noticed that ZBB retains the original "date-added" and "date-modified" fields from a BibDesk-generated `*.bib` in the Zotero `Extra` field, such as:

```
bibtex{"date-added":"2016-08-20 09:21:14 +0000","date-modified":"2016-08-20 09:21:14 +0000"}
```

That is great.

Could ZBB also write this data into the respective "native" Zotero fields?

I'd like to retain this information, if at all possible.

**Comment by retorquere** [comment]
Translators are not allowed to write those fields; a change in Zotero would be required to make this possible.

**Comment by maxheld83** [comment]
thanks!

So this is blocked until [Zotero enables writing to date modified fields](https://github.com/zotero/zotero/issues/1229).

(Opened an issue).

**Comment by retorquere** [comment]
That is correct, and thanks for opening that issue.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5321](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.73.5321.issue-663.xpi) ("value").

**Comment by retorquere** [comment]
Until Zotero adds this capability I have for the time being added [this](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#patchdates)
