### ISSUE TITLE
raise error if bibtex fields for Extra are not properly processed

### ISSUE THREAD

**Issue by maxheld83** [retorquere/zotero-better-bibtex#666]
*if* my hypothesis for the behavior in #664 is correct (that ZBB *silently* chokes on `ac3.bib`), then it'd be nice if ZBB could raise a ruckus in such an event.

It might be disorienting for the user (as it was for me) when there is (among other things) no `Extra` field, though that *would* be expected of a successful ZBB run.

**Comment by retorquere** [comment]
This was a different error - but the error handling facilities of zotero translators are incredibly limited. All a translator can do is reject the whole import with only the literal message "an error has occurred", which doesn't give the user any info to correct the error.
