### ISSUE TITLE
Feature request: Option to use et al. in author list if >5 authors

### ISSUE THREAD

**Issue by lrperlmu** [retorquere/zotero-better-bibtex#668]
It would be useful to have a checkbox in the Export tab of BetterBibTeX options, offering the following option:

If there are 6 or more authors, replace author names after the first author with et al.

Exporting with BibTeX
Error report ID: FDDSQHHR  -- this is an example of a publication with 6 or more authors.

Thank you!!!

**Comment by retorquere** [comment]
The "etal" patterns (https://help.jabref.org/en/BibtexKeyPatterns) should get you close. I'd prefer not to add more toggles if it can be avoided.

**Comment by lrperlmu** [comment]
@retorquere thanks for the quick response! I realize I was a bit vague in my request.

To clarify, this is the line exported by Zotero (using Better BibTeX) to my .bib file:

`author = {den Bergh, M. Van and Carton, D. and Nijs, R. De and Mitsou, N. and Landsiedel, C. and Kuehnlenz, K. and Wollherr, D. and Gool, L. Van and Buss, M.},`

And this is what I'd like the line to be:

`author = {den Bergh, M. Van and others},`

So that the author is rendered as "M. Van den Bergh et al." when I include the .bib file in a latex document using the `\bibliography` command.

Your link describes how to use etal patterns to describe patterns for citation keys. Can they also be used to customize the author field that gets exported to the .bib file? After some poking around in the options, I haven't been able to figure out how to do this.

**Comment by retorquere** [comment]
I see, but this should be done in the bibliography processor/style, not the bibliography manager. https://tex.stackexchange.com should be able to get you information on how to achieve this.

**Comment by retorquere** [comment]
(this also has localization ramifications - much better handled in a bib style)

**Comment by lrperlmu** [comment]
ok, thanks!
