### ISSUE TITLE
Drag-and-drop yields bibtex entry, not citation key

### ISSUE THREAD

**Issue by TilmanHartley** [retorquere/zotero-better-bibtex#669]
Report ID: KBAKTA66

When I try to drag-and-drop, instead of a citation key I get the bib entry. For example, where I would expect to have the inline text `\cite{darwin_origin_1859}` I get the entry `@book{darwin_origin_1859, title = {On the {{Origin}} of {{Species}}}, publisher = {{London: John Murray}}, author = {Darwin, C. R.}, date = {1859}}`.

My settings in the Better BibTeX tab are:
- Citation key format: `[zotero]`;
- QuickCopy format: all options drop the bib entry, including `LaTeX` and `Cite Keys`;
- LaTeX command: `cite`.

My settings in the Zotero Export tab are:
- Default Output Format: `Better BibTex`.

Drag-and-drop worked as expected a couple of weeks ago, and I don't think I have changed much since then. I have switched every setting in those tabs back and forth, restarting after each attempt. Thanks

Linux x86_64 Linux x86_64, Firefox 52.0.2, Zotero 4.0.29.19, Better BibTex 1.6.96.

**Comment by retorquere** [comment]
Setting the quick copy format to Better BibTeX Quick Copy should do it.

**Comment by copark86** [comment]
For those who have no idea where to find the "Better BibTeX Quick Copy",
Edit->Preferences-> Export tab -> Default Output Format

Thanks for the nice add-on!

**Comment by ygechn** [comment]
> For those who have no idea where to find the "Better BibTeX Quick Copy",
> Edit->Preferences-> Export tab -> Default Output Format
> 
> Thanks for the nice add-on!

Hi for the latest version, I just cannot find the option as you mentioned above, could you help me to find an updated path? Thank you.

Edit->Preferences-> Export tab -> (not sure what this step is) Default Output Format

**Comment by retorquere** [comment]
It's still in the same place:

<img width="714" alt="QuickCopy" src="https://user-images.githubusercontent.com/132108/64544738-cb545e00-d327-11e9-898c-904ec9ea8b6a.png">

**Comment by ygechn** [comment]
Thank you so much,

I think previously I go to the wrong place (Better Bib Tex button), now I found it.
