### ISSUE TITLE
citation-key based on file-name

### ISSUE THREAD

**Issue by nikadon** [retorquere/zotero-better-bibtex#673]
Thanks for brilliant add-on! **citation-key based on file-name** feature would be a day saver for users who rely on Emacs, where a `citation-key` can be used to quickly open `citation-key.pdf`... Is it possible? If not, would it be very hard to add?

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.97-br673-3755.xpi with `[attachment]` for the pattern? Note that if multiple references *across your library*, not just across any collection in it, have the same attachment file name, they'll be getting `attachment-name`, `attachment-namea`, `attachment-nameb` etc as citation keys. This is not changeable (and won't be), unless you manually pin the citation key.

It's also possible to go the other way around BTW; if you have ZotFile and BBT installed, you can use `[%b]` in the file rename pattern; `[%b]` will expand to whatever citation key BBT generated. This already works in the current release versions of ZotFile and BBT, no need to install this pre-release.

**Comment by nikadon** [comment]
Works like a charm. However I didn't know about the "other way around" that you have pointed out. It might be handier to use it as filenames contain whitespace characters replaced by "_" and that char can cause problems in bibtex/biber and LaTeX. (I will try if I can force zotfile to use "-" instead of "_" not only for the authors separation, but as any whitespace characters replacement, also I haven't tested the `[%b]` yet)

Anyway, the feature that I have kindly asked for works perfectly well. Thanks a lot!

**Comment by retorquere** [comment]
This isn't yet merged to main; I've reopened this as a reminder to do so Tuesday when I have access to my dev system.

**Comment by nikadon** [comment]
alright.
