### ISSUE TITLE
Very slow startup even after clearing cache manually

### ISSUE THREAD

**Issue by rcoreilly** [retorquere/zotero-better-bibtex#674]
I filled debugging report id: CTGSU22A  -- I and several others in my lab had recently experienced very slow startup even after attempting to clear the cache (we have a very large lab database of citations, over 22k).  I looked in my firefox profile files and it did not seem that the cache.json file was any smaller recently than in the previous saved versions.  I manually removed the latest one and it still didn't startup any quicker.  Then I turned on debugging messages and finally after that restart it started up quickly! Hopefully you can see something in the logs..

It also did not prompt me about clearing the cache, like it usually does, after recent firefox updates.

**Comment by retorquere** [comment]
Going one-by-one:

1. All that I can see in that log seems sync related. BBT doesn't show up at all. If you hadn't enabled it already, can you enabled extended debugging in the BBT prefs and submit a new log? Unfortunately the logs I can capture don't have all the logging from the start -- the first zotero logging activity goes to the console, not the log file. If the new log doesn't show anything relevant we can capture that, but it's a bit of manual work on your part (which is fortunately doable under MacOS)
2. If you deleted the cache.json but left the cache.json.[1-4] it will pick up those and just be on its way. You'll need to delete all cache.json files to be sure you're starting from an empty cache. Deleting the cache is harmless.
3. Deleting the cache should make things slower, not faster.
4. Turning on debug logging should make things even slower.
5. A Firefox upgrade shouldn't trigger the cache-clearing message, only a BBT of Zotero upgrade should.

So unfortunately we still don't have a good lead on what's the cause of the slow startup. Have you tried disabling BBT to see if that consistently leads to better startup time? It wouldn't surprise me in the least but it'd be good to have confirmation on that. If we know that I can start putting out instrumented builds to see what part of BBT is causing the slow load.

**Comment by rcoreilly** [comment]
Ok, well right now it is starting up fast, and my cache files are now very small (4kb) whereas they used to be much larger (unfortunately I lost the screen with that on it so I don't know exact size).

My general experience over the past year or so is that:
1. periodically firefox startup gets very slow -- I unscientifically associate this with updates of some sort
2. clearing the BBT cache fixes it -- startups are then fast until event 1 occurs again.  Note also that I'm talking about starting the firefox app, not exporting my .bib file -- my mental model of the situation is that a bad / old cache is being checked during startup.. note also that if I do not clear the cache, it was always slow -- clearing the cache and regenerating seemed to be an essential step.

And this time, the main difference was that step 2 didn't fix it, and judging from the file sizes, it seems like perhaps the clear cache button didn't work properly.

I will re-generate the cache and turn on debugging when I next experience the slowness and send you those reports!

**Comment by retorquere** [comment]
The cache is currently only filled when you export using BBT. Cache pre-fills will likely be part of the 5.0 port, but as long as you don't export anything, the cache files will hold only registrative overhead. At this time, the cache is not regenerated if missing, all that you'll see is an empty DB showing up in preparation of a later fill.

BBT doesn't do any cache validation on startup. it will occasionally scan for stale items, but even for 22k references that should be unnoticeably fast, and it only happens somewhere 10 seconds after startup the first time.

There haven't been many updates lately (you can see them [here](https://github.com/retorquere/zotero-better-bibtex/releases)), but for a 22k cache, you should see the cache-clear popup every time for those upgrades, unless you haven't exported much. But if the delays are associated with BBT doing something with the cache, then it would not be out of the ordinary for this to delay the startup of FF. Zotero starts up with FF, and BBT starts up with Zotero.

Looking forward to those logs. If it is also possible to test if the slowdown happens without BBT, that would be great. I currently can't think of anything cache related that happens at startup which would take a lot of time.

**Comment by rcoreilly** [comment]
On several occasions I disabled BBT and that fixed the slow startup, so that was definitely the cause.  I'll see if someone else in my lab is still experiencing slow startup and can send the logs.

**Comment by jmol048** [comment]
I'm another member of the group using the same large shared library, I can confirm that disabling BBT also fixed slow startup for me. I am also experiencing the slow startup, even with debugging enabled. I have filed this debug report id after enabling debugging and still getting a very slow startup: KVMHCAD7

**Comment by retorquere** [comment]
There's a key-rescan in that log, and key rescans take a lot of time, but the log reports it's user-initiated (which could be an error). In the logfile I can see it is set to `true`, which simply shouldn't occur -- after the key scan, it should be reset to false. Can you set it to `false` and restart and see if that fixes things? This will have no relation to whether the cache is removed or not BTW.

**Comment by jmol048** [comment]
Hi- which file do I need to change to set scanCitekeys to false? Where would it be located? Or do I need to open zotero and change that in the better bibtex preferences?

**Comment by retorquere** [comment]
Sorry - you type `about:config` in the address bar and press enter.

**Comment by jmol048** [comment]
That definitely fixed it! Thanks so much! Startup is fast now.

**Comment by retorquere** [comment]
Could you try something for me? Set that setting back to `true`, install [this version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.97-br674-3757.xpi), and restart. It'll be slow to start, but after it's started it should be set to `false` and stay there. If that works (it does here), I'll merge this fix to master.

**Comment by retorquere** [comment]
(I still have no idea how clearing the cache could have any influence over this behaviour)

**Comment by jmol048** [comment]
Hi - I installed that version, waited for Zotero to start up (it was slow as you said), then checked the about:config and scanCiteKeys was set to false. I then restarted (it was fast this time), and checked the about:config and scanCiteKeys was still false. So your fix looks good! Thanks again.

**Comment by retorquere** [comment]
Super, thanks for the confirmation. You don't have to install another version, I'll merge this into a new release, and you'll be upgraded automatically.

**Comment by retorquere** [comment]
OK, merged to the new release. You'll get the upgrade automatically.
