### ISSUE TITLE
Capitalisation problem on export

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#676]
I'm trying to export the following item title to BibLaTeX:

`a-na 1/2 GÍN-šú GAL-bi`

which tends to get somewhat randomly capitalised. In particular, the 'n' of a-na, the 'š' of '-šú', and the 'b' of '-bi' all get capitalised. How can I prevent this?

**Comment by lyndondrake** [comment]
And just for clarity, it's the export that alters the capitalisation. This is from the ` .bib ` file:
`title = {\{a-Na 1/2 \vphantom\}{{GÍN}}-Šú {{GAL}}-Bi},`

**Comment by retorquere** [comment]
If you set the language of the reference to anything non - English, no capitalization will be done.

**Comment by retorquere** [comment]
Or you can enclose parts of the title with `<span class="nocase" >... </span>`

**Comment by lyndondrake** [comment]
The ` span ` class worked perfectly. Thanks!

**Comment by retorquere** [comment]
This is not merely for BBT btw - the capitalization would also have been done by zotero itself, and the span trick will also work there.
