### ISSUE TITLE
Can't get JSON5 or CSL fields to export using "extra" field

### ISSUE THREAD

**Issue by lyndondrake** [retorquere/zotero-better-bibtex#677]
If I use this syntax in my BibLaTeX-exported Zotero record:

` bibtex[shortseries=WBC;referencetype=commentary] `

But JSON5:

```
bibtex{
  shortseries: WBC,
  referencetype: commentary
}
```

or CSL:

```
{:shortseries: WBC}
{:referencetype: commentary}
```

don't have any effect on the exported file. I'm probably doing something wrong, but I can't figure out what! For this example, the ` bibtex[…] ` syntax works fine but I have some others where I want more flexibility.

**Comment by retorquere** [comment]
The first isn't valid json5, as the values (like "WBC") need to be single or double quoted, so the whole block is ignored, and the second doesn't have recognized csl keys, so these keys are ignored.

**Comment by lyndondrake** [comment]
Yep, that was it - error between keyboard & chair I'm afraid :-) Thanks for the quick response

**Comment by retorquere** [comment]
No worries, this is all vastly underdocumented.
