### ISSUE TITLE
generic quick-copy launch for external program on linux [feature request]

### ISSUE THREAD

**Issue by faraway1nspace** [retorquere/zotero-better-bibtex#679]
Hi!

Would it possible to make a generic external program quick-copy? It would be similar to the orgmode output, but would also point to the zotero binary:
`"/opt/zotero/zotero` --url zotero://select/items/0_" + `item.__citekey__`

The problem would be that the location of the binary may vary from installation to installation, and wouldn't work on windows or mac. And of course this is specific to the zotero standalone, not the FF plugin, which would be something like "firefox zotero://select/..."

My intention is to quick-copy the output to Freeplane so that I can MindMap my zotero items.

**Comment by retorquere** [comment]
As of Zotero 5 there is only standalone. You mean you'd want to have the quick copy export something that has a binary path included? If Zotero installs an UTRL handler (it might if you have installed the connector), it may just work using the [play around](https://github.com/retorquere/zotero-better-bibtex/wiki/Cite-as-you-Write#playing-around) option of quick copy.

**Comment by retorquere** [comment]
Still interested?

**Comment by faraway1nspace** [comment]
Yes, still very much interested!

**Comment by retorquere** [comment]
So all you'd need is a quick-copy format that outputs 

```
/opt/zotero/zotero --url zotero://select/items/<library ID>_<item key>
```

and you'd use this output in some way to select items in zotero? Because if all you want to do is select items, you wouldn't need to launch zotero, a browser would do.

The `item key` is not the same as `citekey` BTW. Which of the two do you want to select by? Or doesn't it matter and you're happy as long as the item gets selected?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4775](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4775.issue-679.xpi) ("first stab at #679").

**Comment by faraway1nspace** [comment]
> The item key is not the same as citekey BTW. Which of the two do you want to select by? Or doesn't it matter and you're happy as long as the item gets selected?

Yes, so long as the item gets selected, I don't care about citekey vs itemkey. 

>  Because if all you want to do is select items, you wouldn't need to launch zotero, a browser would do

Yes, I know I must have zotero-standalone running. The point is to allow 3rd-party connections. For example, A mind map is a visual representation of items, where an "item" can be a line-of-code like this quick-copy export that points to an article in Zotero. Therefore, I can use this quick copy to build a MindMap of zotero items, where each item literally points to the item.

**Comment by retorquere** [comment]
I understand, but if all works well, just clicking a `zotero://select/items/<library>_<key>` should launch zotero if it is not already running, and then select the item in question. There would be no need for the `/opt/zotero/zotero --url` bit. Zotero registers itself as the `zotero://` protocol handler.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4778](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4778.issue-679.xpi) ("fallbacks").

**Comment by faraway1nspace** [comment]
Yes, I see what you mean. My original suggestion was linux specific (https://forums.zotero.org/discussion/comment/289119#Comment_289119) and the method you suggest ( zotero://select/items ) seems to work outside of linux. The forum link also suggests that it can work on Ubuntu with some minor effort on my end (something about registering a process)

**Comment by retorquere** [comment]
It'd be better to see if the problems with launching zotero can be fixed before adding a new quick export option. If Zotero would work as expected here I could just add a select-link quick export, which would require no further preferences to be added.

**Comment by faraway1nspace** [comment]
Well, I'd say that so long as the zotero://select/items/ quick-copy functionality is anticipated to work with windows and Mac, and maybe eventually with linux (seems to be solved with a simple edit to a .desktop file), then I would appreciate it!!

But if there are other issues with the zotero://select/items method, then, yeah, maybe it is not worth it yet.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4793](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.38.4793.issue-679.xpi) ("Merge branch 'master' into 679").

**Comment by retorquere** [comment]
This build has a 'select link' quick copy option, see if that works for you.

**Comment by faraway1nspace** [comment]
Okay, I will try it tomorrow. Thanks!

**Comment by retorquere** [comment]
So...

**Comment by faraway1nspace** [comment]
I was looking in the CONTRIBUTIONS.md file and trying to install node 7.1 ruby on Ubuntu 16.1. Is all that necesary to build the xpi file? Or do you have an xpi readily available?

**Comment by retorquere** [comment]
That's what 4793 was for, but these auto-builds expire automatically. I've scheduled a new build that includes this feature; it will be announced here shortly by blip-bloop as 4877.

The `CONTRIBUTIONS.md` instructions are only for those that want to build locally and run the test suite; for building you need node, for the test suite you need node+ruby. But for testing any particular build you just need to download is not too long after it's announced.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4877](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4877.issue-679.xpi) ("Merge branch 'master' into 679").

**Comment by retorquere** [comment]
Any progress?

**Comment by faraway1nspace** [comment]
The quick-copy shortcut produces an error: "An error occurred while trying to export the selected file". But I think that is a Zotero issue, because it happens for other quick-copies too.
If instead I do an Export Item..., and choose Better BibTex Quick Copy, then export to a file, and then read that file, the file contains the expected item: something like zotero://selection/items/0_ABCDEDF

Thanks for this! I guess the issue is in Zotero

**Comment by retorquere** [comment]
Before you report that to Zotero, could you go to `Help`, `Debug Output Logging`, `Restart with Logging enabled`, reproduce the error, and send a BBT error report? Wouldn't be the first time I affected Zotero, and I'd like to make sure it's not my fault that stuff is not working before bothering the Zotero devs.

**Comment by retorquere** [comment]
the link that you showed is what I'd expect BTW, so that part seems to work as expected

**Comment by faraway1nspace** [comment]
I got the output for two types of errors: 1) Debug Output Logging (14597 lines) of text when trying to do a quick-copy with BBT; and 2) right-clicking on a zoterio item and selecting "Report Better Bibtex Errors" and copying the pop-up output. Would you like me to raise a new Github issue with those outputs attached as txt, or attach here or something else?

**Comment by retorquere** [comment]
If you click `Next` on the dialog you get for option 2, the error log will be submitted to a place where I can get it. You will be presented with an alphanumeric ID -- if you post that here, I can take it from there.

**Comment by faraway1nspace** [comment]
Sorry, but the dialogue for "Report Better Bibtex Errors" doesn't have a next button (on Unity nor on i3wm). Its a yellow window that reads: "XML Parsing Error: undefined entity
Location: chrome://zotero-better-bibtex/content/ErrorReport.xul
Line Number 28, Column 27:      &helpMenu.label; -- &debugOutputLogging.label; -- &debugOutputLogging.restartWithLoggingEnabled;
--------------------------^"

... with no options to close window or any buttons.

**Comment by retorquere** [comment]
What version/platform of zotero are you on?

**Comment by faraway1nspace** [comment]
5.0.4 from a ppa (cogscinl)

**Comment by retorquere** [comment]
Sorry, I only support the latest version -- 5.0.28 at this time. I'm doing this alone, and I can't afford to support more than one version. Cogscinl (are you Dutch?) carries 5.0.23 if I'm not mistaken -- you can see if that work.

**Comment by faraway1nspace** [comment]
Okay I updated to zotero 5.0.28 and re-installed the test-build BBT.
Here is the report ID: DHPZA3HM

**Comment by retorquere** [comment]
The error is mine, but I don't know why it occurs. Can you try 4925? It doesn't change anything, but adds logging, so with a new debug log I'll be able to say more.

**Comment by faraway1nspace** [comment]
Okay, report ID for 4925: 38UQG4RI

**Comment by retorquere** [comment]
Can you go into the Help -> Debug Output Logging -> Restart with logging enabled, and then send a new debug log after the error occurs? It looks like my translators are not being installed and that you're using an older one. That's fixable but I'd prefer to know for sure.

**Comment by faraway1nspace** [comment]
Yes, I got the output for 1 quick-copy  and 1 drag-and-drop attempt. 
Should I submit or attach here?

**Comment by retorquere** [comment]
Just a report id would be preferable if possible. The restart with debugging enabled will put more information in the log.

**Comment by faraway1nspace** [comment]
Debug ID: D656670240 sent to zotero. I made the errors with a quick-copy "select links" and then a drag'n'drop attempt (both failed).
Happy Thanksgiving and Cryptopocalypse.

**Comment by retorquere** [comment]
I should have expressed myself clearer - I need a "better bibtex error report", not the regular error report. I can't access the zotero error reports, those go to the zotero devs.

We don't do Thanksgiving where I live :) is the cryptocalypse already upon us this year? Better to go backup this repo to clay tablets quickly then.

**Comment by faraway1nspace** [comment]
Lol, so many ways to submit. Sorry about confusion. 

Report ID: 3JEV9DJV
Okay, that is output from Help--> Debug Output Logging->Enable...; then doing one quick copy attempt (fails with error prompt); and then two unsuccessful drag-n-drops; then Help->Report Better Bibtex Errors...

**Comment by retorquere** [comment]
Sorry I have to ask, but are you sure that you restarted after clicking the "Enable" button? I'm missing the whole startup of Zotero, and that's the part of the log I need.

**Comment by faraway1nspace** [comment]
Duh! Let me know if this is good (>9000 lines):
XIPKRPHW

**Comment by retorquere** [comment]
Yeah, that confirms what I thought. Damn, that's a shame, it means I'll probably have to reinstall the translators every startup.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4949](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4949.issue-679.xpi) ("Merge branch 'master' into 679").

**Comment by retorquere** [comment]
Can you try 4949?

**Comment by retorquere** [comment]
So....

**Comment by faraway1nspace** [comment]
Sorry, I get a same error. Here is a Report ID: WQNLDQ7V

**Comment by retorquere** [comment]
The startup sequence is not in the log (and the problem happens in the startup sequence), can you restart with debugging enabled, replay the problem, and submit a new debug log?

**Comment by retorquere** [comment]
Apologies, I wasn't looking at the right log, the startup is there.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4968](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4968.issue-679.xpi) ("should be the same?").

**Comment by retorquere** [comment]
Can you try 4968?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4973](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4973.issue-679.xpi) ("Merge branch 'master' into 679").

**Comment by faraway1nspace** [comment]
Same error: VW4QPWQZ. Good luck!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4996](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4996.issue-679.xpi) ("more logging -- what is going on here?!?!").

**Comment by retorquere** [comment]
It still thinks it's already installed the newest versions. Can you try 4996, and submit a new log (after restart with debugging -- I need the startup sequence)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5000](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5000.issue-679.xpi) ("Merge branch 'master' into 679").

**Comment by faraway1nspace** [comment]
Hi, I went ahead and tried the 5000 build. Here is the report ID: KU3FGLEU
Good luck!

**Comment by retorquere** [comment]
Note to self: `lastUpdated` is not in the included header. But that's not the problem, if anything, it should over-fix it.

@faraway1nspace can you get me a copy of `/home/rob/Documents/Literature/translators/Better BibTeX Quick Copy.js`?

**Comment by retorquere** [comment]
Lucky you, you have a brand new error I've not seen before 🙄 . I've posted a question on [zotero-dev](https://groups.google.com/forum/#!topic/zotero-dev/j_FdSB3psmI), hoping they can get me in the right direction.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5009](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5009.issue-679.xpi) ("include lastUpdated").

**Comment by retorquere** [comment]
OK, so don't expect this build to fix things, but could you get me a debug log anyway?

**Comment by faraway1nspace** [comment]
I renamed it as a txt file so I could upload, hope that's okay. Here is Better Bibtex Quick Copy.pj
[Better_BibTex_Quick_Copy_js.txt](https://github.com/retorquere/zotero-better-bibtex/files/1515028/Better_BibTex_Quick_Copy_js.txt)

**Comment by faraway1nspace** [comment]
Errors for 5009: NQANPDM7

**Comment by retorquere** [comment]
OK now I'm just pissed.

In the logs it says "not reinstalling 2017-11-29 18:20:36"; that means BBT is being told 2017-11-29 18:20:36 is installed when the version you attached says "2017-04-19 17:54:02".

Try 5010 when it drops in a few minutes (plus new log yada yada), but if that doesn't work I'm going for more drastic measures. Which will make BBT start up slower than it has to, but jeez louise, I need to have this fixed.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5010](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5010.issue-679.xpi) ("explicitly cache in DB").

**Comment by faraway1nspace** [comment]
same error: EL793245
Hang in there! From my end, I am happy to help. Gives me an opportunity to give back to the zotero community from which I have taken a lot of benefit. Good luck!

**Comment by retorquere** [comment]
Same error, but not the problem I posted to zotero-dev about... can you attach `/home/rob/Documents/Literature/translators/Better BibTeX Quick Copy.js` again? This time it looks like Zotero just straight-up misinforms me -- when I ask it 'what version do you have of `Better BibTeX Quick Copy.js`' it says ` 2017-11-29 18:53:22`, but I'm fairly sure at this point that you don't have this version.

**Comment by faraway1nspace** [comment]
Okay, here is  the js file renamed as a txt
[Better_BibTex_Quick_Copy_js.txt](https://github.com/retorquere/zotero-better-bibtex/files/1519173/Better_BibTex_Quick_Copy_js.txt)

**Comment by retorquere** [comment]
Still 2017-04-19 17:54:02. I have no idea why Zotero is telling me you have `2017-11-29 18:53:22` installed. Can you check two things for me:

* Is the `translators` directory and/or `Better BibTeX Quick Copy.js` read-only (I don't think it is the case, and it shouldn't matter, as Zotero is telling me I need not overwrite them)?
* Can you get me a copy of your database somehow?

I have one last option, which is just stupid but it might work; I'll get you a new build within an hour or so. I'd prefer to find out what's happening, but if you're fed up with it, you can reset your translators and restart. If you do this the problem will most likely be resolved, but I won't be able to find the cause.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5013](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5013.issue-679.xpi) ("manually check version").

**Comment by retorquere** [comment]
And a new log from 5013 please.

**Comment by faraway1nspace** [comment]
I'm not getting fed up. Don't worry, I'd like to get this working.
As for the .js file: it is not read only, nor is the directory. The directory is nested within a directory that is symlinked to a data partition with the following parameters: ext4 (rw,relatime,data=ordered), for what that is worth.
Error report of 5013 build: E3PJPSVQ
As for sending you my database: how would I do that? Send just the sqlite file, or the storage and translators directories as well? I can compress and put them on a Pydio share drive (like dropbox)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5022](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5022.issue-679.xpi) ("curiouser and curiouser").

**Comment by retorquere** [comment]
Please try a new log with 5022. It's just nuts; I'm reading the installed translator *from disk*, and it says it has the newest version already. Was E3PJPSVQ directly after a restart? So install, restart *with debugging*, send-log? That's what I need, not install, restart, restart with debugging, send-log. I need to have a log of that translators being installed.

Pydio will do fine; what I need is just the sqlite file (the zotero.sqlite, not better-bibtex.sqlite)

**Comment by faraway1nspace** [comment]
for 5022: 2NCH48LE  For this ID, I did: install, restart with debugging, try ctrl+c, send-log. But, you are correct in that for all previous submissions, I did: install, restart, restart with debugging. Sorry, I just followed the prompts.

I will get the share link for the sqlite db shortly...

**Comment by faraway1nspace** [comment]
http://sesync.us/mcb80

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5030](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5030.issue-679.xpi) ("more logging, and use async save").

**Comment by retorquere** [comment]
You couldn't have known about the startup sequence. Nothing of note in the DB -- try 5030, you know the spiel by now.

**Comment by retorquere** [comment]
This is just nuts. A recap of what I'm seeing:

* BBT says the old translators are not installed, both by asking Zotero, and looking on disk. No translators. Which makes sense, because an extension upgrade is technically an uninstall + install, and BBT removes the translators at uninstall.
* Because no translators exist, BBT installs the bundled translators. Zotero gives the thumbs-up.
* You try to export, and somehow magically a very old version reappears (which you've attached a few times now), and the export fails.

This is just crazy.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5060](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5060.issue-679.xpi) ("uninstall old translator").

**Comment by retorquere** [comment]
I am a moron.

You have been consistently telling me what the problem was, and I just failed to pick up on it. You are using `Better BibTeX Quick Copy`, which was renamed a while ago to `Better BibTeX Citation Key Quick Copy`. Installing 5060 will get rid of the defunct translator; set the quick-copy translator to `Better BibTeX Citation Key Quick Copy` and it should work.

**Comment by faraway1nspace** [comment]
I generated a 5060 log: 595YVAJU
I see that the "Export items.." now just has the Better BibTeX Citation Key Quick Copy. That works as expected.
It doesn't produce an error when I do Ctrl+C quick copy. However, the item doesn't copy to my clipboard. I think it may be a zotero issue because neither do the other quick-copy types, like Latex.

**Comment by retorquere** [comment]
Does it copy to the clipboard for one of the standard translators when you uninstall BBT?

**Comment by faraway1nspace** [comment]
Yes, I can do normal Quick-Copies when BBT is uninstalled.

**Comment by retorquere** [comment]
Can you get me a new log from 5060 doing a quick-copy with a standard Zotero translator (e.g. `RIS`)?

**Comment by retorquere** [comment]
In `595YVAJU` you still had the export format set to the defunct `Better BibTeX Quick Copy` BTW.

**Comment by faraway1nspace** [comment]
Sorry, my bad. It totally works now: quick-copy pasted to clipboard. I had done it wrong in my previous post because I forgot to set the Quick-Copy field in the Export tab to BBT Citation Key Quick Copy.  I made an error report, in case you are interested: R6EHSD57
One minor thing, if I use BBT Quick Copy and the "select link", and then I highlight two items and do Ctrl-C, then it concatenates the two items to one line, e.g., zotero://select/items/0_PQK3PMTQzotero://select/items/0_DJELQ7SJ
... whereas it might be better to have a break or ; or something like with your other export formats.
Otherwise, looking great!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5082](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.51.5082.issue-679.xpi) ("separate select-link with newlines").

**Comment by faraway1nspace** [comment]
Works as expected! Thanks a lot for your hard work and tenacity with the BBT!
