### ISSUE TITLE
Omit field option only partially worked on BibTeX export

### ISSUE THREAD

**Issue by Laadr** [retorquere/zotero-better-bibtex#680]
Hi !
I am using BibTex export on a subcollection and I use the preference option to omit particular fields. As explained, I write a comma-separated list of the fields to omit but the resulting bibtex file does not fit my settings. Fields have been omitted only for a few references and are still there for some references. I hope you could find the solution to this problem.
Thanks for your great work !

**Comment by retorquere** [comment]
Can you try clearing the cache in the advanced settings?

**Comment by Laadr** [comment]
I clear the cache but it did not solve the issue. Nevertheless, I can specify a bit more the issue now. In my case, I want to omit the doi field which appears in the exported bibtex. And it still appears for two references which have in common to be two books. I also notice that in zotero the doi field of this two ref is specified in the field "Extra" (even it appears as a doi field in the export) and I think this may be the problem.

**Comment by retorquere** [comment]
That was sort of by design - the thought being that if you've taken the effort to put it in the extras field, you want it there.

**Comment by Laadr** [comment]
Maybe I was not specific enough. The references I was talking about have actually been generated automatically with IEEE explore. The thing is that there is no doi field in zotero for book. That's why the doi is save in the field 'extra' of zotero. But then when you want to export it as bibtex, the export process creates a doi field and it is no more an 'extra' field in your bibtex file. If you try to ignore it with the omit option, it is not possible. Asking to omit 'doi' or 'extra' has no effect.

**Comment by retorquere** [comment]
I think I understood, but previously this was intended behavior: what was in `extra` for whatever reason was deemed a manual override and thus always put in. But give [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.99-br680-3767.xpi) a go to see if it does what you need.

**Comment by Laadr** [comment]
It works perfectly now. Thank you for great work and your incredible reactivity !
