### ISSUE TITLE
Autocapitalization with english language entries

### ISSUE THREAD

**Issue by aleimba** [retorquere/zotero-better-bibtex#681]
Hi @retorquere,

first of all, Better Bib(La)TeX is pretty fantastic. Makes Zotero really great for LaTeX, thanks for all your efforts.

I saw that you put a lot of work into the capitalization issue with english titles etc. #383. However, it would be great if autocapitalization could be made optional (maybe an option in the preferences). In life sciences are only very few journals that use a title-case style instead of a sentence-case style. Probably because there are too many exceptions for species, gene name camel-cases etc.

This is an example for one of my entries in my Better BibLaTeX exported BIB file (my title in Zotero is `Genome sequence analyses of two isolates from the recent <i>Escherichia coli</i> outbreak in Germany reveal the emergence of a new pathotype: Entero-Aggregative-Haemorrhagic <i>Escherichia coli</i> (EAHEC)`):

```
@article{brzuszkiewicz_genome_2011,
  title = {Genome Sequence Analyses of Two Isolates from the Recent {{{\emph{Escherichia}}}}{\emph{ Coli}} Outbreak in {{Germany}} Reveal the Emergence of a New Pathotype: {{Entero}}-{{Aggregative}}-{{Haemorrhagic}} {{{\emph{Escherichia}}}}{\emph{ Coli}} ({{EAHEC}})},
  volume = {193},
  issn = {1432-072X},
  doi = {10.1007/s00203-011-0725-6},
  shorttitle = {Genome Sequence Analyses of Two Isolates from the Recent {{Escherichia}} Coli Outbreak in {{Germany}} Reveal the Emergence of a New Pathotype},
  number = {12},
  journaltitle = {Arch. Microbiol.},
  author = {Brzuszkiewicz, Elzbieta and Thürmer, Andrea and Schuldes, Jörg and Leimbach, Andreas and Liesegang, Heiko and Meyer, Frauke-Dorothee and Boelter, Jürgen and Petersen, Heiko and Gottschalk, Gerhard and Daniel, Rolf},
  date = {2011-12},
  pages = {883--891}
}
```

For me it feels wrong to set the language for all my entries to a different language if they are actually english ... Is this possible to do?

Thanks a lot in advance.

Cheers,
Andreas

**Comment by retorquere** [comment]
For the record, there are biblatex styles that do the right thing given the output BBT generates (which is in spec); it shouldn't be necessary to say they're not English. I'm a little surprised those life science journals don't use styles that generate the desired output given in-spec references.

That all said, if you go into `about:config` and search for `suppressTitleCase` and set it to `true`, BBT will not do any titlecasing ever. I don't want to add it as an exposed option because I'm still unsure whether I should have/keep it. Technically, Bib(La)TeX expects english references to be title cased and the styles would then bring them back to sentence case where desired. Setting the option to true technically brings BBT out of spec.

**Comment by njbart** [comment]
One more thing: You should also enclose species names and other stuff where processors must not meddle with capitalization with `<span class="nocase">…</span>` tags, e.g.

`<span class="nocase"><i>Escherichia coli</i></span>`

If you don’t, Zotero itself will not render this correctly either if using a title-case style.

**Comment by aleimba** [comment]
Thanks for your fast responses! Setting `extensions.zotero.translators.better-bibtex.suppressTitleCase` to `true` worked for me, brilliant!

I'm pretty new to the whole style thing (seems awfully complicated), so there surely are life science journal styles that are according to specs (which I'm just not aware of). I'm using `bibstyle=authoryear` (with `backend=bibtex8` in the `classicthesis` package), which apparently uses the BIB titles as is. `classicthesis` is already complicated enough to run in my Ubuntu without worrying about all the other stuff ...

@njbart Yep, I saw `<span class="nocase">…</span>` in one of the issue threads here. Just with 300+ references it's no fun to do so much manual work of `<i>...</i>` etc. (even with batch conversions).

Anyways, thanks a lot guys!

**Comment by retorquere** [comment]
Styles *are* complicated, and to be honest, I know that technically there are styles that do sentence casing but I couldn't name you one. But this really should be something the journal ought to provide.

**Comment by aleimba** [comment]
For sure, thanks! Closing the issue now (at least it might be useful for others in the future).
