### ISSUE TITLE
Suggestion for Improving the Explanation of Pinning

### ISSUE THREAD

**Issue by IsaacDodd** [retorquere/zotero-better-bibtex#682]
Better Bib(La)Tex is a great extension to Zotero and is the sole reason why I switched from another Reference Manager to Zotero. My compliments to you Emilio on creating such a useful and very powerful extension idea and please be encouraged to continue to maintain it.
**My Request**:
For Tools -> Preferences -> Better Bib(La)Tex -> **Updating Citation Keys**
The explanation here for the two options is very confusing and there does not appear to be much of an explanation in the documentation as to what is meant by these options. Further documentation or illustrations of the concept of auto-pinning and key changes in the context of using a citation in a LaTeX .tex file versus not having used the citation would be helpful. I understand conceptually what it is these options are trying to achieve but the explanation here is not at all clear. Thank you.
![image](https://user-images.githubusercontent.com/4949675/27997033-2840272e-64bd-11e7-8fdf-6041bb39192f.png)

**Comment by retorquere** [comment]
Pinning will be reworked substantially for Z5

**Comment by IsaacDodd** [comment]
Okay, thank you.
