### ISSUE TITLE
Current version not compatible with Zotero 5.0.4

### ISSUE THREAD

**Issue by kendonB** [retorquere/zotero-better-bibtex#686]
It gives me the error that says it may not be compatible with my version of zotero.

My zotero database upgraded to the new version so I also can't (or at least don't know how to) revert back to an old version.

**Comment by retorquere** [comment]
BBT is indeed not yet compatible with Zotero 5.0. Work on this is underway and is being tracked under #555.

I don't know how to revert a database to the 4.0 version. If it is synced I *think* you can just sync afresh with 4.0 for the time being. The Zotero devs have said to me they keep backups during the upgrade, but I haven't tried any backout scenarios myself.

**Comment by kendonB** [comment]
For any googlers, I followed the instructions here to get back https://www.zotero.org/support/kb/newer_db_version
