### ISSUE TITLE
Chinese bibtex 

### ISSUE THREAD

**Issue by qiuzhu** [retorquere/zotero-better-bibtex#688]
I just found when I  export bibtex when the item include some chinese title or author , the export key is just like this format :_2014, the author is missing
for example:
@article{__2008,
  title = {{关节型机器人二指平动手爪的设计}},
  issn = {1672-6413},
  lccn = {14-1319/TH},
  language = {中文;},
  timestamp = {2017-06-13T14:23:22Z},
  number = {05},
  journal = {机械工程与自动化},
  author = {苏, 子昊 and 孔, 庆忠},
  year = {2008},
  note = {00005},
  keywords = {二指平动手爪,机器人,运动分析,movement analysis,robot,two-finger translation gripper},
  pages = {80--81+84},
}
how to fix this ?

**Comment by duncdrum** [comment]
Hi qiuzhu I use [juris-m](https://juris-m.github.io) for multi-lingual bibliographies, but with regular Zotero you might want to try to change the citation key preference (zotero->preferences ->better biblatex ->citation keys) to ``[auth][year][0]`` see if that helps. 

Even if that works, you might still want to take a look at juris-m. greetings

**Comment by retorquere** [comment]
Yeah that's almost certainly the default `[zotero]` pattern at work. BBT5 will have `[auth][shorttitle][year]` as its default.

**Comment by qiuzhu** [comment]
@retorquere thank you for your reply，and shortite will be great，looking forward to bbt5，hoping bbl5 can add new feature just like jabref that can interact with latex editor app(texstudio) ，for example，right click the item will appear “export to texstudio”

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 HUAWEI EVA-DL00 发送_

**Comment by retorquere** [comment]
Please file a separate feature request for that.
