### ISSUE TITLE
German umlaut in author name

### ISSUE THREAD

**Issue by kitingChris** [retorquere/zotero-better-bibtex#69]
I just realized that the export has a small bug:

The german umlaut "sharp s" (ß) in the authors name is exported wrong:

```
Däßler, Klaus
```

expected output:

```
D\"{a}{\ss}ler, Klaus
```

actual output:

```
D\"{a}\ss ler, Klaus
```

Thanks in advance

**Comment by zsteinmetz** [comment]
I'd also opt for parentheses around \ss. Otherwise you lack a space when the first author name ends e.g. with ß followed by an et al. In such cases you get Maaßet al. instead of Maaß et al.

**Comment by retorquere** [comment]
Can you open a new issue with a debug report for this?
