### ISSUE TITLE
interact with latex editor app(texstudio)

### ISSUE THREAD

**Issue by qiuzhu** [retorquere/zotero-better-bibtex#690]
hoping bbl5 can add new feature just like jabref that can interact with latex editor app(texstudio) ，for example，right click the item will appear “export to texstudio”

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5002](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5002.issue-690.xpi) ("fixes #690").

**Comment by retorquere** [comment]
please try 5002. `texstudio` must be in the `PATH` for this to work.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5004](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5004.issue-690.xpi) ("TeXstudio").
