### ISSUE TITLE
Z5: Export stops without a key in the "Extra"-field

### ISSUE THREAD

**Issue by Wekhrlin** [retorquere/zotero-better-bibtex#694]
With beta v. 3907, BBT exports just fine, when there is a key set in the "Extra"-field. Without it stops with the following log:

> [JavaScript Error: "No citation key in {"version":5067,"itemType":"journalArticle","volume":"1","pages":"48–58","publicationTitle":"Der neue Teutsche Merkur","date":"1790","title":"Ueber reelle und persönliche Majestät","creators":[{"firstName":"Karl von","lastName":"Knoblauch","creatorType":"author"}],"tags":["Knoblauch","Volkssouveränität","konstitutionelle Monarchie","Französische Revolution"],"collections":["F6KX3H2S","A4AMQ4AK"],"relations":{"dc:relation":["http://zotero.org/users/1772795/items/A7PS3KTJ"]},"dateAdded":"2014-01-29T08:32:17Z","dateModified":"2016-08-31T15:41:39Z","uri":"http://zotero.org/users/1772795/items/DF6TSRD9","attachments":[{"version":6562,"itemType":"attachment","title":"knoblauch_ueber_1790.txt","parentItem":"DF6TSRD9","linkMode":"imported_file","contentType":"text/plain","charset":"windows-1252","filename":"knoblauch_ueber_1790.txt","tags":[],"relations":{},"dateAdded":"2017-07-14T11:40:23Z","dateModified":"2017-07-14T11:40:24Z","uri":"http://zotero.org/users/1772795/items/9SKPCAKB","itemID":2103,"journalAbbreviation":null,"localPath":"/Users/ml/Zotero/storage/9SKPCAKB/knoblauch_ueber_1790.txt"},{"version":4764,"itemType":"attachment","title":"Ueber_reelle_und_persnliche_Majestt.pdf","parentItem":"DF6TSRD9","linkMode":"imported_file","contentType":"application/pdf","charset":"","filename":"Ueber_reelle_und_persnliche_Majestt.pdf","tags":[],"relations":{},"dateAdded":"2016-08-31T15:49:38Z","dateModified":"2016-08-31T15:49:38Z","uri":"http://zotero.org/users/1772795/items/NBG7QVD6","itemID":1361,"journalAbbreviation":null,"localPath":"/Users/ml/Zotero/storage/NBG7QVD6/Ueber_reelle_und_persnliche_Majestt.pdf"}],"notes":[{"key":"N7QHXUNR","version":6541,"itemType":"note","parentItem":"DF6TSRD9","note“:“…“,“tags":[],"relations":{"dc:relation":["http://zotero.org/users/1772795/items/A7PS3KTJ","http://zotero.org/users/1772795/items/IQGJ8TC6"]},"dateAdded":"2014-03-18T13:54:24Z","dateModified":"2017-07-13T12:39:53Z"}],"itemID":12,"journalAbbreviation":"Neue Teutsche Merkur","extra":"","__citekey__":""}" {file: "Better BibLaTeX" line: 690}]
> 
> [JavaScript Error: "this.sanitizeCollection is not a function" {file: "BetterBibTeX JSON" line: 454}] 
> 
> [JavaScript Error: "this.sanitizeCollection is not a function" {file: "BetterBibTeX JSON" line: 454}] 
> 
> [JavaScript Error: "translation failed"] 
> 
> [JavaScript Error: "TypeError: this._generator is undefined" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js" line: 97}] module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:9 module.exports/Promise.coroutine/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:201:9 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1 Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad' Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad' Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad' 
> 
> [JavaScript Error: "this.sanitizeCollection is not a function" {file: "BetterBibTeX JSON" line: 454}] 
> 
> [JavaScript Error: "this.sanitizeCollection is not a function" {file: "BetterBibTeX JSON" line: 454}] 
> 
> [JavaScript Error: "translation failed"] 
> 
> [JavaScript Error: "TypeError: this._generator is undefined" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js" line: 97}] module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:9 module.exports/Promise.coroutine/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:201:9 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1 version => 5.0.8, platform => MacIntel, oscpu => Intel Mac OS X 10.12, locale => de, appName => Zotero, appVersion => 5.0.8, extensions => Zotero automatic export (1.2.4, extension), Zutilo Dienstprogramm für Zotero (2.0.1, extension), Zotero Better Bib(La)Tex (5.0.2.circle.3907, extension), Zotero Word for Mac Integration (5.0.1.SA.5.0.8, extension, disabled), Zotero LibreOffice Integration (5.0.6.SA.5.0.8, extension, disabled)

**Comment by retorquere** [comment]
Can you:
1. go into Zotero preferences/advanced, check "enable on restart", 
2. restart
3. export again
4. right-click that reference and send a debug report
5. post the ID here

**Comment by Wekhrlin** [comment]
ok, the ID is: QWR4N74C

**Comment by retorquere** [comment]
Sorry, that item has moved in zotero. It should be:

1. Go into Help/Debug Output Logging/Restart with logging enabled
2. Have Zotero restart
3. export
4. right-click that reference and send a debug report
5. post the ID here

**Comment by Wekhrlin** [comment]
This one? D408211381

**Comment by Wekhrlin** [comment]
btw, the first one was via the BBT prefs/advanced/extended debug logging

**Comment by retorquere** [comment]
I think you've submitted to Zotero; I can't read those logs. You really need the right-click version. extended debugging doesn't work anymore and I've removed it in a later version but the "restart with logging" does the same.

**Comment by Wekhrlin** [comment]
although I deleted my own notes, which were inside the log, it is quite long...

[log_zotero_BBT.txt](https://github.com/retorquere/zotero-better-bibtex/files/1208596/log_zotero_BBT.txt)

**Comment by Wekhrlin** [comment]
forgot to update. still can't export with 3912 but the log is smaller:

[log_zotero_BBT_3912.txt](https://github.com/retorquere/zotero-better-bibtex/files/1208628/log_zotero_BBT_3912.txt)

**Comment by Wekhrlin** [comment]
...and a bit longer. similar to the first.

[log_zotero_BBT_3912_2.txt](https://github.com/retorquere/zotero-better-bibtex/files/1208649/log_zotero_BBT_3912_2.txt)

**Comment by retorquere** [comment]
Doesn't the regular debug submit work? The log is missing quite a bit of info. Just right-click the reference you were trying to export and click `Report Better BibTeX Errors...`

**Comment by retorquere** [comment]
Oh I see there's an error with the debug submission, you need 3909 for that.

**Comment by Wekhrlin** [comment]
I tried to export the whole library but the error "works" with one item, too.

VPP5WT8F is the ID for the new report.

**Comment by retorquere** [comment]
You're on 3912, which is an alpha build; I've changed the build process to include the branch in the xpi. Please try 3914.

**Comment by Wekhrlin** [comment]
now with 3914 the report for a specific reference doesn't work but the normal via the prefs: RBTB6DWY

**Comment by retorquere** [comment]
Can you install 3919, check "rescan" in the BBT preferences, restart, and try an export again? If that doesn't do it, a new log.

**Comment by Wekhrlin** [comment]
it works! :-) thank you! I'll keep searching for bugs while working.

**Comment by retorquere** [comment]
Superb, and thanks for the help.

**Comment by Wekhrlin** [comment]
thank you for porting BBT to Z5!
