### ISSUE TITLE
Z5: Better BibTeX keeps recreating and deleting its translators

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#695]
Just noticed it: when installed, Better BibTeX creates its translators in Zotero translators folder. When I close Zotero and run it again, BBT deletes its translator files (though popup shows info about waiting for and then loading translators). So exports does not work of course. After Zotero restart, translators are recreated again, everything works fine until Zotero is restarted, when translators are deleted again. And so on, and so on.

Report ID: 4CT5CWI9 (created after translators are deleted)
Report ID: TEEJ9IMX (created after translators are recreated)

**Comment by retorquere** [comment]
Zotero does what now? I can see in the log that it's deleting my translators. I have no idea why it would be doing that -- I'm not doing it.

I'll get in touch with the Z team. Thanks for reporting.

**Comment by retorquere** [comment]
Just to be clear: after a restart, Zotero actually removes the files from the `translators` directory? Or just from the DB? The DB delete could be because I'm asking Zotero to replace the files.

**Comment by dbobak** [comment]
Yes, exactly. Zotero removes BBT files (BetterBibTeX JSON.js, Better CSL YAML.js, Better CSL JSON.js, Better BibTeX.js, Better BibLaTeX.js) from my profile/translators directory.  And on the next restart, creates them again, till next restart, when they deleted again. Everything happens on the initial run, between BBT messages: "Better BibTeX: waiting for Zotero to load translators" and "Zotero translators loaded".

**Comment by retorquere** [comment]
Can you try 3923?

**Comment by dbobak** [comment]
In 3923 the files are as solid as a rock ;) Thank you, @retorquere

**Comment by retorquere** [comment]
Super. Turned out to be my error -- Z4 just didn't seem to mind.

**Comment by dbobak** [comment]
After upgrading from 3920 (or earlier, I cannot check it now) to 3925 (in my other computer, when Zotero was closed with translator files deleted), the the translator files are not created. Even after uninstalling and installing BBT again. They are also not created, when installing BBT in the another Zotero profile, where BBT was never installed.

**Comment by retorquere** [comment]
Can

**Comment by retorquere** [comment]
Can you submit a new debug log?

**Comment by dbobak** [comment]
Yes, of course: UTTN9KK6

**Comment by retorquere** [comment]
I see where the problem is. Damn, this means some pretty fundamental changes to BBT. 
This may take a few days.
