### ISSUE TITLE
Z5: Citation Quick Copy errors out

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#697]
After upgrade to 3925, QuickCopy stopped working for any of the BBT translators. Due to bug #695, I have extracted all the translators manually from the xpi file (including Better BibTeX Citation Key Quick Copy.js) and copied it to the translators directory. Then, when trying to use any of the BBT translators as a Quick Copy format, I'm getting an error: when pressing Shift+Ctrl+C, message is "An error occured while trying to export the selected file", drag & drop is also impossible, but without any error message.

ReportID: PQMHH375

**Comment by dbobak** [comment]
Just have noticed that any BBT export stopped working, not only Quick Copy.

ReportID; 56L7EPFY

**Comment by dbobak** [comment]
And after downgrade to 3924, export works just fine, except of the 3925 BBT Quick Copy translator.

**Comment by retorquere** [comment]
I'm doing major rework on the initialization, you'll have to wait for that to clear. Could be today, but could also take a few days.

**Comment by dbobak** [comment]
Ok, thank you!

**Comment by dbobak** [comment]
Hello Zotero! Looks, like 3931 is working now. Translators are created and functional (except of `Better BibTeX Citation Key Quick Copy.js`). After restart, they still exist (although it looks like they are recreated). BBT installed in a fresh profile also works.

**Comment by retorquere** [comment]
Yeah that will probably not make it to the final release, but man does Zotero take a long time to get the translators ready. Translators are indeed recreated. I may build in a check to see if that can be avoided, but it's low priority right now.

Quick Copy doesn't work? I have a few tests on that and those pass.

**Comment by dbobak** [comment]
Yes, Quick Copy shows the same error as before. Here's report id: NVTKX9QK

**Comment by retorquere** [comment]
Can you test whether 3933 fixes the issue for you?

**Comment by dbobak** [comment]
As soon as it appears [here](https://github.com/retorquere/zotero-better-bibtex/releases/tag/builds)

**Comment by retorquere** [comment]
It's already there: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.697.3933.xpi . I fix bugs in separate branches so I can do concurrent work; I merge to master as fixes are confirmed.

**Comment by dbobak** [comment]
Ok, quickly tested. And looks that everything exports without problems, also Quick Copy in all its formats (LaTeX, Pandoc etc.).

**Comment by retorquere** [comment]
alright, merged to master

**Comment by retorquere** [comment]
(will be out as 3936 when the tests finish)

**Comment by dbobak** [comment]
3936 tested, works well also.
