### ISSUE TITLE
Z5: startup scan-and-fix does not create citation keys

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#698]
Report ID: G4PF3PKN

When reference does not have citation key, it's not created during the scan on startup. It is added when creating new reference, modifying existing reference or choosing rescanning keys in options.
That's the issue that @dmbortz reported in EG89WWHE. 

Automatically created keys are soft keys. It would be nice to have option to manually assign pinned key, or to choose if keys created automatically should be soft or pinned.

**Comment by retorquere** [comment]
Z5 is so much fun :frowning_face:. I'm trying to scan-and-fix during startup, but it looks like I must wait until the zotero clears stage 2 init. stage 1 is fast, but stage 2 takes 15 seconds even with an empty library on my tests. I'll go find out what I can do about this.

**Comment by retorquere** [comment]
Can you install 3937, restart and submit a new log? This will not fix the problem but it will give me more info.

**Comment by dbobak** [comment]
Report ID is P5HIHPM7

BTW, how BBT counts references without keys? In my test profile (the report is from that profile), it shows correct numer of references without key. But in my everyday profile it shows that found 197 references without keys. I have 188 references (+ one in trash) without keys in shared libraries, but in my main library there is no such references. So the number does not match.

**Comment by retorquere** [comment]
OK, I have more info now; more big changes, but at least I know what I must do now. Man, this async stuff...

WRT finding citekeyless entries: BBT does a select over the database:

```
select item.itemID, extra.value as extra
from items item
left join itemData field on field.fieldID = 22 and field.itemID = item.itemID
left join itemDataValues extra on extra.valueID = field.valueID
where item.itemTypeID not in (14, 1) and item.itemID not in (select itemID from deletedItems)
```
and then just parses the results using regexes to see if it can find a cite key. Until Z5+ implements a separate field for the citation key, this is the way to store citation keys the Z devs keep pushing for.

**Comment by dbobak** [comment]
OK. It seems that I must have some mess in my database; the query returns more rows than references in Zotero. And there is exactly 197 rows with NULL value in extra column. Thanks!

**Comment by retorquere** [comment]
Do you have group libraries synced? The select picks up all references across all groups and the main library. Otherwise I'd *really* like to know what those other references are. Can you send me the output of
that query on your database?

**Comment by dbobak** [comment]
I have group libraries synced, so maybe that is the case. I'm attaching the result of the query.
[test.zip](https://github.com/retorquere/zotero-better-bibtex/files/1214648/test.zip)

**Comment by retorquere** [comment]
I don't readily see any duplicates, which is what I was worried about. Group libraries would explain it.

**Comment by dbobak** [comment]
I think so.

**Comment by dmbortz** [comment]
With 3937, for:
* exporting one reference (which has the "bibtex*:Wang2017IEEESpectr" in the Extra field) doesn't work  Report ID: 32SFR46D
* subsequent exporting of the same reference (and other refs that populate the Extra field) does work!
* exporting one reference with the Extra field blank doesn't work. Report ID: ZKYL53AF
* exporting a library doesn't work. Report ID: STAAE3BN

**Comment by retorquere** [comment]
Can you try again with 3942?

**Comment by retorquere** [comment]
Can this issue be closed?

**Comment by dbobak** [comment]
For me, yes.

**Comment by dmbortz** [comment]
Export with empty Extra field: 2VEWMLJD
Export with Extra field populated works just fine.
Export of library: 8WBF2J77

Also, fyi, on the Preferences->BBT->Advanced tab, when I clicked on Re-scan citekeys, BBT conclusdes that 2280 (out of 2431) references don't have citekeys.  Zotero then maxes out a core and resident memory starts going up.  The Extra field starts to be populated in the references, but then it stopped at one reference that didn't have an associated pdf.  I exited zotero when resident memory cracked 1GB.

After a restart, the Extra fields that were being populated are blank again.  I found the pdf for that one entry and have restarted the Re-scan and it's still going.  I'll update this if it completes.

**Comment by retorquere** [comment]
Dammit. Both the scanner and the key generator should ignore notes and attachments, so I don't know why the presence of an attachment should make any difference. That the references would be blank again I can explain -- I was saving the results of the reset in a transaction, if that gets aborted, the whole is undone. I've changed it to one-at-a-time saving in 3946 -- can you try again? But seeing performance issues at 2.5k references is not a good sign. I may have to fall back to the shadow DB -- again 😞 .

**Comment by dmbortz** [comment]
I think that's a red herring...I assumed the Extra fields were being populated one after another...so likely the blank one was just not sequential in the database in the way I had sorted the references.

The load eventually went back to nominal, but not all the references have citekeys.  I've clicked "Rescan" twice now and each time more of the citekeys get filled in.   I'm now on the third click and it's down to 981.

**Comment by retorquere** [comment]
You shouldn't have to click multiple times unless you're also actively adding new entries. As a matter of fact I may have to make sure there are not two scan active at the time.

Man I *hate* async.

**Comment by retorquere** [comment]
3947 will not allow concurrent scans but will tell you how many are still left to scan.

Is there an easy way for you to clear all your citekeys? Did you keep a backup?

**Comment by dmbortz** [comment]
I was just watching 'to'p until the load drops and then hitting "Re-scan"...so maybe I wasn't actually re-running the re-scan.

And, I just exported after the Re-scan finished and it worked! I can now export items and my library and the scheme generates the correct keys!

**Comment by retorquere** [comment]
I still don't like the fact we're already hitting serious performance issues with so little references. I'm resurrecting the shadow database. Will probably take me a day or so to do.

**Comment by retorquere** [comment]
Can you try 3951, preferably on a DB that has no citekeys?

**Comment by dmbortz** [comment]
I tried it, but I was actually unable to find a database with no citekeys. When I tried to make a new collection or group, the Extra field was populated with every reference I entered.  Regardless, exporting works for items, collections, and libraries.

**Comment by lowercasename** [comment]
Hi! I've just installed zotero-better-bibtex-5.0.2.3956.master.xpi on the latest version of Z5 and keys weren't automatically created for me at startup. Keys _are_ created if I even click on a field in an item to activate it, without editing anything. But I can't see an option anywhere to force creating keys for multiple items.

**Comment by retorquere** [comment]
@lowercasename can you try 3995? If that still fails for you, please open a new issue -- I don't get notifications for closed issues.
