### ISSUE TITLE
Z5: export error, Report ID: WF4FGGXG

### ISSUE THREAD

**Issue by ppoppitz** [retorquere/zotero-better-bibtex#701]
Running 5.0.2.3952.issue-699 I got an very general error message after trying to export a folder with ~1000 items (similar error happend with individual items): 

> An error occurred while trying to export the selected file

PS: Did worked with an older BBT Z5 version, but I don't remember which one.

**Comment by retorquere** [comment]
Can you try again with 3995? I expect the error will still be there but this version has more debug info for me to inspect

**Comment by ppoppitz** [comment]
Sorry, not within the next 3 weeks, travelling ...

Am 18. August 2017 10:46:01 MESZ schrieb retorquere <notifications@github.com>:

**Comment by retorquere** [comment]
No problem, but then I will be closing this issue. Things are moving too fast for older reports.
