### ISSUE TITLE
Z5: Export fails at the second time

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#702]
Build 4011. After installing, export works properly. But only at first time. All the next exports of the same fails, ever after deleting ```better-bibtex.sqlite``` and ```better-bibtex``` folder. Uninstalling and installing BBT helps, but only for the first export.
I can export another collection, but also for the firs time, all the subsequent export of once exported collection fails.

ReportID: LEXA2B47 for the one of the collection, ID PWRU64TQ  for the second one.

**Comment by retorquere** [comment]
Man that part of the code needs a thorough going through

**Comment by dbobak** [comment]
Anyway, 4012 corrects the problem.
