### ISSUE TITLE
Z5: Exporting collections fails, BetterBibTeX report ID: H2NJE925

### ISSUE THREAD

**Issue by jogrue** [retorquere/zotero-better-bibtex#703]
(Zotero debug report ID D1603974230)

Hello,

I am currentyl testing 4013 and exporting collections fails sometimes, I get "An error occurred while trying to export the selected file." It did work with the previous versions I tried (quite a few, unfortunately I cannot tell anymore which was the latest version that worked).

As far as I can see: Exporting a collection only fails if the collection also has subcollections. And it does not fail for Better CSL JSON export, only for Better BibTeX and BibLaTeX.

Also, it is no problem to select all items of said collections and export them.

**Comment by retorquere** [comment]
Can you submit an debug log after a failure by right-clicking whatever you tried to export and selecting "Submit BBT error"? I don't have access to the regular Zotero debug logs.

**Comment by jogrue** [comment]
H2NJE925 should be a BBT error log?
I created another one and hope it worked: VA3AZKDU

**Comment by retorquere** [comment]
H2NJE925 is, but your initial message said D1603974230 -- I don't generate that kind of debug ID, so I was guessing it was a Zotero debug ID. I'll look into those reports, thanks.

**Comment by dbobak** [comment]
Confirming the bug. ID: UPIZFQS6

**Comment by jogrue** [comment]
@retorquere Sorry for the confusion. I thought the BBT report generator is not working for me at first (I was not patient enough to wait for a few moments) and generated the Zotero report instead. When I found out that the BBT report generator worked as supposed I still included both IDs (BBT ID in the title and Zotero ID in the post).

**Comment by retorquere** [comment]
Right, you must wait for the "BBT ready for business" popup -- I can't do anything about that, I've been told by the Z devs that I must wait for that signal. Before that, you can't use BBT reliably (which includes the error report in case you're also sending references)

**Comment by retorquere** [comment]
No idea what could be the cause of this -- Zotero reports one of your collections to have a non-existent parent. Can you try 4016 when it drops in a few? It should still error out, but a new debug log should give me more info.

**Comment by jogrue** [comment]
Report with 4016: MVGZZEG8
This is the collection, nothing special in my opinion (and it already worked at some point):
 <https://i.imgur.com/BBqPsGO.png>

I tried another collection that is inside a collection, also failed: <http://i.imgur.com/8o3Y19o.png>
Unfortunately, submitting the error report for this one takes a long time at the moment and I cannot wait. I can send it tomorrow if necessary.

**Comment by jogrue** [comment]
An here the report for the same collection in above's edit, but with version 4018: JDFJ7QQL
Hope it helps a little.

**Comment by retorquere** [comment]
Can you try again with 4020? This is driving me nuts, I can't reproduce it and the data in the error log seems to conflict with the data in the references being sent at the same ^&%!#&^% time.

**Comment by retorquere** [comment]
Oh can you make sure that when you submit the error report, you right-click the same selection that you did the failing export on earlier?

**Comment by retorquere** [comment]
4021 is out, please use that instead.

**Comment by jogrue** [comment]
ID with 4021: QRCFZ649

And usually I right-click the same collection I tried to export when generating the report (no guarantee I did it for every report, though I think I did).

**Comment by retorquere** [comment]
I'm not claiming you didn't but I needed to make sure. The logs are head-scratchers right now.

**Comment by retorquere** [comment]
*^!*&^*# still those discrepancies. Maybe the order that I'm requesting them in is relevant? Can you try 4022?

**Comment by jogrue** [comment]
Okay, I tried one more thing.

I started Zotero with a new and empty profile and installed BBT 4021. I then

- created a "collection a",
- created a "collection b",
- created a "subcollection b.1" in "collection b",
- imported one article,
- and moved this article to both collections (a and b).

Exporting "collection a" (without any subcollections) works, exporting "collection b" (with an empty subcollection) fails. Both collections only contain the same single item.

ID: MTQJZSIK

**Comment by jogrue** [comment]
I am using this rather empty testing profile now: <http://i.imgur.com/spmSklH.png> You said, you cannot reproduce it?

Here the new ID for 4022: 8U3RVL8C

**Comment by retorquere** [comment]
I have it reproducible now! This will make it easier for me to find out what in tarnation is going on here.

**Comment by retorquere** [comment]
Can you try 4023?

**Comment by jogrue** [comment]
It works! Thanks a lot.

**Comment by retorquere** [comment]
Thanks for the feedback, it helps a lot.
