### ISSUE TITLE
Z5: Year in square brackets -> origdate

### ISSUE THREAD

**Issue by Wekhrlin** [retorquere/zotero-better-bibtex#704]
If I have in the date field of Zotero a year with square brackets, in the previous version (Z4) and with the new version a week ago, it was exported correctly as:
year = {[1796]}

With 4032 the brackets are missing and I get 'origdate' and not 'year':
origdate = {1796}

I need the square brackets to indicate when there is a book with no given date. Can you bring back the old style of exportation?

**Comment by retorquere** [comment]
Are the brackets meant to denote an approximate date?

**Comment by Wekhrlin** [comment]
no, it means that the date is deduced/derived. It's the same, when there is no given printing place – but this works fine in export :-)

**Comment by retorquere** [comment]
Just curious: derived/deduced from what?

**Comment by retorquere** [comment]
Can you test 4038 when it drops?

Your issue opens a broader issue on date parsing. BBT does quite a bit of work to make sense of whatever is in the Zotero date field and tries to produce `year`, `date`, `month` and `origdate` fields from that (depending on whether you're exporting BibTeX or BibLaTeX -- which were you targeting BTW?). Maybe I should just leave that to the user and just put whatever is in the Zotero date field into Bib(La)TeX.

**Comment by retorquere** [comment]
Alright. I see you must have been using BibLaTeX because I only output `origdate` for that, not for BibTeX. 4038 has dropped. What would you make of `2012 [1802]`? That has split out to `date` and `origdate` even in Z4 (IIRC).

**Comment by Wekhrlin** [comment]
Yes, I use BibLaTex for export, and it works again with 4038.
For 2012 [1802] I would put the 1802 with 'origdate' in the extra field, I think, but luckily I don't have citations in that style.

**Comment by retorquere** [comment]
merged
