### ISSUE TITLE
Better BibTeX export fails when Postscript contains dateAdded

### ISSUE THREAD

**Issue by dotran** [retorquere/zotero-better-bibtex#706]
Report ID: EP3TZF3B

My postscript is

```
if (Translator.BetterBibTeX) {
    if (this.item.dateAdded) {
        this.add({ name: 'dateadded', value: this.item.dateAdded });
    }
}
```

And on *any* of the three references included the report, I got the Error message:
"An error occurred while trying to export the selected file."

Feel free to let me know if you need any further details.

Thanks for the great work and kind support!

**Comment by retorquere** [comment]
Bleep bloop; this is your friendly neighborhood build bot announcing new test build [4046](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4046.issue-706.xpi).

**Comment by retorquere** [comment]
Can you try 4046?

**Comment by dotran** [comment]
Just tried, now works perfectly!
Thanks for the super quick update.
