### ISSUE TITLE
Z5: Citekey generation failure

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#708]
When I use `[authorsAlpha:lower][year]` in CItationKey format the CitationKeys are generated with no problem. 
However, when I use different format pattern i.e. `[auth.etal][shortyear:prefix,.][0][Title:fold:nopunct:skipwords:select,1,1:abbr:lower:alphanum:prefix,.]` the citation keys are not generated. 
When I change the citation pattern to `[authorsAlpha:lower][year]` and restart Zotero the citation keys are generated. 
Report ID is: G3HRTHXB

**Comment by retorquere** [comment]
:pager: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4081](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4081.issue-708.xpi).

**Comment by retorquere** [comment]
:pager: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4082](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4082.issue-708.xpi).

**Comment by retorquere** [comment]
Can you try 4082?

**Comment by mijalche** [comment]
it solves the problem.
Thanks!

**Comment by averter** [comment]
Same problem with `[auth:lower]_[veryshorttitle:lower]_[year]` citekey format. Report ID: NYYWBQ5Z.
Using version: zotero-better-bibtex-5.0.2.4082.issue-708

**Comment by retorquere** [comment]
:pager: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4084](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4084.issue-708.xpi).

**Comment by retorquere** [comment]
@averter can you try 4084? If that doesn't work, can you submit a debug report by right-clicking some references? @mijalche, your references now serve as a test case in my test suite, but if you want to try 4084 for confirmation I wouldn't complain.

**Comment by mijalche** [comment]
before I installed 4084 I used the [auth:lower]_[veryshorttitle:lower]_[year] citekey format. I had no problems with this or mine citekey format.
after I installed 4084 I test it with [auth:lower]_[veryshorttitle:lower]_[year] and my citekey format again I had no problem
I also tested 4084 with the [authorIni][title][shortyear] and had no problems

**Comment by retorquere** [comment]
@mijalche thanks. The problem was triggered earlier by `[auth.etal]`; I didn't handle the `.` well. I restructured the part of the code that dealt with the pattern and that may or may not have fixed @averter 's problem -- it looks good in my tests, but I'd prefer confirmation, and then I'll merge it to master.

**Comment by mijalche** [comment]
excellent. If you want something else to be tested in more details I can do that.

**Comment by retorquere** [comment]
Right now most issue are found by people just using BBT. I don't know of anything specific you could test. But thanks, much appreciated.

**Comment by mijalche** [comment]
After updating to 4085, citekey is not generated with my citekey format. 
ID: G2JKF5SX
Also there are no visible changes to existing citekeys when I click Pin/Unpin/Refresh. Can you tell me what behaviour is expected from these options.

**Comment by retorquere** [comment]
4085 doesn't have the fixes from this issue yet; once @averter confirms I can merge.

**Comment by retorquere** [comment]
:pager: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4088](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4088.issue-708.xpi).

**Comment by retorquere** [comment]
The fix has been merged to master and is available on 4089+

**Comment by averter** [comment]
Not working here. Report ID: VATQYHL8
I've re-scanned the keys, just to make sure that I was not doing some stupid mistake.

**Comment by retorquere** [comment]
@averter what problem are you experiencing? Your log doesn't show any errors.

**Comment by averter** [comment]
@retorquere Essentially  the `[auth:lower]_[veryshorttitle:lower]_[year]` citation key format in better bibtex does not work. The generated keys do not agree with this format.

**Comment by retorquere** [comment]
But other patterns do? I see no key generation activity in your log. What happens if you change a reference? Does it keep the current citekey, is it blank?

**Comment by averter** [comment]
Now I am confused. I thought that the generation was automatic, and I am sure that in version 4082 I didn't had a refresh bibtex key option on the left click menu of each entry. As soon as I refreshed the keys it displayed perfectly.  Thanks, I guess this closes the issue.

**Comment by retorquere** [comment]
@averter ah yeah the behavior has changed from Z4; for performance reasons dynamic keys don't update for all references anymore when you change the pattern; the pattern change only takes effect for references that are modified after the pattern is changed. A refresh will force an update without the reference changing.
