### ISSUE TITLE
Z5: Export does not show in Automatic export

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#709]
Hi,
I have problem with showing export in the Automatic export. I export as BetterBibTex with selected Notes and Keep updated. But none of the exports is shown in Automatic export panel. I have tried with different Collections, but it does not show up. I am sending two errors.
Error ID: CMEELQRZ
Error ID: NSNCUKYY
Keep the good work!

**Comment by retorquere** [comment]
Auto export is [not yet implemented](https://trello.com/b/OpJQyVTP/better-bibtex-for-zotero-5).
