### ISSUE TITLE
Hash in citekey

### ISSUE THREAD

**Issue by awesomeindustries** [retorquere/zotero-better-bibtex#71]
Do you think it would be possible to implement the hash in citekey, as Papers.app does?

http://support.mekentosj.com/kb/read-write-cite/universal-citekey

/edit
Nevermind, this is not worth your time!

**Comment by tolot27** [comment]
Is it planned to support the universal citekeys? I found your repository retorquere/universal-citekey-js and believe it would be very useful. I often run into the problem of different abc suffixes, especially after bibtex imports.

**Comment by retorquere** [comment]
It wouldn't help for bibtex imports, as bibtex imports retain the key that was imported. You can clear those using "unpin key" though.

As to the "universal" citekeys, I can get you a custom build that has them, but I'm at the current stage of the proposal very hesitant to include them, for (a.o.) the reasons listed [here](https://forums.zotero.org/discussion/comment/302067#Comment_302067). Given the state of things, we'd either have to give up universality and just go with "BBT-universal", or other ref mgrs would have to get involved (but Papers are themselves apparently no longer interested).

If you still want a build, just holler, but if you want to discuss the way universal citekeys could be done right, please use that link to the Zotero forums. On something like this I like to have more people involved, and I don't want to put out anything that touches the citekeys that I'd have to change soon after, or that would require yet another option in the preference pane to distinguish old from new behavior.

**Comment by retorquere** [comment]
Oh unless with import you mean "import of the same bibfile more than once leading to duplicates". Universal citekeys wouldn't help there at all, even if imports wouldn't retain the imported key. citekey postfixing happens after the key is generated, so if you generate two duplicate (non-pinned) universal citekeys, one would still be postfixed by BBT.
