### ISSUE TITLE
Pinning the citekey clears the extra field

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#711]

**Comment by retorquere** [comment]
:pager: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4087](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4087.issue-711.xpi).

**Comment by retorquere** [comment]
@dotran this fixes the issue for me.

**Comment by retorquere** [comment]
I'm pushing this to master together with #708 combined fix will drop as 4088

**Comment by dotran** [comment]
OK, so I will install 4088 and try it out once it drops.

**Comment by retorquere** [comment]
Ugh forget it I'm dropping 4089 on master

**Comment by retorquere** [comment]
This works for me but I'd love confirmation

**Comment by dotran** [comment]
Confirmed. Works as expected.

**Comment by dotran** [comment]
Just that we need to click away and then click back the item to see the `Citation Key` updated on the right pane (on each pinning or unpinning action). But this is a different issue -- maybe about refreshing.

**Comment by retorquere** [comment]
Yeah, that's a refresh issue. There's no formal Zotero API for most of what BBT does so I'm just trying to figure out what I can abuse or run-time-patch to get BBT to work at all. The UI stuff is the hardest for this.

**Comment by dotran** [comment]
And another one is that after an *unpinning* action, the `Citation Key` field is not getting back to the *italic* font face. Just an observation -- perhaps it's no important nor influential.

**Comment by dotran** [comment]
> Yeah, that's a refresh issue. There's no formal Zotero API for most of what BBT does so I'm just trying to figure out what I can abuse or run-time-patch to get BBT to work at all. The UI stuff is the hardest for this.

No problem -- we all can live with this.

**Comment by retorquere** [comment]
Mother of ... the citekey just plain disappears after pinning/unpinning. I hate UI work.

**Comment by retorquere** [comment]
Hold on no that's not a refresh issue.

**Comment by dotran** [comment]
Yeah, the `Citation Key:` field on the right pane just completely disappears on each pinning/unpinning (if the action actually makes a change). This causes the right pane being shifted up a row (which catches my attention).

**Comment by dotran** [comment]
> Hold on no that's not a refresh issue.

Then you might know how to fix this ;-)

**Comment by retorquere** [comment]
if you pin or unpin the star doesn't change in the reference list even if you click to a different collection -- that's not a refresh issue.

**Comment by dotran** [comment]
And BTW, when a reference does not include enough info to make a citekey, BBT generates an `Unknow` or `Unknowa` then `Unknownb`. Have you make a concrete decision on this pattern? Or in a future release this might be something else? (Just for the purpose of parsing the output of BBT and filter out the "indecent" citekeys.)

**Comment by retorquere** [comment]
I have no specific preference for this. It used to be `zotero-<itemID>`.

**Comment by dotran** [comment]
I see that with my old references, but new references got `Unknow` or `Unknown<postfix>`. You might want to save an arbitrary webpage to Zotero and remove the fields your citekey format needs.

**Comment by retorquere** [comment]
The same will be true for me -- I changed it to `Unknown` in BBT5. You prefer the old way?

**Comment by dotran** [comment]
Ah nope, keep it the way you like. I've realized the change and just want to suggest maintaining the consistency (from now on).

**Comment by retorquere** [comment]
Nah, you make a good point about discoverability. I'll change it back.

**Comment by retorquere** [comment]
I think I have the disappearing field fixed (ugly, but seems to do the work). Also got `zotero-<itemID>` back. 4092 will drop momentarily.

**Comment by dotran** [comment]
Works!

**Comment by dotran** [comment]
Just that upon pinning/unpinning, the value of the field `Citation Key` on the right pane is something wrong (like it caches this citekey in the buffer and just prints that here). However, if I click away and then click back the reference, `Citation Key` displays the correct value then. (`Extra` always displays the correct citekey.)

**Comment by retorquere** [comment]
I hate UI work. It doesn't help that I'm not really supposed to be able to display stuff there and I'm hijacking Zotero internals left and right to get it there in the first place. I've added a Trello card to track the issue, but I'm giving other stuff priority right now.

**Comment by retorquere** [comment]
The stuff in the `extra` field is just the regular Zotero refresh mechanism, so that will always work (and will always be authoritative)

**Comment by dotran** [comment]
Yes, the refresh stuff like that doesn't hurt. Let's live with it if Zotero doesn't support this nicely.

**Comment by dotran** [comment]
BTW, you might want to make a Trello-like board under the **Projects** menu of the repo. Not as visually fancy and feature-rich as Trello but reodering cards or moving cards between lists are much like Trello's.

**Comment by retorquere** [comment]
I didn't know about that and I'll take it into account for a next time, but since there's no import feature I'd have to retype all the cards. Doesn't seem worth it now. Too bad it isn't git-backed.

**Comment by retorquere** [comment]
Can you see whether 4095 deals with the refresh issue better? I can't readily replicate what you're seeing and I really need to get some sleep.

**Comment by dotran** [comment]
Well, no import feature! I believe they will add this important feature in the future.

I've just tried 4095. No apparent difference with the previous build :-(.

**Comment by retorquere** [comment]
Bah.
