### ISSUE TITLE
Citekey in details pane doesn't update

### ISSUE THREAD

**Issue by lakonis** [retorquere/zotero-better-bibtex#713]
I'm not convinced the report would help (I was not able to open BBibtex preferences to extend the error report). Report ID UA3A74QH was directly issued from the contextual menu.

The bug is the following : when navigating from one zotero reference to another, the Citation key displayed in the Info tab remains always the same, coming from another reference.
The Citation key displayed in the central area remains correct.

The bug seems to occurs on an off, it looks like an interface refresh problem. I don't understand the pattern to reproduce it.

**Comment by retorquere** [comment]
Yeah the citekey in the details is wonky. That part of the Zotero is pretty well cordoned off so I may have to lose it there. 

I'm more worried about you not being able to open the preferences. Can you not reach the bbt Prefs at all?

**Comment by lakonis** [comment]
Sorry, I found it. Call me blind. Zotfile Preferences are accessed from the Tools menu, whereas BBT Preferences are integrated into Zotero Preferences (better choice :)
The citekey is minor indeed for now. Thanks for the great work!

**Comment by retorquere** [comment]
Opinions on the matter what's best vary - the Zotero team isn't fond of me doing this, and actively recommend people going their own-menu route; it doesn't help that I suck at UI so I mess up their clean layout a bit. I also hate UI, and extending their Prefs pane was easiest for me to do. And it's no longer really doable to do top level menus.

**Comment by steve-biggs** [comment]
Update - I'm using build 4165 and the behaviour is as follows:

Pin an item that has an auto generated key - it gets written to the extra field as required but the citation key field updates to the key of a different (pinned) reference (always the same one). Click away from and click back to the recently pinned reference and the citation key is corrected.

Unpin the recently pinned item and the same thing happens. Again, click away and back fixes it.

I agree - minor issue.

**Comment by retorquere** [comment]
I may revisit the issue when the port is done, but right now, it's a [known problem](https://trello.com/b/OpJQyVTP/better-bibtex-for-zotero-5) and it may stay that way until the Zotero team adds the citekey field as they indicated they would. Or I may remove it from the details pane until that point. The way Zotero has implemented the details pane makes it really, *really* resistant to extension.

**Comment by steve-biggs** [comment]
OK, sorry, I missed that it was in the known problems. Other than this (which is very minor) it's working great so far :1st_place_medal:

**Comment by retorquere** [comment]
I just recently added it, you couldn't have known. The port is a lot of work -- I knew it was going to be but it looks like it's going to be at least twice what I had initially thought. I need to pick my battles on this one.

**Comment by retorquere** [comment]
Can you try 5.0.25?

**Comment by ppoppitz** [comment]
I have previously noticed the same bug and can confirm that with 5.0.26 the citekeys are refreshed immediately.
