### ISSUE TITLE
feature request: search & flag duplicate keys

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#714]
I was testing the citekey behaviour when you import a BetterBib(La)Tex reference that you already have in zotero. 
The case is: I exported my ABC subcollection that has one reference with pinned citekey and one reference with unpinned citekey. 
Than I import the exported ABC subcollection. The citekeys of the imported library stay the same thus there are two identical references with same citekeys in different subcollections. I think that this could create a problem in a certain compiling situations where the references are different, but the citekey is the same thus wrong reference can be placed in the bibliography. It might be better when you import a new subcollection if some citekeys are same with already present reference a new citekey to be generated i.e. get postfix for example john.99.c-1. Or to show that there is a conflict with the citekeys and the user should decide how to change the citekey. Also in certain cases you can use the postfix of citekey to identify that you have a duplicate reference. 
Keep the good work!

**Comment by retorquere** [comment]
What format are you using for the import?

**Comment by retorquere** [comment]
Oh wait, you mean you exported using bbt, then imported the result.

Hmm.

BBT has always preserved the incoming key on import. Doing something special after import isn't realistically doable - extensions are not told how references get into zotero, I just see a new reference being saved, and as I put the incoming key into the extra field, it is seen as a pinned key. A regular duplicate merge should get rid of them cleanly. 

It would be possible for me to ignore the incoming key entirely, but not just for keys that would be duplicates after import; I just don't have enough information to make that call. If I ignore citekeys on import, all imports will get dynamic keys. I'm not sure what the results would be of a merge here. The imports don't have any UI, so it'd mean a new setting to ignore incoming keys. I'm not keen on expanding the already pretty baroque preferences screen. I'm not ruling it out, but I want to talk more about the options before I go there.

**Comment by mijalche** [comment]
sorry for the delayed reply. 
I think that you will rarely face a situation like what I have done: export and then import the same subcollection. 
However, I think that at certain point you will face a situation when you import a subcollection with a reference that will have the same citation key. It will be good to somehow indicate that a reference has been changed. One direction will be like what BBT is doing now, when you add the same reference or a reference that with the citation key pattern will create same citation key it adds something like a,b,c or -1,-2, -3 etc. Thus when importing BBT will check do you have the same citation key and if so will add the indication. 
However, the problem here is that there might be several references like this from say imported 100 references and the user will not know which reference's citation key is changed. Thus it will be good to give some indication that changes have been made and generate an import report that will state the references that are changed. This report could be accessed in BBT preferences.
But, on a bottom line I think that this should be done (if done) later on and now to focus on more core issue. 
Thank you

**Comment by retorquere** [comment]
> I think that you will rarely face a situation like what I have done: export and then import the same subcollection.

I think that's likely true

> However, I think that at certain point you will face a situation when you import a subcollection with a reference that will have the same citation key. It will be good to somehow indicate that a reference has been changed. 

I don't quite follow here. If you import a key you already have, you will now have duplicate keys, that is true, but no reference has changed. This is not by necessity an error if you have multiple papers that reference different sources that just happen to have the same key. I wouldn't advocate doing this, but I am not forbidding it.

Ah wait you mean your citation has changed in the article you are writing? I can't really alert to that although the latex compilation should alert you to the fact that you have duplicate keys. The import translators have no avenue to "talk" to the user (there's no UI possible), so I can't really do much here.

> One direction will be like what BBT is doing now, when you add the same reference or a reference that with the citation key pattern will create same citation key it adds something like a,b,c or -1,-2, -3 etc. Thus when importing BBT will check do you have the same citation key and if so will add the indication.

This is in fact not what happens. Currently, when you import a bib(la)tex reference, I assume the key you present at import is significant to you, so during import I add it to the `extra` field, where BBT will pick it up as a pinned key when Zotero saves the imported reference. The only other option I have is to not add it to the `extra` field, which means that after Zotero saves the item, BBT will generate a new key for the reference. It is important to note that from the BBT (or any extension) point of view, there is no such thing as "an imported reference". A translator can offer a prepared reference to Zotero to save; Zotero then saves it. After that, extensions *only* get to hear "there's a new reference", not what was the cause of the new reference (which could be import, manual addition, sync, perhaps other avenues). So I really can't do anything special for "imported references", as there is no such thing from the POV of extensions. And I really don't want to discard the user-provided key.

> However, the problem here is that there might be several references like this from say imported 100 references and the user will not know which reference's citation key is changed.

I still don't understand. In the current setup, no citation keys are changed.

> Thus it will be good to give some indication that changes have been made and generate an import report that will state the references that are changed.

No can do, as the import translators are sandboxed and cannot do anything but read the import-text they're offered and present prepared references to Zotero.

I could perhaps at a later stage add a feature that will flag references with duplicate keys.

**Comment by mijalche** [comment]
I agree with you. 
I think that flagging references with duplicate keys will be sufficient. 
Thanks

**Comment by retorquere** [comment]
Right, about this. What would the scope be for duplicate-flagging? Global? Library? Collection?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.201.2783](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.201.2783.xpi) ("fixes #714")

Install in Zotero by downloading [test build 5.0.201.2783](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.201.2783.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you see if 2783 does what you want?

**Comment by mijalche** [comment]
I installed 2783, and created a duplicate of an items.
I have three items with the same citekey. Two completely identical and one that has small changes in the title, but taking care to generate the same cite key. I select Tag duplicate citation keys but nothing is visually displayed on the duplicate keys. 
Report ID XUA792E5-euc

**Comment by retorquere** [comment]
They've been tagged with `#duplicate-key`, I can see them in the debug report (but strangely enough, not the activity of you selecting the tag action). Tags don't show up in the primary item fields list (tab `Info`), it's on a separate tab (tab `Tags`), but if you select `#duplicate-key` in the tag selector at the bottom right, you should see all items with duplicate keys. We can talk about the tag name if you have a better one, this was just a first shot.

**Comment by retorquere** [comment]
(fixing the items and re-scanning will undo the tags where required, but it's not automatic after the fix, you need to re-select the menu item)

**Comment by mijalche** [comment]
It works! I also noticed that it creates the #duplicate-key tag only in the selected library duplicates are identified. Which is good.
It helped me identify double cite keys which I did not knew about. 
Thank you very much
