### ISSUE TITLE
Type  Howpublished  creates Problems  (Error report 4RN4RJDH )    

### ISSUE THREAD

**Issue by OlafKleinBerlin** [retorquere/zotero-better-bibtex#715]
Hello,

It seems that reading  the filed type "Howpublished" in a bibtex-File 
forces zotero-better-bibtex to stop to read the file, to create the error message
 "An error occurred while trying to import the selected file. Please ensure that 
the file is valid and try again."
without a hint, which of the entries in the bibtex file creates the problem, and leaving 
afterwards the message window "importing .... " on the screen until zotero is left. 

Below please find the entry with the extracted bibtex entry causing the
problems. If the line with "Howpublished"  is removed, the file with this entry can be imported. 

(Sorry for creating the Bug report with standard settings.)

```
% This file was created with JabRef 2.10.
% Encoding: UTF8
@Misc{Davino-2014,
  Title                    = {Identification of a new class of operators aimed to the modeling of smart materials},

  Author                   = {Davino, D.},
  Howpublished             = {},
  Month                    = {April},
  Year                     = {2014},

  File                     = {:/Home/direktor/klein/artikel-vor-other/sorted/hysteresis/ABCDE/Davino-MURPHYS-HSFS.pdf:PDF},
  Owner                    = {klein},
  Timestamp                = {2015.11.02}
}
```

**Comment by retorquere** [comment]
This has been fixed in [4178](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4178.master.xpi).
