### ISSUE TITLE
import bibtex: space after citekey creates confusion

### ISSUE THREAD

**Issue by OlafKleinBerlin** [retorquere/zotero-better-bibtex#716]
Trying to read a bibtex entry with a space between the citekey and the
comma creates problems. If I try to import the both entries attaced below within one file, 
with a space between "HoSp-87" and the following comma,
zotero with zotero-better-bibtex stops to read the file and presents the error as discusses in  #715.

If I put both entries in separate files, I can import both, but the citekey "HoSp-87" for
entry  seems to be ignored, i.e. the entry gets an automatic generated citekey from 
 zotero-better-bibtex. 
Please see error report 5Z4CXKVZ   for version 4165 and HMN6W7VW   for version 4178.

```
@Article{HoSp-87 ,
   author = {Hoffmann},
   title = {Phase transitions},
}

@Book{HoSp-90,
  editor = {Sprekels},
  title = {Free Boundary Problems},
}
```

**Comment by retorquere** [comment]
4220 fixes this issue. Thanks for reporting it.
