### ISSUE TITLE
Jabref groups import does not work

### ISSUE THREAD

**Issue by OlafKleinBerlin** [retorquere/zotero-better-bibtex#717]
I tried to import bibtex files with jabref groups generated by jabref 2.10 and 3.8.2 to Zotero 
(5.0.18 and before). If zotero-better-bibtex (4201 and before) is active, the import is stopped with the "An error occurred while trying to import the selected file. Please ensure that the file is valid and try again." message, and no data are imported.  (If zotero-better-bibtex is not active, I can read both files, and the group structure  is the imported form the jabref 2.10 output but ignored form the
jabref 3.8.2. output.)

Trying to import the jabref 2.10 bitbex file as in 
[test-jabref-classes-2_10.txt](https://github.com/retorquere/zotero-better-bibtex/files/1294945/test-jabref-classes-2_10.txt)
renamed to "test-jabref-classes-2_10.bib" created the error report  892HK9EH,
Trying to import the jabref 3.8.2  bitbex file as in 
[test-jabref-classes-3_82.txt](https://github.com/retorquere/zotero-better-bibtex/files/1294946/test-jabref-classes-3_82.txt)
renamed to "test-jabref-classes-3_82.bib"  created the error report K69HP43W

If I remove in my examples  files the jabref group structure information  at the end,
i.e. the line starting  with "@Comment{jabref-meta" and the following ones, I can import 
these files also if zotero-better-bibtex is active.

**Comment by OlafKleinBerlin** [comment]
Since I have now learnt how to create the better error reports, I have repeated the 
above considerations:
importing  the jabref 2.10 file generated the new error report J7K4F6F9
and the jabref 3.8.2. file generated J5PSQIBY
importing the jabref 3.8.2. file generated

**Comment by retorquere** [comment]
I have it reproducible; I have a fix for 2.10 and am working on 3.82.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4207](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4207.issue-717.xpi).

**Comment by retorquere** [comment]
Can you try 4207? I've added your two files to my test suite so it should be fixed, but confirmation would be nice. Once I get conformation I can merge the fix into the main version.

**Comment by OlafKleinBerlin** [comment]
I have tried 4207 and have imported successfully my test file and my real bibliography files.
Thanks for you work. 
During the test, I feared the the loading  of the classes my not have worked, since the loaded collection is not marked by a triangle until the mouse pointer is moved to the collection part of the window.

**Comment by retorquere** [comment]
You'll have to report that to Zotero; BBT isn't involved in that part of the UI. Thanks fr the confirmation, I'm merging this to master.
