### ISSUE TITLE
Cannot get rid of "BetterBibTeX: Ready for business" notification

### ISSUE THREAD

**Issue by steve-biggs** [retorquere/zotero-better-bibtex#718]
NB: Using test build 4201. Was also present in 4165.

On starting Zotero, there is a notification to say that BBT is initializing, etc. When complete, it gets to "BetterBibTeX: Ready for business". However, I cannot get rid of this notification. It doesn't disappear on its own and I can't click it away. Therefore, it persists while Zotero is open and is always on top, which is obviously rather annoying.

The bug reporting guidance says:

> If your issue is a bug report, but not for exports, please enable extended debugging in the BBT preferences, reproduce your problem, and select "Report Better BibTeX error" from the Zotero gear menu, and post the resulting report ID (shown in red after you submit) here.

However, I cannot see an option to enable extended debugging in the BBT preferences. Am I missing something? If you can tell me how to get the debug report, I will of course post the error message as a comment below.

**Comment by OlafKleinBerlin** [comment]
I have not problems with the "ready for business" notes, but a similar problem with 
the "import file" notice, if I try to read a biibtex file creating problems (see side remark in #715). 
After testing many files with problems, I get a stack of persistent notices, see 
![importing-windows](https://user-images.githubusercontent.com/23361693/30316310-1c278fd2-97a7-11e7-90d1-1b1db10e9a56.png),
which shown up on all of my virtual desktops (kde)

**Comment by retorquere** [comment]
@OlafKleinBerlin please file a separate issue for the import notices.

@steve-biggs extended debugging is gone (where did I leave that? I had meant to remove that from all descriptions); you can now go to `Help` -> `Debug Output Logging` -> `Restart with Logging enabled` and then send a debug report.

**Comment by retorquere** [comment]
@steve-biggs I really need a debug report, without it I can't address the issue; I haven't been able to replicate it here.

**Comment by steve-biggs** [comment]
Hi. Sorry - got distracted yesterday. And then today, I can't reproduce it either! I will send a debug report if it arises again but for now we will have to assume it's "fixed".

**Comment by retorquere** [comment]
That's OK -- if it occurs again, please open a new issue.
