### ISSUE TITLE
"import file" notification does not close after import problems. 

### ISSUE THREAD

**Issue by OlafKleinBerlin** [retorquere/zotero-better-bibtex#719]
After importing a bibtex files with problems, the "import file" notification stays and does not close.

If afterwards a new file is imported, a new "import file" notification is opened slightly 
above the old notification, and which is closed after an import without problems. 
But, after an import with problem, the "new import file" notification stays and the
behaviour repeats, such that after reading some files to find the entry with 
the problems, I get a stack a stack of persistent notices, see 
![importing-windows](https://user-images.githubusercontent.com/23361693/30316310-1c278fd2-97a7-11e7-90d1-1b1db10e9a56.png),
which shown up (as all zotero notifications) on top of all window and also show up on 
all of my virtual desktops (kde Platform Version 4.14.9 on Suse)

**Comment by retorquere** [comment]
I'll need a debug report; I am not experiencing this myself, so I need to know the error on your end.

**Comment by OlafKleinBerlin** [comment]
After importing the file"test-jabref-classes-2_10.bib" and  afterwards the file "test-jabref-classes-3_82.bib" as in #717, I got the error report MDSE23P and had produced two persisting importing notes. 
 After moving my firefox window to the right position, and making a screen shot, I created 
![importing-windows-more](https://user-images.githubusercontent.com/23361693/30323763-be0684fe-97be-11e7-8fe2-4bd0afb3e0a7.png)

**Comment by retorquere** [comment]
I think I have the import error itself fixed, but on this separate issue, I don't think there's anything I can do on the notification staying up; I had forgotten that that notification is put up by Zotero itself, not BBT, so I can't close it. This notification staying up should be generic to all import errors; if that is correct I'm afraid only the [Zotero devs](https://github.com/zotero/zotero/issues) can do anything about it.

**Comment by OlafKleinBerlin** [comment]
I have opened a discussion on the Zotero server, see
https://forums.zotero.org/discussion/67587/import-file-notification-does-not-close-after-import-problems#latest

**Comment by dstillman** [comment]
Those two files import fine for me with stock Zotero, and the notification closes after saying the import is done, so I don't think this is a Zotero issue.

**Comment by retorquere** [comment]
I understand that they import fine with the stock zotero; the problem was not that zotero caused bbt to fail (that was squarely on me), but that *if* a translator throws an error for whatever reason, the notice stays up.

**Comment by retorquere** [comment]
(and since the translator neither puts the notice up not can remove it, it seemed like a zotero issue to me. Of course translators should not throw errors, but bugs do happen)

**Comment by dstillman** [comment]
Got it. Fixed for 5.0.20 — thanks.
