### ISSUE TITLE
Async import, large library

### ISSUE THREAD

**Issue by alexmitrani** [retorquere/zotero-better-bibtex#720]
As requested, I attach .bib file for testing purposes.  (See related discussion: https://forums.zotero.org/discussion/comment/286009)

Kind regards

Alex Mitrani

[Library.zip](https://github.com/retorquere/zotero-better-bibtex/files/1296063/Library.zip)

**Comment by retorquere** [comment]
I've already found at least one instance that breaks my parser, so many thanks!

**Comment by retorquere** [comment]
Waiting for [feedback](https://groups.google.com/forum/#!topic/zotero-dev/Bojg-My30Wg) from the Zotero devs

**Comment by retorquere** [comment]
It takes forever to import (about 2 entries per second), but it works.
