### ISSUE TITLE
bibtex key scheme omission

### ISSUE THREAD

**Issue by dmbortz** [retorquere/zotero-better-bibtex#721]
Thanks again for making this all work @retorquere !

I have a question (or possibly an omission) concerning the bibtex key generation system. The scheme I currently use is:

`[authors3][year][journal:nopunct]`

It does a great job of generating unique keys for articles.  However, I also have dissertations in my database.  Previously I was able to use `[type]`, but now this doesn't seem to work.  Am I missing something? Or, is there a list of possible format options somewhere?

thanks!

**Comment by retorquere** [comment]
I can't find any code in the Z4 branch of BBT that would make `[type]` work. Could it be you were using `[ItemType]`? That used to work but no longer does. I can look at adding `[type]` but it would add the Zotero type, not the Bib(La)TeX type; the Bib(La)TeX type is determined only at export and differs between BibTeX and BibLaTeX; the keys are generated before export.

**Comment by dmbortz** [comment]
Hmmm...I could have sworn I was using [authors3][year][journal:nopunct][type:nopunct] for the key generation...and I have several entries that have "PhD" or "MS" at the end.

Perhaps it just ignored [type:nopunct] and then I'm not remembering that I had manually edited the key...

**Comment by retorquere** [comment]
It wouldn't have ignored the `[type]`, that would have generated an error as you typed it in. But `PhD` or `MS` wouldn't have come from `type` in any case -- more likely to be `[Type]` or `[ThesisType]` (which may work -- I'd have to check); pattern methods that start with a capital letter just fetch the corresponding field from the reference. The way I get the fields from the reference has changed, so I need to re-document which fields are available.

**Comment by retorquere** [comment]
Does `[Type]` do what you want?

**Comment by dmbortz** [comment]
Yes, it does - again, thanks immensely!
