### ISSUE TITLE
Z5: auto-export not working

### ISSUE THREAD

**Issue by ppoppitz** [retorquere/zotero-better-bibtex#723]
I have tried using the auto-export feature since the feature is marked "ready for testing" in trello and encountered various (related?) issues:

1. auto-export jobs are only shown in preferences after a complete Zotero restart.
2. when auto export is set to update on change, not auto-exports happen, not even when manually exporting via BBT preferences nor after Zotero restart (on idle setting not tested)
3. removed jobs remain shown in preferences until reopening preferences, but after restarting zotero they appear again.

System: BBT Build 4220, Z 5.0.18, Ubuntu 16.04

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4265](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4265.issue-723.xpi), apparently because autoexport for collections.

**Comment by retorquere** [comment]
Can you try 4265?

**Comment by ppoppitz** [comment]
with 4265 all auto-export job, complete library and collections, are shown correctly in the preferences and can be removed.
However, triggering of the auto-export "on changes" seems to be still buggy. Unfortunately I'm struggling to find reproducible errors I could make sense of. Maybe I start with the simplest issue:
Step to reproduce:
1. export library (~2000 items) with auto-update option on.
2. change year of item (citekey: furman_brief_2015) --> everything fine, bib updated
3. change year back to original = no changes, but status changed to "scheduled" in preferences
report id: MVEMAEUU

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4268](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4268.issue-723.xpi) (undefined).

**Comment by retorquere** [comment]
Thanks, that debug log had at least one clear reason why you should see this error; please give 4268 a go.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4269](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4269.issue-723.xpi) ("bloop undefined").

**Comment by ppoppitz** [comment]
thanks, with 4270 first problem is solved, updating library works.

second problem I encountered is that collections are not updated when an item is removed from the collection (in this case furman_brief_2015 and zuur_beginners_2009)

report ID: RHHTQMYM

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4274](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4274.issue-723.xpi) ("ae stuff for #723 and #730").

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4278](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4278.issue-723.xpi) ("steps changed").

**Comment by retorquere** [comment]
Can you try 4278?

**Comment by ppoppitz** [comment]
still not working. 
Here is another report with (1) creation of auto export job for collection, (2) including of zuur_beginners_2009 to collection and (3) removing the item from the collection. After (3), the bib is not updated. 
ID: 5FA4EEW4

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4285](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.17.4285.issue-723.xpi) ("loki: inflate needs proto to be set").

**Comment by retorquere** [comment]
Can you try 4285?

**Comment by ppoppitz** [comment]
great, now it's working!
