### ISSUE TITLE
Z5 test build 4220: setting citekey formatting in BBT works once and needs restart afterwards (+ formatting syntax)

### ISSUE THREAD

**Issue by floriandierickx** [retorquere/zotero-better-bibtex#724]
First test, works well! Some observations related to editing the formatting of the citation key for later export with a betterbibtex library (or betterbiblatex library, although I didn't use this in the past), with **OS X Sierra 10.12.6** and **Zotero 5.0.18**. Point 3 relates somehow to issue #721 , but the first point is not yet mentioned I think.

1. After changing the citation formatting to a new pattern (for example `[auth]_[shorttitle]_[year]`), the content of the preference box _Citation key format_ disappears when re-opening the settings box, but other bibtexkeys still refresh according to the first change afterwards. After re-opening the preference box and adding again a new formatting style, it disappears again and the formatting changes still take place according to the first change. 
    - The manipulations for debug ID D593255404 are: (1) changing formatting one time, (2) changing one reference (works), (3) trying to change formatting to a new format (4) trying to change the same reference again (works not). Although I don't know whether this arrives with you @retorquere or somewhere in the zotero developer community? If not I can post the output here, don't know if I followed the debug log steps correctly..
    - When restarting Zotero, I can change again one time the formatting structure (and then it disappears, no editing possible anymore). Not a big issue, it takes only some more time to test different variations =)

2. The different parts of a reference in the new better bibtex library compared to my old library seem to the same, although in a different order (but I guess that does not influence anything, using my limited programmer-brain). And the url and note-options in the settings works nicely!

3. (and a note: I clicked around to find a formatting way for the new betterbibtex database to use the same citation formatting as my old betterbibtex library - and thus be able to re-run pandoc scripts on the new library with already written papers, and it seems that `[auth:lower]_[veryshorttitle:lower]_[year]` does the job! Found the info on [jabref help](https://help.jabref.org/en/BibtexKeyPatterns). If you want somebody to refer to this in the (future) readme (is this somewhere?) for other 'newbies', let me know if I can help, if that's a meaningful enough contribution)

**Comment by retorquere** [comment]
In order:

1. I cannot replicate this right now, and I have no access to the Zotero debug reports; please make sure you select "Send BBT error"; the IDs will be 6 alphanum characters.
2. Order may have changed, but it won't be relevant to the bibtex processors
3. The information is on the [wiki](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#configurable-citekey-generator), but feel free to clarify what is unclear; the wiki is publicly editable
4. I would strongly prefer separate issues for separate questions; multiple questions/remarks in one issue makes it harder for me to track what has been handled and what not.

**Comment by floriandierickx** [comment]
Ok. I didn't know about the wiki, I should have looked at all the tabs.. In general I have never needed it, so that's rather a good sign I guess :) I didn't know about the jabref-formatting styles, something to think about in future work.. 

And I tried to use the button 'Report BetterBibTex Errors...' in the advanced tab of the better bibtex settings pane, but it does not react. Is it supposed to generate a popup with an ID? (after logging, using the 'Restart with logging enabled...' function in the zotero help menu)

**Comment by retorquere** [comment]
It is supposed to get you a popup but I see that is broken ATM. I'll get on that, that should be an easy fix.

**Comment by floriandierickx** [comment]
Ok. I just found out a second way to report (when right clicking on a reference), this seems to work! I will try to submit a report from there. I'm on a very slow phone internet connection, but I hope it'll work..

**Comment by retorquere** [comment]
The error reports are pretty big, so if you're on a data plan, beware.

Wait, phone as in old-school dial-up? What baudrate?

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4223](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4223.issue-724.xpi).

**Comment by floriandierickx** [comment]
Ah I see.. Ok. Jeah I just moved to a new apartment without internet yet, and my phone data plan is on low bandwith quasi-idle mode because I used everything :) Now the upload speed is around 14 kb/s, and the error report stays on the screen with 'Please wait while the error report is submitted' for some time already.. This afternoon (and tomorrow) I was (will be) at university with a more reasonable speed though :)

**Comment by retorquere** [comment]
Logs can range from anywhere between half a meg to several tens of megabytes, depending on how long the logging ran.

I remember the 14k4 days but not fondly enough I'd want to go back 😄 . Tomorrow is soon enough, knowing that the field is empty gives me some leads to work with. Spare the bandwith so you can download Rick & Morty. Life is all about priorities.

Build 4223 removes the debug report from the preferences and moves it to the help menu.

**Comment by floriandierickx** [comment]
Haha, ok, I will keep this advice in mind. I'll keep it uploading for some more time [and use the remaining download space for R&M], maybe at some point it gets through (I think it was around 19000 lines), if not i'll give it another try tomorrow.. And somehow the low speed are like the days of carefully choosing which site to open (and drinking a coffee while waiting), but unfortunately without the dial-in soundscapes :)

**Comment by retorquere** [comment]
And panicking if someone walks to the phone because aw damn there goes your download.

I think I have it reproducible. So enjoy your [coffee](http://goughlui.com/legacy/soundofmodems/v32b-14400bps.mp3).

**Comment by floriandierickx** [comment]
Ok, cool. And exactly, that one gets through :)

**Comment by floriandierickx** [comment]
If still useful, the debug ID for the above steps is 6IM6J7A6 (with build 4220, I can reproduce one with 4223 if needed)

**Comment by retorquere** [comment]
Can you try v5.0.16?

**Comment by floriandierickx** [comment]
This fixed the issue: formatting stays as expected in the settings-box (after different open/close + change formatting), and formatting changes accordingly every time when refreshing a random bibtexkey in the right-click menu. Also, the settings-box turns orange every time when there is an incorrect syntax, until it is adjusted (which is nice!).

**Comment by floriandierickx** [comment]
And also, I don't know if this could be an issue, but however: the formatting change keeps in place after closing and restarting zotero

**Comment by retorquere** [comment]
I don't understand. You'd want to have changes persist across restarts, right?

**Comment by floriandierickx** [comment]
Ah yes, but I wanted to confirm that this is also working (as before, I guess, but I didn't check that when I opened the issue). Sorry for the miscommunication. I thought this gui-change (or 'setting code' change) might be related somehow to how zotero stores the settings when restarting?
