### ISSUE TITLE
Z5 test build 4220: Clicking around too fast in reference list after zotero opening causes crash

### ISSUE THREAD

**Issue by floriandierickx** [retorquere/zotero-better-bibtex#725]
A small (and less important issue I guess), but when I start to click around too enthusiastically in the zotero reference list before the betterbibtex loading is finished, zotero crashes and needs to be restarted. Does not influence behavior afterwards, just need to learn to have some patience I guess :)

When submitting through zotero, it gave D1402030032 (zotero error ID), and I hope clicking on 'Report Better BibTex Errors..' in the advanced pane did send something, there was no confirmation there. In case it didn't arrive, the full log output is:

```
[JavaScript Error: "DB.getCollection(...) is null" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.itemPane.js" line: 80326}]

[JavaScript Error: "TypeError: Zotero.BetterBibTeX.ErrorReport.prototype.start is not a function" {file: "chrome://zotero/content/preferences/preferences.xul" line: 1}]
oncommand@chrome://zotero/content/preferences/preferences.xul:1:1


[JavaScript Error: "TypeError: Zotero.BetterBibTeX.ErrorReport.prototype.start is not a function" {file: "chrome://zotero/content/preferences/preferences.xul" line: 1}]
oncommand@chrome://zotero/content/preferences/preferences.xul:1:1


version => 5.0.18, platform => MacIntel, oscpu => Intel Mac OS X 10.12, locale => en-US, appName => Zotero, appVersion => 5.0.18, extensions => Zotero Word for Mac Integration (5.0.1.SA.5.0.18, extension), Zotero LibreOffice Integration (5.0.6.SA.5.0.18, extension), Zotero Better Bib(La)Tex (5.0.2.4220.master, extension), Shockwave Flash (26.0.0.151, plugin)

(3)(+0042422): {better-bibtex} PrefPane.getCitekeyFormat...

(3)(+0000002): {better-bibtex} PrefPane.getCitekeyFormat got [auth:lower]_[veryshorttitle:lower]_[year]

(3)(+0001181): {better-bibtex} Prefs.set citekeyFormat [auth:lower]_[veryshorttitle:lower]_[year]
```

**Comment by retorquere** [comment]
I'm going to lock the UI until I'm getting an all-clear from the Zotero DB. For some reason Zotero releases the UI way before I can even start my init, which leaves an uncomfortably long window before BBT is in a stable state.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4280](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.16.4280.issue-725.xpi) ("fixes #725").

**Comment by retorquere** [comment]
Can you give 4280 a go?

**Comment by floriandierickx** [comment]
This fixed the issue, works smoothly! Hysterical clicking on menu items, reference items, tags, ... didn't do any harm to the startup process :)
