### ISSUE TITLE
Z5: Failure to finish initialisation disables error reporting and export

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#726]
I installed 4220 and the pop up showing "BetterBibTex: Initialising" is not closed. Although the citekeys are present and I can pin/unpin/refresh successfully. When I try to generate an error the popup window is open but there is no error content and I can not click next. 
Also, I can not export the library: it shows an error. 
The problem might be that there is a dependency: in order to send errors or make exports the "BetterBibTex: Initialising" should be finished and closed.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing new test build [4225](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.2.4225.issue-726.xpi).

**Comment by retorquere** [comment]
Can you try 4225? You won't be able to right-click references to submit a debug log, but the option in the help menu should work.

**Comment by mijalche** [comment]
It solves the problem. I can generate an error report and auto export is functioning.
