### ISSUE TITLE
question about bibtex* key in export

### ISSUE THREAD

**Issue by dmbortz** [retorquere/zotero-better-bibtex#727]
I'm using 4214 and I have a question.  The entries I have recently created work perfectly (i.e., the italicized "Citation Key" at the top of an entry is correct).  However, the previously created entries (i.e., most of them) still have the "bibtex*:blah" in the Extra field.

1) I can't clear out to Extra field with a "pin", "unpin", or "refresh" command (should it do that?).  If not, is there a way to bulk clear the Extra field?

2) When I export to a bib file, the Extra field is included, despite unselecting "Export Notes".

My question is basically: what am I doing wrong?

**Comment by retorquere** [comment]
Ah, that's unfortunate. Yes, I did used to have the dynamic keys there, but performance was lousy. I had a few versions that cleaned out the now-defunct `bibtex*:` format but dropped that code at some point, as it was hitting the same performance bottleneck. I can make a special build that will scrub them if you have too many to clear manually.

`Export Notes` flags whether you want attached notes (the yellow stickies) exported, it doesn't affect the `extra` field. If you want to skip the `extra` field you would have to add it to `skipfields` in the preferences.

(one concern per github issue preferred BTW).

**Comment by dmbortz** [comment]
Yeah, I do actually have too many to clear manually. However, I'm not worried about the "Extra" field, except that when I put "Extra" in the box of fields to skip, it doesn't - and the bib file still has the "bibtex*:blah" in the "note" field.  I can make a new issue though...give me a few minutes...

**Comment by retorquere** [comment]
I'll get you a scrubber build.

**Comment by dmbortz** [comment]
thanks so much - that's awesome!

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4261](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4261.issue-727.xpi), apparently because bibtex*: scrubber.

**Comment by retorquere** [comment]
Try 4261. I won't be merging this into master -- a single time starting up with this build should remove the `bibtex*:` marks, after that you don't need it anymore.

**Comment by dmbortz** [comment]
Hmm...I tried pin, unpin, refresh, and a BBT export to a bib file.  But, nothing changes the "bibtex*:blah" entry in Extra.  Is there something specific I should try?

**Comment by retorquere** [comment]
Just install and restart should do it.

**Comment by retorquere** [comment]
Can you get me a copy of your `zotero.sqlite` (while Zotero is *not* running)?

**Comment by retorquere** [comment]
Ah damn I see the problem already. A copy of your DB would still be helpful though.

**Comment by dmbortz** [comment]
https://www.dropbox.com/s/vu99datbh7hagpz/zotero.sqlite?dl=0

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4262](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4262.issue-727.xpi), apparently because *asynchronously* remove bibtex*:.

**Comment by retorquere** [comment]
I've ran 4262 on your DB an after "Ready for business" I no longer see `bibtex*:` in my spot checks. It will take a *long* time to start up though; it's the primary reasons why I'm no longer using `bibtex*` in the extra field -- having the authoritative citekey data in the extra field is a performance disaster, to be revisited when the Z teams adds a separate field for the cite key.

**Comment by dmbortz** [comment]
It worked for me as well - awesome!  thanks so much.
