### ISSUE TITLE
export doesn't use "Fields to omit from export" 

### ISSUE THREAD

**Issue by dmbortz** [retorquere/zotero-better-bibtex#729]
In the BBT preferences, I have included "Extra" in the "Fields to omit from export" field.  However, the generated bib file still has text from the Extra field. Note that the only thing in the Extra field is the "bibtex*:blah" generated bibtex keys.

Report ID:RKCC6LTZ

**Comment by retorquere** [comment]
That list takes the names of the bib(la)tex fields to omit from export. For `Better BibLaTeX` export you would put `note` there for example to skip the contents of the `extra` field.

**Comment by retorquere** [comment]
Is this explanation sufficient? Or do you still experience other problems?

**Comment by dmbortz** [comment]
Yup - that makes complete sense... thanks!
