### ISSUE TITLE
BibTeX import: preamble with def create problems

### ISSUE THREAD

**Issue by OlafKleinBerlin** [retorquere/zotero-better-bibtex#732]
Hello, 
I have observed the following problems with bibtex Files involving preamble commands
involving defs:

If I try to import a file with a preamble commands containing a complicated
def command (being the result of an old bibtex export from mathematical reviews),
see the file [problem-preamble.txt](https://github.com/retorquere/zotero-better-bibtex/files/1306524/problem-preamble.txt) renamed to to problem-preamble.bib, the import stops with 
the typical zotereo error message (see Error reports  5WM42JHA, HH4U5U9P, DBTTYV3U).
This still holds, if the bibtex file is changed and the defined command is not used in the following 
entry.  

If I import a file with a preamble command with a simple def command, see the file 
[problem-preamble-okay.txt](https://github.com/retorquere/zotero-better-bibtex/files/1306530/problem-preamble-okay.txt) renamed to problem-preamble-okay.bib, then the import works,
but I am not sure if is correct that the defined command in authors is completely ignored during the import.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4267](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4267.issue-732.xpi) (undefined).

**Comment by retorquere** [comment]
Can you try 4267? It should fix the error, and I've added problem-preamble.txt as a test case to prevent regressions. The reference will require fixing after import; BBTs parser is not a full LaTeX processor (that'd be pretty crazy to even try), so the `\def` in the preamble will be ignored, and the name will come out as `[Franc] [Jan]`, not `[Franců] [Jan]` (although `\r u` should import correctly I think).

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4270](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4270.issue-732.xpi) ("Merge branch '723' into 732").

**Comment by retorquere** [comment]
Really could use confirmation on this.

**Comment by OlafKleinBerlin** [comment]
Will check tomorrow on my PC. Sorry for the delayed response.

Am 17. September 2017 20:55:56 MESZ schrieb retorquere <notifications@github.com>:
>Really could use confirmation on this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/retorquere/zotero-better-bibtex/issues/732#issuecomment-330072046

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by OlafKleinBerlin** [comment]
I have tried to test build 4267, but it seems that the link points to an invalid file. I could not load this file
with only 127K as app to zotereo.
I have tested now build 4270 and could import both files for the  problem-preamble.bib file there is 
an additional entry in the literature list which contains the informations: 
>>Import errors found:  Parse error: found "1", expected "}" <<
I think that this is a almost the solution for the really complicated macro situation.
Thank you. 

But I am thinking about how to deal with  LaTeX/TeX macros in BBT. I agree to your point
of view that trying to build a full LaTeX parser is out of question.
But, I am thinking on those commands BBT can not deal with. Maybe BBT could mark somehow
that some fixing is required, for example by marking the overall entry with some tag/some note or 
inserting it into some new subcollection "Entries needing fixing" 
and by replacing the complicated command by 
>>"UNEXPANDED_MACRO["copy of complicated"]"<< in the resulting entry, e.g 
replaceing "\ocirc{u}" by  "UNEXPANDED_MACRO[\ocirc{u}]" in my example.  Should I open a new issue for this discussion, or has this already been discussed before?

**Comment by OlafKleinBerlin** [comment]
Sorry, I closed the issue accidentally.

**Comment by retorquere** [comment]
Yeah sorry about that link, the build process only retains the last 6 builds, so if you don't grab them promptly they get removed as I push out newer builds. I can always produce a new build, no problem.

No need to open a new issue -- I've added a [feature request](https://github.com/fiduswriter/biblatex-csl-converter/issues/82) for the parser so I can mark references appropriately, but I wouldn't expect too much -- bib(la)tex import is always going to have problems with anything but very straightforward references.

Thanks for the confirmation, I'll fold this into a new release.
