### ISSUE TITLE
Z5: quick-copy & automatic journal abbreviation

### ISSUE THREAD

**Issue by RafalSkolasinski** [retorquere/zotero-better-bibtex#733]
- continuation of additional posts in https://github.com/retorquere/zotero-better-bibtex/issues/604
Thanks for a quick reply there! I am afraid however that it is still not working for me.

I installed [pre-relase v5.0.22](https://github.com/retorquere/zotero-better-bibtex/releases/download/v5.0.22/zotero-better-bibtex-5.0.22.xpi) (through the automated update) and updated Zotero to ``5.0.20`` (through the automated update too).

I see the new option in ``Better BibTeX`` settings Pane: Journal abbrevations, and I have the only option there checked.

Unfortunately still when I do quick copy of an entry with ``ctrl+shift+c`` the journal names don't get abbreviated. When I click it however with RMB and select export, then it does---just in case you'd be worried that the entry on which I am testing it is corrupted. 

I will be happy to provide any additional details you may need.

**Comment by retorquere** [comment]
What quick-copy translator do you have set?

**Comment by RafalSkolasinski** [comment]
It is ``Better BibTeX``. This is the option I set. Is there any other place I should change settings in?

![2017_09_20_12 10 00](https://user-images.githubusercontent.com/10928117/30638729-a686520c-9dfc-11e7-9560-fa5d6c540dc1.png)

**Comment by retorquere** [comment]
Can you right-click the reference you were quick-copying and select "Send BBT error"?

**Comment by RafalSkolasinski** [comment]
Here it comes IZ8RPBY6

**Comment by retorquere** [comment]
Ah, that's a different matter. You're not looking for auto-abbreviation (which is what the preference controls) but to have the abbreviated title exported to the reference `journal` field instead of the full title. 

What you want is not possible; during regular export you can check `Use journal abbreviation`, but there's no way to communicate this intent to quick-copy, and Zotero doesn't tell translators whether they're being used for quick-copy or regular exports, so I can't enforce it for quick-copy only.

**Comment by RafalSkolasinski** [comment]
Ah... I see... Do you know maybe about some extension that could go over all my entries and abbreviate them? Anyway, this issue can be closed then.

**Comment by retorquere** [comment]
You want all your reference titles replaced by their abbreviated titles? Or do you want the Abbreviated Title field filled for all your references?

**Comment by RafalSkolasinski** [comment]
I want to have Quick-Copy export abbreviated name as a title so I hope just substituting all names by abbreviated form would do the trick. I could always export first to file (checking abbreviate option) and then copy paste it wherever I want to but it seems like annoying hassle to do.

**Comment by retorquere** [comment]
If Zotero had export options for quick-copy I could make use of those, but as it is there's nothing I can do about this that would not also affect regular exports.

I don't know of any extensions that do what you want, sorry.

**Comment by stroitzsch** [comment]
For reference if anyone comes across this issue:

A workaround to get journal abbreviations with `Better BibTeX` quick-copy is to edit `Zotero\translators\Better BibTeX.js` and set `"useJournalAbbreviation"` to `true`.

**Comment by retorquere** [comment]
Which will get overwritten the next time BBT updates.
