### ISSUE TITLE
Z5 v5.0.22: manual refresh of dynamic keys -> no warning when changing more than allowed number

### ISSUE THREAD

**Issue by floriandierickx** [retorquere/zotero-better-bibtex#734]
Report ID: YFXDIIGX

As manual refresh of dynamic keys is mentioned as 'to be tested', I gave it a try and observed that when changing more than the allowed number of citations is changed (advanced -> warn me when changing citation keys in bulk) there is no warning.

Settings:
Warn me when changing citation keys in bulk: 10

Report ID actions:
1. Changing 10 references (no warning as expected)
2. Changing around 15 references (no warning)
[3. Changing all the references (2441 items) in the database] (not relevant for this issue)

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4317](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.22.4317.issue-734.xpi) ("warn on bulk refresh").

**Comment by floriandierickx** [comment]
This fixed the issue!

**Comment by retorquere** [comment]
Thanks for the confirmation
