### ISSUE TITLE
Z5 v5.0.22: manual refresh of dynamic keys -> citation key column changes when scrolling/moving mouse over citation

### ISSUE THREAD

**Issue by floriandierickx** [retorquere/zotero-better-bibtex#735]
Report ID: YFXDIIGX

When changing citation style of non-pinned citation keys, the 'Citekey' column only shows the key change either when scrolling with the mouse (all changes visible at once), or when moving with the mouse over the changed citations (individual change of citation key when moving over). The changes in the right 'Info' column are displayed correctly as expected. In the end it does not obstruct the usability of the app at all, but it's one of the (minor) observations..

I also experienced the display issue for pinned keys as explained in issue #713, but this does not come into play here as I didn't pin any keys.

Report ID actions:

1. Changing 10 references (no warning as expected) -> visibility changes as explained above
[2. Changing around 15 references (no warning)] (not relevant for this issue)
[3. Changing all the references (2441 items) in the database] (not relevant for this issue)

**Comment by retorquere** [comment]
Looking at the logfile I think it may be caused by the same problem of #738. Can you try to reproduce with 4316, and if it still occurs, submit a new debug log?

**Comment by floriandierickx** [comment]
The issue is still there it seems (changed 5 references, no warning as expected), changed 15 references (also no warning). I tried to submit a bug report (with right clicking a reference), but it gave the following output:

```
Invalid response from repository: 403, expected 204
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>DAE96CE26E225639</RequestId><HostId>fz2oDX22St2tvGcuPb6XiuTn9uljEmwaM51Jri01k38JjpZFDIccLuhDJJVQ3R1O8srI/iOfctk=</HostId></Error>
```

Also another app is giving error messages something related to javascript (I have also python running, maybe that's an issue?). Hmm.. I'll try a restart and see what it does.

**Comment by retorquere** [comment]
The error above doesn't seem to relate to BBT. Can you submit a new error log from 5.0.23?

**Comment by retorquere** [comment]
(the error you listed comes from Zotero trying to update bundled tools/translators -- looks like they haven't updated their policy document on S3. The error should be harmless to BBT)

**Comment by floriandierickx** [comment]
There is still the same error when trying to submit an error report, also in 5.0.23. And in another application (gmail inbox) created with nativefier (https://github.com/jiahaog/nativefier) I also get an error message which wasn't there before:

A Javascript Error occurred in the main process
```
Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
    at App.<anonymous> (/Applications/Inbox.app/Contents/Resources/app/lib/webpack:/app/src/main.js:61:7)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)`
```

I recently removed xcode developer tools, might be linked with that.. As zotero is also a javascript application, I guess indeed it's not linked with BBT. I will try to get a solution somewhere else.. :) Maybe reinstall javascript? Hmm..

**Comment by floriandierickx** [comment]
hm I made a mistake, Java = not JavaScript as I remember correctly :)

**Comment by retorquere** [comment]
Java is indeed not Javascript. 

The errors in gmail inbox and other apps are not related to BBT. The javascript interpreter Zotero uses lives inside Zotero and has no relations to other javascript-running apps.

Error reporting should now work again, I had let the form submission expire.

**Comment by floriandierickx** [comment]
Ok, it works again. The report ID is IJSFAPY7. I changed some citations, and moved over with my mouse, changed again some citations and a slight scroll to change the appearance. It's really a very (!) minor issue, just if it's easy to fix, why not..

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4335](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.24.4335.issue-735.xpi) ("fixes #735 (although 'easy' isn't exactly the right term)").

**Comment by retorquere** [comment]
Can you give 4335 a run?

**Comment by floriandierickx** [comment]
Yes, bingo. Fixed! The keys refresh all at once, looks nice! And sorry to add this, but it seems there's a side-effect: depending on the citation, the space between `Citation Key` and `Item Type` changes, and also the alignment of the four tabs (`Info`, `Notes`, `Tags` and `Related`) shift to the right, sometimes completely, sometimes a little bit.. I've added some screenshots to illustrate:

<img width="335" alt="screenshot 2017-09-22 14 03 10" src="https://user-images.githubusercontent.com/12695083/30743723-2fe93fd4-9f9f-11e7-81db-8eafc3ea60ef.png">
<img width="333" alt="screenshot 2017-09-22 14 03 01" src="https://user-images.githubusercontent.com/12695083/30743724-30729b80-9f9f-11e7-9775-3edc7b09f3f7.png">
<img width="333" alt="screenshot 2017-09-22 14 02 36" src="https://user-images.githubusercontent.com/12695083/30743725-3074d634-9f9f-11e7-9bec-a62020d81e12.png">

**Comment by floriandierickx** [comment]
And double checked with v5.0.24, it does not seem the case in this last pre-release.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4336](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.24.4336.issue-735.xpi) ("fiddle with sizing").

**Comment by retorquere** [comment]
That's correct, 4335 tries a different way to get the citekey into the item pane.

The Zotero item pane assumes no one else has any business there and will clear out all fields whenever something changes. Keeping a field there takes a whole lot of contortions. The new way is more stable but messes with the layout apparently.

The only really safe way to do it is to have it in a separate tab. That would fix the layout issue, but there's not a whole lot of space in the tab bar above the item, so if anyone else comes to this grand idea, it'd mess up the layout again. It also seems like an enormous waste to have a whole pane dedicated to just the citekey.

Try 4336, but I'm considering just dropping the citekey from the itemPane. Zotero is fighting too hard against changes to that pane.

**Comment by retorquere** [comment]
(sorry -- 4337. Should drop in a few minutes).

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4337](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.24.4337.issue-735.xpi) ("minimize margins").

**Comment by floriandierickx** [comment]
I tried with the one you linked, and it fixes the issue perfectly! Both the citekeys visually change after refreshing, and there are no visual changes in the item pane anymore. It seems indeed something zotero doesn't allow to fiddle with too much, but how it is solved now makes it very usable. If it is possible to keep it in de itempane, it increases the usability somehow by allowing to quickly verify a citekey when writing (although this is also possible with the citekey column open in the reference list itself). The only practical '+' seems to me that it's possible to select and copy the text from the itempane (and use it in a text editor), which is not possible with the citekey column..

<img width="337" alt="screenshot 2017-09-22 16 30 46" src="https://user-images.githubusercontent.com/12695083/30749602-2fee3812-9fb4-11e7-9925-9a7a23d4a637.png">
<img width="333" alt="screenshot 2017-09-22 16 30 37" src="https://user-images.githubusercontent.com/12695083/30749603-30445cba-9fb4-11e7-88c4-191c041641aa.png">

, which is not possible in the citekey column

**Comment by retorquere** [comment]
The copy-paste functionality is why I want it there. If this is OK as-is I'll just merge it in; I've asked the Zotero devs for tips on how best to do this, but they're not too fond of people screwing around with their layout (which is a ^@$&%&#$ to get right TBH). I still screw up the prefs pane layout.

**Comment by retorquere** [comment]
(I don't link to these builds myself BTW -- I have scripts that post links automatically; I just can't prevent my account being associated with those posts)

**Comment by floriandierickx** [comment]
Ok there's a slight intend change compared with before, but anyway, that does not alter at all the usability.. And the better bibtex preferences pane does seem to me completely normal, works perfectly!

**Comment by retorquere** [comment]
Yeah I know about the indent but the alternative was that the fields sometimes scrolled from left to right.

If you look at the Zotero "Cite" pane in the references you'll see it has a margin at the bottom and the right which isn't there if BBT is not installed.
