### ISSUE TITLE
Z5 v5.0.22: manual refresh of dynamic keys -> no citation key change when changing large set of items

### ISSUE THREAD

**Issue by floriandierickx** [retorquere/zotero-better-bibtex#736]
Report ID: YFXDIIGX

When changing a large set of items (2441), the citation keys don't seem to change. I don't know if it's a a performance issue, personal issues with impatience or something else... I've let it run for some minutes (and zotero effectively uses CPU for that it seems, around 120 %) until it drops to a 'normal' level of around 3-5 %.

Report ID actions:

1. Changing 10 references : visible change (both in column + sidepane)
2. Changing around 15 references : visible change (both in column + sidepane)
3. Changing all the references (2441 items) in the database: no visible change (both in column + sidepane) after around 4 minutes (drop in zotero CPU usage)

**Comment by retorquere** [comment]
Looking at the logfile I think it may be caused by the same problem of #738. Can you try to reproduce with 4316, and if it still occurs, submit a new debug log?

**Comment by floriandierickx** [comment]
Good news, that's indeed the case. After a refresh of all the bibtexkeys, they all change accordingly..
