### ISSUE TITLE
Z5: Early import seems to create race condition and afterwards citekey confusion

### ISSUE THREAD

**Issue by OlafKleinBerlin** [retorquere/zotero-better-bibtex#737]
Be being really nasty to BBT, it seems that I have produced a strange citekey confusion: 

Starting from Zotero 5.0.20 without the BBT addon I imported the file 
[hystop-redu.txt](https://github.com/retorquere/zotero-better-bibtex/files/1318045/hystop-redu.txt)
(renamed to hysop-redu.bib) five times. Afterwards I installed BBT 5.0.22 and
restarted zotero. After the restart I did not wait for BBT to become ready, but 
immediately started to import the file hystop-redu.bib again while BBT was occupied with 
dealing with all the entries in my library without citekeys.  
Hence, in the 6th imported version of hystop-redu.bib, my citekeys were not imported. 
Now, after this import was complete and also BBT was ready for business, 
I imported  hystop-redu.bib again. 
Clicking now on the first tag, i.e. on "<-- Tag Not Handled ..><--keyword=#key0 ............",
and clicking afterwards on the corresponding paper in the central paper list, I get
![test-citekey-hmm](https://user-images.githubusercontent.com/23361693/30650304-e0afb98e-9e22-11e7-8512-e58511a26a72.png), i.e. the citekey in the central list and in the info window is
equal to the citekey `Klein-2013-HMM` in my bibfile. 
Now, clicking on Tags, afterwards on notes and afterwards on info in the right-hand part of the 
zotero window, I get 
![test-citekey-long](https://user-images.githubusercontent.com/23361693/30650510-5b1f533c-9e23-11e7-95f6-1aaa7df20547.png), i.e. the citekey in the info window is now
`Kleinrepresentationresulthysteresis2014b` but the citekey in the center is still  `Klein-2013-HMM`.

And now it becomes even more wired: Attaching the dataset for this  paper in the sixth, i.e. in the second to last,  import of  hystop-redu.bib,  by clicking the strange tag and clicking on
the  dataset method again, and returning afterwards to the dataset within the last import 
of hystop-redu.bib, the citekey in the import window become `Klein-2013-HMM` again.

I agree that this error in this situation is maybe not important, since I ignored that BBT is not ready, 
but considering it may allow to get rid of a more general problem.

**Comment by retorquere** [comment]
If you're importing before BBT says "ready for business", you're importing using the stock importers of Zotero. I wish to _X_<sup>1</sup> that I could just lock the Zotero UI until BBT is ready for business, or that Zotero would have a clean mechanism allowing extensions to initialize, but I can't, and it doesn't. I'm hoping one of the Zotero devs [gets me some info](https://groups.google.com/forum/#!topic/zotero-dev/wx5j8Y8Dwjo), but I'm not holding my breath. The init circus has cost me a disproportionate amount of time already, so I can't assure you I'm going to try and work around this without infra support by Zotero.

I'm having some difficulty following the scenario TBH. I'd need to see the content of the extra field, because right now I don't know whether a citekey is pinned. A copy of your Zotero DB and the better-bibtex.sqlite files may tell me more.

<sup>1</sup> where _X_ is your pick of deity, I'll take whatever works.

**Comment by OlafKleinBerlin** [comment]
Since there seems now to be a kind of progress bar part of zotero, showing up e.g. if one tries
to empty the trash if it contains many items, there may be some (small?) hope to get access to this component maybe also  from your extension.  

But, after some tests I realized now that my problem seems not to be an  problem with the initialization of BBT, but a general bug:
I seems that the citekey of the **first** open opened is stored somehow, and is shown up
later for all papers in the "info" tab on the right-hand side,  if **before** the "notes" or the "tag"-tab 
have been cheeked.
To reproduce this 
I start Zotero 5.0.20 with BBT 5.0.22 and **wait until** BBT is ready for business. Afterwards I import 
[citekey-conf.txt](https://github.com/retorquere/zotero-better-bibtex/files/1320277/citekey-conf.txt), 
and open the first entry (Aaa) in the list. Afterwards I open the second entry (Bbb) in the list.,
and the citekey shown in the info tab is BBB, i.e. the citekey in my bibtex file, which was imported imported thanks to thanks to BBT. 
Opening the tags view, afterwards the notes view and finally the info view again, I end up with:
![test-citekey-new](https://user-images.githubusercontent.com/23361693/30683799-1f6b5782-9eaf-11e7-91e3-f1cf6e0fff57.png)
So the citekey displayed in the  info panel now shows the  citekey AAA, i.e. the one displayed for the **first** paper opened. If I open now the last paper (CCC)  in the list, the citekey shown initially is the correct one, but after opening the  the tab view or the note view and reopening the info 
view, the displayed citekey key ist AAA again. 
If I quit afterwards zotero and start it again, and now open e.g. the last paper in this libary, i.e. (CCC),
then this citekey shows up for all papers in the info view, if **before** the notes or the tags view were chose.

**Comment by retorquere** [comment]
I could indeed tap into the progress bar, so the init race condition should now be solved in .23

The info pane citekey not updating is currently a known problem -- the item pane is *really* resistant to monkey patching. I'll try what I can but it's starting to look like the real solution will only come when Zotero adds the citekey field as a native field. This is planned, but there's no clear time line -- but not before the end of the year.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4325](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.23.4325.issue-737.xpi) ("itemPane refresh").

**Comment by retorquere** [comment]
Can you try 4325?

**Comment by OlafKleinBerlin** [comment]
4325 solves the item pane refresh problem. 
Moreover, the progress bar stops me form doing stupid thinks while BBT initializes.

Thanks for your efforts. 

(As check for the "user have to wait" time, I have imported https://github.com/retorquere/zotero-better-bibtex/files/1318045/hystop-redu.txt renamed to hysop-redu.bib five times to zotero 5.0.20 without bbt. After installing bbt, 4325 and 
restarting zotero  BBT blocked the  zoterio UI for around 22 seconds since also the citekey needed
to be created. At the following start of zotero, bibtex blocked the UI for around 6 seconds. )

P.S.: I have really tried to create problems by removing/deinstalling BBT just during a file import, but I have not succeed.

**Comment by OlafKleinBerlin** [comment]
(For comparison: If I remove the collections and the iitems of my five hysop-redu.bib inports,
empting the trash takes around 4 seconds.)

**Comment by retorquere** [comment]
It's possible that Zotero will at some point have a more structural solution for extension init, but right now this makes sure BBT is in a stable state before you can start messing with its database.

I think I've also fixed the issue from https://github.com/retorquere/zotero-better-bibtex/issues/737#issuecomment-331079921 (to the extent that it is fixable at all) -- are you satisfied with how it works now?

**Comment by retorquere** [comment]
Oh wait you already said it was fixed. Great, then I'm merging this in.
