### ISSUE TITLE
Z5: in citation pane, dynamic citation key is not italic

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#739]
When I add new citation in the column I get an * as indication for dynamic citation key. However, in the details pane the citation key is not *italic*, but it is regular, thus not showing that it is still dynamic citation key.
ID report is 8DDKR5L3

**Comment by mijalche** [comment]
I also think that it might be better the indication in the details pane for dynamic key to be * as a consistency with the indication in the column

**Comment by retorquere** [comment]
Having the `*` be in the field would mean you'd also pick it up if you copy-pasted from that field.
