### ISSUE TITLE
additional bbt lines in extra field

### ISSUE THREAD

**Issue by ppoppitz** [retorquere/zotero-better-bibtex#741]
I'm not sure if this is an error, a misconfiguration on my side or the remains of an update.
I noticed a second line in the extra field including an asterisk. When manually pinning a citekey, a second line is added:

> bibtex*:bartolini_great_2014
> bibtex: bartolini_great_2014

unpinning removes the second line, but not the first.

TL;DR: everything working fine, just confusing.

Report ID: BERWVYYX

**Comment by retorquere** [comment]
That's a remnant of an earlier approach to storing dynamic citekeys; there had been builds in te interim that removed those which you must have missed (builds didn't auto-upgrade back then). You can install [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.26.4349.scrub-star.xpi) build which will remove those lines but it will always be slow to startup; my advice would be to install it, restart Zotero to let it do its cleanup work, and then install 5.0.26.
