### ISSUE TITLE
Zotfile does not function well with better-bibtex

### ISSUE THREAD

**Issue by qyin** [retorquere/zotero-better-bibtex#742]
I don't know if it is appropriate to report this bug here.

I basically use two extension with zotero, zotfile and better-bibtex

Recently I upgrade zotero 4 to zotero 5 and find the "send to/get from tablet" function of zotfile does not play well with better-bibtex.

The problem is if I disable better-bibtex, then the "send to/get from tablet" function works as expected.

1. use "send to tablet" for an attachment file, the zotifle will send a copy of the file to a predefined place and add a tag "_tablet" to the attachment.
2. for an attachment with a "_tablet" tag, using the "get from table" function, zotfile will replace the attachment file in zotero storage with an updated version in the predefined place.

When better-bibtex is enabled, I can still use the "send to tablet" function and the attachment file will be sent to the predefined place as expected. But the file will not be updated with a tag "_tablet" as expected. As a result, the "get from tablet" function is not applicable if I want to get the updated version from the predefined place.

Zotero version: 5.0.21
Better-bibtex version: 5.0.26
Zotfile version: 5.0.4

**Comment by retorquere** [comment]
Can you send an better bibtex error report after the failing action?

**Comment by retorquere** [comment]
Never mind, it's reproducible. With BBT installed, there's a most unhelpful `Exception... "Unexpected error"` in the logs (no shit Firefox).

I don't see any obvious thing that I'm touching that would affect Zotfile, so we'll need help from @jlegewie. Can you open an issue on the [Zotfile issue tracker](https://github.com/jlegewie/zotfile/issues)?

**Comment by qyin** [comment]
@retorquere, Sure.

I have opened an issue jlegewie/zotfile#307 on the Zotfile issue tracker.

**Comment by retorquere** [comment]
Can you still get me a debug log using "Send BBT error"? Perhaps there's a different/more informative error in your logs. What I'm getting is not much to go on.

**Comment by qyin** [comment]
Hi @retorquere,

Report ID: CGBC2WX4.
