### ISSUE TITLE
Z5: Auto-Export Fails

### ISSUE THREAD

**Issue by jGleitz** [retorquere/zotero-better-bibtex#744]
Failure Report: GSPXQR9T

I noticed that my Library wasn’t auto-exported anymore. I tried:

* Changing various entries and fields
* Removing the target file, re-adding the target file
* Hitting “Refresh” and “Export” in the BetterBibTex settings
* Restarting Zotero and trying these things again

neither did have any effect on the exported file. I also noticed that clicking “Remove” in the BitterBibTex settings did not remove the configured export.

I restarted with debugging enabled and did these things:

 * Changed an entry
 * Clicked “Refresh” in the Automatic Export settings
 * Clicked “Export” in the Automatic Export settings
 * Clicked “Remove” in the Automatic Export settings. This time it worked and the configured export was removed.
 * Re-configured the automatic export. Now it worked as expected.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4365](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.26.4365.issue-744.xpi) ("Merge branch 'master' into 744").

**Comment by retorquere** [comment]
Please try 4365

**Comment by jGleitz** [comment]
I have installed 4365. Please note that the issue does not occur reproducibly (or at least I wouldn’t know how to produce it). But I will report back if I ever see it again.

**Comment by retorquere** [comment]
You have an item with a date `2017-07-25T19:00` that I failed to parse right -- you would have seen a "rescanning" popup every start that you won't see anymore now. The auto-exports failing was likely just fallout from the init failing. If you can manually trigger the registered auto-export to `/home/josh/Dokumente/Bachelorarbeit/Literature.bib` and it succeeds, the problem is gone.

**Comment by jGleitz** [comment]
I couldn’t find an entry with that format in my database, so I added one. The same symptoms started again. Failure report: 46LGS3I3

What I find odd is that once I have removed the export and added it again, auto-export works just fine, even though the entry is still present. Even if I edit the entry, nothing breaks, even when editing the date.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4366](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.26.4366.issue-744.xpi) ("test date parse for NaN").

**Comment by retorquere** [comment]
Can you try 4366? Same thing, a manually triggered auto-export should now succeed.

**Comment by retorquere** [comment]
(it was the `updated` field of the auto-export that cause the breakage -- a newly registered auto-export would not have one)

**Comment by retorquere** [comment]
Forget the manual trigger -- the problem was 

1. set up auto-export
2. restart (which would fail to load the auto-exports properly)
3. trigger an auto-export

The auto-exports should load correctly in 4366, but a log generated after a restart will make sure.

**Comment by jGleitz** [comment]
Tried with 4366: 

 * set up auto-export
* restart (the rescanning dialogue did not show on start!)
* trigger an auto-export

everything works fine. Any changes I make are auto-exported.

But after a restart, the rescanning dialogue shows again and the symptoms are back again.

Failure report: WLVBUML5

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4367](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.26.4367.issue-744.xpi) ("more debug logging for #744").

**Comment by retorquere** [comment]
there's still the problem with your autoexport database. I've added more debug logging, can you get me a new log?

**Comment by retorquere** [comment]
NM, I have it reproducible

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4369](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.26.4369.issue-744.xpi) ("cleanup").

**Comment by retorquere** [comment]
4369 solves it for me, can you try that? No need to set up new auto-exports; if you have existing auto-exports, triggering them in any way after a restart would have resulted in an error. It should now proceed without error.

**Comment by jGleitz** [comment]
I was not able to produce this issue with 4369. However, I still get the “waiting for Zotero database”, “scanning” etc. dialogues everytime I start Zotero. Is that expected?

**Comment by retorquere** [comment]
I hope that at some point the `waiting for Zotero database` will be fast enough to be unnoticeable, but as the message says, BBT is at that point just waiting for the go-ahead from Zotero that the database is ready for use. I've been told in no uncertain terms by the Zotero devs not to do anything with the database before I get the signal that the DB is ready. I'm not fond of the delay myself (its worst on first startup, which means every time for me in my testing -- 20 seconds is common), but it's out of my hands. The startup time is on the Zotero team's radar but I don't know how far along they are in solving it:

* https://github.com/zotero/zotero/issues/1298
* https://forums.zotero.org/discussion/67287/zotero-very-slow-to-open
* https://forums.zotero.org/discussion/67545/5-slower
* https://forums.zotero.org/discussion/67627/long-loading-time-for-5-0-18
* https://forums.zotero.org/discussion/67104/long-synchronisation-with-z5
* https://forums.zotero.org/discussion/63763/zotero-standalone-mac-very-slow/

As to the other messages, you should only see `Scanning for references without citation keys`, but not `Assigning citation keys`. The `scanning message is however superfluous to the `Starting key manager` message, so I'm removing the former.

If you can send me a new log I can ascertain that the error messages you had are now gone.

**Comment by jGleitz** [comment]
Thanks for the detailed explanation. The messages don’t bother me (I only start Zotero one or two times per day), I just wanted to make sure that they don’t indicate an error.

Failure report: TFSZ969F

**Comment by jGleitz** [comment]
Thanks for fixing this (and fixing it so fast)!

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4372](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.26.4372.issue-744.xpi) ("Merge branch 'master' into 744").

**Comment by retorquere** [comment]
Took me a lot longer than I had hoped. There are some unrelated errors in your log -- can you submit a new log with 4372 to see if I got those too?

**Comment by jGleitz** [comment]
Of course: U2FK4HC4

**Comment by retorquere** [comment]
Super, thanks, that took care of those. I've scheduled a release of 5.0.27 -- you should auto-update somewhere in the next 24 hours (don't know what schedule Zotero has set for addons), but you can force it from the addons pane. 5.0.27 is just a tagged 4372.

**Comment by jGleitz** [comment]
Thanks!
