### ISSUE TITLE
Z5: Wrong Citekey When Importing .bib from the Web

### ISSUE THREAD

**Issue by jGleitz** [retorquere/zotero-better-bibtex#745]
I imported a bibtex-citation from the web ([this article from SpringerLink, to be precise](https://link.springer.com/chapter/10.1007/978-3-642-31753-8_17)) and it was assigned a wrong citation key. According to my citekey format, `[auth]_[shorttitle]_[year]`, it should have been `Martinez_EvaluatingImpactModelDriven_2012`. But it was `Martínez2012` instead.

This only happened because, for some reason or another, I didn’t use the “Zotero button” in Firefox, 
![zoterobutton](https://user-images.githubusercontent.com/4305652/31056214-69309900-a6ce-11e7-9257-fdf43c846c30.png)
but Springer’s “Download .bib” function:

![download bib](https://user-images.githubusercontent.com/4305652/31056222-7838f8ca-a6ce-11e7-8e89-81a31eb8579e.png)
clicking the link will also store the citation in Zotero.

When using the “Zotero button”, everything works as expected.

Failure Report: NIAA66WD

**Comment by retorquere** [comment]
I don't know what the `Zotero` button does, precisely, but when you download that bibtex file, you get this:

```
@Inbook{Martínez2012,
author="Mart{\'i}nez, Yulkeidi
and Cachero, Cristina
and Meli{\'a}, Santiago",
editor="Brambilla, Marco
and Tokuda, Takehiro
and Tolksdorf, Robert",
title="Evaluating the Impact of a Model-Driven Web Engineering Approach on the Productivity and the Satisfaction of Software Development Teams",
bookTitle="Web Engineering: 12th International Conference, ICWE 2012, Berlin, Germany, July 23-27, 2012. Proceedings",
year="2012",
publisher="Springer Berlin Heidelberg",
address="Berlin, Heidelberg",
pages="223--237",
abstract="BACKGROUND: Model-Driven Engineering claims a positive impact on software productivity and satisfaction. However, few efforts have been made to collect evidences that assess its true benefits and limitations.",
isbn="978-3-642-31753-8",
doi="10.1007/978-3-642-31753-8_17",
url="https://doi.org/10.1007/978-3-642-31753-8_17"
}
```

BBT retains the key of files you import, so you get `Martínez2012`. If you want the BBT-generated key, you must right-click it and choose `unpin`, then `refresh` (or `unpin` and make any change to the reference, which will refresh the key)

**Comment by jGleitz** [comment]
Ah, I see. You’re respecting a citekey if it’s already set in a .bib file. That makes little sense when importing from some anonymous source but might make a lot of sense when importing personal or organization-specific .bib-files. I didn’t think of that.

I’m closing this as a non-issue.
