### ISSUE TITLE
Citation key year generated incorrectly when date field contains date range in DD-DD MMM YYYY format

### ISSUE THREAD

**Issue by breakeyd** [retorquere/zotero-better-bibtex#746]
The standard European-style date range is DD-DD MMM YYYY (e.g. 22-26 June 2015). When a date is entered in this format in Zotero, Better Bib(La)TeX generates an incorrect citation when using the "year" field in the citation key format.  Instead of the year (2015) it uses the first date (22). When the date entry is either June 22-26 2015 or 22 June 2015, the correct key is generated. Zotero itself recognizes this format and if the built-in bibtex exporter is used, the year is correctly used in the citation key.

Sample Zotero entry (conference paper):
Authors: Vera, J.V., Lawrence, J., Self, R.H., Kingan, M.
Title: The prediction of the radiated pressure spectrum produced by jet-wing interaction
Date: 22-26 June 2015

Generated citation key: `Vera_prediction_22`
Expected citation key: `Vera_prediction_2015`

Citation key rule used: `[Auth]_[Title:skipwords:select,1,1]_[year]`

I used this sample reference to generate an error report for this and obtained the following report ID: WN8SPSVR. I note that the citation rule is slightly more complicated than necessary, but even when just "year" is used, the same issue arise. I also note that I am using Zotero 5, but I think this is a more general issue, so I'm posting a new issue.

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4494](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4494.issue-746.xpi) ("fixes #746").

**Comment by retorquere** [comment]
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4496](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4496.issue-746.xpi) ("issue numbers").

**Comment by retorquere** [comment]
Can you try 4496?

**Comment by breakeyd** [comment]
I can confirm that this is solved in 4496. Thanks very much! I will mark it as closed.
