### ISSUE TITLE
Question: What does star next to citation key means?

### ISSUE THREAD

**Issue by RafalSkolasinski** [retorquere/zotero-better-bibtex#749]
Hi,
I just realised that column CiteKey shows star (*) after the Citation Key.
I couldn't find any information what it means.
Cheers,
Rafal

**Comment by Alexander-Serov** [comment]
It would be nice to mention it somewhere in the interface

**Comment by retorquere** [comment]
I've added it to https://retorque.re/zotero-better-bibtex/citing/#set-your-own-fixated-citation-keys, but I'd prefer new issues to be opened over reviving old ones -- it's ways too easy for me to overlook old issues, because they don't show up in open issues.
