### ISSUE TITLE
Quick copy does not work with keyboard shortcut

### ISSUE THREAD

**Issue by cossio** [retorquere/zotero-better-bibtex#753]
I have configured quick-copy to the better bibtex export format. When I select an item in the library and click Edit menu -> Copy as Better Bibtex, the bibtex data gets correctly copied. But if I use the keyboard shortcut (Cmd + Shift + C on a Mac), nothing gets copied.

**Comment by retorquere** [comment]
If you send a debug report after this happens I can take a look, but the quick-copy stuff isn't really bbt at work - zotero invokes the same translators when you use the shortcut or the menu option, and I'm not involved until that call happens. Does quick copy by shortcut work for other translators?

**Comment by cossio** [comment]
You are right, it does not work for other translators too, so it's Zotero problem.

**Comment by cossio** [comment]
I have posted this on Zotero forum, https://forums.zotero.org/discussion/68271/quick-copy-keyboard-shortcut-not-working#latest

**Comment by cossio** [comment]
After disabling BBT, the quick copy worked again. See https://forums.zotero.org/discussion/68271/quick-copy-keyboard-shortcut-not-working. Therefore it seems the problem is on the interaction between BBT and zotero, so I am reopening this.

**Comment by cossio** [comment]
By the way there is a debug report, D1137812411

**Comment by retorquere** [comment]
I have no access to those debug reports, can you send a BBT report instead?

**Comment by cossio** [comment]
Guess what? It is working now. Disabling and enabling BBT again fixed the problem. Sorry that I cannot reproduce it now. Maybe it will happen again in the future. Until then I will close this. Thanks!

**Comment by retorquere** [comment]
That's fine, I'm not complaining about problems that solve themselves :) Can you post this on the form too?

**Comment by cossio** [comment]
Sure.

**Comment by danmackinlay** [comment]
I experienced this problem too. Disabling BBT did not fix the keyboard shortcut, but re-enabling BBT _did_ fix the keyboard shortcut. 
This problem does recur intermittently across my computers; what would I do do collect debug information about it?

**Comment by danmackinlay** [comment]
I experienced this problem too. Disabling BBT did not fix the keyboard shortcut, but re-enabling BBT _did_ fix the keyboard shortcut. 
This problem does recur intermittently across my computers;
perhaps the procedure here will be useful to debug it: https://forums.zotero.org/discussion/comment/339352#Comment_339352

**Comment by retorquere** [comment]
Looking at that forum thread, it just seems to be an intermittent problem in Zotero. When you do a quick-copy, Zotero just runs the selected translator. That translator can work or fail, but it wouldn't touch the code path of the shortcut keys. I'm afraid there's nothing much I can do about this, as it does not seem to be caused by BBT. Re-enabling BBT will re-init the Zotero translators, maybe that's related, but that would still be a problem in Zotero. I've posted this information in the thread you linked, maybe that will help the Zotero devs with a diagnosis.
