### ISSUE TITLE
Keyboard shortcuts for BBT

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#754]
I do not think that it is very important, but I just want to ask is it possible to have a keyboard shortcut for BBT. For contextual menu like Pin/Unpin/Refresh? I tried with BetterTouchTool but with no success.
Thanks!

**Comment by retorquere** [comment]
I wouldn't know where to start; I'm not actually all that familiar how the UI stuff works in Zotero, as I'm more of a backend person, and the docs on the UI framework and Zotero are non-existent. For the UI work I copy from other extensions; if you know one that does it, I can take a peek.

**Comment by mijalche** [comment]
thank you for having positive attitude for the idea. Regarding some example how it has been done you can see [Zutilo](https://github.com/willsALMANJ/Zutilo). It has implemented different shortcuts for different things. For example, I extensively use the shortcut for renaming attachment.
Thanks!

**Comment by retorquere** [comment]
No worries.

Yeesh, I have *no* idea what's going on in the key capture code for Zutilo. I'll ask on the zotero-dev list, but I'm going to prioritize getting the rewrite behind me. It will take a while.

**Comment by retorquere** [comment]
From Will S:

> Zutilo has a mechanism for adding custom shortcuts. It is based on the old Keyconfig extension for Firefox. You can look at this file where I adapted Keyconfig for Zutilo:
>
> https://github.com/willsALMANJ/Zutilo/blob/master/addon/chrome/content/zutilo/keyconfig_adapted.js
>
> It does try to check that its shortcuts don't conflict with other registered shortcuts (XUL calls a shortcut a "key" or "keycode"). However, Zotero handles keypresses directly in ZoteroPane.js instead of registering shorcuts, so it doesnt check for conflicts with those. This general conflict detection was more useful in the Firefox version where more things could add shortcuts. You could add something to read the Zotero shortcut preferences to avoid conflicting with them as well.

**Comment by mijalche** [comment]
I do not know, but is it possible to add a custom shortcut in Zutilo that will actually refer to BBT and make the changes in BBT like pin BibTeX key?

**Comment by retorquere** [comment]
Sure, Zutilo can just call what I do:

* `Zotero.BetterBibTeX.KeyManager.pin('selected')` (pin key for selected references)
* `Zotero.BetterBibTeX.KeyManager.unpin('selected')` (unpin key for selected references)
* `Zotero.BetterBibTeX.KeyManager.refresh('selected', true)` (force-refresh key for selected references)

Other extensions can check for BBT's presence by testing for `Zotero.BetterBibTeX`; for safety it would be best to wait until the `Zotero.BetterBibTeX.ready` promise resolves.

**Comment by mijalche** [comment]
I think that will work best. And those three options will be added in Zutilo list of shortcuts so the user can define its own shortcuts.

**Comment by retorquere** [comment]
"will" as in "consider it done", or as in "it could technically be realized"?

**Comment by mijalche** [comment]
I was thinking in direction that it could be technically realised with least effort. I think that in this way you will not need to develop additional features within BBT and add UI for adding the shortcuts. The drawback is that then for the shortcuts there will be a dependance on Zutilo.

**Comment by retorquere** [comment]
I don't mind, as I despise UI work. But will the Zutilo author want to do this?

**Comment by mijalche** [comment]
If you decide that this the path that should be followed I will open issue at Zutilo and reference to this tread. However, on a long term maybe it is better to be within BBT. You make BBT so it is your call, what you suggest I will support and provide feedback in the development

**Comment by retorquere** [comment]
In the long term it is better for everybody if I leave the UI stuff to people more suited to it. Have you *seen* the BBT prefs UI? 😆

**Comment by retorquere** [comment]
Yep!

**Comment by mijalche** [comment]
issue opened at Zutilo https://github.com/willsALMANJ/Zutilo/issues/72

**Comment by retorquere** [comment]
implemented by Zutilo
