### ISSUE TITLE
pull export

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#756]

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4574](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4574.issue-756.xpi) ("@pe").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4575](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4575.issue-756.xpi) ("@pe").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4593](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4593.issue-756.xpi) ("fixes #756").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4594](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4594.master.xpi) ("fixes #756").
