### ISSUE TITLE
arXiv handling

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#762]

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4595](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4595.issue-762.xpi) ("fixes #762").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4596](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.28.4596.master.xpi) ("fixes #762").
