### ISSUE TITLE
Automatic export does not show on the list (though it works in background)

### ISSUE THREAD

**Issue by dbobak** [retorquere/zotero-better-bibtex#767]
Automatic export doesn't show on the export list. It works in the background, the export is done as I set it, but I just cannot see it on the list. 

ReportID: 282GSF7T
BBT version: 5.0.28.4598 (in a few earlier versions the bug existed too)
Zotero 5 on Windows 10 Pro 64 bit, Polish language version

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4613](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.29.4613.issue-767.xpi) ("website, caching").

**Comment by retorquere** [comment]
Can you try 4613?

**Comment by dbobak** [comment]
I just did and it's working now :)
Thank you!

**Comment by retorquere** [comment]
Super thanks for the fast feedback.

**Comment by dbobak** [comment]
The problem appeared again with 4848, in new clothes. Automatic export is invisible in the list, but is selectable (and can be released manually), as on the attached picture.
ReportID: MVV78499

![screen_1](https://user-images.githubusercontent.com/6285546/32982824-e321c658-cc8a-11e7-82f8-c68e057fdcab.PNG)

**Comment by retorquere** [comment]
It's really a different issue, but I see what's going wrong.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4855](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4855.issue-767.xpi) ("New translations zotero-better-bibtex.properties (French) (#800)").

**Comment by retorquere** [comment]
Try 4855

**Comment by dbobak** [comment]
Works perfectly now. Thanks!

**Comment by retorquere** [comment]
Alright, i'm closing a few more issues and then cutting a new release
