### ISSUE TITLE
Snapshot urls continue to be exported even after deletion.

### ISSUE THREAD

**Issue by JohnLukeBentley** [retorquere/zotero-better-bibtex#771]
Snapshot urls continue to be exported even after deletion.

Steps to reproduce:

1. Open Zotero.
2. In Firefox surf to http://www.abc.net.au/news/2017-11-09/conservatives-to-sponsor-alternative-same-sex-marriage-bill/9131826 (or Skip ahead to step 5 and use Report ID: 7F6B9KDH)
3. In Firefox click on the Zotero button (which will export with the "Save to Zotero (Embedded Metadata)" command).
4. In Zotero observe that the web page has been saved with a snapshot.
5. In Zotero click on the new record and export (Ctrl + Shift + C ... with Better Biblatex set).
7. Paste into an editor. Observe ...

    > @online{barbour_2017_conservative,
    >  author = {Barbour, political reporter Lucy},
    > ...
    > file = {Snapshot:C\:\\Users\\John\\Documents\\CustomData\\Direct\\Live\\Zotero\\storage\\YL92HK6A\\9131826.html:text/html},
    > ...

   That is, as expected a `file = {Snapshot` url exists.

8. In Zotero click on the record's triangle near the title to open up the snapshot record underneath.
9. On the snapshot record right click > Move Item to Trash ... . Click OK. Observe the snapshot has been deleted from Zotero.
10. Export again (Ctrl + Shift + C ... with Better Biblatex set).
11. Paste into your editor and observe the exported record is unchanged. Specifically, ...

    > file = {Snapshot:C\:\\Users\\John\\Documents\\CustomData\\Direct\\Live\\Zotero\\storage\\YL92HK6A\\9131826.html:text/html}

    ... remains, when it shouldn't.

In addition, for a record that had its snapshot removed: restarting Zotero doesn't remove the snapshot url on export.

I'm on Zotero 5.0.24. Firefox 57.0 (64bit). zotero-better-bibtex-5.0.31.4637.issue-590.xpi. Note this arouse while testing in the #590 branch.

**Comment by retorquere** [comment]
This is likely a cache invalidation problem, in turn likely caused by zotero not notifying parent references as changed when their children do.

I'm on the go right now, but could you shut down zotero, go into your zotero directory, subdirectory better-bibtex, remove cache.json, and retry the export (so not the removal, do that before)? If that gets you the correct output I'll have confirmation.

**Comment by JohnLukeBentley** [comment]
Yes deleting ...\Zotero\better-bibtex\cache.json and retrying the export did indeed produce the correct output (Snapshot url no longer exported).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4666](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.32.4666.issue-771.xpi) ("fixes #771").

**Comment by JohnLukeBentley** [comment]
That fixes it! :)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4667](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.32.4667.master.xpi) ("fixes #771").
