### ISSUE TITLE
copy-paste to Latex

### ISSUE THREAD

**Issue by raffam** [retorquere/zotero-better-bibtex#772]
I don't think the copy-paste feature works in current BBT version

When I do ctrl+c in zotero and ctrl+v in TexStudio the URL of the article is copied
When I drag the article with the mouse, a textual reference is copied

**Comment by retorquere** [comment]
Can you submit a debug log?

**Comment by raffam** [comment]
> 
> version => 5.0.24, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 5.0.24, extensions => ZotFile (5.0.5, extension), Zotero LibreOffice Integration (5.0.6.SA.5.0.24, extension), Zotero Word for Windows Integration (5.0.5.SA.5.0.24, extension), Zotero Better Bib(La)Tex (5.0.32, extension)
> 
> (4)(+0000000): SELECT collectionID FROM collections WHERE collectionID IN (SELECT collectionID FROM collectionItems WHERE itemID=?) [1098]
> 
> (4)(+0008940): SELECT collectionID FROM collections WHERE collectionID IN (SELECT collectionID FROM collectionItems WHERE itemID=?) [1098]
> 
> (3)(+0012093): mozSourceNode not set -- storing source node
> 
> (3)(+0000000): Dragging with format {"mode":"bibliography","contentType":"","id":"http://www.zotero.org/styles/chicago-note-bibliography","locale":""}

**Comment by retorquere** [comment]
I'd prefer a log submitted by `Help` -> `Report Better BibTeX Errors`.

**Comment by raffam** [comment]
ID: NXNGRPIF

**Comment by raffam** [comment]
is it okay?

**Comment by retorquere** [comment]
No, but that's not your fault; I'll make a change next week that will notify for this, but you'll need to select `Help` -> `Debug Output Logging` -> `Restart with Logging Enabled...` before submitting an error report, or it will be mostly empty.

**Comment by raffam** [comment]
ID: 676VYDLT

Is it ok now?

**Comment by retorquere** [comment]
yes

**Comment by retorquere** [comment]
There are seemingly unrelated errors in the logs, but I'd prefer to make sure. Can you restart and send another log?

**Comment by raffam** [comment]
report id R7KIWZC6

**Comment by retorquere** [comment]
It has the same error. Can you list the files and file sizes in your `C:\Users\raffa\Zotero\better-bibtex\` directory (after Zotero has been shut down)?

**Comment by raffam** [comment]
>  Directory of C:\Users\raffa\Zotero\better-bibtex

11-Nov-17  12:51    <DIR>          .
11-Nov-17  12:51    <DIR>          ..
11-Nov-17  12:51               988 cache.Better BibTeX Citation Key Quick Copy.json
11-Nov-17  12:51               940 cache.Better BibTeX.json
11-Nov-17  12:51               944 cache.Better CSL JSON.json
11-Nov-17  12:51               944 cache.Better CSL YAML.json
11-Nov-17  12:51               948 cache.BetterBibTeX JSON.json
11-Nov-17  12:51             4,335 cache.itemToExportFormat.json
11-Nov-17  12:51               597 cache.json
10-Jul-17  16:42           796,600 cache.json.1
10-Jul-17  16:42           796,600 cache.json.2
10-Jul-17  16:41           796,600 cache.json.3
10-Jul-17  16:41           796,600 cache.json.4
10-Jul-17  16:40           796,600 cache.json.5
10-Jul-17  16:44            20,464 db.json
09-Jul-17  19:50            20,463 db.json.1
09-Jul-17  16:44            20,271 db.json.2
09-Jul-17  16:44            20,274 db.json.3
09-Jul-17  16:44            20,271 db.json.4
09-Jul-17  16:44            20,274 db.json.5
              18 File(s)      4,114,713 bytes
               2 Dir(s)  421,961,502,720 bytes free

**Comment by retorquere** [comment]
That looks totally reasonable. I don't know why BBT would complain about the files missing. Can you try the following:

1. Close Zotero
2. Remove all those json files you just listed (don't worry, they're just cache files)
3. Start Zotero, choose "Restart with debugging enabled" from the Help menu
4. Send a new debug log

Sorry for all the rigmarole, but I don't like seeing errors relating to the DB load, even if they should be fairly harmless when it comes to loading the cache (you just wouldn't have cache persistence).

**Comment by retorquere** [comment]
I don't have Windows BTW -- is ctrl-c just the Zotero shortcut for `Preferences` -> `Advanced` -> `Shortcuts` -> `Copy Selected Items to Clipboard`? Because that shortcut just works for me.

Can you disable ZotFile, restart Zotero, and try again? Maybe there is an interplay between ZotFile and BBT that makes this happen.

**Comment by retorquere** [comment]
(it still works for me even with ZotFile installed, but I'd just like to check)

**Comment by raffam** [comment]
This is the report ID with zotfile disabled and .json files removes (but not *.json.*)
2N4UJEFX
why ctrl+c? i am just dragging with the mouse

**Comment by retorquere** [comment]
You can also remove the `.json` file.

Alright, the error is gone. Still doesn't work then? Then you can re-enable ZotFile.

Why `ctrl-c`? You mentioned that that's what's not working for you at https://github.com/retorquere/zotero-better-bibtex/issues/772#issue-272760767 .

**Comment by raffam** [comment]
ctrl+c and dragging with the mouse leads the same result
Anyway yes, edit-> copy is equivalent to ctrl+C in windows

**Comment by raffam** [comment]
i have removed the .json file. I did not remove the .json.1 file, .json.2 and so on

**Comment by retorquere** [comment]
Wait, I don't follow. You're not talking about the quick-copy shortcut keys, but just regular ctrl-c. I don't know how that's supposed to work, Edit-Copy is greyed out for me whether I have BBT or not.

Do you know of any documentation on the edit-copy behavior? I could only find [this](https://www.zotero.org/support/kb/keyboard_shortcuts) but that only talks about notes for `ctrl+c`.

Jou can remove *all* files in that directory. They're holdovers from BBT4.

**Comment by raffam** [comment]
Sorry. Edit->Copy Bibliography, which equals ctrl+shift+c, gives the same result as dragging with the mouse. That result is a full citation and not a latex \parencite{}
Removing all files did not solve the problem

**Comment by retorquere** [comment]
What did you set the quick-copy translator to in `Preferences`/`Export`/`Default format`?

**Comment by raffam** [comment]
that's it, now it works :) it looks a lot to find this out XD

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#latex-command
