### ISSUE TITLE
New blog post does not autoselect the new element

### ISSUE THREAD

**Issue by raffam** [retorquere/zotero-better-bibtex#774]
When using BBL,
File->new item->blog post does not autoselect the new element.
Instead, if an element is currently selected, its title texbox gets edited

If BBL is disabled, it works

Report ID: QQ2JHLCC

**Comment by retorquere** [comment]
I can reproduce this but there is no error in the logs, and I have no idea how I'm interfering with Zotero. I've posted a message to the [dev group](https://groups.google.com/forum/#!topic/zotero-dev/yGP4uJQCrMc) for assistance.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4676](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.33.4676.issue-774.xpi) ("fixes #774").

**Comment by retorquere** [comment]
Try 4676

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4680](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.33.4680.issue-774.xpi) ("cleanup").

**Comment by raffam** [comment]
Perfect. It seems to also have fixed [this](https://forums.zotero.org/discussion/68592/cannot-save-website?new=1)

**Comment by retorquere** [comment]
Alright, that's a happy coincidence then. You can just keep using this version, .34 which will drop soon is just a retagged 4680.
