### ISSUE TITLE
ErrorReport: warn when Zotero.Debug.enabled is false

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#776]
Error reports need to be submitted after "restart with debug logging"

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4664](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.32.4664.issue-776.xpi) ("fixes #776").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4665](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.32.4665.master.xpi) ("fixes #776").
