### ISSUE TITLE
Custom Bibtex export

### ISSUE THREAD

**Issue by Emic37** [retorquere/zotero-better-bibtex#777]
Hi,

The Better BibTex default behavior seems be to export Encyclopedia Article Item (Zotero) as misc item (BibTex). I would prefer the Encyclopedia Article item is exported as BibTex article item. Is it possible to make that with a postscript ? If yes, please say me how to make that ?
Thanks in advance.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4670](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.32.4670.issue-777.xpi) ("fixes #777").

**Comment by retorquere** [comment]
You can do it using this postscript:

```
if (Translator.BetterBibTeX) {
   if (this.item.itemType == 'encyclopediaArticle') this.referencetype = 'article'
}
```

but this was really just an oversight on my part -- try 4670 without the postscript.

**Comment by Emic37** [comment]
Thank you very much. It's working with test build 4670 !

**Comment by retorquere** [comment]
Alright, you can keep using this, it's the same as .33 which will be released in a few minutes. Zotero will upgrade in a day or so (don't know what schedule it's set to), or you can force the upgrade from the addons screen.

**Comment by Emic37** [comment]
Ok thank you.
