### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by Emic37** [retorquere/zotero-better-bibtex#779]
When I use Zotero in english, I have no problem with Better BibTex. But, when I configure Zotero in French, all category on the list of items are enabled after restart and Better BibTex seems disabled : all options or preferences of Better BibTex are not displayed and I can't use it of course.
After to configure again Zotero in english, I reactive Better BibTex and everything is working again. :/ Sorry for this problem... :/

**Comment by retorquere** [comment]
I need to get a better handle on the translation process. I think it's because I've added new doc strings.

**Comment by retorquere** [comment]
I've set up Crowdin for translations (I think I've done it right this time); can you take a look at https://crowdin.com/project/zotero-better-bibtex ?

**Comment by Emic37** [comment]
Ok, super ! I have just looked at Crowdin and I added the late missing translation.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4721](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4721.issue-779.xpi) ("fr").

**Comment by retorquere** [comment]
Can you try 4721?

**Comment by Emic37** [comment]
There is no bug with test build 4721. Better BibTex work fine but no french.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4724](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4724.issue-779.xpi) ("tr").

**Comment by retorquere** [comment]
Damn. I don't really know what to do about this. I've posted on the Zotero dev group, but I'll have to wait and see if someone knows what's going on -- the UI part of BBT is a bit of a mystery to me, cobbled together from code samples.

**Comment by Emic37** [comment]
No problem. It's not urgent. Thanks for your work.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4735](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4735.issue-779.xpi) ("New translations zotero-better-bibtex.dtd (French) (#785)").

**Comment by Emic37** [comment]
Ok super ! Thanks !

**Comment by retorquere** [comment]
Does it work for you? It does for me.

**Comment by Emic37** [comment]
Yes ! It works very well ! But French is so longer than English 🙄 and there are some display default. I'll looking for reduce the length of some translations...

**Comment by retorquere** [comment]
OK, but the base problem is solved. I'v scheduled a release of .37 that has the current translations included -- when new translations roll in, I'll just re-release.

**Comment by Emic37** [comment]
Yes,  it does. Thank you very much !

**Comment by retorquere** [comment]
There are still English strings hard-coded into the UI that are not loaded from the dtd. If you find some of those, let me know, and I'll set up a way to have those translated too.

**Comment by Emic37** [comment]
Indeed, I noted some strings : 
- Better BibTex : Waiting for Zotero database...
- Better BibTex : Starting serialisation cache...
- Better BibTex : Installing bundled translators...
- Keep updated
- Better BibTex Citation Key Quick Copy

There is too the description of the extension displayed in Zotero add-ons manager. 
Then, "Automatic export" string is used in two places but it would be better with two different translations.

**Comment by Emic37** [comment]
And a suggestion for "Warn me when changing citation keys in bulk" string, which is not very understandable : 

![sans titre](https://user-images.githubusercontent.com/2921424/32830070-58578136-c9f4-11e7-99c0-8f728e6252a5.jpeg)
If you can make something like that, it would be perfect. 

 In french, we can translate this string like that : 
" Lors d'un changement par lot, m'avertir si cela concerne plus de (field) clés de citation"

...which maybe means in english something like that : 
"Before bulk change, warn me if this concerns more  than (field) citekeys"

But it's a detail and maybe you have lot of more important things to fix.
I any case, I corrected translation on Crowdin to make it shorter.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4757](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4757.issue-779.xpi) ("return libraryID, not unparsed lib").

**Comment by retorquere** [comment]
> Indeed, I noted some strings : 

Most are now available in Crowdin for translation. The exceptions are

> - Keep updated

because Zotero does not (realistically) allow these to be translated, and

> Better BibTex Citation Key Quick Copy

because the translators are named after their filename on disk, and having this localized would be a nightmare.

> There is too the description of the extension displayed in Zotero add-ons manager. 

Can't localize this, it's a fixed build-time string. Firefox doesn't allow for dynamic strings here.

> Then, "Automatic export" string is used in two places but it would be better with two different translations.

Done

> And a suggestion for "Warn me when changing citation keys in bulk" string, which is not very understandable : 

![sans titre](https://user-images.githubusercontent.com/2921424/32830070-58578136-c9f4-11e7-99c0-8f728e6252a5.jpeg)

> If you can make something like that, it would be perfect. 

That's possible, but not now.

> In french, we can translate this string like that : " Lors d'un changement par lot, m'avertir si cela concerne plus de (field) clés de citation"

If there's a way to do that without embedding the edit field but keeping it at the end that would be easier.

**Comment by retorquere** [comment]
One mistake -- the plugin name *can* be localized. I'll look at that this weekend

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4771](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4771.issue-779.xpi) ("New Crowdin translations (#788)\n\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4773](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4773.issue-779.xpi) ("tr").

**Comment by Emic37** [comment]
Ok. Thank you. I translated new strings in Crowdin and I'll cogitate again to find the better translation of "Warn me when changing citation keys in bulk" with edit field at the end.

**Comment by Emic37** [comment]
After many attempts, I just updated the translation for "Warn me when changing citation keys in bulk" and some strings which were too long. I also updated some strings following the syntax of Zotero for better integration of Better BibTex in Zotero in french. 

On the over hand, I'm sorry but I don't find two different strings for "Automatic export" in Crowdin. Maybe I misinterpreted your "Done"... xD

Finally all is good now except for "Keep updated". Too bad that Zotero makes things so difficult. It's the only "important" string which is not translated. 

In any case, I hope now this translation will help some french users to adopt easier your add-on Better BibTex.

**Comment by retorquere** [comment]
The duplicate strings are hidden by default. They should be at the end, in grey. If not, I'll have to twiddle some more settings. Crowdin takes some getting used to.

There are some things I can try WRT "Keep updated" but please don't tempt me until the weekend :(

**Comment by retorquere** [comment]
OK, can you see if you can find the duplicate term now?

**Comment by Emic37** [comment]
It works. Thank. 
And for "Keep updated", I will not say another word ! xD Seriously, it's not very important, take your time.

**Comment by retorquere** [comment]
Moar strings

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4794](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.38.4794.issue-779.xpi) ("Merge branch 'master' into 779").

**Comment by retorquere** [comment]
More specifically, I think I have a solution for "keep updated"

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4819](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.41.4819.l10n_master.xpi) ("release").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4823](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.41.4823.l10n_master.xpi) ("New Crowdin translations (#796)\n\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)").

**Comment by Emic37** [comment]
Hello, good idea to replace chip by drop down menu. :) The zotero's syntax in this case seems be not use colon and capital. I'll update translation.
Super for "Keep updated". And thanks for the auto-build when there are new strings.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4825](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.41.4825.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4868](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4868.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French) (#802)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4881](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4881.l10n_master.xpi) ("ASCII is a bit techy").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4950](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4950.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French) (#821)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5024](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5024.l10n_master.xpi) ("Merge branch '690'").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5025](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5025.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5033](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5033.l10n_master.xpi) ("New Crowdin translations (#831)\n\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5034](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5034.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5084](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.51.5084.l10n_master.xpi) ("separate select-link with newlines").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5093](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.51.5093.l10n_master.xpi) ("correct grammar, based on spoken sound (#840)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5111](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.54.5111.l10n_master.xpi) ("Merge branch '834'").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5112](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.54.5112.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5150](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.58.5150.l10n_master.xpi) ("tr").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5178](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.60.5178.l10n_master.xpi) ("more explanation").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.123.6305.l10n_master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.123.6305.l10n_master.xpi) ("ISSUE_TEMPLATE.md").

**Comment by Emic37** [comment]
Translation updated :)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6587.l10n_master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6587.l10n_master.xpi) ("New translations zotero-better-bibtex.properties (French) (#963)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6602.l10n_master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6602.l10n_master.xpi) ("New Crowdin translations (#964)\n\n* New translations zotero-better-bibtex.properties (French)\r\n\r\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6603.l10n_master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6603.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (Dutch)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6621.l10n_master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6621.l10n_master.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6620.l10n_master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6620.l10n_master.xpi) ("collected notes").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.147.7080](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.147.7080.xpi) ("Move item context menu to submenu (#990)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.148.7148](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.148.7148.xpi) ("Move journal abbreviations to Export tab (#995)\n\n* Move journal abbreviations to Export tab\r\n\r\nIt conceptually fits there well. I tried having a separator between the checkbox and the \"Abbreviation style:\" label and listbox, but thought that this looked better.\r\n\r\n* Additional tweaks to preferences\r\n\r\n- Reduce rows shown for Abbreviation Style in Juris-M, the BBT pane the same height as the Zotero Cite pane\r\n- Hide column picker on the autoExport tree\r\n\r\n* Swtich abbreviation style to menulist\r\n\r\n* Fix stretching of preference panes").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7480](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7480.xpi) ("error report version").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7481](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7481.xpi) ("New translations zotero-better-bibtex.properties (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.164.7526](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.164.7526.xpi) ("fix nightly").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7607](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7607.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7606](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7606.xpi) ("ncu").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7608](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7608.xpi) ("New translations zotero-better-bibtex.properties (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.166.7609](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.166.7609.xpi) ("New translations zotero-better-bibtex.dtd (German)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.185.8023](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.185.8023.xpi) ("travis").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.190.2638](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.190.2638.xpi) ("New translations zotero-better-bibtex.dtd (French)").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.190.2640](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.190.2640.xpi) ("New translations zotero-better-bibtex.dtd (French)").
