### ISSUE TITLE
Backward compatibility for export of main library via localhost

### ISSUE THREAD

**Issue by crsh** [retorquere/zotero-better-bibtex#784]
Hi, thanks for all the hard work on this plugin. I'm the developer of an [R package](https://github.com/crsh/citr) that provides an Addin to the R Studio IDE to connect to Zotero via the localhost exports of the Better BibLaTeX plugin.

Until recently I accessed the library via `http://localhost:23119/better-bibtex/library?library.biblatex`. With the latest release of Better BibLaTeX that URL seems to load indefinitely. However, I can access the library via `http://localhost:23119/better-bibtex/library?/1/library.biblatex`. I would simply update the changed URL but this would break backward compatibility. I wonder whether this is intended behavior. If so is it possible to query the Zotero/Better BibLaTeX version via localhost so I can implement version dependent behavior?

P.S.: I know this is unrelated to the above issue, but I've now that I'm here and having been wondering about this for a while, is it possible to get a list of the shared libraries via localhost?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4728](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4728.issue-784.xpi) ("fixes #784").

**Comment by retorquere** [comment]
Try 4728.

There currently isn't a way to request shared libraries, but it shouldn't be too hard. I'd appreciate it if you could open a separate issue for that.

**Comment by crsh** [comment]
Great, this seems to have done it. Thank you!

**Comment by retorquere** [comment]
No worries, thanks for reporting.

Minor point: for future issues, I'd prefer it if you (or others) not close the issue (unless you opened one by mistake and expect no action from me). The open issue also serves as a reminder to me that I still need to merge this fix into the main release, or it would be lost again once I put out a new release. Issues are closed automatically when I do that. I've done the merge, so the issue can remain closed now.
