### ISSUE TITLE
Additional information about Zotero libraries via localhost

### ISSUE THREAD

**Issue by crsh** [retorquere/zotero-better-bibtex#787]
Hi again. With reference to my other [recent issue](#784) it would be very useful for my integration with RStudio if Better BibLaTeX would provide additional information about the Zotero library:

1. A list of shared libraries via localhost. I currently can access the a users local library via `http://localhost:23119/better-bibtex/library?/1/library.biblatex` but it seems I need to know the ID of shared libraries in order to access them. I have been unable to find a programmatic way to obtain the IDs.
2. For backward compatibility it would be helpful to know the version number of Zotero and/or Better BibLaTeX.

I suppose a list of such information in YAML or JSON format would work well and is flexible for future additions.

**Comment by retorquere** [comment]
I'd actually prefer using JSON-RPC for such things. It's not hard to implement and if we're really talking about more than fetching stuff at some point it'd be a better fit I think. If not, certainly JSON, which is much faster to produce in javascript than YAML.

**Comment by retorquere** [comment]
Thoughts?

**Comment by crsh** [comment]
I'm no expert on this. So far I had just hoped for a page that provides fixed information formatted as a JSON list. Being able to query the database would open up many more possibilities. JSON-RPC sounds good to me but given my sketchy knowledge about alternative approaches I'm probably the wrong person to debate possible advantages and disadvantages with you. Sorry. If JSON is easier to implement, than that would certainly satisfy all my needs.

**Comment by retorquere** [comment]
I strongly prefer it; for one thing, it allows better ways for me to tell you what went wrong if something does go wrong. It's more a question of whether you think you can do it on your end; it's [not much harder](http://www.jsonrpc.org/specification#examples) than doing an HTTP-get, but it's not exactly the same. POST a JSON string, get a JSON string back, instead of GET and URL, get a JSON string back.

**Comment by crsh** [comment]
Sounds reasonable and I think I'll be able to work with JSON-RPC.

**Comment by retorquere** [comment]
This will work against 4813:

```
curl http://localhost:23119/better-bibtex/scholmd -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "libraries" }'
```

We can talk about the namespace on the url (something like http://localhost:23119/better-bibtex/scholmd/rmarkdown or http://localhost:23119/better-bibtex/rmarkdown or something else entirely) or the function name (method could be something like `rmarkdown.libraries` if you prefer that).

**Comment by retorquere** [comment]
So...

**Comment by retorquere** [comment]
still interested?

**Comment by crsh** [comment]
Hey, sorry, I was busy with other stuff. I just tried using the latest release and this looks great. This enables me to access all the information I currently need:

~~~r
library("httr")
bb_response <- POST(
  "http://localhost:23119/better-bibtex/scholmd"
  , add_headers("Content-Type" = "application/json")
  , body = '{"jsonrpc": "2.0", "method": "libraries" }'
  , encode = "json"
)

headers(bb_response)$`x-zotero-version`
~~~

~~~r
# [1] "5.0.23"
~~~

~~~r
do.call(rbind, content(bb_response)$result)
~~~

~~~r
#      id      name            
# [1,] 1       "My Library"    
# [2,] 2774014 "CI"            
# [3,] 2774016 "falco"         
# [4,] 1537540 "methexp"       
# [5,] 1746248 "methexp_public"
~~~

I'm happy with the method name `libraries`. I think this not limited to R Markdown, so I don't think "rmarkdown" needs to be in the title. `scholmd` stands for scholarly markdown I suppose? Again, from what I understand this is a general interface to access information, so I think the naming could be more generic and depends on in what other methods could be added...

**Comment by retorquere** [comment]
Reasonable. I could just stick it under `/better-bibtex/json-rpc` and be done with it. I'm torn right now between

* just adding this and seeing what comes up later, 
* having it structured after the [zotero web api](https://www.zotero.org/support/dev/web_api/v3/start), which means the method call would be `groups` (and would not include `My Library`), or
* partially implementing that web api, but I'd have to figure out what the appropriate response is to those calls -- I don't see the responses documented there.

**Comment by crsh** [comment]
Intuitively, I'd go with the structure of the Web API. Since, the ID of `My Library` can be expected to be 1, if I'm not mistaken, querying the group IDs should be sufficient.

**Comment by retorquere** [comment]
In that case I'd want to host it under `/better-bibtex/api`, and the method would be `user.groups()` (really mimicking the api would make that `users`, but locally, there's always only a single user) .  If I'd follow the API structure, `user.X` would be the analogue to `/users/<userID>/X`, but would always just query the users' personal library; `groups.X(groupID, ...)` (or perhaps `groups.X({ groupID: groupID, ...})` if you prefer named parameters for clarity) would be analogous to `/groups/<groupID>/X`. `groups.<groupID>.X(...)` is also possible.

I've looked at the API, but I'd have to reverse-engineer the output since I can find the docs. I'd really rather not do that. Following the API for structure as above gives us some, well, structure, but it's easier for me to do.

**Comment by retorquere** [comment]
I've probed the public API a bit and while I think it's probably not as hard as I thought it'd be, it can't be done 100% (not everything makes sense for local access, not all data is available), but I'd have to stick a `?` in front of the URLs, so existing clients won't be able to use it as-is, and the responses carry a lot of duplicate data, which strikes me as something they'll want to change at some point anyhow.

**Comment by crsh** [comment]
I see. If I understand correctly, this would break backward compatibility, which I'd try to avoid if possible. So, if I interpret the situation correctly the three options all have some pros and cons.

1. Providing the JSON-RPC in it's current form and building as new things come up is straight forward but may turn out to be unwieldy and would require more documentation because developers cannot rely on known structures.
2. Using the Web API structure but without mimicking the response would structure the interface but may violate expectations of developers who have used the API in other contexts
3. Partially implementing the Web API including response structure would break backward compatibility and may require the most maintenance effort.

Unless I misunderstand something, I think it may be worth considering to go with 1., place it at `/better-bibtex/json-rpc` and see what other methods may be requested (if any). If lots of other usecases come up you could still resort to either 2. or 3. later and place them at `/better-bibtex/api` as you suggested.

**Comment by retorquere** [comment]
It wouldn't break backward compatibility; implementing the web api would allow existing clients of the public web-api to work with the BBT-supplied implementation with some minimal changes to those clients. There could be some benefit to that... although really this is more something the Zotero team would be well-positioned to do. I have to keep reminding myself that BBT is in the BibTeX business, and that stuff I add ought to relate to it somehow.

> Providing the JSON-RPC in it's current form and building as new things come up is straight forward but may turn out to be unwieldy and would require more documentation because developers cannot rely on known structures.

Yes. I don't excel at documentation, exactly, so if I can copy some documented behavior, if only roughly, everyone comes out ahead. It's why I went with the JabRef patterns for the citekeys for example.

> Using the Web API structure but without mimicking the response would structure the interface but may violate expectations of developers who have used the API in other contexts

Possible, but at least there would be structure. 

> Partially implementing the Web API including response structure would break backward compatibility and may require the most maintenance effort.

Not backwards compatibility (there is nothing back there right now), but the protocol is pretty chatty, and given that I can't find any docs, I don't know what to aim for other than what I happen to find probing the public web api.

> Unless I misunderstand something, I think it may be worth considering to go with 1., place it at `/better-bibtex/json-rpc` and see what other methods may be requested (if any). If lots of other usecases come up you could still resort to either 2. or 3. later and place them at `/better-bibtex/api` as you suggested.

The downside to that is that would leave me with two APIs to maintain. Deprecating old APIs is painful, someone is bound to end up with some client no longer being updated expecting the older protocol to be in place. 

I'm going to go with 2, sticking it under `/json-rpc`, keeping to the structure of the web-api where it makes sense, and deviating where necessary. I'll leave it to the Zotero team to do a local implementation of the web api.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4955](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4955.issue-787.xpi) ("fixes #787").

**Comment by retorquere** [comment]
Alright, 4955 has `user.groups` on `/better-bibtex/json-rpc`. If you can (re)verify this works, I'll merge this into the next release.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4972.issue-787.xpi) ("Merge branch 'master' into 787").

**Comment by crsh** [comment]
Hey, thanks for the test build. Works like a charm.

~~~r
library("httr")
bb_response <- POST(
  "http://localhost:23119/better-bibtex/json-rpc"
  , add_headers("Content-Type" = "application/json")
  , body = '{"jsonrpc": "2.0", "method": "user.groups" }'
  , encode = "json"
)

headers(bb_response)$`x-zotero-version`
~~~~
~~~r
# [1] "5.0.23"
~~~~
~~~r
do.call(rbind, content(bb_response)$result)
~~~
~~~r
#      id name              
# [1,] 1  "Meine Bibliothek"
# [2,] 5  "CI"              
# [3,] 7  "falco"           
# [4,] 3  "methexp"         
# [5,] 4  "methexp_public" 
~~~
