### ISSUE TITLE
quickCopyMode option is not respected in Better BibTeX Citation Key Quick copy

### ISSUE THREAD

**Issue by egh** [retorquere/zotero-better-bibtex#789]
I am updating zotxt for zotero 5 and ran into the following issue.

## Steps to reproduce:

- Run the following code to export using the Quick copy export:

```
function myExport (items, translatorId) {
    let callback = function (resolve, reject) {
        let translation = new Zotero.Translate.Export();
        translation.setItems(items);
        translation.setTranslator(translatorId);
        /* I don't understand why Zotero still has `setHandler` now that we are in
         * promise-land, but OK */
        translation.setHandler("done", function (obj, worked) {
            if (worked) {
                Zotero.debug(obj.string);
                resolve(obj.string);
            } else {
                reject();
            }
        });
        if (translatorId === 'a515a220-6fef-45ea-9842-8025dfebcc8f') {
            /* This isn't working */
            translation.setDisplayOptions({quickCopyMode: 'pandoc'});
        }
        translation.translate();
    };
    let promise = new Promise(callback);
    return promise;
}
myExport(items, 'a515a220-6fef-45ea-9842-8025dfebcc8f'); // UUID for Better BibTeX quick copy
```
## Expected result:
- `@DoeArticle2006` is the exported content

## Actual result
- `\cite{DoeArticle2006}`

I monkey-patched the `Better BibTeX Citation Key Quick Copy.js` file in `translators/` as follows:
```
--- "Better BibTeX Citation Key Quick Copy.js"	2017-11-15 08:43:10.931117234 -0800
+++ "/home/egh/Better BibTeX Citation Key Quick Copy.js.orig"	2017-11-15 08:41:39.668714900 -0800
@@ -27,7 +27,7 @@
     if (stage == 'detectImport') {
       this.options = {}
     } else {
-      for (var key in this.options) {
+      for (var key in this.preferences) {
         this.options[key] = Zotero.getOption(key)
       }
       // special handling
```

And this fixed the issue, but I'm not sure if this is a correct solution, or how to file a PR to achieve this.

Thank you!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4774](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4774.issue-789.xpi) ("fixes #789").

**Comment by retorquere** [comment]
BBT translators now need to be explicit about the config options they sneak in -- I forgot to add this one to QC.

**Comment by egh** [comment]
Thanks for the quick response! That seems to fix the issue for me.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4795](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.38.4795.issue-789.xpi) ("Merge branch 'master' of github.com:retorquere/zotero-better-bibtex").
