### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by dbdennis** [retorquere/zotero-better-bibtex#795]
A newbie to github and following a project, please excuse me if this is an inappropriate way to post something other than an issue.  

I just want to say thank you to everyone involved with updating this project over the last months.  It is an important tool and I very much appreciate the work that went into keeping it going despite the Zotero transition.

**Comment by retorquere** [comment]
"Everyone" is me :rofl: but thanks

**Comment by dbdennis** [comment]
I get it! Hat's off to "Mr. Everyone"!  All best!
