### ISSUE TITLE
Citekey search integration

### ISSUE THREAD

**Issue by tmchartrand** [retorquere/zotero-better-bibtex#798]
Debug ID: CPLW6TPB
To reproduce, make a new empty collection and select it, change the search bar to search "All fields and tags" or "everything", and enter a simple search term. The empty list of items will populate with results from other collections (although not the entire library it seems).

It's not at all obvious to me why this is related to BBT, but it goes away if I disable the extension.

**Comment by retorquere** [comment]
Yeah, and I see why this happens. Damn. I'm not sure there's a way to fix this. Certainly not a quicky-fix.

**Comment by tmchartrand** [comment]
Hmm, well Advanced Search at least works as a workaround, although it's not the most convenient.

**Comment by retorquere** [comment]
I'm disabling citekey search until I've figured out (whether there is) a way to do this. Zotero search doesn't really lend itself to being extended. Thought I had found a way, but that turned out to be wrong.

**Comment by retorquere** [comment]
There's no way to hook into the search right now. Shame.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6176](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6176.xpi) ("citekey search")

Install in Zotero by downloading [test build 5.2.18.6176](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6176.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I think this works.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6177](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6177.xpi) ("also search pane")

Install in Zotero by downloading [test build 5.2.18.6177](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6177.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6179](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6179.xpi) ("auto-add citekey in search only for quicksearch")

Install in Zotero by downloading [test build 5.2.18.6179](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6179.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.18.6180](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6180.xpi) ("return localized name")

Install in Zotero by downloading [test build 5.2.18.6180](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.18.6180.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
