### ISSUE TITLE
Citekey Skipword in AuthorsAlpha removing AuthorsAlpha.

### ISSUE THREAD

**Issue by Niklas123Niklas** [retorquere/zotero-better-bibtex#804]
Hi,

I found a maybe-bug for generation of citekeys. I got the case that the author of the paper is: "The Gene...".
My citekey geneartion is [authorsAlpha][year]. In this case, I get the citekey The2017. 
To circumvent this, I tried [authorsAlpha:skipwords][year] as pattern, but the resulting key is 2017 instead of Gen2017. Without "the" in the author field, it is working normal. The Bug report number is 9BJXFMZ2.

**Comment by retorquere** [comment]
Can you right-click that reference and send a new debug report from that menu?

**Comment by retorquere** [comment]
I really can't do much without the actual reference. Right-clicking that reference and selecting "Send BBT error report" from that menu will get me the reference, and your BBT settings.

**Comment by Niklas123Niklas** [comment]
Hey,
here you go: H45MEBPE
Is it enough?

**Comment by retorquere** [comment]
OK, I see what's going on now. `authorsAlpha` takes the first 3 letters of the author if there is only one (which there is, in your case); that in your case happens to be `The`, and `the` is in the default skipwords list. So you end up with nothing.

I think in this case there's no good pattern to use; I would suggest just manually pinning the key to what you want by adding `bibtex: Gen2017` to the `extra` field.

**Comment by retorquere** [comment]
For the auto-export issue, please upgrade to 5.0.43 first; if the problem persists, please open a new issue on github (one problem-one issue makes issue handling manageable for me).

**Comment by Niklas123Niklas** [comment]
Wouldn´t it be a good idea to take the next word? I just got a new citation calling "The ENCODE Consortium", and for me skipping "the" and use the next word is the expected behavior of skipwords. 

@auto-export issue: I will have a look on this and do as you said.

**Comment by retorquere** [comment]
Doing that would change the semantics of authAlpha. See the section on the [Auth functions](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#functions) (in particular the capitalized versions), the section on the  the [filters](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#filters) and the `Usage note` below it; the whitespace-dependent filters are only effective for the capitalized `Auth...` functions and direct field access (see the table on that same page)

**Comment by retorquere** [comment]
It is *not* ignoring the skipwords; [authorsAlpha](http://help.jabref.org/en/BibtexKeyPatterns) simply doesn't generate `The` for more than one author; it generates `TX`, and `TX` is not in skipwords; in `[authorsAlpha:skipwords]` means `do authorsAlpha, then apply skipwords`, not `apply skipwords, then authorsAlpa`. You may want to play around with `Authors` (note the caps, and see the [functions](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#functions) explanation of the capitalized `Auth...` functions), but both `authorsAlpha` and `skipwords` are doing what they are designed to do here, even if that does not get you the desired output.

`[Authors:skipwords:select,1,1]` may get you closer, but the key generator is meant as a convenience, not a 100% solution for all cases; this is why key-pinning is available. If you simply add `bibtex: Gen2017` to the `extra` field, the problem goes away.

**Comment by retorquere** [comment]
Is there anything else I can do for you?

**Comment by Niklas123Niklas** [comment]
Hey,

I see the Problem. First the citekey is generated and then it gets filtered. So I will pin that key and remain with this knowledge. So far everything works perfectly. Thank you for the great effort in rewriting better bibtex for Z5!

**Comment by retorquere** [comment]
Exactly. The commands are executed in order. You can get super fancy with the capitalized fields, but I generally don't recommend micro-managing the process that way; in some sense I'm sorry I added more than the JabRef functions.
