### ISSUE TITLE
Enhancing CAYW picker ala Papers3

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#807]
https://forums.zotero.org/discussion/68793/feature-request-magic-citations-as-in-papers

The Papers3 app has a similar citation picker as BBT. In addition to inserting citekeys, it can also insert formatted references and show the attachment for an item. The use case for inserting a formatted citation is if you are working in, say, an email client or web browser and want to paste a reference to article without having to switch to Zotero, search, and use Quick Copy.

Would it be possible to add an option to insert formatted references for a specified style (or copy them to the clipboard) to the CAYW picker? Does Does the CAYW picker include the Show in My Library button? If not, could that also be added?

**Comment by retorquere** [comment]
I'd prefer separate issues for separate requests; the part that starts with `Does Does the CAYW picker include` is very different from adding a new CAYW format. But if you mean "can that UI be added if it is missing" then the answer is "no". If you mean something else, please open a separate issue so #807 can concentrate on adding a new CAYW format.

WRT to #807, yes, that can be done.

**Comment by retorquere** [comment]
The formatted text, that would be plaintext? HTML? Markdown?

**Comment by retorquere** [comment]
Oh with "Show in My Library" you mean "Open in my library"? Yes, that's still there -- I don't touch the picker, I just pop it up as-is, and grab the results, but between those two I just let Zotero do whatever it does there.

**Comment by bwiernik** [comment]
Formatted text as either plain text or HTML would probably be good (Zotero Quick Copy has both options) perhaps you could grab the Zotero setting for that?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4904](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.43.4904.issue-807.xpi) ("Update ISSUE_TEMPLATE.md").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4905](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.43.4905.issue-807.xpi) ("formatted-citations").

**Comment by bwiernik** [comment]
Great. I'll check it out. What is the command to call for a formatted reference? And does it just use the Zotero Quick Copy setting?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4906](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.43.4906.issue-807.xpi) ("formatted-").

**Comment by retorquere** [comment]
Better try 4906. I've updated the [wiki](https://github.com/retorquere/zotero-better-bibtex/wiki/Cite-as-you-Write) with the new formats, even if they're only in 4906 right now.

**Comment by retorquere** [comment]
Yes, it uses the Zotero Quick Copy setting to choose the style -- it will complain if it's not set to a citation style.

**Comment by bwiernik** [comment]
Seems to be working great!

**Comment by retorquere** [comment]
Alright, .45 should drop in a few minutes which has this.

**Comment by bwiernik** [comment]
Is .45 missing the packaged .xpi?

**Comment by retorquere** [comment]
Yes, yes it was, because the build failed. .46 will drop in a few minutes.
