### ISSUE TITLE
CAYW: BBT outputs malformed Scannable-cite IDs

### ISSUE THREAD

**Issue by vtcarlino** [retorquere/zotero-better-bibtex#808]
Hi, 

I have an issue with CAYW, using the Scannable-cite format. BBT now adds the document's title in the Scannable Cite format whereas it shouldn't. Here's an example:

The following URL `http://localhost:23119/better-bibtex/cayw?format=scannable-cite` returns `{ | Akrich, et al., Sociologie de la traduction: textes fondateurs, 2006 | | | zu0:TJVCIMFC }`.

BBT adds the title of the document ("Sociologie de la traduction ...") while it shouldn't. As a result, I have to remove manually the title in order to scan my ODT files... The output should be: `{ | Akrich, et al., 2006 | | | zu0:TJVCIMFC }`. 

Any idea on how to bring it back to normal?

Thank you

**Comment by retorquere** [comment]
1. The citation scanner is supposed to ignore the text in the first field. You'll want to report that at the [citation scanner project](https://github.com/Juris-M/zotero-odf-scan-plugin).
2. If you export that reference using the Scannable Cite exporter, what text do you get?

**Comment by retorquere** [comment]
Can you also right-click that reference and submit a BBT error report?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4899](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.43.4899.issue-808.xpi) ("scannable-cite").

**Comment by retorquere** [comment]
The scan being broken was more likely being caused by BBT malforming the ID at the end. BBT now uses (in 4899) the scannable cite translator itself to format the citation. This does mean that the ODF scanner plugin must be installed, or you must drop the Scannable Cite translator into the translators directory yourself.

Would appreciate you trying 4899 and letting me know how it fares.

**Comment by vtcarlino** [comment]
I tried 4899 and things get worse. I am given this output: `CAYW failed: Error: Expected zu:0:VK7PPZSP, found zu:966903:VK7PPZSP
Scannable-cite@chrome://zotero-better-bibtex/content/common.js:79277:23`

For some references, the output is completely blank. I submitted a BBT error report (ID 7G5EE3IU).

I get the right output using Scannable Cite as quick export format: `{ | McQuail, 2010 | | |zu:966903:VK7PPZSP}`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4907](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.43.4907.issue-808.xpi) ("Zotero uses different item urls internally than it sends to the translators...").

**Comment by retorquere** [comment]
4907 should be better.

**Comment by vtcarlino** [comment]
It is! Thanks a lot 👍

**Comment by retorquere** [comment]
Cool. I'll fold that into a new release.

**Comment by marcelpelz** [comment]
I have a problem, when i want to cite two sources at once:

CAYW failed: Error: Expected zu:2996967:EAP2DCWP, found zu:2996967:RRAIQIWZ
Scannable-cite@chrome://zotero-better-bibtex/content/common.js:79391:23

With the quick export feature everything is fine.

**Comment by retorquere** [comment]
Could you open a separate issue for this? It's a different problem.
