### ISSUE TITLE
'Keep updated' option in auto-export not be presented.

### ISSUE THREAD

**Issue by hankook** [retorquere/zotero-better-bibtex#809]
I'm using latest version of Zotero5 (5.0.27) and zotero-better-bibtex (5.0.43) on macos High Sierra.

I tried perform an export as following:
1) File -> Export Library -> OK -> select directory and save.
2) And then, check Automatic export tab in Better BibTex preferences, but I cannot see anything:

![2017-11-21 10 57 44](https://user-images.githubusercontent.com/4075389/33050930-d1f9827c-ceaa-11e7-88e6-52adebb33df5.png)

How to perform automatic export?

**Comment by retorquere** [comment]
Did you enable "Keep updated" when you exported?

**Comment by retorquere** [comment]
The checkbox is not in the preferences screen, it's in the export dialog.

**Comment by hankook** [comment]
Thanks for response. I cannot find the checkbox in the export dialog...

![2017-11-21 5 18 49](https://user-images.githubusercontent.com/4075389/33061616-1dd7f784-cee0-11e7-90e9-dd158c11a14f.png)

![2017-11-21 5 18 59](https://user-images.githubusercontent.com/4075389/33061619-21006022-cee0-11e7-90bf-a7764a3942f1.png)

**Comment by retorquere** [comment]
You have to select "Better BibLaTeX", not "BibLaTeX".

**Comment by hankook** [comment]
OMG...   The checkbox is shown now! Thanks!
