### ISSUE TITLE
"My publications" doesn't export correctly

### ISSUE THREAD

**Issue by michaelaye** [retorquere/zotero-better-bibtex#810]
# Bug classification

Exporting incorrect items

## Exporting references

I right-clicked on the "My Publications" item in Zotero 5.26 and chose Export Library -> Format Better bibtex. I had EXport notes, and keep updated activated.
But the resulting BibTex file contains ALL the library, as evident by papers in there not from me, and having the same size as my full library export (= 1.2 MB).

**Comment by michaelaye** [comment]
After updating Better-Bibtex I tried again the export of only my papers, but with the same results (full 1.2 MB file).
(created Report ID ZGHLR5TM)

**Comment by retorquere** [comment]
What happens if you don't tick "Keep updated", or when you choose regular "BibTeX" rather than "Better BibTeX"?

**Comment by retorquere** [comment]
This looks to be a Zotero bug. If I remove BBT and export "My publications", it still exports the whole library. Please report this at Zotero.
