### ISSUE TITLE
Changing the pattern doesn't regenerate the non-fixed keys 

### ISSUE THREAD

**Issue by nicaogr** [retorquere/zotero-better-bibtex#814]
When I change the pattern of the key generator from [zotero] to [auth:lower][year] it doesn't cause all my non-fixed keys to be regenerated. I am using Zotero 5.0.27

You can find here the Report ID : ZFG6TIXP but I doesn't think it will be used full.

**Comment by retorquere** [comment]
This is correct and is a behavior change against Zotero 4; under Zotero 5 it would require re-loading the whole database and I just couldn't get the performance right for larger libraries.

The functionality is still available by selecting everything, right-clicking, and choosing "Refresh key"; less convenient, I do realize.

**Comment by nicaogr** [comment]
I understand. That's works well too.
