### ISSUE TITLE
cite keys not working

### ISSUE THREAD

**Issue by Cyberfly100** [retorquere/zotero-better-bibtex#816]
I came from Zotero 4 with the old BBT version 1.6.100 installed. I had automatic bib key generation working with [auth.auth.ea]:[year]. I updated to Zotero 5 and without uninstalling the old (zotero 4) version of BBT installed the new version 5.0.48. This just replaced the old (non-woking) entry in the extensions page. Now I cannot use [auth.auth.ea] (it is orange), but all other  JabRef cite keys work, like e.g. [auth.etal]. 

report ID CVNHH3WE
![image](https://user-images.githubusercontent.com/28017534/33176447-64b2a034-d05f-11e7-9f58-3b17e6c3e127.png)
![image](https://user-images.githubusercontent.com/28017534/33176565-c6662760-d05f-11e7-955a-8bfc7c9f44d1.png)

edit: removed part after "Also,"

**Comment by retorquere** [comment]
One problem, one issue please (the part after "also" sounds like a different problem)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4929](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.47.4929.issue-816.xpi) ("replace *all* periods; fixes #816").

**Comment by retorquere** [comment]
Try 4929. I think that will solve the issue with the citekey pattern.

**Comment by Cyberfly100** [comment]
Great, test build 4929 fixed the [auth.auth.ea] issue. I will open a new issue for the part after the "also,"
