### ISSUE TITLE
changing cite key pattern does not change citation keys

### ISSUE THREAD

**Issue by Cyberfly100** [retorquere/zotero-better-bibtex#818]
I am using Zotero 5.0.28 and BBT 5.0.47.4929.
If I export my collection using BBT, the cite keys are not changed to whatever I put in the cite key field in the BBT options. Instead the cite key displayd in my collection (see attached image) is used for the export.
To be more clear: I have the cite key [auth.auth.ea]:[year] selected in the BBT options, but an example cite key copied from the generated .bib file is HuberHighlyindistinguishablestrongly2017, which is probably more like [auth][title][year].

![image](https://user-images.githubusercontent.com/28017534/33185579-fafc5d36-d083-11e7-86b5-cd21722fb868.png)

**Comment by retorquere** [comment]
Just so I understand correctly: the citekey used in the export *is* the same as you see in Zotero, but the citekey in export *and in Zotero* does not match the pattern you've entered (sorry for the extra questions, but when you use "citekey" you may mean "pattern" -- there's no citekey in the BBT prefs).

If that's what you mean, that is correct, and is a behavior change against how BBT worked under Zotero 4. Under BBT for Zotero 4 used to update all citekeys when the pattern changes. I could not get the performance right to do that under Zotero 5, so now the pattern is only used for changes to references after that pattern changed. You can force a refresh by selecting all your references, right-clicking, and selecting "refresh keys", but it's no longer automatic.

**Comment by Cyberfly100** [comment]
Yes, that's what I meant. I didn't realize I have to manually refresh the keys now. I'll try that tomorrow, but I guess you can close the issue. Thanks for your quick help!

**Comment by retorquere** [comment]
No worries. I figured pattern changes are infrequent enough to make this a pressing issue.
