### ISSUE TITLE
When escape picker, brackets pasted with Pandoc format

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#819]
For pasting citation key in a document I use Pandoc Quick copy format with the selected option "Surround Pandoc citations with brackets". It functions perfectly. However, when I call a picker to add citation key and change my mind so I press escape to cancel adding the citation key. The picker is canceled but again the brackets are pasted [ ]. 
Report ID: 3KMN3YXF
Can you make it when I escape the citation picker the brackets not to be pasted. 
Thank you!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4938](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.48.4938.issue-819.xpi) ("fixes #819").

**Comment by retorquere** [comment]
The picker does not use that preference; CAYW and quick-export are (until #765 is resolved) distinct. 

4938 should fix your problem, please try it out.

**Comment by mijalche** [comment]
4938 solves the issue. Thanks!

**Comment by retorquere** [comment]
Wow, that was fast :)

**Comment by mijalche** [comment]
Extremely agile development :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
