### ISSUE TITLE
citekey export ignoring pattern

### ISSUE THREAD

**Issue by Cyberfly100** [retorquere/zotero-better-bibtex#820]
I managed to have the displayed citekey match my BBT pattern, but the better BibTeX export still uses the [auth][titel][year] pattern.

I hope it's not me again not knowing how to use this software...
Again, I am on Zotero 5.0.28 and BBT 5.0.47.4929.

![image](https://user-images.githubusercontent.com/28017534/33200812-74ec028c-d0f6-11e7-8699-f8c8a87330cc.png)

![image](https://user-images.githubusercontent.com/28017534/33200793-6002ec3c-d0f6-11e7-8ca7-3b9cac9e958c.png)

**Comment by retorquere** [comment]
Isn't this the same as #818?

**Comment by Cyberfly100** [comment]
I don't think so, but maybe I missunderstood. In issue #818 I learned I have to select the entries and right-click to apply the pattern specified in the BBT options. This is no longer automatic in Zotero5. I managed to do this with my [auth.auth.ea]:[year] pattern now, as you can see in the first screenshot above.
In issue #818 we assumed that the export would then work, because the displayed cite key and the exported cite key were the same. But now, that I changed the displayed cite key I realize it is not what determines the exported format. Somehow I still end up with HuberHighlyindistinguishablestrongly2017 instead of Huber.Reindl.ea:2017 (which is displayed in Zotero).

**Comment by retorquere** [comment]
Ah, I see. Can you restart with debug logging enabled from the help menu, do an export, and then send a BBT error report?

**Comment by Cyberfly100** [comment]
Sure, here is the report ID: C3629IRH

**Comment by retorquere** [comment]
Can you shut down Zotero and tell me what's in `C:\Users\Lucas Schweickert\Zotero\better-bibtex\`?

**Comment by Cyberfly100** [comment]
it seems to work now with version 5.0.48!

but if it still helps here is the content of the better-bibtex folder:
![image](https://user-images.githubusercontent.com/28017534/33230904-5057cd74-d1ec-11e7-9c69-17b2bdaacbf9.png)

**Comment by retorquere** [comment]
If it works, it works. There was nothing of note in the logs.
