### ISSUE TITLE
Addon incompatible with Zotero 5.0.28 on Ubuntu 16.04

### ISSUE THREAD

**Issue by Saipraneet** [retorquere/zotero-better-bibtex#822]
I recently updated Zotero on my Ubuntu desktop and it says that the Zotero-Better-Bibtex addon is incompatible with Zotero 5.0.28.

**Comment by retorquere** [comment]
It will probably automatically update in a day or so, but just grab the latest version and install it, that will solve it.

**Comment by retorquere** [comment]
Does this solve your problem?

**Comment by retorquere** [comment]
Assuming fixed
