### ISSUE TITLE
JSON export uses lowercase 'doi'

### ISSUE THREAD

**Issue by adunning** [retorquere/zotero-better-bibtex#825]
BBT has switched to exporting records with a DOI in the Extra field with the label `doi` rather than `DOI` for the Better CSL JSON export (the uppercase version is still used for items that have a proper DOI field). This is case-sensitive, and the lowercase version isn't picked up by pandoc-citeproc.

**Comment by retorquere** [comment]
I can't currently reproduce this (I get `DOI`, not `doi`); can you send me that reference by sending it as a error report?

**Comment by retorquere** [comment]
Oh wait, do you have the `DOI` in the extra field in lowercase?

**Comment by adunning** [comment]
I don't have it in lowercase. See report ID U8WMG6YN.

**Comment by retorquere** [comment]
Can you get me a new bug report but by right-clicking that reference? I think I know what's happening, but I want to add it to my test suite.

**Comment by adunning** [comment]
Thank you! See NKV9KHL9.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4981](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4981.issue-825.xpi) ("fixes #825").

**Comment by retorquere** [comment]
Finally. 4981 should take care of it.

**Comment by adunning** [comment]
Thank you very much!

**Comment by retorquere** [comment]
Works to your satisfaction then? Looking to cut a new release when #811 clears.

**Comment by adunning** [comment]
It certainly does. Thank you!
