### ISSUE TITLE
Citekeys default behavior change with BBT 5

### ISSUE THREAD

**Issue by pprw** [retorquere/zotero-better-bibtex#827]
I have always use the default behavior of Zotero for bib(la)tex keys generation. Thus, all my keys look like this: author_shortitle_year(a/b/c...).

With the new version (5.0.49), I have a different (default) behaviour which remove the "_" and add uppercase letters. For example: If I add this ISBN: 0-465-09720-0, I obtain this key: NozickAnarchystateutopia1974.

Edit: I figure out the problem: out of the box, in 5.x version, it is not zotero which manages keys generation but BBT. The way to activate again zotero behavior is to add [zotero] in the field related to the keys generation.

I think it would be a good thing to restore the zotero behavior by default (if there is no problem with it) because most of the users have a database with zotero generated keys.

**Comment by retorquere** [comment]
There is a problem with the zotero-generated keys: it is too easy to generate keys that are not valid in bibtex/biber. So between the choice of

* having a smooth migration for existing zotero-bibtex users, and
* having new BBT users unburdened of broken keys

I opted for the latter. If the `[zotero]` filter generated safe keys, I'd use that.

**Comment by pprw** [comment]
A middle solution could be to have BBT generate keys that are similar (in most cases) to what zotero do. It would allow users with old documents containing zotero keys to still compile these documents

**Comment by pprw** [comment]
something like [auth:lower][shorttitle:lower][year] but the shorttitle contains only one word with zotero and two (or more?) with BBT.

**Comment by pprw** [comment]
I am also interested by the description of the flaw in Zotero concerning citation keys not supported by LaTeX's bibliography processors. I use Zotero for years and never had trouble to compile with biber/biblatex. In what cases it happens?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5008](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5008.issue-827.xpi) ("fix tests").

**Comment by retorquere** [comment]
One that I know of is the `&` sign (#602, https://github.com/jgm/pandoc-citeproc/issues/289, https://forums.zotero.org/discussion/66510/v-5-0-4-bibtext-key-error-with-ampersands). 5008 sets the default to `[zotero:clean]` which would get the standard Zotero keys but stuff like `&` removed (I can't recall if there are other problems -- I seem to recall there are, but I don't readily know what they are).

**Comment by kaaylim** [comment]
Hi,
I also had the citation keys as follow : author_short
[test.xlsx](https://github.com/retorquere/zotero-better-bibtex/files/1517218/test.xlsx)
title_year and used "drag and drop" to a markdown document, and yesterday my references stopped working. I am not quite sure what to do. 
So the last Zotero update change the citation key format?
I tried to change the citations keys like this [author]_[shorttitle]_[year] in better Bibtex settings before exporting but this does not seems to work. Also for some reason the drag and drop using "Better bibtex quick copy" does not work, only "Citation Key quick copy".
What would be the best thing to do?

**Comment by pprw** [comment]
@kaaylim The quick solution is to add [zotero] instead of [auth][shorttitle][year] and then click right on our references and update their keys. After that, you can export them.

**Comment by kaaylim** [comment]
@pprw Thank you! I also tried [zotero] before but did not update them!

**Comment by retorquere** [comment]
@kaaylim yeah that's a behavior change from the pre-5 series. I may have to think of a way to alert the user to this.

**Comment by retorquere** [comment]
I'll just fold the new default into a new release.
