### ISSUE TITLE
Better BibTeX hangs at startup "Starting key manager..." even after DB Scrub

### ISSUE THREAD

**Issue by pkalikman** [retorquere/zotero-better-bibtex#828]
Error log: G7UV4JTH

Please let me know if you need more information. Thanks!

**Comment by retorquere** [comment]
Thanks. It looks like there's an error in the database library I use that's triggered by some condition in your particular database, so I'll need a copy of your better-bibtex.sqlite and the contents of the better-bibtex folder under your zotero data directory. Make sure zotero is not running when you copy those.

**Comment by pkalikman** [comment]
So I just went ahead and moved all the better-bibtex files into a backup location outside the Zotero folder and let it rebuild from scratch, and it seems to be working fine. I realize this means you won't be able to diagnose the actual error but my guess is it was another one of those caused by lingering data from early release testing. Please let me know if you want to pursue anyway and thanks for your help and all your work on this plugin!

**Comment by retorquere** [comment]
I'd really love to get a hold of those DB files if you still have them. It's not just pre-release data, the database engine itself errored out, which is simply not supposed to happen no matter what data you stick in it, so I want to file an error report with the developers of that database -- for that, I'll need to generate an isolated test case.

**Comment by retorquere** [comment]
(removing the DB files means the keys are regenerated BTW -- if you had duplicates with postfixes, it is technically possible, although unlikely, they'll have gotten their postfixes swapped)

**Comment by retorquere** [comment]
If you still have the DB files I'd *really* love to get to the bottom if this. If not, I will have to close the issue.

**Comment by retorquere** [comment]
Do you still have the files?

**Comment by retorquere** [comment]
Alright. I'm going to close this issue for now - if the files do turn up, and you comment here, the issue will reopen automatically.
