### ISSUE TITLE
I think quick copy should use 1 for local library ID instead of 0

### ISSUE THREAD

**Issue by scottmartincampbell** [retorquere/zotero-better-bibtex#829]
Quick copy of a local library item using `Better BibTeX Citation Key Quick Copy.js` in org-mode creates a link in emacs that uses 0 (zero) for the library ID, as in zotero://select/items/0_HVC7IEPW. This used to work with zotero 4, but no longer works in my setup (linux, Zotero 5.0.29, latest version of BBT, zotxt 5.0, emacs 25, org-mode 9.1). Changing the library ID to 1, as in zotero://select/items/1_HVC7IEPW, or getting rid of it all together, as in zotero://select/items/HVC7IEPW, does work. According to https://groups.google.com/forum/#!msg/zotero-dev/efFuMEqLarY/bZ167jIyGQAJ it looks like the local library ID should be 1 or nothing at all.  

I patched `Better BibTeX Citation Key Quick Copy.js` myself to change 0_ to 1_ and it works for me now.

(Also, your work getting this working for Z5 has been amazing. I've held off updating because BBT and zotxt were so critical to my workflow. Thanks so much!)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5017](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5017.issue-829.xpi) ("fixes #829").

**Comment by retorquere** [comment]
try 5017

**Comment by scottmartincampbell** [comment]
Great! Thanks.

**Comment by scottmartincampbell** [comment]
This problem seems to have reappeared in Quick Copy. Looking at translators/Better BibTeX Citation Key Quick Copy.ts it's back to "0_" prefix before the key instead of "1_" or nothing. Should I patch my own translator?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.133.6513.issue-829](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.133.6513.issue-829.xpi) ("re-fixes #829").

**Comment by retorquere** [comment]
Don't know how that got back in. Can you try 6513?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.133.6518.master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.133.6518.master.xpi) ("re-fixes #829").
