### ISSUE TITLE
Usage Q on Versions (based on issue with citekeys)

### ISSUE THREAD

**Issue by kwinkle** [retorquere/zotero-better-bibtex#830]
Apologies this may be something I've missed from somewhere else. I recently updated Zotero (on version 5.0.28) and got the latest version of BBT. Displayed citekeys now do not match those exported, and I no longer have the option to right click and generate bibtex keys. Is it a version incompatibility?

**Comment by retorquere** [comment]
There must be a startup error; submit a bbt error report and post the ID here. If you're offered to restart with debugging enabled, please do so before submitting the error report.

**Comment by kwinkle** [comment]
Thanks for quick response!
Report ID: F5B32KJA

**Comment by retorquere** [comment]
You did not restart with debugging enabled; there's not enough info in the log this way.

**Comment by kwinkle** [comment]
Apologies, have restarted. New ID: YUANRR9K

**Comment by retorquere** [comment]
No errors in the logs. Can you (making sure having restarted with debugging enabled), right, click a reference that displays a different key than is exported, and then

* with the right-click menu open, get me a screenshot, and then
* from that menu, select "report BBT errrors" and get me that ID

**Comment by kwinkle** [comment]
![image](https://user-images.githubusercontent.com/17174384/33485129-26b838d6-d69d-11e7-8a26-29819d438339.png)

Report ID: K56NGS9C

**Comment by retorquere** [comment]
I don't follow, from what I'm seeing:

* That reference has a pinned citekey `Fongsurveysociallyinteractive2003`. This key is displayed and also exported (at least to the debug format that submits the reference, but they use the same key cache as all the other exporters)
* You can regenerate the citekey by refreshing it (second to last option)

What key do you get when you export?

**Comment by kwinkle** [comment]
When I export the whole library into a .bib I get:

@article{fong_survey_2003,
	series = {Socially {Interactive} {Robots}},
	title = {A survey of socially interactive robots},
	volume = {42},
	issn = {0921-8890},
	url = {http://www.sciencedirect.com/science/article/pii/S092188900200372X},
	doi = {10.1016/S0921-8890(02)00372-X},
	abstract = {This paper reviews “socially interactive robots”: robots for which social human–robot interaction is important. We begin by discussing the context for socially interactive robots, emphasizing the relationship to other research fields and the different forms of “social robots”. We then present a taxonomy of design methods and system components used to build socially interactive robots. Finally, we describe the impact of these robots on humans and discuss open issues. An expanded version of this paper, which contains a survey and taxonomy of current applications, is available as a technical report [T. Fong, I. Nourbakhsh, K. Dautenhahn, A survey of socially interactive robots: concepts, design and applications, Technical Report No. CMU-RI-TR-02-29, Robotics Institute, Carnegie Mellon University, 2002].},
	number = {3–4},
	urldate = {2017-03-28},
	journal = {Robotics and Autonomous Systems},
	author = {Fong, Terrence and Nourbakhsh, Illah and Dautenhahn, Kerstin},
	month = mar,
	year = {2003},
	note = {bibtex: Fongsurveysociallyinteractive2003},
	keywords = {Human–robot interaction, Interaction aware robot, Socially interactive robot, Sociable robot, social robot},
	pages = {143--166},
	file = {ScienceDirect Full Text PDF:C\:\\Users\\Katie\\Zotero\\storage\\BBIJ8AKF\\Fong et al. - 2003 - A survey of socially interactive robots.pdf:application/pdf;ScienceDirect Snapshot:C\:\\Users\\Katie\\Zotero\\storage\\QE9C8CT4\\S092188900200372X.html:text/html}
}

where fong_survey_2003 is the pinned citation key I previously generated using BBT before updating everything. My method previously was to import something to zotero directly from chrome and then right click and generate citation key; which always worked fine and allowed me to see citation keys with zotero (in the 'extra' box) without having to export. Not sure how best to now approach use. 

Just tested with a freshly imported reference and same issue, citation key listed in Zotero as 'AndrewsBSACstandardizeddisc2001' but exports as 'andrews_bsac_2001'

**Comment by retorquere** [comment]
Are you exporting this with `BibTeX` or with `Better BibTeX`? This looks like it's been generated by the standard BibTeX exporter from Zotero.

**Comment by retorquere** [comment]
A key is always generated for a reference; you can refresh after you change the pattern, but for a pinned key, refresh won't do anything; you'd need to unpin the key first.

**Comment by retorquere** [comment]
(that reference does not have a pinned citekey of `fong_survey_2003` BTW -- I can see in the Zotero-generated BibTeX above, and in the debug log you submitted, that it is pinned to `Fongsurveysociallyinteractive2003`)

**Comment by kwinkle** [comment]
You're right, I was exporting just with standard BibTeX exporter; sorry that was pretty stupid of me. Suspect the pinned key has changed since the update as I was trying to figure out what was wrong (doh). Still, that means that previously BBT was just allowing me to see citation keys automatically generated by Zotero? Which I could then use when exporting via standard Bibtex? Is there a way to get back to that?

**Comment by retorquere** [comment]
The update hasn't changed the pinned keys -- BBT is conservative (one could say paranoid) about changing the Zotero DB, so I only ever pins keys on user action. The keys must have been there before the upgrade. I don't know what else to say.

BBT has never displayed the Zotero-generated keys; it can't because these keys are only generated on the fly during the Zotero-BibTeX export. They don't exist before or after, there's nothing to display. The standard BibTeX exporters are not BBT-enabled, they don't know anything about BBTs facilities, so they can't tap into the key cache, or the auto-export, etc.

If you want Zotero-keys, change BBTs citekey pattern to `[zotero]`; if you want mostly-Zotero-like keys but cleaned for rare incompatibilities with biber, user `[zotero:clean]` (which is going to be the default soon); after that, select all references, and select "unpin" from the right-click menu. The selected references will be unpinned and refreshed by doing that, so they'll get Zotero-like keys.

**Comment by kwinkle** [comment]
Ok great, not sure how I got myself into such a mess, but thanks for the speedy help & advice; much appreciated!

**Comment by retorquere** [comment]
No worrries
