### ISSUE TITLE
ISBN fields break export

### ISSUE THREAD

**Issue by psmith1303** [retorquere/zotero-better-bibtex#833]
## Exporting references

Whilst exporting all my references (5344) of them, the export falls over.

The error report ID is JMF72LQV

The error text is:
> [JavaScript Error: "isbn is null" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.js" line: 19731}]

**Comment by psmith1303** [comment]
I think I have found the record which BetterBibtex stumbles on. If I do a 'plain old' BibLaTex export it looks like this.

> @book{kaiser_strategic_2011,
> 	location = {Heidelberg},
> 	title = {Strategic management of professional service firms theory and practice},
> 	isbn = {978-3-642-16063-9},
> 	abstract = {Machine generated contents note: pt. I Professional Service Firms -- 1.The World of Professional Service Firms -- 1.1.What Are Professional Service Firms? -- 1.2.Management Challenges and Approaches for Professional Service Firms -- 1.3.Strategic Challenges and Approaches for Professional Service Firms -- 2.The Business of Professional Service Firms -- 2.1.Types of Professional Service Firm Businesses -- 2.2.Remuneration Forms in Professional Service Firms -- 3.The Subsectors of Professional Service Firms -- 3.1.Auditing Firms -- 3.2.Corporate Law Firms -- 3.3.Consulting Firms -- 3.4.Recruitment Agencies -- 3.5.Investment Banks -- 3.6.Communication Agencies -- 3.7.Engineering Service Providers -- pt. {II} Management of Strategic Resources -- 4.Quality Management -- 4.1.Increase of Service Quality -- 4.2.Development and Use of Social Competence -- 4.3.Reputation and Trust as Long-Term Quality Criteria -- 5.Knowledge Management and Innovation -- 5.1.Knowledge and Innovation as Key Success Factors in Professional Service Firms -- 5.2.Management of Knowledge -- 5.3.Innovation as a Special Challenge -- 6.Marketing and Relationship Management -- 6.1.Criteria when Purchasing Professional Services -- 6.2.Effective Marketing of Professional Services -- 6.3.Operative Professional Service Marketing -- pt. {III} Management of Professionals -- 7.Human Resource Management in Professional Service Firms -- 7.1.Objectives and Challenges -- 7.2.Performance Analysis as Informational Basis -- 7.3.Acquisition of Professionals -- 7.4.Motivation of Professionals -- 7.5.Development of Professionals -- 8.Professional Service Firms as High Performance Work Systems -- 8.1.The Idea of High Performance Work Systems -- 8.2.Elements of a High Performance Work System -- 8.3.From High Performance Work Systems to Employee Performance -- 8.4.Professional Service Firms as Field of Application of High Performance Work Systems -- 9.Work-Life Balance in Professional Service Firms -- 9.1.Ideas About the Balance of Work and Life -- 9.2.Factors Influencing Work-Life Balance -- 9.3.Promotion of the Work-Life Balance of Professionals -- 9.4.Positive Impacts of a Good Work-Life Balance -- 10.The Alumni Network -- 10.1.Origins of Alumni Networks in Professional Service Firms -- 10.2.Organization and Size of Alumni Networks -- 10.3.Key Elements and Selectivity -- 10.4.Relevance of Alumni Networks as Success Factor -- 10.5.Implications for the Management of Professional Service Firms -- 10.6.Development Tendencies of Alumni Networks in Professional Service Firms -- pt. {IV} Management of Strategic Development -- 11.Strategic Development of Professional Service Firms -- 11.1.Generic Options for Strategic Development -- 11.2.Organic Development -- 11.3.External Development Through Acquisitions -- 11.4.External Development Through Cooperations -- 12.Networking as a Strategy for Small and Medium Professional Service Firms -- 12.1.The Basic Problem -- 12.2.Value-Adding Networks, Social Capital and Professional Service Firms -- 12.3.Configuration of Value-Adding Networks for Small and Medium Professional Service Firms -- 13.Surviving Crises - Crisis Management -- 13.1.Growth Crises in the {PSF} Sector -- 13.2.Strategic Options -- 13.3.Company Areas Relevant for Crisis Management -- 14.Archetype Change Towards Management -- 14.1.Dimensions of Archetypes -- 14.2.P2 and the Managed Professional Business -- 14.3.Change of Archetype - Yes or No?.},
> 	publisher = {Springer-Verlag Berlin Heidelberg},
> 	author = {Kaiser, Stephan and Ringlstetter, Max Josef},
> 	date = {2011},
> 	file = {Kaiser_Ringlstetter_2011_Strategic management of professional service firms theory and practice.pdf:C\:\\Users\\psmi045\\Dropbox\\psmith\\Work\\Research\\Citations\\Zotero\\storage\\5Z2DDJ9B\\Kaiser_Ringlstetter_2011_Strategic management of professional service firms theory and practice.pdf:application/pdf}
> }

**Comment by psmith1303** [comment]
If I delete the IBSN from this record, then I get a bit further through my references, before it falls over again with the same error on a different isbn.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5056](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5056.issue-833.xpi) ("Merge branch 'master' into 833").

**Comment by retorquere** [comment]
Try 5056

**Comment by psmith1303** [comment]
That looks good to me :) 
Thanks for the quick fix.
