### ISSUE TITLE
Removed folder breaks auto-exports

### ISSUE THREAD

**Issue by koliii** [retorquere/zotero-better-bibtex#834]
Hi Emiliano,

Some how my bib file is not getting auto updated in the R working dir. Hence citr is writing reference update own its own but wrongly (it is not adding commas in author entry). As a result, R halt the latex output. I might have messed up some zotero settings. 
![screenshot from 2017-12-04 22-22-13](https://user-images.githubusercontent.com/28312545/33590448-7929ecb2-d9a5-11e7-9c11-b50c03e141fd.png)

**Comment by retorquere** [comment]
And you did check the "Keep updated" box? Can you get me a screenshot of the bbt auto-export Prefs screen?

**Comment by ak-koli** [comment]
Yes, I checked the box. I hope attached screen shot is the one you asked for, otherwise please guide me to get the right one
![screenshot from 2017-12-05 12-27-53](https://user-images.githubusercontent.com/28312545/33593985-0a2ad46c-d9b8-11e7-8cdf-ad42fdc69c00.png)
.

**Comment by ak-koli** [comment]
What are the chances that this issue is related with the zotero connector preferences - under tab 'General' - 'authorize' settings. Yesterday by mistake I clicked the "authorize" and then I did not understand any thing so I bring it back to default setting, present status is this:
![screenshot from 2017-12-05 12-39-17](https://user-images.githubusercontent.com/28312545/33594292-5b13ce46-d9b9-11e7-8140-5f51a357b28e.png)

**Comment by retorquere** [comment]
Zero chance.

Can you get me a debug report (Help -> Report Better BIbTeX Errors); if it asks you to restart with debugging enabled, please do so before submitting the report.

**Comment by ak-koli** [comment]
this is the report ID: 2CGZTWS2, I'm new with all these procedures, I hope that things work out fine.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5057](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5057.issue-834.xpi) ("Merge branch 'master' into 834").

**Comment by retorquere** [comment]
Can you try 5057 and send a new log? It won't fix it but it will give me more info.

**Comment by ak-koli** [comment]
Sorry, are you asking me?

**Comment by retorquere** [comment]
Yep.

**Comment by ak-koli** [comment]
I clicked on test build 5057 but firefox is not allowing this add-on.

**Comment by retorquere** [comment]
Firefox user, yeah? You need to right-click and choose "save link as". XPI is also the format for FF extensions to it thinks you want to install in the browser.

**Comment by ak-koli** [comment]
this is id: CVQ76QEQ

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5061](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5061.issue-834.xpi) ("structure logs").

**Comment by retorquere** [comment]
Can you try again with 5061?

**Comment by ak-koli** [comment]
this is log id: 4MG89NG6

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5062](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.50.5062.issue-834.xpi) ("reject when translation target dir does not exist -- why isn't this error just thrown by Z?").

**Comment by retorquere** [comment]
Two things:

1. Can you try 5062, and
2. Does the folder `/home/ajay/Desktop/r-tutorial-practice-sessions` exist?

**Comment by ak-koli** [comment]
report id: BS65XPB9

and yes, this particular folder is present.

**Comment by ak-koli** [comment]
@retorquere , It may not be important but I got error while working in this folder:
```
/home/ajay/thesis-ajay-10mbph04
```
the folder your mentioned is just another directory for practicing `R`.

**Comment by retorquere** [comment]
There were errors in 4MG89NG6 that indicated Zotero could not open the export file for writing... but in BS65XPB9 there are no errors, and there's also no auto-export activity, I can only see you have 3 of them set up. Can you look what the state of those three are in the BBT prefs?

**Comment by ak-koli** [comment]
right now it is like this
![screenshot from 2017-12-05 20-12-16](https://user-images.githubusercontent.com/28312545/33612789-b84d041c-d9f8-11e7-83ff-933f78fe2679.png)

**Comment by retorquere** [comment]
You seem to have auto-exports set up for 

* /home/ajay/Desktop/r-tutorial-practice-sessions/book.bib
* /home/ajay/Desktop/My Library.bib
* /home/ajay/thesis-ajay-10mbph04/book.bib

4MG89NG6 has a Zotero error that it cannot open an export file for writing but it doesn't say which; I was just guessing about the directory not existing. BS65XPB9 has no errors, but also no AE activity, which should only happen if all have been status `done`.

**Comment by ak-koli** [comment]
@retorquere , now things are without error, I checked by adding two new references, auto export done and citr run without error, see this screen shot
![screenshot from 2017-12-05 20-20-08](https://user-images.githubusercontent.com/28312545/33613132-cd35b904-d9f9-11e7-8c3f-6ffcffeca396.png)

**Comment by retorquere** [comment]
They're currently all marked as `done`; you'll have to change one of the references in those collections to kick off an auto-export, or select one from that screen and click `Export`. Otherwise there won't be anything for me to analyze in the logs.

**Comment by retorquere** [comment]
No idea why it now works, I only added logging ¯\\\_(ツ)_/¯

**Comment by ak-koli** [comment]
Let me restart the computer and double check it, if any error then I'll will again ask for your help. Thank you so much for your sincere effort during these long hours.  :-)

**Comment by retorquere** [comment]
No worries.

**Comment by ak-koli** [comment]
Regarding this issue no more errors. May I close it now?

**Comment by retorquere** [comment]
Thanks for the confirmation - I'll close it myself in a bit, I did some cleanup while working on the diagnosis,and I'll close when that's in the main branch.

**Comment by ak-koli** [comment]
Sure, good night friend Emiliano

**Comment by ak-koli** [comment]
@retorquere , sadly this error is back in a similar way.

**Comment by ak-koli** [comment]
citation key is appearing strange, starting with small case alphabet and even after deleting the reference from zotero and after adding it again the cit key is ending with 1,2,. after every successive re-entry of the same reference.

**Comment by retorquere** [comment]
What's your citation key format?

**Comment by retorquere** [comment]
BTW this really is a very different issue; I prefer new issues being opened for unrelated problems.

**Comment by ak-koli** [comment]
okay @retorquere , the citation key format is two fields: Surname, First name

**Comment by retorquere** [comment]
Can you open a new issue for this please.

**Comment by ak-koli** [comment]
I already did, please let me re-check.

**Comment by ak-koli** [comment]
Yes, new issue is at #837

**Comment by ak-koli** [comment]
report id: VH8SIGW7

**Comment by retorquere** [comment]
I'm seeing errors in the log that claim that `/home/ajay/Desktop/r-tutorial-practice-sessions/book.bib` is either a directory, or that it's parent folder does not exist.

**Comment by ak-koli** [comment]
I'm working in this directory `/home/ajay/thesis-ajay-10mbph04`. It contains all my PhD thesis work. The one you mentioned is not very important for me because it is used just to practice `R`.

**Comment by ak-koli** [comment]
Shall I delete others and keep only `/home/ajay/thesis-ajay-10mbph04` this folder? If it helps you.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5071](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.51.5071.issue-834.xpi) ("ae target detection").

**Comment by ak-koli** [comment]
I'm trying it.

**Comment by ak-koli** [comment]
Yes, now no more error. What wrong I did so it came back? In case you can spare some time, please.

**Comment by retorquere** [comment]
In the BBT auto-export prefs, one of them (most likely `/home/ajay/Desktop/r-tutorial-practice-sessions/book.bib`) will say `error`, and if you hover over the error, it will tell you what's wrong with the path (please let me know what it is). Zotero craps out if you export to an invalid path, so I'm testing the path now before the export.

**Comment by ak-koli** [comment]
Emiliano, you are absolutely right. On hovering over `status` it is showing more details, in comparison to two other paths, with error on `home/ajay/Desktop/r-tutorial-practice-sessions/book.bib` .

**Comment by ak-koli** [comment]
If you do not mind, may I leave? It is 3am here.

**Comment by retorquere** [comment]
Can you post the actual error that you get on hover tomorrow?

**Comment by ak-koli** [comment]
I do not know how to copy the error from that box, a screen shot is attached
![screenshot from 2017-12-07 03-34-04](https://user-images.githubusercontent.com/28312545/33687910-b2c6ac66-daff-11e7-8aec-6344d29c0b34.png)

**Comment by ak-koli** [comment]
Will it work?

**Comment by retorquere** [comment]
Yep. 5074 will drop in a few minutes and the error will be less technical; I'd appreciate a screenshot, but no rush, tomorrow is absolutely fine.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5074](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.51.5074.issue-834.xpi) ("test for parent").

**Comment by ak-koli** [comment]
Good morning @retorquere , after installing test build 5074 this is zotero pref auto exp `status` hovering screen shot:
![screenshot from 2017-12-07 10-42-37](https://user-images.githubusercontent.com/28312545/33699845-a18b1de2-db3b-11e7-986f-4464ec861c81.png)

**Comment by ak-koli** [comment]
@retorquere , I'm sorry. It seems I made a mistake. Right now on my computer no folder with this name `home/ajay/Desktop/r-tutorial-practice-sessions/book.bib`
My poor focus, I forgot that I renamed it as this and deleted the bib file
`/home/ajay/Desktop/cRaft`

I'm sincerely sorry if this has caused all this trouble.

**Comment by retorquere** [comment]
That's OK, I thought it would be something like that. Can you manually kick off the failing export by selecting it and clicking "export", and them get me a new hover - screenshot? I'm hoping to see a more explanatory error.

**Comment by ak-koli** [comment]
Thank you @retorquere :)
![screenshot from 2017-12-07 11-48-48](https://user-images.githubusercontent.com/28312545/33701423-b1ac1d26-db44-11e7-9511-fa0cca640831.png)

**Comment by retorquere** [comment]
That is strange, 5074 doesn't have a test for isDirectory anymore. Can you change a reference that would usually cause those auto-exports to fire, then look at the error again?

**Comment by ak-koli** [comment]
This error occurred when I was working in this dir `/home/ajay/thesis-ajay-10mbph04` and at present everything is working fine in this directory. And this is present status on hovering over `status`, no error
![screenshot from 2017-12-07 12-27-40](https://user-images.githubusercontent.com/28312545/33702549-2717ec2a-db4a-11e7-894d-4a0fb6b19cfa.png)

**Comment by ak-koli** [comment]
Will it be considered a good practice if I remove manually the unused bib file paths from the zotero?

**Comment by retorquere** [comment]
Super, that's what I'd expect to see.

Yeah, currently you have to manually remove auto exports you no longer want. I suppose I could technically remove auto-exports where the target dit has been removed, but that'd also mean if you rename and rename it back, the auto-export would have been unnecessarily removed.

I think I'll keep it this way. I'll fold this change into the new release.

**Comment by retorquere** [comment]
Ah yeah, it says "done", not "error". I'll think about that, but the message you're seeing is the error that was detected.

**Comment by ak-koli** [comment]
It was showing no `parent dir`, so that was error too.
I removed those unused dirs, and things are looking fine
![screenshot from 2017-12-07 12-52-51](https://user-images.githubusercontent.com/28312545/33703369-d0c03388-db4d-11e7-826a-d1b9307623a5.png)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5104](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.54.5104.issue-834.xpi) ("display error status").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5108](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.54.5108.issue-834.xpi) ("Merge branch 'master' into 834").

**Comment by koliii** [comment]
Hi @retorquere , it seems that a similar error has returned

![screenshot from 2018-01-29 21-50-55](https://user-images.githubusercontent.com/28312545/35520970-8ef0e3b0-053e-11e8-94d9-5002e4b4aa74.png)

**Comment by retorquere** [comment]
This seems like a different problem from #834. Can you open a new issue?

**Comment by koliii** [comment]
I'm not able to create a new issue. At your page the `submit new issue` is not working for me.

**Comment by retorquere** [comment]
I'm not sure which page that is, but [this](https://github.com/retorquere/zotero-better-bibtex/issues/new) is the correct link.
