### ISSUE TITLE
Auto Update not working

### ISSUE THREAD

**Issue by phinal** [retorquere/zotero-better-bibtex#835]
I have trouble with the _keep updated_ feature since the latest update of Better Bibtex.
Plus, the dialog for exporting showing `exportOptions.keepUpdated` and not _keep updated_ as regular text.

<img width="361" alt="screen shot 2017-12-05 at 17 30 38" src="https://user-images.githubusercontent.com/1871283/33618235-44c98d0a-d9e2-11e7-9b94-550a0b727b22.png">

**Zotero**: Version `5.0.29`
**Zotero Better Bib(La)Tex**: Version `5.0.50`
**OS**: macOS `10.13.1`

**Comment by retorquere** [comment]
Can you get me a BBT debug log?

**Comment by retorquere** [comment]
Really can't do anything without a log.

**Comment by retorquere** [comment]
Hello?

**Comment by katrinleinweber** [comment]
Do you mean the `Help > Report Better BibTeX Errors` kind of log?

**Comment by phinal** [comment]
Sorry for the delay.
The Issue disappeared by it's own … Thanks for help anyway.

**Comment by retorquere** [comment]
@katrinleinweber yes, that kind. Do you see this problem too?

**Comment by katrinleinweber** [comment]
Luckily not. Was just browsing the repo to get a feel for this project's development after it didn't fit into my thesis writing workflow a few years ago. Trying again now :-)

**Comment by retorquere** [comment]
Nothing much has changed from a functional point of view.
