### ISSUE TITLE
zotero + better bibtex citation key 

### ISSUE THREAD

**Issue by ak-koli** [retorquere/zotero-better-bibtex#837]
@retorquere , suddenly all new and if updated then old too citation keys are coming in small case, I hope that it will not make unstable all references earlier done in my r markdown doc.

**Comment by retorquere** [comment]
Existing references won't have had their citation key changed. Can you look in the bbt preferences what the pattern format is?

**Comment by ak-koli** [comment]
It is showing this: [zotero:clean]
I've no clue how it happened.

**Comment by retorquere** [comment]
The default has changed -- I had forgotten this would affect existing users. I'll think of a fix, but right now, you'll want `[auth][shorttitle][year]`.

**Comment by ak-koli** [comment]
Shall I add this `[auth][shorttitle][year]` in pref cit key format box?

**Comment by retorquere** [comment]
Yes.

**Comment by ak-koli** [comment]
this citation key issue is fine now. But issue #834 error is active again.

**Comment by retorquere** [comment]
Then I'll need an error log there. It is really important to me to keep bug communication focused - one issue to focus on one problem.

**Comment by ak-koli** [comment]
Just now I added the report id.
