### ISSUE TITLE
Don't escape right square brackets

### ISSUE THREAD

**Issue by mmwood** [retorquere/zotero-better-bibtex#85]
First, I want to say thank you for the extension, which is critical for my use of Zotero and bibtex!  But just recently I've run into a problem...

When you import a paper from the arxiv, e.g. at website
http://arxiv.org/abs/1407.5694
Zotero puts 
arXiv:1407.5694 [math]
in the publication field.  Better bibtex seems to be currently exporting this as a Bibtex file with
  journal = {{arXiv:1407.5694 [math]}},
or
  journal = {arXiv:1407.5694 [math]},
without the double braces option.  For contrast a regular bibtex export gives
    journal = {{arXiv}:1407.5694 [math]},

The problem is that Latex renders the [ and ] around math as a displayed equation.  This is a new problem.  From looking at .bbl files that I produced from a Better bibtex exported .bib file awhile ago, I am guessing that the export used to be something like

  journal = {arXiv:1407.5694 \ensuremath{[}math\ensuremath{]}}.

which is fine.  Let me know if you need any more information.

**Comment by retorquere** [comment]
Hey @mmwood, could you take a look at #460? The changes made there would render your reference as

```
@article{Hu2014,
  abstract = {Let X be a projective variety which is algebraic Lang hyperbolic. We show that Lang's conjecture holds (one direction only): X and all its subvarieties are of general type and the canonical divisor K\_X is ample at smooth points and Kawamata log terminal points of X, provided that K\_X is Q-Cartier, no Calabi-Yau variety is algebraic Lang hyperbolic and a weak abundance conjecture holds.},
  author = {Hu, Fei and Meng, Sheng and Zhang, De-Qi},
  archivePrefix = {arXiv},
  eprint = {1407.5694},
  eprinttype = {arxiv},
  keywords = {32Q45 Hyperbolic and Kobayashi hyperbolic manifolds; 14E30 Minimal model program (Mori theory; extremal rays),Mathematics - Algebraic Geometry,Mathematics - Complex Variables,Mathematics - Differential Geometry},
  month = jul,
  note = {\url{http://arxiv.org/abs/1407.5694}},
  primaryClass = {math},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {Ampleness of Canonical Divisors of Hyperbolic Normal Projective Varieties},
  urldate = {2014-08-11},
  year = {2014}
}
```

would that still be OK for your case?
