### ISSUE TITLE
CAYW: BBT Error while citing two sources (Scannable-cite)

### ISSUE THREAD

**Issue by marcelpelz** [retorquere/zotero-better-bibtex#851]
I have a problem, when i want to cite two sources at once. I am using Scannable-cites and the CAYW-Feature. Also i've installed the newest Zotero- and Plugin-Versions

CAYW failed: Error: Expected zu:2996967:EAP2DCWP, found zu:2996967:RRAIQIWZ
Scannable-cite@chrome://zotero-better-bibtex/content/common.js:79391:23

With the quick export feature everything is fine.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5166](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.59.5166.issue-851.xpi) ("reduce to object").

**Comment by retorquere** [comment]
BBT quick-copy doesn't do scannable cite, that must be their own translator. Can you try 5166? If that doesn't solve the issue, can you restart with debugging enabled, try again, and send a BBT error report?

**Comment by marcelpelz** [comment]
5166 solved the issue :-)
Thanks!

**Comment by retorquere** [comment]
Strangeand I now know why. Cool, will fold this into a release as soon as my MacBook finishes rebooting (which may take a while)
