### ISSUE TITLE
Suppress author not represented in CAYW pandoc format

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#857]
Hi, 
I identified that when I call the picker and in it I check the option Suppress the author, the pasted citation key does not follow this requirement i.e. I receive [author.00.e] instead of [-author.00.e].  I use the Pandoc option in QuickCopy format. The other options like page, prefix, suffix are appropriately added to the citation key.
Report ID: KSLVMAQX
Thanks for continuous and great work!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5206](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.63.5206.issue-857.xpi) ("fixes #875").

**Comment by mijalche** [comment]
issue solved.
Thanks!
