### ISSUE TITLE
BBT does not override existing journal abbreviations on export (edit: this is by design)

### ISSUE THREAD

**Issue by kuangyia** [retorquere/zotero-better-bibtex#858]
BBT can produce well the abbreviation style for most of scientific journals. But there still exists some journals that can not be abbreviated with BBT. Here, I give three examples below:

@article{CamargoElectricalpropertiesinplaneimplanted2017,
  title = {Electrical Properties of In-Plane-Implanted Graphite Nanoribbons},
  volume = {122},
  **journal = {Journal of Applied Physics},**
  author = {Camargo, B. C. and {de Jesus}, R. F. and Semenenko, B. V. and Precker, C. E.},
  year = {2017},
  pages = {244302}
}

@article{LiAnisotropicopticalabsorptiona,
  title = {Anisotropic Optical Absorption Induced by {{Rashba}} Spin-Orbit Coupling in Monolayer Phosphorene},
  **journal = {Physica E: Low-dimensional Systems and Nanostructures},**
  author = {Li, Yuan and Li, Xin and Wan, Qi and Bai, R. and Wen, Z. C.}
}

@article{BoularesSurfacephononstopological2018,
  title = {Surface Phonons in the Topological Insulators {{Bi2Se3}} and {{Bi2Te3}}},
  volume = {271},
  **journal = {Solid State Communications},**
  author = {Boulares, Ibrahim and Shi, Guangsha and Kioupakis, Emmanouil and Lo{\v s}{\v t}{\'a}k, Petr and Uher, Ctirad and Merlin, Roberto},
  year = {2018},
  pages = {1--5}
}

So what's the reason of this problem ?

**Comment by retorquere** [comment]
I know you can't send debug reports right now, but can you export this reference using "BetterBibTeX JSON" and attach that here?

**Comment by kuangyia** [comment]
Sorry, here do not support json file type. How to do then ?

**Comment by kuangyia** [comment]
[Exported.txt](https://github.com/retorquere/zotero-better-bibtex/files/1589686/Exported.txt)
I just converted it into txt, and attach it again.

**Comment by retorquere** [comment]
BBT won't abbreviate this reference because you've filled the `Journal Abbr` field in Zotero. If you put something in that field it will always be used as the abbreviation. You've entered the abbreviated title in the `Publication` field. You may want to swap these two around.

**Comment by kuangyia** [comment]
Yes. I admit that I have filled the 'publication' field. Actually, even before I filled this field, it still gave a full journal name. As you said, I need to exchange two field values. But the problem is that I have to do it manually.

**Comment by retorquere** [comment]
I can look at auto-abbreviation problems if you have a reference with a full title that doesn't abbreviate properly, but BBT can't help you with swapping these fields.

**Comment by kuangyia** [comment]
I know BBT can't do this automatically. So in these occasions, I have to do it manually.

**Comment by retorquere** [comment]
But do you have a reference where you have not filled out the abbreviation field and BBT doesn't do auto-abbrev?

**Comment by kuangyia** [comment]
Yes. I have two. Do you want to see ?

**Comment by kuangyia** [comment]
As I said, BBT can produce well most of scientific journals into their abbreviations. But still some can not be.

**Comment by kuangyia** [comment]
for example:

[Zotero Report.pdf](https://github.com/retorquere/zotero-better-bibtex/files/1589894/Zotero.Report.pdf)

**Comment by retorquere** [comment]
I need a "BetterBibTeX JSON" export of those two references.

**Comment by retorquere** [comment]
But if that pdf is the reference you mean, that has the journal abbrev field filled in. As I've mentioned already, if you fill out the abbrev field, BBT will not override it.

**Comment by kuangyia** [comment]
The export:
[Export.txt](https://github.com/retorquere/zotero-better-bibtex/files/1589994/Export.txt)

BTW: I did not fill out for sure (just keep as it is).

**Comment by retorquere** [comment]
Both of those references have the journal abbrev field filled. If you want BBT to auto abbrev journal titles, that field must be empty. If there's something in the abbrev field for a reference, BBT will not override it.

**Comment by kuangyia** [comment]
OK. That means to manually change/delete the field, right ?

**Comment by kuangyia** [comment]
If I want to get the journal abbreviation.

**Comment by retorquere** [comment]
Well yeah, if you want BBT to generate missing abbreviations, they have to be missing first.

**Comment by kuangyia** [comment]
Anyway, the good thing is that BBT is powerfully able to convert most of journals into their abbreviations. There is only a minority of journals that need to be manipulated by hand. So still cheers with BBT, ^_^.

**Comment by retorquere** [comment]
I'd still like to know about that minority, but the samples you've given me so far simply don't activate the BBT abbreviator (which is under water just the Zotero abbreviator, so the praise should go there). If a reference has a manually filled-out title abbreviation, BBT is not going to second-guess that and will use what was entered. That is not "a minority of journals that need to be manipulated by hand", that is "BBT will not wantonly disregard what the use has entered".

If you have a reference that
* does not have a value entered for the `Journal Abbrev` field, but 
* does have a journal title, and
* that journal title is not appropriately abbreviated during export

then I'd *really* love to see it so I can see if I (or Zotero) can improve the abbreviator. But none of the references posted match these criteria.

**Comment by kuangyia** [comment]
I double check the reference and I am 100% sure that I did not change anything. But as  I reported here, BBT (Zotero) does not give the journal abbreviation for that reference.  If you do not believe, I provide you below the link of that reference and you can try it by yourself.

https://www.sciencedirect.com/science/article/pii/S1386947717317538
http://aip.scitation.org/doi/full/10.1063/1.4995223

**Comment by retorquere** [comment]
I'd really much rather have a "BetterBibTeX JSON" export of a reference that you think doesn't export well. That will give me exactly what's in your library.

**Comment by kuangyia** [comment]
Well, I can not attach that export because json file is not supported here. Do you know how to ?

**Comment by retorquere** [comment]
Just rename it to .txt

**Comment by retorquere** [comment]
I've also tried importing those two references you mentioned and they include text in the `Journal Abbrev` field *in Zotero* after they are imported. If this field has any text, BBT will not override this text. I do not know how to make this any clearer. If there is text in the `Journal Abbrev` field, BBT will use that as the journal abbreviation. Only if that field is not filled for a reference will the auto-abbreviator come into action. This is by design and will not change.

Can you explain what you are seeing that is counter to your expectations? Would you have expected BBT to replace the journal abbrev even though it has been provided (not going to happen)? Something else? I am at a loss here to understand what you expect.

**Comment by retorquere** [comment]
If the field which I've marked in red here has text, that *is* the journal abbreviation (I can't help it if the abbreviation is wrong), and BBT will always use that instead of auto-abbreviating.

![screenshot from 2017-12-29 20-49-30](https://user-images.githubusercontent.com/132108/34446321-60f93056-ecda-11e7-90fe-0cfa3749bd36.png)

**Comment by kuangyia** [comment]
Yeah, you have gotten what I had gotten. In the above reference, I expected to get 'journal = {Physica E}' after exported to note by Zotero via BBT. Nevertheless, it did not work automatically as expected (but now I understand why after you explained). To be honest, I really want Zotero to fix this problem, then it can be more powerful and useful.

**Comment by retorquere** [comment]
Right, this is a more general issue of how to detect quality problems with references in general so they can be corrected. It's not something in the domain of responsibility of BBT, and a solution to this would be of use to regular Zotero users as much as it would benefit BBT users.

**Comment by retorquere** [comment]
You can enable [quality report](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#include-comments-about-potential-problems-with-the-references) for some hints about the references, BTW.

**Comment by retorquere** [comment]
Can this issue be considered resolved?

**Comment by retorquere** [comment]
I've not seen anything presented that isn't BBT acting as it's designed to do; if my assessment is wrong, feel free to re-open.
