### ISSUE TITLE
Include first name initial(s) in cite key generation pattern

### ISSUE THREAD

**Issue by rtwld** [retorquere/zotero-better-bibtex#86]
Is there a way to specify the first name initial(s) of the author(s) in the pattern citekey generator?

Eg.  

David Lewis 1960 -> `LewisD1960` (or `DLewis1960`)
Clarence Irving Lewis 1960 -> `LewisCI1960` (or `CILewis1960`)

The [JabRef generator](http://jabref.sourceforge.net/help/LabelPatterns.php) doesn't readily give such an option. And Zotero's `Creator` field doesn't either. But Zotero's data model knows about given names, as seen in the [name disambiguation feature](https://www.zotero.org/support/kb/given_name_disambiguation). Maybe there's a way to tap into that information?

**Comment by retorquere** [comment]
Hey @rtwld, could you take a look at #460? The changes made there would render your reference as

```
@article{HuF2014,       
  abstract = {Let X be a projective variety which is algebraic Lang hyperbolic. We show that Lang's conjecture holds (one direction only): X and all its subvarieties are of general type and the canonical divisor K\_X is ample at smooth points and Kawamata log terminal points of X, provided that K\_X is Q-Cartier, no Calabi-Yau variety is algebraic Lang hyperbolic and a weak abundance conjecture holds.},
  archivePrefix = {arXiv},
  author = {Hu, Fei and Meng, Sheng and Zhang, De-Qi},
  eprint = {1407.5694},
  eprinttype = {arxiv},
  keywords = {32Q45 Hyperbolic and Kobayashi hyperbolic manifolds; 14E30 Minimal model program (Mori theory; extremal rays),Mathematics - Algebraic Geometry,Mathematics - Complex Variables,Mathematics - Differential Geometry},
  month = jul,
  note = {\url{http://arxiv.org/abs/1407.5694}},
  primaryClass = {math},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {Ampleness of Canonical Divisors of Hyperbolic Normal Projective Varieties},
  urldate = {2014-08-11},
  year = {2014}
}
```

would that still be OK for your case?
