### ISSUE TITLE
Automatic update of the citation keys (BibTex keys) with Zotero 5.0.33

### ISSUE THREAD

**Issue by NaoBerlin** [retorquere/zotero-better-bibtex#861]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Hello everyone, 

I hope this is the right place to ask that. I'm using Zotero and then export my references for LaTeX with BetterBibTeX as a .bib file. Zotero used to automatically name the BibTex keys for my references this way: goffman_forms_1981, i.e. author_firstwordofthetitle_year. Zotero has been automatically updated to 5.0.33 and all the citation keys have changed. I'm currently writing my thesis and I have hundreds and hundreds of references that now need to be updated in my text. Thus I would like to know how to change the automatic bib keys in Zotero to reinstall the previous format. I have downloaded the add-on for that purpose, but I am still experiencing problems. 

I have changed the code to write this in Zotero: `[auth]_[veryshorttitle]_[year]`

It partly works, yet the first letter of the author's name and of the title are in capital letters (for instance, Goffman_Forms_1981) while it was in lower case before. I have also noticed some conflicts when the first word of the title is not the 'key word', as in: ducrot_les_1980 that has become Ducrot_mots_1980 (the title is: Les mots du discours). 

**I also have problems with names with particles (such as "de" or "von"). They used to be indicated as follows: de_cock_profiling_2014. Now they are: DeCock_Profiling_2014.**  

This results in conflicts with my LaTeX files and the references are not recognised anymore. 

My questions are the following: 
- how can I have the exact same citation keys I had before the update, i.e. only lower case and first word of the title? 
- how can I change ALL the citation keys in my Zotero library at once? I have 4000 references, and even though I don't use them all for my dissertation, it would cost me an extensive amount of time to refresh each single citation key by hand. I have already tried selecting all the references, right-click on "Refresh BibTex key", but it did not work. 

Thank you very much in advance! 
A PhD student quite stressed despite the New Year :)

-------------

If your bug report/feature request/question concerns problems with exporting references, please specify whether you're exporting BibTeX or BibLaTeX. 
> In texmaker (using Mac OS), I click on "BibTeX" when I want to update the references. Does it answer the question?

**Comment by retorquere** [comment]
You should have gotten a popup warning about this; I'll have more questions later, but for the interim, set your pattern to `[zotero:clean]`, select your references, right-click and select "refresh".

Starter questions:
1. When you say "Zotero has been updated", what version did you come from?
2. Did you previously use Zotero BibTeX or Better BibTeX for exports?
3. Did you see a popup warning about key changes?

**Comment by NaoBerlin** [comment]
Hello, thank you very much for your quick answer. 

1. When you say "Zotero has been updated", what version did you come from?
> I don't know, I assume the previous one. The update started this morning automatically when I opened Zotero (I work with it every day). 

2. Did you previously use Zotero BibTeX or Better BibTeX for exports?
> I downloaded the add-on only today, so I assume I used to use BibTex, but I'm not sure.

3. Did you see a popup warning about key changes?
> Yes. Here is a screenshot. 
![screenshot 2018-01-02 10 37 48](https://user-images.githubusercontent.com/27682526/34482780-872d7006-efba-11e7-9c76-323f909f6dcb.png)

I hope this partly answers your questions...

**Comment by NaoBerlin** [comment]
@retorquere I am sorry, but I don't understand what "set your pattern to [zotero:clean]" means. What should I concretely do? Where should I click?

**Comment by NaoBerlin** [comment]
@retorquere Hey, so I googled it and it made me wiser :) 
I found a previous thread in Zotero: https://forums.zotero.org/discussion/69423/citation-keys-changed. I've done what has been suggested, i.e. [auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year], and this is good!!

But, still one issue: 
I also have problems with names with particles (such as "de" or "von"). They used to be indicated as follows: de_cock_profiling_2014. Now they are: DeCock_Profiling_2014. (I have underlined this sentence in my first post). 
> The new code gave this: decock_profiling_2014.

**Comment by retorquere** [comment]
Just enter `[zotero:clean]` where you entered that long pattern and refresh your keys.

I'm going to device a way to make the popup at first run clearer. Not wholly sure how yet. Any tips? 

There's no "everyone" BTW, just me.

**Comment by retorquere** [comment]
You have no idea what Zotero version you used before this? Do you know if you were on an 4 release, or on a 5 release before you upgraded? And did you previously use BBT to export bibtex, or just zotero?

**Comment by NaoBerlin** [comment]
Well, hello @retorquere only then, and thank you so much for your help! 

I've just tried what you have suggested `[zotero:clean]` and it seems to work. I have only tested it on a few references, though, because I've just noticed that with the code `[auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year]`, "only" 119 references are different when compiling my LaTeX file. I am considering re-write them manually in my LaTeX document, because it seems that Zotero was automatically giving a key that was sometimes incoherent. 

To answer your questions: 
- I'm going to device a way to make the popup at first run clearer. Not wholly sure how yet. Any tips?
> You mean the message from the screenshot I've sent before? Maybe just say: "If you want the old citation keys back, go to `Preferences / Better BibTexKey / Citation key format` and write `[zotero:clean]`. This only would have spared me a lot of stress :) 

- You have no idea what Zotero version you used before this? Do you know if you were on an 4 release, or on a 5 release before you upgraded?
> I unfortunately *really* have no idea, but if you tell me where I might find this info in my previous TimeMachine backups, I'll be happy to have a look. 

- Did you previously use BBT to export bibtex, or just zotero?
> Nope, just Zotero. I downloaded and installed the add-on the morning only. 

Conclusion: 
- From your side, I think the problem is already solved. 
- From my perspective, I'm happy I discovered the existence of BBT today because it raised awareness on how citation keys should or shouldn't be, and it seems I've been too confident in Zotero only before. Unfortunately, my thesis is too advanced to consider having a `[auth:lower][year]` code as you suggest on the page on citation keys, but I'll keep that in mind for later. 

And a final question: 
What's the difference between `[auth:fold:lower]` and `[auth:lower]`? I can't see any.

**Comment by retorquere** [comment]
Alright, to get back to the first premise of this issue:

> Automatic update of the citation keys (BibTex keys) with Zotero 5.0.33

BBT did not (could not) update the citation keys you were using. If you export with "BibTeX" (which is Zotero BibTeX, and is still available when BBT is installed), you will get your keys as you had them. 

> I've just tried what you have suggested [zotero:clean] and it seems to work. I have only tested it on a few references, though, because I've just noticed that with the code [auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year], "only" 119 references are different when compiling my LaTeX file. I am considering re-write them manually in my LaTeX document, because it seems that Zotero was automatically giving a key that was sometimes incoherent.

`[auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year]` was an early attempt to replicate the standard Zotero-generated keys. That didn't always work, so I added `[zotero]`, which exactly replicates the Zotero-generated keys. Those occasionally have edge cases; `[zotero:clean]` removes the edge-case characters. So if you have existing papers that used the standard Zotero-generated keys, `[zotero:clean]` is the recommended pattern.

> I unfortunately really have no idea, but if you tell me where I might find this info in my previous TimeMachine backups, I'll be happy to have a look.

That's OK, I now know you've just ran BBT for the first time. The behavior you see is the expected behavior (at least for now).

> From my perspective, I'm happy I discovered the existence of BBT today because it raised awareness on how citation keys should or shouldn't be, and it seems I've been too confident in Zotero only before.

I wouldn't say that. Standard Zotero BibTeX (and the keys it generates) is serviceable. The BibTeX BBT generates is, well, better, and duplicate key handling is better.

> Unfortunately, my thesis is too advanced to consider having a [auth:lower][year] code as you suggest on the page on citation keys, but I'll keep that in mind for later.

No need. This is my personal preference only, and I only recommended away from it because I ran into trouble with Zotero-generated keys. With `[zotero:clean]` that problem does not exist.

> What's the difference between [auth:fold:lower] and [auth:lower]? I can't see any.

See https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#filters

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5264](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.65.5264.issue-861.xpi) ("onboarding").
