### ISSUE TITLE
getting BBT working on Zotero-Linux 

### ISSUE THREAD

**Issue by baradhili** [retorquere/zotero-better-bibtex#862]
- [X] I am on the latest release of BBT and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing

# Bug classification
User problem most likely, I have installed BBT for Zotero and it appears in the preferences.
However drag and drop the ref into TexStudio and I get a literal citation, not the Tex \cite entry - eg `Pulse+IT Magazine. Our Digital Hospital Journey with the Lorenzo EMR. Accessed January 1, 2018. https://www.youtube.com/watch?v=UyWGrk8ZQ6Q.`
. Use "Push references to TexStudio" under the context menu and I get a \cite, but it doesn't obey the settings under the BBT prefs. eg prefs for Latex command is autocite, but Zotero puts cite

Exporting the collections gives me valid bibtex which I convert to biber via "biber --tool items.bib"
However the refs don't see to obey the BBT keys and don't match what is pushed to TexStudio
eg.
```
@VIDEO{pulse+it_magazine_our_????,
  AUTHOR = {{Pulse+IT Magazine}},
  KEYWORDS = {Byron Phillips, {CSC}, Dr Mark Simpson, {EMR}, Hull and East Yorkshire Hospitals {NHS} Trust, Lorenzo, 
Paul Wallbank, Pulse+{IT}, Webinars},
  NOTE = {bibtex: Pulse+{ITMagazineOurDigitalHospital}},
  TITLE = {Our Digital Hospital Journey with the Lorenzo {EMR}},
  URL = {https://www.youtube.com/watch?v=UyWGrk8ZQ6Q},
  URLDATE = {2018-01-01},
}
```
I'm sure I've stuffed up something basic... any suggestions?

Thanks

**Comment by retorquere** [comment]
For the drag-and-drop, make sure you have set up Zotero to use BBT to generate the output: https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys#drag-and-drophotkey-citations

For TeXStudio, BBT can only push the citation keys to TeXstudio; how TeXstudio handles those is apparently configurable on the TeXstudio side; I don't use it myself, but see the [manpage](http://manpages.ubuntu.com/manpages/wily/man1/texstudio.1.html) under `--insert-cite`. You will have to ask the TeXstudio people about how this actually works.

**Comment by retorquere** [comment]
As to the export, it looks like you're using "BibTeX" for the export (which is Zotero's bundled BibTeX) rather than "Better BibTeX" (which is BBTs BibTeX generation). I'm working on better on-boarding.

**Comment by baradhili** [comment]
Thanks that fixed it :)..
