### ISSUE TITLE
Missing preferences menu in 5.0.66

### ISSUE THREAD

**Issue by melsophos** [retorquere/zotero-better-bibtex#865]
In the last version (5.0.66) the preferences tab for Better Bibtex is missing in Zotero's preferences. Restarting, disabling/reinstalling does not change anything. Reverting to 5.0.65 restores the menu.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5273](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.66.5273.issue-865.xpi) ("New Crowdin translations (#864)\n\n* New translations zotero-better-bibtex.dtd (French)\r\n\r\n* New translations zotero-better-bibtex.properties (French)").

**Comment by retorquere** [comment]
Were you on the French version by any chance? If so, could you try 5273?

**Comment by melsophos** [comment]
Yes I am indeed with the French version. 5273 fixes the problem. Thank you for the rapid feedback!

**Comment by retorquere** [comment]
Thanks for reporting this. .67 will be out momentarily which will have this fix.
