### ISSUE TITLE
translating zotero item types in postscript?

### ISSUE THREAD

**Issue by baradhili** [retorquere/zotero-better-bibtex#866]
- [x ] I am on the latest release of BBT and Zotero
- [ x] I am posting a single question, bug or feature request
- [ x] I have included a descriptive subject of the problem
- [ x] I am available for follow-up questions and testing

# Bug classification
User question, exporting to Biblatex

Hi, I have some emails in my reference collection and trying to get them into Biblatex, Zotero-BBT exports them as LETTER, however biblatex doesn't know of a Letter type.. 
Is it possible for me to translate 
```
@LETTER{BloggsFredcontactingS4S2016,
  AUTHOR = {Bloggs, Fred},
  DATE = {2016-06-17},
  TITLE = {Contacting {{4uk}}},
}
```

Into
```
@MISC{BloggsFredcontactingS4S2016,
  AUTHOR = {Bloggs, Fred},
  DATE = {2016-06-17},
  TITLE = {Contacting {{4uk}}},
  HOWPUBLISHED = {private communication},
}
```

Using the postscript js?

Thanks

**Comment by njbart** [comment]
From the biblatex manual: “2.1.3 Unsupported Types […] When using the standard styles, [the types in this section] will be treated as `@misc` entries.” `@letter` is listed in this section, so I can’t see why the item type should pose a problem at all.

**Comment by retorquere** [comment]
But if you must you can do

```
if (Translator.BetterBibLaTeX && this.referencetype === 'letter') {
  this.referencetype = 'misc'
}
```

but as @njbart suggested, I'd only do this when you have actual problems.

**Comment by retorquere** [comment]
BTW the sample you posted is most likely produced by Zotero bibtlaex, not bbt biblatex.

**Comment by retorquere** [comment]
No, wait, those citekeys can't have been generated by Zotero bibtex. But BBT bibtex has lowercase field names. How did you get this reference?

**Comment by baradhili** [comment]
sorry for the delay, I'm running biber, so once its exported from BBT I need to run biber --tool xxx.bib 

I suspect the problem might be upstream from zotero though. thanks :)

**Comment by retorquere** [comment]
I don't understand. Is your question resolved?

**Comment by baradhili** [comment]
you can mark it as resolved, from BBT's standpoint
