### ISSUE TITLE
import/retain Jabref fields and groups

### ISSUE THREAD

**Issue by steffen-o** [retorquere/zotero-better-bibtex#870]
Hi,

first of all - thank you for this great enhancement for Zotero!

My working group has a very large bibtex literature database that is managed with jabref. We now want to migrate it to a zotero group library. Unfortunately some jabref fields are not supported/imported.

Would it be possible to retain some fields of jabref (e.g. groups, timestamp [jabref]) in the "extra" field in Zotero (similar to the citekey)?
Thank you!

**Comment by retorquere** [comment]
Group information should already be mostly retained; BBT does not (and will not) support query-based groups, but simple groups including exclusions are (should be at least) imported as Zotero collections.

And as far as I can recall, unmapped data is already retained in the `extra` field. Do you have a (preferably simple/small) sample where either the groups import or the unmapped-to-extra fails?

**Comment by steffen-o** [comment]
Maybe I did it wrong (I only recently started to use Zotero and Jabref) but the groups from Jabref are not imported into the collections. Zotero just puts all entries in a collection with the filename of the bib. It would save me a lot of time if that was possible but I suspect it is not that easy.
I attached a Bib file with 10 entries. When I import them in Zotero they are put in a collection "test4zotero"; the fields **bibtexkey** and **owner** and for some entries **database** are retained in the Zotero `extra` field. 
The **groups** and the original jabref **timestamp** seem to be lost.

[test4zotero.zip](https://github.com/retorquere/zotero-better-bibtex/files/1619379/test4zotero.zip)

Thanks a lot for your help!

P.S.: I also reexported these entries to jabref :  the **groups** are lost and the **timestamp** is the date of the import into zotero.

**Comment by retorquere** [comment]
Oh wonderful, Jabref has decided to change their groups format again.

**Comment by retorquere** [comment]
What version of Jabref produces this?

**Comment by steffen-o** [comment]
Jabref 4.1

**Comment by retorquere** [comment]
BBT ignores a few fields on import as Zotero has an equivalent field but it's not possible for a translator to set it: `date-modified`, `date-added`, `added-at` and `timestamp`. There's an [open request](https://github.com/zotero/zotero/issues/1229) on the Zotero tracker to change this.

I'm looking into the groups, but the format is not documented.

**Comment by retorquere** [comment]
I'm working with the parser authors on the new JR format [here](https://github.com/fiduswriter/biblatex-csl-converter/issues/84).

**Comment by retorquere** [comment]
This is straight from JabRef? In `Osmanski2011` there's a bare `%` in the abstract -- AFAIK, this is an error and should have been `\%` (@njbart ?)

**Comment by njbart** [comment]
At least in biblatex, an unescaped `%` in an abstract definitely causes an error.

**Comment by retorquere** [comment]
I thought so, yet it's surprisingly common to find them.

**Comment by retorquere** [comment]
But I'd have expected JabRef to have taken care of these, TBH.

**Comment by retorquere** [comment]
5.0.73 is out which should retain JabRef 4.1 group information. Can you try that?

**Comment by steffen-o** [comment]
Yes, it is a direct export from Jabref. As far as I know there were no problems - at least there are no errors in Jabref nor in Zotero nor in Texstudio

**Comment by steffen-o** [comment]
The new Release works fine!! All groups are imported. Thank you so much!!

**Comment by retorquere** [comment]
It will depend on where the `%` is in the reference; if it is the last field, biber (or other bibtex parsers) may not recover, but I've seen biber recover if it's somewhere in the middle. But it's not valid bibtex; I thought JabRef actively checked or changed such things, but it looks then that that isn't the case.

BBT will parse `%` and `\%` the same. Try importing your references with 5.0.73, and let me know how it goes.

**Comment by retorquere** [comment]
Ah sorry, crossed messages there :)

**Comment by retorquere** [comment]
OK, cool, so the groups aspect is fixed. WRT the `timestamp` field I'd *really* prefer to have https://github.com/zotero/zotero/issues/1229 fixed, at which point I could just import the `timestamp` and have them properly reflected in Zotero. Are you OK with this approach?

**Comment by steffen-o** [comment]
Works for me. Thank's again!
