### ISSUE TITLE
Issues with round instead of curly braces do not import correctly

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#871]
@njbart is this a valid bibtex reference?

```
@Article(py03,
     author = {Xavier D\'ecoret},
     title  = "PyBiTex",
     year   = 2003
)
```

http://artis.imag.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html seems to say it is.

**Comment by njbart** [comment]
Yep. (Valid biblatex, too.)

**Comment by retorquere** [comment]
This is only for the reference itself, right? Not the fields.

**Comment by njbart** [comment]
Just the reference itself.
