### ISSUE TITLE
Auto-pin citation keys in Z5

### ISSUE THREAD

**Issue by ionm** [retorquere/zotero-better-bibtex#875]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

I'm running the latest instalments of BBT (5.0.73) and Zotero (5.0.34). I have just noticed that BBT doesn't have anymore the option for Auto-pin citation keys "on export" or "on change". Is this a feature which was dropped altogether? I am slightly confused because [in your documentation](https://github.com/retorquere/zotero-better-bibtex/wiki/Citation-Keys) (last revised on 11/20/2017) you still talk about the "on export" and "on change" options.

**Comment by retorquere** [comment]
I'm still working on updating the documentation after the port, but indeed, pin-on-export is not in the Z5 port.
