### ISSUE TITLE
book section -> biblatex: incollection or inbook?

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#877]
@njbart, is there a reason I should prefer to translate Zotero "Book Section"s to `incollection` (current behavior) rather than `inbook`?

**Comment by retorquere** [comment]
Also, for an `inbook`, what's the difference between `title` and `chapter`.

**Comment by njbart** [comment]
From the biblatex manual: 

“`book` – A single-volume book with one or more authors where the authors share credit for the work as a whole.”

“`inbook` – A part of a book which forms a self-contained unit with its own title. Note that the profile of this entry type is different from standard BibTeX, see § 2.3.1.”

“`collection` – A single-volume collection with multiple, self-contained contributions by distinct authors which have their own title.  The work as a whole has no overall author but it will usually have an editor.”

“`incollection` – A contribution to a collection which forms a self-contained unit with a distinct author and title.  The author refers to the title, the editor to the booktitle, i. e., the title of the collection.”

In practice, incollection items vastly outnumber inbook items, so incollection certainly is a sensible default.

If you wish to distinguish between these two, a simple rule is, if in Zotero there is a bookauthor, then it’s a biblatex `inbook`.

`chapter` is usually the chapter number. In the formatted output of plain biblatex, it appears at the end of the entry, prefixed by “Chap. ”.

**Comment by retorquere** [comment]
Cool -- I already do `inbook` on `bookauthor`.
