### ISSUE TITLE
Better BibTeX export not selectable

### ISSUE THREAD

**Issue by Aesara** [retorquere/zotero-better-bibtex#881]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

BetterBibTeX version: 5.0.74
Zotero version: 5.0.34
OS: Windows 10

I am facing a similar issue as #880 : no citation keys are generated. But even though I installed Better BibTeX (it shows up as a add-on and also in the Zotero Preferences pane), I cannot choose to export to Better BibTeX (instead of just BibTeX or BibLaTeX). 

By this I mean that I can neither select Better BibTeX as `Default Format` in the Zotero `Export` pane, nor select Better BibTeX in the `Format` field of the` Export ` pane that opens when I right-click on a collection and select "Export collection", since the "Better BibTeX" option is not displayed.

Since I am not actually able to export using Better BibTeX, this probably also explains the other problems I have, namely
1. when I add my custom key in the `Extra` field (e.g. "bibtex: Example001"), upon exporting (choosing either BibTeX or BibLaTeX as format), a different key is generated, i.e. my key is not used 
2. even though I selected the ​[auth:lower][year] key-format in the Better BibTeX preferences pane, it still exports them in the format _author_simplifiedTitle_year_ 
3. when selecting "Pin BibTeX key", "Refresh BibTeX key", or "Unpin BibTeX key" after right-clicking on an item, nothing happens

Thank you for your response

**Comment by retorquere** [comment]
Can you also try https://github.com/retorquere/zotero-better-bibtex/issues/880#issuecomment-357908922

**Comment by Aesara** [comment]
I get the following: 



(3)(+0000000): {better-bibtex} Trying to find TeXstudio:
{"platform":"win32","pathsep":";","dirsep":"\\"}

(1)(+0000003): NS_ERROR_FILE_UNRECOGNIZED_PATH Exception: Component
returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)
[nsILocalFile.initWithPath]
Zotero.File</this.pathToFile@chrome://zotero/content/xpcom/file.js:46:12
Zotero.BetterBibTeX<["./tex-studio.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:3085:17
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 Zotero.BetterBibTeX<["./BetterBibTeX.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:1445:25
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 webpackJsonpCallback@chrome://zotero-better-bibtex/content/common.js:26:23
@chrome://zotero-better-bibtex/content/BetterBibTeX.js:2:1

(3)(+0000000): Error: BBT: load of content/tex-studio.ts failed:Error:
Unexpected value
'\texstudio'::Zotero.File</this.pathToFile@chrome://zotero/content/xpcom/file.js:55:9
Zotero.BetterBibTeX<["./tex-studio.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:3085:17
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 Zotero.BetterBibTeX<["./BetterBibTeX.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:1445:25
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 webpackJsonpCallback@chrome://zotero-better-bibtex/content/common.js:26:23
@chrome://zotero-better-bibtex/content/BetterBibTeX.js:2:1

(3)(+0000000): BBT: loading content/cayw.ts

(3)(+0000000): BBT: loading content/cayw/formatter.ts

[Debug Output.txt](https://github.com/retorquere/zotero-better-bibtex/files/1634581/Debug.Output.txt)

**Comment by retorquere** [comment]
OK, same problem as #880. Can you please join us there?
