### ISSUE TITLE
BBT add-on not compatible with Firefox 57.0.4

### ISSUE THREAD

**Issue by Algebreaker** [retorquere/zotero-better-bibtex#886]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug description
I just tried to install the BBT add-on and seem to be getting an error message saying that it's incompatible with Firefox version 57.0.4. Is this a known issue?

**Comment by retorquere** [comment]
https://www.zotero.org/blog/zotero-5-and-firefox-faq/
https://github.com/retorquere/zotero-better-bibtex/issues/838
