### ISSUE TITLE
Preserve Capitalisation?

### ISSUE THREAD

**Issue by RafalSkolasinski** [retorquere/zotero-better-bibtex#888]
What option is responsible for capitalisation of titles?

All my entries in library have capital letters as it should be. So far export with better bibtex was giving me e.g.
```
title = {New {{Method}} for {{High}}-{{Accuracy Determination}} of the {{Fine}}-{{Structure Constant Based}} on {{Quantized Hall Resistance}}}
```
Now however it is 
```
title = {New Method for High-Accuracy Determination of the Fine-Structure Constant Based on Quantized Hall Resistance}
```

How can I force it to add braces? I do not want to edit 200 entries by hand...

**Comment by RafalSkolasinski** [comment]
Seems that capitalisation doesn't work properly when ``#LaTeX`` tag is set.
How one can force it to work with #LaTeX?

**Comment by retorquere** [comment]
Given that `#LaTeX` means "my reference has literal LaTeX, don't touch it", no.

**Comment by retorquere** [comment]
Why would you want braces for this reference in any case? That seems like the right bibtex to me? Styles will re-capitalize as needed.

**Comment by RafalSkolasinski** [comment]
I have a lot of entries, most of them mixing in titles formulas with words that must be capitalised. 
I grabbed them from PRL, PRB, or whatever journal webpages using Zotero. 

Example title in Zotero would be: ``$\boldsymbol{k}\cdot\boldsymbol{p}$ studies on InAs/GaSb quantum wells``. 

Now if I do not use ``#LaTeX`` tag the ``InAs/GaSb`` is properly capitalised but I loose math. 
If I use ``#LaTeX`` then math is correct but ``InAs/GaSb`` is all lowercase. \

I am not aware on doing it with document styles. What I was usually doing, and it was working on small paper-size bibliographies, was to add {} by hand in final document. But now I work on thesis and it's just too much to fix by hand. 

It would be cool if on export one could preserve both math and capitalisation.

**Comment by retorquere** [comment]
You can preserve math (or anything else `LaTeX`) by wrapping it in `<pre>...</pre>`. It's possible to automate this using a [postscript](https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting#detect-latex-math-formulas), but you will have to be on the lookout for titles that actually do legitimately include multiple `$` signs.

**Comment by retorquere** [comment]
(that is, of you use `<pre>...</pre>`, anything inside that is treated as if `#LaTeX` was set, everything outside it as if it isn't).

**Comment by RafalSkolasinski** [comment]
Ok, thanks for the tip. I'll keep it in mind for later.
Right now I will just export everything with ``#LaTeX`` and use some script to add extra ``{}`` around the whole title in my ``.bib`` file; or use sublime. I do not want to manually edit over 200 entires ;)

**Comment by retorquere** [comment]
That's cool, but with the postscript you wouldn't have to.

**Comment by retorquere** [comment]
Can we close this issue?
