### ISSUE TITLE
Month showing up in year field on export

### ISSUE THREAD

**Issue by rcoreilly** [retorquere/zotero-better-bibtex#889]
- [X] I am on the latest release of BBT and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing

# Bug classification

I have a number of references that have a Date field in Zotero as something like "08 1995" (e.g., see debug data I sent you) -- this gets exported to my .bib file intact as: year = {08 1995} (see example output below).

Clearly the 08 is a month, but zotero itself parses this as "d y" in the date field.  In any case, I don't care about the month, I just want the year to export without the month there, as it messes up my citations etc.  This used to not be an issue with the previous 4.x version (same database).

@article{HoukWise95,
  title = {Distributed Modular Architectures Linking Basal Ganglia, Cerebellum, and Cerebral Cortex: {{Their}} Role in Planning and Controlling Action.},
  volume = {5},
  number = {2},
  journal = {Cerebral Cortex},
  author = {Houk, J. C. and Wise, S. P.},
  year = {08 1995},
  pages = {95--110},
  file = {/Users/oreilly/Zotero/storage/DJUQINI6/HoukWise95.pdf}
}

BTW export time is quite fast now that I'm using it regularly and have the cache primed..

## Exporting references

If your bug report/feature request/question concerns problems with exporting references, please specify whether you're exporting BibTeX or BibLaTeX. Please right-click the references where you experience the export problem, select "Send Better BibTeX Error", and post the resulting report ID (shown in red after you submit) here.

BXSY966N

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5432](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.78.5432.issue-889.xpi) ("fixes #889").

**Comment by retorquere** [comment]
Can you try 5432?

**Comment by rcoreilly** [comment]
Yep that fixes it! :)

**Comment by retorquere** [comment]
Thanks for the confirmation, release is in its way.
