### ISSUE TITLE
Auto pin option?

### ISSUE THREAD

**Issue by rcoreilly** [retorquere/zotero-better-bibtex#890]
- [X] I am on the latest release of BBT and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing

# Bug classification

Would it be possible to add an option to auto pin the key when a new item is added, and a new key is first generated?  We prefer to always have the keys pinned so they show up in the extra field when viewing on the web, and in general to ensure consistency across users of our shared lib.  Thanks!

**Comment by retorquere** [comment]
I'll have a look. It's not as easy as it used to be, so this will probably get done somewhere after next week -- no guarantees. My life got flipped-turned upside down lately.

**Comment by retorquere** [comment]
Can you try 5745? You'll have to enable the hidden `autoPin` setting.

**Comment by rcoreilly** [comment]
hmm -- didn't seem to work -- I enabled that setting in the config editor, restarted zotero, and grabbed a new reference, and it wasn't pinned automatically...

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5832](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.94.5828.issue-890.xpi) ("Merge branch 'master' into 890").

**Comment by retorquere** [comment]
Oh great, patching the save function doesn't always work. I have another option, but it's slower. Try 5832.

**Comment by rcoreilly** [comment]
yep that works! :)

**Comment by retorquere** [comment]
Alright, should drop in a few minutes.

**Comment by rcoreilly** [comment]
btw are you going to add the autoPin option to a visible place in the preferences??  obviously would make it easier for others to find it..

**Comment by retorquere** [comment]
I'm not sure yet. Z5 makes auto-pin a potential cause for race conditions, and I need to think more about potential edge cases.
