### ISSUE TITLE
Citekeys without a date don't work in Pandoc

### ISSUE THREAD

**Issue by MageJohn** [retorquere/zotero-better-bibtex#891]
If an entry doesn't have a date, then four question marks, ????, are appended instead. However this makes it an invalid citation key in Pandoc. Sometimes I just can't find a date for something, and I've had to manually set a cite key in order to use it. Perhaps a better idea would be to use 'nd' instead (for 'no date').

**Comment by retorquere** [comment]
If you're getting the question marks, you probably have the pattern set to `[zotero]`; that pattern faithfully implements the citation keys as Zotero itself does, warts and all. You could try setting the pattern to `[zotero:clean]` (which should remove the question marks) or something like `[auth][shorttitle][year]`.

**Comment by MageJohn** [comment]
Thanks! It turns out I'm using `[zotero:clean]` already, however. `[auth][shorttitle][year]` works, but it changes all my cite keys to not have underscores, which, while not as bad as it could be as I'm not as heavy a user as some, is still a hassle. If I change it to `[auth]_[shorttitle]_[year]` it's almost right, but `[shorttitle]` doesn't seem to be quite the same as the title used by `[zotero:clean]`.

**Comment by retorquere** [comment]
I have a fix but my releases are not being uploaded right now. I'm looking into that.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5447](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.79.5447.issue-891.xpi) ("Merge branch 'master' into 891").

**Comment by retorquere** [comment]
Finally. Can you try 5447?

**Comment by retorquere** [comment]
I mean can you try 5447 with `[zotero:clean]`?

**Comment by MageJohn** [comment]
Oops. sorry I took so long to reply. Just tested this, and it works great! Thanks so much for fixing it.

**Comment by retorquere** [comment]
cool, thanks for the confirmation. Now just feedback from #892 and I can cut a new release.
