### ISSUE TITLE
creating a key with [authForeIni] and [authN] not working properly

### ISSUE THREAD

**Issue by tobi2192** [retorquere/zotero-better-bibtex#892]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [ ] I am available for follow-up questions and testing

I'm running on Zotero Better BibTex 5.0.78 with Zotero 5.0.34.4 on MacOS High Sierra. With the firefox extension I created my cite keys like this: 

[authForeIni:upper][auth2:upper][shortyear]

This should give me the first letter of the authors forename and the first two letters of the authors lastname in uppercases along with the last to digits of the year. Unfortunally now it gives me two times the first letter of the authors forename along with the last to digits of the year.

For example "Otto Forster: Analysis 1. Differential- und Integralrechnung einer Veränderlichen. Wiesbaden 2013." should be OFO13 but it actually is OO13.

> If your bug report/feature request/question concerns problems with exporting references, please specify whether you're exporting BibTeX or BibLaTeX. **Please right-click the references where you experience the export problem, select "Send Better BibTeX Error", and post the resulting report ID (shown in red after you submit) here.**

**Comment by retorquere** [comment]
Can you right-click the reference where this happens and select "send better bibtex error"? If you post the ID you get at the end of that wizard here I'll have the reference so I can test.

**Comment by retorquere** [comment]
In what sense does `authForeIni` not work?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5455](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.79.5455.issue-892.xpi) ("test for #892").

**Comment by retorquere** [comment]
I think 5455 fixes the problem; if you could verify, I can wrap that into a release. I'd also *really* still like that report, as it will give me your settings + the reference you experienced this with, and I want to add those to my test suite so the problem can't reappear.

**Comment by retorquere** [comment]
I could really use feedback (and the debug log), I'm looking to cut a new release and I'd like to include this.

**Comment by tobi2192** [comment]
Sorry for the late feedback. Now its working properly. Thanks a lot!

**Comment by retorquere** [comment]
Super. Can I still get a debug report from that reference? Then I can add it to my test suite.

**Comment by tobi2192** [comment]
How can I create one?

**Comment by retorquere** [comment]
right-click the issue, "send bbt error rfeport", post ID here

**Comment by tobi2192** [comment]
292CND9L this one?

**Comment by retorquere** [comment]
Yep, thanks.

**Comment by retorquere** [comment]
```
@book{FMO14,
  address = {Berlin [u.\textasciitilde{}a.]},
  author = {Modler, Florian and Kreh, Martin},
  edition = {3. Aufl.},
  isbn = {978-3-642-37365-7},
  language = {ger},
  publisher = {{Springer}},
  shorttitle = {{Tutorium}},
  title = {{Tutorium Analysis 1 und Lineare Algebra 1. Mathematik von Studenten f{\"u}r Studenten erkl{\"a}rt und kommenteiert}},
  year = {2014}
}
```

looking good?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5464](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.79.5464.issue-892.xpi) ("test case for #892").

**Comment by tobi2192** [comment]
yeah, looks good
