### ISSUE TITLE
Stuck at Starting key manager

### ISSUE THREAD

**Issue by fruchtblase** [retorquere/zotero-better-bibtex#894]
Hi,

first of all, thank you for your excellent extension and all the work you put into making it! 

When I'm starting Zotero Better Bibtex gets stuck at "Starting key manager".  After a while Zotero displays the "An error has occured" message. I'm on Linux Mint 18.3.

Unfortunately reporting better bibtex errors doesn't work on my machine; the enabled debug output isn't registered by the program for some reason (reporting to the zotero devs does work). I copied the output manually to this gist: https://gist.github.com/fruchtblase/585899212c2a3e1eb8c13c7e8c92a382
If you need further details, I'm happy to help!

**Comment by retorquere** [comment]
Which version of BBT do you have?

**Comment by fruchtblase** [comment]
I'm running 5.0.84

**Comment by retorquere** [comment]
Then I'll need a new log, the line numbers have likely changed.

**Comment by fruchtblase** [comment]
oh, sorry didn't mean to put up the old log
here's the current one:
https://gist.github.com/fruchtblase/42c52ddc39696fd058af27e5a057c9df

**Comment by retorquere** [comment]
Can you restart with debugging enabled from the help menu and capture a new log? I need to know if the errors we're seeing are collateral damage from some earlier error.

**Comment by fruchtblase** [comment]
Sure:
https://gist.github.com/fruchtblase/7d0bdf296e10483f56602b10dedc55b8

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5471](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5471.issue-894.xpi) ("async...").

**Comment by retorquere** [comment]
Can you try 5471? It really oughtn't make a difference, but Z5 is a really odd beast.

**Comment by fruchtblase** [comment]
Unfortunately, it didn't fix it. Here is a new log, hope that helps!
https://gist.github.com/fruchtblase/378c42b4ff717333163a101634e9b292

**Comment by retorquere** [comment]
This is the full log? I'm used to seeing such errors mentioned twice in the log, once at the top without stack trace (which is useless), and once with the stacktrace.

**Comment by fruchtblase** [comment]
Should be the full log. Did you click on "view the full file"?  Github truncates the output of long gists.

**Comment by retorquere** [comment]
I have the full log, but the TypeError (which is what causes BBT to flame out) is only present once. And unfortunately the error that is in the top of the log only indicates where it happens, but not the call stack, and this is a method that gets called a *lot*. It's not really useful to know that it happens there.

I'll see what I can think up.

**Comment by retorquere** [comment]
Can you get me a copy of the JSON file in the `better-bibtex` subdirectory of your Zotero data folder?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5474](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5474.issue-894.xpi) ("short-circuit old loki bug").

**Comment by fruchtblase** [comment]
there you go
[better-bibtex_dir.zip](https://github.com/retorquere/zotero-better-bibtex/files/1679875/better-bibtex_dir.zip)

**Comment by retorquere** [comment]
I forgot to say, Zotero needs to be stopped before capturing that directory as the relevant files are only written at shutdown. Can you also (with Zotero stopped) include the `better-bibtex.sqlite` file?

**Comment by retorquere** [comment]
Can you also try getting a debug log by starting Zotero with the `-ZoteroDebugText` command line parameter and redirecting what is being sent to stdout to a file? So something like `zotero -ZoteroDebugText  > logfile.txt`. That should get more from the early start of Zotero.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5502](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5502.issue-894.xpi) ("dump main DB after load").

**Comment by fruchtblase** [comment]
Logging with Zotero is strange, simply using > didn't catch the errors at all, because they are printed to stderr. 

This is the logfile I produced with `./zotero -ZoteroDebugText &> zoterolog.txt `:
[zoterolog.txt](https://github.com/retorquere/zotero-better-bibtex/files/1685277/zoterolog.txt)

Here are the `bibtex dir` and the `.sqlite` file, after Zotero shut down:
[better-bibtex.zip](https://github.com/retorquere/zotero-better-bibtex/files/1685182/better-bibtex.zip)
[better-bibtex.sqlite.zip](https://github.com/retorquere/zotero-better-bibtex/files/1685290/better-bibtex.sqlite.zip)

I hope this helps!

**Comment by retorquere** [comment]
Could you also install 5502, let it start, and get me the text file that's created in the better-bibtex directory?

**Comment by fruchtblase** [comment]
[better-bibtex.txt](https://github.com/retorquere/zotero-better-bibtex/files/1685608/better-bibtex.txt)

**Comment by retorquere** [comment]
There's an error in the underlying database library, I'm going through diagnosis with the maker of that lib, but the last file allows me to cleanly replicate the problem. Shouldn't be hard to fix now that we have it locally reproducible.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5506](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5506.issue-894.xpi) ("temporary fix for #894").

**Comment by retorquere** [comment]
Try 5506.

**Comment by fruchtblase** [comment]
it works!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5508](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5508.issue-894.xpi) ("cloneobjects").

**Comment by retorquere** [comment]
Sweet! Tests are running and I'm cutting a new release as soon as they go green.
