### ISSUE TITLE
cleanup markers end up in citation key

### ISSUE THREAD

**Issue by MatthewThomasMiller** [retorquere/zotero-better-bibtex#895]
I will apologize in advance if this is a stupid question, but I keep getting the following error message:

> Error reading bibliography /Users/MTM/Documents/ZoteroBibliography/Testlibrary3.bib (line 5527, column 10):
unexpected "\65533"
expecting white space
Error running filter pandoc-citeproc:
Filter returned error status 1

I have been using Pandoc with Zotero for citation for over a year and this only started happening today after I updated Pandoc, Zotero, and Better Bib(La)tex.

Attached is sample doc producing the error.
[TestText.txt](https://github.com/retorquere/zotero-better-bibtex/files/1680325/TestText.txt)

Here is example of bib entry:

> @book{CervonePoeticsIncarnationMiddle2012,
location = {{Philadelphia}},
title = {Poetics of {{Incarnation}}: {{Middle English Writing}} and the {{Leap}} of {{Love}}},
publisher = {{University of Pennsylvania Press}},
date = {2012},
author = {Cervone, Cristina Maria}
}

Not sure if I am overlooking something simple, but I cannot seem to find much out there on this issue.

**Comment by retorquere** [comment]
I don't think it's with this reference but with the reference that includes line 5527 in your bibliography. Can you attach (not paste) the whole bib file?

**Comment by MatthewThomasMiller** [comment]
I originally thought that as well, but then in two different bibs (which had two different references at line 5527) I was getting the same error.

Attached are two example bibs that were giving me the error.

[Archive.zip](https://github.com/retorquere/zotero-better-bibtex/files/1681666/Archive.zip)

**Comment by retorquere** [comment]
`MyLibrary.bib` has a unicode replacement character (with character code `65533`) instead of the citation key. This reference looks like

```
@article{�,
  title = {Philologika {{XVI}}. {{Far\={\i}dudd\={\i}n}} `{{Aṫṫ{\=a}r}}. {{IV}}},
  volume = {13/14},
  journaltitle = {Oriens},
  date = {/1961},
  pages = {195--239},
  author = {Ritter, Hellmut}
}
```

Can you right-click the Zotero reference this came from, select "send BBT error report", and post the ID the wizard displays at the end here?

**Comment by MatthewThomasMiller** [comment]
I just submitted it. Report #: NP4TGUK9

Any idea why the second bib I sent, which has different reference at line 5527, still was producing the same error?

**Comment by retorquere** [comment]
The other file also has this reference at 5527:

```
@article{�,
  title = {Philologika {{XVI}}. {{Farīduddīn}} ‘{{Aṫṫār}}. {{IV}}},
  volume = {13/14},
  journaltitle = {Oriens},
  date = {/1961},
  pages = {195--239},
  author = {Ritter, Hellmut}
}
```

so same problem.

**Comment by retorquere** [comment]
You have `bibtex: �` in the `extra` field of your reference. If you have `bibtex: <anything>` in the `extra` field BBT will use that without questioning.

**Comment by MatthewThomasMiller** [comment]
Strange. In my "MTMReferenceLibrary.bib" file, I have the following reference at line 5527:

> @book{RidgeonSufiCastigatorAhmad2006,

  location = {{London}},
  title = {Sufi {{Castigator}}: {{Ahmad Kasravi}} and the {{Iranian Mystical Tradition}}},
  shorttitle = {Sufi {{Castigator}}},
  publisher = {{Routledge}},
  date = {2006},
  author = {Ridgeon, Lloyd}
}

And it produces the same error. The fact that I saw two different references at the same line in two different bibs but was still getting the same error was mainly what was confusing me. (I am probably just doing something stupid.)

In any case, thank you for your help. I will comb through my references to see if I have any other � in there. I think this is a holdover from when I used to use Bookends for bibliography management. Probably something got messed up in importing these old references into Zotero.

**Comment by MatthewThomasMiller** [comment]
Update: I just successfully ran it without an error. Removing those � (character code 65533) in old references solves the issue. Thanks for your help!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5476](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5476.issue-895.xpi) ("remove markers even if pinned").

**Comment by retorquere** [comment]
I've added code to 5476 to actively remove these cases. Would you be willing to test by pasting `bibtex: �` into the `extra` field of a reference, restarting Zotero (using cmd-quit and restarting Zotero), and seeing if it's gone when BBT is done initializing?

**Comment by MatthewThomasMiller** [comment]
I just tried testing it. Restarted Zotero and tested it after BBT initialized. Still got same error on same reference entry.

> Error reading bibliography /Users/MTM/Downloads/Archive/MyLibraryTest2.bib (line 5544, column 10):
unexpected "\65533"
expecting white space
Error running filter pandoc-citeproc:
Filter returned error status 1

The bib I used is attached. It was generated after restart.
[MyLibraryTest2.bib.zip](https://github.com/retorquere/zotero-better-bibtex/files/1681927/MyLibraryTest2.bib.zip)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5480](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5480.issue-895.xpi) ("more logging for #895").

**Comment by retorquere** [comment]
Can you install 5480, retart, and submit a BBT error report (with the markers still in the extra field)?

**Comment by MatthewThomasMiller** [comment]
Sure. Just did that. Here is the report #: YMYE9CWR

**Comment by retorquere** [comment]
That log comes from the official 5.0.78 release, not from the 5480 debug build.

**Comment by MatthewThomasMiller** [comment]
Sorry, here is a new one. Report #: W8VGIVX2

**Comment by retorquere** [comment]
This one is from the 5.0.84 official release, I need one from the [5480 debug build](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5480.issue-895.xpi).

**Comment by retorquere** [comment]
OK super, so 5480 just fixes the problem? If so I can merge and release.

**Comment by MatthewThomasMiller** [comment]
Yes, it appears to fix the issue. The bibtex: � disappears completely from the reference when I installed 5480 and the resulting exported bib file runs with Pandoc without an error. Thanks!

**Comment by retorquere** [comment]
Cool, merged, I'll cut a new release in a day or so.
