### ISSUE TITLE
Can I generate a bib from BBT starting with a list of citations?

### ISSUE THREAD

**Issue by rpgoldman** [retorquere/zotero-better-bibtex#896]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification
Question

## Non-export problems with BBT

Is it possible to somehow take a list of citation keys (that I could extract from my Latex manuscript) and push them at Zotero + BBT to create a collection for that set of citation keys?

I'm slowly training myself to use Zotero + BBT, but I'm not quite sure how I export from it just the citations I need for my manuscript. 

If it helps answer my question, I'm using Emacs as the editor, and I know enough emacs lisp, perl, python, etc. that I could extract a list of the citation keys from the document myself, if necessary.

Thanks!

**Comment by retorquere** [comment]
The documentation site is in the process of being updated (and fixed), but I think what you want is [here](http://retorquere.github.io/zotero-better-bibtex/aux/).

**Comment by rpgoldman** [comment]
Thank you very much. I'm sorry to follow up one simple question by another but ... what's the gear menu?  I've attached a screen shot to show what I see.
I don't see any gear icon in the main Zotero window.  There's a gear in the add-ons window, but nothing about aux scanning there.  There's also a gear in the Zotero preferences pane set, but I don't see aux scanning there, either.
Thanks

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5496](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.84.5496.issue-896.xpi) ("re-add aux scanner to menu").

**Comment by retorquere** [comment]
Can you try 5496?

**Comment by rpgoldman** [comment]
That worked, thanks.  But there isn't a "gear menu" at least in my version: the command only appears in the "Tools" menu.  So maybe the documentation needs an update?

**Comment by retorquere** [comment]
Yep, it did. The site is updated, and I'll fold this into the new release

**Comment by rpgoldman** [comment]
Thank you!!!

**Comment by retorquere** [comment]
You're welcome.
