### ISSUE TITLE
Omit field not working in Zotero 4

### ISSUE THREAD

**Issue by mattysimonson** [retorquere/zotero-better-bibtex#897]
- [ ] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Much of the time when Zotero grabs a book citation from google it captures a "Google-Books-ID" number which then gets printed in bibliography.  It appears to be stored in the "Extra" field.  I tried listing Extra as a field to omit, but no result
Report ID: 9DDA7ACC61670E63

**Comment by retorquere** [comment]
I can't read the Zotero debug reports, can you right-click the reference and send a "Better BibTeX error report"?

**Comment by mattysimonson** [comment]
Done. Request ID: F90E242201111636

**Comment by retorquere** [comment]
I can't read the zotero debug reports. Can you right-click that reference and make sure you select "send *better bibtex* error report" from the menu that pops up?

**Comment by mattysimonson** [comment]
Uh, I thought that's what I did last time.  I get this error message when I
click through:

nvalid response from repository: 403, expected 204
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy:
Policy
expired.</Message><RequestId>639C681B44DFADCE</RequestId><HostId>rOURYLCFYiIERfO0rhMsbHaoRgIol+VIloWFQFAcn9UDqBZuGTRg/a2UmPGQDwqy5BbGSLQmtvQ=</HostId></Error>


*FYI, here's the applications context from the previous screen:*

Platform: MacIntel Intel Mac OS X 10.11
Application: Zotero 4.0.29.15 en-US
Zotero standalone: 4.0.29.15
Active addons:
  Adobe Acrobat NPAPI Plug-in, Version 18.009.20050 (plugin): 17.012.20098
  AdobeAAMDetect (plugin): AdobeAAMDetect 1.0.0.0
  Citrix Online Web Deployment Plugin 1.0.0.105 (plugin): 1.0.105
  Default Browser Helper (plugin): 601
  Java Applet Plug-in (plugin): Java 9.0.4 build 11
  WebEx64 General Plugin Container (plugin): 1.0
  Wolfram Mathematica (plugin): 10.0.0
  Zotero Better Bib(La)Tex (extension): 1.6.100
  Zotero LibreOffice Integration (extension): 3.5.12.SA.4.0.29.15
  Zotero Word for Mac Integration (extension): 3.5.14.SA.4.0.29.15
  ZotFile (extension): 4.2.8
Disabled addons:
  Shockwave Flash (plugin): 21.0.0.242
Settings:
  asciiBibLaTeX = true
  asciiBibTeX = true
  attachmentsNoMetadata = false
  autoAbbrev = false
  autoAbbrevStyle = "http://www.zotero.org/styles/elsevier-harvard"
  autoExport = "immediate"
  autoExportIdleWait = 10
  biblatexExtendedDateFormat = false
  biblatexExtendedNameFormat = false
  bibtexParticleNoOp = false
  bibtexURL = "off"
  cacheFlushInterval = 5
  caching = true
  citeCommand = "cite"
  citekeyFold = true
  citekeyFormat = "[zotero]"
  confirmCacheResetSize = 1000
  csquotes = ""
  debug = false
  defaultDateParserLocale = ""
  DOIandURL = "doi"
  itemObserverDelay = 100
  jabrefGroups = 4
  jurismPreferredLanguage = "zh-alalc97"
  keyConflictPolicy = "keep"
  langID = "babel"
  pinCitekeys = "manual"
  postscript = ""
  preserveBibTeXVariables = false
  qualityReport = false
  quickCopyMode = "latex"
  quickCopyPandocBrackets = false
  rawImports = false
  scanCitekeys = false
  showCitekeys = true
  showItemIDs = false
  skipFields = "Extra"
  skipWords =
"a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
  suppressTitleCase = false
  tests = ""
  warnBulkModify = 10
  ZotFile = true

*and the references tab*

{
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "release": "1.6.100",
    "preferences": {
      "asciiBibLaTeX": true,
      "asciiBibTeX": true,
      "attachmentsNoMetadata": false,
      "autoAbbrevStyle": "http://www.zotero.org/styles/elsevier-harvard",
      "autoAbbrev": false,
      "autoExport": "immediate",
      "autoExportIdleWait": 10,
      "cacheFlushInterval": 5,
      "confirmCacheResetSize": 1000,
      "itemObserverDelay": 100,
      "caching": true,
      "citeCommand": "cite",
      "citekeyFormat": "[zotero]",
      "citekeyFold": true,
      "debug": false,
      "DOIandURL": "doi",
      "bibtexURL": "off",
      "csquotes": "",
      "keyConflictPolicy": "keep",
      "langID": "babel",
      "pinCitekeys": "manual",
      "preserveBibTeXVariables": false,
      "rawImports": false,
      "scanCitekeys": false,
      "showCitekeys": true,
      "showItemIDs": false,
      "skipFields": "Extra",
      "skipWords":
"a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum",
      "tests": "",
      "warnBulkModify": 10,
      "postscript": "",
      "jabrefGroups": 4,
      "defaultDateParserLocale": "",
      "bibtexParticleNoOp": false,
      "biblatexExtendedNameFormat": false,
      "biblatexExtendedDateFormat": false,
      "quickCopyMode": "latex",
      "quickCopyPandocBrackets": false,
      "jurismPreferredLanguage": "zh-alalc97",
      "ZotFile": true,
      "qualityReport": false,
      "suppressTitleCase": false
    },
    "options": {
      "exportFileData": false,
      "exportNotes": true
    }
  },
  "collections": [],
  "items": [
    {
      "itemType": "journalArticle",
      "tags": [],
      "relations": {},
      "url": "http://dx.doi.org/10.1162/ISEC_a_00091",
      "volume": "37",
      "issue": "1",
      "pages": "142-177",
      "publicationTitle": "International Security",
      "ISSN": "0162-2889",
      "date": "July 1, 2012",
      "journalAbbreviation": "International Security",
      "DOI": "10.1162/ISEC_a_00091",
      "accessDate": "2017-04-02 00:35:05",
      "libraryCatalog": "MIT Press Journals",
      "abstractNote": "A central question in civil war research is how
state sponsorship, overseas funding, involvement in illicit economics, and
access to lootable resources affect the behavior and organization of
insurgent groups. Existing research has not arrived at any consensus, as
resource wealth is portrayed as a cause of both undisciplined predation and
military resilience. A social-institutional theory explains why similar
resource wealth can be associated with such different outcomes. The theory
argues that the social networks on which insurgent groups are built create
different types of organizations with differing abilities to control
resource flows. There is no single effect of resource wealth: instead,
social and organizational context determines how these groups use available
resources. A detailed comparative study of armed groups in the insurgency
in Kashmir supports this argument. A number of indigenous Kashmiri
insurgent organizations received substantial funding, training, and support
from Pakistan from 1988 to 2003, but they varied in their discipline and
internal control. Preexisting networks determined how armed organizations
were built and how material resources were used. Evidence from other South
Asian wars shows that this is a broader pattern. Scholars of civil conflict
should therefore explore the social and organizational processes of war in
their research.",
      "title": "Organizing Insurgency: Networks, Resources, and Rebellion
in South Asia",
      "shortTitle": "Organizing Insurgency",
      "creators": [
        {
          "creatorType": "author",
          "lastName": "Staniland",
          "firstName": "Paul"
        }
      ],
      "attachments": [
        {
          "path": "/Users/matthewsimonson/Library/Application
Support/Zotero/Profiles/n85hau5c.default/zotero/storage/82RG5ND5/ISEC_a_00091.html",
          "title": "International Security Snapshot",
          "mimeType": "text/html",
          "url": "
http://www.mitpressjournals.org/doi/abs/10.1162/ISEC_a_00091#.WOBHOBIrKYU"
        },
        {
          "path": "/Users/matthewsimonson/Library/Application
Support/Zotero/Profiles/n85hau5c.default/zotero/storage/2DTDMQ8N/Staniland_2012_Organizing
Insurgency.pdf",
          "title": "Staniland_2012_Organizing Insurgency.pdf",

**Comment by retorquere** [comment]
You're on the 4.0 series of Zotero/BBT. BBT no longer supports the 4.0 series, sorry.

**Comment by mattysimonson** [comment]
Ah, thanks. Upgrading fixed the problem.

**Comment by retorquere** [comment]
My pleasure. The issue template did specifically ask whether you were on the latest BBT/Zotero though; it makes it a lot harder for me to do support if conditions aren't checked.
