### ISSUE TITLE
Using citr leaves warning message: readLines(parents_path[parents])

### ISSUE THREAD

**Issue by koliii** [retorquere/zotero-better-bibtex#898]
Hi @retorquere 

This is not a very urgent issue. And I'm sure it is just because of some issue with my R project files. Because this warning is not coming in my other R projects.

R output is running good. But somehow citr is leaving a warning message like this:

`Listening on http://127.0.0.1:5358
Warning message:
In readLines(parents_path[parents]) :
  incomplete final line found on '/home/ajay/PhD_Thesis_AJAY/index.Rmd'`

I hope that this warning will not create any issue in future.

warning screen-shot:
![screenshot from 2018-02-01 23-41-04](https://user-images.githubusercontent.com/28312545/35695399-5be92900-07aa-11e8-966a-8e4920b452f8.png)

**Comment by retorquere** [comment]
You'd have to talk to the citr developer. I don't generate this message, and I don't have a service running on the network port mentioned.

**Comment by koliii** [comment]
Thank you @retorquere

**Comment by retorquere** [comment]
I've joined https://github.com/crsh/citr/issues/27 so let's track the problem there; if it involves change in BBT, we'll continue here
