### ISSUE TITLE
[authN_M] citation key syntax has off-by-one error

### ISSUE THREAD

**Issue by stephen-frank** [retorquere/zotero-better-bibtex#899]
# Description

When using the Jabref citation key syntax `[authN_M]` (N first letters of Mth author name), `M` indexes from 0 instead of 1. For instance `[auth2_1]` produces the first two letters of the 2nd author's name. `[auth2_0]` and `[auth2]` both produce the first two letters of the 1st author's name.

# Expected Behavior

`M=1` should correspond to the first author: `[authN_1]` is author 1, `[authN_2]` is author 2, etc. I'm pretty sure this is how my old version of Jabref did it.

# To Reproduce

1. Copy the example BibTeX entry from the citation below and import to Zotero using "Import from Clipboard" in the *File* menu. (Or put it in a text file an import it that way.)
2. Under the citation keys tab of the Better BibTeX preferences, set the citation key format to `[auth2_1][auth2_2][auth2_3][year]`.
3. Go to the newly imported entry, right click, and select "Unpin BibTeX key" (so that it stops using the imported key).
4. At this point, you should see that the citation key is autogenerated as "TwThFo2018". (I don't think it will need a refresh, but in any case, it is the same after refresh.)

This illustrates the issue, because the expected citation key value is "OnTwTh2018".

```
@article{one_author_my_2018,
	title = {My {Article}},
	volume = {1},
	number = {1},
	journal = {A Fancy Journal},
	author = {{One, Author} and {Two, Author} and {Three, Author} and {Four, Author}},
	year = {2018},
	pages = {1--2}
}
```

# Debug Info

**Classification:** Bug
**Debug Report ID:** BBN6Z798
**Zotero Version:** 5.0.34
**Better BibTeX Version:** 5.0.85
**OS:** Windows 7 Pro

# Checklist

- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing: https://github.com/stephen-frank

**Comment by stephen-frank** [comment]
Thanks for all your work on this addon!

**Comment by retorquere** [comment]
Can you get me an additional debug report by right-clicking that reference and sending a debug report from the popup menu? That will get me a copy of the reference in question to add to my test suite.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5511](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.85.5511.issue-899.xpi) ("test cases for #899").

**Comment by stephen-frank** [comment]
Ok, I think I did what you asked; see report DWQA4GBI.

**Comment by stephen-frank** [comment]
Test build 5511 fixes it for me.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5517](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.87.5517.issue-899.xpi) ("test for #899").
