### ISSUE TITLE
Better BibTeX does not export collections

### ISSUE THREAD

**Issue by Lycurgue** [retorquere/zotero-better-bibtex#901]
Hi,

I export my library with **_Better Bibtex_** in **_BibLaTex_** format to use some features in Jaberf but collections do not export well. Only the first collection in the _Zotero_ left pane is exported but not properly since the collection (now a group in Jabref) is empty with 24 sub-collections (sub-groups) equally empty and named "undefined".

Here's the result in Jabref. _Commun_ (it means shared in french) is the name of my first collection in _Zotero_.

![betterbibtex](https://user-images.githubusercontent.com/29729875/35782262-776e635a-09c3-11e8-92ca-a5b04938c1c5.PNG)

Otherwise all 1183 entries are exported properly.

Is Better BibTex for Zotero 5 exports collections as the old version for Zotero 4?

Should I change the preferences of Better Bibtex?

The error ID is : KSIPH7HB

Thanks,

Françcois 

- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5526](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.88.5526.issue-901.xpi) ("test cases for #901").

**Comment by retorquere** [comment]
Can you try 5526?

**Comment by Lycurgue** [comment]
Hi, thanks for build 5526

@retorquere 
> Can you try 5526?

Yes I tried build 5526.
It is much better since all sub-collections are now exported but not first level collections except for the first one, in my case _Commum_ colleciton.
In other words, all sub-collections from all first level collections are now sub-collections of _Commun_ collection in Jabref.
Once again, I have three first level collections: _Commun_, _Francois_, _Isabelle_.
_Francois_ and _Isabelle_ collections do not appear **_but_** their sub-collections are now under _Commun_ collection in Jabref 

Thanks,

Françcois

Now,

**Comment by retorquere** [comment]
Can you get me a copy of your `zotero.sqlite` file (while Zotero is not running -- it's not safe to copy the file while Zotero is active)?

**Comment by retorquere** [comment]
> In other words, all sub-collections from all first level collections are now sub-collections of Commun collection in Jabref.

So you mean that on export, `FM` is under `Commun`?

**Comment by retorquere** [comment]
Ah hold on I see the problem

**Comment by Lycurgue** [comment]
Hi retorquere, do you need more information?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5528](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.88.5528.issue-901.xpi) ("jabref groups").

**Comment by retorquere** [comment]
Can you try 5528?

**Comment by Lycurgue** [comment]
Hi retorquere,

Works very well.
Nice job.

I very appreciate this plugin.
It allows us to combine the best of _Zotero_ and the best of _Jabref_.

Thanks a lot

**Comment by retorquere** [comment]
This will drop in 5.0.90 in a few minutes
