### ISSUE TITLE
Auto-update sticks on "Scheduled" or "Running"

### ISSUE THREAD

**Issue by roblevy** [retorquere/zotero-better-bibtex#903]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

With reference to bug report: 4VMI4ZGN

When I do a biblatex export of one of my collections, and tick the keep updated button, the auto-export shows up where it should:
![Automatic export](https://user-images.githubusercontent.com/4764631/35820261-f7c6c89c-0a9c-11e8-8d6f-d9dceda5dc0c.png)

But it just stays at either "running" (as I've shown here) or, sometimes, "scheduled".

It's one of these really annoying issues where "it used to work", then I fiddled with some stuff (I think relating to the "Export unicode as plain-text latex command" options under the "Export" options menu, and then it never worked again.

I can run the export through Zotero by doing File > Export as normal, but it no longer automatically updates on changes.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5530](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.88.5530.issue-903.xpi) ("fixes #903").

**Comment by retorquere** [comment]
Can you try 5530?

**Comment by bpiwowar** [comment]
It works for me

**Comment by privatarmee** [comment]
Also work for me. THX

**Comment by roblevy** [comment]
Yep. It all works fine now. Wow! Fastest turnaround ever! Thank you retorquere.

**Comment by retorquere** [comment]
Only I and @blip-bloop can close issues; I keep issues open until I've merged the changes into the main development line. Tests on the merge are running and should drop as a new release in a few minutes. Thanks for your help guys, it's so important to get test feedback (and sorry for the disruption in your workflow).

**Comment by roblevy** [comment]
:D thank _you_

**Comment by retorquere** [comment]
@blip-bloop will also re-open issues if you comment on them :smile:
