### ISSUE TITLE
Exporting multi-word last name with no first name has no braces (Biblatex)

### ISSUE THREAD

**Issue by adamaltmejd** [retorquere/zotero-better-bibtex#906]
Thanks for a truly amazing add-on!

Maybe this has been discussed before but I couldn't find anything. I have a reference to the following paper (http://science.sciencemag.org/content/349/6251/aac4716), where the author field is just populated by "Open Science Collaboration" in the last name box. However, the exported biblatex code treats this as a including a first name (since there are no braces around the text) and cites (using biber) just shows "Collaboration". Here is the exported bib:

```
@article{Collaboration2015_estimating_reproducibility,
  langid = {english},
  title = {Estimating the Reproducibility of Psychological Science},
  volume = {349},
  issn = {0036-8075},
  doi = {10.1126/science.aac4716},
  number = {6251},
  journaltitle = {Science},
  date = {2015-08-28},
  author = {Open Science Collaboration},
  eprinttype = {pmid},
  eprint = {26315443}
}
```

Changing to `author = {{Open Science Collaboration}}` yields the correct output.

And my report Id: FJVK9ECH

**Comment by retorquere** [comment]
Try changing the author field to single-field instead of firstname-lastname by clicking the icon between the author name and the `-` button in Zotero.

**Comment by adamaltmejd** [comment]
Worked perfectly :), thanks. Sorry for creating an issue about it - will read Zotero docs better next time hehe.

**Comment by retorquere** [comment]
No worries. The issue tracker is for questions too.
