### ISSUE TITLE
Failing to finish "Loading citation key"

### ISSUE THREAD

**Issue by pnacht** [retorquere/zotero-better-bibtex#908]
- [X] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification
I am using Zotero 5.0.35.1 with Better BibTeX 5.0.90. When Zotero is opened, the "Better BibTeX: Initializing" box appears in the bottom-right corner with "Waiting for Zotero database" (or something). After 1-2 seconds, this changes to "Loading citation key", which never disappears, even if I close Zotero (indeed, it has been there the entire time I've been writing this post).

Thinking this might just be a display bug, I continued on. However, if I try to export a collection with Better BibTeX (or BibLaTeX), I can go through the entire process up to selecting the location for the .bib file and clicking "OK", but then an error appears: "An error occurred while trying to export the selected file". This happens regardless of the options I choose in the export dialog (i.e. with or without "Keep updated"). This also happens with other collections I've previously been able to export without issue. If I try to export into another format (i.e. CSV), the export is successful, which would seem to indicate the issue is with BBT, not Zotero.

I have tried to send an error log via the usual channel, but Better BibTex doesn't seem to notice debugging is active. I can go Help > Debug Output Logging > View Output and see the full debug log. However, if I click Help > Report Better BibTeX Errors, it states that "Zotero Debug Logging is currently disabled" and that I should restart with logging enabled. Even if I restart from this dialog, BBT continues unaware of the debug log. Indeed, if I ignore the warning and click "Next", all data tabs (Application Context, Errors, Debug log and References) are blank. I have therefore  attached a copied version of the Debug Log found in "View Output" here. The log includes only the opening of Zotero, without any export attempts, since the root issue is probably linked to the failure of "Loading citation key".

[BBT.txt](https://github.com/retorquere/zotero-better-bibtex/files/1726332/BBT.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5565](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.90.5565.issue-908.xpi) ("fixes #908").

**Comment by retorquere** [comment]
Can you try 5565?

**Comment by pnacht** [comment]
I downloaded and installed 5565, but it unfortunately has not fixed the issue. All of the symptoms remain ("Loading citation key", error exporting, doesn't detect active debugging). 

Here's the new debug log: [BBT.txt](https://github.com/retorquere/zotero-better-bibtex/files/1727222/BBT.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5566](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.90.5566.issue-908.xpi) ("partial error report").

**Comment by retorquere** [comment]
The debug report should work again with 5566, can you try submitting a report with that? The error log you posted doesn't have all the details I need because you could not activate debug logging.

**Comment by pnacht** [comment]
Done. Report 3XW3GTNB.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5571](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.90.5571.issue-908.xpi) ("indexes, not indices").

**Comment by retorquere** [comment]
Try 5571

**Comment by pnacht** [comment]
Yep, that seems to be working. All symptoms are gone: the "Loading citation key" disappears after a moment (as expected), and exports work (including "Keep Updated").

When 5571 is merged into the main trunk, will my BBT be auto-updated or should I do so manually?

**Comment by retorquere** [comment]
5.0.91 will drop in a few minutes, but it's just a rebranded 5571, and Zotero will auto-update it (I think it checks once a day or so for extension updates). You don't have to do anything, but it doesn't hurt either to update manually (using "check for updates" in the Zotero add-ons menu).
