### ISSUE TITLE
Relative Path Export

### ISSUE THREAD

**Issue by amijalis** [retorquere/zotero-better-bibtex#910]
First, thank you very much for this awesome piece of software. I was wondering if there is a way to export filepaths as  ~/Zotero/... instead of /home/***/Zotero or /Users/***/Zotero. I'm trying to take my Zotero library cross-platform and the home folder is in different places on my machines. 

I've seen mentions of relative path exporting in other issues but cannot seem to get this working for Zotero's PDF attachments. This solution would also work.

Thanks in advance for your help!

**Comment by retorquere** [comment]
Sorry for the spurious close, and that this sat ignored so long -- github makes it hard to address older issues.

What you want can be achieved with a postscript:

```
if (Translator.BetterTeX && !Translator.options.exportFileData && item.attachments && Translator.exportPath.match(/^\/((home\/Zotero)|(Users\/Zotero))\/)) {
  for (const att in item.attachments) {
    att.localPath = att.localPath.replace(/^\/((home\/Zotero)|(Users\/Zotero))\/, '~/Zotero/')
  }
  reference.add({ name: 'file', value: item.attachments, enc: 'attachments' })
}
```

**Comment by retorquere** [comment]
Oh, you closed this yourself -- never mind then.
