### ISSUE TITLE
Exporting references add capitals for titles' words 

### ISSUE THREAD

**Issue by laspic** [retorquere/zotero-better-bibtex#913]
Hello,

I don't really understand what happens, but for each French reference I export, all the title fields are re-written. Capital letters are added to the words (but not always), in accordance with the english titles standards. I've tried with BibTeX and BibLaTeX, the result is identical.

For instance: 
"Usages et usagers de la permanence du député" gives "Usages et Usagers de La Permanence Du Député" ;
"L'État en perspective" gives "L'État En Perspective" ;
"L'usage de l'entretien en sciences sociales" gives "L'usage de l'entretien En Sciences Sociales".

Is there a setting I've missed ? Or is it a normal feature ?

Here is a report ID: HRHE7GGG

**Comment by retorquere** [comment]
It is a normal feature; the reason is explained [here](https://retorque.re/zotero-better-bibtex/all-them-braces/#bbt-is-changing-the-capitalization-of-my-titles--why) but you can just set the language of your reference to French and it will go away.

**Comment by laspic** [comment]
Oh, sorry. All explanations were available and I missed them. I promise that I have looked for ! :-)
Thank you, everything works great now.
