### ISSUE TITLE
No automatic exports from tag selection

### ISSUE THREAD

**Issue by laspic** [retorquere/zotero-better-bibtex#915]
Hello, 

My question is closely similar to [this one](https://github.com/retorquere/zotero-better-bibtex/issues/904).
Would it be possible to set an automatic export from a tag selection of references ?

(I'm surprised not to find this question already asked, if I'm wrong, sorry in advance).

Thanks.

**Comment by retorquere** [comment]
That is actually the same as saved-search. You can save a tag-selection as a saved search, then (if Zotero exposes the information), I could export saved-search.

**Comment by retorquere** [comment]
Please join the discussion at #904.
