### ISSUE TITLE
"Waiting for Zotero database..." indefinately 

### ISSUE THREAD

**Issue by cjwit** [retorquere/zotero-better-bibtex#916]
I am having some trouble getting BBT up and running. After installing the latest version (5.0.92.xpi) into my standalone Zotero (version 5.0.35.1), I see the notification "Better BibTex: Initializing / Waiting for Zotero database..." Something appears to be hanging, preventing the system from moving forward.

I understand that this may simply be a first-time initialization that takes a while, but the discussion at issue #815 leads implies that the wait for the database should be a quick one. I've left it on for a while multiple times. In case it's helpful information, when I go to Export within the Zotero preferences, my Default Format options are unavailable (the drop down menu says "Loading..."). I can also see that the Citekey column and Citation Key row within individual documents are there, but they are empty. Since the notification tells me that BBT is still waiting for Zotero, I am not confident that this is BBT setting up those keys yet.

I've installed, restarted, and reinstalled a few times with no change. I'm at a loss of a next thing to try. I appreciate any advice and look forward to using the add-on.

**Comment by retorquere** [comment]
Can you send a bbt error report?

**Comment by retorquere** [comment]
Really can't do anything without the debug report.

**Comment by cjwit** [comment]
I ran a debug report but had to do so by right clicking a collection. (There is no more gear menu and I didn't see the option to report an error within the preferences.) There were no error messages within the debug report, though the Initializing phase is still holding. The report ID is V2E7YL9M.

**Comment by retorquere** [comment]
Found the docs issue. The other way is by selecting `Report Better BibTeX Errors` from the `Help` menu. I've updated the docs.

**Comment by cjwit** [comment]
Thanks for the docs update. The new report is `PAGCS9N5`.

**Comment by retorquere** [comment]
Nothing out of the ordinary in the logs. Can you try disabling (or uninstalling) BBT, restarting Zotero, and exporting a reference using "RIS"?

**Comment by cjwit** [comment]
Tried and failed. Without BBT, the Export pane in preferences is still stuck on loading and exporting does not appear to take any action at all. If this is a Zotero 5 issue, please let me know if you have any advice. Based on [this issue from the Zotero forums](https://forums.zotero.org/discussion/70519/default-format-for-export), I'll try waiting with the Export pane open and BBT disabled for a start... Thanks again for the assistance.

**Comment by retorquere** [comment]
I had a suspicion... I do see this in the log:

> [JavaScript Error: "Unix error 1 during operation remove on file /Users/witulski/Zotero/translators/A Contra Corriente.js (Operation not permitted)" {file: "(unknown module)" line: 0}]

so it looks like Zotero wants to remove this file but fails, and that in turn means BBT never gets the green light to start (hence the "waiting for Zotero..." message). In this case BBT is just the messenger of this fact, but as far I can tell, Zotero silently fails to initialize.

**Comment by cjwit** [comment]
Thanks. I'll move this question to the Zotero forum.
