### ISSUE TITLE
Cyrillic symbols export format

### ISSUE THREAD

**Issue by bom-bibom** [retorquere/zotero-better-bibtex#917]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

I have cyrillic sources in my bibliography. When I use "export document" (export to .bib file) with options "bibtex" or "biblatex" there is no problem. But when I chose "better bibtex" or "better biblatex" options I have some special commands instead of cyrillic symbols in my .bib file. For example "\cyrchar\cyrt" instead of cyrillic "т".
Examples are in the following files:
[better_bibtex.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/1750850/better_bibtex.bib.txt)
[bibtex.bib.txt](https://github.com/retorquere/zotero-better-bibtex/files/1750851/bibtex.bib.txt)

P.S: I'm new in LaTeX, sorry for stupid question

**Comment by retorquere** [comment]
bibtex doesn't really support cyrillic symbols, so BBT translates them to LaTeX commands instead, which bibtex does support. You can change that behavior in the [preferences](https://retorque.re/zotero-better-bibtex/configuration/#export-unicode-as-plain-text-latex-commands).

**Comment by retorquere** [comment]
BBT in biblatex mode by default does not do this though, so it looks like you have turned on "Export unicode as plain-text latex commands" for BibLaTeX in the BBT preferences.

**Comment by bom-bibom** [comment]
Thank you very much for so quick answer, it works.
P.S.: I use biber as a back-end for bibliography.
