### ISSUE TITLE
adding year field when exporting with Better Biblatex

### ISSUE THREAD

**Issue by hoehnp** [retorquere/zotero-better-bibtex#918]
First of all I want to thank you for all your efforts on zotero-better-bibtex. 

Recently, I was working on a paper for an ASME publication and noticed that the years are not printed correctly in the paper. I could figure out, that the ASME bibtex style rather uses the 'year' field and ignores the 'date' field. Could you please add the 'year' field in addition to the date field?

**Comment by retorquere** [comment]
Are you exporting with "Better BibTeX" or with "Better BibLaTeX"?

**Comment by hoehnp** [comment]
Thank you for the quick response.

as written in the title, I use Better BibLaTeX.

**Comment by retorquere** [comment]
The reason I I'm asking is that you mention using a bibtex style, not a biblatex style, and you're asking for bibtex fields, not biblatex fields. Why not export using Better BibTeX?

**Comment by hoehnp** [comment]
I just checked it. You are right, I get the year when exporting with Better BibTeX. Just out of habit I guess I was using Better BibLaTeX without thinking too much.

**Comment by retorquere** [comment]
That's cool, it happens.

**Comment by vnmabus** [comment]
Why this can not be added? I am exporting with Better BibLaTeX because the presentation type does not export the name of the event with Better BibTeX, and have the same problem.

**Comment by retorquere** [comment]
What can what not be added?

**Comment by vnmabus** [comment]
Yes, I know. The thing is that the export format for the presentation type in Zotero is better for BibLaTeX (where the type is unpublished, and more information is preserved) than for BibTeX. I was wondering if there is anything wrong with adding the year and month fields to the BibLaTeX export, so that it could be used in plain BibTeX, or if the BibTeX export could be improved.

**Comment by retorquere** [comment]
`month` is not a biblatex field. If your date has a month, it will show up in the `date` field. biblatex supports that.

**Comment by retorquere** [comment]
If you want the meeting name in bibtex, where would you put it?

**Comment by vnmabus** [comment]
In the note field, I suppose. It is a shame that there is no specific type for presentations without an attached paper 😞

**Comment by retorquere** [comment]
Yeah, but bibtex is getting a bit long in the tooth. It's best to move to biblatex when possible. I don't want to add unsupported fields to Better BibLaTeX just so it can be used with bibtex, sorry. You can add your meeting name for the bibtex export with a postscript:

```
if (Translator.BetterBibTeX && item.itemType ===  'presentation' && item.meetingName && !reference.has.note) {
  reference.add({ name: 'note', value: item.meetingName })
} 
```

**Comment by vnmabus** [comment]
Thank you!
