### ISSUE TITLE
Capitalizing Title in Cite Keys 

### ISSUE THREAD

**Issue by cands** [retorquere/zotero-better-bibtex#919]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

I'm not sure whether this is expected behavior, but I think it may be a bug. I would like to have the `[shorttitle]` and `[title]` commands for generating Cite Keys capitalize the words of the title they're extracting. I've tried to use the 'capitalize' filter, but is still not capitalizing. Here are three examples of generated Cite Keys for a journal article with title "Effectiveness of prehospital trauma triage systems in selecting severely injured patients: Is comparative analysis possible?":

`[auth]_[year]_[shorttitle]`: vanRein_2018_Effectivenessprehospitaltrauma

`[auth]_[year]_[shorttitle:capitalize]`: vanRein_2018_Effectivenessprehospitaltrauma

`[auth]_[year]_[title]`: vanRein_2018_EffectivenessofprehospitaltraumatriagesystemsinselectingseverelyinjuredpatientsIscomparativeanalysispossible

**Comment by retorquere** [comment]
It's not a bug, `[title]` and `[shorttitle]` were made to mimic the JabRef behavior, which lowercases the result. I can't change that behavior now as it would affect citekeys for existing users.

`capitalize` works only on space-separated words; `[title]` and `[shorttitle]` don't deliver space-seperated words, but `[Title]` does (the meaning of the capitalized `Title` is explained [here](https://retorque.re/zotero-better-bibtex/citation-keys/)). You could try something like `[auth]_[year]_[Title:capitalize:skipwords:select,1,3]`.

**Comment by cands** [comment]
Great, thank you for explaining and providing the suggested command, I confirm that it works!
