### ISSUE TITLE
CSL YAML export of date with original publication date in [brackets]

### ISSUE THREAD

**Issue by scarwire** [retorquere/zotero-better-bibtex#922]
- [X] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Exporting references

This is a bug report related to reference SWDEYIT2. Export to CSL YAML.

I'm sorry to bring up another issue similar to #811 -- this is really a feature request more than a bug report -- but I'm having trouble exporting references that include dates of original publication. For instance, I'm trying to get output like this:

> Amos Vogel, _Le Cinéma : art subversif_, Paris, Capricci, 2016 [1974].

where 2016 is the date of publication and 1974 is the date of the first edition. Under Zotero's date field, I had put in `2016 [1974]`.

In BBT for Zotero 4, exporting this reference to YAML produced something like this:

```
  issued:
    literal: '2016 [1974]'
```

Under Z5, I'm getting this:

```
  issued:
    - year: 2016
```

So the original date of publication is just getting thrown out. Is there any way to have it included again?

Thanks again for an otherwise fabulous piece of software.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5742](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.93.5738.issue-922.xpi) ("Merge branch 'master' into 922").

**Comment by retorquere** [comment]
Can you give 5742 a spin?

**Comment by scarwire** [comment]
5742 hangs on "Loading citation keys" when starting up. I can't export anything!

**Comment by retorquere** [comment]
Can you submit an BBT error report?

**Comment by scarwire** [comment]
Done! Debug ID is D1618111088

**Comment by retorquere** [comment]
I can't access the Zotero debug reports, I specifically need a BBT error report.

**Comment by scarwire** [comment]
Oops, sorry about that. How about report ID B2WMGJ5F ?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5764](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.93.5762.issue-922.xpi) ("lokijs binary indexes are not as reliable as one might want them to be").

**Comment by retorquere** [comment]
Can you try 5764?

**Comment by scarwire** [comment]
Ok, thanks, looks like it works! I tested it in pandoc-citeproc which now outputs this:

> Foo (Vogel [1974] 2016).
>
> Vogel, Amos. (1974) 2016. _Le Cinéma, art subversif_. Traduit par Claude
> Frégnac. Paris: Capricci.

A lot of CSL styles haven't implemented this format

```
   original-date:
    - year: 1974
```

but I guess I can take that up with their authors.

**Comment by retorquere** [comment]
Well... the bracket notation isn't any kind of formal standard. If you want the former notation back, this postscript should do it:

```
if (Translator.BetterCSLYAML) {
  if (reference['original-date'] && reference.issued) {
    reference.issued += ` [${reference['original-date'][0].year}]`;
    delete reference['original-date'];
  }
}
```
