### ISSUE TITLE
Safari causes spurious pop-up of Add/Edit Citation modal dialog in Zotero

### ISSUE THREAD

**Issue by rpgoldman** [retorquere/zotero-better-bibtex#923]
- [X] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing

# Bug classification

## Non-export problems with BBT

I have a very odd error where, when Zotero is active and so is Safari, something causes Zotero to repeatedly pop up its "Add/Edit Citation" modal dialog box.

I have previously described this behavior in [a post on the Zotero forums](https://forums.zotero.org/discussion/comment/302686) where dstillman reports (based on my debug logs) that it's an issue with BBT not with Zotero proper.  He cites this snippet of code (presumably from my debug log):
```
{better-bibtex} CAYW.getDocument {"id":12} {
```

Unfortunately, while I have tried to replicate this with BBT logging turned on, I don't seem to be able to.  Perhaps it's best to mark this as low priority pending my ability to get a good log.  I don't know whether the BBT logging is actually interfering with whatever causes this bug.

**Comment by retorquere** [comment]
It's almost certain BBT is involved in this, but this is usually triggered by an explicit call to its web-api by some outside software. Can you semi-reliably trigger this? I'd be much helped with a debug log, but I can't access the regular ZOtero debug reports, but if you have debug logging on, and send me a BBT error report after it's happened, I'm sure we can find the issue.

**Comment by retorquere** [comment]
never mind -- the message log in that forum thread shows that Safari is in fact calling the URL. If you don't use the picker I could add an option to disable it, but it seems to be Safari is misbehaving, not BBT.

**Comment by rpgoldman** [comment]
Would you please LMK what the URL is that Safari is calling?  I wonder if there's something stale in its cache that's causing the problem.  annoying that the logging seems to interfere with the bad behavior....

**Comment by rpgoldman** [comment]
Thanks!  I'll see if I can find anything by looking at the network traffic in the Safari debugger. 

Is there any way to put this ticket in "low priority" status until I'm able to provide more info?

**Comment by retorquere** [comment]
The logging doesn't interfere -- Dan Stillman (one of the Zotero devs) has identified from the logs you sent them that it's not BBT that's at fault (which I suspected, but the logs would have told me what Dan found out himself) but that actually Safari is actively calling the BBT CAYW url.

**Comment by retorquere** [comment]
No need for low-prio labelling -- the "awaiting" label is sufficient.

**Comment by retorquere** [comment]
I can't find a good configurable way to allow excluding specific browsers (the user-agent has become a mess in the past years). If you want a full disable option, please re-open for a feature request.

**Comment by rpgoldman** [comment]
I suspect this is some simple misconfiguration on my part.  Perhaps I have some add-on to Safari that's causing this to happen.  I only use Safari for special purposes; it's not my day-to-day browser, so  I won't worry about this until/unless I find out more specifically what's causing the problem.  Thanks for your attention, and for the great add-on.

**Comment by retorquere** [comment]
You're welcome.
