### ISSUE TITLE
CAYW returns empty results (Zotero 5.0.36beta)

### ISSUE THREAD

**Issue by adam3smith** [retorquere/zotero-better-bibtex#924]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification
CAYW

## Non-export problems with BBT
When calling CAYW using http://localhost:23119/better-bibtex/cayw?format=mmd&clipboard=yes the picker doesn't come up. Error report is DJJE5DJU -- this doesn't have debug, let me know if you still need this, but the main error looks pretty promising. Since the new beta includes significant changes to integration.js, this is probably not surprising. Let me know if you need anything else

**Comment by retorquere** [comment]
Ugh, I don't like the sound of "significant changes" -- this part of Zotero is essentially undocumented. Do you know anything about these changes?

**Comment by retorquere** [comment]
Adomas says the integration [hasn't changed](https://groups.google.com/d/msg/zotero-dev/bnNPtkvy_js/j8lR4OTTDAAJ).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5807](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.94.5805.issue-924.xpi) ("cayw: wait for BBT ready").

**Comment by retorquere** [comment]
The picker pops up for the new beta, but the actual fetch fails. It's reproducible, so this one shouldn't be too hard (FLW).

**Comment by retorquere** [comment]
Found it. The picker returns itemIDs as strings rather than numbers in the beta.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5819](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.94.5813.issue-924.xpi) ("beta changes type of itemID in CAYW").

**Comment by retorquere** [comment]
Can you give 5819 a spin?

**Comment by adomasven** [comment]
We've fixed it on our end. https://github.com/zotero/zotero/commit/079cb258f44504acd7f335f700d9e5d245a52586

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5847](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.94.5845.issue-924.xpi) ("fixed on Zotero end").

**Comment by retorquere** [comment]
@adam3smith can you try 5847 with the new beta after the fix from @adomasven ?

**Comment by adam3smith** [comment]
Working here, thanks!

**Comment by retorquere** [comment]
Merged into release
