### ISSUE TITLE
convert diaresis (german umlauts) in citation keys

### ISSUE THREAD

**Issue by tolot27** [retorquere/zotero-better-bibtex#926]
In JabRef, author names with german umlauts (diaresis) are converted to their longer form during citation key generation, i. e. Jäger -> Jaeger. That does not happen in BBT. It would be great if BBT would support it, too.
A conversion is described, i. e. at https://german.stackexchange.com/a/4993.

I tried `[auth:ascii]`, `[auth:fold]` as well as the `Auth` variants.

**Comment by retorquere** [comment]
Can you right-click that reference and send me a bbt error report?

**Comment by retorquere** [comment]
This is tricky to get right. The German transliteration is not the universal choice for languages that use characters with umlauts, see the discussion [here](http://forum.camendesign.com/language_specific_transliteration_re_transliteration).

**Comment by tolot27** [comment]
The report ID is 2EYR7R37.
I know that is tricky. Maybe an intermediate solution is to just replicate how JabRef handle these cases.

**Comment by retorquere** [comment]
Perhaps as a separate filter (so something like `:ascii,german`) but not as the default. I am conservative about changing behavior these days, and doing things exactly as jabref does them has stopped being a goal a long while ago; I take the jabref behavior for guidance, but not for strict adherence.

**Comment by retorquere** [comment]
Sorry, that would be `:fold,german`

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5850](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.97.5848.issue-926.xpi) ("fold,german").

**Comment by retorquere** [comment]
try `[auth:fold,german]` in build 5850.

**Comment by tolot27** [comment]
It does not work. See 5YBRUGWU.

**Comment by retorquere** [comment]
You have to make a change to the reference for the key to regenerate -- have you tried that?

**Comment by tolot27** [comment]
I've just unpinned the key, which changed my manual edited key from `Jaeger2002` to `Jager2002`.

**Comment by retorquere** [comment]
My mistake: try `[Auth:fold,german]` (note the uppercase `A`)

**Comment by retorquere** [comment]
I copied the `ä` from your comment above into `vi` and it says it's hex code `00e4`. Javascript is [odd with unicode](https://mathiasbynens.be/notes/javascript-encoding) so UTF-16 expressions is usually the best way to go about having unicode chars in the source -- internally, it will do the encoding/decoding magic required (in my experience).

**Comment by tolot27** [comment]
With `[Auth:fold,german]` it works well. Thanks.

**Comment by retorquere** [comment]
Cool, I've folded (ha!) that into a new release which should drop in a few minutes.
