### ISSUE TITLE
Exporting title 

### ISSUE THREAD

**Issue by declanol** [retorquere/zotero-better-bibtex#927]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification

When exporting a reference that contains a special character in the title word (specifically "Grey's Anatomy"), the special character (apostrophe) is added to the citation key (i.e. standring_gray's_2016 instead of standring_grays_2016). This does not cause an error in Better BibLaTeX itself, but does cause an error when trying to use the resulting .bib file.

For names with special characters such as apostrophes, these are automatically removed for the citation key, the same could be done for the title word? It can be overcome manually by removing the special characters and pinning the citation key.

My full citation key is:
`[0][auth:lower:postfix,_][Title:lower:skipwords:select,1,1:postfix,_][year]`

**Comment by retorquere** [comment]
You will want to use `[0][auth:lower:postfix,_][Title:lower:skipwords:select,1,1:clean:postfix,_][year]`. `:clean` is implied for lowercase fields (functions), but not for capitalized fields (property access).

BTW, I usually see the `[0]` at the end (because it's a postfix), but technically it doesn't matter where you put it.

**Comment by declanol** [comment]
Perfect, thanks a lot.

**Comment by retorquere** [comment]
bad label-gun, down!
