### ISSUE TITLE
BBT citekey in csl note stopped working

### ISSUE THREAD

**Issue by ToLoKn** [retorquere/zotero-better-bibtex#929]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

First of all, thanks retorquere for this really helpfull extension
# Bug classification
Since I do the main writing of texts in word (due it's good support for spelling and grammar checks) but want to include many math formula in my thesis, I've searched a way of easy tranfering text with a lot of citations from Word to LaTeX. I also want to use BibLaTeX to manage the bibliography. 

After some digging in the BBT code I found the `better-bibtex-citekeys.csl` file and the hidden setting 
 `extensions.zotero.translators.better-bibtex.citeprocNoteCitekey` allowing me to (mis)use the Word integration with a custom csl file to actually write valid latex cite commands with the citekeys as provided by BBT. 

With the last update of Zotero this way stopped working. When trying to update any references in the Word document (or updating the references in the word file) I keep getting an error message saying something went wrong and `Error: Keymanager.get expects a number, got undefined`.  
Also the CSL Editor and CSL Preview stopped working for any selected item/csl.

I narrowed the problem down to BBT and further to the `extensions.zotero.translators.better-bibtex.citeprocNoteCitekey` being set to true, as all (expect to show the citekeys in word) work well when switched back to false.

I've recorded the debug output and attached it to this post
[DebugOutput.zip](https://github.com/retorquere/zotero-better-bibtex/files/1803097/DebugOutput.zip).
If I am not mistaken, I think there is some problem with the monkey patch of the `itemToCSLJSON` function of `Zotero.Utilities` done in `BetterBibTeX.ts:80`.  As I understand this handles setting the BBT citekey as note for the CSL usage.

Is there any way to "quick" fix the problem?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5927](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.102.5925.issue-929.xpi) ("itemToCSLJSON has changed in 5.0.37").

**Comment by retorquere** [comment]
Try 5927

**Comment by ToLoKn** [comment]
With build 5927 using the citekey (as note field) in csl works again. Both Word integration and style editor/style preview show the expected result.

Thanks for the quick fix.

**Comment by retorquere** [comment]
Thanks for the confirmation, new release should be out in a few minutes.
