### ISSUE TITLE
Replacing 'director' by 'author' on video or movie types when exporting with Better BibLaTeX

### ISSUE THREAD

**Issue by RicardoGuzmanVelasco** [retorquere/zotero-better-bibtex#930]
Hi!

I asked this on Zotero forums, https://forums.zotero.org/discussion/70889/replacing-director-by-author-on-video-or-movie-types-when-exporting-with-better-biblatex#latest

Because of the problems LaTeX platforms have with fields like 'director' in 'movie' or 'video' types, I tried to autochange that fields by 'author' field. But 'director' is exported in Zotero as a field whilst 'author' is a namelist, so I figured out I needed to add the list format in the postscript. I tried it as follows:
```

if (Translator.BetterBibLaTeX && this.item.itemType === 'videoRecording') {
   this.add({ name: 'author', value: '{' + this.item.director + '}' })
}

if (Translator.BetterBibLaTeX && this.item.itemType === 'film') {
   this.add({ name: 'author', value: '{' + this.item.director + '}' })
}

```
That's not the problem. But the result was an 'author' field with "undefined" word, so I think this is a problem with 'director' field data information on this.item.director. 

As I said on Zotero forums (follow the previous link), it doesn't work neither with somethink like:

```
if (Translator.BetterBibLaTeX && this.item.itemType === 'videoRecording') {
   this.add({ name: 'author', value: this.item.director  })
}
```

Maybe... Am I missing something?
Thanks.

**Comment by retorquere** [comment]
I have a little trouble following what you're trying to achieve. Can you right-click on a reference were you want to do this, send a BBT error report, and then post here the biblatex you would want to see after the postscript ran.

**Comment by retorquere** [comment]
I also don't quite follow what you mean when you say 

> 'director' is exported in Zotero as a field whilst 'author' is a namelist

the creators all sit in one array. If you want to see what the references look like within the translators, export it as `BetterBibTeX JSON`.

Perhaps what you want is something like

```
if (Translator.BetterBibLaTeX) {
  switch (this.item.itemType) {
    case 'videoRecording':
    case 'film':
      this.item.creators.forEach(creator => {
        if (creator.creatorType === 'director') creator.creatorType = 'author'
      })
      this.addCreators();
      break;
  }
}
```

**Comment by RicardoGuzmanVelasco** [comment]
OMG I think I was misunderstanding everything about how creators is stored. In Zotero forums I got a explication simmilar that this you're saying now to me. I think I was doing totally wrong. I will try and say you everything you're asking, ok? Give me some hours!

**Comment by retorquere** [comment]
No worries.

**Comment by RicardoGuzmanVelasco** [comment]
That was. Solved.

Thanks so much!

PS: I think a case like this could be such a useful adding to the scripting examples.

**Comment by retorquere** [comment]
Done. The site needs a few minutes to rebuild, but it should be up there soon.
