### ISSUE TITLE
Unnecessary -1 suffix on citekeys after reorganizing library

### ISSUE THREAD

**Issue by ewa** [retorquere/zotero-better-bibtex#931]
Hi,

I reorganized my Zotero library, moving a lot of documents between my private library and a group library.   In the process, I created and then got rid of (merged) a bunch of duplicate entries.  Now (presumably as a consequence, but I don't actually know), I have a bunch of documents where there's no cite key collision, but there's a -1 suffix on the key anyway.  Is there any way to get these re-numbered?

The attached screenshot shows some of these. I'ts sorted by Citekey, so duplicates are next to each other, when they exist (and there is one legit duplicate pair in this screenshot).

Thanks!
Eric
![image](https://user-images.githubusercontent.com/288020/37604232-1e1f8d10-2b56-11e8-86d9-665e7efda478.png)

**Comment by ewa** [comment]
I should add that there's an automatic export (BibTeX) configured for the library.

**Comment by retorquere** [comment]
You can do this by

1. enabling [keyRefreshPostfix](https://retorque.re/zotero-better-bibtex/configuration/#keyrefreshpostfix)
2. select all your references
3. right-click
4. refresh

The reason for the default behavior is explained [here](https://github.com/retorquere/zotero-better-bibtex/issues/914).

**Comment by ewa** [comment]
That seems to do it, thanks!

**Comment by retorquere** [comment]
Cool, thanks for the confirmation.
