### ISSUE TITLE
 CAYW: BBT inserts dots instead of blanks in Scannable-cite IDs

### ISSUE THREAD

**Issue by vtcarlino** [retorquere/zotero-better-bibtex#932]
Hi,
Since the rewrite, BTT puts dots into Scannable-cite IDs instead of blank spaces where there's no data to display (e.g. page number). Here's an example: `{ | Latour, 2007 |. |. | Zu:966903:CTRBUMIB }`

As a result, I get this output at the export:  (Latour, 2007, p. ..)

Could you replace the dots with blanks? This way, the output won't display the "p." abbreviation but simply (Latour, 2007).

Thanks,

Vincent

**Comment by retorquere** [comment]
I can't reproduce this. Can you go to `Help` -> `Debug output logging` -> `Restart with logging enabled`, let Zotero restart, then do the CAYW pick again, and submit a BBT error report from the `Help` menu. If you post the debug ID here, I can see what's being picked.

**Comment by retorquere** [comment]
I also can't make sense of the `|. |. |` part. BBT separates parts in scannable cite with ` | `, so even if it was BBT injecting these periods, it should have looked like `| . | . |`. A debug log will tell me more.

**Comment by vtcarlino** [comment]
I tried to submit a BBT error report but got the following error message:

Invalid response from repository: 403, expected 204
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>03E800805470DCB4</RequestId><HostId>GHFUqjCr3xHdKw/Po1GqspFr6JeIZDtMxzIX/qxpjti68B0m1OjSbSBbTp8inFa0mp6u8L0HsxY=</HostId></Error>

**Comment by retorquere** [comment]
Can you try again?

**Comment by vtcarlino** [comment]
Here you go! Report ID: E45WKXBP

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5970](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.103.5968.issue-932.xpi) ("Merge branch 'master' into 932").

**Comment by retorquere** [comment]
Can you try again with build 5970? I don't expect the results to be different, but there's more logging.

**Comment by vtcarlino** [comment]
Tried with 5970: T3PYH4K6. Hope you'll manage to fix it!

**Comment by vtcarlino** [comment]
I see `{ | Latour, 2007 |  |  | zu:966903:CTRBUMIB }` in the browser. How is that even possible?

**Comment by retorquere** [comment]
I don't know, but that's what BBT produces. What happens after that is out of my control. From where do you call CAYW to get the `.`s?

**Comment by vtcarlino** [comment]
I use zotpick https://github.com/davepwsmith/zotpick-applescript to call CAYW in my editor of choice which is Scrivener.

**Comment by retorquere** [comment]
I don't have a Mac at hand, but it looks like you'd have to see what's in `theReference` after https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-scannable-cite.applescript#L24

**Comment by vtcarlino** [comment]
I'm a total newbie when it comes to programming (even AppleScript!) ... How do I check what's in `theReference`?

**Comment by retorquere** [comment]
I have no idea - perhaps best to ask the author of zotpick. I have no experience with applescript.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5996](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.103.5994.issue-932.xpi) ("odfscan").

**Comment by retorquere** [comment]
Can you give 5996 a go? It should output scannable-cite references without double spaces.

**Comment by vtcarlino** [comment]
5996 works great, the scannable-cite IDs are cleaner: `{ | Latour, 2007 | | | zu:966903:CTRBUMIB }`

**Comment by retorquere** [comment]
Cool, that's in the new release.
