### ISSUE TITLE
Dates incorrect when Zotero date field includes times

### ISSUE THREAD

**Issue by ckrf** [retorquere/zotero-better-bibtex#934]
References with times as well as dates in the date field, e.g., "2016/09/22 17:12:01" produced garbage dates in a document compiled on ShareLaTeX (which I think is pdflatex?)

Sorry for the incomplete report.

**Comment by retorquere** [comment]
Can you right-click the reference in Zotero and submit an BBT error report?

**Comment by retorquere** [comment]
Really can't do much without that error report.

**Comment by ckrf** [comment]
Sorry, I used a workaround and I no longer have the references which were causing problems. I understand that you can't do anything with more info.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 6034](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.107.6032.issue-934.xpi) ("fixes #934").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 6041](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.107.6039.issue-934.xpi) ("Juris-M is *really* slow to start up").

**Comment by retorquere** [comment]
I found the problem.
