### ISSUE TITLE
Unable to produce relative file paths for attachments in file: field when exporting

### ISSUE THREAD

**Issue by abradd** [retorquere/zotero-better-bibtex#935]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

My data directory is set to ~/zotero (with the storage folder internally that symlinks to another location so I can sync it across computers) in the Zotero preferences and my pdfs are exported via Zotfile to ~/literature. I saw an explanation for the current scheme of generating relative vs. absolute paths for the file: field in #654, but I am still unable to produce relative paths regardless of my selected export location. The ~/zotero/storage folder contains mostly html content from snapshots because I relocate the pdfs with Zotfile.

I have exported my .bib file to ~/zotero, ~, and ~/literature, but every time it produces an absolute path in the file: field. This applies for both the html content in ~/zotero/storage and the pdf content in ~/literature. Given the current implementation I don't really expect the pdf files to be defined relative paths under any case, but I am surprised the html content was not defined as a relative path.

**Comment by retorquere** [comment]
If you export to ~/literature where your attachments live, the path should automatically be relative. I will have a look.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.192.2655](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.192.2655.xpi) ("fixes #935 (I think)").

**Comment by FirasSadiyah** [comment]
@retorquere This build is working for me. Many thanks.

**Comment by retorquere** [comment]
A new release (.194) will be out soon, but it's just what you have now with a formal label on it. You will be upgraded autommatically, or you can force-update in the addons panel in 10 minutes or so when the tests have ran.
