### ISSUE TITLE
installation with Firefox 59.0.1

### ISSUE THREAD

**Issue by niconum** [retorquere/zotero-better-bibtex#937]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

I tried this morning to install betterBibTex (last release: v5.0.108) but my Firefox (59.0.1) tells me it's impossible because this add-on is not verified. I use zotero 5.0. Do you have information about this?
Thanks

**Comment by retorquere** [comment]
You have to install BBT in Zotero, not in Firefox: https://retorque.re/zotero-better-bibtex/faq/#are-there-any-plans-to-support-firefox-57
