### ISSUE TITLE
[zotero] citekey pattern does not render CJK characters

### ISSUE THREAD

**Issue by sati-bodhi** [retorquere/zotero-better-bibtex#938]
Citation keys for items containing CJK characters cannot be properly generated. They either end up empty or are replaced by question marks. Ex. ![Citekey not displaying properly](https://user-images.githubusercontent.com/7592695/37934815-17b7b92a-3182-11e8-9e76-eeebe3567a13.png)

Can this ~~bug be fixed~~ be changed?

**Comment by retorquere** [comment]
That's [not a bug](https://retorque.re/zotero-better-bibtex/citation-keys/); you almost certainly have the pattern set to `[zotero]`, and

> `zotero`: Generates citation keys as the stock Zotero Bib(La)TeX export does

`[zotero]` faithfully replicates the way Zotero generates citekeys in its own BibTeX generation, warts and all. I don't recommend its use, but if you have existing papers that use them it could be a reason to keep using it. You may want to try `[auth][Title][year]` or something like it instead.

**Comment by sati-bodhi** [comment]
The Citekey is automatically transliterated after changing its format. Gets a bit lengthy for certain titles, but at least identifiable. I was not able to refresh everything (11125 items) with one click after the redefinition. 

![2018-03-27 11 25 01](https://user-images.githubusercontent.com/7592695/37945198-9ef09720-31b1-11e8-8341-4505024d8210.png)

**Comment by retorquere** [comment]
Please right-click the references where you experience the export problem, select "Send Better BibTeX Error", and post the resulting report ID (shown in red after you submit) here.

**Comment by sati-bodhi** [comment]
It could be a processing power issue. Works fine when I do a dozen or so at a time. (But tedious work to update everything this way. )

**Comment by retorquere** [comment]
I really just need that debug log.

**Comment by sati-bodhi** [comment]
Here you go. 
Report ID: I2EJKMVK

**Comment by retorquere** [comment]
You have your pattern set to `[auth:lower][shorttitle][year]`, which will transliterate your key, see the [docs](https://retorque.re/zotero-better-bibtex/citation-keys/#generating-citekeys) on citekey configuration, especially the note under that section. You will have to set your pattern to `[Auth][Title][year]` or something like it instead (note the capitalization of `Auth` and `Title`).

**Comment by retorquere** [comment]
I don't see any errors in your log that would explain why you can't update your keys all at once, if you want me to check, click "restart with logging enabled" in the BBT error report window, let Zotero restart, try to refresh them all again, and send a new report.

**Comment by sati-bodhi** [comment]
Batch update is still problematic. 
Refreshing 100 items took 13 secs. So 11100 items should about take 24 minutes to update. 
This either causes Zotero to be unresponsive, or the process is (presumably) aborted altogether. 
The case is highly likely that Zotero just needs some time to run. The error report itself took a long time to generate. 
I'm trying to send you a new error report id, but it took ages and Zotero ended up giving me a network error pop-up msg. 
Other than that, Zotero is functioning normally. 

As with your previous suggestion, setting the pattern to `[Auth][Title][year]` doesn't change the transliteration behavior. 

I am attaching the Mac error report below when Zotero is forced to stop. See if it helps with your diagnosis. 

[zotero error maclog.txt](https://github.com/retorquere/zotero-better-bibtex/files/1854370/zotero.error.maclog.txt)

**Comment by retorquere** [comment]
11k items will take a while. If you want *all* keys regenerated, and you have no auto-export setup, removing better-bibtex.sqlite from the zotero folder while zotero is not running will regenerate everything at startup.

Wrt the transliteration - do you still have "force to plain text" on in the settings?

**Comment by sati-bodhi** [comment]
Yes, the option is still on the settings. But it has no effect on behavior, either.

**Comment by retorquere** [comment]
There's little I can do about the speed of refresh. I need to load the zotero object from the database in order to calculate the new key, and loading 11k items is just going to take a while.

**Comment by sati-bodhi** [comment]
It did not take very long for Zotero to generate the keys afresh when I just started using the Biblatex add-on. Don't see why refreshing should take a much longer time.

**Comment by sati-bodhi** [comment]
It works, thanks! ^ ^
