### ISSUE TITLE
literal "[?]" when with \cite

### ISSUE THREAD

**Issue by y2klol** [retorquere/zotero-better-bibtex#942]
Using BBT and TexStudio.
```
\documentclass{article}
\bibliography{honoursbib}
\begin{document}
Cite this\cite{PinkPalacepolicyOverell2009}
\end{document}
```
TexStudio autocompletes the citation so it's being read properly but when compiling I get a "[?]" as the citation.

**Comment by retorquere** [comment]
What does the entry for `PinkPalacepolicyOverell2009` in `honoursbib` look like?

**Comment by retorquere** [comment]
closing for lack of feedback
