### ISSUE TITLE
"[?]" citation when compiling using bibtex generated by BBT?

### ISSUE THREAD

**Issue by y2klol** [retorquere/zotero-better-bibtex#945]
When compiling using TexStudio using the \cite{} command results in a "[?]" on the pdf. using \cite{} autocompletes in TexStudio so it seems that TexStudio can read the bibfile. 

```
@book{JapaneserevolutionParisKawamura2004,
  langid = {english},
  location = {{Oxford}},
  title = {The {{Japanese}} Revolution in {{Paris}} Fashion},
  isbn = {978-1-85973-815-3},
  pagetotal = {x+198},
  publisher = {{Berg}},
  date = {2004},
  keywords = {Fashion designers France.,Fashion designers Japan.,Fashion France Asian influences.},
  author = {Kawamura, Yuniya}
}
```
This is for any reference (I have tried 15 references). I generated the bibtex file using BBT.

**Comment by retorquere** [comment]
That looks OK to me. Try compiling this:

```
\documentclass{article}
\usepackage[style=authoryear-comp]{biblatex}
\addbibresource{\jobname.bib}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{JapaneserevolutionParisKawamura2004,
  langid = {english},
  location = {{Oxford}},
  title = {The {{Japanese}} Revolution in {{Paris}} Fashion},
  isbn = {978-1-85973-815-3},
  pagetotal = {x+198},
  publisher = {{Berg}},
  date = {2004},
  keywords = {Fashion designers France.,Fashion designers Japan.,Fashion France Asian influences.},
  author = {Kawamura, Yuniya}
}
\end{filecontents}

\begin{document}

I'm citing \cite{JapaneserevolutionParisKawamura2004}

\printbibliography

\end{document}
```

**Comment by y2klol** [comment]
I copied and pasted and I got
![citing](https://user-images.githubusercontent.com/7161748/38407075-692e8d10-39bb-11e8-91b5-6c276ee9a98e.png)
It looks like the cite key and not author-date or number reference.

Will it look different when I cite it from the bibfile?

**Comment by retorquere** [comment]
No, the sample above is self-contained -- `\begin{filecontents}{\jobname.bib}...\end{filecontents}` just means "pretend there's a file present with name `\jobname.bib` with the following content. How many times have you compiled the document? You know you need multiple runs for bibliography right?

**Comment by retorquere** [comment]
Just to be clear -- we're not discussing a BBT problem here, we're just discussing a LaTeX compilation issue. The above MWE is correct and self-contained, and will compile to the following output in a correct setup:

```
I’m citing Kawamura 2004
References
Kawamura, Yuniya (2004). The Japanese Revolution in Paris Fashion. Oxford:
Berg. x+198. isbn: 978-1-85973-815-3.
```

If you're new to LaTeX, I can recommend starting with a service like Overleaf or ShareLaTeX. They have all the setup figured out for you, I use it heavily myself.

**Comment by retorquere** [comment]
No problem
