### ISSUE TITLE
The >X pseudofunction

### ISSUE THREAD

**Issue by bothide** [retorquere/zotero-better-bibtex#947]
I am not sure that I understand how the `>X` pseudofunction is expected to work.  The construct `[journal][>0]|[Archive]` works as described, i.e., produces the name of the Archive, e.g. the preprint archive "arXiv" where the not (yet) published article is uploaded to.

However, prepending this with something such as in the construct `[auth.etal]:[journal][>0]|[Archive]`
it will only produce the author name and not include the "arXiv" part.

Am I missing something here?

**Comment by retorquere** [comment]
`[auth.etal]:[journal][>0] | [Archive]` means:

* use `auth.etal`, append a `:`, and append `journal`. Use that if the resulting key so far is longer than 0
* Alternately, use the `Archive` field.

But since the first pattern always adds a `:`, it is guaranteed to be longer than zero, since it is at least one.

**Comment by bothide** [comment]
Thanks for the comment.  Even without the first ":", it will be longer than 0 (assuming there is at least one author name).  If not a bug, this feature, it seems to me, limits the usefulness of ">X".  This could be (partially) resolved by some kind of grouping/bracketing of a ">X" construct, allowing the
[journal][>0]:[Archive]
part to be evaluated independently of what precedes it.  It could look something like
"{[journal][>0] | [Archive]}",
"||[journal)[>0] | [Archive]||",
or that the length of anything that precedes the ">X" construct ("[journal][>0]") is neglected (or set to zero) before the evaluation.  There may be other ways to implement it, but of the three I mention, probably the third one is the one that will not break any existing "codes".

Of course, a nestable "if..then..else" function would be fantastic.  But that's probably asking too much.  So may even be the case for the above :-).

**Comment by retorquere** [comment]
I'm not sure what these patterns are mean to achieve, but vertical bars (`|`) have an existing meaning: they specify alternate patterns. `>x` can't neglect what precedes it, because it's meaning is exactly "if the length of what precedes me is not larger than `x`, skip to next pattern".

**Comment by bothide** [comment]
The patterns are meant to achieve a more generic functionalty that is able to generate an
[author]:[journal]:[year] citekey when that is appropriate, an
[author]:[Archive]:[year] when that is appropriate, an
[author]:Book:[year] and similar.  Examples from my .bib database:

@ARTICLE{Thide&al:PRL:2007, ....
@BOOK{Thide:Book:2009,...
@UNPUBLISHED{Thide&al:ARXIV:2010,...
@INPROCEEDINGS{Thide&al:SPIE:2014,...

I think this explains what I want to acheive.

**Comment by bothide** [comment]
Thanks.  I will test the =typeName method.  It might solve most of my problems.  However, I have not been able to find a (sufficiently detailed) documentation on how to use it.  For one thing, I have not been able to figure out what a proper "typeName" is.  Clearly, "book" is.

**Comment by retorquere** [comment]
It's not well documented TBH. The way to find out currently is to do a `BetterBibTeX JSON` export and look at the `itemType` for the reference you selected. I don't maintain the list (it's just the Zotero internal types) but they don't change in practice. The current list is:

artwork
attachment
audioRecording
bill
blogPost
book
bookSection
case
computerProgram
conferencePaper
dictionaryEntry
document
email
encyclopediaArticle
film
forumPost
hearing
instantMessage
interview
journalArticle
letter
magazineArticle
manuscript
map
newspaperArticle
patent
podcast
presentation
radioBroadcast
report
statute
thesis
tvBroadcast
videoRecording
webpage

**Comment by retorquere** [comment]
You can test for multiple by using e.g. `[=journalArticle/magazineArticle]`

**Comment by bothide** [comment]
Thanks a million!  Just out of curiosity, how are these related to the BibTeX pubication types?

**Comment by retorquere** [comment]
For biblatex it's steered using [this](https://github.com/retorquere/zotero-better-bibtex/blob/master/translators/Better%20BibLaTeX.ts#L149) mapping, unless you have a [csl type](https://github.com/retorquere/zotero-better-bibtex/blob/master/translators/Better%20BibLaTeX.ts#L149) set using the [cheater syntax](https://github.com/retorquere/zotero-better-bibtex/issues/587), and even then you can change it using a [postscript](https://retorque.re/zotero-better-bibtex/scripting/). Bibtex follows a similar strategy but uses a different [mapping](https://github.com/retorquere/zotero-better-bibtex/blob/master/translators/Better%20BibTeX.ts#L79).

The bib(la)tex types are not available at the time of key generation however. They get mapped during export, the key is calculated long before (and would in any case be different depending on whether you target bibtex or biblatex).

**Comment by bothide** [comment]
Great.  Thanks to your help, I am finally making some progress.

**Comment by retorquere** [comment]
Can we consider this issue closed?

**Comment by bothide** [comment]
For the time being, at least. I am still running tests of ever increasing
complexity and may come back with more later.

**Comment by retorquere** [comment]
That's ok, but a) that would be a feature request, not a bug report on the >x function, and b) my intention is not to make the pattern generator a fully fledged programming language. No guarantees on how much complexity I will add.
