### ISSUE TITLE
Automatic exports information hard to read

### ISSUE THREAD

**Issue by jackwasey** [retorquere/zotero-better-bibtex#956]
Automatic exports window cannot be resized on Mac or Linux in a way which shows more information.
Any export error messages are crushed into the Status line and cannot be read.
Unable to edit an automatic export once established
Would also be nice to be able to add an export from the Automatic export tab in Better BibTex.

Thanks for your work - so useful.

**Comment by retorquere** [comment]
Adding exports from the tab won't happen. I hate UI work, and adding from the tab I'd have to implement a collection picker. If I could do away with the autoexport tab I would, but it's the only way to see the exports you have or remove them.

Editing I could consider, but only for the checkboxes. Editing the collection would yield the same problem as above. Editing the target file... maybe. Also requires a file picker to pop up, but a file picker may well be standard in Zotero so perhaps I can use that.

Adding a field that displays the error is doable.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.135.6545.issue-956](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.135.6545.issue-956.xpi) ("treeview is seriously weird").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.135.6551.issue-956](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.135.6551.issue-956.xpi) ("fixes #956").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.135.6554.issue-956](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.135.6554.issue-956.xpi) ("proper labeling").

**Comment by retorquere** [comment]
can you see if 6554 looks better to you?

**Comment by jackwasey** [comment]
Thanks so much - will take a look
