### ISSUE TITLE
Zotero beta changes documentplugin to async, CAYW broken

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#958]

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.130.6456.issue-958](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.130.6456.issue-958.xpi) ("async cayw").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.130.6459.issue-958](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.130.6459.issue-958.xpi) ("xuloki drops methods").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.131.6470.issue-958](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.131.6470.issue-958.xpi) ("temporarily disable juris-m").

**Comment by retorquere** [comment]
fixed in Zotero
