### ISSUE TITLE
eprinttype field dropped on import

### ISSUE THREAD

**Issue by rzach** [retorquere/zotero-better-bibtex#959]
I have a BibTeX file with entries that include the "eprinttype" field. It's not imported into the Zotero "Extra" field, although "eprint" (and a non-standard "scholar" filed) are.

Report ID: ABQF99CE
Testcase: https://gist.github.com/rzach/b4fef20bb651e2abb57181348de5c468

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.132.6491.issue-959](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.132.6491.issue-959.xpi) ("fixes #959").

**Comment by retorquere** [comment]
Can you try 6491 (linked above)?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.132.6497.master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.132.6497.master.xpi) ("fixes #959").

**Comment by rzach** [comment]
Thanks!

**Comment by retorquere** [comment]
I'm assuming here that .133 indeed fixes your problem. I've added the gist as a testcase, but If you could confirm that'd still be very helpful.

**Comment by rzach** [comment]
Works!

**Comment by retorquere** [comment]
Cool, thanks.
