### ISSUE TITLE
The BBT Citation key format string is reset to the default after restarting Zotero

### ISSUE THREAD

**Issue by bothide** [retorquere/zotero-better-bibtex#960]
Report ID 4GK4M25R

Every time I restart Zotero, my own rather elaborate Citation key format string gets lost and replaced by the format string

`[auth:lower][shorttitle3_3][year]`

This means that I have to enter my own string (I do it by copying from a separate file end pasting it into BBT)  every time I start/restart Zotero. Is this to be expected or am I not doing the right thing or is it a bug?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.133.6509.issue-960](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.133.6509.issue-960.xpi) ("logging for #960").

**Comment by retorquere** [comment]
Can you get me a new log with 6509?

**Comment by bothide** [comment]
Done.  Report ID T68YTWUL

**Comment by retorquere** [comment]
Do you have a file `user.js` in your Zotero profile? If so, can you check whether that holds the old preference?

**Comment by bothide** [comment]
Sorry. I do not have a file called user.js in my own or in any other directory.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.133.6512.issue-960](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.133.6512.issue-960.xpi) ("more logging").

**Comment by retorquere** [comment]
Can you get me a new log from 6512?

**Comment by bothide** [comment]
Done.  Report ID: 2E6LTXGE
This one seems to work!  With 6512, a couple of tests show that my personal, long Citation format key string is now saved between Zotero sessions, at least on the one and the same local Linux (OpenSuSE Leap 42.3).  Will check if it also saved across other platforms (Windows, MacOS, Linux) that I use on my other computers  (shall I expect it to be saved?).

**Comment by retorquere** [comment]
I hate these kinds of problems. I really only added logging.

Preferences don't sync unfortunately. This is something that would need support from Zotero.

**Comment by retorquere** [comment]
wait, I think I see something in that last log.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.133.6521.issue-960](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.133.6521.issue-960.xpi) ("async prefs load... sure...").

**Comment by retorquere** [comment]
6521 locks out the pattern edit field until the Zotero DB is ready; I need the DB to be ready to read the supported reference types. Not a great fan, but this is how Zotero works.

**Comment by bothide** [comment]
OK.  I have tried the 6521 both on Linux and Windows 10 on my ThinkPad P50 and it works fine. Thanks!
