### ISSUE TITLE
Be more flexible for Extra field cheater syntax

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#967]
# Bug classification

## Exporting references

https://github.com/zotero/zotero/commit/1f320e1f5d5fd818e2c2d532f4789e38792a77a2 allows Zotero to more flexibly extract CSL variables from Extra (e.g., to use `Original Date:` rather than `original-date:`). It would be nice if BBT export could behave similarly.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6644.issue-967](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6644.issue-967.xpi) ("fixes #967").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.136.6647.master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.136.6647.master.xpi) ("fixes #967").
