### ISSUE TITLE
Is there a way to preserve citekeys when going from v4 to v5?

### ISSUE THREAD

**Issue by regua** [retorquere/zotero-better-bibtex#970]
I have finally updated both Zotero and Better BibTeX to v5, only to find that many of the citation keys have been changed. Is there a way to preserve the ones I had in v4? I would like to use the latest release of Zotero, but I don't want to have to change all of my LaTeX documents because of it...

**Comment by retorquere** [comment]
If you go into Preferences/Advanced/Files and Folders/Show Data Directory, Zotero will open your data directory. Can you confirm that there is a folder there called `better-bibtex` that has a file named either `db.json` or `db.json.migrated`?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.138.6695.issue-970](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.138.6695.issue-970.xpi) ("migrate v4 after initial key scan").

**Comment by retorquere** [comment]
Right, I get that, but I needed to know if the old database was still in place. I'm surprised to see that both are still present though, I had expected to see just one.

Can you get me a copy of both of those files?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.138.6698.issue-970](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.138.6698.issue-970.xpi) ("more verbose migration logging").

**Comment by retorquere** [comment]
I will need more detailed logging to see what's going on. In this case, it's a little involved, but here goes:

1. Install Zotero 5, install BBT test build 5.0.138.6698.issue-970 linked to above, **do not restart after installation**, go into `Help`, `Debug Output Logging`, `Restart with logging enabled`, then let Zotero restart
2. After the restart (and after BBT has finished initializing), verify that `db.json` is now renamed to `db.json.v4`.
3. Go into `Help` and select `Report Better BibTeX Errors...`
4. Post the debug ID you get here.

**Comment by retorquere** [comment]
And the file was renamed to `db.json.v4`, correct?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.138.6701.master](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.138.6701.master.xpi) ("fixes #970").

**Comment by regua** [comment]
> And the file was renamed to `db.json.v4`, correct?

That's right.

**Comment by retorquere** [comment]
Super, that's what I needed to know, it's now released as 5.0.139
