### ISSUE TITLE
What is pinning

### ISSUE THREAD

**Issue by ihincks** [retorquere/zotero-better-bibtex#971]
I am having trouble finding documentation about what exactly pinning is. What does it mean for something to be pinned or unpinned, and how does this interact with exported bibtex files?

I have inferred through experimentation that pinning and unpinning can (sometimes?) be used to update the bibtex key to my new format string.

Thanks for your patience with this simple question.

**Comment by retorquere** [comment]
No worries. Pinning just means that the citekey stays what it is at the time of pinning regardless of updates to the reference fields. Unpinning means follow any updates to the fields in the key, starting from the moment you unpin. Pinned keys don't change on refresh, unpinned keys can update.

**Comment by ihincks** [comment]
Thanks, that is clear.
