### ISSUE TITLE
Git auto push does not actually push changes to the repository on Windows

### ISSUE THREAD

**Issue by wittenator** [retorquere/zotero-better-bibtex#972]
# Bug classification
I tried to setup a pipeline for pdf creation from latex files in gitlab. Part of that endeavour is the git push support from betterbibtex. I set it up, added the git config in the repo and exported the collection with the right flag. Whenever I add a new item to the collection, the .bib file gets updated. Sadly the actual push to the remote git repo does not happen. I tried both saving the ssh key and the credentials for gitlab, because I suspected that that may be a reason for a silent failure. But it didn't help.
Did anyone encounter similar problems with this feature?

## Exporting references
 - FYA494LP (BibTeX)

## Non-export problems with BBT
- EX8RDSJ5

**Comment by wittenator** [comment]
T4D4R2MB
That's pretty interesting. I had a a look at the logs and apparently it doesn't even start the procedure. Just to be sure that I didn't fuck up the setup: Do I have to do anything else besides exporting the collection to an existing git repo and setting the config flag?

**Comment by retorquere** [comment]
It does start the procedure in the sense that it tries to probe if it's been set up, but it silently doesn't finish the probe -- how it does that I don't know. Can you try again with 6720?

There's nothing to configure outside these two:

- Set up collection for autoexport
- Configure with `git config zotero.betterbibtex.push true`

in any order, and that should be it. It works on my end. The new log should be able to tell me more.

**Comment by wittenator** [comment]
WMC7QTRI
Then it can't be that. Hmm, that's getting really interesting!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6726.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6726.issue-972.xpi) ("only test for parent dir existence, not bib file").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6725.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6725.issue-972.xpi) ("only test for parent dir existence, not bib file").

**Comment by retorquere** [comment]
And finally, it's back. Can you get me a new log from 6725?

**Comment by wittenator** [comment]
UB8H79FL
By mistake I destroyed my last OS and had to do a fresh install from scratch. Interestingly enough, even after the fresh install this problem persists.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6744.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6744.issue-972.xpi) ("even more logging").

**Comment by retorquere** [comment]
That's a pretty costly mistake.

It looks like it's just suddenly stopping mid-detect. I log whether it could find the config yes/no and it's simply not getting there. You do have extended debugging on right? Can you try again with 6744?

**Comment by wittenator** [comment]
HLIUN39U
For every new build I restart the whole application with debugging enabled and try to add a file to the exported collection or force an export with the corresponding menu option. Is there an option to enhance the output logs even more?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6747.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6747.issue-972.xpi) ("whut. isFile fails?").

**Comment by retorquere** [comment]
It says it can't open `/home/tim/Projects/the_status_quo_of_energy_sector_blockchain/text/.git/config`. Can you try again with 6747?

**Comment by retorquere** [comment]
(there's no way to expand the logs more. I was just surprised to see the logging stop mid-detect, but I think I may have a handle on that particular problem now)

**Comment by wittenator** [comment]
8N58NXTT
Ahh, I see. Betterbibtex seems to assume that any export is always saved to the root of a git repo (I exported to a folder in a git repo until now - that could be a feature request.) Now it also starts logging, but still doesn't push it.

**Comment by retorquere** [comment]
I do assume the bib file is in the repo root. It's a performance issue -- I do not want to walk all parent directories to the root of the disk just to find out if I'm in a git repo.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6750.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6750.issue-972.xpi) ("even more logging").

**Comment by retorquere** [comment]
You know the spiel

**Comment by wittenator** [comment]
UMCYBV5D
Hmm, I think that a note in the docs could be really helpful. Should I open an enhancement ticket ?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6758.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6758.issue-972.xpi) ("ambiguous true").

**Comment by retorquere** [comment]
as always

**Comment by retorquere** [comment]
Do you have a windows machine you could test on BTW? I may have a solution for files not in the root of the repo but there are cross-platform issues I need to assure I've tackled.

**Comment by retorquere** [comment]
(and I don't have a windows machine)

**Comment by wittenator** [comment]
I am going to send the output later today. And I have a Windows machine and a VM to test on (Win7 and Win10 respectively). Did you also stumble upona way to get the git root folder via 'git rev-parse --show-toplevel' and use it with command substitution?
BTW: Is there any documentation on how to build the .xpi from the repo? Then I could also help in finding the bug myself.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6776.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6776.issue-972.xpi) ("root-push only").

**Comment by retorquere** [comment]
If you clone the repo, and you have `node` and `yarn` installed, this should do it:

```
git checkout 972
yarn install
yarn run build
```
the xpi will end up in the `xpi` directory. There's also a second xpi there (debug-bridge), but you *don't* want to install that unless you want to run automated tests, which require a lot more setup. Having the debug bridge installed is a security risk (to your library, not to your computer in general), you really don't want it unless you're running tests on a system you trust.

The latest code in the `972` branch has code to do pushes of files deeper in the repo. Tests on that are running and it should be announced here in a few minutes by @blip-bloop.

I've looked at `git rev-parse --show-toplevel` but finding the root isn't the problem (rev-parse is going to do essentially the same, walking the parent dirs until it finds `.git` in them) but to find the relative path between the repo root and the bibfile. The javascript environment BBT is running in doesn't have an API to get a relative path from two absolute paths; I'm doing string comparisons now but that's a little iffy cross-platform, and I can't test on Windows.

**Comment by retorquere** [comment]
(missed one: what do you mean by command substitution?)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.139.6780.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.139.6780.issue-972.xpi) ("deeper git pushes").

**Comment by retorquere** [comment]
The stuff we're looking at lives [here](https://github.com/retorquere/zotero-better-bibtex/blob/972/content/auto-export.ts#L291)

**Comment by retorquere** [comment]
(the build process outputs some lint warnings and an error from the docs parser, these can be ignored. If the build fails for other errors, those cannot be ignored)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.141.6801.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.141.6801.issue-972.xpi) ("new build").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.141.6804.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.141.6804.issue-972.xpi) ("compacter").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.141.6806.issue-972](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.141.6806.issue-972.xpi) ("better varnames").

**Comment by retorquere** [comment]
Any feedback? I think I have it now, even for bib files that don't sit at the repo root, but confirmation would be much appreciated.

**Comment by retorquere** [comment]
Assuming fixed

**Comment by wernersa** [comment]
This is still an issue for Windows.

Getting this in the log:

`{better-bibtex +16} git.init: git not found: <Error: Executable not found: git.exe# SubprocessWin.pathSearch<@resource://gre/modules/subprocess/subprocess_win.jsm:162:17 TaskImpl_run@resource://gre/modules/Task.jsm:319:42 TaskImpl@resource://gre/modules/Task.jsm:277:3 createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14 pathSearch@resource://gre/modules/Subprocess.jsm:157:16 init@chrome://zotero-better-bibtex/content/common.js:53709:30 init@chrome://zotero-better-bibtex/content/common.js:53934:15 init@chrome://zotero-better-bibtex/content/common.js:54703:15 >
`

Checked system environment "PATH" which includes: `C:\Program Files\Git\cmd`

Also, the conditional inclusion of `.exe` should not be neccesary, as the Subprocess.pathSearch() function parses the PATHEXT environment, which includes the extensions.

**Comment by retorquere** [comment]
Is PATHEXT always set on Windows? I don't have a Windows machine.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3385](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3385.xpi) ("pathsearch does extensions?")

Install in Zotero by downloading [test build 5.1.45.3385](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3385.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 3385?

**Comment by wernersa** [comment]
Also tried running as administrator, doesn't make a difference.

Noticed that my environment %PATH% variable was named "Path", tried changing this to "PATH" as windows reads the environment case-insensitive. Still no change.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3388](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3388.xpi) ("EDTF date export")

Install in Zotero by downloading [test build 5.1.45.3388](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3388.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by wernersa** [comment]
Great! It works perfectly 👍 !

Output from log:
`(3)(+0000018): {better-bibtex +18} pathSearch: looking for git in C:\Program Files (x86)\Zotero;C:\Python37\Scripts\;C:\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;

(3)(+0000140): {better-bibtex +140} pathSearch: git found at C:\Program Files\Git\cmd\git.EXE`


Output from `git log`:
`> git log
commit ada6eb995dd721295xx415x3039193f016e51019 (HEAD -> master, origin/master, origin/HEAD)
Author: Werner Sævland <werner.saevland@gmail.com>
Date:   Sun Jan 27 16:33:00 2019 +0100

    BibLaTeX updated by Better BibTeX for Zotero`

Great job Emiliano 🥇 !

The only downside with Zotero.Utilities.Internal.exec() is that it opens 5 different cmd windows sequentially in the foreground, which could get a bit annoying when exporting on update. It would be great if it could be possible to execute all commands in the same process, of if the process launched was done silently (in the background). I'm not sure if either is possible though.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3395](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3395.xpi) ("startHidden")

Install in Zotero by downloading [test build 5.1.45.3395](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3395.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
All at once is not possible, since the sequence must be

1. git pull (to make sure we don't get merge conflicts in the last step, I am *not* going to create an UI to deal with merge conflicts)
1. create bib
1. add/commit/push

so there's a need for at least two calls. But try 3395.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3407](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3407.xpi) ("5.1.46")

Install in Zotero by downloading [test build 5.1.46.3407](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3407.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by wernersa** [comment]
Auto-export doesn't work in 3395

`(1)(+0000004): {better-bibtex! +4} could not pull in B:\directory: <Error: Cannot modify properties of a WrappedNative# exec@chrome://zotero-better-bibtex/content/common.js:55126:9 pull@chrome://zotero-better-bibtex/content/common.js:55098:19 run@chrome://zotero-better-bibtex/content/common.js:55216:19 run@chrome://zotero-better-bibtex/content/common.js:55329:9 run@chrome://zotero-better-bibtex/content/BetterBibTeX.Preferences.js:158:9 oncommand@chrome://zotero/content/preferences/preferences.xul#better-bibtex:1:1 gViewController.commands.cmd_showItemPreferences.doCommand@chrome://mozapps/content/extensions/extensions.js:1193:9 gViewController.doCommand@chrome://mozapps/content/extensions/extensions.js:1530:5 showPreferences@chrome://mozapps/content/extensions/extensions.xml:1555:11 oncommand@chrome://mozapps/content/extensions/extensions.xul:1:1 >`

There was no other related errors

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3416](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3416.xpi) ("cannot modify environment dict")

Install in Zotero by downloading [test build 5.1.46.3416](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3416.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by wernersa** [comment]
Tried 3416, and it broke the pathsearch:
`(3)(+0000014): {better-bibtex +14} git.init: git not found: <Error: Executable not found: git# SubprocessWin.pathSearch<@resource://gre/modules/subprocess/subprocess_win.jsm:162:17 TaskImpl_run@resource://gre/modules/Task.jsm:319:42 Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:932:23 this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7 this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11 >`

**Comment by retorquere** [comment]
There must be something just before it if you have extended logging on with `pathSearch: looking for`

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3420](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3420.xpi) ("firefox is pretty finnicky")

Install in Zotero by downloading [test build 5.1.46.3420](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3420.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
No worries -- I thought you had used it before but that was the OP. Can you try 3420 with both `PATH` and `PATHEXT` in capitals? Firefox seems very finnicky about env vars, and the only other option would be to re-implement pathSearch myself. I will if I must but I'd rather not.

**Comment by wernersa** [comment]
Still doesnt work :/

My environment:
https://transfer.sh/141dPo/SystemPropertiesAdvanced_2019-01-29_13-36-30.png

```
(3)(+0000000): {better-bibtex +0} pathSearch: looking for git

(1)(+0000014): {better-bibtex! +14} pathSearch: PATH not set

(3)(+0000000): {better-bibtex +0} git.init: git not found
```

Report-ID: 93X4DA5X-euc

Submitted with Debug ID: D1453173287

**Comment by retorquere** [comment]
And if you type `set` in a command window?

**Comment by wernersa** [comment]
Pretty sure that would be restricted in scope to the process of that
specific terminal window.

Didn't do any change

Den tir. 29. jan. 2019 kl. 15:35 skrev Emiliano Heyns <
notifications@github.com>:

**Comment by retorquere** [comment]
Why would that be restricted in scope? AFAIK windows has two sets of environment variables -- system-wide (are set for everyone) and user-specific (only apply to the logged in user and override system-wide). I'm not aware of any app-specific level of env vars for windows.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3421](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3421.xpi) ("reimplement pathSearch")

Install in Zotero by downloading [test build 5.1.46.3421](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3421.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
3421 has my own implementation of pathsearch, give that a go.

**Comment by wernersa** [comment]
Pathsearch works now, although you successfully had pathsearch working in [3388](https://github.com/retorquere/zotero-better-bibtex/issues/972#issuecomment-457929872) though. The same problem persists as in [3395](https://github.com/retorquere/zotero-better-bibtex/issues/972#issuecomment-458291368):

`(1)(+0000038): {better-bibtex! +38} could not pull in B:\overleaf: <Error: Cannot modify properties of a WrappedNative# exec@chrome://zotero-better-bibtex/content/common.js:55246:9 pull@chrome://zotero-better-bibtex/content/common.js:55218:19 run@chrome://zotero-better-bibtex/content/common.js:55334:19 run@chrome://zotero-better-bibtex/content/common.js:55456:9 run@chrome://zotero-better-bibtex/content/BetterBibTeX.Preferences.js:158:9 oncommand@chrome://zotero/content/preferences/preferences.xul:1:1 >
`

Report-ID: L2R8NVSM-euc

**Comment by retorquere** [comment]
Ah dammit. Zotero builds on an old Firefox version (52.9.0esr), and that ability to start programs without a shell popping up on Windows wasn't added until Firefox 55. There's nothing I can do about this.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3422](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3422.xpi) ("first init, then startHidden")

Install in Zotero by downloading [test build 5.1.46.3422](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3422.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I'm building 3423 now which should work (and should work with any spelling of the `path` variable on Windows) but the shells popping up is out of my hands. I can look at whether I can minimize the number of calls, but two is the minimum for the reason I outlined above.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.46.3423](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3423.xpi) ("Zotero builds on an old FF, this won't work")

Install in Zotero by downloading [test build 5.1.46.3423](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.46.3423.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
In windows you might be better off with running sparkleshare until Zotero upgrades to FF55+

**Comment by retorquere** [comment]
5 is actually the minimum because I can't chain commands into 1 using the api I can use.

**Comment by wernersa** [comment]
Thanks for trying to work it out! Great job :)
