### ISSUE TITLE
Picker not always appearing on top in Windows when calling CAYW url

### ISSUE THREAD

**Issue by AmomentOfMusic** [retorquere/zotero-better-bibtex#973]
I have written a [powershell script for Windows 10](https://github.com/AmomentOfMusic/Zotero_scrivener_picker_windows) which makes a curl request to insert citations into Scrivener. For the most part, it works great.

My main issue is that the picker, the first time it is called, does not appear on top, but rather buried under my other active windows. After the first time I manually bring it to the top, Windows seems to "remember" it's position and the subsequent times I call up the picker, it does remain on top. That is, until I change my active window and then the problem happens again.

I cannot seem to fix the problem on my end with commands such as ["setforegroundwindow"](https://stackoverflow.com/questions/2556872/how-to-set-foreground-window-from-powershell-event-subscriber-action/2560504#2560504) for two reasons:

1. If I put the setforegroundwindow command before the curl request, the picker window doesn't exist yet, so it obviously can't be called to the front
2. If I put the setforegroundwindow command after the curl request, the command only gets executed *after* it has sent it's response and the picker itself has been closed.

The only solution so far is to set the entire Zotero application as the foreground window before calling the picker, but this has the obvious disadvantage of flashing the entire Zotero interface in front of Scrivener before entering the citation - I'd like to have it work like the word plugin where only the picker is called to the front.

Is there anyway on your end to set certain parameters to the picker when it is called up so that it appears on top in Windows? Or perhaps to embed a "setforegroundwindow" command into the code once the picker is called up but *before* it sends the response?

I am also willing to accept that the answer is: "windows is stupid, get a mac!" or "use a better programming language for your script"

I am using the latest version of both Zotero and betterbibtex

**Comment by retorquere** [comment]
I think this is a Zotero bug; I've seen this behavior too with just calling up the picker from Word. There's nothing I can do about this -- I don't actually call up the picker, I just ask Zotero to put up the picker. I've opened the issue [here](https://groups.google.com/forum/#!topic/zotero-dev/BXeM4mxDKXc), they may need your help to reproduce.

**Comment by AmomentOfMusic** [comment]
Hmm, okay, I will remain on standby, hopefully there is something they can do on their end

**Comment by retorquere** [comment]
There's really nothing else I can do. I don't control the picker, and as mentioned I have seen the same behavior under Word on Windows. Usually the best way to get things moving in Zotero is to replicate the problem under their primary intended use (Word/LibreOffice) and post on forums.zotero.org. Can you see whether you have the same problem using Word/LibreOffice?

**Comment by AmomentOfMusic** [comment]
I can reproduce the problem in LibreOffice, but not Word. The picker in LibreOffice no longer comes to the front if I maximize, then minimize the Zotero window. Both show up on top when first called, unlike the BBT picker, so I am wondering what they have done to ensure this behaviour.

In any case, I will do as you suggest and post this issue on the Zotero forums. Thanks for the response.

**Comment by retorquere** [comment]
Thanks. I've seen the response on the forums; not very encouraging, but there's really nothing I can do on the BBT end about this (short of digging into Zotero and fixing the bug there)
