### ISSUE TITLE
BBT Does Not Load: "Better BibTeX failed to load: <Error: update: validation failed…"

### ISSUE THREAD

**Issue by oncomouse** [retorquere/zotero-better-bibtex#974]
- [x] I have verified in the Zotero addons screen that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Report ID: PJUECUD8

I'm having a problem with Better BibTeX not starting. The Initializing message says "Loading citation keys" and never vanishes. It started occurring after I upgraded to the newest version of the extension (for some reason I was using a year-old version previously, as Zotero has not been automatically updating extensions).

In looking through the report I submitted, I notice the error I copied+pasted below. It's particularly weird because I have deleted that citation from my database (and emptied the trash) but the error is still occurring.

Clicking on reset cache and re-scan citation keys in the preferences does not seem to do anything, either.

I have removed and reinstalled the extension multiple times, which has not helped.

## Report Error

~~~
(3)(+0000016): {better-bibtex} update: validation failed for {"itemID":2096,"libraryID":1,"pinned":false,"citekey":"BernalWorldFleshDevil2018","extra":"","meta":{"revision":0,"created":1527102495788,"version":0},"$loki":1067} [{"keyword":"additionalProperties","dataPath":"","schemaPath":"#/additionalProperties","params":{"additionalProperty":"extra"},"message":"should NOT have additional properties"}] <Error: update: validation failed for {"itemID":2096,"libraryID":1,"pinned":false,"citekey":"BernalWorldFleshDevil2018","extra":"","meta":{"revision":0,"created":1527102495788,"version":0},"$loki":1067} ([{"keyword":"additionalProperties","dataPath":"","schemaPath":"#/additionalProperties","params":{"additionalProperty":"extra"},"message":"should NOT have additional properties"}]) @chrome://zotero-better-bibtex/content/common.js:8121:21 exports.DB.init@chrome://zotero-better-bibtex/content/common.js:5542:13 >

(3)(+0000000): {better-bibtex} Better BibTeX failed to load: <Error: update: validation failed for {"itemID":2096,"libraryID":1,"pinned":false,"citekey":"BernalWorldFleshDevil2018","extra":"","meta":{"revision":0,"created":1527102495788,"version":0},"$loki":1067} ([{"keyword":"additionalProperties","dataPath":"","schemaPath":"#/additionalProperties","params":{"additionalProperty":"extra"},"message":"should NOT have additional properties"}]) @chrome://zotero-better-bibtex/content/common.js:8121:21 exports.DB.init@chrome://zotero-better-bibtex/content/common.js:5542:13 >
~~~

**Comment by retorquere** [comment]
A year ago that's probably still a beta; the beta has stuff in the DB that transitional versions cleaned up, but that cleanup is now no longer present.

I can either clean up the `better-bibtex.sqlite` database manually if you get me a copy (not hard), or you can remove it altogether (all keys will be regenerated and you will lose auto-export). Either of these will let BBT start up normally.

**Comment by retorquere** [comment]
The early beta's didn't update automatically, so it's very likely you're on a pre-release.

**Comment by oncomouse** [comment]
Deleting the DB worked! Thanks so much!
