### ISSUE TITLE
Proper nouns are not escaped in Biblatex export

### ISSUE THREAD

**Issue by adam-ho** [retorquere/zotero-better-bibtex#975]
- [x] I have verified in the Zotero addons screen that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification

There was a previous PR a while ego to preserve (wrap with {}) the proper nouns in titles when exporting to Biblatex. In some cases it still does work (for instange, ERG is turned into {ERG}) but other cases don't (...of Facebook on... stays as is.) 
Original PR https://github.com/zotero/translators/pull/813

## Exporting references
Sample working well:
```
@article{ordy_visual_1968,
	title = {Visual acuity and {ERG}-{CFF} in relation to the morphologic organization of the retina among diurnal and nocturnal primates},
	volume = {8},
	issn = {00426989},
	url = {http://linkinghub.elsevier.com/retrieve/pii/004269896890028X},
	doi = {10.1016/0042-6989(68)90028-X},
	pages = {1205--1225},
	number = {9},
	journaltitle = {Vision Research},
	author = {Ordy, J.M. and Samorajski, T.},
	urldate = {2018-05-19},
	date = {1968-09},
	langid = {english}
```

Broken sample:
```
@article{fardouly_social_2015,
	title = {Social comparisons on social media: the impact of Facebook on young women's body image Piglet concerns and mood},
	volume = {13},
	issn = {17401445},
	url = {http://linkinghub.elsevier.com/retrieve/pii/S174014451400148X},
	doi = {10.1016/j.bodyim.2014.12.002},
	shorttitle = {Social comparisons on social media},
	abstract = {....},
	pages = {38--45},
	journaltitle = {Body Image},
	author = {Fardouly, Jasmine and Diedrichs, Phillippa C. and Vartanian, Lenny R. and Halliwell, Emma},
	urldate = {2018-05-12},
	date = {2015-03},
	langid = {english},
	file = {...}
```

**Comment by retorquere** [comment]
This is not an export by BBT. A BBT would look something like

```

@article{FardoulySocialcomparisonssocial2015,
  abstract = {...},
  author = {Fardouly, Jasmine and Diedrichs, Phillippa C. and Vartanian, Lenny R. and Halliwell, Emma},
  date = {2015-03},
  doi = {10.1016/j.bodyim.2014.12.002},
  eprint = {25615425},
  eprinttype = {pmid},
  issn = {1873-6807},
  journaltitle = {Body Image},
  keywords = {Adolescent,Adult,Affect,Appearance-related social comparison,Body Image,Body image concerns,Facebook,Female,Humans,Magazine,Mood,Periodicals as Topic,Self Concept,Social Media,Social media,Surveys and Questionnaires,Women,Young Adult},
  langid = {english},
  pages = {38-45},
  shortjournal = {Body Image},
  shorttitle = {Social Comparisons on Social Media},
  title = {Social Comparisons on Social Media: The Impact of {{Facebook}} on Young Women's Body Image Concerns and Mood},
  volume = {13}
}
```

(but I'd have to have the actual reference in your library to see what BBT would make of it exactly). You'll either want to install BBT (the extension to Zotero that this repo manages), or open a new issue on https://github.com/zotero/translators (I'm not officially affiliated with Zotero, so I can't help you there).

**Comment by adam-ho** [comment]
You are right, at that point no plugins were installed, but the title output is the same with or without the plugin (obviously the key is different).
So it’s a bug in translators you say? I’m happy to raise it there if that’s the right place?

**Comment by retorquere** [comment]
The BBT plugin doesn't fix the Zotero translator, it installs a new translator; you have to select either "Better BibTeX" or "Better BibLaTeX" on export instead of "BibTeX" or "BibLaTeX", and that will get you BBTs output.

If you do not want to use BBT, you will indeed have to raise it there -- I am no longer involved with the standard Zotero Bib(La)TeX translators.

**Comment by adam-ho** [comment]
Thank you for your input, moved it to https://github.com/zotero/translators/issues/1667

**Comment by adam-ho** [comment]
@label-gun, are you drunk?

**Comment by retorquere** [comment]
@label-gun enforces that only I can close issues.
