### ISSUE TITLE
Hyphenated last names not escaped properly (or at all) in BibTeX

### ISSUE THREAD

**Issue by Hyphenated-Name** [retorquere/zotero-better-bibtex#976]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

I have a hyphenated last name. I.e., my name looks like "Firstname Last-Name". I believe that the proper way to handle such names in BibTeX is

```
@inproceedings{LasPaperWhose,
  title = {A paper whose author's last name is hyphenated},
  author = {Last{-}Name, Firstname}
}

```
(Note the curly braces around the hyphen.) At least, this is what I've always done. I've also seen the entire last name surrounded in curly braces, which seems fine too, though maybe this causes issues in more complicated cases.

Currently, my name is entered as [Last-Name][Firstname] in Zotero, and Better BibTeX outputs the following:

```
@inproceedings{LasPaperWhose,
  title = {A paper whose author's last name is hyphenated},
  author = {Last-Name, Firstname}
}
```

I.e., it does not put any curly braces to account for the hyphen. The issue with this is that BibTeX treats me as though I am two people! I.e., instead of the citation rendering as [L] or [Last] or whatever, it renders as [LN], as though there is an author whose last name is "Last" and another whose last name is "Name". 

Here's a minimal running example to make sure we're on the same page. With the Better BibTeX output above, the following code

```
\documentclass[11pt]{article}

\begin{document}

\cite{LasPaperWhose}

\bibliographystyle{alpha}
\bibliography{HyphenatedName}

\end{document}
```

renders as

> [LN]
> 
> **References**
> 
> [LN] Firstname Last-Name. A paper whose author's last name is hyphen-
> ated.

With the correct BibTeX that escapes the hyphen, it renders as

> [Las]
> 
> **References**
> 
> [Las] Firstname Last-Name. A paper whose author's last name is hyphen-
> ated.

(Sorry if this is overly detailed. I know that most of these are far too vague, so I'm trying to avoid that pitfall.)

I tried a few alternatives like [Last{-}Name][Firstname], but I couldn't find anything that rendered properly. I tried searching for others with the same issue that had workarounds, but the closest I found was https://github.com/retorquere/zotero-better-bibtex/issues/565, which makes it seem as though Better BibTeX is expected to handle this itself.

I am exporting as BibTeX. I have the latest version. I submitted an error with Report ID YN457R2G.

Thank you for your time and for making a great product :).

**Comment by retorquere** [comment]
I don't know whether it's the preferred method; I know (perhaps surprisingly) little about bib(la)tex, which is why I hailed @njbart, who know a lot about them.

The quotes are a standard feature of zotero (it will also work in word eg), but I don't know where it's documented.

**Comment by Hyphenated-Name** [comment]
Ok... this fix has a very annoying problem. It breaks when I add the #LaTeX tag to the document (which as I understand it is necessary when the title contains TeX). Is <pre></pre> preferred to using #LaTeX, since #LaTeX seems to be a more "global" tag that affects more fields.

**Comment by retorquere** [comment]
`#LaTeX` affects almost all fields. If you use `#LaTeX`, you can just use `Last{-}Name` in the lastname field, BTW.

There's no real categorical preference between `#LaTeX` or `<pre>`. If quoting (without `#LaTeX`) doesn't do the right thing, I could look into fixing it, but I'd have to ask @njbarI what's best to do.

**Comment by njbart** [comment]
Wrapping a string in Zotero’s last name field in double quotes should be used for one purpose only: influencing Zotero’s parsing decisions if the string starts with a lower-case element, i.e., distinguishing `von Braun` (to be parsed as particle + last name) from `"von Braun"` (one multi-part last name).

Since Zotero (and BBT) have no difficulty parsing `Last-Name` as one multi-part last name, double quotes shouldn’t have to be used in Zotero in such cases.

What BBT could do is to add curly braces around either just the hyphen(s), or the complete (fully parsed) last name if it contains hyphen(s). Note that this seems to be necessary for bibtex only; biblatex, using its `alphabetic` style, does output a `[Las18]` label in the absence of any additional hyphens.

**Comment by retorquere** [comment]
But that would be the fully parsed last name, excluding particles, right?

**Comment by retorquere** [comment]
@Hyphenated-Name can you right-click an actual reference you have that has such a name and send a BBT error report? Then I can include it as a test case.

**Comment by njbart** [comment]
> But that would be the fully parsed last name, excluding particles, right?

Right.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.141.6884.issue-976](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.141.6884.issue-976.xpi) ("test cases for #976").

**Comment by retorquere** [comment]
6884 contains the fix (for BibTeX, not BibLaTeX). I'd appreciate feedback on whether that solves the issue for you.

**Comment by Hyphenated-Name** [comment]
Thanks so much for the incredibly rapid fix! :)

It looks good on first inspection. It's a little annoying for me that it doesn't play nicely with the #LaTeX tag, but maybe that's a feature and not a bug. I'll try it out more extensively when I have more time, and I'll let you know if I find any issues.

**Comment by retorquere** [comment]
This is definitely a feature. `#LaTeX` means "yo BBT, get out of my way, I got this, I'll put raw latex code *everywhere*". If you don't want to type raw latex *everywhere* in that reference, don't use `#LaTeX`. You  can think of `#LaTeX` as wrapping every field in Zotero with `<pre>...</pre>`.
