### ISSUE TITLE
Export unicode as plain text fails for Vietnamese characters

### ISSUE THREAD

**Issue by deleporte** [retorquere/zotero-better-bibtex#977]
This bug concerns the encoding of .bib files at export (with Better Bibtex or Better Biblatex). In the options panel there is a tick box "Export unicode as plain tex". This feature seams to work properly for standard diacritics such as

á à â ä ã ǎ.

However it does not work for the vietnamese underdot : if a field contains the following character
ạ
then Better bib(la)tex will keep it as is instead of converting it to {\d a}.

This is quite surprising as vanilla zotero supports plain text translation of vietnamese characters. I cannot locate the part of the source code where these encoding changes are dealt with.

Alix

**Comment by retorquere** [comment]
It's an oversight in the mapping table. Can you right-click that reference and get me a BBT debug report? I'd like to add it as a test case.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.142.6897.issue-977](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.142.6897.issue-977.xpi) ("adjust tests for #977").

**Comment by retorquere** [comment]
Can you also try 6897 to see if it fixes the problem for you?

**Comment by deleporte** [comment]
Hi,

6897 indeed fixes the problem.

The report ID is TU473C26, unfortunately I created it *after* installing 6897 so that the BBT version shown is wrong (it should be 5.0.142).

**Comment by retorquere** [comment]
That is no problem, I just needed the source reference.

**Comment by deleporte** [comment]
So do I need to send anything else?

**Comment by deleporte** [comment]
This reference actually has an ọ. It has the same behaviour as ạ.

**Comment by retorquere** [comment]
OK, but that seems to output correctly then. If you consider this a representative sample of the problem, I can cut a release.

**Comment by retorquere** [comment]
(these two characters are however handled individually, not as a class-of-characters-with-a-dot. `ọ` could work and `ạ` not. I just have a mapping table for each individual character)

**Comment by deleporte** [comment]
I understand this, I should have been more precise in my original message. This is indeed a representative sample of the problem.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.142.6900.issue-977](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.142.6900.issue-977.xpi) ("test cases for #977").

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.142.6901.issue-977](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.142.6901.issue-977.xpi) ("it helps to actually run the tests").

**Comment by retorquere** [comment]
No problem, just wanted to make sure. And thanks for reporting it, turns out there were more symbols I had missed. 5.0.143 has been scheduled for a release and should drop in 10 minutes or so; you will be updated automatically, but it's just what you have right now under a different name.

**Comment by retorquere** [comment]
> This is quite surprising as vanilla zotero supports plain text translation of vietnamese characters. I cannot locate the part of the source code where these encoding changes are dealt with.

The mapping lives [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/translators/bibtex/unicode_translator.json).
