### ISSUE TITLE
braces after textemdash followed by unicode

### ISSUE THREAD

**Issue by marquistj13** [retorquere/zotero-better-bibtex#980]
In the generated bib file, I want  all the em dash in the bib item title to be recognized as `\textemdash{}`, instead of `\textemdash`.

This is already the case when the bib item is in English.
e.g.
for the original title `System identification—a survey`, the bib item is
```tex
@article{aastrom_system_1971,
  title = {System Identification\textemdash{}a Survey},
```

However, when the bib item is in Chinese, the em dash is recognized as `\textemdash`
e.g.
for the original title`基于支持向量机的降雨—径流预测研究`, the bib item is 
```tex
@article{__2009-6,
  title = {{基于支持向量机的降雨\textemdash径流预测研究}},
```
and , I want it always to be `\textemdash{}`
because `\textemdash` followed by a character may cause the xelatex engine to fail.

I use `Better Bibtex` to produce the above examples.

Hope someone can fix this problem.
thanks.

**Comment by retorquere** [comment]
Can you submit a BBT error report? (not to put too fine a point on it, but the issue template requests it for a reason)

**Comment by retorquere** [comment]
(to be specific: right-click the reference and submit an error report)

**Comment by retorquere** [comment]
(also: someone is by necessity me, since I'm the only dev here)

**Comment by marquistj13** [comment]
Report ID:  `4NACBANR`

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.145.6976.issue-980](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.145.6976.issue-980.xpi) ("test cases for #980").

**Comment by retorquere** [comment]
Can you try 6976 and see if that works for you?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.145.6979](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.145.6979.xpi) ("ncu").

**Comment by marquistj13** [comment]
Yes，it works. 👍

**Comment by retorquere** [comment]
Would a space work equally well as `{}`?
