### ISSUE TITLE
Ctrl+Shift+C doesn't work, but edit/"Copy as Better Biblatex" does

### ISSUE THREAD

**Issue by hagenblix** [retorquere/zotero-better-bibtex#982]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export-related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

# Bug classification
I installed zotero and the better-bibtex plugin, both in their most up to date version. I am running Windows 10. Under Preferences/Export, I have selected Better Biblatex.
When I select a reference, and press ctrl+shift+c, I get a grayed out version of the window, but without the high DPI scaling applied. It covers the full screen, including the taskbar. Afterwards, pasting is empty (even if something was there before). However, when I select "Copy as Better Biblatex" under the edit menu, everything works as intended.
I reported a bug, with reference 5DF8BSGI, as well as the reference itself (even though it appears to happen with all references) under 87HK7CT4.

**Comment by retorquere** [comment]
I can see in 5DF8BSGI that BBT has correctly generated the reference. Does ctrl+shift+c work with the standard Zotero BibTeX export?

**Comment by hagenblix** [comment]
Ah, that seems to cause the same issue, so I suppose it's a problem with zotero itself, rather than the plugin; sorry for not checking that earlier!

**Comment by retorquere** [comment]
That's ok, that's why I asked.
