### ISSUE TITLE
Zotero select links broken

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#984]
BBT seems to be not including the library ID in zotero select links, so they don’t work. 

Here is the working code from Zutilo for generating select links:

```
copyZoteroSelectLink: function() {
        var zitems = this.getSelectedItems();
        var links = [];

        if (!this.checkItemNumber(zitems, 'regularNoteAttachment1')) {
            return false;
        }

        var libraryID;
        for (var ii = 0; ii < zitems.length; ii++) {
            libraryID = zitems[ii].libraryID ? zitems[ii].libraryID : 0;
            links.push('zotero://select/items/' +
                       libraryID + '_' + zitems[ii].key);
        }

        var clipboardText = links.join('\r\n');

        this._copyToClipboard(clipboardText)

        return true;
    },
```

**Comment by retorquere** [comment]
Will `1` always work for the user library, even if the user library is synced?

**Comment by bwiernik** [comment]
Yes, the user library is always `1`, but why not just let Zotero tell you what the `libraryID` for each item is?

**Comment by retorquere** [comment]
I seem to recall that the user library Id changes once you start syncing your library, but I am not passed the libraryID in the translator (which is where I am generating the links) nor can I access the userlibraryid. I can access the group id for group library items from the item uri, but it's simply "local" for user library items. I'll probably pass in userlibraryid in the exporter sandbox piercer I already have, but if it's not required, I'd rather not.

**Comment by bwiernik** [comment]
No, that doesn't work for Group libraries. The groupID on zotero.org and the libraryID for groups in the local client are not the same. The zotero.org groupID would work for creating Zotero URIs (e.g., https://www.zotero.org/groups/250396/items/RFGEMQ4C), but it doesn't work for Select links for the local client.

Here is an example for a group library item:
BBT: zotero://select/items/250396_RFGEMQ4C
Zutilo: zotero://select/items/12_RFGEMQ4C

The userlibrary will always be `1`, but the group libraries you would need to get libraryID.

**Comment by retorquere** [comment]
Oy. Seriously? Then I'm just going to go with the item ID. If the links are not globally valid anyhow, there's no point in making it more complicated. I do have access to the item ID.

**Comment by bwiernik** [comment]
I'm not sure what you mean. In order for the Select links to work, they need to have a libraryID–itemID pair seprated by `_`. Links that only use the itemID don't work.

**Comment by retorquere** [comment]
The underscore separated id is actually the item key. The internal numeric ID still works.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.146.7028](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.146.7028.xpi) ("why are my test cases all wonky all of a sudden?").

**Comment by retorquere** [comment]
Can you try 7028? The zotero links have never worked for me, so I can't test them.

**Comment by bwiernik** [comment]
Yes, they seem to be working with both My Library and Group Library items.

**Comment by mijalche** [comment]
I think that the update to solve this problem, broked the solution at #769 . The previous solution was 
zotero://select/items/bbt:%@ and when I replace %@ with the citation key (for example Lewin.etal.16.c) it opens the reference in Zotero. Now it cannot do that. Is there something I need to change in the link?
Thanks!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.151.7201](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.151.7201.xpi) ("adds bbt:... select-link").

**Comment by mijalche** [comment]
installed the test build andI tested it with my existing settings, but again it does not select the appropriate reference in Zotero

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.151.7204](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.151.7204.xpi) ("select-link debugging").

**Comment by retorquere** [comment]
Can you install 7204, turn extended debugging on, use a select-link, then send a BBT error report? Unfortunately I can't test this myself as I've never gotten the select links to work, not even the Zotero standard ones.

**Comment by mijalche** [comment]
the ID report is F3KLA2SA

**Comment by retorquere** [comment]
Again with 7210 please?

**Comment by mijalche** [comment]
the ID is 75R5U3W5 
7210 solves the problem for selecting the right reference in My Library, however it does not work for Group libraries. 
Ffor group libraries is zotero://select/items/bbt:{2301676}%@ where {2301676} is my Group library ID.

**Comment by mijalche** [comment]
when I right click on group library and select `Show BibLaTeX server URL` I get the 2301676 as the internal library ID. Maybe I need to reset the internal ID number?

**Comment by mijalche** [comment]
on Zotero web site the group library ID for the same group library is 364499

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.151.7213](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.151.7213.xpi) ("decodeURIComponent").

**Comment by mijalche** [comment]
Report ID for 7213 is 64UACMAS

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.151.7216](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.151.7216.xpi) ("library ID is integer").

**Comment by mijalche** [comment]
Report ID for 7216 is HQ6DC5Y4

**Comment by bwiernik** [comment]
This is an attempt to use a Citekey select link in 7216: XLRU42ZK

Works for me.

**Comment by mijalche** [comment]
hm, strange, I do not know why it is not shown the report.
However, now I tried to recreate the error and the link was working for group libraries. The report is 3M89QJK4. Before I did this test I cleared the Full-text cache. 
In any case 7216 works for me

**Comment by retorquere** [comment]
thanks for the confirmation

**Comment by scottmartincampbell** [comment]
I'm having the original problem of this issue. In particular, I'm using the org-mode quick copy export, but org-mode with org-zotxt cannot open these new select links.

Is there any way to go back to the previous behaviour, which has worked for me for years, and the same as Zutilo?  Perhaps another variation for the translator?

**Comment by retorquere** [comment]
What does the link you got look like?

**Comment by retorquere** [comment]
Which org-mode quick-copy do you use btw? There are two now.

**Comment by scottmartincampbell** [comment]
The link is either zotero://select/items/@[bbt-key] or zotero://select/items/12618. Neither work for me in org mode or cutting and pasting to firefox. For what it's worth, I'm using Ubuntu. 

What does work and has worked is the previous format with the item id. Eg: zotero://select/items/H4JIVI5R (or zotero://select/items/1_H4JIVI5R to indicate the user library).  Is it possible to have a third org-mode quick-copy that uses the old format?

**Comment by retorquere** [comment]
The library ID (which is the leading number in the underscore-separated format) isn't available to translators, so I can't do that without patching zotero methods (which I do when necessary, but I try to keep it to a minimum.

The one with just a number is not something I add, that's one of the zotero-supported ones. That one should always work.

**Comment by retorquere** [comment]
FWIW I've never gotten select links of any form to work on Linux, so I can't test myself. But the bare-number one should just work if I look at the zotero code. It's not the preferred format (according to comments in the code), but it's there.

**Comment by retorquere** [comment]
With 'bare-number' I meant zotero://select/items/12345 (which is actually a very old format rather than new); zotero://select/items/ABCD1234? (or items/1_ABCD1234, which is technically the same thing) is the new. The preferred is the new.

I don't know how zotxt is involved; I'd prefer another way to test that doesn't involve helpers. Should links just work from the browser? I always assumed they should (but again, I can't test). Since others have reported the current links work, I'd like to get that working first - any format in fact.

**Comment by retorquere** [comment]
Problem is that translators aren't given the library ID, so I can't produce the new-style links from the quick copy translator. I don't know what zotxt does to make the links work but I'd argue that at least the itemID link (the old style but still supported, the one with only numbers) should be supported in addition to the new style (itemKey, with the alphanumeric IDs). I can't fault zotxt for not supporting the bbt-style select links, which will only work when bbt is installed.

**Comment by scottmartincampbell** [comment]
Can the translator still produce the new-style links without the library ID? As in: zotero://select/items/ABCD1234. Because that does still work in org-mode (with zotxt) and has worked until recently. 

I realize it's not ideal because without the library ID group libraries won't work. But unless I can convince the zotxt author to update and support bbt style links or the older bare-number style (or do it myself), I'm stuck.

**Comment by retorquere** [comment]
I don't have access to my dev system right now; when I do I can take a look, but I want to stress here that the only "bbt-style" link is the one with @. The other ones are just native zotero-style links, and they work with or without bbt.

**Comment by retorquere** [comment]
I've taken a look at org-zotxt and I see no reason why the old-style links (`zotero://select/items/<number>`) wouldn't automatically be supported.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.182.7968](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.182.7968.xpi) ("Merge branch 'master' into 984").

**Comment by retorquere** [comment]
Can you try 7968?

**Comment by scottmartincampbell** [comment]
That works great.

Thanks!

**Comment by retorquere** [comment]
You will probably still want to report to the zotxt author.
