### ISSUE TITLE
Move context menu items to submenu

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#985]
BBT adds 5 items to the Zotero item context menu, several of which I suspect most users never use (e.g., citation links, reporting BBT errors). I imagine that most users only use any of these functions on occasion. It's a bit annoying to me to have so many items that I never use added to the context menu.

Would you be okay with moving the item context menu options to a Better BibTeX sub menu? What about moving the Report BBT Errors option to the Help menu, where Zotero's own error reporting is? If you're okay with that, I can make a PR to do that.

**Comment by retorquere** [comment]
I'm ok with moving them to a submenu, but wrt the error reporting option, that already lives on the help menu but it does something else there. The error report from the help menu only submits the error log, the one from the context menu sends the error report + the selected items. I'd sooner remove the one in the help menu than the one in the context menu. I usually need a copy of the items to do any real debugging, plus it gives me new test cases to prevent regressions.

**Comment by retorquere** [comment]
The file names with colons have been changed on master

**Comment by bwiernik** [comment]
Can you also change `aux.md` to `aux-scanner.md` (or I can do that).

**Comment by retorquere** [comment]
done (but renaming files of the website needs to be done in tow places to have the navigation work)

**Comment by bwiernik** [comment]
Yeah, saw that. Thanks!
