### ISSUE TITLE
Export problem with multiple authors and prefixes

### ISSUE THREAD

**Issue by SolidTux** [retorquere/zotero-better-bibtex#987]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [X] If I am posting an export-related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

# Bug classification

## Exporting references

When exporting BibLaTeX with an entry with an author with prefix (e.g. "von ...") and multiple authors (e.g. [this paper](https://www.sciencedirect.com/science/article/pii/S0921453499000660?via%3Dihub), report ID TCZFA5E9) the resulting file results in errors with LuaLaTeX:

```
Too many commas in name 2 of "Andersen, N.H and family=Zimmermann, given=M., prefix=von, useprefix=true and Frello, T and K{\"a}ll, M and M\o{}nster, D and Lindg\aa{}rd, P.-A and Madsen, J and Niem{\"o}ller, T and Poulsen, H.F and Schmidt, O and Schneider, J.R and Wolf, Th and Dosanjh, P and Liang, R and Hardy, W.N" for entry Andersen1999
while executing---line 2633 of file biblatex.bst
```

This can be fixed, by wrapping the part of the second author in `{...}`.

**Comment by retorquere** [comment]
this looks like you have `biblatexExtendedNameFormat` on. Are you processing this with biber 2.7/biblatex 3.5 or later?

**Comment by SolidTux** [comment]
Ah, I accidently had biblatex as backend, with biber it is now working.
