### ISSUE TITLE
Disable BibLaTeX URL option for Feed libraries

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#989]
The contents of the Feeds libraries aren't stable, so the BibLaTeX URL server should probably be disabled there.

**Comment by retorquere** [comment]
I don't understand.

**Comment by bwiernik** [comment]
Zotero's Feeds feature: https://www.zotero.org/support/feeds

Internally, Feeds are just a special kind of Library, so the BibLaTeX URL option shows up on the Feed context menu. This is probably a bad idea to offer to users, as the contents of that feed library is not stable (it changes whenever the RSS feed changes). So the BibLaTeX URL menu items should be suppressed when the Library being selected is a feed.

**Comment by retorquere** [comment]
Do you have a sample feed I could test this with?

**Comment by bwiernik** [comment]
https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=10869&channel-name=Journal+of+Business+and+Psychology

**Comment by retorquere** [comment]
It'd seem useful to disable BBT on this, but I'm not sure how to go about it. I can add static elements to the context menu but not dynamic ones (that I know of), so it's currently on or off for everything.

**Comment by bwiernik** [comment]
You can set the `hidden` property on menu items in the JS. 

Zotero builds a `show` vector for different types of collections:
https://github.com/zotero/zotero/blob/2a7f31813e4ddffbc6f316851b59c93cffd7e8a1/chrome/content/zotero/zoteroPane.js#L2620

Then unhides only the menus listed in `show`:
https://github.com/zotero/zotero/blob/2a7f31813e4ddffbc6f316851b59c93cffd7e8a1/chrome/content/zotero/zoteroPane.js#L2733

**Comment by retorquere** [comment]
Right but that function doesn't know about the existence of BBT.

**Comment by bwiernik** [comment]
In addition to feeds, would also seem reasonable to disable this option on the Trash, Duplicate Items, and maybe Unfiled Items?

**Comment by retorquere** [comment]
Reasonable, yes.

**Comment by bwiernik** [comment]
> Right but that function doesn't know about the existence of BBT.

But you could write a similar function controlling the BBT menus, ala:
```if (collectionTreeRow.isFeed()) {
  document.getElementById('better-bibtex.biblatex-server-url').setAttribute('hidden', false);
  document.getElementById('better-bibtex.report-errors').setAttribute('hidden', false);
}

**Comment by retorquere** [comment]
But when would it run?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.148.7141](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.148.7141.xpi) ("simpler test for submenu visibility").

**Comment by retorquere** [comment]
Alright, give 7141 a spin.

**Comment by bwiernik** [comment]
Still showing up on Feeds, but not Trash, Unfiled Items, or Duplicate Items. It's also not showing up on Saved Searches or My Publications–was that intentional? Those might be okay to have the option?

When the options are hidden, the menu separator is still there. That should be hidden too by giving it an `id`.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.148.7144](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.148.7144.xpi) ("more targeted tests for collection menu").

**Comment by retorquere** [comment]
OK, try 7144

**Comment by bwiernik** [comment]
Looks good!
