### ISSUE TITLE
Better BibTeX disregards "Export unicode as plain-text latex commands" Setting

### ISSUE THREAD

**Issue by avonmoll** [retorquere/zotero-better-bibtex#991]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [x] If I am posting an export-related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

# Bug classification

## Exporting references (Better BibTeX)

**Report ID: DGQVCGB8**

I'm trying to export a reference using Better BibTeX. I have _Export unicode as plain-text latex commands_ **unchecked**. The reference contains information in the Extra field: `\url{https://google.com}` (but with a real URL). I understand there is a setting to export URL field as a note, but I only want to include a URL for this particular reference (and none of the others I'm exporting). When I do the export, I get:

```
...
note = {$\backslash$url\{https://google.com\}}
...
```

I was under the impression that unchecking _Export unicode as plain-text latex commands_ would cause BBT to pass the text through verbatim. The output is the same whether the option is checked or unchecked.

**Comment by retorquere** [comment]
That setting only means that unicode characters are not replaced by latex equivalents. If you want raw latex, look at [these options](https://retorque.re/zotero-better-bibtex/advanced/#you-are-a-hardcore-latex-user).

**Comment by retorquere** [comment]
You can also [add your own fields](https://retorque.re/zotero-better-bibtex/customized-exports/#add-your-own-biblatex-fields).

**Comment by retorquere** [comment]
Does this cover your question?

**Comment by avonmoll** [comment]
The use of `<pre>...</pre>` ended up being exactly what I was looking for. Thank you!

**Comment by retorquere** [comment]
You're welcome.
