### ISSUE TITLE
One-word journal names not wrapped in braces on BibTeX export

### ISSUE THREAD

**Issue by gimber** [retorquere/zotero-better-bibtex#999]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export-related bug report, I have included an error-report by right-clicking the problematic reference and submitting an BBT error report

When exporting to BibTeX, it seems that one-word journal names are not wrapped in braces. (I understand that either braces or quotation marks are required by the [BibTeX format](http://www.bibtex.org/Format/).) When I use `natbib` to generate a bibliography, this means that the journal name is not displayed in the references list. Error report ID: 8PCS9882. I've attached a minimum working example: [LaTeX code](https://github.com/retorquere/zotero-better-bibtex/files/2128819/mwe.txt) and [PDF output](https://github.com/retorquere/zotero-better-bibtex/files/2128821/mwe.pdf). Possibly related to [this previously fixed issue](https://github.com/retorquere/zotero-better-bibtex/issues/5#issuecomment-28898677)?

Thanks so much for making zotero-better-bibtex - it's extremely useful!

Andrew

**Comment by retorquere** [comment]
You have [this setting](https://retorque.re/zotero-better-bibtex/configuration/#assume-single-word-strings-to-be-externally-defined-string-vars-and-thus-not-surrounded-by-braces) on.

**Comment by gimber** [comment]
I've turned that setting off and it's working perfectly now. Thanks very much!

**Comment by retorquere** [comment]
Only I can close issues on this repo.

The setting is off by default BTW, so at one point you must have used this for something. But it's an export setting for people with very specific needs (external @string vars).
